### ISSUE TITLE
Delta API nextLink with $skiptoken return 404 code:UnknownError

### ISSUE THREAD

**Issue by rdtsai** [microsoftgraph/microsoft-graph-docs#1000]
[Same issue reported on stackoverflow](https://stackoverflow.com/questions/42450276/microsoft-graphapi-users-delta-endpoint-returns-404/42451021#42451021)

**Http Request**
GET /beta/groups/delta?$skiptoken=_a_very_long_token_returned_by_delta_api_
Authorization: Bearer _a_working_access_token_
Host: graph.microsoft.com

**Response**
HTTP/1.1 404 Not Found
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json
request-id: 9d196b62-8492-49f9-b634-77849273442f
client-request-id: 9d196b62-8492-49f9-b634-77849273442f
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Central US","Slice":"SliceB","ScaleUnit":"000","Host":"AGSFE_IN_5","ADSiteName":"CHI"}}
Preference-Applied: odata.track-changes
Duration: 171.1846
Date: Mon, 27 Mar 2017 18:24:37 GMT
Connection: close

{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "9d196b62-8492-49f9-b634-77849273442f",
      "date": "2017-03-27T18:24:37"
    }
  }
}

**Comment by AveAdam** [comment]
Same issue with me.
When will fix it?

**Comment by palmtown** [comment]
+1 I am getting the same exact error... @microsoft let's fix this ASAP please, it was reported almost 1.5 months ago and users are still experiencing this issue.  Tech is moving at a rapid pace, please keep up as you're slowing us down.

**Comment by jesakowi** [comment]
We've made a fix for this issue and are in the process of rolling it out. This should be complete in the next few days.

**Comment by palmtown** [comment]
Thanks for the update jesakowi, much appreciated and will look forward to your updates.

**Comment by jesakowi** [comment]
This is fixed now. Let us know if you have any more issues, or if you have feedback on the capability.

**Comment by palmtown** [comment]
First and foremost, thank you for looking into this issue.  Secondly, I have verified this feature is now working as expected.  Third, it was the last issue that prevented us from fully migrating off the Azure Active Directory Graph API for any of those who are questioning if it is possible or not--it all possible.
