### ISSUE TITLE
Create Teams example with owners@odata.bind do not work.

### ISSUE THREAD

**Issue by kjhughes097** [microsoftgraph/microsoft-graph-docs#10031]
Not sure if this is a documentation issue or a Graph API bug - but the example of creating a Team with an owner specified does not work.
Replicated it in Graph Explorer. It returns a 'BadRequest' error with the message 'Invalid bind property name owners in request'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@kjhughes097 , Document needs to updated for this, You can try below piece of request to run this API

```
{
"template@odata.bind":"https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
"displayName":"My Sample Team",
"description":"My Sample Team’s Description",
"members":[{
"@odata.type":"#microsoft.graph.aadUserConversationMember",
"roles":["owner"],
"user@odata.bind":"https://graph.microsoft.com/beta/users('userId')"
}]}
```

**Comment by Prasad-MSFT** [comment]
@tamerdaif - We followed the steps mentioned in this doc(https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#example-4-create-a-team-from-group) and were able to create a Team from a group

**FYI, The team that's created will always inherit from the group's display name, visibility, specialization, and members. Therefore, when making this call with the group@odata.bind property, the inclusion of team displayName, visibility, specialization, or members@odata.bind properties will return an error.**

Steps followed:
1. Create a group(https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#example-1-create-a-microsoft-365-group)
![image](https://user-images.githubusercontent.com/62237649/171856852-2a55b217-1653-4a47-b865-044a518cc36e.png)

2.Create a team from group(https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#example-4-create-a-team-from-group)
![image](https://user-images.githubusercontent.com/62237649/171856981-8cde6668-db09-4998-bd67-68d331a69d9a.png)
