### ISSUE TITLE
Policy.ReadWrite.ApplicationConfiguration Application Permission is missing

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/microsoft-graph-docs#10040]
Policy.ReadWrite.ApplicationConfiguration Application Permission is missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ryanspletzer for raising this issue. I've raised a PR to update the page. Closing this issue.
