### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by divasinbox** [microsoftgraph/microsoft-graph-docs#10071]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd1927e-32a6-871d-25e7-e83622ba388e
* Version Independent ID: 1ae3e429-4c05-1663-d8e7-08ae3d36a9d4
* Content: [Download printDocument binary file - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/printdocument-get-file.md)
* Product: **universal-print**
* Technology: **microsoft-graph**
* GitHub Login: @braedenp-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by braedenp-msft** [comment]
No feedback content was entered. Please open a new issue with a question or suggestion.
