### ISSUE TITLE
Extra permission for /me/memberOf needed for hidden groups

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/microsoft-graph-docs#10109]
The `/me/memberOf` endpoint of the v1 and beta seem to not return the groups with the privacy setting `HiddenMembership`.

1. Can this be solved by adding the delegated persmission **Member.Read.Hidden**?
2. Is there some other way to enable this?
3. It either isn't possible to get groups the current user is a member of with the privacy set to HiddenMembers or it isn't documented.

The only place mentioning this new extra scope is [Add Student](https://docs.microsoft.com/en-us/graph/api/educationclass-post-members?view=graph-rest-1.0&tabs=http) in the Education part of the api  (that I could find using the default search). So this might be a hidden feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42dfe6b6-0866-c127-c8a6-230399f99761
* Version Independent ID: 040281fe-21b5-6435-3b4e-8bcb1fd0fe4a
* Content: [List memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-memberof.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svrooij** [comment]
@krbain is there a way we can use to speed up the solution for this issue?

**Comment by FaithOmbongi** [comment]
Hello @svrooij ,

Apologies for the delayed response. Our Engineering team was not able to reproduce this issue. With Directory.Read.All permission, you should be able to view the membership of hidden groups using the /me/memberOf endpoint.

Could you retry and also confirm the permission you are using?

**Comment by svrooij** [comment]
I will check this later today, but to be totally clear: The tenant we where testing on is an education tenant, I don't think the privacy settings `HiddenMembership` are available in a regular tenant. You also cannot change a normal group to this privacy setting (is that correct?)

Are you sure you've tested against an educational tenant with this privacy settings enabled for that specific group?

**Comment by FaithOmbongi** [comment]
To answer your questions:

1. Yes, we've tested on an Education tenant. 
2. You can set `HiddenMembership` on a regular tenant.
3. You can only set `HiddenMembership` on create, not update.

Please see below an extract from our latest run. I hope this helps.

```
{
            "@odata.type": "#microsoft.graph.group",
            "id": "2e8581c3-ff81-4be1-a920-dacd08dbfb1c",
            "deletedDateTime": null,
            "classification": null,
            "createdDateTime": "2021-02-27T06:39:11Z",
            "creationOptions": [
                "Team",
                "classAssignments",
                "ExchangeProvisioningFlags:2509"
            ],
            "description": "Welcome to Physical Science!",
            "displayName": "Physical Science",
            "expirationDateTime": null,
            "groupTypes": [
                "Unified"
            ],
            "isAssignableToRole": null,
            "mail": "PhysicalScience@contoso.com",
            "mailEnabled": true,
            "mailNickname": "PhysicalScience",
            "membershipRule": null,
            "membershipRuleProcessingState": null,
            "onPremisesDomainName": null,
            "onPremisesLastSyncDateTime": null,
            "onPremisesNetBiosName": null,
            "onPremisesSamAccountName": null,
            "onPremisesSecurityIdentifier": null,
            "onPremisesSyncEnabled": null,
            "preferredDataLocation": null,
            "preferredLanguage": null,
            "proxyAddresses": [
                "SPO:SPO_567c98c4-d60c-41f3-9c38-ac879f1a3ae9@SPO_643f4266-f42e-47e0-a7f1-34d1017d89b8",
                "SMTP:PhysicalScience@contoso.com"
            ],
            "renewedDateTime": "2021-02-27T06:39:11Z",
            "resourceBehaviorOptions": [
                "HideGroupInOutlook",
                "WelcomeEmailDisabled",
                "ConnectorsDisabled",
                "SubscribeNewGroupMembers"
            ],
            "resourceProvisioningOptions": [
                "Team"
            ],
            "securityEnabled": false,
            "securityIdentifier": "S-1-12-1-780501443-1273102209-3453624489-486267656",
            "theme": null,
            "visibility": "HiddenMembership",
            "extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType": "Section",
            "onPremisesProvisioningErrors": []
        }
```

**Comment by FaithOmbongi** [comment]
I trust this issue is now resolved.
