### ISSUE TITLE
Is it attribute preferredSingleSignOnMode only affected at beta?

### ISSUE THREAD

**Issue by berviantoleo** [microsoftgraph/microsoft-graph-docs#10105]
Hi, I see the `preferredSingleSignOnMode` only at beta properties. When I try to v1.0 API, seems it is also not have any problem. Here is my query:

```bash
curl --location --request PATCH 'https://graph.microsoft.com/v1.0/servicePrincipals/<principal-id>' \
--header 'Authorization: Bearer ....' \
--header 'Content-Type: application/json' \
--data-raw '{
    "preferredSingleSignOnMode": "saml",
    "notificationEmailAddresses": ["<my-valid-email>"]
}'
```

some value I already hide because sensitive information. The response of API also bring me 204. It also bring me 204 when bring `preferredSingleSignOnMode` only. How I know that API also worked in v1.0? Is it already can use the parameter `preferredSingleSignOnMode` in v1.0? If yes, can we update the docs?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c964cc2-808d-9cbf-0a1f-778b1017531d
* Version Independent ID: a7dc4262-533e-b866-e2c1-0663e7090dcb
* Content: [Update serviceprincipal - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/serviceprincipal-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hello @berviantoleo ,

Thank you for your feedback. Yes, you're correct. The **preferredSingleSignOnMode** parameter can be updated in v1.0 also. I'll update the page to reflect this.

If you need to confirm that the API worked, run GET on servicePrincipal. Kindly see the example on the [get servicePrincipal](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-1.0&tabs=http) page.

`GET https://graph.microsoft.com/v1.0/servicePrincipals/{principal-id}`

**Comment by berviantoleo** [comment]
Hi @FaithOmbongi ,

Thank you for the confirmation.

Cool, I think the documentation already updated as well.

![image](https://user-images.githubusercontent.com/15927349/108586285-fb5aba00-737f-11eb-82de-4ee83feb0924.png)

It's good news.

I will close this since the docs already updated.
