### ISSUE TITLE
Get all Terms of a Termset as plain list

### ISSUE THREAD

**Issue by MrTantum** [microsoftgraph/microsoft-graph-docs#10108]
In the past it has been possible to load all terms of a termset in a flat list using a single call by executing the [TermSet.GetAllTerms](https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.termset.getallterms) method.

**Is there a similar parameter for the _List children_ endpoint (e.g. `/children/all`)?**

When using `https://graph.microsoft.com/beta/termStore/sets/{TermSetId}/children` this seems to only return the terms of the first level of terms. 

Therefore multiple api calls would have to be made to get all terms of termset **which can cause huge server load depending on the size of the termset**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 882ae83e-c747-d528-b083-afc9ce59d259
* Version Independent ID: 91eda749-2150-2a0f-4bed-973f9be60b9b
* Content: [List children - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/termstore-term-list-children?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/termstore-term-list-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/termstore-term-list-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @mohitpcad
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vishriv** [comment]
@MrTantum For fetching all children under a termset, you have to call this API : https://graph.microsoft.com/beta/sites/{site-id}/termStore/sets/{set-id}/terms

**Comment by vishriv** [comment]
Hi @MrTantum , API for fetching all children under a set or a term is not currently in the plan. That will be enabled sometime in the future.
