### ISSUE TITLE
isFavoriteByDefault property is only available in Beta

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-docs#10145]
Couple of snippets do not compile because `isFavoriteByDefault` is only available in Beta. Can that property be removed from HTTP samples until the property gets published to v1.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=csharp&viewFallbackFrom=graph-rest-v1.0)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zengin** [comment]
I have just seen that the following message appears at the top:
```
 The requested page is not available for graph-rest-v1.0. You have been redirected to the newest product version this page is available for.
```

I will need to figure out a way to exclude these pages from v1.0 snippet compilation tests.

**Comment by zengin** [comment]
The message above was showing up because I was generating a malformed url in my tool. Sorry about my confusion.

[The v1.0 documentation](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=csharp&viewFallbackFrom=graph-rest-v1.0) has the properties that are not GA'd yet, so the initial issue report still holds hence reopening.

**Comment by Manish-MSFT** [comment]
Hi @zengin, Did you get any errors while using the property "isFavoriteByDefault" for v1.0? I just tried using "/v1.0/teams" to create teams using "isFavoriteByDefault" and is see there are no issues.

**Comment by zengin** [comment]
Hi @Manish-MSFT, for our SDK generation the source of truth is the metadata published here: https://graph.microsoft.com/v1.0/$metadata. Published metadata doesn't have `isFavoriteByDefault` property.

We are also generating C# snippets using the HTTP snippets, and we can't compile the snippet with `isFavoriteByDefault` property because SDK doesn't have it.

It seems like, when called directly with HTTP, the service is either 
1. Ignoring the extra property or 
2. It consumes the property but that feature is not reflected in the metadata.

If it is # 2, the issue can also be resolved by publishing the property in the metadata.

**Comment by darrelmiller** [comment]
@Manish-MSFT We must not include properties in examples that are not documented and not described in metadata.  These properties may change before GA and that would be a breaking change that we do not allow.  The fact that the API currently accepts the property is not sufficient reason for being able to include it in an example.

**Comment by Manish-MSFT** [comment]
Hi @zengin, We have notified respective team regarding the above issue and it will be corrected in next sprint.

**Comment by zengin** [comment]
I have confirmed that `isFavoriteByDefault` property has GA'd, so there is no need to fix the docs anymore.
