### ISSUE TITLE
Incomplete Documentation

### ISSUE THREAD

**Issue by Andy65** [microsoftgraph/microsoft-graph-docs#10175]
The documentation for the isActive property is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ece84fa7-6592-bbe3-34e4-757590e07241
* Version Independent ID: 44df91bc-bc49-dfa4-2ad5-1782dbe22550
* Content: [shiftItem resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/shiftitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/shiftitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/shiftitem.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@Andy65 , Where you are getting the `isActive `property, I checked this in graph explorer response, it doesn't return `isActive`. 
![image](https://user-images.githubusercontent.com/50989436/95547227-160b4280-0a20-11eb-9780-3bb16c3543fb.png)

Could you please explain bit more about document issue?

**Comment by Andy65** [comment]
Yes, apologies I was confusing the ShiftItem that is returned as part of a shift with the shift change data that is sent with a workforce integration (it includes an additional isActive property) - I will close the issue.
