### ISSUE TITLE
Search API doesn't return drive id for drive items

### ISSUE THREAD

**Issue by mechanik0s** [microsoftgraph/microsoft-graph-docs#10173]
I found big problem with search api:
Now it return only `siteId` in `parentReference`, but unfortunately it's absolutely useless if your site contains more than one drive.
Documentation for ["get drive item resource"](https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http) describes `/drives/{drive-id}/items/{item-id}` request and `driveId` is mandatory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files#feedback)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmoreau** [comment]
Ack. 
Thank you for this very useful feedback. The query works are long as the Site has a single DocLib.
Let me get back to you on this when there are multiple DocLibs.

**Comment by mechanik0s** [comment]
Thanks for your reaction @nmoreau !
But query successfully find files in all libs, I checked it. The only problem that you can't do anything with this found file.
So,

**Comment by nmoreau** [comment]
We have identified the issue and have a plan for a fix for this.
This fix should be landing in WW on 10/27.
Thank you for your patience.

**Comment by nmoreau** [comment]
FYI the code change has landed in Production.
Every DriveItem now gets a driveId in the SharePointids property.
Thank you for raising this. We are also working to add most of the SharePointids we know about in there.
