### ISSUE TITLE
swapShiftsChangeRequest: approve - Microsoft Graph v1.0 / Response type issue

### ISSUE THREAD

**Issue by ajs117** [microsoftgraph/microsoft-graph-docs#10178]
At first it says this API should return a 200 then in the example it says it should return a 204.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414c6235-d477-924c-5403-b59bac765275
* Version Independent ID: 67c2391c-d079-c076-8a36-aaf8d22877ee
* Content: [swapShiftsChangeRequest: approve - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/swapshiftschangerequest-approve?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/swapshiftschangerequest-approve.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/swapshiftschangerequest-approve.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@AkJo - Could you please update the 204 NO CONTENT response code [here](https://learn.microsoft.com/en-us/graph/api/swapshiftschangerequest-approve?view=graph-rest-1.0&tabs=http#response).

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/92150070/04c438dc-6d10-4246-970d-0516ad41ef6f)
