### ISSUE TITLE
Unlisted error received

### ISSUE THREAD

**Issue by tbreamgh** [microsoftgraph/microsoft-graph-docs#10180]
I received an error message with the code ErrorInvalidUser. However, this does not appear to be listed on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77cc3520-96d8-6aa4-1243-20b7f4d5c4cb
* Version Independent ID: 79a31ea9-d9b3-2602-e412-4959498a11c0
* Content: [Microsoft Graph error responses and resource types - Microsoft Graph](https://docs.microsoft.com/en-us/graph/errors)
* Content Source: [concepts/errors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/errors.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@baywet not sure if you are the right person who can take a look at this issue. If not, do you happen to know who might be able to help? Thanks.

**Comment by baywet** [comment]
@lramosvea I believe this should fall under the OData lib responsibilities so @mumbihere or someone from her team.

But this error is probably returned by a workload specifically. @tbreamgh Sorry about the late reply on this. Do you remember which URL you were querying when you received this error?
