### ISSUE TITLE
Sharepoint site is not created on private channel creation via graph.

### ISSUE THREAD

**Issue by ValerasNarbutas** [microsoftgraph/microsoft-graph-docs#10206]
good day, 
graph query /teams/{id}/channels/{id}/filesFolder works fine but only if:
1. private channel created 
2. Team member clicks "files" tab in a channel.

Otherwise sharepoint for private channel is not created and no automatic provisioning can be done on private channel default document library. Is were any workaround on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3914d7e5-bbb3-b349-893c-ef01c2938981
* Version Independent ID: 15bc6db6-36cd-cc2b-2b9c-34c30141b89c
* Content: [Get filesFolder - Microsoft Graph v1.0](https://docs.microsoft.com/en-US/graph/api/channel-get-filesfolder?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-get-filesfolder.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by qquiuc** [comment]
Hi  Team

We also found that if the private channel was created by the application token, the sharepoint site will not be created unless some one click the files tab in the channel in the GUI. but the private channels created through delegate permission work fine.

Thanks

**Comment by ValerasNarbutas** [comment]
> Hi Team
> 
> We also found that if the private channel was created by the application token, the sharepoint site will not be created unless some one click the files tab in the channel in the GUI. but the private channels created through delegate permission work fine.
> 
> Thanks

hey @qquiuc ,
I noticed one more thing, if parent team is "class" template private channels are created with SP site with no issue, but if in teams parent team was created "Other" option it fails. This is with educational licence.

**Comment by Jeroen00** [comment]
Also working on the same issue. There is a difference between Edu and Ent tenants and the template you use. In Ent the SP private channel sites are created right away if you create a Team based on an existing Team (template). If you create the Team from scratch the SP private channel sites are only created after clicking Files. 

In Edu you are not getting SP private channel sites without clicking on Files first if you use the Edu 'Other' Teams template. But if you use one of the other three available Edu Teams templates, the sites are created right away!

Very confusing behaviour...

**Comment by VaraPrasad-MSFT** [comment]
This is current behavior of the system, there is no work around for now.

**Comment by hitesh-bansal** [comment]
> Hi Team
> 
> We also found that if the private channel was created by the application token, the sharepoint site will not be created unless some one click the files tab in the channel in the GUI. but the private channels created through delegate permission work fine.
> 
> Thanks

Hi @qquiuc , Is there any way to get the site id of private channel unless click on the files tab using the delegate permission?

**Comment by ValerasNarbutas** [comment]
> This is current behavior of the system, there is no work around for now.

Hi @VaraPrasad-MSFT ,
it might be not entirely true,
Currently if I use Education teams with Parent team channel created from "Staff" template but not "Other" template, I can create private channels via graph and sharepoint sites are provisioned without clicking on "Files" in private channels.

One thing to note, if I use beta rest call to graph when id does not work and "files" must be clicked. If used version 1.0 works fine.
this works: https://graph.microsoft.com/v1.0/teams/{teamid}/channels
this works but sharepoint is not created : https://graph.microsoft.com/beta/teams/{teamid}/channels

**Comment by JvdH-NL** [comment]
> > This is current behavior of the system, there is no work around for now.
> 
> Hi @VaraPrasad-MSFT ,
> it might be not entirely true,
> Currently if I use Education teams with Parent team channel created from "Staff" template but not "Other" template, I can create private channels via graph and sharepoint sites are provisioned without clicking on "Files" in private channels.
> 
> One thing to note, if I use beta rest call to graph when id does not work and "files" must be clicked. If used version 1.0 works fine.
> this works: [https://graph.microsoft.com/v1.0/teams/{teamid}/channels](https://graph.microsoft.com/v1.0/teams/%7Bteamid%7D/channels)
> this works but sharepoint is not created : [https://graph.microsoft.com/beta/teams/{teamid}/channels](https://graph.microsoft.com/beta/teams/%7Bteamid%7D/channels)

@ValerasNarbutas and @VaraPrasad-MSFT : facing same kind of issue, creating new private channel in Team (using New-MgTeamChannel calls), private channel creation works like a charm, the SharePoint site is however not provisioned (until a user clicks on Files). Any hints/clues to get the provisioning of SharePoint site collection working?

**Comment by Abhijit-MSFT** [comment]
> > > This is current behavior of the system, there is no work around for now.
> > 
> > 
> > Hi @VaraPrasad-MSFT ,
> > it might be not entirely true,
> > Currently if I use Education teams with Parent team channel created from "Staff" template but not "Other" template, I can create private channels via graph and sharepoint sites are provisioned without clicking on "Files" in private channels.
> > One thing to note, if I use beta rest call to graph when id does not work and "files" must be clicked. If used version 1.0 works fine.
> > this works: [https://graph.microsoft.com/v1.0/teams/{teamid}/channels](https://graph.microsoft.com/v1.0/teams/%7Bteamid%7D/channels)
> > this works but sharepoint is not created : [https://graph.microsoft.com/beta/teams/{teamid}/channels](https://graph.microsoft.com/beta/teams/%7Bteamid%7D/channels)
> 
> @ValerasNarbutas and @VaraPrasad-MSFT : facing same kind of issue, creating new private channel in Team (using New-MgTeamChannel calls), private channel creation works like a charm, the SharePoint site is however not provisioned (until a user clicks on Files). Any hints/clues to get the provisioning of SharePoint site collection working?

@JvdH-NL: SharePoint site will get created when you hit Files after Channel creation. This is by design. As of now there is no way to get the SharePoint site provisioned by any other way.

**Comment by JvdH-NL** [comment]
> > > > This is current behavior of the system, there is no work around for now.
> > > 
> > > 
> > > Hi @VaraPrasad-MSFT ,
> > > it might be not entirely true,
> > > Currently if I use Education teams with Parent team channel created from "Staff" template but not "Other" template, I can create private channels via graph and sharepoint sites are provisioned without clicking on "Files" in private channels.
> > > One thing to note, if I use beta rest call to graph when id does not work and "files" must be clicked. If used version 1.0 works fine.
> > > this works: [https://graph.microsoft.com/v1.0/teams/{teamid}/channels](https://graph.microsoft.com/v1.0/teams/%7Bteamid%7D/channels)
> > > this works but sharepoint is not created : [https://graph.microsoft.com/beta/teams/{teamid}/channels](https://graph.microsoft.com/beta/teams/%7Bteamid%7D/channels)
> > 
> > 
> > @ValerasNarbutas and @VaraPrasad-MSFT : facing same kind of issue, creating new private channel in Team (using New-MgTeamChannel calls), private channel creation works like a charm, the SharePoint site is however not provisioned (until a user clicks on Files). Any hints/clues to get the provisioning of SharePoint site collection working?
> 
> @JvdH-NL: SharePoint site will get created when you hit Files after Channel creation. This is by design. As of now there is no way to get the SharePoint site provisioned by any other way.

Thanks for restating. This "unfinished design/implementation" ... from governance/architecture perspective we want to stapple/change document libraries of private channels before users start to work there (and this also blocks migration of documents to private channels,), anymway: I was hoping for some kind of fix/change in October/November timeframe (the 'only thing' I need is a Graph call that enables me to get the destinitation of a (private) channel provisioned.

**Comment by daniel-pfaeffli** [comment]
@Abhijit-MSFT will msft fix this issue or provide a workaround within a useful period? This is a big blocker for any ISV's.
Regards

**Comment by JvdH-NL** [comment]
@Abhijit-MSFT and @daniel-pfaeffli : any news/info about this?

**Comment by TheElectricCo** [comment]
Also very interested in seeing this issue fixed.

**Comment by daspionzor** [comment]
@VaraPrasad-MSFT @Abhijit-MSFT  We are also facing the same issue. This is currently blocking us from correctly creating private channels. It works when first creating the team through the Teams UI and then using the graph to create the private channels. We need this to work the same way when the team is created through the graph.

**Comment by Jeroen00** [comment]
Should be fixed by MSFT. Right now we are sending an email from Power Automate to an IT Admin to click the Files tab and kick off a second workflow to provision folders and metadata inside the Private channel. Doable for 1 private channel, not for multiple, but the private channel site should just automatically be created from Graph call.

**Comment by Trinetra-MSFT** [comment]
@ValerasNarbutas , Site will get created once user click on files tab in channel, currently this is expected behavior

**Comment by Jeroen00** [comment]
> @ValerasNarbutas , Site will get created once user click on files tab in channel, currently this is expected behavior

Expected maybe, but not logical or practical from an automation point of view of course!

**Comment by TheElectricCo** [comment]
@ValerasNarbutas : As @Jeroen00  states, we know it is the expected behaviour, but this is a nightmare to automate + a blocking issue i our company to move our data to Sharepoint online. Still would love to see this feature "enchanced"

**Comment by ValerasNarbutas** [comment]
> @ValerasNarbutas : As @Jeroen00 states, we know it is the expected behaviour, but this is a nightmare to automate + a blocking issue i our company to move our data to Sharepoint online. Still would love to see this feature "enchanced"

@TheElectricCo i do agree, maybe with new provisioning plans in teams it will be better :)

**Comment by gkumra** [comment]
Can someone confirm if this works/supported with graph delegated permission?

**Comment by odrouin** [comment]
Hey everyone I think I found a workaround for this issue. It seems like if you first make a call to the filesFolder endpoint on the primaryChannel of the team (the General channel), then the site will be provisioned for a private channel created afterward.

**Comment by acolom** [comment]
Hello @odrouin  that's true, if you request filesFolder for the channel, afterwards the site is provisioned. Unfortunately this is not the behavior if the same request is made as an app registration instead of a user. In that case the site is never provisioned

**Comment by avican** [comment]
Yeah the delegated permission workaround works. Seems like I had to do all of the steps as delegated:
- Create team (delegated permissions through custom connector)
- Get primaryChannel for the created team
- Get folderFiles for the primaryChannel (delegated permissions through custom connector)
- Create a new private channel for the team (delegated permissions through custom connector)
- wait one minute
- At this point the SharePoint site for the private channel should have been generated already. But I also request folderFiles for the private channel to verify

**Comment by GottemHams** [comment]
This behaviour is __unacceptable__. What's the entire point of using an API? That's right, to __automatically__ take care of things and not to have stuff only handled for 50% (creating a team and channel but not provisioning __any__ of the features? Who thought this was ever a good idea?). __Manually__ having to go into the team/channel and clicking a specific tab is completely backwards.

Using delegated permissions is __not an option__, it __must__ work with application permissions. It doesn't matter if the team and/or channel are set as public, private or whatever. It REFUSES to provision regardless.

Why does Microsoft always insist on delivering half-finished features?

**Comment by Nagesh29** [comment]
Anyone found any solution for this? I am not able to provision Excel tab to a private channel. When I am trying to copy my excel file to the https://siteurl-channelName/Shared Documents it throws an error that site does not exists.

**Comment by Jeroen00** [comment]
So far, haven't seen a good solution. We are using a manual in between step where someone clicks the files tab in the channel and waits until the site is created. After which the workflows continues provisioning the site. Not really acceptable so Microsoft should fix this. 

@Nikitha-MSFT  @VaraPrasad-MSFT  @Trinetra-MSFT  any updates on this?

**Comment by Nikitha-MSFT** [comment]
We have raised a bug. we are tracking internally, we don't have ETA to share when it will be fixed.

**Comment by Nagesh29** [comment]
Do we have any workaround atleast? Any other API call or something?

**Comment by Nagesh29** [comment]
@Nikitha-MSFT 
Do we have any workaround atleast? Any other API call or something?

**Comment by Nikitha-MSFT** [comment]
Bug is Resolved now, we have tested this at our end,Hence, we are closing this question for now. If you still face any issue please feel free to reopen the issue

**Comment by Jeroen00** [comment]
@Nikitha-MSFT  Thanks, good to hear. Does it take a while until we see this in our environments? I tested it just now but it is not yet working in an environment of one of our customers.

**Comment by Nikitha-MSFT** [comment]
We have tested in public version and the bug in fixed for environments? If you are still facing the issue please share the error details with client request id and timestamp.

**Comment by GottemHams** [comment]
I'm almost 100% certain that the alleged fix only works for channels created __after__ the fact? Like I have 8 channels that were created __before__ and all 8 of them still complain that "Folder location for this channel is not ready yet". Is this true?

**Comment by Nikitha-MSFT** [comment]
For old channels created before you need to go to UI and open the files folder then it will create the files folder in SharePoint. For newly created channels the folder will be created automatically in share point

**Comment by orty** [comment]
Hi @Nikitha-MSFT , we are also relying on the Graph API to create template-based teams, containing both public and private channels. So far, none of the `DriveItem`s are created (folder for a public channel, SP Site for a private one). 

Does your fix implies that this behavior will change and they will be automatically created again when provisioning a Team through the Graph API, or do we need to rely on the `/teams/{id}/channels/{id}/filesFolder` workaround ?

**Comment by Nikitha-MSFT** [comment]
For old channels created before you need to go to UI and open the files folder then it will create the files folder in SharePoint - this is the only work around.

**Comment by orty** [comment]
Thank you, although I am talking about future channels. I would like to know how our product should be adapted (if needed) to ensure the best experience to our customers ? So far, by my latest tests, when using App permissions the channels files storage are not populated at all (seen on several Tenants)

**Comment by GottemHams** [comment]
@orty In my case I'm simply doing a `GET` to `teams/$team_id/channels/$channel_id/filesFolder` to figure out the "drive ID", then using that I can create stuff. It sometimes may take a little while before the channel is fully provisioned, so until that happens you __will__ get `folder location is not ready yet`.

I'm not 100% sure if the `GET` is required before it gets provisioned, but it doesn't look like it.

**Comment by orty** [comment]
Thanks @GottemHams , I spent some time to try and develop the workaround.
In our case, our product gives the ability to choose whether to create the Teams using `delegated` or `application` permissions. 

It seems that with the `delegated` ones, everything is fully provisioned, from a single public channel folder to a whole private channel SP Site. But if you create the Team using `application` permissions, you are left with an empty document library, an inexisting SP Site, and the quite disturbing (from an end-user point of view) error message `We can't get your files. We are working on getting them back`.

So, what we did so far (after we found this very useful thread) is to issue a `GET` query to the `/teams/$team_id/channels/$channel_id/filesFolder` endpoint, always using the `delegated` permissions user token, to stimulate the provisioning of the required items (again, folder or SP Site). 

It seems to be working great (1 day old development, hope it will remain stable 🤞) but I would really like to know what exactly the "fix" issued by the MS Graph team was about. Provisioning automatically when creating a Team through the API using `delegated` permissions ? If so, seems to be working and rolled out to our Tenants. If not, please let me know if our workaround is supposed to be needed in the future or not.

Many thanks for your work !

**Comment by GottemHams** [comment]
Yeah, the message `We can't get your files. We are working on getting them back` is what I meant with `may take a little while before the channel is fully provisioned`. At that stage, the error you'll get through the API is `folder location not ready`. You'll likely still get that even with the fix by MS, that's why my code keeps trying every 5 minutes to create directories/files and it usually works by the second run. I think one time it worked on the first try (like, without __any__ requests to "drive"-related stuff), which is always at least 5 minutes after I've created the channel. When the bug was still around I could never get it to provision no matter what calls I made. I'm __always__ using __application__ permissions by the way, I can't use delegated for my case.

I'm pretty sure the root of the bug was that while a SP site was being created, none of its features (or "apps" I think they call em?) were provisioned. So the fix is simply to actually do that now.

But you're right that Microsoft should be a little more clear about this.

**Comment by Nagesh29** [comment]
@Nikitha-MSFT 
I am still experiencing the same issue. I am creating a private channel using Graph API in a newly created team. Private channel creation is successful. However, I am not able to provision Excel tab to a private channel. Whenever I am trying to copy my excel file to the "https://siteurl-channelName/Shared Documents" it throws an error that site does not exists. I have tried verifying the private channel SharePoint URL manually and it is giving me 404. As soon as I visit the files section of the private channel from Teams, I am able to access the SharePoint site.

**Comment by Nikitha-MSFT** [comment]
@Nagesh29  - are you checking for files tab or excel tab? The bug us fixed for files tab.

**Comment by Nagesh29** [comment]
Files tab.
I am stuck at the point where "https://siteurl-channelName" this site is not getting created for a private channel until I click on files tab of the private channel manually.

**Comment by sgsmittal226** [comment]
@Nikitha-MSFT it is for sure still an issue. I am also able to reproduce continuously same thing.
I tried  with delegated and application permission but still same thing.

**Comment by Nagesh29** [comment]
@Nikitha-MSFT 
Can you please re-open this issue?

**Comment by Wajeed-msft** [comment]
Reopening this for tracking.

**Comment by Nikitha-MSFT** [comment]
@Nagesh29 - Could you please share the latest client-request id and timestamp?

**Comment by Nagesh29** [comment]
@Nikitha-MSFT 
"client-request-id": "a6a8ce24-7365-4510-8448-80287704982a"
"Date": "Tue, 22 Jun 2021 09:30:43 GMT"

**Comment by Nikitha-MSFT** [comment]
We are checking internally, we don't have ETA to share

**Comment by nilsvbconxion** [comment]
Also interested to see if this can be done via Application Permissions. Could really help the adoption to Teams for customers who are used to getting a certain folderstructure when managing projects.

**Comment by theofred** [comment]
With *application permissions* my current workaround is to call `{channel-id}/filesFolder` of the `General` channel and then `filesFolder` of the private channel.
It returns the `... not ready yet` error. I've implemented a retry logic that is running for a total of 5 minutes. Today it takes arround 160 seconds to retrieve the `filesFolder` of the private channel.

Hope this helps and will keep working. It should work out of the box though. Props to the ideas in this issue.

**Comment by alexandergroup-jnelson** [comment]
MSFT - After seeing this thread I have a clue why my JavaScript code using delegated permissions works better than my C# code that uses application permissions.  Most of the time with delegated permissions it's just a few minutes before the channels are ready for files/folders.  But with application permission I've waited over 24 hours and it's never ready.  Clicking the "files" tab on the channel doesn't seem to help it at all.

This is killing any attempts at automating project Teams creation with common channels and folders structure.  Please fix this.  I hope not to see any more "this is expected behavior" comments as it might be expected by MSFT but it's not expected by developers that use the product.

Any updates?

**Comment by sgsmittal226** [comment]
@Nikitha-MSFT  Can you please check if there is any update or if this has been scheduled for any specific release ?

**Comment by Wajeed-msft** [comment]
@anandab-msft - could you please help to share updates on this?

**Comment by ShadowStar-RC** [comment]
> With **application permissions** my current workaround is to call `{channel-id}/filesFolder` of the `General` channel and then `filesFolder` of the private channel. It returns the `... not ready yet` error. I've implemented a retry logic that is running for a total of 5 minutes. Today it takes arround 160 seconds to retrieve the `filesFolder` of the private channel.
> 
> Hope this helps and will keep working. It should work out of the box though. Props to the ideas in this issue.

@theofred  - Is this still working for you? I've tried to replicate this in Power Automate with calls separated by a 5 minute delay but still get 'not ready yet'.

**Comment by SjoerdV** [comment]
I am wondering why this is taking so long to solve (over a year already). The Product Team could just make a separate endpoint available to trigger the site creation, not dependent an whether Delegated or App permissions are used, right? Hope to see some progress on this soon, cheers!

**Comment by Jeroen00** [comment]
Agreed! This has been open for over 12 months and is limiting provisioning options for Teams. 

@anandab-msft @Nikitha-MSFT  any updates?

**Comment by GottemHams** [comment]
> I am wondering why this is taking so long to solve (over a year already)

Because they would rather waste time on useless features like a meme generator (for a professionally-aimed product, really?) instead of stabilising existing features. I know it's (most likely) a different team that's responsible for it, but it does show where their priorities lie in general (and this doesn't only apply to Teams). They haven't even responded here in almost half a year so I don't think they're currently actively working on this anymore.

**Comment by v-chetsh** [comment]
@Jeroen00 -  We will check the status internally and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@ValerasNarbutas - This issue has fixed. Could you check it at once.

**Comment by vilmarci** [comment]
We are experiencing the same issue, only we are creating the private channels with Power Automate. Even created a case with premier support, only to receive the "this is by design" message and there is no 100% workaround, even by calling the folder locations. Cannot we just have a parameter in the graph call like "force create channel location" ?

**Comment by v-chetsh** [comment]
@vilmarci - Could you please elaborate on your ask & share the repro steps, if possible?

**Comment by vilmarci** [comment]
@v-chetsh - we use the HTTP request with Azure AD action in PowerAutomate to create the private channel, like:

POST

`{
  "@odata.type": "#Microsoft.Graph.channel",
  "membershipType": "private",
  "displayName": "InternalShare",
  "description": "This is for private content",
  "members":
     [
        {
         "@odata.type":"#microsoft.graph.aadUserConversationMember",
           "user@odata.bind":"https://graph.microsoft.com/v1.0/users('@{outputs('owner')?['body/id']}')",
           "roles":["owner"]
        }
     ]
}`

The channel is created then I call the url most people use as workaround:
GET
@{concat('https://graph.microsoft.com/v1.0/teams/',variables('groupid'),'/channels/',outputs('Run_a_Child_Flow')?['Body']?['channelid'] ,'/filesFolder')}

And get the error message: "Folder location for this channel is not ready yet, please try again later."

**Comment by Nivedipa-MSFT** [comment]
@vilmarci - We tried to create private channel using Power Automate via Graph API and instantly we called Get FileFolder API and got the error message "Folder location for this channel is not ready yet, please try again later.". But when after sometime we tried to run Get FileFolder API query, its working fine.
Could you please call GET filesFolder Query after some time as it might take some time for the creation of private channel?

**Comment by vilmarci** [comment]
@Nivedipa-MSFT What is "after some time" exactly mean? 1 minute, 1 hour, 1 day?

**Comment by v-chetsh** [comment]
Hello @vilmarci - We will check on the execution time for private channel creation internally and get back to you.
Thanks for your patience!!

**Comment by alexandergroup-jnelson** [comment]
@vilmarci - We've had this working now for a few months from JavaScript where we create a Team and a private channel and add folders to it.  We have set up a loop that checks for filelFolder every 30 seconds for up to 15 minutes.  Typically it is ready in just less than 5 minutes.  If it doesn't work after 15 minutes we send an email to someone that can finish the process manually.  It's been working well for some time now.  Hope that helps.

**Comment by rlodev67** [comment]
Hey,

I reproduced the issue when I create a team in migration mode.
No folders are created at sharepoint side.

Any workarround for that ?

**Comment by rens8** [comment]
We're experiencing the same issue for some time now. We hoped to have a resolution/workaround. From our side the Team is created from an Azure Function which uses the Graph API to create the private channels.

Unfortunately the /filesFolders throws the error message: "Folder location for this channel is not ready yet, please try again later."
Is it possible to force the creation of the SharePoint site? How? (no, not manually via the files tab :))

**Comment by v-chetsh** [comment]
@rens8 - We are checking it internally with engineering team and let you know the updates once we get any.

**Comment by Nivedipa-MSFT** [comment]
@ValerasNarbutas, @rens8 - Is your issue resolved with above workaround or still facing the issue?

**Comment by ValerasNarbutas** [comment]
> @ValerasNarbutas, @rens8 - Is your issue resolved with above workaround or still facing the issue?

hey @Nivedipa-MSFT , i will try and give an update

**Comment by rens8** [comment]
> @ValerasNarbutas, @rens8 - Is your issue resolved with above workaround or still facing the issue?

Based on some very limited testing, these steps seem to resolve the problem. I'm getting back the data from the private channels SharePoint site.

Thanks!

**Comment by JBDUBREUIL** [comment]
I have the same issue and workfing with MS on it but this workaround solution not working for me : 

**I try to call GET "filesFolder" every 30 second during 10min without success , if I click manually on tabs "File" on my private channel and .... it's working but I have to wait  5min after private channel created **

- Create private team using /teams API
- Create private channel using /teams/{team-id}/channels API
- Create public channel using /teams/{team-id}/channels API
- **Execute graph query on standard channel first /teams/{id}/channels/{id}/filesFolder,** and once it returns the folder details, then
- Excute graph query on private channel /teams/{id}/channels/{id}/filesFolder

**Comment by alexandergroup-jnelson** [comment]
@JBDUBREUIL - we have been very successful using the following steps.  I believe it's only failed getting the private channel filesFolder once in the last 4 months. YMMV

- Create team
- Create private channel
- Add owner(s) to general channel
- Add owner(s) to private channel
- Get general channel files folder
-      Loop every 5 seconds up to 5 minutes (generally done in first few tries)
- Get private channel files folder
-      Loop every 30 seconds up to 15 minutes (generally around 5 minutes and has rarely failed)
- Add folders to general channel
- Add folder to private channel
- Add members to team
- Add members to private channel

If it fails on at any point an email is sent to someone for manual intervention.

Hope that helps!

**Comment by rens8** [comment]
@Nivedipa-MSFT we are experiencing a new issue with this setup. The call /filesFolder does return the correct information, but when we try to add documents to the privates channel library we get an Access Denied. (using an AAD App registration with full permissions and with the user account itself, which definately has access to the private channel)

This issue is resolved when the files tab in Teams is clicked and the file tab is loaded. Which is not a solution in our scenario.

**Comment by Nivedipa-MSFT** [comment]
@rens8 - Apologies for the delay. We are investigating your query. We will get back to you once we have any update.

**Comment by Nivedipa-MSFT** [comment]
@rens8 - Could you please share the repro steps to try at our end. Are you using any graph API for adding documents to the private channel library? If yes please share the API details.

**Comment by r-bytes** [comment]
Thanks to this amazing article, I was able to provision 200+ SPO site collections after creating the private channels.
I hope it helps!

https://www.tribework.nl/2022/03/howto-initialize-private-teamchannel-spo-sites/

**Comment by JBDUBREUIL** [comment]
It's not working. I try to reach endpoint "https://graph.microsoft.com/v1.0/teams/TeamsID/channelID/filesFolder" from my flow every minutes during 10minutes...

I try with postman, same result ...

**Comment by Nivedipa-MSFT** [comment]
@JBDUBREUIL - Could you please confirm is your issue resolved or are you still facing the issue?

**Comment by ValerasNarbutas** [comment]
> I have the same issue and workfing with MS on it but this workaround solution not working for me :
> 
> **I try to call GET "filesFolder" every 30 second during 10min without success , if I click manually on tabs "File" on my private channel and .... it's working but I have to wait 5min after private channel created**
> 
> * Create private team using /teams API
> * Create private channel using /teams/{team-id}/channels API
> * Create public channel using /teams/{team-id}/channels API
> * **Execute graph query on standard channel first /teams/{id}/channels/{id}/filesFolder,** and once it returns the folder details, then
> * Excute graph query on private channel /teams/{id}/channels/{id}/filesFolder

I have tried steps suggested by @JBDUBREUIL , and mainly step  **Execute graph query on standard channel first /teams/{id}/channels/{id}/filesFolder,** with loop to check for 10 min helped. Now private channel is created with sharepoint doc library - all via MS automate
. 
I will close this issue as resolved. 

My current setup which is wotkinig:
- Using a custom connector to graph i am creating team with public channels
 - Using a custom connector to graph i am creating private channels
 - using http call to sharepoint of private channel i am calling site design
  - site design script configured to create custom views and site columns
  -  and main thing, after oit is done i can now add dynamic values to columns in Private channel general library without a "file not found " errror

Hooray!!!
