### ISSUE TITLE
Shared mailbox category access not working

### ISSUE THREAD

**Issue by ShanSanear** [microsoftgraph/microsoft-graph-docs#10234]
Hi,

Right now whenever I try to access Outlook categories for a shared mailbox in my company, I am getting an "access denied" error:

HTTP Respons 403 Client Error: Forbidden for url: https://graph.microsoft.com/beta/users/SHARED_MAILBOX_MAIL/outlook/masterCategories | Error Message: Access is denied. Check credentials and try again.

When I do so with my own mailbox everything is fine and I can both create categories, set them to mails, etc.

I am however able to read emails from this shared mailbox.

The authentication method is "On behalf of a user" and I have a shared mailbox connected to my account.

As in the linked content source suggests, I am using `/users/SHARED_MAILBOX_MAIL/outlook/masterCategories` endpoint.

Permissions I am requesting at the start are:

- Mail.Send.Shared
- User.Read
- Mail.ReadWrite.Shared
- MailboxSettings.ReadWrite
- MailboxSettings.Read
- offline_access

Am I missing some access rights?

Any suggestions of what can be done would be great. Currently, it is not possible for me to request an Azure application that would authenticate using its own identity due to company policy restrictions.

I was also trying to use v1.0 API version, but to no avail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9a67c9-1216-d180-9d29-de8365c2e943
* Version Independent ID: 4ee9c109-26f1-5009-9b18-8051213251d5
* Content: [List Outlook categories - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/outlookuser-list-mastercategories?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/outlookuser-list-mastercategories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/outlookuser-list-mastercategories.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ShanSanear** [comment]
Can I expect any response to this issue?

**Comment by topcats** [comment]
<BUMP>

I have the same issue.

As far as i can tell i have the permissions set correctly.

I have full access from within outlook itself, and this works correctly.

**Comment by ShanSanear** [comment]
> 
> 
> I have the same issue.
> 
> As far as i can tell i have the permissions set correctly.
> 
> I have full access from within outlook itself, and this works correctly.

I managed, in the end, to update those categories on the shared mailbox but I am not sure what exactly is the cause of this.

Maybe this will help you.

Using O365 Python library, https://pypi.org/project/O365/ it is possible for me to load the shared mailbox as described in my post.

However, setting categories is a stretch.

The ONLY way I found that works is to change the "categories" property of the mail and **save it**.

I don't have code on me, the pseudocode is something like this:

```python
... # log in, getting messages and stuff, "message" is the Message object from shared mailbox
print(message.categories) # this will print categories of the message we are working on
message.categories = ["MY_CATEGORY_TO_SET_1", "MY_CATEGORY_TO_SET_2"]
# message.categories = messsage.categories + ["ANOTHER_CATEGORY"] <- in case you want to add categories
message.save() # Those two lines will set categories of the message to the two categories mentioned above
```

Bear in mind however, that this solution:
* can set single category multiple times to the single message, which can cause Outlook to freak out; you need to manually remove duplicates
* requires categories to be already defined on the message box if you want them to have colors; categories that have not been defined will be uncolored, but still visible after opening mail
* doesn't require usage of "Category" class of the library - you just use name of the category and that's it

I am not sure how exactly does it work internally, didn't have much time to see the difference. However since finding out how to solve this, our shared mailbox automation finally came to be and works as we expect.

Also, the most important part - this does not require application permission. "On behalf of a user" is enough for this to work (with appropriate selection of permissions of course).
