### ISSUE TITLE
Typo in returned Reports column name

### ISSUE THREAD

**Issue by ianByrne** [microsoftgraph/microsoft-graph-docs#1026]
Not an issue with the documentation, as such, but SO and UserVoice don't seem to be the right places to report this - a typo in the returned column name when accessing the Minutes ViewType for the SfbOrganizerActivity endpoint:

`https://graph.microsoft.com/beta/reports/SfbOrganizerActivity(view='Minutes',period='D7')/content`

> Data as of,Last activity date (UTC),Reporting period in days,Audio/**Vieio**,Dial-in Microsoft,Dial-out Microsoft

Vieio instead of Video. The other ViewTypes seem fine.

**Comment by ianByrne** [comment]
Similar column typo issue in the response for:

`https://graph.microsoft.com/beta/reports/Office365ActiveUsers(view='Detail',period='D7')/content`

> Data as of,User principal name,DisplayName,Deleted,Deleted date,License For Exchange,License For **OndDrive**,License For SharePoint,License For Skype For Business,License For Yammer,Last Activity Date For Exchange,Last Activity Date For **OndDrive**,Last Activity Date For SharePoint,Last Activity Date For Skype For Business,Last Activity Date For Yammer,License Assigned Date For Exchange,License Assigned Date For **OndDrive**,License Assigned Date For SharePoint,License Assigned Date For Skype For Business,License Assigned Date For Yammer,Products assigned

OndDrive instead of OneDrive

**Comment by JohnAustin-MSFT** [comment]
@kszb, Can you take a look at this issue? It appears to be an issue in the Graph endpoint logic.

**Comment by ianByrne** [comment]
Looks like these issues have since been resolved. The endpoint URLs have also been updated, and the whole shebang released to v1.0:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/report
