### ISSUE TITLE
Needing C# example

### ISSUE THREAD

**Issue by ChrisB9907** [microsoftgraph/microsoft-graph-docs#10304]
Needing C# example of this as it doesn't seem like this is functioning in the graph nuget packages yet. Tested the Microsoft.Graph.Beta package as well (version 0.29.0-preview)  which is the newest on nuget.org.

communications has the following properties currently

![image](https://user-images.githubusercontent.com/60661129/96166821-5e6ca980-0ed3-11eb-9aea-6d16a0cb913e.png)

and call records has the following properties currently 

![image](https://user-images.githubusercontent.com/60661129/96166987-91af3880-0ed3-11eb-8485-f13dd3833b5f.png)

The graph rest api URL usually looks like the following
`https://graph.microsoft.com/beta/communications/callRecords/getPstnCalls(fromDateTime=2020-10-15,toDateTime=2020-10-16)`

So there doesn't seem to be a getPstnCalls option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 225370c6-9fb6-9a48-9275-12cff5d87d46
* Version Independent ID: c3fdaa61-1d7d-447d-7844-737902b786d8
* Content: [callRecord: getPstnCalls - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/callrecords-callrecord-getpstncalls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by luuhuyentrang** [comment]
I'm also looking for a C# example to get the Pstncalls.
I couldn't find the function corresponding to this endpoint. 
I tested the newest Microsoft.Graph.Beta package (version 0.33.0-preview)

**Comment by mcm223** [comment]
This is a known issue and will be corrected in the next version. Please see this comment for a workaround and additional information: https://github.com/microsoftgraph/microsoft-graph-docs/issues/19958#issuecomment-1404681637
