### ISSUE TITLE
Get/Create Channel Graph API Issue

### ISSUE THREAD

**Issue by ivaibhavarya** [microsoftgraph/microsoft-graph-docs#10315]
Hi,

I am getting issue while creating/getting channels. Please find details on the same below : 

This is the response from getting access token. I am able to get both the access token and refresh token.
{
    "token_type": "Bearer",
    "scope": "Channel.Create ChannelMessage.Read.All ChannelMessage.Send Directory.AccessAsUser.All Directory.Read.All Directory.ReadWrite.All Group.Read.All Group.ReadWrite.All Mail.Read User.Read User.Read.All User.ReadBasic.All User.ReadWrite User.ReadWrite.All profile openid email",
    "expires_in": 3599,
    "ext_expires_in": 3599,
    "access_token": "xx",
    "refresh_token": "xx"
}

However, when I am using this token to create Channel or get Channel - I am getting the following response every time on both of the APIs :

Create Channel API Sample : 

Request : https://graph.microsoft.com/v1.0/teams/xx/channels
Method : POST
Response :
{
    "error": {
        "code": "Forbidden",
        "message": "Unable to fetch team thread: Failed to execute Skype backend request GetThreadS2SRequest.",
        "innerError": {
            "date": "2020-10-16T07:14:59",
            "request-id": "90abbba1-6df0-4a09-aec0-71bc393fc2e0",
            "client-request-id": "90abbba1-6df0-4a09-aec0-71bc393fc2e0"
        }
    }
}

I had already applied required permissions on Azure Portal and in the "scope" attribute of body as well while getting the access token. Still, I am not able to fetch any channel list present in the team or create any channel. Although, I was able to create team with the same access token. 

Note: I am using the access token on the behalf of user and had used Authorization Code to get the access token.

Kindly let me know to fix this at the earliest. 

Regards,
Vaibhav 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2109ed82-4572-a453-a379-0ff259360879
* Version Independent ID: 96361942-5ec7-f062-64a5-06ef63f9d2e2
* Content: [Create channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VaraPrasad-MSFT** [comment]
To list the channels you can use the Get https://graph.microsoft.com/v1.0/teams/{id}/channels, and to create channel use POST https://graph.microsoft.com/v1.0/teams/{id}/channels with the payload. Please refer these documents for [listing channel](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http#example-1-list-all-channels)s and [creating channels](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#example-1-create-a-standard-channel) . And also please check the required permissions for [create channel](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#permissions) and [list channels](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http#permissions).

**Comment by Nikitha-MSFT** [comment]
Please feel free to reopen the issue if issue still persists
