### ISSUE TITLE
Sites Analytics not working

### ISSUE THREAD

**Issue by RowanAdvisors** [microsoftgraph/microsoft-graph-docs#10321]
I'm getting a 400 bad request error when trying to get the site analytics endpoint in graph using the graph explorer.  Has this endpoint be retired?

For reference the site analytics endpoint:
GET /sites/{site-id}/analytics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc23aedb-c478-2515-0d37-a3683897eebc
* Version Independent ID: 60536091-1ce7-fde8-9e39-115517304400
* Content: [Get itemAnalytics - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/itemanalytics-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/itemanalytics-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/itemanalytics-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @daspek
* Microsoft Alias: **dspektor**

**Comment by takawazo** [comment]
Try /sites/{site-id}/analytics/allTime
