### ISSUE TITLE
endsWith example returns 'Unsupported Query'

### ISSUE THREAD

**Issue by Tiberriver256** [microsoftgraph/microsoft-graph-docs#10324]
The documentation provides an example of how to use the endsWith function in the $filter parameter:
```
https://graph.microsoft.com/v1.0/users?$count=true&$filter=endsWith(mail,'@hotmail.com')
```
Running this results in the following error:

```
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported Query.",
        "innerError": {
            "date": "2020-10-16T20:15:58",
            "request-id": "b1c66367-1a84-4183-834f-0000000",
            "client-request-id": "b3156938-7d23-3f14-9831-000000000"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters?view=graph-rest-beta)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hannespreishuber** [comment]
works with todays graph explorer but not with the -net object 
GraphServiceClient
        .Users
        .Request()
        .Filter(filterString) ->startwith works  but not endwith

**Comment by jcop** [comment]
At [https://developer.microsoft.com/en-us/graph/graph-explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) the endswith filter does not work as well.

It just returns "Request_UnsupportedQuery"

The startswith does work.

**Comment by hannespreishuber** [comment]
it works - you have to add a header

```
 var options = new List<Option>()

 options.Add(new QueryOption("$filter",
 "endsWith(mail,'ppedv.de') or endsWith(mail,'ppedv.at') "));

   options.Add(new HeaderOption("ConsistencyLevel", "eventual"));

    options.Add(new QueryOption("$count", "true"));

  var tmp = await graphClient.Users.Request(options).GetAsync();
```

**Comment by jcop** [comment]
@hannespreishuber, thank you for the heads-up, I completely missed (ie did not read the documentation) the header and $count requirement.

I can confirm that it works with python.

Thanks again!

**Comment by FaithOmbongi** [comment]
Thank you @hannespreishuber for helping resolve this issue.

The `endsWith` operator is one that is supported only when you add a set of advanced parameters: the **ConsistencyLevel** header set to `eventual` and the `$count` parameter. In this case:

[https://graph.microsoft.com/v1.0/users?$count=true&$filter=endsWith(mail,'@hotmail.com')](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DendsWith(mail%2C'%40hotmail.com')&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

Additional guidance on this will be published soon via the [Use query parameters](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0) page.
