### ISSUE TITLE
Cannot add value because header 'Authorization' does not support multiple values.

### ISSUE THREAD

**Issue by kepeter** [microsoftgraph/microsoft-graph-docs#10329]
After creating a team based on 'educationClass' template, I'm trying to add an assignment...
My code is like this:
```
await _Client.Education.Classes["1f3b606a-27fa-4e48-a051-0a35c4d2da07"].Assignments.Request().AddAsync(new EducationAssignment()
{
    DisplayName = "Any name",
    Instructions = new EducationItemBody()
    {
        ContentType = BodyType.Text,
        Content = "Any description"
    },
    Status = EducationAssignmentStatus.Draft,
    AssignDateTime = new DateTimeOffset(DateTime.Parse("2020-10-19T12:00")),
    DueDateTime = new DateTimeOffset(DateTime.Parse("2020-10-22T12:00"))
});
```
I'm receiving the error in the title...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f526390-3f1b-58f0-2cf4-05dff77e0eff
* Version Independent ID: 216b05ef-8fbb-53f3-1e10-a02f2445654c
* Content: [Create educationAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/educationclass-post-assignments.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kepeter** [comment]
A little addition... It does not matter if the team was created previously (either via API or via UI) or as the part of the current session, it fails...

**Comment by dipakboyed** [comment]
The error would indicate there's something wrong with the Authorization Http request header. The error does not seem educationAssignment specific and was blocked by the auth layer.
Are you able to call other APIs with the same auth token?

**Comment by kepeter** [comment]
@dipakboyed What you say is a good interpretation of the error message, however it happens only to this call. I can do any short of calls (create class, add channel, add/remove members) with the very same instance of AuthenticationProvider, only this call fails...

So while it IS an authentication problem it IS definitely a problem with this specific API...

For instance - in the following code sample only the last part fails with the error - anything else works without problem...
```
_Client = new GraphServiceClient(GraphClientFactory.Create(new AuthenticationProvider(ClientID, ClientSecret, TenantID)));

EducationClass oClass = await _Client.Education.Classes.Request().AddAsync(new EducationClass
{
	DisplayName = Name,
	Description = Description,
	ClassCode = CourseEmail,
	MailNickname = CourseEmail
});

Team oTeam = await _Client.Groups[oClass.Id].Team.Request().GetAsync();

EducationAssignment oAssign = await _Client.Education.Classes[oTeam.Id].Assignments.Request().AddAsync(new EducationAssignment()
{
	DisplayName = Name,
	Instructions = new EducationItemBody()
	{
		ContentType = BodyType.Text,
		Content = Description
	},
	Status = EducationAssignmentStatus.Draft,
	AssignDateTime = Start == null ? (DateTimeOffset?)null : new DateTimeOffset(Start.Value),
	DueDateTime = End == null ? (DateTimeOffset?)null : new DateTimeOffset(End.Value)
});
```

**Comment by dipakboyed** [comment]
@kepeter , apologies for the late reply. 
For troubleshooting, would it be possible to share a recent failed API call and it's timestamp and request-id from the response headers?

**Comment by kepeter** [comment]
@dipakboyed The request never makes it... It fails inside the SDK while building the actual post to send...
This is the most inner exception:
```
Cannot add value because header 'Authorization' does not support multiple values.

   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(String name, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, String value)
   at MichlolTeams.MichlolTeamsAPI.AuthenticationProvider.<AuthenticateRequestAsync>d__4.MoveNext() in C:\Users\peter\Source\Repos\TeamsConsole\TeamsConsole\Program.cs:line 39
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.AuthenticationHandler.<SendRetryAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.AuthenticationHandler.<SendAsync>d__16.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.SimpleHttpProvider.<SendRequestAsync>d__13.MoveNext()
```
The whole flow of my code (that the sample code does not include) is:
* create EducationClass
* add AD user as owner
* create a Team based on the EducationClass, with lots of configurations to fit my needs
* add EducationAssignment to the Team - HERE it fails

**Comment by dipakboyed** [comment]
Thank you. Let me have the SDK and/or Auth experts chime in

**Comment by dipakboyed** [comment]
StackOverflow search would indicate this error message is typically seen if the HttpRequest being constructed somehow ended up adding the Authorization header twice.
I'm reassinging this issue to @mmast-msft , we need the SDK gurus to look into this.

**Comment by kepeter** [comment]
@dipakboyed I did some search and I do understand the possible meaning of the code. The problem is that the request built by the SDK, and it is the only one - so far - that does it. In the mentioned sequence there are several other HTTP requests and all goes well... So it either this specific call or the specific sequence (the previous call didn't clean up)...

**Comment by darrelmiller** [comment]
From the code snippet above it would be the implementation of AuthenticationProvider that would set the Authentication header on the request.  That is not class that in the SDK.  I suspect that the code in that class is adding an `Authorization` header instead of just setting the strongly typed Authorization property.  When a retry happens we need to clone the request and I suspect at that point it tries to add the auth header again.  Can you show the code in the AuthenticationProvider?  Also, feel free to use the AuthenicationProvider implementations that are in the Microsoft.Graph.Auth library, even though it is marked as in preview.

**Comment by kepeter** [comment]
@darrelmiller My code for implementing IAuthenticationProvider looks like this
```
private class AuthenticationProvider : IAuthenticationProvider
{
    private string _ClientID;
    private string _ClientSecret;
    private string _TenantID;

    public AuthenticationProvider(string ClientID, string ClientSecret, string TenantID)
    {
        _ClientID = ClientID;
        _ClientSecret = ClientSecret;
        _TenantID = TenantID;
    }

    public async Task AuthenticateRequestAsync(HttpRequestMessage Request)
    {
        ConfidentialClientApplicationBuilder oBuilder = ConfidentialClientApplicationBuilder.Create(_ClientID);

        oBuilder.WithClientSecret(_ClientSecret).WithClientId(_ClientID).WithTenantId(_TenantID);

        IConfidentialClientApplication oClientApplication = oBuilder.Build();

        AuthenticationResult oResult = await oClientApplication.AcquireTokenForClient(new string[] { "https://graph.microsoft.com/.default" }).ExecuteAsync();

        Request.Headers.Add("Authorization", oResult.CreateAuthorizationHeader());
    }
}
```
I built this code on two sources I found on the internet on this subject:
* https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth
* https://adrianszen.com/2019/06/16/microsoft-graph-how-to-implement-iauthenticationprovider

The last line - indeed - do add a Authorization' header, but without that line I receive an error of '**InvalidAuthenticationToken
Message: Access token is empty.**', and I do not see any way to set the '**strongly typed Authorization property**' you are mentioning (neither found it in the documentation)...

It seems to me now, that the problem is with my code, but without proper documentation I had no choice but 'bombard' you with somethin that looks like a bug on your side...
If I understand correctly now, the problem is with the second time I try to add the header, but can't see what is the right way to solve it...

**Comment by darrelmiller** [comment]
You can set the Authorization header like this:
 
```csharp
         httpRequestMessage.Headers.Authorization = new AuthenticationHeaderValue(CoreConstants.Headers.Bearer, authenticationResult.AccessToken);

```
https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth/blob/dev/src/Microsoft.Graph.Auth/ConfidentialClient/ClientCredentialProvider.cs#L63

Also, you really don't want to be creating a new application instance on every request.  Store it as a field in the auth provider and re-use it.

**Comment by kepeter** [comment]
> Also, you really don't want to be creating a new application instance on every request. Store it as a field in the auth provider and re-use it.

I do not understand what do you mean here... This code represents an authentication provider for a GraphServiceClient object that created only once...

As for the change of line - it only changes the error to something less informative:
```
Code: UnknownError
Inner error:
	AdditionalData:
	date: 2020-12-10T07:45:09
	request-id: 4fad1fc5-e8f8-492a-87bc-c728a9d5a3af
	client-request-id: 4fad1fc5-e8f8-492a-87bc-c728a9d5a3af
ClientRequestId: 4fad1fc5-e8f8-492a-87bc-c728a9d5a3af
```

**Comment by kepeter** [comment]
I have investigated it further and found that for each API call there is exactly one call to _IAuthenticationProvider.AuthenticateRequestAsync_, but when calling this API there are two calls. The first sets the header and the second fails...

**Comment by mmast-msft** [comment]
Added Darrel to assignees for visibility.

**Comment by MuradMamedov** [comment]
I had same error, reason was that I had mixed API Permissions
![image](https://user-images.githubusercontent.com/27346426/116363107-12e07400-a803-11eb-95f1-b0bb2a77c269.png)
Removing all delegated permissions in my case fixed the problem.
