### ISSUE TITLE
Permissions inconsistency between beta and v1.0 endpoint

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs#10350]
Hello,
the [post](https://developer.microsoft.com/en-us/graph/blogs/announcing-the-general-availability-of-microsoft-graph-teams-membership-api/) officially announced the availability of the Teams Membership API. Thank you very much for the work done so far.

I noticed that the [beta endpoint](https://docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-beta&tabs=http) is suggesting different API permissions as the v1.0 endpoint.

The beta endpoint for example can be used with ChannelMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All while the v1.0 endpoint can only be used with TeamMember.ReadWrite.All based the documentation.

I am wondering why the permissions Group.ReadWrite.All and Directory.ReadWrite.All have been removed from the endpoint? I am seeing it like this. If you are an administrator of an object (the Group) where my privatechannel is member of, then I should be able to perform the operation against this object.

Thank you for your feedback,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7279fc44-89a2-5b5e-1064-a5701880a564
* Version Independent ID: 095d95ca-2198-9cfe-ef6a-3a69ed5bcfe9
* Content: [Add members to team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Manish-MSFT** [comment]
Hi @plamber, We are investigating this internally.
