### ISSUE TITLE
No team found with Group Id...

### ISSUE THREAD

**Issue by kepeter** [microsoftgraph/microsoft-graph-docs#10364]
Hi,

This is my code sample:
```
EducationClass oClass = await _Client.Education.Classes.Request().AddAsync(new EducationClass
{
    DisplayName = "Class10",
    Description = "From API",
    ClassCode = "class10@dummy.com",
    MailNickname = "class10@dummy.com"
});

/* https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-beta&tabs=csharp
    If the group was created less than 15 minutes ago, 
    it's possible for the Create team call to fail with a 404 error code 
    due to replication delays. 
    The recommended pattern is to retry the Create team call three times, 
    with a 10 second delay between calls.
    */
int nRetry = 3;
while (nRetry > 0)
{
    try
    {
        await _Client.Teams.Request().AddAsync(new Team
        {
            DiscoverySettings = new TeamDiscoverySettings
            {
                ShowInTeamsSearchAndSuggestions = false
            },
            MessagingSettings = new TeamMessagingSettings
            {
                AllowUserEditMessages = true,
                AllowUserDeleteMessages = true,
                AllowOwnerDeleteMessages = true,
                AllowChannelMentions = true,
                AllowTeamMentions = true
            },
            GuestSettings = new TeamGuestSettings
            {
                AllowCreateUpdateChannels = false,
                AllowDeleteChannels = false
            },
            MemberSettings = new TeamMemberSettings
            {
                AllowAddRemoveApps = false,
                AllowCreatePrivateChannels = false,
                AllowCreateUpdateChannels = false,
                AllowCreateUpdateRemoveConnectors = false,
                AllowCreateUpdateRemoveTabs = false,
                AllowDeleteChannels = false
            },
            AdditionalData = new Dictionary<string, object>()
    {
        {"template@odata.bind", "https://graph.microsoft.com/beta/teamsTemplates('educationClass')"},
        {"group@odata.bind", string.Format("https://graph.microsoft.com/beta/groups('{0}')", oClass.Id)}
    }
        });

        break;
    }
    catch (Exception)
    {
        Thread.Sleep(10000);

        nRetry--;
    }
}
```

The code creates a Team based on the educationClass template and works perfectly up to Microsoft.Graph.Core 1.22.0-preview.2.
When upgrading to version 2.0.0-preview.3 (the latest) it receives the error in the title, even the group IS exists... It seems to me as timing problem of some sort, but blocks me from receive newer versions of the graph API...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33803a53-4965-1c01-ea17-49e01b8378c5
* Version Independent ID: 9223513b-37d0-f9ea-f004-83f2222906b0
* Content: [Create team from group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Abhijit-MSFT** [comment]
@kepeter, This API is in process of being deprecated. Use [this](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http) API for teams creations. Let me know if you face any issue with this API.

**Comment by kepeter** [comment]
@Abhijit-MSFT 
It seems that the issues bounded to the wrong API...
In the code there are two calls:
- Education.Classes.Request().AddAsync - which creates a group
- Teams.Request().AddAsync - to create a team based on that group (and gets an error when using new Graph.Core library)

None of them seems to be deprecated - it seems that the new version of the API can't create group based on the educationClass template...

**Comment by kepeter** [comment]
@Abhijit-MSFT 
Today updated to the latest beta:
- Microsoft.Graph.Core - 2.0.0-preview.3
- Microsoft.Graph.Beta - 0.32.0-preview

There is a new error:
```
Code: BadRequest
Message: The navigation bind for template was missing in request.
Inner error:
	AdditionalData:
	date: 2020-11-17T11:03:50
	request-id: 74cd955e-f02c-47e3-a371-6423220df456
	client-request-id: 74cd955e-f02c-47e3-a371-6423220df456
ClientRequestId: 74cd955e-f02c-47e3-a371-6423220df456
```
I couldn't find anything about that 'navigation bind' the error mentions...

**Comment by kepeter** [comment]
@Abhijit-MSFT 
Walked over all the versions and saw that the last combination to work is

- Microsoft.Graph.Core - 2.0.0-preview.1
- Microsoft.Graph.Beta - 0.32.0-preview

If I further update Microsoft.Graph.Core to preview.2 or preview.3 I receive the error mentioned earlier...

**Comment by Manish-MSFT** [comment]
@kepeter, I tried this usecase by copying same code and got an error stating that Collection doesn't support Assignment categories . Could you please verify if my authprovider is correct?
![image](https://user-images.githubusercontent.com/70321016/99521319-4698b180-29ba-11eb-83d1-2c16544ffc25.png)
![image](https://user-images.githubusercontent.com/70321016/99521330-4ac4cf00-29ba-11eb-8b38-3581a0d46cda.png) 

I am using the latest preview nuget packages.

**Comment by kepeter** [comment]
@Manish-MSFT I think you need A1 (minimum) for this to work...

**Comment by darrelmiller** [comment]
The preview version of the Microsoft.Graph.Core library uses System.JSON.Text for serialization.  It should not be used with any of the Microsoft.Graph service libraries as they use Newtonsoft.JSON serializers.  Please use the non-preview version of Microsoft.Graph.Core.  Future versions of the Microsoft.Graph service library will be ported to System.Text.JSON.

Sorry for the confusion.

**Comment by kepeter** [comment]
There is a place where a mare mortal, like me, can follow these changes?

**Comment by darrelmiller** [comment]
We have release notes here https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/releases  however I have to admit we didn't do a good job of communicating this particular issue.  The 2.0 preview wasn't supposed to be around for as long as it has been but the dev who was working on it got reassigned due to priorities.

**Comment by kepeter** [comment]
Thank you!
I close the issue (not that it exactly solved, but we do know the solution to come), and link myself to that page to follow...
