### ISSUE TITLE
Typo in Device resource type documentation. 

### ISSUE THREAD

**Issue by di-wu** [microsoftgraph/microsoft-graph-docs#10381]
Typo in description: **interal** should be **internal**.

Property | Type | Description
-- | -- | --
... | ... | ...
deviceMetadata | String | For interal use only. Set to null.
deviceVersion | Int32 | For interal use only.
... | ... | ...
physicalIds | String collection | For interal use only. Not nullable.
-- | -- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b855b67-0f09-bf85-782f-7fb68a24ee7c
* Version Independent ID: 500e299b-6f0f-f0b6-f89b-ae60f77f9332
* Content: [device resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/device.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @spunukol
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @di-wu 

thanks for reporting this issue. I've authored a pull request, whenever it gets merged it'll close this issue!

Regards
Jarbas

**Comment by Lauragra** [comment]
Thanks.
