### ISSUE TITLE
Where is this filesfolder request looking?

### ISSUE THREAD

**Issue by m3ngi3** [microsoftgraph/microsoft-graph-docs#10396]
It would be nice to know where this filesfolder request is looking for automation purposes.
Is this stored in the Channel property?
In the Group property?

Can we provide an own URL / Folder ID that links the files folder to the (newly) created channel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3914d7e5-bbb3-b349-893c-ef01c2938981
* Version Independent ID: 15bc6db6-36cd-cc2b-2b9c-34c30141b89c
* Content: [Get filesFolder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-get-filesfolder.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VaraPrasad-MSFT** [comment]
Everything will be stored in SharePoint site. If you are looking to get the file path, you need to provide the SharePoint site path.
Your question is not clear. Can you please explain your automation scenario.

**Comment by m3ngi3** [comment]
Hi @VaraPrasad-MSFT, when I have created a SharePoint Folder in the Teams Related SharePoint Site with the exact same naming of the Teams Channel --> this Graph Call action returns a notification with SharePoint Folder not found.

When I then click on the Files Tab of that Channel, it apparently links the existing SharePoint Folder to the Teams Channel somewhere --> because now this Graph Call action returns the URL to the existing SharePoint Folder.

My question is where the Graph Call action of **GET /teams/{id}/channels/{id}/filesFolder** looks at to retrive the files folder link. I want to see if I can influence it...

Background info = https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41743294-default-files-tab-of-channel-programmatically-pro

**Comment by Abhijit-MSFT** [comment]
@m3ngi3, Creating folder manually and searching through graph api will not work because there is no link between the folder that is manually created in the SharePoint site and the Files option in Teams so it is correctly returning the "not found", The current behavior of the application is to hit the Files tab manually then the SharePoint site will get created.
Currently there is no way to influence this process.

**Comment by m3ngi3** [comment]
Clear!
So now for the million dollar question: where does the Graph call: **GET /teams/{id}/channels/{id}/filesFolder** look??

When a user has hit the Files Tab of a Microsoft Teams Team, this call returns a URL of the Folder based on giving the Group ID with the Channel ID as —> so there is a magical place where a SharePoint Folder is linked to a Channel of a Team right??

**Comment by VaraPrasad-MSFT** [comment]
@m3ngi3 ,
When you use Graph call:  GET /teams/{id}/channels/{id}/files Folder it will retrieve the data from the Teams. When the file is uploaded to teams files tab the file is stored in the SharePoint that teams channel and SharePoint linked. So as the file stored in the SharePoint you will receive the SharePoint URL as to response of file For graph API call.

**Comment by m3ngi3** [comment]
I am going to repeat some of the information, I shared already in the background info mentioned above.

At the moment clicking the Files Tab by a user for the FIRST time: 
A => creates a folder if the default Drive of the Group (=default document library of the Team related SharePoint Site), does not contain a root level sub folder yet with the EXACT name of the specific Teams Channel at the moment of first time clicking 
B => links the Teams Channel to an existing Folder if there is a Folder with the EXACT name of the Channel at the moment of first time clicking.

In scenario B there is a Folder already in SharePoint with exact same name as the Teams Channel. When using this Graph Call in this Scenario B BEFORE someone clicks the Files tab in Teams Channel for the first time —> the Graph Call returns an error with nothing found in SharePoint —> again: I created a folder manually with the exact same name as the Teams Channel so there is definitely a Folder for this Channel.
When using this Graph Call AFTER someone clicks the Files tab —> the Graph Call returns the SharePoint folder url of the folder created manually by me.

So this means that after someone clicks the Files tab in a Teams Channel for THE FIRST TIME:
A- it creates a new Files Folder if not already existing
B- it links to an existing Files Folder of the Group Drive if this folder with exact same name as Channel already exists

Where does this Graph Call look to retrieve the Files Folder URL of a specific channel? It is not a property of the Group and not a property of the Team, because the Graph Calls on those Get Group and Get Team actions DO NOT show Channel Folder URLs... Get Channel Graph Call also does not show a SharePoint Folder as a property...

**Comment by Nikitha-MSFT** [comment]
**For scenario1 :** When you are trying to create the folder with same name as teams channel name then while fetching the sharepoint URl for the channel through Graph API, Sharepoint URL will be available in the response. This is Because teams create the sharepoint of the channel once user clicks on the files tab and this is backend mechanism 
 **For scenario2:**  When a channel is created in Teams, The files folder is not created in sharepoint. Teams create the shrepoint folder on demand,when user clicks on the files tab. This is by design.

**Comment by m3ngi3** [comment]
Yes... maybe an idea to put that in the documentation belonging to the Graph Call 👍

Please vote to improve the design: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/41743294-default-files-tab-of-channel-programmatically-pro
