### ISSUE TITLE
Patching fido2 and ms authenticator app passwordless does not work

### ISSUE THREAD

**Issue by mariussm** [microsoftgraph/microsoft-graph-docs#10400]
You might as well remove the "update" pages for these, because the patch does not WORK. It responds success, but nothing is updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 293194c4-5b4e-360b-e0a6-771b2347cc5d
* Version Independent ID: 966ea0c0-250a-d2f3-4b36-89450cfa484a
* Content: [Update fido2AuthenticationMethodConfiguration - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/fido2authenticationmethodconfiguration-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hello @mariussm ,

Kindly verify.
I've tested and the example listed on the page is successfully updating my **fido2AuthenticationMethodConfiguration** object. After you get a 204 on PATCH, run GET https://docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-beta and you'll see the properties were correctly updated.


No updates identified for the page. Closing the issue.
