### ISSUE TITLE
Directory Roles  with members as service principals

### ISSUE THREAD

**Issue by meetppr** [microsoftgraph/microsoft-graph-docs#10414]
This API doesn give the member service principal objects. It only lists the users and groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c272ae84-e425-d521-8ceb-5c4f2296bb4c
* Version Independent ID: 14e8c12f-711d-5af5-4acc-4ea5444cc569
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryrole-list-members?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/directoryrole-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryrole-list-members.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abhijeetsinha** [comment]
@meetppr - Service principals are in beta endpoint, not in v1.0 endpoint yet. That's why your v1.0/directoryRoles/{id}/members does not return service principals. Try this - beta/directoryRoles/{id}/members .
