### ISSUE TITLE
/me/insights endpoints throw 403 when using delegated permissions with Sites.Manage.All or Sites.FullControl.All

### ISSUE THREAD

**Issue by MrTantum** [microsoftgraph/microsoft-graph-docs#10427]
When using Microsoft graph for the `/me/insights` endpoints the calls fail with an `HTTP 403` response when the executing azure ad app has `Sites.Manage.All` and / or `Sites.FullControl.All`. When using `Sites.Read.All` and/or `Sites.ReadWrite.All` the calls are successful. 

`Sites.ReadWrite.All` is not mentioned in the documentation pages ([Trending](https://docs.microsoft.com/en-us/graph/api/insights-list-trending?view=graph-rest-1.0), [Used](https://docs.microsoft.com/en-us/graph/api/insights-list-used?view=graph-rest-1.0), [Shared](https://docs.microsoft.com/en-us/graph/api/insights-list-shared?view=graph-rest-1.0)).

Normally using a higher permission level for an endpoint results in successful response (e.g. read site data in a SharePoint list with an app that has `Sites.Manage.All` but not `Sites.ReadWrite.All` permissions).

This does not seem to be the case for these endpoints.

**Therefore please fix the documentation or ensure that the endpoints also work with `Sites.Manage.All` and `Sites.FullControl.All`.**

# Steps to reproduce
1. Login to [Graph Explorer](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjW-M7ztNLsAhXIzKQKHamyCUwQFjAAegQIAxAD&url=https%3A%2F%2Fdeveloper.microsoft.com%2Fen-us%2Fgraph%2Fgraph-explorer&usg=AOvVaw0-qGv5YJEy5fIbF6107MZd).
2. Ensure that Graph Explorer has been given `Sites.Manage.All` permissions and not been given `Sites.Read.All` and not `Sites.ReadWrite.All`.
3. Execute `GET` `https://graph.microsoft.com/v1.0/me/insights/used`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852bc9f0-fb75-6421-6e01-1f17e418b75a
* Version Independent ID: 54a4a457-0ab7-f5ce-efba-5baff4a1ec71
* Content: [List shared - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/insights-list-shared?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/insights-list-shared.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/insights-list-shared.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by elmakhmu** [comment]
Just checked on clear demo tenant.
1. only Sites.Read.All and/or Sites.ReadWrite.All are required for accessing me/insights. 
2. and it's already documented. 


![image](https://user-images.githubusercontent.com/54312959/97312877-464b4180-1866-11eb-82aa-2ed5cb71a989.png)
![image](https://user-images.githubusercontent.com/54312959/97312931-595e1180-1866-11eb-9069-1dbec66fc11f.png)
![image](https://user-images.githubusercontent.com/54312959/97312977-6844c400-1866-11eb-9819-2353bf4188cd.png)

**Comment by MrTantum** [comment]
You are right I did not check this correctly. The docu has `Site.ReadWrite.All` already mentioned.

But what about the other question stays:

Why isn't this working with `Sites.Manage.All` and `Sites.FullControl.All` working?

**Comment by elmakhmu** [comment]
Historically, this has implemented.
What kind of problem are you trying to solve?

**Comment by MrTantum** [comment]
To minimize customer confusion we are always trying to minimize redundancy in our azure ad app permission. Therefore we do not add any permissions that are already part of another (e.g. no `Group.Read.All` when the app already has `Group.ReadWrite.All`).

In this case the app already has `Sites.FullControl.All` delegated permissions. Until now it has not been necessary to add any other `Site...` permissions because `Sites.FullControl.All` already contains everything else.

Now we will have to explain our customers why for this one usecase (insights endpoints) the will also have to add `Site.ReadWrite.All` or `Site.Read.All`.

**Comment by elmakhmu** [comment]
Sorry for inconvenience, Insights APIs were released many years ago, maybe there weren't such a permissions before. We will take this note into account in our new APIs implementation.

**Comment by MrTantum** [comment]
Thanks @elmakhmu. Would be nice if you could also keep this point in mind when you ever update these endpoints again.

I'll close this topic here for now.

**Comment by elmakhmu** [comment]
@MrTantum One more question. For my personal learning - am I understanding right and the customer has 3rd party app, working on Insights API? Maybe you know what kind of app is it, what purpose does it serve? 

It will help for us to understand patterns of usage Insights APIs very much.

**Comment by MrTantum** [comment]
Sure. This is used for an SPFX WebPart that is similar to the ([personal email](https://github.com/pnp/sp-starter-kit/blob/master/documentation/components/wp-personal-email.md)) WebPart. But in this case case it shows _My Last opened / Files shared with me / Files trending around me_ in a tab view.

**Comment by elmakhmu** [comment]
@MrTantum  thanks a lot! Could I ask you (for the future) if you will find any cases of using our Insights API in 3rd party applications - write me couple sentences about it, please. we want to understand better use cases in order to implement in the future better trending, used and shared files.
