### ISSUE TITLE
Microsoft graph list access reviews endpoint not working

### ISSUE THREAD

**Issue by Mobrockers** [microsoftgraph/microsoft-graph-docs#10452]
No matter in which format as specified on the docs I execute the list access reviews request, I get the error `Bad filter: One of these properties must be specified: 'businessFlowTemplateId' or 'partnerId' or 'businessFlowId'. List of businessFlowTemplates is available at /businessFlowTemplates`.

See:

```
PS C:\Users\roukeb> az rest --method get --url "https://graph.microsoft.com/beta/accessReviews"  --uri-parameters $filter="businessFlowTemplateId eq 842169fe-e1b7-4ce9-98b6-6a9db02eec6b" $top=1 $skip=0
Bad Request({
  "error": {
    "code": "",
    "message": "Bad filter: One of these properties must be specified: 'businessFlowTemplateId' or 'partnerId' or 'businessFlowId'. List of businessFlowTemplates is available at /businessFlowTemplates",
    "innerError": {
      "date": "2020-10-28T11:18:56",
      "request-id": "18d6a98a-cf41-49e1-9228-f88d025b65ea",
      "client-request-id": "18d6a98a-cf41-49e1-9228-f88d025b65ea"
    }
  }
})
PS C:\Users\roukeb> az rest --method get --url "https://graph.microsoft.com/beta/accessReviews"  --uri-parameters $filter="businessFlowTemplateId eq '842169fe-e1b7-4ce9-98b6-6a9db02eec6b'" $top=1 $skip=0
Bad Request({
  "error": {
    "code": "",
    "message": "Bad filter: One of these properties must be specified: 'businessFlowTemplateId' or 'partnerId' or 'businessFlowId'. List of businessFlowTemplates is available at /businessFlowTemplates",
    "innerError": {
      "date": "2020-10-28T11:19:03",
      "request-id": "1b0d78ea-e912-4814-94d3-05c4ad7c1231",
      "client-request-id": "1b0d78ea-e912-4814-94d3-05c4ad7c1231"
    }
  }
})
PS C:\Users\roukeb> az rest --method get --url "https://graph.microsoft.com/beta/accessReviews"  --uri-parameters $filter="businessFlowTemplateId+eq+'842169fe-e1b7-4ce9-98b6-6a9db02eec6b'" $top=1 $skip=0
Bad Request({
  "error": {
    "code": "",
    "message": "Bad filter: One of these properties must be specified: 'businessFlowTemplateId' or 'partnerId' or 'businessFlowId'. List of businessFlowTemplates is available at /businessFlowTemplates",
    "innerError": {
      "date": "2020-10-28T11:19:10",
      "request-id": "b115393b-7274-489a-bf6d-03a6dd30c6ff",
      "client-request-id": "b115393b-7274-489a-bf6d-03a6dd30c6ff"
    }
  }
})
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d56f62-91d1-6e41-3d8e-c167c2d2d512
* Version Independent ID: af9347f9-6471-3066-3dd7-9c2cfb1f70ec
* Content: [List accessReviews - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/accessreview-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accessreview-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Hi this may be an issue with Github issue quoting, but in your example above it appears you are using a PowerShell environment to run the az command.  In your example, because $filter starts with a dollar symbol character, it is probably being treated as a PowerShell variable name and so is not being sent to the Graph API. In my test I noticed that it not include "$filter" in the URL being sent to Graph.  Try escaping the $ character so that is not treated as a variable, e.g.,  --uri-parameters "%24filter=  instead of --uri-parameters "$filter=      Also I'd suggest adding --verbose as well to see the full Request URL sent to the service.

**Comment by Mobrockers** [comment]
Hi! Thank you that did fix the issue, the request was sent successfully! I did now get an authorization issue even though my user has full permissions on access reviews and as I understand the az cli should be able to handle authentication tokens for the graph api but that's another issue.


Can I just say I think it's pretty awkward to use $ in the query param for a microsoft product when the default microsoft shell can't handle it without url encoding :/ 

Is that a graph filter thing or is that specific to this beta api? If it's specific to the beta api I would kindly suggest you remove that $ sign from the api spec as I'm sure I won't be the only one running into this.

Anyway thanks for your help!

**Comment by markwahl-msft** [comment]
The use of the $ character is part of the OData protocol underlying Graph, so you'll see that it is needed elsewhere in Graph 1.0 as well as beta.

**Comment by Mobrockers** [comment]
> The use of the $ character is part of the OData protocol underlying Graph, so you'll see that it is needed elsewhere in Graph 1.0 as well as beta.

Okay thank you!
