### ISSUE TITLE
Recommended way to add Client-Request-Id to all requests

### ISSUE THREAD

**Issue by adrianmander** [microsoftgraph/microsoft-graph-docs#10465]
The best practices docs say to add a Client-Request-Id header to all SDK requests.
I don't get this header automatically (confirmed in Fiddler); it looks like some intervention is needed.
It works (Again, confirmed in Fiddler) to do this:

`                var headerOptions = new List<HeaderOption>()
                {
                    new HeaderOption("client-request-id", "Hello world")
                };
                IGraphServiceUsersCollectionPage currentPageUsers =
                    await graphServiceClient.Users.Request(headerOptions)
                        .Top(_pageSizes.UsersPageSize)
                        .GetAsync(cancellationToken.Token);
 `
... But this doesn't scale very well, since it has to be repeated everywhere I call Request(). I would rather only set this up once for my entire project. Something along these lines:

` var client = new GraphServiceClient(
                graphBaseUrl,
                new GraphAuthenticationProvider(accessToken),
                _httpProvider);
            client.HttpProvider.AlwaysAddClientRequestIds(If you please);`

Does anyone know the right way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad5cf072-5b76-8cbf-1835-9142257850bb
* Version Independent ID: 82071dbf-2417-1bbd-fa8c-64a711b68d2f
* Content: [Best practices for working with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/best-practices-concept)
* Content Source: [concepts/best-practices-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/best-practices-concept.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adrianmander** [comment]
My IGraphAuthenticationProvider's AuthenticateRequestAsync method provides a hook for adding arbitrary stuff to all  requests headers, including a client-request-id. This feels like a bit of a hack, but it does work. Does anyone foresee any problems doing it this way?

**Comment by MIchaelMainer** [comment]
Setting `client-request-id`  is only helpful if you're logging out the value. I suggest that you take a look at https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/docs/logging-requests.md#a-implementing-a-logginghandler. You can add a new `client-request-id` header with a new guid for every request before it is sent.
