### ISSUE TITLE
Not able to download a file from OneDrive

### ISSUE THREAD

**Issue by truongthang2211** [microsoftgraph/microsoft-graph-docs#10485]
[Enter feedback here]
According to Microsoft Graph's documentation, the API to download file contents of a file in my OneDrive is:

> https://graph.microsoft.com/v1.0/users/7d75128f-d11b-44c5-b6b6-45a68196c178/drive/items/01QOTTV75AYZU6TEKOWVEZ734NY65DKW4S/content

however it was return Status Code 0 and show nothing 

If I just do 

> https://graph.microsoft.com/v1.0/users/7d75128f-d11b-44c5-b6b6-45a68196c178/drive/items/01QOTTV75AYZU6TEKOWVEZ734NY65DKW4S

It returns the correct file metadata - so this means the file exists so any clues why Graph cannot fetch the content

![api1](https://user-images.githubusercontent.com/59715444/97694670-8401d180-1ad5-11eb-8a86-bea52f47de20.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f920b06-ceec-49eb-5628-f94cf64bacae
* Version Independent ID: 9e15429d-b51f-7c10-4d0b-cc06569735d4
* Content: [Download a file - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by solarseven** [comment]
I can confirm that this is also the case with the "GET /me/drive/items/{item-id}/content" call.
This call returns an empty response "{}" in the Graph Explorer.

From this I conclude that right now the "/content" does not actually do what the documentation describes it should do.

**Comment by NikitaRomanenko** [comment]
in my case I have 400 error while trying : https://graph.microsoft.com/v1.0/me/drive/items/015JN4C72LQSEWJGZXQNB2ABCM2SYVHHJ7/content
<img width="834" alt="Снимок экрана 2021-03-01 в 17 35 24" src="https://user-images.githubusercontent.com/38432639/109520155-97896d00-7ab4-11eb-9ecc-ec08aa9157a3.png">

**Comment by jlangedk** [comment]
I also get nothing or {} if I try this in the graph explorer:  https://graph.microsoft.com/v1.0/me/drive/root:/Attachments/Alpha%203.ply:/content

**Comment by jlangedk** [comment]
I contacted Microsoft Azure Support and got this answer: "_Currently, it's not possible to download the file content using Graph Explorer - every request comes back with "0" as response code, and null contents/headers._"

I tried the same thing from code, and after a few bugs I got it up and running
