### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by pedro-ramirez-suarez** [microsoftgraph/microsoft-graph-docs#10496]
The links to GitHub are broken, neither the sample code or the deploy instructions work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1892fb12-8994-0c53-e761-c8c75360e792
* Version Independent ID: 3fdd5b67-a0d9-2122-2f8a-6110ba9b25a0
* Content: [Manage phone numbers for bots - Microsoft Graph](https://docs.microsoft.com/en-us/graph/cloud-communications-phone-number)
* Content Source: [concepts/cloud-communications-phone-number.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/cloud-communications-phone-number.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@isvargasmsft could you please check the following? It seems like links in the See also section should point to V1.0 now:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/RemoteMediaSamples/IncidentBot

https://github.com/microsoftgraph/microsoft-graph-comms-samples/blob/master/Samples/V1.0Samples/RemoteMediaSamples/README.md#deploying-the-sample

There is also a link to Skype for Business Online Module which needs to be updated too.

**Comment by lramosvea** [comment]
Closing as doc has been updated and links have been fixed
