### ISSUE TITLE
issue with task details patch 

### ISSUE THREAD

**Issue by kodeprav** [microsoftgraph/microsoft-graph-docs#1049]
I see below error when I try to update task details. My If-Match etag matches task etag. I dont think that is an issue.  What is the best way to debug these issues?
 
client-request-id: 00dbaf4c-a772-4902-9c7e-e8674f78842e
content-type: application/json
cache-control: private
request-id: 00dbaf4c-a772-4902-9c7e-e8674f78842e
Status Code: 412
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "00dbaf4c-a772-4902-9c7e-e8674f78842e",
            "date": "2017-04-05T21:37:29"
        }
    }
}

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
