### ISSUE TITLE
printDocument: createUploadSession - Unsupported document-format: application/pdf

### ISSUE THREAD

**Issue by elvinristi** [microsoftgraph/microsoft-graph-docs#10498]
After getting required permissions based https://github.com/microsoftgraph/microsoft-graph-docs/issues/10486 I was able now to call `print/shares/{{PrinterId}}/jobs/{{JobId}}/documents/{{DocumentId}}/createUploadSession` request without getting `UnknownError`.

[Example page](https://docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta) 
 (and is also our need) shows POST call with body `"contentType": "application/pdf"`

but when executing this then graph api returns error by saying that only `application/oxps` is supported:

```
Unsupported document-format: application/pdf. Supported formats: Attribute document-format-supported: SimpleIppValue-Type:MimeMediaType-Value:application/oxps
```

Why createUploadSession with `application/pdf` can't be called?

Example request:
```
{
    "properties": {
        "documentName": "example.pdf",
        "contentType": "application/pdf",
        "size": 144547
    }
}
```

Example response on this
```
{
    "error": {
        "code": "415",
        "message": "Unsupported document-format: application/pdf. Supported formats: Attribute document-format-supported: SimpleIppValue-Type:MimeMediaType-Value:application/oxps\n",
        "innerError": {
            "date": "2020-11-02T07:14:30",
            "request-id": "cac0834d-fcc7-4111-9fbb-9f3a99fa85ab",
            "client-request-id": "cac0834d-fcc7-4111-9fbb-9f3a99fa85ab"
        }
    }
}
```

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926d05ed-3eb1-5bd4-f86a-c3be35cbe8ce
* Version Independent ID: b6f59259-ac71-9fd2-d406-39768ba1e3a7
* Content: [printDocument: createUploadSession - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/printdocument-createuploadsession.md)
* Product: **universal-print**
* Technology: **microsoft-graph**
* GitHub Login: @nilakhan
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nilakhan** [comment]
contentType being passed to createUploadSession must be supported by printer/printerShare. 
In this case, printerShare supports only application/oxps. 
This can be verified by following request: 
GET print/shares/{{PrinterShareId}}?$select=id,displayName,capabilities. 
Here, you can see the content types supported by this particular printerShare.

**Comment by elvinristi** [comment]
Thank you for the replies, @nilakhan !

I see under capabilities.supportedDocumentMimeTypes only application/oxps
```
    "capabilities": {
        "isColorPrintingSupported": true,
        "supportsFitPdfToPage": false,
        "supportedDocumentMimeTypes": [
            "application/oxps"
        ],
        "supportedFinishings": [
            "none"
        ],
```

Tried PATCH `print/shares/{{PrinterShareId}}` with
```
{
    "capabilities": {
        "contentTypes": ["application/pdf", "application/oxps"]
    }
}
```
but seems it's read-only - `Printer share capabilities are read only`

Under Universal Print management under Printer Options "Content type" has also only 1 option - application/oxps
![image](https://user-images.githubusercontent.com/3975860/97964563-a50e3f00-1dc1-11eb-8bb7-a3eeec867ef1.png)

Where this can be extended?

**Comment by nilakhan** [comment]
@elvinristi printerShare capabilities cannot be updated by user right now. They are provided by the printer behind the printerShare. 
Are you using Microsoft Universal Print connector? If yes, it only supports application/oxps right now.
