### ISSUE TITLE
Inconsistant unseenCount value

### ISSUE THREAD

**Issue by Benjpoirier** [microsoftgraph/microsoft-graph-docs#105]
I try to get unseenCount property from /beta/groups/<id> and the value is not returned. I have to specify a $select property to get it. The value returned is the same for all my team mate and is not equal to outlook groups notifications.
i would like to know if this feature is in developement ?

**Comment by martellaj** [comment]
Thanks for the feedback, @Benjpoirier. I think @dkershaw10 will be able to provide more insight on the feature than I can. :+1:

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
