### ISSUE TITLE
Returned list of chats does not inlcude chat threads attached to meetings

### ISSUE THREAD

**Issue by chrisbardon** [microsoftgraph/microsoft-graph-docs#10521]
I'm not sure if this is intentional or not, but if I pull the list of my chats, I get 1:1 and group chats, but not meeting threads that are listed in the chat tab in Teams.  If those aren't going to show up in this query, is there another way to retrieve the chat contents of a historical meeting? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79531fbc-dd22-cf80-c97c-746f7dcab790
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@chrisbardon , [List Chat](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http), API returns 1:1 or group chats, not meeting chat history. We asked engineering team for confirmation is this by design or Bug.

**Comment by Trinetra-MSFT** [comment]
@chrisbardon , Issue is Resolved now, I'm able to get the meeting chat in response, 
`{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#chats",
    "@odata.count": 154,
    "value": [
        {
            "id": "19:meeting_YzVkY2E0NxxxxxxxxxxxxxxxxxxxxTM1YjRlMjkxYzEy@thread.v2",
            "topic": "test meeting chat",
            "createdDateTime": "2020-11-04T10:55:12.29Z",
            "lastUpdatedDateTime": "2020-11-04T11:16:10.54Z"
        },
        {
            "id": "19:3xxxxxxxxxxxxxxxxxxxxxxxx5@thread.v2",
            "topic": "Test Group",
            "createdDateTime": "2020-05-11T12:36:04.093Z",
            "lastUpdatedDateTime": "2020-05-15T07:21:10.789Z"
        }
]
}`
Could you please confirm?
Let me know if you still facing this issue.

**Comment by chrisbardon** [comment]
Yes, looks to be resolved now-thanks!
