### ISSUE TITLE
Security Groups not mentioned 

### ISSUE THREAD

**Issue by aksoftware98** [microsoftgraph/microsoft-graph-docs#10536]
Hi

I was checking this doc, and I wanted to see how to create a Security Group using the POST endpoint mentioned here, but all the examples exist are for Microsoft 365 groups 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aksoftware98** [comment]
I have discovered it was pretty easy but better to mention that in a note or something in the documentation 

While trying to create a Security Group instead of Microsoft 365 Group just in the request object in the body leave the value of  _**GroupTypes**_ set to null 
Then the type of the group by default is going to be Security Group when it is created 

Thanks for that awesome API & Documentation

**Comment by yyuank** [comment]
Thank you for the suggestion. We will update the document to clarify security group creation.
