### ISSUE TITLE
Error while running the informationProtection API

### ISSUE THREAD

**Issue by SruthiJeelugula** [microsoftgraph/microsoft-graph-docs#10531]
Getting below error while running `labels available to the organization` after providing the required permission
`https://graph.microsoft.com/beta/informationProtection/policy/labels`

```
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2020-11-03T16:02:58",
            "request-id": "13a82bc3-2325-43df-a9b6-ed29508fa985",
            "client-request-id": "92153d1b-a3ae-84fc-056e-d1bd697123ef"
        }
    }
}
 
```
![image](https://user-images.githubusercontent.com/61568311/98124072-b39b4a00-1ed8-11eb-82bf-cda1efff7372.png)

facing issue with MS Graph sdk
`var labels = await graphClient.Users["sruthi@XXX.live"].InformationProtection.Policy.Labels.Request().GetAsync();`
![image](https://user-images.githubusercontent.com/61568311/98123817-5f906580-1ed8-11eb-8aee-e90198f3b7c5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da17f77-de16-97ad-22d3-9fe3ea30fd3e
* Version Independent ID: 0fbb3be6-d763-7418-bcad-e78838e113b8
* Content: [informationProtectionLabel: listLabels - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/informationprotectionpolicy-list-labels?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/informationprotectionpolicy-list-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/informationprotectionpolicy-list-labels.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @tommoser
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cwdata** [comment]
Same API, same problem here. But we also get a message inside the error object:
`<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>Microsoft-Azure-Application-Gateway/v2</center>\r\n</body>\r\n</html>\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n`

**Comment by tommoser** [comment]
The bad gateway issue should now be resolved. 

Have you published a labeling policy in security and compliance center? (https://security.microsoft.com)

**Comment by cwdata** [comment]
@tommoser 
the bad gateway message is now gone. Now we're facing the same empty "unknown error" as the OP.
We have published 2 labeling policies in the security center.

**Comment by tommoser** [comment]
I'm able to reproduce this if I haven't set permissions. It looks like Graph Explorer requires an extra step where you need to provide consent. In the latest UX, click the gear next to the logged in user on the left, **select permissions**, then find the InformationProtectionPolicy.Read and make sure it's selected. 

![image](https://user-images.githubusercontent.com/36175320/103837884-85ed9100-5040-11eb-8b63-e12631925420.png)

**Comment by cwdata** [comment]
@tommoser,
thanks for investigating the GE issue. As I've written before, I already consented to that API:
![grafik](https://user-images.githubusercontent.com/26869201/103869095-276cf500-50ca-11eb-884e-00412f419bf5.png)
When checking the permissions via the gear icon next to the user it shows the same. There is no button to 're-consent'.
The API itself still works when it is called from within an Azure runbook.

**Comment by bsylla** [comment]
Hello, any update on this issue?

**Comment by tommoser** [comment]
The issue is due to the endpoint you're using.

https://graph.microsoft.com/beta/informationProtection/policy/labels is only for applications with the InformationProtectionPolicy.Read.All right.

If you're using a user token, you should use https://graph.microsoft.com/beta/me/informationProtection/policy/labels

**Comment by bsylla** [comment]
Thanks a lot I fixed the permission!
It's working properly.

**Comment by cwdata** [comment]
@tommoser 
works for me too in Graph Explorer when adding /me/.
Can we assume that this will change when the API goes GA? To my knowledge there is no concept of "my policy labels". They are centrally stored / managed and the endpoint should not change depending on the type of token that is used.

**Comment by tommoser** [comment]
@cwdata The Graph endpoint for MIP labels is intended to expose only the **published** labels for a user. Think of it not as a management API that lists all labels, but as a user or application API that enables apps and services to list labels on behalf of a user. When I call the endpoint, I'm seeing **my** labels. If an application calls the endpoint, it can fetch all published labels in the tenant (a union of all labels that are defined in a label policy). Labels not added to any policy aren't included. 

A concrete example would be a mobile application that wants to fetch labels. I open the app, it signs me in and connects to Grapt to fetch the labels that I can use for labeling information in that application.
