### ISSUE TITLE
GetMessage On Old Messages Returns 400 Not Found Error

### ISSUE THREAD

**Issue by speschka** [microsoftgraph/microsoft-graph-docs#10553]
When you get a list of messages for a channel, using the List Messages API as described here:  https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http, it gives you a list of all messages in the channel.  However some of those messages are older and no longer show up in the Teams client.  When you try and retrieve one of those messages using the GetMessage API described on this page, it returns a 400 Not Found error.  This should, at a minimum, be documented (or fixed if that is not the intended behavior).  Also, a work-around should be described or linked to that allows you to get a historically accurate list of all messages in a given channel.

Thanks,

Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01baf176-9ca8-79c7-c84f-b4165c84e0dd
* Version Independent ID: 62950fbf-7f47-f062-b0dd-e457b6c4f9ea
* Content: [Get channel message - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-get-message.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
we could not repro the issue at our end. When messages are not shown in team client then How did you get the message id to retrieve the message using the GetMessage API ? Could you please share the repro steps?

**Comment by speschka** [comment]
The repro steps are what's in the original issue I opened.  I had a couple of old messages that stopped showing up in the Teams client.  So they weren't deleted, they were apparently just aged out.  I have an app that is retrieving all messages for a channel and exporting them.  So to get all of the messages I use the List messages API as described in my original post.  It returns all messages that were ever in the channel, including the ones that the Teams client does not display.  I then go through each ID it returns and call the GetMessage API on it.  When I try the message IDs that aren't displayed in the Teams client (but which were never deleted - they just aged out), I get the 400 Not found error.

If you want specific IDs for my tenant, team and channel so you can try it yourself let me know and tell me how to post it privately.

**Comment by Nikitha-MSFT** [comment]
Could you please share the client request id?

**Comment by speschka** [comment]
Sure, here's a client request ID from a request I just made:  96a78a97-3247-41e8-99df-aad8e44b99d5

It returned a total of 7 messages; in the Teams client it shows a total of 2 messages.  The thing is, as I mentioned at the start, to be historically accurate I really want all seven messages.

**Comment by Nikitha-MSFT** [comment]
Could you please share time stamp also?

**Comment by speschka** [comment]
Okay, here's the complete header list from another query I just did with the same results:  

{Cache-Control: private
request-id: 8e6a3650-4897-4820-8782-a1d30475157f
client-request-id: 8e6a3650-4897-4820-8782-a1d30475157f
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"South Central US","Slice":"SliceC","Ring":"3","ScaleUnit":"000","RoleInstance":"AGSFE_IN_55"}}
OData-Version: 4.0
Strict-Transport-Security: max-age=31536000
Date: Wed, 25 Nov 2020 16:00:03 GMT
}

**Comment by Manish-MSFT** [comment]
@speschka , Are you still facing issue with this?

**Comment by speschka** [comment]
Hi Manish, I just tested it again and yes, I'm still getting messages from the list messages API that return a 404 not found when I try and retrieve the individual message.

**Comment by Nikitha-MSFT** [comment]
When the messages are deleted in Teams Client, You cannot get details of the deleted messages using API. This is by design.

**Comment by speschka** [comment]
Hmm.  Well if you can't get details of a message, then why include it with the list of messages for the channel?  You should either be all the way in or all the way out.  All the way in would be better, because as far as I can tell you no longer have a way (via Graph at least) in which to get a complete archive.  How does that fit into the Microsoft story around legal discovery?  It's extensive in SharePoint but this approach seems to leave us with gaps.
