### ISSUE TITLE
Missing third type of report under Azure AD provides three types of activity reports:

### ISSUE THREAD

**Issue by seancorryio** [microsoftgraph/microsoft-graph-docs#10622]
Missing third type of report from text below 

"What are Azure AD activity logs?
Azure AD provides three types of activity reports:

audit logs
sign-in logs
????????"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3a74bbc-2a8b-1ff6-78e3-e33f143e41db
* Version Independent ID: b9f3185c-1406-e1eb-99b8-edbc84c4e58a
* Content: [Activity reports API overview - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-1.0&source=docs)
* Content Source: [api-reference/v1.0/resources/azure-ad-auditlog-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/azure-ad-auditlog-overview.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by CelesteDG** [comment]
@davidmu1 and @FaithOmbongi - Please take a look at this one. Looks like a missing entry in the docs or a possible typo
