### ISSUE TITLE
Does calendars support immutable ids

### ISSUE THREAD

**Issue by jbiversen** [microsoftgraph/microsoft-graph-docs#10626]
The page says that calendars (and other containers) doesn't support immutable ids, but if I call /me/calendars with the Prefer header set to IdType="ImmutableId", the call returns other ids than when without the header set. Also I have experienced that calendar ids have changed, so I would like to use this feature if it works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dc8516-103a-7df2-2685-1ce9045941b5
* Version Independent ID: 90ebf4ab-1563-4a6d-d184-c91159352366
* Content: [Get immutable identifiers for Outlook resources - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-immutable-id)
* Content Source: [concepts/outlook-immutable-id.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-immutable-id.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@Harini84 - Can you confirm/deny immutable ID support for calendars? When the feature was shipped I was advised that all containers (mailFolders, contactFolders, calendars, etc.) did not support immutable ID since their normal IDs never change.

However, I do see the same behavior reported.

**Comment by Harini84** [comment]
@jasonjoh 
Yes calendar IDs do not change as calendars are containers. There was an issue reported by a partner as well that the calendar ID is getting changed. This issue has been fixed and the fix is being rolled out to worldwide.

Thanks

**Comment by jbiversen** [comment]
@Harini84 When was the issue fixed, and when is it expected that the roll out is completed?
