### ISSUE TITLE
How to update application logo using microsoft graph api

### ISSUE THREAD

**Issue by bhanu7git** [microsoftgraph/microsoft-graph-docs#10654]
I want to update applicaion logo using microsoft graph api in python

When i look at documentation, it mentions the type as stream. How can i include stream in json body of http patch request
Any example would be appreciated for this use case in documentation. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6afab3-9682-0f8e-0441-2adfde3f84ef
* Version Independent ID: 6eee450a-b6d0-0908-0392-00e01d412185
* Content: [Update application - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bhanu7git** [comment]
any help would be appreciated

**Comment by FaithOmbongi** [comment]
Thank you @bhanu7git for your question. To get support updating this parameter, kindly ask the question at the [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) channel. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). 

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
