### ISSUE TITLE
Unable to filter othermail and identities properties

### ISSUE THREAD

**Issue by SruthiJeelugula** [microsoftgraph/microsoft-graph-docs#10672]
Facing issue while querying the below request
`https://graph.microsoft.com/beta/users?$filter=otherMails/any(id:id eq 'mary@nishantsingh.live') or identities/any(c:c/issuerAssignedId eq 'mary@xxx.live' and c/issuer eq 'xxx')`

{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Complex query on property identities is not supported.",
        "innerError": {
            "date": "2020-11-13T11:52:48",
            "request-id": "3a1e82f6-033e-432c-9b5d-475f9109187c",
            "client-request-id": "896a2a92-85fc-6e23-66c8-30b9a1e8bcdf"
        }
    }
}
![image](https://user-images.githubusercontent.com/61568311/99105375-6de12e80-2608-11eb-8bc6-0cc661bd8a07.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabdb652-eb03-bae6-fa99-66d71fbdd044
* Version Independent ID: 7f5744b6-6770-586e-217c-4b7ac7657051
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sam-wheat** [comment]
I am facing the same issue as OP.  

        public async Task<User> GetUserByEmailAddress(string email)
        {
            IGraphServiceUsersCollectionPage users = await client.Users.Request()
                .Select(x => new { x.Id, x.Mail, x.OtherMails, x.Identities })
                .Filter($"mail eq '{email}' or otherMails/any(id:id eq '{email}') or identities/any(ids:ids/issuerassignedid eq '{email}' and ids/signintype eq 'emailAddress')")
                .GetAsync();

            if(users.Any())
                return users[0];
            
            return null;
        }


Error Message:

>  Message: Complex query on property identities is not supported.
    Inner error:
    	AdditionalData:
    	date: 2020-11-22T14:35:10
    	request-id: 23588b52-bfe8-4a89-9c83-de2568ab8af5
    	client-request-id: 23588b52-bfe8-4a89-9c83-de2568ab8af5
    ClientRequestId: 23588b52-bfe8-4a89-9c83-de2568ab8af5
    
  
> Stack Trace: 
    HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
    BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
    BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
    GraphServiceUsersCollectionRequest.GetAsync(CancellationToken cancellationToken)

**Comment by FaithOmbongi** [comment]
Hi @SruthiJeelugula 

As @sam-wheat shared, filter by identities and another property is currently unsupported - hence the error.
