### ISSUE TITLE
Uploading files to a folder shared to you in ODFB fails

### ISSUE THREAD

**Issue by Mike-Bell** [microsoftgraph/microsoft-graph-docs#107]
I am able to upload files to folders in my OneDrive (for business) just fine using the methods documented here http://graph.microsoft.io/docs/api-reference/v1.0/api/item_uploadcontent. E.g. `PUT https://graph.microsoft.com/v1.0/users/<myUserId>/drive/root:/<someFolderPath>/<someFileName>:/content` (for good measure, I've actually used all three methods listed there).

As soon as I try to upload to a folder shared with me in ODFB, the upload fails with 

```
{
  "error": {
    "code": "unauthenticated",
    "message": "The caller is not authenticated.",
    "innerError": {
      "request-id": "6361fe4f-5c6c-4b33-af72-18f8e679b787",
      "date": "2016-01-22T15:47:19"
    }
  }
}
```

I know I have access to this folder because I can retrieve files from it, and even grab the folder's metadata. I most certainly am authenticated, because I'm sharing the same access token I use in all my code that works fine (and it's the same code that allows me to upload to my folders). The token is clearly in the header.

It seems like the API is 1) failing and 2) returning a faulty error message.

**Comment by michaelhoes** [comment]
I have exactly the same issue. is this a bug? When will it be fixed?

**Comment by fundenys** [comment]
Hi,
it s same to me with 
https://graph.microsoft.com/v1.0/drives/{id shared drive}/items/{folderid}:/{filename:/createUploadSession

error is 
{
    "error": {
        "code": "notAllowed",
        "message": "The action is not allowed by the system.",
        "innerError": {
            "request-id": "17d0c0f4-a775-4865-b958-e4277f3bd629",
            "date": "2016-10-07T14:00:09"
        }
    }
}
thank you to allow uploads to a shared folder

**Comment by alx-andru** [comment]
This looks exactly like the issue I'm facing which I posted yesterday on [stackoverflow](http://stackoverflow.com/questions/43332222/upload-a-large-file-in-microsoft-graph-api-asp-net-access-denied)

@rgregg any updates on this issue or a way to help investigating further?

@michaelhoes did you find a workaround for it? meanwhile?

**Comment by bpkennedy** [comment]
Same issue here.
