### ISSUE TITLE
Availability of Planner task Priority field in version 1.0 ?

### ISSUE THREAD

**Issue by shruti666** [microsoftgraph/microsoft-graph-docs#10741]
When will be the Priority field for planner task available in version 1.0 ? Looks like it was added in beta version in the month of Aug 2019.  Please can anyone update or can anyone advise where it needs to be checked ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e496bc30-ad9f-93ca-e99d-83306a415dbf
* Version Independent ID: 407a66f9-652c-7c27-4bba-967fd856cc83
* Content: [plannerTask resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-1.0&preserve-view=true)
* Content Source: [api-reference/v1.0/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/plannertask.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Queries666** [comment]
Please update me on the above information.

**Comment by aqyx** [comment]
GetTask_Response_V3 does include Priority field, but there isn’t a GetTask_V3 (yet).

**Comment by shruti666** [comment]
> GetTask_Response_V3 does include Priority field, but there isn’t a GetTask_V3 (yet).

If we check this link https://docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-1.0&preserve-view=true , we don't have a Priority field in PlannerTask Properties but we do have assigneePriority which associates to the task assignments. 

If its already present, may i ask for a link which can redirect me there?

**Comment by aqyx** [comment]
Sorry, I'm in the wrong board. I was referring to the Planner connector actions within Power Automate rather than Graph.

**Comment by sankeeth-chinta** [comment]
@TarkanSevilmis  Could you please let me know when can we expect  "Priority", "DueDateTime" for MS planner task availability in 1.0 version of graph?

I see that the properties mentioned above are in beta version.

thanks

**Comment by lramosvea** [comment]
Closing as docs have been updated. Please feel free to reopen if the issue persists.
