### ISSUE TITLE
Error status more documentation needed for scenario

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [microsoftgraph/microsoft-graph-docs#10757]
Multiple customer requests have come for more details on the 'Error' status of the invitation API. What are some scenarios where this Error in the Status field is triggered?  More documentation on this will help
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0170d-e214-ce6f-b7b4-589960e9962d
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/invitation.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @elisolMS
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jeevanbalanmanoj** [comment]
@FaithOmbongi  Do we have an ETA on this change?

**Comment by FaithOmbongi** [comment]
Hello @jeevanbalanmanoj ,

Kindly refer to the [invitation redemption flow ](https://docs.microsoft.com/en-us/azure/active-directory/external-identities/redemption-experience#invitation-redemption-flow) in Azure docs. The section after point 11 provides a scenario when the user/invitation **status** can hit an error.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
