### ISSUE TITLE
Length of URL in OneDrive for Business in Microsoft graph is too short

### ISSUE THREAD

**Issue by Prakashverma042** [microsoftgraph/microsoft-graph-docs#1075]
We are using OneDrive for Business to store files. Currently the limit of URL length is only 260 characters. This length is not reasonable for real applications. This should be at least 500 characters. So that it can solve following problems:-

1. Files with larger name uploads
2. Path flows can be supported (like: folder 1 -> folder 2..........-> folder 10->file).

This restriction on URL limit causing so many problems to the user.  So it should be resolved ASAP.

**Comment by jthake-msft** [comment]
This is a feature request. As per the issue template creation process, feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support


This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
