### ISSUE TITLE
max results when pagination is not supported? 

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-docs#10760]
Hi @nkramer 

There is a comment that this api does not support pagination. The page doesn't state what the max default value is - so doesn't make it clear how many results we can expect to get (or more to the point, the number of results we might miss...). 

also, this api is listed against the Teams (so Team members) - but am i correct to assume that it's essentially the same if we call it against a channel of the team rather than the team itself. My understanding is that a public channel implicitly has the same members as the parent team and a private channel may have membership which is a subset of the team members. 

thanks very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf854943-7edf-1dfa-14c4-b8877537cb06
* Version Independent ID: 83151040-4b99-2389-87da-b49443af92bf
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-list-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamaMohanaChary** [comment]
@AlexSapple, Pagination is supported here. Documentations are in process to update.

**Comment by AlexSapple** [comment]
brilliant - thanks @RamaMohanaChary. Closing this now.
