### ISSUE TITLE
EducationClass creation API docs issue

### ISSUE THREAD

**Issue by niloyc** [microsoftgraph/microsoft-graph-docs#10777]
There seems to be something mismatch with the documentation, For educationClass type team creation.

When doing the following,
```
POST https://graph.microsoft.com/v1.0/teams
{
  "template@odata.bind": "https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
  "displayName": "DisplayName",
  "description": "Description"
}
```
There is error returning below message
```
"errors": [{
	"message": "'Team Definition. Visibility' should be equal to 'HiddenMembership'."
}]
```

But when the request is changed to the following,

```
POST https://graph.microsoft.com/v1.0/teams
{
  'template@odata.bind': "https://graph.microsoft.com/beta/teamsTemplates('educationClass')",
  displayName: 'DisplayName',
  description: 'Description',
  visibility: 'HiddenMembership',  // <--------- Specified here
  members: [
    {
      '@odata.type': '#microsoft.graph.aadUserConversationMember',
      roles: ['owner'],
      userId: 'id'
    }
  ]
}
```
Now the error becomes,
```
"errors": [{
	"message": "Team Visibility must be one of known types: [Private, Public, HiddenMembership]."
}]
```
What is the correct way to proceed here? documentation isn't covering this.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by niloyc** [comment]
Also to add further information there is no documentation about HiddenMembership here
https://docs.microsoft.com/en-us/graph/api/resources/teamvisibilitytype?view=graph-rest-1.0

**Comment by SjoerdDerks** [comment]
Same Error here, This worked  fine last week

{
  "description": "DEV-TEST-EDU",
  "displayName": "DEV-TEST-EDU",
  "owners@odata.bind": [
    "https://graph.microsoft.com/beta/users('xxxxxx-fb1d-41c3-8efb-xxxxxxxx')"
  ],
  "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('educationClass')"
}

If I change educationClass to "Standard" the Team gets created.

**Comment by JElliott242** [comment]
This is being discussed on the [Teams Developer Tech Community](https://techcommunity.microsoft.com/t5/teams-developer/microsoft-graph-api-create-team-visibility-hiddenmembership/m-p/1926611) as well. affecting both v1.0 and beta APIs.

it looks like it has something to do with the way/timing that the educationClass template applies the HiddenMembership visibility setting.

As a workaround, I tried to create the group first and then create a team with the educationClass template leveraging that group, but it still failed due to HiddenMembership being applied to the group already.

**Comment by Nikitha-MSFT** [comment]
We are looking into it.

**Comment by Nikitha-MSFT** [comment]
@niloyc The issue ha ben fixed. Could you please check it now and let us know if you face any issues.

**Comment by niloyc** [comment]
Unfortunately now it is showing new error,

```
{
  'template@odata.bind': "https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
  displayName: 'Testing team creation',
  description: 'Testing team creation description',
  visibility: undefined,
  members: [
    {
      '@odata.type': '#microsoft.graph.aadUserConversationMember',
      roles: ['owner'],
      userId: '1728415c-e750-4fbe-8585-51f7ed5efa50'
    }
  ]
}
```
I get the below error
```
error: {
    code: 'BadRequest',
    message: 'The navigation bind for the user was missing in request',
    innerError: {
      date: '2020-11-26T06:07:21',
      'request-id': '26c00b59-9aee-4693-b528-cb9731bea2a1',
      'client-request-id': '26c00b59-9aee-4693-b528-cb9731bea2a1'
    }
  }
```

**Comment by evengelen** [comment]
change userId: '1728415c-e750-4fbe-8585-51f7ed5efa50' in 
"user@odata.bind":"https://graph.microsoft.com/v1.0/users('1728415c-e750-4fbe-8585-51f7ed5efa50')"

And it will run.

**Comment by evengelen** [comment]
Example off the body i used in my test request:

{
   "template@odata.bind":"https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
   "displayName":"_Testeve_educationClass-Team2",
   "description":"_Testeve_educationClass-Team2 description",
   "members":[
      {
         "@odata.type":"#microsoft.graph.aadUserConversationMember",
         "roles":[
            "owner"
         ],
         "user@odata.bind":"https://graph.microsoft.com/v1.0/users('4xxxxd8b-953f-xxxx-ad4d-9a2652130af5')"
      }
	  
   ]
}

**Comment by evengelen** [comment]
Example off the body i used in my test request:

`{
   "template@odata.bind":"https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
   "displayName":"_Testeve_educationClass-Team2",
   "description":"_Testeve_educationClass-Team2 description",
   "members":[
      {
         "@odata.type":"#microsoft.graph.aadUserConversationMember",
         "roles":[
            "owner"
         ],
         "user@odata.bind":"https://graph.microsoft.com/v1.0/users('42f61d8b-953f-45c2-ad4d-9a2652130af5')"
      }
	  
   ]
}`

**Comment by evengelen** [comment]
Simple test body should look like:

$body
{
   "template@odata.bind":"https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')",
   "displayName":"_Testeve_educationClass-Team2",
   "description":"_Testeve_educationClass-Team2 description",
   "members":[
      {
         "@odata.type":"#microsoft.graph.aadUserConversationMember",
         "roles":[
            "owner"
         ],
         "user@odata.bind":"https://graph.microsoft.com/v1.0/users('42f61d8b-953f-45c2-ad4d-9a2652130af5')"
      }
	  
   ]
}

**Comment by niloyc** [comment]
@Nikitha-MSFT The solution by @evengelen is working. I guess the document just need to be updated then to reflect that?

**Comment by jsh12122020** [comment]
@Nikitha-MSFT - I am receiving the same {
  "error": {
    "code": "BadRequest",
    "message": "The navigation bind for the user was missing in request",
    "innerError": {
      "date": "2020-12-11T20:45:06",
      "request-id": "4dcefa70-514f-48bd-b0b4-108531afca77",
      "client-request-id": "4dcefa70-514f-48bd-b0b4-108531afca77"
    }
  }
}

My simple request body is 

{
  "description": "TestTeamDescription",
  "displayName": "TestTeam",
  "visibility": "private",
  "members": [
    {
      "roles": [
        "owner"
      ],
      "@odata.type": "microsoft.graph.aadUserConversationMember",
      "user@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/('8f96518e-bf96-403c-a4ce-8444e676f423')"
      ]
    }
  ],
  "@odata.type": "microsoft.graph.team"
}

**Comment by VaraPrasad-MSFT** [comment]
Could you please check the required [permissions ](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#permissions)as mentioned.
