### ISSUE TITLE
Response isn't collection of group objects

### ISSUE THREAD

**Issue by jpalo** [microsoftgraph/microsoft-graph-docs#10785]
Response isn't collection of _[group](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/group.md)_ objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 928d261b-20d1-0535-ae15-f262bd24c0ad
* Version Independent ID: 96acbdc6-53ab-df6b-5f8f-ba5b28009d4f
* Content: [List joinedTeams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-joinedteams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@jpalo , ListJoinedTeams graph API return object of collection of teams? what do you mean by response is  not `collection of group object `?, We create team under the group and group id and team id is same.

**Comment by jpalo** [comment]
![image](https://user-images.githubusercontent.com/6917905/100437638-b9381a00-30a9-11eb-8d31-8e8916e3e238.png)

**Comment by Trinetra-MSFT** [comment]
@jpalo , Let me check this internally for confirmation, properties are different, will get back to you in sometime

**Comment by Trinetra-MSFT** [comment]
@jpalo , It need to be corrected to collection of Teams object rather group objects

**Comment by Trinetra-MSFT** [comment]
@laujan , @KirtiPereira , Could you please help to update the above mentioned text in screenshot [Group ](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http#response) to "Team" and update the hyperlink to this one: [https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0](https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0)
