### ISSUE TITLE
Unable to git list of InformationProtectionLabel: listLabels

### ISSUE THREAD

**Issue by hamadaalrefaie** [microsoftgraph/microsoft-graph-docs#10837]
# Bad Gateway 502

I have been using this End Api **GET /me/informationProtection/policy/labels** since January, suddenly today crashed and getting Bad Gateway 502.

![image](https://user-images.githubusercontent.com/32296648/100333462-e82f8c80-2fd2-11eb-9504-d26028691b1c.png)

Please check this and give us more info about this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da17f77-de16-97ad-22d3-9fe3ea30fd3e
* Version Independent ID: 0fbb3be6-d763-7418-bcad-e78838e113b8
* Content: [informationProtectionLabel: listLabels - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/informationprotectionpolicy-list-labels?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/informationprotectionpolicy-list-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/informationprotectionpolicy-list-labels.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @tommoser
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hamadaalrefaie** [comment]
@luviz check this out

**Comment by tommoser** [comment]
This issue should now be resolved.

**Comment by golankopi** [comment]
hi, any update on that? still happens on every request

**Comment by tommoser** [comment]
I'm not able to reproduce this error. Where are you getting this error? Graph Explorer, Postman, etc.?

**Comment by golankopi** [comment]
@tommoser both, every request with an admin consented user gets 403 with similar error:

```
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2020-12-28T16:22:49",
            "request-id": "b83c0eec-dd9d-436c-8ad8-7bf1e103d2e6",
            "client-request-id": "767598ff-4a1b-add7-a84e-de42f95d7279"
        }
    }
}
```

**Comment by hamadaalrefaie** [comment]
@tommoser i had this issue for about 10 day, but everything went back working, maybe it was some bug. microsoft was working on it. but at that time i had it everywhere graph, postman you name it

**Comment by tommoser** [comment]
@golankopi You've published labels via Security and Compliance Center? Not just a label, but the label policy as well? 

You might also want to try to install the AIP client (https://aka.ms/aipclient) to verify that it's able to fetch policy. If it can't, it's likely that you haven't published the policy.

**Comment by tommoser** [comment]
I'll have to check, but I believe we require the /me segment, or an email address there.

**Comment by tommoser** [comment]
It looks like other services also require the /me/ URL. The service team mentioned that they do require this segment and that without it, you're requesting labels for the whole tenant, which is what you've found.
