### ISSUE TITLE
Error 7503 Application is not registered in our store when calling API - .NET SDK

### ISSUE THREAD

**Issue by josephwasily** [microsoftgraph/microsoft-graph-docs#10845]
We are trying to build a calling bot that can join a scheduled teams group call (events) according to example 5, we've followed the documentation for registering a calling bot (the azure subscription flow)
So right now, we have the following configured:
1) Azure Bot Service with Teams channel enabled for calling and messaging.
2) Microsoft Teams App created through App Studio in teams and added to the third-party apps in the tenant we are testing our bot in
3) Azure App Registration with all required application permission for calling and joining group calls, and the testing tenant admin have consented to all permissions on behalf of the organization.
after that, we started building a graph client using .NET SDK (beta) and authenticate it using our application id and secret (through ConfidentialClientApplicationBuilder class), and then we are initiating a call to an online meeting, but we are still receiving the following error 

> Status Code: Forbidden
> Microsoft.Graph.ServiceException: 
> Code: UnknownError
> Message: {"errorCode":"7503","message":"Application is not registered in our store.","instanceAnnotations":[]}

We searched for the issue, and it is probably related to publishing the app to the Teams Store but is there any way to test that API for development before publishing the teams' bot app (which requires manual approval), or it is a different issue that requires different implementation from our side? 

Thanks and Best Regards
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85e9df00-903f-1ebd-80c8-2e400cecea8b
* Version Independent ID: c104ce3c-167a-e4d4-2900-b489e34c74e0
* Content: [Create call - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-calls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by enkelmedia** [comment]
Any updates on this? I have the same issue!

**Comment by michele-bernardinello** [comment]
Same issue. Any news?

**Comment by 1fabi0** [comment]
Please make sure you enabled calling on your bot registration and have a url in the field that can be called
