### ISSUE TITLE
error in code sample

### ISSUE THREAD

**Issue by TheBluLion** [microsoftgraph/microsoft-graph-docs#10865]
Code sample should show 

PATCH /teams/(team-id)/channels/{channel-id}/Messages/{message-id}
PATCH /users/(user-id)/chats/{chatThread-id}/Messages/{message-id}

instead of

PATCH /teams/(team-id)/channels/{channel-id}/chatMessages/{message-id}
PATCH /users/(user-id)/chats/{chatThread-id}/chatMessages/{message-id}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd7e4bdc-e669-efe9-0c08-73d5397bbf5b
* Version Independent ID: 19780b63-b20a-08b8-b181-bee8133f605c
* Content: [Update chatMessage - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/chatmessage-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @laujan
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as doc has been updated
