### ISSUE TITLE
.NET Documentation

### ISSUE THREAD

**Issue by beaudryj** [microsoftgraph/microsoft-graph-docs#1086]
I am having an extremely hard time finding out how to make these calls using the .net libraries. All I want to do is call the graph api and figure out a users group membership

**Comment by flaviodrodrigues** [comment]
I'm getting same problem, want to create a "service" app to read info for graph api using the sdk but not any demos found

**Comment by beaudryj** [comment]
I go annoyed fighting with these so I found a way to do it in powershell simply to mock up and give to my .net developers to digest.

https://github.com/beaudryj/Azure-GraphHelper

**Comment by beaudryj** [comment]
You will just need to remember to create an application on Azure, grant it permissions and grab the client ID / secret to pass along.

Here is the auth flow I used.

https://docs.microsoft.com/en-us/azure/active-directory/develop/media/active-directory-authentication-scenarios/native_app_to_web_api.png

**Comment by PatAltimore** [comment]
Hi @beaudryj and @flaviodrodrigues,

There are some samples here:  https://github.com/search?q=aspnet+sample+user:microsoftgraph&type=Repositories

Vittorio walks through a "minimal" request in this video: https://channel9.msdn.com/Shows/Office-Dev-Show/Office-Dev-Show-Episode-27-Azure-AD-Converged-Authentication-and-the-Microsoft-Graph

I've got a sample based on that video here: https://github.com/PatAltimore/GraphyMcGraphface

You can always test APIs using Graph Explorer: https://developer.microsoft.com/en-us/graph/graph-explorer 

Thanks for the comments Joe.  I saw them coming through as I was typing this. :-)

Hope this helps,
Pat

**Comment by beaudryj** [comment]
Graph explorer would be fine if you could actually grant it the permissions for testing things like groups...

**Comment by PatAltimore** [comment]
Hi @beaudryj,

A new graph explorer has just been released.  It allows you to set scopes.  It's a lot better than the old one.

Pat

**Comment by beaudryj** [comment]
But can I go under Azure ad and set app permissions on it? When I went to
go do that Monday i was not able to thus rendering the tool useless to test
out membership claims

**Comment by flaviodrodrigues** [comment]
The problem is, i want to have the app act like a service, so without asking user login and without using any user credentials.

I just want to connect to app using api secret, get a token and do a get users for example in c# / webapi.

All the examples show the microsoft login auth page and i dont want to have that.

Thank you

**Comment by flaviodrodrigues** [comment]
I want to to do something like this http://stackoverflow.com/questions/38371147/office365-authentication-without-login-redirection but using the new app approach using microsoft applications: https://apps.dev.microsoft.com/

**Comment by beaudryj** [comment]
@flaviodrodrigues this might help - https://gist.github.com/theMichaelB/54658f02e9d0893d00add072820c9d0c

**Comment by flaviodrodrigues** [comment]
Hi, that looks like powershell, and i need to have this in C# :)

Thanks
Flávio

**Comment by beaudryj** [comment]
Well yes, I know its powershell. Haha

`
<#This is generating a Request Body with grant_type of password, resource would be the graph url, client_id being your app, username being the username you want to use *could pull from a web.config or other source, and same for password* 
#>
            'UserName'  {
                $private:body = @{
                        grant_type   = "password"
                        resource     = $Resource
                        client_id    = "1950a258-227b-4e31-a9cf-717495945fc2"
                        username     = $UserCredential.UserName
                        password     = $UserCredential.GetNetworkCredential().Password
                    }
            } 
    }
    Process
    {    
        $private:uri = 'https://login.microsoftonline.com/{0}/oauth2/token?' -f ($TenantId)

#Here he is calling the login microsoft service, so what would be in the Web Form or url redirect
        $private:response = Invoke-WebRequest -Method Post -Uri $private:uri -Body $private:body
#This line captures the response and converts from JSON to a powershell object to work with    
     $private:responseJson = $private:response | ConvertFrom-Json
<#here he takes the response for the auth code, and generates the bearer token to be used on the initial Graph request
#>
        $private:headerParams  = @{
            'Authorization'="$($private:responseJson.token_type)" + `
                                        " $($private:responseJson.access_token)"
        }

**Comment by PatAltimore** [comment]
@beaudryj I think the new graph explorer was released just last week.  If you checked on Monday, you may have been unlucky to try just before the new one was released. In the new one, after you authenticate, you can add scopes in graph explorer.  You don't need to add permissions through the portal with an app registration. Note that there's a issue using Edge browser with the new graph explorer. Use a browser other than Edge for now.

**Comment by beaudryj** [comment]
We were working with the new graph explorer, and we wanted to call the groups on our AzureAD instance but it wasnt allowing us to grant the permissions on the explorer, thats how I ended up with this round about method as I was able to use my own app with my own app permissions to do the same thing. I went into the Azure Applications and saw that Graph Explorer was listed, but locked down so I couldnt add permissions to "Directory Read Access" to it
