### ISSUE TITLE
API Docs reference an action that is not actually available within production

### ISSUE THREAD

**Issue by wmolde** [microsoftgraph/microsoft-graph-docs#10877]
When I attempt to use the 'DELETE' operation against a MobileAppContent record I get errors from the API stating that 'DELETE' is not an valid verb. API documentation shows it should be available for both v1 and beta APIs, however it does not appear to work in either case.

Example Request: 
`https://graph.microsoft.com/v1.0/deviceAppManagement/mobileApps/6d4ba7bc-5f1c-474a-abd6-beb162d1807c/microsoft.graph.mobileLobApp/contentVersions/1/files/853a54dc-5a56-472b-888d-9d2aa758492f`
Example Result:
`{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/cast/navigation/key/navigation/key with http verb DELETE for request /AppLifecycle_2011/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('6d4ba7bc-5f1c-474a-abd6-beb162d1807c')/$/microsoft.management.services.api.mobileLobApp/contentVersions('1')/files('853a54dc-5a56-472b-888d-9d2aa758492f').",
        "innerError": {
            "date": "2020-12-01T21:47:42",
            "request-id": "6132ef1b-dc53-4572-a5d2-ff8310ede8dc",
            "client-request-id": "198eabb5-1160-949f-e93c-1a0beb6842ee"
        }
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc414732-e0d9-90c9-c7b1-f907b25f7cee
* Version Independent ID: 0a8b3d1a-dfcf-0778-392e-a4c733af7ce1
* Content: [Delete mobileAppContent - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-apps-mobileappcontent-delete?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-apps-mobileappcontent-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-apps-mobileappcontent-delete.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback. I've asked our team to review this action and update the documentation accordingly.
