### ISSUE TITLE
{"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}

### ISSUE THREAD

**Issue by Alvin-Rolim** [microsoftgraph/microsoft-graph-docs#10880]
When using the following flow:

IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
    .Create(clientId)
    .WithTenantId(tenantID)
    .WithClientSecret(clientSecret)
    .Build();

ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication)

    graphClient = new GraphServiceClient(authProvider);

     graphClient.Me.Messages
                .Request()
                .AddAsync(message);

I'm getting the following error:

**{"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}**

My App has permission:

Mail.Send | Application | Send mail as any user |  Granted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS#ClientCredentialsProvider)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
You cannot use `.Me` when authenticated as an application.

With v4 of the SDK you should not use `ClientCredentialProvider` anymore. Instead use `ClientSecretCredential` from `Azure.Identity`.
