### ISSUE TITLE
Remove link to CTL - due to planned deprecation

### ISSUE THREAD

**Issue by 9songs** [microsoftgraph/microsoft-graph-docs#10906]
I suggest to remove the sentence "For more scenario details see Configurable token lifetimes in Azure Active Directory." as it will be deprecated and the settings no longer be honored by Azure AD from January 31st, 2021 onwards.
For refresh and session tokens, we should refer to https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime, and https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/concept-continuous-access-evaluation. Access tokens can still be set via Microsoft Graph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 419287f7-8d19-27f5-d840-5e6ad9fec071
* Version Independent ID: 584e208e-b258-bb38-c2ec-25342423f077
* Content: [tokenLifetimePolicy resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/tokenlifetimepolicy?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/tokenlifetimepolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/tokenlifetimepolicy.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lujiangfeng666
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lujiangfeng666** [comment]
Submitted the fix
