### ISSUE TITLE
These cmds don't exist

### ISSUE THREAD

**Issue by lindseylanier** [microsoftgraph/microsoft-graph-docs#10911]
Issue posted here -- https://stackoverflow.com/questions/65131672/allow-applications-to-access-online-meetings-on-behalf-of-a-user.

I checked the powershell library and cannot find the commands from this doc in any MicrosoftTeams package version. Please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec16769-a606-2245-b239-f194cc5a6c50
* Version Independent ID: 334b7969-9a03-08f1-3a15-4435b469f611
* Content: [Allow applications to access online meetings on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy)
* Content Source: [concepts/cloud-communication-online-meeting-application-access-policy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/cloud-communication-online-meeting-application-access-policy.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @frankpeng7
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lindseylanier** [comment]
Any updates here?

**Comment by frankpeng7** [comment]
Here it is: https://docs.microsoft.com/en-us/powershell/module/skype/new-csapplicationaccesspolicy?view=skype-ps
(if you scroll down on https://docs.microsoft.com/en-us/graph/cloud-communication-online-meeting-application-access-policy the cmdlets are listed in the "see also" section)

**Comment by lindseylanier** [comment]
Thanks for your response but those do not exist in the suggested PS library for Skype/Teams, I checked numerous versions. Can you confirm which library we should use? The account I am running as is also a Global Admin / has Skype Admin rights.

**Comment by lindseylanier** [comment]
![image](https://user-images.githubusercontent.com/8949639/101490969-1f862d80-3931-11eb-8daf-3ad76989bd51.png)

**Comment by frankpeng7** [comment]
I'm not an expert on PowerShell but have you checked out this? https://docs.microsoft.com/en-us/microsoft-365/enterprise/manage-skype-for-business-online-with-microsoft-365-powershell?view=o365-worldwide

**Comment by lindseylanier** [comment]
I followed all of the MS docs, as you can see in the screenshot - the suggested cmdlets do not exist in the package at all.

**Comment by frankpeng7** [comment]
Can you trying opening an issue in the PowerShell Repo? https://github.com/microsoftdocs/office-docs-powershell
This is beyond the scope of Graph and it would be much more efficient reaching out to PowerShell directly.

**Comment by jackry** [comment]
They are not in local powershell package. They are tenant remote powershell cmdlets for Sfb/Teams online. Admin needs to run following cmdlets to create online remote powershell session and then run these cmdlets.

**$cred = Get-Credential   #Input tenant admin account and password in the prompt window
Import-PSSession (New-CsOnlineSession -Credential $cred) -AllowClobber**

**Comment by jackry** [comment]
This is required to be installed BTW: https://docs.microsoft.com/en-us/skypeforbusiness/set-up-your-computer-for-windows-powershell/download-and-install-the-skype-for-business-online-connector
