### ISSUE TITLE
Consent screen asks for wrong permissions

### ISSUE THREAD

**Issue by Tekki** [microsoftgraph/microsoft-graph-docs#1093]
I have registered an app with ID 5a968bc0-ba11-4d28-8837-16f5a8a825aa. When I ask for an authorization code for `scope=calendars.read contacts.read files.read files.read.all user.read offline_access`, the consent screen tells me that the app "will be able to read, **create, update and delete** all files that you can access". The app doesn't have read-write permissions, the request neither ask for them, nor gets them, so it seems the texts on the consent screen and later on https://account.live.com/consent/Manage are wrong.

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
