### ISSUE TITLE
List of all properties returned with permission Mail.ReadBasic missing

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [microsoftgraph/microsoft-graph-docs#10946]
I am an FTE at MS and a customer has informed us that the description for Mail.ReadBasic permission is quite vague. They have requested a list of all the properties returned with permission Mail.ReadBasic . Currently, the documentation just says what is not provided with Mail.ReadBasic instead of listing what is provided. PFB below line 
 Allows the app to read email in the signed-in user's mailbox, except for body, bodyPreview, uniqueBody, attachments, extensions, and any extended properties. Does not include permissions to search messages.

If there is any such existing documentation please provide it, otherwise consider updating the existing doc. Looking forward to hearing from you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Thanks @jeevanbalanmanoj, adding @yuhko-msft who is already looking at this issue for related work.

**Comment by jeevanbalanmanoj** [comment]
Hi team,
Do we have any updates on this?

**Comment by yuhko-msft** [comment]
@jeevanbalanmanoj I've channel this ask to the right person. Will get back to you once I heard from them:)

**Comment by jeevanbalanmanoj** [comment]
Got the answer. Thanks
