### ISSUE TITLE
Counting contacts

### ISSUE THREAD

**Issue by Tekki** [microsoftgraph/microsoft-graph-docs#1094]
When I download all my contacts from `https://graph.microsoft.com/v1.0/me/contacts`, I get n contacts, but `$count=true` shows me a number of n+3. If I split the download with `$top=100` I get 97 contacts from the first request and a nextLink with `$skip=100`. I found out that one of the not downloaded elements is a contact group, but I couldn't identify the others. So the question is, why does '$count' and '$top' count elements that are not contacts?

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
