### ISSUE TITLE
B2B Invitations missing customizedMessageBody

### ISSUE THREAD

**Issue by ivarostby** [microsoftgraph/microsoft-graph-docs#1095]
The invititation email doesn't contain the custom message body, however the reply from API does. Our code has been unchanged, so the problem must have appeared during the easter holidays(?).
Input:
```javascript
{
    "invitedUserDisplayName": "x",
    "invitedUserType": "Guest",
    "invitedUserEmailAddress": "x",
    "sendInvitationMessage": true,
    "invitedUserMessageInfo": {
        "messageLanguage": "en-US",
        "ccRecipients": [
            {
                "emailAddress": {
                    "name": null,
                    "address": null
                }
            }
        ],
        "customizedMessageBody": "Hello World!"
    },
    "inviteRedirectUrl": "https://x",
}
```
Output:
```javascript
{
"invitedUserMessageInfo": {
        "messageLanguage": "en-US",
        "ccRecipients": [
            {
                "emailAddress": {
                    "name": null,
                    "address": null
                }
            }
        ],
        "customizedMessageBody": "Hello World!"
}
```
Issue tested in C#, Powershell and Graph Explorer on different tenants, API v1.0 and Beta. Same result.
I can't find any news on this feature being disabled. Bug, API issue?

**Comment by nick-waterhouse** [comment]
Any updates on this one? We are having the same problem as above, where neither the V1.0 or beta endpoint are honouring the `customizedMessageBody` property.

**Comment by girish** [comment]
The mail body is included only when the inviting user has a proxy address field set on him. This is a recent change made due to some legal reasons. In app only mode, the email body will never be included.
