### ISSUE TITLE
Add filter by date in driveItem search samples

### ISSUE THREAD

**Issue by nmoreau** [microsoftgraph/microsoft-graph-docs#10981]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmoreau** [comment]
As we do this, we should close the following uservoice ask.
See : https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/34588291-search-onedrive-files-by-created-or-modified-date

**Comment by yiwenwang-ms** [comment]
resolved
