### ISSUE TITLE
Create team should return id-value in the content of the response the same as create channel

### ISSUE THREAD

**Issue by akiragothick** [microsoftgraph/microsoft-graph-docs#11009]
Create team should return id-value in the content of the response the same as create channel

{
  "id": "id-value",
  "displayName": "New Team",
  "description": "This team"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamaMohanaChary** [comment]
@akiragothick:

It is by design, If successful, this API returns a 202 Accepted response.
If you want to check your joined team id, please use this query https://graph.microsoft.com/v1.0/me/joinedteams in Graph Explorer. You can see your joined team id.
