### ISSUE TITLE
OrderHints service for API response 

### ISSUE THREAD

**Issue by iamtangram** [microsoftgraph/microsoft-graph-docs#11004]
Can I ask a question, from the documentation, it mentions:
`
The client can obtain the values immediate if return=representation preference is specified in the PATCH requests. The values for the case above may look like the following (the actual values may differ).
`

What's the algorithm for orderHints that server api returns to client?

For example,
from：
`
Item 3 (Order Hint: ' 5637!')
Item 5 (Order Hint: ' 5637! 5637 adhg!!')
Item 4 (Order Hint: '5637 adhg!')
Item 2 (Order Hint: 'adhg')
Item 1 (Order Hint: 'adhg ! !')
`
to 
`
Item 3 (Order Hint: '432b')
Item 5 (Order Hint: '6F"#')
Item 4 (Order Hint: '7A$6')
Item 2 (Order Hint: 'adhg')
Item 1 (Order Hint: 'de5%')
`

Sincerely 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1ba9b0a-0328-2c85-dd7d-a896d7793268
* Version Independent ID: 6b0372aa-1876-586f-0593-1a6a3c13c46e
* Content: [Using order hints in Planner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/planner-order-hint-format?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/planner-order-hint-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/planner-order-hint-format.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TarkanSevilmis** [comment]
Order hint calculation mechanism is server specific, and we can change it as needed. Clients should not try to replicate, understand or otherwise depend on it.
