### ISSUE TITLE
Clarify purpose of OCP-client-name and OCP-client-version

### ISSUE THREAD

**Issue by chblac** [microsoftgraph/microsoft-graph-docs#11041]
The headers OCP-client-name and OCP-client-version are listed as "required", but it is not clear what their purpose or what values are acceptable.  Is this for debugging, auditing, access control, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f432b3e4-d462-917f-6179-ca7ca37c7d3d
* Version Independent ID: 10ba3b6a-bc2e-5ba8-0264-96f4b2cd1b0d
* Content: [List recoveryKeys - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/bitlocker-list-recoverykeys?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/bitlocker-list-recoverykeys.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/bitlocker-list-recoverykeys.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @hafowler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zsirkin** [comment]
@hafowler  Hi Do you have any clarification on this?  I'm trying to put in a good bit of automation and getting this to work would be amazing.   Thanks!

**Comment by hafowler** [comment]
@zsirkin OCP-client-name and OCP-client-version are used for debugging purposes. Because BitLocker recovery keys are sensitive pieces of data, we want to capture this information so we can trace callers, should it be necessary.

**Comment by hafowler** [comment]
@chblac Does the above help resolve this?

**Comment by chblac** [comment]
Hi Hannah,

Yes, that is very helpful information.  Can we put it in the document itself?

Thank you,
Chris

**Comment by hafowler** [comment]
@chblac Yes - is this a change I need to make, or you?

**Comment by chblac** [comment]
Hi Hannah, I don't have any ownership of this area, so it would probably be better if you can make the change.

Thanks,
Chris

**Comment by hafowler** [comment]
@chblac Actually, I was just informed that we will be removing this requirement, and making it optional. That change is expected to be deployed ~4/30.

Would you recommend waiting until then to make doc updates, or should we still make changes in the interim?

**Comment by chblac** [comment]
Hi Hannah,

I think a few more weeks is ok.  It sounds reasonable to only update it once, both marking the fields as optional and adding a brief explanation of what they are.

Thanks!
Chris

**Comment by hafowler** [comment]
@chblac - Ok, thank you. I'll update this thread when those changes have been pushed. 
(Also, sorry this has been outstanding. My GitHub notifications were accidentally being sent to an inbox folder not regularly checked. Should be fixed now :) )

**Comment by hafowler** [comment]
@chblac PR to update this: https://github.com/microsoftgraph/microsoft-graph-docs/pull/12975

ocp headers are now optional.
