### ISSUE TITLE
Can't add guest member to education class anymore...

### ISSUE THREAD

**Issue by kepeter** [microsoftgraph/microsoft-graph-docs#11049]
As of today I receive this error, when I try to add a user who is invited guest on my tenat's AD:
```
Exception: 
	Code: Authorization_RequestDenied  
	Message: Guests users are not allowed to join this Unified Group due to policy setting. paramName: Members, paramValue: , objectType: Microsoft.Online.DirectoryServices.Group  
	Inner error:   
		AdditionalData:   date: 2020-12-16T11:16:17   
		request-id: edff3873-fb0f-4b31-85fa-d6e82d18fd03   
		client-request-id: edff3873-fb0f-4b31-85fa-d6e82d18fd03  
		ClientRequestId: edff3873-fb0f-4b31-85fa-d6e82d18fd03      
```
I checked organization level policy and "**Let group owners add people outside your organization to ‎Microsoft 365 Groups‎ as guests**" is still on...
I also saw that the invited quest is listed on my users list of the tenant...
**Nehama_rashim.co.il#EXT#@rashhim.onmicrosoft.com | Guest | No | rashhim.onmicrosoft.com |   | Invitation**

This functionality worked in the past...

For completeness, this is my code:
```
// creates an invitation in the context of an existing Team
Team oTeam = await _Client.Groups[TeamId].Team.Request().GetAsync();

Invitation oInvitation = await _Client.Invitations.Request().AddAsync(new Invitation
{
    InvitedUserDisplayName = Name,
    InvitedUserEmailAddress = Email,
    SendInvitationMessage = true,
    InviteRedirectUrl = oTeam.WebUrl
});
```
```
// try to add the invited user to the Team as member
await _Client.Education.Classes[TeamId].Members.References.Request().AddAsync(new EducationUser
{
    Id = oInvitation.InvitedUser.Id
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 238deea5-ffc1-befc-ff1d-557803e1d644
* Version Independent ID: 53c6e62a-3b18-725e-7eed-1e011e298f55
* Content: [Add a student - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/educationclass-post-members?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/educationclass-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/educationclass-post-members.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmast-msft** [comment]
Marc,
Any ideas why this might be happening.

**Comment by mlafleur** [comment]
I'm curious if this might be a race condition where the invitation was requested but hadn't been sent. Could you check the status of the invitation?

**Comment by kepeter** [comment]
@mlafleur 
If I understand correctly what you are saying is that the invitation returned before it was actually fulfilled?
Should I read back the invitation object to check it and wait for it to complete?

**Comment by mlafleur** [comment]
I don't believe it needs to be completed, but it may need to be sent. When you immediately attempt to add an invited user, it may be occurring before Exchange or AAD has had the chance to create and propagate the objects.

**Comment by mlafleur** [comment]
@kepeter: Just wanted to follow up and see if you've been able to resolve this issue?
