### ISSUE TITLE
Request to add an example to find exact AD group.

### ISSUE THREAD

**Issue by sjosyula3** [microsoftgraph/microsoft-graph-docs#11060]
I am attempting to query and find an AD group with the the **exact displayName** value of `my_custom_ad_group`

To achieve this, I have made the following call, with a large page size -
`https://graph.microsoft.com/v1.0/groups?$select=id,displayName&$top=999`

The response of this call includes - `@odata.nextLink` , which further points to the next page.

I am currently following some custom logic/code to _continue to the next page until the AD group is found._

However, I am seeking guidance to form a query that will avoid making numerous REST calls - which could slow down my application. 

Any pointers is appreciated. 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce8c6d8-bc9a-1caa-37d8-0ebee8460236
* Version Independent ID: 1668bd18-63b3-6b21-d9c8-2706cb654e61
* Content: [List groups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@sjosyula3 

You'd like to use the `$filter` query parameter for that. Apply `$filter` on **displayName** with an `eq` logical operator against the exact display name. Example:

https://graph.microsoft.com/v1.0/groups?$filter=displayName eq 'my_custom_ad_group'

To know which other parameters support `$filter`, checkout the [groups resource page](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0). To see other examples of using `$filter`, check out the [OData query parameters page](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter).

No updated identified for the page. Closing the issue.
