### ISSUE TITLE
Why doesn't the GRAPHAPI work for manageddevices?

### ISSUE THREAD

**Issue by JamieIntune** [microsoftgraph/microsoft-graph-docs#11070]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50125104-6b00-bc96-d8c6-0b94a04b2ada
* Version Independent ID: 84ad5c29-973b-1a2f-2924-6b636a2a0c2a
* Content: [Get managedDevice - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-get.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JamieIntune** [comment]
I'm getting the following error...

The graph api works for other Intune commands but not ManagedDevices and Wipe/Retire endpoints.

{
    "error": {
        "code": "UnknownError",
        "message": "{\"ErrorCode\":\"Forbidden\",\"Message\":\"{\\r\\n  \\\"_version\\\": 3,\\r\\n  \\\"Message\\\": \\\"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 9a2e28e6-6e2b-4430-aec1-5b69ed668f1d - Url: https://fef.msua05.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/users%28%2721926caf-edb8-47cb-941d-0cb85dcf62d%27%29/managedDevices%28%27da057c1f-4d32-48bc-b445-dc060979e5e1%27%29/microsoft.management.services.api.retire?api-version=2018-05-24\\\",\\r\\n  \\\"CustomApiErrorPhrase\\\": \\\"\\\",\\r\\n  \\\"RetryAfter\\\": null,\\r\\n  \\\"ErrorSourceService\\\": \\\"\\\",\\r\\n  \\\"HttpHeaders\\\": \\\"{\\\\\\\"WWW-Authenticate\\\\\\\":\\\\\\\"Bearer realm=\\\\\\\\\\\\\\\"urn:intune:service,c3998d6e-2e37-4c56-87b5-7b444ee1cb26,f0f3c450-59bf-4f0d-b1b2-0ef84ddfe3c7\\\\\\\\\\\\\\\"\\\\\\\"}\\\"\\r\\n}\",\"Target\":null,\"Details\":null,\"InnerError\":null,\"InstanceAnnotations\":[]}",
        "innerError": {
            "date": "2020-12-17T23:27:49",
            "request-id": "9a2e28e6-6e2b-4430-aec1-5b69ed668f1d",
            "client-request-id": "9a2e28e6-6e2b-4430-aec1-5b69ed668f1d"
        }
    }
}

**Comment by iT2afL0rd** [comment]
I also run into this issue. wipe/retire is not working. I can list managedDevices.

**Comment by triplanedave** [comment]
Wipe/Retire are specific actions on the managedDevice object.  You need to ensure you have the right permissions to perform the actions for the account you're using (or the app), and call in this form: POST https://graph.microsoft.com/v1.0/users/{usersId}/managedDevices/{managedDeviceId}/retire
You can also go into developer mode in your browser (F12) and do a network trace when you call the wipe action from the console to see how Intune performs the action.
