### ISSUE TITLE
"Something went wrong while adding students." - After updating Team...

### ISSUE THREAD

**Issue by kepeter** [microsoftgraph/microsoft-graph-docs#11089]
It is a "follow-up" issue on #9538
The summary of that issue that I can not add members until _IsMembershipLimitedToOwners_ property isn't **false**, but it can be done only via update, and not while creating the Team.
So I did the create in two steps (full code later) - the actual create and then the update...
Now, when entering the UI I got a rather odd message:
![image](https://user-images.githubusercontent.com/695660/102716234-3474a080-42e3-11eb-801a-d5fc56ac9bf9.png)
It is odd, because I made no attempt to add students at this point...
Also notice that the code runs without any error, the problems shows only when entering the UI...

Now for the code:
```
string Email = "myemail@mycompany.com";
string Template = "educationClass";

EducationClass oClass = await _Client.Education.Classes.Request().AddAsync(new EducationClass
{
    DisplayName = Name,
    Description = Description,
    ClassCode = CourseEmail,
    MailNickname = CourseEmail
});

User oOwner = await _Client.Users[Email].Request().GetAsync();

await _Client.Groups[oClass.Id].Owners.References.Request().AddAsync(oOwner);

await _Client.Teams.Request().AddAsync(new Team
{
    DiscoverySettings = new TeamDiscoverySettings
    {
        ShowInTeamsSearchAndSuggestions = false
    },
    MessagingSettings = new TeamMessagingSettings
    {
        AllowUserEditMessages = true,
        AllowUserDeleteMessages = true,
        AllowOwnerDeleteMessages = true,
        AllowChannelMentions = true,
        AllowTeamMentions = true
    },
    GuestSettings = new TeamGuestSettings
    {
        AllowCreateUpdateChannels = false,
        AllowDeleteChannels = false
    },
    MemberSettings = new TeamMemberSettings
    {
        AllowAddRemoveApps = false,
        AllowCreatePrivateChannels = false,
        AllowCreateUpdateChannels = false,
        AllowCreateUpdateRemoveConnectors = false,
        AllowCreateUpdateRemoveTabs = false,
        AllowDeleteChannels = false
    },
    AdditionalData = new Dictionary<string, object>()
    {
        {"template@odata.bind", string.Format("https://graph.microsoft.com/beta/teamsTemplates('{0}')", Template)},
        {"group@odata.bind", string.Format("https://graph.microsoft.com/beta/groups('{0}')", oClass.Id)}
    }
});

await _Client.Teams[oClass.Id].Request().UpdateAsync(new Team() 
{ 
    IsMembershipLimitedToOwners = false 
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f85976e-446c-eee6-a4d9-a833229e8a21
* Version Independent ID: 57bbcd71-5b4c-a204-c026-40b5c1e1d41f
* Content: [Update team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kepeter** [comment]
An interesting note. Leave and enter a second time the time removes the red bar even without hitting the button...
But! One should not see that red bar at all - it will frighten the users and cause a lot of unnecessary calls to support...

**Comment by Jagadeesh-MSFT** [comment]
Thank you for reaching out to us We will investigate and if we require further information we will reach out. Best regards, Teams Platform

**Comment by Jagadeesh-MSFT** [comment]
Hi @kepeter, I have gone through your issue, would suggest you to try in graph explorer.

**Comment by YJasonY** [comment]
Hi @Jagadeesh-MSFT  - we are experiencing a similar issue.

We are creating class teams using the following process:

- Create an education class (which also creates a group)
- Create a team using the class group id
- Add owners
- Add members
- Then we attempt to update the "IsMembershipLimitedToOwners" property (setting it to true) in order to activate the team. This is the part we are encountering an issue. 

When we make this call using the Graph API SDK (PATCH /teams/{teamid} with "IsMembershipLimitedToOwners":true in body) - we get a 502 BAD REQUEST. The team then displays the error "Something went wrong while adding students. [retry]".

When we make this call using graph explorer, we get a 204. But upon inspecting the team, the "x students are waiting to join [activate]" message is present.

Is this the correct approach to 'activating' a class team?

**Comment by esserafael** [comment]
I'm experiencing the same issue.

After the EDU_Class is created and the members assigned, I'm updating the team calling the Graph API:
PATCH /teams/{id} with body:

```
{
    "isMembershipLimitedToOwners": "false"
}
```
In the first request I always get a "502 Bad Gateway" response and the error message "Something went wrong while adding students." starts showing up in the UI.
```
{
    "error": {
        "code": "BadGateway",
        "innerError": {
            "client-request-id": "",
            "date": "2021-03-08T14:24:10",
            "request-id": "878832aa-c37d-4295-95e5-20a155e4a803"
        },
        "message": "Failed to execute backend request."
    }
}
```
After the first request, the next requests (doing in the exact same way) always respond "204 No Content", but the error message still shows up in the UI and the members still can't view/join the team.

The team activation error is only "solved" by clicking "Try again" at the message in the UI, then the members are added to the team.

**Comment by Jagadeesh-MSFT** [comment]
Hi @YJasonY, 

Sorry for the delayed response.
We are working on it practically and checking with our internal Team so will update soon.

**Comment by Nikitha-MSFT** [comment]
please feel free to reopen the issue, if issue still persists
