### ISSUE TITLE
expand parameter: Which relationships are expandables?

### ISSUE THREAD

**Issue by habex-ch** [microsoftgraph/microsoft-graph-docs#11118]
Hi there,

how can I find out if a relationship is expandable or not?

E.g. when I get a team (https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=csharp). 
The relationship "primaryChannel" is expandable, the relationship "channels" is not. 

Is there a way without testing it?
It would be good if this documentation points this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#expand-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by habex-ch** [comment]
Any news on this issue?

**Comment by lramosvea** [comment]
@FaithOmbongi should this be assigned to the Teams team?

**Comment by FaithOmbongi** [comment]
@lramosvea - Yes, it should.

**Comment by Nivedipa-MSFT** [comment]
@habex-ch - Could you please elaborate your issue? Are you trying to say that expand property is not supported for Get Channel API?

**Comment by habex-ch** [comment]
@Nivedipa-MSFT : I hope, this helps:

When I use graph to query some objects. I have the option to expand relationships.

For example, the Microsoft Teams get action (https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0#relationships) has 10 relationships like "primaryChannel", "channels", "members" and so on.

Some of those relationships are expandable and some are not. E.g. the relationship "primaryChannel" is expandable, the relationships "channels" and "members" are not. 

If I try e.g. "channels like "https://graph.microsoft.com/v1.0/teams/02bd9fd6-8f93-4758-87c3-1fb73740a315?$expand=primaryChannel,channels,members" I'm getting the following error message: 
```
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. The property 'channels' cannot be used in the $expand query option.",
        "innerError": {
            "message": "The property 'channels' cannot be used in the $expand query option.",
            "date": "2022-07-28T18:09:25",
            "request-id": "df6065a3-4636-42ea-b0e1-f6e3f111d1da",
            "client-request-id": "df6065a3-4636-42ea-b0e1-f6e3f111d1da"
        }
    }
}
```

In the documentation I only see that "$select" and "$expand" are allowed as OData query parameters. But I can't see anywhere, which of those relationships I can expand.

It would be great, if 

1. In each get-method documentation site there would be a section, which relationships are expandable.
Or
2. If they are the same relationships for each resource type: if there would be a column "expandable" (yes/no) in the relationship section on the resource type site ([e.g. https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0#relationships for the team resource type)

**Comment by ChetanSharma-msft** [comment]
@habex-ch - Thanks for share the information.
We will investigate on your issue and let you know.

**Comment by Nivedipa-MSFT** [comment]
@habex-ch - We have tested this scenario and we are also getting same results.
@AkJo - Could you please add a column "expandable" (yes/no) in the relationship section on the resource type in each get method documentation site.

**Comment by ChetanSharma-msft** [comment]
Hello @AkJo - Could you please help us here?

**Comment by Nivedipa-MSFT** [comment]
@habex-ch - We received an update from the engineering team stating that whether a relationship is expandable or not is very contextualized to the exact API. Therefore, there is no need to update the documentation here. We are closing this issue for now. Please feel free to reopen it if required.

**Comment by habex-ch** [comment]
Yes. This is the reason why I would like to have this information in the documentation. 
There is no indication which properities are expandable in each context and which are not.
Is there a way to find out which relationship properties are expandable in each context except of trying it out?
