### ISSUE TITLE
C# Code

### ISSUE THREAD

**Issue by raeesgillani** [microsoftgraph/microsoft-graph-docs#11111]
[Enter feedback here]
There are a lot of examples using HTML could the examples please be made using c# for the chat message pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa6130b-e7ac-9795-9593-f0cef62ff0d4
* Version Independent ID: 7bf7c3d2-7693-7d24-e9c0-6f0c51cb1eaa
* Content: [Send chatMessage in a channel or a chat - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
I am unsure what this feedback is about. The content of the message can be plain text of html. The payload itself however is Json which is agnostic to language you are using for coding.
