### ISSUE TITLE
The owner of the extensions needs to be added

### ISSUE THREAD

**Issue by tonipohl** [microsoftgraph/microsoft-graph-docs#11131]
The sample code and documentation does not state that the owner of the extensions needs to be added in the request to be successful. Without the owner an error with access denied is thrown.

Wrong request:  (using microsoft.graph powershell)
Update-MgSchemaExtension -SchemaExtensionId $SchemaExtension.Id -Status 'Available'

ERROR: 
Update-MgSchemaExtension : Cannot perform this extension schema write operation.

Correct request:
Update-MgSchemaExtension -SchemaExtensionId $SchemaExtension.Id -Status 'Available' -Owner $OwnerAppID

hth
Toni

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e4acf96-63b8-b946-b6eb-e4624a4981c4
* Version Independent ID: 4525d1c4-d00e-fd58-b69a-0b63da939505
* Content: [Update schemaExtension - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/schemaextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/schemaextension-update.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@tonipohl This info **is** in the update topic.  Copying below:

*For delegated flows, the signed-in user can update a schema extension as long as the owner property of the extension is set to the appId of an application the signed-in user owns. That application can be the one that initially created the extension, or some other application owned by the signed-in user.*

*This criteria for the owner property allows a signed-in user to make updates through other applications they don't own, such as Microsoft Graph Explorer. When using Graph Explorer to update a schemaExtension resource, include the owner property in the PATCH request body. For more information, see the [Extensions](https://docs.microsoft.com/graph/known-issues#extensions) section in [Known issues with Microsoft Graph](https://docs.microsoft.com/graph/known-issues).*

I'll look to update the example (step 4) [here](https://docs.microsoft.com/graph/extensibility-schema-groups?context=graph/api/1.0#4-add-update-or-remove-custom-data-in-an-existing-group) with some more details, with a note about this issue.

**Comment by tonipohl** [comment]
Hi Dan, thanks for checking and the hint. 
I used the PS Microsoft.Graph Update-MgSchemaExtension command and ran into this behavior without seeing this important information in the docs. I guess, I´m not the only one. ;)
So it´s clarified. Thx & happy holidays!

**Comment by dkershaw10** [comment]
Ah - OK.  I wonder whether this is a larger issue around how we document PowerShell cmdlets, and the relationship to the (largely REST) API docs.
I'll keep this open to fix one of the examples above.

**Comment by FaithOmbongi** [comment]
Closing this issue here and creating a request for addition of this info into the Microsoft Graph PowerShell SDK docs.
