### ISSUE TITLE
C# example doesn't show how to pass password to un-protect.

### ISSUE THREAD

**Issue by srivardhanms** [microsoftgraph/microsoft-graph-docs#11134]
The C# example doesn't show how to pass password to the api to unprotect worksheet. Because of that, it doesn't work. Can you please correct it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e8028e4-d20a-6d7e-93d8-dd4dd603cedb
* Version Independent ID: 23427ec1-f209-a379-8d73-3b71e53da628
* Content: [WorksheetProtection: unprotect - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/worksheetprotection-unprotect?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/worksheetprotection-unprotect.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/worksheetprotection-unprotect.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by grangeryy** [comment]
Password is not supported yet for unprotected sheet.
