### ISSUE TITLE
AppToken can not add guest user to Team member

### ISSUE THREAD

**Issue by TonyLi2013** [microsoftgraph/microsoft-graph-docs#11137]
Hi Team,

We have encountered an issue while adding guest user to Teams member by application token, the request we used:

https://graph.microsoft.com/v1.0/teams/{{TeamId}}/members
{
"@odata.type": "#microsoft.graph.aadUserConversationMember",
"roles": ["member"],
"user@odata.bind": "https://graph.microsoft.com/v1.0/users/84f974b9-68b9-4713-80dd-e151220afb1b"
}

Response
{
    "code": "Forbidden",
    "message": "An unknown error has occurred.",
    "innerError": {
      "date": "2020-12-29T06:28:20",
      "request-id": "fc9d1662-edc2-460d-adbc-191560e9cb18",
      "client-request-id": "fc9d1662-edc2-460d-adbc-191560e9cb18"
    }
 }

According to our test, delegate token with TeamMember.ReadWrite.All permission is fine, but we didn't want to use delegate permission, so please help confirm if the application token with TeamMember.ReadWrite.All permission can add guest user to teams?

Thanks in advance,
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7279fc44-89a2-5b5e-1064-a5701880a564
* Version Independent ID: 095d95ca-2198-9cfe-ef6a-3a69ed5bcfe9
* Content: [Add member to team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TonyLi2013** [comment]
any update?

**Comment by Manish-MSFT** [comment]
@TonyLi2013 : Hi, We are investigating this internally, will update you soon with resolution.

**Comment by Manish-MSFT** [comment]
@TonyLi2013 : I have added guest member to team using the above mentioned request with application permission "TeamMember.ReadWrite.All"  and it worked. 
![image](https://user-images.githubusercontent.com/70321016/103615483-afc78a80-4f50-11eb-8709-5a3b107e9093.png)

If you are still facing this issue, can you please provide your response for us to investigate. Thanks.

**Comment by TonyLi2013** [comment]
@Manish-MSFT Thanks for your reply! but the issue still exist in my environment, here are some screenshots about this issue I can provide:
app permissions for postman
![image](https://user-images.githubusercontent.com/3928402/103743481-322a7a00-5037-11eb-8caa-dddb67be18e5.png)

generate app token
![image](https://user-images.githubusercontent.com/3928402/103743543-4e2e1b80-5037-11eb-9ab5-5cdec96d1fb7.png)

request and response
![image](https://user-images.githubusercontent.com/3928402/103743604-6867f980-5037-11eb-9184-fcec00c1a6b2.png)

Any other information, feel free let me know.

**Comment by Manish-MSFT** [comment]
Hi @TonyLi2013 : Could you please use this body to generate bearer token, and let me know if it works. 

client_id: {Your Client Id}
scope:TeamMember.ReadWrite.All
code:{Your Authorization Code}
redirect_uri:https://login.microsoftonline.com/common/oauth2/nativeclient
grant_type:authorization_code
client_secret: {Your Client Secret}


![image](https://user-images.githubusercontent.com/70321016/103754587-8c750c00-5032-11eb-9a9d-9dfb4cb8eda5.png)

**Comment by TonyLi2013** [comment]
@Manish-MSFT Yes, you are right, it works through auth code grant token to add guest user to team member, but our program is not SPA client, user can not input the user credential immediately which will stop the progress. We only have ClientId and ClientSecret of our register application of Azure AD, if there is any possible can add guest user without user credential? because it worked for adding normal user to team member, so I raise this issue for your help.

Thanks
Tony

**Comment by Manish-MSFT** [comment]
@TonyLi2013 : Can you please elaborate a little on what normal user means? I don't think there is way other than auth code grant to add guest as team member.

**Comment by TonyLi2013** [comment]
@Manish-MSFT sorry for confuse, what I mean is I can use app token granted by client credential to add non-guest user like aad domain user as team member successfully, only guest user add failed, so I'm not sure this is a feature or something wrong, is guest user special for adding team member function in Graph API?

**Comment by Manish-MSFT** [comment]
@TonyLi2013 , Adding a guest user works with auth code grant because we have enabled "application" permission ('TeamMember.ReadWrite.All') which comes under admin-restricted scopes. There has to be consent given by user to access admin restricted scopes to generate first the authorization token followed by access token.

![image](https://user-images.githubusercontent.com/70321016/104329250-bc308200-5512-11eb-8760-6b8fd2c949df.png)

For more info for above image you can read [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code)

 However, using client credentials flow it works since there are no admin restricted scopes(as we use delegate permissions). Hope this answers your question.
