### ISSUE TITLE
the update chatmessage is not supported in V1.0

### ISSUE THREAD

**Issue by guyuanchen** [microsoftgraph/microsoft-graph-docs#11142]
Based on ICM 218781003, update chatmessage is not supported in V1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd7e4bdc-e669-efe9-0c08-73d5397bbf5b
* Version Independent ID: 19780b63-b20a-08b8-b181-bee8133f605c
* Content: [Update chatMessage - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/chatmessage-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @laujan
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
I have tested all three 
```
PATCH /teams/(team-id)/channels/{channel-id}/messages/{message-id}
PATCH /teams/(team-id)/channels/{channel-id}/messages/{message-id}/replies/{reply-id}
PATCH /chats/{chatThread-id}/messages/{message-id}
```
and it is working fine. Could you please check once and confirm if you are still facing this issue? If you facing this issue, could you please share some screenshot or error what you are getting?
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Hello, We didn't heard back from you. Let us know if you are still facing the issue.

**Comment by v-chetsh** [comment]
Closing this issue for now. Please feel free to reopen this issue if you are still facing the issue.
