### ISSUE TITLE
"Previously satisfied" is also a possible value of the "authenticationMethod" property.

### ISSUE THREAD

**Issue by fexlneb** [microsoftgraph/microsoft-graph-docs#11151]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0686941f-6b4d-2daa-6636-e8022abc7c4e
* Version Independent ID: 9451d4e0-617b-6180-91bc-d7cc5fff6f9a
* Content: [authenticationDetail resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/authenticationdetail?view=graph-rest-beta&source=docs)
* Content Source: [api-reference/beta/resources/authenticationdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/authenticationdetail.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @fexlneb for highlighting this issue. We've raised a PR to update the list of possible values. Closing the issue.
