### ISSUE TITLE
Add and update email address verify

### ISSUE THREAD

**Issue by BakkerJan** [microsoftgraph/microsoft-graph-docs#11160]
I noticed that I can add and update non-valid email addresses via this API, like _test@test._
There is no validation like there is with adding phone numbers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7671dda3-a1c3-c649-621c-0bb741d6ca0b
* Version Independent ID: dda87ad2-a0dd-703b-3f18-1957d1a7ee1f
* Content: [Update emailAuthenticationMethod - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/emailauthenticationmethod-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/emailauthenticationmethod-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/emailauthenticationmethod-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andres-canello** [comment]
This is now fixed.
