### ISSUE TITLE
Why isn't "calendar" a wellKnownName for mailFolders?

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/microsoft-graph-docs#11166]
Why isn't "calendar" a wellKnownName for mailFolders?

### Example from [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer/preview)

```https://graph.microsoft.com/beta/me/mailFolders/calendar```

![image](https://user-images.githubusercontent.com/6450056/103538648-e771fc00-4e96-11eb-858e-38d5ec3a861b.png)

### Relevant resources

* https://docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta
  * https://docs.microsoft.com/en-us/graph/api/mailfolder-get?view=graph-rest-beta&tabs=http

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305e37ab-7385-f323-deef-7fba07a94142
* Version Independent ID: d2657001-73ba-bf6f-e380-3f5cf7cb144a
* Content: [mailFolder resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/mailfolder?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/mailfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/mailfolder.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by o-l-a-v** [comment]
```-Verbose``` and/ or ```-Debug``` does not print anything either.

**Comment by jasonjoh** [comment]
Because it's not a mail folder. Only containers that contain mail are included in the `/me/mailfolders` collection.

**Comment by o-l-a-v** [comment]
> Because it's not a mail folder. Only containers that contain mail are included in the `/me/mailfolders` collection.

Roger that. Kind of inconsistent having Exchange Online PowerShell where we have ```Get-MailboxFolderStatistics``` and ```Get-MailboxFolderPermissions``` which can be pointed to Calendar as if it was a mail folder. Which made me curios why Graph do the same.

**Comment by jasonjoh** [comment]
Interesting - didn't know that about those cmdlets. If I had to guess, the cmdlets are looking at things from the "old" MAPI-based way, where in reality all containers are folders, and their type is determined by a specific property set on them. So they treat everything as folders (Calendar, Contacts, Tasks, etc.) at a low-level.

From a Graph perspective, to get the default calendar, you can use `Get-MgUserCalendar` from PowerShell, or `GET /users/<user-id>/calendar` from a REST perspective (this is the same call the cmdlet makes).
