### ISSUE TITLE
No information in Documentation on the maximum number of posts it can list.

### ISSUE THREAD

**Issue by vskvarma** [microsoftgraph/microsoft-graph-docs#11219]
We have more than 100 Posts for a thread and it lists only 100 and it doesn't even give the nextLink to feature the next set of results. Even $top=999 doesn't work. See below screenshot.

![image](https://user-images.githubusercontent.com/65310468/103897976-44c9af80-511a-11eb-984b-2b2173f5fa7d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84267a45-4eae-9824-2456-ffa55acda5db
* Version Independent ID: b1639289-ad0c-2c9c-04c1-e1491e6d477d
* Content: [List posts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/conversationthread-list-posts?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/conversationthread-list-posts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/conversationthread-list-posts.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @vskvarma for raising this issue and my apologies for the delayed response. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A(https://docs.microsoft.com/en-us/answers/products/graph). Please ask your question there. 

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
