### ISSUE TITLE
Missing examples on how to use the IN operator in $filter parameter

### ISSUE THREAD

**Issue by BrunoGaudette** [microsoftgraph/microsoft-graph-docs#11224]
As mentioned in the [docs](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter), the IN operator should be supported but I can't find any examples on how to use it.
Could you provide one? 

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @BrunoGaudette for pointing out this gap.

An example for this will be available via the [Use query parameters page](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0) soon. Basically,

[GET](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3Ddepartment%20in%20('Retail'%2C%20'Sales')&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) `https://graph.microsoft.com/v1.0/users?$filter=department in ('Retail', 'Sales')`
