### ISSUE TITLE
Filter/Select does not work 

### ISSUE THREAD

**Issue by cltj** [microsoftgraph/microsoft-graph-docs#11262]
Filter does not work on:

usedLicenseCount
totalLicenseCount
vppTokenOrganizationName
vppTokenAccountType
vppTokenAppleId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47554d8a-fa3a-f393-bbb6-dddc0a7a3a8a
* Version Independent ID: a8e7ac28-6da9-2b30-12ed-b4beacd8071f
* Content: [iosVppApp resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-iosvppapp?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/intune-apps-iosvppapp.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-apps-iosvppapp.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback.  I've asked the team to update the docs accordingly.
