### ISSUE TITLE
Application permissions not working for createToken action

### ISSUE THREAD

**Issue by xmihux** [microsoftgraph/microsoft-graph-docs#11294]
Based on the documentation, it should be possible to create a new token using application permissions (DeviceManagementConfiguration.ReadWrite.All).

Based on my tests it only works with delegated permissions and an account with Intune admin role.
When trying to use application permissions, the following error is received:

`{
    "error": {
        "code": "Forbidden",
        "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 111af43c-dadb-4c47-a76c-02fad0bd4894 - Url: https://fef.amsub0502.manage.microsoft.com/AndroidSync/StatelessAndroidSyncFEService/deviceManagement/androidDeviceOwnerEnrollmentProfiles%28%27{profileID}%27%29/microsoft.management.services.api.createToken?api-version=5020-09-16\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{\\\"WWW-Authenticate\\\":\\\"Bearer realm=\\\\\\\"urn:intune:service,1e51d423-b19c-47f7-8225-c723a568e340,f0f3c450-59bf-4f0d-b1b2-0ef84ddfe3c7\\\\\\\"\\\"}\"\r\n}",
        "innerError": {
            "date": "2021-01-15T14:39:08",
            "request-id": "111af43c-dadb-4c47-a76c-02fad0bd4894",
            "client-request-id": "111af43c-dadb-4c47-a76c-02fad0bd4894"
        }
    }
}`

Application permissions work for listing profiles or getting a profile, but it's not possible to createToken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 605b1f8b-58de-b0aa-5936-10718a9c69f9
* Version Independent ID: 108ef18a-8d09-9f71-2732-825c5c13c1b9
* Content: [createToken action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-androidforwork-androiddeviceownerenrollmentprofile-createtoken?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-androidforwork-androiddeviceownerenrollmentprofile-createtoken.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-androidforwork-androiddeviceownerenrollmentprofile-createtoken.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've asked the team to take a look and update the documentation accordingly.
