### ISSUE TITLE
chat->members is not available in V1

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-docs#11309]
This API is only available in Beta according to metadata and Graph Explorer experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e022ab3d-fe02-9834-eef1-b14e1673a754
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Mallipriya-MSFT** [comment]
@zengin, Yes the API is available in beta only.

**Comment by zengin** [comment]
@Lauragra, what is the process for removing a full page from documentation? It is confirmed that this page shouldn't exist in V1.

**Comment by Lauragra** [comment]
@AkJo , can you please remove this topic? We can just remove the file from the repo, I don't think we need to implement a redirect.

**Comment by Mallipriya-MSFT** [comment]
Hi @zengin, Thank you for the insights and the respective changes are made to the [document](https://docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0).
