### ISSUE TITLE
Patch does not work 

### ISSUE THREAD

**Issue by cltj** [microsoftgraph/microsoft-graph-docs#11317]
Getting a "204 No content" even though I supply the json.

![image](https://user-images.githubusercontent.com/72233033/104822822-b9e96300-5845-11eb-8db8-de091e177871.png)

Is there any problems with the v1.0 version of graph api that i should be aware of. Getting a lot of these mistakes, and despite me reporting in there is no response on the other side.  

Kindly clarify the situation, and why I am getting so many errors in my queries. 

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6761b6-688d-b59b-8878-5f75b578d174
* Version Independent ID: 67daafc7-6338-455f-9954-ee746397e23a
* Content: [Update mobileAppCategory - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-apps-mobileappcategory-update?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-apps-mobileappcategory-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-apps-mobileappcategory-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for bringing this to our attention.  I've filed an issue for our team to look at why the 204 is being returned, even though the patch completes successfully.  We'll update the docs according to our findings.
