### ISSUE TITLE
Missing documentation about the AdditionalData parameter for create group api

### ISSUE THREAD

**Issue by AlyaKoni** [microsoftgraph/microsoft-graph-docs#11318]
Looks like this documentation is not up to date. The parameters owners@odata.bind and members@odata.bind have to be specified in the AdditionalData parameter. At least in the GraphServiceClient. In general I miss here the parameter AdditionalData  completly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 413b25ab-97ec-296f-ef60-fd493aca5667
* Version Independent ID: 25cddb92-e198-16e9-635e-bc4dbd5587ac
* Content: [Create group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-beta&tabs=http&source=docs)
* Content Source: [api-reference/beta/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @AlyaKoni for raising this issue.
@andrueastman - Could you kindly assist to validate and resolve this issue? It is not the case in Graph Explorer.

**Comment by AlyaKoni** [comment]
Working code for the graphClient:

                Group egroup = new Group
                {
                    GroupTypes = GroupTypes,
                    DisplayName = displayName,
                    Description = description,
                    MailNickname = mailNickname,
                    Visibility = visibility,
                    MailEnabled = mailEnabled,
                    SecurityEnabled = securityEnabled,
                    AdditionalData = new Dictionary<string, object>() { }
                };
                egroup.AdditionalData.Add("owners@odata.bind", new string[]{"https://graph.microsoft.com/v1.0/users/{ownerId}"});
                egroup.AdditionalData.Add("members@odata.bind", new string[]{"https://graph.microsoft.com/v1.0/users/{memberId}"});
                await graphClient.Groups.Request().AddAsync(egroup);

**Comment by andrueastman** [comment]
Thanks for raising this issue. Any chance you could clarify which example specifically in the documentation has an issue?

**Comment by AlyaKoni** [comment]
As an example group post, example 2. In this example owners and members odata bind is documented as an immediate child of Group. This is not working in graphClient. In graphClient you have to specify these two properties as child of AdditionalData which is not documented at all!

**Comment by andrueastman** [comment]
Thanks for clarifying @AlyaKoni. It looks like the request block for example 2 has been marked as ignored as below. Hence why the SDK samples are not generated.
```
<!-- {
  "blockType": "ignored",
  "name": "create_prepopulated_group"
}-->
```
I will update this appropriately so that it can picked up by the next snippet generation run.

**Comment by FaithOmbongi** [comment]
H @andrueastman , the example doesn't seem to be getting picked up for code snippets. Could you look into it? Thank you.

**Comment by FaithOmbongi** [comment]
For some weird reason, Example 2's not been picked up for code snippets since Jul. But other examples with **owner** and **member** objects in the request body are showing the **AdditionalData** parameter. So this issue is resolved and I'll proceed to close it.
