### ISSUE TITLE
Automate SAML-based SSO app configuration states incorrect steps

### ISSUE THREAD

**Issue by dotMikeH** [microsoftgraph/microsoft-graph-docs#11326]
Issue is specifically around the [adding of the custom signing certificate](https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=http#add-a-custom-signing-key). 

This doc states incorrect use of the graph API for adding the password credential and key credentials. 
1. Microsoft removed the ability to add password credentials directly against the application and service principal objects and request us to go through the /addPassword graph call
2. It's not allowing the adding of the `Sign` key type (tried X509CertAndPassword and AsymmetricX509Cert for type)

Request Body:
```json
{
    "keyCredentials":[
        {
            "customKeyIdentifier": "c2162879ad8a4d46b4fe470b290d8d97d86acc5c",
            "type": "X509CertAndPassword",
            "usage": "Sign",
            "key": "KEY-VALUE"
        }
    ]
}
```
Gives Error:
```
The value for the property \"usage\" in one of your credentials is invalid. Acceptable values are Sign, Verify.
```
3. Because how Microsoft has changed how we add password credentials how are we suppose to get the `customKeyIdentifier` to match for the password credential and key credentials? You need the password credential to create a certificate, but you need the certificate created to get the SHA256 hash of the cert's thumbprint for the `customKeyIdentifier`. You also can't change the `customKeyIdentifier` after the credential object has been added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9067ae9-89d0-5854-7327-856d930e7712
* Version Independent ID: e0ed6a1b-34bc-55a2-b4ca-61fe3f8ca367
* Content: [Use Microsoft Graph APIs to configure SAML-based single sign-on - Microsoft Graph](https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api?tabs=http)
* Content Source: [concepts/application-saml-sso-configure-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/application-saml-sso-configure-api.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @kenwith
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dotMikeH** [comment]
I've also tried this in the body:
```json
{
    "keyCredentials":[
        {
            "customKeyIdentifier": "sha-256-of-thumbprint",
	    "keyId": "GUID",
            "type": "X509CertAndPassword",
            "usage": "Sign",
            "key": "KEY-VALUE"
        },
        {
            "customKeyIdentifier": "sha-256-of-thumbprint",
	    "keyId": "GUID",
            "type": "AsymmetricX509Cert",
            "usage": "Verify",
            "key": "KEY-VALUE"
        }

    ]
}
```

Where the `keyId` is the same GUID as the passwordCredential and I still get the error:
```
The value for the property \"usage\" in one of your credentials is invalid. Acceptable values are Sign, Verify.
```

**Comment by kenwith** [comment]
@dotMikeH I have checked with the PM on this feature and the documentation is correct. Please open a support ticket so a service engineer can look into your specific scenario and get this resolved for you. 

#please-close

**Comment by dotMikeH** [comment]
Um not sure how the documentation around adding the password credential is correct when the [passwordCredential object](https://docs.microsoft.com/en-us/graph/api/resources/passwordcredential?view=graph-rest-1.0) states
> Using POST or PATCH to set passwordCredential is not supported. Use the addPassword and removePassword methods to update the password for an application or a servicePrincipal

Also this [Microsoft Blog](https://developer.microsoft.com/en-us/identity/blogs/breaking-changes-application-and-serviceprincipal-api-updates-in-microsoft-graph-beta/) calls out the change as well. 

The Automate SAML documentation is showing that I apparently can however use the PATCH request against the Service Principal to add a password credential

**Comment by lcleonp** [comment]
@dotMikeH you can use the PATCH request as long as you use the same call to PATH the keyCredential with usage="Sign" and the passwordCredential using the same keyID. 

I understand that the error you're getting may not be super helpful to figure out why the call is falling. But, may be something related to the format of the key. Are you using the C# code sample to generate the private and public key?

**Comment by dotMikeH** [comment]
Hmm interesting if it allows it if the required keyCredentials are present, I figured it was probably removed because people were creating poor secrets. If that is the case I'll try that use case again and it might help to add to this document to specifically call out that when adding the signing key you can add the passwordCredentail through the PATCH. 

I did end up opening a case with MS. I figured it has to be something with the key, but the error isn't telling me what. I'm actually using python for this as our automation is being built on that. What it's basically doing is using the crypto library to create the public cert and private key (both pem) and I then use it to read in the private key and export as pfx and then I get the base64 of the contents of the pfx file. The base64 looks correct, but can't really confirm because the error tells me invalid property. 

Thanks for the help on this :)
