### ISSUE TITLE
Create Token - application permissions - forbidden

### ISSUE THREAD

**Issue by pieewiee** [microsoftgraph/microsoft-graph-docs#11327]
Can't create token when using application permissions. Followed:

https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-androidforwork-androiddeviceownerenrollmentprofile-createtoken.md

https://docs.microsoft.com/en-us/graph/api/intune-androidforwork-androidforworkenrollmentprofile-createtoken?view=graph-rest-beta

First noticed Problem: 08. December 2020

https://graph.microsoft.com/beta/deviceManagement/androidDeviceOwnerEnrollmentProfiles/{id}/createToken

**Response:**
{
    "error": {
      "code": "Forbidden",
      "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer
  support): 00000000-0000-0000-0000-000000000000 - Activity ID: bb1abce8-c089-46f7-89a9-1919d02fceb6 - Url: https://fef.m
  sub01.manage.microsoft.com/AndroidSync/StatelessAndroidSyncFEService/deviceManagement/androidDeviceOwnerEnrollmentProfi
  les%28%274f8d2df9-cebd-4b89-9cd0-5abec27e9b00%27%29/microsoft.management.services.api.createToken?api-version=5020-09-1
  6\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n
  \"HttpHeaders\": \"{\\\"WWW-Authenticate\\\":\\\"Bearer realm=\\\\\\\"urn:intune:service,1e51d423-b19c-47f7-8225-c723a5
  68e340,f0f3c450-59bf-4f0d-b1b2-0ef84ddfe3c7\\\\\\\"\\\"}\"\r\n}",
      "innerError": {
        "date": "2021-01-18T18:28:59",
        "request-id": "bb1abce8-c089-46f7-89a9-1919d02fceb6",
        "client-request-id": "bb1abce8-c089-46f7-89a9-1919d02fceb6"
      }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've asked the team to update the docs with the the correct required permissions.
