### ISSUE TITLE
Update androidForWorkMobileAppConfiguration OEMConfig - forbidden

### ISSUE THREAD

**Issue by pieewiee** [microsoftgraph/microsoft-graph-docs#11328]
Can not Update OEMConfig Specific androidForWorkMobileAppConfiguration regardless of delegation or application permission. 

worked with MS Premier Support on this topic for about 3 months and they were unable to fix it.
First noticed Problem: 1. july 2020

**Response:**
{
  "error": {
    "code": "Forbidden",
    "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer
support): 00000000-0000-0000-0000-000000000000 - Activity ID: cf1d7da3-308b-4328-be2c-0ac8929272e9 - Url: https://fef.m
sub01.manage.microsoft.com/AppLifecycle_2012/StatelessAppMetadataFEService/deviceAppManagement/mobileAppConfigurations?
api-version=5020-10-07\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\":
\"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
    "innerError": {
      "date": "2021-01-18T19:12:59",
      "request-id": "cf1d7da3-308b-4328-be2c-0ac8929272e9",
      "client-request-id": "cf1d7da3-308b-4328-be2c-0ac8929272e9"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Can you paste a copy of the request body that you submitted (but don't paste anything that might be company or personal information which cannot be shown publicly) and the endpoint that you performed the PATCH against?
