### ISSUE TITLE
Microsoft Graph - Skype for Business PSTN call data not included.

### ISSUE THREAD

**Issue by CWBerube** [microsoftgraph/microsoft-graph-docs#1133]
Issue: When using the SfBActivity > Detail report source\method, the .CSV returned does not include any PSTN call statistics. It appears every access method to obtain that data has been left out. Is this something that's currently in-scope for development?

It was working originally in PowerShell using the "Get-CsPSTNUsageDetailReport" cmdlet but that system is no longer functional for new records and now we're left without a way to pull PSTN data from Azure \ SfB database.

NAME
Get-CsPSTNUsageDetailReport

SYNOPSIS
This cmdlet is available only in the cloud-based service.
**This cmdlet is still available, but it no longer gives accurate results.**

Article: SfBActivity \ Microsoft Graph API

**Comment by minhtripham** [comment]
I'm having the same issue.

**Comment by CWBerube** [comment]
Exactly. I'm not sure why a Microsoft developer or manager isn't acknowledging this ticket.
I even created a ticket to SkypePreview and they told me that the PowerShell cmdlet was indeed deprecated but a new version was being actively developed.

I have no preference whether it be Microsoft Graph or PowerShell, I just need a programmatic way to obtain SfB PSTN call stats. This is the 1 and only hurdle keeping us from switching entirely to SfB for all VoIP.

Can someone possibly provide a status for us please?
Why take away functionality without 1st establishing a replacement?

**Comment by AzureArchitecture** [comment]
Any status on this?

**Comment by CWBerube** [comment]
Yes my management team would really like an update if possible. All we need is a .csv output or some other simple text data output of the Skype for Business PSTN call log details. Originating # \ Destination # \ Call Duration \ Connect? (Yes\No) \ TimeStamp. Most of that is already visible in the Reports GUI in Office 365 so I'm positive the data stream already exists. All we need is Graph to tap that data source. Thank you

**Comment by jthake-msft** [comment]
This is a feature request for the powershell or Microsoft Graph APIs. As per the issue template creation process, feature requests should be added to UserVoice for Microsoft Graph. https://developer.microsoft.com/en-us/graph/support 

This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.

The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.

For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
