### ISSUE TITLE
How to avoid duplicate subscriptions

### ISSUE THREAD

**Issue by timscott** [microsoftgraph/microsoft-graph-docs#11346]
Creating subscriptions is not idempotent -- I can create two identical subscriptions (except the system-generated ID). Also, there is no way to fetch a subscription except by ID. Therefore, the only way to check if an identical subscription already exists would be to fetch a complete list of all subscriptions and search through the complete results. This seems impractical.

Is there some method of querying for subscriptions, perhaps by resource, so I can avoid duplicate subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee6e183-6b0e-bc49-e3d0-5c2a564ca4ad
* Version Independent ID: 798f0583-3e48-1731-b57c-2f2021239e68
* Content: [List subscriptions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-list.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Unfortunately, you can't identify by resource, only Id. The issue has been communicated to engineering. No change identified for the page. Closing the issue. For any product related questions in the future, please ask at Microsoft Q&A (https://aka.ms/askgraph).
