### ISSUE TITLE
"Microsoft Graph beta endpoint reference" is a circular link

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/microsoft-graph-docs#11357]
Was probably meant to actually point to something but it just points to the same article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d489b596-8db6-6b4e-7271-77a6fb735c37
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph REST API v1.0 reference - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/overview.md)
* Product: **non-product-specific**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@JustinGrote , thanks for pointing out the issue. The link used an older approach that's apparently broken now. FYI PR #11400 will be published the next work day after the weekend, and the link will be fixed on the live site then.
Thanks again for your support!
