### ISSUE TITLE
Recurrence object Order-sensitive

### ISSUE THREAD

**Issue by xelnagapi** [microsoftgraph/microsoft-graph-docs#11359]
If a patternedRecurrence object is made with the following structure:

{
  "range": {"@odata.type": "microsoft.graph.recurrenceRange"},
  "pattern": {"@odata.type": "microsoft.graph.recurrencePattern"}
}

Then an error will be fired by Graph "UnableToDeserializePostBody".

The order must strictly be "pattern", and then "range".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc0466f-10cf-f53a-0eff-351f36288718
* Version Independent ID: 5d54df69-0ab6-0d86-4ae4-5bf51ea1426c
* Content: [recurrencePattern resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/recurrencepattern?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/recurrencepattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/recurrencepattern.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Please raise a support ticket for issues for product development team to triage.
