### ISSUE TITLE
Error in Japanese version public information (“Identities” is translated “ID" )

### ISSUE THREAD

**Issue by omifumi** [microsoftgraph/microsoft-graph-docs#11350]
[Enter feedback here]

I want to correct the error in the Japanese version public information.

“Identities” is translated as “ID” in the Japanese version public information ,
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/43370236/105109929-dcf36b80-5b00-11eb-811f-40e31b5f16c0.png)
 and the customer is confused.
https://docs.microsoft.com/ja-jp/graph/api/resources/user?view=graph-rest-1.0#properties
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @omifumi for highlighting this translation issue.
We'll raise it up with the localization team and see if we can get it resolved.

No updates identified for the _en-us_ page. Closing the issue.

**Comment by elenaost** [comment]
@omifumi Thank you for reporting the issue. It is fixed now.
