### ISSUE TITLE
Unable to get or update meetings created with application permission

### ISSUE THREAD

**Issue by rghanel** [microsoftgraph/microsoft-graph-docs#11360]
If a meeting is created with applications permissions, the meeting is created successfully and response received however you are unable to use the meeting id in the response to allow a 'Get onlineMeeting' or 'Update onlineMeeting' operation (again using application permissions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb82ac27-1e14-06dd-21b2-7238162fe68c
* Version Independent ID: 6cc4993f-2ae8-9b39-0bee-01dfb44d125b
* Content: [Create onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by devanshuGit** [comment]
Hi, do we have any update on this?
Similar is being observed with fetching meeting details using application token and assigned policy
https://stackoverflow.com/questions/67676500/create-online-meeting-on-behalf-of-user-ms-graph-api

**Comment by devanshuGit** [comment]
@ananmishr any updates, this is open since long
