### ISSUE TITLE
Expanding SharePoint list columnSet does not work

### ISSUE THREAD

**Issue by paulsutherland** [microsoftgraph/microsoft-graph-docs#1137]
**Issue:** 
Expanding SharePoint list column set does not work

**Article:** 
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/listitems_list

Querying a list and returning items works fine, but expanding the column set with 
?expand=columnSet 
is not returning the column data.

This was working last week.

**Comment by trillian74** [comment]
Any news  on this topic? I have the same on my tenants. Would be great with som e feedback on this issue.

**Comment by paulsutherland** [comment]
@trillian74 Complete speculation here, but with Microsoft's Build event being held next week, we might see a new release/update of the api.  As you know, and are likewise feeling the pain, there is always a risk using a beta api that it may not be stable, therefore, as a fallback I am looking at querying the [Sharepoint api direct](https://msdn.microsoft.com/en-us/library/office/fp142380.aspx).

This allows:

`<site url>/_api/<context>/<resource>  (example, https://contoso.com/_api/web/lists)`

Graph is a wrapper around this api I believe.

**Comment by trillian74** [comment]
yes, the risk is allways there:) But i was hoping that someone could say (without speculating;)) : Yes we know, we're workin' on it or that we're discarding the functionality. its somewhat more complicated getting access from two apps. Thanx for keeping the thread alive.

**Comment by trillian74** [comment]
I think its kinda incredible that there is a post regarding this on github, techcommunity and stackoverflow and nobody from the graph team has picked it up? nice upgrade of the Graph Exporer, but still nothing on the sharepoint beta api and expanded columnsets???

**Comment by rgregg** [comment]
@trillian74 Thank you for reporting this error and consuming the SharePoint APIs in Microsoft Graph. While I can't confirm any speculation, I am aware of this issue and we're working on a resolution for the API issue. We should have an update to share next week.

**Comment by trillian74** [comment]
@rgregg looking forward to it

**Comment by trillian74** [comment]
Just reviewed the new 1.0 api for sites and the beta for listitems seems like a solid improvement:) But it's not returning correctly @rgregg is it due to geo replication issues?
`
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'sites'.",
        "innerError": {
            "request-id": "f783b07e-2b21-4d93-8db5-0098b2353186",
            "date": "2017-05-09T11:08:53"
        }
    }
}`

**Comment by trillian74** [comment]
I recommend closing this one since the change in beta api is using fields instead of columnset. And that it is actually working on my end:) https://graph.microsoft.com/beta/sites/tenant.sharepoint.com,sitecolid,siteid/lists/listid/items?expand=fields

**Comment by paulsutherland** [comment]
I am not so sure.  The [documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/listitems_list) says the query signature is:

`https://graph.microsoft.com/beta/sites/{site-id}/lists/{list-id}/items?expand=fields`

That does not work for me, I get the error: "Provided id is not suitable for the current host"

The query signature that you are having success with does not match the docs, which should be corrected either way.  I think this should remain open until the docs query works or is changed to match yours.

**Comment by paulsutherland** [comment]
Actually - scrap that.  It does work. 👌   The Id for the sites are now prefixed with the tenant name

`<tenant>.sharepoint.com,<siteid>/lists/<listid>/items?expand=fields`

or subsite

`<tenant>.sharepoint.com,<siteid>,<subsiteid>/lists/<listid>/items?expand=fields`

Factoring that in I can successfully query as per the docs and your query signature.

So, yes I agree this is now working as per the docs.

Great job on the New Graph Explorer 🎉 

Happy days....

**Comment by drewmo** [comment]
I am having an issue with this as well. I am able to make a call to get the list items from a calendar on my SharePoint site, but as soon as I try to make a call to a list I have created I get this response:
`{
    "error": {
        "code": "generalException",
        "message": "An unspecified error has occurred.",
        "innerError": {
            "request-id": "a04f301d-f119-4cc8-b2ef-24cd06a672cf",
            "date": "2017-05-23T23:39:22"
        }
    }
}`

I am trying to user `/items?expand=fields` yet I do not get anything back. Strangely enough if I change the request to `/iteams?expand=fields(select=id)` I get a response, but the only items in fields are the ids, and adding any other column names to the query continues to return only the id.

**Comment by paulsutherland** [comment]
Hi, we still have an issue with this, unless I have the syntax wrong, but following the docs at

**Article:
Enumerate items in a list**
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/listitems_list

Querying a list and returning items and expanding the fields works fine, but selecting fields with

`/items?expand=fields(select=Column1,Column2)`

is returning an error.

I can successfully return the ids with:

`/items?expand=fields(select=Id)`

but selecting columns, such as Title:

`/items?expand=fields(select=Title)`

returns:

```
{
    "error": {
        "code": "invalidRequest",
        "message": "The request is malformed or incorrect.",
        "innerError": {
            "request-id": "2b49c6a7-88f7-4663-86df-a621dd0a0001",
            "date": "2017-06-02T10:29:43"
        }
    }
}
```

If I query for Title with the Id:

/items?expand=fields(select=Id,Title)

I get no error, but it only returns the Id for each item!

Any help with getting the query correct would be greatly appreciated.

**Comment by dancampbell691** [comment]
@paulsutherland : did you get a resolution to your issue?  I'm having the same problem.  The documentation for FieldValueSet ([https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/fieldvalueset.md]) explicitly says this should work.

**Comment by paulsutherland** [comment]
@dancampbell691 
Sorry for the delay, I was on a summer holiday.

No I have not heard anything back.  I regularly check the api, but it is still not working as per my previous comment.

I have assumed the beta api is too fragile to use, so I am looking at proxying requests to Sharepoint lists through an api app.

**Comment by frank1340** [comment]
@paulsutherland How would you accomplish this?  I've tried to use the Sharepoint API through a Sharepoint Add-In application and OAuth2 and I receive Audience Uri validation errors.  Thanks nonetheless.

**Comment by paulsutherland** [comment]
@frank1340 have a look at [SP request](https://github.com/s-KaiNet/sp-requestl).  It makes use of [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth), in particular the [addin only authentication](https://github.com/s-KaiNet/node-sp-auth/wiki/SharePoint%20Online%20addin%20only%20authentication).

**Comment by tmAsim** [comment]
@paulsutherland I am facing the same issue with fields selector, did you able to solve that issue?

**Comment by paulsutherland** [comment]
@tmAsim I did not get a resolution.  My use case allowed me to achieve what I needed using SP request.

**Comment by tmAsim** [comment]
@paulsutherland ah, is there any work around to get the items of lists using Microsoft Graph API?

**Comment by paulsutherland** [comment]
@tmAsim I didn't find one.

**Comment by mikewiese** [comment]
... 2 years pass by. Still broken. Am using 'v1.0' of the Graph API.

/items?$expand=fields($select=fieldname1,..fieldnameN) only returns a subset of the specified fields.
/items?$expand=fields with no 'select' clause only returns 15 out of the 47 fields in my SharePoint List.

**Comment by isvargasmsft** [comment]
Hello, my deepest apologies for the delays in addressing this issue. 

I checked from my end and noticed:
1. ColumnSet attribute has been renamed to "Fields". Details in the [changelog.](https://developer.microsoft.com/en-us/graph/changelog/?filterBy=v1.0,Sites%20and%20lists,beta&page=2#54c8f6cc-3d14-4c83-9d87-e93e1318f7c8beta)
2. The issue has been fixed as the request is working with the following command:
`https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-id}?$expand=fields`

Hope this clarifies. 

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at Microsoft Q&A: [Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html). 

Kind regards, 

Isaac Vargas
