### ISSUE TITLE
MS Graph API device  should return operating system iOS

### ISSUE THREAD

**Issue by jitendraRai** [microsoftgraph/microsoft-graph-docs#11379]
URL:- https://graph.microsoft.com/v1.0/devices

The response object of graph API for iphone or ipod device should return operating system as iOS.

The sample and return value should be updated.

Reference:- 
https://stackoverflow.microsoft.com/questions/240407

Screenshot:- 
![image](https://user-images.githubusercontent.com/4159689/105469393-2c32cb00-5cbe-11eb-87bb-e72b696dea0b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 761e9b84-2e08-6b7c-2dc6-977c95100fae
* Version Independent ID: 8d456032-3df5-0698-d4b7-32a60beb3a1f
* Content: [List devices - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/device-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @spunukol
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jitendraRai for raising the issue. Unfortunately this forum is only for documentation-related issues and isn't monitored for functionality issues. But, I notice you've already appropriately filed the issue as a bug report. If this has not yet been resolved, kindly post this question at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) where the relevant Engineers will be able to respond in good time.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
