### ISSUE TITLE
attendeeReport 500

### ISSUE THREAD

**Issue by Loenser** [microsoftgraph/microsoft-graph-docs#11404]
[Enter feedback here]
After trying out the attendeeReport endpoint the server keeps sending me following response:
{
    "error": {
        "code": "InternalServerError",
        "message": "Object reference not set to an instance of an object.",
        "innerError": {
            "date": "2021-01-25T08:14:21",
            "request-id": "110289ca-d978-4622-b8c3-874c1e857708",
            "client-request-id": "227f5417-e77a-dd0f-c49e-8d0f7955175f"
        }
    }
}
Both my userId and my meetingId are right and i can get responses from the server asking other endpoints with them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9593d8-ed60-527f-c549-b22dce5adbd9
* Version Independent ID: cdf36bed-fd4f-8be7-918c-6cdf74258676
* Content: [Get onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ffactory-ofcl** [comment]
I'm having the same issue! Any word on this?

**Comment by ffactory-ofcl** [comment]
The issue has been fixed for quite a while, IIRC.
