### ISSUE TITLE
Under Search permissions, applications permissions required is ExternalItem.ReadWrite.All. 

### ISSUE THREAD

**Issue by flyingxi2** [microsoftgraph/microsoft-graph-docs#11403]
Why would we need write permission to search over site entityTypes? Read permission should be enough.
POST https://graph.microsoft.com/v1.0/search/query
Request body:
{
    "requests": [
        {
            "entityTypes": [
                "site"
            ],
            "query": {
                "queryString": "work"
            },
            "from": 0,
            "size": 2
        }
    ]
}
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @flyingxi2 for raising your issue. I've raised a PR to fix this issue. 
The list of supported permissions is from Least to Most privileged. But, yes, applying least privilege rule, you don't need write permissions when read-only will get the job done.
