### ISSUE TITLE
Group creation fails using the `PUT /groups/{id}/team` endPoint when Guests are in a Group

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs#11417]
Hello,
I noticed that the provisioning a Team from an existing Group with Guest accounts associated as members is failing using the `PUT /groups/{id}/team` endpoint.

On the other hand, if you provision the Team using the endPoint described [here](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http) it works fine (by passing the "group@odata.bind").

It can be tested by creating a M365 Group with a guest as a member and then provision a Team either by the first or second endpoint. The first endPoint will fail.

br,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4532c86e-d363-3181-b439-a91bce41c44e
* Version Independent ID: 9223513b-37d0-f9ea-f004-83f2222906b0
* Content: [Create team from group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamaMohanaChary** [comment]
Hi @plamber,

We are checking internally will get back to you soon.

**Comment by plamber** [comment]
Hi @RamaMohanaChary,
thank you for coming back to me. Highly appreciated.

br,
Patrick

**Comment by Mamatha-MSFT** [comment]
Hi @plamber I am able to repro the issue. I am getting 404 error when I try to create a team using `PUT /groups/{id}/team` request.

![image](https://user-images.githubusercontent.com/78795357/114192532-35e9d780-996b-11eb-8b8a-3bcbe039bfa1.png)

Will be raising the same as bug if it gets confirmed from internal team and will be sharing the details with you.

**Comment by plamber** [comment]
Thank you. Highly appreciated

**Comment by Mamatha-MSFT** [comment]
@plamber  I have raised a bug and concerned team is working on it

**Comment by ChetanSharma-msft** [comment]
Hello @plamber - Sorry for delay in response.
This issue has fixed. 

Could you please check and confirm, so that we can close this issue?

**Comment by plamber** [comment]
Thank you. I can confirm that it works again. Closing the issue
