### ISSUE TITLE
Resource URL for  ServiceHealth.Read.All and ServiceMessage.Read.All

### ISSUE THREAD

**Issue by junecastillote** [microsoftgraph/microsoft-graph-docs#11414]
Microsoft Graph API Permissions include `ServiceHealth.Read.All` and `ServiceMessage.Read.All`. But, where is the graph resource URL to use these permissions? I cannot find any mention of them on the Graph API reference page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nganbui** [comment]
I have the same question about the endpoint Graph API to use ServiceHealth.Read.All and ServiceMessage.Read.All

**Comment by ITSportGuys** [comment]
I have this question as well.

**Comment by angelgolfer-ms** [comment]
@davidmu1 , @Jackson-Woods , can you please follow up the circumstances that customers are seeing ServiceHealth.Read.All or ServiceMessage.Read.All? These strings don't appear in the docs. Is there a discrepancy with what's appearing in the Azure portal?

**Comment by FaithOmbongi** [comment]
The resources that would consume these permissions have not yet been released. Can't confirm when they'll be released.

**Comment by FaithOmbongi** [comment]
**Update:**

The APIs that consume these permissions are now in Private Preview. See [Service health and communications (preview)](https://docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-beta).
