### ISSUE TITLE
Calendar event online meeting unchangeable and weird behaviour

### ISSUE THREAD

**Issue by Bragegs** [microsoftgraph/microsoft-graph-docs#11419]
Graph token permissions:

Calendar.ReadWrite, email, profile, User.read

How event is created:

`/me/events`

```
{
  'subject': 'Test-subject',
  'isOnlineMeeting': true,
  'onlineMeetingProvider': 'teamsForBusiness',
  'body': {
    'contentType': 'HTML',
    'content': 'Body of event'
  },
  'start': {
    'dateTime': '2021-02-04T16:30:00.0000000',
    'timeZone': 'UTC'
  },
  'end': {
    'dateTime': '2021-02-04T16:45:00.0000000',
    'timeZone': 'UTC'
  },
  'location': {
    'displayName': '',
    'locationType': 'default',
    'uniqueIdType': 'unknown',
    'address': {},
    'coordinates': {}
  },
  'attendees': [
    {
      'type': 'required',
      'status': {
        'response': 'none',
        'time': '0001-01-01T00:00:00Z'
      },
      'emailAddress': {
        'name': 'x-name',
        'address': 'x@company.com'
      }
    },
    {
      'type': 'required',
      'status': {
        'response': 'accepted',
        'time': '2021-01-26T13:21:32Z'
      },
      'emailAddress': {
        'name': 'y-name',
        'address': 'y@organization.com'
      }
    }
  ],
  'organizer': {
    'emailAddress': {
      'name': 'x-name',
      'address': 'x@company.com'
    }
  }
}
```

works perfectly, and creates an online meeting link with teams.

When I try to update(with update I mean PATCH) this event with the same token:

`/me/events/<event_id>`

```
{
  'isOnlineMeeting': false
}
```

Online meeting is <b>not</b> toggled off. Response: 

```
HTTP/1.1 200 OK

{
 ...
  'isOnlineMeeting': true,
  'onlineMeeting': {
    'joinUrl': 'teams-url.com'
  }
 ...
}
```

When I try to update the body and keep isOnlineMeeting to true:

`/me/events/<event_id>`

```
{
  'body': {
      'contentType': 'HTML',
      'content': 'New body',
   },
   'isOnlineMeeting': true,
}
```

The online meeting is toggled of and on every other request, meaning that the isOnlineMeeting is set to the opposite of what the current value is, even tho I specify true. Edit: After further testing this seems to happen when `
onlineMeetingProvider` is set to `teamsForBusiness`. With `skypeForBusiness` the online meeting field is not toggled on updating body.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aee1ce02-2e47-8de4-e716-3d8910fee70d
* Version Independent ID: 68365876-8446-59cc-235e-ed62926e204a
* Content: [Enable an event as an online meeting in an Outlook calendar - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-calendar-online-meetings?tabs=http)
* Content Source: [concepts/outlook-calendar-online-meetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-calendar-online-meetings.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @Bragegs , 
Can you please confirm if you observed the described issue using the v1.0 endpoint or beta endpoint?

Assigning to @Harini84 for the following 2 issues:

- Can you please confirm if the _intended_ behavior for the isOnlineMeeting property should be the same in beta and in v1.0?

  The description for the isOnlineMeeting property in the [event topic in beta](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta#properties) says:
  "After you set isOnlineMeeting to true, Microsoft Graph initializes onlineMeeting. Subsequently Outlook ignores any further changes to isOnlineMeeting, and the meeting remains available online."
  If the answer is yes, then please have the v1 property description updated :-)

- Do you mind following up on the toggling behavior - being able to toggle isOnlineMeeting to the opposite value? A behavior like that sounds like a bug to me.

**Comment by Bragegs** [comment]
Ok, thank you for the fast response. 

The endpoint used is `https://graph.microsoft.com/v1.0`.

**Comment by Harini84** [comment]
The logic for online meeting has been updated for client needs by which when the meeting blob is not present, then the meeting is considered to have been downgraded from online meeting to offline meeting.

For an online meeting, when updating meeting body, fetch the meeting body first and then apply the update.

This is because the meeting body contains meeting blob for an online meeting. If the blob is not present during meeting body update, then service would consider that the meeting is no longer an online meeting and the meeting gets downgraded to an offline meeting.

This need to be updated in public documentation.

@angelgolfer-ms @JuForan

**Comment by Bragegs** [comment]
Thank you for your swift responses and the explanation 👍🏻
