### ISSUE TITLE
Add PUID/NetID to user resource

### ISSUE THREAD

**Issue by nimoskovE** [microsoftgraph/microsoft-graph-docs#11422]
Please add the PUID/NetID field to the user so I can match it with what I get from the [Classic Administrators API](https://docs.microsoft.com/en-us/rest/api/authorization/classicadministrators/list#classicadministratorlistresult)
The Classic Administrators API returns the email address and PUID/NetID.
- Email address is not reliable
- PUID/NetID is only accessible with the old Graph API (graph.windows.net) and only in the '1.61-internal' version that I can't use

Thank you very much,
Nitzan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8446021-6786-c54c-066f-d99ba4644312
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@nimoskovE 
**PUID/NetID** was removed from Graph API and there are currently no plans on resurfacing it. The recommendation for apps is to rely on **TenantID** and **ObjectID** to identify users and stop relying on PUID/Net ID. 

We'll check into ClassifyAdministrators API to understand why it's still returning PUID.

No updates identified for the page. Closing the issue.

**Comment by nimoskovE** [comment]
@FaithOmbongi 
I try to rely solely on TenantID and ObjectID but I can't with the ClassicAdministrators API..
It will really help if you could get Azure to change the API and return the user's ObjectID instead of the PUID.

Users who are **Classic Administrators have sensitive permissions in Azure** and currently there is no way to automate the process of identifying them.

Please let me know if I can contact someone in Azure to help speed things up since it is very important to me.
Thank you very much

**Comment by FaithOmbongi** [comment]
Hello @nimoskovE ,

I did ask around and since this is a product-related issue, the [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) channel is the best forum to raise it up. You'll receive better support for this API issue.
