### ISSUE TITLE
"chats" segment is only available as a top-level entity set in the V1 metadata

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-docs#11425]
Neither `user` entity nor the `me` singleton has `chats` defined as a property in the V1 metadata. `chats` segment only appears as a top-level entity set.

So only first request of the following two is correct according to the metadata:
```
GET /chats/{id}/members
GET /users/{id}/chats/{id}/members
```

And the sample should also use the top level entity set.
Instead of:
```
GET https://graph.microsoft.com/v1.0/me/chats/{id}/members
```
It should be:
```
GET https://graph.microsoft.com/v1.0/chats/{id}/members
```

Wrong sample blocks the validation of generated snippets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e022ab3d-fe02-9834-eef1-b14e1673a754
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Mallipriya-MSFT** [comment]
@zengin, Chat->Members API is available in beta only.

**Comment by zengin** [comment]
@Mallipriya-MSFT can this page be removed from the documentation then?

**Comment by Mallipriya-MSFT** [comment]
Hi @zengin, we have asked documentation team to make the necessary changes and in result the page is redirected to beta version API document as shown in the image. 
![image](https://user-images.githubusercontent.com/73868678/108816677-99e35700-75dc-11eb-87b1-4afce5d65f73.png)

**Comment by zengin** [comment]
@Mallipriya-MSFT, thanks for the prompt response.

I think I am missing something.

The content link in the auto-generated issue description doesn't take me to this redirection page.

Similarly, the search result also takes me to the v1 page without redirection: https://docs.microsoft.com/en-us/search/?scope=graph&view=graph-rest-1.0&terms=list%20conversationmembers

I tried incognito to make sure that there is no caching, but I get the same result.

**Comment by pixieofhugs** [comment]
@Lauragra Can we remove the reference page for this in 1.0 as it is only available in Beta?

**Comment by Lauragra** [comment]
This issue has already been resolved: https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/conversationmember-list.md

**Comment by zengin** [comment]
Thank you @Lauragra. The same issue shows up in two other pages: #12274 and #12162. Could you please help us in getting those fixed?
