### ISSUE TITLE
Intermittent 404's on team-related calls

### ISSUE THREAD

**Issue by fvanheeswijk** [microsoftgraph/microsoft-graph-docs#11430]
We are facing intermittent 404 not found responses on the following calls:

    Get team
    List team members
    List channels

We are confident that the teams are in fact present in Microsoft Teams, however the Microsoft Graph API decides to return a 404 not found response for an unknown reason.

Please look into this. Our first occurrence was at timestamp 2021-01-27T01:46:33.
This is causing serious issues for our team synchronization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04dfdea1-2848-4462-1e78-3c08c7b4fc45
* Version Independent ID: f9c8bdce-c8b8-7c1d-8f4d-9ab841902c89
* Content: [Get team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TonyLi2013** [comment]
same issue， the response is：
"error": {
    "code": "UnknownError",
    "message": "404 page not found\n",
    "innerError": {
      "date": "2021-01-28T07:09:54",
      "request-id": "88dd1d83-9d91-47e7-a188-ca5270e73ead",
      "client-request-id": "88dd1d83-9d91-47e7-a188-ca5270e73ead"
    }
  }

**Comment by fvanheeswijk** [comment]
We're indeed getting the same "404 page not found\n" errors. It's still not fixed.

**Comment by Nikitha-MSFT** [comment]
We are not able to repro the issue at our end. Could you please share the request Url and client-request id?

**Comment by Nikitha-MSFT** [comment]
Please provide the required inputs and reopen the Issue. As of now we are closing the issue.
