### ISSUE TITLE
Adding $select to "/beta/teams/{team}/channels" returns empty array

### ISSUE THREAD

**Issue by matula** [microsoftgraph/microsoft-graph-docs#11472]
If I hit `/beta/teams/{team}/channels`, I get a correct list of channels in a Teams. However, if I hit `/beta/teams/{team}/channels?$select=id`, it returns an empty array. According to the documentation, $select should work and it has worked previously.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba27412-77d2-0cf2-d5cf-a015546d0ea6
* Version Independent ID: fe27e8cc-9e04-9184-dd8d-36990e4d7064
* Content: [List channels - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by OskarNet** [comment]
This is the same issue as with the v1.0 endpoint.

Regards,
Oskar

**Comment by alvaroyurrita** [comment]
We are experiencing the exact same issue in production code. One of our apps broke because of this.

Regards.
Alvaro

**Comment by fuzeowcwsk** [comment]
We are also having the same issue impacting one of our apps.

**Comment by OskarNet** [comment]
One would think there should be automatic tests run against these endpoints so that basic functionality don't just stop working

**Comment by fuzeowcwsk** [comment]
> 
> 
> One would think there should be automatic tests run against these endpoints so that basic functionality don't just stop working

You would definitely hope so, especially as the same issue exists for production endpoint.

**Comment by Jesper-ma** [comment]
We have the same problem in production code:
This was working before:
https://graph.microsoft.com/v1.0/teams/********/Channels?$select=id,displayname,description,webUrl
Now it is returning an empty result.

**Comment by cupcoder** [comment]
Same issue here as well. I can't believe Microsoft is so bad with their testing.

**Comment by OskarNet** [comment]
Are there no news on this bug? We had this in production code and had to release a fix to remove the $select for now.

**Comment by fuzeowcwsk** [comment]
> 
> 
> Are there no news on this bug? We had this in production code and had to release a fix to remove the $select for now.

We had to do the same also. Hopefully someone recognises this bug soon.

**Comment by nero120** [comment]
Yep same issue here. Microsoft never miss an opportunity to dissappoint.

**Comment by OskarNet** [comment]
So this has now silently been fixed by Microsoft and is working now.

**Comment by lramosvea** [comment]
Seems like this issue has been resolved. Please feel free to reopen if that is not the case, so that the Microsoft Teams team can take a look at it.
