### ISSUE TITLE
Some properties listed are readonly and not required for the payload 

### ISSUE THREAD

**Issue by tiagoinacio** [microsoftgraph/microsoft-graph-docs#11471]
The documentation not only shows the required properties but also some read-only properties, for example the ID. Please update the table properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a80437-a9a0-7c3c-0ad5-6a4ed3b7ae71
* Version Independent ID: 373923d8-98c5-3752-704c-398f05017e7f
* Content: [Create win32LobApp - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-apps-win32lobapp-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-apps-win32lobapp-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've requested that we consider changes to our doc process to surface this information in future updates to our documentation.
