### ISSUE TITLE
Unclear documentation on {parent-id} for OneDrive > Upload

### ISSUE THREAD

**Issue by bpkennedy** [microsoftgraph/microsoft-graph-docs#1151]
Issue: 
I do not know what {parent-id} is in this documentation.  Please clarify.

Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/item_uploadcontent.md#upload-or-replace-the-contents-of-a-driveitem

**Comment by CaramelHeaven** [comment]
Hello @bpkennedy. Did you find out what this means?

**Comment by jthake-msft** [comment]
Closed as no response.
