### ISSUE TITLE
access policy for the permission CallRecords.Read.All

### ISSUE THREAD

**Issue by Jame-Stitel** [microsoftgraph/microsoft-graph-docs#11570]
Hi, how is it possible to limit the application access to only specific users for the permission `CallRecords.Read.All`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca1eed2-d0ca-11de-4f25-f09865605a0f
* Version Independent ID: 9fd423e0-86e4-b7e4-9249-1bacb51e81ad
* Content: [Scoping application permissions to specific Exchange Online mailboxes - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access)
* Content Source: [concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-limit-mailbox-access.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
The page where this question is requested (Application Access Policy for REST) is applicable for Exchange workload & the associated permission scopes. This particular request is for _CallRecords.Read.All_, which belongs to the workload IC3.DataPlatform/Teams. Adding @stephenjust, who is the author of [GET CallRecords](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0)  to comment if a similar feature is available there.

**Comment by stephenjust** [comment]
This is an application-only permission, so it is not bound to any user.

If customers want to use these APIs in user-facing applications, we expect them to set up their own intermediate API with access, and that API can do more specific access control per user.
