### ISSUE TITLE
$filter=endswith apparently also requires $count=true

### ISSUE THREAD

**Issue by zaphod4254** [microsoftgraph/microsoft-graph-docs#11575]
Example 5 using $filter=endswith, please add a note that using endswith also requires using $count=true.  Although the example includes both $orderby and $count, it is not clear that $count is required to make endswith work.  ($orderby is not required for endswith to work, but $count is.)

Maybe also update the description of the ConsistencyLevel header in the "Request headers" section.
"This header and $count are required when using $search, or when using $filter with the $orderby query parameter **or endswith operator.**"

In my use case, I don't care about $orderby.  I only wanted to use the endswith operator on the $filter.

Details...

Tested in 2 different tenants, and both via Graph Explorer and via direct Graph API in Postman in both tenants.

This works for startswith, for comparison:
https://graph.microsoft.com/v1.0/users?$filter=startswith(mail,'smith.')

This does NOT work:
https://graph.microsoft.com/v1.0/users?$filter=endswith(mail,'@contoso.com')
Produces error "Unsupported  Query."

This DOES work (must also have ConsistencyLevel header set because of the $count parameter):
https://graph.microsoft.com/v1.0/users?$filter=endswith(mail,'@contoso.com')&$count=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabdb652-eb03-bae6-fa99-66d71fbdd044
* Version Independent ID: 7f5744b6-6770-586e-217c-4b7ac7657051
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @zaphod4254 for highlighting this issue. I've raised a fix to update the doc with this information. Closing the issue.
