### ISSUE TITLE
Example not provided

### ISSUE THREAD

**Issue by chaitnya12** [microsoftgraph/microsoft-graph-docs#11582]
[Enter feedback here]
Please provide an example for making get request to location of the teamsAsyncOperation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c049b616-d611-c25f-38ac-d7f27702c330
* Version Independent ID: c83604a3-b769-19d4-fee1-9f3090e8f3cc
* Content: [teamsAsyncOperation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teamsasyncoperation.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chaitnya12** [comment]
I am not getting complete URL of location of the teamsAsyncOperation while creating team using [this](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http) API. 
Which base URL to use is not mentioned in the document.
Attaching screenshot for the reference.
![image](https://user-images.githubusercontent.com/32693312/107330267-574b5600-6ad7-11eb-93ca-f368a1833907.png)

**Comment by Mamatha-MSFT** [comment]
@chaitnya12 Thank you for the insights on the document and taking this with internal team.

**Comment by Mamatha-MSFT** [comment]
Hi @chaitnya12 Could you please use `https://graph.microsoft.com/v1.0/ ` as base URL followed by Location.

**Comment by chaitnya12** [comment]
Thanks @Nikitha-MSFT , I am getting response after using this base URL.
