### ISSUE TITLE
Unable to create functional Planner tabs by following the documentation

### ISSUE THREAD

**Issue by siljemda** [microsoftgraph/microsoft-graph-docs#11588]
Unsure if this is a bug or if documentation is missing on how to craft a proper Planner tab request.

The documentation gives examples on creating tabs with displayName, bind and and configuration. However, the documentation states that configuration in Graph is not supported for Planner. By eliminating configuration, using only the required properties (displayName and teamsApp@odata.bind) the result is a tab with a configuration window that cannot be completed using the provided name:

![image](https://user-images.githubusercontent.com/48088663/107382954-c41f1a00-6af0-11eb-8e59-19a5a77872ef.png)

Could you please provide guidance on providing a name without that same name blocking the completion of tab configuration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#planner-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamaMohanaChary** [comment]
Hi @siljemda,

We are checking internally on this, will get back to you soon.

**Comment by RamaMohanaChary** [comment]
Hi @siljemda,

Every time when you create a tab that name should be unique, in case if there is tab already with that name then it won't allow you. So, could you please enter an unique name for that.

**Comment by siljemda** [comment]
@RamaMohanaChary this is what we are currently doing. Tabs are created using custom names just after creation of the team, so there should be no room for conflicting tab names.

**Comment by RamaMohanaChary** [comment]
Hi @siljemda,

As per the document shared by you, will explains only how to create planner tab. Once tab is created, a pop up that opens will show you planner tasks.

When you try to add a Planner Task using graph api or manually, default value will be "Tasks". At first attempt it won't give you an error message. In case if there is tab already with that name then it will give you an error message.

We have to update the name when you face an error message.

It's by design.

**Comment by siljemda** [comment]
@RamaMohanaChary Apologies, this is still unclear to me what you mean. The error message is displayed even if we use a custom title in the API call.

**Comment by Jagadeesh-MSFT** [comment]
Hi @siljemda, could you please share the post request query that your are trying.

**Comment by siljemda** [comment]
I have discussed with the dev who's currently on this and it has been resolved on our end. Thanks for the follow-up.
