### ISSUE TITLE
"Get Lists" page in the wrong section

### ISSUE THREAD

**Issue by jeffreymcclain** [microsoftgraph/microsoft-graph-docs#11618]
The "Get Lists" page should be in the "Lists" section, not the "Sites" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0ccff7-e177-0d55-d5c5-1fb9cf728638
* Version Independent ID: 8955ee30-5dc2-43f3-105d-78d8baf6d727
* Content: [List the SharePoint lists in a site - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/list-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/list-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/list-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by lramosvea** [comment]
Closing as I see this page in the List section already. Please feel free to reopen if the issue persists.
