### ISSUE TITLE
Gettign BadRequest on trying to update autopilot device properties using "updateDeviceProperties action" graph api.

### ISSUE THREAD

**Issue by SaiSasankKhajjayam** [microsoftgraph/microsoft-graph-docs#11620]
I am trying to update the properties of autopilot imported device using the following graph api:

HTTP Request : 

 **https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeviceIdentities/65df8e77-c9e4-437a-a28e-1516072bb878/updateDeviceProperties** 

HTTP Response  : 

{
    "error": {
        "code": "ResourceNotFound",
        "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 385a4302-b11a-49cc-90de-8f584dcb134a - Url: https://fef.msuc01.manage.microsoft.com/DeviceEnrollmentFE_2101/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeviceIdentities%28%2765df8e77-c9e4-437a-a28e-1516072bb878%27%29/microsoft.management.services.api.updateDeviceProperties?api-version=5020-09-14\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
        "innerError": {
            "date": "2021-02-11T03:19:56",
            "request-id": "385a4302-b11a-49cc-90de-8f584dcb134a",
            "client-request-id": "385a4302-b11a-49cc-90de-8f584dcb134a"
        }
    }
}

Can anyone help me to get out of the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be06c68b-8b40-9266-1973-6cb8b21c76f4
* Version Independent ID: 7b4b9ed2-a2a1-0383-36bc-2e0b3b5c8db3
* Content: [updateDeviceProperties action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-windowsautopilotdeviceidentity-updatedeviceproperties?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-enrollment-windowsautopilotdeviceidentity-updatedeviceproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-windowsautopilotdeviceidentity-updatedeviceproperties.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Are you able to post your request body? Don't share anything that might be company confidential information, but I'm curious about which properties you're trying to update.  Also, I assume you verified the {windowsAutopilotDeviceIdentityId} was correct?  I only ask because the error was ResourceNotFound which would first imply that the Id wasn't found.

**Comment by SaiSasankKhajjayam** [comment]
@triplanedave   Thanks for response. 

I am not sharing any company confidential information.

Please find the below scenario where we stuck and not able to proceed further.

1.  We were able to import the device using this "https://graph.microsoft.com/beta/deviceManagement/importedWindowsAutopilotDeviceIdentities" where we supply the device serial number and hardwarehash and "**userPincipleName** "
2.  we will get 200 OK on firing the above request and we will see the same device info in "microsoft endpoint manager".

As per our understanding , above request is doing 2 actions and one is importing the device and second one is assigning the user to device .(basically whatever the value supplied to the userPincipleName will be assigned)

In some of our cases , devices are there and users are not assigned to the device, that time if I fire above request without user, request is successful and device is imported. after some period , I wana trying to assign the user with this https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeviceIdentities/**a670a959-985e-423d-a5ba-c8cf3ae78cb**/assignUserToDevice  its failing. 

**Request** :  https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeviceIdentities/**a670a959-985e-423d-a5ba-c8cf3ae78cb**/assignUserToDevice

RequestBody  :

{
  "userPrincipalName": "test@xyz.onmicrosoft.com",
  "addressableUserName": "test@xyz.onmicrosoft.com"
}

Response :
{
    "error": {
        "code": "BadRequest",
        "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 7d98d1fa-9680-4b61-8133-dc8bdbb45ef6 - Url: https://fef.msuc05.manage.microsoft.com/DeviceEnrollmentFE_2102/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeviceIdentities%28%27a670a959-985e-423d-a5ba-c8cf3ae78cb%27%29/microsoft.management.services.api.assignUserToDevice?api-version=5020-09-14\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
        "innerError": {
            "date": "2021-02-24T10:17:15",
            "request-id": "7d98d1fa-9680-4b61-8133-dc8bdbb45ef6",
            "client-request-id": "7d98d1fa-9680-4b61-8133-dc8bdbb45ef6"
        }
    }
}

We were able to get the device info for same device with this https://graph.microsoft.com/beta/deviceManagement/importedWindowsAutopilotDeviceIdentities/**a670a959-985e-423d-a5ba-c8cf3ae78cbf**

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#deviceManagement/importedWindowsAutopilotDeviceIdentities/$entity",
    "id": "a670a959-985e-423d-a5ba-c8cf3ae78cbf",
    "orderIdentifier": "",
    "groupTag": "",
    "serialNumber": "2733-3603-2688-3601-2700-0291-02",
    "productKey": "a670a959-985e-423d-a5ba-c8cf3ae78cbf",
    "importId": "a670a959-985e-423d-a5ba-c8cf3ae78cbf",
    "hardwareIdentifier": null,
    "assignedUserPrincipalName": null,
    "state": {
        "deviceImportStatus": "complete",
        "deviceRegistrationId": "e13eb486-8502-46e3-8aab-43d81f5f63e5",
        "deviceErrorCode": 0,
        "deviceErrorName": "None"
    }
}


Note : Basically I am looking two individual apis to perform my operation instead of one single api.  Please suggest me the proper api to import device and assign the user to device.

**Comment by triplanedave** [comment]
To assign the user (or update the tag), you can POST to https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeviceIdentities/**_{deviceID}_**/UpdateDeviceProperties with a request body such as: 
{userPrincipalName: "aashka@contoso.onmicrosoft.com", addressableUserName: "Aashka", groupTag: ""}

**Comment by SaiSasankKhajjayam** [comment]
@triplanedave   We have tried the API ,which you suggested for update device properties and  observed the following issues.

Issue 1 :  Need to trigger the UpdateDeviceProperties API twice to update device.
1. Triggered the request to update the device properties using  https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeviceIdentities/**_{deviceID}_**/UpdateDeviceProperties  .
2. Request is Successful and received 200 Ok response.
3. I used the GET https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeviceIdentities/{deviceID} to validate properties or updated or not.
4. Device Properties are not updated.
5. after 10 mins , validated the device properties again and observed that still device is not updated with latest info.
6. Triggered the POST call again with data and request successful . This time device data is updated.
7. Same behavior observed when we repeated the steps to update any device.
8. device properties are updating always for the second call.



Issue 2 : UpdateDeviceProperties API is returning error for few users . (Note: All users in my azure AD have same permissions and licenses) 
1. We  have list of users in Azure AD , where all of them have same permissions and license.
2. For few users UpdateDeviceProperties API is working and successful
3. For few Users UpdateDeviceProperties API is not working and getting bad request.

API Request : https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeviceIdentities/46637f95-4cd4-42fd-8b1f-881106677793/updateDeviceProperties

Request Body : 

{
  "userPrincipalName":"user1_outlook.com#EXT#@xyzoutlook.onmicrosoft.com",
  "addressableUserName":"user1",
  "groupTag": ""
}

Response : 

{
    "error": {
        "code": "BadRequest",
        "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"'user1_outlook.com#EXT#@xyzoutlook.onmicrosoft.com' is not in a valid format. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 8d1affc2-0f79-4293-ae35-6ef6ccc9d3b5 - Url: https://fef.msuc05.manage.microsoft.com/DeviceEnrollmentFE_2102/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeviceIdentities%28%2746637f95-4cd4-42fd-8b1f-881106677793%27%29/microsoft.management.services.api.updateDeviceProperties?api-version=5020-09-14\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
        "innerError": {
            "date": "2021-02-25T07:25:21",
            "request-id": "8d1affc2-0f79-4293-ae35-6ef6ccc9d3b5",
            "client-request-id": "8d1affc2-0f79-4293-ae35-6ef6ccc9d3b5"
        }
    }
}
