### ISSUE TITLE
Updating app roles to existing app registration documentation missing

### ISSUE THREAD

**Issue by jeevanbalanmanoj** [microsoftgraph/microsoft-graph-docs#11625]
Hi, 

quite a few customers are requesting PowerShell scripts or Graph APIs to programmatically add app roles to existing app registrations. Even when a user googles "create app roles ms graph" this document pops but it doesnt say how users can update app roles/ As far as I know, the only way to do it now is to leverage the patch application registration API [here ](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http) Any reference to that documentation would help. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 132fbbaf-f190-38e9-7af0-89aca63f69d7
* Version Independent ID: d68663e4-2d2f-898f-07a2-6748419cdf7b
* Content: [appRole resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/approle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/approle.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@jeevanbalanmanoj Thanks for raising this problem with the docs experience. We're now tracking it with our content team, so I'm closing this Github issue.
