### ISSUE TITLE
Error in examples

### ISSUE THREAD

**Issue by bartvermeersch** [microsoftgraph/microsoft-graph-docs#11637]
The examples in this page (or the titles above the examples) is wrong.

The HTTP request in the first example will probably add an owner, but the response is incorrect.
The request in the second example is incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79f9efdd-1dbf-e2af-6cf1-810d46ef92dc
* Version Independent ID: 4ae0f300-aa78-54c6-f9c0-cc286e756cf9
* Content: [Add member to channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @laujan
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
@surbhigupta12 , these issues shouldn't be assigned to me. la was the former owner of the content, do you know who should be taking over ownership? Thanks.

**Comment by surbhigupta12** [comment]
@Lauragra, I'd check with La and get back.

**Comment by Meghana-MSFT** [comment]
Please update the examples as below:
Example 1 :  Add a member to a channel
Request : 
```
POST https://graph.microsoft.com/v1.0/teams/f16072d7-5c19-4def-9291-1bc778c8cb4c/channels/19%3Aee602f2f295141d8bed4d1c8554bac26%40thread.tacv2/members
Content-type: application/json
Content-length: 100
{
 "@odata.type": "#microsoft.graph.aadUserConversationMember",
 "roles": [],
 "user@odata.bind": "https://graph.microsoft.com/v1.0/users('599cfd99-dab6-4ae4-8458-93ab38edc5fc')"
}
```
Response :
```
HTTP/1.1 201 Created
Content-type: application/json
Content-length: 468

{
"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('f16072d7-5c19-4def-9291-1bc778c8cb4c')/channels('19%3Aee602f2f295141d8bed4d1c8554bac26%40thread.tacv2')/members/$entity",
"@odata.type": "#microsoft.graph.aadUserConversationMember",
"id": "MCMjMiMjMjk1ZTM1NmItNGM3MS00NWQ4LTk4YmYtYzA4NjVlZjRhNGU4IyMxOTplZTYwMmYyZjI5NTE0MWQ4YmVkNGQxYzg1NTRiYWMyNkB0aHJlYWQudGFjdjIjIzU5OWNmZDk5LWRhYjYtNGFlNC04NDU4LTkzYWIzOGVkYzVmYw==",
"roles": [],
"displayName": "Diego Siciliani",
"userId": "599cfd99-dab6-4ae4-8458-93ab38edc5fc",
"email": null
}
```
Example 2: Add a member with the owner role to a channel
Request:
```
POST https: https://graph.microsoft.com/v1.0/teams/f16072d7-5c19-4def-9291-1bc778c8cb4c/channels/19%3Aee602f2f295141d8bed4d1c8554bac26%40thread.tacv2/members
Content-type: application/json
Content-length: 100
{
 "@odata.type": "#microsoft.graph.aadUserConversationMember",
 "roles": ["owner"],
 "user@odata.bind": "https://graph.microsoft.com/v1.0/users('c56d2c27-bd96-4895-92ee-2e87ba051b84')"
}
```
Response:
```
HTTP/1.1 201 Created
Content-type: application/json
Content-length: 468

{
 "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('f16072d7-5c19-4def-9291-1bc778c8cb4c')/channels('19%3Aee602f2f295141d8bed4d1c8554bac26%40thread.tacv2')/members/$entity",
 "@odata.type": "#microsoft.graph.aadUserConversationMember",
 "id": "MCMjMiMjMjk1ZTM1NmItNGM3MS00NWQ4LTk4YmYtYzA4NjVlZjRhNGU4IyMxOTplZTYwMmYyZjI5NTE0MWQ4YmVkNGQxYzg1NTRiYWMyNkB0aHJlYWQudGFjdjIjI2M1NmQyYzI3LWJkOTYtNDg5NS05MmVlLTJlODdiYTA1MWI4NA==",
 "roles": ["owner"],
 "displayName": "Adele Vance",
 "userId": "c56d2c27-bd96-4895-92ee-2e87ba051b84",
 "email": null
}
```

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
