### ISSUE TITLE
"Worksheet: delete" HTTP request format is incorrect 

### ISSUE THREAD

**Issue by jeffreymcclain** [microsoftgraph/microsoft-graph-docs#11677]
The HTTP request format is incorrect, the actual format is:

`DELETE /workbook/worksheets/{id|name}`

as documented separately in this example https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0#delete-a-worksheet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b01bacb2-4946-6f08-a6eb-6e88d4f3e428
* Version Independent ID: 90f4a533-0ff9-3275-de95-ea9f88546649
* Content: [Worksheet: delete - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/worksheet-delete?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/worksheet-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/worksheet-delete.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008

**Comment by lramosvea** [comment]
Closing as doc has been updated
