### ISSUE TITLE
Searching on group for exact term

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#11680]
From the documentation is not clear how to search for a exact term like "foo bar" with `$search` clause. 

Searching on messages works only if the words are separated by the comma.

`https://graph.microsoft.com/v1.0/me/messages?$search="subject:foo,bar"`

Query returns the message with "foo bar" term in the subject.

Searching on groups doesn't work for the term.

```
https://graph.microsoft.com/v1.0/groups?$search="displayName:foo,bar"
https://graph.microsoft.com/v1.0/groups?$search="displayName:foo bar"
https://graph.microsoft.com/v1.0/groups?$search="displayName:"foo bar""
https://graph.microsoft.com/v1.0/groups?$search="displayName:'foo bar'"
```

Queries above return either all groups or groups with "foo" or "bar" in the subject but not the group with the exact term "foo bar" in the subject.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o

**Comment by Licantrop0** [comment]
hi @MartinM85, if you want an exact match you need to use `$filter=property eq 'value'` syntax.
like this: https://graph.microsoft.com/v1.0/groups?$filter=displayName eq 'foo bar'
