### ISSUE TITLE
ErrorInsufficientPermissionsInAccessToken

### ISSUE THREAD

**Issue by KevUdeM** [microsoftgraph/microsoft-graph-docs#11683]
Hi,

Even if I am global/tenant admin and User.Read, User.Read.All are present , I get an error when trying to list the properties :
        "code": "ErrorInsufficientPermissionsInAccessToken",
        "message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.",

What am i missing ? 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05519ea9-cfab-6668-4e5f-71199518acf1
* Version Independent ID: 9211d5d0-b709-c008-e8d6-3e541bbc4b4e
* Content: [List profileCardProperties - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/organizationsettings-list-profilecardproperties?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/organizationsettings-list-profilecardproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/organizationsettings-list-profilecardproperties.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger

**Comment by shayaneumar-mitel** [comment]
Click to vote
0 Votes"
0
ShayaneUmar-1910 answered · 58 minutes ago
I am also facing the same issue but with different resource(phone), it was all working fine 5 days ago.
I have User.ReadBasic.All permission as mentioned in document.
https://docs.microsoft.com/en-us/graph/api/profile-list-phones?view=graph-rest-beta&tabs=http

{
"error": {
"code": "ErrorInsufficientPermissionsInAccessToken",
"message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileAccessDeniedException' was thrown.",
"innerError": {
"date": "2021-02-25T03:27:38",
"request-id": "487ea242-f51f-4a0c-86b5-838bfd6efba7",
"client-request-id": "d329d5a4-c894-e2d1-d874-71a691af3d09"
}
}
}

Request URL: https://graph.microsoft.com/beta/users/<userid>/profile/phones?$select=number,type
Request Method: GET
Status Code: 403 Forbidden
