### ISSUE TITLE
Meeting Id is corrupted

### ISSUE THREAD

**Issue by mlindemu** [microsoftgraph/microsoft-graph-docs#11696]
Hello, when I make the following request:

```
Authorization: Bearer {token}

GET https://graph.microsoft.com/beta/me/onlineMeetings/MCMxOTptZWV0aW5nX056bGtZMlJrT0RNdE9XVTJOQzAwTXprNUxUbGtZbVF0TmpZek5qQXdPVFUyTmpBNUB0aHJlYWQudjIjMA==
```

I receive the following response:
```json
{
    "error": {
        "code": "BadRequest",
        "message": "Meeting Id is corrupted.",
        "innerError": {
            "date": "2021-02-18T18:36:54",
            "request-id": "ad8c17bd-2f2e-411a-b820-d67856342fd4",
            "client-request-id": "ad8c17bd-2f2e-411a-b820-d67856342fd4"
        }
    }
}
```

I retrieve the meeting ID using the Microsoft Teams JavaScript SDK inside a Teams tab.  I suspect the format of the SDK's context.meetingId is different from what Microsoft Graph expects.

What format does Microsoft Graph require for the meetingId field in this GET request? Would be very helpful to either have a sample meeting ID in the field description or a sample request with a sample meeting ID.

Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9593d8-ed60-527f-c549-b22dce5adbd9
* Version Independent ID: cdf36bed-fd4f-8be7-918c-6cdf74258676
* Content: [Get onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr

**Comment by dima-ivanov-pdffiler** [comment]
I have same problem, do you solved it?

**Comment by lemonpowah** [comment]
Same issue here. As per [this](https://docs.microsoft.com/answers/answers/180143/view.html )answer:
- You can retrieve the meeting by its joinUrl (You get the join URL from the Share Invite screen if you want to quickly access this)
- The call would then be https://graph.microsoft.com/beta/me/onlineMeetings?filter=joinWebUrl eq '{meetingUrl}'
- You will receive an array because of the filter, but when you inspect it, surprise, the meeting ID is actually longer and different.
- I suspect you get the meeting ID from the microsoft-teams-sdk, I guess there's a bug there.

You can try using the filter (which works only on the beta endpoing atm) or wait for a teams sdk update.

**Comment by mlindemu** [comment]
For anyone who runs into this, the Microsoft Teams SDK meeting ID is a shortened version of the one required for Microsoft Graph endpoints.

For example, the Teams JavaScript SDK will return a meeting ID like this:
```
MCMxOTptZWV0aW5nX3BCcTZuMVpDdktVUWFXakxpN2xSdXFEZG1aT3ZmYkNLS1ZGeFBmYWxqd1ZPU3dybUB0aHJlYWQudjIjMA==
```

The ID above can be base64 decoded to:
```
0#19:meeting_pBq6n1ZCvKUQaWjLi7lRuqDdmZOvfbCKKVFxPfaljwVOSwrm@thread.v2#0
```

Microsoft Graph cannot use this Meeting ID. Instead, it expects the following ID format:
```
1*{Meeting Organizer OID}*0**{string between 0# and #0 in base64 decoded Teams Meeting ID above}
```

For example, take the following randomly generated sample values:
* Meeting Organizer (User) OID
** c8cb7bb2-fb4d-4247-905f-1c52d6bec960
* String from Teams SDK Meeting ID
** 19:meeting_pBq6n1ZCvKUQaWjLi7lRuqDdmZOvfbCKKVFxPfaljwVOSwrm@thread.v2

Generate the following string:
```
1*c8cb7bb2-fb4d-4247-905f-1c52d6bec960*0**19:meeting_pBq6n1ZCvKUQaWjLi7lRuqDdmZOvfbCKKVFxPfaljwVOSwrm@thread.v2
```

Lastly, base64 encode the string above to create the Microsoft Graph Online Meeting ID
```
MSpjOGNiN2JiMi1mYjRkLTQyNDctOTA1Zi0xYzUyZDZiZWM5NjAqMCoqMTk6bWVldGluZ19wQnE2bjFaQ3ZLVVFhV2pMaTdsUnVxRGRtWk92ZmJDS0tWRnhQZmFsandWT1N3cm1AdGhyZWFkLnYy
```

Now you have an ID that can be used with Microsoft Graph to work with an Online Meeting resource.

**Comment by AJIXuMuK** [comment]
@mlindemu - how do you get the organizer ID from the SDK? I don't see in the context

**Comment by mlindemu** [comment]
@AJIXuMuK, you can't. The answer under @lemonpowah issue from @Nikitha-MSFT makes it sound like they won't add this functionality:

> Currently the specific meeting metadata received from client sdk can not be used to interact with graph. This is by design.

_Originally posted by @Nikitha-MSFT in https://github.com/OfficeDev/microsoft-teams-library-js/issues/539#issuecomment-821144558_

**Comment by AJIXuMuK** [comment]
Sad, as from my vision it's useless :)
