### ISSUE TITLE
issuerAssignedId Service Limits

### ISSUE THREAD

**Issue by Kasenga** [microsoftgraph/microsoft-graph-docs#11693]
Hello team!
Are there any service limits to consider while working with issuerAssignedId?

Is there a defined limit for length above and beyond the  standard definition for an email address?

In your documentation, you mention, "_Additional validation is enforced on issuerAssignedId when the sign-in type is set to emailAddress or userName_". Can you provide the full validation that is required for this field?

For example, if the value of issuerAssignedId is longer that 100 characters, I'm seeing the response, "_Request_BadRequest, Unsupported property or property value or combination of property and operation occurred_"

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a27bcc-3c5c-f12a-17f2-4afb365bb0f4
* Version Independent ID: c72e021b-c801-a398-b5b5-19bc8b565fe7
* Content: [objectIdentity resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/objectidentity?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/objectidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/objectidentity.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain

**Comment by djswilly** [comment]
I am getting a similar error when attempting to create a user with an issuerAssignedId longer than 100 characters. We need to know what validation is required. It is definitely the issuerAssignedId causing the problem as I can create a user with the same details and a 100 character email address with no issues, if a 101 character email address is used then I get the following:

"error": {
    "code": "Request_BadRequest",
    "message": "Invalid value specified for property 'identities' of resource 'User'.",
    "innerError": {
      "date": "2021-03-02T11:31:00",
      "request-id": "d016e6d1-ddf8-4862-ba70-392dac174bc8",
      "client-request-id": "d016e6d1-ddf8-4862-ba70-392dac174bc8"
    },
    "details": [
      {
        "target": "identities",
        "code": "InvalidValue"
      }
    ]
  }

**Comment by FaithOmbongi** [comment]
Thank you @Kasenga, @djswilly for raising your issues. The only validation performed on issuerAssignedId today is that the maximum length can't be greater than 100 characters. If your email address is longer than that, you'll hit an error. I'll raise a PR to indicate this in the doc.

@djswilly Our feature team is currently working to enforce the 64-character limit on the local part of the email address as per standard.

Closing this issue for now.
