### ISSUE TITLE
Get Table Range: Request body is missing

### ISSUE THREAD

**Issue by jeffreymcclain** [microsoftgraph/microsoft-graph-docs#11717]
https://docs.microsoft.com/en-us/graph/api/table-range?view=graph-rest-1.0&tabs=http#request-body
The request body is missing for the Table > Get range documentation.

https://docs.microsoft.com/en-us/graph/api/worksheet-get?view=graph-rest-1.0&tabs=http#request-body
Note that for other documentation. there is text stating "Do not supply a request body for this method." if the body is not supposed to be included.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0bf7332-8e08-b82a-c9d7-e8a4e6f7aee2
* Version Independent ID: 5ac3b882-6a6a-1779-ded2-460ba2b29e03
* Content: [workbookTable: range - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/table-range?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/table-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/table-range.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008

**Comment by grangeryy** [comment]
fix with this [PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/14069)
