### ISSUE TITLE
Getting it working - C#

### ISSUE THREAD

**Issue by PieterHeemeryck** [microsoftgraph/microsoft-graph-docs#11748]
This is a request to modify the documentation or improve on the C# Graph (beta) SDK to reflect my findings.

I spent quite some time figuring out this call in the C# Graph SDK. The documentation states a PUT call must be made using .PutAsync(...). However, the latest Graph beta SDK (0.38.0-preview) does not even have this method. Instead, an .UpdateAsync(...) method is provided which performs a PATCH, which the Graph is not having.

This is how I managed to get the call working:

// Get access review definition ('ard') & modify the properties you want
// Verify that the Settings.Range.Type is not set to numbered when the numberOfOccurrences is set to 0 (error!)
// ard.Settings.Recurrence.Range.Type = Beta.RecurrenceRangeType.NoEnd;
// ard.Settings.Recurrence.Range.StartDate = new Date(newStartDate.Year, newStartDate.Month, newStartDate.Day);
// ard.DisplayName = $"{ard.DisplayName} updated from console app";

// Setting the ODataType to null is required or the PUT request will fail
ard.ODataType = null;
ard.Settings.ODataType = null;
ard.Settings.Recurrence.ODataType = null;
ard.Settings.Recurrence.Pattern.ODataType = null;
ard.Settings.Recurrence.Range.ODataType = null;
ard.Scope.ODataType = null;
ard.CreatedBy.ODataType = null;
ard.InstanceEnumerationScope.ODataType = null;
foreach(var reviewer in ard.Reviewers){reviewer.ODataType = null;}
foreach(var backupReviewer in ard.BackupReviewers){backupReviewer.ODataType = null;}

var httpReqMessage = BetaClient.IdentityGovernance.AccessReviews.Definitions[ard.Id]
.Request()
.GetHttpRequestMessage();

httpReqMessage.Method = HttpMethod.Put; // Required: PATCH (aka UpdateAsync) calls fail
httpReqMessage.Content = BetaClient.HttpProvider.Serializer.SerializeAsJsonContent(ard);

await BetaClient.AuthenticationProvider.AuthenticateRequestAsync(httpReqMessage);
var updatedArdResponse = await BetaClient.HttpProvider.SendAsync(httpReqMessage);

I do would like to know the reason for having to set the ODataType to null...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64c71fdb-0c82-1188-11ef-d77329f9b4b2
* Version Independent ID: f211b883-2ea6-f525-05df-d647d398e5fd
* Content: [Update accessReviewScheduleDefinition - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accessreviewscheduledefinition-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @isabelleatmsft

**Comment by isabelleatmsft** [comment]
Hey @FaithOmbongi , this looks like a client SDK issue. Are you able to transfer this to that team?

**Comment by FaithOmbongi** [comment]
Hi @andrueastman , kindly assist to resolve this issue.

**Comment by FaithOmbongi** [comment]
Reopening this issue because it was not resolved in the new snippets.

**Comment by FaithOmbongi** [comment]
To be automatically resolved when new snippets are regenerated next week.
