### ISSUE TITLE
Update document to state that guest members cannot be added to a team with app permissions

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-docs#11757]
Related https://github.com/microsoftgraph/microsoft-graph-docs/issues/11756

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7279fc44-89a2-5b5e-1064-a5701880a564
* Version Independent ID: 095d95ca-2198-9cfe-ef6a-3a69ed5bcfe9
* Content: [Add member to team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer

**Comment by v-chetsh** [comment]
@MIchaelMainer - This issue is related to document enhancement, so redirecting to doc-enhancement team.

**Comment by v-chetsh** [comment]
@nkramer, @lramosvea - Please let us know once it is updated, so that we can close this issue.

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please help us to update the documentation.

**Comment by v-chetsh** [comment]
Hello @v-abirade - Could you please share the updates on this?
