### ISSUE TITLE
itemAttachment contentBytes

### ISSUE THREAD

**Issue by andreastheodosiou** [microsoftgraph/microsoft-graph-docs#11786]
The so far readings do not solve the problem of getting contentBytes of itemAttachment. We have an email A, that has an email B as attachment, and email B has a jpg (for example) as an attachment. So far I have not seen a way to get the contentBytes of email B (the itemAttachment of email A). The $value and $expand give you details of email B but not the contentBytes of email B.

Let me know what we are doing wrong
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a57348-6af4-4184-6af7-6cf160b3c123
* Version Independent ID: 4b319adc-597f-ced4-503e-a287b85d1db0
* Content: [Get attachment - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/attachment-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das

**Comment by jasonjoh** [comment]
[itemAttachment](https://docs.microsoft.com/graph/api/resources/itemattachment?view=graph-rest-1.0) does not have a `contentBytes` property. The `$value` property gives you the MIME contents of the file.

Issues in this repository aren't a good forum for getting answers to Graph questions - they are intended for reporting issues with the documentation itself. For quicker answers to your questions, please post on [Microsoft Q&A](https://docs.microsoft.com/answers/questions/ask.html) with an appropriate `microsoft-graph*` tag.
