### ISSUE TITLE
Need clarity on how to associate the ID of the approleassignment object with the approle

### ISSUE THREAD

**Issue by max-vaughn** [microsoftgraph/microsoft-graph-docs#1179]
Issue: 
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/approleassignment

It is not clear the relationship between this object, approleassignment and its customer appRole.  The ID field comes back as an encoded strings, the format of which is not clearly explained.  More information needs to be provided.
Article:

**Comment by lmenzel** [comment]
The id field of the approleassignment should contain the id of the assigned role, as described here: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/approleassignment
but in the current beta api https://graph.microsoft.com/beta/servicePrincipals/{principalId}/appRoleAssignments another id is returned (possibly the id of the approleassignment itself)

**Comment by LoulG** [comment]
Regarding the documentation, the id property returned by [](https://graph.microsoft.com/beta/servicePrincipals/%7BprincipalId%7D/appRoleAssignments) should contain a Guid.
Which is not the case at the time of writing.

**Comment by mihirnanavati93** [comment]
Is there any update on this? I am also confused about how to associate id field with tenant appRole.

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
