### ISSUE TITLE
Documented number of maximum search results with $search param incorrect

### ISSUE THREAD

**Issue by andreaszecher** [microsoftgraph/microsoft-graph-docs#11800]
On this page the following is mentioned:

`A $search request returns up to 250 results.`

However the actual search result limit seems to be 275?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#using-search-on-message-collections)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o

**Comment by Licantrop0** [comment]
this is outlook, @JefWight still you?

**Comment by JefWight** [comment]
Sorry for the delay.  I haven't been in this area for quite some time.  Do you have another contact in Outlook?
