### ISSUE TITLE
Where is C# code for this?

### ISSUE THREAD

**Issue by under3415** [microsoftgraph/microsoft-graph-docs#11815]
Is it possible to perform this using C#?

Other Graph articles had HTTP code, but also C#. Can this be dine using C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods

**Comment by Jackson-Woods** [comment]
@davidmu1 Can we add MSAL C# in a tabbed code view for the authentication flow examples here (or better yet, for all our supported languages)?

**Comment by FaithOmbongi** [comment]
ask internally if it would be possible to add these tabs in this article type. In the meantime, I've raise a a PR to link to this [Azure docs list of MSAL libraries for the different frameworks](https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries).
