### ISSUE TITLE
How to handle multiple signed in users

### ISSUE THREAD

**Issue by under3415** [microsoftgraph/microsoft-graph-docs#11816]
When identity client app caches multiple user credentials, how does authProvider "know" which one to use?

Can you add some info on this?

I assume the flow should be:
1. Check for cached credentials
2. Ask user which one they want to use
3. Either silently sign in to the chosen credential, or initiate authorization from scratch if users wants none

Can you provide an example on how to do this? I can get cached credentials from identity client app using this code:

`await IdentityClientApp.GetAccountsAsync();`

But it is not clear how to pass account to authProvider. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef52833-8b23-b9cd-4337-73eec3c34f4d
* Version Independent ID: 9b012e4f-93b3-bda8-0e35-1c9c6326295c
* Content: [Create a Microsoft Graph client - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=CS)
* Content Source: [concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/create-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer

**Comment by jasonjoh** [comment]
There are a few ways you could accomplish this. 

First, the .NET SDK have moved away from the auth providers implemented in the Microsoft.Graph.Auth package. You can now [use the Azure Identity SDK's credential objects to authenticate](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/tokencredentials.md). The Azure Identity SDK implements a number of different credentials for different scenarios, but for user scenarios they tend to assume a single-user setup.

For a scenario where you want to manage multiple identities in one app, probably the simplest way to handle it would be to create a separate `GraphServiceClient` for each identity. If that's not possible, then a custom implementation of `IAuthenticationProvider` could work, where you use MSAL directly for token acquisition and choose the appropriate account from MSAL's cache.
