### ISSUE TITLE
Error in Logic App (403)

### ISSUE THREAD

**Issue by JohnWuensche** [microsoftgraph/microsoft-graph-docs#11818]
Hello everyone,

i am experiencing issues with a Logic App regarding the Error-Code 403.

"error": {
    "code": "Authentication_RequestFromNonPremiumTenantOrB2CTenant",
    "message": "Neither tenant is B2C or tenant doesn't have premium license","

The Error is **not** occurring with every run of the LA but in some runs it occurs while using a custom connector that calls this Graph Endpoint: "https://graph.microsoft.com/beta/reports/credentialUserRegistrationDetails"

The Tenant got a AAD P2 Licence and the User that is calling the API is also licensed with AAD P1.

Thanks for your help.
Regards
John
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786282cc-2e01-7a67-bff8-7fdfc069d8f3
* Version Independent ID: 56775e93-d8b0-9fda-88ce-b6dd762a11c5
* Content: [List credentialUserRegistrationDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler

**Comment by J-a-k-o-b** [comment]
I'm also experiencing this issue in my tenant. I use a logic app custom connector. The user which is used for the connection has a P2 License Assigned. Most of the runs now lead to the 403 error. Some runs succeed without an error.

**Comment by Koldmunch** [comment]
I have the same issue. Sometimes the call is returning data, sometimes I get the license error as described.

**Comment by FaithOmbongi** [comment]
Thank you @JohnWuensche, @J-a-k-o-b , @Koldmunch for the feedback. Unfortunately this forum isn't monitored for functionality issues, but questions like this are closely monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). 

If it's not too much to ask, whoever posts the question first can come back and comment with a link to the post for others to voice out the same issue. Closing this issue for now.
