### ISSUE TITLE
Inconsistient results

### ISSUE THREAD

**Issue by TheMasterPrawn** [microsoftgraph/microsoft-graph-docs#11881]
Hi Team, 

I see that https://graph.microsoft.com/v1.0/groups/{id}/transitiveMembers/microsoft.graph.user returns users but
https://graph.microsoft.com/v1.0/groups/{id}/transitiveMembers/microsoft.graph.group does not return group, it just returns a bad request. This is inconsitient with the /groups/{id}/members endpoint. 

In this case I am only trying to return transitiveMembers that are groups, but i cannot find a filter that works, can the doc be updated with the correct usage of this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37eaad48-9559-ab5c-5b83-338f53fbbc6f
* Version Independent ID: 591556a3-d528-7f19-e03b-3bf5a67bce51
* Content: [List group transitive members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-transitivemembers.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @TheMasterPrawn for raising this issue.
@Jordanndahl Replicated this customer issue. I can see the member groups in the response of the /groups/{id}/members, can filter /groups/{id}/transitiveMembers by microsoft.graph.users OData cast, but not by the microsoft.graph.group OData cast. FYA.

**Comment by TheMasterPrawn** [comment]
Thanks @FaithOmbongi for the note. What are the next steps in this ? Is it being considered for a fix ?

**Comment by FaithOmbongi** [comment]
@TheMasterPrawn, this seems to be a bug. Unfortunately this forum isn't monitored for functionality issues, but you can post this at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-groups.html). Please add the **bug** tag. 

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.

**Comment by FaithOmbongi** [comment]
**Posting another response after further investigations**

Using OData cast to filter the results of the [transitiveMembers API](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http) requires using the [advanced query parameters](https://docs.microsoft.com/en-us/graph/aad-advanced-queries), that is the **ConsistencyLevel** header set to `true` and the `$count=true` query string. This applies for all OData cast types. I've raised a PR to update the page.
