### ISSUE TITLE
Clarify license requirement: "application permissions for specific channels and chat threads"

### ISSUE THREAD

**Issue by mishakogan** [microsoftgraph/microsoft-graph-docs#11894]
Can you please clarify the exact meaning of 

> or with application permissions for specific channels and chat threads

^ Can a customer create an application with access to ALL channel and chat threads and NOT have to pay anything additional (assume customer is E3) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f880b9-2394-f540-9b06-bcddbe40bfa8
* Version Independent ID: 22de9e03-e917-bcc6-abd7-ebfb3a0cdec8
* Content: [Licenses for subscribing to chat messages - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-licenses)
* Content Source: [concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-licenses.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mishakogan** [comment]
@nkramer - we would greatly appreciate your help on this!

**Comment by Nikitha-MSFT** [comment]
@mishakogan - When you create a subscription using application permissions you does not require any additional licensees to create a subscription.
