### ISSUE TITLE
Update Group Sometimes Returns HTTP 200 Instead of HTTP 204

### ISSUE THREAD

**Issue by cparker-msft** [microsoftgraph/microsoft-graph-docs#11905]
[Enter feedback here]
When updating a group, sometimes an HTTP 200 response is returned rather than an HTTP 204. This seems to occur specifically when updating properties that are handled by Outlook REST rather than the AAD REST endpoint. For example, the allowExternalSenders and autoSubscribeNewMembers properties.

PATCH https://graph.microsoft.com/v1.0/groups/{groupId}
{
    "allowExternalSenders": "true",
    "autoSubscribeNewMembers": "true"
}

HTTP/1.1 200 OK

A $whatif containing these messages shows that these properties are being handled by Outlook REST:

PATCH https://graph.microsoft.com/v1.0/groups/{groupId}?$whatif

{
    "Description": "Execute the main request and notify async",
    "MainRequest": {
        "Description": "Execute HTTP request",
        "Uri": "https://outlook.office365.com/api/v2.0/groups/305d67ce-45df-48d0-a555-f5e2f1f9d57f@9d66e685-baf7-4437-a2d3-e84d0a1424f3",
        "HttpMethod": "PATCH",
        "TargetWorkloadId": "Microsoft.Exchange"
    },
    "NotifyUrls": {
        "Microsoft.Exchange": "https://outlook.office365.com/EWS/Exchange.asmx",
        "Microsoft.SharePoint": "[spoRootSiteResource]/_vti_bin/client.svc/ProcessQuery",
        "Microsoft.Teams.GraphSvc": "https://teamsgraph.teams.microsoft.com/v1.0/instantonnotification"
    }
}

Can the documentation be updated to reflect that this operation may also result in a HTTP 200 response?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fd4acca-d6dc-403f-5a29-6efbf532c9e3
* Version Independent ID: b2a352f9-d11a-2487-4a47-9b238f083565
* Content: [Update group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-update.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @cparker-msft for raising this issue—and yes, you're right. You receive response code 200 when updating Exchange workload-specific properties. We'll raise a fix to update the page. Closing this issue.
