### ISSUE TITLE
Can't get photo for one user

### ISSUE THREAD

**Issue by adsfjhbsdjfhbdsjfhb** [microsoftgraph/microsoft-graph-docs#11967]
Hi, am trying to get the photo of an other user, but this isn't working.

I've tried this in postman for example https://graph.microsoft.com/beta/users/{5bfbc0a2-90cd-4c8e-acf6-987ef68b8d6a | email@address.com}/photo?$value with an app-only token, but it doesn't work, I get a 404 so the syntax must be wrong.

Is this the right way to query this?

Also, why don't you guys list actual examples when sharing your query templates as such? This would help with working out the syntax!!

GET /me/photo/$value
GET /users/{id | userPrincipalName}/photo/$value
GET /groups/{id}/photo/$value
GET /me/contacts/{id}/photo/$value
GET /users/{id | userPrincipalName}/contacts/{id}/photo/$value
GET /me/contactfolders/{contactFolderId}/contacts/{id}/photo/$value
GET /users/{id | userPrincipalName}/contactfolders/{contactFolderId}/contacts/{id}/photo/$value

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff825d93-a760-df51-c5e6-6d1908149047
* Version Independent ID: 12917a72-1596-c079-4fc2-69a3221b9637
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
The ` {id | userPrincipalName}` bit in the URL is intended to convey that you can use either the user's `id` property or the user's `userPrincipalName`. Basically anywhere you see curly-braces `{}`, that indicates a placeholder where you insert some value, and if you see a pipe `|` it indicates an OR.

Correct syntax from your request would be either of these:

```
https://graph.microsoft.com/beta/users/5bfbc0a2-90cd-4c8e-acf6-987ef68b8d6a/photo?$value
https://graph.microsoft.com/beta/users/email@address.com/photo?$value
```

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
ok, I also tried those, but they don't work.

When's the last time you've actually tried those 2 queries and they worked for you?

And, actually, there is a / in the sample request

GET /users/{id | userPrincipalName}/photo/$value

you are doing it without the last /

this is probably the problem then, please confirm.

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
https://graph.microsoft.com/beta/users/email@address.com/photo?$value doesn't work for me either with an app token:

![image](https://user-images.githubusercontent.com/74684638/110961771-12217a80-8348-11eb-9d64-2047da6485bf.png)

**Comment by jasonjoh** [comment]
Ah I missed that you had a `?` in your URL - I had just copy/pasted it from your post. Yes it needs to be a `/`. [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer) is great for testing this stuff.

![image](https://user-images.githubusercontent.com/8966342/110961813-35373480-831e-11eb-8794-f5e471af823b.png)

**Comment by jasonjoh** [comment]
If you're getting a 401 there's an auth issue unrelated to your URL.

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
The question mark came from your comment so I tried the same:

![image](https://user-images.githubusercontent.com/74684638/110962216-a25fbf80-8348-11eb-9e2f-2794f0ea65d0.png)

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
However, even this doesn't work
https://graph.microsoft.com/beta/users/email@address.com/photo/$value
gives me the same 401
yes, I can tell there's an auth issue, but this is how you Microsoft, have built your API collection at https://docs.microsoft.com/en-us/graph/use-postman

your collection doesn't work when this endpoint is used to try and retrieve an other users' photo with an app-token, please test and update your collection then if it is wrong.

**Comment by jasonjoh** [comment]
I'm sorry you're having trouble, but the collection is working fine for me. It doesn't have a ready-made "Get photo" request for app-only, but I modified the existing "Get Users" and it worked fine. What is the response body you get from Postman?

![image](https://user-images.githubusercontent.com/8966342/110963540-2d788f80-8320-11eb-81d5-c884cdbbda3c.png)

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
Glad it's working for you.
This is what I get despite doing everything by the book.
I just downloaded the forked version from MS' postman collection and modified nothing save the get url.
Doesn't work for me with either the email address or GUID, I get the same result.
The token is app-only, not user.
![image](https://user-images.githubusercontent.com/74684638/110971163-6e899780-8352-11eb-827b-a8e9b7e16145.png)

**Comment by jasonjoh** [comment]
That's helpful. This usually indicates that the permissions you configured on your app registration haven't been consented by an admin. Check your app registration's **API permissions** tab and verify that `User.Read.All` is listed, it's type is **Application**, and the status says **Granted for...**.

![image](https://user-images.githubusercontent.com/8966342/110972406-f6a77700-8329-11eb-9481-f83f22fb3ef4.png)

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
Oh, ok, that's fine, will check that then.

However, as per my initial request, please provide actual examples with actual values for all the request templates you've pasted as examples in the article.

"GET /users/{id | userPrincipalName}/photo/$value" is especially misleading at first glance to anyone that doesn't work for Microsoft as it looks as one should supply both the id and UPN in the request.

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
Come to think of it, even documenting this error and why it occurs would be good to have in this article, as it would also be good to have in all other articles.
It would also be good if the PostMan collection had links to these docs in the Documentation tab as sometimes it's hard to find the documentation for a specific request in the Postman collection.

Thanks.
