### ISSUE TITLE
Authentication error - RequestFromNonPremiumTenantOrB2CTenant

### ISSUE THREAD

**Issue by Koldmunch** [microsoftgraph/microsoft-graph-docs#11986]
I get the following error almost every time I use the endpoint. Sometimes I get data using the exact same call and credentials. 

![image](https://user-images.githubusercontent.com/8860722/111160308-3ffdfd80-859a-11eb-8a9e-e005ca1840d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786282cc-2e01-7a67-bff8-7fdfc069d8f3
* Version Independent ID: 56775e93-d8b0-9fda-88ce-b6dd762a11c5
* Content: [List credentialUserRegistrationDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by michevnew** [comment]
Same here, this seems to be a recent change as it was working previously on a O365 Dev tenant (Azure AD for Office 365 SKU).

**Comment by ghadirim** [comment]
same here...Was working as of last Thursday, then Friday started seeing errors.

**Comment by apollon7** [comment]
Same here, getting this error since yesterday when querying signIns (application permissions).

**Comment by besiler** [comment]
All, Azure AD engineering analyzed this issue. We are working on a fix for this error that should be deployed in the next few weeks. Please let me know if this is blocking or disrupting any of your production queries or other vital workloads.

**Comment by michevnew** [comment]
Ben, can you please clarify what are Microsoft's plans with regards to licensing going forward? The documentation still mentions that a P1/P2 license will be required, but this makes no sense to me. Both functionalities that are covered by this report are free for use with every O365/M365 subscription, why would reporting on them require AAD Premium? If this is just to distinguish from the "free" tier, please update the requirements to explicitly mention the "Azure AD for Office 365" SKU as eligible.

**Comment by ghadirim** [comment]
Hi @besiler This is production impacting our customers Azure Sentinel service from us and we are continuing to see this error.   We are a managed detection and response provider and need a fix sooner or a better timeline.

**Comment by dkmonaghan** [comment]
+1 also seeing this here. Would greatly appreciate a fix as this is service impacting. I'm surprised the ETA is 'a few weeks' on something like this.

**Comment by besiler** [comment]
Based on your comments, we accelerated a fix for this that we delivered last week. Are you still seeing the behavior? If so, please let me know

**Comment by michevnew** [comment]
Thanks Ben. I'm still seeing the same error on an old dev tenant (Azure AD for Office 365 SKU). Can you please clarify whether this will be license-restricted going forward?

**Comment by dkmonaghan** [comment]
> Based on your comments, we accelerated a fix for this that we delivered last week. Are you still seeing the behavior? If so, please let me know

Still not resolved for us. We have an Azure AD Premium P1 license.

**Comment by besiler** [comment]
> > Based on your comments, we accelerated a fix for this that we delivered last week. Are you still seeing the behavior? If so, please let me know
> 
> Still not resolved for us. We have an Azure AD Premium P1 license.

Thanks for the info! Can you send me the tenant ID where you're seeing the problem so I can ask our team to troubleshoot? You can email me at besiler@microsoft.com

**Comment by dkmonaghan** [comment]
> > > Based on your comments, we accelerated a fix for this that we delivered last week. Are you still seeing the behavior? If so, please let me know
> > 
> > 
> > Still not resolved for us. We have an Azure AD Premium P1 license.
> 
> Thanks for the info! Can you send me the tenant ID where you're seeing the problem so I can ask our team to troubleshoot? You can email me at [besiler@microsoft.com](mailto:besiler@microsoft.com)

Details sent over. Thank you.

**Comment by dkmonaghan** [comment]
Hi all,

I have just discovered this blog post: https://blogs.aaddevsup.xyz/2021/03/receiving-error-neither-tenant-is-b2c-or-tenant-doesnt-have-premium-license-from-microsoft-graph/

Adding the Directory.ReadAll permission has resolved this bug in my case.

Best,
Dan

**Comment by michevnew** [comment]
> According to the docs, this endpoint requires at least P1: https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta
> 
> Overall, I've heard the feedback loud and clear that many customers think that some of the endpoints that currently require P1 should also work for the O365 apps license level. In general, our licensing team requires that programmatic export of Azure AD data requires P1 or above. I'll make sure that they hear this feedback, however

Thanks Ben, and I know this is not the right place to discuss licensing. Just mentioned it here because the endpoint did seem to work previously on that dev tenant. For the record, never had an issue with P1 tenants.

**Comment by FaithOmbongi** [comment]
Thank you all for posting your issues and feedback.

- The original issue was a bug that has since been resolved.
- Regarding the licensing plans, we have raised this issue internally. But, we recommend that as customers, you can raise this request via the [Microsoft 365 Developer Platform Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) space so other customers can upvote it. You can post the link back here to refer others to vote for it.

No current updates identified for the [List credentialUserRegistrationDetails](https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http) page. Closing the issue.
