### ISSUE TITLE
Broken link to known issue

### ISSUE THREAD

**Issue by tommysanterre** [microsoftgraph/microsoft-graph-docs#11998]
In the Get a list of groups using beta APIs section there is a note.
Note: Certain unused old teams will not be listed. For details, see known issues.

But the known issues does not mention this issue and the links brings us to the top of the page.
Was the issue resolved and the doc not updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75dbe68-e162-8861-d194-4a29de3bd731
* Version Independent ID: f58a6930-8575-8306-4273-fc413b979879
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#feedback)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-list-all-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Mamatha-MSFT** [comment]
Hi @tommysanterre, Since it is a doc bug, I will raise a doc bug and concerned team will work on it.

**Comment by lramosvea** [comment]
@Mamatha-MSFT I believe the issue was resolved but you can confirm. If so, the note should be removed from this page.

**Comment by tommysanterre** [comment]
The issue is not resolved. There is still a link to the know issue page and there is no mention of the word unused in that page.

**Comment by lramosvea** [comment]
Closing as doc has been updated. Thanks.
