### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by lukeAnderson2015** [microsoftgraph/microsoft-graph-docs#11995]
"query": "test path:\"https://contoso.sharepoint.com/sites/Team Site/Documents/Project\\""

I think this example has an extra escape-quotes backslash at the end.
Should it be
"query": "test path:\"https://contoso.sharepoint.com/sites/Team Site/Documents/Project\"" ?

GitHub is auto-fixing the issue, but MS Docs shows an extra backslash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **yiwenwang**

**Comment by cristianv-ms** [comment]
Hi lukeAnderson2015,

You were right, there was an extra escape-quotes at the end of the query. 

You can use this query:
"test path:\"https://contoso.sharepoint.com/sites/Team Site/Documents/Project\\"

or without the double backslash at the end:
"test path:\"https://contoso.sharepoint.com/sites/Team Site/Documents/Project"

You will get the same result.

**Comment by lramosvea** [comment]
@cristianv-ms I see in the do the following query example: "test path:\"https://contoso.sharepoint.com/sites/Team Site/Documents/Project\\"" .... does this mean the issues has been resolved? If so, we can close it. Otherwise, the doc will need to be updated.

**Comment by nmoreau** [comment]
This is a feature request to the feature team.
Tagging @yiwenwang-ms

**Comment by yiwenwang-ms** [comment]
Ack
