### ISSUE TITLE
Page indicates that $expand Odata is supported... but is it?

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-docs#12001]
Hi guys, 

I wanted to query Teams channels with expanded team members (otherwise I'm looping through each channel and doing an additional request per channel to get team members (public channels share a member list with the parent team - so that's not so bad, but private channels are a subset and require additional querying). Consider if there are a relatively large number of channels in play to iterate. 

The page suggests that $expand is supported- however I don't see anything that expands on the Channel entity. Am I misunderstanding something? When using the expand odata param I'm seeing;

> The query specified in the URI is not valid. Query option 'Expand' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings. 

This is the same for members, messages & Tabs - which would make me wonder if there really is anything that can be expanded? 

Ultimately, it would be ideal if, given a TeamId - I could query all the channels which I am a member of (that is channels that are public or channels that are private and I am a member). Currently, I am iterating through each channel and querying 
    `Teams/[TeamId]/Channels`

then from those results, doing another query for 
    `Teams[team.Id]/Channels/[channelId]/members`

which... really isn't efficient.

would be great if my use case were supported. Thanks, 
Alex.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3980610-a5dc-7b2a-43a2-27def95a2ece
* Version Independent ID: fe27e8cc-9e04-9184-dd8d-36990e4d7064
* Content: [List channels - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AlexSapple** [comment]
Whilst not entirely connected, there is also the following issue; 

`Teams[team.Id]/Channels/[channelId]/members`

cannot use select against the userId field - despite the Odata type showing it's a `aadUserConversationMember` you cannot select this field, because.. casting...

`Parsing OData Select and Expand failed: Could not find a property named 'userId' on type 'microsoft.graph.conversationMember'`

OData support in these API's very poor - would be such an improvement if more consistency could be achieved on Odata params.

**Comment by RamaMohanaChary** [comment]
Hi @AlexSapple, 

We are investigating on this, will get back to you soon.

**Comment by Wajeed-msft** [comment]
@AlexSapple - Query option 'Expand' is not supported. We will update the documentation.

**Comment by AlexSapple** [comment]
thanks @Wajeed-msft - that's a shame, but ok. I'll close this ticket.
