### ISSUE TITLE
What are the string options for activity and availability props?

### ISSUE THREAD

**Issue by cagrimunyas** [microsoftgraph/microsoft-graph-docs#12028]
No distinct values for Activity and availability are provided in the documentation. The only reference is: https://docs.microsoft.com/en-us/microsoftteams/presence-admins  but doesn't include the strings that will be returned by the api call. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bbc3b83-e470-a8b8-3c5b-2bd9dab05482
* Version Independent ID: 4d94466a-1d49-c36f-da1d-50d24f5c0661
* Content: [presence resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/presence.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @elvinyang-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by elvinyang-msft** [comment]
Please refer to the [presence API](https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-1.0) documentation for the list of supported `activity` and `availability` values:
