### ISSUE TITLE
Create item fails

### ISSUE THREAD

**Issue by kotpal** [microsoftgraph/microsoft-graph-docs#12047]
```
{
    "properties":  {
                       "additionalData":  {
                                              "priority":  "1",
                                              "ticketTitle":  "Some title",
                                              "assignee":  "someone@somewhere.com"
                                          }
                   },
    "acl":  [
                {
                    "accessType":  "grant",
                    "identitySource":  "external",
                    "value":  "somevalue",
                    "type":  "User"
                },
                {
                    "accessType":  "deny",
                    "identitySource":  "external",
                    "value":  "someothervalue",
                    "type":  "User"
                }
            ],
    "content":  {
                    "value":  "Some value",
                    "type":  "text"
                },
    "@odata.type":  "microsoft.graph.externalItem"
}
2021-03-19 18:19:18.901 Exception:
2021-03-19 18:19:18.906 Message: The remote server returned an error: (400) Bad Request.
2021-03-19 18:19:18.912 Code: BadRequest
2021-03-19 18:19:18.915 Description: Bad Request
2021-03-19 18:19:18.918         Response: 2021-03-19 18:19:18.927       {
2021-03-19 18:19:18.931   "error": {
2021-03-19 18:19:18.934     "code": "InvalidRequest",
2021-03-19 18:19:18.942     "message": "The request is malformed or incorrect.",
2021-03-19 18:19:18.948     "innerError": {
2021-03-19 18:19:18.955       "code": "DeserializationError",
2021-03-19 18:19:18.964       "message": "The given untyped value '{\"priority\":\"1\",\"ticketTitle\":\"Some title\",\"assignee\":\"someone@somewhere.com\"}' in payload is invalid. Consider using a OData type annotation explicitly.",
2021-03-19 18:19:18.971       "date": "2021-03-20T01:19:18",
2021-03-19 18:19:18.978       "request-id": "cdc79ab9-fd44-43e0-97b6-75333d93cf0d",
2021-03-19 18:19:18.982       "client-request-id": "cdc79ab9-fd44-43e0-97b6-75333d93cf0d"
2021-03-19 18:19:18.987     }
2021-03-19 18:19:18.992   }
2021-03-19 18:19:18.999 }


```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b98ea2e-00f2-d564-495e-8384f320a467
* Version Independent ID: 592026d7-4941-aba1-e64b-6951a0848159
* Content: [Create externalItem - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/externalconnection-put-items.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/externalconnection-put-items.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @snlraju-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by snlraju-msft** [comment]
@kotpal if you have registered 'priority', 'ticketTitle' & 'assignee' during [schema registration](https://docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&tabs=http) then the right way to [ingest content](https://docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&tabs=http) would be:

> "properties":  {
  "priority":  "1",
  "ticketTitle":  "Some title",
  "assignee":  "someone@somewhere.com"
}

Instead if you have registered 'additionaData' as a 'string' property - please ingest the value as an escaped 'string' instead of an object. Let me know if you are still facing issues.

**Comment by kotpal** [comment]
Thank you, @snlraju-msft  

However, the [C# sample](https://docs.microsoft.com/en-us/graph/api/externalconnection-put-items?view=graph-rest-beta&tabs=csharp) uses AdditionalData - and it was very confusing - because the other tabs directly set the new fields in Properties itself. So I thought that is how it is done equivalently in C#

I used PostMan and PowerShell to insert the data. And I was able to do a GET and read them back.

However, I am not getting any results when I use the Graph Search API call:
POST https://graph.microsoft.com/beta/search/query
Request:
```
{
    "requests": [
        {
            "entityTypes": [
                "externalItem"
            ],
            "contentSources": [
                "/external/connections/WestKMConnector"
            ],
            "query": {
                "queryString": "*"
            }
        }
    ]
}
```
Response:
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#microsoft.graph.searchResponse",
    "value": [
        {
            "searchTerms": [],
            "hitsContainers": [
                {
                    "total": 0,
                    "moreResultsAvailable": false
                }
            ]
        }
    ]
}
```

But when I do:
GET https://graph.microsoft.com/beta/external/connections/WestKMConnector/items/ABC1234, I get back:
Response:
```
{
    "@odata.context":  "https://graph.microsoft.com/beta/$metadata#external/connections(\u0027WestKMConnector\u0027)/items/$entity",
    "id":  "ABC1234",
    "acl":  [
                {
                    "type":  "user",
                    "value":  "somevalue",
                    "accessType":  "grant",
                    "identitySource":  "external"
                },
                {
                    "type":  "user",
                    "value":  "someothervalue",
                    "accessType":  "deny",
                    "identitySource":  "external"
                }
            ],
    "properties":  {
                       "priority":  "1",
                       "ticketTitle":  "Some title",
                       "assignee":  "someone@somewhere.com"
                   },
    "content":  {
                    "value":  "Some value",
                    "type":  "text"
                }
}
```

What am I missing?

**Comment by snlraju-msft** [comment]
@kotpal the Microsoft Search query API would return results once you request for at least one 'retrievable' field ([see example](https://docs.microsoft.com/en-us/graph/api/search-query?view=graph-rest-beta&tabs=http#examples)). If you are using an alternate query string (other than *) - you will get results as long as there is a search hit against one of the 'searchable' fields in the connection. Hope this helps!

> {
   "requests":[
      {
         "entityTypes":[
            "externalItem"
         ],
         "contentSources":[
            "/external/connections/MyConnector"
         ],
         "query":{
            "queryString":"*"
         },
         "from":0,
         "size":25,
         "fields":[
            "title",
            "description"
         ]
      }
   ]
}

**Comment by kotpal** [comment]
Thank you, @snlraju-msft I tried that but still no results. ticketTitle is searchable (and I have used title as well - one of it's labels). 

```
$schema = @{
    "baseType" = "microsoft.graph.externalItem"
    "properties" = @(
        @{
            "name" = "ticketTitle"
            "type" = "String"
            "isSearchable" = "true"
            "isRetrievable" = "true"
            "labels" = @("title")
        },
        @{
            "name" = "priority"
            "type" = "String"
            "isQueryable" = "true"
            "isRetrievable" = "true"
            "isSearchable" = "false"
        },
        @{
            "name" = "assignee"
            "type" = "String"
            "isRetrievable" = "true"
        }
    )
}
```
POST https://graph.microsoft.com/beta/search/query
Request:
```
{
    "requests": [
        {
            "entityTypes": [
                "externalItem"
            ],
            "contentSources": [
                "/external/connections/WestKMConnector"
            ],
            "query": {
                "queryString": "*"
            },
            "fields": [
                "ticketTitle"    // I used "title" as well
            ]
        }
    ]
}
```
returns no results
Response:
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#microsoft.graph.searchResponse",
    "value": [
        {
            "searchTerms": [],
            "hitsContainers": [
                {
                    "total": 0,
                    "moreResultsAvailable": false
                }
            ]
        }
    ]
}
```
