### ISSUE TITLE
"The group must have at least one owner, hence this owner cannot be removed"

### ISSUE THREAD

**Issue by giertz** [microsoftgraph/microsoft-graph-docs#12054]
Sometimes when trying to remove a group owner from a group with **multiple owners** the request fails. 

Input:
`DELETE - https://graph.microsoft.com/v1.0/groups/<GROUPID>/owners/<OWNERID>/$ref`

Output: 
```
{
  "error": {
    "code": "Request_BadRequest",
    "message": "The group must have at least one owner, hence this owner cannot be removed.",
    "innerError": {
      "date": "2021-03-22T07:44:43",
      "request-id": "39d60326-04af-40a3-bf38-26ad1520e43c",
      "client-request-id": "39d60326-04af-40a3-bf38-26ad1520e43c"
    }
  }
}
```

Example of a group with two owners against which the request failed: 
![image](https://user-images.githubusercontent.com/17637102/111961432-569fd980-8af1-11eb-9f4e-cc2af5050ee1.png)

Other:
I'm running this via Logic App using using application permission via app registration. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7de0b71f-e448-e714-a1b4-5aa10cb33865
* Version Independent ID: 998646cc-03c6-c069-f096-567b9b021df8
* Content: [Remove owner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @giertz for raising this issue. You can create a group without assigning an owner. In this case, administrators in the Group Administrator role will still be able to manage the group. However, once owners are assigned to a group, the last owner of the group cannot be removed. Please make sure to select another owner before removing the last owner from the group.

Will update the page to indicate this key information. Closing the issue.

**Comment by giertz** [comment]
Im not removing the **last** owner. I am trying to remove 1 out of 2 owners in the group when i get this error.

**Comment by FaithOmbongi** [comment]
I have tested this and as long as they are not the last owner, you should be able to delete them via either the Microsoft Graph API or the Azure portal. Let me investigate further and see what could be your exception. What type of group is the subject group? Have you experienced this in other groups?

**Comment by giertz** [comment]
The issue seems the be sporadic. I'm using Logic App to remove a service account on M365 groups. 
![Capture](https://user-images.githubusercontent.com/17637102/112797589-e43c7580-906b-11eb-864e-eab72d023fc6.PNG)

Success:
![image](https://user-images.githubusercontent.com/17637102/112797703-1221ba00-906c-11eb-9e98-5332b0ac2968.png)

Failure:
![image](https://user-images.githubusercontent.com/17637102/112797769-2cf42e80-906c-11eb-932b-5fba56f5bd1e.png)

Im using application permission with a shared secret:
![image](https://user-images.githubusercontent.com/17637102/112797903-6462db00-906c-11eb-8fc6-a6708408ee38.png)

**Comment by FaithOmbongi** [comment]
Thank you @giertz for your response. 

This seems to be a functionality issue and not docs-related. Unfortunately, this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). I advise that you post your issue there and provide this additional information. There's a team of engineers needs to assist you to troubleshoot and resolve. Closing this issue here for now.
