### ISSUE TITLE
JSON payload example is invalid

### ISSUE THREAD

**Issue by EgorEmeliyanov** [microsoftgraph/microsoft-graph-docs#12077]
The provided JSON payload example is invalid. It won't work with Graph Explorer and won't pass JSONLint validation as single quotes (apostrophes) are not allowed in JSON. Double quotes should be used with string values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90d84542-0c21-4806-4c5b-174e76d2e360
* Version Independent ID: cfc63ae5-4ffc-a4a5-a76b-5c9d15a4358c
* Content: [Write data to an Excel workbook with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/excel-write-to-workbook)
* Content Source: [concepts/excel-write-to-workbook.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/excel-write-to-workbook.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by grangeryy** [comment]
Fixed the issue.
