### ISSUE TITLE
Incorrect Permission Scope

### ISSUE THREAD

**Issue by merill** [microsoftgraph/microsoft-graph-docs#12078]
The GET permission is incorrectly documented as requiring Directory.ReadWrite.All permission. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ed915f-ea7d-7161-d581-7b0e25d69458
* Version Independent ID: afff0011-16ca-2427-8e53-2eb17130356b
* Content: [List featureRolloutPolicies - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/featurerolloutpolicies-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/featurerolloutpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/featurerolloutpolicies-list.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @madhavpatel6
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @merill for raising this issue. Yes, you're right. The _Policy.Read.All_ permission is sufficient for this read operation. I'll raise a PR to fix the permissions table.

**Comment by FaithOmbongi** [comment]
Thank you @merill for raising this issue. I've tested and the documentation is correct. The  LIST operation requires **Directory.ReadWrite.All** permission and doesn't work with **Policy.Read.All** or **Policy.ReadWrite.FeatureRollout** permissions. Though, I think the API should actually support the lesser privileged **Policy.Read*** permissions instead.

I'll raise this issue internally with the product team.
