### ISSUE TITLE
Under what circumstances are ResponseStatus populated?

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-docs#12073]
Hi guys, 

When we look at the CalendarView query - the response status fields against attendees of an event are not populated. When I look at the event via Teams - I can clearly see the response statuses (so I know they are there...) - but from calendar view query they all look like;

![image](https://user-images.githubusercontent.com/30351641/112183898-98667800-8bf6-11eb-942d-88520c360ea9.png)

which is a real shame. Is there any way to get this data?

Is there anything documented to detail when I might expect to have visibility of the response data?

many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8837ed-fee9-835f-c724-88b2cea5688b
* Version Independent ID: cf38a184-7667-1039-c0b2-d1c6f2bcc95a
* Content: [responseStatus resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/responsestatus.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AlexSapple** [comment]
any update on this question? thanks.

**Comment by AlexSapple** [comment]
Hi @Harini84 - is there any additional documentation or feedback regarding this ticket - It would be really appreciated, thank you.

**Comment by Harini84** [comment]
@AlexSapple 
Could not repro the issue. Except for organizer for whom the status will be none, all the attendees do have the response value populated. Example:

            "attendees": [
                {
                    "type": "required",
                    "status": {
                        "response": "none",
                        "time": "0001-01-01T00:00:00Z"
                    },
                    "emailAddress": {
                        "name": " ",
                        "address": "  "
                    }
                },
                {
                    "type": "required",
                    "status": {
                        "response": "notResponded",
                        "time": "0001-01-01T00:00:00Z"
                    },
                    "emailAddress": {
                        "name": "  ",
                        "address": " "
                    }
                },
                {
                    "type": "optional",
                    "status": {
                        "response": "declined",
                        "time": "0001-01-01T00:00:00Z"
                    },
                    "emailAddress": {
                        "name": "  ",
                        "address": " "
                    }
                },

**Comment by AlexSapple** [comment]
ok thanks @Harini84 - let me check again.

**Comment by AlexSapple** [comment]
Hi @Harini84 - on closer inspection, I'm thinking that this may be related to how an event is set up. If I create an event in MS Teams and send out invitations, upon accepting the invitations - the status looks to be set properly, however - when I create an event from my custom app, and send out invitations, upon accepting, and subsequently querying the calendar view, the response status is not captured. I can see this in MS Teams as well which again does not reflect the acceptance status if setting up the meeting from my custom app. 

So, now I need to try and understand what is the difference between how the event is set up when done from my custom app - that uses the following; 
```
 Event teamsMeetingEvent = await _graphServiceClient.Me.Events.Request().AddAsync(new Event
            {
                Start = DateTimeTimeZone.FromDateTime(meeting.StartDateTime),
                End = DateTimeTimeZone.FromDateTime(meeting.EndDateTime),
                Subject = meeting.Subject,
                Body = GetMeetingBody(meeting.Description, guestLink),
                IsOnlineMeeting = true,
                AllowNewTimeProposals = false,
                OnlineMeetingProvider = OnlineMeetingProviderType.TeamsForBusiness,
                Attendees = GetAttendees(meeting.Participants)
            });
```
where GetAtendees() is; 

```
attendees.Add(new Attendee
                {
                    EmailAddress = new EmailAddress
                    {
                        Address = participant.GuestEmailAddress,
                        Name = participant.GuestEmailAddress
                    },
                    Type = participant.Type == ParticipantType.Mandatory ? AttendeeType.Required : AttendeeType.Optional
                });
```

**Comment by AlexSapple** [comment]
ok, this functionality isn't properly documented and doesn't make sense without some explanation - please can we clarify how the response statuses work - 

In some cases I have seen responses returned when I am NOT the organizer of the meeting and in some cases I only see my own response. The organizer seems to be able to see everyone's responses. 

What is the expected behavior for organizer/none organizer participants? I am utterly lost.

**Comment by AlexSapple** [comment]
ok wait, and again we come full circle - seems like there is a time sync involved (running the same query against the same event a while later DID include the statuses where previously is DID NOT include the statuses)

I still think this needs much better documentation

**Comment by Harini84** [comment]
Response status documentation is updated inhttps://docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0

"_The response type. Possible values are: none, organizer, tentativelyAccepted, accepted, declined, notResponded.

To differentiate between none and notResponded:

none – from organizer's perspective. This value is used when the status of an attendee/participant is reported to the organizer of a meeting.

notResponded – from attendde's perspective. Indicates the attendee has not responded to the meeting request.

Clients can treat notResponded == none.

As an example, if attendee Alex hasn't responded to a meeting request, getting Alex' response status for that event in Alex' calendar returns notResponded. Getting Alex' response from the calendar of any other attendee or the organizer's returns none. Getting the organizer's response for the event in anybody's calendar also returns none._"
