### ISSUE TITLE
From/EmailAddress/Address not working as expected

### ISSUE THREAD

**Issue by adrichema** [microsoftgraph/microsoft-graph-docs#121]
I have the following issue when querying for email using the v1.0 or beta Graph API.

When I try to filter on the following property From/EmailAddress/Name+eq+'xxx xxxx' it works perfectly. The returned result set, displays the expected email address in the from object:  xxxx@mydomain.onmicrosoft.com

When I try to filter on the following property From/EmailAddress/Address+eq+'xxxx@mydomain.onmicrosoft.com' I get no results at all, although I am sure the given email address is correct.

This problem only happens with email addresses from the same domain. Filtering for external email addresses works as expected.

**Comment by JaspervdK** [comment]
Hi, we're still experiencing this issue. Any progress on a fix?

**Comment by JaspervdK** [comment]
Hi, this is still an issue for me. I fixed it temporarily by using  (From/EmailAddress/Address eq 'xxxx@mydomain.onmicrosoft.com' or startswith(From/EmailAddress/Address,'xxxx@mydomain.onmicrosoft.com'))

**Comment by ArunMSFT** [comment]
Thanks for looping me in @jthake-msft . We'll investigate this.

**Comment by forrestedw** [comment]
Just checking in to say that this is still an issue. I'm using @JaspervdK 's work around, but would be good to see this fixed as the documentation is currently misleading.

**Comment by isvargasmsft** [comment]
Hello, 

My deepest apologies for the time taken to address this issue. 

I tried to reproduce the error from my end, but it is working with the following command:
`GET https://graph.microsoft.com/v1.0/me/messages?$filter=(from/emailAddress/address) eq 'name@mydomain.onmicrosoft.com'`

It does show the information as expected. Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at Microsoft Q&A: [Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).

Kind regards, 

Isaac Vargas
