### ISSUE TITLE
Update to include all available properties

### ISSUE THREAD

**Issue by Peter-Ross-C** [microsoftgraph/microsoft-graph-docs#12101]
Hi, it would be beneficial to include a list of all available properties that can be fetched using the $select query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97f543bc-6546-d808-8214-a9e5f632825b
* Version Independent ID: a0f6ebb9-99cd-3ffc-e0e4-af523296f657
* Content: [Get group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Peter-Ross-C for raising your issue.
To know properties that support `$select` OData query parameter, kindly refer to the [properties table](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#properties) in the **Group** resource page. 

No updates identified for the **Get group** API page. Closing this issue.
