### ISSUE TITLE
It's not comparisonValue, but detectionValue when looking at result.

### ISSUE THREAD

**Issue by PascalVerbruggen** [microsoftgraph/microsoft-graph-docs#12116]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8578eb55-d5c2-dfdf-89ef-c7e92b1f79d6
* Version Independent ID: a17aa404-3ae0-8954-cd26-1bd177d186ed
* Content: [win32LobAppRegistryRule resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-win32lobappregistryrule?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/intune-apps-win32lobappregistryrule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-apps-win32lobappregistryrule.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Hi @triplanedave, has this issue been resolved yet? Thanks

**Comment by triplanedave** [comment]
Sorry, I realized that my response from before was incomplete.  I get the same result when outputting detection rules for registry.  My guess is that the docs were originally published with the old schema value, then the backend changed, but the docs didn't refresh.  I'll file a bug for it, but the correct return property is detectionValue.
