### ISSUE TITLE
[Doc-enhancement] [Doc-enhancement] Create online meeting with APPLICATION PERMISSIONS

### ISSUE THREAD

**Issue by SubbaReddi** [microsoftgraph/microsoft-graph-docs#12135]
When trying to create online meeting with application permissions, facing 403 forbidden. Issue get fixed by creating application access policy.

It's worth to mention that if application access policy is not applied, will face 403 forbidden error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @jsandoval-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @SubbaReddi thanks for the suggestion! I'll create a work item in our backlog to improve the 4xx error messages.
