### ISSUE TITLE
I need a sample app to send activity notification to user.

### ISSUE THREAD

**Issue by jonathanhotono** [microsoftgraph/microsoft-graph-docs#12144]
I need a sample app manifest that does this without having to specify the static tabs, etc.

I assume that, once the app is added into the teams I can straightaway call that api from an external service like azure function to provide a notification to a particular user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef120b3-03b9-cca1-9479-05720e6fd9ef
* Version Independent ID: 0cf32a73-043a-6b34-f71c-a8d3bd410bf7
* Content: [Send activity feed notifications to users in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications)
* Content Source: [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-send-activityfeednotifications.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Right now you need atleast one other component to be present in the app for notifications to work. A static tab might be a good choice if you app is mostly background.
