### ISSUE TITLE
UserAssignLicenseParameterSet not found as an import under assignLicense

### ISSUE THREAD

**Issue by sanasalim** [microsoftgraph/microsoft-graph-docs#12154]
[Enter feedback here]

Dear Team,

When I try to import UserAssignLicenseParameterSet, listed under Java source code, it does show up as an available import, under v1.0 Microsoft Graph API. 
Can someone please help me with this ?

Thanks in advance !

Best Regards,
Sana Salim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b679a04b-f0bd-0ae2-023f-22ddcaf616c4
* Version Independent ID: 9be46203-2d58-0662-6d2c-69cee14769be
* Content: [assignLicense - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-assignlicense?view=graph-rest-1.0&tabs=java#example-1)
* Content Source: [api-reference/v1.0/api/user-assignlicense.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-assignlicense.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @sanasalim for raising your issue. Can you please confirm that your import statement is as in the attached screenshot?

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/14026935/115060756-ecf8cc80-9ef0-11eb-8c8f-a1908b11e8d1.png)

**Comment by sanasalim** [comment]
Dear @FaithOmbongi, the above import does not appear as an option.

![image](https://user-images.githubusercontent.com/24691182/115275407-0cd2ff00-a142-11eb-8dfa-210d7d1b7665.png)

I am using the Maven dependency microsoft-graph.version 2.10.0

**Comment by FaithOmbongi** [comment]
Hello @baywet: kindly assist to look into and resolve this customer issue. Thanks.

**Comment by baywet** [comment]
@sanasalim Please upgrade your project to version 3.2.0 of the SDK and try again, you should then see the different packages and classes you're trying to access.

**Comment by FaithOmbongi** [comment]
@sanasalim : Kindly confirm that the upgrade resolved your issue.

**Comment by sanasalim** [comment]
@FaithOmbongi, I confirm that upgrading to version 3.2.0 resolved the issue.
Many thanks for your support !

**Comment by baywet** [comment]
thanks for confirming this. closing.

**Comment by FaithOmbongi** [comment]
Thanks @sanasalim for confirming. Thank you @baywet for helping resolve this.
