### ISSUE TITLE
https://microsoftgraph.uservoice.com is deactivated

### ISSUE THREAD

**Issue by snebjorn** [microsoftgraph/microsoft-graph-docs#12171]
From the issue guidelines

> # Important!
> If you have suggestions or feedback on Microsoft Graph, please submit this at [Microsoft Graph Uservoice](https://microsoftgraph.uservoice.com/).

But User Voice site have been deactivated.

![image](https://user-images.githubusercontent.com/1266245/113144294-6031eb80-922d-11eb-84ce-aea62295fd42.png)

**Comment by snebjorn** [comment]
@abheek-das sorry to tag you here, but can you forward this to someone that can do something about this?

**Comment by jasonjoh** [comment]
Thanks for reporting @snebjorn. I've removed the link to UserVoice from our issue template. Please watch out for an announcement on the Microsoft Graph blog in next few weeks for a new experience to submit feature requests.

**Comment by snebjorn** [comment]
@jasonjoh Do you know what will happen to the feedback from user voice? I was tracking a few issues on it
