### ISSUE TITLE
Return only users, not shared mailboxes

### ISSUE THREAD

**Issue by ufeg02** [microsoftgraph/microsoft-graph-docs#12183]
I want to receive a list of 'real' users only. The API now returns also shared mailboxes etc. Is it possible to filter out the shared mailboxes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabdb652-eb03-bae6-fa99-66d71fbdd044
* Version Independent ID: 7f5744b6-6770-586e-217c-4b7ac7657051
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by michevnew** [comment]
You are confusing object types here. The /users endpoint returns data from Azure AD, whereas mailbox data is held within ExODS (no Graph API endpoints for that yet). Both user mailboxes and shared mailboxes have "real" user object associated with them, and as far as Azure AD is concerned, there is no difference between those. Same applies for room/equipment mailboxes btw.

**Comment by FaithOmbongi** [comment]
Thank you @ufeg02 for raising your issue. And thank you @michevnew for your response.

This API returns only a list of users. We haven't had an experience where it returns shared mailboxes. Could you share a screenshot of what you're getting so we can identify your issue?

**Comment by FaithOmbongi** [comment]
Closing this issue due to non-response.
