### ISSUE TITLE
publisherName is only returned via /beta, not /v1.0

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#12202]
I realize this will eventually be available for the /v1.0 endpoint as well, but currently it doesn't seem to be the case, so the example output provided is wrong/misleading. Can you please update it or add some note?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a1dcc-0e0d-e5ba-8fa3-ad0289803a52
* Version Independent ID: bccef64c-675b-364e-30f6-5c1310fef8bd
* Content: [List servicePrincipals - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/serviceprincipal-list.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @michevnew for catching this. I'll raise a PR to update the page. Closing this issue.
