### ISSUE TITLE
Update user photo error

### ISSUE THREAD

**Issue by EugeneKulikovskiy** [microsoftgraph/microsoft-graph-docs#12219]
Hello

We use Azure B2C tenant and manually create users (members). 
Try to upload image using this request using v1.0 graph api. Use application permissions User.ReadWrite.All. Admin consent has done.

PUT /users/{id}/photo/$value 

get error

{
  "error": {
    "code": "UnknownError",
    "message": "{\"error\":{\"code\":\"OrganizationFromTenantGuidNotFound\",\"message\":\"The tenant for tenant guid '<tenant guid>' does not exist.\",\"innerError\":{\"oAuthEventOperationId\":\"6c5273d1-de55-4c1a-b089-2e7d76396355\",\"oAuthEventcV\":\"UFKNPbwUrU2iQ8h44rHgRA.1.1\",\"errorUrl\":\"https://aka.ms/autherrors#error-InvalidTenant\",\"requestId\":\"c99b3dc4-8158-473b-8721-7ad3aa63961e\",\"date\":\"2021-04-06T20:45:51\"}}}",
    "innerError": {
      "date": "2021-04-06T20:45:51",
      "request-id": "c99b3dc4-8158-473b-8721-7ad3aa63961e",
      "client-request-id": "c99b3dc4-8158-473b-8721-7ad3aa63961e"
    }
  }
}

When photo uploads to user through azure portal, the get method returns photo successfully.

GET /users/{id}/photo/$value 

What is the reason of this error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe020479-a6f3-1dbf-2b2b-3dbd50e74d92
* Version Independent ID: 6da3efa4-e243-1d29-65a2-8ce172dc9cf3
* Content: [Update profilephoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dmitryelmanov** [comment]
Hello
We have the same issue.
We use Graph API for user management. And if we try to upload a photo for the user we just created, it fails.

Steps via Postman:
1. Create a user `POST /users` with API **v1.0**
2. Upload a photo for the user `PUT /users/{id | userPrincipalName}/photo/$value` with **beta** version of API
It fails with 
```"error": {
        "code": "UnknownError",
        "message": "{\r\n  \"ErrorCode\": \"ErrorConsumerShardProvisioningTenantIsNotConsumer\",\r\n  \"Message\": \"Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileNotFoundException' was thrown.\",\r\n  \"Target\": null,\r\n  \"Details\": null,\r\n  \"InnerError\": null,\r\n  \"InstanceAnnotations\": []\r\n}",
        "innerError": {
            "date": "2021-06-16T13:17:27",
            "request-id": "abce36c0-8819-41d5-ab46-cc29d0f8c6e0",
            "client-request-id": "abce36c0-8819-41d5-ab46-cc29d0f8c6e0"
        }
    }```
3. You can repeat the previous request and the result would be the same for some time. Or you can just wait a minute.
4. Repeat the request from Step 2 and now it will fail with 
```"error": {
        "code": "ErrorStoreServerUnavailable",
        "message": "Exception of type 'Microsoft.Fast.Profile.Core.Exception.ProfileStorageUnavailableException' was thrown.",
        "innerError": {
            "date": "2021-06-16T13:18:36",
            "request-id": "dd1b5591-80ef-4add-95ef-fb451dcb2b0c",
            "client-request-id": "dd1b5591-80ef-4add-95ef-fb451dcb2b0c"
        }
    }```
4. Repeat the request once again and it will be ok.
5. You can repeat the request many times and it will always be ok.

Using Portal everything is fine.

Any ideas on how to upload a photo for the user we just created?
