### ISSUE TITLE
Service Principal appRoleAssignedTo endpoint is not returning all assigned objects

### ISSUE THREAD

**Issue by adriano-kaiser** [microsoftgraph/microsoft-graph-docs#12243]
If a Service Principal has Managed Identities App Role assignments, this endpoint is omitting them in the response:
https://graph.microsoft.com/v1.0/serviceprincipals/{SP_ObjectId}/appRoleAssignedTo

However if one includes magic query parameter top=999 all entries are listed:
https://graph.microsoft.com/v1.0/serviceprincipals/{SP_ObjectId}/appRoleAssignedTo?$top=999

Only top=999 will work. top=99 for example will not work. There is some weird magic logic behind that endpoint.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 585bb8e4-a9bb-f727-a5eb-e9c3244ec3a2
* Version Independent ID: b66f0561-4c0f-9ded-4734-482328d99eb0
* Content: [List appRoleAssignments granted for a service principal - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @adriano-kaiser for raising this issue and apologies for the delayed response.

Unfortunately, this forum is not monitored for functionality issues but issues like this are monitored at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-groups.html). Kindly post this question there to get troubleshooting help from our engineers.

No immediate updates identified for the page but the page will be updated when possible. Closing this issue for now.

**Comment by PontusEkengren** [comment]
Also had this issue, worked around for now with top999... Until those run out.
Thank you @adriano-kaiser
