### ISSUE TITLE
"Edit" button on docs.microsoft.com links to wrong branch on Github

### ISSUE THREAD

**Issue by ascott18** [microsoftgraph/microsoft-graph-docs#12247]
The "Edit" button on the top right corner of the docs site links to `https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-getmembergroups.md`. Note that this links to the `master` branch. However, `master` is not the default branch of this repo - `main` is. 

This is leading contributors to edit the wrong files, and should be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview?view=graph-rest-1.0)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ascott18** [comment]
I tried to report this as a general, standalone issue but got shot down. https://github.com/microsoftgraph/microsoft-graph-docs/issues/12246

**Comment by jasonjoh** [comment]
This should be fixed now.
