### ISSUE TITLE
Instructions for env variable download

### ISSUE THREAD

**Issue by adsfjhbsdjfhbdsjfhb** [microsoftgraph/microsoft-graph-docs#12242]
This page should show instructions on how the environment variables can be downloaded from the PostMan collection, it would save people time if they can just export and import it rather than have to manually create variables themselves.
This used to be available in the previous version of this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman?source=docs)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adsfjhbsdjfhbdsjfhb** [comment]
Yes, I know, that’s why I wrote in.

Forgot to mention that there are environment variables in the main collection that aren’t even in the environment you have defined, {{userid}} and {{username}} are in there as well.

The old environment used to have them, but the new one only has 3 variables for some reason.

Please include all variable references listed in the collection in the environment as well.

Thanks.

Daniel Berghian​
Senior Support Engineer
The Granary, Abbey Mill Business Park,  Guildford,      Surrey  .       GU7 2QW
T       +44 (0)1483 239254<tel:+44%20(0)1483%20239254>
[www.unily.com]<https://www.unily.com/>

**Comment by jthake-msft** [comment]
The additional environment variables get created as you run particular requests. For instance if you run Get Profile, it stores the userid from the response.
The new instructions are awaiting approval https://github.com/microsoftgraph/microsoft-graph-docs/pull/12245

**Comment by lramosvea** [comment]
Closing this issue since the doc has been updated already.
