### ISSUE TITLE
Sites.Selected - Upload is not working

### ISSUE THREAD

**Issue by krzysztofrosol** [microsoftgraph/microsoft-graph-docs#12253]
We get accessDenied when trying to upload a file. (UploadAsync C# / REST API / Official MS libraries)
If we switch to Sites.ReadWrite.All or  Files.ReadWrite.All it works.

Permissions are granted for an application for specific site with role: "write".

CreateUploadSession - works
UploadAsync - is not - access denied

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 20413e04-bb90-3095-1c5a-6f1bb2b56a4e
* Version Independent ID: 9b2c3897-9c52-8562-9502-e3037c271f76
* Content: [Get permission - Microsoft Graph v1.0](https://docs.microsoft.com/pl-pl/graph/api/site-get-permission?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/site-get-permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/site-get-permission.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @barrysh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ekdegerman** [comment]
We have the same issue. Only for the resumable uploads of larger files through the upload session URL, smaller file uploads work as expected.

**Comment by BarryShehadeh** [comment]
There was an issue with Sites.Selected not being honored in some cases, but I believe it has been fixed. 
@krzysztofrosol/ @ekdegerman Are you still having an issue with it?

**Comment by BarryShehadeh** [comment]
Closing issue as it should be fixed.
