### ISSUE TITLE
404 for federated chat conversation that exists when using List chats

### ISSUE THREAD

**Issue by ShaneOss** [microsoftgraph/microsoft-graph-docs#12259]
Getting a 404 not found for a chat I know exists when using GET https://graph.microsoft.com/beta/chats or via GET https://graph.microsoft.com/beta/chats/19:federateduserID_myID@fed.unq.gbl.spaces
It is a federated conversation. 
However, If I call messages from the conversation ID GET https://graph.microsoft.com/beta/chats/19:federateduserid_myid@fed.unq.gbl.spaces/messages
I get all the messages associated with the conversation as expected. The chat conversation just isn't shown in the list of my chats using GET https://graph.microsoft.com/beta/chats.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79531fbc-dd22-cf80-c97c-746f7dcab790
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Can you share client-request-Id response header value and timestamp?

**Comment by ShaneOss** [comment]
Failure (on chatid):
{
    "error": {
        "code": "NotFound",
        "message": "Not Found",
        "innerError": {
            "date": "2021-04-11T10:40:35",
            "request-id": "64539a38-0488-4973-944f-c8d8e9fa0818",
            "client-request-id": "ffc05d42-500d-edeb-a424-4f0a3f2eb834"
        }
    }
}

Success (call on chatid/messages):
{
    "client-request-id": "ca659993-5652-916d-0b9f-4d2c1cd45d4a",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "77b54d0b-851c-4755-9364-95edd31b678f"
}

**Comment by RamjotSingh** [comment]
This is expected. The user making the call is on SFB. So doesn't exactly have view of the conversation. We are working on a feature where you might be able to fetch the chat using Get Chat, but List user chats will not return the chat because the chat is not in Teams for the user who is making the call.

**Comment by ShaneOss** [comment]
Thanks for the info.

**Comment by RamjotSingh** [comment]
SFB interop threads do not get migrated to normal teams to teams conversations. So the above condition applies.
