### ISSUE TITLE
"chats" segment is only available as a top-level entity set in the V1 metadata

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-docs#12274]
Same issue exists on this page as #11425 and #12162

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1155f8-abe0-902a-2f91-8cd2fe00c567
* Version Independent ID: a88f1a96-46b9-2742-8f19-b55d25dce815
* Content: [List members of a chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @bhartono
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by pixieofhugs** [comment]
@Lauragra Can we get this page taken down?

**Comment by Lauragra** [comment]
@bhartono , can you please look into this issue? Thanks.

**Comment by lramosvea** [comment]
Hi @bhartono any update on this?

**Comment by isvargasmsft** [comment]
Syncing with the team as Benny is no longer in this role.

**Comment by RamjotSingh** [comment]
This was fixed a long while back. Here is the current schema from v1

![image](https://user-images.githubusercontent.com/13517857/134549817-13728dd1-1489-470a-948b-93f07bfa9346.png)
