### ISSUE TITLE
How to set property 'Allow members to upload custom apps'

### ISSUE THREAD

**Issue by FabianMelzer** [microsoftgraph/microsoft-graph-docs#12284]
Dear all, thanks for your documentation. However I could not find an option to enable/disable the teams property 'Allow members to upload custom apps' via Graph API or Powershell. Thank you in advance for your answer!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3ad374-9441-28ec-2aab-2d051a65514f
* Version Independent ID: 69f0743c-f292-a657-75cd-c6123f97d465
* Content: [teamMemberSettings resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/teammembersettings?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/teammembersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/teammembersettings.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jagadeesh-MSFT** [comment]
Hi @FabianMelzer, we can use allowAddRemoveApps property for members can add and remove apps.

**Comment by FabianMelzer** [comment]
Thanks for your answer @Jagadeesh-MSFT. 

The 'allowAddRemoveApps' property will (de-)/activate the setting 'Allow members to add and remove apps'. However, I am looking for an option to change the setting 'Allow members to upload custom apps' (see attached screenshot)
![Teams settings](https://user-images.githubusercontent.com/35842019/114687744-54a5f080-9d14-11eb-97aa-541ac48c020d.JPG)

**Comment by Jagadeesh-MSFT** [comment]
Hi @FabianMelzer, we are working practically on this, we will update you soon.

**Comment by FabianMelzer** [comment]
Thanks a lot!

**Comment by Jagadeesh-MSFT** [comment]
Hi @FabianMelzer, You can set "Allow members to upload custom apps" from the Teams UI by choosing "Manage Team". Currently, we do not have an option to do this from powershell/Graph Api.

**Comment by Wajeed-msft** [comment]
Closing this issue, please reopen if you still have any queries.
