### ISSUE TITLE
Example 1: Add a member to a channel

### ISSUE THREAD

**Issue by ashleywb** [microsoftgraph/microsoft-graph-docs#12298]
In the example given below
POST https://graph.microsoft.com/v1.0/teams/ece6f0a1-7ca4-498b-be79-edf6c8fc4d82/channels/19%3A56eb04e133944cf69e603c5dac2d292e%40thread.skype/members
Content-type: application/json
Content-length: 100

{
    "@odata.type": "#microsoft.graph.aadUserConversationMember",
    "roles": ["owner"],
    "user@odata.bind": "https://graph.microsoft.com/v1.0/users('8b081ef6-4792-4def-b2c9-c363a1bf41d5')"
}
This should be 
POST https://graph.microsoft.com/v1.0/teams/ece6f0a1-7ca4-498b-be79-edf6c8fc4d82/channels/19%3A56eb04e133944cf69e603c5dac2d292e%40thread.skype/members
Content-type: application/json
Content-length: 100

{
    "@odata.type": "#microsoft.graph.aadUserConversationMember",
    **"roles": [],**
    "user@odata.bind": "https://graph.microsoft.com/v1.0/users('8b081ef6-4792-4def-b2c9-c363a1bf41d5')"
}
Also, when using this endpoint it appears to add the member (when checking channel members via this endpoint https://docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&tabs=http)

When checking the user in the Microsoft Team ui, it does not appear. When you try and add the user in Microsoft Teams
![image](https://user-images.githubusercontent.com/9212081/114698907-87051d00-9d17-11eb-8cbc-43d49f088822.png)
![image](https://user-images.githubusercontent.com/9212081/114699012-a8660900-9d17-11eb-8009-72ccf24dbf4a.png)
Does anything else need to be added for it to be displayed in the UI correctly?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79f9efdd-1dbf-e2af-6cf1-810d46ef92dc
* Version Independent ID: 4ae0f300-aa78-54c6-f9c0-cc286e756cf9
* Content: [Add member to channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @laujan
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@ashleywb-We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@ashleywb -We are unable to repro the scenario. Could you please check it once?
Microsoft Teams Version 1.5.00.5254 (64-bit)
