### ISSUE TITLE
Non-Logged in user calendar events

### ISSUE THREAD

**Issue by dang2906** [microsoftgraph/microsoft-graph-docs#123]
Is it possible to access other user's calendars? Using the examples at [http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_post_events](url) and [http://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_list_events](url), i have attempted to access my colleagues calendar using the user principal name as suggested but i always get an 'Access Denied' error code. I have a requirement where an entry must be created in a non-logged in user's outlook calendar on a particular event. I understand that this may not be possible due to privacy and security concerns, but would it be possible to give the application particular permissions in order for this to be allowed? I have given the application in question all permissions for Microsoft Graph in Microsoft Azure Active Directory with no luck. Any help in this would be greatly appreciated. Thanks,

**Comment by dang2906** [comment]
I am attempting a work around creating an event in logged in user's calendar and inviting the other users as attendees, however, when i make the request i get a 'Bad Request' error because the Microsoft.Graph.AttendeeType.Optional enum is not translated properly and it sends it through as a numeric value of 1 when it requires a string value of "Optional".

**Comment by dang2906** [comment]
I have found a workaround for the enum issue. The full details can be found at [http://stackoverflow.com/questions/35478581/microsoft-graph-attendeetype-not-enumerated-correctly](url) however, i believe this needs addressing as it appears to be quite a major oversight when the coding library forces the use of an enum but the api requires a string value.

**Comment by Harini84** [comment]
Kindly check calendar sharing:
https://docs.microsoft.com/en-us/graph/outlook-share-or-delegate-calendar?tabs=http

and calendar permissions:
https://docs.microsoft.com/en-us/graph/api/resources/calendarpermission?view=graph-rest-1.0

to access other user's calendars
