### ISSUE TITLE
Is it still in preview? 

### ISSUE THREAD

**Issue by AkashAKale** [microsoftgraph/microsoft-graph-docs#12306]
[Enter feedback here]
When will this be available as V1.0 as we see this is still in (Preview).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a0e7861-2853-262b-e5e2-05d74a11b748
* Version Independent ID: d83704be-60f2-a1ff-e5af-ec6120148603
* Content: [Customize the profile card using the profile API in Microsoft Graph (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/add-properties-profilecard#feedback)
* Content Source: [concepts/add-properties-profilecard.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/add-properties-profilecard.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @PollyNincevic
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PollyNincevic** [comment]
@AkashAKale thank you for the feedback! The feature is still in preview. We are currently working on expanding the list of allowed properties and will make the feature generally available once the underlying APIs are ready.
