### ISSUE TITLE
Update employeeorgdata property

### ISSUE THREAD

**Issue by joergrenn** [microsoftgraph/microsoft-graph-docs#12308]
Hello,
apparently on a user there is an employeeorgdata property.
https://docs.microsoft.com/en-us/graph/api/resources/employeeorgdata?view=graph-rest-1.0
How can I modify this property via ms graph?
Is it also possible to access this propery via pwsh?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc8115d-af6e-dd2a-cddc-8e8fe0eb8744
* Version Independent ID: 16a1f548-f808-6f35-fa3e-b41872f89742
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jpettere** [comment]
Hi @joergrenn. You can update 'employeeOrgData' by making a PATCH API request and including the employeeOrgData payload. (see attached screenshots)

This property is also accessible via PowerShell. 
<img width="712" alt="MicrosoftTeams-image (5)" src="https://user-images.githubusercontent.com/16470165/119405687-83f63880-bc96-11eb-8344-cea54cddf92a.png">
<img width="722" alt="MicrosoftTeams-image (6)" src="https://user-images.githubusercontent.com/16470165/119405698-8789bf80-bc96-11eb-9ace-4f12ef54e846.png">

**Comment by jpettere** [comment]
I mean the Graph API Powershell module. Since it's built directly on top of MS Graph you should be able to retrieve any user attributes. I don't believe there is any AzureAD module cmdlet that'll return employeeOrgData.
