### ISSUE TITLE
Error when trying to create subscription to security/alerts

### ISSUE THREAD

**Issue by Shuna322** [microsoftgraph/microsoft-graph-docs#12319]
Request body example:
```
{
    "changeType": "updated",
    "notificationUrl": "{{PUBLIC_URL}}/notification",
    "resource": "security/alerts?$filter=status eq 'New'",
    "expirationDateTime":"2021-04-15T12:20:45.9356913Z",
    "clientState": ""
}
```

The resource was taken from an example in documentation.

Error:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "2021-04-15T08:33:45",
            "request-id": "6f79aa5a-4ee0-445e-9c59-46815bd8da82",
            "client-request-id": "6f79aa5a-4ee0-445e-9c59-46815bd8da82"
        }
    }
}
```

Trying to modify resource and remove the filter, new resource:` "resource": "security/alerts"`

Error:
```
{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: ]",
        "innerError": {
            "date": "2021-04-15T08:42:41",
            "request-id": "0d44e419-7309-4254-85e7-0c2c4b493890",
            "client-request-id": "0d44e419-7309-4254-85e7-0c2c4b493890"
        }
    }
}
```

Application permissions:
![image](https://user-images.githubusercontent.com/32617699/114841110-2857a600-9de0-11eb-81b0-aeea6b0e9551.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a2554f-8319-2bee-dc3d-c56e53c8878d
* Version Independent ID: 3d68d537-d522-be77-edae-723949fef25e
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @Jumaodhiss
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Shuna322** [comment]
Hi, Any update on this?

**Comment by Jumaodhiss** [comment]
@Shuna322 please try issuing this


{
    "changeType": "updated",
    "notificationUrl": "{{PUBLIC_URL}}/notification",
    "resource": "security/alerts?$filter=status eq 'newAlert'",
    "expirationDateTime":"2021-04-15T12:20:45.9356913Z",
    "clientState": ""
}

Then let us know if it works for you

**Comment by Shuna322** [comment]
@Jumaodhiss Issue still present 

{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: ]",
        "innerError": {
            "date": "2021-04-28T09:30:56",
            "request-id": "fe2c19ea-f25a-41ec-8dc2-be9da7648685",
            "client-request-id": "fe2c19ea-f25a-41ec-8dc2-be9da7648685"
        }
    }
}

Also, it's probably good to mention that I received a request
![image](https://user-images.githubusercontent.com/32617699/116381710-d3735100-a81d-11eb-85a2-23819e13a439.png)

**Comment by Jumaodhiss** [comment]
I am trying to reproduce this but am failing

do you mind running it on graph explorer https://developer.microsoft.com/en-us/graph/graph-explorer

**Comment by Shuna322** [comment]
I'm subscribing using an application with a token and my user does not have the necessary permitions.

**Comment by Jumaodhiss** [comment]
Closing this but you can reopen if you are still facing the same issue
