### ISSUE TITLE
Directory.ReadWriteAdvanced.All permission does not exist and needs to be removed from this topic

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#12323]
Directory.ReadWriteAdvanced.All permission does not exist and needs to be removed from this topic

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f6c98c-785d-7d33-5a27-4c509efdfd1c
* Version Independent ID: 25193182-fe60-5de7-297f-25aa1b8ed287
* Content: [user: activateServicePlan - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-activateserviceplan?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-activateserviceplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-activateserviceplan.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dkershaw10 for catching this. I've raised a PR to fix the permissions reference.
