### ISSUE TITLE
$search and $filter are not honored on list service principals

### ISSUE THREAD

**Issue by Nandeeshswami** [microsoftgraph/microsoft-graph-docs#12338]
[Enter feedback here]

We tried using $filter, it throws a 400 response. We get the same response with ConsistencyLevel:Eventual

https://graph.microsoft.com/v1.0/servicePrincipals/<objectId>/appRoleAssignedTo?$filter=startswith(principalType, 'ServicePrincipal')

{
    "error": {
        "code": "Request_BadRequest",
        "message": "Invalid filter clause principalType: System.String",
        "innerError": {
            "date": "2021-04-09T21:05:45",
            "request-id": "2e512125-7e43-4cf7-988b-b58f2c157518",
            "client-request-id": "c61e4ac1-1d30-14bc-3627-e9cebbf8df59"
        }
    }
    
    With Search, the issue is that if we try to search by let's say a User and then we try a search with ServicePrincipal, both give us the same O/p.
    
    Below are 2 diff queries, which give the same output.
    https://graph.microsoft.com/v1.0/servicePrincipals/<Object ID/>/appRoleAssignedTo?$search="principalType: ServicePrincipal"
https://graph.microsoft.com/v1.0/servicePrincipals/<Object ID/>/appRoleAssignedTo?$search="principalType: User"
    
    One more example where I tried to search for Managed Identity and Application.
    https://graph.microsoft.com/v1.0/servicePrincipals?$search=("ServicePrincipal=Managed Identity")
    https://graph.microsoft.com/v1.0/servicePrincipals?$search=("ServicePrincipal=Application")
    
    Adding ConsistenyLevel:Eventual did not help too.
    As per the doc these are supported please help clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a1dcc-0e0d-e5ba-8fa3-ad0289803a52
* Version Independent ID: bccef64c-675b-364e-30f6-5c1310fef8bd
* Content: [List servicePrincipals - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-list.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Nandeeshswami for raising this issue. For properties of directory objects, `$search` is supported only on **displayName** and **description** properties. servicePrincipals object has both properties.

`$filter `on **servicePrincipals** is not supported on **principalType** but is supported on **accountEnabled**, **displayName**, **id**, **servicePrincipalName**, **servicePrincipalType** among other properties. We're working to publish supported for all query parameters on these properties.
