### ISSUE TITLE
graph api test

### ISSUE THREAD

**Issue by chaos-ui** [microsoftgraph/microsoft-graph-docs#12357]
[test]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a79889c-633f-7c18-105c-905dd3382b08
* Version Independent ID: 3ed67119-eda9-0d29-fd74-d504e88af367
* Content: [Privileged Identity Management - Azure resources - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-resources?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/privilegedidentitymanagement-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/privilegedidentitymanagement-resources.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @chaos-ui for testing. Yes, it works. ☺
Closing the issue.
