### ISSUE TITLE
Channel Message Delta Error

### ISSUE THREAD

**Issue by ihar512** [microsoftgraph/microsoft-graph-docs#12353]
I follow the example provided to get delta channel message, but I am getting this error from VS Code,
"'IChannelMessagesCollectionRequestBuilder' does not contain a definition for 'Delta' and no accessible extension method 'Delta' accepting a first argument of type 'IChannelMessagesCollectionRequestBuilder' could be found"

Any idea?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d8e638-3695-72a4-fa08-2622d0281d42
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessage: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
SDK might be lagging behind. Is it possible for you to make the call directly over HTTP protocol?

**Comment by ihar512** [comment]
I didn't try to make the call directly over HTTP. Upgraded Microsoft.Graph from version 3.22.0 to 3.29.0, .Delta is now accessible.
