### ISSUE TITLE
Unsupported mailNickname property

### ISSUE THREAD

**Issue by guillaumemeyer** [microsoftgraph/microsoft-graph-docs#12421]
I saw the mention "Known issue: this property is currently ignored.", but as the `mailNickname` property is not supported and doesn't work, you should remove it from the documentation as it's really misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c92597-b0ca-9dcc-1c46-27da5659f622
* Version Independent ID: 4a00105a-9208-9197-8231-ba1353224fd6
* Content: [Clone a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-clone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-clone.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by guillaumemeyer** [comment]
BTW this known issue is there for years now...

**Comment by Jagadeesh-MSFT** [comment]
Hi @guillaumemeyer, we are checking with our internal team, if required we will update the document.

**Comment by Jagadeesh-MSFT** [comment]
Hi @guillaumemeyer, we have to use mailNickname property even if it should ignore, since mailNickname is mandatory property.

**Comment by Nikitha-MSFT** [comment]
@guillaumemeyer - If you are still facing the issue please reopen the ticket, as of now we are closing the issue
