### ISSUE TITLE
HTTP 500 using filter parameter

### ISSUE THREAD

**Issue by nickp85** [microsoftgraph/microsoft-graph-docs#12462]
This API doesn't appear to work using the "startswith" filter. It returns an HTTP 500 response. Removing the filter returns all the results.

https://graph.microsoft.com/beta/deviceManagement/deviceConfigurationRestrictedAppsViolations?$filter=startswith(deviceConfigurationName,'US')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233698d8-561a-613f-6f9e-1257392dffdc
* Version Independent ID: a6a8534c-943d-913b-a7b4-f3dc1cd554d6
* Content: [List restrictedAppsViolations - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-restrictedappsviolation-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-deviceconfig-restrictedappsviolation-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-deviceconfig-restrictedappsviolation-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Does 'contains' work instead?

https://graph.microsoft.com/beta/deviceManagement/deviceConfigurationRestrictedAppsViolations?$filter=contains(deviceConfigurationName,'US')

**Comment by nickp85** [comment]
Contains doesn’t work for the filter I’m trying to run. Ended up querying
without a filter and handle the results in PowerShell after the fact.
Heavier on the API though to do it this way.

**Comment by triplanedave** [comment]
Ok, thanks nickp85.  I'll file a suggestion for our engineers to consider adding contains/startswith support for this.

**Comment by nickp85** [comment]
The general graph API page says that startswith is generally supported
across the API. Curious why not here.

**Comment by triplanedave** [comment]
We often need code to handle page sizes and ordering for filters and especially for large returned data sets.
