### ISSUE TITLE
Resource roles for AAD groups are returned with empty IDs (empty GUID value)

### ISSUE THREAD

**Issue by sergeyz7** [microsoftgraph/microsoft-graph-docs#12484]
This seems to be consistent and regardless of whether the role has active assignments or not. Consequently, it makes it very challenging to identify access package(s) in which a particular AAD group resource is present.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de280587-2cf8-01f9-d84c-b50312f2ad42
* Version Independent ID: 3a658916-b47f-7a90-792b-abd376e56aa9
* Content: [List accessPackageResourceRoles - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackagecatalog-list-accesspackageresourceroles?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accesspackagecatalog-list-accesspackageresourceroles.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Thanks, I see that behavior in my test tenant as well; we'll take a look.

**Comment by FaithOmbongi** [comment]
Hi @markwahl-msft , any update on this issue?

**Comment by sergeyz7** [comment]
This issue is still in place and unfortunately has now (recently, cannot pinpoint the exact date) extended to other resource types - particularly SharePoint sites. Any update on what is happening would be very much appreciated @markwahl-msft - if in the meantime anyone here can suggest a workaround for identifying an access package from a site URL/ID, that would be greatly appreciated.

**Comment by FaithOmbongi** [comment]
> oint sites. Any update on what is happening would be very much appreciated @markwahl-msft - if in the meantime anyone here can suggest a workaround for identifying an access package from a site URL/ID, that would be greatly appreciated.

Hi @markwahl-msft, Please help to confirm whether this issue has been resolved.

**Comment by FaithOmbongi** [comment]
Because this is a functionality issue, I'm closing this issue here and tracking it via engineering bug 2201083
