### ISSUE TITLE
Get list of meeting Ids - API endpoint

### ISSUE THREAD

**Issue by GalNakash-RecoLabs** [microsoftgraph/microsoft-graph-docs#12579]
I need to provide a meeting ID to get details of an online meeting. It seems like there is no API endpoint to get all meetings ids and I can only get a meetingId if I created it with the graph API.

I need an API like `/list-meetings` to get all meeting IDs of a specific user/for all org. 
Can you help with it? 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f89278-6b03-e6e4-66a3-2127a11750fe
* Version Independent ID: f6f92861-6d72-2260-2277-d963793fbce2
* Content: [Get onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @jsandoval-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @GalNakash-RecoLabs thanks for the feedback. I understand it's a pain point that we don't have list API in Graph online meetings. I'll definitely work with our PM to make sure this request gets tracked properly.

**Comment by frankpeng7** [comment]
@GalNakash-RecoLabs I'm revisiting this issue. Seems like there are multiple asks in this one:

> I need to provide a meeting ID to get details of an online meeting. It seems like there is no API endpoint to get all meetings ids and I can only get a meetingId if I created it with the graph API.

Besides meetingId, you can look up a meeting by `joinWebUrl`. Here's an [example from our docs](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http#example-3-retrieve-an-online-meeting-by-joinweburl). You should be able to have the `joinWebUrl` even if the meeting was created outside of Graph (e.g. Teams, Outlook...)

> I need an API like /list-meetings to get all meeting IDs of a specific user/for all org.

As replied in the previous message, we will have this feature request tracked in our backlog.
