### ISSUE TITLE
Documentation refers to non-existent group properties

### ISSUE THREAD

**Issue by adrian-corston-unify** [microsoftgraph/microsoft-graph-docs#12606]
The 'Response' paragraph on this page refers to hideFromAddressLists and hideFromOutlookClients properties, neither of which appear to be valid.  An attempt to update either property results in a 400 Bad Request API response code.  The same behaviour occurs on both v1.0 and beta endpoints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f4256b9-1abf-c4a3-34d3-315911ef422b
* Version Independent ID: b2a352f9-d11a-2487-4a47-9b238f083565
* Content: [Update group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-update.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adrian-corston-unify** [comment]
See also https://github.com/microsoftgraph/microsoft-graph-docs/issues/8872

**Comment by adrian-corston-unify** [comment]
Also down the rabbit-hole found this: https://stackoverflow.com/questions/59160848/errorgroupsaccessdenied-when-setting-hidefromaddresslists-or-hidefromoutlookclie
Turns out those properties work for Delegated auth.  The documentation could be updated to mention this.

**Comment by FaithOmbongi** [comment]
Thank you @adrian-corston-unify or raising this issue.

**hideFromOutlookClients** and **hideFromAddressLists** are Exchange properties and they cannot be updated in the same request as core group properties hence the **400 Bad request** error. I'll raise a PR to indicate this in the document.
