### ISSUE TITLE
List detectedApps does not indicate a way to only list detected apps of a particular managed device

### ISSUE THREAD

**Issue by hdavidzhu** [microsoftgraph/microsoft-graph-docs#12631]
https://docs.microsoft.com/answers/answers/59125/view.html seems to indicate some hidden APIs for listing detected apps for a single managed device. Do these endpoints exist? I can't find official documentation for this. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a461acc-e772-1fea-abc9-0de75dd3f6b4
* Version Independent ID: 8e2c3b6c-13fc-13a2-ae84-da6deab09058
* Content: [List detectedApps - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-detectedapp-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-detectedapp-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-devices-detectedapp-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
This is the documentation for the detected apps API: https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-detectedapp?view=graph-rest-1.0

**Comment by hdavidzhu** [comment]
@triplanedave While that documentation has section under Relationships:

![image](https://user-images.githubusercontent.com/3756871/117685584-adce3c00-b17b-11eb-8d02-6e788ed66d07.png)

It says nothing about how I can list all the detected apps for a certain managed device. I do see it going the other direction though: https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-get?view=graph-rest-1.0

> GET /deviceManagement/detectedApps/{detectedAppId}/managedDevices/{managedDeviceId}

Is there an endpoint that lets me get all the detected apps for a particular managed device?

(If possible, please let me also re-open this issue; I can also file a new issue and link this. Thanks!)

**Comment by triplanedave** [comment]
https://graph.microsoft.com/beta/deviceManagement/manageddevices('<insert_your_deviceID_here>')?$expand=detectedApps

**Comment by hdavidzhu** [comment]
Ah I see. Thanks for sharing this example!
