### ISSUE TITLE
Missing information about $top max number on calendarView endpoint

### ISSUE THREAD

**Issue by odin-delrio** [microsoftgraph/microsoft-graph-docs#12653]
Hello!
According to [this doc](https://docs.microsoft.com/en-us/graph/query-parameters#top-parameter), the limits on the "top" can vary depending on the API. 
> The minimum value of $top is 1 and the maximum depends on the corresponding API.

But looking at the linked `calendar-list-calendarview` doc, I can't see any information about that, I just made some calls with absurdly high numbers (1 million and so on) and the API does not fail, but I'm not sure if the graph API is just ignoring my top value there or not.

So, my question is, is there any section in the docs that talks about the limits on that specific API?

If not, could you tell me if there is any limit in the number of results I can get in the `calendarView` endpoint? and, which is the default?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f75563-9954-d973-95e4-5ac854590445
* Version Independent ID: 9c25ea4e-22ca-0ccf-46fb-c965070ffcf8
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/calendar-list-calendarview.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
As documented here: https://docs.microsoft.com/en-in/archive/blogs/exchangedev/throttling-coming-to-outlook-api-and-microsoft-graph
**CalendarView** with $top has min as 1 and max as 1000

@isvargasmsft  
Please update the documentation.
