### ISSUE TITLE
Unable to POST to teams installedApps endpoint

### ISSUE THREAD

**Issue by micaiahwallace** [microsoftgraph/microsoft-graph-docs#12651]
Hello, I am having the same issue as #12199 

I am sending a POST to `https://graph.microsoft.com/v1.0/teams/[team-uuid]/installedApps`

With the json body:
```
{
    "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/[team-app-id]"
}
````

It is also receiving a `400 bad request` error every time. I am using application permissions with the client id and secret for authentication.

I have also verified in multiple locations that I am using the correct ID for the application, including the endpoint `https://graph.microsoft.com/v1.0/appCatalogs/teamsApps`

I'm not sure what else to try to get this to work, is it the authentication mechanism I am using that needs to be changed?

Any ideas would be greatly appreciated!

Thanks,
Micaiah

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dc9bc4-04c6-8f44-2d84-2a15c4a1682d
* Version Independent ID: 4531b625-756e-acf9-d3f4-a47f47142dd3
* Content: [Add app to team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post-installedapps?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-post-installedapps.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Sridevi-MSFT** [comment]
@micaiahwallace - To add an app to team you need to have `TeamsAppInstallation.ReadWriteForTeam, Group.ReadWrite.All, Directory.ReadWrite.All` permissions. Could you please try adding these permissions and let us know if the issue still persists.

**Comment by micaiahwallace** [comment]
@Sridevi-MSFT Thanks for looking into this, I did have those permissions on my local setup I just forgot to add them to the graph explorer. After adding them to the graph explorer I still get the same error message unfortunately.

**Comment by micaiahwallace** [comment]
@Sridevi-MSFT I found some more debugging information as well. It appears that this issue is in part isolated to the combination of the app I am installing and that I'm trying to install to a team. Here is what I could successfully do:

- Install the app (Smart Connect for Jira) to a specific teams channel (POST /chats/CHAT_ID/installedApps)
- Install a different app to the team I was initially trying (POST /teams/TEAM_ID/installedApps)

Let me know if you have any other ideas!

Thanks,
Micaiah

**Comment by Sridevi-MSFT** [comment]
@micaiahwallace - Could you please confirm have you added the application to app catalog.

**Comment by micaiahwallace** [comment]
@Sridevi-MSFT - The application has already been installed on a number of different teams in our organization. I have not directly used an app catalog, but after researching and setting it up on our account, it looks like its made to be used with sharepoint / office and directed at custom applications, which doesn't apply to us. We are installing a 3rd party app that's already hosted on the teams app store (which is enabled on the teams admin portal as well). Here's the link to the app: [https://appsource.microsoft.com/en-cy/product/office/wa200002055?tab=overview](https://appsource.microsoft.com/en-cy/product/office/wa200002055?tab=overview)

Thanks,
Micaiah

**Comment by Sridevi-MSFT** [comment]
@micaiahwallace - I am unable to repro your issue.
1. List the apps in app catalog using GET https://graph.microsoft.com/v1.0/appCatalogs/teamsApps
2. Copy the respective app id from the response body. 
3. POST to https://graph.microsoft.com/v1.0/teams/[team-uuid]/installedApps
   With the json body:
   {
    "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/[team-app-id]"
   }
Replace [team-app-id] with app id which you got from Step2.

Please check if your doing the same.

**Comment by micaiahwallace** [comment]
Hi @Sridevi-MSFT 
![image](https://user-images.githubusercontent.com/2124688/118995960-c80ad580-b944-11eb-8969-4690b742f9b7.png)

I have the correct app from the catalog, I would like to ask if you are able to install that same exact app into any of your teams with the API, because it seems to be isolated to that specific app, as I can install any other app using this method into my teams.

However, I am able to install the app into an individual channel by using `POST https://graph.microsoft.com/v1.0/chats/[channel-uuid]/installedApps` and I just realized that it seems to solve my problem for what I need right now. I also am realizing that when you install the app on the Teams App, it asks for a specific channel in the installation popup which makes me wonder if that's a requirement for the install. Either way I will close this issue for now as I have a workaround to the issue.

Thanks for the help!
Micaiah
