### ISSUE TITLE
Misleading information about using the refresh token

### ISSUE THREAD

**Issue by zak905** [microsoftgraph/microsoft-graph-docs#12663]
In the "Use the refresh token to get a new access token", it seems like the refresh token request can be successful even without specifying the scopes as a parameter. I suggest that the scopes parameter should be made optional (in case a subset of scopes is requested instead of the original scopes request at the first authorize request) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-user.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @zak905 for raising this issue.
To request and get the refresh token, you must first specify the `offline_access` scope in the **scope** parameter, so scope can't be optional in this case. Hope this clarifies the issue.

**Comment by zak905** [comment]
I am not sure my input was clear enough, I am gonna try to put it differently: I am talking about the refresh request mentionned [here](https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#5-use-the-refresh-token-to-get-a-new-access-token) which is basically about getting a new a access token using an existing refresh token. It works without scopes, you are mentionning that scopes are required: 

![docs microsoft com_en-us_graph_auth-v2-user_context=graph%2Fapi%2F1 0 view=graph-rest-1 0 (3)](https://user-images.githubusercontent.com/6265563/121377160-6b4a7b80-c942-11eb-80eb-c60f0b216af1.png)

the `offline_access` is only needed the first time you request a token. This is about requesting a new access token from a refresh token. It works without scopes. I am already working with it in my app without scope parameter. The scopes should be `optional` if not removed at all from the refresh request. 

Up to you if you want to keep your docs accurate.

**Comment by FaithOmbongi** [comment]
Thank you for the clarification @zak905 , I believe I've understood your point of view.
Let me check with the OAuth team to understand the intent of **scope** being **Required** for this step when we're using the refresh token to get a new access token (and update the page if it can be **Optional**).
