### ISSUE TITLE
It seems that delegatedPermissionsIds are documented incorrectly

### ISSUE THREAD

**Issue by Damag3d** [microsoftgraph/microsoft-graph-docs#12675]
[Enter feedback here]
CLI returns error
`Bad Request({"error":{"code":"InvalidValue","message":"Property api.preAuthorizedApplications.delegatedPermissionIds has a Permission Id that cannot be found in the AppPermissions sets.","details":[{"target":"api.preAuthorizedApplications.delegatedPermissionIds","code":"InvalidValue"}],`

When we add it manually via portal, manifest uses PermissionsIds, instead of delegatedPermissionsIds. 

```
"preAuthorizedApplications": [
		{
			"appId": "*****GUID",
			"permissionIds": [
				"*****GUID"
			]
		},
		{
			"appId": "*****GUID",
			"permissionIds": [
				"*****GUID"
			]
		}
	],
```

Please review.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f005940-5216-b9bb-f565-c6f60fab201b
* Version Independent ID: 817e0407-5470-fdfd-793f-2db1730295c4
* Content: [preAuthorizedApplication resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/preauthorizedapplication?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/preauthorizedapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/preauthorizedapplication.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thanks @Damag3d for raising this issue and my apologies for the delayed response. Yes, you're right. The schema for this resource lists the property as **permissionIds**. I've raised a PR to fix the article.
