### ISSUE TITLE
report - UPN and Display Name format

### ISSUE THREAD

**Issue by sonofthemom** [microsoftgraph/microsoft-graph-docs#12676]
Hi There,

Which format you are using for "User Principal Name" or "Display Name"?
I tried to search return values in my directory but I didn't find any users (GUID ? XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX both lower and upper case). This question is relative to all reports I suppose.
Or how I can link users from /reports/getOffice365ActiveUserDetail to real users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f13e30f-2918-9ff1-d7dc-fe574220ff0d
* Version Independent ID: 102504f4-38ce-19dd-368f-e91816eeb540
* Content: [reportRoot: getOffice365ActiveUserDetail - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-getoffice365activeuserdetail?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/reportroot-getoffice365activeuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-getoffice365activeuserdetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @sarahwxy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sonofthemom** [comment]
Any suggestions?

**Comment by stredoux** [comment]
https://graph.microsoft.com/beta/reports/getOffice365ActiveUserDetail(period='D180')?$format=application/json

Normally we got bat the UPN and DisplayName
result = 
[0]
@odata.type: "#microsoft.graph.office365ActiveUserDetail"
reportRefreshDate: "2021-09-02"
userPrincipalName: "C57165363DD1A5AE880A2FE5208291CD"
displayName: "577E905F157ABECE95F454AD0B3058CF"
isDeleted: False
deletedDate: null
hasExchangeLicense: False
hasOneDriveLicense: False
hasSharePointLicense: False
hasSkypeForBusinessLicense: False
hasYammerLicense: False
hasTeamsLicense: False
exchangeLastActivityDate: null
oneDriveLastActivityDate: null
sharePointLastActivityDate: null
skypeForBusinessLastActivityDate: null
yammerLastActivityDate: null
teamsLastActivityDate: null
exchangeLicenseAssignDate: null
oneDriveLicenseAssignDate: null
sharePointLicenseAssignDate: null
skypeForBusinessLicenseAssignDate: null
yammerLicenseAssignDate: null
teamsLicenseAssignDate: null
assignedProducts: [ ]
