### ISSUE TITLE
API reports succeeded but does not respond asap - "not found"

### ISSUE THREAD

**Issue by ofunk** [microsoftgraph/microsoft-graph-docs#12672]
If a team gets created and the async get reports succeeded in the first second the graph api responds with not found

not easy to resolve as I was expecting that once I get a succeeded -- that graph is reachable.

Same for for "groups" -- after creation of team and awainting the succeeded -the groupID is still not reachable for a few seconds. whole idea of async tracking is to expect consistent behaviour - right?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c049b616-d611-c25f-38ac-d7f27702c330
* Version Independent ID: c83604a3-b769-19d4-fee1-9f3090e8f3cc
* Content: [teamsAsyncOperation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-1.0&source=docs)
* Content Source: [api-reference/v1.0/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/teamsasyncoperation.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Mamatha-MSFT** [comment]
Hi @ofunk - Could you please share the code snippets.

**Comment by ofunk** [comment]
Hi.

The batch code is fairly simple:

  1.  Post team
  2.  1.0/teams('{teamsID}')/operations('{opsID}
     *       "operationType": "createTeam",
     *       "createdDateTime": "2021-05-09T12:47:13.7174478Z",
     *       "status": "succeeded",
     *       "lastActionDateTime": "2021-05-09T12:47:13.7174478Z",
  3.  Expected response is good but– just a “patch group” or a list channel fails for sometimes 1-2 sec after the “succeeded”

If you want to do a “batch” script this is difficult
Most useful trace seems a “HAR” file – less the code snippets

Let me know your thoughts.
oliver

Von: Mamatha-MSFT ***@***.***>
Gesendet: Montag, 17. Mai 2021 14:10
An: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Oliver Funk ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoftgraph/microsoft-graph-docs] API reports succeeded but does not respond asap - "not found" (#12672)


Hi @ofunk<https://github.com/ofunk> - Could you please share the code snippets.

**Comment by Mamatha-MSFT** [comment]
Hi @ofunk - I am unable to repro the issue. After creating team and getting succeed status from teamsAsyncOperation resource type and then I am able to run get team request with 200 status code.

**Comment by ofunk** [comment]
Hi. All I can do is send a trace from the browser log

I am doing a loop until succeed and then next step. So manually reproducing without a batch + loop will not work – the delay is in the range of 1sec I guess

Let me know if this is an option?

Von: Mamatha-MSFT ***@***.***>
Gesendet: Dienstag, 18. Mai 2021 20:03
An: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Oliver Funk ***@***.***>; Mention ***@***.***>
Betreff: Re: [microsoftgraph/microsoft-graph-docs] API reports succeeded but does not respond asap - "not found" (#12672)


Hi @ofunk<https://github.com/ofunk> - I am unable to repro the issue. After creating team and getting succeed status from teamsAsyncOperation resource type and then I am able to run get team request with 200 status code.

**Comment by Mamatha-MSFT** [comment]
Hi @ofunk - I have reproduced the same scenario that has been provided by you but it's working fine at my end. 
Could you please share the request and response for failure case.
