### ISSUE TITLE
query resourceAppId's and resourceAccess's displayName

### ISSUE THREAD

**Issue by lordisp** [microsoftgraph/microsoft-graph-docs#12693]
I like to create an overview of api permissions assigned to applications. In the manifest are the resourceAccess ids stored. How can I get the associated displayname using the graph api?

```
"requiredResourceAccess": [
    {
      "resourceAppId": "00000003-0000-0000-c000-000000000000", <- I know, this is graph but but I like to query it somehow
      "resourceAccess": [
        {
          "id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",  <- this maybe "user.read" or something but I like to query it somehow
          "type": "Scope"
        },
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d74f81-566f-f497-75f1-61ea6d0d9f5c
* Version Independent ID: 5ad4a6e4-b716-9a8f-adce-a7768f31e088
* Content: [resourceAccess resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/resourceaccess?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/resourceaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/resourceaccess.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lordisp** [comment]
I found to lookup this with the sp route `GET /servicePrincipals/{id}`
> ```
> "requiredResourceAccess": [
>     {
>       "resourceAppId": "00000003-0000-0000-c000-000000000000", <- I know, this is graph but but I like to query it somehow
>       "resourceAccess": [
>         {
> ```

I'm still missing a way to resolve the `resourceAccess` Ids
> ```
>    "resourceAccess": [
>       {
>          "id": "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
>          "type": "Scope"
> ```

**Comment by psignoret** [comment]
Apologies for the late response here. Adding an answer, in case someone comes across this in the future.

Given a `requiredResourceAccess` list, to fill in the resource app display name and details for the app roles or delegated permissions:

1. Retrieve the resource app's service principal by app ID:

   ```http
   GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appId eq '{resourceAppId}'
   ```

2. For each of the required accesses for that resource app, retrieve the matching value from the  **oauth2PermissionScopes** collection (if `"type": "scope"`) or **appRoles** collections (if `"type": "role"`) **servicePrincipal** object for the **servicePrincipal**.

The OData query as you proposed is not supported, but retrieving the full **servicePrincipal** object should give you all the data you need.

The `$expand` parameter _is_ supported on both `appRoleAssignedTo` (which is what you'd do if you're querying the resource service principal) and `appRoleAssignments` (which is what you'd do if you're querying the client service principal), but the number of returned assignments is fairly limited, so you won't really gain anything over querying the full list.

**Comment by lordisp** [comment]
yeah, I wanted to avoid a forEach loop. Anyhow, thanks for your response.

**Comment by psignoret** [comment]
You'll probably still need to iterate over appIds and permission IDs in your code, but you don't necessarily need to make one request per resource app. You can retrieve up to 15 resource service principals (by appId) in one request:

```none
GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appId eq '{appid-1}' or appId eq '{appid-2}' or ...
```

And you can also use a [`$batch` request](https://docs.microsoft.com/graph/json-batching) to make multiple requests in one go.

**Comment by lordisp** [comment]
> And you can also use a [`$batch` request](https://docs.microsoft.com/graph/json-batching) to make multiple requests in one go.

that's very nice! Wasn't aware of `batching` `request` capabilities. Thank's for this heads up
