### ISSUE TITLE
Membership roles not documented on this page. `member` role not returned in `GET /teams/{team-id}/members`

### ISSUE THREAD

**Issue by zemuldo** [microsoftgraph/microsoft-graph-docs#12713]
[Enter feedback here]

The doc does to state the roles `owner` and `member` values of the [conversationMember resource](https://docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0) .

 Also calling [GET /teams/{team-id}/members](https://docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http) members with role 'member' returns no roles in the response.

#### Request
```shell
GET https://graph.microsoft.com/v1.0/teams/1022dda8-2473-4e29-99c9-d03daf7364f7/members?$select=roles
```

#### Response
```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('1022dda8-2473-4e29-99c9-d03daf7364f7')/members(roles)",
    "@odata.count": 3,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "roles": []
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "roles": [
                "owner"
            ]
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "roles": [
                "owner"
            ]
        }
    ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b15adcff-0536-6702-7cb3-ad64ba8a1846
* Version Independent ID: 770ecfc4-e9a5-cafc-e170-e281a60c1cd1
* Content: [conversationMember resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/conversationmember.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @laujan
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jagadeesh-MSFT** [comment]
Hi @zemuldo, thanks for the insights, our document team will work on it.

**Comment by JakeMoe** [comment]
I also came here to report the documentation doesn't state what the valid values are.  I presume it only accepts '', 'member', or 'owner', with an empty string defaulting to 'member'?  I'm writing PowerShell scripts that sync users to their Teams, and only managers get Owner, so I need to know what the correct value is to put in for the Role property of the BodyParameter hashtable I build.  If the current behaviour is by design and intended to stay that way, then it'd be good for the documentation of [conversationmember](https://docs.microsoft.com/en-au/graph/api/resources/conversationMember) to state this.

**Comment by v-chetsh** [comment]
@AkJo - Can you please help us here to update the documentation?

**Comment by AkJo** [comment]
By default, everyone has a 'member' role. The "roles" property only contains additional qualifiers when relevant - for example, if the member has 'owner' privileges, then the roles property would contain "owner" as one of the values.

Similarly, if the member was a guest, then the roles property would contain "guest" as one of the values.

A basic member should not have any values specified in the "roles" property.

**Comment by JakeMoe** [comment]
Thanks for the clarification.  Hopefully the documentation has been / will be updated to reflect this and make it clear for the next person.  :-)
