### ISSUE TITLE
Question concerning the 8 months limit for the delta messages endpoint

### ISSUE THREAD

**Issue by daspionzor** [microsoftgraph/microsoft-graph-docs#12732]
I saw that this was added to the endpoint

> Note: Delta will only return messages within the last eight months. You can use GET /teams/{team-id}/channels/{channel-id}/messages to retrieve older messages.

I tried to use the delta endpoint without a delta token and I was able to retrieve messages that are older than 8 months. So my question is, is the 8 months limit only applied when using the endpoint with a delta token?

I'm asking this since the delta endpoint returns messages in order from the oldest to the most recent (the messages endpoint is the other way around) which is much more convenient for my use case and we might always use it if the 8 months limit is only when using an actual token.

The $orderby OData parameter could be very useful for us if this could be added.

Maybe the messages order for both endpoints could be stated in the documentation as well since we had to test both endpoints to see that the order was not the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d8e638-3695-72a4-fa08-2622d0281d42
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessage: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Only Delta has a limit of 8 months. /messages will go through the entire history. Delta goes from start to end, while /messages uses the client-like view (end to start).

**Comment by daspionzor** [comment]
> Only Delta has a limit of 8 months.

In any case or just when using a delta token? Because, as explained in my original post, I was able to retrieve message from 1+ year ago using the /delta endpoint (without a token). So I would assume that the 8 months limit is only when using a delta token, I just want to make sure here.

> /messages will go through the entire history. Delta goes from start to end, while /messages uses the client-like view (end to start).

Could the order of the endpoints at least be stated in the documentation?

**Comment by RamjotSingh** [comment]
If you use /delta at the end, we only support 8 months (in some cases you might get more, however the system officially only supports 8 months).

Regarding documenting order, we can take that up.
