### ISSUE TITLE
How do I create an online meeting in a channel (similar to "Meet now")?

### ISSUE THREAD

**Issue by fvanheeswijk** [microsoftgraph/microsoft-graph-docs#12765]
I'm trying to replicate the "Meet now" button in a channel by creating an online meeting and linking it to a channel.
I'm using delegated permissions and when I omit the chatInfo field everything is working fine, however I want to be able to see that there is an active meeting in the channel.
I've tried various things and googled a lot but it seems like I need to use the channel id as threadId in the chatInfo object, however I cannot find any documentation on how exactly to use it.

The result I'm getting is a 400 Bad Request with as only information `An error has occurred.`, which is not exactly helpful.

So.. how do I use it? How do I create an online meeting in a channel?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @jsandoval-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mohkhodeer** [comment]
How do I create an online meeting in a channel? Highly needed

**Comment by frankpeng7** [comment]
Hi @fvanheeswijk @mohkhodeer thank you guys for your interest in trying out the API! Unfortunately, Graph OnlineMeeting APIs don't support creating adhoc(meet now) meetings yet. Before we do, the workaround I could suggest is to create a scheduled meeting in the channel. I'll definitely ask our PM to put a feature request in our backlog for this. Please reply to this thread if you need more help :)

**Comment by mkhribech** [comment]
@frankchen76 added to the backlog

**Comment by mohkhodeer** [comment]
Hi @frankpeng7 
Thank you for your support
But I think that **"create a scheduled meeting in the channel"** is available only in Beta API version

POST https://graph.microsoft.com/beta/me/onlineMeetings
Content-Type: application/json

{
  "startDateTime":"2019-07-12T14:30:34.2444915-07:00",
  "endDateTime":"2019-07-12T15:00:34.2464912-07:00",
  "subject":"User meeting in Microsoft Teams channel.",
  "chatInfo": {
    "threadId":"19%3A3b52398f3c524556894b776357c1dd79%40thread.skype"
  }
}

**Comment by frankpeng7** [comment]
@mkhribech can you respond to the ask to release creating channel meeting in v1?

**Comment by mkhribech** [comment]
@mohkhodeer as far as V1 we are in our sprint planning and we will targeting this feature by Q3
