### ISSUE TITLE
Permissions incorrect

### ISSUE THREAD

**Issue by gomes53** [microsoftgraph/microsoft-graph-docs#12786]
We had customers complaining that they can't test the BETA API.
There is a permission missing from the list on the BETA API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabdb652-eb03-bae6-fa99-66d71fbdd044
* Version Independent ID: 7f5744b6-6770-586e-217c-4b7ac7657051
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @gomes53 for raising your issue. Could you provide more details of the examples they are unable to test so we can verify?

**Comment by gomes53** [comment]
on page https://docs.microsoft.com/ko-kr/graph/api/user-list?view=graph-rest-beta&tabs=http example 3:
using the following endpoint: https://graph.microsoft.com/beta/users?$select=displayName,userPrincipalName,signInActivity

1- using V1.0 is not supposed to display signInActivity (only on beta)
2- if you try to run anything on beta you receive error 403 and on the modify permissions view its missing AuditLog.Read.All

Thank you

**Comment by FaithOmbongi** [comment]
Thank you @gomes53 for confirming the problem query. The **signInActivity** property can only be queried when you have a P1/P2 license and assigned the AuditLog.Read.All permission. My apologies, the information might not have been explicitly stated on the property's description before you raised this issue.

Just in case this requirement might be missed, I'll raise a PR to add a note to the example.
