### ISSUE TITLE
Filter for GET /domains doesn't work, unlike what documentation says

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/microsoft-graph-docs#12782]
[Documentation](https://docs.microsoft.com/en-us/graph/api/domain-list?view=graph-rest-beta&tabs=http#optional-query-parameters) says:

![image](https://user-images.githubusercontent.com/6450056/118829202-322c6780-b8be-11eb-8e67-ed1cb3043789.png)

I first tried list domains by Microsoft.Graph module (against BETA API): ```Get-MgDomain -Filter "IsInitial eq true"```.
Also tried [Microsoft Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer/preview): ```https://graph.microsoft.com/beta/domains?$filter=IsInitial eq true```.

* Tried both with camel case and pascal case for ```IsInitial```.

Both gave error: 

* Code: ```Request_UnsupportedQuery```
* Message: ```Filtered searches against this resource are not supported.```.

**Maybe add to the documentation what properties can actually be used with ```filter```?**

* I read the error message like that this resource ```/domains``` doesn't support filtering at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650a1568-6c6c-c738-2d40-f79c24c4ea29
* Version Independent ID: 5250aa4b-400a-e11a-d35c-0802cb374229
* Content: [List domains - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/domain-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/domain-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/domain-list.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @adimitui
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @o-l-a-v for raising this issue. I apologize for this confusion. We're currently working to ensure each property accurately indicates the query parameters it supports. But for now, for the **domain** resource, only the `$select` query parameter is confirmed.
