### ISSUE TITLE
root EntitySets are selectable and filterable, but Annotations in $metadata say they aren't

### ISSUE THREAD

**Issue by MiroJanosik** [microsoftgraph/microsoft-graph-docs#128]
EntitySet users (and basically all EntitySets) is of type user which is based on type directoryObject. 

This type is marked in Annotations as Filterable = false.
Though, it is posslbe to filter them if queried:
/users?$filter=startswith(displayName, 'John')

directoryObject is also marked as Selectable = false
Though, it is posslbe to select:
/users?$select=id,displayName

these inconsistencies should be fixed in $metadata

**Comment by MiroJanosik** [comment]
Great, so instead of enabling it in metadata you disabled it in the service, right?

When I now try to do:
/users?$filter=startswith(displayName, 'John')

I get: "code": "Request_BadRequest",
"message": "The following query options are not supported by this request method or cannot be applied to the requested resource: $filter,$expand,$orderby,$count,$inlinecount,$select,$skiptoken,$skip,$top",


When I try to:
/users?$filter=id eq '422980c9-e3bc-42cf-a404-c5d1a2565ce5'

I get: "code": "BadRequest",
"message": "Filter not supported.",

Was it necessary to disable the functionality?

**Comment by marych** [comment]
Nothing was disabled. /users?$filter=startswith(displayName,'John') works for me. Could you please provide request-id and timestamp for your failing request? 

There is a bug related to filtering for id property declared on the abstract "entity" entity type which affects the /users?$filter=id eq '422980c9-e3bc-42cf-a404-c5d1a2565ce5' query for /v1.0. I'll look into fixing that.

**Comment by MiroJanosik** [comment]
I tried it again at https://graphexplorer2.azurewebsites.net/ and it fails again for me. I am logged in as miro-az1@miroaz1.onmicrosoft.com and running POST query https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,'John')

This is response:
{
    "error": {
        "code": "Request_BadRequest",
        "message": "The following query options are not supported by this request method or cannot be applied to the requested resource: $filter,$expand,$orderby,$count,$inlinecount,$select,$skiptoken,$skip,$top",
        "innerError": {
            "request-id": "64f44593-d25e-447e-820a-c604b1a7b402",
            "date": "2016-03-01T07:16:41"
        }
    }
}

**Comment by marych** [comment]
I checked the failed request and it was a POST. $filter is only support for GETs.

**Comment by marych** [comment]
FYI - the /users?$filter=id eq '422980c9-e3bc-42cf-a404-c5d1a2565ce5' request should work now as well.

**Comment by MiroJanosik** [comment]
Thanks for the information

**Comment by mattgeim** [comment]
Please feel free to re-open this issue if needed. Thanks!
