### ISSUE TITLE
Boolean?  Or String?

### ISSUE THREAD

**Issue by cwstanton** [microsoftgraph/microsoft-graph-docs#12816]
[Enter feedback here]
In the request body, you specify that the "SaveToSentItems" property is a Boolean.

In the first example, you provide a sample value of "false" (quotes are there in the example).  This would be a String, not a Boolean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 572e47b6-e504-0918-fc06-11217eea40a4
* Version Independent ID: c30fd8a1-e913-0192-7405-d55232ea3703
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
OData allows wrapping booleans in quotes, so valid values are `true`, `false`, `"true"` or `"false"`, not any random string. You can verify in the metadata:

https://graph.microsoft.com/v1.0/$metadata

```
<Action Name="sendMail" IsBound="true">
    <Parameter Name="bindingParameter" Type="graph.user" />
    <Parameter Name="Message" Type="graph.message" Nullable="false" />
    <Parameter Name="SaveToSentItems" Type="Edm.Boolean" />
</Action>
```
