### ISSUE TITLE
ResourcesFolderUrl is read-only and may not be specified in the request

### ISSUE THREAD

**Issue by dwanjuhi** [microsoftgraph/microsoft-graph-docs#12824]
There is currently  no way to create a resources folder and link it to the assignment . When sending;
`PATCH https://graph.microsoft.com/beta/education/classes/{class-id}/assignments/{id}
 {
     "resourcesFolderUrl": "https://graph.microsoft.com/v1.0/drives/{driveid}/items/{item-id}"
 }`
 response: 
` "code": "20243",
     "message": "Invalid request body. ResourcesFolderUrl is read-only and may not be specified in the request.",`

This is not specified in the documentation. The issue was first reported by a customer here: https://docs.microsoft.com/en-us/answers/questions/399289/index.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff389a5-dd32-e165-f72d-d419903b9203
* Version Independent ID: d3939fd5-d76e-c403-a25a-d0f6b1f99331
* Content: [educationAssignment resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/educationassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/educationassignment.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @dipakboyed
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MEIFLWR** [comment]
Hi @dwanjuhi, you can call this API to set up a resources folder for the assignment: https://docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta

**Comment by dipakboyed** [comment]
> Hi @dwanjuhi, you can call this API to set up a resources folder for the assignment: https://docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-beta
