### ISSUE TITLE
Per Graph Explorer, /group/{id}/owners is queryable with `User.ReadBasic.All`

### ISSUE THREAD

**Issue by ascott18** [microsoftgraph/microsoft-graph-docs#12831]
`User.ReadBasic.All` is sufficient for `/group/{id}/owners`, but this is not documented.

![image](https://user-images.githubusercontent.com/5017521/119178864-1c848280-ba23-11eb-8b20-13191e192929.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c49e98ce-6e59-6480-71a4-53065dfdad7b
* Version Independent ID: ad9de78d-b6e2-dd46-051c-d7d4de51ac0a
* Content: [List owners - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-owners?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ascott18** [comment]
This actually doesn't seem to work in practice (I guess graph explorer is polluted with additional scopes that I can't un-consent from). So, Graph explorer here is wrong that this is queryable with only User.ReadBasic.All.

**Comment by FaithOmbongi** [comment]
Thank you @ascott18 for raising this issue. Currently, access tokens are issued with all delegated permissions which have been granted to the client app, in this case Microsoft Graph, even if the permissions were not explicitly requested.
