### ISSUE TITLE
Update default branding returns resource does not exist 

### ISSUE THREAD

**Issue by dwanjuhi** [microsoftgraph/microsoft-graph-docs#12855]
Sending a PATCH request to update default branding returns `Request_ResourceNotFound`. This happens both in postman and GE, see screenshot below: 

![UpdateResourceBrandingError](https://user-images.githubusercontent.com/77264508/119498805-b07d8380-bd6e-11eb-93f8-799e60d8399a.PNG)

See request information below: 

```
{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource 'TENANTID' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2021-05-25T12:29:40",
            "request-id": "a013b998-eb0f-4842-9b32-d25f5912dd86",
            "client-request-id": "76304173-af41-3554-03a6-64a1f7884eff"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0c9f19-e487-c3c3-c776-c524aa9ae5da
* Version Independent ID: 20f09b39-a723-a509-82a0-5a10fe106a68
* Content: [Update organizationalBrandingProperties - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @AlmarS
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AlexanderMars** [comment]
Hi there,

Thanks for reaching out. Please, include the Accept-Language request header with a valid ISO-639 locale or a default value e.g. "default" to avoid getting an error "Resource 'TENANTID' does not exist or one of its queried reference-property objects are not present."

You can find more details [here](https://docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&tabs=http)

Kind regards,
Sasha
