### ISSUE TITLE
isFavourite does not support filter

### ISSUE THREAD

**Issue by dwanjuhi** [microsoftgraph/microsoft-graph-docs#12883]
Adding a filter clause to get request to retrieve list of users who are favourites ( or not ) returns the property 'IsFavorite' does not support filtering see below: 

![PeopleFilterNotSupported](https://user-images.githubusercontent.com/77264508/119683980-ccefed80-be4c-11eb-9745-d9d3744fc945.PNG)

Issue was first reported by a customer on SO [here](https://stackoverflow.com/questions/67700797/how-can-i-get-my-favorite-people-outlook-contacts-via-microsoft-graph)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b391317-725b-2e29-b675-74b5bbcaa293
* Version Independent ID: c58a0fb5-c9f8-62ee-7c21-509b13415e2b
* Content: [person resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/person?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/person.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/person.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @chialiyun for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-people.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
