### ISSUE TITLE
Graph API DriveItem Copy Operation - Copied Resource ID on Accepted

### ISSUE THREAD

**Issue by Jatish-Khanna** [microsoftgraph/microsoft-graph-docs#12897]
In many cases, the copy action is performed asynchronously. The response from the API will only indicate that the copy operation was accepted or rejected. We get a resource monitor URL upon accepting the request but doesn't provide the resource ID unless completed is completed

![image](https://user-images.githubusercontent.com/20390859/119764392-eb96c880-bece-11eb-9ec0-f1e624ff239e.png)

I am assuming flow would be ->
  Copy Request -> Request Accepted -> Create a temporary DriveItem -> (on complete) Place the file and generate metadata

  Is it possible to get the resourceId as soon as the Copy DriveItem operation is accepted, otherwise a client also has to process it async or blocking.

![image](https://user-images.githubusercontent.com/20390859/119764605-5e07a880-becf-11eb-8c64-3ab70ff5a5dc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d5f74c-db0c-2039-cab6-04db509f996d
* Version Independent ID: e70d49fb-aa7a-1800-2161-ff988832c197
* Content: [Working with long running actions (beta) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/long-running-actions-overview?tabs=http)
* Content Source: [concepts/long-running-actions-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/long-running-actions-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @daspek
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @Jatish-Khanna for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/products/graph). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
