### ISSUE TITLE
Wrong guide to get delegated token

### ISSUE THREAD

**Issue by frankpeng7** [microsoftgraph/microsoft-graph-docs#12893]
[Enter feedback here]
This is the official Graph dev guide to get a user delegated token https://docs.microsoft.com/en-us/graph/auth-v2-user?view=graph-rest-beta#token-request, but in the sample request it's showing value of `scope` as:
```
&scope=user.read%20mail.read
```
which is incorrect. I followed this guide and got 
```
{
    "error": "invalid_grant",
    "error_description": "AADSTS65001: The user or administrator has not consented to use the application with ID '95d4de1d-bb2f-43d5-b48f-26f5b82bff61' named 'get-graph-user-token'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 2f352701-f6cb-4c89-96db-fe0a604d2702\r\nCorrelation ID: ab6f9bb0-96ed-4986-935e-fde005c152f2\r\nTimestamp: 2021-05-26 19:02:45Z",
    "error_codes": [
        65001
    ],
    "timestamp": "2021-05-26 19:02:45Z",
    "trace_id": "2f352701-f6cb-4c89-96db-fe0a604d2702",
    "correlation_id": "ab6f9bb0-96ed-4986-935e-fde005c152f2",
    "suberror": "consent_required"
}
```
At this step, the correct `scope` for Graph should be `https://graph.microsoft.com/.default`. See value of "scope" in the official guide to get app token: https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-beta#token-request
```
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
```

Once I changed `scope` from `user.read%20mai.read` to `https://graph.microsoft.com/.default` I was able to get a delegated token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2Fbeta&view=graph-rest-beta)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-user.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
That scope value is a valid value. The error usually indicates you have not completed the authorization/consent step: https://docs.microsoft.com/en-us/graph/auth-v2-user#authorization-request

Using `https://graph.microsoft.com/.default` is only applicable if you pre-define your application's required scopes and set them on the app registration.

**Comment by frankpeng7** [comment]
@jasonjoh I actually have completed the consent step and was still persistently seeing the same error
![image](https://user-images.githubusercontent.com/16726609/119895186-560d3000-bef2-11eb-90ea-c11d28fa7084.png)

**Comment by jasonjoh** [comment]
What scopes did you send in the auth request?

**Comment by frankpeng7** [comment]
This is the request to get the auth code. I basically followed the guide.
```
https://login.microsoftonline.com/909c6581-5130-43e9-88f3-fcb3582cde37/oauth2/v2.0/authorize?client_id=95d4de1d-bb2f-43d5-b48f-26f5b82bff61&response_type=code&redirect_uri=https://bing.com&response_mode=query&scope=offline_access%20onlinemeetings.read%20onlinemeetings.readwrite&state=12345
```

**Comment by jasonjoh** [comment]
So just to clarify, in your auth request you're sending `&scope=offline_access%20onlinemeetings.read%20onlinemeetings.readwrite`, which means you're asking for auth for `offline_access`, `onlinemeetings.read`, and `onlinemeetings.readwrite`. In your token request you're sending `&scope=user.read%20mail.read`, which is asking for `user.read` and `mail.read`, neither of which would have been authorized/consented in your auth request. 

The guide uses those two scopes as an example, and it's consistent across the auth and the token request - which is a crucial point. As it says in the parameter table for the token request:

> A space-separated list of scopes. The scopes requested in this leg must be equivalent to or a subset of the scopes requested in the first (authorization) leg.

In your case in the token request you should be sending `&scope=onlinemeetings.read%20onlinemeetings.readwrite`. If you are doing that and it still isn't working, something non-obvious is going on.

**Comment by frankpeng7** [comment]
This is the actual request I used to get token. I did put onlinemeetings.read onlinemeetings.readwrite in the scope (when I said `&scope=user.read%20mail.read` I was referring to the content in the dev guide)
![image](https://user-images.githubusercontent.com/16726609/119898363-99699d80-bef6-11eb-8a8b-ea3e7178aeef.png)

**Comment by jasonjoh** [comment]
It looks like the %20 in the Postman UI that's causing it to fail. Postman actually re-encodes that (keeps the 20, encodes `%` to `%25`):

```
scope=onlinemeetings.read%2520onlinemeetings.readwrite
```

Make your `scope` field `` and Postman will encode the space for you, yielding the correct result.

![image](https://user-images.githubusercontent.com/8966342/119899380-0a1db380-bf11-11eb-8dcb-51e14c5fb712.png)

![image](https://user-images.githubusercontent.com/8966342/119899936-cf684b00-bf11-11eb-8b28-801ae489115e.png)

**Comment by jasonjoh** [comment]
Closing as we found the problem. Let me know if you're still having an issue.

**Comment by frankpeng7** [comment]
I haven't got time to try it out without encoding the space, but thanks @jasonjoh for helping out! I'll ping you if the issue persists in the future.
