### ISSUE TITLE
unable to find any further information about deviceConfigurationSettingState

### ISSUE THREAD

**Issue by sebsalvat** [microsoftgraph/microsoft-graph-docs#12900]
I'm unable to find this resource under DeviceManagement or elsewhere, could you please provide the URI for this resource which works in the MS graph explorer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d69510e-790c-b8fa-983c-e70c849528b2
* Version Independent ID: 7e68c8a3-094a-8134-1c3b-73ad557e195e
* Content: [deviceConfigurationSettingState resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-deviceconfigurationsettingstate?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-deviceconfig-deviceconfigurationsettingstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-deviceconfig-deviceconfigurationsettingstate.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
You can see these values in the Console by navigating to:
Devices > Configuration  Profiles > (select a profile) > Device Status > (select a device) > Device configuration > (select a configuration) > (select a setting)

This is an example URI from my console when navigating the above path: https://graph.microsoft.com/beta/deviceManagement/managedDevices/<deviceID>/deviceConfigurationStates/a2e13804-2332-4193-90ab-e5fd35e7850f/settingStates?$filter=(userId%20eq%20%279eca12da-e96d-4a03-843b-82e2f1a1eb03%27)
