### ISSUE TITLE
Need to call /sites/{site-id}/analytics/alltime or /sites/{site-id}/analytics/lastsevendays to get analytics data

### ISSUE THREAD

**Issue by aaronmi** [microsoftgraph/microsoft-graph-docs#12928]
/sites/{site-id}/analytics only returns alltime: null or lastsevendays: null.
Need to call /sites/{site-id}/analytics/alltime or /sites/{site-id}/analytics/lastsevendays to get data returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc23aedb-c478-2515-0d37-a3683897eebc
* Version Independent ID: 60536091-1ce7-fde8-9e39-115517304400
* Content: [Get itemAnalytics - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/itemanalytics-get?view=graph-rest-1.0&tabs=http&source=docs)
* Content Source: [api-reference/v1.0/api/itemanalytics-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/itemanalytics-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @daspek
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @aaronmi for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
