### ISSUE TITLE
Limit support for Exchange or Excel???

### ISSUE THREAD

**Issue by heartlocker** [microsoftgraph/microsoft-graph-docs#12945]
Can't understand the limit support is for exchagne or excel. Does it suppot to call excel API in China? it can't work as I tested. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dbd263-9afd-aa90-cb50-bbadfc424cc2
* Version Independent ID: 63aaf699-609e-b4dd-bd02-9f891e09db8d
* Content: [National cloud deployments - Microsoft Graph](https://docs.microsoft.com/en-us/graph/deployments)
* Content Source: [concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/deployments.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @arpitha-dhanapathi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @heartlocker  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/products/graph). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
