### ISSUE TITLE
Search API doesn't return parent reference id

### ISSUE THREAD

**Issue by LukeOwlclaw** [microsoftgraph/microsoft-graph-docs#12940]
When using the search API we get 

    "parentReference": {
         "siteId": "m365x231305.sharepoint.com,5724d91f-650c-4810-83cc-61a8818917d6,c3ba25dc-2c9f-48cb-83be-74cdf68ea5a0"
     },

Unfortunately this parent is only the (sub)site. How can I find out the location where the search result is stored? From `webUrl`  could get the folder name, but I needs its id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files#feedback)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cristianv-ms** [comment]
LukeOwiclaw, can you please upload the both the request and the response.

**Comment by yiwenwang-ms** [comment]
Hi LukeOwiclaw, current now the parentReference doesn't provide parent folder Id,
but you can try use select properties, as below.
can you check if it is the correct id you want?

```
{
    "requests": [
        {
            "entityTypes": [
                "listItem"
            ],
            "query": {
                "queryString": "path:https://microsoft-my.sharepoint.com/personal/yiwenwang_microsoft_com/Documents/Desktop/DDDD/Include_5_files"
            },
            "fields": [
                "ParentId"
            ]
        }
    ]
}
```

**Comment by LukeOwlclaw** [comment]
First, the query using the site api:

    GET
    https://graph.microsoft.com/v1.0/sites/MYCOMPANY.sharepoint.com,SUBSITEID/drive/root/search(q='uniquesearchword​​')
    
    {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
        "value": [
            {
                "@odata.type": "#microsoft.graph.driveItem",
                "createdDateTime": "2021-05-18T10:40:52Z",
                "id": "01LGLZNHXFH4DQDFLBGVGJCKLMAA3TTGTY",
                "lastModifiedDateTime": "2021-06-03T05:52:16Z",
                "name": "MYTESTFILE.pptx",
                "webUrl": "https://MYCOMPANY.sharepoint.com/SUBSITENAME/_layouts/15/Doc.aspx?sourcedoc=%7B01073FE5-6195-4C35-9129-6C0037399A78%7D&file=TeamSlide%20About.pptx&action=edit&mobileredirect=true&DefaultItemOpen=1",
                "size": 636281,
                "createdBy": {
                    "user": {
                        "email": "luke@MYCOMPANY.com",
                        "displayName": "Luke Owlclaw"
                    }
                },
                "lastModifiedBy": {
                    "user": {
                        "email": "luke@MYCOMPANY.com",
                        "displayName": "Luke Owlclaw"
                    }
                },
                "parentReference": {
                    "driveId": "b!b-WgE-V8DUGu3RghC8SHPdCMpj_ARMdAtmmbNW7V8MKxlU2HRTSkQ4MTAU-UWlFh",
                    "driveType": "documentLibrary",
                    "id": "01LGLZNHV6Y2GOVW7725BZO354PWSELRRZ"
                },
                "file": {
                    "mimeType": "application/vnd.openxmlformats-officedocument.presentationml.presentation"
                },
                "fileSystemInfo": {
                    "createdDateTime": "2021-05-18T10:40:52Z",
                    "lastModifiedDateTime": "2021-06-03T05:52:16Z"
                },
                "searchResult": {}
            }
        ]
    }


Next, the equivalent query using the search api:

    POST
    https://graph.microsoft.com/v1.0/search/query
    
    {
        "requests": [
            {
                "entityTypes": [
                    "driveItem"
                ],
                "query": {
                    "queryString": "uniquesearchword​"
                }
            }
        ]
    }
    
    {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.searchResponse)",
        "value": [
            {
                "searchTerms": [
                    "uniquesearchword"
                ],
                "hitsContainers": [
                    {
                        "total": 1,
                        "moreResultsAvailable": false,
                        "hits": [
                            {
                                "hitId": "01LGLZNHXFH4DQDFLBGVGJCKLMAA3TTGTY",
                                "rank": 1,
                                "summary": "<c0>uniquesearchword</c0> Installer <ddd/>",
                                "resource": {
                                    "@odata.type": "#microsoft.graph.driveItem",
                                    "size": 636281,
                                    "id": "01LGLZNHXFH4DQDFLBGVGJCKLMAA3TTGTY",
                                    "createdDateTime": "2021-05-18T10:40:52Z",
                                    "lastModifiedDateTime": "2021-06-03T05:52:14Z",
                                    "name": "MYTESTFILE.pptx",
                                    "webUrl": "https://MYCOMPANY.sharepoint.com/SUBSITENAME/Shared Documents/MYTESTFILE.pptx",
                                    "fileSystemInfo": {
                                        "createdDateTime": "2021-05-18T10:40:52Z",
                                        "lastModifiedDateTime": "2021-06-03T05:52:14Z"
                                    },
                                    "createdBy": {
                                        "user": {
                                            "displayName": "Luke Owlclaw"
                                        }
                                    },
                                    "lastModifiedBy": {
                                        "user": {
                                            "displayName": "OTHER USER"
                                        }
                                    },
                                    "parentReference": {
                                        "driveId": "b!b-WgE-V8DUGu3RghC8SHPdCMpj_ARMdAtmmbNW7V8MKxlU2HRTSkQ4MTAU-UWlFh",
                                        "siteId": "MYCOMPANY.sharepoint.com,SUBSITEID",
                                        "sharepointIds": {
                                            "listId": "874d95b1-3445-43a4-8313-014f945a5161",
                                            "listItemId": "1",
                                            "listItemUniqueId": "01073FE5-6195-4C35-9129-6C0037399A78"
                                        }
                                    }
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    }

In the first response we see: `parentReference.id`==``01LGLZNHV6Y2GOVW7725BZO354PWSELRRZ``

That can be used to get details about the folder using:

    GET    https://graph.microsoft.com/v1.0/sites/MYCOMPANY.sharepoint.com,SUBSITEID/drive/items/01LGLZNHV6Y2GOVW7725BZO354PWSELRRZ

The second response from the search api is missing this parent folder id.

**Comment by LukeOwlclaw** [comment]
@yiwenwang-ms 

    POST
    https://graph.microsoft.com/v1.0/search/query
    {
        "requests": [
            {
                "from": 0,
                "size": 1000,
                "entityTypes": [
                    "listItem"
                ],
                "query": {
                    "queryString": "uniquesearchword​"
                },
                "fields": [
                    "ParentId"
                ]
            }
        ]
    }

Gives me:

    {
        "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.searchResponse)",
        "value": [
            {
                "searchTerms": [
                    "uniquesearchword"
                ],
                "hitsContainers": [
                    {
                        "total": 2,
                        "moreResultsAvailable": false,
                        "hits": [
                            {
                                "hitId": "01073FE5-6195-4C35-9129-6C0037399A78",
                                "rank": 1,
                                "summary": "<c0>uniquesearchword</c0> Installer <ddd/>",
                                "resource": {
                                    "@odata.type": "#microsoft.graph.listItem",
                                    "fields": {
                                        "parentId": "{FD17466F-1D63-4FE9-A4AB-5D0001F39859}"
                                    }
                                }
                            }
                        ]
                    }
                ]
            }
        ]
    }

So, the `parentId` has a completely different value and even format.

GET    https://graph.microsoft.com/v1.0/sites/MYCOMPANY.sharepoint.com,SUBSITEID/drive/items/FD17466F-1D63-4FE9-A4AB-5D0001F39859

gives me `itemNotFound`


I am also surprised to see `"total": 2,` but only one result is listed.

**Comment by yiwenwang-ms** [comment]
@LukeOwlclaw 
Thanks for the details, understood what you want, current now, search API don't provide such ID, we'll discuss internally and feedback later.

**Comment by yiwenwang-ms** [comment]
@LukeOwlclaw 
Thank you, we will have two tasks tracking these two bugs:
 - Add the id you want into the parent reference.
 - Total "2" but only 1 result
If you still have any other concerns, please let us know.

**Comment by yiwenwang-ms** [comment]
Hi @LukeOwlclaw 
Could you please tell me do you want to apply this parent reference id to One Drive Item or just for SharePoint item or need both of  them?

**Comment by yiwenwang-ms** [comment]
@LukeOwlclaw, we have a fix for parent reference, I am verifying it and it will release next week, If you still have any other concerns, please let us know.

**Comment by yiwenwang-ms** [comment]
@LukeOwlclaw , can you see the parent  reference id now?

**Comment by LukeOwlclaw** [comment]
Yes, works great!
