### ISSUE TITLE
Nothing happens on device

### ISSUE THREAD

**Issue by emrecodeshake** [microsoftgraph/microsoft-graph-docs#12964]
It returns the right response but nothing happens on the device. So what should we do for action to affect the device?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01735915-791d-1f2f-c086-63044cfc68fb
* Version Independent ID: 328593a9-cfec-4243-7677-6feb84ffac2d
* Content: [wipe action - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-wipe?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-wipe.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-devices-manageddevice-wipe.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
If nothing happens when you perform the reboot now action from the Admin Console, you are probably better to raise a support ticket with Microsoft to help understand why it's not working.  The Graph API that the console uses is the same as what you're calling here, so both should behave the same.
