### ISSUE TITLE
Missing page. Delete method. 

### ISSUE THREAD

**Issue by makerofthings7** [microsoftgraph/microsoft-graph-docs#1296]
Issue: 
Click on the delete method. It's not there. ..ironic

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/domain_get

**Comment by PatAltimore** [comment]
Hi makerofthings7,

Thanks for the feedback.  We'll get the table of contents fixed soon.  The domain delete method can be found here: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/domain_delete

Thanks,
Pat

**Comment by PatAltimore** [comment]
Hi @makerofthings7,

The table of contents has been fixed.  Thanks for the feedback.

Pat
