### ISSUE TITLE
BadRequest response when Intune deevice action

### ISSUE THREAD

**Issue by emrecodeshake** [microsoftgraph/microsoft-graph-docs#12967]
Hi,

We are using Microsoft Graph Api to retrieve data about devices. Now we are trying to use it for intune device actions but  we are getting error messages even though we followed everything at docs 

1. we checked the permissions and all needed permissions are given.
2. we followed docs and tried multiple versions of API URLs mentioned in docs but none of them worked.
3. we also tried the beta version of API but it didn't work either.
4. we found some readings about some of these actions work specifically on some OS type or some specific device permissions but we can't find detail on docs. I am getting the following error on related actions

I am getting the following error on related actions

POST https://graph.microsoft.com/v1.0/users/{usersId}/managedDevices/{managedDeviceId}/remoteLock

``` 
{
    "error": {
        "code": "BadRequest",
        "message": "{  \"_version\": 3,  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 6676f0a0-8895-302e-672b-3cdb66092428 - Url: https://fef.amsub0502.manage.microsoft.com/DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices%28%27e002cd5b-f97f-4212-b0b6-38ae3e77938e%27%29/microsoft.management.services.api.remoteLock?api-version=2021-04-07\",  \"CustomApiErrorPhrase\": \"\",  \"RetryAfter\": null,  \"ErrorSourceService\": \"\",  \"HttpHeaders\": \"{}\"}",
        "innerError": {
            "date": "2021-05-31T08:56:10",
            "request-id": "a360b06a-fb02-4af3-9f8f-06e138b76288",
            "client-request-id": "6676f0a0-8895-302e-672b-3cdb66092428"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 275019d8-af80-8504-0fe8-bcc7e414126d
* Version Independent ID: e022c577-77af-01f0-dda0-8a5c83b05de2
* Content: [remoteLock action - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-remotelock?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-remotelock.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-devices-manageddevice-remotelock.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Here is a POST of a successful remote lock I did on an iOS device: https://graph.microsoft.com/beta/deviceManagement/managedDevices('26f5d1a5-793d-4f19-bf09-6360701057ee')/remoteLock
Does your POST use the same format for the URL?

**Comment by lramosvea** [comment]
Thank you @dougeby for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-corporate-mgmt.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
