### ISSUE TITLE
chat message list  @odata.nextLink broken

### ISSUE THREAD

**Issue by FixBugsFor** [microsoftgraph/microsoft-graph-docs#12995]
chat message list response's @odata.nextLink is always the same, any one sees it ?
it just started recently:

https://graph.microsoft.com/v1.0/chats/19:6d63c532e74b4013bcc190bbcd790f8d@thread.v2/messages?$top=10&$skiptoken=M2UyZDAwMDAwMDMxMzkzYTM2NjQzNjMzNjMzNTMzMzI2NTM3MzQ2MjM0MzAzMTMzNjI2MzYzMzEzOTMwNjI2MjYzNjQzNzM5MzA2NjM4NjQ0MDc0Njg3MjY1NjE2NDJlNzYzMjAxMDEwMDAwMDAwMDAwMDAwMGRmNDliNTQ1NzgwMTAwMDB8MTYxNzg5NTIyMDQ5MA%3d%3d

it returns the same next link over and over again 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548a7932-274e-ce6c-aed5-e35206f7894a
* Version Independent ID: 02c653f9-fde9-758e-9bb7-a573f88cbbe8
* Content: [List messages in a chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Do you see it returning the same messages?

**Comment by FixBugsFor** [comment]
Yeah, and seems to be only one returned even i put top as 10
***@***.***":1

**Comment by FixBugsFor** [comment]
PS: the channel messages next link is fine; 
user chat messages next link is not.

**Comment by RamjotSingh** [comment]
I am not reproing the behavior. Can you check a few things

1. Have you by any chance actually hit the end of chat (as in these are the last messages in chat)
2. Can you share client-request-Id and timestamp for both requests

**Comment by FixBugsFor** [comment]
It doesn't seem to be the last ones; it could be related to the group user chat messages and could be related to the legacy chatid
, that is not updated recently

Here is an example:
req 1 returns 50
req 2 returns 50
req 3 returns 17
from req 4, it always returns the same 2 in a loop

1. graphResponseHeaders -> {JsonObject@4478} "{"client-request-id":["08eb5c3c-5f7e-437b-b0df-6bb2a7ed4e78"],"content-type":["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"],"date":["Tue, 08 Jun 2021 13:32:58 GMT"],"odata-version":["4.0"],"request-id":["1f275cb9-3147-4e87-a2b0-b47c94ce2640"],"strict-transport-security":["max-age=31536000"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Canada East\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"QB1PEPF0000114B\"}}"]}"


2. graphResponseHeaders -> {JsonObject@4562} "{"client-request-id":["523cdfe7-8969-4702-bec4-867688658c58"],"content-type":["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"],"date":["Tue, 08 Jun 2021 13:34:04 GMT"],"odata-version":["4.0"],"request-id":["e4d126be-91f8-4cc2-8524-0be509b8f7b8"],"strict-transport-security":["max-age=31536000"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Canada East\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"QB1PEPF0000114B\"}}"]}"


3. graphResponseHeaders -> {JsonObject@4616} "{"client-request-id":["bcef1dc7-1fb3-4332-8239-69ce91b6bd94"],"content-type":["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"],"date":["Tue, 08 Jun 2021 13:34:34 GMT"],"odata-version":["4.0"],"request-id":["c9576ccf-66a0-4e26-a8eb-c7ddc19aa9c7"],"strict-transport-security":["max-age=31536000"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Canada East\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"QB1PEPF0000114B\"}}"]}"


---
4. {"client-request-id":["4256359a-f986-42e3-a7ff-9961a3c59f37"],"content-type":["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"],"date":["Tue, 08 Jun 2021 13:35:05 GMT"],"odata-version":["4.0"],"request-id":["6e9a9e65-b704-437b-8efe-c66eecf11177"],"strict-transport-security":["max-age=31536000"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Canada East\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"QB1PEPF0000114B\"}}"]}

5. {"client-request-id":["95e1daca-0a65-44d2-8266-5f4059a02116"],"content-type":["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"],"date":["Tue, 08 Jun 2021 13:35:32 GMT"],"odata-version":["4.0"],"request-id":["4039a788-5ae4-4054-9bed-d8ca57d81fe0"],"strict-transport-security":["max-age=31536000"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Canada East\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"QB1PEPF0000114B\"}}"]}

6. {"client-request-id":["c4548228-bb12-4ec7-9e32-bb0b854c6be2"],"content-type":["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"],"date":["Tue, 08 Jun 2021 13:35:58 GMT"],"odata-version":["4.0"],"request-id":["ac33ff15-3934-43da-87d8-2a0a1f3cc401"],"strict-transport-security":["max-age=31536000"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Canada East\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"QB1PEPF0000114B\"}}"]}

7. {"client-request-id":["f36901f6-b542-4252-99d9-9f311c206c07"],"content-type":["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"],"date":["Tue, 08 Jun 2021 13:36:22 GMT"],"odata-version":["4.0"],"request-id":["0aa2fc7c-2697-4f76-8cb6-2bb198cbb8cd"],"strict-transport-security":["max-age=31536000"],"transfer-encoding":["chunked"],"vary":["Accept-Encoding"],"x-ms-ags-diagnostic":["{\"ServerInfo\":{\"DataCenter\":\"Canada East\",\"Slice\":\"E\",\"Ring\":\"2\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"QB1PEPF0000114B\"}}"]}

**Comment by lramosvea** [comment]
Thank you @ for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-teamwork.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
