### ISSUE TITLE
C# code error in example 2

### ISSUE THREAD

**Issue by antonin-vs-invest** [microsoftgraph/microsoft-graph-docs#13019]
Greetings,

Based on what worked for me, c# code in example 2 should be : 
await graphClient.DirectoryRoles["**roletemplateId=**{directoryRole-id}"].Members.References
	.Request()
	.AddAsync(directoryObject);

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 938ca156-fb76-5388-7f18-e3da2da9c3b0
* Version Independent ID: 685df32e-2a02-ed10-010a-5260a0568a8e
* Content: [Add directory role member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryrole-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryrole-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directoryrole-post-members.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @antonin-vs-invest for raising this issue. The **roleTemplateid** is a different property from the **id** of the directory role. This request requires the value of the **id** property.

**Comment by antonin-vs-invest** [comment]
Right, so to send the request using the role template id, it should be :
await graphClient.DirectoryRoles[**"roletemplateId={role-template-id}"**].Members.References
.Request()
.AddAsync(directoryObject);
My point was that you need to put 'roleTemplateId=' first in the DirectoryRoles[...] part of the request.
Cheers.

**Comment by FaithOmbongi** [comment]
> Right, so to send the request using the role template id, it should be :
> await graphClient.DirectoryRoles["**roletemplateId={role-template-id}**"].Members.References
> .Request()
> .AddAsync(directoryObject);
> My point was that you need to put 'roleTemplateId=' first in the DirectoryRoles[...] part of the request.
> Cheers.

Hi @antonin-vs-invest , yes this is now correct. The C# example in [Example 2](https://docs.microsoft.com/en-us/graph/api/directoryrole-post-members?view=graph-rest-1.0&tabs=csharp#example-2-add-a-new-member-to-a-directory-role-using-role-templateid) seems to have been meant for [Example 1](https://docs.microsoft.com/en-us/graph/api/directoryrole-post-members?view=graph-rest-1.0&tabs=csharp#example-1-add-a-new-member-to-a-directory-role-using-role-objectid). Looks like a mix-up as the other languages are correct. I'll raise a PR to request a fresh code snippet.

Thank you for raising this issue.
