### ISSUE TITLE
re-joining finished meeting overwrites previous attendance reports

### ISSUE THREAD

**Issue by eprigorodov** [microsoftgraph/microsoft-graph-docs#13015]
Online meeting remains accessible after its end time and /with certain setup/ participants can join again.
Such re-join starts meeting anew and overwrites attendance report with the new version, capturing the latest online session. The data on initial session becomes inaccessible.

A simplified example scenario:
* meeting starts,
* participants A, B and C join,
* meeting ends,
* path `/meetingAttendanceReport` returns report with records about A, B and C,
* meeting persists and join links remain to be valid,
* participant C joins again to the same meeting and leaves,
* now attendance report contains a single record about C

Question: shouldn't attendance report be cumulative and collect all join/leave events? If not, can there be parameter to fetch past versions of attendance report?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9593d8-ed60-527f-c549-b22dce5adbd9
* Version Independent ID: cdf36bed-fd4f-8be7-918c-6cdf74258676
* Content: [Get onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @jsandoval-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @eprigorodov thanks for reaching out. I do admit this experience is not quite user-friendly, but at this point of time it's expected because the `/meetingAttendanceReport` API always returns the attendance report of the latest call/meeting session.
I'll ask our PM to create a backlog item to see how we can improve this.

**Comment by eprigorodov** [comment]
Hi @frankpeng7, thank you for reviewing and answering. Your approach is quite fine in the context of beta API. 

Just meant to give some end user input, otherwise /with the current implementation/ the whole call might become unusable.

When it comes to improving, the following options could fix the problem for us:

1. Just accumulate join-leave events from all call sessions and return them in `attendanceIntervals` as if there was only one session. That drops information about session restarts, but we don't see it in the API anyway.
1. Add a parameter like `/meetingAttendanceReport?session=0`. That reveals a concept of having several sessions within the same online meeting, which might require more work on API refinements. But it's worth it.

To possible affected readers: one workaround is polling attendance report periodically around the expected meeting end time and accumulating results. We tried and it works at the expense of higher load on MS Graph. One request in 5-10 minutes seems to be sufficient.

**Comment by mkhribech** [comment]
@frankpeng7  added to the backlog

**Comment by frankpeng7** [comment]
Closing as the ask is being tracked in backlog.
