### ISSUE TITLE
C# code error in example 2

### ISSUE THREAD

**Issue by antonin-vs-invest** [microsoftgraph/microsoft-graph-docs#13018]
Greetings,

Based on what worked for me, c# code in example 2 should be :
await graphClient.DirectoryRoles["**roleTemplateId=**{directoryRole-id}"].Members["{directoryObject-id}"].Reference
	.Request()
	.DeleteAsync();

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd9cfff-a7c4-0a9f-a376-aa950b0af32c
* Version Independent ID: ab16a525-f574-3b94-7020-0a220ab786ab
* Content: [Remove directory role member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryrole-delete-member?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/directoryrole-delete-member.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directoryrole-delete-member.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @antonin-vs-invest for raising this issue. The **roleTemplateid** is a different property from the **id** of the directory role. This request requires the value of the **id** property.

**Comment by antonin-vs-invest** [comment]
Right, so to send the request using the role template id, it should be :
await graphClient.DirectoryRoles[**"roleTemplateId={role-template-id}"**].Members["{directoryObject-id}"].Reference
.Request()
.DeleteAsync();
My point was that you need to put 'roleTemplateId=' first in the DirectoryRoles[...] part of the request.
Cheers.

**Comment by FaithOmbongi** [comment]
> Right, so to send the request using the role template id, it should be :
> await graphClient.DirectoryRoles["**roleTemplateId={role-template-id}**"].Members["{directoryObject-id}"].Reference
> .Request()
> .DeleteAsync();
> My point was that you need to put 'roleTemplateId=' first in the DirectoryRoles[...] part of the request.
> Cheers.

Hi @antonin-vs-invest , yes this is now correct - roleTemplateId goes with the roleTemplateId, not directoryRole-id . The C# example in [Example 2](https://docs.microsoft.com/en-us/graph/api/directoryrole-delete-member?view=graph-rest-1.0&tabs=csharp#example-2-remove-directory-role-member-using-role-templateid) seems to have been meant for [Example 1](https://docs.microsoft.com/en-us/graph/api/directoryrole-delete-member?view=graph-rest-1.0&tabs=csharp#example-1-remove-directory-role-member-using-role-objectid). Looks like a mix-up as the other languages are correct. I'll raise a PR to request a fresh code snippet.

Thank you for raising this issue.
