### ISSUE TITLE
Move Emails - GraphAPI - Issue with Service Account and a shared Mailbox

### ISSUE THREAD

**Issue by PrashantShettyInbotiqa** [microsoftgraph/microsoft-graph-docs#13031]
Hi,

We are trying an archiving strategy for our app, which require capability to move the emails to a separate Public folder (not well-known ones available but a newly created Folder in the mailbox) post processing.

We are using GraphAPI SDK.

Email message Move API seems to work fine for a service account and for it's own mailbox, but same API doesn't work for the shared Mailbox to which service account have Read and Write access.

API under consideration

https://graph.microsoft.com/v1.0/users/es15@yu********.onmicrosoft.com/mailFolders/INBOX/messages/AAMk*******************BGAAAA=/microsoft.graph.move

Any pointers are highly appreciated.

Thanks.
Prashant

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b15ffe-fa85-aba6-a28b-e4a7075d4c31
* Version Independent ID: 61d07c99-1ed6-fa44-0460-053f4d9cdd9c
* Content: [message: move - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/message-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-move.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @PrashantShettyInbotiqa  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-calendar.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
