### ISSUE TITLE
Update teams app in App catalog documentation is wrong

### ISSUE THREAD

**Issue by hbagarich** [microsoftgraph/microsoft-graph-docs#13047]
Hi,
So I have tried to follow the article on how to update Teams App in App catalog and it seems it is wrong. 
Instead of **POST /appCatalogs/teamsApps/{id}/appDefinitions** i needed to **PUT /appCatalogs/teamsApps/{id}**

I found out this by analyzing the Teams Admin center which correctly uses PUT. 
What is the process to update the article to instruct developers to use correct HTTP request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71084976-9b36-4562-9604-6d55b27c6bf9
* Version Independent ID: c94bf2e6-d302-2f15-f02e-ea1dbad377b9
* Content: [Update teamsApp - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/teamsapp-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/teamsapp-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
Thanks for Reporting. Doc team will be follow up and work on update docs.

**Comment by Nivedipa-MSFT** [comment]
@hbagarich - We will test this and update it accordingly in document.

**Comment by Nivedipa-MSFT** [comment]
@hbagarich - Did you get a chance to test this?

**Comment by hbagarich** [comment]
Hi,

For the PUT method I did not use  /appCatalogs/teamsApps/{id}/appDefinitions , I used /appCatalogs/teamsApps/{id} (notice missing appDefinitions). Last time the problem was that the POST on /appCatalogs/teamsApps/{id}/appDefinitions did not work. 

Will check the POST on /appCatalogs/teamsApps/{id}/appDefinitions and get back to you.
