### ISSUE TITLE
Add sample code link to Activity feed document

### ISSUE THREAD

**Issue by Trinetra-MSFT** [microsoftgraph/microsoft-graph-docs#13066]
Please update c# code samples link to document:
c# sample link to be updated:
[https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed/csharp](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/graph-activity-feed/csharp)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f896ed9-bcaf-1225-d285-2b8f472a30d8
* Version Independent ID: e87a78f2-1efc-1303-8404-144ee5d28e15
* Content: [chat: sendActivityNotification - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-sendactivitynotification.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @eddie-lee-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Mamatha-MSFT** [comment]
Thanks for the insights, concerned document team will work on it.

**Comment by lramosvea** [comment]
Closing as doc has been updated
