### ISSUE TITLE
Teams OnlineMeetings, concluded?

### ISSUE THREAD

**Issue by enkelmedia** [microsoftgraph/microsoft-graph-docs#13068]
The docs says:

"Meeting attendance reports are available for meetings other than live events, and are only available when the meeting has concluded."

What I do know if that a host can "End meeting" from the Teams App UI, but what if the host just closes the app? Will the meeting be concluded automatically? I haven't managed to see a way to "End" the meeting via the API so I'm just wondering how our integration should know if the meeting was unattended (nobody logged in and this is why the attendance report is empty) or if the meeting is not concluded.

I think that this needs to be more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9593d8-ed60-527f-c549-b22dce5adbd9
* Version Independent ID: cdf36bed-fd4f-8be7-918c-6cdf74258676
* Content: [Get onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @jsandoval-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mkhribech** [comment]
@enkelmedia to clarify your scenario: will there be other attendees in the call prior to the host disconnecting or ending the call?
the second part you are asking about the behavior if no one attend the report and the meeting is not concluded as in the meeting didn't start?

**Comment by williamlooney** [comment]
This is a question for the online meeting API. Which is owned by Meryem

**Comment by mkhribech** [comment]
@enkelmedia can you please help us address the previous question so we can provide a clear answer. Thanks

**Comment by mkhribech** [comment]
@enkelmedia  if the organizer dropped from the meeting but the meeting is still (there are other users  in the meeting) the meeting is not concluded. Attendance only gets generated when the call has concluded. hope that helps

**Comment by enkelmedia** [comment]
@mkhribech It's a question regarding the API. Since we use it to schedule meetings. The host might forget to conclude the meeting from the Teams UI and I'm we need to fetch attendance reports (which can only be done when the meeting is concluded) so what I'm asking for is a way conclude the meeting via the API.

**Comment by mkhribech** [comment]
@enkelmedia once the call ends that is when we can retrive the report.

**Comment by mkhribech** [comment]
@enkelmedia can we set up time to chat and understand further?

**Comment by enkelmedia** [comment]
@mkhribech I would love that! You can reach me at markus [at sign here] obviuse.se. I’m located in Sweden so might have to consider time zones.

**Comment by frankpeng7** [comment]
Old for 30+ days. Closing for now. Feel free to open a new issue if the problem persists.

**Comment by enkelmedia** [comment]
Still no feedback so it still very much persists.

**Comment by frankpeng7** [comment]
Reopening as customer responded. @mkhribech please help follow up on this.

**Comment by mkhribech** [comment]
can you email me @ mkhribech@microsoft.com to collect your req.
