### ISSUE TITLE
Cannot use this code in production

### ISSUE THREAD

**Issue by GermanEZI** [microsoftgraph/microsoft-graph-docs#13081]
The Authentication Providers mentioned on this page are all in Preview.

I assume I should still be using IAuthenticationProvider; is this correct?   I'm using C# and .NET Core
When will Microsoft.Graph.Auth be GA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS&source=docs)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @GermanEZI  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sdk.html)A. Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.

**Comment by jasonjoh** [comment]
That being said, this topic will soon be updated for the Graph SDK v4, which moves to using the TokenProvider class from the Azure.Identity package. Microsoft.Graph.Auth is never going to be GA, it's basically sample implementations of the older SDK's IAuthenticationProvider interface. I'm going to reopen and assign this to me to track updating this topic.

**Comment by GermanEZI** [comment]
@jasonjoh 

Thanks for that.  Looking forward to v4
