### ISSUE TITLE
Example url should to end with /children

### ISSUE THREAD

**Issue by DennisKuhn** [microsoftgraph/microsoft-graph-docs#13105]
The url in the example doesn't work:
`POST https://graph.microsoft.com/beta/termStore/sets/{setId}/terms`
the url works when ending with chidlren
`POST https://graph.microsoft.com/beta/termStore/sets/{setId}/children`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23fdd90-a81e-3001-a2d6-e315b6a022a7
* Version Independent ID: 91ed3cce-2550-3fc8-0038-524cfdba0128
* Content: [Create term - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/termstore-term-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/termstore-term-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/termstore-term-post.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @mohitpcad
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thanks for your feedback. Closing this issue for now, as this same issue has been reported here: https://github.com/microsoftgraph/microsoft-graph-docs/issues/12902
