### ISSUE TITLE
False/Misleading information about capabilities of API

### ISSUE THREAD

**Issue by zoladkow** [microsoftgraph/microsoft-graph-docs#13114]
The page in question suggests that it is possible to filter the members of a group using $filter, but in fact such queries fail for both `1.0` and `beta` APIs

```
com.microsoft.graph.http.GraphServiceException: Error code: Request_UnsupportedQuery
Error message: The specified filter to the reference property query is currently not supported.

GET https://graph.microsoft.com/v1.0/groups/...REMOVED.../members/microsoft.graph.user?%24select=userPrincipalName%2CdisplayName&%24orderby=displayName&%24top=10&%24filter=startsWith%28displayName%2C%20%27Bar%27%29
ConsistencyLevel : eventual
SdkVersion : graph-java/v3.3.0
```

If it is not possible to have both OData cast and `$filter` this should be **clearly stated** on the page. 
Also, SDK lacks support for `$search` query parameter, which becomes obvious only when doing the implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3edbef-651c-47df-1322-9f39abd35adc
* Version Independent ID: 8774189d-c527-579d-9104-39d538159aff
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zoladkow** [comment]
Ha! apparently the cause for the error is the missing `$count=true` - only then a query with `$filter` fails...

Still, neither the page nor that error message is helpful in this situation :(

**Comment by FaithOmbongi** [comment]
Thank you @zoladkow for raising the issue & resolving it.

For directory objects, and with the exception of `$search`, when you use **ConsistencyLevel** header, you must also use `$count` either as a URL segment (`/$count`) or query string (`$count=true`).

Your query would be:

[https://graph.microsoft.com/v1.0/groups/bbd146a0-3db0-4e9f-a41b-0e162035d29c/members/microsoft.graph.user?$select=userPrincipalName,displayName&$orderby=displayName&$top=10&$filter=startsWith(displayName,'Bar')&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%2Fbbd146a0-3db0-4e9f-a41b-0e162035d29c%2Fmembers%2Fmicrosoft.graph.user%3F%24select%3DuserPrincipalName%2CdisplayName%26%24orderby%3DdisplayName%26%24top%3D10%26%24filter%3DstartsWith(displayName%2C'Bar')%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
