### ISSUE TITLE
Add steps in "Create an Azure Active Directory app" + fix minor omission

### ISSUE THREAD

**Issue by hb-webdev** [microsoftgraph/microsoft-graph-docs#13121]
Forgive me if I'm blind, but I don't see where it ever explicitly tells you to import the `Agenda` component (`import { Agenda, Login } from '@microsoft/mgt-react';`). Luckily the entire code is provided, so this omission is trivial from a practical standpoint.

I also wish it provided a step-by-step in the "Create an Azure Active Directory app" section. First off, I'm not sure how to `grant this app permissions to access specific resources on behalf of the person using your app.` (That's Greek to me--Well not quite; just exaggerating for effect. Maybe a KB link could be provided on how to do exactly this, to avoid 15-minute google hunts) Also, I ran into an error after trying to log in the first time telling me I had to make my Azure app multi-tenant, which I did, but that doesn't seem right to me, since I'm only using the app within my organization. (We do use different email domains within the organization though...I'm guessing that might be the issue.)

As a side-note, [Use the Microsoft Graph Toolkit with React - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react) was the only helpful article to me as a newbie, and I had to Google for--I don't want to exaggerate--but certainly a couple hours (after giving the tutorials below a shot) to find it. I'm sure it's mind-numbingly obvious where I should've gone for a React+Microsoft Graph tutorial for the more apt, but this is one of the few instances where I felt the available official documentation for my general scenario was actually oversaturated. (I guess that's what can happen when you choose to dev in such a popular modern language like React.)

Here are some articles I attempted to follow, each having their own obstacle for me:
 * https://docs.microsoft.com/en-us/graph/tutorials/react
   * Wasn't the bare-bones example I was looking for--too convoluted for me to just focus on the essentials
 * https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-react
   * Used `@azure` library instead of `@microsoft` like the one above did, making me feel off-track
 * https://docs.microsoft.com/en-us/learn/modules/msgraph-toolkit-intro/1-introduction
   * Not React-specific: Imports libraries via `<script src=`. There's a part where it tells you how to import with `npm`, but then the rest of the tutorial assumes you're using `<script src=` and I was too much of a simpleton to adapt

A [big] button linking directly to this article: [Use the Microsoft Graph Toolkit with React - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react#feedback) after going through the "Get Started" steps (https://developer.microsoft.com/en-us/graph/quick-start) would have been awesome for me, personally.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf058f59-299f-bdea-ee08-f432e298b3d6
* Version Independent ID: 0d7cd9f5-c400-6b4d-a68c-408e462cb3b3
* Content: [Use the Microsoft Graph Toolkit with React - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-react#feedback)
* Content Source: [concepts/toolkit/get-started/use-toolkit-with-react.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toolkit/get-started/use-toolkit-with-react.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @waldekmastykarz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by waldekmastykarz** [comment]
@hb-webdev thank you for taking the time and your feedback.

> Forgive me if I'm blind, but I don't see where it ever explicitly tells you to import the Agenda component (import { Agenda, Login } from '@microsoft/mgt-react';). Luckily the entire code is provided, so this omission is trivial from a practical standpoint.

That's on us. We'll get this fixed. Sorry. Good to hear you were able to use the complete snippet to get unblocked.

> I also wish it provided a step-by-step in the "Create an Azure Active Directory app" section.

We have included a link with more detailed description here:

![image](https://user-images.githubusercontent.com/11164679/122004050-30b66800-cdb4-11eb-9755-c7df87cf1efe.png)

Could it be that you missed it or did you find the instructions in the linked page still unclear?

> Also, I ran into an error after trying to log in the first time telling me I had to make my Azure app multi-tenant, which I did, but that doesn't seem right to me, since I'm only using the app within my organization. (We do use different email domains within the organization though...I'm guessing that might be the issue.)

In this example we're using a multitenant app to simplify the setup process of the walkthrough. Were you able to get the single tenant app to work or are you still stuck?

**Comment by hb-webdev** [comment]
Hi, lol no, I didn't miss the link. But I've missed things like that before so the big red arrow I guess isn't too unwarranted :) I just thought the instructions in the link might be missing some steps I was expected to perform for this guide, i.e., "`grant this app permissions to access specific resources on behalf of the person using your app`". I'm just now realizing that phrase wasn't a step per se, but was just informing me why I needed to follow the steps in the link, and what that will do.

Oh, so setting up an app as single-tenant is more complex. I haven't looked into single-tenant options yet but it sounds like that's something I can Google to get working

**Comment by waldekmastykarz** [comment]
Thank you for clarifying @hb-webdev.

> Oh, so setting up an app as single-tenant is more complex.

If you want to use a single-tenant app, there are two more steps involved in the process:

1. You need to copy the client ID of your app from the Azure Portal
2. You need to pass it to the authentication provider using the `authority` property. I blogged about it here: https://blog.mastykarz.nl/single-tenant-azure-ad-apps-microsoft-graph-toolkit/

Hope it helps
