### ISSUE TITLE
Audience/members not working

### ISSUE THREAD

**Issue by BakkerJan** [microsoftgraph/microsoft-graph-docs#13127]
https://graph.microsoft.com/beta/admin/windows/updates/deployments/{ID}/audience/members is not working for me:

{
    "error": {
        "code": "NotFound",
        "message": "Requested resource 'deployment audience' not found.",
        "innerError": {
            "date": "2021-06-15T07:13:42",
            "request-id": "0043eaad-9be1-46a9-9576-3258c48625f9",
            "client-request-id": "427442c7-de0b-d2f0-4213-bcf5bcda7435"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f917d466-75ee-9562-69f6-279464e8e9f4
* Version Independent ID: f97c22d5-a15e-b1af-b995-61f30df01176
* Content: [List deployment audience members - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/windowsupdates-deploymentaudience-list-members?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/windowsupdates-deploymentaudience-list-members.md)
* Product: **w10**
* Technology: **microsoft-graph**
* GitHub Login: @Alice-at-Microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Alice-at-Microsoft** [comment]
Hi @BakkerJan--Have you added any azureADDevices to the deployment audience members?

**Comment by BakkerJan** [comment]
Yes, by using Intune.

Met vriendelijke groet, Jan Bakker
________________________________
Van: Alice-at-Microsoft ***@***.***>
Verzonden: Tuesday, June 15, 2021 10:34:39 PM
Aan: microsoftgraph/microsoft-graph-docs ***@***.***>
CC: Jan Bakker ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoftgraph/microsoft-graph-docs] Audience/members not working (#13127)


Hi @BakkerJan--Have you added any azureADDevices to the deployment audience members?

**Comment by BakkerJan** [comment]
I tried again, and now the API is giving back error 500
![image](https://user-images.githubusercontent.com/38911727/122928496-38ed4500-d36a-11eb-902b-e6cfbcdabda7.png)

**Comment by Alice-at-Microsoft** [comment]
@BakkerJan Thanks for the update. This is a known issue related to deployments created via Intune, and we are looking into a resolution. The request for audience/members should work for deployments created directly via Graph.
