### ISSUE TITLE
Column Definition default value can't be assigned

### ISSUE THREAD

**Issue by genciT5** [microsoftgraph/microsoft-graph-docs#13131]
I am having an issue with the Column Definition default value property. I can create a column definition, but when I'm trying to assign a default value to it, it won't do so.
I have tried this in .NET SDK for the graph API, regular HTTP Call and also in Graph Explorer. Nothing has worked for so far.

Notice, I can create a column definition, but I just can't assign a default value to it.

I've also tried updating the column definition via PATCH Request using endpoint: **POST: /sites/{siteId}/drive/list/columns/{columnId}** but it still won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43745fd6-2b31-4fe7-14e8-1041b01315c4
* Version Independent ID: ac7bc6b8-6593-ed3c-9e98-93c27e1751f3
* Content: [DefaultColumnValue - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/defaultcolumnvalue?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/defaultColumnValue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/defaultColumnValue.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @daspek
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @genciT5  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/products/graph). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
