### ISSUE TITLE
Add Worksheet - sheet name too long - Validation Exception

### ISSUE THREAD

**Issue by dan-morris-by** [microsoftgraph/microsoft-graph-docs#13159]
Instead of having a generic: InvalidArgument exception thrown with a description to match "The Argument is invalid or missing or has an incorrect format"  Could we have a model validation exception to help the user more easily resolve the problem on their own? The page that got me here doesn't mention this limitation and probably should or at least a way to look it up when developing an API consumer.

reference page: 
  https://docs.microsoft.com/en-us/graph/api/worksheetcollection-add?view=graph-rest-1.0&tabs=http 
API consumed: 
  Worksheets: Add 
msgraph c# command: 
  Microsoft.Graph.GraphServiceClient.Drive[id].Items[id].workbook.worksheets.Add(sheetName).Request().PostAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cf6116b-1dd5-10c5-c9a0-297d0c44782f
* Version Independent ID: 8ff5b2d7-da71-ca20-1bb4-fe1079dfaf57
* Content: [WorksheetCollection: add - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/worksheetcollection-add?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/worksheetcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/worksheetcollection-add.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lumine2008** [comment]
Adding Phoebe for Graph API

**Comment by grangeryy** [comment]
Not sure if this will help: [error handling](https://docs.microsoft.com/en-us/graph/workbook-error-handling)

**Comment by dan-morris-by** [comment]
The error I cited in the initial description came from the Inner Exception (at least 2 Inner Exception inward).  The C# code didn't show me the exact response from the API, but I'm assuming that may be a case for improvement on the GraphServiceClient.  

Main 2 "asks" here are: 

1. Could the GraphServiceClient request return a better response than something so generic as Invalid Argument.  Even if it were just the message itself replacing the one cited above to maybe something like "The Workbook sheet's Name Property is limited to 31 characters or less."  Just something to help me figure out which argument was actually invalid.  

2. Could you document this limitation (Sheet name can not exceed 31 characters) on the page cited that got me to this case in first place?

**Comment by grangeryy** [comment]
Get your point and I've created a feature backlog to track this: 
FEATURE 4664865
