### ISSUE TITLE
Incorrect response for creating list item with Date field

### ISSUE THREAD

**Issue by michaelhan-1** [microsoftgraph/microsoft-graph-docs#13168]
When creating list item with Date field via Graph API.  In response, the value of the date field displayed incorrectly. 

![image](https://user-images.githubusercontent.com/69185043/122350188-9440c100-cf7f-11eb-9831-7b8885dfb3c9.png)

However, when using get listItem for the newly created item, the value of the date field would display correctly.

![image](https://user-images.githubusercontent.com/69185043/122350411-c8b47d00-cf7f-11eb-9240-5fbedc433cae.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6752240-02fb-aa22-d553-e56ab6767c64
* Version Independent ID: 40f28dc8-6f2a-e600-b256-07feaa47cbb2
* Content: [Create a new entry in a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/listitem-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamPrasadMeenavalli** [comment]
If we check the list item using SharePoint REST API - (https://_tenant-name_.sharepoint.com/_api/web/lists/getbytitle('_list-title_')/items(_item-id_), I can see that the datetime value is saved in the wrong format as well.

What we pass in Graph API to create list item - "2021-06-15T16:06:39Z" (which is in UTC format)
What gets saved in SharePoint  - "2021-06-15T03:36:39Z" (Time in UTC format, not same as the request payload)

Looks like the Graph API is not considering the UTC time format and considering it as local time

**Comment by JV-TMCZ** [comment]
Same problem with file metadata. When a file is uploaded (using GraphAPI PUT /sites/{site-id}/drive/items/{item-id}/content). File is uploaded succesfully, but metadata of such file are not correct. 
I run cron job every midnight but sharepoint shows **Modified: 17:03**

See also:
https://docs.microsoft.com/en-us/answers/questions/447051/graphapi-create-sharepoint-listitem-timestamp-form.html?childToView=449907#comment-449907

**Comment by lramosvea** [comment]
Thank you @michaelhan-1 for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
