### ISSUE TITLE
Throttling limits are not counted per tenant if they have the same application 

### ISSUE THREAD

**Issue by romanSlivinskyi** [microsoftgraph/microsoft-graph-docs#13169]
On the throttling page: https://docs.microsoft.com/en-us/graph/throttling#service-specific-limits we see that the global limit applies to all tenants that use the same app - _2000 requests per second_  So, that means if we have a single app installed on different tenants all tenants will share the same global throttling limit. 
Our expectation is that each tenant+app will have its own throttling limit. The current scheme means that one app can not be used for many separate organizations (tenants).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling?source=docs#feedback)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PavloMykhailyshyn** [comment]
It is really important to get clarification on this. Please take this into consideration.

**Comment by xliijoe** [comment]
Yeah this limit doesn't seem to make a lot of sense - after all, one could just create unique apps for every tenant to bypass this restriction, but that would leave a mess of individual applications. It is much more tidy to use a single application across multiple tenants and this global restriction works against that.

**Comment by FaithOmbongi** [comment]
Thank you @romanSlivinskyi , @PavloMykhailyshyn , @xliijoe for posting this issue.

This is a feature request and unfortunately, this platform is only for doc gaps and bugs. I recommend (one of) you post this request at the [Microsoft 365 Developer Platform ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) forum so it can be looked into by the relevant team. 

You can post the link back here so others can amplify your voice. Looks to be a popular request. Closing this issue for now.
