### ISSUE TITLE
Code not working completely

### ISSUE THREAD

**Issue by isaaciss** [microsoftgraph/microsoft-graph-docs#13173]
[Enter feedback here]

When i try to execute this code, I receive the message "Insufficient privileges to complete the operation"

Where should I give this permissions?

in code comment, I read 
// OAuth flow and assumes that an administrator has consented to the application.

So I ask, how to consent the application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef52833-8b23-b9cd-4337-73eec3c34f4d
* Version Independent ID: 9b012e4f-93b3-bda8-0e35-1c9c6326295c
* Content: [Create a Microsoft Graph client - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=PHP)
* Content Source: [concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/create-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MIchaelMainer** [comment]
I highly suggest that you try this tutorial: https://github.com/microsoftgraph/msgraph-training-phpapp

**Comment by lramosvea** [comment]
Thank you @isaaciss for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
