### ISSUE TITLE
Documentation on encoding a Graph URL 

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/microsoft-graph-docs#13179]
Recently, I came across an issue with encoding # in a Graph URL. 
# is encoded as %23 and the following URL errors out: 
https://graph.microsoft.com/v1.0/users?$count=true&$search=%22displayName:LidiaH^1!%23@M365x283484.OnMicrosoft.com.

I found out that for v1.0 you will have to double encode the string.
Therefore, letter # will be encoded as %2523. 
Example: 
https://graph.microsoft.com/v1.0/users?$search="displayName:%2523"&$count=true.

Example: 
https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/1197/files

It would be worth documenting how to encode a Graph URL with characters such as #. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7415c6-cfbb-27a1-109c-78aa85e69cef
* Version Independent ID: dfd0a8f0-b01d-baab-67aa-a64eb39d3224
* Content: [Use the $search query parameter in Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-query-parameter#using-search-on-directory-object-collections)
* Content Source: [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/search-query-parameter.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @nikithauc for raising this issue and highlighting this documentation gap.

I've opened an internal work item for this required guidance. Closing this issue here.
