### ISSUE TITLE
$count parameter not supported on microsoft.graph.user

### ISSUE THREAD

**Issue by cchannon** [microsoftgraph/microsoft-graph-docs#13195]
The endpoint referenced in this page, "https://graph.microsoft.com/v1.0/groups/{id}/members/microsoft.graph.user/$count" returns the error:

 "code": "Request_BadRequest",
    "message": "$count is not currently supported.",

$count parameter on "https://graph.microsoft.com/v1.0/groups/{id}/members" works just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3edbef-651c-47df-1322-9f39abd35adc
* Version Independent ID: 8774189d-c527-579d-9104-39d538159aff
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @cchannon for raising this issue.

Use of `$count` on directory objects like groups requires setting the **ConsistencyLevel** header to `eventual`. `$count `and **ConsistencyLevel** are a set of parameters referred to advanced query parameters in Azure AD. You can refer to more in [Advanced query capabilities on Azure AD directory objects](https://docs.microsoft.com/en-us/graph/aad-advanced-queries).

Your query would be:
[https://graph.microsoft.com/v1.0/groups/{groupId}/members/microsoft.graph.user/$count](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%2F{groupId}%2Fmembers%2Fmicrosoft.graph.user%2F%24count&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
