### ISSUE TITLE
Odata.type annotation incorrectly specified

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs#13191]
Specified odata.type `EducationResource` at the last line of the json object supplied is an incorrect type since it's an abstract class. Please provide correct odata.type (seems like it should have been EducationSubmissionResource).

Supplied http body:
```http
POST https://graph.microsoft.com/v1.0/education/classes/acdefc6b-2dc6-4e71-b1e9-6d9810ab1793/assignments/ad8afb28-c138-4ad7-b7f5-a6986c2655a8/submissions/fbe51c90-78b7-418a-b5f3-871bf8d8d21e/resources
Content-type: application/json
Content-length: 1097

{
  "assignmentResourceUrl": "https://graph.microsoft.com/v1.0/drives/b!8-QjN2tsv0WyGnTv7vOvnQkmGHbbeMNLqYKONmHLVnvCVmBYIGpeT456457AdW9f/items/017NJZI25NOB5XZNLABF7646XAMDZTQQ6T",
  "resource": {
      "@odata.type": "#microsoft.graph.educationWordResource",
      "displayName": "Report.docx",
      "createdDateTime": "2017-10-21T07:52:53.9863696Z",
      "createdBy": {
          "application": null,
          "device": null,
          "user": {
              "id": "63cc91d2-59c7-4732-9594-35b91a26b340",
              "displayName": null
          }
      },
      "lastModifiedDateTime": "2017-10-21T07:52:53.9863696Z",
      "lastModifiedBy": {
          "application": null,
          "device": null,
          "user": {
              "id": "63cc91d2-59c7-4732-9594-35b91a26b340",
              "displayName": null
          }
      },
      "fileUrl": "https://graph.microsoft.com/v1.0/drives/b!8-QjN2tsv0WyGnTv7vOvnQkmGHbbeMNLqYKONmHLVnvCVmBYIGpeTZ_iul5AdW9f/items/017NJZI27BCN2QI2H7HJGLIVPXR6SD2DH6"
  },
  "@odata.type": "microsoft.graph.educationResource"
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b7df450-52a9-52fb-9244-2b881adf5e24
* Version Independent ID: f675da86-b8a3-4a6e-f28c-18bad83a7aa3
* Content: [Create educationSubmissionResource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationsubmission-post-resources?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/educationsubmission-post-resources.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationsubmission-post-resources.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @sharad-sharma-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cristobal-buenrostro** [comment]
Hi @fey101 , looking into this issue...
Can you please share an example of the request you are trying to perform and its response body too?
It seems that the **resource** and **odata.type** properties can vary according to the resource type to be loaded.

**Comment by cristobal-buenrostro** [comment]
Hi @fey101 
The documentation has been updated, can you please take a look and try your request based on the resource type?
Please let me know any other question.
