### ISSUE TITLE
Posting a message with mentions in a teams channel fails since yesterday

### ISSUE THREAD

**Issue by advdberg** [microsoftgraph/microsoft-graph-docs#13202]
It looks like something is broken in posting team channel messages since yesterday. On all of our (and customer) tenants this now gives a 400 Bad request error without any detailed information.

Did we miss a change in here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa6130b-e7ac-9795-9593-f0cef62ff0d4
* Version Independent ID: 7bf7c3d2-7693-7d24-e9c0-6f0c51cb1eaa
* Content: [Send chatMessage in a channel or a chat - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Can you share client-request-Id and timestamp of a failed request?

**Comment by advdberg** [comment]
@RamjotSingh I will see if I can retrieve these

**Comment by RamjotSingh** [comment]
If you can please also share the request body.

**Comment by advdberg** [comment]
@RamjotSingh hereby the requested information

**Request:**

Post: POST /v1.0/teams/a64c35dc-7caa-4b21-b9ee-58cf63069d1d/channels/19:Bae2yvv58gmSGOEqx8R-MjFqg5gGfqjxwl3RAtI3Du81@thread.tacv2/messages HTTP/1.1
client-request-id: d36e38b7-8c9a-44f7-80c6-7a95263f461b
Date: Sun, 20 Jun 2021 12:20:24 GMT

**Body**
{​​​​​​​​
    "subject":  "Welcome to your team (progress report)",
    "body":  {​​​​​​​​
                 "contentType":  "html",
                 "content":  "Welcome \u003cat id=\"0\"\u003eP365RegressionTest  English  2305 (P365RegressionTestEnglish2305)\u003c/at\u003e.\u003cbr/\u003e\u003cbr/\u003eThis team is currently still under construction. Your team will be configured in the next few minutes. We\u0027ll keep you posted on the progress in this thread."
             }​​​​​​​​,
    "mentions":  [
                     {​​​​​​​​
                         "mentionText":  "P365RegressionTest  English  2305 (P365RegressionTestEnglish2305)",
                         "id":  0,
                         "mentioned":  {​​​​​​​​
                                           "conversation":  {​​​​​​​​
                                                                "conversationIdentityType":  "team",
                                                                "conversationIdentityType@odata.type":  "#Microsoft.Teams.GraphSvc.conversationIdentityType",
                                                                "displayName":  "P365RegressionTest  English  2305 (P365RegressionTestEnglish2305)",
                                                                "id":  "a64c35dc-7caa-4b21-b9ee-58cf63069d1d"
                                                            }​​​​​​​​
                                       }​​​​​​​​
                     }​​​​​​​​
                 ]
}​​​​​​​​

**Comment by advdberg** [comment]
To be complete, this used to work fine with the identical message body until 2 days ago. We saw it failing in our regression tests since then without any code changes from our side.

**Comment by RamjotSingh** [comment]
Can you remove the `"conversationIdentityType@odata.type": "#Microsoft.Teams.GraphSvc.conversationIdentityType",`. That was never required. When writing you should not be sending OData type unless you intend to overwrite the object.

**Comment by RamjotSingh** [comment]
Here is the sample which tells how to specify identity type information
https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http#example-2--a-user-in-a-channel-message

**Comment by advdberg** [comment]
@RamjotSingh there's no (positive) effect on the call when we remove the OData type parameter from the call. Any other thoughts? Maybe need more info?
