### ISSUE TITLE
Behavior of password profile after resetting password for an user.

### ISSUE THREAD

**Issue by Shweta-1405** [microsoftgraph/microsoft-graph-docs#13208]
In the Microsoft 365 admin center, for a given active user, I reset their password, making sure that I check the box labeled "Require this user to change their password when they first sign in".

![image](https://user-images.githubusercontent.com/83591574/122749092-8c985980-d2aa-11eb-83d9-8ca8d105ad21.png)

So far so good, now I go ahead and click the button to reset the password. I check user properties using the graph api (v1.0), using the endpoint https://graph.microsoft.com/v1.0/users?$select=displayName,passwordProfile
And as expected I see this:

![image](https://user-images.githubusercontent.com/83591574/122749210-af2a7280-d2aa-11eb-90f2-4a44500c1495.png)

But when I reset the password, and don't check the box to require the user to change their password, I get this in the graph api:

![image](https://user-images.githubusercontent.com/83591574/122749274-c701f680-d2aa-11eb-8da0-d08fdc01cf24.png)

 **PasswordProfile is null by default, so why does it stay this way when the password is reset, why wouldn't it show "forceChangePasswordNextSignIn" as false instead**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Shweta-1405 for raising this issue.

**forceChangePasswordNextSignIn**, whether set to `true` or `false`, applies only to the next sign in, which you already accomplished by the reset. After the reset, your **passwordProfile** settings have already been applied and the property is set to `null`.

`"forceChangePasswordNextSignIn": false` means either no password reset at next sign in or it could mean you'll be using the custom policies or user flows to reset the password.

**Comment by Shweta-1405** [comment]
@FaithOmbongi 
Thanks for your answer, could you expand on your statement

 "forceChangePasswordNextSignIn": false means either no password reset at next sign in or ...

How do I get to the state "no password reset at next sign in"? For my current understanding, that means, the second checkbox labeled "Require this user to change their password when they first sign in" is not checked when an admin resets a user's password, which I tried, as demonstrated in the original question. At no point thus far have I been able to see the forceChangePasswordNextSignIn property set to false. Note that I'm checking the graph api response before a user logs in with the automatically generated password.

Is there another setting I'm missing elsewhere? I'm not using any "custom policies or user flows" to reset the password.

**Comment by FaithOmbongi** [comment]
@Shweta-1405 

>  At no point thus far have I been able to see the forceChangePasswordNextSignIn property set to false. Note that I'm checking the graph **api response** before a user logs in with the automatically generated password.

I believe this is your major issue? Expecting to see `"forceChangePasswordNextSignIn": false,` **in the response object?** Correct me if I'm wrong.

Short answer: you won't. `"forceChangePasswordNextSignIn": false,` is only in your request body.

Hope this clarifies things.
