### ISSUE TITLE
isDeliveryReceiptRequested and data type mismatch during deserialization.

### ISSUE THREAD

**Issue by EricWilson-BluePrism** [microsoftgraph/microsoft-graph-docs#13214]
Not sure what the best way is to raise this issue, so here I am. 

I noticed some peculiar behavior with the Outlook portion of the Graph API, specifically as it pertains to retrieving message information. In the default template (this can be seen in Graph Explorer) when you retrieve the list of messages for an inbox there's an element in the JSON for every message titled **isDeliveryReceiptRequested**. In the vast majority of cases, this element is set to **null** even though it is implied boolean. This causes issues when deserializing the JSON using natove Newtonsoft or other libraries as they interpret the field as System.String due to presence of the null value.

I'd suggest changing the handling of Outlook messages in Graph such that if a field has an implied data type it should always be set to some default value of that implied type. In this case, the isDeliveryReceiptRequested element should always be set to false unless specifically set to true for a message where the receipt was requested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b62033d-29c1-f327-e6aa-85cdf02914b2
* Version Independent ID: e58ebce1-e656-51d4-4d08-9ac3cdb98a52
* Content: [List messages - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-messages.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @EricWilson-BluePrism  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
