### ISSUE TITLE
typo in permissions table

### ISSUE THREAD

**Issue by alexandvvvvv** [microsoftgraph/microsoft-graph-docs#13229]
[Enter feedback here]
typo in Permissions table
correct permission is 
DeviceManagementManagedDevices.PrivilegedOperations.All

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bf12047-b65e-54e6-6e3e-ce9ecc973da2
* Version Independent ID: ebfe3cc3-ad6d-5c12-c385-c9ad1046305a
* Content: [rebootNow action - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-rebootnow?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-rebootnow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-devices-manageddevice-rebootnow.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks.  I've filed a bug for our team to make the change.
