### ISSUE TITLE
Can't query for PolicyStatusDetails of AutoPilotEvent - Error 400

### ISSUE THREAD

**Issue by MaikKoster** [microsoftgraph/microsoft-graph-docs#13238]
Trying to query the PolicyStatusDetails for an AutoPilot event as documented in https://docs.microsoft.com/en-us/graph/api/intune-troubleshooting-devicemanagementautopilotpolicystatusdetail-list?view=graph-rest-beta, but am always getting a 400 Response. I can successfully query the corresponding AutoPilotEvent as documented at https://docs.microsoft.com/en-us/graph/api/intune-troubleshooting-devicemanagementautopilotevent-get?view=graph-rest-beta. So the URL and ID of the event seem to be correct. 

`{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation with http verb GET for request /StatelessCustomerDataMTService/9d84eeca-ffff-8665-0655-062010252353/deviceManagement/autopilotEvents('2f3841c5-3f3c-42cf-a7c9-db852b040659')/policyStatusDetails.",
        "innerError": {
            "date": "2021-06-22T19:34:21",
            "request-id": "52f401a2-06f1-4256-8af3-06d10e395f88",
            "client-request-id": "6e5de84b-4b40-dda6-1a0f-c8065177a165"
        }
    }
}`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4f8b16d3-3509-457f-4d45-c9ebc02e73db
* Version Independent ID: 7e1f2838-a694-928f-57fc-5d4b37bad053
* Content: [deviceManagementAutopilotPolicyStatusDetails auflisten - Microsoft Graph beta](https://docs.microsoft.com/de-de/graph/api/intune-troubleshooting-devicemanagementautopilotpolicystatusdetail-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-troubleshooting-devicemanagementautopilotpolicystatusdetail-list.md](https://github.com/microsoftgraph/microsoft-graph-docs.de-DE/blob/main/api-reference/beta/api/intune-troubleshooting-devicemanagementautopilotpolicystatusdetail-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for your feedback.  Sometimes our automated document creation tool picks up endpoints like this that report 400.  The best way to verify the URL is to use a network trace (F12 developer mode in the browser or Fiddler, etc) and see the Intune console API call.
