### ISSUE TITLE
Number of users per page

### ISSUE THREAD

**Issue by lipalath-ms** [microsoftgraph/microsoft-graph-docs#13233]
How many users are returned per page? Please let me know. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/paging)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @lipalath-ms for raising this issue. Paging works differently across different Azure AD resources. One API may return 10 by default and maximum; while another may return 100 by default and 250 maximum. Kindly refer to the resource's API page to see page limits for the API.
