### ISSUE TITLE
Presence endpoints availability for GCC-High

### ISSUE THREAD

**Issue by DakotaWray2** [microsoftgraph/microsoft-graph-docs#13235]
In GCC-High Presence.Read and Presence.Read.All API delegated permissions are available in AAD.

Endpoints return "Request_ResourceNotFound" --- "Resource 'presence' does not exist or one of its queried reference-property objects are not present."

Is this still not available in GCC-High?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a86fbdb8-fb55-1b9f-36b8-210a9b960d86
* Version Independent ID: 01e364fb-9af7-8fe6-a662-185ed233132d
* Content: [Get presence - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/presence-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mkhribech
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
@elvinyang-msft can you help answer this?

**Comment by elvinyang-msft** [comment]
@DakotaWray2 no, the presence APIs are currently only available on public cloud.

**Comment by DakotaWray2** [comment]
@elvinyang-msft Any plans for implementation?

**Comment by mkhribech** [comment]
@DakotaWray2  we dont have a timeline yet but if you provide more details I can log a request to add it to the pipeline

**Comment by DakotaWray2** [comment]
@mkhribech As our office transitions to a hybrid in-office approach we would find it beneficial to aggregate presence data. In my use case it would be for an office map visualization to, at a glance, see who is teleworking on a given day by simply adding 'telework' to their status message.
