### ISSUE TITLE
General availability but still in Beta?

### ISSUE THREAD

**Issue by TobiasAT** [microsoftgraph/microsoft-graph-docs#13240]
On Build you informed the 1:1 chat export API is GA, so this page / API. But this API is still not available on V1. What does GA means for you? See https://developer.microsoft.com/en-us/microsoft-365/blogs/whats-new-in-microsoft-graph-at-build-2021/

Best regards
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e82011f5-de8b-66ea-b454-98b7a62b7ec9
* Version Independent ID: d8ae4a6f-4a10-8937-bdc6-52281d27f653
* Content: [chats: getAllMessages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chats-getallmessages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
Catching up -- sorry, we got the date wrong. We pre-record the Build videos, and found some issues that took a while to resolve.
