### ISSUE TITLE
403 for upload session URL with app-only token

### ISSUE THREAD

**Issue by legsak1mbo** [microsoftgraph/microsoft-graph-docs#1324]
I'm trying to use app-only mode to upload files to OneDrive for business. Following the guidance in https://github.com/microsoftgraph/microsoft-graph-docs/issues/495 I've ensured that the authorisation header is removed from the upload chunk requests (so no 401) but I get a 403 instead.

**Comment by RockJumper** [comment]
I'm having the same issue. I get a token with the client credentials flow and create an upload session.
Then any put or delete request i send to the upload Url returns a 403.

**Comment by wbreza** [comment]
+1

**Comment by legsak1mbo** [comment]
Any update on this? All other file operations work really nicely, it's just the upload session that seems to be a problem.

**Comment by jmacneill** [comment]
I too have the same problem.  The error in the response header is "X-MSDAVEXT_Error: 917656; Access+denied.+Before+opening+files+in+this+location%2c+you+must+first+browse+to+the+web+site+and+select+the+option+to+login+automatically."
But if you're using the URL returned, you shouldn't need to authenticate.  I get the same error if I just try to check the status of the upload session.  I'm trying to use an app token and we're using OneDrive for Business.

Here is my code (you'll need to add a reference to System.Web.Extensions.dll and replace REDACTED with your own info):
Imports System.IO
Imports System.Web.Script.Serialization

Module Module1
    Private dtAccessToken As DateTime = "1/1/1900"
    Private strAccessToken As String = ""
    Private strUserName As String = "REDACTED"
    Private strUploadFile As String = "C:\Applications\OneDrive\test.pdf"
    Private strTokenURL As String = "https://login.microsoftonline.com/REDACTED/oauth2/v2.0/token"
    Private strAppSecret As String = "client_id=REDACTED&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=REDACTED&grant_type=client_credentials"

    Sub Main()
        GetAccessToken()

        Dim driveID As String = GetDriveID(strAccessToken, strUserName)
        Dim strURL As String = "https://graph.microsoft.com/v1.0/drives/" & driveID & "/root:/test.pdf:/createUploadSession"
        Dim rsp As String = ""
        Dim wc As New Net.WebClient()

        wc.Headers.Add("Authorization", "Bearer " & strAccessToken)
        wc.Headers.Add("Content-Type", "application/json")

        rsp = wc.UploadString(strURL, "POST", "{""item"": {""@microsoft.graph.conflictBehavior"": ""rename""}}")

        Dim jss As New JavaScriptSerializer
        Dim objRsp As Object = jss.Deserialize(Of Object)(rsp)
        Dim strUploadUrl As String = ""

        If objRsp.TryGetValue("uploadUrl", strUploadUrl) Then
            Dim strm As New IO.FileStream(strUploadFile, FileMode.Open)
            Dim iChunk As Integer = 3145728
            Dim iLen As Integer = strm.Length
            Dim byt(iLen) As Byte

            strm.Read(byt, 0, strm.Length)

            Dim wr As Net.HttpWebRequest = Net.WebRequest.Create(strUploadUrl)

            wr.ContentLength = iLen
            wr.Headers.Add("Content-Range", "bytes 0-" & iLen - 1 & "/" & iLen)
            wr.Method = "PUT"


            Console.WriteLine("bytes 0-" & iLen - 1 & "/" & iLen)

            Dim rs As IO.Stream = wr.GetRequestStream
            rs.Write(byt, 0, iLen)

            Dim rspe As Net.WebResponse = wr.GetResponse

            rs.Close()
        End If
    End Sub

    Private Sub GetAccessToken()
        Dim wc As New Net.WebClient()

        wc.Headers.Add("Content-Type", "application/x-www-form-urlencoded")

        Dim strReturn = wc.UploadString(strTokenURL, strAppSecret)
        Dim jss As New JavaScriptSerializer
        Dim objRet As Object = jss.Deserialize(Of Object)(strReturn)

        strAccessToken = objRet("access_token").Replace(vbCrLf, "").Replace(vbNewLine, "")
        dtAccessToken = Now()
    End Sub

    Private Function GetDriveID(strToken As String, strUser As String) As String
        Dim strDriveID As String = ""

        Try
            Dim wc As New Net.WebClient()

            wc.Headers.Add("Authorization", "Bearer " & strToken)

            Dim strResponse As String = wc.DownloadString("https://graph.microsoft.com/v1.0/users/" & strUser & "/drives")
            Dim jss As New JavaScriptSerializer
            Dim objContents As Object = jss.Deserialize(Of Object)(strResponse)

            For Each obj As Dictionary(Of String, Object) In objContents("value")
                Dim strContent As Object = Nothing

                If obj.TryGetValue("id", strContent) Then
                    strDriveID = obj.Item("id")
                End If
            Next
        Catch ex As Exception

        End Try

        Return strDriveID
    End Function

End Module

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
