### ISSUE TITLE
Missing Teams specific persmissionlevels

### ISSUE THREAD

**Issue by RoelVB** [microsoftgraph/microsoft-graph-docs#13281]
We got Teams specific permissions (like `Team.Create` etc.), which is great, but I've noticed two things that are missing in this permissionlevels.
For deleting or cloning Teams we still need `Group.ReadWrite.All`, which gives full access to all groups.

Is this how it's mean to work or are there Teams specific permissions coming?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebf93d15-35e5-4455-c291-efbacda54fd9
* Version Independent ID: 551bdd07-9f9f-1ad5-71b2-d7d7133755ec
* Content: [Delete group - Microsoft Graph API - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-delete.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @RoelVB for raising this issue.

Yes, this working is correct. A team is always tied to a Microsoft 365 group, so you need the _Group.ReadWrite.All_ permission for those actions that will affect the group.

If you'd like to propose for deleting and closing teams to require lesser privileges, you can file a feature request at the [Microsoft 365 Developer Platform ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) forum and other users can amplify your voice.
