### ISSUE TITLE
Update AvailableForTagging

### ISSUE THREAD

**Issue by nemegeerm** [microsoftgraph/microsoft-graph-docs#13303]
[Enter feedback here]
Is there a possibility to update the "available for tagging" indicator when updating a term ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a75dba-2ed5-92b5-0c73-2db583b996b1
* Version Independent ID: 398f2fcc-0ec5-13c5-046e-deed4d5d085f
* Content: [Update term - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/termstore-term-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/termstore-term-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/termstore-term-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @mohitpcad
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @nemegeerm for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
