### ISSUE TITLE
Can I know is it possible to write unit tests to check page iterator with multiple pages?

### ISSUE THREAD

**Issue by piyumi25** [microsoftgraph/microsoft-graph-docs#13315]
I have implemented page iterator functionality to get list of graph subscriptions. But I need to know how do I can test it when writing unit tests using mock.

```
subscriptionCollectionPage = await _graphServiceClient.Subscriptions
							.Request()
							.GetAsync();

var pageIterator = PageIterator<Subscription>
				 .CreatePageIterator(_graphServiceClient, subscriptionCollectionPage, (subscription) =>
					 {
						subscriptions.Add(subscription);
						 return true;
						});

await pageIterator.IterateAsync();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d558deeb-3492-230e-b2d9-8d9efeb6f97f
* Version Independent ID: bb2e0da9-acb9-0ffa-7fb6-d1bb534bfd20
* Content: [Page through a collection using the Microsoft Graph SDKs - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/paging?tabs=csharp)
* Content Source: [concepts/sdks/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @piyumi25  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sdk.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
