### ISSUE TITLE
Incorrect documentation for enableSmsSignIn

### ISSUE THREAD

**Issue by mattdurant** [microsoftgraph/microsoft-graph-docs#13328]
Documention is incorrect:

`POST /users/{id | userPrincipalName}/authentication/phoneMethods/{id}/enableSmsSignIn`

This call does _not_ work with userPrincipalName.  It returns a 204 and doesn't enable.  The associated call to disable also doesn't work with UPN.  Both only return 200 and do anything if passing in the User id (GUID).
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b115f94-4086-e99f-f814-34c72f60d350
* Version Independent ID: 8c5a793a-2e82-bb70-a2fa-3dada74aa4fa
* Content: [phoneAuthenticationMethod: enableSmsSignIn - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/phoneauthenticationmethod-enablesmssignin.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @mattdurant for raising this issue.

Unfortunately, I'm unable to replicate it as using the UPN works for both [/phoneMethods/enableSmsSignin](https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-enablesmssignin?view=graph-rest-beta&tabs=http) and [/phoneMethods/disableSmsSignin](https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-disablesmssignin?view=graph-rest-beta&tabs=http) actions. I get a `204 No Content` ack on both actions and a
- _"smsSignInState": "notConfigured"_ after /phoneMethods/disableSmsSignIn
- _"smsSignInState": "ready"_ and /phoneMethods/enableSmsSignIn

If you're still facing this issue, kindly post it at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) to get troubleshooting help from our Engineers.
