### ISSUE TITLE
Deep links to the teams app in the Activity Feed notification don't work if they contain context param value with "=" symbol

### ISSUE THREAD

**Issue by maxmurash** [microsoftgraph/microsoft-graph-docs#13355]
I send an Activity Feed notification with a deep link to a personal teams app. context.subEntityId value contains string with "=" in it.

Link has next structure: 
`https://teams.microsoft.com/l/entity/appId/entityId?context={"subEntityId":"value=value"}`

**The issue I faced:** Deep link doesn't work when user click on the Activity Feed notification.

**Workaround I found:** I have to encode "context" value twice.

Here are examples:

Context value I want to send:
`?context={"subEntityId":"/record/BMIN-21050369?tabKey=EditRecordDetails"}`

**Normal deep link that works in browser with correct context, but doesn't work in Active Feed notification at all:**

https://teams.microsoft.com/l/entity/4787f4d9-e2af-4b21-b66d-efbcff4478f8/ABC?context=%7B%22subEntityId%22%3A%22%2Frecord%2FBMIN-21050369%3FtabKey%3DEditRecordDetails%22%7D

Built context value using:
`encodeURIComponent("{\"subEntityId\":\"/record/BMIN-21050369?tabKey=EditRecordDetails\"}")`

**Adjusted link that works in Active feed notification and send subEntityId to the app correctly, but doesn't send subEntityId value correctly in browser:** 

https://teams.microsoft.com/l/entity/4787f4d9-e2af-4b21-b66d-efbcff4478f8/ABC?context=%257B%2522subEntityId%2522%253A%2522%252Frecord%252FBMIN-21050369%253FtabKey%253DEditRecordDetails%2522%257D

Built context value using:
`encodeURIComponent(encodeURIComponent("{\"subEntityId\":\"/record/BMIN-21050369?tabKey=EditRecordDetails\"}"))`

JSON body example I send to the graph API:

```
{
    "topic": {
        "source": "text",
        "value": "See the record",
        "webUrl": "https://teams.microsoft.com/l/entity/4787f4d9-e2af-4b21-b66d-efbcff4478f8/ABC?context=%257B%2522subEntityId%2522%253A%2522%252Frecord%252FBMIN-21050369%253FtabKey%253DEditRecordDetails%2522%257D"
    },
    "activityType": "freeTextActivity",
    "previewText": {
        "content": "Click on the item to see the record"
    },
    "chainId": 100,
    "recipient": {
        "@odata.type": "microsoft.graph.aadUserNotificationRecipient",
        "userId": "14922fc1-b1f9-4f77-9ed0-43cc6bf330f6"
    },
    "templateParameters": [
        {
            "name": "body",
            "value": "Test notification 1"
        }
    ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9948c753-b761-228d-4915-9c26b47dd6a3
* Version Independent ID: 5b4f132c-3409-885d-9a1a-848bcd7c3c7c
* Content: [userTeamwork: sendActivityNotification - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/userteamwork-sendactivitynotification.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @eddie-lee-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maxmurash** [comment]
Unfortunately, workaround I found doesn't work on mobile devices. Mobile devices don't parse context object at all if it is double encoded.

**Comment by lramosvea** [comment]
Thank you @maxmurash for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-teamwork.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
