### ISSUE TITLE
Missing "SocialIdp" ServicePrincipalType

### ISSUE THREAD

**Issue by ZachEdwards7** [microsoftgraph/microsoft-graph-docs#13387]
The servicePrincipalTypes listed does not include information on "SocialIdp" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcef076-0419-d0c9-1d49-c7c9a95317ce
* Version Independent ID: 0cd73e6b-f547-c257-4ffc-faeb4cfd1abf
* Content: [servicePrincipal resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/serviceprincipal.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ZachEdwards7 for raising this issue. Yes, you're right. This is the servicePrincipalType for O365 LinkedIn Connection. I'll confirm this with the team and raise a PR to update the documentation.
