### ISSUE TITLE
Can't create accessPackageResourceRoleScopes for SharePoint Site, "Resource was not found"

### ISSUE THREAD

**Issue by kellybeazley** [microsoftgraph/microsoft-graph-docs#13399]
Hi,

I am trying to add a role to a Share point site using https://docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&tabs=http

There is no example in the docs to do this with a sharepoint site or application. I am able to do this with an AAD group fine.

POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/access-package-id /accessPackageResourceRoleScopes

The resource already exists in the catalog

My request body is not working.

{
"accessPackageResourceRole": {
"originId": "https://sharepoint.com/sites/mysite",
"displayName": "My Site Members",
"originSystem": "SharePointOnline",
"accessPackageResource": {
"id": "resource-id from GET resources in catalog",
"resourceType": "SharePoint Online Site",
"originId": "https://.sharepoint.com/sites/mysite",
"originSystem": "SharePointOnline"
}
},
"accessPackageResourceScope": {
"originId": "https://******.sharepoint.com/sites/mysite",
"originSystem": "SharePointOnline"
}
}

I get "the resource was not found".

What is the format for the request body for creating a role for a sharepoint site in an access package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 795df5be-978b-2f94-0e0b-d446af29e931
* Version Independent ID: f8abea93-7b85-1306-9975-c4726fa86d98
* Content: [Create accessPackageResourceRoleScope - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accesspackage-post-accesspackageresourcerolescopes.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
> What is the format for the request body for creating a role for a sharepoint site in an access package?

The originId in the resource role would be the identifier of the role rather than of the site. After you have requested to add a site as a resource to a catalog, you could then retrieve originIds for each of the site's available roles,

```http
GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageCatalogs/beedadfe-01d5-4025-910b-84abb9369997/accessPackageResourceRoles?$filter=(originSystem+eq+%27SharePointOnline%27+and+accessPackageResource/id+eq+%2753c71803-a0a8-4777-aecc-075de8ee3991%27)&$select=displayName,originId
```
where the response would be an array with the originId for each of the site roles, e.g.,

```json
{
    "value": [
        {
            "displayName": "Contributors",
            "originId": "4"
        }

   ]
}
```

Then you would send the POST to create the resource role scope with that originId, e.g.,

```json
{
    "accessPackageResourceRole": {
        "originId": "4",
        "originSystem": "SharePointOnline",
        "accessPackageResource": {
            "id": "53c71803-a0a8-4777-aecc-075de8ee3991"
        }
    },
    "accessPackageResourceScope": {
        "id": "5ae0ae7c-d0a5-42aa-ab37-1f15e9a61d33",
        "originId": "https://microsoft.sharepoint.com/portals/Community",
        "originSystem": "SharePointOnline"
    }
}
```
#13422

**Comment by kellybeazley** [comment]
Thanks this worked. However I had to get the accessPackageResourceScope id from an existing access package. How would you get this id if it doesn't already exist in another access package? For groups it uses the same id as the accessPackageResource but that doesn't work for sharepoint sites?

**Comment by kellybeazley** [comment]
But I figured out if I use this `GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageCatalogs/{id}/accessPackageResources?$count=true&$expand=accessPackageResourceScopes,accessPackageResourceEnvironment&$orderby=displayName`

I can get all the resource scopes for every resource in the catalog. I only found this out using developer tools on chrome. This doesn't look like this is on the documentation anywhere?
