### ISSUE TITLE
Incorrect results for OData Query parameters

### ISSUE THREAD

**Issue by piyumi25** [microsoftgraph/microsoft-graph-docs#13429]
I have used following code to filter categories. But it returns all categories without any filtering.

`return (await _graphServiceClient.Users[exchangeUserId]
					.Outlook.MasterCategories
					.Request()
					.Filter($"displayName eq 'Synced'")
					.GetAsync())
					.ToList();`

**Comment by lramosvea** [comment]
Thank you @piyumi25 for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/products/graph). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
