### ISSUE TITLE
Link to invitedUserMessageInfo broken

### ISSUE THREAD

**Issue by antonGritsenko** [microsoftgraph/microsoft-graph-docs#13437]
Hello

Link to page for invitedUserMessageInfo type broken:
``[invitedUserMessageInfo](invitedusermessageinfo.md``

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0170d-e214-ce6f-b7b4-589960e9962d
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/invitation.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @Sammak
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @antonGritsenko for raising this issue. I'll raise a PR to fix the page.
