### ISSUE TITLE
Forbidden error on Application Token OnlineMeeting

### ISSUE THREAD

**Issue by kashish-arora** [microsoftgraph/microsoft-graph-docs#13454]
I am getting Forbidden error on using Microsoft Teams Online Meeting API.

I have all the permissions Delegated, Application, ReadWrite, ReadWrite.All- everything.

![1](https://user-images.githubusercontent.com/43489670/125258111-a6faab80-e31b-11eb-9820-a90ebd2c41b8.PNG)
![2](https://user-images.githubusercontent.com/43489670/125258117-a8c46f00-e31b-11eb-86be-8523b008e0fb.PNG)
![3](https://user-images.githubusercontent.com/43489670/125258121-a9f59c00-e31b-11eb-8c3c-96908d73586b.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=javascript)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mkhribech
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @kashish-arora I checked our log with the info provided in your 2nd screenshot and it says you didn't have the required permission in the token. Can you send a decoded token you were using? (feel free to redact the part you see necessary)

**Comment by kashish-arora** [comment]
This is the payload data that I am receiving in the decoded token:

{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/{{tenant-ID}}/",
  "iat": 1626236503,
  "nbf": 1626236503,
  "exp": 1626240403,
  "aio": "E2ZgYGgOUEyYueMlD2dZ2IsOnp6DAA==",
  "app_displayname": "TeamApp",
  "appid": "{{client-id}}",
  "appidacr": "1",
  "idp": "https://sts.windows.net/{{tenant-id}}/",
  "idtyp": "app",
  "oid": "fbd2405c-6448-443f-b914-dd3b8095f092",
  "rh": "0.AXAAPoK7p73kk0uV5SYPFJjOtRLTKUfaanRAifV0kR_6xK5wAAA.",
  "sub": "fbd2405c-6448-443f-b914-dd3b8095f092",
  "tenant_region_scope": "AS",
  "tid": "{{tenant-id}}",
  "uti": "PlyGWxFUQEKtN-dk_k4SAA",
  "ver": "1.0",
  "wids": [
    "0997a1d0-0d1d-4acb-b408-d5ca73121e90"
  ],
  "xms_tcdt": 1616742256
}

This is the header of the decoded token:

{
  "typ": "JWT",
  "nonce": "c-MHsjE7aa9fC58R5rZZ9Z-WwnZUXolWazNxUKDOq84",
  "alg": "RS256",
  "x5t": "nOo3ZDrODXEK1jKWhXslHR_KXEg",
  "kid": "nOo3ZDrODXEK1jKWhXslHR_KXEg"
}

I hope I haven't entered anything confidential.

**Comment by frankpeng7** [comment]
Hi @kashish-arora it doesn't seem like this token contains the needed permission. In an accepted token, there'd be a claim named `scp` which contains all the granted Graph permission. You can try obtaining a correct token in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) (under the "Access Token" tab) and decode it to see the format.

**Comment by kashish-arora** [comment]
Oh okay, can you please guide me how to obtain the correct permissions? Where do I go and what do I do?

**Comment by frankpeng7** [comment]
Also I noticed in the `idtyp` claim it has `app` which means this is an app token. Can you confirm if you were trying with a delegated token or an app token?

**Comment by frankpeng7** [comment]
If it's an app token, the claim that contains granted permissions is `roles` instead of `scp`. Here's the official guide to obtain an app token: https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-1.0

**Comment by kashish-arora** [comment]
I was trying with an app token.

**Comment by kashish-arora** [comment]
Got it! I had granted permissions but I had not enabled 'Grant Admin Consent' after that. Thank you! One last thing- I want to allow people to join before the host joins. How can I do that?

**Comment by kashish-arora** [comment]
I have set the lobby bypass settings to everyone, still users are being shown the message: 

"When the meeting starts, we'll let people know you're waiting.

If you're the organizer or the invite came from your work or school, please sign in."

This is the meeting object:

{
  "startDateTime":"2021-07-14T00:05:34.2444915-07:00",
  "endDateTime":"2021-07-14T09:20:34.2464912-07:00",
  "subject":"Testttrrfc",
  "lobbyBypassSettings": {
        "scope": "everyone"
    }
}

**Comment by frankpeng7** [comment]
@kashish-arora since this is a different topic, can you close this one and open a new issue?

**Comment by kashish-arora** [comment]
Ok sure!
