### ISSUE TITLE
mail / otherMails properties do not support accented characters. Documentation says otherwise.

### ISSUE THREAD

**Issue by astaykov** [microsoftgraph/microsoft-graph-docs#13477]
Documentation part about `mail` and `otherMails` properties of the user resource type is misleading. 
In the part it mentions:

> NOTE: While this property can contain accent characters, using them can cause access issues with other Microsoft applications for the user.

 

However if you try to update the `mail` property to something with accented character (e.g. jàhn@mail.de), you will get an HTTP 400 Error like this one:

```json
{"error":
   {
       "code":"Request_BadRequest",
       "message":"Invalid value specified for property 'mail' of resource 'User'.",
       "innerError":
         {
             "date":"2021-07-13T09:55:58",
             "request-id":"1c385db5-6b1d-4f9b-aea8-e2a139efa588",
             "client-request-id":"1c385db5-6b1d-4f9b-aea8-e2a139efa588"
        }
   }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @astaykov for raising this issue. Kindly encode the accent characters. Since only ASCII characters can be transmitted in a URL (including the body parameters), you must encode the accent characters when using Microsoft Graph.

**Comment by astaykov** [comment]
Thanks @FaithOmbongi for quick response. 
Can you elaborate more, please! How come accented characters are allowed and work perfectly with Display Name (for example), but require special handling for `mail` attribute?

The following samples are performed with PostMan:

##Request (1) - producing an error
```json
{
            "accountEnabled": true,
            "mailNickname": "4u4u",
            "mail": "chaa@mail.bg",
            "displayName": "电 23",
            "givenName": "电子商öäüабв",
            "surname": "电子商务öäüабв",
            "userPrincipalName": "4u4u@login.tonyco.site",
            "passwordProfile" : {
                "password": "Only€Äß#!ч",
                "forceChangePasswordNextSignIn": false
            },
            "passwordPolicies": "DisablePasswordExpiration"
      }
```

### Result

```json
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Invalid value specified for property 'mail' of resource 'User'.",
        "details": [
            {
                "target": "mail",
                "code": "InvalidValue"
            }
        ],
        "innerError": {
            "date": "2021-07-14T09:53:54",
            "request-id": "c5be0f64-10d4-4d60-a7f6-d15a41b4bc1c",
            "client-request-id": "c5be0f64-10d4-4d60-a7f6-d15a41b4bc1c"
        }
    }
}
```

## Request (2) - still fancy characters, just not in `mail` property

```json
{
            "accountEnabled": true,
            "mailNickname": "4u4u",
            "mail": "chaa@mail.bg",
            "displayName": "电 23",
            "givenName": "电子商öäüабв",
            "surname": "电子商务öäüабв",
            "userPrincipalName": "4u4u@login.tonyco.site",
            "passwordProfile" : {
                "password": "OnlyAsci123!i",
                "forceChangePasswordNextSignIn": false
            },
            "passwordPolicies": "DisablePasswordExpiration"
      }
```

### Result is successfull

```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "id": "b7bdf406-4f33-4592-a548-54a3fa11beaf",
    "businessPhones": [],
    "displayName": "电 23",
    "givenName": "电子商öäüабв",
    "jobTitle": null,
    "mail": "chaa@mail.bg",
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null,
    "surname": "电子商务öäüабв",
    "userPrincipalName": "4u4u@login.tonyco.site"
}
```

So, there is definitely issue with `mail` / `otherMails`, and it most probably isn't about encoding.

**Comment by FaithOmbongi** [comment]
Hi  @astaykov , reopening this issue so we can get more feedback from the product team.

**Comment by FaithOmbongi** [comment]
@astaykov , the latest feedback from the product team is that the two properties do not support accented characters. This will help you avoid any usability issues. I'll raise a PR to update the doc.
