### ISSUE TITLE
When can we expect support for adding members to existing tags?

### ISSUE THREAD

**Issue by mayankmaxsharma** [microsoftgraph/microsoft-graph-docs#13479]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cd0b64a-b1c4-8efe-28e6-318f522079ec
* Version Independent ID: 934e5379-eeaf-705f-3e2c-7645881eec4d
* Content: [Update teamworkTag - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamworktag-update.md)
* Product: **teamwork**
* Technology: **microsoft-graph**
* GitHub Login: @anniecolonna
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mayankmaxsharma** [comment]
Hi @anniecolonna , would you be able to provide any updates. I am working on creating automation around this and this will be huge relief to get this feature published.

**Comment by lramosvea** [comment]
Thank you @mayankmaxsharma for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-teamwork.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
