### ISSUE TITLE
the c# code snippet is incorrect

### ISSUE THREAD

**Issue by georgewen** [microsoftgraph/microsoft-graph-docs#13496]
the C# example code doesn't make sense and plainly wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2dfd214-eebd-923e-1baf-ed140bddc70b
* Version Independent ID: f211b883-2ea6-f525-05df-d647d398e5fd
* Content: [Update accessReviewScheduleDefinition - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/accessreviewscheduledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewscheduledefinition-update.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @isabelleatmsft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@andrueastman Kindly assist to look into this.
Related to #11748

**Comment by FaithOmbongi** [comment]
Reopening this issue because it was note resolved in the new snippets.
