### ISSUE TITLE
Get call record using CallChainId vs Call record id

### ISSUE THREAD

**Issue by SubbaReddi** [microsoftgraph/microsoft-graph-docs#13520]
Hi Team,
We have query related to Call record API. Could you help to answer.
-> Call is created and we captured callchainid for reference.
->And call is forwarded to Phone queue.
-> And user pick up the call.
-> Once call is ended, we see call record notification with different call record id and able to get call record details.

But if we try to get using callchainid, it is not returning results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd76e0a9-874e-1e5e-7238-77247a020064
* Version Independent ID: 08963ed9-21ee-773d-3532-75be9cd57e70
* Content: [Get callRecord - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/callrecords-callrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/callrecords-callrecord-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @SubbaReddi  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-cloud-communications.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
