### ISSUE TITLE
/oauth2/v2.0/token does not return a refresh_token

### ISSUE THREAD

**Issue by kmwill23** [microsoftgraph/microsoft-graph-docs#13544]
Documentation does not properly reflect the current behavior of the API call. The return JSON does nto contain a property for refresh_token, and does contain a property for ext_expires_in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-user.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @kmwill23 for raising this issue. Could you clarify the affected response object? I can see both refresh_token and expires_in in the token responses.

**Comment by kashish-arora** [comment]
This happens with me too.

Here is the response I get: 

{
        "token_type":"Bearer",
        "scope":"",
        "expires_in":3600,
        "ext_expires_in":3600,
        "access_token":""
}

**Comment by FaithOmbongi** [comment]
Thank you @kashish-arora for sharing this response object. Unfortunately, this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html). Please ask this question there. 

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
