### ISSUE TITLE
Incorrect documentation for /oauth2/v2.0/token

### ISSUE THREAD

**Issue by kmwill23** [microsoftgraph/microsoft-graph-docs#13543]
/oauth2/v2.0/token has a request query string. However, during implementation it was discovered that this information needs to be in the POST body, not a query string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-user.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @kmwill23 for raising this issue. Could you clarify the affected request object? I don't see a request query string on /oauth2/v2.0/token in the article.

**Comment by kmwill23** [comment]
Thank you for the response!

While this article can be improved by explicitly calling out the "query string" as POST form data and not attached to the URL, I do feel all the elements are there. The content-type is form data, it is POST.

The reason I feel a callout would be beneficial is that competing products with OATH 2.0 APIs implemented this exact method use the actual query string, even though it is a POST. It can be debated if that is a proper thing at all =)

I feel this issue **can** be closed, or a slight improvement can be made.
