### ISSUE TITLE
https://graph.microsoft.com/v1.0/me/drive/root/children return BadRequest

### ISSUE THREAD

**Issue by erangaapp** [microsoftgraph/microsoft-graph-docs#1354]
GET https://graph.microsoft.com/v1.0/me is working find and return success. But 
GET **https://graph.microsoft.com/v1.0/me/drive/root/children** return error as follows. 

`{"_body":"{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Unable to retrieve user's mysite URL.\",\r\n    \"innerError\": {\r\n      \"request-id\": \"8b51c459-aeea-4968-8fd0-e93a7a83dc79\",\r\n      \"date\": \"2017-05-26T12:08:56\"\r\n    }\r\n  }\r\n}","status":400,"ok":false,"statusText":"Bad Request","headers":{"client-request-id":["8b51c459-aeea-4968-8fd0-e93a7a83dc79"],"Content-Type":["application/json"],"Cache-Control":["private"],"request-id":["8b51c459-aeea-4968-8fd0-e93a7a83dc79"]},"type":2,"url":"https://graph.microsoft.com/v1.0/me/drive/root/children"}`

**What should be the reason.Please help.**

**Comment by panjkov** [comment]
Please post such questions on StackOverflow in the future. 
The error that I see now seems like user does not have ODFB site created. To debug that issue for now, try to use Graph Explorer https://developer.microsoft.com/en-us/graph/graph-explorer# and login with your user account. 
If you can access /me then try accessing /me/drive/root and you will get details about ODFB Doc Lib for current user if it exist.

**Comment by erangaapp** [comment]
Thank you **panjkov** for your quick response.

That's write. It's return current user details from  /me/drive/root when I run query with https://developer.microsoft.com/en-us/graph/graph-explorer (for my account). But the thing is it doesn't return data with my angular 2 app. My code snip as follows. 
 ```
var uri = 'https://graph.microsoft.com/v1.0/me'; //-- This is fine
//var uri = 'https://graph.microsoft.com/v1.0/users';-- This is fine
//var uri = 'https://graph.microsoft.com/v1.0/me/drive/root/children';-- This is not working any more,
//I tried with me/drive/root,me/calendars like what ever thing return a some error.

 this.http.get(uri, {
                headers: new Headers({ "Authorization": "Bearer " + localStorage.getItem('graph_access_token')})
            }).map(response => (<Response>response));

```
 
Actually user want to display some files from the drive. Why is it working only with users. Is it may be a some authentication problem with token??

**Comment by etsrepo** [comment]
what is the solution ?

**Comment by erangaapp** [comment]
when we make this calls within the iframe, then it will work properly. I got a better sample from kurvejs.
[](https://github.com/MicrosoftDX/kurvejs)

**Comment by Arvind6353** [comment]
thank you . let me check with my enterprise admin on the privileges as well .
