### ISSUE TITLE
Missing data for nested contact

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs#13556]
In the example provided below (as copied from docs)
```http
PATCH https://graph.microsoft.com/beta/tenantRelationships/managedTenants/tenantsCustomizedInformation/{tenantCustomizedInformationId}
Content-Type: application/json
Content-length: 278

{
  "@odata.type": "#microsoft.graph.managedTenants.tenantCustomizedInformation",
  "tenantId": "String",
  "contacts": [
    {
      "@odata.type": "microsoft.graph.managedTenants.tenantContactInformation"
    }
  ],
  "website": "String"
}
```
The individual contact(s) data to be provided within the collection `contacts` is missing. Only the odata.type is specified but the concrete data properties like name, address e.t.c for the contact(s) not provided.
The example should instead look like
```http
PATCH https://graph.microsoft.com/beta/tenantRelationships/managedTenants/tenantsCustomizedInformation/{tenantCustomizedInformationId}
Content-Type: application/json
Content-length: 278

{
  "@odata.type": "#microsoft.graph.managedTenants.tenantCustomizedInformation",
  "tenantId": "String",
  "contacts": [
    {
      "@odata.type": "microsoft.graph.managedTenants.tenantContactInformation",
      "name": "String",
      "title": "String",
      "email": "String",
      "phone": "String",
      "notes": "String"
    }
  ],
  "website": "String"
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 084efcdf-bd41-d522-bd60-2b66ac9b0023
* Version Independent ID: 32582f2e-e856-1494-90f8-62c91bee6608
* Content: [Update tenantCustomizedInformation - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/managedtenants-tenantcustomizedinformation-update?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/managedtenants-tenantcustomizedinformation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-tenantcustomizedinformation-update.md)
* Product: **microsoft-365-lighthouse**
* Technology: **microsoft-graph**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by idwilliams** [comment]
This has been corrected.
