### ISSUE TITLE
How can I get the mobile friendly view of the document?

### ISSUE THREAD

**Issue by chenxizhang** [microsoftgraph/microsoft-graph-docs#13553]
[Enter feedback here]

Is there any parameter I can use to identify the document needs to render to mobile friendly?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37a29472-2a4e-11f5-7111-7aa1c1dbc273
* Version Independent ID: bdbaa1b9-f60a-4774-2ec6-8f0ec77c1850
* Content: [driveItem: preview - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-preview.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @chenxizhang for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-files.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
