### ISSUE TITLE
Filter support on LastModifiedDateTime for the "List messages in a chat"

### ISSUE THREAD

**Issue by Dethras** [microsoftgraph/microsoft-graph-docs#13562]
Hi,

I would like to know if the filter support on LastModifiedDateTime for the List Messages in a chat call : (GET /chats/{chat-id}/messages) will ever be implemented, or if it is in the pipeline already.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548a7932-274e-ce6c-aed5-e35206f7894a
* Version Independent ID: 02c653f9-fde9-758e-9bb7-a573f88cbbe8
* Content: [List messages in a chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
What kind of filter are you looking for? Greater than or less than?

**Comment by Dethras** [comment]
@RamjotSingh: Exactly, just like the one for "/users/{id}/chats/getAllMessages" and "/teams/{team-id}/channels/getAllMessages"

**Comment by RamjotSingh** [comment]
Supporting greater than would be possible. Supporting less than might require ton of work. Greater than is something we are working towards supporting.

**Comment by Dethras** [comment]
@RamjotSingh Greater than support would be nice. A further request to my original issue would be, when using the filter, is it possible to have the data sent in ascending LastModifiedOn order?

**Comment by RamjotSingh** [comment]
@Dethras We already have an API which should suffice both these requirements https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http

> **Note:** Delta API only goes back max 8 months.

**Comment by Dethras** [comment]
@RamjotSingh No that would no suffice, since I need the whole history and not just the last 8 Months

**Comment by RamjotSingh** [comment]
If you need the full history then the order would not matter I presume? Either way both these filters aren't supported right now but we have plans to support last modified time based filter.
