### ISSUE TITLE
Getting 500 server error with personal accounts.

### ISSUE THREAD

**Issue by Shweta-1405** [microsoftgraph/microsoft-graph-docs#13587]
Documentation does not specify that this API is not supported for personal accounts and always give 500 error as response.

![image](https://user-images.githubusercontent.com/83591574/126314334-5e8237d1-d271-4ddd-99af-c923ce8716cc.png)

This creates confusion for new users. Please do specify API behavior/limitation with personal account usage.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d66ffe-f5c3-beca-5551-7e1a6271eb12
* Version Independent ID: 248c75b3-8e23-6d5f-365f-6a15fa636a8c
* Content: [Get organization - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/organization-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/organization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/organization-get.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @adimitui
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you for the feedback @Shweta-1405 . Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A(https://docs.microsoft.com/en-us/answers/products/graph). Please ask your question there.
No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
