### ISSUE TITLE
Wrong NavigationProperty Name specified deviceCompliancePolicySettingStateSummarys

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs#13596]
The documentation wrongly specifies a navigation property `deviceCompliancePolicySettingStateSummarys` as opposed to the  Metadata which specifies the property as `deviceCompliancePolicySettingStateSummaries`.

Currently the `HTTP request` definition and the example have used  `deviceCompliancePolicySettingStateSummarys` as appears below.

```HTTP
GET https://graph.microsoft.com/beta/tenantRelationships/managedTenants/deviceCompliancePolicySettingStateSummarys/{deviceCompliancePolicySettingStateSummaryId}
```

instead of

```HTTP
GET https://graph.microsoft.com/beta/tenantRelationships/managedTenants/deviceCompliancePolicySettingStateSummaries/{deviceCompliancePolicySettingStateSummaryId}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c21f6e6d-a35f-b57d-b9d1-85ae84ec01d3
* Version Independent ID: eeff2c2b-ac85-7938-4ea6-5e8e2a0c655c
* Content: [Get deviceCompliancePolicySettingStateSummary - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/managedtenants-devicecompliancepolicysettingstatesummary-get?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/managedtenants-devicecompliancepolicysettingstatesummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/managedtenants-devicecompliancepolicysettingstatesummary-get.md)
* Product: **microsoft-365-lighthouse**
* Technology: **microsoft-graph**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by idwilliams** [comment]
This has been resolved.
