### ISSUE TITLE
The filter, "siteCollection/root ne null" not working

### ISSUE THREAD

**Issue by jinop** [microsoftgraph/microsoft-graph-docs#13595]
Hi team,

The filter, "siteCollection/root ne null" not working because all sites have no key named "root", other than the root site.

Regards,
Jino
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7646ca28-c189-e84b-15af-6693dac77f5c
* Version Independent ID: df13ef64-7b81-8f5c-7949-5b18eece44fc
* Content: [Enumerate sites - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @jinop for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
