### ISSUE TITLE
What are all properties necessary to define a webpart

### ISSUE THREAD

**Issue by rohit404404** [microsoftgraph/microsoft-graph-docs#13602]
DOcument says, there are no fixed properties. 

Does that mean we can pass blank? (event though it doesnt make sense)

Is there a minimum property that needs to be passed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28aede3d-a68f-bb2d-b5cb-46c0c2686c63
* Version Independent ID: 7bc238e1-0fc9-3fdc-cd27-272203b23038
* Content: [SitePageData - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/sitepagedata?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/sitepagedata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/sitepagedata.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @rahmit
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @rohit404404  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
