### ISSUE TITLE
Incorrect Methods on Examples

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/microsoft-graph-docs#13619]
I have executed the examples as is and the following errors occur. 

request-1 fails with error Invalid locale Id value bannerLogo, It Must be a valid iso-639 locale"

request-3 uses a PUT method, however this fails with an error 
"Specified Method is not allowed for the request target".
Using PATCH resolves the issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f0c9f19-e487-c3c3-c776-c524aa9ae5da
* Version Independent ID: 20f09b39-a723-a509-82a0-5a10fe106a68
* Content: [Update organizationalBrandingProperties - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @AlexanderMars
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AlexanderMars** [comment]
Hi George,


Thanks for reporting the issue and sorry for the inconvenience. We are working on the Docs update to make it clear.

- The first one, request-1 might be the Graph Explorer specific error which is covered under GET method "If you try the example in Graph Explorer, you must also include the Accept-Language request header with a valid ISO-639 locale to avoid getting an error "Invalid locale id value en-US,en;q=0.9. It must be a valid ISO-639 locale.""
https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/organizationalbrandingproperties-get.md

- Another one, request-3 with PUT method should work if you update a single property and PATCH if multiple.

Please, let me know if it helps or/and you have any other questions.


Kind regards,
Sasha

**Comment by georgend** [comment]
@AlexanderMars Seems the issue is still persistent. Calling `https://graph.microsoft.com/beta/39310524-be7c-4031-a67c-4dcd422fa535/branding` generates a HTTP 500 even with the accept header set.
![image](https://user-images.githubusercontent.com/1641829/128434165-232154b4-2ef1-4f41-95f5-a6f03f6a4c4a.png)

**Comment by AlexanderMars** [comment]
@georgend Please, update your query to https://graph.microsoft.com/beta/organization/39310524-be7c-4031-a67c-4dcd422fa535/branding 

https://docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-beta&tabs=http

**Comment by georgend** [comment]
@AlexanderMars What should I update it to?

**Comment by AlexanderMars** [comment]
@georgend you've missed "**organization**" in your query according to the provided screenshot and your message
Calling `https://graph.microsoft.com/beta/39310524-be7c-4031-a67c-4dcd422fa535/branding`

the proper call is `https://graph.microsoft.com/beta/organization/39310524-be7c-4031-a67c-4dcd422fa535/branding` with Accept-Language request header.

Let me know if you have any further questions or it doesn't work.
