### ISSUE TITLE
How to add/target section and column in a page

### ISSUE THREAD

**Issue by rohit404404** [microsoftgraph/microsoft-graph-docs#13615]
Sample request body in example explains about adding webparts. However, is there a way to create and target perticular section/column in a page and add webpart to that perticualr section?

I supported , can we have sample request body.

GET query doesnt return section/column related information

GET /sites/{site-id}/pages/{page-id}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfd0c31c-0a44-5d1a-273c-b1692f6bb519
* Version Independent ID: 18b9abd5-479f-3930-035a-fe445fbe935a
* Content: [Create a new page in a SharePoint site - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/sitepage-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @rahmit
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @rohit404404 for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
