### ISSUE TITLE
How to set sensitivity labels using sendmail api?

### ISSUE THREAD

**Issue by qatrick** [microsoftgraph/microsoft-graph-docs#13613]
Hi,

As titled, how to set O365 sensitivity labels using sendmail api?

Before with EWS API, I can follow https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/dd633654(v=exchg.80) to use extended properties to set the sensitivity labels but now with MS Graph API, I refer to https://docs.microsoft.com/en-us/graph/api/resources/extended-properties-overview?view=graph-rest-1.0 to use either single value/multiple value extended properties but it doesnt work as expected.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd382e4-95b6-3ccf-6a15-02d0cc7ed841
* Version Independent ID: 276cebbe-10bc-100e-f9b1-51b2ba30c64b
* Content: [message resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/message.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @qatrick for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
