### ISSUE TITLE
MeetingAttendanceReport response returns empty emailAddress in attendance records

### ISSUE THREAD

**Issue by mduvaise** [microsoftgraph/microsoft-graph-docs#13629]
Hi,
I have come across this issue very recently as this was working correctly before.. The response from `/meetingAttendanceReport` api was returning emailAddress of attendees correctly but now when i checked , that emailAddress key is having empty string which seems like a bug. Any response on this issue would be appreciated.

Thanks,

FYR,
![image](https://user-images.githubusercontent.com/43490612/126761923-3b274cd1-b516-4eaa-ac51-1c0aad62931d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4519bc47-62c4-16be-1975-60a574dfe80f
* Version Independent ID: 0e3b2c24-bfdd-6965-2b76-df45f3904535
* Content: [meetingAttendanceReport resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/meetingAttendanceReport.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mkhribech
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @mduvaise just to confirm, did the emailAddress use to have some value and now it's empty (for the same meeting), or this is a different meeting and the emailAdress is empty?

**Comment by mduvaise** [comment]
Hello @frankpeng7 older meetings(meetings which were created before 1 week) had emailAddress(attendee's email id) and it still has emailAddress in `/meetingAttendanceReport` api response whereas meetings which were created from the past 4-5 days(till present day), have empty string as emailAddress in `/meetingAttendanceReport` api response

**Comment by frankpeng7** [comment]
Are they anonymous/guest users? Also can you provide the `client-request-id` and timestamp in the response headers?

**Comment by mduvaise** [comment]
No they are not guest users, They are users in our tenant. 
This is the entire response headers for the request
`{
    "client-request-id": "60862668-23b2-d32c-fe04-62978d8d6ee6",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "cb9b3c97-506b-4509-a48e-98cff02d77df"
}`

**Comment by mduvaise** [comment]
Hi @frankpeng7, any update on this issue would be appreciated

**Comment by frankpeng7** [comment]
Hi @mduvaise so far what I was able to confirm is that those attendance records do not have emailAddress in our backend. I'll update the thread once I'm able to root-cause this.

**Comment by frankpeng7** [comment]
@mduvaise our backend team confirmed that this was a transient issue and should not happen now. Feel free to reopen if it still persists.

**Comment by mduvaise** [comment]
> @mduvaise our backend team confirmed that this was a transient issue and should not happen now. Feel free to reopen if it still persists.

Thanks @frankpeng7 Issue seems resolved
