### ISSUE TITLE
messageRule ID not constant?

### ISSUE THREAD

**Issue by andywaugh** [microsoftgraph/microsoft-graph-docs#13642]
Under what circumstances would a messageRule's id value change? I had assumed it would be constant but it appears not. More context below.

I have been using the graph API to monitor my user's mail rules for security purposes. Over the weekend, I noticed the rule IDs for all rules belonging to only one of my users all changed. All rules for this user were otherwise exactly the same (conditions etc.). As it happened, this was a test account that I control so I know the "user" was not modifying the rules or even logged in at the time of the change.

I had been treating the ID value of a messageRule as a unique ID for that user but this can't be if it changes for some reason. Clearly the ID will change if a rule is deleted and recreated but this is not what happened here so I'm curious when/why else a rule ID would change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02132387-636e-6b9d-f086-c30e99adf338
* Version Independent ID: c0e0fe75-f9fe-3d56-ca0a-29604e14aeda
* Content: [messageRule resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/messagerule?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/messagerule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/messagerule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @andywaugh for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-mail.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
