### ISSUE TITLE
Translation error (French)

### ISSUE THREAD

**Issue by lpoublan** [microsoftgraph/microsoft-graph-docs#13644]
"Permissions (from least to most privileged)" is translated in French as 
"Autorisations (de celle qui offre le plus de privilèges à celle qui en offre le moins)"
which is the opposite.
It should be translated as:
"Autorisations (de celle qui offre le moins de privilèges à celle qui en offre le plus)".

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f3980610-a5dc-7b2a-43a2-27def95a2ece
* Version Independent ID: fe27e8cc-9e04-9184-dd8d-36990e4d7064
* Content: [Répertorier les canaux - Microsoft Graph v1.0](https://docs.microsoft.com/fr-fr/graph/api/channel-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs.fr-FR/blob/main/api-reference/v1.0/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @lpoublan for raising this issue. I've escalated it for the relevant team to look into it.

**Comment by FaithOmbongi** [comment]
This is now resolved. Closing this issue.
