### ISSUE TITLE
POST to /beta/applications returns an error "Multi-valued extension properties are not supported"

### ISSUE THREAD

**Issue by vman** [microsoftgraph/microsoft-graph-docs#1365]
Issue: 
POSTing to the /beta/applications endpoint worked until last week. This week, we are getting an error "Multi-valued extension properties are not supported"

I have documented the process here: http://www.vrdmn.com/2017/05/create-azure-ad-app-registration-with.html

I understand it is a beta endpoint and bound to change. What I am interested in is knowing what it has changed to and which endpoint should I be using now?

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/application_post_applications

**Comment by garima2510** [comment]
Still not working, I am getting the same issue.

**Comment by takekazuomi** [comment]
I had the same problem. Reproduce in Graph Explorer.

```
POST https://graph.microsoft.com/beta/applications

{
  "displayName": "My Sample Application",
  "replyUrls": [
    "http://localhost:55065"
  ],
  "requiredResourceAccess": [
    {
      "resourceAppId": "00000003-0000-0000-c000-000000000000",
      "resourceAccess": [
        {
          "id": "5b567255-7703-4780-807c-7be8301ae99b",
          "type": "Role"
        },
        {
          "id": "df021288-bdef-4463-88db-98f22de89214",
          "type": "Role"
        }
      ]
    }
  ]
}
```
response.

```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Multi-valued extension properties are not supported.",
        "innerError": {
            "request-id": "ca91f92a-8020-4565-865d-11a0f74eae8c",
            "date": "2017-12-16T17:36:56"
        }
    }
}```

**Comment by vman** [comment]
An update on this: The following code doesn't return any errors anymore, but I cannot see the created app registration anywhere in Azure AD.

```
POST https://graph.microsoft.com/beta/applications

{
  "displayName": "My custom app registration",
  "requiredResourceAccess": [
    {
      "resourceAppId": "00000003-0000-0ff1-ce00-000000000000",
      "resourceAccess": [
        {
          "id": "678536fe-1083-478a-9c59-b99265e6b0d3",
          "type": "Role"
        }
      ]
    }
  ]
}
```

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
