### ISSUE TITLE
There is no way to fetch publisher informaton. For ex: OneNote should have Microsoft Corporation

### ISSUE THREAD

**Issue by BalajiV27** [microsoftgraph/microsoft-graph-docs#13654]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ac1bdb-1ac9-e0aa-67a0-d92ab2d7d7f9
* Version Independent ID: beed2749-a8a2-9670-f3e4-a1bba9e35a62
* Content: [teamsApp resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/teamsapp.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/teamsapp.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @BalajiV27   for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-teamwork.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
