### ISSUE TITLE
PATCH stopped working for deviceManagement/deviceConfigurations - 403 Forbidden

### ISSUE THREAD

**Issue by asmhel** [microsoftgraph/microsoft-graph-docs#13681]
Configuration policy update (PATCH) code that worked yesterday, stopped working today. I got an "403 Forbidden" error.
![image](https://user-images.githubusercontent.com/22907238/127476576-d11a2c65-27cb-4914-847f-c5253fb388be.png)
It work from Graph Explorer with admin account, but it fails when running powershell with appid and secret.

$deviceConfigurationPolicyId = "08df9f62-3e77-47be-b89f-975d2e11c826"
$graphApiVersion = "Beta"
$DCP_resource = "deviceManagement/deviceConfigurations"
$uri = "https://graph.microsoft.com/$graphApiVersion/$($DCP_resource)/$deviceConfigurationPolicyId"
Invoke-RestMethod -Uri $uri -Headers @{Authorization = "Bearer $($authToken.access_token)"} -Method PATCH -Body $JSON -ContentType "application/json"

![image](https://user-images.githubusercontent.com/22907238/127475412-6de52fae-3eaa-42dc-a1de-753a6b1d1229.png)
More detailed error:
![image](https://user-images.githubusercontent.com/22907238/127475689-52b7a33a-841a-40a1-8d56-559346d9c0a9.png)

Compliance PATCH works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16ae043d-c117-a825-b8fa-d6a2ca5f8223
* Version Independent ID: b62de14a-9f3e-2f4c-7af0-f3a11c4cfb63
* Content: [Update windows10CustomConfiguration - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-windows10customconfiguration-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-deviceconfig-windows10customconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-deviceconfig-windows10customconfiguration-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @asmhel  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-corporate-mgmt.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
