### ISSUE TITLE
/me/calendar/calendarView is invalid according to the Graph Explorer.

### ISSUE THREAD

**Issue by richardbushnell** [microsoftgraph/microsoft-graph-docs#13686]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354b863-a317-056c-d1b3-e57da9bd4d49
* Version Independent ID: ba4221c8-6283-9401-e3cc-804bacd1d26c
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-calendarview.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Kindly open a support ticket for reporting issue with API or Graph explorer.

**Comment by richardbushnell** [comment]
It’s your documentation, not mine. Don’t put a feedback button on your page if you don’t want to do anything about it.

From: Harini84 ***@***.***>
Date: Monday, 2 August 2021 at 13:13
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Richard Bushnell ***@***.***>, Author ***@***.***>
Subject: Re: [microsoftgraph/microsoft-graph-docs] /me/calendar/calendarView is invalid according to the Graph Explorer. (#13686)

Kindly open a support ticket for reporting issue with API or Graph explorer.

**Comment by jasonjoh** [comment]
@richardbushnell how did Graph Explorer report it as invalid? Did you get an error trying to execute the query?

`/me/calendar/calendarView` *should* work, though it is redundant with the shorter `/me/calendarView`. I just tested it with one of my test users and it worked OK for me.
