### ISSUE TITLE
Group.Read.All should be removed for delegated auth

### ISSUE THREAD

**Issue by fredericklin** [microsoftgraph/microsoft-graph-docs#13690]
Group.Read.All does not suffice for delegated authentication.  I received this error message:

"Code: Forbidden
Message: Missing role permissions on the request. API required one of 'TeamsAppInstallation.ReadForUser.All, TeamsAppInstallation.ReadWriteSelfForUser.All, TeamsAppInstallation.ReadWriteForUser.All'. Roles on the request 'Group.Read.All, Sites.Read.All, Directory.Read.All, User.Read.All, Chat.Read.All, ChannelMessage.Read.All'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 564e1568-effe-205b-95f5-c10cf3b883c0
* Version Independent ID: 3fb814db-8d20-4cd9-80b1-cfbba1e02880
* Content: [Get installed app in team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-get-installedapps?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-get-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-get-installedapps.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fredericklin** [comment]
Actually, I made a mistake.  The documentation is correct. I called /users/<guid>/teamwork/installedApps

**Comment by lramosvea** [comment]
Closing this issue as @fredericklin has confirmed there is no issue on this doc.
