### ISSUE TITLE
Wrong required request header.

### ISSUE THREAD

**Issue by folbo** [microsoftgraph/microsoft-graph-docs#13695]
The `Content-Type: application/json` header is listed as a required header. It doesn't make sense for GET call as it's not supposed to have a body. Also, the call works without providing this header. Probably `Accept` header was meant in here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61ffb8e6-b359-e831-c045-9d30dbffb633
* Version Independent ID: 9549e56f-40d6-6266-6de5-a54f27f7843b
* Content: [List contacts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-contacts.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
Thanks, I checked in a fix to the article.
