### ISSUE TITLE
OData Filter accessPackageAssignment does not provide expiration

### ISSUE THREAD

**Issue by timd19** [microsoftgraph/microsoft-graph-docs#13727]
When querying the accessPackageAssignmentRequests and providing accessPackageAssignment in the OData query, I cannot see the expiration time. But if I query the accessPackageAssignments endpoint directly, I can see the expiration date.

Shouldn't the accessPackageAssignmentRequests endpoint with the accessPackageAssignment OData query provide the same information?

Below image is accessPackageAssignmentRequests endpoint with no expiration.

![image](https://user-images.githubusercontent.com/22712034/128010946-2945388c-e9dd-4c14-8c62-4f75880fbb50.png)

The below image is accessPackageAssignments endpoint and shows the expiration schedule.

![image](https://user-images.githubusercontent.com/22712034/128011138-98491da3-6b5e-4f43-908c-ea853642302c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccfd8b5-cf53-0d8c-a451-16e5444541ab
* Version Independent ID: 43dc91b0-686e-baac-8433-d75a09cb57ad
* Content: [List accessPackageAssignmentRequests - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/accesspackageassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accesspackageassignmentrequest-list.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Thanks for reporting, we'll take a look.

**Comment by chrisspre** [comment]
Hello Tim,
can we please get the two requests as text snippets together with the complete returned JSON. (instead of output of `$Requests[0] ...` and `$Assignments.value ... ` 
If possible please also simplify the request to just the minimum to show the problem. (e.g. the $exapnd for AccessPackage seems irrelevant)

**Comment by timd19** [comment]
Hi Christof - I scoped the request down to a specific assignment / as others have sensitive information.

https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentRequests/e853c8eb-1765-4394-bf24-c37254e8452d?expand=accessPackageAssignment

`{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/entitlementManagement/accessPackageAssignmentRequests(accessPackageAssignment())/$entity",
    "createdDateTime": "2021-08-17T17:57:45.293Z",
    "completedDate": "2021-08-17T17:58:27.473Z",
    "id": "e853c8eb-1765-4394-bf24-c37254e8452d",
    "requestType": "UserAdd",
    "requestState": "Delivered",
    "requestStatus": "FulfilledNotificationTriggered",
    "isValidationOnly": false,
    "expirationDateTime": null,
    "justification": "",
    "answers": [],
    "schedule": {
        "startDateTime": null,
        "recurrence": null,
        "expiration": {
            "endDateTime": null,
            "duration": null,
            "type": "notSpecified"
        }
    },
    "accessPackageAssignment@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/entitlementManagement/accessPackageAssignmentRequests('e853c8eb-1765-4394-bf24-c37254e8452d')/accessPackageAssignment/$entity",
    "accessPackageAssignment": {
        "id": "acebed63-15b6-4f76-a0ad-558169dd8b59",
        "catalogId": "7830aa49-b7b0-4140-beb5-1ea599a0a025",
        "accessPackageId": "97926029-b330-4a01-a1e6-199750b418c8",
        "assignmentPolicyId": "a6c426b7-4f42-4262-8fe5-b5882e7264b0",
        "targetId": "01e1aedc-248f-4078-a657-1e7f7801fa04",
        "assignmentStatus": "Delivering",
        "assignmentState": "Delivering",
        "isExtended": false,
        "expiredDateTime": null,
        "schedule": {
            "startDateTime": null,
            "recurrence": null,
            "expiration": {
                "endDateTime": null,
                "duration": null,
                "type": "notSpecified"
            }
        }
    }
}`

https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignments/acebed63-15b6-4f76-a0ad-558169dd8b59

`{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#identityGovernance/entitlementManagement/accessPackageAssignments/$entity",
    "id": "acebed63-15b6-4f76-a0ad-558169dd8b59",
    "catalogId": "7830aa49-b7b0-4140-beb5-1ea599a0a025",
    "accessPackageId": "97926029-b330-4a01-a1e6-199750b418c8",
    "assignmentPolicyId": "a6c426b7-4f42-4262-8fe5-b5882e7264b0",
    "targetId": "01e1aedc-248f-4078-a657-1e7f7801fa04",
    "assignmentStatus": "Delivered",
    "assignmentState": "Delivered",
    "isExtended": false,
    "expiredDateTime": null,
    "schedule": {
        "startDateTime": "2021-08-17T17:57:48.517Z",
        "recurrence": null,
        "expiration": {
            "endDateTime": "2021-08-22T17:57:48.517Z",
            "duration": null,
            "type": "afterDateTime"
        }
    }
}`

**Comment by chrisspre** [comment]
> Hi Christof - I scoped the request down to a specific assignment / as others have sensitive information.
> 

Perfect. Thanks Tim, that helps a lot.

**Comment by chrisspre** [comment]
Still investigating where in the stack this happens.

Just for the record the two images show the difference
![image](https://user-images.githubusercontent.com/53094940/134554153-d91e1e5f-1252-464d-8672-65d6c98eb7b6.png)
![image](https://user-images.githubusercontent.com/53094940/134554176-63ec0849-c724-446d-8e24-8127a004e533.png)

**Comment by timd19** [comment]
Hello - Since these endpoints have made it to v.10, has this been resolved?

**Comment by FaithOmbongi** [comment]
> Hello - Since these endpoints have made it to v.10, has this been resolved?

Hi @markwahl-msft - Please help to confirm whether this issue is now resolved. Thanks.

**Comment by timd19** [comment]
Hello - this has not been resolved. In the 1.0 endpoint the expiry date is not displayed in the assignmentRequest endpoint.

![image](https://user-images.githubusercontent.com/22712034/185116661-69948d77-87b8-4546-a080-976cd08a2720.png)

**Comment by FaithOmbongi** [comment]
Because this is a functionality issue, I'm closing this issue here and tracking it via engineering bug 2201078
