### ISSUE TITLE
odata.type "Microsoft.Teams.GraphSvc.aadUserNotificationRecipient" is not working

### ISSUE THREAD

**Issue by vasanthtt** [microsoftgraph/microsoft-graph-docs#13738]
Examples using value to odata type as Microsoft.Teams.GraphSvc.aadUserNotificationRecipient is no more working. Replacing odata type to microsoft.graph.aadUserNotificationRecipient is working fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e8ea77-74b9-50cc-43a9-eee7fa805e7a
* Version Independent ID: 7a3747ed-2b1c-9e1a-adb8-6d1fb8688a48
* Content: [team: sendActivityNotification - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-sendactivitynotification.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @eddie-lee-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@vasanthtt- We are looking into this we will get back to you soon.

**Comment by Prasad-MSFT** [comment]
We tried to repro the issue and found that using `Microsoft.Teams.GraphSvc.aadUserNotificationRecipient` as @odata.type doesn't work throwing below error. However using `microsoft.graph.aadUserNotificationRecipient` as @odata.type works.
![image](https://user-images.githubusercontent.com/62237649/181478336-e3e88329-63c2-4723-bb5d-ad9a68fe31b7.png)

@AkJo - Could you please help here to update the doc accordingly?

**Comment by eddie-lee-msft** [comment]
Ack, this is a mistake in the docs. We will fix.

**Comment by eddie-lee-msft** [comment]
Docs are now fixed.
