### ISSUE TITLE
setUpResourcesFolder - Missing information

### ISSUE THREAD

**Issue by OskarNet** [microsoftgraph/microsoft-graph-docs#13731]
Hi

This page fails to mention what happens if you run this on an assignment that has already run this command.
Will it fail? If so, what could one expect to get in return?

Regards,
Oskar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d63622-9408-2694-3dee-09ba9e50779d
* Version Independent ID: 2b4c3d89-fb4e-e4db-ed43-a9fe053b3e3c
* Content: [educationAssignment: setUpResourcesFolder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationassignment-setupresourcesfolder?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/educationassignment-setupresourcesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/educationassignment-setupresourcesfolder.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @sharmas
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cristobal-buenrostro** [comment]
@OskarNet 
documentation has been updated.
