### ISSUE TITLE
The app creation script is not working fails with multiple errors

### ISSUE THREAD

**Issue by bniranjanbhat** [microsoftgraph/microsoft-graph-docs#13748]
[Enter feedback here]

I am trying out the script provided in this page and I see the following failures:
1. When New-MgServicePrincipal cmdlet gets executed, it fails with the following error:
     

```
New-MgServicePrincipal -AppId $appRegistration.AppId -AdditionalProperties @{}
      New-MgServicePrincipal : Unable to find target address
```

2. Also the Admin consent URL generated by the script is wrong:

`https://login.microsoftonline.com//adminconsent?client_id=e718c3c5-14e4-4f5e-a08a-ca5676a1097b`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d211b6ad-20d1-8683-3562-04e35d8de652
* Version Independent ID: 926e81ea-63c6-ab12-3fa6-ef85070b106f
* Content: [Use app-only authentication with the Microsoft Graph PowerShell SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal)
* Content Source: [concepts/powershell/app-only.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/powershell/app-only.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting @bniranjanbhat. The wrong URL is almost definitely caused by the failure - basically it's omitting the tenant ID from the URL. I will install the latest SDK and see if I can reproduce your error.

**Comment by jasonjoh** [comment]
@bniranjanbhat I do not reproduce any errors in the script with the latest SDK. I have found a change in how Microsoft identity platform handles the admin consent though, which requires that a redirect URI be specified in the app registration. This doesn't cause any errors in the script, just an error when the admin attempts to provide consent.

Can you run the script in a debugger and step over each line to see what's coming back?

**Comment by bniranjanbhat** [comment]
Turns out since I have multiple tenants associated with my account, Graph Powershell was not working as expected ?
When I changed the Connect-MgGraph cmdlet in the script to include my tenantId, I could get the script working.

`Connect-MgGraph  -Scopes "Application.ReadWrite.All User.Read" -TenantId <MY_tenant_ID>`

None the less, there should be at least some sort of help either in the error message or in the documentation which could point us towards what is going on .. Right ?

This is the current error message in the script:

```
New-MgServicePrincipal : Unable to find target address
At line:1 char:1
+ New-MgServicePrincipal -AppId $appRegistration.AppId -AdditionalPrope ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ body = Micros...vicePrincipal }:<>f__AnonymousType1`1) [New-MgServicePrincipal_CreateExpanded1], RestException`1
    + FullyQualifiedErrorId : InternalServerError,Microsoft.Graph.PowerShell.Cmdlets.NewMgServicePrincipal_CreateExpanded1
```

**Comment by jasonjoh** [comment]
Thanks for the additional info @bniranjanbhat! If you get a chance, can you try out the new version of the script in https://github.com/microsoftgraph/microsoft-graph-docs/pull/13842? It adds a `-TenantId` parameter so you don't have to hard-code it in the script.

**Comment by bniranjanbhat** [comment]
I just tried the script. Works now . thanks !
