### ISSUE TITLE
Do the service communication APIs really belong under "Devices and Apps"?

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/microsoft-graph-docs#13775]
I work with the v1 docs weekly, and I remembered hearing that the O365 management APIs would be available through Graph, but never saw it just browsing through the endpoints (admittedly never thought to search). When I see "Devices and Apps", I think InTune, not M365 administration. Is there a better way to categorize this? The /admin endpoints be in their own section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 723ddf19-0a3e-2ea8-37bb-78b4665cc453
* Version Independent ID: f34b4c24-a242-33ff-9e8c-974ce4b89929
* Content: [Working with service communications APIs in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/service-communications-api-overview?view=graph-rest-1.0&preserve-view=true)
* Content Source: [api-reference/v1.0/resources/service-communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/service-communications-api-overview.md)
* Product: **service-communications**
* Technology: **microsoft-graph**
* GitHub Login: @payiAzure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by payiAzure** [comment]
Our doc is put under "Devices and Apps" per @angelgolfer-ms recommendation. 
Hi @angelgolfer-ms , would you think it is better to put our API doc under their own section? may be introducing a new top level section 'Admin'?
I think maybe this makes more sense. When we got our API review, the API reviewers recommended to put our API under Graph top singleton node 'Admin', which is a new introduced top level node in MSGraph. maybe It is better to make documentation keep consistent as the API URL?
our API is under /admin/......

**Comment by payiAzure** [comment]
We would like to put service communication api under "Apps and Devices" node. And when reorganizing the TOC, we will think about put it under more matching top node (may be new introduced toc node).
Attached the conversation we had with Angela as well.

--- From Angela
Hi Pan, thanks for pointing me to the Github issue. Replacing "Devices and apps" by a node named "Admin" would likely stir up opinion about excluding the Identity team APIs. Basically, the majority of the Azure AD APIs exposed on Graph are admin-oriented.

[8/9/2021 5:28 PM] Angela Chu-Hatoun
For the short term, I can suggest "Device and app management". When we find the time to reorganize the TOC and information architecture, customers will get fewer choices to handle in the same TOC level (not like 30+ right now at the same level). A choice in the TOC will open up a 2-D landing page. You can imagine a landing page as rows and columns of "cards". Each card can group similar workloads together. It will be a more reasonable experience for customers to scan.

[8/9/2021 5:31 PM] Angela Chu-Hatoun
This page is a landing page. You can look at it for the layout - a page with cards. https://docs.microsoft.com/en-us/graph/auth/
Microsoft Graph auth overview
Learn how to authenticate and work with permissions to securely access data through Microsoft Graph. Explore the documentation below to learn about app registration, authentication libraries, autho...
