### ISSUE TITLE
Unable to add resource to assignment

### ISSUE THREAD

**Issue by OskarNet** [microsoftgraph/microsoft-graph-docs#13782]
Hi

I was reading this page and trying follow the example by doing a POST to graph.microsoft.com
POST https://graph.microsoft.com/v1.0/education/classes/{classId}/assignments/{assignmentId}/resources
but I'm getting an error back saying the resource wasn't found.

I can see when looking at the network traffic when adding resource to an assignment manually that it's using https://assignments.onenote.com/v1.0...

Should the example be assignments.onenote.com rather that graph.microsoft.com?

Regards,
Oskar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92dce17f-3ffd-7d4a-d88b-597d2062f843
* Version Independent ID: eaba5355-fbe5-571b-4d75-a61d8818978b
* Content: [Upload files for education assignments and submissions using the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/education-upload-resource-overview)
* Content Source: [concepts/education-upload-resource-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/education-upload-resource-overview.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @sharad-sharma-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by OskarNet** [comment]
Ok, so got this working by using graph.microsoft.com.  My issue was that the DriveId was incorrect

**Comment by lramosvea** [comment]
@OskarNet should this issue be closed or is there something you think needs to be updated in the doc?

**Comment by OskarNet** [comment]
Would be good to add in the examples that you need to to use the driveId part of the returnUrl to use going forward in the examples.

**Comment by sharad-sharma-msft** [comment]
@OskarNet , Is Step 3 not clear on how drive-id should be used?

**Comment by OskarNet** [comment]
I feel it's rather that the resourcesFolderUrl that is returned when calling /setupResourcesFolder contains the driveId that should be used going forward in step 1 when constructing the upload URL.
I thought I could access it in any other way like by getting the assignment again but the ResourceFolderUrl property was null. I guess it hadn't updated yet in the Graph.

**Comment by sharad-sharma-msft** [comment]
@OskarNet  Thanks for your feedback!

We will check at our end and if required will update under "Upload a resource" section that it might take some time for the ResourceFolderUrl  to reflect and one might need to poll/GET assignment metadata.
@cristobal-buenrostro FYI.

**Comment by OskarNet** [comment]
I just used the driveId part of the returned ResourceUrl as the driveId and used that for my other requests.

**So as in your example:**
```
{
    ...
    "resourcesFolderUrl": "https://graph.microsoft.com/v1.0/drives/b!6SQl0y4WHkS2P5MeIsSGpKwfynEIaD1OvPVeH4wbOp_1uyhNwJMSSpseJneB7Z4F/items/01YT2AIJRQLVYT24IWWFAJHMRRNYCB3GFA"
    ...
}
```

I just used "b!6SQl0y4WHkS2P5MeIsSGpKwfynEIaD1OvPVeH4wbOp_1uyhNwJMSSpseJneB7Z4F" as the driveId to upload files to.

**Comment by sharad-sharma-msft** [comment]
@OskarNet , I hope you had success in uploading the resource.

**Comment by OskarNet** [comment]
Yes, after I figured that one out :)

**Comment by cristobal-buenrostro** [comment]
> I feel it's rather that the resourcesFolderUrl that is returned when calling /setupResourcesFolder contains the driveId that should be used going forward in step 1 when constructing the upload URL.
> I thought I could access it in any other way like by getting the assignment again but the ResourceFolderUrl property was null. I guess it hadn't updated yet in the Graph.

Hi @OskarNet , any estimate of how much time passed since you setupResourcesFolder until you called get Assignment end point?
I tried manually in graph explorer, and was reflected almost immediately, probably you tried when the service load was heavy.
Please let me know and will update doc accordingly mentioning that it could happen and will need to verify calling get Assignments.

Regards

**Comment by OskarNet** [comment]
Hi, no I'm not sure. I just called get assignment straight afterwards (must be milliseconds) and this property was null so I used the URL string returned from the /setupResourceFolder endpoint.

**Comment by cristobal-buenrostro** [comment]
Closing this issue, tried to replicate couple of times but the resourcesFolderUrl was always there, it could probably be kind of slowness due to service load
