### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by dkreymerman-byredwood** [microsoftgraph/microsoft-graph-docs#13800]
There is literally no explanation how to generate the "@odata.type": "#microsoft.graph.domainIdentitySource" for the request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8546f6-e298-e516-a604-577190592145
* Version Independent ID: bbee081d-b346-02fa-b0cb-84551925f61d
* Content: [Create connectedOrganization - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/connectedorganization-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/connectedorganization-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/connectedorganization-post.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dkreymerman-byredwood for raising this issue.

You don't create the odata type. It's source is explained in the paragraph in the [Request body](https://docs.microsoft.com/en-us/graph/api/connectedorganization-post?view=graph-rest-beta&tabs=http#request-body) section

> The single member of the identitySources collection should be of either the domainIdentitySource or externalDomainFederation type. If the caller provides a domainIdentitySource, the call is successful, and the domain corresponds to a registered domain of an Azure Active Directory tenant, then the resulting connectedOrganization that is created will have an identitySources collection containing a single member of the azureActiveDirectoryTenant type.

The odata type here is required to explicitly identify the type of object you are passing in the identitySources property; in this case either a domainIdentitySource or a externalDomainFederation object, two of the types derived from [identitySource](https://docs.microsoft.com/en-us/graph/api/resources/identitysource?view=graph-rest-beta). I hope I understood your question correctly.

**Comment by FaithOmbongi** [comment]
Closing this issue.
