### ISSUE TITLE
capital letter missing deviceInactivityBeforeRetirementInDays

### ISSUE THREAD

**Issue by xven0mxz** [microsoftgraph/microsoft-graph-docs#13825]
Hi,

in the request of getting 
`Invoke-RestMethod -Uri "https://graph.microsoft.com/beta/deviceManagement/managedDeviceCleanupSettings" -Headers @{"Authorization" = $BearerToken }`

Output
```
@odata.context                                                                           deviceInactivityBeforeRetirementInDays
--------------                                                                           --------------------------------------
https://graph.microsoft.com/beta/$metadata#deviceManagement/managedDeviceCleanupSettings 180
```

But when you want to change the setting with deviceInactivityBeforeRetirementInDays its not working. Because the first letter needs to be captital D so "DeviceInactivityBeforeRetirementInDays"

Without captital D:
`Invoke-RestMethod -Uri "$uri/deviceManagement/managedDeviceCleanupSettings" -Method 'PATCH' -Headers @{"Authorization" = $BearerToken } -ContentType 'application/json' -Body "{`"deviceInactivityBeforeRetirementInDays`":`"180`"}"`

Output
```
Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At line:1 char:1
+ Invoke-RestMethod -Uri "$uri/deviceManagement/managedDeviceCleanupSet ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

With capital D:

`Invoke-RestMethod -Uri "$uri/deviceManagement/managedDeviceCleanupSettings" -Method 'PATCH' -Headers @{"Authorization" = $BearerToken } -ContentType 'application/json' -Body "{`"DeviceInactivityBeforeRetirementInDays`":`"180`"}"`

Output
```
@odata.context                                                                           deviceInactivityBeforeRetirementInDays
--------------                                                                           --------------------------------------
https://graph.microsoft.com/beta/$metadata#deviceManagement/managedDeviceCleanupSettings 180
```

So when i look at intune i see the request there is also with capital D. is it possible to change it for all places to capital or without captital in the graph?

Kind regards
Steven 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 222c111e-12a0-0c07-2f81-09441b41212e
* Version Independent ID: f661b659-4615-69ce-a1cc-b50ac684dc44
* Content: [managedDeviceCleanupSettings resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-manageddevicecleanupsettings?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-devices-manageddevicecleanupsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-devices-manageddevicecleanupsettings.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by xven0mxz** [comment]
Any update?

**Comment by isvargasmsft** [comment]
Hello @xven0mxz, 

My apologies for the delay and thank you very much for bringing this into our attention. 

I am currently working with the product team and they mentioned that this is a bug: the convention is to start with lowercase letter. 

We are working with the team to either make the change in the API or update the documentation. 

Please bear with us in the meantime. 

Kind regards, 

Isaac Vargas

**Comment by isvargasmsft** [comment]
Hello @xven0mxz, 

Thank you very much for your patience. 

The product team is already working to resolve the bug and an engineer is assigned to the case.

Our deepest thanks for bringing this into our attention. 

Best regards, 

Isaac Vargas
