### ISSUE TITLE
add member method wrongly states that you can use graph to add members to a mail-enabled group

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs#13843]
You cannot use Microsoft Graph to add members to a mail-enabled group.  This document is out of sync with this document: https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @RayGHeld for raising this issue. You can actually create a a mail-enabled Microsoft 365 group and add members  during and after group creation. You must explicitly specify the **groupTypes** property and set it to "Unified".

**Sample request:**
```json
POST https://graph.microsoft.com/beta/groups
Content-type: application/json

{
    "description": "Test mail-enabled group with members",
    "displayName": "GitHub issue #13843",
    "mailEnabled": true,
    "groupTypes": [
        "Unified"
    ],
    "securityEnabled": false,
    "mailNickname": "TestMailEnabled",
    "owners@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/4562bcc8-c436-4f95-b7c0-4f8ce89dca5e"
    ],
    "members@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/4562bcc8-c436-4f95-b7c0-4f8ce89dca5e",
        "https://graph.microsoft.com/v1.0/users/6ea91a8d-e32e-41a1-b7bd-d2d185eed0e0"
    ]
}
```

When you run the same query but exclude the groupTypes property, I believe Azure AD assumes you are trying to create a mail-enabled security group, which isn't supported by the API; hence the error message: "_The service does not currently support writes of mail-enabled groups. Please ensure that the mail-enablement property is unset and the security-enablement property is set._"
