### ISSUE TITLE
GA ETA

### ISSUE THREAD

**Issue by sopelt** [microsoftgraph/microsoft-graph-docs#13849]
As previously discussed in https://github.com/microsoftgraph/microsoft-graph-docs/issues/12115 are there any updates on the timeline? Any roadblocks that prevent this and the SDK generation (see https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/277 ) of the corresponding functions?

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41875000-44f1-106d-5603-fb41e00666d4
* Version Independent ID: f7c55985-8bab-e3f7-1681-5d4078f90f71
* Content: [callRecord: getDirectRoutingCalls - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/callrecords-callrecord-getdirectroutingcalls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @williamlooney
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by williamlooney** [comment]
These APIs are live on the 1.0 endpoint, but the documentation updates are still being reviewed and completed. As of today, I would expect this to be completed by no later than ~8/30 but this is not a binding commitment.

**Comment by sopelt** [comment]
Hi @williamlooney , thank you for the swift reply. For both

```
GET https://graph.microsoft.com/1.0/communications/callRecords/getDirectRoutingCalls
```

and

```
GET https://graph.microsoft.com/1.0/communications/callRecords/getPstnCalls
```

I get

```
HTTP/1.1 404 Not Found
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Europe","Slice":"E","Ring":"4","ScaleUnit":"005","RoleInstance":"DU6PEPF00000100"}}

{
  "error": {
    "code": "ResourceNotFound",
    "message": "Invalid version: 1.0",
    "innerError": {
      "date": "2021-08-24T08:19:53",
      "request-id": "a4d3f1c8-933b-413f-8d80-a950627e007d",
      "client-request-id": "a4d3f1c8-933b-413f-8d80-a950627e007d"
    }
  }
}
``` 

which does not look like they are there yet. Is this a regional issue? Did the actual url change?

Thanks.

**Comment by williamlooney** [comment]
Hi @sopelt 

You need to include` v1.0` instead of `1.0` for accessing the 1.0 graph endpoint, so try

`GET https://graph.microsoft.com/v1.0/communications/callRecords/getDirectRoutingCalls`

instead of 

`GET https://graph.microsoft.com/1.0/communications/callRecords/getDirectRoutingCalls`

Team confirmed these reports are live on the v1.0 endpoint. Latest update is the Docs should be published next week (barring unforeseen issues)

**Comment by sopelt** [comment]
My bad, sorry. It now works as expected. Thanks!
