### ISSUE TITLE
Missing lobbyBypassSetting for "People I invite"

### ISSUE THREAD

**Issue by kamilzzz** [microsoftgraph/microsoft-graph-docs#13935]
Looking at the documentation I cannot find a value for bypass scope "invited users".
On the meeting options page I can select:
![![image](https://user-images.githubusercontent.com/32141632/130336938-5e405f45-7743-46bf-928e-3356e3a50cc2.png)](https://user-images.githubusercontent.com/32141632/130336933-80b99453-e7ca-4bb5-8d86-56570a2c68d8.png)
After saving that and retrieving meeting using MS Graph api the bypassScope is set to unknownFutureValue (while looking at the meeting options page network activity it is using different api - not ms graph - and is sending invited users value).
![image](https://user-images.githubusercontent.com/32141632/130336940-0b564df9-20c2-491e-99e6-c200ffc06321.png)

I'm wondering if it's possible to create onlineMeeting using MS Graph with "invited users" lobby bypass setting. unknownFutureValue doesn't seem convincing to me and POST request does not accept that value ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc60e96-a33b-0215-9379-159441e1d264
* Version Independent ID: fd766161-59b1-3983-ad48-23f4cb23a7bb
* Content: [lobbyBypassSettings resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/lobbybypasssettings?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/lobbyBypassSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/lobbyBypassSettings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mkhribech
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frankpeng7** [comment]
Hi @kamilzzz thanks for reporting this. `unknownFutureValue` is a read-only flag used to represent values we don't yet support and unfortunately Graph API does not support "People I invite" at this moment. I can't provide an ETA but I already put this request in our backlog and will work on it.
