### ISSUE TITLE
Unsupported filter example

### ISSUE THREAD

**Issue by mmschouten** [microsoftgraph/microsoft-graph-docs#13942]
One of the examples of the [filter queries](https://docs.microsoft.com/en-us/graph/query-parameters#examples-using-the-filter-query-operator) suggests that this is a valid query:
../users?$filter=assignedPlans/any(a:a/servicePlanId eq 2e2ddb96-6af9-4b1d-a3f0-d6ecfd22edb2 and a/capabilityStatus eq 'Suspended')&$count=true

It is even noted that this is an advanced query. This query does not work and throws an error:
"code": "Request_UnsupportedQuery",
"message": "Complex query on property assignedPlans is not supported." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f6304a-ab90-8543-39c7-2afd61197ffb
* Version Independent ID: 9ca019b5-063f-33a2-3cb9-3ab6baafe9d4
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmschouten** [comment]
Overlooked the requirement to add the 'ConsistencyLevel' header to the request

**Comment by FaithOmbongi** [comment]
Thank you @mmschouten for raising this issue and identifying the problem.
