### ISSUE TITLE
Docs clarification - Expiration Type

### ISSUE THREAD

**Issue by J-a-k-o-b** [microsoftgraph/microsoft-graph-docs#13941]
Hi,

the docs contains an example where an text is used for the Property "type", but this will result in a model error message.
If you're using the int-value which is described in the table (see screenshot), it works like expected.

![image](https://user-images.githubusercontent.com/46894290/130414680-a2bdb2df-df40-4d2f-8b59-ad145067204b.png)

Regards
Jakob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8b9d6e-dc27-9fe8-f084-befb1abb4e2c
* Version Independent ID: 28325e02-ad24-40a7-3a13-d375d2eaac9e
* Content: [expirationPattern resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/expirationpattern.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @J-a-k-o-b for raising this issue. For this Enum type, can use either the int value (therefore `"type": 2`), or it's member equivalent (`"type": "afterDateTime"`).

Could you share the link to the incorrectly represented example so I can fix the doc? Thanks.

**Comment by J-a-k-o-b** [comment]
Hi @FaithOmbongi,
working with the equivalent results in an error message:
See this screenshots:
Using the integer value 2 (Status 200 - Everything is fine):
![image](https://user-images.githubusercontent.com/46894290/130560326-fd1a7370-8da2-449e-bcd1-95f26566c317.png)

Using the text value (Status 400 - Bad Request):
![image](https://user-images.githubusercontent.com/46894290/130560389-62e62000-4144-447b-9fae-0da92d253080.png)

**Comment by FaithOmbongi** [comment]
Ah, thanks for the clarification. So it's the Enum String member that isn't working.
If it isn't too much trouble, could you test with **AfterDateTime** instead of afterDateTime and share the feedback? Capitalize **A**.

BTW, even though type accepts the **int** value when passed as a String, the correct declaration is the int value without the quotes. I believe your query (**int** value passed as a String) would throw an error if you were using the .NET SDKs.

**Comment by J-a-k-o-b** [comment]
That worked @FaithOmbongi, the capitalized A was the trick. Than you only have to update the docs with that information and maybe a hint that capitalization matters.
Thank you for the hint with the int -> string topic.

**Comment by FaithOmbongi** [comment]
Thanks for the confirmation @J-a-k-o-b . Let me first check in with the product team if this could be a product bug (if it should accept either, small **a** only, or capitalized **A** only) then raise a PR to fix the article.
