### ISSUE TITLE
Optional parameters section incomplete

### ISSUE THREAD

**Issue by faboo** [microsoftgraph/microsoft-graph-docs#13953]
"This method supports the OData Query Parameters to help customize the response."

The above is only sort of helpful, since the linked-to page lists several options that aren't supported (like filter and search) - the only way to know which OData parameters are supported seems to be trial-and-error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac52a23b-0065-5a60-15ae-0b774938af12
* Version Independent ID: 9db72af9-0b04-5228-3ec2-b0ca49d9ed01
* Content: [List posts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/conversationthread-list-posts?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/conversationthread-list-posts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/conversationthread-list-posts.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @faboo for raising this issue. Only `$select` and `$expand` OData query parameters are confirmed to be supported by the Posts API. I've raised a PR to indicate this in the docs.
