### ISSUE TITLE
mgt-spfx not working

### ISSUE THREAD

**Issue by RamaKaryam** [microsoftgraph/microsoft-graph-docs#13958]
# Manifest not found for component id "78b11c7d-7ca8-47cb-a93c-d3beabb519a1" and version "2.0.0".
I followed this article exactly https://docs.microsoft.com/en-us/graph/toolkit/get-started/mgt-spfx
Did as mentioned in the 'React' section of the above article.
Tenant-wide deployed v2.2.1 of mgt-spfx library from here https://github.com/microsoftgraph/microsoft-graph-toolkit/releases
My package.json is below. There is not much to the webpart actually. Its basically the same as that outlined in the article.
{
  "name": "sample",
  "version": "0.0.1",
  "private": true,
  "main": "lib/index.js",
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/mgt-react": "^2.2.1",
    "@microsoft/mgt-spfx": "^2.2.1",
    "@microsoft/sp-core-library": "1.12.1",
    "@microsoft/sp-lodash-subset": "1.12.1",
    "@microsoft/sp-office-ui-fabric-core": "1.12.1",
    "@microsoft/sp-property-pane": "1.12.1",
    "@microsoft/sp-webpart-base": "1.12.1",
    "office-ui-fabric-react": "7.156.0",
    "react": "16.9.0",
    "react-dom": "16.9.0"
  },
  "devDependencies": {
    "@types/react": "16.9.36",
    "@types/react-dom": "16.9.8",
    "@microsoft/sp-build-web": "1.12.1",
    "@microsoft/sp-tslint-rules": "1.12.1",
    "@microsoft/sp-module-interfaces": "1.12.1",
    "@microsoft/sp-webpart-workbench": "1.12.1",
    "@microsoft/rush-stack-compiler-3.7": "0.2.3",
    "gulp": "~4.0.2",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1"
  }
}
![image](https://user-images.githubusercontent.com/32988250/130558318-9074d520-9c3c-4791-b76f-e9d0ee4476b9.png)

@waldekmastykarz @nmetulev 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4583d84d-7495-fe6b-0405-d625c8d3db22
* Version Independent ID: 49bf7e2c-2ae6-6a41-579b-5ac5903df8a4
* Content: [SharePoint Framework library for Microsoft Graph Toolkit - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/get-started/mgt-spfx)
* Content Source: [concepts/toolkit/get-started/mgt-spfx.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toolkit/get-started/mgt-spfx.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @waldekmastykarz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by waldekmastykarz** [comment]
Thank you for reporting the issue and sorry for the trouble. Can you share your project so that we can repro it?

**Comment by RamaKaryam** [comment]
@waldekmastykarz  I uploaded the sample I have here: https://github.com/RamaKaryam/mgt-spfx-ver-issue
Also, I downloaded the source code zip file for v2.2.1 from here https://github.com/microsoftgraph/microsoft-graph-toolkit/releases
In microsoft-graph-toolkit-2.2.1\packages\mgt-spfx\config\package-solution.json and in the manifest for the library, the version number is 2.0.0.0. 
In the sppkg file itself, everything is 2.2.1.
That is just me poking around though. Thank you for the quick response. Sometimes I wonder if people around here have more than 24 hours/day.

**Comment by waldekmastykarz** [comment]
Thank you for the code. I can reproduce the error. Let me check if I can find out more about what's wrong.

**Comment by waldekmastykarz** [comment]
@RamaKaryam it seems like it's related to an issue with the mgt-spfx npm package (the mgt-spfx .sppkg file is correct). Let me verify it and get back to you as soon as I know more. Once again, thank you for reporting the issue and sorry for the trouble.

**Comment by RamaKaryam** [comment]
Thanks you for looking into this. In the meantime, gulp serve is doing fine.

**Comment by waldekmastykarz** [comment]
Just wanted to let you know that we haven't forgotten about this issue and it's still being investigated. Thank you for bearing with us 😊

**Comment by RamaKaryam** [comment]
Got it. Thank you for the update.

**Comment by AJIXuMuK** [comment]
Hello @RamaKaryam,
Thank you for reporting the issue and sorry for the delay.
The thing here is your web part is isolated. And isolated web parts don't support referencing of library components due to security reasons.

But from other side, as the isolated web part is running in iframe, you should be able to use standard MGT modules without a risk of crashing the whole page.

**Comment by RamaKaryam** [comment]
Understood. I will switch to mgt modules. May be you want to call it out somewhere? And next time, I will paste the package-solution.json as well, just so I don't send you guys on a wild goose chase. Thank you @waldekmastykarz  and @AJIXuMuK .

**Comment by waldekmastykarz** [comment]
We'll definitely update the guidance. Once again, thank you for bringing it to our attention and helping us find out what's wrong. 👏
