### ISSUE TITLE
Clarification - Duration Unit

### ISSUE THREAD

**Issue by J-a-k-o-b** [microsoftgraph/microsoft-graph-docs#13959]
Hi,

please clarify how to use the afterDuration Value. What is the unit we have to use here and how to insert it. With a simple int value i get an error (Status 400 - Bad Request: The model is invalid)

![image](https://user-images.githubusercontent.com/46894290/130560871-b813b29f-b9fa-48c8-81e8-d64e7db68111.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d8b9d6e-dc27-9fe8-f084-befb1abb4e2c
* Version Independent ID: 28325e02-ad24-40a7-3a13-d375d2eaac9e
* Content: [expirationPattern resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/expirationpattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/expirationpattern.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @J-a-k-o-b for raising this issue. **afterDuration** and the **duration** property are mutually dependent and the value for duration is specified in ISO 8601 format for Duration date/time types. Assuming the 10 intends to refer to 10 hours, your expiration object would be configured as:

```json
"expiration": {
      "@odata.type": "microsoft.graph.expirationPattern",
      "type": "afterDuration",
      "duration": "PT10H"
    }
}
```

or 

```json
"expiration": {
      "@odata.type": "microsoft.graph.expirationPattern",
      "type": 3,
      "duration": "PT10H"
    }
}
```

**Comment by J-a-k-o-b** [comment]
Hi @FaithOmbongi,
thank you for the explanation. It should be described somewhere.

And
"type": 3 
results in a 400 error /InvalidModel
if I use
"type": "afterDuration"
also
It works with 
"type" "AfterDuration"

So, a similar issue like 
https://github.com/microsoftgraph/microsoft-graph-docs/issues/13941
but additionally the int value doesn't work

**Comment by FaithOmbongi** [comment]
Thanks @J-a-k-o-b for this feedback. Let me add it to the internal report so that the configuration of the **type** property of [expirationPattern resource](https://docs.microsoft.com/en-us/graph/api/resources/expirationpattern?view=graph-rest-beta)  is fully investigated.

I've also [raised a PR](https://github.com/microsoftgraph/microsoft-graph-docs/pull/13962) to clarify how **duration** and **type** properties are set.
