### ISSUE TITLE
Not able to get "sortOrderIndex" property through API call but it is mentioned in API call response in documentation

### ISSUE THREAD

**Issue by ChetanSharma-msft** [microsoftgraph/microsoft-graph-docs#13988]
Not able to get "sortOrderIndex" property through API call but it is mentioned in API call response in documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9985f38-783f-6b81-cf25-febcfd6cfb0d
* Version Independent ID: 163fb5ba-7597-bda8-0670-ca6ded3de2ea
* Content: [Get tab in channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-get-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
This issue is related to doc enhancement so redirecting it.
