### ISSUE TITLE
Example Provided Doesn't contain $ref whereas Http Request Definition Does

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs#14004]
Http Request:
```
POST /organization/{id}/certificateBasedAuthConfiguration/$ref
```
Example Provided:
```
POST https://graph.microsoft.com/v1.0/organization/{id}/certificateBasedAuthConfiguration
Content-type: application/json

{
  "certificateAuthorities": [
    {
      "isRootAuthority": true,
      "certificate": "Binary"
    }
  ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bde2f57-570d-b42f-1ce3-fd4ffc352959
* Version Independent ID: 6d070ac8-69ed-aa64-b0a1-a29afb188769
* Content: [Create certificateBasedAuthConfiguration - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/certificatebasedauthconfiguration-post-certificatebasedauthconfiguration.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @adimitui
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Closing this issue because it was resolved through this commit https://github.com/microsoftgraph/microsoft-graph-docs/commit/769dba058530610ce2bc26c5a5ac3a3563acba38
