### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3/Interceptor at HttpClients.createDefault(authenticationProvider)

### ISSUE THREAD

**Issue by rodrigoguariento** [microsoftgraph/microsoft-graph-docs#14015]
I've followed this instructions https://docs.microsoft.com/en-us/graph/sdks/sdk-installation#install-the-microsoft-graph-java-sdk-via-maven to install SDK version `[5.0,)`. 

When I run the following code I receive the message "java.lang.NoClassDefFoundError: okhttp3/Interceptor" at first line:

```
final OkHttpClient httpClient = HttpClients.createDefault(authenticationProvider)
                                .newBuilder()
                                .followSslRedirects(false) // sample configuration to apply to client
                                .build();

final GraphServiceClient graphServiceClient = GraphServiceClient
                .builder()
                .httpClient(httpClient)
                .buildClient();
```

The code above is into https://docs.microsoft.com/en-us/graph/sdks/customize-client?tabs=java , then I've downloaded the following JARs into my Server Runtime ( /opt/tomcat85/lib/ in my laptop ):

- logging-interceptor-4.9.1.jar
- okhttp-4.9.1.jar
- kotlin-stdlib-1.4.10.jar
- okio-2.8.0.jar

Maven should have managed these packages, considering they are dependencies of com.microsoft.graph:microsoft-graph:jar:5.0.0?

The steps above ran fine, but when I've tried to work with BatchRequest, I got the following result:

```
java.lang.LinkageError: loader constraint violation: loader org.apache.catalina.loader.ParallelWebappClassLoader @30f74657 wants to load interface okio.BufferedSink. A different interface with the same name was previously loaded by java.net.URLClassLoader @2cfb4a64. (okio.BufferedSink is in unnamed module of loader java.net.URLClassLoader @2cfb4a64, parent loader 'app')
java.base/java.lang.ClassLoader.defineClass1(Native Method)
	java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2408)
	org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:855)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1327)
	org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	com.microsoft.graph.http.CoreHttpProvider$1.writeTo(CoreHttpProvider.java:332)
	okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:59)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	com.microsoft.graph.httpcore.RedirectHandler.intercept(RedirectHandler.java:137)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	com.microsoft.graph.httpcore.RetryHandler.intercept(RetryHandler.java:176)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	com.microsoft.graph.httpcore.AuthenticationHandler.intercept(AuthenticationHandler.java:59)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	com.microsoft.graph.httpcore.TelemetryHandler.intercept(TelemetryHandler.java:68)
	okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:403)
	com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:222)
	com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:199)
	com.microsoft.graph.content.BatchRequest.post(BatchRequest.java:60)
        com.guariento.task.directory.MicrosoftGroup.processBatchRequestMembers(MicrosoftGroup.java:268)
```

Is this a bug? Is this message a result of JARs manually entered into Server Runtime? Do you have suggestions?

I note that this code snippet was working correctly in previous versions prior to SDK 5. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e4ed6e9-9444-39d0-2a45-920ca4eecd6c
* Version Independent ID: 6e4d2087-45ae-806c-5be6-25c880c8bc12
* Content: [Install the Microsoft Graph SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/sdk-installation)
* Content Source: [concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/sdk-installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Thanks for the additional details.

I don't believe you should be pushing jars manually to the server, as linking may not happen the right way and/or some files might be missing in this process. You should instead package your application (as a WAR file most likely) or using a deployment tool (tomcat manager) and deploy it as a whole.

For the service library the only [dependency changes that happened between 3.3.0 and 5.1.0](https://github.com/microsoftgraph/msgraph-sdk-java/compare/3.3.0...5.1.0#diff-02b139e755ab0e27e0b0a6f9845843ef189116955cc340c49a4022587dbb2b52) (look for dependencies.gradle) are:
- google gson changed from 2.8.7 to 2.8.8
- graph core changed from 2.0.1 to 2.0.8

And the only [dependency changes that happened in core](https://github.com/microsoftgraph/msgraph-sdk-java-core/compare/2.0.1...2.0.8#diff-02b139e755ab0e27e0b0a6f9845843ef189116955cc340c49a4022587dbb2b52) are:
- google gson from 2.8.6 to 2.8.8
- azure identity replaced by azure core 1.18.0

By far the biggest change is the azure identity one and you should look in this area (and its dependencies).

**Comment by rodrigoguariento** [comment]
Thank you @baywet , again I rummaged through everything I could and found the solution. I end up saw in my pom.xml was wrong (after run `mvn versions:use-latest-releases` I suppose):
```
<dependency>
  <groupId>com.microsoft.graph</groupId>
  <artifactId>microsoft-graph</artifactId>
  <version>5.0.0</version>
</dependency>
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>1.3.5</version>
</dependency>
```

I changed back to ( https://docs.microsoft.com/en-us/graph/sdks/sdk-installation#install-the-microsoft-graph-java-sdk-via-maven ) that now is:
```
<dependency>
  <groupId>com.microsoft.graph</groupId>
  <artifactId>microsoft-graph</artifactId>
  <version>[5.0,)</version>
</dependency>
<dependency>
  <groupId>com.azure</groupId>
  <artifactId>azure-identity</artifactId>
  <version>[1.3,)</version>
</dependency>
```

After this, the okhttp 4.9.0 worked:
```
<dependency>
  <groupId>com.squareup.okhttp3</groupId>
  <artifactId>okhttp</artifactId>
  <version>4.9.0</version>
</dependency>
```

Thank you!

**Comment by FaithOmbongi** [comment]
Thanks @rodrigoguariento for confirming resolution; @baywet, @ramsessanchez for helping to resolve the issue.
