### ISSUE TITLE
What will happen with the data of a custom attribute (Azure B2C) when you remove a custom attribute

### ISSUE THREAD

**Issue by LockTar** [microsoftgraph/microsoft-graph-docs#14030]
I opened https://github.com/MicrosoftDocs/azure-docs/issues/78069 a while ago because the documentation is not really clear. Your colleague @yoelhor [asked me](https://github.com/MicrosoftDocs/azure-docs/issues/78069#issuecomment-901255668) to open this ticket for confirmation from this team on this subject. See his last [comment about the AAD documentation](https://github.com/MicrosoftDocs/azure-docs/issues/78069#issuecomment-901255668).

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 098167ab-8401-9d23-6782-e7d0b58f38e3
* Version Independent ID: 6ce8313c-db6d-19cd-41dc-72cfa8c26fb1
* Content: [extensionProperty resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/extensionproperty?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/extensionproperty.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @LockTar for raising this issue.

> What will happen with the data of a custom attribute (Azure B2C) when you remove a custom attribute 

If you delete the custom attribute without first setting its value to `null`, the extension property isn't queryable on the directory object, **its data is inaccessible, and there's nothing you can do with both the property and the data.**

But, you may restore the accessibility of the extension. From the [Azure AD Graph documentation](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/howto/azure-ad-graph-api-directory-schema-extensions?source=docs#extension-behavior-and-limitations--):

![image](https://user-images.githubusercontent.com/14026935/131376090-357bd61b-cd25-427b-907d-8b2c17f8808a.png)

Unfortunately, this forum is for documentation gaps/bugs only. For more technical support on restoring the accessibility of the extension property and its data, kindly repost this question at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-extensions.html). 

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.

**Comment by LockTar** [comment]
@FaithOmbongi this was actually the confirmation that I needed. Then my workaround for the problem with the graph api will work. 

In my opinion the documentation of B2C is then not correct or not fully up to date. I will open a new ticket there. Thanks!
