### ISSUE TITLE
Example is Invalid

### ISSUE THREAD

**Issue by jagrock** [microsoftgraph/microsoft-graph-docs#14036]
Under the https://docs.microsoft.com/en-us/graph/query-parameters#examples-using-the-filter-query-operator there is a complex query that returns an error.  It would be good to have a proper example of an advanced/complex query like this or a statement that these are not valid.

Example in doc:  
GET ../users?$filter=assignedPlans/any(a:a/servicePlanId eq 2e2ddb96-6af9-4b1d-a3f0-d6ecfd22edb2 and a/capabilityStatus eq 'Suspended')&$count=true

When executing this, both on v1.0 and beta, the return is below.

"code": "Request_UnsupportedQuery"
 "message": "Complex query on property assignedPlans is not supported."

If you try something similar:

GET ../users?$filter=assignedLicenses/any(x:x/skuId eq 1e1a282c-9c54-43a2-9310-98ef728faace or x/skuId eq 8e7a3d30-d97d-43ab-837c-d7701cef83dc)

you get:  

"code": "BadRequest",
"message": "Invalid filter clause",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f6304a-ab90-8543-39c7-2afd61197ffb
* Version Independent ID: 9ca019b5-063f-33a2-3cb9-3ab6baafe9d4
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jagrock for raising this issue. Kindly add the **ConsistencyLevel** header and set to `eventual`. For more information see the [Advanced query capabilities on Azure AD directory objects](https://docs.microsoft.com/en-us/graph/aad-advanced-queries).

[Try in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DassignedPlans%2Fany(a%3Aa%2FservicePlanId%20eq%202e2ddb96-6af9-4b1d-a3f0-d6ecfd22edb2%20and%20a%2FcapabilityStatus%20eq%20'Suspended')%26%24count%3Dtrue&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=eyJAb2RhdGEudHlwZSI6Im1pY3Jvc29mdC5ncmFwaC5vcGVuVHlwZUV4dGVuc2lvbiIsImV4dGVuc2lvbk5hbWUiOiJhc2tNZUFib3V0IiwidG9waWNzIjoiTWljcm9zb2Z0IEdyYXBoIFJFU1QgQVBJIiwib3RoZXJDb250YWN0cyI6W3siZ2l0SHViYWxpYXMiOiJvbWJvbmdpbW9yYWEiLCJwZXJzb25hbE1haWwiOiJvbWJvbmdpLm1vcmFhLmZlQGdtYWlsLmNvbSIsImZvckZ1biI6ImNvb2tpbmcsIGVhdGluZywgbW92aWVzLCBtZSB0aW1lIn1dfQ==&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
