### ISSUE TITLE
Please explain if GET and POST are both required

### ISSUE THREAD

**Issue by Mike-Crowley** [microsoftgraph/microsoft-graph-docs#14056]
The HTTP request section shows both a POST to one URI and a GET to another. Are there two APIs for dismissing risky users, one requiring POST and the other GET? Why do both examples use POST? Why are there two URIs and why are there two Methods, with one unused?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972ebfab-90e6-a0d9-3e99-01deeeb1c791
* Version Independent ID: bef697c7-2687-5559-af79-1e3c9f74f94f
* Content: [Dismiss riskyUser - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/riskyusers-dismiss?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/riskyusers-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/riskyusers-dismiss.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Mike-Crowley for raising this issue. The `GET /identityProtection/riskyUsers/dismiss` path is inaccurate. It should be `POST /identityProtection/riskyUsers/dismiss`. However, we recommend that you use `POST /riskyUsers/dismiss` instead. I'll raise a PR to fix the article.

**Comment by Mike-Crowley** [comment]
Can you explain why one uri is preferred over the other?


-Mike Crowley
________________________________

**Comment by FaithOmbongi** [comment]
Hi @Mike-Crowley , running `POST /identityProtection/riskyUsers/dismiss` has some known issues in that the risk might not be dismissed. We're working to resolve that and ensure both endpoints are supported.

**Comment by Mike-Crowley** [comment]
Interesting. That may explain some of the inconsistencies I experienced. but can the article also explain the difference between these two endpoints, when things aren't broken? i.e. why are there two?

**Comment by FaithOmbongi** [comment]
There only difference between the two endpoints is the path, but they return the same output. Also, please note that /beta which supports both endpoints is for public preview and is not recommended for production because such changes may occur.
