### ISSUE TITLE
Incorrect link to this page in Azure Portal

### ISSUE THREAD

**Issue by VitalyMCT** [microsoftgraph/microsoft-graph-docs#14064]
The link in Azure Portal uses an underscore instead of a dash, so it gives 404:

![image](https://user-images.githubusercontent.com/1765732/131581035-257f39f0-1898-4663-b886-e2460690ee8d.png)

![image](https://user-images.githubusercontent.com/1765732/131581141-ba763fdf-107a-4ac6-b81b-f1a8b1bbd724.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@VitalyMCT Thank you for documenting this issue. I've forwarded to our portal team.

**Comment by FaithOmbongi** [comment]
This fix has been added to the resolution pipeline. Closing this issue.
