### ISSUE TITLE
Examples advanced query capabilities not working

### ISSUE THREAD

**Issue by maeni70** [microsoftgraph/microsoft-graph-docs#14074]
When trying the examples on the Graph API Explorer, there is always an error response with code "Request_UnsupportedQuery". 

Example:
GET https://graph.microsoft.com/v1.0/users?$filter=accountEnabled ne true&$count=true
ConsistencyLevel: eventual

{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported property filter clause operator 'NotEqualsMatch'.",
        "innerError": {
            "date": "2021-09-01T08:49:09",
            "request-id": "42eae13b-0c60-4d1f-bd07-dced22f788d3",
            "client-request-id": "42eae13b-0c60-4d1f-bd07-dced22f788d3"
        }
    }
}

Are these advanced query capabilities not supported anymore, or are there other ways now how to use ne, endswith etc. in the filter queries?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Azure AD directory objects - Microsoft Graph](https://docs.microsoft.com/en-us/graph/aad-advanced-queries)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/aad-advanced-queries.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Licantrop0
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @maeni70 for raising this issue. Kindly ensure that you're signed in and that you've set the **ConsistencyLevel** header to `eventual`. The error is because of one or both of these.

[Try in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DaccountEnabled%20ne%20true%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d).

**Comment by maeni70** [comment]
Ok, sorry. It was a bad example.

Please check this, which does not work ("Request_UnsupportedQuery"):
https://graph.microsoft.com/beta/users?$count=true&$filter=**endsWith**(DisplayName,'vasil')

However, no issue with this query:
https://graph.microsoft.com/beta/users?$count=true&$filter=**startsWith**(DisplayName,'vasil')

But no issue with this query (same operator endsWith):
https://graph.microsoft.com/beta/users?$count=true&$filter=**endsWith**(mail,'@outlook.com')

Are there any explanations for this behavior?

Thanks,
Roger

**Comment by FaithOmbongi** [comment]
Hi @maeni70 , for this scenario:

> Please check this, which does not work ("Request_UnsupportedQuery"):
> https://graph.microsoft.com/beta/users?$count=true&$filter=endsWith(DisplayName,'vasil')

**endsWith** operator is only supported on **mail** and **userPrincipalName** properties of directory objects as per this [list of common scenarios](https://docs.microsoft.com/en-us/graph/aad-advanced-queries#support-for-filter-on-properties-of-azure-ad-directory-objects). If you require `endsWith` to be supported on **displayName** or any other property, kindly [send us feedback](https://aka.ms/MsGraphAADSurveyDocs). Hope that helps.

**Comment by maeni70** [comment]
Thanks Ombongi! It was confusing as some queries in Graph API Explorer were just working without being authenticated, and for this reason I started trying different examples, instead of finishing to read the documentation.
Have a nice day.

**Comment by FaithOmbongi** [comment]
Thanks @maeni70. And a wonderful day to you!
