### ISSUE TITLE
C# samples not working

### ISSUE THREAD

**Issue by ohaak** [microsoftgraph/microsoft-graph-docs#14083]
Documentation is fine and code samples for C# would be indeed very helpful, if they were functional. Unfortunately the GraphServiceClient's constructor is expecting an implementation of IAuthenticationProvider and the code samples I've checked are not providing such.

I've searched for hours now and wasn't able to get the sample for using the username/password provider to compile.

If these samples ever had been correct, they seem to be broken now. And either way - I guess it might be helpfull to give a hint on the necessary packages or at least "using" statements for the code sample.

It's very frustrating to have to read half the internet to get some simple sample up-and-running. And in this case not even that seems to be possible.

I wouldn't even think about fiddeling with something like username/password authentication provider if there was an option to do all necessary stuff using app only authentication. Unfortunately it isn't and it seems to me that MS is more or less just ignoring the fact that a lot of necessary operations you have to handle e. g. in some kind of provisioning backend process are more or less broken that way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS&source=docs)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@ohaak for .NET you need the Azure.Identity package to get access to those auth provider implementations. This is stated in the **Note** block underneath the table of scenarios, which is admittedly not very discoverable. 

You mentioned not being able to do stuff with app-only - we do support app-only auth, but there are some APIs that don't support it, and it does require an admin to consent. If an API you need to use doesn't support app-only auth, you can create a feature request on [Microsoft Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph).

**Comment by ohaak** [comment]
@jasonjoh Thanks for your answer. Azure.Identity is installed, but Azure.Identity.UsernamePasswordCredential implements TokenCredential while the GraphServiceClient is expecting an object implementing IAuthenticationProvider. Don't see how that could ever work out.

Regarding app-only auth ... Yes, I know you do support it. And it really works fine for most of the stuff we need to do. But as you said yourself, there are some APIs that don't support app-only. 

Just one example: I want to set a sensitivity label to an existing M365 group. Doesn't work with app-only for whatever reason. That's my current motivaiton why I need to find a solution working with some kind of "service account".

**Comment by jasonjoh** [comment]
What version of the Graph SDK do you have? Azure.Identity support was added in 4.x.

**Comment by ohaak** [comment]
@jasonjoh  Well - that seems to be my issue. I'm still on 3.2.0. I'll try to update that stuff. Seem you've saved my day. Big thanks!

**Comment by jasonjoh** [comment]
No problem I hope that clears it up for you!

**Comment by ohaak** [comment]
@jasonjoh Sorry to bother you again ... I just updated my project's Microsoft.Graph nuget package to version 4.3.0, but unfortunately that doesn't change the fact that the GraphServiceClient is still expecting an IAuthenticationProvider and thus won't accept an instance of Azure.Identity.UsernamePasswordCredential. By the way, my version of Azure.Identity is 1.4.1.

**Comment by jasonjoh** [comment]
That's odd. I just created a new project with those same package versions, and it's showing the right constructor:

![image](https://user-images.githubusercontent.com/8966342/131709350-ee94be97-abfa-48cf-8138-75e14290e30a.png)

Is it possible that your Intellisense just hasn't updated with the new version?

To be sure, I ran the following code with no issue.

```
using System;
using System.Threading.Tasks;
using Azure.Identity;
using Microsoft.Graph;

namespace UserNamePassword
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var scopes = new[] { "User.Read" };

            // Multi-tenant apps can use "common",
            // single-tenant apps must use the tenant ID from the Azure portal
            var tenantId = "YOUR_TENANT_ID";

            // Value from app registration
            var clientId = "YOUR_APP_ID";

            var options = new TokenCredentialOptions
            {
                AuthorityHost = AzureAuthorityHosts.AzurePublicCloud
            };

            var userName = "lynner@contoso.com";
            var password = "SuperSecretPassword";

            var userNamePasswordCredential = new UsernamePasswordCredential(
                userName, password, tenantId, clientId, options);

            var graphClient = new GraphServiceClient(userNamePasswordCredential, scopes);

            try
            {
                var me = await graphClient.Me.Request().GetAsync();

                Console.WriteLine($"Hello {me.DisplayName}!");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}
```

**Comment by ohaak** [comment]
@jasonjoh Seemed to have been some hickup with my Visual Studio. It's now accepting the UsernamePasswordCredential as TokenCredential and code builds. Thanks a lot!
