### ISSUE TITLE
Sentinel values are acceptable in code, not so sure about having them in an API

### ISSUE THREAD

**Issue by d-noll** [microsoftgraph/microsoft-graph-docs#14108]
I happened to spot this,

> The `visibleHistoryStartDateTime` property for a members added event in a channel is always set to `0001-01-01T00:00:00Z`, which indicates that all history is shared.

I get that this is the .NET epoch, but I think for most of the world, omitting the value would be a better API. If a value is "always" set to the same thing, you can omit the value.

On top of that, we also see `1970-01-01T00:00:00Z` erroneously returned from this API for some users, seemingly having the same meaning.

What I don't get is, if the meaning of the value is "the first time from which the user can see the history", why you wouldn't just set it to the instant the chat was created.

KISS principles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f608671f-92ef-4caf-a3cd-7e954bddea40
* Version Independent ID: 85e55cdb-9708-287b-399a-9b01288820ae
* Content: [membersAddedEventMessageDetail resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/membersaddedeventmessagedetail?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/membersaddedeventmessagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/membersaddedeventmessagedetail.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Multiple questions are asked so let me try to answer them one by one
- Why `0001-01-01T00:00:00Z` and not something else?
This is not about .Net epoch (btw epoch is same for everyone which is 1st Jan 1970). This is the EDM's minimum datetime value.

- Why not just omit it?
Omit can send weird or wrong message. Is it now? Or is it start of time? Always having a value avoids that guess work. So as you said it actually abides by KISS principal. No guess work it is just plain sentinel value. The event is shared with chats where the value has relevance.

- I see `1970-01-01T00:00:00Z` sometimes
Definitely an issue. We will look into it.

- What I don't get is, if the meaning of the value is "the first time from which the user can see the history", why you wouldn't just set it to the instant the chat was created.
Same as 1 above, setting it to some standard value is easier for parsing or just looking at it and taking a guess. There are also future implications (something that doesn't make sense to discuss right now coz it will take 2-3 pages). Certain sentinel values are also for future proofing the ACL checks for others.

**Comment by d-noll** [comment]
You say it's easier for parsing, but in reality it's actually harder for parsing than not having it, because now we have to take care of a special value.

And, if there are future implications, then the documentation should not say "always", but rather "currently".
