### ISSUE TITLE
Request for more complex examples

### ISSUE THREAD

**Issue by DeanGross** [microsoftgraph/microsoft-graph-docs#14129]
Could you please add an example that shows how to create a name location with many ipaddresses in the range attribute.

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a4987f-38c2-9709-79c1-1d3b51d2b6ef
* Version Independent ID: a40986f8-e23b-5c3c-8452-8bdf3821266e
* Content: [Create namedLocation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-namedlocations?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/conditionalaccessroot-post-namedlocations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/conditionalaccessroot-post-namedlocations.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @videor
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @DeanGross for raising this issue. Kindly look at [Example 1](https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-namedlocations?view=graph-rest-1.0&tabs=http#example-1-create-an-ipnamedlocation) which creates an ipNamedLocation object with two ip addresses. You may add more objects within the ipRanges object. Hope that helps.

**Comment by DeanGross** [comment]
@FaithOmbongi  thanks, I was not very clear. What I really meant was an example in which a large list of ip addresses is provided from a separate file to populate the ipRanges object. I can't figure out how to format and read values from a text file. this is easy to do for other powershell commands, but there appear to be some unique requirements for this cmdlet.

**Comment by FaithOmbongi** [comment]
Ah, noted @DeanGross . What you need is help with your code. Unfortunately, this forum is only for documentation bugs/gaps but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html). I recommend that you ask this question there so that you may receive additional guidance from engineers and other developers alike.

**Comment by DeanGross** [comment]
Many of the other powerhsell cmdlets have numerous examples in their help file. I'm just asking for more examples for this cmdlet. I have already spent many hours trying to do something that should be simple. This cmdlet is overly complex and is not consistent with the powershell design guidelines. This is the only cmd that I have ever seen that requires a list<t> attribute

**Comment by FaithOmbongi** [comment]
My apologies for the unpleasant experience. I wasn't aware that you're using the cmdlet. We are currently working to improve the examples in our Microsoft Graph PowerShell SDK. For issues specific to the Microsoft Graph PowerShell SDK, you may ask at [the channel](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues); However, I highly recommend using the [Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) for this scenario.
