### ISSUE TITLE
beta/users returns 403 Forbidden Neither tenant is B2C or tenant doesn't have premium license

### ISSUE THREAD

**Issue by mkeennon** [microsoftgraph/microsoft-graph-docs#14120]
App is a Service Principal app using client secret auth to login and get token.
App has privs to the users API with User.Read.All and AuditLog.Read.All with admin consent.
Calls to standard /users endpoint works fine.
Tenant is a standard enterprise tenant with AAD P1 license for all employees.
Call to beta endpoint succeeds maybe 1/10 times and fails with error below 9/10 times.
Goal is to use beta endpoint to retrieve user signInActivity. 
Request below works on standard /users without the signInActivity attribute so there is no issue with the msgraph schema extension or related filter.

Request URI:
https://graph.microsoft.com/beta/users/?$select=id,givenName,surname,mail,accountEnabled,createdDateTime,signInActivity,ejgallo_GalloAuthz&$filter=ejgallo_GalloUser/gwusertype eq 'distributor'
Options: {
method:'GET',
timeout:60000,
headers:{Accept: 'application/json', Content-Type: 'application/json', Authorization: 'Bearer eyJ0…WV2w'}
 }

Error:
error:{code: 'Authentication_RequestFromNonPremiumTenantOrB2CTenant', message: 'Neither tenant is B2C or tenant doesn't have premium license', innerError: {…}}
code:'Authentication_RequestFromNonPremiumTenantOrB2CTenant'
innerError:{date: '2021-09-02T14:32:39', request-id: '2501535b-2fd7-43e3-87db-c12cbe31fca0', client-request-id: '2501535b-2fd7-43e3-87db-c12cbe31fca0'}
message:'Neither tenant is B2C or tenant doesn't have premium license'

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f291cb-b55b-4b55-c42a-cec61e5c4384
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph beta endpoint reference - Microsoft Graph beta](https://docs.microsoft.com/en-au/graph/api/overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/overview.md)
* Product: **non-product-specific**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
> Call to beta endpoint succeeds maybe 1/10 times and fails with error below 9/10 times.

Thank you @mkeennon for raising this issue. Unfortunately, this forum is only for documentation bugs/gaps but issues like these are investigated at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-users.html). Kindly post this question there and the team will assist to investigate this intermittent failure.

BTW, could you add the **Directory.Read.All** permission and see if you are still getting the error message: _Neither tenant is B2C or tenant doesn't have premium license_? If you are still getting the error, definitely ask this at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-users.html) so it can be investigated.

**Comment by mkeennon** [comment]
Directory.read.all solved the problem.

Thank you!

________________________________

**Comment by FaithOmbongi** [comment]
Good to know that fixed it. The error message was as a result of a bug which results in intermittent license check failures even though you have an active license. Adding the **Directory.Read.All** permission is a workaround but, the team is currently working to resolve the bug so that the directory permission won't be required.
