### ISSUE TITLE
Error when birthday field is specified in $select query parameter

### ISSUE THREAD

**Issue by dwanjuhi** [microsoftgraph/microsoft-graph-docs#14141]
From the documentation, the `birthday` parameter is returned on $select. When making a delta request for users and specifying the param, Graph responds with an error: 

 GET https://graph.microsoft.com/v1.0/users/delta?$select=id,userPrincipalName,givenName,surname,displayName,birthday,companyName,department,jobTitle,proxyAddresses,mail,otherMails,businessPhones,mobilePhone,faxNumber

Response: 

`     {  
         "error": {  
             "code": "BadRequest",  
             "message": "Invalid request for delta query: for this entity set, $expand/$select is not supported for the following properties: birthday",  
             "innerError": {  
                 "date": "2021-07-19T10:42:40",  
                 "request-id": "d13cd022-3883-4ac7-817b-bf1a4d464902",  
                 "client-request-id": "d13cd022-3883-4ac7-817b-bf1a4d464902"  
             }  
         }  
     } `

This issue was first reported by a customer on [Microsoft QnA:](https://docs.microsoft.com/en-us/answers/questions/481084/index.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dwanjuhi for raising this issue.

Yes, birthday is returned only on **$select**, but as indicated in the accepted answer and the [Optional query parameters](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) section, it's also returned only when retrieving a single user, not on a collection. So only` ../users/{user id}?$select=birthday` or `../me?$select=birthday` would work. Unfortunately, the **delta** function is only on collections.

I'd like to hear your ideas on how we can make this information more visible. Maybe we add a statement in the property descriptions, for example, `Returned only on $select and on a single GET request`.
