### ISSUE TITLE
Where do i find the list of allowed fields for 'driveItem'. 

### ISSUE THREAD

**Issue by ashishmittal-ally** [microsoftgraph/microsoft-graph-docs#14175]
Where do I find the list of allowed fields for 'driveItem'. I am specifically looking for createdBy user's email. The api is only returning the displayName of the user. 

https://docs.microsoft.com/en-us/graph/search-concept-files#example-6-specify-select-properties

`{
    "requests": [
        {
            "entityTypes": [
                "driveItem"
            ],
            "query": {
                "queryString": "ra contentType:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            },
            "fields": [
                "id",
                "name",
                "webUrl",
                "parentReference",
                "createdBy",
                "file"
            ]
        }
    ]
}`

`
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.searchResponse)",
    "value": [
        {
            "searchTerms": [
                "ra",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            ],
            "hitsContainers": [
                {
                    "total": 4,
                    "moreResultsAvailable": false,
                    "hits": [
                        {
                            "hitId": "01ZGPD2XOTZBRJRHUOXZFZ6SRNZSEJ7APA",
                            "rank": 1,
                            "summary": "5 6 7 8<ddd/>1 445 0 Microsoft Teams Services Microsoft Teams Web Client {9862C8D3<ddd/>",
                            "resource": {
                                "@odata.type": "#microsoft.graph.driveItem",
                                "id": "01ZGPD2XOTZBRJRHUOXZFZ6SRNZSEJ7APA",
                                "name": "Raw files from teams - bdi.xlsx",
                                "webUrl": "https://veossoft.sharepoint.com/sites/BDI/Shared Documents/General/Raw files from teams - bdi.xlsx",
                                "createdBy": {
                                    "user": {
                                        "displayName": "Anirudh R"
                                    }
                                },
                                "parentReference": {
                                    "driveId": "b!xFUmEZcAFEWjTY1iiaI78x11rlb9-_xFvEPdg_lKSnTYvxr3EFQkQIgsMzxmiQcN",
                                    "id": "01ZGPD2XKRGKJIQ4TWWND2MHIVJSLEOQ4Y",
                                    "siteId": "veossoft.sharepoint.com,112655c4-0097-4514-a34d-8d6289a23bf3,56ae751d-fbfd-45fc-bc43-dd83f94a4a74",
                                    "sharepointIds": {
                                        "listId": "f71abfd8-5410-4024-882c-333c6689070d",
                                        "listItemId": "3",
                                        "listItemUniqueId": "9862C8D3-8E9E-4BBE-9F4A-2DCC889F81E0"
                                    }
                                }
                            }
                        },
                        {
                            "hitId": "01ZGPD2XO2XZQR62AD2VGI4A2OE76HNC7A",
                            "rank": 2,
                            "summary": "5 6 7 8<ddd/>1 445 0 Microsoft Teams Services Microsoft Teams Web Client {1F61BEDA<ddd/>",
                            "resource": {
                                "@odata.type": "#microsoft.graph.driveItem",
                                "id": "01ZGPD2XO2XZQR62AD2VGI4A2OE76HNC7A",
                                "name": "Raw files from teams - personal chat.xlsx",
                                "webUrl": "https://veossoft.sharepoint.com/sites/BDI/Shared Documents/Channel 2/Raw files from teams - personal chat.xlsx",
                                "createdBy": {
                                    "user": {
                                        "displayName": "Anirudh R"
                                    }
                                },
                                "parentReference": {
                                    "driveId": "b!xFUmEZcAFEWjTY1iiaI78x11rlb9-_xFvEPdg_lKSnTYvxr3EFQkQIgsMzxmiQcN",
                                    "id": "01ZGPD2XKDIR6G7BOX7FAZF5G62CDS5DHE",
                                    "siteId": "veossoft.sharepoint.com,112655c4-0097-4514-a34d-8d6289a23bf3,56ae751d-fbfd-45fc-bc43-dd83f94a4a74",
                                    "sharepointIds": {
                                        "listId": "f71abfd8-5410-4024-882c-333c6689070d",
                                        "listItemId": "5",
                                        "listItemUniqueId": "1F61BEDA-0368-4CD5-8E03-4E27FC768BE0"
                                    }
                                }
                            }
                        },
                        {
                            "hitId": "01KKQUXX7JOTETLY7RLJA26P522MGN26IY",
                            "rank": 3,
                            "summary": "<c0>Ravishankar</c0> Prasad 1 0 Microsoft Teams Services Microsoft Teams Web Client {35C974E9<ddd/>",
                            "resource": {
                                "@odata.type": "#microsoft.graph.driveItem",
                                "id": "01KKQUXX7JOTETLY7RLJA26P522MGN26IY",
                                "name": "Raw files from teams - personal chat.xlsx",
                                "webUrl": "https://veossoft-my.sharepoint.com/personal/anirudh_veossoft_onmicrosoft_com/Documents/Microsoft Teams Chat Files/Raw files from teams - personal chat.xlsx",
                                "createdBy": {
                                    "user": {
                                        "displayName": "Anirudh R"
                                    }
                                },
                                "parentReference": {
                                    "driveId": "b!kM4gEdbeI0W1BnJ_CGYKCOCCJPZhcZ1Ig6i0CF8ubDEaL-PfB4P9RJm1bIJneXuw",
                                    "id": "01KKQUXXYKO7DHXMHI3BBLCMQ7J6YKP4R6",
                                    "siteId": "veossoft-my.sharepoint.com,1120ce90-ded6-4523-b506-727f08660a08,f62482e0-7161-489d-83a8-b4085f2e6c31",
                                    "sharepointIds": {
                                        "listId": "dfe32f1a-8307-44fd-99b5-6c8267797bb0",
                                        "listItemId": "4",
                                        "listItemUniqueId": "35C974E9-F1E3-415A-AF3F-BAD30CDD7918"
                                    }
                                }
                            }
                        },
                        {
                            "hitId": "01V6TNPXMIB2U5HRETBNAK3IV3W2KIF43V",
                            "rank": 4,
                            "summary": "5 6 7 8<ddd/>1 0 Microsoft Teams Services Microsoft Teams Web Client {D3A90E88<ddd/>",
                            "resource": {
                                "@odata.type": "#microsoft.graph.driveItem",
                                "id": "01V6TNPXMIB2U5HRETBNAK3IV3W2KIF43V",
                                "name": "Raw files from teams.xlsx",
                                "webUrl": "https://veossoft.sharepoint.com/sites/Veos/Shared Documents/General/Raw files from teams.xlsx",
                                "createdBy": {
                                    "user": {
                                        "displayName": "Anirudh R"
                                    }
                                },
                                "parentReference": {
                                    "driveId": "b!_jvuIRtDn0e9twk5x2SZ-B11rlb9-_xFvEPdg_lKSnTYvxr3EFQkQIgsMzxmiQcN",
                                    "id": "01V6TNPXKIGYZM3N4CHNA26ACRCN5SU2JA",
                                    "siteId": "veossoft.sharepoint.com,21ee3bfe-431b-479f-bdb7-0939c76499f8,56ae751d-fbfd-45fc-bc43-dd83f94a4a74",
                                    "sharepointIds": {
                                        "listId": "f71abfd8-5410-4024-882c-333c6689070d",
                                        "listItemId": "2",
                                        "listItemUniqueId": "D3A90E88-93C4-400B-ADA2-BBB69482F375"
                                    }
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ]
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yiwenwang-ms** [comment]
Hello, I suggest you use listItem instead current now.
and expand the fields, could you please have a try.

```
{
    "requests": [
        {
            "entityTypes": [
                "listItem"
            ],
            "query": {
                "queryString": "*"
            },
            "fields": [
                "AuthorOWSUSER",
                "EditorOWSUSER"
            ]
        }
    ]
}

```

**Comment by ashishmittal-ally** [comment]
I want to use driveItem because that matches my usecase. It contains `driveId` in `parentReference`. (listItem doesn't).

Where do i find a list of all the allowed fields?

**Comment by yiwenwang-ms** [comment]
Hi,

We will try to improve the functionality for this case.
Will let you know once the enhancement got released.

Best Regards,
Yiwen
________________________________

**Comment by yiwenwang-ms** [comment]
Hi @ashishmittal-ally, we've applied a new change to driveItem, it will released to PROD in two weeks.
![image](https://user-images.githubusercontent.com/78404769/133584188-accb06a2-da8f-4aaf-93f1-cf1e6b7bbbae.png)

**Comment by ashishmittal-ally** [comment]
Thanks for such a quick resolution. Also, please keep me informed of the release.

**Comment by yiwenwang-ms** [comment]
@ashishmittal-ally sure, thanks for your feedback. 
It should be released to WW next Tuesday(UTC+0). Please try it after next Tuesday and leave a comment, let us know if the issue got fixed.

**Comment by yiwenwang-ms** [comment]
@ashishmittal-ally Please help verify the change.

**Comment by ashishmittal-ally** [comment]
@yiwenwang-ms  its working now. I can see the users email in the response.

`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.searchResponse",
    "value": [
        {
            "searchTerms": [
                "personal",
                "chat",
                "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            ],
            "hitsContainers": [
                {
                    "total": 4,
                    "moreResultsAvailable": false,
                    "hits": [
                        {
                            "hitId": "01KKQUXX7JOTETLY7RLJA26P522MGN26IY",
                            "rank": 1,
                            "summary": "",
                            "resource": {
                                "@odata.type": "#microsoft.graph.driveItem",
                                "id": "01KKQUXX7JOTETLY7RLJA26P522MGN26IY",
                                "name": "Raw files from teams - personal chat.xlsx",
                                "webUrl": "https://veossoft-my.sharepoint.com/personal/anirudh_veossoft_onmicrosoft_com/Documents/Microsoft Teams Chat Files/Raw files from teams - personal chat.xlsx",
                                "createdBy": {
                                    "user": {
                                        "displayName": "Steve Smith",
                                        "email": "anirudh@veossoft.onmicrosoft.com"
                                    }
                                },
                                "parentReference": {
                                    "driveId": "b!kM4gEdbeI0W1BnJ_CGYKCOCCJPZhcZ1Ig6i0CF8ubDEaL-PfB4P9RJm1bIJneXuw",
                                    "id": "01KKQUXXYKO7DHXMHI3BBLCMQ7J6YKP4R6",
                                    "siteId": "veossoft-my.sharepoint.com,1120ce90-ded6-4523-b506-727f08660a08,f62482e0-7161-489d-83a8-b4085f2e6c31",
                                    "sharepointIds": {
                                        "listId": "dfe32f1a-8307-44fd-99b5-6c8267797bb0",
                                        "listItemId": "4",
                                        "listItemUniqueId": "35c974e9-f1e3-415a-af3f-bad30cdd7918"
                                    }
                                }
                            }
                        },
                        {
                            "hitId": "01ZGPD2XO2XZQR62AD2VGI4A2OE76HNC7A",
                            "rank": 2,
                            "summary": "",
                            "resource": {
                                "@odata.type": "#microsoft.graph.driveItem",
                                "id": "01ZGPD2XO2XZQR62AD2VGI4A2OE76HNC7A",
                                "name": "Raw files from teams - personal chat.xlsx",
                                "webUrl": "https://veossoft.sharepoint.com/sites/BDI/Shared Documents/Channel 2/Raw files from teams - personal chat.xlsx",
                                "createdBy": {
                                    "user": {
                                        "displayName": "Steve Smith",
                                        "email": "anirudh@veossoft.onmicrosoft.com"
                                    }
                                },
                                "parentReference": {
                                    "driveId": "b!xFUmEZcAFEWjTY1iiaI78x11rlb9-_xFvEPdg_lKSnTYvxr3EFQkQIgsMzxmiQcN",
                                    "id": "01ZGPD2XKDIR6G7BOX7FAZF5G62CDS5DHE",
                                    "siteId": "veossoft.sharepoint.com,112655c4-0097-4514-a34d-8d6289a23bf3,56ae751d-fbfd-45fc-bc43-dd83f94a4a74",
                                    "sharepointIds": {
                                        "listId": "f71abfd8-5410-4024-882c-333c6689070d",
                                        "listItemId": "5",
                                        "listItemUniqueId": "1f61beda-0368-4cd5-8e03-4e27fc768be0"
                                    }
                                }
                            }
                        }
                    ]
                }
            ],
            "resultTemplates": {}
        }
    ]
}`

**Comment by yiwenwang-ms** [comment]
Thanks, I will close this issue now.
