### ISSUE TITLE
Service principal sign-ins

### ISSUE THREAD

**Issue by airlinedev** [microsoftgraph/microsoft-graph-docs#14196]
[Enter feedback here]

Hi,

I'm having troubles finding any documentation on querying the Graph API for service principal sign-in logs. It looks like providing the query parameter source=sp does the trick, but I can't find documentation on this query parameter or querying these type of sign-in logs. Example: https://graph.microsoft.us/beta/auditLogs/signIns?source=sp works for getting service principal sign-in logs, but no documentation on the correct method or on the parameter "source".
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637c0260-f07d-b6d6-29ff-c21153daf742
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/signin-list.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @airlinedev for raising this issue. 

To query the logs based on, for example, service principal sign ins, you may apply filter on the **signInEventTypes** property that is currently in beta. We're currently working to document this and other undocumented properties.

**signInEventTypes** property represents the category of sign in for the event.  It's a String collection with the following possible values: `interactiveUser`, `nonInteractiveUser`, `servicePrincipal`, and `managedIdentity`. To retrieve specific signInEventTypes, for example, servicePrincipal types, you can run the following command:

   [https://graph.microsoft.com/beta/auditLogs/signIns?$filter=signInEventTypes/any(s:s eq 'servicePrincipal')](https://developer.microsoft.com/en-us/graph/graph-explorer?request=auditLogs%2FsignIns%3F%24filter%3DsignInEventTypes%2Fany(s%3As%20eq%20'servicePrincipal')&method=GET&version=beta&GraphUrl=https://graph.microsoft.com)

source is not a property of the signIns resource, but the hack that you shared seems to work. I'm following up about this internally and will share feedback.

**Comment by airlinedev** [comment]
Thanks Faith - the source=sp came from looking at API requests made by the browser when exploring the Azure AD blade

**Comment by FaithOmbongi** [comment]
Hi @airlinedev—thanks for confirming. That's the internal implementation of Microsoft Graph. To be on the safe side, kindly use the publicly available filter features.
