### ISSUE TITLE
Response seems not right, as it returns directory object not the id itself

### ISSUE THREAD

**Issue by farshad-alinta** [microsoftgraph/microsoft-graph-docs#14221]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7ee9be9-4ab9-6813-27a9-a39c55f111fa
* Version Independent ID: 0bc1f464-486d-5a11-182f-bd439f778547
* Content: [Get directoryObject - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryobject-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directoryobject-get.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @farshad-alinta for raising this issue. The response object has been truncated for readability but I must admit, this is too short and maybe misleading. I'll raise a PR to provide a fuller example.
