### ISSUE TITLE
expirationDateTime for a group object is GA in Microsoft Graph v1.0 but the example on page says otherwise. 

### ISSUE THREAD

**Issue by shashishailaj** [microsoftgraph/microsoft-graph-docs#14242]
This is related to MicrosoftDocs/azure-docs#80972 . As per the details from the customer , the **expirationDateTime** property for the group object is available on Microsoft Graph v1.0 and is GA . Earlier it was only available in MS Graph beta version. 

The example on the page needs to be updated to show the **expirationDateTime** property for v1.0 . It is already there in the [MS graph beta version](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta#example&preserve-view=true ) for group object . If the  **expirationDateTime** property is available , please do update this page and we can accordingly update the [main document](https://docs.microsoft.com/en-us/azure/active-directory/enterprise-users/groups-lifecycle#how-to-retrieve-microsoft-365-group-expiration-date) which says the following. 

![image](https://user-images.githubusercontent.com/532022/133126627-1e6b23b6-11e6-4859-b44b-242981f5d8e8.png)

cc: @curtand 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e064c0-4789-0ec7-1e7c-c36519049ffd
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http#example&preserve-view=true)
* Content Source: [api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @shashishailaj for raising this issue. I've raised a PR to include **expirationDateTime** in the response object. The change will go live at the end of the day when the PR is merged. You may update the link in the Azure docs to https://docs.microsoft.com/en-us/graph/api/group-get#example-1-return-all-default-properties, it will default to Example 1 of the v1.0 version of the doc. Thanks.
