### ISSUE TITLE
Broken (-ish) link to Exchange Blog

### ISSUE THREAD

**Issue by gdukevt** [microsoftgraph/microsoft-graph-docs#14260]
Please consider updating the link under "On-Premises Architectural Requirements for the REST API" (last item on the page) from the decommissioned TechNet blog to the new location under techcommunity. The link currently redirects to the top of the new Exchange Team blog, rather than the specific article. Here's the current direct URL:

https://techcommunity.microsoft.com/t5/exchange-team-blog/on-premises-architectural-requirements-for-the-rest-api/ba-p/605609

Cheers
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a67800f-ff03-8ce1-f196-80f9b35c2684
* Version Independent ID: 76676dba-cdc5-f733-45f9-3fd5512091ad
* Content: [Use REST APIs to access mailboxes in Exchange hybrid deployments (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/hybrid-rest-support)
* Content Source: [concepts/hybrid-rest-support.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/hybrid-rest-support.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@isvargasmsft could you please take a look at this issue and update the link as suggested? Thanks.

**Comment by isvargasmsft** [comment]
Creating PR to fix this issue.

**Comment by isvargasmsft** [comment]
Hello @gdukevt, 

Thank you very much for bringing this into our attention. 

This issue is now fixed. 

Kind regards, 

Isaac Vargas
