### ISSUE TITLE
Japanese notation distortion in tables

### ISSUE THREAD

**Issue by mihohoi0322** [microsoftgraph/microsoft-graph-docs#14341]
[フィードバックをこちらに入力してください]
英語では以下の列の種類が「No / Yes」の二択ですが、日本語だと「いいえ/不要/必要」となっています。
> 通知には、リソース データを含めることができます。

![image](https://user-images.githubusercontent.com/5423565/134324641-6cb4cdcc-1659-458e-829a-b07571791362.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Microsoft Graph API を使用して変更通知を取得する - Microsoft Graph v1.0](https://docs.microsoft.com/ja-jp/graph/api/resources/webhooks?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs.ja-JP/blob/main/api-reference/v1.0/resources/webhooks.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @Jumaodhiss
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @mihohoi0322 for raising this issue. I've logged in internally for the translation team to resolve. Closing the issue here.

**Comment by TinaMcN** [comment]
@mihohoi0322 thank you for reporting the issue.  It has been fixed now, please let us know if you notice any further issues.
