### ISSUE TITLE
How do you query external content with external access control groups?

### ISSUE THREAD

**Issue by wobba** [microsoftgraph/microsoft-graph-docs#14343]
Looking at the documentation I cannot find information how you can query external items and specify which external groups the issuing user is a member of on the request. If the documentation exist adding a cross link would help. If it doesn't exist, then creating it and cross linking would help :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae142515-f6bf-2035-390d-8024f7465f6c
* Version Independent ID: 085867dc-6a0f-1c8b-25d8-67712068afdb
* Content: [Use external groups to manage permissions to Microsoft Graph connector data sources - Microsoft Graph](https://docs.microsoft.com/en-us/graph/connecting-external-content-external-groups)
* Content Source: [concepts/connecting-external-content-external-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-external-groups.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @mecampos
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by wobba** [comment]
@balajipattabhi Right, so the current user's id is picked up from the query context, then expanded to groups he/she is a member of. Makes sense. Maybe mention something around this in the docs to clarify the external group ACL expansion? This issue can be closed.

**Comment by MariaAngela24** [comment]
@wobba I submitted your suggestion to the docs team. Am closing the issue for now.

**Comment by mecampos** [comment]
Thank you for the suggestion, I'm including this feedback in the next set of updates for the documentation.
