### ISSUE TITLE
List joinedTeams API call response is not correct

### ISSUE THREAD

**Issue by ChetanSharma-msft** [microsoftgraph/microsoft-graph-docs#14384]
As per documentation Note, it says that in Response: **"API call returns only the id, displayName, and description properties of a team"**
https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta&tabs=http#response

But it actually returns other properties as well with null values like below:
 {
            "id": "c53f3ea2-xxxx-4341-a217-xxxxxxx",
            "createdDateTime": null,
            "displayName": "xxx test teams",
            "description": "xxx test teams Description",
            "internalId": null,
            "classification": null,
            "specialization": null,
            "visibility": null,
            "webUrl": null,
            "isArchived": false,
            "isMembershipLimitedToOwners": null,
            "memberSettings": null,
            "guestSettings": null,
            "messagingSettings": null,
            "funSettings": null,
            "discoverySettings": null
        }
        
Could you please update it accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4878b58-31d9-f8e1-ed30-2316c5f9ca15
* Version Independent ID: 1dcb5dda-2a45-77e1-bbe1-46ec24b33eec
* Content: [List joinedTeams - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-list-joinedteams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
@AkJo - Could you please share updates on this issue.

**Comment by AkJo** [comment]
The rest of the properties should be ignored. The caller should process only the specific properties that were called out.
