### ISSUE TITLE
Incorrect documentation restId vs ewsId

### ISSUE THREAD

**Issue by bje2eadvising** [microsoftgraph/microsoft-graph-docs#14419]
**Graph ID:** AAMkAGUzMWEzZmRjLTkzY2EtNDMxNS1hOTMzLWRiZjQyNjE2MDc0NgFRAAgI2a_mhiqAAEYAAAAAsWi2nD1JzUqEiTxqPbFNSgcA2iKnZiVk1kCLU_Dw4WArgQAAAAABDQAA2iKnZiVk1kCLU_Dw4WArgQAASTCjRwAAEA==
**EWS ID:** AAMkAGUzMWEzZmRjLTkzY2EtNDMxNS1hOTMzLWRiZjQyNjE2MDc0NgFRAAgI2a+mhiqAAEYAAAAAsWi2nD1JzUqEiTxqPbFNSgcA2iKnZiVk1kCLU+Dw4WArgQAAAAABDQAA2iKnZiVk1kCLU+Dw4WArgQAASTCjRwAAEA==

INCORRECT 
Replace + with -
Replace / with _

WHAT I SEE IS:

Replace + with _
Replace / with -

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f87019e-ef7d-0125-b677-e573ddd93e9e
* Version Independent ID: a62ae14e-7205-c0fb-f742-15643c4ffa9c
* Content: [user: translateExchangeIds - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-translateexchangeids?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-translateexchangeids.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-translateexchangeids.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam
![MSFTPIC](https://user-images.githubusercontent.com/77231311/135313363-a6dadd94-34ec-4879-824e-b11e851b236d.PNG)
**

**Comment by jasonjoh** [comment]
@bje2eadvising I think I see the confusion. The documentation is not describing how to translate between REST and EWS manually. It's telling you how to take a binary format (`entryId` or `immutableEntryId`) and convert it into the format expected by the API.

So if you took an entry ID from MAPI, you would perform the described transforms to generate a string you could use in the `inputIds` array to this API call.

RFC 4648 covers this. In the standard [Base 64 Alphabet](https://datatracker.ietf.org/doc/html/rfc4648#section-4), 62 is `+` and 63 is `/`. In the ["URL and Filename safe" Base 64 Alphabet](https://datatracker.ietf.org/doc/html/rfc4648#section-5), 62 is `-` and 63 is `_`.

**Comment by bje2eadvising** [comment]
Hi Jason,

Thank you for your quick reply.

Thanks,
Boby Joseph
812-606-1920
***@***.******@***.***>
www.e2eadvising.com<http://www.e2eadvising.com/>
Student Success and Retention Platform

**Comment by lramosvea** [comment]
Closing as @jasonjoh has provided and answer already.
