### ISSUE TITLE
Can you please provide C# example?

### ISSUE THREAD

**Issue by alvipeo** [microsoftgraph/microsoft-graph-docs#14431]
I've searched all the docs but I do not understand how to update **the value** of schema extension for a users (more - Azure AD B2C custom attribute value which is a schema extension created on an app but the value set for a particular user).
Can you please add C# examples?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38374504-35a1-d36e-bc8d-a46948f628e2
* Version Independent ID: 1df3c939-3ffd-ca35-7dfa-a20a549c76b3
* Content: [Add custom data to groups using schema extensions  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/extensibility-schema-groups)
* Content Source: [concepts/extensibility-schema-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-schema-groups.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by alvipeo** [comment]
ok, figured it out:

```
                   OpenTypeExtension ext = new()
                    {
                        Id = b2cCustomAttr.Id,
                        AdditionalData = new Dictionary<string, object> {{b2cCustomAttr.Name, value}}
                    };

                    try
                    {
                        //
                        // PATCH request - https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS#updating-an-existing-entity-with-patch
                        //
                        await GraphClient!.Users[userId].Extensions[b2cCustomAttr.Id].Request()
                            .UpdateAsync(ext);
                    }
 ```

but please add it to the docs.

**Comment by FaithOmbongi** [comment]
Thank you @alvipeo for raising this issue. I'll first check-in with the team is we can have code snippets for tutorials too and update the article.

You can also use [Graph Explorer](https://aka.ms/ge) to get the code snippets by clicking the **Code snippets** tab after you run your request.

cc @andrueastman for awareness.
