### ISSUE TITLE
Wrong CSharp code snippets in MS docs for search request scenarios.

### ISSUE THREAD

**Issue by Shweta-1405** [microsoftgraph/microsoft-graph-docs#14450]
I see that all csharp examples in Microsoft Graph REST API v1.0 reference docs that perform a search request are wrong. 
For instance:

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var users = await graphClient.Users
    .Request()
    .Header("ConsistencyLevel","eventual")
    .Search("displayName:wa")
    .OrderBy("displayName")
    .GetAsync();
```
But it should be:

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var options = new Option[]
{
   new QueryOption("$search", "\"displayName:wa\"")
};
var users = await graphClient.Users
    .Request()
    .Header("ConsistencyLevel","eventual")
    .Search("displayName:wa")
    .OrderBy("displayName")
    .GetAsync();
```

Are these samples being autogenerated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Shweta-1405 for raising this issue. Yes, the snippets are autogenerated and I've looped in @andrueastman who knows more about this and will help us resolve this issue on the SDK side.

Closing the issue here and following up via issue [#705](https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/705) in the devx-api channel.
