### ISSUE TITLE
AuthentionMethod: where to find the default method information

### ISSUE THREAD

**Issue by dbollaer** [microsoftgraph/microsoft-graph-docs#14470]
Hello,

When trying to clear the authentication methods, I sometimes get this error:
```json
{
  "error": {
    "code": "badRequest",
    "message": "Cannot delete default method with other methods configured. Please change default method before deletion.",
    "innerError": {
      "message": "Cannot delete default method with other methods configured. Please change default method before deletion.",
      "date": "2021-10-04T09:56:43",
      "request-id": "xxxxxxx",
      "client-request-id": "xxxxxxx"
    }
  }
}

```
While the error is clear, that I can not delete the **default** authenticationmethod, without deleting the other authentication methods first.
It's not clear where I can find the information to know if this authenticationmethod, is the default method.
Or how to change the default method.
I also did not find information about the error in question.

Thank you in advance for having a look.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2131c0c0-b5c1-61fa-98cf-5af744c9f72d
* Version Independent ID: 77be448b-3d8b-9b50-7941-c6218942b6ce
* Content: [Azure AD authentication methods API overview - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/authenticationmethods-overview.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dbollaer for raising this issue and my apologies for the delayed response.

Unfortunately, retrieving the default authentication methods is not yet supported in Microsoft Graph beta. But, it's in the release pipeline. Currently, to manage the default authentication method programmatically, use the [Get-MsolUser](https://docs.microsoft.com/en-us/powershell/module/msonline/get-msoluser?view=azureadps-1.0) and [Set-MsolUser](https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoluser?view=azureadps-1.0) MSOL PowerShell modules.

An example for a user whose default auth method is set to `PhoneAppNotification`

**Step 1: Get the authentication methods configured for the user**
For example: Use Get-MsolUser cmdlet to get authentication methods for a user
```PowerShell
Get-MsolUser -UserPrincipalName BiancaP@Contoso.OnMicrosoft.com | select -ExpandProperty StrongAuthenticationMethods
```
 Sample output
```PowerShell
ExtensionData                                    IsDefault MethodType
-------------                                    --------- ----------
System.Runtime.Serialization.ExtensionDataObject     False OneWaySMS
System.Runtime.Serialization.ExtensionDataObject     False TwoWayVoiceMobile
System.Runtime.Serialization.ExtensionDataObject     False PhoneAppOTP
System.Runtime.Serialization.ExtensionDataObject      True PhoneAppNotification
```

In the above case, `PhoneAppNotification` is the default authentication method for BiancaP.

**Step 2: Use the Set-MsolUser cmdlet to change the (default) auth methods using a PowerShell script** 
The following script:
- Sets `OneWaySMS` as the default method
- Retains `TwoWayVoiceMobile` and `PhoneAppOTP` in the list of configured auth methods for the user
- Removes/deletes `PhoneAppNotification` from the list of configured auth methods for BiancaP. You can choose to retain it in the configured list.

```PowerShell
$UserPrincipalName = "BiancaP@M365x010717.OnMicrosoft.com"
$SMS = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationMethod
$SMS.IsDefault = $true
$SMS.MethodType = "OneWaySMS"
$Phone = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationMethod
$Phone.IsDefault = $false
$Phone.MethodType = "TwoWayVoiceMobile"
$PhoneApp = New-Object -TypeName Microsoft.Online.Administration.StrongAuthenticationMethod
$PhoneApp.IsDefault = $false
$PhoneApp.MethodType = "PhoneAppOTP"
$PrePopulate = @($SMS,$Phone,$PhoneApp)
Set-MsolUser -UserPrincipalName $UserPrincipalName -StrongAuthenticationMethods $PrePopulate
```

Sample response
```PowerShell
ExtensionData                                    IsDefault MethodType
-------------                                    --------- ----------
System.Runtime.Serialization.ExtensionDataObject     False PhoneAppOTP
System.Runtime.Serialization.ExtensionDataObject     False TwoWayVoiceMobile
System.Runtime.Serialization.ExtensionDataObject      True OneWaySMS
````

**Step 3: [Optional] Delete the non-default authentication method**
If in Step 2, you'd retained `PhoneAppNotification` as a configured auth method for BiacaP, you can now call the [Delete microsoftAuthenticatorAuthenticationMethod](https://docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-beta&tabs=http) to delete it using Microsoft Graph API. 

Hope this helps.
