### ISSUE TITLE
roleManagement endpoints vs non-AzureGlobal tenants (e.g. AzureChina)

### ISSUE THREAD

**Issue by purek77** [microsoftgraph/microsoft-graph-docs#14508]
Hello.

Would be nice to provide information about e.g. Azure environments which supports API. 1.0 and BETA as well. 
Right now I have to prepare report about eligible/active assignments in 21V (Azure China) tenants, targeting Azure AD RBACs, and it seems this is not possible, as BETA is not introduced in 21V tenants.

Hover not sure, as I get simple 'The remote server returned an error: (400) Bad Request', hence assumption that BETA calls toward e.g. /beta/roleManagement/directory/roleEligibilitySchedules endpoint doesn't work.

Actually just tested - 1.0 endpoints gives same error, e.g. call against /1.0/roleManagement/directory/roleDefinitions ends with error: (400) Bad Request as well.

Tried to look for information around e.g. https://azure.microsoft.com/en-us/global-infrastructure/services/ - but again nothing.

Regards,
Peter
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfa4ab56-b8e2-cecb-4211-feeaa1173e3a
* Version Independent ID: 0a7f288e-ce9f-513f-35fb-29576c2b2fe7
* Content: [roleManagement resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/rolemanagement.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rolyon** [comment]
Hi @purek77
Thanks for your feedback and patience. We checked with the team and roleManagement should be available in the national clouds.
Let us know if you have any additional feedback.
thanks
