### ISSUE TITLE
Need a url which opens in a browser window instead of downloading it

### ISSUE THREAD

**Issue by ashishmittal-ally** [microsoftgraph/microsoft-graph-docs#14513]
**File search**: 

When I use this url `/me/drive/search` , i get the webUrl like : `https://beta1ally-my.sharepoint.com/personal/swathi_beta1ally_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7BEA4B61FB-1DA6-49E7-959A-0F277FAC9154%7D&file=swathi%20drive%20-%20my%20file.xlsx&action=default&mobileredirect=true&DefaultItemOpen=1`.

This url takes me to a browser window with this excel file opened.

But when i use this url `/search/query` , it get the webUrl like : `https://beta1ally-my.sharepoint.com/personal/swathi_beta1ally_onmicrosoft_com/Documents/swathi drive - my file.xlsx` .  

This url downloads the file instead.

From the `/me/search/query` api , I want the webUrl like the first one which opens in a browser window. 
Or please mention if there is any other way to get it.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files?view=graph-rest-1.0)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ashishmittal-ally** [comment]
Please update on this ticket @nmoreau .

**Comment by nmoreau** [comment]
This is a feature request to the team.
Tagging @yiwenwang-ms

**Comment by yiwenwang-ms** [comment]
Ack

**Comment by yiwenwang-ms** [comment]
@ashishmittal-ally can you try to refer to https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=csharp. It needs time to discuss and onboard this feature due to the multi device dependencies.

Please let me know if any question.

Share a sample I tried:
```
GET /drives/{drive-id}/items/{item-id}/content

Sample:
https://graph.microsoft.com/v1.0/drives/b!b54iWjn6jE-wonbJd0SznCGWZ20pcixHs_cRqoBrC9Hhz7j_gHbxTYdX3psaiKxt/items/01ATL3AYBVOA6MFVTTVVFYSAM6FEYNJPUO/content

```
The DriveItem from Graph Search API.

```           
                            "hitId": "01ATL3AYBVOA6MFVTTVVFYSAM6FEYNJPUO",
                            "rank": 2,
                            "summary": "iOS 14 + Mail/Calendar + Multi Factor <ddd/> Updated Known <c0>Issue</c0> topic with new variant of the <c0>issue</c0> <ddd/> This <c0>issue</c0> is more prevalent with users who have both smart links and the &quot;URL defense <ddd/> ",
                            "resource": {
                                "@odata.type": "#microsoft.graph.driveItem",
                                "size": 4550713,
                                "id": "01ATL3AYBVOA6MFVTTVVFYSAM6FEYNJPUO",
                                "name": "Outlook Top Issues Nov_Dec 2021.pptx",
                                "webUrl": "https://microsoft.sharepoint.com/teams/OutlookClientsCSSTechnicalCommunity/Shared Documents/Emerging issues/Outlook Top Issues Nov_Dec 2021.pptx",
                                "parentReference": {
                                    "driveId": "b!b54iWjn6jE-wonbJd0SznCGWZ20pcixHs_cRqoBrC9Hhz7j_gHbxTYdX3psaiKxt"
                                }
                            }

```
