### ISSUE TITLE
Getting the planner task list does not seem to support filters. It would be really beneficial to allow for filtering on percentComplete

### ISSUE THREAD

**Issue by figgsoftware** [microsoftgraph/microsoft-graph-docs#1454]
To load only the incomplete tasks we could do:

https://graph.microsoft.com/v1.0/planner/plans/oCQ9-mwWLEWX_GuZzqN2mZYACi5U/tasks?$filter=percentComplete+ne+100

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.

This is a feature request. As per the issue template creation process, feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support



The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
