### ISSUE TITLE
Possible contradiction in docs between groups-endpoint's for attachments

### ISSUE THREAD

**Issue by 0xUnicorn** [microsoftgraph/microsoft-graph-docs#14567]
When calling `GET /groups/{id}/threads/{id}/posts/{id}/attachments` using application permissions, this is the response:

> {"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}

My Application has the following permissions added with admin consent

![image](https://user-images.githubusercontent.com/17219001/136805428-d1838423-1ce9-4068-89e1-1eafc3bccec6.png)

If I run the query manually in Graph Explorer using delegated permissions (As the user authenticating) it works fine.

I did notice when looking directly under the /attachments docs for **groups**, `Application` is `Not supported`

So if this is a contradiction in the docs or am I getting it wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7b7da4-9c96-1ab6-3b5d-d554d0485853
* Version Independent ID: 3e362bac-b627-86eb-14d6-e5eaaf1c04d7
* Content: [List attachments - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/post-list-attachments?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/post-list-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/post-list-attachments.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zabeth129** [comment]
I'm in the same situation.
I can call the api at Graph Explorer with delegated permission, but I can't with application permission.

**Comment by henrymbuguakiarie** [comment]
@dkershaw10 Who can take a look at this? It's over 230 days old.
