### ISSUE TITLE
OpenTypeExtension size limitation for Organization resource

### ISSUE THREAD

**Issue by dwanjuhi** [microsoftgraph/microsoft-graph-docs#14605]
Each open extension can have up to 2 KB of data for directory resources, this is not documented for the organization resource type:
![OrgExtensionMaximum](https://user-images.githubusercontent.com/77264508/137324727-d742b4b9-4d0b-4369-86c9-aa5d51dd7b79.PNG)

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9ba2e9-2111-5815-e18b-1158eb9140d2
* Version Independent ID: 22d7b10f-f484-8b91-98da-39aa63478dd6
* Content: [Add custom data to resources using extensions - Microsoft Graph](https://docs.microsoft.com/en-us/graph/extensibility-overview#data-limits)
* Content Source: [concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PooLP** [comment]
I valid this problem, and support a maximum of two openTypeExtension.
The documentation must be modified to warn users.

**Comment by FaithOmbongi** [comment]
Thank you @dwanjuhi for raising this issue. Yes, you're right. The documentation lists only a subset of supported directory objects but, I'll raise a PR to explicitly indicate the **organization** resource to the list.
