### ISSUE TITLE
Endpoint Internal Error for Delete to https://graph.microsoft.com/v1.0/groups/{GroupId}/events/{EventId}

### ISSUE THREAD

**Issue by jchilde** [microsoftgraph/microsoft-graph-docs#1461]
What I am trying to do:  Delete an event in a Unified Group Calendar.

Issue: "Get" to the above address works fine.  "Delete" to the above address fails:
I have tried this using the Rest API, .net client, and the Graph Explorer --same results for each.

The same code worked successfully last week - so this is a recent development.

I also tried https://graph.microsoft.com/v1.0/groups/{GroupId}/calendar/events/{EventId}

Error Received:
{
    "error": {
        "code": "ErrorInternalServerError",
        "message": "[0x30140102] BodyTag",
        "innerError": {
            "request-id": "2ab3ad41-b6e2-47d1-88cc-ef3a3640d153",
            "date": "2017-06-29T04:08:38"
        }
    }
}

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
