### ISSUE TITLE
Replacement for deprecated PIM REST APIs

### ISSUE THREAD

**Issue by JS-Jake** [microsoftgraph/microsoft-graph-docs#14617]
Hello, 
The notice on this page

> This version of the Privileged Identity Management (PIM) API for Azure Resource roles will be deprecated soon. Please use the new Azure REST PIM API for Azure resource roles.

Isn't very clear on the specific APIs that are replacing the current ones - I can't seem to find a replacement for the `governanceResource: register` api specifically - are there any updated pages to show what is being deprecated and what is replacing any deprecated calls?

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabd7961-73aa-5a6c-0935-66038bf6fcfd
* Version Independent ID: 52882de2-8556-9a76-b2fa-0efefe0f0398
* Content: [governanceResource resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/governanceresource?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/governanceresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/governanceresource.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stevenoneill-jmfamily** [comment]
Bump :-)  Any updates on this?  We seem to have run into it as well.

**Comment by amanswaika** [comment]
Hi @JS-Jake 

In the Azure REST PIM API you do not need to manage resources separately so there is no equaivalent of governanceResource out there.

You can pick any resource - management groups, subscriptions, resource groups etc, and use the scope id of that resource to make calls to the Azure REST PIM APIs.

**Comment by JS-Jake** [comment]
Hi @amanswaika, thanks for the reply

I agree that most of the APIs for PIM are now available in the azure resource manager APIs, however unless I am mistaken there is no way to 'onboard' a resource into PIM using the ARM APIs which is the purpose of this ticket

**Comment by FaithOmbongi** [comment]
Hi @JS-Jake, please see [this response](https://github.com/microsoftgraph/microsoft-graph-docs/issues/14739#issuecomment-1016773282) from Aman regarding onboarding. I hope this answers your follow-up question.

> In the Azure REST PIM API you do not need to manage resources individually by Registering or onboarding them.
> 
> You can make a `RoleEligibilityScheduleRequest` or a `RoleAssignmentScheduleRequest` and the onboarding happens automatically.

**Comment by JS-Jake** [comment]
> Hi @JS-Jake, please see [this response](https://github.com/microsoftgraph/microsoft-graph-docs/issues/14739#issuecomment-1016773282) from Aman regarding onboarding. I hope this answers your follow-up question.
> 
> > In the Azure REST PIM API you do not need to manage resources individually by Registering or onboarding them.
> > You can make a `RoleEligibilityScheduleRequest` or a `RoleAssignmentScheduleRequest` and the onboarding happens automatically.

Hi @FaithOmbongi, doing this returns a 'Resource Not Onboarded' error

**Comment by amanswaika** [comment]
Hi @JS-Jake 

If you do a `GET` operation for the very first time you may get a `ResourceNotOnboarded` error. But if you do a `PUT` operation on the resource the resource will be onboarded automatically.

After this the subsequent `GET` calls will also work.
