### ISSUE TITLE
How can I get a values that 'Get access on behalf of a user' No.3 articles required parameters

### ISSUE THREAD

**Issue by yuzuirotori** [microsoftgraph/microsoft-graph-docs#14615]
Hi, I have a few question of this Document.
I`m trying to get bearer token for  this([Databases - List By Elastic Pool](https://docs.microsoft.com/en-us/rest/api/sql/2021-02-01-preview/databases/list-by-elastic-pool#code-try-0)) document.

So, my question below.
In this Document No.3 is Get a token, what I tried. but, I wonder know that find required parameters value in azure portal.
In azure portal, I`m trying to find scope, code, rediret_uri. How can i find this values and example urls

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4323239e-0486-0f8f-6f2b-5e41e6178594
* Version Independent ID: 627883a9-8cd7-93cd-358d-b841d390714b
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-user.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@yuzuirotori Apologies for the delay replying.

First, the doc you shared (Databases...) is for a service accessed that uses the Azure Resource Manager (ARM) API. This documentation is for the Microsoft Graph API. The documentation for ARM can be found here: [https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview)

In general, for an app to receive a token from Azure AD, you will need to provide some values in the token request.

- "scope" means a single scope or list of scopes. Scopes are defined by the resource - in this case, the resource will be ARM, so you will need to check for the scopes that ARM supports.
- "code" is the authorization code that can be passed to receive an access token, as described on this document under [https://docs.microsoft.com/en-us/graph/auth-v2-user#authorization-response](https://docs.microsoft.com/en-us/graph/auth-v2-user#authorization-response)
- "redirect_uri" is described in the table on this document [https://docs.microsoft.com/en-us/graph/auth-v2-user#authorization-request](https://docs.microsoft.com/en-us/graph/auth-v2-user#authorization-request). You can add a new redirect_uri for the app you will use to call ARM (or any other resource) in the Azure portal -> Azure AD -> App registrations -> Authentication UI using the "Add a platform" button, as shown below. Or if you have already added a redirect URI, it will appear there and you can edit it.

![image](https://user-images.githubusercontent.com/34143250/143919248-473d6d01-61e7-4284-b5cc-811bf9ed912e.png)

Hope that help! Closing this issue.
