### ISSUE TITLE
Cannot validate subscription using TLS 1.2 only

### ISSUE THREAD

**Issue by vanta** [microsoftgraph/microsoft-graph-docs#1462]
I have Amazon loadbalancer box with latest policy which allows only for TLS 1.2 connections. When MS Graph is validating subscription (`POST`ing to my `notificationUrl`), connection cannot be established and subscription creation fails with error: 
`The underlying connection was closed: An unexpected error occurred on a send.`

Can you please fix it and till the fix make it clear what are the expectations for `notificationUrl` host to be able to reply on notification validation request?

**Comment by tgrunnagle** [comment]
TLS 1.2 is expected to be compatible with our service. Would you mind sharing an example response from MsGraph for us to further investigate?

**Comment by vanta** [comment]
Sure. To make it clear, this is the response **I receive** when I try to create subscription and MS Graph is trying to validate my `notificationUrl` in between. The response is:
```
{
  "error": {
    "code": "InvalidRequest",
    "message": "The underlying connection was closed: An unexpected error occurred on a send.",
    "innerError": {
      "request-id": "01574510-6416-4425-aa32-17fb26f8c780",
      "date": "2017-06-30T20:36:55"
    }
  }
}
```

**Comment by tgrunnagle** [comment]
We have identified the issue and will be deploying a fix in the coming week. In the mean time, clients will need to continue using TLS 1.0 or SSL 3 to create subscriptions.

**Comment by annapotepa** [comment]
Is there any ETA for this fix? @tgrunnagle

**Comment by tgrunnagle** [comment]
It should be rolled out completely next Tuesday.

**Comment by vanta** [comment]
I can see it working now, against DC in EU and US. Thank you.
