### ISSUE TITLE
The method is not supported for this URL.

### ISSUE THREAD

**Issue by SashaSidorenko** [microsoftgraph/microsoft-graph-docs#14648]
![image](https://user-images.githubusercontent.com/30925159/137881498-93e4f20d-b3d9-43a5-8b1a-3f0a5fe58c64.png) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe81600e-7193-3178-0e9c-44055f5138e4
* Version Independent ID: 19ba9c42-1b6d-5193-3d9e-64bcf668004f
* Content: [passwordAuthenticationMethod: resetPassword - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/passwordauthenticationmethod-resetpassword?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/passwordauthenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/passwordauthenticationmethod-resetpassword.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @SashaSidorenko for raising this issue. I think you might be using an incorrect ID in your query? The second ID should be the ID for passwordMethods which I believe is always `28c10230-6103-485e-b985-444c60001490`. To confirm:

- Run [GET https://graph.microsoft.com/beta/users/userID/authentication/passwordMethods](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2FuserID%2Fauthentication%2FpasswordMethods&method=GET&version=beta&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d) to get the correct passwordMethods ID for the user

- With the ID you retrieve above, please re-run your query
    [POST https://graph.microsoft.com/beta/users/userID/authentication/passwordMethods/passwordMethodsID/resetPassword](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%2FuserId%2Fauthentication%2FpasswordMethods%2FpasswordMethodsID%2FresetPassword&method=POST&version=beta&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

Hope that resolves the problem.
