### ISSUE TITLE
Seeded Capacity Referred to in a model with no seeded capacity.

### ISSUE THREAD

**Issue by thewrabbit** [microsoftgraph/microsoft-graph-docs#14653]
https://docs.microsoft.com/en-us/graph/teams-licenses#modelb-requirements

Within the notes for Model B API calls it states the seeded capacity is shared with other  API calls eg Seeded capacity is shared with conversationMember change notifications.

However this model has no seeded capacity.

In addition
https://docs.microsoft.com/en-us/graph/teams-licenses#seeded-capacity
"The seeded capacity differs by API, see model=A requirements and model=B requirements"

Model B has no seeded capacity.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f880b9-2394-f540-9b06-bcddbe40bfa8
* Version Independent ID: 22de9e03-e917-bcc6-abd7-ebfb3a0cdec8
* Content: [Licensing and payment requirements - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-licenses)
* Content Source: [concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-licenses.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Closing this issue as the document is updated. Please feel free to reopen this issue.
