### ISSUE TITLE
How to differentiate between Custom app and Enterprise app?

### ISSUE THREAD

**Issue by Shweta-1405** [microsoftgraph/microsoft-graph-docs#14655]
I have few custom apps created by a User and the User has also subscribed to few enterprise apps like Skype, Workday, Google cloud.

When I am fetching app roles assigned to user via API : /users/{userId}/appRoleAssignments
I get a list of all apps assigned to him/her, which is correct.

I want to know that is there a way I can get only Enterprise apps assigned to him (and skip getting custom apps created by him in response).

Documentation doesn't specify how to actually differentiate between these two? Is there any property that can be used for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3753b05-1ea1-4351-8081-a34257d7bc97
* Version Independent ID: 997da5ea-2e40-67ad-4b39-f153d3eb107a
* Content: [List appRoleAssignments granted to a service principal - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignments?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-list-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-list-approleassignments.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
@Shweta-1405 

The `resourceId` property of the app role assignment corresponds to the ID of the `servicePrincipal` object for the app/service which has been assigned to the user.

To retrieve additional details about those service principals, you can query them one by one:

```none
GET https://graph.microsoft.com/v1.0/servicePrincipals/{id}
```

Several at a time using [JSON batching](https://docs.microsoft.com/graph/json-batching):

```none
POST https://graph.microsoft.com/v1.0/$batch
Content-type: application/json

{
  "requests": [
    {
      "id": "1",
      "method": "GET",
      "url": "/servicePrincipals/{id-1}"
    },
    {
      "id": "2",
      "method": "GET",
      "url": "/servicePrincipals/{id-2}"
    }
}
```

Or many at a time using [getByIds](https://docs.microsoft.com/graph/api/directoryobject-getbyids?view=graph-rest-1.0&tabs=http):

```none
POST https://graph.microsoft.com/v1.0/directoryObjects/getByIds
Content-type: application/json

{
    "ids": ["{id-1}","{id-2}"],
    "types":["servicePrincipal"]
}

(Or, in extreme cases, even more at a time with a JSON batch of getByIds.)

Once you have the service principals, you can decide which app role assignments you're interested in keeping, based on the various properties of the [service principal](https://docs.microsoft.com/graph/api/resources/serviceprincipal?view=graph-rest-1.0).  Which properties you'd look for depend on what exactly you mean by "custom app" vs. an "enterprise app", but likely candidates are **appOwnerOrganizationId** and **tags**. My recommendation is to look at example service principals to determine which properties identify the service principals you're interesting.
