### ISSUE TITLE
Api PhoneAuthentication List is not available

### ISSUE THREAD

**Issue by KSchlobohm** [microsoftgraph/microsoft-graph-docs#14662]
I believe List and Get operations have the same limitations. The following comment from Get should be available on the List doc.

> This method is available only for standard Azure AD and B2B users, but not B2C users.
'/api-reference/beta/api/phoneauthenticationmethod-get.md'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df4ede94-a1b0-cdce-59c4-f3fde441f74f
* Version Independent ID: 4138842a-de3b-113e-868e-96cc990d32f5
* Content: [List phoneMethods - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authentication-list-phonemethods.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @KSchlobohm for raising this issue. Yes, you're right. The LIST method is also unavailable for B2C users. I've raised a PR to resolve this.
