### ISSUE TITLE
user->mailboxSettings is a plain property, not a navigation property in the metadata

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/microsoft-graph-docs#14703]
`mailboxSettings` property is not defined as navigation property in the metadata, that's why SDKs can't generate the corresponding request builders correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e6b8492-815a-5809-acef-a7551489dbea
* Version Independent ID: f80ffa1b-6461-cfbf-d909-a0d5bff3159f
* Content: [Get user mailbox settings - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get-mailboxsettings?view=graph-rest-1.0&amp%3Btabs=csharp&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-get-mailboxsettings.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
This isn't a doc issue. This is an SDK issue.  In OData, structural properties can also be addressed using a path segment.  They do not need to be a navigation property.  Our challenge with the SDKs is how do we know which structural properties are actually exposed explicitly by the API.  We need additional metadata to know when to generate the request builder.

**Comment by zengin** [comment]
Thanks for the additional context @darrelmiller. I will create an SDK issue if it doesn't exist and close this one afterwards.

**Comment by zengin** [comment]
turns out we already have an issue.

closing this as duplicate of https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/258
