### ISSUE TITLE
Remove mention of uniqueness of "mailNickname" from the doc page or enforce uniqueness in the API call

### ISSUE THREAD

**Issue by eprigorodov** [microsoftgraph/microsoft-graph-docs#14716]
Group property `mailNickname` is described as "The mail alias for the group, unique in the organization."

That can be read as if property is required and must also be unique, as if MS Graph will return an error if the group with the same `mailNickname` already exists. It could have been a natural protection against duplicates.

At present moment that is not the case. MS Graph allows creating two groups with identical `mailNicknames`. You can find an  example in our dev tenant `61052ab8-5da9-4f0f-b3ee-6ba96e47ecb6`: object IDs are `d6fab68c-e0ec-4cf1-af3a-f24821222ff9` and `65853ed1-773b-4708-97b4-a9abd2547058`, the second created month later than first.

If nothing enforces uniqueness of `mailNickname` then the doc page would be less confusing without the phrase "unique in the organization".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @eprigorodov , I've tested this and I see this behavior affects security groups, not Microsoft 365 groups? Could you confirm that your groups that have similar mailNickname are also security groups? I'll escalate this to the product team to provide more clarity.

**Comment by eprigorodov** [comment]
Hi @FaithOmbongi, thank you for testing and I confirm that the observed behavior was with security groups having similar `mailNickname`. Just tested again and the bug still reproduces, the new group ID is `db7173f2-c32d-442b-b4ee-ea28c82aad54`.

**Comment by FaithOmbongi** [comment]
Hi @eprigorodov, engineering has confirmed that the uniqueness of **mailNickname** is only enforced for Microsoft 365 groups, not security groups. Though security groups receive the **mailNickname** property, the property really has no meaning there (unlike in mail-enabled security groups which aren't managed via Microsoft Graph anyway).

I've raised a PR to correct the docs.

**Comment by eprigorodov** [comment]
Hi @FaithOmbongi, thank you for this research and the fix.

If **mailNickname** has no meaning for the security groups, would it maybe have a sense to make it also non-mandatory for them?

**Comment by FaithOmbongi** [comment]
Hi @eprigorodov—unfortunately, it may not be that straightforward. In Microsoft Graph, "security groups" is assumed to refer to Azure AD-managed security groups. We also have [mail-enabled security groups](https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0) which can only be managed via Exchange. These require the **mailNickname** property because **mailEnabled** is `true` for them.

For the sake of future-proofing for when mail-enabled security groups might be managed via Microsoft Graph, **mailNickname** has to be required (though maybe the fact that uniqueness isn't enforced for security groups might be addressed before the feature is supported).
