### ISSUE TITLE
accountEnabled permissions (reopen #7104)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoftgraph/microsoft-graph-docs#14731]
Issue #7104 was closed prematurely if you ask me.

@FaithOmbongi stated:

> Updating accountEnabled status of an Admin user is allowed by another Admin user with User.ReadWrite.All permission.
> 
> No updates identified for the page. Closing the issue.

I **think** the key point there is "another _Admin_ user", meaning (again I **think**), for confidential client apps, we need the corresponding Service Principal (i.e., Enterprise Application) to be assigned an Azure AD admin role, in addition to the registered app being granted/consented the necessary API application permission.

But none of this is on the page whatsoever.  So please @FaithOmbongi , can you confirm if what I'm saying is true?  I will submit a PR to add this into into the purple note box.  It's a perfectly fine issue to be opening and needs resolution.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#permissions)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jpettere** [comment]
Hi @JeremyTBradshaw. Your description is accurate. accountEnabled can only be updated via delegated permissions and only Global Admins have the ability to edit the property for all users (including all admin roles). I've raised the following PR to add the info to the doc. https://github.com/microsoftgraph/microsoft-graph-docs/pull/14803

Let me know if you have any other questions, otherwise I'll close the issue.

**Comment by JeremyTBradshaw** [comment]
@jpettere thanks for the confirmation, and just to confirm, is it definite that Application Permissions / confidential client, if the associated service principal is assigned an AAD admin role?  Or in other words is it definite that it must be via delegated permissions?

**Comment by jpettere** [comment]
@JeremyTBradshaw correct, there needs to be an actual signed in user.
