### ISSUE TITLE
Where is the replacement functionality of this ?

### ISSUE THREAD

**Issue by mnj** [microsoftgraph/microsoft-graph-docs#14739]
You mention we should use the new "Azure REST PIM API for Azure resource roles.", but where is the functionality to enable/register a subscription for use in PIM like this provides?

All the deprecation warnings link to the same "Role Eligibility Schedule Requests" stuff, that seems unrelated to this?

What I'm mostly looking for, is how we can automate the configuration of PIM, seems a step backwards, having to manually click around in the portal, that does not scale to hundreds of subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabd7961-73aa-5a6c-0935-66038bf6fcfd
* Version Independent ID: 52882de2-8556-9a76-b2fa-0efefe0f0398
* Content: [governanceResource resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/governanceresource?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/governanceresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/governanceresource.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by amanswaika** [comment]
Hi @mnj 

In the Azure REST PIM API you do not need to manage resources individually by Registering or onboarding them.

You can make a `RoleEligibilityScheduleRequest` or a `RoleAssignmentScheduleRequest` and the onboarding happens automatically.
