### ISSUE TITLE
Insufficient rights

### ISSUE THREAD

**Issue by BakkerJan** [microsoftgraph/microsoft-graph-docs#14730]
Despite having RoleManagement.ReadWrite.Directory permissions (application), I cannot add members to the Role Assignable Group. I can create the group, but cannot add members to it. 

What permission is required to do so? 

{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "date": "2021-10-25T15:30:49",
      "request-id": "020d2e6d-66ef-4641-b870-0d9236e05f64",
      "client-request-id": "020d2e6d-66ef-4641-b870-0d9236e05f64"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79f1188-8828-5eaa-386a-f18507561ba0
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abhijeetsinha** [comment]
@BakkerJan - The request is failing on GetUser task. To be able to add members, the app will also need permissions to read the user. Please grant the app this permission.
cc: @rolyon
