### ISSUE TITLE
Add clarification where query parameter should be added for list and change subscriptions

### ISSUE THREAD

**Issue by TheBluLion** [microsoftgraph/microsoft-graph-docs#14775]
Examples for where the query parameter for mode=a should be included. 

For change subscriptions this should be on the resources node in the body of the request, but for list operations this would be added to the request URL directly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f880b9-2394-f540-9b06-bcddbe40bfa8
* Version Independent ID: 22de9e03-e917-bcc6-abd7-ebfb3a0cdec8
* Content: [Licensing and payment requirements - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-licenses)
* Content Source: [concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-licenses.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@TheBluLion - Could you please elaborate the issue in little detail?

**Comment by TheBluLion** [comment]
Clarification should be provided as to where the query parameter should be included on a graph request. (example below)

![image](https://user-images.githubusercontent.com/41968802/139860987-a37590bf-c251-4bf7-ac2f-da0a6eefac59.png)

Correct format for a change subscription should be 

`POST https://graph.microsoft.com/v1.0/subscriptions
Content-type: application/json

{
   "changeType": "created",
   "notificationUrl": "https://webhook.azurewebsites.net/api/send/myNotifyClient",
   "resource": "/chats/getAllMessages?mode=A",
   "expirationDateTime":"2016-11-20T18:23:45.9356913Z",
   "clientState": "secretClientValue",
   "latestSupportedTlsVersion": "v1_2"
}`

Correct format for get messages across all chats for user should be 
`GET /users/{id | user-principal-name}/chats/getAllMessages?mode=A`

**Comment by Meghana-MSFT** [comment]
Thanks for giving detailed explanation about the issue. I will update you soon.

**Comment by Meghana-MSFT** [comment]
We have raised this issue with the internal team. They are working on it.

**Comment by v-chetsh** [comment]
@TheBluLion - The documentation is updated.
We are closing this issue for now, Please feel free to reopen it, if required.
