### ISSUE TITLE
remove user from group,Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by siyangzzz** [microsoftgraph/microsoft-graph-docs#14806]
Hello,I have added all the permissions that this page mentioned,and call this url:https://graph.microsoft.com/v1.0/groups/{group-id}/members/{directory-object-id}/$ref,then i got a wrong:"Insufficient privileges to complete the operation",so is there any another permissions that i need to add,i have added these permissions
![image](https://user-images.githubusercontent.com/16680825/139797758-f5517b3a-d5d3-4aff-8d4a-196bf5248372.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by siyangzzz** [comment]
> Hello,I have added all the permissions that this page mentioned,and call this url:[https://graph.microsoft.com/v1.0/groups/{group-id}/members/{directory-object-id}/$ref,then](https://graph.microsoft.com/v1.0/groups/%7Bgroup-id%7D/members/%7Bdirectory-object-id%7D/$ref,then) i got a wrong:"Insufficient privileges to complete the operation",so is there any another permissions that i need to add,i have added these permissions ![image](https://user-images.githubusercontent.com/16680825/139797758-f5517b3a-d5d3-4aff-8d4a-196bf5248372.png)
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
> * Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
> * Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http#feedback)
> * Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-delete-members.md)
> * Product: **groups**
> * Technology: **microsoft-graph**
> * GitHub Login: @Jordanndahl
> * Microsoft Alias: **MSGraphDocsVteam**

The issue has been resolved,because the group is dynamic group with Dynamic membership rules, so that i can not remove user from group.To solve it,you should update user's info that can pass the Dynamic membership rules.

**Comment by FaithOmbongi** [comment]
Thank you @siyangzzz for raising this issue and helping to resolve it. I've added a note to address this gap.
