### ISSUE TITLE
Group Resource - Add member does not support mail-enabled security groups

### ISSUE THREAD

**Issue by colinhqgit** [microsoftgraph/microsoft-graph-docs#14827]
The description for "Add member" is as follows:
Add a user or group to this group by posting to the members navigation property (supported for security groups **and mail-enabled security groups only**).

However, when I attempt to add a member (or guest) account to a mail-enabled security group, I receive the following error:
```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Cannot Update a mail-enabled security groups and or distribution list.",
        "innerError": {
            "date": "2021-11-03T19:19:39",
            "request-id": "1fbfac21-16ac-43b1-ac8d-f816a62159be",
            "client-request-id": "1fbfac21-16ac-43b1-ac8d-f816a62159be"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
[Marking as a duplicate of #14899.]
Thank you @colinhqgit for raising this issue. Add members method works only for security and Microsoft 365 groups. This has since been corrected in the docs.
