### ISSUE TITLE
incorrect name displayed for employee hire date attribute

### ISSUE THREAD

**Issue by krbain** [microsoftgraph/microsoft-graph-docs#14826]
The naming of the hire date on the update user page is incorrect. The "hireDate" attribute should be "employeeHireDate" for both beta and v1.0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @krbain for raising this issue and yes, you're right; **employeeHireDate** is the updatable property, not **hireDate**. I've raised a PR to fix the reference. Closing this issue.
