### ISSUE TITLE
Create a new list API calls is never success (beta API)

### ISSUE THREAD

**Issue by Gelembjuk** [microsoftgraph/microsoft-graph-docs#1484]
Issue: 
I try to execute the MS Graph API call described there
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/list_create
It is a creation of a list for a sharepoint site.

I need to create it to be able to make folders in root of my sharepoint sites using the MS graph API . 
My initial request and problem was described there https://stackoverflow.com/questions/44900200/ms-graph-api-sharepoint-site-create-a-folder-in-root 

Noone offered a solution. It looks like the only way to create folders in root of sites is to use this BETA API to create lists.
However, the API doesn't work as described in docs. 

When i try to do

    POST https://graph.microsoft.com/beta/sites/{site-id}/lists
    Content-Type: application/json
    
    {
      "name": "Books",
      "columns": [
        {
          "name": "Author",
          "text": { }
        },
        {
          "name": "PageCount",
          "number": { }
        }
      ],
      "list": {
        "template": "generic"
      }
    }

I have an error response with the message

    Cannot define a 'name' for a list as it is assigned by the server. Instead, provide 'displayName'

If i change 'nme' to 'displayName' in the JSON document then error is "One of the provided arguments is not acceptable."

Also i tried to set

    ,"list":{"template":"documentLibrary"}

and still same errors

What do i do wrong? Or that BETA API just doesn't work ?

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/list_create

**Comment by pchc2005** [comment]
@rgregg hi ryan, any updates on this problem?

**Comment by ksheode** [comment]
Hi there! I am also a PM on Ryan's team. Sorry that you ran into this issue! We are fixing it now and we expect create lists to start working on the beta endpoint by mid-August.

**Comment by Gelembjuk** [comment]
Any update on this?

**Comment by DDAndyChen** [comment]
Any update on the plan to fix this?

**Comment by JANorman** [comment]
Is there any plan to fix this?

**Comment by darthelch** [comment]
I am also interested in a solution for this.

**Comment by DDAndyChen** [comment]
This API is in v1.0 now: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/list_create
Has anyone made a successful call with it?

**Comment by Gelembjuk** [comment]
@DDAndyChen , i tried and i got same wrong results with v1.0 as with beta.
it doesn't work :(

**Comment by DDAndyChen** [comment]
@Gelembjuk 

Today I added these permissions then the create list worked for me.

> Sites.Manage.All
> Sites.FullControl.All

**Comment by Gelembjuk** [comment]
I am still getting the error "The caller is not authenticated."
I also added Sites.Manage.All and  Sites.FullControl.All . Saved the app settings.
Received new refresh token .
But still can not create a list

**Comment by DDAndyChen** [comment]
@Gelembjuk 
I use oauth2 v2.0 version, Ican make sure the the access token has some thing like this (notice the *Sites.Manage.All*)
> "scp": "Mail.Read Sites.Manage.All User.Read",

use the https://jwt.io/

Otherwise, you access token does not have enough permission.

**Comment by Gelembjuk** [comment]
It works now! 
Thanks, guys

**Comment by healthycola** [comment]
I can't add Sites.Manage.All from Azure V2. Any one have ideas on how to fix this?

**Comment by dmitrybg** [comment]
Seems it still doesn't work. Still reports "Can't define name ... " error with v1.0 API. Any ideas? I have all rights listed above.

**Comment by dzardoya** [comment]
dmitrybg: change "name" to "displayName", it works for me
