### ISSUE TITLE
GET /informationProtection/policy/labels always returns 403 with documented permissions granted

### ISSUE THREAD

**Issue by jlehmanndg** [microsoftgraph/microsoft-graph-docs#14888]
I have verified I have the following permissions fully granted in my Azure enterprise application, which is all that is mentioned as required in the online documentation:

InformationProtectionPolicy.Read Delegated
InformationProtectionPolicy.Read Application
InformationProtectionPolicy.Read.All Application

I then retrieve an authentication token successfully and use it as my bearer token to make API calls.

When I make the call to get all labels in an organization restfully, I get a 403 with an "internalError" response, like the following:

```
< HTTP/1.1 403 Forbidden
< Date: Tue, 09 Nov 2021 14:13:24 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Strict-Transport-Security: max-age=31536000
< request-id: 81b7a7eb-f0c9-41e3-9aec-92bc7db0d943
< client-request-id: 81b7a7eb-f0c9-41e3-9aec-92bc7db0d943
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"CH01EPF00004E9D"}}
< 
* Connection #0 to host graph.microsoft.com left intact
{"error":{"code":"UnknownError","message":"","innerError":{"date":"2021-11-09T14:13:25","request-id":"81b7a7eb-f0c9-41e3-9aec-92bc7db0d943","client-request-id":"81b7a7eb-f0c9-41e3-9aec-92bc7db0d943"}}}
```

Again the online documentation states the previously mentioned permission is the only one required to make this call, and again I have a valid bearer token at the time. Any insight into how to make this call successfully?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da17f77-de16-97ad-22d3-9fe3ea30fd3e
* Version Independent ID: 0fbb3be6-d763-7418-bcad-e78838e113b8
* Content: [informationProtectionLabel: listLabels - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/informationprotectionpolicy-list-labels?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/informationprotectionpolicy-list-labels.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/informationprotectionpolicy-list-labels.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @tommoser
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tommoser** [comment]
@jlehmanndg Are you making the call with a user or an app secret?
