### ISSUE TITLE
AAD User documentation is incomplete or not correct

### ISSUE THREAD

**Issue by ivi-hamiti** [microsoftgraph/microsoft-graph-docs#14898]
While working with the graph api for actions towards users i noticed the following issues

- it is not stated that the endpoint does not support **$skip** for user listing
- **externalUserState** support **$filter** and **eq** operator, but this does not work for null check, for filtering out external users. i tried for the same purpose to do an inverse, so excluding the known values but does not work either, which would be useful to be listed in the documation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ivi-hamiti for raising this issue.

- **externalUserState** does not support filtering on `null `values. This additional info is currently available on the [advanced query parameters page](https://docs.microsoft.com/en-us/graph/aad-advanced-queries#user-properties). I'll see how best to add this info into the table cells.

My tests also show that `$skip` is not supported by the user API. But, I'll check in with engineering just to be sure and get back to you.

**Comment by ivi-hamiti** [comment]
From my experience till now with the graph API, i noticed that it is hard to keep on track with all the information, as they are spread on multiple places. It would be more obvious if this information is documented in is single place. For **exteralUserState** you have all the descriptions that it supports the filtering etc. but to see all filtering detail you still must navigate away.

**Comment by FaithOmbongi** [comment]
Hi @ivi-hamiti, I've confirmed that `$skip` isn't supported on the user API. I'll raise a PR to explicitly document this info.

Thanks for your feedback on discoverability. For query parameters, we currently have a "disclaimer" note before the Properties tables & in the Optional query parameters section of List operations, for example, List users. This was to avoid cluttering the property descriptions with the info on [advanced querying functionality](https://docs.microsoft.com/en-us/graph/aad-advanced-queries#user-properties). But, we haven't stopped looking for better ways to document such information.

Is there another specific instance where you feel that the info is split up unnecessarily? We can always look into such and work at improving your experience of our docs.
