### ISSUE TITLE
Unable to add members to mail enabled security groups

### ISSUE THREAD

**Issue by rakheshster** [microsoftgraph/microsoft-graph-docs#14899]
According to [this page](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0) one should be able to use Graph API to add members to mail enabled Security groups:

> Add a user or group to this group by posting to the members navigation property (supported for security groups and mail-enabled security groups only).

And this worked fine for me until last week or so. But it has stopped working since then and now I get the following error:

```powershell
New-MgGroupMember -GroupId 4938ba57-5e96-4a3e-b069-a066dd194a55 -DirectoryObjectId b269b48d-afa4-49ed-a26e-d684531b62c7
New-MgGroupMember_CreateExpanded1: Cannot Update a mail-enabled security groups and or distribution list.
```

I see that someone else has encountered a similar problem and raised the question in [this post](https://docs.microsoft.com/en-us/answers/questions/608720/i-am-trying-to-add-member-in-mail-enabled-security.html). Has something changed recently? 

I have many scripts that use Graph API to add members to groups and while I could rewrite them to use the ExO cmdlets I'd rather not if this is a temporary bug. 

Thanks,
Rakhesh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rakheshster** [comment]
Just to add, I went through the run history of my job and see that these errors started on the 20th of Oct. Until then `New-MgGroupMember` was able to add users to mail enabled security groups.

**Comment by FaithOmbongi** [comment]
Thank you @rakheshster for raising this issue. The API should work as documented. I've escalated the issue to engineering for investigation and will get back to you.

**Comment by FaithOmbongi** [comment]
My apologies @rakheshster for the delayed response. I've confirmed that we recently fixed a bug that previously allowed you to use the Add members method to add members to a mail-enabled security group. Managing mail-enabled security groups through Microsoft Graph is currently possible [as per this article](https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0). I'll also raise a PR to fix the docs.

To request that the Microsoft Graph groups API support creation and managing of mail-enabled security groups, you may [open a feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) and other customers may amplify your voice.

**Comment by FaithOmbongi** [comment]
Yes, that's right @rakheshster.

**Comment by loryanstrant** [comment]
This disappointing, as it would've been a good feature to retain as opposed to it being a bug.
I don't like that the only way to add users to a mail-enabled security group programmatically requires a PowerShell script.
