### ISSUE TITLE
Connect-MgGraph

### ISSUE THREAD

**Issue by Mike-Crowley** [microsoftgraph/microsoft-graph-docs#14931]
It seems CertificateThumbprint only is able to enumerate the user's local certificate store.  If this is by design, i suggest this code sample for people trying to connect with a certificate stored in the machine's certificate store or other location. Admin rights are also required to view the keys of the machine store.
```

$MgConnectParams = @{
  ClientId = '459a03cf-9447-4d55-8ede-be4f98b65783'
  TenantId = '2100b519-cdac-491d-b6fd-251416b8c1d2'
  Certificate = (Get-ChildItem Cert:\LocalMachine\my\1234567890637B11419A4725D708BCE7C8139507)
}
Connect-MgGraph @MgConnectParams
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d211b6ad-20d1-8683-3562-04e35d8de652
* Version Independent ID: 926e81ea-63c6-ab12-3fa6-ef85070b106f
* Content: [Use app-only authentication with the Microsoft Graph PowerShell SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal)
* Content Source: [concepts/powershell/app-only.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/powershell/app-only.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@maisarissi FYI

**Comment by jasonjoh** [comment]
This particular document walks you through a specific scenario, where the cert is stored in the user's store. This should probably go in the PowerShell reference, and we can add a link to this doc for ("if you want to store the cert somewhere else, go here").

**Comment by msewaweru** [comment]
> We do provide 3 different samples on how to use certificate when connecting to Graph in our [GitHub repo README.md file](https://github.com/microsoftgraph/msgraph-sdk-powershell#usage), using -CertificateThumbprint, -CertificateName or -Certificate (the one used by @Mike-Crowley ).
> 
> @lramosvea @jasonjoh maybe we should move that content to the Graph docs? @msewaweru same applies to PowerShell reference docs.

Agreed @maisarissi. I think that we can apply it to the reference content that we will be handwriting i.e. for the authentication cmdlets. Thanks.

**Comment by jasonjoh** [comment]
Hi @msewaweru has this been added in the reference?

**Comment by msewaweru** [comment]
> Hi @msewaweru has this been added in the reference?

Hi @jasonjoh, not yet. We took the route to create [a conceptual article](https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/70) that introduces the authentication cmdlets in the interim as @maisarissi and team, work of creating reference content for the same.

**Comment by maisarissi** [comment]
@msewaweru we are actually adding this to the conceptual documentation here: https://github.com/MicrosoftDocs/microsoftgraph-docs-powershell/pull/70/files#diff-e1c3bd1d859a5548271980c4884b039058426b76610478274867a9c3682ef211R61-R62

We might want to add a short sentence making it clear that the -Certificate example can be used for people trying to connect with a certificate stored in the machine's certificate store or other location.

**Comment by msewaweru** [comment]
We finally published this article [here]( https://docs.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0).
