### ISSUE TITLE
Would like example of how to replace search for 'items shared by me'

### ISSUE THREAD

**Issue by ctboeheim** [microsoftgraph/microsoft-graph-docs#14945]
We have been trying to duplicate the 'items shared by me' search in OneDrive, so we can notify collaborators of shared items before a user is deleted. It would be very useful to have the example here, or a pointer to the query terms that can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files#next-steps)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yiwenwang-ms** [comment]
Ack

**Comment by yiwenwang-ms** [comment]
@ctboeheim Thanks for your feedback.
Briefly summarize it, seems you want to get a user list that a document been shared to.
If any misunderstanding, please feel free to correct me. We will discuss it internally first.

**Comment by yiwenwang-ms** [comment]
@ctboeheim Could you please share a sample for  'items shared by me'  scenario, a screenshot or which service you duplicated from.

**Comment by ctboeheim** [comment]
Thank you @yiwenwang-ms .  We are trying to delete the OneDrives of people who have left. Before we do that, we would like to know if the drive contains items shared with other people, so we can notify them to make a copy if they still want it.  The desired result set is what is displayed by OneDrive online on the Shared By Me tab, but in a list that can be consumed by a program.

![Screen Shot 2021-12-07 at 10 13 38 AM](https://user-images.githubusercontent.com/5943572/145055329-17280abf-79fa-4672-a33a-a3faf1ae0802.png)

**Comment by yiwenwang-ms** [comment]
@ctboeheim Thank you!
Do you mean you want to get an user list like below:
![image](https://user-images.githubusercontent.com/78404769/145062038-dfeeac00-c798-4bff-a233-8c574721e2bc.png)

I'd like to check if any other existed API supports it or if Graph Search API can support it.

**Comment by ctboeheim** [comment]
@yiwenwang-ms I would like to this in three passes:
1. From the list of OneDrives to deprovision, find the list of drives that share anything with anyone 
2. From the list of drives from 1, find the list of files that are shared with anyone
3. For each file from 2, find who it is shared with.

This is easy to do in other online services that we use, and this is a well-developed model for us, but it's hard to get that info out of OneDrive.

**Comment by yiwenwang-ms** [comment]
Hi @ctboeheim Could you please open an issue here, https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/drive-sharedwithme.md

I didn't find a search term or existed functionalities to meet your requirements in search API current now. Need more time to do more investigation.

**Comment by ctboeheim** [comment]
Hi @yiwenwang-ms, I'd be happy to open the issue; is that the right place to open it? What I'm looking for is the converse of the intent of that API. Just don't want to muddy the waters by putting it in the wrong place.

**Comment by yiwenwang-ms** [comment]
Hi @ctboeheim, I got the link from https://docs.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-beta&tabs=http, seems these documents maintained by the OneDrive service developers. I think they should have more ideas here.

For Search API current now, I need more time to investigate and confirm with other teams.
And also curiously which online service provide this scenario, could you please share me a link? It will be a good reference to us.

**Comment by ctboeheim** [comment]
Actually, this issue is already in category you pointed me to. When I followed the link it took me in a circle right back here.

Box provides a report that lists all the files shared by a user and the users they are shared with. Processing this CSV gives me exactly what we need.

Google provides a search for files with permissions granted to others. This is more laborious to process than Box's report, but we can derive what we need.

I'm not finding anything in Graph that will get that information for me.  Since the OneDrive Web UI can produce that list instantly, it must exist somewhere.

**Comment by yiwenwang-ms** [comment]
Hi @ctboeheim ,

As I investigate, Graph Search API doesn't support that current now.

Though there are some internal API to get the shared file list and corresponding shared user list,  but both of them are internal APIs and not exposed to customers. 

Such like  

-Get shared documents
https://microsoft-my.sharepoint.com/personal/yiwenwang_microsoft_com/_api/web/Lists(@a1)/GetItemById(@a2)/GetSharingInformation?@a1=%27%7B971A2ACC%2D7FA9%2D457D%2DB477%2DE49BE09D72E9%7D%27&@a2=%273706%27&$Expand=permissionsInformation,pickerSettings


- Get shared user list for specific document. 
https://microsoft-my.sharepoint.com/personal/yiwenwang_microsoft_com/_api/web/Lists(@a1)/GetItemById(@a2)/GetSharingInformation?@a1=%27%7B971A2ACC%2D7FA9%2D457D%2DB477%2DE49BE09D72E9%7D%27&@a2=%273706%27&$Expand=permissionsInformation,pickerSettings

I am asking OneDrive Service for help, still in internal discussion.

**Comment by yiwenwang-ms** [comment]
Hi @ctboeheim ,

I got the reply from ODSP side, they don't have a public API to support 'Shared By Me' scenario, and also don't have plan to support it in recent future.

 GetSharingInformation is not intended nor supported for customer consumption as an API, so don’t advise them to use that at all. It’s marked internal and the intent is it never will get marked as public supported, as I will be getting rid of it as soon as I can. We don’t have a full equivalent of the data in GetSharingInformation in graph today, and likely never will (as it’s very expensive especially if used like your customer likely wants)

Sorry for that, I'd like close it with this comment.
