### ISSUE TITLE
Can we have link to or exhaustive list of fields available to send in request?

### ISSUE THREAD

**Issue by pallavrustogi** [microsoftgraph/microsoft-graph-docs#14987]
[Enter feedback here]
Can we have link to or exhaustive list of fields available to send in request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ff7ff9f-c955-c32f-756c-59e9165f3fa3
* Version Independent ID: c181ecf0-6586-9b36-20a8-f2f1e1381397
* Content: [Create event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/calendar-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
The exhaustive list of properties on event resource type is available:
https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0
