### ISSUE TITLE
Additional response property now included creationOptions

### ISSUE THREAD

**Issue by nikki-c** [microsoftgraph/microsoft-graph-docs#15009]
GET groups is now returning creationOptions  array which is not described on the page.

See examples
{
            "id": "014974f4-66d0-47ec-9951-135a3b5d470e",
            "deletedDateTime": null,
            "classification": null,
            "createdDateTime": "2020-06-11T17:04:09Z",
            "creationOptions": [],

The options I see on my test tenant are:
    "creationOptions": [],

            "creationOptions": [
                "ExchangeProvisioningFlags:2020"
            ],

            "creationOptions": [
                "Team",
                "ExchangeProvisioningFlags:3552"
            ],

            "creationOptions": [
                "ProvisionGroupHomepage",
                "SensitivityLabel:c9c61b1e-f782-4589-afe3-ba638c508fc9",
                "HubSiteId:00000000-0000-0000-0000-000000000000",
                "SPSiteLanguage:1033"
            ],

            "creationOptions": [
                "YammerProvisioning"
            ],
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c5cd62a-5325-aeda-c1ae-33b6157eb04c
* Version Independent ID: c9b14f46-af37-3520-450c-3ed4d5f54f46
* Content: [List groups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @nikki-c for raising this issue and my apologies for the delayed response. On a general note, the group resource is an open type that may include some dynamic properties, in addition to those defined in the schema. However, in the case of **creationOptions**, I'm following up with the team to get clarity on this property especially because it's returned only through the v1.0 endpoint, not the beta endpoint. I'll get back to you once I have more information.

**Comment by FaithOmbongi** [comment]
Hi @nikki-c, my apologies for dropping the ball on this. Adding @crewpay to the response.

**creationOptions** is a property currently still used by a few services and will be replaced in the future by either **resourceBehaviorOptions** or **resourceProvisioningOptions**. When your **resourceProvisioningOptions** includes `Teams`, you'll see the same value in **creationOptions**. The `ExchangeProvisioningFlags:[intvalue] `values are calculated based on the Exchange-related settings in **resourceBehaviorOptions**. I've opened an internal work item to request conclusive documentation about the property.

The `ProvisionGroupHomepage` option provisions a SharePoint site for the Microsoft 365 group.
