### ISSUE TITLE
Wrong 'least privilege' for List user transitive memberOf

### ISSUE THREAD

**Issue by ntrpnr** [microsoftgraph/microsoft-graph-docs#15015]
In the search for a lower privilege which works for 'List user transitive memberOf' I have discovered that **a combination of User.Read.All and Group.Read.All** works. This combination is a lower privilege than **Directory.Read.All** which is currently listed as 'least privilege'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e41493-05ab-9f85-ccd8-7244303ae4ff
* Version Independent ID: 30167152-63a7-da89-573e-2ea68bd352f8
* Content: [List user transitive memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-transitivememberof.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ntrpnr for raising this issue. While **User.Read.All** and **Group.ReadWrite.All** are lesser privileged permissions and will work for this request, please note that only limited information will be returned.

Please see the following comment just [after the permissions table](https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http#permissions):

> When an application queries a relationship that returns a directoryObject type collection, if it does not have permission to read a certain derived type (like device), members of that type are returned but with limited information. With this behaviour applications can request the least privileged permissions they need, rather than rely on the set of Directory.* permissions. For details, see Limited information returned for inaccessible member objects.

You see in your response objects (when you queried while having the **User.Read.All** and **Group.ReadWrite.All** permission) that apart from the **id** property, (almost) all the other properties have the value `null`.

**Directory.Read.All** permission allow you to see all properties but, consider your app's needs before you consent to it. If the limited information is all your app needs, please consent to the least privileged permission possible. In this case, the **User.Read** would be considered the least privileged permission that'll work in the context of delegated permissions.
