### ISSUE TITLE
Settings Catalog comes back with no results

### ISSUE THREAD

**Issue by rcos152** [microsoftgraph/microsoft-graph-docs#15029]
Hello, 

When running this command, the settings catalog policies come back reporting 0 results.  

  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#deviceManagement/deviceConfigurations('PolicyID')/deviceStatusOverview/$entity",
    "id": 
    "pendingCount": 0,
    "notApplicableCount": 0,
    "successCount": 0,
    "errorCount": 0,
    "failedCount": 0,
    "lastUpdateDateTime": "2021-11-23T16:49:36.6799348Z",
    "configurationVersion": 0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1593a3d2-c97a-0f84-333b-be673f512999
* Version Independent ID: 54e409b7-6edd-f6ef-7f6d-b1dbfc8160bc
* Content: [List deviceConfigurationDeviceStatuses - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-deviceconfigurationdevicestatus-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-deviceconfigurationdevicestatus-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-deviceconfig-deviceconfigurationdevicestatus-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
I am able to get a view of device status info with a GET to this: https://graph.microsoft.com/v1.0/deviceManagement/deviceConfigurations/717863e4-09cc-411f-b7a8-875e52592bb0/deviceStatusOverview.  

My response body: {
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#deviceManagement/deviceConfigurations('717863e4-09cc-411f-b7a8-875e52592bb0')/deviceStatusOverview/$entity",
    "id": "296ce329-7fba-4b77-93b8-07d5a17f1378_717863e4-09cc-411f-b7a8-875e52592bb0",
    "pendingCount": 0,
    "notApplicableCount": 0,
    "successCount": 3,
    "errorCount": 0,
    "failedCount": 0,
    "lastUpdateDateTime": "2021-11-29T11:18:58.95Z",
    "configurationVersion": 1
}

**Comment by rcos152** [comment]
Hi @triplanedave, was that pulling one if the setting catalog policies?  I only seem to have issues pulling results for those.  Admx templates and configuration profiles work fine.

**Comment by rcos152** [comment]
Can we report this and double check the setting catalog profiles?
