### ISSUE TITLE
Cannot filter users by businessPhones attribute

### ISSUE THREAD

**Issue by pvallerie** [microsoftgraph/microsoft-graph-docs#15033]
Hello Microsoft Graph team,

I am trying to query for users while filtering against the `businessPhones` attribute, but am having trouble figuring out the proper way to do so.

Here is the HTTP Request I'm testing against your sample data in the Graph Explorer:
`https://graph.microsoft.com/v1.0/users?$filter=businessPhones/any(s:s eq '8006427676')&$count=true`
`ConsistencyLevel: eventual`

Here is the response I receive when sending the above request:
`{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported or invalid query filter clause specified for property 'businessPhones' of resource 'User'.",
        "innerError": {
            "date": "2021-11-23T16:30:23",
            "request-id": "7ebbfd52-8121-4c6c-a2cd-204241764dbe",
            "client-request-id": "7ebbfd52-8121-4c6c-a2cd-204241764dbe"
        }
    }
}`

According to the [documentation](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0), `businessPhones` should support `$filter` when using `eq` as long as `$count=true` and `ConsistencyLevel: eventual` are used since it is an Advanced Query, so I would believe this query should work as is. 

I'm assuming I must be missing something and was hoping someone would be able to point it out for me.

Thank you!
Pete Vallerie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @pvallerie for raising this issue. I've tested your exact query and it works in my tenant. Could you confirm that you're using Azure AD and not Azure AD B2C? `$count` is not supported in Azure AD B2C. Please see [query parameter limitations](https://docs.microsoft.com/en-us/graph/known-issues#some-limitations-apply-to-query-parameters).

**Comment by pvallerie** [comment]
Hi @FaithOmbongi - thanks so much for the quick response! Glad to hear that query worked for you. I was testing in the Graph Explorer and was not logged in because I'm doing some testing on my customer's behalf and don't have their credentials. Does the Graph Explorer default to Azure AD B2C if the user is not logged in?

**Comment by FaithOmbongi** [comment]
> Hi @FaithOmbongi - thanks so much for the quick response! Glad to hear that query worked for you. I was testing in the Graph Explorer and was not logged in because I'm doing some testing on my customer's behalf and don't have their credentials. Does the Graph Explorer default to Azure AD B2C if the user is not logged in?

Makes sense. 
> Does the Graph Explorer default to Azure AD B2C if the user is not logged in?

No, Graph Explorer doesn't default to Azure AD B2C in an unauthenticated session. It uses a default sample tenant instead to fulfil your read queries. I asked if it were possible you were logged in to a B2C tenant because Azure AD B2C doesn't support advanced query capabilities and the error message returned would be similar to the one you got.

> ... was not logged in ..

The advanced query capabilities are also not supported in an unauthenticated session. 

**Side note:** Azure AD B2C is a different flavor of Azure AD. While Azure AD is for organizations to manage their users (employees, partners), B2C is for organizations to manage consumer identity. For more info, please see what is [Azure AD B2C](https://docs.microsoft.com/en-us/azure/active-directory-b2c/overview)?

**Q:** I hope now that you're logged in, the query works?

**Comment by pvallerie** [comment]
Thanks for the clarification @FaithOmbongi ! This was very helpful and yes, I have the query working now that I'm logged in to an Azure AD tenant.

If you're in the States, have a great holiday! Otherwise, have a great week!

-Pete

**Comment by FaithOmbongi** [comment]
Thanks @pvallerie! And an awesome holiday to you!
