### ISSUE TITLE
Details on whether or not we can retrieve a list of send as accounts before attempt.

### ISSUE THREAD

**Issue by Will-at-FreedomDev** [microsoftgraph/microsoft-graph-docs#15035]
It isn't clear whether or not we can get a list of verified email addresses a user has access to send as or send on behalf without actually making the attempt. I've searched the docs and can't find references to getting this list, so I assume it isn't possible.

It would be great if this page was clear about whether or not it is possible to retrieve this list without making the attempt.

I was looking for documentation as we have a custom emailing web client and it would be great if we could give the signed in user a list of emails they can choose from (like Outlook can do), but I'm not seeing any documentation for or against such functionality.

This page is related so I think it would be clear to include a sentence indicating getting such a list is not possible with the API.

However, if it is possible to do what I'm looking for, then a page should be added detailing how to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61ed298-c1b2-31d1-472c-3e7b912459e9
* Version Independent ID: 1cd6a8dd-f3a9-bae9-462b-bede56d15c6c
* Content: [Send Outlook messages from another user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-send-mail-from-other-user?view=graph-rest-beta)
* Content Source: [concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/outlook-send-mail-from-other-user.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@jasonjoh should you be the person assigned to this issue? Please feel free to reassign

**Comment by jasonjoh** [comment]
@lramosvea sure, it's just a matter of adding a note that it isn't possible.
