### ISSUE TITLE
Unable to use query in documentation. This query:

### ISSUE THREAD

**Issue by anthonylevine** [microsoftgraph/microsoft-graph-docs#15032]
Odata query "https://graph.microsoft.com/v1.0/users?$filter=companyName ne null and NOT(companyName eq 'Microsoft')&$count=true" which is included within documentation does not seem to work. May need updated to reflect so. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @anthonylevine for raising this issue. Kindly add the **ConsistencyLevel** header with the value **eventual**. Please note that usage of `$filter` with `ne` operator, `$count`, and other query instances require both the **ConsistencyLevel** header and `$count` . For more information, please see the note just before the [Properties](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties) table and the [advanced query capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries) guidance.
