### ISSUE TITLE
List User Chats - Application Permissions

### ISSUE THREAD

**Issue by EvanTrow** [microsoftgraph/microsoft-graph-docs#15058]
Why Does list chats of a user only have Delegated permissions if the get chat does have Application Permissions? How is the app supposed to know what chats to get?

Needs Application Permissions to work for my project.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97dd66c-3052-87c8-ddfc-c41d180faa42
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Work to enable application permissions is going on right now. It should be available early next year.

**Comment by sunnyspan** [comment]
We need that too, a lot of work around has been used in order to list the chats of a user with the app permission currently. It's very inefficient plus making more traffic to the Graph service. It would be nice to have it available for app permission as soon as possible. Thanks🙏

**Comment by urbanonymous** [comment]
@sunnyspan Hello! What workaround were you able to use?
Would be nice to hear a solution to this problem :)

**Comment by EvanTrow** [comment]
> @sunnyspan Hello! What workaround were you able to use? We ended up with a crazy expensive solution ... Would be nice to hear a solution to this problem :)

I created a user authenticated app instead of a backend app.

**Comment by urbanonymous** [comment]
> > @sunnyspan Hello! What workaround were you able to use? We ended up with a crazy expensive solution ... Would be nice to hear a solution to this problem :)
> 
> I created a user authenticated app instead of a backend app.

Sadly we need to use application rights, not delegated.

**Comment by sunnyspan** [comment]
> @sunnyspan Hello! What workaround were you able to use? We ended up with a crazy expensive solution ...
> Would be nice to hear a solution to this problem :)

I used getAllMessages to filter out all chats that the user involved, it's expensive as well but is the only way we could think of with the app permissions for now.

**Comment by urbanonymous** [comment]
We ended up with the exact same solution, keep an eye in the new licensing costs in the v1!

**Comment by RamjotSingh** [comment]
/users/id/chats now supports application context permissions in /beta. Docs are being updated.

**Comment by RamjotSingh** [comment]
Docs have been updated.
