### ISSUE TITLE
Is there any way to filter against none human user resources (for example room resources)

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-docs#15054]
Hi, 

the user list works well, but there doesn't appear to be any mechanism to identify users in the list that are resources rather than human users. In my use case, this makes it very difficult to manage scenarios where I don't want to include room resources in the response. 

The `/people` endpoint has far more flexibility in this matter with the `personType` field. I assume there is no expandable or select data that would give this level of information in the `/users` endpoint?

I was tempted to just switch all my scenarios over to the `/people` endpoint rather than the `/users` (the relevance in searching people rather than just users is great) - but I would only do that if I could ensure at least all users of the current organization could be returned with the right search criteria but unfortunately this isn't the case - there are results that I get from `/Users` that I cannot get in the `/people` whatever criteria I try.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
@PeterNjorogeMS , kindly assist here.

**Comment by yyuank** [comment]
isResourceAccount indicates if an user object is other resource than a person. Please try this query: https://graph.microsoft.com/v1.0/users?$count=true&$filter=isResourceAccount eq true

**Comment by AlexSapple** [comment]
thanks @yyuank - but I think I must be missing something as the query above doesn't return any results regardless of isResourceAccount = true or isResourceAccount = false

I've tried this on v1.0 and beta with the same results and then just in case it's something to do with how our users are set up I've also tried using the default contoso tenant (if you don't log in to graph explorer) and same zero results

**Comment by yyuank** [comment]
Did you use "eq" instead of "="? If you used "=", you would get "bad request - invalid filter clause" result, so I assumed you used "eq". If the query doesn't return anything, it means your tenant doesn't have any user with isResourceAccount value set. I tried this query in different tenants and was able to get a list of users with "isResourceAccount eq true" from one tenant, but nothing from another. The default contoso tenant doesn't have any user with isResourceAccount value set, so that's expected.

**Comment by AlexSapple** [comment]
thanks @yyuank - sure this makes sense, but how would users be assigned as isResourceAccount? - I didn't set the users up in our tenant, but we have certain users that are set up as rooms (I'm not entirely sure how this all fits together, but on looking at the users in AD - I can't immediately see anything that makes the user a resource - I also note that the documentation states that the flag isResourceAccount isn't supported (which is discussed here- https://github.com/microsoftgraph/microsoft-graph-docs/issues/4094) 

so I'm a bit lost.

**Comment by AlexSapple** [comment]
and aren't these resources set up in my tenant? 

![image](https://user-images.githubusercontent.com/30351641/144217012-f79d4291-52ca-4083-9091-fbf025a5a36a.png)

the explanation above just doesn't appear to tally with that I'm seeing. Please can you reopen this ticket.

**Comment by yyuank** [comment]
Not all the conference rooms are modelled as "user.isResourceAccount eq true". I don't have the historical context of how this was decided. My guess was some legacy Microsoft 1st party app was using this property to model conference rooms and later switched to something else. Thus isResourceAccount is then "deprecated" (Do not use). My guess is that this property is set by some Microsoft 1st party apps and customers won't be able to set this value.

**Comment by AlexSapple** [comment]
ok, thanks @yyuank - I appreciate your effort looking in to this. I guess that means in my case, ultimately, and going back to the original question, there isn't going to be a reliable way to determine a resource account from the users endpoint (depending on _how._ resources have been setup)

thanks for clarifying.

I guess my options are; 
1. nasty - maintain a local record of resource Ids to filter out my end)
2. good - migrate to /people endpoint that does give flexibility for this sort of filtering (but with the caveat that I can't get a like for like set of organization users on this endpoint even with search criteria)

I'll mull it over, 

thanks again.
