### ISSUE TITLE
ConsistencyLevel is 'eventual', Graph does not return a count of users

### ISSUE THREAD

**Issue by rrperkin** [microsoftgraph/microsoft-graph-docs#15067]
The page's "Example 3: Get only a count of users" specifies instructions to query GET:
```
GET https://graph.microsoft.com/v1.0/users/$count
ConsistencyLevel: eventual
```
... and predicts a text/plain response with an integer as the output. 

Using MS Graph Explorer with the AAD admin user, as pictured, instead results in 400 Bad Request: 

```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "$count is not currently supported.",
        "innerError": {
            "date": "2021-11-29T20:44:59",
            "request-id": "641ded75-e733-4d7d-a1ee-5291ad90b7da",
            "client-request-id": "02d96d92-a91b-4eee-5cdd-6e63587fff8d"
        }
    }
}

```

Please let's not waste anyone's time closing this over ConsistencyLevel. See attached screencap. The behavior is the same with both the beta and 1.0 endpoints.

![image](https://user-images.githubusercontent.com/466101/143941159-af4d4ebc-2082-4863-8dbe-4bafcf6f8a6a.png)

You could correct the documentation to remove the example. It would be better to have clear instructions on how to do the thing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rrperkin** [comment]
More info: The AAD instance is an "Azure B2C" directory. However, the authenticated admin user is a "standard" AAD user with admin rights. 

I read elsewhere that the $count feature is not lit up on B2C instances. If that's the case, then an annotation or some notes saying so would have prevented me from wasting 45 minutes today. An error message that actually said "not supported on B2C" that instead of the generic uselessness of seeing "not currently supported" would have made the whole thing resolve sooooo much faster.

**Comment by FaithOmbongi** [comment]
Thank you @rrperkin for raising this issue and I apologize for the bad experience. Yes, `$count` isn't supported in Azure AD B2C.  The following statement is currently declared in the [Optional query parameters](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) section: 

> The `$count` and `$search` parameters are currently not available in Azure AD B2C tenants.

and in the [query parameters limitations](https://docs.microsoft.com/en-us/graph/known-issues#some-limitations-apply-to-query-parameters).

As for the error message, the engineering team has an internal work item to make error messages related to [advanced query capabilities](https://docs.microsoft.com/en-us/graph/aad-advanced-queries) more on point. Can't promise a definitive ETA. A related feature request has been filed here: [search for group in Azure AD B2C](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/please-add-option-to-search-for-group-in-b2c-tenant/idi-p/2910888). You can add to it/upvote and amplify the request or, you can open a new feature request and others can amplify your voice or, you can send feedback to the [advanced query capabilities engineering team](https://aka.ms/MsGraphAADSurveyDocs).

cc @Licantrop0

**Comment by rrperkin** [comment]
I ask that the issue stay open. 

You have how-tos for both $count and $search. I am asking that the text "The $count and $search parameters are currently not available in Azure AD B2C tenants" appear in examples that use those elements. I would have saved me a lot of time, since my entry point into the documentation came after a websearch on the useless error message that appeared in Graph Explorer. 

Add the text in each of the examples and you'll be doing all humankind a service. Do it for the people. 

And, of course, more generally, MS could stop not supporting features in B2C or at least kick out "unsupported in B2C" errors when they're attempted. I filled out the form. I imagine the work to make the error messages is not terribly dissimilar to the work to introduce the feature support, but that's a detail for a different scope, right?
