### ISSUE TITLE
Company Branding - update banner/logo/image does not work

### ISSUE THREAD

**Issue by astaykov** [microsoftgraph/microsoft-graph-docs#15061]
I am trying to make company branding working for changing Images. Nothing works so far.

The given sample, to minimum is wrong:
```
PATCH https://graph.microsoft.com/v1.0/organization/{tenant_id}/branding/bannerLogo
Content-Type: image/jpeg

<Image>
```

As by executing it, I get the following error:
```json
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Invalid locale id value bannerLogo. It must be a valid ISO-639 locale.",
        "innerError": {
            "date": "2021-11-29T09:08:56",
            "request-id": "31233f29-59d3-4aeb-985d-21a9e3bfa0d8",
            "client-request-id": "31233f29-59d3-4aeb-985d-21a9e3bfa0d8"
        }
    }
}
```

The error - `Invalid localte id value *bannerLogo*` hints me, that the path is not correctly recognized. So I tried comple of variations I came to, by reading the object properties and documentation:

Option one: tried using `0` or `default` as path, right after the `/branding/` and before `bannerLogo`:
```
 PATCH 'https://graph.microsoft.com/v1.0/organization/{tenant_id}/branding/default/bannerLogo'
```

Then I got (equally same for `0` and `default`:
```
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'default'.",
        "innerError": {
            "date": "2021-11-29T09:15:02",
            "request-id": "45092228-06c0-483b-89ae-03a94d595f82",
            "client-request-id": "45092228-06c0-483b-89ae-03a94d595f82"
        }
    }
}
```

Next was one step further - `/branding/localizations/default/bannerLogo`:
```
PATCH 'https://graph.microsoft.com/v1.0/organization/{tenant_id}/branding/localizations/default/bannerLogo'
```

And I got Internal server error:
```json
{
    "error": {
        "code": "Service_InternalServerError",
        "message": "Encountered an internal server error.",
        "innerError": {
            "date": "2021-11-29T09:16:49",
            "request-id": "61442e7a-dbcd-4bed-a4a0-59429a6a1fc8",
            "client-request-id": "61442e7a-dbcd-4bed-a4a0-59429a6a1fc8"
        }
    }
}
```

Now this error at least hints me I am on the correct path and documentation sample about updating Logo is wrong. But still no result.

Note: I am using application only permissions, which according to documentation is not supported. However, changing the texts (`usernameHintText`, `signinPageText`) is working perfectly fine. And the errors given back by the Microsoft Graph for logos, do not hint there is a permission issue.

> Please provide correct documentation and a working sample of updating branding logo.

P.S. My tenant is Premium P2 liensed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2e613fe-3bcb-b071-8277-1437ad7b77e9
* Version Independent ID: 42a4cb6a-9008-cfbe-90f4-f127efcbf75b
* Content: [Update organizationalBrandingLocalization - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/organizationalbrandinglocalization-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/organizationalbrandinglocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/organizationalbrandinglocalization-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @AlexanderMars
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @astaykov for raising this issue. I'm following up with engineering and will get back to you.

**Comment by AlexanderMars** [comment]
Hi @astaykov,

Thanks for reaching out and reporting the issue/s. There are a few things.

1. PATCH doesn't work for stream properties at the moment. We're investigating the root cause of the issue. Please, use PUT method instead: PUT https://graph.microsoft.com/beta/organization/{tenant_id}/branding/localizations/0/bannerLogo
2. Please, use localizations to update any stream property.

We will update the documentation accordingly. Please, let me know if you have any questions.

Thank you.

Kind regards,
Sasha
