### ISSUE TITLE
Missing request information

### ISSUE THREAD

**Issue by nickp85** [microsoftgraph/microsoft-graph-docs#15088]
For this page, there is no sample request, just the response.

For example as reverse engineered from the Intune GUI
`https://graph.microsoft.com/beta/deviceManagement/managedDevices/<deviceid>/deviceCompliancePolicyStates/<policyid>/settingStates`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ea2e73-84d1-b937-6e10-5dd2ebe9138d
* Version Independent ID: 3a431f56-597b-c77e-4ecb-aca820d3d60d
* Content: [deviceCompliancePolicySettingState resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-devicecompliancepolicysettingstate?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-deviceconfig-devicecompliancepolicysettingstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-deviceconfig-devicecompliancepolicysettingstate.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback.  This setting state is an output only property. There is no way to generate a new setting state object, the system does that automatically based on a configuration profile assigned to a device.
