### ISSUE TITLE
hasExtendedValue

### ISSUE THREAD

**Issue by chadmcox** [microsoftgraph/microsoft-graph-docs#15092]
Anyway to document this attribute being returned?

hasExtendedValue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb6264f4-f053-bf11-15ae-528652ff8a79
* Version Independent ID: 90aa6e1d-6efa-5100-b51f-7766325086a6
* Content: [keyCredential resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/keycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/keycredential.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by madansr7** [comment]
@FaithOmbongi , @chadmcox  
We do not intend to make this a first-class property. This property was introduced to help customers mitigate a security issue and will be removed in the near future. The property was introduced with a deprecation annotation with a clear intention of removing it after a certain date/time.
Updating the metadata will start to reflect this property in SDKs and we do not want to go that route.
Closing the issue.
