### ISSUE TITLE
List messages of meeting chat alone

### ISSUE THREAD

**Issue by bkmalan** [microsoftgraph/microsoft-graph-docs#15113]
Hey,

I'm curious to know if there's a way to get the chat messages of a particular meeting in a channel alone.The list messages using chatId list the messages of the entire channel.

TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fa912d-43d1-099b-44d5-fdcdaae00db7
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessage: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
https://docs.microsoft.com/en-us/graph/api/chatmessage-list-replies?view=graph-rest-1.0&tabs=http allows you to just list replies of a root message in a channel. If you knw the root message which has meeting in it. You can use this API to list the replies.
