### ISSUE TITLE
How to find Guest User Creator

### ISSUE THREAD

**Issue by bolte04** [microsoftgraph/microsoft-graph-docs#15123]
Hello,

we are currently developing a guest user management solution and would like to find out who has created a guest user inside the AAD.  The only solution we found for this specific case is to query the Audit Log and watch for the specific guest user creation events.

Is there a way to get the creator of a guest in any other / easier way? 

Having access to the audit log is a pretty high right, which not all customers will be happy to grant - therefore it would be nice to have a less privileged permission / way to get this information.

Kind regards
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3a74bbc-2a8b-1ff6-78e3-e33f143e41db
* Version Independent ID: b9f3185c-1406-e1eb-99b8-edbc84c4e58a
* Content: [Activity reports API overview - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/azure-ad-auditlog-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/azure-ad-auditlog-overview.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @jpettere, @Sammak — could you assist here? Thanks.

**Comment by Sammak** [comment]
Unfortunately, monitoring audit logs is the only way to get the inviter for a guest today. We are planning a feature that will help track this relationship in the future, but can't share any dates at this point.

**Comment by FaithOmbongi** [comment]
Thank you @Sammak for providing this clarity. Closing this issue.
