### ISSUE TITLE
Updating event leads to error "ID is malformed"

### ISSUE THREAD

**Issue by aggr0lite** [microsoftgraph/microsoft-graph-docs#15159]
I followed the steps in the documentation, trying to build a flow with Power Automate in order to update an event in a group calendar. I can get all events in the calendar, using the group id and the according HTTP call from the doc: 

https://graph.microsoft.com/v1.0/groups/{id}/events

However, when I try to update an existing event with PATCH https://graph.microsoft.com/v1.0/groups/{id}/events/{id}, it leads always to the error "ID is malformed". 

The id I use for the event is exactly the one I get as a response from the call above, listing all events of the calendar. It looks like this:

AAMkADc5MmRmNDRhLTY4NTktNDE2ZS1hYzAzLWM4MWQzMjAwNjg1NABGAAAAAAB0mOFeCiThRL7fP5F8sbm8BwCFIXOlwiZRQbNe_eybqpg5AAAAAAENAACFIXOlwiZRQbNe_eybqpg5AAFjpuDSAAA=

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 96b913ec-91b7-a82e-4443-ac60cf86517b
* Version Independent ID: 497daf1d-7ecb-b4c5-6787-758630023490
* Content: [Ereignis aktualisieren - Microsoft Graph v1.0](https://docs.microsoft.com/de-de/graph/api/group-update-event?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-update-event.md](https://github.com/microsoftgraph/microsoft-graph-docs.de-DE/blob/main/api-reference/v1.0/api/group-update-event.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Please report issues through support ticket for the product development team to triage.
