### ISSUE TITLE
The shortlink for the overview video is broken

### ISSUE THREAD

**Issue by michou** [microsoftgraph/microsoft-graph-docs#15160]
The shortlink for the Microsoft Teams API overview video `https://aka.ms/teamsgraph/v1/video` is broken. After some fiddling with the link it looks like it should point to `https://aka.ms/teamsgraph` instead – although I'm not really sure about that, as it's actually a link to this very page (that does have a video at the very beginning, though...).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4f5720-3eb2-fe1d-472e-497d1449f97b
* Version Independent ID: eaa22434-4691-77e2-8905-bf6d7e9e0bef
* Content: [Microsoft Teams API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-concept-overview)
* Content Source: [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-concept-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
We are assigning it to doc team.

Thanks

**Comment by HunaidHanfee-MSFT** [comment]
@@surbhigupta12 -
https://docs.microsoft.com/en-us/graph/teams-concept-overview#next-steps - The first watch video link is incorrect and it's opening Bing.

**Comment by v-chetsh** [comment]
@AkJo - The first watch video link is incorrect and it's opening Bing:
https://docs.microsoft.com/en-us/graph/teams-concept-overview#next-steps

Could you please help to update it to the correct one?

**Comment by lramosvea** [comment]
Hi @AkJo could you please assist to update the link to the video? Thanks

**Comment by sayali-MSFT** [comment]
@AkJo - The first watch video link is incorrect and it's opening Bing:
https://docs.microsoft.com/en-us/graph/teams-concept-overview#next-steps

Could you please help to update it to the correct one?

**Comment by lramosvea** [comment]
@isvargasmsft could you help on this?

**Comment by AkJo** [comment]
@surbhigupta12 please look into this.

**Comment by isvargasmsft** [comment]
This one is resolved.
