### ISSUE TITLE
Default value for type is very ambiguous in the description

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#15191]
For the type property (see bold face in the description below).

Specifies whether this delegated permission should be considered safe for non-admin users to consent to on behalf of themselves, or whether an administrator should be required for consent to the permissions. **This will be the default behavior**, but each customer can choose to customize the behavior in their organization (by allowing, restricting or limiting user consent to this delegated permission.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b76052a-a68f-47e1-24be-1d5828712fb4
* Version Independent ID: edefe199-37ab-ca8f-8565-f3bc92db56b7
* Content: [permissionScope resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/permissionscope?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/permissionscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/permissionscope.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @dkershaw10 for highlighting this. The intent was to indicate that the tenant admin can override the consent requirement specified in the **type** property for a delegated permission. I'll raise a PR to make the description clearer.
