### ISSUE TITLE
Filtering Users by businessPhones using startsWith returning BadRequest response

### ISSUE THREAD

**Issue by pvallerie** [microsoftgraph/microsoft-graph-docs#15207]
Hello Microsoft Graph API team,

I'm attempting to filter _Users_ by _busnessPhones_ using _startsWith_, but consistently receiving a _BadRequest_ response. We are working with a B2B account, so advanced queries such as filtering by _businessPhones_ should be available to us.

According to [this doc](https://docs.microsoft.com/en-us/graph/aad-advanced-queries), the below query should return any user whose businessPhones attribute contains a number starting with '44 121'. 

```
URL:
https://graph.microsoft.com/v1.0/users?$filter=businessPhones/any(p:p startsWith '44 121')&$count=true

Headers:
ConsistencyLevel=eventual
```

Am I misunderstanding the documentation?

Thank you!
Pete Vallerie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Azure AD directory objects - Microsoft Graph](https://docs.microsoft.com/en-us/graph/aad-advanced-queries)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/aad-advanced-queries.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Licantrop0
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @pvallerie for raising this issue. I see the error is in your syntax; how you've declared the `any `lambda operator with `startsWith`. Kindly correct the URL as follows:

Try in Graph Explorer: [https://graph.microsoft.com/v1.0/users?$filter=businessPhones/any(p:startsWith(p, '44 121'))&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24filter%3DbusinessPhones%2Fany(p%3AstartsWith(p%2C%20'44%20121'))%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&requestBody=eyJhY2NvdW50RW5hYmxlZCI6dHJ1ZSwiZGlzcGxheU5hbWUiOiJUZXN0IFVzZXIiLCJtYWlsTmlja25hbWUiOiJ0ZXN0K1VzZXIiLCJ1c2VyUHJpbmNpcGFsTmFtZSI6IlRlc3QrVXNlckBtMzY1eDAxMDcxNy5vbm1pY3Jvc29mdC5jb20iLCJwYXNzd29yZFByb2ZpbGUiOnsiZm9yY2VDaGFuZ2VQYXNzd29yZE5leHRTaWduSW4iOnRydWUsInBhc3N3b3JkIjoieFd3dkpdNk5NdytiV0gtZCJ9fQ==&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)

**Comment by pvallerie** [comment]
Thanks, @FaithOmbongi! That did work.
