### ISSUE TITLE
Privacy APIs availability

### ISSUE THREAD

**Issue by medha-bhatt** [microsoftgraph/microsoft-graph-docs#15224]
Hi,

When are the Privacy APIs going to be publicly available?  Is there an official release date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73c27d5f-1d12-c868-cc64-8e893cdbdb53
* Version Independent ID: 948b4ea0-2c2b-a9a4-5f53-036bf9afb445
* Content: [Use the Microsoft Graph subject rights request API - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subjectrightsrequest-subjectrightsrequestapioverview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/subjectrightsrequest-subjectrightsrequestapioverview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subjectrightsrequest-subjectrightsrequestapioverview.md)
* Product: **compliance**
* Technology: **microsoft-graph**
* GitHub Login: @skadam-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by skadam-msft** [comment]
The API are publicly available. Please give them a try.
