### ISSUE TITLE
MeetingRegistration - 400 Bad Request

### ISSUE THREAD

**Issue by Venkman42** [microsoftgraph/microsoft-graph-docs#15231]
Hi to anyone reading this,

I wanted to test the "create meetingRegistration" feature in Microsoft Graph, but I always get back bad request.
("Invalid request. Provide microsoft.graph.meetingRegistration or microsoft.graph.externalMeetingRegistration in request body.")
I tried it directly from Graph Explorer.

 Here are my steps:

- Create a new OnlineMeeting with the same parameters as mentioned in Microsoft Doc.
With POST Beta "beta/me/onlineMeetings"
Request Headers:
Key:Content-Type; Value:application/json

This works perfectly fine, except the meeting doesnt show up in my calendar, but it gets created and I get a working JoinLink.

- Trying to create a registration for the previously created meeting
With POST Beta "beta/me/onlineMeetings/Meeting ID/registration
Request Headers:
Key:Content-Type; Value:application/json

I used the same time as specified in the OnlineMeeting and the correct id(Get OnlineMeeting works with the ID)
I also used the same parameters as mentioned in the Microsoft Beta Doc for meetingRegistration, except for the custom questions.(I've also tried it with the custom questions, to have everything exactly like in the docs, but no difference).

When I hit enter I just get Error 400 bad request.

Are there any specific requirements for the meeting to be able to create registration, or am I missing any steps?

Thanks in advance,

Cheers 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50b793da-a2ac-f561-f664-63d1b1632d67
* Version Independent ID: f6310d55-e577-ca10-502e-84be532e79e1
* Content: [Create meetingRegistration - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/meetingregistration-post?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/meetingregistration-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/meetingregistration-post.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mkhribech
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Venkman42** [comment]
Hi @frankpeng7 ,
I've seen you were involved in the beta docs for meetingRegistrations too and are quite active on here.
Could you maybe take a look at my issue and help out? One of our customers would really like to implement this feature, but I cant get it to work.

If needed I can also provide more detailed information.

Thanks in Advance,
Cheers

**Comment by frankpeng7** [comment]
Hi @Venkman42, apologies for the breaking experience. This is due a recent change to support meeting registration with external registration system. The documentation for some reason was delayed and now we are targeting this Friday to release the documentation. To fix your issue (this will also be included in the documentation) please add this new property in your reuqest
```
{
    "@odata.type": "#microsoft.graph.meetingRegistration"
}

**Comment by Venkman42** [comment]
> Hi @Venkman42, apologies for the breaking experience. This is due to a recent change to support meeting registration with external registration system. The documentation for some reason was delayed and now we are targeting this Friday to release the documentation. To fix your issue (this will also be included in the documentation) please add this new property in your request
> 
> ```
> {
>     "@odata.type": "#microsoft.graph.meetingRegistration"
> }
> ```
Thanks so much for the quick reply :) 
I still can't get it to work with that, but I will take a look at the new documentation next week and try again.

Thanks anyway ^^ 
If I still can't get it to work next week I'll give you feedback again :)

Cheers

**Comment by frankpeng7** [comment]
Btw @Venkman42 I noticed you were trying registration APIs with Graph explorer. There's a known issue where Graph explorer automatically adds `accept-language` header (even though you didn't specify it) in a format that we don't recognize. Can you try the same request (you can copy-paste the token from Graph explorer) in Posman or Fiddler? If it still doesn't work, please provide the `client-request-id` and timestamp in the response headers I can look something up

**Comment by PunchcardCoder** [comment]
I am experiencing the exact same problem and I've gone through the same exercises as @Venkman42 to replicate the example from the docs (including @odata.type and all that). Has anyone managed to get this to work?

**Comment by PunchcardCoder** [comment]
After tinkering for another hour: meetingRegistration fails for onlineMeeting with `"isBroadcast":"true"` . It works with `"isBroadcast":"false"`

Whoever at MS is reading this: it'd be really good if meetingRegistration and externalMeetingRegistration could go to GA before the next COVID lockdown is upon us. We'd like to tie it to a timeslot reservation/ticket-system for a museum. That way, they can offer paid live online visits when they are not allowed to have real visitors. Thanks

**Comment by frankpeng7** [comment]
@PunchcardCoder You are correct - so far we don't support registration for broadcast meetings (Teams live events). I can improve the error message to better reflect this.

@mkhribech FYI on the customer ask^

**Comment by PunchcardCoder** [comment]
Thanks. Updating the error msg would help... as would including the constraint in the docs.

**Comment by Venkman42** [comment]
> Btw @Venkman42 I noticed you were trying registration APIs with Graph explorer. There's a known issue where Graph explorer automatically adds `accept-language` header (even though you didn't specify it) in a format that we don't recognize. Can you try the same request (you can copy-paste the token from Graph explorer) in Posman or Fiddler? If it still doesn't work, please provide the `client-request-id` and timestamp in the response headers I can look something up

Hi @frankpeng7  ,
Thanks so much for your input! I got it to work with your tips and postman!
I just have one more question you might be able to answer:
Is it normal that OnlineMeetings don't show up in a users calendar?
I guess it's possible to get the teams-join-url and just post it in an event, but is this intentional?

Thanks in advance!

You've been really helpful already :)

Cheers

**Comment by frankpeng7** [comment]
Hi @Venkman42 Yes the meetings created through /onlineMeetings API are not associated with any calendar event hence they won't show up on the calendar. This is described in our doc (see below)
![image](https://user-images.githubusercontent.com/16726609/152044437-1d4e1841-d0aa-44cb-9094-1ce04aed9204.png)
