### ISSUE TITLE
Changes to an existing permission object do not show up in driveitem delta

### ISSUE THREAD

**Issue by Loxxlie** [microsoftgraph/microsoft-graph-docs#15242]
Currently, certain changes to an existing permissions do not generate a webhook notification despite a subscription to the drive, nor does a driveItem delta query against the drive return any changes.

One example of such a change is the addition of an external user to an existing link.

1. Create a new link using "Specific People" and add an internal user.
<img width="336" alt="1-new-link-with-internal-user" src="https://user-images.githubusercontent.com/5957902/145912215-7cc42652-d640-4aaf-91d9-973ee54897ce.png">

Delta Output (shorted for brevity):
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "@odata.deltaLink": "<redacted>",
    "value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "createdDateTime": "2019-10-27T05:48:18Z",
            "lastModifiedDateTime": "2021-12-14T00:27:21Z",
            "name": "root",
            "folder": {
                "childCount": 7
            },
            "root": {},
            "shared": {}
        },
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "@microsoft.graph.sharedChanged": true,
            "createdDateTime": "2021-12-14T00:26:33Z",
            "eTag": "\"{2332ECD8-2774-4832-BE71-C94DAB29D4A9},9\"",
            "lastModifiedDateTime": "2021-12-14T00:27:22Z",
            "name": "sample-document.docx",
            "shared": {
                "scope": "users"
            }
        }
    ]
}
```

2. Add an external user to the same link.
<img width="331" alt="2-edit-link-with-external-user" src="https://user-images.githubusercontent.com/5957902/145912326-71df753a-fb15-46fe-af75-083df72884e1.png">

Delta Output:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "@odata.deltaLink": "<redacted>",
    "value": []
}
```

3. Add another internal user.
<img width="329" alt="3-edit-link-with-internal-user" src="https://user-images.githubusercontent.com/5957902/145912439-c24445bb-e69d-4319-b64d-92cfb01ba796.png">

Delta Output:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "@odata.deltaLink": "<redacted>",
    "value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "createdDateTime": "2019-10-27T05:48:18Z",
            "lastModifiedDateTime": "2021-12-14T00:27:21Z",
            "name": "root",
            "folder": {
                "childCount": 7
            },
            "root": {},
            "shared": {}
        },
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "@microsoft.graph.sharedChanged": true,
            "createdDateTime": "2021-12-14T00:26:33Z",
            "eTag": "\"{2332ECD8-2774-4832-BE71-C94DAB29D4A9},10\"",
            "lastModifiedDateTime": "2021-12-14T00:27:22Z",
            "name": "sample-document.docx",
            "shared": {
                "scope": "users"
            }
        }
    ]
}
```

Sharing a file with an external user might be a consequential change I want to be informed of. If this is not the appropriate way to monitor these types of permission changes, please let me know the correct way. Thanks.

Related documentation:
https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0
https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5785f90e-b37c-c5a5-ddbc-7170307980c9
* Version Independent ID: d8b7729e-38c4-5562-7359-5e926f8d7ae4
* Content: [driveItem: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/driveitem-delta.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Bimal-Gangawal** [comment]
I am also facing similar issues, 
Is there any way around for the same ?

**Comment by ArturasJakubauskas** [comment]
Same issue, any plans to fix this?

**Comment by THoVer** [comment]
Experiencing same issue. Would like to know if it is a bug, or it is not intended to be used this way and another approach should be used instead.
