### ISSUE TITLE
peticiones GET en español

### ISSUE THREAD

**Issue by jaumebalust** [microsoftgraph/microsoft-graph-docs#15259]
[Escriba sus comentarios aquí]
Quien dice OBTENER? sería mucho mejor poner GET...

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8428b093-c293-a3f0-7a2d-7e38f90e1165
* Version Independent ID: 257cf339-20e1-7756-637c-149719b93790
* Content: [Información general sobre la API de OneNote - Microsoft Graph](https://docs.microsoft.com/es-es/graph/integrate-with-onenote)
* Content Source: [concepts/integrate-with-onenote.md](https://github.com/microsoftgraph/microsoft-graph-docs.es-ES/blob/main/concepts/integrate-with-onenote.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by j0rt3g4** [comment]
El problema es que es un motor de traducción si dice GET traduce a lo que conviene, por tanto no veo viable este cambio ya que requeriria seleccionar que traducir y que no... y bueno, cómo tu ya sabes q es GET la recomendación es pues que uses GET.

**Comment by jaumebalust** [comment]
Dile a quina haya decidido lo del motor de traducción, que hay palabras reservadas (y más aun si estan en mayúscula).

me voy a pone a programar en <hacheTeMeLe></hacheTeMeLe> y haré un <formulario></formulario>

Saludos!

**Comment by j0rt3g4** [comment]
jaja Concuerdo :) sólo que cómo dije antes, no creo q persona alguna vaya a hacer cambio alguno. 

Yo no le digo nada a nadie :) soy una persona igual q tu, no tengo potestad de decir o dictar cosas y menos a Microsoft.

**Comment by lramosvea** [comment]
Closing this issue as we have raised an issue internally with the localization team to get this fixed. Thanks!
