### ISSUE TITLE
known issue link is broken

### ISSUE THREAD

**Issue by dBotLFG** [microsoftgraph/microsoft-graph-docs#15314]
[Enter feedback here]
The link for known issue is broken, 404
should resolve to:
https://docs.microsoft.com/en-us/graph/known-issues#license-check-errors-for-azure-ad-activity-reports
but instead is:
https://docs.microsoft.com/en-us/graph//graph/known-issues#license-check-errors-for-azure-ad-activity-reports

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/signin-list.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by besiler** [comment]
Thanks for the report! We have a PR in place to fix this: https://github.com/microsoftgraph/microsoft-graph-docs/pull/15287#pullrequestreview-836735292
