### ISSUE TITLE
chatMessageHostedContent max size

### ISSUE THREAD

**Issue by jamie-everlaw** [microsoftgraph/microsoft-graph-docs#15334]
Is there a maximum size for chatMessageHostedContent? Obviously, would be great to have the size included in the chatMessageHostedContent resource, but in lieu of that a documented max size would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67128427-1b31-10dc-7f59-20e90fe612b4
* Version Independent ID: 320532ec-6603-a341-9856-46b788adb461
* Content: [chatMessageHostedContent resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/chatmessagehostedcontent.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
There isnt exactly a set maximum size because hosted content represents images, videos alike. Generally you should not see size go beyond 3 Gigs as at that point we try to split files up, but that is not a set maximum length.

**Comment by RamjotSingh** [comment]
While posting the maximum size if 4 MBs however.

**Comment by jamie-everlaw** [comment]
Got it. I'll file an API feature request then. Appreciate the quick response!
