### ISSUE TITLE
[Feature Request] Return id after sending email 

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1533]
Right now after sending an email 

```
POST https://graph.microsoft.com/v1.0/me/sendMail
```

Request Body:

```json
{
  "message": {
    "subject": "hello",
    "body": {
      "contentType": "Text",
      "content": "hello world!"
    },
    "toRecipients": [
      {
        "emailAddress": {
          "address": "myemail@example.com"
        }
      }
    ]
  }
}
```

The `response` is null, it does not return any **id** for the mail.

Please at least return the basic info **id** to help developers easily control app states. Thanks

**Reason: After sending the email, developers will save the email info in the app state. However, if the app fetches the emails including that one again, there is no easy way to know any of the emails is same with the email stored before in the app state, which will cause saving two emails in the app state.**

**Comment by phorust** [comment]
I also have this ask, and I'll elaborate a little bit.

If you send an email using the /me/sendMail endpoint, you don't receive any information about the email. If your app needs to store the id, or any other information about the email, a JSON response would be better. For this reason the app I'm working on first POSTs to `/me/messages` to create a draft, saves the `id` from the response, and then POSTs to `/me/messages/<id>/send`.

If you could POST to `/me/sendMail` and just receive the same information back as POST to `/me/messages`, that'd be great

**Comment by Hongbo-Miao** [comment]
One alternative way I thought is saving in draft first and then send out. But the problem is even I save the mail in draft first, after sending, the mail id actually changed. So I cannot use this way neither.

**Comment by Hongbo-Miao** [comment]
Ok, the team is working on an ImmutableId, hopefully it will release soon.

**Comment by Hongbo-Miao** [comment]
Another better way is actually using **open extension**, you add a hidden id to the mail when you send out. When you get new mails, compare the hidden id. But I met the issue [cannot return open extension when use delta](https://github.com/microsoftgraph/microsoft-graph-docs/issues/1993).
I will close this now since using open extension is a better way.

**Comment by phorust** [comment]
@Hongbo-Miao, where did you see that the team is working on an immutable ID? if that's implemented soon it'll solve another issue I have where draft emails `id`s change when they are sent, so keeping track of when a draft email was sent is difficult

**Comment by Hongbo-Miao** [comment]
@phorust it is internal document.
As I mentioned above, you should use open extension to add a hidden id to the mail in the draft, when you fetch mails again, you can compare that hidden id.
It is even faster than waiting the id returns.

**Comment by Hongbo-Miao** [comment]
@phorust 
Even if immutable ID released, you should still use open extension to add a hidden id to the mail in the draft, after you send mail, when you fetch mails again, you can compare that hidden id which won't change. Because this way is faster than waiting the id returns.

Disclosure: I am working for Microsoft.

**Comment by Hongbo-Miao** [comment]
Hi @phorust I think it is ready now, but I think there is no public document in Graph yet.
Check my https://stackoverflow.com/questions/48087082/how-to-use-immutableid-in-microsoft-graph-for-mails-correctly

**Comment by Hongbo-Miao** [comment]
Hi @phorust I think it is ready now, but there is no public document in Graph yet.
You can track here for when the doc will be added https://github.com/microsoftgraph/microsoft-graph-docs/issues/2111

Before that, check my question and answer here to know how to use it https://stackoverflow.com/questions/48087082/how-to-use-immutableid-in-microsoft-graph-for-mails-correctly

**Comment by Hongbo-Miao** [comment]
@phorust please wait the Immutable Id officially publish. Or if you are requesting from Facebook, you should already have the early access of it.

**Comment by djnhh0an** [comment]
Dear @Hongbo-Miao : Could you please update status on this issue?

**Comment by Hongbo-Miao** [comment]
I am also waiting Immutable Id, but I can tell it is definitely not ready for production use. If need further info or want to be an early adaptor to test, please contact Outlook team (I am working in Excel team)

**Comment by kudeshiyah** [comment]
any update on this issue?

**Comment by MKahmen** [comment]
Still no fix? So I have to use filters and custom identifiers to dig through my sent-folder just because Microsoft can't just return the id like it does when creating a draft?

**Comment by Hongbo-Miao** [comment]
I have left Microsoft. Just reopen this and let Microsoft people solve and close this issue later.

**Comment by lievenjanssen** [comment]
Current Microsoft people are you there? Looks like a 👻🏠 here!

**Comment by Apollinaire** [comment]
I have tried with the immutable Ids on both the `/beta` endpoint and the v1 endpoint:
POST on `/me/messages` to create a draft and get an immutable Id.
POST on `/me/messages/{immutable-message-id}/send` to send the mail
Wait a moment (10 seconds)
GET `/me/messages/{immutable-message-id}` -> 404 not found.
Both "immutable" ids are the same except for the last 4 characters:
```
from draft:         .....................................................LiCbgAAABDVagAA
in the sent folder: .....................................................LiCbgAAABDVbAAA
```

So that means we have Immutable Ids, but apparently when you send a draft the resource is deleted and a new one is created in the `Sent` folder. So the "immutable" ids are different.
I found a workaround to this: use the `conversationId` to find the sent message. If it's a new message you're creating, the `conversationId` field on the draft will (hopefully) be unique and won't change when you send the message. So then you can do:
```
GET /me/messages?$filter=conversationId eq '{conversationId-from-draft}'
```
That should return: 
```js
{
  @odata.context: 'whatever',
  value: [
    {
      id: messageId, // <- the correct 'sent' message Id
      ...all the rest from the message resource
    }
  ]
}
```

**Comment by AlmogBaku** [comment]
just set an `internetMessageId` when you create the message, the search for it `/users/{{user}}/messages?$filter=internetMessageId eq '<c56b29ba-e5f9-4a38-bfab-9f6f47a86814@cis.cyren.cloud>'`

**Comment by Apollinaire** [comment]
I agree that this is one of the workarounds. To avoid using a potentially useful field you can also use a personal extension I think. However, I think fixing the problem at the root is better than letting people find hacky workarounds to their poorly designed API.

**Comment by Misiu** [comment]
This would be super useful. Right now we must create drafts, then send it, that's two requests, with this feature implemented we would only have to do a single request.

**Comment by iflow** [comment]
See my workaround in this comment: https://github.com/microsoftgraph/microsoft-graph-docs/issues/6256#issuecomment-559440385
