### ISSUE TITLE
Provide example URLs at every example

### ISSUE THREAD

**Issue by gonardfreeman** [microsoftgraph/microsoft-graph-docs#15337]
Please provide example URLs with domain in it in all examples.
Example:
**NOT** `/post/example`
**YES** `https://login.microsoft.com/post/example`
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4323239e-0486-0f8f-6f2b-5e41e6178594
* Version Independent ID: 627883a9-8cd7-93cd-358d-b841d390714b
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-user.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Hi @gonardfreeman, I've [opened a PR here](https://github.com/microsoftgraph/microsoft-graph-docs/pull/15626) to address your comments. Thanks for your feedback on our docs!
