### ISSUE TITLE
Get Hosted Content Value with Application Permission is forbidden in GCC High Environment

### ISSUE THREAD

**Issue by longnlp** [microsoftgraph/microsoft-graph-docs#15356]
Hello Team,

I have an application which got approval from the protection API, and it does have permission to access the channel message, but it doesn't have permission to access the hosted content value, is the Graph API for Hosted Content supported in GCC High Environment? If this is supported, can you help investigate this issue? 

And following is the details for the request/response.
GET https://graph.microsoft.us/v1.0/teams/7514796d-5c0a-48b4-ab58-1494878ff586/channels/19:gcch:0150d727b82f4626abce47e01ea8c4a6@thread.skype/messages/1639455333840/hostedContents/aWQ9eF8wLWdvdnR4LWQxLWE3NWRjNTg0NWNmMTQ5NTJkYTkzOTkwMDA3NTBmNGM4LHR5cGU9MSx1cmw9aHR0cHM6Ly9hcGkuYW1zLmdvdi50ZWFtcy5taWNyb3NvZnQudXMvdjEvb2JqZWN0cy8wLWdvdnR4LWQxLWE3NWRjNTg0NWNmMTQ5NTJkYTkzOTkwMDA3NTBmNGM4L3ZpZXdzL2ltZ28=/$value HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.17763; en-US) PowerShell/5.1.17763.1007 Invoke-MgGraphRequest
SdkVersion: Graph-powershell-1.9.0, Graph-dotnet-1.25.1
FeatureFlag: 00000047
Cache-Control: no-store, no-cache
Authorization: Bearer 
Accept-Encoding: gzip
Host: graph.microsoft.us
Connection: Keep-Alive

HTTP/1.1 403 Forbidden
Date: Fri, 17 Dec 2021 06:32:38 GMT
Content-Type: application/json
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 5ce94230-573c-4305-9df2-2d616cf05ab0
client-request-id: 5ce94230-573c-4305-9df2-2d616cf05ab0
Content-Length: 207

{"error":{"code":"Forbidden","message":"Forbidden","innerError":{"date":"2021-12-17T06:32:39","request-id":"5ce94230-573c-4305-9df2-2d616cf05ab0","client-request-id":"5ce94230-573c-4305-9df2-2d616cf05ab0"}}}

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f67cabe4-bade-9a07-90ec-15adaeab3de2
* Version Independent ID: dfbbddfe-f113-1ae1-9d21-77ab976ddc20
* Content: [Get chatMessageHostedContent - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
This specific API is not supported in application context in GCCHigh and DOD environment yet.

**Comment by longnlp** [comment]
> This specific API is not supported in application context in GCCHigh and DOD environment yet.

@ram
Thank you for the information, may I know when this is supported?

**Comment by RamjotSingh** [comment]
We are working on it. No set date yet though.
