### ISSUE TITLE
Assign to all devices not working as expected as per the documentation, it works after small tweak which is missing in the documentation

### ISSUE THREAD

**Issue by Dipxssss** [microsoftgraph/microsoft-graph-docs#15359]
POST https://graph.microsoft.com/v1.0/deviceAppManagement/mobileAppConfigurations/Id/assign
with request Body
{
"@odata.type": "#microsoft.graph.managedDeviceMobileAppConfigurationAssignment",
"target": {
"@odata.type": "#microsoft.graph.allDevicesAssignmentTarget"
}
}

Gives out error :
{
"error": {
"code": "No method match route template",
"message": "No OData route exists that match template ~/singleton/navigation/key/action with http verb POST for request /AppLifecycle_2112/StatelessAppMetadataFEService/deviceAppManagement/mobileAppConfigurations('11a3be99-05be-4495-b293-3707e7e2a19c')/microsoft.management.services.api.assign.",
"innerError": {
"date": "2021-12-20T19:37:09",
"request-id": "fe13df75-2b93-4710-a7ba-e5f4d4cd638b",
"client-request-id": "b980efb1-9d06-bf2f-a8f9-6a404d14c86f"
}
}
}

It works when we do small tweak on POST https://graph.microsoft.com/v1.0/deviceAppManagement/mobileAppConfigurations/<mobile/microsoft.graph.managedDeviceMobileAppConfiguration/assign

with the same request body as above works.

Please validate the below screenshot and please update the documentation accordingly

<img width="441" alt="image" src="https://user-images.githubusercontent.com/30771683/147632179-adcb9531-2fa9-4586-9a3c-eec9b8b14057.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17a2ee21-37ed-1d40-36b6-92598156fc68
* Version Independent ID: 220aac31-4329-142e-1856-81937af7084c
* Content: [assign action - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-apps-manageddevicemobileappconfiguration-assign?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-apps-manageddevicemobileappconfiguration-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-apps-manageddevicemobileappconfiguration-assign.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
You're correct with the updated POST request body.  I've filed a bug with our team to update the docs accordingly.  Thanks!
