### ISSUE TITLE
NextPageRequest contains broken $filter in QueryOptions

### ISSUE THREAD

**Issue by simon-baer** [microsoftgraph/microsoft-graph-docs#15369]
I want to query for all active users in C#. The following code throws an exception when there are more than 100 users and the second page is requested:

```c#
var request = graphServiceClient.Users.Request().Filter("accountEnabled eq true").Select(x => new { x.DisplayName, x.Mail, x.BusinessPhones });
var users = await request.GetAsync();
while (request != null)
{
    var users = await request.GetAsync();
    request = users.NextPageRequest;
}
```

It turned out that NextPageRequest contains a QueryOptions with the name "?$filter". This is wrong and should be "$filter" without the leading "?". Actually always the first entry in QueryOptions contains a leading "?".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/paging)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @simon-baer for raising this issue. I'm looping in our C# SDK expert who's better placed to help you resolve this.
@andrueastman, could you look into and help resolve this issue, please?

**Comment by andrueastman** [comment]
Thanks for raising this @simon-baer,

Are you able to confirm which version of the SDK you are using? I believe a similar [issue ](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/345)was resolved using the [latest update](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/347) of the SDK.

**Comment by simon-baer** [comment]
You are right @andrueastman with the latest version 2.0.7.0 its fixed! Sorry my bad...
