### ISSUE TITLE
Many broken changelog links

### ISSUE THREAD

**Issue by dan-silver** [microsoftgraph/microsoft-graph-docs#1536]
https://developer.microsoft.com/en-us/graph/docs/concepts/changelog

Many of the Intune links are broken:
- Added the assign action on iosMobileAppConfiguration - `assign` links to https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_apps_iosmobileappconfiguration_assign.md

- Added the syncDevice action on managedDevice - `syncDevice` links to https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_devices_manageddevice_syncdevice.md

**Comment by lleonard-msft** [comment]
@dan-silver - These seem to be taken care of.  Please let me know if there are more broken ones.  (I've checked, but may have missed something.)
