### ISSUE TITLE
Use a search instead of filter will result in internal server error

### ISSUE THREAD

**Issue by LockTar** [microsoftgraph/microsoft-graph-docs#15382]
The notes states that you can `filter` the response and that you can use `ODATA` queries. 
Yes I can filter the reponse with in example:
`https://graph.microsoft.com/v1.0/oauth2PermissionGrants?$filter=clientId eq '30305898-87d1-4549-a7d2-26e60b5e7a58'`
But a `filter` ODATA is just a filter on the response... Is a `search` not better?
I tried the following:
`https://graph.microsoft.com/v1.0/oauth2PermissionGrants?$search="clientId:30305898-87d1-4549-a7d2-26e60b5e7a58"`
but then you will get an `Service_InternalServerError`.

```json
{
    "error": {
        "code": "Service_InternalServerError",
        "message": "Encountered an internal server error.",
        "innerError": {
            "date": "2022-01-03T15:43:55",
            "request-id": "1bcd47a1-d269-46cd-ae33-1bdadb9906ef",
            "client-request-id": "1bcd47a1-d269-46cd-ae33-1bdadb9906ef"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367837c5-df05-868a-b28c-d88d80e7b4d1
* Version Independent ID: f4085ea1-8936-f0a4-487c-5d839fb0bf94
* Content: [List oAuth2PermissionGrants (delegated permission grants) - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/oauth2permissiongrant-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/oauth2permissiongrant-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/oauth2permissiongrant-list.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
[Support for `$search` varies](https://docs.microsoft.com/graph/search-query-parameter) across different APIs. In the case of oauth2PermissionGrants, `$search` is not supported, only `$filter` (and only as described in the [oauth2PermissionGrant entity type reference](https://docs.microsoft.com/graph/api/resources/oauth2permissiongrant?view=graph-rest-1.0#properties)).

> But a filter ODATA is just a filter on the response... Is a search not better?

What do you mean by "better"? From the service implementation side (for this API, specifically), the expression used in `$filter` is taken into account during the initial data retrieval from the underlying data store, so a `$search` would not optimize anything.

**Comment by LockTar** [comment]
> [Support for `$search` varies](https://docs.microsoft.com/graph/search-query-parameter) across different APIs. In the case of oauth2PermissionGrants, `$search` is not supported, only `$filter` (and only as described in the [oauth2PermissionGrant entity type reference](https://docs.microsoft.com/graph/api/resources/oauth2permissiongrant?view=graph-rest-1.0#properties)). 

I think I missed that line in the docs then. Thanks for the referral. 
Still, a 500 internal server is still not pretty... A 400 would be a better response if you would pass a search parameter. 

> 
> What do you mean by "better"? From the service implementation side (for this API, specifically), the expression used in `$filter` is taken into account during the initial data retrieval from the underlying data store, so a `$search` would not optimize anything.

Well that was actually my question but I think I was unclear. So a 'filter' is actually a filter on the query to the data store and not a filter on the response for in example page 1. I mean, if you would hit an api with 1000 records as result you would get 10 pages. I thought the filter was a filter on the response for in example page 3. And I thought a search was then better.

But then my query is already fine. I already used a filter in my code. Thanks!

**Comment by FaithOmbongi** [comment]
Thank you @psignoret. Hi @LockTar, I hope Philippe's response is satisfactory. If not, please feel free to reopen this issue.
