### ISSUE TITLE
Bug in One Drive SharedWithMe Graph API

### ISSUE THREAD

**Issue by avc2120** [microsoftgraph/microsoft-graph-docs#1540]
The SharedWithMe OneDrive API seems to only give me one drive items that have been shared with me in the past 24 hours. After 24 hours, it stops appearing and returns an empty list. I'm using the following API: 
https://graph.microsoft.com/v1.0/users/<user>/drive/sharedWithMe

This works fine as expected on the Explorer but does not work when I try to call the API myself.

**Comment by kdhindsa** [comment]
I am experiencing the same issue as well. Do you mind sharing the exact API call (with secrets/accounts removed)?

**Comment by andresluzu** [comment]
I'm having the same problem using [access without a user](https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service) token. That it is probably the main difference between this kind of token and the one used by the Graph Explorer.

**Comment by lhzw** [comment]
https://graph.microsoft.com/v1.0/users/695b87a9-eab5-4a9d-926e-6fed7af1d2e5/drive/sharedWithMe
or this url:
https://graph.microsoft.com/v1.0/me/drive/sharedWithMe

Got empty result:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": []
}

**Comment by aronbardsley** [comment]
I am experiencing the same problem as described by andresluzu. No results are returned when using app only auth. The graph explorer returns results however. 

Any info on when this can get looked at? Looks like it's been sitting here for a while.

**Comment by willalewis** [comment]
Has there been any progress on this issue? I'm currently relying on the SharePoint API to search for documents shared to users, and would like to switch completely to the Graph API. However, calling sharedWithMe for a drive always returns an empty array when using app credentials.

**Comment by mlafleur** [comment]
Which scopes are you using?

**Comment by aronbardsley** [comment]
All of them. Doesn't make a difference which ones you turn on, the issue still occurs.

**Comment by willalewis** [comment]
Specifically, right now my app has Device.ReadWrite.All, Directory.ReadWrite.All, Files.ReadWrite.All, Group.ReadWrite.All, Sites.ReadWrite.All, and User.ReadWrite.All.

**Comment by lenyt** [comment]
@katahir If that's the case can you update the documentation to remove from Permissions:

Application        Files.Read.All, Files.ReadWrite.All, Sites.Read.All, Sites.ReadWrite.All

in the documentation:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/drive_sharedwithme
