### ISSUE TITLE
OpenExtensions with Todo Tasks documentation wrong?

### ISSUE THREAD

**Issue by panssystem** [microsoftgraph/microsoft-graph-docs#15430]
I'm not sure if this is a bug in the documentation, or in the code itself. I also can't find a place to file a bug against the code, so here you go.

I'm trying to add an OpenExtension to a Todo Task. It appears to work correctly when I do it as documented, returning the entity (and 201 Created) in both the .NET SDK and Graph Explorer, but when I query for it (either using $expand=extensions on the ToDo, or trying to grab the extension directly, it's not there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 536cb18d-55b2-bfcb-420b-6eca61a93f02
* Version Independent ID: b2f15e40-0706-d65e-dfcb-325b2f48727b
* Content: [Create open extension - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/opentypeextension-post-opentypeextension?view=graph-rest-1.0&tabs=http#permissions)
* Content Source: [api-reference/v1.0/api/opentypeextension-post-opentypeextension.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/opentypeextension-post-opentypeextension.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by panssystem** [comment]
See https://docs.microsoft.com/en-us/answers/questions/687323/are-open-extensions-supported-on-todo-tasks.html for where I worked through the issue I'm seeing, and what I've done to try to work around it. COVID got in the way of my testing, but I should be back to it soon.

**Comment by panssystem** [comment]
Ok, another update. I guess what I missed is that you have to explicitly request the open extension by name or id, rather than iterate through all open extensions on a task. Now as I re-read the documentation this seems clear, but initially, it wasn't. So maybe clarify that there is no List Open Extensions option?

**Comment by FaithOmbongi** [comment]
Thank you @panssystem for raising this issue and resolving it. Yes, as per the documentation the [List openTypeExtension](https://docs.microsoft.com/en-us/graph/api/resources/opentypeextension?view=graph-rest-1.0#properties) isn't supported.
