### ISSUE TITLE
The request to add multiple members to a team that results in a partial failure not return object.

### ISSUE THREAD

**Issue by HugoMtzM** [microsoftgraph/microsoft-graph-docs#15433]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e920719-c0fc-a977-f172-2f8b84422e4f
* Version Independent ID: 2a9011b6-fe66-af8d-192c-5109e678faa2
* Content: [conversationMember: add - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/conversationmembers-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @abshar-teams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abshar-teams** [comment]
@HugoMtzM  Can you share client-request-id, timestamp for the failed api calls ? Do you not see 'userId' in the failure response like this:

    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMemberResult",
            "userId": <user-id>
            "error": {
                "code": "NotFound",
                "message": ""
            }
        }
    ]

**Comment by abshar-teams** [comment]
Closing because of lack of response. Please re-activate if you still face the issue.
