### ISSUE TITLE
Limits?

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#15446]
Can you please include information as to any limits with regards to creation/usage of Schema extensions? For example, is there a limit of the number of extensions that can be registered per given "owner" app. Or per tenant? The number of properties a single extension can define? 

Same for usage, is there a limit on the number of schema extensions a given object can "consume"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b7b26c-499c-6b30-96cd-04b6ac80fbc0
* Version Independent ID: 2e8b2a6a-961b-40d6-acf0-a096a3aec9a1
* Content: [Create schemaExtension - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/schemaextension-post-schemaextensions.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by henrymbuguakiarie** [comment]
@dkershaw10 Who can take a look at this? It's over 130days old.

**Comment by FaithOmbongi** [comment]
My apologies, @michevnew, for my delayed acknowledgment. Let me get more information about this and get back to you.

**Comment by dkershaw10** [comment]
Sorry for the delay.
@michevnew Some of this is already documented - like:

- an owning app can have up to 5 schema definitions (we're double checking if this limit has been raised recently)
- an object instance can have up to 100 extension properties from any schema extension definitions - this limit is for directory objects

I'm not aware of any property limits in a schema extension definition (although it's ultimately limited to 100, or you won't be able to use that extension definition when instantiating an extension onto an object instance
There are no limits AFAIK at the tenant level.

I'm following up on these 2 items to see if there are any limits here.

Are there any reasons why your scenarios need larger limits?

**Comment by michevnew** [comment]
@dkershaw10 I was mostly interested in comparing this to Custom security attributes. And for the sake of completeness of the documentation. You can close this, thanks.
