### ISSUE TITLE
Hit 400 Bad Request (Invalid continuation token)

### ISSUE THREAD

**Issue by sunnyspan** [microsoftgraph/microsoft-graph-docs#15479]
Hi, we used to use the "chats/{id}/messages" to list the messages of a chat with skiptoken for pagination.
But in the last few days, we hit occasional error 400 Bad Request (Invalid continuation token) when listing with the returned skiptoken in the first response.

That is, the first page of response is okay but when we try to list the next page with the nextlink provided, it hits the error.
Yesterday (10Jan2022) we hit the problem for all the chats we tried. But today (11Jan2022) it seems okay but then when further trying more chats, it's not totally okay.
* Update on 12Jan2022: the error 400 Bad Request messages becomes "Bad Request" instead of "Invalid continuation token".

After more tests, we found that it happens on group chat while oneOnOne are okay with the skipToken. (Even though some weird things observed and I'll mention it in ). 

However, even though the oneOnOne skipToken is okay, we found a weird behavior in the returned result. That is some of the message is retained on each page of result, different chat might have different number of messages being retained and we cannot find any patterns on what kind of message will be retained. And in the last page, the retained message(s) is also retained and the nextlink is supplied, if we follow this link, we will get the same result with retained message, and the nextlink will be the same as the last page. So it will become endless.

So in summary, we hits two problems with the list Teams Chat messages Graph API recently:
1. Invalid skipToken
2. Messages retain in every page and endless nextlink in the last page.

We wish it is our problem in using of the API but unfortunately still no clue for it. Thanks in advance!

BTW, we did test it with GraphExplorer with delegated permission, Postman with application permission and even in our own program, they all getting the same result...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548a7932-274e-ce6c-aed5-e35206f7894a
* Version Independent ID: 02c653f9-fde9-758e-9bb7-a573f88cbbe8
* Content: [List messages in a chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
The Invalid Continuation Token issue is being fixed. Can you try in 24 hours from now and then come back and let's look into the other issue.

**Comment by sunnyspan** [comment]
> The Invalid Continuation Token issue is being fixed. Can you try in 24 hours from now and then come back and let's look into the other issue.

Thanks! just tried but still getting "Bad Request". Will keep trying and report the result tomorrow.

**Comment by RamjotSingh** [comment]
The fix for `Invalid continuation token` has finished rolling out in public cloud. If you are still hitting issues please share timestamp and client-request-Id header

**Comment by rowenfelt-everlaw** [comment]
I am experiencing the same issue where 1:1 chats seem fine, but skip tokens for group chats sometimes return a `400 Bad request` and sometimes return the correct result.
Originally I thought this issue was with our Microsoft Graph Java SDK usage, but I can reproduce it with `curl`. Here is my demo script:
```
#!/bin/bash
TOKEN="{token-contents}"

curl -H "Authorization: Bearer $TOKEN" "https://graph.microsoft.com/v1.0/chats/19:3300a88fbed249d38e8beb6c32d86a07@thread.v2/messages"

curl -H "Authorization: Bearer $TOKEN" "https://graph.microsoft.com/v1.0/chats/19:3300a88fbed249d38e8beb6c32d86a07@thread.v2/messages?\$skiptoken=U291cm...{omitted skip token contents}"
```
Response from initial request to /chat/{chat-id}/messages:
```
{
   "@odata.context" : "https://graph.microsoft.com/v1.0/$metadata#chats('19%3A3300a88fbed249d38e8beb6c32d86a07%40thread.v2')/messages",
   "@odata.count" : 4,
   "@odata.nextLink" : "https://graph.microsoft.com/v1.0/chats/19:3300a88fbed249d38e8beb6c32d86a07@thread.v2/messages?$skiptoken=U291cm...{omitted skip token contents}",
   "value" : [ 
      {... message contents}
   ]   
}
```
Response from `chats/{chat-id}/messages?\$skiptoken={skiptoken}`:
```
{
   "error" : {
      "code" : "BadRequest",
      "innerError" : {
         "client-request-id" : "ecec426d-95b3-4110-bfb9-1af4a5c00192",
         "date" : "2022-01-13T19:17:34",
         "request-id" : "ecec426d-95b3-4110-bfb9-1af4a5c00192"
      },
      "message" : "Bad Request"
   }
}
```
Make the _exact same request_ with the same skip token a second later and I get a valid response:
```
{
   "@odata.context" : "https://graph.microsoft.com/v1.0/$metadata#chats('19%3A3300a88fbed249d38e8beb6c32d86a07%40thread.v2')/messages",
   "@odata.count" : 0,
   "value" : []
}
```
If I make this request repeatedly, it'll fail some of the time and pass some of the time. There doesn't seem to be any pattern.

From curl's verbose output: the ids of the `400 Bad request` response where:
```
< request-id: ecec426d-95b3-4110-bfb9-1af4a5c00192
< client-request-id: ecec426d-95b3-4110-bfb9-1af4a5c00192
```
And the ids of the valid response where:
```
< request-id: 9dadbce8-60ee-4dd4-a53c-37b2c967cfb3
< client-request-id: 9dadbce8-60ee-4dd4-a53c-37b2c967cfb3
```

**Comment by tfazekas** [comment]
I am experiencing the same when postion`/teams/{team-id}/channels/{channel-id}/messages` however unfortunately it only comes up in production environment. 


Response: 400 Bad request

```
{
  "error": {
    "code": "BadRequest",
    "message": "Bad Request",
    "innerError": {
      "date": "2022-01-17T02:48:35",
      "request-id": "fc30261d-09e6-46e0-86d1-42828f81224e",
      "client-request-id": "fc30261d-09e6-46e0-86d1-42828f81224e"
    }
  }
}
```

**Comment by RamjotSingh** [comment]
The bad request issues while fetching chat messages should have been fixed now.

@tfazekas Your issue is different than the others please start a new thread.

**Comment by RamjotSingh** [comment]
Coming to the original issue @sunnyspan if you are still hitting issues, please share the following

1. A trace for the requests made (you can remove the auth tokens)
2. Same chat opened in Teams client and traversed back. We want to check where the thread breaks and start looping

**Comment by sunnyspan** [comment]
For my original issue, it look ok and stable in the last few days. Thanks a lot for the works and kindly response!
