### ISSUE TITLE
Is this equivalent to Require re-register MFA?

### ISSUE THREAD

**Issue by gabeluci** [microsoftgraph/microsoft-graph-docs#15504]
Is [Delete microsoftAuthenticatorAuthenticationMethod](https://docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete) equivalent to [Require re-register MFA](https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-userdevicesettings#manage-user-authentication-options) in the Azure Portal? If not, is there an equivalent in the Graph API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0480dbfe-60d2-a773-6807-fe88b9112d8c
* Version Independent ID: b74cff4d-145a-1d73-9000-cdcda031b001
* Content: [Delete microsoftAuthenticatorAuthenticationMethod - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @gabeluci for raising this issue. You configure the **Require re-register MFA** setting in Microsoft Graph through setting the [forceChangePasswordNextSignInWithMfa](https://docs.microsoft.com/en-us/graph/api/resources/passwordprofile?view=graph-rest-1.0) property of the **passwordProfile** property on the [user](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) API to `true`.

**Comment by gabeluci** [comment]
The documentation for `forceChangePasswordNextSignInWithMfa` says:

> If true, at next sign-in, the user must perform a multi-factor authentication (MFA) before being forced to change their password. The behavior is identical to forceChangePasswordNextSignIn except that the user is required to first perform a multi-factor authentication before password change.

That doesn't mention anything about requiring a re-register of MFA. It's only about forcing a password change after using an existing MFA method.

Is that documentation wrong then?

**Comment by FaithOmbongi** [comment]
Hi @gabeluci, reopening to allow me to seek confirmation and get back to you.

**Comment by tamahau30494** [comment]
I too have been waiting 2 years for this to be supported. Any updates you can provide are appreciated @FaithOmbongi !

**Comment by FaithOmbongi** [comment]
Hi @gabeluci, @tamahau30494, unfortunately, this feature is currently not available in Microsoft Graph. But it's in the backlog.  Currently, to **Require re-register MFA** programmatically, use the [Set-MsolUser](https://docs.microsoft.com/en-us/powershell/module/msonline/set-msoluser?view=azureadps-1.0) MSOL PowerShell module.

**Prerequisites: Install the MSOL PowerShell modules and start an authenticated PowerShell session**

```PowerShell
Install-Module -Name MSOnline
Connect-MsolService
```

Step 1: Reset the Strong authentication methods for the user, therefore, causing Azure AD to require them to re-register for MFA

```Powershell
Set-MsolUser -UserPrincipalName AllanD@M365x010717.OnMicrosoft.com -StrongAuthenticationMethods @()
````

When the user logs in to start a new session, after they enter their password, they'll get the following prompt in the browser. They can proceed to register new MFA methods.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/14026935/149568514-d43ba156-0fe8-49b9-8103-da2161ff3648.png">


Kindly test this and revert.

**Comment by gabeluci** [comment]
@FaithOmbongi Yes, that's the method we currently use. Thank you for confirming.

**Comment by FaithOmbongi** [comment]
Hi @gabeluci, thanks for the confirmation. Unfortunately, I'm not able to share an ETA for the Microsoft Graph equivalent. But I would recommend filing a [feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) so other customers can amplify your voice. Once you file the request, you can post the link here so others can easily find it and upvote it.

**Comment by gabeluci** [comment]
Done: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/microsoft-graph-add-support-for-quot-require-re-register-mfa/idi-p/3062110
