### ISSUE TITLE
Feature and featureGroup enumerations

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#15500]
Can we get a list of possible values for feature and featureGroup (enums?), ideally one that will be kept up to date going forward? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a83191f3-4706-5570-2ad9-b2a64f2d8cb6
* Version Independent ID: 7ac0a0bf-3299-998d-4758-ec7821d31f69
* Content: [serviceHealthIssue resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/servicehealthissue.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/servicehealthissue.md)
* Product: **service-communications**
* Technology: **microsoft-graph**
* GitHub Login: @payiAzure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kristitorg** [comment]
@michevnew Thank you for the feedback. This is not currently supported but is something we will consider adding in the future. Please add your support for this feature request on Tech Community page here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-access-to-service-features-in-service-communications-api/idi-p/2738993

**Comment by michevnew** [comment]
Thank you Kristi, I understand that the "feature status" is not currently supported, however information about affected features/featureGroup is still returned as part of incident's data, so it will be nice to have the list of possible values available. I will vote up the feature request as well, thanks for the link.
