### ISSUE TITLE
Intune Graph API URLs should have version v1.0

### ISSUE THREAD

**Issue by nuthatcher** [microsoftgraph/microsoft-graph-docs#15522]
Intune Graph URLs are missing the version. For example, these won't work:
https://graph.microsoft.com/users/{user}/ownedDevices 
https://graph.microsoft.com/deviceAppManagement/mobileApps  
https://graph.microsoft.com/deviceAppManagement/mobileApps/{id}/deviceStatuses/

It should be with "v1.0":
https://graph.microsoft.com/v1.0/deviceAppManagement/mobileApps
https://graph.microsoft.com/v1.0/deviceAppManagement/mobileApps  
https://graph.microsoft.com/v1.0/deviceAppManagement/mobileApps/{id}/deviceStatuses/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36b8419-5890-1e7c-f748-9f71cad21fbf
* Version Independent ID: e6194e1e-a9ca-6acb-1f46-0e3cc1392a02
* Content: [Working with Intune in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-graph-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/intune-graph-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/intune-graph-overview.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback!
I've put in an update to correct the URLs.
