### ISSUE TITLE
Page display issues in Edge

### ISSUE THREAD

**Issue by IN-jwink** [microsoftgraph/microsoft-graph-docs#15559]
[Enter feedback here]

Page cannot be displayed on a 1280x1024 screen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b855b67-0f09-bf85-782f-7fb68a24ee7c
* Version Independent ID: 500e299b-6f0f-f0b6-f89b-ae60f77f9332
* Content: [device resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/device.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @SanDeo-MSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by IN-jwink** [comment]
I use a secondary monitor (Dell 19” with max res 1280x2014 for things like manuals/docs/instructions while I am working on my main monitor.  I am forever in Powershell manual pages and have never had an issue.  But on that page, at 100% zoom the page went squirrely and the last column in the tables vanished because other columns have very large text strings stretching them and eating space.  Not sure how to fix that or if it’s really considered a problem but it was the first page I could’t just view on my secondary monitor.

**Comment by FaithOmbongi** [comment]
> But on that page, at 100% zoom the page went squirrely and the last column in the tables vanished because other columns have very large text strings stretching them and eating space.

Spot on. Some details such as property names may be long and cause a horizontal scroll bar to be "activated" for the table. Unfortunately, this isn't a docs issue nor a Markdown issue but I'll chat with our accessibility experts if anything can be done to help with improving rendering for such.
