### ISSUE TITLE
Sized Photo returned with background

### ISSUE THREAD

**Issue by skuzymkiv** [microsoftgraph/microsoft-graph-docs#15562]
There are annoying difference between fetching sized and default photos.
Reproducible on **v1** and **beta**
Actual: 
https://graph.microsoft.com/v1.0/users/{userId}/photos/{size}/$value **returns photo with background**
https://graph.microsoft.com/v1.0/users/{userId}/photo/$value  **no background**

Expected: 

https://graph.microsoft.com/v1.0/users/{userId}/photos/{size}/$value **no background**
https://graph.microsoft.com/v1.0/users/{userId}/photo/$value  **no background**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get profilePhoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/profilephoto-get.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nabinbaral01** [comment]
- [ ] Ya@kevinbellinger

**Comment by yaw-innovate** [comment]
Hi, acknowledged. The team is looking into this. By background do you mean there is a background picture shown in the photo?

**Comment by yaw-innovate** [comment]
@skuzymkiv can you please clarify what you mean by "returns photo with background" ? Is there an image/layer you see as part of the returned image? Is this an enterprise or a consumer account? - though that shouldn't matter.

**Comment by skuzymkiv** [comment]
@yaw-innovate I mean background around image circle

**Comment by yaw-innovate** [comment]
@skuzymkiv thanks for confirming. This is not reproducible at our end. Are you able to share a screenshot, if possible? Thanks.

**Comment by yaw-innovate** [comment]
Feel free to re-open if this issue is still occurring.
