### ISSUE TITLE
API to get the Team Device summary C#

### ISSUE THREAD

**Issue by That-Zebra** [microsoftgraph/microsoft-graph-docs#15586]
Hi guys, 
I wanted to write an application/PS script  that will list the device summary of teams.  What is the Endpoint that can give us the device summary . https://admin.teams.microsoft.com/devices/ipphones
Want to export that data for reporting purpose, are these IP Phone available via Graph API. Any pointer is appreciated. 
Regards
Sunil Prabha
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5463d788-8e29-ca0a-5490-93506ff1ec80
* Version Independent ID: 1e7ca228-0b9f-beb1-d61f-7f1fdff50008
* Content: [Use the Microsoft Graph API to work with Microsoft Teams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0&source=docs)
* Content Source: [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/teams-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
@That-Zebra - You can follow this [doc](https://docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-1.0&tabs=http) which explains how to get list of device objects registered in the organization.

`GET https://graph.microsoft.com/v1.0/devices`
<html>
<body>


Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | Device.Read.All, Directory.ReadWrite.All, Directory.AccessAsUser.All
Delegated (personal Microsoft account) | Not supported.
Application | Device.Read.All, Device.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All


</body>
</html>

**Comment by That-Zebra** [comment]
Hi Prasad,
I see many devices in Graph or In AD devices section.  I wanted to get details on the Teams summary like phone number , assigned to and other information, how many devices/phones have been issues and want to take a backup of the data.
user phone number assignments back up if possible, via power shell script or rest api.
https://admin.teams.microsoft.com/devices/ipphones
Regards
Sunil Prabha
404 542 5536
________________________________

**Comment by Prasad-MSFT** [comment]
@That-Zebra - There doesn't seem to be any specific API or PS Script to get those data. 
Thanks!

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
