### ISSUE TITLE
Posting team chat messages fail silently when a large hosted content image is attached in C#

### ISSUE THREAD

**Issue by BenRSorce** [microsoftgraph/microsoft-graph-docs#15594]
Using Example 5 of sending inline images along with the message, I've found that trying to send a message with a larger image (e.g. 9MB) in a channel throws no errors but the message never arrives in the team channel. However running it again but using a smaller image allows the image to post successfully. 

I haven't been able to find any documentation that seems to indicate what the limit for the hosted content size limit is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f96d4903-13f7-c489-82b2-ce79d8b77540
* Version Independent ID: 7bf7c3d2-7693-7d24-e9c0-6f0c51cb1eaa
* Content: [Send chatMessage in a channel or a chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Graph has a limit of 4 MB on all calls.
