### ISSUE TITLE
Joseph James Breaux

### ISSUE THREAD

**Issue by jbreaux220** [microsoftgraph/microsoft-graph-docs#15601]
[{   "id": "string (identifier)" }]() 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df87225-c5ec-2ed8-c906-585255a5bd9b
* Version Independent ID: 7da1c157-8b44-515e-49ac-c29bc01d0577
* Content: [entity resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/entity?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/entity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/entity.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
A good day to you @jbreaux220. I'll close this issue because it doesn't have any context.
