### ISSUE TITLE
Get Hosted Content Value with Application Permission is forbidden in G3 GCC

### ISSUE THREAD

**Issue by FixBugsFor** [microsoftgraph/microsoft-graph-docs#15617]
The same problem as
https://github.com/microsoftgraph/microsoft-graph-docs/issues/15356

But it happens on G3 GCC, is this expected ? or what else is restricted to ? how do we check it ?

Thanks a lot!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f67cabe4-bade-9a07-90ec-15adaeab3de2
* Version Independent ID: dfbbddfe-f113-1ae1-9d21-77ab976ddc20
* Content: [Get chatMessageHostedContent - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
We will check on it and get back to you.

**Comment by Meghana-MSFT** [comment]
Could you please share client-Request-Id and timestamp for us to look at? Please make sure you have removed any PII.

**Comment by Meghana-MSFT** [comment]
Thank you, we will check and get back to you.

**Comment by Meghana-MSFT** [comment]
These logs are too old. We only have logs for past 28 days. Could you please help by sharing the client-Request-Id and timestamps in the past 28 days only?

**Comment by Meghana-MSFT** [comment]
@FixBugsFor  - Could you please share the recent IDs?

**Comment by FixBugsFor** [comment]
We are trying to find recent failed 403 client-request-id for hostedcontent downloading; 
We will keep you informed soon as we have it; thanks;

**Comment by ChetanSharma-msft** [comment]
Hello @FixBugsFor - Hope you are doing well!!
Please confirm if it is already fixed or need any further help here.

**Comment by ChetanSharma-msft** [comment]
Hello @FixBugsFor - Hope you are doing well!!
Could you please share the client-request-id for your failed error 403, so that we can further investigate on it?
