### ISSUE TITLE
GetDownloadUrl() method is missing

### ISSUE THREAD

**Issue by johnholliday** [microsoftgraph/microsoft-graph-docs#15618]
[Enter feedback here]

The API is missing the GetDownloadUrl() method.
```csharp
var url = await service.Client.Compliance.Ediscovery.Cases[theCase.Id]
   .Operations[theExport.Id].GetDownloadUrl().Request().GetAsync();
```
The above code produces an exception:
```csharp
CS1061: 'ICaseOperationRequestBuilder' does not contain a definition for 'GetDownloadUrl' and no accessible extension method 'GetDownloadUrl' accepting a first argument of type 'ICaseOperationRequestBuilder' could be found (are you missing a using directive or an assembly reference?)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ef0c894-22f4-504e-87cd-0ce8d3618ec6
* Version Independent ID: b58b0580-c500-02ba-75e1-8e4d8eb5e2f0
* Content: [caseExportOperation: getDownloadUrl - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/ediscovery-caseexportoperation-getdownloadurl?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/ediscovery-caseexportoperation-getdownloadurl.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/ediscovery-caseexportoperation-getdownloadurl.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @mahage-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi @johnholliday .
This is related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/338
We are working on fixing it in the SDK. You can see a workaround in the comments.

**Comment by lramosvea** [comment]
@maisarissi should we keep this issue open here or just keep the one you have referenced in your previous comment?

**Comment by maisarissi** [comment]
Hi @lramosvea . I believe we should keep this one open as you do have a doc issue.
We can use this issue to track the fix in the docs side. Once we have the next .NET SDK version out that will fix the issue in the SDK side, we can validate and then close this.

**Comment by maisarissi** [comment]
Adding @SeunginLyu (new eDiscovery PM) for visibility.

**Comment by lramosvea** [comment]
@maisarissi any update on this?

**Comment by lramosvea** [comment]
Closing as snippet seems to be updated. Please feel free to reopen otherwise.
