### ISSUE TITLE
Can you add details how to read user attribute values in Azure AD B2C?

### ISSUE THREAD

**Issue by SDFVasantHorapeti** [microsoftgraph/microsoft-graph-docs#15642]
I am looking for article, how to read custom attribute value through Graph API. Could you please update the article with those information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @SDFVasantHorapeti for raising this issue. The custom security attributes API is currently only in beta. Please see [Example 4 in the Get user article: Get the custom security attribute assignments of the specified user](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&tabs=http#example-4-get-the-custom-security-attribute-assignments-of-the-specified-user).

More info about custom security attributes and supported methods can be found here: https://docs.microsoft.com/en-us/graph/api/resources/custom-security-attributes-overview?view=graph-rest-beta

**Comment by SDFVasantHorapeti** [comment]
@FaithOmbongi . Thanks for the quick reply. I believe Custom security attribute is different then Custom User Attribute. I am referring to Custom attribute added under User Attribute section. Can you help how to read an custom added attribute under User Attribute section?

![image](https://user-images.githubusercontent.com/42273499/151149287-153466cf-3992-46b9-9e01-cc91be9e97a7.png)

**Comment by FaithOmbongi** [comment]
@SDFVasantHorapeti-thanks for the clarification. In Microsoft Graph, these settings are not in the /users API but are directory-wide restrictions. Let me confirm the respective Microsoft Graph API and get back to you.

**Comment by FaithOmbongi** [comment]
Sorry for the back and forth @SDFVasantHorapeti, but this is now clearer. The **User attributes** feature on the Azure portal (Azure AD B2C tenant view) is the **user flow attributes** API in Microsoft Graph. (If you don't mind, I've edited the title of your issue.)

**Your initial Q:**

> I am looking for article, how to read custom attribute value through Graph API. Could you please update the article with those information?

User flow attributes are not attributes on the user object (retrieved by the **/users** API), rather on B2C user flows. Please see the [List identityUserFlowAttribute](https://docs.microsoft.com/en-us/graph/api/identityuserflowattribute-list?view=graph-rest-beta&tabs=http) method for guidance/examples on how to retrieve all (built-in and custom) user flow attributes.

For more information about the **user flow attributes API**, supported methods and examples, please see the following links:
- To manage user flow attributes: [identityUserFlowAttribute resource type](https://docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta).
- To manage assignments of user flow attributes to a particular user flow, see [identityUserFlowAttributeAssignment resource type](https://docs.microsoft.com/en-us/graph/api/resources/identityuserflowattributeassignment?view=graph-rest-beta)

I hope this now provides the right answer. I'll also raise a PR in Azure AD B2C docs to reference the appropriate API and address this gap.

**Comment by SDFVasantHorapeti** [comment]
Hi @FaithOmbongi .. Well, this documentation will give details how to retrieve list of custom attribution created, their id, name, display name etc. I am not looking for that.

I am looking for details how to update these values for each user, let's say, we have a custom attribute added ( extension_d09380e2b4c6429a203fb816a04a7ad_InternalOrgReferenceNumber) and we have user created - John Smith. I would like to get value of this custom attribute - extension_d09380e2b4c6429a203fb816a04a7ad_InternalOrgReferenceNumber through Graph API for user John Smith.  Is there any documentation for the same?
