### ISSUE TITLE
How to update user attributes in Azure AD B2C

### ISSUE THREAD

**Issue by SDFVasantHorapeti** [microsoftgraph/microsoft-graph-docs#15643]
Could you please update this page with details on how to update custom added attribute(extension_newfield) for an user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @SDFVasantHorapeti for raising this issue. The custom security attributes API is currently only in beta. Please see [Example 4 in the Update user article: Assign a custom security attribute with a string value to a user](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&tabs=http#example-4-assign-a-custom-security-attribute-with-a-string-value-to-a-user).

More info about custom security attributes and supported methods can be found here:
- [Overview of custom security attributes using the Microsoft Graph API (Preview)](https://docs.microsoft.com/en-us/graph/api/resources/custom-security-attributes-overview?view=graph-rest-beta).
- [How-to: Manage custom security attributes](https://docs.microsoft.com/en-us/graph/custom-security-attributes-examples)

**Comment by SDFVasantHorapeti** [comment]
@FaithOmbongi . Thanks for the quick response. I am looking to update custom user attribute(Not custom security attribute). Could you please help how do we update custom attribute created through the following screen through Graph API 

![image](https://user-images.githubusercontent.com/42273499/151156708-bc5cc1a6-2e2a-49e6-a915-c9a60ff9555d.png)

**Comment by FaithOmbongi** [comment]
Hi @SDFVasantHorapeti—the "user attributes" (mine shows **User settings**?) aren't managed through the /user API. Seems like there might have been a recent UI change from **User attributes** => **User settings**. Could you confirm that this is the same view that you have for **User settings**?

<img width="929" alt="image" src="https://user-images.githubusercontent.com/14026935/151157896-73e68460-43fe-4e04-85dd-52be99d15319.png">

**Comment by SDFVasantHorapeti** [comment]
Hi @FaithOmbongi .. I am referring to User Attributes(Please see the screen below) on AD B2C tenant.  I am trying make use of Graph API call to read/write users created on AD B2C 

![image](https://user-images.githubusercontent.com/42273499/151159585-af9cc973-8765-4a3c-8690-69fd7abb79a2.png)

**Comment by FaithOmbongi** [comment]
Sorry for the back and forth @SDFVasantHorapeti, but this is now clearer. The **User attributes** feature on the Azure portal (Azure AD B2C tenant view) is the **user flow attributes** API in Microsoft Graph. (If you don't mind, I've edited the title of your issue)

**Your initial Q:**

> Could you please update this page with details on how to update custom added attribute(extension_newfield) for an user?

User flow attributes are not attributes on the user object (retrieved by the **/users** API), rather on B2C user flows. Please see the [Update identityUserFlowAttribute](https://docs.microsoft.com/en-us/graph/api/identityuserflowattribute-update?view=graph-rest-beta&tabs=http) method for guidance/examples on how to update custom user flow attributes.

For more information about the **user flow attributes API**, supported methods and examples, please see the following links:
- To manage user flow attributes, see [identityUserFlowAttribute resource type](https://docs.microsoft.com/en-us/graph/api/resources/identityuserflowattribute?view=graph-rest-beta).
- To manage assignments of user flow attributes to a particular user flow, see [identityUserFlowAttributeAssignment resource type](https://docs.microsoft.com/en-us/graph/api/resources/identityuserflowattributeassignment?view=graph-rest-beta)

I hope this now provides the right answer. I'll also raise a PR in Azure AD B2C docs to reference the appropriate API and address this gap.
