### ISSUE TITLE
ChatMessage in a channel is not updated after delete

### ISSUE THREAD

**Issue by RajithaE-jan** [microsoftgraph/microsoft-graph-docs#15661]
I could see the message details even after it was deleted from the team's client app. Even after a few hours still, I can see that deleted message which returns and there is no update about deletedDateTime. Can I know the reason why **Get message in a channel**
the response does not return updated values after deleting the messages?
Below I have attached a response to deleted message

API - GET /teams/{team-id}/channels/{channel-id}/messages/{message-id}

Response 
`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('335c19c8-d05d-4e81-82a6-935edb21b018')/channels('19%3AUxhFpUwBwsqyJNbWuqNU0ikfqyfD4HEITkKOcvu8Z981%40thread.tacv2')/messages/$entity",
    "id": "1643191083394",
    "replyToId": null,
    "etag": "1643191185034",
    "messageType": "message",
    "createdDateTime": "2022-01-26T09:58:03.394Z",
    "lastModifiedDateTime": "2022-01-26T09:59:45.034Z",
    "lastEditedDateTime": "2022-01-26T09:59:44.9Z",
    "deletedDateTime": null,
    "subject": null,
    "summary": null,
    "chatId": null,
    "importance": "normal",
    "locale": "en-us",
    "webUrl": "https://teams.microsoft.com/l/message/19%3AUxhFpUwBwsqyJNbWuqNU0ikfqyfD4HEITkKOcvu8Z981%40thread.tacv2/1643191083394?groupId=335c19c8-d05d-4e81-82a6-935edb21b018&tenantId=51aee0f2-088d-4d62-aa6b-e8bc57757c49&createdTime=1643191083394&parentMessageId=1643191083394",
    "policyViolation": null,
    "eventDetail": null,
    "from": {
        "application": null,
        "device": null,
        "user": {
            "id": "2591b2f6-f709-4752-854f-75d82229a5a3",
            "displayName": "青山 二郎",
            "userIdentityType": "aadUser"
        }
    },
    "body": {
        "contentType": "text",
        "content": "12345"
    },
    "channelIdentity": {
        "teamId": "335c19c8-d05d-4e81-82a6-935edb21b018",
        "channelId": "19:UxhFpUwBwsqyJNbWuqNU0ikfqyfD4HEITkKOcvu8Z981@thread.tacv2"
    },
    "attachments": [],
    "mentions": [],
    "reactions": []
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c6947-060a-84a7-6bda-d911789467f5
* Version Independent ID: e544b432-1b2a-dbff-8c05-57118a223d1b
* Content: [Get chatMessage in a channel or chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
I am not seeing this repro. The messages are immediately returning 404. Can you repro and collect these 2 bits of info?

1. Before deleting click the ... and copy the link to message
2. For the GET call post delete, record client-request-Id response header and send it to us

**Comment by RajithaE-jan** [comment]
Hi @RamjotSingh 
Thank you very much. Below I have attached the required info.

**Copy the link to message** - https://teams.microsoft.com/l/message/19:UxhFpUwBwsqyJNbWuqNU0ikfqyfD4HEITkKOcvu8Z981@thread.tacv2/1643332197738?tenantId=51aee0f2-088d-4d62-aa6b-e8bc57757c49&groupId=335c19c8-d05d-4e81-82a6-935edb21b018&parentMessageId=1643332197738&teamName=Rajitha%20test&channelName=General&createdTime=1643332197738

**client-request-Id** - b3fdeb37-f526-4fcb-982b-b41503bd31c1

**response header** - 

Transfer-Encoding: chunked
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8
Content-Encoding: gzip
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: b3fdeb37-f526-4fcb-982b-b41503bd31c1
client-request-id: b3fdeb37-f526-4fcb-982b-b41503bd31c1
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Japan East","Slice":"E","Ring":"2","ScaleUnit":"003","RoleInstance":"TYO1EPF00000B1E"}}
OData-Version: 4.0
Date: Fri, 28 Jan 2022 01:14:44 GMT

**Comment by RamjotSingh** [comment]
Can you check if you are still able to get the message through Graph or not? Just trying to see if there is delay or some other issue

**Comment by RajithaE-jan** [comment]
Hi @RamjotSingh 

Now I got 404 as a response. Seems like a delay.

`{
    "error": {
        "code": "NotFound",
        "message": "Not Found",
        "innerError": {
            "date": "2022-01-28T06:47:10",
            "request-id": "0c141c75-b76b-4e01-911b-f0f555ef6ca7",
            "client-request-id": "0c141c75-b76b-4e01-911b-f0f555ef6ca7"
        }
    }
}`

**Comment by RajithaE-jan** [comment]
HI @RamjotSingh 
Any update about the above-mentioned delay?

**Comment by RamjotSingh** [comment]
Yep we checked. It took about 7 seconds post deletion for change to be reflected. So immediate fetching might work but in few seconds system should get back in synced state.

**Comment by RajithaE-jan** [comment]
@RamjotSingh 
here I have attached a video proof that you can even after 1-minute responses did not update. I'm not sure what is the actual reason for that
[https://drive.google.com/file/d/1jcT_7_-Pysy64IQbXJhFntpNRDOJdg2J/view?usp=sharing](url)

**Comment by RamjotSingh** [comment]
Can you share the details I asked for above for one which is taking super long? 1 min example would be great.

**Comment by RajithaE-jan** [comment]
@RamjotSingh Thank you very much. Now message responses are updating.
