### ISSUE TITLE
Send Notification to mutiple users

### ISSUE THREAD

**Issue by Arpita1906** [microsoftgraph/microsoft-graph-docs#15666]
Hi,
Is there any way to send activity notification to multiple users together in a single Graph API call?  This Graph API has just one user in the URL. We have a use case to send activity notification for more than 10000 users together. What is the right way to do that ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9948c753-b761-228d-4915-9c26b47dd6a3
* Version Independent ID: 5b4f132c-3409-885d-9a1a-848bcd7c3c7c
* Content: [userTeamwork: sendActivityNotification - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/userteamwork-sendactivitynotification.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @eddie-lee-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Arpita1906** [comment]
Hi @eddie-lee-msft  Please let me know if there is any update on this ?

**Comment by eddie-lee-msft** [comment]
There is no way right now to specify more than one user in a payload.

However, it is possible to send notifications to:
- all users in a chat (https://docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&tabs=http#example-5-notify-the-chat-members-about-a-task-created-in-a-chat)
- all users in a team (https://docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&tabs=http#example-5-notify-the-team-members-about-pending-finance-approval-requests), or 
- all users in a channel (https://docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&tabs=http#example-6-notify-the-channel-members-about-pending-finance-approval-requests)

Above 3 are available in beta.

**Comment by lramosvea** [comment]
Closing since the question seems to be answered already. Please feel free to reopen otherwise.
