### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by barrct** [microsoftgraph/microsoft-graph-docs#15688]
The calls fail as they are defined in the documents.
If the exact process is used or the code example is copied and used, there is a "Microsoft.Fast.Profile.Core.Exception.ProfileNotFoundException" even though the call right before that is querying the profile information works perfectly fine and returns all of the related information.
Either the API doesn't work at all or the documentation is completely wrong.
Looks like it was updated just a few days ago, "01/06/2022", but it is unuseable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get profilePhoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/profilephoto-get.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aymather** [comment]
@barrct are sure you're retrieving an image from an account that has a profile picture set? I ran into the same issue, then I set a profile picture and it no longer throws that error.
