### ISSUE TITLE
Active Sync vs ActiveSync

### ISSUE THREAD

**Issue by Philbbailey** [microsoftgraph/microsoft-graph-docs#15698]
[Enter feedback here]
Please correct the spelling of "Active Sync" to "ActiveSync". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61cf8069-b779-ea2a-c02a-c8efd2e18019
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/signin.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Philbbailey for flagging this. I've raised a PR to fix the reference.
