### ISSUE TITLE
Broken link for throttling details

### ISSUE THREAD

**Issue by Snowrries** [microsoftgraph/microsoft-graph-docs#15728]
In section: https://docs.microsoft.com/en-us/graph/known-issues#batch-size-is-limited

Broken link: https://docs.microsoft.com/en-us/graph/concepts/throttling.md#throttling-and-batching
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab98f77-bf6f-4ce6-c189-dec2444a1bac
* Version Independent ID: ec5464a8-4def-9074-6e50-0b737b41b631
* Content: [Known issues with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/known-issues#batch-size-is-limited)
* Content Source: [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/known-issues.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Hi @FaithOmbongi, is this something you can help with? Thanks!

**Comment by FaithOmbongi** [comment]
Thank you @Snowrries, @lramosvea - I've raised a PR to resolve this. Closing this issue.
