### ISSUE TITLE
Unable to update multiple properties on a user with a single request

### ISSUE THREAD

**Issue by MyFavoriteProject** [microsoftgraph/microsoft-graph-docs#15735]
I asked my question here, I will be grateful for any answer
https://stackoverflow.com/questions/70969770/unable-to-update-multiple-properties-on-a-user-with-a-single-request

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MyFavoriteProject** [comment]
Hi)
Perhaps you missed my question, or this format of questions does not suit you. Therefore, I will ask it again. In Microsoft Graph Explorer, if you make such a request, it will throw an error:
`https://graph.microsoft.com/v1.0/users/{userId}
{
    "aboutMe": "Im dev",
    "givenName": "Someone"
}`

Response:
`Code: BadRequest.
Message: The request is currently not supported on the targeted entity set`

If I divide this request by 2 then the user update succeeds
`https://graph.microsoft.com/v1.0/users/{userId}
{
    "aboutMe": "Im dev",
}`
`https://graph.microsoft.com/v1.0/users/{userId}
{
    "givenName": "Someone"
}`

What I noticed is that if you make a request to update a user with any of the following properties (SharePoint Online): aboutMe, birthday, hireDate, interests, mySite, pastProjects, preferredName, responsibilities, schools, skills. With the remaining properties of the Azure AD user, I will get an error as a result. But if I make a request to update the SharePoint Online properties separately from the Azure AD properties, then the update succeeds.

Is it possible to update these properties SharePoint Online and Azure AD in one request?

**Comment by jpettere** [comment]
Hi @MyFavoriteProject. I saw you got a response on your stackoverflow post. It nailed the reason why these properties can't be updated in a single request. AAD and SPO are two different services and we're unable to split a request to two separate directories. Hence, they must be updated separately.
