### ISSUE TITLE
Application Permission "ExternalConnection.ReadWrite.OwnedBy" Used But Endpoint Returns 401

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/microsoft-graph-docs#15737]
Is Documentation lacking in required permissions/authorizations or why is endpoint returning 401 despite using an application that has the `ExternalConnection.ReadWrite.OwnedBy` permission?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4058614-2399-d5a6-ea18-1a66fdbbe604
* Version Independent ID: 8e85a0e4-91a9-0282-4928-4c51df4a14ed
* Content: [Get externalConnection - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/externalconnectors-externalconnection-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/externalconnectors-externalconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/externalconnectors-externalconnection-get.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @mecampos
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fey101** [comment]
Resolved. Documented permission works on it's own.

**Comment by fey101** [comment]
The problem is actually that it seems the test passed because of one or all of the added permissions below and so the permission `ExternalConnection.ReadWrite.OwnedBy` on it's own as documented on the published docs was not returning expected result. 
ExternalItem.Read.All
ExternalConnection.ReadWrite.All
ExternalConnection.Read.All

Meaning, the correct permission needs to be updated in the doc.

**Comment by emzho** [comment]
We typically return 403 Forbidden HTTP code for incorrect permissions; 401 Unauthorized seems to mean that the token itself had the wrong audience or was otherwise formatted incorrectly. ExternalConnection.ReadWrite.OwnedBy is a valid permission on its own for GET externalConnection. Please let us know if you are still facing this issue.
