### ISSUE TITLE
App with application permissions can update some properties

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#15736]
According to the note in the documentation

> The following properties cannot be updated by an app with only application permissions: aboutMe, birthday, employeeHireDate, interests, mySite, pastProjects, preferredName, responsibilities, schools, and skills.

The real behavior is that those properties can be updated separately but it's not possible to update more than one properties in one request by an app with only application permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MartinM85** [comment]
Hi @jpettere. Here is the example request that failed.

```
PATCH

{
    "aboutMe": "Hello",
    "givenName": "Martin"
}
```

**Comment by jpettere** [comment]
@MartinM85 as suspected, givenName is an AAD property while aboutMe is a SharePoint property so they can't be updated in the same request. We'll look to add a note about this in our documentation.
