### ISSUE TITLE
Trust Type values correct?

### ISSUE THREAD

**Issue by 0xd13a** [microsoftgraph/microsoft-graph-docs#15740]
In [O365 Management API docs](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#azure-active-directory-schema) the device trust type is listed in this order: "registered","joined","hybrid", whereas in this documentation "registered" and "joined" are in reverse order. Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acdc5e62-2fb1-8a0f-1fd5-6d342bcdf1df
* Version Independent ID: e0cada59-2a7b-cd6d-5a65-4915403c2eaf
* Content: [joinType enum type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-jointype?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-devices-jointype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-devices-jointype.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
The underlying object that's using these properties is different.  In the O365 case, the AAD STS Logon schema points to the /device object, whereas Intune points to the /deviceManagement/managedDevice object.  So, although inconsistent, they each represent their respective values correctly.
