### ISSUE TITLE
`ethernetMacAddress` is always `null` when listing managed devices

### ISSUE THREAD

**Issue by KoltesDigital** [microsoftgraph/microsoft-graph-docs#15741]
Either the MAC address should be available, or it should not appear in the docs. I'd prefer the former.

Note that the field is correctly populated in the Get endpoint.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1691c888-7955-2567-d53d-3a03eae9d9eb
* Version Independent ID: 6fd35314-8882-a049-fbb9-6037d818d100
* Content: [List managedDevices - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-devices-manageddevice-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback.  The way in which we generate docs shows properties for the object, but I've filed a bug to get the description updated to indicate it doesn't get returned in a LIST, only in a GET.
