### ISSUE TITLE
claimsSchema item by groups in claimsMappingPolicy

### ISSUE THREAD

**Issue by jpizarrom** [microsoftgraph/microsoft-graph-docs#15771]
I have a requirement to apply claims by groups

similar to 
- appliesToUserType:allguests 
- appliesToUserType:members,  memberOf:["oid:XXX","oid:YYYY"]

is AppliesToUserType and memberOf supported in a ClaimsMappingPolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a406ca-6bf9-1d1a-b161-750cf718f1fb
* Version Independent ID: 2aaf62db-0157-22ce-57bd-029e02ef8d59
* Content: [claimsMappingPolicy resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/claimsmappingpolicy?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/claimsmappingpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/claimsmappingpolicy.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @paulgarn
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jpizarrom** [comment]
Hi, could you add a sample or explain how to use AppliesToUserType, MemberOf, or maybe add a link where that is documented. Thanks

```
{
    "Source": "user",
    "ExtensionID": "extension_XXXX",
    "SamlClaimType": "XXXX",
    "AppliesToUserType": "allguests"
},
{
    "Source": "user",
    "ExtensionID": "extension_XXXX",
    "SamlClaimType": "XXXX",
    "AppliesToUserType": "members",
    "MemberOf": ["xxx"]
},
```

**Comment by jpizarrom** [comment]
related https://github.com/MicrosoftDocs/azure-docs/issues/88429

**Comment by paulgarn** [comment]
Looks like we're missing this from the docs.  We'll get it added.  Thanks for asking.  
Heres' and example for  MemberOf

```
{
	"ClaimsMappingPolicy": {
		"Version": 1,
		"IncludeBasicClaimSet": "false",
		"ClaimsSchema": [{	
				"value": "Reader",
				"SamlClaimType":"https://contoso.com/claims/adminrole",
				"JwtClaimType": "https://contoso.com/claims/adminrole",
				"MemberOf":["oid:8e6c32c0-d635-4a25-96c1-75c55a2335bc"]
            }]
	}
}

```

and for AppliesToUserType

```
{
	"ClaimsMappingPolicy": {
		"Version": 1,
		"IncludeBasicClaimSet": "false",
		"ClaimsSchema": [{	
				"value": "Reader",
				"SamlClaimType":"https://contoso.com/claims/adminrole",
				"JwtClaimType": "https://contoso.com/claims/adminrole",
				"AppliesToUserType": "AADGuests"
            }]
	}
}
```
Possible values for AppliesToUser type are: 
"Members"  Members of a tenant
"AllGuests"  Any guest user (Note: A guest user is defined as having an AltSecID on the user object - not by the usertype attrbute)
"AADGuests" A guest user homed in another AAD tenant

**Comment by FaithOmbongi** [comment]
Hello @jpizarrom. I hope the answer @paulgarn shared was helpful. Closing this issue for now.
