### ISSUE TITLE
This example doesn't work

### ISSUE THREAD

**Issue by xipeter** [microsoftgraph/microsoft-graph-docs#15789]
[Enter feedback here]
When I tried to create a private channel, I follow the example code, but got exception:
```
com.microsoft.graph.http.GraphServiceException: Error code: BadRequest
Error message: 'odata.type' must be specified in the request body for each member.

POST https://graph.microsoft.com/v1.0/teams/bb172319-b047-457b-8fed-7a81009e08a1/channels
SdkVersion : graph-java/v5.10.0
SdkVersion : graph-java/v5.10.0
[...]

400 : Bad Request
[...]

[Some information was truncated for brevity, enable debug logging for more details]
```

**This is my request body** 
{"description":"for testing","displayName":"Not working","membershipType":"private","members":[{"roles":["owner"],"user@odata.bind":"https://graph.microsoft.com/v1.0/users('9f114ea4-9913-4a9d-b3f4-d00c88a8fdaf')"}]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Can you confirm if you are using this example  - https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#example-2-create-private-channel-on-behalf-of-user?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
