### ISSUE TITLE
[Question] How can a change notification have multiple change types?

### ISSUE THREAD

**Issue by ejan-089** [microsoftgraph/microsoft-graph-docs#15807]
My application subscribes to Teams channel messages.
The resource is `/teams/getAllMessages`.
From the [MS document](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0), I saw this description about the `changeType`:
> Multiple values can be combined using a comma-separated list.

I think that means the following value may happen:
```json
{
   "value":[
      {
         "subscriptionId":"4b43...",
         "changeType":"created, updated",
         "clientState":"abcde",
         "subscriptionExpirationDateTime":"2020-09-03T22:27:12.936788-07:00",
         "resource":"teams('321f...')/channels('19:5798...')/messages('159...')/replies('159...')",
         "resourceData":{
            "id":"1599...",
            "@odata.type":"#Microsoft.Graph.ChatMessage",
            "@odata.id":"teams('321f...')/channels('19:5798...')/messages('159...')/replies('1599...')"
         },
         "encryptedContent":{
            "data":"ChGA+m...",
            "dataSignature":"Jbbz...",
            "dataKey":"WOsYj9uzu...",
            "encryptionCertificateId":"0342...",
            "encryptionCertificateThumbprint":"15E2..."
         },
         "tenantId":"51ae..."
      }
   ],
   "validationTokens":[
      "eyJ0eX..."
   ]
}
```

I'm not sure under what scenario such a thing can happen.
For example, if a user posts a message on Teams, MS will send a change notification to my server.
How should I interpret the data if the `changeType` is "created, updated"?
Does that mean it was created and updated at the same time or something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe0590e-070b-cf56-cbc7-1dcb8a266380
* Version Independent ID: 2d912536-afc5-60f1-e381-2eef892cbded
* Content: [subscription resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscription.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @Jumaodhiss
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jumaodhiss** [comment]
This means that the subscription was created to deliver a notification if there is an update on a resource OR if a resource is created. In your case that notification was either triggered by a new message or an edited/updated message.

**Comment by FaithOmbongi** [comment]
Thank you @Jumaodhiss. Hi @ejan-089, hope the answer is satisfactory. Closing this issue.
