### ISSUE TITLE
Graph API | How to use $filter=contains

### ISSUE THREAD

**Issue by MehtabSiddiq** [microsoftgraph/microsoft-graph-docs#15837]
[Enter feedback here]
Contains operator is not working with function($filter), And can you please provide any working example for this.
Reference Question :https://stackoverflow.microsoft.com/questions/293333.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f6304a-ab90-8543-39c7-2afd61197ffb
* Version Independent ID: 9ca019b5-063f-33a2-3cb9-3ab6baafe9d4
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MehtabSiddiq for raising this issue. The `contains` operator is supported only by a handful of APIs and not users, groups, or applications APIs. You can see the syntax in one example here: https://docs.microsoft.com/en-us/graph/api/accessreviewset-list-definitions?view=graph-rest-beta&tabs=http#example-2-retrieve-all-access-review-definitions-scoped-to-all-microsoft-365-groups-in-a-tenant

To request that this operator be supported by the users API and user properties, please feel free to [file a feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) and you can repost the link here so other customers can amplify your voice.

**Comment by MehtabSiddiq** [comment]
Thank you @FaithOmbongi  for looking into the issue and providing the clarification on this.
