### ISSUE TITLE
Need to clarify the parameters

### ISSUE THREAD

**Issue by xipeter** [microsoftgraph/microsoft-graph-docs#15876]
[Enter feedback here]
Hi,

Could you please clarify how and where can I get "encryptionCertificate" and "encryptionCertificateId", would appreciate that, thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b371a145-de61-e63d-7c5a-ef25c19ca52b
* Version Independent ID: 0fced10b-0bc7-0645-362b-b20b5bbeff19
* Content: [Get change notifications for messages in Teams channels and chats using Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-changenotifications-chatmessage)
* Content Source: [concepts/teams-changenotifications-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-changenotifications-chatmessage.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Both of these come from the certificate you pass for encryption. CertificateId is a custom string that you can choose to put anything in (it allows you to track certificate on your side which was used for encryption as you are rotating certificates).

Refer to https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data?context=graph%2Fapi%2F1.0&view=graph-rest-1.0
