### ISSUE TITLE
`propagateChanges` update at site level does not work

### ISSUE THREAD

**Issue by FranckyC** [microsoftgraph/microsoft-graph-docs#15915]
Update of the `propagateChanges` property for a site column, like shown in the example, does not work. Get an **InvalidRequest** error:

![image](https://user-images.githubusercontent.com/5659122/154754453-4c2d92f9-d3ca-40d1-80ab-da95a51ae84a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed231325-941a-ce12-8921-3eab2013a74e
* Version Independent ID: 0663140a-ccc0-5380-98e3-3924156247b3
* Content: [Update columnDefinition - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/columndefinition-update.md)
* Product: **sites-and-lists**
* Technology: **microsoft-graph**
* GitHub Login: @swapnil1993
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by swapnil1993** [comment]
This property is not supported for site and list columns. This is described in the Note section of this page https://docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-1.0

**Comment by FranckyC** [comment]
I missed that sorry. That's a shame, is there any plan to make this available? The only way to do it right now is using CSOM?
