### ISSUE TITLE
Cloud-only accounts

### ISSUE THREAD

**Issue by explosivo22** [microsoftgraph/microsoft-graph-docs#15954]
I have an issue with this statement `For a cloud-only user (where onPremisesSyncEnabled is false), these properties can be set during [creation](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0) or [update](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0).`  We have what I would call cloud-only accounts because we created them solely in the cloud and they have never been synced with on-premises thus the `onPremisesSyncEnabled` value is `null` and not `false`.  The onPremisesExtensionAttributes should still be able to be edited with cloud-only accounts when the `onPremisesSyncEnabled` has a value of `null` or `false`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95aef5c2-9605-84f7-a9b2-0e82059e7a77
* Version Independent ID: 49ceed02-edf3-11b6-89ca-da3fa1223630
* Content: [onPremisesExtensionAttributes resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/onpremisesextensionattributes?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/onpremisesextensionattributes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/onpremisesextensionattributes.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @explosivo22 for raising this issue. You are right. **onPremisesSyncEnabled** is a nullable property so its value can be `null` and is `null` for scenarios like yours where the user has never been synced to on-prem. I've raised a PR to address your feedback.
