### ISSUE TITLE
Retrieving data under hold using API

### ISSUE THREAD

**Issue by henry-filosa** [microsoftgraph/microsoft-graph-docs#15970]
[It looks like it is possible to retrieve data under hold using the user interface](https://docs.microsoft.com/en-us/microsoft-365/compliance/create-ediscovery-holds?view=o365-worldwide#search-locations-on-ediscovery-hold). However, I cannot find anything similar in the API and the /drive endpoints will not return data that is under hold, but has been deleted. Will there be an endpoint in the future to retrieve this data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af911d9-6dca-1a02-2bf8-39b20cac13c6
* Version Independent ID: ae5b4afd-7951-62ef-2344-38811dc76817
* Content: [legalHold resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/ediscovery-legalhold?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/ediscovery-legalhold.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/ediscovery-legalhold.md)
* Product: **ediscovery**
* Technology: **microsoft-graph**
* GitHub Login: @mahage-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by SeunginLyu** [comment]
@henry-filosa thanks for your inquiry,
Currently, the eDiscovery APIs in Microsoft Graph only work with Advanced eDiscovery cases.
The search locations on hold is currently a Core eDiscovery-only feature, and we don't have plans to add a similar feature for either Advanced eDiscovery nor as a Graph API endpoint for Advanced eDiscovery.

https://docs.microsoft.com/en-us/graph/api/resources/ediscovery-ediscoveryapioverview?view=graph-rest-beta

**Comment by SeunginLyu** [comment]
@henry-filosa Could you elaborate on "exports not including that under hold, but deleted."? do you mean you aren't seeing data that lives in PHL (preservation hold library)

**Comment by henry-filosa** [comment]
@SeunginLyu Isn't the PHL specific to retention policies? I'm specifically interested in data that is under a preservation hold in the compliance center. For example, Custodian X's exchange inbox is placed under hold. They then delete an email. This email does not appear when we use the drive resources export, but it does appear when using source collections in the compliance center. Should we expect to see deleted data that is retained as part of a hold when using the drive resources endpoints?

**Comment by SeunginLyu** [comment]
The email is part of the custodian's exchange mailbox, not part of the custodian's OneDrive. Please refer to the [userSources](https://docs.microsoft.com/en-us/graph/api/ediscovery-custodian-post-usersources?view=graph-rest-beta&tabs=http) for more information.
