### ISSUE TITLE
Broken nextlink in API response for channel members

### ISSUE THREAD

**Issue by harmputman** [microsoftgraph/microsoft-graph-docs#15973]
The `@odata.nextLink` that is returned in te API response for `/teams/{teamId}/channels/{channelId}/members` is broken; it contains two skiptokens. Please fix.

Example:
Request URI: `https://graph.microsoft.com/v1.0/teams/8b38ffbd-be1f-4d5e-9513-b7da70e8eeec/channels/19:74a1aa15f0c04f8ca07b4305f5afe496@thread.tacv2/members?$top=50`

Value of nextLink: `https://graph.microsoft.com/v1.0/teams/8b38ffbd-be1f-4d5e-9513-b7da70e8eeec/channels/19:74a1aa15f0c04f8ca07b4305f5afe496@thread.tacv2/members?$top=50&$skiptoken=%2fodata%2fteams(%278b38ffbd-be1f-4d5e-9513-b7da70e8eeec%27)%2fchannels(%2719%3a74a1aa15f0c04f8ca07b4305f5afe496%40thread.tacv2%27)%2fmembers%3f%2524top%3d50%26%2524skiptoken%3deyJyYy5mIjpudWxsLCJydiI6MTY0NTYyNzk2NjIwOCwiZiI6Ijg6b3JnaWQ6MjhjN2QzZmMtNGIyYy00YmE2LTk3M2MtNWU0OTk3MWNjNjYzIiwicnMiOjI3NiwiZnIiOiJBZG1pbnxVc2VyfEd1ZXN0IiwiZnQiOm51bGwsImZjbSI6bnVsbCwiZnN1Ijp0cnVlLCJyYy5jbyI6MCwicmMuY3AiOjAsInJjLnBzIjowLCJyYy5jdiI6IlYyIiwidiI6MSwiY3QiOiJHZXRNZW1iZXJzIiwicmdpZCI6IjkyOjc0YTFhYTE1ZjBjMDRmOGNhMDdiNDMwNWY1YWZlNDk2QHRocmVhZC50YWN2MiIsInBzIjo1MH0%253d`

Requesting the nextLink uri results in the following error:

```
{
    "error": {
        "code": "NotFound",
        "message": "UnknownError",
        "innerError": {
            "date": "2022-02-24T10:44:46",
            "request-id": "f81af64f-21ee-4cfd-8433-c0179eb8e0c0",
            "client-request-id": "142b79db-f73e-a9b7-690d-35dda98feb13"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8858f65c-7df0-5391-31cf-7a9aaa95a47b
* Version Independent ID: 5d379b49-c442-f4b5-585d-9376ba2217c6
* Content: [List members of a channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/channel-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-list-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by collaboratetech** [comment]
Hi, is there any update on a fix?

**Comment by AkJo** [comment]
This is being investigated right now.

**Comment by Brunaldo** [comment]
Cool, thanks @AkJo

**Comment by Prasad-MSFT** [comment]
@harmputman - There is bug raised for this issue. We will inform you once we get any update.

**Comment by harmputman** [comment]
Checked in the Graph explorer, fix confirmed. Thanks!
