### ISSUE TITLE
Possible service values

### ISSUE THREAD

**Issue by Dethras** [microsoftgraph/microsoft-graph-docs#15991]
I would like a list of the possible "Service" name strings that I might encounter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e607b71-1928-600d-9179-f0eac1778671
* Version Independent ID: 42b75a67-d934-e239-1610-5b09dc6a7551
* Content: [assignedPlan resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/assignedplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/assignedplan.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Dethras for raising this issue.

The **service** property is not a display name but more of a categorization of a group of services. As an example – “WindowsUpdateforBusinessCloudExtensions” is an example of a service name. Multiple service plans can share the same **service** property value. As an example – Exchange Online (Plan 1) and Exchange Online (Plan 2) both have the service property of `Exchange` as you can see through a `/me/assignedPlans` query.

The categorization information is currently not available publicly except through the API.

**Comment by Dethras** [comment]
@FaithOmbongi - But can't we at least have a list of these, because as of now, we are doing things blindly, and hoping that we don't encounter something else, something new. A map stating that "Exchange" could indicate having either "Exchange Online (Plan 1)" or "Exchange Online (Plan 2)", but it would be at least great to know what other strings like "Exchange" we might encounter. Programmatically you are mapping these so I would assume that you have a list or something. Anything would be a great help. Thanks
