### ISSUE TITLE
OData filter parameters implemented?

### ISSUE THREAD

**Issue by dillardd** [microsoftgraph/microsoft-graph-docs#16010]
The page mentions that the method supports OData Query parameters, however I am not able to get them to work. Have these been implemented yet?

Example:
```powershell
Invoke-RestMethod `
        -Headers $headerParams `
        -Uri "https://graph.microsoft.com/beta/teams/$($team.teamGuid)/schedule/timecards?`$filter=createdDateTime ge '2022-02-01T08:00'"
```

Returns:
```json
{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "date": "2022-02-28T15:49:58",
            "request-id": "26ac5b0a-b93a-4e1e-89e2-13a5da2b3311",
            "client-request-id": "26ac5b0a-b93a-4e1e-89e2-13a5da2b3311"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2ad4f03-78d0-ba9a-75af-e2124cca38ba
* Version Independent ID: 84b05436-c39b-f8ae-a642-9bb45e328566
* Content: [List timeCard - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/timecard-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/timecard-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/timecard-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Apologies for the delay in response. We received the below update from the engineering team -

The properties "createdDateTime" and "lastModifiedDateTime" are not supported as filter parameters. Options in this case would be to filter by ClockIn or ClockOut times.

Example queries.

1. [https://graph.microsoft.com/beta/teams/{teamId}/schedule/timecards?$filter=clockInEvent/dateTime](https://graph.microsoft.com/beta/teams/%7BteamId%7D/schedule/timecards?$filter=clockInEvent/dateTime) ge 2022-05-18
2. https://graph.microsoft.com/beta/teams/{teamId}/schedule/timecards?$filter=originalEntry/clockInEvent/dateTime ge 2022-05-18
