### ISSUE TITLE
Team Mobile Notifications from Microsft Graph (sendactivitynotification) not working

### ISSUE THREAD

**Issue by adashen** [microsoftgraph/microsoft-graph-docs#16020]
We are sending notifications to users through graph. However, in the production version of our app the desktop notifications work but the mobile notifications do not. In our beta/test version of the app both desktop and mobile notifications work.

The only difference that I can think of is

A different Azure Ad App registration

The production version of the teams app is deployed though the store, while the beta/test version of the app is sideloaded.

Both the production and the beta/test version of the app make the same Microsoft Graph call to send notifications, but to different client ids.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9948c753-b761-228d-4915-9c26b47dd6a3
* Version Independent ID: 5b4f132c-3409-885d-9a1a-848bcd7c3c7c
* Content: [userTeamwork: sendActivityNotification - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/userteamwork-sendactivitynotification.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @eddie-lee-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by eddie-lee-msft** [comment]
Can you please share a request-id and timestamp pairing of a call to the API that has notification show up in desktop but not mobile? This would help us debug what may be going on.

**Comment by YorkeNW06** [comment]
@eddie-lee-msft Here is a full trace of a graph call we made. Thanks!

Request-Id = b18a4b9f-c6f7-4b00-8201-689129c5b992
Timestamp = Wed, 02 Mar 2022 14:54:11 GMT

Base Address https://graph.microsoft.com/
Request Uri v1.0/users/a57a464e-71f6-4019-84b4-86acfd710047/teamwork/sendActivityNotification
Full Url https://graph.microsoft.com/v1.0/users/a57a464e-71f6-4019-84b4-86acfd710047/teamwork/sendActivityNotification
Method POST
Request Header Accept-Encoding - gzip
Request Header Authorization - Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IjVMYzV3cUpWYXVVOU5lQlNKZVg4ZWp6UHhsYXdPak9GUzZhRjEzU3EzZjgiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCIsImtpZCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC84MjIyNjc2My1mNTI2LTQ4NTgtYTEwOC1lMDUxN2MyYWFiNDEvIiwiaWF0IjoxNjQ2MjMyNTUxLCJuYmYiOjE2NDYyMzI1NTEsImV4cCI6MTY0NjIzNjQ1MS...
Request Header Content-Type - application/json
Request Content {"topic":{"@odata.type":"#microsoft.graph.teamworkActivityTopic","source":"text","value":"New text message","webUrl":"[https://teams.microsoft.com/l/entity/f56c551e-73cc-4416-a977-482fdfde966f/textingtab?context={\"subEntityId\":\"1b358864-f756-47dd-9f78-7612d7897282\"}"},"activityType":"textReceived","chainId":5178567095741679716,"previewText":{"content":"Trst","contentType":"text"},"templateParameters":[{"name":"from","value":"Nathan"}],"recipient":null}](https://teams.microsoft.com/l/entity/f56c551e-73cc-4416-a977-482fdfde966f/textingtab?context=%7B%5C%22subEntityId%5C%22:%5C%221b358864-f756-47dd-9f78-7612d7897282%5C%22%7D%22%7D,%22activityType%22:%22textReceived%22,%22chainId%22:5178567095741679716,%22previewText%22:%7B%22content%22:%22Trst%22,%22contentType%22:%22text%22%7D,%22templateParameters%22:%5B%7B%22name%22:%22from%22,%22value%22:%22Nathan%22%7D%5D,%22recipient%22:null%7D)
Response Received 03/02/2022 14:54:12 +00:00 (813ms)
Read 03/02/2022 14:54:12 +00:00 (0ms)
Response Header Strict-Transport-Security - max-age=31536000
Response Header request-id - b18a4b9f-c6f7-4b00-8201-689129c5b992
Response Header client-request-id - b18a4b9f-c6f7-4b00-8201-689129c5b992
Response Header x-ms-ags-diagnostic - {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"3","ScaleUnit":"005","RoleInstance":"CH01EPF000051E2"}}
Response Header Date - Wed, 02 Mar 2022 14:54:11 GMT
Response Message No Content
Response Status 204
Response Content
Deserialization Start 03/02/2022 14:54:12 +00:00
Deserialization End 03/02/2022 14:54:12 +00:00 (0ms)
Finished 03/02/2022 14:54:12 +00:00 (813.8606ms)

**Comment by eddie-lee-msft** [comment]
Gotten in contact with mobile folks. Waiting to see what they say.

**Comment by YorkeNW06** [comment]
@eddie-lee-msft is there any update by chance? Thanks!

**Comment by eddie-lee-msft** [comment]
@YorkeNW06 still haven't gotten a response from them. Pinged them again. Sorry for the delay!

**Comment by eddie-lee-msft** [comment]
@YorkeNW06 can you please try now? It turns out the id of your app needed to be added to a special approval list for notifications to pop up on mobile. 

Feel free to reach out to "teamsubm@microsoft.com" if you're still having issues.

**Comment by YorkeNW06** [comment]
It is working now. Thanks!

**Comment by lramosvea** [comment]
Closing this issue as it seems like the question has been answered. Please feel free to reopen.
