### ISSUE TITLE
Action on behalf of another user is not allowed

### ISSUE THREAD

**Issue by umutulas00** [microsoftgraph/microsoft-graph-docs#16021]
GET /me/agreementAcceptances
**GET /users/{id | userPrincipalName}/agreementAcceptances**

it is not supported to retrieve information about another user. "Action on behalf of another user is not allowed"

Is that a bug? If its not, why we have the userPrincipalName option on the get request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aad0b67-f7f5-f110-8450-13e4d137fb99
* Version Independent ID: 03a3cc84-0c9b-a8dc-b75d-164af1bf9ebe
* Content: [List agreementAcceptances - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-agreementacceptances?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-agreementacceptances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-agreementacceptances.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @raprakasMSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @umutulas00 for raising this issue. You can check another user's agreement acceptance status through the following call: [https://graph.microsoft.com/v1.0/identityGovernance/termsOfUse/agreements/id/acceptances](https://developer.microsoft.com/en-us/graph/graph-explorer?request=identityGovernance%2FtermsOfUse%2Fagreements%2Fid%2Facceptances&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)

And you can filter by userPrincipalName (`eq` operator only).

`/users/{id | userPrincipalName}/agreementAcceptances` only works if id/userPrincipalName is the signed-in user's.

I see we're missing some documentation for the query I shared above; I'll leave this issue open so I can raise a PR to close this doc gap.
