### ISSUE TITLE
Problems with the sample code

### ISSUE THREAD

**Issue by robledop** [microsoftgraph/microsoft-graph-docs#16040]
`objectId` is shown as a GUID, but I was only able to make it work by passing the user's DistinguishedName instead.
At `"objectTypeName": "User"`, the parameter "User" only works if it is all lower case: "user".

```
POST https://graph.microsoft.com/beta/servicePrincipals/{servicePrincipalsId}/synchronization/jobs/{synchronizationJobId}/provisionOnDemand
Content-Type: application/json

{
    "parameters": [{
      "subjects": [{
          "objectId": "9bb0f679-a883-4a6f-8260-35b491b8b8c8",
          "objectTypeName": "User"
      }],
      "ruleId": "ea807875-5618-4f0a-9125-0b46a05298ca"
    }]
  }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eafd9238-b824-020e-f37d-374b3077e93f
* Version Independent ID: 10bfb397-4eef-b1ce-a1c2-479a04a3abf7
* Content: [synchronizationJob: provisionOnDemand - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/synchronization-synchronizationjob-provision-on-demand.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @ArvindHarinder1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @robledop for raising this issue and my apologies for the delayed response. Yes, you're right. Synchronization from AD to Azure AD requires the **onPremisesDistinguishedName** and user for **objectId** and **objectTypeName** respectively. The current example applies to synchronization from Azure AD to a third-party app.

I've raised a PR to fix the doc.
