### ISSUE TITLE
Is there a way of filtering printers with hasPhysicalDevice is false

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [microsoftgraph/microsoft-graph-docs#16078]
[Enter feedback here]
Documentation says step (6) At that time, your application can [fetch the jobs of the associated virtual printer](https://docs.microsoft.com/en-us/graph/api/printer-list-jobs) and filter the list to jobs created by the current user.

What is the expectation on above statement, it means that application must remember the registered virtual printers or Is it possible to get the list of virtual printers on the tenant by filtering the printers with hasPhysicalDevice is false?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 314b19af-9c9e-4f82-83d1-eb2261d9c108
* Version Independent ID: 08f4d779-585c-45a7-339b-45e364ac0400
* Content: [Universal Print cloud printing API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/universal-print-concept-overview#extending-universal-print-to-support-pull-printing)
* Content Source: [concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/universal-print-concept-overview.md)
* Product: **cloud-printing**
* Technology: **microsoft-graph**
* GitHub Login: @braedenp-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by braedenp-msft** [comment]
@SonOfJesseAsSnekithan Thanks for your question!

At the moment, the Microsoft Graph API does not support filtering on hasPhysicalDevice. The app will need to keep track of which virtual printers it has registered.

This is a good feature request that we'll consider as we plan updates to the API.
