### ISSUE TITLE
Create teamworkTag doesn't work any more, response is 401

### ISSUE THREAD

**Issue by AvePoint-JasonJiang** [microsoftgraph/microsoft-graph-docs#16095]
Hi Team,
We are working on migration projects, and we have found that the create teamwork tag API won't work any more with application permission since last week
the response is 401 Unauthorized.
Request:
POST https://graph.microsoft.com/beta/teams/65095d2a-c655-44a9-b9f6-1f0dc374ca1d/tags HTTP/1.1
Content-Type: application/json
Authorization: Bearer {token}
User-Agent: TeamGroupMigration
Host: graph.microsoft.com
Content-Length: 126

{
  "displayName": "TestTagaa",
  "members": [
    {
      "userId": "4c830b52-f463-4757-824b-a797347231bd"
    }
  ]
}

Response:

HTTP/1.1 401 Unauthorized
Content-Type: application/json
Strict-Transport-Security: max-age=31536000
request-id: 456127af-76d9-436e-9262-c88efc97c10f
client-request-id: 456127af-76d9-436e-9262-c88efc97c10f
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"Korea Central","Slice":"E","Ring":"3","ScaleUnit":"001","RoleInstance":"SE1PEPF00001DEE"}}
Date: Tue, 08 Mar 2022 01:56:12 GMT
Content-Length: 213

{"error":{"code":"Unauthorized","message":"UnknownError","innerError":{"date":"2022-03-08T01:56:12","request-id":"456127af-76d9-436e-9262-c88efc97c10f","client-request-id":"456127af-76d9-436e-9262-c88efc97c10f"}}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b518b86d-646e-130b-99be-5174a9055f99
* Version Independent ID: 42dc2d0f-ba84-0f61-1015-f5e5788e474c
* Content: [Create teamworkTag - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamworktag-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @anniecolonna
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RayNeel** [comment]
Any updates on this? I'm having the same issue. Worked until recently.

**Comment by Luunk** [comment]
Have the same issue. Any update?

**Comment by Meghana-MSFT** [comment]
We are looking at this issue. We will update you.

**Comment by Meghana-MSFT** [comment]
We tried this using both postman and Graph explorer. It is working fine in both the cases. 

![image](https://user-images.githubusercontent.com/81138249/160173502-b531bd3e-0b94-4b1e-b43b-7669f66cf1cd.png)

![image](https://user-images.githubusercontent.com/81138249/160173630-6759b6f8-1738-45d0-bf5a-ec94313da668.png)

Based on the above error code issue seems to be related to permissions and access token. Could you please check the permissions given and access token.

**Comment by RayNeel** [comment]
It has been working again, recently. 10 days ago, when I documented this, it definitely wasn't. 
No idea why that would be, my code has not changed, since I first authored it, 5 months ago.

**Comment by Meghana-MSFT** [comment]
Thank you for confirming. We are closing this issue from our end. Please feel free to contact us if you face any issue again.

**Comment by Meghana-MSFT** [comment]
@Luunk - Could you please confirm if you still see the issue? We tried creating tab, getting tags and members of a tag. Those worked fine in Postman. Could you please check again and confirm?

**Comment by Meghana-MSFT** [comment]
Could you please confirm if you still see the issue?

**Comment by Luunk** [comment]
@Meghana-MSFT - Sorry for the late response. Yes it is working again! It started to work just 2-3 days after I wrote the previous comment. Thanks for checking it out!

**Comment by lramosvea** [comment]
Closing as the issue seems to be fixed. Please feel free to reopen otherwise.
