### ISSUE TITLE
how do we apply sensitivity label to a local file?

### ISSUE THREAD

**Issue by monishmunot** [microsoftgraph/microsoft-graph-docs#16100]
how do we apply sensitivity label to a local file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 671eaa8a-802d-2b3a-8d4b-52f7c67af519
* Version Independent ID: b7afb88b-21e5-7dde-730f-e36e312939d6
* Content: [informationProtectionLabel: evaluateApplication - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/informationprotectionlabel-evaluateapplication?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/informationprotectionlabel-evaluateapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/informationprotectionlabel-evaluateapplication.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @tommoser
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tommoser** [comment]
The Graph APIs don't support this directly. You should investigate MIP SDK: https://aka.ms/mipsdkdocs. 

Using the Graph API to do this would require that you write your own parser to translate the API response to actions on the file. We implement that out of box in the MIP SDK.
