### ISSUE TITLE
Install-Module Microsoft.Graph -Scope CurrentUser error

### ISSUE THREAD

**Issue by OuterCloud** [microsoftgraph/microsoft-graph-docs#16119]
when I execute the command：
Install-Module Microsoft.Graph -Scope CurrentUser 

error below：
![企业微信截图_16468258778534](https://user-images.githubusercontent.com/16227179/157434541-5a78e7a3-c36c-49a3-a05b-f5648439ac8e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28190588-5c01-b71a-0c2c-8ed034108114
* Version Independent ID: 0fea23a1-b827-5353-d9e5-cdb7704f0a33
* Content: [Install the Microsoft Graph PowerShell SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/powershell/installation)
* Content Source: [concepts/powershell/installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/powershell/installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@OuterCloud have you done the prerequisites for installing in Windows PowerShell?

> The following prerequisites must be met to use the Microsoft Graph PowerShell SDK with Windows PowerShell.

> 
> - Upgrade to [PowerShell 5.1 or later](https://docs.microsoft.com/powershell/scripting/windows-powershell/install/installing-windows-powershell#upgrading-existing-windows-powershell)
> - Install [.NET Framework 4.7.2 or later](https://docs.microsoft.com/dotnet/framework/install/)
> - Update PowerShellGet to the latest version using `Install-Module PowerShellGet -Force`
