### ISSUE TITLE
$expand is not working in transitiveMemberOf

### ISSUE THREAD

**Issue by Vickyk1** [microsoftgraph/microsoft-graph-docs#16118]
User is calling Microsoft's Graph API to retrieve user data via the /me endpoint, using $expand=transitiveMemberOf to get the user's groups both direct and indirect.

Before user had been using $expand=memberOf to just get direct groups which was sufficient. However, now need to get indirect memberships aswell.

The problem  user facing is that $expand=transitiveMemberOf seems to just be returning the same groups as $expand=memberOf.

Due to the implementation, which he cannot change, he is restricted to a single API call, in which he also require information provided by /me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efff8389-bccd-8e3b-ceb1-cd176819b92c
* Version Independent ID: 38d4e860-024e-72de-2546-60d236667129
* Content: [List group transitive memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-transitivememberof.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @Jordanndahl
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Vickyk1 for raising this issue. For directory objects, such as groups and users, `$expand` only returns a maximum of 20 objects for groups, hence the behavior you're seeing. We currently don't support any way to page the expanded results. Please see the note here: https://docs.microsoft.com/en-us/graph/query-parameters#expand-parameter

The best option to use is the /transitiveMemberOf path segment. For example, using the [List user transitiveMemberOf](https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http) or [List group transitiveMemberOf](https://docs.microsoft.com/en-us/graph/api/group-list-transitivememberof?view=graph-rest-1.0&tabs=http) methods. That should return both direct and indirect memberships.

**Comment by TechPhil** [comment]
Hi there, if I may chime in - 
I am also experiencing this exact issue, but unless I'm missing something, the 20 object maximum shouldn't be pertinent.

`memberOf` for me is returning 6 objects, and `transitiveMemberOf` should only return 11 objects, yet calling `$expand=transitiveMemberOf` *only* returns the same 6 as `$expand=memberOf`

Please also see the following in the issue - 
> Due to the implementation, which he cannot change, he is restricted to a single API call, in which he also require information provided by /me.

Using the /transitiveMemberOf path segment is therefore *not* an option

**Comment by FaithOmbongi** [comment]
Hi @TechPhil, your problem is a bit different because you haven't reached the limit of 20 expanded objects; So your problem requires more investigation.

Please test the queries through Graph explorer and if you're still seeing 6 objects through `$expand=transitiveMemberOf` instead of the 11 you expect, kindly file this issue at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-users.html) and please provide a request ID so this can be investigated and a conclusive answer provided.

**Comment by TechPhil** [comment]
Thank you for your response @FaithOmbongi 

I did raise this on Microsoft Q and A a while ago (see [this link](https://docs.microsoft.com/en-us/answers/questions/749986/meexpandtransitivememberof-is-returning-memberof-n.html))

Again, I have tried many different workarounds but I really am restricted to this single API call so getting this to work would be the perfect solution for me
