### ISSUE TITLE
Chat new fields teamworkOnlineMeetingInfo.calendarEventId not populated

### ISSUE THREAD

**Issue by AlexSapple** [microsoftgraph/microsoft-graph-docs#16122]
Hi Guys, 

this is a fantastic addition to the chat entity feb 2022(https://docs.microsoft.com/en-us/graph/whats-new-overview#teamwork) and answers the following ticket I opened just recently - https://github.com/microsoftgraph/microsoft-graph-docs/issues/15537

I rushed to implement this and remove my hack that was trying to cross reference events starting from a chatId... but (there's always a but... :(

the property calendarEventId does not always appear to be populated. In fact, it looks to me as though it's only ever populated if the meeting was created natively in Teams client (for example, meetings created using Outlook or custom apps using Create event [isOnlineMeeting=true] https://docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&tabs=http do not have this populated when querying the associated chatId

![image](https://user-images.githubusercontent.com/30351641/157491087-8d8ae9dd-8356-4d08-a3e0-5eb7dd8fee91.png)

any thoughts on this? many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1b47b99-078f-a85a-fc92-d262b29a991a
* Version Independent ID: faaa6ab2-be92-05fc-9adb-34dcf8fee7cb
* Content: [Get chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AlexSapple** [comment]
I thought that maybe I could take advantage of the joinUrl (which does appear to be populated in all cases) and do something like this to look up my event - `https://graph.microsoft.com/v1.0/me/events?$filter=OnlineMeeting/JoinUrl eq '[joinWebUrl]'`

but that doesn't work as the API reports that OnlineMeeting does not support filtering - so really, unless I am missing something, I can't rely on this new functionality at all without being able to rely on the `CalendarEventId`

**Comment by RamjotSingh** [comment]
Investigating

**Comment by Meghana-MSFT** [comment]
We got an update from the engineering team that "currently this is available only for meetings through teams. Documentation will be updated accordingly.

**Comment by AlexSapple** [comment]
thanks @Meghana-MSFT - is there a roadmap for having this work on any meetings? just that it's quite hard in the first pace to see the use when 1 meeting has the data and the next not. Right now I've coded with a fallback - but would be thrilled to be in a position where the fallback is not needed (in this case the fallback code is a horrific hack to fuzzy search for an event using the calendar.events in a rough time window of the chat created date.

**Comment by Meghana-MSFT** [comment]
Currently there is no workitem for this feature. You can request this feature at [Microsoft UserVoice](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

**Comment by AlexSapple** [comment]
Done - https://feedbackportal.microsoft.com/feedback/idea/9730456d-2aac-ec11-a81c-0022485066fe. I have linked back to this ticket in that feedback. Feels far more like a bug than a feature, but either way - we shall see.
