### ISSUE TITLE
Plans to increase known limitations?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/microsoft-graph-docs#16124]
If I am reading this correctly, the maximum number of external items an organisation can index is 7 million (10 connections, 700,000 external items per connections)

In large organizations this wouldn't cover a single external system, let alone multiple document repositories...

Are there any plans to increase this limit, or is it perhaps already possible by paying more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6401a9e3-bfcc-866f-bfa8-d166b1d0b4f5
* Version Independent ID: 0d0513e5-5158-870c-9c62-99ff39d6a8c9
* Content: [Use the Microsoft Search API to index data - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/indexing-api-overview?view=graph-rest-beta&preserve-view=true#common-use-cases)
* Content Source: [api-reference/beta/resources/indexing-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/indexing-api-overview.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @snlraju-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by henrymbuguakiarie** [comment]
#assign: @Arvind-Ravi

**Comment by henrymbuguakiarie** [comment]
#reassign:Arvind-Ravi

**Comment by KumarSeetharaman74** [comment]
@catmanjan - we will be soon expanding each connection to support up to 5M items. We will be rolling out this capability gradually over the next month or so. Let us know if this answers your question and would satisfy the needs of your organization/customer.

**Comment by Arvind-Ravi** [comment]
Thanks @KumarSeetharaman74 for chiming in. @catmanjan - Like Shiva mentioned, do let us know if you have any follow ups.

**Comment by catmanjan** [comment]
Thanks @KumarSeetharaman74 - that should be enough.

Will the number of connections also be increasing from 10?

**Comment by Arvind-Ravi** [comment]
@catmanjan - It is in the works but further out compared to the 5M item. So for the immediate future, the number of connections is likely to remain at 10. We are collecting feedback from our customers looking for a higher connections limit to prioritize it on the roadmap.
