### ISSUE TITLE
Mention/refer to deep link syntax for "webUrl" property

### ISSUE THREAD

**Issue by dhoelzl** [microsoftgraph/microsoft-graph-docs#16148]
Hello!

It would be nice that you mention and refer to the deep link syntax for the "webUrl" property.

Regards,
Dominik

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef120b3-03b9-cca1-9479-05720e6fd9ef
* Version Independent ID: 0cf32a73-043a-6b34-f71c-a8d3bd410bf7
* Content: [Send activity feed notifications to users in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications#feedback)
* Content Source: [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-send-activityfeednotifications.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
We will check and act on it accordingly.

**Comment by Prasad-MSFT** [comment]
@dhoelzl - PFB Syntax for "webUrl" property

`https://teams.microsoft.com/l/message/<channelId>/<messageId>?tenantId=<tenantId>&groupId=<groupId>&parentMessageId=<parentMessageId>&teamName=<teamName>&channelName=<channelName>&createdTime=<messageId>`

Needs to update in below doc section: https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications#example-3-notify-a-user-about-an-event-using-a-custom-topic

**Comment by v-chetsh** [comment]
@AkJo - Please help us here to update the contents.

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Please feel free to reopen otherwise.
