### ISSUE TITLE
Promote M365 Group to team - BadRequest

### ISSUE THREAD

**Issue by joostvdlinden** [microsoftgraph/microsoft-graph-docs#16209]
This does not seem to work for me.

**Method:** 
PUT

**URI:** 
https://graph.microsoft.com/v1.0/groups/1fed535d-c426-42aa-8d52-9b81ae932df3/team

**Headers:**
{
  "content-type": "application/json"
}

**Body:**
{
  "tenant": "abxxxx31-xxxx-xxxx-xxxx-xxxxedd81xxx",
  "audience": "https://graph.microsoft.com",
  "clientId": "b35de2bf-xxxx-xxxx-xxxx-0a46e4e93e98",
  "secret": "*sanitized*",
  "type": "ActiveDirectoryOAuth"
}

This is the error message that I am receiving:
"message": "Write requests (excluding DELETE) must contain the Content-Type header declaration.",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team from group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@joostvdlinden - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
@joostvdlinden - It looks like content type is not added properly in header section. Could you please add the "Content-Type":"application/json" like this?

**Comment by sayali-MSFT** [comment]
@joostvdlinden -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by joostvdlinden** [comment]
> @joostvdlinden - It looks like content type is not added properly in header section. Could you please add the "Content-Type":"application/json" like this?

@sayali-MSFT the headers are correct.
Please review the screenshots attached. I have verified that the Tenant ID, App ID and Client Secret are correct.
Even the API permissions are correct.

![image](https://user-images.githubusercontent.com/47981540/160858617-f3ee1295-ae92-4656-8f44-4ad35faf418d.png)
![image](https://user-images.githubusercontent.com/47981540/160858662-6c037886-1652-48c6-adf4-8d96b1b5b091.png)
![image](https://user-images.githubusercontent.com/47981540/160858854-ba9c011e-c704-4b7d-a81b-b4265934f7d6.png)

**Comment by sayali-MSFT** [comment]
@joostvdlinden -Could you please try from the following suggestions:-
1.put the body into the Queries and not into the body field. 
2.Passing the authentication as raw.
3.You have to pass the authorization as header in the headers section and pass JSON in the body (for items that you are passing in the query parameter)

**Comment by sayali-MSFT** [comment]
@joostvdlinden -Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by joostvdlinden** [comment]
Hi @sayali-MSFT I used a different App Registration and now it seems to work.
Not sure what had caused this issue. If I encounter this is issue again I will update the thread.
