### ISSUE TITLE
samlMetadataUrl availability?

### ISSUE THREAD

**Issue by qwiku** [microsoftgraph/microsoft-graph-docs#16210]
When is samlMetadataUrl be available for MS Graph? We are using this in AD Graph which will expire soon!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6dddf0-8459-cb01-7b37-6bf881f88b11
* Version Independent ID: 57eebfc1-ffde-35ef-fbb6-5a1c19dae722
* Content: [Property differences between Azure AD Graph and Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences)
* Content Source: [concepts/migrate-azure-ad-graph-property-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-property-differences.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by qwiku** [comment]
Hello, any feedback on this? We'll appreciate if someone can confirm that samlMetadataUrl will be included in MS Graph.

Thanks!

**Comment by FaithOmbongi** [comment]
Thank you @qwiku for raising this issue and my apologies for the delayed response. This is currently in the pipeline, but I can't provide an ETA. Please note Azure AD Graph retirement was postponed and we'll provide a new date by the end of the year. Hopefully, the property will be available in Microsoft Graph by then.
