### ISSUE TITLE
filter function contains not documented

### ISSUE THREAD

**Issue by Agazoth** [microsoftgraph/microsoft-graph-docs#16216]
According to this page, there should be a filter function that supports contains. Also according to the documentation, these filters vary by entity, which is documented in the advanced queries articel (https://docs.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http)

Neither this page nor the advanced queries page document a single entity, where contains is supported.

The need for contains is obvious. It is very common to pre- and suffix group display names and searching for groups is very often based on the middle part that makes sense for the end user. Consider a O365 group naming convention like the following:
```
DK-Customer1-Project1
DK-Customer1-Project2
DK-Customer2-Project1
SE-Customer1-Project3
SE-Customer3-Project1
```
Currently only startsWith or endsWith is supported. This means I need to know what countries have projects for a given customer and make 2 calls using startsWith and even more if I have several countries with projects on the customer.

Being able to do a contains search would mitigate this completely.

The contains function has been missing for years. Either it should be removed from this page or there should be documentation describing on what entities it can be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44f6304a-ab90-8543-39c7-2afd61197ffb
* Version Independent ID: 9ca019b5-063f-33a2-3cb9-3ab6baafe9d4
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#feedback)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Agazoth for asking this question. The `contains` operator isn't currently supported on resources that inherit from directoryObject. But it's supported by a subset of the Identity Governance APIs (access reviews and entitlement management, for example [here](https://docs.microsoft.com/en-us/graph/api/accessreviewset-list-definitions?view=graph-rest-1.0&tabs=http#use-the-filter-query-parameter) and [here](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-list-catalogs?view=graph-rest-1.0&tabs=http#optional-query-parameters)).

If an operator isn't indicated in a property description or in the Optional query parameters section of LIST/GET operations as supported (esp for users, groups, application, service principals resource docs), then you can safely assume that the API does not officially support it yet.

You can file a feature request for `contains` to be supported on directory objects by sending feedback directly to the [advanced filtering](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR_yN8EPoGo5OpR1hgmCp1XxUMENJRkNQTk5RQkpWTE44NEk2U0RIV0VZRy4u) implementation team or also file a request [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) and other customers can amplify your voice.
