### ISSUE TITLE
Broken link in "Use the Microsoft Graph API to work with Microsoft Teams"

### ISSUE THREAD

**Issue by toomanybananas** [microsoftgraph/microsoft-graph-docs#16213]
In the note under https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0#teams-and-groups (right above Membership changes in Microsoft Teams), the [Using Microsoft Graph in your Microsoft Teams pages](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/microsoft-graph) link 404s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5463d788-8e29-ca0a-5490-93506ff1ec80
* Version Independent ID: 1e7ca228-0b9f-beb1-d61f-7f1fdff50008
* Content: [Use the Microsoft Graph API to work with Microsoft Teams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/teams-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
We will check on it from our end and act on it accordingly.

**Comment by v-chetsh** [comment]
@surbhigupta12 - Could you please check and update the link accordingly.

**Comment by lramosvea** [comment]
Closing this but keeping https://github.com/microsoftgraph/microsoft-graph-docs/issues/16213 to get help and fix the link. Thanks.
