### ISSUE TITLE
Multi-tenant app registration billing

### ISSUE THREAD

**Issue by keffordt** [microsoftgraph/microsoft-graph-docs#16249]
Regarding this statement, "The organization that owns the app registration is responsible for the payment, which for multitenant apps may be different from the organization that runs the app". For multitenant apps, does this mean the tenant owner will get billed, or the app owner? Clarity on this will save some potential big billing issues. The "may" leads to too much ambiguity, so guidance will be appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f880b9-2394-f540-9b06-bcddbe40bfa8
* Version Independent ID: 22de9e03-e917-bcc6-abd7-ebfb3a0cdec8
* Content: [Licensing and payment requirements - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-licenses#required-licenses-for-modela)
* Content Source: [concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-licenses.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you

**Comment by Prasad-MSFT** [comment]
@keffordt -For single tenant apps tenant will get billed. For multitenant app (ISV) the owner of the app will get the billed and they will have a charge back mechanism to the tenant.

**Comment by v-chetsh** [comment]
@keffordt - Please let us know if above answer helped your or still need any help here?

**Comment by keffordt** [comment]
Thank you for the update
