### ISSUE TITLE
Registered owners information command not running. kindly check the URL please

### ISSUE THREAD

**Issue by Amty63** [microsoftgraph/microsoft-graph-docs#16256]
Below URL is not working while executing in the graph explorer. Kindly check.
https://graph.microsoft.com/v1.0/devices/{id}/registeredOwners

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2a55862-7db2-c860-811c-8538759e7226
* Version Independent ID: 4ee31c5c-91cf-ee92-6018-1deda67214d1
* Content: [List registeredOwners - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/device-list-registeredowners?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-list-registeredowners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-list-registeredowners.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @spunukol
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Amty63 for raising this issue. Unfortunately, I'm unable to replicate it as it's working on my end.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/14026935/159671436-98772b72-b12f-4c24-bb1b-5e6ae0e6302d.png">

Kindly check that you have the required permissions.

**Comment by Amty63** [comment]
Thanks FaithOmbongi,
just want to know if I use "https://graph.microsoft.com/v1.0/devices?$select=id,registeredOwners,registeredUsers"
I am getting only IDs information not other columns information like registeredOwners & registeredUsers.. What's the reason.

**Comment by FaithOmbongi** [comment]
> Thanks FaithOmbongi, just want to know if I use "https://graph.microsoft.com/v1.0/devices?$select=id,registeredOwners,registeredUsers" I am getting only IDs information not other columns information like registeredOwners & registeredUsers.. What's the reason.

Hi @Amty63, **registeredOwners** and **registeredUsers** aren't a property of devices but they're relationships or navigation properties as per [here](https://docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0#relationships). So they can't be retrieved in a `$select` query but through an `$expand` query (`devices?$expand=registeredOwners` or `devices?$expand=registeredUsers`). Please note only one relationship can be specified in a single `$expand` query as per [this](https://docs.microsoft.com/en-us/graph/query-parameters#expand-parameter).
