### ISSUE TITLE
Clarification about User.Read would be helpful

### ISSUE THREAD

**Issue by mrkeiths** [microsoftgraph/microsoft-graph-docs#16371]
Hello,
"Get a user" documentation lists User.Read among delegated permissions that can be assigned.  It's fair to include this permission but this permission only grants privileges to read the profile "of the signed in user".

I'd like to request that a remark be added to clarify when User.Read permission should be assigned and to advise that User.ReadBasic.All or User.Read.All be assigned if the ability to read other users is required.

The following link clarifies the scope of User.Read in the first sentence and would be helpful to include with "Get a User" documentation: [https://docs.microsoft.com/en-us/graph/permissions-reference#microsoft-graph-permission-names](url)

    Microsoft Graph permission names follow a simple pattern: resource.operation.constraint. For example, User.Read grants permission to read the profile **of the signed-in user**...

Thank you for your consideration,
Keith

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @mrkfor this useful suggestion. I've raised a PR to apply it to the docs.
