### ISSUE TITLE
Confirm `list deleted items` or `list deleted users`

### ISSUE THREAD

**Issue by kuhlaid** [microsoftgraph/microsoft-graph-docs#16389]
This page is confusing. The active left-hand menu item says `List deleted users`, however the main content title and text says `List deleted items` (as shown in the screenshot below). I'm looking for deleted items **within** a group (NOT deleted groups).
![image](https://user-images.githubusercontent.com/41551429/161323874-c63b19e4-8b74-4f6b-9533-985445d3144d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf76efc-5ca2-e829-1604-fa858179858a
* Version Independent ID: bbf2d629-8795-3d87-76de-f147489e4942
* Content: [List deleted items - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directory-deleteditems-list.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @kuhlaid for raising this issue. The **deletedItems** API is used to retrieve deleted directory objects, with only users, groups, and applications currently supported. It's one API used to filter by these sets of directory objects. (I've raised a PR to clear the title a bit). It isn't used to retrieve deleted items within a group.

Can you share what kind of deleted items within a group you're hoping to retrieve?

**Comment by kuhlaid** [comment]
There needs to be easier access to the recycle bin/deleted files of OneDrive. If you have hundreds or thousands of files that get moved to deleted status and placed in the recycle bin the only way I have found for users to access those files is through a web interface that is impossible to retrieve a full list of the deleted files. I was hopeful the Graph API would show deleted items/files from groups (being Office 365 groups). With that being said I'm not even sure now what groups the Graph API is referring to (are these user groups or 'Office 365 groups/teams') as it is not clear in docs?

**Comment by FaithOmbongi** [comment]
Hi @kuhlaid,

OneDrive is exposed through the [files set of APIs](https://docs.microsoft.com/en-us/graph/api/resources/onedrive?view=graph-rest-1.0). To restore a deleted file, please check out [driveItem: restore](https://docs.microsoft.com/en-us/graph/api/driveitem-restore?view=graph-rest-1.0&tabs=http) API. Though I see a note in the doc that restoring deleted files API currently works only with OneDrive personal.

For the case of the groups referred to in the [deletedItems ](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0&tabs=http) API, it's Microsoft 365 (previously Office 365) groups - doesn't have to have a team.
