### ISSUE TITLE
Risk History not getting the history

### ISSUE THREAD

**Issue by victoradmc** [microsoftgraph/microsoft-graph-docs#16407]
The Issue I am facing is simple:

After making a request to 
https://graph.microsoft.com/beta/identityProtection/riskyUsers/{ ID }/history

I'm not getting the correct list of riskyUsersHistoryItem, I'm getting an array with only one object inside of it, no matter which user I try to search. I do have users that are in the 'remediated' status, meaning that they were at risk in some point but the API call is not returning more than one item, which shows only the CURRENT status for the users.

In fact, the call to `riskyUsers/{user id}/history` and the call to `riskyUsers/{user id}` returns basically the same information, but the history one wraps it inside a array named 'value'.

Tried both the v1.0 and beta versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d21ea1d-b626-b1da-371e-29eb2ffa92a5
* Version Independent ID: 13a6c5d6-4a80-6000-0b4c-ae439dada7e1
* Content: [List history of riskyUser - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/riskyuser-list-history?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/riskyuser-list-history.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/riskyuser-list-history.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @victoradmc for raising this issue. Unfortunately, I'm currently unable to replicate it. 

- `/identityProtection/riskyUsers/{userId}` returns the details of the last risk state for the user.
- `/identityProtection/riskyUsers/41c34145-b83e-47c4-b832-aada58a9d84c/history` returns the collection of risk history data for the user, in the order of the latest updated date. The latest value will be similar to what's returned through the `/identityProtection/riskyUsers/{userId}` API, excluding the unsupported properties.

Is it possible that the user either had only one risk history instance or their other records are more than 30 days old? For the latter, please note that a P1 license only allows up to 30 days worth of risky history data to be retained by Azure AD. I'm raising a PR to indicate this in docs.

In case you can validate data that are available in the portal but you can't retrieve them through the API, kindly file this issue at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) and provide a request ID so the issue can be investigated. Unfortunately, this forum is only for documentation-related issues but such functionality issues are investigated at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html).
