### ISSUE TITLE
Samples for creating a bookmark doesn't work

### ISSUE THREAD

**Issue by inerle** [microsoftgraph/microsoft-graph-docs#16402]
The displayed examples for PowerShell or HTTP doesn't work. 
It seems that the JSON Body isn't up to date. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95a7e460-1fbd-1513-0917-0173c666c8eb
* Version Independent ID: dea2f07d-d773-5d40-ee7f-3ba19b1b552f
* Content: [Use the Microsoft Search API to manage administrative answers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/search-api-answers-overview?view=graph-rest-beta&preserve-view=true)
* Content Source: [api-reference/beta/resources/search-api-answers-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/search-api-answers-overview.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @jakeost-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@inerle appreciate your feedback. Are there any specific samples that didn't work?

**Comment by ag0059985** [comment]
this one "create bookmark" is not working.
https://docs.microsoft.com/en-us/graph/api/search-searchentity-post-bookmarks?view=graph-rest-beta&tabs=http#request

**Comment by jakeost-msft** [comment]
@ag0059985 it could be a few things. displayName and webUrl must be unique. If an existing bookmark has either the same displayName or the same webUrl the call will fail. 

Also, "reservedKeywords" must be unique. If a reserved keyword is matched, it will override all other keywords. If you want to make sure that a bookmark shows up for a particular keyword, make that a reserved keyword. Example: time sheet.

**Comment by ag0059985** [comment]
@jakeost-msft thanks so much, will try to create request body, which is unique.
