### ISSUE TITLE
Filter with startswith in PowerShell not working for Invoke-RestMethod API

### ISSUE THREAD

**Issue by Vickyk1** [microsoftgraph/microsoft-graph-docs#16422]
User tried the below URL to achieve, if a user has group membership to a particular group, however it just returns all groups.

$url = "https://graph.microsoft.com/v1.0/users/$upn/memberOf/microsoft.graph.group?$count=true&$orderby=displayName&$filter=startswith(displayName, 'Group_name')"

$groupacheck = (Invoke-RestMethod -Headers @{Authorization = "Bearer $($token)"; ConsistencyLevel = "eventual"} -Uri $Url -Method Get)

when i query with the starts with in PowerShell it gets me all the groups not only the filtered one. I even tried to use the graph module there also for this Get-MgUserMemberOf it is not there , but for Get-mguser it is available

Reference Doc - https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http#example-5-use-filter-and-odata-cast-to-get-groups-with-a-display-name-that-starts-with-a-including-a-count-of-returned-objects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9188ffdb-b7af-597d-9e0a-d92e75ff8e7d
* Version Independent ID: c4427823-3f37-dc4b-ac1e-b750cb633e23
* Content: [List memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http#example-5-use-filter-and-odata-cast-to-get-groups-with-a-display-name-that-starts-with-a-including-a-count-of-returned-objects)
* Content Source: [api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-memberof.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jeremy919** [comment]
I think this issue is discussed and resolved here https://stackoverflow.com/questions/69076658/using-filter-through-microsoft-graph-api-request.

From the link above:

Whenever a string literal uses double-quotes ("'s), PowerShell interprets it as expandable, meaning PowerShell will attempt to resolve and expand variable expressions (like $filter) when evaluating the string.

Use a backtick (`) to escape the $

**Comment by FaithOmbongi** [comment]
Thank you @Vickyk1 for raising this issue @Jeremy919 for providing the solution and the required guidance. Vicky, please check the [PowerShell quoting rules](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.2) for more guidance. Closing this issue.
