### ISSUE TITLE
Response not Correct

### ISSUE THREAD

**Issue by merglml** [microsoftgraph/microsoft-graph-docs#16436]
Response does not match the Example Response. 

Example Response is correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88e3ee4f-6439-bf24-a639-396a70e7f6cf
* Version Independent ID: 4be5dc0e-2d18-932a-bd89-52cae30de7c1
* Content: [Assign a connectorGroup to an application - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/connectorgroup-post-applications?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/connectorgroup-post-applications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/connectorgroup-post-applications.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @japere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @merglml for catching this error. I've raised a PR to correct the documentation.
