### ISSUE TITLE
Redirect URI - Postman v9.15.2 

### ISSUE THREAD

**Issue by rajyraman** [microsoftgraph/microsoft-graph-docs#16435]
I had to add only this redirectURI to the App Registration: https://oauth.pstmn.io/v1/browser-callback. Without this I was getting the error below. 

![image](https://user-images.githubusercontent.com/5035266/161908844-f0d0994a-9bd4-435a-be32-fa07901a37fc.png)

Once I added this redirectURI, I am able to get the token. This redirectURI is not mentioned in [Step 3](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/use-postman.md#step-3---create-an-azure-ad-application)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for reporting. I'll investigate and update ASAP.
