### ISSUE TITLE
We need a way to automate assignment and eligibility requests

### ISSUE THREAD

**Issue by pbo-top** [microsoftgraph/microsoft-graph-docs#16437]
Hi

We are working to automate our tenant setup as much as possible, both for recovery, but mostly to avoid errorprone undocumented UI interactions. The requirement for MFA on the assignment requests blocks this. Please consider to provide a script-first way into this like from pipelines running under service-accounts. Otherwise we really don't see the point in offering the API - when one has to manually use the GraphExplorer or similar to get past the MFA.
(this goes for the eligibility request as well, even though to docs does have mention MFA - one get an 403 on that as well)

Thanks,
Per

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afa14701-1e48-21a7-5e3b-6c7b6cb4811e
* Version Independent ID: 672e38a3-6a6c-b2a5-60e1-9881c80d875e
* Content: [Create unifiedRoleAssignmentScheduleRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/unifiedroleassignmentschedulerequest-post-unifiedroleassignmentschedulerequests?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/unifiedroleassignmentschedulerequest-post-unifiedroleassignmentschedulerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/unifiedroleassignmentschedulerequest-post-unifiedroleassignmentschedulerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @japere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @pbo-top for raising this issue. Would support for application permissions help you achieve your automation needs?

**Comment by pbo-top** [comment]
> Thank you @pbo-top for raising this issue. Would support for application permissions help you achieve your automation needs?

Hi

I'm a bit unsure what you mean by "support for application permissions". But if it were be possible to switch off the MFA requirement for the delegated user in the app permission for those specific endpoints, yes that would indeed help.

Regards
Per

**Comment by FaithOmbongi** [comment]
By application permissions, I mean for your [app to run without a user signed-in](https://docs.microsoft.com/en-us/graph/auth-v2-service). Let me get back to you on the plan for this support.

**Comment by mandardalvi** [comment]
@pbo-top -  the MFA setting is present on the role and not the request. Please update the your role settings in case you dont want the role activation to require MFA.

**Comment by pbo-top** [comment]
@mandardalvi - From your comment I could guess some configuration that the docs doesn't mention. The delegated user needs the "Privileged Role Administrator" as active assigned, and the user have to be excluded from MFA in Conditional Access.
With that, I was able to call the endpoint.

Getting the initial token reqeust working for a delegated user against Graph, does require some extensive searching on the net on itself, and this seems new undiscovered ground on top. I would suggest that the docs on the endpoinsts that do require a delegated user, gets a link to/contains some elaborate explanation.

@FaithOmbongi - There may be a good reason for the two endpoints to require a delegated user - in comparison to the rest of the Role Management section which can be called with Application perm type. But I can't see the need. As suggested above, at least the docs should be more elaborate.

Thanks,

**Comment by mandardalvi** [comment]
@pbo-top : Please check this documentation for how to configure role settings: https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-how-to-change-default-settings

**Comment by pbo-top** [comment]
@mandardalvi - Thanks, I am aware of the specific role policy settings for the Privileged Role Admin. But the delegated user may still be hit by MFA at directory level though, either when MFA has been set for all user or admin roles only. Hence the requirement for excempting him via Conditional Access in AAD also arises.

**Comment by FaithOmbongi** [comment]
Thank you @pbo-top and @mandardalvi for your feedback in this thread.

No updates identified for the docs for now but we'll provide additional guidance where possible.
