### ISSUE TITLE
Is it possible to access Project Online since it's built on SharePoint?

### ISSUE THREAD

**Issue by whitneyland** [microsoftgraph/microsoft-graph-docs#1644]
Is it possible to access Project Online since it's built on SharePoint?

**Comment by dmahugh** [comment]
Project Online is not currently accessible via Microsoft Graph. Thanks for your feedback!

**Comment by whitneyland** [comment]
thank you for the info.  I believe everyone would like some api that is comprehensive and consistent across all of these products, whether it's via graph or some other means.  hopefully it's well underway behind the scenes.
