### ISSUE TITLE
Wrong string quotes.

### ISSUE THREAD

**Issue by Worek** [microsoftgraph/microsoft-graph-docs#16444]
Hi.
I have discovered that in your tutorial you had made mistake in sample commands. All quotes were wrongly used, therefore commands could not be used. 
For example you are using string:
`"<div>....height="246"...</div>"`
that is not recognized as proper string with quotes by any language example you gave,
It should be 
`'<div>....height="246"...</div>'`
with single quote.

Please also repair indents in code example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caa6130b-e7ac-9795-9593-f0cef62ff0d4
* Version Independent ID: 7bf7c3d2-7693-7d24-e9c0-6f0c51cb1eaa
* Content: [Send chatMessage in a channel or a chat - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&tabs=powershell&fbclid=IwAR3cV0sH24SGEy0gU-JX8Ml_zAtytv3_-aciShHhyL-Rohw-7ssRjc_124w)
* Content Source: [api-reference/beta/api/chatmessage-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@Worek - We are investigating your query. We will inform you once we have any update.

**Comment by RamjotSingh** [comment]
The quotes used in the example are correct. Payload is JSON and requires `"` and not `'`

**Comment by Worek** [comment]
This is not correct. 
Simply copping commands given by you dosnt work. We need to change all quotes in order to make it work. 
My friend who is trying to learn from this docs had spend several days trying to figure out why its not working.

We are using powershell ISE, but i have checked in cmd as well. 
None accepts your commands.

**Comment by Nivedipa-MSFT** [comment]
@Worek - We have tested this using graph explorer.
In graph explorer and in postman its working fine.

**Comment by Worek** [comment]
This is Powershell docs therefore we are trying to use it in Powershel ISE and it doesn't accept this format.

**Comment by Nivedipa-MSFT** [comment]
@Worek - Could you please share the Powershell doc which you are referring?

**Comment by Worek** [comment]
@Nivedipa-MSFT The one that this issue is about? Its docs about Microsoft.Graph wich is a library used by Teams and Powershell to send rest messages....
https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http

**Comment by Nivedipa-MSFT** [comment]
@Worek - We will check and let you know the updates.
