### ISSUE TITLE
Create accessPackageResourceRequest with application permissions works for AD groups but not SPO sites

### ISSUE THREAD

**Issue by sergeyz7** [microsoftgraph/microsoft-graph-docs#16442]
As noted previously in a comment to the now closed issue #15381 , the _create accessPackageResourceRequest_ method when used with application permissions (as per current documentation) works for AAD groups but not SharePoint Online sites.

The client applicaton has got the required _Site.FullControl.All_ permission - but requests come back with the code _GetSitesAuthZDenied_ ('The caller is not authorized to get sites.').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec50888f-1fe5-5d73-3a4e-cfd698d6b455
* Version Independent ID: 4786d6a3-0108-20a2-d0fc-b1e727682d57
* Content: [Create accessPackageResourceRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageresourcerequests?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/entitlementmanagement-post-accesspackageresourcerequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Thanks for letting us know. We made an update recently to the service, and this issue should no longer be present.
