### ISSUE TITLE
Conflict error when sending teamActivityNotification.

### ISSUE THREAD

**Issue by constantinMavrodin** [microsoftgraph/microsoft-graph-docs#16469]
Hello,
When trying to send a notification to a user that have a team app installed as a personal tab and a channel tab at the same time, I receive the following error:
"Found multiple applications with the same AAD App ID '00000000-0000-0000-0000-000000000000' - a Teams Application ID is required to resolve which application is correct."

How can we set this "Teams Application ID" when creating the request:

```json
{
   "teamApplicationId":"c012da54-0d03-484c-9dd0-d884f0145812",
   "topic":{
      "source":"entityUrl",
      "value":"https://graph.microsoft.com/v1.0/teams/00000000-0000-0000-0000-000000000000/channels/19:pA4S0rIbWgOT3w2nlJIHKkjYX2rRmGezJ_zFKuUEkkQ1@thread.tacv2/tabs/94940278-8bfb-4e12-9d25-1541d802b537"
   },
   "recipient":{
      "@odata.type":"microsoft.graph.aadUserNotificationRecipient",
      "userId":"00000000-0000-0000-0000-000000000000"
   },
   "activityType":"userMention",
   "templateParameters":[
      {
         "name":"messageContext",
         "value":"a test value"
      }
   ]
}
```

Please note all GUID values were anonymized.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7e8ea77-74b9-50cc-43a9-eee7fa805e7a
* Version Independent ID: 7a3747ed-2b1c-9e1a-adb8-6d1fb8688a48
* Content: [team: sendActivityNotification - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-1.0&tabs=javascript)
* Content Source: [api-reference/v1.0/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-sendactivitynotification.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @eddie-lee-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by eddie-lee-msft** [comment]
You can use the 'teamsAppId' field.
