### ISSUE TITLE
ExtensionProperty id description

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/microsoft-graph-docs#16481]
All endpoints around extension attributes require the `objectID` of the service principal, and not the `appId` which is what I expected seeing the url.

Maybe you can better describe the required `ID` parameter that needs to be set in the path.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad2fa0a-381e-efd5-2030-b76fcdbc2436
* Version Independent ID: 04a78b65-ca47-9cdd-26a0-ab854fd33b51
* Content: [Create extensionProperty - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-extensionproperty?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-extensionproperty.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-extensionproperty.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @svrooij for this feedback. I've raised a PR to apply it and change the syntax URL to `/applications/{applicationObjectId}/extensionProperties`. I hope this helps to differentiate the IDs.

**Comment by svrooij** [comment]
@FaithOmbongi maybe also change this on the list, get and delete endpoints?

And maybe even mention that you are setting the extension properties on the service principal in the tenant, but then they are also available to other tenants if the approved that specific app.

**Comment by FaithOmbongi** [comment]
Hi @svrooij, I was offline for a long holiday weekend and couldn't respond sooner.

For the first - done. As for the 2nd part, let me first verify internally before I can apply the change.

**Comment by svrooij** [comment]
@FaithOmbongi wouldn't it make more sense to change the api, that you actually configure the extensions on the application (and backwards compatible on the service principal). Since the application id is also used in the actual extension anyway.

**Comment by FaithOmbongi** [comment]
> @FaithOmbongi wouldn't it make more sense to change the api, that you actually configure the extensions on the application (and backwards compatible on the service principal). Since the application id is also used in the actual extension anyway.

Hi @svrooij, for this feature request, I recommend that you submit it @ the [developer platform ideas channel](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) so other developers can amplify your voice and the idea can be put up for consideration.

**Comment by svrooij** [comment]
@FaithOmbongi I'm not going to do that, that has never solved an issue I was facing.

According to [Microsoft Web API design best practices](https://docs.microsoft.com/en-us/azure/architecture/best-practices/api-design#what-is-rest) an url should be structured. eg. We are talking **applications** here. So the url is `.../applications` for the list and `.../applications/{applicationId}` for a single application. And `.../applications/{applicationId}/extensions` for a list of extensions that belong to that application.

In the **Microsoft Graph** the "application id" is not the ID of the application, it rather is the ID of the service principal belonging to the application in that specific tenant. So according to Microsoft' own best practices the id should be the application ID or the url should be changed to `.../servicePrincipals/{spID}/extensions`
