### ISSUE TITLE
Need to update the ServiceNow external link 

### ISSUE THREAD

**Issue by Visinghr** [microsoftgraph/microsoft-graph-docs#16498]
ServiceNow link on this page is not correct and does not take the user to the correct locations. 

[Microsoft Graph Security API alert ingestion integration](https://docs.servicenow.com/bundle/orlando-security-management/page/product/secops-integration-sir/secops-integration-ms-graph/concept/ms-graph-about.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae272b3b-0363-dbb7-d04c-364058e1248f
* Version Independent ID: 710ad43f-8714-ef8c-15b6-c7ec44fbf0d3
* Content: [Security solution integrations using the Microsoft Graph Security API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/security-integration#list-of-connectors-from-microsoft)
* Content Source: [concepts/security-integration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/security-integration.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**[Microsoft Graph Security API alert ingestion integration](https://docs.servicenow.com/bundle/orlando-security-management/page/product/secops-integration-sir/secops-integration-ms-graph/concept/ms-graph-about.html)

**Comment by lramosvea** [comment]
@preetikr is this the right link? https://docs.servicenow.com/bundle/orlando-security-management/page/product/secops-integration-sir/secops-integration-ms-graph/concept/ms-graph-about.html

If so, could you please update this doc using the right link?

Thanks

**Comment by lramosvea** [comment]
@Danielabom seems like this is the link we need for ServiceNow... Shoul you confirm with @preetikr ?https://docs.servicenow.com/bundle/quebec-security-management/page/product/secops-integration-sir/secops-integration-ms-graph/concept/ms-graph-about.html

**Comment by Danielabom** [comment]
> * security-integration.md

Hi @lramosvea, I checked with the persona that's now in charge of this topic, Amar Patel and he agreed with the change.
