### ISSUE TITLE
Unable to get information about public teams

### ISSUE THREAD

**Issue by RoelVB** [microsoftgraph/microsoft-graph-docs#16512]
We used to be able to get information about a public Team (without being a member) when calling:
`https://graph.microsoft.com/v1.0/teams/<some-team-guid>`

But now this results in an error:
```json
{
    "error": {
        "code": "Forbidden",
        "message": "Failed to execute Skype backend request GetThreadRequest.",
        "innerError": {
            "message": "Failed to execute Skype backend request GetThreadRequest.",
            "code": "AccessDenied",
            "innerError": {},
            "date": "2022-04-13T12:02:08",
            "request-id": "5797380b-2f7b-4b1b-a95c-def2004addfc",
            "client-request-id": "d1e3979c-055b-649a-330b-64c98cb54719"
        }
    }
}
```

I'm not sure when this changed and I cannot find anything about this.
Is there another way to get information about a public Team?

> Note: Getting the related group (e.g. `https://graph.microsoft.com/v1.0/groups/<some-team-guid>`) does work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c84a5f8-fe8a-615d-4467-9e2dc2d72f42
* Version Independent ID: 8f0f99e3-a8bb-858e-9f1a-92f2435839a7
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RoelVB** [comment]
@Meghana-MSFT thanks you for taking a look.
I forgot to mention that is does work for admins, but not for users.

It's getting stranger. I did some more testing on different tenants with different users.

**Tenant A**
- An user that exists for about 2 years can get information about Teams it's not a member of (even private ones)
- A new user (also with an E5 license) is unable to get information about Teams it's not a member of (getting the error mentioned above)

**Tenant B**
- An user that exists for almost 10 years is unable to get information about public Teams (same error)

**Comment by Meghana-MSFT** [comment]
We got an update from the engineering team - 

GET /teams/id is accessible only to team member or owner or admin unlike /groups/id. Only a person who is part of the team's roster or is an Admin (Global Admin or Teams Service Admin or AU Admin) can see anything under GET /teams/team-id/.
