### ISSUE TITLE
Values for Status Property on Invitation Manager Page

### ISSUE THREAD

**Issue by zaedwa** [microsoftgraph/microsoft-graph-docs#1651]
Issue: 
In the Invitation Manager document, there is no mention of the "Accepted" value for the status property. I have not yet received the "Completed" or "InProgress" status when utilizing this API. There is no explanation of why an invitation is automatically Accepted. See example response, edited for brevity.

{  
"@odata.context":"https://graph.microsoft.com/beta/$metadata#invitations/$entity",
"id":"29272590-150c-40d8-a14d-34fbc87615e0",
## **"status":"Accepted",**
}

Article:

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/invitation

**Comment by elisolMS** [comment]
I think this issue is based on an old implementation that has since changed.  If you're still seeing this, please re-open with the details of the call so we can investigate.
