### ISSUE TITLE
How do I set owner for app template instantiations?

### ISSUE THREAD

**Issue by scastria** [microsoftgraph/microsoft-graph-docs#16545]
I have Application.ReadWrite.OwnedBy which allows me to use Graph API to instantiate an application from a template.  However, both the Application and Service Principal are created with NO OWNER.  Therefore, I can't modify them after they are created.  And, of course, I can't add an Owner because I am not the Owner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2bcec4-f3cb-29ad-1f74-4b2419d98bac
* Version Independent ID: 97634873-8d0d-1e6c-01a1-cf03082c611a
* Content: [applicationTemplate: instantiate - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/applicationtemplate-instantiate?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/applicationtemplate-instantiate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/applicationtemplate-instantiate.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @luleonpla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @scastria for raising this issue and my apologies for the delayed response. You/the app can modify the service principal and assign it an owner, but you must grant the app the Application.ReadWrite.All and Directory.Read.All permissions.
