### ISSUE TITLE
Document the `$search` of `people` query

### ISSUE THREAD

**Issue by viebel** [microsoftgraph/microsoft-graph-docs#1654]
Microsoft graph provides a `people` query that can receive `$search` url parameter e.g.
`https://graph.microsoft.com/beta/me/people/?$search="topic: work"`

- what search parameters are supported in the `people` query?
- what is the exact meaning of the `topic` filter?

**Comment by dmahugh** [comment]
You can find documentation for the $search query parameter here: [https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters](https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters)

**Comment by viebel** [comment]
Hi @dmahugh 
It's not clear from the documentation what is the meaning of topic.
Could you please elaborate on that?

**Comment by cloudguy-pro** [comment]
I would like to know where the "topics" are maintained and if the users can manipulate them...

**Comment by dmahugh** [comment]
The topics aren't a maintained list, but rather are generated by an algorithm that looks to your conversation history. We're looking into how to address this better in the documentation, but for now you can find some good background info on this StackOverflow question (see Marc LaFleur's responses): [https://stackoverflow.com/questions/46025166/in-microsoft-graph-api-what-filters-are-supported-in-people-search-query](https://stackoverflow.com/questions/46025166/in-microsoft-graph-api-what-filters-are-supported-in-people-search-query)

**Comment by cloudguy-pro** [comment]
But unfortunately, this does not really reflect the actual skills of people which would be of more use for people/skill search. You can vote for this feature in the uservoice here https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/20299153-ability-to-filter-on-collection-type-properties-e

**Comment by angelgolfer-ms** [comment]
Hi @viebel , @cloudguy-pro ,
The topic data that is searched is basically a collection of words that have been used most by users in email conversations, and Microsoft creates an index for it to facilitate fuzzy searches.
A search like the following:
GET https://graph.microsoft.com/v1.0/me/people/?$search="topic:windows"
is a fuzzy search in this topic data index. Topics in this data are context free, so a search for "windows" can include instances that mean the Windows operating system, an opening in a building wall, or other definitions.

Hope this helps.

Angelgolfer-ms

**Comment by viebel** [comment]
Thanks @angelgolfer-ms
