### ISSUE TITLE
The response column of getTeamsUserActivityUserDetail (v1.0) api has been added but not in the document and changelog.

### ISSUE THREAD

**Issue by akkomats** [microsoftgraph/microsoft-graph-docs#16549]
The response column of getTeamsUserActivityUserDetail (v1.0) api has been added but not in the document and changelog.

GET https://graph.microsoft.com/v1.0/reports/getTeamsUserActivityUserDetail(period='D7')

Added column in March.
- Urgent Messages
- Post Messages
- Reply Messages

Added column in the last week.
- Tenant Display Name
- Shared Channel Tenant Display Names

Document URL
https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivityuserdetail?view=graph-rest-1.0
ChangeLog
https://developer.microsoft.com/en-us/graph/changelog/?filterBy=Microsoft%20365%20usage%20reports

Would you please update the document and changelog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa64daf9-bfd7-bfe0-0a4a-cec6b062a192
* Version Independent ID: a2b14964-5512-9183-9cc8-ad00e55e146d
* Content: [reportRoot: getTeamsUserActivityUserDetail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivityuserdetail?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @sarahwxy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as the docs have been updated. Thanks.
