### ISSUE TITLE
Access Denied on Graph call

### ISSUE THREAD

**Issue by Oddleif** [microsoftgraph/microsoft-graph-docs#1656]
I am having a similar issue as #587. Tried to follow the steps on adding read permission on the root site collection but no luck. I assume what you mean by root site permissions was "https://{tenantid}.sharepoint.com"? Any other suggestions?

{error: {code: "UnknownError", message: "401 UNAUTHORIZED",…}}
error
:
{code: "UnknownError", message: "401 UNAUTHORIZED",…}
code
:
"UnknownError"
innerError
:
{request-id: "b09a21de-505d-4cbe-9a40-354c911d08b9", date: "2017-09-05T07:45:51"}
message
:
"401 UNAUTHORIZED"

**Comment by marych** [comment]
@Oddleif - access was denied because your organization has SharePoint configured to only allow access from specific network locations (IPs). The calls from MS Graph are currently getting rejected due to that policy.

**Comment by Oddleif** [comment]
@marych Ok. Thanks for clarifying.

**Comment by Oddleif** [comment]
@marych Just a follow up. Does this mean we need to open up for specific Microsoft Graph IP ranges? In that case is such a list published? Or do we need to disable IP location filter completely?

**Comment by marych** [comment]
To make it work reliably you'd need to disable the IP location filter completely.

**Comment by Oddleif** [comment]
@marych What will it take to make it work "unreliably"? And can you share something on whether or not this a feature that will be supported in the near future?

**Comment by marych** [comment]
You could potentially whitelist IPs returned by DNS for graph.microsoft.com, but that set will be changing over time, so it wouldn't work reliably. We're considering a feature to support SharePoint policy evaluation against client IP passed by MS Graph, but there is no specific plan or ETA yet.

**Comment by Oddleif** [comment]
@marych Do you know if an official list of those IP addresses is published somewhere? I tried to search for it, but no luck.

In any case, having the MS Graph mirror the SharePoint policy is really what we are after. As we build applications directly on top of he MS Graph, environments IP location filter requirements will be a real issue for us.
