### ISSUE TITLE
Graph API for Recommendations

### ISSUE THREAD

**Issue by ShilpaSharePoint** [microsoftgraph/microsoft-graph-docs#16566]
Looking for Graph API to read M365 Recommended content. If Graph API is not available, are there any alternative solution; It would be great if you can provide me documentation link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@ShilpaSharePoint , do you mean the content that you get in Edge when you click "Microsoft 365", as described in this [article](https://support.microsoft.com/en-us/office/the-microsoft-365-tab-in-edge-db32c45f-7f35-479d-b4a8-f015b55333dc)?

If so and if you'd like to use a Microsoft Graph API to get files that are most recently used or shared with a user, as an example, take a look at the overview topic for the insights API: [Overview of item insights](https://docs.microsoft.com/en-us/graph/item-insights-overview).

Hope that helps.

**Comment by ShilpaSharePoint** [comment]
Hi Angel,
Thanks for the response. I am not looking for the  content that you get in Edge when you click "Microsoft 365"
As per the image attached. Trying to develop SPFX webpart which displays Microsoft recommended content based on technology.

![image](https://user-images.githubusercontent.com/102510249/164154439-bfb5db2c-78ee-4b68-b945-2a0c46f08af1.png)

**Comment by angelgolfer-ms** [comment]
Hi @ShilpaSharePoint , thanks for the clarification. I suggest you check out [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/m365) and apply a SharePoint tag. They are better resourced to help answer a wider range of customer questions :-)
Cheers!
