### ISSUE TITLE
Update Application: Add documentation for updating spa redirect URIs

### ISSUE THREAD

**Issue by DanielArthurUK** [microsoftgraph/microsoft-graph-docs#16581]
There is no mention of `spa` in the request body for the Update Application API. However, it is valid to include something like this to the request body:

```json
...
    "spa": {
      "redirectUris": ["http://localhost:8000"]
    }
...
```

It was quite difficult to find out that we could do this with the API. Is it possible to please add this to the documentation?

Many thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6afab3-9682-0f8e-0441-2adfde3f84ef
* Version Independent ID: 6eee450a-b6d0-0908-0392-00e01d412185
* Content: [Update application - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-update.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @DanielArthurUK for catching this oversight. Yes, **spa** is an updatable property. I've raised a PR to add it to the list of updatable proeprties.
