### ISSUE TITLE
[Germany] how can I get latest update of graph in Germany

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#1660]
Hello:

Some APIs are not supported in graph on Germany endpoint:
```
 https://graph.microsoft.de
```

like 
```
GET https://graph.microsoft.com/v1.0/me/mailFolders/{id}/messages/delta
```

Is there a forum to discuss this?

thank you!

**Comment by VenkatAyyadevara-MSFT** [comment]
@Jeff Sakowicz<mailto:Jeff.Sakowicz@microsoft.com> @Sripresanna Sripresanna<mailto:sripress@microsoft.com> Can you please take a look and respond?  Why would we not support Delta Query on MS Graph in BlackForest?

Thanks,
Venkat

**Comment by joewutaiwan** [comment]
Thank you for help
enclosed the response
```
GET https://graph.microsoft.de/v1.0/users/{user_id}/mailFolders/delta
```
```
cache-control →private
client-request-id →edea28e0-2231-48ba-a45f-e29b0e55aeed
content-type →application/json
date →Thu, 07 Sep 2017 07:28:36 GMT
duration →237.4811
request-id →edea28e0-2231-48ba-a45f-e29b0e55aeed
transfer-encoding →chunked
x-ms-ags-diagnostic →{"ServerInfo":{"DataCenter":"Germany Northeast","Slice":"SliceA","ScaleUnit":"001","Host":"AGSFE_IN_1","ADSiteName":"DNE"}}
{
    "error": {
        "code": "ErrorInvalidIdMalformed",
        "message": "Id is malformed.",
        "innerError": {
            "request-id": "edea28e0-2231-48ba-a45f-e29b0e55aeed",
            "date": "2017-09-07T07:28:36"
        }
    }
}
```

**Comment by joewutaiwan** [comment]
Hello, guys:

Do you have any updates with the issue?

Thanks

**Comment by joewutaiwan** [comment]
Hello, @VenkatAyyadevara-MSFT  @jesakowi 

Is there any alternative to this issue?

Or it is just a bug?

Really thank you for help!

**Comment by baywet** [comment]
Hi @joewutaiwan thanks for reaching out and really sorry for the delay in the answer.
National clouds have different release cadences and might have a different feature set than the public cloud.
If there are features available in public clouds that are missing in the national clouds you should post it on uservoice. (details following in a second comment)
Currently only China's national cloud and the public cloud support delta queries.
