### ISSUE TITLE
todo task api does not contain list group

### ISSUE THREAD

**Issue by lee88688** [microsoftgraph/microsoft-graph-docs#16606]
list group contains many lists, but recent todo task api does not contain this list's group which it belongs to. an individual list group api is not provided neither.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5214c858-f451-267d-bce1-5b9442f7fd6c
* Version Independent ID: bb4e54db-730a-c43b-d02b-4f253cf3390f
* Content: [Use the Microsoft To Do API - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/todo-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/todo-overview.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @avijityadav
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chrissyast** [comment]
+1. It would be massively helpful to have: 

* a GET for all groups `.../me/todo/groups`
* a GET for all lists within a group `.../me/todo/groups/{groupId}/lists`
* the id of the containing group to be exposed on the [`todoTaskList`](https://learn.microsoft.com/en-us/graph/api/resources/todotasklist?view=graph-rest-1.0) object

**Comment by chrissyast** [comment]
> Is there any kind of official feature request area for this API?

I've found it. Anyone who is interested please upvote this idea 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-functionality-to-query-todo-api-with-groups/idi-p/3778681
