### ISSUE TITLE
Unable to retrieve role management policies for a specific scope and role definition with the Azure REST API

### ISSUE THREAD

**Issue by glennvanrymenant-tc** [microsoftgraph/microsoft-graph-docs#16615]

**Comment by glennvanrymenant-tc** [comment]
@FaithOmbongi regarding your response below, I tried copying your exact query in Postman and PowerShell (Invoke-RestMethod) but even then the API returns all role management policies for that scope...

requestId without special characters converted: 7d5fc511-f400-48a3-87ba-647981c23830
requestId for exact copy: 01f5b512-da15-4cd8-bb40-697204b3d492


_Hi @glennvanrymenant-tc, OK, I've confirmed that the $filter as documented in this article https://docs.microsoft.com/en-us/rest/api/authorization/privileged-role-policy-rest-sample should work. 

Please see the following screenshot and try to correlate it with your request
![MicrosoftTeams-image](https://user-images.githubusercontent.com/14026935/164499842-66acedd2-87cf-4af3-9aa7-b99c6c433f78.png)

In case you're still hitting an error, share your request ID for further investigation.

_Originally posted by @FaithOmbongi in https://github.com/microsoftgraph/microsoft-graph-docs/issues/15910#issuecomment-1105403889__

**Comment by FaithOmbongi** [comment]
Hi @glennvanrymenant-tc - checking...

**Comment by FaithOmbongi** [comment]
Hi @glennvanrymenant-tc,

Thank you for your patience. Unfortunately, this has been confirmed as a product bug. But the good news is - the team's currently working on a fix and the issue should be resolved soon. Try re-running the query sometime mid-next week to confirm whether it's resolved.

**Comment by glennvanrymenant-tc** [comment]
Hi @FaithOmbongi, thank you for the feedback, any chance I could get ping here once the fix has been deployed? I also noticed that calls to this endpoint were rather slow compared to other Azure REST API calls - is that going to be improved now as well?

**Comment by FaithOmbongi** [comment]
Hi @glennvanrymenant-tc - yep, I can get back to you once the fix is deployed. 

On the slow response times, let me share this report with the team so they can investigate and resolve it as well.

**Comment by glennvanrymenant-tc** [comment]
@FaithOmbongi any update?

**Comment by FaithOmbongi** [comment]
Hi @glennvanrymenant-tc, let me get back to you at the end of the week.

**Comment by FaithOmbongi** [comment]
Hi @glennvanrymenant-tc, the issue has been resolved. Can you also test on your end and advise?

**Comment by FaithOmbongi** [comment]
Hi @glennvanrymenant-tc - the issue has been resolved and we're now closing this issue.
