### ISSUE TITLE
How to pass the token in when I initiate the client just once

### ISSUE THREAD

**Issue by xipeter** [microsoftgraph/microsoft-graph-docs#16625]
Hi Dear,

This is my code, if I only initiate one client, how can I pass the access token, since it'll be expired anyway, thanks!

   public static GraphServiceClient<Request> getGraphClient(String accessToken) throws ClientException {
        if (client == null) {
            client = GraphServiceClient.builder()
                    .authenticationProvider(new MsalGraphAuthenticationProvider(accessToken))
                    .buildClient();
        }

        return client;
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aef52833-8b23-b9cd-4337-73eec3c34f4d
* Version Independent ID: 9b012e4f-93b3-bda8-0e35-1c9c6326295c
* Content: [Create a Microsoft Graph client - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=CS)
* Content Source: [concepts/sdks/create-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/create-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Berndatno** [comment]
This is what I am doing so far. I did have written a few of API client applications. I stored the token in a plain text file, read the file when I need to initialize a client. Some tokens expire very often, e.g. 30 days, in this case, I call the method to request a new token, and write the token received to a file.

For Microsoft graph, I really have the issue to get the token (right now, I can get the temp token via https://developer.microsoft.com/en-us/graph/graph-explorer within my personal account), I can call API method to post, and get the calendar for my personal office365 account. However my application is intended to post event for my organization. So I have to register the application without user. For such non-web application, there is no returnURL, no URI,  I really have the issue when request the access token. Do you know what the value for scope  should be used (&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default)?

**Comment by MIchaelMainer** [comment]
Can you tell us where you get MsalGraphAuthenticationProvider?
What documentation and tutorials have you tried?

You won't be passing in an access token. The authentication provider will get the token for you.

**Comment by xipeter** [comment]
I created one as the following
/**
     * Our Msal Graph Authentication Provider class. Required for setting up a
     * GraphServiceClient. It extends BaseAuthenticationProvider which in turn implements IAuthenticationProvider.
     */
    private static class MsalGraphAuthenticationProvider extends BaseAuthenticationProvider {

        private String accessToken;

        /**
         * Set up the MsalGraphAuthenticationProvider. Allows accessToken to be
         * used by GraphServiceClient through the interface IAuthenticationProvider
         */
        public MsalGraphAuthenticationProvider(String accessToken) {
            this.accessToken = accessToken;
        }

        /**
         * This implementation of the IAuthenticationProvider helps injects the Graph access
         * token from Azure AD into the headers of the IHttp request used by GraphSDK.
         *
         * uses contextAdapter to get the latest access token from context
         * -> make sure you're updating AT in context with AuthHelper.acquireTokenSilently() before each API call.
         *
         * @param requestUrl the outgoing request URL
         * @return a future with the token
         */
        @Override
        public CompletableFuture<String> getAuthorizationTokenAsync(@Nonnull final URL requestUrl) {
            return CompletableFuture.completedFuture(this.accessToken);
        }
    }

Is that the problem? @MIchaelMainer

**Comment by MIchaelMainer** [comment]
Okay, I now see that this is for Java. I don't see a problem, but that doesn't mean there isn't one. 

Why are you implementing that yourself instead of using the Java identity library? I'd suggest that you take a look at https://github.com/microsoftgraph/msgraph-training-java for an example implementation. 

For future reference, questions like this should be posted to Microsoft Q&A and tagged with one of [microsoft-graph-*](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) tags.

**Comment by xipeter** [comment]
@MIchaelMainer  Sorry for the confusion.
I actually followed one sample code somewhere from Microsoft, in my case, I need to use the delegated authentication flow to get the token.
