### ISSUE TITLE
Mention that the licenseAssignmentStates property currently has no delta support

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-docs#16690]
While the "licenseAssignmentStates" property can be selected when calling /users/delta, it is not currently supported, so it would be good if the documentation mentioned this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dcda67c-9d6f-6732-f454-c2d6e02d886f
* Version Independent ID: f23af4a1-bf3c-2ef1-a94f-79be31ea6618
* Content: [user: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/user-delta.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @manuel-falcao-magalhaes for raising this issue. I'm sorry I don't understand. Do you mean that any changes to the license state won't be reflected in a `?users/delta` response object?
