### ISSUE TITLE
credentialUserRegistrationDetails Report Sync Time?

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/microsoft-graph-docs#16867]
Is there a known Report sync time? I would like to know how long does it take from a user registering MFA until it shows up here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786282cc-2e01-7a67-bff8-7fdfc069d8f3
* Version Independent ID: 56775e93-d8b0-9fda-88ce-b6dd762a11c5
* Content: [List credentialUserRegistrationDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @MichaMican - let me confirm this and get back to you.

**Comment by besiler** [comment]
@MichaMican , you should see updates to a user's MFA methods showing up within 1d on that API. However, we recommend that you use userRegistrationDetails instead: https://docs.microsoft.com/en-us/graph/api/resources/userregistrationdetails?view=graph-rest-beta 

UserRegistrationDetails will be the source of truth going forward for MFA status for users

**Comment by MichaMican** [comment]
Any updates on this? (@besiler )

**Comment by MichaMican** [comment]
Can you please clarify which sync times are present on the UserRegistrationDetails endpoint you suggested? Is it updated there more often or does it also have an update cycle of 1d? 

(@besiler  @FaithOmbongi )

**Comment by FaithOmbongi** [comment]
My apologies @MichaMican for the delayed response. Yes, the data should be updated within 1 day. As for when to expect the /userRegistrationDetails endpoint in v1.0, unfortunately, I'm unable to provide a date. You can subscribe to the [Microsoft Graph changelog](https://developer.microsoft.com/en-us/graph/changelog/?search=) to get notified when the object is available in v1.0.
