### ISSUE TITLE
Link to Microsoft Graph PowerShell SDK is broken

### ISSUE THREAD

**Issue by joshtransient** [microsoftgraph/microsoft-graph-docs#16871]
In the second paragraph of this page, the link to "Microsoft Graph PowerShell SDK" is broken. It points to a .md file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9eead3-fd14-629f-dd6d-55e0c51d74ff
* Version Independent ID: cc096658-8f79-45c2-9d42-69e4fe9a3a49
* Content: [Make API calls using the Microsoft Graph SDKs - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS)
* Content Source: [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/create-requests.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Hi @isvargasmsft could you please help updating this link? It seems like ".md" part needs to be removed

**Comment by isvargasmsft** [comment]
@jasonjoh Do you know what the correct link is? Both links to powershell are broken in the second paragraph. And it is not the .md part.

**Comment by lramosvea** [comment]
@isvargasmsft These links work for me:
https://docs.microsoft.com/en-us/powershell/microsoftgraph/get-started
https://docs.microsoft.com/en-us/powershell/microsoftgraph/navigating

**Comment by jasonjoh** [comment]
Linked PR updates the second link. Verified on staging that the links work after this fix.
