### ISSUE TITLE
Inadequate requirements

### ISSUE THREAD

**Issue by markcms** [microsoftgraph/microsoft-graph-docs#16918]
I've created an app with appropriate permissions, but am receiving the response:

AADSTS500011: The resource principal named /v1.0/communications/callRecords/getDirectRoutingCalls(fromDateTime=2022-05-10,toDateTime=2022-05-16) was not found in the tenant named XXX. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

The admin (me) has installed the app, given consent and has the documented permissions. I've also confirmed the request is going to the right tenant.

Other endpoints work fine.

Seems to be that either the documentation is incomplete, or the endpoint is broken. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2db24412-509c-c456-1501-36b92e334740
* Version Independent ID: f7c55985-8bab-e3f7-1681-5d4078f90f71
* Content: [callRecord: getDirectRoutingCalls - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getdirectroutingcalls?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/callrecords-callrecord-getdirectroutingcalls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @williamlooney
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by williamlooney** [comment]
@SanderSade - Can you take a look?
