### ISSUE TITLE
Example 3 response has Canary endpoint in the odata context 

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#16924]
We should not show Canary in any examples.  Please fix to be public endpoints and versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7a6bcab-6c5a-8829-5f1c-725f06683b8c
* Version Independent ID: 61203b25-0162-5022-7a0f-c48fbbc40acb
* Content: [Get teamsAppIcon - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/teamsappicon-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamsappicon-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @jecha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@dkershaw10 - We are investigating your query. We will get back to you once we have any update.

**Comment by pruthvi-ustepalle** [comment]
This is fixed - https://docs.microsoft.com/en-us/graph/api/teamsappicon-get?view=graph-rest-beta&tabs=http#response-3
