### ISSUE TITLE
roleEligibilityScopes does not support expanding DirectoryScope

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/microsoft-graph-docs#16936]
![image](https://user-images.githubusercontent.com/15258962/168922463-58fc0144-5acd-42a5-8cff-d6ef78a0b023.png)
![image](https://user-images.githubusercontent.com/15258962/168923072-7bd960dd-9e74-49b9-9373-152d098364fd.png)

This works on the beta API and may be a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d967eb8-ec6b-8496-6a6d-74adaf4c645e
* Version Independent ID: b8db8a3e-dade-c3d5-2c95-cd3cc4afb7a3
* Content: [unifiedRoleEligibilitySchedule resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/unifiedroleeligibilityschedule?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/unifiedroleeligibilityschedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/unifiedroleeligibilityschedule.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @rkarim-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JustinGrote** [comment]
@FaithOmbongi thank you, are you doing it with an admin user? It happens with an unprivilieged user
![image](https://user-images.githubusercontent.com/15258962/169122422-e6e5c4ff-98d2-4aad-990e-1408e38805d6.png)

**Comment by JustinGrote** [comment]
Switch it to beta and it works fine
![image](https://user-images.githubusercontent.com/15258962/169122642-a86f54cc-8481-4802-b4f7-e12d187bcb03.png)

**Comment by FaithOmbongi** [comment]
Hmm, still not able to replicate it. I've tried it with a user with Global Reader eligibility and another without any role eligibilities but my queries against v1.0 are successful either way.

   

> <img width="679" alt="image" src="https://user-images.githubusercontent.com/14026935/169240150-6b9b7d9e-d73e-46e9-b58b-920415584b2c.png">


Let me share your request IDs to see if anything can be found there. 

cc @rkarim-ms, @mandardalvi to help out.

**Comment by FaithOmbongi** [comment]
Hi @JustinGrote - Thank you for your patience. Unfortunately, this has been identified as a product bug but also an edge case, and an internal work item has been opened. We, however, don't have an ETA for its resolution. 

I don't have a better suggestion than to use the LIST/GET APIs as a workaround, and filter by the signed-in user's principalId to emulate the filterByCurrentUser function.

Because this forum is only for documentation-related issues, I'll close the issue here.

**Comment by JustinGrote** [comment]
@FaithOmbongi thanks for your assistance.
