### ISSUE TITLE
Missing Resources from Change Notification Documentation

### ISSUE THREAD

**Issue by colinfike** [microsoftgraph/microsoft-graph-docs#16931]
I noticed that this page https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0 does not mention that we can subscribe to `calendar` resource change notifications. This functionality is available on the Outlook API and (as far as I can tell from my testing) it is actually available on the Graph API now. This is different than subscribing to notifications for events on a calendar, just to be clear.

Is this a case of the documentation being out of date or are `calendar` change notification not officially supported on the Graph API? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/webhooks.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @Jumaodhiss
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @Harini84, could you please confirm this and help to close the doc gap if confirmed? Thanks.

Adding @isvargasmsft for visibility.

**Comment by colinfike** [comment]
Gentle bump, just wondering if we could get a response about this because we are currently migrating from the Outlook API to the Graph API and this will potentially inform if there is new functionality we will need to add to support that.

**Comment by iamgirishck** [comment]
Hi @colinfike, apologies for the delay. Could you clarify what you mean by calendar change notifications. Are you referring to changes to calendar events? You can refer or delta changes to calendar events- https://docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http

**Comment by colinfike** [comment]
I am not referring to changes to calendar events. I am specifically wondering about notifications for changes to the calendars themselves such as a new calendar being added, a calendar being renamed, etc. On the Outlook API we do this by subscribing to the `/calendars` resource, something like `https://outlook.office.com/api/v2.0/sampleemail@outlook.com/calendars` (I don't have the actual resource in front of me at the moment).

This is not included in the aforementioned docs for the Graph API but if we create a subscription with the `users/sampleemail@outlook.com/calendars` as the passed `resource` parameter, we do get those notifications as expected if I change the name of one of my calendars/etc.

I would like to confirm that those notifications are fully supported so we can use them in production in case these notifications are in development or something similar.

**Comment by keylimesoda** [comment]
Hi @colinfike , you can see the list of resources that support change notifications here:  https://learn.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0

We do support Outlook Event resources, but Calendar resources are not currently wired up to receive change notifications.

@abheek-das , are you able to review this feature request?

**Comment by keylimesoda** [comment]
Issue answered in above response.
