### ISSUE TITLE
Link to "Known Issues" redirects to a "#pagenotfound" error

### ISSUE THREAD

**Issue by RyanTaite** [microsoftgraph/microsoft-graph-docs#1694]
Issue: On the [Changelog](https://developer.microsoft.com/en-us/graph/changelog) web page for the Microsoft Graph there is a link to known issues:  https://developer.microsoft.com/en-us/graph/known_issues

This link takes you to https://developer.microsoft.com/en-us/graph/known_issues#pagenotfound where it says 

> Sorry, we couldn't find that page.

Article: https://developer.microsoft.com/en-us/graph/changelog

**Comment by Lauragra** [comment]
Thanks for pointing that out. The link does work correctly when you access the page from this URL: https://developer.microsoft.com/en-us/graph/docs/concepts/changelog 

It looks like you have an old URL. Can you let me know how you navigated to this link: https://developer.microsoft.com/en-us/graph/changelog?

**Comment by RyanTaite** [comment]
Looks like I got there from this MSDN blog: https://blogs.msdn.microsoft.com/aadgraphteam/2016/07/08/microsoft-graph-or-azure-ad-graph/ in the "Microsoft Graph closing the gap with Azure AD Graph" section

Which is the first result for me when I Google search for:
> ms graph or aad graph

**Comment by Lauragra** [comment]
Okay, thanks! We'll implement a redirect from https://developer.microsoft.com/en-us/graph/changelog to the new URL.

**Comment by RyanTaite** [comment]
That's neat! Thanks!

**Comment by Lauragra** [comment]
The redirect was implemented and published; sorry for the delayed notice. Closing this issue. Thanks!
