### ISSUE TITLE
GET Contacts API on Subscription started throwing "Missed" event in LifeCycleNotificationURL

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs#16969]
GET Contacts API on Subscription started throwing "Missed" event in LifeCycleNotificationURL .

Looks like a Bug since multiple people are reporting the same.

All other endpoints works as expected however only problem is with Contacts API

POST https://graph.microsoft.com/v1.0/subscriptions/

{
"changeType": "updated",
"notificationUrl": "https://abc.azurewebsites.net/api/GraphNotificationHook?",
"lifecycleNotificationUrl":"https://abc.azurewebsites.net/api/GraphNotificationHook?",
"resource": "users/c847a04c-dae5-4c46-ba00-b48480d4ffb4/contacts",
"expirationDateTime":"2022-05-10T18:23:45.9356913Z",
"clientState": "SecretClientState"
}

RequestID: cc85bfee-7133-4a09-8f51-e76b4b987697
TimeStamp: Mon, 09 May 2022 10:12:08 GMT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5dc5d01-8bbf-2370-ab1c-680608707ca9
* Version Independent ID: e80b8c52-22f9-24df-528a-50b7d1492eac
* Content: [List contacts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-contacts.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Hi, this repo is for doc-related issues. You can post your question here: https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-contacts.html, so the product team can reply there.

If you consider this is indeed a doc-related issue, please feel free to reopen.
