### ISSUE TITLE
Documentation on permissions for appRoleAssignment is not correct

### ISSUE THREAD

**Issue by hugo-syn** [microsoftgraph/microsoft-graph-docs#16978]
Hello, I would like to add an _appRoleAssignment_ to a service principal. I have another service principal with the appropriate rights, I checked the Azure portal and the JWT token has the same permissions:
 
![2022-05-19_15-35_1](https://user-images.githubusercontent.com/61210734/169307152-fdcc15f4-bf34-4da9-8260-0629cfcf7713.png)

```
$ python3 jwt_tool.py eyJ0e[...]  | grep roles
[+] roles = ['User.ReadWrite.All', 'Application.ReadWrite.All', 'Directory.ReadWrite.All']
```

But it's not working I have an _Authorization_RequestDenied_ response from the server:

![2022-05-19_15-35](https://user-images.githubusercontent.com/61210734/169307537-517fb180-0430-44ac-ad96-d5cc6e17a4ff.png)

However, according to the documentation those permissions should be enough:

![2022-05-19_15-33](https://user-images.githubusercontent.com/61210734/169307860-95c5180b-af4d-4733-87db-2762ec4886d1.png)

If I add the _AppRoleAssignment.ReadWrite.All_ permission it works but not with  _Application.ReadWrite.All_ or _Directory.ReadWrite.All_. Am I missing something or the documentation is wrong ? 

Thank you :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8e535a1-f0e1-eb8f-8b34-365b43d38ad6
* Version Independent ID: 2f1ad830-0642-5cc5-982d-a2b4f75f8f80
* Content: [Grant an appRoleAssignment for a service principal - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-post-approleassignedto.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
I believe the documentation is wrong here and neither _Application.ReadWrite.All_ nor _Directory.ReadWrite.All_ are sufficient, but I will confirm and report back here once I've corrected the documentation.

**Comment by hugo-syn** [comment]
Thank you !
