### ISSUE TITLE
IncludeHiddenFolders does not exist as a parameter for the Microsoft.Graph PowerShell module yet. 

### ISSUE THREAD

**Issue by huybry** [microsoftgraph/microsoft-graph-docs#17005]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad44cdb-5d58-2689-6731-f9b1f791c33f
* Version Independent ID: 5f41b59d-994a-36d8-978f-db8a738fe10d
* Content: [List mailFolders - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-mailfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@maisarissi for visibility

**Comment by Mike-Crowley** [comment]
Any plans on fixing this article? Despite this article wishing it to be true, `-IncludeHiddenFolders` is not a parameter of `get-mgusermailfolder`, even in v 1.12.0.

**Comment by ThoughtContagion** [comment]
Still true as of version 1.19.0

![image](https://user-images.githubusercontent.com/88730003/211335876-5485549a-774e-435a-9470-3909f0efcbd0.png)

[Get-MgUserMailFolder](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.mail/get-mgusermailfolder?view=graph-powershell-1.0) does not have an `-Includehiddenfolders` switch.

![image](https://user-images.githubusercontent.com/88730003/211339383-dde6db0d-661d-4ef5-b8cb-075df0da1161.png)

**Comment by peombwa** [comment]
The query parameter was missing in the metadata. The parameter was added to the metadata by https://github.com/microsoftgraph/msgraph-metadata/pull/319.

The command should now support the query parameter as of v1.27.0:
![image](https://user-images.githubusercontent.com/7061532/235783086-26d9c2d0-4000-4007-a84b-ef2b7286f297.png)
