### ISSUE TITLE
[Doc-Bug] Personal accounts are not showing in group chat members information

### ISSUE THREAD

**Issue by SubbaReddi** [microsoftgraph/microsoft-graph-docs#17034]
I created group chat with adding tenant users and personal account (@gmail.com). When i call following graph api: 
GET https://graph.microsoft.com/v1.0/users/8b081ef6-4792-4def-b2c9-c363a1bf41d5/chats?$expand=members
It is listing tenant users only. Result is not showing personal account user information. 

If it is by design, please add note to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97dd66c-3052-87c8-ddfc-c41d180faa42
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http#example-2-list-all-chats-along-with-the-members-of-each-chat)
* Content Source: [api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Can you test in /beta? We added new functionality there but it hasn't been shipped to v1 yet

**Comment by SubbaReddi** [comment]
@RamjotSingh : Tried with /beta as well, Not returning personal accounts information in group chat members.

**Comment by RamjotSingh** [comment]
I wonder how you added personal account. Was the account added to tenant as a guest? In this case the AAD identity of the user will show up. Or are you using federation?

**Comment by Prasad-MSFT** [comment]
@SubbaReddi - Is there any update on this? Has this issue been resolved?

**Comment by SubbaReddi** [comment]
@Prasad-MSFT: Shared Graph API details and requested details to Ramjot offline.

**Comment by Prasad-MSFT** [comment]
Hi @RamjotSingh - Could you please provide any update on this?

**Comment by SubbaReddi** [comment]
Tried with Beta API and working fine now.
