### ISSUE TITLE
A parameter cannot be found that matches parameter name 'ConsistencyLevel'

### ISSUE THREAD

**Issue by vmhenard** [microsoftgraph/microsoft-graph-docs#17048]
- Ran into the same issue  as #16501  
- Tried to add the ConsistencyLevel parameter but got the "A parameter cannot be found that matches parameter name 'ConsistencyLevel'" error.

![transitiveRoleAssignmentsErrors](https://user-images.githubusercontent.com/96445579/170305451-080a1b81-4eb4-41c9-8957-0216809d0808.png)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f25cb16b-12ac-9f45-8321-961ce167e02c
* Version Independent ID: f5c90128-c35d-4cc3-19d4-4eeffe4f404c
* Content: [List transitiveRoleAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/rbacapplication-list-transitiveroleassignments?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/rbacapplication-list-transitiveroleassignments.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you, @vmhenard, for raising this issue. It is under investigation.

**Comment by msewaweru** [comment]
@vmhenard, it seems the -ConsistencyLevel parameter is not currently supported in this cmdlet. The PowerShell version of the HTTP example does not use this parameter. I have logged [an issue](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1285) for the SDK team to advise on the same.
