### ISSUE TITLE
Using filter now works in v1.0

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/microsoft-graph-docs#17079]
Docs say this filter only works in beta but it works in v1.0 just fine. Graph explorer doesn't support spaces in resourceprovisioning options so I can't provide a test URL there but it works fine in PowerShell graph SDK
![image](https://user-images.githubusercontent.com/15258962/170710120-08ee5d16-67b8-4ee2-b58f-1e07b4f4f78b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c84a5f8-fe8a-615d-4467-9e2dc2d72f42
* Version Independent ID: 8f0f99e3-a8bb-858e-9f1a-92f2435839a7
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-list-all-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@JustinGrote - We are looking into this I will get back to you soon.

**Comment by sayali-MSFT** [comment]
In Note section already present," Filtering groups by resourceProvisioningOptions is only available through the beta endpoint. resourceProvisioningOptions **is available in v1.0** and beta."

Doc-https://docs.microsoft.com/en-us/graph/teams-list-all-teams?view=graph-rest-1.0#get-a-list-of-groups-using-beta-apis

**Comment by JustinGrote** [comment]
More specifically this whole header section should remove reference to the beta endpoint completely since it is no longer relevant.

**Comment by lramosvea** [comment]
Closing as doc has been updated. Thanks.
