### ISSUE TITLE
Missing PowerShell example

### ISSUE THREAD

**Issue by Mike-Crowley** [microsoftgraph/microsoft-graph-docs#17073]
What is the powershell Microsoft.Graph.Identity.Governance cmdlet for this API? Similar articles list these examples. 

It doesn't seem exposed in any of the following, but perhaps its not obvious?

Get-MgAccessReview          
Get-MgAccessReviewDecision  
Get-MgAccessReviewInstance  
Get-MgAccessReviewMyDecision
Get-MgAccessReviewReviewer  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9f57e3-04f9-8e00-efc5-e7b0bd6ebf6c
* Version Independent ID: 4bbaa69b-d41e-6290-acdb-35eb06ffb9d3
* Content: [Create definitions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewset-post-definitions.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @isabelleatmsft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you, @Mike-Crowley, for raising this issue. Unfortunately, the access reviews cmdlets aren't available in v1.0 yet. They are currently only in `beta`. I've filed an issue with the SDK team to investigate generating the cmdlets.

Closing this issue in the docs repo and tracking through the SDK repo https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1286

**Comment by Mike-Crowley** [comment]
Hi, thanks for the quick response, but I am indeed aware the cmdlets work for the beta API only. My question however was about a potentially missing cmdlet for this resource type. Apologies for the poorly filed issue. What I'm saying is that none of the above cmdlets i mentioned seem to allow you to define accessReviewScheduleDefinition ,

**Comment by FaithOmbongi** [comment]
> Hi, thanks for the quick response, but I am indeed aware the cmdlets work for the beta API only. My question however was about a potentially missing cmdlet for this resource type. Apologies for the poorly filed issue. What I'm saying is that none of the above cmdlets i mentioned seem to allow you to define accessReviewScheduleDefinition ,

Hi @Mike-Crowley, got it. Unfortunately, I can't find the cmdlets in the catalog either. It looks like this affects APIs called with the `/identityGovernance/accessReviews/definitions` URL path. The ones you listed in your original issue relate to the [deprecated access reviews API](https://docs.microsoft.com/en-us/graph/api/resources/accessreviews-root?view=graph-rest-beta). 

I've flagged this broader issue with the SDK team for investigation.
