### ISSUE TITLE
Error registering schema - Refiner property 'someproperty' cannot be of type 'Boolean'.

### ISSUE THREAD

**Issue by DmitriyVdE** [microsoftgraph/microsoft-graph-docs#17126]
Hi!

I'm currently working on a Search/Graph connector for an external source of data containing files.
I followed the [tutorial here](https://docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart) and successfully got it to work along with the [full example code here](https://github.com/microsoftgraph/msgraph-search-connector-sample).

Unfortunately I ran into an error while trying to register my own schema within a newly created connection.
I get the following error:

`BadRequest error registering schema:
Code: InvalidRequest
Message: The request is malformed or incorrect.
Inner error:
        Code: RefinerShouldNotBeOfType
Message: Refiner property 'someproperty' cannot be of type 'Boolean'.`

I could just change the type to a 'PropertyType.Int64' and save it like that, but I'm not sure if I can handle it from within the result type on the other side. I also don't know if this data is actually important to the customer but I'd like to get it working either way.

All schema property resource types can be found [here](https://docs.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-1.0).

Also, **unrelated** to this question, the example adds a 'price' property of type 'PropertyType.Double' which does work for registering the schema, and adding the items to the index, but when trying to display the value, it just shows nothing. [You can see this here](https://docs.microsoft.com/en-us/graph/connecting-external-content-build-quickstart?tutorial-step=7), There is no value for 'price' in the result items.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab0cbb92-7d68-c185-f476-beb43aaf2f37
* Version Independent ID: f52a2e44-ec0e-91d6-7aab-38daed432b20
* Content: [property resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/externalconnectors-property?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/externalconnectors-property.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/externalconnectors-property.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @mecampos
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DmitriyVdE** [comment]
I took a look at the error again after a good night's sleep and noticed that it said 'RefinerShouldNotBeOfType', so I set the 'IsRefinable' property of all the Boolean fields to false and the schema gets created perfectly. I just find it weird that I can't have a refinable field of that type, wouldn't it make sense to have it as a refinable property?

**Comment by DmitriyVdE** [comment]
Will this be reassigned?

**Comment by njerigrevious** [comment]
Hi @DmitriyVdE - looking into this and will keep you posted. Thanks for all your questions and let me know if anything else comes to mind!

**Comment by DmitriyVdE** [comment]
Any updates?

**Comment by emzho** [comment]
For the first issue, I believe the schema should register the “type” property as a string, lower-case “boolean”. 

For the second issue regarding the results not showing the price, this is related to a small bug in the result-type.json file in the sample code. Change ${price} to {price} in the result type registered in step 6 of the tutorial ([Build your first custom Microsoft Graph connector | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fgraph%2Fconnecting-external-content-build-quickstart%3Ftutorial-step%3D6&data=05%7C01%7CEmily.Zhou%40microsoft.com%7C37caed87439a4cd6eba708daf7096f5a%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C638093917323277129%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LyWv7q2wzRGSraH9MWLKk7CoyR%2BfpTn5ESNjq4YKOds%3D&reserved=0)).

The result-type.json file has been updated accordingly.
