### ISSUE TITLE
Different information in device compliance and Graph (beta)

### ISSUE THREAD

**Issue by MehtabSiddiq** [microsoftgraph/microsoft-graph-docs#17139]
[Enter feedback here]

Does Microsoft Graph (beta) -usersloggedon property store info for a specific period of time?, There's no such option (usersloggedon) in v1.0, so if anybody knows how I can check the user or users logged on in a device and who is the current users not using Device Compliance and/or Graph.

This is related to the question: https://docs.microsoft.com/en-us/answers/questions/869488/index.html

Thanks in advance.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce4b5d74-ce7b-c686-02e1-03fa24260e39
* Version Independent ID: 90f2dba8-998b-52b8-ceca-3407065d8762
* Content: [windowsManagedDevice resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-windowsmanageddevice?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/resources/intune-devices-windowsmanageddevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-devices-windowsmanageddevice.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
No, there isn't a way to query that information from Intune.

**Comment by MehtabSiddiq** [comment]
Hi @triplanedave 
Thanks for the update.
