### ISSUE TITLE
"Write code" link to Graph Security SDK is broken

### ISSUE THREAD

**Issue by mrossesf** [microsoftgraph/microsoft-graph-docs#17135]
The [Write code](https://aka.ms/graphsecuritysdk) link in [this section](https://docs.microsoft.com/en-us/graph/security-concept-overview#why-use-the-microsoft-graph-security-api) doesn't work. I can't find a page/doc covering a "security SDK" that it should link to anywhere. Seems like maybe the link needs to be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37523f8b-0e66-4805-0fec-786505bc4917
* Version Independent ID: 3628a8a4-4c7d-608b-fe04-d4a9e4bb5468
* Content: [Microsoft Graph Security API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/security-concept-overview#why-use-the-microsoft-graph-security-api)
* Content Source: [concepts/security-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/security-concept-overview.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@Danielabom I guess we should remove the "Write code" link
