### ISSUE TITLE
Are the required permissions correct: Read permission for an Update (and Create/Delete) action

### ISSUE THREAD

**Issue by ykuijs** [microsoftgraph/microsoft-graph-docs#17140]
Are the required permissions correct for this API? It is an update action, but the least privileged documented permissions is Policy.Read.All. It doesn't make sense that a Read permission is required for an update action.

The same is true for the Create and Delete pages of this API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c800e1e8-eec7-27e1-d2bf-96905c4d5995
* Version Independent ID: 41a53e6d-8d05-de1c-d1cd-645783dfdc1b
* Content: [Update ipnamedlocation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/ipnamedlocation-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/ipnamedlocation-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/ipnamedlocation-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @davidspooner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ykuijs for raising this issue. The least privileged permission as per the table is the set of Policy.Read.All _and_ Policy.ReadWrite.ConditionalAccess permissions, _not_ Policy.Read.All only.

We're working to find a better way to represent these multiple permissions requirement so it's not confusing.
