### ISSUE TITLE
503 for create connection API

### ISSUE THREAD

**Issue by sreealekhya-ms** [microsoftgraph/microsoft-graph-docs#17173]
We followed all the steps mentioned and we are getting 503 errors.
We are using TDF test account could that be an issue?
user alias : alekhyag
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1852d5fd-2fef-34ba-2bc5-2cbb03c17d4e
* Version Independent ID: 03e4bac8-3339-62c2-8257-141c6f200d38
* Content: [Use Postman with the Microsoft Graph connectors API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/connecting-external-content-connectors-api-postman?view=graph-rest-beta#step-4-configure-authentication)
* Content Source: [concepts/connecting-external-content-connectors-api-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/connecting-external-content-connectors-api-postman.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @mecampos
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sreealekhya-ms** [comment]
![image](https://user-images.githubusercontent.com/75155049/172383895-fd6b1f49-7af1-404f-a600-66aef6eccc5b.png)

**Comment by mecampos** [comment]
Please assign this issue to the Microsoft Graph content team.

**Comment by emzho** [comment]
Please reach out to the internal team to troubleshoot in detail. Thanks!
