### ISSUE TITLE
Devices attribute missing in ConditionalAccessConditionSet variable

### ISSUE THREAD

**Issue by JAmler** [microsoftgraph/microsoft-graph-docs#17205]
Hello,
I try to create a Conditional Access Policy using the New-AzureADMSConditionalAccessPolicy cmdlet. For this I have to create an object of the Type ConditionalAccessConditionSet. But this Object only has only the following attributes:
![image](https://user-images.githubusercontent.com/93119211/173073431-884674b5-5bf8-4276-a406-ad37ed4f8d51.png)
So the devices attribute is missing and it's not possible to create Device Filters with the PowerShell cmdlet. But following this documentation devices should be implemented in ConditionalAccessConditionSet.

Best regards,
Jakob
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bd679e-c5b2-e1cd-c402-7bb162a958ec
* Version Independent ID: 1d56190d-96db-a565-54d9-b752eadbbd89
* Content: [conditionalAccessConditionSet resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessConditionSet?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/conditionalaccessconditionset.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @davidspooner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidspooner** [comment]
@lstallman Please follow up with Jakob on this request, Azure AD PowerShell is planned for deprecation and as such we should start to look at Microsoft Graph which does contain all the new conditions.

**Comment by CelesteDG** [comment]
Opened issue 1347 in SDK PowerShell repo

CC @msewaweru @FaithOmbongi

**Comment by peombwa** [comment]
@lstallman, as stated above, AzureAD PowerShell module is planned for deprecation. Please use Microsoft Graph PowerShell SDK which supports the property. See the example in https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-1.0&tabs=powershell#example-1-require-mfa-to-access-exchange-online-outside-of-trusted-locations for more details.

See [New-MgIdentityConditionalAccessPolicy](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/new-mgidentityconditionalaccesspolicy?view=graph-powershell-1.0) reference.

**Comment by FaithOmbongi** [comment]
> @FaithOmbongi I have just done this and realised the problem why I couldn't use this command. I use DevOps to run the skripts, so windows opening up aren't possible and the skripts should just run after starting them. But unfortunately with the Microsoft Graph cmdlet it's not possible to just connect with admin credentials like with all other cmdlet. You need to use them in a window opening (what's not possible with DevOps) or with the device code, whats really complicated using DevOps, as you don't know when you need to do and you can miss the time slot to do it really often. Is there a possibility you add -Credential to the Connect-MgGraph command?

Hi @msewaweru, @peombwa - Kindly investigate this customer request to add a `-Credential` option to the **Connect-Graph** cmdlet. Thanks.

**Comment by maisarissi** [comment]
Hi @JAmler .
Have you tried to create your own application and using it when connecting to Graph to do what you need?
The app-only authentication doesn't require windows opening up. You can find more information here: https://docs.microsoft.com/en-us/powershell/microsoftgraph/app-only?view=graph-powershell-1.0&tabs=azure-portal

That way the admin can add all permissions they would like to consent for that app to performance what needs to be done.

**Comment by JAmler** [comment]
Hi @maisarissi ,
Yes I have tried this, but the script should be useable for many tenants and most of the time only needs to be run once. So for another script where I use MS Graph Headers for authentification I alread have a script part which creates and afterwards deletes the application, whats possible with only admin credentials, while it's not possible to just use the admin credentials to authentificate.
But in this case I can't use this as I need the certificate on top. Any authentification with certificate isn't possible as I use DevOps and I would need a certificate of the computer where I run the script, but the script runs on a unkown DevOps Server.
