### ISSUE TITLE
Document advanced query support for oauth2PermissionGrants

### ISSUE THREAD

**Issue by commakoerschgen** [microsoftgraph/microsoft-graph-docs#17247]
Please add the information that the `/oauth2PermissionGrant` endpoint supports advanced queries.

Indeed, without advanced queries (i.e., without using consistency level eventual and count) it provides incomplete results. This is not a sync delay but a persistent issue.

Therefore, it should be documented that the endpoint supports these advanced queries, and it should probably also be documented that it is recommended to use them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Azure AD directory objects - Microsoft Graph](https://docs.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/aad-advanced-queries.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Licantrop0
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Licantrop0** [comment]
@psignoret can you please work with @FaithOmbongi to add advanced query info to [oauth2PermissionGrant ](https://docs.microsoft.com/en-us/graph/api/oauth2permissiongrant-list) page?

**Comment by Licantrop0** [comment]
resolved with #17392

**Comment by FaithOmbongi** [comment]
Related to https://github.com/microsoftgraph/microsoft-graph-docs/issues/5877

**Comment by lramosvea** [comment]
@FaithOmbongi any update on this?

**Comment by FaithOmbongi** [comment]
I've filed internal work item # 2654018 for @psignoret. Closing this issue here.
