### ISSUE TITLE
Needs steps change the licensing mode from evolution to Model = B. The document does not have clear steps to achieve this

### ISSUE THREAD

**Issue by skommu1403** [microsoftgraph/microsoft-graph-docs#17253]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01f880b9-2394-f540-9b06-bcddbe40bfa8
* Version Independent ID: 22de9e03-e917-bcc6-abd7-ebfb3a0cdec8
* Content: [Licensing and payment requirements - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-licenses)
* Content Source: [concepts/teams-licenses.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-licenses.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@skommu1403 - Could you please elaborate more on this.

**Comment by skommu1403** [comment]
Hi Nivedipa,

Thank you for your looking into the issue.

May I loop in the customer who is experiencing the issue to this email thread?


Kind Regards,
Sushmitha K | Support Engineer | Azure Subscription Management Support
Email: ***@***.******@***.***> | Manager: ***@***.******@***.***>
Working Hours: 01:00 AM - 04:00 PM (Monday - Friday) UTC | Local Time<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__nam06.safelinks.protection.outlook.com_-3Furl-3Dhttp-253A-252F-252Fwww.timebie.com-252Fstd-252Fgmt.php-26data-3D02-257C01-257Crahuj-2540microsoft.com-257C84b5b6db2344457c644108d8555ad6ed-257C72f988bf86f141af91ab2d7cd011db47-257C1-257C0-257C637353195969899913-26sdata-3DyZEU0c2my1-252B0K9s6mtkemZDzYSlfK33tnTw99ycSags-253D-26reserved-3D0%26d%3DDwMFAg%26c%3D8ur-RRqq3WDcPLLOBCG0i_KAzF09e0LSstmlvhYQODI%26r%3Do2HcqvdJqLwxstCb-JbpJsfCDYX9Xy3IkiRJSw08ruw%26m%3DWmSNasIdBOz3tw3s4CQ1rnGdoOl6-3fdWTm-AvoaIcs%26s%3DnZgeiawQ7qIF6ESnXseZmhkmCcHsEn_pb7aOIx3eKYo%26e%3D&data=04%7C01%7Cskommu%40microsoftsupport.com%7C08b5b20373b74719799608da161a1718%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637846598579674337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oQQk%2BaLUe1nP8krO5vEBchZ%2B2weFVboY4eTI%2F5W8UwE%3D&reserved=0>

To reach Azure Support outside of my working hours, please email ***@***.******@***.***> with your support request number.
Service Dashboard<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__nam06.safelinks.protection.outlook.com_-3Furl-3Dhttp-253A-252F-252Fazure.microsoft.com-252Fstatus-26data-3D02-257C01-257Crahuj-2540microsoft.com-257C84b5b6db2344457c644108d8555ad6ed-257C72f988bf86f141af91ab2d7cd011db47-257C1-257C0-257C637353195969899913-26sdata-3DaqFSyj2XJ6shJ1R-252FYolAVoGrWnwiIypeLqOmGD1ejBo-253D-26reserved-3D0%26d%3DDwMFAg%26c%3D8ur-RRqq3WDcPLLOBCG0i_KAzF09e0LSstmlvhYQODI%26r%3Do2HcqvdJqLwxstCb-JbpJsfCDYX9Xy3IkiRJSw08ruw%26m%3DWmSNasIdBOz3tw3s4CQ1rnGdoOl6-3fdWTm-AvoaIcs%26s%3D0OlrNCKGVzs9S7nL8WGZoT6pokQN7ypx2VTI_XIufmw%26e%3D&data=04%7C01%7Cskommu%40microsoftsupport.com%7C08b5b20373b74719799608da161a1718%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637846598579674337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xUY4lK5E8mH2o%2FGJsO2r2A4Lu5p4KV5qNMq0pKNc9eE%3D&reserved=0>  | Create a Case <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fportal.azure.com%2F%23blade%2FMicrosoft_Azure_Support%2FHelpAndSupportBlade&data=04%7C01%7Cskommu%40microsoftsupport.com%7C08b5b20373b74719799608da161a1718%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637846598579674337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Datlesc6b8Rwgi0kujIVLpU1IT5Qekvc%2FO2dvQtfulU%3D&reserved=0>  | Azure Announcements<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__nam06.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Fazure.microsoft.com-252Fen-2Dus-252Fblog-252Ftopics-252Fannouncements-252F-26data-3D02-257C01-257Crahuj-2540microsoft.com-257C84b5b6db2344457c644108d8555ad6ed-257C72f988bf86f141af91ab2d7cd011db47-257C1-257C0-257C637353195969909908-26sdata-3DXDSujb6I4R9I9y22vxozY3r-252FRtO7IQzFKp83gsEV19w-253D-26reserved-3D0%26d%3DDwMFAg%26c%3D8ur-RRqq3WDcPLLOBCG0i_KAzF09e0LSstmlvhYQODI%26r%3Do2HcqvdJqLwxstCb-JbpJsfCDYX9Xy3IkiRJSw08ruw%26m%3DWmSNasIdBOz3tw3s4CQ1rnGdoOl6-3fdWTm-AvoaIcs%26s%3DO6W5bMGPWXz-h1mi26TXIw17781DHQRM6Ch7bfJWOQk%26e%3D&data=04%7C01%7Cskommu%40microsoftsupport.com%7C08b5b20373b74719799608da161a1718%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637846598579674337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BNdEsPaTZ9Q97XO9tlKy2PtkSeuHnRVBt0mfZQa4wEM%3D&reserved=0> | Have an idea or a suggestion?<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__nam06.safelinks.protection.outlook.com_-3Furl-3Dhttps-253A-252F-252Ffeedback.azure.com-252Fforums-252F34192-2D-2Dgeneral-2Dfeedback-26data-3D02-257C01-257Crahuj-2540microsoft.com-257C84b5b6db2344457c644108d8555ad6ed-257C72f988bf86f141af91ab2d7cd011db47-257C1-257C0-257C637353195969919900-26sdata-3DFK6pszBVLpfH5XytTOLSoDWbPw8TQBQWHEDc7oFinF4-253D-26reserved-3D0%26d%3DDwMFAg%26c%3D8ur-RRqq3WDcPLLOBCG0i_KAzF09e0LSstmlvhYQODI%26r%3Do2HcqvdJqLwxstCb-JbpJsfCDYX9Xy3IkiRJSw08ruw%26m%3DWmSNasIdBOz3tw3s4CQ1rnGdoOl6-3fdWTm-AvoaIcs%26s%3Dcp3qfXgMWqWBKpzOFvoCm5EH0X2J4PH-JHRXiaePdz4%26e%3D&data=04%7C01%7Cskommu%40microsoftsupport.com%7C08b5b20373b74719799608da161a1718%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637846598579674337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DIueV1BEcFtCltlbTHBAccQsB3ru3%2BaLF2XAX6GQz%2FU%3D&reserved=0>
For your privacy and security, NEVER send your login credentials or full credit card number in email.

**Comment by skommu1403** [comment]
Hi,

Thank you for getting back to me. Customer would like to if there is anything beyond passing in "model=B" as a query string that needs to be done for changing the licensing program? Did not find this documented in the page. Please help.


Thanks,
Sushmitha

**Comment by Nivedipa-MSFT** [comment]
@skommu1403 - There are no licensing requirements for model=B.

**Comment by Wajeed-msft** [comment]
Closing this issue as there is no further action pending. Please feel free to reopen if you have any questions.

**Comment by skommu1403** [comment]
Thank you for the support

Thanks,
Sushmitha
