### ISSUE TITLE
Microsoft graph live status monitoring

### ISSUE THREAD

**Issue by sharmajnu** [microsoftgraph/microsoft-graph-docs#1726]
Is there any portal where we can check the live status of different graph endpoints? 
Something like this, that we have for azure.

[https://azure.microsoft.com/en-in/status/](https://azure.microsoft.com/en-in/status/)

Recently when accessing the graph endpoints from India we are getting lots of 504 on random endpoints, sometimes we also get 503.

Couple of months back all our calls were responded by South India data centre, now all calls are responded by North(and sometimes West) Europe data centre.

Are there some issues with South India data centre or the calls are directed because our Azure AD app is hosted in Europe data centre?

**Comment by dpim** [comment]
We don't currently have a dedicated endpoint for checking overall Graph service status, but you can see the health of some underlying Office services [here](https://status.office365.com/). Thank you for bringing this to our attention.

**Comment by rsweetland** [comment]
I would like to suggest that this ticket remains open until some type of status page is implemented for graph api.

[This outage](https://github.com/microsoftgraph/microsoft-graph-docs/issues/6462) affected a number of people (including us), made worse by the fact that it was a silent failure – webhooks just stopped firing.

I understand that graph endpoints map to different underlying resources. An end-user of the APIs should not have to think about this abstraction. From a developer standpoint the graph-api is either working or not. 

At the very least, if there was a  "Graph API Status" page which linked to the proper services it would be more helpful. And it would like show up when developers are frantically searching "Graph API status" when their APIs stop working.

**Comment by udlose** [comment]
@dmahugh  can we re-open this?  There should be some official endpoint created to programmatically check the health status of the Microsoft Graph API.

**Comment by dmahugh** [comment]
@udlose Sorry, I'm no longer involved in this org/repo. Have been working at Google since July 2019.

**Comment by udlose** [comment]
@dpim are you someone who can re-open this ticket?

**Comment by jasonjoh** [comment]
@udlose that would be a feature request, not an issue with the documentation. Please use https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests for suggestions or feature requests for Graph.

**Comment by udlose** [comment]
@rsweetland @anoopnair @denitsagencheva @tedbergeron @eran-levy @sharmajnu @johanovic @Legfordrum @jerrypnz 

I created a feature request if anyone wants to vote/track:

[Add Microsoft Graph API Health endpoint](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/40319329-add-microsoft-graph-api-health-endpoint)
