### ISSUE TITLE
chatMessage delta $filter param not working

### ISSUE THREAD

**Issue by Harleymckee** [microsoftgraph/microsoft-graph-docs#17270]
[Enter feedback here]

docs say the following 

```
$filter allows returning messages that meet a certain criteria. The only property that supports filtering is lastModifiedDateTime, and only the gt operator is supported. For example, ../messages/delta?$filter=lastModifiedDateTime gt 2019-02-27T07:13:28.000z will fetch any reply chain (each channel post message and associated reply messages) created or changed after the specified date time.
```

but when I try to use this param, I see
```
400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/teams/<team_id>/channels/<chan_id>/messages/delta?$expand=replies&$filter=lastModifiedDateTime%20gt%202022-02-27; error: Parameter 'Filter' not supported for this request
```

Thanks, it would be awesome for my team if this parameter was working 😄  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d8e638-3695-72a4-fa08-2622d0281d42
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessage: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adricl** [comment]
So I have found with this issue that the filter is very picky with the date format and will fail. 
"lastModifiedDateTime gt 2022-05-23T06:14:43.1329004z"

This works for me. 

From the docs https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http#optional-odata-query-parameters

"$filter allows returning messages that meet a certain criteria. The **only property that supports filtering is lastModifiedDateTime, and only the gt operator** is supported. For example, ../messages/delta?$filter=lastModifiedDateTime gt 2019-02-27T07:13:28.000z will fetch any reply chain (each channel post message and associated reply messages) created or changed after the specified date time."

Hope that helps

**Comment by ChetanSharma-msft** [comment]
@Harleymckee - Thanks for reporting this issue.
We will check on it from our end and get back to you.

**Comment by Prasad-MSFT** [comment]
We tried to repro this at our end, and it works fine for us. It seems like you are using wrong DateTime format. On using format as below, it works.
 `?$filter=lastModifiedDateTime gt 2022-02-27T07:13:28.000z`
 
 
![image](https://user-images.githubusercontent.com/62237649/181709370-2c75c896-68e2-4067-8162-44462e4fb3b9.png)

**Comment by ChetanSharma-msft** [comment]
@Harleymckee - Please let me know if you need any further help or shall we close this issue?

**Comment by Harleymckee** [comment]
@ChetanSharma-msft lost track of this thread, yes this is sorted. Thank yall for help!
