### ISSUE TITLE
List subscription is not showing values

### ISSUE THREAD

**Issue by schmeedy87** [microsoftgraph/microsoft-graph-docs#17354]
Since last week list of subscription is not working.

GET https://graph.microsoft.com/v1.0/subscriptions/

returns:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/subscriptions/?$skiptoken=8r8sF6wDHaAzFnJAdgxsF%252Ba4hVGBzgyoZFT0S%252B3yOxgSWlU5O9djviYtCjbeuhREFZwR8cdSBXwOCvxRl4Nfo8JubFzb1vmd1DzOlghObno%253D",
    "value": []
}

If I'm going through nextLink I get more then 50 pages of empty value. Create subscription is working properly, same as getting info about certain subscription with subscription ID. Deleting subscrpition is working too. The problem is just with listing all the subscriptions.

Similar error was: #5681 and #4644

**Comment by gazben** [comment]
@robward-ms I think the #15648 issue is happening again. A couple of days ago I started to get exceptions regarding the subscription queries.

**Comment by FaithOmbongi** [comment]
Hi @gazben - This looks like a product bug. If you don't mind, could you file a product bug at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-change-notifications.html) so this issue can be investigated? If you have some request IDs to help with debugging, please share them in your post.

**Comment by gazben** [comment]
@FaithOmbongi I've opened a thread here: https://docs.microsoft.com/en-us/answers/questions/900718/graph-api-subscription-list-endpoint-returns-empty.html

How do I get a request id?

**Comment by FaithOmbongi** [comment]
Hi @gazben, thanks for sharing the Q&A issue link here so others can track it as well. You can get the request ID by inspecting the headers. If using Graph Explorer or Postman, check the "Response headers/headers" tabs. But it's not necessary.

**Comment by robward-ms** [comment]
@schmeedy87 - Thanks for the report! The issue has been investigated and a mitigation is rolling out and should be complete today.

@gazben - No need to submit a request id unless you see the issue beyond today.

**Comment by gazben** [comment]
@robward-ms I've checked the logs and the exceptions stopped. I was able to query the subscriptions manually also.

**Comment by robward-ms** [comment]
@gazben  - Great news, thanks for the feedback! The rollout is not 100% complete so it's possible you'll still hit the issue throughout the day until all regions get the mitigation later today.
