### ISSUE TITLE
No properties in MS Graph API to determine if MFA status is Enabled / Disabled / Enforced for users

### ISSUE THREAD

**Issue by JanakarM** [microsoftgraph/microsoft-graph-docs#17374]
MSOnline is going to be deprecated soon. But there is no alternative to get MFA status of users. Let me know the documentation link, if what I'm asking is already possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4a6a107-2470-e832-c718-a7cc8482badf
* Version Independent ID: e79dd7b7-4e27-06c6-744d-5b3b8aac39df
* Content: [List userRegistrationDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-list-userregistrationdetails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/authenticationmethodsroot-list-userregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by koenhalfwerk** [comment]
The only option I found was seeing if they have a method enabled 
`"https://graph.microsoft.com/beta/users/$($user.id)/authentication/Methods"`

but that is not the same as the enabled\enforced data

**Comment by JohnDCCIU** [comment]
There needs to be a way to reliably Get or Set the MFA Enforcement State (i.e. "Disabled", "Enabled" or "Enforced") on a Per-User basis (not Conditional Access).  This can be easily done via PowerShell, but not via MS Graph API, as it is completely missing from the latter.

The PowerShell equivalents of what I'm referencing are:
**Get MFA State**
```
$UserObjectSAR = get-msoluser -UserPrincipalName $Username | Select-Object -Expand StrongAuthenticationRequirements
$MFAState = $UserObjectSAR.State
```

**Set MFA State**
```
$AuthenticationRequirements = New-Object "Microsoft.Online.Administration.StrongAuthenticationRequirement"
$AuthenticationRequirements.RelyingParty = "*"
$AuthenticationRequirements.State = $MFAState
Set-MsolUser -UserPrincipalName $Username -StrongAuthenticationRequirements $AuthenticationRequirements
```

**Comment by v1ctormoreno** [comment]
Still waiting for this feature in the MSGraph API. Trying to migrate almost all of my scripts to the Graph API. Thanks

**Comment by aperally** [comment]
+1

**Comment by glennmspeasy** [comment]
really need this before MSOL is deprecated

**Comment by DavisHenckel** [comment]
Please don't decommission MSOL module until there is a per-user MFA set option in Microsoft Graph API...

**Comment by anwarmahmood1** [comment]
MFA can be enforced using conditional access, Microsoft's preferred method, or per-user.  But conditional access requires an appropriate license. Hence, per-user is still required for user accounts not licensed for conditional access. 

per-user MFA isn't obsolete; it **MUST** become available through Graph API

**Comment by merill** [comment]
@andres-canello @jpettere FYI

**Comment by kernelkraut** [comment]
We are also busy moving all our admin tasks from PowerShell to Graph. Being able to Enable/Disable/Enforce with Graph is an absolute requirement for us...

**Comment by v1ctormoreno** [comment]
Looks like we are not getting this feature anytime soon.

**Comment by aperally** [comment]
https://feedbackportal.microsoft.com/feedback/idea/d466133f-5cb3-ed11-a81b-002248519701
