### ISSUE TITLE
Missing documentation for Remove-MgGroupMemberByRef

### ISSUE THREAD

**Issue by vermarine** [microsoftgraph/microsoft-graph-docs#17422]
The [Remove member](https://docs.microsoft.com/en-us/graph/api/group-delete-members) article mentions the powershell cmdlet [`Remove-MgGroupMemberByRef`](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/remove-mggroupmemberbyref), however this cmdlet is not documented in the official [Microsoft Graph reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/?view=graph-powershell-1.0). Is this undocumented cmdlet safe to use in production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @vermarine for catching this. Looks like the [Microsoft.Graph.Groups module reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/?view=graph-powershell-1.0) is incomplete. The `Remove-MgGroupMemberByRef` is available in v1.0 as per the following screenshot and therefore safe to use in production.

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/14026935/175501848-94c3cbe9-472f-4f64-adf1-91cfaced76ab.png">

cc @msewaweru to help update the [Microsoft.Graph.Groups module reference](https://docs.microsoft.com/en-us/powershell/module/microsoft.graph.groups/?view=graph-powershell-1.0)

**Comment by FaithOmbongi** [comment]
Closing this issue here and tracking it through https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1345.
