### ISSUE TITLE
The required permission seems to be DeviceManagementConfiguration.ReadWrite.All / DeviceManagementConfiguration.Read.All 

### ISSUE THREAD

**Issue by SathyarGit** [microsoftgraph/microsoft-graph-docs#17446]
The required permission for List deviceManagementScripts seems to be 
   DeviceManagementConfiguration.ReadWrite.All / DeviceManagementConfiguration.Read.All 

and not 
  DeviceManagementManagedDevices.ReadWrite.All, DeviceManagementManagedDevices.Read.All

as given on this page. Please verify and update.

Thanks
Sathya Rajagopalan.
sathyar@outlook.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d748098a-39a0-1c85-0349-cd8b797ac69d
* Version Independent ID: 0b652b35-171b-8821-a0ae-4874b0f71f53
* Content: [List deviceManagementScripts - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagementscript-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-shared-devicemanagementscript-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-shared-devicemanagementscript-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jaiprakashmb** [comment]
Acked @SathyarGit/ @rolyon , Thanks for bringing this to my attention. 
This should be fixed in our next doc release. 

Thanks

**Comment by triplanedave** [comment]
This has been updated.
