### ISSUE TITLE
Wrong definition of ICalUId

### ISSUE THREAD

**Issue by Thoma997** [microsoftgraph/microsoft-graph-docs#17479]
The description for ICalUId reads: 
```A unique identifier for an event across calendars. This ID is different for each occurrence in a recurring series. Read-only.```

However, in `Microsoft Graph calendar events – iCalUId Update` from `February 25th, 2020` it is stated that `[ICalUId] is an ID that is unique to a meeting or meeting series in case of recurring meeting.`.

This behaviour is confirmed by me comparing the ICalUIds of two occurances of the same recurring event using the `CalendarView` API call.

I would suggest to update the Docs respectively to prevent confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41a9857-98a9-e400-d7ce-bd7c0f37cd46
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/event.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by iamgirishck** [comment]
iCalUId in current form in MS-Graph has different instances of a series having different value. This is different from EWS iCalUId where different instances of a series has same value. Hence there was a plan to make this change in MS-Graph in iCalUId field However the initiative is not complete We will update the documents once required code changes are complete
