### ISSUE TITLE
Could it be that permissions are not correct?

### ISSUE THREAD

**Issue by baartch** [microsoftgraph/microsoft-graph-docs#17503]
I was not able to update any groupSetting on the default _Consent Policy_.
```
    "displayName": "Consent Policy Settings",
    "templateId": "dffd5d46-495d-40a9-8e21-954ff55e198a"
```
I got the error `"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation."`.  

I ran the command with a delegated work account.
To me it seems like the permissions documented on this page are not correct.

To get it work, I had to additionally provide the permission `Directory.AccessAsUser.All`. Is it wrong documented or did I do something wrong?

Thanks for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de1d3c0-ff82-f955-15d4-ffe99717d93a
* Version Independent ID: 0d541fbf-4acc-31a7-62d7-0855b0774362
* Content: [Update groupSetting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/groupsetting-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/groupsetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/groupsetting-update.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
@baartch When changing settings for the "Consent Policy Settings" settings template, the app requries *Policy.ReadWrite.Authorization*.

Note: Do not change the value for "EnableAdminConsentRequests". Leave the default value (if doing a POST), or leave the value unchanged (if doing a PATCH). To enable the admin consent workflow, [update adminConsentRequestPolicy](https://docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&tabs=http) instead.

Thanks for reporting this documentation issue!

**Comment by psignoret** [comment]
The documentation has been updated, closing this issue. Thanks for the feedback, @baartch !

**Comment by baartch** [comment]
> @baartch When changing settings for the "Consent Policy Settings" settings template, the app requires _Policy.ReadWrite.Authorization_.
> 
> Note: Do not change the value for "EnableAdminConsentRequests". Leave the default value (if doing a POST), or leave the value unchanged (if doing a PATCH). To enable the admin consent workflow, [update adminConsentRequestPolicy](https://docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&tabs=http) instead. (If for some reason you really need to update this value, the app will need _Policy.ReadWrite.ConsentRequest_.)
> 
> Thanks for reporting this documentation issue!

Thanks for your hint. My intention was doing a PATCH. **But how do I leave the the value unchanged??** (without retrieving it first and then writing what I received).

If I don't provide _EnableAdminConsentRequests_ I get:  
`The expected property 'EnableAdminConsentRequests' defined in template with SettingTemplateId 'dffd5d46-495d-40a9-8e21-954ff55e198a' was not provided.`

If I send a blank value, I get:  
`The value '' for property 'EnableAdminConsentRequests' does not match the expected type 'System.Boolean'.`

If I provide a "true" value, I'm fine.

If you are asking now, why I'm doing this at all. Actually my goal is just to ensure, the following values are set like this:
```json
{
  "id": "a501d93e-9401-49dc-98f9-397eee4653f7",
  "displayName": "Consent Policy Settings",
  "templateId": "dffd5d46-495d-40a9-8e21-954ff55e198a",
  "values": [
    {
      "name": "EnableGroupSpecificConsent",
      "value": "false"
    },
    {
      "name": "EnableAdminConsentRequests",
      "value": "true"
    }
  ]
}
```

**Comment by psignoret** [comment]
@baartch What I meant was that when you PATCH, you leave the value for "EnableAdminConsentRequests" at whatever it was when you received it from the GET. If it's present and "true", leave it as "true". If it's present and "false", leave it as "false". If it's absent, set it to the default value (which you would get from directorySettingsTemplate).
