### ISSUE TITLE
Filter on Visibility using advanced query (Eventual)

### ISSUE THREAD

**Issue by jebalert** [microsoftgraph/microsoft-graph-docs#17507]
Regarding the PowerShell SDK for MSGraph, specifically the Get-MgGroup cmdlet..

In large orgs, performance of a standard Get-MgGroup -All query where one would then filter down using where-object {$_.Visibility -eq Public} for example, takes far too long to execute. Was hoping that using the -filter -CountVariable -ConsistencyLevel method would work, but the lack of group based attributes to filter on using that method makes things difficult.

Is there a better way for handling this type of scenario in orgs where there are tens of thousands or maybe hundreds of thousands of objects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Azure AD directory objects - Microsoft Graph](https://docs.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/aad-advanced-queries.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Licantrop0
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Licantrop0** [comment]
Hi @jebalert, unfortunately filtering on visibility property of a group is not supported yet.  
I put this on the backlog and will update you once we enable this functionality.

**Comment by jebalert** [comment]
> Hi @jebalert, unfortunately filtering on `visibility` property of a group is not supported yet.  
> 
> I put this on the backlog and will update you once we enable this functionality.

Excellent. Thank you. Another incredibly useful filter would be createdDateTime.

**Comment by FaithOmbongi** [comment]
Thank you @Licantrop0 for your feedback to @jebalert's request. Closing this issue and tracking the feature request internally.
