### ISSUE TITLE
Missing id property for team resource type

### ISSUE THREAD

**Issue by fangbli** [microsoftgraph/microsoft-graph-docs#17504]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9da05bd1-f389-cc6d-1c51-00eac3a5f581
* Version Independent ID: e4fadfc1-26e8-fb24-424a-a37c5a77b911
* Content: [team resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/team.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
@fangbli - Thanks for reporting this issue.
We will check on from our end and get back to you.

**Comment by sayali-MSFT** [comment]
@AkJo -Could you please help us for update document?
In below document in table section need to add id properties-
<html>
<body>


Property | Type | Description
-- | -- | --
id| String | The unique identifier of the team. The group has the same ID as the team.

</body>
</html>

Document-https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0#properties

**Comment by ChetanSharma-msft** [comment]
@AkJo - Please help us here to update the documentation.

**Comment by ChetanSharma-msft** [comment]
Hello @AkJo - Could you please help us here to update the documentation?

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Please feel free to reopen otherwise. Thanks.
