### ISSUE TITLE
$top parameter when using delta query to track changes

### ISSUE THREAD

**Issue by xyz92** [microsoftgraph/microsoft-graph-docs#17516]
Is there a way to use `$top` parameter when using delta query to track changes? Please provide an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66201f1c-504b-eba2-f489-c611523fdf8d
* Version Independent ID: 5c711b4f-e234-ae03-53e5-ecd206a157ff
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @xyz92 - Unfortunately, `$top` isn't supported by all APIs and will be silently ignored in delta for unsupported APIs. It will depend on the API you're trying to call and the maximum page size for that API - see the [Optional query parameters section in the delta guidance](https://docs.microsoft.com/en-us/graph/delta-query-overview).

You use `$top` in delta queries exactly the same way you would use it in the normal API queries - as query parameters.

For example, the messages API supports `$top` for delta results. The syntax is

```http
https://graph.microsoft.com/beta/me/mailFolders/{mailFolderId}/messages/delta?$top=9
```

Hope this information helps.

**Comment by ilantom** [comment]
@FaithOmbongi https://graph.microsoft.com/v1.0/groups/delta?$filter=id  eq 'id'&$top=1. I tried this and I see it returned all users instead of 1 user. What am I missing? if $top is not supported, how many users are returned per page if the group contains a large number of users?
