### ISSUE TITLE
Reference for the Shifts callback API missing?

### ISSUE THREAD

**Issue by Chipzter** [microsoftgraph/microsoft-graph-docs#17556]
I'm unable to find any detailed documentation and reference for the API Shifts expects from workforce integration implementations. It would be great if you could link to that documentation on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 345971af-1648-7acf-b7e8-d587e4fbf47f
* Version Independent ID: 1d6f173d-be17-e4b3-7ea9-e4590ea22cf5
* Content: [workforceIntegration resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/workforceintegration?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/workforceintegration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/workforceintegration.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
@Chipzter - Thanks for reporting this issue.
We will check on it and get back to you.

**Comment by Nivedipa-MSFT** [comment]
@Chipzter - Could you please refer below document. In this document multiple shift related APIs are mentioned.
Example- List shifts, Create shift, Get shift, Replace shift, Delete shift.

https://docs.microsoft.com/en-us/graph/api/resources/shift?view=graph-rest-1.0

**Comment by ChetanSharma-msft** [comment]
Hello @Chipzter - Hope you are doing well!!
Please confirm whether your issue has resolved or need any further help here?

**Comment by Nivedipa-MSFT** [comment]
We are closing this issue for now, please feel free to reopen it, if required.
