### ISSUE TITLE
Listing 00000002-0000-0000-c000-000000000000 as MS Graph incorrect?

### ISSUE THREAD

**Issue by neilmca-inc** [microsoftgraph/microsoft-graph-docs#17580]
In all the examples it lists the Microsoft Graph as 00000002-0000-0000-c000-000000000000

When I've added a Microsoft Graph permission manually and checked the manifest - it is listed as 00000003-0000-0000-c000-000000000000

Which one should it be? I thought 00000002 was the AAD Graph API that is being retired?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1caf7b-7d94-ed49-f84a-1c8adad5bc93
* Version Independent ID: 7b1caf7b-7d94-ed49-f84a-1c8adad5bc93
* Content: [Configure required Azure AD Graph permissions for an app registration - Microsoft Graph](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions)
* Content Source: [concepts/migrate-azure-ad-graph-configure-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-configure-permissions.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @neilmca-inc for asking this question. The guide is for **adding Azure AD Graph permissions** to an app, _not_ Microsoft Graph permissions. All references to `00000002-0000-0000-c000-000000000000` refer to the **Azure AD Graph API**. 

> I thought 00000002 was the AAD Graph API that is being retired?

Correct. Azure AD Graph is still on the path of retirement. This guide is intended only for developers that still have apps with dependencies on Azure AD Graph and for some reason, they are unable to migrate the apps to using Microsoft Graph. The devs ∴ need to add more Azure AD Graph permissions for their apps/app scenarios to keep working while they plan for migration.

**Comment by neilmca-inc** [comment]
OK thank you @FaithOmbongi  - I'll continue to pass in 03 I think ;)
