### ISSUE TITLE
List User endpoint only shows 'relevant' results for Delegated request

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoftgraph/microsoft-graph-docs#17599]
I've tested this endpoint from Graph Explorer, and it appears, following a case with Support (31496165), that it will **only** find results based on 'relevance' for the current logged-in user. That means that, for example, if I've never sent or received an email to/from a user named 'Bob' in my organisation, the following query will return an empty result: `https://graph.microsoft.com/v1.0/users?$search=bob`

This is not obvious at all, nor is it mentioned on this Docs page at all - I want to suggest that the page be updated with this so developers using this API will be aware of this important constraint.

On a side note, I'd love to know if there's an endpoint that **does** search **all** users in the organization? I can't seem to find one...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @HiltonGiesenow - Thank you for sharing your experience.

> I've tested this endpoint from Graph Explorer, and it appears, following a case with Support (31496165), that it will only find results based on 'relevance' for the current logged-in user.

The behavior you're describing is weird and unfortunately, I'm unable to replicate it. The **https://graph.microsoft.com/v1.0/users** endpoint returns ALL users in the tenant (with pagination applied if the result set is more than the default per page). This is without exception AFAIK.

> That means that, for example, if I've never sent or received an email to/from a user named 'Bob' in my organisation, the following query will return an empty result: https://graph.microsoft.com/v1.0/users?$search=bob

Your query isn't completely accurate in that the syntax for using the `$search` query parameter is different for the users API. Please see more info here: [Use the search query parameter](https://docs.microsoft.com/en-us/graph/search-query-parameter?tabs=http). Therefore, to find all users named "bob" in your tenant, the correct query is 
```
https://graph.microsoft.com/v1.0/users?$search="displayName:bob"
ConsistencyLevel: eventual
```
**NOTE:** The header is required in your request. More info is in the guidance.

Though I wonder how you're getting 0 results. The query should instead be a silent fail where only https://graph.microsoft.com/v1.0/users is fulfilled and all users are returned with no matching on the display name.

> if I've never sent or received an email to/from a user named 'Bob'

A point of note that to find all emails received from a particular user, use the [message ](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0) API and not the users API. So your query would be (PS: No header required here)

```
https://graph.microsoft.com/v1.0/me/messages?$search="participants:bob"
```

Kindly retry with this guidance. If you still see a discrepancy between what's in your tenant vs the Microsoft Graph output, please file a request at Microsoft Graph Q&A and provide a request ID so the issue can be investigated. 
Unfortunately, this forum is only for documentation-related issues but functionality issues are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/products/graph).
