### ISSUE TITLE
Use the microsoft.graph.group OData cast to get only members that are groups

### ISSUE THREAD

**Issue by ilantom** [microsoftgraph/microsoft-graph-docs#17604]
I tested [Example 3 ](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=csharp#example-3-use-the-microsoftgraphgroup-odata-cast-to-get-only-members-that-are-groups) in C# and it returned all directory object not just members that are groups. What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37eaad48-9559-ab5c-5b83-338f53fbbc6f
* Version Independent ID: 591556a3-d528-7f19-e03b-3bf5a67bce51
* Content: [List group transitive members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http#example-3-use-the-microsoftgraphgroup-odata-cast-to-get-only-members-that-are-groups)
* Content Source: [api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-transitivemembers.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @ilantom - Unfortunately, I'm unable to replicate this behavior in my tenant. 

Can you verify that your request includes both the $count=true query parameter and you added the **ConsistencyLevel** header and set its value to `true`? If yes and the response payload still contains inacurrate results, please file an issue at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-groups.html) and provide a request ID. Unfortunately, this forum is only for documentation-related issues but functionality issues are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/products/graph).

**Comment by JasonCelestine** [comment]
same is happening for me... Not sure what I'm doing wrong
![GraphBug](https://user-images.githubusercontent.com/4588930/180103983-83adb6b0-f2c8-4f66-bf60-9ec67048b248.png)

**Comment by JasonCelestine** [comment]
@ilantom your note says " ... the ConsistencyLevel header and set its value to true? " but the docs say set it to "eventual"... can you elaborate?

**Comment by FaithOmbongi** [comment]
> @ilantom your note says " ... the ConsistencyLevel header and set its value to true? " but the docs say set it to "eventual"... can you elaborate?

Good catch, @JasonCelestine - **ConsistencyLevel** should be `eventual`. I've corrected my initial response.

>Also, is there docs that explain HOW this incantation of header and count filters the TransientMembers? Maybe I'm just not finding it but I can't find it... thanks.

Please find more info here [Advanced query capabilities on Azure AD directory objects](https://docs.microsoft.com/en-us/graph/aad-advanced-queries).

@ilantom - I'm not a C# expert but you can get help from other developers when you post your question at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/products/graph).
