### ISSUE TITLE
Update the documentation || please mention where on azure portal we can see the billing information

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs#17615]
Please also mention if the billing for instance for Model B will be displayed on an hourly/weekly/monthly basis on the Azure portal ?

I am trying Model B for the past 3 days but I can't see any charges on my Cost Management slide on Azure portal.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b32ca7f9-ea75-d0fd-f887-136e0c9686e3
* Version Independent ID: 6e9b24bc-9869-0b70-8881-3c4aad2bebed
* Content: [Protected APIs in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-protected-apis)
* Content Source: [concepts/teams-protected-apis.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-protected-apis.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
We are looking at this issue, we will get back to you.

**Comment by DebugwithDJ** [comment]
We would like to get same information. please suggest.

**Comment by Meghana-MSFT** [comment]
We checked this with the engineering team, and we got the below response. 

ModelB isnt getting charged right now as the system is still being built up. If you're not seeing charges in Azure Portal, you're not being charged. In the meantime, you may use the service free of charge. 

Engineering team is also working to update the document as well.

**Comment by ProgrammingWithDJ** [comment]
@Meghana-MSFT thank you so much for your Inputs we can close this issue.

Appreciate your time and insights.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
