### ISSUE TITLE
DeviceManagementManagedDevices.PriviligedOperation.All or DeviceManagementManagedDevices.PrivilegedOperations.All?

### ISSUE THREAD

**Issue by patrickdeline** [microsoftgraph/microsoft-graph-docs#17641]
This is still an ongoing issue with graph operations utilizing the DeviceManagementManagedDevices.PriviligedOperation.All scope.

I've seen a couple of issues reported, but none seem to point out that "Priviliged" is mis-spelled. It should be "Privileged".

Please also doublecheck whether the permission should be plural or not.

![image](https://user-images.githubusercontent.com/85367106/178362918-237f3b4f-f1e4-4d1f-add9-bfdc145e22b8.png)

![image](https://user-images.githubusercontent.com/85367106/178363054-00760e81-dfc6-4e72-831d-b795526a72ed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c495e30-023a-b13c-dafe-40aed336bdd8
* Version Independent ID: 06b36718-ae83-8247-1a55-3127c0c5266c
* Content: [locateDevice action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-locatedevice?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-devices-manageddevice-locatedevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-devices-manageddevice-locatedevice.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
This appears to be fixed now.
