### ISSUE TITLE
Error setting "discoverySettings" as AdditionalData using C# SDK

### ISSUE THREAD

**Issue by bretthacker** [microsoftgraph/microsoft-graph-docs#17669]
Regarding this example, using the C# SDK:

https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=csharp#example-3-create-a-team-with-multiple-channels-installed-apps-and-pinned-tabs-using-delegated-permissions

I confirmed at a breakpoint, prior to making the call, that my resulting 'discoverySettings" value was identical to that in the documentation:

`
	AdditionalData = new Dictionary<string, object>()
	{
		{"template@odata.bind", "https://graph.microsoft.com/v1.0/teamsTemplates('standard')"},
		{"discoverySettings", "{\"showInTeamsSearchAndSuggestions\":true}"}
	}
`

I received this error:

`{"error":{"code":"BadRequest","message":"Could not cast or convert from System.String to Microsoft.Teams.Graph.GraphModels.TeamDiscoverySettings.","innerError":{"date":"2022-07-13T03:56:13","request-id":"ce26c825-5c14-46f5-a218-df520f695add","client-request-id":"ce26c825-5c14-46f5-a218-df520f695add"}}}`

Am removing this setting for now but the documentation for this C# example may be flawed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=csharp#example-3-create-a-team-with-multiple-channels-installed-apps-and-pinned-tabs-using-delegated-permissions)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @anandjo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @bretthacker - Thanks for reporting your issue.
We will look into it and redirect to doc team accordingly.

**Comment by sayali-MSFT** [comment]
@bretthacker - You need to add the `DiscoverySetting` in the C# code like below snippets , Could you please try it once-

```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var team = new Team
{
	DisplayName = "My Class Team",
	Description = "My Class Team’s Description",
	Channels = new TeamChannelsCollectionPage()
	{
		new Channel
		{
			DisplayName = "Class Announcements 📢",
			IsFavoriteByDefault = true
		},
		new Channel
		{
			DisplayName = "Homework 🏋️",
			IsFavoriteByDefault = true
		}
	},

	DiscoverySettings = new TeamDiscoverySettings 
         {
         showInTeamsSearchAndSuggestions= true
         },
	  
	MemberSettings = new TeamMemberSettings
	{
		AllowCreateUpdateChannels = false,
		AllowDeleteChannels = false,
		AllowAddRemoveApps = false,
		AllowCreateUpdateRemoveTabs = false,
		AllowCreateUpdateRemoveConnectors = false
	},
	InstalledApps = new TeamInstalledAppsCollectionPage()
	{
		new TeamsAppInstallation
		{
			AdditionalData = new Dictionary<string, object>()
			{
				{"teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('com.microsoft.teamspace.tab.vsts')"}
			}
		},
		new TeamsAppInstallation
		{
			AdditionalData = new Dictionary<string, object>()
			{
				{"teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('1542629c-01b3-4a6d-8f76-1938b779e48d')"}
			}
		}
	},
	AdditionalData = new Dictionary<string, object>()
	{
		{"template@odata.bind", "https://graph.microsoft.com/v1.0/teamsTemplates('educationClass')"}
	}
};

await graphClient.Teams
	.Request()
	.AddAsync(team);
```

**Comment by ChetanSharma-msft** [comment]
Hello @bretthacker - Could you please confirm if your issue has resolved with above suggestion or still looking for any help?

**Comment by bretthacker** [comment]
Sorry for the delay. OK, this will clearly require me to rev the SDK again. I sincerely regret having adopted the SDK and not just called REST directly - every time I have to upgrade it creates a rat's nest of dependency errors, some of which result in breaking changes against other components that have their own issues.

Taking a look at this, will get back. Can you please post a sample articulating this setting using REST/JSON, as I may leave the version as is and make this specific call directly just to work around the broken SDK.

**Comment by ChetanSharma-msft** [comment]
Hello @bretthacker - Sorry for delay in response.
We will look into it and let you know the updates.

**Comment by sayali-MSFT** [comment]
@bretthacker -Currently, it is available in beta version.
Microsoft Graph SDKs use the v1.0 version of the API by default, and do not support all the types, properties, and APIs available in the beta version. For details about accessing the beta API with the SDK, see [Use the Microsoft Graph SDKs with the beta API](https://learn.microsoft.com/en-us/graph/sdks/use-beta).
APIs under the /beta version in Microsoft Graph are subject to change. Use of these APIs in production applications is not supported.

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/07b348612cf75786084c8822596fab27e00ddf91/src/Microsoft.Graph/Generated/model/Team.cs#L49

**Comment by lramosvea** [comment]
Closing as this issue seems to be resolved. Please feel to reopen otherwise.
