### ISSUE TITLE
Publish Teams app failed with BadRequest error

### ISSUE THREAD

**Issue by nliu-ms** [microsoftgraph/microsoft-graph-docs#17671]
It only happen for a specific tenant, we use this tenant for CI/CD. We will call this API to publish a Teams app per day. It works for a few months, and all of a sudden, it constantly respond with a **BadRequest** error.

I'm wondering if there's any fraud detection strategy? If so, how can I recover this tenant? Otherwise we need to migrate to different tenants again and again. Thanks!

```
Tenant id: d85e8d90-95a6-4c9f-a8a1-0dad203412bf

API: https://graph.microsoft.com/v1.0/appCatalogs/teamsApps?requiresReview=true
{
    "error": {
        "code": "BadRequest",
        "message": "BadRequest",
        "innerError": {
            "message": "",
            "code": "BadRequest",
            "innerError": {},
            "date": "2022-07-13T06:26:02",
            "request-id": "f8c4dcad-66ca-45cf-a14b-89e962db2507",
            "client-request-id": "f8c4dcad-66ca-45cf-a14b-89e962db2507"
        }
    }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc580041-9ed5-dc21-2eb1-813152044527
* Version Independent ID: b229cada-3a68-38b5-4236-7cd0d970679f
* Content: [Publish teamsapp - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/teamsapp-publish.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@nliu-ms -We do a hard delete on staged apps, Could you please try a delete and then upload a new one?
Also , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by nliu-ms** [comment]
Hey @sayali-MSFT  @ChetanSharma-msft , just wondering if there's any updates on this issue. Thanks!

**Comment by sayali-MSFT** [comment]
@nliu-ms -Have you try this, We do a hard delete on staged apps, Could you please try a delete and then upload a new one?

**Comment by nliu-ms** [comment]
Hey @sayali-MSFT , I just find a button "Reject" in Teams admin center. Is it what you mean by "hard deletion"? 

Or do I need to delete the stagged app with Graph API: https://docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&tabs=http

![image](https://user-images.githubusercontent.com/71362691/189842896-88db143e-7a9e-42aa-a5de-206c3dea466e.png)

**Comment by sayali-MSFT** [comment]
@nliu-ms -In Teams Admin center after select App you will get the delete button like below-
If not then you can try with Graph API.
Graph API- `DELETE https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/06805b9e-77e3-4b93-ac81-525eb87513b8`
![admin](https://user-images.githubusercontent.com/93527375/189845084-bdb149de-dfb5-418c-ac41-2bcf603a8b18.png)

**Comment by nliu-ms** [comment]
Thanks @sayali-MSFT , I missed that button. I will try to hard delete my stagged apps to see if it works.

**Comment by ChetanSharma-msft** [comment]
Hello @nliu-ms - Please confirm whether your issue has resolved or still looking for any help here ?

**Comment by nliu-ms** [comment]
Thanks @ChetanSharma-msft  and @sayali-MSFT , hard deletion works for me.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
