### ISSUE TITLE
Mapping AAD built-in roles to permissions scopes

### ISSUE THREAD

**Issue by meggarlandmsft** [microsoftgraph/microsoft-graph-docs#17704]
Hi, the Graph permissions reference is very helpful (https://docs.microsoft.com/en-us/graph/permissions-reference). Is there a mapping anywhere in Microsoft docs with what AAD built-in roles align to different permission scopes? For our product, I am trying to understand what AAD built-in roles are required to perform any task, and we would like to be able to do this by examining AAD built-in roles required to call different APIs available on our service. I have not been able to find anything public on this. 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you, @meggarlandmsft, for asking this question and we appreciate your positive feedback about the permissions reference.

> Is there a mapping anywhere in Microsoft docs with what AAD built-in roles align to different permission scopes?

Azure AD built-in roles (RBAC) don't technically align with Microsoft Graph permissions. Rather, they align with the Microsoft Graph operations. For example, an operation like "read user properties", aka GET /users. No RBAC role aligns with the _User.Read.All_ permission; but some RBAC roles like the Global Admin and Global Reader roles align with a read user operation that may be defined in the RBAC world as microsoft.directory/users/allProperties/read.

Not all APIs and operations require [Azure AD built-in roles](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference). For some APIs, simply having the right permission and being a "member" user type may be enough to call the API. For example, retrieving all groups and all users.

I don't think there are any Microsoft Graph APIs you can call with just an RBAC role and 0 Microsoft Graph permissions.

That said, a lot of APIs relating to write operations - Create, Update, Delete - do require some Azure AD built-in role _in addition to_ the Microsoft Graph permission. The role requirements for such APIs are indicated within the **Permissions** section of the respective API doc. For example in [Create administrative unit](https://docs.microsoft.com/en-us/graph/api/directory-post-administrativeunits?view=graph-rest-1.0&tabs=http#permissions).

> For our product, I am trying to understand what AAD built-in roles are required to perform any task, and we would like to be able to do this by examining AAD built-in roles required to call different APIs available on our service.

I recommend checking the info on the API page relating to the API your app wants to call. That will allow you to know any RBAC role required in addition to the permissions.

A quick tip: you also have an option of creating **custom roles** off the Azure AD built-in roles. That allows you even more fine-grained access control than the Azure AD built-in roles. See more [here](https://docs.microsoft.com/en-us/azure/active-directory/roles/custom-create).

LMK if this helps.

**Comment by meggarlandmsft** [comment]
Thank you, Faith, for your detailed explanation! That does help, I do have a follow up question.

Azure AD built-in roles (RBAC) don't technically align with Microsoft Graph permissions. Rather, they align with the Microsoft Graph operations. For example, an operation like "read user properties", aka GET /users. No RBAC role aligns with the User.Read.All permission; but some RBAC roles like the Global Admin and Global Reader roles align with a read user operation that may be defined in the RBAC world as microsoft.directory/users/allProperties/read.
Is there a mapping of Azure AD built-in roles (RBAC) to Microsoft graph operations? Or, is there a common pattern that can be distinguished by cross-referencing Microsoft Graph operations and RBAC roles, like in your example of GET /users?

Here is more context on our scenario, which may help:

Our application is M365 Lighthouse<https://docs.microsoft.com/en-us/microsoft-365/lighthouse/m365-lighthouse-overview?view=o365-worldwide>, which is a multi-tenant management tool that Managed Service Providers (MSPs) use to manage and secure their small and medium-sized customers. MSPs use Granular Delegated Admin Privileges (GDAP)<https://docs.microsoft.com/en-us/partner-center/gdap-introduction> roles - a subset of Azure AD built-in roles - to manage their customers' environments. MSPs can take action that initiates an API call from M365 Lighthouse to the respective workload. For example, they can dismiss user risk on behalf of their customers (Dismiss riskyUser - Microsoft Graph beta | Microsoft Docs<https://docs.microsoft.com/en-us/graph/api/riskyusers-dismiss?view=graph-rest-beta&tabs=http>). The permission scope for this API is IdentityRiskyUser.ReadWrite.All. To dismiss a customer use'rs risk from our app, the MSP user initiates the action on behalf of a customer, then the app checks if the MSP user has any GDAP role for that customer. If they do, the app lets them proceed - then the underlying workload (i.e. AAD in this case) blocks the action or completes the necessary authorization if they have an appropriate role.

That said, we have a list of APIs available to call from M365 Lighthouse, and we're trying to determine what GDAP roles are required for each API. We're especially curious if any of the APIs can only be called with delegated Global Admin, and no other delegated role.

Thanks again!

Meg Garland | Program Manager
Microsoft | New York, NY
Office: +1 (212) 835-8735 | ***@***.******@***.***>

[Microsoft]

**Comment by FaithOmbongi** [comment]
_PS: GitHub doesn't apply Markdown format to email responses well so I hope I've captured all your questions in my reply below_


> Is there a mapping of Azure AD built-in roles (RBAC) to Microsoft graph operations? Or, is there a common pattern that can be distinguished by cross-referencing Microsoft Graph operations and RBAC roles, like in your example of GET /users?

Yes, there is. The mapping isn't in form of a Graph API URL like `GET https://graph.microsoft.com/users`, but is indicated as a set of actions like `microsoft.directory/users/standard/read`. Find [an RBAC role and see its list of allowed actions](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference).

> That said, we have a list of APIs available to call from M365 Lighthouse, and we're trying to determine what GDAP roles are required for each API. We're especially curious if any of the APIs can only be called with delegated Global Admin, and no other delegated role.

Back to my initial recommendation:
1. Check the API doc for the API you want to call
2. In the **Permissions** section of that API doc, find more information about possible RBAC requirements for that API

I'm aware of only one set of APIs that can be called by the global admin only - but there's a fix underway for the API to support lesser-privileged RBAC roles. All APIs that have RBAC requirements should allow lesser-privileged admin roles and you should never need only the Global Admin (Please raise a doc issue if you identify any APIs that don't).
