### ISSUE TITLE
v1.0 and beta endpoints for creating Groups

### ISSUE THREAD

**Issue by dzhavat** [microsoftgraph/microsoft-graph-docs#1770]
Just noticed that the documentation for [v1.0](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_post_groups) and [beta](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/group_post_groups) endpoints related to creating Groups is very much the same.

I've been using the beta endpoint for a few weeks now and discovered v1.0 today by accident. That made me wonder for how long has this been available? 

Since there is a stable v1.0 endpoint wouldn't it be better to drop/deprecate the beta or at least put some kind of message in the documentation page that makes people aware of v1.0?

**Comment by jannikb-sim** [comment]
As I understand it both endpoints are under active development. The v1.0 is stable  (only new stuff gets added), whereas the beta endpoints will have breaking changes. So do not use the beta for production.
At some point in time out of the beta endpoint will evolve a v2.0 endpoint (my assumption).

**Comment by dzhavat** [comment]
I see. It makes sense. My suggestion then would be to just have a short message/note in the documentation page for the beta endpoint that point people to the v1.0 endpoint since it's already available.

**Comment by jannikb-sim** [comment]
this seems to be a place for feature requests and feedback https://officespdev.uservoice.com/forums/224641-general/category/101632-microsoft-graph-o365-rest-apis

**Comment by mlafleur** [comment]
The list of changes dating back to December 2015 are cataloged in the [Changelog](https://developer.microsoft.com/en-us/graph/docs/concepts/changelog). This page includes additions, subtractions and changes to the API as well as noting when endpoints are moved from `beta`  to `v1.0`. The ability to create Groups  has been in v1.0 long enough that it predates the Changelog.

In general, you should never use a `beta` endpoint in production. They fairly regularly see breaking changes without warning. They're also not supported so issues you run across are not easily resolved. They are suitable for testing vNext APIs but that is all they should be used for.
