### ISSUE TITLE
Graph: Filter Calendar Events by Attendees

### ISSUE THREAD

**Issue by JeroenKocyigit** [microsoftgraph/microsoft-graph-docs#1771]
When calling `me/events?$filter=attendees/any(a: a/emailAddress/address eq '')`:

I get the following error:

``` javascript
{
  "error": {
    "code": "UnsupportedEntityExpression",
    "message": "'i => i.Attendees.Any(a => (a.EmailAddress == ""))' is not a supported filter expression.",
    "innerError": {
      "request-id": "0f6b84c5-d037-4053-88f2-7df86807d6fd",
      "date": "2017-09-29T10:07:28"
    }
  }
}
```
does anyone know why?

**Comment by koreanilkumar** [comment]
Can we filter the results based on attendees?. any fix available?

**Comment by mlafleur** [comment]
This is expected behavior. The API does not support filtering for empty/null values (i.e. `''` or `null`).

**Comment by koreanilkumar** [comment]
But, I have the email address in result 'abc@xyz.com'
I'm getting the same error

Request [GET]
https://graph.microsoft.com/v1.0/me/calendar/events?$select=subject,body,bodyPreview,organizer,attendees,start,end,location&$filter=attendees/any(a: a/emailAddress/address eq 'abc@xyz.com')

Response:

{
    "error": {
        "code": "UnsupportedEntityExpression",
        "message": "'i => i.Attendees.Any(a => (a.EmailAddress == \"abc@xyz.com\"))' is not a supported filter expression.",
        "innerError": {
            "request-id": "b86bc0f9-5cbf-4d3a-a7c2-63577762f12e",
            "date": "2018-05-31T06:58:29"
        }
    }
}

**Comment by howardcho** [comment]
I am also having the same issue; I really only need events which have an attendee. I've tried the below queries, which seem to be structured properly:

Request:
`https://graph.microsoft.com/v1.0/me/events?$filter=attendees/any(e:e/type eq 'required')`

Response:
`{
    "error": {
        "code": "ErrorInvalidUrlQueryFilter",
        "message": "The query filter contains one or more invalid nodes.",
        "innerError": {
            "request-id": "aaae9ee9-33fc-415b-93ba-aa70292ee300",
            "date": "2018-08-01T01:04:32"
        }
    }
}`

Another request:
`https://graph.microsoft.com/v1.0/me/events?$filter=attendees/any(e:contains(e/emailAddress/address,'@')`

Response:
`{
    "error": {
        "code": "BadRequest",
        "message": "Invalid filter clause",
        "innerError": {
            "request-id": "e2477b59-4ace-4ffd-bee6-cc8ef4519248",
            "date": "2018-08-01T01:05:48"
        }
    }
}`

**Comment by mlafleur** [comment]
Microsoft Graph doesn't support drilling down multiple levels of relationships like this (`a/emailAddress/address`). You cannot only filter one relationship "hop" from the parent resource. 

Also, `contains` itself is not a [supported string operator for `$filter`](https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters#filter-parameter).

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
