### ISSUE TITLE
There is no docs with info consent permission through graph explorer required admin consent. 

### ISSUE THREAD

**Issue by Vickyk1** [microsoftgraph/microsoft-graph-docs#17729]
For the basic permission which doesn't require admin consent), like- chat.read (as you can see in screenshot, it doesn't need admin consent , while granting permission why it is asking admin consent, why there is no proper docs, which says for every permission you consented from graph required admin consent. 
![image](https://user-images.githubusercontent.com/99316327/179684144-fde75c23-f653-481d-8dd2-2da9d2239616.png)

---
#### I read several docs ,none of them has this info - https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/admin-consent-workflow-overview 
https://docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&tabs=http

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c6947-060a-84a7-6bda-d911789467f5
* Version Independent ID: e544b432-1b2a-dbff-8c05-57118a223d1b
* Content: [Get chatMessage in a channel or chat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chatmessage-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Your admin can choose for some or all permissions to require admin consent. The setting shown here is the 'default' behavior. But admins can choose to override this. Please refer to https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-permission-classifications?tabs=azure-portal and https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent
