### ISSUE TITLE
The type of the value doesn't match the property whose type is DateTime on filter=employeeHireDate

### ISSUE THREAD

**Issue by pagejustin** [microsoftgraph/microsoft-graph-docs#17744]
https://graph.microsoft.com/v1.0/users?$count=true&$filter=employeeHireDate ge 2022-07-15
Headers: ConsistencyLevel:eventual

Returns the error

...
"error": {
    "code": "Request_UnsupportedQuery",
    "message": "The type of the value doesn't match the property whose type is DateTime",
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Azure AD directory objects - Microsoft Graph](https://docs.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#support-for-filter-on-properties-of-azure-ad-directory-objects)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/aad-advanced-queries.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Licantrop0
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Licantrop0** [comment]
Hi @pagejustin all DateTimeZones need to be formatted according to the ISO 8601 standard, [try this in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24count%3Dtrue%26%24filter%3DemployeeHireDate%2Bge%2B%3Cvalue%3E%26%24select%3Did%2CdisplayName%2CemployeeHireDate&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d):
```https://graph.microsoft.com/v1.0/users?$count=true&$filter=employeeHireDate ge 2022-07-15T00:00:00Z
Headers: ConsistencyLevel:eventual```
