### ISSUE TITLE
one drive copy method between two different drives fails with 504 gateway timeout with large files > 10MB

### ISSUE THREAD

**Issue by abdulkareemnalband** [microsoftgraph/microsoft-graph-docs#1777]
stackoverflow question [link](https://stackoverflow.com/q/46558011/1859367)

[Copy Item](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_copy) method fails with 504 gateway timeout when file is copied from group drive to user's personal drive with large file.

Method works fine when file size is small (tested with 170KB)

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).

**Comment by landall** [comment]
https://stackoverflow.com/questions/46480494/onedrive-copy-item-using-microsoft-graph-sdk-gatewaytimeout-at-10-seconds-if

As metioned in this thread:
Api works fine for both large and small file, but method returns 504 gateway time for large files, – AbdulKareem Oct 4 '17 at 16:30

so is it a bug or a document error?
