### ISSUE TITLE
Casing on the key 'Value' should be all lowercase

### ISSUE THREAD

**Issue by pettewayshade** [microsoftgraph/microsoft-graph-docs#17798]
For the **"Example 2: User requests a package and answers questions for approval"** section in the doc, casing on the key "Value" inside of **answers** seems to be strict and is expecting all lowercase. The sample will throw a "The model is invalid error" when ran because of this. 

1. The doc should be updated with the correct case
2.  The case on other keys has no effect, but only on the key 'value' where it is expected to be all lowercase. Can this be updated? This will cause confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813866f8-92ef-246c-5288-7d22a44b2f99
* Version Independent ID: a6c111a0-ddcd-1570-e82b-a0b5e8f83095
* Content: [Create accessPackageAssignmentRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/entitlementmanagement-post-accesspackageassignmentrequests?view=graph-rest-beta&tabs=powershell)
* Content Source: [api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/entitlementmanagement-post-accesspackageassignmentrequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @pettewayshade - to make sure I've understood what you've encountered correctly...do you mean the String value inside the **value** property is case-sensitive and must be in all lowercase? Like "Arizona" and "Need access to marketing campaign material" should be in all lowercase?

**Comment by pettewayshade** [comment]
Hello @FaithOmbongi  - No, the actual property/key named 'Value' should be all lowercase. 

```Value = "Arizona" --> value = "Arizona"```

Also, besides updating the script to have the correct casing, is it possible to update the property so that it is not case-sensitive? This can be confusing as the other properties/keys do not have the same requirement.

**Comment by FaithOmbongi** [comment]
Hmm, I can't locate any doc instance where the "value" property has the "V" in caps. Could you share a screenshot?

> Also, besides updating the script to have the correct casing, is it possible to update the property so that it is not case-sensitive? This can be confusing as the other properties/keys do not have the same requirement.

I can share this request with the engineering team but making properties case-sensitive is an allowed practice in the OData protocol. But I'll pass on the suggestion to the engineering team.

**Comment by pettewayshade** [comment]
My apologies, I realize I did not mention that sample with the issue. The issue is with the PowerShell example.

![image](https://user-images.githubusercontent.com/15715637/180458047-612cd067-bac7-45f1-aa92-2b4c63d3cf61.png)

My suggestion to the engineering team would be to be consistent throughout, as all other properties in the PS sample are not case-sensitive.

**Comment by FaithOmbongi** [comment]
Ah, got it. 

I believe properties in PowerShell are mostly PascalCased, so "Value" is correct. But at the same time, I agree with you that case sensitivity doesn't apply to PowerShell AFAIK.

Because this isn't a doc but an SDK issue, I'm closing this issue here but filing another in the PowerShell SDK repo where it'll get better visibility.
