### ISSUE TITLE
Able to fetch direct reports without permissions on listed on documentation 

### ISSUE THREAD

**Issue by jwccit** [microsoftgraph/microsoft-graph-docs#17792]
I am able to get my list direct reports, `/me/directReports`, when using permissions not listed on the documentation

The documentation lists `User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All` which all need admin consent, but by using both `User.Read` and `User.ReadBasic.All` I am able to pull back my direct reports. 

Is the documentation missing or is this an issue with the MS Graph?

**Request made on MS Graph Explorer**
![image](https://user-images.githubusercontent.com/74728196/180175583-913e9761-3c69-4c66-ae56-10910878f78e.png)

**Access Token Scopes**
![image](https://user-images.githubusercontent.com/74728196/180175745-fa0d2d05-9609-4205-b2c2-0a11650b0720.png)

**MS Graph enterprise application for used tenancy**
![image](https://user-images.githubusercontent.com/74728196/180175902-3da6c0d2-b126-48d7-9d2c-409a2eef781f.png)

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9cc449-510b-0110-e2e7-bfa47eb4bfe5
* Version Independent ID: 4ce7f9ed-8e86-5d7b-99d5-ff5d5af5dce6
* Content: [List directReports - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-directreports?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-directreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-directreports.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jwccit for highlighting this doc gap. I've reproduced this behavior and yes, `User.Read` and `User.ReadBasic.All` is the least privileged permission combination required to retrieve my direct reports. I've raised a PR to update the documentation.
