### ISSUE TITLE
Link to Graph Explorer redirects to old Graph portal

### ISSUE THREAD

**Issue by OfficeGSX** [microsoftgraph/microsoft-graph-docs#1782]
Hello,

Link to Graph Explorer at the end of the topic "Try out sample REST calls in our API Explorer." is redirecting to the old Graph portal. Please update the link to ensure the link redirects to the new Graph portal.

Topic: [https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/get-started.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/get-started.md)

Incorrect link: https://graph.microsoft.io/graph-explorer
Correct link:  https://developer.microsoft.com/en-us/graph/graph-explorer

Thanks,
Petr

**Comment by Lauragra** [comment]
This link has been fixed. Thanks.
