### ISSUE TITLE
App registration with new flow failed. Status code 401

### ISSUE THREAD

**Issue by leahpeker** [microsoftgraph/microsoft-graph-docs#17838]
[Enter feedback here]
I'm getting the following error:
App registration with new flow failed. Status code 401 .MS-CorrelationId: bc2be85d-a684-427e-bf9a-6a195ef552dc

Unsure of what is triggering the error and how to resolve it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2966c1-2bc1-adf7-3328-d1f4d4c583b2
* Version Independent ID: 484b0243-f009-a275-0ba2-1f886c80c48b
* Content: [Microsoft Graph quick start FAQ](https://docs.microsoft.com/en-us/graph/quick-start-faq)
* Content Source: [concepts/quick-start-faq.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/quick-start-faq.yml)
* Product: **non-product-specific**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by leahpeker** [comment]
Additional context:

I'm trying to use the [quick start](https://developer.microsoft.com/en-us/graph/quick-start?code=0.ARMAR-jB8tJboku15LUppkXzGklfR1jC_qZOg9x1EEvAbPMTAAQ.AgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P8MBornMqS-5pFEXO0a8RC9wY0AerwMUQICbsKcyVY4zRNOzMroSeXpmDKT3MFY2DEEvXZ8cSFa3pGZHiutUNfiyEICE66rsWJpLvh2GldBRYv4OsFALhd4CkJ0iZ_VVkgdLgJAbzVBIGN1Q7izVGIE9aw8F8u2E5MmfzacHeGft1e3qhEnLW-CpE8gaEYH0QynuI3ReIInsYWdjOftDUIkWna9ZKR5Aci4zGagW8y3QOGG6J0XEeIFCWV_7F1KRXgd3Y3l0UfDPsmsSGhjXsPg9OJs4QtoOsWC3O5bfS2XLvMdvxcXmkQmgOb-gVHo19h4Y8Yf_hjy4kz3gIYUWDSPzRcQIFVl6kfvhc4BQvPPrZVEBDRm3ad4ab2DqdJWNRyuJ6BqOsdATugd4yvQ1g1ftco_67uZ7uK5WoAhrVFt1boAmW8lkKIjjC3Zcs-Dra_W6Dk6XQyzP1eTzw9mQYIkjoCIkRhzq1cWTShnTxelI88CVcde78wvHe6XYE_K5cXJfxm4bsi7JBXeFhapKCnQC63HMNVZvAV5CoSOnR0wIVyIA-TuoaCMV-hQqLX1lKNCELzZwyrmbEIY9mNuRR9VFiqVZGdgQwA7au_mEkhoYYoFCtSYFPssKg6cI2twxDmEG_4MjjqWOebCTH9b-cSiVpqpWZRTcpv3WGTXrF0&state=option-python&session_state=ef406b49-cf89-49b3-8582-7c5f3665a895)

Step 2 - Get a Client ID brings me to the login page. When I log in and enter my password, it returns me to the quickstart guide with the step incomplete and a dialog box with the error.

**Comment by jasonjoh** [comment]
Hi @leahpeker! A 401 status indicates that you aren't authorized to register an application. Are you using a work email to sign in to the tool? If so, your admins may have disabled your ability to register applications.

To test if this is indeed the case, you can go to https://aad.portal.azure.com and attempt to register an app following these instructions: https://docs.microsoft.com/graph/tutorials/dotnet?tabs=aad&tutorial-step=1.

**Comment by jasonjoh** [comment]
Yes unfortunately you'll need to contact your organization admins for assistance. Another option if you're looking for a test environment is to get a developer tenant through the [Microsoft 365 Developer Program](https://developer.microsoft.com/microsoft-365/dev-program).
