### ISSUE TITLE
Powershell cmdlet doesn't exist

### ISSUE THREAD

**Issue by t0w0ru** [microsoftgraph/microsoft-graph-docs#17862]
The article describes a way to list access review definitions via the 
Get-MgIdentityGovernanceAccessReviewDefinition
cmdlet.
This cmdlet doesn't exist anywhere in the Microsoft.Graph.Identity.Governance module,
nor anywhere else in the psgallery
The cmdlet is equally wrong in the other [Access-Review-Schedule-Definition-methods](https://docs.microsoft.com/en-us/graph/api/resources/accessreviewscheduledefinition?view=graph-rest-1.0#methods)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f25102f2-2cb7-c46b-864c-dec1d017de95
* Version Independent ID: 08a487ef-341a-6937-fce5-b1e72bc1d509
* Content: [List definitions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/accessreviewset-list-definitions?view=graph-rest-1.0&tabs=powershell)
* Content Source: [api-reference/v1.0/api/accessreviewset-list-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accessreviewset-list-definitions.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @zhusijia26
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @t0w0ru - I can't locate **Get-MgIdentityGovernanceAccessReviewDecisionInstanceDefinition** anywhere in the documentation. Could you share an anchor link and a screenshot?

**Comment by t0w0ru** [comment]
My bad, its Get-MgIdentityGovernanceAccessReviewDefinition, which still doesn't exist in any module on the psgallery

**Comment by t0w0ru** [comment]
https://docs.microsoft.com/en-us/graph/api/accessreviewset-list-definitions#:~:text=Graph.Identity.Governance-,Get%2DMgIdentityGovernanceAccessReviewDefinition,-%2DTop%20100%20%2DSkip

**Comment by FaithOmbongi** [comment]
I've confirmed this. I opened related issues in the PowerShell SDK repo and I've replied to the threads for the team to look into this:

+ https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1291
+ https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1286

Closing this issue here and tracking it via the PowerShell SDK repo.

cc @msewaweru to help with tracking
