### ISSUE TITLE
Audit events are not working for v1.0 but it works for beta 

### ISSUE THREAD

**Issue by DebugwithDJ** [microsoftgraph/microsoft-graph-docs#17882]
Hi Team, 

The Audit events are not working for v1.0 version of this API and it is giving 400 bad request however the beta version is working as expected.

Client ID and timestamp.

        "date": "2022-07-28T01:48:02",
            "request-id": "f8f5e188-6e42-4680-be97-41785340bbd5",
            "client-request-id": "df8fedfa-7718-dd86-7ab4-0d1c67b9652b"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c30c92f-f500-573e-fdae-224b288f2f69
* Version Independent ID: 351b1de3-a3aa-f18c-3cf3-6aefc6200931
* Content: [List auditEvents - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-auditing-auditevent-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-auditing-auditevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-auditing-auditevent-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jaiprakashmb** [comment]
Currently AuditEvent is only supported in beta, v1.0 support will be added in near future as currently work still in progress.
We have active work item update Intune docs to reflect the same.

Thanks.

**Comment by DebugwithDJ** [comment]
Thank you for the confirmation.

**Comment by jaiprakashmb** [comment]
V1.0 docs have been updated to remove unsupported content. Once AuditEvents is released in v1.0 we will republish docs. 

Thanks @DebugwithDJ, will close this thread. Feel free to re-open in case necessary.
