### ISSUE TITLE
Missing options for application access token

### ISSUE THREAD

**Issue by AlexFilipin** [microsoftgraph/microsoft-graph-docs#17911]
It seems like when you request an application access token via Postman you have to specify the resource in Postman's advanced options which is missing in this guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Can you elaborate? I assume you mean the **Resource** field in the **Advanced Options**? You should not have to put anything there.

**Comment by AlexFilipin** [comment]
Yep, exactly with the resource field set to https://graph.microsoft.com I get a token with "aud": "https://graph.microsoft.com", roles claim etc. 

Without the resource field I get a token for "aud": "00000002-0000-0000-c000-000000000000"

**Comment by jasonjoh** [comment]
Hmmm - that sounds like maybe an old version of the Postman collection using the Azure v1 endpoints. What is the value in your **Access Token URL** field in the **Configuration Options**? Also, do you see `https://graph.microsoft.com/.default` in the **Scope** field?

**Comment by AlexFilipin** [comment]
Ahh okay, yes, I was using v1 endpoints which seem to need the resource. With v2 endpoints everything is fine without providing a resource.

I was using `.default` as scope, not `https://graph.microsoft.com/.default` but even with the later the v1 endpoint needs the resource specified on top of it.

PS: I was following the documentation without forking as I already had a collection for small area of Graph calls relevant to me, hence the mistake. Maybe worth a note in the docs for other folks that follow it without forking but I understand that may go beyond the scope of the documentation.

**Comment by AlexFilipin** [comment]
Feel free to close this issue unless you want to keep it open in case you want to add a note :)

**Comment by jasonjoh** [comment]
Thanks Alex, glad we could figure it out. Yeah, you do definitely have to use the full `https://graph.microsoft.com/.default` to ensure it gets the right `aud`.

**Comment by AlexFilipin** [comment]
@jasonjoh so to be clear the "partial" `aud` was not the issue, using v2 endpoints even `.default` as `aud` works fine but v1 needs the resource in the advanced options no matter if you specify `https://graph.microsoft.com/.default` or `.default`

Anyways all good 👍
