### ISSUE TITLE
The Create Method listed in documentation is not working as expected

### ISSUE THREAD

**Issue by DebugwithDJ** [microsoftgraph/microsoft-graph-docs#17977]
"error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation with http verb POST for request /StatelessOnboardingService/deviceManagement/complianceManagementPartners.",
}

Something seem to be missing in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d2e50b0-ca61-0ed6-e7cf-1ec62e8e68b0
* Version Independent ID: 6bcc8f6f-ed0a-51d6-a29a-cc52868de082
* Content: [Create complianceManagementPartner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-onboarding-compliancemanagementpartner-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-onboarding-compliancemanagementpartner-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/intune-onboarding-compliancemanagementpartner-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
My suggestion would be to go through the flow in the console and use F12 developer tools to trace the API calls.  You can then replicate that call in your code.  Unfortunately, we have automated tools that generate the API documentation, and sometimes the routes are mis-identified as in this case.
