### ISSUE TITLE
Service principal cannot update users in any directory role

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs#17991]
A Service Principal cannot update any user that is in a directory role, even the role Directory Reader.  The Service principal must be in a higher level role to be able to update users in directory roles.  There is a escalation ticket related to this you can ping me for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @jpettere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jpettere** [comment]
Hi @RayGHeld - what user MS Graph permissions does the service principal have?

**Comment by jpettere** [comment]
Closing as the corresponding support case has been resolved. We'll be adding a note to the doc that mentions sensitive properties for admin users or users in a role-assignable group can't be updated by app only permissions unless the app is assigned one of the roles specified here: [Azure AD built-in roles - Azure Active Directory - Microsoft Entra | Microsoft Docs](https://docs.microsoft.com/en-us/azure/active-directory/roles/permissions-reference#who-can-update-sensitive-attributes)
