### ISSUE TITLE
Include Groups/Photo in Groups/Group documentation

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-docs#18]
Given that retrieving Group's photo is a single Group operation rather than operation on the Groups collection, it would be more intuitive if the Get photo task was listed in the Groups/Group section.

**Comment by sumurthy** [comment]
That's  a good point. The grouping of "methods" today is based on where the API is available (collection or object) vs. where it should be listed. We are planning on re-arranging that to make it more easier to find.. in logical places. Thanks for your suggestion.

**Comment by waldekmastykarz** [comment]
You're welcome! I don't know if the system that you are using for publishing content from GitHub supports it, but it would be great if a single page could appear in multiple logical locations where the corresponding API can be used. This would allow for maintaining the content in a single place and reuse it across the different endpoints.

**Comment by keyur32** [comment]
Marking this as closed as this was resolved a while back. Get photo is listed under groups.
