### ISSUE TITLE
Add "Z" at the end of event time

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1800]
For `event.start.dataTime` and `event.end.dataTime`, right now the format is
```
2017-10-12T00:00:00.0000000
```
we should add **Z** at the end like below since it is standard. (Other fields such as `lastModifiedDateTime` are correct which have **Z** at the end)
```
2017-10-12T00:00:00.00Z or 2017-10-12T00:00:00.0000000Z
```

> [The Z stands for the Zero timezone, as it is offset by 0 from the Coordinated Universal Time (UTC).](https://stackoverflow.com/a/29282022/2000548)

Otherwise it may cause unexpected error when using time libraries such as moment.js

```
console.log(moment('2017-10-12T00:00:00.0000000').local().hour());      // 0
console.log(moment.utc('2017-10-12T00:00:00.0000000').local().hour());  // 17
console.log(moment('2017-10-12T00:00:00.0000000').hour());              // 0, wrong, should be 17

console.log(moment('2017-10-12T00:00:00.00Z').local().hour());          // 0
console.log(moment.utc('2017-10-12T00:00:00.00Z').local().hour());      // 17
console.log(moment('2017-10-12T00:00:00.00Z').hour());                  // 17
```

<kbd>[jsbin](http://jsbin.com/rumolivawe/1/edit?js,console)</kbd>

**Comment by jasonjoh** [comment]
No, this isn't correct. You're assuming this value is always in UTC, and it isn't. The time zone is controlled by the `Prefer: outlook.timezone` header. You need to look a the value of `event.start.TimeZone` as specified in the [docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/datetimetimezone) to determine the correct time zone.

**Comment by Hongbo-Miao** [comment]
Oh, thanks. I didn't realize that. But it will give more work for developers to convert based on the `timeZone` field. Is there a reason that just not simply return a UTC time?

Another doc issue, I cannot find the value `UTC` I got in [docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/datetimetimezone).
![image](https://user-images.githubusercontent.com/3375461/31457540-ec6c15a6-ae71-11e7-811e-1378e59161c4.png)

**Comment by jasonjoh** [comment]
You can use the header I mentioned above to set a preferred time zone and get your dates back pre-converted. If you don't use the header I believe they always come back in UTC. Either way I would advise checking the `timeZone` value to make sure you handle it correctly.

**Comment by Hongbo-Miao** [comment]
Thanks for help. I will close this one and create another doc issue.
