### ISSUE TITLE
Migration mode + attachments

### ISSUE THREAD

**Issue by cabadam** [microsoftgraph/microsoft-graph-docs#18002]
This is very similar to a concern previously raised here:
https://github.com/microsoftgraph/microsoft-graph-docs/issues/10206

However, we have an additional quirk that was not covered in that issue.  In general, the workaround identified in that issue was:

1. Retrieve the primary/general channel.
2. Use a delegated authentication client to query /filesFolder for the primary/General channel.
3. Loop Step 2 until it is successful.  This is supposed to provision the sharepoint storage.
4. Retrieve the private channel that you need /filesFolder for.
5. Use a delegated authentication client to query /filesFolder for this private channel.
6. Loop Step 5 until it is successful.

In our case, we are migrating existing data from another system, so the team and channels are created in "migrationMode".  This breaks Step 2 - a delegated authentication client is apparently unable to retrieve properties for a team or channel that is still in migration mode.  A 403 error is returned.  I don't know if the 403 error is because the channel is in migration mode or because the delegated auth user is not a member of the channel.  In any case, that part is moot because members cannot be added to a migration mode team/channel until migration mode is completed (attempting to do ALSO returns a 403).

So, that leaves the question:  How do we migrate in backdated posts (which requires an application authentication client) that have file attachments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3914d7e5-bbb3-b349-893c-ef01c2938981
* Version Independent ID: 15bc6db6-36cd-cc2b-2b9c-34c30141b89c
* Content: [Get filesFolder - Microsoft Graph v1.0](https://docs.microsoft.com/en-US/graph/api/channel-get-filesfolder?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-get-filesfolder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-get-filesfolder.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@cabadam - We are investigating your query. We will update you soon.

**Comment by cabadam** [comment]
I could, if the SharePoint site corresponding to the new channel existed.  That's the problem.  I can't upload a file to the include as an attachment.

**Comment by Nivedipa-MSFT** [comment]
@cabadam - Could you please explain a bit more what exact issue you are facing? Its not clear from above comment.

**Comment by cabadam** [comment]
So, the use case we're trying to solve:  We are trying to migrate a variety of teams/channels from another system into MS Teams.  A number of the messages in question have file attachments.

Based on our testing with teams interactively (through the Teams application, no migration), when a user attaches a file to a message, the file gets uploaded to the Sharepoint site / folder associated with the team and channel.  So, to migrate such a message, we have to upload the file first to Sharepoint.  Then we can then include that uploaded file as an attachment in a message.  The problem is, that Sharepoint locatoin doesn't exist yet.

The link in my original post described a way to trigger the creation of that Sharepoint location through the Graph API.  However, that process does not seem to work for teams/channels which are in migration mode.

**Comment by Nivedipa-MSFT** [comment]
@cabadam - We are checking this internally. We will update you soon.

**Comment by cabadam** [comment]
> Creating the team will create the sharepoint site as well

Unfortunately, that is incorrect.  That is the whole reason the thread I linked to in my first post exists.  Creating a team does NOT create the sharepoint site.

**Comment by cabadam** [comment]
If it WERE correct (and correct for migration mode), that would definitely solve my problem - i have code that tries to wait and then upload it.  However, that just means it waits forever.

**Comment by cabadam** [comment]
Good afternoon @Nivedipa-MSFT , I wanted to follow-up to see if you had been able to check any further on this.  We're going to have to make a decision soon on how to handle the migration we're trying to go through with respect to file attachments. Thanks

**Comment by Nivedipa-MSFT** [comment]
> sharepoint

Do you mean your code waits to upload and it is not uploading and waiting forever?

**Comment by Nivedipa-MSFT** [comment]
@cabadam - We are checking this with engineering team. We will let you know once we have any updates on it.

**Comment by Nivedipa-MSFT** [comment]
@cabadam - Could you please share the logs to investigate further?

**Comment by ChetanSharma-msft** [comment]
Hello @cabadam - Hope you are doing well!!
Could you please share the logs, so that we can further investigate your issue?

**Comment by cabadam** [comment]
I thought I had replied to this, although obviously it doesn't seem to be there.

What kind of logs are you interested in?  Does the Graph API package have a way to generate logs?

**Comment by ChetanSharma-msft** [comment]
Hello @cabadam - Could you please share the request id, timestamp of your Graph API call so that we can check the detailed logs internally and let you know the updates. 

Thanks!!

**Comment by ChetanSharma-msft** [comment]
> I thought I had replied to this, although obviously it doesn't seem to be there.
> 
> What kind of logs are you interested in? Does the Graph API package have a way to generate logs?

Yes, we have a way to get the error logs from the backend based on the request id, timestamp of Graph API.
Could you please share these details?
