### ISSUE TITLE
completedDate is returned instead of completedDateTime - completedDate cannot be used in OData filter

### ISSUE THREAD

**Issue by tjsawyer** [microsoftgraph/microsoft-graph-docs#18012]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58329c0d-50b2-2b69-b968-e36e4d7c6ad9
* Version Independent ID: 0369ad98-97b9-c193-eff8-3bc1aec1c267
* Content: [accessPackageAssignmentRequest resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accesspackageassignmentrequest.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tjsawyer** [comment]
Documentation is incorrect.  completedDateTime is not returned - it is returned as completedDate.  In addition, completedDate cannot be used as an OData filter.   This is highly inefficient.

......
            "requestType": "UserAdd",
            "requestState": "Delivered",
            "requestStatus": "FulfilledNotificationTriggered",
            "createdDateTime": "2022-08-08T15:07:25.147Z",
            "completedDate": "2022-08-09T20:05:56.523Z",
........


When trying to use as a filter ...
  "error": {
        "code": "InvalidFilter",
        "message": "OData query is invalid: Filter 'completedDate GreaterThan 8/1/2022 11:34:13 AM +00:00 is not supported. .", ........................

**Comment by markwahl-msft** [comment]
You are correct, completedDateTime cannot currently be used as a filter when listing assignmentRequests. It is possible to use createdDateTime, however.

**Comment by FaithOmbongi** [comment]
Thank you @tjsawyer for reporting the error. The doc has been updated. Closing this issue.

**Comment by tjsawyer** [comment]
> You are correct, completedDateTime cannot currently be used as a filter when listing assignmentRequests. It is possible to use createdDateTime, however.

Thanks @markwahl-msft for the suggestion.   My issue is that I am trying to build a nice PowerBI dashboard for our IAM team so they can easy see and report on requests and status.  We have 2000+ packages now and there is no good way to filter in graph and grab only changed items since last update.  Even completedDateTime was less then ideal for this, but still better then grabbing the last 35 days of requests completed using createdDateTime which is what I am doing now.  Any chance of getting a lastModified date on the request itself?  That would be very beneficial.  Also, and I know this is a long shot, but if we could also get who the request is pending in the payload, that would be huge!  Thanks!
