### ISSUE TITLE
Endpoint in the documentation doesn't return an orgContact

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-docs#18027]
The endpoint doesn't return an orgContact, as it is pointing to the /contact resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac63aafb-330a-8bf9-dfe7-dae4bb6263b0
* Version Independent ID: 96c7c458-b558-1a37-a134-e7b0923ad1fb
* Content: [Get orgContact - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/orgcontact-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/orgcontact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/orgcontact-get.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @manuel-falcao-magalhaes for asking this question.

[orgContact refers to organizational contacts](https://docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-1.0) and is managed via the `/contacts` endpoint as per the doc. These are different from personal contacts (outlook contacts, [contact resource type](https://docs.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-1.0)) which are managed via the `/me/contacts` or `/users/{id}/contacts` endpoint. Were you looking for the latter API instead?

**Comment by manuel-falcao-magalhaes** [comment]
You're right, I was thinking of personal contacts, my bad. Thanks for the link to the contact resource type.
