### ISSUE TITLE
Create  a shared channel some times  the channel site can't initialize 

### ISSUE THREAD

**Issue by SheldonQin** [microsoftgraph/microsoft-graph-docs#18037]
[Enter feedback here]
Hi
When I use [Create channel](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http) API to create 
a shared channel some times  the channel site can't initialize(about 1in 20?). With private channel I always can initialize the channel site by click the files tab. But shared channel case we can't initialize it in any way,  and I try to initialize the channel after two weeks when created the channel still won't work.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
We are checking the issue. We will get back to you shortly.

**Comment by Prasad-MSFT** [comment]
@SheldonQin - We tried to repro this issue by creating a shared channel as mentioned and it got created successfully without any issue. PFB the screenshots:
1. 
![image](https://user-images.githubusercontent.com/62237649/184820392-c521ad39-ef43-4993-b3a2-73a91ad6049a.png)
2. 
![image](https://user-images.githubusercontent.com/62237649/184820511-de3d0038-c0d4-4d54-a8c9-bbb7b48cab0c.png)

**Comment by AvePoint-JasonJiang** [comment]
@Prasad-MSFT  Hi
Recently I create a shared channel with graph API has this issue, you can use my data if it's any help.
Tenant ID:a6957f64-1bbb-48aa-bb2a-d41e95e7d181
Team ID:58ae439c-63f6-4798-8af4-4f0d5b8ee634
Channel ID:19:UYjk30MM86jdexxqSvql2puWxmh3h9BdUUtd9f3_OCs1@thread.tacv2
Thanks.

**Comment by Prasad-MSFT** [comment]
@AvePoint-JasonJiang - Could you please share the step along with error details where you are having issue ?

**Comment by SheldonQin** [comment]
@Prasad-MSFT Hi
Sorry use the wrong account, We use the graph API to do some migration test. In this case I follow the steps below.

1. Create team with migration mode.
2. Create some standard channels.
3. Complete channels and teams.
4. Create shared channel (No error in this step).
After this I check the files tab can't open that.

**Comment by Prasad-MSFT** [comment]
@SheldonQin - We created team with migration mode and created standard and shared channel as mentioned.
After that clicked on files tab and was able to open it as shown below:
![image](https://user-images.githubusercontent.com/62237649/184902722-29f290b8-73f6-4372-8604-104ecc8e6234.png)

**Comment by SheldonQin** [comment]
@Prasad-MSFT Hi
Update information, If I use Application Permission to create shared channel there is a good chance to meet this issue.

**Comment by Prasad-MSFT** [comment]
Yes @SheldonQin - While creating channel using Application Permissions, we are also not able to access 'Files' tab. The issue is happening. As work around, please use delegated permission to create the channel.

![image](https://user-images.githubusercontent.com/62237649/185401016-63dbaaab-17a2-4200-ade5-ab0ab1137519.png)

![image](https://user-images.githubusercontent.com/62237649/185400906-50b01b31-3058-4580-a283-2d32c4c643f3.png)

**Comment by SheldonQin** [comment]
Ok, Thanks.
