### ISSUE TITLE
Unable to delete phoneAuthenticationMethod 

### ISSUE THREAD

**Issue by sanalkr** [microsoftgraph/microsoft-graph-docs#18091]
I am trying to delete phoneAutheticationMethod on **Azure AD B2C** tenant

```
DELETE /v1.0/users/{user object id}/authentication/phoneMethods/{id}/ 
Host: graph.microsoft.com
Authorization: Bearer eyJ0eXA....
```

But I keep getting below error 
```
{
    "error": {
        "code": "badRequest",
        "message": "The requested authentication method id of [{phone method id}] matches the user's current default authentication method, and cannot be deleted until the default authentication method is changed",
        "innerError": {
            "message": "The requested authentication method id of [{phone method id}] matches the user's current default authentication method, and cannot be deleted until the default authentication method is changed",
            "date": "2022-08-18T06:00:12",
            "request-id": "cc3cd47c-3dc1-4e27-9b8d-7af002bcc671",
            "client-request-id": "cc3cd47c-3dc1-4e27-9b8d-7af002bcc671"
        }
    }
}
```

How do I change the default authentication method to, let's say, maybe a password? What I am trying to achieve is to reset all MFA options for a User.
Basically, I am trying to replicate the "Require re-register multifactor authentication" functionality. It seems there is no direct way to do it via GraphAPI as per the below documentation link.
https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethod?view=graph-rest-1.0
![image](https://user-images.githubusercontent.com/20180412/185306712-0e58b41b-4a93-4412-be96-868217ab0062.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 699c6d0f-9143-6308-aca5-c1437f652b37
* Version Independent ID: 29ddafa6-e1e1-c210-3ac5-356d0fa09c13
* Content: [Delete phoneAuthenticationMethod - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/phoneauthenticationmethod-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/phoneauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/phoneauthenticationmethod-delete.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @sanalkr for asking this question. There's currently no way to reset the default method using Microsoft Graph as noted in this [comment in the overview doc](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0).

<img width="550" alt="defaultMethod" src="https://user-images.githubusercontent.com/14026935/185343328-087d98e4-1a70-40f8-a1e3-07bb36a214da.png">

Can you check out [the response in this thread](https://github.com/microsoftgraph/microsoft-graph-docs/issues/14470#issuecomment-989712874) and confirm if it unblocks you? There's a feature request for this capability to be available in Graph. You can [upvote the request here](https://feedbackportal.microsoft.com/feedback/idea/c46a3e47-42d2-ec11-a7b6-000d3a54e061) so it can be prioritized.

cc @mmcla

**Comment by sanalkr** [comment]
Thanks, @FaithOmbongi. It does bring clarity on what is supported right now. It does become a blocker as we are trying to find a way to automate this.

Any expected timeline on when this could be availble through GraphAPI as Microsoft themselves are recommending to move away from ADAL stuff.

**Comment by FaithOmbongi** [comment]
Hi @sanalkr, unfortunately, I can't confirm when the feature will be available in Microsoft Graph. But we will provide a solution before MSOL is retired.

If the process doesn't work on B2C tenants, I recommend that you post the issue in [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) so that our engineering team can be investigated. Please specify that you're running the queries in a B2C tenant. If you can get a request ID for your requests, please share it as well to help with the investigation. 

Unfortunately, this forum is only for documentation-related issues so closing this issue here.
