### ISSUE TITLE
inconsistency of creationDateTime or createdDateTime

### ISSUE THREAD

**Issue by rvzakngh** [microsoftgraph/microsoft-graph-docs#18100]
The JSON example uses `creationDateTime`, but the properties table stated `createdDateTime`. Although the value is not populated currently, it would be good to keep the example and property in the table consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b8b9f84-f816-7a11-90ba-d76b9c4fddec
* Version Independent ID: cc07ad58-bdf6-c6bd-349f-41b6506d8614
* Content: [passwordAuthenticationMethod resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/passwordauthenticationmethod?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/passwordauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/passwordauthenticationmethod.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @zhvolosh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @rvzakngh for catching this error. The correct property is **createdDateTime**. I've raised a PR to fix the docs.
