### ISSUE TITLE
accessPackageRequestState is missing UserExtend value and is not consistent with other states

### ISSUE THREAD

**Issue by timd19** [microsoftgraph/microsoft-graph-docs#18116]
Hello,

The document does not reference as a valid accessPackageRequestState for UserExtend - Document says "A request from the user themselves would have requestType of UserAdd or UserRemove." but UserExtend is also valid.

![image](https://user-images.githubusercontent.com/22712034/185809893-f79de4af-e6aa-42ce-8112-9fe1aa2979c9.png)

Also - the state name for UserExtend is not consistent with the other states like userAdd and userRemove. All the other states start with a lower case, but the response for UserExtend is uppercase U.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58329c0d-50b2-2b69-b968-e36e4d7c6ad9
* Version Independent ID: 0369ad98-97b9-c193-eff8-3bc1aec1c267
* Content: [accessPackageAssignmentRequest resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accesspackageassignmentrequest.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @timd19 for raising this issue. Unfortunately, this forum is only for documentation-related issues but I've opened an internal work item number 2037768 to investigate the validity of "UserExtend" and to track the casing issue. Closing this issue here for now but the documentation will be updated as soon as new information is available.

cc @markwahl-msft
