### ISSUE TITLE
Using filter from the example return error

### ISSUE THREAD

**Issue by mortaelth** [microsoftgraph/microsoft-graph-docs#18122]
Using this api call mentioned in the example:
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=keyCredentials/any(k:k/endDateTime le 2021-01-02T12:00:00Z)

result:
```json
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Complex query on property keyCredentials is not supported.",
        "innerError": {
            "date": "2022-08-22T09:37:39",
            "request-id": "355f841c-ebb8-40de-8ded-eb5af6693221",
            "client-request-id": "355f841c-ebb8-40de-8ded-eb5af6693221"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Version Independent ID: ca630f7c-e88d-3b10-4ed1-3574dd415ad2
* Content: [Use the $filter query parameter to filter a collection of objects - Microsoft Graph](https://docs.microsoft.com/en-us/graph/filter-query-parameter)
* Content Source: [concepts/filter-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/filter-query-parameter.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Hi @Licantrop0, any update on this? Is this issue still open? Thanks

**Comment by Licantrop0** [comment]
@lramosvea we had some engineering challenges, and the team is now targeting CY23Q2 for prod deployment. I'll close this as soon as the property filtering is available.
