### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by jbh999** [microsoftgraph/microsoft-graph-docs#18189]
Many links, under each section's _The preceding limits apply to the following resources:_, result in a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Version Independent ID: ce39639f-5e2c-06d6-5775-ac16a6a4828e
* Content: [Microsoft Graph service-specific throttling limits - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling-limits)
* Content Source: [concepts/throttling-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/throttling-limits.md)
* Content Source: [throttling-excel.md](https://github.com/microsoftgraph/microsoft-graph-docs/edit/main/includes/throttling-excel.md)
* Content Source: [throttling-education-rostering-apis.md](https://github.com/microsoftgraph/microsoft-graph-docs/edit/main/includes/throttling-education-rostering-apis.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Closing this issue because the docs have been fixed. Thank you, @jbh999.
