### ISSUE TITLE
API path formats are incorect in doc

### ISSUE THREAD

**Issue by aosolis** [microsoftgraph/microsoft-graph-docs#18191]
The format is specified as 

GET /me/onlineMeetings({meetingId})/transcripts({transcriptId})
GET /users({userId})/onlineMeetings({meetingId})/transcripts({transcriptId})

but in the examples, the actual paths are

GET /me/onlineMeetings/{meetingId}/transcripts/{transcriptId}
GET /users/{userId}/onlineMeetings/{meetingId}/transcripts/{transcriptId}

that is, the IDs are segments in the path, not enclosed in parentheses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f346bfa-ac5b-1d2f-b675-06c6fd8b9d16
* Version Independent ID: d1732c1a-8bd7-a23a-4e03-c726a4540e26
* Content: [Get callTranscript - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/calltranscript-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/calltranscript-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/calltranscript-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @mankadnandan
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @AkJo - Could you please help us here to update the documentation?

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Please feel free to reopen otherwise. Thanks.
