### ISSUE TITLE
Typo on responseStatus resource type page

### ISSUE THREAD

**Issue by mateowinn** [microsoftgraph/microsoft-graph-docs#18192]
Just letting you know that "attendee" is misspelled once on this page as "attendde". No other errors, as far as I can tell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8837ed-fee9-835f-c724-88b2cea5688b
* Version Independent ID: cf38a184-7667-1039-c0b2-d1c6f2bcc95a
* Content: [responseStatus resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/responsestatus.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@Danielabom Could you help with this one? Thanks
