### ISSUE TITLE
Exact permission wording missing

### ISSUE THREAD

**Issue by fowl2** [microsoftgraph/microsoft-graph-docs#18219]
Here is a (redacted) permission/consent request a we've received from a vendor for security review:

![image](https://user-images.githubusercontent.com/12844147/187112851-2ee5fc8a-9818-4437-ac7e-798dbdfb6c6a.png)

The first item reads:
> **Edit or delete items in all site collections**
> Allow the application to edit or delete documents and list items in all site collections on your behalf. 

The closest I can find in this document is "Sites.ReadWrite.All" delegated permission:

> **Read and write items in all site collections**
> Allows the app to edit or delete documents and list items in all site collections on behalf of the signed-in user. 

But because it doesn't match it's really hard to be certain. Does "on your behalf" imply delegated permissions or is "your" in this context refer to an administrator?

The lack of clarity is unfortunate for making security decisions. 

Could this document please be reviewed to ensure that all the "in product" text is listed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edcc46d-c145-fad7-a54c-52c21f05ab7c
* Version Independent ID: 8b6bcf33-b048-2d3c-33b5-5a3dd5d25a75
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @fowl2 for asking this question.

> But because it doesn't match it's really hard to be certain. Does "on your behalf" imply delegated permissions or is "your" in this context refer to an administrator?

"your" => the end-user who wants to grant the app those permissions. This is a user-facing consent message, as opposed to the admin/dev-facing message.

The "Description" column in the permissions documentation indicates the message that's displayed to an admin when they need to consent a permission grant to an app on behalf of a user. We don't indicate the user-facing message in the doc, which is what is shown on your screenshot. 

The target audience of the permissions reference is the admin who wants to review what permissions to grant in the tenant, and the dev who wants to review the permissions to request an admin to grant in the tenant. Not end-users. AFAIK, you can only see the user-facing message by reading the permissions through the [Microsoft Graph service principal object](https://developer.microsoft.com/en-us/graph/graph-explorer?request=servicePrincipals%3F%24filter%3DdisplayName%2Beq%2B'Microsoft%2BGraph'%26%24select%3DappRoles%2Coauth2PermissionScopes&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) (See userConsentDescription and userConsentDisplayName properties).

I hope this helps to clarify the scope of the permissions reference.
