### ISSUE TITLE
Rename AWS Single Sign-On to AWS IAM Identity Center (successor to AWS Single Sign-On)

### ISSUE THREAD

**Issue by ppanchal-mobiz** [microsoftgraph/microsoft-graph-docs#18226]
According to [AWS documentation](https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html#:~:text=On%20July%2026%2C%202022%2C%20AWS%20Single%20Sign%2DOn%20was%20renamed%20to%20AWS%20IAM%20Identity%20Center%20(successor%20to%20AWS%20Single%20Sign%2DOn).%20For%20existing%20customers%2C%20the%20following%20table%20is%20meant%20to%20describe%20some%20of%20the%20more%20common%20term%20changes%20that%20have%20been%20updated%20throughout%20this%20guide%20as%20a%20result%20of%20the%20rename.) `AWS Single Sign-On` was renamed to `AWS IAM Identity Center (successor to AWS Single Sign-On)` on 26th July 2022. An attempt to create the SAML application would fail since it will not find the template with the legacy name. Kindly change accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9067ae9-89d0-5854-7327-856d930e7712
* Version Independent ID: e0ed6a1b-34bc-55a2-b4ca-61fe3f8ca367
* Content: [Use Microsoft Graph APIs to configure SAML-based single sign-on - Microsoft Graph](https://docs.microsoft.com/en-us/graph/application-saml-sso-configure-api)
* Content Source: [concepts/application-saml-sso-configure-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/application-saml-sso-configure-api.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @kenwith
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ppanchal-mobiz for bringing this change to our attention. I've raised a PR to fix the reference.
