### ISSUE TITLE
schema links point to markdown pages not html

### ISSUE THREAD

**Issue by mmascolino** [microsoftgraph/microsoft-graph-docs#18222]
The schema links on this page:
https://docs.microsoft.com/en-us/graph/data-connect-datasets
all point to markdown pages vs. their rendered HTML counterparts:
i.e. this: https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/SharePointSitesDataset_v0_Preview.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 017a905f-877d-4b43-5894-fe2231f7b9ac
* Version Independent ID: e2938c70-9085-fd95-9d34-b27f94450921
* Content: [Datasets, regions, and sinks supported by Microsoft Graph Data Connect - Microsoft Graph](https://docs.microsoft.com/en-us/graph/data-connect-datasets)
* Content Source: [concepts/data-connect-datasets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/data-connect-datasets.md)
* Product: **data-connect**
* Technology: **microsoft-graph**
* GitHub Login: @fercobo-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fercobo-msft** [comment]
Please work with @David1997sb. I am no longer in charge of this documentation. @David1997sb please update the author metadata headers in the MD pages to your alias.

**Comment by David1997sb** [comment]
@mmascolino can you please explain what the issue is?

**Comment by mmascolino** [comment]
the page linked in the original details of the issue has hyperlinks that
point at markdown pages vs. the rendered HTML output.

**Comment by David1997sb** [comment]
@mmascolino can we have a call to go over this? please share your MS Email address :)

**Comment by mmascolino** [comment]
on this page:
https://docs.microsoft.com/en-us/graph/data-connect-datasets

the schema links point at markdown files instead of the rendered html:
[image: image.png]

one of those md's:
https://github.com/microsoftgraph/dataconnect-solutions/blob/main/datasetschemas/DocumentSharingDataset_v0_Preview.md

GitHub renders the MarkDown experience for this file which includes all the
github and ms docs metadata

**Comment by rgirish2** [comment]
Thanks @mmascolino for the feedback. At this point we are not making changes to these pages. We will try to fix this in upcoming iterations based on more feedback here. thnx!
