### ISSUE TITLE
Shared channels are returned with "standard" membershipType

### ISSUE THREAD

**Issue by Dujma** [microsoftgraph/microsoft-graph-docs#18258]
Hello,

a recent change in the API is now returning shared channels with `membershipType` of "standard", making the https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http#example-3-list-all-shared-channels endpoint unusable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc7bd1a-6210-6010-c9ff-4245c342b20a
* Version Independent ID: e667c977-60ef-a81d-e94b-7eed5061b2c7
* Content: [List channels - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
Hi @Dujma -  We are able to repro this issue. We have already raised a bug for this and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by shantanu1singh** [comment]
I believe this has now been fixed. Can you please check?

**Comment by Prasad-MSFT** [comment]
@shantanu1singh - We checked, but for shared channels we are getting

 "membershipType": "unknownFutureValue"

![image](https://user-images.githubusercontent.com/62237649/193277940-b4eb210c-36eb-4413-82a3-f1b8f955bc99.png)

**Comment by shantanu1singh** [comment]
@Prasad-MSFT that's expected. Please see the related documentation:

https://learn.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0#properties

![image](https://user-images.githubusercontent.com/2570312/193515645-50e40368-36c5-4197-b212-48f38f3be681.png)

**Comment by shantanu1singh** [comment]
Closing as the original bug has been fixed
