### ISSUE TITLE
We cannot update a "group" just by having Directory.ReadWrite.All application permission

### ISSUE THREAD

**Issue by saraamini8** [microsoftgraph/microsoft-graph-docs#18279]
According to our documentation (https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=http), we need to add "Group.ReadWrite.All" **OR** "Directory.ReadWrite.All" permission to be able to update a group. 
But we cannot update a "group" just by having Directory.ReadWrite.All application permission and we have to add "Group.ReadWrite.All" permissions to be able to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9552ff12-2b05-3a95-978a-061605f38404
* Version Independent ID: ed70a9f8-9b47-7d73-7188-c7456a4b558b
* Content: [Update group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-update.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@saraamini8 - We are looking into this we will get back to you soon.

**Comment by FaithOmbongi** [comment]
Hi @saraamini8 - I'm unable to replicate your issue. _Group.ReadWrite.All_ is a very highly privileged permission and would allow you to successfully update many basic objects for many Azure AD APIs.

Could you share what Azure AD role you had and which group objects you were trying to update?

**Comment by saraamini8** [comment]
Hi @FaithOmbongi 
I used application permissions (client credential), and try to update "hideFromOutlookClients" property:
According to [this](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-1.0&tabs=http#:~:text=To%20update%20the%20following%20properties%2C%20you%20must%20specify%20them%20in%20their%20own%20PATCH%20request%2C%20without%20including%20the%20other%20properties%20listed%20in%20the%20table%20above%3A%20allowExternalSenders%2C%20autoSubscribeNewMembers%2C%20hideFromAddressLists%2C%20hideFromOutlookClients%2C%20isSubscribedByMail%2C%20unseenCount.), there is no exception for updating this property.

**Comment by psaffaie** [comment]
@saraamini8 when you were updating the property with application permissions - did you try to update more than just the 
hidefromoutlookclients attribute in its own PATCH request?

**Comment by saraamini8** [comment]
@psaffaie no, I just put "hidefromoutlookclients" in the body request.

**Comment by psaffaie** [comment]
Hi @saraamini8 like Faith, I was unable to replicate this scenario. I was able to change this attribute via a PATCH operation with Directory.ReadWrite permissions. Have you been able to replicate this scenario with other applications that have Directory.ReadWrite permissions? Or was this an isolated scenario?

**Comment by saraamini8** [comment]
Hi @psaffaie, the first test was on cx's environment, then I tried it on my test tenant and could see the same issue.
Here I will add some screenshots of the requests I sent.

First I send the request with a token which only has "Directory.ReadWrite.All " permission -> getting error 403
Then I added the "Group.ReadWrite.All" and update the property, and it worked.
The first request:
![image](https://user-images.githubusercontent.com/101718968/204805425-85257a1b-78c7-4b4d-8cf6-8a52cda9748d.png)
![image](https://user-images.githubusercontent.com/101718968/204805696-3003ab1e-73d0-4d20-bd72-a39335e3c7a9.png)

New request after adding "Group.ReadWrite.All" permission:
![image](https://user-images.githubusercontent.com/101718968/204806129-81d5793f-f9ae-4bd9-a4f2-e6239083f274.png)
![image](https://user-images.githubusercontent.com/101718968/204806215-20d54f7d-8916-4d2a-a323-1eb797e46c07.png)

![image](https://user-images.githubusercontent.com/101718968/204806511-0f1d20e4-6bbd-455b-9681-0abf29dd4428.png)
