### ISSUE TITLE
Don’t include these characters in the names of sites and channels in Microsoft Teams ~  #  %  &  *  {  }  +  /  \  :  <  >  ?  |  ‘  ” 

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs#18299]
Please mention in the documentation to do not include these characters in the names of sites and channels in Microsoft Teams
~  #  %  &  *  {  }  +  /  \  :  <  >  ?  |  ‘  ” 

Channel names also shouldn’t start with an underscore (_) or period (.), or end it with a period (.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@AkJo -Could you please help us to update the document?

**Comment by ChetanSharma-msft** [comment]
PR has raised for it: https://github.com/microsoftgraph/microsoft-graph-docs/pull/19247
