### ISSUE TITLE
createdDateTime and lastModifiedDateTime are wrong from the search API

### ISSUE THREAD

**Issue by Mike-Bell** [microsoftgraph/microsoft-graph-docs#183]
I created a file at 3/25/2016 at about 9:30 AM (Eastern US). According to Google, this is 1:30 PM (13:30) UTC. I then did a Search for this file (https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_search). The return I get from graph API is `{"@odata.type":"#microsoft.graph.driveItem","createdBy":{...}},"createdDateTime":"2016-03-25T20:33:50Z","file":{},"id":"...","lastModifiedDateTime":"2016-03-25T20:33:50Z","name":"..."}`

`2016-03-25T20:33:50Z`

Clearly this is off by 7 hours.

This seems to be limited to the search API. If I use `/drive/items/id` I get the correct time: `016-03-25T13:33:50Z`

**Comment by isvargasmsft** [comment]
Hello, 

My sincere apologies for the delays.

I tried to reproduce the error but it is showing the right date and time in UTC (GMT) now. The command I am using is:
`GET https://graph.microsoft.com/v1.0/me/drive/root/search(q='filename')`

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at Microsoft Q&A: [Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).

Best regards, 

Isaac Vargas
Microsoft Graph DevX
