### ISSUE TITLE
Cannot run code snippet 

### ISSUE THREAD

**Issue by benfarmer3** [microsoftgraph/microsoft-graph-docs#18302]
running the code snippet returns the error "Item has already been added. Key in dictionary: " 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1caf7b-7d94-ed49-f84a-1c8adad5bc93
* Version Independent ID: 7b1caf7b-7d94-ed49-f84a-1c8adad5bc93
* Content: [Configure required Azure AD Graph permissions for an app registration - Microsoft Graph](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-configure-permissions?tabs=powershell-1#tabpanel_1_powershell-1)
* Content Source: [concepts/migrate-azure-ad-graph-configure-permissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/migrate-azure-ad-graph-configure-permissions.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @benfarmer3, This sounds like a "duplicate" error message. I think you may already have the exact permission granted to your app. Can you confirm the permission IDs in your request object vs what's already in the app manifest?

**Comment by benfarmer3** [comment]
Hi, @FaithOmbongi  Thanks for the response, this is before the connection is made to azure (I have removed any references to azure). I don't think you can combine two hash maps like the code suggests as they would both contain the key "ResourceAppId".  This code throws the same error : 


```
## Azure AD Graph's globally unique appId is 00000002-0000-0000-c000-000000000000 identified by the ResourceAppId
$AzureADGraphAppId = "00000002-0000-0000-c000-000000000000"
$MicrosoftGraphAppId = "00000003-0000-0000-c000-000000000000"

## Replace a05f9f7f-4377-4915-bbd0-5fe8f9517046 with the object ID of the app you wish to add new permissions to
$clientObjectId = "a05f9f7f-4377-4915-bbd0-5fe8f9517046" 

## Define the new Azure Graph permissions to be added to the target client
$newAzureADGraphPermissions = @{  
    ResourceAppId  = $AzureADGraphAppId; 
    ResourceAccess = @( 

        ## Replace the following with values of ID and type for all Azure AD Graph permissions you want to configure for the app
        @{ 
            # User.Read scope (delegated permission) to sign-in and read user profile 
            id   = "311a71cc-e848-46a1-bdf8-97ff7156d8e6";  
            type = "Scope"; 
        },

        @{ 
            # Application.Read.All app role (application permission) to view application data
            id   = "3afa6a7d-9b1a-42eb-948e-1650a849e176"; 
            type = "Role"; 
        }
    )
}

## Define the new Microsoft Graph permissions to be added to the target client
$newMicrosoftGraphPermissions = @{  
    ResourceAppID  = $MicrosoftGraphAppId;
    ResourceAccess = @(

        ## Replace the following with values of ID and type for all Microsoft Graph permissions you want to configure for the app
        @{
            # User.Read scope (delegated permission) to sign-in and read user profile 
            id   = "e1fe6dd8-ba31-4d61-89e7-88639da4683d";
            type = "Scope"
        },
        @{
            # Application.Read.All app role (application permission) to view application data
            id   = "9a5d68dd-52b0-4cc2-bd40-abcf44ac3a30";
            type = "Role";
        }
    )
}

$existingResourceAccess = $existingResourceAccess + $newAzureADGraphPermissions + $newMicrosoftGraphPermissions

```

**Comment by FaithOmbongi** [comment]
@benfarmer3 - Hmm, last I tested this script it worked without throwing errors. But I'm happy to retest.

If you change the property name to something else, does it work for you?
