### ISSUE TITLE
Example of "dependsOn property"

### ISSUE THREAD

**Issue by saraamini8** [microsoftgraph/microsoft-graph-docs#18306]
In "**Sequencing requests with the dependsOn property**" section, it is mentioned that "For example, in the following request, the client is specifying that requests should be run in the order _request 1 then request 3, then request 2, then request 4_."
But I believe it should be in this order: 1->2->4->3
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e33b4529-dfaa-b051-a73e-fa7312e911f5
* Version Independent ID: 55111137-63ad-3408-9295-ef44128aed14
* Content: [Combine multiple requests in one HTTP call using JSON batching - Microsoft Graph](https://docs.microsoft.com/en-us/graph/json-batching)
* Content Source: [concepts/json-batching.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/json-batching.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Good catch, @saraamini8! I've raised a PR to fix this reference.
