### ISSUE TITLE
https://graph.microsoft.com/beta/teamwork/teamTemplates returns API is not supported exception

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs#18324]
Hello,
I went to the official Microsoft documentation listed below and tried the endpoints presented on the page. Right now the endpoint returns following exception:

```
{
    "error": {
        "code": "NotFound",
        "message": "Requested API is not supported. Please check the path.",
        "innerError": {
            "date": "2022-09-07T06:22:38",
            "request-id": "86726379-83d3-432a-8a03-5b4843b516b8",
            "client-request-id": "b79f6ac9-ec6d-52b6-650b-90b5582f3b50"
        }
    }
}
```

Has something changed?

Thank you for your feedback,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6109b93f-dd36-f7fb-8cfd-d17999d57df6
* Version Independent ID: 2704fa29-d78d-9bca-bffd-61ca329b5c4e
* Content: [List teamTemplates - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/teamwork-list-teamtemplates?view=graph-rest-beta&tabs=http&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/teamwork-list-teamtemplates.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamwork-list-teamtemplates.md)
* Product: **teamwork**
* Technology: **microsoft-graph**
* GitHub Login: @charlieforce
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@plamber - We will test this and update you soon.

**Comment by Nivedipa-MSFT** [comment]
@plamber - We have tested this and we are also getting same error. We are checking this with engineering team. We will update you soon.

**Comment by elarrieux** [comment]
Any updates? It works by using the token issued in Graph Explorer.

**Comment by ChetanSharma-msft** [comment]
Hello @elarrieux - Sorry for delay in response.
We will check on the bug status and let you know the updates.

**Comment by Nivedipa-MSFT** [comment]
@plamber - We have tested https://graph.microsoft.com/beta/teamwork/teamTemplates graph API in graph explorer and Postman. We are getting the results.

![image](https://user-images.githubusercontent.com/92150070/214515371-747372be-ded9-4e3e-9c14-5417df6fe802.png)

![image](https://user-images.githubusercontent.com/92150070/214515722-78808b4e-919a-4159-84db-5eb97c685b73.png)

Could you please test and confirm on this?

**Comment by plamber** [comment]
Thank you. It works on my end.

Cheers

**Comment by Nivedipa-MSFT** [comment]
@plamber - Could you please share your valuable [feedback ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FDevSupport[Feedback](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FDevSupportFeedback&data=05%7C01%7Cv-nivedipasu%40microsoft.com%7C24c7ea98af3d4287f5a608dafe9758dc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638102223329218137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kDiWYJy6DWp40z1jnQnrIkGbm%2F3nbj4LgQ1C6eMl6bg%3D&reserved=0)&data=05%7C01%7Cv-nivedipasu%40microsoft.com%7C24c7ea98af3d4287f5a608dafe9758dc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638102223329218137%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kDiWYJy6DWp40z1jnQnrIkGbm%2F3nbj4LgQ1C6eMl6bg%3D&reserved=0)here.

**Comment by plamber** [comment]
@Nivedipa-MSFT: yes I would but the link does not work

**Comment by ChetanSharma-msft** [comment]
Hello @plamber - Could you please share your valuable feedback here: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUOThVR081SllSR05aSDQxQ0tUMDVPTVIxTi4u
