### ISSUE TITLE
Documented Permissions do not exist, leading to a non functional command

### ISSUE THREAD

**Issue by Ng-marelec** [microsoftgraph/microsoft-graph-docs#18333]
The new [SoftDelete functionality](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-softdelete.md) requires the `ChatMessage.ReadWrite` permission according to the documentation.

However, this is not available for selection in the Azure Portal.
Hence, the command is useless? (Trying produces the error `"Could not load file or assembly 'Microsoft.Graph.Authentication, Version=1.11.1.0, Culture=neutral, PublicKeyToken=XXX' or one of its dependencies. The system cannot find the file specified."`)

**➟ Please verify whether the documented permission is correct.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2781b95-7df2-8985-3c89-31b73b9ee502
* Version Independent ID: 95cd55d8-8003-5fa6-5660-582089488d66
* Content: [chatMessage: undoSoftDelete - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-undosoftdelete?view=graph-rest-beta&WT.mc_id=M365-MVP-5001530&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-undosoftdelete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/chatmessage-undosoftdelete.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Ng-marelec** [comment]
@RamjotSingh

**Comment by Meghana-MSFT** [comment]
We are looking into this issue; we will get back to you.

**Comment by sumitgupta3** [comment]
Fix PR for the same is created. There was bug in documentation.

**Comment by Ng-marelec** [comment]
> Fix PR for the same is created. There was bug in documentation.

Ok, thanks for the update.
This still implies a non-functional cmdlet, however?

**Comment by sumitgupta3** [comment]
Actually, the permission required for this is Chat.ReadWrite. But updated wrong in Public documents. We will soon publish new version of doc.

**Comment by Ng-marelec** [comment]
Perhaps my brain is damaged, but when I try to run the `Invoke-MgSoftUserChatMessageDelete` with the mentioned permissions (which were already enabled in my screen shot), I still receive the same `Could not load` error.

**Comment by Meghana-MSFT** [comment]
Please try using the API after the document is updated with correct permissions.

**Comment by Meghana-MSFT** [comment]
We are closing this issue as the document is updated with correct permissions. Please feel free to contact us if you have any questions. Thank you.
