### ISSUE TITLE
Invalid Reference

### ISSUE THREAD

**Issue by Nett3000** [microsoftgraph/microsoft-graph-docs#18354]
[Enter feedback here]
Hello @Jackson-Woods,

This article contains the following wording:

_There's no admin consent endpoint. Instead, your app can request administrator consent during runtime by adding the prompt=admin_consent parameter to an authorization request. For more information, see Triggering the Azure AD consent framework at runtime in [Integrating applications with Azure Active Directory](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications)._

The referenced article, however, has no mention of "Triggering the Azure AD consent framework at runtime".

Please correct accordingly.

Many thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4323239e-0486-0f8f-6f2b-5e41e6178594
* Version Independent ID: 627883a9-8cd7-93cd-358d-b841d390714b
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-user.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Nett3000 for catching this broken link. The article no longer exists and has been [archived](https://github.com/uglide/azure-content/blob/master/articles/active-directory/active-directory-integrating-applications.md). I've raised a PR to remove the reference.
