### ISSUE TITLE
This document is great but does not work with AzureUSGovernment cloud

### ISSUE THREAD

**Issue by rguthriemsft** [microsoftgraph/microsoft-graph-docs#18351]
I followed the steps but get error in postman console when I try to get a delegated access token in step 5.6 when my tenant is in AzureUSGovernment cloud.

AADSTS900432: Confidential Client is not supported in Cross Cloud request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rguthriemsft** [comment]
All I needed to do to make it work was adjust Auth URL, Access Token URL and Scope and was able to get a token.

**Comment by jasonjoh** [comment]
Thanks @rguthriemsft for the report. Could you provide more detail on the change to Scope? Was it just swapping out the .com for .us, so it was `https://graph.microsoft.us/.default`?
