### ISSUE TITLE
Endpoint to work with permissionScope

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#18384]
There is the resource `permissionScope` but there is no reference to any endpoint that returns `permissionScope`.

Documentation mentions that delegated permissions can be requested through the `requiredResourceAccess` collection on the [application](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0) object.

[requiredResourceAccess](https://docs.microsoft.com/en-us/graph/api/resources/requiredresourceaccess?view=graph-rest-1.0) resource has collection [resourceAccess](https://docs.microsoft.com/en-us/graph/api/resources/resourceaccess?view=graph-rest-1.0) with property `id` which is Guid of delegated permission.

How to retrieve `permissionScope` object if I want to get a name of delegated permission from its `id`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b76052a-a68f-47e1-24be-1d5828712fb4
* Version Independent ID: edefe199-37ab-ca8f-8565-f3bc92db56b7
* Content: [permissionScope resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/permissionscope?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/permissionscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/permissionscope.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
@MartinM85 Good question and feedback. 

There are two places where the **permissionScope** complex type is used:

1. In the [**oauth2PermissionScopes**](https://docs.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0#:~:text=oauth2PermissionScopes,-permissionScope%20collection) collection within the [**api**](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties:~:text=api,-apiApplication) property (of type [**apiApplication**](https://docs.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0)) of the [**application**](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0) entity type.
2. In the [**oauth2PermissionScopes**](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0#properties:~:text=oauth2PermissionScopes,-permissionScope%20collection) collection on the [**servicePrincipal**](https://docs.microsoft.com/graph/api/resources/serviceprincipal?view=graph-rest-1.0) entity type.

A **permissionScope** entity represents the definition of a delegated permission. It is typically defined on the **application** entity representing the API's app registration, and gets automatically included in the **servicePrincipal** entity, which represents an instance of the app/service in a tenant.

If you have a resource app's **appId** and a delegated permission's **id**, you would typically do the following:

1. Retrieve the service principal for the resource app. Here, I'm using the **appId** for Microsoft Graph:

   ```none
   GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appId eq '00000003-0000-0000-c000-000000000000'
   ```

2. Iterate over the values in the **oauth2PermissionScopes** collection of the resulting object, looking the **permissionScope** instance with the matching **id** property. For example, if we're looking for **id** "b340eb25-3456-403f-be2f-af7a0d370277", we find it's for *User.ReadBasic.All*:

   ```jsonc
   {
       "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#servicePrincipals",
       "value": [
           {
               "appId": "00000003-0000-0000-c000-000000000000",
               "displayName": "Microsoft Graph",
               /* ... */
               "oauth2PermissionScopes": [
                   {
                       "adminConsentDescription": "Allows the app to read a basic set of profile properties of other users in your organization on behalf of the signed-in user. This includes display name, first and last name, email address and photo.",
                       "adminConsentDisplayName": "Read all users' basic profiles",
                       "id": "b340eb25-3456-403f-be2f-af7a0d370277",
                       "isEnabled": true,
                       "type": "User",
                       "userConsentDescription": "Allows the app to read a basic set of profile properties of other users in your organization on your behalf. Includes display name, first and last name, email address and photo.",
                       "userConsentDisplayName": "Read all users' basic profiles",
                       "value": "User.ReadBasic.All"
                   },
               /* ... */
               ],
               /* ... */
           }
       ]
   }
   ```

As a more complete example, here we use Microsoft Graph PowerShell, to take a client app's **requiredResourceAccess** property, and print out human-readable names for the required APIs and permissions:

```powershell
$clientAppId = "{client-app-id}"

# Retrieve the client app's app registration
$clientApp = Get-MgApplication -Filter "appId eq '$($clientAppId)'"

foreach ($requiredResourceAccess in $clientApp.RequiredResourceAccess) {

    # Retrieve the service principal for each resource app (i.e. the API)
    $resourceService = Get-MgServicePrincipal -Filter "appId eq '$($requiredResourceAccess.ResourceAppId)'"
    Write-Host "$($resourceService.DisplayName) "

    # Look up the details for each required permission
    foreach ($resourceAccess in $requiredResourceAccess.ResourceAccess) {
        switch ($resourceAccess.Type) {
            "Scope" {
                # The permission ID is for a delegated permission
                $permissionScope = $resourceService.Oauth2PermissionScopes | ? { $_.Id -eq $resourceAccess.Id }
                Write-Host "    Scope: $($permissionScope.Value)"
            }
            "Role" {
                # The permission ID is for an app role (application permission)
                $appRole = $resourceService.AppRoles | ? { $_.Id -eq $resourceAccess.Id }
                Write-Host "    Role:  $($appRole.Value)"
            }
        }
    }
}
```

Which might provide an output as follows:

```none
Microsoft Graph
    Scope: User.Read
    Scope: User.ReadBasic.All
    Role:  User.Read.All
Windows Azure Service Management API
    Scope: user_impersonation
```
