### ISSUE TITLE
GCC High

### ISSUE THREAD

**Issue by TheDapperDevin** [microsoftgraph/microsoft-graph-docs#18484]
Looking to use the signinactivity with Graph API in GCC High but it doesn't seem to be present - is there any timeline on when this will be added? 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0f258b-b61e-72a2-0caf-d9b7fff5857d
* Version Independent ID: 90c2edf2-51ee-6bab-84a6-3710a3f0ccd2
* Content: [signInActivity resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/signinactivity.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @TheDapperDevin for asking this question. Unfortunately, I'm unable to share any ETAs for the availability of this property in other clouds where it may currently be unavailable. Please raise this question through the portal to get further assistance.

**Comment by FaithOmbongi** [comment]
Thank you @TheDapperDevin for asking this question. Unfortunately, I'm unable to share any ETAs for the availability of this property in other clouds where it may currently be unavailable. Please raise this question through the portal to get further assistance.
