### ISSUE TITLE
404 unknown user

### ISSUE THREAD

**Issue by raclettierer** [microsoftgraph/microsoft-graph-docs#18589]
Get 404 if one member is shown as "Unknown User" in teams 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38b882ba-662c-665b-600d-2a92d1948c92
* Version Independent ID: a7c4a7c9-08f1-f321-e805-6a7d90a8cf41
* Content: [List teamworkTagMembers - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teamworktagmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @anniecolonna
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
We are checking the issue.

**Comment by Prasad-MSFT** [comment]
@raclettierer - We tried to repro the issue by following below doc: 
https://learn.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&tabs=http

Steps followed:
1. We created a tag allocating 2 members of that specific team
    https://learn.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&tabs=http
2. Then we tried to get the teamworktagmember details as below and it showed 2 members as expected.
![image](https://user-images.githubusercontent.com/62237649/192210782-211b23ca-25d0-42f5-be2e-8db2f0422de2.png)

3. Then we removed the above marked member from the organization and again ran the query
4. Now also it got successfully run giving details of only existing single user. It didn't show the removed/unknown user at all in the output.
![image](https://user-images.githubusercontent.com/62237649/192210562-269505d4-b84a-4976-9556-1617b2ea5d64.png)

**Comment by raclettierer** [comment]
the following screen shows the user under a teams tag. The are shown as unknown user. I don't know whats happen with these users. Same behavier on six other MSTeams. I think the api can't resolve these user and throw an exception. 

![image](https://user-images.githubusercontent.com/32407069/193283109-98121709-f26a-49a9-9957-4f75887038ab.png)

**Comment by raclettierer** [comment]
I find out that I can add user to a tag which is blocked. The result are these "unknown user".

maybe the api should validate if the user is active or blocked in the AAD.
