### ISSUE TITLE
Issue with publishing teams apps

### ISSUE THREAD

**Issue by magnusjak** [microsoftgraph/microsoft-graph-docs#18610]
I am using an AppRegistration+ServicePrincipal to fetch a graph token for various tasks. This has been working fine until I tried to publish a teamsApp. At first I got the error that I was missing the AppCatalog.ReadWrite.All permission on my app, but after that was added I started receiving this error:
`User not authorized to perform this operation. UserId: '00e4cfb7-b765-4d85-b337-f2b65c6395b0', TenantId: 'my tenantId'`

The UserId that is referred to is the integrated ServicePrincipal 'Microsoft Teams Graph Service'. So I thought that that SP needed some more permissions, so I added the AppCatalog.ReadWrite.All permission to that as well. But it still won't work.

In both SP's I tried adding both the delegated and application type.

Anyone have any idea on how to solve this issue?
I can't find anything in the documentation that tells me what I have done wrong, and where the 'Microsoft Teams Graph Service' comes into play. The error-message doesn't really give a clear picture of what the problem is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc580041-9ed5-dc21-2eb1-813152044527
* Version Independent ID: b229cada-3a68-38b5-4236-7cd0d970679f
* Content: [Publish teamsapp - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/teamsapp-publish.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@magnusjak - Thanks for reporting your issue.
We will investigation this issue and get back to you.

**Comment by sayali-MSFT** [comment]
@magnusjak - Is the user in the same tenant? Could you please try with the another user which is already in the same tenant?

**Comment by magnusjak** [comment]
@sayali-MSFT - The Application/ServicePrincipal is in the same tenant as I am trying to run the code against, yes. There are no normal users involved here, as I am trying to run these things unattended/non-interactive.

**Comment by sayali-MSFT** [comment]
@magnusjak -We are not able to repro the issue, Could you please share the repro steps so that we can investigate from our end and also share the error log.

**Comment by magnusjak** [comment]
Hi @sayali-MSFT,

I have created an app-registration/ServicePrincipal with the following permissions:
![image](https://user-images.githubusercontent.com/103104630/192542703-a4f2d03e-72ec-40da-9c3c-e16953a95c9b.png)

I am fetching a Graph token using the following code:
```
$params = @{
    grant_type    = "client_credentials";
    client_secret = $AOBOAppClientSecret
    client_id     = $AOBOAppClientId
    scope         = "https://graph.microsoft.com/.default";
}

$TenantId = "my tenantID"
$customerAccessTokenUri = ('https://login.microsoftonline.com/{0}/oauth2/v2.0/token' -f $TenantId)
$MsgToken = Invoke-RestMethod -Uri $customerAccessTokenUri -Method POST -Body $params -ContentType "application/x-www-form-urlencoded"
```

I am then trying to upload a new application using this code:
`Invoke-RestMethod -Method POST -Uri "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps" -Headers @{"Authorization" = "Bearer $($MsgToken.access_token)"} -ContentType "application/zip" -Body "C:\temp\testApp.zip"`

This is when I am getting the error:
_Error: The remote server returned an error: (403) Forbidden._

And when I dig further down into the error I can see this:
_{"error":{"code":"Forbidden","message":"User not authorized to perform this operation. UserId: '00e4cfb7-b765-4d85-b337-f2b65c6395b0', TenantId: 'my tenantId'","innerError"
:{"message":"User not authorized to perform this operation. UserId: '00e4cfb7-b765-4d85-b337-f2b65c6395b0', TenantId: 'my tenantId'","code":"AccessDenied","innerError":{},"
date":"2022-09-27T13:52:02","request-id":"a677a69c-2e89-4689-9e6a-01c9c344a71c","client-request-id":"a677a69c-2e89-4689-9e6a-01c9c344a71c"}}}_


However, using the Get method I can list out every TeamsApp in my tenant, so the token is working as it should. If I have done anything wrong, please let me know. I have tried to follow the Graph documentation here https://learn.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&tabs=http and added the required permissions.

**Comment by sayali-MSFT** [comment]
@magnusjak - Azure App permission require also AppCatalog.Submit, Directory.ReadWrite.All with type Delegated.
Could you please add it once and check?

**Comment by magnusjak** [comment]
@sayali-MSFT - This is wrong. It is clearly stated that any of these permissions will suffice.
![image](https://user-images.githubusercontent.com/103104630/192763492-789f6861-8728-4a5c-94da-651ad8c8aab9.png)

Even so, I tried adding both of them and do another test. It still gave me the same error-message. And yes, I made sure that I cleared my authentication and received the token with the updated permissions

**Comment by ChetanSharma-msft** [comment]
Hello @magnusjak - Can you please verify that the user on behalf you are trying to upload the app has required admin permission to upload the app in Admin Center ?
Can you please also try it using the user who have Admin permissions ?

**Comment by magnusjak** [comment]
@ChetanSharma-msft I am not sure what you are asking for here. As I have shown in the screenshots I have provided, the application I am using has the required permissions.

If I log on interactively with my GA account and fetch a Graph-token, that works fine. But I am trying to get this to work through an application/ServicePrincipal so that we can use it in unattended/non-interactive automations.

**Comment by ChetanSharma-msft** [comment]
Hello @magnusjak - Looks like the way you have generated the Graph token may not have required permissions level as your GA account.

Can you please re-verify the permissions level.
Meanwhile we will also check it from our end once again and get back to you.

**Comment by magnusjak** [comment]
Hi @ChetanSharma-msft 
I can verify that these are the permissions our application has:
![image](https://user-images.githubusercontent.com/103104630/193223478-85a03a04-50e9-473d-9c5b-257dbc8d1cb6.png)

I have tried AppCatalog.Submit and Directory.ReadWrite.All (Delegated) as well. But these don't work either.

**Comment by ChetanSharma-msft** [comment]
@magnusjak - We will investigate on it further and get back to you.

**Comment by sayali-MSFT** [comment]
@magnusjak - We are able to repro that issue , We have raised bug for the same and concerned team is looking into it. We will inform you once we get any update.

**Comment by magnusjak** [comment]
@sayali-MSFT - Thanks for the update. I will await your reply :)

**Comment by sayali-MSFT** [comment]
@magnusjak - Got the reply from engineering team, to be able to publish an app, the token used must be that of the tenant admin or the Teams Service Admin. Publish app (Review flows) only work in app context. This will not work if app context token is being used. will go ahead and remove the App context support from the TGS Api so that proper response is sent back.

**Comment by sayali-MSFT** [comment]
@magnusjak - Got the reply from engineering team, to be able to publish an app, the token used must be that of the tenant admin or the Teams Service Admin. Publish app (Review flows) only work in app context. This will not work if app context token is being used. will go ahead and remove the App context support from the TGS Api so that proper response is sent back.

**Comment by sayali-MSFT** [comment]
@magnusjak - Did you get chance to check above suggestion?

**Comment by magnusjak** [comment]
@sayali-MSFT - I didn't understand your reply to be a solution. Was it? If so, I still don't understand what to do.
I am using a token as I am not a native admin-user in the tenant I am trying to update. I am trying to get this working in an app-context so that I am able to automate these things for multiple tenants.

**Comment by sayali-MSFT** [comment]
@magnusjak - Thank you for the detail information, we are providing the details to engineering team and get back to you, once we get any update.

**Comment by sayali-MSFT** [comment]
@magnusjak - Currently, Publishing apps is not supported in app context. A workaround, you can create a separate service account and use that for the automation.
