### ISSUE TITLE
Add member to channel broken?

### ISSUE THREAD

**Issue by PatrickMcLeanTJAC** [microsoftgraph/microsoft-graph-docs#18669]
This seems to be broken now? I'm constantly getting "User is not found in the team" even though I confirm through a Graph Call that they are, and confirm through the Teams WebUI as well. Not sure what is going on here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79f9efdd-1dbf-e2af-6cf1-810d46ef92dc
* Version Independent ID: 4ae0f300-aa78-54c6-f9c0-cc286e756cf9
* Content: [Add member to channel - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/channel-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
We are checking the issue.

**Comment by Prasad-MSFT** [comment]
@PatrickMcLeanTJAC - Are you trying to add member to 'Standard' or 'Private' or 'Shared' channel?
Could you please share the API Query details which you are using e.g., Request header and Request Body?

**Comment by PatrickMcLeanTJAC** [comment]
Private channels.

https://graph.microsoft.com/beta/teams/<teamID>/channels/<channelid>/members

Headers:
Content-type application/json

Body:
{
  "roles": ["member"],
  ***@***.***": "https://graph.microsoft.com/beta/users(‘<userID>')",
  ***@***.***": "#microsoft.graph.aadUserConversationMember"
}


Patrick McLean
Senior IT Specialist

***@***.***
(519) 594-0144 x501
(888) 594-4272 x501

***@***.***

**Comment by Prasad-MSFT** [comment]
@PatrickMcLeanTJAC -
We tried using below API query to add user as member in a private channel using v1.0 and it got added successfully.
Can you please try once with v1.0 instead of beta?
![image](https://user-images.githubusercontent.com/62237649/198953012-36008e04-5df7-4a02-a044-b6e401ee7759.png)

**Comment by PatrickMcLeanTJAC** [comment]
I received Bad Request – 400

***@***.***

Also, when doing it through power automate:
Input:
{
    "uri": ***@***.***/members/,
    "method": "POST",
    "headers": {
        "Content-type": "application/json"
    },
    "authentication": {
        "tenant": "*sanitized*",
        "audience": https://graph.microsoft.com,
        "clientId": "*sanitized*",
        "secret": "*sanitized*",
        "type": "ActiveDirectoryOAuth"
    },
    "body": {
        "roles": [
            "member"
        ],
        ***@***.******@***.***>: ***@***.***>
        ***@***.******@***.***>": "#microsoft.graph.aadUserConversationMember"
    }
}

Output:
{
    "statusCode": 404,
    "headers": {
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "Strict-Transport-Security": "max-age=31536000",
        "request-id": "*sanitized*",
        "client-request-id": ""*sanitized*",",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\""*sanitized*",\"}}",
        "Date": "Wed, 26 Oct 2022 14:41:40 GMT",
        "Content-Type": "application/json",
        "Content-Length": "308"
    },
    "body": {
        "error": {
            "code": "NotFound",
            "message": "User is not found in the team.",
            "innerError": {
                "message": "User is not found in the team.",
                "code": "ItemNotFound",
                "innerError": {},
                "date": "2022-10-26T14:41:41",
                "request-id": "*sanitized*",",
                "client-request-id": "*sanitized*","
            }
        }
    }
}


Patrick McLean
Senior IT Specialist

***@***.***
(519) 594-0144 x501
(888) 594-4272 x501

***@***.***

**Comment by PatrickMcLeanTJAC** [comment]
Sorry disregard the first part, I was putting in the wrong channel ID. It worked for me through graph, but the issue still remains with my power automate flow, I have it fail to add them because it thinks they aren’t in the team, but I have a check in my flow that checks to make sure they are in the team first before adding them to private channel. So why is it failing still?

Patrick McLean
Senior IT Specialist

***@***.***
(519) 594-0144 x501
(888) 594-4272 x501

***@***.***

From: Patrick McLean
Sent: Monday, October 31, 2022 12:14 PM
To: microsoftgraph/microsoft-graph-docs ***@***.***>; microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoftgraph/microsoft-graph-docs] Add member to channel broken? (Issue #18669)

I received Bad Request – 400

***@***.***

Also, when doing it through power automate:
Input:
{
    "uri": ***@***.******@***.***/members/>,
    "method": "POST",
    "headers": {
        "Content-type": "application/json"
    },
    "authentication": {
        "tenant": "*sanitized*",
        "audience": https://graph.microsoft.com,
        "clientId": "*sanitized*",
        "secret": "*sanitized*",
        "type": "ActiveDirectoryOAuth"
    },
    "body": {
        "roles": [
            "member"
        ],
        ***@***.******@***.***>: ***@***.***>
        ***@***.******@***.***>": "#microsoft.graph.aadUserConversationMember"
    }
}

Output:
{
    "statusCode": 404,
    "headers": {
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "Strict-Transport-Security": "max-age=31536000",
        "request-id": "*sanitized*",
        "client-request-id": ""*sanitized*",",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\""*sanitized*",\"}}",
        "Date": "Wed, 26 Oct 2022 14:41:40 GMT",
        "Content-Type": "application/json",
        "Content-Length": "308"
    },
    "body": {
        "error": {
            "code": "NotFound",
            "message": "User is not found in the team.",
            "innerError": {
                "message": "User is not found in the team.",
                "code": "ItemNotFound",
                "innerError": {},
                "date": "2022-10-26T14:41:41",
                "request-id": "*sanitized*",",
                "client-request-id": "*sanitized*","
            }
        }
    }
}


Patrick McLean
Senior IT Specialist

***@***.******@***.***>
(519) 594-0144 x501
(888) 594-4272 x501

***@***.***

**Comment by PatrickMcLeanTJAC** [comment]
BTW it is completely random when it fails too. I literally just had 2 new users run through the flow, one was successfully added to 4 private channels, and one failed to add to any.

Patrick McLean
Senior IT Specialist

***@***.***
(519) 594-0144 x501
(888) 594-4272 x501

***@***.***

From: Patrick McLean
Sent: Monday, October 31, 2022 12:22 PM
To: microsoftgraph/microsoft-graph-docs ***@***.***>; microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoftgraph/microsoft-graph-docs] Add member to channel broken? (Issue #18669)

Sorry disregard the first part, I was putting in the wrong channel ID. It worked for me through graph, but the issue still remains with my power automate flow, I have it fail to add them because it thinks they aren’t in the team, but I have a check in my flow that checks to make sure they are in the team first before adding them to private channel. So why is it failing still?

Patrick McLean
Senior IT Specialist

***@***.******@***.***>
(519) 594-0144 x501
(888) 594-4272 x501

***@***.***

From: Patrick McLean
Sent: Monday, October 31, 2022 12:14 PM
To: microsoftgraph/microsoft-graph-docs ***@***.******@***.***>>; microsoftgraph/microsoft-graph-docs ***@***.******@***.***>>
Cc: Mention ***@***.******@***.***>>
Subject: RE: [microsoftgraph/microsoft-graph-docs] Add member to channel broken? (Issue #18669)

I received Bad Request – 400

***@***.***

Also, when doing it through power automate:
Input:
{
    "uri": ***@***.******@***.***/members/>,
    "method": "POST",
    "headers": {
        "Content-type": "application/json"
    },
    "authentication": {
        "tenant": "*sanitized*",
        "audience": https://graph.microsoft.com,
        "clientId": "*sanitized*",
        "secret": "*sanitized*",
        "type": "ActiveDirectoryOAuth"
    },
    "body": {
        "roles": [
            "member"
        ],
        ***@***.******@***.***>: ***@***.***>
        ***@***.******@***.***>": "#microsoft.graph.aadUserConversationMember"
    }
}

Output:
{
    "statusCode": 404,
    "headers": {
        "Transfer-Encoding": "chunked",
        "Vary": "Accept-Encoding",
        "Strict-Transport-Security": "max-age=31536000",
        "request-id": "*sanitized*",
        "client-request-id": ""*sanitized*",",
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\""*sanitized*",\"}}",
        "Date": "Wed, 26 Oct 2022 14:41:40 GMT",
        "Content-Type": "application/json",
        "Content-Length": "308"
    },
    "body": {
        "error": {
            "code": "NotFound",
            "message": "User is not found in the team.",
            "innerError": {
                "message": "User is not found in the team.",
                "code": "ItemNotFound",
                "innerError": {},
                "date": "2022-10-26T14:41:41",
                "request-id": "*sanitized*",",
                "client-request-id": "*sanitized*","
            }
        }
    }
}


Patrick McLean
Senior IT Specialist

***@***.******@***.***>
(519) 594-0144 x501
(888) 594-4272 x501

***@***.***

**Comment by Prasad-MSFT** [comment]
@PatrickMcLeanTJAC - We just tested the scenario by running API query via Power Automate flow to add user in private channel and it got added successfully. 
![image](https://user-images.githubusercontent.com/62237649/199460408-ce3ba9f5-34dd-4034-9a09-ec1e73f41a0d.png)

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
