### ISSUE TITLE
lastUpdatedDateTime does not reflect correct date time

### ISSUE THREAD

**Issue by joostvdlinden** [microsoftgraph/microsoft-graph-docs#18661]
The following article, published by Microsoft, describes that the API endpoint GET /chats response JSON payload includes a 'lastUpdatedDateTime' property: [https://learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http](https://learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http) 

The API does indeed include the property in its response, but the date and time does not reflect the correct date time. In my opinion this makes the endpoint useless. 

I suppose this is a bug? Or is there any workaround to work around this issue?

Thanks for all help provided.

Update:
Even Example 3 supplied by the article does not even work...
I get the error message:

`
{
    "error": {
        "code": "BadRequest",
        "message": "Could not find a property named 'lastMessagePreview' on type 'microsoft.graph.chat'.",
        "innerError": {
            "date": "2022-09-27T20:44:21",
            "request-id": "5dc56063-6b3c-477c-9479-dab876795fb3",
            "client-request-id": "5dc56063-6b3c-477c-9479-dab876795fb3"
        }
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a97dd66c-3052-87c8-ddfc-c41d180faa42
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
We are checking the issue.

**Comment by Prasad-MSFT** [comment]
@joostvdlinden -
**Case-1:** 
We tried to repro the issue, however it's working fine at our end.
`lastUpdatedDateTime `denotes Date and time at which the chat was renamed or list of members were last changed.

1.Updated chat name 
![image](https://user-images.githubusercontent.com/62237649/194813471-8ffb2948-8bcb-4e9f-9ce8-7d94449464fd.png)

_FYI , here the timezone is in IST_

2. Run the below query and the `lastUpdatedDateTime` is showing correct only.
![image](https://user-images.githubusercontent.com/62237649/194813546-918c9c56-ad77-4ff7-8436-c9c6f76cc3b2.png)

_FYI, the timezone in the output of the API is in UTC. So, on converting it will be 12:30 PM in IST_

**Case-2:**

Tried to run the query as mentioned in [Example-3](https://learn.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http#example-3-list-all-chats-in-order-of-the-most-to-least-recent-chat-messages) and it gives the same error as described.
![image](https://user-images.githubusercontent.com/62237649/194814736-9d5bee42-c8fe-4795-9b2c-d8bc3650f384.png)

We have raised a bug for the same and engineering team is looking into it. We will inform you once we get any further update. Thanks!

**Comment by joostvdlinden** [comment]
Hi @Prasad-MSFT, you're right about Case 1. I did find the information that this property only updates when a chat has been renamed or members have been added.
Thanks for looking into Case 2.

**Comment by Prasad-MSFT** [comment]
@joostvdlinden - The bug is fixed. Please do verify.
Thanks!

**Comment by joostvdlinden** [comment]
@Prasad-MSFT it looks like it has been resolved.
