### ISSUE TITLE
 If these APIs are free to use then while submitting the Request access form why I have been asked for Azure Subscription details? Please clarify.

### ISSUE THREAD

**Issue by ProgrammingWithDJ** [microsoftgraph/microsoft-graph-docs#18703]
If these APIs are free to use then while submitting the Request access form why I have been asked for Azure Subscription details? Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b32ca7f9-ea75-d0fd-f887-136e0c9686e3
* Version Independent ID: 6e9b24bc-9869-0b70-8881-3c4aad2bebed
* Content: [Protected APIs in Microsoft Teams - Microsoft Graph](https://learn.microsoft.com/en-us/graph/teams-protected-apis)
* Content Source: [concepts/teams-protected-apis.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-protected-apis.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
@ProgrammingWithDJ - This is not a required field.
For consuming below APIs you need to have subscription details:
```
Export chat: getAllMessages
Export channel: getAllMessages
Update channel: chatMessage
Update chat: chatMessage
Change notifications: chatMessage
Change notification: conversationMember
```

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required.
Thanks!
