### ISSUE TITLE
mail attribute is not nullable

### ISSUE THREAD

**Issue by willfiddes** [microsoftgraph/microsoft-graph-docs#18722]
Update article to state that mail attribute is not nullable.

For cloud only users with no license, it is possible to update the mail attribute, however an error will be received if it is attempted to be assigned a empty string or null as the value. Other attributes on this page identity if it is non-nullable, this one should be flagged as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
mail attribute can be null. Try creating a new user without specifying the mail value. Then GET the user by id, you will see the new user's mail attribute is null.

**Comment by willfiddes** [comment]
Once the user is created, you can't set the mail attribute to null. If you read my description carefully. I said when udpating a user, not creating a user. The mail attribute is NOT nullable when trying to "update" the property. We should update the doc to mention this.
