### ISSUE TITLE
clarification for the callRecords subscription quota

### ISSUE THREAD

**Issue by bughit** [microsoftgraph/microsoft-graph-docs#18733]
https://learn.microsoft.com/en-us/graph/webhooks#teams-resource-limitations

> Per organization: 100 total subscriptions

Is this for the organization sending the notifications (across all receiving apps/orgs)?

Or for the organization receiving the notifications (across all sending orgs)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in resource data - Microsoft Graph](https://learn.microsoft.com/en-us/graph/webhooks)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jumasure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @stephenjust - Kindly assist.

**Comment by stephenjust** [comment]
The limit is associated with the organization that the webhook subscription is created on behalf of.

With multi-tenant applications, where many organizations can use the same application that creates subscriptions, the limit is per organization using the application - it doesn't count against any limit for the app publisher.

So if Contoso uses an app that creates 100 different subscriptions publishing to 100 different webhook endpoints for call records in Contoso, Fabrikam could also use the same app to send webhook notifications for their org to 100 different places.

(We expect organizations to use significantly less than 100 different webhook subscriptions, most should only have <5 subscriptions against them. It's a high data volume, and relatively sensitive data to be sending to many places.)
