### ISSUE TITLE
Not enough clear examples

### ISSUE THREAD

**Issue by epuio** [microsoftgraph/microsoft-graph-docs#18731]
When you state "Enter a value specific to your application, such as myapp://auth." you're assuming we have some understanding of what that means. I'm trying to access an Excel sheet in SharePoint. The graph page (https://learn.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-1.0&preserve-view=true) sent me to this page to figure out authentication. The "quickstarts" page you reference doesn't provide any quick clue as to what I should enter for URL. 

Then, I get to the end, having clicked Register, and there is no documentation telling me who to get a bearer token. Again, you assume I'm going to understand that. 

I find Azure so very difficult to navigate in this way. Amazon and Google are far more intuitive. You have componentized everything so much that I have to learn the architecture of each component before I can solve my very specific need that crosses multiple components. 

Finally, to be as clear as possible, authentication and authorization are the most fundamental requirements for accessing an API. I should not have to spend hours trying to figure out how to get a bearer token. Each application (e.g., Excel) should have clear step-by-step instructions on how to get a bearer token for that application. Then, I can quickly get through the red tape of authentication and authorization and start actually trying to solve a business problem. I'm not trying to trivialize authn and authr. They're critically important. But don't make figuring them out more difficult than solving business logic. The latter is my goal. The former should be a nearly transparent facilitator.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bf9ff3a-a9db-3996-731a-0fdc3fcd103a
* Version Independent ID: 034a7f02-2a99-ffbc-e818-653bb8d72ba5
* Content: [Register your app with the Azure AD v2.0 endpoint - Microsoft Graph](https://learn.microsoft.com/en-us/graph/auth-register-app-v2)
* Content Source: [concepts/auth-register-app-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-register-app-v2.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies @epuio for the delayed response. Thank you for this feedback, and I apologize for the unfavorable experience.

Yes, you're right. AuthN/Z are the most basic concepts to deal with before you can call an API and we should make them as easy to understand as possible. I've taken your feedback and shared it with the team for consideration. I'll get back to you with a response on doc updates that we'll make.

**Comment by lramosvea** [comment]
@FaithOmbongi any update on this? Thanks

**Comment by FaithOmbongi** [comment]
Hi @lramosvea - We have two PRs to address this and related authN/Z issues. Should be merged by the end of May then we'll close this issue. Thanks.
