### ISSUE TITLE
LicenseAssignment.ReadWrite.All as Least Privileged Permission

### ISSUE THREAD

**Issue by SeanC2222** [microsoftgraph/microsoft-graph-docs#18753]
This page doesn't document `LicenseAssignment.ReadWrite.All` as a viable permission for this call. Is this intentional? It appears that that permission is sufficient _and_ the least privileged permission to access to this endpoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 55a0c1ea-55ef-cde5-717d-6c48980afe7d
* Version Independent ID: fe4af7e1-b7b1-ca53-ebdc-dfc05932337b
* Content: [group: assignLicense - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-assignlicense?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-assignlicense.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-assignlicense.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @SeanC2222 for asking this question. Unfortunately, _LicenseAssignment.ReadWrite.All_ is currently not properly scoped to read license assignments for groups. Please don't rely on the permission until it's referenced in the documentation. We have an internal work item to track the resolution of this issue. Thank you.
