### ISSUE TITLE
members@delta Part is not clear in the Group delta result

### ISSUE THREAD

**Issue by devsmart** [microsoftgraph/microsoft-graph-docs#18763]
members@delta shows as 
```
   "members@delta": [
        {
          "@odata.type": "#microsoft.graph.user",
          "id": "693acd06-2877-4339-8ade-b704261fe7a0"
        },
        {
          "@odata.type": "#microsoft.graph.user",
          "id": "49320844-be99-4164-8167-87ff5d047ace"
        }
      ]
```

This is not clear, what are these IDs? Are they added or removed User/Group Ids?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e89b9ed-663c-3639-9d0d-9aad705920f3
* Version Independent ID: b003a86a-f78f-05eb-e67d-54bb5ca0f2b1
* Content: [group: delta - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-delta.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @devsmart for asking this question. Given there are no @removed or @changed annotations, those are IDs for the users that were added as new members of the group.
