### ISSUE TITLE
Error when filtering servicePrincipal on appRoleAssignmentRequired

### ISSUE THREAD

**Issue by DMoenks** [microsoftgraph/microsoft-graph-docs#18795]
Notice: IDs in below error messages were left in place as Graph Explorer was used with the provided sample data.

According to the documentation, **servicePrincipal** resources should be filterable on their property **appRoleAssignmentRequired** with at least _eq_ and _ne_ operators. Executing the following query in Graph Explorer...

```
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appRoleAssignmentRequired eq true
```

...results in the following error message though:

```
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported or invalid query filter clause specified for property 'appRoleAssignmentRequired' of resource 'ServicePrincipal'.",
        "innerError": {
            "date": "2022-10-09T13:07:23",
            "request-id": "b445ca76-9644-4682-89e0-4c9f88cfa772",
            "client-request-id": "b445ca76-9644-4682-89e0-4c9f88cfa772"
        }
    }
}
```

Executing the following query instead...

```
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appRoleAssignmentRequired ne false
```

...results in the following error message:

```
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported property filter clause operator 'NotEqualsMatch'.",
        "innerError": {
            "date": "2022-10-09T13:16:41",
            "request-id": "a6f10f93-a95d-4566-8783-f07e1bfe3b51",
            "client-request-id": "a6f10f93-a95d-4566-8783-f07e1bfe3b51"
        }
    }
}
```

As querying works as expected when filtering on other properties, I suppose the error is not caused by limitations in Graph Explorer. Question is, if this is either caused by an issue in Graph API or if the documentation is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcef076-0419-d0c9-1d49-c7c9a95317ce
* Version Independent ID: 0cd73e6b-f547-c257-4ffc-faeb4cfd1abf
* Content: [servicePrincipal resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/serviceprincipal.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @DMoenks, for raising this issue. Filtering service principals using the appRoleAssignmentRequired property requires [advanced query parameters](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#service-principal-properties) as per this little box just before the properties table. 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/14026935/195411824-069e2943-01f1-417e-851f-bedd76697e76.png">

So add the **ConsistencyLevel** header set to `eventual`, and `$count=true` query string and both queries will succeed.

**Comment by DMoenks** [comment]
> Thank you @DMoenks, for raising this issue. Filtering service principals using the appRoleAssignmentRequired property requires [advanced query parameters](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#service-principal-properties) as per this little box just before the properties table.
> 
> <img alt="image" width="541" src="https://user-images.githubusercontent.com/14026935/195411824-069e2943-01f1-417e-851f-bedd76697e76.png">
> 
> So add the **ConsistencyLevel** header set to `eventual`, and `$count=true` query string and both queries will succeed.

I actually checked the advanced query parameters article for properties requiring the additional parameters before running the query, but I obviously must have overlooked the entry for _appRoleAssignmentRequired_ in the list. I suppose I might have looked at the list of _application_ properties instead of the _service principal_ properties in that article.
Sorry for that, my bad.

Following up on the hint I tried using the parameters and it results in the queries to succeed. I wouldn't actually call the resulting output "successful" though, at least if my understanding of Boolean terms isn't faulty:

```
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appRoleAssignmentRequired eq true&$count=true
ConsistencyLevel: eventual
```
...returns 0 results, which might be true if no service principals exist or if all of them would use the default setting, which if `false` according to the [servicePrincipal properties](https://learn.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0#properties) list.

```
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appRoleAssignmentRequired eq false&$count=true
ConsistencyLevel: eventual
```
...also returns 0 results, which might again be true if no service principals exist.

```
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appRoleAssignmentRequired ne true&$count=true
ConsistencyLevel: eventual
```
...returns 236 results, all of them having their _appRoleAssignmentRequired_ property set to `false`, which matches the query but doesn't match the results from the previous query.

```
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appRoleAssignmentRequired ne false&$count=true
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=NOT(appRoleAssignmentRequired eq true)&$count=true
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=NOT(appRoleAssignmentRequired eq false)&$count=true
ConsistencyLevel: eventual
```
...also all return the same 236 results having their _appRoleAssignmentRequired_ property set to `false`.

At least the last three queries seem to break my understanding of querying Graph for specific properties and I couldn't yet find anything in the documentation that would explain that specific behavior.
