### ISSUE TITLE
Doesn't mention Event Hubs at all on web hooks main page

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#18799]
I don't see any mention of Event Hubs in our change notification documentation page at all. 

We have a page called [Get change notifications delivered in different ways - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/change-notifications-delivery)

but if i control F on the main page it really should mention Event Hubs there.The only way I found this was Google search.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in resource data - Microsoft Graph](https://learn.microsoft.com/en-us/graph/webhooks)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jumasure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Currently working on this as part of the overhaul/refresh of change notifications docs. The article should be updated in a few weeks.

**Comment by jumasure** [comment]
https://learn.microsoft.com/en-us/graph/webhooks?view=graph-rest-1.0#receiving-change-notifications
