### ISSUE TITLE
Update message not working

### ISSUE THREAD

**Issue by OsniNeto** [microsoftgraph/microsoft-graph-docs#18867]
Hello

I'm trying to update a message of a channel chat, but the request is returning a error...

In GraphExplorer:
GET
![image](https://user-images.githubusercontent.com/17650353/195705502-4e267613-f1fb-404f-8e8c-350423421b84.png)

PATCH
![image](https://user-images.githubusercontent.com/17650353/195705544-3b3d063f-ba0b-4902-8c5f-03632c63e685.png)

In GraphClient SDK:
First, i get de message from client:

`var chatMessage = await _graphService.Teams[<TeamId>].Channels[<ChannelId>].Messages[<MessageId>].Request().GetAsync();`

Than, i update de body content:
```
chatMessage.Body = new ItemBody
{
    ContentType = BodyType.Html,
    Content = <New Text>
};
```
And finally, i try to update the message
`var message = _graphService.Teams[<TeamId>].Channels[<ChannelId>].Messages[<MessageId>].Request().UpdateAsync(chatMessage);`

This call results in:
  _Code: BadRequest
  Message: Rich html messages require details of attachments, mentions and reactions.
  Inner error:
	  AdditionalData:
	  date: 2022-10-13T20:43:05
	  request-id: 320d59f8-fd45-4de6-a5b8-67957f5e98b7
	  client-request-id: 320d59f8-fd45-4de6-a5b8-67957f5e98b7
  ClientRequestId: 320d59f8-fd45-4de6-a5b8-67957f5e98b7_

What i'm doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd7e4bdc-e669-efe9-0c08-73d5397bbf5b
* Version Independent ID: 19780b63-b20a-08b8-b181-bee8133f605c
* Content: [Update chatMessage - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chatmessage-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by terranj** [comment]
Would love to see this fixed as well.

**Comment by GuillaumeSD** [comment]
You can't update the content body of a message.

@OsniNeto @terranj see https://learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-1.0&tabs=http#request-body

> In the request body, supply a JSON representation of a [chatMessage](https://learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0) object, specifying **only the policyViolation property**

**Comment by OsniNeto** [comment]
@GuillaumeSD What about the beta API?

The documentation says that is possible update any prop...
[https://learn.microsoft.com/en-us/graph/api/chatmessage-update?view=graph-rest-beta&tabs=http#request-body](url)

> Example for updating any property of a message by using delegated permissions

From beta, i received the same error
![image](https://user-images.githubusercontent.com/17650353/198391438-b1de0015-d6c0-45d8-b9ba-c093b072e09d.png)

**Comment by GuillaumeSD** [comment]
@OsniNeto I am not using the beta version atm, so I don't have information on that. Bear in mind that : 

> APIs under the /beta version in Microsoft Graph are subject to change. Use of these APIs in production applications is not supported.

If you want to update messages created by your bot, you should use the Connector API.

**Comment by Meghana-MSFT** [comment]
@OsniNeto - We tried this at our end, and we are able to update the message properly using beta and V1.0. Can you please confirm if you are still experiencing this issue?
![image](https://user-images.githubusercontent.com/81138249/209559808-a343b16c-4842-4f03-ad84-058b55de5269.png)

**Comment by GuillaumeSD** [comment]
@Meghana-MSFT It indeed works with `"contentType:" "text"`, but can you get it working with `"contentType:" "html"`. It doesn't work on my end with html.

**Comment by Meghana-MSFT** [comment]
@GuillaumeSD - We will check and get back to you.

**Comment by Meghana-MSFT** [comment]
@GuillaumeSD - Based on the error message it seems like when contentType is html, the messages require details of attachments, mentions, reactions.

I did try like above by mentioning only text inside `<p></p>` tags and got the same error as you. Whereas adding an attachment in the update message API call works fine.

![image](https://user-images.githubusercontent.com/81138249/210774754-75fe4029-61b7-409c-8285-4d714ba02e75.png)

**Comment by Meghana-MSFT** [comment]
@OsniNeto, @GuillaumeSD - The validation has been removed. Update message is working when html content type is added. We tested this today and it has worked successfully. Thank you for your patience. 
![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/81138249/422c53c1-7f3a-45e5-9d5e-5bacb6d2a0c8)
