### ISSUE TITLE
Spell mistake udpate 

### ISSUE THREAD

**Issue by wilbertduenk** [microsoftgraph/microsoft-graph-docs#18875]
Ctrl+F on udpate and you will find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa9ed02-2297-9f0b-27c2-b523d72ed87f
* Version Independent ID: c4d6c886-d3ab-e7fb-eaab-aa9c2defd98c
* Content: [windowsUpdateState resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/intune-shared-windowsupdatestate?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-shared-windowsupdatestate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-shared-windowsupdatestate.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback.  I've filed a bug to get it addressed.
