### ISSUE TITLE
RequestBroker-ParseUri when listing categories

### ISSUE THREAD

**Issue by mohamedltaief** [microsoftgraph/microsoft-graph-docs#1888]
I tried to list categories:
- Request:
```GET https://graph.microsoft.com/beta/me/outlook/masterCategories```
- Response:
```
{
    'error': {
        'innerError': {
             'date':  '2017-10-24T10:37:04',
             'request-id': u'e12d16a9-53e9-4e8b-819f-5cf20a91b7c4'
        },
        'message':  "Resource not found for the segment 'Outlook'.",
        'code': u'RequestBroker-ParseUri'
    }
}
```

**Comment by ghostring31** [comment]
Same problem

**Comment by ArunMSFT** [comment]
Thanks for reporting, we're looking into the issue.

**Comment by ArunMSFT** [comment]
Is this still happening, I'm having difficulty repro'ing it in my setup.

**Comment by Spazer9** [comment]
Same issue here still happening @dmahugh 

Not sure if anyone is able to access these API endpoints

**Comment by Spazer9** [comment]
Same issue here still happening @dmahugh @ArunMSFT 

Not sure if anyone is able to access these API endpoints

**Comment by Spazer9** [comment]
@ArunMSFT Even the example request "my outlook categories" on the Microsoft graph explorer itself returns this error FYI. (with mailboxsettings.readwrite permission too)

![](https://s3.amazonaws.com/snaps-bucket/2017/12/ufdod9P/2017-12-28_18-08-35.png)

**Comment by ArunMSFT** [comment]
Thanks Spazer9. Could you tell us if the account you are using is a Office 365 account or an Outlook.com account?

**Comment by Spazer9** [comment]
Hey @ArunMSFT - it's ryanworks7@outlook.com - happy to even provide the password since it's just a dispostable test account.

**Comment by ArunMSFT** [comment]
Thanks Spazer9.

**Comment by ArunMSFT** [comment]
The issue has been fixed. Pl reoopen if it happens again.
