### ISSUE TITLE
GraphAPI Search issue for entity type 'chatMessage'

### ISSUE THREAD

**Issue by penleychan** [microsoftgraph/microsoft-graph-docs#18900]
Hello,

The GraphAPI search for 'chatMessage' entityType is no longer returning chat messages (1:1 chat/group chats), however I do see channel messages is now included in the response which is great addition to the API.

Another issue 'total' from hit results is returning incorrectly:
Results only return 3 hits but the total = 11?

<img width="532" alt="image" src="https://user-images.githubusercontent.com/5407937/196245823-36974c13-47a0-425f-b80d-b6f897677223.png">

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71635643-eee1-2894-f676-aa6869403aef
* Version Independent ID: c550a543-c448-29f8-5a4d-4bdd77352708
* Content: [searchRequest resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/searchrequest.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmoreau** [comment]
@thewahome can you reassign to someone from the Microsoft Search product team ?

**Comment by yiwenwang-ms** [comment]
Thanks @nmoreau for redirect to the correct team!
Hi @penleychan, could you please share me searchRequest sample and the provide me the clientRequestId in the response header.

**Comment by penleychan** [comment]
Hello @yiwenwang-ms 

Thank you for fixing the search on 1:1/group chat. 

As per your request:

searchRequest
````
{
    "requests": [
        {
            "entityTypes": [
                "chatMessage"
            ],
            "query": {
                "queryString": "bot"
            },
            "from": 0,
            "size": 25
        }
    ]
}
````

"client-request-id": "c29d169f-e816-b457-abe7-6585ff4e0992"

**Comment by yiwenwang-ms** [comment]
Hi @penleychan, could you please help double confirm today to see whether you can search 1:1/group chat?

**Comment by penleychan** [comment]
Hi @yiwenwang-ms I can confirm that the 1:1/group chat is in fact working along with channel messages in search results.
Many thanks.

**Comment by yiwenwang-ms** [comment]
Good news! Thank you for reaching out to us!
