### ISSUE TITLE
Will it be possible to add multiple conversation members during the creation of a shared channel?

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs#18919]
Hi there,
I noticed a difference between creating a private and a shared channel.

When creating a private channel, you can pass multiple members to the array. If you create a shared channel, it only works to add a single user even if the object accepts an array. Is this behavior by design or could this be a bug?

Thank you for your feedback,
Patrick

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce77c63d-12f7-828d-f0a9-2b72835412f0
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create channel - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @AkJo
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@plamber - We are also able to repro this issue, we are checking internally and get back to you.

**Comment by devjha-ms** [comment]
Hi @plamber Specifying more than one member while creating the shared channel is not allowed. The request will fail with similar error as below when more than one member is specified:

"message": "{\"errors\":[{\"message\":\"In App-context, the specified Users in the request must be a team owner.\",\"errorCode\":\"Unknown\"}],\"operationId\":\"db7fba4e777f7a499015cb5c464afe22\"}",

**Comment by plamber** [comment]
Hi @devjha-ms ,
Thank you for the confirmation. Is this something that you plan to add in future to be consistent with the other APIs?

I would recommend to add a hint in the documentation if this is not the case.

Cheers

**Comment by devjha-ms** [comment]
@plamber 

 Is this something that you plan to add in future to be consistent with the other APIs?
 
 This is not yet planned.
We will update the documentation to stating the current behaviour.

**Comment by Meghana-MSFT** [comment]
@plamber - A note has been added in the [documentation](https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http) stating "While creating a channel, you can only add one member per shared channel; however, you can add up to 200 members per private channel".

**Comment by Meghana-MSFT** [comment]
We are closing this issue, please feel free to reach out to us if you have any questions. Thanks.
