### ISSUE TITLE
requireChangeOnNextSignIn flag doesn't work as described

### ISSUE THREAD

**Issue by IgorCayosoft** [microsoftgraph/microsoft-graph-docs#18911]
The requireChangeOnNextSignIn flag doesn't work as described. Using requireChangeOnNextSignIn: false leads to a message like "This flag is not avilable" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2677688a-13a6-b2e2-ac25-7c28f35e6ef3
* Version Independent ID: 2ae14fab-ad85-bdab-371f-3a5cd3b514e0
* Content: [authenticationMethod: resetPassword - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/authenticationmethod-resetpassword?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/authenticationmethod-resetpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authenticationmethod-resetpassword.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @zhvolosh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @IgorCayosoft - My apologies for the experience. The **requireChangeOnNextSignIn** property will be deprecated soon, and we will make the required doc changes, communicating the alternative way to achieve the functionality.

@zhvolosh for visibility and prioritization.

**Comment by BakkerJan** [comment]
@FaithOmbongi @zhvolosh @mmcla Thanks! Any workaround for now that you can share?

**Comment by mmelkersen** [comment]
Would be very nice to know if we have a new property to put in the body to remove the need for the user to change the password. Thank you

**Comment by FaithOmbongi** [comment]
Hi @IgorCayosoft, @BakkerJan, @mmelkersen - Thank you for your patience.

requireChangeOnNextSignIn = false will not be supported by the [resetPassword API](https://learn.microsoft.com/en-us/graph/api/authenticationmethod-resetpassword?view=graph-rest-1.0&tabs=http) and we have deprecated the property. This is also a best practice as a password should be secret and an admin should never have the need to know a user’s password.
 
However, (if you really need this functionality) as a temporary workaround, you can explore the [Update passwordProfile](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#example-3-update-the-passwordprofile-of-a-user-to-reset-their-password) operation.
 
I’ve also raised a PR to remove the **requireChangeOnNextSignIn** property from the docs.
