### ISSUE TITLE
ChannelMessage.ReadWrite.All in Application context

### ISSUE THREAD

**Issue by rezabj** [microsoftgraph/microsoft-graph-docs#18928]
It looks like the ChannelMessage.ReadWrite.All permission in Application context is not available. I don't know why, but I guess it is replaced by Teamwork.Migrate.All permission. If this is true, can you fix the documentation?

This inconsistency is listed in both version 1.0 and Beta.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72b46d81-1b08-24b6-b873-0636af81cbe7
* Version Independent ID: 402882ed-8c20-e848-8103-9a01f1df1d37
* Content: [Send replies to a message in a channel - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chatmessage-post-replies?view=graph-rest-1.0&tabs=http#permissions)
* Content Source: [api-reference/v1.0/api/chatmessage-post-replies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chatmessage-post-replies.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
Engineering team is working on fixing the document.
Same permission issue for Send chatMessage in a Channel has been reported here - https://github.com/microsoftgraph/microsoft-graph-docs/issues/18996

**Comment by ChetanSharma-msft** [comment]
Hello @RamjotSingh, @AkJo - Could you please help us here to update the documentation?

**Comment by fcjack** [comment]
Hi, I am trying to send a message to a channel using the api.
In the docs we have the permission ChannelMessage.ReadWrite.All, but this is not available on Api Permissions configuration and the Teamwork.Migration.All can't be used unless is an import operation.

 Is there any way to send a message from a bot, using the REST API?
 If yes, could you point here?

**Comment by Meghana-MSFT** [comment]
Can you please check if this helps - https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#reply-to-activity

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Please feel free to reopen otherwise. Thanks.
