### ISSUE TITLE
UPDATE operation

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#18939]
I know this is in beta, but I don't expect the rules will change after GA, so can you please update the documentation on the UPDATE operation to list only properties that can actually be modified post creation of a retention label? I.e. you cannot use a PATCH request to modify the displayName. Same goes for almost all of the remaining properties, so the current table is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c1531fe-cda7-a085-2f25-9b24514d4df6
* Version Independent ID: 2be0e273-4e58-69db-013f-e7af5739c84f
* Content: [Update retentionLabel - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/security-retentionlabel-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/security-retentionlabel-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionlabel-update.md)
* Product: **compliance**
* Technology: **microsoft-graph**
* GitHub Login: @sseth
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sseth** [comment]
@michevnew Hi, you probably meant to tag someone else here

**Comment by sseth-msft** [comment]
Fixing this in the PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/19605

**Comment by sseth-msft** [comment]
This is fixed and merged but still showing up on my weekly github list, can you take a look at this, @michevnew

**Comment by michevnew** [comment]
Yes, I can see the smaller table, seems good.
