### ISSUE TITLE
DisplayName does not have to be a unique value.  Docs should state that.

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs#18935]
When creating a group in azure, the displayName property does not have to be unique.  You can create multiple groups with the same displayName value.  This is confusing to admins who are used to on-prem development where a group name must be unique.  Can the docs be updated to reflect that?  I did open an escalation ticket to the product group to learn that this is the expected behavior in Azure.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DMoenks** [comment]
You might be surprised, at least I was, that groups don't require unique display names even in Active Directory, they just require unique names. I just tested this with two universal security groups residing in the same organizational unit.
So stating this in some Azure Active Directory or Graph documentation might in fact imply a difference to Active Directory which doesn't actually exist.

**Comment by FaithOmbongi** [comment]
Thank you @DMoenks for sharing these insights about the **displayName** property.
Hi @RayGHeld - I hope Dominik's answer is satisfactory. No doc update identified for now. Closing this issue.
