### ISSUE TITLE
getting other's avatar always returns own avatar

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1898]
If you use personal mail end with my@outlook.com (not office 365 account) to run

```
POST https://graph.microsoft.com/beta/$batch

{
  "requests": [
    {"url": "/users/anyother@notexisit.com/photos/48X48/$value", "method": "GET", "id": "1"}
  ]
}
```

instead of return 404, it always returns 200 with the user's own avatar.
It only happens when use $batch.

```
GET https://graph.microsoft.com/v1.0/users/anyother@notexisit.com/photos/48X48/$value
```

works well which returns 404.

**Comment by Hongbo-Miao** [comment]
Further test, the issue is not related with batch
```
GET /v1/users/anyother@notexisit.com/photos/48X48/$value
```
returns
```
{
    "error": {
        "code": "ErrorInvalidUser",
        "message": "The requested user 'anyother@notexisit.com' is invalid.",
        "innerError": {
            "request-id": "018f381d-07d2-470a-b782-22ada3c964f9",
            "date": "2017-11-29T18:39:34"
        }
    }
}
```
which is correct.

However,
```
GET /beta/users/anyother@notexisit.com/photos/48X48/$value
```
always return my own avatar.

The issue only happens to personal account.

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
