### ISSUE TITLE
Pass an existing PublicClientApplication in the publicClientApplication property documentation is incorrect

### ISSUE THREAD

**Issue by elninoisback** [microsoftgraph/microsoft-graph-docs#18994]
The code mentioned below doesn't work:

interface Msal2PublicClientApplicationConfig {
  publicClientApplication: PublicClientApplication;
  scopes?: string[];
  authority?: string;
  redirectUri?: string;
  loginType?: LoginType; // LoginType.Popup or LoginType.Redirect (redirect is default)
  prompt?: PromptType; // PromptType.CONSENT, PromptType.LOGIN or PromptType.SELECT_ACCOUNT
  sid?: string; // Session ID
  loginHint?: string;
  domainHint?: string;
  options?: Configuration // msal-browser Configuration object
}

It's more or less the same mentioned in https://www.npmjs.com/package/@microsoft/mgt-msal2-provider?activeTab=readme
and that doesn't work either.

Basically it doesn't tell you how to get the PublicClientApplication from msal-angular.
Because with Angular, you register your public client in APpModule as MsalModule.forRoot(new PublicClientApplication({});
There is no way mentioned to get it back afterwards, as this incorrect documentation points out

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c957619d-0f7e-2894-311b-f5ea8a30da3c
* Version Independent ID: 69b1d469-7b39-146e-8922-9bfc5b67d273
* Content: [MSAL2 provider - Microsoft Graph](https://learn.microsoft.com/en-us/graph/toolkit/providers/msal2)
* Content Source: [concepts/toolkit/providers/msal2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/toolkit/providers/msal2.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @sebastienlevert
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sebastienlevert** [comment]
In this case you wouldn't pass a new PublicClientApplication() but an instance you'd create and keep to pass it to the Provider. Would that work for you?

**Comment by elninoisback** [comment]
> In this case you wouldn't pass a new PublicClientApplication() but an instance you'd create and keep to pass it to the Provider. Would that work for you?

It is not clear how to 'keep' the PublicClientApplication at hand when you need one. Even if you have one, when do you need to pass in another dozen of parameters along with the PCA when newing up the Msal2Provider? It doesn't make sense.

**Comment by mattallscripts** [comment]
@sebastienlevert I'd love an example of how this would work too. How do we retrieve the PublicClientApplication that is created for MsalModule.forRoot( new PublicClientApplication(... and then pass that into the Msal2PublicClientApplicationConfig?

**Comment by elninoisback** [comment]
> @sebastienlevert I'd love an example of how this would work too. How do we retrieve the PublicClientApplication that is created for MsalModule.forRoot( new PublicClientApplication(... and then pass that into the Msal2PublicClientApplicationConfig?

Hi @mattallscripts, I've been meddling with this ever since. So far what I've found was, the msalService.instance which you have at hand IS the PublicClientApplication! Currently, I'm using the following code to get it registered as the global provider for toolkit components.

`Providers.globalProvider = new Msal2Provider({ publicClientApplication: this.msalService.instance as PublicClientApplication });`

**Comment by mattallscripts** [comment]
Ok great, that's helpful to know it's working for you as well. I was literally just about to write back as I had found an sample that was added as part of the original pull-request for this feature "[_Allow PublicClientApplication to be passed directly into Msal2Provider_](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/1175)"

On the very bottom of that page, you'll see that a sample was merged;
https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/1192

```
  private configureMgt() {
    Providers.globalProvider = new Msal2Provider({
      publicClientApplication: this.msalService.instance as PublicClientApplication,
      scopes: (MsalGuardConfig.authRequest as MsalGuardAuthRequest).scopes,
      options: MsalConfig
    });

```

So if you hit any further road blocks, you might look there for how they're doing it.

**Comment by elninoisback** [comment]
Thanks @mattallscripts! It's really relieving to see it officially! I'm not sure why you need to pass in scopes and options though. Maybe if the app uses progressive scopes?

**Comment by sebastienlevert** [comment]
Glad you got it working! Closing for now!
