### ISSUE TITLE
Type of property "logo":  "Stream" or "String"?; if "Stream", what is that?

### ISSUE THREAD

**Issue by dsbos** [microsoftgraph/microsoft-graph-docs#19018]
The properties section says that the type of property `logo` is `Stream`.

It that is correct, what is type `Stream`?  (There doesn't seem to be any documentation the names/phrases in the Types column that are not links to documentation (e.g., likes to page sections for nested JSON).

Or is that type supposed to be `String` instead of `Stream`?

(The JSON example says `..., "logo": "Stream", ...`, which isn't clear:
- Is `Stream` there a literal value (e.g., of some enumeration type, maybe saying how to retrieve a logo image)?
- If `Stream` there just stands in form the representation of a stream encoded as a string, what is the format of the string?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f54172c8-c149-8002-b172-5d1d286177f0
* Version Independent ID: c23c0d2f-5f70-e67d-9068-99e660126fd0
* Content: [application resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/application.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hi @dsbos,

based on other documentation articles, I assume that Stream in this context means the binary data of an image. Does it help to clarify your question?

Thanks,
Jarbas

**Comment by FaithOmbongi** [comment]
Hi @dsbos - As @JarbasHorst has correctly indicated, [Stream](http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#_Toc38530338:~:text=Edm.Stream,Binary%20data%20stream) is the binary data for an image.

**Comment by dsbos** [comment]
> Does it help to clarify your question?

No.

1. JSON does not define a representation of binary data, so the answers so far do not answer how a the binary data is represented in represented in JSON. Presumably, its in a JSON string, but how does the string encode the binary data?  

2. The answers so far do not answer the question of which format or formats the image data can be in, or, if there are several options, how to know which format it is in? (E.g., is a client expected to look for "magic" numbers to recognize the binary format?

(Or does Stream mean there's a JSON object with some (nested) property that specifies the format, with some string property that encodes the binary data?)

> based on other documentation articles,

Is there one that specifies what type Stream is?  (I looked but did find one.)

**Comment by JarbasHorst** [comment]
Hi @dsbos,

for clarity, I am trying to support you as a community contributor and I don't have experience with this specific resource.

> Is there one that specifies what type Stream is? (I looked but did find one.)
1. The resource topic about [profile photos ](https://learn.microsoft.com/en-us/graph/api/resources/profilephoto?view=graph-rest-beta) doesn't have a property of type Stream but the corresponding [GET ](https://learn.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-beta#example-5-get-the-team-photos-binary-data)operation returns binary data and the [PATCH](https://learn.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&tabs=csharp) method requires binary data in the request body.

2. [This ](https://learn.microsoft.com/en-us/graph/api/resources/onenoteresource?view=graph-rest-beta)resource has a property of type Stream but the only [example ](https://learn.microsoft.com/en-us/graph/api/resource-get?view=graph-rest-beta&tabs=http)I found is about retrieving content.
