### ISSUE TITLE
The documentation is missing information on how to create retentionDuration

### ISSUE THREAD

**Issue by ayoubelasryRoot** [microsoftgraph/microsoft-graph-docs#19016]
The json schema is missing the "days" attribute 

``` json
"retentionDuration": {
      "@odata.type": "microsoft.graph.security.retentionDurationInDays",
      "days": 1400
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 114de793-1665-cb75-20a1-e149e8f045c7
* Version Independent ID: 71c3dcbe-0318-6527-8672-1491d5abc9eb
* Content: [retentionDuration resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/security-retentionduration?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/security-retentionduration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/security-retentionduration.md)
* Product: **compliance**
* Technology: **microsoft-graph**
* GitHub Login: @sseth
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sseth** [comment]
@ayoubelasryRoot Hi – I don't work for Microsoft. This is the second time this week that I've been assigned an issue here.

**Comment by ayoubelasryRoot** [comment]
very weird it added you by default sorry about that

**Comment by JarbasHorst** [comment]
Hi @ayoubelasryRoot,

thank you for your question. For clarity, why should the days property be added to the retentionDuration resource? The days property is part of the retentionDurationInDays resource.

**Comment by ayoubelasryRoot** [comment]
My mistake, I did not see the property. Thank you for the info also I was confused because the name is not spelled correctly:
Represents how long an item will be retained before it can be deleted. This is an abstract type. The retentionDuration resource is the base type for the retentionDurationForever and **_retnetionDurationInDays_**

**Comment by JarbasHorst** [comment]
No worries and thanks for mentioning the typo. I've authored a PR that when merged will fix this issue.
