### ISSUE TITLE
security: runHuntingQuery always returns 500 - Unknown error

### ISSUE THREAD

**Issue by biste5** [microsoftgraph/microsoft-graph-docs#19084]
We want to integrate hunting in our solution and trying out this endpoint using a Service Principal to which we've provided the necessary Application Permissions.

Tried few simple KQL queries to test and evaluate results, but calls to this endpoint always return an error status code (500), with few more details in the response

```json
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "date": "2022-11-02T13:22:02",
            "request-id": "1033a640-1c97-48f2-a1ad-face30df60a6",
            "client-request-id": "1033a640-1c97-48f2-a1ad-face30df60a6"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75c1195e-9be0-c6fd-a0f4-4e38a68f4f29
* Version Independent ID: 3b43a6e4-664a-c3d8-332b-ea784c78e345
* Content: [security: runHuntingQuery - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/security-security-runhuntingquery?view=graph-rest-beta#request-headers)
* Content Source: [api-reference/beta/api/security-security-runhuntingquery.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-security-runhuntingquery.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @BenAlfasi
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by BenAlfasi** [comment]
Hi @biste5 
Can you please attach a request body for example?
Does It happen for all your Hunting requests?

**Comment by biste5** [comment]
Hi @BenAlfasi ,

yes, I can also provide some more insights based on my tests and findings.
The issue seems to occur always when running a search across all tables (using `search <term>` without a specific table)

So queries of these types, always return _UnknownError_

Queries using specific table(s) seems to return results.

So probably has to do with that, but it doesn't seem to be properly documented.

By the way, we're running these queries without specific table(s) using Log Analytics (REST APIs) and Advanced Hunting API (Defender / ATP) successfully. We're discarding for now the Graph Security APIs due to the issue.

Any further details you can provide about what type of KQL queries are supported by Graph Security, or if it's in the plan to support also our scenario?

**Comment by BenAlfasi** [comment]
Hi @biste5 
We should support any query MDE/MTP Hunting API supports.
Please provide one that works there but fails on Graph and we will make it work :) 
Thanks,
Ben

**Comment by biste5** [comment]
Hi @BenAlfasi ,

thanks!

Here's one of those queries (very simple):

`
search '1.1.1.1' | count
`

**Comment by biste5** [comment]
Hi @BenAlfasi ,

just checking if there's any update or the information I provided are clear enough.
It has been over a month without any update on this issue

**Comment by BenAlfasi** [comment]
Hi @biste5 
Very sorry for the late response (busy days pushing the new APIs to V1.0)

I just tried the following and got bad request:

`
{
    "query": "search '1.1.1.1' | count"
}
`

Can you please share your full request body that is working in the old APIs? 
Can you also please hit some API calls that fail and share your tenant id so we can check the logs?

Thanks,
Ben

**Comment by biste5** [comment]
Hi @BenAlfasi ,

yesterday I wrote a full response with details to your message above, and then trying to hit again Graph endpoint now my request(s) seem to work properly. Quite a surprise :)

I didn't use to do further tests during last month since when I created this issue

Some details about the query that I use, which seems to work also against Graph now

`POST https://graph.microsoft.com/beta/security/runHuntingQuery`

```json
{
    "query": "search \"1.1.1.1\" | limit 1 | count"
}
```

Client Request ID: 07d4bc19-75b1-4281-af2f-2d2f43d06969
Tenant ID: 316bec54-8d14-4882-8af3-ee5e61570603

P.S. Before creating the issue I tested, and I was getting consistent errors against different tenants

**Comment by BenAlfasi** [comment]
Thanks @biste5, 
Please let me know if you have any issue in that area again.
Closing the issue meanwhile.
