### ISSUE TITLE
"accessreviewnotificationrecipientscope resource type" documentation page is missing properties needed and JSON representation with these properties

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-docs#19087]
The documentation page is missing the properties needed for notificationRecipientScope such as @odata.type, query, queryType, and queryRoot. It's also missing a JSON representation with said properties.

Below is an example of a valid notificationRecipientScope:

{
                "@odata.type": "#microsoft.graph.accessReviewNotificationRecipientQueryScope",
                "query": "/v1.0/groups/{group-object-id}/transitiveMembers/microsoft.graph.user",
                "queryType": "MicrosoftGraph",
                "queryRoot": null
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 641542ea-c0b6-1017-68b7-19c3fd258932
* Version Independent ID: 1aec3192-df16-a025-11a8-a0aa4ca747ba
* Content: [accessreviewnotificationrecipientscope resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accessreviewnotificationrecipientscope.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @jyothig123
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @manuel-falcao-magalhaes for raising this issue.

[accessReviewNotificationRecipientScope](https://learn.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-1.0) is actually an abstract type that's inherited by [accessReviewNotificationRecipientQueryScope](https://learn.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientqueryscope). So the three properties are actually properties of accessReviewNotificationRecipientQueryScope (as you can see from the odata.type in the example that you shared) and they are defined in the respective doc.

If in the future another resource type is added that inherits from accessReviewNotificationRecipientScope, it may have different properties from accessReviewNotificationRecipientQueryScope. 

I hope this clarifies the architecture of the objects and the respective docs.
