### ISSUE TITLE
Missing role permissions as managed identity (application permissions)

### ISSUE THREAD

**Issue by PatrickHaake** [microsoftgraph/microsoft-graph-docs#19105]
Hi,

when using the "Get-MgTeamTag" in a runbook with managed identity an error on missing role permissions is raised despite the permissons are set as application permissions as stated in the article.

**Error**
`Get-MgTeamTag : Missing role permissions on the request. API requires one of 'TeamworkTag.Read, TeamworkTag.ReadWrite'. Roles on the request 'TeamSettings.Read.All, TeamworkTag.Read.All'.`

**Permissions on the service principal**
![image](https://user-images.githubusercontent.com/50192312/199684934-f5bf0909-8fcc-4622-8b59-d9c115fb851e.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: 0e1f48bb-e9bc-c63d-0c28-e9cb05e19576
* Version Independent ID: 6cf73fe4-1a9d-006e-d6aa-8debfdbb5358
* Content: [List teamworkTags - Microsoft Graph v1.0](https://learn.microsoft.com/de-de/graph/api/teamworktag-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/teamworktag-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Can you share client-request-Id and timestamp for the failing request?

**Comment by PatrickHaake** [comment]
Here are the requested informations for one example request:

client-request-id: 95861734-a6b4-4370-a261-bda677945cf1
Date: Thu, 03 Nov 2022 10:33:23 GMT

**Comment by RamjotSingh** [comment]
There is an issue on our side. Please check back on this thread next week towards the end and I can share timeline for a fix.

**Comment by RamjotSingh** [comment]
Can you try again and see if you see success now?

**Comment by RamjotSingh** [comment]
Closing since the rollout is done. If it still doesn't work please let us know.

**Comment by PatrickHaake** [comment]
Sorry for the late respone, but this issue is resolved. All queries run without permission error and return the desired informations. Thank you very much!
