### ISSUE TITLE
 Explanation on Mapping of rule IDs to portal settings

### ISSUE THREAD

**Issue by SB-o-matic** [microsoftgraph/microsoft-graph-docs#19122]
The different ruleIDs are not very explanatory and I have not been able to find documentation detailing how they map to the role settings on the Azure portal when configuring PIM role settings. For example, there is confusion when trying to translate ‘EndUser’ or ‘Admin’. Or understand what ‘AuthenticationContext_EndUser_Assignment’ is for. This aspect needs more documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 264e0cf2-1b05-4803-7894-b8313b3fe19f
* Version Independent ID: ee257771-c240-89fe-cd3f-c680fca91ab5
* Content: [List roleManagementPolicies - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/policyroot-list-rolemanagementpolicies?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/policyroot-list-rolemanagementpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/policyroot-list-rolemanagementpolicies.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @rkarim-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @SB-o-matic for this valuable feedback. I'm looking into this.

cc @rkarim-ms to assist.

**Comment by SB-o-matic** [comment]
Hello,
Any updates?

**Comment by FaithOmbongi** [comment]
Hi @SB-o-matic - Unfortunately, it may take a while to get the documentation out. Allow me to reply to this thread once we have it.

cc @rkarim-ms

**Comment by SB-o-matic** [comment]
Can we at least get descriptions of these rule IDs and which portal settings they map to? Documentation can be updated at a later date if desired but we need an answer now to be able to move ahead. Been 7 days since we last heard back.

**Comment by FaithOmbongi** [comment]
My apologies @SB-o-matic for my delayed response. Here's a mapping of the rule IDs and the Azure portal. Let me know if this helps.

Microsoft Graph Rule ID / Derived resource type | Azure Portal UX Description | Caller
-- | -- | --
`Enablement_EndUser_Assignment` / unifiedRoleManagementPolicyEnablementRule | Update justification and MFA requirements for active assignment. | End user
`Approval_EndUser_Assignment` / unifiedRoleManagementPolicyApprovalRule | Require approval to activate. | End user
`Expiration_EndUser_Assignment` / unifiedRoleManagementPolicyExpirationRule | Update the activation maximum duration in hours. | End user
`Enablement_Admin_Eligibility` / unifiedRoleManagementPolicyEnablementRule | Update the justification, MFA, and ticket information requirements upon role activation. | Admin
`Enablement_EndUser_Assignment` / unifiedRoleManagementPolicyExpirationRule | Update justification and MFA requirements for active assignment. | End user
`Enablement_Admin_Assignment` / unifiedRoleManagementPolicyExpirationRule | Update justification and MFA requirements for active assignment | Admin
`Expiration_Admin_Assignment` / unifiedRoleManagementPolicyExpirationRule | Set expiration for active assignment. | Admin
`Expiration_Admin_Eligibility` / unifiedRoleManagementPolicyExpirationRule | Set expiration for eligible assignment. | Admin
`Notification_Approver_EndUser_Assignment` / unifiedRoleManagementPolicyNotificationRule | Send notifications when eligible members activate this role. | Approver
`Notification_Requestor_EndUser_Assignment` / unifiedRoleManagementPolicyNotificationRule | Send notifications when eligible members activate this role. | Requestor
`Notification_Admin_EndUser_Assignment` / unifiedRoleManagementPolicyNotificationRule | Send notifications when eligible members activate this role. | Admin
`Notification_Approver_Admin_Assignment` / unifiedRoleManagementPolicyNotificationRule | Send notifications when members are assigned as eligible to this role. | Approver
`Notification_Requestor_Admin_Assignment` / unifiedRoleManagementPolicyNotificationRule | Send notifications when members are assigned as active to this role. | Requestor
`Notification_Admin_Admin_Assignment` / unifiedRoleManagementPolicyNotificationRule | Send notifications when members are assigned as active to this role. | Admin
`Notification_Approver_Admin_Eligibility` / unifiedRoleManagementPolicyNotificationRule | Send notifications when members are assigned as eligible to this role. | Approver
`Notification_Requestor_Admin_Eligibility` / unifiedRoleManagementPolicyNotificationRule | Send notifications when members are assigned as eligible to this role. | Requestor
`Notification_Admin_Admin_Eligibility` / unifiedRoleManagementPolicyNotificationRule | Send notifications when members are assigned as eligible to this role. | Admin

**Comment by FaithOmbongi** [comment]
Hi @SB-o-matic - Thank you for your patience and thank you for your feedback. We have published an article that maps the rules to the settings on the Azure portal. We hope you find it useful.
