### ISSUE TITLE
How do I return only Members from the delta API for group

### ISSUE THREAD

**Issue by ilantom** [microsoftgraph/microsoft-graph-docs#19202]
How do I return only Members from the delta API for group:

The following code gives an error on .Members

```
await _graphServiceClient
                                    .Groups
                                    .Members
                                    .Delta()
                                    .Request()
                                    .Filter($"id  eq '{groupId}'")                                  
                                    .GetAsync();
```

On trying this:

            var queryOptions = new List<QueryOption>()
            {
                new QueryOption("select", "members")
            };
           
                await _graphServiceClient
                                    .Groups                                    
                                    .Delta()
                                    .Request(queryOptions)
                                    .Filter($"id  eq '{groupId}'")
                                    .GetAsync();

I see this error:

```
Message: Unrecognized query argument specified: 'select'.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdaf58ca-8b6c-cddd-f583-f8617b0450a6
* Version Independent ID: 08b26245-df55-d5d5-a6d2-edc69eda3fe3
* Content: [Get incremental changes for groups - Microsoft Graph](https://learn.microsoft.com/en-us/graph/delta-query-groups)
* Content Source: [concepts/delta-query-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-groups.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jumasure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @ilantom for asking this question.

I'm not a C# expert but I've run the HTTP REST query and successfully got a response. Please [run this query in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%2Fdelta%3F%24select%3Dmembers%26%24filter%3Did%2Beq%2B'06269010-2d8e-48e4-8f0e-33580720c9e1'&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com) to view the C# code snippet.
