### ISSUE TITLE
Create Application - Needs sample to set keyCredentials

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/microsoft-graph-docs#19269]
The [Create application - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http) and the [Update application](https://learn.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http) for that matter can use a sample how to create/update an application that uses a certificate instead of a secret.

This (using a certificate) is the most secure if you cannot use a managed identity.

I'm not telling you that you should show how people can generate a certificate in the Certificate Store, I just want to know how to get from a certificate in the LocalUser store with a certain Thumbprint to a `KeyCredential`.

The use case is that we want to automated everything related to app creation, and this is the only step where we still need the portal because we don't know the magic.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad791e4-374f-b47d-1897-ed7879b18978
* Version Independent ID: 6260abb6-0adf-241d-23d8-78632ee20b3f
* Content: [Create application - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-applications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-applications.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
> I was hoping for a sample http request with the full json body filled-in, to create an application with a certificate. That would help a lot of users that are pragmatically creating applications.

OK. Let me get back to you in a few days with a how-to guide. It will include the HTTP requests, body, and all. 

> We are unblocked because we figured out how to do it with the new graph PowerShell SDK.

Awesome! Glad the SDK helped.

> How do I add language specific samples? Then I'll add the sample code myself.

As for the language-specific samples, don't worry. We have an automated process where once an example is published in the docs, 6 language-specific samples are ingested into the published docs on the first Tuesday after the doc is live. As an alternative, when you test the request in Graph Explorer, you'll also be able to see the samples in the 6 supported SDKs (including PS SDK) in Graph Explorer. Then when you have these samples, you can add the rest of the code.

As a first step, let me get back to you @ the end of next week with a documented guide.

**Comment by FaithOmbongi** [comment]
Experiencing a bit of delays but still following up on this ask.

**Comment by FaithOmbongi** [comment]
Thank you @svrooij for your patience.
Based on your feedback, we recently published this article [https://learn.microsoft.com/en-us/graph/applications-how-to-add-certificate?view=graph-rest-1.0&tabs=http](https://learn.microsoft.com/en-us/graph/applications-how-to-add-certificate?view=graph-rest-1.0&tabs=http) that guides you on how to use the Update application API to add certificate creds to an app. We hope you find it useful.

**Comment by svrooij** [comment]
I’ve seen the page and this is going to help a lot of users. Understanding that you need to base64 the raw byte is the key for getting this to work.
