### ISSUE TITLE
Delete Device

### ISSUE THREAD

**Issue by takeittothemax** [microsoftgraph/microsoft-graph-docs#19294]
Please allow deleting of devices via application as opposed to forcing user authentication. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3a6b91f-5c3a-d92f-a572-fa47ff846e6b
* Version Independent ID: bcf37011-94d5-0dc3-1cc2-d00da6ab9758
* Content: [Delete device - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-delete.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @spunukol
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @takeittothemax for your suggestion. Unfortunately, this forum is only for documentation-related issues but feature requests are accepted via the [feedback portal](https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80). Please file this request there so other developers can amplify your voice.
