### ISSUE TITLE
Broken Links on Page

### ISSUE THREAD

**Issue by mlibenocg** [microsoftgraph/microsoft-graph-docs#19397]
On the page https://learn.microsoft.com/en-us/graph/api/resources/identitygovernance-task?view=graph-rest-beta, there is a list of Supported Tasks with hyperlinks. The first five hyperlinks are "dead" and return a 404 - Page not found. I assume the remainder of the links in the list are broken, too. I need the content at the first two links for a client project so appreciate prompt attention.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b619747e-a25c-f2c1-3271-94d837ba7af9
* Version Independent ID: 4c5bfd8b-50c2-8ac5-5c7d-7d52c40cf2bf
* Content: [task resource type (lifecycle workflow tasks) - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/identitygovernance-task?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/identitygovernance-task.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/identitygovernance-task.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @AlexFilipin
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @mlibenocg,

thanks for opening this issue. Indeed, all links on that documentation page are broken. While we wait for the article to be fixed, you can find a list of supported tasks [here](https://learn.microsoft.com/en-us/azure/active-directory/governance/lifecycle-workflow-tasks#supported-tasks-preview).

Best,
Jarbas Horst

**Comment by JarbasHorst** [comment]
The "Supported tasks" section has an include that refers to a table outside of the Microsoft Graph repository: https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/lifecycle-workflows-tasks-table.md. The table contains relative links pointing to topics in the Microsoft Azure docs. When the table is loaded in the Microsoft Graph docs all links won't work, because they point to "https://learn.microsoft.com/azure/" instead of "https://learn.microsoft.com/graph/". 

One way to solve this issue, is to replace the relative links with absolute links.

**Comment by FaithOmbongi** [comment]
Thank you @mlibenocg for catching this error and @JarbasHorst is correct. 
I'm looking into this problem and will resolve it soon.

**Comment by mlibenocg** [comment]
Jarbas,

Thanks for pointing out the correct links.

Mike Liben



Client Confidential - OCG Internal
From: Jarbas Horst ***@***.***>
Sent: Monday, November 28, 2022 2:26 AM
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Michael Liben ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [microsoftgraph/microsoft-graph-docs] Broken Links on Page (Issue #19397)

[EXTERNAL] Use caution opening attachments, clicking links, or responding.


The "Supported tasks" section has an include that refers to a table outside of the Microsoft Graph repository: https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/lifecycle-workflows-tasks-table.md<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-docs%2Fblob%2Fmain%2Fincludes%2Flifecycle-workflows-tasks-table.md&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C9210ac0c889b44f4bcd808dad111cc72%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052171624728037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k8TFkUpfJo1iarcss2S40Jn3ndbNlsNOfPoGS8Kwtok%3D&reserved=0>. The table contains relative links pointing to topics in the Microsoft Azure docs. When the table is loaded in the Microsoft Graph docs all links won't work, because they point to "https://learn.microsoft.com/azure/<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fazure%2F&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C9210ac0c889b44f4bcd808dad111cc72%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052171624728037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=H8f8MvovHUJrNlLgFEFutziGgKmsE1E%2Bmu1%2BqtguMlA%3D&reserved=0>" instead of "https://learn.microsoft.com/graph/<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fgraph%2F&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C9210ac0c889b44f4bcd808dad111cc72%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052171624728037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FzzbSlC3MXVr4rw%2FtEupVwVlcLdEhSAwGJLSkpbY5yA%3D&reserved=0>".

One way to solve this issue, is to replace the relative links with absolute links.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fissues%2F19397%23issuecomment-1328652167&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C9210ac0c889b44f4bcd808dad111cc72%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052171624728037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zCsnP8kbpMm7kVn7isBGluRnkfmR0MH3hlK3Ykq1c4g%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO3KH6ULCEBD5HIWV37I7OLWKRNAPANCNFSM6AAAAAASM4IQKU&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C9210ac0c889b44f4bcd808dad111cc72%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052171624728037%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ay5ilsLENBHWMfOmuFEMA333c7R6Ij0JTTwqCAmZ%2BiM%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

DISCLAIMER: The information contained in this message may be confidential and/or subject to legal privilege and is for the use of the intended recipient(s) only. Any unauthorized use, dissemination or copying of the information in this message is strictly prohibited. If you have received this message in error, please notify the sender immediately and delete this message.

**Comment by mlibenocg** [comment]
Faith,

Thanks for the feedback. For the time being, I am leveraging he corrected location described by Jarbas.

Mike Liben



Business Confidential
From: Faith Moraa Ombongi ***@***.***>
Sent: Monday, November 28, 2022 5:56 AM
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Michael Liben ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [microsoftgraph/microsoft-graph-docs] Broken Links on Page (Issue #19397)

[EXTERNAL] Use caution opening attachments, clicking links, or responding.


Thank you @mlibenocg<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmlibenocg&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C3922b9d156c6477fe95a08dad12f2035%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052297602209700%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=roZfsoH27Sr1PtTll6p24tQ%2FhVJ8sWEW9gxd96dsZEI%3D&reserved=0> for catching this error and @JarbasHorst<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJarbasHorst&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C3922b9d156c6477fe95a08dad12f2035%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052297602209700%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mYDMYWnmWTuxckwZdv3%2FP9u7Hjvy8lOVaGVWFAbmRtQ%3D&reserved=0> is correct.
I'm looking into this problem and will resolve it soon.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fissues%2F19397%23issuecomment-1328880635&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C3922b9d156c6477fe95a08dad12f2035%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052297602209700%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qb0Ex9mMPPEe6qA%2FW9Nfi%2F0e8KXWUq38yVBvdtKn5Ws%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO3KH6XBCP5KR34E3S54BFDWKSFTXANCNFSM6AAAAAASM4IQKU&data=05%7C01%7Cmichael.liben%40oxfordcomputergroup.com%7C3922b9d156c6477fe95a08dad12f2035%7C9505d3230e794ceab1d35475ecc368b6%7C0%7C0%7C638052297602209700%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GNyKK3z5zsPH6cRaemgmgP0okHG2kvvR0EBlM7eX024%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

DISCLAIMER: The information contained in this message may be confidential and/or subject to legal privilege and is for the use of the intended recipient(s) only. Any unauthorized use, dissemination or copying of the information in this message is strictly prohibited. If you have received this message in error, please notify the sender immediately and delete this message.
