### ISSUE TITLE
Response code mistake ?

### ISSUE THREAD

**Issue by Avtokar40** [microsoftgraph/microsoft-graph-docs#19390]
[Enter feedback here]

The documentation states that the response code is "202 Accepted", but it actually returns "201 Created"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 255b956c-6f75-2e82-acfa-f8943bfb5614
* Version Independent ID: e0782778-3134-8905-3bce-98a79fef2d51
* Content: [message: reply - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/message-reply.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @abheek-das
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hi @Avtokar40,

I tried the endpoint but got `202 Accepted` as the response code, which is the same as in the docs. This is what the request and response values look like:

![image](https://user-images.githubusercontent.com/26866873/205321661-5f9f12f6-b762-4b96-8e56-6b180b522e2d.png)

Is your feedback related to the first or second example?

Thanks,
Jarbas

**Comment by Avtokar40** [comment]
I would like to clarify which endpoint you are sending the request to. Judging by the screenshot, this is editing /message/id, not creating a reply  /messages/id/reply
Is it because I'm sending an empty request body that's causing the discrepancy?

**Comment by JarbasHorst** [comment]
> I would like to clarify which endpoint you are sending the request to. Judging by the screenshot, this is editing /message/id, not creating a reply /messages/id/reply

I used the following endpoint for this request, which returns a `202 Accepted` as the response code: POST https://graph.microsoft.com/beta/me/messages/{id}/reply

> Is it because I'm sending an empty request body that's causing the discrepancy?

I tried also the scenario where the request body contains an empty JSON object but I also got a `202 Accepted` as the response code.

What endpoint are you using?
