### ISSUE TITLE
Group.ReadWrite missing from the documentation

### ISSUE THREAD

**Issue by figgsoftware** [microsoftgraph/microsoft-graph-docs#1940]
In this article https://stackoverflow.com/users/105518/marc-lafleur-microsoft
Marc Lafleur of Microsoft mentions that there is a permissions scope Group.ReadWrite that does not require admin_consent like Group.ReadWrite.All.
The Group.ReadWrite does not seem to be documented anywhere. Why?
It is really a showstopper in large orgs to require an admin_consent for Office Graph Apps.

**Comment by mlafleur** [comment]
This was a mistake on my part. I was demonstrating how the `.all` convention works and mistakenly using `Group.ReadWrite` as an example. 

There currently isn't a `Group.ReadWrite` scope available. There is an UserVoice for this however: dd a ["My Groups - Read/Write" Permission (that does not require Admin Consent)](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/15969922-add-a-my-groups-read-write-permission-that-do).

**Comment by figgsoftware** [comment]
Thanks for the quick reply, Marc!
That Uservoice is actually posted by me☺ The admin_consent for Groups is really hurting our onboarding of new clients.

Best regards,

Jørgen

**Comment by jamescro** [comment]
Resolving since Marc's answer clarifies that this isn't a documentation issue.
