### ISSUE TITLE
Fra un po' e se ti va di partecipare ad un concerto dei ragazzi che hanno tutti detto che è successo qualcos'altro di voi può prenderne di

### ISSUE THREAD

**Issue by LeoBLMitz** [microsoftgraph/microsoft-graph-docs#19454]

**Comment by FaithOmbongi** [comment]
Hi @LeoBLMitz - Please open the issue against a doc page by scrolling to the bottom of the page and selecting the "Submit feedback for **This page** button". Thank you.
