### ISSUE TITLE
Incorrect search string for C#

### ISSUE THREAD

**Issue by Nisden** [microsoftgraph/microsoft-graph-docs#19490]
The search strings in the C# samples are incorrect.

When using **OR** statements each individual property should be wrapped in quotes and not the full parameter.

**Current & Incorrect:**  
`"\"displayName:OneVideo OR mail:onevideo\""`

**Correct**
`"\"displayName:OneVideo\" OR \"mail:onevideo\""`

See also: https://stackoverflow.com/a/70616247/1020941
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7415c6-cfbb-27a1-109c-78aa85e69cef
* Version Independent ID: dfd0a8f0-b01d-baab-67aa-a64eb39d3224
* Content: [Use the $search query parameter in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/search-query-parameter?tabs=http)
* Content Source: [concepts/search-query-parameter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/search-query-parameter.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Licantrop0** [comment]
The verified syntax is correct, good catch. @FaithOmbongi let's update the documentation.

**Comment by FaithOmbongi** [comment]
Thanks for the confirmation, Luca. I'll forward this issue to the [C# SDK repo](https://github.com/microsoftgraph/msgraph-sdk-dotnet) because the generation of the snippets is automated and any manual updates will be overwritten in the next run anyway.

**Comment by andrueastman** [comment]
Hey @FaithOmbongi,

Looks like the original HTTP sample is the issue here. It should also have the search terms surrounded with double quotes as the document suggests. 

![image](https://user-images.githubusercontent.com/6464005/206148609-32c15ab2-38c6-4a19-93c9-67d81b820b2c.png)

**Comment by FaithOmbongi** [comment]
@andrueastman - Oops, wasn't looking. Raising a PR to fix the doc. Thanks!
