### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by Logintd826** [microsoftgraph/microsoft-graph-docs#19507]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4bfca17-b9c5-785d-3d0b-428842f7c080
* Version Independent ID: e47c10cf-cd07-850e-fdb5-29d0aec8a5bd
* Content: [directoryObject resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/directoryobject?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/directoryobject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/directoryobject.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @Logintd826 - Looks like you may have opened an issue by mistake. I'll close it here.
If you have an issue to raise against the doc, please open another issue and provide a detailed description.
