### ISSUE TITLE
what are permission required for this api?

### ISSUE THREAD

**Issue by StevenVBeek** [microsoftgraph/microsoft-graph-docs#19529]
Please update the docs! It's not correctly working at the moment.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: 1c098039-d2f7-a13e-a7bc-cffc1bed2f05
* Version Independent ID: af38e3e3-a3b2-3fd9-a56b-31f710ac17c1
* Content: [deviceManagementSettings resource type - Microsoft Graph beta](https://learn.microsoft.com/nl-nl/graph/api/resources/intune-deviceconfig-devicemanagementsettings?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-deviceconfig-devicemanagementsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/intune-deviceconfig-devicemanagementsettings.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
This is a complex type.  So the permissions required would the permissions needed for the entity type that you're trying to LIST/GET.  Most likely, the permissions needed are 

DeviceManagementConfiguration.Read.All or
DeviceManagementConfiguration.ReadWrite.All
