### ISSUE TITLE
How to add a group to a review code example

### ISSUE THREAD

**Issue by ctahok** [microsoftgraph/microsoft-graph-docs#19566]
Hi there,

I appreciate the Identity Governance is in beta. But the [article](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.governance/new-mgaccessreview?view=graph-powershell-beta) says "The Azure AD resources include groups...." however nowhere in the documentation, I was able to find how to create an access review for an AAD group. I managed to create a new review via Powershell, API but it has no group assigned. When trying to create a similar one via Azure Portal the Group(s) name is mandatory whereas here it is missing. Can you please give an example of a code to create one with an AAD group or a subset of groups?
Update:
I have posted the code I used [here ](https://learn.microsoft.com/en-us/answers/questions/1123289/azure-access-review-api.html)

Thanks beforehand

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 30aa5604-bed2-4be4-8b8a-343efe93c1da
* Version Independent ID: a1686182-907c-78eb-abd8-095b34cfb547
* Content: [Azure AD access reviews - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/accessreviewsv2-overview?source=recommendations&view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/accessreviewsv2-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/accessreviewsv2-overview.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @jyothig123
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jyothig123** [comment]
+Shubham
Hi Shubham,
Can you help with this API request?

Thanks,
Jyothi Gangadhar

From: ctahok ***@***.***>
Sent: Friday, December 9, 2022 10:46 PM
To: microsoftgraph/microsoft-graph-docs ***@***.***>
Cc: Jyothi Gangadhar ***@***.***>; Mention ***@***.***>
Subject: [microsoftgraph/microsoft-graph-docs] How to add a group to a review code example (Issue #19566)


Hi there,

I appreciate the Identity Governance is in beta. But the article<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Fmicrosoft.graph.identity.governance%2Fnew-mgaccessreview%3Fview%3Dgraph-powershell-beta&data=05%7C01%7Cjgangadhar%40microsoft.com%7C6f551aa92b8b4648f9ea08dada08fa44%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638062029364026318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lmlCgtFZRSQVVRLL5d1ykMjCVMI2lx848foxSxn6gTE%3D&reserved=0> says "The Azure AD resources include groups...." however nowhere in the documentation, I was able to find how to create an access review for an AAD group. I managed to create a new review via Powershell, API but it has no group assigned. When trying to create a similar one via Azure Portal the Group(s) name is mandatory whereas here it is missing. Can you please give an example of a code to create one with an AAD group or a subset of groups?

Thanks beforehand

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 30aa5604-bed2-4be4-8b8a-343efe93c1da
  *   Version Independent ID: a1686182-907c-78eb-abd8-095b34cfb547
  *   Content: Azure AD access reviews - Microsoft Graph v1.0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fresources%2Faccessreviewsv2-overview%3Fsource%3Drecommendations%26view%3Dgraph-rest-1.0&data=05%7C01%7Cjgangadhar%40microsoft.com%7C6f551aa92b8b4648f9ea08dada08fa44%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638062029364026318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j1SIvCP5ugpuaN4ZnFHi%2F5jybRXUdSMkpTNXJf2UHyw%3D&reserved=0>
  *   Content Source: api-reference/v1.0/resources/accessreviewsv2-overview.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fblob%2Fmain%2Fapi-reference%2Fv1.0%2Fresources%2Faccessreviewsv2-overview.md&data=05%7C01%7Cjgangadhar%40microsoft.com%7C6f551aa92b8b4648f9ea08dada08fa44%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638062029364026318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MiLoUVSm7q8EO%2BwxlTVZkguexFZA3YEHKe8LVCth%2FWs%3D&reserved=0>
  *   Product: governance
  *   Technology: microsoft-graph
  *   GitHub Login: @jyothig123<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjyothig123&data=05%7C01%7Cjgangadhar%40microsoft.com%7C6f551aa92b8b4648f9ea08dada08fa44%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638062029364026318%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tgvPFBq%2BVYVcIC7JQmAePda1pTFG1kPxpJmW6Al3QsQ%3D&reserved=0>
  *   Microsoft Alias: MSGraphDocsVteam

**Comment by FaithOmbongi** [comment]
Thank you @ctahok for asking this question.
Please check out [Example 1: Create an access review on a group](https://learn.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&tabs=http#example-1-create-an-access-review-on-a-group) in the Create accessReview topic for an example.

For more patterns, see [Configure the scope of your access review using the Microsoft Graph API](https://learn.microsoft.com/en-us/graph/accessreviews-scope-concept). Let me know if these resources help you.

**Comment by FaithOmbongi** [comment]
Hi @ctahok, I haven't heard back from you, so I assume that my last response was the answer you needed. I'll proceed to close this issue.

In case it's still unresolved, kindly reply.

**Comment by ctahok** [comment]
> Thank you @ctahok for asking this question. Please check out [Example 1: Create an access review on a group](https://learn.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-1.0&tabs=http#example-1-create-an-access-review-on-a-group) in the Create accessReview topic for an example.
> 
> For more patterns, see [Configure the scope of your access review using the Microsoft Graph API](https://learn.microsoft.com/en-us/graph/accessreviews-scope-concept). Let me know if these resources help you.

Thanks a lot, this is good enough.
