### ISSUE TITLE
Does not function as documented

### ISSUE THREAD

**Issue by Charliecoolblue** [microsoftgraph/microsoft-graph-docs#19597]
GET /devices(deviceId='{deviceId}')

Does not work with an id provided by the object

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1b83431a-943d-3f37-b2c3-67061a16cd3c
* Version Independent ID: 14c425d1-40e6-b37e-d327-322933054866
* Content: [Get device - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/device-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-get.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @SanDeo-MSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @Charliecoolblue - {deviceId} in this case is the value of the **deviceId** property. Not value of **id** property. Please confirm that you're using the value of **deviceId** property.

<img width="485" alt="image" src="https://user-images.githubusercontent.com/14026935/207676036-fa182fb2-aee6-4b54-b2aa-2b2f75b35fbe.png">

**Comment by FaithOmbongi** [comment]
Hi @Charliecoolblue - I haven't heard back from you so I assume that using the correct ID helped resolve this issue? I'll close this thread now.
If the issue is still unresolved, please do let me know.
