### ISSUE TITLE
Out of date documentation for New-MgEntitlementManagementAccessPackageAssignmentPolicy

### ISSUE THREAD

**Issue by WayneAASPLLC** [microsoftgraph/microsoft-graph-docs#19602]
direct copy/paste from "Questions =" section for powershell does not work

Error:
New-MgEntitlementManagementAccessPackageAssignmentPolicy : The model is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8adc885a-777d-c3ba-5609-4ffd80d35c62
* Version Independent ID: 394d5d37-978b-0e07-f867-93a2710df0d9
* Content: [Update accessPackageAssignmentPolicy - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&tabs=powershell)
* Content Source: [api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accesspackageassignmentpolicy-update.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by WayneAASPLLC** [comment]
On a side note, it looks like there is only information for duration in days. there should be an ability to do it the following ways:
On date
Number of days
Number of hours
Never

**Comment by WayneAASPLLC** [comment]
both of those involve multiple choice and there wouldn't be localization in my case.

Here is what I am trying to accomplish through the JSON coding:
![image](https://user-images.githubusercontent.com/117128832/207702428-4c50a008-d473-4267-8a52-4200755b4745.png)

**Comment by WayneAASPLLC** [comment]
Below is some example code. I have tired many different things inside of questions, but it always ends up as invalid model errors. The example information doesn't show how to do a single question as short text, and the example information does not work by copy/pasting it. The format below is standard JSON POST testing on Microsoft Graph Explorer beta.
```
{
    "accessPackageId": "",
    "displayName": "Initial Policy",
    "description": "Initial Policy",
    "requestorSettings": {
        "scopeType": "SpecificDirectorySubjects",
        "acceptRequests": true,
        "allowedRequestors": [
            {
                "@odata.type": "#microsoft.graph.groupMembers",
                "isBackup": false,
                "id": "",
                "description": "Authorized requestors"
            }
        ]
    },
    "questions": [
        {
            "@odata.type": "#microsoft.graph.accessPackageQuestion"
        }
    ]
}
```

**Comment by markwahl-msft** [comment]
There are unfortunately some known issues with the PowerShell Graph SDK, impacting data structures containing `@odata.type`.  Take a look at the following payload for creating a new policy.  Note that the character case of the field names in Graph is significant.

```powershell
$params = @{
     AccessPackageId = "f56504d6-db20-4d54-aa0e-8f42243011e7"
     DisplayName = "Users from connected organizations can request"
     Description = "Allow users from configured connected organizations to request and be approved by their sponsors"
     CanExtend = $false
     DurationInDays = 365
     ExpirationDateTime = $null
     RequestorSettings = @{
         ScopeType = "AllExistingConnectedOrganizationSubjects"
         AcceptRequests = $true
         AllowedRequestors = @(
         )
     }
     RequestApprovalSettings = @{
         IsApprovalRequired = $true
         IsApprovalRequiredForExtension = $false
         IsRequestorJustificationRequired = $true
         ApprovalMode = "Serial"
         ApprovalStages = @(
             @{
                 ApprovalStageTimeOutInDays = 14
                 IsApproverJustificationRequired = $true
                 IsEscalationEnabled = $false
                 PrimaryApprovers = @(
                     @{
                         "@odata.type" = "#microsoft.graph.groupMembers"
                         isBackup = $true
                         id = "76a87ba7-9afa-4a8c-a970-b6e6a8efd4bc"
                         description = "group for users from connected organizations which have no external sponsor"
                     }
                     @{
                         "@odata.type" = "#microsoft.graph.externalSponsors"
                         isBackup = $false
                     }
                 )
 }
 )
     }
 Questions = @(
         @{
             IsRequired = $false
             Text = @{
                 DefaultText = "Who is your manager?"
                 LocalizedTexts = @(
                     @{
                         Text = "por qué necesita acceso a este paquete"
                         LanguageCode = "es"
                     }
                 )
             }
             "@odata.type" = "#microsoft.graph.accessPackageTextInputQuestion"
             isSingleLineQuestion = $false
         }
     )
 }
```

**Comment by WayneAASPLLC** [comment]
This is just a copy/paste from the documentation that doesn't work? That is what this was created for. When trying to change the details to what is needed via the screenshots provided. You get a model is invalid error.

**Comment by markwahl-msft** [comment]
The documentation for PSh in the article is unfortunately not correct and results in an error if you try to use it.  The example I pasted above is not the same as what is in the article, I had updated so that it would not give that error.  See also https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1628

**Comment by WayneAASPLLC** [comment]
Ok, I have no P2 license at this time to test this now. I'll need to find out later, but it looks like it's fixed. Thanks!
