### ISSUE TITLE
SubscribedSkus is under the wrong parent in TOC

### ISSUE THREAD

**Issue by ioamnesia** [microsoftgraph/microsoft-graph-docs#19615]
Looks like there was a simple indentation mistake in the toc.yaml that places this under Organizational Contacts instead of its parent Directory Management. This issue makes it VERY difficult to find via the TOC.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 368af49c-31b1-ebb9-68df-5cf4a041d50b
* Version Independent ID: 0ee918a5-296e-99e5-2902-cbb8e73a9dbd
* Content: [subscribedSku resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/subscribedsku?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/subscribedsku.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/subscribedsku.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @SumitParikh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you for catching this error @ioamnesia and my apologies for the mix up. I've raised a PR to move it up a level in the TOC.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/14026935/207692330-12d31e58-b1f6-4893-afef-429e1120e39f.png">
