### ISSUE TITLE
Using odata cast to filter transitiveMembers to groups does not work as documented

### ISSUE THREAD

**Issue by barclayadam** [microsoftgraph/microsoft-graph-docs#19672]
I'm attempting to list all transitive group members but the casting does not appear to work as per documentation and I'm not sure if this is a product or documentation issue. I suspect product based on below:

If I make a `GET` request to `https://graph.microsoft.com/v1.0/groups/f5cddf0b-083b-4677-8a57-928cbb68b912/transitiveMembers/microsoft.graph.user` I get a list of users that are a member of that group.

If I make a `GET` request to `https://graph.microsoft.com/v1.0/groups/f5cddf0b-083b-4677-8a57-928cbb68b912/transitiveMembers/microsoft.graph.group` it fails:

````json
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Invalid search request.",
        "innerError": {
            "date": "2022-12-20T14:40:07",
            "request-id": "2dce0b45-db6a-455f-98e1-bf14d25b2205",
            "client-request-id": "d9bf7274-e1f4-f95c-544f-56222030bc3f"
        }
    }
}
````

Interestingly if I mimic the exact requests made in the documentation with $count=true I get a successful response with no values returned (which is correct).

If I make the same requests with a group that *does* contain child groups then the values are correctly returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37eaad48-9559-ab5c-5b83-338f53fbbc6f
* Version Independent ID: 591556a3-d528-7f19-e03b-3bf5a67bce51
* Content: [List group transitive members - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-transitivemembers.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @barclayadam for raising this issue. IIs it possible that your group of ID `f5cddf0b-083b-4677-8a57-928cbb68b912` is a Microsoft 365 group? These groups can have only users as members (see [here](https://learn.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#:~:text=The%20following%20table%20shows%20the%20types%20of%20members%20that%20can%20be%20added%20to%20either%20security%20groups%20or%20Microsoft%20365%20groups.)), so running your query would give an invalid search result error. Can you confirm whether my assumption is true? Thanks.

**Comment by barclayadam** [comment]
Thank you for your response @FaithOmbongi. You are indeed correct this is a Microsoft 365 group. 

It would be great to include a note on this page regarding this, it is unexpected (from my POV at least) to get an error, particularly when doing a $count query works perfectly. I would not have thought to check the type before seeing that other page you linked, which I had not visited as not had the need to create groups (we are pulling in already existing data)

**Comment by FaithOmbongi** [comment]
This is fair feedback @barclayadam. I'll add a note about the error responses when you query for an unsupported object type.

Unfortunately, the `$count=true` gives you a false positive - while you get a 200 OK, the request technically didn't succeed. I'll share this feedback with the team to reconsider this behavior. cc @Licantrop0

**Comment by barclayadam** [comment]
Thank you @FaithOmbongi for the quick turnaround, nice to see responsive fixes :) 

Can I suggest the documentation includes the code, not just the error message? At least from my end checking against a code and not a message feels less likely to break if error messages are ever changed in the future (my assumption is codes are more resilient to API changes, but that could be wrong), so knowing the code would be useful.

**Comment by FaithOmbongi** [comment]
> Thank you @FaithOmbongi for the quick turnaround, nice to see responsive fixes :)
> 
> Can I suggest the documentation includes the code, not just the error message? At least from my end checking against a code and not a message feels less likely to break if error messages are ever changed in the future (my assumption is codes are more resilient to API changes, but that could be wrong), so knowing the code would be useful.

Consider it done. And yes, we've improved some error messages in recent times so that value may change; I'll document the code.

**Comment by Licantrop0** [comment]
From a semantic standpoint, returning 0 results and not a generic "Request_UnsupportedQuery" error is correct. Also, is what @barclayadam expected in the first place.
Returning an error instead of an empty list just because Microsoft 365 groups don't (currently) support nesting is confusing for our customers. @psaffaie can you please discuss with @rchkodrova and consider a change for this?

**Comment by FaithOmbongi** [comment]
Hi @Licantrop0, I've opened an internal work item so the engineering team can consider changing the API behavior. Work item # 2286605.

I'll close this issue here because it's not doc related.
