### ISSUE TITLE
Getting profile photo by size is available in v1.0 but only documented in beta

### ISSUE THREAD

**Issue by dan-silver** [microsoftgraph/microsoft-graph-docs#1975]
It looks like the section for `HTTP request to get the metadata for a specific photo size` is documented at https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/profilephoto_get but it's missing in the v1.0 page at https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/profilephoto_get.  To test this, try GET `https://graph.microsoft.com/v1.0/me/photos/64X64/$value` and you should see an image returned.

**Comment by lleonard-msft** [comment]
@dan-silver - Just wanted to let you know that this fix has been checked in and should be public in 24 hours.  Once you confirm that's it public, would you mind closing the issue?

**Comment by dan-silver** [comment]
Thanks @lleonard-msft!
