### ISSUE TITLE
Error creating SharePoint list with "currency" column

### ISSUE THREAD

**Issue by wbreza** [microsoftgraph/microsoft-graph-docs#1977]
```
POST https://graph.microsoft.com/v1.0/sites/{site-id}/lists
```

When attempting to create a SharePoint list with a `currency` column it fails with the following error.

```
{
  "error": {
    "code": "invalidRequest",
    "message": "Unable to determine type of provided column definition",
    "innerError": {
      "request-id": "6cd47ee7-a401-4917-9b8e-ef7eec3b78fc",
      "date": "2017-11-15T20:56:50"
    }
  }
}
```

Here is an example JSON reqeust body to reproduce the issue:

```
{
    "displayName": "Products",
    "columns": [{
        "currency": {
            "locale": "en-us"
        },
        "displayName": "Price",
    }]
}
```

I'm following the documentation from the following links:
- [Creating Sharepoint List](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/list_create)
- [Column Definition](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/columnDefinition)
- [Currency Column](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/currencyColumn)

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
