### ISSUE TITLE
Known Issues - EWSAllowList

### ISSUE THREAD

**Issue by MichaelJZurawski** [microsoftgraph/microsoft-graph-docs#19788]
[Enter feedback here]

Known issues:
If your company uses an EWSAllowList you need to add {PostmanRuntime/*} as a UserAgent String.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://learn.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@MichaelJZurawski can you provide more context here? Did you get a specific error?

**Comment by MichaelJZurawski** [comment]
Here is the resolution email from the MSFT Case we had to open.   Error message when using postman line was “Access to OData is disabled.”

Request was blocked due to a Tenant-Configured UserAgent AllowList being set for this Organization;ExceptionDetails=Access Denied Using ShouldPermitAccess. ExceptionMessage=Access to OData is disabled.;

UserAgent
PostmanRuntime/7.29.2

To resolve we just added {PostmanRuntime/*} within our existing UserAgent Strings.


Thank you,
Michael J. Zurawski | EUC Engineering | Collaboration
Health Care Service Corporation (HCSC)
***@***.******@***.***>
M: (847) 366-9388

**Comment by jasonjoh** [comment]
Thanks for the quick response! Were you accessing an Exchange resource like email when you received this error?

**Comment by MichaelJZurawski** [comment]
Yes it was an Exchange Mailbox hosted solely online as we are an O365 shop.



Thank you,
Michael J. Zurawski | EUC Engineering | Collaboration
Health Care Service Corporation (HCSC)
***@***.******@***.***>
M: (847) 366-9388

**Comment by MichaelJZurawski** [comment]
The EWSAllowlist affects all client apps that try to use EWS, but most companies do not enable it.   Here is an example of our current allow list so for this post it’s only relevant to the Postman/xxxx user agent string.



EwsAllowList
------------
{PostmanRuntime*, *Microsoft.Skype.Presence.App/*, *Workday*, Safari/*, AppleWebKit/*, *Chrome/*, *Edge/*, WeveEngine/*, myanalytics/*, SkypeRoomSystem/*, MicrosoftTeamsRoom/*, StickyNotes*, azure-hcsc-adcmobileapp-pilot-sp, *PhishAlarm*, Microsoft.OWS.*, DelveMiddleTier-Azure-DelveWeb/*, Microsoft.Skype.Presence.App/*, Cisco*, *Teams/*, *SchedulingService*, *PhotoImport*, SkypeSpaces/*, *Microsoft Office*, okhttp/*, Planner/*, iPhoneLync/*, iPadLync/*, AndroidLync/*, PowerApps/*, *MAPI*, MicrosoftNinja/*, Outlook-iOS/*, Outlook-Android/*, OC/*, LogicAppsDesigner*, azure-logic-apps*, Rest*, Exchange*, DiscoveryDownloadManager*, O365 Planner Task Service*, ExchangeInternalEwsClient*, Mozilla/*, SharePoint/*}


*, Mozilla/*, SharePoint/*}



Thank you,
Michael J. Zurawski | EUC Engineering | Collaboration
Health Care Service Corporation (HCSC)
***@***.******@***.***>
M: (847) 366-9388

**Comment by lramosvea** [comment]
@jasonjoh any update on this issue? Thanks!
