### ISSUE TITLE
Bad Request while creating Access Reviews with a Access Package assignments Scope

### ISSUE THREAD

**Issue by J-a-k-o-b** [microsoftgraph/microsoft-graph-docs#19810]
Hi,
I'm trying to create an Access Review using the Access Review GraphAI. I want to create a Review for all users that have an specific Access Package assigned. That accesReviewQueryScope is listed on this page a possible Scenario:

> User and service principal access to Entitlement Management access packages.

When I try to implement it as described in Example 7 (https://learn.microsoft.com/en-us/graph/accessreviews-scope-concept#example-7-review-all-assignment-to-entitlement-management-access-packages) I receive an support/compatiblity error (Bad Request 400) and the review is not generated. The error message is:

> "Query /identitityGovernance/entitlementManagement/accessPackageAssignments?$filter=(accessPackageId eq 'f472a75e-47dc-48b3-9e5f-8ebaaa43162d' and assignmentPolicyId eq '7de693c3-9ef5-49c8-abd9-00962f271399') is not supported. Please pass in one of the following queries : /users/{userId}, /groups/{groupId}/owners, /groups/{groupId}/transitiveMembers, /groups/{groupId}/transitiveMembers/microsoft.graph.user/?$count=true&$filter=(userType eq 'Guest') or /roleManagement/directory/roleAssignmentAndEligbilitySchedules?$filter=roleDefinitionId eq '{roleDefinitionId}'"

![image](https://user-images.githubusercontent.com/46894290/211303465-4d16a8e9-06de-4481-8c8f-09de2886b958.png)

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 75138c63-be86-9412-00f7-1907a77577f1
* Version Independent ID: 22b54c30-1082-ae34-96f3-f3ae41f38f9a
* Content: [Configure the scope of your access review using the Microsoft Graph API - Microsoft Graph](https://learn.microsoft.com/en-us/graph/accessreviews-scope-concept)
* Content Source: [concepts/accessreviews-scope-concept.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/accessreviews-scope-concept.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @jyothig123
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @J-a-k-o-b for raising this issue. I've escalated it internally for investigation.

**Comment by FaithOmbongi** [comment]
Hi @J-a-k-o-b, can you add the **catalogId** to the scope query and confirm whether the query now works? See the sample

```
"scope": {
        "@odata.type": "#microsoft.graph.accessReviewQueryScope",
        "query": "/beta/identityGovernance/entitlementManagement/accessPackageAssignments?$filter=(accessPackageId eq '09d48cb7-0d2f-4da5-92ff-490339ef1f09' and assignmentPolicyId eq '96d96f17-81c3-4b62-95f1-c3183eee7f3a' and catalogId eq '4e9d000c-2a3e-416a-aa7c-c0407b3c65ef')",
        "queryType": "MicrosoftGraph",
        "queryRoot": null
    },
```

**Comment by J-a-k-o-b** [comment]
Hi @FaithOmbongi,
unfortunately, i get the same error including the catalogId:
![image](https://user-images.githubusercontent.com/46894290/212269975-281e5e71-ab93-4449-82b9-345af089f3d2.png)

**Comment by FaithOmbongi** [comment]
Hi @J-a-k-o-b : Can you capture the request ID as well? That will help with investigation.

**Comment by J-a-k-o-b** [comment]
Hi @FaithOmbongi, i've changed the screenshot. Now the request-id is included.

**Comment by leherpel** [comment]
Hey @J-a-k-o-b thanks for reporting this, I'm an engineer on the Access Reviews team. I wasn't able to repro this, would you mind sharing your full POST body here and a correlation Id? It would be this header value: 
![image](https://user-images.githubusercontent.com/81385520/213253115-e01c897c-b5b0-440b-84d5-717d1a104726.png)

**Comment by J-a-k-o-b** [comment]
Hi @leherpel,
sure, here is the request body:
`{
    "scope": {
        "@odata.type": "#microsoft.graph.accessReviewQueryScope",
        "queryType": "MicrosoftGraph",
        "query": "/beta/identitityGovernance/entitlementManagement/accessPackageAssignments?$filter=(accessPackageId eq 'a840b8b5-d387-401e-b365-76964c7f5ad3' and assignmentPolicyId eq '51373e5b-8735-4dd0-9dbd-1a82c067982d' and catalogId eq '2a736afb-de54-4816-9096-858992ae2ca5')",
        "queryRoot": null
    },
    "displayName": "Pre-Migration Review",
    "reviewers": [
        {
            "query": "/users/09960a29-cb93-4450-b9a0-a7a2d8e09594",
            "queryType": "MicrosoftGraph"
        }
    ],
    "descriptionForAdmins": "Created in preparation of the IAM transferation",
    "settings": {
        "decisionHistoriesForReviewersEnabled": false,
        "recommendationsEnabled": true,
        "justificationRequiredOnApproval": false,
        "mailNotificationsEnabled": true,
        "recommendationLookBackDuration": "P30D",
        "instanceDurationInDays": 14,
        "recurrence": {
            "range": {
                "startDate": "2023-01-09",
                "type": "noEnd"
            },
            "pattern": null
        },
        "defaultDecisionEnabled": false,
        "applyActions": [
            {
                "@odata.type": "#microsoft.graph.removeAccessApplyAction"
            }
        ],
        "autoApplyDecisionsEnabled": true,
        "defaultDecision": "None",
        "reminderNotificationsEnabled": true,
        "recommendationInsightSettings": [
            {
                "recommendationLookBackDuration": "P30D",
                "@odata.type": "#microsoft.graph.userLastSignInRecommendationInsightSetting",
                "signInScope": "tenant"
            }
        ]
    }
}`
 and the id's:

 `        "innerError": {
            "date": "2023-01-19T09:42:37",
            "request-id": "b87ca005-de3f-4bbe-b566-8e52cbfcb7d1",
            "client-request-id": "14e6ba83-6b01-818d-9908-5fba9db14252"
        }`

**Comment by leherpel** [comment]
Thanks @J-a-k-o-b I see the issue. In your scope "identityGovernance" was spelled wrong. Could you try replacing your scope with this:
`    "scope": {
        "@odata.type": "#microsoft.graph.accessReviewQueryScope",
        "queryType": "MicrosoftGraph",
        "query": "/beta/identityGovernance/entitlementManagement/accessPackageAssignments?$filter=(accessPackageId eq 'a840b8b5-d387-401e-b365-76964c7f5ad3' and assignmentPolicyId eq '51373e5b-8735-4dd0-9dbd-1a82c067982d' and catalogId eq '2a736afb-de54-4816-9096-858992ae2ca5')",
        "queryRoot": null
    },
`

**Comment by J-a-k-o-b** [comment]
Hi @leherpel,
you're right about that. The typo was the main issue all the time :)
But I still need to add the catalogId to the scope, right? The documentation should be updated to reflect that.

**Comment by FaithOmbongi** [comment]
LO! Glad the subsequent issue was because of a typo :) Thank you so much @leherpel for investigating this issue.

@J-a-k-o-b - yes, the **catalogId** is required. I've raised a PR to document it.

**Comment by leherpel** [comment]
Thank you @FaithOmbongi and @J-a-k-o-b, glad we could get it resolved!
