### ISSUE TITLE
Unpaid Break (minutes) Missing from - List Shift Response

### ISSUE THREAD

**Issue by Sm62dev** [microsoftgraph/microsoft-graph-docs#19811]
[Enter feedback here]
Please include: "Unpaid Break (minutes)" into the SHIFT response. We are currently facing various issues because of this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1b8d81-3af1-4f36-e844-304e3840ab06
* Version Independent ID: 3f85085c-b7ee-b573-79a1-b954dfcf10ff
* Content: [List shifts - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/schedule-list-shifts?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/schedule-list-shifts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/schedule-list-shifts.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Sm62dev** [comment]
Thanks a lot for responding, we are using Shifts to calculate payroll hours for Clients, and it would be helpful if that field is included in the API.

Otherwise, we must use "Activities" to log unpaid breaks.

Kind Regards
Simeon
________________________________

**Comment by Meghana-MSFT** [comment]
@Sm62dev - Engineering team has advised not to use Shifts as a workforce management system itself to trigger payroll.

**Comment by Sm62dev** [comment]
Hey thanks for your response, we are already using shifts data for WFM and payroll.

 Just to clarify, you will not be adding "unpaid breaks" to the API in the foreseeable future?

Kind Regards
Simeon
________________________________

**Comment by Meghana-MSFT** [comment]
@Sm62dev - Yes, "unpaid breaks" won't be added into the SHIFT response.

**Comment by Sm62dev** [comment]
[Crying face with solid fill with solid fill]
