### ISSUE TITLE
createdBy is not required

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1987]
**Issue:** 
For this sentence:

> For each mention in the mentions property, you must specify the mentioned and createdBy properties.

I think it is wrong.
I tested. When I only provide `mentioned`, but no `createdBy`, for the user who got the mail, `isMentioned` is still true.

Personally I feel it makes sense, createdBy is always be sender.

**Article:**
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_post_messages#request-2

**Comment by ArunMSFT** [comment]
@angelgolfer-ms - Looks like @Hongbo-Miao has some feedback on the docs here i.e. the createdBy even though optional seems to be mentioned as a required field. Please take a look when you get a chance.

**Comment by Hongbo-Miao** [comment]
Add another feedback

"mentioned":{
  "name":"Dana Swope",  // <- name is also optional
  "address":"danas@contoso.onmicrosoft.com"
}
