### ISSUE TITLE
Instructions for PATCH oAuth2PermissionGrant Replace the Permissions

### ISSUE THREAD

**Issue by influential-eliot** [microsoftgraph/microsoft-graph-docs#19974]
The instructions on this page actually work to replace all existing permissions when run for a servicePrinciple.

In reading the page one would assume that the PATCH would *add* permissions to a given service principle.

Have tested this by trying to add multiple permissions to the 'Graph Explorer' Enterprise App on my tenant. The PATCH call is successful, but each subsequent call wipes out previously assigned permissions.

So if you wanted to (for example, a bad example) add ALL delegated permissions to an app, then you would never be able to affect this using the API. Because there's a maximum length for the "scope" value, and if you send multiple sets to exhaust all, you'll just end up with the last set of permissions that you sent.

I would also raise this as an issue with Graph, if I knew how, but I don't ... so I'm sure you lovely folks know how to put this under the right microsopes. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27575308-a93a-127b-9286-51911efb7ac0
* Version Independent ID: 68bf43b6-3303-320d-6f01-e215374fd4b3
* Content: [Update an oAuth2PermissionGrant - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/oauth2permissiongrant-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/oauth2permissiongrant-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/oauth2permissiongrant-update.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @influential-eliot for your feedback.

> In reading the page one would assume that the PATCH would add permissions to a given service principle.
> 
> Have tested this by trying to add multiple permissions to the 'Graph Explorer' Enterprise App on my tenant. The PATCH call is successful, but each subsequent call wipes out previously assigned permissions.

Yes, this API overwrites the existing scopes. To retain the existing scopes and add (append) new scopes, you must specify both existing and new scopes in the request. I'll make sure the doc explicitly calls this out.

> So if you wanted to (for example, a bad example) add ALL delegated permissions to an app, then you would never be able to affect this using the API. Because there's a maximum length for the "scope" value, and if you send multiple sets to exhaust all, you'll just end up with the last set of permissions that you sent.

Good observation and yes, you're right. 

First: As I've mentioned above, you must send the full set of scopes you want to grant to the app.

As for the 3850 max. character length, I can say that's the intent. Your app should serve a specific business scenario. The average length of permission is 26 characters. To reach the limit, the scope parameter would have around 102 permissions. I think that's a very overprivileged app, the possibility of having unused permissions is high, and the app can be considered at risk. Even when working with Graph Explorer for testing, you may never need 102 permissions.

I hope this answer helps.

**Comment by influential-eliot** [comment]
Thanks, @FaithOmbongi, all good to know.

I think some kind rewording might help folks understand the literature a bit more, but yeah, understood. Thanks again. 👍
