### ISSUE TITLE
The draft created by createReplyAll has wrong recipients

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#1999]
**UPDATE**: It seems happens to all personal accounts.

___

I have an account. When I registered this account, I typed the capital letter `J`. Jack@outlook.com

For example, Rose sent a mail to Jack.

When I use Jack's account to reply Rose's mail by

```
POST /me/messages/{messageId}/createReplyAll
```

For the draft created, the correct draft should be
```
From: Jack
To: Rose
```
But for this account, since the address has capital letter, the draft created is always
```
From: Jack
To: Rose, Jack
```
which is wrong.

This issue only happens if your mail address has capital letter when you register your account.

I think somewhere in our server, it tries to compare `Jack@outlook.com` and `jack@outlook.com`, and think they are different person.

**Comment by ArunMSFT** [comment]
Thanks for reporting, we'll look into the issue.

**Comment by Hongbo-Miao** [comment]
@ArunMSFT I got another case. Seems like it happens to all personal mail. It does not matter whether it is capital letter.

**Comment by Hongbo-Miao** [comment]
Thanks, I will close this once I see the update.

**Comment by Hongbo-Miao** [comment]
Close this since the issue has been fixed, thanks!
