### ISSUE TITLE
/joinedGroups endpoint returns 500 error

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-docs#20]
If you try to call the `/v1.0/me/joinedGroups` endpoint you get a 500 Internal Server Error. Given that this endpoint is included in the `/v1.0/me` metadata you would expect it to work. If it's a known issue it should be listed as known issue in the documentation including the right way to retrieve user's groups.

**Comment by sumurthy** [comment]
@VenkatAyyadevara-MSFT @rohitag1

**Comment by martellaj** [comment]
@waldekmastykarz, can you tell me where you see /joinedGroups as part of the /v1.0/me metadata? I think `/v1.0/me/memberOf`is what you're looking for.

**Comment by waldekmastykarz** [comment]
It's listed in the metadata if you request `/v1.0/me` with the `Accept: application/json;odata.metadata=full` header

**Comment by martellaj** [comment]
I passed this along to the dev team and will let you know when I hear something. Thanks very much for the feedback!

**Comment by dkershaw10** [comment]
We filed an internal bug about /joinedGroups being visible in the full metadata response on /v1.0

**Comment by Lauragra** [comment]
It looks like we can close this issue. Feel free to reopen if you need anything else. Thanks.
