### ISSUE TITLE
Issue creating Device via the Graph API when following documentation

### ISSUE THREAD

**Issue by whgibbo** [microsoftgraph/microsoft-graph-docs#20019]
As mentioned on https://github.com/microsoftgraph/microsoft-graph-docs/issues/19992 this example does not work.

When invoking it returns the following error:
```
   "code": "Request_BadRequest",
    "message": "Cannot convert the literal 'base64Y3YxN2E1MWFlYw==' to the expected type 'Edm.Binary'.",
```

Seems like the documentation is wrong or I'm following incorrectly.
Any thoughts on this ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72f83337-e16d-a8a2-1de0-c8be4dc5cc80
* Version Independent ID: 72b6e873-460a-5c56-6851-eca8f679038a
* Content: [Create device - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/device-post-devices?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-post-devices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/device-post-devices.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @spunukol
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @whgibbo for raising this issue.
The **key** value in the documentation is just a sample and has been truncated. Please use your own key instead for this operation.

**Comment by whgibbo** [comment]
> Thank you @whgibbo for raising this issue. The **key** value in the documentation is just a sample and has been truncated. Please use your own key instead for this operation.

@FaithOmbongi   Sorry can you when you mention **key**   you are referring to 
```
"alternativeSecurityIds":
  [
    {
      "type":2,
      "key":"base64Y3YxN2E1MWFlYw=="
    }
  ],
```

Can you please explain where this key is obtained from.

**Comment by FaithOmbongi** [comment]
Hi @whgibbo - Yes, by key, I mean the **key** property that's part of the **alternativeSecurityIds** object.

> Can you please explain where this key is obtained from or how one is created?

Unfortunately, I'm unable to advise where to get the key from. Can you post this question to [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/241/microsoft-graph-directory-management-api)? This forum is for documentation issues only but functionality inquiries are answered at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/241/microsoft-graph-directory-management-api). There's a team of engineers, MVPs, and other developers on hand to answer functionality questions.

**Comment by whgibbo** [comment]
@FaithOmbongi  Sure I can post there.. But surely the documentation should be updated to the reflect this regardless.

**Comment by whgibbo** [comment]
https://learn.microsoft.com/en-us/answers/questions/1164902/issue-creating-a-device-using-graph-api
