### ISSUE TITLE
Link needs to be updated

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#20056]
Folks, "Filter using lambda operators" link should be updated to its new location (https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http#filter-using-lambda-operators). From:

[Filter using lambda operators](https://learn.microsoft.com/en-us/graph/query-parameters#filter-using-lambda-operators)

to

[Filter using lambda operators](https://learn.microsoft.com/en-us/graph/filter-query-parameter?tabs=http#filter-using-lambda-operators)

I'd PR it myself, but those tables in the article get me nervous :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36cbb5db-1ff4-a7b9-819a-4efb704007ce
* Version Independent ID: 7e6f3bbd-f364-0ff8-2e14-977860bd7ff9
* Content: [Advanced query capabilities on Azure AD directory objects - Microsoft Graph](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http)
* Content Source: [concepts/aad-advanced-queries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/aad-advanced-queries.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @michevnew for catching the error and the laugh 😀. I've raised a PR to resolve the broken anchor link.
