### ISSUE TITLE
No limitations listed

### ISSUE THREAD

**Issue by bernatagulloesbrina** [microsoftgraph/microsoft-graph-docs#20053]
this page should list the number of parallel calls allowed 
from my testing it looks like 200 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List group members - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @bernatagulloesbrina - Can you clarify what you mean by "parallel calls"? Thanks.

**Comment by bernatagulloesbrina** [comment]
I'm using it in a foreach box of Azure data factory, and there you can
specify how many parallel executions can be worth the same call but for
different groups.

I see that maybe the issue is with the lookup value task of Azure data
factory that only retrieves 100 rows

Regards

**Comment by FaithOmbongi** [comment]
OK, I hope I've understood you well this time.

Yes, the [List group members](https://learn.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http) API returns a default page size of 100 records. Using `$top`, you can increase the page size to 999 records.

When running multiple instances of the API concurrently, you are now working against [throttling limits](https://learn.microsoft.com/en-us/graph/throttling-limits?context=graph%2Fapi%2F1.0&view=graph-rest-1.0). I think that's what you meant in your initial post?  For details about throttling limits for each API, please refer to the [throttling limits page](https://learn.microsoft.com/en-us/graph/throttling-limits?context=graph%2Fapi%2F1.0&view=graph-rest-1.0).
