### ISSUE TITLE
Get Historical Status with Graph API

### ISSUE THREAD

**Issue by dferraiolo4** [microsoftgraph/microsoft-graph-docs#20055]
From the article it is not clear if the following statment from the O365 Service Communication API also applies to  Microsoft Graph: "Get Historical Status: Get a historical view of service incidents." Is this possible for 30 day history as per the Admin Center? Is it also possible to receive the historical view of reported issues by the customer or only from SH Incidents raised by Microsoft? thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22646fa2-d7d2-32d9-7fe6-ce9cd9ca5ecc
* Version Independent ID: 35c1263b-6b0b-eceb-7976-effec5f57464
* Content: [Access service health and communications in Microsoft Graph - Microsoft Graph](https://learn.microsoft.com/en-us/graph/service-communications-concept-overview)
* Content Source: [concepts/service-communications-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/service-communications-concept-overview.md)
* Product: **service-communications**
* Technology: **microsoft-graph**
* GitHub Login: @payiAzure
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by payiAzure** [comment]
`Is this possible for 30 day history as per the Admin Center?`
Yes, you could use $filter query to get data within the time window specified, this is also how Admin Center call MSGraph service communications API to get historical data. For example: /serviceAnnouncement/healthOverviews?$expand=issues($filter=(isResolved+eq+false)+or+endDateTime+eq+null+or+(lastModifiedDateTime+gt+2023-01-06T17%3a12%3a30.6568739Z))

With out using any $filter in the url, the API returns all service incidents including historical and current.

**Comment by payiAzure** [comment]
`Is it also possible to receive the historical view of reported issues by the customer or only from SH Incidents raised by Microsoft?`
Yes. you could use the property `origin` in entity `serviceHealthIssue` to filter the issues that raised by customers or Microsoft.
[serviceHealthIssue](https://learn.microsoft.com/en-us/graph/api/resources/servicehealthissue?view=graph-rest-1.0)

**Comment by dferraiolo4** [comment]
@payiAzure Last question: can you confirm that without any filter the API returns all incidents also raised by customers and with history also older than 30days? Thank you

**Comment by dferraiolo4** [comment]
Sorry forgot to ask what’s the max time period back in past that the api can return (history of incidents raised by customer and/or Microsoft)thanks a lot

**Comment by payiAzure** [comment]
@dferraiolo4 , for both your questions above, without specifying any filter in the request url, the incidents returned in the API include both customer raised and Microsoft raised.

Without specifying time span filter in the API, the API returns all active incidents; And closed incidents (IsResolved = true) that are closed within 180 days and are last updated within 1 year.

**Comment by lramosvea** [comment]
Closing as questions seem to be answered. Please feel to reopen otherwise. Thanks.
