### ISSUE TITLE
Missing documentation for ScopeId and ScopeType parameters (azurerbac/azureresources)

### ISSUE THREAD

**Issue by Ellestad1995** [microsoftgraph/microsoft-graph-docs#20060]
The documentation states to use the filter properties `scopeId` and `scopeType` to be able to use the api.
But there is missing on what those properties can be.

For AzureAD roles it says `scopeId eq '/' and scopeType eq 'DirectoryRole'`

But what should it be for **AzureResources**?

I have tried different variants but ends up with the error message:
```
"code": "UnknownError",
 "message": "{\"errorCode\":\"MissingProvider\",\"message\":\"The provider is missing.\",\"instanceAnnotations\":[]}"
```

I've tried variants of scopeType = azurerbac, azureresources, azrbac
 
```
https://graph.microsoft.com/v1.0/policies/roleManagementPolicies?$filter=scopeId eq '/providers/Microsoft.Management/managementGroups/<mggroup>' and scopeType eq 'azurerbac'

https://graph.microsoft.com/v1.0/policies/roleManagementPolicies?$filter=scopeId eq '/subscriptions/<subid>' and scopeType eq 'azurerbac'
```

There's another mention of a related issue from a year ago he: https://github.com/microsoftgraph/microsoft-graph-docs/issues/15910

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 264e0cf2-1b05-4803-7894-b8313b3fe19f
* Version Independent ID: ee257771-c240-89fe-cd3f-c680fca91ab5
* Content: [List roleManagementPolicies - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/policyroot-list-rolemanagementpolicies?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/policyroot-list-rolemanagementpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/policyroot-list-rolemanagementpolicies.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @rkarim-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Ellestad1995 for asking this question.

This set of Microsoft Graph API relates to PIM for Azure AD roles. PIM for Azure resources isn't manageable through Microsoft Graph. Instead, use this set of APIs: https://learn.microsoft.com/en-us/rest/api/authorization/privileged-role-eligibility-rest-sample

See the purple note on the Overview page. https://learn.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagementv3-overview?view=graph-rest-1.0
