### ISSUE TITLE
List messages in a chat API docs specify incorrect properties for Optional query parameters

### ISSUE THREAD

**Issue by vtyagunov** [microsoftgraph/microsoft-graph-docs#20146]
1. A `$filter` query parameter with the `createdDateTime` property **only** supports `lt` operator, while docs saying that `le` is the only operator supported.
2. A `$filter` query parameter with the `lastModifiedDateTime` property **only** supports `lt` and `gt` operators, while docs saying that only `ge` and `le` are supported.

_Query example 1:_ `https://graph.microsoft.com/beta/chats/{chat-id}/messages?$orderby=createdDateTime+desc&$filter=createdDateTime+le+2023-01-15T17:16:32.057Z`
Result: 
```
{
    "error": {
        "code": "BadRequest",
        "message": "The entity property 'createdDateTime' and operationKind 'LessThanOrEqual' is not allowed in $filter query.",
        "innerError": {
            "date": "{date}",
            "request-id": "{request-id}",
            "client-request-id": "{client-request-id}"
        }
    }
}
```
_Query example 2_: `https://graph.microsoft.com/beta/chats/{chat-id}/messages?$orderby=lastModifiedDateTime+desc&$filter=lastModifiedDateTime+le+2023-01-15T17:16:32.057Z`
Result: 
```
{
    "error": {
        "code": "BadRequest",
        "message": "The entity property 'lastModifiedDateTime' and operationKind 'LessThanOrEqual' is not allowed in $filter query.",
        "innerError": {
            "date": "{date}",
            "request-id": "{request-id}",
            "client-request-id": "{client-request-id}"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 548a7932-274e-ce6c-aed5-e35206f7894a
* Version Independent ID: 02c653f9-fde9-758e-9bb7-a573f88cbbe8
* Content: [List messages in a chat - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chat-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chat-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by evanypark** [comment]
Document contained incorrect information. Supported operators for $filter clause are 'gt' and 'lt' for lastModifiedDateTime and 'lt' for createDateTime. Change to the documentation has been updated to show correct information.

https://learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-1.0&tabs=http
https://learn.microsoft.com/en-us/graph/api/chat-list-messages?view=graph-rest-beta&tabs=http

**Comment by vtyagunov** [comment]
@evanypark @RamjotSingh Thank you guys!
