### ISSUE TITLE
Getting "Insufficient memory" error message from Graph API. "https://graph.microsoft.com/beta/me/calendarView" API is failing over 50% times.

### ISSUE THREAD

**Issue by joechoi-git** [microsoftgraph/microsoft-graph-docs#2017]
Starting today, 12/1/2017, we are seeing a lot of failures from "https://graph.microsoft.com/beta/me/calendarView" API endpoint.
MS documentation is at https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_list_calendarview

It's been failing at a rate of 50%-90% throughout the day.

Please investigate this matter.

Sample request and response below,
 
Request
https://graph.microsoft.com/beta/me/calendarView?startDateTime=2017-12-01T17:20:13.000Z&endDateTime=2017-12-02T03:20:13.000Z&$top=100&$count=true
 
Response
handleGraphError { statusCode: 500,
  code: 'ErrorInternalServerError',
  message: 'Insufficient memory within specified address space range to continue the execution of the program.',
  requestId: 'a8e6c932-569b-4fa0-8d50-637cddac7121',
  date: 2017-12-01T22:32:29.000Z,
  body: 
   { code: 'ErrorInternalServerError',
     message: 'Insufficient memory within specified address space range to continue the execution of the program.',
     innerError: 
      { 'request-id': 'a8e6c932-569b-4fa0-8d50-637cddac7121',
        date: '2017-12-01T17:32:29' } } }

**Comment by JuForan** [comment]
Hi, we have fixed this issue, and it's rolling out now (currently at ~25% of servers).

**Comment by JuForan** [comment]
@ElizabethSamuel-MSFT can you please close this issue?
