### ISSUE TITLE
Application Permission Type

### ISSUE THREAD

**Issue by tieje** [microsoftgraph/microsoft-graph-docs#20180]
When can we expect the Application Permission Type to be supported by Graph API?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54133b45-7905-d48e-61aa-89bcbc3fb8f4
* Version Independent ID: f72ab940-76f9-996f-717c-6f748046170e
* Content: [List methods - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/authentication-list-methods.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @tieje, application permissions aren't required for acting on *self* through the `/me/authentication/methods` endpoint - because that's a delegated-only scenario. But they are supported for acting on users through the `/users/{id | userPrincipalName}/authentication/methods` endpoint. See [Permissions acting on other users](https://learn.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&tabs=csharp#permissions-acting-on-other-users) in the doc.

**Comment by tieje** [comment]
> Hi @tieje, application permissions aren't required for acting on _self_ through the `/me/authentication/methods` endpoint - because that's a delegated-only scenario. But they are supported for acting on users through the `/users/{id | userPrincipalName}/authentication/methods` endpoint. See [Permissions acting on other users](https://learn.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&tabs=csharp#permissions-acting-on-other-users) in the doc.

Sorry, I did not read the documentation correctly. It clearly says it there. Sorry.

**Comment by FaithOmbongi** [comment]
> > Hi @tieje, application permissions aren't required for acting on _self_ through the `/me/authentication/methods` endpoint - because that's a delegated-only scenario. But they are supported for acting on users through the `/users/{id | userPrincipalName}/authentication/methods` endpoint. See [Permissions acting on other users](https://learn.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&tabs=csharp#permissions-acting-on-other-users) in the doc.
> 
> Sorry, I did not read the documentation correctly. It clearly says it there. Sorry.

No worries @tieje. I'm here to be of service to you.
