### ISSUE TITLE
Getting system lists from SharePoint

### ISSUE THREAD

**Issue by remyblok** [microsoftgraph/microsoft-graph-docs#2020]
Issue: 
https://stackoverflow.com/questions/47562127/can-no-longer-find-sharepoint-site-assets-list-via-graph-api
The documentation is not clear on getting system lists from SharePoint. 
This can apperantly by accomplished by explicitely getting the System-facet,. This facet itself is documented but not it's use. Since I ran into this issue myself last week, I think it is a good thing to document.

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/list_list

**Comment by dmahugh** [comment]
Good suggestion, we've added this to our internal backlog for documentation updates. Thanks!

**Comment by jantman** [comment]
For anyone else who happens by this issue, the StackOverflow question has [an answer](https://stackoverflow.com/a/47563009/211734) that explains how to get the system lists:



By default both the `lists` and `drives` enumerations attempt to hide system objects, but unfortunately doing so in SharePoint is non-trivial. As a result some system lists were still coming through until recently when we made sure they didn't.

You can still see them, but you'll need to explicitly ask for them by requesting the `system` facet.

```
https://graph.microsoft.com/v1.0/sites/{siteid}/lists?select=weburl,system
https://graph.microsoft.com/v1.0/sites/{siteid}/drives?select=weburl,system
```
