### ISSUE TITLE
Help on how to assign the directory role to restore the users

### ISSUE THREAD

**Issue by nukala29** [microsoftgraph/microsoft-graph-docs#20220]
[Enter feedback here]
The customer is using the service principal to restore the users
In this case, he tries to restore the user who is Global Administrator or a user administrator
He is assigned the application type permission user.read.write.all  
But to delete the user the application needs the directory role like Global administrator or the user administrator I explain to the customer this by the design of the graph API  and redirect them to the below URL but he wants to have that documented in his doc to share with their customers because the below doc only talks about the user, not the application.
I try to explain to him that if the user needs that role on delegated flow then the application needs that role to do the action but as I said he needs to be documented on this page. 
https://learn.microsoft.com/en-us/azure/active-directory/roles/permissions-reference
Let me know if you have any questions 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40e760d3-a032-5214-1fb2-e8c811d48a57
* Version Independent ID: 2f86af0c-8ed0-16f1-674c-91c6ebfb045d
* Content: [Restore deleted item (directory object) - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/directory-deleteditems-restore.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @nukala29 for raising this issue.

- For a signed-in user to restore a deleted user who has admin privileges, the app must be granted the _User.ReadWrite.All_ permission on behalf of the calling user and the user must have qualifying roles indicated in [Who can update sensitive attributes?](https://learn.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0#who-can-update-sensitive-attributes).
- For an app-only to restore a deleted user who has admin privileges, Microsoft Graph permissions like _User.ReadWrite.All_ don't work. The app needs to be assigned the qualifying roles indicated in [Who can update sensitive attributes?](https://learn.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0#who-can-update-sensitive-attributes) instead.

I hope this is the info that the customer requires to be documented? I'll raise a PR to document it.

**Comment by nukala29** [comment]
FaithOmbongi  below link didn't answer the customer question.
He is looking for this statement on restore the delete user. 
It does not make sense that you need more permissions to restore a user from recycle bin than to create a user.   I believe that is why we mentioned that we will need documentation in that case as customers will question it.
 
Since it is not a bug and stated “as designed” please point us to the URL where in the docs it explains that this extra permission is needed when recovering a user from recycle bin.  If that URL / Page does not exist the request is that the API info is updated to include this so we can pass along to our customers.

this("For an app-only to restore a deleted user who has admin privileges, Microsoft Graph permissions like User.ReadWrite.All don't work") statement looks like contradicted to me because as per the design of the graph the app needs to have that permissions and the necessary directory role to call the graph Api.
As I mentioned with the normal users without the any admin privileged role when you add the permission to the application work but when you try to restore the admin privileged users then app need that privileged role  to do the same action.
The customer is looking to document this on this doc so that they can pass to their customer.

**Comment by FaithOmbongi** [comment]
Hi @nukala29 

> It does not make sense that you need more permissions to restore a user from recycle bin than to create a user. I believe that is why we mentioned that we will need documentation in that case as customers will question it.

For clarity, restoring a regular user who doesn't have administrator privileges requires only _User.ReadWrite.All_. It's restoring users with privileged administrator roles that require more control - not just anyone or any app should do it.

Also, creating a user may require _User.ReadWrite.All_, but [granting administrator privileges to that user requires higher privileged permissions like RoleManagement.ReadWrite.Directory](https://learn.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&tabs=http).

> Since it is not a bug and stated “as designed” please point us to the URL where in the docs it explains that this extra permission is needed when recovering a user from recycle bin. If that URL / Page does not exist the request is that the API info is updated to include this so we can pass along to our customers.

Yep, sure. See the updated article here [Restore deleted directoryObjects: for users](https://learn.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0&tabs=http#for-users)

**Comment by nukala29** [comment]
@FaithOmbongi Thank you for the document
