### ISSUE TITLE
Hyperlink issue because id="search" is both attached to the section and the search button

### ISSUE THREAD

**Issue by khalyomede** [microsoftgraph/microsoft-graph-docs#2026]
Issue: 
In the documentation "Use query parameters to customize responses", try to click on the `$search` hyperlink from the parameter table. You will notice it will not link to the related paragraph, but to the search button. This is because both the `<h2>` tag of the `$search` section and the search button have the same `id` HTML attribute.

Article:
[https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters](https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters)

**Comment by Lauragra** [comment]
Hi, thanks for pointing this out. This is a known issue with conflicting element names on the page. We're unable to rename the search button, so we'll need to update the content to remove the conflict. I'll update you when the fix is published. Thanks!

**Comment by Lauragra** [comment]
This issue is fixed on the site now. Thanks again!
