### ISSUE TITLE
Adding max value information for $top optionals OData Query Parameters 

### ISSUE THREAD

**Issue by khalyomede** [microsoftgraph/microsoft-graph-docs#2028]
Issue: 
The `$top` OData optional Query Parameter max value is not mentionned. 

Article:
[https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters#top](https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters#top)

**Comment by baywet** [comment]
Thank you for the feedback and sorry it took so long to address it.
PR #5448 is being reviewed and it addresses the issue.
