### ISSUE TITLE
Missing content in underlying fields of authentication resource type

### ISSUE THREAD

**Issue by joetechin** [microsoftgraph/microsoft-graph-docs#20287]
Hi,

This property exists for users retrieved using Get-MgUser and underlying fields can be found but its content cannot be shown using e.g. the following:
$user = get-mguser -userid $userid -property Authentication
Regardless of which version of the API used.

Examples of intended use? Not in use yet? Changelog?

Sincerely,
Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf36053-15b8-175a-38ea-7859940bfed1
* Version Independent ID: a3b8b007-78b0-d083-4d44-321bf3bf73f4
* Content: [authentication resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/authentication?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/authentication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/authentication.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @joetechin for raising this issue.

**authentication** is a relationship, not a property. You cannot retrieve the authentication methods for all users in the same query, but for one user at a time. To work with the related APIs using REST, see [Azure AD authentication methods](https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0). For PowerShell, one of the cmdlets is [Get-MgUserAuthenticationMethod](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.signins/get-mguserauthenticationmethod?view=graph-powershell-1.0).

**Comment by joetechin** [comment]
Thank you for your reply, @FaithOmbongi.

Perhaps I'm interpreting the documentation incorrectly.
Upon retrieving a user using the following:
$myUser = Get-MgUser -userid $upn 
There is a field called Authentication and it can be accessed with say, $myUser.Authentication. There is indication that there could be information which should be present there.
Checking $myuser | Get-member also shows the following:
Authentication  |  Property |  Microsoft.Graph.PowerShell.Models.IMicrosoftGraphAuthentication Authentication {get;set;}  

Do I interpret it correctly that it is NOT equivalent with StrongAuthenticationMethods property which could be retrieved with MSOnline Powershell SDK?

**Comment by FaithOmbongi** [comment]
Hi @joetechin -

> Perhaps I'm interpreting the documentation incorrectly.
> Upon retrieving a user using the following:
> $myUser = Get-MgUser -userid $upn
> There is a field called Authentication and it can be accessed with say, $myUser.Authentication. 

Yes, you're right that the PowerShell cmdlet `Get-MgUser -userid $upn` returns the **Authentication** object by default. However, it seems PowerShell SDK returns all details of the user entity by default, and it may not be clear which objects are relationships vs those that are properties. @msewaweru, can you advise if it's possible to differentiate at the SDK level?

> There is a field called Authentication and it can be accessed with say, $myUser.Authentication. There is indication that there could be information which should be present there.
> Checking $myuser | Get-member also shows the following:
> Authentication | Property | Microsoft.Graph.PowerShell.Models.IMicrosoftGraphAuthentication Authentication {get; set;}

It's not a guarantee that when you see _Microsoft.Graph.PowerShell.Models.***_, it means there's info in the object. The object could be `null` if it's nullable. This kind of placeholder indicates that the property stores some complex kind of information, as opposed to primitive types like String and GUID types. You must read the specific object using the appropriate syntax to identify whether it stores some information.

> Do I interpret it correctly that it is NOT equivalent with StrongAuthenticationMethods property which could be retrieved with MSOnline Powershell SDK?

Correct. The **Authentication** relationship isn't the replacement for **StrongAuthenticationMethods** relationship in the MSOL cmdlets. In fact, the capabilities that are available through **StrongAuthenticationMethods** aren't available in Microsoft Graph currently, as per[ the comments in this doc](https://learn.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0#what-authentication-methods-can-be-managed-in-microsoft-graph:~:text=The%20following%20authentication%20methods%20are%20not%20yet%20supported%20in%20Microsoft%20Graph%20v1.0.). There's an open developer request to add support for these capabilities in Microsoft Graph.
