### ISSUE TITLE
Canceling upload request does not removes partially uploaded file

### ISSUE THREAD

**Issue by abdulkareemnalband** [microsoftgraph/microsoft-graph-docs#2033]
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_put_content

If file upload pull request is canceled (say by aborting `XMLHttpRequest` https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort), File uploading stops.

But partially uploaded file remains on server.

I think this partial file should be deleted on upload closes before completion

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
