### ISSUE TITLE
Can't assign users to apps using Graph API

### ISSUE THREAD

**Issue by MimoLab** [microsoftgraph/microsoft-graph-docs#2034]
Issue: Can't assign users to apps using Graph API

Article: 
I'm working on a web application that uses AAD authentication. I want to restrict access to the app to users who are assigned to it.
As far as I see, only the beta version of Microsoft Graph API allows this functionality
However I can't manage to make it work. I'm getting the following error while trying to assign a user to an app : Unsupported segment type. ODataQuery: users/{userId}/appRoleAssignments/{Id}

Is this feature still avalible? or am I just missing something?

here is the request url : PATCH https://graph.microsoft.com/beta/users/{userId}/appRoleAssignments/{id}

Body : 
{
    "principalId" : "myprincipalid",
    "resourceId" : "resourceid",
    "id" : "id"
}

Any help would be appreciated

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
