### ISSUE TITLE
The example request does not show the retentioneventtype

### ISSUE THREAD

**Issue by rooobeert** [microsoftgraph/microsoft-graph-docs#20389]
Hi, 

I am trying to figure out how to incorporate the Retention Event Type that needs to be specified, when creating an event. 
The Request body shows the retentionEventType in the table but not in the HTTP schema. 
![image](https://user-images.githubusercontent.com/87785803/221824379-33b68fcc-6702-45d6-8518-eb873355d0d4.png)

Can you specify in the request schema for http where the retentionEventType goes?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24eb81cc-8dbd-7498-3b46-17ee5c1cdb63
* Version Independent ID: b1000f98-c72b-0fcb-4888-c93f0d351383
* Content: [Create retentionEvent - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/security-retentionevent-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/security-retentionevent-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/security-retentionevent-post.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @sseth
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sseth-msft** [comment]
This is fixed and merged but still showing up on my weekly github list, can you take a look and help to close this @rooobeert

**Comment by lramosvea** [comment]
Closing as suggested by @sseth-msft . Please feel free to reopen if not fixed yet. Thanks
