### ISSUE TITLE
One source  for thumbnail photos in the Office 365 stack would be nice!

### ISSUE THREAD

**Issue by MapsRus** [microsoftgraph/microsoft-graph-docs#2039]
Right now the Graph API pulls the thumbnail photo from Azure AD.  However, this photo can be added at the Office 365 User admin layer, as well as in SharePoint Online.  Why have it in three places?  Very confusing and redundant to keep in sync.

**Comment by dmahugh** [comment]
Thanks for your suggestion. FYI, feature requests are handled over on the User Voice site, please feel free to add this there: [https://officespdev.uservoice.com/](https://officespdev.uservoice.com/)
