### ISSUE TITLE
Cannot use orderBy on date property for /users API

### ISSUE THREAD

**Issue by Bux42** [microsoftgraph/microsoft-graph-docs#20427]
Hello

I am trying the following request:
https://graph.microsoft.com/v1.0/users?$select=createdDateTime&$orderby=createdDateTime desc

And I get the following error:

```json
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported sort property 'createdDateTime' for 'User'.",
        "innerError": {
            "date": "2023-03-02T08:26:07",
            "request-id": "d99978ed-4d62-4460-a84f-0cc16fad6d83",
            "client-request-id": "0dba0390-388b-b29b-f9c6-e6aed00bd15d"
        }
    }
}
```

How come sorting works for every type (string, number etc) but not for dates?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44f6304a-ab90-8543-39c7-2afd61197ffb
* Version Independent ID: 9ca019b5-063f-33a2-3cb9-3ab6baafe9d4
* Content: [Use query parameters to customize responses - Microsoft Graph](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/query-parameters.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @Bux42 for raising this issue.

I've tested and your request requires the `$count=true` query string and the **ConsistencyLevel** header set to `eventual`. For more information, see [Advanced query capabilities on Azure AD directory objects](https://learn.microsoft.com/en-us/graph/aad-advanced-queries?tabs=http#:~:text=The%20following%20table%20lists%20query%20scenarios%20on%20directory%20objects%20that%20are%20supported%20only%20in%20advanced%20queries%3A).

Try in Graph Explorer: [https://graph.microsoft.com/v1.0/users?$select=createdDateTime&$orderby=createdDateTime desc&$count=true](https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24select%3DcreatedDateTime%26%24orderby%3DcreatedDateTime%2Bdesc%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d).

I'll follow up with our team to provide comprehensive documentation of all properties of directory objects that support `$orderBy` only with advanced queries when `$orderBy` is used in standalone requests like your example.
