### ISSUE TITLE
Need powershell example using the Microsoft Graph PowerShell SDK

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs#20549]
Multiple people have tried to get this to  work in PowerShell using the MG Graph SDK but there is no example ( sure, it shows the JSON format but no example of how to implement it ).  Please add an example to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a9558a20-4713-973e-8856-b08ba1c37427
* Version Independent ID: 584e208e-b258-bb38-c2ec-25342423f077
* Content: [tokenLifetimePolicy resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/tokenlifetimepolicy?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/tokenlifetimepolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/tokenlifetimepolicy.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @lujiangfeng666
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RayGHeld** [comment]
I have figured this out:  

connect-mggraph


$params = @{
    "definition"= @("{'TokenLifetimePolicy':{'Version': 1, 'AccessTokenLifetime': '5:00:00'}}")
    "displayName"= "5hr_AccessTokenPolicy"
}


New-MgPolicyTokenLifetimePolicy -BodyParameter $params

**Comment by FaithOmbongi** [comment]
Thank you @RayGHeld for raising this issue and providing a response.

To see the Microsoft Graph PowerShell syntax for the Create operation, please see the examples in the [Create tokenLifetimePolicy documentation](https://learn.microsoft.com/en-us/graph/api/tokenlifetimepolicy-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=powershell#examples).

**Comment by RayGHeld** [comment]
Hi FaithOmbongi, so the docs show using this value in the json:  "definition-value"  -- however, that value must be in a very specific format and that is what is difficult to find.  This is what I ended up using ( no clear documentation for this at all ):  $params = @{
    "definition"= @("{'TokenLifetimePolicy':{'Version': 1, 'AccessTokenLifetime': '5:00:00'}}")
    "displayName"= "5hr_AccessTokenPolicy"
    "IsOrganizationDefault" = $true
}
That works but our docs do not help at all.
