### ISSUE TITLE
Missing justification from response in v1.0

### ISSUE THREAD

**Issue by timd19** [microsoftgraph/microsoft-graph-docs#20555]
In this 1.0 endpoint, justification is missing from the response. but in the beta endpoint, justification is available.

v1.0
![image](https://user-images.githubusercontent.com/22712034/224484858-cea242c2-0993-4510-bb6a-9df99b137c61.png)

BETA
![image](https://user-images.githubusercontent.com/22712034/224484592-92ccc13e-3bc5-4596-bcf0-051b55371fb5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de2849e0-cfdb-3f14-36c1-78afba09c5a3
* Version Independent ID: 5f557910-648d-c73a-4ea8-50a45ad49eb8
* Content: [Get accessPackageAssignmentRequest - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/accesspackageassignmentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/accesspackageassignmentrequest-get.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @timd19 for raising this issue.

**accessPackageAssignmentRequest** in v1.0 doesn't have the justification property. Please see the [resource documentation: Properties](https://learn.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-1.0#properties).

**Comment by timd19** [comment]
I wasn't looking for an answer to the obvious. when will this property be available in 1.0? It seems these endpoints are all over the place, and takes years for things to make it into V1.0. We have been using entitlement management for 3 years now, and have never got to all 1.0 endpoints.

**Comment by FaithOmbongi** [comment]
> I wasn't looking for an answer to the obvious. when will this property be available in 1.0? It seems these endpoints are all over the place, and takes years for things to make it into V1.0. We have been using entitlement management for 3 years now, and have never got to all 1.0 endpoints.

Hi @timd19 - Unfortunately, I can't provide an ETA. If you file [a version parity request](https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80), the engineering team can provide an ETA or prioritize the ask.
