### ISSUE TITLE
the permission should be 'UserAuthenticationMethod.Read.all'

### ISSUE THREAD

**Issue by jillchangms** [microsoftgraph/microsoft-graph-docs#20569]
For the read permission, the permission should be 'UserAuthenticationMethod.Read.all'
But the permission only state:  UserAuthenticationMethod.Read
It would have the 
Get-MgUserAuthenticationMicrosoftAuthenticatorMethod : Request Authorization failed

 -   UserAuthenticationMethod.Read
![image](https://user-images.githubusercontent.com/102293058/224738918-230aae81-f5e8-4b97-ae6d-d26fa8ea9240.png)

 - UserAuthenticationMethod.Read.all
 
![image](https://user-images.githubusercontent.com/102293058/224739059-62e6c558-9343-47cd-b95c-93d66605e521.png)

Please modify the document, thank you.

ref: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/550

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7b1ddbdb-cac1-0ee0-2e78-f0051415ce86
* Version Independent ID: 4268e948-031e-5476-f799-aa525074d41f
* Content: [List microsoftAuthenticatorAuthenticationMethods - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jillchangms for raising this issue. This API and the related cmdlet can be used in two contexts that are indicated in the documentation.

- By a user to retrieve their own methods, through `/me/authentication/microsoftAuthenticatorMethods` or `/users/{id | userPrincipalName}/authentication/microsoftAuthenticatorMethods` where "{id | userPrincipalName}" is the signed-in user's.
    - In this context, _UserAuthenticationMethod.Read_ is sufficient. Please see [Permissions acting on self](https://learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&tabs=http#permissions-acting-on-self).
- By a user to retrieve auth methods for others in the tenant through `/users/{id | userPrincipalName}/authentication/microsoftAuthenticatorMethods` where "{id | userPrincipalName}" can be any user's. In this context, _UserAuthenticationMethod.Read.All_ is required. Please see [Permissions acting on others](https://learn.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&tabs=http#permissions-acting-on-other-users).
   - Based on your screenshot and the error messages, this is the context you were running.
   
Hope this provides an answer to the issue you ran into and points to the appropriate guidance in the doc.
