### ISSUE TITLE
.expand does not work in the sdk

### ISSUE THREAD

**Issue by Omzig** [microsoftgraph/microsoft-graph-docs#20574]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9eead3-fd14-629f-dd6d-55e0c51d74ff
* Version Independent ID: cc096658-8f79-45c2-9d42-69e4fe9a3a49
* Content: [Make API calls using the Microsoft Graph SDKs - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS)
* Content Source: [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/create-requests.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this has been reported already and it will be tracked here: https://github.com/microsoftgraph/microsoft-graph-docs/issues/20525. Thanks.
