### ISSUE TITLE
[Germany] fail to request mailFolders' delta

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2059]
Hi,

**It is on germany endpoint, https://graph.microsoft.de**

I can successfully list mail folders by
```
https://graph.microsoft.de/v1.0/users/{user_id}/mailFolders/
```

But when I request for delta
```
https://graph.microsoft.de/v1.0/users/{user_id}/mailFolders/delta
```

It returns 
```
{
    "error": {
        "code": "ErrorInvalidIdMalformed",
        "message": "Id is malformed.",
        "innerError": {
            "request-id": "786e6dfd-b021-497e-a3d1-1127d24bd526",
            "date": "2017-12-12T06:53:58"
        }
    }
}
cache-control →private
client-request-id →786e6dfd-b021-497e-a3d1-1127d24bd526
content-type →application/json
date →Tue, 12 Dec 2017 06:53:58 GMT
duration →408.2544
request-id →786e6dfd-b021-497e-a3d1-1127d24bd526
transfer-encoding →chunked
x-ms-ags-diagnostic →{"ServerInfo":{"DataCenter":"Germany Central","Slice":"SliceB","Ring":"NA","ScaleUnit":"000","Host":"AGSFE_IN_4","ADSiteName":"DCE"}}
```

Thanks for help!

**Comment by ArunMSFT** [comment]
Hey @joewutaiwan - Sorry about the delay in getting to this. Is this still an issue?

**Comment by joewutaiwan** [comment]
@ArunMSFT 

Hi sir,

It is still with the same problem.

Thank you!

**Comment by joewutaiwan** [comment]
@ArunMSFT 

Hi sir,
Do you have any update on this issue?
Thank!

**Comment by ArunMSFT** [comment]
Sorry I don’t have an update yet. Will get back soon.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jthake-msft** [comment]
@ArunMSFT ?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. I'm cleaning up this repo. 
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
