### ISSUE TITLE
Wrong line ending in url

### ISSUE THREAD

**Issue by pawjo** [microsoftgraph/microsoft-graph-docs#20597]
Hello,
I found probably wrong url ending in request for access token.
There is "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token HTTP/1.1" but it didn't work for me and I had to use such url: "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 04f96510-c628-47f8-971f-d5ba7b560efc
* Version Independent ID: f27f8646-1313-f225-b315-1ae3bc036117
* Content: [Get access without a user - Microsoft Graph](https://learn.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/auth-v2-service.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @pawjo for raising this issue.

The URL in the doc follows the generally applied format for documenting HTTP requests hence the `HTTP/1.1` in the same line after the URL. Unfortunately, clearly, this can be confusing.

In response to popular developer feedback, we are updating the sample requests to include curl formats that most developers have said are easier to understand and import into testing tools of their choice. Hopefully, this will help address the issue.

**Comment by FaithOmbongi** [comment]
Closing this issue as the article now includes cURL requests.
