### ISSUE TITLE
"Unrecognized query argument specified: ''." when using filter with  https://graph.microsoft.com/beta/groups/delta

### ISSUE THREAD

**Issue by gfree76** [microsoftgraph/microsoft-graph-docs#20602]
When I try to use a filter against the beta/groups/delta endpoint, I get an error regardless of what I try passing in. 

here's an example: 
```
curl -X GET "https://graph.microsoft.com/beta/users/delta/?$filter=startsWith%28displayName%2C%20%27Geoff%27%29" \
    -H "Authorization: Bearer $TOKEN" | jq '.' 
```
returns
```
{
  "error": {
    "code": "Request_BadRequest",
    "message": "Unrecognized query argument specified: ''.",
    "innerError": {
      "date": "2023-03-15T16:47:28",
      "request-id": "c64282b0-4d76-48d3-9d81-c0b213874b7e",
      "client-request-id": "c64282b0-4d76-48d3-9d81-c0b213874b7e"
    }
  }
}
```

I get the same thing when I try the format from https://learn.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http#request-1
```
curl -X GET "https://graph.microsoft.com/beta/groups/delta/?$filter=hasMembersWithLicenseErrors+eq+true" \
    -H "Authorization: Bearer $TOKEN" | jq '.' 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bdaf58ca-8b6c-cddd-f583-f8617b0450a6
* Version Independent ID: 08b26245-df55-d5d5-a6d2-edc69eda3fe3
* Content: [Get incremental changes for groups - Microsoft Graph](https://learn.microsoft.com/en-us/graph/delta-query-groups?tabs=http)
* Content Source: [concepts/delta-query-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/delta-query-groups.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @gfree76 for raising this issue.

From [the docs](https://learn.microsoft.com/en-us/graph/delta-query-overview#:~:text=Scoping%20filters%20allow%20you%20to%20track%20changes), it seems `$filter` with `/delta` for users and groups is only supported for **id** and with the `eq` operator. And doesn't seem supported in any other filter scenarios.

cc @jumasure

**Comment by gfree76** [comment]
I would argue that the docs aren't clear at all - they say that scoping filters allow you to track one or more, but not that it's only support for that or for the eq operator. 

But even WITH that - can you make it work? I have tried it a bunch of different ways, and none of them work. 
Here's the example from the doc: 
```
curl -X GET "https://graph.microsoft.com/beta/groups/delta/?$filter=id eq '477e9fc6-5de7-4406-bb2a-7e5c83c9ae5f'" \
    -H "Authorization: Bearer $TOKEN" | jq '.' 
```
returns curl: (3) URL using bad/illegal format or missing URL, because you can't have spaces in the url. So I tried putting plusses in, like I'd seen in a doc somewhere about the filter operator:
```
curl -X GET "https://graph.microsoft.com/beta/groups/delta/?$filter=id+eq+'477e9fc6-5de7-4406-bb2a-7e5c83c9ae5f'" \
    -H "Authorization: Bearer $TOKEN" | jq '.' 
```
returns
```
{
  "error": {
    "code": "Request_BadRequest",
    "message": "Unrecognized query argument specified: ''.",
    "innerError": {
      "date": "2023-03-15T18:20:57",
      "request-id": "2d43a0ce-a720-4d12-b3ef-56f23adcee96",
      "client-request-id": "2d43a0ce-a720-4d12-b3ef-56f23adcee96"
    }
  }
}
```

Same response with the following tries where I tried url encoding: 
```
curl -X GET "https://graph.microsoft.com/beta/groups/delta/?$filter=id%20eq%20%27477e9fc6-5de7-4406-bb2a-7e5c83c9ae5f%27" \
    -H "Authorization: Bearer $TOKEN" | jq '.' 
> Unrecognized

curl -X GET "https://graph.microsoft.com/beta/groups/delta/?$filter=id%2Beq%2B%27477e9fc6-5de7-4406-bb2a-7e5c83c9ae5f%27" \
    -H "Authorization: Bearer $TOKEN" | jq '.'
> Unrecognized
```

Can you give me an example of what a successful invocation would look like?

**Comment by gfree76** [comment]
oh and I also tried with plusses but without quotes around the guid: 
```
curl -X GET "https://graph.microsoft.com/beta/groups/delta/?$filter=id+eq+477e9fc6-5de7-4406-bb2a-7e5c83c9ae5f" \
    -H "Authorization: Bearer $TOKEN" | jq '.' 
```
Unrecognized query arguement specified ''.

**Comment by FaithOmbongi** [comment]
Hi @gfree76 -

We have an ongoing effort to improve the documentation around change tracking and I'm taking your feedback as an action item. So, I'll leave this issue open until we update the documentation. cc @jumasure for visibility.

> Can you give me an example of what a successful invocation would look like?

I've tried this curl request and it has succeeded

```http
curl -X GET --header "Authorization: Bearer eyJ0..aaw" "https://graph.microsoft.com/v1.0/groups/delta?%24filter=id%20eq%20%278afc02cb-4d62-4dba-b536-9f6d73e9be26%27"
```

You can also try in Postman to get the curl format. See this also helps you.

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/14026935/225411972-36fa51ff-9c42-4780-aced-efa86afe44f9.png">

**Comment by gfree76** [comment]
gah - i hadn't URL encoded the '$' character in front of the parameter name. Thanks Faith! The postman hint is a big help.

**Comment by FaithOmbongi** [comment]
Glad to be of service @gfree76.

**Comment by FaithOmbongi** [comment]
The docs are now up to date thanks to @keylimesoda. Closing this issue.
