### ISSUE TITLE
Alternative for production

### ISSUE THREAD

**Issue by safari137** [microsoftgraph/microsoft-graph-docs#20663]
I'm looking for something to show the last sign in date that's available in the production v1.0 endpoint.  By policy we do not use beta endpoints since they are subject to change.

We cannot use audit logs since they only show data for the last 30 days.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0f258b-b61e-72a2-0caf-d9b7fff5857d
* Version Independent ID: 90c2edf2-51ee-6bab-84a6-3710a3f0ccd2
* Content: [signInActivity resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/signinactivity.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @safari137 for raising this issue. The signInActivity property and its downstream signInActivity resource type object will become available in v1.0 soon. We have a docs PR to make it available for production.

cc @besiler

**Comment by safari137** [comment]
That's good news, thanks for the quick reply.  Do you have any dates? Maybe be the end of the second quarter?

**Comment by FaithOmbongi** [comment]
Hi @safari137 - Unfortunately, I can't commit to an ETA. You can periodically check the [Microsoft Graph changelog](https://developer.microsoft.com/en-us/graph/changelog/?search=) or subscribe to get notified when the resource type is published.

**Comment by FaithOmbongi** [comment]
Good news @safari137 - signInActivity is now available in v1.0! You can find the docs here [signInActivity resource type](https://learn.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-1.0).

**Comment by safari137** [comment]
awesome, thank you for the update!
