### ISSUE TITLE
Intune Create #Device#CompliancePolicy

### ISSUE THREAD

**Issue by shareonline** [microsoftgraph/microsoft-graph-docs#2070]
Issue: 
When trying to create Device compliance policies through Graph, i just get an error.
This worked fine a month ago, but when reusing my code now nothing works and just comes back with the following error:

{
"error": {
"code": "InternalError",
"message": "An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 83cf2637-fd85-48da-a7bf-3fd1797d3c93 - Url: https://fef.amsub0102.manage.microsoft.com/StatelessDeviceConfigurationFEService/deviceManagement/deviceCompliancePolicies?api-version=5017-09-19 - CustomApiErrorPhrase: ",
"innerError": {
"request-id": "83cf2637-fd85-48da-a7bf-3fd1797d3c93",
"date": "2017-12-13T10:21:26"
}
}
}

I have also tried through graph explorer and 2 different tenants
Article:

**Comment by shareonline** [comment]
I'm creating a new issue as the other was closed. #2064

My endpoint is /deviceManagement/deviceCompliancePolicies so the issue still persist..

**Comment by triplanedave** [comment]
There were a number of changes that went into the latest update.  Check the changelog here: https://developer.microsoft.com/en-us/graph/docs/concepts/changelog

Additionally, as a test, you might try this. 
In the Azure Portal for Intune - create your intended policy.  But, before you start, launch the developer tools (typically just press F12) and get a trace of the network during your save operation.  Look at the request body and compare that with what your code is submitting.  Likely we made a change that'll be (hopefully) obvious by comparing what the UI pushes in the request body and what your code is generating for the request body.

Dave [MSFT]

**Comment by shareonline** [comment]
This is not working..

{
  "@odata.type": "#microsoft.graph.androidForWorkCompliancePolicy",
  "description": "Description value",
  "displayName": "Display Name value",
  "passwordRequired": true,
  "passwordMinimumLength": 5,
  "passwordRequiredType": "alphabetic",
  "passwordMinutesOfInactivityBeforeLock": 5,
  "passwordExpirationDays": 6,
  "passwordPreviousPasswordBlockCount": 2,
  "securityPreventInstallAppsFromUnknownSources": true,
  "securityDisableUsbDebugging": true,
  "requireAppVerify": true,
  "deviceThreatProtectionEnabled": true,
  "deviceThreatProtectionRequiredSecurityLevel": "secured",
  "securityBlockJailbrokenDevices": true,
  "osMinimumVersion": "Os Minimum Version value",
  "osMaximumVersion": "Os Maximum Version value",
  "minAndroidSecurityPatchLevel": "Min Android Security Patch Level value",
  "storageRequireEncryption": true,
  "requireSafetyNetAttestationBasicIntegrity": true,
  "requireSafetyNetAttestationCertifiedDevice": true,
  "requireGooglePlayServices": true,
  "requireUpToDateSecurityProviders": true,
  "requireCompanyPortalAppIntegrity": true
}
POST https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies

I get the following error in graph explorer:

{
    "error": {
        "code": "InternalError",
        "message": "An internal server error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: f0bb5b24-d9cc-43cc-be43-b2f6138321d5 - Url: https://fef.amsub0102.manage.microsoft.com/StatelessDeviceConfigurationFEService/deviceManagement/deviceCompliancePolicies?api-version=5018-01-10 - CustomApiErrorPhrase: ",
        "innerError": {
            "request-id": "f0bb5b24-d9cc-43cc-be43-b2f6138321d5",
            "date": "2017-12-18T10:56:52"
        }
    }
}

**Comment by shareonline** [comment]
I also tried to take the POST made from azure portal (F12) remove the ID but same error..

**Comment by shareonline** [comment]
Seems like scheduledActionsForRule is now mandatory.. Please update the documentation..

{
"id":"00000000-0000-0000-0000-000000000000",
"displayName":"test",
"description":"test",
"@odata.type":"#microsoft.graph.androidForWorkCompliancePolicy",
"scheduledActionsForRule":[
	{
	"ruleName":"PasswordRequired",
	"scheduledActionConfigurations":[
		{
		"actionType":"block",
		"gracePeriodHours":0,
		"notificationTemplateId":"",
		"notificationMessageCCList":[]
		}
	]}
],
"deviceThreatProtectionRequiredSecurityLevel":"unavailable",
"deviceThreatProtectionEnabled":false
}
