### ISSUE TITLE
Provide code examples for both .NET SDK v4 and v5

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#20809]
All Graph API documentations show .NET examples for SDK v5. 

Many users are still using SDK v4 for some reasons and providing examples for .NET SDK v4 would be very useful.

It would be also useful to highlight that .NET code examples are for SDK v5.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Microsoft Graph overview - Microsoft Graph](https://learn.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maisarissi** [comment]
Hi @MartinM85 .

Our docs are meant to only support the latest version of our tooling.
However, we do know the new version introduced a lot of breaking changes and we do recognize that folks need time to update their applications. With that in mind, we generated a [snapshot of the reference documentation](https://github.com/microsoftgraph/msgraph-sdk-dotnet/tree/dev/docs/v4-reference-docs) with v4 samples and saved it in the .NET client library repo. However, we will only keep them in the repo for a period of time to allow users plan their migration, after that, the content will be deleted.

We will also add a reference to the .NET client repo in our docs to improve discoverability. Here is the issue: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/1498

**Comment by MartinM85** [comment]
Agree that folks need time to update their applications but there is one important point. Developers expect that everything what worked in v4 will work in v5. 

v5 was released a month ago and there is still no support for workbook API. https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1783 and https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1673. Maybe it doesn't effect many developers but it still blocker for migration and sometimes it's hard to explain to the customer why we cannot migrate to v5.

**Comment by maisarissi** [comment]
Yes, you are completely right! We are working to make sure those paths are available in v.5.x
In the meantime, please, keep raising issues whenever you see a bug, so we can make sure to cover the scenarios you need to migrate!
As a workaround, you can use the https://github.com/microsoftgraph/msgraph-sdk-dotnet/tree/dev/docs/v4-reference-docs to find v4 samples for the things you need.
