### ISSUE TITLE
Doc question: is "oauth2Permissions" nullable or not?

### ISSUE THREAD

**Issue by aaronmi** [microsoftgraph/microsoft-graph-docs#2081]
Question: 
In doc titled "servicePrincipal resource type", under Properties, "oauth2Permissions" is marked as "Not nullable" under description column. However, on same page, under Relationships, it is marked as "Nullable". 
Is "oauth2Permissions" nullable or not?

Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/serviceprincipal.md

**Comment by Hongbo-Miao** [comment]
Misread?
oauth2Permissions is not nullable.
oauth2PermissionGrants is nullable.

**Comment by aaronmi** [comment]
Thanks for correcting me. I see it clearly now.
