### ISSUE TITLE
Missing API Reference Document for Path: "/users/{user-id}/manager/$ref"

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/microsoft-graph-docs#20817]
The Api path ```GET /users/{user-id}/manager/$ref``` which translates to ```Get-MgUserManagerByRef``` PowerShell command, is missing from the Api reference doc. So, it's impossible to get examples associated with that path.

**Comment by FaithOmbongi** [comment]
Thank you @timayabi2020 for your patience. Engineering has confirmed that the endpoint is not a valid endpoint (even if it may work today) and therefore shouldn't be documented.

**Comment by timayabi2020** [comment]
@FaithOmbongi. I don't understand when you say that the endpoint is not valid yet it's available in the clean metadata [file](https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/powershell.yaml).
<img width="620" alt="image" src="https://user-images.githubusercontent.com/10947120/236574575-da197a8d-0c22-4e76-8cd9-dfb84088670f.png">
It therefore implies that our metadata is not valid and that's what we rely on to generate PowerShell commands.

**Comment by FaithOmbongi** [comment]
Hi @timayabi2020 - I understand that the metadata also relies on the Microsoft Graph schema. If annotations need to be added to the schema to block this, then I recommend that solution. But today, this endpoint isn't considered valid for customer use.

**Comment by timayabi2020** [comment]
Hi @FaithOmbongi thanks for following this up and the suggestion. I have a PR [here](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1953) which will prevent publishing of wrong examples to the PowerShell reference docs portal. It will also generate a report from pipeline runs. The report will include all the commands whose examples should be reviewed.
