### ISSUE TITLE
Needs clarity on property descriptions

### ISSUE THREAD

**Issue by Mark-InvokeLLC** [microsoftgraph/microsoft-graph-docs#20923]
1) Does the id property value appear in a property of another object type? Does it somehow map to an AppRole record (other than appRoleId)?
2) The description for resourceId property seems vague. How does it relate to principalId?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba2d096-43e1-c42d-a258-e31f76d2c5f2
* Version Independent ID: de382dbd-ef59-9a2e-dad0-aefd5f97555b
* Content: [appRoleAssignment resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/approleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/approleassignment.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
@Mark-InvokeLLC:

1. No, the **id** property of an **appRoleAssignment** entity does not currently appear as a property of any other resource type. It is the ID of that assignment, not of the app role. You'd use it to operate directly on a specific assignment, such as deleting it (e.g. `DELETE .../servicePrincipals/{resource-sp-id}/appRoleAssignedTo/{id}`).
2. The **resourceId** property of an **appRoleAssignment** is the **id** of the **servicePrincipal** for which the app role assignment is being made--known as the "resource service principal". Any suggestions on wording that would make it more clear would be most welcome.
   Here are two examples that might help you understand what this means:
   1. In an app role assignment for the app role "Reader" on app "Fabrikam App" to user "Bob":
      - **resourceId** is the **id** of the service principal for "Fabrikam App"
      - **appRoleId** is the **id** for the "Reader" app role (defined on "Fabrikam App")
      - **principalId** is the **id** for Bob's user object
   2. In an app role assignment for the app role "User.Read.All" on the "Microsoft Graph" API to the service "Contoso Automation Service"
      - **resourceId** is the **id** of the Microsoft Graph **servicePrincipal**
      - **appRoleId** is the **id** of the "Reader" **appRole** (defined on Microsoft Graph)
      - **principalId** is the **id** of the service principal for "Contoso Automation Service"

**Comment by Mark-InvokeLLC** [comment]
OK awesome clarification. For #2, your wording is great. no suggestions for improvement on that.

**Comment by psignoret** [comment]
@Mark-InvokeLLC Thanks for the feedback!
