### ISSUE TITLE
Possible bug in /outlook/masterCategories endpoint

### ISSUE THREAD

**Issue by Spazer9** [microsoftgraph/microsoft-graph-docs#2094]
It seems any endpoints starting with `/outlook` return this error:

```
GET https://graph.microsoft.com/beta/me/outlook/masterCategories
{
    "error": {
        "code": "RequestBroker-ParseUri",
        "message": "Resource not found for the segment 'Outlook'.",
        "innerError": {
            "request-id": "a75d1c9a-c6ae-4b69-83ca-fc0e467a4ad7",
            "date": "2017-12-26T17:23:17"
        }
    }
}
```

I have authorized the scopes `mail.read` `offline_access` `user.read` `mailboxsettings.readwrite` so I should be able to access a user's inbox categories, but the beta API endpoints starting with "outlook" mentioned in this post: 

https://blogs.msdn.microsoft.com/exchangedev/2017/10/09/new-outlook-apis-in-the-microsoft-graph-rooms-rules-categories-headers-and-time-zones/

are not accessible whatsoever, am I doing something wrong?

Keep in mind I tested this endpoint and it works perfectly: https://graph.microsoft.com/beta/me/mailFolders

but this one: https://graph.microsoft.com/beta/me/outlook/masterCategories returns the error above.

**Comment by ArunMSFT** [comment]
Thanks for reporting, we are looking into this.

**Comment by Spazer9** [comment]
@ArunMSFT I can confirm that this only happens on personal @outlook.com accounts, not on O365 accounts.

**Comment by ArunMSFT** [comment]
Thanks for the info. We are working on a fix and hope to have it released in a week or two.
