### ISSUE TITLE
How to list groups which users are a Visitor of?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/microsoft-graph-docs#20961]
My understanding with group permissions is that they can be based on Visitor, Member or Owner.

We can find which groups a user is a member of, or which they are an owner of, but how do we find groups that the user is a visitor of?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2e41493-05ab-9f85-ccd8-7244303ae4ff
* Version Independent ID: 30167152-63a7-da89-573e-2ea68bd352f8
* Content: [List a user's memberships (direct and transitive) - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-list-transitivememberof.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @catmanjan for asking this question.

I'll assume by "Visitor" you mean "guest user".

There's no concept of guest membership for groups. A user is either a member of the group or they are not. In PIM for groups, a user can be a group member for a specific time only and their membership removed when the time expires. But still, they are either a member or they aren't. Hope this answers your question.

**Comment by catmanjan** [comment]
@FaithOmbongi what about the SharePoint Visitor group that exists in every Teams Site?
