### ISSUE TITLE
The current create domain does not allow to create sub domain when root domain is federated

### ISSUE THREAD

**Issue by JimmyLS** [microsoftgraph/microsoft-graph-docs#20987]
As per my testing, I found the current create domain does not allow to create sub domain when root domain is federated. No matter if sudomain is set to "Federated" or "Managed".

Repro steps:

1. Find a verified root domain which is "Federated".
2. Use MS Graph Powershell/MS Graph Explorer to create sub domain:

MS Graph Powershell Command:

```
New-MgDomain -Id "sub.domain.com" -AuthenticationType "Managed"
New-MgDomain -Id "sub.domain.com" -AuthenticationType "Federated"
```

MS Graph API used when using Ms Graph Explorer:

POST: https://graph.microsoft.com/v1.0/domains

Req body:

```
{
    "id": "sub.domain.com",
    "authenticationType": "Managed"
}

{
    "id": "sub.domain.com",
    "authenticationType": "Federated"
}

```
Tried on both "v1.0" and "beta" MS Graph version, both not working. 

We got this error when trying to set subdomain as "Managed":

```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "One or more properties contains invalid values.",
        "innerError": {
            "date": "2023-04-19T07:14:16",
            "request-id": "96697314-bc2c-4ab3-8e84-511929237595",
            "client-request-id": "be1d7add-f6ff-d220-cdc7-ac70e8b9dabc"
        }
    }
}

```
We got this error when trying to set subdomain as "Federated":

```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Creation of federated domain is not allowed.",
        "innerError": {
            "date": "2023-04-19T07:18:59",
            "request-id": "ba6dbfd4-fec5-4584-af2c-4bca5a40ad9a",
            "client-request-id": "014d840f-52d2-61a5-a24b-ddb0f2f220ad"
        }
    }
}
```

Currently, when using the old "MSOnline" powershell command we can achieve the requirement, createing a sub domain as "Federated", command:

`New-MsolDomain -Name "sub.domain.com" -Authentication Federated`

The sub domain is needed in cases when we want to create mailboxes. After MSOL powershell module been deprecated, this will become unachievable. Could you please have a review and consider to allow this in MS Graph API?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b63f8c75-1a5f-dcc2-2ae7-3e943706120e
* Version Independent ID: 30320df1-0307-30d6-af00-7447a3889ba7
* Content: [Create domain - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/domain-post-domains?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/domain-post-domains.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/domain-post-domains.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @adimitui
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @JimmyLS for raising this issue. I see in the documentation that only ID can be specified during the Create operation and the **authenticationType** property is also read-only.

Your question seeks clarity on an API functionality and questions feature parity with an MSOL cmdlet. I recommend that you file this issue at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/271/microsoft-graph-identity-api) so it can be investigated, and a conclusive response provided.

No updates identified for the documentation as of now, but we'll update the doc when new information becomes available. Closing this issue here.

**Comment by JimmyLS** [comment]
@FaithOmbongi  I think that's nor correct. The same API works fine when I attemted to create a sub domain (managed) which the root is also managed.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/25541899/233035647-b7e4fb82-20bf-48ea-a94d-250656671ebb.png">

Also, when using `New-MgDomain` common the document stated there's a parameter called "AuthenticationType" which can be set to "Managed" or "Federated".

[](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.identity.directorymanagement/new-mgdomain?view=graph-powershell-1.0#-authenticationtype)

**Comment by JimmyLS** [comment]
I have posted the question here: https://learn.microsoft.com/en-us/answers/questions/1246992/the-current-create-domain-does-not-allow-to-create
