### ISSUE TITLE
Article does not state if more than one owner can be added at a time

### ISSUE THREAD

**Issue by jreyes4949** [microsoftgraph/microsoft-graph-docs#20998]
Would like clarification if adding multiple owners at once is possible or if this has to be ran for each individual owner.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb86baa1-3d23-e549-c840-60c095976b6d
* Version Independent ID: d20191f3-e896-da5b-a280-7c3ff673d3e7
* Content: [Add owner - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-owners.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jreyes4949 for asking this question. You can only add one owner at a time throughh the API.
