### ISSUE TITLE
Cannot retrieve group/unseenCount

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-docs#21]
I've just noticed that although the **unseenCount** property is specified in Group's schema, it's not returned as a part of the `/v1.0/directoryObjects/<id>` request: either when requesting the complete group information or only the **unseenCount** property using the **$select** parameter. If this is a known limitation it would be helpful if it was mentioned in the documentation.

**Comment by sumurthy** [comment]
@dkershaw10 @VenkatAyyadevara-MSFT @rohitag1

**Comment by dkershaw10** [comment]
Filed an internal bug about unseenCount

**Comment by Lauragra** [comment]
Closing this issue for now. Feel free to reopen if you need anything else. Thanks.
