### ISSUE TITLE
Birthday (and other properties) not available when signing in with a Microsoft Account

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#2101]
Issue:  Some `user` properties are not available (will be null) for Microsoft Account users.  We don't make this explicit in the documentation.  An example is `birthday` which the developer expects to be available through Microsoft Graph, but it's not.  Other examples are properties that are clearly organization/school properties and not consumer properties. 
See https://stackoverflow.com/questions/48028896/microsoft-graph-api-does-not-give-birthday-user-information for the reported issue on StackOverflow.

Articles:  
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/user
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get

**Comment by PatLac04** [comment]
Another incorrect behavior when using a Microsoft Account is the fact that it ignores the properties specified in the $select and returns everything instead of only the specified properties. 

Try the following request in the graph explorer and sign-in with work or school account. Then try it when signed-in using Microsoft account:
  https://graph.microsoft.com/v1.0/me?$select=displayName,givenName,surname.

Thanks.

**Comment by mindaugasvcs** [comment]
Microsoft, how do we get gender and birthday???

**Comment by dluc** [comment]
Any update?

**Comment by pantoholli** [comment]
Any update how to get the birthday?

**Comment by dluc** [comment]
@FaithOmbongi could you provide some feedback? Why was the request closed? Any suggestion about how we can address this problem? Thanks

**Comment by FaithOmbongi** [comment]
Hello @dluc , the [List users API page](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters) now indicates all properties that have been confirmed as unavailable for personal Microsoft accounts. The team has also received the request to support some of these properties in commercial accounts. I would also recommend you open a [feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph) for this and others can upvote it.
