### ISSUE TITLE
getAllMessages loops infinitely

### ISSUE THREAD

**Issue by jamie-everlaw** [microsoftgraph/microsoft-graph-docs#21096]
When fetching all messages for a user, we frequently run into a case where a page of messages has either itself or a previous page returned as the next page leading to an infinite loop.
We've hacked around this by tracking all skip tokens and exiting our loop whenever we're given one that we've used before, but there's concern that we aren't receiving all the data.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5ddb2c6-bfd9-a019-c1e3-3744b63653df
* Version Independent ID: d8ae4a6f-4a10-8937-bdc6-52281d27f653
* Content: [chats: getAllMessages - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/chats-getallmessages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chats-getallmessages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/chats-getallmessages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Do you have a set of client-request-ID and timestamp where this happened? We would like to take a deeper look.

**Comment by Nivedipa-MSFT** [comment]
@jamie-everlaw - Could you please share the client-request-ID and timestamp to investigate further?

**Comment by jamie-everlaw** [comment]
Our currently logging doesn't capture request id, but I have timestamp and the url if those are sufficient. If not, I can add the request id to our logs and let you know the next time it comes up.

**Comment by RamjotSingh** [comment]
Let's start with those, if we cant find we will come and ask.

**Comment by jamie-everlaw** [comment]
@RamjotSingh ok great. What's the best way for me to send those to you? Also, would providing app ID be helpful?

**Comment by RamjotSingh** [comment]
Provide the exact timestamp, request path (atleast parts of it) and share appId or some parts of it.

**Comment by jamie-everlaw** [comment]
App ID: 78be7154-485f-4f46-9b70-179bcfcde4c0

Here are a couple recent examples. I can provide more if that's helpful

1.
@timestamp:Apr 25, 2023 @ 20:44:57.000 UTC
Multi page loop detected on url https://graph.microsoft.com/beta/users/58f1e97c-1d88-4259-80db-1fbb5b2b78f9/chats/microsoft.graph.getAllMessages?$skiptoken=U2tpcFZhbHVlPTQwI01haWxib3hGb2xkZXI9TWFpbEZvbGRlcnMvVGVhbXNNZWV0aW5ncw%3d%3d and https://graph.microsoft.com/beta/users/58f1e97c-1d88-4259-80db-1fbb5b2b78f9/chats/microsoft.graph.getAllMessages?$skiptoken=U2tpcFZhbHVlPTAjTWFpbGJveEZvbGRlcj1NYWlsRm9sZGVycy9UZWFtQ2hhdA%3d%3d

The first URL above is the current page and the second URL is a previous page that's being given as a next page.

2.
@timestamp:Apr 25, 2023 @ 16:04:34.000 UTC
Same page loop detected on url https://graph.microsoft.com/beta/users/1fc4d42e-08b9-4caf-8ac4-6b3bcd2af33a/chats/microsoft.graph.getAllMessages?$skiptoken=U2tpcFZhbHVlPTEwI01haWxib3hGb2xkZXI9TWFpbEZvbGRlcnMvVGVhbXNNZWV0aW5ncw%3d%3d

This is an example of a page where it has itself as a next page.

**Comment by RamjotSingh** [comment]
We identified the issue and the fix should be deployed in next 2-3 weeks.

**Comment by jamie-everlaw** [comment]
That's great news, thanks!

**Comment by RamjotSingh** [comment]
This should be fixed. Please reopen if it isnt.
