### ISSUE TITLE
No reference returned for the Access Package id when requesting Access Package Assignment Policies

### ISSUE THREAD

**Issue by brolifen** [microsoftgraph/microsoft-graph-docs#21117]
When returning an assignment policy there is no information referencing the Access Package it's linked to. This does not allow you to filter on access package ID to for instance only return the assignment policies linked to a specific access package.

A reference to the Access Package ID should be included in the response.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e48dbd82-88f7-4705-dcae-34ec235d6e70
* Version Independent ID: 5678582a-43fb-38a9-d332-a839a4138294
* Content: [List assignmentPolicies - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/entitlementmanagement-list-assignmentpolicies?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/entitlementmanagement-list-assignmentpolicies.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jan1503** [comment]
Hey,
you have to request that the response should include the access-packages with the following to get the linked access-packages:
![image](https://user-images.githubusercontent.com/10504259/236301424-7f5d4f8e-fb2d-486f-ab72-430d9e9bbc6a.png)
