### ISSUE TITLE
List settings API does not return any data neither error

### ISSUE THREAD

**Issue by Anton-uptycs** [microsoftgraph/microsoft-graph-docs#21141]
The problem is that [List settings API](https://learn.microsoft.com/en-us/graph/api/group-list-settings?view=graph-rest-1.0&tabs=go) does not return any data neither error. 
I don't receive any errors related to permissions or any other issues. 

The example of how I call it: 

```
func (c *clientImpl) GetGroupSettingsV1(ctx context.Context) ([]models.GroupSettingCollectionResponseable, error) {

	clientOptions := msgraphsdk.GetDefaultClientOptions()
	defaultMiddleware := msgraphcore.GetDefaultMiddlewaresWithOptions(&clientOptions)

	allMiddleware := append(defaultMiddleware, azure.GetMiddlewares(azure.ServiceNameActiveDirectory)...)

	// Create an HTTP client with the middleware
	httpClient := khttp.GetDefaultClient(allMiddleware...)

	adapter, err := msgraphsdk.NewGraphRequestAdapterWithParseNodeFactoryAndSerializationWriterFactoryAndHttpClient(
		auth, nil, nil, httpClient)
	if err != nil {
		return nil, err
	}

	graphClient := msgraphsdk.NewGraphServiceClient(adapter)

	 
	result, err := graphClient.GroupSettings().Get(context.Background(), nil)
	if err != nil {
		return nil, err
	}

	groupSettingListV1 := make([]models.GroupSettingCollectionResponseable, 0)
	pageIterator, err := msgraphcore.NewPageIterator(result, c.adapter, models.CreateGroupSettingFromDiscriminatorValue) 
	if err != nil {
		return nil, err
	}

	err = pageIterator.Iterate(ctx, func(pageItem interface{}) bool {
		if app, ok := pageItem.(models.GroupSettingCollectionResponseable); ok {
			groupSettingListV1 = append(groupSettingListV1, app)
		} else {
			utilities.GetLogger().Error("Failed to parse the object")
			b, _ := json.Marshal(pageItem)
			// display the object
			utilities.GetLogger().Error(string(b))
		}
		return true
	})
	if err != nil {
		return nil, err
	}

	return groupSettingListV1, nil
}
```

![image](https://user-images.githubusercontent.com/99398851/235629335-b85a4ecc-65d6-4544-a954-a020bd1d0ac7.png)

BTW same issue with beta version of this API -[List directory setting](https://learn.microsoft.com/en-us/graph/api/group-list-settings?view=graph-rest-beta&tabs=http)

Other APIs are working fine with the same approach. Additionally tested it with [Group setting template API](https://learn.microsoft.com/en-us/graph/api/groupsettingtemplate-list?view=graph-rest-1.0&tabs=go) - it works fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57dfc134-20c0-9a9a-ca7a-2a57a341bb30
* Version Independent ID: 9c9bb940-47f8-5e8d-c544-3a081c0404a9
* Content: [List settings - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/group-list-settings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/group-list-settings.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @psaffaie
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @Anton-uptycs for raising this issue.

The [List settings API](https://learn.microsoft.com/en-us/graph/api/group-list-settings?view=graph-rest-1.0&tabs=go) won't return any data if you haven't [created any settings](https://learn.microsoft.com/en-us/graph/api/group-post-settings?view=graph-rest-1.0&tabs=http) first, and you create the setting based off a [groupSettingTemplate](https://learn.microsoft.com/en-us/graph/api/resources/groupsettingtemplate?view=graph-rest-1.0). The List settings API returns the settings in your tenant, which the setting templates are global in Azure AD. Please create a setting first for the API to return any data.

<img width="797" alt="image" src="https://user-images.githubusercontent.com/14026935/235711710-56e879db-505f-4a45-ae30-475fb9cacf9e.png">

**Comment by Anton-uptycs** [comment]
Hello @FaithOmbongi, first of all, I would like say thank you for your help, I managed to get information, thanks to your help.
I'm right to use this API to get information from this azure page?  I need to get the value of the field `Users can create security groups in Azure portals, API or PowerShell`. 
If it's correct then could you please navigate me what template and setting value name I should check for it? 
![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/99398851/58b68f98-1689-41e5-8d6e-d1ec7e06b79a)

**Comment by Anton-uptycs** [comment]
Thank you very much for your help @FaithOmbongi, and I hope the last question about it, on the same page "groups" > general, we have also these 3 fields `Owners can manage group membership requests in the Access Panel`, `Restrict user ability to access groups features in the Access Panel. Group and User Admin will have read-only access when the value of this setting is 'Yes'.` , and `Users can create Microsoft 365 groups in Azure portals, API or PowerShell` How can get them through the API?

**Comment by FaithOmbongi** [comment]
> Thank you very much for your help @FaithOmbongi, and I hope the last question about it, on the same page "groups" > general, we have also these 3 fields:
> 
> 1. `Owners can manage group membership requests in the Access Panel`
> 2. `Restrict user ability to access groups features in the Access Panel. Group and User Admin will have read-only access when the value of this setting is 'Yes'.`
> 3. `Users can create Microsoft 365 groups in Azure portals, API or PowerShell`
>    How can get them through the API?

Hi @Anton-uptycs - 

- No. 1 and 2 aren't available through the API.
- No. 3 is the `EnableGroupCreation` object in the group settings and groupSettingTemplate objects. For more information, you can review [Overview of group settings > Group.Unified > EnableGroupCreation](https://learn.microsoft.com/en-us/graph/group-directory-settings#:~:text=sites%20classification.-,EnableGroupCreation,-Boolean). Also refer to my initial response for how to configure it and other objects.

**Comment by Anton-uptycs** [comment]
Thank you very much @FaithOmbongi , I really appreciate your help!
