### ISSUE TITLE
getOffice365GroupsActivityDetail missing GroupGuid

### ISSUE THREAD

**Issue by ivanfioravanti** [microsoftgraph/microsoft-graph-docs#2114]
Issue: **getOffice365GroupsActivityDetail missing GroupGuid and reporting misleading information.**

This happens even in the portal. If there are multiple groups with same Display Name, it's impossible to discern between them. Can you please add Group Guid in Graph Reporting API? 

Article:https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/reportroot_getoffice365groupsactivitydetail

**Comment by ElizabethSamuel-MSFT** [comment]
@kszb : Please take a look

**Comment by jthake-msft** [comment]
This is a feature request. As per the issue template creation process, feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support

**Comment by NavaneethaDev** [comment]
Hi Jeremy,
Posted here. Thanks!
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/36444133-issue-getoffice365groupsactivitydetail-missing-gr

**Comment by wobba** [comment]
This has moved here: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/36444133-issue-getoffice365groupsactivitydetail-missing-gr and @jthake-msft, including the ID would be super useful when you get the reports and want to take action.

It's not uncommon for groups to have the same display name.
