### ISSUE TITLE
get error 301 when get profile with select since today

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2115]
This error started this morning. (beta still works)

```
GET https://graph.microsoft.com/v1.0/me?$select=mail,userPrincipalName
```
return error 301.

![image](https://user-images.githubusercontent.com/3375461/34687912-19bc2e04-f465-11e7-9848-4921560066fc.png)

client-request-id: b794c817-fc65-40dd-9e5c-0387ed744cdb
content-type: text/plain
cache-control: private
request-id: b794c817-fc65-40dd-9e5c-0387ed744cdb

**Comment by cincue** [comment]
Having the same problem

Here the full response including headers

> 
> *   Trying 137.117.96.109...
> * TCP_NODELAY set
> * Connected to graph.microsoft.com (137.117.96.109) port 443 (#0)
> * TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
> * Server certificate: graph.microsoft.com
> * Server certificate: Microsoft IT SSL SHA2
> * Server certificate: Baltimore CyberTrust Root
> 
> GET /v1.0/me HTTP/1.1
> Host: graph.microsoft.com
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer *******
> 
> HTTP/1.1 301 Moved Permanently
> Cache-Control: private
> Transfer-Encoding: chunked
> Content-Type: text/plain
> request-id: 8ca05e8a-5b4a-4b42-9422-29967d15e85b
> client-request-id: 8ca05e8a-5b4a-4b42-9422-29967d15e85b
> x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceA","Ring":"5","ScaleUnit":"003","Host":"AGSFE_IN_11","ADSiteName":"EST"}}
> 
> Duration: 185.5381
> Date: Mon, 08 Jan 2018 20:38:19 GMT
> 
> * Connection #0 to host graph.microsoft.com left intact

**Comment by marych** [comment]
The was a regression this morning for /v1.0/me requests. It was corrected and this should no longer be occurring.
