### ISSUE TITLE
Problem with special characters

### ISSUE THREAD

**Issue by plettb** [microsoftgraph/microsoft-graph-docs#2116]
I am using the Microsoft.Graph 1.7.0 NuGet package.  It seems to have trouble with special characters.  The following line, in which "graphClient" is an authenticated "GraphServiceClient":
`folder = await this.graphClient.Me.Drive.Root.ItemWithPath(path).Request().Expand(expandValue).GetAsync();`
will throw an exception if "path" contains a special character.  For example, if I have a OneDrive folder at the root named "C# Files", this call will fail.  So far the special characters I've found that cause failure are "#" and "%".

I assume I may be able to get around this with encoding, but I would think the API should handle that for me.

**Comment by amtlib-dot-dll** [comment]
As pointed out here https://stackoverflow.com/a/41623465 many of the special characters can be handled in this way, except the single quotation mark itself `'`. URLs like `https://graph.microsoft.com/v1.0/me/drive/root/children("text(a).abc")/content` does not work, only `https://graph.microsoft.com/v1.0/me/drive/root/children('text(a).abc')/content` works

**Comment by plettb** [comment]
I see this got closed, but there is no indication that it got dealt with in any way.  Did it get fixed?

**Comment by ernestotw85** [comment]
@plettb I had a similar issue and I found that graph do not support % and # but you can manually replace by %25 and %23 or just encode, other special characters are supported

**Comment by siriak** [comment]
I had this issue too, you have to **first** escape single quotation marks duplicating them and then apply URL encoding to the whole query
