### ISSUE TITLE
Update Operation Missing From AppRoleAssignmentTo Resource

### ISSUE THREAD

**Issue by timayabi2020** [microsoftgraph/microsoft-graph-docs#21171]
Update operation for appRoleAssignmentTo resource is missing from the documentation.
The only documented operations [here](https://learn.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0) are:

1. Get/List
2. Post
3. Delete
PATCH operation for this resource is available in the graph metadata.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/10947120/236038141-179268b1-be68-4ea4-ba73-f3bc28244d36.png">
The corresponding open API path for the above is "/servicePrincipals/{servicePrincipal-id}/appRoleAssignedTo/{appRoleAssignment-id}'"

**Comment by FaithOmbongi** [comment]
Hi @timayabi2020 - Unfortunately, I'm unable to verify that this method is supported or that it's valid. The Microsoft Graph schema doesn't include an annotation that the UPDATE operation is supported. And while testing, I'm getting a 400 Bad Request.

<img width="799" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/252f044d-c819-4bb4-9a07-fe8ad0f2677f">

<img width="514" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/759657ed-8ac4-4f01-bb2b-6fb1671a4c50">


Do you get a different result?
