### ISSUE TITLE
Invalid Powershell sample code

### ISSUE THREAD

**Issue by SylwiaMeier** [microsoftgraph/microsoft-graph-docs#21182]
The sample provided does not work, the following line requires an additional parameter:

$User = Get-MgUser -UserId $UserId **-Property EmployeeLeaveDateTime**

If the property parameter is not specified, Get-MgUser will return empty values. An alternative approach is to configure the MgProfile to use "beta" instead of "v1.0", e.g.:

 Select-MgProfile -Name **"beta"**

This caused me quite some headaches. Thanks for fixing it!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 46248f55-1aa5-6e84-d5de-1d058e60b068
* Version Independent ID: 46248f55-1aa5-6e84-d5de-1d058e60b068
* Content: [Set employeeLeaveDateTime - Microsoft Graph](https://learn.microsoft.com/en-us/graph/tutorial-lifecycle-workflows-set-employeeleavedatetime?tabs=http)
* Content Source: [concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/tutorial-lifecycle-workflows-set-employeeleavedatetime.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Hi @AlexFilipin - Can you help with this? Thanks.

**Comment by AlexFilipin** [comment]
Well it used to be correct I am not sure why it got changed, see https://github.com/microsoftgraph/microsoft-graph-docs/commit/8db7e05cfad23b1c920bbf02946d9bd96bffc8f5
