### ISSUE TITLE
pendingScopes is empty for some application requests

### ISSUE THREAD

**Issue by David-A-P** [microsoftgraph/microsoft-graph-docs#21235]
Hi,
We are testing the endpoint /identityGovernance/appConsent/appConsentRequests/, and in some cases we get the pendingScopes like

pendingScopes                     : {@{displayName=offline_access}, @{displayName=User.Read},
                                    @{displayName=Chat.ReadWrite}, @{displayName=Team.ReadBasic.All}...}

While in others is just empty. 

@odata.context                    : https://graph.microsoft.com/v1.0/$metadata#identityGovernance/appConsent/appConsent
                                    Requests/$entity
id                                : (...)
appId                             : (...)
appDisplayName                    : Calendar Pro
**pendingScopes                     : {}**
userConsentRequests@odata.context : (...)
userConsentRequests               : {}

The information we found is related with the fact the ConsentType is Static, but we don't know what does it mean.
Is there a way to retrieve the scopes via Graph for those applications with empty "pendingScopes"? When we do the admin consent from Azure's Admin Consent section, those applications are requesting permissions like the others.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6a6eeee-1a00-94a4-e256-0e4ed8254786
* Version Independent ID: 47b1327b-9760-3ca5-4321-1a1504061904
* Content: [List appConsentRequests - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/appconsentapprovalroute-list-appconsentrequests?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/appconsentapprovalroute-list-appconsentrequests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/appconsentapprovalroute-list-appconsentrequests.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by David-A-P** [comment]
@psignoret 
Thank you very much for your reply. 
I was able to retrieve the "InProgress" requests via Graph Explorer and also MGGraph cmdlet.
And yes, I can see all pending requests have the PendingScopes populated.
The only question is the meaning of ".default" value..., unless ".default" means any of the basic permissions, such as: User.Read, profile, opeind, offline_access  If that is not correct, how we can retrieve the requested permissions behind ".default" entry?
Thanks again.

**Comment by psignoret** [comment]
> The only question is the meaning of ".default" value..., unless ".default" means any of the basic permissions, such as: User.Read, profile, opeind, offline_access If that is not correct, how we can retrieve the requested permissions behind ".default" entry?

@David-A-P In an **appConsentRequest**, `.default` means "all API permissions configured in the app registration". You can see all of these permissions listed if you [build an admin consent URL](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent) with `scope=.default`, but there's no API available today to query this for an arbitrary multi-tenant app.

**Comment by David-A-P** [comment]
@psignoret  Thanks for the information. All clear now!
