### ISSUE TITLE
New-MgIdentityGovernanceAccessReviewDefinition_Create1: An error has occurred

### ISSUE THREAD

**Issue by Cardas26** [microsoftgraph/microsoft-graph-docs#21230]
I cannot get this Graph PowerShell commandlet to work. The error in the issue subject line appears with every attempt. Using the -debug parameter did not provide any additional information for troubleshooting. I am using this body and commandlet in PowerShell:

`
$params = @{
	displayName = "PIM review"
	descriptionForAdmins = "Review for some pim roles"
	descriptionForReviewers = "Review for some pim roles"
	scope = @{
		"@odata.type" = "#microsoft.graph.accessReviewQueryScope"
		query = "/roleManagement/directory/roleEligibilityScheduleInstances?$expand=principal&$filter=(isof(principal,'microsoft.graph.user') and roleDefinitionId eq '9c6df0f2-1e7c-4dc3-b195-66dfbd24aa8f')"
		queryType = "MicrosoftGraph"
	}
	settings = @{
		mailNotificationsEnabled = $true
		reminderNotificationsEnabled = $true
		justificationRequiredOnApproval = $true
		defaultDecisionEnabled = $false
		defaultDecision = "Deny"
		instanceDurationInDays = 25
		recommendationsEnabled = $true
		recurrence = @{
			pattern = @{
				type = "absoluteMonthly"
				interval = 3
			}
			range = @{
				type = "noEnd"
				startDate = "2023-06-01"
			}
		}
	}
}
`
New-MgIdentityGovernanceAccessReviewDefinition -BodyParameter $params

If I use the https command equivalent in graph explorer, it works:

POST https://graph.microsoft.com/beta/identityGovernance/accessReviews/definitions

Request Body:
`
{
    "displayName": "PIM review",
    "descriptionForAdmins": "Review for some pim roles",
    "descriptionForReviewers": "Review for some pim roles",
    "scope": {
        "@odata.type": "#microsoft.graph.accessReviewQueryScope",
        "query": "/roleManagement/directory/roleEligibilityScheduleInstances?$expand=principal&$filter=(isof(principal,'microsoft.graph.user') and roleDefinitionId eq '9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3')",
        "queryType": "MicrosoftGraph"
    },
…                "type": "absoluteMonthly",
                "interval": 3
            },
            "range": {
                "type": "noEnd",
                "startDate": "2023-06-01"
            }
        }
    }
}
`

If there was a typo in $params, I would expect the "Invalid Request" error. But this generic message "An error has occurred" doesn't tell me much. 

Can you assist?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85cb3eb7-6a19-bb7d-e0fe-f7d793680a36
* Version Independent ID: 4bbaa69b-d41e-6290-acdb-35eb06ffb9d3
* Content: [Create definitions - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/accessreviewset-post-definitions?view=graph-rest-beta&tabs=powershell)
* Content Source: [api-reference/beta/api/accessreviewset-post-definitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/accessreviewset-post-definitions.md)
* Product: **governance**
* Technology: **microsoft-graph**
* GitHub Login: @jyothig123
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Cardas26** [comment]
Any news on this?

**Comment by Cardas26** [comment]
Hello?

**Comment by timayabi2020** [comment]
@Cardas26 thank you for identifying and reporting this issue. I replicated the issue and found out that the problem is actually in the SDK. I have logged an issue [here](https://github.com/Azure/autorest.powershell/issues/1173) on the SDK's code generator repository. Once it has been resolved, we will publish a release with changes that resolves this issue.
Meanwhile, below is an alternative that you may wish to explore.

1.  Connect to graph with AccessReview.Read.All scope. i.e. Connect-MgGraph -Scope "AccessReview.Read.All".
2. Run the script below
$url = "https://graph.microsoft.com/beta"
$object = "microsoft.graph.group"
$body = @{
  "descriptionForAdmins" = "Review for some pim roles"
  "descriptionForReviewers" = "Review for some pim roles"
  "displayName" = "PIM review"
  "scope" = @{
    "query" = "/roleManagement/directory/roleEligibilityScheduleInstances?$expand=principal&$filter=(isof(principal,'microsoft.graph.user') and roleDefinitionId eq '9c6df0f2-1e7c-4dc3-b195-66dfbd24aa8f')"
    "queryType" = "MicrosoftGraph"
    "@odata.type" = "#microsoft.graph.accessReviewQueryScope"
  }
  "settings" = @{
    "defaultDecision" = "Deny"
    "defaultDecisionEnabled" = $false
    "instanceDurationInDays" = 25
    "justificationRequiredOnApproval" = $true
    "mailNotificationsEnabled" = $true
    "recommendationsEnabled" = $true
    "reminderNotificationsEnabled" = $true
    "recurrence" = @{
      "pattern" = @{
        "type" = "absoluteMonthly"
        "interval" = 3
      }
      "range" = @{
        "type" = "noEnd"
        "startDate" = "2023-06-01"
      }
    }
  }
}
 
$accessReview = Invoke-MgGraphRequest -Uri "$url/identityGovernance/accessReviews/definitions" -Method POST -ContentType "application/json" -Body $body -StatusCodeVariable StatusCodeVariable
 
if($StatusCodeVariable -eq 201){

Write-Host "Success"
}else{
Write-Host "Failed"
}

**Comment by Cardas26** [comment]
I'm afraid the alternative methods errors out with the same message on my side (see below). Thanks for addressing this, I will await the SDK fix.

Invoke-MgGraphRequest: 
Line |
  32 |  … essReview = Invoke-MgGraphRequest -Uri "$url/identityGovernance/acces …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | POST https://graph.microsoft.com/beta/identityGovernance/accessReviews/definitions
HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 6070e5fe-90b4-4d3b-b0dc-bf1bf2f5fe6b
client-request-id: 6070e5fe-90b4-4d3b-b0dc-bf1bf2f5fe6b
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"005","RoleInstance":"AM4PEPF00025BE9"}}       
Link: <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:customData&from=2021-06-01&to=2021-07-01>;rel="deprecation";type="text/html", <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:customData&from=2021-06-01&to=2021-07-01>;rel="deprecation";type="text/html", <https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=beta,PrivatePreview:customData&from=2021-06-01&to=2021-07-01>;rel="deprecation";type="text/html"
Deprecation: Thu, 03 Jun 2021 23:59:59 GMT
Sunset: Sat, 03 Jun 2023 23:59:59 GMT
Date: Mon, 05 Jun 2023 12:11:50 GMT
Content-Type: application/json
Content-Encoding: gzip

{"error":{"code":"","message":"An error has occurred.","innerError":{"date":"2023-06-05T12:11:51","request-id":"6070e5fe-90b4-4d3b-b0dc-bf1bf2f5fe6b","client-request-id":"6070e5fe-90b4-4d3b-b0dc-bf1bf2f5fe6b"}}}
Failed

**Comment by timayabi2020** [comment]
@Cardas26 Apologies, I forgot to escape "$" on the query options with backticks.
Replace "/roleManagement/directory/roleEligibilityScheduleInstances?$expand=principal&$filter=(isof(principal,'microsoft.graph.user') and roleDefinitionId eq '9c6df0f2-1e7c-4dc3-b195-66dfbd24aa8f')" with the one below
====================================================
"/roleManagement/directory/roleEligibilityScheduleInstances?`$expand=principal&`$filter=(isof(principal,'microsoft.graph.user') and roleDefinitionId eq '9c6df0f2-1e7c-4dc3-b195-66dfbd24aa8f')" and try again.

**Comment by timayabi2020** [comment]
@Cardas26  I got a response on the issue I had logged with the code generators. On your request body please escape any "$" on the query options with backticks and try again.  I have tried it and it worked.
<img width="855" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/10947120/a6d2b556-704b-48c4-8078-40b3a5b46d6b">
