### ISSUE TITLE
Create User Documentation Omits Clarification of 'usageLocation'

### ISSUE THREAD

**Issue by danieldjewell** [microsoftgraph/microsoft-graph-docs#21263]
When creating a new user (via a POST to `[...]/users`), the `usageLocation` property is not set by default. While not strictly required for new user creation (the API endpoint *did* work without it)... I was unable to subsequently use the `assignLicense` [endpoint](https://learn.microsoft.com/en-us/graph/api/user-assignlicense?view=graph-rest-1.0&tabs=http)

The end result was that I had to run a PATCH against each new user to update the `usageLocation` property (i.e. `{"usageLocation": "US"}`) 

While I'm sure there are cases where `usageLocation` should be null/empty, the documentation should be clarified that if one intends to immediately assign a license after creation, this property needs to be included. (It's not even clear *if* other properties **can** be included in the original `POST`...)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-post-users.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jconley76** [comment]
@danieldjewell the requirement for specifying the usage location before assigning a license is documented here: 
[https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Ffundamentals%2Flicense-users-groups%3Fcontext%3D%252Fazure%252Factive-directory%252Fenterprise-users%252Fcontext%252Fugr-context%23available-license-plans&data=05%7C01%7Cjercon%40microsoft.com%7C85f34995bdbf412ade5208db5307d1c5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638195065402621369%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7K06Zq099hEwMCwLD358eEhNOe9tjUolApA2n6cm%2BF0%3D&reserved=0](url)

**Comment by danieldjewell** [comment]
@jconley76 Yes, that's documented clearly ... but not as part of the API documentation. Nor is there a link (or even mention, that i can see) in the API documentation *alerting* a developer to the information/fact that `usageLocation` needs to be set. (I suppose a larger question for the MS Graph API team is: *Why would `usageLocation` not be a required parameter when creating a new user object*?...    

If a developer is reading the API documentation it is (and remains) completely unclear that the `usageLocation` needs to be set.

I don't believe it's an acceptable response to say that something Graph API-related is documented in the Azure AD fundamentals documentation.... The issue still exists.
