### ISSUE TITLE
Restrict the App Permission Scope to specific channel

### ISSUE THREAD

**Issue by Raj-MCITP** [microsoftgraph/microsoft-graph-docs#21273]
Do we have an option to restrict the Application Permission Scope to specific channel, like how the application access policy option available for exchange online ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b32ca7f9-ea75-d0fd-f887-136e0c9686e3
* Version Independent ID: 6e9b24bc-9869-0b70-8881-3c4aad2bebed
* Content: [Protected APIs in Microsoft Teams - Microsoft Graph](https://learn.microsoft.com/en-us/graph/teams-protected-apis)
* Content Source: [concepts/teams-protected-apis.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/teams-protected-apis.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @Raj-MCITP - Thanks for raising your query.
We will check on it and let you know the updates.

**Comment by sayali-MSFT** [comment]
@Raj-MCITP - Application permissions in the Graph API cannot be restricted - once you grant them, they cover the entire tenant. For specific workloads, additional controls exist that do allow you to restrict access, i.e., Application Access Policies for Exchange Online, or the recently announced support for [RBAC for Applications](https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-public-preview-of-role-based-access-control-for/ba-p/3688228). For SharePoint Online, we have the Sites.Selected scope, allowing you to limit access to specific site collections. Those controls however only apply for the specific workload, and the Graph API as a whole does not support scoping for application scenarios yet.

**Comment by Raj-MCITP** [comment]
Hi Sayali, Thank you for the details. Since other workloads having an option to limit the scope, pls bring one to Microsoft Teams. Read Channel Messages All is a over privilege for an app who wants to read message from single channel for their automation.

**Comment by sayali-MSFT** [comment]
@Raj-MCITP -Could you please help by suggesting this feature on - [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472)

**Comment by lramosvea** [comment]
Hi everyone, closing this issue since this forum is for documentation issues only. For feature requests, please use [Microsoft Teams · Community](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472), as suggested above. Appreciate your feedback.
