### ISSUE TITLE
How to download reference attachment in messages

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2129]
Hello,

The attachment APIs in graph seems only support getting file attachment content.
Is any way to download the reference attachment in messages?

BTW, size in get-reference-attachment request is wrong
```
GET /users/{id | userPrincipalName}/events/{id}/attachments/{id}
```
```
{
            "@odata.type": "#microsoft.graph.referenceAttachment",
            "id": "xxx",
            "lastModifiedDateTime": "2018-01-10T02:21:43Z",
            "name": "xxx.png",
            "contentType": "image/png",
            "size": 870,      //??? what is this?
            "isInline": true
}
```

thank you!

**Comment by jasonjoh** [comment]
The beta API adds the properties you need. `sourceUrl` gives the URL you can use to download the attachment.

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/referenceattachment

**Comment by joewutaiwan** [comment]
@jasonjoh ,

thanks for the reply,
I can successfully download the image and text file, but **_online docs._**
But **_the return size is not correct_** for the downloaded file
How can I check the file integrity?

Thank you,
Joe

**Comment by jasonjoh** [comment]
Ah I see what you mean. I reproduce this as well. I'll check with my engineering folks.

**Comment by jasonjoh** [comment]
Mods you can assign this to me :)

**Comment by jasonjoh** [comment]
@joewutaiwan I chatted with our devs, and the value in `size` for a reference attachment is computed from the size of the metadata stored in the attachment table on the message, which is a fairly unimportant bit of information for a Graph app. The real size of the attachment isn't available from the email store as it could change at any time.

I'll submit a PR to fix up the docs with this bit of detail.

**Comment by joewutaiwan** [comment]
Hi @jasonjoh ,

Thanks for the reply,
So now the size is for reference only.

But how about the online docs?
Is possible to download from source url?

**Comment by jasonjoh** [comment]
I would assume that you could do a GET on the `sourceUrl`. Is that not the case?

**Comment by joewutaiwan** [comment]
Hi @jasonjoh ,

Yes, I could do a GET on the `sourceUrl` .
But if it is an `Online doc` like `onenote` or `pdf`,  is it possible to download the real file?
Using the GET will return a webpage instead of a real file.

Thanks!

**Comment by abhishek1401** [comment]
Hi there,
Is there any way download whole email as .eml format?
