### ISSUE TITLE
SharePoint list - provided @odata.nextLink results in Error 500

### ISSUE THREAD

**Issue by kumbol** [microsoftgraph/microsoft-graph-docs#2130]
Hi. It seem's there's an issue happening now at paging results from SharePoint lists. The URL provided in @odata.nextLink doesn't work, resulting in Error 500 (generalException). 

I'm using a following query:

`https://graph.microsoft.com/beta/sites/[site URL],[site ID]/lists/[list ID]/items?expand=fields`

The first page of results comes in correctly, and the @odata.nextLink contains a following URL:

`https://graph.microsoft.com/beta/sites/[site URL],[site ID]/lists/[list ID]/items?expand=fields&$skiptoken=Paged%3dTRUE%26p_ID%3d205`

Unfortunately, using it results in:
`
{
    "error": {
        "code": "generalException",
        "message": "An unspecified error has occurred.",
        "innerError": {
            "request-id": "f7e33c22-15b5-4aac-b928-31c1a2bf04ae",
            "date": "2018-01-11T09:48:57"
        }
    }
}`

This happens using both the beta and 1.0 endpoint.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
