### ISSUE TITLE
Inconsistency in FindMeetingTimes API response

### ISSUE THREAD

**Issue by jakubbares** [microsoftgraph/microsoft-graph-docs#2131]
I am not satisfied with the  FindMeetingTimes API responses I get. 
The first problem is I get only three out of five results that are valid and contain a location. Others have location empty.
The second problem is when I increase the from-to search range I get even less results and two of the previous results are not included.
This is really weird.

**Comment by JuForan** [comment]
These should be assigned to @Charlie Chung<mailto:crchung@microsoft.com>

**Comment by maulikshah87** [comment]
Hi ,
I am facing issue while calling findmeeting times api .

I am using this API to check Room Avaialability for given time duration . As a attendees i have pass all the room  email address to check availability . Here I am attaching  error response which i recevied from graph. I have tried both Beta and V 1.0 Version 

{"statusCode":500,"code":"ErrorInternalServerError","message":"An internal server error occurred. The operation failed.","requestId":"3ecb6c3c-96e6-426c-b3c8-257d0e519444","date":"2018-02-13T06:52:35.000Z","body":{"code":"ErrorInternalServerError","message":"An internal server error occurred. The operation failed.","innerError":{"request-id":"3ecb6c3c-96e6-426c-b3c8-257d0e519444","date":"2018-02-13T06:52:35"}}}
=========================================================
{"statusCode":500,"code":"ErrorInternalServerError","message":"An internal server error occurred. The operation failed.","requestId":"4e3459b3-2c92-499a-a501-65e1279a3632","date":"2018-02-13T06:43:38.000Z","body":{"code":"ErrorInternalServerError","message":"An internal server error occurred. The operation failed.","innerError":{"request-id":"4e3459b3-2c92-499a-a501-65e1279a3632","date":"2018-02-13T06:43:38"}}}
======================================================
{"statusCode":500,"code":"ErrorInternalServerError","message":"An internal server error occurred. The operation failed.","requestId":"5774549d-68d9-4756-98bd-2c3af438b547","date":"2018-02-13T06:01:27.000Z","body":{"code":"ErrorInternalServerError","message":"An internal server error occurred. The operation failed.","innerError":{"request-id":"5774549d-68d9-4756-98bd-2c3af438b547","date":"2018-02-13T06:01:27"}}}


Thanks

**Comment by snobu** [comment]
I can repro that as well:

```
POST https://graph.microsoft.com/beta/me/findMeetingTimes
```
Payload:
```json
{
  "attendees": [
    {
      "emailAddress": {
        "address": "bob@swearjarbank.onmicrosoft.com",
        "name": "Bob Loblaw Attorney at Law"
      },
      "type": "Required"
    }
  ],
  "timeConstraint": {
    "timeslots": [
      {
        "start": {
          "dateTime": "2018-03-28T08:49:17.136Z",
          "timeZone": "Pacific Standard Time"
        },
        "end": {
          "dateTime": "2018-04-04T08:49:17.136Z",
          "timeZone": "Pacific Standard Time"
        }
      }
    ]
  },
  "locationConstraint": {
    "isRequired": "false",
    "suggestLocation": "true",
    "locations": [
      {
        "displayName": "Conf Room 32/1368",
        "locationEmailAddress": "conf32room1368@imgeek.onmicrosoft.com"
      }
    ]
  },
  "meetingDuration": "PT1H"
}
```

Response:
```
{
    "error": {
        "code": "ErrorInternalServerError",
        "message": "An internal server error occurred. The operation failed.",
        "innerError": {
            "request-id": "68549143-a8c8-4f33-9f44-9a35d621e350",
            "date": "2018-03-28T09:12:00"
        }
    }
}
```

Is this a temporary glitch in the API or is there a recent breaking change introduced in /beta?

**Comment by distracteddev** [comment]
@crchung-MSFT I am also receiving 500 errors for some users (and not others). Is this the correct place to receive support for this? If not, could you please direct me to how I can get support for this issue?

**Comment by si87** [comment]
i'm also facing this issue. Error Message is not very helpful.

```
{ error: 
   { code: 'ErrorInternalServerError',
     message: 'An internal server error occurred. The operation failed.',
     innerError: 
      { 'request-id': '5b5f5ccb-d7b5-429b-9c00-27f665acbfbd',
        date: '2018-05-07T09:25:02' } } }
`
``

for some users the api is working, for some users not.

**Comment by arunmohandas196** [comment]
Facing similiar error mentioned above.
Detail description in :https://github.com/microsoftgraph/microsoft-graph-docs/issues/2746

Facing inconsistent behaviour for some users, where timeConstraint property only works when passed start/end dateTime excluding a certain time interval from currentDate and consistently gives below error response.

`{ "error": { "code": "ErrorInternalServerError", "message": "An internal server error occurred. The operation failed.", "innerError": { "request-id": "392ddb83-d4cd-4715-a9c6-2cbfd581920c", "date": "2018-06-07T07:45:45" } } }`

**Comment by jnlkds** [comment]
So... when I make a request and leave the locations blank, it only provides three results, when we have lots more locations (i.e., conference rooms).  How do we get more than three?
Using the following query only provides a list of three resources, when I would like it to provide more locations.  How can we increase the number of locations?

    {
      "attendees": [
      ],
      "timeConstraint": {
        "timeslots": [
          {
            "start": {
              "dateTime": "2018-06-25T12:45:00.000Z",
              "timeZone": "Pacific Standard Time"
            },
            "end": {
              "dateTime": "2018-06-25T22:39:07.097Z",
              "timeZone": "Pacific Standard Time"
            }
          }
        ]
      },
      "locationConstraint": {
        "isRequired": "true",
        "suggestLocation": "true",
        "locations": [
        ]
      },
      "meetingDuration": "PT30M",
        "returnSuggestionReasons": "true",
      "maxCandidates": "4",
        "minimumAttendeePercentage": "100"
    }

BTW: if you fill in the locations block, it appears as though the API does NOT take this into account.  If the resources get listed as resources in the "attendees" block, then it looks for only a meeting when all resources are available.

**Comment by nikunj2712** [comment]
@jnlkds Were you able to make this work? I am also receiving empty locations array. Here is the request body.
`{
  "attendees": [
    {
      "emailAddress": {
        "address": "Nikunj.Bhagat@outlook.com",
        "name": "Nikunj"
      },
      "type": "Required"
    }
  ],
  "timeConstraint": {
    "timeslots": [
      {
        "start": {
          "dateTime": "2018-07-27T19:26:33.701Z",
          "timeZone": "Pacific Standard Time"
        },
        "end": {
          "dateTime": "2018-08-03T19:26:33.701Z",
          "timeZone": "Pacific Standard Time"
        }
      }
    ]
  },
  "locationConstraint": {
    "isRequired": "false",
    "suggestLocation": "true",
    "locations": [
      {
        "displayName": "Conf Room 32/1368",
        "locationEmailAddress": "conf32room1368@imgeek.onmicrosoft.com"
      }
    ]
  },
  "meetingDuration": "PT1H"
}`

Here is one of the suggestion I get in response with empty locations.
`{
            "confidence": 100,
            "organizerAvailability": "free",
            "meetingTimeSlot": {
                "start": {
                    "dateTime": "2018-07-30T13:00:00.0000000",
                    "timeZone": "UTC"
                },
                "end": {
                    "dateTime": "2018-07-30T14:00:00.0000000",
                    "timeZone": "UTC"
                }
            },
            "attendeeAvailability": [],
            "locations": []
        }`


Let me know if you were able to fetch available locations.
Thanks.

**Comment by jnlkds** [comment]
Yes,  I got it working.
However, as noted above, it ONLY provides 3 responses. 
In your request, clear the locations field NOT to have any locations.

**Comment by nikunj2712** [comment]
@jnlkds Still same after changing locations. Also tried removing `locations` key too, doesn't help.
```
 "locationConstraint": {
    "isRequired": "false",
    "suggestLocation": "true",
    "locations": []
  }
```

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
