### ISSUE TITLE
Clarify user roles when updating extension properties

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#21336]
**For this section:**

#### Permissions and privileges

_The same privileges that your app requires to read from or write to a resource instance are also required to manage any extensions data on that resource instance. For example, for an app to update any user's profile with custom app data, the app must have been granted the User.ReadWrite.All Microsoft Graph permission._

We don't mention anything about the role that the user needs to be in (for a delegated permission).
So if it's a delegated permission, the signed-in user must be in an appropriate role that allows read or write to the resource instance.  In the example given, this would be the User Administrator Role.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9ba2e9-2111-5815-e18b-1158eb9140d2
* Version Independent ID: 22d7b10f-f484-8b91-98da-39aa63478dd6
* Content: [Add custom data to resources using extensions - Microsoft Graph](https://learn.microsoft.com/en-us/graph/extensibility-overview?tabs=http)
* Content Source: [concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/extensibility-overview.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @dkershaw10 for calling this out. Yes, you're right. So I've raised a PR to add a note about this.
