### ISSUE TITLE
Not able to find postAsync in c# code snippet in messages structure

### ISSUE THREAD

**Issue by vchiluka5** [microsoftgraph/microsoft-graph-docs#21367]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96c52956-2c53-b7c9-755e-6692535564cf
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/chatmessage.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nivedipa-MSFT** [comment]
@vchiluka5 - Thanks for reporting your issue. We will check this and update you soon.

**Comment by ChetanSharma-msft** [comment]
Hello @vchiluka5 - Could you please share the details, so that we can further investigate on this issue?

**Comment by vchiluka5** [comment]
Hey Sorry for late response and thanks for following up

i was talking about this link
https://learn.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=csharp

in this, c# code snippet,

// Code snippets are only available for the latest version. Current version is 5.x

var graphClient = new GraphServiceClient(requestAdapter);

var requestBody = new ChatMessage
{
	Body = new ItemBody
	{
		Content = "Hello World",
	},
};
var result = await graphClient.Teams["{team-id}"].Channels["{channel-id}"].Messages.PostAsync(requestBody);

There is no method "PostAsync" in structure Messages. I got AddAsync() which kindof does the same which unblocked me.

**Comment by Nivedipa-MSFT** [comment]
@vchiluka5 - as @andrueastman said the[ PostAsync](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/2ff102c8861bb709cbde5611073c2efbc0be5100/src/Microsoft.Graph/Generated/Teams/Item/Channels/Item/Messages/MessagesRequestBuilder.cs#L79) method is present in V5 and above which the snippets show. However, the AddAsync method is present for earlier versions before version 5.

**Comment by Nivedipa-MSFT** [comment]
@vchiluka5 - We are closing this issue for now. Please feel free to reopen if required.

**Comment by vchiluka5** [comment]
I believe we were using master branch but anyway as shelved that particular task for now. Thanks for quick replies :-). We can close it for now.
