### ISSUE TITLE
CallRecords datetime format inconsistency.

### ISSUE THREAD

**Issue by cagrimunyas** [microsoftgraph/microsoft-graph-docs#21376]
When analyzing call records, I noticed inconsistencies in the datetime format for the properties whose type is datetime ( e.g StartDateTime, EndDateTime, etc. ), which is supposed to follow the ISO 8601 standard mentioned in the documentation. The digit accuracy varies across different records. Some instances of 'StartDateTime' property from different CallRecords: 

2023-05-18T12:29:12.0605236+00:00
2023-05-18T06:46:41.5815661+00:00
2023-05-18T08:40:56.41277+00:00
2023-05-17T06:32:16+00:00

All these show that 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 171dc858-defb-6ffb-1f66-3d4d691a6f1c
* Version Independent ID: 14cd7a2a-a5ca-772f-d398-5a7124029878
* Content: [callRecord resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/callrecords-callrecord.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @mcm223
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mcm223** [comment]
@cagrimunyas Thank you for the notification. Could you provide some recent example Call IDs showing this discrepancy to help accelerate our investigation?

**Comment by cagrimunyas** [comment]
@mcm223 it's customer data. Can you share your msft alias so I can send you over Teams.

**Comment by mcm223** [comment]
@cagrimunyas mamcgrath@

**Comment by mcm223** [comment]
@cagrimunyas Thanks for your patience as I looked into this. I met with our API architects and they clarified that we generally follow RFC 3339 for datetime formatting. Fractional seconds are optional in that spec and have no set level of precision. Based on that, this behavior is working as expected.
