### ISSUE TITLE
group: checkMemberGroups permission documentation bug

### ISSUE THREAD

**Issue by harrisb** [microsoftgraph/microsoft-graph-docs#2137]
Issue: 
group: checkMemberGroups documentation page has "Not supported" permission everywhere
Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group_checkmembergroups.md#permissions

**Comment by jamescro** [comment]
Thanks for calling this to our attention. The fix for this should be published by tomorrow.

**Comment by jamescro** [comment]
This is fixed now.
