### ISSUE TITLE
[Outlook][calendar] import calendar in office365

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2138]
Hi all,

About import ICS file to office365, here are two questions:

1. The import seems not applies UTC time format in EXDATE and RECURRENCE-ID
```
EXDATE:20180103T093000Z
...
RECURRENCE-ID:20180104T093000Z
```
It works with window desktop application outlook, so I think something goes wrong in office 365.

--
2. RRULE only return partial date in UNTIL field
```
"start" : {
            "dateTime" : "2018-01-02T09:30:00.0000000",
            "timeZone" : "UTC"
         },

"recurrence" : {
            "pattern" : {
               "dayOfMonth" : 0,
               "daysOfWeek" : [],
               "firstDayOfWeek" : "sunday",
               "index" : "first",
               "interval" : 1,
               "month" : 0,
               "type" : "daily"
            },
            "range" : {
               "endDate" : "2018-01-06",
               "numberOfOccurrences" : 0,
               "recurrenceTimeZone" : "Taipei Standard Time",
               "startDate" : "2018-01-02",
               "type" : "endDate"
            }
         },
```
start and recurrence are in different precisions.

--

Thank you for help!

**Comment by JuForan** [comment]
Please assign all github issues to @Charlie<mailto:crchung@microsoft.com>

**Comment by joewutaiwan** [comment]
Hi @crchung-MSFT 

Do you have any updates on this issue?

thanks!

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
