### ISSUE TITLE
Upload Session returning 400 Bad Request

### ISSUE THREAD

**Issue by Herz3h** [microsoftgraph/microsoft-graph-docs#2139]
Hello, 

Issue: Trying to [create an upload session
](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_createuploadsession) but it keeps returning 400 Bad Request : 

```
{
    "error": {
        "code": "invalidRequest",
        "message": "The request is malformed or incorrect.",
        "innerError": {
            "request-id": "facd8841-329f-4066-a075-869b0ccabf1e",
            "date": "2018-01-15T13:34:40"
        }
    }
}
```

Here is the JSON Body I'm sending along the request : 

```
{
  "item": {
    "@microsoft.graph.conflictBehavior": "replace",
    "name": "largefile"
  }
}
```

I've tried different urls : 

`POST /me/drive/root:/:/createUploadSession
`
`POST /me/drive/items/PARENT_FOLDER_ID_HERE/createUploadSession
`
`POST /sites/root/drive/items/PARENT_FOLDER_ID_HERE/createUploadSession
`
None of the above worked for me.

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_createuploadsession

Any idea ?

**Comment by euregio-systems** [comment]
I used /drives/{driveID}/items/{parentID}:/{fileName}:/createUploadSession and it works ;)

**Comment by Herz3h** [comment]
Today it seems it is working..

Very strange, tried about 10 different paths, and none worked yesterday, now it's responding with a url.

**Comment by cristian-vescan** [comment]
Hello,
I'm also receiving the same error if I specify both `"@microsoft.graph.conflictBehavior": "replace"` and `"name": "largefile"`.
If I specify only `"@microsoft.graph.conflictBehavior": "replace"` it works fine.
I think the issue should be reopened
