### ISSUE TITLE
Wrong application permission documented for user: getMemberGroups

### ISSUE THREAD

**Issue by Liversage** [microsoftgraph/microsoft-graph-docs#2140]
On the page for [user: getMemberGroups](../blob/master/api-reference/v1.0/api/user_getmembergroups.md) the `User.ReadBasic.All` permission is in the application permissions list . I do not believe that `User.ReadBasic.All` is an application permission. It is only a delegated permission as far as I can tell. However, as I'm quite new to this API I might have overlooked something obvious so I'm raising this as an issue instead of making a pull request.

**Comment by jamescro** [comment]
Thanks for bringing this to our attention. You are correct that User.ReadBasic.All is only available as a delegated permission.
This fix should be published by tomorrow.

**Comment by Liversage** [comment]
I was interested in the permissions required to call `user: getMemberGroups` because I have an Azure AD application that has to query Microsoft Graph to determine the groups an AD user is member of. Based on the (now updated) documentation I was unable to do this. I had to open a support case in Azure and the support engineer told med that I need the following application permissions as displayed in the Azure Portal:

- Read all users' full profiles
- Read and write directory data
- Read all groups

I believe these maps to the following application permissions:

- `User.Read.All`
- `Directory.ReadWrite.All`
- `Group.Read.All`

At the time of writing the updated documentation on `user: getMemberGroups` contains this information about required application permissions:

> Permissions (from least to most privileged)
> Group.Read.All, Directory.Read.All, Directory.ReadWrite.All

Am I looking in the wrong place for what application permissions I need to give to my Azure AD application to perform Microsoft Graph queries because Azure AD has stricter permission requirements than Microsoft Graph in general?

(Also, I find it surprising that my application requires write permissions to the entire AD to be able to query group membership but that is not relevant to this issue.)

**Comment by jamescro** [comment]
Thanks for noting this discrepancy. The documentation should be in sync with the guidance you got from Azure. I'm following up with someone from that group to make sure that we nail this down more precisely.

**Comment by jamescro** [comment]
We've gotten a fix for this from the product team.
