### ISSUE TITLE
GetAsync method for List Teams is missing in the SDK 5

### ISSUE THREAD

**Issue by ErikdeWilde** [microsoftgraph/microsoft-graph-docs#21423]
If updated the nugets and in the new version the list all teams in an organization is missing the GetAsync method and only has the PostAsync

var graphClient = new GraphServiceClient(requestAdapter);
await graphClient.Teams.GetAsync();

 Microsoft.Graph Version=5.11.0
 Microsoft.Graph.Beta  Version=5.30.0-preview

This does work in the versions

 Microsoft.Graph Version=4.54.0
 Microsoft.Graph.Beta  Version=4.72.0-preview
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 798ded8d-f70e-c9f8-0782-4083422b8c85
* Version Independent ID: 54678d54-44a6-d935-443e-e64a48b1ef0b
* Content: [List teams - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/teams-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/teams-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/teams-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akhilkohlimicrosoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @ErikdeWilde  - Thanks for raising your query.
We will look into it and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@ErikdeWilde - This looks related to the metadata change related to the change at the link below. The intention was to remove the method only for v1 but this is missing in beta as well now. https://github.com/microsoftgraph/msgraph-metadata/issues/237. 

Engineering team has raised an issue for the beta metadata to be fixed for beta. However, it is not expected that the path should exist for V1.

https://github.com/microsoftgraph/msgraph-metadata/issues/356

**Comment by Meghana-MSFT** [comment]
https://github.com/microsoftgraph/msgraph-metadata/issues/356 has been merged and closed. Could you please let us know if we can close this thread?

**Comment by ErikdeWilde** [comment]
@Meghana-MSFT I works in both version now, thanks!
