### ISSUE TITLE
How to call macros using azure api

### ISSUE THREAD

**Issue by istiaqiut** [microsoftgraph/microsoft-graph-docs#2143]
I have an excel file in containg around 100K rows in onedrive. This file contains some macros. I want to run these macros using api for example 

 **https://graph.microsoft.com/beta/me/drive/root:/book1.xlsx:/workbook/tables/{id|name}**

Here, I want to call my macros function in place tables/{id|name}
Any way to do this?
Thanks

**Comment by jamescro** [comment]
Have you looked at the Excel functions documentation here?

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/workbook

Look under the "Functions" header.

**Comment by istiaqiut** [comment]
These are the functions. I want to call macros like that.

**Comment by jamescro** [comment]
I've checked with the product team and confirmed that, unfortunately, you can't currently run macros with the REST API.
