### ISSUE TITLE
updateMobileAppIdentifierDeployments  and updateTargetedSecurityGroups  are not working.

### ISSUE THREAD

**Issue by adison88** [microsoftgraph/microsoft-graph-docs#2144]
Hi,

I'm trying to run following APIs and they're still failing with following response with 400

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_mam_iosmanagedappprotection_updatemobileappidentifierdeployments

`{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'updateMobileAppIdentifierDeployments'.",
        "innerError": {
            "request-id": "6a5ecebe-9356-45bd-a8f4-c306e097db13",
            "date": "2018-01-17T15:25:46"
        }
    }
}`

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_mam_iosmanagedappprotection_updatetargetedsecuritygroups

`{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'updateTargetedSecurityGroups'.",
        "innerError": {
            "request-id": "c1b7c3f8-2783-4e53-a1fa-efe9a43550d6",
            "date": "2018-01-17T04:13:12"
        }
    }
}`

Please let me know if anything in APi has changed recently.

Issue: 

Article:

**Comment by BrucePerlerMS** [comment]
Thanks for the heads up. I'm looping in the developer I work with for his take. Will keep you posted. 
~ Bruce

**Comment by alemeshetalemu** [comment]
@adison88 

**Apps:** Here is a sample request to update list of targeted apps. 

POST https://graph.microsoft.com/beta/deviceAppManagement/iosManagedAppProtections('T_f3b0a6f1-d2be-4747-9817-7f9e46267faa')/**targetApps**

{"apps":[{"mobileAppIdentifier":{"@odata.type":"#microsoft.graph.iosMobileAppIdentifier","bundleId":"com.microsoft.office.excel"}}]}

**Groups:** Here is a sample request to update list of assigned groups

POST https://graph.microsoft.com/beta/deviceAppManagement/iosManagedAppProtections/T_b710416e-27e9-4820-a1d4-2c5bb7bef364/assign
{"assignments":[{"target":{"groupId":"8b68c4a6-c4a6-8b68-a6c4-688ba6c4688b","@odata.type":"#microsoft.graph.groupAssignmentTarget"}}]}

Thanks,
Alemeshet Alemu from MSFT
