### ISSUE TITLE
Missing properties of contact resource object

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2151]
Hi,

I found some information that I can't get from graph api. (https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/contact)

Here are the missing properties of contact resource object.

1. mobilePhone: We can insert two records in mobilePhone field, but the api only responses the first one.
2. Personal web page
3. School
4. Hobbies
5. Location
6. Anniversary

Is it a bug or should I use another api to get these information?
Thanks a lot.

**Comment by judithting** [comment]
Hi,

I found the following contact information can't get from graph api too.

1. Phone -> Other -> Other
2. Phone -> Other -> Pager
3. Phone -> Other -> Business fax
4. Phone -> Other -> Home fax
5. Phone -> Other -> Other fax
6. Phone -> Other -> Organization main
7. Phone -> Other -> Assistant
8. Phone -> Other -> Callback
9. Phone -> Other -> Radio
10. Phone -> Other -> Telex
11. Phone -> Other -> tty/tdd

Is there any way to get those information?
Thanks a lot.

**Comment by jasonjoh** [comment]
@judithting you're right that the Graph doesn't expose all of these fields. The data is there on the server, stored in various MAPI properties. You an always access arbitrary MAPI properties via [extended properties](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/extended-properties-overview).

The first step is to figure out which MAPI property you need. All of the various MAPI properties used by Outlook and Exchange are documented in [MS-OXPROPS](https://msdn.microsoft.com/en-us/library/cc433490(v=EXCHG.80).aspx), which is a huge document, so I recommend using it in conjunction with a more specific document based on the item type you're working with. In your case, the relevant doc would be [MS-OXOCNTC](https://msdn.microsoft.com/en-us/library/cc463907(v=exchg.80).aspx).

In addition, I'd recommend getting [MFCMapi](https://github.com/stephenegriffin/mfcmapi/releases/latest), which is a tool you can run on a machine with Outlook installed to connect to your mailbox and explore all of the MAPI properties on an item. This makes it a lot quicker to find the property you need.

So first the good news: the [beta version of the contact entity](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/contact) changes how it exposes phone numbers, so some of these fields will be directly accessible via the `phones` property. It won't cover all of those though, especially the ones where you can have more than one (mobile, home, etc.)

For the ones that you still can't get to, you need to access via extended properties. Here's an example using one of the properties you mentioned: the mobile phone. In Outlook on the web, we can add two mobile phones. I've done that on a test contact here:

![image](https://user-images.githubusercontent.com/8966342/35284810-bf205d64-0029-11e8-88fa-476a557b59d2.png)

Now if I run MFCMapi, open my mailbox, and navigate to Root Container->Top of Information Store->Contacts, then double-click Contacts to see the contents, I can locate my test contact. With it selected, the bottom part of the window shows me all of the MAPI properties. Looking through the values, I can find the property that holds what I'm looking for. In this case as it happens, MFCMapi tells me the property is `PR_CAR_TELEPHONE_NUMBER`:

![image](https://user-images.githubusercontent.com/8966342/35285230-cf135518-002a-11e8-8923-efc698512473.png)

The really nice thing is that it also gives me the info I need to get this from Graph without even having to worry about looking this up in MS-OXPROPS or MS-OXOCNTC: the **Tag** and **Type**. In this case the **Tag** is `0x3A1E001E`, and **Type** is `PT_STRING8`. We need the "high" bits of **Tag** (`0x3A1E`) and an idea of what the **Type** means (in this case it's a fairly safe guess it's a string) to construct the query format for an extended property:

```
String 0x3A1E
```

Plugging that into an `$expand` clause in the request URL (as mentioned [here](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/singlevaluelegacyextendedproperty_get)), gives us:

```
GET /me/contacts?$expand=singleValueExtendedProperties($filter=id eq 'String 0x3A1E')
```

And the contact in the response has this additional property:

```
"singleValueExtendedProperties": [
  {
    "id": "String 0x3a1e",
    "value": "555-2222"
  }
]
```

**Comment by joewutaiwan** [comment]
Hi @jasonjoh 

How to get Custom properties between 0x8000 and 0xFFFE ?

For example:
```
Tag: 0x8126001E
Type: PT_STRING8
DASL: http://schemas.microsoft.com/mapi/id/{00062004-0000-0000-C000-000000000046}/80E9001E
Named Prop Name: id: 0x80E9=33001
Named Prop Guid: {00062004-0000-0000-C000-000000000046} = PSETID_Address
```

What will the query look like in
```
GET /me/contacts?$expand=singleValueExtendedProperties(???)
```

Thanks!

**Comment by joewutaiwan** [comment]
Hi @jasonjoh 

After post for a while, I figured it out!
```
GET /me/contacts?$expand=singleValueExtendedProperties
($filter=id eq 'String {00062004-0000-0000-C000-000000000046} Id 0x80E9')
```

Thanks

**Comment by jasonjoh** [comment]
Yep, that's it! If the **tag** is over 0x8000, it's a MAPI named property, and you have to use either the GUID + ID syntax as you saw there, or a GUID + Name syntax, depending on how the property is defined in MS-OXPROPS.

**Comment by judithting** [comment]
@jasonjoh I see. Thanks for your help.
By the way, can I use the same pair of Type and Tag to get Mobile 2 from different O365 account?

**Comment by jasonjoh** [comment]
Yes, it is the same.

**Comment by judithting** [comment]
@jasonjoh
Got it. Thanks for your detailed and easy to understand explanation.
I really appreciate it.
