### ISSUE TITLE
Sharepoint PHA applications need to set symmetric keys with a password to replace MSOL PS commands

### ISSUE THREAD

**Issue by westleyMS** [microsoftgraph/microsoft-graph-docs#21510]
We have been told that we need to update the scripts we are using to the new graph scripts, but they don't quite do what the old scripts did.

I am not sure if they require the base64 encode, but SP might require it, which would mean we need a way to set it instead of relying on the auto-generated one. Here is the code in our current article-

$bytes = New-Object Byte[] 32
$rand = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$rand.GetBytes($bytes)
$rand.Dispose()
$newClientSecret = [System.Convert]::ToBase64String($bytes)
$dtStart = [System.DateTime]::Now
$dtEnd = $dtStart.AddYears(3)
New-MsolServicePrincipalCredential -AppPrincipalId $clientId -Type Symmetric -Usage Sign -Value $newClientSecret -StartDate $dtStart  -EndDate $dtEnd
New-MsolServicePrincipalCredential -AppPrincipalId $clientId -Type Symmetric -Usage Verify -Value $newClientSecret   -StartDate $dtStart  -EndDate $dtEnd
New-MsolServicePrincipalCredential -AppPrincipalId $clientId -Type Password -Usage Verify -Value $newClientSecret   -StartDate $dtStart  -EndDate $dtEnd
$newClientSecret

[Article here](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in)

I have been trying to use a combo of Add-MgServicePrincipalPassword  and Add-MgServicePrincipalKey

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb011a0-dc99-d162-3f2a-d84c002ef2e7
* Version Independent ID: 10adc564-dbbb-6688-07c1-8576727990be
* Content: [application: addKey - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-addkey?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-addkey.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-addkey.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by westleyMS** [comment]
also, I have been getting permission issues when trying to add a key-
Add-MgServicePrincipalKey : Insufficient privileges to complete the operation.

Here are the scopes I get on connect-
    Connect-MgGraph -Scopes "Application.ReadWrite.All","AppRoleAssignment.ReadWrite.All","ServicePrincipalEndpoint.ReadWrite.All","Directory.ReadWrite.All"

Here is what Graph says it needs-
[Link to addkey doc](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-addkey?view=graph-rest-1.0&tabs=http)

**Comment by madansr7** [comment]
@westleyMS You need to create a PATCH request on the app and send your base64 symmetric key generated with a pwd. MS Graph does not have a provision to generate symmetric keys with a pwd, so that's something you would need to do outside of the MS Graph call. 
Sample payload for the PATCH call would look something like: 
```
{
            "displayName": "SymKey",
            "endDateTime": "2023-06-09T00:00:00Z",
            "key": "WmFUGdV.....=",
            "startDateTime": "2023-06-05T00:00:00Z",
            "type": "Symmetric",
            "usage": "Verify"
}

Curious to know why could you not use client secrets or x509 certs?
```

**Comment by westleyMS** [comment]
So we don't have a command to do this?
This is a product requirement for SharePoint add-ins. I can patch it, but the old tools did this for you, and this is an ongoing maintenance procedure for admins managing their PHA credentials. We should add a way to do this with a command. The code will be much more cumbersome if we need to make an httpclient call. Can we add a switch to the command?
Here is the current documentation-
https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in

**Comment by FaithOmbongi** [comment]
Hi @westleyMS @madansr7 - Because this issue relates to the larger effort to help customers migrate from MSOL -> Microsoft Graph PS cmdlets, I'll close this issue here and start an internal thread.
