### ISSUE TITLE
Service principal description

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#21514]
When calling

    GET https://graph.microsoft.com/v1.0/servicePrincipals

`description` and `appDescription` properties are `null` for all `servicePrincipal` objects.

Does user/app need some specific permission to see `description` and `appDescription`?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d9a1dcc-0e0d-e5ba-8fa3-ad0289803a52
* Version Independent ID: bccef64c-675b-364e-30f6-5c1310fef8bd
* Content: [List servicePrincipals - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/serviceprincipal-list.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by madansr7** [comment]
@MartinM85 you don't need any special permissions. However the description properties aren't shown in Azure portal and hence most apps created via UI would start with null descriptions. If you update the description via MS Graph API or via the manifest page in portal, then it should start to show up in the payload.

**Comment by madansr7** [comment]
I realize we do not have description property in the portal. Taking an action here to raise this as an issue for the team internally.
