### ISSUE TITLE
[Outlook] how to distinguish between shared mail box user and normal user

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2152]
Hi all,

When I created a shared mailbox, the system will automatically add a new user.

In graph API I found something like: **_provisionedPlans_** or **_assignedLicenses_** may indicate that.

I want to know how to distinguish between shared mailbox user and normal user

thx!

**Comment by ArkaGPL** [comment]
Same issue here, I'm unable to distinguish an user from a shared mailbox using the graph api.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
