### ISSUE TITLE
authMethods property not being refreshed properly from Azure AD

### ISSUE THREAD

**Issue by JohnDCCIU** [microsoftgraph/microsoft-graph-docs#21522]
I've successfully been using _credentialUserRegistrationDetails_ to retrieve information on the MFA status for a given user, but sometime around May 31 it stopped reflecting new changes in Azure AD in the _authMethods_ property.  The JSON retrieval itself works fine with no errors, but the _authMethods_ property shows the value from before May 31(ish).  New changes to the user's authMethods are not reflected in the JSON.

I'm aware of MVP recommendations in the Learn Q&A that I could use _/users/{id | userPrincipalName}/authentication/methods_, but _credentialUserRegistrationDetails_ should be working and I shouldn't have to rework my code due to this thing failing to refresh its data, unless it's being deprecated and everyone should stop using it, but I don't see that said anywhere.

### **Example 1**
User1 before May 31 had "mobileSMS" method configured, but not "appCode".  User1 added "appCode" on June 1.

Azure AD console _User_ > _Authentication_ Methods now shows:
```
Usable authentication methods
Authentication method / Detail
Phone number / Primary mobile: +1 <redacted>
Software OATH token (Preview) / 083a4d45-5c1f-4576-a5e2-<redacted>
```

MS Graph API Call to _credentialUserRegistrationDetails_ now shows (_authMethods_ property is missing "appCode"):
```{"@odata.context":"https://graph.microsoft.com/beta/$metadata#reports/credentialUserRegistrationDetails","value":[{"id":"9cabc2b3-aec8-491c-90d2-<redacted>","userPrincipalName":"User1@domain.com","userDisplayName":"User1First User1Last","isRegistered":false,"isEnabled":false,"isCapable":false,"isMfaRegistered":true,"authMethods":["mobilePhone"]}]}```

### **Example 2**
User2 before May 31 had no methods configured.  User2 added "appCode" on June 1.

Azure AD console _User_ > _Authentication_ Methods now shows:
```
Usable authentication methods
Authentication method / Detail
Software OATH token (Preview) / 3e177a88-5a79-4e16-bb52-<redacted>
```

MS Graph API Call to _credentialUserRegistrationDetails_ now shows (_authMethods_ property is empty, is missing "appCode"):
```{"@odata.context":"https://graph.microsoft.com/beta/$metadata#reports/credentialUserRegistrationDetails","value":[{"id":"6095837e-fa0c-4db0-8c46-<redacted>","userPrincipalName":"User2@domain.com","userDisplayName":"User2First User2Last","isRegistered":false,"isEnabled":false,"isCapable":false,"isMfaRegistered":false,"authMethods":[]}]}```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8238a381-7421-a45f-8972-d71e23a3a380
* Version Independent ID: 35235db8-2017-ff94-1574-ec10671a7ba9
* Content: [credentialUserRegistrationDetails resource type - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/resources/credentialuserregistrationdetails?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/credentialuserregistrationdetails.md)
* Product: **identity-and-access-reports**
* Technology: **microsoft-graph**
* GitHub Login: @besiler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @JohnDCCIU for raising this issue. Unfortunately, this forum is only for documentation-related issues but functionality issues like this are investigated through [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-governance.html). Please file this issue there and provide the request IDs so it can be investigated. Closing this issue here.
