### ISSUE TITLE
@odata:nextLink is sometimes not present when paginating through Outlook mail even if there is more mail

### ISSUE THREAD

**Issue by sathoro** [microsoftgraph/microsoft-graph-docs#2153]
We are syncing user's Outlook accounts by paginating through the `/me/messages` endpoint in chronological order. Sometimes the API response will not include `@odata:nextLink` even if there are more messages. We are just using the `$top`, `$select`, `$skip`, and `$orderby` parameters.

For example, one account was paginated up to about 25,000 emails and then there was no `@odata:nextLink` but the emails returned were over 6 months old so it was clear there were more emails since it is an active account. When I changed the `$skip` parameter to a higher number the API showed newer emails and then correctly returned a `@odata:nextLink` in the response. Also we have the `$top` set to 100 but in the response missing a nextLink only 19 emails were returned (despite the emails being returned being over 6 months old and there being many newer emails), so there is some sort of gap in the messages being returned.

Calling the URL `https://graph.microsoft.com/v1.0/me/messages?%24top=100&%24select=id%2CreceivedDateTime%2Csubject%2CbodyPreview%2Cfrom%2CtoRecipients%2CisDraft%2Csender&%24skip=23352&%24orderby=receivedDateTime+asc` returns 19 emails from 2017-06-16 and there is no `@odata:nextLink` in the response. Calling the same URL but with 24352 as the `$skip` parameter (skipping 1,000 ahead) returns 100 emails from 2017-06-17 to 2017-06-20 and has a `@odata:nextLink` in the response so it is clear there actually were more emails and a `@odata:nextLink` should have been present in the first response.

Please let me know if I am doing something wrong or if there is a way we can work around this, thank you!

**Comment by sathoro** [comment]
After further investigation, this appears to only happen when the `$orderby` is present

**Comment by jasonjoh** [comment]
@sathoro Can you post the response headers from a request that does not contain the `nextLink`? If so I'll file this as a bug with our engineering team to investigate.

**Comment by sathoro** [comment]
@jasonjoh I found another account has over 100,000 emails but a simple query with `$orderby=receivedDateTime asc` does not return a `nextLink` (even without a `$skip`) and does not return any emails. The request without the `$orderby` does return a `nextLink`. Also this behavior isn't consistent across all Outlook accounts, it seems to be pretty random as far as when a `nextLink` is returned and not.

Response headers with the `$orderby` and no `nextLink`:

    {
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"South Central US\",\"Slice\":\"SliceA\",\"Ring\":\"5\",\"ScaleUnit\":\"001\",\"Host\":\"AGSFE_IN_11\",\"ADSiteName\":\"SAN\"}}",
        "status": "200",
        "content-length": "203",
        "content-location": "https://graph.microsoft.com/v1.0/me/messages?%24top=100&%24select=id%2CreceivedDateTime%2Csubject%2CbodyPreview%2Cfrom%2CtoRecipients%2CisDraft%2Csender&%24orderby=receivedDateTime+asc",
        "transfer-encoding": "chunked",
        "request-id": "66ccd93a-98bc-47f0-a05f-f6588c104ea4",
        "vary": "Accept-Encoding",
        "duration": "541.8586",
        "-content-encoding": "gzip",
        "client-request-id": "66ccd93a-98bc-47f0-a05f-f6588c104ea4",
        "cache-control": "private",
        "date": "Wed, 24 Jan 2018 17:12:38 GMT",
        "odata-version": "4.0",
        "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"
    }

Response headers with no `$orderby` and a correct `nextLink`:

    {
        "x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"South Central US\",\"Slice\":\"SliceA\",\"Ring\":\"5\",\"ScaleUnit\":\"001\",\"Host\":\"AGSFE_IN_37\",\"ADSiteName\":\"SAN\"}}",
        "status": "200",
        "content-length": "95907",
        "content-location": "https://graph.microsoft.com/v1.0/me/messages?%24top=100&%24select=id%2CreceivedDateTime%2Csubject%2CbodyPreview%2Cfrom%2CtoRecipients%2CisDraft%2Csender",
        "transfer-encoding": "chunked",
        "request-id": "14da0d36-96a9-4481-a24f-a2594a4f954d",
        "vary": "Accept-Encoding",
        "duration": "1802.1905",
        "-content-encoding": "gzip",
        "client-request-id": "14da0d36-96a9-4481-a24f-a2594a4f954d",
        "cache-control": "private",
        "date": "Wed, 24 Jan 2018 17:17:41 GMT",
        "odata-version": "4.0",
        "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"
    }

**Comment by jasonjoh** [comment]
Thanks. I've pushed this info to the right folks, will update here if I get any further info.

**Comment by sathoro** [comment]
@jasonjoh Thank you :+1:

**Comment by sathoro** [comment]
@jasonjoh Hey I'm wondering if there is any update on this? We are going to need to work around this very soon

**Comment by jasonjoh** [comment]
The team has this on the backlog for investigation, but I don't have a timeline for when that might be concluded. However, from looking at what you're doing, it seems like you're manually syncing by pulling all the results and maybe comparing?

As a workaround, you might try using a [delta query](https://developer.microsoft.com/en-us/graph/docs/concepts/delta_query_messages) to do your syncing. That way you only get changes and your result set should be much smaller (after initial sync), hopefully avoiding this issue.

**Comment by sathoro** [comment]
For the initial sync we are paginating through the results from oldest to newest messages until there are none left (which would normally mean we have gotten all the messages). Then when our webhook gets called we sync the new messages by starting where we left off and paginating through until there are no more messages. We use the same method for our Gmail sync and it works great.

Does the delta query work for all messages or do you have to call it for each folder? We would like to get sent messages and all received messages no matter what folder they are in from a single query

**Comment by jasonjoh** [comment]
So no, delta only work on a folder level, it doesn't work on the `/me/messages` endpoint. However, you can also do delta query on the /me/mailfolders collection, so you can keep your client up-to-date with what mailfolders exist on the server.

The advantages of delta query over what you're currently doing (as I understand it) is:

- After initial sync, you only sync deltas, so processing is theoretically quicker. I don't know how you're determining your "cutoff" point, but with delta you don't have to handle that yourself.
- In addition to new messages, you would also get updates to existing messages, deletes, etc.

So the basic approach would be:

Initial sync:

- Do delta query on `/me/mailfolders` to get full folder list. Once done, save the deltaLink
- For each folder, do delta query on `/me/mailfolders/{id}/messages` to get full message list, save deltaLink for each folder.

Webhook gets notification:

- Check `parentFolderId` of message from notification.
- Find the corresponding saved deltaLink for that folder
- Do new delta query using that deltaLink to get just changes to just that folder.
- If you don't have a folder saved with that ID, there's likely a new folder, so redo your mailFolder sync with the saved deltaLink for folders.

**Comment by sathoro** [comment]
Currently we don't need the additional functionality that the delta query provides so for now I think we will keep it a bit simpler. But thank you for your comment because in the future if we do want updates on messages that will be helpful.

So what we are currently doing is paginating through `/me/messages?$orderBy=receivedDateTime+asc` from `$skip=0`, then `$skip=100` (or whatever the `$nextLink` is), and on until there are no messages returned. When there is a new message we simply call the URL again that previously didn't return anything and that catches us up, and then we store the `$nextLink`. It works great (in theory) because syncing each inbox is almost always just a single API call.

I think what we will do is just remove the `$orderBy` (since it appears that `$orderBy=receivedDateTime+asc` isn't supported), store the last `receivedDateTime` and then do `$filter=receivedDateTime+gt+{value}` when a new message comes in to catch us up. Do you think that would work?

**Comment by jasonjoh** [comment]
Filtering by `receivedDateTime` will likely work, though you should probably keep an offset on the times to account for differences in how times are represented on the server and in the API. Times are stored with much greater precision on the server, where the API goes only to the millisecond. This can cause some edge cases where items get missed because they are technically less than the time you set in your filter, but would have been rounded up by the API. 

My suspicion is that delta queries would scale better than this method, so depending on how often you are "syncing" and against how many mailboxes, this might be something to benchmark.

**Comment by sathoro** [comment]
Thank you that is good to know, we will offset by a second then and make sure duplicates are handled appropriately. 

Do you think filtering by the time won't scale as well because the API call will be slow? We are only syncing when a change actually happens and it would only be a single API call (unless somebody sends/receives over 100 messages since the last sync) so from my end it seems like it would be fine but I do want to make sure I understand your concerns on how it will scale.

**Comment by jasonjoh** [comment]
It was more a concern of hitting the server with multiple distinct searches fairly quickly, it sounds like you may not be doing that so it probably isn't as big of a concern :).

If you're doing it that way, why not just get the specific item that caused the notification to your webhook? The ID is included, so you could simplify even further :)

**Comment by manishgadhock** [comment]
While filtering by receivedDateTime, i found the same issue (wasn't able to get the @odata:nextLink in the api when i have more messages left). 

When i am calling
https://graph.microsoft.com/v1.0/users/me/messages?$filter=receivedDateTime+ge+2018-02-04T10:49:38Z

I am getting 27 mails only and after that there is no mails as there is no @odata:nextLink

https://graph.microsoft.com/v1.0/users/me/messages?$filter=receivedDateTime+ge+2018-02-22T10:49:38Z

I am getting 150 mails. 

What I want is, to get all the mails from somedate upto today.

I have also tried this  : 

https://graph.microsoft.com/v1.0/users/me/messages?$filter=receivedDateTime+ge+2018-02-22T10:49:38Z+and+receivedDateTime+le+2018-03-01T10:49:38Z

But it gives the same issue. Kindly help me with this.

**Comment by vajanishant** [comment]
@jasonjoh 
Getting same issue with this api call:
https://graph.microsoft.com/v1.0/me/messages?$top=1&$filter=receivedDateTime+gt+2018-01-25T09:52:12.000Z
It sends @odata.nextlink when i am making post request on https://developer.microsoft.com/en-us/graph/graph-explorer or in postman but when i am making this api call from my code it gives me all data except @odata.nextlinlk

please help me. 
Thanks.

**Comment by sathoro** [comment]
@jasonjoh It turns out 1) this doesn't work reliably even without the `$orderBy` so I'm not even clear on a straightforward way to do an initial sync of somebody's mailbox and 2) filtering by `receivedDateTime` is not working 100% of the time either (some emails have been getting skipped in our sync process, even when doing a 1 second offset)

**Comment by nmalzieu** [comment]
Hi @jasonjoh I'm having the exact same issue and am unable to do the inital sync of emails for an account.
I'm filtering this way and ordering via received date time : `$orderby=ReceivedDateTime+asc&$filter=ReceivedDateTime ge 2016-11-18T17:57:35.000Z` 
This query gives me 0 email and no nextLink. But if I change 35 to 38 (hence looking a bit more into the future) I have results ! How come ? Can you help ? Here is the full URL : 

`https://outlook.office.com/api/v2.0/me/messages?$select=From,CcRecipients,ToRecipients,ReceivedDateTime,ConversationId,Subject,Id&$orderby=ReceivedDateTime+asc&$filter=ReceivedDateTime ge 2016-11-18T17:57:38.000Z&top=50`

**Comment by mlafleur** [comment]
I can't speak to the `35` vs `38` (Jason is well beyond me when it comes to Outlook/Exchange), but I could of things worth noting:

1. You shouldn't need to append `+asc` to your `$orderby`. It will sort the results by ascending values by default. I highly doubt it will affect your results at all, but it does make for a slightly easier to read URI. 

2. You don't need to be that granular with `DateTime` values. I rarely specify beyond `hh:mm`. For example, Microsoft Graph will happily consume `2016-11-18T17:57Z` as your `DateTime` value.

**Comment by nmalzieu** [comment]
@mlafleur  Thanks a lot for your answer. Actually, I tried with and without the `+asc` already, it doesn't change anything.
As for the `DateTime` value, the only reason why I'm so granular is that I give the `DateTime` value of the last email I fetched in order to get all emails coming after this one. Of course I could round this value but it shouldn't change anything right ?

**Comment by sathoro** [comment]
@jasonjoh Would it be possible for you to provide a method for reliably syncing an inbox without resorting to using delta queries for individual folders? I think this is a very common use case and would be great to include in the documentation

**Comment by nmalzieu** [comment]
@jasonjoh indeed, I'm looking to get all the messages and it would make my code much more complicated if I had to go through all the folders : 
- I would need to get the list of folders
- I would have to keep a delta token for each folder
- A message can be in multiple folders, I would also have to handle that

**Comment by dorshemer** [comment]
Just stumbled upon this issue, have the exact some problem.
@jasonjoh, a delta query on `/me/messages` would be extremely useful for me as well, for the exact same reasons @nmalzieu detailed.

**Comment by sathoro** [comment]
@jasonjoh Yeah, our app just wants to sync all emails and doesn't care about folders. Having to keep folders up to sync and do syncing on a folder-basis way over complicates things. Let's say we want to sync a user's inbox every 10 minutes if there was a change in that 10 minute period. That would only require a single query to the `/me/messages` endpoint if it worked properly. How many queries would that require in your delta query example? I think it would be N queries where N is the number of folders that changed. Plus the possibility of having to re-sync the folders if there is a new one, which again our app doesn't even use folders.

On a related note, I just realized that message IDs will change when an email is moved to a different folder. In the webhook notification it only notifies us of the new message ID. How are we supposed to update the old message stored in our database with the new ID - if we don't have the old ID to cross-reference our database? Will we have to use delta queries for that as well?

**Comment by jasonjoh** [comment]
Thanks guys. I've asked (again) for the dev team to please investigate this :). There's obviously a problem here somewhere.

@nmalzieu: Just a point of clarification, technically a message cannot be in multiple folders. You can copy a message into another folder, but they are technically different messages at that point.

@dorshemer: I'd suggest filing a feature request for delta on the `/me/messages` endpoint on [User Voice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis). I don't think there are any current plans to do this.

@sathoro: 

- Yep, understood about the complexity. I would recommend any app that uses delta on multiple folders pair that solution with subscriptions to those folders. That way, instead of syncing every 10 minutes, you could sync a particular folder whenever you get a notification for that folder. Way less requests that way :). (And to be clear, I'm not trying to push you that way, just sharing information).
- On the message ID changing: yes, this is because of what I pointed out above: moving a message basically copies the message to the new folder and deletes the original, causing a new ID to be created. Are you saying that you only get a "created" for the new ID, and no corresponding "deleted" for the old ID?

**Comment by sathoro** [comment]
@jasonjoh 

> That way, instead of syncing every 10 minutes, you could sync a particular folder whenever you get a notification for that folder. Way less requests that way :)

It would actually be more requests that way, and would mean that if the webhook failed we would lose the update. We just mark that account as needing to be synced and then do the syncing later in the background. So if they got 5 emails in 10 minutes then it is 1 request vs 5 requests.

> Are you saying that you only get a "created" for the new ID, and no corresponding "deleted" for the old ID?

Ah okay, we do not have a webhook subscription for the deleted change type. However, this still presents a bit of a problem. Our app has references to that particular email in our database. So if we delete the old one and create a new one that would be lost. Is there any reliable way to be able to reference the same email when the ID changes, so we can just make an update in our database with the new ID?

**Comment by jasonjoh** [comment]
> Is there any reliable way to be able to reference the same email when the ID changes, so we can just make an update in our database with the new ID?

Not currently.

**Comment by sathoro** [comment]
@jasonjoh I think the `conversationId` doesn't change and the email headers in `internetMessageHeaders` shouldn't change either right? So you could probably do something like `uniqueId = hash(conversationId + internetMessageHeaders.toString())`. Since most email clients will set a unique `Message-Id` and `Date` header I imagine that would be pretty good

**Comment by gokulnathk** [comment]
@jasonjoh I think delta also not working as expected. Since, I tried the delta endpoint to get the SentItem data of a user. That user have around 1500 emails in his SentItem, but the delta returns only 50 items.

`https://graph.microsoft.com/v1.0/users/admin@test.com/mailFolders/{SentFolderId}/messages/delta?$top=50`

This is the API call I'm using to get the mails

> {
> 	"cache-control": "private",
> 	"content-type": "application\/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
> 	"request-id": "5137c25e-ee90-4636-b8d9-64a5068a6e63",
> 	"client-request-id": "5137c25e-ee90-4636-b8d9-64a5068a6e63",
> 	"x-ms-ags-diagnostic": "{\"ServerInfo\":{\"DataCenter\":\"East US\",\"Slice\":\"SliceA\",\"Ring\":\"5\",\"ScaleUnit\":\"003\",\"Host\":\"AGSFE_IN_8\",\"ADSiteName\":\"EST\"}}",
> 	"preference-applied": "odata.track-changes",
> 	"odata-version": "4.0",
> 	"duration": "124.1115",
> 	"strict-transport-security": "max-age=31536000",
> 	"date": "Fri, 15 Jun 2018 10:48:52 GMT",
> 	"connection": "close"
> }

For your reference I have included the response header.

**Comment by rickyk586** [comment]
Pulling from each folder separately seems to return all emails `https://graph.microsoft.com/v1.0/me/mailFolders/{folderId}/messages`

**Comment by lsnider** [comment]
Think I figured it out.  Curious if it works for others.  Try dropping the $top parameter.  It *seems* like rather then $top controlling how many items to return in each request, it controls how far the API will look through the available items before suggesting it's at the end of the list.

**Comment by sathoro** [comment]
@jthake-msft Was this issue closed because the original problem has been resolved?

The comment above about dropping the `$top` parameter is for the `/messages/delta` endpoint which is different from the original problem on the `/me/messages` endpoint.

Can you confirm that either:

1) dropping the `$top` parameter on the `/me/messages` endpoint is a work around for this bug
2) the bug has been fixed

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.

**Comment by sathoro** [comment]
@jthake-msft I did [post the same question](https://stackoverflow.com/questions/48347666/odatanextlink-is-sometimes-not-present-when-paginating-through-outlook-mail-ev) on StackOverflow with the `microsoft-graph` tag in January and it has gone unanswered. Can you pass it along to the dedicated team you have mentioned? Thanks.
