### ISSUE TITLE
Confusion on Throttling Information for Change Notifications

### ISSUE THREAD

**Issue by bpandit-everlaw** [microsoftgraph/microsoft-graph-docs#21558]
The throttling information for Microsoft Change Notifications as mentioned at https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks?tabs=http#throttling is a little confusing. 

Specifically the last sentence of this section states "Notifications are dropped if the throttled endpoint slow percentage is greater than or equal to 15%.". In the context of a throttled app, does this mean that no retries are performed for notifications that have an unsuccessful delivery on first attempt? Otherwise, I read it as, no notifications (new or old) will be delivered as soon as the slow percentage reaches 15%. 

Does the 15% cutoff also mean that if my service is down (so the slow percentage is 100), the app will be throttled, and notifications will start to drop off immediately afterwards? Also, once the app is throttled, notifications won't be retried for upto 4 hours, they will be retried per the throttling policy, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8126c38b-f6ce-b473-7c9f-dff6cf966946
* Version Independent ID: 8126c38b-f6ce-b473-7c9f-dff6cf966946
* Content: [Receive change notifications through webhooks - Microsoft Graph](https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks?tabs=http)
* Content Source: [concepts/change-notifications-delivery-webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/change-notifications-delivery-webhooks.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by keylimesoda** [comment]
Updating this documentation here:  https://github.com/microsoftgraph/microsoft-graph-docs/pull/22011

To answer your question directly, once a service reaches 15% no-response over a 10-minute window, notifications will be dropped and will not be redelivered.

Below is the relevant part of the update:  

=======
1. An endpoint will be marked "slow" once more than 10% of responses take longer than 3 seconds in a 10-minute window.
      - Once an endpoint has been marked "slow", any new notifications will be sent on a 10 second delay.
      - An endpoint will exit "slow" state once less 10% of responses take longer than 3 seconds in a 10-minute window.

2. An endpoint will be marked "drop" once more than 15% of responses take longer than 3 seconds in a 10-minute window.
      - **Once an endpoint has been marked "drop", any new notifications will be dropped, for up to 10 minutes**
      - An endpoint will exit "drop" state once less than 15% of responses take longer than 3 seconds in a 10-minute window.


#### Retry
Once change notifications service has received a 2xx class code from your endpoint, a notification is considered sent and will not be tried again.

As long as the change notifications service receives any other HTML response in a timely manner (within 3 seconds), the service will continue to try to deliver the notification for up to 4 hours.
