### ISSUE TITLE
Graph Explorer does not support the Edu Graph APIs.

### ISSUE THREAD

**Issue by mjfusa** [microsoftgraph/microsoft-graph-docs#2156]
Issue:  
Bottom of page directs dev to use the Graph Explorer to try the Edu APIs. However, the Graph Explorer currently does not support this.  

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/education-overview

**Comment by jthake-msft** [comment]
@garethj-msft is this being looked at?

This is a feature request out side of scope of docs improvements.

As per the issue template creation process, feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support
