### ISSUE TITLE
DisplayName Reports not readable

### ISSUE THREAD

**Issue by miriamht** [microsoftgraph/microsoft-graph-docs#2157]
Issue: https://graph.microsoft.com/beta/reports/getYammerActivityUserDetail(period='D7') 
Returns for the User Principal Name and the Display Name properties a string of 32 charachters. Example:
Report Refresh Date,User Principal Name,Display Name,User State,State Change Date,Last Activity Date,Posted Count,Read Count,Liked Count,Assigned Products,Report Period
2018-01-21,8534B5299C82560FF54340D4018AF368,47271E821628B160A91D87CF8088D983,active,2017-08-23,2018-01-21,2,107,0,OFFICE 365 ENTERPRISE E5 WITHOUT AUDIO CONFERENCING+Microsoft Stream+Microsoft PowerApps,7

In October the User Principal Name and the Display Name were still readable. Can you please explain what the 32 charachter strings mean? Or return the readable Display Name or User Principal Name?

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/reportroot_getyammeractivityuserdetail

Thank you,

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
