### ISSUE TITLE
[Graph] how to define throttle control

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2161]
Hi all,

I am building a backup app for all user in an office 365 domain.
And now I am going to add a throttle control for this app, 
stopping to send request when receiving some error codes, like
```
429 | Too Many Requests
```
In this point, I want to know the mechanism of this error.
Should I add throttle control to this app or the capacity is maintained in every specific user?
Or I can add on service level? (E.g: control on Onedrive and emails and calendars)

Thanks.

Joe

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
