### ISSUE TITLE
[Outlook] how to handle SyncStateNotFound when get delta

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2162]
Hi all,

I found that when I traverse **_nextLink_** for mails to the end, the former **_nextLink_** will gradually turn to `SyncStateNotFound`.
```
The sync state generation is not found; generation=518;[highest=523][523][521][522].
```
So in this circumstance, how should I handle this error?
Should I assign token to empty and re-perform a full sync?
Or should I reuser the last **_deltaLink_** for recover this?

BTW, I found a document for this error, but I dont know whether it is valid for this API
```
SyncStateNotFound |
The sync state for the device was unexpectedly missing.
It might have disappeared while the request was in progress.
The next request will likely answer a sync key error 
and the device will be forced to do full sync.<44>
```
link 
http://interoperability.blob.core.windows.net/files/MS-ASCMD/[MS-ASCMD]-090715.doc

Thanks,

Joe

**Comment by jasonjoh** [comment]
Please post the response headers from a request that returns the bad `nextLink`. I'll forward it to engineering to investigate.

**Comment by joewutaiwan** [comment]
Hi @jasonjoh ,

Really thank you for help,

Here is the information

request:
`https://graph.microsoft.com/v1.0/users/464d152f-fda5-47ac-a05e-367002229986/mailFolders/AAMkADUxNDkxMmIzLTY3OTUtNDAxYS04MmFiLWNkOGM1OTI4MTlkZgAuAAAAAADZ4rJ1mTRFSo7InsH8LltSAQCP3sKosIJ4T5a5s8bVX3BWAAAI4f8CAAA=/messages/delta?$deltatoken=LztZwWjo5IivWBhyxw5rAJPpoRGn5nru3qIqZKxwjjY7xBDP__M1TUvFrj0rfYMHO5b83T2nwrZjbbsp0wV0-6XmPTJciuCkNm6u70CsqSg.VtTcmoaaTWiy53wR3KTuvGRAkVAZzxk_SI7rICNbt84`

header:
```
cache-control →private
client-request-id →0f6cb6d4-366f-4930-b0b7-4d591209964c
content-type →application/json
date →Fri, 26 Jan 2018 07:00:31 GMT
duration →335.0923
preference-applied →odata.track-changes
request-id →0f6cb6d4-366f-4930-b0b7-4d591209964c
transfer-encoding →chunked
x-ms-ags-diagnostic →{"ServerInfo":{"DataCenter":"East Asia","Slice":"SliceA","Ring":"4","ScaleUnit":"000","Host":"AGSFE_IN_2","ADSiteName":"HKG"}}
```

response:
```
{
    "error": {
        "code": "SyncStateNotFound",
        "message": "The sync state generation is not found; generation=518;[highest=523][523][521][522].",
        "innerError": {
            "request-id": "0f6cb6d4-366f-4930-b0b7-4d591209964c",
            "date": "2018-01-26T07:00:31"
        }
    }
}
```

**Comment by jasonjoh** [comment]
Thanks. I will send this to our engineering team for investigation.

**Comment by JamesDommisse** [comment]
Hi, is there any news on this issue?
I am also seeing a few of these errors and am not sure how best to handle them.

**Comment by lsnider** [comment]
We are seeing these too if anyone found a workaround?

**Comment by ZaMaZaN4iK** [comment]
+1 I also got the issue. Is any workable workaround for this?

**Comment by jthake-msft** [comment]
@ArunMSFT ?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. I'm cleaning up this repo. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
 The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
