### ISSUE TITLE
[Outlook] delta API in China and Germany endpoint

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2163]
Hi folks,

I am going to integrate all endpoints in office 365 like China and Germany.

But I found that both in China (https://microsoftgraph.chinacloudapi.cn) 
and Germany (https://graph.microsoft.de) the delta API cannot work.

All of them returns :
```
http code 400
{
    "error": {
        "code": "ErrorInvalidIdMalformed",
        "message": "Id is malformed.",
        "innerError": {
            "request-id": "3ffd7580-0d4e-478f-9479-42fa815cf00d",
            "date": "2018-01-24T07:04:16"
        }
    }
}
```
What API I have tried:

> mailFolders/delta
> messages/delta
> contactFolders/delta
> contacts/delta
> calendarGroups/delta
> calendars/delta
> calendars/calendarView/delta

If the API is not supported yet, what time will they be ready?
Or as the response said, 

`Id is malformed.`

How can I fix it?

BTW it works fine in global version https://graph.microsoft.com

Thanks!

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
