### ISSUE TITLE
BadRequest error when accessing 'deviceStatuses' resource segment in the API.

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/microsoft-graph-docs#21648]
**Error Response Summary:**
The API call results in a BadRequest error response with the following details:

**Error code: BadRequest**
Error message: Resource not found for the segment 'deviceStatuses'.
Date of the error: June 14, 2023, at 12:07:24 (UTC)
Request ID: 98a1fc3f-ea87-4265-881e-2eef98f8de91
Client Request ID: 98a1fc3f-ea87-4265-881e-2eef98f8de91

The error message indicates that the requested resource segment, 'deviceStatuses', was not found.

Please assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8f7269c9-70e5-eeb0-0931-df77e6c19acd
* Version Independent ID: 63369a03-6001-08b1-71b7-a4f7f1bcff3f
* Content: [List mobileAppInstallStatuses - Microsoft Graph beta](https://learn.microsoft.com/en-us/graph/api/intune-apps-mobileappinstallstatus-list?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/intune-apps-mobileappinstallstatus-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/intune-apps-mobileappinstallstatus-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @jaiprakashmb
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lnoeltnerIVI** [comment]
We are also receiving this error, but this endpoint used to work fine.

**Comment by BerkantKsTC** [comment]
We are having the same issue...
