### ISSUE TITLE
Add new app role to an existing Application throws error: `Request contains a property with duplicate values`

### ISSUE THREAD

**Issue by copdips** [microsoftgraph/microsoft-graph-docs#21667]
[Enter feedback here]

Hi,

I would like to add a new app role with PATCH application, but I got `Request contains a property with duplicate values` error.

hereunder the Pyhon code, even if you're not on Python, I think the code should be easy to understand 

```python
import requests
body = {
        "appRoles": [
            {
                "allowedMemberTypes": ["User", "Application"],
                "description": "test",
                "displayName": "test",
                "id": <new uuid>,
                "isEnabled": True,
                "origin": "Application",
                "value": "test",
            },
        ],
    }
url = f"https://graph.microsoft.com/v1.0/applications/{app_oid}"
# headers contains the bearer token
requests.patch(url, json=body, headers=headers)
```

Above command throws following error:

{"error":{"code":"DuplicateValue","message":"Request contains a property with duplicate values.","details":[{"code":"DuplicateValue","message":"Request contains a property with duplicate values.","target":"appRoles"}],"innerError":{"date":"2023-06-15T13:36:53","request-id":"fbe313c3-2a42-4dd7-938b-353f2b640445","client-request-id":"fbe313c3-2a42-4dd7-938b-353f2b640445"}}}
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 132fbbaf-f190-38e9-7af0-89aca63f69d7
* Version Independent ID: d68663e4-2d2f-898f-07a2-6748419cdf7b
* Content: [appRole resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/approle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/approle.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by copdips** [comment]
@FaithOmbongi @psignoret 
any updates please ?

**Comment by psignoret** [comment]
@copdips Apologies for the delay in responding here. If you're still able to reproduce this, can you please show the value of the *appRoles* and *api/oauth2PermissionScopes* properties before the PATCH, and the full error message (just link in your original post)?

**Comment by copdips** [comment]
sorry i forgot to update my issue. In fact, in the body of appRoles, I should include also the existing roles, but I added only the new one, that's why I got the above error. All is OK now, I will close this issue.
