### ISSUE TITLE
Problem with getting/setting the charm of a event via Graph api

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2169]
Hi,

The 'charm' property doesn't show in [event document](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/event).

Is there any way to get or set the charm of a event via api?

Thanks.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
