### ISSUE TITLE
Set token lifetime policy for a service principal

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#21709]
According to the doc, token lifetimes can be set for a specific service principal in organization. 

What I'm missing is a list of service principals for which I can/can't set token lifetime policy.

Could I set a lifetime policy for Graph Explorer?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 419287f7-8d19-27f5-d840-5e6ad9fec071
* Version Independent ID: 584e208e-b258-bb38-c2ec-25342423f077
* Content: [tokenLifetimePolicy resource type - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/resources/tokenlifetimepolicy?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/tokenlifetimepolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/resources/tokenlifetimepolicy.md)
* Product: **identity-and-sign-in**
* Technology: **microsoft-graph**
* GitHub Login: @lujiangfeng666
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for asking this question. I believe you can't set token lifetime policies only for managed identity service principals. And yes, you can set for Graph Explorer.

**Comment by MartinM85** [comment]
@FaithOmbongi Thank you for the answer. I'm not sure about Graph Explorer. In my dev tenant I set a default token lifetime policy to 30 minutes. It works fine for the applications but after sign-in in Graph Explorer I see that the token has expiration 1 day. I would expect either 30 minutes or default value 1 hour, not 1 day. 

It leads me to believe that there are more exceptions not mentioned in the doc.

**Comment by MartinM85** [comment]
There are contradictory information across the documentation.

According [this](https://learn.microsoft.com/en-us/graph/api/tokenlifetimepolicy-list-appliesto?view=graph-rest-1.0&tabs=http#:~:text=applied%20to.%20The-,tokenLifetimePolicy,-can%20only%20be) - TLP can be applied only to application

According [this](https://learn.microsoft.com/en-us/graph/api/resources/tokenlifetimepolicy?view=graph-rest-1.0#:~:text=specific%20service%20principal) - also to a specific service principal

According [this](https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes#:~:text=Microsoft%20identity%20platform.-,You%20can%20set,-token%20lifetimes%20for) - not to managed identity service principals

**Comment by FaithOmbongi** [comment]
Hi @MartinM85 - Thanks for sharing this additional info. It's possible that the token lifetime policy isn't being honored for service principals, though I was able to successfully assign it to Graph Explorer.

I'll reopen this issue and bump it internally to get more information, then I'll get back to you.

**Comment by MartinM85** [comment]
Hi @FaithOmbongi Assigning is working but the policy is ignored in my case

**Comment by FaithOmbongi** [comment]
Thank you @MartinM85 for sharing this information. I'm glad to learn something new and it explains a lot.

Allow me to get further clarification from the feature team before I can apply this feedback to the documentation so this concept can become clearer to others who visit the docs.
