### ISSUE TITLE
employeeOrgData is missing in User Api

### ISSUE THREAD

**Issue by andreasschild** [microsoftgraph/microsoft-graph-docs#21704]
Hi!
The [employeeOrgData resource type](https://github.com/microsoftgraph/microsoft-graph-docs/blob/f4ea34152929490a7e1c0a580882db3a81da43ee/api-reference/v1.0/resources/employeeorgdata.md) is listed in the [user resource type](https://github.com/microsoftgraph/microsoft-graph-docs/blob/f4ea34152929490a7e1c0a580882db3a81da43ee/api-reference/v1.0/resources/user.md) as a property, but it is not listed within the api documentation like [update user](https://github.com/microsoftgraph/microsoft-graph-docs/blob/f4ea34152929490a7e1c0a580882db3a81da43ee/api-reference/v1.0/api/user-update.md).

I tested it successfully with a direct REST call via PowerShell:

```
$params = @{
    Headers = @{ Authorization = ("Bearer {0}" -f "<replaced token>" )}
    Method = "PATCH"
    Uri = https://graph.microsoft.com/v1.0/users/abc@def.onmicrosoft.com
    ContentType = "application/json"
    Body = @{
        employeeOrgData = @{
            Division = "My Devision"
            CostCenter = "12345"
        }
    } | ConvertTo-Json
}
Invoke-RestMethod @params
```
I also found the property within the PowerShell module MgGraph. For example: [New-MgUser](https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users/new-mguser?view=graph-powershell-1.0#:~:text=%5B%2DEmployeeOrgData%20%3CIMicrosoftGraphEmployeeOrgData%3E%5D)

Has this property been forgotten within the documentation, is this property obsolete or do I missing something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @andreasschild for asking this question. This is a documentation oversight. employeeOrgData can be updated. I've raised a PR to document it among the list of updatable properties.
