### ISSUE TITLE
[Graph] Validation on ServiceConfigurationRecords or Office 365 DNS / Domains

### ISSUE THREAD

**Issue by Daniel-DNC** [microsoftgraph/microsoft-graph-docs#2170]
Does anyone know or can help me with programmatically start the Setup within domains at Office 365 (https://portal.office.com/AdminPortal/Home#/Domains).

The issue:

When I add a new domain (under a tenant) I can verify the domain (with DNS txt record). After the domain is added I adjust the domain so I can add Email and OfficeCommunicationsOnline to the SupportedServices. After updating the domain I can retrieve the ServiceConfigurationRecords but all of the created domains will stay in the state Setup in progress on the Office 365 site. I have changed the DNS Records accordingly the ServiceConfigurationRecords.

If I go to https://portal.office.com/AdminPortal/Home#/Domains, click on the created domain Continue setup and work my way through the wizard and verify it instantly works.

Can someone shed a light on which calls I need to make in order this to work from code? 

Daniel

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
