### ISSUE TITLE
Delete request deletes the object entirely from AD not just from the Administrative Unit

### ISSUE THREAD

**Issue by Chris-PGIT** [microsoftgraph/microsoft-graph-docs#21749]
[Enter feedback here]
When using this request I saw that the device is completely deleted from Azure AD. This request does not remove a device from an Administrative Unit... It deletes the device from AzAD...

Please provide the right request to remove a device from an Administrative Unit or update this with the right information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb22431b-47e4-5e55-af54-484645e305f7
* Version Independent ID: c0224593-2094-ba2a-20bb-d4ea98a3aa98
* Content: [Remove a member - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/administrativeunit-delete-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/administrativeunit-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/administrativeunit-delete-members.md)
* Product: **directory-management**
* Technology: **microsoft-graph**
* GitHub Login: @DougKirschner
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @Chris-PGIT - Unfortunately, I've been unable to repro your issue. Did you add /$ref segment to the URL? As per the doc, the syntax is

```
DELETE /directory/administrativeUnits/{id}/members/{id}/$ref
```

If you didn't add $ref, then that's the reason the device was deleted. But if you did, then this must be a functionality issue though I can't repro it myself and I recommend that you file the issue at [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html). Unfortunately, you currently can't recover deleted devices so always make sure to append `$ref`. I'll raise a PR to add a note of caution and stress on the need for $ref.

**Comment by Chris-PGIT** [comment]
Hello Faith,

I can confirm that the $ref was indeed in the request.
It seems like a bug then…

Below the URL (with truncated IDs) that has been used.
"https://graph.microsoft.com/v1.0/directory/administrativeUnits/9b320bfe-XXXXX/members/651c2b4b-XXXXXX/$ref"
Regards,
[https://i.ibb.co/ZcwmngY/LOGO-pragmatism-it-vertical-RVB-couleur.png]
[linkedin]<https://www.linkedin.com/in/descamps-c/>
Chris DESCAMPS
Consultant IT
Expert Microsoft 365

[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/phone-icon-2x.png]
+33 (0)3 76 043 930<tel:+33376043930>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/email-icon-2x.png]
***@***.******@***.***>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/link-icon-2x.png]
www.pragmatism-it.com<http://www.pragmatism-it.com>
[https://cdn2.hubspot.net/hubfs/53/tools/email-signature-generator/icons/address-icon-2x.png]
38 boulevard Carnot, Bureau 3 - 59000 LILLE

**Comment by FaithOmbongi** [comment]
Hi @Chris-PGIT - If you're able to get the request ID, please file the issue at [Microsoft Graph Q&A](https://learn.microsoft.com/en-us/answers/tags/241/microsoft-graph-directory-management-api) for investigation of this bevahior.
