### ISSUE TITLE
Rules for assigning token lifetime policies

### ISSUE THREAD

**Issue by MartinM85** [microsoftgraph/microsoft-graph-docs#21746]
App has already assigned token lifetime policy.

When trying to assign second token lifetime policy to an application

```
POST https://graph.microsoft.com/v1.0/applications/{app_id}/tokenLifetimePolicies/$ref
{
    "@odata.id": "https://graph.microsoft.com/v1.0/policies/tokenLifetimePolicies/{id}"
}
```

it returns error response

```
{
    "error": {
        "code": "Request_MultipleObjectsWithSameKeyValue",
        "message": "Request contains property changes that would result in property-uniqueness violation(s). Please retry your request with corrected values.",
        "innerError": {
            "date": "2023-06-21T13:41:04",
            "request-id": "f8cff810-456f-45e1-85dc-02cab71063dc",
            "client-request-id": "84b57260-4d19-b22c-0229-34a01118ee07"
        }
    }
}
```

Both token life time policies have different display name and definition (access token lifetime).

It should be mentioned in the documentation whether it is possible to assign more than token lifetime policy to the app and what the rules to avoid `Request_MultipleObjectsWithSameKeyValue` error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eacd922d-78d7-b319-912b-5a583b846115
* Version Independent ID: d3b1e758-9c81-0f20-792f-df516bce4b9f
* Content: [Assign tokenLifetimePolicy - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-tokenlifetimepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/application-post-tokenlifetimepolicies.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mitrasomit** [comment]
@MartinM85 

As per the document Microsoft Graph REST API V1.0 - Article 06/14/2023

<img width="448" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/63601724/35ba280c-f237-46ad-be9e-70f0dbde5d00">

https://learn.microsoft.com/en-us/graph/api/application-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=http#http-request

For me, it works when I try with Object ID in the JSON payload, **/v1.0/policies/tokenLifetimePolicies/{Object ID} and it returns the expected 204 No Content response code in the HTTP response**

<img width="581" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/63601724/59a0784f-2fff-4041-8344-240a23fa4843">


I have also tried with other references too, and it is works with either Object id or appId(Client).

Thanks!

**Comment by MartinM85** [comment]
@mitrasomit Hi, thanks for the answer. Have you tried to assign the second token lifetime policy?

According to the [doc](https://learn.microsoft.com/en-us/graph/api/application-list-tokenlifetimepolicies?view=graph-rest-1.0&tabs=http)

    GET /applications/{id}/tokenLifetimePolicies

returns a list the tokenLifetimePolicy objects that are assigned to an application. Based on this, users can assume that you can assign more than one policy to the application.

When I assign the first policy, the response is 204 but when I assign another policy (without removing the first one) the response returns the error Request_MultipleObjectsWithSameKeyValue

**Comment by FaithOmbongi** [comment]
Thank you for your patience @MartinM85.

You can't assign more than one token lifetime policy per application and even though the LIST operation will return a collection, the collection will always have only one policy. @mitrasomit has raised a PR to document this limitation and clear the confusion.
