### ISSUE TITLE
[Beta] Setting parentFolderId on an outlook task does not seem to work as documented

### ISSUE THREAD

**Issue by twindan** [microsoftgraph/microsoft-graph-docs#2176]
Issue: 
I am using the beta APIs to create outlook tasks and it seems like the parentFolderId is being ignored. I have reproduced this issue with both the Graph Explorer and Microsoft.Graph C# library (using a custom build to access the beta APIs.)

The steps to reproduce it (using the graph explorer) is as follows:

1. Do a GET on https://graph.microsoft.com/beta/me/outlook/taskFolders    
2. Scan the resulting list of tasks for the desired folder and save its id.
3. Do a POST to https://graph.microsoft.com/beta/me/outlook/tasks    
4. Send:
`{
  "subject": "Test task",
  "parentFolderId": "<ID FROM NO 1>=="
}`
5.  It will create the task, but it will be in the default folder and not the folder specified in the JSON request. The parentFolderId in the returned JSON will be the default folder and not the one that was specified in the request.

Using a PATCH request to https://graph.microsoft.com/beta/me/outlook/tasks   will also not change the folder id.
 
The parentFolderId may be ignored on a create request. If I change the parentFolderId to something invalid (e.g., a random string of characters), it still creates the task in the default folder.

Article:

**Comment by mlafleur** [comment]
You need to `POST` into the `TaskFolder` itself. From the [documentation](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlooktaskfolder_post_tasks.md): 

```
POST /users/{id|userPrincipalName}/outlook/taskFolders/{id}/tasks
```
The documentation here could be clearer:

- [`resources/outlooktask`][2]: The `parentFolderId` property should include a note that this property is a Read-Only.

- [`outlookuser_post_tasks`][1]: This page should include a reference to the [creating tasks within a Task Folder][3] page. 

- Potentially, the [Create Tasks][1] and [Create TaskFolder Tasks][3] pages could be combined into a single page. As best I can tell, the only substantive difference between these pages is the URI prototype. 


[1]: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlookuser_post_tasks.md

[2]: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/outlooktask.md

[3]: (https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlooktaskfolder_post_tasks.md
