### ISSUE TITLE
How to capture response

### ISSUE THREAD

**Issue by mattielung** [microsoftgraph/microsoft-graph-docs#21786]
[The sample code shows what the Response should be but does not give any clue on how to capture the response ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 44f6304a-ab90-8543-39c7-2afd61197ffb
* Version Independent ID: 9ca019b5-063f-33a2-3cb9-3ab6baafe9d4
* Content: [Use query parameters to customize responses - Microsoft Graph](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/query-parameters.md)
* Product: **applications**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Hi @mattielung , can you clarify what you mean by "but does not give any clue on how to capture the response "?

When you run the request using any API client, you should receive the response object and your app should have the logic to handle the responses. Please let me know if this doesn't answer your question.

**Comment by FaithOmbongi** [comment]
Hi @mattielung - I haven't heard back from you. I'll assume you got the answer to your question and will proceed to close this issue.
