### ISSUE TITLE
How to add charm information via ics import?

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2179]
Hi,

I have a question about ics import.
Can I update my event's categories and charm during the ics file import?
If yes, how should I store these information in the ics file and could you get me an example?

Thanks.

**Comment by jasonjoh** [comment]
Can you explain what you mean by ICS import? As far as I know the Graph API doesn't have any way to import an ICS file.

**Comment by judithting** [comment]
Sorry for my undetailed question.

I want to use the function on the Calendar website to add calendar from .ics file, like the following picture.
![import_isc](https://user-images.githubusercontent.com/25191249/35677464-a0f82458-078a-11e8-942c-f3f971a765e9.png)

I have use EWS api to export a calendar event, and I find how to add categories via .ics file.
However, I didn't find any keyword about charm in the .ics file which was export from EWS api.
Could you help me to deal with this problem?
Or which github project I can get the answer of the question?

Thanks a lot.

**Comment by jasonjoh** [comment]
I would assume you could use CATEGORIES in the ICS file, but I'm not 100% sure it's supported by Outlook. I don't believe there's anything in ICS that would support adding a charm, as it's an Outlook-specific feature. This isn't a Graph-related question so this is the wrong place for it. 

The detail on how Outlook and Exchange handle ICS import is covered in detail in [MS-OXCICAL](https://msdn.microsoft.com/en-us/library/cc463911(v=exchg.80).aspx), so if it's possible I'd expect it to be called out there.
