### ISSUE TITLE
Can't get seriesMaster event info of a meeting poll event via ListCalendarView

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2182]
Hi, 

I found that the ListCalendarView api would not response the seriesMaster event of a meeting poll event.
Could you check is it a bug of ListCalendarView api?

Here are my test steps.

1. Create a meeting poll event with the meeting time options which are "2018/1/30 8:00 AM" and "2018/1/31 8:00 AM".
2. Send api: GET me/events
    the responses contains a seriesMaster event and two exception events of the meeting poll.
3. Send api: GET me/calendars/$(my_calendar_id)/calendarView/delta?startDateTime=2018-01-01&endDateTime=2018-12-31
    the response only contains two exception events.

Thanks.

**Comment by judithting** [comment]
Hi @Hongbo-Miao ,

Could you help me to check this problem?
Is it a bug or the limitation of ListCalendarView api?
If it is bug, will you and your team fix it in the future?

Thanks a lot.

**Comment by Hongbo-Miao** [comment]
Hi @judithting I am working in Excel team, just saw it and help quickly add a label. You will get response from Outlook team next week I think.

**Comment by jasonjoh** [comment]
This is by design. When you use `calendarview`, recurring appointments are expanded, and you get the occurrences, not the master. They should both have a `seriesMasterId` property that you can use to retrieve the master.

**Comment by judithting** [comment]
Hi @jasonjoh 

Thanks for your explanation, but I can get seriesMaster event of **normal** event via ` calendarview` with **delta** command.
Therefore, I think I can get seriesMaster event of **meeting poll event** too.
Is it also by design?
Thanks for your help.

The calendarview api I sent is `me/calendars/$(calendar_id)/calendarView/delta?startDateTime=2018-01-01&endDateTime=2018-12-31`.
If I don't add "**delta**" after "calendarView", I can't get seriestMaster event as your explanation.
However, if I use the calendarView api with delta, I can get seriestMaster event of normal event.


Normal event: a repeated event and I don't set up meeting poll.
Meeting poll event: create a event with "Poll for a time to meet"
![meeting_poll_event](https://user-images.githubusercontent.com/25191249/35970850-d1bbcec4-0d06-11e8-837e-673fdac00aff.png)

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
