### ISSUE TITLE
Update exmaple in intune_apps_mobileapp_assign.md 

### ISSUE THREAD

**Issue by fm107** [microsoftgraph/microsoft-graph-docs#2183]
Hi,

Is it possible to update an example of the request for assigning app to groups which is [here](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune_apps_mobileapp_assign.md#example)?

When I'm trying to submit a request I get the error: 
```
{
  "error": {
    "code": "ModelValidationFailure",
    "message": "A type named 'microsoft.management.services.api.mobileAppGroupAssignment' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.",
    "innerError": {
      "message": "A type named 'microsoft.management.services.api.mobileAppGroupAssignment' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.",
      "request-id": "895365cf-757b-4f62-bb3c-2b3a45eb96b4",
      "date": "2018-01-29T13:36:53"
    }
  }
}

```
with the following payload

```
{  
   "mobileAppGroupAssignments":[  
      {  
         "@odata.type":"#microsoft.graph.mobileAppGroupAssignment",
         "targetGroupId":"7a454e80-0645-4455-9de8-7ff8128df030",
         "installIntent":"AvailableWithoutEnrollment"
      }
   ]
}
```

**Comment by jthake** [comment]
It appears that this documentation has been updated since. Does this work for you now? Apologies for the delay here, I'm triaging all the open issues.

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/intune_apps_mobileapp_assign
