### ISSUE TITLE
[Outlook] [Contact] failed to create contact with email address 

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2186]
Hi all, 

I using this API to create a contact
```
POST /me/contacts
```
With this field

```
...
"emailAddresses": [
                {
                    "name": "BBB@msn.com,",
                    "address": "A@msn.com,"
                }
],
...
```
Something strange happened.

I could see both name and address in this contact on web, 

But when I use graph API for detail
```
GET /me/contacts
```
The field _**address**_ has gone
```
...
"emailAddresses": [
        {
            "name": "BBB@msn.com,"
        }
    ],
...
```

**Comment by jasonjoh** [comment]
I do not reproduce this in an Office 365 account or an Outlook.com account. Is there a step missing?

I did:

1. Create contact:

    **REQUEST**
    ```
    POST /me/contacts

    {
      "givenName": "Pavel",
      "surname": "Bansky",
      "emailAddresses": [
        {
          "address": "pavelb@fabrikam.com",
          "name": "peebles@contoso.com"
        }
      ],
      "businessPhones": [
        "+1 732 555 0102"
      ]
    }
    ```
1. Get contacts

    **REQUEST**
    ```
    GET /me/contacts
    ```

    **RESPONSE**
    ```
    ...
    {
      "@odata.etag": "W/\"EQAAABYAAADHaculwhfXTIbYxXizQ2NIAAD6e5w8\"",
      "id": "AQMk...",
      "displayName": "Pavel Bansky",
      "emailAddresses": [
        {
          "name": "peebles@contoso.com",
          "address": "pavelb@fabrikam.com"
        }
      ]
    }
    ...
    ```

**Comment by joewutaiwan** [comment]
Hi @jasonjoh ,

Please try one more comma:
```
POST /me/contacts

{
  "givenName": "Pavel",
  "surname": "Bansky",
  "emailAddresses": [
    {
      "address": "pavelb@fabrikam.com,",
      "name": "peebles@contoso.com,"
    }
  ],
  "businessPhones": [
    "+1 732 555 0102"
  ]
}
```
Thanks!

**Comment by jasonjoh** [comment]
Why are you putting commas in the values like that? That would result in an invalid SMTP address, so it would fail validation. For the name field it only has to be a string, so that value would be OK.

**Comment by joewutaiwan** [comment]
Hi @jasonjoh ,

Thanks for reply,

The reason why  I  putting commas because I could type 'pavelb@fabrikam.com,' on office365 website.
So if that kind of email could be blocked or validated at the first time, it will be a good help. 

Thanks!

**Comment by jasonjoh** [comment]
I'd consider that a bug in the Outlook web client. I see that you can enter a value like that and it doesn't complain, but it doesn't save it as an email address either. I agree it would be a better user experience to notify the user that the value is invalid rather than silently dropping it. I'll let the engineering team know.
