### ISSUE TITLE
[DocBug] Subscribing to User resource, when user is created or updated partner is receiving multiple user updated events.

### ISSUE THREAD

**Issue by Konapalli1508** [microsoftgraph/microsoft-graph-docs#21882]
When the user is created or updated, it is triggering multiple notifications that each correspond to some user property that has changed. Customer receives multiple notifications due to reply mechanism corresponding to various outages that can occur in our pipeline.
Also when the customer endpoint is slow in responding with 200/202 status codes and MS Graph is re trying to deliver those notifications for up to 4 hours until the customer endpoint responds in less than 3 secs with 200/202 status codes.
 It seems to be an expected behavior So, could you please update the same in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: **change-notifications**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@FaithOmbongi FYI

**Comment by FaithOmbongi** [comment]
Thank you @Konapalli1508 for raising this issue. The second part of your feedback seems to be covered in the [Notifications through webhooks: throttling](https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks?tabs=http#throttling) section. Is this what you mean?

**Comment by keylimesoda** [comment]
We have updated documentation pending for our throttling here:  https://github.com/microsoftgraph/microsoft-graph-docs/pull/22011

The relevant section is below:
=======================

1. An endpoint will be marked "slow" once more than 10% of responses take longer than 3 seconds in a 10-minute window.
      - Once an endpoint has been marked "slow", any new notifications will be sent on a 10 second delay.
      - An endpoint will exit "slow" state once less 10% of responses take longer than 3 seconds in a 10-minute window.

2. An endpoint will be marked "drop" once more than 15% of responses take longer than 3 seconds in a 10-minute window.
      - **Once an endpoint has been marked "drop", any new notifications will be dropped, for up to 10 minutes**
      - An endpoint will exit "drop" state once less than 15% of responses take longer than 3 seconds in a 10-minute window.

If you are unable to stand up an endpoint with these performance characteristics, please consider using Event Hub (link) or Event Grid (link) as a target for receiving notifications.

#### Retry
Once change notifications service has received a 2xx class code from your endpoint, a notification is considered sent and will not be tried again.

As long as the change notifications service receives any other HTML response in a timely manner (within 3 seconds), the service will continue to try to deliver the notification for up to 4 hours.
