### ISSUE TITLE
PATCH request to me/contacts/{id} returns 405 error

### ISSUE THREAD

**Issue by gnome-leader** [microsoftgraph/microsoft-graph-docs#2188]
I am unsuccessfully attempting to update the properties of an existing Contact using the Graph API.  I am sending a PATCH request the the following URL:

https://graph.microsoft.com/v1.0/me/contacts/AAMkAGRmYmZlZDBkLTI1NjMtNDZkZi04MDk2LTk4YjBmODkyNzU1MwBGAAAAAABOOTMEQgwCRbbGUCX4oqohBwBWD04NmgV3S5nBYHa4vj4iAAAAAAEOAABWD04NmgV3S5nBYHa4vj4iAAB_PMFJAAA=

Payload/content:

```
{
  "emailAddresses": [
    {
      "address": "testaccount@gnometestdomain.com",
      "name": "testaccount@gnometestdomain.com"
    },  
    {   
      "address": "additional@gnometwodomain.com",
      "name": "new address"
    }
  ],
  "businessPhones": [
    "standardPhoneTestValue",
    "AddPhoneTestValue"
  ]
}
```

Response content:

```
{
  "error": {
    "code": "ErrorInvalidRequest",
    "message": "The OData request is not supported.",
    "innerError": {
      "request-id": "19450549-8e1a-46ac-9214-098b86a8befa",
      "date": "2018-01-30T15:36:24"
    }
  }
}
```

I have not been able to figure out why this doesn't work.  Help?

Thanks!

Issue: 

Article:

**Comment by jasonjoh** [comment]
Your request works fine for me. Can you do a GET on that URL?

**Comment by gnome-leader** [comment]
I can.  GET works.

 

My test logic does a GET, then a DELETE, then a POST to me/contacts to create a new Contact.

 

It’s only when I attempt the PATCH to modify the Contact that I just created when I get this error.

**Comment by mlafleur** [comment]
The error you're getting is a little confusing but there is an issue with `businessPhones` your payload:

```
"businessPhones": [
    "standardPhoneTestValue",
    "AddPhoneTestValue"
  ]
```

If you're passing multiple values, this will result in an error. From the [documentation](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md):

> The telephone numbers for the user. **NOTE: Although this is a string collection, only one number can be set for this property.**

**Comment by gnome-leader** [comment]
That may be the case for the phone(s) field, but I changed the payload to this:

{"jobTitle":"debug title"}

...and I still get the same error.

**Comment by jasonjoh** [comment]
Going to pass this one up to engineering to see what they can determine.

**Comment by gnome-leader** [comment]
If it helps, this is the most recent error response payload:

{
  "error": {
    "code": "ErrorInvalidRequest",
    "message": "The OData request is not supported.",
    "innerError": {
      "request-id": "81caec05-bddd-4fd2-bdd2-86fab73ec328",
      "date": "2018-02-06T15:26:05"
    }
  }
}

**Comment by OlaCarlander** [comment]
Having the same issue, POST and GET works, but PTACH yields: 
{
    "error": {
        "code": "ErrorInvalidRequest",
        "message": "The OData request is not supported.",
        "innerError": {
            "request-id": "2c355e9e-ead9-4f60-80a1-10c3e92e01f9",
            "date": "2019-05-16T10:50:00"
        }
    }
}

Following the guide from: 
https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=cs

**Comment by samedwards** [comment]
Was there a fix for this?  I am also getting this error.
```
"ExceptionDetail": {
	"HResult": -2146233088,
	"Message": "Code: ErrorInvalidRequest\nMessage: The OData request is not supported.\n\nInner error\n",
	"Source": "Microsoft.Graph.Core",
	"Error": {
		"Code": "ErrorInvalidRequest",
		"InnerError": {
			"Code": null,
			"InnerError": null,
			"Message": null,
			"ThrowSite": null,
			"AdditionalData": {
				"request-id": "611f9311-b3c5-4531-9317-b03017af7b59",
				"date": "2019-08-29T23:16:15.0000000"
			}
		},
		"Message": "The OData request is not supported.",
		"ThrowSite": null,
		"AdditionalData": null
	},
	"ResponseHeaders": [{
		...
	],
	"StatusCode": "MethodNotAllowed",
	"Type": "Microsoft.Graph.ServiceException"
}
```

**Comment by Machecek** [comment]
@OlaCarlander did you overcome this issue? I have run into same problem as you

**Comment by gnome-leader** [comment]
Never got around the issue.  Moved on to other problems.

**Comment by Machecek** [comment]
@gnome-leader in my case i was missing the event ID in request URL

**Comment by OlaCarlander** [comment]
@Machecek, I don't think so. Can't remember how I worked around it really
