### ISSUE TITLE
Creating channels via MS Graph API does not create corresponding file area - (sometimes)

### ISSUE THREAD

**Issue by Luunk** [microsoftgraph/microsoft-graph-docs#21921]
We are having a bit of a strange issue. We create short lived teams with channels for different projects. Everything is automated via API calls to the Graph API. Sometime when we create channels in the newly created team, there is no file area to store files. Mostly this happens for private channels but also for standard channels. We do not get any error when posting to the API to create a channel. So we have nothing to really troubleshoot. It only says "
When we creates channels with the teams app for the same team everything works as it should. File area gets created. 
This also only applies to our organization tenant. I have tested in my own private / demo tenant and no issues at all there. Same code, same automation etc. Just a different tenant. 

Does anyone know where to start troubleshoot? Or do we have to engage MS with a ticket? Where do one rase an issue with Graph API for just one tenant?  🤔

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create channel - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @Luunk - Thanks for raising your query.
We will look into it and let you know.

**Comment by Meghana-MSFT** [comment]
@Luunk - Could you please confirm if you are facing the issue as this - https://github.com/MicrosoftDocs/msteams-docs/issues/8934?

The channel created via Graph gives "There was a problem reaching this app" while accessing the files tab. We already have a bug raised for this.

**Comment by Luunk** [comment]
> @Luunk - Could you please confirm if you are facing the issue as this - [MicrosoftDocs/msteams-docs#8934](https://github.com/MicrosoftDocs/msteams-docs/issues/8934)?
> 
> The channel created via Graph gives "There was a problem reaching this app" while accessing the files tab. We already have a bug raised for this.

Oh yes, it looks very similar! So I would say yes probably is the same issue. We have seen other error pages depending on what client is used to access Teams. But over all looks to be the same issue. It´s Ok to close this issue and I can track the one you linked. 
Thanks!

**Comment by Meghana-MSFT** [comment]
@Luunk - Thank you for confirming, we are closing this issue. Please refer the above thread for further updates. We would like your [feedback on your experience with our support team and Platform](https://aka.ms/DevSupportFeedback). Click here to [escalate](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR7iCOpS5_b9Nqmwx43u5rtZUN0dNSTA4WVo2S05JQ1M4TVlYMjROSjhURS4u).
