### ISSUE TITLE
Add clarification on case-sensitivity for Id property in Microsoft Graph API batch request

### ISSUE THREAD

**Issue by jianhsieh** [microsoftgraph/microsoft-graph-docs#21940]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Content Idea adding clarification for: [microsoft-graph-docs/concepts/json-batching.md at main · microsoftgraph/microsoft-graph-docs · GitHub](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/json-batching.md)

We would like to associate note in content: [Access data and methods by navigating Microsoft Graph - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/traverse-the-graph?tabs=http#microsoft-graph-api-metadata) to [Combine multiple requests in one HTTP call using JSON batching - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/json-batching):

Note:
- Use resource IDs in the same case as they are returned from Microsoft Graph APIs.
- Assume resource IDs, values you assign, and other base-64-encoded values are case-sensitive.
- Assume path URL resource names, query parameters, action and function names, their request body parameters, including any API property names and values, are not case-sensitive.

Background:
I have a scenario - using email message Id as Id in the batch request. The email message Id is case sensitive; therefore, we may have email message Id for item A as "abcxyz" and another item B as "abcXyz" representing two separate items. However, the Id in batch operation isn't case-sensitive; therefore, using abcxyz & abcXyz as Id in the same batch request will throw bad request "<Id> has to be unique in a batch.". Per [Access data and methods by navigating Microsoft Graph - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/traverse-the-graph?tabs=http#microsoft-graph-api-metadata), this appears to be expected since request body parameters Id in batch request is not case-sensitive and abcxyz & abcXyz are considereed the same.

The batch operation stated the Id property is just a correlation value. We should generate random unique Ids rather than inheriting email message Id to prevent the issue:

id | Required. A correlation value to associate individual responses with requests. This value allows the server to process requests in the batch in the most efficient order.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e33b4529-dfaa-b051-a73e-fa7312e911f5
* Version Independent ID: 55111137-63ad-3408-9295-ef44128aed14
* Content: [Combine multiple requests in one HTTP call using JSON batching - Microsoft Graph](https://review.learn.microsoft.com/en-us/graph/json-batching?branch=main)
* Content Source: [concepts/json-batching.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/json-batching.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @FaithOmbongi
* Microsoft Alias: **ombongifaith**

**Comment by FaithOmbongi** [comment]
Thank you @jianhsieh for this suggestion. And yes, you're right. I've raised a PR to apply your suggestion.
