### ISSUE TITLE
Determine customers supported services for a domain

### ISSUE THREAD

**Issue by rsebescen** [microsoftgraph/microsoft-graph-docs#2195]
Issue: Is there a way to determine which supported services can be linked to a domain?

Article: [Here](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/domain.md) is the list of all possible services but I need to know which ones can actually be assigned to a domain.

Thank  you

**Comment by jthake-msft** [comment]
@angelgolfer-ms  who owns this page?

**Comment by angelgolfer-ms** [comment]
@lleonard-msft , would you be able to help please? This is an AAD API on Microsoft Graph.
@Lauragra , the [redirects for the domain APIs in the changelog](https://developer.microsoft.com/en-us/graph/docs/concepts/changelog#march-2017) from graph.microsoft.io to developer.microsoft.com don't seem to be working properly. That leads me wondering if all similar redirects are not working. Would you be able to verify please?

**Comment by Lauragra** [comment]
@angelgolfer-ms , I'll follow up with the engineering team about the redirects.

**Comment by lleonard-msft** [comment]
Hi @rsebescen - Did you see the description of the supportedServices property in the topic you linked to?  It specifically says that the following services can be added or removed using the Graph API: Email, OfficeCommunicationsOnline, and Yammer.

Is there more to the scenario?  If so, could you clarify your question?

Note that, in general, issues for documentation projects are meant as a feedback mechanism on the documentation itself, such as typos, broken links, unclear/missing descriptions, and so on.  Support is available through official channels (see the appropriate blade in your subscription portal) or through [StackOverflow](https://stackoverflow.com/search?q=microsoft-graph+azure-active-directory).

**Comment by lleonard-msft** [comment]
Since we've not had any follow-up in nearly a year, I'm closing this.

If there's more to discuss, please re-open or file a new issue.
