### ISSUE TITLE
Invalid URL in the directoryObject/drive@odata.navigationLink property

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-docs#22]
When requesting user's Groups using the `/v1.0/me/memberOf` endpoint, Groups represented by directoryObjects return invalid drive URLs in the **directoryObject/drive@odata.navigationLink** property such as `https://graph.microsoft.com/v1.0/directoryObjects/2a39e1d7-6d12-4a16-a486-70dedfb36a7e/microsoft.graph.group/drive`. If you try to access this URL you get the following error:

```
{
    "error": {
        "code": "BadRequest",
        "message": "Unsupported segment type.",
        "innerError": {
            "request-id": "39079e84-42c7-4715-b6ee-d369aba856ed",
            "date": "2015-11-20T12:35:59"
        }
    }
}
```

If you would access Group's drive through the `/groups` endpoint like `https://graph.microsoft.com/v1.0/groups/2a39e1d7-6d12-4a16-a486-70dedfb36a7e/drive` things work as expected.

Invalid link in the **directoryObject/drive@odata.navigationLink** property makes it difficult to work with Groups and their resources. If this behavior is intented it should be reflected in the documentation.

**Comment by dkershaw10** [comment]
Hi Waldek,
The problem here is that memberOf needs to return directoryObjects, because memberOf returns the user's group AND directory role memberships.  A better approach would be to use:
https://graph.microsoft.com/v1.0/me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(a:a%20eq%20'Unified') to get the Office365 groups the user is a member of (and specifically have content).  In this case the type returned in odata.type is a group, and odata.id contains group/<id>.  Are you looking for this to be explicit in the documentation?

**Comment by waldekmastykarz** [comment]
Absolutely! The documentation should make it super obvious for everyone to use the new APIs and should mention any workarounds and recommendations for getting the most out of the APIs.

Regarding the request you mentioned, if I issue it using Postman in Chrome (or an Angular SPA) I'm getting the following error:

```
{
    "error": {
        "code": "BadRequest",
        "message": "Unsupported segment type.",
        "innerError": {
            "request-id": "da13d3e5-fdcc-4303-bf38-8a313864b8af",
            "date": "2015-11-20T18:49:44"
        }
    }
}
```

I have seen it working in the API Explorer but cannot get it to work with my own apps. I first suspected that it would be an issue with permissions but my app has the following scopes `AllSites.Read Directory.AccessAsUser.All Group.Read.All Sites.Search.All User.Read` which should be sufficient for the call if I understood the documentation correctly.

**Comment by jthake-msft** [comment]
Closing as I believe @waldekmastykarz that this is a bug that has been squashed.
