### ISSUE TITLE
A bug of timezone conversion when calling create event api

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2202]
Hi,

I found a bug of timezone conversion when I call the event api to create a repeated event.
There are my test steps.

1. Create a repeated event A and set up 
    (1) start_time: 2018-02-03 6:00 in GMT+8
    (2) end_time:  2018-02-03 8:00 in GMT+8
    (3) recurrence: repeat every Saturday until 2018-03-10

2. Use GET /me/events/event_id to get the event information as the following. 

3. Use POST /me/events with the json response which we get from Step 2.

4. The UI shows the start_time is "2018-02-04 6:00 in GMT+8" and the end_time is "2018-02-04 8:00 in GMT+8" of the new repeated event A' which I create via api.

A part of response from GET /me/events/event_id
```
{
    "id": "AAMkADVmMzE2MjY0LTZkOGYtNGI4MS1iNWMxLTljYzg3MWY5MWQxMQBGAAAAAABZMfR36TVMQ6yunaqZPvVRBwAF9fKWjhbKTIB6dNkgJcvkAAAAAAENAAAF9fKWjhbKTIB6dNkgJcvkAACO7c0qAAA=",
    "originalStartTimeZone": "Taipei Standard Time",
    "originalEndTimeZone": "Taipei Standard Time",
    "iCalUId": "040000008200E00074C5B7101A82E008000000005969BE9B5A9BD3010000000000000000100000006B4527122707AA4F914EDB509D9E557B",
    "isAllDay": false,
    "isCancelled": false,
    "isOrganizer": true,
    "seriesMasterId": null,
    "type": "seriesMaster",
    "responseStatus": {
        "response": "organizer",
        "time": "0001-01-01T00:00:00Z"
    },
    "start": {
        "dateTime": "2018-02-02T22:00:00.0000000",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2018-02-03T00:00:00.0000000",
        "timeZone": "UTC"
    },
    "recurrence": {
        "pattern": {
            "type": "weekly",
            "interval": 1,
            "month": 0,
            "dayOfMonth": 0,
            "daysOfWeek": [
                "saturday"
            ],
            "firstDayOfWeek": "sunday",
            "index": "first"
        },
        "range": {
            "type": "endDate",
            "startDate": "2018-02-03",
            "endDate": "2018-03-10",
            "recurrenceTimeZone": "Taipei Standard Time",
            "numberOfOccurrences": 0
        }
    }
}
```

**Comment by jasonjoh** [comment]
What behavior do you consider a bug?

**Comment by judithting** [comment]
I have used GET /me/events to get the new event A‘, but the recurrence part is different from event A.

I think it have to be as same as the request I have sent in Step 3.
On the other words, I think the time of these two events have to be same. 

Besides, the UI shows the original event is occurred at 2018-02-03, and the new event is at 2018-02-04. There are totally different date.

Therefore, I think it is bug of timezone conversion.

**Comment by jasonjoh** [comment]
Could you please share the request you used to create the event?

**Comment by judithting** [comment]
I sent POST /me/events to create the event A‘, and the request json is what I get from GET /me/events/{id of event A}.

I have show a part of response of GET /me/events/{id of event A} on the first conversation.

Is these information enough for you?
If you need more, please let me know.
Thanks for your help.

**Comment by jasonjoh** [comment]
Yes but I'm asking what payload are you sending in the POST to create the event?

**Comment by judithting** [comment]
I only put the auth key in request header and the json format of Event in the request body.

**Comment by jasonjoh** [comment]
Can you share the JSON you put in the body? I can't try to reproduce your problem without understanding what you're sending.

**Comment by judithting** [comment]
Hi,

The original event I have removed, so I create a new event to reproduce this problem again. 

1. On the Outlook Calendar website to create a event with
    (1) start_time: 2018-03-03 6:00 AM in Taipei timezone
    (2) end_time:  2018-03-03 8:00 AM in Taipei timezone
    (3) Repeat every Saturday from 2018-03-03 to 2018-08-18

![create_event](https://user-images.githubusercontent.com/25191249/35727775-3724fa32-0844-11e8-9430-de183df385b5.png)

2. Use GET /me/events to the Event object via the Graph Explorer.

3. Use POST /me/events via the Graph Explorer.

Here is the JSON I put in the body.
I replace my name and my account mail with "xxx yyy" and "xxx@yyy.onmicrosoft.com" in the JSON object separately.

{
  "@odata.etag": "W/\"fC7Rd+rnm0WMcnjN+DiQ9QABCixjGQ==\"",
  "id": "AAMkAGU4MjE3NDA5LTNmMmMtNDUwYi1iMjk5LTFlNTkzOTE0YTk0NABGAAAAAADK5iiXu3goQLndw7y_3oX3BwB8LtF36uebRYxyeM34OJD1AAAAAAENAAB8LtF36uebRYxyeM34OJD1AAEJ_w9XAAA=",
  "createdDateTime": "2018-02-02T02:47:56.093665Z",
  "lastModifiedDateTime": "2018-02-02T02:47:56.1874148Z",
  "changeKey": "fC7Rd+rnm0WMcnjN+DiQ9QABCixjGQ==",
  "categories": [],
  "originalStartTimeZone": "Taipei Standard Time",
  "originalEndTimeZone": "Taipei Standard Time",
  "iCalUId": "040000008200E00074C5B7101A82E00800000000CA60813AD09BD301000000000000000010000000F10FCE825EBC88468D27310C95B2E87A",
  "reminderMinutesBeforeStart": 15,
  "isReminderOn": true,
  "hasAttachments": false,
  "subject": "Repeat on every Saturday  morning 6:00~8:00",
  "bodyPreview": "",
  "importance": "normal",
  "sensitivity": "normal",
  "isAllDay": false,
  "isCancelled": false,
  "isOrganizer": true,
  "responseRequested": true,
  "seriesMasterId": null,
  "showAs": "busy",
  "type": "seriesMaster",
  "webLink": "https://outlook.office365.com/owa/?itemid=AAMkAGU4MjE3NDA5LTNmMmMtNDUwYi1iMjk5LTFlNTkzOTE0YTk0NABGAAAAAADK5iiXu3goQLndw7y%2B3oX3BwB8LtF36uebRYxyeM34OJD1AAAAAAENAAB8LtF36uebRYxyeM34OJD1AAEJ%2Bw9XAAA%3D&exvsurl=1&path=/calendar/item",
  "onlineMeetingUrl": null,
  "responseStatus": {
    "response": "organizer",
    "time": "0001-01-01T00:00:00Z"
  },
  "body": {
    "contentType": "html",
    "content": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<meta content=\"text/html; charset=us-ascii\">\r\n<style type=\"text/css\" style=\"display:none\">\r\n\r\n</style>\r\n</head>\r\n<body dir=\"ltr\">\r\n<div id=\"divtagdefaultwrapper\" dir=\"ltr\" style=\"font-size:12pt; color:#000000; font-family:Calibri,Helvetica,sans-serif\">\r\n<p style=\"margin-top:0; margin-bottom:0\"><br>\r\n</p>\r\n</div>\r\n</body>\r\n</html>\r\n"
  },
  "start": {
    "dateTime": "2018-03-02T22:00:00.0000000",
    "timeZone": "UTC"
  },
  "end": {
    "dateTime": "2018-03-03T00:00:00.0000000",
    "timeZone": "UTC"
  },
  "location": {
    "displayName": "",
    "address": {}
  },
  "recurrence": {
    "pattern": {
      "type": "weekly",
      "interval": 1,
      "month": 0,
      "dayOfMonth": 0,
      "daysOfWeek": [
        "saturday"
      ],
      "firstDayOfWeek": "sunday",
      "index": "first"
    },
    "range": {
      "type": "endDate",
      "startDate": "2018-03-03",
      "endDate": "2018-08-18",
      "recurrenceTimeZone": "Taipei Standard Time",
      "numberOfOccurrences": 0
    }
  },
  "attendees": [],
  "organizer": {
    "emailAddress": {
      "name": "xxx yyy",
      "address": "xxx@yyy.onmicrosoft.com"
    }
  }
}

4. Here is the response of POST /me/events
    I highlight the different part in bold as the following.

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('71111e6a-323f-49fc-8900-c6c536536578')/events/$entity",
    "@odata.etag": "W/\"fC7Rd+rnm0WMcnjN+DiQ9QABCixjGg==\"",
    "id": "AAMkAGU4MjE3NDA5LTNmMmMtNDUwYi1iMjk5LTFlNTkzOTE0YTk0NABGAAAAAADK5iiXu3goQLndw7y_3oX3BwB8LtF36uebRYxyeM34OJD1AAAAAAENAAB8LtF36uebRYxyeM34OJD1AAEJ_w9YAAA=",
    "createdDateTime": "2018-02-02T02:49:36.7344045Z",
    "lastModifiedDateTime": "2018-02-02T02:49:36.8125307Z",
    "changeKey": "fC7Rd+rnm0WMcnjN+DiQ9QABCixjGg==",
    "categories": [],
    "originalStartTimeZone": "UTC",
    "originalEndTimeZone": "UTC",
    "iCalUId": "040000008200E00074C5B7101A82E00800000000ADEF7D76D09BD301000000000000000010000000E007AFE8A50A0948AF2115DE5A18DB92",
    "reminderMinutesBeforeStart": 15,
    "isReminderOn": true,
    "hasAttachments": false,
    "subject": "Repeat on every Saturday  morning 6:00~8:00",
    "bodyPreview": "",
    "importance": "normal",
    "sensitivity": "normal",
    "isAllDay": false,
    "isCancelled": false,
    "isOrganizer": true,
    "responseRequested": true,
    "seriesMasterId": null,
    "showAs": "busy",
    "type": "seriesMaster",
    "webLink": "https://outlook.office365.com/owa/?itemid=AAMkAGU4MjE3NDA5LTNmMmMtNDUwYi1iMjk5LTFlNTkzOTE0YTk0NABGAAAAAADK5iiXu3goQLndw7y%2B3oX3BwB8LtF36uebRYxyeM34OJD1AAAAAAENAAB8LtF36uebRYxyeM34OJD1AAEJ%2Bw9YAAA%3D&exvsurl=1&path=/calendar/item",
    "onlineMeetingUrl": null,
    "responseStatus": {
        "response": "organizer",
        "time": "0001-01-01T00:00:00Z"
    },
    "body": {
        "contentType": "html",
        "content": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<meta content=\"text/html; charset=us-ascii\">\r\n<meta content=\"text/html; charset=us-ascii\">\r\n<style type=\"text/css\" style=\"display:none\">\r\n\r\n</style>\r\n</head>\r\n<body dir=\"ltr\">\r\n<div id=\"divtagdefaultwrapper\" dir=\"ltr\" style=\"font-size:12pt; color:#000000; font-family:Calibri,Helvetica,sans-serif\">\r\n<p style=\"margin-top:0; margin-bottom:0\"><br>\r\n</p>\r\n</div>\r\n</body>\r\n</html>\r\n"
    },
    "start": {
        "dateTime": "2018-03-03T22:00:00.0000000",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2018-03-04T00:00:00.0000000",
        "timeZone": "UTC"
    },
    "location": {
        "displayName": "",
        "address": {}
    },
    "recurrence": {
        "pattern": {
            "type": "weekly",
            "interval": 1,
            "month": 0,
            "dayOfMonth": 0,
            "daysOfWeek": [
                "saturday"
            ],
            "firstDayOfWeek": "sunday",
            "index": "first"
        },
        "range": {
            "type": "endDate",
            "startDate": "2018-03-03",
            "endDate": "2018-08-18",
            **"recurrenceTimeZone": "UTC"**,
            "numberOfOccurrences": 0
        }
    },
    "attendees": [],
    "organizer": {
        "emailAddress": {
            "name": "xxx yyy",
            "address": "xxx@yyy.onmicrosoft.com"
        }
    }
}

5. The Outlook Calendar websites shows the new event on every Sunday.
![outlook_calendar](https://user-images.githubusercontent.com/25191249/35727947-e8d094da-0844-11e8-82fc-3d134e211665.png)

**Comment by jasonjoh** [comment]
Ok, your recurrence isn't quite right, which is causing the unexpected behavior. Posting just the relevant bits:

```
  "start": {
    "dateTime": "2018-03-02T22:00:00.0000000",
    "timeZone": "UTC"
  },
  "end": {
    "dateTime": "2018-03-03T00:00:00.0000000",
    "timeZone": "UTC"
  },
  "recurrence": {
    "pattern": {
      "type": "weekly",
      "interval": 1,
      "month": 0,
      "dayOfMonth": 0,
      "daysOfWeek": [
        "saturday"
      ],
      "firstDayOfWeek": "sunday",
      "index": "first"
    },
    "range": {
      "type": "endDate",
      "startDate": "2018-03-03",
      "endDate": "2018-08-18",
      "recurrenceTimeZone": "Taipei Standard Time",
      "numberOfOccurrences": 0
    }
  },
```

You've set your start date as March 2, which is a Friday. But your recurrence says that it should repeat on Saturdays (` "daysOfWeek": [ "saturday"],`). This is further confused by the time zone discrepancy. You set the start and end times in UTC, but try to set the recurrence time zone to Taipei. This won't work. (Note that you cannot set `originalStartTimeZone` or `originalEndTimeZone`, those fields are being ignored in your POST). Whenever your recurrence doesn't match the start and end times on your event (time zone differences, day differences, etc.) you get unexpected results.

The right way to do this would be to set your start and end times in Taipei along with the timezone, which should make this work.

```
{
  "reminderMinutesBeforeStart": 15,
  "isReminderOn": true,
  "subject": "Taipei - Repeat on every Saturday morning 6:00~8:00",
  "importance": "normal",
  "sensitivity": "normal",
  "isAllDay": false,
  "responseRequested": true,
  "showAs": "busy",
  "start": {
    "dateTime": "2018-03-03T06:00:00.0000000",
    "timeZone": "Taipei Standard Time"
  },
  "end": {
    "dateTime": "2018-03-03T08:00:00.0000000",
    "timeZone": "Taipei Standard Time"
  },
  "recurrence": {
    "pattern": {
      "type": "weekly",
      "interval": 1,
      "month": 0,
      "dayOfMonth": 0,
      "daysOfWeek": [
        "saturday"
      ],
      "firstDayOfWeek": "sunday",
      "index": "first"
    },
    "range": {
      "type": "endDate",
      "startDate": "2018-03-03",
      "endDate": "2018-08-18",
      "recurrenceTimeZone": "Taipei Standard Time",
      "numberOfOccurrences": 0
    }
  }
}
```

**Comment by judithting** [comment]
@jasonjoh 

Thanks for your through explanation.
According your advice, I can create a correct event right now.
I very appreciate your help. Thanks a lot!

**Comment by vanta** [comment]
> Whenever your recurrence doesn't match the start and end times on your event (time zone differences, day differences, etc.) you get unexpected results.

@jasonjoh shouldn't this result in error 400 when sending such request?

**Comment by jasonjoh** [comment]
@vanta it would be nice if it did, but it doesn't.

**Comment by shangec** [comment]
When I use Graph Exporer called "https://graph.microsoft.com/v1.0/me/calendar/getSchedule" API, the response is not right, Can you check it for me?
**Request:**
{       
     "schedules": ["chris.shang@morningstar.com"],
     "startTime": {
         "dateTime": "2019-09-17T09:00:00",
         "timeZone": "China Standard Time"
     },
     "endTime": {
         "dateTime": "2019-09-17T18:00:00",
         "timeZone": "China Standard Time"
     },
     "availabilityViewInterval": "15"
}

**Response:**
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.scheduleInformation)",
    "value": [
        {
            "scheduleId": "chris.shang@morningstar.com",
            "availabilityView": "000000000000000000000000000000000000",
            "scheduleItems": [
                {
                    "isPrivate": false,
                    "status": "free",
                    "subject": "Reminder on daily updates",
                    "location": "",
                    "start": {
                        "dateTime": "2019-09-17T09:00:00.0000000",
                        "timeZone": "UTC"
                    },
                    "end": {
                        "dateTime": "2019-09-17T09:15:00.0000000",
                        "timeZone": "UTC"
                    }
                }
            ],
            "workingHours": {
                "daysOfWeek": [
                    "monday",
                    "tuesday",
                    "wednesday",
                    "thursday",
                    "friday"
                ],
                "startTime": "08:00:00.0000000",
                "endTime": "17:00:00.0000000",
                "timeZone": {
                    "@odata.type": "#microsoft.graph.customTimeZone",
                    "bias": -480,
                    "name": "Customized Time Zone",
                    "standardOffset": {
                        "time": "00:00:00.0000000",
                        "dayOccurrence": 0,
                        "dayOfWeek": "sunday",
                        "month": 0,
                        "year": 0
                    },
                    "daylightOffset": {
                        "daylightBias": 0,
                        "time": "00:00:00.0000000",
                        "dayOccurrence": 0,
                        "dayOfWeek": "sunday",
                        "month": 0,
                        "year": 0
                    }
                }
            }
        }
    ]
}

**Comment by shangec** [comment]
The correct result should be:
"scheduleItems": [
{
"isPrivate": false,
"status": "free",
"subject": "Reminder on daily updates",
"location": "",
"start": {
"dateTime": "2019-09-17T17:00:00.0000000",
"timeZone": "UTC"
},
"end": {
"dateTime": "2019-09-17T17:15:00.0000000",
"timeZone": "UTC"
}
}
]
