### ISSUE TITLE
Clarification regarding User.EnableDisableAccount.All

### ISSUE THREAD

**Issue by manuel-falcao-magalhaes** [microsoftgraph/microsoft-graph-docs#22112]
The User.EnableDisableAccount.All is stated in the permissions grid. According to the Microsoft Graph permissions reference (https://learn.microsoft.com/en-us/graph/permissions-reference), this permission "Allows the app to enable and disable users' accounts, on behalf of the signed-in user." (Delegated) and "Allows the app to enable and disable users' accounts, without a signed-in user." (Application).

Would an authenticated user or app solely with that permission consented, _regardless of the roles they have assigned_, be able to enable or disable accounts by updating the accountEnabled for _any_ user targeted, even those with highly elevated roles assigned?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @manuel-falcao-magalhaes for asking this question.

> Would an authenticated user or app solely with that permission consented, regardless of the roles they have assigned, be able to enable or disable accounts by updating the accountEnabled for any user targeted, even those with highly elevated roles assigned?

No, for delegated scenarios. The [concept of delegated access in Microsoft Graph](https://learn.microsoft.com/en-us/graph/permissions-overview?view=graph-rest-1.0&tabs=http#delegated-permissions) still applies. And for user accounts, the statements in the note after the [permissions table](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#permissions) additionally apply. 

<img width="555" alt="image" src="https://github.com/microsoftgraph/microsoft-graph-docs/assets/14026935/f25a4e35-39ee-4a9d-a4af-b8efc66e76bd">

Yes, for app-only scenarios. I've tested to be sure and my app that had only the permission was able to disable accounts for three global administrators. The [concept of application access in Microsoft Graph](https://learn.microsoft.com/en-us/graph/permissions-overview?view=graph-rest-1.0&tabs=http#application-permissions) still applies.
