### ISSUE TITLE
$select cannot get event info in message when with delta

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2211]
Continue https://github.com/microsoftgraph/microsoft-graph-docs/issues/2018

```
GET /beta/me/mailfolders('inbox')/messages/delta
```

returns `subject`, `meetingMessageType`, etc.

But

```
GET /beta/me/mailfolders('inbox')/messages/delta?$select=subject,meetingMessageType
```

returns `subject`, but cannot return event related fields such as `meetingMessageType`.

From a user point, I think this counts a bug. If this is by design, it is a bad design.
If the delta API can return event related fields without `$select`, it has to support `$select` to allow users to return selected fields.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
