### ISSUE TITLE
The size limitation of adding a file attachment

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2212]
Hi,

Is there any size limitation of adding a file attachment to an event?

I use POST /user/${user_id}/events/${event_id}/attachments to upload a file attachment to an event.
However, if my attachment is bigger than 3 MB, the api will response failed with error message: Maximum request length exceeded. 

Is it the api limitation and is there any solution that I can upload the file attachments which is bigger than 3 MB to an existed event?

**Comment by jasonjoh** [comment]
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/event_post_attachments

> Since there is currently a limit of 4MB on the total size of each REST request, this limits the size of the attachment you can add to under 4MB.
