### ISSUE TITLE
[Outlook][Contact] fail to import same contacts

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2213]
Hi all,

When I import two contacts with the same value in office 365.
The contacts will merge into one instead create two contact items.
Moreover, the merged contact will show duplicated value like email:
![image](https://user-images.githubusercontent.com/12619781/35796462-a2df38fa-0a97-11e8-8f91-ed1c7665aebe.png)

Thanks for help

**Comment by jasonjoh** [comment]
What do you mean by import? Can you provide repro steps?

**Comment by joewutaiwan** [comment]
Hi @jasonjoh ,

Yes,

1. create a csv file for contacts
2. import here

![image](https://user-images.githubusercontent.com/12619781/36085694-90ecc200-1002-11e8-9769-964a35ac0aba.png)


Thanks!

**Comment by jasonjoh** [comment]
Ok. This isn't the place to ask support questions for Outlook. If you need help from support, please go to support.office.com for support options. If you just want to leave feedback on Outlook, click the **?** in the top right and choose the **Feedback** link.
