### ISSUE TITLE
Document of timezone name

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2216]
Hi,

I found the timezone name which I actually get from api response is different from the graph api [document](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/datetimetimezone).

For example, I get "Taipei Standard Time", but this string doesn't show in the document.
Therefore, I google "Taipei Standard Time Microsoft", and I found this web page:
https://msdn.microsoft.com/en-us/library/ms912053(v=winembedded.10).aspx

Does "timezone name", which responses from graph api, follow this web page?
Thanks.

**Comment by jasonjoh** [comment]
@judithting the doc actually says:

> The `TimeZone` property can be set to **any of the time zones supported by Windows**, as well as the following time zones names.

I think that falls under the "any of the time zones supported by Windows" clause :). The MSDN doc you found is probably good, but the safest option would be to query the Graph for a list of supported time zones:

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/outlookuser_supportedtimezones

**Comment by judithting** [comment]
@jasonjoh 

This web page is what I need!
It's very useful.
I really appreciate your help.

By the way, I found the doc says:

> Get the list of time zones that are supported for **the user**, as configured on the user's mailbox server.

Therefore, is it possible that I get different time zones response via different user account?

**Comment by jasonjoh** [comment]
Not that I've ever seen.

**Comment by judithting** [comment]
Got it.
Thanks for your help.
