### ISSUE TITLE
Error in Create administrativeUnit

### ISSUE THREAD

**Issue by dan-silver** [microsoftgraph/microsoft-graph-docs#2217]
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/administrativeunit_post_administrativeunits

The post body shouldn't be wrapped in an `administrativeUnit` object. That threw an error, removing it worked.

**Comment by dan-silver** [comment]
Also, having real values for the example instead of `displayName-value` or `visibility-value` would be much more helpful.

**Comment by JohnAustin-MSFT** [comment]
Corrected example request body per dan-silver experience.
