### ISSUE TITLE
Identity object - id property missing

### ISSUE THREAD

**Issue by Schweigi** [microsoftgraph/microsoft-graph-docs#222]
In the documentation for the [Identity object](https://graph.microsoft.io/GraphDocuments/en-us/api-reference/v1.0/resources/identity.htm) the `id` property is listed as a return value. But when I get the [file permissions](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/permission) then the `id` property is missing when the `grantedTo` Identity points to a `Group`.

Is this a bug or are permissions for groups not fully supported yet?

Example call:

```
https://graph.microsoft.com/v1.0/me/drive/items/<ITEM-ID>/permissions
```

Response:

``` json

{
    "@odata.context": "...",
    "value": [
        {
            "grantedTo": {
                "user": {
                    "displayName": "Marco",
                    "id": "<USER-ID>"
                }
            },
            "id": "<PERMISSION-ID>",
            "roles": [
                "write"
            ]
        },
        {
            "grantedTo": {
                "user": {
                    "displayName": "Engineering"
                    <======= `id` missing because `Engineering` is a group
                }
            },
            "id": "<PERMISSION-ID>",
            "roles": [
                "read"
            ]
        }
    ]
}
```

**Comment by rgregg** [comment]
@Schweigi This is a known issue right now. Groups are only returned with their display name but no identifier. Fixing this is on our backlog but we're still working through some issues that are preventing us from returning the data.

**Comment by rgregg** [comment]
@Schweigi This is a known issue that we're tracking. We don't have an ETA for a fix but we're working on it.

**Comment by NarangAshish** [comment]
We tried, it doesn't seems to be granting permission to group as well.
@rgregg Could you please confirm if current implementation doesn't support group or issue is just Group Id is not being returned in Response.

**Comment by isvargasmsft** [comment]
Hello, 

My deepest apologies for the delays in this issue. 

Thank you for bringing this into our attention. I checked with the OneDrive team and the fix is being worked already. It will take a bit longer because this design is intended to fix more than the current issue. Unfortunately, we don't have an ETA.

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).
