### ISSUE TITLE
The rule of hasAttachments in a event

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2221]
Hi,

I find the rule of hasAttachments is changed today!
About one week ago, if I use `GET /me/event` to an event which has an inline attachment, the response will show hasAttachments = true.

However, I found the `GET /me/event` will response hasAttachments = false while the event only has inline attachments.

I think the change is not make sense, because this kind of events actually have attachments and the response of `GET /me/event/$(event_id)/attachment` is not empty.

**Comment by jasonjoh** [comment]
AFAIK this has always been true. The [docs for `hasAttachments` on the message resource](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/message) explicitly warns about this:

> Indicates whether the message has attachments. This property doesn't include inline attachments, so if a message contains only inline attachments, this property is false. To verify the existence of inline attachments, parse the **body** property to look for a src attribute, such as `<IMG src="cid:image001.jpg@01D26CD8.6C05F070">`

**Comment by judithting** [comment]
@jasonjoh 
Thank for your explanation.
I think the docs for hasAttachments on the `event` resource have to mention the case of inline attachments like the docs on the message resource.

Here is my test steps. You can see the 'hasAttachments' is false in my case.
1. Create a event and insert picture inline
![inline_event](https://user-images.githubusercontent.com/25191249/36008553-c26b2b3c-0d82-11e8-85eb-a8741a646416.png)

2. Save this event, and use Graph Explorer to GET /me/event/$(event_id).
    Here is a part of the response and the hasAttachments is false.
```
{
            "@odata.etag": "W/\"BfXylo4WykyAenTZICXL5AAAk+cWww==\"",
            "id": "AAMkADVmMzE2MjY0LTZkOGYtNGI4MS1iNWMxLTljYzg3MWY5MWQxMQBGAAAAAABZMfR36TVMQ6yunaqZPvVRBwAF9fKWjhbKTIB6dNkgJcvkAACKnLIBAAAF9fKWjhbKTIB6dNkgJcvkAACSPnfdAAA=",
            "createdDateTime": "2018-02-07T07:08:08.4544892Z",
            "lastModifiedDateTime": "2018-02-09T02:17:12.9144897Z",
            "changeKey": "BfXylo4WykyAenTZICXL5AAAk+cWww==",
            "categories": [],
            "hasAttachments": false,
            "subject": "inline attachment",
            "bodyPreview": "",
            "importance": "normal",
            "sensitivity": "normal",
            "isAllDay": false,
            "isCancelled": false,
            "isOrganizer": true,
            "responseRequested": true,
            "seriesMasterId": null,
            "showAs": "busy",
            "type": "singleInstance",
            "onlineMeetingUrl": null,
            "responseStatus": {
                "response": "organizer",
                "time": "0001-01-01T00:00:00Z"
            },
            "body": {
                "contentType": "html",
                "content": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<meta content=\"text/html; charset=us-ascii\">\r\n<style type=\"text/css\" style=\"display:none\">\r\n<!--\r\np\r\n\t{margin-top:0;\r\n\tmargin-bottom:0}\r\n-->\r\n</style>\r\n</head>\r\n<body dir=\"ltr\">\r\n<div id=\"divtagdefaultwrapper\" dir=\"ltr\" style=\"font-size:12pt; color:#000000; font-family:Calibri,Helvetica,sans-serif\">\r\n<p style=\"margin-top:0; margin-bottom:0\"><br>\r\n</p>\r\n<div class=\"rps_177e\">\r\n<div>\r\n<div dir=\"ltr\">\r\n<div id=\"x_divtagdefaultwrapper\" dir=\"ltr\" style=\"font-size:12pt; color:rgb(0,0,0); font-family:Calibri,Helvetica,sans-serif,&quot;EmojiFont&quot;,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;,NotoColorEmoji,&quot;Segoe UI Symbol&quot;,&quot;Android Emoji&quot;,EmojiSymbols\">\r\n<img size=\"38242\" id=\"x_img868161\" tabindex=\"0\" width=\"140\" height=\"140\" src=\"cid:7d3c3995-d7f4-4026-8f6a-f07786b15ed1\" style=\"width:140px; height:140px\"><br>\r\n<p style=\"margin-top:0; margin-bottom:0\"><br>\r\n</p>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n</body>\r\n</html>\r\n"
            },
            "start": {
                "dateTime": "2018-02-13T00:00:00.0000000",
                "timeZone": "UTC"
            },
            "end": {
                "dateTime": "2018-02-13T00:30:00.0000000",
                "timeZone": "UTC"
            },
            "location": {
                "displayName": "",
                "address": {}
            },
            "recurrence": null
        }
}
```

**Comment by jthake-msft** [comment]
@JuForan could  the events docs be updated to represent this?

**Comment by JuForan** [comment]
@Harini84 should be the assignee.
