### ISSUE TITLE
Clarify difference between "list events" and "list calendarView"

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/microsoft-graph-docs#2222]
More context: https://stackoverflow.com/questions/48686471/is-microsoft-graph-api-calendarview-limited-to-a-single-month-how-to-get-all-ev

**Comment by emres** [comment]
It'll be also great if you can mention the use of `$top` parameter and its usage.

**Comment by Harini84** [comment]
Work item created to address the same.
