### ISSUE TITLE
Adding members to a team in bulk throws "BadGateway"

### ISSUE THREAD

**Issue by ahaverdings** [microsoftgraph/microsoft-graph-docs#22246]
I'm trying to add members in bulk but get an error as response. 

```
POST https://graph.microsoft.com/v1.0/teams/{team-id}/members/add
{
    "values": [
        {
            "@odata.type": "microsoft.graph.aadUserConversationMember",
            "roles":[],
            "user@odata.bind": "https://graph.microsoft.com/v1.0/users('{user-id}')"
        }
    ]
}
```

Response:
```
{
    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "date": "2023-07-26T15:42:27",
            "request-id": "a06b189a-911b-4cc7-86d7-620e7e7ade44",
            "client-request-id": "a06b189a-911b-4cc7-86d7-620e7e7ade44"
        }
    }
}
```

Any clue what is wrong here? I checked that the team is there, the user id exists and also tried adding the user through `POST https://graph.microsoft.com/v1.0/teams/{team-id}/members` which was successful. It's just the bulk insert that doesn't seem to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e920719-c0fc-a977-f172-2f8b84422e4f
* Version Independent ID: 2a9011b6-fe66-af8d-192c-5109e678faa2
* Content: [conversationMember: add - Microsoft Graph v1.0](https://learn.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/v1.0/api/conversationmembers-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @abshar-teams
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abshar-teams** [comment]
Ack.
Looking at it

**Comment by Prasad-MSFT** [comment]
@ahaverdings - We tried to repro this issue at our end but in our case, members are getting added successfully.
```
POST https://graph.microsoft.com/v1.0/teams/b6c60e0e-0326-4189-a136-e6ad36a70eb9/members/add

{
    "values": [
        {
            "@odata.type": "microsoft.graph.aadUserConversationMember",
            "roles": [
                "owner"
            ],
            "user@odata.bind": "https://graph.microsoft.com/v1.0/users('1640f0b5-50be-47a9-98c7-3dad61079bef')"
        },
        {
            "@odata.type": "microsoft.graph.aadUserConversationMember",
            "roles": [
                "owner"
            ],
            "user@odata.bind": "https://graph.microsoft.com/v1.0/users('6b754a41-6dc3-44c9-9eb0-113fa79a2f11')"
        }
    ]
}

```
Response:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.actionResultPart)",
    "@odata.count": 2,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMemberResult",
            "userId": "6b754a41-6dc3-44c9-9eb0-113fa79a2f11",
            "error": null
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMemberResult",
            "userId": "1640f0b5-50be-47a9-98c7-3dad61079bef",
            "error": null
        }
    ]
}
```


![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/62237649/ad816af6-8ad6-4436-86b2-d98e118156b1)

**Comment by ahaverdings** [comment]
Today I tried the exact same request again and got the following response:

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.actionResultPart)",
    "@odata.count": 1,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMemberResult",
            "userId": "{userid}",
            "error": null
        }
    ]
}
```

User was added to the team. So, I'm closing this as being glitch in the system.. it just didn't work for a day or two..
