### ISSUE TITLE
Please provide COMPLETE, compileable examples!! 

### ISSUE THREAD

**Issue by hjrb** [microsoftgraph/microsoft-graph-docs#22252]
In the section Configuring the HTTP proxy for the client
the variable tokenCredential is undefined. Where does it come from? We don't know? We can't continue?
ALSO: ALWAYS use parameter names in calls. There is many overloads - often unclear which one it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d7184ab-9db8-f040-e61f-f8cef01df25e
* Version Independent ID: ca61d03d-4a6d-21fe-31cc-08f339981ffe
* Content: [Customize the Microsoft Graph SDK service client - Microsoft Graph](https://learn.microsoft.com/en-us/graph/sdks/customize-client?tabs=csharp)
* Content Source: [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/concepts/sdks/customize-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
There are many ways to obtain a token credential depending on the type of credentials that you want to use.  There are a range of examples here https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=csharp

Providing all the initialization code detracts from the point being made in the snippet and potentially causes confusion to someone who needs to use a different credential.  If you are looking for complete working examples, you will find the tutorials better suit your needs https://learn.microsoft.com/en-us/graph/tutorials

**Comment by hjrb** [comment]
why not simply add that link as comment 
// https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=csharp
