### ISSUE TITLE
Wrong contentType returned

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2230]
I got a mail with an attachment today, the content type should be `message/rfc822` instead of `null` since it is an attached mail.

```
GET /me/messages/AAMkADBlZTUwNTkxLWVmODgtNDVhNC1iZjhlLTdjNjA1ODZlMDI5MgBGAAAAAACUbnk-iwQZRbXMgkfKtmYhBwCpTc-InBsuTYwTUBb_VIb4AAAAAAEMAACpTc-InBsuTYwTUBb_VIb4AADXss08AAA=/attachments
```

        {
            "@odata.type": "#microsoft.graph.itemAttachment",
            "id": "AAMkADBlZTUwNTkxLWVmODgtNDVhNC1iZjhlLTdjNjA1ODZlMDI5MgBGAAAAAACUbnk-iwQZRbXMgkfKtmYhBwCpTc-InBsuTYwTUBb_VIb4AAAAAAEMAACpTc-InBsuTYwTUBb_VIb4AADXss08AAABEgAQAIvlKWi6r45Gh9M_Y3NYumg=",
            "lastModifiedDateTime": "2018-02-09T20:28:37Z",
            "name": "Fwd: Hello",
            "contentType": null,
            "size": 108189,
            "isInline": false
        }

Please contact me directly, so I can send the original mail to you.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
