### ISSUE TITLE
 Could not process subscription creation payload. Are all property names spelled and camelCased properly

### ISSUE THREAD

**Issue by chenxizhang** [microsoftgraph/microsoft-graph-docs#2231]
![image](https://user-images.githubusercontent.com/1996954/36069659-09a2cc24-0f29-11e8-8915-117ffc4c080f.png)

**Comment by geeksam** [comment]
At a glance, it looks like you're asking for an expiration time 10 days later than the date you posted this issue.  Per [1], it looks like the most time you can request is just under three days.

[1] https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/subscription#maximum-length-of-subscription-per-resource-type

**Comment by jonatan-kazmierczak** [comment]
I see the same issue when I try to subscribe for events (meetings).    
I've tried it with 2 available endpoints:
1. POST https://graph.microsoft.com/beta/subscriptions
1. POST https://graph.microsoft.com/v1.0/subscriptions

### Request
```json
{
  "changeType": "created,updated,deleted",
  "notificationUrl": "[1]",
  "resource": "me/events",
  "expirationDateTime": "2018-07-20T12:00:00",
  "clientState": "0xFFFF"
}
```

[1] URL pointing to Azure function returning the content as required. Logging discloses, that there is no verification request sent to the `notificationUrl`.

### Response
```json
{
    "error": {
        "code": "InvalidRequest",
        "message": "Could not process subscription creation payload. Are all property names spelled and camelCased properly?",
        "innerError": {
            "request-id": "30b7b923-98b1-4340-bfa9-3afe19709ddc",
            "date": "2018-07-19T14:01:42"
        }
    }
}
```

The error `message` doesn't bring any value. It should rather say, which property name or value is incorrect.

I'd be glad for a correct events subscription example-request.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
