### ISSUE TITLE
Webhook Subscription Works in Beta but not in V1.0

### ISSUE THREAD

**Issue by EulerChavez** [microsoftgraph/microsoft-graph-docs#2233]
Issue:  

I use the Graph API to synchronize calendars with an app created from an Office 365 account.

I do user tests with an account outlook.com and hotmail.com (I log in oauth), all API calls work, however, as soon as I try to create a subscription with the endpoint **"v1.0/subscriptions"**, the API returns this error:

> 400 - Specified resource is not supported for MSA requests

If I create a subscription with the endpoint **"beta/subscriptions"**, the subscription is created.

**Comment by lievenjanssen** [comment]
I'm having the same issue.

**Comment by mirkods** [comment]
Save issue, any news about it?

**Comment by jasonjoh** [comment]
What resource are you trying to subscribe to?

**Comment by mirkods** [comment]
@jasonjoh on `/me/mailfolders(\'inbox\')/messages`

**Comment by jasonjoh** [comment]
Ok. This is actually a documented limitation at https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/webhooks:


Permission type | Supported resource types in v1.0
-- | --
Delegated - work or school account | contact, conversation, drive, event, message
Delegated - personal Microsoft account | None
Application | contact, conversation, event, message

Note that "personal Microsoft account" is MSA. Beta adds support for MSA resources.

**Comment by mirkods** [comment]
This finally clear why it works with some accounts and not with other ones. Thanks @jasonjoh
