### ISSUE TITLE
Filters not working with group members

### ISSUE THREAD

**Issue by amogh79** [microsoftgraph/microsoft-graph-docs#2239]
Issue: I want to filter  members from a group, when I use the filter clause in following format I am getting a not supported error. Sample get URL: https://graph.microsoft.com/v1.0/groups/{groupid}/members?$filter=startswith(givenName,'N')

Can some please help on this?

Article:

**Comment by vishwajeetrkale** [comment]
https://stackoverflow.com/questions/48765756/how-to-filter-group-members-in-microsoft-graph-api

**Comment by gjadhav-saviant** [comment]
URL you are using i.e.  https://graph.microsoft.com/v1.0/groups/{groupid}/members
Returns only directoryObject (https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/directoryobject.md) which contains object id of the resource, hence no filter will support

Workarround:
https://graph.microsoft.com/beta/groups/GROUPID/members/microsoft.graph.user?filter=yourfilter

**Comment by vishwajeetrkale** [comment]
Workaround gives below error - 
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Invalid property 'businessPhones' specified in $select.",
        "innerError": {
            "request-id": "7cffe4b2-88b8-4086-b84f-8b857cef8d65",
            "date": "2018-02-13T12:48:45"
        }
    }
}
my get URL - https://graph.microsoft.com/v1.0/groups/{groupId}/members/microsoft.graph.user?filter=startswith(displayname,'N')

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.

**Comment by ThomasPe** [comment]
I've created a UserVoice request for this feature:
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/35630488-enable-filter-on-group-members

**Comment by sharaaU7** [comment]
@ThomasPe - I don't find the link ('https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/35630488-enable-filter-on-group-members'). is it moved somewhere else?
