### ISSUE TITLE
UnknownTenantId Error undocumented

### ISSUE THREAD

**Issue by MertenK-HV** [microsoftgraph/microsoft-graph-docs#2241]
Issue: 
I got the following error while requesting a Skype For Business activity report via Microsoft Graph (i removed the customer-relevant IDs]:

REQUEST: 
https://graph.microsoft.com/v1.0/reports/getSkypeForBusinessActivityCounts(period='D30')
ERROR:
{
  "error": {
    "code": "UnknownTenantId",
    "message": "We do not recognize this tenant ID [TENANT-GUID]. Please double-check the tenant ID and try again.",
    "innerError": {
      "request-id": "[REQUEST-ID]",
      "date": "2018-02-12T16:49:26"
    }
  }
}

The documentation has no record on this error. It seems to me the error is not meaningful because the error only occurs while requesting the report API.

Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/errors.md

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
