### ISSUE TITLE
[intune] deviceManagement/notificationMessageTemplates error

### ISSUE THREAD

**Issue by jfremmegaard** [microsoftgraph/microsoft-graph-docs#2243]
https://graph.microsoft.com/v1.0/deviceManagement/notificationMessageTemplates fails both in own code and Graph Explorer. Both with own data and example from doc. Error in doc?

{
  "@odata.type": "#microsoft.graph.notificationMessageTemplate",
  "displayName": "Display Name value",
  "defaultLocale": "en-us",
  "brandingOptions": "includeCompanyLogo"
}

returns:

{
    "error": {
        "code": "BadRequest",
        "message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 8b7ec281-f527-484c-8678-2375eb0db7a3 - Url: https://fef.msub03.manage.microsoft.com/StatelessNotificationFEService/deviceManagement/notificationMessageTemplates?api-version=2017-04-01",
        "innerError": {
            "request-id": "8b7ec281-f527-484c-8678-2375eb0db7a3",
            "date": "2018-02-15T13:40:01"
        }
    }
}

**Comment by lleonard-msft** [comment]
@jfremmegaard - Thanks for the report. 

Unfortunately, there isn't enough information on your report to effectively reproduce the problem.  To troubleshoot connection issues, verify that:
- You have a valid Intune license (and the appropriate accounts have the relevant permissions).
- You've taken care of [the prerequisites](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/intune_graph_overview).
- You're using the appropriate [authentication technique](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios#application-types-and-scenarios).

For more specific help, consider reaching out [to support](https://azure.microsoft.com/en-us/support/options/) (who may be able to look directly into your request-id) or to post a question to StackOverflow.  (Use the tags `graph-api`, `azure-ad`, and `microsoft-intune`.)

**Comment by jfremmegaard** [comment]
Hello

License. prerequisites and authentication is OK. I have a dozen other MS Graph API functions in the same script that works perfectly.

But if I follow the documentation trying to create a Notification Template in Intune, it always fails, both in Graph Explorer and in my script.

I do a POST to https://graph.microsoft.com/v1.0/deviceManagement/notificationMessageTemplates  with the following JSON body:

 {
    "@odata.type": "#microsoft.graph.notificationMessageTemplate",
    "displayName": "Notifikasjon til sluttbruker",
    "defaultLocale": "en-us",
    "brandingOptions": "includeCompanyLogo, includeCompanyName, includeContactInformation"
    }

I have tried with different combinations including example from documentation. All give error code 400


{
    "error": {
        "code": "BadRequest",
        "message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 701936cb-e145-4293-945f-6a19de8061de - Url: https://fef.msub03.manage.microsoft.com/StatelessNotificationFEService/deviceManagement/notificationMessageTemplates?api-version=2017-04-01\r\n__BEGINCMEXCEPTIONMETADATA__\r\n{\r\n  \"_version\": 2,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 701936cb-e145-4293-945f-6a19de8061de - Url: https://fef.msub03.manage.microsoft.com/StatelessNotificationFEService/deviceManagement/notificationMessageTemplates?api-version=2017-04-01\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\"\r\n}",
        "innerError": {
            "request-id": "701936cb-e145-4293-945f-6a19de8061de",
            "date": "2018-02-21T17:34:02"
        }
    }
}

**Comment by jfremmegaard** [comment]
Found out via support.
"@odata.type": "#microsoft.graph.notificationMessageTemplate", should not be a part of the post JSON body. It's only in the reply.

An working example would have been nice in the documentation.

**Comment by lleonard-msft** [comment]
@jfremmegaard - Thanks for following up.  It's good to know the resolution.  I'll forward your suggestion to the right folks.  Thanks for letting us know.
