### ISSUE TITLE
[Graph] Timeouts when getting profile

### ISSUE THREAD

**Issue by cincue** [microsoftgraph/microsoft-graph-docs#2247]
We are experiencing a degraded service since February 9 trying to get https://graph.microsoft.com/v1.0/me 

The chart below shows the api response time
![image](https://user-images.githubusercontent.com/7199997/36308850-0b23b3d4-1301-11e8-9a46-40de90800d34.png)

Our authentication flow uses Microsoft's OAuth service. Here you have a response time comparison between the api calls:
Violet line for [login.microsoftonline.com/common/oauth2/v2.0/token](login.microsoftonline.com/common/oauth2/v2.0/token) and
Yellow line for https://graph.microsoft.com/v1.0/me

![image](https://user-images.githubusercontent.com/7199997/36309019-a99f2886-1301-11e8-8311-1e969d01b685.png)

The performance of this API is currently not good enough to manage the traffic we deal with.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
