### ISSUE TITLE
ErrorItemNotFound error code

### ISSUE THREAD

**Issue by dmcweeney** [microsoftgraph/microsoft-graph-docs#2248]
Issue: 
Trying to get a user's photo and when the photo does not exist the error code returned in the error response is 

```
  "error": {
    "code": "ErrorItemNotFound",
    "message": "The photo wasn't found.",
```

ErrorItemNotFound is NOT listed in the list of error codes in the article but itemNotFound is. Should my code be catering for both ErrorItemNotFound and itemNotFound.

Article:
https://developer.microsoft.com/en-us/graph/docs/concepts/errors

Thanks

Donal

**Comment by dmcweeney** [comment]
I've also encountered a case of

```
"error": {
    "code": "GetUserPhoto",
    "message": "The photo wasn't found.",
```

Which is not documented too...

**Comment by ajtruckle** [comment]
I encounter this too now when deleting calendar entries and none are found.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
