### ISSUE TITLE
Message move documentation has inconsistent response code

### ISSUE THREAD

**Issue by centromere** [microsoftgraph/microsoft-graph-docs#2253]
Issue: The response is supposed to be `201 Created`, however the example response says, `200 OK`.

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/0b47c3e9c5624c0d01a07a7cbfe4775c310ed1de/api-reference/beta/api/message_move.md#response

**Comment by jthake-msft** [comment]
@angelgolfer-ms can we confirm this.

**Comment by angelgolfer-ms** [comment]
Yes, the return code is HTTP 201 Created. I have tracked a work item to update the docs and add a real REST example. Thanks for reporting!

**Comment by angelgolfer-ms** [comment]
@centromere , you should be able to see the docs updated (per PR #2974 ) in the next day. Thanks for pointing out the error.
