### ISSUE TITLE
[Outlook][Mail] how to handle update message error code ErrorIrresolvableConflict

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2256]
Hi,

Sometimes when I update a message would return this error:
```
ErrorIrresolvableConflict
  - The send or update operation could not be performed 
  - because the change key passed in the request does 
  - not match the current change key for the item.
  error request_id : cb7e4c81-9af6-466e-a567-4522fe43f39a
  error date: 2018-02-21T06:59:26
```
I have tried to remove the change key field but it still is the same.
How should I handle this situation?

Thanks,
Joe

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
