### ISSUE TITLE
Confusion with the Excel - microsoft graph API

### ISSUE THREAD

**Issue by yagss** [microsoftgraph/microsoft-graph-docs#2259]
Hi, I'm having problems with Excel - microsoft graph API.
I have a python library for make requests to the API and I'm using a personal outlook account.
***When i use the api version "v1.0"
- When I try to create the session I get this error:

> "403 - Forbidden: Access is denied. You do not have permission to view this directory or page using the credentials that you supplied."

***When i use the api version "beta"
- When I try to add a row I send the worksheet ID as the documentation API says: `/%7B00000000-0008-0000-0100-000003000000%7D` and get this error: (I get this error in almost every petition)

> microsoftgraph.exceptions.NotFound: {'error': {'message': 'Workbook Not Found', 'code': 'DeploymentInvalidEditSession', 'innerError': {'date': '2018-02-21T20:11:18', 'request-id': '38c7184b-c02f-432d-a356-72548fd3d4bf'}}}

***In both cases in the api documentation says that I have to send the session id in the header request `workbook-session-id: {session-id}` , but sometimes this works and sometimes don't.
Regards.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
