### ISSUE TITLE
[Intune] inconsistent result between 1.0 and beta

### ISSUE THREAD

**Issue by leonzhuyihong** [microsoftgraph/microsoft-graph-docs#2263]
Issue: 
https://graph.microsoft.com/v1.0/deviceManagement/managedDevices/{Device id}
https://graph.microsoft.com/beta/deviceManagement/managedDevices/{Device id}
we got inconsistent results. V1.0 miss "managementState" which is quire critical for checking device status
Article:

**Comment by jthake** [comment]
Sorry for the delay here. Could you provide more information on what the inconsistencies are? Do they stll exist today?

**Comment by leonzhuyihong** [comment]
Hi Jeremy,

Thanks for your reply.

https://graph.microsoft.com/beta/devicemanagement/manageddevices
https://graph.microsoft.com/v1.0/devicemanagement/manageddevices

Seems beta version can provide more details comparing to V1.0 .

Cheers,
Leon

**Comment by jthake** [comment]
In our documentation we explain the difference between the beta and v1.0 endpoints. Eventually those features in the beta end point that you are using will make it up to v1.0. I am not sure on the timeframes specifically for the Intune ones, so you will need to keep an eye on our blog for those announcements.

https://developer.microsoft.com/en-us/graph/docs/concepts/versioning_and_support#versions
