### ISSUE TITLE
[Outlook] create messages to be MeetingRequest

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2269]
Hi, 

I would like to know it is possible to create message like a meeting request form,
like this in graph API?
![image](https://user-images.githubusercontent.com/12619781/36668165-62c71964-1b2b-11e8-9951-a33cf3f1c345.png)

Thanks!

**Comment by mlafleur** [comment]
No, Microsoft Graph is a REST API. It is consumed/leveraged by your application, it isn't an application frontend itself.
