### ISSUE TITLE
Use delta with $expand

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2270]
Hi,

Is it possible to use delta api with $expand parameters?
There are some information which is not contained in event object, so I want to use $expand with delta api.

However, the server responses 500 error while I send ``GET me/calendars/AAMkADVmMzE2MjY0LTZkOGYtNGI4MS1iNWMxLTljYzg3MWY5MWQxMQBGAAAAAABZMfR36TVMQ6yunaqZPvVRBwAF9fKWjhbKTIB6dNkgJcvkAAAAAAEGAAAF9fKWjhbKTIB6dNkgJcvkAAAc4z9RAAA=/calendarView/delta?startDatetime=2016-12-01T00:00:00Z&endDatetime=2018-12-30T00:00:00Z&$expand=singleValueExtendedProperties($filter=id eq 'Binary {1a15a70e-6248-4cba-9194-92aa60304a35} Name EventTimeBasedInboxReminders')``

response:
```
{
    "error": {
        "code": "InternalServerError",
        "message": "Value cannot be null.\r\nParameter name: type",
        "innerError": {
            "request-id": "0e1a98ea-e03d-46ab-b394-61538eadac83",
            "date": "2018-02-26T13:03:14"
        }
    }
}
```

Does there anything wrong in my query? 
Or is it just the limitation of Graph api?

Thanks.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
