### ISSUE TITLE
The problems of a meeting poll event

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#2276]
Hi,

I have some problems about a meeting poll event.
I created an event with two polling time on Outlook Calendar website, and I use Graph api to get the events information.
There are three events from Graph api: one is a seriesMaster event and the others are exception events with the polling time.
I found that the **_recurrence_** of the seriesMaster event is null but its type is seriesMaster.

The sereisMaster meeting poll event
```
{
            "@odata.etag": "W/\"BfXylo4WykyAenTZICXL5AAAnpBatg==\"",
            "id": "AAMkADVmMzE2MjY0LTZkOGYtNGI4MS1iNWMxLTljYzg3MWY5MWQxMQJGAAAAAABZMfR36TVMQ6yunaqZPvVRBwAF9fKWjhbKTIB6dNkgJcvkAAAAAAENAAAF9fKWjhbKTIB6dNkgJcvkAACeandyAAA=",
            "iCalUId": "040000008200E00074C5B7101A82E008000000002B2703E1CBAFD301000000000000000010000000DEBD2BD8754EAC4C8C1015D3C10879E3",
            "seriesMasterId": null,
            "showAs": "busy",
            "type": "seriesMaster",
            "start": {
                "dateTime": "2018-02-27T13:20:00.0000000",
                "timeZone": "UTC"
            },
            "end": {
                "dateTime": "2018-02-27T14:30:00.0000000",
                "timeZone": "UTC"
            },
            "recurrence": null
}
```

Q1. Is it by design or do I use the wrong way to get meeting poll event?
Q2. If it's by design, is the event which type = seriesMaster and recurrence = NULL always a meeting poll event? 
Q3. How can I create a meeting poll event via Graph api?
       I have tried to use POST /me/events to create the seriesMaster poll event, but the server only created a singleInstance event. Therefore, I can't update the time options (exception events).

**Comment by judithting** [comment]
Hi,

Is there any way to create a meeting poll event via Graph api or EWS api?
Thanks.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
