### ISSUE TITLE
allowthrottleablequeries error when filtering columns

### ISSUE THREAD

**Issue by barisbikmaz** [microsoftgraph/microsoft-graph-docs#2279]
Issue: 
When you do the following graph call to filter a list **with few items** by title

`https://graph.microsoft.com/v1.0/sites/root/lists/<listid>/items?top=10&expand=fields&filter=startswith(fields/Title,%27ba%27)`

you get the following error:

"Field 'Title' cannot be referenced in filter or orderby as it is not indexed. Provide the 'allowthrottleablequeries' preference to allow this, but be warned that such queries may fail on large lists."

I know that this call was working before. Did something changed?

**Comment by barisbikmaz** [comment]
The error message today changed to:

Field 'Title' cannot be referenced in filter or orderby as it is not indexed. Provide the 'Prefer: HonorNonIndexedQueriesWarningMayFailRandomly' header to allow this, but be warned that such queries may fail on large lists.

**Comment by mlafleur** [comment]
Could you post an example of the JSON response you're getting? 

Also, could you try adding `whatif` to your query? This won't give you a result but it will trace the call to see what it is passing into the SharePoint REST API behind the scenes. 

`https://graph.microsoft.com/v1.0/sites/root/lists/<listid>/items?top=10&expand=fields&filter=startswith(fields/Title,'ba')&whatif=true`

**Comment by barisbikmaz** [comment]
My JSON response is:

```
{
    "error": {
        "code": "invalidRequest",
        "message": "Field 'Title' cannot be referenced in filter or orderby as it is not indexed. Provide the 'Prefer: HonorNonIndexedQueriesWarningMayFailRandomly' header to allow this, but be warned that such queries may fail on large lists.",
        "innerError": {
            "request-id": "776ed60a-52f4-4757-8e58-bf65cedcc543",
            "date": "2018-03-09T08:09:50"
        }
    }
}
```

When I add &whatif=true I get:

```
{
	"Description": "Execute HTTP request",
	"Uri": "https://officeatwork1.sharepoint.com/_api/v2.0/sites('root'):/TestSubSite:/lists/25fe4032-4373-4735-a0f4-39772e4865d8/items?top=30&expand=fields&filter=startswith(fields%2fTitle%2c'ap')&whatif=true",
	"HttpMethod": "GET"
}
```

We found out that, when we add the header **HonorNonIndexedQueriesWarningMayFailRandomly** the call works as expected.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
