### ISSUE TITLE
Getting list of events for conference rooms, checking on availability?

### ISSUE THREAD

**Issue by jnlkds** [microsoftgraph/microsoft-graph-docs#2280]
Issue: 
Given the documentation, it suggests that GET /users/confrm101@xyz.com/calendar/events will pull the single instance events and the series masters,  But...if I am trying to find out if an room is available right now?  How can I determine? 

or is it better to go and use GET /users/{id | userPrincipalName}/calendarView?startDateTime={start_datetime}&endDateTime={end_datetime}

Article:
Assumption is that I can set the startDateTime to the current... and presuming that the list comes back in chronological order...we can check the first scheduled event.  But what about the recurring events as identified above?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
