### ISSUE TITLE
List React samples under Samples & SDKs

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2291]
We have two React samples right now
https://github.com/microsoftgraph?utf8=%E2%9C%93&q=react&type=&language=

Please list them at
https://developer.microsoft.com/en-us/graph/code-samples-and-sdks

**Comment by Lauragra** [comment]
@Hongbo-Miao , please file a bug and assign it to me. Thanks!

**Comment by Hongbo-Miao** [comment]
I think we can just use GitHub.

**Comment by jthake-msft** [comment]
There is work being done on graph.microsoft.com with a getting started page. We have on track to add a React one. The current code samples and SDK page is going away. I'm closing this and you'll se e the progress shortly...
