### ISSUE TITLE
Add React quick start

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2292]
Please add React quick start.

Seems like we don't have now
https://developer.microsoft.com/en-us/graph/quick-start

![image](https://user-images.githubusercontent.com/3375461/37080691-ec64ca88-219b-11e8-9990-9a999e45e8e9.png)

**Comment by jthake-msft** [comment]
Technically this is not docs. I am tracking this offline as part of our roadmap for Quick Starts.
