### ISSUE TITLE
Add React under Build your first app

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2293]
React has large number of user, the tutorial is missing under Build your first app.
https://developer.microsoft.com/en-us/graph/docs/concepts/get-started

![image](https://user-images.githubusercontent.com/3375461/37080936-bc7931be-219c-11e8-9a66-549ae06cc8f4.png)

**Comment by jthake-msft** [comment]
@jasonjoh we should add this to our backlog to build a react lab and in our merging of 'build your first app' get this done.

**Comment by jasonjoh** [comment]
This is published at https://docs.microsoft.com/graph/tutorials/react
