### ISSUE TITLE
getMailboxUsageDetail doc is out of date?

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/microsoft-graph-docs#2295]
**Issue:** 

I tried the API

```
GET https://graph.microsoft.com/v1.0/reports/getMailboxUsageDetail(period='D7')
```

by my work account.

It actually works well.

However, the doc says

> Delegated (work or school account) | Not supported.

So maybe the doc needs update?

**Article:**

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/reportroot_getmailboxusagedetail

**Comment by jthake-msft** [comment]
@angelgolfer-ms can you review this?

**Comment by angelgolfer-ms** [comment]
@jthake-msft , looped you in offline to look for the owner.
