### ISSUE TITLE
$ref odata support documentation

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-docs#2308]
Issue: I was recently that the $ref  odata capability was supported by the Graph. However it is not documented anywhere today

Article: I guess it should be here, I'm not sure though. https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters
With guidance I could issue a PR for that

**Comment by angelgolfer-ms** [comment]
@jthake-msft , following up with you offline.

**Comment by dkershaw10** [comment]
@baywet Thanks for raising this issue.  We'll discuss internally whether $ref is strictly a query parameter.  In my thinking, a query(string) parameter is something that appears in the URL **after** the `?`.  `$ref` is already documented in the places where it is relevant (i.e. when updating navigation properties) - for example https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_post_members.
However, I do see the point that we don't establish this as a calling pattern for Microsoft Graph (although it is based on OData), and that maybe this should be documented in our **Use the API** section

**Comment by baywet** [comment]
thanks for the follow up! To add to that, I think $value should be on that list as well.
