### ISSUE TITLE
event adding/removing attendees without emailing other attendees

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-docs#2309]
Issue: Today, at least as documented, it's impossible to add/remove attendees from an event without emailing the other attendees. Chatting with @yinaa earlier, she indicated the Graph should already support that even though it's not explicitly documented. 

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/event_update

**Comment by baywet** [comment]
had a follow up discussion with a PM, it is actually not possible at the moment, closing

**Comment by usedtobeNemesh** [comment]
Hello! Has anything changed on this matter in the mean time? Thank you!

**Comment by vputsenko** [comment]
@baywet Hi, any promises to have this in the future? It is actually a blocker porting EWS client to Graph API.

Thank you for your response.
