### ISSUE TITLE
Unable to create Team from O365 group

### ISSUE THREAD

**Issue by MarialL** [microsoftgraph/microsoft-graph-docs#2325]
I have two different tenants, if I try to create a Teams Team from a O365 group I have the same error:
{
    "error": {
        "code": "",
        "message": "No HTTP resource was found that matches the request URI 'https://api.teams.skype.com/v1.0/groups('groupId')/team'.",
        "innerError": {
            "request-id": "d8fb5xxx-8f1e-46c8-xxxx-xxxxxc904ff2",
            "date": "2018-03-15T10:40:08"
        }
    }
}
The used REST request was:

POST https://graph.microsoft.com/beta/groups/groupId/team

**Comment by patrick-rodgers** [comment]
This method is only available on the beta end point.

**Comment by MarialL** [comment]
If you check which REST call I've used, it's clearly specified "https://graph.microsoft.com/beta/groups/groupId/team" 
The v1.0 url is given by the error message.

**Comment by ollij** [comment]
According to the documentation (https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/team_put_teams), you should use PUT method and this only works if you are using Delegated (work or school account) | Group.ReadWrite.All permissions.

We would greatly benefit if application permissions would work with this one. I really hope we will get that soon on this method.

**Comment by MarialL** [comment]
Thanks you for your support @ollij as you say, it was my misunderstanding. And you're right, this is a trouble if you cannot use application permissions. Thanks you :)
