### ISSUE TITLE
[Intune] Error in https://graph.microsoft.com/v1.0/deviceManagement/deviceCompliancePolicies/id/assignments

### ISSUE THREAD

**Issue by jfremmegaard** [microsoftgraph/microsoft-graph-docs#2326]
The example
{
  "@odata.type": "#microsoft.graph.deviceCompliancePolicyAssignment",
  "target": {
    "@odata.type": "microsoft.graph.deviceAndAppManagementAssignmentTarget"
  }
}

Gives error 

{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation with http verb POST for request /StatelessDeviceConfigurationFEService/deviceManagement/deviceCompliancePolicies('id')/assignments.",
        "innerError": {
            "request-id": "xxxxx",
            "date": "2018-03-15T12:13:17"
        }
    }
}

The example should include example of assigning the policy to a group.

**Comment by jfremmegaard** [comment]
It works with:
POST https://graph.microsoft.com/v1.0/deviceManagement/deviceCompliancePolicies/{id}/assign

 {
 "assignments": [
 {
 "@odata.type": "#microsoft.graph.deviceCompliancePolicyAssignment",
  "target": {
    "@odata.type": "#microsoft.graph.groupAssignmentTarget",
    "groupId": "{id}"
  }}
  ]
  }

**Comment by jthake** [comment]
It appears the documentation for this api on this page needs verifying https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/intune_deviceconfig_devicecompliancepolicyassignment
