### ISSUE TITLE
CDN CSS issue 

### ISSUE THREAD

**Issue by mlafleur** [microsoftgraph/microsoft-graph-docs#2336]
The production site seems to be having issues pulling a file from the CDN: `https://cdn.graph.office.net/prod/css/msgraph-portal20180319.css`.  It is causing some odd rendering behaviors such as failing to properly display the TOC.

**Comment by Lauragra** [comment]
Thanks; we're looking into it.

**Comment by lindalu-MSFT** [comment]
@mlafleur We brought this up at our daily stand-up. The bug has been assigned to a dev and should be resolved shortly. Thanks for the catch!
