### ISSUE TITLE
FindMeetingTimes API

### ISSUE THREAD

**Issue by Muthuprasanth** [microsoftgraph/microsoft-graph-docs#2341]
Issue: 
FindMeetingTimes API throw the following error
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "Access is denied. Check credentials and try again.",
        "innerError": {
            "request-id": "94444eff-d9e0-4143-886a-bca41143ae46",
            "date": "2018-03-21T08:22:56"
        }
    }
}
Article:

**Comment by petterkjeilen** [comment]
This has already been reported back in 2016 -> https://github.com/microsoftgraph/microsoft-graph-docs/issues/559

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
