### ISSUE TITLE
/me/drive/recent returns deleted documents

### ISSUE THREAD

**Issue by RobinBreman** [microsoftgraph/microsoft-graph-docs#2348]
Issue: 

The endpoint /me/drive/recent can return deleted documents for a while.
The recent endpoint returns a collection of driveitem, i'd expect to see the 
```json
"deleted": { "@odata.type": "microsoft.graph.deleted"}
````
property, but this is not available.

/me/drive/recent?$select=deleted,name
```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "name": "file.docx"
        }
     ]
}
```

Noticed that portal.office.com also shows deleted document for a while.

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/drive_recent
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/driveitem

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
