### ISSUE TITLE
Message move behaviour

### ISSUE THREAD

**Issue by mirkods** [microsoftgraph/microsoft-graph-docs#2349]
According with the documentation https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_move this API should create a new copy of the message.

```
This creates a new copy of the message in the destination folder
```
It's not clear if the original message is preserved in its folder or is removed after the copy is completed. What am I expect?

Best,
Mirko

**Comment by jasonjoh** [comment]
It is not. Move means just that, the item is "moved" (copy is created in destination, original is deleted). The [copy operation](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_copy) would preserve the original.
