### ISSUE TITLE
Microsoft Graph API Filter on Lookup Column in SharePoint List to get Items?

### ISSUE THREAD

**Issue by BharatKhunti** [microsoftgraph/microsoft-graph-docs#2351]
I am tried to apply Filter on SharePoint List Lookup column using Microsoft graph API filter based on string value. But it didn't filter. I am able  to filter using Lookup-id. I have used below api to filter.
`https://graph.microsoft.com/v1.0/sites/{sites}/lists/{listname}/items?expand=fields(select=Id,Title,LookUpcolumn)&$filter=Fields/LookUpcolumn eq 'value'.`

**Comment by mcraiha** [comment]
Do you get error like 

> Message: Field 'Title' cannot be referenced in filter or orderby as it is not indexed. Provide the 'Prefer: HonorNonIndexedQueriesWarningMayFailRandomly' header to allow this, but be warned that such queries may fail on large lists.

?

**Comment by BharatKhunti** [comment]
No, It's give result but didn't filter. I think MS graph API lookup column filter by Value is not work.

**Comment by ParthasarathyBalan** [comment]
hi 
@BharatKhunti  did you find the fix for this? because I am facing the same problem I want to filter the lookup field with lookup value instead of lookup id it's not working in Graph API. Please provide me a solution if you found out anything. Thanks in advance

**Comment by BharatKhunti** [comment]
It seems Graph API does not support to apply filter by lookup value
As a workaround you could consider the following solution to filter by lookup value (requires two requests).
1. first step would be to query on lookup list by Title and return Id property
2. and then to query to current list by lookup Id

**Comment by CaramelHeaven** [comment]
Hello. Can you give some examples of how to solve this problem? I have the same problem, and I need to filter the list items. Thanks in advance.

**Comment by CaramelHeaven** [comment]
If I understood correctly, you had to use a filter on a custom column. If so, then I found a solution. I'm adding it here for future people :) 

`https://graph.microsoft.com/v1.0/sites/{siteId}/lists/{listId}/items?$filter=fields/{Lookup Column name} eq 'value'&$expand=fields`

Also u can use select: .`...'value'&$expand=fields(select=Id, Title...)`

**Comment by BharatKhunti** [comment]
Hello @CaramelHeaven,

It work fine for simple column(like Text, Number, Currency etc). But It didn't work for Look Up column. For lookup column filter you have to filter by LookUp Id. You can refer below query to filter look up column.
`https://graph.microsoft.com/v1.0/sites/{siteID}/lists/{listID}/items?$filter=fields/{LookUp Column Name+LookupId} eq itemID &$expand=fields($select=Id, Title, LookUpColumn)`

Before, filter by Lookup id you should get Item Id from Look up List
 `https://graph.microsoft.com/v1.0/sites/{siteID}/lists/{LookUplistID}/items?$filter=fields/{Column Name} eq 'Value' &$expand=fields($select=Id)`
