### ISSUE TITLE
even if i had added the mail delegate for special user, but i still can not access his messages via microsoft  graph api

### ISSUE THREAD

**Issue by iovex** [microsoftgraph/microsoft-graph-docs#2361]
Issue: 
even if i had added the mail delegate for special user, but i still can not access his messages(outlook mail ) via microsoft 
graph messages api(beta or 1.0) (some user's email can be accessed ,but other can not)

refer to links:
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_list_messages

Article:
i had refered to this article to add the mail delegate 
https://support.microsoft.com/en-us/help/10048/accessing-other-people-s-mailboxes-in-office-365

Note：
the signed-in user is the global admin
had added  the permissons listed in
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_list_messages

**Comment by iovex** [comment]
after some tests , finally i can access the users mails successfully, it seems that there are some latency between setting the mail delegate and invoking the messages api successfully.
you may need to wait for more than one hour

**Comment by iovex** [comment]
but i still want to know why the lantency is so long

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
