### ISSUE TITLE
[Outlook][Calendar][document] locationEmailAddress in graph

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2367]
Hi all,

Here is a special key in event["location"] structure:
`locationEmailAddress | String | Optional email address of the location.`

But I have no idea how to add corresponding value from office 365 UI.
Could you provide some case for this?

Furthermore, Graph API In China has no such key.
It is the error response from creating an event
```
{
    "error": {
        "code": "RequestBodyRead",
        "message": "The property 'locationEmailAddress' 
does not exist on type 'Microsoft.OutlookServices.Location'. 
Make sure to only use property names that 
are defined by the type or mark the type as open type.",
        "innerError": {
            "request-id": "2d61cd6f-28f6-4f3c-9779-39675b4d13f0",
            "date": "2018-03-28T02:31:43"
        }
    }
}
```

Thank you,

Joe

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
