### ISSUE TITLE
findmeetingtimes not considering All-Day meetings?

### ISSUE THREAD

**Issue by cyberpine** [microsoftgraph/microsoft-graph-docs#2388]
seems to suggest times and locations already in an all day meeting.

**Comment by jthake** [comment]
Apologies for the late reply here. Is this still an issue for you @cyberpine ? Do you have any examples of this you can show more detail for?

**Comment by cyberpine** [comment]
we are fine. please close.

**Comment by jthake** [comment]
OK thanks for the update.
