### ISSUE TITLE
/me/events unable to update (patch) event location with an actual location, only text allowed or possible?

### ISSUE THREAD

**Issue by cyberpine** [microsoftgraph/microsoft-graph-docs#2389]
Seems only allows "text" in the location.  Is there an option or way to place an actual location object in Location field of a meeting event?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
