### ISSUE TITLE
Groups Porperties

### ISSUE THREAD

**Issue by LagerstedtMarcus** [microsoftgraph/microsoft-graph-docs#2390]
Issue: 

The property "allowExternalSenders" is not a property that can be changed or selected. Given the information in the API, it looks like it should be possible to get the property or change it.

Really nice if it could be implemented if it exists in the docs.

**Comment by mlafleur** [comment]
This is documented in the [Known Issues ](Setting the allowExternalSenders property
There is currently an issue that prevents setting the allowExternalSenders property of a group in a POST or PATCH operation, in both /v1.0 and /beta. ) area:

> **Setting the allowExternalSenders property**
> There is currently an issue that prevents setting the allowExternalSenders property of a group in a POST or PATCH operation, in both `/v1.0` and` /beta`.

**Comment by LagerstedtMarcus** [comment]
When will this be solved ? Is it possilbe to do something to work around this problem ? 

This is important for a costumer to automatically change this, therefore this functions is important for me. 
Also resents update will change how groups are created, and therefore make this a important feature in the api combined with autosubscribenewmembers attribute

**Comment by fubizitch** [comment]
We've been waiting for a long time for this fix.  It's difficult to make groups in the API and then have to resort to Powershell to fix...plus, we cannot add users until the autoSubscribeNewMembers flag has been set - otherwise users do not get messages to their inbox.

**Comment by LagerstedtMarcus** [comment]
Yeah, I have noticed that. 

And they are releasing feature that makes you need the possibilities to change this values. Also, this is not supported to make a global setting for your tenant and therefore you can change these settings without PowerShell(Which isn't fun to have in the backend) or postman where you sign in as a user. 

We have a lot of groups in the organization (over 3k groups) and you cannot handle this setting with PowerShell(Works but not suitable to have code in the backend to do this automatically ) or manually. 

other things in the API works really great, but please fix this, I would really appreciate this.

**Comment by jthake-msft** [comment]
Closing as a known issue and being worked on.

**Comment by ethanfann** [comment]
"Closing as a known issue and being worked on."

Been almost a month since closed due to "being worked on", but no updates.

Can we re-open this?

**Comment by jthake-msft** [comment]
We do not currently have a mechanism for indicating when things will be rolled out at this granular level unfortunately. And this issues list is specifically about documentation content. The docs state this is a known issue, let me chase with the PMs who own this and ask if this is already in the pipe or whether its further out.

**Comment by ethanfann** [comment]
I truly appreciate it.

**Comment by LagerstedtMarcus** [comment]
I would also like to know how the issue evolves.

**Comment by LagerstedtMarcus** [comment]
It is a known issue. But I get a feeling this isn't being worked on. 

Been around 1 year since I first encountered the problem, Groups has been active for longer, and this issue still stands. No option for a global setting within the tenant or a fix for the problem. I don't see the case why this cant be added for application tokens. Could i get some kinda of example? or a update of some sort? to ensure me that its being worked on. @jthake-msft
