### ISSUE TITLE
Documentation page navigation menu is empty

### ISSUE THREAD

**Issue by wctr-io** [microsoftgraph/microsoft-graph-docs#2428]
Issue: 
Documentation page navigation menu is empty
Article:
https://developer.microsoft.com/en-us/graph/docs/concepts/overview

**Comment by Lauragra** [comment]
Thanks; we're working on a fix and it should be back up on the site shortly.

**Comment by Lauragra** [comment]
This issue is now fixed on the live site. It may take a few hours for the cache to clear for all users. Thanks.
