### ISSUE TITLE
List orgContact  for beta documentation doesn't list the required scope

### ISSUE THREAD

**Issue by mikeholtkamp** [microsoftgraph/microsoft-graph-docs#245]
This page http://graph.microsoft.io/en-us/docs/api-reference/beta/api/orgcontact_list doesn't have any required scopes listed this seems incorrect to me

**Comment by jthake-msft** [comment]
Permission scopese have been added here https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/orgcontact_list
