### ISSUE TITLE
@microsoft.graph.downloadUrl suddenly returns 403 FORBIDDEN for sharepoint files

### ISSUE THREAD

**Issue by kimrohdin** [microsoftgraph/microsoft-graph-docs#2458]
Since last friday (13th april) we are getting FORBIDDEN when trying to access the graph downloadUrl when authenticating as an Azure APP and fetching files from sharepoint. This is working through graph explorer when authenticating as an user.

I have looked through the token generated and all the permissions is the same for both the app and the user.

This is very urgent. It seems like this is due to some release? Bug? Please urgent fix this.

**Comment by Christian-Stahl** [comment]
.. and suddenly it just worked again for us, a temporary bug in the graph explorer?

**Comment by MIchaelMainer** [comment]
This was fixed. https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/257#issuecomment-381715343
