### ISSUE TITLE
Browsing experience for docs in iPad are not great

### ISSUE THREAD

**Issue by wobba** [microsoftgraph/microsoft-graph-docs#2467]
Browsing graph docs on iPad is cumbersome. The menu overlays, but closes quickly when trying to scroll etc. Would be great if we could force desktop layout or have the mobile experience work better.

Seen on API browsing at for example https://developer.microsoft.com/en-us/graph/docs/concepts/overview

**Comment by jthake** [comment]
Hey @wobba we are currently working on migrating to the docs.microsoft.com platform. The investments there will mean we'll get a few quick wins with experiences for things like iPad scrolling support.
