### ISSUE TITLE
Support for expanding photo in /users query

### ISSUE THREAD

**Issue by LoungeFlyZ** [microsoftgraph/microsoft-graph-docs#251]
We would like to tell if someone has a photo when querying the /users endpoint.

E.g.
`https://graph.microsoft.com/beta/users?$expand=photo`

Would this be considered?

Thanks.

**Comment by yinaa** [comment]
We will support this with batch not expand, we can't have both the binary and the json payload in the response. [Here](https://github.com/microsoftgraph/microsoft-graph-docs/issues/762) is the link to the request in UserVoice and we already have internal work items tracking this,
