### ISSUE TITLE
PATCH /Groups/{id}

### ISSUE THREAD

**Issue by LagerstedtMarcus** [microsoftgraph/microsoft-graph-docs#2510]
Issue: 
Hello,

When I try to patch the value for a group like I do when changing the visibility of a group with PATCH.
for AllowExternalSenders I get the errors:

```
Failed - stringContent={"allowExternalSenders":true} - response.Content,={
 "error": {
   "code": "ErrorAccessDenied",
   "message": "Access is denied. Check credentials and try again.",
   "innerError": {
     "request-id": "ce49c54d-8b80-4560-b602-0f74f4ff85fd",
     "date": "2018-04-26T07:34:51"
   }
 }
}
```

And for attribute autoSubscribeNewMembers

```
Failed - stringContent={"autoSubscribeNewMembers":false} - response.Content,={
 "error": {
   "code": "ErrorAccessDenied",
   "message": "Access is denied. Check credentials and try again.",
   "innerError": {
     "request-id": "dbcf93bc-11f9-4123-a381-39b2a9f7cbd3",
     "date": "2018-04-26T07:31:39"
   }
 }
}

```
According to the Documentation for Graph API I'm supposed to be able to change these setting with a PATCH command from an application that is verified with clientid and secretkey.

Other commands work fine with the same Token but not these two commands. 

If I verify with a user through postman I can run the commands but through a C# application, I get these errors.

All scopes are added to eliminate not having the right scopes.

Link for documentation:
Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_update

**Comment by fubizitch** [comment]
We've been waiting for a long time for this fix.  It's difficult to make groups in the API and then have to resort to Powershell to fix...plus, we cannot add users until the autoSubscribeNewMembers flag has been set - otherwise users do not get messages to their inbox.

**Comment by mlafleur** [comment]
See the [Known Issues ](https://developer.microsoft.com/en-us/graph/docs/concepts/known_issues#groups-and-microsoft-teams )documentation for this:

> Examples of group features that support delegated and app-only permissions:
>
> - Creating and deleting groups
> - Getting and updating group properties pertaining to group administration or management
> - Group directory settings, type, and synchronization
> - Group owners and membership
>
>Examples of group features that support only delegated permissions:
> - Group conversations, events, photo
> - **External senders**, accepted or rejected senders, group subscription
> - User favorites and unseen count
> - Microsoft Teams channels and chats

**Comment by LagerstedtMarcus** [comment]
@mlafleur Is there any possibility that these settings from the API could be fixed before you launch the new settings for groups are taking into production.
That all member automatically subscribe to all messages in a group?
Feature ID: 27326
Subject : Groups in Outlook - Members of newly created groups will receive all group email in their inbox by default

**Comment by jthake-msft** [comment]
Closing as known issue.

**Comment by fraserjordan** [comment]
@jthake-msft when will this 'known issue' be fixed? The documentation states the following:
![image](https://user-images.githubusercontent.com/8469994/46696527-d792ef80-cc6e-11e8-9823-c421f3b7373f.png). But I still get access denied when attempting to make this call?

**Comment by jthake-msft** [comment]
@fraserjordan just to eliminate a few things. Have you tried it in graph explorer signed in with the same user?

**Comment by fraserjordan** [comment]
@jthake-msft Yes, and yes it worked fine in there, which I found strange. I have given my app application permissions for group-read-write as stated in the documentation, but to no avail.

**Comment by jthake-msft** [comment]
mmm that's hard to troubleshoot without seeing your code. anyway you can repro this in a small project on the platform you're building so I can take a look?

**Comment by fraserjordan** [comment]
Would I be correct in saying I can't make this request using application permissions? Do I need Delegate permissions?

**Comment by jthake-msft** [comment]
App permissions should work as per the doc.

**Comment by fraserjordan** [comment]
Hmmm... ok, please see code here: https://github.com/fraserjordan/GroupExampleApp/tree/master/GroupExampleApp

**Comment by tfrancois** [comment]
Microsoft, when is this going to be fixed?!  This leaves a lot to be desired in terms of the type of support we are seeing for these types of issues.  It's extremely worrisome to me and speaks volumes.

**Comment by rivkia** [comment]
face with the same issue, please let us know when is it fixed
