### ISSUE TITLE
 'Get a user' documentation: OData $select query parameter doesn't select as documented

### ISSUE THREAD

**Issue by Velojet** [microsoftgraph/microsoft-graph-docs#2517]
Issue: OData $select query parameter doesn't select

Article: 
The MS Graph 'Get a user' documentation says: "If you need a different property set, you can use the OData $select query parameter" but it appears not to work, either in my code or in the Graph Explorer. In both, the query `https://graph.microsoft.com/v1.0/me?$select=displayName` returns the _full set_ of user properties.
Ref: <https://stackoverflow.com/questions/50013804/microsoft-graph-odata-select-query-parameter-doesnt-select>
(Query works as documented for some, but not for me.)

**Comment by jasonjoh** [comment]
Posted an answer on SO, but this looks like a difference in behavior between MSA and Office 365 users.

**Comment by jasonjoh** [comment]
Per #2117 this isn't supported for MSA. We need to update the documentation here.

**Comment by Velojet** [comment]
Thanks very much, Jason, for your explanation and the cross-ref to  [#2117](https://github.com/microsoftgraph/microsoft-graph-docs/issues/2117) (I missed picking that up). Good to hear that the documentation will be updated : )
