### ISSUE TITLE
Outlook task update and delete methods not working as documented

### ISSUE THREAD

**Issue by gabrielittner** [microsoftgraph/microsoft-graph-docs#2528]
Issue: 

The documentation lists the following paths to update and delete tasks.

```
PATCH /users/{id|userPrincipalName}/outlook/tasks/{id}
PATCH /users/{id|userPrincipalName}/outlook/taskFolders/{id}/tasks/{id}
PATCH /users/{id|userPrincipalName}/outlook/taskGroups/{id}/taskFolders/{id}/tasks/{id}

DELETE /users/{id|userPrincipalName}/outlook/tasks/{id}
DELETE /users/{id|userPrincipalName}/outlook/taskFolders/{id}/tasks/{id}
DELETE /users/{id|userPrincipalName}/outlook/taskGroups/{id}/taskFolders/{id}/tasks/{id}
```

When I try to use the second one of each I'm getting this error:

```
{
    "error": {
        "code": "NavigationNotSupported",
        "message": "Recursive navigation is not allowed after property 'Tasks' according to the entity schema.",
        "innerError": {
            "request-id": "b0cff3b9-9f6b-4f47-939c-1a93ac2c6eef",
            "date": "2018-04-29T10:41:39"
        }
    }
}
```

Doing the same request without the `taskFolders/{id}` (so the first variant) works just fine.

Article:

https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/outlooktask_update
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/outlooktask_delete

**Comment by gabrielittner** [comment]
The following attachment related methods have the same issue.

```
GET /users/{id | userPrincipalName}/calendars/{id}/events/{id}/attachments
```
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/event_list_attachments
```
POST /users/{id | userPrincipalName}/calendars/{id}/events/{id}/attachments
```
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/event_post_attachments
```
GET /users/{id|userPrincipalName}/outlook/taskFolders/{id}/tasks/{id}/attachments
```
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/outlooktask_list_attachments
```
POST /users/{id|userPrincipalName}/outlook/taskFolders/{id}/tasks/{id}/attachments
```
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/outlooktask_post_attachments
```
DELETE /users/{id | userPrincipalName}/calendars/{id}/events/{id}/attachments/{id}
```
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/attachment_delete

**Comment by gabrielittner** [comment]
@jasonjoh Thanks for the response. I wasn't completely sure about that because the docs always say something like 
> Attachments for an event in the user's or group's default calendar.

That makes it sound like you need to use a more specific path for attachments of events in a secondary calendar (same for folders etc.).

**Comment by jthake-msft** [comment]
@jasonjoh  nudge...

**Comment by jasonjoh** [comment]
My bad! Assigning to myself, I'll see about updating these docs

**Comment by yaalaa** [comment]
`Recursive navigation is not allowed after property 'Events' according to the entity schema.`, 
`beta` API

**Comment by DavidSlechticky** [comment]
Hello,
I am trying to delete event in shared calendar group having shared calendar and event. I want to delete event in this shared calendar:
DELETE /me/calendargroups/{id}/calendars/{id}/events/{id}   with response:

{
    "error": {
        "code": "NavigationNotSupported",
        "message": "Recursive navigation is not allowed after property 'Calendars' according to the entity schema.",
        "innerError": {
            "request-id": "ea35aa0c-efdb-46a4-921c-4c87eeddc822",
            "date": "2019-08-16T07:01:16"
        }
    }
}
Can you please help with that?
Regards,
David
