### ISSUE TITLE
New TOC

### ISSUE THREAD

**Issue by mlafleur** [microsoftgraph/microsoft-graph-docs#2610]
I really love the new TOC layout. It is far more approachable for developers who are new to Graph. Excelent work. 

One request: It would be helpful if the "groups"  were also collapsible. For developers flipping through the _reference_ docs, the current layout forces the user to scroll pretty far down.  The ability to collapse "learn" would make it a lot easier to navigate.

**Comment by jthake** [comment]
We are currently in the process of migrating to docs.microsoft.com @mlafleur . I'll reach out to you with some working prototypes to get feedback offline ;-)
