### ISSUE TITLE
contentUrl is useless when handling embedded media

### ISSUE THREAD

**Issue by ssshake** [microsoftgraph/microsoft-graph-docs#2621]
What is the point of providing contentUrl, which returns a static html page, if all of the embedded resources (images, audio recordings, etc) are external links to another graph API call that requires a bearer token.

This could never work. Providing a static html file is great because I can make one call and render a document in our custom tool. But the  document is broken because all of the resources will be broken links / 401's.

Why wouldn't you have the option to base64 encode all of the resources so they are included in this static file?

I can't possibly see how anyone would use contentUrl to do anything meaningful. The best work around I can come up with is parse the static html for src= and data=, make subsequent API calls to fetch those resources, including bearer token, then base64 encode each, and replace the original resource urls with the base64 encoded data. Which is a lot of work and a pain. But short of doing that how else can this be used to do anything meaningful??

**Comment by mlafleur** [comment]
You didn't specify which APIs you're talking about but I assume OneNote?

You can [request pre-authed](https://developer.microsoft.com/en-us/graph/docs/concepts/onenote-get-content#page-html-content) URIs by adding ` preAuthenticated=true` to your GET request. This will set the `src` for each `img` tag to a pre-authenticated URI to the image. These URIs remain active for ~1hr.

**Comment by ssshake** [comment]
Hey thanks, as you saw I reported a bug with that argument, I found it after the fact. Maybe the docs could show this more clearly as I had to do some digging to find it. Otherwise this can be closed.

p.s. from a security stand point I'm sure it's unlikely for anyone to discover that public URL but I dont like the idea of private, corporate content being temporarily made available to anyone with that link. Which is why I think it would be more secure to just return inlined base64 content in the mark up.

**Comment by mlafleur** [comment]
I'd argue that encoding it as inline base64 is even riskier. A temporary URI means you've exposed content for a short duration of time. If someone were to discover the URL later it wouldn't be useless. Encoding it inline, however, would result in that image being accessible permanently.,

**Comment by ssshake** [comment]
That's not correct as far as I understand it. The contentUrl isn't accessible publicly, it requires a bearer token to retrieve the content. So the markup and inlined data would be secured behind oauth. Where as the temporary exemption is not.

**Comment by mlafleur** [comment]
The assumption with `preAuthenticated` is that you're specifically looking to share the images to an unauthenticated or otherwise external user. 

If you want to secure it from end-to-end, you could always pull down the images on the backend and convert them to base64 data URIs before you return it to the client. I've done this myself in the past. It works well and reduces exposure (in one case I also hide the source so all they saw was the content without seeing where it came from). Another option would be to include the Authorization header with each IMG request (although this seems burdensome).
