### ISSUE TITLE
OneNote preAuthenticated=true not working as documented/expected

### ISSUE THREAD

**Issue by ssshake** [microsoftgraph/microsoft-graph-docs#2624]
Issue: Onenote Input And Output Page has incorrect info about preAuthenticated=true.

If you set preauthenticated=true, when you request a page any embedded content such as images still fail to load saying:

{
  "error": {
    "code": "40001",
    "message": "The request does not contain a valid auth token.",
    "@api.url": "https://aka.ms/onenote-errors#C40001"
  }
}

However, the interesting part is if you replace the left half of the url, replace graph.microsoft.com/... with the onenote.com api url, it works. Which means that submitting the get request to graph with preauthenticated=true, actually does something in the back end. But, consuming the document link that comes back failed through graph, but succeeds through onenote's legacy api.

Article: https://developer.microsoft.com/en-us/graph/docs/concepts/onenote_input_output_html

![image](https://user-images.githubusercontent.com/1675868/39838281-f6d12f24-53a6-11e8-9bda-8660989cd958.png)

**Comment by mlafleur** [comment]
I can replicate the error, albeit with a slightly different error:

```json
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Bearer access token is empty.",
    "innerError": {
      "request-id": "2637c8fc-aa01-4321-9d34-341cc4794596",
      "date": "2018-05-10T21:46:47"
    }
  }
}
```
Could you expand on what you mean by "replace graph.microsoft.com/... with the onenote.com api url"? An example of a working and non-working URI would be super helpful.

**Comment by ssshake** [comment]
Hey, yes I'm saying that onenote and graph both have the same api calls. If you make the same api call to the onenote domain instead of graph it returns the expected content. 

So it looks to me like graph respect setting the flag, but doesnt respect processing the flag. 

Setting preauthenticated=true returns a url for the content. When you hit that url, all sources in that markup have the publicAuth=true appended to them. But when your browser requests that source (an image for example) the api errors out.

When you do that same request for an image on the onenote api (not graph) it respects publicAuth=true and returns the image.

**Comment by mlafleur** [comment]
An example of a working and non-working URI would be super helpful.

**Comment by JamesWinterburn** [comment]
I have this exact issue. For example, I am making the following call to get page content from a notebook stored on a team site:

`https://graph.microsoft.com/v1.0/sites/{0}/onenote/pages/{1}/content?preAuthenticated=true`

This works perfectly and returns the html content including the <img> tags. However, when the browser tries to actually fetch the image specified in the src, it gives the following error in the browser console:

`Failed to load resource: the server responded with a status of 401 (Unauthorized)`

My understanding is that preAuthenticated=true should ensure we have access to the images as well after a call to retrieve the content is successful

Unfortunately, I've not been able to get it working using the onenote.com api URL, though suspect this is because the notebook is stored on a team site on O365

**Comment by ssshake** [comment]
Why was this closed? You have an actual bug in production, is this going not to be addressed?

I don't know what other information I can give you. I don't know how to supply a "working URI" on MS Graph because as far as I can tell the feature does not work at all.

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
