### ISSUE TITLE
Groups Graph Endpoint Limit on Results

### ISSUE THREAD

**Issue by injector22** [microsoftgraph/microsoft-graph-docs#2631]
Is there a parameter that specifies the quantity of results returned by the groups Graph API?

https://graph.microsoft.com/v1.0/groups

When I query the endpoint it only ever returns 100 groups.

**Comment by wobba** [comment]
You can get up to 500 I think with $top=500, but you should implement paging looking at the `@odata.nextLink` parameter being returned in your response.
