### ISSUE TITLE
Documentation: Incomplete Format description of Extended Properties

### ISSUE THREAD

**Issue by krasnor** [microsoftgraph/microsoft-graph-docs#2637]
In the documentation for [extended properties](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/extended-properties-overview) the list of 

Valid `id` formats for extended properties seems to be incomplete. There are actually three valid syntaxes:

 - `MapiPropertyType namespaceGuid Name propertyName`
 - `MapiPropertyType namespaceGuid Id propertyId`
 - `MapiPropertyType propertyTag` (missing entry for properties in the default MAPI Space)

**Comment by jthake** [comment]
@angelgolfer-ms can you look into this?

**Comment by ArunMSFT** [comment]
@jthake-msft @angelgolfer-ms Please assign this to me

**Comment by ArunMSFT** [comment]
Thanks @krasnor for pointing out the gap, we'll update the doc soon.

**Comment by jthake-msft** [comment]
@ArunMSFT  has this been updated? I couldn't see it.

**Comment by angelgolfer-ms** [comment]
@krasnor , thank you for your patience. I added the proptag format description to the docs (PR #2996 ). You should be able to see the content updates within the next day on the live site.
