### ISSUE TITLE
MS Graph missing documentation on how to unassign / remove policy from ServicePrincipal or Application

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#2655]
Issue: 
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/policy_assign is to assign a policy 
Looks like we are missing the topic to remove/unassign a policy for a service principal / application

Article:

**Comment by davidmu1** [comment]
The policy content has been restructured. The link in this issue redirects to the overview where it does not appear that a change is needed. Closing the issue.
