### ISSUE TITLE
Undocumented limit on Planner API

### ISSUE THREAD

**Issue by dzhavat** [microsoftgraph/microsoft-graph-docs#2685]
Issue: When I try to create a new plan and set the `owner` to an id of an existing group that already has a plan, I get a `403` error with a message that is not documented.

This is the response object: 

![image](https://user-images.githubusercontent.com/1096332/40489737-0e8ceb5c-5f6a-11e8-8f3c-ef6c42e2db66.png)

Maybe this error is somehow related (similar) to the `MaximumProjectsOwnedByUser` that is already documented under `Planner error status codes`. Or maybe the error is the same but the value has been changed.

Article: [Planner API Overview](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/planner_overview)

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
