### ISSUE TITLE
Failed to create upload session on existing file by id

### ISSUE THREAD

**Issue by amtlib-dot-dll** [microsoftgraph/microsoft-graph-docs#2699]
Environment: OneDrive Personal

Steps to reproduce:
1. Create a file with id `xxxxxxxxxxxxxxxx!xxx`
2. `POST /me/drive/items/xxxxxxxxxxxxxxxx!xxx/createUploadSession`

Expected behaviour:
* `HTTP 2xx` with the upload URL

Actual behaviour:
* `HTTP 400` with response
```json
{
  "error": {
    "code": "invalidRequest",
    "message": "File name not provided in url",
    "innerError": {
      "request-id": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "date": "xxxx-xx-xxTxx:xx:xx"
    }
  }
}
```

As stated by the third example on https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem_createuploadsession.md#http-request, the aforementioned behaviour is not expected. Either the API or the documentation is wrong. Thank you for reviewing this issue.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
