### ISSUE TITLE
No internetMessageHeaders in sent messages

### ISSUE THREAD

**Issue by dorshemer** [microsoftgraph/microsoft-graph-docs#2716]
Even when explicitly requesting internetMessageHeaders, I only get them on inbound messages:

`https://graph.microsoft.com/v1.0/me/messages?$select=internetMessageHeaders,from,toRecipients&$top=3
`

Getting 3 messages: first two are outbound w/o internetMessageHeaders, last one in inbound with it. Checked with more results and it seems consistent.

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('25edea58-53a2-45b4-a9db-ebfeec4499fb')/messages(internetMessageHeaders,from,toRecipients)",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/messages?$select=internetMessageHeaders%2cfrom%2ctoRecipients&$top=3&$skip=7",
    "value": [
        {
            "@odata.etag": "W/\"CQAAABYAAAAH4lhl6lYyTo2SHe2mEko/AABpal+c\"",
            "id": "AAMkADYzMzNjYjEwLTJiNDMtNDMxMy1hOTA5LTU3OTgxYzlhNmYxZABGAAAAAACgtKjWhV8QS4Jb9YZxtLKDBwAH4lhl6lYyTo2SHe2mEko-AAAAAAEJAAAH4lhl6lYyTo2SHe2mEko-AABpW7BDAAA=",
            "from": {
                "emailAddress": {
                    "name": "{ME}"
                }
            },
            "toRecipients": [
                {
                    "emailAddress": {
                        "name": "{PERSON1}"
                    }
                }
            ]
        },
        {
            "@odata.etag": "W/\"CQAAABYAAAAH4lhl6lYyTo2SHe2mEko/AABpal9/\"",
            "id": "AAMkADYzMzNjYjEwLTJiNDMtNDMxMy1hOTA5LTU3OTgxYzlhNmYxZABGAAAAAACgtKjWhV8QS4Jb9YZxtLKDBwAH4lhl6lYyTo2SHe2mEko-AAAAAAEJAAAH4lhl6lYyTo2SHe2mEko-AABpW7BCAAA=",
            "from": {
                "emailAddress": {
                    "name": "{ME}",
                }
            },
            "toRecipients": [
                {
                    "emailAddress": {
                        "name": "{PERSON2}"
                    }
                }
            ]
        },
        {
            "@odata.etag": "W/\"CwAAABYAAAAH4lhl6lYyTo2SHe2mEko/AABpal9N\"",
            "id": "AAMkADYzMzNjYjEwLTJiNDMtNDMxMy1hOTA5LTU3OTgxYzlhNmYxZABGAAAAAACgtKjWhV8QS4Jb9YZxtLKDBwAH4lhl6lYyTo2SHe2mEko-AAAAAAEMAAAH4lhl6lYyTo2SHe2mEko-AABpW4kfAAA=",
            "from": {
                "emailAddress": {
                    "name": "{PERSON1}"
                }
            },
            "toRecipients": [
                {
                    "emailAddress": {
                        "name": "{ME}"
                    }
                }
            ]
            "internetMessageHeaders": [
                {
                    "name": "Received",
                    "value": "from VI1PR0101MB2109.eurprd01.prod.exchangelabs.com (2603:10a6:803:1::18) by HE1PR0101MB2108.eurprd01.prod.exchangelabs.com with HTTPS via VI1PR0502CA0005.EURPRD05.PROD.OUTLOOK.COM; Thu, 31 May 2018 07:00:45 +0000"
                }
                // ... etc                
            ]            
        }
    ]
}
```

**Comment by jasonjoh** [comment]
If by outbound you mean messages in the Sent Items folder, that's expected. Internet message headers get added to the message once they actually go out via SMTP to recipients. Before that, they're still all internal to the user's mailbox. Since they haven't gone through transport, there's no headers.

**Comment by dorshemer** [comment]
I see. Perhaps this should be documented in the API reference, it doesn't state that anywhere I looked :)

I don't think this is the right behavior, for what it's worth. The message has already been sent (that's even the folder's name), so the headers are available _somewhere_. It makes going through messages in `/me/messages` harder because you can't expect all of them to have headers, and makes it impossible to get important data from the actual sent headers (specifically the `References `and `In-Reply-To` headers).

**Comment by jasonjoh** [comment]
This is a limitation of the internals of Exchange server, which does not store things natively as MIME, so things like `References` and `In-Reply-To` just don't exist. That message in Sent Items is a copy (in Exchange-native format) of the message that gets sent out. The message that goes out would go through MIME conversion, and those headers would be derived from the Exchange-native format. (Details [here](https://msdn.microsoft.com/en-us/library/cc463915(v=exchg.80).aspx) if you're curious). 

Of course the recipient would get the version that's been stamped along the way, but the original copy wouldn't have all of that. There's no way that it could, given that some values are updated per-hop (like the `Received` header). The best Exchange could do would be to reach back into the sender's mailbox as the message goes out via transport and stamp the headers it sets at that point in time.

**Comment by dorshemer** [comment]
Thanks for clarifying.

**Comment by garrettm** [comment]
@jasonjoh sorry to bother you, but I'm also having this problem.  Is there a recommended workaround, if I want to see headers on messages that I've sent?  Assuming I can't just remember locally -- I also want to see these headers on other devices that are using the same mail account.

**Comment by jasonjoh** [comment]
@garrettm No, internet headers just do not exist on the copy in Sent Items.

**Comment by garrettm** [comment]
@jasonjoh okay, thanks.  I'm planning on using a strategy from another one of your posts to add attributes to mail I send.

https://github.com/microsoftgraph/microsoft-graph-docs/issues/3766#issuecomment-454816463
