### ISSUE TITLE
findMeetingTimes returns no results with an empty reason of Unknown

### ISSUE THREAD

**Issue by carblue5757** [microsoftgraph/microsoft-graph-docs#2720]
findMeetingTimes will often return no `MeetingSuggestions` with the empty reason of `Unknown` when I believe there should be a result. 

My request is simple, findMeetingTimes that are an hour in duration from 9:30am to 11:30am where the organizer is optional and the minimum attendee percentage is set to 0%.  I feel I should always get some results in this scenario, but am finding out that I keep getting nothing because of Unknown. 

**Request**:
``` json
{
  "timeConstraint": {
    "timeslots": [
      {
        "start": {
          "dateTime": "2018-05-24T09:30:00",
          "timeZone": "Eastern Standard Time"
        },
        "end": {
          "dateTime": "2018-05-24T11:30:00",
          "timeZone": "Eastern Standard Time"
        }
      }
    ]
  },
  "meetingDuration": "PT1H",
  "isOrganizerOptional": true,
  "minimumAttendeePercentage": 0
} 
```

**Returns**
``` json
{
  "emptySuggestionsReason": "Unknown",
  "meetingTimeSuggestions": []
}
```
**Notes**: 

I am busy during this time and so is the one attendee I added as part of the request

Another scenario is I am performing a findMeetingTime over a 15 minute Time Slot and a 15 minute duration.   This often fails for me saying the `OrganizerUnavailable` (or `Unknown` if I set `isOrganizerOptional` to true) even though my schedule and my single attendee schedule is open.  When I expand the time slot to 30 minutes and change the duration to 30 minutes, it works as expected.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
