### ISSUE TITLE
Graph API does not return SPO subsites correctly

### ISSUE THREAD

**Issue by y-inocchi** [microsoftgraph/microsoft-graph-docs#2739]
Issue: 

I was working with the Microsoft Graph API and discovered what looks like a bug in the Sites API.

When using the Graph API (https://graph.microsoft.com/v1.0/sites/root/sites) to get the subsite of the root site, an error was returned.
```
{
  "Error": {
    "Code": "itemNotFound",
    "Message": "Resource was not found",
  }
}
```

However, when browsing from the SharePoint Online Web, it appears that there are several subsites.

And, if there are no subsites, the API (https://graph.microsoft.com/v1.0/sites/root/sites) returns an empty array like this:
```
{
  "@Odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites",
  "value":[]
}
```

While investigating these phenomena, I found a certain condition.

When the number of subsites of root is 20 or more, API execution failed and an error was returned. 
And, when 19 or less, the API execution succeeded and the subsite list was returned.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.

**Comment by mpacary** [comment]
Here is [the equivalent question on StackOverflow](https://stackoverflow.com/q/46622889/488666).
