### ISSUE TITLE
preferredLanguage is not allowed when creating or updating a Group object

### ISSUE THREAD

**Issue by sugcat** [microsoftgraph/microsoft-graph-docs#2744]
Issue: The documentation says that we can specify other writable properties when creating a group. However, when passing the `preferredLanguage` property in the body, it gives back an error saying that this property is not settable. **It prevents me from creating a group with a specified language**, which is a major blocker for provisioning groups in multilingual environments.

The group entity properties page doesn't mention that this property is read-only.

Article: [group_post_groups](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group_post_groups.md)

**Comment by Jackson-Woods** [comment]
The `preferredLanguage` property is a user property: see the [User resource](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/user) page. It is not available on groups in Azure AD or Microsoft Graph. The cited documentation is correct to omit this property.

Closing issue.
