### ISSUE TITLE
Can't update SPO metadata choiceColumn allowed multi select

### ISSUE THREAD

**Issue by y-inocchi** [microsoftgraph/microsoft-graph-docs#2745]
I can't update SPO metadata choiceColumn allowed multi select, when execute Graph API ( `PATCH /sites/{site-id}/lists/{list-id}/items/{item-id}/fields` ) .

I set a choice column which allowed multi-select like this:

``` json
{
  "columnGroup": "Custom Columns",
  "description": "",
  "displayName": "sample_multi_select",
  "enforceUniqueValues": false,
  "hidden": false,
  "id": "b4a7f15f-c056-4033-ade9-cdb94976bfb9",
  "indexed": false,
  "name": "sample_multi_select",
  "readOnly": false,
  "required": false,
  "choice": {
      "allowTextEntry": false,
      "choices": [
          "A",
          "B",
          "C",
          "D"
      ],
      "displayAs": "checkBoxes"
  }
}
```

And, I use Graph API ( `PATCH /sites/{site-id}/lists/{list-id}/items/{item-id}/fields` ) to update the choice column, using below parameter body.

``` json
{
  "sample_multi_select": "A"
}
```

However, an error was returned.

``` json
{
    "error": {
        "code": "generalException",
        "message": "An unspecified error has occurred.",
    }
}
```

I have tried to execute API with shown below parameters, but the same error came back in each case.

``` json
{
  "sample_multi_select": "A, B"
}
```

``` json
{
  "sample_multi_select": "[A, B]"
}
```

**Comment by jthake** [comment]
In our documentation, we do not currently have clear instructions on how to handle different field types.

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/listitem_update

I'll get the answer for you and post it here.

**Comment by jthake** [comment]
@VesaJuvonen  do you know the answer here?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
