### ISSUE TITLE
nextLink broken for drive delta

### ISSUE THREAD

**Issue by daviande** [microsoftgraph/microsoft-graph-docs#2749]
I'm trying the following:

https://graph.microsoft.com/v1.0/me/drive/root/delta

This works as expected, I get a response containing changes and a nextLink:

https://graph.microsoft.com/v1.0/me/drive/root/delta?token=aTE09NjM2NjM2Nzc3MDYwNjM7SUQ9RkRENTYxOEVDQzBCOEU3MyExMDE7TFI9NjM2NjM5OTMyMzYxODc7RVA9MTg7U0k9MTQ7TElEPTg1NDYyOTtGRD1UcnVlO0JVPVRydWU7U0c9MTtTTz0yO1BJPTM

I then make a GET request for the nextUrl.  My response contains more items (as expected), but the nextLink is the same as before (it is still:  https://graph.microsoft.com/v1.0/me/drive/root/delta?token=aTE09NjM2NjM2Nzc3MDYwNjM7SUQ9RkRENTYxOEVDQzBCOEU3MyExMDE7TFI9NjM2NjM5OTMyMzYxODc7RVA9MTg7U0k9MTQ7TElEPTg1NDYyOTtGRD1UcnVlO0JVPVRydWU7U0c9MTtTTz0yO1BJPTM).

Therefore, because the link is the same, I am unable to continue paging through the delta results.  

Expected result:  The value for nextLink is different for each 'page' of results.

**Comment by jthake** [comment]
Could you show the exact calls you are making to replicate this, just so I totally understand?

**Comment by daviande** [comment]
Here are the requests/responses I'm seeing:

Request:

GET https://graph.microsoft.com/v1.0/me/drive/root/delta

Response:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/drive/root/delta?token=aTE09NjM2NjQ5MzU2MTExNzc7SUQ9RkRENTYxOEVDQzBCOEU3MyExMDE7TFI9NjM2NjQ5Mzk5MzU0MjM7RVA9MTg7U0k9Mjk7TElEPTg1NDcxODtGRD1UcnVlO0JVPVRydWU7U0c9MTtTTz0yO1BJPTM",
    "value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
....

Request

GET https://graph.microsoft.com/v1.0/me/drive/root/delta?token=aTE09NjM2NjQ5MzU2MTExNzc7SUQ9RkRENTYxOEVDQzBCOEU3MyExMDE7TFI9NjM2NjQ5Mzk5MzU0MjM7RVA9MTg7U0k9Mjk7TElEPTg1NDcxODtGRD1UcnVlO0JVPVRydWU7U0c9MTtTTz0yO1BJPTM

Response:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/drive/root/delta?token=aTE09NjM2NjQ5MzU2MTExNzc7SUQ9RkRENTYxOEVDQzBCOEU3MyExMDE7TFI9NjM2NjQ5NDAwNjM1Njc7RVA9MTg7U0k9Mjk7TElEPTg1NDUxMTtGRD1UcnVlO0JVPVRydWU7U0c9MTtTTz0yO1BJPTM",
    "value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "createdDateTime": "2007-08-10T18:35:43.18Z",
...

NOTE:  That in both requests, the nextLink values are the same.  I would've expected a different nextLink value in the second response.

**Comment by daviande** [comment]
I might've made a mistake when I originally filed the bug, I am seeing different nextLink values now.  Sorry for the noise.
