### ISSUE TITLE
Microsoft graph NotificationUrl scheme='http' is not supported

### ISSUE THREAD

**Issue by ChiranjibKarn** [microsoftgraph/microsoft-graph-docs#2751]
Issue: While trying to create subscriptions (using https://graph.microsoft.com/v1.0/subscriptions" endpoint) from local system with notificationUrl schema "http", it throws following error:

> "code": "InvalidRequest", "message": "NotificationUrl scheme='http' is not supported."

Is not "http" should be allowed for development purpose? 
Also, can I give "localhost" in subscription's "NotificationUrl" ?

[SO](https://stackoverflow.com/questions/50758972/microsoft-graph-notificationurl-scheme-http-is-not-supported)

**Comment by mlafleur** [comment]
That is correct, `http` is not supported. The URL must be secure (`https`). From the [documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/subscription#properties):

>| | ||
>|--|--|---|
>|notificationUrl | string | The URL of the endpoint that will receive the notifications. **This URL has to make use of the HTTPS protocol.**|

**Comment by ChiranjibKarn** [comment]
Any future plan to allow http and localhost for development purpose?
