### ISSUE TITLE
$filter not working on group members operation.

### ISSUE THREAD

**Issue by chmediko** [microsoftgraph/microsoft-graph-docs#2761]
Issue: I am trying to run a msgraph query like this:
https://graph.microsoft.com/v1.0/groups/0ffa0e7a-4554-476a-a971-507db84b525b/members?$filter=isof('microsoft.graph.user')

The error I see is:
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Cast or IsOf Function must have a type in its arguments.",
        "innerError": {
            "request-id": "7f4a7294-26d0-4e92-bd58-762a53b4211f",
            "date": "2018-06-14T15:06:21"
        }
    }
}

Any idea what is the issue here?

Article:

**Comment by jthake** [comment]
What are you trying to do here with the filter? he way to get the members of a group is as follows https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_list_members

**Comment by dkershaw10** [comment]
@chmediko Unfortunately this operation is not currently supported.  You'll filter on the member types on the client side.  The AAD team is working on some improved query support for filtering across relationships (starting with group members), but I don't have an ETA.
