### ISSUE TITLE
Word/Excel AutoSave Events in CoAuthoring

### ISSUE THREAD

**Issue by subbiahkk** [microsoftgraph/microsoft-graph-docs#2777]
Hi,
I am Implementing Excel/Word CoAuthoring using Office 365. Everything works as expected. We have Addins on top of the excel/Word and Override the Autosave events. We are calling our own API on top of the Excel/Word Sync with onedrive. The issue here is Autosave triggers frequently and calling our API on every autosave event. Is there way to differentiate AutoSave and User manual Save inside Workbook_BeforeSave Event?

Thanks,
Subbiah K

**Comment by jthake** [comment]
The webhook currently doesn't differentiate between the type of save it is in OneDrive. 

We use UserVoice to track feature requests 
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis

I would appreciate it if you could add this as a requested feature and we can encourage others to vote it up to help prioritize this.
