### ISSUE TITLE
Inconsistent responses from api endpoint v1.0 for expanding Sharepoint list 

### ISSUE THREAD

**Issue by mahpour** [microsoftgraph/microsoft-graph-docs#2779]
Issue: 

Some of the lookup fields disappear from responses from time to time. we have not changed our code but network traffic shows those lookup fields are not being returned at all. 

here's my code:
```typescript
const obs = new Subject<GraphResponseModel>();
    this.msAuthService.getGraphClient().subscribe(client => client.api(`sites/${environment.sharepointSiteId}/lists/Program List/items`)
      .filter(searchText && searchText.length ? `startswith(fields/Title,'${searchText}')` : '')
      .select('fields')
      .expand('fields')
      .get(((error1, response) => {
        obs.next({error: error1, data: response});
      })));
    return obs.asObservable();
```

here's my generated query via Graph JS API:

`https://graph.microsoft.com/v1.0/sites/websparksolutions.sharepoint.com,0a55ef5d-e0c7-481c-9d81-0d4065747418,8c1d538f-737c-49ca-b95a-ae221fa0b9a9/lists/Program%20List/items?$filter=&$select=fields&$expand=fields`

This was working for months. In last few days those lookup fields come and go at times. We can't rely on an inconsistent response for our production code. 

Are you deploying anything on production?

**Comment by JeremyKelley** [comment]
@mahpour Are the fields that are missing always lookup fields or are you seeing this with other field types as well?

**Comment by mahpour** [comment]
@JeremyKelley, It was lookup fields only. the issue has not happened since when I reported it but that's really concerning if we rely on graph to sometimes not work as expected. specially that we are not using the beta api channel. 

We also noticed some inconsistencies when different users are accessing the API sometimes it reports as unauthorized call for same user (non domain user/ guest user) but the next day it works. we made sure that cookies and cached are cleared and token is renewed.

**Comment by mahpour** [comment]
@JeremyKelley It's happening again, we are not getting lookup values in the responses. It's so disappointing to see your API's are not stable and production ready. We will pull out the plugs on your Graph API. 😠

**Comment by mahpour** [comment]
![screenshot](https://user-images.githubusercontent.com/202065/42645648-91a00082-85cc-11e8-9417-1e85d4227efb.png)

**Comment by mahpour** [comment]
It’s working now. I will check the response headers when I’m back at the office tomorrow. Thank you!

**Comment by ificator** [comment]
I managed to find some relevant logs, and it looks like we had an issue specifically with multi-value lookup fields. Can you confirm this aligns with your scenario? If so I'll make sure it's correctly handled before we make any further attempts to enable the problematic feature.

Rest assured we will not regress this behavior again.

**Comment by mahpour** [comment]
It's broken again! now the lookups don't work for single lookups! this is so frustrating!

**Comment by ificator** [comment]
Hmm, we haven't made any changes that would have touched this area - we're deliberately being very careful now! Let me quick see if I can spot anything unexpected.

**Comment by mahpour** [comment]
It's back up again

**Comment by ificator** [comment]
Everything checks out - in the response you should have a `request-id` header and a `date` header... could you provide those for one of the requests that's not doing what you expect? I'll drill in and see what's going on.

**Comment by mahpour** [comment]
I'll send you the request-id next time I can catch it. Thanks for quick response!

**Comment by ificator** [comment]
Thanks! The fact that it was a transient issue is a little strange - hopefully that means it was a one off and you won't see it again. But if you do definitely let me know ASAP and we'll figure out what's going on.

**Comment by mahpour** [comment]
Thanks so much for the quick escalation!

**Comment by ificator** [comment]
Closing stale issues.
