### ISSUE TITLE
Graph Subscription - IP Range

### ISSUE THREAD

**Issue by fredericklin** [microsoftgraph/microsoft-graph-docs#2787]
Issue:

I'm looking at further securing an Azure Function that is consuming a Graph subscription.  I do not want the function to be called by anything but a Microsoft Graph subscription, which includes:

1. Sending a validation request to the Azure Function
2. Sending a payload request to the Azure Function

Would it be possible to include the IP ranges for Microsoft Graph subscriptions so that they can be included in the IP whitelist for an Azure Function?

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/subscription_post_subscriptions

**Comment by jthake** [comment]
@mattchenderson any advice you can give here?

**Comment by jthake** [comment]
@richdizz  have you done anything here on this space? Seems like a great place to have some guidance...

**Comment by fredericklin** [comment]
@jthake @richdizz Much appreciated!  I'm thinking could also renew function keys everytime a graph subscription is renewed?

**Comment by mattchenderson** [comment]
@jthake-msft We can handle IP restrictions on the Functions side, but I assume the Graph has non-static outbound IPs, right? I think this is more a question for the Graph folks.

@fredericklin That's an interesting idea. Is there a specific scenario that you have around rotating that frequently?. Also, Would you mind filing a separate issue against the https://github.com/Azure/azure-functions-host repo around key rotation? This would likely just need to be an action the subscription refresh function takes.

**Comment by piotrci** [comment]
@fredericklin The infrastructure sending webhook notifications is hosted in Azure Data Centers. We do not have a fixed list of IPs associated with that infrastructure - they are subject to fluctuate as we re-deploy the service.
The best approach we can recommend is as follows:

1. Filter traffic based on official IP ranges for Azure Data Centers
2. Update those ranges weekly, as recommended here: https://www.microsoft.com/en-us/download/details.aspx?id=41653

Note that this will allow traffic from anybody hosting on Azure, which is not perfect, but the closest you can currently get to the solution without risking filtering out legitimate traffic from our service.
