### ISSUE TITLE
Missing permission in drive GET request produces no error

### ISSUE THREAD

**Issue by sergeantbaker** [microsoftgraph/microsoft-graph-docs#2790]
Please forgive me if this is placed in the wrong place or is missing important details. This is my first ever bug report on Github.

I think I found a bug in the Graph API concerning permissions and error responses. Usually, when my OAuth2 token does not have the required permissions, the response body will mention this in its JSON content. However, all day today I have been blaming my own code for not working and breaking my head over it. 

I just found the problem. When performing the GET request: `me/drive/root/children` without the necessary OAuth scope the Graph API sends an empty list as the response rather than telling me I lack permissions. This is an annoying bug because most people will think that means their Drive is empty while it isn't. I think a standard authorization error should be returned.

Raymon Been

**Comment by jthake** [comment]
@dkershaw10 any chanceyou could help here? that seems odd that the permissions are not working like they should....

@sergeantbaker  could you provide the reponses and requests you are doing. And scrub out any tokens?

**Comment by sergeantbaker** [comment]
Sorry, but I am no longer able to reproduce the error. This due to the required permissions now being part of my account. I have attached a screenshot of a correct response.

This is what you get when you use a valid token with the proper permissions:
![driveitems_normal](https://user-images.githubusercontent.com/7905472/41708542-24351cc6-7541-11e8-8a9a-7a8cb2860417.png)

When using a token without Files.Read permissions you will get a response like 
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('********-****-****-****-************')/drive/root/children",
    "value": []
}

This is incorrect. Returning an empty list would mean the root drive folder is empty. This is not the case. I just lack the permissions to view it. I believe the proper response would be something like:
![requestdenied](https://user-images.githubusercontent.com/7905472/41711112-9fe4c4d8-7547-11e8-885f-19f687dbc584.PNG)

If you have any questions, please mail raymonbeen98@gmail.com

Raymon Been

**Comment by jthake** [comment]
@dkershaw10 can you help here?

**Comment by gwmpey** [comment]
I am also having this issue and it has been very frustrating. Additionally, it would be very helpful if the response would include what the missing permission was.
