### ISSUE TITLE
Issue in  "orderby" query parameter 

### ISSUE THREAD

**Issue by jeevanjaiswalsimpplr** [microsoftgraph/microsoft-graph-docs#2801]
Hi,
For API: `https://graph.microsoft.com/v1.0/drives/{driveId}/root?$expand=children,permissions,versions&$orderby=createdDateTime desc` the "$orderby" query parameter is not providing expected sorted result. It returns same order of result irrespective of the order by parameter.
Please let me know if you need any other information on this.

Thanks,
Jeevan

**Comment by jthake** [comment]
Just to eliminate a few things, are you able to get this to work in Graph Explorer? 

https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters#orderby-parameter

**Comment by jeevanjaiswalsimpplr** [comment]
Yes It is working for  API on graph API explorer:
https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/messages?$orderby=from/emailAddress/name
,subject

Regards,
Jeevan

**Comment by jeevanjaiswalsimpplr** [comment]
Yes It is working for  API on graph API explorer:
https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/
messages?$orderby=from/emailAddress/name ,subject

Regards,
Jeevan

**Comment by jthake** [comment]
how are you calling this graph api in your application? can you confirm that the full url string is being called in whatever http call stack you are using?

**Comment by jeevanjaiswalsimpplr** [comment]
GET:
https://graph.microsoft.com/v1.0/drives/b!zjYXQOp_KkSFvp3rwm-Pbz-g6njL7dpDhrZCR-wtv0_Zbcln8bPBTadBJCjssPc_/root?$expand=children,permissions,versions&$orderby=lastModifiedDateTime
desc

**Comment by jthake** [comment]
Does this work for you?

https://graph.microsoft.com/v1.0/me/drive/root?$expand=children,permissions,versions&$orderby=lastModifiedDateTime desc

Just to elimate the /drives/{drive-id} being the issue here

**Comment by jeevanjaiswalsimpplr** [comment]
No, even the endpoint shared by you in above email is not sorting the
results.

**Comment by jthake-msft** [comment]
Somehow in whatever http stack you're using on your platform its stripping the query string it seems. If its working in Graph Explorer and not in your code, that would be my assumption.

**Comment by jeevanjaiswalsimpplr** [comment]
It is not working, neither in graph explorer nor in the code.

I just  want to sort the result returned by below API:
https://graph.microsoft.com/v1.0/drives/{driveId}/root?$expand=children,permissions,versions

and hence I appended &$orderby=createdDateTime desc at the end of it as mentioned in the documentation, but even after appending it returns the same order of results irrespective of the if orderby is asc or desc. It is not working in code and graph explorer as well.
Please let me know if my API request is not framed correctly and if not please let me know how can I sort the result(i.e children list) returned by the AP:
https://graph.microsoft.com/v1.0/drives/{driveId}/root?$expand=children,permissions,versions

**Comment by jthake-msft** [comment]
@JeremyKelley  @daspek any ideas here on why its not sorting?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
