### ISSUE TITLE
Change Log difficult to use - reorg suggested

### ISSUE THREAD

**Issue by DeanGross** [microsoftgraph/microsoft-graph-docs#2806]
Issue: 
The headings are not properly sorted this causes items in the right side navigation to be out of order. The Page is very long which makes scrolling and finding content difficult. 
Breaking this page into multiple pages, maybe one for each year, would make it much easier to navigate.

Article:

**Comment by Lauragra** [comment]
Hi @DeanGross , thanks for your feedback. I just submitted a PR to fix the issue that caused the In this article section to appear to be out of date order. That update will appear on the live site by tomorrow. We'll consider the feedback to improve the navigation for the Changelog in general.
