### ISSUE TITLE
msgraph findmeetingtimes does not provide enough locations

### ISSUE THREAD

**Issue by jnlkds** [microsoftgraph/microsoft-graph-docs#2810]
Issue: 

Article:

**Comment by jnlkds** [comment]
Sending in no locations so that the system should recommend locations that are currently available ONLY yield a few locations,  How do you increase the number of suggestions?
{
  "attendees": [
   ],
  "timeConstraint": {
    "timeslots": [
      {
        "start": {
          "dateTime": "2018-06-21T00:00:07.097Z",
          "timeZone": "Pacific Standard Time"
        },
        "end": {
          "dateTime": "2018-06-21T20:39:07.097Z",
          "timeZone": "Pacific Standard Time"
        }
      }
    ]
  },
  "locationConstraint": {
    "isRequired": "true",
    "suggestLocation": "true",
    "locations": [
    ]
  },
  "meetingDuration": "PT30M",
    "returnSuggestionReasons": "true",
  "maxCandidates": "4",
    "minimumAttendeePercentage": "100"
}

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.

**Comment by theakc** [comment]
@jnlkds this is by design as of now. findmeetingtimes can only recommend location that an user has used in past.

**Comment by jnlkds** [comment]
Thanks... but that's not a good answer. 
If someone is trying to find room availability, they should be able to select some type of filter on the response [All, FrequentyUsed,WhatsAvailable], etc...

**Comment by theakc** [comment]
It is current limitation of the api. I will bring it up with internal team to consider it. Thanks for the feedback @jnlkds
