### ISSUE TITLE
Get Organization documentation state wrong response

### ISSUE THREAD

**Issue by Nness** [microsoftgraph/microsoft-graph-docs#2811]
Issue: 
[Get Organization](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/organization_get.md) returns array instead of object.

Correct format should be following (This is confirmed through Graph Explorer on either v1.0 or beta):

`https://graph.microsoft.com/v1.0/organization`
```
{
	"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#organization",
	"value": [{
		"assignedPlans": [{
			"assignedDateTime": "datetime-value",
			"capabilityStatus": "capabilityStatus-value",
			"service": "service-value",
			"servicePlanId": "servicePlanId-value"
		}],
		"businessPhones": ["businessPhones-value"],
		"city": "city-value",
		"country": "country-value",
		"countryLetterCode": "countryLetterCode-value",
		"displayName": "displayName-value"
	}]
}
```

**Comment by jthake** [comment]
@angelgolfer-ms is this something you own? can you verify and update this?

**Comment by FaithOmbongi** [comment]
Thank you @Nness for raising this issue.
As Jackson has pointed out, there's only one organization that the user or app is authenticated into at a time, and therefore only 1 will be returned, even for the [organization-list](https://docs.microsoft.com/en-us/graph/api/organization-list?view=graph-rest-1.0&tabs=http) operation. Raising a PR to update the [organization-get](https://docs.microsoft.com/en-us/graph/api/organization-get?view=graph-rest-1.0&tabs=http) page.

Closing the issue.
