### ISSUE TITLE
Graph API doesn't return the content of an item in an O365 group drive

### ISSUE THREAD

**Issue by espressobeanies** [microsoftgraph/microsoft-graph-docs#2815]
Issue: Microsoft Graph API v1.0 doesn't return the binary content of an item in an O365 group drive when specifying the correct item-id in the following Graph path:

> /groups/{group-id}/drive/items/{item-id}/content

Documentation is also conflicting with '/files' parameter from Graph API Beta
https://dev.office.com/blogs/GroupsRESTAPI

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_get_content

**Comment by jthake** [comment]
@daspek  was is the correct way to get the content of a item in a groups onedrive?

**Comment by JeremyKelley** [comment]
@espressobeanies Getting the content of a file should be the same regardless of what Drive it's in, whether it's a group or other.  The doc you linked to in the API Reference is the most up to date on how to get content.

One thing I did notice is that the call to get content does not work when using Graph Explorer.  If you put it inside an actual application however it should work.  In my case I did a test against a word doc and properly got back a file with the type "application/vnd.openxmlformats-officedocument.wordprocessingml.document" in the media type from the headers.

Do you have a specific file type you're trying to get that isn't working?

**Comment by espressobeanies** [comment]
@JeremyKelley Yes, I'm working with .docx files and I'm only able to get back 323 bytes of the actual file. I tried setting the 'content-type' to what you have, however it didn't seem to make much difference in my output.

**Comment by espressobeanies** [comment]
Is anyone monitoring responses to these threads?

**Comment by espressobeanies** [comment]
Thanks @jthake-msft 

Daspek, I'm seeing this for all the files I tried in a directory. So, I actually get the following message when I open the file in Notepad: 

> <?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2147024891, System.UnauthorizedAccessException</m:code><m:message xml:lang="en-US">Access denied. You do not have permission to perform this action or access this resource.</m:message></m:error>

Sure, please reach out to me. Thanks.

**Comment by jthake-msft** [comment]
@espressobeanies did this resolve your issue? if so could you close the issue below?

**Comment by espressobeanies** [comment]
@jthake-msft it didn't. I tried both URL methods and they kicked back the same "Access Denied" message that I posted above

**Comment by daspek** [comment]
@espressobeanies thanks for the clarification. The 323-byte response you're getting is the error message, not a corrupt partial file. So that's good. The URL you're using points to a direct SharePoint REST API and is not part of Microsoft Graph. If you're using an auth token for Microsoft Graph, then that token won't work with this API, and that could be the source of your problem.

Could you try using the Graph API you linked to above (https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_get_content) instead?

**Comment by espressobeanies** [comment]
Daspek, if I use the Microsoft Graph link from above, I get a file size with zero bytes and no error messages from my REST output.

**Comment by daspek** [comment]
@espressobeanies, when you request `/content`, the server should return a 302 redirect to a download URL. if you follow the download URL, you should be able to get the content. also, in the metadata response you get back without `/content`, you should see a property called `@microsoft.graph.downloadUrl`. you can do a GET on that URL to download the file, as well. this is essentially what the `/content` endpoint redirects to.

**Comment by espressobeanies** [comment]
Daspek, thanks for the clarification. I'll have to test this behavior on Postman because my REST script is not providing any output after it runs, especially involving a 302 redirect.

**Comment by espressobeanies** [comment]
Yep, confirmed my program wasn't able to accommodate 302 requests and that it was failing to follow the redirect. Thanks all.
