### ISSUE TITLE
'lastModifiedDateTime' property is broken for sharepoint lists

### ISSUE THREAD

**Issue by romanSlivinskyi** [microsoftgraph/microsoft-graph-docs#2819]
I created an Item in List, when I use 
`GET /sites/{site-id}/lists/{list-id}`

I get this for **/beta**:
```
{
    ....
    "lastModifiedDateTime": "2018-06-27T07:07:10Z",
   ....
}
```
and this for **/v1.0**:
```
{
    ....
    "lastModifiedDateTime": "2018-06-26T14:16:40Z"
   ....
}
```
However, when I add _select_ parameter to: 
`GET /sites/{site-id}/lists/{list-id}?select=lastModifiedDateTime`

I get the same response for both **/beta** and **/v1.0**
```
{
    ...
   "lastModifiedDateTime": "2018-06-27T07:12:04Z"
}

```
None of the above is correct.

**Comment by jthake** [comment]
@JeremyKelley  can this be investigated please?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
