### ISSUE TITLE
Excel API available on consumer drive?

### ISSUE THREAD

**Issue by Tekki** [microsoftgraph/microsoft-graph-docs#2826]
Is my impression correct that the Excel API is now working with personal accounts? If yes, we need some changes to the docs.
See #1663 as an example.

**Comment by jthake-msft** [comment]
@sumurthy are we ready to merge that in yet?

**Comment by sumurthy** [comment]
The Excel API on personal accounts are not supported. It has few technical issues that we are working through and is not suitable for public usage. There is no timeline available on when we can take it to GA.

**Comment by Tekki** [comment]
By the way, for my requirements (reading from and writing to spreadsheets) the API works: https://github.com/Tekki/ivoc4
