### ISSUE TITLE
MS Graph some user's properties are empty

### ISSUE THREAD

**Issue by aslanovsergey** [microsoftgraph/microsoft-graph-docs#2833]
Issue: 
When I fetch data through ms graph (v1.0 and beta) I don't get values of many basic properties like next

```
{
    "businessPhones": [],
    "jobTitle": null,
    "mobilePhone": null,
}
```
although I see them when I get this user though Get-AzureADUser and some of the properties have slightly different names

```
JobTitle: CEO

Mobile: 0000000000

TelephoneNumber: 0000000000
```
Should I configure some mapping somewhere?

**Comment by aslanovsergey** [comment]
The answer was to give User.Read.All permissions. But is it possible to reveal some more properties on top of User.ReadBasic.All?

**Comment by jthake-msft** [comment]
Apologies for delay in responding here.

Are you using the 

```
GET https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}?$select=displayName,givenName,postalCode
```

You can specifically select which properties you would like. These are documented [here ](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get)

**Comment by jthake-msft** [comment]
@aslanovsergey  did this help?

**Comment by aslanovsergey** [comment]
Sorry for delay @jthake-msft, select would help as a makeshift. I wanted data to be protected and having User.ReadBasic.All to get some of the properties which available only with User.Read.All.
