### ISSUE TITLE
File API: Impossible to get thumbnail of a document uploaded without a user (app token)

### ISSUE THREAD

**Issue by climam** [microsoftgraph/microsoft-graph-docs#2841]
**Issue:** 

When calling the File API to get the thumbnail of a document uploaded without a user (app token), the request fails after 20secs with following error:

`{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "ad155c56-7218-4417-8238-50b4290d1129",
            "date": "2018-07-04T14:09:56"
        }
    }
}`

**Reproduction scenario:**

1. Get an app token (https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service)
2. Call the get thumbnail of File API:
`https://graph.microsoft.com/v1.0/drives/b!g2EYmMNDtkGr-rziwiXaOJ_uGjgL5CNMgOc3lFsYevw2sawr-j4sQbLR60aYMSSv/items/01ZZJQAVWAQT2NVRWHU5FZCKRQBYVVIANZ/thumbnails
`

**Actual result:**

`{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "4a322975-21c3-4c02-a6db-21d27e459e40",
            "date": "2018-07-04T14:14:12"
        }
    }
}`

**Comment by jthake-msft** [comment]
Are you requesting the correct permissions for the app-only token before making this call?

In the documentation it lists what you require
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_list_thumbnails

**Comment by climam** [comment]
Yes, we have actually Files.ReadWrite.All

**Comment by jthake-msft** [comment]
@JeremyKelley any idea why it would be returning and UnknownError here?

**Comment by climam** [comment]
Do you have any news regarding this issue ?

**Comment by JeremyKelley** [comment]
Hi @climam, does asking for other metadata come back successful?  Is it just the thumbnails in particular that are failing?

**Comment by climam** [comment]
Hi @JeremyKelley, yes only the thumbnails.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
