### ISSUE TITLE
Filtering by date not working in bookings appointments

### ISSUE THREAD

**Issue by Chotimir** [microsoftgraph/microsoft-graph-docs#2846]
I tried to get appointments filtering by date but I get 400 error code (message: "This filter query is not supported."). There are urls:
`https://graph.microsoft.com/beta/bookingBusinesses/<id>/appointments?$filter=start/dateTime eq '2018-06-07T06:50:02.0000000Z'`
`https://graph.microsoft.com/beta/bookingBusinesses/<id>/appointments?$filter=start/dateTime gt datetime'2018-06-07T06:50:02.0000000Z'`
`https://graph.microsoft.com/beta/bookingBusinesses/<id>/appointments?$filter=start/dateTime gt '2018-06-07T06:50:02.0000000Z'`

Also filtering by null is impossible, for example:
`https://graph.microsoft.com/beta/bookingBusinesses/<id>/appointments?$filter=customerPhone eq null`
returns 500 error code with message "An error has occurred.".

**Comment by jthake-msft** [comment]
@fpintos  could you share any insight here?
There doesn't seem to be a known limitation here for this https://developer.microsoft.com/en-us/graph/docs/concepts/known_issues#bookings

**Comment by fpintos** [comment]
Filtering by dates should be done by using [calendarView](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/bookingbusiness_list_calendarview).

We'll investigate what is going on with the null case.

**Comment by fpintos** [comment]
Hi @Chotimir , the fix to filter by 'eq null' and 'ne null' has been deployed.
