### ISSUE TITLE
Excel documents do not return a thumbail

### ISSUE THREAD

**Issue by RobinBreman** [microsoftgraph/microsoft-graph-docs#2849]
Issue: 

Requesting thumbnails for Excel documents returns an empy collection. 
There is no mention in the docs about unsupported files. 

Item: https://graph.microsoft.com/beta/drives/x/items/y

```json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('b%217xokGhE9GUWd7zRtpF9I6mbje5IN609CiULDS4b4TRatsdAyhmnNSbAhrRCzxFXS')/items/$entity",
     "name": "ExcelFile.xlsx",
    "webUrl": "https://.....sharepoint.com/sites/.../_layouts/15/Doc.aspx?sourcedoc=...&file=ExcelFile.xlsx&action=default&mobileredirect=true",
}
```

Thumbnail: https://graph.microsoft.com/beta/drives/x/items/y/thumbnails

```json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#drives('b%217xokGhE9GUWd7zRtpF9I6mbje5IN609CiULDS4b4TRatsdAyhmnNSbAhrRCzxFXS')/items('016BZQA5EKJBFJ53KKEZBLPTTEFTTFWXTW')/thumbnails",
    "value": []
}
``` 

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/driveitem_list_thumbnails

**Comment by jthake-msft** [comment]
Is there any reason you are using the beta endpoint and not v1.0 ? 
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_list_thumbnails

**Comment by justdevelopment** [comment]
This issue also occurs in V1.0 and we just noticed it also happens on the regular SharePoint activity feed (I'm unsure if this runs on Graph. I don't see any calls to the thumbnail endpoint so perhaps it's not Graph specific?):

![image](https://user-images.githubusercontent.com/23448165/42565109-d4d6586c-8502-11e8-9f59-bc81ab7135b9.png)

It seems to be related to the content of the Excel file. When there is an image in the file, that is show in the preview window. When there is just filled out cells, no preview is shown.

This happens on several tenants.

**Comment by jthake-msft** [comment]
@JeremyKelley can you give any advice on this one?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
