### ISSUE TITLE
assignLicense Graph API returns 400

### ISSUE THREAD

**Issue by Sparsh12345** [microsoftgraph/microsoft-graph-docs#2853]
I am trying to add user licence while creating new user using Microsoft Office 365 Graph API but i have tried so many times it returns 400 (Bad Request).

My Url : https://graph.microsoft.com/v1.0/users/{username}/assignLicense

Post Json

{"addLicenses":[{"disabledPlans":[],"skuId":"u86tgb54-b296-42f0-b197-1e91e994b900"}],"removeLicenses":[]}

Please suggest what the issue here.

**Comment by jthake-msft** [comment]
what is that SkuID you are using there?

The documentation has one sample, have you tried that?
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_assignlicense

**Comment by rpkarthi** [comment]
i am using the below article to assign the license for user

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_assignlicense
and getting the error
Cannot convert a primitive value to the expected type 'Edm.Guid'. See the inner exception for more details
any idea?
