### ISSUE TITLE
 Incorrect permissions required for creating openExtension on User resource

### ISSUE THREAD

**Issue by limefrogyank** [microsoftgraph/microsoft-graph-docs#2862]
Issue:  Incorrect permissions required for creating openExtension on User resource

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/opentypeextension_post_opentypeextension.md

The article states that to create an openExtension on the user resource, you need `Directory.AccessAsUser.All`.  However, using the Graph Explorer and verifying that none of the Directory-based permissions were checked, I can create the openExtension without them.  You can use the 2nd sample request under Extensions and see it happen.  I tried this in my dev tenancy and in an organization's (not administer by me) account.

I would love it if this is actually not a bug and that the docs are just wrong because getting administrator ok for this permission would make the route I'm taking impossible.

**Comment by limefrogyank** [comment]
Since getting a positive result in Graph Explorer, I tried it in my own app on my Office dev tenancy.  It did not work at all without `Directory.AccessAsUser.All` permission described in the docs.  

I think the confusing part is that this permission cannot be requested by the app, but only be enabled by the administrators.  It seems that whether or not you check them off in the Graph Explorer, those permissions are administrator-enabled automatically.

**Comment by limefrogyank** [comment]
So I guess this is not an error in the docs.  The way Graph Explorer gives you a toggle to turn those permissions on/off seems to be meaningless and confusing.  So maybe direct this to the Graph Explorer people...

**Comment by jthake-msft** [comment]
@MIchaelMainer  any help here too?

**Comment by limefrogyank** [comment]
`"scp": "Calendars.Read Calendars.ReadWrite Contacts.ReadWrite Files.Read.All Files.ReadWrite Files.ReadWrite.All Mail.ReadWrite Notes.ReadWrite.All openid People.Read profile Sites.ReadWrite.All Tasks.ReadWrite User.ReadBasic.All User.ReadWrite email"`

**Comment by limefrogyank** [comment]
And when using Postman and stealing the token from Graph Explorer, I can view and edit the extensions.  As you can see, the specific `Directory.AccessAsUser.All` permission is not there.  Is it the case that this permission is the same as another User access permission?  If so, this is entirely not clear from the docs...

**Comment by tfrancois** [comment]
I ran into the same issues and it is NOT clear why this is not working even if the Owner (application ID) is set and the application has delegated rights with `Directory.AccessAsUser.All` in addition to ReadWrite privileges at the User level.  Perplexing and nothing short of extremely frustrating.  Is anyone at Microsoft listening?
