### ISSUE TITLE
Download a file in another format - Convert docx to pdf

### ISSUE THREAD

**Issue by dzardoya** [microsoftgraph/microsoft-graph-docs#2869]
Issue: 
I'm trying to get a Word document (.docx) from the Document library in a SharePoint 365 site as a Pdf using the contents format described in the article below but always getting the following result:
Failure - Status Code 0
{
    "isTrusted": true
}

This is the URL I'm using from graph explorer:
https://graph.microsoft.com/v1.0/sites/{site-id}/drive/items/{document-id}/content?format=pdf

I have checked that the user has all permissions for managing sites and files, in fact, I'm executing many other actions like creating new lists, document libraries, check-in/out documents, move documents and so on without problems.

Can you check that, please?

Article:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content_format

**Comment by Zombaya** [comment]
Simply requesting the original file also does not work.

## Example
### File info
[https://graph.microsoft.com/v1.0/me/drive/items/01BYE5RZ4FL7NVUU4UDVHIRG32OLTW4IKM](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me/drive/items/01BYE5RZ4FL7NVUU4UDVHIRG32OLTW4IKM&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)
```json

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('48d31887-5fad-4d73-a9f5-3c356e68a038')/drive/items/$entity",
    "@microsoft.graph.downloadUrl": "https://m365x214355-my.sharepoint.com/personal/meganb_m365x214355_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=5adb5f85-9453-4e1d-889b-7a72e76e214c&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbTM2NXgyMTQzNTUtbXkuc2hhcmVwb2ludC5jb21AZGNkMjE5ZGQtYmM2OC00YjliLWJmMGItNGEzM2E3OTZiZTM1IiwiaXNzIjoiMDAwMDAwMDMtMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwIiwibmJmIjoiMTUzMTgzMjA0MSIsImV4cCI6IjE1MzE4MzU2NDEiLCJlbmRwb2ludHVybCI6InJXOGFHck92ckUzbGc2bUZEeHVQQUNFeFJUZ1g2NGdpYkwyNmlWMGl6eDg9IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNjkiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImNpZCI6Ik9UQmlNRE00TldVdE1qSTFZaTAwT0dZekxXRTRPRGd0TTJJeVlqVTVOamMzTmpjNCIsInZlciI6Imhhc2hlZHByb29mdG9rZW4iLCJzaXRlaWQiOiJaRGd5TXpFeVpqa3RZakl6WWkwMFkySmpMVGsxWkRVdE0yVXdaRGswWlRZNFl6RmwiLCJhcHBfZGlzcGxheW5hbWUiOiJhcGlzYW5kYm94cHJveHkiLCJhcHBpZCI6IjAwOTFlNTllLTE3ZTgtNDdmMC1hNDUwLTQ0M2Q0ZGQzYTAwNiIsInRpZCI6ImRjZDIxOWRkLWJjNjgtNGI5Yi1iZjBiLTRhMzNhNzk2YmUzNSIsInVwbiI6Im1lZ2FuYkBtMzY1eDIxNDM1NS5vbm1pY3Jvc29mdC5jb20iLCJwdWlkIjoiMTAwM0JGRkRBMzgxMzFBRiIsInNjcCI6ImFsbHNpdGVzLnJlYWQgbXlmaWxlcy5yZWFkIGdyb3VwLnJlYWQgbXlmaWxlcy5yZWFkIGFsbHNpdGVzLnJlYWQgYWxsc2l0ZXMucmVhZCBteWZpbGVzLnJlYWQgYWxscHJvZmlsZXMucmVhZCBhbGxwcm9maWxlcy5yZWFkIiwidHQiOiIyIiwidXNlUGVyc2lzdGVudENvb2tpZSI6bnVsbH0.NHhSbVloMWtld0EwVkl2SzBZNFZ2T2FRL2VJdGFMVjRKR3ZPRVRURlBGcz0&ApiVersion=2.0",
    "createdDateTime": "2017-08-07T16:01:51Z",
    "eTag": "\"{5ADB5F85-9453-4E1D-889B-7A72E76E214C},4\"",
    "id": "01BYE5RZ4FL7NVUU4UDVHIRG32OLTW4IKM",
    "lastModifiedDateTime": "2017-08-07T16:01:51Z",
    "name": "Annual Financial Report (DRAFT).docx",
    "webUrl": "https://m365x214355-my.sharepoint.com/personal/meganb_m365x214355_onmicrosoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B5ADB5F85-9453-4E1D-889B-7A72E76E214C%7D&file=Annual%20Financial%20Report%20(DRAFT).docx&action=default&mobileredirect=true",
    "cTag": "\"c:{5ADB5F85-9453-4E1D-889B-7A72E76E214C},1\"",
    "size": 22750,
    "createdBy": {
        "user": {
            "email": "MeganB@M365x214355.onmicrosoft.com",
            "id": "48d31887-5fad-4d73-a9f5-3c356e68a038",
            "displayName": "Megan Bowen"
        }
    },
    "lastModifiedBy": {
        "user": {
            "email": "MeganB@M365x214355.onmicrosoft.com",
            "id": "48d31887-5fad-4d73-a9f5-3c356e68a038",
            "displayName": "Megan Bowen"
        }
    },
    "parentReference": {
        "driveId": "b!-RIj2DuyvEyV1T4NlOaMHk8XkS_I8MdFlUCq1BlcjgmhRfAj3-Z8RY2VpuvV_tpd",
        "driveType": "business",
        "id": "01BYE5RZ56Y2GOVW7725BZO354PWSELRRZ",
        "path": "/drive/root:"
    },
    "file": {
        "mimeType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "hashes": {
            "quickXorHash": "YY1FIiSDCS9hcAptSPs7prNdf5A="
        }
    },
    "fileSystemInfo": {
        "createdDateTime": "2017-08-07T16:01:51Z",
        "lastModifiedDateTime": "2017-08-07T16:01:51Z"
    },
    "shared": {
        "scope": "users"
    }
}
```
### File contents
[https://graph.microsoft.com/v1.0/me/drive/items/01BYE5RZ4FL7NVUU4UDVHIRG32OLTW4IKM/content](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me/drive/items/01BYE5RZ4FL7NVUU4UDVHIRG32OLTW4IKM/content&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)
```json
{
    "isTrusted": true
}
```
### File contents converted to pdf
[https://graph.microsoft.com/v1.0/me/drive/items/01BYE5RZ4FL7NVUU4UDVHIRG32OLTW4IKM/content?format=pdf](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me/drive/items/01BYE5RZ4FL7NVUU4UDVHIRG32OLTW4IKM/content?format=pdf&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)
```json
{
    "isTrusted": true
}
```

**Comment by JeremyKelley** [comment]
Graph Explorer doesn't really let you download the content from a file as far as I know.  If you use the Graph URLs from within your own app you should see the results work.

If it doesn't work from outside Graph Explorer please let me know.

Thanks!

**Comment by dzardoya** [comment]
Hi Jeremy,

You are completely right, it works from C#!

Thanks
