### ISSUE TITLE
Create List with custom template

### ISSUE THREAD

**Issue by dzardoya** [microsoftgraph/microsoft-graph-docs#2872]
I'm using MS Graph for managing SharePoint online sites dynamically.

I'm able to create new lists and document libraries using the default templates, i.e.:

POST https://graph.microsoft.com/v1.0/sites/{myTenant}:/sites/{mySiteCollection}/{mySite}:/lists

BODY

```
{
  "displayName": "LibraryName",
  "list": {
    "template": "documentLibrary"
  }
}
```

The problem is that we have defined a library template with several columns (all are "single line of text" type) and some advanced configuration, like disabling folder creation, so we want to use that custom template for generating new document libraries using MS Graph.

When we perform the same POST changing the "template" value to our custom template we get the following error:

```
{
    "error": {
        "code": "invalidRequest",
        "message": "One of the provided arguments is not acceptable.",
        "innerError": {
            "request-id": "a3794cbf-3e3f-45ad-8f9b-cad629d56eb9",
            "date": "2018-06-28T08:28:18"
        }
    }
}
```

We have verified that the custom template is for the same language that the target site, also, we have verified that we are able to create new document libraries from the custom template manually from the SharePoint site, using the option "New app" and choosing the template.

How can we use custom templates for creating new document libraries on Sharepoint online sites with MS Graph?

**Comment by dzardoya** [comment]
Hi!

Any updates on that issue?

Thanks

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
