### ISSUE TITLE
Graph showing data from other customers, possible security breach

### ISSUE THREAD

**Issue by Vullers** [microsoftgraph/microsoft-graph-docs#2874]
Issue: 
Microsoft Graph is showing files that we do not have access to. We are getting usernames and filenames in the Microsoft Graph of files that are from other Office 365 tenants were we do not have access to or have any relationship with. When we try to open the link they access is denied.

I don't think it is good to put the output of the Graph Explorer here, because it contains personal information of Microsoft Customers that I don't know.

I've try'd to talk to Office 365 support, but they wanted me to post the problem here.

In my opinion this is vulnerability and goes against the GDPR law.

**Comment by Crispify** [comment]
I too believe this is a security breach happening in the /drive endpoint of the Graph API.

**Comment by Vullers** [comment]
Apparently the Office 365 finally sees the urgency of this problem and is asking me to test again. Now I do not see information about other customers.  @Crispify can you try again too ?

**Comment by Crispify** [comment]
Indeed, not seeing results from other tenants anymore.

**Comment by Vullers** [comment]
@CelticCoder I have send the email on how I got the results. This now is not possible anymore, also an escalation manager at Microsoft is working on this as well, maybe team up and investigate this further?

I can also assure you that this was not example / sample / demo data, this was real data, I've verified the people that were showing in the Graph output.

**Comment by CelticCoder** [comment]
@Vullers We received, I can confirm. Thank you for your extremely detailed response which aptly demonstrates the issue. We will revert. Thank you again for reporting this. We are working on this now

**Comment by jthake-msft** [comment]
There was an internal incident escalation on this. The issue was resolved last week. I apologize for not coming back to this thread to update here. I know that there was engagement with people on this thread directly via email.
