### ISSUE TITLE
SyncStateNotFound error: how to fix or avoid?

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2877]
Hello.
I am using Microsoft Graph API delta queries for downloading some information (messages, contacts, events) regularly. But sometimes I get this error:
```
{
    "error" :
    {
        "code" : "SyncStateNotFound",
        "innerError" :
        {
            "date" : "2018-06-01T06:31:24",
            "request-id" : "47e918a9-ce5b-42b4-8a86-12b96c93121a"
        },
        "message" : "The sync state generation is not found; generation=605;[highest=841][841][839][840]."
    }
}
```
I can't provide you steps for reproducing because I don't know how to reproduce it. It happens sometimes on production environment.

So I have some questions:

1. What is generation in Microsoft Graph API? Is there any available documentation about it? I didn't find anything useful in the Internet.
2. Why delta links expire? Delta link expires by time or some iterations of using delta links? Can I save my delta link in my database and in a e.g. 1 year use this delta link for syncing again?
3. How to avoid delta links expiration? Are there any lifehacks?
4. What should I do if I got this issue? Full resync and getting new delta link?
5. Is it a bug or feature?

Thank you.

**Comment by jthake-msft** [comment]
@dkershaw10 are you the right PM on delta questions? I think this would be great questions to answer in the docs on this

//cc: @angelgolfer-ms @lleonard-msft

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our [official channel for questions](https://developer.microsoft.com/en-us/graph/support). This is StackOverflow with 'Microsoft-graph' tag. 

I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
