### ISSUE TITLE
How to differ on-premise and online mailboxes

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2878]
Hello.

AFAIK Microsoft Graph API can work partially with on-premise mailboxes. In my case I need any way to divide mailboxes into 2 groups via Graph API: online mailboxes and on-premise mailboxes.

1. Is any good way for doing this stuff?
2. According to documentation there is possibility to set up on-premise: Exchange, Sharepoint, One Drive. If any of them is configured as on-premise for some user, does it mean that whole user will be detected as on-premise? My current solution is based on checking "OnPremiseSyncEnabled" field but I am not sure, is it valid solution or not.

Thank you.

**Comment by jthake-msft** [comment]
@ArunMSFT is there a way in the API to do this? I couldn't see it in the docs and couldn't see a property to filter by.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our [official channel for questions](https://developer.microsoft.com/en-us/graph/support). This is StackOverflow with 'Microsoft-graph' tag. 

I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
