### ISSUE TITLE
How to detect shared and resource mailboxes

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2879]
Hello.

Is there any way to detect shared and resource mailboxes?

Thank you.

**Comment by jthake-msft** [comment]
@ArunMSFT  sorry another one, couldnt' see this filtering either.

**Comment by jthake-msft** [comment]
I've confirmed with the team that this is not available.
@ZaMaZaN4iK could you please create a UserVoice feature request for this so the team can track this?
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis

**Comment by ZaMaZaN4iK** [comment]
@jthake-msft Thank you. Okay, I will create a feature request of UserVoice portal.

I hope you will try to answer another issues that I have opened.
