### ISSUE TITLE
userType field - which values are allowed?

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2880]
Hello.

Microsoft Graph API's User entity has field "userType". According to documentation there is no any information about this. There is one line: "A string value that can be used to classify user types in your directory, such as “Member” and “Guest”. Supports $filter.". So there is no any limitations :-)

1. Can be "userType" null? I can't PATCH existing user manually via graph api  - graph api return an error. But on production we have some users, which have "userType": null
2. Which values are valid for "userType"? Can you provide it in documentation or here please?

Thank you.

**Comment by jthake-msft** [comment]
@dkershaw10 could you provide more info on the userType for the docs?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our [official channel for questions](https://developer.microsoft.com/en-us/graph/support). This is StackOverflow with 'Microsoft-graph' tag. 

I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.

**Comment by rlisnoff** [comment]
My team has also gotten a "None" UserType during our usage of the Graph API, which leads me to believe this is still a problem.
