### ISSUE TITLE
How to enumerate deleted SharePoint sites via Graph API

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2881]
Hello.

Is it possible to enumerate deleted SharePoint sites via Microsoft Graph API? If yes, how can I do it?

Thank you.

**Comment by JeremyKelley** [comment]
Hi @ZaMaZaN4iK I don't believe we currently have a way to do this.

To get specific, are you looking for sites deleted in a site collection or site collections that are deleted in your tenancy?

Thanks!

**Comment by ZaMaZaN4iK** [comment]
@JeremyKelley I am interested in both cases.

**Comment by JeremyKelley** [comment]
We don't currently have a way to do this in the Graph APIs.  I would suggest going to User Voice https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform and putting the request there so it makes its way onto our backlog.

Thanks!

**Comment by ZaMaZaN4iK** [comment]
Can you add a remark about it to the documentation please?

**Comment by jthake-msft** [comment]
The documentation won't remark on what we don't do as the documentation would get too verbose and be impossible to manage. It would be assumed that if I was enumerating a collection of Sites, that it would not return deleted ones as they are deleted.
If you can raise a UserVoice for the feature that would be appreciated.
