### ISSUE TITLE
Get access to public folders on Exchange Online

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2882]
Hello.

Is there any way to enumerate and get access to public folders on Exchange Online via Microsoft Graph API? I didn't find any information in documentation about it.

Thank you.

**Comment by jthake-msft** [comment]
@ArunMSFT  is this available on Graph yet? I couldn't see it in the docs.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our [official channel for questions](https://developer.microsoft.com/en-us/graph/support). This is StackOverflow with 'Microsoft-graph' tag. 

I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
