### ISSUE TITLE
DriveItem Move error

### ISSUE THREAD

**Issue by dzardoya** [microsoftgraph/microsoft-graph-docs#2890]
Hi,

We are getting the following error when calling the Move method as described here: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_move

"Requested move requires an async response, add 'Prefer: respond-async' to allow"

If we add that header to the request it works, but it returns 202 instead of 200 as status code without response body. We need, as described in the documentation, that this method returns the new drive item id in the target drive.

We have tried it on another tenant and its working as expected, returning 200 and response body with the required information.

Can you check that, please?

**Comment by JeremyKelley** [comment]
Hi @dzardoya are you attempting a move within a drive or to another drive?  @ificator you may want to take a look at this one.

**Comment by ificator** [comment]
It would have to be a cross-drive scenario to trigger this behavior. Can you give us some details about the source and target drive? Did this scenario use to work for you?

**Comment by dzardoya** [comment]
Hi both,

We are using this method to move documents between 2 document libraries inside the same SharePoint online site. This works like a charm in our development tenant, but the behavior is completely different in the preproduction tenant as described.


Regards

**Comment by ificator** [comment]
Hi @dzardoya I just wanted to give you a heads up that we're going to be enabling the original change again now that we've fixed the issue you encountered. I've validated that your scenario looks good, but please let us know if you notice anything else weird.

**Comment by dzardoya** [comment]
Thanks for the update iflicator, I have tried and it keeps working as expected.

regards
