### ISSUE TITLE
Detect Mail user via Graph API

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2892]
Hello.

Is there any way to detect Mail Users (https://docs.microsoft.com/en-us/exchange/recipients-in-exchange-online/manage-mail-users https://technet.microsoft.com/en-gb/library/40300ed4-85a5-463d-bb3a-cf787bd44e9d.aspx) via Graph API?

Thank you.

**Comment by jthake-msft** [comment]
@ArunMSFT  I couldn't find this in the documentation . Do we have this yet on graph?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our [official channel for questions](https://developer.microsoft.com/en-us/graph/support). This is StackOverflow with 'Microsoft-graph' tag. 

I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
