### ISSUE TITLE
How to delete mail from RecoverableItemsDeletions via Graph API?

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2894]
Hello.

Is it possible to delete a mail via Microsoft Graph API from MailFolders/RecoverableItemsDeletions ? I tried to send a request, but got this error:

```
{
    "error": {
        "code": "ErrorCannotDeleteObject",
        "message": "Object cannot be deleted.",
        "innerError": {
            "request-id": "e6e208e3-1448-4888-8bf9-e61e90b8aab8",
            "date": "2018-07-20T08:46:05"
        }
    }
}
```

Thank you.

**Comment by jthake-msft** [comment]
@ArunMSFT  Do we document this anywhere? because we probably should?

**Comment by angelgolfer-ms** [comment]
Hi @ZaMaZaN4iK , FYI I added some general information about deleting the Recoverable items deletions folder in PR #2935. Please take a look if that helps.

**Comment by ZaMaZaN4iK** [comment]
@angelgolfer-ms Thanks a lot, but it's not about my question. I asked "How to delete messages from RecoverableItemsDeletions folder via Graph API" , not about "How to delete RecoverableItemsDeletions folder via Graph API". I think it's a little bit different case.

**Comment by angelgolfer-ms** [comment]
Hi @ZaMaZaN4iK , I clarified what I really meant in PR #2939 . :-) Both PRs point to this IT Pro article that might help you: [Clean up or delete items from the Recoverable Items folder](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/recoverable-items-folder/clean-up-deleted-items).
In summary, if a mailbox has been placed on "In-Place Hold" or "Litigation Hold", or has single item recovery enabled, you may not delete items in RecoverableItemsDeletions until the hold is removed or single item recovery is enabled. These conditions apply to _using the REST API_ to delete those items as well.

**Comment by ZaMaZaN4iK** [comment]
@angelgolfer-ms Thank you a lot! And thanks for the updated documentation :-)

**Comment by angelgolfer-ms** [comment]
@ZaMaZaN4iK , you are welcome. If it's fine with you, I am going to close this issue. If you have further questions on using DELETE for this purpose, please feel free to reopen the issue.
