### ISSUE TITLE
H2 links in content pages have anchors

### ISSUE THREAD

**Issue by jthake** [microsoftgraph/microsoft-graph-docs#29]
It would be great to have <A name="section-title" /> HTML elements that are the same as the DIV ID elements so that you can reference particular parts of a page more easily in the graph.microsoft.io documentation. For instance I would like to be able to refer to the ODATA v4 query supported parameters but can only reference the page right now http://graph.microsoft.io/docs/platform/rest and not the last heading section on that page.

**Comment by martellaj** [comment]
Probably a good thing to have. 

@sumurthy, do you think this is something that can be added during generation? I'm not sure how the MD to HTML conversion tool works enough to know if it would support HTML tags in Markdown.

**Comment by keyur32** [comment]
Coming back to this. Apologies for the delay in response. We added the ability to do this awhile back: click the In this article control link on the right hand side and you'll be able to see the anchor tag.
