### ISSUE TITLE
corrections to doc

### ISSUE THREAD

**Issue by sebastus** [microsoftgraph/microsoft-graph-docs#2902]
Issue: 
Integration with Azure Monitor Add-on for Splunk not quite right

Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/security_siemintegration.md#step-3-download-and-install-the-azure-monitor-add-on-for-splunk-which-will-allow-splunk-to-consume-security-alerts

In step 3a the doc says to put "_json" as the value of a new json property. The add-on does not use this value to determine the data is json - it uses it to know what Splunk sourcetype to use when transferring the data to splunk. It should be something like "amdl:security:alert". But the user has the final say - this is so when he writes the query in Splunk it has the right meaning.

In addition, the doc says to use "tenantId" in hubs.json. This value tells the add-on where to find the resourceId of the resource that is reporting or the resource that is being reported about. it is parsed by the add-on to get the subscriptionId, resourceType, resourceName and resourceGroup. Is tenantId really the source of this information in the Microsoft.SecurityGraph/alert feed?

Lastly, alert information from Security Center used to go through the Activity Logs. Is this no longer the case? The add-on has code that parses messages on the Activity Logs looking for this information and attaches a Splunk sourcetype accordingly. Should this code be modified?

**Comment by jthake-msft** [comment]
@edwardkoval could you take a look at this docs suggestion please?

**Comment by psmaan1** [comment]
@edwardkoval @jthake-msft: I tried to configure security alerts as suggested in the article 1) as it is and then 2) with additional suggestions given by @sebastus. Both times, Splunk was not able to initialize the monitor with following error:
ERROR ModularInputs - Unable to initialize modular input "azure_diagnostic_logs" defined inside the app "TA-Azure_Monitor": Introspecting scheme=azure_diagnostic_logs: script running failed (exited with code 1).

**Comment by sebastus** [comment]
This error is almost always a problem with dependencies. For diagnostic logs, the node.js dependencies. The best way to get a hint is to execute azure_diagnostic_logs.js from the command line in a bash shell, similar to how it's done in the shell script, azure_diagnostic_logs.sh.

**Comment by abakiaydin** [comment]
@psmaan1, there is also a new version of Azure Monitor Plugin, 1.2.9, that includes the suggestions from @sebastus. Even though the error seems relevant to dependency issues, I highly recommend using the new version for Microsoft Graph Security API integration. The documentation will reflect the changes in the new version where mainly you will not need to modify `hubs.json` and `logCategories.json` in step 3.3 of the current documentation.

**Comment by psmaan1** [comment]
@abakiaydin  @sebastus  I did use the latest version of plugin : 1.2.9. I made the changes suggested for hubs.json and logCategories.json, and it did not work. I reversed everything to original, and it worked. 
With this plugin, i am getting activity and diagnostic logs, However, it is not fetching "Security Alerts using Microsoft Graph API". Would it need any additional configurations to make that happen.

**Comment by sebastus** [comment]
@psmaan1 Can you confirm the event hub namespace and hub name that is receiving the security alerts? And can you confirm that the hub is actually receiving the alerts? Also, is the count of messages outbound from that hub non-zero? In other words, can you confirm that the correct hub is receiving alerts and that those alerts are not going somewhere besides where you want them to? If all of this is true, then modifying hubs.json is sufficient see the messages flow into splunk. Adding the line to logCategories allows you to tailor the splunk sourcetype of those messages so it's easier to query them.

**Comment by abakiaydin** [comment]
@psmaan1, I would be happy to help debugging remotely if the suggestions from @sebastus doesn't work. 
Please ping me at abaydin@microsoft.com when you need.

**Comment by psmaan1** [comment]
@sebastus : The event hub name is "insights-logs-alerts". I am bit confused on if I am receiving any alerts there. I have Zero incoming messages however, I can see substantial number of incoming requests to this. I can confirm that Splunk is making active queries to this hub. I disabled it and can see error in Splunk debug logs. I can see alerts using MS Graph explorer. I followed exact procedure to enable security alerts as mentioned in the link above.
@abakiaydin Thanks, I will contact you shortly.

**Comment by sebastus** [comment]
The requests is the Splunk add-on attempting to get messages each minute. You probably need to work on the Azure side of things - ensure that messages are going to that hub.

**Comment by preetikr** [comment]
The issue reported by @sebastus is now resolved by #3017 - thanks, for the report, @sebastus 
@psmaan1  - Thanks for reporting the monitor initialization error with Splunk integration. This is a separate problem hence we are tracking that in issue #3065
