### ISSUE TITLE
Issue with /messages

### ISSUE THREAD

**Issue by Shaydoth** [microsoftgraph/microsoft-graph-docs#2909]
Issue: 

Microsoft Graph /messages doesn't work as it says it will in the documentation.

Article:

In the documentation for /messages here https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list_messages it claims that when you make this api call it will, "Get the messages in the signed-in user's mailbox", and the call is located within the mail section of the documentation. When you actually make this call, it returns all messages that have been sent on that specific Microsoft account, for example any Teams messages you have sent will also come up there. The only way to specifically get emails sent is to use /mailFolders/inbox/messages, but that shouldn't be the way you get them, as the documentation says otherwise. Could you possibly add a type filter for when Microsoft graph queries exchange accounts to stop this?

**Comment by angelgolfer-ms** [comment]
Hi @Shaydoth , when you do GET /users/id/messages, the response includes all the messages in the specified user's mailbox, and that includes messages in folders like Inbox, Sent Items, Deleted Items, etc.
If you want to get only messages that have been sent by the specified user, you should do GET /users/id/mailfolders/sentitems/messages.
Does that help?

**Comment by Shaydoth** [comment]
Hey @angelgolfer-ms , unfortunately that does not help. I am well aware of the use of GET /users/id/mailFolders/inbox/messages to access the emails from an exchange account only. This is however, not the problem. The problem lies within the documentation of Microsoft Graph claiming that /users/id/messages returns all of the user's emails. This is evidently incorrect, as it also displays messages from other sources such as Microsoft Teams.

**Comment by angelgolfer-ms** [comment]
Hi @Shaydoth , I think you mean GET /messages responses include the user's chats in Microsoft Teams?
FYI I added this as a [known issue](https://developer.microsoft.com/en-us/graph/docs/concepts/known_issues) under the "Messages" section. Note that it may take up to 24 hours for the documentation site to refresh and display this note.
We hope to remove this note from the docs when the GET messages behavior is fixed.

Thanks!
