### ISSUE TITLE
[Outlook] how to get the in-place archive mailbox name

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2910]
Hi all,

`GET mailFolders/archivemsgfolderroot`

I use distinguish name to get this in-place mailbox folder
and the response is:
```
"displayName": "Top of Information Store",
```

However, this is not the custom name I modified on office365.
Is it possible to get that custom name?

thanks!

**Comment by jthake-msft** [comment]
@angelgolfer-ms  is this possible? I can't see custom name mentioned in the docs.

**Comment by joewutaiwan** [comment]
Hi @jthake-msft @angelgolfer-ms 

Thank you for reply,

Just add some reference:

modify here:
![image](https://user-images.githubusercontent.com/12619781/43297642-1f613b48-9185-11e8-88e7-c4b9b5ed98cf.png)

show here:
![image](https://user-images.githubusercontent.com/12619781/43297612-f9d7f43e-9184-11e8-9d62-25ac5955cafe.png)

**Comment by jasonjoh** [comment]
Graph cannot access the in-place archive mailbox, so no this isn't possible.
