### ISSUE TITLE
[Outlook] corrupted mail in mailbox

### ISSUE THREAD

**Issue by joewutaiwan** [microsoftgraph/microsoft-graph-docs#2913]
Hi all,

Just encounter a situation,
When I list messages using
`GET /mailFolders/id/messages?$top=500`
```
HTTP code 500
{
    "error": {
        "code": "InternalServerError",
        "message": "Error while processing response.",
        "innerError": {
            "request-id": "555f66a3-1030-4c11-82c5-15496510e03c",
            "date": "2018-07-27T07:20:20"
        }
    }
}
```
found that there is a corrupted mail in this query range

after I found the specific mail from EWS managed API
get the mail again

`GET /mailFolders/id/messages/id`
```
HTTP code 500
{
    "error": {
        "code": "ErrorContentConversionFailed",
        "message": "Content conversion failed., Content conversion: Body conversion failed.",
        "innerError": {
            "request-id": "39cc59a4-a669-48f1-abe1-a8e3f0edbef0",
            "date": "2018-07-27T07:06:30"
        }
    }
}
```
And the mail on O365:
![image](https://user-images.githubusercontent.com/12619781/43307567-3244e382-91b1-11e8-982e-725d31908c4d.png)

My question : 
1. Could the graph API just skip the corrupted mail?
2. Error handle in list API seems to be unclear.

Thank you for further help!

**Comment by ZaMaZaN4iK** [comment]
I think I got similar issue but with events. When I process request like this one (I replaced userId and calendarId): `GET https://graph.microsoft.com/beta/Users('userId')/calendars('calendarId')/events?$expand=attachments&$top=100&$skip=1500` I got this error:
`ReplyBodyError: { ErrorCode: "ErrorCorruptData", ErrorMessage: "Data is corrupt." }`

1. What is the reason of getting these errors?
2. How should we deal with it?

**Comment by jthake-msft** [comment]
@ArunMSFT is this expected behavior?

**Comment by lsnider** [comment]
I've received this on the `https://graph.microsoft.com/v1.0/me/messages/<message-id>` endpoint as well

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with 'Microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
