### ISSUE TITLE
Can't view messages on Graph Explorer anymore

### ISSUE THREAD

**Issue by LiviaMihalce** [microsoftgraph/microsoft-graph-docs#2914]
Hi All,

Microsoft Graph API currently returns 404 error when I try to access my messages:
GET https://graph.microsoft.com/v1.0/me/messages
Failure - Status Code 404, 
{
    "error": {
        "code": "ResourceNotFound",
        "message": "Resource could not be discovered.",
        "innerError": {
            "request-id": "95a3cbbc-e82f-46a8-ae64-73ffcce62de0",
            "date": "2018-07-27T13:18:23"
        }
    }
}

Please help us fix the issue ASAP.

Regards,
Livia

Issue: 

Article:

**Comment by angelgolfer-ms** [comment]
Hi @LiviaMihalce , Github says it's been 4 hours since you reported the problem. Do you still have the issue? Were you using the sample account or your own account in Graph Explorer?

**Comment by LiviaMihalce** [comment]
Hi All,

Issue is fixed now. Thanks a lot for your quick follow-up.

Have a great weekend,
Livia
________________________________
