### ISSUE TITLE
Delete User with Administrator rights with application

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2917]
Hello.

According to Microsoft Graph API documentation, it's possible to delete User **without** administrative rights via Graph API with Application permission: https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference

My question is: is it possible to delete a user with administrative rights by application? Which rights are necessary for doing this? 

Thank you.

**Comment by jthake-msft** [comment]
In the documentation for delete user the permissions are listed there https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_delete

**Comment by ZaMaZaN4iK** [comment]
@jthake-msft I know about this page, but if you will read the page on provided by me link you will see that described rights give us possibility to create/delete only non-administrative users. My question is about administrative users.

**Comment by jthake-msft** [comment]
@dkershaw10 @lleonard-msft  Dan I'm assuming we do this for a security reason? I think we should probably add to the docs that we explicitly don't support that.

**Comment by dkershaw10** [comment]
Not sure what changes are required.  This scenario is not supported (for security reasons) and is implicit in the description of the user.readwrite.all app-only permission:  
Allows the app to read and write the full set of profile properties, group membership, reports and managers of other users in your organization, without a signed-in user.  Also allows the app to **create and delete non-administrative users**. Does not allow reset of user passwords.

The only way to create/deleted admin users, is for an app to use a delegated permission, along with a user with sufficient privileges (to manage other admin users).

@ZaMaZaN4iK What's your scenario for deleting privileged users, using the application only flow?

**Comment by ZaMaZaN4iK** [comment]
We have some application permissions, which restore deleted users, enumerates their messages and delete these users again. And we can't do it for admins.

So, if it impossible... Should I create on User Voice feature request?

**Comment by jthake-msft** [comment]
Yes, if you can create a UserVoice request that would be appreciated.

**Comment by lleonard-msft** [comment]
@jthake-msft - Are we good to close this issue, then?
