### ISSUE TITLE
Life time of OneDrive downloadUrl

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2918]
Hello.

[Here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get_content) specified that `@microsoft.graph.downloadUrl` is valid for a short period of time (a few minutes). Can you specify in the documentation please - what does it mean "a few minutes" for you? 1 minute, 10 minutes, 1 hour or smth else?

Thank you.

**Comment by ZaMaZaN4iK** [comment]
@jthake-msft @JeremyKelley any news?

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our [official channel for questions](https://developer.microsoft.com/en-us/graph/support). This is StackOverflow with 'Microsoft-graph' tag. 

I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
