### ISSUE TITLE
How exactly OneDrive search query works

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [microsoftgraph/microsoft-graph-docs#2920]
Hello.

OneDrive supports search query ([link](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_search)). According to the documentation: ... The query text used to search for items. Values **may be** matched across several fields **including** filename, metadata, and file content.
 
Can you please describe more precisely, which fields **exactly** are used for search on OneDrive?

Thank you.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you, I know you've waited here for an answer. We have a new triage process that our customer experience team are monitoring on our [official channel for questions](https://developer.microsoft.com/en-us/graph/support). This is StackOverflow with 'Microsoft-graph' tag. 

I was trying not to close these off here in the documentation GitHub issues repo and get them answered.. It's proving too hard for me to be single point of failure here. Apologies. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
