### ISSUE TITLE
Not able to update PlanID for a task using update task API

### ISSUE THREAD

**Issue by mganeshphani** [microsoftgraph/microsoft-graph-docs#2925]
**Issue**: Failure - Status Code 403.. when tried to update PlanId for an existing task using update API. Trying to do this to move the planner tasks from one plan to another using automation and graph API
please see the request id and error info
{
    "error": {
        "code": "",
        "message": "You do not have the required permissions to access this item, or the item may not exist.",
        "innerError": {
            "request-id": "822184e5-b6c3-44cb-9578-abe7e67f5e39",
            "date": "2018-07-30T22:24:42"
        }
    }
}

**Article**:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannertask_update.md

**Comment by jthake-msft** [comment]
What scopes do you request in your call? Sounds like you don't have the correct permissions...

**Comment by mganeshphani** [comment]
@jthake-msft I am not passing any scopes in my call.. Infact the AAD application has them defined
Group.Read.All
Group.Write.All


Does this API support moving a task from one plan to another plan? by just updating PlanId on a task? or am I using this method for wrong purpose..

**Comment by jthake-msft** [comment]
From the documentation it doesn't look like this is possible https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/plannertask

@erayc-msft  can you add any more information here?

**Comment by jthake-msft** [comment]
Thx for clarifying @erayc-msft 

@mganeshphani if this is a feature that you desire, can you please submit a request for it on UserVoice? https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis

**Comment by jthake-msft** [comment]
@angelgolfer-ms what is the standard way to document this given @mganeshphani response above?

**Comment by angelgolfer-ms** [comment]
I think planId should be removed from the "Request body" section. +@TarkanSevilmis :-)

**Comment by TarkanSevilmis** [comment]
Sure, makes sense. I'll prepare a pull request for the change.

**Comment by mganeshphani** [comment]
Thankyou Folks, Appreciate it.

**Comment by jthake-msft** [comment]
@TarkanSevilmis  was their a Pull request for this, couldn't see it and would like to close the issue.
