### ISSUE TITLE
User Photos

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoftgraph/microsoft-graph-docs#2926]
Hi,

I have been trying to get organisational user profile photos. I can see them in graph explorer but am only able to retrieve my own photo when calling into the endpoint from an app.

Have tried everything listed in the docs etc. I suspect this is to do with mailboxes being on premise and not o365? If this is the case, perhaps the docs can be a little more detailed around these subjects?

One of the admins here says that he is not able to automate the migration of photos from either AD or Exchange on premise to Azure AD. Is there something I can point him to, which may make this possible? 

Thanks for any help and nice job on Graph - starting to getting there!

**Comment by jthake-msft** [comment]
@dkershaw10 can we have some guidance on the hybrid aspects of the graph in the docs specifically around profiles?

**Comment by yaw-innovate** [comment]
Hi @mrbrennonwilliams can you please confirm if you're still facing this issue? For your admins, you may point them to this doc, if they haven't seen it already. https://docs.microsoft.com/en-us/exchange/troubleshoot/administration/user-photos-not-synced-to-exchange-online.

**Comment by drfbwilliams** [comment]
Sorry - moved on 3 years ago.... Thanks for the response though.

**Comment by yaw-innovate** [comment]
Thanks for the feedback.
