### ISSUE TITLE
List all organisational users

### ISSUE THREAD

**Issue by mrbrennonwilliams** [microsoftgraph/microsoft-graph-docs#2930]
Hi,
Coming across scenarios where I can execute on an endpoint in Graph Explorer, but I'm not able to do the same in an application. Ensuring that scopes are correct, and using the same logged in user on both, I am left wondering just what is left that could be different?

Any guidance here would be great.

Cheers

**Comment by jthake-msft** [comment]
Did you admin consent the permissions to list all organizational users? Graph Explorer has a user consent flow and a admin consent flow that is optional.
In a Developer Tools in your browser, you can go to the console tab and type `tokenPlease()` and then use https://jwt.ms to decode it and look at the scopes it is using. You should compare that to your own application.

Ultimately the documentation explains what is required though 
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list

```
Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | User.ReadBasic.All, User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All, Directory.AccessAsUser.All
Delegated (personal Microsoft account) | Not supported.
Application | User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All

```

**Comment by mrbrennonwilliams** [comment]
Hi,
Thanks for picking this up.
All the scopes you list are being provided in the token request. It would appear to be an issues based around the enterprise management of azure profiles and registered applications.

This is the question the sys admin sent me:
"How does an enterprise Admin, approval/add the admin required permissions, either via the azure portal or via powershell cmdlets"

AFAIK the converged app can be seen in powershell, but not in azure. 

Is it possible to jump on a call with your folks so myself and the sys admins can talk through the scenario?

Thanks for the help

Cheers

**Comment by jthake-msft** [comment]
For adding admin consent to an application, you can sign into the Azure Portal and go to Azure Active Directory | Applications. And find the application listed there and grant the permissions. There is more information here https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-scopes#requesting-consent-for-an-entire-tenant and step by step here https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications

Just FYI. To get that level of support jumping on a call there are a few approaches. Do you have a [premier support](https://support.microsoft.com/en-us/premier) agreement with Microsoft? Or are you a partner who can [submit a support ticket](https://partner.microsoft.com/en-US/support/partnersupport)? Or are willing to pay for support (can purchase in packages of 5)?

**Comment by mrbrennonwilliams** [comment]
Hi Jeremy,

The set of applications this org is working on are called "converged" apps. The azure portal has not implemented the management of these V2 app graph permissions yet.

Linked from your document, you will note the "limitations" of V2 apps and in particular this line:

> Currently, for each app that you want to integrate with the v2.0 endpoint, you must create an app registration in the new Microsoft Application Registration Portal. **Existing Azure AD or Microsoft account apps are not compatible with the v2.0 endpoint**.

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-limitations

The sys admin found away to manage a converged app in the Azure portal, as long as admin permissions are being assigned to an application, but this does not appear to be best practice.


With regards to support - I'll reach out to some of my MSFT internal connections and see where that takes us.

Cheers

**Comment by mlafleur** [comment]
That is correct, v2 applications are currently not managed via the Azure Portal, they are managed via the Application Registration Portal (https://apps.dev.microsoft.com). 

To obtain Admin Consent of a v2 App, you need to provide the tenant admin an Admin Consent URL for the application. The prototype for an  Admin URL is `https://login.microsoftonline.com/common/adminconsent?client_id=[APPLICATION ID]&redirect_uri=[REDIRECT URI]`. When the Admin navigates to this URL and authenticates using their credentials, they are presented a Consent page listing the scopes requested and the ability to consent or reject the request. 

You might find this article helpful: [v2 Endpoint & Admin Consent](https://massivescale.com/microsoft-v2-endpoint-admin-consent/)

**Comment by jthake-msft** [comment]
@mrbrennonwilliams  sorry I made an assumption here on v1, but yes you are correct if you are doing v2 this is the right way to go that @mlafleur has mentioned.
So you know, there is work currently in flight, after speaking to the Identity team, that will dramatically improve this experience.
