### ISSUE TITLE
Beta resources contain dead links

### ISSUE THREAD

**Issue by NBMladenov** [microsoftgraph/microsoft-graph-docs#2931]
Issue: 
The property type "[outlookGeoCoordinates](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/outlookGeoCoordinates.md)" is a dead link and needs to be modified to "[GeoCoordinates](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/geocoordinates.md)".

The property type "[emailAddress](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/emailAddress.md)" is also a dead link and needs to be modified to "[emailAddress](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/emailaddress.md)".

Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/location.md

https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/attendee.md

**Comment by angelgolfer-ms** [comment]
@NBMladenov , thanks for reporting the link issues. PR #2932 should have fixed them. Please allow up to a day or so for the fix to be refreshed on the live site.
BTW, just to clarify, the first link you reported should be linked to outlookGeoCoordinates, not geoCoordinates. The link problem was that the destination file name had been specified in camel case and should have been all lower case instead.
Thank you for your support!
