### ISSUE TITLE
Cannot use "startswith" and "any"  about filter query

### ISSUE THREAD

**Issue by cloud-developer123** [microsoftgraph/microsoft-graph-docs#2933]
Issue: 

I want to get user's contact from address by using the forward match like below.
`/v1.0/me/contacts?$filter=emailAddresses/any(a:startswith(a/address,'user'))`

But this returns the following error:

``` json
{
    "error": {
        "code": "ErrorInvalidUrlQueryFilter",
        "message": "The query filter contains one or more invalid nodes.",
        "innerError": {
            "request-id": "bffeeef7-07c5-4db1-a60f-519fbef07fd7",
            "date": "2018-08-01T07:53:59"
        }
    }
}
```
Does the `filter` support the combination of  `startswith` and `any`?

**Comment by mlafleur** [comment]
I'm afraid not. According to the underlying [Outlook API documentation](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/complex-types-for-mail-contacts-calendar#contact), the `EmailAddresses` collection is not filterable.

**Comment by cloud-developer123** [comment]
Thanks for reply.

However, if EmailAddresses property doesn't support "filter", it also should be written in Graph document.

And, I also confirmed that if we used only "any", we could filter it by the following url.
https://graph.microsoft.com/v1.0/me/contacts?$filter=emailAddresses/any(a:a/address eq 'sample')

**Comment by mlafleur** [comment]
I agree this information should be revalidated and migrated over to the Graph documentation.

**Comment by angelgolfer-ms** [comment]
@MadsSibeko , can you confirm please? Thanks.

**Comment by MadsSibeko** [comment]
We support filtering using any on emailAddresses/address, but only using the EQ operator. Using a different operator or function (e.g. startswith(), NE, LE), or targeting a different property (e.g. emailAddresses/name) is not supported.

**Comment by angelgolfer-ms** [comment]
I made some updates per #3573 . They should be live tomorrow. (Please ignore the subsequent revert #3574 . That was due to an internal build issue. I have got around it.)

**Comment by angelgolfer-ms** [comment]
My updates in the list contacts topic ([v1](https://docs.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0) and [beta](https://docs.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-beta)) are live. Closing this task.
