### ISSUE TITLE
Convert to pdf from xlsx file over 1MB

### ISSUE THREAD

**Issue by cloud-developer123** [microsoftgraph/microsoft-graph-docs#2946]
Issue: 
I tried to convert a `.xlsx` file that was over 1MB to `.pdf` using the [`content?format`](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_get_content_format)

However, it returned following error: 

``` json
{
  "error": {
    "code": "notSupported",
    "message": "...",
    "innererror": {
      "code": "OfficeConversion_NotSupported"
    }
  }
}
``

Is this behavior specification?
It's better to write this behavior in this document.

**Comment by mlafleur** [comment]
Can you please add an example showing how you're calling the API? An error message without context is a little difficult to diagnose.

**Comment by cloud-developer123** [comment]
We are using api like below.
https://graph.microsoft.com/v1.0/me/drive/items/[item-id]/content?format=pdf

If we set .xlsx file that was over 1MB as [item-id], Microsoft graph api returns error.
If you want, I can share additional information.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with the 'microsoft-graph' tag.
I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.

**Comment by cloud-developer123** [comment]
OK. I will ask this in StackOverflow.
Thanks for your reply.
