### ISSUE TITLE
Permissions for Get User

### ISSUE THREAD

**Issue by mganeshphani** [microsoftgraph/microsoft-graph-docs#2947]
Issue: Why do Get User require lot of read-write permissions?

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_get 

Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | User.Read, User.ReadWrite, User.ReadBasic.All, User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All, Directory.AccessAsUser.All
Delegated (personal Microsoft account) | User.Read, User.ReadWrite
Application | User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All

**Comment by mlafleur** [comment]
I believe you misunderstand how scopes work. Scopes are documented from least to most permissive. You don't need to request all of these scopes (in fact, you absolutely _shouldn't_ do so). You should only request the least permissive scopes that support the functionality you require.  

For example, if all you're doing is reading the current user's profile, you only need to request  `User.Read`. If, on the other hand, you need to read _any_ user's profile, you would request `User.ReadBasic.All`.

**Comment by mganeshphani** [comment]
@mlafleur thankyou..   so just to read any profile in my org.. I need can use "User.Read.All".. correct?

also once I change my V2 application to reflect the new permissions.. should I wait for a while to get the application work with updated privileges or will it be seamless.. also how do I do a admin consent for V2 application? can you shed some light on this or redirect me to respective documentation
