### ISSUE TITLE
Update message body incorrect description or API bug?

### ISSUE THREAD

**Issue by randalpinto** [microsoftgraph/microsoft-graph-docs#2952]
Issue: In the description of this API it says that "The body of the message. Updatable only if IsDraft = true." however it is currently possible to update the body of a non-draft message. Is this a documentation error or an API bug?

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/message_update.md

**Comment by jthake-msft** [comment]
@angelgolfer-ms  can you verify this?

**Comment by jthake-msft** [comment]
This issues list is specifically for documentation content issues. This is not for questions or raising issues on the underlying service, sdks or samples. We have a triage process that our customer experience team are monitoring on our StackOverflow ‘[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph)’ tag for questions and issues.

**Comment by randalpinto** [comment]
@jthake-msft I don't understand why this issue was closed. The documentation says that body cannot be modified whereas if you use the API the body can be modified. So one of them is definitely incorrect.

**Comment by jthake-msft** [comment]
I apologize. I have re-opened this. I had too many tabs open in my browser. @angelgolfer-ms  can you verify please?

**Comment by randalpinto** [comment]
No worries @jthake-msft, thanks for reviewing. 

Btw, if i can cast a vote, I hope that the documentation is incorrect, we have a strong use case for being able to modify the body of an existing message.

**Comment by angelgolfer-ms** [comment]
I think this is by design, that you can't programmatically modify the body of a sent/received email in a mailbox. Other than the body property, there's a bunch of message properties that behave the same way, as noted in the topic.
@ArunMSFT , can you please confirm? Thanks.

**Comment by ArunMSFT** [comment]
@randalpinto - I would like to connect with you to understand the usecase. Can you drop me an email at arvaradh at microsoft dot com?

**Comment by abheek-das** [comment]
The documented behavior is correct (i.e., modification of only draft messages is allowed). Even if modification of non-draft messages works in certain cases, it would be blocked soon. For opening a feature request to support this officially, please use the following: https://feedbackportal.microsoft.com/feedback/forum/ebe2edae-97d1-ec11-a7b5-0022481f3c80

**Comment by randalpinto** [comment]
@abheek-das, back in 2018 I had a conversation with MSFT's product management team and I was assured that the behaviour was supported and would remain supported. We have an important use case for this. Happy to discuss.
