### ISSUE TITLE
Partially created assignment returned by the API

### ISSUE THREAD

**Issue by ftunholm** [microsoftgraph/microsoft-graph-docs#2957]
Issue: 
When creating an assignment in Microsoft Teams web application, it seems to be a delay between the creation of the actual assignment and some of it's properties. In our case the following scenario occurs:

Create an assignment and assign it directly in the Teams web application. If a listAssignments (https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/educationclass_list_assignments) request is made too fast - the API will return a partially created assignment that has null values for both assignDateTime and assignedDateTime properties.

**Comment by jthake-msft** [comment]
I'm sorry to have to do this to you. We have a new triage process that our customer experience team are monitoring on our official channel for questions. This is StackOverflow with the 'microsoft-graph' tag.

I was trying not to close these off here in the documentation GitHub issues repo and get them answered. This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.

It's proving too hard for me to be single point of failure here in assigning the correct engineers to answer questions. It is best for questions to go on StackOverflow where they'll be monitored by a dedicated team and escalated internally to PMs through a defined process.
