### ISSUE TITLE
Validity @odata.deltaLink

### ISSUE THREAD

**Issue by JValck** [microsoftgraph/microsoft-graph-docs#2962]
Issue:
How long is the `@odata.deltaLink` provided by the delta query valid? One year? Eternal? 30seconds?
Article:
[Track changes for a Drive](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_delta#permissions)

**Comment by jthake-msft** [comment]
@daspek  is it possible to provide this information in the docs?

**Comment by kumbhaj** [comment]
How long is @odata.deltalink valid? Please provide the information.

**Comment by kumbhaj** [comment]
How can we use the deltatoken obtained from deltalink to get new messages using java? I am unable to find how to use deltatoken using java to just get the new messages only.

**Comment by baywet** [comment]
thank you for pointing out this information was lacking in our documentation @JValck 
FYI I just authored PR #6961 to provide the information for AAD objects. 
hopefully @daspek and @svpsiva can provide additional information for OneDrive/SharePoint and Exchange.
