### ISSUE TITLE
User documentation is wrong (or Graph is broken)

### ISSUE THREAD

**Issue by CortanaLoneRanger** [microsoftgraph/microsoft-graph-docs#2978]
Issue: 

Using an MSA account and connecting to Graph via Cortana with appropriate permissions, I've run into the same issue as this while attempting to update the "Birthday Bot" example from 2017 Build.

https://stackoverflow.com/questions/48028896/microsoft-graph-api-does-not-give-birthday-user-information

Regardless of User.Read and User.ReadWrite being granted, the birthday on my profile is not returned. (I am trying a work around to add myself as a contact and get my birthday from contacts instead; but it seems odd that this data is obscured after a successful authentication.)

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples.
We a triage process that our customer experience team monitors on our official channel for questions. This is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag. I will close this issue so our documentation team can focus on content issues.
