### ISSUE TITLE
permissions for getting the team information and team members?

### ISSUE THREAD

**Issue by paul-cheung** [microsoftgraph/microsoft-graph-docs#2986]
i am following the [sample code](https://github.com/OfficeDev/microsoft-teams-sample-auth-node/blob/master/src/views/tab/simple/simple.hbs) to authenticate, the function on that page called 'getUserProfile' was used to get user information. but i am now gonna get current team information and list all members of this team, what permissions/accessToken should i have? i am using this [list team member](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/group_list_members) api

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
