### ISSUE TITLE
From property documentation is misleading [area: outlook] [bug: documentation]

### ISSUE THREAD

**Issue by devagnanam** [microsoftgraph/microsoft-graph-docs#3000]
Issue: 
The documentation is misleading as it says From property is editable. Yes it's doable only on specific scenarios, so it should be specific. The From/Sender property is editable but it is supported for specific scenarios like shared mailbox or delegate scenarios where one user wants to send out an email as another mailbox.

Article:
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations#SendMessageOnTheFly

**Comment by angelgolfer-ms** [comment]
Hi @devagnanam , thanks for your input. Do you mean making a clarification in the Microsoft Graph message_update.md article (https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_update)?
I can get clarification for that.

The article you referred to, btw, uses the Outlook endpoint (https://outlook.office.com). We hope Microsoft Graph can fulfill your needs, so please use the Microsoft Graph documentation. The Outlook endpoint documentation is no longer updated.

**Comment by devagnanam** [comment]
Thanks @angelgolfer-ms for the update and looking at this. Yes please update the Microsoft Graph documentation - it would be sufficient.

**Comment by angelgolfer-ms** [comment]
Hi @devagnanam , FYI, I made clarifications for the from and sender properties in the message.md and message_update.md topics, for v1.0 and beta, via PR #3004 . The content will be refreshed within the next day on the live site. Thank you for your support.
