### ISSUE TITLE
Unknown Error while generating a sharing link for one-drive for business

### ISSUE THREAD

**Issue by rahchau** [microsoftgraph/microsoft-graph-docs#3015]
**Issue**: We are using Microsoft.Graph ver. 1.10.0 in Xamarin Forms PCL and same version in iOS and Android platforms but while creating sharing link or sending invitation, graph APIs are throwing an unknown error.

**Code snippet causing a problem** - Permission permission = await graphClient.Me.Drive.Items[id].CreateLink("view").Request().PostAsync();

var invite = graphClient.Me.Drive.Items[id].Invite(recipients, true, new List<string>() { "write", "read" }, true, $"Inviation from {sender}");
                        var permissions = await invite.Request().PostAsync();

Article: Microsoft Graph API

**Comment by darrelmiller** [comment]
Hi @rahchau . Could I ask you to either move this issue to the msgraph-sdk-dotnet repository, or over to StackOverflow with the tag microsoft-graph-sdks?  This repo is just for documentation issues and from the looks of it, this seems to be either and SDK or service error.  Thanks.

**Comment by rahchau** [comment]
I have moved this issue to msgraph-sdk-dotnet repository in GitHub as per your suggestion. Thanks
