### ISSUE TITLE
Cannot get deviceSettingStateSummaries to return data for individual Settings

### ISSUE THREAD

**Issue by StuartNock** [microsoftgraph/microsoft-graph-docs#3033]
Issue: 

GET /deviceManagement/deviceConfigurations/{deviceConfigurationId}/deviceSettingStateSummaries/{settingStateDeviceSummaryId}

does not work, whilst

GET /deviceManagement/deviceCompliancePolicies/{deviceCompliancePolicyId}/deviceSettingStateSummaries/{settingStateDeviceSummaryId}

does work

can you please advise on how to get
GET /deviceManagement/deviceConfigurations/{deviceConfigurationId}/deviceSettingStateSummaries/{settingStateDeviceSummaryId} 
working,  whenever I run it with the appropriate ID's I get the error:

No OData route exists that match template ~/singleton/navigation/key/navigation/key with http verb GET for request /StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations...

Article:

https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune_deviceconfig_settingstatedevicesummary_get.md

**Comment by StuartNock** [comment]
further review has proven that 

GET /deviceManagement/deviceConfigurations/{deviceConfigurationId}/deviceSettingStateSummaries/{settingStateDeviceSummaryId}

also does not actually work, however 

GET
/deviceManagement/deviceCompliancePolicySettingStateSummaries/{CompliancePolicySettingStateSummaryId}

does produce a list of devices for the selected setting - I am looking to do the same thing for Configuration Settings

**Comment by StuartNock** [comment]
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation/key with http verb GET for request /StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations('308d0332-2b6d-4378-835a-284c47b89fde')/deviceSettingStateSummaries('6757c04f-e9ad-dfe7-1b87-6536e9538a34_308d0332-2b6d-4378-835a-284c47b89fde').",
        "innerError": {
            "request-id": "3478c709-ef69-4395-8b65-7608392b499a",
            "date": "2018-09-05T13:06:21"
        }
    }
}

**Comment by triplanedave** [comment]
Thanks for the feedback.  In this case, Graph allows the call to go through to that route, but we don't have any code at that endpoint to pick up the incoming call.  I've filed a bug for our developers to remove the endpoint from the documentation, as it's not an endpoint you can call.
