### ISSUE TITLE
Could not process subscription creation payload. Are all property names spelled and camelCased properly?

### ISSUE THREAD

**Issue by SergiiOliinyk** [microsoftgraph/microsoft-graph-docs#3041]
https://graph.microsoft.com/beta/subscriptions
{
   "changeType": "created,updated",
   "notificationUrl": "https://mywebhook.azurewebsites.net/api/send/sample",
   "resource": "me/mailFolders('Inbox')/messages",
   "expirationDateTime":"2018-09-05T18:23:45.9356913Z",
   "clientState": "secretClientValue"
}
If to send the date 2018-09- and set 5 instead of 05. It gives no corresponding error 
Could not process subscription creation payload. Are all property names spelled and camelCased properly?
I would suggest to be more precise. Day specified in wrong format for expirationDateTime.

**Comment by jthake-msft** [comment]
The change notification page makes reference to the subscription resource object.
https://developer.microsoft.com/en-us/graph/docs/concepts/webhooks

We do actually state the required UTC format in the resource object page.
 https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/subscription

Is this not satisfactory?

**Comment by 88SergiiOliinyk** [comment]
@jthake-msft documentation is ok, but the error Are all property names spelled and camelCased properly? - it doesn't reflect the problem. It says " about property names spelled and camelCased" - but the issue is in expirationDateTime value.

**Comment by jthake-msft** [comment]
@dan-silver  is this on our list to try and fix?

**Comment by 88SergiiOliinyk** [comment]
any update @jthake-msft @dan-silver ? Common 13 days

**Comment by sidxyz** [comment]
I have a similar issue , but I am not sure If this is has the same root cause.
Below is a screenshot of my request body and response headers.

Can you help me out?
![Screenshot 2019-11-18 at 5 58 26 PM](https://user-images.githubusercontent.com/22117977/69052524-3d82a680-0a2d-11ea-843e-8cd7b22c5c5c.png)

**Comment by sidxyz** [comment]
Well I figured it out. It was indeed a Date time issue ,
Here is my screenshot that worked just in case anyone else needs it

It would really help if you change the error message, or just show an error code and maybe a separate page for what they mean.

It is really frustrating when you are being pointed in the wrong direction with an error message.

![Screenshot 2019-11-18 at 6 20 57 PM](https://user-images.githubusercontent.com/22117977/69053768-2c876480-0a30-11ea-9267-3e9e0377b740.png)

**Comment by baywet** [comment]
Thanks for the updated details and sorry about the delayed answers.
We are looking into where is this erroneous message coming from.

**Comment by baywet** [comment]
Thanks for your patience on the matter @SergiiOliinyk 
We're currently in the process of rolling out a more explicit error message when the date is not formatted properly so customers have a better idea of what needs to be fixed when sending badly formatted payloads for subscriptions. We anticipate this change to be available in production by the end of the month.

**Comment by baywet** [comment]
The code change has been deployed to the service, the message now says "Could not process subscription creation payload. Are all property names spelled and camelCased properly? Also are the dateTimeOffest properties in a valid internet Date and Time format?"
