### ISSUE TITLE
use the MS graph api to list users with $filter=AccountEnabled  : Invalid filter clause

### ISSUE THREAD

**Issue by Joyw1** [microsoftgraph/microsoft-graph-docs#3044]
Issue: 

When use the MS graph api to list users with `$filter` : GET `https://graph.microsoft.com/v1.0/users?&$filter=AccountEnabled eq 'true'`, it gives the bad request error 
` "message": "Invalid filter clause"`, but according to the [official doc](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/user#properties), `accountEnabled` supports `$filter`.

![inva](https://user-images.githubusercontent.com/36072422/45022002-ac145800-b065-11e8-8705-d496d96862d5.PNG)

**Comment by cvcGitHub** [comment]
The problem is with quotes surrounding boolean value i.e. 'false'.
Try removing quotes around it and it'll work.

![capture1111](https://user-images.githubusercontent.com/31278945/45022750-9d707580-b052-11e8-81cf-f8932b3bc6ce.PNG)

**Comment by Joyw1** [comment]
Thanks @cvcGitHub , it works like a charm.;-)
