### ISSUE TITLE
500 Internal Server Error from Graph User API

### ISSUE THREAD

**Issue by bijithbalan** [microsoftgraph/microsoft-graph-docs#3046]
Issue: The API - GET https://graph.microsoft.com/v1.0/me is returning 500 Internal Server Error with body - An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below. [NullReferenceException: Object reference not set to an instance of an object.]

Article: https://graph.microsoft.com/v1.0/me

**Comment by jmaupin** [comment]
I am also encountering this problem and am seeing similar results from the Graph explorer.

**Comment by TheRealEliteOwl** [comment]
Can confirm that we are also receiving the error in Microsoft Flow. 

Also a note: POSTMAN seems to handle fine.....

**Comment by jmaupin** [comment]
It appears to be working correctly now.

**Comment by bijithbalan** [comment]
Yes, the API is working fine now. Thank you everyone.
