### ISSUE TITLE
No documentation for Subscription webhooks - tenant ID field missed 

### ISSUE THREAD

**Issue by SergiiOliinyk** [microsoftgraph/microsoft-graph-docs#3055]
I make a subscription due to documentation 
https://developer.microsoft.com/en-us/graph/docs/concepts/webhooks
1)In response on my webhook
`{
  "value": [
    {
      "subscriptionId": "b6d39c5f-9a8b-4642-a617-2de1663c2fd6",
      "subscriptionExpirationDateTime": "2018-08-06T11:00:00+00:00",
      "tenantId": "",
      "changeType": "created",
      "resource": "Users/20b663ae81ed297a/Messages/AQMkADAwATM3ZmYAZS0xN2JiAC1lMmMxLTAwAi0wMAoARgAAA0E0H85XdKJEoR52pY5G2U4HAN8--6iaIT5Bg_Vakuv-SKAAAAIBDAAAAN8--6iaIT5Bg_Vakuv-SKAAAAAD2ztoAAAA",
      "resourceData": {
        "@odata.type": "#Microsoft.Graph.Message",
        "@odata.id": "Users/20b663ae81ed297a/Messages/AQMkADAwATM3ZmYAZS0xN2JiAC1lMmMxLTAwAi0wMAoARgAAA0E0H85XdKJEoR52pY5G2U4HAN8--6iaIT5Bg_Vakuv-SKAAAAIBDAAAAN8--6iaIT5Bg_Vakuv-SKAAAAAD2ztoAAAA",
        "@odata.etag": "W/\"CQAAABYAAADfP/+omiE+QYPlWpLr/0igAAAD2smR\"",
        "id": "AQMkADAwATM3ZmYAZS0xN2JiAC1lMmMxLTAwAi0wMAoARgAAA0E0H85XdKJEoR52pY5G2U4HAN8--6iaIT5Bg_Vakuv-SKAAAAIBDAAAAN8--6iaIT5Bg_Vakuv-SKAAAAAD2ztoAAAA"
      },
      "clientState": "wqsqwsws"
    }
  ]
}`
I can't find this filed tenantID on subscription page.
Please update the documentation. 
2) In         "@odata.id":"Users/{user_guid}@<tenant_guid>/Messages/{long_id_string}",
Where should i specify <tenant_guid> to get it in notification ?

**Comment by 88SergiiOliinyk** [comment]
any update @jthake-msft @dan-silver ? Common 13 days

**Comment by jthake-msft** [comment]
if this is a question and not an issue about the documentation, can you please post on stackoverflow with microsoftgraph tag?
If it is an issue with the documentation, can you explain in more detail wha tis wrong with the docs?

**Comment by 88SergiiOliinyk** [comment]
The issue is that no documentation for tenantId. I think it’s pretty understandable what I wrote above. @jthake-maft

**Comment by jthake-msft** [comment]
are you asking where to get the tenant id from?

**Comment by 88SergiiOliinyk** [comment]
In the documentation for subscription there is no tenantId !

**Comment by jthake-msft** [comment]
The tenant id is different for every organization environment. You can get it like [this

]([url](https://developer.microsoft.com/en-us/graph/graph-explorer?request=organization&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com))

**Comment by TomerHeber** [comment]
I think it would make sense to pass tenantId for each notification. Anyways, it's unclear if and when the "tenantId" field is passed in notifications. In general the documentation states it is not passed in the notification. However, in the following link https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data I do see "tenantId" in the examples. (Maybe it's work in progress?).

**Comment by baywet** [comment]
Thank you for all the valuable feedback! We do pass the tenantId as part of the notifications and it was missing from the documenation.
I just authored a pull request #6902 to address that.
