### ISSUE TITLE
Attachments do not work when posting into Teams via https://graph.microsoft.com/beta/teams/{team}/channels/{channel}/chatthreads

### ISSUE THREAD

**Issue by adriancable** [microsoftgraph/microsoft-graph-docs#3058]
I am using the Graph API to post a new thread into a Teams channel, using something like this as the POST body:

        rootMessage: {
          body: {
            contentType: 1,
            content: 'Test content'
          },
          attachments: [{
            contentType: 'image/png',
            contentUrl: 'data:...',
            name: 'filename.png'
          }]
        }

The message content does appear in the channel, but there is no attachment. If I GET the https://graph.microsoft.com/beta/teams/{team}/channels/{channel}/messages, I can see my message there but attachments is [].

I have also tried contentType: 'reference' and contentUrl: 'https://something.com/image.png' but in all cases, there is no attachment posted.

There is a typo in the Graph API docs for chatmessage (it says 'attachment' for the key rather than 'attachments') but I am using the correct key.

Is this an API problem or a documentation problem? (i.e. is the API wrongly documented, hence following the documentation leads to this failure?)

Thanks!

-Adrian

**Comment by JSteunou** [comment]
I am very interested on some intel on this one too. Did you finally succeed to add attachments @adriancable?

**Comment by adriancable** [comment]
Jerome - not quite - but I managed to employ a workaround which was good enough for my purposes. I upload the image to OneDrive, use the createLink API endpoint to get a public link to it, and then I can post an HTML message into Teams containing an <a> tag pointing to that public link. Teams automatically displays images pointed to by links in posts, so it ends up displaying what I want it to.

**Comment by JSteunou** [comment]
This is the road I was ready to take. Thanks for the feedbacks !

**Comment by nkramer** [comment]
To close the loop on this -- no, we don't currently support posting attachments.

**Comment by Crazyconv** [comment]
I tried using <img src="public link of my image"/> but teams did not display the image. @adriancable could you show me how your constructed the message with the link? Thanks!

**Comment by clumdee** [comment]
> Jerome - not quite - but I managed to employ a workaround which was good enough for my purposes. I upload the image to OneDrive, use the createLink API endpoint to get a public link to it, and then I can post an HTML message into Teams containing an tag pointing to that public link. Teams automatically displays images pointed to by links in posts, so it ends up displaying what I want it to.

Would you be able to share an example HTML message with a public link? I can get a target link but cannot make a post that display an image.

Thank you.

**Comment by nkramer** [comment]
Close out the issue since it doesn't track a documentation bug.
