### ISSUE TITLE
Able to provision team when creating group, but not apearing as a team in Teams.

### ISSUE THREAD

**Issue by AlexanderHolmeset** [microsoftgraph/microsoft-graph-docs#3073]
Issue: When creating a Group using the beta API, even if its not listed as a property for the Request body:
https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/group_post_groups

You can add the following to the request body:
"resourceProvisioningOptions": ["Team"]

If you check the group you created with this property, it is listed to have a team provisioned to it, but does not apear as a team in the Teams client.
 Is this a bug or should using the "resourceProvisioningOptions" property when creating groups be blocked?
I know you can use PUT /groups/{id}/team to create a team from a group, but why is "resourceProvisioningOptions": ["Team"] availible when creating a Group?

**Comment by AveAdam** [comment]
You should call **_PUT /groups/{id}/team_** to create team after the Office 365 Group is created.

**Comment by AlexanderHolmeset** [comment]
I know that. Updated the original post so its more understandable why i
posted the issue.

**Comment by nkramer** [comment]
To close the loop on this -- yes, this is expected behavior. If you claim there is a team in the group when there isn't one by setting the ResourceProvisioningOptions, you will get groups that claim to be teams but aren't.
