### ISSUE TITLE
Documentation indicates that teams channels GET supports Odata but it doesn't

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-docs#3091]
Issue: GET https://graph.microsoft.com/beta/teams/<groupId>/channels?$filter=displayName eq 'something' returns the full data set and not a single channel.
However the documentation states that this endpoint supports OData.  
At this point I'm not sure whether it's an issue with the endpoint itself or with the documentation. If the documentation needs to be updated, happy to help with that.  

client-request-id: a5e174f7-236e-41ca-817b-762bf095952b
request-id: a5e174f7-236e-41ca-817b-762bf095952b

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/group_list_channels

**Comment by ArchSerpo** [comment]
Top and Select aren't working for me either

**Comment by nkramer** [comment]
Thanks for pointing this out, we have added support for this.
