### ISSUE TITLE
/me/memberOf API does not work with listed permission

### ISSUE THREAD

**Issue by aakashw** [microsoftgraph/microsoft-graph-docs#3093]
Issue: 
/me/memberOf API does not work with listed permission
As per document
The first three permissions can be granted to an app by a user. The rest can only be granted to an app by the administrator.
User.ReadBasic.All
User.Read
User.ReadWrite

Token generated with these permission is not working against /me/memberOf API endpoint
Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/users

**Comment by lhanson** [comment]
I think this is related to https://github.com/microsoftgraph/microsoft-graph-docs/issues/746#issuecomment-271371911, i.e. you need `Groups.Read.All`.

As far as I'm aware, there is no way to use the Graph API to query the groups a user belongs to without having an admin grant your app access to all groups on the tenant, which a non-starter at my org and I suspect many others. That introduces significant pain when trying to do the usual thing of basing authentication in your app based on a user's roles/group membership, which seems to be a blocker for a number of people at present (https://github.com/microsoft/azure-spring-boot/issues/383).

Can somebody explain the rationale behind this, and whether there's a different way we should be trying to get a user's roles/groups?

**Comment by talesleaves** [comment]
I found the necessary permission for us. The required permission is "Directory.Read.All".
Please check the following Microsoft Graph API information.
[List memberOf](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=cs)

It is resolved with this permission that 403 error appears at the time of authentication with OAuth.
Depending on the operation of the app, I think that you also need read access to Group and User.

**Comment by blacelle** [comment]
We used to rely on the role "Group.Read.All" within "Microsoft Graph".

But recently, we observed it does not work properly anymore, but the following role fixed the 403 issue: 'Member.Read.Hidden'

**Comment by krbain** [comment]
This issue has been reviewed and is planned to be addressed by a doc update.
