### ISSUE TITLE
$filter params support not documented.

### ISSUE THREAD

**Issue by LoungeFlyZ** [microsoftgraph/microsoft-graph-docs#31]
$filter only seems to support certain OData operations like startswith, but not many others.  It would be GREAT to have what operations are supported vs. the OData 4 specs so developers dont have to try each one out trail and error style.

**Comment by martellaj** [comment]
@siewmoi, do we know which operations are supported and which aren't? I agree with @LoungeFlyZ that this would be super beneficial for devs to see in the docs.

**Comment by Mike-Bell** [comment]
Not sure if it's worth making a whole new issue, but oData support in general seems pretty spotty and sometimes even inconsistent with the docs. For instance, this page http://graph.microsoft.io/docs/overview/query_parameters directly lists `https://graph.microsoft.com/v1.0/me/drive/root?$expand=children($select=id,name)` as a query to `only return the id and name properties of the children items`. But I definitely get full item objects in response (i.e. the exact same response as `https://graph.microsoft.com/v1.0/me/drive/root?$expand=children`).

Probably asking a lot, but it would be awesome if oData support in general were more consistent or at least better documented all around.

**Comment by jthake-msft** [comment]
@angelgolfer-ms I really think we need to tackle this OData support page. It is clear there is confusion on what OData filtering the Graph actually supports.

**Comment by jthake-msft** [comment]
Technically this is a feature request to get the remaining unsupported filters for Graph. As per the issue template creation process, feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support
