### ISSUE TITLE
Odata filter query does not work with group/members resource 

### ISSUE THREAD

**Issue by geekwhocodes** [microsoftgraph/microsoft-graph-docs#3112]
Issue: **Odata filter is not working with group/member resource:**
I am getting error while filtering group member using odata '_startswith_' string function. 

_Note: I was not able to find documentation which states that those queries are not supported for the give resource(group/{guid}/members). If it's not supported yet, please close this issue._ 

**Example URL:**
https://graph.microsoft.com/v1.0/groups/27ad2e64-fd50-439e-b96d-05cf9ef49985/members?$filter=startswith(userPrincipalName, 'Adele')

**Error details:**
```
"code": "Request_UnsupportedQuery"
"message": "The specified filter to the reference property query is currently not supported."
```

**Comment by FaithOmbongi** [comment]
@geekwhocodes 

To run the query successfully, please use:
https://graph.microsoft.com/beta/groups/{id}/members?$count=true&$filter=startswith(displayName, 'P'). 

Please see t[his example](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http#example-5-use-filter-to-get-group-membership-with-a-display-name-that-starts-with-the-letter-a-including-a-count-of-returned-objects) on the page. Take note that you must set the **ConsistencyLevel: eventual** header parameter.

In addition, not all parameters support OData query parameters. To verify which support specific parameters, please refer to the API's main resource page.

No updates identified for the page. Closing the issue.
