### ISSUE TITLE
OneNote preAuthenticated=true not working as documented/expected

### ISSUE THREAD

**Issue by damien122** [microsoftgraph/microsoft-graph-docs#3149]
Hi,
every time I try to use a onenote URI with preAuthenticated resources like jpeg, I got an error when try to access this pictures.

As documented I should just use this property in my page query and then the images are public assessable for one hour. But it won't work.

My Page content query:

`https://graph.microsoft.com/v1.0/users/XXXXXX@XXXXX/onenote/pages/XXX[PAGE_ID]XXX/content?preAuthenticated=true&includeIDs=true`

Afterwards I extract the `src `attribute from the `img `tag and try to access it:

`https://graph.microsoft.com/v1.0/users('XXXXXX@XXXXX')/onenote/resources/XXX[RESOURCE_ID]XXXX/content?publicAuth=true&mimeType=image/jpeg`

but every time I try to access this recourse I got the error:

> {
>     "error": {
>         "code": "InvalidAuthenticationToken",
>         "message": "Access token is empty.",
>         "innerError": {
>             "request-id": "XXXXXX-XXX-XXXX-XXXX-XXXXXXXXX",
>             "date": "2018-09-22T13:42:38"
>         }
>     }
> }

With the old API from `https://www.onenote.com/api/v1.0` everything works fine. But unfortunately this API is no longer active and I was forced to switch to `https://graph.microsoft.com/v1.0`.

Here is the part of the documentation [https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-get-content.md#image-or-other-file-resource](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-get-content.md#image-or-other-file-resource)

Can some one reproduce this error?

**Comment by damien122** [comment]
do someone react on requests here?

**Comment by manjushm-microsoft** [comment]
Can you send me the request-id and the timestamp when you made the request? I will look at our logs to find the issue. Thanks!

**Comment by damien122** [comment]
@manjushm-microsoft 
I have made two separate requests:

```
{
    "error": {
        "code": "InvalidAuthenticationToken",
        "message": "Access token is empty.",
        "innerError": {
            "request-id": "328ede37-e8b8-4a62-82cf-b3174437f32e",
            "date": "2018-10-06T11:26:32"
        }
    }
}


{
    "error": {
        "code": "InvalidAuthenticationToken",
        "message": "Access token is empty.",
        "innerError": {
            "request-id": "778e937b-2f52-4e23-a463-0dab12218b59",
            "date": "2018-10-06T11:31:36"
        }
    }
}
```

**Comment by damien122** [comment]
@manjushm-microsoft
could you find something at your backend?

**Comment by damien122** [comment]
@mlafleur could you please have a look? because of this problem I can't use my software anymore.

**Comment by jmrobyou** [comment]
Any update on this issue? can you MS confirm this is not working as listed in API docs. I tested with enterprise account, not working at all.

**Comment by damien122** [comment]
@jmrobyou I have tested it some days ago and fir me it works again with a personal account.

**Comment by jmrobyou** [comment]
@damien122 thanks for letting me know. I only has business account with enterprise version at work for Office 365. even i took the url for image generated from page content response, directly paste it into browser, got exactly the same error in your first post. and using same url, if i add token to request header, then i got image back. i am not sure if this only related to enterprise version.

**Comment by squidmarks** [comment]
I was just googling this, as I am seeing the same issue - glad I found someone with the same problem.  Whether its for a onenote page or a preview, I can get the correct response from either ../pages/{page-id}/preview or ../pages/{page-id}/content?preAuthenticated=true, but when I try to render either in a non-authenticated browser, I get this same "InvalidAuthenticationToken" message.

Geoff

**Comment by damien122** [comment]
@jmrobyou sorry my fault, it still not work. What I have tested was with Postman and I forget to unset authentication token. If I test such an preAuthenticated link in my browser, it still not work.

**Comment by damien122** [comment]
@manjushm-microsoft & @mlafleur could you please have a look here?
Why Microsoft don't fix something?

Here this document is wrong or the backend has a bug. 
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-input-output-html.md#output-html-examples-for-images

**Comment by jmrobyou** [comment]
@damien122 , no worries my friend, thanks again for keep me updated. at my workplace we opened a support ticket with MS for this issue, I will let you know what they response back. just FYI, I have another issue which is not able to retrieve any shared notebook content at all. After opened support ticket with MS, they said they didn't implemented the feature of retrieving shared notebook due to performance reason, and not sure when this feature will be implemented. This is really really bad, shared notebook used extensively in enterprise user scenario.
@squidmarks , yep, I have exactly the same error message, I don't know what other landmines out there in their API, I can't trust their doc, i have to test each one I need to confirm they work as they say in their doc :(

**Comment by squidmarks** [comment]
I have to say, just started working with this API to scrape notes pages for our group (just got enterprise 365).  I'm very disappointed with the API - everything I try to do seems painful.  I'm working in Node, hoping someone writes a more evolved interface as writing my own graph REST calls seems a bit archaic, these days.  For office 365 which seems to be around for awhile, seems that they should have a better interface than raw REST calls.  Need a Node graph component!  Best thing is, tho, the graph explorer - very helpful in troubleshooting and testing REST api calls when the docs are not all that great.  Ok, I'll stop complaining now...hopefully they take care of this issue...

Geoff

**Comment by paususe** [comment]
Is this still broken?

**Comment by damien122** [comment]
Hi @paususe, yes the problem is still existing. For me its over her. I will cancel my project.
