### ISSUE TITLE
Creating an event in a group automatically adds the creator as attendee?

### ISSUE THREAD

**Issue by tevert** [microsoftgraph/microsoft-graph-docs#315]
The behavior we're seeing:
1. Authorize against Azure AD using my credentials, to our application. 
2. Our application then creates an event on a group calendar (on my behalf) like so: 
3. POST /groups/1234-5678/calendar/events
4. The interesting part of the response is: 

``` json
{
   "attendees": [
      { "this is": "the group" },
      { "this is": "me" }
   ]
}
```

This behavior is consistent if I leave the attendee list undefined, or pass an empty list, or explicitly specify _just_ the group account. 

I'm wondering if it's possible to create that group event _without_ including myself on the attendee list by default. The alternative for me would be to fire an update request to explicitly remove myself, but that adds a bit of ugliness. 

Note that I'm currently using the using Microsoft.Graph C# client library; not that I would expect this to be an issue.

**Comment by shreedevi** [comment]
Hi tevert, Thanks for your interest. There is no option to not add the creator of the group event as an attendee right now, but this is one of the improvements we are considering for the API.
