### ISSUE TITLE
orderby and filter query do not work for ListDrives using Microsoft Graph API

### ISSUE THREAD

**Issue by sswati1507** [microsoftgraph/microsoft-graph-docs#3163]
I am trying to use orderby or filter to sort or filter the response of List Drives, but the api seems to ignore these query parameters. The documentation suggests that OrderBy is supported. 

Please suggest.

https://graph.microsoft.com/v1.0/sites/{site_id}/drives?orderby=name%20desc

**Comment by cperson** [comment]
I second this. The query I'm using is: 

https://graph.microsoft.com/v1.0/sites/{{sharepointSiteId}}/drives?$filter=name eq 'driveName'

**Comment by PumpkinVision** [comment]
I also would ask that filtering be enabled so that we can filter the drive listing by name.
