### ISSUE TITLE
User_Update documentation incorrect for user.PreferredLanguage?

### ISSUE THREAD

**Issue by MrTantum** [microsoftgraph/microsoft-graph-docs#3164]
Issue: 

I'm trying to update the preferred language of a user using the /me endpoint or the /users/{currentUserID} endpoint but this always throws:

403 "Insufficient privileges to complete the operation."

**This happens in the graph explorer app and also in a custom azure ad app I have created.**

![graphproblem 1](https://user-images.githubusercontent.com/31658807/46015765-6599a280-c0d3-11e8-9d9f-5c5aea987d66.png)
![graphproblem 2](https://user-images.githubusercontent.com/31658807/46015766-6599a280-c0d3-11e8-9e3f-0e4cc5867f5d.png)
![graphproblem 3](https://user-images.githubusercontent.com/31658807/46015763-6599a280-c0d3-11e8-802a-ba961053ba9f.png)
![graphproblem 4](https://user-images.githubusercontent.com/31658807/46015764-6599a280-c0d3-11e8-879f-8ffbf41e9700.png)

I have checked the permissions according to the documentation page and added the permissions for **User.ReadWrite, User.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All.** This does not seem to have any effect.

I closed the browser and started in private mode afterwards. Did not help.

The jwt-token looks fine: 

_"scp": "... **Directory.AccessAsUser.All Directory.ReadWrite.All** Files.ReadWrite.All Group.ReadWrite.All IdentityRiskEvent.Read.All Mail.ReadWrite MailboxSettings.ReadWrite Notes.ReadWrite.All openid People.Read profile Reports.Read.All Sites.ReadWrite.All Tasks.ReadWrite **User.ReadBasic.All User.ReadWrite User.ReadWrite.All** email"_

The request works fine if I execute it with an azure ad administrator user. The tenant is a development tenant. It has no On-Premise AD connection only Azure AD.

The [permissions Reference guide](https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference) states:

> For example, assume your app has been granted the **User.ReadWrite.All** delegated permission. This permission nominally grants your app permission to read and update the profile of every user in an organization. If the signed-in user is a global administrator, your app will be able to update the profile of every user in the organization. **However, if the signed-in user is not in an administrator role, your app will be able to update only the profile of the signed-in user.** It will not be able to update the profiles of other users in the organization because the user that it has permission to act on behalf of does not have those privileges.

Is the documentation incorrect or are there still permissions missing?

Article:

https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_update

**Comment by krbain** [comment]
Issue has been addressed and no longer repros.
