### ISSUE TITLE
not getting all the members information which mention in docs

### ISSUE THREAD

**Issue by Ady321** [microsoftgraph/microsoft-graph-docs#3190]
Issue: 
         when i checked the api for v1.0/education/classes/{classId}/members it is not showing all the information which mention in docs and how can i get all the information in v1.0

Article:

**Comment by ftunholm** [comment]
Hello @Ady321 I'm experiencing the same problem at this time, did you find a solution?

**Comment by Ady321** [comment]
Hi
You can get the information by using app only tokens not by delighted token

**Comment by ftunholm** [comment]
I see, thank you very much for your fast response. I'll look in to this.

Kind regards
