### ISSUE TITLE
Application owner can also be a ServicePrincipal object as well (besides user object)

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#3193]
Issue: The documentation for Application's Owners properties is missing ServicePrincipal

owners | directoryObject collection | Directory objects that are owners of the application. **The owners are a set of non-admin users who are allowed to modify this object.** Requires version 2013-11-08 or newer. Read-only. Nullable.
-- | -- | --

Need to Add ServicePrincipal object to the above documentation as wll

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/application

**Comment by davidmu1** [comment]
Removed the confusing sentence. A service principle is a directory object. Closing the issue.
