### ISSUE TITLE
Location Resource properties don't match JSON, incomplete

### ISSUE THREAD

**Issue by iambmelt** [microsoftgraph/microsoft-graph-docs#32]
https://graph.microsoft.io/GraphDocuments/api-reference/v1.0/resources/location.htm

The object properties list three fields:
`altitude`, `latitude`,`longitude`

but the JSON has two different fields:

``` json
{
  "address": {"@odata.type": "microsoft.graph.physicalAddress"},
  "displayName": "string"
}
```

**Comment by pschaeflein** [comment]
I have two different events. The location for one is a conference room found in the address book. The location result for that event:

```javascript
"location": {
  "displayName": "Conf Room Rainier",
  "address": {
    "street": "",
    "city": "",
    "state": "",
    "countryOrRegion": "",
    "postalCode": ""
  },
  "coordinates": { }
}
```
The second event has a location that was typed, instead of selected from the address book. The result for that event:

    "location": { "displayName": "MPR 2" }

**Comment by yinaa** [comment]
Location for events matching the schema is documented here: https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/location 
<ComplexType Name="location">
   <Property Name="displayName" Type="Edm.String" Unicode="false" />
   <Property Name="locationEmailAddress" Type="Edm.String" Unicode="false" />
   <Property Name="address" Type="microsoft.graph.physicalAddress" />
</ComplexType>
