### ISSUE TITLE
Access Review create return 500 error.

### ISSUE THREAD

**Issue by vgilbertsson** [microsoftgraph/microsoft-graph-docs#3215]
Issue: 
When trying to create a new accessreview the return is always 500. Including when using the example request in microsoft-graph-docs/api-reference/beta/api/accessreview_create.md

**Comment by lousimonetti** [comment]
I get the same error.  Has this been vetted yet? Any work arounds?

**Comment by lleonard-msft** [comment]
@markwahl-msft - Do you have any insight?

**Comment by lousimonetti** [comment]
I was able to create an Access review using the following request body
`
{
  "displayName": "string",
  "startDateTime": "2019-01-03T14:20:42Z",
  "endDateTime": "2020-09-24T14:20:42Z",
  "businessFlowTemplateId": "{businessFlowTemplateId}",
  "reviewerType": "entityOwners",
  "description": "test",
  "reviewedEntity": {
    "id": "{Group Object ID}"
  }
}
`

It only works for entityOwners - at least in my testing.  I ended up having to create an OpenAPI 3 version of the Microsoft Graph Beta $metadata and read it in Swagger UI.  I put the Swagger JSON [here](https://raw.githubusercontent.com/lousimonetti/MicrosoftGraph-OpenAPI/master/2019-beta-metadata.json) 
![image](https://user-images.githubusercontent.com/17498016/50710981-94aca200-103a-11e9-8411-a65e5b2d9063.png)

**Comment by lleonard-msft** [comment]
@vgilbertsson & @lousimonetti - It looks like Mark's updated the docs to address this issue.  Are we ready to close?

**Comment by lleonard-msft** [comment]
No follow-up from the OP; closing.
