### ISSUE TITLE
MaximumPlannerPlans limit should be documented

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-docs#3235]
Related to #3234 
Issue: 
The limit triggering the `MaximumPlannerPlans` error code (or how to get it depending on tenant configuration/licence or anything else) should be documented and available to developers.
Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/planner_overview#common-planner-error-conditions

**Comment by baywet** [comment]
Page has been moved here https://docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-1.0#common-planner-error-conditions

**Comment by lramosvea** [comment]
@baywet closing this issue as I can see this has been documented already. Feel free to reopen if you think this still needs to be fixed.
