### ISSUE TITLE
Beta - Drive Item - Invite (Add permissions)

### ISSUE THREAD

**Issue by titobf** [microsoftgraph/microsoft-graph-docs#325]
I'm using the invite method to share a file with another user: [Send a sharing invitation](http://graph.microsoft.io/en-us/docs/api-reference/beta/api/item_invite)

I expected it to return the sharing link in the response, the same link that is included in the email if "sendInvitation" is set to true, but it doesn't.

request body:

```
{
   "recipients":[
      {
         "email":"titobf@ekinex.onmicrosoft.com"
      }
   ],
   "message":"Sharing link",
   "requireSignIn":true,
   "sendInvitation":true,
   "roles":[
      "write"
   ]
}
```

response content:

```
{
    "@odata.context" : "https://graph.microsoft.com/beta/$metadata#Collection(permission)",
    "value" : [{
            "@odata.type" : "#microsoft.graph.permission",
            "grantedTo" : {
                "user" : {
                    "id" : "af7......",
                    "displayName" : "Augusto Barreto"
                }
            },
            "id" : "aTowI..........",
            "roles" : ["write"]
        }
    ]
}
```

I know I can use the [Create a sharing link for a driveItem](http://graph.microsoft.io/en-us/docs/api-reference/beta/api/item_createlink) but that creates a link accessible to anyone, whereas the link included in the invitation email requires sign in.

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
