### ISSUE TITLE
Is there any different between findmeetingtimes (outlook) and findMeetingTimes (ms graph)

### ISSUE THREAD

**Issue by korrio** [microsoftgraph/microsoft-graph-docs#3275]
Issue: 
https://outlook.office.com/api/v2.0/me/findmeetingtimes
https://graph.microsoft.com/v1.0/me/findMeetingTimes

Article:
I'm implementing the microsoft graph api called findMeetingTimes and found another simlar api name in outlook, is there any different between these 2 apis and which one should I stick with it.

**Comment by korrio** [comment]
Any other ideas ?

**Comment by milapshah15** [comment]
@korrio Is it working for you?I am getting error below

Request body

            {
                "attendees": [
                {
                    "type": "required",
                    "emailAddress": {
                    "name": "M",
                    "address": "xxxxxx@xxx.com"
                    }
                }
                ],
                "locationConstraint": {
                "isRequired": false,
                "suggestLocation": false,
                "locations": [
                    {
                    "resolveAvailability": false,
                    "displayName": "xxxx"
                    }
                ]
                },
                "timeConstraint": {
                "activityDomain": "work",
                "timeslots": [
                    {
                    "start": {
                        "dateTime": "2019-04-18T09:00:00",
                        "timeZone": "Pacific Standard Time"
                    },
                    "end": {
                        "dateTime": "2019-04-20T17:00:00",
                        "timeZone": "Pacific Standard Time"
                    }
                    }
                ]
                },
                "meetingDuration": "PT2H",
                "returnSuggestionReasons": true,
                "minimumAttendeePercentage": 100
            }

            Error 

            {
                "error": {
                    "code": "BadArgument",
                    "message": "Invalid user address",
                    "innerError": {
                        "request-id": "02d99e8e-b61f-4e4a-96de-371cd3786489",
                        "date": "2019-04-18T23:12:55"
                    }
                }
            }
