### ISSUE TITLE
Outlook message file attachment always returns a null contentLocation

### ISSUE THREAD

**Issue by seandhoey** [microsoftgraph/microsoft-graph-docs#3278]
Issue: The title pretty much explains it. Whenever I get a Graph API response for an attachment, the contentLocation is always set to null. This means if I want to get the file, I must convert it from the contentBytes field, and never filter out the cumbersome contentBytes field.

API request format: https://graph.microsoft.com/v1.0/me/messages/{id}/attachments/{id}

Related documentation: [https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/fileattachment](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/resources/fileattachment)

**Comment by seandhoey** [comment]
Given this issue, this is how I am currently dealing with it:

1. Get the list of messages for the authenticated user.
2. For each message ID, get the list of attachments associated with it. Only return the name and id.
3. For each attachment ID, get all of its data. This means that fields such as contentBytes and contentLocation are also returned.
4. Given the base 64 string in contentBytes, turn it into a file.

From testing, I have found that the time it takes to get the API request in step 3 is my bottleneck. This is due to the large amount of data being returned in the field contentBytes. I will call this the "download". A file of 2MB can take up to 10 seconds to download on a good connection. When I am limited to a download speed of 5mbps, this can take over a minute to retrieve. If I must stick to working with contentBytes, surely there is an explanation why the download is so slow? What can I do to improve it?

**Comment by jeevaengg21** [comment]
Any latest update on this issue ? we are still gettingll returned for Message.attachments

**Comment by kavitha1051** [comment]
Still the issue is open, please update the status

**Comment by jasonjoh** [comment]
Per the [docs](https://docs.microsoft.com/graph/api/resources/fileattachment?view=graph-rest-1.0), regarding `contentLocation`:

> Do not use this property as it is not supported.

You must use `contentBytes`. If you have feedback on the design of the API, please use [UserVoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).
