### ISSUE TITLE
MS Graph docs missing information on how to create a new Service Principal object

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#3282]
Issue: The following documentation does not have any info on how to create a new Service Principal object:  https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/serviceprincipal 

Article:

**Comment by shyamkris** [comment]
The POST call doesnt work.
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Specified HTTP method is not allowed for the request target.",
        "innerError": {
            "request-id": "04c30e03-8ce5-45df-b472-3308c8b30776",
            "date": "2019-03-15T06:26:20"
        }
    }
}

**Comment by davidmu1** [comment]
https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-beta&tabs=http

Closing the issue.
