### ISSUE TITLE
The contact list length from graph contacts api does not match with the the contacts count shown by the people page of office365

### ISSUE THREAD

**Issue by huanhulan** [microsoftgraph/microsoft-graph-docs#3286]
Issue:  We are using the graph api to fetch the contacts. But for a special test account the result from the Graph API does not match with what shown by the people panel of the Office365. 
![Screen shot](https://i.stack.imgur.com/ivflp.png)

Article: https://stackoverflow.com/questions/52848161/the-contact-list-length-from-graph-contacts-api-does-not-match-with-the-the-cont

**Comment by huanhulan** [comment]
Also, we do import the contact list twice by running script which resulting in duplicated contacts data which do have different id field. And we cannot find the duplicated ones from the people panel of the Office365. 

But if I remove the duplicated ones by `displayName`, the result would be **5507** other than **5517**.

So, how the O365 decide which one is duplicated so they can show only 5517 contacts other than 6586. I want a `generic solution` for the question.

**Comment by kevinbellinger** [comment]
This is due to the "people" API being used for the list view. It de-dupes duplicate or linked entries. We're working on a new Contact API which will replace the existing experience API's and provide consistency.
