### ISSUE TITLE
Attendee Documentation missing fields

### ISSUE THREAD

**Issue by iambmelt** [microsoftgraph/microsoft-graph-docs#33]
I seem to recall that an [attendee](https://graph.microsoft.io/docs/api-reference/v1.0/resources/attendee) has an `EmailAddress` - it seems like quite a few fields are missing from the documentation of this object.

**Comment by martellaj** [comment]
Thanks for the feedback, @iambmelt. :sheep: 

@VenkatAyyadevara-MSFT, can you confirm this?

**Comment by angelgolfer-ms** [comment]
The documentation for both v1.0 and beta is up-to-date now :-)

https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/attendee
https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/attendee

Cheers!

Angelgolfer-MS
