### ISSUE TITLE
Application Owner can not be group object

### ISSUE THREAD

**Issue by Powerhelmsman** [microsoftgraph/microsoft-graph-docs#3303]
The issue was created by @bachoang from https://github.com/MicrosoftDocs/feedback/issues/718

Group object is not allowed to be an Application's owner per https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/application. Trying to make a Group object to be an owner will result in error
The reference target 'Group_xxx' of type 'Group' is invalid for the 'owners' reference.',
The following documentation on this is wrong:
https://docs.microsoft.com/en-us/rest/api/graphrbac/Applications/AddOwner

**Comment by dkershaw10** [comment]
Thanks for filing this issue. The doc you are referencing are part of the Azure SDK and not Microsoft Graph, and we look at Microsoft Graph only as part of this repo.  You should let the doc owners for that referenced doc know that only users and servicePrincipals can be valid owners at this time.

**Comment by dkershaw10** [comment]
Should have closed this earlier.
