### ISSUE TITLE
Presence API + Call API

### ISSUE THREAD

**Issue by vovanb** [microsoftgraph/microsoft-graph-docs#3309]
I have two questions for Teams API: 
1. If exist any way to register for presence events and change user presence?
2. If exist any way to register for user calls and answer, hangup call on behalf-of user?

**Comment by nkramer** [comment]
There's not currently a way to do either of those. Consider requesting/uploading a feature on [Uservoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis?query=team).
