### ISSUE TITLE
Is The Graph API for Creating Calls Outdated?

### ISSUE THREAD

**Issue by speschka** [microsoftgraph/microsoft-graph-docs#3344]
After having every request for creating a new call fail with a 400 - Bad Request error, I finally just copied and pasted the entire payload from microsoft-graph-docs/api-reference/beta/api/application_post_calls.md into my code...and it also fails with a 400 - Bad Request error.  Is this really working somewhere?  Seems more likely the documentation is outdated, in which case, how can we get it updated?

**Comment by ksikorsk** [comment]
Hi, thanks for reaching out.  We can certainly help you with your issue.  First if you don’t mind I’d like to get some more information.

Are you using any of our SDKs, or are you using the REST API directly?
Are you able to attach the full http response (including headers)?

Once I can track down your request in our logs, I can troubleshoot why you are getting the 400 response.

**Comment by ksikorsk** [comment]
Hi @speschka, one more request please.  This repository is for all of graph, we have one specific to the communications infrastructure.  Would you mind posting your question in the following repository?

https://github.com/microsoftgraph/microsoft-graph-comms-samples

**Comment by speschka** [comment]
No problem @ksikorsk, I was hoping there was one specifically for calls, but the Issues tab on the Calls page took me here.  I'll repost using the link you have above, and then I'll follow up with the header info you are requesting.  Thanks!
