### ISSUE TITLE
Broken link to manage devices page

### ISSUE THREAD

**Issue by mahoekst** [microsoftgraph/microsoft-graph-docs#3434]
Issue: 
microsoft-graph-docs/concepts/azuread-identity-access-management-concept-overview.md has a broken link to manage devices
       
Article:
microsoft-graph-docs/concepts/azuread-identity-access-management-concept-overview.md

**Comment by jthake-msft** [comment]
Thanks buddy! Sorry we've been mid swing on migration, we'll get to this tomorrow when migration is done!

**Comment by Jackson-Woods** [comment]
Resolved in PR #3514. Closing the issue.
