### ISSUE TITLE
Students not being added to Class Notebook

### ISSUE THREAD

**Issue by justinclak** [microsoftgraph/microsoft-graph-docs#3469]
I posted this on StackOverflow but I suspect that it may be a bug or missing feature.

When adding a student to a class using Education.Classes[""].Members, they do not get access to the Class Notebook and do not get a Section Group created for them.  I get the same results when I use Groups[""].Members.  If I open the Class in Microsoft Teams, and manually add or remove any member then the groups and permissions are configured correctly, even for the students that were added only using the Graph API.  

https://stackoverflow.com/questions/53452782/adding-students-with-the-api-and-class-notebook

**Comment by jthake-msft** [comment]
I'm going to close this and get the PM to answer this on the stackoverflow post. If we think that we can improve docs to clear this up, we will do that too!
