### ISSUE TITLE
Subscriptions for resource calendars

### ISSUE THREAD

**Issue by markolb81** [microsoftgraph/microsoft-graph-docs#3510]
Hi,
is it also possible to create a subscription to the exchange calendar of an exchange-resource (meeting room calendar)? Despit full delegated rights on that resource calendar, I receive an "ExtensionError" with Message "Operation: Create; Exception: [Status Code: Forbidden; Reason: Forbidden]".

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
It is possible to create a subscription to a shared calendar using application permissions (app-only) with Calendars.Read, but not delegated user permissions. If you would like us to prioritize this scenario, please submit a user voice request. https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis

**Comment by jthake-msft** [comment]
Re-opening. We should make it clearer in these docs that only app-only is supported for shared calendar.

**Comment by rajeshkrrajjo** [comment]
Error: I am unable to create a subscription as it throws me error as shown below, can you please help?
Code: InvalidRequest Message: Subscription validation request failed. Must respond with 200 OK to this request. Inner error

**Comment by angelgolfer-ms** [comment]
@jthake-msft , PR #3656 will contain the doc updates in the subscription CRUD topics to clarify the permissions that support subscribing to Outlook contacts, events, or messages in user mailboxes.

Basically:
- The Outlook sharing permissions (Contacts.Read.Shared, Calendars.Read.Shared, Mail.Read.Shared, and their read/write counterparts) allow reading or writing contacts, events, and messages in shared or delegated folders. These sharing permissions do **not** support subscribing to change notifications on items in shared or delegated folders. 
- Instead, use the corresponding delegated permission to subscribe to items in folders in the signed-in user's mailbox. 
- Or, use the corresponding application permission to subscribe to items in any user's folders and mailbox in the tenant.

**Comment by asith-w** [comment]
@jthake-msft  how do we create a subscription to a shared calendar using application permissions (app-only) with Calendars.Read, but not delegated user permissions.  ? 

```
{
   "changeType": "created,updated",
   "resource": "users/user@mydomain.com/events",
   "notificationUrl": "https://webhook.azurewebsites.net/api/send/myNotifyClient",   
   "expirationDateTime":"2016-11-20T18:23:45.9356913Z",
   "clientState": "secretClientValue"
}
```

**Comment by MarkRBM** [comment]
When using application permissions in this way, ie to allow an application to create a subscription to a rooms calendar, is there a way to granularly decide which calendars an app has access to? for example I want to allow the application to have access to all room calendars but not to any users calendars?

**Comment by angelgolfer-ms** [comment]
@asith-w , @MarkRBM , would you please post your questions on [stackoverflow](https://stackoverflow.com/questions/tagged/microsoft-graph), making sure to tag your posts with [microsoft-graph]?
There's a better chance your questions would get answers there.

**Comment by maxlund** [comment]
There really should be a way to subscribe to only shared calendars without requiring read permissions to every single calendar in the tenant. Since there already is a Calendars.Read.Shared permission, I can set up this behavior myself by polling the calendars I'm interested in - why can't I also be notified of changes in these calendars using the same permission?
