### ISSUE TITLE
MaximumPlannerPlans Error Code

### ISSUE THREAD

**Issue by longnlp** [microsoftgraph/microsoft-graph-docs#3517]
I received the MaximumPlannerPlans error code when create the second plans for Microsoft Teams, this is can be done by the Teams UI, why the API is not allowed? Thank you.

Long

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab7673b3-983b-652f-64ff-80eaf048ad31
* Version Independent ID: 945a792e-fef8-c57e-3632-4da58996f088
* Content: [Use the Planner REST API - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-1.0#common-planner-error-conditions)
* Content Source: [api-reference/v1.0/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/planner-overview.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
Can you please ask questions about service issues on stackoverflow.com with tag microsoft-graph, feedback system is meant for feedback on the content of the docs, not troubleshooting service issues. If you have a paid support agreement, you can also raise a support ticket.

**Comment by longnlp** [comment]
Thank you @jthake-msft , I posted here because there is no MaximumPlannerPlans error code mentioned in this document, and also there is no good answer for this question from stackoverflow.com 
posted by other people. https://stackoverflow.com/questions/51299049/microsoft-graph-api-creating-a-plan-returns-maximumplannerplans-exception

What else place we can post the graph api issue? Thank you.
Long

**Comment by jthake-msft** [comment]
I've submitted #3531 to be more specific on this. Essentially the API is limited right now to creating one plan per Group, whereas this limit does not exist for creating plans through Microsoft Teams UI.

**Comment by longnlp** [comment]
Thank you @jthake-msft for your help.
