### ISSUE TITLE
Requesting for Github Project Sample

### ISSUE THREAD

**Issue by velanchandru** [microsoftgraph/microsoft-graph-docs#3529]
Actually i followed this article but couldn't succeed till the end , steps i followed , registered  application in apps.dev.microsoft.com got the appSecret and appID and approved the consents as Admin in Azure but i cannot proceed after authorization,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
Could you please post your question on stackoverflow.com with tag microsoft-graph. These feedback requests are specifically for issues in the documentation. On stackoverflow we can help you to get your app running. I will close this issue. Feel free to reply here with the stack url.
