### ISSUE TITLE
You can not use OData Query Parameters

### ISSUE THREAD

**Issue by christiandgv** [microsoftgraph/microsoft-graph-docs#3530]
Currently can not be used  OData Query Parameters, but in this document it is indicated that if possible, is very necessary add this functionality

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 7ebb8175-fd04-5a6f-f3f9-4b64e385dc24
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List group members - Microsoft Graph beta](https://docs.microsoft.com/es-es/graph/api/group-list-members?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list-members.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by Jackson-Woods** [comment]
@madansr7 Can you clarify which operations are supported on this API?

**Comment by alan994** [comment]
HI all,

There is one limitation in this call and that is if you want get all members from group you will get only first 100. If group has more than 100 members you will need to work with @odata.nextLink property. We manage to work around this with "$top=999" parameter. 

https://docs.microsoft.com/en-us/graph/query-parameters#top-parameter 

Also $count parameter is not working on this call 
https://docs.microsoft.com/en-us/graph/query-parameters#count-parameter

**Comment by fenxu** [comment]
I have a requirement that check if a user is a member of a group. If filter can use in members, that would meet my requirement.

**Comment by madansr7** [comment]
@fenxu , filtering is not a supported query option but you can write a query to select the 'userPrincipalName' for a particular group and then check if their name is in the response. 
`https://graph.microsoft.com/v1.0/groups/{id}/members?$select=userPrincipalName` will get you a collection of UPNs which you can query locally to check if the user exists.
hope this helps.

**Comment by fenxu** [comment]
@madansr7 Thanks for quick response. However, it seems not big different without query as I still needs to get all paginate results and check result page by page. Any other better idea that I can call with result directly?

**Comment by riginding** [comment]
I also have a problem with `OData Query Parameters`. It is not clear which, `OData Query Parameters` are available on the `list group members` resource. $top is working, but $skip is not.

**Comment by umutge** [comment]
If filtering is not supported, optional query parameters section should be reworded

**Comment by andrewalderson** [comment]
Filter is working for me. This query ```await graphClient.Groups[tenantId].Members.Request().Filter($"Id eq '{userId}'").GetAsync();``` works fine.

**Comment by rodiaza** [comment]
I have tried many OData filters, none of them seem to work, here's an example

https://graph.microsoft.com/v1.0/groups/{group id}/members?$filter=id eq '{userId}'

{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported referenced-object resource identifier for link property 'members'.",
        "innerError": {
            "request-id": "197ee1d4-130f-43f6-a455-3b9ce09cf3e0",
            "date": "2020-04-01T05:50:54"
        }
    }
}

**Comment by yyuank** [comment]
I can't repro the error with filtering group member with id. Please file a support case, if similar issues continue.
