### ISSUE TITLE
Tenant Id

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#3540]
We use the value tenantId across many docs here, for instance the calling apis, but searching on how to get the tenant id returns no results. The property on the resource object is called id but even in the description we don't label it tenant id so search doesn't pick this up. We should optimize the description so this does work out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8453dc23-7ef7-8ee0-9342-4709ee532672
* Version Independent ID: 20aa3e3e-2f05-f307-fb36-2281cafc1cbf
* Content: [organization resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/organization.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by lleonard-msft** [comment]
@jthake-msft - [PR #3662](https://github.com/microsoftgraph/microsoft-graph-docs/pull/3662) was merged and addresses this issue.  Are we ready to close this?

**Comment by lleonard-msft** [comment]
No reply from OP; closing.
