### ISSUE TITLE
Object Types Incorrect

### ISSUE THREAD

**Issue by kcrosby** [microsoftgraph/microsoft-graph-docs#3549]
EDIT: Fixed metadata lines so they would show up.

Something is amiss... the sample data shown above is from Outlook contact object as defined in the metadata as:

`<EntityType Name="contact" BaseType="microsoft.graph.outlookItem" OpenType="true">`

and the sample data above matches the contact definition shown here: https://docs.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-beta

HOWEVER... the link in this article (and 'Get Org Contact' too) indicates it should be of type orgContact as defined in the metadata as:

`<EntityType Name="orgContact" BaseType="microsoft.graph.directoryObject" OpenType="true">`

with sample data based on this link (which is the one included in this article): https://docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta

so if 'GET /contacts' returns contact objects, then how do we retrieve orgContacts?  'GET /orgContacts' yields a 400 error and:

{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'orgContacts'.",
        "innerError": {
            "request-id": "d1e47f28-4034-469e-9db9-b982111725ef",
            "date": "2018-12-04T22:42:43"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410096e1-fd64-dcb9-8248-6ae543c62f28
* Version Independent ID: 25d607e0-2216-5191-ff3d-119fb816369d
* Content: [List orgContacts - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/orgcontact-list.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by kevinbellinger** [comment]
/contacts = org contacts (orgContact entity)
/me/contacts = user contacts (contact entity)
