### ISSUE TITLE
Members are not getting displayed on SharePoint Page under Group Membership

### ISSUE THREAD

**Issue by Prakash-Ramasamy** [microsoftgraph/microsoft-graph-docs#3553]
I was able to add members to the MS Group using the **Graph API** and it is immediately reflecting under the MS Group. But in the SharePoint page under the Group Membership the added members are not getting updated. It is taking more than 1 hour. 

If we add members via SharePoint UI, it is reflecting immediately under MS Group and SharePoint Group Membership as well. **Adding members using Graph API is not reflecting immediately.**

![image](https://user-images.githubusercontent.com/18693389/49495676-cc80c800-f889-11e8-88d4-d16b01141cd5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@jasonjoh did you experience this with Contoso Airlines?

**Comment by Prakash-Ramasamy** [comment]
@jasonjoh I have tested with Beta end point. The members group is getting updated within less than 3 min of delay which can be acceptable. But we can't use it for production environment as it is not recommended.

**Comment by asoet** [comment]
@jasonjoh we are having difficulties with adding guests to a MS Teams Team. On both beta and 1.0 it takes several hours.

**Comment by miriamvoth** [comment]
@jthake-msft We also have delay of two hours before members added to a team via MS Graph have access to the team.

**Comment by yyuank** [comment]
Group members should show up on SharePoint and Teams fairly quickly, when members are added on MS Graph, as they get notifications directly from MS Graph. This sounds like a service reliability issue. Please file a support case if issues like this continue.
