### ISSUE TITLE
translateExchangeIds with MAPI Entry ID

### ISSUE THREAD

**Issue by mrfloppy82** [microsoftgraph/microsoft-graph-docs#3554]
Hello,

I have a problem using this call with an MAPI Entry ID. I got the following error:

```
{
  "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(microsoft.graph.convertIdResult)",
  "value": [
    {
      "sourceId": "AAAAALT9g2EaySBMpeaAIkKg+cYHALMy6/nXduZLi1s7Y9Wvrv4AAAAAAQwAALMy6/nXduZLi1s7Y9Wvrv4AA5OWcb0AAA==",
      "errorDetails": {
        "message": "Value cannot be null.\r\nParameter name: rawBytes",
        "code": "Value cannot be null.\r\nParameter name: rawBytes"
      }
    }
  ]
}
```

I use NewtonSoft.Json in C# to serialize my DTO. In my DTO the MAPI Entry ID is a byte-array. I could not find any further informations in the documentation about the MAPI Entry ID.

The conversation from EWS to REST works perfectly.

Regards

Nico

**Comment by jasonjoh** [comment]
@mrfloppy82 can I ask how you got your MAPI Entry ID?

What I tried here was I did a GET for a message using Graph, then using it's ID, I translated from `restId` format to `entryId`. I can translate that value back with no problem. If you do that for the message in question, how does the output from `restId`->`entryId` compare to the value you supplied above?

**Comment by jasonjoh** [comment]
Ah I think I see the problem. To verify, can you try this value for your ID?

```
AAAAALT9g2EaySBMpeaAIkKg+cYHALMy6/nXduZLi1s7Y9Wvrv4AAAAAAQwAALMy6/nXduZLi1s7Y9Wvrv4AA5OWcb0AAA0
```

**Comment by mrfloppy82** [comment]
Hello Jason,

thank you for response. The ID is from an outlook addin, It is in HEX-ENTRY-ID format.
00000000B4FD83611AC9204CA5E6802242A0F9C60700B332EBF9D776E64B8B5B3B63D5AFAEFE00000000010C0000B332EBF9D776E64B8B5B3B63D5AFAEFE0003939671BD0000

Now I have the solution. I decoded the HEX-ENTRY-ID to a byte array and encode it to base64. Then i get this ID:
 
AAAAALT9g2EaySBMpeaAIkKg+cYHALMy6/nXduZLi1s7Y9Wvrv4AAAAAAQwAALMy6/nXduZLi1s7Y9Wvrv4AA5OWcb0AAA==

It is like yours except the last characters. I must replace the "==" with "2" and in your ID the "0" with "2". Now a get a target id in my result.

Nico

**Comment by mrfloppy82** [comment]
Is the rule to encode the base64 padding the number of the padding characters?

**Comment by jasonjoh** [comment]
Thanks for trying. So it seems that the process is this.

1. Take your entry ID and add a `CR` to the end (hex: `0D`)
2. Encode as base64 **without padding** (that's the `=` signs on the end)

**Comment by jasonjoh** [comment]
> Is the rule to encode the base64 padding the number of the padding characters?

No, that's just a coincidence in your particular ID. You just drop the padding characters (which is legal in base64-land). The trick is adding the `CR` to the end of your data **before** encoding.

**Comment by mrfloppy82** [comment]
Hello Jason,

when i encode the id like you described, I got an InternalServerErrror.

"An internal server error occurred. The operation failed."

My id is Base64 encoded:
AAAAALT9g2EaySBMpeaAIkKg+cYHALMy6/nXduZLi1s7Y9Wvrv4AAAAAAQwAALMy6/nXduZLi1s7Y9Wvrv4AAeCUCvMAAA0

When I change the last character to "2" it works.

Nico

**Comment by jasonjoh** [comment]
@mrfloppy82 I chatted with the developer for this, and basically you're right :). Graph uses [HttpServerUtility.UrlTokenEncode](https://docs.microsoft.com/dotnet/api/system.web.httpserverutility.urltokenencode?view=netframework-4.7.2) to encode the binary MAPI entry ID, so that's what you should do as well.

If you're not using .NET, you can basically do the same thing by following these steps:

- Convert the binary to base64
- Replace `+` with `-` and `/` with `_`
- Replace all padding (`=`) characters
- Append an integer to the end of the string indicating how may padding characters were removed (can be 0)

Source for HttpServerUtility.UrlTokenEncode: https://referencesource.microsoft.com/#System.Web/Util/HttpEncoder.cs,0e3cb83cf51ca334
