### ISSUE TITLE
How can you get recurrence data of list item of type events?

### ISSUE THREAD

**Issue by sshresthareach** [microsoftgraph/microsoft-graph-docs#3558]
Is there a way to get recurrence information of sharepoint calendar events using the graph api? I can get the event fields using this endpoint but I could not figure out a way to get event recurrence data of sharepoint calendar.

If there's no way to do that, is there any documentation regarding working with sharepoint calendars? I could not really find any official documentation for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f44873-e61b-3f77-e2ad-b46112b065b2
* Version Independent ID: 3ef66bdc-06cf-4356-4e1e-f4d7bed17dcb
* Content: [Get an entry from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/listitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-get.md)
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by tkokk** [comment]
Same question. As a workaround I used CSOM.
