### ISSUE TITLE
Directory.AccessAsUser.All says Admin Consent Required "Yes" but Azure Portal says "No"

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/microsoft-graph-docs#3559]
Directory.AccessAsUser.All says Admin Consent Required "Yes" but Azure Portal says "No"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jnevins-gcm** [comment]
Any update on this?

**Comment by lqin-pki** [comment]
Any updates?

And I want to know what scope the site "https://graphexplorer.azurewebsites.net/" requests?

**Comment by rshimoda** [comment]
I would also appreciate if someone shares an update on this

**Comment by darrelmiller** [comment]
Graph Explorer says it does 
![image](https://user-images.githubusercontent.com/447694/104095163-510d5400-5263-11eb-87fd-b8e0b10d33e0.png)

And the azure portal now says it does,

![image](https://user-images.githubusercontent.com/447694/104095179-5f5b7000-5263-11eb-93b6-ea339f735d64.png)

So, it seems we are consistent everywhere.

Thanks for reporting this issues, closing it.
