### ISSUE TITLE
Customer has too many consumed units

### ISSUE THREAD

**Issue by rlisnoff** [microsoftgraph/microsoft-graph-docs#3560]
I'm running into a strange issue where a customer of ours has a subscription with 6 consumed units, yet when we view the prepaid units in the subscription there are only 5 total, in this case there are 5 enabled units. How is consumed units calculated? How can someone consume more units than what they have prepaid for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52263bf3-6bd2-2219-e2f0-dda921ea7e10
* Version Independent ID: b625c2db-d6a2-8a18-88dc-fad7e76f9251
* Content: [List subscribedSkus - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/subscribedsku-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscribedsku-list.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by junecastillote** [comment]
I see the same thing happening with my clients. In their case, the licenses were already assigned while they were still valid and then some units expired over time - but it does not mean that the previously assigned units get automatically UnAssigned.

**Comment by FaithOmbongi** [comment]
Hello @rlisnoff ,

Thank you for your query. 

Are you still experience this issue? If so, I recommend that you post this question at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored there.

No updates identified for the page. Closing this issue .
