### ISSUE TITLE
Microsoft Graph BETA API - App Role Assignment does not work for "Users"

### ISSUE THREAD

**Issue by mmushatt** [microsoftgraph/microsoft-graph-docs#3566]
Issue: In the App Role Assignments, the PATCH does not work for "Users".  We need to modify the documentation to remove any "User" reference until it is working.

Article: Update approleassignment - https://docs.microsoft.com/en-us/graph/api/approleassignment-update?view=graph-rest-beta

**Comment by dkershaw10** [comment]
Yes - assigning an app role actually should use a POST.  We'll need to fix the docs.

**Comment by psignoret** [comment]
Cleaning up outstanding issues. The current docs only refer to GET, POST and DELETE.
