### ISSUE TITLE
Question About Filter

### ISSUE THREAD

**Issue by Norrch2** [microsoftgraph/microsoft-graph-docs#3577]
Does the $filter support custom attributes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8f0b0d-c0f7-7774-d5fb-5df3c09dc83a
* Version Independent ID: f23af4a1-bf3c-2ef1-a94f-79be31ea6618
* Content: [user: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delta.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@madansr7 for Odata query params with $filter, do we support custom attributes through open schema extensions on resource objects? Our doc isn't that clear on this https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0#odata-query-parameters . We should up date this to be clearer.

**Comment by Norrch2** [comment]
@jthake-msft ,

Another question I would have is 
"Are delta requests" supported in the B2C environment? I am running a delta request and am getting an error message '
change enumeration is not supported in requested client'

I am unable to find any resources on this message.

**Comment by madansr7** [comment]
@Norrch2, are you referring to custom attributes or custom annotations? It would be great if you can post an example of the scenario you are trying to solve.

**Comment by Norrch2** [comment]
@madansr7 , 

Thank you for your response.

I am talking about custom attributes. 

The scenario I have is that I am trying to find a list of users based on a customer Boolean attribute. For example, I have a custom Boolean attribute that provides consent. I want to filter the results based on the custom attribute equal true. 


Also, does delta requests work with B2C environments?

**Comment by baywet** [comment]
@Norrch2 sorry for the late reply. As for the B2C support see the following comment https://github.com/microsoftgraph/microsoft-graph-docs/issues/4018#issuecomment-578844806
