### ISSUE TITLE
What's the domain for the token POST request?

### ISSUE THREAD

**Issue by AskYous** [microsoftgraph/microsoft-graph-docs#3584]
The [code](https://docs.microsoft.com/en-us/graph/auth-v2-service#token-request) just shows the URL starting with a `/`. Why was the beginning of the URL cut out? I don't know what it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service#token-request)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@Jackson-Woods  any chance you can take a look at the auth question?

**Comment by AskYous** [comment]
I found out the domain was `https://login.microsoftonline.com`. I hope it will be mentioned in the docs. I think that code block is the only one that has no domain.

**Comment by Jackson-Woods** [comment]
Thanks @AskYous for pointing this out. I'll submit a PR to fix.

**Comment by Jackson-Woods** [comment]
Resolved in PR #3590. Closing this issue.
