### ISSUE TITLE
Request Body

### ISSUE THREAD

**Issue by liampkemp** [microsoftgraph/microsoft-graph-docs#3588]
The article states
"In the request body, supply a JSON representation for the termsAndConditions object.
The following table shows the properties that are required when you create the termsAndConditions."
One of the included properties is ID. When I provide an ID as part of the request body, the termsAndConditions is created successfully, but it is created with a completely different ID

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04f1ec2a-fdaf-c9a4-a8d5-f2f065f21c09
* Version Independent ID: fa3c9c2c-5464-b93d-8db4-4f189485de17
* Content: [Create termsAndConditions - Microsoft Graph beta](https://docs.microsoft.com/en-au/graph/api/intune-companyterms-termsandconditions-create?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-companyterms-termsandconditions-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-companyterms-termsandconditions-create.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@lleonard-msft  could you take a look at this please?

**Comment by lleonard-msft** [comment]
@triplanedave - Any insights here?

**Comment by liampkemp** [comment]
Any update on this?
It's preventing the ability to have reliable automation as I cannot rely on a particular id for a policy

**Comment by Yomodo** [comment]
Omit id, createdDateTime and lastModifiedDateTime, these should be returned after creating the object.

**Comment by triplanedave** [comment]
Yomodo is correct.  Those are read only properties that are generated automatically on CREATE and cannot be included in the request body.
