### ISSUE TITLE
delta users query in graph explorer doesnt work

### ISSUE THREAD

**Issue by ashwineev** [microsoftgraph/microsoft-graph-docs#3608]
Issue: 
I am trying to use graph explorer
I have used this delta users api
https://graph.microsoft.com/v1.0/users/delta?$select=displayName,givenName,surname
v1.0
getting Failure - Status Code 400

Response
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. Could not find a property named 'id' on type 'Microsoft.Fast.Profile.Web.Models._1._0.Profile'.",
        "innerError": {
            "request-id": "5db435fa-d1fb-4c04-aee9-da84df9b1400",
            "date": "2018-12-12T10:17:45"
        }
    }
}

Article:

**Comment by Ady321** [comment]
for me the above query is working fine

**Comment by ashwineev** [comment]
Yes.I can still reproduce the issue on my system.
I deleted the cookies of chrome and tried again still the same issue.
I used Internet explorer,deleted the cookies and tried again but same issue.

I will check on some other system and let you know.

**Comment by ashwineev** [comment]
Hi !! I found the issue. I had created another tenant directory,that was causing the issue.I deleted the other tenant directory and tried again it works.Looks like delta query is having issue with multi tenants.

**Comment by ashwineev** [comment]
Yes.Done the same. but getting {
"isTrusted": true
} response.

**Comment by ashwineev** [comment]
Hi I have a single directory now but when I use the api https://graph.microsoft.com/v1.0/users/delta?$select=displayName,givenName,surname
v1.0 
I get below error
 ```
{
    "error": {
        "code": "",
        "message": "The query specified in the URI is not valid. Could not find a property named 'id' on type 'Microsoft.Fast.Profile.Web.Models._1._0.Profile'.",
        "innerError": {
            "request-id": "9bff24ad-9e2f-4318-b7de-6dfd1c396880",
            "date": "2018-12-18T03:59:45"
        }
    }
}
```

**Comment by jessieli-ad** [comment]
The same query is working for me. I wonder if you have anything special there.

**Comment by ashwineev** [comment]
Its working for tenant user now. I was using guest user which was global administrator.

**Comment by Ady321** [comment]
any idea about following query

when i m calling in microsoft graph explorer

https://graph.microsoft.com/v1.0/users/{userEmail}/drive/root/delta?$select=id

or

https://graph.microsoft.com/v1.0/users/{userEmail}/drive/root/delta?$token=latest

it throwing

"error": {
"code": "invalidRequest",
"message": "Call was made to the default drive, which is not supported for
apponly tokens.",
"innerError": {
"request-id": "18bfc97d-f38d-42f5-ba29-1b7ffe7d856a",
"date": "2018-12-13T10:33:59"
}
}

for some users above query works fine and for some users it is not working
how to resolve this issue if idea please let me know

**Comment by meetaligoel** [comment]
Are you able to execute the query without making it a delta request?
https://graph.microsoft.com/v1.0/users/{userEmail}/drive/root

I don't think it is a delta specific error. Please see this issue which appears similar -- https://github.com/OneDrive/onedrive-api-docs/issues/517

**Comment by Ady321** [comment]
Without Delta also not working

**Comment by Ady321** [comment]
you send me the issue link that i already seen and before 2 months it is
working fine for me and now it is not working

**Comment by meetaligoel** [comment]
https://graph.microsoft.com/v1.0/users/{userEmail}/drive/root not working was what was expected. This is not a delta request issue. Please change the title so it gets picked up by the graph team.

**Comment by Ady321** [comment]
Hey my title is Call was made to default drive #965 not Delta title that
title is by someone else

**Comment by meetaligoel** [comment]
Since this was not the original issue being discussed on this thread, please start a new issue and it will get picked up by the relevant team.
