### ISSUE TITLE
Team cloned via App Only permission it doesn't appear

### ISSUE THREAD

**Issue by giuleon** [microsoftgraph/microsoft-graph-docs#3610]
Hi,

I'm facing a strange issue, when I clone a team by consuming the relative Graph Api endpoint /teams/{id}/clone with app only permission, the latter is created but it doesn't appear in the list of my available Teams, also if I'm owner of it.
In the case of delegated permission it works fine.

Please could you clarify the App Only scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c78c38c-b49d-96d7-ff93-37b4f6bb8e6a
* Version Independent ID: 93752ea2-470d-0226-2928-439d71fe711b
* Content: [Clone a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/team-clone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-clone.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by giuleon** [comment]
Now is visible, I would say that is a really long running operation as described in the docs, is there some plan to optimize the timing?

**Comment by dander11** [comment]
I'm still having this issue with app-only permissions. Is there any way to remove this delay?
