### ISSUE TITLE
List Directory Audit Endpoint returning error 400, due to possibly untreated attribute value

### ISSUE THREAD

**Issue by Goethe0** [microsoftgraph/microsoft-graph-docs#3612]
API Doc: [List Directory Audits](https://docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta)

Endpoint: [https://graph.microsoft.com/beta/auditLogs/directoryAudits/](https://graph.microsoft.com/beta/auditLogs/directoryAudits/)

**Expected:** JSON Response, code 200.
![JSON Response, code 200](https://i.imgur.com/RZJQ5cc.png)

**Actual Response:**
![JSON Response with an error, code 400](https://i.imgur.com/oCZkrRX.png)

**Possible Cause:** The attribute category is returning a _null_ value, which is causing issues, since the attribute must always come populated.

**Workarounds:** None found so far, specially, since the usage of the _select_ filter, is unsupported by this endpoint.

**Comment by Cynothoglys** [comment]
Thank you for posting this - I am also experiencing this issue.

**Comment by SarahBar** [comment]
Thanks for taking the time to share this feedback. I recently took over audit logs in Azure AD and just came across this issue. I see that it's been sitting unresolved for quite some time. I was not able to replicate the issue, and it appears null values are being handled more elegantly now.

![image](https://user-images.githubusercontent.com/9774402/90455533-256ab100-e0ab-11ea-921e-1e32781000d7.png)
