### ISSUE TITLE
Application Permissions

### ISSUE THREAD

**Issue by icelandgrecian** [microsoftgraph/microsoft-graph-docs#3615]
According to this documentation it states that application permissions are not supported, but in the application registration in Azure I can see these listed under Application Permissions.... What are these application permissions for if it not for this API Endpoint?

Read and write class assignments with grades
Read class assignments with grades
Read and write class assignments without grades
Read class assignments without grades

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0726481c-ce0a-ac55-6dcc-8313c0ab6a19
* Version Independent ID: 7728ead8-bd3b-5e20-160b-05f05736f53e
* Content: [List assignments - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/educationclass-list-assignments.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@garethj-msft  could you assist here?

**Comment by icelandgrecian** [comment]
> 
> 
> @garethj-msft could you assist here?

Any update on this?

**Comment by lucyukuk** [comment]
@garethj-msft  I am also after this, are there any plans to do it?

**Comment by mwchambers** [comment]
> @garethj-msft could you assist here?

@jthake-msft This would also be useful to me. @garethj-msft hasn't provided any update on whether there's any chance of application permissions being added to the list assignments API.

Is there anyone else who may be able to offer some feedback?

**Comment by darryn-bryant** [comment]
Agree we need to be able to do this in bulk for all of our classes without having to add a user extract this information and then remove the user again.

**Comment by DongWangQi** [comment]
@garethj-msft , good day to you! Could you share some update for this feature? This is important for the Graph users. Cheers!

**Comment by ZoWeArdeb** [comment]
If i call this endpoint, with PHP i get a Bad Request: Resource not found for the segment 'assignments'.  Although i make use of the samen code to call teachers and members and those work just fine. I activated the right perms in portal.azure.com like defined in the instructions above.

**Comment by garethj-msft** [comment]
@dipakboyed owns the assignment APIs and can address the plan here.

**Comment by dipakboyed** [comment]
Thank you for the community feedback. As of March 2020, there are no known or publicized plans to support Application only Auth for the EDU assignments APIs.
We are constantly revisiting our priorities though. So please suggest this new feature request and upvote it under https://microsoftteams.uservoice.com/forums/599053-schools-and-universities
