### ISSUE TITLE
Not clear what "delete" means

### ISSUE THREAD

**Issue by gkirill** [microsoftgraph/microsoft-graph-docs#3617]
This needs more explanation what a "delete" means. Is the resource logically deleted or physically? Can this resource be restored? In general need a bit more information about the life cycle of the resource, and what it can do at each cycle. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523b3456-9ec1-f405-a9f6-cf1e15b5a0b7
* Version Independent ID: a534e0cf-9e6d-5d85-0915-8c817569a989
* Content: [Delete a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-delete?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delete.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@lleonard-msft  @dkershaw10 I think this is very fair feedback based on other questions I've had around the user object. Can we look at this?

**Comment by lleonard-msft** [comment]
@gkirill - You'll likely want to have a look at the [deletedItems](https://docs.microsoft.com/en-us/graph/api/resources/directory?view=graph-rest-1.0) APIs.  

In short, users and groups are soft-deleted for thirty days.  To do something with a soft-deleted user, [select the deleted user](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-get?view=graph-rest-1.0) and then call [restore](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0) or [delete permanently](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-delete?view=graph-rest-1.0) as desired.  (You'll need to have your [permissions and consents](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-permissions-and-consent) sorted out correctly.)

If you're having trouble getting things to work, consider posting a snippet of code and more details (including the specific error messages you're receiving) as a question on [StackOverflow](https://stackoverflow.com/search?q=%5Bmicrosoft-graph%5D+restore+user).  For best results, use the `[microsoft-graph]` keyword. 

We can certainly consider expanding the existing docs, but that idea will be coordinated with other outstanding requests, requirements, and priorities.  I've added an appropriate item to my internal backlog, but I can't make any promises as to when (or even if) it'll get worked on.  

Hope this helps...

**Comment by gkirill** [comment]
@lleonard-msft Thanks for the reply. Look, I have some questions but not sure if I should ask them on SO. E.g. when I create a user, I assume license is consumed. But when I disable a user (not deleting), is the license released or not? I assume it is released when user is soft deleted? What if I try to restore a soft deleted user but don't have any licenses left? In general it feel like the documentation has little info about dealing with licenses.

**Comment by lleonard-msft** [comment]
@gkirill - As I understand it, the license is supposed to be released when the user is initially (soft-)deleted.  I'm told it doesn't happen instantly and that you can check the status [using the Portal](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/license-users-groups#view-your-product-edition-and-license-details).

We've had similar feedback about licensing questions and there are active discussions about how best to handle them in the Microsoft Graph API for Azure AD docs.  (I'm afraid I don't have any specific details to share at this point, but it is an active conversation.)

(The [Microsoft Graph: Blog](https://developer.microsoft.com/en-us/graph/blogs/) is a good place to look for news about the platform, as well as new documentation sources and samples.  For example, here's [a post](https://developer.microsoft.com/en-us/graph/blogs/30daysmsgraph-day-17-use-case-assign-license/) that walks through various practical license scenarios.)

Have you seen the detailed documentation about [user](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-users-azure-active-directory) and [license](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/license-users-groups) management?  The Graph API for Azure AD documentation merely documents the REST API.  As a result, it's meant to supplement, not replace, the [detailed documentation](https://docs.microsoft.com/en-us/azure/active-directory/).

You might also be interested in [group-based licensing](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-licensing-whatis-azure-portal), recently introduced as a preview feature.

Detailed questions about licensing are best handled through formal support or your field partner resources.  (Certain services and capabilities depend on your region, your subscription, and other environmental factors.)

P.S.  StackOverflow has a [number of threads](https://stackoverflow.com/search?q=%5Bmicrosoft-graph%5D+user+delete) discussing user deletion and Microsoft Graph.

**Comment by lleonard-msft** [comment]
Forgot to add that we'll be updating the Delete user and Delete groups topic accordingly.  (Remember, only Office 365 groups support soft-delete).

**Comment by CelesteDG** [comment]
Fix was merged last year but this issue wasn't closed. Closing now.
