### ISSUE TITLE
 MS Graph: transitiveMembers API - When is the move from Beta to GA ?

### ISSUE THREAD

**Issue by Namusd** [microsoftgraph/microsoft-graph-docs#3622]
**### _List group transitive members : GET https://graph.microsoft.com/beta/groups/{id}/tranisitiveMembers_**

When will this transitiveMembers API move from Beta to GA ? Any ETA please ? 

Link : https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-beta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4ec3a3-ea32-43a0-86f9-d312f5642660
* Version Independent ID: 591556a3-d528-7f19-e03b-3bf5a67bce51
* Content: [List group transitive members - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list-transitivemembers.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by lleonard-msft** [comment]
@Namusd - Just to follow up, the v1.0 version of the docs are [now available](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0).

**Comment by Nothing4You** [comment]
Considering that the 1.0 docs are functionally the same as the beta right now, shouldn't this be closed?

**Comment by CelesteDG** [comment]
Reassigning to @davidmu1 for triage as this issue may already be resolved
