### ISSUE TITLE
Very recent Team does not have a resourceProvisioningOptions with Team as a value

### ISSUE THREAD

**Issue by Benjathing** [microsoftgraph/microsoft-graph-docs#3630]
Listing all teams in our organisation seems to pick up most of them; however there is a very recent team (created in the last month or so) that does not have any values in the `resourceProvisioningOptions` field.

However, it does have a `creationOptions` field with a "Team" value; and many of the other (but not all) teams picked up also have "Team" as a value for this field.

Can `creationOptions` also be used as an identifier of a Team?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75dbe68-e162-8861-d194-4a29de3bd731
* Version Independent ID: f58a6930-8575-8306-4273-fc413b979879
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams?toc=./ref/toc.json&view=graph-rest-1.0)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-list-all-teams.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by Benjathing** [comment]
On further investigation, only groups created 4th week of October have this property. More recently created groups have resourceProvisioningOptions with Team

**Comment by nkramer** [comment]
I would expect all new teams to have "Team" in their resourceProvisioningOptions. Most existing teams, too, although there's a few oddball cases out there involving teams created during certain windows of time that no one has used recently. (When a team is used, we write the resourceProvisioningOptions if it's not already there)
