### ISSUE TITLE
JSON format unsupported

### ISSUE THREAD

**Issue by mdb-wg** [microsoftgraph/microsoft-graph-docs#3637]
attempts to make request with ?format='application/json' returns an error:

request: https://graph.microsoft.com/v1.0/reports/getSkypeForBusinessActivityUserDetail(period='D7')?$format=application/json

error:
{
    "error": {
        "code": "",
        "message": "JSON format is not supported.",
        "innerError": {
            "request-id": "91211339-3804-4c79-81bb-694d1b2fccf6",
            "date": "2018-12-14T18:09:20"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98b0ac4a-8a08-2646-0ffe-025e6379f1d0
* Version Independent ID: b050485d-89be-bd0a-bd49-529a6d66335d
* Content: [reportRoot: getSkypeForBusinessActivityUserDetail - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-getskypeforbusinessactivityuserdetail?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/reportroot-getskypeforbusinessactivityuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-getskypeforbusinessactivityuserdetail.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by mdb-wg** [comment]
didn't realize that the application/json format was only available on the /beta/ endpoint, not the /v1.0/ endpoint.

**Comment by jthake-msft** [comment]
Unfortunately we don't have a time frame yet on when this will make it to v1.0.
