### ISSUE TITLE
Is there any json/xml file for the operations/path? Any TypeScript library?

### ISSUE THREAD

**Issue by chauey** [microsoftgraph/microsoft-graph-docs#364]
I saw this, but it does not have enough info to generate functions and paths? https://graph.microsoft.com/beta/$metadata

Is there any TypeScript library to make all the MSGraph calls? advice? plans? timelines? thx!

**Comment by dan-silver** [comment]
Hey @chauey!  We just published a [javascript library](https://github.com/microsoftgraph/msgraph-sdk-javascript) for making graph requests and [typescript definitions](https://github.com/microsoftgraph/msgraph-typescript-typings) for graph objects.  This is currently in preview and would love your feedback!

**Comment by chauey** [comment]
awesome! we'll have a look! thx!

**Comment by Lauragra** [comment]
It sounds like this issue is resolved so closing for now. Feel free to reopen if you have additional questions. Thanks.
