### ISSUE TITLE
Missing documentation for filter based query parameter support

### ISSUE THREAD

**Issue by shravyk12** [microsoftgraph/microsoft-graph-docs#3641]
I wanted to search for an 'O365 group' or a 'security group' whose displayName starts with a certain value. 

GET https://graph.microsoft.com/v1.0/groups?$filter=((groupTypes/any(c:c eq 'Unified') or (mailEnabled eq false and securityEnabled eq true)) and startswith(displayName, 'marketing')

This call failed with a 400 error stating this 'search filter expression has excessive height: 4. Max allowed: 3'. There  is no public documentation on MS Graph on how this error needs to be handled.

However, when I searched online, I found this AAD article which clarified the filter restriction.
https://blogs.msdn.microsoft.com/aadgraphteam/2014/02/10/support-for-disjunctiveor-filter-clauses-in-the-graph-directory-service/

So, as a workaround, I had to rephrase the query for now (to get unblocked) as:
https://graph.microsoft.com/v1.0/groups?$filter=(groupTypes/any(c:c eq 'Unified') and startswith(displayName, 'marketing')) or (mailEnabled eq false and securityEnabled eq true and startswith(displayName, 'marketing'))

It will be helpful to update the Graph documentation on filter query capabilities with more examples and error cases. It would also be helpful to fix this query limitation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#feedback)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by CelesteDG** [comment]
Reassigned to @davidmu1 for triage. This may already be documented.

**Comment by baywet** [comment]
@davidmu1 I'm not sure how I ended up owner of this page, this feels like something @mumbi-o  should own instead (PM for OData). David: can you update the header please?

**Comment by Arjen-1** [comment]
It would be nice if there was documentation on the heigth of a search query.
Can't find anything on **"search filter expression has excessive height: 4. Max allowed: 3'"**

**Comment by FaithOmbongi** [comment]
Currently keeping an eye on this.
Cc. @Licantrop0 for visibility.

**Comment by Licantrop0** [comment]
@shravyk12 / @Arjen-1 have you tried with the advanced Query Capabilities for Directory Objects?
See [here for an intro](https://developer.microsoft.com/en-us/identity/blogs/build-advanced-queries-with-count-filter-search-and-orderby/) and here for the [GA announcement](https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/)

Practically, try adding &$count=true querystring and ConsistencyLevel=eventual request header to overcome those limitations:
[Try here in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3D(groupTypes%2Fany(c%3Ac%20eq%20'Unified')%20or%20(mailEnabled%20eq%20false%20and%20securityEnabled%20eq%20true))%20and%20startswith(displayName%2C%20'marketing')%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d)
