### ISSUE TITLE
Issue with filter and bad request

### ISSUE THREAD

**Issue by AnirudhKrishan** [microsoftgraph/microsoft-graph-docs#3648]
Couple of issues I am facing : 
a) using loggedByService in $filter returns zero rows no matter what parameter value I pass (all valid values). Similar case with "initiatedBy/app/appDisplayName". Any sample example of filter based on anything other than date values?

b) Audit rest api without any filters randomly (on one of the pages) returns malformed json as last item in returned results 
{"id":"Sync_HM0PK_XXXXX"{
  "error": {
    "code": "BadRequest",
    "message": "The property 'category[Nullable=False]' of type 'Edm.String' has a null value, which is not allowed.",
    "innerError": {
      "request-id": "08732999-580d-4632-ab23-5a2d533078f1",
      "date": "2018-12-17T03:24:44"
    }
  }

c) similar to what we have in Azure AD portal for account provisioning logs, I am trying to build rest api url (using directory audit api) which will return account provisioning logs from one of the enterprise apps in azure ad with user's upn as input to filter the results. Tried many combinations but found the api limited for such advance but practical use cases. I am sure it must be possible to do so through the api but it will be good if the documentation can be updated for such use cases too. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9290469-4977-69e6-e793-795128559276
* Version Independent ID: 716e324d-c23c-5210-7727-c970f4b64837
* Content: [List directoryAudits - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/directoryaudit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/directoryaudit-list.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by lleonard-msft** [comment]
@dkershaw10 - Any insight?

**Comment by LogiO365** [comment]
for a), The following query works fine.
https://graph.microsoft.com/beta/auditLogs/directoryAudits?&$filter=loggedByService eq 'Invited Users'

Have you checked the user account you are using have permission to read audit logs?

**Comment by CelesteDG** [comment]
#reassign:@davidmu

**Comment by CelesteDG** [comment]
Reassigned to @dkershaw10 to help
CC @davidmu1

**Comment by cloudhandler** [comment]
I do not own this API, reassigning

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
