### ISSUE TITLE
Delta token ordering mode

### ISSUE THREAD

**Issue by psibernetic** [microsoftgraph/microsoft-graph-docs#3652]
The documentation on deltas do not list what order items are returned in. This would be useful knowledge to either treat it  as opaque and not rely on it, or understand if it is tree-ordered or flat,  ascending or descending. Alternatively, it may just be the order in which items had changes, but since I don't understand this I have no option than to handle each item one by one in my application or load all items into memory for manual sorting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by maitaowang** [comment]
这是什么 情况啊

**Comment by psibernetic** [comment]
Resolved by https://github.com/microsoftgraph/microsoft-graph-docs/pull/3690
