### ISSUE TITLE
Example for sending attached files

### ISSUE THREAD

**Issue by cpinto** [microsoftgraph/microsoft-graph-docs#3670]
Is it possible to add an example of how to use the sendMail API with file attachments? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by kostiamol** [comment]
@cpinto Have you found a solution?

**Comment by cpinto** [comment]
@kostiamol not a solution but a workaround: create a draft, add the attachments to the draft and then send the draft. The attachment(s) will be included.

**Comment by jasonjoh** [comment]
You don't have to do the draft thing if you don't want to. You can include attachments in the sendMail request.

```
POST /me/sendmail

{
  "message": {
    "subject": "Meet for lunch?",
    "body": {
      "contentType": "Text",
      "content": "The new cafeteria is open."
    },
    "toRecipients": [
      {
        "emailAddress": {
          "address": "meganb@m365x930361.onmicrosoft.com"
        }
      }
    ],
    "attachments": [
      {
        "@odata.type": "#microsoft.graph.fileAttachment",
        "name": "attachment.txt",
        "contentType": "text/plain",
        "contentBytes": "SGVsbG8gV29ybGQh"
      }
    ]
  }
}
```

**Comment by cpinto** [comment]
Sorry, you're correct @jasonjoh . The reason I used the draft is because I needed to save the messageID of the sent message in our database. Not related to the attachment.

**Comment by kostiamol** [comment]
@jasonjoh Works like a charm, thanks)

**Comment by gnome-leader** [comment]
I tried the attachments specifier from your example above.  I used the name, contentType and contentBytes pulled directly from another Message using GET https://graph.microsoft.com/v1.0/me/messages/{id}/attachments".  It sends the email, but does not include the attachment.  POST responds with a 202.  Sent email arrives with expected body, but no attachment.

Any ideas @jasonjoh ?

**Comment by jasonjoh** [comment]
@gnome-leader Only things that comes to mine: 1) Did you specify the `@odata.type`, and 2) there may be a size limit, how big is your attachment?

**Comment by gnome-leader** [comment]
I had the problem worked out by March 14th.  It may have been a format problem that wasn't obvious at the time.  I do not remember the specific fix.

**Comment by nishikant22** [comment]
I want to send the calendar invite in an mail?Can somebody please tell me how to do that?

**Comment by jinkoom** [comment]
Thanks Jason, The example you have provided works. However, I'm unable to use it when the attachment file changes from text to say pdf. The email is sent with the attachment alright but the attached file is corrupted because it doesn't open when you try to open. I suspect the reason is that I may not be supplying the right contentType. Is there a way to show the list of all supported content types as part of the documentation? My json payload is as shown below:

{
  "message": {
    "toRecipients": [
      {
        "emailAddress": {
          "address": "support@excenit.com"
        }
      }
    ],
    "attachments": [
      {
        "name": "Payslip.pdf",
        "contentBytes": "/9j/4AAQSkZJRgABAQEARwBHAAD/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAEAAAAAAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCABMAMQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKK+H/+Cq//AAVd8Rf8E9PiT4R0PRfB2i+JofEmmT38st7fS27QNHKqBQEVsg5zk0AfcFFfjx/xExeO/wDolPhL/wAHNx/8bo/4iYvHf/RKfCX/AIObj/43QB+w9Ffjx/xExeO/+iU+Ev8Awc3H/wAbo/4iYvHf/RKfCX/g5uP/AI3QB+w9Ffj/AKX/AMHJnxG13UYbOx+D/hy+vLltkNvbandTTTN/dVFiLMfYAmui/wCH9nx2/wCjb7r/AL8ap/8AI9AH6vUV+UP/AA/s+O3/AEbfdf8AfjVP/kej/h/Z8dv+jb7r/vxqn/yPQB+r1FflD/w/s+O3/Rt91/341T/5Ho/4f2fHb/o2+6/78ap/8j0Afq9RX5Q/8P7Pjt/0bfdf9+NU/wDkej/h/Z8dv+jb7r/vxqn/AMj0Afq9RX5Q/wDD+z47f9G33X/fjVP/AJHo/wCH9nx2/wCjb7r/AL8ap/8AI9AH6vUV+UP/AA/s+O3/AEbfdf8AfjVP/kej/h/Z8dv+jb7r/vxqn/yPQB+r1FflD/w/s+O3/Rt91/341T/5Ho/4f2fHb/o2+6/78ap/8j0Afq9RX5Q/8P7Pjt/0bfdf9+NU/wDkej/h/Z8dv+jb7r/vxqn/AMj0Afq9RX5G+Lv+DiP4veA9NF1rXwHsdGhkJWKTUZ7+0SVwC21WkgAJwM4HOK/Vr4eeJpPGvgDQ9ZlhW3k1bT7e9eJG3LGZI1cqD3AzjNAGxRRRQAV+Of8Awcvf8nA/C/8A7F68/wDSlK/Yyvxz/wCDl7/k4H4X/wDYvXn/AKUpQB+a9NkkWKNmZlVVGSScACnV95f8EAP2SfDf7RX7S/iLxV4otrTVLP4Y2lnd2Wm3Ch45r65kmEM7KeGWFbaQgEY8x426oKAPFfhD/wAErfjf8YPADeLl8LWvhHwikBujrXi3UItFtfJxnzdsv70RlSCJDGEIIIYjmuT+Pf7EXjz9nf4daF401RfDuu+BvE07Wul+JfDmrxappd5MN52LIuGyRFIQSu1tjYY4r7P/AG2f2hfCf7X/AO094nuPjb8RI/DXwH+FfiC60TS/AOi3RuNf8Y6hZSGKWaS3hO+FHlDqLmYxhI9qReW0klxXzd/wUN/4KT6p+25JonhnRdCt/Avwp8G7F0Dw3bhAymOMwxzTbMIrJESiRR/JErsAz53UAcz/AMExjj/goZ8Hf+xmt/5NX9IFfzf/APBMb/lIZ8Hf+xmt/wCTV/SBQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAfmf8A8HOR/wCMY/h3/wBjNN/6QXFfoL8CP+SH+Df+wFY/+k6V+fX/AAc5f8myfDr/ALGab/0hnr9BfgR/yQ/wb/2ArH/0nSgDq6KKKACvxz/4OXv+Tgfhf/2L15/6UpX7GV+Of/By9/ycD8L/APsXrz/0pSgD816/QH/gkP8AsGfG+LVofjRpPjOD4K+CksXd9Y1O1S5bXdP4kkItZSsf2UiMN58zLgBZIw6/NXzx/wAEyf2Z9P8A2t/23vBHg3W4ftHh1ppdU1iHGRc2trG0phb/AGJZBHE2OdsrY5xX2N/wcL/tq3i+JtM+Afhm4/s/Q9Ps4NS8TrbN5a3Tv81rYkDGI40VZmXkMZIOmwggHmP/AAUM/a4/ZQ+InjzxVdeD/hLc+PvGWs2c1tc+NU1a50LTZL5otgv4rWM7bh1k+dmaKNZSuQzqwc/BcbBl4YNjgkeo6165+zJ+zda/FPTtc8beM7u98P8Awj8C7ZPEWrwL/pF/McGLSbDOBJfXBZVHO2FX8xyBsWTg/ih8Qp/ir4+1LXp7Cw0hb1kS202xTba6XaxRrDb2sQwP3cMMccYY/MwTc2WYkgHq3/BMb/lIZ8Hf+xmt/wCTV/SBX83/APwTG/5SGfB3/sZrf+TV/SBQB8w6TcaZeavrzatD48vpo9VuUjbSGLQpGH4U5bhs549CK+ivCttby+C9NhjjuvsrWUSKl3/rtnlgASf7WOvvmuB0n4J+KvC91qX9j+ModPt9RvZb1ov7KSXDOfVmJ4AA4wOOlei2NtfWvh2GGS6iutSjt1R7l4tqSyhcFyikYBbnaCOuM0AeDeJtb1j4ca1qXw/sdUjkg1q4i+xXs9yTJp0Uxw8bEkkHp3Bwdw5cY918J+GoPB/h21023aaSO1QL5krl5JW6lmJ7k5PpzxgYFcNY/s42dx4M1qy1a8/tLWNclNxPqRh2skgJKFVycBcngHkMw4GAO18FaVqGheGbWz1S+XU7y2Xy2uhGYzMB0LAk/NjAJzyRnvigDy3wj4Wk/aG1jXdU1vUtSj0+xv5LGysLacxRwhADuYd2IYc9c7u2APSPh14OuvA2hNYXOsXmsoszNbyXI/eQxH7sZbPzY9T68ADAHM6r8F9V0fxRf6p4S8RNof8AareZd2ststxC0hyS67vukkk4weSeQMCul+HPgu48D6E9vd6tfa1dzzNPNcXLHG5uoRSTsXvtB6knvgAHjvxRuLWX4761DqS+Kbq0S2haOLRmJdG2JyRkAL1/EivVvgpFZx+BIvsEWuQ27TSEJq3/AB9A7sHPJ4449qxvEnwg165+I2oeIdF8Sw6PJqEMcDIdPW4IVVUYyzY5Kg8AV1/grStV0bRFh1nVF1i93sxuVtlt8qeg2rxx696APE9V8aax4F+N/irW7f7ReaPpd1bw6lbCQtiGZOHVTwCrJ1GOWA6MxHZfBXXV8QfFfx1cW9011ZTGzltzvLJtZHOVB6Z9OK6Lw58Ll0jxj4s1K6nhvbXxQIla1aHAjVEZWViSQwYN6D8ap/CD4KL8JNW1qSG++1WupGPyImi2vAqFyAzZO4/PjOB0z3oAo/EG6lj/AGiPAUSyyrFJHe70VyFfELYyOhx7113jvwJa/EHSorO7uL63jhmEwa0nMLkgMME+nzHj6VQ8S/DuTX/iZ4d8QLeJFHoSzq0Bi3GfzEK8Nn5cZz0Oa6mgDxX9mrwJBrUMmuXF9q0l3pepTW8SG7YwsoQAblPX75/Svaq5X4R/DmT4ZaBeWUl4l611eyXYdYvL2hgo24yem3r711VAH5n/APBzl/ybJ8Ov+xmm/wDSGev0F+BH/JD/AAb/ANgKx/8ASdK/Pr/g5y/5Nk+HX/YzTf8ApDPX6C/Aj/kh/g3/ALAVj/6TpQB1dFFFABX45/8ABy9/ycD8L/8AsXrz/wBKUr9jK/G//g5lvIbX9oP4WiSWOMnw9eEbmAz/AKSlAHzX/wAEmv2ndB/ZJ/bj8M+KPFM/2Pw3e21zouo3mwuLBLhRsmYDnYsscQY/wozN2r7O/wCCiXwQ/Y/+JHx71D40eLPjst5HrVtBJqHhjwhqlpql5rksECQQmExb3hR44o0YnamRnzYslq/Jn+1rX/n6t/8Av4KBqlmvS4tx/wBtBQB7h+19+2JN+0pLonh3w/oFr4B+FPglWh8LeEbFsxWech7u5f8A5b3ku5i8jE43sAWZ5ZJfF6r/ANrWv/P1b/8AfwUf2ta/8/Vv/wB/BQB75/wTG/5SGfB3/sZrf+TV/SBX8wv7J3x80r9nX9pfwP47vo21Kz8J6rHqM1rbTIs06qD8qliFB571+n//ABE9fD3/AKJr4s/8Gdn/APFUAfp3RX5if8RPXw9/6Jr4s/8ABnZ//FUf8RPXw9/6Jr4s/wDBnZ//ABVAH6d0V+Yn/ET18Pf+ia+LP/BnZ/8AxVH/ABE9fD3/AKJr4s/8Gdn/APFUAfp3RX5if8RPXw9/6Jr4s/8ABnZ//FUf8RPXw9/6Jr4s/wDBnZ//ABVAH6d0V+Yn/ET18Pf+ia+LP/BnZ/8AxVH/ABE9fD3/AKJr4s/8Gdn/APFUAfp3RX5if8RPXw9/6Jr4s/8ABnZ//FUf8RPXw9/6Jr4s/wDBnZ//ABVAH6d0V+Yn/ET18Pf+ia+LP/BnZ/8AxVH/ABE9fD3/AKJr4s/8Gdn/APFUAfp3RX5if8RPXw9/6Jr4s/8ABnZ//FUf8RPXw9/6Jr4s/wDBnZ//ABVAFv8A4Ocv+TZPh1/2M03/AKQz1+gvwI/5If4N/wCwFY/+k6V+In/BWT/grn4U/wCChvwf8OaBo3hnVvDc/h3VJNTkmv723lSZDbSRbVEbE5y4PPGBX7dfAc7vgb4MI/6AVj/6TpQB1lFFFABWV4g8C6J4snjk1XR9K1OSFSsb3dpHMyA8kAsDgfStWigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTPg/wD6FTw3/wCCyD/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDm/8AhTXg/wD6FTw3/wCCyH/4mj/hTXg//oVPDf8A4LIf/ia6SigDmj8GfB7Dnwn4a/8ABZB/8TXRwwpbQrHGqxxxgKqqMKoHQAU6igAooooA/9k\u003d",
        "@odata.type": "#microsoft.graph.fileAttachment",
        "contentType": "application/pdf"
      }
    ],
    "subject": "Testing Brokersure Emails",
    "bccRecipients": [
      {
        "emailAddress": {
          "address": "jbinkoom@outlook.com"
        }
      }
    ],
    "body": {
      "contentType": "HTML",
      "content": "Just Testing Brokersure Emails using Microsoft Graph API"
    }
  }
}

**Comment by JuanSaulR** [comment]
i really need help, im trying to send email with attachments but when i sent it the attachments dont appear. this is my json that i post.

{
   "message":{
      "subject":"[AU1588259832480]-etstest",
      "body":{
         "contentType":"HTML",
         "content":"<p>dasddad</p>"
      },
      "toRecipients":[
         {
            "emailAddress":{
               "address":"myEmailtest"
            }
         }
      ],
      "internetMessageId":"AU1588259832480",
      "attachments":[
         {
            "@odata.type":"#microsoft.graph.fileAttachment",
            "contentBytes":"/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQ....",
            "contentType":"image/jpeg",
            "name":"image1.jpg"
         }
      ]
   }
}

**Comment by JuanSaulR** [comment]
can you help me @jasonjoh?
