### ISSUE TITLE
Response Status code for updating a file is incorrect

### ISSUE THREAD

**Issue by kumar-anubhav** [microsoftgraph/microsoft-graph-docs#3673]
The response status code for updating an existing file's content is mentioned as 201 created in the documentation which should actually be 200 success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e09393d2-d54e-6257-94d3-8baa5a58f343
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-beta#example-updating-an-existing-file)
* Content Source: [api-reference/beta/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-put-content.md)
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by Lauragra** [comment]
Thanks. This will be fixed per PR #5196
