### ISSUE TITLE
Use of term "chatMessages"

### ISSUE THREAD

**Issue by DeanGross** [microsoftgraph/microsoft-graph-docs#3675]
When I create a Channel in the UI, it contains Conversations, tabs, and apps. The description above refers to "chatmessages" I assume that these are the same as the Conversations shown in the UI, is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28943613-194a-6a5e-8245-57110fdeded6
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/channel.md)
* GitHub Login: @nkramer
* Microsoft Alias: **jthake-msft**

**Comment by nkramer** [comment]
Yes, chat messages are displayed under the conversations tab.
