### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by DeanGross** [microsoftgraph/microsoft-graph-docs#3676]
What permissions are needed for these methods?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f046b37e-8569-b617-4c9b-402342d4bef9
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessage.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
If you click on the Get Channel messages link in the operations related to this resource object, you'll see a permissions table there. Permissions are based on the operation you are running. https://docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta

**Comment by DeanGross** [comment]
Thanks, not sure what happened but I meant to request that this page https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta get the Permission section added to it.
