### ISSUE TITLE
What About Teams

### ISSUE THREAD

**Issue by DeanGross** [microsoftgraph/microsoft-graph-docs#3677]
Where are the permissions for the Microsoft Teams application? please add them

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#user-permissions)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **jthake-msft**

**Comment by Jackson-Woods** [comment]
To clarify, we have permissions for Teams APIs on the appropriate API reference pages, but there isn't a dedicated section for Teams permissions on this doc: [https://docs.microsoft.com/en-us/graph/permissions-reference#calls-permissions](https://docs.microsoft.com/en-us/graph/permissions-reference#calls-permissions). I'll follow up on this.

**Comment by Jackson-Woods** [comment]
@DeanGross Teams uses the Groups permissions rather than Teams-specific permissions. I've added a note to that effect on the Permissions page. 

Closing issue, addressed by #3801.
