### ISSUE TITLE
[beta] When a message is deleted in a MS Teams Channel Chat, there is an indication that the message was deleted within the Outlook Mailbox via the Graph Beta API

### ISSUE THREAD

**Issue by samsmithnz** [microsoftgraph/microsoft-graph-docs#3681]
When a message is deleted in a MS Teams Channel Chat, there is an indication that the message was deleted within the Outlook Mailbox via the Graph Beta API, but there is no deleted message content or a delete date/time. 

This is a challenge for investigators as they cannot see the content of a deleted message or when that delete occurs. We request Microsoft add the delete content and delete date/timestamp.

**Comment by nkramer** [comment]
Handled off-line
