### ISSUE TITLE
[beta] When a message is deleted in a MS Teams 1:1/1:N Chat, there is no indication that the message was deleted or a delete date/time

### ISSUE THREAD

**Issue by samsmithnz** [microsoftgraph/microsoft-graph-docs#3682]
When a message is deleted in a MS Teams 1:1/1:N Chat, the content is displayed within the Outlook mailbox (we are currently using the Outlook API to pull this data, but would prefer this be added to MS Graph API), but there is no indication that the message was deleted or a delete date/time. 

This is a challenge for investigators as they have no indication of when a user is trying to delete/hide their messages. We request Microsoft add some indication of a deleted message.

**Comment by nkramer** [comment]
Handled off-line
