### ISSUE TITLE
[beta] When a message is edited in a MS Teams Channel Chat, there is a modified date (that appears to be wrong), but no method to capture the content of the previous message versions via the Graph Beta API

### ISSUE THREAD

**Issue by samsmithnz** [microsoftgraph/microsoft-graph-docs#3683]
When a message is edited in a MS Teams Channel Chat, there is a modified date (that appears to be wrong) but no method to capture the content of the previous message versions via the Graph Beta API. This is a challenge for investigators as they cannot see the content of an edited message. We request Microsoft add the previous versions of edited content

**Comment by nkramer** [comment]
Fixed
