### ISSUE TITLE
Filtering results

### ISSUE THREAD

**Issue by grnadav** [microsoftgraph/microsoft-graph-docs#3692]
Is there a way to filter the results? (e.g. by activityDateTime), 
to set order? (e.g.  activityDateTime desc.) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f606b6d-2475-1f99-1111-42a20972bf1d
* Version Independent ID: 351b1de3-a3aa-f18c-3cf3-6aefc6200931
* Content: [List auditEvents - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-auditing-auditevent-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-auditing-auditevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-auditing-auditevent-list.md)
* GitHub Login: @tfitzmac
* Microsoft Alias: **jthake-msft**

**Comment by triplanedave** [comment]
Yes, please see: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/webservices/use-filter-expressions-in-odata-uris 
and
https://docs.microsoft.com/en-us/graph/query-parameters?context=graph/api/1.0
