### ISSUE TITLE
Unhelpful JSON example on the Add tab to channel page

### ISSUE THREAD

**Issue by jhoneill** [microsoftgraph/microsoft-graph-docs#3693]
It would be helpful to show the JSON for the different tab types either on the _add-tab_ page or the _configuring the built in tab_s page . On the Add tab page the example has 
```
{
  "name": "My Contoso Tab",
  "teamsApp@odata.bind" : "https://graph.microsoft.com/beta/appCatalogs/teamsApps/06805b9e-77e3-4b93-ac81-525eb87513b8",
  "configuration": {
```
but for example adding a planner tab needs the middle line to be 
`"TeamsAppId" : "com.microsoft.teamspace.tab.planner",`
The documentation for the planner tab gives the second half but the it took a lot of searching to find that it needed to be TeamsAppID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0778483f-34bc-b383-abfa-99c8d97429e2
* Version Independent ID: 6882946c-c210-29ec-e776-caf8af03c716
* Content: [Add tab to channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamstab-add.md)
* GitHub Login: @nkramer
* Microsoft Alias: **jthake-msft**

**Comment by advdberg** [comment]
Also the 'configuring the built in tabs' page now only describes the **1.0** possibilities while in **beta** there are several additional options available, i.e. configuring the SharePoint library, list and page tab. When adding the samples to the add tab to channel page makes it possible to describe these additional options separate from the 1.0 version.

**Comment by mrik23** [comment]
Obviously they can't detail all different apps that could be added, but there should be an example on how to build the JSON payload (where to get the IDs...).

**Comment by kiwifellows** [comment]
At least some examples would be handy...

**Comment by v-chetsh** [comment]
Oops... looks like Graph API page link is not available now.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
