### ISSUE TITLE
relativeYearly is mentioned as relativeMontly

### ISSUE THREAD

**Issue by GopalChavan** [microsoftgraph/microsoft-graph-docs#3700]
https://docs.microsoft.com/en-us/graph/outlook-schedule-recurring-events#relevant-properties-5
this is the link, where last property (i,e. 'type') is mentioned wrongly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cce09996-035a-db45-8c6a-db62ca814ae6
* Version Independent ID: d5869573-4333-0b94-f114-42c24ba3c1da
* Content: [Schedule repeating appointments as recurring events in Outlook - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-schedule-recurring-events#relevant-properties-5)
* Content Source: [concepts/outlook-schedule-recurring-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-schedule-recurring-events.md)
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **jthake-msft**

**Comment by Jackson-Woods** [comment]
@angelgolfer-ms is this a simple typo in the properties table?

**Comment by angelgolfer-ms** [comment]
Thanks for pointing that out, @GopalChavan and @Jackson-Woods. It's a typo. I just fixed it in PR #3767 . You should be able to see the fix the next time the docs are refreshed on the live site, probably later on 1/14.
