### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by HN5** [microsoftgraph/microsoft-graph-docs#3702]
Hi,

when i try to list channel messages i get :
[...] "code": "UnknownError",
 "message": "Failed to execute backend request." [...]

This error is for all Teams i don't belong.
Is it a bug because "beta" or something i'v missed ?

I have this error when trying to call api from Flow (HTTP GET) but also with Graph Explorer (account with FULL permission but asking to check my permission :

Failure - Status Code 403, 656ms Looks like you may not have the permissions for this call. Please modify your permissions

Thx for help :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
This repo is actually for documentation issues. not bugs/issues/troubleshooting your code. You should use StackOverflow.com for this with microsoft-graph tag.

If you are doing this with delegated user permissions and the user is not part of the Team, then you will get back this error message as it is intended.

**Comment by HN5** [comment]
Thx, sorry for miss used this repo, if anyone faced this issue i opened a question on StackOverflow : https://stackoverflow.com/questions/54004221/unable-to-list-channel-messages-on-azure-ad-graph-api-beta

does this mean that there is no possibility to list channel message for governance like there is possible to list all teams even if we are not member of all of them ?
