### ISSUE TITLE
displayName property of outlookCategory resource should not be read-only

### ISSUE THREAD

**Issue by Booligoosh** [microsoftgraph/microsoft-graph-docs#3705]
Hi there. I'm building an email client that relies heavily on Outlook categories / Gmail labels (equivalent). I can update a label's name using the Gmail API, see below:
https://developers.google.com/gmail/api/v1/reference/users/labels/update
However, I can't update it for Outlook because it is read-only. What is the reason behind this, and is there any way to make it writeable? If not, I may have to consider pulling Microsoft Outlook support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8e6fe2-81cf-ab4f-75e9-4e879eb1fadd
* Version Independent ID: f26b9174-bd57-79b3-5093-3fbc72432ca7
* Content: [outlookCategory resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/outlookcategory?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/outlookcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/outlookcategory.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
Are you trying to update a category that you created, or update one of the preset categories?

**Comment by Booligoosh** [comment]
Would it be possible to update the ID then to achieve a similar effect?

**Comment by svpsiva** [comment]
You will have to set the new category name on all emails in the old category. Hope this helps.
