### ISSUE TITLE
allowExternalSenders on Unified Group not updating

### ISSUE THREAD

**Issue by callmeradical** [microsoftgraph/microsoft-graph-docs#371]
When creating a group with mailEnabled == True, and GroupType == Unified, you are able to create a PATCH request to allowExternalSenders = true, response comes back as 204, but fails to update the allowExternalSenders property.

**Comment by artokai** [comment]
Any updates on this one? I'm also experiencing this issue. I can update the `autoSubscribeNewMembers`  property using a PATCH request but changing `allowExternalSenders` to true does not seem to work.

**Comment by tomvr2610** [comment]
I'm facing the same issue. I can update other properties like description but the allowExternalSenders is not updating, but doesn't return an error.

**Comment by marych** [comment]
The allowExternalSenders property is not currently settable via the API. I created https://github.com/microsoftgraph/microsoft-graph-docs/pull/778 to update the documentation accordingly.

**Comment by Lauragra** [comment]
It looks like this issue is resolved so closing for now. Feel free to reopen if you have additional questions or feedback. Thanks.
