### ISSUE TITLE
I Get "Specified resource is not supported for MSA requests"

### ISSUE THREAD

**Issue by urjitgokhale** [microsoftgraph/microsoft-graph-docs#3711]
I am trying to create subscription for 'messages' resource with v1.0 endpoint for personal microsoft account. But I get "Specified resource is not supported for MSA requests" error. 
However beta endpoint works fine.
Could you explain what could be the reason for that?

I did refer to the same issue that was reported back Feb 2018 (https://github.com/microsoftgraph/microsoft-graph-docs/issues/2233) and the suggestion was to use beta endpoint as, back then, subscriptions were not supported for personal accounts. 

But now, the documentation at https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0 lists message as a supported resource for personal accounts. 
Still it doesn't seem to work.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/webhooks.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@piotrci any guidance here?

**Comment by tapan-patel-simpro** [comment]
Hi There,

I get the same error when I try to create the subscription using V1.0 and the documentation says that it supports the events and other stuff for personal accounts.

https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0

Can you please investigate this as soon as possible?

Thanks

**Comment by jthake-msft** [comment]
As PMs aren't jumping on this. Can you please escalate this via a support ticket. If you go into your Office 365 admin center, and support on left hand side. You can raise a support request.  This will get straight to engineering then.

This repo is not meant to troubleshoot issues. Rather to handle documentation issues.

**Comment by tapan-patel-simpro** [comment]
I am a developer so I do not have office 365 admin account. This is the documentation issue as the document says that it supports the "event" resource type (subscription) for personal accounts. so I am just wondering what is right here? document or codebase? Can you please raise the support ticket on behalf of me?

**Comment by jthake-msft** [comment]
I followed up internally and there are other support tickets out for this. It is a known issue that has been corrected as is currently rolling out. It *should* be across all tenants by Jan 10th. The documentation is correct.

**Comment by svpsiva** [comment]
@tapan-patel-simpro This is now fixed and should work for MSA accounts. Do confirm.

**Comment by tapan-patel-simpro** [comment]
@svpsiva Yes this is working now. Thanks for fixing it
