### ISSUE TITLE
Get Assignment - Submission Object

### ISSUE THREAD

**Issue by icelandgrecian** [microsoftgraph/microsoft-graph-docs#3713]
In the return model on this API call there is a submission object on the returned model, however it always appears to be null/empty. If we call the submissions endpoint for the assignment it returns the submissions as we would expect, but should this be available in this endpoint as well rather than having to make the separate submissions call?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5cd0e3c-c242-9526-b9a6-b3548e594644
* Version Independent ID: f902c6a8-ca69-181d-e231-44217e8de584
* Content: [Get educationAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/educationassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/educationassignment-get.md)
* GitHub Login: @dipakboyed
* Microsoft Alias: **jthake-msft**

**Comment by dipakboyed** [comment]
**submissions** is a navigation property in the **educationAssignment** entity.
Reference: https://graph.microsoft.com/beta/$metadata

So you need to use $expand to inline include the submissions object details.
e.g. add the query param $expand=submissions to your GET assignments api query.
