### ISSUE TITLE
ETA on creating messages? 

### ISSUE THREAD

**Issue by jmcadams-r7** [microsoftgraph/microsoft-graph-docs#3722]
Just wondering if there was an ETA on creating messages yet. There's a lot of bot integrations with the other tools on the market that are immensely helpful (Jenkins, Jira, etc..)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28943613-194a-6a5e-8245-57110fdeded6
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/channel.md)
* GitHub Login: @nkramer
* Microsoft Alias: **jthake-msft**

**Comment by nkramer** [comment]
We have an API for that today in beta.
