### ISSUE TITLE
Links all link to the same reference despite different names

### ISSUE THREAD

**Issue by CorbynG98** [microsoftgraph/microsoft-graph-docs#3729]
All the links in this section (Create, Delete, List and Update) all link to the "List Programs" API Reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f014c940-e57d-7d29-8a8d-f26173eda292
* Version Independent ID: dfbaafc2-bd00-5bc7-d8dd-bfc0be3810b1
* Content: [List programs - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/program-list?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/program-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/program-list.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@lleonard-msft can you take a look at this one please? Thanks.

**Comment by lleonard-msft** [comment]
@CorbynG98 - Thanks for the catch.

When PR #3905 is merged, it should resolve this issue.  (Sorry about that.)

**Comment by lleonard-msft** [comment]
@CorbynG98 - I see that PR #3905 has been merged.  This issues appears to be fixed.  Can we close?

**Comment by CorbynG98** [comment]
Issue appears to be resolved this may be closed, cheers for that.
