### ISSUE TITLE
Small typo in Example Request

### ISSUE THREAD

**Issue by dennisameling** [microsoftgraph/microsoft-graph-docs#3732]
There is a small typo in the Example Request.

"upn-value@tenant-value@onmicrosoft.com"

Should be

"upn-value@tenant-value.onmicrosoft.com"

... just like in the Example Response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 557de097-e035-bfee-1c1a-fcd9a1713fd8
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-post-users.md)
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by Jackson-Woods** [comment]
Hi @dennisameling, thanks for pointing this out. I've submitted a PR to fix and will close the issue when it's accepted.

**Comment by Jackson-Woods** [comment]
Resolved in #3763. Closing issue.
