### ISSUE TITLE
500 error when creating a subscription

### ISSUE THREAD

**Issue by tapan-patel-simpro** [microsoftgraph/microsoft-graph-docs#3754]
Issue: 
When I create a subscription using v1.0 , personal accounts app. I get the following error. However it works for beta

{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Create; Exception: [There was no raw user ticket in the requestPropertyMappings]",
        "innerError": {
            "request-id": "20924650-d047-4de4-ae9f-6305e0a79672",
            "date": "2019-01-10T23:16:00"
        }
    }
}

Article:

**Comment by dkershaw10** [comment]
@tapan-patel-simpro Not sure that this is a documentation issue.  If this is a coding or service issue, please file a question on StackOverflow and tag with [microsoft-graph].

**Comment by tapan-patel-simpro** [comment]
Ok I have created a question here.

https://stackoverflow.com/questions/54189641/500-error-when-creating-a-subscription-using-v1-0-microsoft-graph-api

Please let me know when is this going to be resolved?

**Comment by piotrci** [comment]
Closing since not a doc issue.
