### ISSUE TITLE
Is contentLocation URI or URL?

### ISSUE THREAD

**Issue by ag-theone** [microsoftgraph/microsoft-graph-docs#3786]
Is contentLocation a URI or a URL? Are locations fixed? Is Location a resource that is identified by a URI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e11bf3-1c47-a258-da9b-37cf0ee5cb37
* Version Independent ID: 85b45ad2-c35a-82e8-d77a-47dadfa70e4a
* Content: [fileAttachment resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/fileattachment?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/fileattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/fileattachment.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by jthake-msft** [comment]
@angelgolfer-ms  could we add some clarity to this based on the questions by @ag-theone . Thank you.

**Comment by angelgolfer-ms** [comment]
@svpsiva , can you please confirm if it's more appropriate to describe contentLocation as a URL (i.e., contentLocation should always identify the location and hence it's a URL and would never be a URN).

**Comment by svpsiva** [comment]
contentLocation property is unused. Please ignore. 
We will remove references to the same shortly.

**Comment by angelgolfer-ms** [comment]
FYI I clarified in the fileAttachment resource type documentation for developers to not use contentLocation. PR #3861  will be merged to publish later today. 
I can remove the property from the docs when the metadata and API no longer return the property.
