### ISSUE TITLE
Extended Properties

### ISSUE THREAD

**Issue by Misiu** [microsoftgraph/microsoft-graph-docs#3792]
With EWS we were able to set extended properties, for example using this code:
```
var email = new EmailMessage(ExchangeService);
var messageGuidPropertySetId = new Guid("{120AF1EB-0548-4128-BAF1-B32603DAA3AE}");
var messageGuidExtendedPropertyDefinition = new ExtendedPropertyDefinition(messageGuidPropertySetId, "MessageGuid", MapiPropertyType.String);
var messageGuid = Guid.NewGuid().ToString("N");
email.SetExtendedProperty(messageGuidExtendedPropertyDefinition, messageGuid);
email.SendAndSaveCopy();
```
how can we do this using Graph?
Also, why send mail and create mail have different responses? Currently, there isn't a way to get mail id when using send mail method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by jasonjoh** [comment]
See https://docs.microsoft.com/graph/api/singlevaluelegacyextendedproperty-post-singlevalueextendedproperties?view=graph-rest-1.0. Also see my response in #3766 for an example of doing this.
