### ISSUE TITLE
Daemon Access Denied

### ISSUE THREAD

**Issue by asoet** [microsoftgraph/microsoft-graph-docs#3796]
I'm using the client credentials flow. If this is by design it should be in the document.
When I try and create a thread I get the Access Denied:
```json
{
    "error": {
        "code": "AccessDenied",
        "message": "Failed to execute Aad backend request GetUserLicensesRequest. Request Url: https://graph.windows.net/----/users/----/licenseDetails?api-version=1.6, Request Method: GET, Response Status Code: Unauthorized, Response Headers: ocp-aad-diagnostics-server-name: ---\r\nrequest-id: ---\r\nclient-request-id: ---\r\nStrict-Transport-Security: max-age=31536000; includeSubDomains\r\nDate: ---\r\nServer: Microsoft-IIS/10.0\r\nX-AspNet-Version: 4.0.30319\r\n",
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9704160-8b7d-166c-af96-4d8a938a28fd
* Version Independent ID: 3ac38651-1d94-54f4-41aa-2d8fc16e438c
* Content: [Create chat thread - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-chatthreads?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/channel-post-chatthreads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-chatthreads.md)
* Product: **microsoft-teams**
* GitHub Login: @nkramer
* Microsoft Alias: **jthake-msft**

**Comment by nkramer** [comment]
Thanks for the feedback. The page already says that application permissions are not supported – is there something else it should say?

**Comment by asoet** [comment]
Yes you are correct. I'm sorry I overlooked that
