### ISSUE TITLE
API availability in production?

### ISSUE THREAD

**Issue by ghost** [microsoftgraph/microsoft-graph-docs#3798]
Just out of curiosity, what is the time frame of this API being published and made available for production use? 1 month, 3 months, or longer? Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f046b37e-8569-b617-4c9b-402342d4bef9
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessage.md)
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by ArchieCoder** [comment]
@Messer262a FYI create message is in beta https://docs.microsoft.com/en-us/graph/api/channel-post-chatmessage?view=graph-rest-beta

**Comment by macie-korte** [comment]
Is there any word on when this MS Graph chat resource will be out of beta?
We need to write code to fetch Team chat messages, but:

- The old libraries are deprecated
- The new MS Graph APIs are in beta for a very long time and "not supported in production"

That leaves outside developers in a tough spot when there's no correct/supported way to get this information.

**Comment by chauhanPankaj007** [comment]
When we can expect these API's available for use? As we are waiting for a long time to move ahead from beta.

**Comment by cbremer13** [comment]
Would also like to know when these will be out of beta

**Comment by ashoksubedi1** [comment]
Same here, would like to know when this api will be available in v1. Also Can we delete chat message in Teams using graph api. Is that api will be added soon ?

**Comment by ajtrichards** [comment]
I'm also interested to find out when this is coming out of Beta. Some of the functionality like sending a message to a channel being in beta did surprise me a little.

**Comment by ashoksubedi1** [comment]
@ChrisDXC @ajtrichards  it went into production today. Unfortunately there is no endpoint to delete or update the chat messages yet.

**Comment by FaithOmbongi** [comment]
Selected APIs are now in v1.0.
No updates identified for the page. Closing the issue.
