### ISSUE TITLE
recurrenceEndType never vs Never

### ISSUE THREAD

**Issue by michaelrhyndress** [microsoftgraph/microsoft-graph-docs#3808]
The documentation uses capitalized 'Never', however the api only accepts lowercase 'never' when setting recurrenceEndType in accessReviewRecurrenceSettings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a281916f-c380-e08d-b8e2-9ff8f37c2b48
* Version Independent ID: 8cfa2d8c-2f74-154a-714f-a9c4165a745b
* Content: [accessReview resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/accessreview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/accessreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/accessreview.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **jthake-msft**

**Comment by markwahl-msft** [comment]
The documentation has been updated to match the lower case string.
