### ISSUE TITLE
Problems When reading certain entity attributes from graph

### ISSUE THREAD

**Issue by sokobanjafox** [microsoftgraph/microsoft-graph-docs#381]
This is example of one request that I make, for example for User entity:

https://graph.microsoft.com/beta/users?$select=aboutMe

It fails. There are numerous properties from this, and other entities that make me problems. It's sure that I don't want to fetch entire entities, so I always just select properties I need. Reponse that I get here is usually "Internal Server Error". Here, I provide full list of properties for: User, Contact, and Person, and my test (which of those props work with $select request). Please take a look:

CONTACTS - LIST FROM GITHUB, EVERY PROP MANUALLY CHECKED IN REQUEST

{
  "assistantName": "string", OK
  "birthday": "String (timestamp)",OK
  "businessAddress": {"@odata.type": "microsoft.graph.physicalAddress"}, NOT OK
  "businessHomePage": "string", NOT OK
  "businessPhones": ["string"],NOT OK
  "categories": ["string"],OK
  "changeKey": "string",OK
  "children": ["string"],OK
  "companyName": "string",OK
  "createdDateTime": "String (timestamp)",OK
  "department": "string",OK
  "displayName": "string",OK
  "emailAddresses": [{"@odata.type": "microsoft.graph.emailAddress"}],OK
  "fileAs": "string",OK
  "generation": "string",OK
  "givenName": "string",OK
  "homeAddress": {"@odata.type": "microsoft.graph.physicalAddress"}, NOT OK
  "homePhones": ["string"], NOT OK
  "id": "string (identifier)",OK
  "imAddresses": ["string"],OK
  "initials": "string",OK
  "jobTitle": "string",OK
  "lastModifiedDateTime": "String (timestamp)",OK
  "manager": "string",OK
  "middleName": "string",OK
  "mobilePhone1": "string",NOT OK
  "nickName": "string",OK
  "officeLocation": "string",OK
  "otherAddress": {"@odata.type": "microsoft.graph.physicalAddress"},NOT OK
  "parentFolderId": "string",OK
  "personalNotes": "string",OK
  "profession": "string",OK
  "spouseName": "string",OK
  "surname": "string",OK
  "title": "string",OK
  "yomiCompanyName": "string",OK
  "yomiGivenName": "string",OK
  "yomiSurname": "string",OK
}

USERS - LIST FROM GITHUB, EVERY PROP MANUALLY CHECKED IN REQUEST

{
  "aboutMe": "string", NOT OK
  "accountEnabled": true, OK
  "assignedLicenses": [{"@odata.type": "microsoft.graph.assignedLicense"}], OK
  "assignedPlans": [{"@odata.type": "microsoft.graph.assignedPlan"}], OK
  "birthday": "String (timestamp)", NOT OK
  "businessPhones": ["string"],OK
  "city": "string",OK
  "companyName": "string",OK
  "country": "string",OK
  "department": "string",OK
  "displayName": "string",OK
  "givenName": "string",OK
  "hireDate": "String (timestamp)", NOT OK
  "id": "string (identifier)",OK
  "interests": ["string"], NOT OK
  "jobTitle": "string", OK
  "mail": "string", OK
  "mailboxSettings": {"@odata.type": "microsoft.graph.mailboxSettings"}, NOT OK
  "mailNickname": "string", OK
  "mobilePhone": "string", OK
  "mySite": "string", NOT OK
  "officeLocation": "string", OK
  "onPremisesImmutableId": "string", OK
  "onPremisesLastSyncDateTime": "String (timestamp)", OK
  "onPremisesSecurityIdentifier": "string", OK
  "onPremisesSyncEnabled": true, OK
  "passwordPolicies": "string", OK
  "passwordProfile": {"@odata.type": "microsoft.graph.passwordProfile"}, OK
  "pastProjects": ["string"], NOT OK
  "postalCode": "string", OK
  "preferredLanguage": "string", OK
  "preferredName": "string", NOT OK
  "provisionedPlans": [{"@odata.type": "microsoft.graph.provisionedPlan"}], OK
  "proxyAddresses": ["string"], OK
  "responsibilities": ["string"], NOT OK
  "schools": ["string"], NOT OK
  "skills": ["string"], NOT OK
  "state": "string", OK
  "streetAddress": "string",OK
  "surname": "string",OK
  "usageLocation": "string",OK
  "userPrincipalName": "string",OK
  "userType": "string",OK

  "calendar": { "@odata.type": "microsoft.graph.calendar" },,OK
  "calendarGroups": [{ "@odata.type": "microsoft.graph.calendarGroup" }],,OK
  "calendarView": [{ "@odata.type": "microsoft.graph.event" }],,OK
  "calendars": [ {"@odata.type": "microsoft.graph.calendar"} ],,OK
  "contacts": [ { "@odata.type": "microsoft.graph.contact" } ],,OK
  "contactFolders": [ { "@odata.type": "microsoft.graph.contactFolder" } ],,OK
  "createdObjects": [ { "@odata.type": "microsoft.graph.directoryObject" } ],,OK
  "directReports": [ { "@odata.type": "microsoft.graph.directoryObject" } ],,OK
  "drive": { "@odata.type": "microsoft.graph.drive" },,OK
  "events": [ { "@odata.type": "microsoft.graph.event" } ],,OK
  "inferenceClassification": { "@odata.type": "microsoft.graph.inferenceClassification" },,OK
  "mailFolders": [ { "@odata.type": "microsoft.graph.mailFolder" } ],,OK
  "manager": { "@odata.type": "microsoft.graph.directoryObject" },,OK
  "memberOf": [ { "@odata.type": "microsoft.graph.directoryObject" } ],,OK
  "messages": [ { "@odata.type": "microsoft.graph.message" } ],,OK
  "ownedDevices": [ { "@odata.type": "microsoft.graph.directoryObject" } ],,OK
  "photo": { "@odata.type": "microsoft.graph.profilePhoto" },,OK
  "registeredDevices": [ { "@odata.type": "microsoft.graph.directoryObject" } ],OK
}

PEOPLE - LIST FROM GITHUB, EVERY PROP MANUALLY CHECKED IN REQUEST

{
  "birthday": "string",OK
  "companyName": "string",OK
  "department": "string",OK
  "displayName": "string",OK
  "emailAddresses": [{"@odata.type": "microsoft.graph.rankedEmailAddress"}],OK
  "givenName": "string",OK
  "id": "string (identifier)",OK
  "isFavorite": true,OK
  "mailboxType": "string",OK
  "officeLocation": "string",OK
  "personNotes": "string",OK
  "personType": "string",OK
  "phones": [{"@odata.type": "microsoft.graph.phone"}],OK
  "postalAddresses": [{"@odata.type": "microsoft.graph.location"}],OK
  "profession": "string",OK
  "sources": [{"@odata.type": "microsoft.graph.personDataSource"}],OK
  "surname": "string",OK
  "title": "string",OK
  "webSites": [{"@odata.type": "microsoft.graph.webSite"}],OK
  "yomiCompany": "string",OK
}

**Comment by marych** [comment]
Contact schema has recently changed on the /beta endpoint - see https://blogs.msdn.microsoft.com/exchangedev/2016/06/09/upcoming-changes-to-contacts-and-people-apis/ which is the reason why your requests were failing for some of the properties that were removed from the schema. MS Graph documentation was updated via https://github.com/OfficeDev/microsoft-graph-docs/commit/daec19c0043290094b24b709ee3f751c93451e25.

As for the user type the following properties can only be selected for individual users (e.g. /beta/me?$select=aboutMe or /beta/users/id?$select=aboutMe) and not for collections of users (e.g. /beta/users?$select=aboutMe):
- aboutMe
- birthday
- hireDate
- interests
- mySite
- pastProjects
- preferredName
- responsibilities
- schools
- skills
- mailboxSettings

We should mention that in the documentation.

I don't see any issues for the Person type.
