### ISSUE TITLE
Support Application Permissions for event creation to a Group

### ISSUE THREAD

**Issue by naesevol** [microsoftgraph/microsoft-graph-docs#3816]
My requirement is: 

I want to be able to let my application create an appointment to a group calendar, without a user having to grant consent. I can do this fine in Graph Explorer v1.0 or beta, because that uses Delegated permissions. 

When I try via POSTMAN or any other programmatic method, I am blocked by a 403, despite being authenticated enough to do other things via Graph.

I gave my app ALL possible permissions, and granted admin consent, to rule out anything on that end.
Then I see in the documentation for both v1.0 and BETA (https://docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-beta) that this is "not supported" for Application.

Is this on the road map anywhere? I would hope so, since I can do this in EWS today. 

I want to switch to Graph, because EWS requires that I hard-code my credentials when I am using Exchange Online (non-starter).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3657f7cb-10f9-0631-362d-f8e66edcd018
* Version Independent ID: dfa0e4c5-38d0-6aa0-6d5b-e35f66c78135
* Content: [Create event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-events.md)
* Product: **groups**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by arritx** [comment]
Hi, where have you read "not supported"? I'm getting "Access is denied. Check credentials and try again." no matter what I do. I can read events from the Group calendar in my application. I can create events in my own calendar. I can create events in the Group calendar from the Graph Explorer. Is it really not supported?

**Comment by davidmu1** [comment]
Application permissions are not supported for this API. No change identified for the page. Closing the issue.
