### ISSUE TITLE
nit: Incorrect wording on contribute call to action

### ISSUE THREAD

**Issue by martellaj** [microsoftgraph/microsoft-graph-docs#383]
The call to action to contribute should be "Edit **on** GitHub", rather than "Edit **in** GitHub".

![image](https://cloud.githubusercontent.com/assets/1019478/16744074/338b7916-4764-11e6-9e4e-6fdd7d9e50fc.png)

**Comment by keyur32** [comment]
Old issue, but consulted with folks on our team and we believe this is the correct syntax. We are planning to migrate our docs to docs.microsoft.com and in that case it will simply be "Edit"
