### ISSUE TITLE
Recording duration limitation

### ISSUE THREAD

**Issue by Githamza** [microsoftgraph/microsoft-graph-docs#3834]
I would record a call on teams using Graph API.
As mentionned in [documentation](https://docs.microsoft.com/en-us/graph/api/call-record?view=graph-rest-beta) .

I make a request 

```
POST https://graph.microsoft.com/beta/app/calls/{id}/record
Content-Type: application/json
Content-Length: 394

{
  "bargeInAllowed": true,
  "clientContext": "d45324c1-fcb5-430a-902c-f20af696537c",
  "prompts": [
    {
      "@odata.type": "#microsoft.graph.mediaPrompt",
      "mediaInfo": {
        "uri": "https://cdn.contoso.com/beep.wav",
        "resourceId": "1D6DE2D4-CD51-4309-8DAA-70768651088E"
      },
      "loop": 5
    }
  ],
  "maxRecordDurationInSeconds": 1800,
  "initialSilenceTimeoutInSeconds": 10,
  "maxSilenceTimeoutInSeconds": 2,
  "recordingFormat": "wav",
  "playBeep": true,
  "streamWhileRecording": true,
  "stopTones": [ "#", "11", "*" ]
}
```
I get the response with file locatop,

```
{
 [
    {
      "changeType": "deleted",
      "resource": "/app/calls/57DAB8B1894C409AB240BD8BEAE78896/operations/0FE0623FD62842EDB4BD8AC290072CC5",
      "resourceData": {
        "@odata.type": "#microsoft.graph.recordOperation",
        "@odata.id": "/app/calls/57DAB8B1894C409AB240BD8BEAE78896/operations/0FE0623FD62842EDB4BD8AC290072CC5",
        "@odata.etag": "W/\"54451\"",
        "clientContext": "d45324c1-fcb5-430a-902c-f20af696537c",
        "status": "completed",
        "recordResourceLocation": "https://file.location/17e3b46c-f61d-4f4d-9635-c626ef18e6ad",
        "recordResourceAccessToken": "<access-token>",
        "completionReason": "stopToneDetected"
      }
    }
  ]
}
```
**Actual problem**

When I request the location url and get the file , the maximum duration of the audio file is 300s

**Expected behaviour**

Extend the recording time to longer than 300 s ( 5min ) ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 091cd3ab-66e3-4b3e-8ba1-b1b78bbc0e8d
* Version Independent ID: 813d4f21-2eff-5dd2-451e-311565c5f597
* Content: [call: record - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/call-record?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/call-record.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/call-record.md)
* Product: **microsoft-teams**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **jthake-msft**

**Comment by VinodRavichandran** [comment]
Hi @Githamza, Would it be possible for you to send us logs of your request/response?

**Comment by VinodRavichandran** [comment]
Hi @Githamza, Thanks for sharing your logs. 5 mins is the limit for this service. The intent of this is to record a small audio clip, e.g. name of a participant who joined the meeting. Let me know if you are having an issue with clips of <300s too.

**Comment by Githamza** [comment]
Thanks for your reply, 

what I would is record a conversation between participants, mostly  it lasts more than 5 min. So I'm looking for a solution to be able to do that.

**Comment by VinodRavichandran** [comment]
@Githamza  Look like you have another thread on this, I have replied there :)

**Comment by mwerghemmi** [comment]
Hi @VinodRavichandran, 

In case we want to stream audio while recording, (  "streamWhileRecording": true). 
Are we supposed to receive stream once the record is starting or once is finished ? 

I've done a test where stream is sent only after the record duration is dreached (example 100 sec). 
We would like to retreive as often as possible the audio stream (each 15 or 10 sec for example). 

Thanks in advance !

**Comment by VinodRavichandran** [comment]
@mwerghemmi What is your scenario? Also, can you please open a  separate item, I would like to close the Recording limit question.

**Comment by mwerghemmi** [comment]
Hi @VinodRavichandran , 
sure i'll do.
