### ISSUE TITLE
Bulk create users?

### ISSUE THREAD

**Issue by Gabukun** [microsoftgraph/microsoft-graph-docs#3836]
Does the API accept an array of JSONs for several users to be created?
Does the API accept an array of JSONs for several users to be created?
[
{
  "accountEnabled": true,
  "displayName": "displayName-value1",
  "mailNickname": "mailNickname-value1",
  "userPrincipalName": "upn-value1@tenant-value.onmicrosoft.com",
  "passwordProfile" : {
    "forceChangePasswordNextSignIn": true,
    "password": "password-value"
  }
},
{
  "accountEnabled": true,
  "displayName": "displayName-value2",
  "mailNickname": "mailNickname-value2",
  "userPrincipalName": "upn-value2@tenant-value.onmicrosoft.com",
  "passwordProfile" : {
    "forceChangePasswordNextSignIn": true,
    "password": "password-value"
  }
}
]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-gb/graph/api/user-post-users?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by kevinCefalu** [comment]
Did this question ever get answered?

**Comment by andrewconnell** [comment]
I don't believe it does. The recommended way to do this would be to use the `$batch` endpoint to submit multiple requests in one round-trip.

**Comment by dkershaw10** [comment]
https://docs.microsoft.com/graph/json-batching
