### ISSUE TITLE
Graph API $Count: Wrong result

### ISSUE THREAD

**Issue by damirgrcic** [microsoftgraph/microsoft-graph-docs#3848]
The result of my query is  "@odata.count": -1," (expect: @odata.count": 10)  if I have a resultset which is greater than 9. Same query with a resultset of lower-equals 9 works fine.

Example Request: 
https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages/?$filter=isRead eq true&$select=isRead&$count=true

Response:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('xxxxx')/mailFolders('inbox')/messages(isRead)",
    "@odata.count": -1,
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages/?$filter=isRead+eq+true&$select=isRead&$count=true&$skip=10",
    "value": [
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {
            "isRead": true
        },
        {,
            "isRead": true
        }
    ]
}

**Comment by BraunJonathan** [comment]
Same here, so strange...
same request with isRead eq false works...

Can somebody respond ?

**Comment by zhipingliu32** [comment]
Same here. Any update about the fix plan.

**Comment by kandharithirumalreddy** [comment]
Hi Is there any fix for it?

**Comment by abheek-das** [comment]
I checked the above query and a few more, and this looks to be working as expected. Closing this. Please re-open if you still see the issue.

Request: 
https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages?$filter=isDeliveryReceiptRequested eq false&$select=isRead&$count=true

Response:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('56f34a3d-e47f-4326-b3d6-9837d8e5a99d')/mailFolders('inbox')/messages(isRead)",
    "@odata.count": 1786,
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/mailfolders/inbox/messages?$filter=isDeliveryReceiptRequested+eq+false&$select=isRead&$count=true&$skip=10",
    "value": [
        {
            "@odata.etag": "W/\"CQAAABYAAAA9TX1A44yVSYZq/GJlk8mvAAAAABkV\"",
            "id": "AAMkADg3NTY5MDg4LWMzYmQtNDQzNi05OTgwLWQyZjg2YWQwMTNkZABGAAAAAABovLYeNNaVTqLtDrPKCY1jBwA9TX1A44yVSYZq-GJlk8mvAAAAAAEMAAA9TX1A44yVSYZq-GJlk8mvAAAAAAVoAAA=",
            "isRead": true
        },
        ...
    ]
}
