### ISSUE TITLE
Selecting User fields and including value "hireData" raises a NotImplementedError

### ISSUE THREAD

**Issue by gmicek** [microsoftgraph/microsoft-graph-docs#3878]
Not sure if/how you all might want to update the documentation for this. Doesn't personally matter to me, just an FYI

If I hit this endpoint like this:
/users?$select=id,displayName --&gt; This works OK, but
/users?$select=id,displayName,hireDate --&gt; This throws a "NotImplementedError"
Thus, the hireDate field is not implemented yet and cannot be used by ODATA select

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by Lauragra** [comment]
@dkershaw10 , can you look into this please?

**Comment by gmicek** [comment]
I've got some others that stop with NotImplementedError. Not sure if you all want them, but just an FYI (again no concerns from my side, just letting docs team know):

Specifically for the /groups endpoint (a different endpoint from this aforementioned issue at /user), these throw NotImplementedError:
/groups?$select=allowExternalSenders
/groups?$select=autoSubscribeNewMembers
/groups?$select=isSubscribedByMail

**Comment by dkershaw10** [comment]
@gmicek I can't repro this in Graph Explorer for hireDate or the other properties.
Are you making these calls in application only mode?
Do you have an Office 365 subscription?

**Comment by gmicek** [comment]
Hi @dkershaw10 I was able to reproduce this in graph explorer? Note that there are 2 different endpoints: /users in the description and /groups in my additional comment

URL: https://developer.microsoft.com/graph/graph-explorer/
GET https://graph.microsoft.com/v1.0/Users?$select=id,displayName,hireDate

This results with:
Failure - Status Code 501
Response Preview:

{
    "error": {
        "code": "NotImplemented",
        "message": "This operation target is not yet supported.",
        "innerError": {
            "request-id": "463f8ba0-62c0-44b5-b0ff-77f5d551146a",
            "date": "2019-02-19T18:57:53"
        }
    }
}

**Comment by BrianTJackett** [comment]
Getting NotImplemented error with the following as well on v1 and beta endpoints.

  /users?$select=mySite      <-- Errors

This does work when specifying an individual user though, but then means I have to make call(s) to get all users and then individual calls for each user to get their mySite.  Not efficient at all.

  /users/{user-id}?$select=mySite    <-- Succeeds

**Comment by LoungeFlyZ** [comment]
We are also experiencing this with `skills` in a $select in a query to /users. 

`https://graph.microsoft.com/v1.0/users?$select=id,skills&$top=5` <-- Errors

**Comment by DominicArchual** [comment]
I am experiencing this issue as well; I have posted a question about it on stackoverflow documenting all the steps I've taken: https://stackoverflow.com/questions/56570313/cannot-get-more-than-basic-user-info-with-microsoft-graph-api

Can someone (from Microsoft) look into this soon, please?

**Comment by synth** [comment]
FYI: 
> Certain properties cannot be returned within a user collection. The following properties are only supported when retrieving an single user: aboutMe, birthday, hireDate, interests, mySite, pastProjects, preferredName, responsibilities, schools, skills, mailboxSettings.

https://github.com/microsoftgraph/microsoft-graph-docs/blob/d8b442a0adf189eda12e8132d13fb3b056b7a64f/api-reference/v1.0/api/user-list.md#optional-query-parameters

**Comment by krbain** [comment]
Thanks @synth. Yes, this is already included in the docs: https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#http-request
