### ISSUE TITLE
Selecting User fields without $ fails with bad request

### ISSUE THREAD

**Issue by gmicek** [microsoftgraph/microsoft-graph-docs#3879]
Not sure if/how you all might want to update the documentation for this. Doesn't personally matter to me, just an FYI

This is contrary to global docs stating that "$" is optional

If I hit this endpoint like this:
/users?$select=id,displayName --> This works OK, but
/users?select=id,displayName --> This fails with HTTP 400 Bad Request. Details:

{
    "error": {
        "code": "Request_BadRequest",
        "message": "Unrecognized query argument specified: 'select'.",
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by Lauragra** [comment]
@piotrci , can you look into this please?

**Comment by baywet** [comment]
Hi @gmicek 
Thank you bringing this to our attention and sorry if it took so long to reply to you.
It seems that since you posted the issue the page was edited multiple times and the faulty reference was removed.
Closing for now, let me know if I'm missing something
