### ISSUE TITLE
Partial range download for DriveItemVersion

### ISSUE THREAD

**Issue by ryazonjr** [microsoftgraph/microsoft-graph-docs#3882]
It seems partial range download is not supported, it seems to ignore the range specified in the request and the whole content is returned in the response.  Can you please confirm and if so update the doc? Will this be supported in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80b4146-ab1c-7d90-aa65-106961f2b57a
* Version Independent ID: bf6b72db-acf6-3b9e-d24c-681c172035f7
* Content: [DriveItemVersion resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/driveitemversion?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/driveItemVersion.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/driveItemVersion.md)
* Product: **sharepoint**
* GitHub Login: @jthake-msft
* Microsoft Alias: **jthake-msft**

**Comment by mlafleur** [comment]
Could you explain what you mean by "partial range"? Are you looking for only part of the content?
