### ISSUE TITLE
Method returns status code 400

### ISSUE THREAD

**Issue by trevonmckay** [microsoftgraph/microsoft-graph-docs#3887]
I attempted to update an importedWindowsAutopilotDeviceIdentity object based on the example but received the following error

```
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key with http verb PATCH for request /DeviceEnrollmentFE/StatelessDeviceEnrollmentFEService/deviceManagement/importedWindowsAutopilotDeviceIdentities('...').",
        "innerError": {
            "request-id": "61622792-93d2-417f-ae2d-119456809173",
            "date": "2019-01-29T23:46:02"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8325c764-03a8-b691-077d-375bb340b514
* Version Independent ID: 623750fd-2f7c-8897-eb68-c8b5419260e0
* Content: [Update importedWindowsAutopilotDeviceIdentity - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-importedwindowsautopilotdeviceidentity-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-update.md)
* Product: **intune**
* GitHub Login: @tfitzmac
* Microsoft Alias: **jthake-msft**

**Comment by sringler** [comment]
+1

**Comment by cconrado** [comment]
any fix? @rolyon

**Comment by triplanedave** [comment]
Thanks for the feedback.  In this case, Graph allows the call to go through to that route, but we don't have any code at that endpoint to pick up the incoming call.  I've filed a bug for our developers to remove the endpoint from the documentation, as it's not an endpoint you can call.
