### ISSUE TITLE
Access a site by server-relative URL does not work for root site

### ISSUE THREAD

**Issue by romanSlivinskyi** [microsoftgraph/microsoft-graph-docs#3892]
Access a site by server-relative URL does not work the root site

I am using the following endpoint to fetch site information:

`GET /sites/{hostname}:/{server-relative-path}`

For the root site I send to :

`GET /sites/{hostname}:/`

It was working perfectly, but now it doesn't.
However, I am able to get such an information sending to: 

`GET /sites/root`

Should both endpoint work or the first one is deprecated now?

**Comment by dmcweeney** [comment]
Just encountered this problem too. Any update on this issue?

**Comment by romanSlivinskyi** [comment]
I use /root, does it work for you?

**Comment by dmcweeney** [comment]
Do you mean use /root as the server-relative-path? That does not work.

```
https://graph.microsoft.com/v1.0/sites/m365xYYYYYY.sharepoint.com:/root
{
    "error": {
        "code": "itemNotFound",
        "message": "The provided path does not exist, or does not represent a site",
    }
}
```

This https://graph.microsoft.com/v1.0/sites/root site alright but can it be possible to have a secondary SharePoint server with a different hostname?

**Comment by romanSlivinskyi** [comment]
There are user personal sites like tenant-my.sharepoint.com and Ms graph doesn't see them as well. I had users that migrated from on premise and got somehow a different host name and those also we're not visible from Ms graph.

**Comment by dmcweeney** [comment]
@jthake-msft any ideas?

**Comment by paul2newman** [comment]
We are experiencing the same issue. Has been driving me nuts, but good to know I'm no the only one. Please can we have a fix as soon as possible.
