### ISSUE TITLE
Workaround for creating ChatThread using application permission?

### ISSUE THREAD

**Issue by dni128** [microsoftgraph/microsoft-graph-docs#3894]
heyhey, i understand that this option is not yet available. First Question: is there a date for the release? Second Question: does anyone know of a WORKAROUND for the problem? ... problem is: posting a message (with attachment optional) into a Teams Channel without using a Bot and application permissions (AccessToken from  Azure AD v2.0 endpoint using OAuth 2 client credentials grant - as in https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9704160-8b7d-166c-af96-4d8a938a28fd
* Version Independent ID: 3ac38651-1d94-54f4-41aa-2d8fc16e438c
* Content: [Create chat thread - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-chatthreads?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/channel-post-chatthreads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-chatthreads.md)
* Product: **microsoft-teams**
* GitHub Login: @nkramer
* Microsoft Alias: **jthake-msft**

**Comment by nkramer** [comment]
No, we don't have the date for application permissions for sending messages, it's not going to be for quite a while. Bots are the preferred workaround -- why doesn't using a bot work for you? Thx.

**Comment by dni128** [comment]
hey Nick, thanx for answering! That is a pitty, because i could really use it ;( You are asking, why not use a bot. Because, as far as i know, i can not implement it without the client credential flow, a user LOGIN? If so, i was missing something and would gladly listen to you, if you share this information with me ;) To be more specific: I am building a SERVICE, that (ideally) NEVER quotes a USER for interaction, but instead has granted itz permissions by an administrator while installed! Is a Bot something i can use in this scenario? Thanx for you time, respectfully - Dennis.
