### ISSUE TITLE
Properties missing when requesting resource from Graph API

### ISSUE THREAD

**Issue by ftunholm** [microsoftgraph/microsoft-graph-docs#3897]
Hello!

According to the [`educationUser`] (https://docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0) documentation, there should exist `teacher`, `student` and other properties that I can not locate when requesting the same object from the API. 

What is the intention? Is this something that is broken in the API or is the documentation outdated? I'm in real need to extract the `externalId` from an `educationUser` or `educationTeacher` but I cannot find any way to accomplish this. Any suggestions?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 777a85af-5cbb-e62e-7123-bd7ffac215dc
* Version Independent ID: d7719b66-bb44-a67b-d87a-ae7bf888c9e4
* Content: [educationUser resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/educationuser.md)
* Product: **education**
* GitHub Login: @mmast-msft
* Microsoft Alias: **jthake-msft**

**Comment by ftunholm** [comment]
UPDATE:

I did find another issue related to this #3190. I Asked if the issuer found a solution and got the response - that the expected properties is only if I authenticate as the application and not with a delegated access token. I did try this out and it indeed worked. I also had to add some application permission before I got the data (I don't know which because I tried a few).

**Comment by stnor** [comment]
What's the plan going forward here? Ping @mmast-msft 
Are there any plans to make the missing properties available when using delegated permissions?
Or works as expected, update docs?

**Comment by mmast-msft** [comment]
Unfortunately, we don't have any mechanism to filter properties based on the role of the logged-in user, so EduRostering.ReadBasic is extremely restrictive on the properties that it will expose on an educationUser object.  We'll need to update the documentation to clarify this.  We don't have plans at this time to make this information available with delegated permissions.

**Comment by stnor** [comment]
As it stands you need to do some weird stuff to get the students of a class with delegated permissions. 
1. GET /education/classes/{id}/members
2. GET /education/classes/{id}/teachers
3. Remove the teachers from (1).

It would be helpful with a GET /education/classes/{id}/students.

**Comment by mmast-msft** [comment]
Thank you for the feedback.  We agree that it would be helpful.   While the request sounds rather simple, there are complications in the current implementation that have prevented us from providing that endpoint.  We will keep it in mind for the future.

**Comment by mlafleur** [comment]
These properties have been made available to delegated callers in `beta` and are currently in the pre-release pipeline for `v1.0` (expected to roll out in Q1 of 2021).

**Comment by stnor** [comment]
Thanks for this! It there any mechanism that can notify me when it's released?
