### ISSUE TITLE
Getting error when accessing Teams channel messages: Proxy_InternalServerError

### ISSUE THREAD

**Issue by devlanfear** [microsoftgraph/microsoft-graph-docs#3901]
Issue: 
When getting Teams channel messages via delegated permissions (user is a member of the team): https://graph.microsoft.com/beta/teams/{team_id}/channels/{channel_id}/messages/ 

Getting error:

{
    "error": {
        "code": "Proxy_InternalServerError",
        "message": "Failure in forwarding request.",
        "innerError": {
            "request-id": "511b812c-df43-402b-b9dd-34ca1c1bd397",
            "date": "2019-02-01T14:22:50"
        }
    }
}

Tested with Graph Explorer and code.

Article:
https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta

**Comment by merouaneh** [comment]
Hello,
I can get the first Result, but i get the same error for the second page using  the **@odata.nextLink**
https://graph.microsoft.com/beta/teams/idteam/channels/idchannel/messages?$skiptoken=a-long-
string...

the ids have this form: **19:fd12dfd121eb4ddb5ccbfe1dca1d111@thread.skype**

Any one could help ?
Many thanks

**Comment by devlanfear** [comment]
Tried now again, new response for the same request:

{
    "error": {
        "code": "UnknownError",
        "message": "Bad Request",
        "innerError": {
            "request-id": "d8a474d7-08c3-46ea-87c0-f31e88363303",
            "date": "2019-04-07T06:01:38"
        }
    }
}

**Comment by aakarshit** [comment]
I see a mix of both as of yesterday

**Comment by Aldarean** [comment]
This error might also happen because some subscription has expired. I spend half a day today to find out why the following call doesn't work in the Graph Explorer:

```
https://graph.microsoft.com/beta/me?$select=
id,
displayName,
pastProjects,
skills,
schools,
businessPhones,
givenName,
jobTitle,
mail,
mobilePhone,
officeLocation,
preferredLanguage,
surname,
userPrincipalName,
department,
hireDate,
jobTitle,
Interests,
mySite,
officeLocation
```

The error that I got:
```
{
    "error": {
        "code": "Proxy_InternalServerError",
        "message": "Failure in forwarding request.",
        "innerError": {
            "request-id": "cef95ea9-f65a-4c6f-ad9c-7deb2fd79d35",
            "date": "2019-09-05T13:01:37"
        }
    }
}
```

it turned out that this worked:
`https://graph.microsoft.com/beta/me?$select=id,displayName,givenName,jobTitle,department,surname,officeLocation`

thus I was able to conclude that Sharepoint was no longer available to me. Pity the error discription is so vague about it.

**Comment by yaagraw** [comment]
@devlanfear , @rwormsbecher , @akudhingra , @ashoksubedi1 , @merouaneh 

Is this issue fixed ?

**Comment by ashoksubedi1** [comment]
Mine was fixed along ago, my apologies for not coming back to notice every one. Thank you
