### ISSUE TITLE
Poor documentation on how to use the Revoke Refresh Token Function call:

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#3908]
Recently we had a case and several discussion forum about the Refresh Token Revocation Function does not work from one of the following links:
 
https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureadsignedinuserallrefreshtoken?view=azureadps-2.0 
https://docs.microsoft.com/en-us/powershell/module/azuread/revoke-azureaduserallrefreshtoken?view=azureadps-2.0 
https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/users-operations#invalidate-all-refresh-tokens-for-a-user 
https://docs.microsoft.com/en-us/graph/api/user-invalidateallrefreshtokens?view=graph-rest-beta 
 
It's not very obvious about on how to use this Function correctly.   From ICM 
99554631
 
the way it’s supposed to work is as followed due to “clock skew” consideration:

Auth -&gt; wait 1+ mins -&gt; revoke the refresh token -&gt; wait 1+ mins -&gt; reuse the refresh token -&gt; should get error.  The higlighted are keys.
 
Can we get the documentation updated please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f5dd2-e23e-4453-258d-036950e5a589
* Version Independent ID: 2290444e-dbb1-194f-d6f5-132972153998
* Content: [user: invalidateAllRefreshTokens - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-invalidateallrefreshtokens?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/user-invalidateallrefreshtokens.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-invalidateallrefreshtokens.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **jthake-msft**

**Comment by rsrinivasanhome** [comment]
When this issue is planned to be closed

**Comment by dkershaw10** [comment]
Fixed with https://github.com/microsoftgraph/microsoft-graph-docs/pull/4675
