### ISSUE TITLE
Need more info on "Global Administrator"

### ISSUE THREAD

**Issue by chryw** [microsoftgraph/microsoft-graph-docs#3917]
I'm stuck on getting access and can't figure out what "Global Administrator" means. Is this our team's SharePoint admin or Azure subscription admin? I don't know who to contact to get permission.

Here's the error message:
![image](https://user-images.githubusercontent.com/7075677/52233360-b4222f00-2873-11e9-9426-9cb6f81be2ce.png)

```
Need admin approval
Tutorial Sample App
Tutorial Sample App needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

Have an admin account? Sign in with that account
Return to the application without granting consent
```

```
Request Id: 215af977-11d5-4ed1-b1bc-5003db27a400
Correlation Id: 13efa1db-5aba-426e-bbd1-5925624c60a3
Timestamp: 2019-02-04T19:44:56Z
Message: AADSTS900941: An administrator of Microsoft has set a policy that prevents you from granting Tutorial Sample App the permissions it is requesting. Contact an administrator of Microsoft who can grant permissions to this application on your behalf.
Advanced diagnostics: Enable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.
```

In Azure Portal when I try to click "Grant Permission" button, it gives me this error code:
```
{"errorCode":"Authorization_RequestDenied","localizedErrorDetails":{"errorDetail":"An administrator of Microsoft has set a policy that prevents you from granting lucky-charms the permissions it is requesting. Contact an administrator of Microsoft who can grant permissions to this application on your behalf."},"operationResults":null,"timeStampUtc":"2019-02-04T19:52:06.3537798Z","clientRequestId":"14fc1ba2-6fca-4b44-96f9-80ec0a0d1031","internalTransactionId":"366d8326-92ef-40b9-b60a-0cadaf54f0de","upn":"username@microsoft.com","tenantId":"72f988bf-86f1-41af-91ab-2d7cd011db47","userObjectId":null,"exceptionType":"AADGraphException"}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **jthake-msft**

**Comment by FaithOmbongi** [comment]
Thank you @chryw for raising your issue. If you are still facing challenges with admin approval, kindly use the [Microsoft Graph Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html) channel to get assistance on this. Unfortunately, this channel is not monitored for such issues as it's only for documentation issues.
