### ISSUE TITLE
The sample of creating plan doesn't work

### ISSUE THREAD

**Issue by VitorX** [microsoftgraph/microsoft-graph-docs#392]
POST https://graph.microsoft.com/beta/me/plans
    Content-type: application/json
    Content-length: 88

    {
      "createdBy": "createdBy-value",
      "owner": "owner-value",
      "title": "title-value"
    }
Check the document [here](http://graph.microsoft.io/en-us/docs/api-reference/beta/api/user_post_plans). But if I remove the **me** in the request URL, it worked! Is the document incorrect?

And you can check [here](POST /users/<objectId>/plans
POST /drive/root/createdByUser/plans
POST /drive/root/lastModifiedByUser/plans) for creating plans. It is a little different with previews link.

    POST /users/<objectId>/plans
    POST /drive/root/createdByUser/plans
    POST /drive/root/lastModifiedByUser/plans

**Comment by marych** [comment]
me/plans is a read-only collection of plans shared with the signed-in user as per https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/user. https://graph.microsoft.io/en-us/docs/api-reference/beta/api/plan_post_plans documents plan creation. The document that you referenced was deleted from GitHub and should not be linked from anywhere - how did you find it?

**Comment by VitorX** [comment]
I open the document of Microsoft Graph from http://graph.microsoft.io/en-us/docs/. Then navigate the page by /Beta Reference/Tasks/Plan/Create Plan. It seems still able to find now.

**Comment by marych** [comment]
@sumurthy - could you please make a menu change to reference http://graph.microsoft.io/en-us/docs/api-reference/beta/api/plan_post_plans instead of http://graph.microsoft.io/en-us/docs/api-reference/beta/api/user_post_plans for the "Create plan" menu item?

**Comment by Lauragra** [comment]
Closing this issue as the content update has been published live. Thanks.
