### ISSUE TITLE
Couldn't permanently delete resources with the help of App level permissions

### ISSUE THREAD

**Issue by arutvicky** [microsoftgraph/microsoft-graph-docs#3925]
I have provided enough permissions mentioned in the documentation but I couldn't delete resources with the help of access token generated through App permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c78ec6-6d61-ae2f-5037-e2a57f0580ba
* Version Independent ID: 34b4451f-abca-fa2c-80e2-b651bdab506f
* Content: [Permanently delete item - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-delete?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directory-deleteditems-delete.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **jthake-msft**

**Comment by WardWilmsen** [comment]
Having the exact same issue here. We are writing a solution to clear up some group sites and permanently delete the groups afterwards. But it won't succeed with an app only access token.

Have you found any solution yet ?

**Comment by mrvaghani** [comment]
I am facing the same issue. Has there been any workaround for this?

**Comment by Rakesh654** [comment]
I am also facing the same issue. Is there any fix for this

**Comment by arutvicky** [comment]
Nope. It still exists I think.

**Comment by Bjorn80** [comment]
Having the same issue :S
ETA on fix?

**Comment by keylimesoda** [comment]
Internal bug opened to track this issue.  Will update through triage and resolution.

**Comment by nganb** [comment]
I am having the same issue, permanently delete item with App only permission give the error "Insufficient privileges to complete the operation". Is there any updates on this bug?

**Comment by keylimesoda** [comment]
This has been triaged by the product team and assigned priority 2, severity 3 (medium)

This has been assigned to a team members for the May sprint.

**Comment by keylimesoda** [comment]
Determined to be a doc bug.  Created pull request to fix here:  

https://github.com/microsoftgraph/microsoft-graph-docs/pull/8489

**Comment by DominikMarin** [comment]
Hello,

the same "Insufficient privileges" error also occurs when trying to delete groups with delegated user App permissions - can you please recheck? I do not think this is solely a doc issue.

**Comment by nganbui** [comment]
> Determined to be a doc bug. Created pull request to fix here:
> 
> #8489

Same issue "Insufficient privileges" error also occurs when trying to delete groups permanently with app-only permission, Can you please check, it it working for delegated perm?

**Comment by stupidchen** [comment]
Same issue. Any updates?

**Comment by davidmu1** [comment]
Thank you for the feedback. Removed the unsupported permissions from the page. You can ask functionality related questions at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). Closing the issue.
