### ISSUE TITLE
Creating team - We're still setting up your team, please try again later

### ISSUE THREAD

**Issue by gschilten** [microsoftgraph/microsoft-graph-docs#3926]
Issue:
When creating a team through graph api, days later it's still giving the user 'We're still setting up your team' when asking for the mail address of one of the channels.

Article:

**Comment by gschilten** [comment]
Apparently, the team name seems to be at fault. Still finding the pattern.

**Comment by mohsinhere** [comment]
Hi,

Were you able to make any progress with this? I'm having the same issue (after more than a year!)
