### ISSUE TITLE
Query parameters $orderby, $skip aren't working

### ISSUE THREAD

**Issue by biste5** [microsoftgraph/microsoft-graph-docs#393]
Trying to make use of mentioned query parameters, also trying examples from documentation
[Microsoft Graph optional query parameters](http://graph.microsoft.io/en-us/docs/overview/query_parameters)

for instance (from documentation page linked)
`https://graph.microsoft.com/v1.0/me?$orderby=createdDateTime&$skip=20`
returns a 400 response code, with detailed error message _"OrderBy not supported."_

I do see some other endpoints/examples using $groupby do work though.
I'm not able to perform this query using just $skip
`https://graph.microsoft.com/v1.0/users?$select=displayName&$skip=10`

These happen for both v1.0 and beta endpoints.

It should be more clear which endpoints support which query parameters, if not supported consistently by all (yet?)
Is $skip supported only where the endpoint doesn't support $skipToken ? If this is the case it should be more clear as well

**Comment by marych** [comment]
User entity type doesn't have a createdDateTime property and thus the first request fails. According to description the request should be for /me/events and not just /me. I created pull request https://github.com/OfficeDev/microsoft-graph-docs/pull/451 to correct that example. It looks like it was accidentally broken by https://github.com/OfficeDev/microsoft-graph-docs/commit/71a81beb2a4bc38df3d69ccd850bdfdfde85c199.

As for $skip vs $skipToken - yes, normally only one of them is supported for a given collection. $skip allows access to any page in the result set whereas $skipToken only to the next page. @odata.nextLink would use $skip for collections that support it (e.g. events) or $skipToken for collections that don't support $skip (e.g. users).

**Comment by dmahugh** [comment]
Verified PR was merged.
