### ISSUE TITLE
Incorrect OneNote Tab configuration sample

### ISSUE THREAD

**Issue by advdberg** [microsoftgraph/microsoft-graph-docs#3931]
In the example OneNote Tab configuration, properties contentUrl and removeUrl, where the {sectionsUrl} is mentioned, the {groupId} should be placed, otherwise the tab will give an error when opened in Teams. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* GitHub Login: @nkramer
* Microsoft Alias: **jthake-msft**

**Comment by NCSTman** [comment]
Yeah I second the notion to update the article as per advdberg's comment as it will save a lot of heads smashing through desks. I speak from experience.

**Comment by jjtbsomhorst** [comment]
I just smashed my head..

**Comment by advdberg** [comment]
I think @nkramer or @jthake-msft can prevent a lot of sore heads ;-)

**Comment by HN5** [comment]
Awesome @NCSTeam many thx for your help... I wasted half a day on this :(

**Comment by umaknow-francis** [comment]
Tryning to interpret your comment about OneNote since I also get the error, but I can't figure it out. Anyone can provide a working URL pattern? I tried to add %2F{GroupId} before the %2F{sectionsUrl}.

**Comment by advdberg** [comment]
don't use the sectionsUrl but the groupId instead

**Comment by umaknow-francis** [comment]
Worked like a charm. Thank you so much for your quick answer!

**Comment by joakimhogberg** [comment]
Thank you @advdberg for posting this! This works fine, but I noticed that my tab now doesn't take my name that I provide as displayName. It show correct name first, but then it changes to "note":
![image](https://user-images.githubusercontent.com/5407853/57927943-c28ad880-78af-11e9-8515-72549c56becd.png)

Don't know if this is related, or if it should be a new issue...

**Comment by NCSTman** [comment]
@joakimhogberg

No issue, remember that you're working with links when creating the tab. Read the "Displayname of OneNote tab changes on first access"  that I brought up and you'll get it.

**Comment by magnusdanielson** [comment]
What could possibly be wrong with below. It gives me "Entity can not be null" exception but id does add the tab to the team
var oneNoteTab = new TeamsTab()
            {
                Id = oneNoteEntityId,
                ODataBind = "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/0d820ecd-def2-4297-adad-78056cde7c78",
                DisplayName = "Notes",
                TeamsApp = oneNoteApp,
                Configuration = new TeamsTabConfiguration()
                {
                    EntityId = oneNoteEntityId,
                    ContentUrl = contentUrl,
                    RemoveUrl = removeUrl,
                    WebsiteUrl = webSiteUrl,
                }
            };
