### ISSUE TITLE
Graph API's that access Exchange return different error codes than what is listed

### ISSUE THREAD

**Issue by mattgaspar** [microsoftgraph/microsoft-graph-docs#3935]
For example I was getting the code "ErrorQuotaExceeded" when using sendMail
Exchange response codes (which seem to get returned by the graph api) are listed here: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/responsecode

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77cc3520-96d8-6aa4-1243-20b7f4d5c4cb
* Version Independent ID: 79a31ea9-d9b3-2602-e412-4959498a11c0
* Content: [Microsoft Graph error responses and resource types - Microsoft Graph](https://docs.microsoft.com/en-us/graph/errors?view=graph-rest-1.0)
* Content Source: [concepts/errors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/errors.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svpsiva** [comment]
Graph API calls should return Graph error codes as listed in the error documentation.
@mattgaspar Can you share details any of the following details for us to investigate?
API name, time duration during which you've faced the error, exact error message/response.

**Comment by svpsiva** [comment]
Closing issue due to no response.
