### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by cirwin152** [microsoftgraph/microsoft-graph-docs#3936]
Could you please add a creation/update timestamp to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c845aee3-a05b-2183-cde6-e51341ec5609
* Version Independent ID: eb1b915b-f376-82d4-ecc6-c9da3b78af89
* Content: [List rules - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/mailfolder-list-messagerules?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/mailfolder-list-messagerules.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/mailfolder-list-messagerules.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @cirwin152 , thank you for your suggestion.
You can enter feature requests on UserVoice at https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/category/101632-microsoft-graph-o365-rest-apis.

In the future, you can also conveniently get to UserVoice by choosing **Product feedback** in the **Feedback** section at the end of each reference topic.

Thank you for your interest.
