### ISSUE TITLE
Permissions levels not correct 

### ISSUE THREAD

**Issue by ferronsw** [microsoftgraph/microsoft-graph-docs#3938]
With the following permissions I get an insufficient permissions error:

Delegated (work or school account)	User.Read, Group.Read.All

The permission level with the least permissions that works is the Directory.Read.All.
Please update the docs with the correct permission info.

The info for GetMemberObjects is also not correct, because I get results with User.Read.All permission who are not described on the page:
https://docs.microsoft.com/en-us/graph/api/user-getmemberobjects?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f25fe8f4-6ed0-4bba-b7f6-2d2f1dee1b65
* Version Independent ID: 896de422-1460-41c0-883b-e5cfd77f6317
* Content: [user: getMemberGroups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-getmembergroups?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-getmembergroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-getmembergroups.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by swoldemi** [comment]
Any status on this? Would be nice if User.Read was the actual least privileged permission level... 😞

**Comment by juho-hanhimaki** [comment]
Any updates? We're running into the same issue. User.Read permission is not to enough to call the API.

**Comment by jasonjoh** [comment]
@dkershaw10 what are the correct permissions for this API? The doc site (https://docs.microsoft.com/en-us/graph/api/user-getmemberobjects?view=graph-rest-1.0&tabs=cs) does not list `User.Read` or `Group.Read.All` for delegated permissions, but I see that the Markdown file (https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-getmembergroups.md) does list it.

**Comment by juho-hanhimaki** [comment]
This github issue is related to getmembergroups which should accept User.Read but it does not.
Content Source: api-reference/v1.0/api/user-**getmembergroups**.md

https://docs.microsoft.com/en-us/graph/api/user-getmembergroups?view=graph-rest-1.0&tabs=cs

It doesn't really make sense that user cannot get list of identifiers of his groups? Giving application level permissions such as Directory.Read.All increases attack surface area noticeably. So I expect the User.Read should be sufficient and the graph API is not working properly.

**Comment by juho-hanhimaki** [comment]
Some additional context:

The Microsoft Identity Platform already returns max 200 group identifiers in the ID tokens:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims

Graph API is required to query group identifiers when the user is member of more than 200 groups. Ideally this should be done with minimal *delegated* permissions such as User.Read to avoid increasing surface area for attacks.

**Comment by jasonjoh** [comment]
What I've found out is that the docs are wrong here. For delegated permissions, you need User.Read AND Group.Read.All. Directory.Read.All isn't needed if you have those two. See the pull request linked.

**Comment by juho-hanhimaki** [comment]
Group.Read.All: 
"Also allows the app to read calendar, conversations, files, and other group content for all groups the signed-in user can access."

That is far from ideal for use scenario of group based authorization (common scenario for SaaS developers). Getting permission for something like this from customer will not be easy as it exposes huge amount of information.

Additionally Group.Read.All can be used at application level. It isn't clear what can be accessed when it is used at application level.

**Comment by jasonjoh** [comment]
I hear ya. I just wanted to share how it actually works today, and to make sure our docs reflect the reality of the service. This might be something you want to file on [UserVoice](https://microsoftgraph.uservoice.com/), unless @dkershaw10 @krbain @psignoret have anything to add here.

**Comment by juho-hanhimaki** [comment]
No problem, it's good to get documentation up to date.

For the group based authorization scenario we're quite disappointed if there isn't any sensible way to implement it on Microsoft Identity platform / Graph. UserVoice request is something that we can file, but historically we've found UserVoice to be more like a graveyard for ideas rather than actual channel to discuss important issues.

**Comment by juho-hanhimaki** [comment]
UserVoice request opened at:
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/38004631-allow-signed-in-user-to-read-ad-group-memberships
