### ISSUE TITLE
/teams/{id}/channels/{id}/messages api stopped working

### ISSUE THREAD

**Issue by krchaval** [microsoftgraph/microsoft-graph-docs#3939]
Issue: /teams/{id}/channels/{id}/messages api returning UnknownError with "message": "Value cannot be null.\r\nParameter name: source"

Article:
Receiving below error when trying to access 
Request **GET** [16:16] https://graph.microsoft.com/beta/teams/{group-id-for-teams}/channels/{channel-id}/messages

Response
{
    "error": {
        "code": "UnknownError",
        "message": "Value cannot be null.\r\nParameter name: source",
        "innerError": {
            "request-id": "0416e0a4-007a-4ceb-8f7b-2e6ce6e0cbec",
            "date": "2019-02-07T10:43:11"
        }
    }
}

I am passing the required tokens. From yesterday it stopped working for me. Have the request parameters changed?

**Comment by krchaval** [comment]
We are able to retreive messages for general channel only. If we try getting messages for any other channel we are seeing this error.

**Comment by Dilden** [comment]
I've noticed issues when attempting to retrieve messages from a particular channel as well. All endpoints work fine with my given access token, but when attempting to access /teams/{id}/channels/{id}/messages the result is

```
{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "833c58a8-13bb-4096-82f6-d7bef0cdb1c9",
            "date": "2019-07-03T17:55:52"
        }
    }
}
```
