### ISSUE TITLE
Unable to fetch group photo using Application permissions

### ISSUE THREAD

**Issue by Wajeed-msft** [microsoftgraph/microsoft-graph-docs#3945]
I have consented for all required permissions and I could see them in my access token. Still I am getting 403 - "Access is denied. Check credentials and try again." while fetching profile photo. 
Error response:
```
{
  "error": {
    "code": "ErrorAccessDenied",
    "message": "Access is denied. Check credentials and try again.",
    "innerError": {
      "request-id": "74202a96-a7ff-4cbf-9fdd-588b90558f6e",
      "date": "2019-02-07T04:51:02"
    }
  }
}
```
I verified that token has required permissions:
![image](https://user-images.githubusercontent.com/31851992/52460387-058e2f00-2b90-11e9-9514-465627ee142e.png)

Please let us know if there is something I am doing wrong.

Note: This works fine with delegated permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrewwburns** [comment]
I am getting a similar 401-Unauthorized while trying to read users photos with Application permissions. However, I can read their basic profiles without any issue.

**Comment by kunalvalecha** [comment]
I am also facing the same issue. Can't get group/teams for photo using application permissions. I found that it is listed in known issues https://docs.microsoft.com/en-us/graph/known-issues . Any further update whether this has been fixed or not ?

**Comment by ibMSFT** [comment]
We are currently investigating how to add support for this. I can't give a timeline yet, as we are in the process of unpacking.

**Comment by jthake-msft** [comment]
@kunalvalecha  If you would be kind enough to add a specific feature request for this. As the status of this feature changes you will be notified.  https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?query=photo There is one there for updating photos, but not fetching them.

This github repo is for submitting issues with the content in the documentation, not the service or its feature requests.
