### ISSUE TITLE
List item attachment

### ISSUE THREAD

**Issue by sergioacortes** [microsoftgraph/microsoft-graph-docs#3959]
I am looking for a way to retrieve the documents attached to a list item propert

Could you please give some feedback

Kind regards

Sergio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f44873-e61b-3f77-e2ad-b46112b065b2
* Version Independent ID: 3ef66bdc-06cf-4356-4e1e-f4d7bed17dcb
* Content: [Get an entry from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/listitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-get.md)
* Product: **sharepoint**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by peterbunting** [comment]
I also need this functionality so that I can download attachments via the API.  This is now blocking my project, so please provide detail as soon as possible.  Many thanks.

**Comment by topmax** [comment]
any updates of this issue ?

**Comment by rafagsiqueira** [comment]
Same thing here. Any ideas?

**Comment by peterbunting** [comment]
Hi @topmax and @rafagsiqueira ,
No, i've not heard anything here.  I've had to work around this by converting my attachments into Base64 text and save them in a text field, and then undo this when accessing the data from my application.  Very annoying considering I can simply attach a file to the list item.
I'm not sure whether there will be any response from Microsoft on this?  Or how we would request this functionality?

**Comment by niels9001** [comment]
Any updates on this issue? Would like to know how to get access to the attachment.

**Comment by dveraDsi** [comment]
Is there any update concerning this issue ? I tried to find out a solution...
