### ISSUE TITLE
How to set oauth2AllowImplicitFlow

### ISSUE THREAD

**Issue by gavinwoolley** [microsoftgraph/microsoft-graph-docs#3967]
You have depreciated the value for `oauth2AllowImplicitFlow` using this API.
Can you please link to documentation on how to set this value using an API, C# or Powershell please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75124460-879c-0891-ec85-d13f51991198
* Version Independent ID: 34f50157-48f8-9c31-a1e6-66f069eb93bc
* Content: [web resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/web?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/web.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/web.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by iam4567** [comment]
Hello,
Same issue here,  I don't understand why we cannot set those values using API.. We want to automate this creation process. 

@Microsoft
Do you have solution/work around already there or for a near future regarding this capability using APIs ?
