### ISSUE TITLE
Quick Launch Menu

### ISSUE THREAD

**Issue by kiefergrylls** [microsoftgraph/microsoft-graph-docs#3968]
Hi there!
I don't know if it's the right place to ask that, but is there a way to show the list we want to create in the quick launch menu of the SharePoint site? (Like manually go in the parameters of the list, "name, description and navigation" and tick Yes for "Display the list component in the Quick Launch pane?"). I would like to do it directly with the request...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc5a9ce-652e-1dc5-c3a8-8b9e342efafb
* Version Independent ID: 04c8824e-5e0c-0086-a972-97f3a890ab47
* Content: [List - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/list.md)
* Product: **sharepoint**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by tatelang** [comment]
Is it possible to retrieve via an API call, the custom formattings for views and columns for a list?
