### ISSUE TITLE
Wrong location

### ISSUE THREAD

**Issue by martinlatrille** [microsoftgraph/microsoft-graph-docs#3970]
This article is about replying to messages, though it's located in Reference &gt; Calendar &gt; Event message; should probably be in Reference &gt; Users &gt; Mail, with the other articles regarding emails

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255b956c-6f75-2e82-acfa-f8943bfb5614
* Version Independent ID: e0782778-3134-8905-3bce-98a79fef2d51
* Content: [message: reply - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-reply.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kshitijrana** [comment]
@martinlatrille Why was this issue closed? It still hasn't been moved under the correct location.

**Comment by martinlatrille** [comment]
@kshitijrana I can't remember, I think there was an equivalent article in an appropriate place that's why, still weird to have this article in Calendar though
