### ISSUE TITLE
Wrong permission stated in documentation for Calendars.Read

### ISSUE THREAD

**Issue by sebastianzolg** [microsoftgraph/microsoft-graph-docs#3971]
Documentation states required permission is Calendar.Read which has a missing (s). 
The correct permission is Calendar**s**.Read 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6748e9-6e15-db5e-f85f-79dbe8171e9b
* Version Independent ID: a30e4438-c54b-643f-5573-c904ace73e70
* Content: [Get free/busy schedule of users and resources (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-free-busy-schedule#permissions)
* Content Source: [concepts/outlook-get-free-busy-schedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-get-free-busy-schedule.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sebastianzolg** [comment]
Any consideration? It's a simple one but could cost people a lot of time. Please update.

**Comment by shangec** [comment]
Why is Time Zone invalid? Please help me ?

**Comment by sebastianzolg** [comment]
Has this been fixed?

**Comment by shangec** [comment]
> Has this been fixed?

Yes, thank for your feedback.

**Comment by angelgolfer-ms** [comment]
@sebastianzolg , did you open this issue for an occurrence of misspelling in https://docs.microsoft.com/en-us/graph/outlook-get-free-busy-schedule?
That was fixed about a year ago. Just searched our source, there isn't another misspelling :-)

**Comment by sebastianzolg** [comment]
Thanks @angelgolfer-ms ! I just wanted to make sure the issue gets closed. Cleanup action ;-) 
Many thanks for fixing.
