### ISSUE TITLE
Add a note to show max # of results by page

### ISSUE THREAD

**Issue by CaioCavalcanti** [microsoftgraph/microsoft-graph-docs#3976]
Hi,

I think this document should include a note to show the maximum number of results by page (100 groups) and a link to [Use the api &gt; Paging](https://docs.microsoft.com/en-us/graph/paging?toc=./ref/toc.json&view=graph-rest-1.0) to show more details on how to use `@odata:nextLink`.

In one of the projects I'm working with, we didn't plan for that, during development all users we tested had just a few groups. But during QA we got users with 100+ groups and couldn't find the groups we were looking for. 

We spent some time figuring out what was going on. This could help other people avoid the issue I had 😄 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9188ffdb-b7af-597d-9e0a-d92e75ff8e7d
* Version Independent ID: c4427823-3f37-dc4b-ac1e-b750cb633e23
* Content: [List memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-memberof.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Yeah - that's a good call, and sorry for your challenges here.  We'll take a look at how we could add some details here, but to be honest you should be prepared to page results for **any** collection, and not just group memberships, but also groups, groups members, users, devices, applications, messages, etc etc.  You might also want to look at the best practices doc too.
https://docs.microsoft.com/en-us/graph/best-practices-concept

**Comment by krbain** [comment]
Unfortunately, as mentioned, this is part of best practices and something for all collections. The product team for users has no plans to address this specifically for users.
