### ISSUE TITLE
is team channel messages allowed for change notifications beta?

### ISSUE THREAD

**Issue by fkatada** [microsoftgraph/microsoft-graph-docs#3977]
Issue:  I have tried using it in https://graph.microsoft.com/beta/subscriptions
request body:
`{
  "changeType": "created,updated",
  "notificationUrl": "https://<ms flow url>/workflows/<workflow id>/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=<sig>",
  "resource": "/teams/<team id>/channels/<channel id>/messages",
  "expirationDateTime": "2019-02-13T14:00:00.0000000Z",
  "clientState": "9f15c04a-0fc2-4293-bddb-ee98cd4390e5"
}`

response: 
`{
    "error": {
        "code": "ExtensionError",
        "message": "Operation: Create; Exception: [Status Code: Unauthorized; Reason: ]",
        "innerError": {
            "request-id": "aaefd156-7a7e-4564-8dae-eaee430e369c",
            "date": "2019-02-13T13:13:49"
        }
    }
}`

**Comment by fkatada** [comment]
Guessing it wasn't enabled [yet](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta). But maybe worth a shot knowing when teams subscription for change notification would be enabled?

**Comment by ravisamani** [comment]
Our team also is waiting to subscribe to receive Channel Notifications.
Any clue when this support will be added?

**Comment by baywet** [comment]
Thanks for the feedback and sorry about the late reply.
@fkatada change notifications for teams messages (in channels or group chats) have been available for two months now.
There are two caveats thought:
- you need to include "includeResourceData" set to "true" and provide certificate information as described [here](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http#chatmessage-microsoft-teams)
- you need to get your application [approved](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http#chatmessage-microsoft-teams)

@ravisamani are you referring to notifications for messages in a channel or something else?
