### ISSUE TITLE
GET beta/education/classes Graph api does NOT return all classes

### ISSUE THREAD

**Issue by dipakboyed** [microsoftgraph/microsoft-graph-docs#3980]
Issue: 
GET classes Graph api does NOT return all classes
Article:
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/educationclass-get.md

Are there any restrictions on which groups are returned by the GET classes api? I have created a class inside Teams and have a valid GroupId for it. But GET classes api's response does NOT include it. However calling GET classes/{groupid} does work. Bug?

**Comment by bendodge-xwis** [comment]
I've noticed this behavior, too. Not 100% sure, but this might be the magic group property:
```
{
    "extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType": "Section"
}
```
Classes I've created via `POST /education/classes` do show up in `GET /education/classes`.

**Comment by mlafleur** [comment]
@WyattBest is correct. The `/education/classes` endpoint uses a query equivalent to `/groups?$filter=extension_fe2174665583431c953114ff7268b7b3_Education_ObjectType eq 'Section'`.
