### ISSUE TITLE
Permissions for reading directReports (and manager) is incorrect

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#3982]
Get direct reports (this issue is also present in the /beta docs)
1.  User.Read alone cannot be used to read directReports
2.  directReports is not supported for MSA users
3.  Reading other user's direct reports (or manager) requires User.Read.All.  Basic doesn't cut it, because report/manager is not treated as basic user profile information.

Get manager can be achieved using User.Read + User.ReadBasic.All (not listed and also a /beta issue too)

Remove manager topic is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9cc449-510b-0110-e2e7-bfa47eb4bfe5
* Version Independent ID: 4ce7f9ed-8e86-5d7b-99d5-ff5d5af5dce6
* Content: [List directReports - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-directreports?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-list-directreports.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-directreports.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
Issue has already been addressed.
