### ISSUE TITLE
Graph Explorer: Can't POST beta/applications with MSA account. Method not allowed.

### ISSUE THREAD

**Issue by carlosscastro** [microsoftgraph/microsoft-graph-docs#3983]
The graph explorer allowed me to log in with my @hotmail.com account, but then when I send a POST to /beta/applications I get a 'Method not allowed' error.

With my @microsoft.com account it just works.

What configuration do MSA accounts in general need to be able to call this endpoint?

Thanks!

**Comment by davidmu1** [comment]
Unfortunately, it is not a matter of configuring the account, it is a permission issue. Most APIs do not have permission to be run from an MSA account. You will see this often in the Permissions table:

Delegated (personal Microsoft account) | Not supported.

No change identified for the page. Closing the issue.
