### ISSUE TITLE
signalr?

### ISSUE THREAD

**Issue by FuturistiCoder** [microsoftgraph/microsoft-graph-docs#3987]
for now, there is no c# socket io client usable. how about using signalr instead of socket io?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 376b8725-b0e5-e555-aa25-c19aee7c5e5c
* Version Independent ID: 8a2e5885-7612-3850-6192-c766b61da835
* Content: [Get websocket endpoint - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-subscriptions-socketio?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/driveItem-subscriptions-socketio.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveItem-subscriptions-socketio.md)
* Product: **sharepoint**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by awash233** [comment]
aaa__aaax@hotmail.com
