### ISSUE TITLE
The documented format of the error response is not exactly the same as we get

### ISSUE THREAD

**Issue by masterjs** [microsoftgraph/microsoft-graph-docs#3988]
Issue: 
In this very useful documentation, you mention that the response of an error should be 
```
{
  "error": {
    "code": "invalidRange",
    "message": "Uploaded fragment overlaps with existing data.",
    "innerError": {
      "requestId": "request-id",
      "date": "date-time"
    }
  }
}
```
But in `innerError`, we get `request-id` instead of a `requestId` .
Can easily be tested on https://developer.microsoft.com/graph/graph-explorer/ by putting an invalid query.

Could also be nice if you could mention somewhere that the OAuth related calls do not use the same error format (https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#error-response-1).
Its minor, but I had to go back in my code to properly map it.
JS

Article:
https://docs.microsoft.com/en-us/graph/errors

**Comment by JPuzzled** [comment]
I'd like to address that the docs are unclear about the error model.

The Graph docs (https://docs.microsoft.com/en-us/graph/errors) state the following JSON object which seems to correspond with real responses from the API, except for the request id, as @masterjs noticed:
`{
  "error": {
    "code": "invalidRange",
    "message": "Uploaded fragment overlaps with existing data.",
    "innerError": {
      "requestId": "request-id",
      "date": "date-time"
    }
  }
}`

However, on the same doc page the error model is defined as:
`{
  "error": { "@odata.type": "odata.error" }  
}`

The innerError is defined as the same type:
`{
  "code": "string",
  "message": "string",
  "innererror": { "@odata.type": "odata.error" }
}`

This type does not correspond with the request-id and date properties in the real response.

Updating the docs would be nice, but the more important question is how to get the more detailed errors (innerErrors)? I did not manage to reproduce an example error with innerError yet.

**Comment by isvargasmsft** [comment]
Fixed
