### ISSUE TITLE
Typo in Response message for 403 error in Example 2

### ISSUE THREAD

**Issue by slaFFik** [microsoftgraph/microsoft-graph-docs#3996]
Currently:
> The user account which was used to submit this request does not have the right to send mail on behalf of the specified sending account., Cannot submit message.

There should be no `.,` in the end of the 1st sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61ed298-c1b2-31d1-472c-3e7b912459e9
* Version Independent ID: 1cd6a8dd-f3a9-bae9-462b-bede56d15c6c
* Content: [Send Outlook messages from another user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-send-mail-from-other-user)
* Content Source: [concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-send-mail-from-other-user.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dplotnikov** [comment]
@Lauragra please merge the PR and feel free to close this ticket
