### ISSUE TITLE
Encryption of PFX password

### ISSUE THREAD

**Issue by bb-github** [microsoftgraph/microsoft-graph-docs#4001]
Hello,

I am currently attempting to upload an S/MIME user certificate (as PKCS#12) to Intune using the Graph API operation described here.

When I correctly understand the information provided under [1], the password of the user PFX blob (see "encryptedPfxBlob" and "encryptedPfxPassword") is encrypted with another certificate/public key. According to my understanding, a new key pair must be created initially on Microsoft Intune (or somewhere else on the side of the Graph API backend). The corresponding public key can then be exported and used to encrypt the PFX password (on the side of the Graph API client). Here, the following questions arise: 

- How can I create the key pair on Microsoft Intune backend?
- Can I create it externally and upload the private key using the Intune admin portal or PowerShell?
- Is there another Microsoft documentation page that can clarify things?

Thanks a lot!

[1] https://github.com/Microsoft/Intune-Resource-Access/tree/develop/src/PFXImportPowershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57df7941-ff32-20d5-6758-683a91249cb1
* Version Independent ID: 3414a470-c21a-c882-cf2f-65556c43cec0
* Content: [Create userPFXCertificate - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-raimportcerts-userpfxcertificate-create?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/intune-raimportcerts-userpfxcertificate-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-raimportcerts-userpfxcertificate-create.md)
* Product: **intune**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by flix-** [comment]
The keypair is not created in Intune but rather on some machine that is running a certificate connector. You can e.g. generate and import a key to the machine keystore. The provider will then be "Microsoft Key Storage Provider" and the key name has to be looked up e.g. using certutil. The connector establishes a connection to MS and receives decryption requests for PKCS#12 passwords which the connector is able to decrypt by using the provided location information.

**Comment by triplanedave** [comment]
Marking closed based on flix's comments.
