### ISSUE TITLE
Unable to get user photo

### ISSUE THREAD

**Issue by teocomi** [microsoftgraph/microsoft-graph-docs#4002]
Hello, I'm getting the following when trying to get a user photo, I have tried both with the graph explorer and graph api nuget package:

```
{
    "error": {
        "code": "AuthenticationError",
        "message": "Error authenticating with resource",
        "innerError": {
            "request-id": "7ace800d-f2b5-4ac1-94bb-9fc194d037ef",
            "date": "2019-02-18T12:49:49"
        }
    }
}
```

Permissions are set to: `User.Read User.ReadBasic.All`

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
This is not the correct place to ask troubleshooting questions. Please use StackOverflow and the microsoft-graph tag. This issue list is for documentation feedback.
