### ISSUE TITLE
SupportsScopeTags in Intune Device Configuration returns 'The remote server returned an error: (400) Bad Request' 

### ISSUE THREAD

**Issue by jseerden** [microsoftgraph/microsoft-graph-docs#4003]
When "SupportsScopeTags" equals to True, I am receiving Bad Request (400) errors trying to Create or Update a Device Configuration policy. When set to false or removed from the JSON Body, the request is successful, however in the response SupportsScopeTags is always set to True.

Example:
```json
{
    "@odata.type":  "#microsoft.graph.windowsIdentityProtectionConfiguration",
    "id":  "f0ae9fd2-0dbb-4a35-83f0-a11fbfe79427",
    "lastModifiedDateTime":  "2019-02-18T12:54:49.6534521Z",
    "roleScopeTagIds":  [

                        ],
    "supportsScopeTags":  true,
    "createdDateTime":  "2019-02-18T12:54:49.6534521Z",
    "description":  "",
    "displayName":  "Windows - Windows Hello for Business",
    "version":  1,
    "useSecurityKeyForSignin":  false,
    "enhancedAntiSpoofingForFacialFeaturesEnabled":  true,
    "pinMinimumLength":  8,
    "pinMaximumLength":  16,
    "pinUppercaseCharactersUsage":  "blocked",
    "pinLowercaseCharactersUsage":  "blocked",
    "pinSpecialCharactersUsage":  "blocked",
    "pinExpirationInDays":  null,
    "pinPreviousBlockCount":  null,
    "pinRecoveryEnabled":  false,
    "securityDeviceRequired":  true,
    "unlockWithBiometricsEnabled":  true,
    "useCertificatesForOnPremisesAuthEnabled":  false,
    "windowsHelloForBusinessBlocked":  false
}
```

```powershell
$Uri = "https://graph.microsoft.com/$ApiVersion/deviceManagement/deviceConfigurations"
Invoke-RestMethod -Uri $Uri -Headers $AuthHeaders -Body $Json -Method Post
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8086837-0b5d-5615-5025-fcc3e31be96e
* Version Independent ID: 63ddbaad-52ed-eba1-9bd8-5f2972697b34
* Content: [Create windows10GeneralConfiguration - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-windows10generalconfiguration-create?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-deviceconfig-windows10generalconfiguration-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-deviceconfig-windows10generalconfiguration-create.md)
* Product: **intune**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rolyon** [comment]
Hi @jseerden 
Thanks for the feedback. This is a read-only property used to identify if scope tags are supported on an existing type/object.  This is not something that can be set.
thanks

**Comment by rolyon** [comment]
If you have additional feedback, please reopen this issue.
thanks
