### ISSUE TITLE
Request to add a sharepoint library linked tab in Teams : Error 500

### ISSUE THREAD

**Issue by kiefergrylls** [microsoftgraph/microsoft-graph-docs#4005]
I'm doing exactly what's described [here](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#document-library-tabs) to add a document library tab to a Teams channel (providing the link the root folder of the document library concerned, entityId set to an empty string :
![image](https://user-images.githubusercontent.com/32267729/53004092-b9b17480-3430-11e9-8a61-e4e48f3035ab.png)

But the response is a 500 internal server error :
![image](https://user-images.githubusercontent.com/32267729/53004141-da79ca00-3430-11e9-9dcd-803c5d78f1d7.png)

I tried several combinations with the configuration parameters, but it never works. I am thinking that it's a graph API sided problem?

EDIT: I managed to make it worked on graph explorer, but still not on Postman. Might the problem come from the fact that graph uses a user token, whereas, in postman, I want to do this via application token?

**Comment by phillipharding** [comment]
Today I tried adding a Document Library tab to a Team Channel using the **v1.0** and **beta** endpoints using the request body below - creating Tabs of other kinds (Stream, Forms, Site etc) works fine.
```
{
  "displayName": "Document%20Library%20Tab",
  "teamsApp@odata.bind" : "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.files.sharepoint",
  "configuration": {
    "entityId": null,         // also tried "" instead of null
    "contentUrl": "https://tenant.sharepoint.com/sites/site/doclib",
    "removeUrl": null,
    "websiteUrl": null
  }
}
```
Which returns a **GeneralException** response
```
{
    "error": {
        "code": "GeneralException",
        "message": "Object reference not set to an instance of an object.",
        "innerError": {
            "request-id": "request guid",
            "date": "2019-03-13T12:28:04"
        }
    }
}
```

**Comment by nkramer** [comment]
Thanks for pointing this out, I've opened a bug for this.

**Comment by phillipharding** [comment]
Is there any update on this?

**Comment by mdissel** [comment]
Any updates?

**Comment by kiefergrylls** [comment]
Any news on Microsoft side ?

**Comment by phillipharding** [comment]
@nkramer is there any progress on this issue?

**Comment by nkramer** [comment]
The fix has been deployed.

**Comment by mdissel** [comment]
So now it's possible to use an application-only access token?

**Comment by nkramer** [comment]
Yes.

**Comment by phillipharding** [comment]
Thanks @nkramer 
Adding a SharePoint Library Tab via an App-Only access token confirmed working today on the ```v1.0``` and ```beta``` endpoints.
