### ISSUE TITLE
Mail send notification

### ISSUE THREAD

**Issue by Misiu** [microsoftgraph/microsoft-graph-docs#4006]
I need to store DateTimeSend of the email message that is sent via my app. Currently, I send mail, wait few seconds and then I check if the email with specific extended property exists in SentItems folder. This works fine but is slowing down the whole process, because  I must wait before I check. I'd like to use notifications (webhooks) to remove the check from my app and have Outlook notify me when mail was sent.
To what notification I should subscribe? changeType: created and sentitems as a resource? Won't this also get called for drafts? I need to be 100% sure the mail was sent.
Is there a dedicated notification that can be used to know when mail was sent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: **non-product-specific**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Misiu** [comment]
Any comments?

**Comment by jasonjoh** [comment]
Sorry for the delay. This isn't really a support channel, issues here are meant to be for issues with the documentation.

No, there is no notification for send. You could listen for notifications on Sent Items and ignore any items that have `isDraft` set to true (or if `sentDateTime` is not set).

**Comment by Misiu** [comment]
@jasonjoh thank You for the reply and sorry for posting question here. I was hoping this kind of notification is possible and that is isn't listed in docs.

I'll try Your suggestions.

**Comment by Misiu** [comment]
I've created a feature request for this type of notifications: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/36957805-webhook-email-send-notification.

**Comment by TzachiF** [comment]
Hi, I see that you introduced Mail.ReadBasic permission but the it is not reflected in the notifications permission table. Is it going to be supported? Thanks
