### ISSUE TITLE
Flag Status property is missing in "Request body" properties

### ISSUE THREAD

**Issue by thatapiguy** [microsoftgraph/microsoft-graph-docs#4007]
I am able to change the flag status property of the message using the update message request and using this in the body - 
{
  "flag": {
    "flagStatus": "complete"
  }
}
However, it's not listed in the properties that can be modified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6afe5d0-80cb-88c6-3deb-299f9688aa9b
* Version Independent ID: 4539753e-3fdc-e631-94c3-f017ee2e55a0
* Content: [Update message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/message-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-update.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @thatapiguy , thanks for pointing this out. FYI I updated the v1 and beta versions of the "update message" topic to include the flag property in PR #4009 . The topics should be updated in the live site within the next day.

Thank you for your continued support!

**Comment by thatapiguy** [comment]
Thank you! That was super quick!
