### ISSUE TITLE
how to send a message with a attachment for file content type ?? 

### ISSUE THREAD

**Issue by Allauvdheenbasha** [microsoftgraph/microsoft-graph-docs#4008]
i couldn't post the message with attachments for any content types, then followed documentation. still, i couldn't send message with attachment. help me out with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d57683-3c22-8f3f-e547-f77d9470ce6e
* Version Independent ID: 9919200f-9f53-b6bb-bc6e-4b9c32e0811d
* Content: [chatMessageAttachment resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatattachment?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatAttachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatAttachment.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
can you please ask this troubleshooting question on stackoverflow please using microsoft-graph tag. feedback on docs is meant to be specifically about the content in the docs, not troubleshooting questions.
