### ISSUE TITLE
Receiving 404 error while trying to apply access reviews

### ISSUE THREAD

**Issue by ramadongre** [microsoftgraph/microsoft-graph-docs#4011]
With right amount of permissions, i still get 404 error while applying access reviews using ms graph api.

I have posted detailed question on stack-overflow as below.

https://stackoverflow.com/questions/54776833/microsoft-graph-api-access-review-apply-decisions-returning-404

Any feedback will be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6571262f-c66a-0f90-1cc5-fdb69b3b6446
* Version Independent ID: d0a6d287-d97c-f0a9-a20d-08c0f65b70ee
* Content: [Apply accessReview - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accessreview-apply?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/accessreview-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accessreview-apply.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
The stackoverflow page is not available any more.
