### ISSUE TITLE
Unable to create more than one policies for a particular tenant with E5 License

### ISSUE THREAD

**Issue by PavithraTamizh** [microsoftgraph/microsoft-graph-docs#4013]
I'm new to Microsoft Graph and I am doing a project using Graph API's .
There is an existing policy for my tenant. When I tried creating a new policy for the same tenant, I got the following error.
Error : Tenant already has maximum allowed 1 policy
Exception Message : Error in validating lifecycle manangement policy
Exception Code :  MaxExpirationPoliciesCountReached
Exception Type : Microsoft.Graph.ServiceException

In the Response body of [List groupLifecyclePolicies](https://docs.microsoft.com/en-us/graph/api/grouplifecyclepolicy-list?view=graph-rest-1.0) document, the value is an Array []. Is it possible to create more than one policies for a tenant.

Thanks in advance..!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b2ea434-6141-1644-1849-b1c2d71d18f9
* Version Independent ID: 6745ed22-838b-060f-5229-60115d401a4e
* Content: [List groupLifecyclePolicies - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/grouplifecyclepolicy-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/grouplifecyclepolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/grouplifecyclepolicy-list.md)
* Product: **groups**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HN5** [comment]
Hi, I face same issue

I'm not able to add more than 1 policy

{
    "error": {
        "code": "MaxExpirationPoliciesCountReached",
        "message": "Error in validating lifecycle manangement policy. Error: Tenant already has maximum allowed 1 policy(s).",
        "innerError": {
            "request-id": "1f557bc9-1343-4ffc-a7db-92897d491610",
            "date": "2019-03-05T08:58:43"
        }
    }
}

Any workarround for this ?
Thx for help :)

**Comment by HN5** [comment]
@PavithraTamizh  i think i found an explanation .... : according to this doc : https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-lifecycle

> Currently only one expiration policy can be configured for Office 365 groups on a tenant.

 Note

Configuring and using the expiration policy for Office 365 groups requires you to have on hand Azure AD Premium licenses for all members of the groups to which the expiration policy is applied.
