### ISSUE TITLE
Example incorrect?

### ISSUE THREAD

**Issue by ScaleOvenStove** [microsoftgraph/microsoft-graph-docs#4014]
when the example is listed above, it is calling 

POST https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages/{id}/messages

but I think it should be /replies instead of /messages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78d7f28-2ac1-bdc1-4ac5-3a20756270be
* Version Independent ID: 353e1a63-1ae9-201a-4ac2-8949b164788f
* Content: [Reply to a message in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messagereply.md)
* Product: **microsoft-teams**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jagrock** [comment]
Using /replies i get the responses:  Invalid request body was sent.

**Comment by nkramer** [comment]
/messages => /replies was fixed a while ago.
