### ISSUE TITLE
Delta Query for Azure AD B2C

### ISSUE THREAD

**Issue by sirjameswood** [microsoftgraph/microsoft-graph-docs#4018]
I am trying to use a Graph delta query to find changes in users within an Azure AD B2C tenant.

For example:

`GET https://graph.microsoft.com/v1.0/users/delta`

Which results in:

`Request_UnsupportedQuery Change enumeration is not supported for requested tenant.`

What is a supported tenant? Should this work for Azure AD B2C?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cvrtaw** [comment]
Same issue here, noticeably it worked just a bunch of times. I was debugging, I called it 1 time, I followed the NextLink a bunch of times, I retrieved something like 300 user changes, after that the call stopped working and never worked again.

If it helps, I'm accessing Azure AD Graph API+B2C using Microsoft Graph authentication

**Comment by dkershaw10** [comment]
Sorry for the delayed response. I don't think delta query is currently supported on Azure B2C tenants. @piotrci please confirm.

**Comment by ashoksubedi1** [comment]
Hello,  Once I go through the changes given by the previous delta link, I have been saving the new delta links into the database all I want to know is the expiry life period of those new received delta link. Because I want to run the script to renew delta link only when it is about to expire for capturing changes

**Comment by baywet** [comment]
@dkershaw10 that's my understanding as well. Closing to suggest people to post the feature request to uservoice https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/38934121-allow-notification-for-user-registration-creation
