### ISSUE TITLE
Azure AD B2C Set Authentication Contact Info Email Address

### ISSUE THREAD

**Issue by sirjameswood** [microsoftgraph/microsoft-graph-docs#4019]
I am trying to programmatically update the Authentication Contact Info email address for a contact created using Azure AD B2C.

I have attempted to do this via the Microsoft Graph API, but failed. For example; 

```
PATCH /users/{id}
{
       "givenName": "James12344",
       "mail": "james@wood.com"
}

```
Which results in:

```
Property 'mail' is read-only and cannot be set
```

How can I programmatically set this field?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae97ef5-d7e5-3934-6323-1bcff216f4fb
* Version Independent ID: 1ed620e1-cb79-dda3-2c18-30791ec9e15a
* Content: [Working with users in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/users.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by pjbrigden** [comment]
I am also encountering this issue, is this simply a feature that only Azure AD Graph supports for now?

**Comment by ashemedai** [comment]
Late to the party, but everything I have checked so far seems to indicate that B2C support in Microsoft Graph is at bare minimum and one should still use the Azure AD Graph API if you need to manage users and such for B2C.

**Comment by TheMagnificent11** [comment]
I've found that the "mail" property is not set when the user is created via Azure B2C registration.

Viewing the user in the Azure portal shows the email address as "sign-in name" or "user name".  However, these properties are not accessible on the Graph User object.

I've been told that using the REST API directly allows you to access the email address as the first "signInNames" (apparently it's an array on user object).

**Comment by krbain** [comment]
The mail property is read-only, so it cannot be updated for a user. B2C support in MS Graph is minimal, however, you can check out https://docs.microsoft.com/en-us/graph/api/resources/objectidentity?view=graph-rest-1.0 which may be helpful.
