### ISSUE TITLE
Why are there two Ids

### ISSUE THREAD

**Issue by findyoucef** [microsoftgraph/microsoft-graph-docs#4021]
Why are theyre GUID ids. What is the difference??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d792f6b-8c07-bb1e-1d8c-f0f779951e0b
* Version Independent ID: dd1aa2b5-55fa-9114-7bf4-6dd0b887d1ca
* Content: [Get a SharePoint Site - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/site-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get.md)
* Product: **sharepoint**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by TobiasAT** [comment]
The format of the IDs is {hostname},{spsite-id},{spweb-id}.

**Comment by KoalaBear84** [comment]
Indeed. Here is an official note about it (See "Note for existing SharePoint developers"):
https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0

**Comment by umutge** [comment]
Site Id object explained here: https://docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta#id-property

**Comment by BrianTJackett** [comment]
@findyoucef Do the above responses answer your question?  If so please consider closing the issue.

**Comment by FaithOmbongi** [comment]
No additional feedback from @findyoucef or updates identified for the page. Closing the issue.
