### ISSUE TITLE
Why are settings returns as JSON strings?

### ISSUE THREAD

**Issue by MysticRyuujin** [microsoftgraph/microsoft-graph-docs#4025]
This is the only Privileged Identity Management API function I've come across where the settings are provided as JSON strings instead of just JSON objects. It seems unnecessarily complex to force conversion to/from JSON strings for settings that are already in JSON format...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c246b7a-a74d-d45c-13b8-34a56baab232
* Version Independent ID: ff8afd61-e389-6ec6-8609-4adf499bf93b
* Content: [List governanceRoleSettings - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governancerolesetting-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/governancerolesetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governancerolesetting-list.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
