### ISSUE TITLE
Programatically creating an online meeting

### ISSUE THREAD

**Issue by taaoo75** [microsoftgraph/microsoft-graph-docs#4033]
Although the documentation mentions "online meeting", it does not tell us how to programmatically schedule an event that "is" an online meeting? Can it be done? How?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41a9857-98a9-e400-d7ce-bd7c0f37cd46
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/event.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @taaoo75 , that's correct, the onlineMeetingUrl property of the event entity is useful once the event has already been set as an online meeting. Currently, you cannot set that property to create an online meeting in the Outlook calendar.

**Comment by JonasDewit** [comment]
@angelgolfer-ms , sorry to comment even though this issue is closed, but do you have an idea about when this will be available? The IsOnlineMeeting property that is currently available in beta allows this, so the question is when will this go to GA?

**Comment by angelgolfer-ms** [comment]
@Harini84 , is there a reliable timeline yet for bringing the online meeting API to v1?

**Comment by Harini84** [comment]
@angelgolfer-ms 
PR for Graph changes to make onlinemeeting available already raised by @sochowdh : 
https://microsoftgraph.visualstudio.com/onboarding/_git/AGS-OnboardingAutomationPipeline/pullrequest/3218?_a=overview

It is waiting for approval from Graph team.

Thanks

**Comment by angelgolfer-ms** [comment]
@JonasDewit , isOnlineMeeting is now available in v1 as well: https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0

Thanks for your patience!

**Comment by JonasDewit** [comment]
hi @angelgolfer-ms, thank you very much for the update!

**Comment by YasiruUOK** [comment]
Hi @angelgolfer-ms, But when using it in C#, it give a compile error, reason is Event does not contain the definition of   isOnlineMeeting
