### ISSUE TITLE
Portal Link Broken?

### ISSUE THREAD

**Issue by largeDachshund** [microsoftgraph/microsoft-graph-docs#4035]
This link:  Microsoft App Registration Portal resolves to one's Microsoft Account.  I see the url: apps.dev.microsoft.com.  Not sure why it lands at account.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Hi @largeDachshund, thanks for raising this issue. I've confirmed that all three links to the app registration portal on the page have the correct URLs and are currently resolving correctly. Closing the issue.
