### ISSUE TITLE
Same as info from the portal?

### ISSUE THREAD

**Issue by dcbrown16** [microsoftgraph/microsoft-graph-docs#4038]
Would the information obtained through the Graph API for audit and sign-in logs be the same as the info that can be downloaded from the Azure portal (assuming the same time period and access)?
Just wondering if there are any differences in the underlying mechanism (such as API versions) that might make that different (I have seen this with Azure activity logs in the Portal vs PowerShell).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 880b9e7b-6ecc-69fa-035c-98a5ebbea632
* Version Independent ID: b9f3185c-1406-e1eb-99b8-edbc84c4e58a
* Content: [Azure AD audit log API overview - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/azure-ad-auditlog-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/azure-ad-auditlog-overview.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
