### ISSUE TITLE
messageType?

### ISSUE THREAD

**Issue by dni128** [microsoftgraph/microsoft-graph-docs#4040]
What exactely is the meaning of: The type of message, currently supported values are: message, chatEvent, Typing? I can't seem to find any information about the diffenent types...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f046b37e-8569-b617-4c9b-402342d4bef9
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessage.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
We've removed documentation about the types that aren't actually supported.

**Comment by pravin-cyclotron** [comment]
Can you please tell me how to post a link to chat using graph API since there is no messageType defined? We can post a normal message to chat easily but I didn't get a way where we could post a link to chat.
