### ISSUE TITLE
Timeline for GA release

### ISSUE THREAD

**Issue by JSOnions** [microsoftgraph/microsoft-graph-docs#4050]
Hi

Is there any roadmap / timeline for the GA release of BETA APIs, specifically these Autopilot device assignment ones.

Thanks
JS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef346228-d627-60f3-9796-3258c811eabf
* Version Independent ID: 6f55e368-fca9-2f2b-15d9-6c0a66e0500e
* Content: [assignUserToDevice action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-windowsautopilotdeviceidentity-assignusertodevice?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-enrollment-windowsautopilotdeviceidentity-assignusertodevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-windowsautopilotdeviceidentity-assignusertodevice.md)
* Product: **intune**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ShiChen872** [comment]
We would like to know the same thing.   when will you move beta feature to GA or V2?

**Comment by triplanedave** [comment]
Generally, the feature owners will move to GA when they know they've had sufficient time to validate the API with customers & partners.  Sometimes the move to GA is longer if we know that there are pending changes for that particular API.  The best way to know updates is to watch the Graph changelog.
