### ISSUE TITLE
Does Create App Registration (/beta/applications) API work for CSP users?

### ISSUE THREAD

**Issue by crpietschmann** [microsoftgraph/microsoft-graph-docs#4051]
I have a Azure AD user that's a CSP user. When I get an Auth Token from Azure AD for the CSP user and then try to use this API to create a new App Registration in a CSP Azure Subscription it always returns "400 Bad Request"

Here's the JSON I'm POSTing to the `/beta/applications` REST API:

    {"allowPublicClient":true,"displayName":"devopsautomation"} 

And here's the HTTP response from the API:

    { "error": { "code": "Request_BadRequest", "message": "One or more property values specified are invalid.", "innerError": { "request-id": "b2ac87da-2279-4ca7-ad81-95904aeb116a", "date": "2019-02-26T01:41:08" } } } 

This appears to be a bug in the API when a CSP user is attempting to create an App Registration in an Azure Subscription that is managed under the CSP. For greater context, a call to Delete an App Registration works fine. It's just the Create that is broken and returning this error message when it shouldn't be.

Also, a CSP user can login to the Azure Portal for the given Azure Subscription and create a new App Registration within Azure AD using the portal. It seems that the REST API just isn't working.

Any advice on a work around to get the REST API to work?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9081788-2993-0621-059d-e686ea9ae5cb
* Version Independent ID: 6260abb6-0adf-241d-23d8-78632ee20b3f
* Content: [Create Application - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/application-post-applications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-applications.md)
* Product: **microsoft-teams**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nromyn** [comment]
I am also seeing this behaviour, and I am not in a CSP situation. I am able to create an application only including DisplayName, but I then cannot see it in the Portal.

**Comment by dkershaw10** [comment]
@sureshja You need to update the create scenario/example as the `allowPublicClient` property no longer exists.

**Comment by MaxHogervorst** [comment]
Any news on this?

**Comment by davidmu1** [comment]
allowPublicClient is not available in MS Graph. Look at isFallbackPublicClient to configure the public client as default app type. No change identified for the page. Closing the issue.
