### ISSUE TITLE
Where to find "id"

### ISSUE THREAD

**Issue by sbalogunpcgus** [microsoftgraph/microsoft-graph-docs#4060]
what is meant above where it says 
"Note: The "id" in the request is the "id" property of the device, not the "deviceId" property."

Where do i find this "id"? I am trying to run a simple query in graph explorer and have used Intune Device ID and Azure AD device ID and keep getting error code "Request_ResourceNotFound".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b83431a-943d-3f37-b2c3-67061a16cd3c
* Version Independent ID: 14c425d1-40e6-b37e-d327-322933054866
* Content: [Get device - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/device-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/device-get.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sbalogunpcgus** [comment]
I got a 200 OK when I used the objectid, which i got from a get-azureaddevice -searchstring "computername" PowerShell command.

**Comment by stevep4** [comment]
You'd want to use something like:

https://graph.microsoft.com/v1.0/devices?$filter=deviceId eq '{Azure AD Device ID GUID}'
