### ISSUE TITLE
"_Crop" is casesensitive and should be lowercase

### ISSUE THREAD

**Issue by martinvillysson** [microsoftgraph/microsoft-graph-docs#4063]
If you use "_Crop" with a capital C you get this error: "Unsupported options were provided in the thumbnail descriptor."
However use a lowercase "c" and it will work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 493fd563-8a90-df7d-1373-80e82b18f8ee
* Version Independent ID: 62d1050e-1a7d-8167-f7a1-8f139d07af9c
* Content: [Retrieve thumbnails for a file or folder - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-list-thumbnails?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/driveitem-list-thumbnails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-list-thumbnails.md)
* Product: **sharepoint**
* GitHub Login: @rgregg
* Microsoft Alias: **rgregg**

**Comment by isvargasmsft** [comment]
Hello @martinvillysson, 

My deepest apologies for the delays in our response. Thank you for reporting this issue.

Fixing this issue tight away. 

Kind regards, 

Isaac
