### ISSUE TITLE
Patch Channel topic not present TOC

### ISSUE THREAD

**Issue by nikrampi** [microsoftgraph/microsoft-graph-docs#4065]
Page is not present under "Teamwork/Channel" tree on left menu.
Moreover example points to /beta/ endopoint even if browsing on v1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20375f61-c4bc-be33-18b9-d494f359ff5a
* Version Independent ID: bc912754-3388-4cc0-90cc-df7164a78fc1
* Content: [Patch channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-patch.md)
* Product: **microsoft-teams**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by DeanGross** [comment]
The above comment is accurate, when will it be addressed by the content authors?

**Comment by Lauragra** [comment]
@clearb, can you look into this please? @nkramer , FYI.
