### ISSUE TITLE
Wrong request example in docs

### ISSUE THREAD

**Issue by denispo3** [microsoftgraph/microsoft-graph-docs#4066]
You provided copy of response in place where request example is supposed to be

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ff7ff9f-c955-c32f-756c-59e9165f3fa3
* Version Independent ID: c181ecf0-6586-9b36-20a8-f2f1e1381397
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-post-events.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @denispo3 , thank you for your feedback. We have been aware of the general issue - where there are pseudo examples (like this case), the example request payload may not contain the typical properties and give the impression it's the response payload.
For this API to create an event in a specific calendar, PR #4070 has replaced the pseudo examples:
https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0#example
https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-beta#example

We are continuing to work on improving the overall code example experience. Thank you for your patience!
