### ISSUE TITLE
Spelling error in meetingTentativelyAccepted

### ISSUE THREAD

**Issue by frennkie** [microsoftgraph/microsoft-graph-docs#4069]
The letter **t** is missing in `meetingTenativelyAccepted`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13f88fa7-c026-e9c1-a2d2-a5979243b221
* Version Independent ID: acc57ef0-932c-42b0-5227-6237710c9cf8
* Content: [eventMessageRequest resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/eventmessagerequest?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/eventmessagerequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/eventmessagerequest.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frennkie** [comment]
This is not only a mistake in the documentation. The API actually returns the value with the typo `meetingTenativelyAccepted` !

**Comment by angelgolfer-ms** [comment]
Hi @frennkie , thanks for pointing that out! FYI PR #4070 fixed this issue. The fixes are live:

- [eventMessageRequest (beta)](https://docs.microsoft.com/en-us/graph/api/resources/eventmessagerequest?view=graph-rest-beta#properties)
- [eventMessage (v1.0)](https://docs.microsoft.com/en-us/graph/api/resources/eventmessage?view=graph-rest-1.0#properties)
- [eventMessage (beta)](https://docs.microsoft.com/en-us/graph/api/resources/eventmessage?view=graph-rest-beta#properties)

Thanks for your support!

**Comment by angelgolfer-ms** [comment]
@frennkie , can you elaborate exactly which API you called please?

**Comment by frennkie** [comment]
@angelgolfer-ms `https://graph.microsoft.com/v1.0/me/messages/A[....]A=` - is that sufficient information?

**Comment by angelgolfer-ms** [comment]
Hi @frennkie , you mean when you did a GET operation on a specific message? 
And you probably used beta and not the v1 endpoint? (That enum member is defined only for beta, AFAIK.)

Please confirm. Thanks.

**Comment by frennkie** [comment]
@angelgolfer-ms I had to double check because normally I use a python library [python-o365](python-o365).

But this can simply be verified using https://developer.microsoft.com/en-us/graph/graph-explorer

There I request https://graph.microsoft.com/v1.0/me/messages from the V1.0 API and the error is present. Here is a screenshot:

![msgraphtentatively](https://user-images.githubusercontent.com/6499251/53680721-9ebbeb80-3cdf-11e9-9248-9c1b83c54acf.png)

**Comment by svpsiva** [comment]
This is a known issue. There is no plan to fix the same as existing clients might break.

**Comment by frennkie** [comment]
@angelgolfer-ms have you reversed the change to the documentation?

@svpsiva any chance to fix this in future versions?

**Comment by angelgolfer-ms** [comment]
@frennkie , thanks for the clarification. 
Sorry I got the (mis)impression from the initial feedback that you had noticed the problem when accessing the beta resource, eventMessageRequest, as the feedback came through that [page ](https://docs.microsoft.com/en-us/graph/api/resources/eventmessagerequest?view=graph-rest-beta#feedback) for eventMessageRequest. 

Yes, I can see at the API level, when doing a GET message in v1, if the message is a tentative response to a meeting request, the meetingMessageType property shows the misspelt value "meetingTenativelyAccepted".

FYI, PR #4089  has made the docs for v1 reflect the misspelt value "meetingTenativelyAccepted". So from the perspective of consistency across the API, metadata, and docs, they are all consistent (consistently misspelling the enum value :-|).

And to clarify, for beta, the docs and metadata currently reflect the correct spelling "meetingTentativelyAccepted". I will request the product team to verify the behavior and spelling from the API.
