### ISSUE TITLE
How do you filter by file type with OneDrive files?

### ISSUE THREAD

**Issue by jimbarrett33** [microsoftgraph/microsoft-graph-docs#407]
The $filter and search examples don't cover this.  Is it possible?

Thanks.

**Comment by OneDriveAutomation** [comment]
@jbarr33 It's not really possible today. OneDrive for Business doesn't the depth of $filter syntax necessary to make this work. It's on our backlog though.

**Comment by jbarr33** [comment]
OK.  Thanks for the reply.  If you have any workarounds to find only Excel files and that "contains" a match on file name please let me know. Currently, I am using search with an AND like below but it doesn't work that well because search doesn't always (or at all) match on file name.

`https://graph.microsoft.com/v1.0/me/drive/root/search(q='<name filter>%20AND%20.xlsx')`

**Comment by jaycdave88** [comment]
Has there been any progress on this?

**Comment by bora89** [comment]
Guys, about 2 years passed, NO progress has been made. It is just ridiculous how careless you can be. Either fix it or [remove from the documentation that it is possible](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results)

**Comment by isvargasmsft** [comment]
Hello!

My deepest apologies for the delays addressing this thread. 

Unfortunately, while the [OneDrive API does support filters](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online#filterable-properties) on any property, support for filter operators varies across Microsoft Graph APIs. [Here the list of generally supported logical operators](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter) in Microsoft Graph. 

Additional documentation for reference: [Optional query parameters | List children of a driveItem](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#optional-query-parameters)

Hope this clarifies and my sincere apologies for the inconveniences this may cause. We take your feedback in consideration for future upgrades of the service. 

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at Microsoft Q&A: [Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).

Best regards!

Isaac Vargas
