### ISSUE TITLE
Inconsistency in available / required API permissions between this document and Azure Portal

### ISSUE THREAD

**Issue by robinmalik** [microsoftgraph/microsoft-graph-docs#4081]
This document may be correct in stating that the 'Application' permission type is not supported for listing conversations from an Office 365 Group. However, when editing the API permissions for an application in the Azure Portal, I am able to select 'Group.ReadWrite.All' and grant admin consent. The mouseover description for this is: 'Allows the app to create groups, read all group properties and memberships, update group properties and memberships, and delete groups. Also allows the app to read and write group calendar and conversations. All of these operations can be performed by the app without a signed-in user.'. So it would suggest that I should be able to list conversations, but when I try it returns an error 403 forbidden. If I use the Graph Explorer as a signed in user, the query works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08b0bfa2-3b0e-6d33-c6ec-5b3f7cedf77c
* Version Independent ID: f59ae5d3-4c81-42c7-29a5-965fe36df83b
* Content: [List conversations - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-list-conversations?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/group-list-conversations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list-conversations.md)
* Product: **groups**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ardymalihi** [comment]
The same issue. Cannot access conversation(s) and I have Group.Read.All, Group.ReadWrite.All access

**Comment by benstoneham** [comment]
Same issue here.. very irritating...

**Comment by VayaCh** [comment]
I have this issue too. Any updates?

**Comment by AudunWangen** [comment]
Same here. Documentation needs to be updated, or the API needs to be fixed.

**Comment by davidmu1** [comment]
This seems to have been updated. This is now listed in the page:

Application | Group.Read.All, Group.ReadWrite.All

No change identified for the page. Closing the issue.
