### ISSUE TITLE
Create Scheduled online meeting request sample

### ISSUE THREAD

**Issue by oserdiuk** [microsoftgraph/microsoft-graph-docs#4082]
What is the valid format for scheduling online meetings? 

I'm trying to create a scheduled meeting. The request is valid according to onlinemeeting object.
{
   "meetingType":"scheduled",
   "subject":"Meeting",
   "startDateTime":"2019-03-04T16:21:36Z",
   "endDateTime":"2019-03-04T16:35:36Z",
   "participants":{
      "organizer":{...},
      "attendees":[...]
   }
}

But the API throws the error, that I should specify the organizer. After I insert organizer into onlinemeeting object, another error is thrown: "onlinemeeting cannot be null". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create online meeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **microsoft-teams**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
@oserdiuk What is the scenario that you are trying to achieve? Are you trying to authenticate the request with User token?

**Comment by oserdiuk** [comment]
@VinodRavichandran 
Hi,
I'm trying to schedule a meeting for a group of people. As I understand, there are multiple types of meetings: meet now and scheduled.
When I send a request to create meetnow meeting with body like this:
{
  "meetingType": "meetNow",
  "participants": {
    "organizer": {
  "identity": {"user":{"id":"3fc30878-9cfe-4436-bb68-0875484be16c"}},
  "upn": "Oksana Serdiuk"
    }
  },
  "subject": "subject-value"
}

It's created a meeting successfully. When I change type like this:
{
  "meetingType": "scheduled",
  "participants": {
    "organizer": {
  "identity": {"user":{"id":"3fc30878-9cfe-4436-bb68-0875484be16c"}},
  "upn": "Oksana Serdiuk"
    }},
  "subject": "subject-value"
}
It throws Organizer - User/App instance id missing.
Then I moved Organizer out of Participants object
{
  "meetingType": "scheduled",
 "organizer": {
  "identity": {"user":{"id":"3fc30878-9cfe-4436-bb68-0875484be16c"}},
  "upn": "Oksana Serdiuk"
    },
  "subject": "subject-value"
}
And I've got an exception: 
{
    "error": {
        "code": "UnknownError",
        "message": "{\"message\":\"onlinemeeting cannot be null.\"}",
        "innerError": {
            "request-id": "01b3f4cc-50dd-4f5a-8ceb-3767b8cf5756",
            "date": "2019-03-06T09:43:33"
        }
    }
}

**Comment by hafarey** [comment]
I'm getting the same error.  It's been a couple of months since I've tried this request.  The last time I tried it, I remember seeing a note from Microsoft about the other `meetingType` values being not yet supported.  Alas, I can't find where I saw that note.

**Comment by oserdiuk** [comment]
@VinodRavichandran 
I would really appreciate if you could provide a valid example of json for scheduling a live event. It would be so helpful.

**Comment by VinodRavichandran** [comment]
@oserdiuk @hafarey  By 'live event', I believe you mean broadcast meeting? From a experience perspective, are you having thinking of having your App call our APIs and get returned a meeting URL? If yes, that will be supported in  next quarter. Also, I'm assuming you are using Application auth token and not Client auth?

**Comment by oserdiuk** [comment]
Thank you for your answer.

> By 'live event', I believe you mean broadcast meeting?
Yes, I mean broadcast meeting. I suppose that it is called "live event" in Teams application.

> From a experience perspective, are you having thinking of having your App call our APIs and get returned a meeting URL?
Yes, my goal is to make a bot who should help a user to create a meeting for a large group of people, send invitations and it should participate in those meetings. So I want to call your API to create a meeting and get the URL.

> Also, I'm assuming you are using Application auth token and not Client auth?
I've created a registered application, given them all the required permissions, and I use its credentials for retrieving an access token. But I guess that wasn't my problem, because one of my requests has worked and created a "meetnow" meeting.

**Comment by VinodRavichandran** [comment]
@oserdiuk  We are targeting the above scenario by end of next quarter, so June/July.

**Comment by ogarules** [comment]
> Thank you for your answer.
> 
> > By 'live event', I believe you mean broadcast meeting?
> 
> Yes, I mean broadcast meeting. I suppose that it is called "live event" in Teams application.
> 
> > From a experience perspective, are you having thinking of having your App call our APIs and get returned a meeting URL?
> 
> Yes, my goal is to make a bot who should help a user to create a meeting for a large group of people, send invitations and it should participate in those meetings. So I want to call your API to create a meeting and get the URL.
> 
> > If yes, that will be supported in next quarter.
> 
> Do you mean April by next quarter?
> 
> > Also, I'm assuming you are using Application auth token and not Client auth?
> 
> I've created a registered application, given them all the required permissions, and I use its credentials for retrieving an access token. But I guess that wasn't my problem, because one of my requests has worked and created a "meetnow" meeting.

I'm on the same scenario and facing the same issue, it's successful when is of type meetnow, otherwise tells me Organizer - User/App instance id missing, have you found any workaround ?

**Comment by oserdiuk** [comment]
> > Thank you for your answer.
> > > By 'live event', I believe you mean broadcast meeting?
> > 
> > 
> > Yes, I mean broadcast meeting. I suppose that it is called "live event" in Teams application.
> > > From a experience perspective, are you having thinking of having your App call our APIs and get returned a meeting URL?
> > 
> > 
> > Yes, my goal is to make a bot who should help a user to create a meeting for a large group of people, send invitations and it should participate in those meetings. So I want to call your API to create a meeting and get the URL.
> > > If yes, that will be supported in next quarter.
> > 
> > 
> > Do you mean April by next quarter?
> > > Also, I'm assuming you are using Application auth token and not Client auth?
> > 
> > 
> > I've created a registered application, given them all the required permissions, and I use its credentials for retrieving an access token. But I guess that wasn't my problem, because one of my requests has worked and created a "meetnow" meeting.
> 
> I'm on the same scenario and facing the same issue, it's successful when is of type meetnow, otherwise tells me Organizer - User/App instance id missing, have you found any workaround ?

It seems that it's the same issue we've faced. As I understand from the following answer:

> @oserdiuk We are targeting the above scenario by end of next quarter, so June/July.

the current version of API supports only meetnow meetings, and others will be available in June/July. 
So I have not tried anything else. I thought about the option to create a meetnow meeting and reschedule it (if the API allows it, I don't know it). But what I need is broadcast meeting that should allow up to 1000 users to connect to the meeting.

**Comment by ogarules** [comment]
Similar situation here, hope this is released as planned.

**Comment by ajp-psj** [comment]
@VinodRavichandran
Is there any update as to the status of scheduled and other meeting types being available?

**Comment by axpae** [comment]
Any update on this? When will this new feature be available so meetings can be Scheduled?.
Thanks,
Adrian

**Comment by VinodRavichandran** [comment]
We are working on enabling creating and retrieving scheduled meeting events with user delegated permissions, should be available in this Q. 

Note that this will not add events in people's calendar, you would have to use Exchange APIs (create event) to do so. The design of this API is only planned to retrieve a meeting (URL) for a scheduled time. We will mention this in the documentation once the API is available to try and fixes are made on our end.

FYI @zhengni-msft

**Comment by axpae** [comment]
Thankyou for the update..


On Jul 11, 2019 at 4:16 pm, <Vinod Ravichandran<mailto:notifications@github.com>> wrote:


We are working on enabling creating and retrieving scheduled meeting events with user delegated permissions, should be available in this Q.

Note that this will not add events in people's calendar, you would have to use Exchange APIs (create event) to do so. The design of this API is only planned to retrieve a meeting (URL) for a scheduled time. We will mention this in the documentation once the API is available to try and fixes are made on our end.

FYI @zhengni-msft<https://github.com/zhengni-msft>

**Comment by axpae** [comment]
Thanks Vinod,
Quick question.. eventually want to use the graph API to create a teams meeting (extracting the URL via this API) and then inject that URL into a new scheduled meeting that we will create via Exchange Web Services..
One question I have, is what “attribute” has to be set on the scheduled meeting in the calendar associated with a teams device, so that the  meeting request will be picked up by a teams device (video conferencing device), so the meeting is associated with the appropriate teams meeting id (included in the URL link)
Any thoughts?
Adrian

Sent from my iPhone

On 11 Jul 2019, at 3:46 pm, Vinod Ravichandran <notifications@github.com<mailto:notifications@github.com>> wrote:


We are working on enabling creating and retrieving scheduled meeting events with user delegated permissions, should be available in this Q.

Note that this will not add events in people's calendar, you would have to use Exchange APIs (create event) to do so. The design of this API is only planned to retrieve a meeting (URL) for a scheduled time. We will mention this in the documentation once the API is available to try and fixes are made on our end.

FYI @zhengni-msft<https://github.com/zhengni-msft>

**Comment by VinodRavichandran** [comment]
Hi Adrian, If the device is using Exchange APIs, then it would have to clarified with the team that owns the Exchange APIs. You could potentially start here - https://docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-beta&tabs=http

Closing this issue, as next steps are provided in the comments above.

**Comment by jannikbuschke** [comment]
We are also eagerly waiting for this to land.

**Comment by kirubha-webex** [comment]
Please let me know if there are any sample requests for meetingType apart from "meetNow" type.

POST https://graph.microsoft.com/beta/app/onlineMeetings
Content-Type: application/json
Content-Length: 1553

{
  "meetingType": "meetNow",
  "participants": {
    "organizer": {
      "identity": {
        "user": {
          "id": "550fae72-d251-43ec-868c-373732c2704f"
        }
      }
    }
  },
  "subject": "subject-value"
}

**Comment by hmamoun** [comment]
Hi @VinodRavichandran, I wonder if you can provide a sample C# code to create a live event, this was promised in the past quarter as I understand from reading this thread, but I could find it nowhere.

**Comment by miguuelo** [comment]
Hi,

if a want to use the api https://docs.microsoft.com/es-es/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http (not the beta version) Could I sent into the body to configure who is the organizer? Thanks!
