### ISSUE TITLE
Unable to submit email message on behalf of another outlook account

### ISSUE THREAD

**Issue by SamShekhovtsov** [microsoftgraph/microsoft-graph-docs#4085]
For some reason the 'Send on Behalf' feature fails. The GrpahAPI always returns "ErrorSendAsDenied" (when From and Sender field values are different). The accounts are verified to have correct configuration for sending on behalf. I couldn't make it work after spending more than three days. Following permissions are requested during authentication "openid+email+profile+offline_access+User.Read Mail.Read Mail.Send Mail.Read.Shared Mail.ReadWrite.Shared Mail.Send.Shared Mail.ReadWrite". Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d61ed298-c1b2-31d1-472c-3e7b912459e9
* Version Independent ID: 1cd6a8dd-f3a9-bae9-462b-bede56d15c6c
* Content: [Send Outlook messages from another user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-send-mail-from-other-user#feedback)
* Content Source: [concepts/outlook-send-mail-from-other-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-send-mail-from-other-user.md)
* Product: **outlook**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
How is the correct configuration verified? Can the account in question send on behalf using Outlook?

**Comment by SamShekhovtsov** [comment]
one clarification, the Sender has 'Send on behalf' permission, but doesn't have Full Access permission.

From: test1@contoso.com
actual Sender: sender2@contoso.com

The sender sender2@contoso.com has granted permission to send on behalf of the test1@contoso.com

when sending Email message on behalf using Outlook application, it fails as well, with the following error:

 Your message did not reach some or all of the intended recipients.

 

      Subject:     test from outlook

      Sent:  04/03/2019 14:22

 

The following recipient(s) cannot be reached:

 

      'receivertest1@test.com' on 04/03/2019 14:22

            This message could not be sent. You do not have the permission to send the message on behalf of the specified user.

 

__________________________________________________

 

Diagnostic information for administrators:

__________________________________________________

 

Error is [0x80070005-0x000004dc-0x00000524].

 

Exchange response headers:

      request-id: 80777843-7f20-4ec9-9be9-25b02372310b

      X-ServerApplication: Exchange/15.20.1665.000

      X-FEServer: LO2P265CA0356

      X-BEServer: AM6PR0502MB3622

      X-CalculatedBETarget: AM6PR0502MB3622.eurprd05.prod.outlook.com

      X-RequestId: {399B1CD8-9DF0-41DE-878A-FA9E08CF808F}:540

      X-ClientInfo: {9E747231-C6D0-4B65-BD67-92F7651C4297}:143680192

      X-ElapsedTime: 119

      X-BackEndHttpStatus: 200

      X-ResponseCode: 0

      X-DiagInfo: AM6PR0502MB3622

      X-RequestType: Execute

__________________________________________________

 

ROPs Summary:

 

      0: ropSetProps (10) Processed(1) Completed(0)

            ROP result: 0

            Response codes: 0

      1: ropSetProps (10) Processed(1) Completed(0)

            ROP result: 0

            Response codes: 0

      2: ropFlushRecipients (14) Processed(1) Completed(0)

            ROP result: 0

            Response codes: 0

      3: ropSetProps (10) Processed(1) Completed(0)

            ROP result: 0

            Response codes: 0

      4: ropTransportSend (74) Processed(1) Completed(0)

            ROP result: 0

            Response codes: 1244

__________________________________________________

 

Response Exceptions:

 

ROP Index: 4

ROP Associated: ropTransportSend (74)

Microsoft.Exchange.Data.Storage.SendAsDeniedException: Can't transport send message. ---> Microsoft.Mapi.MapiExceptionSendAsDenied: MapiExceptionSendAsDenied: Unable to transport send message. (hr=0x80070005, ec=1244)

Diagnostic context:

    Lid: 55847   EMSMDBPOOL.EcPoolSessionDoRpc called [length=2775]

    Lid: 43559   EMSMDBPOOL.EcPoolSessionDoRpc returned [ec=0x0][length=148][latency=1]

    Lid: 52176   ClientVersion: 15.20.1665.0

    Lid: 50032   ServerVersion: 15.20.1665.6006

    Lid: 35180 

    Lid: 23226   --- ROP Parse Start ---

    Lid: 27962   ROP: ropSetProps [10]

    Lid: 27962   ROP: ropFlushRecipients [14]

    Lid: 31418   --- ROP Parse Done ---

    Lid: 55847   EMSMDBPOOL.EcPoolSessionDoRpc called [length=152]

    Lid: 43559   EMSMDBPOOL.EcPoolSessionDoRpc returned [ec=0x0][length=416][latency=24]

    Lid: 52176   ClientVersion: 15.20.1665.0

    Lid: 50032   ServerVersion: 15.20.1665.6006

    Lid: 35180 

    Lid: 23226   --- ROP Parse Start ---

    Lid: 27962   ROP: ropSetProps [10]

    Lid: 27962   ROP: ropTransportSend [74]

    Lid: 17082   ROP Error: 0x4DC    

    Lid: 44949 

    Lid: 21921   StoreEc: 0x4DC    

    Lid: 27962   ROP: ropExtendedError [250]

    Lid: 1494    ---- Remote Context Beg ----

    Lid: 38698 

    Lid: 37692 

    Lid: 44092 

    Lid: 41232 

    Lid: 60208 

    Lid: 37136 

    Lid: 34608 

    Lid: 55056 

    Lid: 42768 

    Lid: 56112 

    Lid: 52807 

    Lid: 33016   StoreEc: 0x4DC    

    Lid: 40748   qdwParam: 0xB01000000000001

    Lid: 57132   qdwParam: 0x0              

    Lid: 63016   dwParam: 0x4A

    Lid: 39640   StoreEc: 0x4DC    

    Lid: 45434   Guid: 738866d3-dd05-4c3f-b664-4212a38bad21

    Lid: 10786   dwParam: 0x0        Msg: 15.20.1665.000:AM6PR0502MB3622:33ecfd59-d6f8-4310-aed6-0c20007f2233

    Lid: 1750    ---- Remote Context End ----

    Lid: 31418   --- ROP Parse Done ---

    Lid: 22753 

    Lid: 21817   ROP Failure: 0x4DC    

    Lid: 59285 

    Lid: 46997   StoreEc: 0x4DC    

   at Microsoft.Mapi.MapiExceptionHelper.ThrowIfError(String message, Int32 hresult, IExInterface iUnknown, Exception innerException, MapiStore mapiStore)

   at Microsoft.Mapi.MapiUnk.ThrowIfError(String message, Int32 hr)

   at Microsoft.Mapi.MapiMessage.TransportSendMessage(PropValue[]& propsToReturn)

   at Microsoft.Exchange.Data.Storage.MapiAccessor.TransportSendMessage(Object mapiObject, ExTimeZone timezone, PropertyDefinition[]& propertyDefinitions, Object[]& propertyValues)

   --- End of inner exception stack trace ---

   at Microsoft.Exchange.Data.Storage.MapiAccessor.TransportSendMessage(Object mapiObject, ExTimeZone timezone, PropertyDefinition[]& propertyDefinitions, Object[]& propertyValues)

   at Microsoft.Exchange.Data.Storage.CoreItem.TransportSend(PropertyDefinition[]& properties, Object[]& values)

   at Microsoft.Exchange.RpcClientAccess.Handler.Message.TransportSend()

   at Microsoft.Exchange.RpcClientAccess.Handler.RopHandler.<>c__DisplayClass154_0.<TransportSend>b__0()

   at Microsoft.Exchange.RpcClientAccess.Handler.ExceptionTranslator.TryExecuteCatchAndTranslateExceptions[TResult](Func`1 protectedCode, Func`2 errorCodeExtractor, Boolean noThrow, TResult& result, Exception& exception, ErrorCode& errorCode)

 

 

Transport-Send failed: failure enum(25), HResult(0x00000000), EC(1244).

Transport-Send failed: failure enum(22), HResult(0x00000000), EC(1244).

Submit-Message failed: message id(6), failure enum(13), HResult(0x8007000

**Comment by jasonjoh** [comment]
If you cannot send with Outlook, there's a configuration issue unrelated to Graph. Since the problem seems related to configuration and not to the documentation, closing this issue.
