### ISSUE TITLE
User attribute 'isResourceAccount' always null

### ISSUE THREAD

**Issue by bcotoras** [microsoftgraph/microsoft-graph-docs#4094]
Hi, I'm trying to get the user list without rooms users. I found the user attribute 'isResourceAccount' but when I call the service with this attribute, that is always `null `(using v1.0 and beta)

Using Microsoft Graph Explorer I try with this 
`https://graph.microsoft.com/v1.0/users?$select=displayName,mail,userType,isResourceAccount`

and this is the response:

``` json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(displayName,mail,userType,isResourceAccount)",
    "value": [
        {
            "displayName": "Abel King",
            "mail": "abel.king@imasde.onmicrosoft.com",
            "userType": "Member",
            "isResourceAccount": null
        },
        {
            "displayName": "Ben George",
            "mail": "ben.george@imasde.onmicrosoft.com",
            "userType": "Member",
            "isResourceAccount": null
        },
        {
            "displayName": "Leslie Meyer",
            "mail": "leslie.meyer@imasde.onmicrosoft.com",
            "userType": "Member",
            "isResourceAccount": null
        },
        {
            "displayName": "Room 1",
            "mail": "s1p1@imasde.onmicrosoft.com",
            "userType": "Member",
            "isResourceAccount": null
        },
        {
            "displayName": "Room 2",
            "mail": "s2p1@imasde.onmicrosoft.com",
            "userType": "Member",
            "isResourceAccount": null
        }
    ]
}
```

**Comment by joergschoba** [comment]
i have got the same problem, i want to differ amongst normal user and room/equipment users but on both v1.0 and beta graph endpoint the isResourceAccount property is null for both normal users and room users: 

`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users(displayName,isResourceAccount)",
    "value": [
        {
            "displayName": "Conf Room Adams",
            "isResourceAccount": null
        },
        {
            "displayName": "Adele Vance",
            "isResourceAccount": null
        }
}`

**Comment by figgsoftware** [comment]
Same problem here

**Comment by TheSinding** [comment]
When is there an update for this?

**Comment by arnoldmatusz** [comment]
Same here. Any update on this?

**Comment by krbain** [comment]
isResourceAccount is not supported, docs indicate that is should not be used e.g. Do not use – reserved for future use. See https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties
