### ISSUE TITLE
login_hint cannot use?

### ISSUE THREAD

**Issue by zaidrashid** [microsoftgraph/microsoft-graph-docs#4096]
When directing to the authentication page, I want to pass the login_hint, the user email so that the user does not have to enter it again. It seems that its not working with https://login.microsoftonline.com/{tenant}|common/adminconsent. But if I try this using https://login.microsoftonline.com/common/oauth2/v2.0/authorize, this works fine. 

Anything that miss?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies for the delayed response.
Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-identity.html). Please ask your question there; a team's available to guide you in this. Closing this issue.
