### ISSUE TITLE
Sign In alerts are missing important information

### ISSUE THREAD

**Issue by boaz-w** [microsoftgraph/microsoft-graph-docs#4099]
Some alerts related to sign in activity that are generated in MCAS or Azure AD are missing important information such as source IP address and an identifier that can be used to view the alert in the provider's UI.
For example, here is an identity protection alert from Graph Explorer samples:

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#Security/alerts/$entity",
    "id": "FB8F3278-88BC-4536-9353-F949919BBE4E",
    "azureTenantId": "00000001-0001-0001-0001-000000000001",
    "azureSubscriptionId": "",
    "riskScore": null,
    "tags": [],
    "activityGroupName": null,
    "assignedTo": "",
    "category": "UnfamiliarLocation",
    "closedDateTime": null,
    "comments": [],
    "confidence": 0,
    "createdDateTime": "2019-02-25T18:21:01.4314701Z",
    "description": "User logged in from a new unfamiliar location based on user’s past login history.",
    "detectionIds": [],
    "eventDateTime": "2019-02-25T18:18:29.1832451Z",
    "feedback": null,
    "lastModifiedDateTime": "2019-02-25T18:29:48.20682Z",
    "recommendedActions": [],
    "severity": "medium",
    "sourceMaterials": [],
    "status": "newAlert",
    "title": "Sign-in from an unfamiliar location",
    "vendorInformation": {
        "provider": "Azure AD Identity Protection",
        "providerVersion": "3.0",
        "subProvider": null,
        "vendor": "Microsoft"
    },
    "cloudAppStates": [],
    "fileStates": [],
    "hostStates": [],
    "historyStates": [],
    "malwareStates": [],
    "networkConnections": [],
    "processes": [],
    "registryKeyStates": [],
    "triggers": [],
    "userStates": [
        {
            "aadUserId": "",
            "accountName": "adamw",
            "domainName": "M365x594651.onmicrosoft.com",
            "emailRole": "unknown",
            "isVpn": null,
            "logonDateTime": null,
            "logonId": "0",
            "logonIp": null,
            "logonLocation": null,
            "logonType": null,
            "onPremisesSecurityIdentifier": "",
            "riskScore": "0",
            "userAccountType": null,
            "userPrincipalName": "adamw@M365x594651.onmicrosoft.com"
        }
    ],
    "vulnerabilityStates": []
}

There are some important pieces of context related information missing:
1. From which IP address did the sign in originate?
2. From what location did the sign in originate?
3. How can the alert be found in the risk events section of Azure AD?
4. From what device did the user sign in?
5. Did the sign in include MFA?

Most of the information can be gathered from the Risk Events blade within Azure AD, but there is no way to directly find the alert within Azure AD.
I hoped that the 'id' field could be used for such correlation, but when looking at real data from MCAS I was not able to correlate between the 'id' field and the actual alert id in MCAS.

Looking forward for your advice.

Regards,
Boaz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f98833-3e2f-978a-716a-637323f9314a
* Version Independent ID: 3d0a052a-2c66-35be-3079-65db8f5f8d95
* Content: [Get alert - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/alert-get.md)
* Product: **security**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
This issue will be closed because this forum is for documentation issues only. To report functionality issues or get help with your code, please visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-security.html)
