### ISSUE TITLE
Listing deviceComplianceScheduledActionForRule objects fail with Bad Request

### ISSUE THREAD

**Issue by jseerden** [microsoftgraph/microsoft-graph-docs#4104]
Listing deviceComplianceScheduledActionForRule objects fail with Bad Request:

```
Request to https://graph.microsoft.com/v1.0/deviceManagement/deviceCompliancePolicies/b2213752-98f8-4bc0-8a73-6c0be4869705/scheduledActionsForRule failed with HTTP Status BadRequest Bad Request.
Response content:
{
  "error": {
    "code": "No method match route template",
    "message": "No OData route exists that match template ~/singleton/navigation/key/navigation with http verb GET for
request /StatelessDeviceConfigurationFEService/deviceManagement/deviceCompliancePolicies('b2213752-98f8-4bc0-8a73-6c0be
4869705')/scheduledActionsForRule.",
    "innerError": {
      "request-id": "190dbed4-d84c-403b-9c77-abccac70a7fb",
      "date": "2019-03-06T00:22:12"
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4be9dcc-8a18-d93b-23ed-05e191d51bcb
* Version Independent ID: 2952d4a3-dff3-0f72-828f-1a714a9a0b14
* Content: [List deviceComplianceScheduledActionForRules - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancescheduledactionforrule-list?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-devicecompliancescheduledactionforrule-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-deviceconfig-devicecompliancescheduledactionforrule-list.md)
* Product: **intune**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by daveyyoung** [comment]
Having the same issue.  Unable to get the id's available as a result

**Comment by JSOnions** [comment]
I am also having the same problem.

This issue seems to be consistent across all methods and endpoints for scheduled actions. I cannot list all or get individual actions, nor can I create or update actions on an existing compliance policy.

I can customise the default "block" action inGracePeriod when initially creating the policy by adding the below to the bottom of the JSON body:
"scheduledActionsForRule": 
        [
          {
            "ruleName":"blockAction",
            "scheduledActionConfigurations":  
                    [
                      {
                        "actionType":"block",
                        "gracePeriodHours":24,
                        "notificationTemplateId":"",
                        "notificationMessageCCList":[]
                        }
                    ]
          }
]

This works with a POST request to https://graph.microsoft.com/v1.0/deviceManagement/deviceCompliancePolicies.

Unfortunately I cannot add other rules at this stage for email templates etc.

I appear to have found the ID for the rules via developer mode in the Azure portal, however this has not enabled me to get any further info via the Graph API.

**Comment by alutgert** [comment]
I'm having the same issue. I'm trying to configure the other actions: Encryption, Device Security and Defender. But I cannot figure out how the rules need to be added.

The Password can be configured with:

"scheduledActionsForRule":[{"ruleName":"PasswordRequired","scheduledActionConfigurations":[{"actionType":"block","gracePeriodHours":0,"notificationTemplateId":""}]}],


So I tried:

"scheduledActionsForRule":[{"ruleName":"PasswordRequired","scheduledActionConfigurations":[{"actionType":"block","gracePeriodHours":0,"notificationTemplateId":""}]}{"ruleName":"Firewallrequired"}],

but that doesn't work.

Does anybody know how to add the other actions to the devicecompliancepolicy?

Thanks is advance.

**Comment by alutgert** [comment]
You can ignore the last part.....

**Comment by rrbruin** [comment]
Yes, same issue here too.

**Comment by phuong-vo** [comment]
I have the same issue!

**Comment by triplanedave** [comment]
You can use this format: https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies/<yourpolicyid>?($expand=assignments,scheduledActionsForRule($expand=scheduledActionConfigurations))
