### ISSUE TITLE
Specified scopes for user: getMemberObjects are incorrect 

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/microsoft-graph-docs#411]
Confirmed that User.Read and User.ReadWrite from a non admin account are insufficient to access member objects.

From: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/33

**Comment by dkershaw10** [comment]
Actually the whole topic is completely wrong and needs fixing.   It should mirror the information here: https://msdn.microsoft.com/en-us/library/azure/ad/graph/api/functions-and-actions#getMemberObjects.  The example requests aren't even valid and cannot be run on the manager link AFAIK.
As for permissions, for a full result set you would need Directory.Read.All
