### ISSUE TITLE
How to use GET photo graph api directly from raw html img tag src attribute?

### ISSUE THREAD

**Issue by dipakboyed** [microsoftgraph/microsoft-graph-docs#4113]
I'd like to use the GET photo/$value Graph api directly from my web content (html img tag, src attribute).
Instead of requiring the Authorization header is there is way to pass the access token as a query param or some option so that I generate a graph api url with authorization token and directly reference its from the img tag's src attribute in my html?
Adding support for this would greatly improve the dev experience for this api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Thanks for your input, @dipakboyed . Will follow up on this.

**Comment by aarushi-mittal** [comment]
@angelgolfer-ms hello , I am trying to do somewhat similar.
I am trying to display my image to my web app .

Is there a way to do this?

Thanks,
Aarushi
