### ISSUE TITLE
How to pass authorization token from uri instead of http header?

### ISSUE THREAD

**Issue by dipakboyed** [microsoftgraph/microsoft-graph-docs#4114]
I'd like to use the Microsoft Graph apis directly from my web content (e.g. call GET ~/photos api from my html img tag, src attribute).
Instead of requiring the Authorization header is there is way to pass the access token as a query param or some option so that I generate a graph api url with authorization token and directly reference its from the img tag's src attribute in my html?
Adding support for this would greatly improve the dev experience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e0d58a-5413-d9ef-b9f7-52bb82c1eb8b
* Version Independent ID: 18b4320d-52b6-3dab-b92b-35eb6093118b
* Content: [Get access tokens to call Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-overview#what-is-an-access-token-and-how-do-i-use-it)
* Content Source: [concepts/auth-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-overview.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dipakboyed** [comment]
@darrelmiller , @garethj-msft : are there any API recommendations on this request?

**Comment by darrelmiller** [comment]
Hi @dipakboyed, there is not a way to pass the regular Graph token via the URL.  Tokens that are put in URLs need to be very short lived and should be tied to the URL in some way.

**Comment by dipakboyed** [comment]
not supported/not expected

**Comment by garethj-msft** [comment]
@dipakboyed  There are two recommendations here to get teh sort of experience you would like.
It's to insecure to have a one hour OAUTH token in the url as URLs are too easily intercepted compared to headers in log files etc.

1 Where you don't have control of the API. Having an intermediate layer for this that uses cookie authentication and then makes the call to graph based on that is the recommended pattern here.
2 If you do have control of the API have a way to get a pre-auth'd URL for the resource.  Make that a short lived auth token that is hashed with the actual resource id and then encrypted, so it can only be applied to that one URL.  then you can parse that and reconvert it under the hood.
