### ISSUE TITLE
Content Type

### ISSUE THREAD

**Issue by cooleyenet** [microsoftgraph/microsoft-graph-docs#4119]
When calling invalidateAllRefreshTokens from PowerShell Invoke-WebRequest or Invoke-RestMethod, -ContentType 'application/json' is required, or else you will get "The remote server returned an error: (415) Unsupported Media Type."

Would be good to call out the required content type in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b3f5dd2-e23e-4453-258d-036950e5a589
* Version Independent ID: 2290444e-dbb1-194f-d6f5-132972153998
* Content: [user: invalidateAllRefreshTokens - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-invalidateallrefreshtokens?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/user-invalidateallrefreshtokens.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-invalidateallrefreshtokens.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Doc updated
