### ISSUE TITLE
Missing Topic

### ISSUE THREAD

**Issue by ermajor23** [microsoftgraph/microsoft-graph-docs#4126]
Create Service Principal topic is missing. It should be equivalent to this topic: https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-beta, except you are doing a POST /beta/servicePrincipals, and you must specify the appId of the backing application object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07769b8-df00-6abc-bc50-79cc07b75339
* Version Independent ID: 0cd73e6b-f547-c257-4ffc-faeb4cfd1abf
* Content: [servicePrincipal resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/serviceprincipal.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@sureshja - this is a dup :)

**Comment by mahoekst** [comment]
Where is the create principal doc?

**Comment by linux-paul-e** [comment]
@dkershaw10  you say this is a dup, but link to the dup?   still cannot find the docs to create a service principal

**Comment by thrixton** [comment]
I can confirm that a `POST` to the endpoint `/serviceprincipals` works with the below body.
If this can be added to the documentation that would be great.
``` json
{
  "displayName": "{APP_NAME}",
  "servicePrincipalType": "Application",
  "servicePrincipalNames": [
    "{APP_ID}"
  ],
  "appId": "{APP_ID}"
}
```

**Comment by davidmu1** [comment]
https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-beta&tabs=http

Closing this issue.
