### ISSUE TITLE
Documentation Discrepency

### ISSUE THREAD

**Issue by ermajor23** [microsoftgraph/microsoft-graph-docs#4127]
Using the example request does not allow users to be added to the Service Principal as expected. Instead the error message; "Write requests are only supported on contained entities" is displayed.

Using POST https://graph.microsoft.com/beta/servicePrincipals/{id}/owners/$ref and the request body of of {"@odata.id":"https://graph.microsoft.com/beta/users/{id}"} does allow owners to be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8641fff-2063-de08-4c79-743d82ae962f
* Version Independent ID: 72b36f35-e582-9742-e982-419fc2354faf
* Content: [servicePrincipal: Add owner - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-owners?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/serviceprincipal-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-post-owners.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by juunas11** [comment]
I can also confirm the request in the docs does not work, this one does.

**Comment by moroienius** [comment]
me too..documentation steps are not working.thx for payload from comment

**Comment by MrAzureAD** [comment]
Another example for a non-working example. Bug open for more than 1 year.
Easily fixable in seconds - and I would volunteer to provide a fix.
Is it possible for non-Microsoft guys to contribute?  
@jthake-msft @dkershaw10

**Comment by jthake-msft** [comment]
@MrAzureAD I just got demoed by our DevX engineering team that we are no taking the examples that are generated and testing them. We are aware of a few hundred across all the API pages right now and addressing these.
I understand this is frustrating and are putting in some more checks to follow up with owners to get these things addressed.

**Comment by davidmu1** [comment]
This issue seems to be resolved. Successfully ran this example:

POST https://graph.microsoft.com/beta/applications/{id}/owners/$ref
Content-type: application/json

{
"@odata.id": "https://graph.microsoft.com/beta/directoryObjects/{id}"
}

No change identified for the page. Closing the issue.
