### ISSUE TITLE
Getting an empty response

### ISSUE THREAD

**Issue by hizki** [microsoftgraph/microsoft-graph-docs#4129]
When using the API, although I have many items in my user's recycling bin, some over 2 days old, I'm getting 200 but with an empty list.

Requests I tried:
GET https://graph.microsoft.com/v1.0/directory/deletedItems/microsoft.graph.user
GET https://graph.microsoft.com/v1.0/directory/deletedItems/microsoft.graph.group
POST https://graph.microsoft.com/v1.0/directory/deletedItems/getUserOwnedObjects

For all requests I get 200 and "value": [].
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf76efc-5ca2-e829-1604-fa858179858a
* Version Independent ID: bbf2d629-8795-3d87-76de-f147489e4942
* Content: [List deleted items - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-list?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directory-deleteditems-list.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by meven3000** [comment]
Yep, same issue when using the Graph Explorer (yes it 'should' work)

I tried doing the same command via a LogicApp using HTTP Request and it worked as expected.

Steve

**Comment by keylimesoda** [comment]
Internal product bug opened to track this issue. Will update through triage and resolution.

**Comment by keylimesoda** [comment]
This bug has been triaged by the product team and assigned priority 2, severity 3.

It has been assigned to a team member for the May sprint.

**Comment by keylimesoda** [comment]
@hizki Wanted to make sure we have clear repro steps.  We're having some issue triggering the behavior.

1.  Add items to a user's recycling bin
2.  Call one of the three APIs listed

Are there any other mitigating circumstances that may help us recreate this issue?  If not, we may ask to dig in on your specific tenant to look at any environmental issues.

**Comment by keylimesoda** [comment]
@meven3000 can you provide a recent repro to help with debugging?

**Comment by davidmu1** [comment]
No change currently to the page. Closing the issue.
