### ISSUE TITLE
Do you have an idea if it's gonna be kept in v1.0 ?

### ISSUE THREAD

**Issue by Daavidaviid** [microsoftgraph/microsoft-graph-docs#4145]
Hi,
My team and I find this endpoint very useful, do you guys have any idea if you'll keep it ?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cdeed1b-b792-b92e-c202-427e412cf122
* Version Independent ID: 3db73371-c6ee-2add-9d51-223e3f1f82e4
* Content: [calendar: getSchedule - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/calendar-getschedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/calendar-getschedule.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@Daavidaviid , good news - getSchedule is now officially available in v1 as well: [getSchedule in v1](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0).
Thanks for your patience!
