### ISSUE TITLE
Different Endpoint URLs

### ISSUE THREAD

**Issue by MysticRyuujin** [microsoftgraph/microsoft-graph-docs#4146]
The endpoint given at the top of the documentation does not match that of the endpoint given in the Example

`/privilegedAccess/azureResources/roleSettings/{id}`

v.s.

`https://graph.microsoft.com/beta/privilegedAccess/pimforazurerbac/roleSettings/5fb5aef8-1081-4b8e-bb16-9d5d0385bab5`

There is another reference to `pimforazurerbac` in the document as well but it's unclear what this is referencing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5d48e2-9e52-3008-4d6c-5adc88316008
* Version Independent ID: 2e32435c-8fe9-2c10-5d87-fde050787413
* Content: [Update governanceRoleSetting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governancerolesetting-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/governancerolesetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governancerolesetting-update.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Removed references to pimforazurerbac.
