### ISSUE TITLE
the /token endpoint doesn't provide refresh token unless scope offline_access is specified in the request

### ISSUE THREAD

**Issue by jonasjancarik** [microsoftgraph/microsoft-graph-docs#4147]
It seems that for the /token endpoint to return a refresh token, it is necessary to explicitly state the scope offline_access along with the https://graph.microsoft.com/.default scope, i.e.: "scope": "offline_access https://graph.microsoft.com/.default".

The documentation makes it sound like "https://graph.microsoft.com/.default" alone should be enough (and in other contexts it is).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service#feedback)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Added a note that the `offline_access` scope is required when the app needs a refresh token.
