### ISSUE TITLE
[Bug] beta/applications - responding with a single item only

### ISSUE THREAD

**Issue by kumbol** [microsoftgraph/microsoft-graph-docs#4154]
I'm currently only getting a **single value as a response** for this request. I was expecting a full list of apps I can see within the Azure Portal in the Enterprise Apps tab.

Request: `https://graph.microsoft.com/beta/applications?$select=id,displayName`

Response: 
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#applications(id,displayName)",
    "value": [
        {
            "id": "8870c009-852f-43af-9e5f-5c1a01b27f6f",
            "displayName": "SharePoint Online Client Extensibility Web Application Principal"
        }
    ]
}
```
![Image](https://i.imgur.com/cb5HjFW.png)
vs.
![Image](https://i.imgur.com/FQP9Nmt.png)

I also **cannot find any other app by filtering** (either via IDs or displayName).

The tenant is set up for targeted release. This is a test tenant acquired from Office 365 Dev Program (within dev.onmicrosoft.com domain). It's not fresh, I've been using it for a few months now, there's a lot of apps both from Microsoft as well as 3rd party already registered and visible in AAD portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6cedaa-9bc6-d29e-9bf1-bd865075869c
* Version Independent ID: 05d7f4b4-d564-1ce7-d676-ca8b433f763d
* Content: [List applications - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-list.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
This doesn't seem like a doc issue.  This looks like a product/service issue - please file those on StackOveflow, tagged with [microsoft-graph].
