### ISSUE TITLE
List messages doesn't respect Prefer text header

### ISSUE THREAD

**Issue by taviandir** [microsoftgraph/microsoft-graph-docs#4156]
In the API docs, there is a section that says one can set the Prefer header to `outlook.body-content-type=text` to get text body on the returned message. This same feature is documented on both "Get Message" and "List Messages". When I tried it on "Get Message" it worked, but on "List Messages" it didn't; I got the body back as `html` instead of `text`, without `Preference-Applied`.

**Expected behavior:** 

"List messages" looks at HTTP Header `Prefer: outlook.body-content-type=text`, and returns emails with body field as text (with HTTP response header `Preference-Applied`).

**Actual behavior:** 

Setting it doesn't make any difference, I get `html` in `body` field.

So is the docs wrong? Is this feature is not available for "List Messages"? As it currently stands, the API docs don't match actual behavior.

I tried using` $filte`r to limit the number of items to a smaller result set, but that didn't do anything either.

```
GET https://graph.microsoft.com/v1.0/users/jimmy.REDACTED@REDACTED.no/messages HTTP/1.1
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0169c1-e6e7-da8f-4158-5e721eae8b9a
* Version Independent ID: f2907cde-b9d7-4ba7-e813-047e5b938e50
* Content: [List messages - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-messages.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by julienFlexsoft** [comment]
I had the same as you because I wrote my header wrong. Try it with this:
Header:
- Name: Prefer
- Value: outlook.body-content-type="text"

**Comment by taviandir** [comment]
Thanks for your reply!

I tried it now, and it seems like it works as expected for text, both with and without quotes around "text" in the header. 
I would expect that the "Preference-Applied" to be set in the response (like with Get Message). But that isn't a deal breaker for me, and it's not specified in the documentation for List Messages either.

Since the documentation now does what it says it does in regards to this topic, I'll close this issue. :)
