### ISSUE TITLE
"dateTime" and "timeZone" attribute documentation out of date

### ISSUE THREAD

**Issue by ryandamico** [microsoftgraph/microsoft-graph-docs#4157]
Looks like the /getSchedule beta endpoint now requires "DateTime" and "TimeZone", not "dateTime" and "timeZone"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf420cde-d6d2-9db4-d1f1-162d93d2b7dc
* Version Independent ID: 9d5477ea-fe33-6234-94cf-fdfe3c3ecb9e
* Content: [dateTimeTimeZone resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/datetimetimezone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/datetimetimezone.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by alexandersoto** [comment]
I am also seeing this. Sending `dateTime` and `timeZone` gives the following error: `The property 'dateTime' does not exist on type 'Microsoft.OutlookServices.DateTimeTimeZone'. Make sure to only use property names that are defined by the type or mark the type as open type.`.

Change the fields to `DateTime` and `TimeZone` and it works as expected.

**Comment by kidGodzilla** [comment]
I am also seeing this. Breaking change to use the older Exchange server style case, which occurred for us without warning a few hours ago. Seems more like a bug than an intentional change, as other key cases appear unchanged.

**Comment by angelgolfer-ms** [comment]
Hi @ryandamico , @alexandersoto , @kidGodzilla , can  you confirm if you're still experiencing the same problem using getSchedule and specifying camel case "dateTime" and "timeZone" in the request payload?

**Comment by alexandersoto** [comment]
@angelgolfer-ms I'm still seeing the same issue. Response:

```
{
  "error": {
    "code": "RequestBodyRead",
    "message": "The property 'dateTime' does not exist on type 'Microsoft.OutlookServices.DateTimeTimeZone'. Make sure to only use property names that are defined by the type or mark the type as open type.",
    "innerError": {
      "request-id": "5e9bc11e-8aa8-47b0-916d-6e3438631661",
      "date": "2019-03-14T20:13:19"
    }
  }
}
```

**Comment by jthake-msft** [comment]
@alexandersoto what was the request you sent this? 
in the docs there is an example here https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-beta

```
POST https://graph.microsoft.com/beta/me/calendar/getschedule 
Prefer: outlook.timezone="Pacific Standard Time"
Content-Type: application/json

{        
    "schedules": ["AdeleV@contoso.onmicrosoft.com", "AlexW@contoso.OnMicrosoft.com"],
    "startTime": {
        "dateTime": "2018-08-06T09:00:00",
        "timeZone": "Pacific Standard Time"
    },
    "endTime": {
        "dateTime": "2018-08-06T18:00:00",
        "timeZone": "Pacific Standard Time"
    },
    "availabilityViewInterval": "15"
}
```

This works for me no problems.

**Comment by alexandersoto** [comment]
It was a `POST` to [getSchedule](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-beta).

Although it now looks to be working as expected with `dateTime` and `timeZone` in camel case. It must have been fixed in the last couple hours.

**Comment by jthake-msft** [comment]
do you have an example of your post body? in our logs we can't see that. but can confirm ou did indeed get  an error.

**Comment by alexandersoto** [comment]
Sure thing. I don't remember the exact arguments, but the body structure looked like:
```
{
  "schedules": [
    "${email1}",
    "${email2}"
  ],
  "startTime": {
    "dateTime": "2019-03-14T22:46",
    "timeZone": "UTC"
  },
  "endTime": {
    "dateTime": "2019-03-14T22:56",
    "timeZone": "UTC"
  },
  "availabilityViewInterval": 10
}
```

I'm no longer getting an error though, so it looks fixed on my end.

**Comment by angelgolfer-ms** [comment]
Hi @ryandamico  and @kidGodzilla , can you please confirm if you are experiencing the problem?
On our end, we're following up to try to mitigate this problem for the future.

**Comment by amirakbulut** [comment]
Does this error got anything to do with it as well?

> Client error: `POST https://graph.microsoft.com/v1.0/me/calendar/getschedule` resulted in a `400 Bad Request` response:
> {
>   "error": {
>     "code": "RequestBodyRead",
>     "message": "Cannot convert the literal '04/06/2019 17:00:00' to the (truncated...)
> 
>

**Comment by ryandamico** [comment]
Hi @angelgolfer-ms - Just getting back to this thread. Haven't had a chance to test reverting back to lower camel case, but the upper camel case is still working for me. I assume it's safe to continue using that?

**Comment by angelgolfer-ms** [comment]
@ryandamico , sorry for the much delayed response, yes, it's fine to specify API property names in request bodies in upper camel case. They are not case-sensitive.
FYI I have PR #5691 clarifying what are and are not case-sensitive when calling a Microsoft Graph API in a purple note in the [Access data and methods](https://docs.microsoft.com/en-us/graph/traverse-the-graph#microsoft-graph-api-metadata) topic. The content will be updated on the live site on the first weekday next week.
