### ISSUE TITLE
PHP or Laravel?

### ISSUE THREAD

**Issue by greatBigMassive** [microsoftgraph/microsoft-graph-docs#4159]
Hi there,

Could we have some clarity on the tutorial please because it suggests we are going to be shown how to do it using raw PHP but instead it is being complete using Laravel which is a framework above PHP.

It is like saying the tutorial is in Javascript only it teaches us how to do everything in jQuery which uses mostly commands and utilities completely different to that of raw Javascript.  If we were developing in MooTools for example, the tutorial would be completely useless just like anyone who wants to understand how to connect to graph with raw PHP and not use a framework that needs to install above it just for the sakes of getting an access token and reaching the ability to issue requests and received responses.

I don't mean this to be negative but the necessity to install Laravel means the tutorial is for people using the Laravel framework.  It's the same as saying there's a tutorial for Ruby which is also a framework built over PHP.

Is there any chance we can have a much more basic tutorial that is in raw PHP and shows us how to initiate a user login to approve the app can read their basic user data and then process the access token and send a basic graph command?

Thank you for your time.
All of this is appreciated.

Adam

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0733b09-b4b0-a83f-d417-32ed26c33790
* Version Independent ID: 2bc7308f-0688-d7d6-d6e9-be06b3452cb8
* Content: [Microsoft Graph tutorials - Microsoft Graph](https://docs.microsoft.com/en-gb/graph/tutorials#feedback)
* Content Source: [concepts/tutorials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/tutorials.md)
* Product: **non-product-specific**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for the feedback @greatBigMassive. It's a fair point, and not just applicable to PHP. All of our web app tutorials use some sort of framework (Express for Node, Rails for Ruby, etc.). I can't promise anything at this point, but I'll take this to the team for investigation and discussion.

**Comment by PREngineer** [comment]
This is an old message but I just wanted to do the same, 6 months after, and I am faced with the same problem.

Laravel adds a lot of bloatware to the tutorial and I definitely want to stay away from adding other people's code's possible security vulnerabilities or development dependencies.

I'm pretty sure that it can be done in a very simple class that doesn't require additional MBs of space.

**Comment by jasonjoh** [comment]
Our PHP tutorial has been simplified, removing the need for Laravel.

https://docs.microsoft.com/graph/tutorials/php
