### ISSUE TITLE
Provide documentation on Status Code "429" Too Many Requests

### ISSUE THREAD

**Issue by jbarr33** [microsoftgraph/microsoft-graph-docs#416]
It would be great is there was some documentation or guidance on application throttling (the error is below). While developing with the Excel Online API's I get this error a lot.  I think I have figured out how to avoid during development by using a different workbook but for production apps the design must incorporate how to avoid these limits. For example, if an app can only make "x" requests in "y" time period then an particular app design might not even be feasible. It is critical to know this up front before endeavoring on weeks/months of development.

429     Too Many Requests   Client application has been throttled and should not attempt to repeat the request until an amount of time has elapsed.

Thanks.

**Comment by sumurthy** [comment]
The Excel API requests are treated as part of the overall Office Online requests. The 429 condition can be reached under few conditions: the workbook requests in itself could be going over the threshold, or the workbook requests in addition to existing traffic on the tenant could cause it to hit 429. So, there are no hard numbers to publish. Some of the admin level settings can also impact the limit. There are things one can do to limit the issue: such as limiting the number of sessions being created on the same workbook (which caps around 25). We'll revise the doc to mention high level steps one could take to minimize scenario.
