### ISSUE TITLE
some data not coming with v1.0/me/contacts graph api

### ISSUE THREAD

**Issue by bewithdhanu** [microsoftgraph/microsoft-graph-docs#4163]
I have some other stuff like Anniversary,Home fax,Personal web page,etc in my contacts.
but with v1.0/me/contacts graph API I can't get these fields
How can i get that remaining information
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c362f52-d8d5-3365-c1af-3bfa5baf951e
* Version Independent ID: 14dbab56-fdfe-87e5-da39-43c22160ee8e
* Content: [Get contact - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/contact-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/contact-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/contact-get.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cmparth** [comment]
Below mentioned issues can help you in getting those values
https://github.com/microsoftgraph/microsoft-graph-docs/issues/2151
https://github.com/microsoftgraph/microsoft-graph-docs/issues/2251
