### ISSUE TITLE
Does the Graph API support for updating Page Level in OneNote yet?

### ISSUE THREAD

**Issue by RMinshall** [microsoftgraph/microsoft-graph-docs#4168]
Does the API support updating Page Level in OneNote page?  I have found Patch syntax that seems to indicate it is possible, but when I attempt that I always get an Error 400 Bad Request Type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8cb77b2-6255-f9f1-9732-c1aef3a91f05
* Version Independent ID: 78736bc6-53ba-14b2-31fb-412459b29298
* Content: [Update page - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/page-update?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/page-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/page-update.md)
* Product: **onenote**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jjtbsomhorst** [comment]
Yes it does. You can send the following json as a patch request to the /content endpoint of a page:

{ "level": 0}

the level can be 0,1 or 2.

**Comment by RMinshall** [comment]
Thank you for such a quick response,

Might you have some sample code that shows how to build this json body?   I had found the information you sent and that is the format that I am sending but am getting the bad request response.  Using the -Verbose option I am getting an error “-1-byte payload” so I must be building the body incorrectly.

Thanks much,

Roland

**Comment by jjtbsomhorst** [comment]
add the content-type: application/json in the request header and be sure to use PATCH instead of put/post.

**Comment by RMinshall** [comment]
Thank you for the assist.  I was able to finally get the page level set.

Is it possible to make this page a sub-page rather than just indenting it?  A real subpage allows a user to collapse the top level and not see the sub-pages, but simply changing the level does not seem to do that.

Thanks much,

Roland

**Comment by jjtbsomhorst** [comment]
Not as far as I know
