### ISSUE TITLE
I'm always getting resource not found. 

### ISSUE THREAD

**Issue by shyamkris** [microsoftgraph/microsoft-graph-docs#4170]
I believe the `id` here is the `applicationId`:

``` http
https://graph.microsoft.com/beta/servicePrincipals/{id}
```
I'm passing the following in the body

```json
{
  "appDisplayName": "my-app",
  "appId": "appId"
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68153a69-a97b-8ee1-dfbf-0769d10e8f5e
* Version Independent ID: a7dc4262-533e-b866-e2c1-0663e7090dcb
* Content: [Update serviceprincipal - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-update?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/serviceprincipal-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-update.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mlafleur** [comment]
It should be the `id` for the `servicePrincipal` you want to update. You can see this `id` using this query:

```
https://graph.microsoft.com/beta/servicePrincipals?$select=id,appid,appDisplayName
```
Using the sample data from Graph Explorer, [the results look like this](https://developer.microsoft.com/en-us/graph/graph-explorer?request=servicePrincipals?$select=id,appid,appDisplayName&method=GET&version=beta&GraphUrl=https://graph.microsoft.com):

```json
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#servicePrincipals(id,appId,appDisplayName)",
    "@odata.nextLink": "https://graph.microsoft.com/beta/servicePrincipals?$select=id%2cappid%2cappDisplayName&$skiptoken=X%274453707402000100000035536572766963655072696E636970616C5F61333132363132662D613439332D343266312D396332622D63623230363535626163623235536572766963655072696E636970616C5F61333132363132662D613439332D343266312D396332622D6362323036353562616362320000000000000000000000%27",
    "value": [
        {
            "id": "00063ffc-54e9-405d-b8f3-56124728e051",
            "appId": "870c4f2e-85b6-4d43-bdda-6ed9a579b725",
            "appDisplayName": "Microsoft Information Protection Sync Service"
        },
        {
            "id": "016091d9-2c1e-40c6-89ba-34e676e6352b",
            "appId": "47ee738b-3f1a-4fc7-ab11-37e4822b007e",
            "appDisplayName": "Azure AD Application Proxy"
        },
        {
```
So, for example, to update Azure AD Application Proxy you would `POST` your changes to:

```
https://graph.microsoft.com/beta/servicePrincipals/016091d9-2c1e-40c6-89ba-34e676e6352b
````

**Comment by Hong-Revo** [comment]
In addition, if you want to retrieve the service principal for a given app, you can filter the list of all SPs on the app ID:
```
https://graph.microsoft.com/beta/servicePrincipals?$filter=appId+eq+'app-id'
```
The result will have a `value` component containing an array of the matching results, in this case an array of one.

Note that the app ID is not the same as the directory (object) id of either the app or the service principal.

**Comment by shyamkris** [comment]
Thank you. That helped.
