### ISSUE TITLE
How to Create Service Principal?

### ISSUE THREAD

**Issue by shyamkris** [microsoftgraph/microsoft-graph-docs#4171]
Issue: 
I need to create a service principal. But there is no POST call for a servicePrincipal. 

Article:

**Comment by Hong-Revo** [comment]
This operation is exposed in the beta version of the API. The basic request is

```
POST https://graph.microsoft.com/beta/servicePrincipals

{
    "appId": "your-registered-app-id"
}
```
That's it. You do need to have created an app first though.

**Comment by shyamkris** [comment]
Thank you. I guess the documentation is yet to be updated here [https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta]

**Comment by davidmu1** [comment]
https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-beta&tabs=http

Closing this issue.
