### ISSUE TITLE
Misspelled Pacific under Examples heading

### ISSUE THREAD

**Issue by Assisting** [microsoftgraph/microsoft-graph-docs#4173]
Sentence reads "A simple example is to find the free/busy schedule of a coworker, Alex, on a specific day, from 9am to 6pm, Pacitfic Standard Time:", should be "Pacific Standard Time:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6748e9-6e15-db5e-f85f-79dbe8171e9b
* Version Independent ID: a30e4438-c54b-643f-5573-c904ace73e70
* Content: [Get free/busy schedule of users and resources (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-free-busy-schedule#feedback)
* Content Source: [concepts/outlook-get-free-busy-schedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-get-free-busy-schedule.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
The typo had been fixed in PR #4175 and verified on the live site. Closing this issue. Thanks for bringing this up!
