### ISSUE TITLE
Not able to List Taskfolders using graph outlook beta API: Error - ErrorItemNotFound

### ISSUE THREAD

**Issue by ranavale** [microsoftgraph/microsoft-graph-docs#4174]
I am not able to list the Task Folders even though I can see those folders inside Outlook and ToDo.

Below is the error while I try the API on [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer):

``` HTTP
GET https://graph.microsoft.com/beta/me/outlook/taskFolders
Failure - Status Code 404
```

```json
{
    "error": {
        "code": "ErrorItemNotFound",
        "message": "The specified object was not found in the store.",
        "innerError": {
            "request-id": "0eb006e9-2ec5-4e9c-8c01-4fda9ccf396a",
            "date": "2019-03-15T19:52:56"
        }
    }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbe985ef-bfea-c91c-d61c-9297aa85beb9
* Version Independent ID: 1cc7b305-84ef-04e8-e3d0-4e849429b829
* Content: [Get outlookTaskFolder - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlooktaskfolder-get?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/outlooktaskfolder-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlooktaskfolder-get.md)
* Product: **outlook**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mlafleur** [comment]
The correct endpoint /**task**Folders rather than /**tasks**Folders (no `s`). So the URI should be `https://graph.microsoft.com/beta/me/outlook/taskFolders`

**Comment by ranavale** [comment]
Yes, I have updated the description.
While commenting by mistake I typed in extra ‘s’

Thanks,
Rakesh Navale
Redmond, StudioF/3309
________________________________

**Comment by ranavale** [comment]
I tried to use the Outlook v2.0 API as well `GET https://outlook.office.com/api/v2.0/me/taskfolders`
Which returned the similar issue. I understand this page belongs to **microsoft-graph-docs** Please let me know or redirect, if this issue belong to other team/group

**Comment by jthake-msft** [comment]
This is not really a docs content issue. This is an issue with your user mailbox as I cannot repo this on various tenants I hvae. You will need to raise this with our suppport desk using the portal.office.com Help in the admin center.
