### ISSUE TITLE
Open /education/me to run without admin

### ISSUE THREAD

**Issue by r3dh0t** [microsoftgraph/microsoft-graph-docs#4183]
Issue: /education/me 

Article:
I am wanting to develop out solutions for our school (141 other schools on our tenant), however, I cannot do so without admin access. 

Everything I need to develop could be achieved through the /me endpoint for edu. Could this be permissioned to run without admin?

**Comment by mmast-msft** [comment]
I apologize for missing this posting.  All EDU APIs require Admin Consent to protect access to student data as described [here](https://docs.microsoft.com/en-us/graph/permissions-reference#education-permissions).  This restriction will remain for the foreseeable future due to technical limitations.
