### ISSUE TITLE
Alert api does not return alerts

### ISSUE THREAD

**Issue by tangobango5** [microsoftgraph/microsoft-graph-docs#4184]
My security console i.e. https://protection.office.com/#/viewalerts shows 2 alerts while.
Alerts graph api return empty array with header set to 199 -&gt; Microsoft/WDATP/401/228. and status code of 206.
I have tried all set of combinations in the api but no luck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122ff9f6-5393-cb46-79d5-dac18a7131a8
* Version Independent ID: 150fb49f-a607-2297-b461-3979433a88c5
* Content: [List alerts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/alert-list?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/alert-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/alert-list.md)
* Product: **security**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by prescottbreeden** [comment]
Hello,

The error you are reporting has to do with issues on the side of the federated request to the provider (e.g. invalid license, etc.).  When these errors occur, the API will return a 206 status code.   You can read more about this issue [here](https://docs.microsoft.com/en-us/graph/api/resources/security-error-codes?view=graph-rest-1.0)
