### ISSUE TITLE
List channels for my team

### ISSUE THREAD

**Issue by silvestrpeknik** [microsoftgraph/microsoft-graph-docs#4185]
Hello, 

Is there a way to get list of channels for my teams, without having to ask for Group.Read.All permission?

It seems natural to be able to get list of my channels without having to get tenant admin's approval.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc7bd1a-6210-6010-c9ff-4245c342b20a
* Version Independent ID: e667c977-60ef-a81d-e94b-7eed5061b2c7
* Content: [List channels - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-list.md)
* Product: **microsoft-teams**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Unfortunately there is not right now. There is work currently in progress to allow for this scenario to not require Admin Consent. There is no timeframe on this right now. There is a user voice request you can vote on to be informed when this ships. https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/15969922-add-a-my-groups-read-write-permission-that-do

**Comment by Karishma-Tiwari-MSFT** [comment]
@jthake-msft The link you shared above is throwing 404. Can you please share the correct link.

**Comment by Karishma-Tiwari-MSFT** [comment]
If I am listed as owner of my team, what do I need to do in order to allow anyone to retrieve the channels in my team as well as messages in my channels using API?
Where can I find Group.Read.All permission option to set it to all?

**Comment by nkramer** [comment]
See https://docs.microsoft.com/en-us/graph/permissions-reference and https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/15969922-add-a-my-groups-read-write-permission-that-do
