### ISSUE TITLE
Release Date for MS Teams Education  - Assignments and Submissions API

### ISSUE THREAD

**Issue by engelmann2** [microsoftgraph/microsoft-graph-docs#4186]
Is there a planned release date to know when we will be able to integrate our SIS with MS Teams covering assignments & Submissions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbd1a2e-ef19-a212-e515-d9aa967985df
* Version Independent ID: 9292e7e6-6b37-d821-e678-a7c527902eea
* Content: [educationSubmission resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/educationsubmission?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/educationsubmission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/educationsubmission.md)
* Product: **education**
* GitHub Login: @dipakboyed
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmast-msft** [comment]
The beta assignments and submissions APIs are expected to be moved to production before the end of the year.
