### ISSUE TITLE
Workbooks Table Delete : Wrong route

### ISSUE THREAD

**Issue by ThibaudJeannin** [microsoftgraph/microsoft-graph-docs#4188]
The routes for this requests seem to be wrong and won't work for what I'm trying to achieve : 
```
POST /workbook/tables/{id|name}/delete
POST /workbook/worksheets/{id|name}/tables/{id|name}/delete
```
These routes produce a 400 (Bad Request) as a response.
At first, I thought that deleting an item with a `POST` was absurd, so I tried the same request with a different route and it worked. The route I used was :
```
DELETE /workbook/worksheets/{id|name}/tables/{id|name}
```
and I assume the other one would be 
```
DELETE /workbook/tables/{id|name}
```
If I'm correct, the error I had would be related to the documentation only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6cad19c-f212-6693-88de-4ffd70e991ce
* Version Independent ID: 61494ffd-6dbf-6a8a-8b88-31a7b9eb7d76
* Content: [Table: delete - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/table-delete?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/table-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/table-delete.md)
* Product: **excel**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing this issue as docs have been updated. Thanks.
