### ISSUE TITLE
Mistyped example

### ISSUE THREAD

**Issue by ThibaudJeannin** [microsoftgraph/microsoft-graph-docs#4189]
The example provided in this page (and others pages related to `TableColumn`) is the following :
```json
{
  "id": 1024,
  "index": 1024,
  "name": "string",
  "values": "json"
}
```
However, according to the Properties section, the type of `id` should be `string`, not `int`.
The example should be : 
```json
{
  "id": "1024",
  "index": 1024,
  "name": "string",
  "values": "json"
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15e7266a-6fc1-05a9-a5e8-4c0630a999d6
* Version Independent ID: 98d9dfdc-d14c-03c2-7d78-fd444d9ad199
* Content: [TableColumn resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/tablecolumn?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/tablecolumn.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/tablecolumn.md)
* Product: **excel**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
The page has since been removed and the correct information is now available in the [Table resource page](https://docs.microsoft.com/en-us/graph/api/resources/table?view=graph-rest-1.0).

Closing the issue.
