### ISSUE TITLE
Request method POST, but no request body?

### ISSUE THREAD

**Issue by benanderman** [microsoftgraph/microsoft-graph-docs#4194]
This documentation says to use a POST request, but it sounds like a GET request; it only talks about what will be returned, has nothing in the "Request body" section, and doesn't say anything about what one might send.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52fb41a3-d8b6-05e7-d403-9f2852e02c3c
* Version Independent ID: 234c6662-bc88-2900-7205-7f8b388d91fa
* Content: [NamedItem: Range - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/nameditem-range?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/nameditem-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/nameditem-range.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @benanderman for highlighting the issue. The page was corrected via PR #8556.

No current updates identified for the page. Closing the issue.
