### ISSUE TITLE
Tutorial links 404ing

### ISSUE THREAD

**Issue by bnb** [microsoftgraph/microsoft-graph-docs#4196]
Issue: The newly launched graph page (https://docs.microsoft.com/en-us/graph/) includes several links to 404s, specifically the tutorials links. 

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/index.yml

**Comment by jasonjoh** [comment]
This seems to be fixed now, are you still getting 404 on your end?

**Comment by jasonjoh** [comment]
Closing this as the issue appears to be fixed. Please let us know if you're still having issues here
