### ISSUE TITLE
Unable to update the specified properties for objects that have originated within an external service

### ISSUE THREAD

**Issue by mikesomersgfi** [microsoftgraph/microsoft-graph-docs#4210]
When using the example above in Microsoft Flow (HTTP Action) to add a user to a Mail-Enabled Security Group or Distribution Group, I get this error: 

>Unable to update the specified properties for objects that have originated within an external service. 

In previous posts, this issue was because the Mail-Enabled Security and Distribution groups were not yet supported, but this should no longer be the case, correct? Adding users to the other types of groups using the Flow's HTTP Action works like a charm. FYI: I get the same error when using the "Add user to group" action.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-gb/graph/api/group-post-members?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jimmyengman** [comment]
I get the same error when trying to add member to a mail-enabled security group through graph explorer. No matter if I use v1.0 or beta, same error.

![bild](https://user-images.githubusercontent.com/13765676/57224367-8632bf00-7009-11e9-8660-eecae1941eca.png)

**Comment by Jackson-Woods** [comment]
@krbain Does our documentation say that mail-enabled security groups cannot be edited?

**Comment by davidmu1** [comment]
The overview article for groups states that mail-enabled security groups cannot be created or managed using the API: https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-beta
