### ISSUE TITLE
Is token sample a valid one?

### ISSUE THREAD

**Issue by chesteryang** [microsoftgraph/microsoft-graph-docs#4215]
It looks like that https://jwt.ms failed to decode your sample token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e0d58a-5413-d9ef-b9f7-52bb82c1eb8b
* Version Independent ID: 18b4320d-52b6-3dab-b92b-35eb6093118b
* Content: [Get access tokens to call Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-overview#feedback)
* Content Source: [concepts/auth-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-overview.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @chesteryang for raising your issue. I believe this was a momentary failure at the time. https://jwt.ms/ should now successfully decode your access token. Closing this issue.
