### ISSUE TITLE
Add some more query examples for auditlog

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4221]
Add some examples to show how to use the any filter to query for audit data.  The table doesn't provide enough clarity as is, as to how to formulate the query.
Suggestion - update the table with some real example requests.

As documented leads to customer confusion on how to query

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9290469-4977-69e6-e793-795128559276
* Version Independent ID: 716e324d-c23c-5210-7727-c970f4b64837
* Content: [List directoryAudits - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/directoryaudit-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/directoryaudit-list.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
The particular request that was asked for was what an any() + startswith() looks like.
For context here is what we should add in an example
`GET https://graph.microsoft.com/beta/auditLogs/directoryAudits?$filter=targetResources/any(x: startswith(x/displayName, 'def'))`

**Comment by davidmu1** [comment]
Added the suggested example to the $filter table entry.
