### ISSUE TITLE
How does Graph detect request volumes at a tenant level?

### ISSUE THREAD

**Issue by nabalakr** [microsoftgraph/microsoft-graph-docs#4223]
The statements under "Common throttling scenarios" above need clarification:

- How does MS Graph track request volumes per app at a tenant level and have that available as a real-time feedback when deciding to throttle an incoming request?
- Clients in a tenant are distributed and it is unlikely that they're hitting a single data center when making requests.
- If the data for decision making is not real time, then it is possible for clients to exceed thresholds for whatever duration it takes for the feedback data to be available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling#feedback)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Sorry for the tone it took to get an answer. Over the last few months we've added a lot of information about throttling in the documentation. Since this issue is old, I'll go ahead and close it.
Please review the page and feel free to open more specific issues if some information is still missing
