### ISSUE TITLE
Confusing behaviour of group membership

### ISSUE THREAD

**Issue by thomasgassmann** [microsoftgraph/microsoft-graph-docs#4224]
I'm trying to udpate group membership for Microsoft Teams based on values in a  request. I find this to be hugely confusing. Before trying to add a new group member/owner I check what members/owners the group already has. Microsoft Graph returns the following response:

Members:
- a@tenant.com

Owners:
- a@tenant.com
- b@tenant.com
- c@tenant.com

In Microsoft Teams the following is displayed (as should be):
Members:

Owners:
- a@tenant.com
- b@tenant.com
- c@tenant.com

In the Office 365 Group the following is displayed:
Members:
- b@tenant.com
- c@tenant.com

Owners:
- a@tenant.com

Why and how could this have happened? Does Microsoft Teams, Microsoft Graph and SharePoint use different data sources to check for Group/Team membership? I couldn't find anything in the docs.
Should it even be possible for an user to be owner and member at the same time?
Additionally, SharePoint displays "1 member", but when clicking on it, it displays "3 members" afterwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8c3174-470e-6bd6-0445-eb95526e85ea
* Version Independent ID: bb1a9ace-6ef2-ddef-b6d1-999a891697ab
* Content: [Add group owner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/group-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-owners.md)
* Product: **groups**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
Thanks for the question @thomasgassmann. Indeed Microsoft Teams and SharePoint use different data sources to check for Group/Team membership. So it can lead to confusion like the scenario you pointed out.  Also, it is possible for a user to be both a member and owner of a group at the same time. There's no restriction.
@yyuank @VenkatAyyadevara-MSFT please have a look to see if there are ways to better handle this for consistent results.

**Comment by thomasgassmann** [comment]
@krbain Thanks for the clarification! So, for example, if I wanted to "upgrade" a member of a group to an owner, would it be recommended to delete the member or keep it?

> Indeed Microsoft Teams and SharePoint use different data sources to check for Group/Team membership.
If they use different data sources, then which data source does Microsoft Graph use to determine group membership?

**Comment by EsaHeikkiPoutanen** [comment]
I get:
Code: BadRequest
Message: Unsupported segment type. ODataQuery: /groups/owners/$ref
when using this like the above example

**Comment by yyuank** [comment]
Hi @EsaHeikkiPoutanen, did you specify group id in the request? groups/**{id}**/owners/$ref?

**Comment by EsaHeikkiPoutanen** [comment]
Yes

Hanki Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yyuank** [comment]
@EsaHeikkiPoutanen I tested on graph and got a success 204. Please reference [this doc](https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=http).

**Comment by EsaHeikkiPoutanen** [comment]
Hi Yuan,
You mean in Graph Explorer ? Yes I can do it in there, but not in my Azure function, written in c# and using Microsoft Graph version 1.18.0....

Cheers,
Esa

**Comment by EsaHeikkiPoutanen** [comment]
Here's the peace of code giving me thsi error:

                        await graphClient.Groups[myGroup.Id].Owners.References
                            .Request()
                            .AddAsync(user);

**Comment by EsaHeikkiPoutanen** [comment]
btw. adding members this way (changing Owners to Users in that call) works just fine

**Comment by EsaHeikkiPoutanen** [comment]
umph, sorry, not Users, Members of course

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
