### ISSUE TITLE
Skype Meetings from Graph API

### ISSUE THREAD

**Issue by kesavanpurushothaman** [microsoftgraph/microsoft-graph-docs#4225]
Hi Team, Can we create skype meetings using any of the Graph API. Please provide your comments.
Thanks, Kesavan Purushothaman

**Comment by jthake-msft** [comment]
No, Microsoft Graph only supports Microsoft Teams as it is the strategic direction of Microsoft. There is many details about this on Microsoft teams and Skype for Business web sites.
