### ISSUE TITLE
No Body - Not Managed

### ISSUE THREAD

**Issue by MysticRyuujin** [microsoftgraph/microsoft-graph-docs#4226]
The example does not show the body to be posted.

Also, I'm currently having 403 errors when trying to list managed resources, when there are no managed resources. But then how do you get the ExternalId of a subscription that isn't managed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff46d9cc-0523-d47e-8856-dea4a53f0c8e
* Version Independent ID: 0a39faf3-7d2e-b605-0fa2-3cf9cd28e1c5
* Content: [Register governanceResource - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governanceresource-register?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/governanceresource-register.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceresource-register.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by t1agob** [comment]
Is there any feedback on this issue? It has been open for 3 months and it is not clear what should be the body of this request. and what is the ExternalId of a subscription?

Any help would be much appreciated.

**Comment by Lauragra** [comment]
@davidmu1 , can you look into this please?

**Comment by MysticRyuujin** [comment]
I figured it out myself, but it should still be fixed in the docs...

Body would be:
```
{
    "externalId": "/subscriptions/$subscriptionId"
}
```

Where `$subscriptionId` is just your actual subscription guid

**Comment by Lauragra** [comment]
Thanks. I'll keep this open to track getting the update to the doc.

**Comment by davidmu1** [comment]
Added the body and a description of using the subscription id.
