### ISSUE TITLE
BusinessFlowId

### ISSUE THREAD

**Issue by MysticRyuujin** [microsoftgraph/microsoft-graph-docs#4227]
What is a `BusinessFlowId` how do I create one? How do I list one? Where is its definition?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16eb36c4-eb4d-f3e7-f0fc-33119c304cbb
* Version Independent ID: 76ec1128-fbe0-0231-5f67-f09f82cde386
* Content: [Get governanceRoleSetting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governancerolesetting-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/governancerolesetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governancerolesetting-get.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ystrte** [comment]
Any updates here? Almost a year and no one can answer what BusinessFlowId is?

**Comment by MysticRyuujin** [comment]
I ignored it, it doesn't seem to matter for calling the API.

**Comment by shauliu** [comment]
Hi there, this attribute is for internal use to setup approvers for a role. We are still looking at a user friendly way to expose an API for this functionality. Just leaving it as is when updating the role setting should be fine.

**Comment by shauliu** [comment]
Closing this issue
