### ISSUE TITLE
Contacts are breaking the .NET Graph SDK v1.12-1.14

### ISSUE THREAD

**Issue by mtmjansen** [microsoftgraph/microsoft-graph-docs#4238]
Microsoft Graph Reference / Groups / Group / List members

This request now also returns contacts as members. 
Contacts are NOT  derived from DirectoryObject.
This is breaking the .NET SDK ver 1.12-1.14 :
Task&lt;IGroupMembersCollectionWithReferencesPage&gt; IGroupMembersCollectionWithReferencesRequest.GetAsync();
public interface IGroupMembersCollectionWithReferencesPage : ICollectionPage&lt;DirectoryObject&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Closing this as https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/415 covered
