### ISSUE TITLE
Get connectorGroups does not work

### ISSUE THREAD

**Issue by AleksandrIakhnev** [microsoftgraph/microsoft-graph-docs#4240]
Does this endpoint actually work? It returns status 400 "Resource not found for the segment 'connectorGroups" when I try it from Graph Explorer (both for beta and v1.0 versions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b24e2eb-f24b-81ac-f43e-02823033aa6b
* Version Independent ID: 23881ce5-590c-53bb-b7a0-a5c737cebb9c
* Content: [List connectorGroups - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/connectorgroup-list?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/connectorgroup-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/connectorgroup-list.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Works in beta. No change identified for the page. Closing the issue.
