### ISSUE TITLE
Listed TimeZone not valid

### ISSUE THREAD

**Issue by TaskListGuy** [microsoftgraph/microsoft-graph-docs#4242]
Using TimeZone "America/New_York" as listed is not valid. This was tested using the .NET SDK. "Eastern Standard Time", however, works. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e773d204-1933-45d8-17b2-5868787e25ca
* Version Independent ID: 9d5477ea-fe33-6234-94cf-fdfe3c3ecb9e
* Content: [dateTimeTimeZone resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/datetimetimezone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/datetimetimezone.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mj1856** [comment]
If this is indeed the case, then it's not a docs issue but a product issue.  Both formats should be supported.

**Comment by shangec** [comment]
Hi, i'm in shenzhen china, but when i use TimeZone "Asia/Shanghai" in my code, it's not valid, Does anyone help me? thanks.

**Comment by FaithOmbongi** [comment]
@TaskListGuy , @shangec  
**America/New_York** and **Asia/Shanghai** are clearly listed as supported in the [additional timezones](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-1.0#additional-time-zones) list. If you can't use them, then this is a product/functionality issue, as @mj1856 has pointed out.

Unfortunately this forum isn't monitored for product/functionality issues, but issues like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
