### ISSUE TITLE
The example script provided above to make the change uses the wrong syntax

### ISSUE THREAD

**Issue by JSchulleratWork** [microsoftgraph/microsoft-graph-docs#4243]
Hello.  The example script provided above to make the change uses the wrong syntax to reference the json file.

Example provided
ARMClient.exe put https://management.azure.com/providers/Microsoft.SecurityGraph/diagnosticSettings/securityApiAlerts?api-version=2017-04-01-preview  @".\AzMonConfig.json"

What should be (and works) 
ARMClient.exe put https://management.azure.com/providers/Microsoft.SecurityGraph/diagnosticSettings/securityApiAlerts?api-version=2017-04-01-preview  @'AzMonConfig.json'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b018d05c-4f26-ccce-df84-900d4e301b7b
* Version Independent ID: 8f90b82c-4fdc-9827-e7a3-54c5b5b524d1
* Content: [Integrate Microsoft Graph Security API alerts with IBM QRadar SIEM using Azure Monitor - Microsoft Graph](https://docs.microsoft.com/en-us/graph/security-qradar-siemintegration#feedback)
* Content Source: [concepts/security-qradar-siemintegration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/security-qradar-siemintegration.md)
* Product: **security**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by preetikr** [comment]
We've changed the approach to connect Microsoft Graph Security API alerts with SIEM with new connectors to provide coverage for all security providers and in an effort to improve the alert experience - refer to the https://aka.ms/graphsecuritysolutionsconnectors and https://aka.ms/graphsecuritysplunkaddonblogpost for further details. Thanks.
