### ISSUE TITLE
How to query for event conflicts using calendarView?

### ISSUE THREAD

**Issue by klassicd** [microsoftgraph/microsoft-graph-docs#4252]
I'm trying to use the [calendarView API](https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0) to retrieve any possible event conflicts in a date range. 

The problem I'm noticing is that it won't return events that:

 - Started before the `startDateTime`, and end on or before the `endDateTime`.
 - Started on or after the `startDateTime`, and end after the `endDateTime`.
 - Started before the `startDateTime`, and end after the `endDateTime`. 

Previously, with the [events API](https://docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0) I was able to user `$filter`.  I had to move away from this API because it didn't return recurring events.  The calendarView API throws an error when I try to `$filter` these date fields. 

    (start/dateTime ge '${startDate}' and start/dateTime lt '${endDate}')
    or
    (end/dateTime gt '${startDate}' and end/dateTime le '${endDate}') 
    or
    (start/dateTime lt '${startDate}' and end/dateTime gt '${endDate}')

What's the ideal way to accomplish this? Should I be using a completely different API?  I wasn't sure if this was a documentation issue or underlying limitation of the Graph API so I also posted here: https://stackoverflow.com/questions/55360648/how-to-query-for-event-conflicts-using-calendarview

**Comment by jasonjoh** [comment]
@klassicd Using a calendar view (which itself has a start and end time) sort of inherently filters by start and end for you. I'm not clear what value your filters would add here, but I may be missing some nuance.

**Comment by klassicd** [comment]
The calendar view startDateTime/endDateTime parameters do not find events that:

- Started before the startDateTime, and end on or before the endDateTime.
- Started on or after the startDateTime, and end after the endDateTime.
- Started before the startDateTime, and end after the endDateTime.

I should point out that Google's event search does.

A commentor pointed out on https://stackoverflow.com/questions/55360648/how-to-query-for-event-conflicts-using-calendarview that I need to use the free/busy API instead to find these type of conflicts.

I believe this will work for my use case, although one limitation of free/busy is you don't get the conflict event ID.

I'm closing this for now because it's not a documentation issue.
