### ISSUE TITLE
More clarity required on shared schema extensions

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4253]
We've been receiving confused messages about the notion of shared schema extensions, since this is contrary to our standard mode of operation where APIs only get data in the app/signed-in user's tenant context.  Add some more clarity on the difference of this API.  Probably requires an update to the conceptual topic and the GET topics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d950a443-0656-d29b-6a3b-d18c2f5d092c
* Version Independent ID: 424c99df-a666-7303-5b23-3f03b14aecc0
* Content: [List schemaExtensions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/schemaextension-list.md)
* Product: **non-product-specific**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by michevnew** [comment]
I second that. Currently, querying /v1.0/schemaExtensions gives a huge list of extensions, and it's easy to see that most of these are just tests from people playing with the API, and not anything relevant to the current tenant/user.
