### ISSUE TITLE
Display Name of Section not Updating After Rename

### ISSUE THREAD

**Issue by AntLaC** [microsoftgraph/microsoft-graph-docs#4255]
When a user renames a section in OneNote, the DisplayName remains the original name. Is there another field to be looked at? I'm not seeing anything in the API response.

Issue: 

Article:

**Comment by jthake-msft** [comment]
Could you provide more information here including screen shots of before and after repro'ing this? and your request /responses from API?

**Comment by AntLaC** [comment]
Screen Shot of name change - the bottom section tab is the changed section name, Data DevOps - Test Name:
![image](https://user-images.githubusercontent.com/2325226/55109212-821e9380-5092-11e9-8487-5da787321835.png)

API request to get list of sections:
`https://graph.microsoft.com/v1.0/sites/{site-id}/onenote/notebooks/{notebook-id}?expand=sections`

API response - with just the section in question to simplify:
`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('{site-id}')/onenote/notebooks/$entity",
    "id": "{notebook-id}",
    "self": "https://graph.microsoft.com/v1.0/sites/{site-id}/onenote/notebooks/{notebook-id}",
    "createdDateTime": "2017-04-26T17:20:14Z",
    "displayName": "Dev-Ops Notebook",
    "lastModifiedDateTime": "2019-03-26T23:13:30Z",
    "isDefault": false,
    "userRole": "Owner",
    "isShared": false,
    "sectionsUrl": "https://graph.microsoft.com/v1.0/sites/{site-id}/onenote/notebooks/{notebook-id}/sections",
    "sectionGroupsUrl": "https://graph.microsoft.com/v1.0/sites/{site-id}/onenote/notebooks/{notebook-id}/sectionGroups",
    "createdBy": {
        "user": {
            "id": "{user-id}",
            "displayName": "{User Name}"
        }
    },
    "lastModifiedBy": {
        "user": {
            "id": "{user-id}",
            "displayName": "{User Name}"
        }
    },
    "links": {
        "oneNoteClientUrl": {
            "href": "onenote:https://{company.sharepoint.com}/sites/dev-ops/SiteAssets/Dev-Ops%20Notebook"
        },
        "oneNoteWebUrl": {
            "href": "https://{company.sharepoint.com}/sites/dev-ops/SiteAssets/Dev-Ops%20Notebook"
        }
    },
    "sections@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites('{site-id}')/onenote/notebooks('{notebook-id}')/sections",
    "sections": [
        {
            "id": "{section-id}",
            "self": "https://graph.microsoft.com/v1.0/sites/{site-id}/onenote/sections/{section-id}",
            "createdDateTime": "2018-06-14T21:16:43Z",
            "displayName": "Data DevOps",
            "lastModifiedDateTime": "2019-03-26T23:33:28Z",
            "isDefault": false,
            "pagesUrl": "https://graph.microsoft.com/v1.0/sites/{site-id}/onenote/sections/{section-id}/pages",
            "createdBy": {
                "user": {
                    "id": "{user-id}",
                    "displayName": "{User Name}"
                }
            },
            "lastModifiedBy": {
                "user": {
                    "id": "{user-id}",
                    "displayName": "{User Name}"
                }
            },
            "links": {
                "oneNoteClientUrl": {
                    "href": "onenote:https://{company.sharepoint.com}/sites/dev-ops/SiteAssets/Dev-Ops%20Notebook/Data%20DevOps.one"
                },
                "oneNoteWebUrl": {
                    "href": "https://{company.sharepoint.com}/sites/dev-ops/SiteAssets/Dev-Ops%20Notebook?wd=target%28%2F%2FData%20DevOps.one%7C%2F%29"
                }
            }
        }
    ]
}`


You will see the `displayName` for the section is **NOT** the same as the screen shot.

**Comment by AntLaC** [comment]
Some more info to add...
The updated name is preserved when opening the notebook by other users in a browser, but still not the API call.

When opening the notebook in the desktop app, you will see the old name, but once it syncs it shows the new name - and, after this sync with the desktop app, the API starts showing the correct updated display name.

**Comment by fridden** [comment]
I am having similar issues with the displayname of sections.  

I use OneNote webb app and create a notebook.
It will create one default section with a default name.
I create a second section and name it "S2".
I change the name of the first section and name it "S1"

I list the section through the API and it will return the correct name for S2, but the default name for section 1.

I synchronize the notebook with OneNote 2016, and now the correct name is returned in the API call as well.

**Comment by JulienG-Sinequa** [comment]
We are having similar issue with the API.

A notebook created with the web app will always have the section names as originally created when accessed through the OneNote endpoint, and the file names of the sections access through the OneDrive endpoints also match the original name of the section, event after multiple renames.

Accessing the notebooks through OneNote 2016 is not an option in our case. We need to have the correct section name returned from the API in all cases.

**Comment by monichol92** [comment]
Hey all! My name is Monique and I'm a program manager with the Microsoft OneNote team. This issue is a known issue and we will take care to keep this post updated when any progress is made.

**Comment by vikrantsingh47** [comment]
> Hey all! My name is Monique and I'm a program manager with the Microsoft OneNote team. This issue is a known issue and we will take care to keep this post updated when any progress is made.

this issue is still not resolved. the section names keep reverting back to old names. this is so frustrating. also there should be an option to take automatic backups of the notebooks, as i lost a section completely even though it was synced properly.

**Comment by gregsohl** [comment]
Still happening, I've renamed the 3rd and 4th sections more times that I can remember:

![image](https://user-images.githubusercontent.com/1578466/112416915-98e53880-8cf4-11eb-9587-263e27de10b8.png)

They always revert back to "New Section Group" and "New Section Group 2".

**Comment by coupalm** [comment]
@monichol92  Is someone looking at this? Still not working. Trying to implement OneNote customer solutions with Graph API but does not work....
