### ISSUE TITLE
Complete example on ASP.NET MVC is needed

### ISSUE THREAD

**Issue by ridife** [microsoftgraph/microsoft-graph-docs#4259]
the Graph API explorer doesnt support this scenario. Therefore, The complete example is needed  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create online meeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **microsoft-teams**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
@ksikorsk Can you provide?

**Comment by ksikorsk** [comment]
These are the samples we have.  No MVC samples as these are service bots.  User scenarios are still under development.

https://github.com/microsoftgraph/microsoft-graph-comms-samples
