### ISSUE TITLE
Impossible to filter event by organizer email address

### ISSUE THREAD

**Issue by marcussaad** [microsoftgraph/microsoft-graph-docs#426]
Calling `/v1.0/me/events?$filter=organizer/emailAddress/address eq 'WHATEVEREMAIL&$select=createdDateTime, organizer, start, end, attendees&$orderby=createdDateTime desc&$top=1` returns :

``` javascript
{
  "error": {
    "code": "UnsupportedEntityExpression",
    "message": "'i => (i.Organizer.EmailAddress == \"WHATEVEREMAIL\")' is not a supported filter expression."
  }
}
```

Any ideas..?

**Comment by DianeD** [comment]
Reproduced and opened a bug. Thanks for reporting @marcussaad !

**Comment by Rishabhadept** [comment]
I am still facing this issue as I need to get meeting based on organizer email address.
Is this bug not fixed yet?

**Comment by koreanilkumar** [comment]
it is still reproducing.

**Comment by blexis** [comment]
this issue still continue to exists after 3 years of the first report.

**Comment by ajalex114** [comment]
Still facing the problem.

Tried the following : 
**Request 1**
`https://graph.microsoft.com/v1.0/me/events?$filter=organizer.emailAddress.address eq 'test@example.com'`

**Response**
`Bad Request - 400 - 620ms`

_Snippet_

```csharp
The child type 'organizer.emailAddress.address' in a cast was not an entity type. Casts can only be performed on entity types.
```

**Request 2**
`https://graph.microsoft.com/v1.0/me/events?$filter=organizer/emailAddress/address eq 'test@example.com'`

**Response 2**
`Not Implemented - 501 - 402ms`

_Snippet_

```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var events = await graphClient.Me.Events
	.Request()
	.Filter("organizer/emailAddress/address eq 'test@example.com'")
	.GetAsync();
```

_Note: I'm using Microsoft Graph Explorer_

**Comment by martindr** [comment]
I'm using a different endpoint but I also find I cannot filter on organizer Email address.

https://graph.microsoft.com/v1.0/users/<user-email>/calendar/calendarView?startDateTime=2019-03-03T12:28:57&endDateTime=2021-03-03T12:28:57&$filter=organizer/emailAddress/address eq '<organizer-email>'

I don't encounter an error but get back an empty array. If I filter instead on organizer Name then the query returns results fine.

**Comment by joshidp** [comment]
any update on this issue? I am also getting the empty array while filtering based on the organizer email address.

**Comment by isvargasmsft** [comment]
Hello, 

My deepest apologies for the delays in my response. 

Unfortunately, filtering by organizer email address is not supported yet and there is no plan to change it in the upcoming months.

As a workaround, filtering by organizer name is supported. 

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at Microsoft Q&A: [Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).

Kind regards, 

Isaac Vargas
