### ISSUE TITLE
Two property names are incorrect (have old AAD Graph names)

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4260]
Some of the organization property names are incorrect. Organization object does have neither companyLastDirSyncTime nor dirSyncEnabled. 
Correct property names should be: 
- onPremisesLastSyncDateTime 
- onPremisesSyncEnabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb2f84e-bdb1-cc44-c27a-4a5cf98edca9
* Version Independent ID: 20aa3e3e-2f05-f307-fb36-2281cafc1cbf
* Content: [organization resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/organization.md)
* Product: **microsoft-identity-platform**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Updated the property names.
