### ISSUE TITLE
A new password is always required in a passwordProfile PATCH

### ISSUE THREAD

**Issue by andrewliddell** [microsoftgraph/microsoft-graph-docs#4267]
The documentation states, for the password property, that "This property is required when a user is created. ", but it is always required when setting forceChangePasswordNextSignIn:true.

It would be great if a PATCH could be made in this form:

```
{ "passwordProfile" : { "forceChangePasswordNextSignIn" : true }}
```

which would force the user to change their password when they next sign in with their existing password - this would replicate this powershell command:

```
Set-MsolUserPassword -UserPrincipalName a.user@adomain.onmicrosoft.com -ForceChangePassword:$true -ForceChangePasswordOnly:$true
```

At present, trying to force a password change without supplying a new password results in a 204 as if it has been successful, but nothing happens. Either this functionality should be changed, or the documentation should be updated to make it clearer that a new password must always be supplied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0af34f7d-edee-2f33-e6b7-2e5be74ac80f
* Version Independent ID: 84a1d515-67c3-3a44-4bfd-114632bf96fa
* Content: [passwordProfile resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/passwordprofile?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/passwordprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/passwordprofile.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@andrewliddell Sorry for the late response here.  This is a service bug.  It's being fixed.  Will update when I have more info.

**Comment by abagri** [comment]
Any update on this?

**Comment by dkershaw10** [comment]
This fix is rolling out through the deployment rings.  Unfortunately this can take a while.  Looking at this fully deploying world-wide in production by end of next week.

**Comment by abagri** [comment]
Thank you. Looking forward.

**Comment by dkershaw10** [comment]
It looks like this has finally deployed and should be working now according to spec.
