### ISSUE TITLE
Displayname of OneNote tab changes on first access

### ISSUE THREAD

**Issue by NCSTman** [microsoftgraph/microsoft-graph-docs#4271]
After creating a OneNote tab properly when I go to access the tab for the first time in teams, whether on web app or desktop app, the displayname always changes from whatever I set it originally to just "note". Can't wrap my head around this one, any suggestions from anybody?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#feedback)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by NCSTman** [comment]
Never mind I figured it, for those that would need help see below.

The contentURL and removeURLs has the &notebookName=note as shown above. 'note' is actually variable, so set that as remove if you're working dynamically with onenote notebook creations [ex- I am designing an MS Flow to create a notebook based off a a Dynamics account name, so I just set that portion of a variable so the tab looks nice.]

**Comment by nkramer** [comment]
Reopening to track fixing the docs

**Comment by nkramer** [comment]
(And thanks for pointing this out!)

**Comment by PzKfWg** [comment]
Thanks so much for pointing this out!

**Comment by ashoksubedi1** [comment]
How do I find the ranomguidId for onenote tab I have notebookid but how do I get the randomguidid ? what should I query to find that ?

**Comment by PzKfWg** [comment]
Just checked what I did and to generate the entityId, I generated a GUID on the fly (in Azure Logic App, it is simply guid() ), added a '_' and then the notebookId. So just concatenate "Guid_NotebookID". Generating a random GUID depends on your programming language.

**Comment by Meghana-MSFT** [comment]
@NCSTman - Currently as soon as we select a Onenote notebook, tab name changes to the name of the notebook that you selecteded.  Also Configuration is not supported in OneNote tabs.
