### ISSUE TITLE
id property is not in GUID format in directoryAudit resource type

### ISSUE THREAD

**Issue by o365developer** [microsoftgraph/microsoft-graph-docs#4279]
>Id- Indicates the unique ID for the activity. This is a GUID.

But the property is not in the GUID format. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46e67064-841e-27e5-1770-b7730d560c7d
* Version Independent ID: a79f0b1e-dc2e-754a-eee7-2c6c3d92efd4
* Content: [directoryAudit resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/directoryaudit?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/directoryaudit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/directoryaudit.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @o365developer for catching error. We'll fix this and close the issue.
