### ISSUE TITLE
Wrong responseType values

### ISSUE THREAD

**Issue by Nagapito** [microsoftgraph/microsoft-graph-docs#4282]
The values described here are all Camel Cased but the response from the API is all lower case

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8837ed-fee9-835f-c724-88b2cea5688b
* Version Independent ID: cf38a184-7667-1039-c0b2-d1c6f2bcc95a
* Content: [responseStatus resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/responsestatus.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by giveitaGo** [comment]
Also, I'm seeing "noResponse" instead of "NotResponded". This needs to be updated

**Comment by angelgolfer-ms** [comment]
@giveitaGo , can you please clarify if you got the responseStatus property as part of an event, or as part of an attendee?

**Comment by giveitaGo** [comment]
At the moment, I am using the Graph explorer to hit me/calendar/events. I am looking at the responseStatus which looks like:

"responseStatus": {
        "response": "notResponded",
        "time": "0001-01-01T00:00:00Z"
}

Here is what an attendee looks like:
{
     "type": "required",
     "status": {
         "response": "none",
         "time": "0001-01-01T00:00:00Z"
      },
     "emailAddress": {
         "name": "John Doe",
         "address": "john.doe@contoso.com"
     }
}

Perhaps this documentation was intended for response under an attendee, not responseStatus for an event?

**Comment by angelgolfer-ms** [comment]
Hi @giveitaGo , may I clarify my question - you mentioned the following:
>>  I'm seeing "noResponse" instead of "NotResponded".

Can you show the request and response for this please?

**Comment by nagapito-fruition** [comment]
Hi,
I noticed a mistake on my comment.
When I mean the API respondes is lower case I mean, LowerCamelCase instead of UpperCamelCase as its described in the documentation.

**Comment by Nagapito** [comment]
Hi,
I noticed a mistake on my comment.
When I mean the API respondes is lower case I mean, LowerCamelCase instead of UpperCamelCase as its described in the documentation.

**Comment by giveitaGo** [comment]
@angelgolfer-ms, 

Here is my request:
(GET) https://graph.microsoft.com/v1.0/me/calendar/events

Here is my response (cleaned, and only showing one event record):

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('89df4a6d-1234-4321-1234-aa18bc18b9a6')/calendar/events",
    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/calendar/events?$skip=10",
    "value": [
        {
            "@odata.etag": "W/\"iCTE/HGTBIGLONGUGLYSTRINGxtg==\"",
            "id": "AAMkAGVlOTc3ZGIxLTRiBIGLONGUGLYSTRINGCIJMT8cZOrSJAU1Mzc4stIAAAAAJRdAAA=",
            "createdDateTime": "2019-07-09T20:05:09.5425616Z",
            "lastModifiedDateTime": "2019-07-10T02:41:22.1604995Z",
            "changeKey": "iCTE/HGTBIGLONGUGLYSTRINGzFxtg==",
            "categories": [],
            "originalStartTimeZone": "Mountain Standard Time",
            "originalEndTimeZone": "Mountain Standard Time",
            "iCalUId": "040000008200E00074BIGLONGUGLYSTRINGE109449C886C4567810BF9",
            "reminderMinutesBeforeStart": 15,
            "isReminderOn": true,
            "hasAttachments": false,
            "subject": "John Doe working Remotely",
            "bodyPreview": "I will be working remotely every Tuesday unless there is an onsite, meeting, or Lunch and Learn that I need to be there physically.",
            "importance": "normal",
            "sensitivity": "normal",
            "isAllDay": false,
            "isCancelled": false,
            "isOrganizer": false,
            "responseRequested": true,
            "seriesMasterId": null,
            "showAs": "tentative",
            "type": "seriesMaster",
            "webLink": "https://outlook.office365.com/owa/?itemid=AAMkAGBIGLONGUGLYSTRINGAAAJRdAAA%3D&exvsurl=1&path=/calendar/item",
            "onlineMeetingUrl": null,
            "responseStatus": {
                "response": "tentativelyAccepted",
                "time": "2019-07-09T20:05:00Z"
            },
            "body": {
                "contentType": "html",
                "content": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<meta content=\"text/html; charset=us-ascii\">\r\n<meta name=\"Generator\" content=\"Microsoft Word 15 (filtered medium)\">\r\n<style>\r\n\r\n</style>\r\n</head>\r\n<body lang=\"EN-US\" link=\"#0563C1\" vlink=\"#954F72\">\r\n<div class=\"WordSection1\">\r\n<p class=\"MsoNormal\"><span style=\"font-size:11.0pt\">I will be working remotely every Tuesday unless there is an onsite, meeting, or Lunch and Learn that I need to be there physically.\r\n<br>\r\n</span></p>\r\n</div>\r\n</body>\r\n</html>\r\n"
            },
            "start": {
                "dateTime": "2019-07-09T14:30:00.0000000",
                "timeZone": "UTC"
            },
            "end": {
                "dateTime": "2019-07-10T14:30:00.0000000",
                "timeZone": "UTC"
            },
            "location": {
                "displayName": "",
                "locationType": "default",
                "uniqueIdType": "unknown",
                "address": {},
                "coordinates": {}
            },
            "locations": [],
            "recurrence": {
                "pattern": {
                    "type": "weekly",
                    "interval": 1,
                    "month": 0,
                    "dayOfMonth": 0,
                    "daysOfWeek": [
                        "tuesday"
                    ],
                    "firstDayOfWeek": "sunday",
                    "index": "first"
                },
                "range": {
                    "type": "endDate",
                    "startDate": "2019-07-09",
                    "endDate": "2020-01-09",
                    "recurrenceTimeZone": "Mountain Standard Time",
                    "numberOfOccurrences": 0
                }
            },
            "attendees": [
                {
                    "type": "required",
                    "status": {
                        "response": "none",
                        "time": "0001-01-01T00:00:00Z"
                    },
                    "emailAddress": {
                        "name": "John Doe",
                        "address": "john.doe@contoso.com"
                    }
                },
                {
                    "type": "required",
                    "status": {
                        "response": "none",
                        "time": "0001-01-01T00:00:00Z"
                    },
                    "emailAddress": {
                        "name": "SharePoint",
                        "address": "spteam@contoso.com"
                    }
                },
                {
                    "type": "optional",
                    "status": {
                        "response": "accepted",
                        "time": "0001-01-01T00:00:00Z"
                    },
                    "emailAddress": {
                        "name": "Jane Doe",
                        "address": "Jane.doe@contoso.com"
                    }
                },
                {
                    "type": "optional",
                    "status": {
                        "response": "tentativelyAccepted",
                        "time": "0001-01-01T00:00:00Z"
                    },
                    "emailAddress": {
                        "name": "John Wayne",
                        "address": "john.wayne@contoso.com"
                    }
                }
            ],
            "organizer": {
                "emailAddress": {
                    "name": "John Doe",
                    "address": "John.doe@contoso.com"
                }
            }
        }
    ]
}
