### ISSUE TITLE
Document is missing from menu

### ISSUE THREAD

**Issue by BenWhite27** [microsoftgraph/microsoft-graph-docs#4291]
This document seems to be missing from the side Navigation menu.  I've checked under Files&gt;DriveItems and couldn't find as link to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e87dfc28-095a-f2f3-99a7-d2323e564f7a
* Version Independent ID: 933f5fa6-a7f6-c4f5-c6f0-b81cbbcad84b
* Content: [Check Out Files - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-checkout?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/driveitem-checkout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-checkout.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by FaithOmbongi** [comment]
Page has since been added to the navigation tree. Thank you @BenWhite27 for highlighting the oversight.

No updates identified for the page. Closing the issue.
