### ISSUE TITLE
Requires information on how to discard a check-out.

### ISSUE THREAD

**Issue by BenWhite27** [microsoftgraph/microsoft-graph-docs#4293]
No information here on how to discard a check-out.  Unless the API forces you to check-in a new version but you are also forced to provide a comment?  Doesn't feel right to do a check-in with something like "Undoing pending changes".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13c0408-7bbe-485f-aeef-b9dd14fd7ae3
* Version Independent ID: 53548df3-7d53-bc9d-a2e1-5eb0298132cb
* Content: [Check In Files - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-checkin?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/driveitem-checkin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-checkin.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by schaeferto** [comment]
Having the same problem. In the SP Rest API there is a `/UndoCheckout` endpoint to discard a checkout. In the current Graph library this feature seems to be missing.

**Comment by LeoGoGarcia** [comment]
Even: I'm receiving a message "The file is not checked out" but I can't find a file status under GraphAPI

**Comment by schaeferto** [comment]
As I mentioned here #5046, you can get the CheckOutUser for the file status. But I miss the endpoint to **UNDO** a checkout instead of checking the file in (which generates a new version of that file).

**Comment by 23W** [comment]
> As I mentioned here #5046, you can get the CheckOutUser for the file status. But I miss the endpoint to **UNDO** a checkout instead of checking the file in (which generates a new version of that file).

Do you.know, is there way how to detect version number (id) for which check-out operation had been done, so as to perform rollback to it?
