### ISSUE TITLE
remove parameter from user

### ISSUE THREAD

**Issue by martinamalkova** [microsoftgraph/microsoft-graph-docs#4299]
How can I remove some parameter from the user? With PATCH request I am not able to null some value, or is there any possibility (like json patch)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@martinamalkova - Can you be more specific about which property you were trying to make null?

**Comment by davidmu1** [comment]
Closing the issue until more information can be provided.

**Comment by ross-currie** [comment]
The following seems to do the trick for most string attributes (including extension attributes)
{
  "Department": null,
  "jobTitle": null
}

Assume this would also work for multi-value string attributes (businessPhones for example), but doesn't seem to work with reference values like manager (which, admittedly has to be updated using the [Assign a Manager](https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http) example anyway).

**Comment by omnifreefall** [comment]
{ "city": null } did NOT work for me

**Comment by blyw** [comment]
I am using the Graph C# SDK. The problematic property is 'department'. Setting the property to null or string.Empty does not clear the property. The property 'OfficeLocation' is also affected. For now, I will put a hyphen whenever possible. I compared to the REST API. There null works, but "" would throws an error.

Somebody please make a note somewhere. Naturally, a fix would be better.
