### ISSUE TITLE
Merge JavaScript and NodeJS in the Supported Platforms grid

### ISSUE THREAD

**Issue by SPDoctor** [microsoftgraph/microsoft-graph-docs#4304]
Issue: 
Under the Supported platforms heading there is a grid of Quickstarts, Tutorials and SDKs. JavaScript and Node.js have their own columns but the only entry under JavaScript is the msgraph-sdk-javascript link which is the same SDK as under Node.js. This is probably just going to be confusing to users, and the grid will look better if you just merge the two columns and call it JavaScript or Node/JavaScript.

Article:
Home page for Microsoft Graph documentation: https://docs.microsoft.com/en-us/graph/

**Comment by jasonjoh** [comment]
Thanks for the feedback @SPDoctor. There is only one JS SDK, it's used in both JS SPA apps in the browser and in Node.js server-side apps. (Note the JS SDK is also listed under Angular!). It's on our backlog to create a tutorial and quickstart for "plain-old" JavaScript, though we may rethink that if there's not much demand over SPA's that use a popular framework like Angular or React.
