### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by kayjtea** [microsoftgraph/microsoft-graph-docs#4305]
An example showing any filters that are supported would be helpful. For example, this returns "HTTP 400 specified filter to the reference property query is currently not supported"

https://graph.microsoft.com/v1.0/me/memberOf?$filter=securityEnabled eq true

Alternatively, stating that no filters are currently supported would also be helfpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9188ffdb-b7af-597d-9e0a-d92e75ff8e7d
* Version Independent ID: c4427823-3f37-dc4b-ac1e-b750cb633e23
* Content: [List memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-memberof.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Schuer84** [comment]
The documentation states this already: 

Optional query parameters
This method supports the OData Query Parameters to help customize the response. **$filter is not supported.**

**Comment by Jackson-Woods** [comment]
This isn't supported currently, please file a feature request on the Microsoft Graph UserVoice (https://microsoftgraph.uservoice.com/).
