### ISSUE TITLE
If you don't add owner as member you got counting problem + problem creating planner

### ISSUE THREAD

**Issue by thunem** [microsoftgraph/microsoft-graph-docs#4310]
If you create a group with a single user as owner you got no "group" icon in SharePoint. Then you having problem adding members without going into Office 365 administration. You also get the problem to add new planner since the user is not a member.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adrichema** [comment]
The SDK for C# does not show how to add owners and members.

**Comment by gclark01** [comment]
The note referenced [here](https://docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-1.0&tabs=http), should also be added to the Create Group documentation

Note:  When you create a new group by using Create group, you are not added to the group as a member. After the group is created, add yourself as a member by using group post members.

**Comment by davidmu1** [comment]
I don't think the note is needed on the create group page. It is only an issue for creating a plan and the note exists there. No change identified for this page. Closing the issue.

**Comment by gclark01** [comment]
@davidmu1 - the only reason I called that out is we have customers that create Groups via Graph, but then users try to create a Planner from the Teams client and it fails.
