### ISSUE TITLE
Missing AD-OnPremise property "Description"

### ISSUE THREAD

**Issue by RedBlue1776** [microsoftgraph/microsoft-graph-docs#4311]
The on premise AD account field "Description" is missing in AzureAD Graph, and missing from the commandlets.  We use this field to annotate information for administrators and occasionally for provisioning purposes.  I inspected the Exchange endpoint, and the User endpoint. neither contain the desired object and text.

Also, it would be nice to get the last login for the user (if possible)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8446021-6786-c54c-066f-d99ba4644312
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
This isn't supported currently, please file a feature request on the Microsoft Graph UserVoice (https://microsoftgraph.uservoice.com/).
