### ISSUE TITLE
getSharePointSiteUsageSiteCounts method description duplicate

### ISSUE THREAD

**Issue by ejazhussain** [microsoftgraph/microsoft-graph-docs#4313]
It seems like getSharePointSiteUsageSiteCounts method description is duplicated from  getSharePointSiteUsageFileCounts. Below description is used for both methods.

## Get the total number of files across all sites and the number of active files. A file (user or system) is considered active if it has been saved, synced, modified, or shared within the specified time period.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35a7127-dcd0-83db-8e8d-79ccaf72c10b
* Version Independent ID: 8772e9c1-90a0-8d06-3da6-a5bbdc9add1e
* Content: [reportRoot: getSharePointSiteUsageSiteCounts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getsharepointsiteusagesitecounts?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/reportroot-getsharepointsiteusagesitecounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/reportroot-getsharepointsiteusagesitecounts.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing this issue as the doc has been updated.
