### ISSUE TITLE
How to concatenate the filter operators correctly

### ISSUE THREAD

**Issue by hosebei** [microsoftgraph/microsoft-graph-docs#4319]
I would love to see an example, how to concatenate the operators "and" and "or" correctly together. 
As example:
value01 -eq true and (value02 -eq true or value03 -eq false)
is not possible as I understand? I need to use a query like:
value01 -eq true and value02 -eq true or value01 -eq true and value03 -eq false
Am I correct? Because I cannot use parentheses in any form within the request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#feedback)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jjtbsomhorst** [comment]
it should work similar like: https://www.odata.org/getting-started/basic-tutorial/

**Comment by FaithOmbongi** [comment]
A few additional examples have been added to [Query parameters](https://review.docs.microsoft.com/en-us/graph/query-parameters?branch=pr-en-us-13212#examples-using-the-filter-query-operator) article since this issue was raised. Kindly check it out and advise if the guidance is adequate.
