### ISSUE TITLE
When will this be out of preview/beta?

### ISSUE THREAD

**Issue by tpmeredith** [microsoftgraph/microsoft-graph-docs#4321]
When will the calling functionality for API be out of beta/preview? This is a critical gap in API functionality for companies using teams for VoIP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d091176-d55a-e9cf-ac12-96e010f60985
* Version Independent ID: 57c00459-3fa7-1610-e327-2374c1613bdf
* Content: [call resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/call.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tpmeredith** [comment]
Sad this still has not gotten any attention. MS Seems to have time to introduce "praise" to teams, but not to support key enterprise VoIP features... :(

**Comment by VinodRavichandran** [comment]
Hi @tpmeredith - Apologies, I didn't receive notifications of this item for some reason. We are actively working on moving a part of the APIs to v1. I don't have exact dates to share but you'll see some of the APIs move over to v1 in CY19Q3.

**Comment by ydfried** [comment]
@VinodRavichandran I'm sorry, but at this point the rate of transfer is unacceptable. We've been using these features with Skype for Business for a while. Microsoft forces an upgrade to Teams when the features aren't entirely compatible?

**Comment by VinodRavichandran** [comment]
No further action on this.

**Comment by tpmeredith** [comment]
@VinodRavichandran - With it now being 2020 with February upon us, it wont be long before this has already been a year. Is this any closer to being out of beta? 

Skype for business is end of life next year and there is still no set in stone guarantee or confirmation about when a functional calling API will be available leaving a major gap in functionality. 

Will companies be forced to use a deprecated/unsupported product because they can't integrate with its replacement?

**Comment by VinodRavichandran** [comment]
@tpmeredith This was released to v1 in December. https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-cloud-communications-apis-are-now-generally-available/

@ananmishr
