### ISSUE TITLE
expirationDateTime field ignored for meetNow

### ISSUE THREAD

**Issue by armanschwarz** [microsoftgraph/microsoft-graph-docs#4329]
Since the "Scheduled" meeting type doesn't appear to be implemented (per #4082) I tried creating a meetNow meeting with a long expiration period, so the meeting could be joined later when the calendar invite is scheduled. However, this field seems to be ignored.

I tried the following request:

```
{
  "expirationDateTime": "2019-04-06T12:00:00.000000Z",
  "meetingType": "meetNow",
  "participants": {
    "organizer": {
      "identity": {
        "user": {
          "id": "3403c469-37bf-43f3-875c-d34baad9b8e0"
        }
      }
    }
  },
  "subject": "Test Meeting"
}
```

This is what I got back:

```
{
  "@odata.context": "https://graph.microsoft.com/beta/$metadata#app/onlineMeetings/$entity",
  "creationDateTime": "2019-04-05T14:27:49.5260536Z",
  "startDateTime": "0001-01-01T00:00:00Z",
  "endDateTime": "0001-01-01T00:00:00Z",
  "canceledDateTime": null,
  "expirationDateTime": "2019-04-05T22:27:50.3072248Z",
  "creationTime": "2019-04-05T14:27:49.5260536Z",
  "startTime": "0001-01-01T00:00:00Z",
  "endTime": "0001-01-01T00:00:00Z",
  "canceledTime": null,
  "expirationTime": "2019-04-05T22:27:50.3072248Z",
  "entryExitAnnouncement": null,
  "joinUrl": XXX,
  "subject": "Test Meeting",
  "isCancelled": false,
  "meetingType": "MeetNow",
  "accessLevel": "SameEnterprise",
  "id": XXX,
  "audioConferencing": null,
  "meetingInfo": null,
  "participants": {
    "organizer": {
      "upn": XXX,
      "sipProxyAddress": XXX,
      "identity": {
        "application": null,
        "device": null,
        "phone": null,
        "user": {
          "id": XXX,
          "displayName": null,
          "tenantId": XXX,
          "identityProvider": "AAD"
        }
      }
    },
    "attendees": []
  },
  "chatInfo": {
    "threadId": XXX,
    "messageId": "0",
    "replyChainMessageId": null
  }
}
```

Note that the expirationDateTime field is 8 hours in the future, instead of the value for expirationDateTime in the request. How can I create a meeting that is either scheduled or has a far dated expiry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create online meeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
We are changing the schema of online meeting due to similar issues of some parameters now working E2E. Closing this now, please try it after the new schema is updated in docs.

**Comment by armanschwarz** [comment]
When is this change happening and where can I find more information about it?

**Comment by armanschwarz** [comment]
Also can you please unclose this. It's obviously not resolved.

**Comment by VinodRavichandran** [comment]
This change will happen in this Q. We will update the Graph docs. I closed the issue because we have identified the problem and is being tracked for change internally. FYI @zhengni-msft

**Comment by armanschwarz** [comment]
@VinodRavichandran you should close the issue when it's resolved, not when you've made a decision to plan to resolve it. Otherwise I have no way of keeping track of it. Please re-open or mark as In Progress.
