### ISSUE TITLE
Authentication_RequestFromNonPremiumTenantOrB2CTenant

### ISSUE THREAD

**Issue by o365developer** [microsoftgraph/microsoft-graph-docs#4336]
I have an Office 365 license. But, can not access the sign in logs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637c0260-f07d-b6d6-29ff-c21153daf742
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/signin-list.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Sign in logs are only available for features that you currently have licensed: https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-beta#what-licenses-do-i-need

**Comment by jjindrich** [comment]
@Jackson-Woods In Azure Portal is blade in Monitoring section Sign-Ins, where are data available for 7 days. Is it possible to access it via API ? If I take token from portal user, I'm able to access API. Why is not possible with managed identity ?
