### ISSUE TITLE
Names a bit long

### ISSUE THREAD

**Issue by brentschmaltz** [microsoftgraph/microsoft-graph-docs#4347]
These names seem a bit long: deviceManagementAbstractComplexSettingDefinition.
How about: deviceManagementDefinition or deviceSettingDefinition 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016a68eb-b5d0-817d-c68b-ca793f685a33
* Version Independent ID: 5fdd3a45-4f42-599f-a158-2902011c71a2
* Content: [deviceManagementAbstractComplexSettingDefinition resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceintent-devicemanagementabstractcomplexsettingdefinition?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/intune-deviceintent-devicemanagementabstractcomplexsettingdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-deviceintent-devicemanagementabstractcomplexsettingdefinition.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
You're right, some of the names do get quite long.  We try to minimize the naming based on the context of the object (e.g. not repeating words as a preface that indicate the context of the object, but we also want to ensure there is enough information to identify the objects' intent.  Sometimes we have conflicts within all of Graph for entity names that we have to avoid too.  But point taken that keeping names short(er) is desirable.
