### ISSUE TITLE
This Article is not present in the API reference

### ISSUE THREAD

**Issue by Enforcer007** [microsoftgraph/microsoft-graph-docs#4352]
It would be great if we can have this article on creating recurring events in the below link

https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cce09996-035a-db45-8c6a-db62ca814ae6
* Version Independent ID: d5869573-4333-0b94-f114-42c24ba3c1da
* Content: [Schedule repeating appointments as recurring events in Outlook - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-schedule-recurring-events?view=graph-rest-1.0)
* Content Source: [concepts/outlook-schedule-recurring-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-schedule-recurring-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
I see a reference to the article in the API reference doc and also an example on how to create a recurring event. Please feel free to reopen if you think this is not fixed yet.
