### ISSUE TITLE
Graph User Schema Extension not available as AAD dynamic group filter

### ISSUE THREAD

**Issue by Modarel** [microsoftgraph/microsoft-graph-docs#4354]
Issue: I have Graph Schema Extensions in place in "User" context. defined and maintained but still on "InDevelopment" State. 
When trying to set Azure AD dynamic group filter to use these attributes they are not available in the listing of membership rules filters.
is it supported this way? or only through what is called ActiveDirectory Extensions Properties?

it is not mentioned explicitly if such scenario is possible or not and would appreciate a help on it.
Article:

**Comment by Jackson-Woods** [comment]
This isn't supported currently, please file a feature request on the Microsoft Graph UserVoice (https://microsoftgraph.uservoice.com/).

**Comment by Modarel** [comment]
Many Thanks @Jackson-Woods  

I did file the feature request. What can you suggest meanwhile as an alternative method to register extension attributes in order to use them as AAD dynamic group filters? (ActiveDirectory Graph Client) looks outdated to me therefore I am looking for a supported way to register those extensions via C#.
Best Regards,
