### ISSUE TITLE
Message Threading

### ISSUE THREAD

**Issue by thejazz15** [microsoftgraph/microsoft-graph-docs#4355]
Messages can be sent using the endpoint:
> POST /v1.0/me/sendMail

On creation of a message, the response returned contains an `id` and `conversationID`.
Messages on the same thread have the same `conversationID` as observed. 

Currently we can reply to a particular message using the endpoint:
 > POST /v1.0/me/messages/{id}/reply

However there is no way to add a message to the same thread with the same `from` and `to` headers.

**Comment by jaebradley** [comment]
I could also be missing something, but it seems like in Outlook, one is able to create a message in a thread, but there does not seem to exist an API via creating a message, or a reply all, or updating a message after the fact, that makes it able to replicate this behavior.

**Comment by jaebradley** [comment]
I was definitely missing something.

The errors I was seeing was due to the fact that I was creating reply drafts referencing message ids that were _drafts_ 😞.

Sorry for the additional noise on this issue.
