### ISSUE TITLE
Chats returned from /messages endpoint do not have 'IM' as their subject

### ISSUE THREAD

**Issue by aakarshit** [microsoftgraph/microsoft-graph-docs#4357]
Issue: In the list of Known Issues, the document says that the /messages endpoint returns teams chat and these have 'IM' as their subject. This is no longer true. Since end of March 2019, the subject appears as an empty string.

Article: https://docs.microsoft.com/en-us/graph/known-issues#get-messages-returns-chats-in-microsoft-teams

**Comment by imihalcea** [comment]
I'm affected by this issue to. Today I don't see any efficient way to distinguish between mail messages and chat messages. Big problem for us.

**Comment by svpsiva** [comment]
Reading teams chats via /messages endpoint is not a supported scenario. We would suggest that you make use of Teams APIs in Microsoft Graph to fetch chat messages.
