### ISSUE TITLE
Retrieve Team id and channel id

### ISSUE THREAD

**Issue by Karishma-Tiwari-MSFT** [microsoftgraph/microsoft-graph-docs#4363]
Please share how can I retrieve the Teams id and channel id to be used in api request: GET https://graph.microsoft.com/beta/teams/{id}/channels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1235c480-f924-457c-93ca-29221ba62c9d
* Version Independent ID: e667c977-60ef-a81d-e94b-7eed5061b2c7
* Content: [List channels - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aakarshit** [comment]
Use the /groups endpoint to get a list of all groups. Then use the group-id from there as the team-id to use with the /teams/{group-id}/channels endpoint to get a list of channels along with their ids.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks @aakarshit . I will close this now.
