### ISSUE TITLE
Microsoft Teams Chats

### ISSUE THREAD

**Issue by jerem99** [microsoftgraph/microsoft-graph-docs#4367]
It's been a few days that "IM" is no longer in the subject of the message, so now we have no information to determine if it's a Teams chat.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7ca25a-037d-5202-debc-92c06a2c8480
* Version Independent ID: 8ebb4dbc-76a1-00fd-e740-87eda29a40f0
* Content: [Known issues with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/known-issues#messages)
* Content Source: [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/known-issues.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by imihalcea** [comment]
I'm affected by this issue to. Today I don't see any efficient way to distinguish between mail messages and chat messages.

**Comment by erickbp** [comment]
@jerem99 @imihalcea have you been able to efficiently distinguish between mail messages and chat messages?
Thanks

**Comment by TIvanyo** [comment]
@jerem99 @imihalcea @erickbp 

If this helps, setting the mailFolder to "TeamChat" will only return chat messages. Having the mailFolder set to "ConversationHistory" will return Skype messages

https://graph.microsoft.com/beta/users/{user.Id}/mailFolders/**TeamChat**/messages

**Comment by aakarshit** [comment]
@TIvanyo how did you figure this out? Is this documented somewhere?

Thank you for sharing this.

**Comment by TIvanyo** [comment]
@aakarshit I found that out after reading an article talking about the compliance functionality for Teams. I haven't found those particular folders in the official documentation however but I've been using this method for a while and haven't had any issues with it.

https://www.petri.com/teams-compliance-story

**Comment by nkramer** [comment]
Using exchange/mailbox APIs to get teams messages is not a supported scenario. In some cases, you can use the Teams chat APIs, it in other cases (e.g. application permissions) there may not be a viable workaround today.
