### ISSUE TITLE
Attachments > 4 MB?

### ISSUE THREAD

**Issue by omascia** [microsoftgraph/microsoft-graph-docs#4370]
"Since there is currently a limit of 4MB on the total size of each REST request, this limits the size of the attachment you can add to under 4MB."
Could the doc give pointers on what to do best if some email must have an attachment file of, let's say, 5 MB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd65821-a482-8b49-7da5-4afdcbe6d9f0
* Version Independent ID: d964d80e-c019-aed5-a26e-489a57f0653b
* Content: [Add attachment - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/message-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-post-attachments.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MolendijkK** [comment]
In my project (for a large home care provider) I need the same, because 4 MB really isn't enough and leads to quite a lot of operational issues. So I hope this will be fixed soon (let's say to 8 or 10 MB)!

**Comment by celloist** [comment]
I use outlook api if it is bigger then 4 mb here is my testcode:
(permission scope for the access token is  "scope", "https://outlook.office.com/mail.readwrite"  )
        private async Task<HttpResponseMessage> UploadUsingOutlookApi(string accessToken, string payload)
        {
            var request = new HttpRequestMessage(HttpMethod.Post, "https://outlook.office.com/api/v2.0/me/MailFolders/drafts/messages");
            request.Headers.Add("Authorization", $"bearer {accessToken}");
            var requestContent = new StringContent(payload);
            requestContent.Headers.Remove("Content-Type");
            requestContent.Headers.Add("Content-Type", "application/json");
            request.Content = requestContent;
            var client = new HttpClient();
            return await client.SendAsync(request);
        }

        private string GeneratePayload(string fileName, string fileEncoded)
        {
            var jMessage = new JObject();
            var jAttachments = new JArray();
            var jAttachment = new JObject
            {
                {"@odata.type", "#Microsoft.OutlookServices.FileAttachment"},
                {"Name", fileName},
                {"ContentBytes", fileEncoded}
            };
            jAttachments.Add(jAttachment);
            jMessage.Add("Attachments", jAttachments);
            return jMessage.ToString();
        }

**Comment by Zombaya** [comment]
This is related to #3593, which was closed since this is supposedly a feature request and you should vote for this on [uservoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/37353598-send-message-with-a-larger-than-3-mb-file-attachm).

Also related to #85, but that one was closed as well since we needed to follow-up in issue #3593...

**Comment by maitra** [comment]
This appears to be that way of MS (or, at least, of @svpsiva and his group) of making it appear that they are working hard. Start a new thread every once in a while and pretend that work has just started. The reality is that this so-called work and really minor enhancement has been pretending to be going on for years. Any other organization would fire @svpsiva but I guess he is some "Senior Program Manager" of incompetence.

**Comment by jthake-msft** [comment]
@maitra I appreciate your passion and desire for this to be shipped. 

But you have no right making personal attacks on any of the team on Microsoft Graph. You have no idea what our priorities look like at Microsoft or the complexities of our platform and design choices.

In future I would encourage you to stay positive and provide feedback that will help us to prioritize our backlog.

**Comment by maitra** [comment]
I fail to understand what aspect of my comments constituted a "personal attack" but I do understand why it is easy to shift attention than actually solve the issue that users have paid for. 

And you may well be right that we have no idea of the complexities of your platform or design choices. Many of it is needless, and perhaps poorly programmed (the massive changes presumed to be required and being worked on for years to increase the 4MB limit seems to indicate arbitrary coding). In any case most of it is tried on consumers as test beds without caring for them: why else would you recommend the use of MS Graph when it is clearly not ready with such an arbitrarily low limit? 

But I am glad to report that we are moving away from MS Crap and to a different provider who we hope will be more responsive and do less harm.

**Comment by jdew73** [comment]
On behalf of our clients who have been asking, are there any updates on this issue?

**Comment by svpsiva** [comment]
We are almost ready for you. We are weeks away from a beta release.

**Comment by NeilGo** [comment]
This is becoming critical as Microsoft PowerPlatform  (Flow/PowerApps) is deprecating the Outlook REST API (It appears to be happening this month) in favor for the Graph API when connecting to Outlook 365.
https://flow.microsoft.com/en-us/blog/office-365-outlook-connector-important-upcoming-changes/

Now user and business flows and PowerApps that deal file attachments are breaking in odd and unexpected ways.

The Graph API should at least be able to handle messages that conform the smallest limits per:
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#message-limits-across-office-365-options
which would be 25MB total message size for legacy encryption system "Size limit for encrypted messages (for subscribers using Office 365 Message Encryption legacy version)5"


Please vote for https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/37353598-send-message-with-a-larger-than-3-mb-file-attachm

Thanks!

**Comment by svpsiva** [comment]
This feature is now available via Beta. https://developer.microsoft.com/en-us/office/blogs/attaching-large-files-to-outlook-messages-in-microsoft-graph-preview/

**Comment by kishor1910** [comment]
This is still in beta?...https://developer.microsoft.com/en-us/office/blogs/attaching-large-files-to-outlook-messages-in-microsoft-graph-preview/
any plans to move to use for production?

**Comment by angelgolfer-ms** [comment]
@kishor1910 , you can now attach files up to 150MB in size to message and event resources on the v1 endpoint, good for production apps.
If you're interested - there's a weekly roll up of [what's new](https://docs.microsoft.com/en-us/graph/whats-new-overview) in the docs. The large file attachment update came in [April](https://docs.microsoft.com/en-us/graph/whats-new-overview#april-2020-new-and-generally-available).
Heads-up - that [what's new](https://docs.microsoft.com/en-us/graph/whats-new-overview) topic features the two most recent months at a time. As we get into June, April updates will go to [highlights of earlier releases](https://docs.microsoft.com/en-us/graph/whats-new-earlier) any time now.
