### ISSUE TITLE
What is the limit for $top for this specific API call?

### ISSUE THREAD

**Issue by jamatz** [microsoftgraph/microsoft-graph-docs#4372]
From https://docs.microsoft.com/en-us/graph/query-parameters, we know that "Different APIs might have different default and maximum page sizes.", but I don't see where on the individual pages we can actually learn what these maximums are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
For most directory APIs, the limit is 999 and the default is 100.

**Comment by JBines** [comment]
I was thinking about converting over a couple of my PS scripts to graph API to limit the global admin useage but I guess I can put that on hold :(

**Comment by yyuank** [comment]
I saw the limit is updated on the query parameter page, so closing this issue.
