### ISSUE TITLE
Here String Header Error

### ISSUE THREAD

**Issue by rpcbrowe** [microsoftgraph/microsoft-graph-docs#4376]
These instructions cannot be executed as written. PS continues to throw an error when executing Step 2.7 to execute the ARMClient.exe put command.  Copying/pasting the exact entry on this page results in "No characters are allowed after a here-string header but before the end of the line".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35407771-ba0c-a92f-fb04-e6ecb3b935bd
* Version Independent ID: d85334a6-8037-5026-6e49-5325a20c8bb1
* Content: [Integrate Microsoft Graph Security API alerts with your SIEM using Azure Monitor - Microsoft Graph](https://docs.microsoft.com/en-us/graph/security-splunk-siemintegration#feedback)
* Content Source: [concepts/security-splunk-siemintegration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/security-splunk-siemintegration.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
Hi @rpcbrowe, to help us better investigate the issue, can you please provide some screenshots and a detailed description of the issue? And what sample and documentation did you use for reference in this case?

**Comment by preetikr** [comment]
The Azure Monitor - EventHub SIEM cone connectivity option for Microsoft Graph Security API is not supported since we have relevant direct integrations with SIEMs like Splunk and QRadar. Please switch to the respective integration for this scenario. https://docs.microsoft.com/en-us/graph/security-splunk-siemintegration
