### ISSUE TITLE
@odata.nextLink presence

### ISSUE THREAD

**Issue by damienestewart** [microsoftgraph/microsoft-graph-docs#4380]
Hi! Quick question, should we ever expect this result to be paginated? Should we be checking for the existence of "@odata.nextLink" or will this always return the full list of a user's joined teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4878b58-31d9-f8e1-ed30-2316c5f9ca15
* Version Independent ID: 1dcb5dda-2a45-77e1-bbe1-46ec24b33eec
* Content: [List joinedTeams - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list-joinedteams.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jjtbsomhorst** [comment]
expect all list requests to be paginated. Always. Simple ignore if the nextlink property can't be found.

**Comment by damienestewart** [comment]
Sounds good, thanks! Closing.

**Comment by yogi466** [comment]
if teams are more than 1000 then not pulling all the teams nor having @odata.nextLink , what to do ?
