### ISSUE TITLE
Insight needed

### ISSUE THREAD

**Issue by 2toLeadMike** [microsoftgraph/microsoft-graph-docs#4406]
Can some insight be shared on the algorithm behind this? What is used and weighted? Currently it is hard to take advantage of this functionality when its unclear on how the underlying mechanisms work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0275d59-a7c7-374a-3445-d39d1085cf39
* Version Independent ID: 92f5224d-ac9d-99a9-0b82-9fdc117fcfe9
* Content: [List trending - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/insights-list-trending?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/insights-list-trending.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/insights-list-trending.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by simonhult** [comment]
The weight field is an indication of relevance. This number is not normalized in any way, but computed using a time-decay function and a per-person baseline that is useless in any other circumstance than to compare items that are returned in the same call.

We define "trending" to be content that is frequently used (accessed and edited) by the people that you work the most with, where the "people you work with" is the list of people you get back from https://docs.microsoft.com/en-us/graph/api/user-list-people?view=graph-rest-beta.

**Comment by 2toLeadMike** [comment]
@simonhult thanks! I was curious mostly about the weighting of the inputs of the underlying logic. You mention accessed and edited, is this using some existing metadata (i.e. SharePoint's ViewsRecent or Modified field?). As far as I am aware there is no count for editing but only views so I'm curious to know more how this works on Graphs side.

The 'people that I work with' from _list people_ can returns tens to hundreds of people, would this function only look at the top X number of people? I.e. is there a point where (say after the top 10) users would no longer impact the trending results I get back, or does the entire organization I am in have some level of impact? Hopefully this sheds light on why I am cautious to use this functionality as it is still very unclear on what trending really is.
