### ISSUE TITLE
"Track changes for a Drive" link broken

### ISSUE THREAD

**Issue by danielgwilson** [microsoftgraph/microsoft-graph-docs#4408]
Link leads to 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview?toc=./ref/toc.json&view=graph-rest-beta)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
Thanks; I just opened PR #4409 to fix this issue.
