### ISSUE TITLE
User_List_Approleassignments missing from Github and functioning incorrectly

### ISSUE THREAD

**Issue by cbales** [microsoftgraph/microsoft-graph-docs#441]
I am looking at documentation for the following beta endpoint:

https://graph.microsoft.io/en-us/docs/api-reference/beta/api/user_list_approleassignments

Running the given command through the Graph Explorer:

`GET https://graph.microsoft.com/beta/me/appRoleAssignments`

throws the following error:

`{
    "error": {
        "code": "BadRequest",
        "message": "Unsupported segment type. ODataQuery: users/01d8c44a-98ff-465c-b331-6bec0d6354d1/appRoleAssignments",
        "innerError": {
            "request-id": "7ffcdc8a-e47a-43c9-aa6f-10904d8f6f55",
            "date": "2016-08-26T15:55:41"
        }
    }
}`

I'm wondering if there is a certain level of permission required to make this request. Could you provide some clarification on how to make this call? If this is a functionality bug and not a documentation bug, could you forward me to the correct party? Thanks!

I also was unable to find this page on GitHub; I'm not sure if this feature is being deprecated or is simply missing from the repo.

**Comment by marych** [comment]
User entity type doesn't currently have appRoleAssignments property. I suspect that documentation page was removed on purpose from GitHub. It looks like it's still linked in the menu though (beta ->users -> directoryObjects -> List appRoleAssignments). It should be removed from the menu until such property is added.

**Comment by thargy** [comment]
More importantly, how on earth do you administer these roles programmatically in the meantime as all the docs point to the appRolesAssignments message???

**Comment by honb** [comment]
I'm facing the same issue. Did you find a solution for this?

Got bad request:
https://graph.microsoft.com/beta/users/me/appRoleAssignments/
https://graph.microsoft.com/beta/users/me/appRoleAssignments/{AadAppID}

 (beta ->users -> directoryObjects -> List appRoleAssignments). ==> Is this no longer available?

**Comment by jthake-msft** [comment]
@lleonard-msft could someone comment on the changese to the docs here? has it been moved?

I see this https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/resources/approleassignment

**Comment by lleonard-msft** [comment]
Hi everyone,

Sorry for the delay in responding.  It looks like @jthake-msft has the right idea.

@cbales - The page you're looking for can be [found here](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/approleassignment_get).  (The developer site has the full documentation experience and may be more functional than previewing individual pages on GitHub.)

Note that the page includes a list of the required permissions and also has an example showing a call to user.

Also, note that the call is GET appRoleAssignments, not LIST. 

I was able to use Graph Explorer to successfully call `GET https://graph.microsoft.com/beta/me/appRoleAssignments` when logged in using a work account and when not logged in.  

As noted in the Permissions block, the call isn't supported for personal MSA accounts and Graph Explorer correctly showed a BadRequest (Unsupported segment type) when I tried calling the method when logged in with a personal MSA account.

@marych - The page can now be found in the table of contents; see Develop > beta > Identity and Access > Get appRoleAssignment. 

@thargy - This is the correct call, though you may need to verify your permissions and [app set-up](https://developer.microsoft.com/en-us/graph/docs/concepts/auth_overview#how-do-i-get-my-app-talking-to-azure-ad-and-microsoft-graph).

@honb - Verify that you're using a work or school account to call the endpoint.  Using a personal MSA account leads one instance of the error you mention; there may be other causes as well (e.g. permissions).  To get a sense of the underlying problem, check the value of _error.message_.

**Comment by lleonard-msft** [comment]
Since there hasn't been any recent responses, I'm closing this.  

If there are outstanding issues, please file new ones so that we can track them separately.

**Comment by avpdm** [comment]
I am trying to get user installed Apps using Admin account for which Global Admin permissions enabled. But I am getting only appRoleAssignments and assignedPlans of a specific user. Can you please suggest how to get apps(add-inds) installed by the user(s).
I tried below 2 APIs and getting only Admin enabled/installed apps.
https://graph.microsoft.com/v1.0/users/<userId>?$select=assignedPlans,id,mail,displayName,userPrincipalName,proxyAddresses,addIns,assignedLicenses,userType
https://graph.microsoft.com/beta/users/<userId>/appRoleAssignments
