### ISSUE TITLE
managedDevices roleScopeTagIds always empty

### ISSUE THREAD

**Issue by cblomart** [microsoftgraph/microsoft-graph-docs#4414]
Issue: 

Queriying managedDevices returns an empty array for roleScopeTagIds for all devices.
The documentation should state that.

@dhelia mentioned on [stackoverflow](https://stackoverflow.com/questions/54357450/how-to-get-all-managed-devices-rolescopetagids-using-intune-graph-ap) that this was intented to limit the size of retruned data (scope tags not capped).

As advised in the issue template, i also created a [uservoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/37398955-imporve-searching-manageddevice-by-rolescopetagids) to request more possibilities on the link between managedDevices and scope tags.

Article:

https://docs.microsoft.com/fr-fr/graph/api/resources/intune-devices-manageddevice?view=graph-rest-beta should mentioned that roleScopeTagIds is not allways filled in.

**Comment by triplanedave** [comment]
Thanks for the feedback.  I've filed a work item for our developers to update the description text to indicate the roleScopeTagIds can be empty.
