### ISSUE TITLE
IdentityRiskEvent filtering

### ISSUE THREAD

**Issue by sivabalaguru** [microsoftgraph/microsoft-graph-docs#4415]
Issue: I was able to filter IdentityRiskEvents till yesterday 4/16/2019 based on the riskEventDateTime. Seems like it is broken now. Though the filter is specified identityRiskEvents pulls all the risk events.

Article:

**Comment by cloudhandler** [comment]
I do not own this API, reassigning. (FYI @dkershaw10)

**Comment by cloudhandler** [comment]
This API has been deprecated
