### ISSUE TITLE
PUT /users/:id/photo/$value fails even with Users.ReadWrite.All (beta)

### ISSUE THREAD

**Issue by Sammons** [microsoftgraph/microsoft-graph-docs#442]
SCP value is : Directory.AccessAsUser.All Directory.ReadWrite.All Group.ReadWrite.All offline_access User.Read User.ReadBasic.All User.ReadWrite.All

```
PUT /beta/users/2a404193-12b9-41e7-85e9-ba5c0ec2e0a3/photo/$value HTTP/1.1
Content-Type: application/octet-stream
```

```
{
  "error": {
    "code": "ErrorAccessDenied",
    "message": "AccessDeniedException",
    "innerError": {
      "request-id": "b23fa5d6-9141-4393-aba2-99d0b40cbe2d",
      "date": "2016-08-26T20:48:03"
    }
  }
}
```

but the docs say here https://graph.microsoft.io/en-us/docs/api-reference/beta/api/profilephoto_update that this should work.

**Comment by marych** [comment]
@sumurthy - user photo can only be updated with User.ReadWrite scope as far as I know. Your https://github.com/OfficeDev/microsoft-graph-docs/commit/38e45cb9b67b75c6773111523b630c667c666c71 changed profilephoto_update.md to indicate that User.ReadWrite.All should allow updating any user photo, but I don't think that is supported. Is it a new feature or should that documentation change be reverted?

**Comment by Sammons** [comment]
I've noticed this isn't true with all orgs, it works with a different test org on users without exchange accounts.

**Comment by marych** [comment]
@Sammons - do you have a request-id & timestamp of a working request with no User.ReadWrite scope in the token?

**Comment by Sammons** [comment]
@marych sure, here is an example of an admin user modifying a different user:

request

```
PUT /beta/users/2fcc15a7-753c-4284-879a-882f815e69d4/photo/$value HTTP/1.1
Content-Type: application/octet-stream
Host: graph.microsoft.com
Connection: close
User-Agent: Paw/3.0.6 (Macintosh; OS X/10.11.6) GCDHTTPRequest
Content-Length: 18513
```

the body is binary, the scp of the jwt is:
```
Directory.AccessAsUser.All Directory.ReadWrite.All offline_access User.Read User.ReadBasic.All User.ReadWrite.All
```

result

```
HTTP/1.1 204 No Content
Cache-Control: private
Content-Length: 0
Content-Type: text/plain
Server: Microsoft-IIS/8.5
request-id: 98e30ac0-51f2-4910-9742-1737a230bb54
client-request-id: 98e30ac0-51f2-4910-9742-1737a230bb54
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US","Slice":"SliceA","ScaleUnit":"001","Host":"AGSFE_IN_4","ADSiteName":"WST"}}
Duration: 4464.2378
X-Powered-By: ASP.NET
Date: Thu, 01 Sep 2016 00:01:00 GMT
Connection: close
```

**Comment by marych** [comment]
This is a side effect of the Azure Active Directory fallback that we enabled for /**beta**/users/id/photo requests in April (see https://graph.microsoft.io/en-us/changelog#). /**v1.0**/users/id/photo is only available to users with Exchange license, so the plan is to enable access to user photo also for users without Exchange license. There are currently a few known differences in how the API works depending on whether the photo is stored in Exchange or AAD.  In particular AAD does allow User.ReadWrite.All, but that will only be attempted for users that don't have Exchange mailbox as for them MS Graph will attempt to store the photo in Exchange and that requires User.ReadWrite scope.

**Comment by Sammons** [comment]
In the future will User.ReadWrite.All let us write to photo for users with an Exchange license? Or some other scope? It is severely limiting to our application to require every user to individually log into our application in order to set their photo - since we'd like to modify users using admin credentials.

**Comment by marych** [comment]
Unfortunately the is no plan currently to allow admins to store other user photos in Exchange. Could you raise it at https://officespdev.uservoice.com/forums/224641-general/category/101632-microsoft-graph-o365-rest-apis ?

**Comment by mattgeim** [comment]
Please feel free to reopen this issue if needed. Thanks!
