### ISSUE TITLE
missing implementation in graph.dll

### ISSUE THREAD

**Issue by akukolj** [microsoftgraph/microsoft-graph-docs#4422]
This method cannot be found in Microsoft.graph.dll, I tried to access it as graphClient.Me.Calendar.Getschedule , but there is no such method. Can you explain how to access this service method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72df543-3deb-151b-f634-608a04881289
* Version Independent ID: 3db73371-c6ee-2add-9d51-223e3f1f82e4
* Content: [calendar: getSchedule - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/calendar-getschedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-getschedule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by pawlowski** [comment]
I'm also looking for this method. Will it be implemented in the C# SDK?

**Comment by jasonjoh** [comment]
It is in 1.15, which version are you using? (Reference: https://github.com/microsoftgraph/msgraph-sdk-dotnet/releases/tag/1.15.0)

**Comment by pawlowski** [comment]
I was using 1.14, thanks for the heads up! Sure enough, it appears to be implemented now.

@jasonjoh I appreciate your help!

**Comment by jasonjoh** [comment]
No problem!

**Comment by akukolj** [comment]
@jasonjoh Thanks  for the informations
