### ISSUE TITLE
"Privileged role assignment request" does not have proper sub-headings

### ISSUE THREAD

**Issue by ryanspletzer** [microsoftgraph/microsoft-graph-docs#4428]
They are currently "List role assignments", "Create role assignments", "Cancel role assignments" and "Get my role assignments".

But they should be "List role assignment requests", "Create role assignment request", "Cancel role assignment request", "Get my role assignment requests".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1a4042c-9e7f-7eb6-92b7-cb3b838913c1
* Version Independent ID: cd1273c5-a1f4-d333-63a7-d207dabc81f0
* Content: [List privilegedRoleAssignmentRequests - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/privilegedroleassignmentrequest-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/privilegedroleassignmentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/privilegedroleassignmentrequest-list.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
