### ISSUE TITLE
Request Format

### ISSUE THREAD

**Issue by ddallen-oosha** [microsoftgraph/microsoft-graph-docs#4434]
After a bit of trial and error it looks like the correct request format should be "/deviceManagement/windowsAutopilotDeploymentProfiles/{windowsAutopilotDeploymentProfileId}/assignments"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f218b31-c5ac-70c9-1f06-9e86c1b11d0e
* Version Independent ID: 5bc9f34a-5580-90f9-dee2-fc8e002377db
* Content: [List windowsAutopilotDeploymentProfileAssignments - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-windowsautopilotdeploymentprofileassignment-list?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-enrollment-windowsautopilotdeploymentprofileassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-windowsautopilotdeploymentprofileassignment-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've filed a work item to have our engineers update the docs.
