### ISSUE TITLE
internetMessageHeaders missing on emails sent from outlook.offic365.com

### ISSUE THREAD

**Issue by samirmeghani** [microsoftgraph/microsoft-graph-docs#4436]
[Enter feedback here]

I receive a message from another user in my company using outlook.office365.com. I then reply to him. When I query that message in the API, it has no value for the internetMessageHeaders property. The incoming message however does have internetMessageHeaders. If I respond to the message again using Outlook Desktop client, internetMessageHeaders is set. This seems to be a bug in how outlook.office365.com sent mail is handled.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bf275f-7a02-7e90-120f-2e1d055dac95
* Version Independent ID: b1556931-c2fd-7400-4e45-d666a8a53540
* Content: [Get message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/message-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by garrettm** [comment]
I am also seeing this problem

**Comment by gopinath-manyam** [comment]
This is blocking

**Comment by xkobal** [comment]
Same problem for. I can see headers into outlook.office365.com but it's impossible to get them with the API and the flag `?$select= internetMessageHeaders `
