### ISSUE TITLE
Id is case insensitive

### ISSUE THREAD

**Issue by meum** [microsoftgraph/microsoft-graph-docs#4449]
If it is intentional that the id property is case insensitive this should be mentioned.

E.g. sending a batch with one id "a" and another one "A" gives the error "Request Id A has to be unique in a batch".

I discovered this because I came across two events with nearly identical ids, only the casing on one letter was different, and I was reusing these ids as ids in a batch request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26695cc3-710f-0579-7d0a-d770988a0e97
* Version Independent ID: 5bcdfc0f-d9d8-066f-60aa-17ecb174b346
* Content: [Combine multiple requests in one HTTP call using JSON batching - Microsoft Graph](https://docs.microsoft.com/en-us/graph/json-batching)
* Content Source: [concepts/json-batching.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/json-batching.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@meum , thank you for bringing this up. In general, we should assume Microsoft Graph entity id values are case sensitive. This information has been documented in this [topic ](https://docs.microsoft.com/en-us/graph/traverse-the-graph#view-a-collection-of-resources), and it wasn't not very discoverable.
FYI PR #5208 clarifies this and makes the information more discoverable. The content update should be live in the next day.
Thank you for your patience and continued support.
