### ISSUE TITLE
Not possible to filter results of /members

### ISSUE THREAD

**Issue by Sheikz** [microsoftgraph/microsoft-graph-docs#4450]
Not possible to filter when listing members of a team.
I would like to be able to filter members based on a email address.

When I try: https://graph.microsoft.com/beta/groups/:teamId/members?$filter=mail eq 'mail@example.com'

I get the error that the filter is not supported
{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "The specified filter to the reference property query is currently not supported.",
        "innerError": {
            "request-id": "f62d7300-12a4-431b-bb4a-733044ef5852",
            "date": "2019-04-23T14:52:43"
        }
    }
}

**Comment by dkershaw10** [comment]
Correct - this is not currently supported, but it is something we are working on supporting in the future.  No ETA yet.  Please make sure to make feature request on UserVoice - https://microsoftgraph.uservoice.com
