### ISSUE TITLE
Is there a way to get to SubscriptionId using any graph API? This is the ID that represents the product subscription that user is using

### ISSUE THREAD

**Issue by jigarme9** [microsoftgraph/microsoft-graph-docs#4451]
Is there a way to get to SubscriptionId using any graph API? This is the ID that represents the product subscription that user is using

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52263bf3-6bd2-2219-e2f0-dda921ea7e10
* Version Independent ID: b625c2db-d6a2-8a18-88dc-fad7e76f9251
* Content: [List subscribedSkus - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/subscribedsku-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscribedsku-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Can you provide more info? In the response, an id and skuId are already provided for each item in the subscription collection. If you need the subscriptions that a user is using, then check users/{id}/licenseDetails: https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http
