### ISSUE TITLE
Is there a event callback or webhook when a group member ship changes

### ISSUE THREAD

**Issue by karanth77** [microsoftgraph/microsoft-graph-docs#4460]
Issue: 

Article:

**Comment by karanth77** [comment]
Can i get web hook notification when a member gets added /removed or the properties of a group change

**Comment by Jackson-Woods** [comment]
This is already supported, see our webhooks documentation here: https://docs.microsoft.com/en-us/graph/webhooks?context=graph%2Fapi%2F1.0&view=graph-rest-1.0
