### ISSUE TITLE
The Create OnlineMeeting doesnt work on microsoft graph explorer

### ISSUE THREAD

**Issue by tktakaishi** [microsoftgraph/microsoft-graph-docs#4461]
Issue: 

Hello. Im trying to implement the microsoft graph example to make an online meeting in php, and first im trying to do the request, but that doesnt work in the graph explorer. I already gave all delegates permission in the explorer.
 
Article:

https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta#feedback

![image](https://user-images.githubusercontent.com/42976461/56699052-9bc6f100-66b9-11e9-906f-e7209fd1b577.png)

**Comment by ai-works** [comment]
Hey, I got the same problem, did you find a solution?

**Comment by tktakaishi** [comment]
Yes, i did.

The trouble all time was access token. 

Since microsoft documentation uses 1 way to login, that endpoint was wrong; that access token doesnt work for applications. PHP documentation is poor and they never say the difference between application roles and scopes.

In this case the key is to give role access "OnlineMeetings" for token, and to do that we need to use another oauth endpoint.

Im not on home but when i come back ill upload the correct code.

I hope this asnwer helps you since on internet there is nothing.

**Comment by ai-works** [comment]
Wow, thank you very much. If you could upload the code would be really awesome!

BR
