### ISSUE TITLE
How to add multiple scopes in a request url.

### ISSUE THREAD

**Issue by azzurolilc** [microsoftgraph/microsoft-graph-docs#4462]
Add a small section to help user understand that 
adding multiple scopes to a request url should be comma separated(?).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @azzurolilc for raising your issue. You can add multiple scopes to your URI by separating them with using a space. This clarification is available in this guidance for [getting authorization on behalf of a user](https://docs.microsoft.com/en-us/graph/auth-v2-user#authorization-request).  I hope this helps.

No further updates identified for the page. Closing the issue.
