### ISSUE TITLE
incorrect work 'top' OData system query options for get a list messages of a channel via Api request

### ISSUE THREAD

**Issue by aakifiev** [microsoftgraph/microsoft-graph-docs#4471]
Issue: not corrected response

Article: If we have message about added tab, it's not appear in response of request like this https://graph.microsoft.com/beta/teams/3fb8b60a-062a-4c3c-b393-f13d8c53cf91/channels/19:193ffa2f85bc44208c9c4afb87195a64@thread.skype/messages?$top=5

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this, I will get back to you soon.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
I tried this and I am getting the Tab added message in the response. Could you please confirm once?

**Comment by HunaidHanfee-MSFT** [comment]
We are closing this issue, feel free to open it if you have any query.
