### ISSUE TITLE
'visibility' value not cloned when not specified in the payload

### ISSUE THREAD

**Issue by VelinGeorgiev** [microsoftgraph/microsoft-graph-docs#4476]
'visibility' description says `If visibility is not specified, the visibility will be copied from the original team/group.` However, when I clone team with visibility of `Public` then the clone has visibility of `Private` after the clone is being created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c78c38c-b49d-96d7-ff93-37b4f6bb8e6a
* Version Independent ID: 93752ea2-470d-0226-2928-439d71fe711b
* Content: [Clone a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/team-clone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-clone.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by williamsunnnnnn** [comment]
Still not working right now
