### ISSUE TITLE
Calls to /calendarView/ endpoint are no longer returning "emailAddress" field as part of attendee resource type

### ISSUE THREAD

**Issue by ryandamico** [microsoftgraph/microsoft-graph-docs#4477]
As of an hour ago, calls to the /calendarView/ endpoint are returning "attendee" resource types that only include a "status" field. They're missing both the "type" and the "emailAddress" fields documented here: https://docs.microsoft.com/en-us/graph/api/resources/attendee?view=graph-rest-1.0

We're currently experiencing downtime in a production application as a result. Is this a known issue?

**Comment by iechevarria** [comment]
I'm also seeing this issue, and it looks like it also affects `/calendar/events`. It's reproducible in the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) for both `/calendarView/` and `/calendar/`.
