### ISSUE TITLE
Fail to filter user for personal account (MSA).

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoftgraph/microsoft-graph-docs#4480]
Fail to filter user for personal account (MSA).

URL : https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,%20'test')%20or%20startswith(givenName,'test')%20or%20startswith(surname,'test')%20or%20startswith(mail,'test')%20or%20startswith(userPrincipalName,'test')

Message: The query specified in the URI is not valid. Could not find a property named 'displayName' on type 'Microsoft.Fast.Profile.Web.Models._1._0.Profile'.

Things work well for work account.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3808467e-580d-f890-faf5-ae2cd473a7bf
* Version Independent ID: ab6994b8-039c-3dd7-467d-6b764bee1b6f
* Content: [Use the People API in Microsoft Graph to get information about the people most relevant to you - Microsoft Graph](https://docs.microsoft.com/en-us/graph/people-example)
* Content Source: [concepts/people-example.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/people-example.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kevinbellinger** [comment]
Filter is not supported for MSA users.
