### ISSUE TITLE
Conflicting requirements?

### ISSUE THREAD

**Issue by jasonshave** [microsoftgraph/microsoft-graph-docs#4487]
The following page has the same reference to the checkMemberGroups Graph call however the other page seems to indicate there is a bug with permissions and only Directory.* calls will work. Also, this page's example is much more clear as to what you get back. Do we need two pages for the same referenced query?? Seems like this could be confusing...

https://docs.microsoft.com/en-us/graph/api/user-checkmembergroups?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66b82e22-7a27-2e9a-1e5e-4d8a53d20c30
* Version Independent ID: eb96410f-f978-a127-4c28-b70146b14d22
* Content: [Check member groups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryobject-checkmembergroups?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/directoryobject-checkmembergroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryobject-checkmembergroups.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
I do believe there is a need for both articles. One refers to the specifics of checking membership of a user, the other gives specifics about checking membership of user, group, service principal or directory object. The only difference in the response examples I see is that one provides a placeholder for the value and the other a fictitious identifier. Going to close this for now. If you feel changes should be made, please provide specific information about the change to the referenced article.
