### ISSUE TITLE
The $ prefix for filter seems to be required for v1.0. please double check.

### ISSUE THREAD

**Issue by TheodoreShi** [microsoftgraph/microsoft-graph-docs#4488]
In article, I saw 'Note: On the v1.0 and beta endpoints, the $ prefix is optional. For example, instead of $filter, you can use filter.' ,  but in fact, the $ prefix is not optional for v1.0, please double check.
I got the below error when removed $ prefix on v1.0 version.

[HTTP_GET] https://graph.microsoft.com/v1.0/users?filter=displayName eq 'Demo user name'
error message: 
{
    "error": {
        "code": "Request_BadRequest",
        "message": "Unrecognized query argument specified: 'filter'.",
        "innerError": {
            "request-id": "6e1ef2a5-fb94-4bde-9183-f1a24c2272a7",
            "date": "2019-04-29T09:00:37"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#feedback)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@TheodoreShi , thanks for your patience. PR #4757 should make that clear now. The content update to the [query parameters](https://docs.microsoft.com/en-us/graph/query-parameters) topic should be deployed in the next day.
