### ISSUE TITLE
"assignedTo" not working

### ISSUE THREAD

**Issue by TonyTong502** [microsoftgraph/microsoft-graph-docs#4496]
Team, "assignedTo": "Dana Swope" seems not working, I tried following scenarios and all response return assignedTo as empty, please kindly advise how to make it work?

1, "assignedTo": "{firstName} {lastName}"
2, "assignedTo": "{lastName} {firstName}"
3, "assignedTo": "{userEmail}"

Thanks
Tony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312c9fd8-9544-f242-c394-35d353406648
* Version Independent ID: 53114d87-dcf5-a47f-e5c2-7a2043f7c67e
* Content: [Create outlookTask - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlookuser-post-tasks?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/outlookuser-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlookuser-post-tasks.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by figgsoftware** [comment]
Trying to share a task with someone else. It seems you then need the parentFolderId for that other user. Getting  "message": "A folder id must be specified for delegate access." How is this supposed to work? How do you get that id?

**Comment by angelgolfer-ms** [comment]
Hi, thanks for your patience. I pinged the owner product team regarding your questions. I'll give an update once I hear back.

**Comment by Oddleif** [comment]
Any feedback from the product team on this?

**Comment by angelgolfer-ms** [comment]
Hi, thanks for your patience! I got confirmation and just fixed the content in PR #4981 . You should be able to see the content updated in the next day.
