### ISSUE TITLE
@removed not in response when user is deleted

### ISSUE THREAD

**Issue by nickdekesel** [microsoftgraph/microsoft-graph-docs#4498]
When a user is deleted or permanently deleted the annotation @removed is not added to the response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05eda6b9-c06f-2a02-707c-34b49f1d6f6e
* Version Independent ID: cf533ea9-3054-ef1d-b8eb-aa5c4589fbdf
* Content: [Get incremental changes for users - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-users#feedback)
* Content Source: [concepts/delta-query-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-users.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by venelin-phonebook** [comment]
Have the same problem.

**Comment by baywet** [comment]
Hi,
Sorry for the long delay in the answer.
Are you still experiencing the issue? If yes can you provide a clear reproduction as well as the requests ids please? Thanks!

**Comment by baywet** [comment]
closed due to no response

**Comment by gd1212** [comment]
Hello, could you please re-open this issue? I have the same problem with deleted users. A GET request to https://graph.microsoft.com/v1.0/users/delta doesn't contain the "@removed" annotation for deleted users. Thanks.

**Comment by baywet** [comment]
Hi @gd1212 
Can you provide more details please? Did your request originally contain a select? Thanks!

**Comment by gd1212** [comment]
Hello, no I didn't include a $select query parameter

**Comment by baywet** [comment]
Hi @gd1212 
I went ahead and did some testing.
I do get the reason property. As this issue list is reserved for issues with the documentation, please go ahead and open a support case from your tenant. This will allows our support engineers to investigate why you are not getting the property.
