### ISSUE TITLE
statement "If a Driveitem has a non-null shared facet, the item has been shared." doesn't seems to be correct 

### ISSUE THREAD

**Issue by TCPcloudDEV** [microsoftgraph/microsoft-graph-docs#4499]
I have many DriveItems on my personal OneDrive that used to be shared and not share any more, but they still have non-null shared facet. Why is that? According to this article itm.Shared should be null for those items. How can I check via  Graph API that item is truly shared on not? OneDrive.com seems to showing sharing data correctly and for all items that used to be shared displays message: This item is not shared.  How can I achieve it using Graph API? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 251542e4-d834-1673-cd2a-c51c3ea9338f
* Version Independent ID: 5b35e6bb-86f2-3b2b-6112-28e85ad24ef4
* Content: [Shared - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/shared?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/shared.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/shared.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by TCPcloudDEV** [comment]
I'm still getting not null values for items that no longer shared. What is the best way to get only shared by me items via  Microsoft Graph API?

**Comment by v-pajorg** [comment]
@JeremyKelley  any news on this?
