### ISSUE TITLE
TASK resource type not operational without Planner

### ISSUE THREAD

**Issue by kachihro** [microsoftgraph/microsoft-graph-docs#45]
The /tasks endpoint shows an error - either 404 or 'unknown segment'

This REST url doesn't work : 
http://graph.microsoft.io/docs/api-reference/beta/api/task_list

Can you update the doco, to notify that this endpoint is reliants on the "PLANNER" functionality - which hasn't been rolled out across all tenants, as yet ?

Within our tenant (Australia), we haven't got this ability (PLANNER) - is is only for USA tenants ??

Also - need to distinguish between a SharePoint task (specifically - a workflow task) - and a O365 task.  
I'd been trying to do an API call to get all "my workflow tasks" - this is NOT the way to do it.

**Comment by martellaj** [comment]
Hey, @kachihro, thanks for the feedback. I'm not :100:% sure on Planner roll out, but can you confirm that you were trying to access it via `beta` endpoint? Can you provide the whole request? Thanks!

**Comment by kachihro** [comment]
![image](https://cloud.githubusercontent.com/assets/16025947/11770175/25296328-a24c-11e5-994d-ce0a744fce56.png)

**Comment by kachihro** [comment]
![image](https://cloud.githubusercontent.com/assets/16025947/11770179/2e72cd2a-a24c-11e5-8a1c-ad236d9639e8.png)

**Comment by kachihro** [comment]
URL...>    https://graph.microsoft.com/beta/tasks

**Comment by misterabdullahAziz** [comment]
@martellaj i use the same request.
![screenshot from 2016-03-02 14 33 40](https://cloud.githubusercontent.com/assets/8374545/13456495/430f5088-e085-11e5-974e-b0bba7eccd84.png)

**Comment by keyur32** [comment]
Hi @kachihro, Planner general availability was announced this past summer (https://blogs.office.com/2016/06/06/microsoft-planner-ready-for-showtime/) and should be available to all tenants, and accessible through both the beta endpoint.
