### ISSUE TITLE
deltaLink manager changes?

### ISSUE THREAD

**Issue by butchmarshall** [microsoftgraph/microsoft-graph-docs#4500]
I am successfully using the deltaLink to sync my profiles for every field except manager.

When a users manager changes deltaLink does not return an updated user profile.

Am I doing something wrong or is this out of scope?  Is it possible to get manager changes to trigger an update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05eda6b9-c06f-2a02-707c-34b49f1d6f6e
* Version Independent ID: cf533ea9-3054-ef1d-b8eb-aa5c4589fbdf
* Content: [Get incremental changes for users - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-users)
* Content Source: [concepts/delta-query-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-users.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HDsouza-FPSS** [comment]
In my select query I use the manager attribute that has successfully worked. It will give you a user's profile if their manager has changed, as well as the manager's ObjectID. Looks something like this:
"manager@delta": [
                {
                    "@odata.type": "#microsoft.graph.user",
                    "id": "12345ef5-1234-1fa3-1223-126lyo898"
                },
                {
                    "@odata.type": "#microsoft.graph.user",
                    "id": "984af984-9g65-65gg-9865-19462684",
                    "@removed": {
                        "reason": "deleted"
                    }
                }
            ]

**Comment by baywet** [comment]
thank you for providing the answer @HDsouza-FPSS !
Closing.
