### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by rbrayb** [microsoftgraph/microsoft-graph-docs#4504]
"To learn more, including how to choose permissions, see Permissions."

The Permissions link is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 729b3d53-530b-58bc-e314-149f54e8fcdd
* Version Independent ID: 1bebd3c1-6275-e90e-2cdd-5c424013b6c1
* Content: [List trustFrameworkPolicies - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/trustframework-list-trustframeworkpolicies?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/trustframework-list-trustframeworkpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/trustframework-list-trustframeworkpolicies.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @valnav
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by seantleonard** [comment]
The Permissions link has .md at the end. Take the .md out and it should work, but this still needs to be corrected in the documentation .

**Comment by Lauragra** [comment]
Thanks. I just submitted a fix and this will go live when we publish this afternoon.
