### ISSUE TITLE
Http Response Code is Incorrect

### ISSUE THREAD

**Issue by Andy65** [microsoftgraph/microsoft-graph-docs#4508]
The actual HTTP response code returned by this method is 200 OK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b734f89-f938-1a8a-c6d0-5ed5aac8aa39
* Version Independent ID: 50e02b8f-ed23-31e7-1c89-94be5fec2e3b
* Content: [schedule: share - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/schedule-share?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/schedule-share.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/schedule-share.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
We are looking into it and let you know.

**Comment by Meghana-MSFT** [comment]
Hi Doc Team, Please update the status as 200 OK.

**Comment by lramosvea** [comment]
@akumar39 could you please help updating the doc as suggested? Thanks
