### ISSUE TITLE
No next link

### ISSUE THREAD

**Issue by gazeboparty** [microsoftgraph/microsoft-graph-docs#4509]
Doc says: "get all the rooms in the tenant, or get all the rooms in a specific room list". But there is no nextLink to page. It only returns the first 100 for every invocation. How do you get next results?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e112f02f-d98f-e863-dfc2-f1c80530d65c
* Version Independent ID: 136af786-1231-28db-9de4-a44b59e066f2
* Content: [user: findRooms - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-findrooms?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/user-findrooms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-findrooms.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by thisisforeagle** [comment]
+1
I know this is in beta but a response would be very much appreciated

**Comment by abhijeet610** [comment]
+ 1
Is there a way to find emailAddress based on room name only?

**Comment by vrod9429** [comment]
Hi, please use our new API https://docs.microsoft.com/en-us/graph/places-concept-overview

**Comment by EliasKaplan** [comment]
To paginate through responses, in Places api, https://docs.microsoft.com/en-us/graph/places-concept-overview, use $count=true, to find the number of entries and $top, $skip to go through pages.
