### ISSUE TITLE
Add resource and methods for restrictedSignIns

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4511]
Missed an item here that is in the service.  Also need to backport some of the new topics from v1.0 to beta.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e7c8c9-8f24-f7b9-f275-59699e748383
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signin.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
