### ISSUE TITLE
Add info about external user state in this topic

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4549]
It's hard to find information on how to query for external user state.  This should be mentioned in this topic, along with the user  properties that can be tracked, with a link to the user entity type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c019c1-e222-38d1-74c6-845253b43cef
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation manager - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/invitation.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by juunas11** [comment]
I'd like to know how to find out if the invitation has been accepted or not. The MS Graph API Swagger doc identifies paths to GET /invitations and GET /invitations/id, but neither of these work and produce a response like this:

```
{
    "error": {
        "code": "UnknownError",
        "message": "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n",
        "innerError": {
            "request-id": "4e646fc2-5277-4048-9f8b-5b19704e49b1",
            "date": "2019-05-10T21:08:51"
        }
    }
}
```

Getting an invite is also available in the Graph SDK but only throws the above error.

**Comment by dkershaw10** [comment]
@juunas11 Yeah - that's exactly the issue.  GET /invitations is not supported (although I can totally see how you would expect that to be a valid request).  The error is bad too (I'll take that up with the team).  @valnav Can you file a bug for the error condition here please?

**Comment by dkershaw10** [comment]
Doc updated
