### ISSUE TITLE
The menu item Reference -> Tools gives a 404 - Page not found message

### ISSUE THREAD

**Issue by cristianiorga** [microsoftgraph/microsoft-graph-docs#4551]
1. Go to https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0
2. Click on Tools

Expected: Tools page should load
Actual: 404 - Page not found page loads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d489b596-8db6-6b4e-7271-77a6fb735c37
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph REST API v1.0 reference - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/overview.md)
* Product: **non-product-specific**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jdanyow** [comment]
Investigating: https://dev.azure.com/ceapex/Engineering/_workitems/edit/91703/

**Comment by Lauragra** [comment]
Hi @cristianiorga , thanks for reporting this. The Tools TOC entry is intended to be a parent node. I submitted PR #4569 to update the TOC file accordingly. This fix will be visible on the live site later this afternoon.
