### ISSUE TITLE
What is $ref?

### ISSUE THREAD

**Issue by fatal-exception** [microsoftgraph/microsoft-graph-docs#4552]
Hi there,

the doc doesn't specify what $ref should be set to, can this please be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae95208a-8b4f-fac5-14d5-b949692c9aa8
* Version Independent ID: 2816e3d5-8ac8-8c40-8b2e-1e13f2ee8fa9
* Content: [Add directory role member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryrole-post-members?view=graph-rest-1.0&tabs=javascript)
* Content Source: [api-reference/v1.0/api/directoryrole-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryrole-post-members.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
$ref isn't set to anything.  This is part of the syntax (based on OData v4) to say that you are just working with the navigation entity reference/relationship.  See http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_EntityIdsandEntityReferences.  Here, in the `POST` request, the payload of the request indicates where this relationship reference should link to.

So in this case, a directoryRole has members.  Here you are adding a member relationship (entity reference) from a directoryRole to an existing user entity.

**Comment by fatal-exception** [comment]
ok thanks a lot. I looked through all the Microsoft Graph docs and couldn't find this information, and thought it was quite unusual to have dollar, a symbol that needs a URI escape, in a path. Maybe it's worth you adding this information to the Microsoft Graph API introduction?

**Comment by dkershaw10** [comment]
Yeah that's reasonable - although I *think* we say somewhere that Microsoft Graph uses OData syntax.  $ref is defined in OData, but I get that it might look strange for anyone who's not looked at OData.
