### ISSUE TITLE
Improve information about OData query parameter support

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4555]
All of the identityRiskEvent topics could be improved with a list of supported OData queries (and filterable properties), and examples, to avoid support calls.
Support issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f306ce73-293d-256c-820b-7b7862e0b471
* Version Independent ID: 3f4dca70-c765-79c3-13a7-d92f58c730e6
* Content: [identityRiskEvent resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/identityriskevent?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/identityriskevent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/identityriskevent.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cloudhandler** [comment]
This API has been deprecated in public cloud, pending deprecation in us gov. Can we close this?
