### ISSUE TITLE
Caml query/ filter functionality

### ISSUE THREAD

**Issue by anisiaalexandra** [microsoftgraph/microsoft-graph-docs#4556]
Is there a way to have some sort of Caml query that we can pass and recuperate filtered items? thank you in advance for response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14f44873-e61b-3f77-e2ad-b46112b065b2
* Version Independent ID: 3ef66bdc-06cf-4356-4e1e-f4d7bed17dcb
* Content: [Get an entry from a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-get?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/listitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by dsm0880** [comment]
I'm looking for this as well. Microsoft has recently started to us the word "Legacy" with the SharePoint REST API. That is a bit concerning given the functionality on the MSGraph side does not fill in all the gaps.
