### ISSUE TITLE
immutable-id

### ISSUE THREAD

**Issue by nielsbartels** [microsoftgraph/microsoft-graph-docs#4557]
Good to know: The message ID is not something you want to rely on. I found this announcement after searching for a while:
https://developer.microsoft.com/en-us/outlook/blogs/announcing-immutable-id-for-outlook-resources-in-microsoft-graph/

Summary: Add this in the headers of your request: Prefer: IdType="ImmutableId" to get more (stable) ID's that will only change in case of archiving or a actual move to another mailbox etc.

If you got a lot of (historic) data. You can even convert the existing ID's to the Immutable structure with this endpoint: POST https://graph.microsoft.com/beta/me/translateExchangeIds

Read more in the (source) / announcement.
https://developer.microsoft.com/en-us/outlook/blogs/announcing-immutable-id-for-outlook-resources-in-microsoft-graph/

@Microsoft, I was really missing this important detail on this page.

Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd382e4-95b6-3ccf-6a15-02d0cc7ed841
* Version Independent ID: 276cebbe-10bc-100e-f9b1-51b2ba30c64b
* Content: [message resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/message.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Thanks for pointing this out @nielsbartels. Immutable ID is still in preview, so we haven't mentioned it at all in v1 docs. I'm following up with engineering on this.

In the meantime, I'll update the beta docs to call this out.

**Comment by gregory** [comment]
@jasonjoh is there a way to translate conversationId and parentFolderId to immutable formats? ...

**Comment by jasonjoh** [comment]
@gregory you should leave feedback on [UserVoice](https://microsoftgraph.uservoice.com/) about your pains, especially on the search/query endpoint.

Folder IDs are always immutable, so they don't care about the header. Conversation IDs aren't part of the immutable supported set. See https://docs.microsoft.com/graph/outlook-immutable-id?view=graph-rest-beta#items-that-support-immutable-id

**Comment by gregory** [comment]
NVM I'll just use the $search on the /messages endpoint: 
https://docs.microsoft.com/en-us/graph/query-parameters#search-parameter

**Comment by Shawnaldinho** [comment]
I keep seeing the point that Folder IDs are immutable, unless I'm mistaken, Folder IDs are generated as part ReplicaID and part Global Counter, where the ReplicaID is a unique reference based on the Store the mailbox exists on. If the mailbox is moved to a different Store, the FolderIDs will change. The definition of immutability is "unchanging over time or unable to be changed." ... in Exchange Online, mailboxes could move between Stores on a daily basis. The reason Microsoft have created the Immutable ID is to aid external applications tracking those IDs, but as more people move to Exchange Online, and mailboxes move around between Stores, will the immutable ID even be useful? The "immutability" will exist for a short period whilst the mailbox exists within the same store. After that, ID's change and you've lost your immutability?

**Comment by jasonjoh** [comment]
@Shawnaldinho this is what the engineering team has told me regarding folders - basically they did not implement immutable ID for folders because the folder IDs never change. I'm not sure if this covers store moves.

Immutable ID should survive across a store move AFAIK. Let me check and I'll report back.

**Comment by jasonjoh** [comment]
Both IDs will survive a database move. The only operation that will cause these IDs to change are copy/delete operations, instead of a true "move".

So in the scenario you describe, the IDs will survive. They won't survive if:

- Moving a message/folder to another mailbox (such as moving from the main mailbox to an archive mailbox).
- Disaster recovery scenarios that require creating a whole new mailbox and copying content from the old to the new. This should be a pretty rare occurrence :).

**Comment by Shawnaldinho** [comment]
I don’t know if this is always the case. We recently migrated hundreds of mailboxes between on-prem Exchange databases and afterwards, an external application that was tracking FolderIDs had a lot of problems as those folders now didn’t exist (e.g. their IDs had changed). Also, the same thing occurred when migrating from on-prem Exchange to Exchange Online. We are now a little worried that in EOL we will have no ability to control mailbox moves, and thus ID changes, within that environment. We haven’t found an instance yet where the IDs have changed but are tracking it through event listeners. Anyway I’m still not convinced these IDs are truly immutable.
