### ISSUE TITLE
stsRefreshToken is not set When creating Federated Domain User

### ISSUE THREAD

**Issue by watahani** [microsoftgraph/microsoft-graph-docs#4565]
When creating Federated Domain user using Graph API, stsRefreshTokenValidFrom value is not set.
It will cause that created users are forced sign in frequently.

To fix this issue, update stsRefreshTokenValidFrom value using Azure AD Connect or Azure AD Powershell.
https://support.microsoft.com/en-us/help/4025960/federated-users-in-azure-ad-are-forced-to-sign-in-frequently

Or using Graph API beta "user: invalidateAllRefreshTokens."
https://docs.microsoft.com/en-us/graph/api/user-invalidateallrefreshtokens?view=graph-rest-beta&tabs=cs

see #1945

It is better to add Note to describe this consideration and how to fix it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-US/graph/api/user-post-users?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Closed with https://github.com/microsoftgraph/microsoft-graph-docs/pull/4675
