### ISSUE TITLE
Application permission for checkMemberGroups

### ISSUE THREAD

**Issue by husseinkorly** [microsoftgraph/microsoft-graph-docs#4576]
The documentation states that only `Directory.Read.All` or `Directory.ReadWrite.All` permission required for an application to call `/checkMemberGroups` and there's a bug when using `User.Read.All` or `User.ReadWrite.All` !  
An application with permissions `User.Read.All` and `Group.Read.All` should work. I just tried it !
Could you please clarify this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9b92830-bd9d-61db-7d2e-9ac356984332
* Version Independent ID: ecb93554-a5a3-d937-f0e4-4a1c6d388218
* Content: [checkMemberGroups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-checkmembergroups?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-checkmembergroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-checkmembergroups.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kostrse** [comment]
Have the same question: what is the minimal required permission to call this API?
Documentation is confusing.

On StackOverflow people asked the same question and no definitive answers:
https://stackoverflow.com/questions/43215253/minimum-set-of-permissions-required-for-checkmembergroups-graph-api-in-azure

**Comment by husseinkorly** [comment]
@kostrse, the minimal permissions that you can give to an application are `User.Read.All` and `Group.Read.All`.
I am guessing you don't want to give all the permissions that listed in the documentation.

**Comment by kostrse** [comment]
After some experimentation, it seems that the minimum permissions are the following:

`/me/checkMemberGroups`

* **User.Read**
* **GroupMember.Read.All**

`/users/{userId}/checkMemberGroups`

* **User.ReadBasic.All**
* **GroupMember.Read.All**

**Comment by krbain** [comment]
The doc has been updated to address this issue and identify the list of permissions that can be used.
