### ISSUE TITLE
The Chinese version of this page's title is incorrect.

### ISSUE THREAD

**Issue by foxdave** [microsoftgraph/microsoft-graph-docs#4577]
For Chinese version of this page, the title is the same as 'https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get-mailboxsettings.md' which is called '获取用户的邮箱设置'.
It is not correct, the title should be '更新用户的邮箱设置’.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 743129d7-ae63-b658-2690-8f9ee2c2743d
* Version Independent ID: 04d4f30e-15cc-e4bf-ec8e-2da840ce5d9f
* Content: [Update user mailbox settings - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/user-update-mailboxsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update-mailboxsettings.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by foxdave** [comment]
![2019-05-13 14_16_53](https://user-images.githubusercontent.com/7928690/57599939-dd490e80-758a-11e9-939e-fa63eac2b3ec.png)

**Comment by Lauragra** [comment]
@Soran-M , can you look into this issue please? Thanks.

**Comment by foxdave** [comment]
> @Soran-M , can you look into this issue please? Thanks.

Hi Lauragra

How is the issue?

**Comment by OfficeGlobal** [comment]
@Soran-M Working on a fix (Bug 3399995)

**Comment by OfficeGlobal** [comment]
@foxdave the title has been updated and published live
