### ISSUE TITLE
UnknownError when trying to add a message to a specific channel

### ISSUE THREAD

**Issue by adriantompaarchive360** [microsoftgraph/microsoft-graph-docs#4578]
I have this code:

var body = new ItemBody
            {
                ContentType = BodyType.Text,
                Content = "...",
            };

            var chatMessage = new ChatMessage
            {
                Subject = "Hello again. How are you? This is Adrian!",
                Body = body,
                Attachments = null
            };

           var message = await gsc.Teams[teamId].Channels[channelId].Messages.Request().AddAsync(chatMessage);

The error is: 

Microsoft.Graph.ServiceException: 'Code: UnknownError

Inner error
'

what is not ok at this point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ecd308d-1814-d043-17cc-0b852e08db9a
* Version Independent ID: ff798848-0095-a878-817f-c70a9fb2955b
* Content: [Send a message in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-chatmessage?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/channel-post-chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-chatmessage.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by butchmarshall** [comment]
Getting the same thing.  Is it returning a 401 HTTP code for you?

I am able to retrieve teams/channels via the beta API but posting a new message does not seem to work.

I wonder if this is because I'm using an application token.  It would be a shame if our applications couldn't push out messages.

**Comment by adriantompaarchive360** [comment]
It was an authorization issue. After I gave the necessary permissions in Azure portal, it worked fine. but again, the API seems very unstable ;)

**Comment by BerndSadleder** [comment]
I have exactly the same issue using application permission (not delegated) -> i also tried to assign every possible application permission - but does not seem to work.

@adriantompaarchive360: which permission was missing?

**Comment by adriantompaarchive360** [comment]
Group.ReadWrite.All for delegated. pls try to add the same permissions for legacy app registrations.

**Comment by BerndSadleder** [comment]
Thank you, but it does not help - same exception occuring.
Possibly the exception only occures when using application permission - using client credential flow (clientId, clientSecrete).

**Comment by adriantompaarchive360** [comment]
try to add permissions for both: application and delegated. I'm using authentication with public client application (requires input for user/password)

**Comment by adriantompaarchive360** [comment]
did you manage to solve the issue?

**Comment by BerndSadleder** [comment]
I don't get it to work, when using client credential flow (no user/password) (even with giving Group.ReadWrite.All for delegated).

**Comment by nkramer** [comment]
This API does not support application permissions.

**Comment by praveenpudi329** [comment]
We need to register for accessing messages using application permissions https://docs.microsoft.com/en-us/graph/teams-protected-apis
