### ISSUE TITLE
event:  responseStatus -  difference between None and NotResponded

### ISSUE THREAD

**Issue by hphirke** [microsoftgraph/microsoft-graph-docs#4579]
responseStatus resource types are:
The possible values are: None, Organizer, TentativelyAccepted, Accepted, Declined, NotResponded

Out of these except None and NotResponded are self-explanatory.

What is different between None and NotResponded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8837ed-fee9-835f-c724-88b2cea5688b
* Version Independent ID: cf38a184-7667-1039-c0b2-d1c6f2bcc95a
* Content: [responseStatus resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/responsestatus?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/responsestatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/responsestatus.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AFrazier-Git** [comment]
Don't KNOW that this is difference, but... as I'm building my app, I noticed that if someone declines an invite, they show up as "Declined" to the organizer's event, but the events of other attendees, it show their status as "None".

Also, the organizer doesn't appear in the attendee list for the organizer, but does appear with a "None" status to other attendees.

**Comment by AFrazier-Git** [comment]
I think that "none" specifies that a response is not required, such as when the attendee is also the organizer.

**Comment by AFrazier-Git** [comment]
After reviewing further, that doesn't seem to be it after all. May be that "none" means the user hasn't responded to the event at all, whereas "notResponded" means they initially responded but event has since been updated and the user hasn't responded again.

**Comment by dkoleary88** [comment]
I am also having this issue. This needs to be more clearly documented.
From what I've seen, some Outlook clients will set this as "none" for a self-organized event.

**Comment by Harini84** [comment]
Please find the details below:

None – is from organizer's perspective. This value is used when the status of an attendee/ participant is reported to the organizer of a meeting.

NotResponded – is from attendde's perspective. Indicates to the attendee that he has not responded to the meeting request.

Clients can proceed to treat NotResponded == None.

Since server components EWS, EAS, XSO expose both the values to client, this is made available on service layer as well.

@angelgolfer-ms 
Since this issue was raised an year ago, kindly update the documentation for 'None' and 'NotResponded' as above.

**Comment by isvargasmsft** [comment]
Hello @hphirke, 

My apologies for the delays in our response. Thank you for reporting this issue. 

Adding a clearer description in our documentation now. 

Kind regards,

Isaac
