### ISSUE TITLE
Next Steps broken links

### ISSUE THREAD

**Issue by mmascolino** [microsoftgraph/microsoft-graph-docs#4580]
The "datasets, regions and sinks" & "user selection and filtering" links in the "Next steps" section are broken links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0302f7b1-e754-fd0a-4a8a-057ed5deaa9a
* Version Independent ID: f819a46b-23d4-65c4-fc12-5b558b81511a
* Content: [Get started with Microsoft Graph data connect - Microsoft Graph](https://docs.microsoft.com/en-us/graph/data-connect-get-started#feedback)
* Content Source: [concepts/data-connect-get-started.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/data-connect-get-started.md)
* Product: **data-connect**
* Technology: **microsoft-graph**
* GitHub Login: @ajacks-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tlenig** [comment]
Thanks for highlighting this issue! We are working to rectify it

**Comment by Lauragra** [comment]
Thanks for bringing this to our attention. We just published a fix; it should be visible on the live site shortly.
