### ISSUE TITLE
The App Registration link in the Auth Overview is broken.

### ISSUE THREAD

**Issue by nkramer** [microsoftgraph/microsoft-graph-docs#4581]
Issue: The App Registration link ("Begin your Microsoft Graph journey by registering your application.") is broken.

Article: https://docs.microsoft.com/en-us/graph/auth/?toc=.%2Fref%2Ftoc.json&view=graph-rest-beta

**Comment by nkramer** [comment]
Opened on behalf of Steven Abrams (MSFT)

**Comment by Lauragra** [comment]
Thanks for raising this. We merged a fix and it will go live with today's publish.
