### ISSUE TITLE
Success status code is actually 204

### ISSUE THREAD

**Issue by mbrrg** [microsoftgraph/microsoft-graph-docs#4586]
No content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0a37b89-80c2-00b8-3ac3-55c5978e6011
* Version Independent ID: 64125169-a127-0f95-2763-a1afe1ee674f
* Content: [Update plannertaskdetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/plannertaskdetails-update?view=graph-rest-beta&tabs=javascript#feedback)
* Content Source: [api-reference/beta/api/plannertaskdetails-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/plannertaskdetails-update.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by thesofakillers** [comment]
I'm also getting this... is this an error in the documentation or? Any updates at all?

**Comment by jthake-msft** [comment]
dupe as #5794  has engagement on it.
