### ISSUE TITLE
SDK sample code

### ISSUE THREAD

**Issue by blair-bryant** [microsoftgraph/microsoft-graph-docs#4596]
Is the SDK sample code correct on this page? It looks to be the code to create a user not send an invitation. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51b2654-e447-d495-2788-d6d5b13402b4
* Version Independent ID: 32183c44-363a-a028-a3d9-390b99bffc8b
* Content: [Create invitation - Microsoft Graph v1.0](https://docs.microsoft.com/en-au/graph/api/invitation-post?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/invitation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/invitation-post.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
@darrelmiller , can you please look into this issue? Thanks.

**Comment by darrelmiller** [comment]
@blair-bryant Thanks for the heads up on this.  It does not look like correct code to me.  I will open an issue to investigate.

**Comment by imartinez2** [comment]
If you need send the invitation email add this parameter to the request: sendInvitationMessage:Boolean, please refer to https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0

**Comment by andrueastman** [comment]
This was closed via https://github.com/microsoftgraph/microsoft-graph-docs/pull/4614
