### ISSUE TITLE
New Planner Task error - InternalServerError - Unexpected end when reading token

### ISSUE THREAD

**Issue by joostvdlinden** [microsoftgraph/microsoft-graph-docs#4609]
Dear all,

I am trying to create a new task in Microsoft Planner through the use of the Office Graph API. 
I use this article as a reference: https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=javascript

I use Postman to test the request outcome. Please note that I am a novice/beginner at generating API calls for Office Graph. 
Somehow, the request is being answered with an 500 error:

> {
    "error": {
        "code": "InternalServerError",
        "message": "Unexpected end when reading token. Path 'assignments.c52fede4-537a-4fac-b2b9-033224cc5753'.",
        "innerError": {
            "request-id": "5cb01562-5b48-4b1d-81f2-2652973b1709",
            "date": "2019-05-15T21:41:28"
        }
    }
}

My API call is quite the same as how Microsoft described it in its article,  as follows:

POST https://graph.microsoft.com/v1.0/planner/tasks

**Headers used:**
Key: Content-Length
Value: 285
Key: Authorization
Value: Bearer eyJ……….
Key: Content-Type
Value: application/json

**Body used**

> {
>   "planId": "rdKJDnc............",
>   "bucketId": "EOBeGf................",
>   "title": "Just some title",
>   "assignments":{ 
>     "c52fede4-537a-....................Azure AD User Object ID": {
>       "@odata.type": "#microsoft.graph.plannerAssignment",
>       "orderHint": " !"
>     }
>   }
> }

In Microsoft's example, they include a comma before the last curly bracket. Postman is giving me an error when I leave this comma as it is.

I am struggling for the whole evening to find a clue to this issue. Is the example provided by Microsoft not complete? I assume that it is ready to use, and that I only need to change the variables.

I hope the description of my issue is clear enough.

Thanks in advance for your help!

Joost

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c5c966-fda0-a17d-9362-6466585ad2bf
* Version Independent ID: 93a1b1df-e030-a6d9-8e5f-fa5051fa7122
* Content: [Create plannerTask - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=javascript)
* Content Source: [api-reference/v1.0/api/planner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/planner-post-tasks.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TarkanSevilmis** [comment]
Yes the comma is erroneous. The error looks like a json parsing issue. I’ve noticed that you have the exact same content-length in your request from the sample. Is that number actually correct for your request? That may be the issue, as the error seems to be indicative of the content being terminated abruptly.

**Comment by joostvdlinden** [comment]
> Yes the comma is erroneous. The error looks like a json parsing issue. I’ve noticed that you have the exact same content-length in your request from the sample. Is that number actually correct for your request? That may be the issue, as the error seems to be indicative of the content being terminated abruptly.

Dear @TarkanSevilmis, 
Thank you for your help. I really appreciate it.

I have increased the **Content-Length** value. My findings are interesting (_I still use Postman to troubleshoot_):

When I use Content-Length value <= 300, I get response:

> {
>     "error": {
>         "code": "InternalServerError",
>         "message": "Unexpected end when reading token. Path 'assignments.c52fede4-537a-4fac-b2b9-033224cc5753'.",
>         "innerError": {
>             "request-id": "99955ac0-e051-4c12-b8f9-4241990177ff",
>             "date": "2019-05-16T06:31:15"
>         }
>     }
> }

When I use Content-Length value = 301, 302 or 303, I get response:

> {
>     "error": {
>         "code": "BadRequest",
>         "message": "Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.",
>         "innerError": {
>             "request-id": "4feec4bf-c62d-4802-bca7-dbdb2020b62f",
>             "date": "2019-05-16T06:33:51"
>         }
>     }
> }

When I use Content-Length value >= 304 and <= 318, I get response:

> {
>     "error": {
>         "code": "InternalServerError",
>         "message": "Unexpected end when deserializing object. Path 'assignments.c52fede4-537a-4fac-b2b9-033224cc5753.orderHint', line 8, position 23.",
>         "innerError": {
>             "request-id": "67557b06-a166-422e-9753-001166dec61c",
>             "date": "2019-05-16T06:37:05"
>         }
>     }
> }

When I use Content-Length value = 319, it works!! Why does it matter that much, the exact value of Content-Length? I have also noticed that when I completely remove the Content-Length property from the request's headers, it also works!

I thought it was a required property since it was included in Microsoft's example.

**Comment by TarkanSevilmis** [comment]
Content-Length is pretty much required in the HTTP protocol, which is the basis of most modern web requests. It identifies the length of the request content. You can read more about the header here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

Since it is essential, I’d think Postman (or most web request libraries) would add this automatically for you (based on the content of the request), without you needing to explicitly specify it yourself.

**Comment by joostvdlinden** [comment]
You were completely right. After removing the Content-Length key, Postman added it automatically while sending the request.

Thank you for all your effort! And thanks for referring to more info. Case solved :-)
