### ISSUE TITLE
List classes returns classes you don't have permission to see with delegated EduRoster.ReadBasic

### ISSUE THREAD

**Issue by stnor** [microsoftgraph/microsoft-graph-docs#4613]
Ideally the API should only return the classes you're allowed to see...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcab0a3-a255-5b3d-82d5-32151073d238
* Version Independent ID: cf41c6fc-448b-9e0e-a806-7eac97bf4e1a
* Content: [List classes - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationroot-list-classes?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/educationroot-list-classes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/educationroot-list-classes.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stnor** [comment]
Mike, is this a bug that will be fixed at some point? @mmast-msft

**Comment by mmast-msft** [comment]
This is actually by design.  /education/classes will list all classes, even with the delegated ReadBasic permission.  An example use might be accessing a course catalog.

**Comment by stnor** [comment]
Ok. Its not consistent with the user interface though

**Comment by stnor** [comment]
Yeah - I ended up filtering out all classes with 0 students. 

/Stefan

**Comment by mmast-msft** [comment]
Thank you for the feedback.  The API is designed to be useful in a variety of EDU apps.  That does mean putting some of the burden of filtering those apps.
