### ISSUE TITLE
The SDK for C# does not show how to add owners and members.

### ISSUE THREAD

**Issue by adrichema** [microsoftgraph/microsoft-graph-docs#4622]
The SDK for C# does not show how to add owners and members.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by BrianTJackett** [comment]
I see example 2 showing how to add members and owners for the C# language.  Recommend closing this issue.
