### ISSUE TITLE
What's the default or maximal page size when the $top query parameter is missing?

### ISSUE THREAD

**Issue by HeinPauwelyn** [microsoftgraph/microsoft-graph-docs#4636]
If the request is paged and you don't added the `$top` query parameter, is there a default or maximal page size on the request? If yes, how big are they?

---
#### Document Details

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/paging#feedback)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Unfortunately (per the referenced page) there's no consistency across APIs on the default or maximum size.  For example, in Azure AD (users, groups, devices etc) the default is 100 and max 999.  In Outlook the default is 10 (and I can't even tell you what the max is here).

**Comment by msimecek** [comment]
Where can developers get this information for individual APIs? For instance I would like to know what's the page size limit for the "List messages" API in Microsoft Graph. The [Docs page](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=cs) says:

> Depending on the page size and mailbox data, getting messages from a mailbox can incur multiple requests. The default page size is 10 messages. To get the next page of messages, simply apply the entire URL returned in @odata.nextLink to the next get-messages request. This URL includes any query parameters you may have specified in the initial request.

It  would be great to have consistency at least in the MS Graph documentation (such as simple table with "default" and "limit" numbers).

**Comment by povlhp** [comment]
No matter pagesize, your will always have results larger than the largest possible pagesize. So just make robust code, and add the extra while loop so you run as long as you have a valid nextlink.

**Comment by Dsiddhesh** [comment]
@povlhp can we safely set $top to 100 in our application ?

**Comment by Herz3h** [comment]
For some reasons the max for sharepoint seems to be 203.....even though I specified $top 999

**Comment by FaithOmbongi** [comment]
As Dan mentioned, each API has its own default and maximum page size. If the question applies to a specific API and the page limits are not documented on the API page, kindly open an issue from the respective API page. Closing this issue for now.
