### ISSUE TITLE
Content-type 'application/json' not accepted

### ISSUE THREAD

**Issue by andysh-uk** [microsoftgraph/microsoft-graph-docs#4648]
Trying to create an event with the Content-Type header set to "application/json" results in the following error returned from the API:

```JSON
{
  "error": {
    "code": "RequestBodyRead",
    "message": "A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false, application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true, application/json;odata.metadata=minimal;odata.streaming=true, application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false, application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true, application/json;odata.metadata=minimal;odata.streaming=false, application/json;odata.metadata=minimal;IEEE754Compatible=false, application/json;odata.metadata=minimal;IEEE754Compatible=true, application/json;odata.metadata=minimal, application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false, application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true, application/json;odat  a.metadata=full;odata.streaming=true, application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false, application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatib...' matches the content type 'applicaton/json'.",
    "innerError": {}
  }
}
````
>A supported MIME type could not be found that matches the content type of the response. None of the supported type(s) 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false, application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=true, application/json;odata.metadata=minimal;odata.streaming=true, application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=false, application/json;odata.metadata=minimal;odata.streaming=false;IEEE754Compatible=true, application/json;odata.metadata=minimal;odata.streaming=false, application/json;odata.metadata=minimal;IEEE754Compatible=false, application/json;odata.metadata=minimal;IEEE754Compatible=true, application/json;odata.metadata=minimal, application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=false, application/json;odata.metadata=full;odata.streaming=true;IEEE754Compatible=true, application/json;odat  a.metadata=full;odata.streaming=true, application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatible=false, application/json;odata.metadata=full;odata.streaming=false;IEEE754Compatib...' matches the content type 'applicaton/json'.

I had to set `Content-Type` to `application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false` (one of the suggestions in the error response) for this to come back successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by thisisforeagle** [comment]
Thanks for the above suggestion setting the **Content-Type** to 

> application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false

This helped me as well.
I was testing in Graph Explorer and would not read the response.

Its not clear that this content-type required when initially readings docs/examples.

**Comment by nozhT** [comment]
| ng=false;IEEE754Compatib...' matches the content type 'applicaton/json'
There's an "i" missing from your "applicaton"

**Comment by YogeshPateliOS** [comment]
Hii , I have remove Content-Type: application/json to 'application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false'
But it gives me a error: 
{"error":{"code":"RequestBodyRead","message":"Invalid JSON. A token was not recognized in the JSON content."}}
can you please help me on this. Thanks!

That's What i DID
```
            let baseURL = "https://outlook.office.com/api/v2.0/me/events"
            let parameters: Parameters = [
              "Subject": "Discuss the Calendar REST API",
              "Body": [
                "ContentType": "HTML",
                "Content": "I think it will meet our requirements!"
              ],
              "Start": [
                  "DateTime": "2020-03-14T18:00:00",
                  "TimeZone": "Pacific Standard Time"
              ],
              "End": [
                  "DateTime": "2020-03-16T19:00:00",
                  "TimeZone": "Pacific Standard Time"
              ]
            ]

        let headers: HTTPHeaders = [
            "Content-Type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false",
            "Authorization": "Bearer \(token)"
        ]

```
