### ISSUE TITLE
Delete plan doesn't seem to work (yet)

### ISSUE THREAD

**Issue by k-boden** [microsoftgraph/microsoft-graph-docs#4649]
Manually deleting a plan from within Teams is not an issue.
When you try to delete any plan (even a brand new one) with the following request, you will always receive a `403 Forbidden` error:

```
DELETE https://graph.microsoft.com/v1.0/planner/plans/{id}
If-Match: ... (value filled of course)
```

Is this request not implemented yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85091de2-df23-2c1f-72d9-256a94cfcf75
* Version Independent ID: 058ccce1-cd86-1d50-c6e2-15b48729e309
* Content: [Delete plannerPlan - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/plannerplan-delete?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/plannerplan-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannerplan-delete.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TarkanSevilmis** [comment]
We currently do not support deleting Plans through the API. You can delete Plans using Planner web app:  https://tasks.office.com.

**Comment by jeffblackadar** [comment]
Per above, would you have a scheduled date to support deleting Plans through the API?
