### ISSUE TITLE
Are attachments in Teams messages supported?

### ISSUE THREAD

**Issue by DeanMauro** [microsoftgraph/microsoft-graph-docs#4650]
Issue: Are Attachments supported?

Article: [Send a message to a channel](https://docs.microsoft.com/en-us/graph/api/channel-post-chatmessage?view=graph-rest-beta&tabs=cs)

There's a note that says "Note: Sending messages with attachments and images is not supported.", but the SDK sample code contains a list of attachments. Are they supported at this time?

**Comment by mooreds** [comment]
This is an issue for creating adaptive cards as well. The examples (here https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http#example-3-cards ) show creating an adaptive card via the API with an attachment, but I keep getting back an error message (400 bad request). The notes on the resource (here: https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta ) state that sending attachments won't work.
