### ISSUE TITLE
Delta link returns Appointment as Deleted, but it is actually not deleted 

### ISSUE THREAD

**Issue by rubanjoshva** [microsoftgraph/microsoft-graph-docs#4659]
Calendar deltas have started to return new created/updated appointments as `deleted`. This was working until this afternoon, but now I am getting responses like this  (even for a newly created appointment) : 

``` JSON
"value": [
    {
      "@odata.type": "#microsoft.graph.event",
      "id": "AAMkADNlZDIyMGIyLWY2M2EtNGE0NS1hNTgxLThlMjE3YzIyNjIyYgBGAAAAAABlmSrvjYWpR7w8qeyIUCsJBwDRq-dCzZ7LRb9kdOoCmT9eAAAAAAE-dCzZ7LRb9kdOoCmT9eAAM5NtUyAAA=",
      "@removed": {
        "reason": "deleted"
      }
    }
  ]
```

I am sure, I am not deleting the appointment, but I do only creation and update.

**Comment by mlafleur** [comment]
Are you able to see the appointment in Outlook? How are you creating/updating the appoint (a code sample would help).

**Comment by rubanjoshva** [comment]
Hi Yes, I am able to see the appointment in Outlook. I created it in Outlook web itself not thorough Graph REST.

**Comment by janstp** [comment]
Hi @rubanjoshva 
Is your event that you created between the start and end datetime in you getdelta request?

**Comment by jthake-msft** [comment]
Closed as no response.
