### ISSUE TITLE
isFavoriteByDefault propery is always null

### ISSUE THREAD

**Issue by AlexanderDorofeev** [microsoftgraph/microsoft-graph-docs#4661]
According to my tests in Graph Explorer isFavoriteByDefault property of Channel is always set to null. I can't set it when creating a channel via POST request or updating it via PATCH.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28943613-194a-6a5e-8245-57110fdeded6
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/channel.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by LudwigVanGysel** [comment]
I have this as well.

**Comment by agtenr** [comment]
+1
