### ISSUE TITLE
Had an issue with this API...

### ISSUE THREAD

**Issue by sivabalaguru** [microsoftgraph/microsoft-graph-docs#4673]
I did tried this Api using PowerShell call but never got succeeded:

function RefreshToken($loginURL,$resource,$ClientID,$clientSecret,$tenantName)
{
$body       = @{grant_type="client_credentials";resource=$resource;client_id=$ClientID;client_secret=$ClientSecret} 
$oauthResponse      = Invoke-RestMethod -Method POST -Uri $loginURL/$TenantName/oauth2/token?api-version=1.1 -Body $body 
return $oauthResponse
}  
$loginURL       = "https://login.microsoftonline.com" 
$resource = "https://graph.microsoft.com"
$ClientSecret="Secret" 
$ClientID="ID" 
$TenantName="tenant.com"
$oauth=RefreshToken -loginURL $loginURL -resource $resource -ClientID $ClientID -clientSecret $ClientSecret -tenantName $TenantName
$headerParams = @{'Authorization'="$($oauth.token_type) $($oauth.access_token)"}
$url="https://graph.microsoft.com/beta/riskyUsers/dismiss"
$ReportURL = "https://graph.microsoft.com/beta/identityRiskEvents?`$filter= riskLevel eq 'high' or riskLevel eq 'medium' &`$top=10"
$userIds=@()
$userIds+="UserGuid"
$body=(@{"userIds"=$userIds})|convertto-json
try
{
$Response = Invoke-WebRequest -UseBasicParsing -Headers $headerParams -Uri $url -Body $body -Method Post -ContentType "application/Json"
}
catch
{
$_
}

Here's the exception:
Invoke-WebRequest : The remote server returned an error: (500) Internal Server Error.
At C:\SourceCode\MIMSolution\PowerShellScripts\AzurePSMA\RiskyIdentityEvents\ExportScript_debug.ps1:21 char:13
+ $Response = Invoke-WebRequest -UseBasicParsing -Headers $headerParams -Uri $url  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

IsMutuallyAuthenticated : False
Cookies                 : {}
Headers                 : {Transfer-Encoding, request-id, client-request-id, x-ms-ags-diagnostic...}
SupportsHeaders         : True
ContentLength           : -1
ContentEncoding         : 
ContentType             : application/json
CharacterSet            : 
Server                  : 
LastModified            : 5/22/2019 12:06:28 PM
StatusCode              : InternalServerError
StatusDescription       : Internal Server Error
ProtocolVersion         : 1.1
ResponseUri             : https://graph.microsoft.com/beta/riskyUsers/dismiss
Method                  : POST
IsFromCache             : False

I did decoded the OAUTH token and found that it has all required permissions and the same token is used to call List IdentityRiskEvents which successfully retrieved.

I might be missing something that is required to call this API and not available in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972ebfab-90e6-a0d9-3e99-01deeeb1c791
* Version Independent ID: bef697c7-2687-5559-af79-1e3c9f74f94f
* Content: [Dismiss riskyUser - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/riskyusers-dismiss?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/riskyusers-dismiss.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/riskyusers-dismiss.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sivabalaguru** [comment]
![image](https://user-images.githubusercontent.com/15766653/58236976-b98f8080-7d61-11e9-867a-cb6f89381f7d.png)

Image showing that the token has all required permissions

**Comment by cloudhandler** [comment]
@sivabalaguru - what license do you have in your tenant? Do you have P2 licenses?

**Comment by sivabalaguru** [comment]
Yes we do have P2 license.

And Finally after multiple trails , I have figured out the solution:
Issue was with the token which as OAuth 1.0 earlier. 

I did fixed this snippet and the issue resolved:
``

**Comment by davidmu1** [comment]
@sivabalaguru - Can you please be more specific about the issue in the referenced article? Closing this issue for now. Please reopen with specific changes.
