### ISSUE TITLE
What's the maximum length of subscription for user and group

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4674]
The table does not document subscription length maximum for users and groups. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe0590e-070b-cf56-cbc7-1dcb8a266380
* Version Independent ID: 2d912536-afc5-60f1-e381-2eef892cbded
* Content: [subscription resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0#maximum-length-of-subscription-per-resource-type)
* Content Source: [api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/subscription.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
PR created: https://github.com/microsoftgraph/microsoft-graph-docs/pull/4707
