### ISSUE TITLE
Any way to convert DateTimeTimeZone to/from DateTime?

### ISSUE THREAD

**Issue by pawlowski** [microsoftgraph/microsoft-graph-docs#4680]
The DateTime type is fully implemented with comparison, equality, conversion, etc. The DateTimeTimeZone type seems to be new and only for JSON interactions with the Graph API.

I am using the C# SDK and would like to be able to take my DateTime and convert it so that I can hand it to the SDK to pass to the API, and then would like to get the response back and be able to convert it to DateTime. I haven't found any existing tools to accomplish this. I've been working with /v1.0/me/calendar/getschedule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e773d204-1933-45d8-17b2-5868787e25ca
* Version Independent ID: 9d5477ea-fe33-6234-94cf-fdfe3c3ecb9e
* Content: [dateTimeTimeZone resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/datetimetimezone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/datetimetimezone.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Per the pull request referenced above, this is being worked on in the SDK. In the meantime you can always use `DateTime.Parse` to convert to `DateTime`, and `DateTime.ToString` to convert from.
