### ISSUE TITLE
follow item not working in beta

### ISSUE THREAD

**Issue by harshdamaniahd** [microsoftgraph/microsoft-graph-docs#4685]
I am trying to write a code to follow document but it is not working
`https://graph.microsoft.com/beta//sites/****.sharepoint.com:/sites/Medarbeider-Documents:/lists/61850c31-b7a8-478e-8e5c-890b89c9d574/items/52/follow`

I am executing this code directly in explorer. Can i execute this request in explorer

Response which i get 
**```
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'follow'.",
        "innerError": {
            "request-id": "f3cbe430-41b5-4ca3-b608-495e6522e670",
            "date": "2019-05-28T15:16:23"
        }
    }
}
```**
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900c2e67-17f7-ac58-a027-3fb077bf4b35
* Version Independent ID: 77b39edd-8bc3-914c-8870-0215251bc14e
* Content: [Follow drive item - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-follow?view=graph-rest-beta&tabs=cs)
* Content Source: [api-reference/beta/api/driveitem-follow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-follow.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @chackman
* Microsoft Alias: **chackman**

**Comment by jthake-msft** [comment]
So resource not fund is stating that the item doesn't exist. Do other things work other than follow on that item?

**Comment by harshdamaniahd** [comment]
@jthake-msft okay this is my observations
Follow only works on Shared Document Library i.e default drive for a site. It doesnt work for other libraries in same site . 
API : 
`https://graph.microsoft.com/beta//sites/qa.sharepoint.com,4c3fec34-b7da-4b95-b258-33338538dc4f,733489ef-85df-4a46-a599-5eef9e3c45fa/drive/items/017LZDUZFQ3Q26RTOO6FGZYQXCYZCNYTFY/follow`


`POST /sites/{site-id}/drive/items/{item-id}/follow`

Here in the above syntax there is no option of drives . Hence I can only follow documents of shared library
**site id** : qa.sharepoint.com,4c3fec34-b7da-4b95-b258-33338538dc4f,733489ef-85df-4a46-a599-5eef9e3c45fa
**drive** : means default drive i.e shared document library of team site
**item-id**: 017LZDUZFQ3Q26RTOO6FGZYQXCYZCNYTFY


Am i correct ?
