### ISSUE TITLE
Does this call support paging?

### ISSUE THREAD

**Issue by lesterw1** [microsoftgraph/microsoft-graph-docs#4686]
The previous Azure Active Directory REST API did not support paging for Users.  Does this new Microsoft Graph API support paging for users (i.e., does it return an @odata:nextLink)? Not all APIs support paging yet.  Please document this either way.  Details on paging support are here: https://docs.microsoft.com/en-us/graph/paging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Added this sentence to the Response section: If a large user collection is returned, you can use paging in your app. the words "paging in your app" are linked to the paging article.

#please-close

**Comment by lesterw1** [comment]
Are you certain paging is supported for this collection? It hasn't been previously supported.

**Comment by peterwake** [comment]
If you call e.g. https://graph.microsoft.com/v1.0/users?$select=givenName,surname,mail&$top=3 from https://developer.microsoft.com/en-us/graph/graph-explorer?request=users you will see it does page :)

**Comment by lesterw1** [comment]
Confirmed. I do see the "@odata.nextLink" property in the response.  Thank you Peter.  

As for the documentation, I'd suggest clearly listing the graph APIs which do you (yet) support paging on the page: https://docs.microsoft.com/en-us/graph/paging.  Thank you all.
