### ISSUE TITLE
Unsupported segment type. ODataQuery: /me/scopedAdministratorOf

### ISSUE THREAD

**Issue by zabenamr** [microsoftgraph/microsoft-graph-docs#4687]
attempting to call: https://graph.microsoft-ppe.com/beta/me/scopedAdministratorOf

which returns 400:
{  
"error": {
    "code": "BadRequest",
    "message": "Unsupported segment type. ODataQuery: /users/efbebcdb-5d15-4603-98d7-2fd1531fcaec/scopedAdministratorOf",
    "innerError": {
      "request-id": "50847e8c-e176-45a2-b0d6-437044f9ead1",
      "date": "2019-05-24T18:37:28"
    }
  }
}

**Comment by Jackson-Woods** [comment]
@zabenamr Try this request without "-ppe" (graph.microsoft.com).
