### ISSUE TITLE
Add transitive expansion scenarios and link to other methods

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#4690]
The transitive* operations are for specific scenarios, and are relatively expensive.  Without clear scenarios for when these methods should be used vs some of the other more performant methods, developers will chose the wrong option.  So we should add brief scenarios and guidance + links to other methods like checkMemberGroups to ALL transitive* operations (that have alternates).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e41493-05ab-9f85-ccd8-7244303ae4ff
* Version Independent ID: 30167152-63a7-da89-573e-2ea68bd352f8
* Content: [List user transitive memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-transitivememberof?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/user-list-transitivememberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-transitivememberof.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @anchanda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
@yyuank can you please triage this request for groups

**Comment by davidmu1** [comment]
Communicated issue to engineering. No change identified for this page. Closing the issue.
