### ISSUE TITLE
Patch to update securescore control profiles is not working

### ISSUE THREAD

**Issue by msandbu** [microsoftgraph/microsoft-graph-docs#4691]
I'm trying to use the API to update secure score control profiles, using the example above.

{
  "assignedTo": "",
  "comment": "control is reviewed",
  "state": "Reviewed",
  "vendorInformation": {
    "provider": "SecureScore",
    "providerVersion": null,
    "subProvider": null,
    "vendor": "Microsoft"
  }
}

And I get this in return (using the Graph Explorer) 
{
    "error": {
        "code": "",
        "message": "Http request failed with statusCode=BadRequest",
        "innerError": {
            "request-id": "cb1eb11f-580d-4a76-b4dc-51840fb4c0e7",
            "date": "2019-05-25T16:25:03"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2c3a79-0019-6d9e-56ef-cab94a3da1d3
* Version Independent ID: 9048f03f-7295-2465-5f81-e06716e4880b
* Content: [Update secureScoreControlProfile - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/securescorecontrolprofile-update?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/securescorecontrolprofile-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/securescorecontrolprofile-update.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
Hi @msandbu , can you please provide the query you used for updating the secure score control profile? Or can you please provide a screenshot of your Graph Explorer query, request body, and response?

**Comment by chinguyen1** [comment]
If you still face the same issue, please feel free to reopen the issue. Also, we have [code samples](https://github.com/microsoftgraph/security-api-solutions/tree/master/QuickStarts) you can refer to for this Patch method.
