### ISSUE TITLE
Getting InvalidRequest as Response but the team is getting created

### ISSUE THREAD

**Issue by thesagarlee** [microsoftgraph/microsoft-graph-docs#4692]
I am following the exact steps mentioned in the doc..

I am getting this response when I send the PUT request to create the team: (Team is getting created)( I wasn't getting this error a couple of months ago)
{
    "error": {
        "code": "InvalidRequest",
        "message": "19:4608037a935d4e9395b1440570ea544f@thread.skype is not part of groupId",
        "innerError": {
            "request-id": "d03f3d90-68d8-4f50-aedf-94bf78d83f25",
            "date": "2019-05-25T17:03:45"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed58b36a-1416-fcc0-4dd7-39d2a9f48b7c
* Version Independent ID: 438b361c-d067-4027-6a7d-3988c7028837
* Content: [Creating a group with a Microsoft Teams team - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-create-group-and-team)
* Content Source: [concepts/teams-create-group-and-team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-create-group-and-team.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by frodale** [comment]
I am getting the same error using the graph service client, can you explain why this happens? Cannot find the issue anywhere, thanks!

Code: BadRequest
Message: 19:bced6a7df89648c28a27d507518b4575@thread.skype is not part of groupId
Inner error:
AdditionalData:
request-id: 954fb648-8e3b-4cc2-8925-7a6f30bfe463
date: 2020-03-19T06:52:47
ClientRequestId: 954fb648-8e3b-4cc2-8925-7a6f30bfe463
