### ISSUE TITLE
Exception thrown when SPOSite's LockState is ReadOnly

### ISSUE THREAD

**Issue by fredericklin** [microsoftgraph/microsoft-graph-docs#4693]
An O365 Group's SPOSite has been set to Read Only.  When getting a list of OneNote notebooks, I get this error:

https://graph.microsoft.com/v1.0/groups/groupid/onenote/notebooks

```json
{
    "error": {
        "code": "10001",
        "message": "An unexpected server error has occurred. Please try again later.",
        "innerError": {
            "request-id": "54a12c73-dd6b-4105-88fa-a13363e60832",
            "date": "2019-05-25T17:55:57"
        }
    }
}
```

Setting the group to Unlock resolves the issue.  Can this be documented?  Or better, can this be resolved so that I can query OneNote notebooks when the SPOSite is still locked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b24a655-9acd-760f-7e56-3c39dd57c1da
* Version Independent ID: 5f468015-c5b3-caef-ea10-92208e176898
* Content: [List notebooks - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onenote-list-notebooks?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/onenote-list-notebooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/onenote-list-notebooks.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fredericklin** [comment]
Disregard. It worked after I unlocked/locked the SPOSite.

**Comment by JeremyKelley** [comment]
Since user says to disregard, closing this issue.
