### ISSUE TITLE
Query $orderby on planner not taked into account

### ISSUE THREAD

**Issue by Kperroch** [microsoftgraph/microsoft-graph-docs#4698]
Hi everyone, I'm experiencing some issue with odata filter on the graph api.
Issue: Orderby filter doesn't seems to work on planner tasks node
[https://graph.microsoft.com/v1.0/me/planner/tasks?$orderby=dueDateTime DESC](https://graph.microsoft.com/v1.0/me/planner/tasks?$orderby=dueDateTime%20DESC) 
do return the same thin as 
[https://graph.microsoft.com/v1.0/me/planner/tasks?$orderby=dueDateTime ASC](https://graph.microsoft.com/v1.0/me/planner/tasks?$orderby=dueDateTime%20ASC) 
which is not valid.

**Comment by fsp-ge** [comment]
I'm running in to a similar issue. I would like to filter out tasks that are not complete. ($filter=percentComplete ne 100) It would appear that $orderby, $filter and $top don't work.

**Comment by Kperroch** [comment]
@fsp-ge Right as workarround I retrieve all tasks then do my filters, but it will bee much more faster with the implementation of those tools

**Comment by fsp-ge** [comment]
@Kperroch This is what I ended up doing, not very efficient though.

**Comment by Katli95** [comment]
Is there no update for this? Can we at least get confirmation that the Planner endpoint does not support filter or order?

I tried for some time today and [the official docs](https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=http) said nothing of it not being an option..

P.S. Sorry if I seem a tad displeased, but I feel that such a shortcoming should be mentioned in the official documentation or at least addressed officially so as to prevent users spending time bashing their heads against an invisible wall

P.P.S Really love the solution though, just found this to be quite irritating after an hour of attempting to debug my testing 😘

**Comment by jthake-msft** [comment]
Please can you go and request this at Microsoft Graph Uservoice.
