### ISSUE TITLE
$orderby on /me/memberOf throws exception

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-docs#47]
If you try to call `https://graph.microsoft.com/v1.0/me/memberOf?$orderby=displayName` you get the following exception:

```
{
    "error": {
        "code": "InternalServerError",
        "message": "Object reference not set to an instance of an object.",
        "innerError": {
            "request-id": "4b513104-0c8e-4fae-b752-549981f5db99",
            "date": "2015-11-27T12:01:54"
        }
    }
}
```

According to the [documentation](https://github.com/OfficeDev/microsoft-graph-docs/blob/2dc2921de053bbe25d969fd7d5dee8cdea112ece/api-reference/v1.0/api/user_list_memberof.md#optional-query-parameters) using the $orderby option should be supported.

If this is a known limitation it would be helpful if it was mentioned in the documentation.

**Comment by martellaj** [comment]
Thanks for the feedback, @waldekmastykarz!

@dkershaw10, do you know if orderBy is supported yet?

**Comment by dkershaw10** [comment]
This is not currently supported - we don't support further OData $ operators on the result of a navigation.  This is something we are working on.

**Comment by waldekmastykarz** [comment]
@dkershaw10 thank you for confirming

@martellaj how about we add this to the [documentation](https://github.com/OfficeDev/microsoft-graph-docs/blob/2dc2921de053bbe25d969fd7d5dee8cdea112ece/api-reference/v1.0/api/user_list_memberof.md) as a known limitation to avoid confusion?

**Comment by martellaj** [comment]
@waldekmastykarz, that's definitely ideal, though difficult with the size of the API and the number of different workloads that are exposed. It's on our radar though, thanks again for the feedback!

**Comment by jthake-msft** [comment]
Closing this. A decision was made not to list what is unsupported in the docs and to list what is supported.
