### ISSUE TITLE
Add a link on API, how to retrieve available plans/skus

### ISSUE THREAD

**Issue by SychevIgor** [microsoftgraph/microsoft-graph-docs#4701]
It will help us, if Microsoft provide us an article right on this page- how to retrieve via API all available plans/skus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ae95800-e9b3-0491-dc4e-759b27253e3c
* Version Independent ID: bd735181-0625-7cc9-a1ae-e085b4c89534
* Content: [assignedLicense resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/assignedlicense?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/assignedlicense.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/assignedlicense.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Fornori** [comment]
IS there any updates?

**Comment by Fornori** [comment]
@SychevIgor I found this one: https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-1.0&tabs=cs

**Comment by dkershaw10** [comment]
That API gets all the SKUs that the organization has subscribed to.  
@SychevIgor - if that is what you are looking for, great!  If you truly want an API that can tell you all the available SKUs that Microsoft offers, then that API doesn't (currently) exist.  If that's something you need please file a new suggestion/idea in [Microsoft Graph UserVoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests)
