### ISSUE TITLE
Group requirements

### ISSUE THREAD

**Issue by OlliePythagoras** [microsoftgraph/microsoft-graph-docs#4703]
It may be worth adding (to point 2) that the group required is a mail-enabled security group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0302f7b1-e754-fd0a-4a8a-057ed5deaa9a
* Version Independent ID: f819a46b-23d4-65c4-fc12-5b558b81511a
* Content: [Get started with Microsoft Graph data connect - Microsoft Graph](https://docs.microsoft.com/en-us/graph/data-connect-get-started#feedback)
* Content Source: [concepts/data-connect-get-started.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/data-connect-get-started.md)
* Product: **data-connect**
* Technology: **microsoft-graph**
* GitHub Login: @ajacks-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tlenig** [comment]
Thanks for reaching out @OlliePythagoras and apologies for the extended delay in response. This issue should be resolved, please do re-open if you would like to see additional changes too.
