### ISSUE TITLE
create user articles should clarify when to use this vs invite API

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/microsoft-graph-docs#4705]
In the Create user articles, there is no mention that this API doesn’t create external users, even though external users are users (they’re returned by GET etc). If creating an external user is only possible via the invite API, should there be some link from these article to the corresponding invite API articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 557de097-e035-bfee-1c1a-fcd9a1713fd8
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abazanov** [comment]
@markwahl-msft what is the process to create a "consumer user account" as per this link https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet#create-consumer-user-accounts

**Comment by markwahl-msft** [comment]
@abazanov Please note that the article you reference is for managing in a B2C directory, and that article states "You must use the Azure AD Graph API to manage users in an Azure AD B2C directory. This is different from the Microsoft Graph API.".

**Comment by abazanov** [comment]
@markwahl-msft thank you for coming back to me. So is that the recommended way of adding consumer user accounts programmatically? I seem to be of the impression that the `Azure AD Graph API` is not receiving a great deal of attention anymore and that Microsoft is encouraging developers to move away from it to the `Microsoft Graph API`. Am I correct? I don't want to develop against an API which will be discontinued soon. Hence I was asking how to add consumer user accounts via the `Microsoft Graph API`.
