### ISSUE TITLE
Missing wns.connect - allows connecting to windows notification service

### ISSUE THREAD

**Issue by butchmarshall** [microsoftgraph/microsoft-graph-docs#4709]
I'm attempting to configure my application permissions but am missing the wns.connect permission.

This page does not indicate where I'm supposed to find it or what conditions need to be met in order for it to be available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf53c20-0e14-5ad8-5522-6dd2036ced91
* Version Independent ID: 62a97f3a-1e7d-ba70-e827-ad2a18ded879
* Content: [Manage app registration and API permission for Microsoft Graph notifications - Microsoft Graph](https://docs.microsoft.com/en-us/graph/notifications-integration-app-registration)
* Content Source: [concepts/notifications-integration-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/notifications-integration-app-registration.md)
* Product: **notifications**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by merzink** [comment]
Quick update: Instructions on this page were updated to reflect the simplified permission setup.
