### ISSUE TITLE
ISV?

### ISSUE THREAD

**Issue by damienestewart** [microsoftgraph/microsoft-graph-docs#4711]
Hi, I'm just wondering what an ISV is (mentioned in "Build applications that are aware of class roster")?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e97afdd-1b9c-8b8d-482f-60ad8993f3b3
* Version Independent ID: 46ac5a0d-ed66-9a7a-a045-bf8b165d3ed8
* Content: [Education API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/education-concept-overview#build-applications-that-are-aware-of-class-roster)
* Content Source: [concepts/education-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/education-concept-overview.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
Thanks for your question. Spelled out the acronym as "independent software vendor" on first mention in PR #4714.
