### ISSUE TITLE
scope can be users?

### ISSUE THREAD

**Issue by jeanlucdemers** [microsoftgraph/microsoft-graph-docs#4715]
&lt;
When I use the query:
https://graph.microsoft.com/v1.0/sites/xxxxxxxxxx/lists/xxxxx/items?$expand=driveItem($expand=permissions;$select=id,name,webUrl,permissions)&$select=id,driveItem

The result contains:
...
{
                        "id": "4bc98a01-99c9-42c9-a2e1-4f589fddc5d6",
                        "roles": [
                            "write"
                        ],
                        "inheritedFrom": {},
                        "link": {
                            "scope": "users",
                            "type": "edit",
                            "webUrl": "https://m365x287284.sharepoint.com/:f:/s/test3/ErPlPNegICxMoa0Jma20jGABtVvB1AcBeCy1p5zSCPAFZw"
                        }
                    },
...

Is it the same as "organisation" or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4533e3f-a2b7-8147-30f5-ae775811ad1c
* Version Independent ID: 08e5e0cd-3bf5-c978-6077-1c45c560dd0d
* Content: [SharingLink - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/sharinglink?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/sharinglink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/sharinglink.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by kevklam** [comment]
'users' refers to the "specific people" sharing link option. It is documented in the 'beta' docs, we missed documenting it in the v1.0 documentation.

**Comment by lramosvea** [comment]
Closing as this seems to be resolved
