### ISSUE TITLE
No documentation of API found for Office 365 video REST API in MS Graph.

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/microsoft-graph-docs#4716]
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/video-rest-operations.
From above link it moved to this link https://docs.microsoft.com/en-us/graph/overview#feedback.

I want to know does it possible that using REST API we can download video in Office 365 video. ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview#feedback)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
No unfortunately not. we are currently in early stages of Microsoft Stream API for Microsoft Graph as this is the strategic future of video in Microsoft 365.
