### ISSUE TITLE
Download attachments with contentType="reference"

### ISSUE THREAD

**Issue by phallguy** [microsoftgraph/microsoft-graph-docs#4723]
How can we download the actual contents of the attachment? Navigating to the address in `contentUrl` results in a 403 forbidden response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6c8af40-4558-336d-e5f9-cff107e0b8bc
* Version Independent ID: 445506cc-9392-e0d5-e4cb-35a1da9e0dd7
* Content: [chatMessageAttachment resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessageattachment?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessageattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessageattachment.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AlexanderDorofeev** [comment]
You can download it from group drive /groups/{team-id}/drive/root:/{item-path}:/content 
Also you should ensure that your app has Files.Read.All permission

**Comment by kaaloo** [comment]
Thanks for this ! I ended up opening an issue about this here:

https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/200

There is a small bit of code there as a workaround to generate the above url when dealing with an attachment in a team chat and also for a one to one chat.
