### ISSUE TITLE
The scopes should be part of the documentation

### ISSUE THREAD

**Issue by chanmmn** [microsoftgraph/microsoft-graph-docs#4725]
I believe the scope (the line below) need to be part of the sample code in this documentation..
var scopes = new List&lt;string&gt;() { "User.ReadBasic.All" }.ToArray();
Else the code just impossible to run. 

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@Lauragra @angelgolfer-ms Who worked on the sample code generation?  Looks like the ask is to have an auth snippet that ALSO contains the least privileged require permission.

**Comment by Lauragra** [comment]
Adding @darrelmiller .

**Comment by darrelmiller** [comment]
We have not been able to do that up until now because the Permissions are not in the Graph metadata.  It should be possible to add this in the near future.
