### ISSUE TITLE
Create a new chat (user to user) message via api/sdk 

### ISSUE THREAD

**Issue by motim6026** [microsoftgraph/microsoft-graph-docs#4734]
i want to send message to user in chat (not in chanell) using api\sdk
i can see that i can only get message but not create a new message using api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cdc4c00-eec5-0591-c8e3-b62b878a6827
* Version Independent ID: 1ce189ae-83b1-527c-19d4-f56a51c877ee
* Content: [chat resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chat.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by SHAGGAR** [comment]
Its weird that this hasn't been added when its already available for channels.  Maybe they don't want us making 3rd party chat clients.

**Comment by ljr55555** [comment]
Upvote the [request on the Graph API UserVoice site](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/37802836-add-support-for-creating-chat-messages-on-the-user).

**Comment by nkramer** [comment]
We would like to support this someday but have only so many hours in the day. Please track feature requests on UserVoice. Thanks.

**Comment by dipakboyed** [comment]
Is there a UserVoice link we can upvote?
