### ISSUE TITLE
Add a note about unsupported $select properties

### ISSUE THREAD

**Issue by mwiedemeyer** [microsoftgraph/microsoft-graph-docs#4746]
It is stated, that $select can be used "as in any GET request".
However it seems, that in the `delta` endpoint, some properties are not supported.
For example:
- skills
- aboutMe 

I get the following error:
`Invalid Request: $select is not supported for these properties`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8f0b0d-c0f7-7774-d5fb-5df3c09dc83a
* Version Independent ID: f23af4a1-bf3c-2ef1-a94f-79be31ea6618
* Content: [user: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/user-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delta.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by blyw** [comment]
Can we get a list of supported properties? Trial and error is not a feasible solution!

**Comment by krbain** [comment]
This issue has been reviewed and will be addressed by a doc update.
