### ISSUE TITLE
Graph v1.0 optional $ sign is inconsistent

### ISSUE THREAD

**Issue by madansr7** [microsoftgraph/microsoft-graph-docs#4750]
Issue:Graph v1.0 optional $ sign is inconsistent. 

Article: The current query parameter document says that $sign is optional for query parameters in v1.0 and beta. However, the following API call does not work if the $ sign is removed in v1.0. 
https://graph.microsoft.com/users?select=id

The `Note` in the [query parameter documentation](https://docs.microsoft.com/en-us/graph/query-parameters?toc=.%2Fref%2Ftoc.json&view=graph-rest-1.0) needs to be updated to reflect the accuracy of the feature.

**Comment by angelgolfer-ms** [comment]
Hi @madansr7 , thanks for tracking this issue. PR #4757 should make the requirement for $ in v1.0 clear now. The content update to the [query parameters](https://docs.microsoft.com/en-us/graph/query-parameters) topic should be deployed in the next day.
