### ISSUE TITLE
productKey = PKID? and orderIdentifier = ???

### ISSUE THREAD

**Issue by domcote** [microsoftgraph/microsoft-graph-docs#4753]
Looks like all properties are required. For clarity: is "productKey" = PKID?
And what are "orderIdentifier", "importId" and "hardwareIdentifier"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9947e426-056f-5183-6600-78942fc4daa7
* Version Independent ID: 81b4f72b-3d95-d41e-563f-84c7fc57007f
* Content: [Create importedWindowsAutopilotDeviceIdentity - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-importedwindowsautopilotdeviceidentity-create?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback, This shows the properties that need to be included in the import: https://docs.microsoft.com/en-us/mem/autopilot/add-devices
