### ISSUE TITLE
Getting Unknown Error when sending message

### ISSUE THREAD

**Issue by Bob1995** [microsoftgraph/microsoft-graph-docs#4760]
{
    "error": {
        "code": "UnknownError",
        "message": "404 page not found\n",
        "innerError": {
            "request-id": "d6c4edd1-271f-48f7-971d-6b8c65dbb597",
            "date": "2019-06-06T15:32:44"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
I see the call was made with groups/{id}/channels/{id}/messages instead of teams/{id}/channels/{id}/messages. Please use teams path.

**Comment by Bob1995** [comment]
I have tried with teams path getting same error.{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "1862b0ea-3ec2-4710-bb80-1b7812aaf3da",
            "date": "2019-06-07T05:22:12"
        }
    }
}

Please suggest me body for sending message

**Comment by bogdanovic** [comment]
I have the same error please not close while is this error. 

POST: https://graph.microsoft.com/beta/teams/{teamId}/channels/{channelId}/messages
RequestBody:
`
{
  "body": {
  	"contentType": "html",
    "content": "<h1>Hello World</h1>"
  }
}
`
Respond:
`{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "ac170a0b-c546-484e-ab66-093cb7e9ee09",
            "date": "2019-06-07T09:16:21"
        }
    }
}`

**Comment by RamjotSingh** [comment]
The API does not support Application Permissions. Please refer to the Permissions section above for more details. The call above was made with application permissions. Please make sure the call is made on-behalf-of user and the user is part of the team.

**Comment by Bob1995** [comment]
How can we obtain information about Permission type??

**Comment by RamjotSingh** [comment]
The table above (https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=cs#permissions) shows the permissions this API supports. Please refer to that.

**Comment by Bob1995** [comment]
{
    "error": {
        "code": "AccessDenied",
        "message": "Failed to execute Aad backend request GetUserLicensesRequest. Request Url: https://graph.windows.net/b54a6b16-7d33-439e-98bf-92c2739aa62c/users/22a07e91-0144-45be-aa8d-ec7e12e292fd/licenseDetails?api-version=1.6, Request Method: GET, Response Status Code: Unauthorized, Response Headers: ocp-aad-diagnostics-server-name: RoSyBIIaN30hAmu9SEgI7ZBNQXuy33sdsgZZFASGMzU=\r\nrequest-id: 2abdd647-8ef0-4d31-84c3-a9322c86045d\r\nclient-request-id: 3e45d100-a229-4572-b16f-c36435390ecb\r\nStrict-






I am able to post message using Graph explorer.But can't post with postman. It is showing following error 
Transport-Security: max-age=31536000; includeSubDomains\r\nDate: Mon, 17 Jun 2019 11:13:06 GMT\r\n",
        "innerError": {
            "request-id": "d61c5c32-c36e-41ec-8893-f5b1370104e1",
            "date": "2019-06-17T11:13:07"
        }
    }
}

**Comment by JacobAtchley** [comment]
> The table above (https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=cs#permissions) shows the permissions this API supports. Please refer to that.

@RamjotSingh Do you know if there are plans to add Application Permissions will be allowed? I am currently investigating sending chat messages to an MS Teams channel from a C# application. Thanks!

**Comment by menfra** [comment]
I get  unknown error when the Chatmessage has an attachment of contentType: file, application/word, image/png, except reference. I am using the sdk

```await graphClient.Teams[SelectedChannel.MyTeamId].Channels[SelectedChannel.Id].Messages.Request().AddAsync(chatMessage);```

**Comment by Raansoon** [comment]
There is now a delegated "ChannelMessage.Send" and other ChannelMessage Permissions.  Is the documentation that calls out Group.Read.All as the required permission now out of date?

**Comment by akarczag** [comment]
I'm using Delegated permissions and still getting the following error message when using a Global Admin and an account that is a member of the team:
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "a1acbb1f-e553-47da-97cd-b7f016584e9a",
      "date": "2020-03-06T22:32:36"
    }
  }
}
