### ISSUE TITLE
What permission I should have to view all the tasks of other user?

### ISSUE THREAD

**Issue by JayakumarB** [microsoftgraph/microsoft-graph-docs#4766]
The endpoint GET /users/{id}/planner/tasks is not working any user except my userid. Even though I'm member of the plan where multiple users are already there. i couldn't see tasks of my team members. i'm getting 403 error says "You do not have the required permissions to access this item."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60667-9c25-f040-1bb0-b214ad2d55cb
* Version Independent ID: e00d1752-cfad-d7d5-93a1-d4de96e8aa09
* Content: [List tasks - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/planneruser-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/planneruser-list-tasks.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by spectre-dt** [comment]
What permissions do you currently have set?

**Comment by TarkanSevilmis** [comment]
Currently, viewing tasks assigned to other people is not permitted. If the tasks are in the plans you can access, you can query the tasks in those plans to find out tasks assigned to other people.

**Comment by JayakumarB** [comment]
If that is the case, why do we have endpoint like  GET `/users/{id}/planner/tasks` to get tasks based on userid just `/me/planner/tasks` is enough. Is there any future plan to get tasks of other user based on userid?

**Comment by spectre-dt** [comment]
> Currently, viewing tasks assigned to other people is not permitted. If the tasks are in the plans you can access, you can query the tasks in those plans to find out tasks assigned to other people. From: Jayakumar Balasubramaniam <notifications@github.com> Sent: Thursday, June 6, 2019 6:32 PM To: microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com> Cc: Tarkan Sevilmis <tarkanse@microsoft.com>; Mention <mention@noreply.github.com> Subject: [microsoftgraph/microsoft-graph-docs] What permission I should have to view all the tasks of other user? (#4766) The endpoint GET /users/{id}/planner/tasks is not working any user except my userid. Even though I'm member of the plan where multiple users are already there. i couldn't see tasks of my team members. i'm getting 403 error says "You do not have the required permissions to access this item."
> […](#)
> ________________________________ Document Details ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking. * ID: 52f60667-9c25-f040-1bb0-b214ad2d55cb * Version Independent ID: e00d1752-cfad-d7d5-93a1-d4de96e8aa09 * Content: List tasks - Microsoft Graph v1.0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fplanneruser-list-tasks%3Fview%3Dgraph-rest-1.0%26tabs%3Dcs%23feedback&data=02%7C01%7Ctarkanse%40microsoft.com%7Ccb035fb027bb42ea227e08d6eae7e1fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954678981537074&sdata=eaLqnf6PXogDtts%2BaPCvXJ7H5751GnD0kVnhIMSU4Cs%3D&reserved=0> * Content Source: api-reference/v1.0/api/planneruser-list-tasks.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fblob%2Fmaster%2Fapi-reference%2Fv1.0%2Fapi%2Fplanneruser-list-tasks.md&data=02%7C01%7Ctarkanse%40microsoft.com%7Ccb035fb027bb42ea227e08d6eae7e1fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954678981547083&sdata=wzTPP8QMXmw9mFLIrZfJW673CWriLDD3G%2FcxOyx5%2BNw%3D&reserved=0> * Product: planner * Technology: microsoft-graph * GitHub Login: @TarkanSevilmis<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTarkanSevilmis&data=02%7C01%7Ctarkanse%40microsoft.com%7Ccb035fb027bb42ea227e08d6eae7e1fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954678981547083&sdata=6Xhk03412d4WoP%2BSKKG61crI2CYSRKEISXAokbw4%2Blc%3D&reserved=0> * Microsoft Alias: MSGraphDocsVteam — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fissues%2F4766%3Femail_source%3Dnotifications%26email_token%3DADY26S65AQ55XSKOEVVVJH3PZG27RA5CNFSM4HVN6T52YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GYE3SYA&data=02%7C01%7Ctarkanse%40microsoft.com%7Ccb035fb027bb42ea227e08d6eae7e1fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954678981557091&sdata=3eJtyiVdMZ7%2BzpjE8QW%2BBzrVvngsjQewInt%2FZfsRLNE%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADY26S2GK7B76OP6EZBGFHDPZG27RANCNFSM4HVN6T5Q&data=02%7C01%7Ctarkanse%40microsoft.com%7Ccb035fb027bb42ea227e08d6eae7e1fb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636954678981557091&sdata=MkavUbaVa0j53A7sxTG0vrHmseq9GrMW61BPCwNKX10%3D&reserved=0>.

Any idea on when it might be permitted?

**Comment by TarkanSevilmis** [comment]
/me is not actually a real endpoint. It is just convenience, and requests to /me are functionally handled as /users/{id of the calling user}. Allowing people read other people’s tasks require a permission model to select who can read whose tasks. This is not a scenario we’re actively looking at right now. However, it may be added in the future. It would be helpful for us to know what your scenario is to help decide if this is something that should be looked at sooner than later. You can also provide feedback and make requests here: https://planner.uservoice.com/

**Comment by JayakumarB** [comment]
I'm trying to list down the team member tasks, so thought to use Microsoft Graph. As we were able to see the tasks of a team member through planner it would be great to get the same through Microsoft Graph as well.

**Comment by TarkanSevilmis** [comment]
Are you just trying to get the tasks assigned to a user within a Plan? Planner does not have a way of showing tasks assigned to other people, anything that is assignee based is essentially a filter on the tasks within a plan. You can get the same data by reading the tasks in the plan, then filtering them on the client side.

**Comment by spectre-dt** [comment]
I'm currently using a workaround for this until they allow it.

1. Get the plan
2. Get all the buckets in that plan
3. Get all the tasks in each bucket
4. Loop through the tasks
5. Loop through the assignments and add the task to an array with that users ID
6. This should leave you with arrays of all users and their tasks

I'm currently doing this in Python/Django and it does what I need it to however this approach does have a negative impact on performance.

**Comment by TarkanSevilmis** [comment]
Step 2 is not necessary, you can directly load the tasks in a plan via “/planner/plans/<id>/tasks”. However this only returns tasks assigned to a user **within a plan**, not all tasks assigned to the user.

**Comment by JayakumarB** [comment]
Thanks for the workaround @TarkanSevilmis . But it seems time consuming process, also I must get the plan id/name as an input else I want to loop through all the plans. I'm thinking to keep it simple with just userid/username it should return the result. As we are able to see tasks of other user when we go to planner I hope Microsoft Graph Team will come with a solution for this.

**Comment by tanioskahi** [comment]
That's weird. What is the purpose of that endpoint if it only returns data if I put my own email?

As for a practical use case, as a team manager I need to retrieve the tasks of my team members in one place, instead of accessing the different "Planners" in each team. We create one Team for each Project, so team members will have tasks dispersed everywhere.

**Comment by jthake-msft** [comment]
Please provide your feedback here https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359623

**Comment by tanioskahi** [comment]
It's not a service issue. It's a bug. Microsoft is back to it's old ways of
ignoring customer feedback
