### ISSUE TITLE
Getting User Presence Availability in Microsoft Teams

### ISSUE THREAD

**Issue by dikeshkumar** [microsoftgraph/microsoft-graph-docs#4767]
Hi,
Can you provide the API to check user presence status on Microsoft Teams? To check if the user is online or away or busy or in a meeting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c59a30c-47c7-42d8-59a8-da11fa35243a
* Version Independent ID: a2b14964-5512-9183-9cc8-ad00e55e146d
* Content: [reportRoot: getTeamsUserActivityUserDetail - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivityuserdetail?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-getteamsuseractivityuserdetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rodneyjoyce** [comment]
Hmmm the Reporting APIs would not be the place for this as they aggregate up to day level.

**Comment by VinodRavichandran** [comment]
@dikeshkumar We are working on this functionality to expose it through Beta. Closing this because its not an issue.

**Comment by martinepic** [comment]
Has this option been implemented in microsoft graph api?

**Comment by cbtham** [comment]
Yeap. Here is the docs. https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta
