### ISSUE TITLE
how do i set the header in json ?

### ISSUE THREAD

**Issue by danielmanatal** [microsoftgraph/microsoft-graph-docs#4768]
Prefer: outlook.timezone="Pacific Standard Time"
Prefer:outlook.body-content-type=text"

How can i set this header in json ???, is this correct
 {"Prefer":
 'outlook.timezone="Pacific Standard Time",outlook.body-content-type="text" '
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c86813-3128-8d76-1853-fde56fb17349
* Version Independent ID: da447d8b-6f50-027e-6d6f-46636eb7294b
* Content: [List events - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-list-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-events.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by floppydisken** [comment]
You're trying to add header to the request body. Rather add it to the header. 
Which language are you using to achieve this?

**Comment by jthake-msft** [comment]
No response so closing.
