### ISSUE TITLE
Not applicable for Mail enabled security groups

### ISSUE THREAD

**Issue by bartvermeersch** [microsoftgraph/microsoft-graph-docs#4771]
The first line says: "Use this API to remove a member from an Office 365 group, a security group, or a mail-enabled security group through the members navigation property. You can remove users or other groups." 

But you can't add or remove members in mail-enabled security groups using the MS graph at this moment.
error="Unable to update the specified properties for objects that have originated within an external service."

See https://github.com/microsoftgraph/microsoft-graph-docs/issues/546 and https://github.com/microsoftgraph/microsoft-graph-docs/issues/4210 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Sentence was revised.
