### ISSUE TITLE
Calling Webhook

### ISSUE THREAD

**Issue by tpmeredith** [microsoftgraph/microsoft-graph-docs#4773]
Hi,

Is it possible to create a webhook for incoming call (VoIP) notification in teams? Teams has the beta calling in API but unclear if it is possible to create webook? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
This is being discussed over email.

**Comment by andrearivaben** [comment]
Hi Vinod, I would like to have some info on this, can you please contact me?
