### ISSUE TITLE
Example request body does not match educationUser representation example

### ISSUE THREAD

**Issue by WyattBest** [microsoftgraph/microsoft-graph-docs#4778]
This doc says, "In the request body, supply a JSON representation of an educationUser object." However, the example body does not look like the [educationUser object sample](https://docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0#json-representation). Compare
```
{
  "@odata.id":"https://graph.microsoft.com/v1.0/education/users/13015"
}
```
vs
```
{
    "id": "string",
    "accountEnabled": true,
    "assignedLicenses": [{"@odata.type": "microsoft.graph.assignedLicense"}],
    "primaryRole": "string",
    "student": {"@odata.type": "microsoft.graph.educationStudent"},
    ...
 }
```

If I put anything else in the body besides @odata.id, I get a variety of errors. Bodies that don't work:
```
{
    "@odata.id": "https://graph.microsoft.com/v1.0/education/users/7bdee050-f1ce-4306-880f-b335431a7cff",
    "primaryRole": "student"
}
```
```
{
    "@odata.id": "https://graph.microsoft.com/v1.0/education/users/7bdee050-f1ce-4306-880f-b335431a7cff",
    "@odata.primaryRole": "student"
}
```
```
{
    "id": "7bdee050-f1ce-4306-880f-b335431a7cff",
    "primaryRole": "student"
}
```

Is this a documentation issue, or am I just confused?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b917e08c-cf1b-6efe-43f3-1351469c98f8
* Version Independent ID: bfed9616-483e-fdd4-7c52-f5ffc43d51bf
* Content: [Add a student - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationclass-post-members?view=graph-rest-1.0&tabs=javascript)
* Content Source: [api-reference/v1.0/api/educationclass-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/educationclass-post-members.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bendodge-xwis** [comment]
I just realized that `primaryRole` has nothing to do with the individual class. However, I am still confused about whether or not this request body will actually accept "a JSON representation of an educationUser object."

**Comment by mlafleur** [comment]
It doesn't take an `educationUser` object directly, it takes a _refference_ to an existing `educationUser` object.  You need to first create the `educationUser` and then add a reference to each `educationSchool` and `educationClass` you want to associate them with.
