### ISSUE TITLE
Create new chat

### ISSUE THREAD

**Issue by pf0ley** [microsoftgraph/microsoft-graph-docs#4779]
I see no way to create a new chat, EG: send a message to someone whom does not have any established chats yet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456c26fc-a47b-9f84-9d55-68cb48aad3fc
* Version Independent ID: 27b8eca1-ad6a-2881-a029-8d392c470b78
* Content: [Create chatMessage - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
As of this moment, chats cannot be creating using Microsoft Graph. It is something we are working on but don't have a timeline yet.

**Comment by simiczhang** [comment]
Post message to group chat or private chat not working

It seems post message to "/users/{id}/chats/{id}/messages" would get "UnknownError" ("request-id": "b6173842-c07a-4a2f-8089-6f3c60136fe3) , I understand this is BETA API but it seems it is still not ready?

**Comment by ganlbarone** [comment]
plus 1 to this, its not very useful not being able to initiate.

**Comment by Ravi1393Choudhary** [comment]
When we will get this feature (create a new chat)

**Comment by ganlbarone** [comment]
Maybe its worth starting a uservoice? im not sure where graph requests are captured.

**Comment by RajeshRs1** [comment]
I have raised a feature request for this in Microsoft. Please do vote for this to suggest this feature to Microsoft.
https://microsoftteams.uservoice.com/forums/913786-microsoft-teams-free/suggestions/38776681-it-would-be-awesome-l-if-there-is-an-api-functiona

**Comment by JohnGGeo** [comment]
Is there an update on this? I voted for user voice but it's really needed especially for commerical/Enterprise customers...

**Comment by menfra** [comment]
I also voted for hat issue. I hope MS provides a solution soon.
