### ISSUE TITLE
Date value mismatch

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/microsoft-graph-docs#4784]
This page mentions that the date should be in the range of past 30 days, however the API replies that a valid range is 28 days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56cbc05a-0edc-ab32-0164-c662c170a73e
* Version Independent ID: 00ea9031-ff95-f0a1-c825-462e5a40cabf
* Content: [reportRoot: getTeamsDeviceUsageUserDetail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsdeviceusageuserdetail?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/reportroot-getteamsdeviceusageuserdetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by isvargasmsft** [comment]
Hello @waldekmastykarz, 

My sincere apologies for the delays in our response. Thank you for reporting this issue. 

I am creating a PR right away to fix it. 

Kind regards,

Isaac
