### ISSUE TITLE
Problem adding SPFX app to team with Microsoft Graph

### ISSUE THREAD

**Issue by magnusdanielson** [microsoftgraph/microsoft-graph-docs#4785]
If I try to add an SPFX app to my team with instructions from above through Graph Explorer I get the following error:
User is trying to create a team entitlement for a non existent App definition

If I list apps I can see the app, so it is "existent"

POST https://graph.microsoft.com/v1.0/teams/e3d9f6f9-72c5-4c2e-bebe-5f56a469c423/installedApps
with the body:
{
  "teamsApp@odata.bind" : "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/d82353ea-4200-41d1-88d8-0238dd39bc2b"
}

If I try with any of the apps from the store, it works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34603d36-1be8-0a02-eeaf-09ffe733bd86
* Version Independent ID: ffb494cb-0954-7294-e71d-c019250b5c35
* Content: [Add app to team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-add?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/teamsappinstallation-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/teamsappinstallation-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by magnusdanielson** [comment]
You can close this. It works with below code. I guess some of it is redundent but I will clean that up tomorrow.

TeamsAppInstallation teamApp = new TeamsAppInstallation();
                teamApp.Id = "9b9a673d-31d4-4604-8ad0-cf2ca527e452";
                teamApp.AdditionalData = new Dictionary<string, object>() { { "teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/d82353ea-4200-41d1-88d8-0238dd39bc2b" } };
                teamApp.TeamsApp = new TeamsApp()
                {
                    AdditionalData = new Dictionary<string, object>() { { "teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/d82353ea-4200-41d1-88d8-0238dd39bc2b" } },
                    ExternalId = "cf9de072-f0e4-4d42-b9a8-c7dfd7579679",
                    Id = "d82353ea-4200-41d1-88d8-0238dd39bc2b",
                    DistributionMethod = TeamsAppDistributionMethod.Organization

                };
                await graphClient.Teams[team.Id].InstalledApps.Request().AddAsync(teamApp);

**Comment by BigEaseGueldi** [comment]
Hi @magnusdanielson!
Any chance you can provide more info regarding the IDs you have used? 

I'm currently struggling with the fact that each time a want to add my app, I get the following error: "Cannot create a team entitlement for a non existent App".

Thanks!
Dirk

**Comment by magnusdanielson** [comment]
Hi @BigEaseGueldi ,

I see my post is not crystal clear. Below is all you need to add an app to a team. The next step is to add the app to a tab, that is another story.

Start Microsoft Graph Explorer and send the following GET request
 https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/

It will return; id, displayName and externalId. 
I call the "id" above for "teamAppId" below.
Store that in a configuration file or similar, then run below code:

    // Lägg till appen
    var additionalData = new Dictionary<string, object>() { { "teamsApp@odata.bind", "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/" + teamAppId } };`
    TeamsAppInstallation teamApp = new TeamsAppInstallation();
    teamApp.AdditionalData = additionalData;
    await graphClient.Teams[groupId].InstalledApps.Request().AddAsync(teamApp);

**Comment by BigEaseGueldi** [comment]
Thanks @magnusdanielson - installing works, but because of [Incorrect placeholder interpretation in manifest.json for Teams tab app](https://github.com/SharePoint/sp-dev-docs/issues/3063) I'm not able to add it to a tab by using Application Permissions.

-> You can close this one (although most people that install an app to a team might want to add it to a tab somewhere, but as you said, that's another story ;-)).

**Comment by magnusdanielson** [comment]
@BigEaseGueldi I am running a webjob that creates a Group, then Team, installs the app and then creates a Tab in the team using the app. The app is a spfx webpart. It works great. Ping me if you have trouble.

**Comment by BigEaseGueldi** [comment]
@magnusdanielson I'm using Azure Functions that create a Group, then the Team on top, then configure the Team. And I'm starting this via on SPFx Web Part as well (that makes it easy to have an authenticated call to Azure). For the MS Graph operations I use an Enterprise Application that is secured via a certificate. The thing is that adding the tab works, but because of the placeholders issue I'm currently not able to "preconfigure" it in a way that it will work with the first call...

**Comment by manishmishra026** [comment]
@BigEaseGueldi. Can you please provide me the body of the post method you are using to add spfx webpart to teams tab..

**Comment by BigEaseGueldi** [comment]
This is my version. Installs the app, adds the tab, but configuration is not possible...


```
string appId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";

Dictionary<string, object> additionalData = new Dictionary<string, object>()
{
   {"teamsApp@odata.bind","https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/" + appId}
};

TeamsAppInstallation teamsAppInstallation = new TeamsAppInstallation()
{
   Id = appId,
   AdditionalData = additionalData
};

TeamsApp teamsApp = new TeamsApp()
{
   AdditionalData = additionalData,
   DisplayName = "App Display Name",
   DistributionMethod = TeamsAppDistributionMethod.Organization,
   Id = appId,
   ExternalId = "xyxyxyxyxy-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
};

teamsAppInstallation.TeamsApp = teamsApp;

try
{
   await graphClient.Teams[groupId].InstalledApps.Request(requestHeaders).AddAsync(teamsAppInstallation);
}
catch (System.Exception ex)
{
   throw new System.Exception("Error during installation of app", ex);
}

TeamsTab teamsTab = new TeamsTab()
{
   DisplayName = "Tab Display Name",
   TeamsApp = teamsApp,
   AdditionalData = additionalData
};

try
{
   await graphClient.Teams[groupId].Channels[channelId].Tabs.Request(requestHeaders).AddAsync(teamsTab);
}
catch (System.Exception ex)
{
   throw new System.Exception("Error during adding Guest user management", ex);
}

```

**Comment by manishmishra026** [comment]
@BigEaseGueldi ..thank you so much for this.. I was able to install and add the tab with the code provided above but was hoping to configure it as well..

**Comment by Chrissie** [comment]
@manishmishra026 As far as I know it is possible to configure a tab with the Graph API as well. 

You might have a look at this blog:
https://laurakokkarinen.com/cloning-teams-and-configuring-tabs-via-microsoft-graph-prelude/

Documentation: 
https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
