### ISSUE TITLE
Cannot get specific attributes with permission

### ISSUE THREAD

**Issue by kenzoohba** [microsoftgraph/microsoft-graph-docs#4786]
Providing permission below for application which login to get target attributes by C#, but cannot get attribution by Graph API for mail enabled security group.

**Permission**
 Group.Read.All, Group.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All

**Target attributes**
・allowExternalSenders
・autoSubscribeNewMembers
・hasMembersWithLicenseErrors
・isSubscribedByMail
・unseenCount

**Error code**
Inner error
) ---> Microsoft.Graph.ServiceException: Code: ErrorAccessDenied
Message: Access is denied. Check credentials and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e064c0-4789-0ec7-1e7c-c36519049ffd
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
The docs do need updating with a special note.  These properties are all mastered (behind the scenes) by the Outlook service.  Unfortunately that service (should but) does not support application permissions for Group.Read.All or Group.ReadWrite.All.  This is documented in groups known issues here:  https://docs.microsoft.com/en-us/graph/known-issues#groups. You can also add your vote to an existing feature suggestion in UserVoice https://microsoftgraph.uservoice.com

**Comment by davidmu1** [comment]
Note added.
