### ISSUE TITLE
Get List SP for one user

### ISSUE THREAD

**Issue by adhatahir** [microsoftgraph/microsoft-graph-docs#4787]
What is the {Id} that I have to put here? 
I'm trying to get a list of serviceplan for one user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95303edc-e6d7-7879-92e6-3766cc97cda7
* Version Independent ID: 28be3d91-d1de-6dc2-f4d9-05436681b162
* Content: [Get subscribedSku - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscribedsku-get?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/subscribedsku-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscribedsku-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@adhatahir If you are trying to get the list of service plans for one use, I would recommend using the `licenseDetails` API:  https://docs.microsoft.com/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=cs.  If this is what you are looking for, please close this.
@davidmu1 This kind of question might indicate that we need some uber topic on subscriptions, licenses and service plans.

**Comment by davidmu1** [comment]
Created workitem https://identitydivision.visualstudio.com/Technical%20Content/_queries/edit/742298 to cover the documentation request.
