### ISSUE TITLE
List conversationMembers takes 10+ seconds

### ISSUE THREAD

**Issue by simiczhang** [microsoftgraph/microsoft-graph-docs#4788]
And this is only for a private chat with only two members, is this slowness expected behavior (for a beta API) or unexpected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c0f5d6-3a9f-3818-d049-314aa8ec7b93
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta&tabs=cs)
* Content Source: [api-reference/beta/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by simiczhang** [comment]
Any update?

**Comment by nkramer** [comment]
We haven't put a lot of effort into perf tuning or perf testing this, but this is a lot slower than we are seeing.

**Comment by Meghana-MSFT** [comment]
We tried this at our end and we are able to see the results right away without any delay. List conversationMembers is in V1.0 now.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
