### ISSUE TITLE
Taking 5+ minutes to fetch 4k contacts

### ISSUE THREAD

**Issue by ashokkumarjuly** [microsoftgraph/microsoft-graph-docs#4792]
Issue: 
We using your node package "@microsoft/microsoft-graph-client" to access Graph API from node enviroment.

Actually the purpose is to fetch the user contacts (outlook,live,office, hotmail) into our system through API, 

API "/me/contacts" by default fetching only 10 contacts per call, so in our system we iterating the API using "skip & @odata.nextLink" until all the contacts are received.
While referencing Graph API document it says, by default each request will provide 10 contacts,

So to fetching 4k contacts from my account it takes 5+ minutes.

So here there are 2 questions from my side,
1. Is there any query parameters to fetch maximum contacts in a single API request.
2. To reduce the delay in fetching huge contact list say 8k contacts, is there any other API available to reduce the time delay.

Article: Contacts API

**Comment by jthake-msft** [comment]
dupe #4798
