### ISSUE TITLE
Error in the app id for websites

### ISSUE THREAD

**Issue by TheBluLion** [microsoftgraph/microsoft-graph-docs#4793]
Using the beta endpoint, the app id for websites is
microsoft.teamspace.tab.web (no com. prefix)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#feedback)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
"com.microsoft.teamspace.tab.web" is definitely supported. We have a couple cases where the same app has more than one id for legacy reasons, this may be one of them.
