### ISSUE TITLE
The Assign Owner doesnt seem to work

### ISSUE THREAD

**Issue by whytoe** [microsoftgraph/microsoft-graph-docs#4794]
Unable to assign owner 400 Error received
{
  "directoryObject": {
     "id" : "guid-of-user"
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e5100e9-69ed-9b9b-6566-0a094daae0ae
* Version Independent ID: d20191f3-e896-da5b-a280-7c3ff673d3e7
* Content: [Create owner - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-owners?view=graph-rest-beta&tabs=javascript#example)
* Content Source: [api-reference/beta/api/application-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-owners.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Updated the request body.

**Comment by huajunzhao** [comment]
Hi, What kind of permission should I set?

I'm hitting the error like:

{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Insufficient privileges to complete the operation.",
        "innerError": {
            "request-id": "f85ec48c-ef75-4123-89f7-697037c37a7e",
            "date": "2019-09-23T07:26:40"
        }
    }
}
