### ISSUE TITLE
More filter examples

### ISSUE THREAD

**Issue by cconrado** [microsoftgraph/microsoft-graph-docs#4796]
can we get more examples using the filter option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637c0260-f07d-b6d6-29ff-c21153daf742
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&tabs=cs)
* Content Source: [api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/signin-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
There is already a table containing supported parameters for the filter option, what other information would you like to see here?

**Comment by cconrado** [comment]
@Jackson-Woods have an example that combines a couple attributes like something complex. So we know the proper structure.

**Comment by GeneCupstid** [comment]
I was banging my head against the wall on this too.  The documentation here is lacking, without a doubt.  There should be examples of how multiple filters work together.  

Many tries later, and it looks like this works.  

```
https://graph.microsoft.com/v1.0/auditLogs/signIns?&$filter=userPrincipalName eq 'user@domain.com'&$top=1
```

So if the first parameter is `filter`, it needs an `&` before it, but `top` and `skipToken` don't?

**Comment by anwarmahmood1** [comment]
Microsoft have announced that Teams on Android 4.4 will stop working.  The Message Center announcement tells me I have Android 4.4 devices using Teams.

I expect this is the report to use.

The web page says I can use deviceDetail/operatingSystem with eq

Hence I need to query...

deviceDetail/operatingSystem eq Android

How on _earth_ do I even do this?  You should provide an example ASAP!

**Comment by davidmu1** [comment]
Thank you for your feedback. Your request for more examples has been communicated to the engineering team.  You could possibly ask your question at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*).  No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
