### ISSUE TITLE
Unknown error when sending a message using beta/teams/{id}/channels/{id}/messages

### ISSUE THREAD

**Issue by envite1** [microsoftgraph/microsoft-graph-docs#4797]
Got the following error when trying to send a message using Global Admin credentials to a teams where the User and the Global Admin is part of it using /beta/teams/{id}/channels/{id}/messages api.

{
    error:
    { 
        code: 'UnknownError',
        message: '',
        innerError:
            { 
                'request-id': 'cdb860e4-4611-4ea1-8411-890d3d73cb05',
                date: '2019-06-10T14:17:13'
            } 
    }
}
The same API with the same credential worked good few days before. The mentioned error is also not helpful to identify the issue.

Is there anything changed on the beta api and how to identify the root cause of this issue ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Are you still seeing this error? I investigated and it looks like a temporary thing where the request timed out. If you continue to see this error please send the request Ids and I look further.

**Comment by pythonpsycho1337** [comment]
I am also having the exact same problem. The problem seems to be related to the token. When calling the api with a work account token it executes successfully. However, when calling the api with the exact same request except for using our application's token instead of the work account token, it fails with this error.

**Comment by envite1** [comment]
@RamjotSingh If that is a request time out issue a simple re-try would help ?

**Comment by RamjotSingh** [comment]
@pythonpsycho1337 - As the permission table above notes, Application only context is not supported on this API at the moment.
@envite1 - Yes

**Comment by ssudheerk99** [comment]
@RamjotSingh can we expect to support  in Application only context  in near future ?
if yes, what can be the ETA

**Comment by jmcadams-r7** [comment]
So wait, I've given my application both Application and Directory permissions with Group.ReadWrite.All and Directory.ReadWrite.All I'm still seeing the above error. Is there something else to this?

**Comment by tchay99** [comment]
Please vote on this: https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40298410-ability-to-query-channel-message-timestamps-via-ms
