### ISSUE TITLE
Huge Delay in fetching the contacts from O365 account through Graph API

### ISSUE THREAD

**Issue by Harishiv** [microsoftgraph/microsoft-graph-docs#4798]
Issue: 

Hi,

We using your node package "@microsoft/microsoft-graph-client" to access Graph API from node environment.

Actually the purpose is to fetch the user contacts (outlook,live,office, hotmail) into our system through API, 

API "/me/contacts" by default fetching only 10 contacts per call, so in our system we iterating the API using "skip & @odata.nextLink" until all the contacts are received.
While referencing your API document it says  API request will default provide 10 contacts,

So while fetching 4k contacts from my account it takes 5+ minutes.

So here there are 2 questions from our side,
1. Is there any query options to fetch maximum contacts in API.
2. To reduce the delay in fetching huge contact list say 8k contacts, is there any other API available to reduce the time delay.

We are in urgent need to get this issues resolved, pls do the needful.

Article:

**Comment by PeterChencha** [comment]
Hello @Harishiv thanks for reaching out. To query maximum contacts use $top parameter, currently $top parameter can handle max value of 1000 in one go. At the moment we do not have another API, but we'll be investigating the delay.
