### ISSUE TITLE
How long are deltas kept, and how to manage their life cycle

### ISSUE THREAD

**Issue by pontusvision** [microsoftgraph/microsoft-graph-docs#4803]
Is there an expiry date on deltas; if so, what is it?  
How are deltas managed (e.g. how would someone delete or reset a delta link)?
How many parallel deltas can there be?  Are they tied to the credentials of the account that called the API, or is there another mechanism to manage them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab355c92-69ff-7b13-964a-9c3bc495e417
* Version Independent ID: 158fb540-d830-19fb-9c76-9db9a78c32fe
* Content: [Get incremental changes to messages in a folder - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-messages#feedback)
* Content Source: [concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-messages.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ashoksubedi1** [comment]
I had the same questions as you so I decided to manually check my self. Group and Users deltas did not expire even after a month but planner plan deltas and messages delta were expiring within a week. Does anybody know what is the format of the {value } DateTime on the filter query of the delta messages above?

**Comment by baywet** [comment]
#4317 is a very similar question. Closing this one to centralize.
