### ISSUE TITLE
Why is clientState null when listing subscriptions

### ISSUE THREAD

**Issue by HenryHall** [microsoftgraph/microsoft-graph-docs#4807]
When listing subscriptions, the clientState property for each subscription is null.  However, it is not mentioned on this page, except  obscurely in the example response.  If this is the intended behavior, this page should highlight this fact and discuss the reasoning.  If one can get the clientState from querying individual subscriptions, why not when listing them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c121424-d0a2-017c-e40d-3552ea66915c
* Version Independent ID: 999939fe-62c4-e17c-e0b6-d46ef100ecb5
* Content: [List subscriptions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-list.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chassq** [comment]
Any way someone can answer this question?

**Comment by venkateshchepuru** [comment]
Client State is not set for the List Subscription on purpose by design, because subscription collections could be listed by say some other user  (example tenant admin using Subscription.Read.All). It is not desirable to share this Client state information through the Listing API for that user who is not the creator of the subscription.

**Comment by hi1uo** [comment]
Why I kept getting Error - "message": "Get Subscriptions list is not supported for the API version 1.0.",

**Comment by chassq** [comment]
Hey @venkateshchepuru. This does not seem reasonable. The fact is that if I wanted I can go through and GET any one of the subscriptions I list currently. The only thing that not having the Client State in the LIST accomplishes is making us do yet another query to Graph and causes Graph to fulfill yet another query. Does this not seem wasteful to both parties? Client State is my correlation id and I, as a developer , should have the access to do with it as I please. If Client State is trying to be used as some security mechanism then it is not an especially good one.

**Comment by chassq** [comment]
Per @piotrci in #5248 sounds like ClientState will be removed.

> Hi @chassq ,
> 
> We plan to remove clientState from any responses, GET or list. for this reason we will not be adding it to the list response.
> 
> We will be communicating this breaking change in the future - in the meantime we recommend you adjust your app code to not rely on the clientState property being returned at all.
> 
> Thank you.

While this is probably a good thing from a security stand point overall, as client state is probably not a great security option in its current usage, we still need a good correlation id so we can optionally assign an internal id (e.g. Guid) to a subscription in Graph.

**Comment by chassq** [comment]
Per comments by @piotrci in #5248 that indicate ClientState will be removed I went back and reviewed our code. For sure this change will break our code but also will remove the ONLY way we have currently (v1.0 and beta) to correlate subscriptions. So a few added comments to please consider before removing ClientState:

1) Please provide a link to track when this change may come so we can better coordinate on our end. This breaks all current usage for v1.0 and Beta APIs.
2) As requested above please provide another way to correlate subscriptions. Please let us know this well ahead of time so we have time to react. Again provide a link to track this.
3)  Consider keeping ClientState as a correlation value so as not to break all the folks currently using it. But instead just deprecate its usage as a kind of security measure.

Thank you!

**Comment by baywet** [comment]
Hi everyone!
I just authored PR #7012 to document the fact the clientState is not returned.
As for your question, you should keep tracks of the subscription Id for all subscription management operations. The client state is a way to correlate the source of a notification but should not be used to manage the subscription itself.
