### ISSUE TITLE
Possible resource values are unclear

### ISSUE THREAD

**Issue by gabelimon** [microsoftgraph/microsoft-graph-docs#4808]
Please clarify specific resource names and modifiers. I've been trying all day to subscribe both Calendar changes (calendars added, removed, etc), and Calendar Event changes (events added, events deleted, etc.).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe0590e-070b-cf56-cbc7-1dcb8a266380
* Version Independent ID: 2d912536-afc5-60f1-e381-2eef892cbded
* Content: [subscription resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/subscription.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by gabelimon** [comment]
@piotrci can I please get an update on this? My team is critically blocked on this issue.

**Comment by sammym1982** [comment]
Agree here. @piotrci any comments referring doc?

**Comment by piotrci** [comment]
The resource paths are the same as when using GET APIs in Microsoft Graph. However, not all expressions are supported. Please have a look at the below article listing what is supported - if you would like to see more detailed information, please re-open the issue. Thanks!
https://docs.microsoft.com/en-us/graph/webhooks?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#processing-the-notification

**Comment by sshresthareach** [comment]
Hi,
I went back and tested different types of resources with a personal account and nothing seems to work (looks like support for business OneDrive is not implemented yet. Below is the list of resource path format I tried.

```
/drives/{drive-id}/root/{path-to-file}
/drives/{drive-id}/root/{path-to-folder}
/drives/{drive-id}/items/{item-id}
drive/items/{item-id}
me/drive/root/{path-to-file/path-to-folder}
/drive/root/{path-to-file/path-to-folder}
```

None of them work. They all return the error below:
`resource '*' is not supported.
`
The only resource route that worked is me/drive/root.

Could you please provide me with a link that shows how to give path to a resource that is not root folder?

**Comment by gabelimon** [comment]
Please reopen the issue

**Comment by sammym1982** [comment]
I agree here. The documentation has to be explicitly edited to exact list of resources and scenarios supported.
