### ISSUE TITLE
How can i get users at any specified page?

### ISSUE THREAD

**Issue by rick-hayek** [microsoftgraph/microsoft-graph-docs#4811]
say I have 50 users in my organization, and every page shows only 5 users. Then how can I get the users at the fifth page?

if using the @odata.nextLink, I need to send 5 requests. it is insane.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/paging#feedback)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Currently the directory APIs in Microsoft Graph don't support skip capability, so you will need to page through each page. If this is important for you, please file a new suggestion at microsoftgraph.uservoice.com.
