### ISSUE TITLE
This api endpoint doesnt return third party apps

### ISSUE THREAD

**Issue by ganlbarone** [microsoftgraph/microsoft-graph-docs#4817]
Issue: This endpoint does not return third party apps registered in azure AD. We have roughly 400 apps, many of which were added by users. This endpoint only returns apps that we created directly in the tenant, it isnt returning anything added via thirdparty apps.

Article:https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-beta&tabs=cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6cedaa-9bc6-d29e-9bf1-bd865075869c
* Version Independent ID: 05d7f4b4-d564-1ce7-d676-ca8b433f763d
* Content: [List applications - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
For those use https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta.

A service principal represents an instance of an application that is acquired by a user/admin (generally through the consent operation).  Please see https://docs.microsoft.com/en-us/azure/active-directory/develop/app-objects-and-service-principals for an explanation
