### ISSUE TITLE
Table row deletion documentation inaccurate?

### ISSUE THREAD

**Issue by mmajis** [microsoftgraph/microsoft-graph-docs#4818]
The documentation seems inaccurate for table row deletion. I'm trying to delete a table row with this kind of request:

```
POST /beta/drives/{id}/items/{id}/workbook/tables/{name}/rows/0/delete HTTP/1.1" 400
```

Getting this error:
```
{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'delete'.",
    "innerError": {
      "request-id": "c3d635bc-b29f-4e19-aabd-94bc4ea21a22",
      "date": "2019-06-12T09:41:35"
    }
  }
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d820d5-0956-32bc-649d-bca00c4ce54c
* Version Independent ID: 3bbd3aea-07c8-ecd0-5f54-9231da7a64cd
* Content: [TableRow: delete - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/tablerow-delete?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/tablerow-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/tablerow-delete.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmajis** [comment]
Looks like this page has a different URL for deleting table rows: https://docs.microsoft.com/en-us/graph/api/resources/excel?view=graph-rest-beta#delete-table-row

That one seems to work.

**Comment by lramosvea** [comment]
Closing this issue as the doc has been updated
