### ISSUE TITLE
fieldValueSet underlines Color and Quantity in Visual Studio .Net console project

### ISSUE THREAD

**Issue by kyza222** [microsoftgraph/microsoft-graph-docs#4821]
Can not make this to work as the Color and Quantity is underlined straight away as I put it into my project.
Could not find any documentation for FieldValueSet.
Help please :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4e338a-772e-0fc8-cff2-14d5a2f0d173
* Version Independent ID: 01362b8b-5f0b-4a40-d21f-0d27012c7311
* Content: [Update listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/listitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by kyza222** [comment]
This did the trick.
var fieldValueSet = new FieldValueSet();
fieldValueSet.AdditionalData = new Dictionary<string, object>();
fieldValueSet.AdditionalData.Add("ColumnName@odata.type", "Edm.String");
fieldValueSet.AdditionalData.Add("ColumnName", "DesiredValue");

await graphServiceClient.Sites["xyz.sharepoint.com:/sites/ITOddeleni:"].Lists["TeamsRequest"].Items[item.Id].Fields
                                    .Request()
                                    .UpdateAsync(fieldValueSet);

**Comment by jthake-msft** [comment]
could you take a look at this one?

**Comment by andrueastman** [comment]
Thanks for pointing this out. I will investigate and resolve this.

**Comment by andrueastman** [comment]
Closing this as the snippet has been updated to fix this.
