### ISSUE TITLE
delta with `transitiveMembers`?

### ISSUE THREAD

**Issue by mrgoos** [microsoftgraph/microsoft-graph-docs#4822]
Hi, is it possible to use delta with this endpoint?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37eaad48-9559-ab5c-5b83-338f53fbbc6f
* Version Independent ID: 591556a3-d528-7f19-e03b-3bf5a67bce51
* Content: [List group transitive members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/group-list-transitivemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-transitivemembers.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @anchanda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Hi @mrgoos this isn't currently supported. If you need this, please post a new suggestion on microsoftgraph.uservoice.com.

**Comment by mrgoos** [comment]
Apparently we can just use `@odata.nextLink` for this, works well.
