### ISSUE TITLE
How do you get an access token using a cert rather than a secret?

### ISSUE THREAD

**Issue by jaffadog** [microsoftgraph/microsoft-graph-docs#4824]
If I configure my registered app with a public certificate for authentication (rather than a "client secret" / "app password") then how do I form my token request? Or does Graph not support certificate based authn?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-1.0)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@jmprieur can you suggest a link or sample for certificate-based token acquisition?

**Comment by jmprieur** [comment]
@Jackson-Woods : [dotnetcore-daemon-v2](https://github.com/azure-samples/active-directory-dotnetcore-daemon-v2) would be a good one.

**Comment by FaithOmbongi** [comment]
Thank you @jaffadog for raising your issue. To add on the feedback provided, you can definitely authenticate using the certificate name. You can find additional guidance here: https://docs.microsoft.com/en-us/graph/powershell/app-only?tabs=azure-portal#authenticate. Closing this issue.
