### ISSUE TITLE
Could not find a part of the path 'C:\path-to-app\msgraph-training-aspnetmvcapp\graph-tutorial\bin\roslyn\csc.exe'.

### ISSUE THREAD

**Issue by lauraemilyjacobsen** [microsoftgraph/microsoft-graph-docs#4829]
This is what I got upon downloading and running the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79fb959-193b-5fe5-5885-1d318ac5cacb
* Version Independent ID: 851e3f29-0eda-70a7-48a3-9fab2fa4e02d
* Content: [Microsoft Graph quick start FAQ - Microsoft Graph](https://docs.microsoft.com/en-us/graph/quick-start-faq)
* Content Source: [concepts/quick-start-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/quick-start-faq.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
Thanks for reporting this @lauraemilyjacobsen. We're tracking this in the training repository here: https://github.com/microsoftgraph/msgraph-training-aspnetmvcapp/issues/19, so I'm going to close this issue. It appears that this is an issue with Visual Studio and the Roslyn compiler used by ASP.NET (see https://github.com/dotnet/roslyn/issues/15556).

A few things that seem to fix it:

- Unload/reload the project
- Clean solution/Rebuild solution
- Upgrade Nuget packages
