### ISSUE TITLE
Incorrect Planner Tab configuration sample

### ISSUE THREAD

**Issue by advdberg** [microsoftgraph/microsoft-graph-docs#4834]
It seems like the Planner Tab has been changed to:

entityId = <planId>
contentUrl = https://tasks.office.com/&lt;tenantId&gt;/Home/PlannerFrame?page=7&planId=&lt;planId&gt;&auth_pvr=Orgid&auth_upn={upn}&mkt={locale}
websiteUrl = https://tasks.office.com/&lt;tenantId&gt;/Home/PlanViews/&lt;planId&gt;
removeUrl = https://tasks.office.com/&lt;tenantId&gt;/Home/PlannerFrame?page=13&planId=&lt;planId&gt;&auth_pvr=Orgid&auth_upn={upn}&mkt={locale}

Where
&lt;tenantId&gt; = the id (guid) of the O365 tenant
&lt;planId&gt; = the id of the Planner plan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by babakdanyal** [comment]
Below worked for me but you are right the configuration mentioned above is incorrect

contentUrl= https://tasks.office.com/{tenantName}/Home/PlannerFrame?page=7&planId={planID}
websiteUrl = https://tasks.office.com/{tenantName}/en-AU/Home/Planner#/plantaskboard?groupId={GroupID}&planId={planID}
removeUrl = https://tasks.office.com/{tenantName}/Home/PlannerFrame?page=13&planId={planID}

**Comment by ofunk** [comment]
My experience seems still to be inconsistent  to add planneer tab to teams using graph api
a) localization is missing -- so it appears all english only (de-DE)
b) websiteUrl needs a different syntax see below - else the link goes nowhere
c) appearance in teams is still not locatized 100% -- it appears partly german but not all- webview is fine

Variables used:
_planID: is the plannerID
_o365domain_isDefaul: the default Email domain worked for me as "customer domain"


{
  "displayName": "Aufgaben",
  "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/com.microsoft.teamspace.tab.planner",
  "configuration": {
    "entityId": "_planID.", 
    "contentUrl": "https://tasks.office.com/_o365_domain_isDefault/de-DE/Home/PlannerFrame?page=7&planId=&_planID", 
    "websiteUrl": "https://tasks.office.com/_o365_domain_isDefault/de-DE/Home//Planner/#/plantaskboard?groupId=&_datagroupID&planId=&_planID",
    "removeUrl": "https://tasks.office.com/_o365_domain_isDefault/de-DE/Home/PlannerFrame?page=7&planId=&_planID"
  }
}

**Comment by HunaidHanfee-MSFT** [comment]
We are looking into this and will get back to you soon.
Thanks

**Comment by HunaidHanfee-MSFT** [comment]
Documentation got updated. Configuration is not supported for planner tab. 

We are closing this issue as of now, feel free to open in case of any query.
