### ISSUE TITLE
Character Lengths of Respose Values

### ISSUE THREAD

**Issue by foxniver** [microsoftgraph/microsoft-graph-docs#4840]
Could you please list possible character or byte lengths of the response values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/signin-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dhanyahk
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@dhanyahk Can you provide this information? I can change the article if I can find the information. Thanks.

**Comment by dkershaw10** [comment]
@foxniver Can you provide more information on your ask here please? And why you need this information?

**Comment by davidmu1** [comment]
No response. Closing issue.
