### ISSUE TITLE
Specify timeout before Graph service retries notification

### ISSUE THREAD

**Issue by kabir-plod** [microsoftgraph/microsoft-graph-docs#4841]
> Send a 202 - Accepted status code in your response to Microsoft Graph. If Microsoft Graph doesn't receive a 2xx class code, it will retry the notification a number of times.

Can the documentation be updated to specify how long the graph service waits to receive a 2xx code before retrying? Same for how many times the notification will be retried if a 2xx is _not_ received.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks#feedback)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ywu321** [comment]
Hi @piotrci  wondering if there is any update on this question? We have the exact same question as @kabir-plod , thanks!

**Comment by Misiu** [comment]
Hi there, I'm also searching for that information.
What is the timeout when waiting for 202, when Graph will retry the request and how many times it will retry it.
This information is very important and should be added to the docs.
@piotrci @Jackson-Woods can we have this info added?

**Comment by piotrci** [comment]
Acknowledging the notification should be the first step your endpoint performs, before it executes any further business logic. More detail will be added to this article soon:
https://docs.microsoft.com/en-us/graph/webhooks?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#processing-the-notification
