### ISSUE TITLE
C# SDK sample code has minor issue

### ISSUE THREAD

**Issue by jimt4593** [microsoftgraph/microsoft-graph-docs#4842]
the await is missing a the Reference property:

await graphClient.Groups["{id}"].Owners["{id}"]
        .Reference
	.Request()
	.DeleteAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4e8438-09f9-b27d-ceed-559d9f142211
* Version Independent ID: dc761c5d-1357-5fdb-f2e3-fd687ef89346
* Content: [Remove owner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/group-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Thanks for pointing this out @jimt4593. @darrelmiller can you check to see if our other navigation-based APIs have the same sample code issue?

**Comment by darrelmiller** [comment]
I believe this is related to the lack of support for the $ref operator.  We will investigate /cc  @andrueastman

**Comment by andrueastman** [comment]
Closing this as it was resolved.
