### ISSUE TITLE
Why DirectorySettingTemplate doesn't support creat/update/delete operation?

### ISSUE THREAD

**Issue by cppcraze** [microsoftgraph/microsoft-graph-docs#4843]
Hi there,
This document lists DirectorySettingTemplate only supports Get, List operation, why does it not support create/update/delete operation? How will those template be created if graph doesn't support create operation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75b8f50f-7073-1299-e616-fb782f09fb2a
* Version Independent ID: a8195023-07a9-9dc8-0813-b8baadfb8942
* Content: [directorySettingTemplate resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/directorysettingtemplate?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/directorysettingtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/directorysettingtemplate.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@dkershaw10 and @krbain - It looks to me like there is no documentation change here. The article seems to cover existing functionality and the issue looks to be a feature request to be able to create templates. Can you confirm?

**Comment by davidmu1** [comment]
Closing this issue. Templates cannot currently be created.
