### ISSUE TITLE
JsonReaderException encountered while following this documentation.

### ISSUE THREAD

**Issue by Norrch2** [microsoftgraph/microsoft-graph-docs#4844]
Greetings,

When following this example, I am presented with the JsonReaderException: "Unexpected character encountered while parsing value: R. Path ", line 0, position 0.

I have verified that I have proper permissions "Report.Read" and am using the Client Authentication Flow. I have used fiddler and can see that the Graph Client is automatically redirecting and trying to use JSON to deserialize the stream which is causing this error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27aed79e-077d-941a-8de7-a1a7471fe8df
* Version Independent ID: e5770dea-769f-47dc-6c3b-12b49ca3aaf6
* Content: [reportRoot: getMailboxUsageDetail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/reportroot-getmailboxusagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/reportroot-getmailboxusagedetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by wadstromdev** [comment]
Any thoughts on when this issue might get fixed in Graph Client?

Thanks

**Comment by jthake-msft** [comment]
@andrueastman was this fixed?

**Comment by andrueastman** [comment]
This looks like it requires a fix on the sdk and is tracked with the following bug https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/32.

I will also investigate and resolve this on the snippet generator to have a working snippet present in the docs.

**Comment by henrymbuguakiarie** [comment]
Hello @andrueastman, does this issue still exist?  

You mentioned that this is a bug tracked by https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/32 which was closed about 4 days ago.

Cc: @FaithOmbongi

**Comment by andrueastman** [comment]
Closing this one for now.

With the v5 previews, one should get back a stream with the call below.

```cs
using var usageFileStream = await graphServiceClient.Reports.GetMailboxUsageDetailWithPeriod("D7").GetAsync();
```
