### ISSUE TITLE
Subscribe message event example

### ISSUE THREAD

**Issue by huberts90** [microsoftgraph/microsoft-graph-docs#4846]
Hi,

could you provide any example of subscribing message events ? 
When I create subscribtion I should get _notificationUrl_, but how can I use it ?
It should be request at intervals of time or send events via other protocol ?

**Comment by piotrci** [comment]
Please clarify your question. Please have a look at the example of setting up notifications for changes to user collection. the steps are very similar for messages
https://docs.microsoft.com/en-us/graph/webhooks?context=graph%2Fapi%2F1.0&view=graph-rest-1.0
