### ISSUE TITLE
getMemberGroups listed delegated permissions are incorrect

### ISSUE THREAD

**Issue by ahelwer** [microsoftgraph/microsoft-graph-docs#4853]
Issue: The documentation for the getMemberGroups API says that User.Read is an accepted delegated permission, but it is not.

Article: [docs](https://docs.microsoft.com/en-us/graph/api/user-getmembergroups?view=graph-rest-1.0&tabs=cs), [github](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-getmembergroups.md)

**Comment by krbain** [comment]
This issue has been address and the doc has been updated.
