### ISSUE TITLE
Invalid API Reference Link (404)

### ISSUE THREAD

**Issue by gs-snallaballi** [microsoftgraph/microsoft-graph-docs#4854]
Issue: 
The links provided for API Reference are not valid and redirects to 404 page in Github.

**Comment by Lauragra** [comment]
Hi, can you let us know where you're seeing links that result on a 404? In some cases relative links won't work in GitHub but they work on the live site: https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0. Thanks.

**Comment by jthake-msft** [comment]
Closing due to no response.
