### ISSUE TITLE
Syntax error in C# SDK snippet

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/microsoft-graph-docs#4858]
The List object does not have a property named List. The property is ListInfo

```csharp
var list = new List
{
	DisplayName = "Books",
	Columns = new List&lt;ColumnDefinition&gt;()
	{
	...
	},
	ListInfo = new ListInfo    \\ <-- s/b ListInfo, not List
	{
		Template = "genericList"
	}
};
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 986fb32a-c9aa-fbad-12b2-30eef3d9f7b1
* Version Independent ID: 722992d5-18ee-5499-b2a6-440ac705d40a
* Content: [Create a SharePoint List - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/list-create?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/list-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/list-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by andrueastman** [comment]
Thanks for pointing this out. I will investigate and resolve this.

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/microsoft-graph-docs/pull/8656
