### ISSUE TITLE
Conflicting Permission Name

### ISSUE THREAD

**Issue by zhusulai** [microsoftgraph/microsoft-graph-docs#4859]
In the Microsoft Graph API Reference doc, the permission to manage Azure resources in PIM is "PrivilegedAccess.ReadWrite.AzureResources". In this doc, the same permission is called "PrivilegedAccess.ReadWrite.AzureRBAC". Which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@zhusulai thanks for catching this, it looks like it should be "PrivilegedAccess.ReadWrite.AzureResources."
