### ISSUE TITLE
contains in not supported on any resources?

### ISSUE THREAD

**Issue by msimecek** [microsoftgraph/microsoft-graph-docs#4866]
Note in the filter section states that:

> The `contains` string operator is currently not supported on any Microsoft Graph resources.

I've just successfuly run this query:

```
https://graph.microsoft.com/v1.0/me/messages?$filter=contains(from/emailAddress/address, 'microsoft.com')
```

Is the note correct? That `contains` is not supported on **any** of the resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @msimecek for raising this issue. You're right and the comment has been overtaken by Microsoft Graph developments. The `contains` operator is supported in Microsoft Graph, though currently on a very limited number of resources. I've raised a PR to fix the page.
