### ISSUE TITLE
Inconsistent results

### ISSUE THREAD

**Issue by ganlbarone** [microsoftgraph/microsoft-graph-docs#4869]
So executing this request works perfectly fine and you see a list of assigned apps for the users.
GET /users/{id | userPrincipalName}/appRoleAssignments/{id}

What I am trying to do is the reverse of this. Where we grab the app, and look at the users assigned to it. Im assuming the below endpoint is supposed to do this?
GET /servicePrincipals/{id}/appRoleAssignedTo

I get good results with the first endpoint, but when taking the same app Id to an app I know I have assigned to me. I get 0 results on the second endpoint.

Looking for some guidance there. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3546a45-22f6-8f62-9f5d-26450c484572
* Version Independent ID: 0f6521fa-e1ed-ae22-9958-6a118c3518e6
* Content: [Get appRoleAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/approleassignment-get?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/approleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/approleassignment-get.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@dkershaw10 could you help? notice this page does not have a author in yaml so not sure who owns this...

**Comment by dkershaw10** [comment]
@psignoret Please add yourself to the Microsoft Graph org so we assign items to you (yes it's a double-edged sword)

**Comment by psignoret** [comment]
Apologies for the lack of response here. Answering here for future reference:

@ganlbarone is correct in his original assertion: to see all things (users, groups or service principals) which have been granted an app role for a resource app, the query is [GET /v1.0/servicePrincipals/{resource-id}/appRoleAssignedTo](https://docs.microsoft.com/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0&tabs=http), where `resource-id` is the **id** of the resource app's **servicePrincipal** object. Towards the end of 2019, there was a change in beta which would explain why it wasn't working as expected (see under "Identity and access" for in the [December 2019 change log](https://docs.microsoft.com/graph/changelog?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#december-2019).
