### ISSUE TITLE
typo in examples

### ISSUE THREAD

**Issue by pfageras** [microsoftgraph/microsoft-graph-docs#4876]
In the examples "formula" is used, but it should be "formulas"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e621007-b67f-9b43-a215-34346262a307
* Version Independent ID: 5f103903-d402-281a-aaa9-38cfe1ce9d00
* Content: [Update range - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/range-update?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/range-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/range-update.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by martyquinn** [comment]
This has still not been changed as of today. It was a bit confusing why it didn't work till I changed it to formulas.

**Comment by lumine2008** [comment]
Sorry, I just notice this issue, I transferred Graph API ownership to other PM 2 years ago, so I haven't track this thread. I just did a quick edit, please review, if further action is needed, i would loop the new PM,  
PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/7773

**Comment by grangeryy** [comment]
fixed
