### ISSUE TITLE
When using Graph to send a message which @mentions a bot, the bot never gets the message

### ISSUE THREAD

**Issue by chtartMSFT** [microsoftgraph/microsoft-graph-docs#4886]
Issue: 
I am following the process to send a message to a channel.
I include a mention of my bot.

The message shows in the channel as expected, but the bot never gets the message.

![image](https://user-images.githubusercontent.com/32363982/59880148-556cd600-937a-11e9-9e70-3735da11ebf4.png)

Article:
https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=cs

**Comment by priyankur05** [comment]
I am also facing the same issue with beta api.

Error thrown is 

()@https://statics.teams.microsoft.com/hashedjs/3.1-app.min-f892f4aa.js:923:2289 Array.forEach@<anonymous>
messageZ1 empty ClientMessageIds found for these message.ids under longpoll receive: 15797798269561message1Z1 empty ClientMessageIds found for these message.ids under longpoll receive: 157486867561 

Where as when we do 1-1 chat with bot then it is properly sending response.

()@https://statics.teams.microsoft.com/hashedjs/3.1-app.min-f892f4aa.js:923:2289 Array.forEach@<anonymous>
messageZ1 empty ClientMessageIds found for these message.ids under longpoll receive: 1574700269561message1Z1 empty ClientMessageIds found for these message.ids under longpoll receive: 1574700269561
