### ISSUE TITLE
The filter startswith option is not fully supported

### ISSUE THREAD

**Issue by narulasrinivas** [microsoftgraph/microsoft-graph-docs#4887]
Hi All,

I'm trying to select some fields and filter it on Office Groups. Because our company has a massive list of groups and it would hamper the performance if I read all columns without filter.

[https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter](url)

Below query I was trying to execute in graph explorer, but it is not working.

[https://graph.microsoft.com/v1.0/me/memberOf?$filter=startswith(displayName,T)](url)

`{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Unsupported Query.",
        "innerError": {
            "request-id": "f0d1ec98-9e3d-41ee-b15f-caa2872f462c",
            "date": "2019-06-21T09:03:39"
        }
    }
}`

Please correct the URL, If I'm doing anything wrong.

**Comment by davidmu1** [comment]
@madansr7 and @dkershaw10 - I tried the command that the customer tried and received the same error. It appears that the call is formatted correctly from this page: https://docs.microsoft.com/en-us/graph/query-parameters. Can someone confirm that filtering is not enabled for this API? Thanks.

**Comment by davidmu1** [comment]
@narulasrinivas Unfortunately, the filter parameter doesn't work with Relationships, which is what memberOf is.
