### ISSUE TITLE
Get Started link for setting up Approval Group results in 404

### ISSUE THREAD

**Issue by cveld** [microsoftgraph/microsoft-graph-docs#4888]
Get Started link for setting up Approval Group within the introduction links to:
https://docs.microsoft.com/en-us/concepts/data-connect-get-started.md 
This page request results in a 404. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05149aa1-ea7c-dab6-a389-dbb35a85a2ba
* Version Independent ID: 370c18b9-6627-687f-a437-1851b25d3c39
* Content: [Microsoft Graph data connect integration with Privileged Access Management - Microsoft Graph](https://docs.microsoft.com/en-us/graph/data-connect-pam)
* Content Source: [concepts/data-connect-pam.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/data-connect-pam.md)
* Product: **data-connect**
* Technology: **microsoft-graph**
* GitHub Login: @tlenig
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tlenig** [comment]
Thank you for raising this request @cveld! I did a pass and I believe this issue is now fixed. I will close this for now but please do let us know if you see this behavior and re-open this issue for us to fix it
