### ISSUE TITLE
Add SharePoint Online webhook support into the Microsoft Graph

### ISSUE THREAD

**Issue by dvdsmpsn** [microsoftgraph/microsoft-graph-docs#4889]
There is basic OneDrive support for webhooks/subscriptions in the Microsoft Graph, but nothing for SharePoint Online sites - which are somewhat similar. 

- Can we get updates to SharePoint sites added to webhooks/subscriptions?
- Also, folding all other SharePoint webhooks (including support for Lists) into the Microsoft Graph would be a big help.

**Is this even on the product roadmap?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f57544-01c8-95bd-d945-5c54210f1579
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TomerHeber** [comment]
AFAIK there are webhooks/subscription for the drives associated with Sharepoint sites.
What is missing is a delta API for sites (There is ones available for drive, users and groups).

Once this (delta) API becomes available for sites, it would make sense to add webhooks/subscription to monitor site changes (new, modified and deleted sites).

**Comment by vasanthtt** [comment]
@TomerHeber When we can expect webhooks subscription for site changes? Any ETA? Thanks.

**Comment by TomerHeber** [comment]
Hi @vasanthtt , I have no idea (I am not affiliated with Microsoft).

Thank you,
Tomer.
