### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by ganlbarone** [microsoftgraph/microsoft-graph-docs#4893]
I am using delegate permissions since there are no app permissions to list the messages (which is frustrating). With delegate perms I can decode the JWT token I see that my token contains the proper group.read\write permissions. However, when issuing the get I receive back 403 errors. Not entirely sure why at this point. Anyone else experience this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
This doesn't look like a docs issue from what I can tell.  If this is a coding or permissions issue please file a question on StackOverflow and tag with [microsoft-graph]

**Comment by mtucker2112** [comment]
> I am using delegate permissions since there are no app permissions to list the messages (which is frustrating). With delegate perms I can decode the JWT token I see that my token contains the proper group.read\write permissions. However, when issuing the get I receive back 403 errors. Not entirely sure why at this point. Anyone else experience this?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 701a6812-452b-7724-dc1b-635fc90736c9
> * Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
> * Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=cs#feedback)
> * Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
> * Product: **microsoft-teams**
> * Technology: **microsoft-graph**
> * GitHub Login: @nkramer
> * Microsoft Alias: **MSGraphDocsVteam**

Did you ever get past this issue or otherwise get an answer?  We also are getting a 403 when using delegate permissions.

**Comment by ganlbarone** [comment]
@mtucker2112

Very annoying but yeah. What you need to do is take whatever account you are using for delegate permissions and make it a member of the team. 

Even if that account is a ga it still needs to be a member of the team. Which is illogical, but that is how it works.
