### ISSUE TITLE
nextLink is repeatedly the same

### ISSUE THREAD

**Issue by sk-** [microsoftgraph/microsoft-graph-docs#4897]
Since a couple of days (starting around June 16, 2019), the Mail Graph APIs started to always return the same `nextLink`, which caused us to be stuck in an endless loop. Please document whether this is expected and what to do in such cases.

**Comment by srasp** [comment]
Hi, I noticed the same behaviour. Have you found any solution/workaround?

**Comment by sk-** [comment]
What we did was to repeatedly call nextLink until nextLink was either null
or the same value as before.

That seems to work fine for the endpoint we are calling (email api).

In our case the bogus nextLink returns just fine, but with an empty
response, so calling it does not break our business logic.
