### ISSUE TITLE
Example Request wrong API version

### ISSUE THREAD

**Issue by Theragus** [microsoftgraph/microsoft-graph-docs#4900]
when i execute the example request it says:
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'identityRiskEvents'.",
        "innerError": {
            "request-id": "b11d490a-284e-42f2-a264-ebfd33db879b",
            "date": "2019-06-23T20:04:58"
        }
    }
}

i think it should be API version beta?

GET https://graph.microsoft.com/beta/identityRiskEvents

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ef6d73-3f70-1132-7e5f-d43e2cecf10d
* Version Independent ID: 5925ebcb-a1da-11fa-d12f-3d7bb3cf0d19
* Content: [List identityRiskEvents - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/identityriskevent-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/identityriskevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/identityriskevent-list.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Corrected the API version.
