### ISSUE TITLE
Select not working

### ISSUE THREAD

**Issue by agatap2** [microsoftgraph/microsoft-graph-docs#4902]
I cannot select any parameter. I will always receive all of them. I need request like this:
https://graph.microsoft.com/v1.0/me/calendar/getSchedule?$selecet="scheduleId"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72df543-3deb-151b-f634-608a04881289
* Version Independent ID: 3db73371-c6ee-2add-9d51-223e3f1f82e4
* Content: [calendar: getSchedule - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/calendar-getschedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-getschedule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by varunkataria** [comment]
To my understanding, you are unable to use query parameters on POST methods like getSchedule. See: https://stackoverflow.com/questions/56657077/how-to-filter-response-with-query-parameters-on-post-methods-on-microsoft-graph/56673331#56673331
