### ISSUE TITLE
RestoreVersion API seems to be Broken.

### ISSUE THREAD

**Issue by nk-gears** [microsoftgraph/microsoft-graph-docs#4907]
@Lauragra, @jthake-msft  , I followed this article and tried the url end points to POST the restoreVersion

End Point :
https://graph.microsoft.com/v1.0/sites/{siteId}/drives/{driveId}/list/items/2244/versions/15.0/restoreVersion

Issue: 
restoreVersion API seems to be broken. When we restore a specific version using POST, its restoring the major version again and again instead of the actual version specified in the Url.

Article:
https://docs.microsoft.com/en-us/graph/api/driveitemversion-restore?view=graph-rest-1.0&tabs=cs to

**Comment by JeremyKelley** [comment]
@nk-gears Can you please ask this question here: **https://github.com/OneDrive/onedrive-api-docs**

Also, if you could provide a timestamp of when the API call was made and the request ID that comes back in the response headers that will give us more info to investigate with.  Ideally for a request to get the version you want and the request to restore.

(The template in the other project has the instructions on required info)

**Comment by nk-gears** [comment]
Thank you @JeremyKelley. I will add this issue in that repo.
