### ISSUE TITLE
Please provide a way and example for updating managed metadata columns

### ISSUE THREAD

**Issue by latonita** [microsoftgraph/microsoft-graph-docs#4911]
For now we had to fallback to Sharepoint REST API for update operations on columns with terms since we found no way to update it through Graph API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83faa62f-570d-f554-1067-f6c55d99de04
* Version Independent ID: 01362b8b-5f0b-4a40-d21f-0d27012c7311
* Content: [Update a record in a SharePoint list - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/listitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/listitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by bernhardkannemann** [comment]
We contacted the Microsoft Support and they told us that updating managed metadata columns (columns with terms / TaxonomyFields) are not supported through the graph API.

Here is the response provided by the Microsoft Support:
> The only supported way to achieve this programmatically through remote APIs is using CSOM – the right API to use is
https://docs.microsoft.com/de-de/dotnet/api/microsoft.sharepoint.client.taxonomy.taxonomyfield.setfieldvaluebyvalue
>
> If you need a code sample, allow me to share this with you:
https://github.com/SharePoint/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Extensions/TaxonomyExtensions.cs (search for ‘SetFieldValueByValue’)
>
>Any other technique of updating this kind of field is going to be unsupported.

Hope this helps someone saving time.

**Comment by latonita** [comment]
Thats pity. I would leave this ticket open untill graph api gives that possibility.

**Comment by jthake-msft** [comment]
Please vote up this user voice request https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/33421180-support-for-setting-sharepoint-managed-metadata-t

**Comment by o-utofbounds** [comment]
the method described here for the SharePoint MM (for multivalue MM in this case) seems to work on the MSFT Graph API as well (in my case on a site Columns assigned to a Doclib) 

https://sharepoint.stackexchange.com/questions/130945/is-possible-to-update-metadata-type-collectionsp-taxonomy-taxonomyfieldva

use the -1;#Term|IdForTerm; format for the value and the internal name of the MM field for the key

i guess the MSFT Graph API is just calling the matching SP API method
