### ISSUE TITLE
List owned objects - add path within Users | Groups | List owned 

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#4913]
It would make this operation much more discover-able if it was next to List memberOf in table of contents under Users | Groups. 

Can this be added that links to this same page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1713e3b5-47e0-372b-8d59-6926018fde07
* Version Independent ID: aa23772f-b67b-98b0-2902-1f06a4b2e8bd
* Content: [List ownedObjects - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-ownedobjects?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-list-ownedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-ownedobjects.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@dkershaw10  as suggested...if you're ok with it that'd be aweseome

**Comment by andrewconnell** [comment]
This doesn't appear to be working in the v1 endpoint. When submitting a request for a specific user in a group, you get the user object back. Simply adding `/ownedObjects` to the end of it returns the same thing.

Example (from a M365 demo tenant):

HTTP GET https://graph.microsoft.com/v1.0/groups/f33d703e-fc70-4651-b3ee-dfaa728c4a83/members/70c095fe-df9d-4250-867d-f298e237d681

Yields an identical response, except for the `@odata.context`, value, as this:

HTTP GET https://graph.microsoft.com/v1.0/groups/f33d703e-fc70-4651-b3ee-dfaa728c4a83/members/70c095fe-df9d-4250-867d-f298e237d681/ownedObjects

**Comment by krbain** [comment]
This issue has been reviewed and the product team has no plans to address.
