### ISSUE TITLE
incoherent instructions on how to use the body

### ISSUE THREAD

**Issue by ssteiner** [microsoftgraph/microsoft-graph-docs#4915]
Under Request Body, it says "Do not supply a request body for this method.". Then after the request, it tells you to send a JSON representation in the body. It can either be one or the other. Given the example, I'm leaning towards an empty body

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e760d3-a032-5214-1fb2-e8c811d48a57
* Version Independent ID: 2f86af0c-8ed0-16f1-674c-91c6ebfb045d
* Content: [Restore deleted item - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directory-deleteditems-restore.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by marcelriegr** [comment]
I'm also left confused by the instructions at first. But it works if you just leave the request body empty.

**Comment by davidmu1** [comment]
Removed the instruction to provide a request body.
