### ISSUE TITLE
Chat.Read.All Permission

### ISSUE THREAD

**Issue by robraytaylor** [microsoftgraph/microsoft-graph-docs#4920]
In the Chat Permissions section, it references the Chat.Read.All description which says the following;

Allows the app to read all 1:1 or group chat messages in Microsoft Teams, without a signed-in user.

If you go to the API reference for Chat (https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=cs) it says application permissions are not supported?

I have granted the permission and tried to list chats as an Application but I just get a 401 and "UnknownError".

Is this supposed to be working? Or is it coming soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#chats-permissions)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
The permission has been created in anticipation of upcoming APIs.

**Comment by pdyharshad** [comment]
Hello @nkramer. 
We want to read and write chats in Teams. Is it possible to do with current API V1.0?
I would like to thank you in advance for the considering my question and helping.

**Comment by zhipingliu32** [comment]
From May we know the current status? 

> The permission has been created in anticipation of upcoming APIs.
May we know the current status?

**Comment by zhipingliu32** [comment]
> The permission has been created in anticipation of upcoming APIs.

It means that it is not supported for now. May you share the status of upcoming support timeline?
