### ISSUE TITLE
List Message and Get Message links are swapped

### ISSUE THREAD

**Issue by pplusawork** [microsoftgraph/microsoft-graph-docs#4921]
In the header of the "List channel messages" page, the line "To get the replies for a message, call the {list message replies} or the {get message reply} API." contains links to the channel-get-messagereply and channel-list-messagereplies documentation.  

Currently, the "list message replies" link is pointing to "channel-get-messagereply", and "get message reply" is pointing to "channel-list-messagereplies".  These should be swapped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
Fixed in https://github.com/microsoftgraph/microsoft-graph-docs/commit/1e110cc1860ba242630146a62e6484a464a19089#diff-21d31992478372599edf3a8874a4f55c
