### ISSUE TITLE
Example in list mailfolders for v1 is from beta-api

### ISSUE THREAD

**Issue by Zombaya** [microsoftgraph/microsoft-graph-docs#4922]
The example shown for the mailfolders-list for version v1 is from the beta-version.

I noticed this since there is no field `wellknownName` in the v1-api, although this has been in beta since [march 2016](https://docs.microsoft.com/en-us/graph/changelog#march-2016).

My preferred solution would be to update the v1-api to also include the field `wellknownName` since it would solve an issue we are having.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad44cdb-5d58-2689-6731-f9b1f791c33f
* Version Independent ID: 5f41b59d-994a-36d8-978f-db8a738fe10d
* Content: [List mailFolders - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-mailfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mstojanovv** [comment]
Hello.

This seems right, 

I spent an hour trying to figure out why the wellKnownName property is not shown, then i noticed that the result is from the beta version, can you please update the version 1.0 to include the wellKnownName?

Also, how do I sort the folders so inbox can be on top or get the same result like the user ordered the folders like they are shown in the web outlook or desktop outlook app?

Regards.
