### ISSUE TITLE
Creating a team without Group

### ISSUE THREAD

**Issue by franzbuenaventura** [microsoftgraph/microsoft-graph-docs#4923]
No reference for creating a team without a group which should be possible since you can create a team from scratch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by adback03** [comment]
Any updates on this?

**Comment by nkramer** [comment]
There is no concept of a team that's not inside a group. The Teams UI blends both steps together (create group and create team), the V1 API doesn't, see the Creating a group with a team link at the bottom of the doc page.
