### ISSUE TITLE
Property fax not working

### ISSUE THREAD

**Issue by ufeg02** [microsoftgraph/microsoft-graph-docs#4930]
When added the property `fax` to the object `educationSchool` the POST request is rejected (`400 Bad request`). Removing the `fax` property solves the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f53fff-2202-aea5-50b5-11dcc0a5f864
* Version Independent ID: 5ecaa3ad-8c0c-2749-ea95-a8c4e973f3e9
* Content: [Create educationSchool - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationroot-post-schools?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/educationroot-post-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/educationroot-post-schools.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mlafleur** [comment]
Thank you for reporting this. There is a bug in the current schema which is mapping the `Fax` property to an invalid extension. I will open a bug report internally to get this fixed.

**Comment by mlafleur** [comment]
Fixed by #5985
