### ISSUE TITLE
Description - BadRequest

### ISSUE THREAD

**Issue by mariopenterman** [microsoftgraph/microsoft-graph-docs#4934]
An exception is thrown when the description contains a symbol: !@#$%^&*()-+=

{
  "error": {
    "code": "BadRequest",
    "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: ac66938c-22ac-4dd3-b28b-45a0de76e26c - Url: https://fef.amsub0302.manage.microsoft.com/DeviceEnrollmentFE/StatelessDeviceEnrollmentFEService/deviceManagement/windowsAutopilotDeploymentProfiles%28%278314c450-cb6d-49a3-a7f1-0743409c8f12%27%29?api-version=5019-04-17\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}",
    "innerError": {
      "request-id": "d6666666-34f4-430a-acb5-798480579165",
      "date": "2019-06-27T13:01:59"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a4cd699-a79b-c57a-a3ff-9282df143f86
* Version Independent ID: 57013606-ecf3-5e34-a18b-32e0bd3a3c53
* Content: [windowsAutopilotDeploymentProfile resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-enrollment-windowsautopilotdeploymentprofile?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-enrollment-windowsautopilotdeploymentprofile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-enrollment-windowsautopilotdeploymentprofile.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rolyon** [comment]
Hi @mariopenterman 
The code checks for unsupported characters in the payload. Does the payload include a hyphen (-)?
thanks

**Comment by triplanedave** [comment]
The OP shows a '-' character in the request body.  So, closing this as expected
