### ISSUE TITLE
Where to found {id} for the group? 

### ISSUE THREAD

**Issue by gosiaborzecka** [microsoftgraph/microsoft-graph-docs#4935]
The missing bit in documentation is how to get the {id} from the SharePoint site.
The one way is calling API to get all properties and select the groupId:
_api/web/allproperties?$select=GroupId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e064c0-4789-0ec7-1e7c-c36519049ffd
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@gosiaborzecka Can you please provide more information about this issue?

**Comment by gosiaborzecka** [comment]
I just needed to find how to get 'GroupId' and documentation don't have any information or links to another source how to get this GroupId from Office365.

**Comment by TheRealStriff** [comment]
Struggling with this.
Created a "custom" query with any groups with the name Test. WHat to query the expiration to see who was targeted.
PS C:\WINDOWS\system32> Get-AzureADMSGroupLifecyclePolicy
Get-AzureADMSGroupLifecyclePolicy : Object reference not set to an instance of an object

**Comment by nadcraker** [comment]
Is there a way to get a Group via the group name and not the Id? Most of the time we don't know the guid of the group but we know the name.
