### ISSUE TITLE
"mobilePhone" and "businessPhones" should be part of the basic information

### ISSUE THREAD

**Issue by simiczhang** [microsoftgraph/microsoft-graph-docs#4940]
Now access this API with permission "User.ReadBasic.All" would not return mobilePhone and businessPhones (both values are null) , is this by design? 

I think basic contact information like business phone should not be confidential to users in same organization, see that now I could view all my colleagues' office phone number (or even their mobile phone number) in outlook, I believe it is essential information for collaboration. See that all non-admin members of MSFT teams only have Users.ReadBasic.All permission but no User.Read.All permission  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=cs)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@simiczhang This isn't supported currently, please file a feature request on the Microsoft Graph UserVoice (https://microsoftgraph.uservoice.com/).

**Comment by simiczhang** [comment]
@Jackson-Woods I filed the feature request on the UserVoice see [here](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/38072701-include-businesephones-in-basic-profile) , please vote it if you think this request is reasonable .
