### ISSUE TITLE
"shouldSetSpoSiteReadOnlyForMembers" is confusing

### ISSUE THREAD

**Issue by mgoto-git** [microsoftgraph/microsoft-graph-docs#4944]
・Permission type:Application with "shouldSetSpoSiteReadOnlyForMembers": true returns 400 error. （without shouldSetSpoSiteReadOnlyForMembers , it works fine .)

・with Fiddler investigation , "shouldSetSpoSiteReadOnlyForMembers is not supported in app-only context" was found  in response message, and if it is true , it seems no documented

・Permission type:Delegation with "shouldSetSpoSiteReadOnlyForMembers" seems to work with only team/sites which the delegated user has owner permission.

Document's  note [Note: This API supports admin permissions. Global admins and Microsoft Teams service admins can access teams that they are not a member of.] is confusing.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20088f1-c784-991b-952d-238b1b74fba5
* Version Independent ID: 5b72dce5-7cea-d2fd-327e-dd1d8860ccd8
* Content: [Archive team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-archive?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/team-archive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-archive.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Rtoribiog** [comment]
Hello @phecdalouie  any clue on this ? i would like to use the api with app-only token but doesn´t work currently with shouldSetSpoSiteReadOnlyForMembers.

**Comment by WyattBest** [comment]
I have the same issue.

**Comment by jarleskogheim** [comment]
Do you have any update on this? Is the documentation incorrect?

**Comment by SPC-BB** [comment]
Same issue. Any update?

**Comment by plamber** [comment]
We are experiencing the same issue and are interested to see if there is a way to get this working

**Comment by Imari91** [comment]
Do we have any update here? We are still facing the same issue

**Comment by lucahost** [comment]
I'm not quite sure, if this should work using the beta version.
In 1.0 there is a hint, that using the parameter does not working using the application-context.

However in the [beta version](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/team-archive.md) there is not mention about this.

**Comment by Prasad-MSFT** [comment]
The documentation is updated stating that, `The shouldSetSpoSiteReadOnlyForMembers parameter is not supported in the application context.`

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
