### ISSUE TITLE
Optional query parameters section missing in some docs

### ISSUE THREAD

**Issue by narulasrinivas** [microsoftgraph/microsoft-graph-docs#4945]
This feedback for documentation is more of improvement of docs but not an issue.

In List directoryAudits page, [documentation ](https://docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-1.0&tabs=cs#optional-query-parameters)clearly shows which query parameters are supported for this api. 

Where as in [listitem](https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0) page, I don't find Optional query parameters section. 

If somebody can guide me or point to the direction where I can find which query parameters are supported for api. I'm happy to give hand and update in respective pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e00d6372-f1f5-58ea-0fdf-90496cc68abf
* Version Independent ID: 82a66768-cf64-369a-944f-fb6c282b340b
* Content: [listItem resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/listitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by Licantrop0** [comment]
agree, for example orderby is not supported by sharepoint list, the api doesn't throw errors, but it doesn't work and it's not written anywhere.

**Comment by FaithOmbongi** [comment]
Thank you @narulasrinivas , @Licantrop0 for raising this issue. We are working to ensure all query parameters supported per each resource's properties are clearly documented. To flag missing query parameters in a page, kindly consider opening the issue from the subject page and the appropriate team will be notified to take action. Closing this issue for now.
