### ISSUE TITLE
Returning only subset of user properties

### ISSUE THREAD

**Issue by mguoth** [microsoftgraph/microsoft-graph-docs#4946]
The properties returned by "Get delta" endpoint are the subset of properties returned by e.g. "List users" endpoint. From my tests, it looks, that properties containing null value are not included in the result, but it is not clear from documentation. In the Request 1 example, there is stated "There is no $select parameter, so a default set of properties is tracked and returned.", but it looks that this default set is different from default set of properties returned by "List users" (containing also null value properties).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8f0b0d-c0f7-7774-d5fb-5df3c09dc83a
* Version Independent ID: f23af4a1-bf3c-2ef1-a94f-79be31ea6618
* Content: [user: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delta.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @mguoth 
Thanks for pointing this out and sorry in the delay in the response.
It seems that since the documentation has been fixed. See https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delta.md#default-return-the-same-properties-as-initial-delta-request 
(3rd bullet point)
Can you confirm this addresses your concern please?

**Comment by mguoth** [comment]
Honestly that bullet points are confusing for me.

- If the property has changed, the new value is included in the response. This includes properties being set to null value.
- If the property has not changed, the old value is included in the response.
- If the property has never been set before it will not be included in the response at all.

It is not stated there, but my understanding is that 3rd bullet point is applied only to initial delta requests and 1 & 2 bullet points are applied only to follow up $deltatoken requests. Am I right?

**Comment by baywet** [comment]
What leads you to think this?
For point 3 you could have a new user, who has never set his/her preferred language for example, the user will be included in the response without the mentioned property. And this regardless to whether you're issuing an initial request on the /delta endpoint or a follow up request with a delta token.

**Comment by mguoth** [comment]
You are right, the 3rd point could be applied on all requests. It is clear now.

**Comment by baywet** [comment]
Perfect! Glad we could get to the bottom of this. Thank you for taking the time. Closing for now.
