### ISSUE TITLE
id field

### ISSUE THREAD

**Issue by robraytaylor** [microsoftgraph/microsoft-graph-docs#4947]
In the docs, the id field is listed as the "Unique id of the attachment", but we have found that the id of individual attachments can change. As in one day the id for a message attachment is xyz, and the next day it is abc. 

I am not sure if this is an ms-graph bug, but if not the documentation should be updated to mention this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6c8af40-4558-336d-e5f9-cff107e0b8bc
* Version Independent ID: 445506cc-9392-e0d5-e4cb-35a1da9e0dd7
* Content: [chatMessageAttachment resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessageattachment?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessageattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessageattachment.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sunilm-css** [comment]
Can we post with FILE attachment?
attachment = [
                {
                    "id": "74d20c7f34aa4a7fb74e2b30004247c5",
                    "contentType": "file",
                    "contentUrl": "file://tmp/abc.csv",
                    "name": "sun"
                }
        ]
        body = {
                "contentType": "html",
                "content": "<attachment id=\"74d20c7f34aa4a7fb74e2b30004247c5\"></attachment>"
        }
        payload = {
            "subject":"Test",
            "body":body,
            "attachments": attachment
        }
I keep getting 400.


<Response [400]> {'Cache-Control': 'private', 'Content-Type': 'application/json', 'request-id': '2ba8630b-b9d7-4601-afbb-...', 'client-request-id': '2ba8630b-b9d7-4601-afbb-....', 'x-ms-ags-diagnostic': '{"ServerInfo":{"DataCenter":"West US","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_34"}}', 'Strict-Transport-Security': 'max-age=31536000', 'Date': 'Mon, 11 May 2020 22:06:25 GMT', 'Content-Length': '238'}

**Comment by Meghana-MSFT** [comment]
@sunilm-css - We tried to repro this at our end following the [Send a message with file attachment in it](https://docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http#example-4-send-a-message-with-file-attachment-in-it) documentation. We were able to send a message with a file in it.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
