### ISSUE TITLE
Typo in the resource type description

### ISSUE THREAD

**Issue by TomLavenziano** [microsoftgraph/microsoft-graph-docs#4948]
The resource type description currently states:
> Represents a customer of a **bookingBsiness**.

It should be:
> Represents a customer of a **bookingBusiness**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 529be162-f830-eec3-2da6-4cbd8fb894ce
* Version Independent ID: 6e4954d8-dc55-a6fd-21df-5c337ac9a4d8
* Content: [bookingCustomer resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/bookingcustomer?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/bookingcustomer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/bookingcustomer.md)
* Product: **bookings**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dplotnikov** [comment]
@angelgolfer-ms please merge my PR for this issue

**Comment by dplotnikov** [comment]
@Lauragra please close this ticket as well
