### ISSUE TITLE
Retry logic

### ISSUE THREAD

**Issue by fume** [microsoftgraph/microsoft-graph-docs#4949]
What happens if the webhook is not reachable while notifying the event? Or in case of timeout/non successful response codes? Is there any retry logic on the change notification side? If so, please document it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fume** [comment]
please, any news on this?

thanks, regards
F

**Comment by fume** [comment]
please, any info about this?

thanks, regards

**Comment by fume** [comment]
Still waiting for an answer. Thanks

**Comment by piotrci** [comment]
There is a brief comment regarding this here: https://docs.microsoft.com/en-us/graph/webhooks?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#processing-the-notification

It will be updated with more information, soon.
