### ISSUE TITLE
Is it possible to use ARM deployment template to register a AzureAD APP?

### ISSUE THREAD

**Issue by yixue-at-symantec** [microsoftgraph/microsoft-graph-docs#4950]
r.t., I didn't find any related template or documentation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ef7d61-0334-9c13-14ca-e17f328110c6
* Version Independent ID: b59a85bb-6ac3-be82-569a-01b6295e1343
* Content: [Register your app with the Azure AD v2.0 endpoint - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-register-app-v2#feedback)
* Content Source: [concepts/auth-register-app-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-register-app-v2.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@yixue-at-symantec  This isn't support currently, please file a feature request on the Microsoft Graph UserVoice (https://microsoftgraph.uservoice.com/).
