### ISSUE TITLE
Property 'mail' is read-only and cannot be set.

### ISSUE THREAD

**Issue by ravitalveda** [microsoftgraph/microsoft-graph-docs#4957]
This example doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a885e328-2f32-cdf8-5ed8-907001c07797
* Version Independent ID: ed70a9f8-9b47-7d73-7188-c7456a4b558b
* Content: [Update group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=cs#feedback)
* Content Source: [api-reference/beta/api/group-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-update.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ravitalveda** [comment]
I need to update the mailNickname, which is not updating even after a successful patch call. Or I tried to patch a proxy address as below:
https://graph.microsoft.com/beta/groups/f4d56207-3acc-4389-8aaa-832009b0XXXX

{
    "proxyAddresses": [
        "SMTP:ravitalveda@gmail.com"
    ]
}

Gives below error:

{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "The requesting application is not authorized to set group proxy addresses.",
        "innerError": {
            "request-id": "708694d2-4cc7-42ca-9c8e-dc953d72f9c5",
            "date": "2019-07-01T07:10:36"
        }
    }
}

**Comment by Sebosek** [comment]
Hi, try this out

```
PATCH https://graph.microsoft.com/v1.0/groups/aeaeaeae-0000-0000-0000-000bbbbbbbbb

{
  "mailEnabled": true,
  "mailNickname": "updated-email-identifier"
}
```

**Comment by ravitalveda** [comment]
Above call is successful.

But is it not possible to update mail? Part of Get Group response below:

    **"mail": "YYY-XXX-1A@onmicrosoft.com",**
    "mailEnabled": true,
    "mailNickname": "updated-email-identifier",

**Comment by ken5scal** [comment]
I think we (including @ravitalveda) want to execute a request which is equivalent to the following powershell command 

Set-UnifiedGroup "group01" -PrimarySmtpAddress group01@contoso.com

**Comment by crfarnsworth** [comment]
I just ran into this same issue with a C# console application.
`var updateFields = new Group
{
    ProxyAddresses = new List<String>()
   {
    "SMTP:" + upGroup.MailNickname + "@" + tenantID
   }
};

wait graphClient.Groups[upGroup.Id]
                .Request()
                .UpdateAsync(updateFields);`

Using Visual Studio I was able to hover over the ProxyAddresses field and the description claims it is a read only field. The failed message I get is for insufficient permissions but when changing the Mail field the message is that the Field is Read-Only.

Is setting the ProxyAddresses property coming soon?

**Comment by paulsharma2000** [comment]
Any progress on this issue?. We'd like to change the domain on the groups that we create through the MS Graph API but are unable to.

**Comment by ravitalveda** [comment]
> Any progress on this issue?. We'd like to change the domain on the groups that we create through the MS Graph API but are unable to.

Appearently we can only add an alias email but we can't change or update the primary smtp 'mail'. (At least using C# and VS). Some say it is possible through powershell, but I wasn't successful in converting that command to C#.
