### ISSUE TITLE
C# SDK Sample Code Does Not Compile

### ISSUE THREAD

**Issue by nevadawilliford** [microsoftgraph/microsoft-graph-docs#4972]
I had to set the @microsoft.graph.conflictBehavior by adding it to the AdditionalData property like so. 

var driveItem = new DriveItem
            {
                Name = "New Folder",
                Folder = new Folder { },
                AdditionalData = new Dictionary&lt;string, object&gt;
                {
                    { "@microsoft.graph.conflictBehavior", "rename" }
                }
            };

Full credit to Brad for his answer on SO here. 
https://stackoverflow.com/a/45910556/186001

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9069032a-3cb9-37df-9ef5-3901aad572e0
* Version Independent ID: 37fce8f3-cd7c-2450-b1ee-95956653d179
* Content: [Create a new folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-post-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-post-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by jthake-msft** [comment]
@MIchaelMainer  are we aware of this one?

**Comment by MIchaelMainer** [comment]
We are aware of this. Instance annotations are not discoverable by the GE Snippets API. We will need to set this manually.

**Comment by MIchaelMainer** [comment]
Nevermind, this has been addressed.

https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http
