### ISSUE TITLE
Can everyone access Schools/Classes information through Graph API

### ISSUE THREAD

**Issue by prabhakarreddy1234** [microsoftgraph/microsoft-graph-docs#4973]
We have built an Education app which will be used by teachers and students. We want to get access to their `school`, `class`, `student`, `contact`, `roster` information through Graph API. Is it possible? If yes, what process should we follow to get that data?

**Comment by mlafleur** [comment]
You sure can. You can find documentation on the Graph Education APIs [here](https://docs.microsoft.com/en-us/graph/education-concept-overview).

Note that the objects are a little different than the ones you listed:
- `educationSchool`
- `educationUser` (can be a teacher, student, faculty, etc)
- `educationClass`
