### ISSUE TITLE
Add Create New team SDK code snippet

### ISSUE THREAD

**Issue by Wajeed-msft** [microsoftgraph/microsoft-graph-docs#4974]
Could you please add Create New team SDK sample code similar to [Create Group](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=cs#sdk-sample-code). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
I believe the snippet is not being created because the request example has the following metadata attached

    

I'm not sure why it was added, but if it is removed then the snippet will be generated next time we generate samples  /cc @andrueastman

**Comment by andrueastman** [comment]
Closing this as the snippet was added
