### ISSUE TITLE
How to assign tasks?

### ISSUE THREAD

**Issue by Oddleif** [microsoftgraph/microsoft-graph-docs#4982]
As AssignedTo is a read only field, how is one supposed to assign tasks to someone else through the API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312c9fd8-9544-f242-c394-35d353406648
* Version Independent ID: 53114d87-dcf5-a47f-e5c2-7a2043f7c67e
* Content: [Create outlookTask - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlookuser-post-tasks?view=graph-rest-beta&tabs=cs)
* Content Source: [api-reference/beta/api/outlookuser-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlookuser-post-tasks.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@Oddleif , I did get confirmation from a member in the corresponding product team that assignedTo is currently a read-only property, and is set in only the Outlook Win32 client by a user to delegate an Outlook task to someone else.

Perhaps you'd like to voice your need in the [Microsoft Graph User Voice ](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) site?

**Comment by Oddleif** [comment]
Thanks for clarifying. That said, we really need to see that option to delegate Outlook tasks to someone else for this API to bring any real value to us. I will add it to user voice.

**Comment by angelgolfer-ms** [comment]
Thank you, @Oddleif . I see the User Voice item you added; User Voice is the more appropriate venue for this purpose. Perhaps meanwhile you could look for a workaround?
I'm going to close this issue in Github. Thank you for your support.
