### ISSUE TITLE
POST request for compliance assignment not available

### ISSUE THREAD

**Issue by JSOnions** [microsoftgraph/microsoft-graph-docs#4984]
POST requests always return the following error:

"No OData route exists that match template ~/singleton/navigation/key/navigation with http verb POST for request /DeviceConfiguration/StatelessDeviceConfigurationFEService/deviceManagement/deviceCompliancePolicies('&lt;yourpolicyID&gt;')/assignments."

I have also opend an issue here https://github.com/microsoftgraph/microsoft-graph-docs/issues/4983 but thought that either the request should work or the documentation should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7226b7a7-d7eb-d634-a65d-a36a2f957df6
* Version Independent ID: 3f4d10d6-eb2b-b1f9-2c11-b67f2bea6975
* Content: [Create deviceCompliancePolicyAssignment - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancepolicyassignment-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-devicecompliancepolicyassignment-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-deviceconfig-devicecompliancepolicyassignment-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Yomodo** [comment]
I've found my holy grail here: https://github.com/microsoftgraph/microsoft-graph-docs/issues/2326
