### ISSUE TITLE
How to identify the user and resource via this api

### ISSUE THREAD

**Issue by wucj** [microsoftgraph/microsoft-graph-docs#4987]
From the point of view of graph api, we could use /users/{user_id} to get user's profile, and here user_id could be a user_id or resource_id. Note, those resource we could get from /findrooms/ api.
There is no attribute to recognize which is user or resource.  Is anyway approach available? 
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=cs#feedback)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@wucj In Graph beta endpoint, we have an isResourceAccount boolean. This should meet your need: https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

**Comment by wucj** [comment]
Thanks for answering, however, I tried to get them (one regular user and one resource) back, both "isResourceAccount" are null. Could any information I provide?

BTW, I call /beta/users/{email_address}
Thanks.
