### ISSUE TITLE
Graph mail API - $search filter returns Gateway timeout error

### ISSUE THREAD

**Issue by parmarpratt** [microsoftgraph/microsoft-graph-docs#4988]
I have a requirement to get emails with different filters and with the specified time range. I am using Odata query for the filter, a couple of examples are:

`https://graph.microsoft.com/v1.0/users/<Email-id>/<folder-id>/messages?$search="received>2019-07-02T07:16:39.094Z AND received<2019-07-02T07:17:39.095Z AND isRead=false"`

`https://graph.microsoft.com/v1.0/users/<Email-id>/<folder-id>/messages?$search="received>2019-07-02T07:16:39.094Z AND received<2019-07-02T07:17:39.095Z AND isRead=false AND body:testbody"`

Till the morning it was working fine, but now I am facing the 504 Gateway timeout issue

```
{
"error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
        "request-id": "f3ecaf3d-e9c2-4b99-8a01-224de9852d57",
        "date": "2019-07-02T11:38:20"
    }
}
```

After spending some time I observed there is an issue with below filter with the greater sign.

`received>2019-07-02T07:16:39.094Z`

If I remove this, then this will work fine. It works fine with the less sign as well.

`received<2019-07-02T07:17:39.095Z`

Any idea team why it stops working?

**Comment by ThisGuyOverThere** [comment]
Not sure if this is the right place, but: I'm hitting a similar issue searching Emails through the Graph-API. 

Digging into it, it's happening to my queries where there are no results to return. To test, I took the term I was searching for in one of the failed queries and sent a test mail with that term in the subject line of the email to the box I was searching. Next query returned a result immediately.

I then deleted the email, tried again, and received a 504 again.

**Comment by parmarpratt** [comment]
@ThisGuyOverThere , Thanks for digging into it. I tried to reproduce the way you said and it is giving 504 when there is no data. Till yesterday, it was working fine. If there was no data then it was returning an empty list and not the Gateway timeout issue.

**Comment by rexxmagnus** [comment]
I can confirm this bug, using a straightforward search of the inbox where I'm using a search term for which I expect to get no results returns a server error.

**Comment by lievenjanssen** [comment]
We are experiencing the same issue. This is a major bug making various functionalities in our app unusable.

**Comment by IgbyLargeman** [comment]
Same issue here. Mailbox searches which would return zero results are timing out since July 1. SO post: https://stackoverflow.com/questions/56880644/why-do-i-get-gateway-timeout-on-no-result-queries-of-office-365-shared-mailbox-v

**Comment by lievenjanssen** [comment]
Seems to be fixed

**Comment by IgbyLargeman** [comment]
Working here now too. Any word from Microsoft? It would be nice to know if it's actually been fixed, or is intermittent.

**Comment by fex1024** [comment]
Looks working now. Is this issue really fixed?

**Comment by IgbyLargeman** [comment]
Microsoft has acknowledged that the issue is fixed: https://stackoverflow.com/a/56941138/293522

"This issue has been resolved on the back end of the service and you should not be seeing this issue anymore."

**Comment by parmarpratt** [comment]
This is fixed.
