### ISSUE TITLE
supportedSingleSignOnModes value types not matching API

### ISSUE THREAD

**Issue by JefTek** [microsoftgraph/microsoft-graph-docs#4995]
The docs reference the returned types as: 
password
saml
external
oidc

However testing the API the returned values are:

password
existing
federated
oidc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 105c3b64-9092-e23a-0e05-d57136a72278
* Version Independent ID: 5ff0c889-dd39-e40d-a919-e42bf169ea7e
* Content: [applicationTemplate resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/applicationtemplate?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/applicationtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/applicationtemplate.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @luleonpla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by luleonpla** [comment]
Thanks for surfacing this. We're investigating internally and will fix the docs or the API values.

**Comment by jeevansd** [comment]
@JefTek Which app you have tested? Some apps just support the Password and LinkedSSO and so it will not return the SAML value in it. When I have tested this it is returning the correct list as         
        "oidc",
        "password",
        "saml",
        "external"

**Comment by luleonpla** [comment]
@JefTek we have fixed the API. Now, as @jeevansd  mentioned we return "oidc", "password", "saml", "external".

**Comment by jeevansd** [comment]
#please-close

**Comment by jeevansd** [comment]
#please-close
