### ISSUE TITLE
Does this page's content apply to group calendars?

### ISSUE THREAD

**Issue by nozhT** [microsoftgraph/microsoft-graph-docs#4996]
v1.0 reference &gt; Groups &gt; Calendar &gt; Get delta links to this page, but the page content does not mention groups anywhere.
Does this page's content apply to group calendars?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f65c9af5-60ee-0887-c63b-0dc338450ec3
* Version Independent ID: 2f7fef8b-4379-1847-751b-f53508ab7bae
* Content: [event: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-delta.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Event-delta is on calendarview construct; Calendarview construct is applicable only for user's calendars:
https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-1.0&tabs=http

**Comment by nozhT** [comment]
Then shouldn't the "v1.0 reference > Groups > Calendar > Get delta" link be removed from the panel on the left? The link being there is quite misleading.

**Comment by Harini84** [comment]
Updated the comment. Event delta and calendar view are supported for both user's calendars and group calendars.

Sorry for not stating it clearly initially.

**Comment by Harini84** [comment]
@angelgolfer-ms 
Kindly update the documentation
