### ISSUE TITLE
Property appliedConditionalAccessPolicy is appliedConditionalAccessPolicies

### ISSUE THREAD

**Issue by mrik23** [microsoftgraph/microsoft-graph-docs#4997]
Came to check the change in API response as it used to be "conditionalAccessPolicies" and here it gives "appliedConditionalAccessPolicy" but in fact the API response is plural "appliedConditionalAccessPolicies".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e7c8c9-8f24-f7b9-f275-59699e748383
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signin.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Corrected attribute.
