### ISSUE TITLE
Is it possible that getting resource events through delegated permission api?

### ISSUE THREAD

**Issue by wucj** [microsoftgraph/microsoft-graph-docs#4998]
If an user login and only has credential with delegated permissions, seems that that users can't get events of room resource.  I got the access deny via /users/{email_address_of_resource}. So, if we would like allow users to check when/who has reserved time slot to a specific room, how we can do? 

I tried to use access token of Application permissions, seems work but might not safe, because some of events might include some credential information that should limited for some users. 

So, is it possible to allow an user who using his own access token to get events of resource meeting room and could see limited event content? 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7064b6c8-8cb1-a8e2-c5b3-29d9107e3373
* Version Independent ID: 1720fe53-158d-0543-7f0c-5da3d900588a
* Content: [List events - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-list-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-list-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maxlund** [comment]
We are having a similar problem: https://stackoverflow.com/questions/59882182/find-out-through-microsoft-graph-if-a-room-is-bookable-by-current-user

The assumption is that if you can view events in a room, you can book that room. A way we found that lets you use view events in a certain room calendar: with an Admin account, log in to admin.microsoft.com. In the left panel, open up Exchange admin center by clicking Show All -> Exchange. Go to recipients -> resources. Double click the room you want to edit. In the new window, click "mailbox delegation". Under "Full Access", add yourself. Now go to your own outlook calendar (the one you just added). Click your initials in the top right, then "open another mailbox". Enter the email of the room calendar you just modified. Click "..." (more options) on its calendar in the left panel and click "sharing and permissions". Now add all the people you want to have API access to events in this list with "Can view all details". A (kind of) guide to changing room calendar sharing settings:
https://www.uleth.ca/information-technology/tips-tricks/managing-office-365-resource-settings-and-permissions
