### ISSUE TITLE
Supported OData Query Parameters objects

### ISSUE THREAD

**Issue by tiny-dancer** [microsoftgraph/microsoft-graph-docs#5000]
It appears manager is not expandable in this query, it would be very helpful to document supported odata objects on /users as it does not match /users/{user}.
 
https://graph.microsoft.com/beta/users?expand=manager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbc2099e-c474-a648-60bb-4520f9fa1d23
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
You're right that this should work - the bug is in our backlog.

**Comment by tiny-dancer** [comment]
@Jackson-Woods glad to hear!  As far as documenting supported objects, am I assume that is not necessary b/c they *should* all work?
