### ISSUE TITLE
Remove member example for C# is incorrect

### ISSUE THREAD

**Issue by chadliuxc** [microsoftgraph/microsoft-graph-docs#5001]
Current is 
GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var directoryObject = new DirectoryObject
{
};
await graphClient.Users["{id}"].Manager.Reference
	.Request()
	.PutAsync(directoryObject);

It should be
//remove "userid" from "groupid"
await graphClient.Groups[groupId].Members[userId].Reference.Request().DeleteAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
I think this may be a dupe.

**Comment by darrelmiller** [comment]
Closing as this is now resolved
