### ISSUE TITLE
 OData v4 specification for error responses

### ISSUE THREAD

**Issue by alex-tomin** [microsoftgraph/microsoft-graph-docs#5002]
1. OData v4 specification, does not recommend to use "innererror" for anything except exception detail in development environment
2. For more details about the error "details" property is there.

OData implementation is .Net (and Asp.Net including Core) follows and relies on the OData specification and recommendations for Error Response. 

Are there any plans to switch to and follow the specification instead of custom interpretation of innererror?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77cc3520-96d8-6aa4-1243-20b7f4d5c4cb
* Version Independent ID: 79a31ea9-d9b3-2602-e412-4959498a11c0
* Content: [Microsoft Graph error responses and resource types - Microsoft Graph](https://docs.microsoft.com/en-us/graph/errors#feedback)
* Content Source: [concepts/errors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/errors.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by madansr7** [comment]
@alex-tomin, we do intent to align all APIs to follow the same conventions for generating errors. Even though these are errors, changing and aligning would make that a breaking change. We are currently investigating the best way to move forward without affecting the existing coded flows.

**Comment by jthake-msft** [comment]
@madansr7 who is driving this work now?
