### ISSUE TITLE
permit Type "Application" removed

### ISSUE THREAD

**Issue by miun894** [microsoftgraph/microsoft-graph-docs#5014]
why was the permit Type "Application" removed? 
Now I get a "permission denied" when I invoke the service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lindseylanier** [comment]
Any updates on when this will be reenabled!?

**Comment by miun894** [comment]
Unfortunately I have no news. we have developed "reports" on the adaptation of individual teams groups and without using  the api via application, as was possible before, we fail to monitor adoption.

**Comment by nkramer** [comment]
Just published: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-protected-apis.md
