### ISSUE TITLE
Creating page with Application permissions

### ISSUE THREAD

**Issue by remcovn** [microsoftgraph/microsoft-graph-docs#5016]
When I'm trying to create a new page on an existing SharePoint page using application permissions, I'm experiencing some weird issues. The request gives a valid response object, but the page itself doesn't show up under Site Pages in SharePoint and doesn't show up when listing all pages using the Graph API neither.

The request body I'm using is:
`
{
    "name": "Testpage.aspx",
    "title": "Test",
    "pageLayout": "Article",
    "publishingState": {
        "level": "checkedOut",
        "versionId": "0.1"
    },
    "webParts": [
        {
            "type": "rte",
            "data": {
                "innerHTML": "<h3>Test</h3>"
            }
        }
    ]
}
`

I'm POST-ing this to 
`
https://graph.microsoft.com/beta/sites/[SITEID]/pages
`

When I'm performing exactly the same request using delegated permissions in a user context the result is as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf8c08e-49be-b1b7-54fc-c83983f8ff83
* Version Independent ID: d5afa542-1f60-630e-4133-314a90e03165
* Content: [Create a new page in a SharePoint site - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/sitepage-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @rahmit
* Microsoft Alias: **rahmit**

**Comment by klorenzen7** [comment]
Hello @remcovn, I am having the same problem. I was assuming that we need to publish the page before it can be seen. Have you tried to get the pageId from the response object then publish?

When I try to publish, I always get a 401 Unauthorized return status. Here is the docs page:
https://docs.microsoft.com/en-us/graph/api/sitepage-publish?view=graph-rest-beta

I created the question below but got no response:
https://stackoverflow.com/questions/56659500/using-ms-graph-beta-api-to-create-a-site-page-works-but-can-not-publish

I will keep asking around and watching your post for the answer.
