### ISSUE TITLE
Missing information related to chat functions as part of online Teams meetings

### ISSUE THREAD

**Issue by angoo-atea** [microsoftgraph/microsoft-graph-docs#5018]
Every Teams meeting has a chat function. There appears to be no reference here to API functions related to chat conversations. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c04f3b-9434-acad-e5ac-2aeaa3559578
* Version Independent ID: 5e6aba7e-2d50-82fb-196a-82027e5a37f4
* Content: [Working with the calls and online meetings API in Microsoft Graph - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/calls-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/calls-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
Hi @angoo-atea - Here you go https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta. Please ask your questions on that page.
