### ISSUE TITLE
Azure AD identity protection API (preview)

### ISSUE THREAD

**Issue by Cloud-Architekt** [microsoftgraph/microsoft-graph-docs#5023]
There's no link to the advanced and updated "AAD identity protection" APIs (currently in preview): https://docs.microsoft.com/en-us/graph/api/resources/identityprotection-root?view=graph-rest-beta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 950f7b2a-e6b6-877f-9928-dbc5006e9224
* Version Independent ID: 7a638117-dba8-9431-cb16-0bd91727f25f
* Content: [Integrate Microsoft Graph Security API alerts with a SIEM - Microsoft Graph](https://docs.microsoft.com/en-us/graph/security-siemintegration#feedback)
* Content Source: [concepts/security-siemintegration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/security-siemintegration.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cloudhandler** [comment]
This has been fixed, thanks for feedback!
