### ISSUE TITLE
Compliance, Configuration Policies and deviceHealthAttestationState

### ISSUE THREAD

**Issue by peterpantheking** [microsoftgraph/microsoft-graph-docs#5026]
How can I get the assigned Compliance and Configuration Policies to this device and why does the deviceHealthAttestationState Attribute always return null if I send a requeat for a mangedDevice object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3ea619-bc42-6c9d-2b39-a59f59c7b89d
* Version Independent ID: d6e48a69-7536-b293-a86e-5c629ed5cb78
* Content: [managedDevice resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-manageddevice?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/intune-devices-manageddevice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-devices-manageddevice.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
The easiest way to determine the API calls required for a scenario is to use F12 developer mode in a browser to trace the network traffic.  I have a video here that shows how to do this: https://youtu.be/AaD1gxd9us4
You may need to do $select to have the deviceHealthAttestationState property returned.  Not all properties are returned by default when getting a managedDevice object.
