### ISSUE TITLE
Filtering events by start and end date results in "This filter query is not supported" on beta api

### ISSUE THREAD

**Issue by fbcouch** [microsoftgraph/microsoft-graph-docs#5033]
Filtering events using https://graph.microsoft.com/beta/me/calendars/{calendarId}/events?$filter=Start/DateTime+lt+'2019-09-08'+and+End/DateTime+gt+'2019-05-26' stopped working today around 2:30pm Pacific time (this has been working since at least October 2018). Interestingly, the same call on the v1.0 API still works. 

Example response:

```
{
    "error": {
        "code": "BadRequest",
        "message": "This filter query is not supported.",
        "innerError": {
            "request-id": "e668e082-2d1d-425a-ba45-0d88658b26d1",
            "date": "2019-07-09T01:53:32"
        }
    }
}
```

**Comment by vladski** [comment]
I can confirm the issue and you can replicate it in Graph explorer:

- still works in v1.0:
https://developer.microsoft.com/en-us/graph/graph-explorer?request=me/events?$filter=start/dateTime%20ge%20%272017-11-15%2007:00:00%27&method=GET&version=v1.0

- does not work in beta:
https://developer.microsoft.com/en-us/graph/graph-explorer?request=me/events?$filter=start/dateTime%20ge%20%272017-11-15%2007:00:00%27&method=GET&version=beta

**Comment by BraunJonathan** [comment]
I can add that i had a dateTime filter on Outlook/tasks beta api which was working until a few hours ago...

https://graph.microsoft.com/beta/me/outlook/tasks?$filter=status ne 'completed' and dueDateTime/DateTime ge '2019-07-09T00:00:00.000' and dueDateTime/DateTime lt '2019-07-10T00:00:00.000'&$orderby=status, dueDateTime/DateTime asc

Same bad request error now...

**Comment by GreyMana-git** [comment]
I have the same issue since early today/yesterday:

Beta query does not work (This filter query is not supported):
[](https://graph.microsoft.com/beta/me/calendar/events?$filter=start/dateTime ge '2019-07-09T06:00:00.000Z' and start/dateTime lt '2019-07-09T17:00:00.000Z'&$select=id,start,end,showAs,subject,attendees,sensitivity)

Changing the API to v1.0 works fine:
[](https://graph.microsoft.com/v1.0/me/calendar/events?$filter=start/dateTime ge '2019-07-09T06:00:00.000Z' and start/dateTime lt '2019-07-09T17:00:00.000Z'&$select=id,start,end,showAs,subject,attendees,sensitivity)

**Comment by justdevelopment** [comment]
The same thing happens on $orderby for these endpoints. This is a breaking change for us if this gets pushed to v1, so I'm hoping this is an 'oops'.

I've created an issue on stackoverlow (we've been told in the past to report bugs/issues there). Feel free to add/comment ; https://stackoverflow.com/questions/56953195/calendar-tasks-endpoints-in-beta-stopped-working-with-filter-or-orderby-on-d

**Comment by dan-silver** [comment]
Thank you for reporting the issue. We're investigating now

**Comment by dan-silver** [comment]
We have mitigated the issue. If anyone still sees this behavior in the beta endpoint, please let me know!

**Comment by fbcouch** [comment]
Looks good to me, thanks!
