### ISSUE TITLE
Now no id is coming in the permissions api in v1.0 flow 

### ISSUE THREAD

**Issue by deepeshalways** [microsoftgraph/microsoft-graph-docs#5034]
Hi there is removal of id from permission api and adding of email field in this. why so uncertanity in your v1.0 apis too.

i am calling this api from  batch call and the response is suddenly changed in v1.0 apis.

Also now not getting link sharing notification from your side itself which we were getting previously. so please look into it asap. thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d86c75f2-a9c8-af58-e9c1-30579417348a
* Version Independent ID: 0b0cd088-c182-de7c-7216-57027b118c46
* Content: [Identity - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/identity?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/identity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/identity.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by deepeshalways** [comment]
Also Link share notification and notification for (when removed folder inherted shares from files is missing)

Please Fix this asap, it is affecting our clients.

**Comment by davidmu1** [comment]
This does not seem to be an issue with the documentation. These issues should be calling out problems in the documentation itself. Closing the issue. Go ahead and reopen with more information about specific changes that need to be made to the content in the page.
