### ISSUE TITLE
Inconsistent behavior wrt Create group

### ISSUE THREAD

**Issue by zvrba** [microsoftgraph/microsoft-graph-docs#5036]
It is possible to create a group with no owners, both from the API and the portal (it's what happens by default automatically). This call fails when trying to delete the last remaining owner. Why should this be an error? It should at least be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4e8438-09f9-b27d-ceed-559d9f142211
* Version Independent ID: dc761c5d-1357-5fdb-f2e3-fd687ef89346
* Content: [Remove owner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
"It is recommended for every group to have at least one owner. Once owners are assigned to a group, the last owner of the group can not be removed." This is documented here: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners
