### ISSUE TITLE
Calendar Event "isReminderOn": false is not working in v1.0

### ISSUE THREAD

**Issue by raeika** [microsoftgraph/microsoft-graph-docs#5040]
Issue: Setting "isReminderOn" to false is not working for Calendar Create Event. It triggers the reminder although it was set to false. I also tried setting up
IsReminderOn = false,
ReminderMinutesBeforeStart = 2147483647

Article:

**Comment by jthake-msft** [comment]
@Harini84 just fyi might be worth checking if this is still valid.
