### ISSUE TITLE
Error creating page "message": "[page] Found an unbalanced bracket expression.",

### ISSUE THREAD

**Issue by TheMasterPrawn** [microsoftgraph/microsoft-graph-docs#5041]
Issue: When using the above sample, I keep getting 

"message": "[page] Found an unbalanced bracket expression.",

Full 
```json
{
    "error": {
        "code": "invalidRequest",
        "message": "[page] Found an unbalanced bracket expression.",
        "innerError": {
            "request-id": "db0f746d-01ca-424f-93f8-54d44c8138da",
            "date": "2019-07-09T15:08:04"
        }
    }
}
```
If I remove everything related to the web parts , then a blank page is successfully created 
```json
{
    "name": "Events.aspx",
    "title": "Team Events",
    "publishingState": {
        "level": "checkedOut",
        "versionId": "0.1"
    }
}
```
This works.

Is this due to the nature of the beta API or do we need to know the exact naming for web parts ?

Article:

**Comment by jantman** [comment]
I'm having this issue as well, even if I remove the Events webpart and just send:

```json
{
    "name": "Events.aspx",
    "title": "Team Events",
    "publishingState": {
        "level": "checkedOut",
        "versionId": "0.1"
    },
    "webParts": [
        {
            "type": "rte",
            "innerHTML": "<p>Here are the team's upcoming events:</p>"
        }
    ]
}
```

I can't figure out how to create a page like this, and it's a bit troubling that the documentation example doesn't work.

**Comment by jantman** [comment]
I believe I've solved this. The issue appears to be caused by https://github.com/OData/odata.net/issues/764. Specifically... as crazy as this is... by the presence of a single quote (`'`) or left bracket (`[`) in the HTML.

The workaround is to either just replace the single quote in the example with its HTML entity `&apos;` or to explicitly set the odata type on the innerHTML:

```
{
    "name": "Events.aspx",
    "title": "Team Events",
    "publishingState": {
        "level": "checkedOut",
        "versionId": "0.1"
    },
    "webParts": [
        {
            "type": "rte",
            "innerHTML": "<p>Here are the team's upcoming events:</p>",
            "innerHTML@odata.type": "#String"
        }
    ]
}
```
