### ISSUE TITLE
Query checkout status

### ISSUE THREAD

**Issue by lauraemilyjacobsen** [microsoftgraph/microsoft-graph-docs#5046]
How can I use the API to find out if a drive item is checked out and to whom?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e87dfc28-095a-f2f3-99a7-d2323e564f7a
* Version Independent ID: 933f5fa6-a7f6-c4f5-c6f0-b81cbbcad84b
* Content: [Check Out Files - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-checkout?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/driveitem-checkout.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-checkout.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by schaeferto** [comment]
You could query the list item like described [here](https://docs.microsoft.com/de-de/graph/api/listitem-get?view=graph-rest-1.0&tabs=http).
e.g. `https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-id}/fields/$expand=CheckoutUser`
Then check if the CheckoutUser is set.

**Comment by lauraemilyjacobsen** [comment]
Great, this is exactly what I needed. The key was to query the DriveItem using the Lists API instead of the Drives API as I had been doing. Thank you!
