### ISSUE TITLE
Contact photo doesn't exist if this contact is added from user

### ISSUE THREAD

**Issue by simiczhang** [microsoftgraph/microsoft-graph-docs#5063]
If I add a user of this group to contact list by "add to contact", I can't use API: "GET /me/contacts/{id}/photo/$value" to get his contact photo, but if I manually set a photo in "Edit contact", this API works.

Why not make it consistent , the contact added from user should have a contact photo that uses user photo by default ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PeterChencha** [comment]
Hello @simiczhang thanks for reaching out. This by design, your feedback is highly appreciated. We welcome ideas and hope to take them into consideration in future releases.
