### ISSUE TITLE
Use $count=true&$top=5 would get "@odata.count": -1"

### ISSUE THREAD

**Issue by simiczhang** [microsoftgraph/microsoft-graph-docs#5064]
While using query option "count" with another query option "top" to get contact list, the result would show the odata.count value as "-1", there is no where in the document "OData Query Parameters" mentions "count" can't be used with "top" so is this a bug?

The url I am testing with:  "https://graph.microsoft.com/v1.0/me/contacts?count=true&$top=4"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a53287-56fe-6cb1-71c2-5f27560b11b0
* Version Independent ID: 57d2f08b-d98a-4028-5cec-a7ef0121fdc3
* Content: [List contacts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/contactfolder-list-contacts?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/contactfolder-list-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/contactfolder-list-contacts.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by simiczhang** [comment]
Updated: this bug can't be reproduced all the time, it happens randomly.

**Comment by xdmushui** [comment]
#6221

**Comment by PeterChencha** [comment]
Hello @simiczhang thanks for reaching out. This looks to be resolved, kindly confirm if this is recurring, happy to help.

**Comment by PeterChencha** [comment]
Hello @simiczhang this issue appears resolved. Please feel free to open another issue if this is still recurring for you.
