### ISSUE TITLE
UpdateList returns HTTP 200 status code, but the document says 201

### ISSUE THREAD

**Issue by mannharleen** [microsoftgraph/microsoft-graph-docs#5076]
Issue: UpdateList returns HTTP 200 status code, but the document says 201.

Article: https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=javascript

**Comment by isvargasmsft** [comment]
Hello @mannharleen, 

My deepest apologies for the delays in our response. Thank you very much for bringing this into our attention.

Creating a PR right away to fix this issue. 

Kind regards,

Isaac
