### ISSUE TITLE
Mysterious socketIO API endpoint

### ISSUE THREAD

**Issue by MarshHawk** [microsoftgraph/microsoft-graph-docs#5079]
It's not completely clear how to use this functionality. Minimally, using MS GraphAPI version 1.0:

1. After authenticating, I successfully get a subscription object from https://graph.microsoft.com/v1.0/me/drive/root/subscriptions/socketIo

2. The subscription object has a notification URL with "notifications?" not "callback?" and no "resource" property.

3. Correctly connect a socket.io client to notificationUrl with token and listen for "notification" event.

4. Successfully post to create new folder https://graph.microsoft.com/v1.0/me/drive/root/children

I would expect to receive a "notification" event for the folder creation, yet I don't. Is there something missing in the above workflow? Do I need to create a subscription with the given notificationUrl in order to receive notifications?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1e1ab1b-55aa-f10f-7262-1f1bb3fce3d6
* Version Independent ID: 8a2e5885-7612-3850-6192-c766b61da835
* Content: [Get websocket endpoint - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-subscriptions-socketio?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveItem-subscriptions-socketio.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveItem-subscriptions-socketio.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @daspek
* Microsoft Alias: **dspektor**

**Comment by daspek** [comment]
We've made some simplifications so you no longer need to deconstruct the URL. You can pass the raw  `notificationUrl` from the subscription object directly to socketIo:

```
...
{
  "id": "opaqueId-fj3hd7yf283jfk193726nvc2w3i2diemdu8",
  "notificationUrl": "https://f3hb0mpua.svc.ms/zbaehwg?snthgk=1ff3-2345672zz831837523"
}

var notificationUrl = "https://f3hb0mpua.svc.ms/zbaehwg?snthgk=1ff3-2345672zz831837523";
var socket = io(notificationUrl);
...
```

We're going to clean up the documentation soon. But the existing documented sample should still work as-is, since the string-split won't produce two elements when 'callback' is missing. Can you check whether it works with the simplified example?

**Comment by MarshHawk** [comment]
Hi, 

Yes, it did work with the simplified example. Thanks. I'll close the issue. I would just mention that it would be good to know if there are any other events that would be published to this endpoint besides "notification"? Please let me know with a comment if there are.
