### ISSUE TITLE
Typo: " 

### ISSUE THREAD

**Issue by davisjam** [microsoftgraph/microsoft-graph-docs#5080]
Stray double-quote?

```
If you wish to activate the newly added worksheet, call ".activate() on it.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdd1d978-a9fc-b6b0-54c9-6898dc6a1890
* Version Independent ID: 0f543185-509d-4050-bbab-a9d94e1037bc
* Content: [WorksheetCollection: add - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/worksheetcollection-add?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/worksheetcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/worksheetcollection-add.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dplotnikov** [comment]
@lumine2008 I've made a fix for it, please accept the PR

**Comment by dplotnikov** [comment]
@Lauragra please close this ticket as well
