### ISSUE TITLE
OneNote Tab wrong

### ISSUE THREAD

**Issue by phvogel** [microsoftgraph/microsoft-graph-docs#5098]
The OneNote sample is still wrong.
Create a OneNote tab manually and then look at the output of /teams/{teamId}/channels/{channelId}/tabs.
That is the correct format.

Here a Code Sample in C# that works:

var contentUrl = "https://www.onenote.com/teams/TabContent?notebookSource=New" +            $"&notebookSelfUrl=https%3A%2F%2Fwww.onenote.com%2Fapi%2Fv1.0%2FmyOrganization%2FsiteCollections%2F{siteCollectionId}%2Fsites%2F{siteId}%2Fnotes%2Fnotebooks%2F{notebookId}" +
$"&oneNoteWebUrl={WebUtility.UrlEncode(notebook.Links.OneNoteWebUrl.Href)}" +
$"&notebookName={WebUtility.UrlEncode(notebook.DisplayName)}" +
$"&siteUrl={WebUtility.UrlEncode(rootSite.WebUrl)}" +
$"&createdTeamType=Standard" +
"&ui={locale}&tenantId={tid}&upn={userPrincipalName}&groupId={groupId}&theme={theme}&entityId={entityId}&subEntityId={subEntityId}&sessionId={sessionId}&ringId={ringId}";

For removeUrl its the same except that you need to use the URL /TabRemove.

It's also incorrect that all information can be retrieved from
GET /groups/{id}/onenote/notebooks

You need the Site Collection Id and Site Id from the corresponding GET /groups/{groupId}/sites/root

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Philipp-Vogel** [comment]
Also if the JSON of the Configuration part is over 2048 characters long, the Graph API returns the following error: `InvalidRequest Configuration size exceeded. Provided:'2056'bytes MaxAllowed:'4096'bytes` 

This can be reproduced with the Graph API explorer: Try to add a OneNote Tab, and use a Notebook Name which is somwhat longer, to easly exceed the 2048 character limit. The Graph Explorer will the display the same error. Where is the correct location to report this error?

**Comment by TOPDHI** [comment]
For me it works as it is described. Just with the 'note' name tweak as written by @NCSTman

**Comment by jerem99** [comment]
@Philipp-Vogel have you resolve the issue with "size exceeded"? I have the same problem.

**Comment by Philipp-Vogel** [comment]
No as far as I remember, as soon as the name is somewhat longer, I still have the same error and have to correct it manually

**Comment by Philipp-Vogel** [comment]
The API seems to have changed somewhat. To try go get around the "Configuration size exceeded" error, I used to split it into two request:
- Add: All properties set, but the URL's empty
- Update: Jus tthe URL's set
This is no longer accepted, so i have to set all parameters in a single Add request, leading to still the same problem:

Microsoft.Graph.ServiceException: 'Code: BadRequest
Message: Configuration size exceeded. Provided:'2222'bytes MaxAllowed:'4096'bytes

**Comment by satsuper** [comment]
For anyone running into the "Configuration size exceeded" error you can omit the `removeUrl` and `websiteUrl` fields. I was able to load my OneNote tab and delete it from the Teams UI successfully after adding it through the API.

I was not able to add the URLs with a PATCH request as per the Update Tab API as it overwrites all properties in the configuration object.

**Comment by HunaidHanfee-MSFT** [comment]
@phvogel Could you please confirm if you are still facing this issue?

**Comment by HunaidHanfee-MSFT** [comment]
Please feel free to open this issue, if you are facing any issue. We are closing this as of now.
