### ISSUE TITLE
Channel Message From object

### ISSUE THREAD

**Issue by ashleywb** [microsoftgraph/microsoft-graph-docs#5118]
Is there any more detail around from object, what gets returned for application, device and conversation. Thanks
 "from": {
                "application": null,
                "device": null,
                "conversation": null,
                "user": {
                    "id": "bb8775a4-4d8c-42cf-a1d4-4d58c2bb668f",
                    "displayName": "Adele Vance",
                    "userIdentityType": "aadUser"
                }
            },

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Application refers to things like Bots, AAD Apps etc.
Device is not used at the moment
Conversation refers to chats, channels, teams etc.
User refers to AAD users, Guests etc

**Comment by HunaidHanfee-MSFT** [comment]
`from` is of type [chatMessageFromIdentitySet](https://docs.microsoft.com/en-us/graph/api/resources/chatmessagefromidentityset?view=graph-rest-beta). Please have a look at the documentation.

As mentioned by @RamjotSingh you will find the same info in doc.
> application- If present, represents the application (for example, bot) that sent the message.
> device- Not used.
> user- If present, represents the user that sent the message.

Please let us know if you have any query. We will be closing this issue, please feel free to open it.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
