### ISSUE TITLE
Permissions (from least to most privileged)

### ISSUE THREAD

**Issue by dgancho** [microsoftgraph/microsoft-graph-docs#5121]
Permissions (both delegated and application) should be listed in the opposite order: Group.Read.All, Group.ReadWrite.All

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac52a23b-0065-5a60-15ae-0b774938af12
* Version Independent ID: 9db72af9-0b04-5228-3ec2-b0ca49d9ed01
* Content: [List posts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/conversationthread-list-posts?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/conversationthread-list-posts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/conversationthread-list-posts.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
Fixed.
