### ISSUE TITLE
MailNickname is not enforced to be unique

### ISSUE THREAD

**Issue by zvrba** [microsoftgraph/microsoft-graph-docs#5122]
The documentation for Group object properties says the following for `mailNickname` in the description: "The mail alias for the group, unique in the organization." Create group allows creation of groups with identical nicknames. This is inconsistent with the property documentation, or possibly bug in the implementation of the API. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by alutgert** [comment]
I just tried with the BETA api and I'm getting the following response:

Response content:
{
  "error": {
    "code": "Request_BadRequest",
    "message": "Another object with the same value for property mailNickname already exists.",
    "innerError": {
      "request-id": "94d4abf2-60a0-4d9c-8a3e-6d69b12d2e1b",
      "date": "2019-08-22T12:29:22"
    },
    "details": [
      {
        "target": "mailNickname",
        "code": "ObjectConflict"
      }
    ]
  }
}

**Comment by zvrba** [comment]
Have you tried with the v1 API? Is it advisable to rely on beta APIs in production?

**Comment by alutgert** [comment]
Hi,

I just tested it with the v1.0 api and I got the same result (error) as in the Beta API:

{
    "error": {
        "code": "Request_BadRequest",
        "message": "Another object with the same value for property mailNickname already exists.",
        "innerError": {
            "request-id": "39eb0405-4757-4815-b0de-a6fe40bb055a",
            "date": "2019-08-22T17:58:57"
        },
        "details": [
            {
                "target": "mailNickname",
                "code": "ObjectConflict"
            }
        ]
    }
}

I would not advise to use the beta API in production.

**Comment by zvrba** [comment]
Ok, thanks for testing. I was using the C# Graph library and used a `mailNickname` without an `@` sign, i.e., it was something like `a-x-b-y`. Weird.

**Comment by zvrba** [comment]
I figured out what my mistake was. I wasn't looking carefully: I was taking user input into a string, then used `String.getHashCode()` to derive `mailNickname`. However, hash code is not stable from run to run when running in Azure AppService so a different nickname was generated each time even with same user input.
