### ISSUE TITLE
ID mismatch and missing info..

### ISSUE THREAD

**Issue by steffenschumacher** [microsoftgraph/microsoft-graph-docs#5123]
Using this yields resourceIDs which doesn't map to the app - and without this, its next to pointless?
the resourceDisplayName is correct, but that's not kosher for mapping?
Secondly, I get the appRoleId, but not the appRoleName? This would mean I would need to maintain that mapping locally in my app????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3546a45-22f6-8f62-9f5d-26450c484572
* Version Independent ID: 0f6521fa-e1ed-ae22-9958-6a118c3518e6
* Content: [Get appRoleAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/approleassignment-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/approleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/approleassignment-get.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
Apologies for the lack of response here. Adding an answer in case someone comes across this in the future:

* The **resourceId** of an **appRoleAssignment** is the **id** of the resource app's **servicePrincipal** in the tenant. To retrieve this object (and get other identifiers and details, including the **appId**), do `GET /v1.0/servicePrincipals/{resourceId}`.
* The **appRoleId** of an **appRoleAssignment** is the **id** of one of the items in the **appRoles* collection of the resource app's **servicePrincipal**. Once you've retrieved the resource service principal (as mentioned in the previous point), you can find the matching app role to get the display name, description and claim value (if one exists).
