### ISSUE TITLE
microsoft.graph.search not working on beta api

### ISSUE THREAD

**Issue by BerndSadleder** [microsoftgraph/microsoft-graph-docs#5126]
Hello,
i have an issue with the new **graph beta api**.

Issue:
The library Microsoft.Graph(.Beta) generates an api call "/drive/root/microsoft.graph.search(q='test')" which is working on production api but not on beta api. On beta api only "/drive/root/search(q='test') works.

Sample - NOT working:
https://graph.microsoft.com:443/beta/groups/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX/drive/root/microsoft.graph.search(q='test')

Sample - working:
https://graph.microsoft.com:443/v1.0/groups/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX/drive/root/microsoft.graph.search(q='test')

**Comment by janbalcarik** [comment]
Hi, it's not ideal, but this is my temporary solution:

```
            graphService = new GraphServiceClient(graphAPIEndpoint, new DelegateAuthenticationProvider(async (requestMessage) =>
            {
                requestMessage.Headers.Authorization = new AuthenticationHeaderValue("bearer", authResult.AccessToken);
                requestMessage.RequestUri = new Uri(requestMessage.RequestUri.AbsoluteUri.Replace("microsoft.graph.search", "search"));
            }));
```

**Comment by BerndSadleder** [comment]
@janbalcarik This workaround will work - thank you.

**Comment by Kalle4242** [comment]
Why was this issue closed? 
The workaround works, but it is still an error!
And if you are working with the SDK you are searching a long time to find out, why the search is not running!
