### ISSUE TITLE
Please let us know if this works for Office 365 F1 licensed users.

### ISSUE THREAD

**Issue by anoopt** [microsoftgraph/microsoft-graph-docs#5127]
Hello,

Can you please let us know if this request (/me/joinedTeams) works with users who have Office 365 F1 license assigned to them? 

When I open Postman or Graph Explorer (and assign required permissions) with the query https://graph.microsoft.com/v1.0/me/joinedTeams, the error message I see is - "User Login. Teams is disabled for your tenant".

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fbcfbc4-78ba-8b4c-d5b9-dc58f9d84f5f
* Version Independent ID: 1dcb5dda-2a45-77e1-bbe1-46ec24b33eec
* Content: [List joinedTeams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-joinedteams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-joinedteams.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Rafaelki** [comment]
Same problem here with F1 and /me/joinedTeams, different error message: 
"CompactToken parsing failed with error code: 80049217"

**Comment by HunaidHanfee-MSFT** [comment]
It seems like you need at least basic license to do. I will confirm about this internally get back to you soon. 
 Have a look at these documents - [Prepare your Microsoft 365 tenant](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant) and [Enable Teams for your organization](https://docs.microsoft.com/en-us/microsoftteams/enable-features-office-365)

**Comment by v-chetsh** [comment]
@anoopt - We are closing this issue for now, Please feel free to reopen it, if required.
