### ISSUE TITLE
Sample for Code using the Graph Client SDK for .NET 

### ISSUE THREAD

**Issue by TaviTruman** [microsoftgraph/microsoft-graph-docs#5130]
It would be very useful to have the example code for the native .NET SDK Client library. We don't use any REST APIs and we don't develope REST APIs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a073f203-e931-588c-7b15-227483fe01fb
* Version Independent ID: 59982274-4dae-4c9e-fd55-414ec30c0573
* Content: [calendar resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/calendar.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @TaviTruman , thanks for your input! If you take a look at the Microsoft Graph method topics like [list calendars](https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=csharp), there is a C# tab that shows the corresponding code for the .NET SDK.
Hope that helps!
