### ISSUE TITLE
Working C# remove member example

### ISSUE THREAD

**Issue by jimt4593** [microsoftgraph/microsoft-graph-docs#5133]
GraphServiceClient graphClient = new GraphServiceClient(authProvider);

            await _gscs.GraphServiceClient.Groups[groupId]
                .Members[userId]
                .Reference
                .Request()
                .DeleteAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@MIchaelMainer what should this be?

**Comment by MIchaelMainer** [comment]
I don't see anything wrong with this sample. This should work as expected.

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
