### ISSUE TITLE
checkMemberGroups end point is giving wrong info

### ISSUE THREAD

**Issue by msdevanms** [microsoftgraph/microsoft-graph-docs#5137]
Issue: While using  following API end point i am getting all groups and users associated with the application.

https://graph.microsoft.com/beta/servicePrincipals/{service_pricipal_id}/appRoleAssignments

But while i am using following end points with associated service principal, i am getting **false** as result.

old API 
https://graph.windows.net/{tenant_id}/isMemberOf?api-version=1.6

beta API
POST /servicePrincipals/{id}/checkMemberGroups

**Comment by msdevanms** [comment]
https://stackoverflow.com/questions/40731389/microsoft-azure-graph-api-approleassignedto-not-working

**Comment by jthake-msft** [comment]
i will close this as you've asked it in stack. this issue list is specifically for docs feedback.
