### ISSUE TITLE
Wrong information about Conflict Behaviour.

### ISSUE THREAD

**Issue by anurag2994** [microsoftgraph/microsoft-graph-docs#5140]
[This page](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-beta) suggests to use `"@microsoft.graph.conflictBehavior": "rename | fail | overwrite"`.

While using the `overwrite` flag, I received an error that the supported conflict behaviors are: `rename | fail | replace`.

Could someone please confirm this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by mlafleur** [comment]
You are correct, the possible values are `fail` (default), `replace`, or `rename`.
