### ISSUE TITLE
Different name required for POST /drives/{driveId}/items/{itemId}/copy

### ISSUE THREAD

**Issue by oleglpts** [microsoftgraph/microsoft-graph-docs#5141]
If you do not specify a different name than the original when using POST /drives/{driveId}/items/{itemId}/copy, response code is 202, bit item don't copied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d887c2a6-40ba-675b-7b09-a7a3fffe17f5
* Version Independent ID: 03692ea1-b802-f768-a3bc-04a846b6771a
* Content: [Copy a file or folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-copy?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-copy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-copy.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by ificator** [comment]
Are you by any chance using an application permission token (i.e. `app-only` / `daemon`)? There's a known issue for that scenario that can result in the behavior you outlined.

See https://github.com/OneDrive/onedrive-api-docs/issues/980 for details.

**Comment by ificator** [comment]
Closing stale issues.
