### ISSUE TITLE
add documentation on how to access a specific tenant/subscription

### ISSUE THREAD

**Issue by ravensorb** [microsoftgraph/microsoft-graph-docs#5150]
I believe the graph api can be used against specific tenants -- it would be great if you could update the documentation to include examples for these use cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c5cd62a-5325-aeda-c1ae-33b6157eb04c
* Version Independent ID: c9b14f46-af37-3520-450c-3ed4d5f54f46
* Content: [List groups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
When you register an application that you use to access the graph. you can specific it being a single tenant or multiple tenants.
The get a token section of our docs covers this
https://docs.microsoft.com/en-us/graph/auth-register-app-v2
