### ISSUE TITLE
Graph Toolkit not showing in reference table of contents

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#5153]
@nmetulev the TOC.yml for beta and v1.0 needs to have the toolkit nodes in it like the SDK nodes. They currently only show in the conceptual documentation pages.

**Comment by Lauragra** [comment]
@jthake-msft , they should be there - I already added them. Let me know if I'm missing something?

**Comment by jthake-msft** [comment]
OK I see them ! Thanks!
