### ISSUE TITLE
How can base64 output be assigned to contentBytes ?

### ISSUE THREAD

**Issue by codeshift25** [microsoftgraph/microsoft-graph-docs#5159]
"The contentBytes property contains the base64-encoded contents of the file". Base64 is a binary to text encoding and contentBytes accepts a byte array. Is this a mistake or do you expect the client to convert the binary data to base64 string and then encode that string again into bytes ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e11bf3-1c47-a258-da9b-37cf0ee5cb37
* Version Independent ID: 85b45ad2-c35a-82e8-d77a-47dadfa70e4a
* Content: [fileAttachment resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/fileattachment?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/fileattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/fileattachment.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@codeshift25 `contentBytes` is Binary in the OData sense. So basically you encode the bytes as base64 and put them into that property.
