### ISSUE TITLE
New created group cannot directly be used for create a permission on a file in SharePoint Online

### ISSUE THREAD

**Issue by digiofficerobin** [microsoftgraph/microsoft-graph-docs#5162]
Example code:

		private static void AddAndUseGroep(GraphServiceClient graphClient, string siteID, string driveItemID)
		{

			var group = new Group
			{
				DisplayName = "Home Alone",
				MailEnabled = false,
				SecurityEnabled = true,
				MailNickname = "HomeAlone"
			};

			var newGroup = graphClient.Groups.Request().AddAsync(group).Result;

			var recipients = new List&lt;DriveRecipient&gt;(){new DriveRecipient{ObjectId = newGroup.Id}};

			var message = string.Empty;

			var requireSignIn = true;

			var sendInvitation = false;

			var roles = new List&lt;String&gt;(){"write"};

			// Why does the group isn't directly available for use in permissions?
			// Also the exception message "The request is malformed or incorrect." is not clear. An "Recepient not found" exception would be more informative.
			int maxRetries = 10;
			for (int i = 0; i &lt; maxRetries; i++)
			{
				try
				{
					graphClient.Sites[siteID].Drive.Items[driveItemID].Invite(recipients, requireSignIn, roles, sendInvitation, message)
						.Request()
						.PostAsync().Result.ToList();
					
					break; // break the retry loop
				}
				catch(Exception ex)
				{
					Console.WriteLine(ex.Message); //Message: The request is malformed or incorrect.
					Thread.Sleep(10000);
				}
			}
		}

Please solve this problem.

This has cost me several hours to find out why it isn't possible to add a permission with a new group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ificator** [comment]
This error message is indeed unhelpful - I'll see if we can improve it.

**Comment by davidmu1** [comment]
This forum is not meant to assist with programming issues, it is for discussing issues with the documentation on the page. Suggest posting the question on a forum like StackOverflow. No change identified for the page. Closing the issue.
