### ISSUE TITLE
List chats Not working

### ISSUE THREAD

**Issue by inbrij** [microsoftgraph/microsoft-graph-docs#5163]
Hi, 

graphClient.Users["xxxxxx"].Chats.Request().GetAsync().GetAwaiter().GetResult();
when i try to use this function i get the following error 

Code: BadRequest
Message: Specified method is not supported.

The same code works if i just try to get the user object 
graphClient.Users["xxxxxx"].Request().GetAsync().GetAwaiter().GetResult()

Please can you explain.

Thanks 
B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79531fbc-dd22-cf80-c97c-746f7dcab790
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
app permissions aren't supported – you're using user delegated, right?

**Comment by inbrij** [comment]
yes, i have added chat.read.all and chat.read rights to the proxy. How come Microsoft publish an endpoint without implanting it. 
is there any other way to extract the chat history ? 
edicovery is very manual and it does not give chat threads. i need a mechanism through which we can extract chats

**Comment by nateclar** [comment]
Is there a timeline for when these app permissions will be supported?

**Comment by Dev-Don** [comment]
I have a need to allow an web API to access the chat list. I have an API that uses users credentials, App secret and api id to get a accessToken. Is there a way I can set my api up to access the chat list with a user accessToken?

**Comment by Dev-Don** [comment]
Also, my API is setup with delegated permissions within Azure.

**Comment by snovo** [comment]
does anyone know if application permissions are supported?
the documentation is a bit confusing as it states both!
![chats](https://user-images.githubusercontent.com/2424053/66561517-8c494080-eb51-11e9-8e01-256304ecf3df.PNG)

**Comment by rdtsai** [comment]
Hi @nkramer, is there a plan to have /chats to support application permissions? 
1. its documentation is marked as Protective API. Application permissions make sense
2. since chats/{id}/messages is already support application permissions according to the documentation. it would be natural to have its parent level to also support the same permissions.
3. asking since this issue has been open for some time

Thanks

**Comment by Jowdan3006** [comment]
I Also need application level permissions. Would be really useful to have this. Are there any updates?
Thanks.

**Comment by mag382** [comment]
Adding on here: delegated permissions should be enabled for Chats.  A system administrator in an organization should be able to access chats for the purpose of eDiscovery and litigation.  Requiring the login for each individual user does not match the design of any other user data stored and accessed through the Microsoft Graph API.

**Comment by MushyMiddle** [comment]
eDiscovery & litigation being valid use cases, another is analytics.  As an ISV, I want to allow my customers to do analytics on chat, and cannot do so.  On the other hand, Microsoft *does* use this API (seemingly) to generate per-user analytics which I get in my inbox every week or so.  While it might be a bit childish to call that "unfair", it does seem like Microsoft has an uneven playing field here.

**Comment by nkramer** [comment]
We do intend to support application permissions eventually, but it's a long slog getting that to work. I'm gonna close this issue so we can keep this repo for doc issues, but please log feedback on User Voice.

**Comment by apitts** [comment]
For those looking for the UserVoice suggestion to upvote, this is the most relevant one I was able to find: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/39249823-add-support-for-application-permission-to-get-a-li
