### ISSUE TITLE
Mute is not in the table of contents

### ISSUE THREAD

**Issue by nkramer** [microsoftgraph/microsoft-graph-docs#5167]
add it to toc.yaml

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b6d5c51-529b-8d06-273b-c04859878b67
* Version Independent ID: d7040fd7-ebb2-d127-1da6-9706a5c941fc
* Content: [call: mute - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/call-mute?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/call-mute.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/call-mute.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dplotnikov** [comment]
@nkramer and @VinodRavichandran I've made a PR, feel free to merge it

**Comment by ananmishr** [comment]
@dplotnikov I'm closing this issue since the PR has been merged in
