### ISSUE TITLE
Slow query

### ISSUE THREAD

**Issue by rvoj** [microsoftgraph/microsoft-graph-docs#5168]
I have experimented with this in the last couple of hours, and found that getting the owners of groups is extremely slow.
Why should I have to wait 10 minutes to get a result for around 3000 groups.
I tried to add $select=id to the query, but it took the same time to finish.
All I need is the user id that is the owner, or null if there is no owner.
I don't need the whole user object, just the id, and the group id in a collection on the group object.
I already have all users and all groups in my database, so I just need a link to make SQL queries on them.
I haven't started on the journey of getting group members yet, but I suspect it will point down to the same rabbit hole as group owners.
One thing we need for our schools, is a quick way do determine who owns groups, and to get the members (at least a count).
Pure statistics really, but very time consuming.
As I have been working with on-premise AD for some time, I recognize the same slow queries to get members of groups from AD.
I thought you had gone forward in that field with Azure, but it seems like it's the same, just with a different data source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c10a6bf-b0f6-37ab-6986-96a88fa74618
* Version Independent ID: 2cc62631-7aeb-d8fd-d074-4b253df340f1
* Content: [List owners - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-list-owners?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/group-list-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
Hi - Can you please provide some additional details about your implementation? There should be no need to make the calls in serial, so moving through 3000 groups shouldn't take that long.

**Comment by jthake-msft** [comment]
Closing issue as no response.
