### ISSUE TITLE
About the default channel "General"

### ISSUE THREAD

**Issue by TedZeng** [microsoftgraph/microsoft-graph-docs#5172]
Hi guys, if I use https://graph.microsoft.com/beta/teams/{id}/channels invoke the channels list(there are a lot of  channels),  is the first result always the "General"  channel??

For example：var resultList = List-ChannelsFromTeam(); 
so is the resultList[0] always specify "General" channel ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1235c480-f924-457c-93ca-29221ba62c9d
* Version Independent ID: e667c977-60ef-a81d-e94b-7eed5061b2c7
* Content: [List channels - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
That's not something we guarantee, it could change at any time.
