### ISSUE TITLE
Policy.ReadWrite.All does not exist

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#5173]
Under Delegated permission, it lists Policy.ReadWrite.All but this permission does not exist in MS Graph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 324650b9-b272-bf7b-c002-2bcb6cf9da84
* Version Independent ID: 03d68e68-a6b5-b809-57c1-72ec8b4755e6
* Content: [Update trustFrameworkPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/trustframework-put-trustframeworkpolicy?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/trustframework-put-trustframeworkpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/trustframework-put-trustframeworkpolicy.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @valnav
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by matteopessina** [comment]
It has been changed to `Policy.ReadWrite.TrustFramework`.
