### ISSUE TITLE
Delegated permissions

### ISSUE THREAD

**Issue by mganeshphani** [microsoftgraph/microsoft-graph-docs#5174]
per the following link delegated permissions are not available
https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=csharp#permissions

but per following link, it is possible
https://docs.microsoft.com/en-us/graph/permissions-reference#calendars-permissions

which is true here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create online meeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=csharp#permissions)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
@mganeshphani  - online meetings is just to create and retrieve Teams Meeting URL for a defined time interval. Calendar APIs are using to create scheduled meetings in people's calendar. Teams Meeting URL creation and retrieval will be planned to be available for delegated permissions in CY19Q3.

**Comment by mganeshphani** [comment]
Thankyou @VinodRavichandran .. we will be waiting for this.
