### ISSUE TITLE
does this also apply for online meetings?

### ISSUE THREAD

**Issue by mganeshphani** [microsoftgraph/microsoft-graph-docs#5175]
we are planning to use following API
https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=csharp#permissions

if i restrict application policy to few set of users, will that apply for online meeting cases as well?
when i said application policy limitation, i mean this
https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca1eed2-d0ca-11de-4f25-f09865605a0f
* Version Independent ID: 9fd423e0-86e4-b7e4-9249-1bacb51e81ad
* Content: [Scoping application permissions to specific Exchange Online mailboxes - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access)
* Content Source: [concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-limit-mailbox-access.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svpsiva** [comment]
No. This is not supported.
