### ISSUE TITLE
Bot listing own messaged

### ISSUE THREAD

**Issue by dgancho** [microsoftgraph/microsoft-graph-docs#5182]
A BOT should be able to list own previously posted messages in a channel (not everyone's, only own) without requesting this special access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b32ca7f9-ea75-d0fd-f887-136e0c9686e3
* Version Independent ID: 6e9b24bc-9869-0b70-8881-3c4aad2bebed
* Content: [Protected APIs in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-protected-apis)
* Content Source: [concepts/teams-protected-apis.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-protected-apis.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
That's a great feature, let's put it on UserVoice.
