### ISSUE TITLE
is this api to create only link? not send meeting to other users?

### ISSUE THREAD

**Issue by mganeshphani** [microsoftgraph/microsoft-graph-docs#5190]
it was not clear from documentation that this is only for teams link creation..
should we still create a calendar meeting and include the teams link in it to get experience like we do in outlook(new items -&gt; teams meeting)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create online meeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
Yes, that's correct. Meeting link creation is Communications (Calling/Meetings) APIs and Event creation is Exchange API. Both have to be combined to achieve the scenario you mentioned.
