### ISSUE TITLE
Removing from O365 group does not remove team ownership

### ISSUE THREAD

**Issue by mmathews123** [microsoftgraph/microsoft-graph-docs#5207]
I've been removed from the O365 group associated with a Team. Verified this via https://portal.azure.com
The Team loads in MS Team and I'm listed as an owner.

How can I remove a specific user from a list of Teams that the person is an owner of?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b4e8438-09f9-b27d-ceed-559d9f142211
* Version Independent ID: dc761c5d-1357-5fdb-f2e3-fd687ef89346
* Content: [Remove owner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-owners?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
If you haven't done so already check out the section on Teams & group membership. https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta Groups treats owners a little differently than Teams, what may have happened is your no longer a member but still an owner, and Teams interprets that as still part of the team, while groups doesn't (but would let you add yourself to the team at any time…).
