### ISSUE TITLE
Azure AD Renew expiring access token using refresh token

### ISSUE THREAD

**Issue by mikeholtkamp** [microsoftgraph/microsoft-graph-docs#521]
According to the documentation an redirect_uri parameter is needed to refresh your access_token. By incident I forgot to send the redirect_uri in a request and that request returned a status 200. So either the documentation is incorrect or this is a api bug

**Comment by dstrockis** [comment]
I think it should only be required on auth code grant requests, not on refresh token. Should probably check the Oauth spec and run a test to confirm.
