### ISSUE TITLE
Wrong docs about OriginalStartTimeZone

### ISSUE THREAD

**Issue by agordeev** [microsoftgraph/microsoft-graph-docs#5210]
Here's what the doc say:
<img width="937" alt="Screenshot 2019-07-23 at 11 23 15" src="https://user-images.githubusercontent.com/2883524/61695557-5fe50b80-ad3c-11e9-94ee-1dc6d0ed8bad.png">
Below there are a list of possible time zone values. However, while testing the API I'm getting this value: "Russian Standard Time", which is not documented.

Article:
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/complex-types-for-mail-contacts-calendar#EventResource
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/complex-types-for-mail-contacts-calendar#DateTimeTimeZoneV2

**Comment by Harini84** [comment]
Kindly refer below links:
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/complex-types-for-mail-contacts-calendar#DateTimeTimeZoneV2

As specified, The TimeZone property can be set to any of the time zones supported by Windows, as well as the following time zones names. See TimeZone for more information.

Timezone link:
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc749073(v=ws.10)

Russian standard time is specified in the above link.
