### ISSUE TITLE
Delete mobileAppContentFile does not work

### ISSUE THREAD

**Issue by portaldotjay** [microsoftgraph/microsoft-graph-docs#5221]
Documentation does not include "microsoft.graph.windowsMobileMSI" in the URI. Tried with and without. 

DELETE https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/eca69c1e-6e93-495a-bcc6-b8c30c579404/contentversions/1/files/3180ec1b-72f8-4b2a-8df8-cc809128008a

RESPONSE

```
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'contentversions'.",
        "innerError": {
            "request-id": "35282043-0966-45e4-b1bb-36ddb9ce05f0",
            "date": "2019-07-23T23:58:51"
        }
    }
}
```

DELETE https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/eca69c1e-6e93-495a-bcc6-b8c30c579404/microsoft.graph.windowsMobileMSI/contentversions/1/files/3180ec1b-72f8-4b2a-8df8-cc809128008a

RESPONSE
```
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/cast/navigation/key/navigation/key with http verb DELETE for request /AppLifecycle/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('eca69c1e-6e93-495a-bcc6-b8c30c579404')/$/microsoft.management.services.api.windowsMobileMSI/contentVersions('1')/files('3180ec1b-72f8-4b2a-8df8-cc809128008a').",
        "innerError": {
            "request-id": "72f98792-3d7d-4b8c-96cb-25874a06e715",
            "date": "2019-07-23T23:58:07"
        }
    }
}

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee053d0-998a-adf7-e2e6-06731e69c0af
* Version Independent ID: e5a1d19f-6903-51d1-8063-4e462472683a
* Content: [Delete mobileAppContentFile - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-mobileappcontentfile-delete?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-apps-mobileappcontentfile-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-apps-mobileappcontentfile-delete.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by max-ott** [comment]
Also tried with the following `types`, neither are working:
- microsoft.graph.mobileLobApp
- microsoft.graph.managedMobileLobApp
- microsoft.graph.androidLOBApp
- microsoft.graph.iosLOBApp

**Comment by triplanedave** [comment]
Thanks. The system is indicating, there is no code that supports this route. This sometimes occurs based on how our documentation is generated. I'll file a bug so it can eventually be cleaned out. The best method to validate an entity creation is by doing F12 developer tools in the browser and seeing the actual calls being made to create an object.
