### ISSUE TITLE
Error delete

### ISSUE THREAD

**Issue by diepvienit** [microsoftgraph/microsoft-graph-docs#5225]
I perform functions to add users, edit users, get users to run successfully. However, when doing the delete function, the data cannot be deleted. The system still runs normally without displaying errors but the data is not deleted. my code:

IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(clientId)
                .WithTenantId(tenant)
                .WithClientSecret(clientSecret)
                .Build();
ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);
GraphServiceClient graphClient = new GraphServiceClient(authProvider);
graphClient.Users[id].Request().DeleteAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523b3456-9ec1-f405-a9f6-cf1e15b5a0b7
* Version Independent ID: a534e0cf-9e6d-5d85-0915-8c817569a989
* Content: [Delete a user - Microsoft Graph API - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delete.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Either this is a service bug, client library bug or a client code bug.  Either way, I don't think this is an issue with the documentation.  For coding/service issues, please file a question on StackOverflow and tag with [microsoft-graph].
