### ISSUE TITLE
Post message to group chat or private chat not working

### ISSUE THREAD

**Issue by simiczhang** [microsoftgraph/microsoft-graph-docs#5242]
It seems post message to "/users/{id}/chats/{id}/messages" would get "UnknownError" ("request-id": "b6173842-c07a-4a2f-8089-6f3c60136fe3) , I understand this is BETA API but it seems it is still not ready?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456c26fc-a47b-9f84-9d55-68cb48aad3fc
* Version Independent ID: 27b8eca1-ad6a-2881-a029-8d392c470b78
* Content: [Create chatMessage - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mfulan** [comment]
I think I may have found the answer to this as I also ran into the same problem.

Turns out if I execute /me/chats/[id]/messages with a POST it fails. But if I execute /chats/[id]/messages (remove the /me) then it succeeds.

**Comment by RamjotSingh** [comment]
You are right. We are working on bringing both API sets to parity but for now /chats will work.

**Comment by wypfl9** [comment]
I get the same error using https://graph.microsoft.com/beta/chats/<chat id>/messages

Invoke-RestMethod : {
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "63506cdd-a619-4953-becc-509c7e1c26e0",
      "date": "2019-12-10T00:13:43"
    }
  }
}
At C:\ps\Office365\Create-TeamsMessage.ps1:165 char:11
+   $Data = Invoke-RestMethod -Headers $authHeader -Uri $apiUrl -Method ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

But it works from Graph Explorer

**Comment by RamjotSingh** [comment]
Folks this issue is closed. No more responses will be provided to this issue. Please open a new issue.

@wypfl9 You app lacks Chat.ReadWrite permissions.
