### ISSUE TITLE
Undeletable Certificates

### ISSUE THREAD

**Issue by flix-** [microsoftgraph/microsoft-graph-docs#5246]
When using certain malformed thumbprints during upload of a certificate the certificate cannot be deleted anymore. Verify by appending "-enc" or "-sign" to thumprint when pushing a cert.

**Comment by dkershaw10** [comment]
@flix - Please provide more details.  Which API are you talking about?  Can you provide a reference to the documentation in question?
Also are you sure that this is an issue with the documentation, or is this an issue with the service? If it's the latter, please close this issue and open a new question on StackOverflow and tage [microsoft-graph].

**Comment by jthake-msft** [comment]
Closed as no more information provided.
