### ISSUE TITLE
Graph Subscriptions Need Far Better Correlation Options

### ISSUE THREAD

**Issue by chassq** [microsoftgraph/microsoft-graph-docs#5248]
When we create a subscription in Graph we should be able to read or list them back to us with the ClientState we added (only seems to be in Read for now) and the type of subscription (not change type) but the resource type. For example there is no way on a subscription it would seem to determine the type of resource the subscription is for, short of parsing the resource value, and making a guess.

**Comment by dkershaw10** [comment]
@piotrci Looks like a new feature request? UserVoice?

**Comment by chassq** [comment]
My vote here is that this is a bug (overlooked) and should be addressed. Not a new "feature". The client state comes back when you call for a single subscription. It should be added to the List subscription function as well. Not only would it save us a trip (and more hits against graph) to get the client state. It would make the overall correlation story consistent with what overall subscription processing should look like.

**Comment by piotrci** [comment]
Yes, it looks like an omission. There is no reason why a property should be returned for a single entity, but not for a list. I will follow up re this.

**Comment by venkateshchepuru** [comment]
Client State is not set for the List Subscription on purpose by design, because subscription collections could be listed by say some other user  (example tenant admin using Subscription.Read.All). It is not desirable to share this Client state information through the Listing API for that user who is not the creator of the subscription.

**Comment by chassq** [comment]
Hey @venkateshchepuru. This does not seem reasonable. The fact is that if I wanted I can go through and GET any one of the subscriptions I list currently. The only thing that not having the Client State in the LIST accomplishes is making us do yet another query to Graph and causes Graph to fulfill yet another query. Does this not seem wasteful to both parties? Client State is my correlation id and I, as a developer , should have the access to do with it as I please. If Client State is trying to be used as some security mechanism then it is not an especially good one. See my same answer in https://github.com/microsoftgraph/microsoft-graph-docs/issues/4807. Bottom-line is we need an effective correlation id. Sounds like Client State is not a correlation id nor a good security mechanism right now. If a security mechanism is required then make one but we also need a good correlation id.

**Comment by piotrci** [comment]
Hi @chassq ,

We plan to remove clientState from any responses, GET or list. for this reason we will not be adding it to the list response.

We will be communicating this breaking change in the future - in the meantime we recommend you adjust your app code to not rely on the clientState property being returned at all.

Thank you.

**Comment by chassq** [comment]
OK sounds good. But can you indicate if any kind of possible CorrelationId will be place on the Subscription (or if there is one today) that we can use to correlate the subscription to a entity on our side? Thanks!
