### ISSUE TITLE
Documents can be enhanced

### ISSUE THREAD

**Issue by mahapatraprabhanjan** [microsoftgraph/microsoft-graph-docs#5249]
It's hard figuring out how to send a custom message when deleting the event to the invitees. Looking at the docs it could have more information about the implementations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9265c344-d87a-cbbe-3dec-90feafc017ca
* Version Independent ID: 47893faf-f604-8a75-4e1f-663722a89631
* Content: [Delete event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-delete?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-delete.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jingo64** [comment]
This is an old issue, but I think is still relevant. The "delete event" endpoint deletes the event, but unlike through Outlook, we do not appear to have control over whether a notification is sent to attendees on delete. We can "decline event" instead, but its not clear whether if I decline an event as the organizer, it cancels it for everyone or not.

**Comment by Harini84** [comment]
https://docs.microsoft.com/en-us/graph/api/event-delete?view=graph-rest-1.0&tabs=http

As documented, Delete event Removes the specified event from the containing calendar.

If the event is a meeting, deleting the event on the organizer's calendar sends a cancellation message to the meeting attendees.
