### ISSUE TITLE
GraphServiceClient doesn't seem to have Applications property as in the sample

### ISSUE THREAD

**Issue by varunpuranik** [microsoftgraph/microsoft-graph-docs#5279]
I am not able to find the Applications object on the GraphServiceClient either in the released or the beta version. 
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/GraphServiceClient.cs
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/blob/master/src/Microsoft.Graph/Requests/Generated/GraphServiceClient.cs

I see the class is partial. Is it defined somewhere else? Is there some other SDK other than Microsoft.Graph, Microsoft.Graph.Core and Microsoft.Graph.Auth that I need? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9081788-2993-0621-059d-e686ea9ae5cb
* Version Independent ID: 6260abb6-0adf-241d-23d8-78632ee20b3f
* Content: [Create Application - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-applications?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/application-post-applications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-applications.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
@jthake-msft Not sure why am I the author of this content.

**Comment by jthake-msft** [comment]
@VinodRavichandran it appears the yaml autho and product is incorrect for this page. I'll raise an issue for this. This issue is for @sureshja

**Comment by davidmu1** [comment]
Doesn't seem like a change to this article is needed. Seems to be an issue with the SDK.

**Comment by Adriana171** [comment]
The Applications object is missing from the Java SDK as well.
