### ISSUE TITLE
SharePoint Graph API - enumerate subsites and hierarchy - not enough data returned

### ISSUE THREAD

**Issue by panjkov** [microsoftgraph/microsoft-graph-docs#528]
Refering to https://graph.microsoft.io/en-us/docs/api-reference/beta/api/subsites_list
How will the SharePoint Graph API handle nested subsites in return collection?

As of now, the subsites_list returns only collection of items that contain only ID and Name of the subsites. The displayed properties do not describe in any way:
-Site URL
-Site hierarchy within site collection.

Any plans to address this, and do you consider this an issue in the API.

**Comment by panjkov** [comment]
This also makes impossible to perform "get site by url" call after I get list of subsites, as the site url is not retrieved when "Lst Subsites" call is performed

**Comment by panjkov** [comment]
Posted the above also as an ide on uservoice here https://officespdev.uservoice.com/forums/224641-general/suggestions/16454263-sharepoint-graph-api-list-subsites-results-shou

**Comment by rgregg** [comment]
Hi @panjkov: You actually get back a lot more information about subsites, but the documentation only shows those two properties. Here's an example of the subsite data we return from the API. I'll use this issue to track updating the docs to show all of the properties we return.

```json
{
    "value": [
        {
            "createdDateTime": "2016-07-21T03:05:59Z",
            "description": "",
            "id": "c5bc4bcc-1a63-4f39-8175-4f789765c0ed,199e6fdb-285e-4de5-a2fb-0ba5640d1d0d",
            "lastModifiedDateTime": "2016-10-18T10:40:59Z",
            "name": "Subsite Name",
            "webUrl": "https://contoso.sharepoint.com/subsite-url",
            "siteCollectionId": "c5bc4bcc-1a63-4a39-8175-4f789765c0ea",
            "siteId": "199e6fdb-285f-4df5-b2fb-0ab1640d1d0d"
        }
}
```

**Comment by rgregg** [comment]
I've updated the example response to be inclusive of these properties in commit a8603b5.

**Comment by panjkov** [comment]
Thanks, @rgregg 
it didn't work for me at all when I posted the issue so I couldn't play with it at the time (I also guessed that it might need to be accessed by expanding some of properties during the call). Now it works as you described and I can confirm it works.
