### ISSUE TITLE
Add sample code for updating different user

### ISSUE THREAD

**Issue by ptelman** [microsoftgraph/microsoft-graph-docs#5282]
Issue:
Add sample code for updating different user. Probably with code sample from:
[https://stackoverflow.com/a/43747507](url)
Article:
https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=csharp#example

**Comment by dkershaw10** [comment]
@davidmu1 Can you add another (HTTP REST) example for patching a specific user (rather than /me).  The platform will automatically pick this up and generate code for your new REST example.

**Comment by davidmu1** [comment]
Added example.
