### ISSUE TITLE
How to get all html content of site pages

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/microsoft-graph-docs#5296]
For SharePoint Pages or News, we want all Html data in a single field similar to sharepoint field "CanvasContent1".
How to get all HTML content of site pages using Microsoft Graph?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54e3e5eb-7666-72ba-b2f4-7db35d292159
* Version Independent ID: 5240b940-e117-278e-7a05-682916369b92
* Content: [SitePage - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/sitepage?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/sitepage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/sitepage.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @rahmit
* Microsoft Alias: **rahmit**

**Comment by sentieo-raghib** [comment]
Dear Microsoft Team, Please provide a solution for this.
