### ISSUE TITLE
assign manager with user.ReadWrite.All

### ISSUE THREAD

**Issue by Ballzer0** [microsoftgraph/microsoft-graph-docs#5304]
it would be really handy to be able to assign managers using the user.ReadWrite.All Permission. The roles here expose a crazy amount of functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b619f6e-e391-ef3d-cd45-682ad87b5a73
* Version Independent ID: 907a4979-7d65-112e-05d1-c2a13fd5f897
* Content: [Assign a manager - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-manager.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Ballzer0** [comment]
further testing reveals that im actually allowed to use this role. This should either be considered a security breach or undocumented.

**Comment by dkershaw10** [comment]
I'll add a note to the topic.  Yes this will work with User.ReadWrite.All if the manager is a user resource.  For back-compat with on premises AD functionality, it is possible to also assign an org contact as a manager - go figure.

**Comment by Ballzer0** [comment]
So the least privileged you need to be for this operation is User.ReadWrite.All. not Directory.ReadWrite.All ?

**Comment by dkershaw10** [comment]
Yes indeed. The PR above should capture that change.

**Comment by dkershaw10** [comment]
Doc updated
