### ISSUE TITLE
"hostedImages" or "hostedContents"

### ISSUE THREAD

**Issue by thchuong-x11** [microsoftgraph/microsoft-graph-docs#5311]
Hello

I am testing this REST API and I have found some incoherence between the documentation and the exposed REST API endpoint.
I have noticed that the hosted images / contents are returned in the JSON (specifically, the preview string) of chat message with the endpoint being "hostedContents". 
For example, one of the URL that I have seen is: https://graph.microsoft.com/beta/teams/3db251ef.../channels/19:...@thread.skype/messages/1...2/replies/1...5/hostedContents/aWQ9eF8w...9pbWdv/$value, whereas the documentation only mentions "hostedImages".

Having believed that the two endpoints were aliases to each other, I have tested the same request by replacing "hostedContents" by "hostedImages". The request yields a HTTP 400 Bad Request instead.

Could you please verify this ?

Thank you very much.

Chuong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce859fe1-e22b-b624-ca74-2b93c9996cf8
* Version Independent ID: 75bc2c14-d5ba-7f06-3279-129b9939e4b6
* Content: [Get chatMessageHostedImage - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessagehostedimage-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/chatmessagehostedimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessagehostedimage-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
Hi - 'hostedContent' is the correct resource/endpoint to use.
