### ISSUE TITLE
URL property is not returned in the JSON of ChatMessageHostedImage

### ISSUE THREAD

**Issue by thchuong-x11** [microsoftgraph/microsoft-graph-docs#5312]
Hello,

Following my trial with hostedImages endpoint in the issue #5311, I have also noticed that the URL property is not returned in the JSON of ChatMessageHostedImage, but only its id.

The request that I have executed is as follow: https://graph.microsoft.com/beta/teams/3db251ef.../channels/19:...@thread.skype/messages/1...2/replies/1...5/hostedContents/aWQ9eF8w...92aWV3cy9pbWdv.

Thank you for your time.

Chuong
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce859fe1-e22b-b624-ca74-2b93c9996cf8
* Version Independent ID: 75bc2c14-d5ba-7f06-3279-129b9939e4b6
* Content: [Get chatMessageHostedImage - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessagehostedimage-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessagehostedimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessagehostedimage-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
Please see this example: https://docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-beta&tabs=http#example-2-get-hosted-content-bytes-for-an-image
