### ISSUE TITLE
Is there any sample of Microsoft Graph available in Java and Maven 

### ISSUE THREAD

**Issue by freelancer6969** [microsoftgraph/microsoft-graph-docs#5314]
Hello, 
I want to implement Microsoft Graph for sending an email.

The sample which I am seeing [https://github.com/microsoftgraph/console-java-connect-sample](url) Here is in Gradle.

But, I want to use the Maven instead of Gradle.

Please let me know if any samples are available for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e4ed6e9-9444-39d0-2a45-920ca4eecd6c
* Version Independent ID: 6e4d2087-45ae-806c-5be6-25c880c8bc12
* Content: [Install the Microsoft Graph SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/sdk-installation#feedback)
* Content Source: [concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/sdk-installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
https://docs.microsoft.com/graph/tutorials/java uses Maven.

**Comment by freelancer6969** [comment]
@jasonjoh  
Hi jason,

Thanks for the reply.

I went to https://docs.microsoft.com/en-us/graph/tutorials/java

After Clicking on **Begin** I get Below Command



`mvn archetype:generate -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeGroupId=org.apache.maven.archetypes -DgroupId=com.contoso -DartifactId=graphtutorial -Dversion=1.0-SNAPSHOT`

After executing the command I get below error 

`[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (C:\Users\hp\Desktop\GraphApiNew). Please verify you invoked Maven from the correct directory. -> [Help 1]`

Do I need any `pom.xml` to be stored at the directory where I am executing the command ??

**Comment by freelancer6969** [comment]
@jasonjoh 

I went to the repository` https://github.com/microsoftgraph/msgraph-training-java` 

Can you please tell me Which Code Should I use for implement send mail functionality

**Comment by jasonjoh** [comment]
That sample only lists calendar events, but it should be a good starting point. You'll need to add code to send mail.

**Comment by jasonjoh** [comment]
> Do I need any pom.xml to be stored at the directory where I am executing the command ??

No, you do not. I just tested it, note my Maven version, maybe you're using a different one?

```
C:\Source\temp\javatest>dir
 Volume in drive C is OSDisk
 Volume Serial Number is D682-6EF0

 Directory of C:\Source\temp\javatest

07/31/2019  10:11 AM    <DIR>          .
07/31/2019  10:11 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  857,031,938,048 bytes free

C:\Source\temp\javatest>mvn archetype:generate -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeGroupId=org.apache.maven.archetypes -DgroupId=com.contoso -DartifactId=graphtutorial -Dversion=1.0-SNAPSHOT
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.1.0:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.1.0:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.1.0:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] Archetype [org.apache.maven.archetypes:maven-archetype-quickstart:1.4] found in catalog remote
[INFO] Using property: groupId = com.contoso
[INFO] Using property: artifactId = graphtutorial
[INFO] Using property: version = 1.0-SNAPSHOT
[INFO] Using property: package = com.contoso
Confirm properties configuration:
groupId: com.contoso
artifactId: graphtutorial
version: 1.0-SNAPSHOT
package: com.contoso
 Y: : y
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: maven-archetype-quickstart:1.4
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: com.contoso
[INFO] Parameter: artifactId, Value: graphtutorial
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Parameter: package, Value: com.contoso
[INFO] Parameter: packageInPathFormat, Value: com/contoso
[INFO] Parameter: package, Value: com.contoso
[INFO] Parameter: groupId, Value: com.contoso
[INFO] Parameter: artifactId, Value: graphtutorial
[INFO] Parameter: version, Value: 1.0-SNAPSHOT
[INFO] Project created from Archetype in dir: C:\Source\temp\javatest\graphtutorial
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43.292 s
[INFO] Finished at: 2019-07-31T10:12:52-04:00
[INFO] ------------------------------------------------------------------------

C:\Source\temp\javatest>mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00)
Maven home: C:\Program Files\Maven\bin\..
Java version: 12.0.1, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-12.0.1.12-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

C:\Source\temp\javatest>
```
