### ISSUE TITLE
Only plain text?

### ISSUE THREAD

**Issue by ganlbarone** [microsoftgraph/microsoft-graph-docs#5315]
looks like the body of the message can only be plain text. If you try to inject links via a tags in html it sends them through as plain text. 

If the body only supports plain text and you cant do html I think thats rather limiting. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 862443a6-0ffd-9214-efef-51ea33b67356
* Version Independent ID: 811b0abd-663d-266b-fbe1-25ded0910faa
* Content: [sendCustomNotificationToCompanyPortal action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagement-sendcustomnotificationtocompanyportal?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-shared-devicemanagement-sendcustomnotificationtocompanyportal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-shared-devicemanagement-sendcustomnotificationtocompanyportal.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rolyon** [comment]
Hi @ganlbarone 
Thanks for the feedback. We checked with the team. That is correct. Currently, custom notifications only support plain text.

**Comment by rolyon** [comment]
I'm going to close this issue, but you can re-open if you have any additional feedback.
thanks
