### ISSUE TITLE
Documentation for function s in Excel REST API

### ISSUE THREAD

**Issue by sanjaybhagia** [microsoftgraph/microsoft-graph-docs#532]
Is there any documentation around using functions in Excel REST api?  
The only example i could find it for pmt function (/workbook/functions/pmt)

I have tried some other functions but didnt manage to get it working, even throuhkgh i tried to keep the parameters as ee have in Excel.

Thanks

**Comment by sumurthy** [comment]
The documentation functions is limited given the number of functions available. We recently added a couple of samples under workbook resources. Look under functions section. 
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/workbook.md 

If you have a specific function you'd like to use, please let us know and I can add the sample.
