### ISSUE TITLE
Creating Managed Device through Graph API

### ISSUE THREAD

**Issue by udesh210479** [microsoftgraph/microsoft-graph-docs#5321]
I'm trying to register my device using the above API and it fails with error "No OData route exists that match template ~/singleton/navigation with http verb POST for request /DeviceFE/StatelessDeviceFEService/deviceManagement/managedDevices." 
Article on the net suggest other way around, https://www.oipapio.com/question-3287928 (Cant create managed device, using graph API.)

Q : Can I register an personal device in Intune using Graph API?

If this is not achievable, then do update the documentation as this is misleading or add some note that helps developers not to make an attempt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04504a62-d768-a27c-d4f9-64092a6b2edd
* Version Independent ID: 29741af4-f851-5a0c-3eca-c836120f5172
* Content: [Create managedDevice - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-create?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
You cannot create a new managed device object.  You must enroll a device, and Intune creates the managed device object as part of enrollment.
