### ISSUE TITLE
wrong example in javascript add member to group

### ISSUE THREAD

**Issue by alina-pavaluc** [microsoftgraph/microsoft-graph-docs#5324]
The content for the post request should be directoryObject, not {directoryObject : directoryObject}. Using the example provided by this documentation, an error is given: "Request_BadRequest: An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Closing this as the issue was fixed in the docs.
