### ISSUE TITLE
List Item Attachments

### ISSUE THREAD

**Issue by gi-joe-moto** [microsoftgraph/microsoft-graph-docs#5325]
How do you add attachments to list items?  I don't see a way to do it via the Graph API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7a3906-32dd-fab9-a6f4-a5f8e55429ce
* Version Independent ID: 088ac63e-886e-71f2-bc9b-36f25f93305a
* Content: [Create a new entry in a SharePoint list - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-create?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by bdv1234** [comment]
any update on this. Is this integrated to Java Graph SDK ?
