### ISSUE TITLE
AppRole : Important: This functionality is disabled in the current release.

### ISSUE THREAD

**Issue by scharette** [microsoftgraph/microsoft-graph-docs#5338]
Important: This functionality is disabled in the current release.
Does this mean that the functionality is not available in version 1.0 or it means its disabled in the Beta version of the API ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73755ce0-d3f9-d10f-7723-a8db055828af
* Version Independent ID: d68663e4-2d2f-898f-07a2-6748419cdf7b
* Content: [appRole resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0#feedback)
* Content Source: [api-reference/beta/resources/approle.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/approle.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @sumurthy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by greigs** [comment]
Same question!

**Comment by jdelforno** [comment]
Got this working. Use a unique valid user generated ID.

PATCH operates as a PUT.

You must include the previous roles in the PATCH, otherwise it assumes you're trying to delete them. 

You must set isEnabled to FALSE prior to removing it completely. 

Removing an appRole, deletes the association on the Enterprise Application Users / Groups.

**Comment by greigs** [comment]
Had a call with Microsoft about this. They confirmed that the beta appRoles functionality was working but then became broken. They are working on it. The message should change once it is fixed and it is getting closer to GA.

**Comment by jstallm** [comment]
Is this functionality broken today? Where can we view more information about this? Above makes it appears this is an ongoing issue. Having errors running patch.

**Comment by jstallm** [comment]
I read on this page

> This functionality is disabled in the current release.

Does that mean I cannot PATCH update and add a new element to appRoles currently?

**Comment by jdelforno** [comment]
> I read here https://docs.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-beta
> 
> > This functionality is disabled in the current release.
> 
> Does that mean I cannot PATCH update and add a new element to appRoles currently? If it is disabled, how exactly does microsoft expect developers to add custom new roles to applications which are created in azure AD?

Thank you for the down vote for no reason @jstallm 

We have working code in both powershell and python. The details above will prevent you from making PATCH statements unless you follow those 3 rules. 

I'd suggest you give it a shot in future prior to casting a vote ;)

**Comment by jstallm** [comment]
> > I read here https://docs.microsoft.com/en-us/graph/api/resources/approle?view=graph-rest-beta
> > > This functionality is disabled in the current release.
> > 
> > 
> > Does that mean I cannot PATCH update and add a new element to appRoles currently? If it is disabled, how exactly does microsoft expect developers to add custom new roles to applications which are created in azure AD?
> 
> Thank you for the down vote for no reason @jstallm
> 
> We have working code in both powershell and python. The details above will prevent you from making PATCH statements unless you follow those 3 rules.
> 
> I'd suggest you give it a shot in future prior to casting a vote ;)

Im not exactly sure why I downvoted you. I removed it though. Also, I believe I have figured out the issue to my particular problem. I was passing in a not-accepted attribute as part of the element.

**Comment by psignoret** [comment]
This functionality is currently available in both beta and v1.0.
