### ISSUE TITLE
TeamID in header vs. body

### ISSUE THREAD

**Issue by ofunk** [microsoftgraph/microsoft-graph-docs#5347]
Can you please explain how to retrieve the teamID after creation in header vs. in all other functions in body. like create group or team from group.
apps like Powerapps cannot read header info in variables -- so having a teamID in header is difficult to retrieve.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
I don't believe there is a way -- since this is a standard REST pattern, I suggest passing this feedback along to the Powerapps team.

**Comment by ofunk** [comment]
Hi Nick,

please have another look at it like create group or create team from group
https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-beta&tabs=http

the response of groupID is in the body section not in header. so it is only the create team function which has the teamID in header and not in body -- please review and reopen the ticket. thx in advance

**Comment by nkramer** [comment]
The difference between these two APIs is POST /groups creates the group synchronously – it doesn't return until the group is created. POST /teams is the opposite – it takes a while to create a team, and the API call returns before the team is done being created, hence the different pattern.
