### ISSUE TITLE
TeamID in header vs. body #2

### ISSUE THREAD

**Issue by ofunk** [microsoftgraph/microsoft-graph-docs#5349]
Hi Nick, my last request 2h ago might not have been precise enough.

POST https://graph.microsoft.com/beta/teams
returns in response

*HTTP/1.1 202 Accepted
*Content-Type: application/json
*Location: /teams/{teamId}/operations/{operationId}
*Content-Location: /teams/{teamId}
*{
*}

which seems not to match std REST api pattern. rather more the body section needs to contain variables or responses for further use. please compare the following "response" body and header 

POST https://graph.microsoft.com/beta/groups

*HTTP/1.1 201 Created
*Content-type: application/json

*{
	 "id": "45b7d2e7-b882-4a80-ba97-10b7a63b8fa4",
*}

which allows to use the response "body" section in other functions or environments like PowerApps etc

this seems to be a bug from my perspective in "create team f()"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
We're following the Microsoft OneAPI REST guidelines, see https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#13-long-running-operations . I sympathize that this is awkward to use in Flow, but that needs to be taken up with the Flow team.
