### ISSUE TITLE
CreateUser Javascript example should not create the object when calling the post method

### ISSUE THREAD

**Issue by joaoaguiam** [microsoftgraph/microsoft-graph-docs#5356]
The create user javascript example should not send create an object in the post method but just send the user instead.

Instead of: 
`let res = await client.api('/users')
	.post({user : user});`

Should be: 
`let res = await client.api('/users')
	.post(user);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrueastman** [comment]
Fixed with https://github.com/microsoftgraph/microsoft-graph-docs/pull/5533
