### ISSUE TITLE
revokeSignInSessions returns a 200 OK

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#5359]
Per docs, this API should return a 204 No content if successful.  However it returns 200 OK with a boolean status parameter (which is always set to true :)).
This is a service bug and needs to be fixed.  In the meantime, please update the Known Issues topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4662c3f7-8566-09b3-962c-2cfcccfcfc2f
* Version Independent ID: 1cdc7db2-7c2c-9b23-16f7-05e76f588f6c
* Content: [user: revokeSignInSessions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-revokesigninsessions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-revokesigninsessions.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
NOTE:  this came from a customer that contacted Microsoft through Support.

**Comment by davidmu1** [comment]
Added to known issues and a note was added to this article.
