### ISSUE TITLE
SharePoint Mobile App and Graph Error

### ISSUE THREAD

**Issue by Holden15** [microsoftgraph/microsoft-graph-docs#5364]
Issue: We have deployed a SPFx to a site that includes using MSGraphClient to get a person's information and to get images from a document library.  When we access the site on the SharePoint Mobile App (happens on both iOS and Android), we get an error when we try to do any graphClient get().

The first is when we try to get a user:

    public getMe(graphClient: MSGraphClient): Promise<MicrosoftGraph.User> {
        return graphClient.api(`/me`).get()
    }

We then tried getting an image from a document library:

    public getRevenueSourceThumbnailsForBranch(branchName: string, graphClient: MSGraphClient): Promise<MicrosoftGraph.Thumbnail[]> {
        let branchWithUnderscores: string = _.startCase(branchName).replace(/ /g,"_");

        return graphClient.api(`drives/${kRevenueSourcesDriveIDProd}/root/children?filter=startswith(name, '${branchWithUnderscores}')`).get()
            .then((result: any) => {
                let driveItems: MicrosoftGraph.DriveItem[] = result.value;

                let promises: any[] = [];

                for (let driveItem of driveItems) {
                    promises.push(this._getThumbnailForDriveItem(driveItem, graphClient));
                }

                return Promise.all(promises)
                    .then((results: any[]) => {
                        return results;
                    });
            });
    }

Both calls result in an error (we put the error in a dialog since we can't access the console):

<img width="414" alt="20190805_214340757_iOS" src="https://user-images.githubusercontent.com/43765678/62497080-7f4e5080-b7a0-11e9-9e93-b3411968a687.png">

I suspect this is an issue any time MSGraph is used in SharePoint Mobile App.

EDIT:  We refactored the code and removed MSGraph from the application and it works fine in the SharePoint Mobile App, so it was the MSGraph calls that were causing the issue.

**Comment by ificator** [comment]
@Holden15 are you able to get a trace of the calls being made to Graph? It would be useful to see the status code associated with the request sent to Graph, along with the `request-id` and `date` headers from the response.

**Comment by Holden15** [comment]
@ificator Its in the app itself so there is no console log.  I can look into adding more data to the dialog I display when it happens.
