### ISSUE TITLE
Need end-to-end solution

### ISSUE THREAD

**Issue by davidekarasek** [microsoftgraph/microsoft-graph-docs#5365]
Where can I find an end-to-end .Net API solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
We have a ton of .Net samples.  Not sure any are full E2E, but the Contoso airlines one might be.
Here's the list of C# samples
https://developer.microsoft.com/en-us/graph/gallery/?filterBy=Samples,ASP.NET,C%23
