### ISSUE TITLE
Any road mapping indication for this coming out of Beta?

### ISSUE THREAD

**Issue by WyldLynx** [microsoftgraph/microsoft-graph-docs#5369]
It would be great to know/understand how long the $value segment on messages will stay in beta?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7cb05e-2711-7152-a596-6a057272d459
* Version Independent ID: 97b9b22a-88f1-748f-49bb-32c7d8f7b35f
* Content: [Get MIME content of a message - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-mime-message#feedback)
* Content Source: [concepts/outlook-get-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-get-mime-message.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@svpsiva , any comment?

**Comment by svpsiva** [comment]
This feature is now available in v1.
