### ISSUE TITLE
How to create notification with filter by singleValueExtendedProperties

### ISSUE THREAD

**Issue by Misiu** [microsoftgraph/microsoft-graph-docs#5373]
There is an option to append filter when creating subscriptions. This works great when You, for example, filter mails by subject, but I can't build a filter that will notify me when an email that has a specific singleValueExtendedProperty gets updated.

This works fine: $"users/{user.Id}/mailFolders('sentitems')/messages?$filter=subject eq 'Test'"
but when I try to filter by singleValueExtendedProperties I get no notifications.

My filter looks like this:
$"users/{user.Id}/mailFolders('sentitems')/messages?$filter=singleValueExtendedProperties/Any(ep: ep/id eq 'String {{1f5657a1-f16a-493e-9baf-461f9e2218b7}} Name MyId' and ep/value ne null)"
Subscription gets created (I see request to my endpoint), but I get no notifications.

Is it even possible to filter by singleValueExtendedProperties inside subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks#feedback)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Misiu** [comment]
@piotrci any updates?

**Comment by Misiu** [comment]
@piotrci any updates?

**Comment by piotrci** [comment]
Witam @Misiu ,
@svpsiva can provide clarification here.

**Comment by Misiu** [comment]
@piotrci @svpsiva any chance to get an update on this? Right now I must query graph to check if the message has specific singleValueExtendedProperty, having the ability to add a filter (like I described in my question) would be really helpful and would allow me to reduce the number of request to MS Graph by a half!

**Comment by Misiu** [comment]
@svpsiva any updates?

**Comment by tfrancois** [comment]
Also interested in knowing if there are any updates to this question? Can someone from Microsoft please advise/respond?

**Comment by baywet** [comment]
Closing the following issue as this is a feature request and not an issue with the documentation at the moment. There is a request to support that functionality [here](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/31791508-allow-ms-graph-api-messages-delta-to-include-sing) please go ahead and upvote it if this is something you need.
Also: this is where we will keep the community updated on the request.
