### ISSUE TITLE
Clarify availability of this header

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/microsoft-graph-docs#5374]
This page has a note stating that the header applies only the beta endpoint.

A [blog post](https://developer.microsoft.com/en-us/office/blogs/announcing-immutable-id-for-outlook-resources-in-microsoft-graph/) indicates it is available on v1.0. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dc8516-103a-7df2-2685-1ce9045941b5
* Version Independent ID: 90ebf4ab-1563-4a6d-d184-c91159352366
* Content: [Get immutable identifiers for Outlook resources - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-immutable-id)
* Content Source: [concepts/outlook-immutable-id.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-immutable-id.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Misiu** [comment]
@jasonjoh any updates?

**Comment by jasonjoh** [comment]
Yep sorry. Immutable ID is now available on the v1 endpoint. Will work on updating the doc.

**Comment by jasonjoh** [comment]
And silly me, I forgot that I already updated this topic to remove the "beta only" text (in September!)

**Comment by Misiu** [comment]
@jasonjoh thanks :)
