### ISSUE TITLE
Add guests to Microsoft Teams using graph

### ISSUE THREAD

**Issue by csnarain** [microsoftgraph/microsoft-graph-docs#5375]
I'm trying to add a guest to one of the teams in MS Teams using graph api. I first create and send an invite which the guest is receiving on their side and following the instructions. What value should I give for "inviteRedirectUrl"? I tried giving "teams.microsoft.com" but this one prompts the guest to create a free teams account with a new organization as input. The guest eventually lands up in a different team altogether than the invited one. Everything works smoothly when the guest is added as a member from within the Teams App. What could be the issue here?

**Comment by Prasad-MSFT** [comment]
@csnarain 
 inviteRedirectUrl is the URL that the user will be redirected to after redemption.
Could you please try to give "inviteRedirectUrl": "https://myapp.contoso.com" as mentioned in below doc and see if it works?
https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-beta&tabs=http#request

**Comment by csnarain** [comment]
@Prasad-MSFT - This question was posted more than 2yrs ago. We somehow resolved it at that time and unfortunately I don't remember what I did to fix it. If required you can close this thread.

**Comment by Prasad-MSFT** [comment]
@csnarain ,Thanks for the confirmation.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
