### ISSUE TITLE
showInAddressList propery always null

### ISSUE THREAD

**Issue by Oleksa126** [microsoftgraph/microsoft-graph-docs#5380]
Issue:
 i want get from graph api showInAddressList propery but it`s null although in Exchange admin center i set false in checkbox
![image](https://user-images.githubusercontent.com/18749256/62610635-bf324680-b90c-11e9-9502-55539f172efb.png)
![image](https://user-images.githubusercontent.com/18749256/62610689-d2451680-b90c-11e9-9e06-5711208bbfc8.png)
![image](https://user-images.githubusercontent.com/18749256/62610705-d83af780-b90c-11e9-8f67-56095e260f72.png)

**Comment by svpsiva** [comment]
@Oleksa126 Can you share the API that was used to generate the json output?

**Comment by thewruck** [comment]
I am having the same trouble. I am calling this via C# that I forked from one of the Microsoft examples.
                    Microsoft.Graph.IGraphServiceUsersCollectionPage users = await graphServiceClient.Users.Request().Select("id, AccountEnabled, GivenName, ShowInAddressList, onPremisesExtensionAttributes, MobilePhone, Surname, Department, Country, UserType, businessPhones, PasswordProfile, PasswordPolicies, displayName,UserPrincipalName,assignedLicenses").GetAsync();

**Comment by lance-mccluskey** [comment]
Any update on this? The call shows null for me even when the user is supposed to be on the global address list.

**Comment by Alex-JTI** [comment]
Via AzureAD powershell this value is also null so it's not graph issue.

**Comment by ajhosek** [comment]
Still seems like an issue to me, wanted to use this property and it is still returning null.

**Comment by tako-0** [comment]
I got the same issue

**Comment by abheek-das** [comment]
This information seems to be coming from Identity/Directory Services. Adding @davidmu1 to help on this one.

**Comment by davidmu1** [comment]
The issue has been communicated to engineering. No immediate change identified for the page. The page will be updated when information becomes available. For future questions related to the product, please ask your question at https://aka.ms/askgraph. Closing the issue.
