### ISSUE TITLE
ListItem webUrl invalid

### ISSUE THREAD

**Issue by Mhbuur** [microsoftgraph/microsoft-graph-docs#5381]
Issue:
I'm not sure where to report this issue really - please point me in the right direction if I'm wrong :-)

It seems the format of ListItem webUrl is not supported anymore. The Url is not leading to a display of the list item, but instead results in a download of a blank file named e.g. "1_.000". 

Article:
https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0

**Comment by mimidotsuser** [comment]
This is not really Graph related issue. A list item will require a display form reference. 
Kindly refer to a similar answer on [Stack Exchange here ](https://sharepoint.stackexchange.com/questions/205872/properties-listitem-url-inside-an-event-receiver-is-working-well-for-discussion?answertab=votes#tab-top) on a related SharePoint question. Hope that answer's the question.

**Comment by Mhbuur** [comment]
That makes sense, thanks (What confused me is that this actually has been working fine for a long time).
