### ISSUE TITLE
Java SDK does not have concept of chat messages

### ISSUE THREAD

**Issue by PaulWoods4422** [microsoftgraph/microsoft-graph-docs#5382]
The Java example is not in the beta SDK - no IChatMessageCollectionPage  or ChatMessage types.  Also the channel object does not have a messages() method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a9873-c692-64f3-6185-d4177e5640db
* Version Independent ID: 6e39496f-94cc-2daf-17fe-f5a2590d2327
* Content: [Get channel message - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-get-message.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
SDK issue?

**Comment by darrelmiller** [comment]
@PaulWoods4422  We don't yet have a beta SDK for Java.  If you could open an UserVoice request for this, it would be very helpful  https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests

We probably shouldn't generate Java snippets in the docs for beta until we do... oops.

**Comment by darrelmiller** [comment]
We will be taking the Java snippets out of the beta reference docs until we get a Java Beta SDK available.  Hopefully that shouldn't be too long, most of the work is already done.
