### ISSUE TITLE
Sending an invite for a Teams Guest

### ISSUE THREAD

**Issue by csnarain** [microsoftgraph/microsoft-graph-docs#5383]
Has anyone tried to invite a guest to a Teams team using this API? I tried using this api with redirectUrl set to "teams.microsoft.com", and sent the invite. The invitation process is forcing the user to create a new Teams account in a different organization and eventually the guest lands up in a team org that's different from the one he/she was invited to.

**Comment by v-chetsh** [comment]
@csnarain - Could you please share the API documentation URL which you are referring.
Also could you please share the repro steps so that we can try it from our end.

**Comment by v-chetsh** [comment]
@csnarain - Could you please share the details of your implementation?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
