### ISSUE TITLE
Incorrect C# Syntax In Code Block

### ISSUE THREAD

**Issue by vanderby** [microsoftgraph/microsoft-graph-docs#5387]
Under "Overview of the migration steps", step 4, "Change:" code block there is "=\&gt;" as well in step 5, "To do so, change:" code block is a "=\&gt;".

You need to remove the \ from the code block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c493be74-c959-d3f5-574d-786680fab1e9
* Version Independent ID: aa944269-7151-622a-1968-2b473ee0048c
* Content: [Migrate Azure AD Graph .NET apps to Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-client-libraries#overview-of-the-migration-steps)
* Content Source: [concepts/migrate-azure-ad-graph-client-libraries.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/migrate-azure-ad-graph-client-libraries.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dplotnikov** [comment]
@dkershaw10 please merge the PR and feel free to close this issue

**Comment by dkershaw10** [comment]
Thanks @dplotnikov - I've approved the PR.

**Comment by dkershaw10** [comment]
Closing as the associated PR is merged.
