### ISSUE TITLE
What does id refer to in the task details body?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [microsoftgraph/microsoft-graph-docs#539]
```
{
  "description": "description-value",
  "previewType": "previewType-value",
  "completedBy": "completedBy-value",
  "references": {
  },
  "checklist": {
  },
  "id": "id-value"
}
```

What does `id` property [here](https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/beta/api/taskdetails_update.md) is referring to? I am already passing the `id` of the task in the url.

**Comment by marych** [comment]
It refers to the task id as per https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/taskdetails.md. I created pull request 647 to correct the sample as id is read-only and shouldn't be needed for updates.

**Comment by Lauragra** [comment]
It looks like this issue is resolved so closing for now. Feel free to reopen if you have additional questions. Thanks.
