### ISSUE TITLE
List calls and Online meetings of employees in an organisation

### ISSUE THREAD

**Issue by asitha1987** [microsoftgraph/microsoft-graph-docs#5394]
Is there an API to retrieve list of Calls and Online meetings of employees in an organisation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d091176-d55a-e9cf-ac12-96e010f60985
* Version Independent ID: 57c00459-3fa7-1610-e327-2374c1613bdf
* Content: [call resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/call.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rugt0r** [comment]
If you mean real-time data of all the ongoing calls then no.

We need this information too for call tracking and user presence purposes. We are trying to improvise by having a bot which all calls will go through, but we still don't get all the information we need (participants, tracking transfers) and it's not a great solution.

**Comment by asitha1987** [comment]
I didn't mean realtime data. I want details like call duration, start time, end time, participants of the meeting, call list for a specific date, meeting list for a specific date, etc.

**Comment by 0xVesion** [comment]
@asitha1987  You can try to achieve your goal by subscribing to the resource `/communications/callRecords` and then calling `/communications/callrecords/{id}` to receive a detailed call record including the start and end times. These endpoints are only available in the graph beta and there is a noticeable delay (about 5 minutes) until the call records webhook is called after ending a call.

**Comment by 0xVesion** [comment]
@asitha1987 This is the link to the official docs page 
https://docs.microsoft.com/en-us/graph/cloud-communications-callrecords

**Comment by lovingjo** [comment]
@0xVesion Hi Vincent, I got Error when calling API https://graph.microsoft.com/beta/communications/calls/
"code": "UnknownError",
"message": "{\"errorCode\":\"7503\",\"message\":\"Application is not registered in our store.\",\"instanceAnnotations\":[]}"
Do you know how to resolve it?

Does the API "https://graph.microsoft.com/beta/communications/calls/" return all the calls log?
Do I have to give a specific id for this API?

**Comment by 0xVesion** [comment]
@lovingjo unfortunately there is no such API at the moment. You really need to supply the id of a specific teams call. By subscribing to the `/communications/callRecords` endpoint you can get a notification after a call has been ended with its id.

**Comment by 0xVesion** [comment]
@lovingjo @asitha1987  I created a feature request over on uservoice. If you think that my feature description matches your needs you can go ahead and vote for it :)
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/40431649-api-for-retrieving-teams-call-records-more-easily

**Comment by JonasDewit** [comment]
> @lovingjo unfortunately there is no such API at the moment. You really need to supply the id of a specific teams call. By subscribing to the `/communications/callRecords` endpoint you can get a notification after a call has been ended with its id.

@0xVesion, is the id of the callRecord the same as the id of the call?

**Comment by 0xVesion** [comment]
@JonasDewit callRecord == call as far as I'm concerned → yes

**Comment by JonasDewit** [comment]
@0xVesion, thanks. I can't get it to work though: I've got a bot that joins an Online Meeting and returns a call id. However, callRecords endpoint returns a 404, NotFound when I use this call id.

My understanding, so far, is that if multiple people join an Online Meeting, there will be multiple call ids. However, the callRecords endpoint does not seem to recognise those.

It does work with the id that is provided in the call back by the subscription service.

Is there another way to get the callRecord id for a specific Online Meeting?

**Comment by faizan1990** [comment]
According to the documentation here: https://docs.microsoft.com/en-us/graph/api/call-list-participants?view=graph-rest-1.0&tabs=http

It says neither delegated nor application permissions are supported. How am I supposed to use it then?

**Comment by JonasDewit** [comment]
> According to the documentation here: https://docs.microsoft.com/en-us/graph/api/call-list-participants?view=graph-rest-1.0&tabs=http
> 
> It says neither delegated nor application permissions are supported. How am I supposed to use it then?

It says the application doesn't need any specific permissions, not that it's not supported

**Comment by Jame-Stitel** [comment]
> @lovingjo unfortunately there is no such API at the moment. You really need to supply the id of a specific teams call. By subscribing to the `/communications/callRecords` endpoint you can get a notification after a call has been ended with its id.

Sure, but how to get the past calls? Not only the future ones as they come..

**Comment by 0xVesion** [comment]
@Jame-Stitel As far as I know there is still no support for that in the graph api.

**Comment by rzechu** [comment]
I see theres still no support...
Schools / Universities need to check students attendance during online meetings/classes. I know there's option to download report after meeting but If lecturer forget do this, the report is gone

**Comment by enkelmedia** [comment]
Since a couple of weeks there is the MeethingAttendanceReport that can be fetched after the meeting.

https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&tabs=csharp#example-6-retrieve-the-attendance-report-of-a-meeting

We're building a integration where we would like to keep track of how many participants the meeting has in real time, this does not seem to be possible... or have anyone managed to do this?

**Comment by samljac** [comment]
Hello, is there any updates on this subject? 
Thank you.
