### ISSUE TITLE
What is limit of attendees for msgraph create event API

### ISSUE THREAD

**Issue by quincycs** [microsoftgraph/microsoft-graph-docs#5395]
Hi 

In one API call, what is the limit of how many attendees can be created on the event?

Is it 500?  I saw this article, https://support.office.com/en-gb/article/scheduling-meetings-with-hundreds-of-attendees-f8cce35d-673e-41a0-8aea-dc5331bb60ed

But I’m afraid the article may be out of date.  If the limit is defined by O365, perhaps you can still describe where to find the limit imposed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ff7ff9f-c955-c32f-756c-59e9165f3fa3
* Version Independent ID: c181ecf0-6586-9b36-20a8-f2f1e1381397
* Content: [Create event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@quincycs , thank you for your question. I'll try to get some clarification, and will reply when I hear back.

**Comment by angelgolfer-ms** [comment]
@quincycs , the 500 limit is current. You can also take a look at the section "Sending limits" in the article [Exchange Online limits](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-limits#sending-limits).
I added this information to the event and message topics via PR #5449 . The doc update will go live within the next day.
