### ISSUE TITLE
Trust Framework policy permissions should just be Policy permissions

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#5398]
Policy permissions, in some cases will span different APIs, so really there should just be a Policy permissions section with the different supported variants.
Also the name and description for Policy.Read.All is wrong and does not match the actual Policy.Read.All permission definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#trust-framework-policy-permissions)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Same for the Feature rollout capability.

**Comment by Jackson-Woods** [comment]
Permission strings have been updated to match Azure AD portal. Still working on policy content organization.

**Comment by Jackson-Woods** [comment]
Closing in light of #5633
