### ISSUE TITLE
Create place

### ISSUE THREAD

**Issue by khaullen** [microsoftgraph/microsoft-graph-docs#5400]
How should places be created?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227ceac7-ddb7-01ff-a42b-4d71394d3a74
* Version Independent ID: 44cfac3b-3d9f-0f26-5f50-e695da0fcea7
* Content: [place resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/place.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vrod9429** [comment]
A place should be created using this cmdlet. It needs to be created by the tenant. https://docs.microsoft.com/en-us/powershell/module/exchange/mailboxes/new-mailbox?view=exchange-ps

**Comment by EliasKaplan** [comment]
Room/Resource creation hasn't changed, few option to create the rooms: ECP, O365 Admin center, powrshell, ...
