### ISSUE TITLE
Group visibility values should not be lower case

### ISSUE THREAD

**Issue by MortenBroerup** [microsoftgraph/microsoft-graph-docs#5402]
The description of the visibility property says that the possible values are: "private", "public", or "hiddenmembership".
So does the Value column under the Group visibility options headline.
Everywhere else I have seen, these values are not lower case. E.g. "Private", not "private".
Getting a group that was created with visibility "private" returns visibility "Private".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@MortenBroerup I think when setting the value, it's case insensitive, however it is stored as a capitalized value.

**Comment by MortenBroerup** [comment]
And since it is effectively an `enum`, although string based, it is likely that someone will use case sensitive comparison or a `switch/case` construction with the lower case values, and thus will get unexpected results.

**Comment by davidmu1** [comment]
Changed the values to uppercase.

**Comment by MortenBroerup** [comment]
Looking elsewhere, it looks like Hiddenmembership should be HiddenMembership.
