### ISSUE TITLE
403 Forbidden for Post

### ISSUE THREAD

**Issue by aakashb01** [microsoftgraph/microsoft-graph-docs#5404]
Issue: I am following the article https://docs.microsoft.com/en-us/graph/extensibility-schema-groups to register new SchemaExt, but I keep getting "403 Forbidden". I get the same error on Graph Explorer (logged in with Global Admin with all permissions) and on Postman with AccessToken

Article: https://docs.microsoft.com/en-us/graph/extensibility-schema-groups

**Comment by jthake-msft** [comment]
What permissions have you requested in your application? as per this document, https://docs.microsoft.com/en-us/graph/extensibility-overview you will require the appropriate resource object read write permissions there.

**Comment by aakashb01** [comment]
I have provided all possible permissions . Please check screenshot.
<img width="768" alt="1" src="https://user-images.githubusercontent.com/42469570/63025031-00ef5e00-bec6-11e9-8053-f554780252e6.png">
