### ISSUE TITLE
API does'nt return OneNote documents

### ISSUE THREAD

**Issue by leksandr** [microsoftgraph/microsoft-graph-docs#5406]
API doesn't return OneNote documents. I have several OneNote documents on OneDrive for Business and SharePoint, but when I call https://graph.microsoft.com/beta/me/insights/used?$filter=ResourceVisualization/Type eq 'OneNote', it returns "value": [].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 943ddff4-163d-2857-89d3-1f646280acc2
* Version Independent ID: 5529441d-5ef3-6f7e-4885-751bb93a7658
* Content: [List used - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/insights-list-used?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/insights-list-used.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/insights-list-used.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by simonhult** [comment]
Thank you for reporting this issue, and I am sorry for the inconvenience that this might be causing. This is unfortunately a known shortcoming of the service that we have not yet been able to address.
