### ISSUE TITLE
Outlook task comes up when referring to it by id even if it was deleted

### ISSUE THREAD

**Issue by lesharadkovich** [microsoftgraph/microsoft-graph-docs#5407]
When deleting task, no matter if it was deleted via Todo app or via REST API, it still comes up as a response to GET /tasks/{id}. However it's not coming when I do for example searching tasks for extended properties. It feels like a very annoying bug, I don't think this was meant to work this way 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea8b4088-5ae4-d9f8-d1c2-2b2e322ad7f8
* Version Independent ID: 50fa444d-6630-b4b8-da54-7da384be3dea
* Content: [Delete outlookTask - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlooktask-delete?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/outlooktask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlooktask-delete.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mashriv** [comment]
@lesharadkovich thanks for sharing this. This looks like a bug. We will investigate and update more on this. Meanwhile could you please share how you are searching tasks for extended properties?

**Comment by tobiasviehweger** [comment]
@mashriv We are using the following call (where the deleted tasks are NOT returned, which is correct):

`https://graph.microsoft.com/beta/me/outlook/tasks?$filter=singleValueExtendedProperties/any(ep:ep/Id eq 'jiraProjectId' and ep/Value eq 'someId')`

**Comment by mashriv** [comment]
@tobiasviehweger thanks! We have created an internal tracking issue for this. One of our dev will soon do the investigation
