### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by mgbnetus** [microsoftgraph/microsoft-graph-docs#5411]
First mention of OneDrive on the page spells it :  "OneDrive for Bussiness"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46ed48c0-a925-c3c9-1db1-965c9b2b034b
* Version Independent ID: 60f3cca5-daf2-9b3b-cf9e-b1528d4ee889
* Content: [sharedInsight resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/insights-shared?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/insights-shared.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/insights-shared.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dplotnikov** [comment]
@simonhult please merge the PR and feel free to close this issue

**Comment by Lauragra** [comment]
Thanks; merged and this will go live Monday afternoon.
