### ISSUE TITLE
How to get resource ID of a subscription or a management group?

### ISSUE THREAD

**Issue by zhusulai** [microsoftgraph/microsoft-graph-docs#5412]
The API does not work with externalId. How do we get the internal ID of a subscription or a management group so we can use other APIs to query role definitions and role assignments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb8df1af-47d1-1d2c-4075-7c29b3247b6a
* Version Independent ID: 6c0f96b4-09d6-eece-a771-b19625e091b9
* Content: [Get governanceResource - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governanceresource-get?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/governanceresource-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceresource-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by shauliu** [comment]
You should be able to do a filter on the list api https://docs.microsoft.com/en-us/graph/api/governanceresource-list?view=graph-rest-beta&tabs=http using your external id
