### ISSUE TITLE
Not checking delegated permissions

### ISSUE THREAD

**Issue by Bhavya207** [microsoftgraph/microsoft-graph-docs#5417]
The query: /privilegedAccess/azureResources/resources/register
is not checking for permissions, It is bypassing the permissions level and giving the result. 
List and Get resources is giving some uknown error.. Not specific about what kind of error.
The customer that I am dealing with has a directory role of application admin, still they are able to get the Register resource working. 

List and get resources is working fine in the portal and not through API queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff46d9cc-0523-d47e-8856-dea4a53f0c8e
* Version Independent ID: 0a39faf3-7d2e-b605-0fa2-3cf9cd28e1c5
* Content: [governanceResource: register - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governanceresource-register?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/governanceresource-register.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceresource-register.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@Bhavya207 - The engineering team is asking if you can provide the URL that you used and the specific value that was returned?

**Comment by davidmu1** [comment]
No response. Closing the issue.
