### ISSUE TITLE
Every operation underRoleAsignmentRequests is working in Portal, but not through API queries

### ISSUE THREAD

**Issue by Bhavya207** [microsoftgraph/microsoft-graph-docs#5418]
Every operation underRoleAsignmentRequests is working in Portal, but not through API queries.
For this query - GET /privilegedAccess/azureResources/roleAssignmentRequests?$filter=resourceId+eq+'{resourceId}'
What exactly is the resourceID ->Does this means subscription Id? ->ask from the Customer.

None of these are working through API, No proper error description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c8925b-bf52-c385-b2f0-cace73234560
* Version Independent ID: 31800dc3-4297-831e-3d9e-688e444d8fd7
* Content: [governanceRoleAssignmentRequest resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/governanceroleassignmentrequest?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/governanceroleassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/governanceroleassignmentrequest.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @wn9237
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@Bhavya207 - The resourceId is the identifier of the governanceResource object that is part of the role assignment request: https://docs.microsoft.com/en-us/graph/api/resources/governanceresource?view=graph-rest-beta. The Id of the governanceResource is generated by Privileged Identity Management. You can find the Id by using the externalId of the resource, which is the original id in Azure. 

Can you be more specific about what isn't working and what the error is that you are seeing?

**Comment by davidmu1** [comment]
No response. Closing the issue.
