### ISSUE TITLE
No Java Example?

### ISSUE THREAD

**Issue by mcowan-jama** [microsoftgraph/microsoft-graph-docs#5420]
Just curious why there are no java examples? Our internal tool suite is Java based and I wanted to build a little helper that allows publishing test results directly to an excel document in onedrive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a79fb959-193b-5fe5-5885-1d318ac5cacb
* Version Independent ID: 851e3f29-0eda-70a7-48a3-9fab2fa4e02d
* Content: [Microsoft Graph quick start FAQ - Microsoft Graph](https://docs.microsoft.com/en-us/graph/quick-start-faq#feedback)
* Content Source: [concepts/quick-start-faq.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/quick-start-faq.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **jasonjoh**

**Comment by jasonjoh** [comment]
@mcowan-jama we have a Java tutorial here: https://docs.microsoft.com/graph/tutorials/java. We also have Java sample code in our API topics (for example: https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=java#example-1-standard-users-request)

We are working on generating a quick start download for Java, which will basically be the completed project from the tutorial linked above.
