### ISSUE TITLE
Permissions requirement is incorrect

### ISSUE THREAD

**Issue by pschaeflein** [microsoftgraph/microsoft-graph-docs#5422]
This page (group-list-members) states that the Application permission required for the operation is User.Read.All or Directory.Read.All.  The permissions required to read a group are Group.Read.All or Directory.Read.All.  This is an apparent contradiction.

Testing shows that having User.Read.All permission is not sufficient to perform the group list operation. The response:
```json
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "a03aa710-880f-4f49-97d3-3d43987b3728",
      "date": "2019-08-13T02:30:24"
    }
  }
}
```

The group-list-members page should be updated to reflect the correct permissions required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
I have verified with engineering team that Group.Read.All is needed to perform list group member operation. I'll update this document by adding Group.Read.All permission.

**Comment by davidmu1** [comment]
The article has been updated. Closing the issue.
