### ISSUE TITLE
LastModifiedDateTime field isn't changed after document renaming. 

### ISSUE THREAD

**Issue by leksandr** [microsoftgraph/microsoft-graph-docs#5423]
For API insights/used, LastModifiedDateTime field isn't changed after document renaming. I renamed a document on OneDrive, but lastModifiedDateTime wasn't changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 943ddff4-163d-2857-89d3-1f646280acc2
* Version Independent ID: 5529441d-5ef3-6f7e-4885-751bb93a7658
* Content: [List used - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/insights-list-used?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/insights-list-used.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/insights-list-used.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by simonhult** [comment]
There is currently an inclusion-list of file-extensions that we support for the used-list, so it could be that you were hit by that limitation. Could you provide some additional details about your document? What file type is it, where did you change it, and can you see the changed title if you open OneDrive on the web?

**Comment by jthake-msft** [comment]
No information provided so closing issue.
