### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by dluc** [microsoftgraph/microsoft-graph-docs#5428]
Page: https://docs.microsoft.com/en-us/graph/azuread-users-concept-overview#feedback
Broken link: 
* title: Users API in Microsoft Graph beta
* URL: https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-beta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a16713a-38df-7902-81c2-776d8d1f9b43
* Version Independent ID: 1a53cac2-f14b-92be-adfe-f4aff31b1efe
* Content: [Overview of users in Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/azuread-users-concept-overview#feedback)
* Content Source: [concepts/azuread-users-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/azuread-users-concept-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The link is working now.
