### ISSUE TITLE
Error Response Documentation

### ISSUE THREAD

**Issue by hasahmed** [microsoftgraph/microsoft-graph-docs#5431]
Would be nice if there was documentation covering what the response codes are for specific errors. I.e. User doesn't have a license that is being attempted to remove. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a174c9b-6a84-c56a-d8a4-6e66cfcb6c03
* Version Independent ID: a34a5bf0-82cb-9b77-3cf7-b554a45a1f13
* Content: [assignLicense - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-assignlicense?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-assignlicense.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-assignlicense.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@davidmu1 I think this is a higher order question.  Should we have an error specific section on every API page?

**Comment by davidmu1** [comment]
I opened a workitem to cover any work that we might do to document error response codes:  https://identitydivision.visualstudio.com/Technical%20Content/_queries/edit/813383/?triage=true. Closing this issue.
