### ISSUE TITLE
issue with v1.0 reporting

### ISSUE THREAD

**Issue by gurpreetaror** [microsoftgraph/microsoft-graph-docs#5436]
When I try to access any kind of report from graph v1.0 url, I get the success error response but no data. 
I use the query : https://graph.microsoft.com/v1.0/reports/getOneDriveUsageAccountDetail(period='D7')

Whereas when I run same Query on beta graph url, to get one drive usage account detail report, there is good response. 
I use the query : https://graph.microsoft.com/beta/reports/getOneDriveUsageAccountDetail(period='D7')?$format=application/json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 143da283-bce1-4112-0bf9-52d488721f80
* Version Independent ID: 8bd96416-cff2-67e7-0f62-2732fb21cccf
* Content: [reportRoot: getOneDriveUsageAccountDetail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getonedriveusageaccountdetail?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/reportroot-getonedriveusageaccountdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/reportroot-getonedriveusageaccountdetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rarowston** [comment]
I'm a bit late to this, but will add a thought on this as I had a similar problem that I solved in case others come across it. The difference may be the return format of the response, the first query returns CSV data while the second query returns JSON. 
If you using the graph explorer to test these the JSON can be displayed in the response preview while the CSV cannot. You can see the full response by going to the bottom of the explorer window and clicking show more under history. You can then export the query and response to see what data is actually returned.
![image](https://user-images.githubusercontent.com/58011740/69284463-97a68600-0c3e-11ea-94eb-992f4b46a196.png)
^Show more under history

![image](https://user-images.githubusercontent.com/58011740/69284614-f409a580-0c3e-11ea-8875-e7b75382eb1f.png)
^File export

**Comment by normand-MSFT** [comment]
If you are consuming the data using PowerShell, you can use Invoke-RestMethod and use the -OutFile parameter to write the content directly to a CSV file.
