### ISSUE TITLE
Provide example to retrieve an other user information

### ISSUE THREAD

**Issue by Robouste** [microsoftgraph/microsoft-graph-docs#5440]
The example only shows how to retrieve our own profile and not someone else's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d24b1d9-ee3e-32ca-5c86-aebef8f09a85
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&tabs=csharp#feedback)
* Content Source: [api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Sergey-Grudskiy** [comment]
IUserMemberOfCollectionWithReferencesPage batch = await graphServiceClient.Users["<oid or principal name>"].MemberOf.Request().GetAsync();
var groups = new List<string>();
while (batch != null)
{
    groups.AddRange(batch.CurrentPage.OfType<Group>().Select(gr => $"[{gr.Id}]: {gr.MailNickname} / {gr.DisplayName}"));
    batch = batch.NextPageRequest == null ? null : await batch.NextPageRequest.GetAsync();
}

**Comment by Sergey-Grudskiy** [comment]
Inside Users[""] you can specify user's Azure Id (oid) or principal name (email most likely).

**Comment by davidmu1** [comment]
Added an example to get the properties of another user.
