### ISSUE TITLE
Moving message between mailboxes owned by different users

### ISSUE THREAD

**Issue by kerestan** [microsoftgraph/microsoft-graph-docs#5444]
If I have Application Mail.ReadWrite and User.Read.All (to get the folder ID of their folders), can I use this operation to move a message from one user's mailbox to another user's mailbox? I just tried it, passing `/{user_id}/mailFolders/{folder_id}/messages/{message_id}/move` with the `id` of another user's mailbox in the body, and received an error stating `The specified target folder could not be found.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5923fd4f-48ad-5d6f-3115-57f95e4ba92a
* Version Independent ID: eee95702-14a2-d4d2-3e03-739ae47bb577
* Content: [message: move - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/message-move.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-move.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@kerestan , thank you for bringing this up. No, the move method is between folders within the same mailbox.
I made some clarification in the docs for the move method by PR #5447 . The docs will be published within the next day.
In general, if you have API behavior type of questions, feel free to bring them up on stackoverflow and tag them with "microsoftgraph".
