### ISSUE TITLE
The endpoint GET /users/{id|userPrincipalName}/outlook/tasks is not working any user except login UserId. Even though I'm using our work account credential. i couldn't see tasks of outher members. i'm getting 403 error says "You do not have the required permissions to access this item."

### ISSUE THREAD

**Issue by sudodx** [microsoftgraph/microsoft-graph-docs#5459]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 269af1ad-db75-2d9d-fb59-5c834dee2863
* Version Independent ID: e21cb190-f4b6-2cb6-68d4-17cd8769b1ba
* Content: [outlookTask resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/outlooktask?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/outlooktask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/outlooktask.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hanneslarsson** [comment]
We have the same issue, why is it possible to fetch all users calendars and read all content as an application, but not fetch a specific user's tasks. Should be the same permission strategy here.

**Comment by angelgolfer-ms** [comment]
Hi @sudodx and @hanneslarsson , thank you for your input!
With delegated permission, a user can access the Outlook tasks in only his/her own mailbox. 

Can one of you please make a request for application permissions on the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) site? 

In general, the product team folks value customer requests and prioritize their work based on the number of votes an idea gets. @bandmask, @daniellundberg, you might want to cast a vote, or submit a request if a similar request doesn't already exist on [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).

Thank you!

**Comment by bandmask** [comment]
@sudodx FYI. 
This might be a worthy suggestion for what we are asking here: **https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/20160895-add-permissions-tasks-read-all-or-tasks-readwrite**

**Comment by sudodx** [comment]
Is there any way to use Tasks.Read.Shared scope to access Outlook Tasks that were shared with the current user.

**Comment by angelgolfer-ms** [comment]
@sudodx , the assignedTo property on an Outlook task is read-only, so if your question is about assigning a task, then the answer is you can't do it programmatically at this point through the REST API.

BTW, this GitHub issues site is primarily for documentation issues. Perhaps to get more community and product team response, you can post API questions on stackoverflow and tag them with "microsoftgraph"? If you have a feature request, like being able to assign tasks using the REST API, you can check out [User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests), and submit or vote as appropriate.
