### ISSUE TITLE
add members for mail-enabled security group

### ISSUE THREAD

**Issue by VitorX** [microsoftgraph/microsoft-graph-docs#546]
Based on the document [here](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/group_post_members), it should support to add members for mail-enabled security group.

But I got the error message like below:
**message=Unable to update the specified properties for objects that have originated within an external service.**

Is the document incorrect?

**Comment by yinaa** [comment]
The document mentions that "you can add only users to Office 365 groups". We are working on enabling adding users to the other types of groups as well, but this functionality is not available at this point in time

**Comment by dougroutledge** [comment]
Has there been any progress on this?  Adding and removing from distribution lists, which are the group type for Skype queues, would remove a major barrier for call center users.  If non tenant admin users and or their supervisors could move people in and out of the queue, with an MS graph application, that would be a strong business case for this capability.

**Comment by sweeneyrobb** [comment]
i'm also interested in this. currently have a solution that is being ported to non-windows and our current solution leverages powershell execution from ASP.NET MVC

**Comment by jakub-klapka** [comment]
+1 for updating distribution lists via ms graph

**Comment by belaie** [comment]
Any updates on this?

**Comment by jjorissen52** [comment]
I am also very interested in this feature. We have hundreds of users and contacts that need to be put into various distribution lists.

**Comment by blah43534** [comment]
I'm surprised this isn't functional yet - when can we expect to have this functionality?

**Comment by sweeneyrobb** [comment]
@yinaa where is the best place to track the progress of this? it sounds like we have a handful of people here interested. likely not getting a response because the issue was closed.

**Comment by laeeq** [comment]
I had same problem, so resorted to Exchange Online Ps command to add\remove members of mail-enabled security group.

**Comment by Didichoune** [comment]
Yes we can wait until the end of time. Thanks Microsoft, Also for your limitations in your runbooks in the Azure cloud...

**Comment by MatthieuArzel** [comment]
Hey guys. I've been trying for a day to add members to a group (for us it's a simple distribution list).

I read online that the "groupTypes" property of the group should be set to "Unified" to be able to do this (and not to "[]" as it is for me now).

Does this ring a bell? Do you know what is this groupTypes = Unified? Is it compatible with a distribution list? Do you know where i can set this in azure?

Has any of you find anything helpful since 2016 otherwise?

Thanks :)

**Comment by laeeq** [comment]
Current solution to add\remove members to mail enabled security groups or distribution groups is to use Exchange Online PowerShell commands.
Thanks

**Comment by marshalexander99** [comment]
All of the suggestions mentioning to use exchange powershell aren't helpful when using azure automation and connecting to azure ad with the runas account. Stored creds (to enable a connection to exchange online) also do not work when 2 factor authentication is enabled.
Surely there must be a way around this by now, especially when the add-azureadgroupmember cmdlet is rendered useless by this limitation
