### ISSUE TITLE
Microsoft Graph Beta Create call Calls.Initiate.All permission not found

### ISSUE THREAD

**Issue by gregdegruy** [microsoftgraph/microsoft-graph-docs#5462]
Trying to create a Teams call using the Graph API, but the Calls.Initiate.All is required. In the Graph explorer I see no means to grant application permissions as delegated permissions are not supported. Is there a way to grant this permission in the explorer or must this be done programmatically? If so how?

![](https://i.stack.imgur.com/Oczz7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b5f237-e7af-1f0f-201c-c600eb4a3cc8
* Version Independent ID: 7aa5b80a-5565-b702-20ae-8d550357980a
* Content: [Create call - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&tabs=http#permissions)
* Content Source: [api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-calls.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
@jthake-msft THis looks like a Graph Explorer question than Calling API, not sure how to address that in this context, can you help?

**Comment by ananmishr** [comment]
@gregdegruy We don't currently support creating a Teams call through Graph Explorer

**Comment by gregdegruy** [comment]
Thanks Ananya. Is there any support for creating Teams calls using the MS Graph API outside the explorer?

**Comment by wimvanhouts** [comment]
You cannot login the graph explorer as an application, only as a user, create call must be made from within an application afaik. You can create a simple application using the SDKs of the language preferred, you only have to define the application in AAD and grant it the permissions
