### ISSUE TITLE
Unable to download DriveItemVersion content from JavaScript

### ISSUE THREAD

**Issue by 3344ahc** [microsoftgraph/microsoft-graph-docs#5464]
When attempting to download the content of a DriveItemVersion, we get the 302 redirect, and run into the same CORS problems as described here:

https://github.com/microsoftgraph/microsoft-graph-docs/issues/43

The "solution" to that issue involves sending a GET to the @downloadUrl value, which may work for a DriveItem, but DriveItemVersion doesn't have that property.

What's the proper way to download an older version of a file using JavaScript?  To the best of my knowledge, we have no way of getting the `Location` header from the response in order to get the "pre-authenticated download URL".  So this guidance from the documentation is misleading:

&gt; To download the contents of the file your application will need to follow the `Location` header in the response. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2c774ac-0a2a-5689-25f5-7f8532404371
* Version Independent ID: 7edc5929-fb33-1a12-dca2-5f7f5f48bc6b
* Content: [Download contents of a DriveItemVersion resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitemversion-get-contents?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/driveitemversion-get-contents.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitemversion-get-contents.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@JeremyKelley  @ificator  not sure why this page is set to me as owner, can this be changed as it's now auto assigning...

**Comment by ificator** [comment]
That was very useful, thanks @3344ahc! I have a repro - it looks like the target of the redirect does not handle the case where `Origin: null`, which is unfortunately what a browser will send when it's following a redirect.

It looks like it would be a fairly simple fix so I'll see that it gets done.

**Comment by ificator** [comment]
Hi @3344ahc, the fix for this has now been deployed. Can you confirm that it's now working for your scenario?
