### ISSUE TITLE
Bug in beta end-point for retrieving site by its path

### ISSUE THREAD

**Issue by estruyf** [microsoftgraph/microsoft-graph-docs#547]
In the documentation is written that you can retrieve a site by its path like this: `https://graph.microsoft.com/beta/sharepoint:/{site-path}`. If you try this out on a tenant you get the following error:

```
GET https://graph.microsoft.com/beta/sharepoint:/sites/demo


{
    "error": {
        "code": "InternalServerError",
        "message": "A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.",
        "innerError": {
            "request-id": "45b3437a-538c-4f71-9fcc-ff06a8a006d0",
            "date": "2016-10-06T07:19:48"
        }
    }
}
```

I knew from the past that the Graph API used caml casing, so I tried using share**P**oint in the end-point and noticed that this solved the problem. 

```
GET https://graph.microsoft.com/beta/sharePoint:/sites/demo

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#baseItem",
    "@odata.type": "#microsoft.graph.site",
    "createdDateTime": "2016-08-18T21:15:42Z",
    "description": "",
    "id": "...",
    "lastModifiedDateTime": "2016-10-01T05:44:32Z",
    "name": "demo",
    "webUrl": "https://.../sites/demo",
    "root": {},
    "siteCollection": {
        "hostname": "....sharepoint.com"
    },
    "siteCollectionId": "...",
    "siteId": "..."
}
```

**Comment by marych** [comment]
Thanks for reporting the issue. A fix was rolled out about a month ago and it's now case insensitive, so https://graph.microsoft.com/beta/sharepoint:/sites/demo will return the same result as https://graph.microsoft.com/beta/sharePoint:/sites/demo

**Comment by estruyf** [comment]
Already noticed it a couple of weeks ago 👍, thanks!
