### ISSUE TITLE
What would be URL path to execute the request?

### ISSUE THREAD

**Issue by ken5scal** [microsoftgraph/microsoft-graph-docs#5472]
I have searching for it for a long time.
Isn't it supposed to be https://graph.microsoft.com/beta/deviceManagement/geoLocastions or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639d5c1a-b3b4-b8b7-65a1-289308d3b9bc
* Version Independent ID: 6274178f-9f66-61a9-3173-1eb522fd4be0
* Content: [deviceGeoLocation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-devicegeolocation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/intune-devices-devicegeolocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-devices-devicegeolocation.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sathishvc** [comment]
@ken5scal, I am also looking for this URL path info. If you figured it out, please help me with the URL path. Thanks!
