### ISSUE TITLE
Create tasks using work account credential  for  users

### ISSUE THREAD

**Issue by sudodx** [microsoftgraph/microsoft-graph-docs#5479]
We have a work account  with an azure  subscription. We need to create tasks for other users using this work account. Is this possible? if so how to proceed ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312c9fd8-9544-f242-c394-35d353406648
* Version Independent ID: 53114d87-dcf5-a47f-e5c2-7a2043f7c67e
* Content: [Create outlookTask - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlookuser-post-tasks?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/outlookuser-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlookuser-post-tasks.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mashriv** [comment]
@sudodx , please go through https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-beta .. Let us know if it still not enough.
