### ISSUE TITLE
Timezone information do not apply to body on createReply & createForward

### ISSUE THREAD

**Issue by erandac** [microsoftgraph/microsoft-graph-docs#5481]
When creating  a forward or a reply from a message (`POST /me/messages/{id}/createForward`), the body html contains UTC date time for sent paragraph.

`<b>Sent:</b> Tuesday, August 20, 2019 7:53:20 AM<br>
`
I expect the time value should formatted to user configured timezone or timezone requested from header `Prefer : outlook.timezone="Asia/Colombo" `

**Comment by jthake-msft** [comment]
What is your question exactly? Or are you stating a behaviour change in the API?

**Comment by erandac** [comment]
Yes, it's kind of change in the API result, since `createForward` return fully formatted HTML body, It would be better if service can adjust the date time values to timezone we provided. Other wise client application required to replace the html body time values before sending the drafted item.

**Comment by jthake-msft** [comment]
OK. So if this is a feature request. We track these on https://microsoftgraph.uservoice.com/ because we benefit from the ability to vote features up by other developers.
