### ISSUE TITLE
Xamarin: Avoid inadvertently leaking your app ID

### ISSUE THREAD

**Issue by jbe2277** [microsoftgraph/microsoft-graph-docs#5485]
I like the **Note**:
> If you're using source control such as git, now would be a good time to exclude the OAuthSettings.cs file from source control to avoid inadvertently leaking your app ID.

Unfortunately, a few lines below this is done again with the `AndroidManifest.xml` file:
```XML
<data android:scheme="msalYOUR_APP_ID_HERE" android:host="auth" />
```
Excluding the file `AndroidManifest.xml` from source control would solve this issue. But it makes it difficult for other developers to get the code to build and to run.

Same issue with the iOS `Info.plist` file:
* **URL Schemes:** set to msal{YOUR-APP-ID}

**Article:** [Add Azure AD authentication](https://docs.microsoft.com/en-us/graph/tutorials/xamarin?tutorial-step=3)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0733b09-b4b0-a83f-d417-32ed26c33790
* Version Independent ID: 2bc7308f-0688-d7d6-d6e9-be06b3452cb8
* Content: [Microsoft Graph tutorials - Microsoft Graph](https://docs.microsoft.com/en-us/graph/tutorials)
* Content Source: [concepts/tutorials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/tutorials.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@Jackson-Woods  What is our guidance here for source control and app ids?

**Comment by psignoret** [comment]
Just to close the loop here on a super old issue: There is no expectation that an app ID is secret (they're easily discoverable in URLs and sign-in logs). App IDs *are* specific to a deployment or app, much like redirect URLs and domain names, so those hosting code projects that are intended to be used by others (i.e. using their own app IDs) are encouraged to follow the same pattern as they would for other instance-specific configuration such as domain names, redirect URLs, etc.
