### ISSUE TITLE
Incorrect Class Name in the C# Example

### ISSUE THREAD

**Issue by zhusulai** [microsoftgraph/microsoft-graph-docs#5486]
It should be `GovernanceRoleAssignmentRequestObject` instead of `GovernanceRoleAssignmentRequest`.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0926dfc7-4119-849b-cce6-428d14b310ef
* Version Independent ID: e34cdb5e-9682-1321-bc32-495801540df5
* Content: [Create governanceRoleAssignmentRequest - Microsoft Graph beta](https://docs.microsoft.com/en-ca/graph/api/governanceroleassignmentrequest-post?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/governanceroleassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceroleassignmentrequest-post.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@dkershaw10  who owns this page? As we should really update the author as well as resolve this feedback.

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
