### ISSUE TITLE
No data in ChartFill

### ISSUE THREAD

**Issue by benanderman** [microsoftgraph/microsoft-graph-docs#5487]
Hi! I'm trying to get the fill colors of each slice of a pie chart. I believe this is the type it should be, but this type has no properties or relationships.
When I request "https://graph.microsoft.com/v1.0/users/{}/drive/root:{}:/workbook/worksheets/{}/charts/{}/series/itemAt(index=0)/points/itemAt(index=0)", I get back a JSON blob that includes a value, so I can tell everything up until that point is working. But I add "/format" or  "/format/fill" to that URL, I get a successful result, but the JSON blob only has the context and ID fields, but no actual data. Please make this API return an actual fill color!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e22c58-884d-f407-9cbe-8a9fed11ec5f
* Version Independent ID: 502d1bc5-e9c2-ba3d-b542-e168b6176cf3
* Content: [ChartFill resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/chartfill?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/chartfill.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/chartfill.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by grangeryy** [comment]
Does this issue still reproduce?

**Comment by benanderman** [comment]
> Does this issue still reproduce?

Yes, I can still reproduce this. One thing to note, is that the format I'm trying to get has an "automatic" fill. Maybe this only returns the fill if it's set explicitly?

**Comment by grangeryy** [comment]
Hey @benanderman currently the property is not supported yet for ChartFill in Excel Graph. I'll open a feature request in our backlog and close the issue here. THX!
