### ISSUE TITLE
Previous page using ARMClient

### ISSUE THREAD

**Issue by scunge6006** [microsoftgraph/microsoft-graph-docs#5491]
Can you please put up a link to the previous page that detailed how to use ARMclient and EventHubs for SIEM integration thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 950f7b2a-e6b6-877f-9928-dbc5006e9224
* Version Independent ID: 7a638117-dba8-9431-cb16-0bd91727f25f
* Content: [Security solution integrations using the Microsoft Graph Security API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/security-integration#feedback)
* Content Source: [concepts/security-integration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/security-integration.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by preetikr** [comment]
This method is no longer supported since we have direct SIEM integrations for Splunk and QRadar. Please follow steps in https://docs.microsoft.com/en-us/graph/security-integration?view=graph-rest-1.0

**Comment by scunge6006** [comment]
Understood thank you :-)
