### ISSUE TITLE
Get list of task folder for users

### ISSUE THREAD

**Issue by sudodx** [microsoftgraph/microsoft-graph-docs#5492]
GET /users/{id|userPrincipalName}/outlook/taskFolders 
trying to get task folder for users using  work or school account
{
    "error": {
        "code": "ErrorItemNotFound",
        "message": "The specified object was not found in the store.",
        "innerError": {
            "request-id": "10b1d172-d812-4dfc-9355-fed180c77441",
            "date": "2019-08-21T05:25:10"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c7e244-509d-c4fa-e1c8-ff4dabeebf7b
* Version Independent ID: bd63ae54-0f85-a512-2435-8f8f2ed0917d
* Content: [List taskFolders - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlookuser-list-taskfolders?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/outlookuser-list-taskfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlookuser-list-taskfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mashriv** [comment]
@sudodx, thanks to contacting us. We do support query by id or userPrincipalName. Could you help us with your use case scenario. Is it an application that is creating tasks for users? How is this app authorizing with Graph? You can go through this to get more understanding, https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0

**Comment by mashriv** [comment]
@sudodx, thanks to contacting us. We do support query by id or userPrincipalName. Could you help us with your use case scenario. Is it an application that is creating tasks for users? How is this app authorizing with Graph? You can go through this to get more understanding, https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-beta
