### ISSUE TITLE
Deployment summary query out of date

### ISSUE THREAD

**Issue by timofeitonu** [microsoftgraph/microsoft-graph-docs#5496]
- according to the article, to view the deployment summary for an iOS MAM policy, one uses: GET /deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtectionId}/deploymentSummary
- this returns an error in Graph Explorer: Failure - Status Code 400. No method match route template.
- the current correct query uses expand: GET /deviceAppManagement/iosManagedAppProtections/{iosManagedAppProtectionId}?$expand=deploymentSummary
- the same applies for Android MAM policies

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 914ef597-dc52-cf0a-0120-e5f693b98e2a
* Version Independent ID: daa10795-8b2c-7de0-7fe9-f580e481cf46
* Content: [Get managedAppPolicyDeploymentSummary - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-mam-managedapppolicydeploymentsummary-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-mam-managedapppolicydeploymentsummary-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-mam-managedapppolicydeploymentsummary-get.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
When we see the error, there actually is no code that supports this route. This sometimes occurs based on how our documentation is generated. Thanks for posting the correct way to retrieve the info.  You can also validate an entity creation by doing F12 developer tools in the browser and seeing the actual calls being made to create an object.
