### ISSUE TITLE
Secret not necessary

### ISSUE THREAD

**Issue by biste5** [microsoftgraph/microsoft-graph-docs#5504]
The article describes how to create and store a Secret for the app registration, but not explaining where/how it should be used
In the scenario described 'Delegated Permissions' are being used; so the Secret isn't really necessary.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf53c20-0e14-5ad8-5522-6dd2036ced91
* Version Independent ID: 62a97f3a-1e7d-ba70-e827-ad2a18ded879
* Content: [Manage app registration and API permission for Microsoft Graph notifications - Microsoft Graph](https://docs.microsoft.com/en-us/graph/notifications-integration-app-registration)
* Content Source: [concepts/notifications-integration-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/notifications-integration-app-registration.md)
* Product: **notifications**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @biste5 for raising your issue. You can use either an App certificate or a client secret to authenticate your app. You don't have to configure both if you'll  prefer to use one. However, as indicated in the note, a certificate is recommended over a client secret.

No further updates identified for the page. Closing this issue.

**Comment by biste5** [comment]
sure. You did NOT understand my point though.

**Comment by FaithOmbongi** [comment]
My apologies @biste5. I hope I've gotten your comment right this time and this response helps: Step 5 is _very_ necessary if you're going to use the web app/api with delegated access. You can see that when you [get access on behalf of a user](https://docs.microsoft.com/en-us/graph/auth-v2-user), you'll use the certificate/secret to authenticate, and in return, receive an access token that'll authorize you to call Microsoft Graph on behalf of the user.

I hope this now answers the question?
