### ISSUE TITLE
Including HTML table in the body of the meeting invite doesn't work as expected

### ISSUE THREAD

**Issue by unk1911** [microsoftgraph/microsoft-graph-docs#5507]
I am trying to include an HTML table as part of the body.  However, when I look at the created event,  the table formatting is gone. For example, I wanted to include borders, but no borders are visible.   It is as if Outlook 2013 stripped it out.   Any way to preserve the html/formatting? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ff7ff9f-c955-c32f-756c-59e9165f3fa3
* Version Independent ID: c181ecf0-6586-9b36-20a8-f2f1e1381397
* Content: [Create event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-post-events?view=graph-rest-1.0&tabs=java#feedback)
* Content Source: [api-reference/v1.0/api/calendar-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svrooij** [comment]
@unk1911 this issue isn't something about the documentation, but rather an issue (or question) about the api itself.

Those questions (or issues) are usually solved quicker by posting a question on [stackoverflow](https://stackoverflow.com/questions/tagged/microsoft-graph) (with some sample code).

**Comment by unk1911** [comment]
no worries, the issue resolved itself when we upgraded to latest version of Outlook.  i think HTML tables simply weren't supported in Outlook 2013.

**Comment by svrooij** [comment]
Outlook had some issues with html in the body, mostly solved in the latest version
