### ISSUE TITLE
attachment-delete.md has wrong request uri sample

### ISSUE THREAD

**Issue by xuzhg** [microsoftgraph/microsoft-graph-docs#5508]
Issue:

in [microsoft-graph-docs/api-reference/v1.0/api/attachment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/9ac31c9f166adbec1fbc71ad4d7416477c72d816/api-reference/v1.0/api/attachment-delete.md)

There's a request Uri as follows:
```
DELETE /me/calendar/{id}/events/{id}/attachments/{id}
DELETE /users/{id | userPrincipalName}/calendar/events/{id}/attachments/{id}
```
However, `calendar` is a single navigation property, append `{id}` after is not correct.
Please correct it.
It should be:
`
DELETE /me/calendar/events/{id}/attachments/{id}
`

**Comment by angelgolfer-ms** [comment]
@xuzhg, thanks for bringing this up. I fixed the typo in those lines of the supported syntax, the navigation property there is "calendar".
I also made some more clarification to the supported syntax - added a couple of lines of syntax that use the calendars navigation property, and, clarified that events in group calendars do not support attachments.

My PR is #5513. The updates should be published some time in the next day.

Thank you for your support.
