### ISSUE TITLE
Amount of messages returned

### ISSUE THREAD

**Issue by jaimeirala** [microsoftgraph/microsoft-graph-docs#5519]
We are getting different amount of messages while retrieving messages from channels.
We have a channel with more than 30 messages, but using just /messages and then @odata.nextLink, we get 7, then 1, then 13, then 16 and last page with 0.
So how does it work/filter intern for just returning 7 in the first place? Shouldn't it return the same amount in every page of results?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by wazawski** [comment]
Hello @jaimeirala, did you check if there was no deleted messages returned by your request ?
Since OData query parameters are not available yet, we cannot filter based on message properties yet (soon I hope)

**Comment by jaimeirala** [comment]
Hi @wazawski ,
Thanks for answering.
Yes, the response included deleted messages too with ""deletedDateTime": "2019-10-09T12:28:35Z"
Maybe the initial amount counts other events? like added/removed member, ..?

**Comment by wazawski** [comment]
Not sure about events since there is no way I know of to get its infos using the API for the moment.

**Comment by nkramer** [comment]
The endpoint filters out control messages, but the filtering is done after we paginate.
