### ISSUE TITLE
Differential query is not supported for entity type: OrgContact

### ISSUE THREAD

**Issue by mtucker2112** [microsoftgraph/microsoft-graph-docs#5523]
We have suddenly started receiving this error when trying to get the latest delta token for contacts:

https://graph.microsoft.com/beta/Contacts/Delta?$deltaToken=latest

{
    "error": {
        "code": "Request_UnsupportedQuery",
        "message": "Differential query is not supported for entity type: OrgContact",
        "innerError": {
            "request-id": "d35d6237-4a9f-4384-b3cb-5e2455022998",
            "date": "2019-08-23T19:41:40"
        }
    }
}

While this is the Beta endpoint, it is an existing API for contacts that until now has worked perfectly.  Please advise!!

**Comment by mtucker2112** [comment]
Any update on this issue?

**Comment by piotrci** [comment]
We had to make some configuration changes in the /beta version to address conflicts between two entity types. We have made a fix and we plan to re-enable the /delta function around 9/30.

**Comment by piotrci** [comment]
Update: our fix has been delayed and is now expected to fully deploy by 10/9

**Comment by mtucker2112** [comment]
Looks like this is working now.  Thanks so much!!

**Comment by piotrci** [comment]
It has been fixed, sorry for the inconvenience.
