### ISSUE TITLE
When will this endpoint be available?

### ISSUE THREAD

**Issue by bpedman** [microsoftgraph/microsoft-graph-docs#5525]
When I test this endpoint (https://graph.microsoft.com/beta/places/microsoft.graph.room) with the Graph Explorer I get a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41555953-ca70-587c-4660-5f0a83c8c230
* Version Independent ID: 4a5b79f8-d685-6c86-d7ed-12d7c5d309cb
* Content: [List places - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/place-list.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bpedman** [comment]
I guess the real issue for this page is that if the endpoint is not actually available it shouldn't be listed on the reference docs.

**Comment by bpedman** [comment]
Odd, I did the exact same operation tonight and its working now 🤷‍♂

**Comment by vchauhangit** [comment]
For app having place.read.all permission always giving message:
"{\"code\":\"invalid_permissions\",\"message\":\"place.read.all permission is required to read company places, scopes/roles provided: Calendars.ReadWrite IsAppOnly:True\"}"
