### ISSUE TITLE
Create team for class

### ISSUE THREAD

**Issue by ashleywb** [microsoftgraph/microsoft-graph-docs#5530]
How do you create a team with the educationClass template? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00765340-ee21-7bec-7199-7d24708cd8b3
* Version Independent ID: 799c512a-e631-139c-9ff1-49e1d284cca9
* Content: [Create educationClass - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationroot-post-classes?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/educationroot-post-classes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/educationroot-post-classes.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmast-msft** [comment]
This is done with the create Team API. https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta

Something like:
POST https://graph.microsoft.com/beta/teams 
Content-Type: application/json  
{ 
"template@odata.bind":"https://graph.microsoft.com/beta/teamsTemplates('educationClass')", 
  "group@odata.bind":       "https://graph.microsoft.com/v1.0/groups('groupId')"  
}
