### ISSUE TITLE
Please support column names while creating a new table

### ISSUE THREAD

**Issue by dennisameling** [microsoftgraph/microsoft-graph-docs#5531]
Currently, when creating a new table in a worksheet using the instructions on this page, you can't provide table column header names. I currently have to:
- Create a table POST /tables/add (address e.g. A1:G1 for 7 columns)
- Get table colums with GET /tables/{ID}/columns
- Patch each column with a column name PATCH /tables/{ID}/columns/{ID} (7x in this case)

Would be great if we could provide the column names on table creation already, instead of having to fire different API calls to accomplish this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6fcbe6-ba46-26e0-360b-4e41167c7a6d
* Version Independent ID: fdd2eed7-3602-c5e5-5d8a-b3066d21df15
* Content: [TableCollection: add - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/tablecollection-add?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/tablecollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/tablecollection-add.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aglakshmi** [comment]
Absolutely true, we need an endpoint to add table with Columns. In my case I need to add 20 columns. I am trying to do this inside Flow. calling 20 times api call is not good enough.

**Comment by aglakshmi** [comment]
Absolutely true, we need an endpoint to add table with Columns. In my case I need to add 20 columns. I am trying to do this inside Flow. calling api 20 times api call is not good enough.

**Comment by grangeryy** [comment]
Thanks for the feedback. Currently it is not supported in Excel Graph for the requirement. We need to support JavaScript API for this first before enabling it in Graph. I'll pass this ask to buddy team. Thx!
