### ISSUE TITLE
beta graph api fails with invalid JSON

### ISSUE THREAD

**Issue by jozefchutka** [microsoftgraph/microsoft-graph-docs#5532]
Issue: when requesting this exact user 
`https://graph.microsoft.com/beta/users/40e99f05-32d8-40c0-b91d-9e98d21f93a9?$expand=manager`

the api responds with error, which is also an invalid JSON:
```
{"@odata.context":"https://graph.microsoft.com/beta/$metadata#users/$entity","id":"40e99f05-32d8-40c0-b91d-9e98d21f93a9","deletedDateTime":null,"accountEnabled":true,LONG_AND_SENSITIVE_CONTENT...{
  "error": {
    "code": "BadRequest",
    "message": "The type 'microsoft.graph.contact' of a resource in an expanded link is not compatible with the element type 'microsoft.graph.directoryObject' of the expanded link. Entries in an expanded link must have entity types that are assignable to the element type of the expanded link.",
    "innerError": {
      "request-id": "456afb70-cf43-4a24-8d14-fb0edcbaee2a",
      "date": "2019-08-26T06:21:46"
    }
  }
}
```

Prefered would be:
- the beta api is fixed and returns a valid data for this user
- or response to be a valid JSON

**Comment by jozefchutka** [comment]
v1.0 does not have the `$expand=manager` option

**Comment by dkershaw10** [comment]
The issue was due to org contact not being in v1.0 at the time.
@jozefchutka This issue should be resolved now.  Can you try this API call again and seeing if it works now please?

**Comment by dkershaw10** [comment]
@jozefchutka I suspect that it was due to a different issue.  It should be working now (in beta). If not please reactivate.
