### ISSUE TITLE
Create appRoleAssignment does not work.

### ISSUE THREAD

**Issue by andrewfabrizi** [microsoftgraph/microsoft-graph-docs#5534]
This API method returns the following:
{
  "error": {
    "code": "Request_BadRequest",
    "message": "One or more properties are invalid.",
    "innerError": {
      "request-id": "6ab3a024-2078-40fe-8460-50f3dcf589b8",
      "date": "2019-08-26T13:39:52"
    }
  }
}

Here are links referencing the same issue. There doesn't seem to be anyone working on this issue. Please fix this.

https://github.com/microsoftgraph/microsoft-graph-docs/issues/4266

https://stackoverflow.com/questions/56786453/how-to-create-an-approleassignment-via-microsoft-graph

https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f89ec701-8220-14ec-0dfd-543d2b4faafc
* Version Independent ID: 794ffd87-99dd-0521-cd5d-8a340d5babad
* Content: [Create appRoleAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta&tabs=javascript#feedback)
* Content Source: [api-reference/beta/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-post-approleassignments.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Zaid-Safadi** [comment]
Check my response here: https://stackoverflow.com/questions/56786453/how-to-create-an-approleassignment-via-microsoft-graph

```cs
        const string ROLE_ASSIGNMENT_FORMATTER = "https://graph.microsoft.com/beta/servicePrincipals/{0}/appRoleAssignments";
        
        public static async Task AddApplicationUsers(string enterpriseAppId, string userId, string roleId)
        {
            HttpClient client = new HttpClient();
            string url = string.Format(ROLE_ASSIGNMENT_FORMATTER, enterpriseAppId);

            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await GetAccessToken());

            var roleAssignment = new
            {
                appRoleId = roleId,
                principalId = userId,
                resourceId = enterpriseAppId
            };


            var content = new StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(roleAssignment), Encoding.UTF8, "application/json");
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            var response  = await client.PostAsync(url, content);

            if (response.IsSuccessStatusCode)
            {
                return ;
            }
            else
            {
                throw new HttpRequestException(response.ReasonPhrase);
            }
        }
```

**Comment by andrewfabrizi** [comment]
Thanks for the response! That worked perfectly.

**Comment by honb** [comment]
@Zaid-Safadi @andrewfabrizi
"https://graph.microsoft.com/beta/servicePrincipals/{enterpriseAppId}/appRoleAssignments"

Request body: {
      appRoleId: 'XXX',
      principalId: 'XXX',
      resourceId: 'XXX'
    }
I tried to test above API by sending a post request but it returns 401 error:
My AAD app has consented "Directory.AccessAsUser.All" for both MICROSOFT GRAPH & WINDOWS AZURE ACTIVE DIRECTORY

**Comment by davidmu1** [comment]
In the SO thread, it appears that the issue was cleared up. No change identified for the page. Closing the issue.
