### ISSUE TITLE
Retrieving team channels results in 403 with the error: Failed to execute Skype backend request 

### ISSUE THREAD

**Issue by SanderSiep** [microsoftgraph/microsoft-graph-docs#5535]
Issue:
When retrieving the team channels a 403 is raised with the error 'Failed to execute Skype backend request'.
This was working perfectly before today on multiple environments, while currently it is not working anymore on all these environments.
The strange thing is that retrieving a specific channel is just working fine.
Also tried to retrieve the channels by teams and by groups. Both resulting in the same error.

The query which is executed and not working:
teams/9b1762ef-0b54-4781-xxxx-4b9c3490b0ba/channels/
groups/9b1762ef-0b54-4781-xxxx-4b9c3490b0ba/channels/

The query which is working ok:
teams/9b1762ef-0b54-4781-xxxx-4b9c3490b0ba/channels/19:8993b34d42fa4016b0b7749fd699xxxx@thread.skype
groups/9b1762ef-0b54-4781-xxxx-4b9c3490b0ba/channels/19:8993b34d42fa4016b0b7749fd699xxxx@thread.skype

Hi @jthake-msft can you please have a look at this while this is blocking issue. Thanks in advance!

**Comment by kkrzaczkowski** [comment]
I have the same problem. Two days ago it worked but today I get similar error.
Checked on two tennant and both client application and MS Graph Explorer.
Tried using another user, give all permissions, removing and adding permissions from begining.
In every case the same error.

Not working request:
GET https://graph.microsoft.com/v1.0/teams/206cde8b-f8bf-4d51-8760-159d1866xxxx/channels
Error: "Failure - Status Code 403"
Response body:
`"error": {
	"code": "AccessDenied",
	"message": "Failed to execute Skype backend request GetThreadsS2SRequest.",
	"innerError": {
		"request-id": "99c3d41d-a26d-4ff9-a5d1-c04a40774fa8",
		"date": "2019-08-26T22:20:09"
	}
}`

Working requests:
GET https://graph.microsoft.com/v1.0/teams/206cde8b-f8bf-4d51-8760-159d1866xxxx
GET https://graph.microsoft.com/v1.0/teams/206cde8b-f8bf-4d51-8760-159d1866xxxx/channels/19:b8e20479be5e495fb8407c4dc537xxxx@thread.skype

**Comment by SanderSiep** [comment]
At our DEV and TST environment the issue is solved and it is working again.
@kkrzaczkowski do you also get correct ressults again when executing the queries? If so I will close the case.

**Comment by kkrzaczkowski** [comment]
Now it works :)

**Comment by SanderSiep** [comment]
Issue is resolved, so closing this thread.

**Comment by nkramer** [comment]
Thanks for the report, we've resolved the issue.
