### ISSUE TITLE
Important! How does Azure AD know in which groups to put a user when it is restored?

### ISSUE THREAD

**Issue by Enosinger** [microsoftgraph/microsoft-graph-docs#5544]
I am very happy to see that Azure AD puts a restored user back into the groups, where it was a member to when it was deleted. But how does Azure AD keep track of this information? And is there a way to access this information?

We have a very important customer request to show the deleted users grouped by their former Azure AD groups.

Looking forward to your reply and thanks for the help. Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e760d3-a032-5214-1fb2-e8c811d48a57
* Version Independent ID: 2f86af0c-8ed0-16f1-674c-91c6ebfb045d
* Content: [Restore deleted item - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directory-deleteditems-restore.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@Enosinger could you please clarify what you mean by "deleted member"? Do you mean a member removed from the group? and you want to get a report of all members that are removed from a certain group?

**Comment by Enosinger** [comment]
@yyuank thanks for the reply. With a "deleted member" I mean a whole user entity, which has been deleted from the Azure AD. They appear in the list of "deleted users" and can be restored for 30 days. (see screenshot below)

![image](https://user-images.githubusercontent.com/14183981/65953270-e5bfba00-e443-11e9-9656-c9af1f09b12f.png)

When we restored one of these deleted users, we observed that they are put back in the groups, they were a member of at the time of their deletion. We´d like to access this information to present a report, in which groups a user was at the time of his deletion.

Does that make a bit more sense? Looking forward to your reply and happy to answer more questions if necessary.

**Comment by yyuank** [comment]
@krbain would be the expert for user deletion.
FYI @davidmu1

**Comment by krbain** [comment]
@Enosinger When the user is deleted from the tenant, we put it in a soft-delete state and maintain all the object links including group memberships, to facilitate easy restoration. We don't currently expose the group membership info for a deleted user, however, you can view all the properties of the deleted user via the deleted items API (ex. GET /directory/deletedItems/{id}).

Hope that helps answer your question.

**Comment by davidmu1** [comment]
No change identified for the reference article. Closing the issue.
