### ISSUE TITLE
Unable to update invitee status as Declined

### ISSUE THREAD

**Issue by bhandvishnu7** [microsoftgraph/microsoft-graph-docs#5545]
I'm using https://graph.microsoft.com/v1.0/me/events/{id} HTTP URL to update invitee status.

But unable to update invitee status as Declined and returned as NotResponded in response where as for all other possible values like None, Organizer, TentativelyAccepted, Accepted, NotResponded are working correctly.

Here is my request body to Patch request:

{'attendees': [{'emailAddress': {'address': '&lt;email&gt;'}, 'type': 'required', 'status': {'response': 'Accepted', 'time': '2019-08-27T12:27:53Z'}}, {'emailAddress': {'address': '&lt;email&gt;'}, 'type': 'required', 'status': {'response': 'Declined', 'time': '2019-08-27T12:27:53Z'}}, {'emailAddress': {'address': '&lt;email&gt;'}, 'type': 'required', 'status': {'response': 'Accepted', 'time': '2019-08-27T12:27:53Z'}}]}

Attendee list inside response:

{"attendees": [{"type": "required", "status": {"response": "accepted", "time": "2019-08-27T12:27:53Z"}, "emailAddress": {"name": "&lt;name&gt;", "address": "&lt;email&gt;"}}, {"type": "required", "status": {"response": "notResponded", "time": "4501-01-01T00:00:00Z"}, "emailAddress": {"name": "&lt;name&gt;", "address": "&lt;email&gt;"}}, {"type": "required", "status": {"response": "accepted", "time": "2019-08-27T12:27:53Z"}, "emailAddress": {"name": "&lt;name&gt;r", "address": "&lt;email&gt;"}}]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1c68e-95bf-e8af-992e-cb790f8ca884
* Version Independent ID: 4072bab0-de7c-1f9f-05b9-6a7b4b6787f8
* Content: [Update event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-update.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jsaveljevs** [comment]
I can confirm this is still the case with current Beta as well. Is this an expected behavior?
