### ISSUE TITLE
Install app for user action not generating conversationUpdate type action to bot

### ISSUE THREAD

**Issue by VKAlwaysWin** [microsoftgraph/microsoft-graph-docs#5547]
I have Bot (Microsoft Bot framework) which I am using for Microsoft Teams channel. For one of the my task I need to use Graph API to install bot (app) directly for other users (https://docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-beta&tabs=http)
I gave correct permissions on Azure and everything works fine, bot installed successfully for all required users. 

On the other hand, after installing bot using Graph API conversationUpdate type is not generated. Please note that if I reinstall bot manually I got next request to my bot:

![image](https://user-images.githubusercontent.com/14337164/63795704-3146eb80-c90d-11e9-8ee2-d1edb79c5b83.png)

I am expecting to receive coversationUpdate type action also after Graph API installing, so I can show welcome message to user. Also I am saving Microsoft recipient id (29:1JpJET3WuYmaf0jrjUBwnFtniMl1oZTaz4_PjPqKC-SMnUJekst4YrWRv8N8PKiWgQje5USlsupmu9gSRo35Ktw) to use it later for Proactive messages in MS Teams. 

Should I expect to have conversationUpdate type action soon ? 
Is that possible to grab Microsoft Teams recipient id (29:1JpJET3WuYmaf0jrjUBwnFtniMl1oZTaz4_PjPqKC-SMnUJekst4YrWRv8N8PKiWgQje5USlsupmu9gSRo35Ktw) somehow from Graph API ? In case if I know aadObjectId (OID) ?

Thank you for a help in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a3150f8-b169-06a4-c719-0dae5426d136
* Version Independent ID: 3aae92e8-d292-ef67-99a4-d2ec29a8f4ea
* Content: [Install app for user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-add-teamsappinstallation?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-add-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-add-teamsappinstallation.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VKAlwaysWin** [comment]
Hi @clearab , thank you for a quick answer and good workaround. I can confirm that bot received conversationUpdate event after I call GET https://graph.microsoft.com/beta/users/{id}/chats?$filter=installedApps/any(x:x/teamsApp/id eq 'APP-GUID')

Please update this thread when fix will be published for install action. Thanks!

**Comment by kosset** [comment]
Having used that yesterday, I can say that this works now. 😃 

Whenever I install my App to a User through the Graph, the bot gets the _ConversationUpdate_ activity.

**Comment by GauravES** [comment]
@VKAlwaysWin  Can you please specify what permissions your App had to get this to work ? GET https://graph.microsoft.com/beta/users/{id}/chats?$filter=installedApps/any(x:x/teamsApp/id eq 'APP-GUID')
Was it Delegated or Application permissions.   (Was the user consent needed again when this call was made?)

**Comment by prashantsoni** [comment]
I have started getting issues, re-installing app does not get conversationUpdate event fired, 
tried with workaround by calling https://graph.microsoft.com/beta/users/{id}/chats?$filter=installedApps/any(x:x/teamsApp/id eq 'APP-GUID'), event that does not fire the conversationUpdate event


When I install the app for a very new user for first time I get this event fire but not for the existing users.

**Comment by rtimoshenko** [comment]
Any updates on this? I'm having the same problem.

**Comment by MasonStricklin** [comment]
> Any updates on this? I'm having the same problem.

Same, I seem to be running into this problem as well.

**Comment by tookam** [comment]
I am not receiving messages when a user gets added or deleted after installing an app programmatically (via POST installedapps). Is it related to the bug that was mentioned? Is there a fix?

**Comment by Prasad-MSFT** [comment]
Hi, we tried at our end and were able to get conversationUpdate type. Could you please share the Bot Id and Graph response?

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
