### ISSUE TITLE
Room Deatils 

### ISSUE THREAD

**Issue by lalitkohlii** [microsoftgraph/microsoft-graph-docs#5553]
how to get all room details like building name,office location and etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e21c05b-5571-2ce3-4b47-260db67b4227
* Version Independent ID: 5c59e059-49d0-0f4a-01a9-bcb268b724ec
* Content: [Create resourceOperation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-rbac-resourceoperation-create?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/intune-rbac-resourceoperation-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-rbac-resourceoperation-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Are you talking about how you get room details that are used in Outlook Calendar location?

**Comment by jthake-msft** [comment]
No response so closing this.
