### ISSUE TITLE
Missing timeout info

### ISSUE THREAD

**Issue by Misiu** [microsoftgraph/microsoft-graph-docs#5554]
I'm creating a subscription notification endpoint in Azure Function App, and because of the "cold-start" problem, sometimes when I try to create a subscription I get 400 with `Subscription validation request timed out.` message.
What is the timeout value? Can it be configured? That info is missing on the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
The timeout is 10 seconds, as documented here. no, it cannot be configured.
https://docs.microsoft.com/en-us/graph/webhooks#notification-endpoint-validation
