### ISSUE TITLE
403 response when searching as an application with Files.Read.All and Sites.Read.All permissions

### ISSUE THREAD

**Issue by ericdepotter** [microsoftgraph/microsoft-graph-docs#5556]
I'm trying to perform a search action as an application. The application has both Files.Read.All and Sites.Read.All permissions. This should be enough according to the documentation. However I get the following 403 response:
{
  "error": {
    "code": "accessDenied",
    "message": "The caller does not have permission to perform the action.",
    "innerError": {
      "request-id": "173eeb8f-2d35-42c4-94da-df670fb6cdc2",
      "date": "2019-08-28T08:52:12"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de33ed18-c074-a734-0b01-648888cb94aa
* Version Independent ID: 9fa15051-394e-d4ce-4687-c93be0ca8b80
* Content: [Search for files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by mbv401920150** [comment]
Try including all permissons in order:
Files.Read Files.ReadWrite Files.Read.All Files.ReadWrite.All Sites.Read.All Sites.ReadWrite.All
