### ISSUE TITLE
getTenantSecureScores does't return max data/device/app score

### ISSUE THREAD

**Issue by tadawID** [microsoftgraph/microsoft-graph-docs#5558]
Issue:
Requesting https://graph.microsoft.com/stagingBeta/reports/getTenantSecureScores(period=1)/content
returns identity/device/data/app score, but not max possible score, so it is useless. Can you please add max possible scores to be reached within those specific areas?

"secureScore":  356,
    "maxSecureScore":  807,
    "identityScore":  77,
(e.g.) ++++++ "maxIdentityScore": 100
    "dataScore":  79,
    "deviceScore":  160,
    "appsScore":  40,

Article:

**Comment by NaynaSheth** [comment]
The customer should be using:
https://graph.microsoft.com/v1.0/security/secureScores
To get their score
                {
                    "controlCategory": "Data",
                    "controlName": "Enable mailbox auditing for all users",
                    "description": "You should enable mailbox auditing for at least ninety percent of all users that have mailboxes in your tenancy. By default all non-owner access is audited, but you must enable auditing on the mailbox for owner access to also be audited. This will allow you to discover illicit access of Exchange Online activity if a user's account has been breached.",
                    **"score": 10,**
                    "total": "69",
                    "count": "50"
                },
And then they can call:
https://graph.microsoft.com/v1.0/security/secureScoreControlProfiles
To get the max scores per control
        {
            "id": "MailboxAuditingEnabled",
            "azureTenantId": "00000001-0001-0001-0001-000000000001",
            "actionType": "Config",
            "actionUrl": "https://github.com/OfficeDev/O365-InvestigationTooling/blob/master/EnableMailboxAuditing.ps1",
            "controlCategory": "Data",
            "title": "Enable mailbox auditing for all users",
            "deprecated": false,
            "implementationCost": "Low",
            "lastModifiedDateTime": "2019-12-30T15:36:00Z",
            **"maxScore": 15,**
            "rank": 6,
            "remediation": "Running the PowerShell script linked below will turn on owner activity mailbox auditing for all mailboxes in your service. By default all non-owner access and administrative actions are recorded, but owner actions are not. Enabling mailbox auditing will include owner activity in the audit records, which will in turn enable you to investigate and scope a compromise of that user's account.",
            "remediationImpact": "This change will have no effect on your users.",
            "service": "EXO",
            "threats": [
                "Account Breach"
            ],
