### ISSUE TITLE
API returns "300 Multiple Choices" response.

### ISSUE THREAD

**Issue by Arisaka-Mashiro** [microsoftgraph/microsoft-graph-docs#5559]
It's not written in the document. 
This problem occurs when you invite some users.
Why return a 300 Multiple Choices HTTP response?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51b2654-e447-d495-2788-d6d5b13402b4
* Version Independent ID: 32183c44-363a-a028-a3d9-390b99bffc8b
* Content: [Create invitation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/invitation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/invitation-post.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
When I use the information in this page to create an invitation, I get a 201 Created response code. Not understanding the issue. Closing the issue until more information can be provided.
