### ISSUE TITLE
What is the maximum possible page size? 

### ISSUE THREAD

**Issue by Samhithgb** [microsoftgraph/microsoft-graph-docs#5565]
No documentation on maximum possible size for each page returned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0169c1-e6e7-da8f-4158-5e721eae8b9a
* Version Independent ID: f2907cde-b9d7-4ba7-e813-047e5b938e50
* Content: [List messages - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-messages.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as this doc has been updated already.
"Depending on the page size and mailbox data, getting messages from a mailbox can incur multiple requests. The default page size is 10 messages. Use $top to customize the page size, within the range of 1 and 1000."
