### ISSUE TITLE
Does delta query support $top query parameter? 

### ISSUE THREAD

**Issue by Samhithgb** [microsoftgraph/microsoft-graph-docs#5566]
We are trying out delta query for List Messages API in Graph Explorer and looks like it does not honor $top query parameter. Documentation required on the same. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview#feedback)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@piotrci I also had Support ask me if delta query response can send more than 200 object pages (for DQ on /users)...  Be good to clarify across the board.

**Comment by piotrci** [comment]
Thanks. PR here: https://github.com/microsoftgraph/microsoft-graph-docs/pull/5612

**Comment by jrlatta** [comment]
I just tried hitting 

_'https://graph.microsoft.com/v1.0/users/[user_id]/mailFolders/[mail_id]/messages/delta?select=subject,sender&top=20'_

and it only returned me 10 values. When I make that call for the non-delta method, I get the requested 20 values.

I saw it was fixed in #5612 but maybe this change isn't live in v1.0?
