### ISSUE TITLE
Pre-consent script needs additional parameter

### ISSUE THREAD

**Issue by morcinim** [microsoftgraph/microsoft-graph-docs#5578]
Hello,
Make sure you use -All attribute when enumerating service principals, especially if you are pre-consenting *an existing* application (rather than creating a new one)
$s = Get-AzureADServicePrincipal -All $true  | ? {$_.AppId -eq $AppId}

Otherwise you will likely see an error "Another object with the same value for property servicePrincipalNames already exists" as the script tries to create service principal although one already exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 901ad71a-7fa8-cb4a-ffe4-396d6b52ccf9
* Version Independent ID: 903c43d0-41d3-99cf-c289-644e64c9b801
* Content: [Call Microsoft Graph from a Cloud Solution Provider application - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-cloudsolutionprovider?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#feedback)
* Content Source: [concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-cloudsolutionprovider.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
The example in this document uses a server-side filter on `appId`, which is guaranteed to return no more than one ServicePrincipal object, so the `-All` parameter is not needed.

```powershell
$sp = Get-AzureADServicePrincipal -Filter "appId eq '{yourAppsAppId}'"
```
