### ISSUE TITLE
Calendar ID from POST response sometimes differs from the ID Graph stores

### ISSUE THREAD

**Issue by crice88** [microsoftgraph/microsoft-graph-docs#5580]
The issue that I am having is that with some user accounts, the calendar ID returned from `POST /me/calendars` differs from the ID that we get back from a `GET /me/calendars`.

If we rely on the ID returned from the POST response, the ID can sometimes change in which we receive an error that the resource doesn't exist. This behavior only happens on a subset of the Outlook accounts we deal with. This can be problematic as we now need to block for an unspecified time to see if the Calendar ID does indeed change.

Not seeing it in the documentation, but is there a more unique value we can save that won't change? My first assumption is that this may be a bug in the actual Graph API and that the documentation is correct.

Reference: https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

**Comment by jthake-msft** [comment]
There is a topic on immutable ids which I'd recommend you take a look at. The page is found under the Calendar section in the docs link in the top navigation of our portal.
https://docs.microsoft.com/en-us/graph/outlook-immutable-id

**Comment by crice88** [comment]
Thanks for link @jthake-msft . This doesn't solve my issue as stated in the documentation: "Container types (mailFolder, calendar, etc.) do not support immutable ID, but their regular IDs were already constant.". 

My issue is that this is not always the case. The ID's for the calendars change for some users within minutes of creating the container.

**Comment by jasonjoh** [comment]
The calendar team has been getting intermittent reports of this and is investigating.

**Comment by crice88** [comment]
@jasonjoh thanks for the info! Is there a better place to report these types of issues??

**Comment by jasonjoh** [comment]
Besides contacting support via the Azure portal, there isn't really a better place. That being said this isn't a great place either since it's just the documentation repository :).

In any event, if you're up for it, the calendar team would love to get some more data on this. If you can reproduce this fairly consistently, have you noticed any pattern (user-created calendar vs. default, type of user, etc.)? If you do your GET with the following HTTP header: `Prefer: odata.track-changes`, does it provide a consistent ID?

**Comment by crice88** [comment]
That's the rough part... It's completely intermittent. Only a subset of our users experience the bug. We only create calendars via the Graph API and the last time we experienced an issue was with an account that was recently created by one of our QA's (just a basic Outlook account). Bummer is that this account was deleted before I could pull more data from it.

I created an issue on StackOverflow that contains our actual payloads (https://stackoverflow.com/questions/57682515/calendar-id-in-create-response-differs-from-what-graph-stores). May have a dead giveaway in the responses?? 

Barring any conclusions in the mean time, I can make sure that if we run into the issue with an account we control again, we'll make sure to provide any data you need to solve this.

We really appreciate the help on this one, it's been boggling our minds for the past few months.

**Comment by jasonjoh** [comment]
Yes, that's the rough part for us too :). What would potentially help is if you hit the repro, if you could log the full response with headers and send those our way. There are diag headers in the response that can enable us to look up our internal logging to see if there's anything helpful there.

**Comment by crice88** [comment]
@jasonjoh we are in luck! We had a user that experienced the bug today. Below are the headers we logged.

This is the response header when we created the calendar:
```json
{
"cache-control"=>["private"], 
"content-type"=>["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"], 
"location"=>["https://outlook.office.com/api/v2.0/Users(<user removed>)/Calendars('AAMkADQ4Mjg4NjU5LTEzMTMtNDhmMC05MGFjLTExZThjMjQ2MWI1YQBGAAAAAABMcIkhLVQcS5wvv15pJfw8BwAgqL_oUegKQIqTVgoLGEV4AAAAAAEGAAAgqL_oUegKQIqTVgoLGEV4AAPIWHxJAAA=')"], 
"request-id"=>["afe5b304-e3e5-4d57-9ccf-6900553ad4b3"], 
"client-request-id"=>["afe5b304-e3e5-4d57-9ccf-6900553ad4b3"], 
"x-ms-ags-diagnostic"=>["{\"ServerInfo\":{\"DataCenter\":\"South Central US\",\"Slice\":\"SliceC\",\"Ring\":\"5\",\"ScaleUnit\":\"002\",\"RoleInstance\":\"AGSFE_IN_10\"}}"], 
"odata-version"=>["4.0"], 
"strict-transport-security"=>["max-age=31536000"], 
"date"=>["Thu, 24 Oct 2019 17:42:56 GMT"], 
"connection"=>["close"], 
"content-length"=>["510"]
}
```

This is an event create success header response (201) right after we created the calendar:
```json
{
"cache-control"=>["private"],
 "content-type"=>["application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"], 
"etag"=>["W/\"IKi/qFHoCkCKk1YKCxhFeAADyRwAKw==\""], 
"location"=>["https://outlook.office.com/api/v2.0/<user removed>/Events('AAMkADQ4Mjg4NjU5LTEzMTMtNDhmMC05MGFjLTExZThjMjQ2MWI1YQBGAAAAAABMcIkhLVQcS5wvv15pJfw8BwAgqL_oUegKQIqTVgoLGEV4AAPIV4bnAAAgqL_oUegKQIqTVgoLGEV4AAPIWIRrAAA=')"], 
"request-id"=>["64a31bb4-1fad-4b8c-9a0b-1509619b84ca"], 
"client-request-id"=>["64a31bb4-1fad-4b8c-9a0b-1509619b84ca"], 
"x-ms-ags-diagnostic"=>["{\"ServerInfo\":{\"DataCenter\":\"South Central US\",\"Slice\":\"SliceC\",\"Ring\":\"5\",\"ScaleUnit\":\"003\",\"RoleInstance\":\"AGSFE_IN_14\"}}"], 
"odata-version"=>["4.0"], 
"strict-transport-security"=>["max-age=31536000"],
 "date"=>["Thu, 24 Oct 2019 17:43:24 GMT"], 
"connection"=>["close"], 
"content-length"=>["2154"]
}
```

And just a moment later when we tried to create another event into that same calendar ID, this was the header response (404):
```json
{
"cache-control"=>["private"], 
"content-type"=>["application/json"], 
"request-id"=>["ad339dce-fdef-4539-8f1f-164d28b62ad4"], 
"client-request-id"=>["ad339dce-fdef-4539-8f1f-164d28b62ad4"], 
"x-ms-ags-diagnostic"=>["{\"ServerInfo\":{\"DataCenter\":\"South Central US\",\"Slice\":\"SliceC\",\"Ring\":\"5\",\"ScaleUnit\":\"001\",\"RoleInstance\":\"AGSFE_IN_12\"}}"], 
"strict-transport-security"=>["max-age=31536000"], 
"date"=>["Thu, 24 Oct 2019 17:43:24 GMT"], 
"connection"=>["close"], 
"content-length"=>["251"]
}
```

If you need anymore details let me know!

**Comment by crice88** [comment]
@jthake-msft can we get this reopened as it's an issue for some?
