### ISSUE TITLE
Chat.Read permission can't be set for Applications from personal account

### ISSUE THREAD

**Issue by VKAlwaysWin** [microsoftgraph/microsoft-graph-docs#5582]
When I am trying to set Chat.Read permission for application from personal account  (Azure Active Directory):
![image](https://user-images.githubusercontent.com/14337164/64042342-54220b80-cb6a-11e9-9500-3b2e1f29132e.png)

 I see next error:
![image](https://user-images.githubusercontent.com/14337164/64042251-2a68e480-cb6a-11e9-89d4-90407ee24f60.png)

With the same app, but from "Owned applications"
I see that everything is ok:
![image](https://user-images.githubusercontent.com/14337164/64042469-8af82180-cb6a-11e9-9338-da97701d4582.png)

Is that an issue with Chat.Read permission or I am doing something wrong ?
As a result I can't use:

GET /users/{id}/chats/{id}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed40734-37bb-8459-962a-f9dc9c15c7d3
* Version Independent ID: faaa6ab2-be92-05fc-9adb-34dcf8fee7cb
* Content: [Get chat - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
@dkershaw10, insights on why we the portal allows one app to do this but not the other?

**Comment by VKAlwaysWin** [comment]
Ok, I found what is going on.

My app from App Studio (MS Teams) was created with next param:
"signInAudience": "AzureADandPersonalMicrosoftAccount",

This is from manifest on Azure.

In case if I change it manually to:
"signInAudience": "AzureADMultipleOrgs",

Then Chat.Read can be set. Is that requirement to use Chat.Read ?
Thank you in advance.

**Comment by nkramer** [comment]
Not sure I'm following -- Chat.Read doesn't support MSAs only AAD. To the extent the AAD portal handles that poorly, that's a product bug rather than a doc bug to track in the docs repo.
