### ISSUE TITLE
The java sdk client is missing the methods for the IWorkbookWorksheetRangeRequestBuilder class

### ISSUE THREAD

**Issue by dmolaro-jama** [microsoftgraph/microsoft-graph-docs#5585]
The *java* sdk client is missing the methods for the IWorkbookWorksheetRangeRequestBuilder class that are documented, with the exception of buildRequest.
```
        <dependency>
            <groupId>com.microsoft.graph</groupId>
            <artifactId>microsoft-graph</artifactId>
            <version>1.6.0</version>
        </dependency>
```
Example:
```
graphClient.me().drive().items("{id}").workbook().worksheets("{sheet-id}")
	.range("$A$1").format().font()
	.buildRequest()
	.patch(workbookRangeFont);

.format() is not available, as well as .clear(), .merge(), .delete() etc...
```
---- Davide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e47328b2-0c19-aee0-ec60-b307089f4c9e
* Version Independent ID: 36760844-cbc4-614c-b0d3-0ca00dd25fd5
* Content: [Update rangeformat - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/rangeformat-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/rangeformat-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/rangeformat-update.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @dmolaro-jama 
Thanks for reaching out.
This was added with version 2.1.0 of the SDK. https://github.com/microsoftgraph/msgraph-sdk-java/blame/2c6e50743a478bf8b48342fed28166100a75093b/src/main/java/com/microsoft/graph/requests/extensions/IWorkbookWorksheetRangeRequestBuilder.java#L38

Closing.
