### ISSUE TITLE
Find meeting times problem

### ISSUE THREAD

**Issue by Rami-KH** [microsoftgraph/microsoft-graph-docs#559]
{
"error": {
"code": "ErrorAccessDenied",
"message": "Access is denied. Check credentials and try again.",
"innerError": {
"request-id": "ec3a5d39-5d12-4069-bb76-3a35b60ace59",
"date": "2016-10-12T12:44:12"
}
}
}
I Have added Calendars.ReadWrite.Shared & Calendars.Read.Shared permission for the app. 

Is there any reason why this won't work?

**Comment by angelgolfer-ms** [comment]
@Rami-KH - we're working on fixing an issue with the scopes required for findMeetingTimes. When that is fixed, the required scope remains to be Calendars.Read.Shared or Calendars.ReadWrite.Shared. We'll let you know when the fix is available. Thank you for your patience!

**Comment by dclohman** [comment]
Any updates to this fix?

**Comment by angelgolfer-ms** [comment]
Hi @Rami-KH and @dclohman, thanks for your patience. Would you like to try one of the said scopes to access findMeetingTimes at your convenience, and let us know if you still have problems? Thanks.

**Comment by dclohman** [comment]
I tried, still got 403 Access Denied.

**Comment by marych** [comment]
@dclohman - could you please provide request-id and timestamp for a sample 403 response? Note that your app needs to be re-consented after you add the *.Shared delegated permissions if the user consented before the change of permissions.

**Comment by dclohman** [comment]
{
  "error": {
    "code": "ErrorAccessDenied",
    "message": "Access is denied. Check credentials and try again.",
    "innerError": {
      "request-id": "bbaf5b4d-c8f9-4666-9e0f-56b7e0045e18",
      "date": "2016-10-21T11:42:48"
    }
  }
}
Here is the info.  Has this API call changed as I was using App-only permissions.  I am communicating service to service so there is no User intervention. It worked fine previous to the last changes.

**Comment by dclohman** [comment]
Any update on this?  This appears to be the only API call that is no longer working with App-only permissions.  We are using the API call in a customer demonstration app, so if I can no longer authenticate this way I will need to look at different way to accomplish getting to recipients calendars for event correlation.

**Comment by dclohman** [comment]
Still getting access denied 403

**Comment by marych** [comment]
@dclohman - the fix that @angelgolfer-ms was referring to was only relevant for requests with delegated permissions. The API is not currently accessible with app-only permissions.

**Comment by dclohman** [comment]
Is there a roadmap timeline?  Never going to work with app-only permissions?  Trying to figure out if I am waiting or start re-writing code.

**Comment by dclohman** [comment]
Anything?

**Comment by Nickxsch** [comment]
dclohman, ever got this working? I (still) have this issue now. At first I thought this was an admin-assigned permission, but it is not. So what is wrong? Is it still being fixed? Via the Graph explorer, it works fine. Via my app, it does not.

**Comment by paulociencia** [comment]
I have the same issue, could you help us please.

**Comment by paulociencia** [comment]
Hey guys,  any guys get any solution or workround for that issue?
i've had this problem with app-only.

**Comment by nthjelme** [comment]
I have the same issue. Haven't fond a workaround for it.

**Comment by mmierzwa** [comment]
Same for me...

**Comment by tpaivaa** [comment]
@mmierzwa you can set permissions for delegated permissions which you use in Azure Graph API Explorer but not for the Application at least at the moment...

**Comment by mmierzwa** [comment]
Thx for update. Any timeline for resolving the issue?

**Comment by NielsGregers** [comment]
Looking forward for a solution here

**Comment by sergiomieic** [comment]
Any update on this?

**Comment by darrenparkinson** [comment]
Any updates?  I'm still getting this issue.  Thanks.

**Comment by BinduPriyaKalathuru** [comment]
Has there been any update on it? I get a HTTP 401 error when I try calling the API.

**Comment by Kaapiii** [comment]
The same thing here.

**Comment by darrenparkinson** [comment]
Could we please get an update on this issue?  Is it ever going to work?  Some kind of timeline?  We can then all decide if we should wait or get on with our lives.  Many thanks.

**Comment by arunv-msft** [comment]
Sorry about the delay in getting this resolved. We are not actively investigating the issue with the goal of pushing out a fix in the next few weeks. I'll post updates regularly on our progress. Thanks for your patience and support.

**Comment by ramseen** [comment]
hi team , i have the same 403 issue , it is working fine in the graph explorer but its getting 403 in postman . could you please resolve this issue .

**Comment by nthjelme** [comment]
Any updates? And where will you post updates on your progress?

**Comment by MarkusBrun** [comment]
@arunv-msft Are you posting regular updates somewhere other than this thread?

**Comment by darrenparkinson** [comment]
@arunv-msft Any updates?  It's been a few weeks since you suggested it would be a few weeks?  Thanks.

**Comment by dborstelmann** [comment]
@arunv-msft Any plan to make this work?

**Comment by ArunMSFT** [comment]
We attempted to resolve the issue a few weeks back but ran into some unforeseen issues. We are still actively looking into this issue but don't have an ETA yet. Sorry this is taking us to longer to resolve this issue.

**Comment by mjsommer** [comment]
For what its wroth here, I can make the same POST `https://graph.microsoft.com/v1.0/me/findMeetingTimes` call in Graph Explorer (where it works), and the Microsoft sample Rails app (where it gives me the 403 error). The authentication credentials are the same in both.

What is unique in the Graph Explorer `https://developer.microsoft.com/en-us/graph/graph-explorer#` app, vs the Microsoft sample Rails app `https://developer.microsoft.com/en-us/graph/docs/concepts/ruby`?

Please note that the SendMail example works in the sample app, but a POST call to `https://graph.microsoft.com/v1.0/me/findMeetingTimes` gives a 403 error.

**Comment by mjsommer** [comment]
Got it! Needed to expand the privs in `/config/environment.rb` to include Calendars:

```
ENV['OAUTH_SCOPE'] = "openid email profile \
  https://graph.microsoft.com/User.Read \
  https://graph.microsoft.com/Mail.Send \
  https://graph.microsoft.com/Calendars.Read.Shared \
  https://graph.microsoft.com/Calendars.ReadWrite.Shared"

```

**Comment by aherrick** [comment]
Before EOY?

**Comment by zdravkoggeorgiev** [comment]
Issue reported 2016, now it's 2018, still no progress.
 And i spent few hours to check my code & permissions, before hit this thread in google.

**Comment by mtnrbq** [comment]
@dmahugh @ArunMSFT  - can someone from Microsoft post a summary of the status of this issue with specific details as this thread has a number of conflicting and confusing notes.

- Is this call currently supported for Application permissions only - i.e. no delegated permissions?
- If not, when will it be?
- If there is a workaround using delegated permissions, what are the exact permissions and scopes required?

Thanks

**Comment by petterkjeilen** [comment]
Yes, can you please add (soon..) support for Application permissions only when using findMeetingTimes.

@yinaa @ArunMSFT  

Thanks

**Comment by JV256** [comment]
So with application permissions I can:

Find a person.
Read their email.
Delete their email.

But I can't:
FindMeetingTimes

Please fix this...

**Comment by fhusoy** [comment]
Would be nice to know if this is something that will be fixed and when we can expect progress on this isssue.

@ArunMSFT @crchung-MSFT

**Comment by turbowars** [comment]
any workaround folks?

**Comment by BenAffleckIsBatman** [comment]
Anything here @ArunMSFT @crchung-MSFT ?

**Comment by turbowars** [comment]
@BenAffleckIsBatman We realised that we were not sending the correct scope during the first authorization call. 

Would suggest you to decrypt your token here (http://jwt.calebb.net/) and find the difference between the tokens. (generated using https://developer.microsoft.com/en-us/graph/graph-explorer and your local api call.)

**Comment by mtnrbq** [comment]
@dmahugh @ArunMSFT @jthake  @angelgolfer-ms - can someone from Microsoft post a summary of the status of this issue with specific details as this thread has a number of conflicting and confusing notes.

1. Is this call currently supported for Application permissions only - i.e. no delegated permissions?

2. If not, when or will it be?

I do not want to have to give an app delegated permissions - as per earlier note from @angelgolfer-ms , the application scope needed was going to be Calendars.Read.Shared or Calendars.ReadWrite.Shared from what I can understand.

Thanks

**Comment by ArunMSFT** [comment]
1. Issue - FindMeetingTimes API is not available in the App only scenario, today it works only in the delegated permissions scenario.
2. Workaround - Currently there are no workarounds available for pure app-only scenarios. You could get access to the API with user-delegated flow
3. Future plans - Our goal is to support this API in the app only scenario. @crchung-MSFT can add more details on timing.

Thanks,
Arun

**Comment by SuneetPatil** [comment]
Hi @turbowars, i tried following ur instructions. the app is working in https://developer.microsoft.com/en-us/graph/graph-explorer but when i try the same using postman using the access token im getting Access is denied. Check credentials and try again. Can u please help me in resolving it or share your inputs did you try getting the result in postman.?

Thanks,
Suneet

**Comment by ramseen** [comment]
Hi all , This is working for me well. only thing i have done is, provided delegate permission to the APP which i have created in azure AD. make calendar.shared and write permissions as delegate. If anyone want more about the working scenario, I can explain. please let me know.

**Comment by SuneetPatil** [comment]
Hi @ramseen, Thank for your reply and happy to know its working for you. My requirement is accessing the find meeting times API directly using my java back end code to get check the availability. I need to access it using app only and i'm integrating with Alexa device and we wont have any UI to delegate the access from user end. 
Can u please explain your user case or in brief how did you achieve or is ur scenario matches my requirement? Thanks in advance for your response.

**Comment by jnlkds** [comment]
In our institution we have an immediate need to know what conference room is "immediately" available such that we can have a meeting. Taking the time to open outlook, look for attendees and then find out what resources (i.e rooms) takes too long. Hence FAR is supposedly report back to the user what rooms are available "right now", allow them to book and folks will meet.

Unfortunately, I am finding that FindMeetingTimes DOES NOT yield a long list of rooms and provide their availability, it provides a short list and want for call to provide some means to extend or filter the list.


________________________________

**Comment by sGaster** [comment]
Any updates to this issue? Facing the same problem: Acces denied for application based permission type.

**Comment by ramseen** [comment]
@SuneetPatil Hi Suneet , As per my understanding it wont work with app only permission. You have to prompt the user to be signed in against the azure ad app which has permission to read all calendars.  in my case the scenario is different We are trying to develop a meeting scheduler in chat bot level. there user can prompt for signed in. So easily we will get the bearer token after sign on.

**Comment by sGaster** [comment]
@SuneetPatil same scenario for me. For the moment we think to throw out our own authentication and use microsoft 365 authentication for our chat-bot as workaround. But if microsoft enables us to do this with app scope based permissions this would be the better solution for everyone.

**Comment by darrenparkinson** [comment]
Seriously, any further update on this.  It's been TWO YEARS!  Just be honest.  If you're not going to fix it, please just tell us that.  Thanks.

**Comment by midrissi** [comment]
Any updates on this issue? I got the same error with graph explorer.
Here is my decoded token:
```json
{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/81e24fe6-fe2d-40d2-9739-126e5b569b6a/",
  "iat": 1533716870,
  "nbf": 1533716870,
  "exp": 1533720770,
  "acct": 0,
  "acr": "1",
  "aio": "AUQAu/8IAAAAIKXVBC07EXKw/QcXg0c5h+SYpc2iShyuSffv7FeeVxbmHWLekJqkxoEBM0xcjfkQkQtIKKKQv8ua7yUt9qqKuQ==",
  "amr": [
    "wia",
    "mfa"
  ],
  "app_displayname": "Graph explorer",
  "appid": "de8bc8b5-d9f9-48b1-a8ad-b748da725064",
  "appidacr": "0",
  "family_name": "Family Name",
  "given_name": "Given Name",
  "name": "Full Name",
  "oid": "e13a5ed9-007b-4976-9450-fb711ac5d932",
  "onprem_sid": "S-1-5-21-1999991193-4164165691-3874356750-43550",
  "platf": "3",
  "puid": "10030000A0BCC435",
  "scp": "Bookings.Read.All Bookings.ReadWrite.All BookingsAppointment.ReadWrite.All Calendars.Read Calendars.Read.Shared Calendars.ReadWrite Calendars.ReadWrite.Shared Contacts.Read Contacts.Read.Shared Contacts.ReadWrite Contacts.ReadWrite.Shared Device.Command Device.Read Files.Read Files.Read.All Files.Read.Selected Files.ReadWrite Files.ReadWrite.All Files.ReadWrite.AppFolder Files.ReadWrite.Selected Financials.ReadWrite.All Mail.Read Mail.Read.Shared Mail.ReadWrite Mail.ReadWrite.Shared Mail.Send Mail.Send.Shared MailboxSettings.ReadWrite Notes.Create Notes.Read Notes.Read.All Notes.ReadWrite Notes.ReadWrite.All openid People.Read profile Sites.Read.All Sites.ReadWrite.All Tasks.Read Tasks.Read.Shared Tasks.ReadWrite Tasks.ReadWrite.Shared User.Read User.ReadBasic.All User.ReadWrite email UserActivity.ReadWrite.CreatedByApp",
  "sub": "kBKIRjRJQZZU5LBAdZQypnCsRtHmlaivlA9tnjSea0M",
  "tid": "81e24fe6-fe2d-40d2-9739-126e5b569b6a",
  "unique_name": "someemailaddress@microsoft.com",
  "upn": "someemailaddress@microsoft.com",
  "uti": "w592kVp4UUW907TLDnAdAA",
  "ver": "1.0",
  "xms_st": {
    "sub": "B6ic6OYhO4ab1B3TD5asnUaMk_vdfqyA3dF6gVMtBT0"
  }
}
```
And Here is a preview of the permissions list:
![graph](https://user-images.githubusercontent.com/3237344/43826254-32243200-9af7-11e8-8f6f-1214575c4300.png)

Everytime I run the requet, I get this:
![capture](https://user-images.githubusercontent.com/3237344/43826393-7c54ef40-9af7-11e8-9e58-17ee157ca682.PNG)

Any help?
Thanks

**Comment by mufsir** [comment]
Any updates on this issue? I'm getting the same 403 error in Graph Explorer.

**Comment by mtnrbq** [comment]
as per earlier update from @ArunMSFT (June 20) @crchung-MSFT 

1. Issue - FindMeetingTimes API is not available in the App only scenario, today it works only in the delegated permissions scenario.

2. Workaround - Currently there are no workarounds available for pure app-only scenarios. You could get access to the API with user-delegated flow

3. Future plans - Our goal is to support this API in the app only scenario. @crchung-MSFT can add more details on timing.
Thanks,
Arun

**Comment by mufsir** [comment]
@ramseen I'm also getting the same error. So I created an app in Azure AD with delegated permission. Can you please help me on the authentication URL format where the user needs to sign in?

**Comment by mufsir** [comment]
@mtnrbq @ArunMSFT 

Can anyone please confirm that this API is supported by **personal Microsoft account**? I tried using graph API v1.0, but no luck. In the [beta API docs](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/user_findmeetingtimes), it is mentioned that this API will only work with Delegated (work or school) accounts.

Thanks,
Mufsir

**Comment by venkatatholetinextdc** [comment]
Can you please provide more context on the alternatives that are available to make the API work? How can we access the API through delegated permissions or through user-delegate flow? Please provide some additional guidance. Thanks

**Comment by mtnrbq** [comment]
@venkatatholetinextdc  - Hi, I was only re-surfacing the last update I could find, as the thread is a little muddled. - I do not have any additional insight or guidance, apologies for any confusion

**Comment by theakc** [comment]
At this moment, we do not have plans to support App-Only token. Only user delegated token are supported. We will work to support this in future ( no timeline yet).

This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph )' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
Feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support

**Comment by abhaythaku** [comment]
> @Rami-KH - we're working on fixing an issue with the scopes required for findMeetingTimes. When that is fixed, the required scope remains to be Calendars.Read.Shared or Calendars.ReadWrite.Shared. We'll let you know when the fix is available. Thank you for your patience!



> Could we please get an update on this issue? Is it ever going to work? Some kind of timeline? We can then all decide if we should wait or get on with our lives. Many thanks.

if we call this api https://graph.microsoft.com/beta/me/people  then solve you issue because currently Microsoft working on this functionality.

**Comment by bsdaniel** [comment]
Hi, I have an application written in nodejs that can read all users in a tenant and creates a calendar event on each of their calendars in outlook. I am now attempting to use the Findmeetingtimes API through code and no results are returned when the URL is called. All requests work in the graph explorer and I would presume that if it works in the Graph Explorer then it would return something once the app is up and running, but it does not do this.  Any help would be extremely helpful. Thanks.
