### ISSUE TITLE
tooManyRetries

### ISSUE THREAD

**Issue by fredericklin** [microsoftgraph/microsoft-graph-docs#5592]
I'm getting this error when iterating through OneNote notebooks:

StatusCode: 0
Code: tooManyRetries
Message: More than 3 retries encountered while sending the request

Can there be some documentation on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77cc3520-96d8-6aa4-1243-20b7f4d5c4cb
* Version Independent ID: 79a31ea9-d9b3-2602-e412-4959498a11c0
* Content: [Microsoft Graph error responses and resource types - Microsoft Graph](https://docs.microsoft.com/en-us/graph/errors)
* Content Source: [concepts/errors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/errors.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Have you looked at the throttling guidance here? If you use our SDKs, there is built in middleware that will handle this for you. https://docs.microsoft.com/en-us/graph/throttling
