### ISSUE TITLE
Group.ReadWrite.All permissions for Reply to a message in a channel

### ISSUE THREAD

**Issue by tempora-mutantur** [microsoftgraph/microsoft-graph-docs#5594]
Hi.
I have a little question regarding permissions for the "Reply to a message in a channel" functionality. It requires the "Group.ReadWrite.All" permissions. Could you please, describe if this really necessary to have such privileges or maybe it should change sometimes. Because it's not very clear that you need have such high level of permissions for this simple action.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78d7f28-2ac1-bdc1-4ac5-3a20756270be
* Version Independent ID: 353e1a63-1ae9-201a-4ac2-8949b164788f
* Content: [Reply to a message in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messagereply.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
Yes, it's required today. We are working on improvements.
