### ISSUE TITLE
mobileDeviceManagementAuthority not present on API endpoint

### ISSUE THREAD

**Issue by JSOnions** [microsoftgraph/microsoft-graph-docs#5595]
Whether using the BETA or v1.0 of this API I do not receive "mobileDeviceManagementAuthority" within the response. Truncated response  below:

"value": [
        {
            "id": "00000000",
            "deletedDateTime": null,
            "businessPhones": [],
            "city": "London",
            "country": null,
            "countryLetterCode": "GB",
            "createdDateTime": "2018-03-27T13:06:30Z",
            "displayName": "00000000",
            "marketingNotificationEmails": [],
            "onPremisesLastSyncDateTime": "2019-09-02T09:06:30Z",
            "onPremisesSyncEnabled": true,
            "postalCode": "00000000",
            "preferredLanguage": "en",
            "securityComplianceNotificationMails": [],
            "securityComplianceNotificationPhones": [],
            "state": null,
            "street": "00000000",
            "technicalNotificationMails": [
                "00000000"
            ],
            "assignedPlans": [
                {
                    "assignedDateTime": "2019-07-31T14:22:58Z",
                    "capabilityStatus": "Deleted",
                    "service": "Windows"....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0fd8073-a487-e3f6-e022-6aeb4f58d8e5
* Version Independent ID: d537bc0d-8d9d-2721-761e-38a072ac1b31
* Content: [List organizations - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-onboarding-organization-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-onboarding-organization-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-onboarding-organization-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rolyon** [comment]
Hi @JSOnions 
Here is what we heard from the team:
The only way to get mobileDeviceManagementAuthority off of the shared organization entity is to perform a $select. Use one of the following calling patterns:
GET https://graph.microsoft.com/beta/organization('{id}')?$select=mobileDeviceManagementAuthority
GET https://graph.microsoft.com/beta/organization/{id}?$select=mobileDeviceManagementAuthority
thanks

**Comment by rolyon** [comment]
Please reopen this issue if you have additional feedback.
thanks

**Comment by rolyon** [comment]
#please-close

**Comment by JSOnions** [comment]
Thanks, that's helpful. But there is still the issue with the documentation being incorrect.

The example request is just a GET to /organization, which does not return the example response (the subject of my initial feedback item). Please can the documentation be updated to either include two examples, the general GET to return the actual organization details, and another with your request example above returning the MDM authority. Or just include the correct response to the existing example request. Thanks

**Comment by rolyon** [comment]
Hi @JSOnions 
Okay, thanks. I sent this feedback to the team to review.

**Comment by triplanedave** [comment]
Based on Rolyon's comment, closing this issue.  Our documentation is generated programmatically, so sometimes I see that the response body isn't 100% complete.  It's intended as a guideline - I know, it could be improved, I've filed a bug on our team to see if we can improve the accuracy of the response body sample.
