### ISSUE TITLE
Using the providers - Heading leads to 404

### ISSUE THREAD

**Issue by BeJoNe** [microsoftgraph/microsoft-graph-docs#5596]
https://docs.microsoft.com/en-us/graph/toolkit/overview?context=graph%2Fapi%2Fbeta&view=graph-rest-beta
open "Providers" and click on "Using the providers" -> 404 not found

checked 
https://github.com/microsoftgraph/microsoft-graph-docs/tree/master/concepts/toolkit/providers
and indeed, there is no "using.." file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a3d3fb-2489-3738-66b7-02dc58e74462
* Version Independent ID: 69d3020d-f6ce-c54b-52fc-dd8b0060e301
* Content: [Custom provider - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/providers/custom?context=graph%2Fapi%2Fbeta&view=graph-rest-beta)
* Content Source: [concepts/toolkit/providers/custom.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/toolkit/providers/custom.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @nmetulev
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmetulev** [comment]
This doesn't seem to happen when I remove the query parameters from the url: https://docs.microsoft.com/en-us/graph/toolkit/overview

The toc seems to be fine: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/toc.yml#L403

@Lauragra, any idea?

**Comment by nmetulev** [comment]
Closing issue as it no longer repros
