### ISSUE TITLE
error when updating dates

### ISSUE THREAD

**Issue by Ballzer0** [microsoftgraph/microsoft-graph-docs#5597]
When i try to update Date properties like Birthday or HireDate using the following request i get an error
permission used: https://graph.microsoft.com/User.ReadWrite.All

**REQUEST**
```
PATCH https://graph.microsoft.com/v1.0/users/{UserID}
{
    "hireDate": "1995-01-01T00:00:00Z"
}
```

**RESPONSE**
```
{
  "error": {
    "code": "-1, Microsoft.Office.Server.Directory.DirectoryObjectUnauthorizedAccessException",
    "message": "Attempted to perform an unauthorized operation.",
    "innerError": {
      "request-id": "056cd380-a746-4cd8-a795-54bd33d417e9",
      "date": "2019-09-02T11:52:53"
    }
  }
}
```

Seems like a pretty weird error to me as i should be allowed to update the properties with user.ReadWrite.all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abhijeet610** [comment]
I saw similar issue for aboutMe property? Although I am able to perform PATCH but how can one see the same details when try to Get? It looks weird that you can update the properties but cannot see that.

**Comment by tslamparter** [comment]
I get the same error. I'm trying to sync HR data to Azure and can not update hireDate or birthday through api. I can do it in Graph Explorer, but that isn't very practical for constant updates.

**Comment by sawpresto** [comment]
If anyone is still running into this issue, I believe that adding a permission for Sites.ReadWrite.All specifically for hireDate and birthday worked for me. https://stackoverflow.com/questions/61100973/how-to-update-users-hiredate-attribute-in-azure-ad-using-graph-rest-api

**Comment by krbain** [comment]
The PATCH should work as long as you're doing it on a single user and not in app only context. See note in https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#request-body 

The GET is only available on a single user, see [https://github.com/microsoftgraph/microsoft-graph-docs/issues/3878](3878)
