### ISSUE TITLE
Permission requirements incorrect

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#5598]
I know this is still beta, but can you please update the document to match the required permissions. Having just Reports.Read.All is NOT sufficient:

{
    "error": {
        "code": "Authentication_ApplicationHasNoReadAuditLogDataAccess",
        "message": "Application missing MSGraph API 'Read all audit log data' permission",
        "innerError": {
            "request-id": "f27dc6bd-de53-4362-b5c6-54b7a1a6c745",
            "date": "2019-09-02T14:50:18"
        }
    }
}

After adding the AuditLog.Read.All permission you should be fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786282cc-2e01-7a67-bff8-7fdfc069d8f3
* Version Independent ID: 56775e93-d8b0-9fda-88ce-b6dd762a11c5
* Content: [List credentialUserRegistrationDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@michevnew - This is actually a bug that the engineering team is aware of (using AuditLogs.Read.All instead of Reports.Read.All), and is currently fixing the issue. Because this is intended to be fixed soon, the article won't be changed. Please temporarily use AuditLog.Read.All.

**Comment by RaghuramP** [comment]
How long does it take to fix permission issue, its already 6 months..
