### ISSUE TITLE
Create Event documentation has malformed example URLs

### ISSUE THREAD

**Issue by iambmelt** [microsoftgraph/microsoft-graph-docs#56]
See screencap below - note the stray pipe (`|`) and `>` characters

<img width="943" alt="screen shot 2015-12-01 at 6 59 50 pm" src="https://cloud.githubusercontent.com/assets/990063/11521094/0734fcf8-985e-11e5-82ac-a2b65bf368f9.png">

**Comment by martellaj** [comment]
I don't see what you're seeing. the `|

**Comment by iambmelt** [comment]
@martellaj Ooooh! I was thrown off by this syntax; adding additional lines to the example may be more clear.

```
POST /users/<user_id>/events/<event_id>/instances
POST /users/<userPrincipalName>/events/<event_id>
```

**Comment by iambmelt** [comment]
@martellaj - if we're happy with this and the auto-generated docs are formatted as expected feel free to close this issue.

Thanks! :+1:

**Comment by martellaj** [comment]
That's good feedback, @iambmelt.

@sumurthy, @yinaa - do you think we should add the extra lines to make the paths a little clearer? Hard for me comment since I'm so used it by now.

**Comment by sethgr** [comment]
As long as adding lines doesn't bloat the topic too much**, I think that this is a good change to make in the name of making it easier for users to understand.

**If there are topics that have a great deal of paths, then adding new lines could get a bit out of control.

**Comment by keyur32** [comment]
Closing this for now, we did switch to a mono-space font on the snippets which will help readibility.
