### ISSUE TITLE
Accept/Decline events failed

### ISSUE THREAD

**Issue by davogoga** [microsoftgraph/microsoft-graph-docs#560]
Hello there,
Could anyone help me with this...?
I have a problem when an user sends a request of accept/ decline an event.

Despite having all the data needed (bearer token) I always got the status 404 Not Found.

This is the request done in Postman
![request1](https://cloud.githubusercontent.com/assets/19927192/19325025/80e4b18a-9081-11e6-99e8-4f1cc0995433.png)

The weirdest thing is if I have a bearer token for the meeting organizer not an attendee like the last one, I got this:

![request2](https://cloud.githubusercontent.com/assets/19927192/19325117/e293068e-9081-11e6-8e8b-1cda6658a1b0.png)

What's happening with this?

Thanks in advance...!

**Comment by marych** [comment]
@davogoga - could you please provide request-id and timestamp for such a 404 response?
It's expected that meeting organizer can't accept or reject their own meeting.

**Comment by shreedevi** [comment]
@davogoga If this is still an issue, could you provide the headers for the request?

**Comment by davogoga** [comment]
Hello guys! Thanks for you help but I've resolved this a long time ago.
