### ISSUE TITLE
DELETE /subscriptions/{Id} not removing subscription

### ISSUE THREAD

**Issue by michalkadziolka** [microsoftgraph/microsoft-graph-docs#5603]
Issue:
When I'm trying to delete Subscription using 

```http
DELETE https://graph.microsoft.com/v1.0/subscriptions/{id}
```
I'm receiving Status 204, but querying for all subscriptions with 
```http
GET https://graph.microsoft.com/v1.0/subscriptions/
```
 returns that deleted item as well.
Further attempt to GET or DELETE that subscription by {id} returns Status 404

**Comment by markb-trustifi** [comment]
I have the same issue. GET all subscriptions retrieves about of the old 50 non existing subscriptions.

**Comment by jthake-msft** [comment]
@piotrci  is this a known issue?

**Comment by teo-mateo** [comment]
@jthake-msft @piotrci Thank you for picking this up.

**Comment by imihalcea** [comment]
Big issue for me as well. Any news?

**Comment by venkateshchepuru** [comment]
I confirm the deleted subscription is no more active. 

I see a bug/regression in the code giving soft deleted subscriptions as part of list subscriptions.

We will fix this and rollout the fixed version in couple of weeks to all cloud regions. I will update the exact ETA in 2 days.

**Comment by piotrci** [comment]
We have deployed the fix to this problem to the production environment. We apologize for any inconvenience caused by this, and thank you for bringing this to our attention.
