### ISSUE TITLE
How to find the source of a particular group?

### ISSUE THREAD

**Issue by mahesh014** [microsoftgraph/microsoft-graph-docs#5604]
For Ex: We can create a group from Office 365,outlook or Teams etc., and  this api will return all the groups. But there is no information that from where is the group created (or) source of the group?

Or In other words , I need a information that specific group is used by which are the applications like Outlook,teams etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by joshmalik** [comment]
Office365 groups will show up as Unified under groupTypes:, this I imagine will be the case for Teams as they're based on Office365 Groups. 

 "groupTypes": [
                "Unified"
            ],

**Comment by yyuank** [comment]
Group creation source is now available on MS graph beta. Please go to beta documentation and you will find createdByAppId attribute on group. Groups created after the attribute is introduced will have the application ID recorded in the createdByAppId field. Hope this resolves this issue.
