### ISSUE TITLE
Are there any restrictions with the attributes that will be sent?

### ISSUE THREAD

**Issue by aleazofeifam** [microsoftgraph/microsoft-graph-docs#5611]
From the Graph Explorer when I do a "[GET] https://graph.microsoft.com/beta/users/XYZ" I will see the list of attributes of that user that I am querying. However when I try to do the invitation and do something like this:
[POST] https://graph.microsoft.com/beta/invitations
{
  "invitedUserEmailAddress": "vopasociw@doc-mail.net",
  "inviteRedirectUrl": "https://bing.com",
  "jobTitle": "Sample",
  "surname": "My Azure Surname",
  "usageLocation": "US",
  "onPremisesExtensionAttributes": {
    "extensionAttribute1": "Test"
  }
}

I will not map the value of those attributes when the user make the redemption of the invite, is there a list of supported attributes that will be synced/provisioned during the invitation? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51b2654-e447-d495-2788-d6d5b13402b4
* Version Independent ID: 32183c44-363a-a028-a3d9-390b99bffc8b
* Content: [Create invitation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/invitation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/invitation-post.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
From engineering:

Invitation payload can only take those values mentions in this page https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0 
User object properties mapping is not there during invite. Only display name is copies over while redeeming.
If customer wants other properties  to be sync’d they could build an application and redirect the user after redemption to do so.

No change required for this article. Closing the issue.
