### ISSUE TITLE
/me/sendMail not working unless 'saveToSentItems' set to 'false'

### ISSUE THREAD

**Issue by isaacdchan** [microsoftgraph/microsoft-graph-docs#5615]
Just experiencing this problem today. I am receiving a successful 202 response after posting both request bodies, but the recipient only receives the email in inbox if 'saveToSentItems' set to 'false'.

Tested with different toRecipients and contentTypes. Same results.

WORKS
```
{
	'message': {
		'subject': 'Test Subject',
		'body': {
			'contentType': 'text',
			'content': 'Test body'
		},
		'toRecipients': [
			{'emailAddress': {'address': 'isaac.d.chan@gmail.com'}}
		]
	},
	'saveToSentItems': 'false'
}
```
DOESN'T WORK
```
{
	'message': {
		'subject': 'Test Subject',
		'body': {
			'contentType': 'text',
			'content': 'Test body'
		},
		'toRecipients': [
			{'emailAddress': {'address': 'isaac.d.chan@gmail.com'}}
		]
	},
	'saveToSentItems': 'true'
}
```

**Comment by jthake-msft** [comment]
I cannot reproduce this issue. Both setting to false or true the email is received. Is this something gmail is doing? Have you tested this sending to a test user in the developer subscription you get with the Developer Program?  https://developer.microsoft.com/en-us/office/dev-program

**Comment by isaacdchan** [comment]
Due to no action of my own, the issue has been resolved. Now sends when saveToSentItems is 'true' or 'false'.

Will reopen if it reappears
