### ISSUE TITLE
Bug in Microsoft Graph API: Endpoint "sendmail" doesn't work with the subject "Einsatzplan"

### ISSUE THREAD

**Issue by MarvinFret** [microsoftgraph/microsoft-graph-docs#5623]
Issue: Using the /sendmail endpoint doesn't work with the subject "Einsatzplan"

Article: I want to send mails with my Angular SPA. I found this template and it works fine:
```const options = {authProvider,};
const client = Client.init(options);
const sendMail = {
  message: {
    subject: "Meet for lunch?",
    body: {
      contentType: "Text",
      content: "The new cafeteria is open."
    },
    toRecipients: [
      {
        emailAddress: {
          address: "myname@mycompany.com"
        }
      }
    ],
    ccRecipients: [
      {
        emailAddress: {
          address: "cc@mycompany.com"
        }
      }
    ]
  },
  saveToSentItems: "false"
};
let res = await client.api('/me/sendMail')
    .post(sendMail);```

However, it stops working once I change the subject to "Einsatzplan". Subjects like "SubjectTitleTooLong" or "Ein Satz Plan" work fine tho.

**Comment by jthake-msft** [comment]
@MarvinFret  can you reproduce this error in Graph Explroer? What is the status code it returns?

**Comment by jthake-msft** [comment]
I cannot repro this in there. I believe there is another issue.

**Comment by MarvinFret** [comment]
> @MarvinFret can you reproduce this error in Graph Explroer? What is the status code it returns?

I can reproduce it in the Graph Explorer and I get no error but still no mail as well. The status code is 202 - just like before.

Request URL: https://graph.microsoft.com/v1.0/me/sendMail
Method: POST

Request Header: Content-type application/json

Request Body:
'''
{
  "message": {
    "subject": "Einsatzplan",
    "body": {
      "contentType": "Text",
      "content": "The new cafeteria is open."
    },
    "toRecipients": [
      {
        "emailAddress": {
          "address": "yourmail@yourcompany.com"
        }
      }
    ],
    "ccRecipients": [
      {
        "emailAddress": {
          "address": "anyone@yourcompany.com"
        }
      }
    ]
  },
  "saveToSentItems": "false"
}
'''

Please try it yourself. Any other subject works fine but "Einsatzplan" doesn't.

**Comment by svpsiva** [comment]
I couldn't repro this issue as well. 
@MarvinFret I'd suggest that you check the spam filters, mail rules of your target email address.

**Comment by MarvinFret** [comment]
@svpsiva no filters applied

What was the status code you received?
Please send me the endpoint, method, header and body of the request that you used in the explorer. Otherwise I'll assume that you send a faulty request.

**Comment by MarvinFret** [comment]
@jthake-msft can you reproduce the error with the informations i added?
