### ISSUE TITLE
Image rendered from html contains excess whitespace

### ISSUE THREAD

**Issue by stpeteparadox** [microsoftgraph/microsoft-graph-docs#5624]
This is in relation to the 'Add an image rendered from HTML' feature (https://docs.microsoft.com/en-us/graph/onenote-images-files?view=graph-rest-2.0#add-an-image-rendered-from-html)

This is a really cool feature, but currently the resulting image size is far in excess of the actual HTML content. In my case I have a complex table that gets rendered perfectly, but the image itself has added whitespace to the right and especially bottom of the rendered HTML content. It as if it is being rendered to an 8x11 or A4 sheet of paper.

Is there any way to get the image rendering to fit to the actual HTML content?

Thank you very much

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e71dd9c-098b-e832-46f6-2724124302e0
* Version Independent ID: 59ed1107-9cf6-69d4-711d-aa6d5b27c527
* Content: [Add images, videos, and files to OneNote pages - Microsoft Graph](https://docs.microsoft.com/en-us/graph/onenote-images-files?view=graph-rest-2.0#feedback)
* Content Source: [concepts/onenote-images-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-images-files.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @stpeteparadox  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-notes.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
