### ISSUE TITLE
Undocumented reactionType "acks"

### ISSUE THREAD

**Issue by dgancho** [microsoftgraph/microsoft-graph-docs#5638]
Received reactionType value "acks" in a chatMessage object, which is not listed as a supported value.
```
  "reactions": [
    {
      "reactionType": "acks",
      "createdDateTime": "2019-09-08T00:40:58.465Z",
      "user": {
        "application": null,
        "device": null,
        "conversation": null,
        "user": {
          "id": "REMOVED",
          "displayName": null,
          "userIdentityType": "aadUser"
        }
      }
    }
  ]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 993102b7-1d1f-892a-2d21-334027927c20
* Version Independent ID: 2a2fe4c8-a580-a648-ff29-e71685052431
* Content: [chatMessageReaction resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessagereaction?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessagereaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessagereaction.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Can you check if this repros now? There was some additional info which was being sent out without processing. This should be fixed now. Please reopen if not fixed.
