### ISSUE TITLE
msgraph-sdk-java vs msgraph-sdk-android 

### ISSUE THREAD

**Issue by Samhithgb** [microsoftgraph/microsoft-graph-docs#5641]
What SDK is suggested to be used for Android development? There are two sdks currently available and no proper documentation what to use and when. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e4ed6e9-9444-39d0-2a45-920ca4eecd6c
* Version Independent ID: 6e4d2087-45ae-806c-5be6-25c880c8bc12
* Content: [Install the Microsoft Graph SDK - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/sdk-installation#feedback)
* Content Source: [concepts/sdks/sdk-installation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/sdk-installation.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
Sorry for the confusion.  The Android SDK is deprecated.  You should use the Java SDK.  The docs will be updated shortly.

**Comment by Samhithgb** [comment]
The official documentation still points to the Android SDK!  https://developer.microsoft.com/en-us/graph/get-started/android.

**Comment by Ranjeet4android** [comment]
How to send these parameters during event creation in Android SDK.

 event.allowNewTimeProposals = true;
        event.isOnlineMeeting = true;
        event.onlineMeetingProvider = "teamsForBusiness";

**Comment by jasonjoh** [comment]
@Ranjeet4android The Android SDK is deprecated, Android development should use the Java SDK.

@Samhithgb I've requested that the page owner for the link you sent update their SDK link.

**Comment by Ranjeet4android** [comment]
Means you are telling that i can't use online meeting request direct from
Android sdk.
For this we should use graph api or java methods.

**Comment by jasonjoh** [comment]
https://developer.microsoft.com/en-us/graph/get-started/android page is updated.
