### ISSUE TITLE
Ability to filter users with onPremisesSamAccountName with Microsoft Graph API

### ISSUE THREAD

**Issue by karthickshanmugam0689** [microsoftgraph/microsoft-graph-docs#5648]
I would like to have a filter on the users api of Microsoft Graph API, where I will be able to filter the users based on onPremisesSamAccountName, which is currently not available with Graph API.

We have the internal employee id to be stored with onPremisesSamAccountName variable which is present in users API of Microsoft Graph. We are trying to filter with onPremisesSamAccountName property to filter based on the internal employee id. Currently we are not able to do that with Graph API but we really need this to be workling or would be happy if we get know any possible workarounds if available

https://graph.microsoft.com/v1.0/users?$filter=onPremisesSamAccountName eq '[some-id]'&$select= userPrincipalName,displayName,department,jobTitle,companyName,onPremisesSamAccountName,....[more list of fields for select]
The expected outcome is to show the required result but the response what we got is as follows

{
"error": {
"code": "Request_UnsupportedQuery",
"message": "Unsupported or invalid query filter clause specified for property 'onPremisesSamAccountName' of resource 'User'.",
"innerError": {
"request-id": "[request-id from request]",
"date": "[date on which request is made]"
}
}
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#feedback)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
This capability is not supported today. Please open a suggestion using User Voice here - this will allow us to track your request and learn if other customers have a similar need:
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359566

**Comment by karthickshanmugam0689** [comment]
Hi @piotrci There is already an idea as per the below link which is posted on October 2018. Can this feature somehow implemented as early as possible
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/35835481-allow-add-onpremisessamaccountname-as-a-filter
