### ISSUE TITLE
Breaking URL change in hosted images (or is it hosted contents?)

### ISSUE THREAD

**Issue by hafarey** [microsoftgraph/microsoft-graph-docs#5652]
It appears that there was a change in which the URL of a hosted image has become invalid.  In chat messages, the img src now begins with `https://graph.microsoft.com/v1.0`, which results in a 400 response.  However, replacing the URL with `https://graph.microsoft.com/beta` works.

On a related note, the API docs specify the endpoints for "hosted images," such as "list hosted images," which end with `/hostedImages`.  But I've been seeing `/hostedContents`.  Is this in flux, or are these two different resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f046b37e-8569-b617-4c9b-402342d4bef9
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessage.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
/hostedImages is the correct endpoint to use, and the functionality should be in beta only.
