### ISSUE TITLE
Cannot segregate access by user mailboxes using EWS

### ISSUE THREAD

**Issue by mishakogan** [microsoftgraph/microsoft-graph-docs#5659]
According to this article (https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access) , there is now a way to segregate access per user for Exchange Online Mailboxes.

We have a background process (runs as a daemon without a signed-in user) that retrieves data from MS Teams in Office 365.

This process uses Client Credential Grant Flow to authenticate and then uses EWS API to retrieve the data. 

We wanted to test to see how we can restrict the app to only have access to certain mailboxes and NOT all. Unfortunately, we found out that `full_access_as_app` permission is needed in order for the app to connect via EWS

![image](https://user-images.githubusercontent.com/8002498/64625241-74936680-d3b1-11e9-8601-8f1d6ffb9d0e.png)

When using this credential method and also scoping down user access to a certain set of users, it seems like scoping down (using https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access instructions) does not take affect (probably because `full_access_as_app` permission is a god-like permission).

When `full_access_as_app` permission is removed (`Mail.Read` permission is enabled), we get the following error from EWS:
**REQUEST:**

```
2019-09-06 17:58:29,030 [PT10] TRACE ExchangeTrace - [EwsRequest]
		<Trace Tag="EwsRequest" Tid="26" Time="2019-09-06 13:58:29Z" Version="3.0.0.0">

		  <?xml version="1.0" encoding="utf-8"?>

		  <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">

		    <soap:Header>

		      <t:RequestServerVersion Version="Exchange2016" />

		      <t:DateTimePrecision>Milliseconds</t:DateTimePrecision>

		      <t:ExchangeImpersonation>

		        <t:ConnectingSID>

		          <t:SmtpAddress>XXXX@XXXX.com</t:SmtpAddress>

		        </t:ConnectingSID>

		      </t:ExchangeImpersonation>

		    </soap:Header>

		    <soap:Body>

		      <m:GetFolder>

		        <m:FolderShape>

		          <t:BaseShape>AllProperties</t:BaseShape>

		        </m:FolderShape>

		        <m:FolderIds>

		          <t:DistinguishedFolderId Id="conversationhistory">

		            <t:Mailbox>

		              <t:EmailAddress>XXX@XXX.com</t:EmailAddress>

		            </t:Mailbox>

		          </t:DistinguishedFolderId>

		        </m:FolderIds>

		      </m:GetFolder>

		    </soap:Body>

		  </soap:Envelope>

		</Trace>
```

**RESPONSE:**

2019-09-06 17:58:29,028 [PT5] TRACE ExchangeTrace - [EwsResponseHttpHeaders]
<Trace Tag="EwsResponseHttpHeaders" Tid="26" Time="2019-09-06 13:58:29Z">

```
HTTP/1.1 **401 Unauthorized**
request-id: e5510dd0-be16-461f-8e98-b725425beecc
X-CalculatedFETarget: CY4PR18CU002.internal.outlook.com
X-BackEndHttpStatus: 401,401
X-FEProxyInfo: CY4PR18CA0046.NAMPRD18.PROD.OUTLOOK.COM
X-CalculatedBETarget: CY4PR22MB0439.namprd22.prod.outlook.com
X-RUM-Validated: 1
X-MailboxGuid: XXXXX
x-ms-diagnostics: 2000008;reason="**The token contains no permissions, or permissions can not be understood.**";error_category="**invalid_grant**"
X-BeSku: Gen9
X-DiagInfo: CY4PR22MB0439
X-BEServer: CY4PR22MB0439
X-Proxy-BackendServerStatus: 401
X-FEServer: CY4PR18CA0046,HE1P190CA0037
Content-Length: 0
Date: Fri, 06 Sep 2019 13:58:28 GMT
Set-Cookie: exchangecookie=XXXX expires=Sun, 06-Sep-2020 13:58:28 GMT; path=/; secure; HttpOnly
Server: Microsoft-IIS/10.0
WWW-Authenticate: Bearer client_id="XXXXX", trusted_issuers="XXXX@*", token_types="app_asserted_user_v1 service_asserted_app_v1", authorization_uri="https://login.windows.net/common/oauth2/authorize", error="invalid_token",Basic Realm=""X-Powered-By: ASP.NET
```

1) Is this expected? Or is this a bug?
2) https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc auth protocol, can technically be used here and then the user can be added as an impersonator in EWS, however it seems that MS does not recommend to use this flow anyway:

![image](https://user-images.githubusercontent.com/8002498/64625708-42363900-d3b2-11e9-958c-af399c4c6101.png)

**What would you recommend for us to do in this case?** Our clients are asking us to give them control in Office 365 to decide which users (mailboxes) our app should have access to? I saw that there is conditional access feature (https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/overview) but it does not seem to work for daemon apps (application runs as a background service without a signed-in user)  like ours - this is being verified in here: https://github.com/MicrosoftDocs/azure-docs/issues/38584

This question has been repeatedly asked by our customers and we don't have a good answer at this point. Can you help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca1eed2-d0ca-11de-4f25-f09865605a0f
* Version Independent ID: 9fd423e0-86e4-b7e4-9249-1bacb51e81ad
* Content: [Scoping application permissions to specific Exchange Online mailboxes - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access)
* Content Source: [concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-limit-mailbox-access.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mishakogan** [comment]
@svpsiva - Hi any updates?

**Comment by jasonjoh** [comment]
@mishakogan the article you linked lists the supported permissions for scoping, and yes, EWS permissions are not included here. EWS is a completely different API than Graph.

Is there a reason you cannot use Graph (besides of course having to rewrite)? That would get you what you want. 

If you need to stay with EWS, I haven't tested this scenario (been years since I've used EWS :)). However, the usual method of accomplishing this before OAuth was to have the app run as a dedicated service account. The admins would configure the account with impersonation rights just to the accounts they want (see https://docs.microsoft.com/exchange/client-developer/exchange-web-services/how-to-configure-impersonation). I suspect this would still work with OAuth, but as I said, I haven't tried it.

If you didn't want to use the ROPC flow for authenticating as a service account, you could use the Auth Code Flow to do an interactive login, get a token and refresh token, then save those in a secure cache or db somewhere so your app can silently get tokens for the service account. You'd need to handle scenarios where the refresh token gets invalidated (password changes, etc) and have the admin re-authenticate, but other than that it should work.

**Comment by mishakogan** [comment]
@jasonjoh - thank you for your answers. Let me pull the list of Graph limitations that we encountered that forced us to use EWS. 

I am aware of Impersonation method / scopes and can confirm that this method works to segregate access, however it is limited to Exchange Online and forces the use of Service Account and Basic Auth. In theory this should work with OAuth as well but have not tried.

**Comment by chopraniitn** [comment]
@mishakogan , i am on the same boat and exactly same implementation as yours  and our client also not liking the fact that we can not limit it. Do post anything if you come across.

Seems like Microsoft would not want to implement as they are pushing more for graph API.

**Comment by mishakogan** [comment]
@chopraniitn - great! As I am preparing the details on limitation of graph API for our use case, can you post graph limitations that you have experienced? This will help put urgency in this ask

**Comment by svpsiva** [comment]
Hi

Thanks for sharing this feedback. We do not support ApplicationAccessPolicy based access control for EWS API's. These policies can only be used for access control when using Microsoft Graph or Outlook REST API's. 

While we understand your need to have this capability in EWS, we have last year announced that EWS is in maintenance mode and will not be receiving any new features. 

We would be very happy to engage with you and understand the blockers that prevent you from moving to Microsoft Graph. 

Thanks
Sivaprakash
Senior PM, Microsoft

**Comment by santiago-obando** [comment]
Hello guys, We're 
 dealing with the same issue as #mishakogan.
We need to give a user / service account privilegies to manage all users mailboxes. Our app is a service app / daemon app with no user interaction (background proccess).
We understand that EWS is being deprecated, could you share with us a way to acomplish this using MS Graph?.

Thank you in advance.

**Comment by svpsiva** [comment]
https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access has the details you need.

**Comment by robertmuehsig** [comment]
Maybe this might help: https://stackoverflow.com/questions/57009837/how-to-get-oauth2-access-token-for-ews-managed-api-in-service-daemon-application/63175301#63175301

**Comment by tjmoore** [comment]
Just to chip in with examples of blockers on moving to Graph API, and I know these may not be the same reasons for others:

1. Graph API does not support on-premises. We need both on-prem and 365 support. It is a lot of work and complexity supporting two APIs for both on-prem and 365, especially as EWS itself is very complicated.

2. Graph API doesn't appear to support streaming notifications, only web hooks. Web hooks are impractical for us due to having a server side application customers install and often cannot or refuse to open access to the outside world, so publishing webhook addresses isn't possible.

**Comment by srudin** [comment]
To us the restriction with Graph is that we cannot access distribution lists.

**Comment by srudin** [comment]
So as Graph is not allowing us to read out distribution lists (even the beta api does not support it) we have to use EWS for this. Giving full_access_as_app only for this is a significant risk that will not pass security audits.

The link posted by @svpsiva has been mentioned by OP at the very beginning already stating that it doesn't work for EWS.

The ROPC approach for using delegated access (impersonation) as linked by @robertmuehsig would work - but is not possible due to enforced two-factor-authentication. Is there a way around this? I think all our company accounts are required to use it so I cannot think of a workaround.

The approach described by @jasonjoh (interactive login + caching / refreshing access token) seems feasible but pretty complicated and rather unreliable.

So running out of ideas... Any other suggestions?

**Comment by srudin** [comment]
I got a user with disabled 2FA and tried the solution linked by @robertmuehsig. I did exactly as stated there but unfortunately I always get an "Unauthorized" exception when doing the ews calls (OAuth calls succeed). Is this broken?

Also I can see that during the last few days the Exchange legacy API has disappeared from the selection on Azure when adding an API permission! It can still be added using Azure CLI commands but what is MS thinking here?

So I guess I need to tell our customer that Microsoft is not allowing us to do what he wants. Maybe moving to Google is an option? Let's see...

**Comment by srudin** [comment]
Ok, so according to https://developer.microsoft.com/en-us/graph/blogs/upcoming-changes-to-exchange-web-services-ews-api-for-office-365/ this is no longer working. So how can I read out distribution lists from a specific mailbox without giving full access and without an interactive login?

**Comment by robertmuehsig** [comment]
It seems that the "Exchange legacy API" is gone from the UI, but (at least with my setup) the app still works. This is the API permission from my app:

![image](https://user-images.githubusercontent.com/756703/99366914-888dfe80-28b9-11eb-9be0-f2372c62c2c9.png)

**Comment by glennblock** [comment]
@srudin @robertmuehsig Hi, I lead the EXO PM team. EWS is not going away, though as mentioned we are no longer investing in adding features. 

The recent change that we made in the portal removed the "Exchange Legacy Option" as part of our [Deprecation](https://developer.microsoft.com/en-us/office/blogs/outlook-rest-api-v2-0-deprecation-notice/) of our Outlook Rest API V2.

There is a work-around for creation of EWS apps via the manifest that is supported. We are planning to post documentation on how to do this within the next few days.

**Comment by tjmoore** [comment]
Removing the Exchange permission from the UI creates a lot of support issues for the project I work on and needs documentation updates as customers will now be calling asking where this option is.

**Comment by chopraniitn** [comment]
Agree with tjmoore, it takes time to train support on those things and now support was almost familiar with this and we have to do repeat the process. will definitely annoy our customers too.

**Comment by tjmoore** [comment]
Additionally, this makes this guide out of date and impossible to follow the steps to register an application - https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth

**Comment by jasonjoh** [comment]
The guide is being updated. See https://github.com/MicrosoftDocs/office-developer-exchange-docs/pull/110

**Comment by glennblock** [comment]
Thank you @tjmoore and @chopraniitn, we understand the concern and know that this will cause some pain. @jasonjoh has updated the documentation. Is there anything else we can do to help smooth the transition?

**Comment by tjmoore** [comment]
Are `resourceAppId` and `resourceAccess.Id` fixed values as in we just copy&paste the JSON manifest in the guide or do the IDs need modifying per app registration?

Back to **full_access_as_app** permission though. We've had potential customers kick back on this saying this will be rejected in their IT policies as it's too wide an access. This still pushes us towards Graph, but as above there are blockers for Graph.

Is there any future intention to require OAuth with on-premises Exchange EWS in future versions or updates to Exchange Server, or could customers configure an environment that requires OAuth on-prem? Where OAuth would require the same configuration as with 365 and the **full_access_as_app** permission for EWS?

**Comment by tjmoore** [comment]
> So as Graph is not allowing us to read out distribution lists (even the beta api does not support it) we have to use EWS for this. 

I've not investigated this far, but we use room distribution lists to get list of room mailboxes. Are these also not available via Graph API, and is there another solution?

**Comment by robertmuehsig** [comment]
Just to add some notes why we are still using EWS
 We are using the EWS way because MS Graph is not really a great option currently. In theory we just want to mimic the "Outlook GAL search", but with the Graph API we would need to combine the "users" and "contacts" endpoint (which is doable), but the [msexchhidefromaddresslist](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/41049382-orgcontacts-should-support-msexchhidefromaddressl) property is missing.

 @glennblock

**Comment by alokste** [comment]
Hi @mishakogan  , 

Maybe the -EWSApplicationAccessPolicy  can be useful in this situation . I am facing the same technical challenge from Security team and I am going to explore this solution with our Exchange admin.

https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-control-access-to-ews-in-exchange

Regards,
Alok

**Comment by tjmoore** [comment]
@alokste I think that just restricts who can use EWS. That may be okay for some, but it still leaves the client application with wide open access to all mailboxes and that can get rejected by some IT security.

Generally, if we can address the issues with Graph vs EWS, and if Graph API could be rolled out to on-prem Exchange, then we can remove EWS entirely, but it seems that's a long way off, or maybe never with seemingly little investment in on-prem Exchange. I know the desire is to get everyone in the cloud, but this is impossible for many organisations.

**Comment by rum80** [comment]
Hello guys,
we're facing the same need: we have a background daemon service application that need to access a single O365 mailbox. It had been developed using EWS to support both Exchange on-prem (Basic Auth only) and online (both Basic Auth and OAuth2). It is working fine, but to let it work in OAuth2 we currently need to **full_access_as_app** privilege, which is a nonsense (and customers do refuse) as it means the application should store a secret which allow to access all organization mailbox.

So, we really need to figure out whether, and how, it's possible to restrict EWS application access to a selected mailbox.

We've tried the technique described in https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-control-access-to-ews-in-exchange - but it's not working, nor on Exchange on prem, neither online.

Has anyone else tried such procedure? Any hint?

**Comment by rum80** [comment]
Hello guys,
we're facing the same need - figuring out how to restrict access for an EWS application to a selected mailbox, as the application has been granted **full_access_as_app** administrative privilege (which is a nonsense as makes the app less secure then using Basic Auth).

We've tried the technique described in https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-control-access-to-ews-in-exchange on Office365, but it seems working only if the client application connects through EWS Basic Authentication. 

I mean: once applied such configuration, if the app connect through OAuth2, it is still able to access any mailbox. On the other hand, if the app connects through EWS Basic Auth, it's no more able to access mailbox (403).

Has anyone else tried such procedure with success with OAuth2? Any hint?

**Comment by tjmoore** [comment]
Update from Microsoft - Until further notice, basic auth won't be turned off, **EXCEPT for protocols not being used by the tenant**

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-february-2021-update/ba-p/2111904

For now this gives an option to still use EWS and basic auth, so long as it has already been used so MS don't turn it off. Not sure if MS turning it off for a protocol or service means it can't be turned back on though.

For organisations that want to disable basic auth generally, there is an option to enable it only for EWS

https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/disable-basic-authentication-in-exchange-online

See **AllowBasicAuthWebServices** policy

**Comment by tjmoore** [comment]
Further update, perhaps this has been solved after all -

[Application Access Policy Support Added to Exchange Web Services in Exchange Online](https://developer.microsoft.com/en-us/office/blogs/application-access-policy-support-added-to-exchange-web-services/)

@alokste - I may have missed what you were suggesting. The link was to an old document, but this recent update may be what you're referring to.

**Comment by tjmoore** [comment]
@jasonjoh Can we get a further update to the [guide document](https://github.com/MicrosoftDocs/office-developer-exchange-docs/blob/master/docs/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth.md) as that is still limited to **full_access_as_app**? I'm trying to work out how to advise customers to configure granular permissions with Application Access Policy. Ideally in our case we need to scope access to Room Mailbox calendars with read/write access, but I'm not sure how to do that yet. With basic auth we used an impersonation role scoped to "RoomMailbox" when using impersonation in EWS.

**Comment by tjmoore** [comment]
Further answering my earlier question, I've worked out I need **full_access_as_app** to get EWS access at all, epsecially to do non-mailbox specific calls to fetch room lists, resolve mailbox info.

Then I can restrict access to specific mailboxes, which I've done by creating a security type distribution group to assign rooms to, and applying Application Access Policy to that group. That works and I can't get access to anything outside of the group.

e.g.

`New-DistributionGroup -Name MyRooms -Type Security`

`Add-DistributionGroupMember -Identity MyRooms -Member room1`
`Add-DistributionGroupMember -Identity MyRooms -Member room2`
etc

`New-ApplicationAccessPolicy -AccessRight RestrictAccess -AppId "[APP_ID]" -PolicyScopeGroupId "MyRooms" -Description "Restrict access to My Rooms"`

The last part of the puzzle is some customers would like read-only access and restrict to calendars (as the app I'm working on is only interested in room mailbox calendars).

I've tried `Calendar.Read` permission but it seems that does nothing with EWS.

p.s. It's a huge pain waiting an hour for permissions to apply to test it in the application!

**Comment by jasonjoh** [comment]
I'm opening a new issue for this in the EWS doc repository and closing this issue (since it has little to do with Graph documentation). Please add any further feedback to https://github.com/MicrosoftDocs/office-developer-exchange-docs/issues/125
