### ISSUE TITLE
Unified Group details

### ISSUE THREAD

**Issue by AveAdam** [microsoftgraph/microsoft-graph-docs#566]
autoSubscribeNewMembers
allowExternalSenders
isSubscribedByMail
Cannot get these three properties for unified group.

**Comment by marych** [comment]
They're not returned by default, please use: https://graph.microsoft.com/v1.0/groups/id?$select=autoSubscribeNewMembers,allowExternalSenders,isSubscribedByMail

**Comment by AveAdam** [comment]
No work for app-only token.

I added my solution at here:
https://github.com/microsoftgraph/microsoft-graph-docs/issues/631 

Thanks!
