### ISSUE TITLE
What could I use for resource and changeType when creating webhook for Teams

### ISSUE THREAD

**Issue by phuong-vo** [microsoftgraph/microsoft-graph-docs#5664]
I want to create the subscription that notifies when users in the Teams send messages.
So I created the subscription as described in this document, but what values should I use for resource and changeType properties. Could you please help me with this.
request:
POST https://graph.microsoft.com/beta/subscriptions
{
  "changeType": "???",
  "notificationUrl": "my-valid-url",
  "resource": "???",
  "expirationDateTime": "2019-06-13T09:09:11.253Z",
  "clientState": "my-client-state"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks#feedback)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
This resource is not yet supported. @nkramer , do you have more information?

**Comment by phuong-vo** [comment]
Hello @nkramer, do you have any update for MS Teams's webhook for new incoming message's notifications. Is there long polling notifications for this? Thank you very much for your help!

**Comment by nkramer** [comment]
This is now supported, see https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http
