### ISSUE TITLE
ActivityLimitReached - Adding Microsoft Teams Tab

### ISSUE THREAD

**Issue by v-prabus** [microsoftgraph/microsoft-graph-docs#5665]
Hi,

While adding the Microsoft tab via graph api(https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/tabs) we are getting "Exception: Code: ActivityLimitReached Message: Failed to execute Skype backend request SetThreadPropertyRequest."

we are facing this issue recently and it was working before.

Thanks,

**Comment by Prithvi-MSFT** [comment]
Hi @v-prabus ,
Can you share more details on the number of tabs you added before facing the error. We added a total of 10 tabs in same channel and did not get any issue.

Thanks

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
