### ISSUE TITLE
Calling the Places API throwing an error even though i have the correct permission

### ISSUE THREAD

**Issue by shinta5150** [microsoftgraph/microsoft-graph-docs#5666]
In my service account JWT I have the following roles.

"roles": [
    "Place.Read.All",
    "Calendars.Read",
    "User.Read.All"
  ],

However I'm still getting the following error:

```
{
  "error": {
    "code": "UnknownError",
    "message": "{\"code\":\"invalid_permissions\",\"message\":\"place.read.all permission is required to read company places, scopes/roles provided:  IsAppOnly:True\"}",
    "innerError": {
      "request-id": "6bed6edf-73d6-4764-8138-6768185d7066",
      "date": "2019-09-11T07:28:30"
    }
  }
}
```

**Comment by EliasKaplan** [comment]
Hi
Sorry for the interruption on service, in Places API for  the MS Graph beta endpoint, a fix has been checked in and being deployed in the next couple of days, if your tenant is in First release you'll see it fixed earlier. I'll respond here once the fix is fully deployed.
Thx for using the API
Elias

**Comment by EliasKaplan** [comment]
Hi @shinta5150 
Deployment of the fix is almost completed, test and let use know.
Thx

**Comment by cys22** [comment]
Hi @EliasKaplan, thank you fixed this problem.
I had test the fix, 
https://graph.microsoft.com/beta/places/microsoft.graph.roomlist
but I got a removed DistributionGroup name Include in the list.

**Comment by shinta5150** [comment]
I've been able to pull the places using my application account on my tenant.

**Comment by cys22** [comment]
> Hi @shinta5150
> Deployment of the fix is almost completed, test and let use know.
> Thx

Hi @EliasKaplan, thank you fixed this problem.
I had test the fix,
https://graph.microsoft.com/beta/places/microsoft.graph.roomlist
but I got a removed DistributionGroup name Include in the list.
