### ISSUE TITLE
Use Postman variables in Get New Access Token dialog

### ISSUE THREAD

**Issue by jsuddsjr** [microsoftgraph/microsoft-graph-docs#5667]
Not sure when the functionality was added, but you can now use environment variables in the **Get New Access Token** dialog, which completely contradicts your statement above that "you cannot use the environment variables here..." In fact, Postman itself provides this warning: "Heads up! These parameters hold sensitive data. To keep this data secure while working in a collaborative environment, _we recommend using variables_."

Auth URL: https://login.microsoftonline.com/{{TenantId}}/oauth2/v2.0/authorize
Access Token URL: https://login.microsoftonline.com/{{TenantId}}/oauth2/v2.0/token
Client ID: {{ClientId}}
Client Secret: {{ClientSecret}}
State: {{$randomUUID}}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jsuddsjr** [comment]
Note that {{$randomString}} is not available, so I choose another random 36 character generator already available in Postman.

**Comment by jthake-msft** [comment]
Thanks @jsuddsjr . The only problem is that if I share this collection or you import it. Those settings are not persisted in the import/export files. So it is additional steps to get operational. The team at Postman are aware of this and have it on their backlog. For now we will stick with the environment variable approach until this persists with exports.

**Comment by owaispathan** [comment]
Hi, i need your help with regards to use to using postman api with Azure MFA. since the organization has enabled MFA my application has stopped working. kindly urgent support is needed.

**Comment by martinepic** [comment]
> Hi, i need your help with regards to use to using postman api with Azure MFA. since the organization has enabled MFA my application has stopped working. kindly urgent support is needed.

Has a solution?
