### ISSUE TITLE
Reading and updating a user's profile photo is only possible if the user has a mailbox

### ISSUE THREAD

**Issue by fume** [microsoftgraph/microsoft-graph-docs#5668]
Please, mention the known restriction as stated here: https://docs.microsoft.com/en-us/graph/known-issues#photo-restrictions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PeterChencha** [comment]
Hello @fume thanks for reaching out. Does the note section of this documentation align with the above restriction or it might need more fleshing out for better clarity -> https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0

**Comment by fume** [comment]
this issue is almost 2 years old...
