### ISSUE TITLE
Discrepancy between MSTeams and GraphApi after member deletion from group

### ISSUE THREAD

**Issue by emanuelefirmani** [microsoftgraph/microsoft-graph-docs#5670]
Issue: I deleted a users from a MSTeams group. When I invoke
https://graph.microsoft.com/beta/groups/ff928b0d-d3b3-4f99-914e-f79ecc16d586/members?$select=displayName
he is still present. MSTeams tells me there are 13 members (3 owners), GraphApi says 17 (4 owners). Sharepoint online returns 17, like GraphApi.

**Comment by jthake-msft** [comment]
Can you be more precise on how you are getting the various values here? Are they showing in the user interface or specific API calls?

**Comment by emanuelefirmani** [comment]
Here is the list taken from the sharepoint online website:
![image](https://user-images.githubusercontent.com/16406477/65217457-64b40a80-dab4-11e9-9004-79bca693fb62.png)

This is the list of users that I see in MSTeams for the same groupt;
![image](https://user-images.githubusercontent.com/16406477/65217539-9b8a2080-dab4-11e9-88a2-ffd5df32e8ad.png)
(Here user pictures are shown, in SPO not)

This is the response of call to https://graph.microsoft.com/beta/groups/e6a598ef-6e27-4de9-a917-e9f95bad9626/members?$select=displayName (using postman)
![image](https://user-images.githubusercontent.com/16406477/65217597-d2f8cd00-dab4-11e9-8109-c8a03e1b5b8f.png)

So, SPO shows 8 members, GraphApi returns the very same 8 users; MSTeams shows only 6.
I'm always using my windows identity which synch'ed with AAD
