### ISSUE TITLE
How about send mail with application authentication ?

### ISSUE THREAD

**Issue by ryantranvn** [microsoftgraph/microsoft-graph-docs#5673]
I get access without a user, after i got access token, i send mail with this api : 
https://graph.microsoft.com/v1.0/users/{my_ip}/sendMail
And receive this error : 
{ "error": { "code": "NoPermissionsInAccessToken", "message": "The token contains no permissions, or permissions can not be understood.", "innerError": { "request-id": "a17cb89a-96b2-47cc-81aa-50eb23e52ce0", "date": "2019-09-11T23:23:10" } } }
I checked and added all permissions about mails with application type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jabbera** [comment]
Same issue. Did you sort this?

**Comment by jasonjoh** [comment]
The error indicates a token problem. Grab your access token and head over to https://jwt.ms/ to decode it. Look for the `roles` claim to see which permissions scope are actually present in the token.

**Comment by chamikasandamal** [comment]
Your application should have the correct [permission](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#permissions)


Permission type | Permissions (from least to most privileged)
-- | --
Delegated (work or school account) | Mail.Send
Delegated (personal Microsoft account) | Mail.Send
Application | Mail.Send

**Comment by oargaruna** [comment]
https://stackoverflow.com/questions/41446437/sendmail-returns-resourcenotfound

**Comment by Rebeckamys** [comment]
I have an application which has all correct permissions mentioned above. But when I try to send an email as "Me" the recipient doesn't get any email (I've tried several recipient email addresses), and I neither get any error messages. Do I need something more to be able to send email as an application more than correct permissions?

**Comment by chamikasandamal** [comment]
You need to have application permission and an admin should grant the permission
Please verify whether both are satisfied

**Comment by nezoic** [comment]
I'm seeing the same problem with applicaton authentication but only when using a shared mailbox.

**Comment by jushi-zf** [comment]
I encountered the similar 'NoPermissionsInAccessToken' issue but finally solved, here's what I found, hope it would help anyone else.

As @chamikasandamal mentioned, you need to have 'Mail.Send' application permission and an admin should grant the permission, however, another important step missed here is to confirm whether this permission is assigned to [Microsoft Graph API v1.0](https://docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0) or to [Outlook Mail REST API v2.0](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/use-outlook-rest-api)

To confirm this, I tried to get the access tokens for both APIs and head over to https://jwt.ms/ to look for the roles claim as @jasonjoh mentioned. 
```sh
# For Microsoft Graph API v1.0
curl -H "Content-Type: application/x-www-form-urlencoded" -d 'client_id=<my_client_id>&client_secret=<my_client_secret>&grant_type=client_credentials&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default' 'https://login.microsoftonline.com/dd5d58b8-0a45-49e0-a249-720e7161d2fa/oauth2/v2.0/token'

# For Outlook Mail REST API v2.0
curl -H "Content-Type: application/x-www-form-urlencoded" -d 'client_id=72c10800-de14-4004-a1fb-f48b61366f1a&client_secret=JzhzX2E6R%402mr%3D9MyQkg%2Fh-0C.Dl5J.x&grant_type=client_credentials&scope=https%3A%2F%2Foutlook.office.com%2F.default' 'https://login.microsoftonline.com/dd5d58b8-0a45-49e0-a249-720e7161d2fa/oauth2/v2.0/token'
```

If the permission is assigned to Microsoft Graph API v1.0, then you need follow [this document](https://docs.microsoft.com/en-us/graph/outlook-send-mail-from-other-user) to send your mail.

For me the permission was actually assigned to Outlook Mail REST API v2.0 and that's why I got the 
'NoPermissionsInAccessToken' error. If you're in the same condition, please go to [this document](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations#SendMessages) for more information, there're two more things need to be noticed:
1. the mail message schema is slightly different with that of Microsoft Graph API v1.0;
2. you need extra 'X-AnchorMailbox' header to specify the sender's mail box, and it must be consistent with object Id specified in URI.

**Comment by jushi-zf** [comment]
I encountered the similar 'NoPermissionsInAccessToken' issue but finally solved. Here's what I found, hope it would be helpful for anyone else.

Just as @chamikasandamal  mentioned, you need to have 'Mail.Send' application permission and an admin should grant the permission, however, another important step missed here is to confirm whether the permission is assigned to [Microsoft Graph REST API v1.0](https://docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0) or assigned to [Outlook REST API v2.0](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/use-outlook-rest-api).

To confirm this, I tried to get the access tokens for both APIs and head over to https://jwt.ms/ to look for the roles claim as @jasonjoh  mentioned, the decoded object of the right token should contains "Mail.Send" in field "role".

```sh
# For Microsoft Graph REST API v1.0
curl -H "Content-Type: application/x-www-form-urlencoded" -d 'scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_id=<my_client_id>&client_secret=<my_client_secret>&grant_type=client_credentials' 'https://login.microsoftonline.com/<my_tenent_id>/oauth2/v2.0/token'

# For Outlook REST API v2.0
curl -H "Content-Type: application/x-www-form-urlencoded" -d 'scope=https%3A%2F%2Foutlook.office.com%2F.default&client_id=<my_client_id>&client_secret=<my_client_secret>&grant_type=client_credentials' 'https://login.microsoftonline.com/<my_tenent_id>/oauth2/v2.0/token'
```

If the permission is assigned to Microsoft Graph REST API v1.0, you should go to [this document](https://docs.microsoft.com/en-us/graph/outlook-send-mail-from-other-user) to consume the token and send the mail.

For me, the pemission was acutally assinged to Outlook REST API v2.0, so I got the 'NoPermissionsInAccessToken' error when I consume the token with Microsoft Graph REST API v1.0. If you are in the same situation, you should go to [this document](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations#create-and-send-messages) instead, and two more things need to be noticed:
1. The mail message schema is different with that of Microsoft Graph REST API v1.0;
2. An extra "X-AnchorMailbox" header is required to specify the sender's mailbox, and it must be consistent with the user specified in API URI.

**Comment by jasonjoh** [comment]
@jushi-zf yes, this is a crucial concept to understand about access tokens, thanks for explaining your findings. The audience (indicated by the `aud` claim in the token) is super important. If the `aud` claim is set to `https://outlook.office.com`, the Graph endpoints cannot use it. Similarly, if the `aud` claim is set to `https://graph.microsoft.com`, the Outlook endpoint cannot use it.

**Comment by salmagomaa** [comment]
What does {my_ip} refers to in https://graph.microsoft.com/v1.0/users/{my_ip}/sendMail ?

**Comment by salmagomaa** [comment]
I found this https://support.office.com/en-us/article/what-is-my-user-id-and-why-do-i-need-it-e456eb4c-9cb9-4aa0-9d0a-923b8c53228d

**Comment by chokribr** [comment]
You can simply use this  function users('xxwcwc@xxx.qds') and your user email as a parmeter
