### ISSUE TITLE
Application permissions

### ISSUE THREAD

**Issue by fredericklin** [microsoftgraph/microsoft-graph-docs#5674]
I'm getting a 403 when doing a GET to this endpoint with application permissions.  I've tried with both Group.Read.All and Group ReadWrite.All scopes applied to the app reg as defined in this doc.

It works fine with delegated permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by oitptobbe** [comment]
You need to get it approved by Microsoft also. It's a "protected api".
https://docs.microsoft.com/en-us/graph/teams-protected-apis

**Comment by Agni-Vikas** [comment]
I have got it approved by Microsoft team by filling that form. it's still not working for application permissions but it's working for delegated permissions
