### ISSUE TITLE
AppCode =? App Password

### ISSUE THREAD

**Issue by husamhilal** [microsoftgraph/microsoft-graph-docs#5675]
Under authMethods, is "AppCode" exactly "App Passwords"? Or is it something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8238a381-7421-a45f-8972-d71e23a3a380
* Version Independent ID: 35235db8-2017-ff94-1574-ec10671a7ba9
* Content: [credentialUserRegistrationDetails resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/credentialuserregistrationdetails?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/credentialuserregistrationdetails.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
From engineering:

App Code is different than App Password. Its generated via Authenticator Apps for MFA and SSPR or H/W tokens . App Password is used for MFA only.

No change required for article. Closing the issue.
