### ISSUE TITLE
Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by icelandgrecian** [microsoftgraph/microsoft-graph-docs#5678]
We have started getting a weird experience, where if we call `https://graph.microsoft.com/v1.0/me/ownedObjects` with no filter param we get the following error, but if we supply something like `$filter=id eq 'groupId'` it works fine. We only have `User.Read.All` permissions. This was working yesterday without an issue.

```json
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "d1c4149d-a64e-4608-8cdf-50076c485dce",
      "date": "2019-09-12T14:56:22"
    }
  }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1713e3b5-47e0-372b-8d59-6926018fde07
* Version Independent ID: aa23772f-b67b-98b0-2902-1f06a4b2e8bd
* Content: [List ownedObjects - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-ownedobjects?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-ownedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-ownedobjects.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
This issue no longer repros. Was likely a temporary issue.
