### ISSUE TITLE
Get subscriptions returns empty values array and/or an odata.nextLink that when queried returns status code 500

### ISSUE THREAD

**Issue by ahaselgrovehatch** [microsoftgraph/microsoft-graph-docs#5681]
I discovered today that when requesting a list of subscriptions using the Graph Explorer that  the value[] is empty, however there is also an odata.nextLink, but when pasted into Graph Explorer this returns with a status code of 500 and an "UnknownError".

This appears to be similar to the behavior previously reported and resolved for #4644

**Comment by mmamaril** [comment]
Thanks  @ahaselgrovehatch for reporting. I can confirm that we have the same issue encountered. 
- Create Subscription - OK
- Get Specific Subscription - OK
- Get List Subscription - **Not working**
- Get Notification - **Not working**

Please update us on the progress of fixing this.

**Comment by sherlock1982** [comment]
I can confirm this also happening for us on get subscription list and it's quite disastrous. 
Looks like sometimes it works sometimes it doesn't.
Here's a code sample in case i do something wrong:

        public async Task<IList<Subscription>> GetSubscriptionsAsync(CancellationToken token)
        {
            var subscriptions = new List<Subscription>();
            var request = _client.Subscriptions.Request();
            while (request != null)
            {
                var response = await request.GetAsync(token);
                subscriptions.AddRange(response);
                request = response.NextPageRequest;
            }
            return subscriptions;
        }

**Comment by raimundasm** [comment]
Hello,
Same problem here
I created subscribtion successfully and received Id in response
I can view it via
https://graph.microsoft.com/v1.0/subscriptions/8a060360-24b8-4b5d-810e-5df2f02ef61a

{
"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions/$entity",
"id": "8a060360-24b8-4b5d-810e-5df2f02ef61a",
...
}
but calling
https://graph.microsoft.com/v1.0/subscriptions/
returns
{
"@odata.context": "https://graph.microsoft.com/v1.0/$metadata#subscriptions",
"@odata.nextLink": "https://graph.microsoft.com/v1.0/subscriptions/?$skiptoken=4ivzOLuAgPfoZRL9VlHjkC3vNI4MkMngxK62wIVhw16GMzP%252Bl%252FNAUj4PC80Lbb4qu%252F7dJGiEA%252BYF91yOc5n7npJQzM75UCN1SJYFJFfSE0E%253D",
"value": []
}

**Comment by venkateshchepuru** [comment]
This issue (List subscriptions giving the empty response along with next link which is not reusable in subsequent API calls) is a bug/regression in our environment due configuration changes made. 

This should not impact other subscription CRUD operations and notification delivery.

We are working on to fix this issue in all our environments. Our ETA to fix this issue in all environments is by   Friday 9/20.

**Comment by piotrci** [comment]
We have deployed the fix to this problem to the production environment. We apologize for any inconvenience caused by this, and thank you for bringing this to our attention.

**Comment by kmichae1** [comment]
This issue seems to be closed but I am still seing this behaviour.
The endpoint https://graph.microsoft.com/v1.0/subscriptions/ sometimes returns my subscriptions and sometimes not. It's completely random, calling it multiple times in a row and some requests return the subscriptions, and some return nothing.

**Comment by ahaselgrovehatch** [comment]
kmichael1, when the call returns no subscriptions does it return a value in the odata.nextLink, and if it does what is the response when querying that link?

**Comment by kmichae1** [comment]
Yes, I just noticed this when I did some further testing. Querying for the next page returns subscriptions. It was just strange that the first page is almost always empty (I had just one subscription when I was testing). Thanks for the quick reply!
