### ISSUE TITLE
paging + batch requests

### ISSUE THREAD

**Issue by droushd** [microsoftgraph/microsoft-graph-docs#5684]
hi - any plans to allow batching and paging in tandem?  e.g. requesting all pages of 'list users' in a single batch request.  seems like i could do an initial 'list users' request and the @odata could contain a list of all additional pages, which i could feed to the batch request.  thanks for considering.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/paging)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
No, we do not have this in our plans.
Have a look at the example of paging the entire user collection in parallel in this demo app:
https://github.com/piotrci/Microsoft-Graph-Efficient-Operations

**Comment by droushd** [comment]
thanks will try this out - much appreciated
