### ISSUE TITLE
Powershell option?

### ISSUE THREAD

**Issue by jschrap** [microsoftgraph/microsoft-graph-docs#5685]
How would you do this with the new Az powershell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bf53c20-0e14-5ad8-5522-6dd2036ced91
* Version Independent ID: 62a97f3a-1e7d-ba70-e827-ad2a18ded879
* Content: [Manage app registration and API permission for Microsoft Graph notifications - Microsoft Graph](https://docs.microsoft.com/en-us/graph/notifications-integration-app-registration#feedback)
* Content Source: [concepts/notifications-integration-app-registration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/notifications-integration-app-registration.md)
* Product: **notifications**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dustindortch** [comment]
New-AzADApplication
