### ISSUE TITLE
FindMeetingTimes returns 'Value cannot be null' error

### ISSUE THREAD

**Issue by no3rdw** [microsoftgraph/microsoft-graph-docs#5696]
I have been using this method for a while and found it stopped working around September 12th without anything changing on my end.  Instead of receiving a meetingTimeSuggestionsResult, I get the following error message:

{"ClassName":"System.ArgumentNullException","Message":"Value cannot be null.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at System.String.Join(String separator, String[] value)\r\n at Microsoft.Griffin.WebService.Calendar.Scheduling.DefaultController.&lt;ExecuteWorkflow&gt;d__53`2.MoveNext()","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nJoin\nmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089\nSystem.String\nSystem.String Join(System.String, System.String[])","HResult":-2147467261,"Source":"mscorlib","WatsonBuckets":null,"ParamName":"value"} 

I *can* execute the exact same request through Graph Explorer and it works... but in my application, I get this unhelpful 'value cannot be null' error.  The app has Calendars.ReadWrite.All permissions, which should be more than enough to execure FindMetingTimes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8b1ea49-cc09-00fe-0fa7-f438b2b337da
* Version Independent ID: a1bd2514-02a7-1125-1896-d3b16defde13
* Content: [user: findMeetingTimes - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-findmeetingtimes?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-findmeetingtimes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-findmeetingtimes.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by EliasKaplan** [comment]
Hi
@no3rdw sorry to know your app was affected.
Fix is being deployed as of now, ready in the next few hours. You can use a workaround meanwhile, add Calendars.Read or Calendars.ReadWrite to your permissions.
BTW: The reason that Graph explorer returns correct is because it includes by default "Calendars.ReadWrite"

**Comment by EliasKaplan** [comment]
MS Graph FindMeetingTimes Fix completed deployment, please check if App is back to previous behavior, no need to use the workaround suggested.
Thx!

**Comment by EliasKaplan** [comment]
Please close the issue, has been resolved for a while
