### ISSUE TITLE
Listing subscriptions stopped working

### ISSUE THREAD

**Issue by billybraga** [microsoftgraph/microsoft-graph-docs#5708]
I've started getting the following error : "Get Subscriptions list is not supported for the API version 1.0."

I've been using this call for a long time; nothing changed on my side.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c121424-d0a2-017c-e40d-3552ea66915c
* Version Independent ID: 999939fe-62c4-e17c-e0b6-d46ef100ecb5
* Content: [List subscriptions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-list.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sebestindragos** [comment]
We are facing the same issue with this endpoint. Started failing about 9 hours ago. Also didn't change anything on our end.

**Comment by piotrci** [comment]
We have deployed the fix to this problem to the production environment. We apologize for any inconvenience caused by this, and thank you for bringing this to our attention.
