### ISSUE TITLE
Limits on subscribing to calendar events

### ISSUE THREAD

**Issue by maxlund** [microsoftgraph/microsoft-graph-docs#5709]
Are there any limits for a service user on subscribing to events for calendars? In the scenario that a service account is subscribing to all the calendars of rooms for a large organization, is there a possibility that the account would hit some limit? The only limits that are listed are for Azure AD based resources, where it says that "an app can create many more subscriptions to message or event resources". Are the subscription limits for a single user for non-Azure AD resources anything to be concerned about?

Thankful for any help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#processing-the-notification)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
No, there aren't any that you should be concerned about.

**Comment by maxlund** [comment]
So these 429 responses we started getting are unrelated?

https://stackoverflow.com/questions/58076298/getting-a-429-response-when-attempting-to-subscribe-to-calendar

**Comment by nblasm** [comment]
@maxlund did you find an answer to this, or atleast a workaround? How many subscriptions did you manage to handle without being throttled?

**Comment by maxlund** [comment]
@nblasm We implemented retry logic according to https://docs.microsoft.com/en-us/graph/throttling
However we opted to remove features related to subscriptions to shared (i.e. room) calendars, since the scope needed for the service account is too permissive. Even if the delegated user scope `Calendars.Read.Shared` could be used to query events in a shared calendar, you need `Calendars.Read` on the application level to subscribe to notifications for changes in the shared calendar. This scope unfortunately also enables you to read all event details in all calendars at tenant.
