### ISSUE TITLE
Not clear what the IDs that should be used for the request are

### ISSUE THREAD

**Issue by ericrrichards** [microsoftgraph/microsoft-graph-docs#5715]
The example invocation is:
await graphClient.Teams["{id}"].InstalledApps["{id}"]
	.Upgrade()
	.Request()
	.PostAsync();

I'm not clear on what the second {id} is supposed to be.  Is it the TeamsAppInstallation.Id, or the TeamsAppInstallation.TeamsApp.Id or the TeamsAppInstallation.TeamsApp.ExternalId?

None of these seem to work - I get a Microsoft.Graph.ServiceException with the message: This request is forbidden.

I have the permissions indicated in the documentation on my Azure AD app registration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4c235b1-4c1d-1a5d-eed0-9202e282ccd2
* Version Independent ID: 86615b8e-3047-a27a-1c52-9e55ce32b73b
* Content: [Upgrade an app in a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-upgrade?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamsappinstallation-upgrade.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ericrrichards** [comment]
Oof, sorry, I had the Groups.ReadWrite.All permission setup as application-level rather than as delegated, and was trying to invoke the operation with a user bearer token and not the application bearer token.

If anyone else is also confused by the doc, it would be clearer if it was presented like this:
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

await graphClient.Teams["{teamId}"].InstalledApps["{teamsAppInstallationId}"]
	.Upgrade()
	.Request()
	.PostAsync();

**Comment by jasonjoh** [comment]
@darrelmiller this is good feedback on the snippets.

**Comment by darrelmiller** [comment]
@jasonjoh @ericrrichards Yes, agreed that would be clearer.  However, we don't touch the parameter names in the generated code, we just carry them through from the HTTP request.  e.g. 

    POST /teams/{id}/installedApps/{id}/upgrade

This particular case should be fixed by changing the HTTP request to

   POST /teams/{teamId}/installedApps/{teamsAppInstallationId}/upgrade

and that can be done directly as a PR to the docs.

**Comment by jasonjoh** [comment]
Good to know, wasn't sure where the snippet generator got those placeholders from.

@ericrrichards would you like to do the honors and get your avatar into the contributor list? :) If not I can take care of it.

**Comment by HunaidHanfee-MSFT** [comment]
Hello, 
This has been updated in the doc:
[teamsAppInstallation: upgrade](https://docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-1.0&tabs=csharp)

Thanks for telling us.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
