### ISSUE TITLE
Id uniqueness

### ISSUE THREAD

**Issue by nozhT** [microsoftgraph/microsoft-graph-docs#5724]
Since users, groups and devices are all directoryObjects, is it safe to assume that a user can never have the same ID as a group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bfca17-b9c5-785d-3d0b-428842f7c080
* Version Independent ID: e47c10cf-cd07-850e-fdb5-29d0aec8a5bd
* Content: [directoryObject resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/directoryobject?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/directoryobject.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/directoryobject.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Id's are unique. A user cannot have the same ID as a group. No change required to the article. Closing the issue.
