### ISSUE TITLE
ID is required in DirectoryObject

### ISSUE THREAD

**Issue by suganyamk** [microsoftgraph/microsoft-graph-docs#5727]
While adding owner or member to group, the DirectoryObject requires ID property set. C# section of the document doesn't mention it in the sample. Request without ID fails with "ID is required to add a reference." error.

https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=csharp#example

`public async Task AddOwnerToGroup(string groupid, string ownerId)
        {
            var directoryObject = new DirectoryObject
            {
                **Id = ownerId,**
                AdditionalData = new Dictionary<string, object>()
                {
                    {"@odata.id",$"https://graph.microsoft.com/v1.0/users/{ownerId}"}
                }
            };

            await _graphClient.Groups[groupid].Owners.References
                .Request()
                .AddAsync(directoryObject);

        }`

Or pls. let me know if this isn't the right approach.

**Comment by blyw** [comment]
I too tried to use the code sample in the documentation and got the same error.
Thanks. Your solution works for me too. 

I ended up with:
` var directoryObject = new DirectoryObject { Id = user.Id };`
`await graphServiceClient.Groups[Group.Id].Members.References.Request().AddAsync(directoryObject);`

Inconsistency between documentation and implementation is horribly fustrating. Could somebody please clarify the discrepancy and apply fixes? Thanks in advance.

**Comment by jthake-msft** [comment]
Thanks for submitting this. as this wasn't submitted directly from the feedback sectin on the docs page itself, this slipped through our process. I have assigned this to be updated.
