### ISSUE TITLE
Not getting the employeeID with  v1.0 version

### ISSUE THREAD

**Issue by lumusinnova** [microsoftgraph/microsoft-graph-docs#5728]
Issue:
I am trying to  get the user's profile and the employeeID  with  https://graph.microsoft.com/v1.0/me  nevertheless I can not see it in the response, I can get the employeeID only with the beta version  https://graph.microsoft.com/beta/me. I checked the documentation and that field supposed to be in the  v1.0 version.  Additionally I need to get the employeeNumber, but that field does not come in neither of the queries.
Article:

**Comment by lumusinnova** [comment]
I am trying to  get the user's profile and the employeeID  with  https://graph.microsoft.com/v1.0/me  nevertheless I can not see it in the response, I can get the employeeID only with the beta version  https://graph.microsoft.com/beta/me. I checked the documentation and that field supposed to be in the  v1.0 version.  Additionally I need to get the employeeNumber, but that field does not come in neither of the queries.

**Comment by jasonjoh** [comment]
You need to explicitly request that field with `$select` in v1. From the [v1 reference](https://docs.microsoft.com/graph/api/user-get?view=graph-rest-1.0&tabs=http):

> **Note:** Getting a user returns a default set of properties only (`businessPhones`, `displayName`, `givenName`, `id`, `jobTitle`, `mail`, `mobilePhone`, `officeLocation`, `preferredLanguage`, `surname`, `userPrincipalName`). Use `$select` to get the other properties and relationships for the user object.
