### ISSUE TITLE
UnknownTenantId

### ISSUE THREAD

**Issue by dboeloe** [microsoftgraph/microsoft-graph-docs#5738]
Issue:
The response when hit the api
Error Code: 404
{"error"=>{"code"=>"UnknownTenantId", "message"=>"We do not recognize this tenant ID <tenant id>. 
Please double-check the tenant ID and try again.", 
"innerError"=>{"request-id"=>"82e958bb-86dd-42c2-a9ad-ec6b47d008fd", "date"=>"2019-09-19T07:50:54"}}}

Tenant is active, when i check using /domains or /organization its valid.

Please Advice

Article:https://docs.microsoft.com/en-us/graph/api/reportroot-getonedriveusageaccountdetail?view=graph-rest-1.0&tabs=http

**Comment by dboeloe** [comment]
Since, there's no respond from Microsoft.

I will share the step that i've been througt to solve this problems.

- Try to create reports on your Admin Center (This should failed or return no data)
- Its more likely that the API won't work if there;s no data. (If its correct, it should be documented)
- Make sure user one drive has file in it. If no, try to upload one.
- Voila the API works now

Hope it helps

**Comment by jthake-msft** [comment]
As this is a reproable issue, and not actually feedback on the docs but the service. Can you please submit this to portal.azure.com and use help and support. Details here https://twitter.com/jthake/status/1179805761339187200

Thank you for reporting this in advance.
