### ISSUE TITLE
Get pending requests to join

### ISSUE THREAD

**Issue by liiamjones** [microsoftgraph/microsoft-graph-docs#5739]
Is it possible to see the pending requests to join a team via graph? im aware the teams client does it via the teams api at https://teams.microsoft.com/api/mt/amer/beta/teams/findJoinRequests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
No, its not.
