### ISSUE TITLE
Exact text searches?

### ISSUE THREAD

**Issue by heyalistair** [microsoftgraph/microsoft-graph-docs#5767]
Can we do exact text searches? It is unclear from the documentation. Like searching for all documents that contain "Bob Smith" instead of all documents with "Bob" AND "Smith"?

I tried doing q=('"Bob Smith"') but that doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de33ed18-c074-a734-0b01-648888cb94aa
* Version Independent ID: 9fa15051-394e-d4ce-4687-c93be0ca8b80
* Content: [Search for files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by johannsa** [comment]
Is there any update or any workaround for this?

**Comment by joey-mcadams** [comment]
Also bumping...would like to know if there's a way to do this.

**Comment by lramosvea** [comment]
Hi, I tried doing search(q='Contoso Project') and it worked. Please feel free to reopen the issue in case this doesn't work for you.
