### ISSUE TITLE
using filters to allow parallelization

### ISSUE THREAD

**Issue by droushd** [microsoftgraph/microsoft-graph-docs#5774]
hi - is there any way to split the alphabet to allow parallelization on the users/groups endpoints?  It does not seem to support filter with a lt/gt/ge/le (e.g. all userprincipalnames lt b).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
This issue has been reviewed and the product team has no plans to address.
