### ISSUE TITLE
List Plan Tasks filter query produces no error but does not filter results

### ISSUE THREAD

**Issue by djswilly** [microsoftgraph/microsoft-graph-docs#5779]
Using this request with a filter query (for example, planner/plans/{plan-id}/tasks?$filter=percentComplete eq 100) produces a successful response (Status Code 200) but does not filter the results i.e. all tasks are returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 722ad076-a741-d4e5-92cb-4f07d1baaa9e
* Version Independent ID: 02808443-59b2-f74f-7c22-3ced1cd818fe
* Content: [List tasks - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/plannerplan-list-tasks?view=graph-rest-1.0&tabs=http#code-try-1)
* Content Source: [api-reference/v1.0/api/plannerplan-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannerplan-list-tasks.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markholst** [comment]
I'm fairly certain none of the filtering works.  I tried filtering on Bucket ID in my query and it still returned all results.

**Comment by renatoromao** [comment]
The same issue here.

**Comment by JMTeamway** [comment]
Same for me

**Comment by markholst** [comment]
I've re-posted this over here:
https://docs.microsoft.com/en-us/answers/questions/586446/list-plan-tasks-filter-query-produces-no-error-but.html
