### ISSUE TITLE
Results limit

### ISSUE THREAD

**Issue by pierodamafalda** [microsoftgraph/microsoft-graph-docs#5781]
Does not clarify if there is a limit to the numer of results. I tried to use it by I get too few results. So I think there is a limit but how to change it in the query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5159efcf-058c-7bf8-3bd4-a680224b72b6
* Version Independent ID: f94e77f3-c166-cc46-de80-b4ca5e8e2803
* Content: [Search for sites - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/site-search.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-search.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by mehtanilay10** [comment]
I was also looking for the same. And I found the way to handle this.
You can use `$top` query parameter for this.
Just like: https://graph.microsoft.com/v1.0/sites?search=Home&$top=2
