### ISSUE TITLE
where are security baselines viewable once implemented

### ISSUE THREAD

**Issue by droushd** [microsoftgraph/microsoft-graph-docs#5783]
hi - can i see implemented templates in another endpoint?  i would like to see assigned groups, settings details, etc...  I didn't see them in these endpoints (maybe i'm mistaken?): '/deviceManagement/deviceConfigurations', '/deviceAppManagement/mobileApps', '/deviceManagement/deviceCompliancePolicies', '/deviceManagement/groupPolicyConfigurations'.  Thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788b977b-806b-b25e-14a1-45df135f4988
* Version Independent ID: 251ee845-2701-2fb7-7db7-ba41e758a1f1
* Content: [List deviceManagementTemplates - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-deviceintent-devicemanagementtemplate-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-deviceintent-devicemanagementtemplate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-deviceintent-devicemanagementtemplate-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rolyon** [comment]
Hi @droushd 
Thanks for the feedback. Here is what we heard from the team. The following is an example graph call to list templates:
https://graph.microsoft.com/beta/deviceManagement/templates?$filter=(isof(%27microsoft.graph.securityBaselineTemplate%27)

**Comment by rolyon** [comment]
Please reopen issue if you have additional feedback.
thanks

**Comment by droushd** [comment]
hi - thanks so much for the note - i'm looking for the implemented copy, with configuration, assignments and even results/status.  it's my impression the endpoint you shared is just the list of available templates.  thanks for clarifying.  best, David
