### ISSUE TITLE
Lifecycle notifications for subscriptions registered in the v1.0 API

### ISSUE THREAD

**Issue by maxlund** [microsoftgraph/microsoft-graph-docs#5784]
It says:

 "Microsoft Graph sends a subscriptionRemoved notification to the lifecycleNotificationUrl (if specified), or the notificationUrl." 

Does this also apply for subscriptions registered with the v1.0 API (i.e. not the beta)? Since the notification examples for these lifecycleEvents looks a bit different than regular notifications, it would be a problem if they now start going to the same notificationUrl we registered in the v.10 API. There we expect the JSON to be of a different format when we do de-serialization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0c2065-46e2-7cd3-4867-a7aba71c2f28
* Version Independent ID: 445e44a7-50eb-0ea3-18c1-0e4dae989e5f
* Content: [Reduce missing subscriptions and notifications for Outlook resources (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks-outlook-authz)
* Content Source: [concepts/webhooks-outlook-authz.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks-outlook-authz.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
@maxlund , yes they are being sent for all subscriptions (this has been happening in production for several months now), created via /beta and /v1.0. We expect that some client code mail fail to process these notifications as they have a slightly different shape. However, we thought that should be OK - client code failing to process these notifications should not result in major problems client side - that has been our assumption.

Please let us know if you have any cases where this has caused problems. @svpsiva , should have a look at this, too.

**Comment by maxlund** [comment]
Okay, it seems a bit strange when we read this https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

"API sets on the v1.0 endpoint (https://graph.microsoft.com/v1.0) are in general availability (GA) status, and have gone through a rigorous review-and-feedback process with customers to meet practical, production needs. Updates to APIs on this endpoint are additive in nature and do not break existing app scenarios."

If the new behavior is in production on /v1. 0 already, why not let us register a lifecycleNotificationUrl there as well?

**Comment by baywet** [comment]
Thank you for the information and sorry about the delayed answer.
As for the  documentation I authored a pull request to address the main concerns #6903 
About the fact your subscriptions created via the v1.0 APIs are sending new notifications that your endpoints were not originally built to receive: this is a limitation on our side and let me apologize for any inconvenience caused.
