### ISSUE TITLE
query - can teamsApp.id can be considered as Planner id ?

### ISSUE THREAD

**Issue by dhheeraj** [microsoftgraph/microsoft-graph-docs#5793]
suppose multiple tabs are added as Planner ,each having different name. Iterating through the  tabs and identified as Planner tab and teamApp.id can be considered as planner id to fetch the plans/tasks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002fd0aa-9008-9299-e29f-fb26f4d1b1e7
* Version Independent ID: bd94c468-347b-1db6-8c61-50d8a6ae58b6
* Content: [List tabs in channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamstab-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prithvi-MSFT** [comment]
Hi, are you trying to access planner task using to id of the planner tab ?
