### ISSUE TITLE
ErrorAccessDenied with Calendars.ReadWrite permission

### ISSUE THREAD

**Issue by icyjhl** [microsoftgraph/microsoft-graph-docs#5796]
I keeps get ErrorAccessDenied error even I already got Calendars.ReadWrite permission, why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e527ca2-ecbe-5512-4115-736edc2ce5e6
* Version Independent ID: c5d90251-c824-6abb-ef53-f3594168fc26
* Content: [Create Calendar - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-calendars.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by michalkadziolka** [comment]
I also have permission issue. 
Can't create subscription for my on drive. Even though I have Files.ReadWrite.All , I'm getting 403 error, with message: "Operation: Create; Exception: [Status Code: Forbidden; Reason: The caller does not have permission to perform the action.]"

**Comment by Harini84** [comment]
@davidmu1 
There is permission issue reported on both calendar and files. Can you please assign it to identity team?

**Comment by davidmu1** [comment]
No doc change identified. Please reopen with specific information about the error if needed. Closing the issue.
