### ISSUE TITLE
Any plan to move this API to v1.0 endpoint ?

### ISSUE THREAD

**Issue by abhatt29** [microsoftgraph/microsoft-graph-docs#5797]
What is the plan to move this API to v1.0 endpoint ?

If this is not planned to be moved to v1.0, what are the equivalent API(in Microsoft Graph v1.0 & Azure AD Graph) to call to get Group & Role details for token user(me) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa79b6c6-f4af-f8f3-3304-32b2f172d821
* Version Independent ID: de382dbd-ef59-9a2e-dad0-aefd5f97555b
* Content: [appRoleAssignment resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/approleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/approleassignment.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @sumurthy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@sureshja  I believe this page has teh wrong page owner too. Can we get teh appropriate owner for this page so that the wdkbot assigns correctly in first place?

**Comment by lafe** [comment]
The first version of the content source is from 2015 according to the history. Does that mean, that this API is beta since 2015?!?

**Comment by SychevIgor** [comment]
Well... interesting situation. It's almost 2020 and API for a 5 years in beta.

**Comment by psignoret** [comment]
Better late than never: this is now in v1.0!
