### ISSUE TITLE
Invitations lifecycle

### ISSUE THREAD

**Issue by ertork** [microsoftgraph/microsoft-graph-docs#5799]
It would be interesting to know how long the invitation redeem urls will be available for the users invited to join as external users. Is it possible to find "stale" invitations and possible delete them/reissue them if the invitation redeem urls have a long retention in the system? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0170d-e214-ce6f-b7b4-589960e9962d
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/invitation.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
According to engineering:

When an invite is out there is no expiry for that invite. The external user can redeem that invite any time.  If the inviter wants to revoke an invite, they can simply delete the invited user object from resource tenant. Also, an tenant admin can do some cleanup like delete guest who hasn’t redeem an invite for than 3 months or so by querying and checking user [properties](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta#properties) “externalUserState” and “externalUserStateChangeDateTime”.

No change required to the article. Closing the issue.
