### ISSUE TITLE
FindMeetingTimes providing suggestions outside working hours

### ISSUE THREAD

**Issue by OlliJuhani** [microsoftgraph/microsoft-graph-docs#580]
I have a problem where I am receiving meeting time suggestions outside of working hours. In this particular example case inviter and participant have currently time zone UTC+02:00 and working hours 8-17 set in O365 / calendar settings. When I limit the start and end e.g. with the constraints:

```
"timeConstraint" : {
    "timeslots" : [{
            "start" : {
                "dateTime" : "2016-10-26T06:00:26.6533137Z",
                "timeZone" : "UTC"
            },
            "end" : {
                "dateTime" : "2016-10-26T23:59:00.0000000",
                "timeZone" : "UTC"
            }
        }
    ]
}
```

In a respose I usually get several suggestions that are inside the attendees working hours, but at least one that is not, for the query above:

```
"meetingTimeSlot" : {
    "start" : {
        "dateTime" : "2016-10-26T21:00:00.0000000",
        "timeZone" : "UTC"
    },
    "end" : {
        "dateTime" : "2016-10-26T21:30:00.0000000",
        "timeZone" : "UTC"
    }
}
```

As a suggestionReason value with these suggestions outside the working hours, seems usually be "Suggested because it is one of the nearest times when all attendees are available.". Whether I include activityDomain = "work" in the query or not, doesn't seem to have an effect.

**Comment by wesley-dynamicowl** [comment]
I'm seeing a similar issue after the update to the API a couple of weeks ago.

I have suggestions ranging from 4:30 AM to 8:00 PM

**Comment by EliasKaplan** [comment]
Hi
I work with the FindMeetingtimes, looking into the issue can you provide some more details?
The complete Request and Response (including the  will help? So far I couldn't get the repor, still trying but will be really helpful to get the complete response. Also the working hours and Timezone of the users.
Thx
Elias

**Comment by OlliJuhani** [comment]
Hi Elias,
here's an example request and response, with emails and room names changed for privacy reasons. Working hours are 8am-17pm EET for the user that makes API request as well as for the other participant. The last suggestion below, from 22:00 to 23:00 UTC would be outside of the working hours.

Request:
```
{
"attendees" : [{
		"type" : "required",
		"emailAddress" : {
			"address" : "attendee1@foobar.com"
		}
	}
],
"locationConstraint" : {
	"isRequired" : true,
	"suggestLocation" : false,
	"locations" : [{
			"displayName" : "Room1",
			"locationEmailAddress" : null
		}
	]
},
"timeConstraint" : {
	"timeslots" : [{
			"start" : {
				"dateTime" : "2016-11-23T00:00:00.0000000",
				"timeZone" : "UTC"
			},
			"end" : {
				"dateTime" : "2016-11-23T23:59:00.0000000",
				"timeZone" : "UTC"
			}
		}
	],
	"activityDomain" : "work"
},
"meetingDuration" : "PT1H",
"isOrganizerOptional" : false,
"returnSuggestionReasons" : true,
"maxCandidates" : 5
}

```

Response:

```
{
"@odata.context" : "https://graph.microsoft.com/beta/$metadata#microsoft.graph.meetingTimeSuggestionsResult",
"meetingTimeSuggestions" : [{
		"meetingTimeSlot" : {
			"start" : {
				"dateTime" : "2016-11-23T06:00:00.0000000",
				"timeZone" : "UTC"
			},
			"end" : {
				"dateTime" : "2016-11-23T07:00:00.0000000",
				"timeZone" : "UTC"
			}
		},
		"confidence" : 100.0,
		"organizerAvailability" : "free",
		"attendeeAvailability" : [{
				"attendee" : {
					"type" : "required",
					"emailAddress" : {
						"address" : "attendee1@foobar.com"
					}
				},
				"availability" : "free"
			}
		],
		"locations" : [{
				"displayName" : "Room1"
			}
		],
		"suggestionReason" : "Suggested because of the time in advance you like to schedule your meetings."
	}, {
		"meetingTimeSlot" : {
			"start" : {
				"dateTime" : "2016-11-23T14:00:00.0000000",
				"timeZone" : "UTC"
			},
			"end" : {
				"dateTime" : "2016-11-23T15:00:00.0000000",
				"timeZone" : "UTC"
			}
		},
		"confidence" : 100.0,
		"organizerAvailability" : "free",
		"attendeeAvailability" : [{
				"attendee" : {
					"type" : "required",
					"emailAddress" : {
						"address" : "attendee1@foobar.com"
					}
				},
				"availability" : "free"
			}
		],
		"locations" : [{
				"displayName" : "Room1"
			}
		],
		"suggestionReason" : "Suggested because of the time in advance you like to schedule your meetings."
	}, {
		"meetingTimeSlot" : {
			"start" : {
				"dateTime" : "2016-11-23T13:00:00.0000000",
				"timeZone" : "UTC"
			},
			"end" : {
				"dateTime" : "2016-11-23T14:00:00.0000000",
				"timeZone" : "UTC"
			}
		},
		"confidence" : 100.0,
		"organizerAvailability" : "free",
		"attendeeAvailability" : [{
				"attendee" : {
					"type" : "required",
					"emailAddress" : {
						"address" : "attendee1@foobar.com"
					}
				},
				"availability" : "free"
			}
		],
		"locations" : [{
				"displayName" : "Room1"
			}
		],
		"suggestionReason" : "Suggested because of the time in advance you like to schedule your meetings."
	}, {
		"meetingTimeSlot" : {
			"start" : {
				"dateTime" : "2016-11-23T12:00:00.0000000",
				"timeZone" : "UTC"
			},
			"end" : {
				"dateTime" : "2016-11-23T13:00:00.0000000",
				"timeZone" : "UTC"
			}
		},
		"confidence" : 100.0,
		"organizerAvailability" : "free",
		"attendeeAvailability" : [{
				"attendee" : {
					"type" : "required",
					"emailAddress" : {
						"address" : "attendee1@foobar.com"
					}
				},
				"availability" : "free"
			}
		],
		"locations" : [{
				"displayName" : "Room1"
			}
		],
		"suggestionReason" : "Suggested because of the time in advance you like to schedule your meetings."
	}, {
		"meetingTimeSlot" : {
			"start" : {
				"dateTime" : "2016-11-23T22:00:00.0000000",
				"timeZone" : "UTC"
			},
			"end" : {
				"dateTime" : "2016-11-23T23:00:00.0000000",
				"timeZone" : "UTC"
			}
		},
		"confidence" : 100.0,
		"organizerAvailability" : "free",
		"attendeeAvailability" : [{
				"attendee" : {
					"type" : "required",
					"emailAddress" : {
						"address" : "attendee1@foobar.com"
					}
				},
				"availability" : "free"
			}
		],
		"locations" : [{
				"displayName" : "Room1"
			}
		],
		"suggestionReason" : "Suggested because of the time in advance you like to schedule your meetings."
	}
],
"emptySuggestionsReason" : ""
}

```

**Comment by EliasKaplan** [comment]
Opened internal VSO item to investigate the Timeslot suggested outside Working hours.
Elias

**Comment by Lucho1970** [comment]
I'm having this same issue and I am wondering if there is any resolution or workaround at the moment? I have resorted to using linq to filter out the dates and times outside "normal" work hours, but this solution doesn't work very well in our environment as some staff will take meetings earlier or later in the day than others.

**Comment by ricardrmsft** [comment]
Hello everybody, wondering if this is still reproing for you.  If it does, would you mind sending your requestIDs?  (RequestId is a header you can find in the response).

Having a particular request id would make it easier for us to verify if something is wrong in FindMeetingTimes.

**Comment by 2toLeadMike** [comment]
@ricardrmsft 

client-request-id: 31da65f1-f2c0-484f-86c2-30381aaee9c1
request-id: 31da65f1-f2c0-484f-86c2-30381aaee9c1

This returned items at around 10:30PM when work hours ends at 5:00. The request was far into the future but perhaps might help your debugging.

**Comment by chewcw** [comment]
Any update to this issue?

**Comment by trace9** [comment]
I can't get anything outside of working hours when specifying "Unrestricted" for the TimeConstraint ActivityDomain value. I'm trying to get times from 6am-8pm and only get times from 8am-6:30 (I haven't seen any returned times later than this.) Adjusting the start/end times has no effect.

**Comment by theakc** [comment]
The issue with findmeetingtimes returning meeting times outside working hours, when activityDomain is set to "work" , is fixed. 

@trace9 : are you still able to repro your issue? could you provide the request that you are sending.  With below request body, I could not repro the issue.

"timeConstraint": {
    "activityDomain":"unrestricted", 
    "timeslots": [ 
      { 
        "start": { 
          "dateTime": "2018-08-22T17:00:00",  
          "timeZone": "Pacific Standard Time" 
        },  
        "end": { 
          "dateTime": "2018-08-23T17:00:00",  
          "timeZone": "Pacific Standard Time" 
        } 
      } 
    ] 
  }

**Comment by theakc** [comment]
If you  have more questions about this , please open a new item in Stackoverflow.

The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph )' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
Feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support

**Comment by trace9** [comment]
@theakc - Thanks for getting back to me. Yes, still appears to be an issue. The account I'm testing has work hours defined from 6am-8pm MST. I'm running the availability on 20+ users and they all show the same start/end times even though the 'ActivityDomain' is 'Unrestricted'. Thanks for the help and please let me know if you'd like a separate issue created. 

The request: 
{"MaxCandidates":100,"Attendees":[],"LocationConstraint":{"IsRequired":"false","SuggestLocation":"false"},"TimeConstraint":{"ActivityDomain":"Unrestricted","Timeslots":[{"Start":{"DateTime":"2018-08-21T06:00:00.0000000","TimeZone":"Mountain Standard Time"},"End":{"DateTime":"2018-09-01T20:00:00.0000000","TimeZone":"Mountain Standard Time"}}]},"MeetingDuration":"PT1H","ReturnSuggestionReasons":"true"}

PHP result (showing first two days only):
[availableMeetingTimes] => Array
        (
            [2018-08-21] => Array
                (
                    [0] => stdClass Object
                        (
                            [startHour] => 8
                            [endHour] => 9
                            [start] => 2018-08-21T08:00:00.0000000
                            [end] => 2018-08-21T09:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 8:00 AM - 9:00 AM
                        )

                    [1] => stdClass Object
                        (
                            [startHour] => 9
                            [endHour] => 10
                            [start] => 2018-08-21T09:00:00.0000000
                            [end] => 2018-08-21T10:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 9:00 AM - 10:00 AM
                        )

                    [2] => stdClass Object
                        (
                            [startHour] => 10
                            [endHour] => 11
                            [start] => 2018-08-21T10:00:00.0000000
                            [end] => 2018-08-21T11:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 10:00 AM - 11:00 AM
                        )

                    [3] => stdClass Object
                        (
                            [startHour] => 11
                            [endHour] => 12
                            [start] => 2018-08-21T11:00:00.0000000
                            [end] => 2018-08-21T12:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 11:00 AM - 12:00 PM
                        )

                    [4] => stdClass Object
                        (
                            [startHour] => 12
                            [endHour] => 13
                            [start] => 2018-08-21T12:00:00.0000000
                            [end] => 2018-08-21T13:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 12:00 PM - 1:00 PM
                        )

                    [5] => stdClass Object
                        (
                            [startHour] => 14
                            [endHour] => 15
                            [start] => 2018-08-21T14:00:00.0000000
                            [end] => 2018-08-21T15:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 2:00 PM - 3:00 PM
                        )

                    [6] => stdClass Object
                        (
                            [startHour] => 15
                            [endHour] => 16
                            [start] => 2018-08-21T15:00:00.0000000
                            [end] => 2018-08-21T16:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 3:00 PM - 4:00 PM
                        )

                    [7] => stdClass Object
                        (
                            [startHour] => 16
                            [endHour] => 17
                            [start] => 2018-08-21T16:00:00.0000000
                            [end] => 2018-08-21T17:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 4:00 PM - 5:00 PM
                        )

                    [8] => stdClass Object
                        (
                            [startHour] => 17
                            [endHour] => 18
                            [start] => 2018-08-21T17:00:00.0000000
                            [end] => 2018-08-21T18:00:00.0000000
                            [date] => Tue. 08/21/2018
                            [displayText] => 5:00 PM - 6:00 PM
                        )

                )

            [2018-08-22] => Array
                (
                    [0] => stdClass Object
                        (
                            [startHour] => 8
                            [endHour] => 9
                            [start] => 2018-08-22T08:00:00.0000000
                            [end] => 2018-08-22T09:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 8:00 AM - 9:00 AM
                        )

                    [1] => stdClass Object
                        (
                            [startHour] => 9
                            [endHour] => 10
                            [start] => 2018-08-22T09:00:00.0000000
                            [end] => 2018-08-22T10:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 9:00 AM - 10:00 AM
                        )

                    [2] => stdClass Object
                        (
                            [startHour] => 10
                            [endHour] => 11
                            [start] => 2018-08-22T10:00:00.0000000
                            [end] => 2018-08-22T11:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 10:00 AM - 11:00 AM
                        )

                    [3] => stdClass Object
                        (
                            [startHour] => 11
                            [endHour] => 12
                            [start] => 2018-08-22T11:00:00.0000000
                            [end] => 2018-08-22T12:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 11:00 AM - 12:00 PM
                        )

                    [4] => stdClass Object
                        (
                            [startHour] => 12
                            [endHour] => 13
                            [start] => 2018-08-22T12:00:00.0000000
                            [end] => 2018-08-22T13:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 12:00 PM - 1:00 PM
                        )

                    [5] => stdClass Object
                        (
                            [startHour] => 13
                            [endHour] => 14
                            [start] => 2018-08-22T13:00:00.0000000
                            [end] => 2018-08-22T14:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 1:00 PM - 2:00 PM
                        )

                    [6] => stdClass Object
                        (
                            [startHour] => 14
                            [endHour] => 15
                            [start] => 2018-08-22T14:00:00.0000000
                            [end] => 2018-08-22T15:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 2:00 PM - 3:00 PM
                        )

                    [7] => stdClass Object
                        (
                            [startHour] => 15
                            [endHour] => 16
                            [start] => 2018-08-22T15:00:00.0000000
                            [end] => 2018-08-22T16:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 3:00 PM - 4:00 PM
                        )

                    [8] => stdClass Object
                        (
                            [startHour] => 16
                            [endHour] => 17
                            [start] => 2018-08-22T16:00:00.0000000
                            [end] => 2018-08-22T17:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 4:00 PM - 5:00 PM
                        )

                    [9] => stdClass Object
                        (
                            [startHour] => 17
                            [endHour] => 18
                            [start] => 2018-08-22T17:00:00.0000000
                            [end] => 2018-08-22T18:00:00.0000000
                            [date] => Wed. 08/22/2018
                            [displayText] => 5:00 PM - 6:00 PM
                        )
                )

**Comment by milapshah15** [comment]
I have been trying to get this work but getting error.here is my request/response

Request body

            {
                "attendees": [
                {
                    "type": "required",
                    "emailAddress": {
                    "name": "M",
                    "address": "xxxxxx@xxx.com"
                    }
                }
                ],
                "locationConstraint": {
                "isRequired": false,
                "suggestLocation": false,
                "locations": [
                    {
                    "resolveAvailability": false,
                    "displayName": "xxxx"
                    }
                ]
                },
                "timeConstraint": {
                "activityDomain": "work",
                "timeslots": [
                    {
                    "start": {
                        "dateTime": "2019-04-18T09:00:00",
                        "timeZone": "Pacific Standard Time"
                    },
                    "end": {
                        "dateTime": "2019-04-20T17:00:00",
                        "timeZone": "Pacific Standard Time"
                    }
                    }
                ]
                },
                "meetingDuration": "PT2H",
                "returnSuggestionReasons": true,
                "minimumAttendeePercentage": 100
            }

            Error 

            {
                "error": {
                    "code": "BadArgument",
                    "message": "Invalid user address",
                    "innerError": {
                        "request-id": "02d99e8e-b61f-4e4a-96de-371cd3786489",
                        "date": "2019-04-18T23:12:55"
                    }
                }
            }

**Comment by milapshah15** [comment]
Is this fixed now?

I can still see lot of suggestions outside working hours.

Warm regards
Milap
