### ISSUE TITLE
[Place API] Any property indicates that a room is available and can we book a room?

### ISSUE THREAD

**Issue by xhr0804** [microsoftgraph/microsoft-graph-docs#5806]
Issue:
I tried to use the Place Api https://graph.microsoft.com/beta/places/microsoft.graph.room and the result shows like:
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#places/microsoft.graph.room",
    "value": [
        {
            "id": "d4552b5c-4215-479a-84cd-137e20d3f61a",
            "displayName": "Conf Room Stevens",
            "address": null,
            "geoCoordinates": null,
            "phone": "",
            "nickname": "Conf Room Stevens",
            "emailAddress": "Stevens@M365x214355.onmicrosoft.com",
            "building": null,
            "floorNumber": null,
            "label": null,
            "capacity": null,
            "bookingType": null,
            "audioDeviceName": null,
            "videoDeviceName": null,
            "displayDeviceName": null,
            "isWheelChairAccessible": false,
            "tags": []
        },....

I can not find a property which can tell users whether the room is available or not. 
What's more, is there any API support the action like "book the room", for I just find the Get Place one without Create/Delete/Update.

Article:

**Comment by cys22** [comment]
Hi, xhr0804.
You can use this API to get room is available info.
https://graph.microsoft.com/v1.0/me/findmeetingtimes

**Comment by xhr0804** [comment]
Thanks cys22.
So, when I find a room available, is there any way to book it so that others will not double book it?

**Comment by svrooij** [comment]
And booking a room is done by creating a new calendar event (in your own or the users calendar) and inviting the room

**Comment by cys22** [comment]
https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http

**Comment by xhr0804** [comment]
Thanks so much.
I find the findmeetingtimes API can suggest some meeting rooms. So could I know how it suggest the rooms , depend on the location of user and room?

**Comment by EliasKaplan** [comment]
Suggestion uses relevance, based on previous meetings history for the organizer, and availability on the timeslots requested
