### ISSUE TITLE
Clearing Manager Attribute

### ISSUE THREAD

**Issue by ross-currie** [microsoftgraph/microsoft-graph-docs#5807]
This page is missing information for clearing a user's manager
I've been trying to recreate the functionality implemented by Remove-AzureADUserManager in the AzureAD PS module

Have tried setting @odata.id to null, but it rejects it as an invalid URL. As near as I can gather, it's this:

DELETE https://graph.microsoft.com/v1.0/users/{id}/manager/$ref
Content-type: application/json

It seems to work, but I'm not convinced it's the proper way to go about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b619f6e-e391-ef3d-cd45-682ad87b5a73
* Version Independent ID: 907a4979-7d65-112e-05d1-c2a13fd5f897
* Content: [Assign a manager - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-manager.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by CodyDeGhetto** [comment]
This is not a proper solution as it removes the resource. Trying to set a manager after removing it results in the following error:

{
  "error": {
    "code": "Request_ResourceNotFound",
    "message": "Resource 'manager' does not exist or one of its queried reference-property objects are not present.",
    "innerError": {
      "request-id": "********-****-****-****-***********",
      "date": "****-**-**T**:**:**"
    }
  }
}

**Comment by davidmu1** [comment]
You used the correct API. No change identified for the page. Closing the issue.
