### ISSUE TITLE
How can I report an issue on the API itself not the doc ? :D (bug on managedDevice notes field)

### ISSUE THREAD

**Issue by julbrs** [microsoftgraph/microsoft-graph-docs#5811]
Hello

I am testing the managedDevice API via Graph Explorer and I notice one issue :

- the `notes` field is not correctly populated in the output (I have some devices with notes, but the field appears all the time `null` in the API)

The fun fact is that I am able to update the field via `PATCH` and I can see it is correctly populated on the Intune interface !

Thanks for your help !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eb0c676-e529-6680-2bbc-824914dd2de6
* Version Independent ID: be2cc5d1-ac43-950a-a304-fffd4fb7f39f
* Content: [Update managedDevice - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-update?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-devices-manageddevice-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-devices-manageddevice-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bobman38** [comment]
Hello

Let me know if it's not the appropriate medium for such issue !

Thanks,

**Comment by paulwetter** [comment]
Working with support, I found a solution.
```
Connect-MSGraph
$DeviceID = 'cdbdb5b1-43f8-4bdf-bce7-feef5cd1ab45'
$Resource = "deviceManagement/managedDevices('$DeviceID')"
$GraphApiVersion = "Beta"
$URI = "https://graph.microsoft.com/$graphApiVersion/$($resource)"
Invoke-MSGraphRequest -HttpMethod GET -Url $uri | Format-List deviceName,Notes
```
More details on my blog here: https://wetterssource.com/get-device-notes-from-graph
