### ISSUE TITLE
Unexpected behaviour if bucket is not specified

### ISSUE THREAD

**Issue by Katli95** [microsoftgraph/microsoft-graph-docs#5814]
If i submit an item without specifying a bucket the task is orphaned and cannot be viewed in the Web Application, this is highly unexpected. I would have expected a default bucket to have been selected or at least that the request had failed and the bucket parameter be made required. 

Is this expected behavior or am I doing something wrong?

Best regards
-Ketill

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33c5c966-fda0-a17d-9362-6466585ad2bf
* Version Independent ID: 93a1b1df-e030-a6d9-8e5f-fa5051fa7122
* Content: [Create plannerTask - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/planner-post-tasks?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/planner-post-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/planner-post-tasks.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rom-se** [comment]
I second this one.  Needs to have default bucket.
-RM

**Comment by joelhellman** [comment]
Agreed. To clarify, the task can be found if the user switched the board's view mode from Group by Bucket to something else, e.g. Group by Priority. 

If you open up the task details in the UI, a bucket is automatically set, so there already seems there is already some logic to determine default bucket.

**Comment by TarkanSevilmis** [comment]
The UI now shows unbucketed tasks.
