### ISSUE TITLE
Select prevents undeletion being detected as delta action

### ISSUE THREAD

**Issue by ross-currie** [microsoftgraph/microsoft-graph-docs#5821]
If you specify ?$select=id,displayName in your initial delta call, ongoing delta queries only return users who have had that value modifed. This is really cool.

However, in some testing it seems like this means that users will not be detected as undeleted as part of the delta action.

This makes sense to me, as the attribute for 'deleted' doesn't appear in my ?$select= call, so an undeletion doesn't count as a delta.

But I'm not sure you can include @reason in your ?select= call. I also tried deletiontimestamp, softdeletiontimestamp, and a few others.

Is there a particular attribute you can include in your select to ensure you capture undeletion events as part of the delta?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
@ross-currie , I tried to delta queries on the users collection:
`https://graph.microsoft.com/v1.0/users/delta?$select=id,displayName`
and
`https://graph.microsoft.com/v1.0/users/delta?$select=id,displayName,deletedDateTime`

both resulted in the user being returned in the delta query response, after they have been un-deleted (restored). Please let us know if you experience any further issues with this.

**Comment by ross-currie** [comment]
Thanks @piotrci - I've added a request to add deletedDateTime to the user properties page, as i couldn't find it documented anywhere.

But yes, further testing appears to indicate I was wrong - undeletions do get collected by the delta. I may have had some filtering on the data returned that prevented me seeing this before.
