### ISSUE TITLE
Wrong method used in Java example of Security API for listing alerts

### ISSUE THREAD

**Issue by Kars-de-Jong** [microsoftgraph/microsoft-graph-docs#5823]
In the Java example, it shows you should use the following method:

```java
            IAlertCollectionPage alerts = graphClient.security().alerts()
                    .buildRequest()
                    .get();
```

This is wrong, the `security()` method doesn't exist. It should be `Security()` instead.

By the way, Java convention is to start method names with lower case so the example is actually better than the actual implementation...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122ff9f6-5393-cb46-79d5-dac18a7131a8
* Version Independent ID: 150fb49f-a607-2297-b461-3979433a88c5
* Content: [List alerts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/alert-list?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/alert-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/alert-list.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@Kars-de-Jong Can you please share a screenshot of your code with the error when implementing this sample code? Thanks.
