### ISSUE TITLE
What about FolderIDs?

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#5825]
The EWS methods work fine for both Item and Folder IDs, and as far as I can tell so do the above examples when converting from entryId to EwsId. I cannot seem to convert to ImmutableIds though, are they only supported for items? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f87019e-ef7d-0125-b677-e573ddd93e9e
* Version Independent ID: a62ae14e-7205-c0fb-f742-15643c4ffa9c
* Content: [user: translateExchangeIds - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-translateexchangeids?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-translateexchangeids.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-translateexchangeids.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svpsiva** [comment]
Folders do not have immutable IDs. This is because the entry ID for a folder never changes so there is no need for an additional immutable ID.
