### ISSUE TITLE
Does not detail how to access subtask/steps on a task

### ISSUE THREAD

**Issue by matthewfcarlson** [microsoftgraph/microsoft-graph-docs#5829]
In microsoft todo, a task can have steps. I don't see a way to modify or list that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 269af1ad-db75-2d9d-fb59-5c834dee2863
* Version Independent ID: e21cb190-f4b6-2cb6-68d4-17cd8769b1ba
* Content: [outlookTask resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/outlooktask?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/outlooktask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/outlooktask.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @matthewfcarlson , thanks for the input! You're right, the to-do tasks API doesn't explicitly support sub-tasks. It would be worthwhile to see if there is already a request on [User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) and vote for it. If there isn't, please enter the request.  
Thank you!
