### ISSUE TITLE
Unable to addPassword

### ISSUE THREAD

**Issue by shyamkris** [microsoftgraph/microsoft-graph-docs#5830]
Hey Does the new way to call addPassword mentioned in https://developer.microsoft.com/en-us/graph/blogs/breaking-changes-application-and-serviceprincipal-api-updates-in-microsoft-graph-beta/ work yet?

**Comment by jthake-msft** [comment]
This repo issue list is for feedback on the docs. Not questions or troubleshooting. Can you please ask on stackoverflow.com with [microsoft-graph] tag? Thank you
