### ISSUE TITLE
Incorrectly auto generated page

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#5837]
Seems like this should not be generated by intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 597942ab-6d87-885d-aa4e-b8fb5e8e3cf3
* Version Independent ID: cb723b94-183e-5941-ec1f-6cd82adc57e9
* Content: [Get user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-shared-user-get?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/intune-shared-user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-shared-user-get.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @tfitzmac
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Engineering is aware of the issue and needs to rework tooling to make the change. Because this article will be automatically generated on each drop until the change is made, closing the issue for now.
