### ISSUE TITLE
refresh_token length in documentation

### ISSUE THREAD

**Issue by dwnz** [microsoftgraph/microsoft-graph-docs#5846]
Issue: It would be worth adding some details around how long the token and refresh token are, had issues refreshing the token as my database column wasn't big enough at first - should make it more clear

Article: https://docs.microsoft.com/en-nz/graph/auth-v2-user#5-use-the-refresh-token-to-get-a-new-access-token

**Comment by jthake-msft** [comment]
@davidmu1 do we document this anywhere in detail already? maybe in identity team.

**Comment by davidmu1** [comment]
I do not know of anywhere this is specified. Assigning to Jackson who is listed as the author of the referenced article. Ryan Wyke may also be able to help by adding information to the Access tokens conceptual article: https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens.

**Comment by psignoret** [comment]
Just to close the loop here on this super old issue: The length of access tokens and refresh tokens is unspecified.
