### ISSUE TITLE
Attachments are not supported in create event method.

### ISSUE THREAD

**Issue by subhanusharma** [microsoftgraph/microsoft-graph-docs#5847]
When we try to attach file attachments in create event method it throws an error that attachments are not supported. And if we create an event without attachments and after creating event add attachments then it automatically sends an invitation to attendees during the create event method and since the attachments were added later they are not reflected on attendees side.

**Comment by jthake-msft** [comment]
This repo issue list is for feedback on the docs. Not questions or troubleshooting. Can you please ask on stackoverflow.com with [microsoft-graph] tag? Thank you
