### ISSUE TITLE
Error 423 while trying to create new event

### ISSUE THREAD

**Issue by agatap2** [microsoftgraph/microsoft-graph-docs#5849]
Issue: When I try create new event I receive error 423, which means that resource that is being accessed is locked, but when I try to create new event via Graph Explorer there is no such problem. I have Calendars.ReadWrite permission added. What can be the reason of such error? How to check what resource is locked, and how to unclock it?

E/global: CoreHttpProvider[sendRequestInternal] - 423Error during http request
E/global: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request

Article: Create Event

[microsoftgraph]

**Comment by agatap2** [comment]
> Issue: When I try create new event I receive error 423, which means that resource that is being accessed is locked, but when I try to create new event via Graph Explorer there is no such problem. I have Calendars.ReadWrite permission added. What can be the reason of such error? How to check what resource is locked, and how to unclock it?
> 
> E/global: CoreHttpProvider[sendRequestInternal] - 423Error during http request
> E/global: Throwable detail: com.microsoft.graph.core.ClientException: Error during http request
> 
> Article: Create Event

**Comment by jthake-msft** [comment]
This is not feedback on docs content which is what this issue list is for. 

Can you please ask this question on stackoverflow.com using [microsoft-graph] tag.

**Comment by agatap2** [comment]
https://stackoverflow.com/questions/58180809/error-423-while-trying-to-create-new-event#58180809
