### ISSUE TITLE
Graph mail API returns 504 gateway timeout

### ISSUE THREAD

**Issue by erickbp** [microsoftgraph/microsoft-graph-docs#5853]
Issue:

I can reproduce this all the time for a couple of mailboxes.
If I change the $top to 100 it works fine for mailbox X but not for Y.

https://graph.microsoft.com/v1.0/users/[USER_ID]/messages?$select=id,receivedDateTime,parentFolderId&$filter=receivedDateTime+gt+2016-12-29T18:46:48.0000000Z&$orderby=receivedDateTime+asc&$top=300

{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "638c6bf4-3a36-49f1-b2e2-5a775a18f69d",
      "date": "2019-10-01T12:51:43"
    }
  }
}

Even with $top=1 I can see the problem for a mailbox (different search parameters)

https://graph.microsoft.com/v1.0/users/[USER_ID]/messages?$select=id,receivedDateTime&$filter=receivedDateTime+ge+2016-09-13+and+receivedDateTime+lt+2019-09-14&$orderby=receivedDateTime+asc&$skip=25651&$top=1

{
  "error": {
	"code": "UnknownError",
	"message": "",
	"innerError": {
	  "request-id": "1ea27a29-5491-44d2-824a-0aaee9280c40",
	  "date": "2019-09-13T19:48:30"
	}
  }
}

Article:

**Comment by svpsiva** [comment]
Can you reproduce the error and share the request-id here? We can then investigate the specific issue at play.

**Comment by erickbp** [comment]
Hi @svpsiva the first request-id above is from 3 days ago. Can you use that one? if not then I can send a new one... the issue happens every time I try. Thanks

**Comment by svpsiva** [comment]
Ok. We will investigate.

**Comment by erickbp** [comment]
@svpsiva here you have another example, this issue can be reproduced with several of our accounts and different queries. Thanks 

https://graph.microsoft.com/v1.0/users/[USER ID]/messages/?$select=id,receivedDateTime,parentFolderId&$top=1000&$skip=233812

HTTP status 504 Gateway Timeout

{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "9c810616-2635-49bc-8faa-351803e3d084",
      "date": "2019-10-07T16:44:56"
    }
  }
}

**Comment by ThorgalAegirsson** [comment]
I encountered the same issue. 504 error while trying to get all messages. After a thorough inspection I figured that in our case the problem was draft items. After adding filter **"isDraft eq false"** 504 stopped and we're getting all messages. It seems some drafts are broken. They won't show up in OWA or Outlook. In our case the one that was messing with the query was stored under parentFolderId that was non-existent, which is a huge problem in and of itself in my opinion.

**Comment by erickbp** [comment]
@ThorgalAegirsson  thanks for your reply. It solved it for some accounts. Thanks

**Comment by gregory** [comment]
Having the same issue even though we are filtering out the drafts :( - @ThorgalAegirsson  how were you able to pull the message to figure out it was missing the parentFolderId ? 

```
➜  curl -vv -H "Authorization: $H" https://graph.microsoft.com/beta/me/messages\?%24filter\=isDraft+eq+false+and+lastModifiedDateTime+lt+2020-02-03T15%3A54%3A49Z\&%24orderby\=lastModifiedDateTime+desc\&%24skip\=34\&%24top\=1
*   Trying 20.190.132.119...
* TCP_NODELAY set
* Connected to graph.microsoft.com (20.190.132.119) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=graph.microsoft.com
*  start date: Jul  1 21:55:17 2020 GMT
*  expire date: Jul  1 21:55:17 2022 GMT
*  subjectAltName: host "graph.microsoft.com" matched cert's "graph.microsoft.com"
*  issuer: C=US; ST=Washington; L=Redmond; O=Microsoft Corporation; OU=Microsoft IT; CN=Microsoft IT TLS CA 2
*  SSL certificate verify ok.
> GET /beta/me/messages?%24filter=isDraft+eq+false+and+lastModifiedDateTime+lt+2020-02-03T15%3A54%3A49Z&%24orderby=lastModifiedDateTime+desc&%24skip=34&%24top=1 HTTP/1.1
> Host: graph.microsoft.com
> User-Agent: curl/7.64.1
> Accept: */*
> Authorization: Bearer <TOKEN>
>
< HTTP/1.1 503 Service Unavailable
< Cache-Control: private
< Content-Type: application/json
< request-id: fe488121-fda3-439e-a059-435630a710a7
< client-request-id: fe488121-fda3-439e-a059-435630a710a7
< x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West US","Slice":"SliceC","Ring":"5","ScaleUnit":"003","RoleInstance":"AGSFE_IN_37"}}
< Strict-Transport-Security: max-age=31536000
< Date: Fri, 17 Jul 2020 17:30:42 GMT
< Content-Length: 198
<
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-07-17T17:30:42",
      "request-id": "fe488121-fda3-439e-a059-435630a710a7"
    }
  }
* Connection #0 to host graph.microsoft.com left intact
}* Closing connection 0
```

**Comment by corytheboyd** [comment]
@abheek-das @svpsiva Any updates on this? I am receiving the same error against the events delta API. We have recorded numerous `UnknownError` responses with both 503 and 504 response codes. Here are a few request IDs:
* `503`: `606b554d-84af-4036-b3b5-3306dbea70c0 `
* `504`: `daf42149-6332-415e-9f68-fcb460eedd0c`
* `504`: `66ab38a0-dc4d-445f-ab07-5a8046df5b5a `

**Comment by ThorgalAegirsson** [comment]
@gregory @corytheboyd  The way I found the message causing problem was a bit convoluted. Basically I tried to narrow down at what point I get the error, by date. I found that it was between two not distant dates, between which in theory there shouldn't be any messages. Then I used Graph Explorer to pull everything from between those dates and it did show up there.
That is the very rough process I used but there was some experimentation on Graph Explorer side as well. It wasn't so simple. I can't recall the details of what I used there, to be honest. I tried various functions to get to the message. Possibly I used beta version of API as well. Unfortunately it was a while ago and my memory is not as good as I'd like :) Sorry I couldn't be of more help.

**Comment by corytheboyd** [comment]
> @gregory @corytheboyd The way I found the message causing problem was a bit convoluted. Basically I tried to narrow down at what point I get the error, by date. I found that it was between two not distant dates, between which in theory there shouldn't be any messages. Then I used Graph Explorer to pull everything from between those dates and it did show up there.
> That is the very rough process I used but there was some experimentation on Graph Explorer side as well. It wasn't so simple. I can't recall the details of what I used there, to be honest. I tried various functions to get to the message. Possibly I used beta version of API as well. Unfortunately it was a while ago and my memory is not as good as I'd like :) Sorry I couldn't be of more help.

No worries, you're a champ for reporting back at at all after so much time!

**Comment by corytheboyd-groove** [comment]
@karanamkc Hey! Any updates on this issue? I have a vast number of request IDs exhibiting this issue still, will throw a few out here (taken from the `innerError` recorded by our monitoring tools):

```
{
client-request-id: ef78b4f4-68f1-4e84-be41-339be30de375, 
date: 2020-11-09T20:29:00, 
request-id: 47622dfd-17d6-4551-aa09-07effb077699
}
```

```
{
client-request-id: ded01ff7-ab46-41ef-ae3d-4c765919b37b, 
date: 2020-11-09T20:28:15, 
request-id: 78b241a4-50ee-4df9-aadd-f739d3c9f017
}
// this one included a message as well, which is:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Service Unavailable</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Service Unavailable</h2>
<hr><p>HTTP Error 503. The service is unavailable.</p>
</BODY></HTML>
```

```
{
client-request-id: 9b5c4da1-2ee1-4a8c-9f75-9f073671fe8b, 
date: 2020-11-09T20:22:48, 
request-id: d76d6ca4-9b31-4778-bee8-68f18e41a329
}
```

```
{
client-request-id: b371b84b-7cb6-459d-b460-a0d7b396d9aa, 
date: 2020-11-09T20:18:12, 
request-id: f5be9e92-f649-4698-bdd3-6902104062b0
}
```

```
{
client-request-id: 226fc1d8-3503-49aa-9d44-96066ceae3f8, 
date: 2020-11-09T20:01:07, 
request-id: 5f5cb4c8-4d3b-49c8-8f8e-c3e825e64261
}
```

All errors error are from distinct tenants in our application. The response code flips between 503/504 but it's always one or the other. I'm guessing some service on the Microsoft side is overloaded with work, but it's really frustrating not being told what to do and instead receiving 5xx responses.

Whatever I can do to help resolve this, I am willing to do, but we need to start somewhere better than a 5xx.

**Comment by Ceetrox** [comment]
same here... need help on that....

**Comment by profsmallpine** [comment]
@karanamkc Are you still monitoring this thread? This is happening for us as well on a handful of accounts. It can be retried consistently to see the error exhibited. I tried added  `isDraft eq false`, and I was able to iterate for a bit longer than previously (skipping 152 vs 83).

```
{"error":{"code":"UnknownError","message":"","innerError":{"date":"2021-06-02T20:56:17","request-id":"b3c479b3-b838-4d86-995e-9e0a1e09c888","client-request-id":"b3c479b3-b838-4d86-995e-9e0a1e09c888"}}}
```

```
{"error":{"code":"UnknownError","message":"","innerError":{"date":"2021-06-02T20:44:41","request-id":"5da153c9-9236-498f-be55-663845bb2ac2","client-request-id":"5da153c9-9236-498f-be55-663845bb2ac2"}}}
```

**Comment by profsmallpine** [comment]
I ended up using $select to only grab the fields that were needed. I also played with page size ($top) and was able to fix this issue in my use case. This would imply that the request was taking too long and microsoft was cancelling it, leading to a gateway timeout error.

**Comment by karanamkc** [comment]
@profsmallpine Can you please share the latest request-id for which the error was seen so that we can investigate further?

**Comment by piskvorky** [comment]
We're getting 504 too:

```json
{'error': {'code': 'UnknownError', 'message': '', 'innerError': {'date': '2021-06-03T21:41:19', 'request-id': 'ac72d201-7720-4c8a-b133-b5ece0fc7104', 'client-request-id': 'ac72d201-7720-4c8a-b133-b5ece0fc7104'}}}
```

**Comment by CLG-Brainstorm** [comment]
I am getting constant 504 Gateway Timeout when adding rows to an Excel worksheet:

`POST https://graph.microsoft.com/v1.0/me/drive/items/01FQ7BMAC6W2LGBN2L6REZLAD5U24NWNSD/workbook/worksheets/%7B00000000-0001-0000-0000-000000000000%7D/tables/%7B6652F94E-22EF-45E5-B201-6644B5460F91%7D/rows/add` resulted in a `504 Gateway Timeout` response:
{"error":{"code":"UnknownError","message":"","innerError":{"date":"2021-10-05T10:26:29","request-id":"ddfef0b4-3c41-4cb1 (truncated...)`

every other Graph call works fine - a sheet is generated with PHPSpreadsheet and uploaded to Onedrive, then the Excel session is opened and table created, only the row adding fails and whats more it works fine around 3am UK time just not during the daytime.

I've added retry logic so it attempts each block of 500 rows 5 times with a 3-second pause in between, but it gives the same response every time

**Comment by CLG-Brainstorm** [comment]
Sometimes it varies with:

`POST https://graph.microsoft.com/v1.0/me/drive/items/01FQ7BMAC6W2LGBN2L6REZLAD5U24NWNSD/workbook/worksheets/%7B00000000-0001-0000-0000-000000000000%7D/tables/%7B6652F94E-22EF-45E5-B201-6644B5460F91%7D/rows/add` resulted in a `401 Unauthorized` response:
{"error":{"code":"InvalidAuthenticationToken","message":"Access token has expired or is not yet valid.","innerError":{"d (truncated...)`

instead

**Comment by piskvorky** [comment]
All requested information was already provided, Mr. Silly Pants bot.
