### ISSUE TITLE
List privilegedRoles return 500 internal server error

### ISSUE THREAD

**Issue by azurestreet** [microsoftgraph/microsoft-graph-docs#586]
Server returned HTTP response code: 500 for URL: "GET" https://graph.microsoft.com/beta/privilegedRoles

**Comment by marych** [comment]
@azurestreet - thanks for reporting the issue. It was caused by a regression that is now reverted.

**Comment by azurestreet** [comment]
Now I got 403 for access this resource, but my AZURE AD settings are permit everything, is anything wrong for the settings?

![graph_permission](https://cloud.githubusercontent.com/assets/8710517/19884689/edde4056-a055-11e6-9a8e-f8bf9010495b.png)

**Comment by azurestreet** [comment]
@marych - Any update for this issue??

**Comment by marych** [comment]
@azurestreet - your tenant needs to have the Azure AD Privileged Identity Management (PIM) configured for this API to work. You can check the sign up status via https://graph.microsoft.com/beta/privilegedSignupStatus. Please follow https://docs.microsoft.com/en-us/azure/active-directory/active-directory-privileged-identity-management-getting-started to get PIM enabled for your tenant.
