### ISSUE TITLE
 Invalid expression term '['

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/microsoft-graph-docs#5861]
I get Invalid expression term '['	for the 2 dictionary objects of "AdditionalData "
AdditionalData = new Dictionary&lt;string, object&gt;()
	{
		{"members@odata.bind",["https://graph.microsoft.com/v1.0/users/ff7cb387-6688-423c-8188-3da9532a73cc","https://graph.microsoft.com/v1.0/users/69456242-0067-49d3-ba96-9de6f2728e14"]},
		{"owners@odata.bind",["https://graph.microsoft.com/v1.0/users/26be1845-4119-4801-a799-aea79d09f1a2"]}
	}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mrvaghani** [comment]
Looks like invalid JSON. Shouldn't it be:

```
{
"owners@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/26be1845-4119-4801-a799-aea79d09f1a2"
  ],
  "members@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/ff7cb387-6688-423c-8188-3da9532a73cc",
    "https://graph.microsoft.com/v1.0/users/69456242-0067-49d3-ba96-9de6f2728e14"
  ]
}
```

**Comment by Ofer-Gal** [comment]
This is not Dictionary<string, object> like the type needs.
I created actual arrays and it works. 
Just that the example is wrong

**Comment by davidmu1** [comment]
This looks like it has been corrected. No change identified for the page. Closing the issue.
