### ISSUE TITLE
Filter on List memberOf

### ISSUE THREAD

**Issue by kurniaga** [microsoftgraph/microsoft-graph-docs#5864]
Hi,

Do you have any plan to implement $filter on List memberOf (https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http)?

Thanks,

Alep 

Issue:

Article:

**Comment by jthake-msft** [comment]
There is nothing planned. Could you please put a request here https://microsoftgraph.uservoice.com so we can track this please?
