### ISSUE TITLE
Guidance on how to access directory extensions properties from the Graph API

### ISSUE THREAD

**Issue by mderriey** [microsoftgraph/microsoft-graph-docs#5865]
The [Azure AD directory schema extensions](https://docs.microsoft.com/en-us/graph/extensibility-overview?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#azure-ad-directory-schema-extensions) section mentions (emphasis mine)

> Azure AD supports a similar type of extension, known as directory schema extensions, on a few directoryObject resources. Although you have to use the Azure AD Graph API to create and manage the definitions of directory schema extensions, **you can use the Microsoft Graph API to add, get, update and delete data in the properties of these extensions**.

Would you be able to provide guidance as to how to access data of directory schema extensions through the Graph API? I wasn't able to find an endpoint in the API reference.

We're using directory schema extensions in our tenant as we have automation based on the `AzureAD` PowerShell module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fbbb2e0-38fb-fb9a-da33-138c09262fbd
* Version Independent ID: 583af78a-8160-e4d3-9710-998b6e6f13f1
* Content: [Add custom data to resources using extensions - Microsoft Graph](https://docs.microsoft.com/en-us/graph/extensibility-overview?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#azure-ad-directory-schema-extensions)
* Content Source: [concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/extensibility-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@mderriey Sorry for the late response.  It's essentially just like Azure AD Graph, but using Microsoft Graph's service endpoint.  When you create/update an object (say a user), you just include the property and its value in the payload.  In this case it's the ugly extension_{appId}_{name} property.  So something like:

```
PATCH ../users/{id}
Content-Type: application/json
{
  "extension_{appId}_{name}": "value"
}
```

For filtering...
GET ../users?$filter=extension_{appId}_{name} eq 'value`

NOTE:  things like users in v1.0 only return a default set of properties.  To see extension properties you would need to use $select.

**Comment by mderriey** [comment]
Fantastic, thanks a lot for your reply.
