### ISSUE TITLE
Missing deletedDateTime from Properties

### ISSUE THREAD

**Issue by ross-currie** [microsoftgraph/microsoft-graph-docs#5866]
A response to [another issue](https://github.com/microsoftgraph/microsoft-graph-docs/issues/5821) I raised mentions the "deletedDateTime" attribute, which is selectable but not present in the above schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ross-currie** [comment]
Sorry, should probably clarify "selectable" a bit.

If the user is not deleted, /users/{id}?$select=Id,deletedDateTime returns "deletedDateTime: null" in the JSON - this is expected, but also distinct to the attribute not existing. Eg, if I select SoftDeletionTimeStamp or DeletionTimeStamp, which is how this attribute is represented in MSOL/AzureAD PS cmdlets respectively, I just get nothing back for that attribute 

If you delete the user then call /directory/deletedItems/{id}?$select=Id,deletedDateTime, then you get an actual ISO 8601 datetime value back. Eg, "deletedDateTime": "2019-10-03T04:57:20Z"

So, my feeling is that the deletedDateTime property should be added to this page (and possibly also mentioned in the deleted items pages)

**Comment by davidmu1** [comment]
The deletedDateTime property is currently defined on the page. Closing the issue.
