### ISSUE TITLE
Group drive root children is failing for some tenants

### ISSUE THREAD

**Issue by figgsoftware** [microsoftgraph/microsoft-graph-docs#587]
Calling GET https://graph.microsoft.com/v1.0/drives/b!Dt2kEgTITUWJLxbcXQAGxu4NnyTZPfBKr8CoNLJbYXvEx6AUcs96Q5yTrxDCF2xY/root/children?$filter=name+eq+'Meetings'

Getting this in return (even thought he user is correctly authenticated and can reach that object from the UI.... the strange thing is that it works fine for an admin user....permission scopes have been set):

{
  "error": {
    "code": "unauthenticated",
    "message": "Access denied. You do not have permission to perform this action or access this resource.",
    "innerError": {
      "request-id": "2038310f-0b6d-4bcc-bd8f-18aa51bb3136",
      "date": "2016-10-31T13:32:14"
    }
  }
}

**Comment by marych** [comment]
@figgsoftware - your access token had Files.ReadWrite delegated permission scope, which only allows the calling app to access the signed-in user's files. Please configure Files.Read.All permission to be able to access all files the signed-in user can access. See https://graph.microsoft.io/en-us/docs/authorization/permission_scopes for the list of permission scopes.

**Comment by rgregg** [comment]
Was the user where you're hitting this error already consented to your application? Adding permissions to your app configuration doesn't automatically add those permissions to existing users. They need to be forced back through the consent flow by adding `&prompt=consent` to the authorization flow.

**Comment by katahir** [comment]
Hi figgsoftware,
This is a known issue with the api. The api checks for permissions against the tenant root site collection in addition to your target site. While we fix the bug, you can work around it by adding yourself as a reader on the tenant root site collection. Please let me know if you still get a 401.

**Comment by isvargasmsft** [comment]
Hello!

My deepest apologies for the delays in this issue. 

Thank you very much for bringing this into our attention. I checked with the OneDrive team and the fix is being worked internally and will be deployed once ready. We don't have an ETA unfortunately. 

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).
