### ISSUE TITLE
Please provide a way to Add/Update Peoplepicker field using Microsoft Graph

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/microsoft-graph-docs#5875]
Please provide a way to update Peoplepicker field using Microsoft Graph.
If we get a sample example for all different types of supported SharePoint ListItem field for CRUD Operation using Microsoft Graph it will be very helpful to us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec4e338a-772e-0fc8-cff2-14d5a2f0d173
* Version Independent ID: 01362b8b-5f0b-4a40-d21f-0d27012c7311
* Content: [Update listItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitem-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitem-update.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by anomepani** [comment]
@JeremyKelley  Is there any updates on this.

**Comment by anomepani** [comment]
Hello @jthake-msft and @darrelmiller Can some help me on provide a way to any insight on this. 
SharePoint List Item creation supported but a most useful and real-world scenarios like DateTime, Hyperlink, PeoplePicker, Taxonomy etc field supported or not if yes then If any demo or detail blog or article available then it will help.

Thanks in advance.

**Comment by Office365Master** [comment]
I did manage to get this working with  DateTime, Choice, Yes/No and RichText field types, but as yet not with Hyperlink, PeoplePicker or Taxonomy field types. 

By way of example (field types self-explanatory), the fieldValueSet in the Request Body being: 
{"My_x0020_Date":"2019-10-14T02:00:00","Choice_x0020_Test":"Cricket","Yes_x0020_No_x0020_Testing_x0020":"false","Rich_x0020_Text":"<p>Rich Text Field Demo</p><p><a href=\"https://masteroffice365.com\">How about this?</a></p>"}

I suspect with complex field types such as Hyperlink and Taxonomy it may be a question of escaping some of the characters in the value set for those field type, given the syntax I used to update a Rich Text field definitely works.

**Comment by anomepani** [comment]
Thanks @office365master. Yes for some basic column type is working  and thanks for richtext demo I didn't tried yet. But for people picker, taxonomy, lookup column I am not sure how it works with graph api

**Comment by Office365Master** [comment]
"Rich_x0020_Text":"<p>Rich Text Field Demo</p><p><a href=\"https://masteroffice365.com\">How about this?</a></p>"

Minor correction for the sample syntax for richtext field type. Somehow lost the escape character that needs to be there after href= 🤔

**Comment by Office365Master** [comment]
Seemingly when replying on this thread it keeps dropping it so watch out for that...

**Comment by darrelmiller** [comment]
Hey @anomepani , sorry, but I've never used this API before However, what I would recommend is using Sharepoint to add a list item with the columns that you are interested in and then retrieve that data via the API.  That should give you an idea of how the data is represented in JSON.  From that we can maybe figure out how to add an item with those column data types.

**Comment by ilinkc611** [comment]
How to insert sharepoint list people picker column using rest api? Please help on this?

import {PeoplePicker} from '@microsoft/mgt-react';

<PeoplePicker selectionMode={"single"} selectionChanged={this.handleSelectionChanged}  showMax={1}></PeoplePicker>
Sharepoint People picker column name "AssignedTo"

   listItem = {
        fields: {
          Title: Title,
          **"AssignedTo@odata.type": "Edm.Int32",
          AssignedTo:11**
        }
      };

let listitems = await Providers.globalProvider.graph.api("/sites/{" + this.siteID + "}/lists/{" + this.SPListID + "}/items").post(listItem);
