### ISSUE TITLE
Access libraries in site collections

### ISSUE THREAD

**Issue by DavidLozzi** [microsoftgraph/microsoft-graph-docs#588]
I can find all the libraries in my root site collection, name.sharepoint.com/ by using https://graph.microsoft.com/v1.0/drives but I'm not finding any libraries from my other site collections, i.e. name.sharepoint.com/sites/lozzi.

**Comment by marych** [comment]
https://graph.microsoft.com/beta/sharePoint:/lozzi should return your non-default site. Please note that the SharePoint Sites API is only available on /beta right now. See https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/sharepoint for more details.

**Comment by DavidLozzi** [comment]
Perfect! https://graph.microsoft.com/beta/sharepoint:/sites/lozzi worked!
