### ISSUE TITLE
Can OData Query Parameters add any additional properties?

### ISSUE THREAD

**Issue by WyattBest** [microsoftgraph/microsoft-graph-docs#5882]
Can OData query parameters add any properties to the response, or only exclude them? "Help customize the response" is a bit vague.

I tried adding `isArchived` and failed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcab0a3-a255-5b3d-82d5-32151073d238
* Version Independent ID: cf41c6fc-448b-9e0e-a806-7eac97bf4e1a
* Content: [List classes - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/educationroot-list-classes?view=graph-rest-1.0&tabs=http#response)
* Content Source: [api-reference/v1.0/api/educationroot-list-classes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/educationroot-list-classes.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmast-msft** [comment]
OData query parameters cannot add properties.  If you are trying figure out if a Class has been archived, that is unfortunately not surfaced in the EDU API.   It seems the the only way to get that is on the Beta endpoint: /beta/teams/{teamId}
