### ISSUE TITLE
Valid Email Format

### ISSUE THREAD

**Issue by deisterhold** [microsoftgraph/microsoft-graph-docs#5883]
What's the allowed format for characters in email addresses? Is there an API I can use to valid email addresses? When trying to use an email address of the format "user+tag@gmail.com" I get an exception saying "The Primary SMTP Address is an invalid value".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0170d-e214-ce6f-b7b4-589960e9962d
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/invitation.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mrvaghani** [comment]
As per the article I found [HERE](https://answers.microsoft.com/en-us/outlook_com/forum/all/outlookcom-address-name-format/93ef4e1e-b055-4652-9a68-20b6643b1d92), you can start your verification with something like this:

```
Your email address can contain only letters, numbers, periods (.), hyphens (-), and underscores (_). It can't contain special characters, accented letters, or letters outside the Latin alphabet.
```

**Comment by EpicPilgrim** [comment]
This is a shame. RFC5322 specifies that other characters such as pluses (+) should be allowed in the local part of an e-mail address. Trying to add guests to our O365 tenant who have plus signs in their e-mail addresses fails.

**Comment by davidmu1** [comment]
Added a list of the characters that aren't allowed.

**Comment by EpicPilgrim** [comment]
> Added a list of the characters that aren't allowed.

I'm not sure that this is a solution? You're fundamentally saying that sure, the standard says one thing, but you accept you're not going to ever meet that standard?

**Comment by dewaynedennis** [comment]
Just curious about this list of "special characters are not permitted in the email address" for the invitedUserEmailAddress property. I see that "At sign (@)" is in there. Is that a typo? (I don't know any email addresses without an @)
