### ISSUE TITLE
Typo and permissions suggestion (based on support feedback)

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#5887]
1. The HTTP request example has a header with a spurious quote mark:
Host: graph.microsoft.com`
2. I think the think that often gets lost (according to support) is how delegated and app permissions relate to the different access token (or token acquisition flows).  It would be good to say the delegated is used with most flows (like code, device, implicit, etc where a user interaction is involved) and application is used with client credentials flow.  You could point to the Microsoft identity platform topic on the supported scenario flows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99744fa1-3662-8ff5-646b-8be06d43b066
* Version Independent ID: bfc9d00c-c96f-afcc-bb8f-15c2d8601c3b
* Content: [Authentication and authorization basics for Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth/auth-concepts)
* Content Source: [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth/auth-concepts.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @matt-steele
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
A long time since this issue was raised but to provide feedback: the page has since been corrected and updated and includes more information on delegated vs application permissions.
