### ISSUE TITLE
Settings object only applicable for users with Exchange Online mailboxes?

### ISSUE THREAD

**Issue by cimares** [microsoftgraph/microsoft-graph-docs#5888]
When I attempt to get the User Settings object from the graph for users that exist in Office 365 but with on-prem mailboxes (in a Hybrid environment) I received a 404 - MailboxNotEnabledForRESTAPI.

    "error": {
        "code": "MailboxNotEnabledForRESTAPI",
        "message": "REST API is not yet supported for this mailbox.",
        "innerError": {
            "request-id": "080ffc52-c4e9-478f-9774-e8723d4a950e",
            "date": "2019-10-07T12:40:14"
        }
    }

If this call is only available for EXO mailboxes, that should be made clear in the documentation. (In this instance we're trying to configure the Delve discovery setting.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0acbb629-4115-c63a-8c97-878f58ea612e
* Version Independent ID: fc917f4f-99bc-1ff2-a378-091dc1ea5977
* Content: [settings resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user-settings?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/user-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user-settings.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Re-assigning.  This topic filename has been renamed.  It's here: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/usersettings.md

**Comment by simonhult** [comment]
I believe that this was verified as resolved on Nov 4, 2019. Please reopen if you are still experiencing this problem.
