### ISSUE TITLE
Posting a message with an image

### ISSUE THREAD

**Issue by unk1911** [microsoftgraph/microsoft-graph-docs#5891]
Is it possible to post a message to Teams that contains a JPG image (without going into creating a Bot and creating a Hero Card, etc)?  I tried various things such as using the &lt;img src=''/&gt; tag.  The only thing that works is if I publish my .jpg image on an external world-readable website and include a reference to it in the &lt;img src&gt;, however, this is not a practical solution since the image I'm posting should only be viewable by members of my group.   I have tried saving this image on my OneDrive and then granting access to only those people in my domain to access it, then generated a link,  however when I include this link in the &lt;img src='https://mycompnayname-my.sharepoint.com/:i:/g/personal/webpublisher_mycompnay_com/AKJDFLKADFKLJAzzkjz933kjz93kj33lkj3933kljz93Nw?e=HPrYRH'/&gt; tag, it doesn't work either... Any ideas on how to make this work? It seems like having to create a Bot is overkill for such a simple task as posting a small message to Teams containing an image..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
SharePoint images require Auth. Only unauthenticated images can be attached to an image.

**Comment by unk1911** [comment]
Yes,  I have noticed that indeed it requires SSO/authentication,  but you would think if the user is already logged in into Teams they are already authenticated, and if a link is being shared with them and the permissions are set to permit the user to view the image, then why wouldn't it automatically work?

**Comment by RamjotSingh** [comment]
Teams does not send any authentication header over for inline images.

**Comment by dennisylyung** [comment]
Are there any suggested workaround?
Currently the teams graph API does not support attachments, and inline messages cannot reference a authenticated image, so there seem to be no way to post an image using API to teams (except developing a bot).

**Comment by RamjotSingh** [comment]
If unauthenticated source is a possibility you can upload images to one such source and use that.

**Comment by unk1911** [comment]
> If unauthenticated source is a possibility you can upload images to one such source and use that.

that is exactly how i implemented it, but seems like a hack...

**Comment by umutge** [comment]
I believe supporting issue can be remediated if API supports multipart/form-data HTML page upload, so that inline images can be inserted in HTML code.
