### ISSUE TITLE
Example response is borderline useless

### ISSUE THREAD

**Issue by davehax** [microsoftgraph/microsoft-graph-docs#5893]
The example response is borderline useless

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9b92830-bd9d-61db-7d2e-9ac356984332
* Version Independent ID: ecb93554-a5a3-d937-f0e4-4a1c6d388218
* Content: [checkMemberGroups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-checkmembergroups?view=graph-rest-1.0&tabs=javascript)
* Content Source: [api-reference/v1.0/api/user-checkmembergroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-checkmembergroups.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Thank you for your feedback. No change identified for the page. Closing the issue.
