### ISSUE TITLE
Can't complete the instructions for the "To associate an existing Azure subscription with your Office 365 account"

### ISSUE THREAD

**Issue by justingden** [microsoftgraph/microsoft-graph-docs#5896]
I have logged in to and explored around the Azure Portal and can't find anything resembling the instructions in this section. I have gone through our Azure Active Directory resource over and over. Is this instruction set for the old Manage portal and not the new portal? If not, can you clarify how to get to the "Active Directory" node?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01567ae-17e0-58ab-efaf-e7fa982bd1a7
* Version Independent ID: 80560253-edc6-166c-d67e-112f479ba7a8
* Content: [Associate your Office 365 account with Azure AD to create and manage apps - Microsoft Graph](https://docs.microsoft.com/en-us/graph/associate-account#feedback)
* Content Source: [concepts/associate-account.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/associate-account.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The associate-account.md article no longer exists. I think this might be the information you are looking for: https://docs.microsoft.com/en-us/office365/enterprise/azure-integration. Closing the issue.
