### ISSUE TITLE
Combining $select with $expand not possible

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/microsoft-graph-docs#5900]
This documentation could use some improvements about combining the `$select` and `$expand` parameters. On the [Known Issues](https://docs.microsoft.com/en-us/graph/known-issues?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#query-parameter-limitations) page there is an entire section about Query parameters. That part should be on the query parameters page as well.

Apart from that I think a lot of applications would profit from the ability to combine `$expand` and `$select`. One example is the use of `singleValueExtendedProperties`, if you want any of those returned you'll need to expand it, but expanding means you cannot do a select. Resulting in getting all the data and the singleValueExtendedProperties (= way more data), instead of just the properties you want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @svrooij 
Thanks for bringing this to our attention, I just submitted a PR to address it.
