### ISSUE TITLE
Graph API Reports no longer returning All Rows in CSV

### ISSUE THREAD

**Issue by TheITRx** [microsoftgraph/microsoft-graph-docs#5905]
Link: https://graph.microsoft.com/v1.0/reports/{Report Root}(period='D180')

E.g.
https://graph.microsoft.com/v1.0/reports/getEmailActivityUserDetail(period='D180')

I normally won't have to do pagination for that report root - it spits out all users with all the information in the report in CSV format. Just a minute ago, my request only gives me 100 rows. 

Tried it on both Powershell and PostMan. Any changes recently?

This is happening on User Detail Reports.

**Comment by ziaga** [comment]
we have the same issue. It's happening for all the office365 reports.

**Comment by SnappyFPV** [comment]
Please advise how to use the paging

**Comment by TheITRx** [comment]
> 
> 
> Please advise how to use the paging

http://bit.ly/33oVcJt
