### ISSUE TITLE
Filter by excluding ID's from the payload

### ISSUE THREAD

**Issue by martyn1111** [microsoftgraph/microsoft-graph-docs#5910]
I have a list of users id and I have to exclude a list of users id from the payload.  I have tried filtering by ID with eq logical operator i.e. $filter=id eq 'id1' or id eq 'id2' and it works nice and only retrieves the users within the ids "list". 
But what I want to have is the opposite to exclude those ids, something like this. 
$filter=id ne 'id1' and id ne 'id2' ..... but this error is shown when I try to use "ne" in the filter for users. "The 'id' property can only be used with the equals-match operator."
how could I perform this scenario? It would be nice a little help. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by piotrci** [comment]
Unfortunately that particular resource (users, and Azure Active Directory objects, in general) does not support this operator. we have plans to support more filtering operators in the future.
