### ISSUE TITLE
October 2019 changelog update teams photo gives Target address not found response

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#5915]
I was using the V1.0 endpoint of updating groups photo and somehow it was updating team photos also on the web portal of the teams but not the desktop version of teams. Now that they brought out only update teams photo (this Api above) it gives an error of target address not found. That makes me think if this API is ready yet to use. When I tried to get on the graph explorer, it works but as we know we can't do "put" request on the graph explorer with binary data. I had to try this with a dummy console app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8bf4e1-4d01-31d0-e09e-1e722e65dc8a
* Version Independent ID: 246c1de8-7ef1-4dc0-3812-80a982befd8c
* Content: [Update team photo - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-update-photo?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-update-photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-update-photo.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
I've been facing the same error when requesting 
PUT/PATCH https://graph.microsoft.com/beta/teams/{id}/photo

Here is what the response looks like:
{
  "error": {
    "code": "InternalServerError",
    "message": "Unable to find target address",
    "innerError": {
      "request-id": "09cf2dc4-b361-479b-b9e8-87e4766271ed",
      "date": "2019-10-24T12:36:52"
    }
  }
}

Unfortunately, there is no difference if I request the API using delegated or application permissions.

**Comment by ashoksubedi1** [comment]
Yeap, same here.

**Comment by TOPDHI** [comment]
Same here. This does not work. The only way is to use v1.0 group. Example in C#:

RestClient client = new RestClient("https://graph.microsoft.com/v1.0");
RestRequest request = Utils.GetGraphRestRequest(Method.PUT, string.Format("/groups('{0}')/photo/$value", groupId), delegatedToken);
byte[] fileAsBytes = System.IO.File.ReadAllBytes(System.Web.Hosting.HostingEnvironment.MapPath(filenamePath));
request.AddParameter("image/jpeg", fileAsBytes, ParameterType.RequestBody);
IRestResponse response = client.Execute(request);
if (response.StatusCode != System.Net.HttpStatusCode.OK)
   Log.WriteDetail("Logo set.");

**Comment by ashoksubedi1** [comment]
I was using that for Group's Pciture but would take a little longer to affect on group's team. It would change the pic of the planners too. I was excited that they had brought an api to change just teams pic, O well.

**Comment by ashoksubedi1** [comment]
Any updates on this. I still get Internal Server Error

**Comment by kevinbellinger** [comment]
I'll try to find someone to look at this. This should be hitting my API, but judging by the error I'm not sure it is.

**Comment by welante** [comment]
I still have the same error for the beta teams photo call. Updating the groups photo seems to work for now. But wondering when this issue will be fixed..

**Comment by ashoksubedi1** [comment]
Team pics are getting changed but the cache is irritating, every time I have to log out and log in to see if the teams pic actually got changed or not. Should not this api by pass the cache on the app?

**Comment by ashoksubedi1** [comment]
Hello Team any update ? Is there any plan taking this api to V1.0. Profile pics are changing but the due to cache its not displaying so either there should be button to clean the cache or have the api post profile pic by pass the cache

**Comment by Prithvi-MSFT** [comment]
Hi, Can you try changing profile using this Patch API mentioned here
https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http
https://graph.microsoft.com/v1.0/users/<userId>/photo/$value
