### ISSUE TITLE
List subscribedSkus does not support OData filter

### ISSUE THREAD

**Issue by rikkuness** [microsoftgraph/microsoft-graph-docs#5922]
The documentation suggests "This method supports the OData Query Parameters" however when attempting to use an OData filter the API responds with `Filtered searches against this resource are not supported.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb987c0-f783-4379-45fe-678c4b9e514f
* Version Independent ID: b625c2db-d6a2-8a18-88dc-fad7e76f9251
* Content: [List subscribedSkus - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/subscribedsku-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/subscribedsku-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/subscribedsku-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Revised the sentence to say that OData parameters are not supported.
