### ISSUE TITLE
Result set limit

### ISSUE THREAD

**Issue by crice88** [microsoftgraph/microsoft-graph-docs#5923]
When we query for more than 100 instances of a recurring event, it looks as though the server automatically pages the result set. Is there anyway we can get this behavior documented? 100 instances is a ballpark guess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1752e9b3-e39d-5589-4d6f-b0642ee13267
* Version Independent ID: cdb2bc7d-3d27-5cb5-c859-852e4dcc57bc
* Content: [List instances - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-list-instances?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-list-instances.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-list-instances.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
This has been reported 2 years back. We did a check and currently there is no limit on returning number of instances using /instances API now.
