### ISSUE TITLE
Show on Card

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#5924]
Is it possible to turn on the "Show on Card " for task details checklist and description using graph API while creating or updating?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b028fb35-808d-e08c-37ab-0845c0e5df18
* Version Independent ID: 64125169-a127-0f95-2763-a1afe1ee674f
* Content: [Update plannertaskdetails - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/plannertaskdetails-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/plannertaskdetails-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannertaskdetails-update.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by thesofakillers** [comment]
Are you hoping to show _both_ checklist and description on the card at the same time? If so this is not possible at the moment. You are not even able to do this by interacting with the task directly through Microsoft Teams, i.e. this isn't an API limitation, it just isn't a feature. 

(**note**: I don't work for microsoft, I don't know if they're planning to add more preview options to unopened cards).

You are however able to show these details orthogonally, if that is the question, i.e. either one or the other. Simply specify the `previewType` to `checklist` or `description` respectively in the plannerTaskDetails object that you send through a `PATCH` request.

**Comment by TarkanSevilmis** [comment]
The comment above is correct. If you'd like to see more than one item to be show on card, please report this feedback on [Planner User Voice](https://planner.uservoice.com/forums/330525-microsoft-planner-feedback-forum). It would help us understand and prioritize the request if you mention why you'd like to see more than one item in the user voice entry/comments.
