### ISSUE TITLE
Outlook resource filters should include more example

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#5926]
From the Outlook REST v2 endpoint docs you can do things like 
POST https://outlook.office.com/api/v2.0/me/subscriptions HTTP/1.1 
Content-Type: application/json 
 
{ 
  @odata.type:"#Microsoft.OutlookServices.PushSubscription", 
  Resource: "https://outlook.office.com/api/v2.0/me/mailfolders('Drafts')/messages?$filter=HasAttachments%20eq%20true%20AND%20Importance%20eq%20%27High%27", 
  NotificationURL: "https://mywebhook.azurewebsites.net/api/send/myNotifyClient", 
  ChangeType: "Created", 
  ClientState: "Has attachments and high importance" 
} 
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/notify-rest-operations#refine-notification-conditions

This is extremely useful to filtering to just get emails with attachments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
thanks for bringing this to our attention @jthake-msft 
Docs issues are... for issues in the docs.
Can I suggest you post to uservoice https://microsoftgraph.uservoice.com/ for any feature suggestion? Thanks!
Closing.

**Comment by baywet** [comment]
Make sure you upvote existing ideas!
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/33570451-add-filter-support-for-webhook-subscriptions
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/19081306-add-select-and-filter-to-webhook-resource-subs
