### ISSUE TITLE
Get plannerTask error response content has empty code for 404

### ISSUE THREAD

**Issue by djswilly** [microsoftgraph/microsoft-graph-docs#5928]
This means we can't implement error handling as recommended in this article. Example response:
{
  "error": {
    "code": "",
    "message": "The requested item is not found.",
    "innerError": {
      "request-id": "2af36f63-d245-4b24-a94e-0139bb0f9507",
      "date": "2019-10-11T03:19:52"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77cc3520-96d8-6aa4-1243-20b7f4d5c4cb
* Version Independent ID: 79a31ea9-d9b3-2602-e412-4959498a11c0
* Content: [Microsoft Graph error responses and resource types - Microsoft Graph](https://docs.microsoft.com/en-us/graph/errors)
* Content Source: [concepts/errors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/errors.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mthakare-onshape** [comment]
innerError gives out request-id, how to use it to further retrieve inner error?
