### ISSUE TITLE
Is there any way or Microsoft Graph API to hide teams for specific team owner?

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/microsoft-graph-docs#5929]
Currently, we have 1000s Microsoft teams and on a daily basis, 10 to 15 teams are created based on contract and in that special Security group's owners(Company Admin and Other Stakeholders) added as an owner for security reasons in groups.
As this owner is added to every team, their Teams app is too slow and unresponsive due to this all teams loaded in their app.

Is there any Microsoft Graph API or Powershell script available which runs for all teams and hide team for a specific user.
As Hide and UnHide Team feature is available but I didn't find any Graph API.
If you guys can help with this issue it is very helpful to us.
Thanks In Advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4f5720-3eb2-fe1d-472e-497d1449f97b
* Version Independent ID: eaa22434-4691-77e2-8905-bf6d7e9e0bef
* Content: [Microsoft Teams API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-concept-overview)
* Content Source: [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-concept-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
If there is, it would be a $filter on GET /groups
