### ISSUE TITLE
Adding Teams functionality to Group fails

### ISSUE THREAD

**Issue by EsaHeikkiPoutanen** [microsoftgraph/microsoft-graph-docs#5945]
in my Azure function (c#) I get Code: Request_BadRequest
Message: Specified HTTP method is not allowed for the request target.
when I'm using the above await graphClient.Groups["{id}"].Team
	.Request()
	.PutAsync(team);
with the just created group.

I've tried few other ways to do this but to no avail, how is this done properly ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by EsaHeikkiPoutanen** [comment]
After adding owner to my group (via Azure portal) and the trying the above I get:
Code: InvalidRequest
Message: Could not find member '@odata.type' on object of type 'TeamMemberSettings'. Path 'memberSettings['@odata.type']', line 1, position 66.,Could not find member '@odata.type' on object of type 'TeamMessagingSettings'. Path 'messagingSettings['@odata.type']', line 1, position 205.,Could not find member '@odata.type' on object of type 'TeamFunSettings'. Path 'funSettings['@odata.type']', line 1, position 329.,Could not find member '@odata.type' on object of type 'Team'. Path '['@odata.type']', line 1, position 384.

please advice.

**Comment by equalizer999** [comment]
@EsaHeikkiPoutanen; Please check last post on the following thread, there you'll find your answer; https://stackoverflow.com/questions/58420993/could-not-find-member-odata-type-on-object-of-type-teammembersettings

**Comment by EsaHeikkiPoutanen** [comment]
Got this working couple of weeks ago, with no help from this documentation.
current problem is:
await graphClient.Teams[myGroup.Id].Members.Request().GetAsync(); doesn't compile..
when will Members functionality be available for Teams ???

**Comment by anandab-gt** [comment]
@EsaHeikkiPoutanen - pls check https://docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http
