### ISSUE TITLE
does the group api only return o365 groups?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs#5947]
there are many kinds of groups in o365. the group api in microsoft graph can only see the o365 groups. am I right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c075526-0f30-ee18-0621-f0632ad59ac4
* Version Independent ID: d7cd062e-608c-b7d4-6963-6c437a2e3897
* Content: [Overview of Office 365 groups in Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/office365-groups-concept-overview#feedback)
* Content Source: [concepts/office365-groups-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/office365-groups-concept-overview.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
Get group API returns all the groups with all group types in Azure Active Directory.
