### ISSUE TITLE
Does every sharepoint sites belongs to only one group?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs#5948]
what is the relation between the two concepts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c075526-0f30-ee18-0621-f0632ad59ac4
* Version Independent ID: d7cd062e-608c-b7d4-6963-6c437a2e3897
* Content: [Overview of Office 365 groups in Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/office365-groups-concept-overview#feedback)
* Content Source: [concepts/office365-groups-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/office365-groups-concept-overview.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by derhallim** [comment]
Not all SharePoint sites belong to groups, and when they do, they belong to one group only. Communication sites don't belong to groups. You can also have Team sites without being connected to a group.

**Comment by landall** [comment]
> Not all SharePoint sites belong to groups, and when they do, they belong to one group only. Communication sites don't belong to groups. You can also have Team sites without being connected to a group.

Where can I find a document to get the exact relation about these things?

**Comment by derhallim** [comment]
@landall 

https://support.office.com/en-us/article/what-is-a-sharepoint-team-site-75545757-36c3-46a7-beed-0aaa74f0401e

Check the section: Integration with Office 365 groups in Sharepoint online.
