### ISSUE TITLE
Recurrence Exceptions

### ISSUE THREAD

**Issue by phillip-proulx** [microsoftgraph/microsoft-graph-docs#5951]
Does the Graph API support Recurrence Exceptions?

For example, I have a Weekly Recurrence Pattern that repeats every Tuesday from October 1st through December 1st. If I delete just the second Tuesday event in the month of October, how does the API correlate that information? 

I have tested this several times and can't seem to get this information pulled from the API. It will pull the original recurrence pattern but no exceptions.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc0466f-10cf-f53a-0eff-351f36288718
* Version Independent ID: 5d54df69-0ab6-0d86-4ae4-5bf51ea1426c
* Content: [recurrencePattern resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/recurrencepattern?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/recurrencepattern.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/recurrencepattern.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @sumurthy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by timothyhoffmann** [comment]
I'm having the same issue. If one deletes a single instance of a recurring meeting of a subscribed resource the Update event is sent pointing to the root event but there's no indication of what changed.

**Comment by phillip-proulx** [comment]
@sumurthy Any update on this?

Thanks!
