### ISSUE TITLE
Get organization return collection(organization), not organization

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs#5952]
this should be a document error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8453dc23-7ef7-8ee0-9342-4709ee532672
* Version Independent ID: 20aa3e3e-2f05-f307-fb36-2281cafc1cbf
* Content: [organization resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/organization.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
I don't understand the requested change. Both the resource page and the API page say that the return type is an organization collection. Closing the issue. It can be re-opened with more specific information about a needed change.

**Comment by landall** [comment]
I means it do not fit the naming rules which microsoft graph is using and it makes me confused about the result.
Just like the discussion in #3654 , I have not find a situation that a user belongs to more than one organization even when he is a guest of the other tenant. This API should be named as /organizations or it should return an only organization.
I have not seen #3654 before I submit this issue so I think they are duplicated.
