### ISSUE TITLE
Examples are missing valid {id} example values

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoftgraph/microsoft-graph-docs#5954]
What are the legal values for {id}?  e.g. User e-mail, Team group title, etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3bc78b-b078-5b95-6ae5-11551d1b852d
* Version Independent ID: fb69519b-3e4a-2279-cf1d-8e9c082fafd6
* Content: [Get team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-msft** [comment]
group id is the only legal value. 
Closing this issue, in case you feel this is not resolved either re-open the issue or create a new issue.
