### ISSUE TITLE
Can we use Team Creation and provisioning using template in production code?

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/microsoft-graph-docs#5961]
Can we use Team Creation and provisioning using the template in production code?
This looks very fast and manageable way to automates Team Provisioning.

Hello Microsoft Team, Do you recommend this endpoint for future Team Provisioning?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anomepani** [comment]
Hello team, @nkramer 
Can we use Microsoft Graph beta endpoints Teams API for production code for team provisioning app?

**Comment by anandab-gt** [comment]
@anomepani - beta APIs are not recommended for production application. Create team using template is available in v1 end point, you can use them in production.

**Comment by anomepani** [comment]
Wow.  I have asked questions one year before, at that time template api not available in v1.
Anyway thanks for update
