### ISSUE TITLE
Documentation on Group.Selected access permission

### ISSUE THREAD

**Issue by HansDahle** [microsoftgraph/microsoft-graph-docs#5962]
There is an application permission on Graph called Groups.Selected. This indicates through the portal that the app can ex. read files etc for a group. However there seems to be missing information on how to grant an app "selected" groups. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Known issue - docs are in process, this is just a temporary sync issue between docs and portal. Closing.
