### ISSUE TITLE
Updating the accountEnabled property for Windows devices only?

### ISSUE THREAD

**Issue by Malewhiskey** [microsoftgraph/microsoft-graph-docs#5968]
Updating the accountEnabled property of a registered device is inconsistent between the Microsoft Graph Explorer and my own powershell script. Using Microsoft Graph Explorer, I can update the accountEnabled property of an Android device. In my own program, the same request for the same Android device returns the following response content. I have tried the PATCH request using "v1.0" and "beta". The results are the same. 

{
  "error": {
    "code": "Request_BadRequest",
    "message": "Properties can only be modified on Windows devices.",
    "innerError": {
      "request-id": "c683b787-ec86-4f82-89a5-1bf65f95fa2e",
      "date": "2019-10-15T17:47:43"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2823c35-1b67-2d65-1585-0c6d6162ef8e
* Version Independent ID: c10ea5e9-24d2-910c-5c10-58cc2188fc1f
* Content: [Update device - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/device-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by silvanet123** [comment]
I am having the same issue updating a device. It seems that my update can be done via Graph Explorer manually, but not by Powershell scripts.

Here is my error if it helps you any.

{
 "error": {
    "code": "Request_BadRequest",
    "message": "Properties can only be modified on Windows devices.",
    "innerError": {
      "date": "2021-01-07T19:03:13",
      "request-id": "dd1c5564-c04e-4f07-bbb6-6eda05579f82",
      "client-request-id": "dd1c5564-c04e-4f07-bbb6-6eda05579f82" }
}}

**Comment by FaithOmbongi** [comment]
Assigned this issue to Engineering to validate and resolve.

No updates identified for the page. Closing the issue.
