### ISSUE TITLE
Multiple Email addresses

### ISSUE THREAD

**Issue by d1337ted** [microsoftgraph/microsoft-graph-docs#5982]
This example does not show how you would handle having more than one email address. I have tried passing a list of dictionaries in the format provided but that resulted in errors. It is also not clear what the "name" field is supposed to be. Is it the name of the person? the name of the type of mailbox? when looking at the contacts online in the web portal there are different types of email accounts like work, home, etc but this does not demonstrate how to address that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c564bd3c-9773-d2c1-76bc-02714e138043
* Version Independent ID: e1005cc1-813d-d865-8208-8f18c9c1bd4e
* Content: [emailAddress resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/emailaddress?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/emailaddress.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/emailaddress.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @d1337ted , thank you for your comments. You can see an example of the emailAddress complex type here, in the [get message](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0) topic, example section: https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=http#example-1.

The emailAddress complex type is used widely in the mail and calendar API, for example, all to, from, cc, bcc recipients are of the emailAddress type, and so is event organizers and attendees. So there are other examples of such properties in other mail and calendar API topics.

Likely what I can clarify here is, where you see a section titled "JSON representation", that section serves the purpose of defining the type of an entity or complex type and its properties, for an internal tool we use to validate examples. Please look for sections titled "Example" or "Examples" to see property values.
