### ISSUE TITLE
"licensedUserCount" is not a count of the licensed users in an Office 365 tenant

### ISSUE THREAD

**Issue by nukelaser** [microsoftgraph/microsoft-graph-docs#5992]
When running the "GET /security/secureScores" http request, the number it returns is not the number of licensed user accounts. It is in fact the number of assigned licenses in the Office 365 tenant, minus one, strangely enough. For example, for a client tenant that I manage, they have 288 assigned licenses, but the "licensedUserCount" property shows 287. The tenant also has 212 licensed users.

This property should either be renamed to "licenseAssignedCount" or the property itself should actually be populated with the correct number of licensed user accounts. As it stands currently this value is completely inaccurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc52e5ba-c66a-a5db-fde8-43ecae447d60
* Version Independent ID: f4ded98c-b942-470f-bb35-a421fccb5261
* Content: [secureScore resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/securescore?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/securescore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/securescore.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@NaynaSheth - Can you please help answer? Thanks.

**Comment by Christine-MSFT** [comment]
@nukelaser Thanks for providing feedback. Would you mind sharing your tenant ID so we can look into this further? You can email secscorepm@microsoft.com if you don't want to comment here.

**Comment by Christine-MSFT** [comment]
Hi @nukelaser, we were having some issues with that email address, so apologies if you were trying to send something. If you'd still like to give us your tenant ID for us to investigate, please email secscorefeedback_at_microsoft_dot_com

**Comment by bkeski** [comment]
I can confirm - licensedUserCount is NOT number of licensed users but number on all licenses in tenant.
In EVERY tenant I checked.
