### ISSUE TITLE
"licensedUserCount" sometimes returning a 6 digit value for some client tenants

### ISSUE THREAD

**Issue by nukelaser** [microsoftgraph/microsoft-graph-docs#5993]
I have a script that runs the "GET /security/secureScores" http request to every tenant that my organization manages in order to collect information for weekly reports (I am a Microsoft Partner). Of the 144 tenants I manage, for 23 of them, the property "licensedUserCount" contains a 6-digit number. It seems to add the actual number to 500,000. For example, bugged Client A returns 500004, bugged Client B returns 500117, and bugged Client C returns 500163. The script is running in a loop so the exact same request is being sent to each tenant with no deviation. All other properties are returned without any issues, only "licensedUserCount" has an issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc52e5ba-c66a-a5db-fde8-43ecae447d60
* Version Independent ID: f4ded98c-b942-470f-bb35-a421fccb5261
* Content: [secureScore resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/securescore?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/securescore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/securescore.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by preetikr** [comment]
@NaynaSheth - Can you please help answer? Thanks.

**Comment by NaynaSheth** [comment]
Thanks Nayna.

@Preeti Krishna<mailto:preetikr@microsoft.com> Could you replace Nayna with this alias: @Microsoft Secure Score PMs<mailto:secscorepm@microsoft.com> ? We will have a rotation of PMs on-call to look at customer issues.

From: Nayna Sheth (MUTHA) <naynam@microsoft.com>
Sent: Friday, April 3, 2020 12:10 PM
To: microsoftgraph/microsoft-graph-docs <reply@reply.github.com>; microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com>; Christine Xu <Christine.Xu@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [microsoftgraph/microsoft-graph-docs] "licensedUserCount" sometimes returning a 6 digit value for some client tenants (#5993)

Adding @Christine Xu<mailto:Christine.Xu@microsoft.com> Secure Score on-call PM for this week to help with this.

**Comment by NaynaSheth** [comment]
Can we get a tenant ID?

From: Christine Xu <Christine.Xu@microsoft.com>
Date: Friday, April 3, 2020 at 1:56 PM
To: Nayna Sheth (MUTHA) <naynam@microsoft.com>, microsoftgraph/microsoft-graph-docs <reply@reply.github.com>, microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com>, Preeti Krishna <preetikr@microsoft.com>, Microsoft Secure Score PMs <secscorepm@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [microsoftgraph/microsoft-graph-docs] "licensedUserCount" sometimes returning a 6 digit value for some client tenants (#5993)
Thanks Nayna.

@Preeti Krishna<mailto:preetikr@microsoft.com> Could you replace Nayna with this alias: @Microsoft Secure Score PMs<mailto:secscorepm@microsoft.com> ? We will have a rotation of PMs on-call to look at customer issues.

From: Nayna Sheth (MUTHA) <naynam@microsoft.com>
Sent: Friday, April 3, 2020 12:10 PM
To: microsoftgraph/microsoft-graph-docs <reply@reply.github.com>; microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com>; Christine Xu <Christine.Xu@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [microsoftgraph/microsoft-graph-docs] "licensedUserCount" sometimes returning a 6 digit value for some client tenants (#5993)

Adding @Christine Xu<mailto:Christine.Xu@microsoft.com> Secure Score on-call PM for this week to help with this.
