### ISSUE TITLE
Please update the title of the doc.

### ISSUE THREAD

**Issue by v-shde** [microsoftgraph/microsoft-graph-docs#5998]
the article is called Add conversationMember (in the menu its called Add a member to a chat), and the user is saying that it is not clear that a member is being added to a Team's channel, so maybe changing the article title (and menu entry) to Add a member to a chat (channel) could help'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497ad1e7-5a61-731f-e0e9-75b5cb9336c8
* Version Independent ID: 776a8387-3525-7289-51bd-1232f58d283a
* Content: [Add conversationMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
Hi - Article titles in Graph documentation refer to the type of entity that is being added. In this case, the conversationMember is what is being added. It is named to allow for extensibility in the future. The Table of Contents entry is title "Add a member to a channel".
