### ISSUE TITLE
Visibility value

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#6001]
According to the visibility property description (https://docs.microsoft.com/en-us/graph/api/resources/administrativeunit?view=graph-rest-beta#properties), the acceptable values are HiddenMembership or Public. What does "true" suppose to mean in this regard? And of course I get an error when trying to use this value:

{
    "error": {
        "code": "Request_BadRequest",
        "message": "true is not a valid value for visibility property. Valid values are HiddenMembership",
        "innerError": {
            "request-id": "60d8fc99-7248-4c4a-b24b-1512012c23a4",
            "date": "2019-10-17T09:42:50"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca3e40c5-42b1-9433-b0d2-684d8cfbaabf
* Version Independent ID: c6a10583-fc98-382b-880b-bef83e17f295
* Content: [Create administrativeUnit - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/administrativeunit-post-administrativeunits?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/administrativeunit-post-administrativeunits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/administrativeunit-post-administrativeunits.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Changed the value from true to HiddenMembership.
