### ISSUE TITLE
Inability to get team from internal id

### ISSUE THREAD

**Issue by liiamjones** [microsoftgraph/microsoft-graph-docs#6014]
The Security and Governance portal only provides the internal id when a team is created. it does not provide the group id.

Is there anyway to query the team by internal id. eg. 19:3d1420e4f42744c0a6581062c96532f0@thread.skype

Or is it possible to add the group id to the created team audit record?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533cbe72-3c95-04b8-5db4-cdd32d088d57
* Version Independent ID: fb69519b-3e4a-2279-cf1d-8e9c082fafd6
* Content: [Get team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by liiamjones** [comment]
anything on this?

**Comment by anandab-msft** [comment]
@liiamjones  as of now there is no way to do this, i would request you to raise this in user voice  - https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359626
