### ISSUE TITLE
broken link in changelog to user reprocess license API

### ISSUE THREAD

**Issue by egcd32** [microsoftgraph/microsoft-graph-docs#6019]
The Changelog for October 2019 item
Addition     beta     Added the user: reprocessLicenseAssignment API, which can be used to reprocess all group-based license assignments for the user. 
has a broken link 
https://docs.microsoft.com/en-us/graph/api-reference/beta/api/user-reprocesslicense?view=graph-rest-beta
which displays 404.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a84942d-0326-24c3-d8fa-4fbd782132b3
* Version Independent ID: 08ab36ac-6f96-920a-b4dd-07c292fbacae
* Content: [Changelog for Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/changelog?view=graph-rest-beta)
* Content Source: [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/changelog.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
This is fixed. Will go live this afternoon.
