### ISSUE TITLE
404 on the Meetings & Calling API Link

### ISSUE THREAD

**Issue by AlexHill90** [microsoftgraph/microsoft-graph-docs#6021]
Hi there,

the link on

Calling and online meetings (Preview)	Create Microsoft Teams apps with bots that can initiate and participate in audio/video calls, route/transfer calls based  

gives a 404 ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4f5720-3eb2-fe1d-472e-497d1449f97b
* Version Independent ID: eaa22434-4691-77e2-8905-bf6d7e9e0bef
* Content: [Microsoft Teams API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-concept-overview)
* Content Source: [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-concept-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@nkramer @ananmishr can we get this updated? I'm not sure what it's supposed to link to, is it https://docs.microsoft.com/graph/api/resources/communications-api-overview?view=graph-rest-beta?
