### ISSUE TITLE
Adding Win32 LoB apps to a category

### ISSUE THREAD

**Issue by tjgruber** [microsoftgraph/microsoft-graph-docs#6029]
This would have been useful to me if it was on the page, for adding an app to a category:

URI: 
https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/{AppId}/categories/$ref

Body: 
{"@odata.id":"https://graph.microsoft.com/beta/deviceAppManagement/mobileAppCategories/{CategoryId}"}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92204146-b459-b68f-14d2-f128748d5fb7
* Version Independent ID: 373923d8-98c5-3752-704c-398f05017e7f
* Content: [Create win32LobApp - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-create?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-apps-win32lobapp-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-apps-win32lobapp-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
To add a category to an app you make a POST call like this
URI:
https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/{AppId}/categories/$ref
Body:
{"@odata.id":"https://graph.microsoft.com/beta/deviceAppManagement/mobileAppCategories/{CategoryId}"}

To delete a category from an app you make a DELETE call like this
URI:
https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/{AppId}/categories/{CategoryId}/$ref
