### ISSUE TITLE
Removing a Win32 LoB app from a category? 

### ISSUE THREAD

**Issue by tjgruber** [microsoftgraph/microsoft-graph-docs#6030]
What uri do i use to do this? I figured it out for adding, using a $ref, but for removing, what's the uri? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c236aca6-0f0e-5838-377d-c02f30cf2e6f
* Version Independent ID: ad9eb8f9-32f1-0497-a824-f8e92a3b964e
* Content: [mobileAppCategory resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-mobileappcategory?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/intune-apps-mobileappcategory.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-apps-mobileappcategory.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tjgruber** [comment]
I have figured it out after a lucky trial-and-error guess:

The URI to use is:
`https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/{appId}/categories/{categoryId}/$ref`

...and without a reference or body.

It'd maybe save others some time if this was documented (as well as adding in my other "issue").

**Comment by rolyon** [comment]
Hi @tjgruber 
Thanks for the feedback. The team has indicated that the URI is:
mobileApps({appId})/categories({categoryId})/$ref
thanks

**Comment by rolyon** [comment]
If you have any additional feedback, you can re-open this issue.
thanks
