### ISSUE TITLE
No C# example

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/microsoft-graph-docs#6031]
How to create it with Core 2.2 C# ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f895c860-20d5-a075-1f01-41cc06e5182e
* Version Independent ID: c0557b9e-b45d-911c-9cbe-e6752f9fa31f
* Content: [ColumnDefinition - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/columndefinition.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by lramosvea** [comment]
You can find a C# example here: https://docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-1.0&tabs=csharp

Please feel free to reopen if this doesn't answer your question.
