### ISSUE TITLE
Shared Calendars

### ISSUE THREAD

**Issue by ssimm** [microsoftgraph/microsoft-graph-docs#6040]
How could I limit an daemon-app (no user interaction) to access the calendars of only one user, but to include the calendars shared with that user?  The list of supported permissions above suggests that this is not possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca1eed2-d0ca-11de-4f25-f09865605a0f
* Version Independent ID: 9fd423e0-86e4-b7e4-9249-1bacb51e81ad
* Content: [Scoping application permissions to specific Exchange Online mailboxes - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-limit-mailbox-access)
* Content Source: [concepts/auth-limit-mailbox-access.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-limit-mailbox-access.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svpsiva** [comment]
Yes, this is not possible with Application permission scopes approach as such apps operate as a service principal and are not associated to any one user.

Delegated permissions + refresh tokens can be used to power daemon apps, but you will need to handle/manage the case when the refresh token is expired and the app needs to be re-authorized by the user.

**Comment by ssimm** [comment]
Darn.
How do I request that this functionality be added?  Is there a wish-list
somewhere?
Thanks,
Stephen

**Comment by svpsiva** [comment]
UserVoice is the place where our users make new feature requests. I'd suggest raising this via 

https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359596

**Comment by ssimm** [comment]
OK, I did it. The title of the request is:
"Daemon Apps should be able to have the same rights as a given user"
