### ISSUE TITLE
Team privacy can not be set

### ISSUE THREAD

**Issue by ovetter1** [microsoftgraph/microsoft-graph-docs#6048]
teamsTemplates('standard')'s privacy is "public" and can not be changed via this API. As an alternative you could offer a second standard template which privacy would be "private".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-gt** [comment]
@ovetter1 - try using visibility parameter in request body ("visibility": "Private")

**Comment by anandab-gt** [comment]
@ovetter1 - closing this issue, in case you feel your problem is not solved either reopen this issue or create a new issue.
