### ISSUE TITLE
Some user attributes needs access permission to SharePoint

### ISSUE THREAD

**Issue by kenmoritest** [microsoftgraph/microsoft-graph-docs#6054]
According to the following discussion, some user attributes such as PastProjects needs to be retrieved internally from SharePoint Online. 
https://github.com/microsoftgraph/microsoft-graph-docs/issues/3901
Please specify the right permission (Sites.*) to access those resources for those cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Closing the issue. Please reopen and provide more information about the call you making if needed.
