### ISSUE TITLE
C# example is invalid

### ISSUE THREAD

**Issue by mheptinstall** [microsoftgraph/microsoft-graph-docs#6061]
There is currently no Contacts property on GraphServiceClient
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/GraphServiceClient.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ba4762-41f1-993c-01ed-29729f889c5e
* Version Independent ID: 25d607e0-2216-5191-ff3d-119fb816369d
* Content: [List orgContacts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/orgcontact-list?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/orgcontact-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/orgcontact-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The C# example is automatically created from code. When I look at: https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Requests/Generated/GraphServiceClient.cs

I see this:

/// <summary>
        /// Gets the GraphServiceContacts request builder.
        /// </summary>
        public IGraphServiceContactsCollectionRequestBuilder Contacts
        {
            get
            {
                return new GraphServiceContactsCollectionRequestBuilder(this.BaseUrl + "/contacts", this);
            }
        }

Please re-open the issue with whatever error you are encountering,
