### ISSUE TITLE
For a csp scenario, what is the recommended authorization flow ?

### ISSUE THREAD

**Issue by blalonde** [microsoftgraph/microsoft-graph-docs#6064]
We currently receive 199 - "Microsoft/Office 365 Security and Compliance/401/72"
Although we can poke the other Graph Api endpoints.

We're using this flow : https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model by targeting graphapi ressource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec00d4cb-7b30-523b-5732-f42411c3dd9c
* Version Independent ID: 299e5875-57b0-d7fe-7831-fff4633d318e
* Content: [Authorization and the Microsoft Graph Security API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/security-authorization#feedback)
* Content Source: [concepts/security-authorization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/security-authorization.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@blalonde , can you please clarify if you are trying to use the Graph Security API or Graph API? And what is the scenario of using the API?
