### ISSUE TITLE
RequestBroker--ParseUri  Resource not found for the segment

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoftgraph/microsoft-graph-docs#6069]
When trying to get the details of an event, Graph aborts with 
```
{
  "error": {
    "code": "RequestBroker--ParseUri",
    "message": "Resource not found for the segment 'JP8UpOlBwDJq7RVfltsSbUbFnyf0zTHAAAAAAENAADJq7RVfltsSbUbFnyf0zTHAAAE'.",
    "innerError": {
      "request-id": "ed99c913-7803-42b7-8d0f-a6064e383271",
      "date": "2019-10-24T14:39:42"
    }
  }
}
```

The URL is 
`https://graph.microsoft.com/v1.0/Users/<tenantid>/Events/AAMkADNhODY5OGJjLTU3ZGItNDAyNC05ZjkyLTMzMThjNTM1OTM4ZABGAAAAAADmVJuXm+jXRIyi/JP8UpOlBwDJq7RVfltsSbUbFnyf0zTHAAAAAAENAADJq7RVfltsSbUbFnyf0zTHAAAE/GtcAAA=`

The EventID I use comes from the Outlook JavaScript API Office.context.mailbox.item.itemId property in an Add-on running in the context of the event.

**Comment by timothyhoffmann** [comment]
Update:  The problem appears to be the format of the itemId that Office.context.mail.item.itemId returns vs what Graph is returning and using.

The ItemID from item.itemId is
`AAMkADNhODY5OGJjLTU3ZGItNDAyNC05ZjkyLTMzMThjNTM1OTM4ZABGAAAAAADmVJuXm+jXRIyi/JP8UpOlBwDJq7RVfltsSbUbFnyf0zTHAAAAAAENAADJq7RVfltsSbUbFnyf0zTHAAAcLYxPAAA=`

The same record pulled via Graph (
> https://graph.microsoft.com/v1.0/Users/"emailaddress"/Events/
) comes back as

`AAMkADNhODY5OGJjLTU3ZGItNDAyNC05ZjkyLTMzMThjNTM1OTM4ZABGAAAAAADmVJuXm_jXRIyi-JP8UpOlBwDJq7RVfltsSbUbFnyf0zTHAAAAAAENAADJq7RVfltsSbUbFnyf0zTHAAAcLYxPAAA=`

The difference appears to be the **m+j** in itemId is a **m_j** in Graph and **yi/JP** is **yi-JP**

Is there a rule that can be documented on how to convert JS API ItemIds to Graph IDs?

**Comment by Harini84** [comment]
@jthake-msft 
This is generic issue on how to convert itemID of a message or event in office.context.mailbox.item to Graph-ID:
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item

@timothyhoffmann 
The method convertToRestId might help.
https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview

**Comment by svpsiva** [comment]
Have you tried using the translateExchangeIds API? https://docs.microsoft.com/en-us/graph/api/user-translateexchangeids?view=graph-rest-1.0&tabs=http API
