### ISSUE TITLE
Please document "Enumerate sites" API here

### ISSUE THREAD

**Issue by aaronmi** [microsoftgraph/microsoft-graph-docs#6073]
"Enumerate sites" API is currently documented in https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/site_list?view=odsp-graph-online. It should be added to here as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 217852fe-79b1-a74c-3ff5-c059f4e7ca47
* Version Independent ID: 170e578f-ddd3-857c-f137-7cb3508aeefe
* Content: [site resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by viraf** [comment]
Enumerate sites endpoint always returns 0 results. 

```
https://graph.microsoft.com/v1.0/sites/root/sites
https://graph.microsoft.com/beta/sites/root/sites
```

Result

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#sites",
    "value": []
}```

Am I missing something. I have multiple subsites in my Sharepoint instance. Anyway to list all the sites the logged in user has access to would help.

**Comment by lramosvea** [comment]
You can find the doc here: https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-1.0

To get help with your code, please visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-sites-lists.html)
