### ISSUE TITLE
lastUpdatedDateTime doesnt change

### ISSUE THREAD

**Issue by AnkitsCode** [microsoftgraph/microsoft-graph-docs#6083]
Hi there,
I get the list of the chats via me/chats/, but even after having conversations, the lastUpdatedDateTime always remains the same. I need to make further GET calls to chats/{id}/messages (and then POST too), but only for recent chats (not all the chats as it may get bulky over time). I was planning to do this via recent lastUpdatedDateTime which never changes for some reason. So currently I have to loop each chat (fetched from me/chats/) -&gt; get the ID for each chat -&gt; call chats/{id}/messages for each ID, get  createdDateTime for each message and based on that createdDateTime of message (inside the chat object), I get to know if this chat is recent one or not. Shouldn't it just update on the lastUpdatedDateTime?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79531fbc-dd22-cf80-c97c-746f7dcab790
* Version Independent ID: 173779d8-884c-44d1-1955-177b5066e78f
* Content: [List chats - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=csharp#feedback)
* Content Source: [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by AnkitsCode** [comment]
Also if you can suggest a better way it will be hugely appreciated.  All I am trying to do is find out all the recent chats received by a particular user (lets say within the last 30 seconds) and echo it back. I am able to get/post but can't seem to find a faster way around finding recent chats (since my way may be problematic if we scale it with more users).

**Comment by AnkitsCode** [comment]
Hi, any update on this please?

**Comment by mrtbyram** [comment]
Hi, I'm waiting for the fix as well.

**Comment by jussmi** [comment]
Confirming that this is still an open issue. I am able to filter results with the OData query parameters, but the underlying data never updates the lastUpdatedDateTime.
https://graph.microsoft.com/beta/me/chats/?$filter=date(lastUpdatedDateTime) ge 2020-10-11T15:09:36Z&$select=id,lastUpdatedDateTime

**Comment by jussmi** [comment]
@AnkitsCode 
Looks like they consider this one differently given the update to the documentation in this pull request-
https://github.com/microsoftgraph/microsoft-graph-docs/pull/9221
lastUpdatedDateTime evidently refers to when the chat was renamed or membership changes. Certainly a less useful parameter.

**Comment by Prithvi-MSFT** [comment]
Hi @AnkitsCode ,
If you refer below document it mentions that lastUpdated field changes when we change conversation name or add new member in conversation. It is not related to chat message update.
https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-1.0

Thanks
