### ISSUE TITLE
Why there is a relation named "drives" and how can list the user's shared document library?

### ISSUE THREAD

**Issue by landall** [microsoftgraph/microsoft-graph-docs#6087]
In which situation the /drives contain moren than one result?
and how can I get the shared library just like onedrive app & website do? I  can only get the ones coming from his office365 group but not the ones from his sharepoint following.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Doesn't appear to be a problem running the operation. No change identified for this page. Closing the issue.
