### ISSUE TITLE
Getting an error...Please help

### ISSUE THREAD

**Issue by sayanroychaudhuri** [microsoftgraph/microsoft-graph-docs#6098]
[object Object]: {body: "{"code":"","message":"No HTTP resource was found that matches the request URI 'https://outlook.office365.com:444/profile/v1.0/users('CID:db8fb4b1a4ab404e')/profile?api-version=AGSV1-internal'.","innerError":{"request-id":"8e3d97e4-b667-4fc2-a32d-3f6dd30cbeb2","date":"2019-10-28T11:40:03"}}", code: "", date: [date] Mon Oct 28 2019 11:40:03 GMT+0530 (India Standard Time), message: "No HTTP resource was found that matches the request URI 'https://outlook.office365.com:444/profile/v1.0/users('CID:db8fb4b1a4ab404e')/profile?api-version=AGSV1-internal'.", requestId: "8e3d97e4-b667-4fc2-a32d-3f6dd30cbeb2"...}

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(Fetch)POST - https://graph.microsoft.com/v1.0/users

I am getting this error in console using javascript api. Please help....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=javascript#request-body)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by andrewconnell** [comment]
Might want to try sharing the code you used to create that request. The endpoint (aka: resource) definitely looks incorrect.

**Comment by davidmu1** [comment]
Not enough information in the issue description to identify a change to the page. Closing the issue.
