### ISSUE TITLE
Date Filter

### ISSUE THREAD

**Issue by tomrade** [microsoftgraph/microsoft-graph-docs#6101]
Issue: Example date field is wrong

Article: https://docs.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-1.0&tabs=http

The Directory Audit docs show an example filter for "createdDateTime". This fails , the correct field is "activityDateTime". 

However I think I would rather have a createdDateTime if I was using this api to pull logs at regular intervals.

**Comment by SarahBar** [comment]
I put in a pull request to update the docs article referenced above to change "createdDateTime" to "activityDateTime", and am closing this issue. We do not have any current plans to add a new DateTime stamp for the date when the activity was created in the logs, although the latency is low (typically the record is created less than 15 minutes after the event occurs). Thank you for taking time to provide feedback and improve the quality of our documentation.
