### ISSUE TITLE
isAllDay requirements for create/update

### ISSUE THREAD

**Issue by Samsinite** [microsoftgraph/microsoft-graph-docs#6129]
The start/end field requirements if isAllDay is true seem to be undocumented, what is the expected format of these fields in this situation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41a9857-98a9-e400-d7ce-bd7c0f37cd46
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/event.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
The time component of `start` and `end` are ignored, which makes the timezone essentially meaningless. But what I would do is specify the user's timezone anyway, so the payload would look something like this:

```
{
  "subject": "My all-day event",
  "isAllDay": true,
  "start": {
    "dateTime": "2019-11-11",
    "timeZone": "UTC"
  },
  "end": {
    "dateTime": "2019-11-12",
    "timeZone": "UTC"
  }
}
```
