### ISSUE TITLE
?$expand=columnSet fails for List Items containing checkBoxes

### ISSUE THREAD

**Issue by bharath063** [microsoftgraph/microsoft-graph-docs#613]
?$expand=columnSet fails for List Items containing checkBoxes in Sharepoint. It works fine if the List Items contain only text inputs.

**Comment by AVDW** [comment]
I'm getting exactly the same result when using expand on Sharepoint list items. REST call is returning a 500 response.

**Comment by codingo** [comment]
I can confirm the 500 response also. It would be good to receive a text string even if it needs to be cleaned up using regex (much like the old API endpoints).

**Comment by isvargasmsft** [comment]
Hello, my deepest apologies for the delays in addressing this issue. 

I checked from my end and noticed:
1. ColumnSet attribute has been renamed to "Fields". Details in the [changelog.](https://developer.microsoft.com/en-us/graph/changelog/?filterBy=v1.0,Sites%20and%20lists,beta&page=2#54c8f6cc-3d14-4c83-9d87-e93e1318f7c8beta)
2. The issue has been fixed as the request is working with the following command:
`https://graph.microsoft.com/v1.0/sites/{site-id}/lists/{list-id}/items/{item-id}?$expand=fields`

Hope this clarifies. 

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at Microsoft Q&A: [Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html). 

Kind regards, 

Isaac Vargas
