### ISSUE TITLE
Application Permissions not working

### ISSUE THREAD

**Issue by felickz** [microsoftgraph/microsoft-graph-docs#6139]
Sending an bearer JWT acquired with app client credentials with the applications permissions as listed here: 
Application.ReadWrite.OwnedBy, Application.ReadWrite.All, Directory.Read.All

Which provides:
  "roles": [
    "Application.ReadWrite.OwnedBy",
    "Application.ReadWrite.All",
    "Directory.Read.All"
  ],

But this endpoint returns: 
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "{uuid}",
      "date": "2019-10-30T13:43:23"
    }
  }
}

Using a user account with delegated permissions (password grant) works as expected sending in SCP of:  "scp": "Directory.AccessAsUser.All Policy.ReadWrite.TrustFramework User.Read profile openid email"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e54b976f-d385-dd5e-26b8-0c989072a47a
* Version Independent ID: a9769817-27b8-c2a4-4ea4-5d9c16296fe6
* Content: [Add application password - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-add-password?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/application-add-password.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-add-password.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sureshja** [comment]
@felickz, Is this still an issue you are facing? Except for the Directory.Read.All the other permissions should work with client credentials as documented.

**Comment by davidmu1** [comment]
No response. Closing the issue.
