### ISSUE TITLE
404 on intune-devices-devicehealthscriptassignment

### ISSUE THREAD

**Issue by jwmoss** [microsoftgraph/microsoft-graph-docs#6149]
Issue: line 53 intune-devices-devicehealthscriptassignment links to a 404

Article: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/graph/api/resources/intune-devices-devicehealthscriptassignment.md?view=graph-rest-beta

**Comment by jthake-msft** [comment]
This link doesn't actual exist. so closing this post.
