### ISSUE TITLE
How to update group's profile picture using C# httpclient request?

### ISSUE THREAD

**Issue by anomepani** [microsoftgraph/microsoft-graph-docs#6150]
How to update group's profile picture using C# httpclient without graph sdk?
I am getting this error:
`An internal server error occurred. The operation failed., The file you chose isn't an image. Please choose a different file.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilephoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
Hi @anomepani , it is a bit difficult to help you debug your code if we can't see your code.  Is there a reason why you don't want to use the SDK?

**Comment by anomepani** [comment]
Actually I am working on Microsoft team provisioning  and want to set ms team picture icon. Unfortunately I think Microsoft Graph Sdk didn't helpful to me on this for team related functionality. I have refered teams contoso airline and other demo which is not using microsoft graph sdk but they are performing all operations with httpclient .  So due to this reason I am searching for non graph sdk approach.

**Comment by jasonjoh** [comment]
Which Contoso Airline sample are you looking at? I updated that to use the SDK once they added support for the features I was using. Originally yes, I used HttpClient, but that was solely because the features were very new and not yet added to the Graph Beta SDK.

**Comment by anomepani** [comment]
@jasonjoh I am using this repo [https://github.com/microsoftgraph/csharp-teams-sample-graph](https://github.com/microsoftgraph/csharp-teams-sample-graph).
As it looks more popular and has more stars as well.

**Comment by anomepani** [comment]
It's very annoying when some feature is available in SDK but there is no such documentation of how to implement with plaint HTTPClient request.

**Comment by anomepani** [comment]
Closing this issue as I have found answer and figure out plain http request for c# and posted answer on [Stackoverflow](https://stackoverflow.com/questions/58569252/how-can-i-set-a-team-picture-programmatically-using-microsoft-graph-api/59325136#59325136)
