### ISSUE TITLE
Function parameters details are missing

### ISSUE THREAD

**Issue by mrkeiths** [microsoftgraph/microsoft-graph-docs#6152]
The "Function parameters" section is missing on many/most pages under this "Privileged Identity Management" section in the left navigation.

Here is an example of a similar graph API that does have parameters documented:
https://docs.microsoft.com/en-us/graph/api/reportroot-getemailactivitycounts?view=graph-rest-1.0&tabs=http

Can these please be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86a88ab-499c-0ce7-09b5-9abf35ab35a2
* Version Independent ID: 79e71535-3d70-f016-e394-fcfc5d17e67d
* Content: [Get privilegedRole - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/privilegedrole-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/privilegedrole-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/privilegedrole-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The only variable value in the request URL on this page is {id} which is defined on the privilegedRole resource page: https://docs.microsoft.com/en-us/graph/api/resources/privilegedrole?view=graph-rest-beta. This parameter is not typically defined on each API page and is not the same situation as the function that you referenced. No change required for this article.
