### ISSUE TITLE
Blazor example

### ISSUE THREAD

**Issue by ADefWebserver** [microsoftgraph/microsoft-graph-docs#6160]
For anyone looking for a Blazor example: Blazor Microsoft Graph Calendar Example With Active Directory Authentication - http://blazorhelpwebsite.com/Blog/tabid/61/EntryId/4358/Blazor-Microsoft-Graph-Calendar-Example-With-Active-Directory-Authentication.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0733b09-b4b0-a83f-d417-32ed26c33790
* Version Independent ID: 2bc7308f-0688-d7d6-d6e9-be06b3452cb8
* Content: [Microsoft Graph tutorials - Microsoft Graph](https://docs.microsoft.com/en-us/graph/tutorials)
* Content Source: [concepts/tutorials.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/tutorials.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jasonjoh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sytone** [comment]
Would be good to have a non server based example as well.
