### ISSUE TITLE
Discrepancy on groups that members can be added to

### ISSUE THREAD

**Issue by MichaelAOliver** [microsoftgraph/microsoft-graph-docs#6162]
The first line of this article states that you can add a member to a security group.  Two lines later it states that you may only add users to Office 365 groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
I don't see that.
First line says:  Add a member to an **Office 365 group or a security group** through the members navigation property.
NOTE later says: You can only add users to **security and Office 365 groups** managed through the cloud.
