### ISSUE TITLE
More Detail needed on passwordCredentials

### ISSUE THREAD

**Issue by acds** [microsoftgraph/microsoft-graph-docs#6164]
As part of the Application PATCH API it would be great to document what are required and what will be populated in a subsequent response such a `keyid`.

We have had code working for 10 months, and now we get a BadRequest and no clear cause as to what changed (recently).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb6264f4-f053-bf11-15ae-528652ff8a79
* Version Independent ID: 90aa6e1d-6efa-5100-b51f-7766325086a6
* Content: [keyCredential resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/keycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/keycredential.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @sumurthy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies for the late response.
Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html). Please ask your question there. No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
