### ISSUE TITLE
400 Bad Request Response code - when update paswordCredentials

### ISSUE THREAD

**Issue by acds** [microsoftgraph/microsoft-graph-docs#6165]
Please can you document what are required fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ebf6ea-2c02-21d8-0ce6-412d8fb4e32d
* Version Independent ID: 6eee450a-b6d0-0908-0392-00e01d412185
* Content: [Update application - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sureshja** [comment]
Developers will no longer be able to set custom passwords through PATCH or POST operation. This was done to enhance the security profile of the apps. See: https://developer.microsoft.com/en-us/office/blogs/breaking-changes-application-and-serviceprincipal-api-updates-in-microsoft-graph-beta/

**Comment by davidmu1** [comment]
No change required to the page. Closing the issue.
