### ISSUE TITLE
Delete Channel doesn't really delete a channel. 

### ISSUE THREAD

**Issue by jmcadams-r7** [microsoftgraph/microsoft-graph-docs#6168]
This happens in the UI. 
Create a channel called "Test" 
Delete the channel
Try to create a channel called "Test" - You'll get an error saying the channel already exists. 

From the API you'll get this...

Create channel a_test_channel failed. {
  "error": {
    "code": "NameAlreadyExists",
    "message": "Channel name already existed, please use other name",
    "innerError": {
      "request-id": "eed9d310-b4c1-4818-95af-14fa37f09940",
      "date": "2019-11-01T20:27:42"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9c20710-ba85-8bd7-4a00-27bb543ed055
* Version Independent ID: b4cbf7eb-1373-a7ee-eb27-3c9c8a8430e7
* Content: [Delete channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-delete.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vasanthtt** [comment]
Any update on this?.. deleting from UI and recreating with same is working. But getting failed through graph API.

```
{
  "error": {
    "code": "BadRequest",
    "message": "Channel name already existed, please use other name",
    "innerError": {
      "request-id": "2dc23641-65ea-4fee-bfb0-39e9840eb5e9",
      "date": "2019-12-19T08:54:13"
    }
  }
}
```

**Comment by hansadmin** [comment]
Probably has to do with the fact that channels are restoreable for 30 days. I bumped into this in combination with the 30-private-channel-limit. Now I can't create any new private channels. Also cannot find documentation on how to permanently delete Team-channels.

**Comment by anandab-gt** [comment]
A deleted channel stays in soft delete state for 24 hours, try creating channel with same name after 24 hours.
