### ISSUE TITLE
Unable to create app with password using beta API

### ISSUE THREAD

**Issue by Hong-Revo** [microsoftgraph/microsoft-graph-docs#6179]
Code that was working up until last week is now failing with a 400 error: `New password credentials must be generated with service actions`. The REST call is

```
POST https://graph.microsoft.com/beta/applications

{
  "displayName": "appname",
  "passwordCredentials": [
    {
      "customKeyIdentifier": "base64/UTF16-encoded-name",
      "endDateTime": "2020-12-31T12:00:00Z",
      "secretText": "some-secret-text"
    }
  ]
}
```

This was using an app with delegated Directory.AccessAsUser.All, User.Read and openid permissions. I'm the admin of the tenant in question.

**Comment by lboro** [comment]
I have the exact same problem : 

I was creating applications with secrets (passwordCredentials) just fine on thursday (october 31st), it stopped working on friday (november 1st) with the same error message : 

```json
{
  "error": {
    "code": "Request_BadRequest",
    "message": "New password credentials must be generated with service actions.",
    "innerError": {
      "request-id": "ce51e04b-8783-4e6a-8b38-833b8d07baf7",
      "date": "2019-11-04T12:44:21"
    }
  }
}
```
