### ISSUE TITLE
Add note about lifecycle events

### ISSUE THREAD

**Issue by JacobMikkelsen** [microsoftgraph/microsoft-graph-docs#6189]
I think it would be worth mentioning that this endpoint should also service lifecycle events. By reading this page I assumed that if the request didn't come with a validationToken query parameter it would be for a notification event, but that doesn't seem to hold up. I realise the page regarding lifecycle events is a couple items down in the sidebar, but it would be good to surface it here so developers know that there are more types of requests that can be given to their endpoints.

The page detailing lifecycle events:
https://docs.microsoft.com/en-us/graph/webhooks-outlook-authz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maxlund** [comment]
related https://github.com/microsoftgraph/microsoft-graph-docs/issues/5784

**Comment by baywet** [comment]
thanks! closing in favor of #5784 to centralize discussions
