### ISSUE TITLE
Unable to get other user's photo thumbnail

### ISSUE THREAD

**Issue by keehl1213** [microsoftgraph/microsoft-graph-docs#619]
According to this document [List thumbnails for a DriveItem](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_list_thumbnails), we can get onedrive photo thumbnails by using this API.

When I sent a request to get a photo thumbnail from my OneDrive with Microsoft graph API, server returned 200 and worked fine.

`https://graph.microsoft.com/v1.0/users/{my user id}/drive/items/{my photo object id}/thumbnails`

However server returned 404 not found while I tried to get a photo thumbnail from other user's onedrive.

`https://graph.microsoft.com/v1.0/users/{other user's id}/drive/items/{other user's photo id}/thumbnails`

I really sure the **other user's photo** is existed and the id is corrected.
If I used it wrong or it just can't access other user's onedrive photo?

**Comment by mimisasouvanh** [comment]
Hi Nina, I don't believe you can access other user's photos unless they are signed in and grant the app access.
Regards,
Mimi

**Comment by keehl1213** [comment]
I tried to share the file to me with email, but still not working. [Share with email](https://support.office.com/en-us/article/Share-OneDrive-files-and-folders-9fcc2f7d-de0c-4cec-93b0-a82024800c07)

Although I know it's weird that one user can access other user's file, the users parameter in this API is confused me.

**Comment by mimisasouvanh** [comment]
If you're trying to list items that are shared with you, by other users, this might help: https://dev.onedrive.com/drives/shared_with_me.htm

**Comment by keyur32** [comment]
I'm closing this out for now, but feel free to re-activate if you are still experiencing issues. thanks!
