### ISSUE TITLE
How to create subscriptions for Sharepoint

### ISSUE THREAD

**Issue by urjitgokhale** [microsoftgraph/microsoft-graph-docs#6190]
There are Graph APIs that let me access sharepoint resource. But I have not found a way to create subscription for sharepoint so I would get realtime notifications when something changes.
I would appreciate if you could point me to relevant documentation.

Thanks,
~ Urjit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by urjitgokhale** [comment]
It seems one could use /drives/root as resource to create subscription for sharepoint. 

However we have seen that we do not get notified when a file on sharepoint is shared with an external user (outside the org).
Whereas we do get a notification when the file on sharepoint is shared with an internal user.
Can someone help us understand this better? 
Any pointers to any resources would be appreciated.
Thanks,
~ Urjit

**Comment by JeremyKelley** [comment]
Thanks for the feedback!  You are correct that today you do not get a notification on sharing with an external user.  This is a feature that the team is working on.

**Comment by lramosvea** [comment]
Closing as I see this doc has been updated already. Please feel free to reopen if the issue persists.
