### ISSUE TITLE
API Sharepoint List

### ISSUE THREAD

**Issue by einue** [microsoftgraph/microsoft-graph-docs#6193]
I used an registered App and try to get the list-items via Get-Request.
But I receive only 

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(microsoft.graph.list)('id')/items",
    "value": []
}

The list have items, but they are not shown in the json-result. Which settings are necessary in the api-permissions?

**Comment by schaeferto** [comment]
I have following permissions set for the application in portal.azure:

**Microsoft Graph**
* Files.ReadWrite.All
* User.Read
