### ISSUE TITLE
Is there a plan to include 'lastPasswordChangeDateTime' field in Users directory objects

### ISSUE THREAD

**Issue by martyn1111** [microsoftgraph/microsoft-graph-docs#6196]
Recently you have added the property lastPasswordChangeDateTime in the /users resource
https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0 But what I'm trying now is getting a list of users using the ids with this /directoryObjects/getByIds?$select=lastPasswordChangeDateTime but this call is not returning this property. Somebody knows if this is going to be returned in some time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652f070a-a126-9add-13db-e35250b8b86c
* Version Independent ID: d256be5b-8466-385f-32a4-2d9fd9a89886
* Content: [Get directory objects from a list of ids - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryobject-getbyids?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-getbyids.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryobject-getbyids.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
$select is not (currently) support on the getByIds action/method.  I say currently because it is work in progress.

**Comment by davidmu1** [comment]
No change required for the article. Closing the issue.
