### ISSUE TITLE
The request only returns the last 10 items in the interval.

### ISSUE THREAD

**Issue by mirronelli** [microsoftgraph/microsoft-graph-docs#6201]
I have a url like this https://graph.microsoft.com/v1.0/me/calendars/SOMEID/calendarview?startdatetime=2019-11-03&enddatetime=2019-11-10. Wishing to get a full week of events. However it only returns the last 10 items. If I move the end interval to a sooner date eg: 2019-11-07, it returns the last 10 items in the new interval.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c927daf-9a45-a43a-2fae-5cec36564ea9
* Version Independent ID: 3af032d0-3e89-1b6c-be38-0da1e580d2e9
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/calendar-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-list-calendarview.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mirronelli** [comment]
Now I get it. It only returns a single page with a link for continuation. Nevertheless it should be documented so that people do not have to learn the hard way.

**Comment by michelcarlo** [comment]
Append the top parameter to your query if you want to retrieve more values in the page (max is 1000):
Example:
https://graph.microsoft.com/v1.0/me/calendars/SOMEID/calendarview?startdatetime=2019-11-03&enddatetime=2019-11-10&$top=1000

**Comment by mirronelli** [comment]
Thanks, I realized that. The pity is that the docs do not mention this.
