### ISSUE TITLE
Unexisting status

### ISSUE THREAD

**Issue by kastromatos** [microsoftgraph/microsoft-graph-docs#6209]
You wrote in supported resources section: "/security/alerts?$filter=status eq ‘New’".
But there is no such alert status. I spent couple of hours to realize it kek. Fix it, please.
https://docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks?source=docs#notification-endpoint-validation)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @kastromatos 
Thanks for letting us know! I just submitted a pull request.
