### ISSUE TITLE
Conflicting information on encoding single quotes in query parameters

### ISSUE THREAD

**Issue by pypmannetjies** [microsoftgraph/microsoft-graph-docs#6215]
This doc states that the single quote does not need to be encoded:

https://docs.microsoft.com/en-us/graph/query-parameters#encoding-query-parameters

> A properly encoded URL looks like this:
> 
> HTTP
> 
> Copy
> GET https://graph.microsoft.com/v1.0/users?$filter=startswith(givenName%2C+'J')

However, another doc states that it should be encoded to `%27`. 

https://developer.microsoft.com/en-us/graph/docs/overview/query_parameters

> In general, when specifying query parameters in your app, make sure you appropriately encode characters that are reserved for special meanings in an URI. For example, encode the space **and quote characters** in the last example, as shown:
> GET https://graph.microsoft.com/v1.0/me/messages?$filter=from/emailAddress/address%20eq%20%27jon@contoso.com%27

It's unclear which is correct. Javascript's encodeURIComponent does not encode the single quote. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @pypmannetjies 
Thanks for reaching out and sorry for taking so long to answer.
The second link you are pointing to is the old location for documentation that has been moved over to docs.microsoft.com where docs are kept up to date.
So the first link is the source of truth.
