### ISSUE TITLE
Suggestion for documentation - the Owner parameter in Request Body section

### ISSUE THREAD

**Issue by MahimaBagla** [microsoftgraph/microsoft-graph-docs#6220]
As mentioned in the Create schema extension documentation, Users can provide owner parameter in Request body to provide the app id that would own this extension, especially in the case when user is using Graph explorer to execute these APIs. The same option is available for Update Schema extension as well, however it is not mentioned here in the documentation. This misleads the user that they cant use this parameter, and without this parameter, this API will always fail when executed through Graph explorer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32452cd3-5367-ff92-6ea4-e38cb42eb78d
* Version Independent ID: 4a2fb87d-a54f-bb9d-61a5-09cf411ff2a5
* Content: [Update schemaExtension - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/schemaextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/schemaextension-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Sorry for the late response.  The `owner` property can only be set on Creation and is immutable after that. Either it's set by the caller, or if not supplied, it's set to the appId of the calling app.  As it's immutable, it cannot be used in PATCH.  This is already noted in the documentation.
