### ISSUE TITLE
Groups' members count

### ISSUE THREAD

**Issue by ivanboscolo** [microsoftgraph/microsoft-graph-docs#6221]
Is it possible to obtain a count of the groups' members without actually expanding the members? $count is currently not supported for directoryObjects, but expanding the members can become quickly inefficient. Thank you for your feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c5cd62a-5325-aeda-c1ae-33b6157eb04c
* Version Independent ID: c9b14f46-af37-3520-450c-3ed4d5f54f46
* Content: [List groups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
&count API is still in Private Preview, so it's not documented. You can try this api to get count: beta/groups/{group-id}/members/$count?ConsistencyLevel=eventual 
This will return the number of members of the group. If you want to include the numbers of members of nested groups, simply replace members with transitiveMembers.

**Comment by nickbower** [comment]
I'm not sure the answer above works, even on the beta?
