### ISSUE TITLE
Estimate time on when the beta endpoints for applications and serviceprincipals will be stabilized

### ISSUE THREAD

**Issue by tucane** [microsoftgraph/microsoft-graph-docs#6232]
<!---
Thank you for helping us to improve the Microsoft Graph documentation.

It seems like applications and serviceprincipals endpoints are being actively worked on with some breaking changes. Is there an estimate timeline on when they're going to be stabilized?

**Comment by dkershaw10** [comment]
Application API is now GA (in v1.0), and as such is stable.  You should use that for all your production applications.  Service principal APIs will soon follow.  Please stay tuned on the changelog for any updates.
cc @sureshja

**Comment by davidmu1** [comment]
I don't think there is anything actionable on the issue. Closing.
