### ISSUE TITLE
these instructions are incorrect

### ISSUE THREAD

**Issue by elrod-johnson** [microsoftgraph/microsoft-graph-docs#6236]
"
**To associate an existing Azure subscription with your Office 365 account**
1. Log on to the Microsoft Azure portal with your existing Azure credentials (for example, your Microsoft ID such as user@live.com).
2. Select the Active Directory node, then select the Directory tab and, at the bottom of the screen, select New.
3. On the New menu, select Active Directory &gt; Directory &gt; Custom Create.
4. In Add directory, in the Directory dropdown box, select Use existing directory. Check I am ready to be signed out, and then select the check mark in the lower-right corner.
"
**NONE of these instructions are valid.** 
i don't know what this stuff is referring to, but it is most certainly NOT related to https://portal.azure.com/#home

justingden reported this one month ago. 
the page was edited two days ago (11/04/2019). 
**why wasn't this fixed then???**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a01567ae-17e0-58ab-efaf-e7fa982bd1a7
* Version Independent ID: 80560253-edc6-166c-d67e-112f479ba7a8
* Content: [Associate your Office 365 account with Azure AD to create and manage apps - Microsoft Graph](https://docs.microsoft.com/en-us/graph/associate-account#feedback)
* Content Source: [concepts/associate-account.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/associate-account.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@Lauragra can you confirm that this topic is a hold over from Office 365 APIs. Can we remove this? It is not required for Microsoft Graph. It is not in the TOC either.

@elrod-johnson your mother would be so proud. Mind your language.

**Comment by bhaskardhone** [comment]
I agree , this article is invalid

**Comment by Lauragra** [comment]
This has been fixed. Thanks.
