### ISSUE TITLE
GET /sites/{site-id}/pages  General exception while processing

### ISSUE THREAD

**Issue by babakdanyal** [microsoftgraph/microsoft-graph-docs#6238]
i have tried this endpoint in Graph explorer and getting this error
    "error": {
        "code": "generalException",
        "message": "General exception while processing",
        "innerError": {
            "request-id": "cf618829-0e77-4471-91fa-9b8c94d3f44b",
            "date": "2019-11-07T06:54:47"
        }
    }

/sites/{site-id} works but with /pages it returns error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0922533d-b396-4bd5-8258-7ce6f2a5b4b0
* Version Independent ID: d1719bc1-65aa-d4e6-24d1-524f35c4ee21
* Content: [List the pages in a site - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/sitepage-list?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/sitepage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/sitepage-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @rahmit
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dico** [comment]
I get the same error

**Comment by babakdanyal** [comment]
> I get the same error

You can try Http request if you are trying to get the Site Pages library of a site
![image](https://user-images.githubusercontent.com/11374923/75215690-aaa09780-57e5-11ea-8359-bd26c120b38b.png)

**Comment by JeremyKelley** [comment]
> I get the same error

What kind of site are you targeting to get the site pages?  The default root site seems to work fine in Graph Explorer, so need some more details.  Also please provide a Request ID and timestamp for a recent failing request.

**Comment by evildivine** [comment]
This happens about twice in a week ... for about half of hour for me .... any clues how to solve this ?
