### ISSUE TITLE
Setting the location in an event don't effective

### ISSUE THREAD

**Issue by dagexiongfeng** [microsoftgraph/microsoft-graph-docs#6242]
when l setting the location with email and name, it only displays the name in the calendar, the server does not accept or rejects the meeting request based on the free/busy schedule of the resource.but when l create a meeting in the calendar. the room l chose that can receive the message.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-gb/graph/api/user-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by arijit462** [comment]
You have to pass meeting room email id as attendee to get it booked

**Comment by dagexiongfeng** [comment]
So what's the use of locationEmailAddress?

**Comment by dagexiongfeng** [comment]
When I create a meeting with room information on outlook，why the messages I get through get event API on attendee have no room message.

**Comment by vrod9429** [comment]
@dagexiongfeng I am not sure I understand the question. Can you please rephrase your question?

**Comment by vrod9429** [comment]
Closing this issue since we have not received a response.
