### ISSUE TITLE
Is it possible to add 3rd Party Security Actions?

### ISSUE THREAD

**Issue by sravan-goud** [microsoftgraph/microsoft-graph-docs#6243]
Hi,

Is it possible to add custom 3rd party "Security Actions" to graph API. If yes, could you please point me to the docs. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 049153d3-d57f-055a-e5ee-b7c7723cc96a
* Version Independent ID: 007aaa19-31d5-b10c-62e1-c592582ef116
* Content: [securityAction resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/securityaction?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/securityaction.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/securityaction.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by preetikr** [comment]
Hi @sravan-goud - Not currently. What's your scenario? Please share details on what you are trying to do / commands and 3rd party actions you are trying to connect with. Thanks!

**Comment by preetikr** [comment]
Closing this due to no response - please reactivate with information requested if this is still needed. Thanks.
