### ISSUE TITLE
In beta API it is not possible to filter events by (iCal) UID

### ISSUE THREAD

**Issue by paulvt** [microsoftgraph/microsoft-graph-docs#6247]
The v1.0 API documentation mentions the `iCalUId` field for the `Event` object that can also be used to retrieve a specific event. For example, using the Graph Explorer:

Query: 
`GET https://graph.microsoft.com/v1.0/me/events?$filter=iCalUId eq '040000008200E00074C5B7101A82E00800000000BF7DFDB82DB1D3010000000000000000100000007E179DE3E9AA9C4DBB784CA0F90F0B86'`
Response body:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('48d31887-5fad-4d73-a9f5-3c356e68a038')/events",
    "value": [
        {
            "@odata.etag": "W/\"IiLKjG2I7E+Xv0+ys6MD0wAAtyemdQ==\"",
            "id": "AAMkAGVmMDEzMTM4LTZmYWUtNDdkNC1hMDZiLTU1OGY5OTZhYmY4OABGAAAAAAAiQ8W967B7TKBjgx9rVEURBwAiIsqMbYjsT5e-T7KzowPTAAAAAAENAAAiIsqMbYjsT5e-T7KzowPTAACNM9xPAAA=",
            "createdDateTime": "2018-03-01T07:20:13.7348518Z",
            "lastModifiedDateTime": "2018-05-05T03:15:32.4797256Z",
            ...
            "iCalUId": "040000008200E00074C5B7101A82E00800000000BF7DFDB82DB1D3010000000000000000100000007E179DE3E9AA9C4DBB784CA0F90F0B86",
           ...
       }
  ]
}
```

In pull request #3202 the field is renamed from `iCalUId` to `uid` for the beta API. However, this new field does not seem to be filterable and this is not mentioned in the documentation.

Query:
`GET https://graph.microsoft.com/beta/me/events?$filter=uid eq '040000008200E00074C5B7101A82E00800000000BF7DFDB82DB1D3010000000000000000100000007E179DE3E9AA9C4DBB784CA0F90F0B86'`
```
{
    "error": {
        "code": "UnsupportedEntityExpression",
        "message": "'x => (x.Uid == \"040000008200E00074C5B7101A82E00800000000BF7DFDB82DB1D3010000000000000000100000007E179DE3E9AA9C4DBB784CA0F90F0B86\")' is not a supported filter expression.",
        "innerError": {
            "request-id": "34c02e03-3004-4db8-9246-ecd6cc382ae8",
            "date": "2019-11-07T15:53:38"
        }
    }
}
```

This is probably a bug in the implementation, but I could not figure out where to file the report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b79e6c20-0ff8-d232-c734-2d606ea5acda
* Version Independent ID: da447d8b-6f50-027e-6d6f-46636eb7294b
* Content: [List events - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-list-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lpld** [comment]
+1 for this. This was a very convenient feature in v1.0. Is this going to be implemented in beta as well?

**Comment by yoxel** [comment]
+1 One of issues preventing our migrations from EWS to Graph API. In EWS we can easily query by clean_global_id (equivalent of uid in graph). Thanks

**Comment by Staja** [comment]
The new Microsoft Graph PowerShell module targets the beta API and this issue has prevented us from using it.

**Comment by johan-smits** [comment]
Is there a timeline or a site where changes are announced to get merged from beta to stable?

**Comment by angelgolfer-ms** [comment]
Hi @johan-smits , 
For recent changes that have been released, please see the [What's New](https://docs.microsoft.com/en-us/graph/whats-new-overview) highlights, with API-level details in the [changelog](https://docs.microsoft.com/en-us/graph/changelog).

 We are aware a roadmap is useful for planning. However, there isn't a Microsoft Graph roadmap to announce upcoming feature releases. Please feel free to search for this request in the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) site, vote for an existing submission that matches your needs, or enter a new one.

**Comment by angelgolfer-ms** [comment]
@Harini84 has provided a preview of what's coming up with the uid and iCalUId properties in beta and v1 respectively in this [blog post](https://developer.microsoft.com/en-us/office/blogs/microsoft-graph-calendar-events-icaluid-update/).

**Comment by Harini84** [comment]
iCalUId is being restored in Graph beta with its value to be as per industry definition as mentioned in the blog post. UId will be removed.

PR details:
https://o365exchange.visualstudio.com/O365%20Core/_git/Substrate/pullrequest/697836
