### ISSUE TITLE
What happens to a message's ID when its status changes from being a draft to being sent?

### ISSUE THREAD

**Issue by vishaldpatel** [microsoftgraph/microsoft-graph-docs#6250]
Hi there,
 We're trying to figure out the following:
 Let's say that I use the API to create a draft (either new message or a reply).
 This returns a Message object with an ID.
 I then subscribe to that ID.
 I then ask the API to send the Message.
 Does the Message's ID change when it gets moved from the Draft folder to the Sent folder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5312ce4-1dfa-0dd7-bfbb-4cbdd2172002
* Version Independent ID: e442026f-0fdf-83dc-70b4-8ad6a7cec8f9
* Content: [Automate creating, sending, and processing messages - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-create-send-messages#feedback)
* Content Source: [concepts/outlook-create-send-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-create-send-messages.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @vishaldpatel , when a message in the drafts folder is sent in Outlook, under the covers, a separate copy of the message is created in the Sent Items folder. So the ID of the message originally in the drafts folder and the ID of the message in the Sent Items folder are not and cannot technically be the same.

I have tried in PR #6280 to make this clearer in the docs, in the [v1](https://docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-1.0) and [beta](https://docs.microsoft.com/en-us/graph/api/resources/mail-api-overview?view=graph-rest-beta) version of the topic "Use the Outlook mail REST API". The doc update will be published some time in the next 24 hours. Thanks for your question!
