### ISSUE TITLE
Example HTTP Request Body does not work

### ISSUE THREAD

**Issue by haehnpt** [microsoftgraph/microsoft-graph-docs#6252]
The given HTTP request body does not work. It will return a `400 - Bad Request`. However, using the user representation of the request body from ["Create Channel > Create Private Channel"](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&tabs=http#example-2-create-private-channel-on-behalf-of-user) which is

```json
{
   "@odata.type":"#microsoft.graph.aadUserConversationMember",
   "user@odata.bind":"https://graph.microsoft.com/beta/users('{id}')",
   "roles":[]
}
```

the request will succeed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497ad1e7-5a61-731f-e0e9-75b5cb9336c8
* Version Independent ID: 776a8387-3525-7289-51bd-1232f58d283a
* Content: [Add conversationMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by haehnpt** [comment]
Sorry. There was a mistake. The quoted user representation is from "Create private channel" and not from "Update conversationMember".

**Comment by akashSharma2505** [comment]
Facing the same issue. But I couldn't get it with 
 "Create Channel > Create Private Channel" which is

{
"@odata.type":"#microsoft.graph.aadUserConversationMember",
"user@odata.bind":"https://graph.microsoft.com/beta/users('{id}')",
"roles":[]
}

the request will succeed.

**Comment by menfra** [comment]
Hi the class AadConversationMember does not exist in Beta or am I missing something.

**Comment by haehnpt** [comment]
@menfra `AadConversationMember` does not exist but `AadUserConversationMember` does. 

See: https://docs.microsoft.com/de-de/graph/api/resources/aaduserconversationmember?view=graph-rest-beta

**Comment by leeford** [comment]
I created a PR and corrected the example. I think this can now be closed?

**Comment by maxali** [comment]
@leeford `aadUserConversationMember` will not work. Could you change it to `AadUserConversationMember` as in `PascalCase`.

```
{
  "@odata.type":"#microsoft.graph.AadUserConversationMember",
  "user@odata.bind":"https://graph.microsoft.com/beta/users('{id}')",
  "roles":[]
}
```
