### ISSUE TITLE
Add an example for updating a group specific setting

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#6253]
Based on a support case, let's add another example for the 2nd pattern:
PATCH /groups/{id}/settings/{id}

Customer was confused about the 2 ids and what they are for...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de1d3c0-ff82-f955-15d4-ffe99717d93a
* Version Independent ID: 0d541fbf-4acc-31a7-62d7-0855b0774362
* Content: [Update a group setting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/groupsetting-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/groupsetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/groupsetting-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by johnnycardy** [comment]
The second pattern isn't as it says it is. It's a POST, and not a PATCH. A PATCH request is rejected with an error. Also, the supplied pattern is `/groups/{id}/settings/{id}`. The second id shouldn't be there - it should be `POST /groups/{id}/settings'

**Comment by marekbuban** [comment]
The pattern is right. First {id} is ID of a group, second {id} is ID of a group settings. Each setting applied to specific group has unique ID.

**Comment by davidmu1** [comment]
Added a sentence to describe the different Ids.
