### ISSUE TITLE
How to delete a contact's photo

### ISSUE THREAD

**Issue by krastins-zz** [microsoftgraph/microsoft-graph-docs#6255]
I see that there are methods to delete a user's or group's photos https://docs.microsoft.com/en-us/graph/api/photo-delete?view=graph-rest-1.0&tabs=http, but it seems impossible to delete a contact's photo. Could you please provide a method to delete a contact's profile photo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilephoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@kevinbellinger are you now the goto for Profile Photos as you own the Profile API?

**Comment by cmparth** [comment]
Can you elaborate a bit more. I am also facing a similar problem while deleting a contact's photo.
Request: 'DELETE https://graph.microsoft.com/v1.0/me/contactFolders/{folder_id}/contacts/{contact_id}/photo'

Response: `{
  "error": {
    "code": "ErrorInvalidRequest",
    "message": "The OData request is not supported.",
    "innerError": {
      "request-id": "073d5301-cc00-407b-a129-3494129eae02",
      "date": "2019-12-09T13:10:47"
    }
  }
}`

**Comment by niconapo** [comment]
Hey there

The issue is still there, do you know when it can be fixed?

**Comment by kevinbellinger** [comment]
We have a design change request filed for this. There is currently no ETA for surfacing the capabilities on MS Graph. 

I'll come back in the next few weeks with some more information.

**Comment by niconapo** [comment]
Hello @kevinbellinger,

Do you have any news please?

Thanks

**Comment by DougChandler** [comment]
I would also like to know when there will be a delete user photo option via the API?

**Comment by PeterChencha** [comment]
Hello @krastins-zz @niconapo @DougChandler thanks for reaching out. At the moment this feature is currently not supported, as mentioned earlier we have a design change request to address this though we do not have an ETA for surfacing this capability on MS graph.
