### ISSUE TITLE
is there an API to add a connector to a channel in Teams?

### ISSUE THREAD

**Issue by gscott** [microsoftgraph/microsoft-graph-docs#6257]
I'd like to use the Graphi API to provision a channel and pre-configure an incoming webhook.  I have no problem provisioning the channel but can't figure out where I would configure a connector.  Is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5463d788-8e29-ca0a-5490-93506ff1ec80
* Version Independent ID: 1e7ca228-0b9f-beb1-d61f-7f1fdff50008
* Content: [Use the Microsoft Graph API to work with Microsoft Teams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teams-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by matthewjohnward** [comment]
Any update on this one?

**Comment by braidenstiller** [comment]
Also looking for this functionality. Any updates on this?
Have tried using the /installedApps endpoint for a team but it doesn't seem to work.

https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-add?view=graph-rest-1.0&tabs=http

**Comment by nkramer** [comment]
No, there is not.
