### ISSUE TITLE
Retrieve deleted channels

### ISSUE THREAD

**Issue by erangeigerShield** [microsoftgraph/microsoft-graph-docs#6265]
It seems that the response doesn't include deleted channels.
Is it possible to retrieve also a list of deleted channels?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc7bd1a-6210-6010-c9ff-4245c342b20a
* Version Independent ID: e667c977-60ef-a81d-e94b-7eed5061b2c7
* Content: [List channels - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abbodh** [comment]
+ 1. I am also looking for a way to know the list of deleted private channels.

**Comment by aprilsky85** [comment]
+1

**Comment by AwakeGitten** [comment]
+1

**Comment by anandab-gt** [comment]
There is no way to fetch list of deleted channels once it is deleted.

**Comment by anandab-gt** [comment]
closing this issue, in case you feel your problem is not solved either reopen this issue or create a new issue.
