### ISSUE TITLE
Get 500 error while deleting calendar via Graph API for one specific account

### ISSUE THREAD

**Issue by jianweiSun** [microsoftgraph/microsoft-graph-docs#6266]
While I was trying to delete a calendar via Graph API through `DELETE /me/calendars/{id}` endpoint. This following error response always happens for one of my accounts.
```
{u'error': {u'code': u'ErrorInternalServerError',
  u'innerError': {u'date': u'2019-11-04T07:13:06',
   u'request-id': u'72ea3226-fab2-4300-af56-6b116ec03a5f'},
  u'message': u'An internal server error occurred. The operation failed.'}}
```
Do you have any suggestions? Or are there any ways to get more error details via the `request-id` in the error response that can help me identify the root cause?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc31ef78-637b-a0f1-392c-35f525201765
* Version Independent ID: 9a865e0f-8e2a-92c7-26b0-ae5b4268c0a6
* Content: [Delete calendar - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/calendar-delete?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/calendar-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/calendar-delete.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mtwelve** [comment]
I'm also seeing a generic error when trying to delete specific calendars. Have raised an issue on the Get method - https://docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-beta&tabs=http

**Comment by angelgolfer-ms** [comment]
Hi @jianweiSun , if you haven't found an answer to your code question yet, may I suggest you post your question on stackoverflow and tag it with "microsoftgraph" please? 
The GitHub issues site is for documentation issues and few product side folks monitor questions on this site. If it turns out there is something lacking in the docs, feel free to reopen this GitHub issue. Thank you for your support!
