### ISSUE TITLE
Are there plans to implement the group: renew API call to the beta Graph API?

### ISSUE THREAD

**Issue by tfrancois** [microsoftgraph/microsoft-graph-docs#6267]
Currently, the group: renew API method is only visible or documented for the v1.0 Microsoft Graph Azure AD API.  Are there plans for this to be ported or supported for the beta version of the API?  Please advise.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f031d83c-aa02-de48-82dc-d6980c1f4399
* Version Independent ID: c741c55b-f20b-9786-4f00-a73ddcf95611
* Content: [group: renew - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-renew?view=graph-rest-1.0&tabs=http&viewFallbackFrom=graph-rest-beta)
* Content Source: [api-reference/v1.0/api/group-renew.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-renew.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
APIs are not typically ported backwards. But, any future API plans can't be discussed here. This forum is for addressing issues with the documentation of the API on the page referenced in this issue. No change identified for the page. Closing the issue.
