### ISSUE TITLE
signInActivity NOT available on BETA endpoints

### ISSUE THREAD

**Issue by pregoli** [microsoftgraph/microsoft-graph-docs#6275]
Hi,
It looks like the "signInActivity" property is not available for BETA version.
Following it's the query and the response from Ms Graph Explorer:

Query:
https://graph.microsoft.com/beta/users/?Select=signInActivity

Response
{
    "error": {
        "code": "NotImplemented",
        "message": "This operation target is not yet supported.",
        "innerError": {
            "request-id": "6b7d3762-e327-490b-8fd3-493f56ad8659",
            "date": "2019-11-11T15:43:05"
        }
    }
}

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 8a0f258b-b61e-72a2-0caf-d9b7fff5857d
* Version Independent ID: 90c2edf2-51ee-6bab-84a6-3710a3f0ccd2
* Content: [signInActivity resource type - Microsoft Graph beta](https://docs.microsoft.com/it-it/graph/api/resources/signinactivity?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signinactivity.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by pregoli** [comment]
Hi @davidmu1 ,
Any news? 
It still not working.

**Comment by rmmiles** [comment]
same here, not working

**Comment by berviantoleo** [comment]
Hi @davidmu1 ,

I got this error when calling beta endpoint of users

```json
{
  "error": {
    "code": "UnknownError",
    "message": "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-size:1.7em;margin:0;color:#CC0000;} \r\nh3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} \r\n#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;\r\nbackground-color:#555555;}\r\n#content{margin:0 0 0 2%;position:relative;}\r\n.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}\r\n-->\r\n</style>\r\n</head>\r\n<body>\r\n<div id=\"header\"><h1>Server Error</h1></div>\r\n<div id=\"content\">\r\n <div class=\"content-container\"><fieldset>\r\n  <h2>404 - File or directory not found.</h2>\r\n  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>\r\n </fieldset></div>\r\n</div>\r\n</body>\r\n</html>\r\n",
    "innerError": {
      "request-id": "fe1c8eaa-5c0d-4233-9042-229e3033ad7f",
      "date": "2020-02-17T03:50:58"
    }
  }
}
```

**Comment by dkershaw10** [comment]
Yeah - the docs were prematurely released.  It is working now (at least listing users with their signInActivity).  Same call to /me doesn't work though.

**Comment by davidmu1** [comment]
As Dan suggested, the query https://graph.microsoft.com/beta/users?select=signInActivity is now working. No change required to this article. Closing this issue.
