### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PhilPJL** [microsoftgraph/microsoft-graph-docs#6276]
var mailFolder = new MailFolder

should be 

var mailFolder = new MailSearchFolder

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e889ecb-a564-06e4-8e48-912c022c923a
* Version Independent ID: 943e6534-cf03-c606-dd84-61cb292e7816
* Content: [Create mailSearchFolder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/mailsearchfolder-post?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/mailsearchfolder-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/mailsearchfolder-post.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
@JarbasHorst   Thank you for the PR to fix this issue.  However, we autogenerate these code snippets, so unless we fix the generator, the next update will overwrite your changes.  I have opened an issue in the generator project to track this.

**Comment by JarbasHorst** [comment]
Hi @darrelmiller, let me know if the generator is open source and I can fix it there as well.
