### ISSUE TITLE
Example needs to be completed

### ISSUE THREAD

**Issue by jamesdschmidt** [microsoftgraph/microsoft-graph-docs#6279]
It looks like the example on the page has stubbed data. The data in the example should continue the example and narrative as found on the Get event document (https://docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&tabs=http).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1c68e-95bf-e8af-992e-cb790f8ca884
* Version Independent ID: 4072bab0-de7c-1f9f-05b9-6a7b4b6787f8
* Content: [Update event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-update.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by isvargasmsft** [comment]
Hello @jamesdschmidt, 

Do you mean the response? We usually display just a section of the response, to improve readability. Please see the note in the example:

> Note: The response object shown here might be shortened for readability.

Closing this issue as the answer was provided, please re-open it if I misunderstood the request.
