### ISSUE TITLE
Getting OData Request is not supported error

### ISSUE THREAD

**Issue by neetgupta7** [microsoftgraph/microsoft-graph-docs#6282]
Hello
While using below example to set out of office i m getting error.
https://docs.microsoft.com/en-us/graph/api/user-update-mailboxsettings?view=graph-rest-1.0&tabs=csharp

It says below-
{
  "error": {
    "code": "ErrorInvalidRequest",
    "message": "The OData request is not supported.",
    "innerError": {
      "request-id": "5dca32a4-898f-4d75-86e1-237370801ea6",
      "date": "2019-11-12T03:44:58"
    }
  }
}
Can you please help. Its urgent.

**Comment by jthake-msft** [comment]
This is not actually the place to submit issues on the service. This repo is for submitting feedback on documentation contents.
If you have premiere support you can use https://admin.microsoft.com to submit a support issue.
If you do not, you can post this on [https://www.stackoverflow.com/](https://stackoverflow.com/questions/tagged/microsoft-graph) using the `microsoft-graph` tag.
