### ISSUE TITLE
New date range limit has been introduced? "The range between the start and end dates is greater than the allowed range. Maximum number of days: 1825"

### ISSUE THREAD

**Issue by awildash-unily** [microsoftgraph/microsoft-graph-docs#6284]
Issue: For a number of years now we've been running a query to calendarView endpoint that has a 5 year span, e.g:

/v1.0/me/calendar/calendarView?$top=5&skip=0&startDateTime=2019-11-12T08:49:06Z&endDateTime=2024-11-12T08:49:06Z&$orderby=Start/DateTime

A few days ago this query stopped working with the error:

`"error": {​
        "code": "ErrorInvalidRequest",​
        "message": "Your request can't be completed. The range between the start and end dates is greater than the allowed range. Maximum number of days: 1825",​
        "innerError": {​
            "request-id": "f9698272-bc55-43b3-9c29-44810f2fc4cb",​
            "date": "2019-11-12T08:51:04"​
        }​
    }​`

1825 / 365 is 5 years which is what we're adding using .Nets AddYears, but unfortunately with leap days taken into account its 1827 days between the 2 dates above. So arguably the 5 year check (which this seems to be) should take leap years into account if the MS intention was for it to be a 5 year limit.

But this isnt mentioned in the calendarView docs as a limit so it would probably be good to add it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18fec655-72d2-4bdf-9201-ccfc37848e1e
* Version Independent ID: 63536b57-171d-f44f-97db-78afa8b499ae
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-calendarview.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
This is not actually the place to submit issues on the service. This repo is for submitting feedback on documentation contents.
If you have premiere support you can use https://admin.microsoft.com to submit a support issue.
If you do not, you can post this on [https://www.stackoverflow.com/](https://stackoverflow.com/questions/tagged/microsoft-graph) using the `microsoft-graph` tag.

**Comment by awildash-unily** [comment]
@jthake-msft with all due respect I do say can this new date range be added to the docs. Are you saying it's a bug then? If not can you point me to where this limit is mentioned in the docs?

Thanks.
