### ISSUE TITLE
Looks like you may not have the permissions for this call

### ISSUE THREAD

**Issue by rodrigoguariento** [microsoftgraph/microsoft-graph-docs#6288]
I'm using https://graph.microsoft.com/beta/app/onlineMeetings to POST the following Request Body in Microsoft Graph Explorer:
```
{
  "isBroadcast": "false",
  "startDateTime":"2019-11-12T12:00:00.0000000-03:00",
  "endDateTime":"2019-09-09T13:00:00.0000000-03:00",
  "subject":"Test Meeting",
  "participants": {
    "organizer": {
      "identity": {
        "user": {
          "id": "6ae3125b-2ce6-4031-92b4-78106e103693"
        }
      }
    }
  }
}
```

After **Run Query** I got the following in the Response Preview tab:
```
{
    "error": {
        "code": "Forbidden",
        "message": "",
        "innerError": {
            "request-id": "d5f5309d-7e8b-4966-8cb6-a65ebdc27585",
            "date": "2019-11-12T13:20:57"
        }
    }
}
```

Why? 

When I click in **modify your permissions** as suggested, I have a list with no **OnlineMeetings.ReadWrite (Delegated)** and no **OnlineMeetings.ReadWrite.All (Application)**. I'm joined to Office Developer Account with access to Admin Center and Azure Active Directory (I'm authenticated with my account too).

What I need to do to have no **Failure - Status Code 403** as response?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create online meeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
/app i.e. Application-based queries can't be tested with Graph explorer. Try it with /me/onlineMeeting and user delegated auth.
