### ISSUE TITLE
Wrong case for 'html'

### ISSUE THREAD

**Issue by mattlaabs** [microsoftgraph/microsoft-graph-docs#6291]
actual value is "html" not "HTML"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a80f4aa-dda6-079a-9e61-df611a2a7e99
* Version Independent ID: 77ea5bcc-08af-7d98-b7be-3b4d758857c4
* Content: [itemBody resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/itembody?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/itembody.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/itembody.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @sumurthy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
Thanks. This is fixed per PR #6304 and will go live today.

**Comment by ashoksubedi1** [comment]
When a person comments on planner task. Regular string comes as a Html. That is weird to me

**Comment by ashoksubedi1** [comment]
When I do a get request for a post the actual message comes as an HTML. Why are they not coming as text ?
