### ISSUE TITLE
Graph Beta - List Channel Messages Returns 403 "unknown Error"

### ISSUE THREAD

**Issue by stevegibbard** [microsoftgraph/microsoft-graph-docs#6292]
Issue:
Hi, I am following the documentation at: https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http for using the Graph API to retrieve a list of messages from a Teams channel.  Each step has worked (Get Team, Get Channels, Get specific Channel ID) until I try and send a request for the messages associated with a channel ID.

Sending:  https://graph.microsoft.com/beta/teams/{{TeamID}}/channels/{{ChannelID}}/messages
returns a 403 Forbidden Error with the following payload.
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "41be8x55-84x4-40b5-8933-1055x1c6e9xx",
      "date": "2019-11-12T14:50:13"
    }
  }
}

I have Group.Read.All permissions set (which according to the docs is enough) and I have checked authorisation token, Team IDs and channel IDs are correct but still no dice.

Interestingly if I try and use the Graph Explorer to send an example request for messages it also returns 403 Forbidden.

Can you advise please?
  

Article:

**Comment by anomepani** [comment]
If you are using app permission then you can't send message.
Posting message only supported using delegated permission.

**Comment by stevegibbard** [comment]
@anomepani Thanks. I wasn't trying to send a message I was using the API to retrieve a list of messages in the channel. However, I have been pointed to the [following page](https://docs.microsoft.com/en-us/graph/teams-protected-apis) which shows Access for List Channel Messages is protected and requires a request to Microsoft for Application permissions.  I will close this issue now as I failed to see the warning on the documentation page about this.
