### ISSUE TITLE
ThreatIndicators.Read.All missed

### ISSUE THREAD

**Issue by kastromatos** [microsoftgraph/microsoft-graph-docs#6293]
There is no info about "ThreatIndicators.Read.All", but Azure UI already provide such option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference?source=docs)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Thanks for raising this item. We are tracking it internally as part of a doc cleanup effort.

**Comment by FaithOmbongi** [comment]
Thank you @kastromatos for highlighting this issue. The permissions is now documented. Closing this issue.
