### ISSUE TITLE
otherMails type is incorrect in user resource description

### ISSUE THREAD

**Issue by thesofakillers** [microsoftgraph/microsoft-graph-docs#6294]
I believe the type for otherMails should say "String collection" rather than just "String", since it effectively is described as a list of strings. This should then be reflected in the JSON representation lower in the page, where it's listed as `"string"` rather tha `["string"]`. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
This is now fixed.  Thanks for filing.
