### ISSUE TITLE
https://graph.microsoft.com/beta/teams/**/channels/**/messages/delta?$filter=lastModifiedDateTime+gt+2019-11-01T09:32:18Z

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#6296]
I tried this query and it gives me a response, but if I switch "lastModifiedDateTime" to "createdDateTime" it gives me an invalid filter. I know nobody has tried this query because it was accidentally working for me. My response to the above API treats "lastModifiedDateTime" to "createdDateTime", the response will be all the messages that were"created" after November 1. I really need this API for incremental changes, can somebody explain if it is ok to use this API for my prod app.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab355c92-69ff-7b13-964a-9c3bc495e417
* Version Independent ID: 158fb540-d830-19fb-9c76-9db9a78c32fe
* Content: [Get incremental changes to messages in a folder - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-messages)
* Content Source: [concepts/delta-query-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-messages.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ashoksubedi1** [comment]
{
    "error": {
        "code": "BadRequest",
        "message": "The entity property 'createdDateTime' is not allowed in $filter query.",
        "innerError": {
            "request-id": "6***46-ceb7-****-*******",
            "date": "2019-11-12T23:31:09"
        }
    }
}

**Comment by nkramer** [comment]
We support filtering on only a very limited set of properties.

**Comment by nkramer** [comment]
We'd like to add more in the future but that's where it is now.
