### ISSUE TITLE
Does the getSchedule API call work with Hybrid Deployments?

### ISSUE THREAD

**Issue by bajzat** [microsoftgraph/microsoft-graph-docs#6303]
Hi!

I tried the getSchedule API call in our Hybrid Deployment(Exchange 2016 CU 12) but I got the following error: 

`{
    "error": {
        "code": "RequestBroker-ParseUri",
        "message": "Resource not found for the segment 'Microsoft.OutlookServices.getSchedule'. REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com/.",
        "innerError": {
            "request-id": "cdfbb3a6-c470-4c98-a90e-ac8f3035a03a",
            "date": "2019-11-13T10:16:05"
        }
    }
}`

According to the Hybrid Deployment documentation, the minimum required CU version is 3 for Exchange 2016 to be able to provide the v1.0 set of APIs (Users, Calendars, Contacts). Is that possible we need a newer version of CU than 12 to have the getSchedule API call in our environment? Or this API call is not supported in Hybrid Deployments at all?

Best Regards

Tamas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72df543-3deb-151b-f634-608a04881289
* Version Independent ID: 3db73371-c6ee-2add-9d51-223e3f1f82e4
* Content: [calendar: getSchedule - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-getschedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-getschedule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
@angelgolfer-ms 
Kindly assign getsSchedule issues to Will Holmes or Jaya Matthew.

**Comment by avin3sh** [comment]
Can someone please confirm this ? @Tariq-Sharif
