### ISSUE TITLE
Graph API "MailboxSettings"

### ISSUE THREAD

**Issue by digitalhuman** [microsoftgraph/microsoft-graph-docs#6305]
Issue: 

https://graph.microsoft.com/v1.0/users/secretUserPrincipleID/mailboxsettings
https://graph.microsoft.com/v1.0/secretUserPrincipleId/mailboxsettings

Returns

"Resource not Found"

```
{
  "error": {
    "code": "ResourceNotFound",
    "message": "Resource could not be discovered.",
    "innerError": {
      "request-id": "4b9087ce-07fe-4afc-930e-1d7499ae3c13",
      "date": "2019-11-13T17:17:50"
    }
  }
}
```

```
{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'mailboxsettings'.",
    "innerError": {
      "request-id": "bf3a19cb-9326-4109-814d-fc26a670d201",
      "date": "2019-11-13T17:25:38"
    }
  }
}
```

Whilst https://developer.microsoft.com/en-us/graph/graph-explorer  Actually shows mailbox settings for:

https://graph.microsoft.com/v1.0/me/mailboxsettings

**Comment by digitalhuman** [comment]
Ok, so apparently /beta/ gives me what I need. Still issues:

https://graph.microsoft.com/beta/users/MySecretUserPrincipleId/mailboxsettings

Now returns "MailboxSetting" returns:

```
{
  "error": {
    "code": "MailboxNotEnabledForRESTAPI",
    "message": "REST API is not yet supported for this mailbox.",
    "innerError": {
      "request-id": "fa89876e-3852-4ac7-af23-1966073f7653",
      "date": "2019-11-14T09:50:44"
    }
  }
}
```

**Comment by jasonjoh** [comment]
@digitalhuman those errors indicate that the mailbox owned by the user (`MySecretUserPrincipleId`) is not on Exchange Online. Your setup may be a hybrid on-premises setup.

**Comment by digitalhuman** [comment]
Well i treed with Outlook API, Office365 API, Exchange API, graph.Microsoft.com and graph.Windows.net
None of them give me MailboxSetting information. All return an error or audience not found, service not found or token signature invalid.

Any help would be very welcome

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jasonjoh** [comment]
Apologies, I should have been clearer :). You cannot use these APIs if your mailbox is not on Exchange Online. Can you confirm if the mailbox is on-premises or on Exchange Online?

**Comment by digitalhuman** [comment]
I have 1 office365 account and 1 Outlook.com account. Neither work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jthake-msft** [comment]
This is not actually the place to submit issues on the service. This repo is for submitting feedback on documentation contents.
If you have premiere support you can use https://admin.microsoft.com to submit a support issue.
If you do not, you can post this on [https://www.stackoverflow.com/](https://stackoverflow.com/questions/tagged/microsoft-graph) using the `microsoft-graph` tag.
