### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Semx11** [microsoftgraph/microsoft-graph-docs#6314]
First table, first row
`lisItem` should be `listItem`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e00d6372-f1f5-58ea-0fdf-90496cc68abf
* Version Independent ID: 82a66768-cf64-369a-944f-fb6c282b340b
* Content: [listItem resource - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/listitem?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/listitem.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/listitem.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by Lauragra** [comment]
Thanks; I opened PR #6316 to fix this; we'll merge and publish today.

**Comment by Semx11** [comment]
@Lauragra I hate to be _that_ guy, but you misspelled "represents" in your change, you typed "Rrepresents"

**Comment by Lauragra** [comment]
LOL, sigh. I just opened a new PR to fix. Thanks!
