### ISSUE TITLE
Request a list calendars given a user id or userPrincipalName

### ISSUE THREAD

**Issue by Blackleones** [microsoftgraph/microsoft-graph-docs#6315]
Is it possible to execute an HTTP request "/users/{id | userPrincipalName}" using Microsoft.Graph C# library? 
I am looking through Microsoft Graph library but actually I don't discover any way 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4c513f-3430-6cad-ed4e-27f6a7a94f32
* Version Independent ID: 26070fca-f408-ea1f-0364-19ca324ed9ae
* Content: [List calendars - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-calendars.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@MIchaelMainer could you help here?

**Comment by jthake-msft** [comment]
I believe this should work fine as per the code snippet in the docs? 

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

```
var calendars = await graphClient.Me.Calendars
	.Request()
	.GetAsync();
```


https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=csharp#feedback

**Comment by Blackleones** [comment]
Thank you @jthake-msft  I solved my issues in this way

`
var calendars = await graphClient.users[{id | userPrincipalName}]. .... 
	.Request()
	.GetAsync();
`
