### ISSUE TITLE
Email is always blank on a new channel

### ISSUE THREAD

**Issue by allaboglaeva** [microsoftgraph/microsoft-graph-docs#6317]
When we create a new channel via graph the email is always blank. There isn't any documentation we can find that shows how to trigger the create email for a channel.

**Comment by Prithvi-MSFT** [comment]
Hi, When you create channel using graphi API the email field is null by default. This is the defualt behavior. 
You can refer response object of example 2 of below document.
https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http

Thanks
