### ISSUE TITLE
How does one send from a shared mail box

### ISSUE THREAD

**Issue by yobokkie** [microsoftgraph/microsoft-graph-docs#6326]
One thing that's not clear in the documentation is how to use the Mail.Send.Shared permission scope to send an email from a shared address. Our organisation has a shared administrative email address that needs to be used to send out all emails to clients. I am using /users/{id | userPrincipalName}/sendMail as the endpoint, where the ID is set to that of the shared mailbox, but when I do a test, it sends as if it came from my email address. How does one use the graph API to have the emails being sent as if they came from the shared inbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@svpsiva  is it possible to send from a shared mailbox?

**Comment by yobokkie** [comment]
I guess I assumed from the permission scope Mail.Send.Shared that there was a way to utilise this option somewhere?

**Comment by jasonjoh** [comment]
@yobokkie does this not work for you? https://docs.microsoft.com/graph/outlook-send-mail-from-other-user

**Comment by yobokkie** [comment]
@jasonjoh Ahh thank you! I didn't realise this needed to be set. That does work!
