### ISSUE TITLE
Add accessPackageResourceRoleScopes during Access Package creation

### ISSUE THREAD

**Issue by mylabonline** [microsoftgraph/microsoft-graph-docs#6328]
Is there a way to add the Resource Role Scope during the creation of the Access Package?

In the Azure Portal I can add the Group Resource but I cannot via the API. This is critical for any automation.

I tried to build the body into the POST (accessPackageResourceRoleScopes and accessPackageResourceRole) but I get error DuplicateAccessPackage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb0e188e-58a7-99f6-4d3c-e348453870d8
* Version Independent ID: e7ecf449-32aa-f5e1-4329-5db547b7bfb6
* Content: [Create accessPackageAssignmentPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/accesspackageassignmentpolicy-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accesspackageassignmentpolicy-post.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Not yet at the time of the access package creation, but we writing the documentation for adding a resource role to an access package, which can be done after an access package has been created.  The work in progress can be found at https://github.com/microsoftgraph/microsoft-graph-docs/pull/6172/files

**Comment by mylabonline** [comment]
Thats great! I looked at the documentation and built the JSON payload for /accessPackageResourceRoleScopes but I get an error ResourceNotFound.

Is this live on the API yet?

**Comment by markwahl-msft** [comment]
It is in the process of coming in.  Did you already have your resource in the access package catalog? That is a prerequisite.   Then, retrieve the accessPackageResources from the catalog, e.g., with accessPackageCatalogs/CATALOGID?$expand=accessPackageResources . Assuming for simplicity the resource is a group and you want the member role, the POST payload for the access package's resource role scope would resemble 
`{
 "accessPackageResourceRole":{
   "originId":"Member_ORIGINID",
   "displayName":"Member",
   "originSystem":"AadGroup",
   "accessPackageResource":{
            --THE RESOURCE --
        }
 },
 "accessPackageResourceScope":{
 "originId": "ORIGINID","originSystem": "AadGroup"
 }
}`

**Comment by mylabonline** [comment]
Yup that did the trick - I didnt have the Resource already added in the Catalog. I also found the POST reference for creating a new Resource in the Catalog (/accessPackageResourceRequests) But I am getting error "InternalServiceError"

I will keep checking... maybe this API isnt available yet? 

Thanks for your help Mark... I have this almost fully automated now. just need the /accessPackageResourceRequests to create the initial resource.

**Comment by DebashisChoudhury-MSFT** [comment]
@mylabonline - are you operating as a Admin user (GA) or a delegated catalog owner?

**Comment by mylabonline** [comment]
I am trying to accomplish this using a delegated catalog owner. 

Does this only work using a delegated GA account?

**Comment by DebashisChoudhury-MSFT** [comment]
@mylabonline - For now continue to use (GA) for resource onboarding using MS Graph API, we are working on the delegated scenario.

**Comment by mylabonline** [comment]
I testing using a GA and User Administrator and both roles work, I guess using the UA Role would be "least privilege” but not optimal.

Are you also working on non-delegated? Allowing for Application Only permission type?

Thanks.

**Comment by DebashisChoudhury-MSFT** [comment]
@mylabonline 
We are working on non-delegated, App Only scenarios, but that will take a bit of time.

Meanwhile for Delegated Non GA User scenario, I understand you are trying to onboard a Group to catalog. In your scenario, is the user a Group owner?

**Comment by markwahl-msft** [comment]
The article updates in the pull request described above are for delegated permissions when an application has a token for a administrator user.  Application permissions, where there is no user token, is not currently provided in Microsoft Graph for this scenario.

**Comment by aronfelipe** [comment]
What means Invalid Model on 403 response?

**Comment by aronfelipe** [comment]
What means Invalid Model on 400 response?

**Comment by mylabonline** [comment]
I was also getting an Invalid Model - It seems some of the properties in the Body Payload has changed. 

For me, it was adding acceptRequests = $true in the requestorSettings and removing isEnabled from the accessPackageAssignmentPolicies object.

Example

requestorSettings = [PSCustomObject]@{
   scopeType = 'SpecificDirectorySubjects'
   acceptRequests = $true
   allowedRequestors = @(                
     [PSCustomObject]@{
     '@odata.type' = '#microsoft.graph.groupMembers'
     displayName = $($RequestorGroupName)
     objectId = $($RequestorGroupId)
     isBackup = $true
     }
   )
   requestorScope = @(
    )
  }

**Comment by markwahl-msft** [comment]
This article covers adding a resource role to an access package:  https://docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&tabs=http

**Comment by brownm5** [comment]
Good day folks....  I am new here so please forgive any faux pas
I am trying to automate an Identity governance solution using ms graph API and I have succeeded in creating catalogs, creating access packages in those catalogs and attaching policies to those access packages.  I see that a resource must already exist in a catalog in order to add that resource to an access package.  
I cannot find any documentation on how to add a resource to a catalog using an API.  Can someone please point me to any documentation.  Or, maybe provide an example of the JSON object and URI?
All assistance appreciated kindly.

**Comment by DebashisChoudhury-MSFT** [comment]
https://docs.microsoft.com/en-us/graph/api/resources/accesspackageresourcerequest?view=graph-rest-beta

**Comment by markwahl-msft** [comment]
There is an example of the request payload to bring a resource (a group, app, site) into an access package catalog in https://docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&tabs=http

**Comment by brownm5** [comment]
Gentlemen....thank you kindly

**Comment by brownm5** [comment]
I was able to add an AadGroup to a catalog.  But I am having problems with Adding an application.  The error message:
"code": "ArgumentException",
        "message": "Requested value 'Application' was not found.",
        "innerError": {
            "request-id": "992f62ec-c5bb-47cb-9b5e-f0a141b5fc6b",
            "date": "2020-04-01T14:36:31"

I have reviewed this doc:  https://github.com/microsoftgraph/microsoft-graph-docs/blob/3961598a89b7e33c2629b39d7065d87b71a8bdde/api-reference/beta/resources/accesspackageresource.md

And it says that originSystem property is either "AadGroup" or "SharePointOnline". Neither of which apply.  And as the error says "Application" doesn't work.
Am I missing some documentation?
Thank you in advance for your time

**Comment by brownm5** [comment]
Never mind Gentlemen ....i found my information.  Thx again

**Comment by brownm5** [comment]
Ah! forgot....if any one else is looking.  Here is JSON post to add an Enterprise Application to a catalog:
{
    "catalogId":  "{catalog ID}",
    "requestType":  "AdminAdd",
    "justification":  "",
    "accessPackageResource":  {
            "displayName": "DataDog"
            "description": "AppId: {application ID}"
            "url": "https://myapps.microsoft.com/cdsmode2.onmicrosoft.com/signin/{application displayName}/{application ID}/
            "resourceType": "Application",
            "originId": "{Application ObjectId}"
            "originSystem": "AadApplication"
                              }
}

**Comment by brownm5** [comment]
Hello 
I hope you can help one more time.  I am trying to accessPackageResourceRoleScope.  I am getting an invalid object error.  I have seen the documentation @:
 https://docs.microsoft.com/en-us/graph/api/accesspackage-post-accesspackageresourcerolescopes?view=graph-rest-beta&tabs=http
The body i am trying to post looks correct.  Can anyone see what i am doing wrong.  Is there any way of determining more specific error information.  Below is the body I am trying to post:

{
    "accessPackageResourceRole":  {
                                      "originID":  "Member_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                      "displayName":  "Member",
                                      "originSystem":  "AadGroup",
                                      "accessPackageResource":  {
                                                                    "id":  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                                                    "resourceType":  "Security Group",
                                                                    "originId":  "{
    "accessPackageResourceRole":  {
                                      "originID":  "Member_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                      "displayName":  "Member",
                                      "originSystem":  "AadGroup",
                                      "accessPackageResource":  {
                                                                    "id":  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                                                    "resourceType":  "Security Group",
                                                                    "originId":  "189490bd-e31d-4f51-bfd8-96f13676e325",
                                                                    "originSystem":  "AadGroup"
                                                                }
                                  },
    "accessPackageResourceScope":  {
                                       "originId":  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                       "originSystem":  "AadGroup"
                                   }
}",
                                                                    "originSystem":  "AadGroup"
                                                                }
                                  },
    "accessPackageResourceScope":  {
                                       "originId":  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                       "originSystem":  "AadGroup"
                                   }
}


Thank you in advance for any assistance you can provide

**Comment by markwahl-msft** [comment]
The body you included in your comment does not appear to be a valid request. In particular from line 9,
```
"originId": "{
```
through line 25,
```
}",
```
I am not sure what you are including as the value of originId?  In the example shown in the documentation, the `originId` property within the `accessPackageResource` has as a value a simple GUID. The article [accessPackageResource](https://docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta) states that `originId` property on this object is the unique identifier of the resource in the origin system. In the case of an Azure AD group, this is the identifier of the group.

**Comment by brownm5** [comment]
I corrected and still got the same error msg.   Thank you for your indulgence..... your time is appreciated

{
    "accessPackageResourceRole":  {
                                      "originID":  "Member_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                      "displayName":  "Member",
                                      "originSystem":  "AadGroup",
                                      "accessPackageResource":  {
                                                                    "id":  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                                                    "resourceType":  "Security Group",
                                                                    "originId":  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                                                    "originSystem":  "AadGroup"
                                                                }
                                  },
    "accessPackageResourceScope":  {
                                       "originId":  "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
                                       "originSystem":  "AadGroup"
                                   }
}

**Comment by markwahl-msft** [comment]
It wasn't clear what role type you're trying to add, and which object's GUID as they're all x'ed out.  Here's a example for a security group.  

Suppose you have a catalog, whose GUID is WWWW, an access package whose GUID is XXXX, and a security group whose GUID is YYYY.

So first you would have requested to add the security group as a new resource in the catalog,

````
POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageResourceRequests

{
  "catalogId":"WWWW",
  "requestType": "AdminAdd",
  "justification": "",
  "accessPackageResource": {
     "displayName": "G added",
     "resourceType": "Security Group",
     "originId": "YYYY",
     "originSystem": "AadGroup"
  }
}
````
followed by 
````

GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageCatalogs/WWWW/accessPackageResources
````
to see the access package resource that was created.  Let's say the access package resource that Azure AD entitlement management created for that group and returned in the GET response has ID ZZZZ.

Then you could use
````

GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageCatalogs/WWWW/accessPackageResourceRoles?$filter=(originSystem+eq+%27AadGroup%27+and+accessPackageResource/id+eq+%27ZZZZ%27)&$expand=accessPackageResource
````
to see the resource roles, like owner and member.

To add that to the access package, you'd send
````

POST https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/XXXX/accessPackageResourceRoleScopes

{
  "accessPackageResourceRole":{
    "originId":"Member_YYYY",
    "displayName":"Member",
    "originSystem":"AadGroup",
    "accessPackageResource":{"id":"ZZZZ","resourceType":"Security Group","originId":"YYYY","originSystem":"AadGroup"}
  },
 "accessPackageResourceScope":{
   "originId":"YYYY","originSystem":"AadGroup"
 }
}
````
and could confirm the resource role scope was present on the access package afterward with 

````
GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/XXXX?$expand=accessPackageResourceRoleScopes
````

**Comment by brownm5** [comment]
Mark...   I took your POST and plugged in the correct GUIDs and it worked like a charm.  When i generate the JSON post via PowerShell.  Invalid model.   Below is the script and below that is a side by side comparison with your JSON POST (top) and my JSON POST (bottom).  Is there something I don't know about how PowerShell converts to JSON?  (I tried to compress the JSON format to remove the pretty print  to no affect.)  Or am I doing something wrong with embedding one pscustomobject inside another?
As always ....your time is very much appreciated :-)


************begin script************

    $AWSaccessPackageResource = [pscustomobject]@{
                                            id=$APGroupResourceRequestId;
                                            resourceType="Security Group";
                                            originId=$GroupObjectID;
                                            originSystem="AadGroup"
                                            }

    $AWSRoleGroupResourceRole = [pscustomobject]@{
                                            originID="Member_$GroupObjectID";
                                            displayName="Member";
                                            originSystem="AadGroup";
                                            accessPackageResource=$AWSaccessPackageResource
                                            }

    $AWSRoleGroupResourceScope = [pscustomobject]@{
                                            originId=$GroupObjectID;
                                            originSystem="AadGroup"
                                            }
    $accessPackageResourcesBodyObj = [pscustomobject]@{
                            accessPackageResourceRole=$AWSRoleGroupResourceRole;
                            accessPackageResourceScope=$AWSRoleGroupResourceScope
                            }
    $accessPackageResourcesBody = $accessPackageResourcesBodyObj|ConvertTo-Json -Depth 10

*************end script*************

![image](https://user-images.githubusercontent.com/62963406/79794303-a4c3c000-8317-11ea-87d3-96e4b5ed94dd.png)

**Comment by markwahl-msft** [comment]
Could you check the case of characters property names in your script match those of the API. In particular, I believe you have in the resource role one occurence of originID= instead of originId=

**Comment by brownm5** [comment]
Thank you very much ....one of these days I am going to learn how to type.  AadGroups are added ....   working on AadApplication now. On line 3 of my json post do I change 
Member_yyyy
to
User_yyyy?

**Comment by brownm5** [comment]
I am trying to add an enterprise application as i stated in my last post and it returns a "role not found error".  Using your pattern  (XXXX, YYYY,  WWWW and ZZZZ) Am i submitting the post in the right format.  Is there more complete documentation anywhere?
As always thank you in advance for your time.

Using Azure Powershell i get the following info for my application
Get-AzureADApplication -SearchString "AvxVPN-app01d1"
ObjectId                             AppId                                DisplayName   
--------                             -----                                -----------   
61ddd29f-3296-46ef-9b6f-806756ec25c0 dac41a00-361f-430d-97d7-2a183db40266 AvxVPN-app01d1

Get-AzureADServicePrincipal -SearchString "AvxVPN-app01d1"
ObjectId                             AppId                                DisplayName   
--------                             -----                                -----------   
948593b2-70aa-4075-a089-09d13844cc8b dac41a00-361f-430d-97d7-2a183db40266 AvxVPN-app01d1

Using the graph API
https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageCatalogs/ba23852b-38dc-4563-89cb-2df96c78906a/accessPackageResources
Get list of resource in Catalog WWWW returns:

AvxVPN-app01d1                 c32d6cef-c825-406f-a6cc-5daf2684862d


Catalog = WWWW = ba23852b-38dc-4563-89cb-2df96c78906a
AccessPackage = XXXX = da6c43d0-38c0-4b8a-9085-9be268216b0b
AadApplication = YYYY = (AppId or ServicePrincipal ObjectID or Application ObjectID )

accessPackageResource = ZZZZ = c32d6cef-c825-406f-a6cc-5daf2684862d


{
  "accessPackageResourceRole":{
    "originId":"User_YYYY",
    "displayName":"User",
    "originSystem":"AadApplication",
    "accessPackageResource":{"id":"ZZZZ","resourceType":"Security Group","originId":"YYYY","originSystem":"AadApplication"}
  },
 "accessPackageResourceScope":{
   "originId":"YYYY","originSystem":"AadApplication"
 }
}
