### ISSUE TITLE
externalUserState and externalUserStateChangeDateTime added to attribute Schema

### ISSUE THREAD

**Issue by JefTek** [microsoftgraph/microsoft-graph-docs#6329]
Add the attributes below to the object schema
externalUserState of Null|PendingAcceptance|Accepted
externalUserStateChangeDateTime as the timedate the externalUserState last changed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
I don't think these properties are available in v1.0 yet.
