### ISSUE TITLE
Add member to Team (Group)

### ISSUE THREAD

**Issue by joicepj11** [microsoftgraph/microsoft-graph-docs#6338]
Issue: Not an issue. In Add member to the team, it would be better if you allow adding multiple users in the single API ( /groups/{id}/members/$ref)  call. if we need to add multiple users now, we need to call API multiple times.

Article: https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-beta&tabs=http

**Comment by jthake-msft** [comment]
This is not actually the place to submit feedback on the service. This repo is for submitting feedback on documentation contents.
To provide feedback, please go to [https://microsoftgraph.uservoice.com/](https://microsoftgraph.uservoice.com/).
