### ISSUE TITLE
Powershell - Not getting any response when creating team using Beta API

### ISSUE THREAD

**Issue by luca-suetterle** [microsoftgraph/microsoft-graph-docs#6339]
I'm using the /beta/teams endpoint to create teams based on templates due to this being much easier than creating teams using 1.0 API. This worked fine for quite a while, but now I'm not getting and response object with the Team's ID that I'd need. It creates the team properly, but without any response from the API. When I use other beta endpoints like /beta/app/onlineMeetings, it works just fine and I get a response.

**Comment by jthake-msft** [comment]
This is not actually the place to submit issues on the service. This repo is for submitting feedback on documentation contents.
If you have premiere support you can use https://admin.microsoft.com to submit a support issue.
If you do not, you can post this on https://www.stackoverflow.com/ using the [microsoft-graph] tag.
