### ISSUE TITLE
O365 groups can have securityEnabled = true

### ISSUE THREAD

**Issue by vacangus** [microsoftgraph/microsoft-graph-docs#6347]
The documentation has that securityEnabled for O365 groups is set to "false" but I do have some O365 groups where it is "true". Talked to a co-worker that told me "o365 groups are a super set of mail enabled security groups". The documentation should be updated, if that's the case. Please, let me know otherwise. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4f2e174-e263-4341-b121-b4b2d64bf989
* Version Independent ID: bcbfad43-66dd-2332-e2f5-30f483550b76
* Content: [Working with groups in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/groups-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/groups-overview.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by giveitaGo** [comment]
I've found that creating O365 groups via Azure portal results in securityEnabled: True. This is "documented" in this article on [Creating O365 groups using Graph API](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#request-body).

**Comment by davidmu1** [comment]
Changed the documentation to say that the value can be true or false.
