### ISSUE TITLE
How to get archived team installed Apps?

### ISSUE THREAD

**Issue by Aravindelumalai04** [microsoftgraph/microsoft-graph-docs#6351]
I have used this https://graph.microsoft.com/v1.0/teams/{Archived team-id}/installedApps?$expand=teamsAppDefinition. but it returns error as access denied "Entitlements cannot be retrieved because this team is archived."

**Comment by jthake-msft** [comment]
This is not actually the place to ask questions on how to do things. This repo is for submitting feedback on documentation contents.
If you have a question on how to do something on Microsoft Graph, please use  https://www.stackoverflow.com/ with the [microsoft-graph] tag.
