### ISSUE TITLE
delta function needed

### ISSUE THREAD

**Issue by mattlaabs** [microsoftgraph/microsoft-graph-docs#6353]
To develop a calendar sync adapter, a delta function for all calendar events is needed, as it is the only way to retrieve deleted events without full sync.
Currently, only the calendarView offers a delta function, but it includes every single occurrence of repeating events (and filtering is not possible). A calendar with many weekly events would thus bloat the initial sync with thousands of unnecessary event occurrences and also every modified recurring event would be expanded to all occurrences for subsequent sync operations.
This leaves two bad options at the moment: 
1) calendarView+delta: very slow initial sync, or 
2) calendar/events: slow full sync every time.

In case I am missing a third option, please explain how to do a complete bidirectional synchronization of a full calendar (without short time-range limits).

Alternatively, providing a filter option to remove events of type 'occurrence' from the calendarView would also be an option.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f65c9af5-60ee-0887-c63b-0dc338450ec3
* Version Independent ID: 2f7fef8b-4379-1847-751b-f53508ab7bae
* Content: [event: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-ca/graph/api/event-delta?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-delta.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mattlaabs** [comment]
Please also see the unresolved Stackoverflow question regarding tracking deleted occurrences here https://stackoverflow.com/questions/55641502/microsoft-graph-api-how-to-trace-deleted-calendar-event-occurrences#

**Comment by mattlaabs** [comment]
There is another stackoverflow with a user who gave up on implementing synchronization via graph here https://stackoverflow.com/questions/39518853/can-i-sync-calendar-events-with-the-microsoft-graph-api

**Comment by Surered** [comment]
> Please also see the unresolved Stackoverflow question regarding tracking deleted occurrences here https://stackoverflow.com/questions/55641502/microsoft-graph-api-how-to-trace-deleted-calendar-event-occurrences#

I am also facing the same issue. If any occurence is deleted in the recurring meeting, delta link returns all remaining occurrences. Instead of sharing the deleted occurence details server is publishing master event along with remaing all occurences

**Comment by whagoort** [comment]
@mattlaabs @Surered I am running into the same problem. There is already a long long very long outstanding uservoice topic. That one has opened in the year 2014.
I have added some more info in a comment.
Please give it some votes: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests
