### ISSUE TITLE
Fail to traverse MS-Graph "Unable to find target address" error

### ISSUE THREAD

**Issue by harmoniedev** [microsoftgraph/microsoft-graph-docs#6354]
Hi,

I'm trying to traverse MS-Graph using "odata.metadata=full".
when calling "https://graph.microsoft.com/v1.0/directoryObjects('%TEAM_ID%')/microsoft.graph.group/drive"
I receive the following error:
    "error": {
        "code": "InternalServerError",
        "message": "Unable to find target address",
        "innerError": {
            "request-id": "3e772ad3-7a70-4ff3-b415-615ff0e853f7",
            "date": "2019-11-19T14:17:30"
        }
    }
This query used to work until yesterday, please assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df2f8cde-557d-f7ef-a21e-99b075985df8
* Version Independent ID: e9a3cb1b-d2ac-6fbf-3f98-3336903b1ae2
* Content: [Access data and methods by navigating Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/traverse-the-graph#feedback)
* Content Source: [concepts/traverse-the-graph.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/traverse-the-graph.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by harmoniedev** [comment]
Any updates?

**Comment by JeremyKelley** [comment]
Apologies for the delay in follow up, is it possible to get fresh request IDs for this request so we can check logs?

**Comment by jonstelly** [comment]
@JeremyKelley - I found this issue through a search.  I'm probably not having the same exact issue as harmoniedev but in case it's helpful...

I get this from Graph Explorer when logged in with an account created for Azure (So the Azure AD Free license), but the request works fine when I log in with a full-fledged Azure AD account.

I seem to be able to generate these at will so if you need more examples/requests I can create those.  FWIW I see these errors for just about everything, the `/me` request, `/servicePrincipals`, the canned examples in Graph Explorer, etc...

```
{
    "error": {
        "code": "InternalServerError",
        "message": "Unable to find target address",
        "innerError": {
            "date": "2021-07-26T20:42:39",
            "request-id": "83f3c1ba-22df-4e31-8567-eff0d31afbb7",
            "client-request-id": "e720dbec-f61d-6b43-2535-1616a6b49456"
        }
    }
}
```

**Comment by MathewsNyirongo** [comment]
Any update on this? I'm still facing the same issue.

**Comment by Dharap18** [comment]
I found this issue through a Graph groups api
Any update on this?
{
    "error": {
        "code": "InternalServerError",
        "message": "Unable to find target address",
        "innerError": {
            "date": "2021-09-24T07:02:01",
            "request-id": "871a521a-5611-4f8e-a481-65afd37845db",
            "client-request-id": "871a521a-5611-4f8e-a481-65afd37845db"
        }
    }
}

**Comment by FaithOmbongi** [comment]
My apologies everyone for the delayed response. Unfortunately, this channel is only for documentation gaps/bugs and isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-explorer.html). Please ask this question there and if possible, share the correlation ids. Closing this issue here.
