### ISSUE TITLE
What happens after 500 devices?

### ISSUE THREAD

**Issue by ranouf** [microsoftgraph/microsoft-graph-docs#6356]
Hi,

What happens if we have more than 500 devices subscribed? or even more like 6000? 
The answer will be really big and long to receive.
Is it possible to filter the number of devices returned? 
Like :

`GET` https://graph.microsoft.com/v1.0/users/{usersId}/managedDevices/?number=500&skip=500

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1691c888-7955-2567-d53d-3a03eae9d9eb
* Version Independent ID: 6fd35314-8882-a049-fbb9-6037d818d100
* Content: [List managedDevices - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-list?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Paging will typically come into play with > 1000 objects.  You can read about it here: https://github.com/microsoftgraph/powershell-intune-samples/tree/master/Paging
