### ISSUE TITLE
Group owners does not have access to planner/task data

### ISSUE THREAD

**Issue by figgsoftware** [microsoftgraph/microsoft-graph-docs#636]
If we add someone as group owners only (not members), then they don't have access to the groups plan. They should since they have access to everything in the group. This is a very valid scenario for managers that want to have access to groups without actually being members.

**Comment by jthake-msft** [comment]
This is a feature request. As per the issue template creation process, feature requests should be added to UserVoice. https://developer.microsoft.com/en-us/graph/support


This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
