### ISSUE TITLE
Permissions list inaccurate

### ISSUE THREAD

**Issue by Mhbuur** [microsoftgraph/microsoft-graph-docs#6364]
According to https://docs.microsoft.com/en-us/graph/permissions-reference you can call /me/memberOf/$/microsoft.graph.group?$filter=groupTypes/any(a:a%20eq%20'unified') which returns unified groups only. And this is possible without Directory.Read.All.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9188ffdb-b7af-597d-9e0a-d92e75ff8e7d
* Version Independent ID: c4427823-3f37-dc4b-ac1e-b750cb633e23
* Content: [List memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-memberof.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
We'll be updating the docs shortly, based on a change in behavior that will allow you to ask for least privileged permissions, even on the List memberOf API.  For more details of the change, please see this blog post: https://developer.microsoft.com/en-us/graph/blogs/upcoming-api-changes-to-return-limited-information-for-inaccessible-member-resources/
cc @VinceSmith @rwike77

**Comment by Mhbuur** [comment]
Thanks - will other endpoints be updated in this regard too? 

Several endpoints list *.Read.All as least privileged permission even to just request data visible for the logged in user, which - if granted - potentially allow the app to show the user more than they have access to normally.

**Comment by davidmu1** [comment]
A note has been added to the page. Closing the issue.
