### ISSUE TITLE
Difference between getMemberGroups and getMemberObjects?

### ISSUE THREAD

**Issue by fowl2** [microsoftgraph/microsoft-graph-docs#6375]
The descriptions are almost identical, take the same parameters, etc:
&gt; Return all the groups that the specified group is a member of. The check is transitive...
vs
&gt; Return all of the groups that this group is a member of. The check is transitive...

However `getMemberObjects` requires significantly more privileged scope.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22d273f4-5924-bb72-0601-d92d9978f009
* Version Independent ID: d46c4ae3-df08-5dc9-1735-d07c4ec18b28
* Content: [group: getMemberObjects - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-getmemberobjects?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-getmemberobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-getmemberobjects.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
group: getMemberObjects returns all directory objects the group is a member of, such as AU and roles, in addition to groups. Since some resource type is not in V1 yet, or capability is not GA, they are not documented on this page.
