### ISSUE TITLE
Create an event for someone else ?

### ISSUE THREAD

**Issue by DyGiiwax** [microsoftgraph/microsoft-graph-docs#6377]
Is it possible to create an event for two others people for exemple, but without including myself ?
I just want to be the organizer and not in the meeting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41a9857-98a9-e400-d7ce-bd7c0f37cd46
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/event.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @DyGiiwax , it's possible for a calendar owner to share or delegate a calendar with another user, let that user create and send meeting requests on the owner's behalf, without including that user as an attendee in those meetings.
Say the calendar owner is Alex. Alex shares a calendar with Adele and gives Adele edit permissions. Adele can access the calendar, create and send a meeting request (on behalf of Alex) to Megan and Samantha. Programmatically, when Adele creates and sends the event, Megan and Samantha would receive a meeting request that specifies the **sender** property as Adele and the **from** property as Alex. As far as the actual **event** on the calendars for Megan, Samantha, Alex, and Adele goes, the **attendees** property includes only Alex, Megan, and Samantha, and the **organizer** property shows Alex. Adele isn't specified in the **event** properties.

The above applies to the case if Alex delegated the calendar to Adele as well. Note that the sharing or delegating of a calendar has to be done in the Outlook client; there isn't a REST API that does this. You can use REST API to do the rest of the scenario - creating and sending a meeting request, responding, getting properties of an event.

One main difference between the sharing and delegating cases is that:
- With sharing, Alex and not Adele receives responses from Megan and Samantha. 
- With delegating, by default, Adele and not Alex receives responses (Alex can further configure this though). Alex can get responses as part of the **attendees** property of the **event**.

**Comment by angelgolfer-ms** [comment]
For anyone looking for information about creating an event on behalf of another user, please see the new article [Create Outlook events in a shared or delegated calendar](https://docs.microsoft.com/en-us/graph/outlook-create-event-in-shared-delegated-calendar).
