### ISSUE TITLE
Do I need create subscription for each groups endpoint or is there a one endpoint for all the conversation change of the groups on the organization

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#6378]
Let's say I have multiple groups and I want to get notified for any additional conversation on any of the groups so do I need to create subscriptions for each groupId endpoint. Or Is their way I create one subscription for change on the conversation of the groups on the organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe0590e-070b-cf56-cbc7-1dcb8a266380
* Version Independent ID: 2d912536-afc5-60f1-e381-2eef892cbded
* Content: [subscription resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/subscription.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @ashoksubedi1 
Thanks for reaching out!
The GitHub issues are a place more adapted to point out issues in the documentation that need fixing.
For questions on "how do I do..." https://stackoverflow.com with the tag [microsoft-graph] is best suited.
Closing for now
