### ISSUE TITLE
Development of this capability

### ISSUE THREAD

**Issue by anwather** [microsoftgraph/microsoft-graph-docs#6384]
Is there a timeline for this to be in preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb10229f-46f3-82b2-b8da-6cd567a9f32c
* Version Independent ID: e272dcc2-641d-33d7-ba26-b3d17239bd4e
* Content: [Privileged Identity Management - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/privilegedidentitymanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/privilegedidentitymanagement-root.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@davidmu1  can we get the owner of this page updated asone thing?
and who could help answer this?

**Comment by davidmu1** [comment]
We do not have a timeline to share at this time.
