### ISSUE TITLE
A value without a type name was found and no expected type is available.

### ISSUE THREAD

**Issue by jmcadams-r7** [microsoftgraph/microsoft-graph-docs#6388]
Anyone know how to fix this? 

{
  "error": {
    "code": "Request_BadRequest",
    "message": "A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.",
    "innerError": {
      "request-id": "f0ba2527-b1ac-46f1-86fb-9d5d18698dca",
      "date": "2019-11-22T15:26:01"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2f4938-7d09-1888-5d89-15cdaa9bf6dd
* Version Independent ID: 601266a3-affe-e167-d643-5de314b0bfd9
* Content: [conditionalAccessPolicy resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/conditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/conditionalaccesspolicy.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jmcadams-r7** [comment]
(Sorry, this is actually for the CreatePolicy action, I put this question on the wrong page, my bad)

**Comment by davidmu1** [comment]
This seems to be a duplicate. Going to close this issue. Requested a response from engineering on the issue and will respond in the other one.
