### ISSUE TITLE
A value without a type name was found and no expected type is available. 

### ISSUE THREAD

**Issue by jmcadams-r7** [microsoftgraph/microsoft-graph-docs#6390]
Does anyone know why we are getting this error? 

{
  "error": {
    "code": "Request_BadRequest",
    "message": "A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value.",
    "innerError": {
      "request-id": "57e2944a-afe7-45a9-8180-085dea79a037",
      "date": "2019-11-22T16:02:09"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1052ee37-5a9e-d36d-2767-a39cdbd5a4df
* Version Independent ID: 10b8d865-1b5b-732f-70c9-a75ea83ce15b
* Content: [Create conditionalAccessPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conditionalaccessroot-post-policies.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jmcadams-r7** [comment]
Some more info...this question is about the actions here: 
https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&tabs=http

I've tried using this endpoint to get a policy: 
https://graph.microsoft.com/beta/{tenant_id}/conditionalAccess/policies

Which returns a policy. 

I'm using that as the payload I'm posting back to the same endpoint, but changing the description, removing all null values, and all seemingly read only values (things like id, date created, etc...)

We keep getting the above error, and I'm not sure how to fix that. 

Here's an example of the payload I'm sending. 
```
{
    "displayName": "Test Policy Number 2",
    "state": "disabled",
    "conditions": {
        "clientAppTypes": [],
        "locations":{
        	"includeLocations": ["None"]
        },
        "applications": {
            "includeApplications": [
                "None"
            ],
            "excludeApplications": [],
            "includeUserActions": []
        },
        "users": {
            "includeUsers": [
                "<user ID removed>"
            ],
            "excludeUsers": [],
            "includeGroups": [],
            "excludeGroups": [],
            "includeRoles": [],
            "excludeRoles": []
        },
        "platforms": {
            "includePlatforms": [
                "android",
                "iOS"
            ],
            "excludePlatforms": []
        }
    },
    "grantControls": {
        "operator": "OR",
        "builtInControls": [
            "approvedApplication"
        ],
        "customAuthenticationFactors": [],
        "termsOfUse": []
    }
}
```

We've also tried the Delegated authentication flow and application flow (I think only Delegated will work here, but I'm down to permutations on the little stuff to get this to work).

**Comment by davidmu1** [comment]
Here is the response from engineering: 

I cannot repro their problem.
The only issue I noticed with their payload is the fact that they added includeLocations: "None". THis is not a valid condition, but the API returns a nice error when that happens:


"code": "BadRequest",
        "message": "Invalid location value: None",

If they still need help, I think we could ask for a fiddler trace because we couldn't repro it. Feel free to engage me if needed.

Can you provide a fiddler trace?

**Comment by jmcadams-r7** [comment]
I'm not sure how to get a fiddler trace from Python. Let me see if I can figure that out. 

The other note is, we've tried a lot of different combinations of the above payload. Removed all the "None" values for instance, and are still running into the same issue.

**Comment by jmcadams-r7** [comment]
I'm having a hell of a time getting fiddler to run on OSX. What are you looking for in the request that will help you out? I can get most of the information provided by fiddler in Post Man I think.

**Comment by davidmu1** [comment]
I will get engineering directly involved with the issue. Stay tuned...

**Comment by elcarlosadrian** [comment]
@jmcadams-r7 : Do you get the same error in Postman? or only python?
If you cannot capture a fiddler trace, then let me ask: have you tried using MS Graph explorer? https://developer.microsoft.com/en-us/graph/graph-explorer

e.g. I just tried with a simple policy:

![image](https://user-images.githubusercontent.com/10471168/70838820-e15a3a80-1dbe-11ea-9281-e297ba651468.png)

**Comment by jmcadams-r7** [comment]
Well...at least we're getting something different now. 

```
{
  "error": {
    "code": "Internal Server Error",
    "message": "There was an internal server error while processing the request. Error ID: 795e95b5-432f-4165-afb8-5549449ec4a9",
    "innerError": {
      "request-id": "795e95b5-432f-4165-afb8-5549449ec4a9",
      "date": "2020-01-22T15:06:51"
    }
  }
}
```

**Comment by jmcadams-r7** [comment]
If I post to: 
https://graph.microsoft.com/beta/<tenant>/policies

```
{
    "displayName": "TestPolicyNumber2",
    "state": "disabled",
    "conditions": {
        "applications": {
            "includeApplications": [
            	"None"
            ]
        },
        "users": {
            "includeUsers": [
                "<user uuid>"
            ]
        }
    },
    "grantControls": {
        "operator": "OR",
        "builtInControls": [
            "mfa"
        ]
    }
}
```

**Comment by jmcadams-r7** [comment]
I also got that same error message when running through Graph explorer.

**Comment by videor** [comment]
@jmcadams-r7 apologies for delayed response on this. Are you still getting issue with the JSON. We have changed the error messages and made them more human readable. Would like to see how you are doing on this.

**Comment by videor** [comment]
@jmcadams-r7 try the below JSON. I have just changes your includeUsers to enum value.

{
    "displayName": "TestPolicyNumber2",
    "state": "disabled",
    "conditions": {
        "applications": {
            "includeApplications": [
            	"None"
            ]
        },
        "users": {
            "includeUsers": [
                "None"
            ]
        }
    },
    "grantControls": {
        "operator": "OR",
        "builtInControls": [
            "mfa"
        ]
    }
}

**Comment by jmcadams-r7** [comment]
I'm not sure, I think we gave up on this call.
