### ISSUE TITLE
Should ONEDRIVE >> ITEM in the TOC display the driveitem resource topic?

### ISSUE THREAD

**Issue by angelgolfer-ms** [microsoftgraph/microsoft-graph-docs#64]
For both v1.0 and beta, currently clicking ITEM displays the drive resource type topic, as attached.

Looks like at one point there was an item.html per the link breadcrumb, and then that was deleted/renamed. Now ITEM in the TOC should be updated to display the driveitem resource topic?

![untitled](https://cloud.githubusercontent.com/assets/12191822/11605958/9b0037b0-9ac3-11e5-8afa-50a6f1dd4c9b.png)

**Comment by mimisasouvanh** [comment]
An item in the graph model is represented by the driveItem resource. As not to be confusing, item will be documented, with driveItem the programmatic representation.

**Comment by angelgolfer-ms** [comment]
@mimisasouvanh, can you work with @yinaa to have ONEDRIVE>>ITEM display driveitem.md, in both the v1.0 and beta portion of the TOC?

BTW, did you mean "with item the programmatic representation"? The MD file is named driveitem, but the title in that MD file is "item resource type".
