### ISSUE TITLE
the final nextlink request contains incorrect skip token

### ISSUE THREAD

**Issue by ahemavathy** [microsoftgraph/microsoft-graph-docs#6403]
just wanted to give the feedback that https://docs.microsoft.com/en-us/graph/delta-query-users#final-nextlink-request contains the old skip token instead of the most recent skip token. please update for correctness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05eda6b9-c06f-2a02-707c-34b49f1d6f6e
* Version Independent ID: cf533ea9-3054-ef1d-b8eb-aa5c4589fbdf
* Content: [Get incremental changes for users - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-users)
* Content Source: [concepts/delta-query-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-users.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @ahemavathy 
Thanks for pointing out this issue in our documentation.
I just authored a pull request to address it #6963
This issue will be closed once the PR is merged.
