### ISSUE TITLE
Not working ins MS Flow

### ISSUE THREAD

**Issue by SUPEUS** [microsoftgraph/microsoft-graph-docs#6404]
Hello,
This DELETE request was made using HTTP request in MS Flow.
It fails even the access token in successfully generated for the global admin with all permissions.
Is it true that Graph Explorer is not compatible with MS Flow?
Ivan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b39bb6a3-8430-2db5-8310-ad548eb366d4
* Version Independent ID: 7fe2e448-7420-c5cf-b835-718a2b9ba210
* Content: [Delete plannerTask - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/plannertask-delete?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/plannertask-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannertask-delete.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TarkanSevilmis** [comment]
Admins do not have special permissions. Your request probably failed because the the calling user (even if they are admin) didn't have permissions do to the operation.
