### ISSUE TITLE
Update a place but GET response still old data

### ISSUE THREAD

**Issue by bang-reactron** [microsoftgraph/microsoft-graph-docs#6410]
Hi

I just use the UPDATE API place to set the tags. The response I got from the server is 200 and in the response body the tags has been updated correctly.

However when I make the GET request, the place tags is empty Array (nothing changed at all). May I know what happened? Does it take time to update data for the place?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f9fd360-9964-de37-16d4-b70a4900b7d9
* Version Independent ID: 52c2bb4f-9e22-0573-b403-3f107d28af75
* Content: [Update place - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/place-update?view=graph-rest-beta&tabs=javascript#feedback)
* Content Source: [api-reference/beta/api/place-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/place-update.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChristopheMaingard** [comment]
Same here :
Here's my place in the admin center : 
![image](https://user-images.githubusercontent.com/57448695/69707149-7e4b8100-10f9-11ea-978a-792fe0767f02.png)
Here's what `/beta/places/microsoft.graph.room` is returning : 
```
            "id": "48c67636-fcc8-*****-****-*******",
            "displayName": "Gehry",
            "address": null,
            "geoCoordinates": null,
            "phone": "",
            "nickname": "Gehry",
            "emailAddress": "gehry@********.com",
            "building": null,
            "floorNumber": null,
            "floorLabel": null,
            "label": null,
            "capacity": 4,
            "bookingType": null,
            "audioDeviceName": null,
            "videoDeviceName": null,
            "displayDeviceName": null,
            "isWheelChairAccessible": false,
            "tags": []
        },
```
You can see that both names and capacity aren't matching.
Now, here's what  `/beta/users/cad689f4-*****-****-****-********/findrooms` returns : 
```
        {
            "name": "GehryRRR",
            "address": "gehry@*******.com"
        },
```
Either graph is returning old data, either it is not the same object, and I don't know where to modify it.

**Comment by bang-reactron** [comment]
@ ChristopheMaingard btw do you know is there any way to add tags into the place by the admin center tool? Right now I got it working by using the API PLACE UPDATE but it's not convenient to manage it in the future.


Also in the Room resource we can add Custom attributes but I can't figure out any way to fetch them by using Microsft Graph Api....


<img width="1348" alt="Screenshot 2019-11-27 at 11 51 22" src="https://user-images.githubusercontent.com/58177683/69712990-6e896800-110c-11ea-812a-02619a6bf229.png">

**Comment by ChristopheMaingard** [comment]
@bang-reactron I'm afraid I have no idea

**Comment by vrod9429** [comment]
Hey @bang-reactron the M365 admin portal has not been updated yet to reflect the new properties supported in Exchange by the Graph API.

**Comment by dtfischer** [comment]
Was there ever any determination made regarding whether the issue was old data being returned, or if the room objects being returned by the places/microsoft.graph.room API differ from the ones that are being updated and/or returned by the me/findRooms API?

**Comment by vrod9429** [comment]
@ChristopheMaingard @bang-reactron @dtfischer When you create a new room it takes about 48 hrs to show up in our Places API. I know this is inconvenient and we hope to have this fixed within the next couple of months. Data that you add in the M365 portal or using set-user,set-mailbox or GET using FindRooms API will also take 48 hrs to replicate in our Places API. The reason for this is that one data is coming from AD while the other is coming from a tenant shard (tenant mailbox). We then need to sync AD information to the tenant shard. This is where we see the 48 hr delay. In the future we will solely use the Tenant shard and do inline updates to make this faster.
