### ISSUE TITLE
What happened to addkey?

### ISSUE THREAD

**Issue by sindrerh2** [microsoftgraph/microsoft-graph-docs#6419]
What happened to addkey? According to this, it was planned, but now I can't find it anywhere: https://github.com/microsoftgraph/microsoft-graph-docs/commit/95b8a3dd0afc8145bf233a177c5c376898835ace?short_path=ade8f24#diff-ade8f24477cacd4e65260543a0ec80c4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd04739f-1ec0-9915-abb3-6a0cd4890e8a
* Version Independent ID: 90aa6e1d-6efa-5100-b51f-7766325086a6
* Content: [keyCredential resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/keycredential?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/keycredential.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/keycredential.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
We don't publish information about availability of features in these articles. No change required to the referenced article.

**Comment by AnnejanBarelds** [comment]
Not sure about the documentation, but it seems to be working. I wrote a post on how to use it: https://blog.annejanbarelds.nl/2020/03/04/how-to-handle-credential-provisioning-and-key-rolling-with-the-microsoft-graph-api/
