### ISSUE TITLE
Small Bug in queries

### ISSUE THREAD

**Issue by itisslizz** [microsoftgraph/microsoft-graph-docs#6423]
In graph explorer https://developer.microsoft.com/en-us/graph/graph-explorer/preview log in as user1.
User1 has Max Power added to Exchange contacts:
            "displayName": "Max Power",
            "emailAddresses": [
                {
                    "name": "mpower@company.com",
                    "address": "mpower@company.com"
                }
            ]
 
1. Search for "mpower" in display name only
https://graph.microsoft.com/v1.0/me/contacts?&$filter=startswith(displayName,%mpower%27)
Actual and expected result: nothing is returned as expected as there is no user with display name "mpower"

2. Search for "mpower" in email only
https://graph.microsoft.com/v1.0/me/contacts?$filter=emailAddresses/any(a:a/address%20eq%20%mpower%27)
Actual and expected result: nothing is returned, this is expected because Microsoft doesn't support 'contains' or even 'starts with' for email field (source: https://docs.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0&tabs=http#optional-query-parameters)

3. Search for "mpower" in display name and email:
https://graph.microsoft.com/v1.0/me/contacts?$filter=startswith(displayName,%mpower%27)%20or%20emailAddresses/any(a:a/address%20eq%20%mpower%27)
Actual result: mpower@company.com is returned
Expected result: ? I suppose nothing should be return here as well (same as in cases 1 and 2)

Note: when in case #3 I look for 'company' or 'com' then contact is returned. But if Look for 'compan' or 'co' then no result. So it looks like in this case the  the email value is split by dots (and probably by @)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5dc5d01-8bbf-2370-ab1c-680608707ca9
* Version Independent ID: e80b8c52-22f9-24df-528a-50b7d1492eac
* Content: [List contacts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-list-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-contacts.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@kevinbellinger , can you please verify if there is a bug in filtering the displayName and emailAddresses properties of the contact entity?
If it turns out we should update our docs and you need my help, please let me know. Thanks.

**Comment by PeterChencha** [comment]
Hello @itisslizz thanks for reaching out, this issue is noted and will be addressed.

@angelgolfer-ms There is no documented bug in filtering the displayName and emailAddresses properties of the contact entity, kindly refer to this documentation for further details on filtering -> https://docs.microsoft.com/en-us/graph/api/user-list-contacts?view=graph-rest-1.0&tabs=http#optional-query-parameters
