### ISSUE TITLE
Doesn't really return all rooms

### ISSUE THREAD

**Issue by mmascolino** [microsoftgraph/microsoft-graph-docs#6427]
This is likely more of a bug/limitation with the endpoint than the documentation but this endpoint doesn't currently return the @odata.nextLink attribute to indicate that there is more pages of data to return.  Sure you can include a $top=1000 to get all the rooms (assuming you less than 1000 rooms) but that isn't a great experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41555953-ca70-587c-4660-5f0a83c8c230
* Version Independent ID: 4a5b79f8-d685-6c86-d7ed-12d7c5d309cb
* Content: [List places - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/place-list.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by EliasKaplan** [comment]
You can use client pagination:
Include on the query:
$top=40&$skip=0&$count=true
$top=40&$skip=40&$count=true

The response contains @odata.TotalCount that will help you through the pagination.
Also once reach the end, $skip=2000 on list of 100 rooms, the response will be empty.
