### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by lafe** [microsoftgraph/microsoft-graph-docs#6435]
It would be great to have a RSS feed for this page, so that we can use a feed reader to be informed automatically when there are changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a84942d-0326-24c3-d8fa-4fbd782132b3
* Version Independent ID: 08ab36ac-6f96-920a-b4dd-07c292fbacae
* Content: [Changelog for Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/changelog)
* Content Source: [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/changelog.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @lafe for raising this. A link for the RSS feed is now included in the [our new changelog experience](https://developer.microsoft.com/en-us/graph/changelog) currently in preview. Try it out and your feedback is welcome! Closing this issue for now.
