### ISSUE TITLE
Error while trying to access the /filesFolder GraphApi endpoint as a global admin for a private channel

### ISSUE THREAD

**Issue by josipGrgic11235** [microsoftgraph/microsoft-graph-docs#6440]
Issue:
Right, so I followed the steps described in this article describing the way to find the SharePoint URL for a given private channel. Basically, I made the following call as a global admin, but having no membership or ownership to the team and/or private channel in question:

`GET https://graph.microsoft.com/beta/teams/<group_id>/channels/<channel_id>/filesFolder`

But, it seems that the call returns an error (sometimes 500, other times 404 with an "Unknown error" message) while supplying a <channel-id> of a private channel. The same thing happens from time to time for a private channel owner account as well which for me doesn't make much sense.

The article does briefly point out that we have to have an admin role but does not delve into more details around the needed permissions. The admin user making the request is, besides GA, additionally a Teams Service Admin as well as a Skype Admin.

Also, I seem to recall that I was able to make the described request last week successfully. Are there any changes, permission-wise, we should be aware of or is there just a bug on your side of things? Any insight is greatly appreciated.

Regards,
Josip
Article:
https://docs.microsoft.com/en-us/MicrosoftTeams/private-channels-life-cycle-management#find-sharepoint-urls-for-all-private-channels-in-a-team

**Comment by josipGrgic11235** [comment]
Currently, the error being thrown is 503 with the following error message:
`
{
    "error": {
        "code": "Proxy_InternalServerError",
        "message": "Failure in forwarding request.",
        "innerError": {
            "request-id": "...",
            "date": "..."
        }
    }
}
`

**Comment by Aravindelumalai04** [comment]
It works perfectly to me. Use beta version to get channel list so you could identity the channel type. 
then use [(https://graph.microsoft.com/beta/teams/<group_id>/channels/<channel_id>/filesFolder)] API

**Comment by josipGrgic11235** [comment]
It does work perfectly for standard channels and any channels I am a member/owner of, but my issue is related to doing the request above for private channels my Office GA account is not a member/owner of. 

Would you be so kind and check that case? Maybe create a new team and then a new private channel so you are sure the admin account doesn't have access to any of them and than try the request with the GA account. It would really go a long way :)

**Comment by Aravindelumalai04** [comment]
Your error represented as "Sending request issue" you might reach out IT server person and ensure Firewall setting from your machine. its purely related to Network server issue and restricted to your machine man. go ahead.

**Comment by buzznut** [comment]
There seems to be a number of issues with the "filesFolder" endpoint and the results are intermittent.

Using Graph to create channels (both private and standard) I then have these errors:

For newly created "private" channels it returns code: "BadGateway" errors. I don't know if they ever go away. The private channel site is created in Sharepoint. The error message: "Failed to execute backend request."

For newly created "standard" channels it always returns code: "NotFound" errors. I can find the channel folder in Sharepoint so I know it exists. The error message: "Sharepoint folder not found."
