### ISSUE TITLE
Call this endpoint when a Team already exist for a Group

### ISSUE THREAD

**Issue by jonnyguo1988** [microsoftgraph/microsoft-graph-docs#6448]
When I call this endpoint for an existing team id, sometime it response with status code 500, sometime it response with 503. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d21f6e2-d207-8fbe-931a-12872e9b50a2
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team from group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-msft** [comment]
calling PUT /groups/{id}/teams operation on a group which has already been teamified will result in conflict-409.
