### ISSUE TITLE
Webhook Subscription not working - Giving Subscription request timed out

### ISSUE THREAD

**Issue by ashishkumarpersistent1992** [microsoftgraph/microsoft-graph-docs#6449]
API - https://graph.microsoft.com/v1.0/subscriptions
Request Type - POST
Request Body - {
  "changeType": "created,updated",
  "notificationUrl": "https://&lt;IP Address of AWS Server&gt;:5000/listen",
  "resource": "me/mailFolders('Inbox')/messages",
  "expirationDateTime": "2020-03-20T11:00:00.0000000Z",
  "clientState": "SecretClientState"
}
Response - {
  "error": {
    "code": "InvalidRequest",
    "message": "Subscription validation request timed out.",
    "innerError": {
      "request-id": "2103a5c1-a780-4c36-b6de-cb98a10e9977",
      "date": "2019-11-28T11:05:46"
    }
  }
}

Please suggest how to resolve this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks#feedback)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mfulan** [comment]
This issue appears to have occurred again. Our tenant is in southwest US. Is this a regional or global issue? Trying to find out from our client if we can raise an MS Support issue on this.

**Comment by ashishkumarpersistent1992** [comment]
My Region is - US

![image](https://user-images.githubusercontent.com/58325407/70020005-56ed2c00-15b1-11ea-9d63-29b5b5708e5e.png)

Please have a look in Image

**Comment by ashishkumarpersistent1992** [comment]
Please could anyone suggest/advise a solution on this.

**Comment by baywet** [comment]
Hi @ashishkumarpersistent1992 
Is this still something you are running into now?

**Comment by techgeekashishkumar** [comment]
So, Point is -

In Notification URL - Now given the Ngrok URL  in API - 

API - https://graph.microsoft.com/v1.0/subscriptions
Request Type - POST
Request Body - {
"changeType": "created,updated",
"**notificationUrl**": "**url provided by ngrok/listen**",
"resource": "me/mailFolders('Inbox')/messages",
"expirationDateTime": "2020-03-20T11:00:00.0000000Z",
"clientState": "SecretClientState"
}

But what can we do best in the production environment? Please suggest because ngrok is not recommended by many Organisations

**Comment by baywet** [comment]
I'm not sure I understand where the recommendation of using ngrok comes from, can you provide a link to the documentation that mentions it please?

ngrok is great for testing and debugging locally, but it is a development tool. In my personal opinion it wasn't designed for production workload.
In a production scenario you'd leverage a PaaS solution like Azure Websites, Azure Functions, an Azure Virtual machine... or a hosted solution.
In both cases that would expose a public url (eg https://something.azurewebsites.net) which you could use to register the subscription.
Does that help clarify the approach?

**Comment by monikadeshmukh72** [comment]
Hi, 
I am also facing the same issue. Is there any solution for this?
