### ISSUE TITLE
Wrong minimum value for availabilityViewInterval

### ISSUE THREAD

**Issue by maxlund** [microsoftgraph/microsoft-graph-docs#6450]
For the availabilityViewInterval property, it says "The default is 30 minutes, minimum is 6, maximum is 1440", however you can set it to 5 without problem. Setting it to 4 or lower results in:
```
"code": "ErrorInvalidMergedFreeBusyInterval",
"message": "The specified merged free/busy interval is not valid. Specify an interval that is less than the free/busy time window and  between 5 and 1440 minutes."
```
I.e. the documentation here is wrong, it should say between "between 5 and 1440 minutes."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e72df543-3deb-151b-f634-608a04881289
* Version Independent ID: 3db73371-c6ee-2add-9d51-223e3f1f82e4
* Content: [calendar: getSchedule - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-getschedule?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-getschedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-getschedule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@maxlund , thank you for pointing this out. I had tried the limits as well and updated the topic (for v1 and for beta) in PR #6660 .
Thank you again for your support.
