### ISSUE TITLE
Bad Gateway or Proxy_InternalServerError on messages/delta of teams API 

### ISSUE THREAD

**Issue by 42wim** [microsoftgraph/microsoft-graph-docs#6451]
Running `https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages/delta` always fails with one of the errors below.

Running `https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages` works fine.

I'm not sure if this is a service outage of that the docs are already there but the service isn't working yet :-)

```
{
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": "adc1a4b9-03e1-45a6-bd3d-2f86cb47e39f",
      "date": "2019-11-25T22:58:47"
    }
  }
}
```

```
{
  "error": {
    "code": "Proxy_InternalServerError",
    "message": "Failure in forwarding request.",
    "innerError": {
      "request-id": "459f392a-6aa9-4a8e-9729-a0a55e54ac26",
      "date": "2019-11-25T23:03:22"
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fa912d-43d1-099b-44d5-fdcdaae00db7
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessages: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
We tried to repro this at our end and it is working as expected. 
Graph API 
"https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages/delta" returns 200 success response with data.

Could you please try now and confirm.
