### ISSUE TITLE
isResourceAccount null

### ISSUE THREAD

**Issue by acraftydev** [microsoftgraph/microsoft-graph-docs#6453]
isResourceAccount is always null. What process's set this value. I'm trying to filter out shared mailboxs and rooms but this value is never set.

Similar to issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/4094

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by undertakingyou** [comment]
I am looking to do much the same thing, and like @acraftydev noted, issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/4094 shows the same thing, but there in no progress on that issue in some time.

Is there any workaround for the above desired outcome? Is there any plans to improve this logic so that it appropriately says true / false, instead of just null?

**Comment by dkershaw10** [comment]
@krbain Can you investigate this please?

**Comment by DavidRogers** [comment]
Is there any update on this? This is a problem for me as well.

**Comment by TheSinding** [comment]
I have the same problem, is there a time frame or any updates for this ?

**Comment by arnoldmatusz** [comment]
Got the same issue. Any updates here?

**Comment by krbain** [comment]
isResourceAccount is not supported, docs indicate that is should not be used e.g. Do not use – reserved for future use. See https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#properties
