### ISSUE TITLE
Clarification on "Required" properties

### ISSUE THREAD

**Issue by bubbletroubles** [microsoftgraph/microsoft-graph-docs#6455]
The page says _"Request body
In the request body, supply a JSON representation for the iosCompliancePolicy object.

The following table shows the properties that are required when you create the iosCompliancePolicy."_

And then it lists properties such as "id", "createdDateTime" etc. But the ID and CreatedDateTime are automatically set, so would not be required. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cacdc799-6a14-0887-0f23-ca06a4499273
* Version Independent ID: 15f5d625-2fcb-c111-d850-e15b5ad50bbb
* Content: [Create iosCompliancePolicy - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-ioscompliancepolicy-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-ioscompliancepolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-deviceconfig-ioscompliancepolicy-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Removed the id and time related properties from the request table.
