### ISSUE TITLE
Wrong targetID?

### ISSUE THREAD

**Issue by snikendeugle** [microsoftgraph/microsoft-graph-docs#6456]
The targetId being returned by this request is not the same as "targetId" being used to create a new assignment request. Is this intentional?
The targetId in the latter is the object-id of a user. I have no idea what targetId in "accessPackageAssignments" is supposed to symbolize, and I can't tie it to a user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62495d1c-009b-4c87-30d5-b3c415f967b5
* Version Independent ID: c3b9c844-417f-14d2-c887-b708de640c1f
* Content: [List accessPackageAssignments - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accesspackageassignment-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by snikendeugle** [comment]
Would love an update on this.

**Comment by markwahl-msft** [comment]
Thanks for reporting.  Yes this is a known bug.

**Comment by aronfelipe** [comment]
Is the solution in development?

**Comment by snikendeugle** [comment]
Requesting an update on this. It is currently inhibiting automation-workflows that we cannot return a usable object-id that correlates to a user account from an assignment.

**Comment by markwahl-msft** [comment]
The targetId in the access package assignment is the ID of the subject.  You can obtain the object ID of the user by expanding the target property of the assignment.  For example,
GET https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignments/6807cec4-0565-4523-8760-7eb0941ed7a6?$expand=target
which would return
```
{
...
    "target": {
        "id": "ce4038ae-5bd4-4dc5-bb8e-e8f7a28c9c29",
        "objectId": "03f3b2be-cef7-48b3-93d9-891e941c5bd2",
        "displayName": "User",
        "principalName": "user@YOURDOMAIN.onmicrosoft.com",
        "email": "user@YOURDOMAIN.onmicrosoft.com",
        "type": "User"
    }
}
```
If the `target.type` is `User`, then the `target.objectid` parameter can then be used to query for the user `/beta/Users/03f3b2be-cef7-48b3-93d9-891e941c5bd2` to retrieve other properties.

**Comment by snikendeugle** [comment]
Ahh, that's what I was missing. Thanks!
