### ISSUE TITLE
Missing SetSectionLevel and GetSectionLevel equal to get and set pagelevel

### ISSUE THREAD

**Issue by Crucerio** [microsoftgraph/microsoft-graph-docs#6463]
Please implement an option to change Section Order, even the OneNote Web App does this in a buggy way, when using drag and drop.
We need a way to change positions of sections like that:
https://graph.microsoft.com/beta/me/onenote/sections/{id}/
HTTP Request PATCH
{
    "id": "Section ID",
    "sectionlevel: "4"
}
Behaviour should be:
Put Section to Specified position in the list
if already occupied: iterate all sections below by 1
when finished, fill the created gap by deiterating sectionlevel of all items above the emptied slot

Alternative:
Accept a complete list of Section IDs in an array and set that as sort Order.
Patch
https://graph.microsoft.com/beta/onenote/notebooks/{ID}/sections/
{{
"id":"Section ID 1",
"sectionlevel":"0"
},{
"id":"Section ID 2",
"sectionlevel":"1"
},{
"id":"Section ID 3",
"sectionlevel":"2"
}}
deny incomplete lists, allow fragmented lists
 return continuation link in answer if requested
Apply changes as transaction, (don't apply untill list completed)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08030920-8482-eedf-4a4c-8f48cb24b385
* Version Independent ID: 7cc67f89-04d8-dac0-66f0-8ce8b56a2e6e
* Content: [Create section - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/notebook-post-sections?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/notebook-post-sections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/notebook-post-sections.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @jonnyguo1988 for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-notes.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
