### ISSUE TITLE
Office 365 Germany group get delta API availibility 

### ISSUE THREAD

**Issue by nozhT** [microsoftgraph/microsoft-graph-docs#6471]
Since this API is currently not available on Office 365 Germany, it would be helpful to mention it somewhere in this page.

I would also like to know when (or if ever) will the API be available for Germany.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e89b9ed-663c-3639-9d0d-9aad705920f3
* Version Independent ID: b003a86a-f78f-05eb-e67d-54bb5ca0f2b1
* Content: [group: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delta.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @nozhT 
Thank you for pointing out this information was missing in our documentation.
I just authored pull request #6960 to address this issue.
Delta queries are currently only available in the public cloud and in the Chinese national cloud.
If you'd like to see this feature deployed to other national clouds, I suggest you request so on [uservoice](https://microsoftgraph.uservoice.com).
This issue will be closed automatically when the PR is merged
