### ISSUE TITLE
Graph API subscriptions not receiving any notifications for >24h now!

### ISSUE THREAD

**Issue by cv711** [microsoftgraph/microsoft-graph-docs#6476]
This is a copy of #6462 since the author closed it and it hasn't been resolved for us yet.

Both old and new subscriptions that were created with the `/v1.0/subscriptions` endpoint, have stopped receiving notifications since 2019/12/01 around 21:00 GMT. Same event also occured a couple of days earlier on Friday, for approximately five hours.

Moving forward, after this is resolved, some kind of status page would improve greatly the visibility and state of the API.

**Comment by sidxyz** [comment]
I have a subscription on any changes in the user resource and even I am not receiving any notifications for the same. I tried deleting my existing subscriptions and creating new ones but still the same case in the past 24 hours.

**Comment by afkirzak** [comment]
The same issue here. I'm not able to receive notifications even with existing and new subscriptions.

**Comment by timothyhoffmann** [comment]
Ditto. Received one notification out of 6+ that should have happened.

**Comment by JordanW7** [comment]
https://github.com/microsoftgraph/microsoft-graph-docs/issues/6462#issuecomment-561340632

**Comment by randalpinto** [comment]
We're now getting 95% or so of the expected notifications but still some missing. What's everyone else's experience?

**Comment by timothyhoffmann** [comment]
Working normally on Wednesday but I have a very low volume.  Note that Support Requests via the Azure Portal are only available to those who have Developer or higher paid support plans.  The Basic plan does not have technical support.

**Comment by sidxyz** [comment]
I am still not receiving any notifications.
 I did try using the beta subscription api as well but no luck.

I am now changing my approach to polling each resource on a timed frequency(mostly going to rely on Delta query) to achieve the desired functionality.
 If anybody comes to know anything about any update on health of Subscription/Webhook, please reply to this thread or email me at sidrt18@gmail.com.

Thanks!
