### ISSUE TITLE
TeamsAppId for OneNote is not working

### ISSUE THREAD

**Issue by LukasNespor** [microsoftgraph/microsoft-graph-docs#6484]
Documentation says that teamsAppId is 0d820ecd-def2-4297-adad-78056cde7c78 but when it is used as with other type of Tabs it ends as bad reguest "Invalid bind property name teamsApp in request.".

"teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/0d820ecd-def2-4297-adad-78056cde7c78"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#custom-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by babakdanyal** [comment]
I am getting the same issue, what did you end up using ?

**Comment by LukasNespor** [comment]
> I am getting the same issue, what did you end up using ?
> Invoke-RestMethod : {
> "error": {
> "code": "BadRequest",
> "message": "teamId needs to be a valid GUID.",
> "innerError": {
> "request-id": "3b179bab-eba8-47c3-91a0-07ff2e775244",
> "date": "2020-02-28T02:40:51"
> }
> }
> }

Well, I stopped implementing my idea, because I didn't manage to create the tab using API.

**Comment by aayush-scalex** [comment]
I was also facing the same issue, 
I'm using the following API - 
https://graph.microsoft.com/v1.0/teams/{team-id}/channels in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)

earlier I used team-id which is like 19:1b5dd...@thread.xyz and it showed error. 

Instead, use group id  which is GUID type

**Comment by aayush-scalex** [comment]
> Documentation says that teamsAppId is 0d820ecd-def2-4297-adad-78056cde7c78 but when it is used as with other type of Tabs it ends as bad reguest "Invalid bind property name teamsApp in request.".
> 
> "[teamsApp@odata.bind](mailto:teamsApp@odata.bind)": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/0d820ecd-def2-4297-adad-78056cde7c78"
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
> * Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
> * Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#custom-tabs)
> * Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
> * Product: **microsoft-teams**
> * Technology: **microsoft-graph**
> * GitHub Login: @nkramer
> * Microsoft Alias: **MSGraphDocsVteam**



> Documentation says that teamsAppId is 0d820ecd-def2-4297-adad-78056cde7c78 but when it is used as with other type of Tabs it ends as bad reguest "Invalid bind property name teamsApp in request.".
> 
> "[teamsApp@odata.bind](mailto:teamsApp@odata.bind)": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/0d820ecd-def2-4297-adad-78056cde7c78"
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
> * Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
> * Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#custom-tabs)
> * Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
> * Product: **microsoft-teams**
> * Technology: **microsoft-graph**
> * GitHub Login: @nkramer
> * Microsoft Alias: **MSGraphDocsVteam**

I was also facing the same issue, 
I'm using the following API - 
https://graph.microsoft.com/v1.0/teams/{team-id}/channels in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)

earlier I used team-id which is like 19:1b5dd...@thread.xyz and it showed error. 

Instead, use group id  which is GUID type

**Comment by Nikitha-MSFT** [comment]
Based on the error message, the server is not complaining about the teamsApp@odata.bind property but the actual request url. 

The url to add a tab is POST /teams/{team-group-id}/channels/{channel-id}/tabs 
Could you please check by adding the team-group id?

**Comment by Nikitha-MSFT** [comment]
@LukasNespor - Are you still facing the issue, if yes could you please reopen the issue. As of now closing the issue at our end.
