### ISSUE TITLE
update permission requirements per MC196237

### ISSUE THREAD

**Issue by mrkeiths** [microsoftgraph/microsoft-graph-docs#6487]
According to MC196237, additional permissions will be required to access the beta *and* v1 reporting APIs beginning 12/16/2019.

The announce indicates a user who calls reporting APIs must also be assigned of one of the following roles in AAD:
Company Administrator, Exchange Administrator, SharePoint Administrator, Lync Administrator, Global Reader, Reports Reader.

The "Permissions" section *for each of the APIs* (in beta and v1 docs) should be updated to include the additional role requirements detailed in MC196237.

Thank you,
Keith

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d5bc441-99d4-0e12-cd62-214e4c78d3d4
* Version Independent ID: e5770dea-769f-47dc-6c3b-12b49ca3aaf6
* Content: [reportRoot: getMailboxUsageDetail - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-getmailboxusagedetail?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/reportroot-getmailboxusagedetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-getmailboxusagedetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as the docs have been updated.
