### ISSUE TITLE
Delta calls failing with error "Failure in forwarding request"

### ISSUE THREAD

**Issue by vikbehal** [microsoftgraph/microsoft-graph-docs#6493]
https://graph.microsoft.com/beta/teams//channels//messages - Works
https://graph.microsoft.com/beta/teams//channels//messages/Delta - Does not work

Error message:
The response is a HTTP 503 code": "Proxy_InternalServerError", "message": "Failure in forwarding request.".
Microsoft Support says, "Because this is a Beta API, the next step is to post this as an issue on the GitHub page"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fa912d-43d1-099b-44d5-fdcdaae00db7
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessages: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Please let us know, if you are still facing any issue.
