### ISSUE TITLE
The import request payload is incorrect. 

### ISSUE THREAD

**Issue by lanatmwan** [microsoftgraph/microsoft-graph-docs#6494]
https://docs.microsoft.com/en-us/graph/api/intune-enrollment-importedwindowsautopilotdeviceidentity-import?view=graph-rest-beta#feedback

The request doesn't need (or preserve) several of the fields listed as they are really return fields.  As far as I can tell, these are the only fields that are used for a request. 

{
  "importedWindowsAutopilotDeviceIdentities": [
    {
      "@odata.type"					: "#microsoft.graph.importedWindowsAutopilotDeviceIdentity",
      "groupTag"					: "My Group Tag",
      "serialNumber"				: "My device Serial Number",
      "hardwareIdentifier"			: "MyHardwareHashValue",
      "assignedUserPrincipalName"	: "WhatIsProperUPNFormat?"
    }
  ]
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93158982-59c0-7492-2002-d7be7a09a46f
* Version Independent ID: ada38fe4-a30c-d442-bb54-2b1c9432ca95
* Content: [import action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-importedwindowsautopilotdeviceidentity-import?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-import.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-import.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for providing this clarification!
