### ISSUE TITLE
Doc is unclear or alternatives or constraints regarding usage on migrations.

### ISSUE THREAD

**Issue by annerajb** [microsoftgraph/microsoft-graph-docs#6495]
&gt;Note: We don't recommend that you use this API for data migration. It does not have the throughput necessary for a typical migration.

Is there any other API  that we can be pointed too?
What are the throughput restrictions can I add a second of sleep between message post?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
The feature for migration is on our backlog. However we have no dates to share right now.
