### ISSUE TITLE
GET (in beta) /teams/{teamId}/channels/{channelId}/filesFolder

### ISSUE THREAD

**Issue by nickhodge** [microsoftgraph/microsoft-graph-docs#6498]
Can this endpoint support $expand=children?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f436918-2c09-be9c-b463-18de76eafa48
* Version Independent ID: 3af5bde5-0179-4cd7-eacd-a903f3cb106b
* Content: [Get a file or folder - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/driveitem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-get.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-msft** [comment]
pls use [drive APIs](https://docs.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0)  to get contents of files folder, this API only gives link to files folder.
