### ISSUE TITLE
Open type entity types have incorrect POST request payload samples

### ISSUE THREAD

**Issue by marych** [microsoftgraph/microsoft-graph-docs#65]
The request object should not have any "entitytype" wrapping of all properties. I noticed it in the following files:
group_post_groups.md 
user_post_users.md 
device_post_devices.md 
directoryrole_post_directoryroles.md 

A sample group creation request is:
{  
    "description": "description-value",
    "displayName": "displayName-value",
    "groupTypes": [
      "Unified"
    ],
    "mailEnabled": true,
    "mailNickname": "mailNickname-value",
    "securityEnabled": false
}
Note that mail attribute is read-only, so it shouldn't be included in the request payload. On the other hand securityEnabled is required and needs to be included.

**Comment by martellaj** [comment]
Hey, @marych. Thanks for submitting the issue. Please include links to make triaging these a little easier.

I'm also confused about the `securityEnabled` bit. I thought @dkershaw10 [alluded that it is **not** required](https://github.com/OfficeDev/microsoft-graph-docs/issues/55) when creating a group, or did I misread that?

**Comment by martellaj** [comment]
Okay, action items from this issue are:
* Remove the outlying JSON object from requests in creation examples
* Update the sample request for creating a group to exclude `mailEnabled` and include `secruityEnabled`

Does that look right, @marych?

**Comment by marych** [comment]
Yes, the 2 actions items look right.

**Comment by marych** [comment]
"mail" needs to be excluded rather than "mailEnabled". Other than that the 2 action items looks ok to me.

**Comment by martellaj** [comment]
What `mail` are you talking about? `mailEnabled` and `mailNickname` are the two properties in the request, and both are required AFAIK.

**Comment by martellaj** [comment]
I made the changes to the files you suggested, but have a couple open issues before closing this issue. I found similar cases in the following files, but unsure if that's how they work or not. @yinaa, @dkershaw10 - you might know better.

* [device_post_registeredowners](https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/device_post_registeredowners.md)
* [device_post_registeredusers](https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/device_post_registeredusers.md)
* [directoryrole_post_members](https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryrole_post_members.md)

@dkershaw10, @angelgolfer-ms - Also, it looks like in [group_post_groups](https://github.com/OfficeDev/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group_post_groups.md), we recently made a change that says don't set `securityEnabled` if it's an Office 365 group, but when I tried to create a group without that, I got a 400. Is this a doc or API bug?

**Comment by dkershaw10** [comment]
Don't set securityEnabled = true for an O365 group.  I guess the doc needs to be more explicit;)

**Comment by angelgolfer-ms** [comment]
Since securityEnabled is defined as a Boolean, it has to have a value either true or false. So I assume Dan's saying "don't set securityEnabled to true" == "set securityEnabled to false", and if we "don't set securityEnabled", it's by default true for a new group?

**Comment by dkershaw10** [comment]
The documentation appears to be correct now.
