### ISSUE TITLE
Expanding group owners and members

### ISSUE THREAD

**Issue by nozhT** [microsoftgraph/microsoft-graph-docs#6500]
This page says that the owners relationship is limited to 10 users. I have 2 questions about this:

1. Trying the API (groups/group-id?$expand=owners) on a group with 100 owners returned 20 of them instead of 10. Are the docs out of date?
2. If a group has more than 10 owners, is it guaranteed that expanding the owners will return at least 10 owners?
3. Testing group members also returns the same results as 1. Is the 10 (or 20) limit also present for group members?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@davidmu1 I can work with you on this.  An update will be required here.
@nozhT Please see https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#expand-parameter for a bit more info which might help a bit.  We will still need to make a few doc changes though, so thanks for filing this.

**Comment by yyuank** [comment]
The limit of number of owners for a group should be 100. There's no limit for the number of members in a group (can be as many as the number of users in a tenant). $expand typically returns a max of 20 items.
