### ISSUE TITLE
Link to path syntax

### ISSUE THREAD

**Issue by danyoel** [microsoftgraph/microsoft-graph-docs#652]
The Graph API reference should describe where to learn more about the “path syntax” because it is not documented on https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/driveitem. Suggested content is at https://dev.onedrive.com/misc/addressing.htm.

**Comment by jthake-msft** [comment]
Closing as docs have significantly improved in this way now that reflect this. https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_list_children
