### ISSUE TITLE
Get Group by ID not working

### ISSUE THREAD

**Issue by krisrajzlive** [microsoftgraph/microsoft-graph-docs#6521]
Issue:
I have been trying to get Group ID with the help of Graph Explorer but getting 404 error. It would be of great help to be able to get the group by displayname or email id. In many cases it impossible to get the group by Id. Ex. I have created a group programmatically by passing the group name from a config file, next time when I run the application I wanted to determine the group exists by its name! 

I have tried by id, name, filters none of them working. Any timely help would be much appreciated.

Article:
https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http

**Comment by ferronsw** [comment]
You can accomplish that with a request like this:

`https://graph.microsoft.com/v1.0/groups?$filter=displayName eq 'Groepname'`

Docs: https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter

**Comment by krisrajzlive** [comment]
Thanks indeed, I did try but none of the methods specified in docs are working! Also tried beta but still no respite!

**Comment by ferronsw** [comment]
Do you have an example of the request you're making? The provided example should work.

**Comment by krisrajzlive** [comment]
Request:
https://graph.microsoft.com/v1.0/groups?$filter=displayName eq 'krisrajzlivegrouptest'

Response:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groups",
    "value": []
}
with status code 200
