### ISSUE TITLE
C# does not contain definition for 'Messages'

### ISSUE THREAD

**Issue by blackfire56** [microsoftgraph/microsoft-graph-docs#6523]
Using v1.20.0 of Microsoft.Graph (Current Latest version), I try to get the messages of a channel using the request sample for c# and get the following error.

 'IChannelRequestBuilder' does not contain a definition for 'Messages' and no accessible extension method 'Messages' accepting a first argument of type 'IChannelRequestBuilder' could be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mayureshjaiswal** [comment]
I'm using version 1.21.0 but still getting the same error.

**Comment by ks-Javin** [comment]
I receive the same issue. Still not working.

**Comment by HaiyeWang0717** [comment]
I am using version 3.5, same error.

**Comment by HunaidHanfee-MSFT** [comment]
Verified with sample code, it's working, suggestions are - 
-  Use Graph SDK version: Microsoft.Graph.Beta -Version 4.8.0-preview
- Graph endpoint: https://graph.microsoft.com/beta/teams/{Teams GUID id}/channels/{Channel Id e.g 19:XXX}/messages
Permissions: ChannelMessage.Read.All (Admin consent), 
Code: 
```
using Microsoft.Graph;

GraphServiceClient graphClient = this.GetGraphServiceClientBeta("{Access token}");
var messages = await graphClient.Teams[teamId].Channels[channelId].Messages
    .Request()
    .GetAsync(); 
```
