### ISSUE TITLE
Filtering by Categories

### ISSUE THREAD

**Issue by AFrazier-Git** [microsoftgraph/microsoft-graph-docs#6526]
Took me awhile to figure this out so in case anyone else needs it... you can filter by category using the following syntax:

categories/any(c:c eq 'Your Category')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#feedback)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @AFrazier-Git 
Thanks for pointing this out.
To make sure I'm understanding the suggestion properly, are you referring to messages or to another type of object?

**Comment by AFrazier-Git** [comment]
Hi @baywet 

In this case it was an Event. I'm not sure if it works on other objects. To clarify, it wasn't a suggestion, but an observation. I just left the comment there in case someone else was searching for a way to filter by category and was stuck like I was.

Sadly, this syntax doesn't appear to work for all types of collections. For example, I was unable to use it to filter by attendees, for example: attendees/any(c:c.emailAddress.name eq 'John Doe')

**Comment by baywet** [comment]
Thanks for the insight and the quick response!

**Comment by scrimo** [comment]
Hy! 
I'm using the categories/any(c:c eq 'Your Category') filter to receive only E-Mails with a specific Categorie, works great! I need a simple extension of this query but i can't figure out if its possible nor how it works.
I need all Mails which:
have CAT A
AND
not have CAT B

The lambda /all Operator isn't available/working. And i cant drop an 'and' in the any lambda of the first expression like categories/any/c:c eq 'CAT A' and c ne 'CAT B') for example.

Any idea?

Thanks,
Jakob

**Comment by SteveTapajna** [comment]
I've been fighting with this for a day, I'm also trying to find emails in graph that DON'T have any categories.  I can use in the filter categories/any()  and that will return ones WITH but I can't seem to figure out how to flip it around as not categoies/any() or categories/any() = false won't work.

**Comment by neoadventist** [comment]
@jthake-msft @SteveTapajna i'm struggling with the same thing! I want to try to find all of the  emails which do not have a certain field in the categories or have *no* field at all...maybe I can try searching to see if the field is blank instead of empty? Anyone have any hints? @AFrazier-Git

**Comment by AFrazier-Git** [comment]
@neoadventist I did some brief testing after @scrimo posted and didn't find a solution either. You may consider opening a new issue to get the attention of someone on the Microsoft Graph team. Sorry and good luck!
