### ISSUE TITLE
contractType possible values (enum)

### ISSUE THREAD

**Issue by colemujadzic** [microsoftgraph/microsoft-graph-docs#6531]
While the article states that "contractType" (string) can be any one of three possible values (SyndicationPartner, BreadthPartner, or ResellerPartner), `GET /contracts/` returns these values as enumerated string values.

Example:
`
{
                "id": "...",
                "customerId": "...",
                "displayName": "...",
                "contractType": "3",
                "deletedDateTime": null,
                "defaultDomainName": "example.com"
},
`

Can the documentation be updated to include which enumerated value corresponds to which contract type? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e50f67b2-76a0-886a-dd3a-5e33c1f2ff51
* Version Independent ID: 5e087d1b-13ab-58f1-93be-adaa80fa97d2
* Content: [Contract resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/contract?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/contract.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/contract.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
**contractType** is of type String but with the specified possible values. 
No updates identified for the page for now. Closing the issue.
