### ISSUE TITLE
What is a "post" resource?

### ISSUE THREAD

**Issue by guillaumemeyer** [microsoftgraph/microsoft-graph-docs#6543]
This page mentions the "post" resource... but it's not mentioned in the supported resource list...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fbbb2e0-38fb-fb9a-da33-138c09262fbd
* Version Independent ID: 583af78a-8160-e4d3-9710-998b6e6f13f1
* Content: [Add custom data to resources using extensions - Microsoft Graph](https://docs.microsoft.com/en-us/graph/extensibility-overview)
* Content Source: [concepts/extensibility-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/extensibility-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
It's a conversation post.  See https://docs.microsoft.com/en-us/graph/api/resources/post?view=graph-rest-1.0.
