### ISSUE TITLE
Verified domain name

### ISSUE THREAD

**Issue by guillaumemeyer** [microsoftgraph/microsoft-graph-docs#6544]
As we're only passing the domain name without extension (graphlearn without .com), it cannot be considered as a "verified" domain, as you can have multiple companies sharing the same name with different extensions.
Another question, as the app may be registered from Azure, how could you correlate it with a domain registered with another Office 365 account?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ffa23e-2e9e-690f-ac7f-6bd71f91bb3e
* Version Independent ID: a28c9070-172f-f26e-4e79-916439f4ee94
* Content: [Add custom data to groups using schema extensions  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/extensibility-schema-groups)
* Content Source: [concepts/extensibility-schema-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/extensibility-schema-groups.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Sorry for the late response.  The issue you point out with domains is indeed a valid concern.  I will be taking this up with the team.
Not sure I understand the question around domain registration from Azure and O365...

**Comment by guillaumemeyer** [comment]
Can't remember what my question was exactly... it was a long time ago ;-)
BTW, in the "See Also" section, there is an invalid link "Adding and Verifying a Domain for the NEW Office 365" that points to "https://office365support.ca/adding-and-verifying-a-domain-for-the-new-office-365/"

**Comment by dkershaw10** [comment]
I'll fix the link.  The other issue you pointed out is a bug/issue that I've added to the backlog.  Unfortunately I don't have an ETA for when this will get fixed.
