### ISSUE TITLE
Large file with upload session documentation questions

### ISSUE THREAD

**Issue by Ibrahim-Islam** [microsoftgraph/microsoft-graph-docs#655]
> To upload the file, or a portion of the file, your app makes a PUT request to the uploadUrl value received in the createUploadSession response. You can upload the entire file, or split the file into fragments, as long as the **_`maximum bytes in any given request is less than 60 MiB`_**. The fragments of the file must be uploaded sequentally in order. Uploading fragments out of order will result in an error.
Note: If your app splits a file into multiple fragments, the size of **_`each fragment MUST be a multiple of 320 KiB`_**. **Using a fragment size that does not divide evenly by 320 will result in errors committing some files.**

1. So each request limit is 60 MiB or 320 KiB?
2. **fragment size that does not divide evenly by 320** what does this mean?

**Comment by darkocolak** [comment]
1. From my understanding, for larger files you have to split them up in fragments.
Each fragment can be 60MiB large, not larger. So its 60MiB.
2. Each fragments length has to be a multiple of 320KiB (327680 bytes), meaning that your chunk size should be dividable by 327680. For example you can set chunk size to 10MiB by setting 327680 * 32 as fragment size.
