### ISSUE TITLE
Is there a correct way to upload logo icon for the application?

### ISSUE THREAD

**Issue by lesharadkovich** [microsoftgraph/microsoft-graph-docs#6557]
It seems that the update payload must be a json object, however in order to upload logo I need to provide a stream. Is there a way to do that (in js particularly)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ebf6ea-2c02-21d8-0ce6-412d8fb4e32d
* Version Independent ID: 6eee450a-b6d0-0908-0392-00e01d412185
* Content: [Update application - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by reginbald** [comment]
Any news on this?

**Comment by MattJeanes** [comment]
@reginbald check out the linked issue #7854 I raised, this endpoint has been around for a while now why hasn't it been documented yet?

**Comment by davidmu1** [comment]
The issue has been communicated to engineering. No immediate change to the page. Closing the issue.
