### ISSUE TITLE
Support for embed on onedrive for business

### ISSUE THREAD

**Issue by arsnyder16** [microsoftgraph/microsoft-graph-docs#6558]
Are there plans for adding supported for type 'embed' for onedrive for business? This would be very helpful for application are that are integrating [custom file handlers](https://docs.microsoft.com/en-us/onedrive/developer/file-handlers/?view=odsp-graph-online). Without 'embed' support file handler applications will need to try and recreate most of the sharing dialog on their own 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533d203c-42f9-0dae-1d05-7e00ca05c9e8
* Version Independent ID: 31ddb53d-5b63-2d8e-06c3-e56125d22937
* Content: [Share a file with a link - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createlink.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by JeremyKelley** [comment]
We don't currently have plans to extend the embed capability, the best place to provide the feedback that it's useful would be at https://microsoftgraph.uservoice.com
