### ISSUE TITLE
Links generated by this endpoint sometime (20% of the time) fail to load.

### ISSUE THREAD

**Issue by hassanacto** [microsoftgraph/microsoft-graph-docs#6559]
There seem to be JavaScript errors on the viewer side. Refreshing the page fixes the issue, but it happens around 20% of the time in my implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399338a3-4d90-4c9b-b3e6-a7aaf970eec5
* Version Independent ID: 22fb7721-70f4-92af-db16-42967cd0043d
* Content: [driveItem: preview - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/driveitem-preview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-preview.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
can you please submit this as an issue here please?
https://github.com/OneDrive/onedrive-api-docs/issues
