### ISSUE TITLE
OData Query Parameters not supported for directoryRoles

### ISSUE THREAD

**Issue by ianByrne** [microsoftgraph/microsoft-graph-docs#656]
In contrast to [the docs](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/directoryrole_list), it seems the searching/filtering [OData query params](https://graph.microsoft.io/en-us/docs/overview/query_parameters) are not supported for:

`GET https://graph.microsoft.com/v1.0/directoryRoles`

I tried:

`?$filter=startswith(displayName,'Exchange')`

```
{
  "error": {
    "code": "Request_UnsupportedQuery",
    "message": "Filtered searches against this resource are not supported.",
    "innerError": {
      "request-id": "[id]",
      "date": "2016-12-05T18:25:52"
    }
  }
}
```

And:

`?$search="Exchange"`

```
{
  "error": {
    "code": "Request_UnsupportedQuery",
    "message": "Full Text queries must use the api-version 'beta'.",
    "innerError": {
      "request-id": "[id]",
      "date": "2016-12-05T18:27:38"
    }
  }
}
```

Tried again with the `beta` endpoint:

`GET https://graph.microsoft.com/beta/directoryRoles?$search="Exchange"`

```
{
  "error": {
    "code": "Request_UnsupportedQuery",
    "message": "Full Text queries must use the api-version 'beta'.",
    "innerError": {
      "request-id": "[id]",
      "date": "2016-12-05T18:28:42"
    }
  }
}
```

(although the docs allude to $search being only available for the messages endpoint?)

**Comment by dkershaw10** [comment]
Indeed.  $filter queries are not supported for directoryRoles directoryRoleTemplates or subscribedSkus.  We need to call this out in the docs (will close when docs updated).  Also $search is not supported by any directory objects currently.

**Comment by dkershaw10** [comment]
See #853

**Comment by sankarnair123** [comment]
Are there plans to support this type of queries with beta or v1.0 APIs ?

https://graph.microsoft.com/beta/users?$search="<firstname> <lastname>" ?
