### ISSUE TITLE
Replace error

### ISSUE THREAD

**Issue by chathway** [microsoftgraph/microsoft-graph-docs#6560]
The description states that if a schedule already exists it will be replaced however, I receive the error below
{
    "error": {
        "code": "Conflict",
        "message": "{\"error\":{\"code\":\"ResourceExists\",\"message\":\"Sorry, this team has already been provisioned with a schedule\",\"details\":[],\"innererror\":{\"code\":\"AadGroupIsLinkedToTeamsTeam\"}}}",
        "innerError": {
            "request-id": "8bbba02b-0eb0-491b-a09d-b32ef39147d3",
            "date": "2019-12-11T15:31:19"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe2af57-5984-0d8d-5438-f9e2e76c2f92
* Version Independent ID: 3a9968ee-64b8-8d97-2567-4e18017be434
* Content: [Create or replace schedule - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-put-schedule?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/team-put-schedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-put-schedule.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ChetanSharma-msft** [comment]
Hello @chathway - Sorry for delay in response.
We will check on it from our end and let you know the updates.

**Comment by Meghana-MSFT** [comment]
@chathway - We tried to update the schedule twice by changing the timezone. It did run successfully.
![image](https://user-images.githubusercontent.com/81138249/209651186-a46f7ef7-968d-4609-a394-d542b10a2509.png)
Can you please confirm if you are still facing this issue? Are you trying it in the same way I tried?

**Comment by lramosvea** [comment]
Closing as this seems to be resolved. Please feel free to reopen otherwise.
