### ISSUE TITLE
Information about servicePrincipal.oauth2Permissions  is missing

### ISSUE THREAD

**Issue by kalyankrishna1** [microsoftgraph/microsoft-graph-docs#6562]
The servicePrincipal.oauth2Permissions collection is present on AAD Graph, but missing from the servicePrincipal object documentation here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6dddf0-8459-cb01-7b37-6bf881f88b11
* Version Independent ID: 57eebfc1-ffde-35ef-fbb6-5a1c19dae722
* Content: [Property differences between Azure AD Graph and Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences#serviceprincipal-property-differences)
* Content Source: [concepts/migrate-azure-ad-graph-property-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/migrate-azure-ad-graph-property-differences.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Documented in the referenced article:


oauth2Permissions | beta  - publishedPermissionScopes v1.0  - oauth2PermissionScopes | Renamed.

Closing the issue.
