### ISSUE TITLE
Example 3: Cards - How do I generate attachment id for request?

### ISSUE THREAD

**Issue by latonita** [microsoftgraph/microsoft-graph-docs#6565]
Shall I request this ID from somewhere? To make sure its not duplicated.
How do I generate attachment id for my POST request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
A New Guid works fine. The Id in the body and the attachments element however needs to be the same.

**Comment by latonita** [comment]
Thank you, @RamjotSingh 
Please do minor update to that section to reflect this.
