### ISSUE TITLE
Some calendars cannot be deleted and are only returning an 'UnknownError' with no further details

### ISSUE THREAD

**Issue by mtwelve** [microsoftgraph/microsoft-graph-docs#6572]
Hello,

I am trying to clear up some calendars in a number of user mailboxes
Using the method on this page I have managed to delete roughly 1/3 of the calendars however the majority of requests simply return 'UnknownError'.
I have attempted a number of different syntax, renaming the calendar to include no special characters, tried both v1.0 and beta.

Any ideas why? and how to fix it?

Invoke-RestMethod : {
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "9c9edce6-aec7-4308-86c1-f6048a137e57",
      "date": "2019-12-11T22:32:04"
    }
  }
}
At line:4 char:13
+ $response = Invoke-RestMethod -Method Delete -Uri $uri -Headers $head ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad1b90a3-fe88-c422-cc68-336039a8b905
* Version Independent ID: 7c555b47-8915-e18e-682a-931e137fe80e
* Content: [Get calendar - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@mtwelve , if you haven't found an answer to your code question yet, may I suggest you post your question on stackoverflow and tag it with "microsoftgraph" please? 
The GitHub issues site is for documentation issues and few product side folks monitor questions on this site. If it turns out there is something lacking in the docs, feel free to reopen this GitHub issue. Thank you for your support!
