### ISSUE TITLE
Mailfolders.delta(deltaLink) is not tracking message changes in a mail folder.

### ISSUE THREAD

**Issue by kumbhaj** [microsoftgraph/microsoft-graph-docs#6576]
Mailfolders.delta(deltaLink) is not tracking message changes in a mail folder. Its only tracking new folder creation or deletion. I want to get the messages that have changed in using that single delta link.

**Comment by jasonjoh** [comment]
That's the correct behavior.

https://docs.microsoft.com/en-us/graph/api/mailfolder-delta?view=graph-rest-1.0&tabs=http

> Get a set of mail folders that have been added, deleted, or removed from the user's mailbox.

There is no single delta link for all messages in a mailbox. You have to do it per folder.

https://docs.microsoft.com/en-us/graph/api/message-delta?view=graph-rest-1.0&tabs=http

> Get a set of messages that have been added, deleted, or updated **in a specified folder**.

You can suggest a single delta for all messages over on [UserVoice](https://microsoftgraph.uservoice.com/).
