### ISSUE TITLE
Clarification on the members returned by the transitiveMembers query

### ISSUE THREAD

**Issue by bpcastilho** [microsoftgraph/microsoft-graph-docs#6577]
Issue: Doc description

Article: [https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http](https://docs.microsoft.com/en-us/graph/api/group-list-transitivemembers?view=graph-rest-1.0&tabs=http)

Even though we mention that groups can have the various members, there's still some confusion when we get the nested groups and their members, instead of only their members.
Probably an example would clarify this.

**Comment by davidmu1** [comment]
I think this is clear in the description:

Get a list of the group's members. A group can have users, devices, organizational contacts, and other groups as members. This operation is transitive and returns a flat list of all nested members.

It states that groups can be member and that a flat list of nested members is returned. This seems to makes sense that all member groups and their members would be returned in the list.

No change identified for the page. Closing the issue. Please reopen if you feel that you want to contribute an example that you think should be on the page.
