### ISSUE TITLE
Assertion around applicability to groups is unclear

### ISSUE THREAD

**Issue by HoCGeek** [microsoftgraph/microsoft-graph-docs#6585]
This page says "deleted items functionality is only supported for the application, group and user resources", but the "directory resource type (deleted items)" page says "Currently, deleted items functionality is only supported for Office 365 groups and users."  Which one is correct?  Applications and groups can be restored?  All groups can be restored?  Or only users and specifically O365 groups can be restored?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e760d3-a032-5214-1fb2-e8c811d48a57
* Version Independent ID: 2f86af0c-8ed0-16f1-674c-91c6ebfb045d
* Content: [Restore deleted item - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directory-deleteditems-restore?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/directory-deleteditems-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directory-deleteditems-restore.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Corrected the text.

**Comment by HoCGeek** [comment]
May I ask what text was corrected and where?  The document linked in the "Document Details" above doesn't show any modifications since October 20th...?
