### ISSUE TITLE
Subscription for events in user created calendar

### ISSUE THREAD

**Issue by vadzappa** [microsoftgraph/microsoft-graph-docs#6595]
Hello!

Scenario: listen for changes in custom Calendar (_work calendar_ for example).

Setup done:
1. Subscription created with specific notificationUrl
2. Notification URL tested with default Calendar (see screenshot for calendar set)
3. Event created for default calendar reaches notificationUrl

Issue? (probably I'm missing smth, help appreciated at this point)
1. Event created for _Work stuff_ calendar doesn't reach notificatoinUrl - by not reaching I mean URL isn't get trigerred at all

Question: is it designed to work only with default calendar or I'm doing smth wrong?
Scopes list: `profile offline_access email User.Read User.ReadBasic.All Calendars.ReadWrite Calendars.ReadWrite.Shared`

P. S. I'm able to fetch ALL calendars, fetch events from these calendars, just notifications for non-default calendar don't come to notificationUrl

![image](https://user-images.githubusercontent.com/3742456/70790667-3d609700-1d9e-11ea-92ee-0855e353889e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
hi @vadzappa 
Thanks for your question.
This GitHub repository is reserved for questions/content fixes around the Microsoft Graph documentation.
If you have a question on "how can I do ..."  https://stackoverflow.com/ with the tag [microsoft-graph] is much more appropriate.
Closing for now.
