### ISSUE TITLE
Range endpoint to slow

### ISSUE THREAD

**Issue by yuriy-belelya-akqa** [microsoftgraph/microsoft-graph-docs#6596]
/range(address='A1:FZ200') - I have 504 (Gateway Timeout) response every time.
Is there any chance to fetch big amount of data form wide range?
Response time &gt; 30s.

{
    "error": {
        "code": "UnknownError",
        "message": "",
        "innerError": {
            "request-id": "461ed234-eb86-48d2-b932-b05853a310d1",
            "date": "2019-12-13T11:25:19"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a4a716-23f8-6290-409a-aa864a68c5f0
* Version Independent ID: 8fe5bf33-4393-800f-1c83-c6fddf81a37d
* Content: [Worksheet: Range - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/worksheet-range?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/worksheet-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/worksheet-range.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ValeGV** [comment]
I used this endpoint too for long time and starting from yesterday I got the same error.

**Comment by yuriy-belelya-akqa** [comment]
Currently works fine. Response time: 1-3s. Seems like temporary API issue.
