### ISSUE TITLE
objectId property is not mentioned on this page

### ISSUE THREAD

**Issue by leniel** [microsoftgraph/microsoft-graph-docs#6598]
I was trying a Microsoft Graph API call like this:

```
B2CService.BuildUrl("/users", $"$filter=signInNames/any(x:x/value%20eq%20%27{encodedEmail}%27)%20or%20otherMails/any(y:y%20eq%20%27{encodedEmail}%27)&$select=id,displayName,{extensionAttribute}");
```

`id` was not returning... the correct property name is `objectId`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @leniel,

there are differences between Azure AD Graph and Microsoft Graph resources. In this case, the returned value is an Azure AD Graph resource and represents an [user identity](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/entity-and-complex-type-reference#user-entity) object. Therefore, the [user resource type](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0) documentation is correct and from my point of view this issue can be closed. 

Ping @dkershaw10

**Comment by leniel** [comment]
@JarbasHorst uhmmm... why is that under Microsoft Graph REST API v1.0 page?

**Comment by JarbasHorst** [comment]
Hi @leniel 

as far as I understand, the objectId is an user's property that you get when using the Azure AD Graph API. The https://graph.microsoft.com/v1.0/users API doesn't have the objectId property. Check out the output of the users API [here](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#code-try-1). I hope that helps 😀

Just out of interest, what URL do you get when calling the B2CService.BuildUrl method?

**Comment by leniel** [comment]
The URL is like this:

`https://graph.windows.net/tenantName/users?api-version=1.6&$filter=...`

You're right... I'm using Azure AD Graph Client. Sorry for the confusion.
