### ISSUE TITLE
Broken removed/deleted delta entries for new events outside the calendarView time frame

### ISSUE THREAD

**Issue by mattlaabs** [microsoftgraph/microsoft-graph-docs#6599]
When making a (non-initial) delta request, new events created since the previous delta request are shown with @removed reason=deleted when outside the delta request's time frame (as specified with the startDateTime and endDateTime query parameters in the initial delta request).

STEPS TO REPRODUCE:
1) make initial delta request (e.g. for entire year 2020)
GET https://graph.microsoft.com/v1.0/me/calendarView/delta?startdatetime=2020-01-01T00:00:00.000000&enddatetime=2021-01-01T00:00:00.000000
2) follow @next link until @delta link is given
3) create new event in 2019
POST https://graph.microsoft.com/v1.0/me/events {"subject": "test"}
4) call delta link from (2)

EXPECTED BEHAVIOUR:
events outside the time frame of this delta should be ignored.

I believe this is also the reason for https://stackoverflow.com/questions/54641708

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8f0b0d-c0f7-7774-d5fb-5df3c09dc83a
* Version Independent ID: f23af4a1-bf3c-2ef1-a94f-79be31ea6618
* Content: [user: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delta.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mattlaabs** [comment]
Sorry, I just realized that this is under the wrong page - it should be under the events delta. Can you move this or should I recreate it at the correct page?

**Comment by baywet** [comment]
hi @mattlaabs 
Thanks for reaching out.
Just tagged it under the proper area and assigned (hopefully) the rightful owner.

**Comment by kishore-mohan** [comment]
@svpsiva @abheek-das @baywet is there any update on this ticket? We are using delta API but it's giving newly created record also like removed block in any other delta call with a different date range. 
is there any other quick workaround or other similar API that will solve this?

**Comment by baywet** [comment]
Hey Folks,
I have transitioned to a new role and I'm not involved in delta queries anymore.
The right contact for this should be @abheek-das

**Comment by kishore-mohan** [comment]
@abheek-das @svpsiva many facing this issue, there are a couple of them raise this issue in StackOverflow. 
[stackoverflow ticket 1](https://stackoverflow.com/questions/58949395/unexpected-deleted-event-in-calendarview-delta-endpoint
)
[stackoverflow ticket 2](https://stackoverflow.com/questions/56965073/problem-to-use-microsoft-graph-delta-query-for-event-syncing)
Is there any priority on this issue? Or just update the microsoft graph API documentation with known issue.

**Comment by andrebel10** [comment]
Any word on this @abheek-das ?

**Comment by Harini84** [comment]
**Scenario**
When clients call the delta on calendarView API with specified time range and make some changes to the events outside the time range between the last delta/sync call, the clients see those events returned in "Deleted" reason type like-

{ "id"= "AAMkADk0MGFkODE3LWE4MmYtNDRhOS04OGQLkRkXbBznTvAADb6ytyAAA=", "@removed": {"reason"="deleted"} }

**Explanation**
This is working as designed. The public documentation will be updated accordingly. The events which got returned as "Deleted" reason type are either deleted inside the selected window or have been moved/added/updated outside the selected window.
From the perspective of the sync window, those events are not part of it and are considered as being removed/deleted from the window.

**Option 1:**
The client may need to filter the events according to their scenario.

*Option 2:*
There is sync based on events on Get/Events which does not require specifying start and end dates and provides capability to sync the entire calendar:
https://docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-beta&tabs=http

 This is currently available in MS-Graph beta (will be graduated to MS-Graph v1 in FY21 Q4).  Please try the delta sync based on events and let us know if this solves the constraint with calendarView based sync.

Thanks

**Comment by hbulens** [comment]
Regarding option 2: I am running against an issue when I drop the start and end date query options in the request.

```csharp
IEventDeltaCollectionPage deltaCollection = await graphClient.Users["myemail"].Events.Delta().Request().GetAsync();

List<Event> eventCollection = deltaCollection.CurrentPage.ToList();
bool morePagesAvailable;
do
{
  morePagesAvailable = deltaCollection.NextPageRequest != null;
  if (!morePagesAvailable)
    continue;

  deltaCollection = await deltaCollection.NextPageRequest.GetAsync(); // Error is thrown here
  eventCollection.AddRange(deltaCollection);
} while (morePagesAvailable);

```
This is the error:
```json
{
  "error": {
    "code": "InvalidDeltaToken",
    "message": "The value '...' of parameter '$deltaToken' is invalid.",
    "innerError": {
      "date": "2021-02-07T10:17:18",
      "request-id": "7ce9703d-57ff-43df-b8f6-d75e8c753505",
      "client-request-id": "7ce9703d-57ff-43df-b8f6-d75e8c753505"
    }
  }
}
```
The first page has a list of 200 events though, so it does work to some extent. However, when I pass a collection of options to the request, the exception is not thrown.

```csharp
List<QueryOption> queryOptions = new List<QueryOption>
{
  new QueryOption("startdatetime", DateTime.Now.AddDays(-7).ToString("s")),
  new QueryOption("enddatetime", DateTime.Now.AddDays(7).ToString("s")),
};

await graphClient.Users["myemail"].Events.Delta().Request(queryOptions).GetAsync();
```

But that brings us back to the original issue. Is this according to the design or is it still work in progress?

**Comment by Harini84** [comment]
Thank you for the feedback on event based sync. We are looking into the issue

**Comment by lramosvea** [comment]
https://docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http
