### ISSUE TITLE
Invalid import links

### ISSUE THREAD

**Issue by hbro** [microsoftgraph/microsoft-graph-docs#6600]
Links to GitHub raw content are invalid. Remove "%20v1.0" in the links and they work again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Thank you for catching. That is my mistake, i removed the version on the new release and had forgotten it was there. I will update this now.

**Comment by jthake-msft** [comment]
Here is the PR for the changes. I'll close this issue now https://github.com/microsoftgraph/microsoft-graph-docs/tree/jthake-postman
