### ISSUE TITLE
Delta query not supported for personal Microsoft accounts.

### ISSUE THREAD

**Issue by chenmach** [microsoftgraph/microsoft-graph-docs#6609]
When I try the users/delta endpoint I got a a 400 response says "Invalid request. Delta query is not supported by this resource.".
The documentation not says that is not support. not on this page or in the known issues page.

(works when the logged in user is work account)

And there is any easy way to check if logged in user is personal/work account?
Right now I need to handle this by try catch this exception.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8f0b0d-c0f7-7774-d5fb-5df3c09dc83a
* Version Independent ID: f23af4a1-bf3c-2ef1-a94f-79be31ea6618
* Content: [user: delta - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-delta.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @chenmach 
Thanks for reaching out!
Can you provide the request you were executing please?

**Comment by chenmach** [comment]
Sure )
Here is an example gist: (c# using Microsoft.Graph Nuget package)
https://gist.github.com/chenmach/6d7a78210ee33a40a456280577ccd39e

or simply execute https://graph.microsoft.com/v1.0/users/microsoft.graph.delta using a personal account

**Comment by baywet** [comment]
Hi @chenmach 
After some reproduction on my end and some internal investigation, it appears it is not supported at the moment.
I went ahead and authored PR #6942 to address the issue in the documentation.
If you feel this is something the Graph should support, I encourage you to post a new idea in [UserVoice](https://microsoftgraph.uservoice.com/)
Thank you for the clear repro! This eased things a lot.
The issue will be closed once the PR gets merged in.
