### ISSUE TITLE
Permissions requires / Unknown error

### ISSUE THREAD

**Issue by jonathanfernandezfm** [microsoftgraph/microsoft-graph-docs#6610]
Hi,
Are Application permissions going to be supported anytime?
Our permissions use non client client credentials grant flow, which only provides Application permissions. In this case, until this is supported, which authorization flow is recommended to grant Delegated permissions aswell? We use a JAVA API to send messages to teams channels.

Endpoint used: POST https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Supporting application permissions is something we plan to do but we do not have a date yet.

**Comment by VictorAyalaMX** [comment]
@ramjotSingh, supporting Application permissions is something my company definitely need, we want to send automatic posts to a Teams channel when critical key performance indicators and events are triggered.

**Comment by dhubbard-ag** [comment]
@RamjotSingh - we need this as well.  We could live with only being able to send messages to Channels that the Application created if granting wide-scale permissions is the road-block on this.

**Comment by phuong-vo** [comment]
@jonathanfernandezfm, for Delegated permissions if you use msgraph-sdk-java-auth to authenticate, then you can use UsernamePasswordProvider.

**Comment by kalop** [comment]
Any update about Supporting application permissions?

**Comment by RamjotSingh** [comment]
We will share on Microsoft Graph Blog once we have application permissions for this API. Since the original question for this issue was answered. Closing it.

**Comment by henrisaksi** [comment]
Any update on this? https://docs.microsoft.com/en-us/graph/teams-protected-apis states that Send message is not protected API, however, I still get this error:

{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "c305d608-6a2b-4036-a455-e4771fe6550b",
      "date": "2020-04-22T14:34:33"
    }
  }
}
