### ISSUE TITLE
List owned objects returns same payload as requesting a specific user... appears to be bug...

### ISSUE THREAD

**Issue by andrewconnell** [microsoftgraph/microsoft-graph-docs#6628]
This doesn't appear to be working in the v1 endpoint. When submitting a request for a specific user in a group, you get the user object back. Simply adding `/ownedObjects` to the end of it returns the same thing.

Example (from a M365 demo tenant):

HTTP GET https://graph.microsoft.com/v1.0/groups/f33d703e-fc70-4651-b3ee-dfaa728c4a83/members/70c095fe-df9d-4250-867d-f298e237d681

![image](https://user-images.githubusercontent.com/2068657/71008480-ad309380-20b6-11ea-86e5-42507f3f3e74.png)

Yields an identical response, except for the `@odata.context`, value, as this:

HTTP GET https://graph.microsoft.com/v1.0/groups/f33d703e-fc70-4651-b3ee-dfaa728c4a83/members/70c095fe-df9d-4250-867d-f298e237d681/ownedObjects

![image](https://user-images.githubusercontent.com/2068657/71008460-a570ef00-20b6-11ea-88a6-44604d65307f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1713e3b5-47e0-372b-8d59-6926018fde07
* Version Independent ID: aa23772f-b67b-98b0-2902-1f06a4b2e8bd
* Content: [List ownedObjects - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-ownedobjects?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-ownedobjects.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-ownedobjects.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
I suspect that the service doesn't support this deeper path through members and just ignores the ownedObjects, which is bad.  It should either fail with a 400 if not supported, or return Adele's ownedObjects.  So this looks like a bug to me.  I'll file this.  I suspect other nav properties might be busted here too, and not just ownedObjects :(

However GET https://graph.microsoft.com/v1.0/users/70c095fe-df9d-4250-867d-f298e237d681/ownedObjects should work.

**Comment by dkershaw10** [comment]
I keep changing my answer!
Sorry this is busted in beta and v1.0.  To me this is a bug

Either this returns a 400 in that this more nested path isn't supported or it works and shows you that users ownedObjects.  Instead it seems to just ignore the ownedObjects navigation property, which is bad.
At least this works for users
GET https://graph.microsoft.com/v1.0/users/70c095fe-df9d-4250-867d-f298e237d681/ownedObjects

Will check this with engineering.

**Comment by davidmu1** [comment]
You should use the users API for owned objects of a user, not the group API. Closing the issue.
