### ISSUE TITLE
Is there a way to check what permissions an admin has given an app?

### ISSUE THREAD

**Issue by liangchr** [microsoftgraph/microsoft-graph-docs#6631]
Is there a way to check what permissions an admin has given an app? e.g they might go to azure and remove some permissions they originally gave to an app. I want to be able to find out what permissions are leftover through the api.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
Just to close the loop here on this old issue:
* [`GET /servicePrincipals/{id}/appRoleAssignments`](https://docs.microsoft.com/graph/api/serviceprincipal-list-approleassignments?view=graph-rest-1.0&tabs=http) to list application permissions (app roles) granted to the app
* [`GET oauth2PermissionGrants?$filter=clientId eq {id} and consentType eq 'AllPrincipals'`](https://docs.microsoft.com/graph/api/oauth2permissiongrant-list?view=graph-rest-1.0&tabs=http) to list delegated permissions granted to the app
