### ISSUE TITLE
Add a more explicit filter example using Any()

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#6633]
Support question - how to filter on a collection property.  We should have a better example in the filter parameter section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
thanks @dkershaw10 for pointing that to our attention. I'll try to take a look at this :)

**Comment by AspenForester** [comment]
For those of us new to the game, a link to an explanation of the syntax of the `any()` query would be exceptionally helpful.

**Comment by tfrancois** [comment]
Yes would love this too...@baywet, any update on this for us please?

**Comment by mumbi-o** [comment]
Hi @AspenForester and @tfrancois, for a link on the documentation, please have a look at the **Lambda Operators** section on graph docs [here]( https://docs.microsoft.com/en-us/odata/concepts/queryoptions-usage). Section 5.1.1.10 on the ODATA docs [here ](https://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752358)might also give more details.

One example given [here ](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0) is `v1.0/groups?$filter=groupTypes/any(c:c+eq+'Unified')` but you'll find other examples such as `v1.0/groups?$filter=proxyAddresses/any(c:c+eq+'.....')` work

Lambda operators are not supported on all Graph endpoints and you might encounter an unsupported query error on endpoints where these are not supported.

**Comment by AspenForester** [comment]
But neither provide any reasonable explanation of the `c:c` syntax.  maybe that 's' refers to a string, but what's 'f'?  Or 'a'?

**Comment by FaithOmbongi** [comment]
Currently keeping an eye on this.
cc @Licantrop0 for visiblity.

**Comment by Licantrop0** [comment]
@AspenForester you're right, lambda expressions are a little harder to understand and we are not doing enough to clearly explaining them in our docs. @FaithOmbongi please track a request for this.

Basically, the `any(...)` operator returns true or false if any of the item in a collection satisfy the condition inside the parenthesis.
As the collection might be a list of objects (and not just a simple string list), the syntax requires a temporary variable (that you can name whatever you want) to iterate on, so you can even more explicit like this:
`..groups?$filter=groupTypes/any(type:type eq 'Unified")` <-- collection of simple string
`..users?$filter=assignedPlans/any(plan:plan/service eq 'xxx')` <-- collection of objects (`assignedPlans` has a `service` property)

**Comment by FaithOmbongi** [comment]
Update: Guidance for using `$filter` with the `any()` lambda operator is now available on the [OData query parameters article](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#filter-using-lambda-operators). Closing this issue.
