### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Weatwagon** [microsoftgraph/microsoft-graph-docs#6635]
Can we get a C# or PowerShell example of this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc580041-9ed5-dc21-2eb1-813152044527
* Version Independent ID: b229cada-3a68-38b5-4236-7cd0d970679f
* Content: [Permissions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamsapp-publish.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
Adding C# code snippets:

 1. Publish an app to the app catalog:
```
    GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var teamsApp = [Zip file containing a Teams app package];

await graphClient.AppCatalogs.TeamsApps
	.Request()
	.AddAsync(teamsApp);
```
 2. Upload a new application for review to an organization's app catalog:
```
       GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var queryOptions = new List<QueryOption>()
{
	new QueryOption("requiresReview", "true")
};

var teamsApp = [Zip file containing a Teams app package];

await graphClient.AppCatalogs.TeamsApps
	.Request( queryOptions )
	.AddAsync(teamsApp);
```

 3. Approve or reject an app pending review:
```
 GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var teamsAppDefinition = null;

await graphClient.AppCatalogs.TeamsApps["a761ad07-22ef-4a53-9feb-2837c8ad4a84"].AppDefinitions["YTc2MWFkMDctMjJlZi00YTUzLTlmZWItMjgzN2M4YWQ0YTg0IyMxLjEuOCMjU3VibWl0dGVk"]
	.Request()
	.UpdateAsync(teamsAppDefinition);
```

**Comment by JordyGit** [comment]
Maybe add the examples to the real docs page?

**Comment by JordyGit** [comment]
What type should the teamsApp variable be in example 1?

**Comment by Prasad-MSFT** [comment]
Ok, we will redirect to appropriate team to update the doc accordingly. Thanks!

**Comment by ChetanSharma-msft** [comment]
Hello @JordyGit - Sorry for delay in response.
Just wanted to inform you that engineering team is actively working on the documentation updates.
We will inform you once it is completed.

**Comment by ChetanSharma-msft** [comment]
Hello @Weatwagon, @JordyGit - Hope you are doing well!!

We are actively checking with engineering team on your query and let you know the updates as soon as we hear from them.

**Comment by Prasad-MSFT** [comment]
> What type should the teamsApp variable be in example 1? Because I can't find out how to become a TeamsApp from a zip file

@JordyGit - Please refer this sample which explains how to read zip file: 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/69c76fded29d7ae0fde49841d4ec9af7597ceedd/samples/graph-appcatalog-lifecycle/nodejs/Helper/AppCatalog.js#L72

We will inform documentation team also to highlight/add [these](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/69c76fded29d7ae0fde49841d4ec9af7597ceedd/samples/graph-appcatalog-lifecycle) sample references in this page. Thanks!

**Comment by Prasad-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen if required. Thanks!
