### ISSUE TITLE
which attributes support $filter query?

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#6638]
Of all the alert's properties, please document which properties support $filter query

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 067ef86f-5831-7038-a104-1003b10530fb
* Version Independent ID: b8924a52-b7d1-ebc9-f413-0eb5156f091f
* Content: [alert resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/alert?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/alert.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/alert.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by pdunnigan** [comment]
+1

**Comment by pdunnigan** [comment]
looks like createdDateTime is not supported by the $filter query

**Comment by mjeg** [comment]
I can replicate the problem. I get no filtering with "createdDateTime":

```
https://graph.microsoft.com/v1.0/security/alerts?$top=100&$filter=createdDateTime+ge+2020-03-09
```

But if I use "eventDateTime" it works as expected:

```
https://graph.microsoft.com/v1.0/security/alerts?$top=100&$filter=eventDateTime+ge+2020-03-09
```

**Comment by chinguyen1** [comment]
@bachoang, most of the properties of security alert supports $filter, except for createdDateTime for provider Office365. You can follow this [GitHub issue](https://github.com/microsoftgraph/security-api-solutions/issues/23) to keep track of the update on this. For more information, please refer to this [curated queries list](https://github.com/microsoftgraph/security-api-solutions/tree/master/Queries)
