### ISSUE TITLE
Newly created plan does not return any buckets

### ISSUE THREAD

**Issue by olasandness** [microsoftgraph/microsoft-graph-docs#6641]
In a Flow (Power Automate) I create a new Plan, put the ID in av variable and try to get hold of the default bucket (Todo) to add a few tasks. All thoug I can clearly see the "Todo" bucket in the plan itself (from the planner web app), this graph call does not return anything:

{
  "requests": [
    {
      "id": 1,
      "url": "/planner/plans/[MY PLAN ID GOES HERE]/buckets",
      "method": "GET",
      "headers": {
        "Content-Type": "application/json"
      }
    }
  ]
}

Response:

{
  "responses": [
    {
      "id": "1",
      "status": 200,
      "headers": {
        "Cache-Control": "no-cache",
        "OData-Version": "4.0",
        "Content-Type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8"
      },
      "body": {
        "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(microsoft.graph.plannerBucket)",
        "@odata.count": 0,
        "value": []
      }
    }
  ]
}

So where is the "Todo" bucket?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41fcd104-c491-d371-6417-bb46c9445d7c
* Version Independent ID: 778d4ad7-fb16-660c-f7b8-dea16652f42f
* Content: [List buckets - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/plannerplan-list-buckets?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/plannerplan-list-buckets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannerplan-list-buckets.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TarkanSevilmis** [comment]
This is by design. The UI creates the "To Do" bucket. We also show tasks without buckets in the UI now. We don't want to restrict the API usage to what the UI does so apps have freedom in representing the data as they need to.
