### ISSUE TITLE
Xamarin Sample App for handling Microsfot Graph Notifications

### ISSUE THREAD

**Issue by rkdanda** [microsoftgraph/microsoft-graph-docs#6643]
Hi, This article is really helpful and I appreciate it. In the given video I could see there is sample application to handle notifications in Xamarin Forms. Please can you share the same application.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1b0217e-a502-c4f1-748e-e1fc82ae1fd9
* Version Independent ID: 96cff4f2-4660-0721-0df7-1670108bf837
* Content: [Enabling human-centric notification experiences using Microsoft Graph notifications  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/notifications-concept-overview#feedback)
* Content Source: [concepts/notifications-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/notifications-concept-overview.md)
* Product: **notifications**
* Technology: **microsoft-graph**
* GitHub Login: @merzink
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by merzink** [comment]
Hello - All current samples are published on [GitHub](https://github.com/microsoft/MSGraphNotifications).
