### ISSUE TITLE
Raw message

### ISSUE THREAD

**Issue by xstos** [microsoftgraph/microsoft-graph-docs#6644]
Is there a way to get the entire raw message using graph?

[this issue](https://stackoverflow.com/questions/46951124/how-to-get-raw-message-with-microsoft-graph/46955711#46955711) claims there isn't but it's dated two years ago...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bf275f-7a02-7e90-120f-2e1d055dac95
* Version Independent ID: b1556931-c2fd-7400-4e45-d666a8a53540
* Content: [Get message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/message-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by xstos** [comment]
Answered my own question... It appears as though it's now supported. Didn't notice this anywhere in the documentation however. Maybe I missed it.

https://developer.microsoft.com/en-us/office/blogs/mime-format-support-for-outlook-mail-and-attachments-translate-item-id-apis-are-now-available-in-microsoft-graph-v1-0/

**Comment by angelgolfer-ms** [comment]
Hi @xstos , yes, there are two ways one can get a message in raw format (MIME): 

1. Append a $value to a [get message](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0) operation.
2. If a message is attached as a file or item to another Outlook item (message or event) or group post, you can get that message attachment by appending $value to the [get attachment](https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http#get-the-raw-contents-of-a-file-or-item-attachment) operation.

[Get MIME content of a message](https://docs.microsoft.com/en-us/graph/outlook-get-mime-message) describes the two scenarios.

In general, keeping an eye on the [Microsoft Graph blog site](https://developer.microsoft.com/en-us/office/blogs/mime-format-support-for-outlook-mail-and-attachments-translate-item-id-apis-are-now-available-in-microsoft-graph-v1-0/), the [what's new](https://docs.microsoft.com/en-us/graph/whats-new-earlier#september-2019-new-and-generally-available) topic, or the [changelog ](https://docs.microsoft.com/en-us/graph/changelog#september-2019) topic (if it's API or permissions updates) would help you discover additions and updates you were looking for. In particular, the ability to get the MIME format of a message or message type attachment was introduced in April 2019 in the beta version, and promoted to v1.0 in September a few months later.

Appreciate your continued support! Cheers!
