### ISSUE TITLE
Provide a full working example in .NET Core 3.1

### ISSUE THREAD

**Issue by alvipeo** [microsoftgraph/microsoft-graph-docs#6647]
I've been trying to use Graph API to add schema extension to a User in order to have a custom claim in my Azure B2C directory. I've tried many things and I failed. Here's my question on SO - https://stackoverflow.com/q/59395423/2896495.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca39c30c-c740-cbd5-98c5-dd1bbcc46b6a
* Version Independent ID: 2e8b2a6a-961b-40d6-acf0-a096a3aec9a1
* Content: [Create schemaExtension - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-beta&tabs=csharp#example)
* Content Source: [api-reference/beta/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/schemaextension-post-schemaextensions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MIchaelMainer** [comment]
According to SO answer, Azure B2C is not supported for MS Graph.
