### ISSUE TITLE
Missing example

### ISSUE THREAD

**Issue by nunommc** [microsoftgraph/microsoft-graph-docs#6650]
Is this page not lacking the section "Here is an example of the request."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8453dc23-7ef7-8ee0-9342-4709ee532672
* Version Independent ID: 20aa3e3e-2f05-f307-fb36-2281cafc1cbf
* Content: [organization resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/organization.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nunommc** [comment]
In terms of "hierarchy", I'm not sure the JSON representation includes that information. I thought we'd get an object with the managers and all users that report to them.

**Comment by davidmu1** [comment]
This page is what we consider a Resource page and only provides a listing of the methods that can be used for the resource and a description of the resource itself. In the Methods table, links are provided to pages that contain the request and response information for the method. In this case that would be Get organization and Update.

No change required to this page. Closing the issue.
