### ISSUE TITLE
C# sample

### ISSUE THREAD

**Issue by xstos** [microsoftgraph/microsoft-graph-docs#6654]
Would be great if there was a C# sample here. Not quite sure how to use the $ stuff with the SDK.

graphClient.Me.Messages["AAMkADQ0Y2M5NDgy....hv5BiAAA="].Request().????("$value") .GetAsync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a7cb05e-2711-7152-a596-6a057272d459
* Version Independent ID: 97b9b22a-88f1-748f-49bb-32c7d8f7b35f
* Content: [Get MIME content of a message - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-mime-message)
* Content Source: [concepts/outlook-get-mime-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-get-mime-message.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by xstos** [comment]
This [post](https://stackoverflow.com/questions/57825319/how-to-pass-value-in-request-to-get-mime-content-of-mail-using-graph-sdk-not-ap) seems to indicate the SDK doesn't quite support the fluent api yet?

**Comment by angelgolfer-ms** [comment]
Hi @xstos , you brought up something I overlooked, thank you. Snippet generation currently only applies to reference topics, not concept topics like the [Get MIME message ](https://docs.microsoft.com/en-us/graph/outlook-get-mime-message) topic.

FYI I added a REST example to the [v1](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=http#example-4) and [beta](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-beta&tabs=http#example-5) versions of the get message reference topic. Provided that the .NET SDK supports $value for get message, our regular code snippet generation will generate the corresponding C# example in the get message topic. 

I'm assigning this issue to @darrelmiller and @andrueastman for them to follow up with the C# code snippet generation for the said examples in the get message topic. Thank you!

**Comment by xstos** [comment]
Cool thanks. This is the code I ended up with:

```cs
        /// <summary>
        /// <see cref="https://stackoverflow.com/a/57830195/1618433"/>
        /// </summary>
        public static async Task<string> GetContent(this IMessageRequest r)
        {
            var x = await r.SendAsync("/$value");
            return await x.Content.ReadAsStringAsync();
        }
        
        public static async Task<HttpResponseMessage> SendAsync(this IBaseRequest r, string relativeUri)
        {
            var httpRequestMessage = r.GetHttpRequestMessage();
            httpRequestMessage.RequestUri = new Uri(httpRequestMessage.RequestUri.OriginalString + relativeUri);
            return await r.Client.HttpProvider.SendAsync(httpRequestMessage);
        }
```

usage::

```cs
    var mimeEmail = await graphClient.Me.Messages[id].Request().GetContent();
```

**Comment by angelgolfer-ms** [comment]
@andrueastman generated the C# and other language code snippets to show how to get the MIME content of a message:

- V1 version: Get message [example 4](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=csharp#example-4)
- Beta version: Get message [example 5](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-beta&tabs=csharp#example-5)
