### ISSUE TITLE
forbidden 

### ISSUE THREAD

**Issue by kriegertom** [microsoftgraph/microsoft-graph-docs#6663]
i tested with graph explorer and i always get "forbidden" I am logged in with work or school account and other requests are working well.  I can´t modify the "OnlineMeetings.ReadWrite" permissions - because of these permissions are not shown on "modify your permissions" in the graph explorer.
 {
    "error": {
        "code": "Forbidden",
        "message": "",
        "innerError": {
            "request-id": "e00bb9fb-5094-48ab-b8bb-3c9f6c8548ae",
            "date": "2019-12-20T10:18:20"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create online meeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
@tituscha @ananmishr

**Comment by buglavecz** [comment]
Hello,

I got this response:

```
{
  "error": {
    "code": "Forbidden",
    "message": "",
    "innerError": {
      "request-id": "0263ba3f-f2a9-48f8-ae0c-9a155c01085a",
      "date": "2020-01-09T11:34:50"
    }
  }
}
```
My request:
```
{
  "startDateTime":"2020-01-10T14:30:34.2444915-07:00",
  "endDateTime":"2020-01-10T15:00:34.2464912-07:00",
  "subject":"Test Meeting"
}
```
My APP id: `4ff0d082-d2ef-4c3e-9f81-9bdacc06004b`
I add `OnlineMeetings.ReadWrite.All` permission to my app. I tested in PostMan.

Thanks.

**Comment by ananmishr** [comment]
@kriegertom The Online Meeting permissions should now be in Graph Explorer.

@buglavecz I will look into your issue and get back to you

**Comment by ananmishr** [comment]
@buglavecz are you using the v1.0 API?

**Comment by buglavecz** [comment]
Hi @ananmishr,

I tried both: v1.0 and beta.

v1.0 request:
```json
POST /v1.0/me/onlineMeetings HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOi...
{
  "startDateTime":"2020-01-11T12:00:00.0000000-03:00",
  "endDateTime":"2020-01-11T13:00:00.0000000-03:00",
  "subject":"Application Token Meeting",
}
```
Result:
```json
{
  "error": {
    "code": "Forbidden",
    "message": "",
    "innerError": {
      "request-id": "b71810b9-27f4-4cc5-b79d-f33589e93ff6",
      "date": "2020-01-14T07:46:58"
    }
  }
}
```
In the documentation i was read this:
![image](https://user-images.githubusercontent.com/43108336/72324304-e30f6a80-36aa-11ea-81c7-8c8ce8a7703d.png)

But I don't understand, how can I generate user token. 
I use to generate token this URL: `https://login.microsoftonline.com/{{TenantID}}/oauth2/v2.0/token`
and this params: 
![image](https://user-images.githubusercontent.com/43108336/72324469-4f8a6980-36ab-11ea-9ae2-dc9c2af67d18.png)

This is generate not an User access token?! 

Result:
```json
{
    "token_type": "Bearer",
    "expires_in": 3599,
    "ext_expires_in": 3599,
    "access_token": "eyJ0eXAiOiJKV1QiL...."
}
```

What is wrong? Please help me! :slightly_smiling_face: 

---

beta endpoint request:
```json
POST /beta/communications/onlineMeetings HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1...
{
 
  "startDateTime":"2020-01-11T12:00:00.0000000-03:00",
  "endDateTime":"2020-01-11T13:00:00.0000000-03:00",
  "subject":"Application Token Meeting",
  "participants": {
    "organizer": {
      "identity": {
        "user": {
          "id": "f6e2c8d1-320b-4fff-b8fd-484382a26eb2"
        }
      }
    }
  }
}
```

Result:
```json
{
  "error": {
    "code": "Forbidden",
    "message": "Forbidden",
    "innerError": {
      "request-id": "78c00bff-c5b0-4929-848a-09da9517debd",
      "date": "2020-01-14T07:42:07"
    }
  }
}
```

In my app permissions is look like this:
![image](https://user-images.githubusercontent.com/43108336/72323935-27e6d180-36aa-11ea-8ea1-623a58a9f1ff.png)

**Comment by ananmishr** [comment]
Hi @buglavecz please add the OnlineMeetings.ReadWrite permission as well. 

The OnlineMeetings.ReadWrite.All permission is an application based permission that works, but is deprecated, for the beta API. Also, yes, you are generating a user token correctly. Hope this helps!

**Comment by buglavecz** [comment]
Hi @ananmishr,

This permission is already added to the app. This image I sent before, but I paste here again, and I'm marked red arrow the permission.

![image](https://user-images.githubusercontent.com/43108336/72412175-026ecc00-376d-11ea-8a53-ff9a19ea6af6.png)

Thank you.

**Comment by buglavecz** [comment]
... and I tested my app, that I wrote above with both API (beta and v1.0), but doesn't works. :-(

**Comment by ananmishr** [comment]
@buglavecz Would you be able to parse your auth token on this site? https://jwt.io/

In the parsed json, in the field that says "scp" do you see an OnlineMeetings.ReadWrite permission somewhere in the value?

**Comment by buglavecz** [comment]
@ananmishr the jwt.io result:

```json
...
"roles": [
    "Calls.JoinGroupCall.All",
    "OnlineMeetings.ReadWrite.All",
    "Calls.InitiateGroupCall.All",
    "Calls.JoinGroupCallAsGuest.All",
    "User.Read.All",
    "Calls.AccessMedia.All",
    "Calls.Initiate.All"
  ],
...
```

Above result doesn't contain this presmission: `OnlineMeetings.ReadWrite` , just this: `OnlineMeetings.ReadWrite.All`.

But here show it:
![image](https://user-images.githubusercontent.com/43108336/72505400-26e7a880-3840-11ea-87b1-5763eca3901d.png)

Whats is wrong?

Thank you.

**Comment by buglavecz** [comment]
I changed presmissions to these:

![image](https://user-images.githubusercontent.com/43108336/72506172-b0e44100-3841-11ea-8a20-50ea46a7cf04.png)

The jwt.io result now this:
```json
{
  "aud": "https://graph.microsoft.com",
  "iss": "https://sts.windows.net/7c2b70ab-cd56-43eb-bc05-8a475a62a229/",
  "iat": *****,
  "nbf": *****,
  "exp": *****,
  "aio": "******",
  "app_displayname": "LetsNearshore Meetings",
  "appid": "******",
  "appidacr": "1",
  "idp": "https://sts.windows.net/*****/",
  "oid": "*****",
  "roles": [
    "OnlineMeetings.ReadWrite.All",
    "User.Read.All"
  ],
  "sub": "****",
  "tid": "****",
  "uti": "b****",
  "ver": "1.0",
  "xms_tcdt": *****
}
```

I replaced ID-s to *.

API call is not working.
The request:
```
POST /v1.0/me/onlineMeetings HTTP/1.1
Host: graph.microsoft.com
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub25jZ.....
{
 
  "startDateTime":"2020-02-11T12:00:00.0000000-03:00",
  "endDateTime":"2020-02-11T13:00:00.0000000-03:00",
  "subject":"Application Token Meeting",
}
```

The result:
```json
{
  "error": {
    "code": "Forbidden",
    "message": "",
    "innerError": {
      "request-id": "a30ec621-1796-461b-b4fb-35659a410c22",
      "date": "2020-01-16T08:25:25"
    }
  }
}
```

**Forbidden** again! :slightly_frowning_face:

**Comment by buglavecz** [comment]
@ananmishr Any idea what is wrong? :slightly_smiling_face:

**Comment by buglavecz** [comment]
I see now contain this permissions:
```
"roles": [
    "OnlineMeetings.Read.All",
    "OnlineMeetings.ReadWrite.All",
    "User.Read.All"
  ],
```

...but doesn't works. :slightly_frowning_face:

**Comment by buglavecz** [comment]
@ananmishr @VinodRavichandran any idea?

Thanks.

**Comment by ananmishr** [comment]
Hi @buglavecz 

I apologize, this is not the correct way to generate a user token 
![image](https://user-images.githubusercontent.com/55606185/73032282-8ff88e80-3df3-11ea-8a87-efd7bcbbdb03.png)

The combination of client_id and client_secret is used for generating an app token. To generate a user token, you must provide a username and password.

To learn more about implicit oauth, this link may be useful https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request

I hope that helps

**Comment by buglavecz** [comment]
Hi @ananmishr,

If I understand correctly, I can't create a meeting room URL from a server side (PHP) because only the APP permission can use a sesame server PHP script.
However, does the Meeting Room API call require USER access permission?
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-app-types#daemons-and-server-side-apps

Previously I used the Skype INTERVIEW API, where I could use the API key to generate meeting rooms from a server side. But now it is end. :slightly_frowning_face:

**Comment by ananmishr** [comment]
Hi @buglavecz Yes, we don't have a Meeting Room API, just the Create Online Meeting API that generates meeting coordinates. These are only supported for client applications that create meetings on behalf of a user and require the user to be signed in

**Comment by buglavecz** [comment]
Hi @ananmishr,

Thanks your reply, but we will not try again with Microsoft Graph API. We now use the zoon.us API: https://zoom.us/ 

It is works fine.

**Comment by AswinSreenath** [comment]
Hi,
I used to delegated permission to create meeting.It shows same error.
`{code:"Forbidden",message:"Forbidden",innerError:{"request-id":"e1abb815-09d3-4b78-5063-39b0236c0968","Date":"2020-06-09T04:14:39"}}`
I have given OnlineMeetings.ReadWrite Permission.I am using the same app to create user and it works without issues.Error shows only when meeting is created

**Comment by nezamuddinansariBL** [comment]
I am getting the same error 
{
  "error": {
    "code": "Forbidden",
    "message": "Forbidden",
    "innerError": {
      "date": "2020-07-05T14:41:42",
      "request-id": "544f69c7-3e36-4130-8b8d-c7e87292a9fa"
    }
  }
}
Please suggest what I am doing wrong
Thanks
Nezam
