### ISSUE TITLE
Unable to create SharePoint subscription per documentation

### ISSUE THREAD

**Issue by trevonmckay** [microsoftgraph/microsoft-graph-docs#6664]
Using "/drive/root" for the resource as specified in this document "Or to the root folder of a SharePoint/OneDrive for Business drive: /drive/root" results in an error "Unable to find target address"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks#feedback)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JeremyKelley** [comment]
Can you share the full path to the resource you pass in to the subscription?  (Minus the hostname).
