### ISSUE TITLE
Support for application permission

### ISSUE THREAD

**Issue by danielpomas** [microsoftgraph/microsoft-graph-docs#6673]
Are there any plans to support application permissions for planner api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe759404-4440-1662-30e0-becad260e161
* Version Independent ID: c1f38f09-2181-3142-d0f2-bd76c6b58434
* Content: [List plans - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/plannergroup-list-plans.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zax123** [comment]
I would also like to know if application permissions will have access to the planner API soon.  Thank you.

**Comment by gregarican** [comment]
Same question here. I believe that Planner is going to be gradually merged into Teams, but for the time being my application cannot access Planner objects.
