### ISSUE TITLE
Length limits for properties?

### ISSUE THREAD

**Issue by adamtoth** [microsoftgraph/microsoft-graph-docs#6675]
What are the length limits for the properties that can be set on a group? displayName? description? I've gotten InvalidLength errors using the api, but the error messages do not indicate what the length limit is, and neither does this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hi @adamtoth 

I've done some research and ended up with following limitations for the Office 365 group properties:

• description: 1024 characters
• displayName: 256 characters
• mailNickname: 64 characters

I've also written a small [blog post](http://www.devjhorst.com/2020/01/length-limits-for-office-365-group-properties.html) about it. Check it out!

I hope it helps!

**Comment by yyuank** [comment]
I saw the character limits have been updated in the doc, so closing this.
