### ISSUE TITLE
get user by id always returns current user

### ISSUE THREAD

**Issue by ikuznmargarita19** [microsoftgraph/microsoft-graph-docs#6679]
get user by id always returns current signed-in user

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=javascript)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@ikuznmargarita19 Not sure I follow. Can you expand a bit?
If you do `GET /me` or `GET /users/{id}` where the id is for the signed-in user, then yes it always returns the signed in user.  If you do `GET /users/{id-but-not-signed-in-user-id} `then you'll get the user details of a different user (and only that user).

**Comment by ikuznmargarita19** [comment]
@dkershaw10 
When I do `GET /users/{id-but-not-signed-in-user-id}` then I expect to get info about the searched user, but l get the user details of a **current** signed-in user.

For example in graph explorer I run request:
`Get https://graph.microsoft.com/v1.0/users/123aaaaaa`

Response is:
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "displayName": "Test User",
    "surname": "User",
    "givenName": "Test",
    "id": "111bbbbbb",
    "userPrincipalName": "test.user@gmail.com",
   ...
}
```

**Comment by udlose** [comment]
IIRC, if the token you pass is user-specific then you will get info about the user represented by the token.  I think this is from the "get token on behalf of user" approach.  I had this problem and needed to get a token that was valid for the ClientId rather than a user-specific token.  If you have a token that is good for the Azure ClientId, then you can get info on any user within that client.  HTH

**Comment by ikuznmargarita19** [comment]
@udlose , sounds reasonable. Could you suggest me, how to get not user-specific token?

**Comment by udlose** [comment]
@ikuznmargarita19 you need to use the "Client Credentials" flow as documented here: [Microsoft identity platform and the OAuth 2.0 client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#get-a-token)

**Comment by udlose** [comment]
@ikuznmargarita19  did my suggestion solve your issue?

**Comment by ikuznmargarita19** [comment]
@udlose, yes, thank you.

**Comment by davidmu1** [comment]
Looks as if the issue was resolved. No change identified for the page. Closing the issue.
