### ISSUE TITLE
"resource": "/teams/{id}/channel/{id}/messages" in the example isn't working now

### ISSUE THREAD

**Issue by nutschan** [microsoftgraph/microsoft-graph-docs#6680]
my subscription with / teams / {ID} / channels / {ID} / messages  failed. 

{

"Error": {

"code": "ExtensionError",

"message": "**Operation: Create; Exception: [Status Code: Forbidden; Reason: ]**",

"innerError": {

"request-id": "08e5743f-f73f-4165-a8d0-f93502075f4c",

"date": "2019-12-25T02:23:58"

}

}

}

The request parameters are:
and  I call the beta API, because it is feasible in the document：**https://graph.microsoft.com/beta/subscriptions**
{

"changeType": "created,updated",

"notificationUrl": "https://ebd6eb5c.ngrok.io/ms/subscription/recieve",

"resource": "/teams/5c4e109b-bcc2-45d4-bab9-89a0695f5465/channels/19:017a7d24f8b54b229ad999a98611351a@thread.skype/messages",

"expirationDateTime":"2019-12-25T02:59:45.9356913Z",

"clientState": "123456"

}

Work account and application permission subscription are all assigned. But interestingly, I was able to successfully subscribe to email, user messages, etc. I suspect it's about scopes, but I'm not sure what I'm missing right now;

The current permission list is as follows:

Email

Group.Read.All

Group.ReadWrite.All

Mail.ReadWrite

Notifications.ReadWrite.CreatedByApp

User.Invite.All

User.Read

User.Read.All

User.ReadWrite

User.ReadWrite.All

Profile

Openid

Can you show me the permission list when you called / teams / {ID} / channels / {ID} / messages? Or do you know what my problem is?

**Comment by user370305** [comment]
Whats the authentication flow are you using to generate token? If its client credential than your application scope will be defaulted. This might be a reason. I am having the same issue with client credential authentication flow, works great if I generate token with user credential flow. If you want to test, use Graph Explorer, sign in with your tenant admin account, copy generated access token and use with your api it will work.

Let me know if you have found solution for this. It will be very helpful for me. Thanks

**Comment by nutschan** [comment]
> What was the authentication flow you are using to generate token? If its client credential than your application scope will be defaulted(Only default permission will be granted for that token). This might be a reason. I am having the same issue with client credential authentication flow, works great if I generate token with user credential flow. If you want to test, use Graph Explorer, sign in with your tenant admin account, copy generated access token and use with your api it will work.
> 
> In my case I am trying to post message using `/teams/{id}/channel/{id}/messages` with beta version apis, using client credential flow and generate token ended up to defaulted to version 1.0 permission.
> 
> Let me know if you have found solution for this. It will be very helpful for me. Thanks

Because of the application scenario needs, I use the ROPC stream. The token obtained is user permission level, so this API should have some problems when I called it at that time. Because later I used the same error parameter in postman history to request again, and I succeeded again.

**Comment by nutschan** [comment]
It is very important to subscribe to the interface I send. Only tokens containing application permissions are supported (and channelmessage. Read. All is a scope). Refer to the authority description in the official subscription document https://docs.microsoft.com/zh-cn/graph/api/subscription-post-subscriptions? View = graph rest beta & tabs = http;




If you want to request a token that contains application permissions, it is recommended to use the client credential flow.

Portal:

https://docs.microsoft.com/zh-cn/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow

**Comment by user370305** [comment]
Thank you so much for your reply. The web links really helped me to understand the access token scope level. Now this solved my issue. The only weird thing I am facing is to maintain two different tokens, one for posting message to channel using user generated token and second for subscribing messages using client credential flow.

Thanks again.
