### ISSUE TITLE
Minor typo in "The videio teleconferencing ID. Read-only."

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs#6687]
Correct spelling of video

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bddf229-c02d-7595-78c5-6dac2b1c3c76
* Version Independent ID: a1ccb913-8d51-1445-e81f-a4f100a495e3
* Content: [onlineMeeting resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/onlinemeeting.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @VinodRavichandran
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VinodRavichandran** [comment]
@ananmishr

**Comment by ananmishr** [comment]
Thanks for bringing this to our attention. The typo has now been corrected.
