### ISSUE TITLE
Where does the file content go?

### ISSUE THREAD

**Issue by rgregg** [microsoftgraph/microsoft-graph-docs#6691]
The example here shows posting a JSON blob, but has no indication for where the contents of the attachment should go. It provides name, contentType, size, and modification dates, but not content! What’s a developer to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a9996f9-9809-0479-8598-40f74ce3b6cc
* Version Independent ID: 6ccb665f-eb43-98ca-4c28-49656f62dd16
* Content: [Create attachment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlooktask-post-attachments?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/outlooktask-post-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlooktask-post-attachments.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @rgregg , I added a couple of examples in PR #6738  to show adding a file attachment and adding an item attachment to a task. If you're wondering about reference attachments, FYI I have asked the product side owner to confirm the support. 

The examples will be published live in the next day. :-)
