### ISSUE TITLE
Permissions "just for my app"

### ISSUE THREAD

**Issue by SychevIgor** [microsoftgraph/microsoft-graph-docs#6694]
As it's beta API- I would like to provide feedback.
Our ApplicationA reads role assignments for ApplicationA. Request permissions "Directory.Read.All" - is a bit too much. It will be nice to have something like "Directory.Read.Me" to retrieve information about assignments only for current application. It's not only utilize principle of "least required privileges", but also could prevent a requirement of approve from global admin.

Of course, it's just feedback. I don't know full context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3546a45-22f6-8f62-9f5d-26450c484572
* Version Independent ID: 0f6521fa-e1ed-ae22-9958-6a118c3518e6
* Content: [Get appRoleAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/approleassignment-get?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/approleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/approleassignment-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
@SychevIgor Please accept my apologies for the lack of response here. I'd like to thank you for taking the time to send us this feedback. I have a few follow-up questions, if you have the time:

1. Are you looking to get the list of users, groups and service principals which have been assigned an app role in ApplicationA? Or is the reverse--you're trying to get the app roles (i.e. application permissions, in this case) which have been granted to ApplicationA?
3. How are you using this information? Is it part of ApplicationA's authorization checks, or something else?
2. Are you looking for this as a delegated permission (i.e. the app is calling on behalf of a signed-in user), or as an app-only permission (i.e. the app is calling under it's own identity)? In other words, is "Me" in your proposed permission name a user, or an application?

**Comment by SychevIgor** [comment]
@psignoret 
1-Are you looking to get the list of users, groups and service principals which have been assigned an app role in ApplicationA
2-part of ApplicationA's authorization checks. As an Application Administrator I wanna see who have permissions on this application and in which role. 
3- As developer, I want to test my apps without involving enterprise AAD Admins.

**Comment by psignoret** [comment]
I'm closing this issue only because it's not a documentation issue. Although we don't have any specific new features to share, we've integrated this feedback into our planning and design process for the next set up improvement. Thank you for your feedback!
