### ISSUE TITLE
Create action missing from topic

### ISSUE THREAD

**Issue by chadmcrowell** [microsoftgraph/microsoft-graph-docs#6700]
The create action is missing from this page, even though it exists

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07769b8-df00-6abc-bc50-79cc07b75339
* Version Independent ID: 0cd73e6b-f547-c257-4ffc-faeb4cfd1abf
* Content: [servicePrincipal resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/serviceprincipal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/serviceprincipal.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nijasbijilyrawther** [comment]
Any update on this?

**Comment by dbollaer** [comment]
@sureshja could you please provide a simple example. I have been looking for this also.
Thank you in advance.

**Comment by davidmu1** [comment]
https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-beta&tabs=http

Closing the issue.
