### ISSUE TITLE
'keySet' field is invalid

### ISSUE THREAD

**Issue by komaflash** [microsoftgraph/microsoft-graph-docs#6707]
I get the error `"The 'keySet' field is invalid in request. Please check the request body and parameters.`  but the docs doesn't say anything about this field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a75ec91a-7c8f-e5a0-d298-1d57ea4c3bea
* Version Independent ID: be8e84de-8562-dd82-762b-2745c723ea14
* Content: [Update trustFrameworkKeySet - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/trustframeworkkeyset-update?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/trustframeworkkeyset-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/trustframeworkkeyset-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @valnav
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nickgmicrosoft** [comment]
Please see this issue.
https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/67

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
