### ISSUE TITLE
code 20258 error

### ISSUE THREAD

**Issue by lockelost** [microsoftgraph/microsoft-graph-docs#6713]
Hi,

If you upload the locally generated OneNote Notebook folder to OneDrive's 'Notebooks' folder, the API returns code 20258 error. So you can not get all the list. (but OneNote/OneDrive webpage itself seems to be working with no problem).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01e3119-5357-9a8d-4737-d412262d9906
* Version Independent ID: 7d60a631-f6f4-8906-77d6-e91e06cc8eb2
* Content: [List pages - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onenote-list-pages?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/onenote-list-pages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/onenote-list-pages.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zaiby** [comment]
I have same issue with both v1.0 and beta endpoint

https://graph.microsoft.com/v1.0/sites/.../onenote/pages

{
    "error": {
        "code": "20258",
        "message": "Synkronisering af denne sektion er ikke understøttet. Detaljerede fejloplysninger: Getting Section",
        "innerError": {
            "request-id": "053acc9f-45ed-42f5-a4d0-972f151da5d0",
            "date": "2020-01-13T13:49:23"
        }
    }
}

**Comment by zaiby** [comment]
I don't think this will be fixed,

Quoting ms support
"Yes, it's expected to break the API because the direct upload of a OneNote notebook is not yet supported. You can fix it by using the "Move Notebook" functionality on the OneNote client."

**Comment by lramosvea** [comment]
Thank you @lockelost  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-notes.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
