### ISSUE TITLE
You can not specify the 'path' of the Notebook, 

### ISSUE THREAD

**Issue by lockelost** [microsoftgraph/microsoft-graph-docs#6714]
In case the OneNote contents are synched onto OneDrive storage, the OneNote contents will usually be located under 'Notebooks' folder there.

OneDrive webpage provides the 'Copy To' button for OneNote item there, and if you click on it, it will generate a new OneNote notebook also on the OneNote website. The problem is that you can specify other Folders on OneDrive storage, no matter how many depths it is.

Because OneDrive does not provide an API option to create this kind of 'OneNote synch' item, In case if you want to restore the OneNote notebook item you have to call this API to create a new Notebook. 

But because you can not specify the 'path' to where in the OneDrive's storage, it will always create one inside the OneDrive's 'Notebooks' folder. So you can not restore properly the Notebook files that were in some other folder location on OneDrive storage.

Either OneDrive needs to consider the way it synchs with OneNote, or this API should provide another option/parameter to specify the target folder location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57e56a29-62ff-9484-52be-6b703148a274
* Version Independent ID: d897784e-c1bb-860a-eaaa-edd2548b0f8e
* Content: [Create notebook - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onenote-post-notebooks?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/onenote-post-notebooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/onenote-post-notebooks.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @lockelost  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-notes.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
