### ISSUE TITLE
Concurrency considerations?

### ISSUE THREAD

**Issue by floppydisken** [microsoftgraph/microsoft-graph-docs#6720]
I have an application that acts upon an event fetched from Graph. 
While this is happening the classic concurrency problem of "the event gets updated in the meanwhile" or in other words lost-updates might occur.
Is there any way to ensure data consistency?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1c68e-95bf-e8af-992e-cb790f8ca884
* Version Independent ID: 4072bab0-de7c-1f9f-05b9-6a7b4b6787f8
* Content: [Update event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-update.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @floppydisken , the "issues" tab for this repo are primarily for Microsoft Graph documentation issues. While your question pertains to a valid scenario, may I suggest you post your question on stackoverflow and tag it with microsoftgraph to get more appropriate exposure? 
May I also suggest you refer to this [stackoverflow help center topic](https://stackoverflow.com/help/on-topic) to consider providing more context to a specific problem, when posting on stackoverflow.
