### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by chenxizhang** [microsoftgraph/microsoft-graph-docs#6722]
I am trying to call this api through the Microsoft.Graph.beta SDK and the Graph Explorer, it just return an unknown error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Ngoroth** [comment]
I have same problem.
Trying with application token and Group.Read.All, User.Read.All scopes
Examples of answers:
x-ms-ags-diagnostic : {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_25"}}
`{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "b0066cad-4f48-44fe-a022-20b48c22c343",
      "date": "2020-04-06T08:53:10"
    }
  }
}`

`Code: UnknownError
Inner error:
	AdditionalData:
	request-id: 5d02570b-7388-498a-905f-c300bb7b8b7b
	date: 2020-04-06T08:52:49`

**Comment by kumbhaj** [comment]
I am getting the same error. I want to read the channel's messages with application permissions without any user signed-in.

**Comment by jpalo** [comment]
Same error here, using Application permission type with Group.Read.All permissions.

**Comment by Ngoroth** [comment]
> Same error here, using Application permission type with Group.Read.All permissions. Can get hold of the channel just fine using `https://graph.microsoft.com/beta/teams/TEAMID/channels` but subsequently fetching messages of that channel fails `https://graph.microsoft.com/beta/teams/TEAMID/channels/CHANNELID/messages`.
> 
> ```
> {
>   "error": {
>     "code": "UnknownError",
>     "message": "",
>     "innerError": {
>       "request-id": "d3c5a0a8-011f-40d8-8b69-1b9a26abe541",
>       "date": "2020-05-05T13:23:59"
>     }
>   }
> }
> ```

Did you get permission to protected graph api?
https://docs.microsoft.com/en-us/graph/teams-protected-apis

**Comment by jpalo** [comment]
No, that must be it. Thank you @Ngoroth!

**Comment by sunilm-css** [comment]
I entered and submitted the form. Still I don't see the messages coming thru. Application Access. I still run in to errors

request:https://graph.microsoft.com/beta/teams/0cefd2e5....../channels/19:417......f4d0@thread.skype/messages?$top=99,

response:{'error': {'code': 'UnknownError', 'message': '', 'innerError': {'request-id': '67d25bc2-......87780e', 'date': '2020-05-07T20:13:03'}}}

**Comment by Ngoroth** [comment]
> I entered and submitted the form. Still I don't see the messages coming thru. Application Access. I still run in to errors
> 
> request:https://graph.microsoft.com/beta/teams/0cefd2e5....../channels/19:417......f4d0@thread.skype/messages?$top=99,
> 
> response:{'error': {'code': 'UnknownError', 'message': '', 'innerError': {'request-id': '67d25bc2-......87780e', 'date': '2020-05-07T20:13:03'}}}

You should wait for approval your permission request. In my case it takes about 4 weeks.

**Comment by kumbhaj** [comment]
Has anyone got any response? Does it work after approval? @sunilm-css @Ngoroth

**Comment by jpalo** [comment]
Yes, it does work. They didn't send any email telling when it was set, though. I waited few weeks, then sent mail to the address mentioned top of the dorm, and they promptly responded permission was approved and granted.

**Comment by anandab-gt** [comment]
closing this issue as this is related to using protected API. Please see https://docs.microsoft.com/en-us/graph/teams-protected-apis for using protected APIs
