### ISSUE TITLE
When will MembershipType added to 1.0?

### ISSUE THREAD

**Issue by ivanfioravanti** [microsoftgraph/microsoft-graph-docs#6732]
MembershipType property of a channel is returned in /beta version of Graph, when will you add this to 1.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21afd0d1-6f5a-c2ec-8f87-9e9dc70f0737
* Version Independent ID: 4a5cc49a-ee65-02a5-583b-acfb0993a25f
* Content: [Get channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-gt** [comment]
@ivanfioravanti  - MembershipType property is not supported in v1 endpoint
