### ISSUE TITLE
Drive recent files top filter return one item less than specified

### ISSUE THREAD

**Issue by ferronsw** [microsoftgraph/microsoft-graph-docs#6733]
Today I started to notice that I saw one file less within my recent files viewer (within my own app).
I'm using this request URL:

https://graph.microsoft.com/v1.0/me/drive/recent?$top=6&$select=name,remoteItem

It returns just 5 items and not 6.
Graph explorer does the same.

Duplicate of https://github.com/microsoftgraph/microsoft-graph-docs/issues/6522 #NoResponse

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7ca25a-037d-5202-debc-92c06a2c8480
* Version Independent ID: 8ebb4dbc-76a1-00fd-e740-87eda29a40f0
* Content: [Known issues with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/known-issues)
* Content Source: [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/known-issues.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JeremyKelley** [comment]
If you don't provide the top filter how many items do you get?  I don't see this same behavior testing in Graph Explorer with the default data set.

**Comment by ferronsw** [comment]
Yesterday I noticed it is showing the correct number of items again suddenly. 
So I'm closing this issue for now.
