### ISSUE TITLE
Broken hyperlink when discussing Error 20166

### ISSUE THREAD

**Issue by ssaamm** [microsoftgraph/microsoft-graph-docs#6737]
There's a link to: https://blogs.msdn.com/b/onenotedev/archive/2016/01/13/onenote-api-throttling-and-best-practices.aspx

which appears to be broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5ce7053-4984-560a-4c4b-cd3b72117280
* Version Independent ID: 97806469-23b3-64d2-1b5f-21548f23c4bb
* Content: [Error codes for OneNote APIs in Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/onenote-error-codes)
* Content Source: [concepts/onenote-error-codes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-error-codes.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mumbi-o** [comment]
Closing as resolved
