### ISSUE TITLE
Delta for user's presence?

### ISSUE THREAD

**Issue by smedvedev** [microsoftgraph/microsoft-graph-docs#6740]
Is it planned to support tracking 'presence' as a part of user?
GET https://graph.microsoft.com/beta/users/delta?$select=presence.
Currently users/delta doesn't track changes of presence, and response even doesn't contain presence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05eda6b9-c06f-2a02-707c-34b49f1d6f6e
* Version Independent ID: cf533ea9-3054-ef1d-b8eb-aa5c4589fbdf
* Content: [Get incremental changes for users - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-users)
* Content Source: [concepts/delta-query-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-users.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @smedvedev 
Github issues are reserved to discuss information missing in the documentation.
For information about upcoming features and/or request additional features please let us know on uservoice https://microsoftgraph.uservoice.com/ :)
