### ISSUE TITLE
Cannot list all my calendar with /me/calendars

### ISSUE THREAD

**Issue by ling595659851** [microsoftgraph/microsoft-graph-docs#6741]
I try the api /me/calendars, but I found that the calendar which is delegated or impersonation can not be listed. If I want to get the  delegated or impersonation calendar, which api should I use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4c513f-3430-6cad-ed4e-27f6a7a94f32
* Version Independent ID: 26070fca-f408-ea1f-0364-19ca324ed9ae
* Content: [List calendars - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-calendars?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-calendars.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Getting delegated shared calendars as listed here:
https://docs.microsoft.com/en-us/graph/outlook-get-shared-events-calendars
