### ISSUE TITLE
Priority property field

### ISSUE THREAD

**Issue by ioku-jts** [microsoftgraph/microsoft-graph-docs#6758]
Is there a way to grab the Priority value from the task? 
I'm talking about the Dropdown next to Progress when looking at a Task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e496bc30-ad9f-93ca-e99d-83306a415dbf
* Version Independent ID: 407a66f9-652c-7c27-4bba-967fd856cc83
* Content: [plannerTask resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/plannertask.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by scoetser** [comment]
Any update on this feedback? In version 1.0 of the API you did not include the priority for a task. This priority value is found in the beta API for the exact same call.

Thanks

**Comment by ioku-jts** [comment]
> Any update on this feedback? In version 1.0 of the API you did not include the priority for a task. This priority value is found in the beta API for the exact same call.
> 
> Thanks

confirmed is in https://graph.microsoft.com/beta/planner/plans/{plan-id}/tasks. Thanks!
