### ISSUE TITLE
API Documentation: Missing field description for attribute 'creationType' on Users documentation page

### ISSUE THREAD

**Issue by tfrancois** [microsoftgraph/microsoft-graph-docs#6759]
Missing helpful information and description (and acceptable values) and whether or not property is read-only from the API documentation on the user object.  (Not sure if it is also missing on Group object page).  Can someone please update the docs to reflect this attribute please and whether or not it is auto-populated or can be provided when provisioning new objects.  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@tfrancois Not sure what else you are looking for.  The description of the property says what values are possible.  The property description also says it is read-only.
This property is ONLY on the `user` resource type.

**Comment by dkershaw10** [comment]
@tfrancois Please re-open this issue if this isn't satisfactory.
