### ISSUE TITLE
Does the Meetings/user each month limit apply to Teams Apps?

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs#6761]
In a remote-advisor situation, will a Teams App be able to create more than 2000 meetings each month via the communications API?  The intention is for the app to be able to set up meetings and invite participants as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ef5e873-6311-937f-7128-fa43e26623a2
* Version Independent ID: 22240852-e5ef-8f27-f60a-4f5f1786bee1
* Content: [Cloud communication API limits in Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/cloud-communications-limits)
* Content Source: [concepts/cloud-communications-limits.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/cloud-communications-limits.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Gousia-MSFT** [comment]
@GauravES The 2000 meetings is a limit of per user per month - so the limit is on a per user basis

**Comment by Gousia-MSFT** [comment]
Please re-open if you have further queries here.
