### ISSUE TITLE
If a Teams App is participating in a group chat with one or more users, is getting a list of messages protected?

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs#6763]
If an App is itself participating in a group chat  with one or more users, should getting a list of messages in that chat still be protected?  (Understand that getting messages for a chat in which the app is not a participant should be protected)

(And if it is not protected, what permissions should the app have?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675658fe-2bf6-fa95-ed24-22f744aefa65
* Version Independent ID: 60b1b2e7-6d8f-98c6-5b26-f8cb9e8dcdb2
* Content: [List chat messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
Whether the app is a member of the chat makes no difference today in the permissions it needs.
