### ISSUE TITLE
is there a way to check an access tokens scope via api?

### ISSUE THREAD

**Issue by liangchr** [microsoftgraph/microsoft-graph-docs#6764]
is there a way to check an access tokens scope via api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user#feedback)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @liangchr for raising your query. There's no API to check the scopes. However, in Graph Explorer, copy the access token from the **Access token** tab, click the **{ }** icon to decode it on jwt.ms. The assigned scopes are defined in the **scope** property of the decoded token.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.

**Comment by FaithOmbongi** [comment]
My apologies @liangchr , I misinformed you. 
Yes, you can check scopes granted to your API using the **appRoleAssignments** and the **oauth2PermissionGrants** APIs. For more information, kindly refer to this response: https://github.com/microsoftgraph/microsoft-graph-docs/issues/6631#issuecomment-827995494
