### ISSUE TITLE
Duplicate Office 365 shared calendar folder and event

### ISSUE THREAD

**Issue by judithting** [microsoftgraph/microsoft-graph-docs#6766]
I'm develop a backup program which can backup all of calendars and events from the Office 365 account you assigned.

When I test the Graph API and EWS API, I found something interesting after sharing a calendar to another user.

When one user (A-USER) shares a calendar C to another user (B-USER), it seems that the system will automatically duplicate the shared calendar folder C to B, because I got two different event id from A and B via Graph API ([List Events](https://docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&tabs=http)) even though they represent the same event.

Besides, I also use EWS API ([GetItem](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getitem-operation-calendar-item)) to check the parent folder of these two events. I found that they belong to different calendar folder; One (Folder _fa_) is under A's mailbox, the other (Folder _fb_) is under B's mailbox.

I want to backup all of events which B can see in Office 365 Portal. 
For the shared calendar C, can I backup the events from Folder _fb_ to achieve my goal? Does _fb_ include all of events in C?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c86813-3128-8d76-1853-fde56fb17349
* Version Independent ID: da447d8b-6f50-027e-6d6f-46636eb7294b
* Content: [List events - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-events.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
@JuForan 
Please help with this query on shared calendars.

**Comment by Harini84** [comment]
For converting ID from EWS to REST, please use the following:
https://docs.microsoft.com/en-us/graph/api/user-translateexchangeids?view=graph-rest-1.0&tabs=http
