### ISSUE TITLE
Get Task folders list in order that they are shown in the MS To Do app

### ISSUE THREAD

**Issue by geoff604** [microsoftgraph/microsoft-graph-docs#6777]
Hi there, I would like to retrieve the list of task folders in the exact order that they are shown in the MS Todo App. The MS To Do app allows the user to drag the lists in a custom order. But the property such as "orderHint" which represents this ordering is currently not exposed on the Outlook Task Folder List Get API. Ideally, I should be able to request something like this:

https://graph.microsoft.com/beta/me/outlook/taskFolders?orderBy=orderHint

but this currently returns:

{
    "error": {
        "code": "BadRequest",
        "message": "Could not find a property named 'orderHint' on type 'microsoft.graph.outlookTaskFolder'.",
        "innerError": {
            "request-id": "91f70aab-3cbc-4ddf-96d6-499363b207c4",
            "date": "2020-01-11T07:16:30"
        }
    }
}
thanks in advance for considering my request!

Best regards,
Geoff Peters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c7e244-509d-c4fa-e1c8-ff4dabeebf7b
* Version Independent ID: bd63ae54-0f85-a512-2435-8f8f2ed0917d
* Content: [List taskFolders - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlookuser-list-taskfolders?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/outlookuser-list-taskfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlookuser-list-taskfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mashriv** [comment]
@geoff604 thanks for raising this issue. This is a known limitation in current beta graph api and currently there is no way to achieve this.
