### ISSUE TITLE
Parameters with issues

### ISSUE THREAD

**Issue by GeneCupstid** [microsoftgraph/microsoft-graph-docs#6778]
Section **"Attributes supported by $filter parameter"** indicates that attribute `IsRisky` is supported with operator `eq`.

There is no property for `isRisky` in the SignIn object I can see - the closest I can find is a property called `RiskState`.

Various forms of the following return `invalid filter clause`:

```
https://graph.microsoft.com/v1.0/auditLogs/signIns?&$filter=IsRisky

https://graph.microsoft.com/v1.0/auditLogs/signIns?&$filter=IsRisky eq true

https://graph.microsoft.com/v1.0/auditLogs/signIns?&$filter=IsRisky eq 'AtRisk'

https://graph.microsoft.com/v1.0/auditLogs/signIns?&$filter=IsRisky eq 'true'
```

This is how I achieved what I believe to be the intention of `isRisky`:

```
https://graph.microsoft.com/v1.0/auditLogs/signIns?&$filter=RiskState eq 'AtRisk'
```

I'm concerned I will find more of these as I add support for the other attributes to my `Get-SignIns` cmdlet... I will append to this issue if I find any additional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/signin-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dhanyahk
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
IsRisky is no longer listed in the page. Closing the issue.
