### ISSUE TITLE
Incorrect field definitions, different between HTTP responses and Microsoft.Graph.Beta package responses

### ISSUE THREAD

**Issue by jlowery99** [microsoftgraph/microsoft-graph-docs#6779]
The members shown as odata enum types (riskType, riskState, riskDetail, detectionTimingType, activity, tokenIssuerType) are returned as enumeration value strings in HTTP responses. They are returned as enumeration value integers in C# package responses. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2aec20a-84b8-f5b5-b30a-07b8bece2eb3
* Version Independent ID: b07140db-8b54-e375-bbb8-1506aa0e616f
* Content: [riskDetection resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/riskdetection.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jlowery99** [comment]
Follow up: not so much "incorrect" as "misleading". Documentation should indicate the differences.

**Comment by jlowery99** [comment]
Additional Follow up: json riskDetection events downloaded from the Azure riskDetection portal contain integer enum value integers for these fields. The values in riskState and riskDetail are inconsistent with those defined in the Microsoft.Graph.RiskState and RiskDetail. Adds to the confusion.

**Comment by cloudhandler** [comment]
Checking with engineering

**Comment by cloudhandler** [comment]
Hey @jlowery99 - we're working on changing the UI behavior so that it's consistent with the strings returned by the API

**Comment by davidmu1** [comment]
No change identified for the documentation page. Closing the issue.
