### ISSUE TITLE
Broken sample Java MSGraph SDK: Conversation Thread -> Create Thread

### ISSUE THREAD

**Issue by micya** [microsoftgraph/microsoft-graph-docs#6780]
Java sample, compiler error on the following line:

    conversationThread.posts = postsList;

Error: incompatible types: LinkedList&lt;Post&gt; cannot be converted to PostCollectionPage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50c3be2a-fbee-4508-83f9-25659207be71
* Version Independent ID: c3f9580e-bdb6-7a40-542c-4dcf0999159e
* Content: [Create conversation thread - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-threads?view=graph-rest-1.0&tabs=java#feedback)
* Content Source: [api-reference/v1.0/api/group-post-threads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-threads.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@jthake-msft - not sure who owns this, but it's not me :)

**Comment by davespat** [comment]
Hi @jthake-msft - any news on this?  Thanks

**Comment by menfra** [comment]
System.InvalidCastException: 'Unable to cast object of type 'System.Collections.Generic.List`1[Microsoft.Graph.Post]' to type 'Microsoft.Graph.IConversationThreadPostsCollectionPage'.'

I got a similar error for the C# version on the graph beta API. Any solution yet?

**Comment by baywet** [comment]
Hi everyone,
Thanks for reaching out and thanks for the patience.
We addressed a bug causing this for the java samples https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/363
The updated samples should rollout soon.
For the dotnet sample, I'll let @andrueastman comment to the situation.

**Comment by andrueastman** [comment]
This is resolved for dotnet as well via https://github.com/microsoftgraph/microsoft-graph-docs/commit/4a13b5bb2b526a3e58cc034dd94adf7cca7acc49
