### ISSUE TITLE
Is there any API to know whether a specific user is a guest or not, or some way can try?

### ISSUE THREAD

**Issue by Jemmy512** [microsoftgraph/microsoft-graph-docs#6781]
We are developing a Teams App that needs to know if a particular user is a visitor and restrict its use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90003fe3-af6f-0ad3-7306-ab77fd9043e9
* Version Independent ID: 07ac7d56-934a-462c-0f6e-84d63c2b0398
* Content: [teamGuestSettings resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teamguestsettings?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/teamguestsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teamguestsettings.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JemmyWong** [comment]
Hi @wdkbot Is there any update?

**Comment by anandab-gt** [comment]
you can apply filter on 'userType'  property, refer below doc for more details
https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0

**Comment by Jemmy512** [comment]
Thank you @anandab-gt.
