### ISSUE TITLE
GetByIds now supports $select

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#6783]
Need to update this topic (and in beta) to remove the note, and have an example using $select

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652f070a-a126-9add-13db-e35250b8b86c
* Version Independent ID: d256be5b-8466-385f-32a4-2d9fd9a89886
* Content: [Get directory objects from a list of ids - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryobject-getbyids?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-getbyids.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryobject-getbyids.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by keylimesoda** [comment]
With merged change this issue is closed.
