### ISSUE TITLE
Delta Query returns duplicate entries

### ISSUE THREAD

**Issue by boachim** [microsoftgraph/microsoft-graph-docs#6785]
We should include in the description of this article the information that a delta query can return duplicate entries. So, this is, for now, an expected behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview#feedback)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @boachim 
Thanks for the feedback on the documentation.
After investigating with the team it appears our documentation was missing this information.
I just authored a pull request to fix it #6957
This issue will be closed automatically when the pull request is merged
