### ISSUE TITLE
Do we have any Delta Query limitations?

### ISSUE THREAD

**Issue by boachim** [microsoftgraph/microsoft-graph-docs#6789]
Do we have any know limitations for retrieving data through this endpoint?
Like, how many days back will this search for data?
How many records is the maximum it will return, if there is any limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
closing as the question is very similar to #4317 we're working on getting this documented and will get the status update over there.
