### ISSUE TITLE
Platform Specific Properties / SPA and Service/Daemon App

### ISSUE THREAD

**Issue by alex-mason-by** [microsoftgraph/microsoft-graph-docs#6790]
1) It seems to me that Single Page App should not require or advise a client secret at all since it is a public client and using Implicit Flow.

2) Similarly, Service/Daemon App should not require or advise a redirect URI since I assume this is using client credentials grant and operates without a browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78ef7d61-0334-9c13-14ca-e17f328110c6
* Version Independent ID: b59a85bb-6ac3-be82-569a-01b6295e1343
* Content: [Register your app with the Azure AD v2.0 endpoint - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-register-app-v2#feedback)
* Content Source: [concepts/auth-register-app-v2.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-register-app-v2.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
Just to close the loop here on this old issue, in case someone comes across this:

* A single-page app (SPA) does not require a credential.
* A daemon/service does not require a redirect URL.

However, a single app might be implementing both scenarios, so it is certainly possible (and not incorrect) for such an app registration to have a redirect URL and a client secret or key.
