### ISSUE TITLE
please add documentation on IsFavoriteByDefault

### ISSUE THREAD

**Issue by Josverl** [microsoftgraph/microsoft-graph-docs#6792]
According to the [changelog] (https://docs.microsoft.com/en-us/graph/changelog)  
&gt; Added the isFavoriteByDefault, email, and webUrl properties to channel.

isFavoriteByDefault does appear to work in Graph 1.0 , but is not documented. ( detailed testing shows it fails to work) 

`POST https://graph.microsoft.com/v1.0/teams/{teams-id}/channels`

``` json
{
  "displayName": "Pinned",
  "description": "This channel is Pinned",
  "isFavoriteByDefault": true
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f86208-723e-a0c9-2cce-3e681dfa7b9c
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/channel.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by STJ-Broeders** [comment]
isFavoriteByDefault is not working for me. The channel stays hidden.

**Comment by Josverl** [comment]
Hi @STJ-Broeders Are you creating a channel or trying to update it? Can you share full details on the call and return please?

**Comment by STJ-Broeders** [comment]
I'm creating a channel like this:

      Channel channel = new Channel
      {
        DisplayName = "joske1",
        Description = "Klasmap",
        IsFavoriteByDefault = true
      };
      graphClient.Teams[team.Id].Channels.Request().AddAsync(channel);

Channel is created but is hidden by default.

**Comment by joostvdlinden** [comment]
I have learned that the IsFavoriteByDefault property is currently only available when calling the Beta endpoint.
Review examples here: https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta#examples

**Comment by STJ-Broeders** [comment]
I'm using the Beta endpoint, and isn't working for me.

**Comment by ashoksubedi1** [comment]
same for me. It is not working even when using Beta endpoint

**Comment by guillaumemeyer** [comment]
Still no news about that... :-( See #4241

**Comment by anandab-msft** [comment]
This is fixed, setting IsFavoriteByDefault to true will make channels visible to everyone.

**Comment by joostvdlinden** [comment]
> This is fixed, setting IsFavoriteByDefault to true will make channels visible to everyone.

Hi @anandab-msft that is wonderful. Thanks for the update.
Could this documentation be updated please? There is no example on how to set this property in a request.
https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta

**Comment by Josverl** [comment]
@joostvdlinden 

The _isFavorityByDefault_ property is now documented with the other properties: 
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/channel.md#properties
