### ISSUE TITLE
List of possible capabilityStatus and skuPartNumber values

### ISSUE THREAD

**Issue by nozhT** [microsoftgraph/microsoft-graph-docs#6798]
The descriptions of the two properties capabilityStatus and skuPartNumber do not contain a list of (or a link to) its possible values, which makes it difficult to utilize APIs that return this resource type.

For example, if I wanted to display the results of this API to an user, due to the lack of documents the only option is to display the raw values of the response (ex: "Enabled"). I can't even display the value as an icon since I'd only know 1 or 2 possible values and any other unexpected value would break my app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368af49c-31b1-ebb9-68df-5cf4a041d50b
* Version Independent ID: 0ee918a5-296e-99e5-2902-cbb8e73a9dbd
* Content: [subscribedSku resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscribedsku?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/subscribedsku.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/subscribedsku.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Added possible values for capabilityStatus. The skuPartNumber can vary, added a link to the List subscribedSkus method.
