### ISSUE TITLE
sharepointIds missing

### ISSUE THREAD

**Issue by aporevop** [microsoftgraph/microsoft-graph-docs#6805]
The sharepointIds property is not returned for a drive resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd926e47-392d-8e60-a72c-bd3591417113
* Version Independent ID: 3094b7bd-9e38-20ea-71db-a4d9ea64550d
* Content: [Drive - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/drive?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/drive.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/drive.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by JeremyKelley** [comment]
The sharepointids facet isn't returned by default and must be selected using the $select query parameter.  It looks like we didn't document that it's not a default property and we'll update the documentation accordingly.

**Comment by ZaMaZaN4iK** [comment]
Is it possible to enumerate drives with sharepointIds with one request? I don't want make two calls: one for enumerating drives and another one for enumerating corresponding sharepointIds.

**Comment by Dethras** [comment]
Is there an update on this? I have the same case, and as @ZaMaZaN4iK said, I would also rather do this in a single call. (Especially when the more calls I make the easier I get throttled)

**Comment by ZaMaZaN4iK** [comment]
@Dethras I can help you here :)

You shall explicitly select `sharepointIds` field with `$select` query. So just perform usual API call like `/drives?$select=sharepointIds`

**Comment by Dethras** [comment]
> @Dethras I can help you here :)
> 
> You shall explicitly select `sharepointIds` field with `$select` query. So just perform usual API call like `/drives?$select=sharepointIds`

My apologies I didn't explain my case. What I am doing is creating an item (Be it a file or a folder) on a successful creation the newly created item is returned. I am trying to find a way to retrieve the sharepointids with that response.

**Comment by ZaMaZaN4iK** [comment]
Hm... I didn't have such case, sorry :(

**Comment by anasahmed-10p** [comment]
Any updates?

**Comment by isvargasmsft** [comment]
Hello @aporevop,

Thank you for reporting this issue in our documentation. My sincere apologies for the delays.

Creating a PR to update the documentation as requested by @JeremyKelley. 

To request a change in the feature/functionality, please use: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph

Kind regards,

Isaac Vargas
