### ISSUE TITLE
Order of permissions is not in order of least to most priviledged

### ISSUE THREAD

**Issue by mbrancato** [microsoftgraph/microsoft-graph-docs#6808]
The permissions required on this page says that values listed in that column are `(from least to most privileged)`.

The values for the Application permission type seem to be in an incorrect order:

```
Application.ReadWrite.All, Directory.Read.All
```

See reference: https://docs.microsoft.com/en-us/graph/permissions-reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d896b7-98ea-eab0-b1a1-b01266c61c68
* Version Independent ID: bccef64c-675b-364e-30f6-5c1310fef8bd
* Content: [List servicePrincipals - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-list.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Out of interest, do you see more of these? Or just this one imparticular?

**Comment by mbrancato** [comment]
Sorry, I do not have an extensive list. It was just something I ran across. It might be good to review these across the board.

**Comment by davidmu1** [comment]
Although it is a read permission, Directory permissions tend to be considered more privileged. The format of the permission section will be changing soon. No change identified for this page at this time. Closing the issue.
