### ISSUE TITLE
Which queries not support paging?

### ISSUE THREAD

**Issue by ikuznmargarita19** [microsoftgraph/microsoft-graph-docs#6812]
It is unclear, which queries supports paging:
&gt;Not all resources or relationships support paging. For example, queries against directoryRoles do not support paging. This includes reading role objects themselves as well as role members.
Specifically, is paging supported for sharedWithMe query?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e1ac6d-b2ee-c495-3194-f2895e26945e
* Version Independent ID: 73f817df-a829-e265-c932-7ae8b3f3e918
* Content: [Paging Microsoft Graph data in your app  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/paging?view=graph-rest-1.0)
* Content Source: [concepts/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @piotrci
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing this issue as the doc has been updated.
