### ISSUE TITLE
How can we be notified when resources are no longer in beta?

### ISSUE THREAD

**Issue by kehrubes-microsoft** [microsoftgraph/microsoft-graph-docs#6814]
I am particularly interested in knowing when the chatMessage (https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta) and presence (https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta#properties) resource types will no longer be in beta.

How can I "subscribe" to know when a feature (or a set of new features) is available to use in production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5463d788-8e29-ca0a-5490-93506ff1ec80
* Version Independent ID: 1e7ca228-0b9f-beb1-d61f-7f1fdff50008
* Content: [Use the Microsoft Graph API to work with Microsoft Teams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teams-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by panks816** [comment]
When we can get these chat Teamwork API's on production ?

**Comment by nkramer** [comment]
You can watch the [Graph blog ](https://developer.microsoft.com/en-us/graph/blogs/)for major announcements, or the change log for minor ones.
