### ISSUE TITLE
Re-ordering tasks by hand in Planner does not change order hints

### ISSUE THREAD

**Issue by philCryoport** [microsoftgraph/microsoft-graph-docs#6816]
Hi there,

Manually re-arranging Tasks within a Bucket in Planner does not change those Tasks' Order Hints.  See my post here in MS Power Automate community forums describing this problem: https://powerusers.microsoft.com/t5/Building-Flows/Planner-Tasks-OrderHint-value-not-respecting-order-within-Bucket/m-p/445202

Would you please take a look?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6653f38-0b88-9eca-15db-c44f52c1a7db
* Version Independent ID: 369b0769-b84f-3ebd-cb6b-3370e3f22cb3
* Content: [Using order hints in Planner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/planner-order-hint-format?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/planner-order-hint-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/planner-order-hint-format.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TarkanSevilmis** [comment]
There are a number of order hints in Planner, mapping different views, which allows tasks to be ordered differently in each view. The UI, by default shows the bucket task board, so the order hint for tasks in that view is accessed via plannerBucketTaskBoardTaskFormat object (/planner/tasks/{id}/bucketTaskBoardFormat).
