### ISSUE TITLE
Does not have the permissions section to show what permissions are required

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#6817]
As per confusion in the stackoverflow question , would be worth clearer that Mail.ReadWrite is required for this operation.
https://stackoverflow.com/questions/59726497/uploading-a-large-attachment-using-microsoft-graph

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e6b4ed-4a94-6789-95e3-407780e8fd7e
* Version Independent ID: ff8aca6f-1a1f-1bef-c1dd-bfdbbaf9f901
* Content: [Attach large files to Outlook messages - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http)
* Content Source: [concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-large-attachments.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
PR #6831 added explicitly the permission for create upload session in the concept topic [Attach large files to Outlook messages as attachments](https://docs.microsoft.com/en-us/graph/outlook-large-attachments).
