### ISSUE TITLE
No file-size parameter for PUT and truncated uploads

### ISSUE THREAD

**Issue by earonesty** [microsoftgraph/microsoft-graph-docs#6819]
On this page (driveitem-put-content) there is no mention of a file-size parameter:

The only content-type is "text/plain", no mention of encodings, etc.

Content-length is not mentioned.

In practice, when using PUT as documented, the graph api servers can occasionally abort connections, resulting in a partial file upload (data corruption).  This is easily reproducible by merely sending some bytes, and then waiting until the connection times out.

In general, the large file upload api should be preferred for reliable data transfer, because it has a byte ranges.

(If there really is no way to prevent partial uploads, I would go so far as to deprecate the PUT api.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by earonesty** [comment]
I ran some tests.   

1. You can get a truncated upload even if the content-length is specified, as long as the request connection is cut (simulating this was tough, but doable).
2. Content-type doesn't matter, i can stick binary data in there even if it's text/plain and it uploads fine.

**Comment by JeremyKelley** [comment]
Generally we document using the PUT method for content < 4MB if it's guaranteed to always be less than that size, and otherwise prefer the CreateUploadSession method of upload.  Is your request to update documentation or just to suggest that we consider removing the PUT method?

Thanks!
