### ISSUE TITLE
Please document the general / abstract concept of how the relationships work

### ISSUE THREAD

**Issue by bionicles** [microsoftgraph/microsoft-graph-docs#6820]
This seems useful but I can't find a deep dive on how the relationships are implemented

Would it be possible to expand on that?

Then users could more easily learn about how they might make a graph api for their projects, and then we could integrate our projects more easily with this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d489b596-8db6-6b4e-7271-77a6fb735c37
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph REST API v1.0 reference - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/overview.md)
* Product: ****
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@bionicles  could you explain what you mean by "how the relationships are implemented"?

This is not a GraphQL API, it is a OData based API. But it is "graphy" in nature.

We have a set of products and services that are hosted on a unified end point. There are some resources that relate to each other.

For instance, a file in OneDrive has a last modified field that is user resource object. So with the API you can use $expand to not only return the driveItem resource object populated for that file, but also deep fill the last modified user information to get the first name and last name of the user etc.

There are many of these types of relationships but user is definitely the most common. 

The API also allows you to understand parent / child relationships . So a file can live within a File Tab of a Channel within a Team which is managed at the highest level by a Group so accessing this file you would use `GET /groups/{group-id}/drive/items/{item-id}`.

Is that the kind of thing you are looking for?

**Comment by bionicles** [comment]
I was just curious how you enable arbitrary traversals with a RESTful syntax, but I guess it’s more of a tree of options than a general traversal? 

Note: it’s pretty well established at this point graph QL isn’t a real “graph query language” and the naming is a misnomer / marketing move

If a user wants to traverse the graph in some way, does that specific path need to be defined in advance by Microsoft, or can users invent new paths you haven’t built in advance, like 

/groups/{group-id}/drive/items/{item-id}/author/cousin/dog/breed ?
