### ISSUE TITLE
Photos loaded via the API are not replicating to sharepoint online

### ISSUE THREAD

**Issue by xMarcus** [microsoftgraph/microsoft-graph-docs#6828]
thumbnails never get sent to tenant-my_sharepoint_com/user photos/profile pictures

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by xMarcus** [comment]
meant to post the the update photo page.

**Comment by jthake-msft** [comment]
@xMarcus  if this is a service issue it needs to be submitted as a support request.
