### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by he852100** [microsoftgraph/microsoft-graph-docs#6834]
The following methods are not valid
```
GET /drives/{drive-id}/items/{item-id}/children
GET /groups/{group-id}/drive/items/{item-id}/children
GET /me/drive/items/{item-id}/children
GET /sites/{site-id}/drive/items/{item-id}/children
GET /users/{user-id}/drive/items/{item-id}/children
```
After constant attempts, I only found this way

```
drives/{drive-id}/root/children
```
What did I miss?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18dfd099-0d73-55e4-56ec-d9129b83aa07
* Version Independent ID: 5705a946-2c25-0d04-a297-01ccb21d7284
* Content: [List the contents of a folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-list-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-list-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by seseals** [comment]
Wow.  Thank you very much.  I couldn't figure out how to actually list the items that were in drive, because I didn't have the item-id nor did I know how I was supposed to get it.

drives/{drive-id}/root/children gave me a list of the items, then I could get the item-id, then I could get the children of it using drives/{drive-id}/items/{item-id}/children

**Comment by he852100** [comment]
Need to obtain application delegation permissions(Administrator authorization)

Functions with different permissions will become available

you also need:

ClientId

ClientId password

[Next get an authorization token](https://docs.microsoft.com/en-us/graph/auth-v2-service?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)

```
$ci="you ClientId"
$cs="Client password"
$ur=@'
https://login.microsoftonline.com/{tenant }/oauth2/v2.0/token
'@

$headers=@{
Host='login.microsoftonline.com'
'Content-Type'='application/x-www-form-urlencoded'
}

$body=@"
client_id=$ci
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
&client_secret=$cs
&grant_type=client_credentials
"@ -replace "[`r`n]+"
$at=irm $ur -headers $headers -method post -body $body
```
Next check the user list([You need to set permissions](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http))
```
$headers=@{
'Content-Type'= "application/json"
Authorization="BEARER "+$at.access_token
}

irm -headers $headers https://graph.microsoft.com/v1.0/users
```

```
https://graph.microsoft.com/v1.0/users/{user id}/drive/root/children
```
