### ISSUE TITLE
List Policies API return 400 error

### ISSUE THREAD

**Issue by watahani** [microsoftgraph/microsoft-graph-docs#6840]
Following request return 400 error.

```http
GET https://graph.microsoft.com/beta/policies
```

or

```http
GET https://graph.microsoft.com/beta/contoso.onmicrosoft.com/policies
```

```json
{
  "error": {
    "code": "Request_InvalidRequestUrl",
    "message": "Request url was invalid. The request should be like /tenantdomainname/Entity or /$metadata. Tenant domain name can be any of the verified, unverified domain names or context id.",
    "innerError": {
      "request-id": "02d80e75-7999-4a4d-b864-d61e7d34a1a3",
      "date": "2020-01-17T09:09:08"
    }
  }
}
```
It seems that something wrong with migration from AAD graph to MS graph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14d632e7-1811-aaaf-89ca-0184b334997b
* Version Independent ID: bd3f530e-5746-94c3-6a6f-ededd46b5773
* Content: [List Policies - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/policy-list?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/policy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/policy-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by despingu** [comment]
I also got this issue when using the cmdlet Get-AzureADPolicy from the AzureADPreview module today. The cmdlet is basically calling the GET https://graph.microsoft.com/beta/policies endpoint.

**Comment by watahani** [comment]
Hi @despingu 
I confirm that issue has been fixed in data center. If you have still same issue, please contact azure ad support.

**Comment by crborgman** [comment]
I am also currently getting this issue, with both the powershell commandlet and a graph api call
