### ISSUE TITLE
GetById: MySite not returned for users even if using $select

### ISSUE THREAD

**Issue by MrTantum** [microsoftgraph/microsoft-graph-docs#6841]
According to [this](https://docs.microsoft.com/de-de/graph/known-issues) page the `GetById `Endpoint currently works with $select because it does not return complete user objects:

> **Incomplete objects when using getByIds request**
> Requesting objects using Get directory objects from a list of IDs should return full objects. However, currently user objects on the v1.0 endpoint are returned with a limited set of properties. As a temporary workaround, when you use the operation in combination with the $select query option, more complete user objects will be returned. This behavior is not in accordance with the OData specifications. Because this behavior might be updated in the future, use this workaround only when you provide $select= with all the properties you are interested in, and only if future breaking changes to this workaround are acceptable.

Nearly all of the properties are returned but `mySite` is missing for some reason (even when using Graph Beta).

![image](https://user-images.githubusercontent.com/31658807/72618110-b70a1880-393a-11ea-9cdb-6754ef800979.png)

Are still not all properties supported yet or is this is bug?

If not supported please add it. Otherwise we currently have to go back making one call for each user we want to process. This would slow down performance from perfect to horrible again for this specific topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652f070a-a126-9add-13db-e35250b8b86c
* Version Independent ID: d256be5b-8466-385f-32a4-2d9fd9a89886
* Content: [Get directory objects from a list of ids - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryobject-getbyids?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-getbyids.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryobject-getbyids.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by keylimesoda** [comment]
Internal product bug opened to track this issue. Will update through triage and resolution.

**Comment by keylimesoda** [comment]
Bug triaged, added to product backlog at priority 2, severity 3.

Will update when it is added to team sprint.

**Comment by davidmu1** [comment]
No change currently to the page. Closing the issue. Information will be added when functionality is available.
