### ISSUE TITLE
Extension class is protected internal

### ISSUE THREAD

**Issue by Norrch2** [microsoftgraph/microsoft-graph-docs#6848]
Hello, I was reviewing your example and it indicated instantiating a new "Extension" class. Per the latest build of Microsoft.Graph.Beta, the extension class is protected internal and not able to be instantiated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33422520-6243-dd3f-d580-142221bb9c5f
* Version Independent ID: 72aee265-bb3a-35f1-6848-028fbdf96355
* Content: [Update open extension - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/opentypeextension-update?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/opentypeextension-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/opentypeextension-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@Norrch2 Are you talking about the Microsoft Graph beta client library?

**Comment by Norrch2** [comment]
Yes.

________________________________

**Comment by dkershaw10** [comment]
@MIchaelMainer Can you help here (assuming this is the .Net client library)?

**Comment by Norrch2** [comment]
Sorry If I wasn’t clear. Yes this is for the beta .net client library.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Torvin** [comment]
You're supposed to use the derived `OpenTypeExtension` class instead.

**Comment by dkershaw10** [comment]
@Norrch2 I'll assume you have this working now through @Torvin's suggestion.  If not please re-activate. Also this capability is GA - so please use the v1.0 endpoint (or the GA client library).
