### ISSUE TITLE
The createUploadSession is returning an uploadurl longer than 2000 chars which is breaking the limit in IE and Edge

### ISSUE THREAD

**Issue by figgsoftware** [microsoftgraph/microsoft-graph-docs#685]
Because of the access_token and proof_token url params the returned upload url is more than 2000 chars. This is causing the preflight OPTIONS request of an ajax PUT to abort in Internet Explorer and Edge. Works fine in Chrome. Please provide some other option of providing the access_token and proof_token (i.e. in the header).

See https://jsfiddle.net/qwp5vocc/7/

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
