### ISSUE TITLE
Return licenseDetails in list users

### ISSUE THREAD

**Issue by d-mariano** [microsoftgraph/microsoft-graph-docs#6857]
Cannot list license details for all users via [list all users](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http). Parsing the return of listing all users is unconventional and potentially inaccurate as you need to somehow join provisioning statuses to service plans and service plans to licenses; they are all in separate JSON objects and do not reference each other.

The return of a [licenseDetails](https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-beta&tabs=http) object returns a JSON object that already represents the relationship between a users' service plan, the provisioning status for said service plan, and the exact license a service plan belongs to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94344cb4-a73b-81b9-03a0-afce12f550b5
* Version Independent ID: 92ebd94c-a4f3-9657-95eb-d76fab8e3f56
* Content: [List licenseDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-list-licensedetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list-licensedetails.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@d-mariano Unfortunately this API is an expensive calculated API, so cannot be used with `GET /users?$expand=licenseDetails` AFAIK.  You can request this idea using [Microsoft Graph UserVoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests).  There may be other options, depending on the scenario you are trying to enable too.  Can you provide more details on your scenario please?

**Comment by hari1692** [comment]
Is there any option to get office365 license details alone? instead of user specific license

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
