### ISSUE TITLE
ccRecipients does not work for invitation

### ISSUE THREAD

**Issue by sujitks** [microsoftgraph/microsoft-graph-docs#6861]
Hi,
I am trying to send b2b invitation to guest users and using ccRecipients object. Invitation message is going to guest however cc messages does not.

Do you have any example/sample for this? I have tried using one recipient and multiple both with no success.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba8d0d2-dce7-23a2-91a7-d8c6eac5627c
* Version Independent ID: 08119651-f376-243e-130c-ffc5a2fbd05d
* Content: [Configuring the invitation message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitedusermessageinfo?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/invitedusermessageinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/invitedusermessageinfo.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @girish
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies @sujitks for the delayed response to this issue. The following is an example request that sends the message to both the invitee and the ccRecipients

**Request**
```json
POST https://graph.microsoft.com/v1.0/invitations
Content-type: application/json

{
    "invitedUserEmailAddress": "test@fabrikam.com",
    "inviteRedirectUrl": "https://myapps.microsoft.com",
    "sendInvitationMessage": true,
    "invitedUserMessageInfo": {
        "messageLanguage": "en-US",
        "ccRecipients": [
            {
                "emailAddress": {
                    "name": "Contoso Admin",
                    "address": "admin@contoso.com"
                }
            }
        ]
    }
}
```

**Response**
```json
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#invitations/$entity",
    "id": "310cebc9-4afd-40d7-a592-ffec11b0f32a",
    "inviteRedeemUrl": "https://login.microsoftonline.com/redeem?rd=https%3a%2f%2finvitations.microsoft.com%2fredeem%2f%3ftenant%3d84841066-274d-4ec0-a5c1-276be684bdd3%26user%3d310cebc9-4afd-40d7-a592-ffec11b0f32a%26ticket%3dywvLqd8SGKhO5tp9YEZndGP%252bwQz%252bjrm11EqtriQdRnE%253d%26ver%3d2.0",
    "invitedUserDisplayName": null,
    "invitedUserType": "Guest",
    "invitedUserEmailAddress": "test@fabrikam.com",
    "sendInvitationMessage": true,
    "inviteRedirectUrl": "https://myapps.microsoft.com/",
    "status": "PendingAcceptance",
    "invitedUserMessageInfo": {
        "messageLanguage": "en-US",
        "customizedMessageBody": null,
        "ccRecipients": [
            {
                "emailAddress": {
                    "name": null,
                    "address": "admin@contoso.com"
                }
            }
        ]
    },
    "invitedUser": {
        "id": "ea965b79-4e9b-400f-9424-76827eafd536"
    }
}
```
