### ISSUE TITLE
Endpoints does not return the birthday value

### ISSUE THREAD

**Issue by Psuban** [microsoftgraph/microsoft-graph-docs#6866]
For all people api endpoints I have tried it looks like the birthday value is not being returned at the moment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3808467e-580d-f890-faf5-ae2cd473a7bf
* Version Independent ID: ab6994b8-039c-3dd7-467d-6b764bee1b6f
* Content: [Use the People API in Microsoft Graph to get information about the people most relevant to you - Microsoft Graph](https://docs.microsoft.com/en-us/graph/people-example#feedback)
* Content Source: [concepts/people-example.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/people-example.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Psuban** [comment]
for example - https://graph.microsoft.com/v1.0/me/people/

stackoverflow post - https://stackoverflow.com/questions/59637219/microsoft-graph-people-api-does-not-return-the-birthday-values-https-docs-mic

**Comment by simonhult** [comment]
@Paul McKevitt<mailto:paulmck@microsoft.com> can you pick this up? Also, can you work with @Jeremy Thake<mailto:Jeremy.Thake@microsoft.com> to have the People API be routed directly to you?

________________________________
Fra: Psuban <notifications@github.com>
Sendt: Tuesday, January 21, 2020 9:13:54 AM
Til: microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com>
Kopi: Simon Hult <simonhul@microsoft.com>; Assign <assign@noreply.github.com>
Emne: Re: [microsoftgraph/microsoft-graph-docs] Endpoints does not return the birthday value (#6866)


for example - https://graph.microsoft.com/v1.0/me/people/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgraph.microsoft.com%2Fv1.0%2Fme%2Fpeople%2F&data=02%7C01%7Csimonhul%40microsoft.com%7C4d887c3f11c147837ada08d79e954b9a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637152236365582254&sdata=equYu%2Bq3cdslTtAOQcqBUIWZ6mdAIx1nD1n8UwIpB2A%3D&reserved=0>

stackoverflow post - https://stackoverflow.com/questions/59637219/microsoft-graph-people-api-does-not-return-the-birthday-values-https-docs-mic<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F59637219%2Fmicrosoft-graph-people-api-does-not-return-the-birthday-values-https-docs-mic&data=02%7C01%7Csimonhul%40microsoft.com%7C4d887c3f11c147837ada08d79e954b9a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637152236365582254&sdata=j1m%2FcZQYWekrgkonD%2BoAfO7MW2rXxyEvaFX8BPB%2BrkM%3D&reserved=0>

**Comment by Psuban** [comment]
hey all, just out of interest do we know when this might be resolved or is there a way i track the status

**Comment by PeterNjorogeMS** [comment]
@Psuban I will be following up with this and share feedback. cc @simonhult

**Comment by PeterNjorogeMS** [comment]
@Psuban after following up with this, I was informed it was intentional not to include the birthday. However, we are working on updating the API this should help resolve this and you will have the birthday data. We are working on an April-May timeline.

**Comment by Psuban** [comment]
Great thanks @PeterNjorogeMS . Look forward to see the change :)
