### ISSUE TITLE
Can I retrieve all a list of the Office365 applications?

### ISSUE THREAD

**Issue by mijgame** [microsoftgraph/microsoft-graph-docs#687]
Hello everyone,

A quick question: is it possible to retrieve all the applications that Office365 provides natively? I mean the applications that are listed in the App launcher on portal.office.com. I am new to Graph / Microsoft API's and I am drowning in the amount of portals, sites and different types of API, so if this is not the right place for this question I am sorry.

Thanks in advance

**Comment by AveAdam** [comment]
Cannot.
Only load the applications registered by your tenant.
You can manage your owned applications in [Azure Portal](https://portal.azure.com)

**Comment by keyur32** [comment]
Hi @mijgame, yea, we do not have the ability  to query for this today. Also, we understand the feedback around having too many sites and different apis and are working to resolve this.

I have added this request to our user voice. Feel free to subscribe to it to stay tuned to updates.
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17721415-get-a-list-of-office-365-applications

thanks
