### ISSUE TITLE
Outlook headers are ignored?

### ISSUE THREAD

**Issue by jdelforno** [microsoftgraph/microsoft-graph-docs#6870]
outlook.timezone = AEST / Australia Eastern Standard Time / Australia Eastern Standard Time / +10GMT / +10

None of these actually work. Nor does setting the text body. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc651382-4054-c223-b87b-5b6d84d34da4
* Version Independent ID: 89d769b4-34d3-2970-e76e-9ac94a30f1f5
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-calendarview?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-calendarview.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
The header is actually `Prefer`, with the value being `outlook.timezone="..."`. When I try this with your values, I don't see it ignored, I see:

```
{
    "error": {
        "code": "TimeZoneNotSupportedException",
        "message": "A valid TimeZone value must be specified. The following TimeZone value is not supported: 'Australia Eastern Standard Time'.",
        "innerError": {
            "request-id": "752e6adf-d207-4e9d-b72b-47a8f4343f43",
            "date": "2020-01-22T19:10:18"
        }
    }
}
```

It appears that the correct string here is `AUS Eastern Standard Time`. I found this by doing a GET /me/outlook/supportedTimeZones. Using that string works.

![image](https://user-images.githubusercontent.com/8966342/72926010-adf5be80-3d21-11ea-9f86-2e38f5136da2.png)

**Comment by jdelforno** [comment]
I'll investigate it tonight. Thanks @jasonjoh

**Comment by dkershaw10** [comment]
Assuming this is working.  @jdelforno please reactivate if necessary.
