### ISSUE TITLE
is this something that is coming in the future?

### ISSUE THREAD

**Issue by chadmcox** [microsoftgraph/microsoft-graph-docs#6874]
nothing about this is working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0f258b-b61e-72a2-0caf-d9b7fff5857d
* Version Independent ID: 90c2edf2-51ee-6bab-84a6-3710a3f0ccd2
* Content: [signInActivity resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signinactivity.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Yeah - the docs were prematurely released.  It is working now (at least listing users with their signInActivity)
