### ISSUE TITLE
Not in table of contents

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#6879]
This page should be in the table of contents as it is super useful and buried at the moment and only discoverable via search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24fb9bb0-8354-a495-449a-fdc320a08545
* Version Independent ID: 9f4bd107-4d8b-650a-2c3c-cd4ba196e0b7
* Content: [List endpoints - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-list-endpoints?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/group-list-endpoints.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list-endpoints.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Added the pages to the table of contents and to the resource page.
