### ISSUE TITLE
ETA on Application support for CAPs? 

### ISSUE THREAD

**Issue by dotMikeH** [microsoftgraph/microsoft-graph-docs#6883]
Sorry in advance if the docs page isn't the right area to open this issue. 
Title really says it all.  Would like to know when the follow requests can be done as an application.

`PATCH /conditionalAccess/policies/{id}`
`POST /conditionalAccess/policies/`
`DELETE /conditionalAccess/policies/{id}`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1052ee37-5a9e-d36d-2767-a39cdbd5a4df
* Version Independent ID: 10b8d865-1b5b-732f-70c9-a75ea83ce15b
* Content: [Create conditionalAccessPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conditionalaccessroot-post-policies.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by paul-hugill** [comment]
I agree that this is a critical use case and makes the feature a bit useless for me without it.
I think Post and Patch mostly work with Application permissions assigned now, I have not tried Delete though.

The issue I am still seeing is Post and Patch when you are specifying Applications in the policy itself.
When I do that, I get this error:
Insufficient privileges to create or update policy. Application.Read.All or Directory.AccessAsUser.All scope is required to add/edit application condition.

**Comment by videor** [comment]
App-only permissions are now supported for full CRUD operations. Please look at the required permissions - https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-1.0&tabs=http

For, read operation only Policy.Read.All is required. For read and write all three permissions are required - Policy.Read.All, Policy.ReadWrite.ConditionalAccess and Application.Read.All
