### ISSUE TITLE
TeamsAppId is not Application Id, but teamsAppDefinition.teamsAppId

### ISSUE THREAD

**Issue by wolskis** [microsoftgraph/microsoft-graph-docs#6884]
Documentation for custom tabs says
&gt; The teamsAppId is the same as the id in the app manifest schema for Microsoft Teams.

This does not appear to be the case.  Posting a request to create a custom tab with app id from manifest returns:
&gt; App id [XXXX] needs to be installed to the team [XXXX] and be in an unblocked state to install/update a tab
This error returns regardless of install or config state.

If one retrieves the team's installedApps (GET v1.0/teams/{team id}/installedApps?$expand=teamsAppDefinition), you will find a teamsAppDefinition object like the following
```
"teamsAppDefinition": {
                "id": "XXXXXX",
                "teamsAppId": "XXXXX",
                "displayName": "App name",
                "version": "1.0.0"
            }
```

If you then POST using that Id
"teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps/{teamsAppDefinition.teamsAppId}"

The request is processed, but again returns an error
&gt;"The specified app does not support tabs. AppId:c949793f-280e-4225-9030-95f98ecf3dc4"

The apps we have tested with both support and install tabs, and so must support them. 

Suspect that some validation on the v1.0/teams/{teams id}/channels/ endpoint is incorrectly invalidating actual app IDs, and that teamsAppDefinition.teamsAppId pass validation, but are inappropriate for the request being made. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#feedback)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment]
@wolskis , Did you try with the Id value given in the response not the one in teamsAppDefinaiton.Id.
{
            "id": "**this_id**",
            "teamsAppDefinition": {
                "id": "xxxxx",
                "teamsAppId": "xxxxxx",
                "displayName": "Name",
                "version": "1.0.0"
            }
        }

**Comment by Subhasish-msft** [comment]
@wolskis  Can you please confirm if it is working, I am closing it. Please reopen if you get the issue.
