### ISSUE TITLE
The fourth example gets the MIME content is not implemented by the Java SDK 

### ISSUE THREAD

**Issue by oscarcosta** [microsoftgraph/microsoft-graph-docs#6886]
The fourth example "gets the MIME content of a message in the signed-in user's mailbox" is not implemented by the Java SDK, as stated by this bug https://github.com/microsoftgraph/msgraph-sdk-java/issues/323

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bf275f-7a02-7e90-120f-2e1d055dac95
* Version Independent ID: b1556931-c2fd-7400-4e45-d666a8a53540
* Content: [Get message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=java#feedback)
* Content Source: [api-reference/v1.0/api/message-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kumbhaj** [comment]
you can make custom request using IgraphClient object.
`JsonObject ob = graphClient.customRequest(
				"/users/ {id} /messages/ {id}/ $value")
				.buildRequest().get();`

**Comment by baywet** [comment]
Hi @oscarcosta 
Thanks for the feedback and for the patience.
This is due to a code generation issue for the SDK. And it's being addressed.
You can find more details here https://github.com/microsoftgraph/msgraph-sdk-java/issues/323#issuecomment-698348116
This issue will be closed whenever the pull requests get merged.
