### ISSUE TITLE
cannot find Java example for uploading file to share-point online site using MS graph Java SDK

### ISSUE THREAD

**Issue by bdv1234** [microsoftgraph/microsoft-graph-docs#6889]
Objective:
I want to upload a file to folder in share-point site using MS graph Java sdk.

findings:
I have gone through the documentation and couldn't find any corresponding article.
There are samples using graph REST APIs, but there is no samples for graph SDK.

If you guys can provide some code samples for above mentioned using graphClient would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by darrelmiller** [comment]
Hey @andrueastman  Can you investigate why the sample for uploading a new file is not being generated?

**Comment by bdv1234** [comment]
@darrelmiller , @andrueastman any progress on java code samples for uploading a file to share-point ?

**Comment by seanpmaxwell** [comment]
Bump, I can't find any either

**Comment by darrelmiller** [comment]
There are load file upload samples in the docs now https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=java

**Comment by seanpmaxwell** [comment]
I need a full example that's in Java and uploading a PDF to sharepoint. Those examples are only bits and pieces of Java code.

**Comment by plutext** [comment]
https://github.com/plutext/java-docx-to-pdf-using-Microsoft-Graph may also help

**Comment by baywet** [comment]
Hey everyone,
Thanks for reaching out and thanks for your patience.
As Darrel mentioned, we do have a sample for large file upload in java now.
Also, we fixed a bug in the java generation process, a sample for java (small) files upload will be added soon. More details in #8429.
Closing
