### ISSUE TITLE
Form response never received

### ISSUE THREAD

**Issue by inovoselic** [microsoftgraph/microsoft-graph-docs#6891]
Hi guys, we applied on the request form to be approved for protected APIs in Microsoft Graph, but never got the response of any kind. We tried sending the email to teamsAppPerms@microsoft.com as well, but no response. Can you help me with more information about that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b32ca7f9-ea75-d0fd-f887-136e0c9686e3
* Version Independent ID: 6e9b24bc-9869-0b70-8881-3c4aad2bebed
* Content: [Protected APIs in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-protected-apis#feedback)
* Content Source: [concepts/teams-protected-apis.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-protected-apis.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by akarczag** [comment]
Same here. Can we get a follow up on this?

**Comment by kumbhaj** [comment]
Same here.

**Comment by fix2k5** [comment]
I've submitted application 2 weeks ago and have not received any response at all.

**Comment by anandab-gt** [comment]
In case you haven't received access please raise a fresh request. Check https://docs.microsoft.com/en-us/graph/teams-protected-apis for more details.
