### ISSUE TITLE
AuditLogs SignIns - Skip not allowed, and SkipToken is not allowed to be extracted and reused. How are we supposed to pick up from where we left off?

### ISSUE THREAD

**Issue by VictorioBerra** [microsoftgraph/microsoft-graph-docs#6892]
I am using the C# Microsoft.Graph.Beta Preview.

I have a script that pages hundreds and thousands of rows going at the max $top allowed (1000).

After about 487k, I get throttled:

&gt; "This request is throttled. Please try again after some time."

The default handler starts retrying 3 times, obviously it fails all three times before throwing, thus making the retry completely pointless IMO.

I have tapped into the `WithShouldRetry()` handler and added a 15 minute sleep, most of the time, it will retry a few more times then fail but this time with a `timeout` error. If I get lucky and the retry works, I get like 4 more records before complete failure again.

The interesting thing is, if I restart my whole app, it starts pulling down data happily again with no problem. Why is this? Is this due to my auth handler re-authing for a fresh auth token? Or is the skip stuff just so high that the backend can not handle it?

I am at the point where not having a $skip and not being allowed to extract and reuse a $skipToken means I have absolutely no way of picking up where I left off.

Please advise.

EDIT More info from my apps log files:

```
2020-01-23 14:15:08.455 -06:00 [INF] Requested Audit Logs - Sign Ins. Got: 1000 | total: 500000 | Skip Token: redacted_500000
2020-01-23 14:15:15.934 -06:00 [INF] Requested Audit Logs - Sign Ins. Got: 1000 | total: 501000 | Skip Token: redacted_501000
2020-01-23 14:15:22.772 -06:00 [INF] Requested Audit Logs - Sign Ins. Got: 1000 | total: 502000 | Skip Token: redacted_502000
2020-01-23 14:15:41.293 -06:00 [WRN] Should retry handler is running. StatusCode: "TooManyRequests"
2020-01-23 14:15:41.295 -06:00 [WRN] Total retries 3 current try 1
2020-01-23 14:15:41.296 -06:00 [WRN] Content {
  "error": {
    "code": "",
    "message": "This request is throttled. Please try again after some time. CorrelationId: redacted_can_provide_if_needed",
    "innerError": {
      "request-id": "redacted_can_provide_if_needed",
      "date": "2020-01-23T20:15:40"
    }
  }
}
2020-01-23 14:15:41.297 -06:00 [INF] Exponentially backing off. Current backoff time in MS: 1200000 minutes: 20
2020-01-23 14:35:41.459 -06:00 [WRN] Timeout from API detected. We have been blocked for a bit. Waiting for MS: 1200000, 20 minutes
```

You will notice I did a `Thread.Sleep` for 20 minutes, and then it retired and almost instantly failed with a "timout". That does not make any sense to me. Also, I can hit the restart button on my app and it will start flying through records again with no issues. What am I missing here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 637c0260-f07d-b6d6-29ff-c21153daf742
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/signin-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by spmanjunath** [comment]
@VictorioBerra :  Sorry to bother you.  I am trying to use WithShouldRetry() to implement custom evaluation of retry policy, however, the delegate event is never triggered.  I couldn't find any sample implementation, or documentation on the usage.  It would be helpful if you could share the way you have used WithShouldRetry() method.  I have implemented it as below, the expectation is that for any exception WithShouldRetry() will be called and based on the delegate evaluation subsequent retry mechanism is set.
```
_graphServiceClientFactory.GetClient().Drives[driveId].Root.ItemWithPath(path).ListItem.Fields.Request()
                       .WithShouldRetry((delay, attempt, httpResponse) =>
                        (attempt <= 5 &&
                        (httpResponse.StatusCode == HttpStatusCode.Conflict)))
                       .UpdateAsync(new FieldValueSet { AdditionalData = dataDictionary });
```
Thanks.

**Comment by VictorioBerra** [comment]
@spmanjunath I no longer have the code I think mine did not work either.

**Comment by davidmu1** [comment]
Thank you for the feedback. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). Please ask your question there. No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
