### ISSUE TITLE
Trying to install app with manifest appid doesn't work

### ISSUE THREAD

**Issue by tfischer** [microsoftgraph/microsoft-graph-docs#6894]
When I try to use my app id (as specified in my manifest.json) to (1) check to see if the app is installed for a user and (2) try to install the app for a user using the above apis, it doesn't seem to work.  However, there is an id that appears when listing installed apps via:

GET https://graph.microsoft.com/beta/appCatalogs/teamsApps

(my manifest.json id appears as 'externalId' in this api)
If I use this id in the above calls (/users/{user-id}/teamwork/installedApps), it seems to work.  This is not documented here.  Two questions:

1) Am I doing something wrong here or missing a step?
2) If not, how is a daemon application (like the proactive messaging bot I am writing) intended to get this id, since the https://graph.microsoft.com/beta/appCatalogs/teamsApps api does not support application permissions?

thanks,
Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4690677-2b12-0d63-06db-45172132f540
* Version Independent ID: 129f7f1f-78c4-4e80-2eac-f0ce7619f231
* Content: [Proactive messaging using a bot in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-proactive-messaging#feedback)
* Content Source: [concepts/teams-proactive-messaging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-proactive-messaging.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markthiessen** [comment]
I'm also trying to find a way to get this ID programmatically, with no luck so far. As a workaround, I've resorted to manually finding this ID and adding it to some persisted tenant settings in my app, which is not ideal.

**Comment by erwelch** [comment]
Any update on this? I'm running into a similar issue as well because I would like to programmatically fetch a `channelId` using the `user-id` and `teamsAppId`.

**Comment by AkJo** [comment]
All 'installation' operations are done using the 'teamsApp' id. This is the id of the teamsApp resource whose collection is returned on a GET /appCatalog/teamsApps call. 

If you only have the external app id, then please use the following query to retrieve the teamsApp id.

GET /appCatalog/teamsApps?$filter=externalId eq '{your-app's-external-id}'

Use the 'id' (say X) from the response to call into any of the installation APIs.

POST /teams/{team-id}/installedApps
{
"teamsApp@odata.bind":"https://graph.microsoft.com/beta/appCatalogs/teamsApps/X"
}

**Comment by AkJo** [comment]
@tfischer, this response if kind of late, but it is not the manifest id but the system generated 'teams app id' which is used to uniquely identify any teams app in the system via the MS Graph APIs.

You need to use the teamsApp Id in the installation APIs.

**Comment by erwelch** [comment]
@AkJo - thanks for this response! Question about this: 

> If you only have the external app id, then please use the following query to retrieve the teamsApp id.
> 
> GET /appCatalog/teamsApps?$filter=externalId eq '{your-app's-external-id}'

This API requires a delegated permission (`AppCatalog.ReadWrite.All`). Is there another API to find the internal teams app ID using the external ID with application permissions?

**Comment by AkJo** [comment]
@erwelch , currently app context is not supported in this API. It is in our backlogs. If you were to spell out your scenario, it might help in prioritization.

**Comment by adiun** [comment]
@AkJo Can we please fix this doc at least? There are two issues:

1. The doc says to use application permissions - this is wrong
2. The subsequent API says "Where {teamsAppId} is the id in the Teams app manifest that you made note of previously" - this is wrong too since it requires an internal teamsAppId

**Comment by Prithvi-MSFT** [comment]
Hi @tfischer ,
Since application permissions are not supported you will need to provide the id externally to app obtained using delegated permissions. You can store the id's and use them in your application.


Thanks
