### ISSUE TITLE
Incorrect C# snippet for Request 2

### ISSUE THREAD

**Issue by jahbenjah** [microsoftgraph/microsoft-graph-docs#6899]
The C# snippet for Request 2 is incorrect. It's using  `microsoft.graph.timeZoneStandard'Iana'` instead of 
`Microsoft.Graph.TimeZoneStandard.Iana`
```cs
 var supportedTimeZones = await graphClient.Me.Outlook
                .SupportedTimeZones(microsoft.graph.timeZoneStandard'Iana')
                .Request()
                .GetAsync();
```

The correct is here

```cs
 var supportedTimeZones = await graphClient.Me.Outlook
               .SupportedTimeZones(Microsoft.Graph.TimeZoneStandard.Iana)
               .Request()
               .GetAsync();
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03a09144-1c0b-7e8e-cd0f-7b8a84489b5c
* Version Independent ID: f45d8ded-bdee-3ea1-e2e5-632488c8a996
* Content: [outlookUser: supportedTimeZones - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/outlookuser-supportedtimezones?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/outlookuser-supportedtimezones.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/outlookuser-supportedtimezones.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@andrueastman , can you please look into this possible issue in the generation code, and have the specified docs updated as appropriate? Thanks!

**Comment by andrueastman** [comment]
I will pick this up and resolve.

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoftgraph/microsoft-graph-docs/pull/8656
