### ISSUE TITLE
Documentation Doesn't match And Example didn't work

### ISSUE THREAD

**Issue by Dagger55555** [microsoftgraph/microsoft-graph-docs#6907]
Example:  "Get all emails received by the signed-in user in April 2017."
As per other API documentation I get the error:
message=The '$filter' parameter value is not supported for 'Messages' resource; only a value of 'ReceivedDateTime ge value' is supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#feedback)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @Dagger55555 
Thanks for reaching out!
To be clear, are you talking about this specific query? `https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$filter=ReceivedDateTime ge 2017-04-01 and receivedDateTime lt 2017-05-01`
I just tried it on one of my tenants and it seems to be working so far.

**Comment by Dagger55555** [comment]
It is hit and miss.

I was very excited when I saw the documentation and when I first tried it I had success.
I then tried adding a time element as I wasn’t sure if LE would be end of day or beginning.  I got invalid filter.
So I tried what you did with LT with the day after and got the same error.
I figured there might be a special undocumented feature that only worked in the same month so I went back to my original query and it failed.
I’m assuming not all the servers are on the same page.
I happen to be using the beta end-point, but I assume it would be generally more powerful.



Doug Dagworthy
Co-Founder & Technical Lead
Devlos Software, Inc.
Work: (647) 695-5856
Email: dougd@devlossoftware.com<mailto:dougd@devlossoftware.com>
[cid:image001.png@01D5D4F7.2D3A8C40]
Visit our website<http://www.soluno.legal/>

**Comment by baywet** [comment]
Thanks for the quick answer.
Can you provide the exact request you are tying to execute and that's failing please?

**Comment by Dagger55555** [comment]
I use fiddler:
I’ve never tried, but I know there are export options that I could send as well….thinking it is because I’m Canadian???

[cid:image002.png@01D5D50D.285CF710]


Doug Dagworthy
Co-Founder & Technical Lead
Devlos Software, Inc.
Work: (647) 695-5856
Email: dougd@devlossoftware.com<mailto:dougd@devlossoftware.com>
[cid:image001.png@01D5D50D.161FC690]
Visit our website<http://www.soluno.legal/>

**Comment by baywet** [comment]
Hey @Dagger55555 it looks like you're replying via email.
Unfortunately when you do that, images don't make it to GitHub.
Would you mind providing the information directly via the interface please?

**Comment by Dagger55555** [comment]
My fiddler session:
![image](https://user-images.githubusercontent.com/10311767/73199590-1fa78100-4103-11ea-90e8-94cb1aa5d3a1.png)

**Comment by baywet** [comment]
Looking at your request:
- You are trying to build a delta query and the documentation about limitations on filters can be found [here](https://docs.microsoft.com/en-us/graph/delta-query-messages#use-query-parameters-in-a-delta-query-for-messages)  (the documentation you initially commented on focuses on general query capabilities)
- In general /delta is the preferred URL for delta queries (in lieu of /microsoft.graph.delta)

**Comment by Dagger55555** [comment]
Not sure I exactly followed that tbh, but I'm using the graph C# to perform delta operations in an attempt to hide that level of detail.   So are you saying this line is not optimal:
                    messages = graphClient.Me.MailFolders[folder].Messages.Delta().Request().Filter(dateFilter).Header("Prefer", "odata.maxpagesize=100").GetAsync().Result;

Where my dateFilter is just what we've been playing with.

**Comment by baywet** [comment]
No worries, ignore my comment about the /delta thing. Another user seems to experience the same behavior (/microsoft.graph.delta instead of /delta) so I opened an issue at the right place for it.

For the filter: the filter you're trying to use is not supported, [here](https://docs.microsoft.com/en-us/graph/delta-query-messages#use-query-parameters-in-a-delta-query-for-messages) is a list of the limitations.

**Comment by Dagger55555** [comment]
Cheers re issue being opened.  Got it re general vs delta...Would really love that feature BECAUSE the reason I'm doing this is because my delta seems to get ignored randomly and I end up retrieving all messages again.  I work with lawyers who have 10K+ emails easily and when it resets my operation takes minutes.  I also need a large period 2015 on-wards but not all at once.  I really want to keep deltas per month and if one delta gets thrown out I'm only ready 1000 emails...still painful, but less so.  Now I'm kinda messed up:  If I just say > 2015 like I do today then i'm semi-constantly re-reading the world.  If I do monthly, then my Nov delta will include Dec info, Oct will include Nov plus Dec - I'm retrieving the same Dec record many times.  I'm also trying to keep copies locally (like Outlook) so I'm not constantly going back to your server.  As it is now, ... 
Thoughts?

**Comment by Dagger55555** [comment]
On a side-note, where would I post this issue:
For modifing contactss, I have to change the ODataType type retrieved to "Microsoft.OutlookSErvices.TypedEmailAddress" when it is set to "microsoft.graph.typedEmailAddress".  Basically a pure echo fails.

**Comment by baywet** [comment]
for the feature request => https://microsoftgraph.uservoice.com/
for the sdk issue => https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues
