### ISSUE TITLE
Missing imAddresses property

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#6909]
This is documented in v1.0.  Not sure if this was accidentally deleted.  Can we also double check properties documented in v1.0 that for some reason aren't documented in /beta?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8446021-6786-c54c-066f-d99ba4644312
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Made sure that all v1.0 properties are also listed on the beta page.
