### ISSUE TITLE
What Is A Resource?

### ISSUE THREAD

**Issue by timscott** [microsoftgraph/microsoft-graph-docs#6910]
A scheduleId can indicate a "resource", but the doc does not say what a "resource" is or give any link.

This is related to my question about getschedule here: https://github.com/microsoftgraph/microsoft-graph-docs/issues/6904. I would like to know how to get a schedule for a user that includes all of their calendars. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee10c689-b4a8-5e9a-ba50-a4aaaf14d722
* Version Independent ID: 9a8f1f4a-0852-436f-2845-9389a5687db2
* Content: [scheduleInformation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/scheduleinformation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/scheduleinformation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/scheduleinformation.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
As specified in the document: https://docs.microsoft.com/en-us/graph/api/resources/scheduleinformation?view=graph-rest-1.0

resource refers to a room or equipment
