### ISSUE TITLE
Cannot get permissions of specific user using app token

### ISSUE THREAD

**Issue by ivanmaria** [microsoftgraph/microsoft-graph-docs#6912]
We need to get the permissions of specific users on the list item using application token.

We are using the following endpoint to get the permission. 

https://graph.microsoft.com/v1.0/drives/&lt;drive_id&gt;/items/&lt;item_id&gt;/permissions

By using above endpoint we are only able to get the groups which are SharePoint defined with no base permission. Please let me know how to drive the user specific permission from the response of the above endpoint

If above is not possible, can you please provide the usecase where this endpoint can be used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1191235c-879e-dffc-82eb-4e8f7edfd29c
* Version Independent ID: 322f9be4-7921-41d8-78c2-2bdc62f916a3
* Content: [Permission - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/permission?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/permission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/permission.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by JeremyKelley** [comment]
For clarification are you trying to evaluate the permissions that a particular user would see on a file from an app only context?  App only should be able to see the actual grants on the item to indicate what groups or individuals (if there are any) have been ACL'ed to the item.  What exactly do you mean by "no base permission"?
