### ISSUE TITLE
Post Error?

### ISSUE THREAD

**Issue by Jason542** [microsoftgraph/microsoft-graph-docs#6916]
When I try to post and create a contact for another user (and it doesn't appear to be a permission issue), I get the following: "message": "The specified folder could not be found in the store.",  -- I'm using POST https://graph.microsoft.com/v1.0/users/user@upn.com/contacts -- and a simple {givenName: "Peter"} just to test.  Works if I run under my own context (/me/contacts)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2886d3e-18d5-1d6b-8ddb-03c8b42c1676
* Version Independent ID: 2d442186-8c46-9ae2-4c8e-860db6409b9a
* Content: [Create Contact - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-contacts?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-contacts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-contacts.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PeterChencha** [comment]
Hello @Jason542 thanks for reaching out. Kindly confirm if you are still facing the same issue, and if so kindly share the permissions scope your app is using. You can confirm the required permission scope here -> https://docs.microsoft.com/en-us/graph/outlook-get-shared-contacts-folders.

**Comment by PeterChencha** [comment]
Hello @Jason542 this issue appears fixed. Kindly feel free to open another issue if you are still facing this problem.
