### ISSUE TITLE
Docs a little bit out of sync

### ISSUE THREAD

**Issue by pc222** [microsoftgraph/microsoft-graph-docs#6920]
GET https://graph.microsoft.com/beta/deviceManagement/roleDefinitions/{roleDefinitionId}/roleAssignments will result in a 400 error.

```
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation with http verb GET for request /StatelessRoleAdministrationFEService/deviceManagement/roleDefinitions('{roleDefinitionId')/roleAssignments.",
        "innerError": {
            "request-id": "987dd29c-2fed-4f78-9f85-fdbbd5f38d22",
            "date": "2020-01-28T10:08:44"
        }
    }
}
```

You have to use "expand"

`https://graph.microsoft.com/beta/deviceManagement/roleDefinitions/{roleDefinitionId}?$expand=roleAssignments`
 
or

`https://graph.microsoft.com/beta/deviceManagement/roleDefinitions/{roleDefinitionId}?$expand=*`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ba52ec0-c4dc-54ed-e56f-0f2ace9e0017
* Version Independent ID: ea959550-a5bb-bb6e-c5c9-60c77f039e96
* Content: [List roleAssignments - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-rbac-roleassignment-list?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-rbac-roleassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-rbac-roleassignment-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JoeDibley** [comment]
Just FYI this is also on the v1.0 API Page too: [List RoleAssignments - Microsoft Graph V1.0](https://docs.microsoft.com/en-us/graph/api/intune-rbac-roleassignment-list?view=graph-rest-1.0)

**Comment by Joey40** [comment]
Very helpful, it looks like this still hasn't been fixed.

**Comment by triplanedave** [comment]
The No Route error sometimes occurs based on how our documentation is generated. I'll file a bug so it can eventually be cleaned out. The best method to validate an entity creation is by doing F12 developer tools in the browser and seeing the actual calls being made to create an object, or in this case, follow pc222's suggestion.
