### ISSUE TITLE
Permissions - Global Admins Only

### ISSUE THREAD

**Issue by icelandgrecian** [microsoftgraph/microsoft-graph-docs#6923]
Why is this endpoint only available for Global administrators? A none global admin can call the methods to add app and tabs to channels and teams they are owners of, but are unable to call this method to get a list of available apps. It would be useful to be able to call this before adding an app to a team that the app is available to be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01fcbc4f-ca00-a642-0a8f-6f5a38f452db
* Version Independent ID: 5832e5e8-9bb4-39bf-5ca0-0aff5b1677b7
* Content: [List the published apps from the Microsoft Teams app catalog - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsapp-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamsapp-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamsapp-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by balbany** [comment]
Seconding this. This is pretty useless as a piece of Teams Apps automation puzzle. Obviously the problem is a lack of a AppCatalog.Read.All resource permission. I can completely understand restricting AppCatalog.ReadWrite.All to Global Admin as it could be mailiciously abused pretty spectacularly.

**Comment by nkramer** [comment]
You can now read this resource without being a global admin.
