### ISSUE TITLE
Issue with image Urls within /content

### ISSUE THREAD

**Issue by nathanwienand** [microsoftgraph/microsoft-graph-docs#6925]
Image resources are being returned as:
https://graph.microsoft.com/v1.0/siteCollections/mydomain.sharepoint.com/xxxxxx/$value
accessing these url's via an authenticated GET api call will fail with a bad request:

Resource not found for the segment 'siteCollections'

after changing the url to:
https://graph.microsoft.com/v1.0/sites/mydomain.sharepoint.com/xxxxxx/$value
the GET call will then return the correct binary image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8de0d2-188e-f598-a729-80d00a703b8e
* Version Independent ID: 40371b25-cc40-d61d-3058-10f6f24168c7
* Content: [Get OneNote content and structure with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/onenote-get-content)
* Content Source: [concepts/onenote-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-get-content.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @nathantempelman  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-notes.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
