### ISSUE TITLE
Missing guidance for Graph API to Create Service Principal (SP) Resource Type

### ISSUE THREAD

**Issue by sriniambati** [microsoftgraph/microsoft-graph-docs#6926]
Under the Service Principal section, there is a documentation (https://docs.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-beta) to get, update, and delete, but it is missing guidance to for Graph API to Create Service Principal (SP) Resource Type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The create operation is defined here:

https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-serviceprincipals?view=graph-rest-beta
