### ISSUE TITLE
IEventDeltaRequest.SkipToken 

### ISSUE THREAD

**Issue by matjazreberc** [microsoftgraph/microsoft-graph-docs#6936]
Hello!
I want to create this example,
https://docs.microsoft.com/en-us/graph/delta-query-events?tabs=http
but i have problem with step 2, .SkipToken(".....")
The error is "IEventDeltaRequest' does not contain a definition for 'SkipToken' and no accessible extension method 'SkipToken' accepting a first argument of type 'IEventDeltaRequest' could be found (are you missing a using directive or an assembly reference?)"
Can somebody help me, what am i doing wrong?
My code:
var page = await graphClient
                    .Users[$"...."]
                    .CalendarView
                    .Delta()
                    .Request()
                    .SkipToken("R0usmcCM996atia_s")
                    .GetAsync();

Thanks, Matjaz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da37d83f-dd2b-dd85-eb5d-75208e26412d
* Version Independent ID: aa5f5279-bec8-fe6e-ab1b-8dc87f2ed688
* Content: [Get incremental changes to events in a calendar view  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-events?tabs=csharp#feedback)
* Content Source: [concepts/delta-query-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-events.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
thank you for reporting this @matjazreberc 
@andrueastman can you take a look at this please? Thanks!

**Comment by andrueastman** [comment]
@matjazreberc For now, you can achieve the desired effect by using the snippet below.
```cs
var queryOptions = new List<QueryOption>()
{
    new QueryOption("$skiptoken", "R0usmci39OQxqJrxK4")
};

var delta = await graphClient.Me.CalendarView
    .Delta()
    .Request(queryOptions)
    .Header("Prefer","odata.track-changes")
    .GetAsync();
```

@baywet I will action this on the snippet generator to reflect this fix.

**Comment by baywet** [comment]
@andreueas thanks for making the update on the generation side. Are we good to close this issue now?

**Comment by andrueastman** [comment]
@baywet We can leave it open for now. 
I will close the issue once the change goes live in the docs in the coming week.
