### ISSUE TITLE
Section dealing with recovering lost chatThreadID is unavailable to devs as needed Application permissions are not available

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs#6937]
Document says If you lose the chatThreadId, you can find it again by calling:
GET /users/{user-id}/chats?$filter=installedApps/any(a:a/teamsApp/id eq '{teamsAppid}')

However this requires Application Permissions, which are not available https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&tabs=http

So what is the current recommendation for an app developer to retrieve the chatThreadID for personal scope, if the initial app added event was missed or was missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4690677-2b12-0d63-06db-45172132f540
* Version Independent ID: 129f7f1f-78c4-4e80-2eac-f0ce7619f231
* Content: [Proactive messaging using a bot in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-proactive-messaging#get-the-chat-thread-id)
* Content Source: [concepts/teams-proactive-messaging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-proactive-messaging.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
You only options if Application Permissions aren't available are to either wait until the end user sends your bot a message, or call the getMembers endpoint in a team/group chat the user is a part of. If you know the 29:* Id for the user you can always call create conversation which will return the conversation Id (even if the conversation is already created)

**Comment by GauravES** [comment]
When we mean Application Permissions are not available, it is not that our tenant Admin has not granted them, it is that your docs say that that specific API end point can not be granted Application Permissions. In this case, the documentation for the Proactive Messaging is misleading as it assumes that Application Permissions will be available.

**Comment by Chekrii** [comment]
Hi all,

How to get the 29:* Id of the user by using ` chat thread ID API ` to send a notification to the user from personal scope.

Thanks.
