### ISSUE TITLE
Bad GateWay: /teams/{teamId}/channels/{channelId}/tabs

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#6944]
I have been getting this error today morning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002fd0aa-9008-9299-e29f-fb26f4d1b1e7
* Version Independent ID: bd94c468-347b-1db6-8c61-50d8a6ae58b6
* Content: [List tabs in channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamstab-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
Without knowing what error I can't do much with this bug.

**Comment by nkramer** [comment]
If you continue to see this, please reopen with the following info:
- The URL and http verb for the method of interest (eg: POST https://graph.microsoft.com/beta/teams/{id}/channels)
- Application permissions or user delegated permissions?
- The request - id from a call thats failed within the last 24 hours (we only keep a few days of logs)
- The payload you passed in, and the payload you got back
- The http response code
- If it was a 401 or 403, why do you think this was a mistake? What permission scopes are you calling it with?
Thx.
