### ISSUE TITLE
permissions incorrect

### ISSUE THREAD

**Issue by JapNolt** [microsoftgraph/microsoft-graph-docs#6945]
In my testing using Delegated auth (work account), it appears like I need at least Group.Read.All. Anything less than that doesn't work. Am I doing something wrong? Is this how it should be? Are the docs wrong or is Graph requiring more than it should?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jublair** [comment]
+1

**Comment by yyuank** [comment]
I added GroupMember.Read.All to the set of permissions as well. To read group memberships, GroupMember.Read.All is the minimum permission required. User permissions are required, if you want to read the properties of users that are members of the group. Without user permission, you can only read the links of the users.
