### ISSUE TITLE
How to get presence away "last seen" / "away since" 

### ISSUE THREAD

**Issue by harlankoehn** [microsoftgraph/microsoft-graph-docs#6948]
Is there any way to get the "Last seen" / "Away since" datetime on the graph presence API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d56857e6-428f-e4ea-f77e-e2662fc7e7ae
* Version Independent ID: 01e364fb-9af7-8fe6-a662-185ed233132d
* Content: [Get presence - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/presence-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @harlankoehn we don't currently support that functionality
