### ISSUE TITLE
Authorization response when user does not give consent

### ISSUE THREAD

**Issue by psterpe** [microsoftgraph/microsoft-graph-docs#6949]
If the user decides not to give consent, what will the authorization response contain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ef7a19-9ce7-7b73-8fa5-b071efacf6ba
* Version Independent ID: 03006629-3161-c4f7-355e-f94a462626e0
* Content: [Get access on behalf of a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-user#feedback)
* Content Source: [concepts/auth-v2-user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
The Azure OAuth docs give more detail on this here: https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow#error-response

You'd get an `access_denied` error. The `error_description` would have text indicating the user canceled authentication.
