### ISSUE TITLE
What will be a default wait Time for 429

### ISSUE THREAD

**Issue by vikrantrajput007** [microsoftgraph/microsoft-graph-docs#6951]
for some endpoint, we don't return retry-after header, in those case what should be a wait time. What is best practice consumer need to have in their application? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling?source=docs#best-practices-to-handle-throttling)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @vikrantrajput007 
Thanks for pointing out the lack of guidance in our documentation.
I just authored a pull request to provide more guidance to readers #6954
We don't recommend waiting a fixed time over and over again, that can lead to traffic congestion  (if you have multiple requests failing at the same time, they'll all retry at the same time and potentially cause each over to be throttled).
If no retry-after header is provided, we recommend instead to implement a exponential backoff retry policy.
Note that if you're using the Microsoft Graph SDK's, they already do this for you!
When the pull request is resolved, it will close the issue automatically.

**Comment by Visinghr** [comment]
Thanks @baywet and @Lauragra - thanks for the quick response and document update.
