### ISSUE TITLE
Paging example?

### ISSUE THREAD

**Issue by trebgatte** [microsoftgraph/microsoft-graph-docs#6965]
Can we get some examples of how to call this API where paging would be required? For example, if I get back 5000 results, how to I retrieve these in batches to prevent throttling?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files#feedback)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmoreau** [comment]
Paging is built in the API using from and size. 
See :  https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta#page-search-results
Regarding throttling : the Search API is not necessarily the most optimal way to suck data. There are throttling limit which are mostly resource based and are not published. Any reasonable User experience scenario should not be throttled.
