### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by FrancoisNevo** [microsoftgraph/microsoft-graph-docs#6969]
Hello, I think there is a typo in the sentence: "By default, Microsoft Graph serves mailbox-only results, which do not include directory/orgainization results."

It should be "organization", not "orgainization".

Also, I am not sure to understand this sentence properly so I have some questions.

1) Does "mailbox" stands for "A location where email is delivered", or is it a directory named "mailbox"?

2) Does "directory/organization" is a path where "organization" is a sub-folder of "directory", or does it mean "the directory or the organization"? 

3) Does "Microsoft Graph serves mailbox-only results" means "The results provided by Microsoft Graph are only related to a mailbox"?

Thanks for you help,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3808467e-580d-f890-faf5-ae2cd473a7bf
* Version Independent ID: ab6994b8-039c-3dd7-467d-6b764bee1b6f
* Content: [Use the People API in Microsoft Graph to get information about the people most relevant to you - Microsoft Graph](https://docs.microsoft.com/en-us/graph/people-example#feedback)
* Content Source: [concepts/people-example.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/people-example.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @Anthona
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @FrancoisNevo for highlighting the issue.
The page is now up-to-date via PR #6977. Thank you @JarbasHorst 

No additional updates identified for the page. Closing the issue.
