### ISSUE TITLE
Search query parameter is now supported for (SPO) Sites resource

### ISSUE THREAD

**Issue by BrianTJackett** [microsoftgraph/microsoft-graph-docs#6971]
Search query parameter can now be used to search / enumerate SharePoint Online sites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#search-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
thank you for reporting the issue in the docs @BrianTJackett would you mind authoring the PR?

**Comment by BrianTJackett** [comment]
I would, but I honestly don't know what level of support or the syntax for sending in queries.  The most I've done is to pass is ".../sites?$search=*" to enumerate the site collections of a tenant.  I'm hoping someone in engineering or community can better explain what support to expect.

**Comment by BrianTJackett** [comment]
I found this article which describes the site-search filter.  Unfortunately it doesn't cover the syntax for keywords or which properties are indexed, but I'll open a separate issue for that.

[https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http)
