### ISSUE TITLE
misleading statement about "JSON representation" 

### ISSUE THREAD

**Issue by xtofs** [microsoftgraph/microsoft-graph-docs#6976]
under Request body it states "supply a JSON representation" but in the example it shows an odata reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89df20ef-614f-8360-004d-d7e53691fdf6
* Version Independent ID: ed0f3e90-2388-aaf8-9a1c-6274826ec56e
* Content: [Add a member - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/administrativeunit-post-members?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/administrativeunit-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/administrativeunit-post-members.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Removed the term JSON representation.
