### ISSUE TITLE
All recurring accessReview objects are returned

### ISSUE THREAD

**Issue by a-bartkus** [microsoftgraph/microsoft-graph-docs#6988]
Page states that:

> If any of the access reviews that match the filter is a recurring access review, one accessReview object will be returned to represent each recurring series as a whole. 

This part is not working and all recurring accessReview objects are returned. Is there any way to make this endpoint return a single object per Review?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d56f62-91d1-6e41-3d8e-c167c2d2d512
* Version Independent ID: af9347f9-6471-3066-3dd7-9c2cfb1f70ec
* Content: [List accessReviews - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/accessreview-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accessreview-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by a-bartkus** [comment]
@markwahl-msft , is there a way to only retrieve single instance per recurring Access Review in a query? some additional filters maybe?

**Comment by markwahl-msft** [comment]
Thanks for the feedback, we will update the documentation. I am not aware of a filter expression that will exclude the instances of a recurring review, instead, it would be necessary to retrieve the accessReview to obtain the settings.
