### ISSUE TITLE
Topic should explain which properties a user can change for themselves

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/microsoft-graph-docs#6991]
Only a very small subset of properties on the user object are writable by a non-admin user. A user can update their own user object, but only change the properties listed in https://docs.microsoft.com/graph/permissions-reference?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#remarks-26

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@jasonjoh  - Thank you for the suggestion. I will relay it to the engineering team and discuss with v-team. Closing the issue.
