### ISSUE TITLE
Remove User From GrantedTo

### ISSUE THREAD

**Issue by mhagesfeld** [microsoftgraph/microsoft-graph-docs#7005]
We are utilizing Graph API to add/remove external users from folder access in OneDrive. We are able to add the users using the Invite call, giving them access to the folder via the link. However, we also need to remove these permissions/rescind the invitation. I tried running the Permissions Update after removing the user from the GrantedToIdentities, but received the error, "The type oneDrive.PermissionEntitySet does not support HTTP PATCH method." I also tried re-inviting the user with no access - no dice. Any ideass would be welcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b838ab-b9f4-0034-0872-640261903f22
* Version Independent ID: ff66bb53-edac-dc88-db0f-ba4447ec6e4d
* Content: [Remove access to an item - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/permission-delete?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/permission-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/permission-delete.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FredTheDane** [comment]
We are very eager to hear about this change too. At some point sharing functionality was changed such that all external invites to a document with a given permission level (read/write) were combined into one, instead of several invites if you chose to invite people individually.

Not being able to take away people from the GrantedToIdentities, and instead having to resort to removing the invite entirely, is not ideal 🚀

**Comment by kryptorado** [comment]
What's the status on this? I also need to be able to remove permissions per user, not all at once.

**Comment by kush316** [comment]
I was also in same boat where we have requirement to remove **individual** external user from the shared link without changing or disturbing underlying security inheritance and previously shared link. 
But unfortunately Graph didn't help, for external user its all or nothing.

But wait a second, when one door closes, God opens another, here it is Rest API.

As SPO UI provides removing individual external user, thought of having a fiddler trace and see what's going on in the background.
Luckily, found below POST request to remove individual external user from shared link without disturbing anything else.

**{Site-Url}/_api/web/Lists(@a1)/GetItemById(@a2)/ShareLink?@a1=%27%7BB221E1C8%2DD39C%2D4908%2D9B34%2D94828114169D%7D%27&@a2=%2734%27**

Body :
**{"request":{"createLink":true,"settings":{"linkKind":6,"expiration":null,"role":2,"restrictShareMembership":true,"shareId":"f4c15a70-464d-4656-9632-a967d009f4c0","scope":2,"inviteesToRemove":{"results":[{"id":-1,"loginName":null,"name":"sachin@contoso.com","isExternal":true,"principalType":0,"email":"sachin@contoso.com"}]}},"emailData":{"body":""}}}**

I have tested this now have a working solution in combination of Graph API to add external user and Rest API for removing them.

Hope that helps!!

Thanks,
Sachin Vashishth

**Comment by FredTheDane** [comment]
> 
> 
> I was also in same boat where we have requirement to remove **individual** external user from the shared link without changing or disturbing underlying security inheritance and previously shared link.
> But unfortunately Graph didn't help, for external user its all or nothing.
> 
> But wait a second, when one door closes, God opens another, here it is Rest API.
> 
> As SPO UI provides removing individual external user, thought of having a fiddler trace and see what's going on in the background.
> Luckily, found below POST request to remove individual external user from shared link without disturbing anything else.
> 
> **{Site-Url}/_api/web/Lists(@A1)/GetItemById(@a2)/ShareLink?@A1=%27%7BB221E1C8%2DD39C%2D4908%2D9B34%2D94828114169D%7D%27&@a2=%2734%27**
> 
> Body :
> **{"request":{"createLink":true,"settings":{"linkKind":6,"expiration":null,"role":2,"restrictShareMembership":true,"shareId":"f4c15a70-464d-4656-9632-a967d009f4c0","scope":2,"inviteesToRemove":{"results":[{"id":-1,"loginName":null,"name":"[sachin@contoso.com](mailto:sachin@contoso.com)","isExternal":true,"principalType":0,"email":"[sachin@contoso.com](mailto:sachin@contoso.com)"}]}},"emailData":{"body":""}}}**
> 
> I have tested this now have a working solution in combination of Graph API to add external user and Rest API for removing them.
> 
> Hope that helps!!
> 
> Thanks,
> Sachin Vashishth

I suppose. I had a look at this type of solution way back when. My only concern is that this is not a part of any API description and would not be what I would consider stable enough to push to production code.

I do appreciate your suggestion 🚀

**Comment by kush316** [comment]
Yes thats a valid risk, but seems MS has actively working on this and they have released beta version Graph endpoint to remove external recipient from the shared link.
