### ISSUE TITLE
403 error when extending eligible rbacs

### ISSUE THREAD

**Issue by ChristoferLee** [microsoftgraph/microsoft-graph-docs#7007]
I'm trying to create an automation account that will automatically extend all PIM eligible RBACs.  It's obtaining the access token properly but when i submit the POST to  https://graph.microsoft.com/beta/privilegedAccess/azureResources/roleAssignmentRequests I get an "UnauthorizedAccessException" saying "Attempted to perform an unauthorized operation".  The app registration has Application permissions on https://graph.microsoft.com/PrivilegedAccess.ReadWrite.AzureResources which should allow this to function but its denying my request.  Is there anything else I should look into?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c8925b-bf52-c385-b2f0-cace73234560
* Version Independent ID: 31800dc3-4297-831e-3d9e-688e444d8fd7
* Content: [governanceRoleAssignmentRequest resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/governanceroleassignmentrequest?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/governanceroleassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/governanceroleassignmentrequest.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @wn9237
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by shauliu** [comment]
Hello, currently the PIM API only supports application calls for read actions. If you are trying to do write, you will need to use a user account with the correct assignment on each of the resources. We are planning to support application calls later this year. You can also check out our PowerShell commands which are based on the graph api if writing a script with a logged in user would be easier for your scenario: https://docs.microsoft.com/en-us/powershell/module/azuread/?view=azureadps-2.0-preview#privileged_role_management
