### ISSUE TITLE
Adaptive cards with chat

### ISSUE THREAD

**Issue by AnkitsCode** [microsoftgraph/microsoft-graph-docs#7009]
Hey in short, I was wondering if we can send Adaptive cards via one to one chat. I have successfully send text/html messages using this API. I have also successfully created Adaptive cards and have been able to send it using BOT framework. But when I am trying to add an Adaptive card attachment to  this message I am getting a bad request error? Am I making a mistake or is this feature not available? This is the body (note the json without attachment works just fine).
 {"body":{"content":"Hi","contentType":"text"},"attachments":[{"contentType":"application/vnd.microsoft.card.adaptive","contentUrl":null,"content":{"type":"AdaptiveCard","version":"1.0","body":[{"type":"TextBlock","size":"large","weight":"bolder","text":"Who will be the key stakeholder?"},{"type":"Image","url":"https://planyourmeetings.com/wp-content/uploads/2016/07/stakeholders2.jpg"},{"type":"Input.ChoiceSet","style":"compact","isMultiSelect":true,"choices":[{"title":"Patients","value":"1"},{"title":"Healthcare professionals","value":"2"},{"title":"Payers","value":"3"},{"title":"Employees","value":"4"},{"title":"Suppliers","value":"5"},{"title":"Others","value":"6"}]}],"actions":[{"type":"Action.Submit","id":"StakeHolders","title":"Submit"}]},"name":null,"thumbnailUrl":null}]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 456c26fc-a47b-9f84-9d55-68cb48aad3fc
* Version Independent ID: 27b8eca1-ad6a-2881-a029-8d392c470b78
* Content: [Create chatMessage - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/chat-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chat-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aarushi-mittal** [comment]
Hello @AnkitsCode ,
were you able to achieve this?

Regards,
Aarushi

**Comment by michaelstiben** [comment]
Hello @AnkitsCode,

I have the same issue here, Did you find the solution?

thanks

**Comment by Hassaf17** [comment]
I was having a similar problem but was able to get around it (slightly). Using the last example in this post: https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http

I got it working by sending a post request to url: `chats/${chatId}/messages

with this body:

body: {
        "body": {
          "contentType": "html",
          "content": "<attachment id=\"04b151bb-2f88-4f5b-9615-30b2a59d9adf\"></attachment>"
        },
        "attachments":[{
          "id": "04b151bb-2f88-4f5b-9615-30b2a59d9adf",
          "contentType": "application/vnd.microsoft.card.adaptive",
          "content": JSON.stringify(card.attachments[0].content)
        }]
      }

I just kept using this random guid i generated for all my tests and it seemed to work, but there's an annoying white space above the card that gets sent that i can't get rid of, still hoping for a better solution than this.

**Comment by v-chetsh** [comment]
@AnkitsCode -  On 1:1 chat, you can send only messages not attachments using [this API](https://docs.microsoft.com/en-us/graph/api/chat-post-messages?view=graph-rest-beta&tabs=http#request)

If you check for chatMessage resource type properties, it is clearly mentioned that **"Attachments are currently read-only – sending attachments is not supported."**

[Reference link](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta#properties)
