### ISSUE TITLE
Revoke Permissions

### ISSUE THREAD

**Issue by ArneLudwig** [microsoftgraph/microsoft-graph-docs#7011]
How can I revoke permissions on the Microsoft Graph? Once permissions are granted they are not selectable anymore to be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
To revoke admin consent on permissions for an application that you own, go to the app registration in the Azure Portal -> API Permissions, then select the three dots at the right of the permission and revoke consent/remove the permission.

To revoke consent that you have granted as a user, go to https://myapplications.microsoft.com/, then right click the app of interest and select "Manage your application" (or click the three dots in top right, then select "Manage your application"). If the app has user-consented permissions, you will see a "Revoke Permissions" link on the right side of the Permissions tab in the app configuration screen.
