### ISSUE TITLE
Incomplete Delegated Permissions List

### ISSUE THREAD

**Issue by jacobwbutler** [microsoftgraph/microsoft-graph-docs#7018]
Why is Application.ReadWrite.All not listed as a valid delegated permission to perform service principal updates? See https://docs.microsoft.com/en-us/graph/permissions-reference#application-resource-permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68153a69-a97b-8ee1-dfbf-0769d10e8f5e
* Version Independent ID: a7dc4262-533e-b866-e2c1-0663e7090dcb
* Content: [Update serviceprincipal - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/serviceprincipal-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
this page needs an author from identity team assigned to it. @davidmu1 do you know who owns this?

**Comment by davidmu1** [comment]
The following is defined in the page:

Delegated (work or school account) | Application.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All

If you are referring to Delegated (personal Microsoft account), very few APIs have permissions for this type of account.

No change identified for the page. Closing the issue.
