### ISSUE TITLE
API access to free tier

### ISSUE THREAD

**Issue by vbosnjak** [microsoftgraph/microsoft-graph-docs#7023]
When creating an integration with MS Teams using Graph API, is it possible to authenticate on the Graph API even though the users do not have "real" accounts (Office365 or Azure)?
More precisely, if I create a conversational bot that uses the Graph API (instead of the SDK) can it be used by users who use only free tier of MS Teams?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5463d788-8e29-ca0a-5490-93506ff1ec80
* Version Independent ID: 1e7ca228-0b9f-beb1-d61f-7f1fdff50008
* Content: [Use the Microsoft Graph API to work with Microsoft Teams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teams-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
It should be possible if you are using application permission flow: [Get access without a user](https://docs.microsoft.com/en-us/graph/auth-v2-service?context=graph%2Fapi%2F1.0&view=graph-rest-1.0).

Could you please share some more details like what API you are trying to use?
