### ISSUE TITLE
mention returns with conversationIdentityType OData type

### ISSUE THREAD

**Issue by kenakamu** [microsoftgraph/microsoft-graph-docs#7038]
When I mention "Team" or "Channel" in message, it returns with OData type information. As a result, when I load data into Power BI via OData connector, it fails and below error is shown.

"DataSource.Error: OData: A type named 'Microsoft.Teams.GraphSvc.conversationIdentityType' could not be resolved by the model. When a model is available, each type name must resolve to a valid type"

I am not sure if this is expected behavior or not but other data seems not returned with odata type

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by smuckwell** [comment]
I am trying to create visualizations in Power BI for engagement with our Teams and the OData feed is giving me the same issues.

**Comment by nkramer** [comment]
I'll be honest, I'm not sure what to do with this. As far as I know our odata annotations are correct, I have no idea what Power BI expects.
