### ISSUE TITLE
.Filter("ProjectNumber eq 'New'") errors as Invalid filter

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/microsoft-graph-docs#7040]
I tried the .Filter option on a query on List items That have a field "ProjectNumber" and some items have  ProjectNumber ="New"
So the code 
```
var items = await nGraphClient.Sites[site.Id].Lists[list.Id].Items.Request(queryOptions)
                        .Filter("ProjectNumber eq 'New'")
                        .GetAsync();
``` 
Shows an error:
```
System.Private.CoreLib: Exception while executing function: HandleQueue. Microsoft.Graph.Core: Code: BadRequest
[2/8/2020 3:36:55 PM] Executed 'HandleQueue' (Failed, Id=7d1aa947-546b-4f32-9a24-454b42291266)
[2/8/2020 3:36:55 PM] Message: Invalid filter clause
[2/8/2020 3:36:55 PM] System.Private.CoreLib: Exception while executing function: HandleQueue. Microsoft.Graph.Core: Code: BadRequest
[2/8/2020 3:36:55 PM] Inner error:
[2/8/2020 3:36:55 PM] Message: **Invalid filter clause** 
```
I also tried based on same page,
```
var queryOptions = new List<QueryOption>() {
new QueryOption("ProjectNumber", "New")};
```
But that returned all the items unfiltered.
What is the right filter syntax?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9eead3-fd14-629f-dd6d-55e0c51d74ff
* Version Independent ID: cc096658-8f79-45c2-9d42-69e4fe9a3a49
* Content: [Make API calls using the Microsoft Graph SDKs - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS)
* Content Source: [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/create-requests.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
My guess is that the service does not enable it it, but if it is possible I would try this,

```
var items = await nGraphClient.Sites[site.Id].Lists[list.Id].Items.Request(queryOptions).Expand("fields")
                        .Filter("fields/ProjectNumber eq 'New'")
                        .GetAsync();
```
@JeremyKelley might know if this is possible.

**Comment by Ofer-Gal** [comment]
Tried this but got:
```
Microsoft.Graph.ServiceException: 'Code: invalidRequest
Message: Field 'ProjectNumber' cannot be referenced in filter or orderby as it is not indexed. 
Provide the 'Prefer: HonorNonIndexedQueriesWarningMayFailRandomly' header to allow this, 
but be warned that such queries may fail on large lists.
```
How do you set headers in GraphServiceClient? 
Also, it is impossible to make all the fields to filter by indexed, that will make them unique. no?

**Comment by darrelmiller** [comment]
Hi @Ofer-Gal 

I'm glad we were able to find the right query syntax and you found out how to send the custom header.  I'm afraid, I am not familiar enough with this particular service to be able to explain why the "title" field is not showing.  Is the filter condition actually doing the filtering?  Is title a custom field you created?  What data type is it?

**Comment by Ofer-Gal** [comment]
Each SharePoint list and library has a default text field Named "Title". 
You can only change it's Display name, not its name. and you cannot remove it from the List or library. 
My filter was on another field and it worked fine. Thanks again.
I also saw there is a .Select(..) option but using the same list as in the graph explorer,
````
https://graph.microsoft.com/v1.0/sites/{siteID}/lists/{ListID}/items?expand=fields(select=ID,Author,Title,DocumentName)
``` 
Works fine
But with the SDK in C# :
```
var items = await graphClient.Sites[{siteID}].Lists[{ListID}].Items.Request().Expand("fields").Select("ID,Author,Title,DocumentName").GetAsync();
```
Show error Code: BadRequest Message: Parsing Select and Expand failed.
Is there a different syntax to the "Select(..)" ?

**Comment by darrelmiller** [comment]
Currently the SDK does not support nested selects.  The last example you show should work.  However, maybe you could try this:
```
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var queryOptions = new List<QueryOption>()
{
	new QueryOption("expand", "fields(select=ID,Author,Title,DocumentName)")
};

var items = await graphClient.Sites["{siteID}"].Lists["{ListID}"].Items
	.Request( queryOptions )
	.GetAsync();
```
I generated this code snippet using the URL you provided and the new Graph Explorer 
 https://developer.microsoft.com/en-us/graph/graph-explorer/preview

![image](https://user-images.githubusercontent.com/447694/74109176-2f858300-4b4f-11ea-936d-878dd089410f.png)

**Comment by Ofer-Gal** [comment]
https://developer.microsoft.com/en-us/graph/graph-explorer/preview is way cooler :-)
Thanks
