### ISSUE TITLE
List shared task folders

### ISSUE THREAD

**Issue by weeezes** [microsoftgraph/microsoft-graph-docs#7041]
Looks like listing task folders through this `https://graph.microsoft.com/beta/me/outlook/taskFolders` endpoint doesn't include task folders that have been shared to you, even when implicit flow scopes contain `tasks.readwrite.shared` (also set in the API permissions). Is there a way to get the shared resources currently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4c7e244-509d-c4fa-e1c8-ff4dabeebf7b
* Version Independent ID: bd63ae54-0f85-a512-2435-8f8f2ed0917d
* Content: [List taskFolders - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/outlookuser-list-taskfolders?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/outlookuser-list-taskfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/outlookuser-list-taskfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Manav-Seth** [comment]
I also have the same question? Any way to get shared task folders through the ToDo APIs?

**Comment by Manav-Seth** [comment]
Any one paying attention to these comments?

**Comment by Manav-Seth** [comment]
@angelgolfer-ms any update on this?

**Comment by angelgolfer-ms** [comment]
Sorry, identified a product side member, @mashriv , to help.

**Comment by weeezes** [comment]
Any news @mashriv :)?

**Comment by mashriv** [comment]
Sorry for delay in response. The current graph API's doesn't support shared folders. We are working on new set of APIs that will bring in support for shared folders.

**Comment by weeezes** [comment]
Cool, thanks for the response :).

**Comment by Manav-Seth** [comment]
thank you @mashriv - any way to get notified when this capability is added to graph APIs? Thanks.

**Comment by mashriv** [comment]
@weeezes Tasks Graph API documentation would be modified.
