### ISSUE TITLE
Filtering currently not possible in C# for "lastmodifieddatetime" & "createddaytime" when using "CalendarView"?!

### ISSUE THREAD

**Issue by MVIF** [microsoftgraph/microsoft-graph-docs#7045]
Works fine in the Graph Explorer; always returns no results for both via C#-API.

(start- endDateTime in the QueryOptions are O.K.)
Using the syntax: ...Filter("createddatetime gt 2020-01-01T07:00:00Z")...

Or am I missing a required subtle difference in the DateTime format in C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c86813-3128-8d76-1853-fde56fb17349
* Version Independent ID: da447d8b-6f50-027e-6d6f-46636eb7294b
* Content: [List events - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/user-list-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-events.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MVIF** [comment]
Oh well, redundant me thinks ... sorry:
https://github.com/microsoftgraph/microsoft-graph-docs/issues/4000

**Comment by Harini84** [comment]
@darrelmiller 
Kindly help with the above query. Filtering works fine in MS-Graph API for calendarView but not in C#.

**Comment by lramosvea** [comment]
Closing as this seems to be fixed. Please feel to reopen otherwise. Thanks.
