### ISSUE TITLE
Wrong maximum limit for the getSchedule endpoint

### ISSUE THREAD

**Issue by Olnexia** [microsoftgraph/microsoft-graph-docs#7047]
The documentation states:

> getSchedule can support looking up free/busy information for up to **20** entities at once. This limit applies to the number of users identified individually or as members of a distribution list, and to the number of resources as well.

But looks like it is possible to look up free/busy information for up to 100 entities. This is the error I received after sending 101 addresses.

`{
"error": {
    "code": "ErrorMailboxDataArrayTooBig",
    "message": "There are too many target users in the EmailAddress array. The allowed size = 100; the actual size = 101.",
    "innerError": {
      "request-id": "81c1a558-aa52-4c7e-a0bf-0f0a11ec6ec1",
      "date": "2020-02-10T17:21:15"
    }
  }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6748e9-6e15-db5e-f85f-79dbe8171e9b
* Version Independent ID: a30e4438-c54b-643f-5573-c904ace73e70
* Content: [Get free/busy schedule of users and resources - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-free-busy-schedule#feedback)
* Content Source: [concepts/outlook-get-free-busy-schedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-get-free-busy-schedule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by crossjoin** [comment]
The same applies to the documented time period.

The documentation states that the limit is 42 days. This works, but the API returns the following error when requesting more than 62 days:

> The requested time duration specified for FreeBusyViewOptions.TimeWindow is too long. The **allowed limit = 62 days**; the actual limit...

**Comment by isvargasmsft** [comment]
Checking with product team.

**Comment by isvargasmsft** [comment]
By design according to product team.
