### ISSUE TITLE
Is `oid` decoded from access token the same as `id` get from /me of microsoft graph api?

### ISSUE THREAD

**Issue by linhdangduy** [microsoftgraph/microsoft-graph-docs#7051]
[About `oid`](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims) decoded from access token/id token of azureAD:
&gt; .... *This ID uniquely identifies the user across applications - two different applications signing in the same user will receive the same value in the oid claim.* ... *Note that if a single user exists in multiple tenants, the user will contain a different object ID in each tenant - they're considered different accounts, even though the user logs into each account with the same credentials.* ...

[About `id`](https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0#common-properties) get from `/me` of microsoft graph api:
&gt; The unique identifier for the user.

Previous, one of my application uses `oid` as the id of azure user.
Now, I want to use `id` of graph api for the same purpose. So:
- Are these two ids ('oid' and 'id') is the same?
- Does `id` get from `/me` is different for `each tenant`, as `oid`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bae97ef5-d7e5-3934-6323-1bcff216f4fb
* Version Independent ID: 1ed620e1-cb79-dda3-2c18-30791ec9e15a
* Content: [Working with users in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/users?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The id is unique across tenants. No change identified for this page. Closing the issue.
