### ISSUE TITLE
When will Entitlement Management API go Public

### ISSUE THREAD

**Issue by mylabonline** [microsoftgraph/microsoft-graph-docs#7052]
Hello,

Since Entitlement management is GA, when will this APIs move from beta into 1.0 of the Graph API? We have created some automation around using entitlement management, and since its still BETA changes keep breaking our automation. 

this morning we had to change the @odata.type for allowed requesters to @odata.type=#Microsoft.IGAELM.EC.FrontEnd.ExternalModel.groupMembers from #microsoft.graph.groupMembers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c79ddbb-ee95-af3a-fcf6-7eea6d203841
* Version Independent ID: 128313eb-fe9b-0c22-e3bb-f7eead5e9ce8
* Content: [Working with the Azure AD entitlement management API - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/entitlementmanagement-root.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
@mylabonline could you email me directly about the API you're using where you're seeing this behavior?  Thanks, mwahl at microsoft.com

**Comment by matttrakker** [comment]
@mylabonline , @markwahl-msft I do get an unkownerror on entitlementmanagement apis(list accessPackages, get accessPackage...)

Is there any news on that GA appointment?
I'd love to use the api for automated subscription setup 😄

**Comment by matttrakker** [comment]
Dear @markwahl-msft is there any update on the ga?

I'm trying to use the entitlement management as well and always get the "UnknownError" for list access packages, get,... etc... V1.0 for other is working so I guess docs is not up-to-date, could this be?

I'd love to automate the subscription generation including the setup of identity governance 😄

**Comment by markwahl-msft** [comment]
I'm not sure why you're getting an Unknown error.  I'd recommend opening a support case so we can diagnose what is going on in your tenant directly.  We have not yet announced a date for these APIs going into 1.0 path as we have a few more changes we'd like to get feedback on in beta (connected organizations for example.)  Once we have brought this to the 1.0 path then they'll be an annoucement.
