### ISSUE TITLE
Should Document Whether Collection of Sign-Ins Are Sorted According to Creation Date and Time or Not

### ISSUE THREAD

**Issue by hasahmed** [microsoftgraph/microsoft-graph-docs#7057]
You may think "Well it is clear from the result". My answer to that is that it should be documented anyway so we can know what behavior to depend on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/signin-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dhanyahk
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hasahmed** [comment]
Looks like the collection is returned descending according to the CreatedDateTime property. Is this functionality we can depend on? Who knows.

**Comment by JeremyTBradshaw** [comment]
Hello @hasahmed @khotz , I too have this same question.  I'm wondering if either of you have found out the answer through other channels since the last update here?

**Comment by davidmu1** [comment]
Thank you for your feedback. Clarified that the response is listed in descending order based on createdDateTime. Closing the issue.
