### ISSUE TITLE
Analytics.Read delegated permission has unclear scope

### ISSUE THREAD

**Issue by mdb-wg** [microsoftgraph/microsoft-graph-docs#7058]
The stated scope is: "Allows the app to read user activities statistics without a signed-in user." Wouldn't this be impossible without impersonation, which is not implemented for msgraph? Application permissions can enable actions without a signed in user, but I am unsure if delegated permissions can. 

Looking at the other permissions, only Domain.ReadWrite.All also has a delegated permission that allows action without a signed in user. Can we please clarify this on both accounts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
Thanks for noticing this. The description for Analytics is incorrect. I've submitted a PR with the correct info: https://github.com/microsoftgraph/microsoft-graph-docs/pull/7137

I'll also follow up on Domain.
