### ISSUE TITLE
Error while updating the password profile

### ISSUE THREAD

**Issue by mustalp** [microsoftgraph/microsoft-graph-docs#7060]
We have been trying to hit an update user api for updating the password profile of a user. We tried to use multiple approaches.
1) Giving the app required delegated and application permissions as mentioned in the document above. But still we are getting an error "Insufficient privileges to complete the operation." Do we have to add any extra permissions to the Application permissions to make this approach work?
2) While trying to hit the api from app by giving user's username and password who is a Global Administrator in the body then we are able to reset password of the user. But using the admin's username and password does not lead to any security constraints?

What is the preferred way of reset/change password of user using microsoft graph apis is it the delegation way or the application permission way? We have gone through couple of blogs like https://gcits.com/knowledge-base/automate-api-calls-microsoft-graph-using-powershell-azure-active-directory-applications/, is there anyway to provide consent to application to enable change/reset password via application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by amanmcse** [comment]
@mustalp  Please try the steps I shared in https://docs.microsoft.com/answers/questions/9024/error-while-updating-the-password-profile.html.

**Comment by inner** [comment]
I have been able to update the password for a local user account via Graph API C# client (for one of my testing accounts), however, after update, I cannot login any more. I am using custom policy to sign-in. In the user sign-ins logs in the Azure portal, I can see it says:

Status: Interrupted
Sign-in error code: 50055
Failure reason: Invalid password, entered expired password.

I have also tried to reset password via the Azure portal and tried the temporary password - no luck. What am I doing wrong here?

**Comment by VadzimPapko** [comment]
Hi @inner have you resolved the issue with login after password updating? Seems we also have the same issue right now.

**Comment by inner** [comment]
@VadzimPapko not via the Graph API unfortunately. Instead, I implemented the password reset via the UI (password reset custom policy).

**Comment by davidmu1** [comment]
In the user update page is this note: When updating the passwordProfile property, the following permission is required: Directory.AccessAsUser.All. Here is the passwordProfile resource: https://docs.microsoft.com/en-us/graph/api/resources/passwordprofile?view=graph-rest-1.0. Closing the issue. Please reopen if needed.
