### ISSUE TITLE
GetByIds expects GUIDs instead of strings

### ISSUE THREAD

**Issue by jaumemilian** [microsoftgraph/microsoft-graph-docs#7063]
When calling the GetByIds endpoint with non GUID values, it throws a 500 error exception.
Regarding the documenation, it seems that the endpoint expects a list of strings, but if you send an string that is not a real GUID, the requests produces a 500 error like this:

{
    "error": {
        "code": "Request_BadRequest",
        "message": "Invalid GUID specified.",
        "innerError": {
            "request-id": "3c1c8c2d-8153-4201-bbc5-725df4a834bc",
            "date": "2020-02-12T14:33:13"
        }
    }
}

It this is the expected, behavior, would be nice to upgrade the documentation, and also the client libraries that expect as a parameter an string array

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 652f070a-a126-9add-13db-e35250b8b86c
* Version Independent ID: d256be5b-8466-385f-32a4-2d9fd9a89886
* Content: [Get directory objects from a list of ids - Microsoft Graph v1.0](https://docs.microsoft.com/en-Us/graph/api/directoryobject-getbyids?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/directoryobject-getbyids.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryobject-getbyids.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@jaumemilian - Can you provide an example of what you are trying to do? All identifiers of directory objects are GUIDS, so I'm not sure why you would want to be using something other then a GUID. The request in this case is treating the GUIDs as strings in the collection.

**Comment by jaumemilian** [comment]
Hi @davidmu1, 

Then I guess that the documentation should be updated to indicate that the accepted **id** body parameter is a **Guid collection** instead of a **String collection**

From the documentation

> 

Parameter | Type | Description
-- | -- | --
ids | **String collection** | A collection of IDs for which to return objects. You can specify up to 1000 IDs.

> 

From the above sentence, I won't never expect to have a 500 error exception when passing a valid String collection (non Guid one).

If this is considered, it would be also nice to upgrade the Graph client nuget packages in order to accept properly the List<Guid> instead of a List<string>

Kind regards,
Jaume

**Comment by keylimesoda** [comment]
1.  This should be a 400 error.  We've filed an internal bug accordingly.
2.  We believe it's good design for ids to remain loosely typed (string instead of GUID type).  However, we also want someone to be able to differentiate between a malformed submission and a missing ID, so we will retain the "invalid GUID" error message.  To help clear up, I am submitting a pull request to add the GUID expectation to the Description field in our documentation so the error message has better context.

**Comment by keylimesoda** [comment]
I think with the merge this issue is closed.
