### ISSUE TITLE
Will applications ever be supported for listing threads and conversation?

### ISSUE THREAD

**Issue by rwspielman** [microsoftgraph/microsoft-graph-docs#7067]
Will applications ever be supported for listing threads and conversations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 763190f2-e1a2-a004-4aa1-0072aaeea6df
* Version Independent ID: 368cc5b6-b2a7-a100-225a-a6cde81feba7
* Content: [List threads - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-threads?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-threads.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-threads.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Unfortunately, any future functionality can't be discussed in this forum. Only corrections to the documentation should be discussed here. No change identified for the page. Closing the issue.
