### ISSUE TITLE
Deleted group still showing in Teams client

### ISSUE THREAD

**Issue by jdoern96** [microsoftgraph/microsoft-graph-docs#7070]
When deleting a group using DELETE https://graph.microsoft.com/v1.0/groups/{id} the associated team is still showing in the user's teams client allowing them to send messages. Is there something else that also needs to be deleted to remove from Teams client as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b88eb2b5-8b17-c22c-014e-9cdd6a9d6a7b
* Version Independent ID: 51e6d4e6-833e-2ecc-d5d6-f68d349abc75
* Content: [Delete group - Microsoft Graph API - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Eickhel** [comment]
I've just tested with the same result. I receive the expected "204 - No Content" response but the Teams client still shows the Team I've just deleted.

**Comment by vltspr** [comment]
Yes, juste tried it, teams aren't actually deleted.

**Comment by vltspr** [comment]
https://techcommunity.microsoft.com/t5/teams-developer/deleting-a-team-via-graph-api/m-p/729152
There might be a delay between deleting the group and the team being deleted.

**Comment by yyuank** [comment]
Deleting the group should delete the Team as well. There's a delay between the source where Office 365 groups are mastered and Teams. It's a system limitation.

**Comment by oshihirii** [comment]
@yyuank - can you please tell me if deleting the `group` via the following code should delete the 'Team Site' that is created on group creation?  

I can see in [the link posted by vltspr above](https://techcommunity.microsoft.com/t5/teams-developer/deleting-a-team-via-graph-api/m-p/729152) that it seems the Team will eventually be deleted after a delay, is this also true with the related 'Team Site'?  

```js
var path = "/groups/group-id"; 

var response = await client.api(path).delete();
```

Currently, it seems it is only deleting:

- Group  
- Outlook Group

It was created with this:

```js
var path = "/groups"; 
            var group = {
              description: "text",
              displayName: "display_name_here",
              groupTypes: ["Unified"],
              mailEnabled: true,
              mailNickname: "display_name_here",
              securityEnabled: false,
              visibility: "Hiddenmembership",
              "owners@odata.bind": [
                "https://graph.microsoft.com/v1.0/users/user-id-here"
              ],
                "members@odata.bind": [
                    "https://graph.microsoft.com/v1.0/users/user-id-here"
              ]
            };

            var response = await client.api(path).post(group);
```

Thank you.
