### ISSUE TITLE
No method match route template error code

### ISSUE THREAD

**Issue by phuong-vo** [microsoftgraph/microsoft-graph-docs#7073]
Hello,
I used Microsoft Graph Explorer to POST https://graph.microsoft.com/v1.0/users/{usersId}/managedDevices/{managedDeviceId}/shutDown
but I got the below error. Could anyone point me out how to fix this issue?

> {
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/entityset/key/navigation/key/action with http verb GET for request /DeviceFE/StatelessDeviceFEService/users('user@mydomain.onmicrosoft.com')/managedDevices('c86602ce-c077-4a77-a45e-00b2b8aca501')/microsoft.management.services.api.shutDown.",
        "innerError": {
            "request-id": "7da82ee9-ccee-4849-ac6c-9c71008e9d15",
            "date": "2020-02-13T00:53:44"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6ffc4d2-7b10-45eb-57c7-088141d947f6
* Version Independent ID: 9f522545-f39a-e3ea-19ee-a030645024b3
* Content: [shutDown action - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-shutdown?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-shutdown.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-shutdown.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by damienvanrobaeys** [comment]
I tried to use the same device action using method POST as mentioned in the API doc.
However I got the below issue:
An error has occurred - Operation ID (for customer support)

I can use the rebootnow action without any issue.

**Comment by triplanedave** [comment]
This is only supported for iOS devices that are operating in Supervised mode.
