### ISSUE TITLE
getRoleScopeTagsById

### ISSUE THREAD

**Issue by GillesBures** [microsoftgraph/microsoft-graph-docs#7079]
[Enter feedback here]
I succeed to call getRoleScopeTagsById to get one scope  or roleScopeTags to get all scopes.
But how can I see group associated to scope ?
I Azure Portal, I am able to see (and add) groupes associated to Scope (Microsoft Intune/Intune roles - Scope (Tags))
How can I do throw graph ?

Regards
Gilles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb1e1566-a05f-26a7-efdf-4703115246aa
* Version Independent ID: 5e709d17-82cb-627c-7ba0-8aeb4181439d
* Content: [getRoleScopeTagsById action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-rbac-rolescopetag-getrolescopetagsbyid?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-rbac-rolescopetag-getrolescopetagsbyid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-rbac-rolescopetag-getrolescopetagsbyid.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by GillesT78** [comment]
Hello

Do you have a solution to assign group to scope tags using Powershell, as it is possible throw the portal ?

Regards
Gilles

**Comment by triplanedave** [comment]
You cannot assign groups to scope tags, or assign scope tags to groups.  Scope tags are associated with a role assignment.  That role assignment can have one or more scope groups.  So, if you view the role assignment, you can see which scope groups and scope tags are tied together.  So, you'd have to enumerate through the roles and their associated role assignments to see which groups are associated with the scope tags.
