### ISSUE TITLE
Example of getting events for a particular calendar

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#7081]
We should add a example of how to list events for a particular calendar, not just me/events. Would benefit of hten having code snippets here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c86813-3128-8d76-1853-fde56fb17349
* Version Independent ID: da447d8b-6f50-027e-6d6f-46636eb7294b
* Content: [List events - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-list-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-events.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Listing of events in a particular calendar is to be done through CalendarView construct:
https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-1.0&tabs=http
