### ISSUE TITLE
Incomplete Delegated Permissions List?

### ISSUE THREAD

**Issue by jacobwbutler** [microsoftgraph/microsoft-graph-docs#7086]
Why is Application.Read.All not considered a valid delegated permission to read oauth2permissiongrants? https://docs.microsoft.com/en-us/graph/permissions-reference#application-resource-permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04af25cc-8820-3a87-4d93-b4186b708f40
* Version Independent ID: a0b1691e-7e90-c800-fac4-0cfb08152c9c
* Content: [Get oAuth2Permissiongrant - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/oauth2permissiongrant-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/oauth2permissiongrant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/oauth2permissiongrant-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
