### ISSUE TITLE
InvitationParticipantInfo.EndpointType no longer exists

### ISSUE THREAD

**Issue by wimvanhouts** [microsoftgraph/microsoft-graph-docs#7090]
In the SDK, the EndpointType member is no longer available in the InvitationParticipantInfo, example needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 335dc162-8c2e-49dc-4419-9ef736ec8ba4
* Version Independent ID: b441332e-a653-e538-d9f0-c66739f9122a
* Content: [call: transfer - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/call-transfer.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by saraefa** [comment]
did you found any answer for this problem?

**Comment by wimvanhouts** [comment]
The problem was that the documentation is not in sync with the code. It has been a while, but, in general I use the .NET SDK to verify a sample and get the correct structure/properties that way... You can also just look inside the Java class definitions to know which property goes where...

**Comment by baywet** [comment]
Hi everyone,
Thanks for reaching out and thanks for your patience.
The SDK needed to be updated, and that enum has been added with version 1.8.0 and up. https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/models/generated/EndpointType.java
Closing
