### ISSUE TITLE
Deleted messages are unidentified

### ISSUE THREAD

**Issue by M1ch3lG4gn0n** [microsoftgraph/microsoft-graph-docs#7094]
The property deletedDateTime is always null.
The deleted property displayed in the JSON representation doesn't exist.
It seems that the only way to know is to check if the body content is an empty string.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f046b37e-8569-b617-4c9b-402342d4bef9
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessage.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by laujan** [comment]
Hi @M1ch3lG4gn0n. Thank for raising an issue in this repository. I would like to assist you. Can you please explain a bit more by briefly explaining when/how you encountered the issue? If you have a code snippet, please feel free to add it to your reply. Thanks again.
