### ISSUE TITLE
add openShiftChangeRequestId to the request

### ISSUE THREAD

**Issue by maheshp9** [microsoftgraph/microsoft-graph-docs#7101]
Request should be POST https://graph.microsoft.com/beta/teams/{id}/schedule/openShiftsChangeRequests/{openShiftChangeRequestId}/decline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b559c78a-0632-937d-93d9-1cb2beb0e7e8
* Version Independent ID: b43e6335-ea9e-847e-3092-d924718358e6
* Content: [openShiftChangeRequest: decline - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/openshiftchangerequest-decline?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/openshiftchangerequest-decline.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/openshiftchangerequest-decline.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by akumar39** [comment]
thanks @maheshp9 ! Created PR fix https://github.com/microsoftgraph/microsoft-graph-docs/pull/7102
