### ISSUE TITLE
Further information on how to access various elements such as sites using "fluent interface"

### ISSUE THREAD

**Issue by davyarris** [microsoftgraph/microsoft-graph-docs#7107]
In the opening paragraph of this page it mentions 
"There are two styles of client class: one uses a fluent interface to create the request (for example, client.Me.Manager) and the other accepts a path string (for example, api("/me/manager"))."
All code samples throughout the documentation show access to the path client.Me. No examples are given on how to access using this fluent style for Sites. Is this even possible? If so how?

BTW: I am using Typescript not c#
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9eead3-fd14-629f-dd6d-55e0c51d74ff
* Version Independent ID: cc096658-8f79-45c2-9d42-69e4fe9a3a49
* Content: [Make API calls using the Microsoft Graph SDKs - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-requests?view=graph-rest-1.0&tabs=CS#feedback)
* Content Source: [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/create-requests.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
In the reference documentation we include auto-generated snippets for many of the examples.  Here is one for Sites.
https://docs.microsoft.com/en-us/graph/api/site-get?view=graph-rest-1.0&tabs=csharp

Also, in our [Graph Explorer preview](https://developer.microsoft.com/en-us/graph/graph-explorer/preview) you can enter your own URL and we will generate corresponding code snippets.

Hopefully this answers your question.  If not please feel free to re-open the issue on the appropriate SDK repo in this GitHub organization.

**Comment by davyarris** [comment]
Hi Darrel,
Thanks for your hasty response.

The examples for javascript in the URL provided access a sites drives like this:
`client.api('/sites/{site-id}/drives').get()`.

This is equivelent to acccessing a MY drives like this:
`client.api('/me/drives').get()`

The above query could also be done using the fluent interface:
`client.Me.Drives.Request().GetAsync()`

I was asking if the "Fluent Interface" was available for sites in the same way as "Me" for example:
`client.Sites[id].Drives`
And if so where is this documented??

I hope this makes more sense now.

Thanks
D

**Comment by darrelmiller** [comment]
Ahh, I assumed you were trying to work in C#.  We do not yet have the "fluent interface" for Javascript.  We are planning to do it in 2020H1.  If you could upvote this [uservoice entry](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/36064216-microsoft-graph-javascript-typescript-sdks-shoul) that would be great.
