### ISSUE TITLE
How to get Custom fields from driveItems

### ISSUE THREAD

**Issue by janmuixidev** [microsoftgraph/microsoft-graph-docs#7111]
when I search for a drive item in /sites/{site-id}/lists/{list-id}/items/{item-id} I can use $expand=fields to retreive custom fields, but here I can't, there is another way to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmoreau** [comment]
Field expansion is not yet available in this API. You are correct that this is not consistent with the enumeration API. We are working on this.
