### ISSUE TITLE
How can I get selected properties of a driveItem like ?expand=fields on normal calls

### ISSUE THREAD

**Issue by janmuixidev** [microsoftgraph/microsoft-graph-docs#7112]
in other calls I can use ?expand=fields to get custom column values, how can I do it here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d55d194-da7b-7f76-4ef0-b6d84a3dccc0
* Version Independent ID: 9139b092-1446-2f30-7cdb-1b41474d9f41
* Content: [Use the Microsoft Search API to query data - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/search-api-overview.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmoreau** [comment]
fields expansion is not yet available in the search API. The reason is that not all fields can be retrieved in the index. We are working to open that functionality in our next release, at least to the fields available in the index.
