### ISSUE TITLE
Is there a rationale for not supporting application permissions?

### ISSUE THREAD

**Issue by MVIF** [microsoftgraph/microsoft-graph-docs#7113]
... or is it just not completed yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b7b26c-499c-6b30-96cd-04b6ac80fbc0
* Version Independent ID: 2e8b2a6a-961b-40d6-acf0-a096a3aec9a1
* Content: [Create schemaExtension - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/schemaextension-post-schemaextensions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Read schema extensions is possible with Application.Read.All.  Looking into why CRUD is not supported with Application.ReadWrite.All, but please feel free to ask for this on user voice.  THere's a PR pending with some related changes here:  #8665
