### ISSUE TITLE
Does a Group automatically get a plan anymore?

### ISSUE THREAD

**Issue by pconnell99** [microsoftgraph/microsoft-graph-docs#7114]
I was under the impression that a group created in the graph (Unified) gets a planner board - but this doesn't seem to be the case - can anybody confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1811bff-5920-affd-cddd-f10632fa7fc7
* Version Independent ID: 5db31163-7897-e632-2671-f3e380ed0889
* Content: [plannerPlan resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/plannerplan.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by oshihirii** [comment]
I also experience the same behaviour.

Creating a Group (depending on the settings), seems to create a Group, Outlook Group and Team Site, but not a Team or Plan.  

Creating a Team (after creating a Group) does not seem to automatically create a Plan either.  

So my understanding is that you must separately create a Group, Team and Plan.  

Create Group:   
https://docs.microsoft.com/en-us/graph/api/group-post-groups   

Create Plan (which is owned by a Group):    
https://docs.microsoft.com/en-us/graph/api/planner-post-plans  

Create Team (which is owned by a Group):    
https://docs.microsoft.com/en-us/graph/api/team-put-teams

**Comment by TarkanSevilmis** [comment]
Creation a group never created a plan automatically. Visiting a group in Planner UI created the plan for you. The functionality of the UI has been altered (e.g. we don't show groups as plans anymore, in other words you can't visit a group in Planner UI) with the capability of having more than one plan in a group.
