### ISSUE TITLE
Deleted member users don't appear in deltaLink response (when using deltatoken)

### ISSUE THREAD

**Issue by gd1212** [microsoftgraph/microsoft-graph-docs#7115]
Hello, deleted member users appear in the initial response when making the initial request using GET https://graph.microsoft.com/v1.0/groups/delta, but member users that are deleted after the initial response was received don't appear when making a deltaLink request (using a deltatoken). It would be nice if this could be fixed.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2e05dc1-af32-8d4c-5998-3a58a3de6341
* Version Independent ID: 298fcfff-52c3-a1a9-5fbe-a109ec6782d1
* Content: [Get incremental changes for groups - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-groups)
* Content Source: [concepts/delta-query-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-groups.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
closing in favor of existing #4498

**Comment by gd1212** [comment]
hello, #4498 is for another endpoint (https://graph.microsoft.com/v1.0/users/delta). Will a solution to it also fix this issue? If not, could you please re-open this issue too? Thanks.

**Comment by baywet** [comment]
Hi @gd1212
I went ahead and did some testing.
I do get the reason property. As this issue list is reserved for issues with the documentation, please go ahead and open a support case from your tenant. This will allows our support engineers to investigate why you are not getting the property.
