### ISSUE TITLE
Creating a recurring event throws a 500 error.

### ISSUE THREAD

**Issue by eduard-bitsea** [microsoftgraph/microsoft-graph-docs#7119]
Creating an single event works, but if the event is recurring, the server returns an Internal Server Error status code. See details in https://stackoverflow.com/questions/60228248/microsoft-graph-api-creating-recurring-event-returns-500.
How can I add a recurring event with the graph api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@eduard-bitsea , there's an article [Schedule recurring events](https://docs.microsoft.com/en-us/graph/outlook-schedule-recurring-events#daily) that describes the properties to set when creating a recurring event that occurs daily. As explained there, you should set the **interval** property to 1; do not set the daysOfWeek property in this case, as it would give you the error.

In the next day, PR #7130 will add an example to the [examples](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#example) section of the create event topic, to show creating a daily recurring event.
