### ISSUE TITLE
HTTP response code wrong

### ISSUE THREAD

**Issue by AirPett** [microsoftgraph/microsoft-graph-docs#7125]
The API returns a `200 OK` on a successful request, not `204 No Content` as the documentation states.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d02fd0-e339-4c9e-0d71-e01a987295ce
* Version Independent ID: 69e0148c-71c0-8632-ccd9-a42fd6c4b4f8
* Content: [sync action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-windowsautopilotsettings-sync?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-enrollment-windowsautopilotsettings-sync.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-windowsautopilotsettings-sync.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've logged a work item with our team to update the help content.
