### ISSUE TITLE
Wrong HTTP status code on not found

### ISSUE THREAD

**Issue by AirPett** [microsoftgraph/microsoft-graph-docs#7129]
For some reason the API returns a `200 OK` with any GUID as the `{importedWindowsAutopilotDeviceIdentityId}` no matter if a corresponding device exists. E.g. `https://graph.microsoft.com/beta/deviceManagement/importedWindowsAutopilotDeviceIdentities/e47da9e0-5661-43d2-a098-4eb05ec7f7be` where the GUID is from an online GUID generator, I get a `200 OK`.

I'd expect the API to properly return a `404 Not Found` if the resource being deleted doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4ff5412-c5d4-24d9-e067-19f320ee011e
* Version Independent ID: 4dfdcf2d-fe87-59a1-ab30-4e67434b3e50
* Content: [Delete importedWindowsAutopilotDeviceIdentity - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-importedwindowsautopilotdeviceidentity-delete?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-importedwindowsautopilotdeviceidentity-delete.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've created a bug for our team to take a look at why it's returning a 200 on non-existent devices.
