### ISSUE TITLE
There is a bug with Assignment orderHint, When I query the delta Link, it gives the same assignment multiple times for the same task with different OrderHint

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#7132]
[
    {
        "@odata.type": "#microsoft.graph.plannerTask",
        "@odata.etag": "blabla",
        "id": "FKvC****",
        "@odata.context": "https://tasks.office.com/taskapi/v2.0/$metadata#tasks/$entity",
        "assignments": {
            "25c9****": {
                "@odata.type": "#microsoft.graph.plannerAssignment",
                "orderHint": "8586195339990176753Pk"
            }
        }
    },
    {
        "@odata.type": "#microsoft.graph.plannerTask",
        "@odata.etag": "W/\"JzEtVGFzayAgQEBAQEBAQEBAQEBAQEVPRCc=\"",
        "id": "FKvC****",
        "@odata.context": "https://tasks.office.com/taskapi/v2.0/$metadata#tasks/$entity",
        "assignments": {
            "25c9****": {
                "@odata.type": "#microsoft.graph.plannerAssignment",
                "orderHint": "8586195339983078055PT"
            }
        }
    },
    {
        "@odata.type": "#microsoft.graph.plannerTask",
        "@odata.etag": "W/\"JzEtVGFzayAgQEBAQEBAQEBAQEBAQEVPSCc=\"",
        "id": "FKvC****",
        "@odata.context": "https://tasks.office.com/taskapi/v2.0/$metadata#tasks/$entity",
        "assignments": {
            "25c9****": {
                "@odata.type": "#microsoft.graph.plannerAssignment",
                "orderHint": "8586195339979324367PZ"
            }
        }
    }
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf5a67a-232a-6ed3-c9eb-9df425de262a
* Version Independent ID: abfbe9ca-9e07-4dfb-398b-a1efcb6d32bf
* Content: [Planner: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/planneruser-list-delta?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/planneruser-list-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/planneruser-list-delta.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TarkanSevilmis** [comment]
Delta will return all the changes that happen (without merging them into a single change). The issue here is a bug that we're tacking about the assignment to the same person the task was assigned to changes the order hint, instead of getting discarded as a no-op. As a result, the delta feed will return each redundant assignment operation with the new order hint. We currently do not have a timeline for a fix.
