### ISSUE TITLE
Is also available in 21Vianet ?

### ISSUE THREAD

**Issue by qquiuc** [microsoftgraph/microsoft-graph-docs#7140]
I'm trying to get domains with graph for a 21Vianet, but the respon return 400 fro this api
request: https://microsoftgraph.chinacloudapi.cn/v1.0/{My 21domain}/domains
Response:
{
    "error": {
        "code": "BadRequest",
        "message": "Resource not found for the segment 'domains'.",
        "innerError": {
            "request-id": "18e2d215-7b98-4053-87c6-37f17ef8a23b",
            "date": "2020-02-20T04:08:48"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b94245-c71b-a359-e716-fbca59df2611
* Version Independent ID: 6eba33cb-9985-91e2-cd4f-ddf40655d565
* Content: [List domains - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/domain-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/domain-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/domain-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
To[ list domains](https://docs.microsoft.com/en-us/graph/api/domain-list?view=graph-rest-1.0&tabs=http), run: `https://microsoftgraph.chinacloudapi.cn/v1.0/domains`
To [get details about a domain](https://docs.microsoft.com/en-us/graph/api/domain-get?view=graph-rest-1.0&tabs=http), run: `https://microsoftgraph.chinacloudapi.cn/v1.0/domains/{My 21domain}`

No updates identified for the page. Closing the issue.
