### ISSUE TITLE
create meeting with specific organizer

### ISSUE THREAD

**Issue by JonasDewit** [microsoftgraph/microsoft-graph-docs#7144]
When creating an online meeting with an 'organizer' upn different from the identity used to generate the auth token, the specified organizer is ignored and the meeting is still created with the user that generated the token as the organizer. 

Is this supposed to work or is the 'organizer' property read-only and the documentation incorrect? Thanks for clarifying.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TheSinding** [comment]
I've got the same question

**Comment by paywuAtMicrosoft** [comment]
Right now on behalf of another user is not supported by this API. The user in the auth token will be organizer

**Comment by JonasDewit** [comment]
hi @paywuAtMicrosoft, thanks for the info. Are there any plans to support this in the future?

**Comment by JohnnyUndercover** [comment]
Is there anything new on this topic?

**Comment by mohkhodeer** [comment]
So is there any way to set alternate hosts (presenters) to the calendar events??

**Comment by hedayatkamalian** [comment]
i have same problem

**Comment by adntobias** [comment]
i would like to have this feature as well, any news on this?

**Comment by davidgarciamt** [comment]
i would like to have this feature too, is there a workaround to do this?
