### ISSUE TITLE
list of properties is incomplete

### ISSUE THREAD

**Issue by JonasDewit** [microsoftgraph/microsoft-graph-docs#7145]
it seems like not all properties that can be used (for example, when creating an online meeting) are documented. E.g. : the isBroadcast property is returned in the response and defaults to false. However, it can be used in the body of the request. Setting it to true in the request allows to create a Teams Live Event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bddf229-c02d-7595-78c5-6dac2b1c3c76
* Version Independent ID: a1ccb913-8d51-1445-e81f-a4f100a495e3
* Content: [onlineMeeting resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/onlinemeeting.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nandomx3** [comment]
Is true  thks for the broadcast info !!!

**Comment by lramosvea** [comment]
Closing as the doc has been updated
