### ISSUE TITLE
Overview of licenses required for each detection in alerts

### ISSUE THREAD

**Issue by TmJr75** [microsoftgraph/microsoft-graph-docs#7157]
Hi, are there any information on what licenses are required in each tenant to view the different threat detections?
For example, if I have Azure AD Premium P1, these alerts are available, and if you have Azure AD Premium or Advanced Threat Protection you have a list of different alerts available? 

Regards
Tore Melberg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2386e96-01f0-3c21-b076-c147e035a17b
* Version Independent ID: 3d0a052a-2c66-35be-3079-65db8f5f8d95
* Content: [Get alert - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/alert-get?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/alert-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/alert-get.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@TmJr75 each security provider will provide different security alerts, and you need to have license for each of the service provider to be able to get their alerts.
