### ISSUE TITLE
Broken link to "Calling and online meetings (Preview)" page

### ISSUE THREAD

**Issue by marco-nicola** [microsoftgraph/microsoft-graph-docs#7158]
The link "Calling and online meetings (Preview)" points to the URL "https://docs.microsoft.com/en-us/graph/api/resources/calls-api-overview?view=graph-rest-beta", which gives the result "404 - Page not found".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4f5720-3eb2-fe1d-472e-497d1449f97b
* Version Independent ID: eaa22434-4691-77e2-8905-bf6d7e9e0bef
* Content: [Microsoft Teams API overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-concept-overview#feedback)
* Content Source: [concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-concept-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by zhengni-msft** [comment]
It should point to https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-beta

**Comment by zhengni-msft** [comment]
Or point to v1 doc might be even better. https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-1.0

**Comment by lramosvea** [comment]
Closing as link has been fixed
