### ISSUE TITLE
$top doesn't work on delta of users

### ISSUE THREAD

**Issue by rayhogan** [microsoftgraph/microsoft-graph-docs#7160]
When I include the the $top parameter in my query, it still returns me the full data set. 

Example: I have 8 changes in my data set, which are a mixture of user changes (firstname, lastname, etc), as well as a new user and a deleted user. When I try include $top=2 in my query, I get all 8 instead of 2 results. I am trying to force a resultset that contains a nextlink property, but without a working $top parameter I am unable to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview#feedback)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @rayhogan 
Thanks for bringing this to our attention.
Can you provide us with the exact request URL you were trying use please?

**Comment by rayhogan** [comment]
Here is the URL I am using:
https://graph.microsoft.com/v1.0/users/delta?$deltatoken=8j2P6jk93EJyKvHOczdP4SKgY3-ublTEGVUiLDAYeCpc7hDpmPXnnMp-j-t_8zfKVjcDJ18CsiJy6SGZz4Uhb6nLOAAiOFMhioKyVbVaTFRlGFCSDCyN2-ByXKxZdkfiAnYtBLVsvtpyc-9UcXLjxxz4X1_Zzp-Cm1KBRPs9gbLvvsFucHDTBwfa8fCCNP0A1efi8zNw-ThBsqnFTHN9scs8Dd_myGSfawIzQrLB-ZqqLACF7IHlCBEdeqioyV4m6RgpIRKZ9Gt1XP_UUkEnZpbZn4-_Q-AQAeejfmvTXoPmPOtvgwjGaFB-AF3kLvXZcyNNhYj4d0QdLZWGYLCtUAWzIlQuxOMpzWlNa-AdSM_FIhxF6Agg2IZjFS9wj37t6eUpTd2CizBItyEHvXGYXM2Rc0t0Ho7QK-hXmQlS8ejYCSf8rebu8xO5r-URah6E3PhOw0pZZIZ8LEFx_RkW0wngzZGCh7IPntnOD6dKAGfq3MfFFqxPE79N-66E_7zEZ1mFKM31RxnXXEIIKRwCOl60drfvlVUyMC_DgRESX5ykxv5ewY1zSM1IpQGAYHtI9Wl-z4OK6CIL_wO2U_PYLDzI7Lb75jEHYMK6pR2LWgqWW39lfP2g8omCYKXfO1QfaiZqciRf4m0nrrBnyRTSwVRJhup1D_u4YPs3loVGpF_YVJsr3SrtIcNqEipoPh5PxkoJOnOMAUr0ei46ErA5KTt9XjjhsC_JEKngpxmjfI5RTRDLEi0qDvNQPgRwOD6d5dS9bKNz3hEwR0VxiVK0pwwDmVUh07Yl4SpR9b4DwlwPOlVvAQXFn9CShdVoYezN8k14nhnm3mmby1r9aW03jWDk2Uqr1BHVzoLrWR3K97TyPdnKQVwfbS5q-rMpNYXf2sgkLeDI2LjA_V2H9wCQsHmdP28QN4-5qz_pvOlosb5SWJfZtORqWmv3TOirDAN635mbHO49MmKd0shp1yqMPBo7zFnrND_QsQ9drQIG2_P6Us-rafgRzZbLsScO98iPbDarF8xl49mqDpadTWcqtK2w-xymB_mm46mDqcsXyLvSPFosw2Kq7FtLlu7n5xNljGzsdtr1dSXCL5QpWCJ9-eH4eF8b_jtnbMJHVOqSR_d_QrWGErIYuNoQa5ONw_BwiJP4B-w1Wtqa8Y7fzCO-3t-BEDIxd67NKKA6BkNLOqDhtRzmHWdBoIu5I3jk3Lf_MGXRf3_kDzqRcJ6ky8Mugc1YZPO2s2s_s6XQ9XQ4Ut_ukWoN-7BDiWGlNAtn-Z4TeiUt6trtMwgyFY2IsrBGOdgjkJvCnBlVrMGJetEVIlGan03T2saJ-dw3vMjmwKDiCzPwVob7yNSK0PYGsLBcdMU5LkFjA6uPClXuGbXEwAEcOUvEiHBBsK3PRedSLZ7FOwD26Uxi9jCDIy9e70PaY55ALJ-sglvVSKhW1LAKG0PH8bpVgGEfbkl88Mfmv_j-zHuehtqMEwrSk6eD4-29ioLj7HWMDAM3OIglKfUbb6opzqDFkzqZS6BgtUnZYVOhmTb56i294c065R8viVA1hJsPvLScy_YNYCId1Y1XhLost7pNk3i4HRH-UBf-B9Ek88whHzowDxQyvs-UHuDxbHPBxzZks6n44rAus8DnWsr8Et_Tv-OIY1VhHXFWk-SFt2cKP78ogkE-TBGTeW64E75wL8o7YHsmisouwqC1YoiOmdgumb5ruMZsV3i-ItCoLRbnmmoSqpoVU7d4i-SQ8LUirWWflqturld9JTxitE9XK3YrsN_IyNMsUI2QJY6DupWqbe7J-56VTlTRuV7vlu4Xp-gfbegtRRvucAYZ2OlpljEVSxMjWhShR08s8Y1bXtWJskdGQIp3vzuwWdbSLEcZEPag5WSIKPx0sz1hme1nyqCVgiY74IyotaERnSrjVpLCWed_YLVci97UuH8X8irD2AlDdEjI7TdqI9bBDwxQQYDHAK4iX-DyVbEVXL77L5t-Wr2O8v-s5LDoXF_ai8M8bkWjjw9VugtuctPd30eT-5OmWOUfvFJ6lEPmGQ4ySPB8Sind03OXlpTYZm542c5lqK3iGFkTZ7UdYy0oBj62I5QpnvrHM6qCMy4Rf3uoYbPYPQgve22ZxfohYuquagAmvYKtBOpof1GLmSz9yy-JbdrRTfnrtlLn2tD6MpOEgpi6E8SQEpnpduIdjH-LUJN2vt0vVwLMZIWo3FFWo-Zh-Zo0uUkmZ7q7amMGcaO5TjppoewMu-tPJBaZWtSOydTwB4hec78mV02LLUkcRc6ogvNcshML34Pjjwg5uYKmGLO4HIUnZAOVm5wsWuX7XtV-6HljNQSS2ic6ZhIMxJq6_yELaQErjdIxsmLWtPTXVGt85jDYWNN_zg-32P_bTaz9NyTTIafEiCyNllSYAY07YhxRWHsDosfFtu1gy24bgyGAis-3gKrmPfwQURTTzeuyNx4DyO3s3Bsqo5Vnr85Dt8BugLDq-6lR8eHTWwpW2joUWI4tTMoTQcQyvzgzd7ESfHU_cS4qgi72EYHaoWhjhouzfBVR3Xmnw-MHQDSeZMdycAFL3IGByL7cd7S5wL_Mrhb9RyCieSO61qkZdc9wCKZ6f_1mK---zgRSOR7-qwxAjgqXMgoaLaVyHuL4Usbmw65Que9j97ukUkBTQH4GJS8P2tX6Bza2fOCpHywSb2wZLiHB8M93M4inhGfcE72up09aVWHylddVLkvQe-j_JH6jVpxGb1yEXQ9kmw09VpPSzBm5Ce1-NYsbJj8ZXRTJk3Cv-GwR_VaZGQBGpeMEhqecBqK1_fpOPpcnHQ7i0K8Lnc8_lJPP6E35nIFJ6Sj-bzndErQrnfecW5U8CG4XMl_pL-En2atZE94HyQqYkzt5TrMspYxM4IdPVqF6QNHwZQmlIhgXDKczFSslTU_MgQyfAfAV1_6MXLfeScXucJBZwWKJI9mW2bzMWskHuA.Gnd-t6fzN7WlWfkVEAG-E3A-Ib97qnKWhqTtP2JTgD0&$top=2

Test it yourself in graph explorer. Including &$top doesn't have any effect. It works on other endpoints but not with on the delta.

**Comment by baywet** [comment]
Thanks for the additional detail. As mentioned here: any OData query parameter has to be specified in the original request and will be part of the token in the subsequent requests, it cannot be provided in a request with a skiptoken or deltatoken.
https://docs.microsoft.com/en-us/graph/delta-query-overview#optional-query-parameters

**Comment by rayhogan** [comment]
I've read that a few times now, and it doesn't read as if it doesn't work, just that it may not work correctly.
"The number of objects in each page can vary depending on the resource type and the type of changes made to the resource."
 If $top cannot be used on a delta query of users then it should be explicitly stated.

**Comment by baywet** [comment]
Thanks! I authored a PR to add the precision. #7175
