### ISSUE TITLE
RecurrenceTimeZone is an empty string for participants of an all-day recurring event

### ISSUE THREAD

**Issue by hensapir** [microsoftgraph/microsoft-graph-docs#7163]
The recurrence.range.recurrenceTimeZone property of an all-day series master event is an empty string for participants of a recurring event, however it is properly set for the organizer of that recurring event. 

The recurrenceTimeZone is necessary to understand what day the OriginalStart value of exception events actually refers to, since OriginalStart is not midnight in UTC, rather it is midnight in the recurrenceTimeZone converted to UTC. 

Is this intentional or a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41a9857-98a9-e400-d7ce-bd7c0f37cd46
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/event.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Could not reproduce the issue.

For event of type 'seriesMaster' with 'isAllDay' set to true and with my ID only as attendee (not as organizer), able to retrieve recurrence with pattern, range and timezone details.
