### ISSUE TITLE
List all teams - Get team information for a group fails if you are not a member

### ISSUE THREAD

**Issue by dbaldacchino** [microsoftgraph/microsoft-graph-docs#7167]
If querying a Team by group-id and you are not a member of that team, the call fails and the response makes little sense, stating "Failed to execute Skype backend request GetThreadRequest." Without this functionality, we cannot query all teams for basic information, to list channels, etc.

I am using Application Permissions that have been consented by an admin for the entire organization (added the required APIs to the application and am using the "/.default" scope when authenticating and getting access & refresh tokens). Also confirmed that this call functions if I am a member of that Team. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75dbe68-e162-8861-d194-4a29de3bd731
* Version Independent ID: f58a6930-8575-8306-4273-fc413b979879
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#feedback)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-list-all-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
Tried to get team information for the team in a particular group using application permissions via Postman and it worked fine although the user was not part of that team.
Also to get a list of all groups in the organization it will give response having all the groups in that organization irrespective of membership of any group.
