### ISSUE TITLE
Wrong JSON Representation

### ISSUE THREAD

**Issue by cr45h0v3rwr173** [microsoftgraph/microsoft-graph-docs#7170]
The JsonFile didnt contain the keyValue 
supportScopeTags :true
this is a bug in the JsonObject that comes from GraphApi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bbbeeb5-43ed-87cf-32d8-73783febba4f
* Version Independent ID: ac54526b-0745-203d-a456-509561c6fc14
* Content: [groupPolicyConfiguration resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-grouppolicy-grouppolicyconfiguration?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-grouppolicy-grouppolicyconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-grouppolicy-grouppolicyconfiguration.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cr45h0v3rwr173** [comment]
Place were the information is missing Example with Custome Profile
![grafik](https://user-images.githubusercontent.com/23104978/75133992-26fb8380-56dd-11ea-8fbe-ea11a6671399.png)

Place off missinge Information at Administrative Template

![grafik](https://user-images.githubusercontent.com/23104978/75133911-ccfabe00-56dc-11ea-8470-05e7ae1e007b.png)

**Comment by triplanedave** [comment]
Thanks for your feedback.  We'll work on updating the docs in the next upcoming few update cycles.

**Comment by triplanedave** [comment]
Marking closed as we have a team work item to update the docs.

**Comment by triplanedave** [comment]
After investigation, the property supportsScopeTags isn't applicable here.  A description of the use of the property is here: https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-androidforworkgeneraldeviceconfiguration?view=graph-rest-beta and indicates why the property isn't needed.
