### ISSUE TITLE
remoteAssistanceSessionUrl is empty, but not with $select

### ISSUE THREAD

**Issue by pedrr** [microsoftgraph/microsoft-graph-docs#7177]
using Graph Explorer to retrieve the device information brings an empty value for 'remoteAssistanceSessionUrl'. If you query with '?$select=remoteAssistanceSessionUrl', you'll receive the correct value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 336b5b0a-2dac-7994-d4dd-1e7eb5d61ac9
* Version Independent ID: 0766eaad-1842-168c-a6c2-81f529370070
* Content: [Get managedDevice - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-get?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-get.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Some properties do require $select to retrieve the value such as this one.

**Comment by triplanedave** [comment]
Marking closed based on previous answer.
