### ISSUE TITLE
Incomplete Coded Workflow for "Create Azure AD User Account" (CreateUser)

### ISSUE THREAD

**Issue by TaviTruman** [microsoftgraph/microsoft-graph-docs#7183]
**Coded Workflow for "Create Azure AD User Account"**
The C# code samples are a great help and aid; however, what is the "Scope" configuration and coded workflow when in your app you need the capability to create a new AD User Account? The use-case might be something like _"New User On-boarding", Register New User Account_. It seems like one would need to configure the API to use the Azure AD endpoint and connect to the source Azure AD tenant with a Scope configuration that is able to create a new Azure AD User Account. 
The sample provided does not describe the context with a coded workflow that precedes the example of how to use the "CreateUser" API call. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=csharp&source=docs#feedback)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sujayvsarma** [comment]
#please-open

**Comment by sujayvsarma** [comment]
#reopen
