### ISSUE TITLE
Application permissions

### ISSUE THREAD

**Issue by MrAzureAD** [microsoftgraph/microsoft-graph-docs#7185]
The reason to modify conditional access policies via API is typically because of automation.
However, for this call application permissions are "not supported". Is that a typo? 
Because the whole call does not make any sense in delegated context.
Please verify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37b07bb9-f3ea-e60e-d235-9aa17c322e77
* Version Independent ID: fc247181-4739-0e4e-bd28-167d1f1767e0
* Content: [Update conditionalAccessPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-update?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/conditionalaccesspolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conditionalaccesspolicy-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by videor** [comment]
App-only permissions are now supported for full CRUD operations. Please look at the required permissions - https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-1.0&tabs=http

For, read operation only Policy.Read.All is required. For read and write all three permissions are required - Policy.Read.All, Policy.ReadWrite.ConditionalAccess and Application.Read.All
