### ISSUE TITLE
Place APIs latency when exchange information is updated

### ISSUE THREAD

**Issue by abbodh** [microsoftgraph/microsoft-graph-docs#7192]
When a room is deleted/modified in exchange then the changes do not get reflected at the same time. There seems to be some latency but it is unclear how much time it takes to reflect the changes. Can you please update the documentation to highlight the same. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41555953-ca70-587c-4660-5f0a83c8c230
* Version Independent ID: 4a5b79f8-d685-6c86-d7ed-12d7c5d309cb
* Content: [List places - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/place-list.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by freedomofkeima** [comment]
Is there any update to this issue? 👀 We encountered similar problem here...

**Comment by vrod9429** [comment]
Hi, yes there is a delay. Today it takes about 48 hours. We will update our documentation to reflect this. We hope to fix this by July.
