### ISSUE TITLE
Limitations For Subscription Creation Using

### ISSUE THREAD

**Issue by ifflanb** [microsoftgraph/microsoft-graph-docs#7196]
Hi, the documentation above says "These limits do not apply to resources from services other than Azure AD. For example, an app can create many more subscriptions to message or event resources". I am creating subscriptions for incoming and outgoing email from and to Office 365 mailboxes. Can you tell me what the limitations are for this scenario please? e.g max number of subscriptions per user account. We are using Azure AD for registering the application. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks#feedback)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ifflanb** [comment]
Any updates on this?

**Comment by saurabh47** [comment]
I want to know the subscription limit for `/users/{userId}/events `. I'm registering webhook for the each users calendar events. so I have more than 300 users.I want subscribe events of all the users.

as per [documentation ](https://docs.microsoft.com/en-us/graph/webhooks) it show the limit 
Maximum subscription quotas:
- Per app: 50,000 total subscriptions
- Per tenant: 1000 total subscriptions across all apps
- Per app and tenant combination: 100 total subscriptions

> Note: These limits do not apply to resources from services other than Azure AD. For example, an app can create many more subscriptions to message or event resources, which are supported by the Exchange Online service as part of Microsoft Graph.

As document suggest event resources can have more subscription.I want to know the limit.

**Comment by ifflanb** [comment]
Is this the correct place for this ticket? Just need to make sure that someone is actioning it?

**Comment by ifflanb** [comment]
@svpsiva ?

**Comment by ifflanb** [comment]
Is anyone looking at this issue?

**Comment by baywet** [comment]
Hey everyone,
Thank you for your patience with the time it took to track the information down internally.
I opened the PR #9363 a couple of days ago to get the information in the documentation. Don't hesitate to leave feedback on the documentation edits there!
This issue will be closed when the PR gets merged.
