### ISSUE TITLE
Unable to find User.ManageIdentities.All permission

### ISSUE THREAD

**Issue by Norrch2** [microsoftgraph/microsoft-graph-docs#7199]
Per your documentation. I am trying to update the identities collection and am looking for the Api permission: User.ManageIdentities.All permission and am unable to find it.

I have tried looking in Azure Active Directory and Azure Active Directory B2C blades. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad15fb9-23aa-165f-2dbd-5838c951c5b5
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
@psignoret can you please take a look at why this permission is not available? It is fully documented.

**Comment by psignoret** [comment]
@krbain I see this permission both in both it's app-only and delegated flavors in the Azure portal > Azure AD > App registrations > API permissions (screenshots below). The permission was enabled on March 8th, 2020, which likely explains why @Norrch2 couldn't see it back when he first opened this issue.

![image](https://user-images.githubusercontent.com/231140/81825055-6c8a5880-9536-11ea-8dbc-e8d6f4afab5a.png)

![image](https://user-images.githubusercontent.com/231140/81825073-7449fd00-9536-11ea-9e6b-7571ffe41ea0.png)
