### ISSUE TITLE
Throttling on listing domains

### ISSUE THREAD

**Issue by sumit-kakadiya** [microsoftgraph/microsoft-graph-docs#7203]
Will the throttling for the domains and outlook API shared or both have different one if I am accessing both of them with single tenant application id?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b94245-c71b-a359-e716-fbca59df2611
* Version Independent ID: 6eba33cb-9985-91e2-cd4f-ddf40655d565
* Content: [List domains - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/domain-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/domain-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/domain-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Sorry for the time it took to respond to this issue.
Over the last few months we've documented a lot of additional service limits for throttling.
Please have a look and open more specific issues if the information you're looking for is still missing. I'm going to go ahead and close this one
