### ISSUE TITLE
resource support for application id

### ISSUE THREAD

**Issue by sumit-kakadiya** [microsoftgraph/microsoft-graph-docs#7210]
Can I have resource type support for entire application instead of individual user? e.g my application wants to set notifications for incoming mail for perticular user.

something like    "resource": "users/user@mydomain.com/messages" , is this supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Yes, /users/user@domain.com/mailFolders('inbox')/messages
As shown in the first example https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#example

**Comment by sumit-kakadiya** [comment]
Thank you verymuch.
