### ISSUE TITLE
Limits are not identified

### ISSUE THREAD

**Issue by M1ch3lG4gn0n** [microsoftgraph/microsoft-graph-docs#7218]
I figured that the maximum message body is 28522 characters.
But sometimes I get a Request Entity Too Large exception. It seems to be related to the JSON payload itself, but it's unclear.
Is there a maximum number of attachments, mentions or JSON size?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams talks about some limits. So the limit is in the order of about 28KB. However things like at mentions consume extra space and so do a lot of cards.
