### ISSUE TITLE
How to filter this properties in User List?

### ISSUE THREAD

**Issue by berviantoleo** [microsoftgraph/microsoft-graph-docs#7228]
Hi I have a problem when filter the user list in property signInActivity. How the correct data I should send?

I use this to filter user:

`GET https://graph.microsoft.com/beta/users/?$select=userPrincipalName,signInActivity&$filter=signInActivity/lastSignInDateTime lt 2020-02-01`

I got this error

```json
{
  "error": {
    "code": "",
    "message": "Could not find a property named 'signInActivity' on type 'Microsoft.AAD.SchemaHelper.Models.MSGraph.UserSignInActivity'.",
    "innerError": {
      "request-id": "a50b7639-6c0e-455a-b010-93697f0d092b",
      "date": "2020-02-28T04:09:01"
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0f258b-b61e-72a2-0caf-d9b7fff5857d
* Version Independent ID: 90c2edf2-51ee-6bab-84a6-3710a3f0ccd2
* Content: [signInActivity resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signinactivity.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @berviantoleo 

according to the documentation the signInActivity supports $filter, but not with any other filterable properties. Maybe you can give it a try and only filter by the signInActivity property?

This is from the documentation: "Get the last signed-in date and request ID of the sign-in for a given user. Supports $filter, but not with any other filterable properties. Returned only on $select. Read-only."

I hope it helps.

Regards,
Jarbas

**Comment by berviantoleo** [comment]
Hi @JarbasHorst , yes, I already only filter by the signInActivity, here is my request:

`https://graph.microsoft.com/beta/users/?$select=userPrincipalName,signInActivity&$filter=signInActivity/lastSignInDateTime lt 2020-02-01`

is it my query wrong?

**Comment by JarbasHorst** [comment]
Hello @berviantoleo 

sorry, your query looks good. I tried that on my tenant, but I'm facing the same exception. If I remove the filter query parameter, the query works great. It looks as if the documentation has been prematurely released and that all functionalities are still not working for the signInActivity property. Have a look at this link for more information: https://github.com/microsoftgraph/microsoft-graph-docs/issues/6874#issuecomment-591691657

I hope MS will support filtering by signInActivity soon! 

Regards,
Jarbas

**Comment by davidmu1** [comment]
@berviantoleo - This is supposed to be working now. Please try again.

**Comment by berviantoleo** [comment]
hi @davidmu1, I want ask little bit out of topic, but this is happened when I call that API too : `https://graph.microsoft.com/beta/users/?$select=userPrincipalName,signInActivity&$filter=signInActivity/lastSignInDateTime lt 2020-02-01`.

I face this error

```json
{
  "error": {
    "code": "Authentication_RequestFromNonPremiumTenantOrB2CTenant",
    "message": "Neither tenant is B2C or tenant doesn't have premium license",
    "innerError": {
      "request-id": "ddb00ccd-d406-41d6-9d55-6fd43e7629e0",
      "date": "2020-03-29T00:25:31"
    }
  }
}
```

So, is it mean I need to have premium license to call on this? I will try to use another account that have premium license after this.

**Comment by berviantoleo** [comment]
Hi, I've checked. I just curious and have last question, when I use filter by lastSignInDateTime, so I can't get who never signIn, yes? Somehow, can close this, because the filter looks like work as expected now.
