### ISSUE TITLE
[LOC] Back-Translation "2 行分"→"Double"

### ISSUE THREAD

**Issue by hyoshioka0128** [microsoftgraph/microsoft-graph-docs#7231]
[LOC] Back-Translation "2 行分"→"Double"

ja-jp:"https://docs.microsoft.com/ja-jp/graph/api/resources/photo?view=graph-rest-1.0"
![photo_j](https://user-images.githubusercontent.com/40815708/75537948-2d7e5800-5a5b-11ea-988b-b79ca7998519.png)

en-us:"https://docs.microsoft.com/en-us/graph/api/resources/photo?view=graph-rest-1.0"
![photo_e](https://user-images.githubusercontent.com/40815708/75537968-340ccf80-5a5b-11ea-8931-85edf9c2e45e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3181203d-50f2-b16d-a881-3415b3104422
* Version Independent ID: e45381ba-be2d-a1b5-d81c-f8ad43759d21
* Content: [Photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/photo?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/photo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/photo.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 article was HumanTranslated. Data types were reverted to ENG

**Comment by hyoshioka0128** [comment]
@OfficeGlobal - "Double" has been Fixed. Thanks.
Closed #7231.
