### ISSUE TITLE
[LOC] Back-Translation "だけ"→"basis"

### ISSUE THREAD

**Issue by hyoshioka0128** [microsoftgraph/microsoft-graph-docs#7232]
[LOC] Back-Translation "2 行分"→"Double"

ja-jp:"https://docs.microsoft.com/ja-jp/graph/api/resources/averagecomparativescore?view=graph-rest-1.0”
![averagecomparativescore_j](https://user-images.githubusercontent.com/40815708/75538912-c2ce1c00-5a5c-11ea-8d0c-2c537fb21e35.png)

en-us:"https://docs.microsoft.com/en-us/graph/api/resources/averagecomparativescore?view=graph-rest-1.0"
![averagecomparativescore_e](https://user-images.githubusercontent.com/40815708/75538931-cc578400-5a5c-11ea-9cfe-a7003c0625ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb68b63-979b-51f2-ff28-b72ff03e948b
* Version Independent ID: 2236b4b8-c4eb-256f-4658-c3db3a3dd9c8
* Content: [averageComparativeScore resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/averagecomparativescore?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/averagecomparativescore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/averagecomparativescore.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@hyoshioka0128 , do you have any specific questions for us regarding the averageComparativeScore?

**Comment by hyoshioka0128** [comment]
@chinguyen1,  I do not have any questions. Over-translation only.Thanks.
