### ISSUE TITLE
Is the return 200 or 204?

### ISSUE THREAD

**Issue by phuong-vo** [microsoftgraph/microsoft-graph-docs#7238]
I use Graph Explore to made a call using this API, I got  200 response, but in this document it is 204.
I use msgraph-sdk-java/msgraph-beta-sdk-java, and debug with those sdk and saw the responses are 200 as well; However, the sdk throwing exception:

`! java.lang.ClassCastException: class java.io.BufferedInputStream cannot be cast to class java.lang.Void (java.io.BufferedInputStream and java.lang.Void are in module java.base of loader 'bootstrap')
! at com.microsoft.graph.requests.extensions.UserWipeManagedAppRegistrationsByDeviceTagRequest.post(UserWipeManagedAppRegistrationsByDeviceTagRequest.java:43)`

So I think there are some mismatch information between this document, Graph API, and msgraph-sdk-java.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d81a9ca-f860-909c-97db-cc9693ba64d4
* Version Independent ID: a9af3bb7-ceb7-e8fa-38bd-f8a35bc62a4c
* Content: [wipeManagedAppRegistrationsByDeviceTag action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-shared-user-wipemanagedappregistrationsbydevicetag?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-shared-user-wipemanagedappregistrationsbydevicetag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-shared-user-wipemanagedappregistrationsbydevicetag.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @rolyon
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks this API should be returning 200 as you indicate.
