### ISSUE TITLE
Example using curl

### ISSUE THREAD

**Issue by mdhruv1** [microsoftgraph/microsoft-graph-docs#7241]
Please can we add the examples using curl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e6b4ed-4a94-6789-95e3-407780e8fd7e
* Version Independent ID: ff8aca6f-1a1f-1bef-c1dd-bfdbbaf9f901
* Content: [Attach large files to Outlook messages - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=javascript#feedback)
* Content Source: [concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-large-attachments.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@mdhruv1 thanks for your feedback, we'll review the possibility to do that. Thanks.
