### ISSUE TITLE
contains, has, endswith support

### ISSUE THREAD

**Issue by sumit-kakadiya** [microsoftgraph/microsoft-graph-docs#7247]
Is there any plan to have "contains", "endswith", or "has" type of support in filter?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-gb/graph/query-parameters#format-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
@sumit-kakadiya are you thinking about specific endpoints or as a general Microsoft Graph support?

**Comment by baywet** [comment]
Closing the issue due to lack of response, feel free to reopen if needed

**Comment by ahacking** [comment]
Please re-open as many graph endpoints have rudimentry (at best) ability to filter on strings.

It is currently not possible to filter groups or users containing a string, or ending with a string on any properites including displayName or mail.

**Comment by baywet** [comment]
@ahacking the issues on this repos are meant to track gaps for the documentation. For any feature request/improvement please upvote existing ideas (or create new ones if none exist) at https://microsoftgraph.uservoice.com . It helps us understand the need for something and priorities which helps you getting the changes faster :)
