### ISSUE TITLE
Returns wrong values

### ISSUE THREAD

**Issue by dankorsholm** [microsoftgraph/microsoft-graph-docs#7248]
Hi, when doing a GET on the secure score via Graph API. I'm presented with wrong data.

This is what is returned when doing a https://graph.microsoft.com/beta/security/secureScores$top=1
id                       : NA
azureTenantId            : NA
activeUserCount          : 8743
createdDateTime          : 2020-03-01T00:00:00Z
currentScore             : 289,0
enabledServices          : {HasExchange, HasProject, HasSharePoint, HasVisio...}
licensedUserCount        : 505785
maxScore                 : 540,0

Firstly, ActiveUserCount is way to high. We aren't near that number. Secondly, the current score according to the secure score portal is currently 163 and not 289. Thirdly, licensedUserCount is also crazy high, like insanely high. Fourthly, the maxScore through Graph is 540, but through the secure score portal, its currently 539.
So my question is, why are all these values returned wrongly?

When looping through the controlScores individually, i'm returned the correct score for each category which is then added up to the correct secure score.

Am i missing something or is the secure score graph api full of bugs atm?

Any ideas on getting the correct data back from Graph?

Best regards
Dan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc52e5ba-c66a-a5db-fde8-43ecae447d60
* Version Independent ID: f4ded98c-b942-470f-bb35-a421fccb5261
* Content: [secureScore resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/securescore?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/securescore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/securescore.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by preetikr** [comment]
@NaynaSheth - Can you please help answer? Thanks.

**Comment by Christine-MSFT** [comment]
Hi Dan,

Thanks for your feedback. The Secure Score team is looking into this issue for you. Can you provide us with your tenant ID so we can troubleshoot further? You can send it to secscorepm@microsoft.com if you don't want to comment here.

Thanks,
Christine

**Comment by dankorsholm** [comment]
Hi,

Ive just sent it through en email :)

Thanks

**Comment by Christine-MSFT** [comment]
Hi Dan, 

Was just about to say we haven't received it and saw your edit. Let me check with the team on how we can get that alias fixed as I don't think we can post individual emails on here.

Christine

**Comment by Christine-MSFT** [comment]
Alternatively, you can click "Give feedback" in the portal, and check "it's ok to contact me". 
![image](https://user-images.githubusercontent.com/63429605/79594452-e2171c00-8091-11ea-871b-af6fdd06800a.png)

This will be the faster resolution.

**Comment by dankorsholm** [comment]
Hi Christine,

I clicked give feedback and sent the message (Text was: Referencing: [microsoftgraph/microsoft-graph-docs] Returns wrong values (#7248))

Thanks for your help :)

/Dan
