### ISSUE TITLE
Auto Admitted Users

### ISSUE THREAD

**Issue by mathiasnielsen0** [microsoftgraph/microsoft-graph-docs#7252]
When i'm creating a meeting with no attendees, the meeting says "Someone in the meeting should let you in shortly". I want to create a meeting, that everyone who has the link is able to join. I can see in the response that there is a property "autoAdmittedUsers" : "EveryoneInCompany", but it doesn't seem that I can change this? Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by aarushi-mittal** [comment]
Did you get any solutions ?

**Comment by mathiasnielsen0** [comment]
No i did not, I just assumed that it is currently not possible to set this

**Comment by younesdiouri** [comment]
Same here, thus it is not possible to make an external email attend to the meeting created via the graph?

**Comment by mathiasnielsen0** [comment]
I found out that this value depends on the configuration made in Azure on the user. I do not know where exactly this is done, as i did not do it myself (working as a consultant, so don’t have administrator access to settings to the service user I’m using). But i hope it helps anyway

**Comment by younesdiouri** [comment]
I saw also that there is an « Everyone » value (should be default) for AutoAdmitted users in the doc. With this value set and the online meeting link, externals should be able to join without restrictions IMO

**Comment by aarushi-mittal** [comment]
Hi @mathiasnielsen0 ,
It would be great if you could share what kind of configuration change was done.

I had also found out that a meeting policy can be set in MS Teams to govern such scenarios. But how it is applied for a particular meeting, that I am not aware of.

Regards,
Aarushi

**Comment by pratik-bhavsar** [comment]
Hello,
Still no information about this?
Its says  "autoAdmittedUsers": "EveryoneInCompany" even if I have set "autoAdmittedUsers": "everyone" in the request.
Regards,
Pratik

**Comment by pratik-bhavsar** [comment]
Hello again
I found the anwser! 
I created a post explaining how to do it here
[https://pratikbhavsar.net/allow-everyone-in-microsoft-graph-online-meeting/](url)
Regards,
Pratik
