### ISSUE TITLE
Create team not working anymore

### ISSUE THREAD

**Issue by Agazoth** [microsoftgraph/microsoft-graph-docs#7259]
I have been running Create Team Beta for the last ½ year with no issues. Today I get this error when calling the API:
```powershell
Invoke-RestMethod: {
  "error": {
    "code": "NotFound",
    "message": "Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/templates/api/team, Request Method: POST, Response Status Code: NotFound, Response Headers: Strict-Transport-Security: max-age=2592000\r\nx-operationid: af9b43f0011aa34bafb0400804c45201\r\nx-telemetryid: |af9b43f0011aa34bafb0400804c45201.38f8d9fe_1.\r\nX-MSEdge-Ref: Ref A: 6A658B600FBD4B62A0AD3C550C0F7AAD Ref B: AM3EDGE1013 Ref C: 2020-03-03T09:36:24Z\r\nDate: Tue, 03 Mar 2020 09:36:24 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"Failed to execute request for MiddleTier CreateTeamS2SAsync. Status code: NotFound.\"}],\"operationId\":\"af9b43f0011aa34bafb0400804c45201\"}",
    "innerError": {
      "request-id": "ef003a99-2268-4e9c-903b-9af5239c971a",
      "date": "2020-03-03T09:36:24"
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Agazoth** [comment]
Furthermore, it worked yesterday according to the logs on my Azure Function.

**Comment by JarbasHorst** [comment]
Hello @Agazoth 

can you create the Team using Microsoft Graph explorer: https://developer.microsoft.com/en-us/graph/graph-explorer Could you give it a quick try, please?

POST: https://graph.microsoft.com/beta/teams

``` JSON
{
    "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('standard')",
    "visibility": "Private",
    "displayName": "Sample Engineering Team",
    "description": "This is a sample engineering team, used to showcase the range of properties supported by this API",
    "channels": [
        {
            "displayName": "Announcements 📢",
            "isFavoriteByDefault": true,
            "description": "This is a sample announcements channel that is favorited by default. Use this channel to make important team, product, and service announcements."
        },
        {
            "displayName": "Training 🏋️",
            "isFavoriteByDefault": true,
            "description": "This is a sample training channel, that is favorited by default, and contains an example of pinned website and YouTube tabs.",
            "tabs": [
                {
                    "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('com.microsoft.teamspace.tab.web')",
                    "name": "A Pinned Website",
                    "configuration": {
                        "contentUrl": "/microsoftteams/microsoft-teams"
                    }
                },
                {
                    "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('com.microsoft.teamspace.tab.youtube')",
                    "name": "A Pinned YouTube Video",
                    "configuration": {
                        "contentUrl": "https://tabs.teams.microsoft.com/Youtube/Home/YoutubeTab?videoId=X8krAMdGvCQ",
                        "websiteUrl": "https://www.youtube.com/watch?v=X8krAMdGvCQ"
                    }
                }
            ]
        },
        {
            "displayName": "Planning 📅 ",
            "description": "This is a sample of a channel that is not favorited by default, these channels will appear in the more channels overflow menu.",
            "isFavoriteByDefault": false
        },
        {
            "displayName": "Issues and Feedback 🐞",
            "description": "This is a sample of a channel that is not favorited by default, these channels will appear in the more channels overflow menu."
        }
    ],
    "memberSettings": {
        "allowCreateUpdateChannels": true,
        "allowDeleteChannels": true,
        "allowAddRemoveApps": true,
        "allowCreateUpdateRemoveTabs": true,
        "allowCreateUpdateRemoveConnectors": true
    },
    "guestSettings": {
        "allowCreateUpdateChannels": false,
        "allowDeleteChannels": false
    },
    "funSettings": {
        "allowGiphy": true,
        "giphyContentRating": "Moderate",
        "allowStickersAndMemes": true,
        "allowCustomMemes": true
    },
    "messagingSettings": {
        "allowUserEditMessages": true,
        "allowUserDeleteMessages": true,
        "allowOwnerDeleteMessages": true,
        "allowTeamMentions": true,
        "allowChannelMentions": true
    },
    "discoverySettings": {
        "showInTeamsSearchAndSuggestions": true
    },
    "installedApps": [
        {
            "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('com.microsoft.teamspace.tab.vsts')"
        },
        {
            "teamsApp@odata.bind": "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps('1542629c-01b3-4a6d-8f76-1938b779e48d')"
        }
    ]
}
```

If the exception only happens sporadically, you could retry the request!

I hope it helps!

Regards,
Jarbas

**Comment by Scott-Cochrane** [comment]
@Agazoth, I started having the same exact issue.  I'm wondering if the schema definition changed at some point on the `template@odata.bind` attribute.  Mine was using `https://graph.microsoft.com/beta/teamsTemplates/standard` and after seeing test template posted above I switched to `https://graph.microsoft.com/beta/teamsTemplates('standard')` which fixed the issue.  Interestingly the old version still works fine on our test tenant but not in production.

**Comment by codezanthor** [comment]
I trying to Create Team Beta with minimal request but i keep getting either "unknown error" or "BadGateway" error

POST https://graph.microsoft.com/beta/teams

```
{
    "template@odata.bind":  "https://graph.microsoft.com/beta/teamsTemplates('standard')",
    "displayName":  "My Sample Team",
    "description":  "My Sample Team’s Description"
}
```

```
{
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": "11d4e62c-7bcc-408a-a746-6b643dc8deb3",
      "date": "2020-03-06T06:05:36"
    }
  }
}
```

**Comment by bckrma** [comment]
I face the same issue. (Beta and v1.0)
Some examples, tested with Graph Explorer:

POST https://graph.microsoft.com/beta/teams
Body
`{
    "template@odata.bind":  "https://graph.microsoft.com/beta/teamsTemplates('standard')",
    "displayName":  "My Sample Team",
    "description":  "My Sample Team’s Description"
}`
Response:
`{
    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "request-id": "4b9326c6-0a63-44a2-89c9-e4b64e50383d",
            "date": "2020-03-07T12:30:32"
        }
    }
}`

POST https://graph.microsoft.com/beta/teams
Body
`
{
  "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('standard')",
  "group@odata.bind": "https://graph.microsoft.com/v1.0/groups('d744b1cd-50a6-4dda-91f7-b4bb4abc6c6c')"
}`
Response:
`
{
    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "request-id": "0f3fffe6-8742-444f-b775-3945bee5ef9b",
            "date": "2020-03-07T12:38:19"
        }
    }
}`

PUT https://graph.microsoft.com/v1.0/groups/d744b1cd-50a6-4dda-91f7-b4bb4abc6c6c/team
Body
`{  
  "memberSettings": {
    "allowCreateUpdateChannels": true
  },
  "messagingSettings": {
    "allowUserEditMessages": true,
    "allowUserDeleteMessages": true
  },
  "funSettings": {
    "allowGiphy": true,
    "giphyContentRating": "strict"
  }
}`
Response
`{
    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "request-id": "713d22d2-2f3d-409b-af03-e0b5b9c9db26",
            "date": "2020-03-07T12:40:18"
        }
    }
}`

**Comment by JarbasHorst** [comment]
You could try to replace the template@odata.bind's value from https://graph.microsoft.com/beta/teamsTemplates('standard') to https://graph.microsoft.com/beta/teamsTemplates/standard. Maybe it helps! However, I haven't been able to reproduce this error yet.

Maybe someone from MSFT could have a look at this issue!

**Comment by Agazoth** [comment]
Works again - must have been a temporary thing
