### ISSUE TITLE
problem with creating booking customer from api

### ISSUE THREAD

**Issue by eliosm** [microsoftgraph/microsoft-graph-docs#7272]
When I create a customer booking from API the 'displayName' gets the same value from 'emailAddress' and please add more properties ('firstname', 'lastname' etc..)

![screenshot-developer microsoft com-2020 03 04-09_59_55](https://user-images.githubusercontent.com/61778961/75865282-98d17c80-5e03-11ea-9492-87938073c6d2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94d23218-f2f7-b0bb-5016-ac44cf4b5124
* Version Independent ID: 3fe487f8-a52e-0441-bdea-94d7ed4b5c7b
* Content: [Use the Microsoft Bookings API in Microsoft Graph - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/booking-api-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/booking-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/booking-api-overview.md)
* Product: **bookings**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@eliosm , thank you for your input. Please submit your suggestion at [Microsoft Graph Uservoice](https://microsoftgraph.uservoice.com/). There is a process set up there for service owners to triage input as such. Thank you!
