### ISSUE TITLE
Send sharing invitation not working for emails that do not have an existing MSA account or is already added to AAD

### ISSUE THREAD

**Issue by figgsoftware** [microsoftgraph/microsoft-graph-docs#728]
The invitation email does not go out when the recipient email do not have an existing MSA account or is already added to AAD

**Comment by dkershaw10** [comment]
Did you file this issue on StackOverflow (tagged [microsoftgraph]) already? That's a better developer forum for solving issues when using Microsoft Graph.  These issues filed here typically track documentation issues.

**Comment by Lauragra** [comment]
Looks like this issue has been posted to [StackOverflow ](http://stackoverflow.com/questions/41429312/send-sharing-invitation-not-working-for-emails-that-do-not-have-an-existing-msa) so closing here. Feel free to reopen if you have additional feedback about how we can clarify our documentation. Thanks.
