### ISSUE TITLE
Not able to filter users by identity

### ISSUE THREAD

**Issue by artmasa** [microsoftgraph/microsoft-graph-docs#7282]
The documentation  states that the `identities` property from `user` supports filter. Also states the property `issuerAssignedId` from  `objectIdentity` also supports filter.
When using expression `$filter=identities/any(d:d/issuerAssignedId eq '{username}')` returns error `Request_UnsupportedQuery`.
What is the right way to filter users by using these properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48a27bcc-3c5c-f12a-17f2-4afb365bb0f4
* Version Independent ID: c72e021b-c801-a398-b5b5-19bc8b565fe7
* Content: [objectIdentity resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/objectidentity?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/objectidentity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/objectidentity.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jonathan-pelletier-jdas** [comment]
After trial and error, the querying is supported, but you must supply both `issuer` and `issuerAssignedId` like so:

`GET https://graph.microsoft.com/beta/users?$filter=identities/any(d:d/issuer eq '{issuerName}' and d/issuerAssignedId eq '{userId}')`

**Comment by krbain** [comment]
When filtering on identities, you must supply both issuer and issuerAssignedId. This note appears on another article, apologies that this is not clearly stated here. We will update this doc to call this out. Thanks for the the feedback.

**Comment by CelesteDG** [comment]
PR https://github.com/microsoftgraph/microsoft-graph-docs/pull/7917 for this issue has been merged to master. FYI @krbain and @davidmu1

**Comment by artmasa** [comment]
Thanks a lot. I have tested providing both attributes clauses and it works as @jonathan-pelletier-jdas and @krbain mentioned.
