### ISSUE TITLE
Unexpected segment OpenPropertySegment. Expected property/$value.

### ISSUE THREAD

**Issue by dvvelzen** [microsoftgraph/microsoft-graph-docs#7283]
When trying the sendMail, with the samples, I keep receiving the error below.
Incomplete or missing json is returning a logical different error.
POST events like for example the move mail do return a "normal" error if the json is missing a property or so.

{
  "error": {
    "code": "Request_BadRequest",
    "message": "Unexpected segment OpenPropertySegment. Expected property/$value.",
    "innerError": {
      "request-id": "dbc6dd34-f7cf-4e30-8426-4ad056793c46",
      "date": "2020-03-05T05:45:05"
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by divurgentuser** [comment]
What was the fix?

**Comment by JeanFrancoisGay** [comment]
What was the fix for this.  I am running into the same issue.

var mailFolders = await client.Users[emailMessage.UserId].MailFolders.Request().GetAsync();

Is throwing Code: Request_BadRequest
Message: Unexpected segment OpenPropertySegment. Expected property/$value.

Yet I am able to retrieve an email's content (body) with the same graph client...

**Comment by dvvelzen** [comment]
> What was the fix for this. I am running into the same issue.
> 
> var mailFolders = await client.Users[emailMessage.UserId].MailFolders.Request().GetAsync();
> 
> Is throwing Code: Request_BadRequest
> Message: Unexpected segment OpenPropertySegment. Expected property/$value.
> 
> Yet I am able to retrieve an email's content (body) with the same graph client...

It was a pebkac. Incorrect url concatenation in the code which let to this message.
