### ISSUE TITLE
application not supported

### ISSUE THREAD

**Issue by jflieben** [microsoftgraph/microsoft-graph-docs#7286]
I'd like to be able to update devices using an SPN / appreg without on-behalf as flow (as an automated process). How can I do that without using a user account (as those are MFA-protected and thus won't work).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa32ac40-6aa6-e603-0d17-b576c30b6b62
* Version Independent ID: c10ea5e9-24d2-910c-5c10-58cc2188fc1f
* Content: [Update device - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/device-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/device-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/device-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
