### ISSUE TITLE
Exception thrown not documented properly.

### ISSUE THREAD

**Issue by chaitnya12** [microsoftgraph/microsoft-graph-docs#7288]
When I try to create channel in a team already having 200 channels , I am getting 403 Forbidden as HTTP status. In the error object returned , code property is 'Forbidden' and message is 'This team has exceeded the Max allowed channels'. However, code property 'Forbidden' is not documented and earlier I used to get 'ResourceLimitExceeded' in code property. Please update , so that we will be able to handle error scenario correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create Channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chaitnya12** [comment]
Hello @nkramer, any update on this issue??

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
