### ISSUE TITLE
Error with password update password

### ISSUE THREAD

**Issue by mattroger-work** [microsoftgraph/microsoft-graph-docs#7301]
When I update the password I get the following error Unable to update the specified properties for on-premises mastered Directory Sync objects or objects currently undergoing migration and when I do get the password to reset and require them to create a new password it uses their previous password rather than the one that I set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by oppknox** [comment]
Did you end up getting this issue fixed? I cant update over C# graph, but I have no problem doing so via powershell. :/

**Comment by davidmu1** [comment]
Synced user cannot be updated in the cloud. This API does not update synced users in the cloud. The sync process overwrites any changes. No change identified for the page. Closing the issue.
