### ISSUE TITLE
posting a file from channel files

### ISSUE THREAD

**Issue by husseinraoouf** [microsoftgraph/microsoft-graph-docs#7307]
is it possible to post a file that is already uploaded to the channels file
i get the file data but don't know how to insert that file as attachment in the message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
We are working on enabling more attachment types. But at the moment it is not supported sadly.

**Comment by rcichielo** [comment]
Is there any estimated timeframe for support of attachments?

**Comment by RamjotSingh** [comment]
The feature is being worked on right now. However with the uncertainty around Covid-19. We can't share a date yet.

**Comment by alardhi** [comment]
Is there any update regarding estimated time frame for support of attachments ?

**Comment by RamjotSingh** [comment]
We are trying to release it by middle of May.

**Comment by RamjotSingh** [comment]
Posting files is supported now. Here are the instructions.

1. Navigate to /teams/Id/channels/Id/filesFolder. You will get the following payload (only showing relevant info here)
```json
{
    "id": "--ITEMID--",
    "parentReference": {
    "driveId": "--DRIVEID--",
    "driveType": "documentLibrary"
}
```

2. Go to /drives/--DRIVEID--/items/--ITEMID--/children. The payload is an array, with one item looking like this
```json
{
    "eTag": "\"{--OBJECTID--},2\"",
     "name": "--FILENAME--",
     "webUrl": "--WEBURL--",
}
```
3. The attachment object now looks like this, with data pulled from above
```json
{
    "id": "--OBJECTID--",
    "contentType": "reference",
    "contentUrl": "--WEBURL--",
    "content": null,
    "name": "--FILENAME--",
    "thumbnailUrl": null
}
```
4. Rest of the message format is unchanged, but for reference the content looks like the following in message
`"content": "<attachment id=\"--OBJECTID--\"></attachment>"`

**Comment by mohaom** [comment]
I'm looking forward to having a thumbnail of the file posted, currently, the thumbnail need to reference an unauthenticated image, is there is a way to reference an image that exists in the files tab?

**Comment by RamjotSingh** [comment]
At the moment no. We are working on allowing posting of inline images. No timelines yet though.
