### ISSUE TITLE
Display name for external participants

### ISSUE THREAD

**Issue by runenur** [microsoftgraph/microsoft-graph-docs#7311]
The display name for external participants is simply "External user". Do you have any plans to change this to the actual Display Name of the external participant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d0ead6-000a-18a5-ed25-768ef68b479b
* Version Independent ID: 14cd7a2a-a5ca-772f-d398-5a7124029878
* Content: [callRecord resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/callrecords-callrecord?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/callrecords-callrecord.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/callrecords-callrecord.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
We don't have any immediate plans to change this.
