### ISSUE TITLE
List of call records

### ISSUE THREAD

**Issue by runenur** [microsoftgraph/microsoft-graph-docs#7312]
Do you have any plans to introduce an API that can be used to get a list of call records, i.e. before/after/between dates. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baff198b-501f-c97d-005d-36875302640d
* Version Independent ID: 413b2545-44cc-1f43-3feb-2c4deab9472e
* Content: [Working with the call records API in Microsoft Graph - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/callrecords-api-overview.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MPBetts** [comment]
Yes I need this too, so we can bulk extract call quality data.

**Comment by Sullemain** [comment]
Agreed, we need this too to extract the quality data logged for all records

**Comment by stephenjust** [comment]
We don't have any immediate plans to implement a historical list capability.

You can use the Change Notification /webhooks mechanism to subscribe to a feed of all call records as they are created or updated.

We do recognize the value of being able to query/list records outside of the change feed, but we don't have the backend in place to support that yet.

**Comment by gulfuroth** [comment]
Also in need of this. Need to be able to log communications from a user/group of users.

**Comment by wendelstam** [comment]
Agree that it would be helpful to be able to retrieve CDRs (or ids) for at least a couple of days back even after they happened.
Where is the best place to know the status of this "feature request" and when/if we can expect it to come?

**Comment by wendelstam** [comment]
Also is or will delta queries be available for the CDRs?

**Comment by jan-rezab** [comment]
We would REALLY need this...

**Comment by gulfuroth** [comment]
For those in need of getting some callRecord IDs for a given user, you can get them manually in the Teams Admin Center/Users/Call History. In fact you'll be able to see there all the info retrieved by the CallRecord API, so it's a good way to validate the info you'll be getting without having to do a full integration.

**Comment by natimerfish** [comment]
Do the call records support the delta link feature ?

**Comment by aabellav** [comment]
We also need this so that we can access to the list of records in a programatic way.

**Comment by biancini** [comment]
Do you have a plan of release for this feature?
Having the call list is fondamental to obtain IDS and then call the callRecord API for getting participation infos...
Thanks

**Comment by ryan-at-werk** [comment]
> For those in need of getting some callRecord IDs for a given user, you can get them manually in the Teams Admin Center/Users/Call History. In fact you'll be able to see there all the info retrieved by the CallRecord API, so it's a good way to validate the info you'll be getting without having to do a full integration.

@gulfuroth - Which attribute represents the callRecord ID?  Under Call History, I select a session and go to **Debug**.  I've tried using **telemetry-id**, **media_leg_id**, and **Cnd_Skype_InitiatingUser_Endpoint_EndpointValue**.  However, I get the same error for all:

`{
  "error": {
    "code": "NotFound",
    "message": "Could not find the requested call record. Records about calls or online meetings that started more than 30 days ago are not available.",
    "innerError": {
      "request-id": "c328ef08-786c-4af9-b472-698d244d42c1",
      "date": "2020-04-29T00:10:26"
    }
  }
}
`

**Comment by stephenjust** [comment]
@ryan-at-werk The ID to use is visible in the address bar. I don't think the Teams Admin Center exposes it in the UI.
