### ISSUE TITLE
Participant e-mail address

### ISSUE THREAD

**Issue by runenur** [microsoftgraph/microsoft-graph-docs#7313]
Today, we only get the id and the display name of the participant. The e-mail address that the user used to sign on is not include. When a recording bot shall decide whether or not to record a call, it would be preferable to base this on a unique e-mail address instead of a display name, which might change.

Do you have any plans to introduce the e-mail address as well, or do we need to use the User API to fetch this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 088a25f7-3e0d-a05e-3ca6-6639fccdfe79
* Version Independent ID: 2a2dafaa-0fe9-150f-aa6d-e32f6cc96c6a
* Content: [Get participant - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/participant-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/participant-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/participant-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by oleksii-gudz** [comment]
Any news/updates on this question? Also interested in this.
