### ISSUE TITLE
Throwing Bad Gateway Error while creating channels.

### ISSUE THREAD

**Issue by chiragSuccessive** [microsoftgraph/microsoft-graph-docs#7315]
#### Input - 
Post request to https://graph.microsoft.com/v1.0/teams/${teamId}/channels
Body - { displayName: channelName }

After creating 4-5 channels for same teams id -

#### Output -
``` 
"extensions":{"response":{"url":"https://graph.microsoft.com/v1.0/teams/fbcad4f2-372a-4512-b083-9e49dc340654/channels","status":502,"statusText":"Bad Gateway","body":{"error":{"code":"BadGateway","message":"Failed to execute backend request.","innerError":{"request-id":"406c6562-fe9c-4b0b-b777-e710c9147077","date":"2020-03-09T13:27:21"}}}}}}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create Channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MichaelLaMontagne** [comment]
Also seeing Bad Gateway error using Graph to create a single channel in one of my customer tenants, started on March 8, 2020. Same code/same tenant was working a week earlier.

**Comment by MichaelLaMontagne** [comment]
Issue resolved for me now.

**Comment by chiragSuccessive** [comment]
@MichaelLaMontagne I am still getting this error.

**Comment by rahrs** [comment]
We get this too.. works with delegated access through the explorer, but not with application

**Comment by chiragSuccessive** [comment]
@rahrs I am getting the error with the delegated access, can you please fix this.

**Comment by chiragSuccessive** [comment]
API is volatile, sometimes it works, sometimes it doesn't.

**Comment by chiragSuccessive** [comment]
Earlier I was getting error after creating more than 4-5 channels for the teams, now it is unpredictable and sometimes works, and sometimes doesn't.

**Comment by tiois** [comment]
Same error but with the beta endpoint. Was working fine until Thursday, April 16th 2020.

```
Server error: `POST https://graph.microsoft.com/beta/teams/{my-team-id-is-here}/channels` resulted in a `502 Bad Gateway` response:
{
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": "2ceece83-e3ff-455d-bc7b-b82f5454269f",
      "date": "2020-04-17T12:45:12"
    }
  }
}
```

**Comment by anandab-gt** [comment]
@chiragSuccessive @rahrs - Although it has been 7 months since you posted, wanted to check if you still facing this issue?

**Comment by daniel-pfaeffli** [comment]
Same issue here. I have multiple channels to provision for a team (up to 20). Put channelcreaton item in a queue an then create create all channels in an queue triggered azure function. Some channels are created for others i get the 502 bad gateway error. Can you please provide a workaround or fix?

**Comment by anandab-gt** [comment]
@daniel-pfaeffli - can you share request id

**Comment by daniel-pfaeffli** [comment]
Hi @anandab-gt 
Sure =>
`{"error":{"code":"BadGateway","message": "Failed to execute backend request.","innerError": {"date": "2020-11-01T08:58:17",  "request-id": "092567af-ea75-497c-921e-b01ff5d89c5a","client-request-id": "092567af-ea75-497c-921e-b01ff5d89c5a"}}}`

I did some more testing and came to following conclusion:
I am able to "bulk" provision about +-70 channels.  Subsequent calls to create a channel are resulting in the "bad gateway" error. 
This smells like the api is not propery responding on internal throttling...

Important => Same behaviour if i bulk provision teams from scratch or from existing group with  a json definition which includes channels. Issue present on the "v1.0/teams" and "beta/team" endpoint. After provisioning some teams witch channels (also around 70 channels) the provisioning status response from the "location" endpoint has several failed channels.

**Comment by daniel-pfaeffli** [comment]
@anandab-gt any update on this issue so far?

regards

**Comment by plamber** [comment]
Hello @anandab-msft,
we are experiencing similar 502 bad gateway error messages.

Please let me know if it helps sharing few request ids with you.

br,
Patrick

**Comment by eddie-lee-msft** [comment]
Hi @plamber. Yes, please share some request-ids and we'll take a look into it.

**Comment by plamber** [comment]
Hi @eddie-lee-msft,
Here some bad request messages:

**During channel creation.**
Exception while executing function: Code: BadGateway
Message: Failed to execute backend request.
Inner error:
	AdditionalData:
	date: 2021-01-18T16:23:18
	request-id: fb8a9b4d-166b-4748-b7ba-02e8758b39fc
	client-request-id: fb8a9b4d-166b-4748-b7ba-02e8758b39fc
ClientRequestId: fb8a9b4d-166b-4748-b7ba-02e8758b39fc

Exception while executing function: Code: BadGateway
Message: Failed to execute backend request.
Inner error:
	AdditionalData:
	date: 2021-01-06T06:16:12
	request-id: 2ae6a58b-0712-4f05-b51b-2e43826589a4
	client-request-id: 2ae6a58b-0712-4f05-b51b-2e43826589a4
ClientRequestId: 2ae6a58b-0712-4f05-b51b-2e43826589a4

I am wondering what is the easiest way to get the error message of the BadGateway request using the .NET Graph SDK. Do you have some suggestions?

Thank you for your efforts,
Patrick

**Comment by eddie-lee-msft** [comment]
Hey @plamber,

Here is the common exception I'm seeing from the logs for all three requests - 'User {user-id} is a guest, and cannot be added as member or owner.' This is our dependency service throwing an exception with this error message - I will get in touch with them to see why they threw this as a 5xx instead of a 4xx, and most likely log a bug on them.

With regards to your second question, we do not currently expose the detailed error message when the error code is a 5xx, only for 4xx user errors.

Please let me know if you have other questions.

Thanks,
Eddie

**Comment by narcisradoi** [comment]
whacking this on as it might help someone or at least track the issue down

it seems to me there's a required format of posts when updating (possibly also when creating) that is not mentioned in https://docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0 - mainly around having one field to update - displayName or description.

Every request to update a channel with a displayName or description field + 1 other field seems to work 

The error also shows if the request has identical information (no changes) but works if there is at least 1 change in one field.

Even if the body had the info below, it still threw the error if the information was exactly the same as the channel information. As soon as I changed one value e.g. favourite from false to true - it went through fine, but threw the error again when posting with the same value as the previous call

{
    "id": "channelID",
    "createdDateTime": "date",
    "displayName":"name",
    "description": "description",
    "isFavoriteByDefault": true/false
}

**Comment by wackywalrus** [comment]
Hello. Any update on this? We see this error while creating multiple private channels in a team. 

{"error":{"code":"BadGateway","message":"Failed to execute backend request.","innerError":{"date":"2021-06-01T14:49:57","request-id":"e739fa70-0ae9-4bdc-aa7a-10f0260d9e2a","client-request-id":"e739fa70-0ae9-4bdc-aa7a-10f0260d9e2a"}}}

Also, we noticed sometimes that the channel for which the request fails becomes a deleted channel. We have to restore it manually.

**Comment by Paul-Konsolute** [comment]
Same issue here,
It seems to be totally random. My example is provisioning 10 channels as 10 separate requests each with a name, and description.
First version works fine, second one :
![image](https://user-images.githubusercontent.com/85363522/122107696-43ac5500-ce13-11eb-82ff-60ab8670d8d3.png)
We get repeated issues, until the graph client eventually fails.
It's like a 429 error is not being propagated correctly.

I can provision say 15 of these groups/teams with 10 channels and then the next one will fail, or it could be 5 and the next two.
Today the error count  seems to be a lot higher.

nb Still occasionally seeing the ''User is not a a member or owner.' error too, but we retry thorough that.

**Comment by Meghana-MSFT** [comment]
Bug has been created for this and the concerned team is looking into it.

**Comment by lramosvea** [comment]
@Meghana-MSFT any update on this? Thanks

**Comment by Meghana-MSFT** [comment]
@lramosvea - Unfortunately, we do not have any update to share, we are checking with engineering team and get back to you.

**Comment by Meghana-MSFT** [comment]
Hi, could you please share the latest request id and timestamp? Thanks.
