### ISSUE TITLE
Filtering on identities rules

### ISSUE THREAD

**Issue by alex-mason-by** [microsoftgraph/microsoft-graph-docs#7317]
Is there a good reason why filtering users by identities must specify both issuer and issuerAssignedId? I can see if I am looking for a particular user this might be necessary but if want to find all users for a given issuer, why is this rule enforced and can it be relaxed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
@dkershaw10 can you please answer this?

**Comment by dkershaw10** [comment]
@alex-mason-by Thanks for bringing this up.  I believe we are looking into this as it is a current limitation, but I don't have any further details on this.
