### ISSUE TITLE
Unable to give a group permission on a folder

### ISSUE THREAD

**Issue by piyushrajput** [microsoftgraph/microsoft-graph-docs#732]
Using the call POST /drives/{drive-id}/items/{item-id}/invite based on https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_invite using the GraphExplorer and using the format provided:
POST https://graph.microsoft.com/v1.0/drive/items/{item-id}/invite

```
{
  "recipients": [
    {
      "email": "ryan@contoso.org"
    }
  ],
  "message": "Here's the file that we're collaborating on.",
  "requireSignIn": true,
  "sendInvitation": false,
  "roles": [ "write" ]
}
```
If I use email id of user, it gets added to the folder but if I used email id of a group, I do not get any error in the response but when I go to check the permission, the group is not there. Is adding group not supported yet?

**Comment by piyushrajput** [comment]
The group is a Office365 group type.

**Comment by jthake-msft** [comment]
This issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).
