### ISSUE TITLE
onenote page title format is missing

### ISSUE THREAD

**Issue by jonnyguo1988** [microsoftgraph/microsoft-graph-docs#7320]
I have a page which has format in title, but use 
https://graph.microsoft.com/beta/groups/{groupId}/onenote/pages/{pageId}/content
the result has no format for title
![image](https://user-images.githubusercontent.com/14086700/76289515-45b86780-62e4-11ea-8c2d-4f16e68433dc.png)

![image](https://user-images.githubusercontent.com/14086700/76289531-4fda6600-62e4-11ea-815d-28637d55b666.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c8de0d2-188e-f598-a729-80d00a703b8e
* Version Independent ID: 40371b25-cc40-d61d-3058-10f6f24168c7
* Content: [Get OneNote content and structure with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/onenote-get-content#feedback)
* Content Source: [concepts/onenote-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/onenote-get-content.md)
* Product: **onenote**
* Technology: **microsoft-graph**
* GitHub Login: @jewan-microsoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thank you @jonnyguo1988  for raising this issue. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-notes.html). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
