### ISSUE TITLE
the code example  incl "Try it" doesn't work

### ISSUE THREAD

**Issue by xhoy** [microsoftgraph/microsoft-graph-docs#7322]
When trying https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http#http-request i get a 400 bad request… 

The beta seems broken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c69782e4-57f5-8739-1e03-12fcdf4853aa
* Version Independent ID: ae3692d0-2697-9713-46d9-628b29cf0e9c
* Content: [Enumerate sites - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/site-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/site-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @xhoy 

the URL https://graph.microsoft.com/beta/sites?$select=siteCollection,webUrl&$filter=siteCollection/root%20ne%20null still works. You can try it with [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer).

It looks as if the "Try it" has a problem enumerating SharePoint sites. For instance, if I change the query to https://graph.microsoft.com/beta/sites/root, it works.

I hope it helps.

Regards,
Jarbas

**Comment by xhoy** [comment]
@JarbasHorst I notice other queries worked so as you noted it seems to be an issue with the "try it' feature.

**Comment by jthake-msft** [comment]
Thanks for the feedback. 

The current TRY experience is for GETs only and uses our demo tenant . There are many scenarios where our demo tenant does not have data so it won't return responses. The TRY it is the same code base as the Graph Explorer Preview. 

We are actually in the process of supporting of supporting signing into the TRY experience in the docs. So you can try samples against your own tenants.

With regards to this particular URL

`https://graph.microsoft.com/beta/sites?$select=siteCollection,webUrl&$filter=siteCollection/root%20ne%20null`

@JeremyKelley does this feature work now across all tenants?

**Comment by JeremyKelley** [comment]
The specific call to enumerate the site roots should work, and does if you copy / paste to Graph Explorer but doesn't from the Try link for some reason.

General site collection enumeration is shipping soon but not yet fully available.

**Comment by xhoy** [comment]
@jthake-msft maybe the try should be "copy to graph explorer preview"? I worked with the graph explorer (except you cannot past urls there...) and it was awesome for testing!
