### ISSUE TITLE
Difference in upn and e-mail for Guest account on External AD

### ISSUE THREAD

**Issue by johanflikweert** [microsoftgraph/microsoft-graph-docs#7324]
When a user has an account on an External Azure Active Directory and its user principal name (upn) differs from his e-mail address; shouldn't you enter its upn besides its e-mail address?
The upn is used for identification, right?
And the e-mail address is needed to send an invitation (with redeem URL)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f51b2654-e447-d495-2788-d6d5b13402b4
* Version Independent ID: 32183c44-363a-a028-a3d9-390b99bffc8b
* Content: [Create invitation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/invitation-post?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/invitation-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/invitation-post.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tfurstms** [comment]
Can we add a comment about this issue on the [Azure Active Directory - B2B - Guest User FAQ](https://docs.microsoft.com/en-us/azure/active-directory/b2b/faq) - Thanks!

**Comment by elisolMS** [comment]
B2B doesn't need the external user's UPN, just their email address.  Under the covers, we can make the connection to their account even if the UPN is different.
