### ISSUE TITLE
Microsoft Graph me/people will not list contacts, only supports querying (searching) for non-admin

### ISSUE THREAD

**Issue by linuxexp** [microsoftgraph/microsoft-graph-docs#7326]
However, I noticed a strange behavior. For non-admin O365 a/c or individual O365 a/c the simple GET call to https://graph.microsoft.com/v1.0/me/people/ will return an empty result, as per the documentation it should return all contacts paginated. However, If I do a $search query, the matches are returned.

It can be reproed on https://developer.microsoft.com/en-us/graph/graph-explorer/preview

I am using `People.Read` permission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f2936c0-5bfb-5bb9-3641-d5ff68c13982
* Version Independent ID: 28758a37-e96d-67e3-c48c-92f5064d477a
* Content: [List people - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-people?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-list-people.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-people.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by linuxexp** [comment]
`me/people` without the search query

<img width="1433" alt="Screenshot 2020-03-10 at 11 31 47 PM" src="https://user-images.githubusercontent.com/1223189/76345061-b1bcbf00-6328-11ea-9265-b5a0bb07b352.png">

`me/people` with the search query
<img width="1425" alt="Screenshot 2020-03-10 at 11 32 13 PM" src="https://user-images.githubusercontent.com/1223189/76345086-bed9ae00-6328-11ea-9476-752fdec046a1.png">

**Comment by PeterNjorogeMS** [comment]
@linuxexp kindly confirm if this is still an issue, I tried out https://graph.microsoft.com/v1.0/me/people/ and it work well.

**Comment by PeterNjorogeMS** [comment]
@linuxexp I tried to repo the issue and it works for me, I will go ahead and close this issue. If this comes up again kindly report it again.
