### ISSUE TITLE
app-only support for graph api planner tasks

### ISSUE THREAD

**Issue by Masood10** [microsoftgraph/microsoft-graph-docs#733]
I have checked and found out that app-only authentication is not supported for the graph api beta version planner tasks? will you allow this feature in near future?

**Comment by yinaa** [comment]
Yes, this is functionality in the roadmap, in the meantime, we opened a user voice request that you can track: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17721166-app-only-support-for-task-api

**Comment by jselamy** [comment]
Hi,

There' s already a similar opened user voice request on that matter... Shouldn't be regroup in one ?
[Here](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17719684-allow-access-to-planner-using-client-credentials-f)

It is in the roadmap ? Is there an ETA when we can expected it ? Or an alternative way ?

Regards.
