### ISSUE TITLE
Team not visible for owner

### ISSUE THREAD

**Issue by dico** [microsoftgraph/microsoft-graph-docs#7336]
[Enter feedback here]
We have an automated process for creating a team in Teams with the API. The team is first created, then owner is added.

All works and looks good in the Admincenter for Teams where team, owner and permissions are correct - but the team does not always show in Teams for the owner. This bug occurs maybe 50% of the times.

To fix this issue, we have to:
1. Login to admincenter for Teams.
2. Add a random member and set that member as owner (as you can't remove the only owner that where created by the API).
3. Set the actual owner as member and back to owner.
4. Delete the random member created in step 2.

When this is done, the actual owner is presented with a popup in Teams where he/she got access to a new team and works.

We are getting request from our users where teams are missing from one week ago to several months ago, so this is not a timing issue. As this also works fine about 50% of the time and it looks correct in the admincenter when it's not working, this have to be some kind of bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8c3174-470e-6bd6-0445-eb95526e85ea
* Version Independent ID: bb1a9ace-6ef2-ddef-b6d1-999a891697ab
* Content: [Add group owner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MohamedSattar** [comment]
We've the same issue, any luck of a solution or a workaround

**Comment by yyuank** [comment]
Thanks for reporting. This sounds like a service issue. Please file a support case with Teams, if similar behavior continues.

**Comment by JustinRustin** [comment]
Hi @dico & @MohamedSattar,
We were using the same method you have described and we had the same issues. We use a service account to do the actions to create the group and add the requesting user as the owner and member of the group and then create the team. We were finding issue rates consistently of 20-50% when our app would do the following:
1. create the group (using /v1.0/group)
2. add a user as a member (/v1.0/groups/<id>/members/)
3. add the owner (/v1.0/groups/<id>/owners)
4. create the Team (/v1.0/groups/<id>/team)

We changed our method to instead: 
1. create the group WITH the owner and member at the time of creation (v1.0/groups) using:  "owners@odata.bind": [ "https://graph.microsoft.com/v1.0/users('userId')" ]
"members@odata.bind": [ "https://graph.microsoft.com/v1.0/users('userId')" ]
2. then create the Team from that group (/v1.0/groups/<id>/team)
 
Using the new method we’ve found 100% creation success rate for now. We will soon be switching from using a Service Account to this work to use app permissions instead.
