### ISSUE TITLE
Incoherence in endpoints

### ISSUE THREAD

**Issue by EmilienCourt** [microsoftgraph/microsoft-graph-docs#7337]
Hi,
There is some incoherence in the endpoints regarding the provisioning logs.
[This page](https://docs.microsoft.com/en-us/graph/api/provisioningobjectsummary-list?view=graph-rest-beta&tabs=http#http-request) refers to GET /auditLogs/provisioning whereas [this page](https://docs.microsoft.com/en-us/graph/api/resources/azure-ad-auditlog-overview?view=graph-rest-beta#what-can-i-do-with-audit-log-apis-in-microsoft-graph) will refer to GET /auditLogs/directoryProvisioning.

What's the right endpoint ?

Regards,
Emilien

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d2181d9-af30-448f-4d3b-893de615e28e
* Version Independent ID: 54eb275d-2d8c-c2ab-57a5-d5f4177a6a69
* Content: [List provisioningObjectSummary - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/provisioningobjectsummary-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/provisioningobjectsummary-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/provisioningobjectsummary-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ArvindHarinder1** [comment]
PR to fix. https://github.com/microsoftgraph/microsoft-graph-docs/pull/7953  #please-close
