### ISSUE TITLE
How to delete events without send cancelation

### ISSUE THREAD

**Issue by atiedemann** [microsoftgraph/microsoft-graph-docs#7339]
When I delete an event in my calendar through ms graph it will send a cancelation to users that are invited to this event. Is this possible to delete events without sending this message?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9265c344-d87a-cbbe-3dec-90feafc017ca
* Version Independent ID: 47893faf-f604-8a75-4e1f-663722a89631
* Content: [Delete event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-delete?view=graph-rest-1.0&tabs=http&source=docs#feedback)
* Content Source: [api-reference/v1.0/api/event-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-delete.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
In case of eventUpdate there is a property 'isDraft' introduced in Graph beta that provides ability to control if e-mail notification to be sent or not in case of eventUpdate.

However this property is not extended for 'createEvent' or 'deleteEvent'.

@JuForan  @crchung-MSFT can comment on if there is plan to extend 'isDraft' property to the above methods.

**Comment by JuForan** [comment]
Correct - this is a principle that we have currently in calendar that the organizer and attendees should all see the same state, details, etc. of a meeting. So it is not possible to delete (effectively cancelling) a meeting that you organized while leaving it on attendee's calendars and not notifying them that the meeting is cancelled.

**Comment by Harini84** [comment]
Thank you @JuForan  for confirmation and @angelgolfer-ms for updating he documentation.

**Comment by angelgolfer-ms** [comment]
You're welcome, harini84.
@atiedemann , thank you for your question. The doc clarification is in PR #7595 . and will be published within the next day. Hopefully that will help other customers in the future.

**Comment by atiedemann** [comment]
@angelgolfer-ms Thanks for your feedback. I will start today the next actions and test if it is working.

**Comment by atiedemann** [comment]
Hello @all, 
so I set the isDraft property to true and my next step is delete event, but the graph system send a cancel meeting notification message to the attendees.

Background: I create a powerShell script to purge all items from a mailbox through ms graph and this is the last thing that makes me trouble
