### ISSUE TITLE
Beta User list applications broken

### ISSUE THREAD

**Issue by chrisMYchen** [microsoftgraph/microsoft-graph-docs#7344]
Neither 
GET https://graph.microsoft.com/beta/users/{id}/teamwork/installedApps
Nor
GET https://graph.microsoft.com/beta/users/{id}/teamwork/installedApps?$expand=teamsAppDefinition

endpoints work when testing with my own credentials. I tried these requests via Postman with auth headers working properly for other requests, and also via the node sdk. The demo TRY IT also doesn't work on this page. 
The response I get is:
```
{
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": XXX,
      "date": XXX
    }
  }
}
```
How can I resolve this?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27e0c7db-a498-3c5b-f414-c7edb352b71a
* Version Independent ID: 957eb16a-547f-b7f4-5871-c2d64e1446db
* Content: [List apps installed for user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list-teamsappinstallation?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-list-teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list-teamsappinstallation.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
@chrisMYchen , we tried at our end and observed that both the endpoints are working fine.
https://docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&tabs=http
