### ISSUE TITLE
What is the actual behavior of the maxpagesize Prefer header?

### ISSUE THREAD

**Issue by smotti** [microsoftgraph/microsoft-graph-docs#7352]
It seems like that this page size is being ignored, especially for recurring events that don't have an end date (recurrence count).
This results in thousands of events being returned per page instead of the requested amount by the specified maxpagesize in the header.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da37d83f-dd2b-dd85-eb5d-75208e26412d
* Version Independent ID: aa5f5279-bec8-fe6e-ab1b-8dc87f2ed688
* Content: [Get incremental changes to events in a calendar view  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-events?tabs=http)
* Content Source: [concepts/delta-query-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-events.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @smotti can you provide an example of the request you are trying please?

**Comment by smotti** [comment]
@baywet
url = https://graph.microsoft.com/v1.0/me/calendarView/delta?$deltatoken=R0usmcFuQtZdtpk4
headers = {'Prefer': 'odata.maxpagesize=2, odata.track-changes'}
response = session.get(url, headers=headers)   # session being a requests-oauthlib OAuth2Session

The response only shows that odata.track-changes was applied.

**Comment by baywet** [comment]
Thanks for the additional information.
I took time to try to reproduce the issue on my dev tenant and the service is behaving fine.
It might be tenant specific, I suggest you open a support ticket.
