### ISSUE TITLE
Is it possible to impersonate a user logged in, as an Azure AD Global Administrator?

### ISSUE THREAD

**Issue by samuel27m** [microsoftgraph/microsoft-graph-docs#7357]
Is it possible to impersonate a user logged in, as an Azure AD Global Administrator? We want for admins to be able to log in as the users in our web application that integrates with Azure B2C login.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service#feedback)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
No, Azure AD does not offer the capability for an administrator to sign in as another user.
