### ISSUE TITLE
displayName not updating

### ISSUE THREAD

**Issue by dbaldacchino** [microsoftgraph/microsoft-graph-docs#7360]
I am trying to update the channel name by supplying the json payload {"displayName": "&lt;string&gt;"} and am receiving a 204 response. Yet the channel name is not updating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b6b6f3b-3f50-04ff-e83a-2dae34e7020d
* Version Independent ID: ddfb266a-a674-20fb-4956-16767ddb6035
* Content: [Update team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dbaldacchino** [comment]
Turns out you can update these properties from the Group object (https://docs.microsoft.com/en-us/graph/api/group-update?view=graph-rest-beta&tabs=http). Would be nice to reference this in the documentation since these properties do show up in the Teams object as well (https://docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta)

**Comment by anandab-gt** [comment]
@dbaldacchino  - you should be able to update the displayName  using PATCH /teams/{id}, can you try doing GET after update and see whether its updated or not. I just tried and was able to do so.

**Comment by dbaldacchino** [comment]
I tested this method as well and it works. Thanks @anandab-gt
