### ISSUE TITLE
Examples in kotlin

### ISSUE THREAD

**Issue by RoarGronmo** [microsoftgraph/microsoft-graph-docs#7362]
In android kotlin is now the preferred language, could you please add a kotlin tab on the examples in use of the APIs ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview#feedback)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@RoarGronmo thanks for your feedback, we'll evaluate the possibility to do that. Thanks.
