### ISSUE TITLE
Add KeySets is not working.

### ISSUE THREAD

**Issue by Norrch2** [microsoftgraph/microsoft-graph-docs#7367]
I have followed this example and it keeps returning "problem with keyset" 

Please update the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c99fbbf3-8960-f54e-5d2c-8f0d90616172
* Version Independent ID: cbda8eca-8961-9b81-dac7-6cff063cfb1a
* Content: [Create trustFrameworkKeySet - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/trustframework-post-keysets?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/trustframework-post-keysets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/trustframework-post-keysets.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @valnav
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Norrch2** [comment]
Forgive me, it appears that there is already a bug opened for this. https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/67

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
