### ISSUE TITLE
C# example has invalid filter

### ISSUE THREAD

**Issue by NotAlexx** [microsoftgraph/microsoft-graph-docs#7370]
There is a comma at the end of the C# example that shouldnt be there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d56f62-91d1-6e41-3d8e-c167c2d2d512
* Version Independent ID: af9347f9-6471-3066-3dd7-9c2cfb1f70ec
* Content: [List accessReviews - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accessreview-list?view=graph-rest-beta&tabs=csharp#feedback)
* Content Source: [api-reference/beta/api/accessreview-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accessreview-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Noting that this version of the access review API is deprecated.
