### ISSUE TITLE
Change Password is not documented

### ISSUE THREAD

**Issue by vikrantrajput007** [microsoftgraph/microsoft-graph-docs#7376]
If we refer to Graph SDK it has changePassword Method which makes a post-call. graph.microsoft.com/v1.0/me/changePassword.

C#-&gt;await graphClient.Me.ChangePassword("currentPassword", "newPassword").Request().PostAsync();

I am able to find the document here ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8446021-6786-c54c-066f-d99ba4644312
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/user.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
This API does need documenting, but we'll be working on a strategy to deprecate this API in favor of a new changePassword API that will also be capable of automatically writing back to on-premises IF the organization masters their passwords on-premises.

**Comment by FaithOmbongi** [comment]
No updates identified for the page. Closing the issue.

**Comment by dkershaw10** [comment]
@FaithOmbongi This API needs to be documented, so that we can properly deprecate it.  It's supported in the SDK.
We got a support case on this too.

**Comment by FaithOmbongi** [comment]
@dkershaw10 Raised a PR to surface this API. Closing the issue.
