### ISSUE TITLE
Retrieve recent files for Teams/Group

### ISSUE THREAD

**Issue by litthatpen** [microsoftgraph/microsoft-graph-docs#7377]
Is there an available API that could retrieve recent files modified in MS Teams. 
(Functionality is similar to the MS Teams Website, https://teams.microsoft.com/_#/my/file-aggregate)

For Example:
In https://teams.microsoft.com/_#/my/file-aggregate,
https://teams.microsoft.com/api/mt/apac/beta/teams/recent/files/aggregatefiles is used to get recent modified files by MS Teams. This request can be done in POSTMAN with access token generated in the MS Teams WebPage. access token used in this case is not documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18dfd099-0d73-55e4-56ec-d9129b83aa07
* Version Independent ID: 5705a946-2c25-0d04-a297-01ccb21d7284
* Content: [List the contents of a folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-list-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-list-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by Subhasish-msft** [comment]
@litthatpen , There is a bet Graph API to get recent files. See if it helps.
https://docs.microsoft.com/en-us/graph/api/drive-recent?view=graph-rest-beta&tabs=http

**Comment by litthatpen** [comment]
The v1 and beta have similar definition. "Get recent files to drives user
have access." I tried v1 so I assume beta is the same.

**Comment by Subhasish-msft** [comment]
Yes, you should use v1 version.

**Comment by sgsmittal226** [comment]
@saurabhsahmsft I used this same documented api
https://docs.microsoft.com/en-us/graph/api/drive-recent?view=graph-rest-beta&tabs=http

but this one and the files I can see in teams recent file are different (i.e not all files are returned) and this is not same as aggregateFiles
