### ISSUE TITLE
NextLink Paging is giving Bad request for some of the Channels 

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#7382]
https://graph.microsoft.com/beta/teams/{0}/channels/{1}/messages/delta?$deltaToken=latest

gave me deltaLink and some of them gave me nextLink so I am doing paging. But every time query next link I am getting 
{
    "error": {
        "code": "BadRequest",
        "message": "Parameter 'DeltaToken' not supported for this request.",
        "innerError": {
            "request-id": "2c246799-d7a0-4d60-a587-f71092377cd4",
            "date": "2020-03-13T22:52:50"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fa912d-43d1-099b-44d5-fdcdaae00db7
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessages: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by xaurx** [comment]
We are also having the same issue. Any updates on it please?

**Comment by HunaidHanfee-MSFT** [comment]
Could you please try again and check if still facing any issue? Please try to do it with _v1.0_ if you face any issue in _beta_.
