### ISSUE TITLE
Create team sends back "BadGateway 502"

### ISSUE THREAD

**Issue by kincho-guerrero** [microsoftgraph/microsoft-graph-docs#7388]
Create team method isn't working anymore, tried both with   
"template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('standard')" or
 "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates/standard" 

Tried from code and from Graph Explorer with the examples in the docs and won't work anymore.
Both of them send a 502 Bad Gateway response as the following:

{
    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "request-id": "38e43708-5a9e-45b2-a2c1-f57831b1fa13",
            "date": "2020-03-16T00:37:56"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by desusai7** [comment]
@nkramer  @kincho-guerrero  I am also facing the same issue, have you got it resolved ?

**Comment by SanderSiep** [comment]
Hi there @nkramer and @kincho-guerrero. We also see this kind of errors popping up once in a while. Yesterday created 5 teams using the same Graph API and at 2 of them got this Bad Gateway 502 error.
There is even a side effect to this, while in a retry of the same Graph API query we get 2 times the Gateway timeout 504 errors and at the background it is creating a team, but we really don`t know the state of it, can we use it, or do we need to remove it and try again?

**Comment by desusai7** [comment]
@SanderSiep  Yeah Sander i too faced the same side effect of getting a bad gateway error but the team gets created and can you please tell me what are the differences between those 3 teams which were created successfully and the 2 teams which were failed !

**Comment by SanderSiep** [comment]
Hi @desusai7, there is not much difference between those teams. The only difference is the title and name and in one Team another Owner. I think this issues pops-up once in a while and has no dependency to the parameters specified. We are now adding a check to see if the group and site collection is created and then continue the flow.

**Comment by desusai7** [comment]
Hey,Hi and yes i too found the teams thus created are working and if you find any alternate solution to it please let me know :)

**Comment by anandab-gt** [comment]
@kincho-guerrero - it has been long time since you posted this query but i wanted to check if you are still facing this issue, if yes can you share the request ID.  (This API to v1 end point as well.)

**Comment by anandab-gt** [comment]
closing this issue, in case you feel your problem is not solved either reopen this issue or create a new issue.
