### ISSUE TITLE
Is documentation for messages/createReply & createForward incorrect?

### ISSUE THREAD

**Issue by rexxmagnus** [microsoftgraph/microsoft-graph-docs#739]
I have attempted to create a reply draft message both manually using Microsoft Graph Explorer and using my own C# calls. In each case the "comment" property seems to be ignored and a reply draft is created with only the quoted text from the original message - the comment property has no effect.

Is the documentation for this function correct, or is there a bug in the api?

**Comment by rexxmagnus** [comment]
This also appears to be happening for createForward - none of the properties are used to set recipients or the body.

**Comment by angelgolfer-ms** [comment]
@rexxmagnus , thanks for bringing up this issue. I am able to reproduce it and have opened a tracking bug for the product team to investigate. I also noted this issue in the Known issues topic for the time being.
