### ISSUE TITLE
Bug: List private channel members returns all team members

### ISSUE THREAD

**Issue by abdulkareemnalband** [microsoftgraph/microsoft-graph-docs#7390]
## Bug
Query for private channel members is returning all team members

### Expected

Query for private channels should return only people who are added to that channel

### Details

when called following URL
```sh
https://graph.microsoft.com/beta/teams/${teamId}/channels/${privateChannelId}/members
```

It returned all team members instead of only channel members

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c0f5d6-3a9f-3818-d049-314aa8ec7b93
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abdulkareemnalband** [comment]
After further investigation this occurs only for small amount of time, just after channel creation, 
If given enough time API returns correct data.

It looks like provisioning issue

**Comment by Prasad-MSFT** [comment]
Happy to hear that it got resolved. 
We also tried to run the query `https://graph.microsoft.com/beta/teams/{teamId}/channels/{privateChannelId}/members`
using Graph explorer and got members of that particular private channel only.
Thanks !
