### ISSUE TITLE
Use Beta API in Production

### ISSUE THREAD

**Issue by smahajan1989** [microsoftgraph/microsoft-graph-docs#7395]
Hey there,

We are trying to use Microsoft Graph API to add users to B2C. We noticed that a lot of functionality that we would like to leverage(for example, using Identities) is only available in beta version; however, it is recommended not to use beta in production. We don't want to use the Azure AD graph and want to leverage technology that Microsoft sees as their future. Since beta has been going on for 2 years, is it okay to use in production. Let me know your feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28f291cb-b55b-4b55-c42a-cec61e5c4384
* Version Independent ID: afc8208d-990b-098f-0508-fcd5745d35e6
* Content: [Microsoft Graph beta endpoint reference - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/overview?toc=.%2Fref%2Ftoc.json&view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/overview.md)
* Product: **non-product-specific**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fabio770** [comment]
Hello @smahajan1989, I was wondering the same thing. I would like to know if I can develop solutions using the Beta version of Microsoft Graph API.

**Comment by ashoksubedi1** [comment]
Hello friends, I am using some of the beta api for my App for example changing the pic of Teams and sending Chat Message into the Channel. I know it is not recommended but I had no other choice. What I do is keep looking at the Microsoft Graph API changelog and keep myself updated on changes. Also, I have some kind of powershell script ready if any of the beta endpoints does not make it to V1.0

**Comment by Alexiserges** [comment]
Hello Friend, I am  working on data analytics project, I still struggling how can I use X-API to extract the data from Online system management. 
How to use X-API from specific frame work to extract the data?

**Comment by angelgolfer-ms** [comment]
Hi, if you would like to see certain API sets to become available in v1.0, please check if there are any similar requests in [User Voice ](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) and vote for it, or if there aren't, post a suggestion there.

@Alexiserges , this Github issues site is for Microsoft Graph documentation issues. If you have a question for a specific Microsoft Graph API, please post on StackOverflow.

Thank you!
