### ISSUE TITLE
The addIns property in the application resource type is a collection 

### ISSUE THREAD

**Issue by Tiagojaduarte** [microsoftgraph/microsoft-graph-docs#7396]
In this page the addIns property is not described as a collection but in fact it is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f54172c8-c149-8002-b172-5d1d286177f0
* Version Independent ID: c23c0d2f-5f70-e67d-9068-99e660126fd0
* Content: [application resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0#properties)
* Content Source: [api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/application.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
This appears to have been fixed:

addIns | addIn collection | Defines custom behavior that a consuming service can use to call an app in specific contexts. For example, applications that can render file streams may set the addIns property for its "FileHandler" functionality. This will let services like Microsoft 365 call the application in the context of a document the user is working on.

Closing the issue.
