### ISSUE TITLE
getByIds is under the directoryObjects resource, not directory

### ISSUE THREAD

**Issue by bemartin** [microsoftgraph/microsoft-graph-docs#7398]
Seems that the table is wrong indicating the getByIds can be invoked on directory when it needs to be used on directoryObjects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 173a076e-666a-b5f5-2953-f585a3fb5d05
* Version Independent ID: e488a4b9-89e4-d4fb-b4fe-524efbabadea
* Content: [Method differences between Azure AD and Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-method-differences?source=docs#feedback)
* Content Source: [concepts/migrate-azure-ad-graph-method-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/migrate-azure-ad-graph-method-differences.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
#8618 should resolve this.  Thanks for filing the issue

**Comment by dkershaw10** [comment]
Fixed with #8618
