### ISSUE TITLE
How does one obtain a list of "Meet now" events?

### ISSUE THREAD

**Issue by MushyMiddle** [microsoftgraph/microsoft-graph-docs#7400]
In the normal channel stream, one sees both messages and meetings, particularly those of the "Meet now" variety.  For scheduled events, getting the events is pretty clear, but for "Meet now" events...?  They don't appear as messages (perhaps reasonably), but they can have replies, so presumably that have some kind of representation in the API so those replies can be harvested?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nkramer** [comment]
Do you know the github handles for the calling & meetings team?

**Comment by jthake-msft** [comment]
@ananmishr  is the PM on this.
