### ISSUE TITLE
Device permissions incomplete

### ISSUE THREAD

**Issue by eketo-msft** [microsoftgraph/microsoft-graph-docs#7404]
Device.Read.All is available as in Azure Portal for MS Graph but not doc'd here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference?view=graph-rest-1.0&source=docs#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
Better late than never, I suppose: I've updated the documentation to include the missing permission. Thanks for the heads up!
