### ISSUE TITLE
Missing app-only permissions

### ISSUE THREAD

**Issue by eketo-msft** [microsoftgraph/microsoft-graph-docs#7405]
Device.ReadWrite.All should be able to delete devices, but it says Unsupported under permissions.  Is there something missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a6b91f-5c3a-d92f-a572-fa47ff846e6b
* Version Independent ID: bcf37011-94d5-0dc3-1cc2-d00da6ab9758
* Content: [Delete device - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/device-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/device-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/device-delete.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
**Device.ReadWrite.All** permission does not allow for device creation, device deletion, or update of device alternative security identifiers.
No updates identified for the page for now. Closing the issue.
