### ISSUE TITLE
GraphServiceClient doesn't seem to have Applications property as in the sample

### ISSUE THREAD

**Issue by Adriana171** [microsoftgraph/microsoft-graph-docs#7415]
I am not able to find the Applications object on the GraphServiceClient in either the released or the beta version of the Java SDK.

https://github.com/microsoftgraph/msgraph-sdk-java/tree/dev/src/main/java/com/microsoft/graph/requests/extensions

A similar issue was opened for the .NET project -&gt; https://github.com/microsoftgraph/microsoft-graph-docs/issues/5279

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @Adriana171 
Thanks for reaching out and thanks for the patience.
I just replied to a very similar issue on #8368 
Closing.
