### ISSUE TITLE
Can we move the system facet remark 

### ISSUE THREAD

**Issue by johnnliu** [microsoftgraph/microsoft-graph-docs#7419]
Since the $select=system facets are hidden like a "scope" (filter).  Could we move this section way up under "Permissions" since it's kind of not documented anywhere else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5f5acff-375b-fd68-530d-3d3c829665c1
* Version Independent ID: e67507c5-25d0-642e-f040-6b386de93d23
* Content: [List the SharePoint lists in a site - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/list-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/list-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/list-list.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as the doc has been updated
