### ISSUE TITLE
Production readiness 

### ISSUE THREAD

**Issue by milosc** [microsoftgraph/microsoft-graph-docs#7422]
Any insights when we can use this features in production?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a591171a-3447-e4f1-2505-e38cf5a9c1ee
* Version Independent ID: a1ccb913-8d51-1445-e81f-a4f100a495e3
* Content: [onlineMeeting resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/onlinemeeting.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @milosc the online meeting APIs are in the v1.0 endpoint as well and ready to use for production. View the same resources page for v1.0 [here](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0).
