### ISSUE TITLE
This page needs clarification on the URL needed for channel members

### ISSUE THREAD

**Issue by MushyMiddle** [microsoftgraph/microsoft-graph-docs#7424]
...or please create a page specific to list/get channel members - perhaps better.  In any case, the URL needed:  /teams/{id}/channels/{id}/members

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c0f5d6-3a9f-3818-d049-314aa8ec7b93
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-gt** [comment]
pls check - https://docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0

**Comment by MushyMiddle** [comment]
Looks good - thanks.

**Comment by MushyMiddle** [comment]
Sorry - please close.
