### ISSUE TITLE
Search across different mailboxes using Query API

### ISSUE THREAD

**Issue by akvadlamani** [microsoftgraph/microsoft-graph-docs#7425]
[Enter feedback here]
One of the limitations is "You can only access a user’s own mailbox. Searching delegated mailboxes is not supported." Wanted to confirm this behavior with application permissions as well? If yes, any plans to open it up in the future?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d55d194-da7b-7f76-4ef0-b6d84a3dccc0
* Version Independent ID: 9139b092-1446-2f30-7cdb-1b41474d9f41
* Content: [Use the Microsoft Search API to query data - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/search-api-overview.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmoreau** [comment]
I confirm this limitation is valid even if you have the application permissions.
Expanding search to delegated mailboxes in not on our roadmap.

**Comment by akvadlamani** [comment]
Thank you
