### ISSUE TITLE
Unable to add a planner tab via Teams to a newly created group

### ISSUE THREAD

**Issue by fzbm** [microsoftgraph/microsoft-graph-docs#7427]
When I create a group via the Graph C# library and add a Teams team to it, I'm unable to add a planner tab using the Teams client. The window just says "Failed to create the plan.".

```
var group = new Group
{
    DisplayName = "Planner Test",
    Description = "Test",
    MailNickname = "plannertest",
    MailEnabled = true,
    SecurityEnabled = false,
    GroupTypes = new[] { "Unified" }
};

Group addAsync = await client.Groups.Request().AddAsync(group);
```

![image](https://user-images.githubusercontent.com/52308785/77035509-2b9a1b80-69ad-11ea-9397-ebcccc0947d1.png)

I analyzed this a little bit and it might be related to the fact, that the call https://tasks.office.com/TasksApiV1/ResolveGroupsToPlansBatchedAsync just returns `NULL` for the requested ID. On Groups/Teams where I'm able to add such tab the call always returns a proper result.

![image](https://user-images.githubusercontent.com/52308785/77035290-8a12ca00-69ac-11ea-8601-f8862686bc69.png)

It seems to be fixed, after I open the group calendar in Outlook Web Access ... but this is not a functional workaround for automatically provisioned Groups/Teams.

Any ideas what could be the problem? I tested it with a `GraphServiceClient` using application and delegated permissions. Both with the same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Gousia-MSFT** [comment]
@fzbm Could you please confirm if you are the owner or a member of the team?

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have any queries here.
