### ISSUE TITLE
SendMail page should have information on possible error responses

### ISSUE THREAD

**Issue by mparq** [microsoftgraph/microsoft-graph-docs#7430]
Only the 202 success response case is mentioned today. I mainly want to differentiate between potentially transient error responses and permanent error responses, so I can handle them differently in my application code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
Here's a [list of error-codes](https://docs.microsoft.com/en-us/graph/errors) that can be encountered in Microsoft Graph and along with their description. I'm closing this issue with this information. Please re-open for any further clarifications.
