### ISSUE TITLE
How to fetch the list of call records for a given user/group/organization

### ISSUE THREAD

**Issue by gulfuroth** [microsoftgraph/microsoft-graph-docs#7433]
Hi,I see in the examples that this API returns the details of a given callRecord but, how do I get the list of call records for a given user/group/organization?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6259f0-9e69-493b-3158-614d11642312
* Version Independent ID: 08963ed9-21ee-773d-3532-75be9cd57e70
* Content: [Get callRecord - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/callrecords-callrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/callrecords-callrecord-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by WardWilmsen** [comment]
I'm also trying to fetch a list of all calls for the organization via an app-only token.

I provided the token with enough permissions as stated in the docs, but the following query is returning me a '404 - Not Found'

https://graph.microsoft.com/beta/communications/callRecords

After bouncing into this issue, I tried to subscribe onto the '/communications/callRecords' resource. But this API looks really unstable and is most of the time **not** firing an event when a teams call has been made. 

I noticed the subscription does never fire when a call has been 'missed'. It only fires sometimes when a call has been answered. 

Are you guys looking to support 'missed' calls with this webhook too?

**Comment by PrimeMoverBMT** [comment]
Hello Everyone

I'm also trying to fetch a attendee list for the university via postman [Microsoft Graph Environment]
have look my response 
Get - https://graph.microsoft.com/beta/communications/callRecords/{Group ID}
GroupID - team id created on MS teams

Response

{
  "error": {
    **_"code": "Forbidden",_**
    "message": "",
    "innerError": {
      "request-id": "************************",
      "date": "2020-03-27T06:23:41"
    }
  }
} 

please help us to resolve this


Regards
Narendra

**Comment by gulfuroth** [comment]
> I'm also trying to fetch a list of all calls for the organization via an app-only token.
> 
> I provided the token with enough permissions as stated in the docs, but the following query is returning me a '404 - Not Found'
> 
> https://graph.microsoft.com/beta/communications/callRecords
> 

AFAIK, /communicatios/callRecords by itself won't work, it requires a Call ID. So the tricky point is to get it as you mention. 

Were you able to call that endpoint with the IDs fetched via subscription that you mention below?

> After bouncing into this issue, I tried to subscribe onto the '/communications/callRecords' resource. But this API looks really unstable and is most of the time **not** firing an event when a teams call has been made.
> 
> I noticed the subscription does never fire when a teams call has been 'missed'. It only fires sometimes when a teams call has been answered.
> 
> Are you guys looking to support 'missed' teams calls with this webhook too?

I've tried to subscribe myself, but out of luck. 


I'm using postman, ngrok and a simple webservice to record subscription callbacks. 
My query to subscription API is
{
    "changeType": "created",
    "notificationUrl": "https://xxxx.ngrok.io",
    "resource": "/communications/callRecords",
    "expirationDateTime": "2020-03-31T16:59:45.9356913Z",
    "clientState": "secretClientValue",
    "latestSupportedTlsVersion": "v1_2"
}
And response: 
{
  "error": {
    "code": "ExtensionError",
    "message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: The request is not authorized for this user or application.]",
    "innerError": {
      "request-id": "xxxxxxxx",
      "date": "2020-03-3zxxx:14"
    }
  }
}

The same query  works perfectly for emails (just changing the resource). Needless to say that I have provided my app with all permissions in the ActiveDirectory management. 

I think my problem is  that, as  I'm not being able to log in using oauth2 and fetch a proper token, I'm using tokens from the GraphExplorer and those  don't hold  the  required  permissions.

**Comment by gulfuroth** [comment]
> Hello Everyone
> 
> I'm also trying to fetch a attendee list for the university via postman [Microsoft Graph Environment]
> have look my response
> Get - [https://graph.microsoft.com/beta/communications/callRecords/{Group](https://graph.microsoft.com/beta/communications/callRecords/%7BGroup) ID}
> GroupID - team id created on MS teams
> 
> Response
> 
> {
> "error": {
> **_"code": "Forbidden",_**
> "message": "",
> "innerError": {
> "request-id": "************************",
> "date": "2020-03-27T06:23:41"
> }
> }
> }
> 
> please help us to resolve this
> 
> Regards
> Narendra

This endpoint does not provide a list of calls, it's just for fecthing call details when you have the callID.

**Comment by hamzajeljeli95** [comment]
Ok, so i'am working on a solution which require this feature sadly :( .. Is there any endpoint that will allow me to fetch all the available Call Records within (let's say Last 7 days) without details ?

**Comment by stephenjust** [comment]
Unfortunately, there is no API to list call records at this time. It's on our backlog.

With respect to permission errors, make sure you are using an app-only token. This API does not support delegated (user-based) authentication.

**Comment by gulfuroth** [comment]
Thanks Stephen,

Please do prioritize this listing API, it makes the whole endpoint so much more useful. 

Thanks for the credentials hint! I managed to get a proper auth token using this workflow: 

https://docs.microsoft.com/en-us/graph/auth-v2-service

Then, with that token, the subscription went through: 

POST https://graph.microsoft.com/beta/subscriptions

{
    "changeType": "created",
    "notificationUrl": "https://XXXX.ngrok.io",
    "resource": "/communications/callRecords",
    "expirationDateTime": "2020-04-06T14:49:45.9356913Z",
    "clientState": "secretClientValue",
    "latestSupportedTlsVersion": "v1_2"
}
Response: 
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#subscriptions/$entity",
    "id": "xxxxx",
    "resource": "/communications/callRecords",
    "applicationId": "xxxx-975d-4daba6a79fd3",
    "changeType": "created",
    "clientState": "secretClientValue",
    "notificationUrl": "https://fd46xxxx.ngrok.io",
    "lifecycleNotificationUrl": null,
    "expirationDateTime": "2020-04-06T14:49:45.9356913Z",
    "creatorId": "xxxx-4ca6-a8c8-b6fe8feb429f",
    "includeProperties": null,
    "includeResourceData": null,
    "latestSupportedTlsVersion": "v1_2",
    "encryptionCertificate": null,
    "encryptionCertificateId": null
}

Sadly I'm not receiving any callbacks during or after calls. Any hints why this might be happening?

**Comment by benyafai** [comment]
> **UPDATE**: Callbacks started appearing. It just take hours for them to arrive.  We  made like 7 calls (P2p/group) and I started receiving notifications 3-4 hours later, not sure if this is the expected behaviour. 

I too found that the subscription took time to kick in, I also received records for calls prior to subscribing so I think it goes back for a certain period which is unexpected but welcome.

**Comment by stephenjust** [comment]
@benyafai This latency is currently expected. We're working on driving this down to be < 1 hour, with the majority arriving in a few minutes after the call ends. The delays should be similar to what is observed in Call Analytics and Call Quality Dashboard, since it's all fed from the same pipeline.

When you subscribe, it takes a couple of minutes for the subscription to take effect, but you should start seeing all calls that flow through the pipeline as of that point in time when your subscription is picked up by our workers. We've got some work on our backlog to try to eliminate this delay.

If our pipeline is delayed, you'll see notifications for calls even if the call ended before you subscribed, if that call reaches our workers after your subscription is active.

**Comment by WardWilmsen** [comment]
> @benyafai This latency is currently expected. We're working on driving this down to be < 1 hour, with the majority arriving in a few minutes after the call ends. The delays should be similar to what is observed in Call Analytics and Call Quality Dashboard, since it's all fed from the same pipeline.
> 
> When you subscribe, it takes a couple of minutes for the subscription to take effect, but you should start seeing all calls that flow through the pipeline as of that point in time when your subscription is picked up by our workers. We've got some work on our backlog to try to eliminate this delay.
> 
> If our pipeline is delayed, you'll see notifications for calls even if the call ended before you subscribed, if that call reaches our workers after your subscription is active.

Any chance this API or any other API will be provided any time soon to check up missed calls too? Because I've been looking into this API which is serving it to the Teams client, but this seems to be resolved by a delegated Skype auth token. So no way to the same call as the Teams client does in an app only scénario I guess....

Any feedback on this topic? Would like to build a dashboard that includes all this information.

**Comment by ishan1089** [comment]
I am trying to subscribe myself, but getting error.

I'm using postman, ngrok and a webservice to record subscription callbacks.
My query to subscription API is
{
"changeType": "created",
"notificationUrl": "https://xxxx.ngrok.io",
"resource": "/communications/callRecords",
"expirationDateTime": "2020-04-11T14:49:45.9356913Z",
"clientState": "secretValue",
"latestSupportedTlsVersion": "v1_2"
}

Response is:
{
  "error": {
    "code": "InvalidRequest",
    "message": "Subscription validation request failed. Notification endpoint must respond with 200 OK to validation request.",
    "innerError": {
      "request-id": "e7bdd469-870a-492a-acbe-c9a46c81afb2",
      "date": "2020-04-09T05:13:02"
    }
  }
}

Tried subscribing through web service as well but still the same error.

**Comment by gulfuroth** [comment]
Hi, the webservice needs to follow a simple rule (returning one of the parameters as part of the response). I did it with Node/Express, it's just a few lines: 

-----
'use strict';

const express = require('express');
const bodyParser = require('body-parser');
const app = express().use(bodyParser.json()); // creates http server

app.listen(7770, () => console.log('[CallSusbcription ] Webhook is listening'));

app.get('/', (req, res) => {
    // check if verification token exists
    if (req.query.token !== undefined) {
        return res.sendStatus(401);
    }

    // return challenge
    return res.end(req.query.challenge);
});

app.post('/', (req, res) => {
  
    // print request body
    console.log(req.body);
    res.set('Content-Type', 'text/html');


    // return the same validation token received
   
    res.send(req.query.validationToken);
});

**Comment by gulfuroth** [comment]
BTW, for those in need of getting some test callRecord IDs for a given user, you can get them manually in the Teams Admin Center/Users/Call History. In fact you'll be able to see there all the info retrieved by the CallRecord API, so it's a good way to validate the info you'll be getting without having to do a full integration.

**Comment by djain1109** [comment]
In the get API https://graph.microsoft.com/beta/communications/callRecords/{ID} what should be ID value here ?

**Comment by benyafai** [comment]
Hi @djain1109,
You will need to subscribe to callRecord events as per https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions.

When your app receives webhooks from the subscription you will be given info such as the ID to poll using the API.

**Comment by gulfuroth** [comment]
@djain1109 @benyafai I recently discovered a workaround. If you have admin rights to get into the MS Teams admin center ( https://admin.teams.microsoft.com/dashboard )  you can get the list of calls a user has done, with IDs and basically most of the info that this endpoint provides.

**Comment by ryan-at-werk** [comment]
@gulfuroth / @benyafai 

I was able to create a subscription:

> {"@odata.context":"https://graph.microsoft.com/beta/$metadata#subscriptions/$entity","id":"3208cc6d-70b5-472b-b1f2-0f28f7272a80","resource":"/communications/callRecords","applicationId":"7f59f664-491a-45e1-8bb4-14b4d7dbc333","changeType":"created","clientState":"someString","notificationUrl":"https://mydomain.ca/callRecords/myEndpoint.php","lifecycleNotificationUrl":null,"expirationDateTime":"2020-05-13T16:59:45.9356913Z","creatorId":"1f1f3743-dac0-443e-8f5c-dc309976ca04","includeProperties":null,"includeResourceData":null,"latestSupportedTlsVersion":"v1_2","encryptionCertificate":null,"encryptionCertificateId":null}

I'm seeing hits to my endpoint but where is the ID?  I've waited a day but there seems to be no POST nor GET data:

> [Wed May 13 09:23:08.674276 2020] [pid 49787] [client xxx.xxx.xxx.xxx:32192] POST_VARIABLES:Array\n(\n)\n
> [Wed May 13 09:23:08.674272 2020] [pid 49787] [client xxx.xxx.xxx.xxx:32192] GET_Variables:Array\n(\n)\n
> [Wed May 13 09:23:08.674264 2020] [pid 49787] [client xxx.xxx.xxx.xxx:32192] Server_Variables:Array\n(\n    [HTTPS] => on\n    [SSL_TLS_SNI] =>mydomain.ca\n    [CONTENT_TYPE] => application/json; charset=utf-8\n    [HTTP_HOST] => mydomain.ca\n    [CONTENT_LENGTH] => 455\n    [HTTP_CONNECTION] => Keep-Alive\n    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\n    [SERVER_SIGNATURE] => <address>Apache/2.4.18 (Ubuntu) Server at mydomain.ca Port 443</address>\n\n    [SERVER_SOFTWARE] => Apache/2.4.18 (Ubuntu)\n    [SERVER_NAME] => mydomain.ca\n    [SERVER_ADDR] => xxx.xxx.xxx.xxx\n    [SERVER_PORT] => 443\n    [REMOTE_ADDR] => xxx.xxx.xxx.xxx\n    [DOCUMENT_ROOT] => /var/www/mydocroot\n    [REQUEST_SCHEME] => https\n    [CONTEXT_PREFIX] => \n    [CONTEXT_DOCUMENT_ROOT] => /var/www/mydocroot\n    [SERVER_ADMIN] => address@mydomain.ca\n    [SCRIPT_FILENAME] => /var/www/mydocroot/callRecords/myEndpoint.php\n    [REMOTE_PORT] => 32192\n    [GATEWAY_INTERFACE] => CGI/1.1\n    [SERVER_PROTOCOL] => HTTP/1.1\n    [REQUEST_METHOD] => POST\n    [QUERY_STRING] => \n    [REQUEST_URI] => /callRecords/myEndpoint.php\n    [SCRIPT_NAME] => /callRecords/myEndpoint.php\n    [PHP_SELF] => /callRecords/myEndpoint.php\n    [REQUEST_TIME_FLOAT] => 1589376188.673\n    [REQUEST_TIME] => 1589376188\n)\n
