### ISSUE TITLE
Bug in listing channel members

### ISSUE THREAD

**Issue by MushyMiddle** [microsoftgraph/microsoft-graph-docs#7434]
Posting this here, as there is not yet a page for List channel members.  If a Team owner is blocked (e.g. leaves the company), even if s/he is not the only owner of the Team, some of the channel APIs will fail with (403):

{  "error": {    "code": "Forbidden",    "message": "Failed to execute Skype backend request GetThreadRosterS2SRequest.",    "innerError": {      "request-id": "32adb90e-5f6d-46c2-b8f7-77f39a28cbd8",      "date": "2020-03-19T14:58:11"    }  }}

The workaround is to remove the blocked user from Team ownership, and the API call will succeed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c0f5d6-3a9f-3818-d049-314aa8ec7b93
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by MushyMiddle** [comment]
...and to be clear, the blocked user/owner was a normal user; the user executing the API was a global admin.

**Comment by jthake-msft** [comment]
@nkramer  can you please update the docs to change the yaml auth for your docs now that Andrew is in another team too ? Thanks.

**Comment by answersamir** [comment]
I am able to reproduce this issue in the following scenarios as well:
1. Team is created without any owner. 
2. A non admin  user is assigned as owner of a team.
