### ISSUE TITLE
Ability to set accessTokenAcceptedVersion with PowerShell, Rest api etc.

### ISSUE THREAD

**Issue by LockTar** [microsoftgraph/microsoft-graph-docs#7435]
We want to set the accessTokenAcceptedVersion of app registration automatically. I've search in Azure AD Graph, Microsoft Graph, CLI etc. No way to set it. How can we do this?

Or is there a way that we can upload a manifest somewhere from code??
https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-app-manifest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c14af104-d60b-1a37-c36c-5282e521c06d
* Version Independent ID: c23c0d2f-5f70-e67d-9068-99e660126fd0
* Content: [application resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta&source=docs)
* Content Source: [api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/application.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
There is no property of that name associated with the application resource. No change identified for the page. Closing the issue.
