### ISSUE TITLE
Trying to update an User Office 365, assignedLicenses read only

### ISSUE THREAD

**Issue by branstraub** [microsoftgraph/microsoft-graph-docs#744]
The Api returns " "message": "Property 'assignedLicenses' is read-only and cannot be set.","

Is there a way to assign licenses to an user when creating or updating the user?
In the documentation of the API, the patch method -> https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_update the following field is available in the json body:

**assignedLicenses	assignedLicense collection   The licenses that are assigned to the user. Not nullable.**

Regards,

**Comment by peteski22** [comment]
I think the dotnet library is a bit misleading in that you can update a user's.. displayname for example. But not their assigned licenses, despite intellisense telling you it's get/set.

From `Microsoft.Graph.User`:

```
[JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "assignedLicenses", Required = Required.Default)]
public IEnumerable<AssignedLicense> AssignedLicenses { get; set; }

```
I'd assume that something like:

`await client.Users[userId].Request().UpdateAsync(userObjWithModifiedLicenses); `

Would be OK, obviously as the initial poster pointed out, you get an error that apparently it's read-only. The '**set**' on the property in the `User `class is misleading.
