### ISSUE TITLE
Few errors found on this document

### ISSUE THREAD

**Issue by JimmyLS** [microsoftgraph/microsoft-graph-docs#7444]
1. The HTTP method based on our testing should be "POST" instead of "PATCH", if we set to PATCH we got error messages like below:
"Specified HTTP method is not allowed for the request target."

2. A sample API should be one of below two based on my testing:
https://graph.microsoft.com/beta/servicePrincipals/{SPObjectID}/appRoleAssignments  
https://graph.microsoft.com/beta/servicePrincipals/{SPObjectID}/appRoleAssignedTo
The SPObjectId can be either Object ID of resource or source SP here.

3. While the article here said "Application Permission Type" is not supported, but based on my testing it can work if we assigned the Caller (SP) MS Graph app permission "AppRoleAssignment.ReadWrite.All". I've used below request command with AZ CLI:
az rest --method POST --uri "https://graph.microsoft.com/beta/servicePrincipals/778946fa-9eaf-44cf-8039-eeab88c18967/appRoleAssignedTo" \
        --header Content-Type=application/json \
        --body '{
          "principalId": "778946fa-9eaf-44cf-8039-eeab88c18967",
          "resourceId": "f4a70950-cfcb-4abe-a73e-8cb6d584846d",
          "appRoleId": "7ab1d382-f21e-4acd-a863-ba3e13f7da61"
        }' 
Note: The PrincipalID and ReourceID is the SPObjectID. appRoleID is the ObjectID of appRole, which can be queried using below command:
az ad sp show --id 00000003-0000-0000-c000-000000000000 --query "appRoles[?value=='Directory.Read.All']" 
-- id is the MS Graph App ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81066b37-6e22-41d8-5b60-d1f3dc692c77
* Version Independent ID: 837a114f-9044-76de-f6fb-498573776044
* Content: [Update approleassignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/approleassignment-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/approleassignment-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/approleassignment-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@davidmu1 can we get this author updated to whoever it should be please?

**Comment by psignoret** [comment]
@JimmyLS Apologies for the late response here. The docs have all been updated now (and the API is now in v1.0), and I believe all your feedback has been addressed. Thanks for taking the time to provide this feedback!
