### ISSUE TITLE
Not have bulk insert for inserting channels

### ISSUE THREAD

**Issue by chiragSuccessive** [microsoftgraph/microsoft-graph-docs#7447]
POST https://graph.microsoft.com/v1.0/teams/{id}/channels
Have to post a request multiple times to create channels for a team id.
Eg- Have to create 4 channels then have post request 4 times with the same team id, bulk channel insert API should be provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create Channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by anandab-gt** [comment]
you can create multiple channels while creating a team, pls refer this doc - 
https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&tabs=http#example-3-create-a-team-with-multiple-channels-installed-apps-and-pinned-tabs-using-delegated-permissions

**Comment by anandab-gt** [comment]
@chiragSuccessive  - closing this issue, in case you feel your problem is not solved either reopen this issue or create a new issue.
