### ISSUE TITLE
Website tab configuration is incorrect

### ISSUE THREAD

**Issue by arafhossain** [microsoftgraph/microsoft-graph-docs#7450]
It's stated to list the 'entityId' as Null, however, setting it as Null or even an empty string sends back an error 'Code: BadRequest, Message: Value cannot be null. Parameter name: entity.' Can this be clarified/fixed? My app can properly create tabs for SharePoint page, Document Library, Wiki, and Power BI tabs but not Website tabs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs#feedback)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by arafhossain** [comment]
Update - the tabs were created successfully in my Teams Channel, but I'm still unclear why it kicks back that error code...

**Comment by JackSentenza** [comment]
The tab is created successfully and as you reported the error is thrown anyway AND subsequent calls to the API to List all tabs (https://docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-1.0) gives back another error: "Failed to execute request.". 
The only solution is to manually remove the website tab from the channel. It should be fixed ASAP I think..

PS: Creating the website tab manually in teams does not generate the error calling the List Tabs API

**Comment by HunaidHanfee-MSFT** [comment]
Tab is getting configured successfully with following API call.
```
{
    ""displayName"": ""test web app"",
    ""teamsApp@odata.bind"": ""https://graph.microsoft.com/beta/appCatalogs/teamsApps/com.microsoft.teamspace.tab.web"",
    ""configuration"": {
        ""entityId"": null,
        ""contentUrl"": ""https://www.google.com/"",
        ""removeUrl"": null,
        ""websiteUrl"": ""https://www.google.com/""
    }
}
```
Please refer following URL for similar issue:
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/381
