### ISSUE TITLE
PowerShell

### ISSUE THREAD

**Issue by lightupdifire** [microsoftgraph/microsoft-graph-docs#7452]
Hello,

I try to run the PS script, but receive an error "Write requests are only supported on contained entities", any ideas?
API Application permission access granted: GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All; Access token well received;

PS:

function AddB2BToDisabledGroup (){
    param(
        [string]$AccessToken
    )

$B2BAddToDisabledGroupHeaders = @{Authorization = "Bearer $AccessToken"}
$url = "https://graph.microsoft.com/v1.0/groups/$groupID/members/$ref"

$Body = @"
{
  "@odata.id": "https://graph.microsoft.com/v1.0/directoryObjects/$b2buserID"
}
"@
$addtogroupres = Invoke-RestMethod -Uri $url -Method Post -Headers $B2BAddToDisabledGroupHeaders -Body $Body -ContentType 'application/json' -ErrorAction Stop
$addtogroupres.status
}

Using the Tenant Admin account, using Graph Explorer, using the same group and user ID, POST works fine. Tested also with: "@odata.id": "https://graph.microsoft.com/v1.0/users/$b2buserID"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 558e6675-990e-b571-6bfb-7392f097edbe
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kevmaitland** [comment]
Same scenario, same issue here.

**Comment by superz202** [comment]
$url = "https://graph.microsoft.com/v1.0/groups/$groupID/members/$ref"

This is due to the "$" used in $ref. In Powershell, you may need to escape that. So the URL should be below, my guess.

$url = "https://graph.microsoft.com/v1.0/groups/$groupID/members/`$ref"

**Comment by lightupdifire** [comment]
@superz202 
Thank you very much! Works fine. Completely forgot to test "escapes" :)
