### ISSUE TITLE
Permissions not clear for this document.

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs#7456]
The "Organization.Read.All" permission also seems to work for this.  That being said, which of these permissions have the lease privilege?  Directory.Read.All" or "Domain.Read.All" or "Organization.Read.All"   Can this document be updated please?  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b94245-c71b-a359-e716-fbca59df2611
* Version Independent ID: 6eba33cb-9985-91e2-cd4f-ddf40655d565
* Content: [List domains - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/domain-list?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/domain-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/domain-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
Domain.Read.All has the least privilege and should be listed first.  I was not aware that Organization.Read.All allowed this /domains API to be read.  I'll come back and check on this.  Organization.Read.All was designed to allow reading of the /organization resource, which contains a subset of the domains information (only verified domains and a subset of the properties - as part of the verifiedDomains property).
