### ISSUE TITLE
User.Read and User.ReadWrite permissions are not working for me/getMemberGroups or me/getMemberObjects

### ISSUE THREAD

**Issue by PatrickMcvay** [microsoftgraph/microsoft-graph-docs#746]
Example Request 

POST https://graph.microsoft.com/v1.0/me/getMemberObjects
Content-Type: 'application/json'
Authorization: Bearer  accessTokenRemovedForBrevity
Host: graph.microsoft.com
Content-Length: 38

Body
{
"securityEnabledOnly" : true
}

Response to that request
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "32f66597-eb66-4843-8227-8c0a8bfc0ac7",
      "date": "2017-01-05T13:48:49"
    }
  }
}

I have both User.Read and User.ReadWrite permissions set up. I also tried "me/memberOf" but I know those permission scopes are different.

And, yes the exact same accessToken that gave me the forbidden response was able to return my messages, my info, and my calendars. These requests were made using Fiddler.

**Comment by marych** [comment]
Hi @PatrickMcvay. To read the groups that a user is a member of, the app will also require Group.Read.All or Group.ReadWrite.All permissions. This is mentioned in https://graph.microsoft.io/en-us/docs/authorization/permission_scopes.

**Comment by dkershaw10** [comment]
That topic may be correct, but other topics are incorrect with the permissions required.  We'll need to fix those to reflect the answer above.

**Comment by dkershaw10** [comment]
See https://github.com/microsoftgraph/microsoft-graph-docs/pull/853
