### ISSUE TITLE
Error communicating with AD using places meeting room

### ISSUE THREAD

**Issue by xhr0804** [microsoftgraph/microsoft-graph-docs#7475]
[Enter feedback here]
It is OK to use the findrooms, but will get error when use places/microsoft.grahp.room
![image](https://user-images.githubusercontent.com/44257569/77423627-982c7480-6e0a-11ea-8965-7450abb73b81.png)
![image](https://user-images.githubusercontent.com/44257569/77423633-9cf12880-6e0a-11ea-8830-6fe086288bba.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 227ceac7-ddb7-01ff-a42b-4d71394d3a74
* Version Independent ID: 44cfac3b-3d9f-0f26-5f50-e695da0fcea7
* Content: [place resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/place.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by EliasKaplan** [comment]
Hi @xhr0804 , places API chaches the list of rooms with enriched information, seem that the repository has not been created for your tenant.
what region, is your tenant? when it was created?
We recently updated the code to run in all regions/forests. can you retry?

**Comment by GoorMoon** [comment]
Hi,
Any progress on this issue ?

**Comment by vrod9429** [comment]
This issue was resolved. Please let us know if you are still hitting an error.

**Comment by lramosvea** [comment]
Closing as this issue has been resolved already
