### ISSUE TITLE
What is the URL path to execute the request?

### ISSUE THREAD

**Issue by sathishvc** [microsoftgraph/microsoft-graph-docs#7476]
@ken5scal has already opened a request but it is closed without providing the URL path in this documentation. Please provide the URL path that needs to be invoked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639d5c1a-b3b4-b8b7-65a1-289308d3b9bc
* Version Independent ID: 6274178f-9f66-61a9-3173-1eb522fd4be0
* Content: [deviceGeoLocation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-devicegeolocation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/intune-devices-devicegeolocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-devices-devicegeolocation.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've asked our dev folks to update the documentation with that information.
