### ISSUE TITLE
Throttling on app ID

### ISSUE THREAD

**Issue by wonderplayer** [microsoftgraph/microsoft-graph-docs#7478]
Based on documentation [here](https://docs.microsoft.com/en-us/graph/throttling#outlook-service-limits) I can create multiple app IDs and then send from one mailbox to increase throttling limit
I've decided I need 5 app IDs to completely avoid getting throttled. But unfortunately I still got throttled the same as with one app ID.
Tried the other way around - one app ID and 5 mailboxes - this worked exactly as I wanted and I've avoided throttling.
So, either I'm missing something or this documentation is incomplete?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling#outlook-service-limits)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by migee** [comment]
Also looking for information on this as well

**Comment by abheek-das** [comment]
As mentioned here, the [Exchange throttling limits](https://docs.microsoft.com/en-us/graph/throttling#outlook-service-limits) are evaluated for each app ID and mailbox combination. So, if you hitting throttling limits then most likely you are exceeding one of the 3 limits described in the page. 

Could you please provide more details on your request and the request patterns? It would be also helpful, if you can provide details of the exact error signature that you are receiving.

**Comment by wonderplayer** [comment]
This was so long ago I don't have that project anymore.
Anyway, I remember that I created 5 app IDs and was sending a large batch of mails one by one with app ID and mailbox combination being picked randomly.

**Comment by abheek-das** [comment]
I am closing this issue now, since we would need additional details on the request pattern to do any further investigation. The docs related to current Exchange throttling limits are mentioned above. Please feel free to re-open this issue with additional details if needed.
