### ISSUE TITLE
Missing resource

### ISSUE THREAD

**Issue by jrmarquard** [microsoftgraph/microsoft-graph-docs#7481]
Hi,

I'm trying to understand the throttling restrictions on https://graph.microsoft.com/v1.0/auditLogs/signIns but it seems to be missing from this page. Can't find a parent section etc where it might be found either.

Cheers,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#feedback)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Sorry for the time it took to reply. Over the last few months we've documented a lot of additional service limits and audit logs are part of the newly documented limits.
I'll go ahead and close this issue, feel free to reopen a more specific one of information is missing
