### ISSUE TITLE
Replying to a Team Chat Message through a Graph API bring down the original message

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#7488]
Hello Team, when I reply to a message in Teams Chat systematically using a graph api, somehow original message with reply comes below other message that were sent after the original message. When I reply to any message manually that does not change the order of postings but with Graph api it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e78d7f28-2ac1-bdc1-4ac5-3a20756270be
* Version Independent ID: 353e1a63-1ae9-201a-4ac2-8949b164788f
* Content: [Reply to a message in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messagereply.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ashoksubedi1** [comment]
Hello @nkramer  thank you for your attention on this issue. 
any updates on this.

**Comment by Nikitha-MSFT** [comment]
when you reply to a message it will take some time to update, But when to try to reply using Graph api it will update immediately. Latest message is shown at the bottom it is by design.

**Comment by ashoksubedi1** [comment]
@Nikitha-MSFT  I think there is a misunderstanding I know latest msg will come on the bottom by design and that's ok. I am here talking about the message that was on the top when I reply to it using graph api that comes down when replied. That is not the case when you reply normally through teams. I can send you screen shots if needed.

**Comment by Abhijit-MSFT** [comment]
You can not reply to any single message. You can reply to the conversation thread. Can you please confirm which API's you are using to reply to conversation thread. You need to use [these](https://docs.microsoft.com/en-us/graph/api/conversationthread-reply?view=graph-rest-1.0&tabs=http) API to respond to thread. Can you please share the code snippet and the screenshot that you are talking about.

**Comment by ashoksubedi1** [comment]
@Abhijit-MSFT There is a misunderstanding again. conversation threads are different in Team(Channel) Chat message. I am not talking about conversation thread and replying to the thread. I am talking about this endpoint which is different from conversations and threads.**POST /teams/{id}/channels/{id}/messages/{id}/replies**. When I reply to a message in the teams chat using graph api, the message that was replied to falls down in the chat platform. May be there is a orderHint issue in this messages on your side. Can you look into it. Again, I am taking about chatting on the channel platform in the **Post Tab**

**Comment by Nikitha-MSFT** [comment]
@ashoksubedi1  - when you are reply to an existing message then it will be shown along with the latest message at the bottom.  It is by design if you are using graph API or you do it manually. When you are using Graph to reply it will be reflected immediately when you do it manually i will take a little time to update. Could you please check the messages which you have replied manually?
