### ISSUE TITLE
Is it feasible to generate a online meeting within our backend service(daemons) for product usage, without user interactive

### ISSUE THREAD

**Issue by wardpeng** [microsoftgraph/microsoft-graph-docs#7495]
Hi there, 

Now, we have a system which is using generated Skype meeting URL, and our company is planning to replace Skype with Teams.

So we would like to generate an online meeting within our backend service(daemons), and send it to target people with another mail. 

My questions:
1. I see from this page, the permission only support **Delegated** permission. 
Does it means it must use 'on behalf of a user' way to get token? Form my understanding, this method must have some 'user interaction'. So is this API feasible to our daemons scenario?

2. Our orgination has open MFA(multi-factor authentication), so we couldn't get token with use ['Owner Password Credentials' ](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc).  We would like to use 'Client Credentials Flow', so does this API support this kind of flow? If not, do we have other API could generat online meeting to support our scenario? And we will use it within our production, and I think api with /beta version is not a good option.

Thanks so much,
Ward

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nassereb** [comment]
Also stuck here.
I would like to use the client credentials flow. this seems not to be supported in v1, the beta documentation mentions that online meeting creation using an application token is deprecated and support will be removed in July 2020.

What are my options?

Many thanks,
nas
