### ISSUE TITLE
Can you please give example for flutter aslo that how to get calendar data?

### ISSUE THREAD

**Issue by kurzekar-rohit** [microsoftgraph/microsoft-graph-docs#7498]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7064b6c8-8cb1-a8e2-c5b3-29d9107e3373
* Version Independent ID: 1720fe53-158d-0543-7f0c-5da3d900588a
* Content: [List events - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-list-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-list-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-list-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@kurzekar-rohit , thank you for your input. Please enter your request at [Microsoft Graph Uservoice](https://microsoftgraph.uservoice.com/) to have it tracked.
