### ISSUE TITLE
GCC High: conditionalAccessPolicy resource returns "Required authentication failed."

### ISSUE THREAD

**Issue by john-crouch** [microsoftgraph/microsoft-graph-docs#7504]
When attempting to list CA policies within a GCC High tenant, I receive the following:

{
  "error": {
    "code": "Unauthenticated",
    "message": "Required authentication failed.",
    "innerError": {
      "request-id": "d7190a07-b223-4cda-a9b8-a8e12b644520",
      "date": "2020-03-26T14:36:15"
    }
  }
}

The request works as expected when run against an O365 commercial tenant. 

- **DOES NOT WORK** - https://graph.microsoft.us/beta/conditionalAccess/policies
- **WORKS** - https://graph.microsoft.com/beta/conditionalAccess/policies

I'm using application permissions on both associated AAD applications: Policy.Read.All

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2f4938-7d09-1888-5d89-15cdaa9bf6dd
* Version Independent ID: 601266a3-affe-e167-d643-5de314b0bfd9
* Content: [conditionalAccessPolicy resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/conditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/conditionalaccesspolicy.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by videor** [comment]
@john-crouch we have now supported CA APIs in US Gov Clouds. Can you please test and confirm is you are still seeing the issue? 

API docs - https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-policies?view=graph-rest-1.0&tabs=http

**Comment by john-crouch** [comment]
@videor Thank you! It's working now.
