### ISSUE TITLE
Application permissions gives unauthorized for property mySite

### ISSUE THREAD

**Issue by PieterHeemeryck** [microsoftgraph/microsoft-graph-docs#7505]
I'm using application permissions Directory.ReadWrite.All, but the following call gives unauthorized:

GET https://graph.microsoft.com/v1.0/users/{upn}?$select=mySite

Context:
https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-userprofileexperience#to-detect-a-users-profile-location-and-personal-site-url

I had to resort to the CSOM alternative...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
@PieterHeemeryck I'm not able to repro this issue, the information is returned for the signed-in user as well as other users. Can you please confirm if you can still repro? Can you also please check/confirm the permissions in Graph Explorer?

**Comment by PieterHeemeryck** [comment]
@krbain It works in the Graph Explorer as that is using delegated permissions (you are signed in with a user). It also works for other users in the Graph Explorer, that is not the issue.

The issue is using application permissions in an AAD app (i.e. Directory.ReadWrtie.All). The documentation for MS Graph states you can use application permissions for the [/users endpoint](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http).

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
