### ISSUE TITLE
Change Log?

### ISSUE THREAD

**Issue by tpmeredith** [microsoftgraph/microsoft-graph-docs#7506]
Is it possible to see a change log of the calling graphs API anywhere? This page says updated march for example and often says updated, but its difficult to tell what features were added, improved, or if anything changed at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c774bda6-ba88-71c4-0dd2-ced4dfb5967f
* Version Independent ID: 57c00459-3fa7-1610-e327-2374c1613bdf
* Content: [call resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/call?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/call.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/call.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @tpmeredith you can view that here - https://docs.microsoft.com/en-us/graph/changelog
