### ISSUE TITLE
Microsoft Graph API in Laravel

### ISSUE THREAD

**Issue by abhikm1991** [microsoftgraph/microsoft-graph-docs#7516]
Kindly look in this link detailly. I need answer from your end.

https://stackoverflow.com/questions/60880089/microsoft-graph-api-in-laravel-controller

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a63d98-d88c-01fe-afca-31d1920ba76c
* Version Independent ID: 7c2deaf1-192f-e3a6-57dd-6b9caa7c2e4c
* Content: [Get organization - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/organization-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/organization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/organization-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abhikm1991** [comment]
why I am not getting Event list ??

**Comment by jasonjoh** [comment]
Closing issue as I've answered it on Stack (and it's unrelated to this documentation)
