### ISSUE TITLE
Formatting issue 'Error Codes'

### ISSUE THREAD

**Issue by nazakathussain** [microsoftgraph/microsoft-graph-docs#7518]
Slight formatting issue with the table under error codes. Possible just needs the table to start on a new  line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc772164-038e-68f5-b9d1-41a889e1e014
* Version Independent ID: 1078b2c2-80b1-55b1-38e9-dde2f160a5c8
* Content: [Cancel governanceRoleAssignmentRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governanceroleassignmentrequest-cancel?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/governanceroleassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceroleassignmentrequest-cancel.md)
* Product: **microsoft-identitiy-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Seems to have been corrected. No change identified for the page. Closing the issue.
