### ISSUE TITLE
filtering on "accessPackageId"

### ISSUE THREAD

**Issue by snikendeugle** [microsoftgraph/microsoft-graph-docs#7519]
For some reason, filtering on "accessPackageId" is not supported.

Example:
https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentPolicies?$filter=accessPackageId eq '########-####-####-####-############'.

Returns:
    "error": {
        "code": "InvalidFilter",
        "message": "OData query is invalid: Filter 'accessPackageId Equals ########-####-####-####-############ is not supported. .",

This would be useful in order to pinpoint access package policies, based on known access package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f33c7125-e0b3-ad3e-8301-2c20d3a96865
* Version Independent ID: 40b6405d-1e65-0439-8c53-585831897f1f
* Content: [List accessPackageAssignmentPolicies - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/accesspackageassignmentpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accesspackageassignmentpolicy-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
While filtering is not possible at this time, you can retrieve access package assignment policies for a particular access package using `expand`, as described in [list accessPackages](https://docs.microsoft.com/graph/api/accesspackage-list?view=graph-rest-beta). Such as `beta/identityGovernance/entitlementManagement/accessPackages/########-####-####-####-############?$expand=accessPackageAssignmentPolicies`.

**Comment by snikendeugle** [comment]
Hi, I know of that possibility now thankfully, but that does not completely cover the use case of being able to filter the other way on objects as well, since there are limitations in filtering on nested objects as well.

I have filed a general feedback thread on filtering with the Graph API in Entitlement Management. Since the data is visible in the queries, it should be able to be filtered as well, in my opinion. Otherwise it leaves a lot to guess-work at this point.
