### ISSUE TITLE
filtering on "requestorSettings/scopeType"

### ISSUE THREAD

**Issue by snikendeugle** [microsoftgraph/microsoft-graph-docs#7520]
Filtering on "requestorSettings/scopeType" is not supported.
Example:
https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackageAssignmentPolicies?$filter=requestorSettings/scopeType eq 'NoSubjects'

Returns:
    "error": {
        "code": "InvalidFilter",
        "message": "OData query is invalid: Filter 'requestorSettings/scopeType Equals NoSubjects is not supported. .",

This would also be very useful to be able to filter for automated workflows that picks out assignment policy based on the policy type (admin assignment/request based)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f33c7125-e0b3-ad3e-8301-2c20d3a96865
* Version Independent ID: 40b6405d-1e65-0439-8c53-585831897f1f
* Content: [List accessPackageAssignmentPolicies - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/accesspackageassignmentpolicy-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accesspackageassignmentpolicy-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by snikendeugle** [comment]
This one could possibly be a problem with the syntax. I did experiment with expanding requestorSettings first, but did not have any luck with this.

**Comment by markwahl-msft** [comment]
List of access package assignment policies does not currently permit filtering on values in these nested structures.  I'd suggest adding this as a request in the  [Azure AD feedback for Entitlement Management](https://feedback.azure.com/forums/169401-azure-active-directory?category_id=363793).  Thanks!
