### ISSUE TITLE
Special characters returned from API call

### ISSUE THREAD

**Issue by Ben-Conrad** [microsoftgraph/microsoft-graph-docs#7522]
When I call getTeamsUserActivityUserDetail and possibly others, the return data has special characters in the Report Refresh Date field as seen below:

ï»¿Report Refresh Date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa64daf9-bfd7-bfe0-0a4a-cec6b062a192
* Version Independent ID: a2b14964-5512-9183-9cc8-ad00e55e146d
* Content: [reportRoot: getTeamsUserActivityUserDetail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivityuserdetail?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ncallison** [comment]
Seeing the same thing. Got around it using -replace in PowerShell but would love to not have to.

**Comment by Ben-Conrad** [comment]
So apparently this is probably a Byte Order Marker (BOM).  

I'm able to get rid of it (-replace) when working inside a PS window but when I export to .CSV it always remains. 

Tried this a hundred different ways:
$report = $result.Replace('ï»¿Report Refresh Date','Report Refresh Date')

**Comment by ncallison** [comment]
Here is how I got it to work, little janky but it worked for me:

[cid:image001.png@01D60673.2203AC00]

Nathan Allison
System Analyst
Data Center Services
Western Carolina University

**Comment by Nootvar** [comment]
If you are working with powershell here is the solution : 
$apiDataBytes= [System.Text.Encoding]::GetEncoding("ISO-8859-1").GetBytes($apiData)
$properData = [System.Text.Encoding]::UTF8.GetString($apiDataBytes)
$apiDataList = ConvertFrom-Csv -InputObject $properData;
