### ISSUE TITLE
Skype For Business

### ISSUE THREAD

**Issue by rpats1997** [microsoftgraph/microsoft-graph-docs#7525]
I noticed on experimentation that the create online meeting api is always returning/generating a teams link, is it possible for me to generate a Skype for Business link instead if Skype permissions are enabled on Azure portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bddf229-c02d-7595-78c5-6dac2b1c3c76
* Version Independent ID: a1ccb913-8d51-1445-e81f-a4f100a495e3
* Content: [onlineMeeting resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/onlinemeeting.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @rpats1997 this isn't supported.

**Comment by ssougnez** [comment]
Why is "SkypeForBusiness" a possible value of the "OnlineMeetingProvider" property then?
