### ISSUE TITLE
Dates are null

### ISSUE THREAD

**Issue by Air-Git** [microsoftgraph/microsoft-graph-docs#7531]
In my policies, when I read them in Graph Explorer, the createdDataTime and modifiedDateTime are both null. Is this a bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2f4938-7d09-1888-5d89-15cdaa9bf6dd
* Version Independent ID: 601266a3-affe-e167-d643-5de314b0bfd9
* Content: [conditionalAccessPolicy resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/conditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/conditionalaccesspolicy.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by michevnew** [comment]
Dates seem to be populated once you edit a policy (or create a new one). I suppose they simply didnt collect this data previously.

**Comment by Air-Git** [comment]
When I create a new policy, and export it, it has no create date or modified date.

**Comment by videor** [comment]
@Air-Git the dates information is captured when you use MS Graph APIs only. Are you using the UX to create the policy and then export using the API? The later scenario is not yet supported for dates but will be supported in future.
