### ISSUE TITLE
Groups Add member incorrect permissions

### ISSUE THREAD

**Issue by christopher-walker** [microsoftgraph/microsoft-graph-docs#7535]
It seems that the permission levels for the add member to groups documentation is misleading (either this or there is a permission issue)

Currently for the following permission sets are given:

|Permission type      | Permissions (from least to most privileged)              |
|:--------------------|:---------------------------------------------------------|
|Delegated (work or school account) | GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All    |
|Delegated (personal Microsoft account) | Not supported.    |
|Application | GroupMember.ReadWrite.All, Group.ReadWrite.All and Directory.ReadWrite.All |

I havent tested for Delegate permission yet (I will do that later) but at least for the application permission additional permissions are needed in the case of GroupMember.ReadWrite and Group.ReadWrite.

I belive that the permissions should read as follows:

|Permission type      | Permissions (from least to most privileged)              |
|:--------------------|:---------------------------------------------------------|
|Application | (GroupMember.ReadWrite.All and User.Read.All), (Group.ReadWrite.All and User.Read.All) and Directory.ReadWrite.All |

Simply having GroupMember.ReadWrite.All or Group.ReadWrite.All is not enough permission to add a user to a group with application permissions as the application does not have access to the user account.

Thanks

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by heinrich-ulbricht** [comment]
I second that.

**Comment by dkershaw10** [comment]
@heinrich-ulbricht That's a nice suggestion.  We'll take a look at this for anything that requires multiple permissions.

**Comment by woottipong523** [comment]
https://graph.microsoft.com/v1.0/groups/{id}/members/$ref

What is the {id} and $ref values?

**Comment by chrisbarber-22** [comment]
I've provisioned all of the above permissions for delegated (GroupMember.ReadWrite.All, Group.ReadWrite.All, Directory.ReadWrite.All, Directory.AccessAsUser.All) and still running into the following: "code": "Authorization_RequestDenied", "message": "Insufficient privileges to complete the operation.

**Comment by yyuank** [comment]
@christopher-walker we have deployed a fix. To add a member to a group, user permission is not needed anymore. If you know the user reference, which is the user objectID, you should be able to add the user to a group with GroupMember.ReadWrite or Group.ReadWrite permission.
