### ISSUE TITLE
Java code example produces wrong request body 

### ISSUE THREAD

**Issue by fsjovatsen** [microsoftgraph/microsoft-graph-docs#7538]
Hi,

the Java code example produces wrong request body. The example produces a request body of:

`{"id":"c18c8c2d-fbfc-4098-xxxx-xxxxxxxxxxxx"}`

instead of 
``` 
{
  "@odata.id": "https://graph.microsoft.com/v1.0/users/{id}"
}
``` 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b619f6e-e391-ef3d-cd45-682ad87b5a73
* Version Independent ID: 907a4979-7d65-112e-05d1-c2a13fd5f897
* Content: [Assign manager - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-manager.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
This appears to be an issue with the functionality of the SDK not this documentation page. Communicating issue with engineering and closing the issue.
