### ISSUE TITLE
More detail on "appliesTo" property?

### ISSUE THREAD

**Issue by JakeLunn** [microsoftgraph/microsoft-graph-docs#7539]
Can the "appliesTo" property be further expanded upon? For context, I am running into an error when trying to assign a specific license to a user. The error is "License ______ cannot be assigned to a user." The appliesTo property on this page seems to suggest that some Licenses might have service plans which are not assignable to users. 

My specific question: If I iterate through each service plan and find that none of the applyTo properties are set to "User" - does that mean the license is unassignable to users? Is this property the best way to check this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 368af49c-31b1-ebb9-68df-5cf4a041d50b
* Version Independent ID: 0ee918a5-296e-99e5-2902-cbb8e73a9dbd
* Content: [subscribedSku resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscribedsku?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/subscribedsku.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/subscribedsku.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Kindly take a look at this article. https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-licensing-whatis-azure-portal
