### ISSUE TITLE
Will this support call like /users/{id | userPrincipalName}/onlineMeetings in the feature?

### ISSUE THREAD

**Issue by sjr2** [microsoftgraph/microsoft-graph-docs#7550]
We are merging Teams into our LMS and would like to have the ability to create a meeting for course in our LMS. Also, we have our own meeting schedule system for our staff that wants to be able to create online meetings through the API. It will be very helpful if we don't need to ask user to sign in again for this kind of setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by asmealio** [comment]
We had to use a service account to do this in combination with leveraging the other APIs available on graph made it work for Telehealth.

Guessing similar scenario. Reach out for more details.

**Comment by tommyJimmy87** [comment]
Hi @asmealio I have a similar use case where I want a backend service to create online meetings without the user sign-in. Is that the case you implemented?

**Comment by asmealio** [comment]
Yeah - it is.

**Comment by tommyJimmy87** [comment]
@asmelio could you share some basic details of the implementation? As per documentation here looks like an Online Meeting can be created only on behalf of the user.

**Comment by rbaryolo** [comment]
Hello @asmealio I have a use case similar to yours. Could you give some insights of your implementation? Up to the docs, meetings can be created only on behalf of the user.

**Comment by asmealio** [comment]
We created a service account to schedule the meetings with no attendees. Then, under application context, inject the meeting information into the required attendees calendar.

We have external attendees as well, so we email the meeting information to them. Although, you could simply just make them required on the calendar event to achieve same effect.

Adam Smeal
C:

**Comment by ajayvjain** [comment]
@asmealio - Do you then have to use this service account to start the meeting? Is there any other way that someone else can start the meeting?
