### ISSUE TITLE
List of rule identifier and values

### ISSUE THREAD

**Issue by anwather** [microsoftgraph/microsoft-graph-docs#7553]
Is there a list of rule identifiers and accepted values - what I need to do is update the NotificationRule with email addresses. I can extract a current representation using fiddler in the portal - but the API doesn't seem to return these values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b8cb559-0058-64b9-4856-7e19a50b2b59
* Version Independent ID: b8ead853-634e-c5fd-353f-fcc527a4af52
* Content: [governanceRuleSetting resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/governancerulesetting?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/governancerulesetting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/governancerulesetting.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @wn9237
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies for the delayed response.
Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/products/m365#microsoft-graph). Please ask your question there. No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
