### ISSUE TITLE
Permissions for /profile are incorrect.

### ISSUE THREAD

**Issue by LoungeFlyZ** [microsoftgraph/microsoft-graph-docs#7559]
Permissions for /profile are listed as "Not supported" for both delegated and application scenarios.  I don't believe that is correct. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd548e6-ce35-e115-9ef0-3b02c4bc3339
* Version Independent ID: 66102ee0-9fec-55a4-dc29-bdecb7884132
* Content: [Get profile - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/profile-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/profile-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/profile-get.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PeterChencha** [comment]
Hello @LoungeFlyZ thanks for reaching out. This documentation has addressed the issue -> https://docs.microsoft.com/en-us/graph/api/profile-get?view=graph-rest-beta&tabs=http. Feel free to reach out if this is not what you were looking for.

**Comment by PeterChencha** [comment]
Hello @LoungeFlyZ, this issue is addressed on the previous comment. Kindly feel free to open another issue if you are still facing this issue.
