### ISSUE TITLE
Web-hook subscription delay + retention period?

### ISSUE THREAD

**Issue by wendelstam** [microsoftgraph/microsoft-graph-docs#7566]
How long after a session/call end will the event be sent? We have a solution running but the events are delayed several hours for some reason?
Are there any information about what time period one could expect and also what is the retention period for the record content on Microsoft side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baff198b-501f-c97d-005d-36875302640d
* Version Independent ID: 413b2545-44cc-1f43-3feb-2c4deab9472e
* Content: [Working with the call records API in Microsoft Graph - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta#key-resource-types)
* Content Source: [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/callrecords-api-overview.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
Notifications are sent only after the call/meeting completes. It takes some time for the telemetry to flow through our pipeline to produce the call record, but in most cases this should be under an hour.

Call records are accessible from the API for 30 days from the start of the call.
