### ISSUE TITLE
Cannot add certain apps in non public Teams created by Graph API

### ISSUE THREAD

**Issue by PieterHeemeryck** [microsoftgraph/microsoft-graph-docs#7567]
We found a very strange issue at several tenants, regarding **Teams creation via the Graph API**:

When a new Team is created with the Graph API, which has Visibility != “Public”, in the created Team you cannot add the Flow app (and possibly other apps will have the same issue…).

When a new Team is set to Public, the issue does not occur.
When creating Teams OOTB, the issue does not occur, neither for Public or Private teams.

I’m at a total loss what the reason could be, and can’t find any solution to the problem…

What I’ve tried so far:

- Creating a Group OOTB, and extending it with a Team through Graph API
- Using PUT /beta/groups/<id>/team to extend with a Team
- Using POST /beta/teams to create the team directly, instead of extending a group
- Cloning an OOTB Team using the Graph API
…

It seems that anything that's being done with Graph API which creates/changes to a non-public team has the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by NickSevens** [comment]
Additionally, the same issue occurs with other apps which add a Bot to the channel. (e.g. Polly)

**Comment by PieterHeemeryck** [comment]
https://techcommunity.microsoft.com/t5/microsoft-teams/cannot-add-certain-apps-in-non-public-teams-created-by-graph-api/m-p/1270817

**Comment by Trinetra-MSFT** [comment]
@PieterHeemeryck Could you please provide request ids and timestamps for:
1) the request to create the team.
2) the request to install the app.

**Comment by PieterHeemeryck** [comment]
@Trinetra-MSFT Thanks for your reply, however, this ticket has been resolved with MS Premier support. MS pushed an update and since then all is working fine again.
