### ISSUE TITLE
Pagination is broken. Results are inconsistent.

### ISSUE THREAD

**Issue by denisthedeveloper** [microsoftgraph/microsoft-graph-docs#7569]
I'm sending this request:
GET https://graph.microsoft.com/v1.0/me/messages?$skip=0&$top=100

and the @odata.nextLink that is returned in the response is:
https://graph.microsoft.com/v1.0/me/messages?$skip=190&$top=100.

If I then use the above @odata.nextLink to make a request I get this @odata.nextLink in the response of the second page:
https://graph.microsoft.com/v1.0/me/messages?$skip=234&$top=100

If I keep using the OData next links returned by the API I get about 3679 objects in total from all pages.
If I then try paging all the way from the beginning ($skip=0) till the end, I get 3667 objects this time. Every time I'm trying this it is returning inconsistent results. Objects are missing.

I'm working around this isseu by specifying the values for 'skip' and 'top' by myself:
GET https://graph.microsoft.com/v1.0/me/messages?$skip=0&$top=100
GET https://graph.microsoft.com/v1.0/me/messages?$skip=100&$top=100
GET https://graph.microsoft.com/v1.0/me/messages?$skip=200&$top=100
GET https://graph.microsoft.com/v1.0/me/messages?$skip=298&$top=100
GET  https://graph.microsoft.com...............

The above pagination method works correctly and is always consistent.
Note: Sometimes, even though I have specified '$top=100', I don't get 100 objects in 'value' array of the response. This is weird, and my workaround to this is to increment 'skip' based on the number of objects in 'value'. In this above case, 98 objects were returned in the response. I've seen as low as 78 being returned, even though I'm always specifying '$top=100'.

The ideal solution for this issue would be for the API to return the correct @odata.nextLink in the response, and for the results to be always consistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e0169c1-e6e7-da8f-4158-5e721eae8b9a
* Version Independent ID: f2907cde-b9d7-4ba7-e813-047e5b938e50
* Content: [List messages - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-messages.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@denisthedeveloper , thank you for bringing this up.
The operation GET /users/id/messages looks in the specified user's mailbox to get message items. If there are more message items that can be returned than the page size (be it the default page size or custom page size), paging kicks in.

Now within a mailbox, there can be message items, and other item types such as event and contact items. The GET /messages operation goes through this mix of items and returns just the message items. Therefore, it's possible that the $skip value returned in an @odata.nextLink is larger than the $top value in the request. Microsoft Graph relies on the $skip value to keep track of the number of items in the user's mailbox that the previous GET operations have gone through. So while the $skip value may appear unintuitive to us, that actually reflects at the point of the GET, the mix of items in the user's mailbox.

BTW, this behavior is described at the top section of the topic
[List messages](https://docs.microsoft.com/en-us/graph/api/user-list-messages?view=graph-rest-1.0).

If you have further questions about this behavior, please post that on stackoverflow, where the community can benefit from what one another learns :-) This Github site is for specific documentation issues and folks may not monitor this site for technical questions.
