### ISSUE TITLE
Example of updating script

### ISSUE THREAD

**Issue by cconrado** [microsoftgraph/microsoft-graph-docs#7571]
Hi There,

Can we get an example of reuploading a script

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eb023f9-bf8b-c4cc-bc71-48e01e3c8037
* Version Independent ID: 3fe3097d-9b23-8bd3-4d3e-449efe82189b
* Content: [Update deviceManagementScript - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagementscript-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-shared-devicemanagementscript-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-shared-devicemanagementscript-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Can you just do a second PATCH to PATCH /deviceManagement/deviceManagementScripts/{deviceManagementScriptId} with the updated binary?

**Comment by triplanedave** [comment]
Marking as closed based on last suggested option to update a script.
