### ISSUE TITLE
Mail.ReadBasic 400 not found issue

### ISSUE THREAD

**Issue by xqpoo9** [microsoftgraph/microsoft-graph-docs#7572]
I'm trying to use the new Mail.ReadBasic permission since its vital for the application i'm building. The problem is I receive a 400 error when this permission is passed as the scope (also tried Mail.ReadBasic.All). Mail.Read works properly.

I know this is a new scope introduced in april 2019, but isn't this now available in the production version? It looks like this feature was merged into master in November and is out of beta: https://github.com/microsoftgraph/microsoft-graph-docs/pull/6308

Any help is appreciated. Only pulling email metadata rather then full contents would be extremely important to my application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#feedback)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by xqpoo9** [comment]
Interestingly User.ReadBasic doesn't work either but User.Read does.

This is my request URL by the way:

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=<CLIENT_ID>&redirect_uri=<REDIRECT_URL>&response_type=code&scope=User.Read

**Comment by Jackson-Woods** [comment]
@xqpoo9 thanks for raising this, I'm investigating with the Mail team. Can you tell us what the value of the "signInAudience" is in your app's manifest?

Microsoft Graph doesn't have a "User.ReadBasic" permission, did you mean "User.ReadBasic.All"?

**Comment by xqpoo9** [comment]
@Jackson-Woods My signInAudience param is set to: AzureADandPersonalMicrosoftAccount and the application permission i'm referencing for mail is: https://docs.microsoft.com/en-us/graph/permissions-reference#application-permissions-22

**Comment by xqpoo9** [comment]
Just an update - I tried plugging Mail.ReadBasic.All into the example app that MS created: https://github.com/microsoftgraph/msgraph-training-nodeexpressapp/tree/master/Demos/03-add-msgraph/graph-tutorial

And it returns an invalid scope error. 

To clarify, I'm creating a background service application that syncs with mailboxes. I dont need the full mail content that Mail.Read provides, just metadata, so im trying to use Mail.ReadBasic which will only return the necessary fields.

**Comment by Jackson-Woods** [comment]
@xqpoo9 Thanks for your reply and additional info. We've identified a specific issue that affects this permission's availability, as you're experiencing. We're working to get that resolved and I'll update here when I have more. 

Also, can you confirm whether you're seeing the same issue with User.ReadBasic.All?

**Comment by xqpoo9** [comment]
@Jackson-Woods Thank you! Your help is really appreciated, as fixing this will significantly improve the security of our app by narrowing access to just the metadata. 

User.ReadBasic.All seems to work fine - When I plug this into the demo app: https://github.com/microsoftgraph/msgraph-training-nodeexpressapp/tree/master/Demos/03-add-msgraph/graph-tutorial as OAUTH_SCOPES='user.readbasic.all', I get a functional sign in dialog. When plugging in "mail.readbasic.all" I receive "invalid_scope"

I've attached some screenshots showing the scope passed into the app, the permissions selected inside the "Configured permissions" and the invalid scope error 
<img width="1115" alt="Screen Shot 2020-04-09 at 2 32 54 PM" src="https://user-images.githubusercontent.com/63019253/78928742-23467500-7a6f-11ea-9d24-5587aef27997.png">
<img width="917" alt="Screen Shot 2020-04-09 at 2 32 29 PM" src="https://user-images.githubusercontent.com/63019253/78928749-26416580-7a6f-11ea-8643-9d8639ce0108.png">
<img width="458" alt="Screen Shot 2020-04-09 at 2 32 16 PM" src="https://user-images.githubusercontent.com/63019253/78928762-29d4ec80-7a6f-11ea-9e47-8e4844f407e6.png">

**Comment by xqpoo9** [comment]
@Jackson-Woods I really appreciate you looking into this issue! I think i've identified the core problem. When trying to consent to the ```Mail.ReadBasic``` permission inside the graph explorer, I get a very similar result to what's happening in my app. I've attached a screenshot highlighting this. Inside the circled green area you will see the display string and description are "undefined", and when clicking the blue consent button a popup window appears then quickly closes, preventing me from consenting to readbasic. Consenting to the other permissions such as Mail.Read works successfully. 

I hope this will help us identify and resolve the issue. As i've mentioned in the past, Mail.ReadBasic is an extremely important, vital permission for the security of my app and im sure of many others. 

Thanks again for your help and work!

<img width="670" alt="Screen Shot 2020-04-13 at 6 37 12 PM" src="https://user-images.githubusercontent.com/63019253/79167662-f7e8c080-7db5-11ea-9a04-b0e2b0ecb724.png">

**Comment by Jackson-Woods** [comment]
@xqpoo9 Thank you for the additional investigation. This is useful and I'm passing it along to the appropriate teams. Small clarification: do you intend to work with delegated Mail.ReadBasic, application Mail.ReadBasic, or both? 

There may be a UI issue here as well, not sure if related. @bettirosengugi Let's follow up on why delegated Mail.ReadBasic is not having its strings displayed correctly in Graph Explorer. I have confirmed that those strings are present in the description data.

**Comment by xqpoo9** [comment]
@Jackson-Woods Thank you!

I'm believe it's the Mail.ReadBasic Application permission

**Comment by xqpoo9** [comment]
@Jackson-Woods I think we've figured it out. This permission only works on "work" accounts, not on personal accounts, which is completely fine for my use case. I've been testing it on a personal account up to today which explains why it hasn't been working. 

Give that this issue is now resolved, i'm closing the issue. Thanks again for your help.
