### ISSUE TITLE
no Location header in responce

### ISSUE THREAD

**Issue by xtofs** [microsoftgraph/microsoft-graph-docs#7589]
Hello, are the examples correct in that they do not return a location header in the responses?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
When I run the first example on the page to Create a user, I see these response headers in Graph Explorer:

{
    "cache-control": "private",
    "client-request-id": "71481c31-448c-63b3-b3f9-3a494448383d",
    "content-length": "355",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "location": "https://graph.microsoft.com/v2/75f98f54-99e9-47cd-a677-654da7ecab54/directoryObjects/26f05cc4-7b54-412d-8fa3-0518270ace02/Microsoft.DirectoryServices.User",
    "request-id": "7f7eb045-2324-4be1-8394-72c15b98cd11"
}

The location header is included. No change identified for this page. Closing the issue.

**Comment by chrisspre** [comment]
It is good that it is the response.  But the documentation makes it seem like there is no Location header. Doesn't this have to be clarified?
