### ISSUE TITLE
Number of Microsoft users by activity clarification

### ISSUE THREAD

**Issue by gdk-gagan** [microsoftgraph/microsoft-graph-docs#7591]
Is this unique or total number of users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 136d2225-b2ba-2649-2e38-afd6647e2313
* Version Independent ID: d2b9d6dd-1aed-44b0-c94d-f894dae689ed
* Content: [reportRoot: getTeamsUserActivityUserCounts - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivityusercounts?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/reportroot-getteamsuseractivityusercounts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-getteamsuseractivityusercounts.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sunilm-css** [comment]
I tried this url and returns 0 rows always
https://graph.microsoft.com/v1.0/reports/getTeamsUserActivityUserCounts(period='D30')

**Comment by Keshav-MSFT** [comment]
@gdk-gagan @sunilm-css 
We have tried to repro this issue and its working fine for us. Attaching screenshot for your reference:

![image](https://user-images.githubusercontent.com/109145952/181249141-4e9e8271-79cb-4763-ac04-1146c9e947fe.png)

Thanks!

**Comment by ChetanSharma-msft** [comment]
@gdk-gagan - We are check with engineering team on your query **"Is this unique or total number of users?"** and get back to you.

**Comment by ChetanSharma-msft** [comment]
Hello @gdk-gagan - There's no user returned in this API response. It's all up numbers for the tenant.

**Comment by ChetanSharma-msft** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
