### ISSUE TITLE
Sending encrypted and signed mails (smime)

### ISSUE THREAD

**Issue by rsajmani** [microsoftgraph/microsoft-graph-docs#7596]
There is no guidance on how to send signed and/or encrypted emails. We have necessary private and public key certificates but it's not clear how to send encrypted email using Graph API. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svpsiva** [comment]
This is not a supported feature in Graph at this time. It is in our backlog. I'd request you to upvote the ask on our UserVoice forum. https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests
