### ISSUE TITLE
How do I add a member to a tag?

### ISSUE THREAD

**Issue by xdmushui** [microsoftgraph/microsoft-graph-docs#7597]
Is there an API that allows me to bulk add members under a certain tag?
Because our company has multiple regional employees, these employees are quickly added or removed when they are on boarding or leaving the company.

Manage tags in Teams: (https://docs.microsoft.com/en-us/microsoftteams/manage-tags)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5463d788-8e29-ca0a-5490-93506ff1ec80
* Version Independent ID: 1e7ca228-0b9f-beb1-d61f-7f1fdff50008
* Content: [Use the Microsoft Graph API to work with Microsoft Teams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teams-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment]
There is no graph API for this currently. You can make a feature suggestion on [Microsoft Teams feedback portal](https://aka.ms/microsoftteamsplatformsuggestions)
