### ISSUE TITLE
changeType spec is not clear

### ISSUE THREAD

**Issue by NT-D** [microsoftgraph/microsoft-graph-docs#7598]
Hi, let me provide feedback about this document.
This document describes that changeType supports `created`, `updated` and `deleted`. Would you please provide detailed information about what kind of user action treated as each type ?
(ex. If user create new event in the calendar, it is handles as `created`)

Let me provide question background.
When I see document, I thought each type expected as following. I mainly focus on calendar to describe example.
- created: This is triggered when user create new schedule in calendar
- updated: This is triggered when user update existing schedule in the calendar
- deleted: This is triggered when user delete existing schedule in the calendar

But, when I create new schedule in the calendar, Microsoft Graph send both `created` and `updated` notification to the webhook. From this experience, I'm confusing and asking this question. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbe0590e-070b-cf56-cbc7-1dcb8a266380
* Version Independent ID: 2d912536-afc5-60f1-e381-2eef892cbded
* Content: [subscription resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/subscription.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi!
Thanks for the feedback. The behavior you are describing is a known issue for Azure Active Directory resources (users, groups,...). Are you saying you are experiencing it also for events? Is there any other resource type you are experiencing it for as well?

**Comment by NT-D** [comment]
Yes, I'm experiencing it also for events in multiple tenants (my testing tenant and customer's testing tenant).
I only tried events, so I don't know other resource types.

**Comment by baywet** [comment]
thanks for the additional information! Assigned to @svpsiva to clarify the expected behavior here.

**Comment by oscarcosta** [comment]
Hi, I'm also experiencing this strange behaviour in email notifications. Our application only registers subscriptions using the changeType created. However, the application receives "created notifications" when the user deletes the email from any folder, including the trash folder.

**Comment by FaithOmbongi** [comment]
Hi @jumasure - Can you help provide a response to this issue? Thanks.
