### ISSUE TITLE
How to create multiple groups in one single API call

### ISSUE THREAD

**Issue by Kiranparab** [microsoftgraph/microsoft-graph-docs#7599]
How to create multiple groups in on single API request through POST

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331b476e-60fe-ebb0-ce4e-22de72bddf2a
* Version Independent ID: 58ceeaf1-7a48-41c0-9260-27a60d90ec57
* Content: [Create deviceCategory - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-shared-devicecategory-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-shared-devicecategory-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-shared-devicecategory-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Take a look at batching.  https://docs.microsoft.com/en-us/graph/json-batching
