### ISSUE TITLE
Updating email of B2B guest users

### ISSUE THREAD

**Issue by rayhogan** [microsoftgraph/microsoft-graph-docs#7602]
Whenever I try update mailNickName or userPrincipalName, I get an InvalidValue error. I've read elsewhere that for B2B accounts these properties are Read Only via Graph and can only be updated using PowerShell. Will we ever have support for this through Graph?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by inner** [comment]
@rayhogan the email address that you're trying to update with, its domain name must match your tenant domain name

**Comment by inner** [comment]
or must be in the verified domain list (check the verifiedDomains property)

**Comment by davidmu1** [comment]
Future functionality isn't discussed in this feedback forum. No change identified for this page. Closing the issue.
