### ISSUE TITLE
Batch requests

### ISSUE THREAD

**Issue by mikegoatly** [microsoftgraph/microsoft-graph-docs#7606]
I'm currently struggling to make use of the batch request capabilities of the .NET SDK. I can't find any documentation anywhere about how it can be accomplished other than in PRs like this https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/412, though that seems a bit out of date now.

It would be great if this page could give a couple of example of batching requests up and processing the results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a9eead3-fd14-629f-dd6d-55e0c51d74ff
* Version Independent ID: cc096658-8f79-45c2-9d42-69e4fe9a3a49
* Content: [Make API calls using the Microsoft Graph SDKs - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/create-requests?tabs=CS#feedback)
* Content Source: [concepts/sdks/create-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/create-requests.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Batch is documented here: https://docs.microsoft.com/graph/sdks/batch-requests?tabs=csharp
