### ISSUE TITLE
#Request-body section has invalid properties

### ISSUE THREAD

**Issue by JakeLunn** [microsoftgraph/microsoft-graph-docs#7613]
The request body section includes some properties which will cause a BadRequest error on post. Properties: @odata.context, createdDateTime, id, lastModifiedDateTime, publishingState, uploadState. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8da67bd-44bc-147c-a2c4-ab0c8dc06818
* Version Independent ID: 89de758e-8b41-e1a3-d03b-901738b92161
* Content: [Create officeSuiteApp - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-officesuiteapp-create?view=graph-rest-beta#request-body)
* Content Source: [api-reference/beta/api/intune-apps-officesuiteapp-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-apps-officesuiteapp-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for letting us know.  We'll work on cleaning this up in the next few doc update cycles.

Dave

**Comment by lramosvea** [comment]
Hi @triplanedave, was the documentation updated? If so, can we close this issue? Thanks

**Comment by triplanedave** [comment]
These have been cleaned up, closing this issue.
