### ISSUE TITLE
trying to utilize this for mass conversion

### ISSUE THREAD

**Issue by phillkOCCM** [microsoftgraph/microsoft-graph-docs#7614]
trying to utilize powershell to make the calls to invite 700 guests to an org. cant seem to get powershell to accept any format of the object json format for 'new-azureadmsinvitation' let me know if this is the worng forum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0170d-e214-ce6f-b7b4-589960e9962d
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/invitation.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by elisolMS** [comment]
@phillkOCCM This isn't really a support forum, but we can try to help.  What does your JSON and PS command look like, and what error are you getting?

**Comment by elisolMS** [comment]
Closing due to no response.
