### ISSUE TITLE
Subscription requirements

### ISSUE THREAD

**Issue by ms-willfid** [microsoftgraph/microsoft-graph-docs#7618]
We should document that at minimum Azure AD Premium P1 or higher is required to use the Azure AD Reporting API.

Otherwise MS Graph will throw a 401 Unauthorized: Neither tenant is B2C or tenant doesn't have premium license;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61cf8069-b779-ea2a-c02a-c8efd2e18019
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-1.0&source=docs#feedback)
* Content Source: [api-reference/v1.0/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/signin.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @kholtz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
This sentence is in the introduction paragraph: You must have an Azure AD Premium P1 or P2 license to download sign-in logs using the Microsoft Graph API. No change identified for the page. Closing the issue.
