### ISSUE TITLE
I can't get more than 20 messages

### ISSUE THREAD

**Issue by AgusL** [microsoftgraph/microsoft-graph-docs#7620]
hey guys, 
I can only get 20 message from a channel. I'm getting nextLink, put it on new request but is not working.
first call: https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages
nextLink: https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages?$skiptoken={id}

please, could you help me?

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a9873-c692-64f3-6185-d4177e5640db
* Version Independent ID: 6e39496f-94cc-2daf-17fe-f5a2590d2327
* Content: [Get channel message - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-get-message?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-get-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-get-message.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
By default, you will get only 20 records. You can use the $top query parameter to control the number of items per response. Maximum allowed value for $top is 50. The other OData query parameters are not currently supported.
https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http#optional-query-parameters
