### ISSUE TITLE
Online meeting created with help of Create Online Meeting API doesn't show in Teams Calendar

### ISSUE THREAD

**Issue by bijaykush** [microsoftgraph/microsoft-graph-docs#7628]
I used Create onlineMeeting API to create an online meeting in MS Teams with delegated permissions. In response, it provides me with the JoinURI of the Online meeting which is easily being accessed by the users.

Questions:

**1. Why doesn't it show that online meeting in Teams Calendar? Do I need to do anything else?**

**2. I also want to add participants through the API in the created online meeting event. Does Microsoft Graph API support this?**

```
Request:
var onlineMeeting = new OnlineMeeting
{
StartDateTime = DateTimeOffset.Parse("2020-04-08T21:30:34.2444915+00:00"),
EndDateTime = DateTimeOffset.Parse("2020-04-08T21:00:34.2464912+00:00"),
Subject = "Test Meeting",
};
```

I am looking for immediate help from anyone who can help with this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 148eb2e9-1b76-469f-ea6e-02dd51b71058
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mrahmadt** [comment]
Hi

Please check https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&tabs=http


`    Note: The meeting does not show up on the user's calendar.`

**Comment by ftomza** [comment]
Ok! How to make an event in the calendar with a meeting in the channel, as it is done from the Temas interface. Thanks!

**Comment by bijaykush** [comment]
Thank you for your reply. I find the solution. We can create the events in the calendar with the number of participants and the online meeting URL.
