### ISSUE TITLE
Any plans to support delta functionality for the "List chat messages" API?

### ISSUE THREAD

**Issue by tobiasviehweger** [microsoftgraph/microsoft-graph-docs#7631]
See title, would be appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675658fe-2bf6-fa95-ed24-22f744aefa65
* Version Independent ID: 60b1b2e7-6d8f-98c6-5b26-f8cb9e8dcdb2
* Content: [List chat messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/chatmessage-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jerem99** [comment]
I think using Webhook is the best approach for this.

**Comment by kumbhaj** [comment]
How do you use webhook

**Comment by Prasad-MSFT** [comment]
You can follow [this](https://docs.microsoft.com/en-us/graph/delta-query-overview#supported-resources) link to check for resources for which delta query is supported.

By using delta query, you can get new or updated messages in a channel.
https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-1.0&tabs=http

**Comment by tobiasviehweger** [comment]
Hi @Prasad-MSFT,
thanks - this was about chat messages, not channel messages - any plans to have the delta thing also work for chats?

**Comment by Prasad-MSFT** [comment]
@tobiasviehweger 
For now, only delta functions for Chat messages in a channel is supported
