### ISSUE TITLE
Missing properties in the occurrences of recurring events

### ISSUE THREAD

**Issue by PietroCaldana** [microsoftgraph/microsoft-graph-docs#7632]
When i call the the following endpoint
/users/{userId}/calendars/{calendarId}/calendarView/delta?startDateTime={start}&endDateTime={end}
i get the list of all normal events with all their properties correctly set. But if there are recurring events, their occurrences only have these properties: @odata.type, @odata.etag, seriesMasterId, type, id, start, end.
The docs don't say anything about this. Should i read all the other properties from the master event?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da37d83f-dd2b-dd85-eb5d-75208e26412d
* Version Independent ID: aa5f5279-bec8-fe6e-ab1b-8dc87f2ed688
* Content: [Get incremental changes to events in a calendar view  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-events?tabs=http#feedback)
* Content Source: [concepts/delta-query-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-events.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by corytheboyd** [comment]
I do agree that the documentation could do a better job explaining this, but it does seem acceptable to me to rely on retrieving these details from the series master event. An occurrence should be viewed as more of an ephemeral resource, it's there for your convenience, but really it's just derived from the master event's recurrence pattern. You'll notice that when you modify an occurrence it becomes an exception, and that that exception has all of the normal event attributes you would expect it to, think of that action as taking the "ephemeral" occurrence and promoting it to a full, real event.

**Comment by pashvin** [comment]
isn't calendarView should give all properties for occurrence? As per my understanding event request gives only master one vs calendarView gives all occurrences with all attributes but when those request goes with delta param, then calendarView starts giving master records. So this looks like a bug in software and not a documentation issue.

**Comment by Harini84** [comment]
Tried in both Graph v1.0 and beta. Issue could not be reproduced.

**Comment by Harini84** [comment]
This issue could not be reproduced. In delta call for seriesMaster all the properties can be retrieved in /users call in both v1.0 and beta.

Thanks
