### ISSUE TITLE
I can't get more than 20 messages, nextlink seems broken

### ISSUE THREAD

**Issue by AgusL** [microsoftgraph/microsoft-graph-docs#7636]
hey guys,
I can only get 20 message from a channel. I'm getting nextLink, put it on new request but is not working.
first call: https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages
nextLink: https://graph.microsoft.com/beta/teams/{id}/channels/{id}/messages?$skiptoken={id}

please, could you help me?

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by emreyigit** [comment]
I am having a similar thing at the beta version. Whenever request me.chats.{id}.messages, I am able to read the first page but rest.

https://graph.microsoft.com/beta/me/chats/{id}/messages is working

https://graph.microsoft.com/beta/me/chats/{id}/messages?skiptoken..... is not working
It returns Bad Request with no detail.

{ "error": { "code": "BadRequest", "message": "Bad Request", "innerError": { "date": "2020-08-27T07:26:45", "request-id": "23b3f1c0-d0c4-45f2-95ca-017a8b819650" } } }

**Comment by mamilov** [comment]
+1, same problem

**Comment by HunaidHanfee-MSFT** [comment]
Please let us know if you are still facing this issue.
