### ISSUE TITLE
Get all Online Meetings

### ISSUE THREAD

**Issue by cconrado** [microsoftgraph/microsoft-graph-docs#7641]
Trying to see how you can get the Video Conference Id. The docs dont say how. Is that because its not possible or I'm doing it wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f89278-6b03-e6e4-66a3-2127a11750fe
* Version Independent ID: f6f92861-6d72-2260-2277-d963793fbce2
* Content: [Get onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @cconrado Video Teleconferencing (VTC) Ids are generated through meeting room devices. You must be a [Cloud-Video-Interop](https://docs.microsoft.com/en-us/microsoftteams/cloud-video-interop) licensed user.

**Comment by cconrado** [comment]
@ananmishr I don't get why you closed it. I'm asking getting it through graph not another method.
