### ISSUE TITLE
Clarify that compliance recording policy is required for calling this API

### ISSUE THREAD

**Issue by alexpls** [microsoftgraph/microsoft-graph-docs#7642]
Attempts to call this API will result in an error unless an appropriate compliance recording policy has been created.

For more info see: https://docs.microsoft.com/en-us/powershell/module/skype/new-csteamscompliancerecordingpolicy?view=skype-ps

An example of how to set up a compliance recording policy is at: https://github.com/FTRLabs/microsoft-graph-comms-samples/tree/master/Samples/BetaSamples/LocalMediaSamples/PolicyRecordingBot#create-an-application-instance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74f9306-ae6b-8294-1716-dcf696834f3d
* Version Independent ID: 75c9c443-2601-5484-c06c-065e4e26f0af
* Content: [call: updateRecordingStatus - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/call-updaterecordingstatus?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/call-updaterecordingstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/call-updaterecordingstatus.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
You are correct, the updateRecordingStatus API can only be called as part of a policy based recording solution.
