### ISSUE TITLE
Failure - Status Code 0, 

### ISSUE THREAD

**Issue by abiarge** [microsoftgraph/microsoft-graph-docs#7646]
Using the /drives/{drive-id}/items/{item-id}/content endpoint

The GET request in graph explorer gives this error with payload: 
`{
    "isTrusted": true
}`

Also, when calling from an outlook add-in (with proper access token and permissions set in Azure), I get a CORS error...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01fa814a-c3b6-d48a-b724-a63e948bbffd
* Version Independent ID: f417cf48-5780-ebf4-1470-1bf0855d62c1
* Content: [Download a file - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by christianbeland** [comment]
Same problem here. Found any solution?

**Comment by abiarge** [comment]
> Same problem here. Found any solution?

Hi, christian. The problem still persists

**Comment by christianbeland** [comment]
It’s the graph explorer that cannot download file.

Also, when using curl from terminal, you have to add -L option to follow redirect to file content.


Christian Béland

**Comment by abiarge** [comment]
> It’s the graph explorer that cannot download file. Also, when using curl from terminal, you have to add -L option to follow redirect to file content. Christian Béland
> […](#)
> On May 6, 2020, at 7:23 AM, abiarge ***@***.***> wrote: ﻿ Same problem here. Found any solution? Hi, christian. The problem still persists — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

what about trying to invoke the Graph endpoint from an outlook add-in? Because I get a CORS error and I'm sucessfully calling the Graph API for other purposes (such as getting the sites in the tenant or uploading content to a file via PATCH)
![image](https://user-images.githubusercontent.com/61998411/81178767-04bd9600-8fa9-11ea-971b-ce91aaf2049a.png)

**Comment by kostenickj** [comment]
Im getting the same error. Will this ever be fixed?

**Comment by crf200** [comment]
I'm running into the same issue trying to build a spfx webpart. I've found that there are some headers to include but there's no documentation of how to do that. 
```
Access-Control-Allow-Origin : *
mode : CORS
```
