### ISSUE TITLE
signInActivity permissions

### ISSUE THREAD

**Issue by roorz** [microsoftgraph/microsoft-graph-docs#7647]
Is there a permission that is required to query this property? For example:

```
https://graph.microsoft.com/beta/users?$top=5&$select=id,displayName,signInActivity
```

Gives this response:

```
{
    "error": {
        "code": "Authentication_RequestFromUnsupportedUserRole",
        "message": "User is not in the allowed roles",
        "innerError": {
            "request-id": "c9c8d936-e160-4d62-a0f4-f6c370513cd4",
            "date": "2020-04-07T10:02:04"
        }
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0f258b-b61e-72a2-0caf-d9b7fff5857d
* Version Independent ID: 90c2edf2-51ee-6bab-84a6-3710a3f0ccd2
* Content: [signInActivity resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signinactivity.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RaghuramP** [comment]
Yes, Directory.Read.All or Organisation.Read.All

**Comment by BigEaseGueldi** [comment]
I was able to make that call (App Permissions) just with User.Read.All.

**Comment by FaithOmbongi** [comment]
@roorz You need to consent to the **AuditLog.Read.All** permission.
