### ISSUE TITLE
Support signInActivity property in $select

### ISSUE THREAD

**Issue by roorz** [microsoftgraph/microsoft-graph-docs#7648]
Can ```signInActivity``` be added to the supported ```$select``` properties? This is required so we can easily query the last sign-in details for all users in a specific AAD group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a73e08e0-aa5c-dde2-6e05-240052049a67
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Your suggestion has been communicated to engineering. No change currently identified for this page. Closing the issue.
