### ISSUE TITLE
$filter not work for the findRooms api

### ISSUE THREAD

**Issue by xhr0804** [microsoftgraph/microsoft-graph-docs#7650]
When I use $filter to get the specific room, the result remains to be all the room result.
![image](https://user-images.githubusercontent.com/44257569/78666598-207e3f80-790a-11ea-9771-c31ae912cf92.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e112f02f-d98f-e863-dfc2-f1c80530d65c
* Version Independent ID: 136af786-1231-28db-9de4-a44b59e066f2
* Content: [user: findRooms - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-findrooms?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-findrooms.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-findrooms.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vrod9429** [comment]
Hi @xhr0804 This API does not support filtering. You can use our new [Places API](https://docs.microsoft.com/en-us/graph/api/place-get?view=graph-rest-beta&tabs=http) that will allow for filtering and will return more metadata about a room.
