### ISSUE TITLE
Support of multi purpose certificates and Intune Graph API

### ISSUE THREAD

**Issue by KeyTalk** [microsoftgraph/microsoft-graph-docs#7651]
It's very common for a certificate as issued by a trusted certificate provider, to be usable for digital signing, and for encryption, and for authentication (both Wifi and VPN).
It seems that such certificates are not useful now, as its not possible to given an uploaded certificate a value of 1, 2, 4 and 8. Uploading the certificate multiple times with independent values of 1, 2, 4 and 8 results in an error, stating "Already Exists".
So how to deal with multi purpose certificates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe1fe71-725e-7f96-641f-01b73250f059
* Version Independent ID: d6cf7667-8c95-6c6e-466c-c1f28df2784e
* Content: [userPfxIntendedPurpose enum type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-raimportcerts-userpfxintendedpurpose?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/intune-raimportcerts-userpfxintendedpurpose.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-raimportcerts-userpfxintendedpurpose.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
When you upload the cert, the purpose value you give is just a way to group.  There isn’t a check to ensure that you are uploading a signing vs encryption vs auth cert.  So you can just assign the different values without re-uploading.
