### ISSUE TITLE
Issue - List mail folder limit -10

### ISSUE THREAD

**Issue by YagzanManjunath** [microsoftgraph/microsoft-graph-docs#7653]
Only 10 folders are listed in Java api call for List mail folders

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad44cdb-5d58-2689-6731-f9b1f791c33f
* Version Independent ID: 5f41b59d-994a-36d8-978f-db8a738fe10d
* Content: [List mailFolders - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-mailfolders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-mailfolders.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@svpsiva , list mailfolders (specified below) should return all the mail folders in the specified user's mailbox?

GET /users/{id | userPrincipalName}/mailFolders

**Comment by YagzanManjunath** [comment]
I use the following snippet to acquire the mailfolders.
`IMailFolderCollectionPage mailFolderCollectionPage = graphServiceClient.users(mailBoxName).mailFolders()
                    .buildRequest()
                    .get();`

When I try to get the contents of the page through `mailFolderCollectionPage .getCurrentPage()` , I am able to acquire a List with size =10.
This can be overcome by adding `queryOptions.add(new QueryOption("top", 100))` as shown in the image . But why is the default size limited to  10?
![Screenshot (15)](https://user-images.githubusercontent.com/58413147/78746019-69260f00-7983-11ea-8cfa-1c7e196cbdac.png)
![Screenshot (16)](https://user-images.githubusercontent.com/58413147/78746020-6a573c00-7983-11ea-8eb3-83ec5cf44542.png)

**Comment by svpsiva** [comment]
Default is set to 10. This is expected behavior. As you realized, there is a way to fetch more folders per API call.
