### ISSUE TITLE
IdentityUserRisk always returns null.

### ISSUE THREAD

**Issue by lihad** [microsoftgraph/microsoft-graph-docs#7675]
When pulling user data via a Graph API request in C#, IdentityUserRisk always returns null.  This is true regardless of whether or not the user has an actual risk score above 0 when viewing directly within the Cloud App Security console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d24b1d9-ee3e-32ca-5c86-aebef8f09a85
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&tabs=csharp#feedback)
* Content Source: [api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@lihad - IdentityUserRisk is not a property that is available on the user resource. Also, the https://docs.microsoft.com/en-us/graph/api/resources/identityriskevent?view=graph-rest-beta resource has been deprecated. This is the note in the page:

The identityRiskEvents API is deprecated and will stop returning data on January 10, 2020. For details, see Deprecation of the IdentityRiskEvents API.

No change identified for this page. Closing the issue.
