### ISSUE TITLE
org-wide?

### ISSUE THREAD

**Issue by Mike-Crowley** [microsoftgraph/microsoft-graph-docs#7695]
There is a 3rd type of visibility for org-wide. How is this set programmatically? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5299d673-b366-180a-f017-a0e30d2ff24f
* Version Independent ID: 1fa6683f-3e4e-9ef7-d0bb-907abe0a6249
* Content: [Members - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/teamvisibilitytype?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/teamvisibilitytype.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/teamvisibilitytype.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ahouck** [comment]
I would also like this functionality

**Comment by Sarah4x** [comment]
I second this. How do I know if a team is set to Org-wide by using the API? I noticed that Org-wide teams have the following in the group JSON.

  "creationOptions": [
        "Team",
        "ExchangeProvisioningFlags:3552"
    ],

Is this flag part of Org-wide teams? Could I check for this Exchange flag to test if a site is Org-wide?

**Comment by anandab-gt** [comment]
As of now, org-wide visibility is not supported through graph API
