### ISSUE TITLE
Examples in documentation does not work

### ISSUE THREAD

**Issue by davidsteinsland** [microsoftgraph/microsoft-graph-docs#77]
From: http://graph.microsoft.io/docs/overview/query_parameters

> $filter
> [...]
> GET https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,'Garth')

Response:

```
{
  "error": {
    "code": "ErrorInvalidUrlQueryFilter",
    "message": "'contains' and 'startswith' are not supported for filtering.  Use Search instead.",
    "innerError": {
      "request-id": "48b73c4c-475c-4a53-9825-0f39f87fcc33",
      "date": "2015-12-10T09:36:25"
    }
  }
}
```

`https://graph.microsoft.com/v1.0/me/contacts?$search=startswith(displayName,'Garth')` gives:

```
{
  "error": {
    "code": "BadRequest",
    "message": "Syntax error: character '(' is not valid at position 10 in 'startswith(displayName,'Garth')'.",
    "innerError": {
      "request-id": "eb90e818-4504-4f7a-aaab-98fd6c9edf2a",
      "date": "2015-12-10T09:36:46"
    }
  }
}
```

So exactly how is filtering supported?

**Comment by martellaj** [comment]
Thanks, @davidsteinsland. This is an area we need to document more clearly. @dkershaw10, can you shed light on the filtering?

**Comment by dkershaw10** [comment]
Thanks for reporting this @davidsteinsland. So the first query is supported (tried it myself and it works fine).  Will look up the error trace and see what the logs indicate for your request. For the second, I'm not sure that you can use startswith syntax with $search.  I think startswith is a $filter expression only.

**Comment by dkershaw10** [comment]
@davidsteinsland:
Just took a look at the logs.  GET https://graph.microsoft.com/v1.0/users?$filter=startswith(displayName,'Garth') should work fine.  However the logs indicate that your query was GET https://graph.microsoft.com/v1.0/contacts?$filter=startswith(displayName,'Garth').  I don't believe $filter is supported on contacts.  Our OData operator support is not consistent across the entity sets, and we need to improve the support/consistency here , as well as improving the documentation as @martellaj says.

**Comment by jincyabraham27** [comment]
I am trying to filter the events from the calendar using the Microsoft Graph API.I want to use the startswith or ends with clause for filtering..for eg GET https://graph.microsoft.com/v1.0/me/events?$filter=endswith(subject,'code') and location/displayName eq 'Canada'.I get a bad request with the endswith and no data for location/DisplayName.So how is the filtering supported for events?

**Comment by marych** [comment]
endswith is not supported for events, but startswith is. The following 2 work fine for me:
https://graph.microsoft.com/v1.0/me/events?$filter=startswith(subject,'code')
https://graph.microsoft.com/v1.0/me/events?$filter=location/displayName%20eq%20'Skype%20Meeting'

**Comment by mikeholtkamp** [comment]
Is there any news about the odata query param support documentation.
Without the documentation it's a little gamble game for example

This works:
https://graph.microsoft.com/beta/contacts?$filter=startswith(givenName,'mi')

This doesn't 
https://graph.microsoft.com/beta/me/contacts?$filter=startswith(givenName,'mi')

**Comment by MJems** [comment]
How to apply filter for search text using linq

   var mailResults = await (from i in outlookServicesClient.Me.Folders.GetById("Inbox").Messages
                                
                                 orderby i.DateTimeReceived descending
                                 select i).Skip((pageNo - 1) * pageSize).Take(pageSize).ExecuteAsync();

**Comment by keyur32** [comment]
Looks like this has been resolved. Please reactivate.
