### ISSUE TITLE
Create windowsUniversalAppX error

### ISSUE THREAD

**Issue by leo180c** [microsoftgraph/microsoft-graph-docs#7705]
Hi there,

We encountered an error when request "Create windowsUniversalAppX" via graph API, would you kindly provide help?

API details:
https://docs.microsoft.com/en-us/graph/api/intune-apps-windowsuniversalappx-create?view=graph-rest-1.0

Request Json:
{"@odata.type":"#microsoft.graph.windowsUniversalAppX","id":"dasda0s98dasidasdksdksds","displayName":"Slack","description":"Slack","publisher":"Slack Technologies Inc.","largeIcon":null,"createdDateTime":"2020-04-08T08:31:28Z","lastModifiedDateTime":"2020-04-08T08:31:28Z","isFeatured":false,"privacyInformationUrl":"","informationUrl":null,"owner":"","developer":"","notes":"","publishingState":"published","committedContentVersion":"1","fileName":"91750D7E.SLACK_4.4.2.0_X64__8SHE8KYBCNZG4.APPX","size":75235456,"applicableArchitectures":"x64","applicableDeviceTypes":"desktop","identityName":"91750D7E.Slack","identityPublisherHash":"8she8kybcnzg4","identityResourceIdentifier":null,"isBundle":false,"identityVersion":"4.4.2.0","minimumSupportedOperatingSystem":{"v8_0":false,"v8_1":false,"v10_0":true}}

Response Error:
{"error":{"code":"BadRequest","message":"{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 57dfe8d7-fe64-43e8-b2bc-c548b61bf0c6 - Url: https:\/\/fef.msuc01.manage.microsoft.com\/AppLifecycle\/StatelessAppMetadataFEService\/deviceAppManagement\/mobileApps?api-version=2018-03-22\",\r\n  \"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{}\"\r\n}","innerError":{"request-id":"57dfe8d7-fe64-43e8-b2bc-c548b61bf0c6","date":"2020-04-10T02:02:43"}}}

Besides, how can we upload the windows appx binary after app creation via Graph API ?

Thanks,
Leo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecd79c9-490b-8ab9-6f89-04c25f9aa579
* Version Independent ID: 2156a09e-f6b7-5925-6d0d-e3ad495f8544
* Content: [Create iosLobApp - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-apps-ioslobapp-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-apps-ioslobapp-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-apps-ioslobapp-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks Leo.  I see a similar error using the sample JSON in the help topic.  We'll have someone on the team take a look at why it's failing.  In the mean time, you might take a look at the PowerShell sample scripts here for LOB app upload of mobile (and Win32) apps to understand the process. https://github.com/microsoftgraph/powershell-intune-samples/tree/master/LOB_Application
