### ISSUE TITLE
Microsoft Graph Api limitation - there isn't enough information about zone id to specify working 

### ISSUE THREAD

**Issue by fenixcommunity** [microsoftgraph/microsoft-graph-docs#7709]
Hello team,
thanks for the great API.

I request to provide more info about Zone Id in Calendar Working Hours.
We have the first user with TimeZoneBase - Central European Standard Time (hidden for us Warsaw id)
The second user also with TimeZoneBase - Central European Standard Time (hidden for us Algeria Time Zone id)

But the first user has set calendar Warsaw time zone ID(offset +2H), second Algeria Time Zone(offset +1). Both Central European Standard Time.

It is difficult to define time zone offset.

Could you provide info about zone region (for example: Sarajevo/ Skopje, Warsaw, Zagreb)
or (Poland/Warsaw).

best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a6748e9-6e15-db5e-f85f-79dbe8171e9b
* Version Independent ID: a30e4438-c54b-643f-5573-c904ace73e70
* Content: [Get free/busy schedule of users and resources - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-get-free-busy-schedule#feedback)
* Content Source: [concepts/outlook-get-free-busy-schedule.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-get-free-busy-schedule.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @fenixcommunity , I am curious, for the user in Warsaw time (UTC+2), wouldn't one specify the time zone as "Central European Summer Time" instead of "Central European Standard Time"?

Are you're requesting an enhancement of the API?

**Comment by fenixcommunity** [comment]
Thanks for your answer.
I'm requesting for API enhancement.
For Warsaw time zone should be now Central European Summer Time.
https://greenwichmeantime.com/time-zone/europe/european-union/poland/time/

**Comment by angelgolfer-ms** [comment]
@fenixcommunity , thank you for the clarification. I'll relay your input to the corresponding service owner.
In addition, can you please go to [UserVoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359572), either check and vote for an item if there's already an item that matches your request, or enter a new item if there isn't an existing one? This is a more systematic approach to aggregate customer feature requests, so to help service owners prioritize such asks.
Thank you for your support!
