### ISSUE TITLE
Some remarks from the field...

### ISSUE THREAD

**Issue by wimvanhouts** [microsoftgraph/microsoft-graph-docs#7710]
Hi, for those who are testing and/or planning on using this, bear in mind two things:
1. Have patience. From experience, when setting a license for a (resource) account, it can take minutes up to hours before this is "known" in the system. This is true when assigning all sorts of licenses, for example, if you want to enable enterprise voice for a user and assign him an E5 license or other valid combination, it took several hours in our tenant before this came effective.
2. You cannot test this with an office developer account and O365 E5 developer tenant that you get with this developer account.  It is not possible to add phone system virtual user licenses in this tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1892fb12-8994-0c53-e761-c8c75360e792
* Version Independent ID: 3fdd5b67-a0d9-2122-2f8a-6110ba9b25a0
* Content: [Manage phone numbers for bots - Microsoft Graph](https://docs.microsoft.com/en-us/graph/cloud-communications-phone-number)
* Content Source: [concepts/cloud-communications-phone-number.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/cloud-communications-phone-number.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Thank you for your feedback @wimvanhouts We welcome any more questions or suggestions that you may have. I'll close this issue for now.
