### ISSUE TITLE
Python example

### ISSUE THREAD

**Issue by mdhruv1** [microsoftgraph/microsoft-graph-docs#7712]
Please can we also get a python example for this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01fa814a-c3b6-d48a-b724-a63e948bbffd
* Version Independent ID: f417cf48-5780-ebf4-1470-1bf0855d62c1
* Content: [Download a file - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-get-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-get-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by mathewrtaylor** [comment]
Echoing my sentiment for the same, please!
