### ISSUE TITLE
Patch Doesn't Work

### ISSUE THREAD

**Issue by cconrado** [microsoftgraph/microsoft-graph-docs#7717]
I'm getting "code": "No method match route template",

Was the docs miss typed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e40b56-d4b7-dc58-7825-4b7dae522157
* Version Independent ID: 5d96219b-20b6-190d-396d-b6541615401a
* Content: [Update windowsAutopilotDeviceIdentity - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-windowsautopilotdeviceidentity-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-enrollment-windowsautopilotdeviceidentity-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-windowsautopilotdeviceidentity-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by portaldotjay** [comment]
I don't think the doc was mistyped as much as it just shouldn't exist. When updating windowsAutopilotDeviceIdentity, you should use POST /deviceManagement/windowsAutopilotDeviceIdentities/{windowsAutopilotDeviceIdentityId}/updateDeviceProperties, which is another page in the docs.

**Comment by cconrado** [comment]
@portaldotjay as in it's going to be a page soon? I couldn't find that page.

**Comment by portaldotjay** [comment]
https://docs.microsoft.com/en-us/graph/api/intune-enrollment-windowsautopilotdeviceidentity-updatedeviceproperties?view=graph-rest-beta

**Comment by cconrado** [comment]
@portaldotjay lol of course I search and it doesnt pop up. Thanks for the help 👍🏻

**Comment by portaldotjay** [comment]
Yeah, kind of weird that there are two pages for the same actions. Hopefully it gets removed soon. I've seen it creating confusion for some others as well.
