### ISSUE TITLE
Outdated Postman sharing link

### ISSUE THREAD

**Issue by nprieto95** [microsoftgraph/microsoft-graph-docs#7722]
The sharing link provided here is not up to date, and it is missing the Subscription Validation request (in the "Misc" folder which is also not present).
In GitHub it looks like this request was added only 23 days ago so maybe it's just a matter of refreshing the link or generating a new one for the current version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 142c7d14-408c-e23d-a2b3-f08b815e09e5
* Version Independent ID: d13758c7-dd3c-1744-6163-b042c0e4afce
* Content: [Use Postman with the Microsoft Graph API - Microsoft Graph](https://docs.microsoft.com/en-us/graph/use-postman#using-the-collection)
* Content Source: [concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/use-postman.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
Its linked to the master branch of the file. I've checked that and the misc folder is in there.

Are you sure @nprieto95  that Postman isn't caching it. It won't override your current collection, it'll great a new one.

**Comment by nprieto95** [comment]
There are actually two links:

1. 
![image](https://user-images.githubusercontent.com/33283964/79333448-efe36a80-7ef4-11ea-9622-adb052550099.png)
This is the first one, and it points to https://www.getpostman.com/collections/d89a737b5f0c0825898a

2.
![image](https://user-images.githubusercontent.com/33283964/79333531-15707400-7ef5-11ea-8d15-00c3439ac707.png)
This is the second one, and it points to https://raw.githubusercontent.com/microsoftgraph/microsoftgraph-postman-collections/master/Microsoft%20Graph.postman_collection.json

The thing is, the first one is not actually opening Postman, it takes you yo the JSON to visualize it (at least on Edge), and when I import it the result is different from that of the second link. Specifically:
![image](https://user-images.githubusercontent.com/33283964/79333644-4650a900-7ef5-11ea-8564-c07cab79ffac.png)
One has 136 requests and the other one has 131. If one is for the beta and the other is for 1.0, it would be beneficial if it said that on the document, but I think Change Notifications are a 1.0 feature so that's why I thought this was an outdated link.

Please let me know if you need further information. Glad to help.

**Comment by jthake-msft** [comment]
Yep sorry this is my fault. Thanks for pointing that out!

**Comment by jthake-msft** [comment]
This is now adjusted. We can't recommend the share approach as it doesn't keep up to date. I've got an ask in with Postman to fix this.
