### ISSUE TITLE
Update intro paragraph to include MS Identity Platform v2.0

### ISSUE THREAD

**Issue by crshovrd41** [microsoftgraph/microsoft-graph-docs#7723]
This article directs you to two out of date articles referencing v1.0. 

You should also include https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-overview as a link as this is the future of the identity platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 901ad71a-7fa8-cb4a-ffe4-396d6b52ccf9
* Version Independent ID: 903c43d0-41d3-99cf-c289-644e64c9b801
* Content: [Call Microsoft Graph from a Cloud Solution Provider application - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-cloudsolutionprovider#feedback)
* Content Source: [concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-cloudsolutionprovider.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @crshovrd41 for raising this issue. This has since been resolved. Closing this issue.
