### ISSUE TITLE
How to create a meeting with an event

### ISSUE THREAD

**Issue by ftomza** [microsoftgraph/microsoft-graph-docs#7724]
Hi!
I am trying to create a meeting, and there are several ways to do this. 
1. Create an event via a calendar with a meeting. In this case, an event is created with a global meeting, or rather a meeting via a link. 
2. Create a meeting via cloud communications. In this case, you can create a meeting in the teams channel, which is what I need, but there is no event for this meeting (this is written in the documentation), and this meeting cannot be edited through the teams channel, and is only available via the link

As a result, you need to create an event in the teams channel with the event and restrict it to a specific list of participants, as well as edit it through the teams channel, as is done through the teams web interface. Thanks for the help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51335f6c-3370-4597-1b22-10aa2d7c429f
* Version Independent ID: dfa0e4c5-38d0-6aa0-6d5b-e35f66c78135
* Content: [Create event - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-post-events.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ajayvjain** [comment]
Do we have this functionality built into the APIs?

**Comment by ftomza** [comment]
Yes, we need support for creating meetings in event-enabled teams through msgraph

**Comment by lucas-faust** [comment]
@ftomza hey there, were you able to do that?
I also saw that the request doesn't support participants. How should you invite others then?

**Comment by HunaidHanfee-MSFT** [comment]
Please have a look at this : https://docs.microsoft.com/en-us/graph/outlook-calendar-online-meetings?tabs=http

Let us know if you have any query.

**Comment by HunaidHanfee-MSFT** [comment]
Please see this document to see the comparison between two.
[Choose an online meeting api](https://docs.microsoft.com/en-us/graph/choose-online-meeting-api)
Thanks

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
