### ISSUE TITLE
Screenshare time, Videotime, and audio time?

### ISSUE THREAD

**Issue by jflor041** [microsoftgraph/microsoft-graph-docs#7726]
is it possible to get the length of the screenshare time, video calls length and same with audio length via Graph API? 
we can download the data via Teams Admin -&gt; Analytics & reports. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa64daf9-bfd7-bfe0-0a4a-cec6b062a192
* Version Independent ID: a2b14964-5512-9183-9cc8-ad00e55e146d
* Content: [reportRoot: getTeamsUserActivityUserDetail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivityuserdetail?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/reportroot-getteamsuseractivityuserdetail.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @pranoychaudhuri
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dataoracle** [comment]
I had created one idea on Microsoft Voice to propose a more consistent information availability between the Graph API and the Teams Admin center reporting. If you are interested on this please consider voting for it!

https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/40214689-add-daily-information-to-teams-admin-center-usage

**Comment by junhui** [comment]
not only the time and also the audio count/message count only include 1:1, group chat not counted. 

the information is really helpful, hope can bring MS attention and priority.

**Comment by mark3grahams** [comment]
I would like parity with the Teams Admin center > Analytics & reports

**Comment by maciz84** [comment]
+1

**Comment by Elpinoino** [comment]
Still a wanted request.... One should think it is an easy fix since this is available from the TAC.

**Comment by mark3grahams** [comment]
Nice. It only one year to review and close an issue summarily.

**Comment by mark3grahams** [comment]
You suck.
