### ISSUE TITLE
API permissions in Azure AD client app(app user)  to call Graph search api for driveItem

### ISSUE THREAD

**Issue by sidhaw** [microsoftgraph/microsoft-graph-docs#7727]
What API permissions does Azure AD client app needs to get app token for calling Graph search for microsoft.graph.driveItem ?
According to the documentation I only need the following permissions:
Sites.Read.All, Sites.ReadWrite.All
But, when i use token returned , it doesnt work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nsyngaivskyi** [comment]
I test permissions here: 
https://developer.microsoft.com/en-us/graph/graph-explorer

When you choose "search driveitems" it suggests to "enable Files.Read.All". 

Maybe it will help you.

**Comment by heshansp** [comment]
Think I'm having the same issue. While my Service Principal has the "Files.Read.All" permission, I still get the following error;

```json
{
  "error": {
    "code": "0x713DBA9F",
    "message": "\r\n The call failed, please try again. ",
    "innerError": {
      "request-id": "5e48a0bb-b3ba-4257-b3d2-31ccfb0f5d65",
      "date": "2020-05-10T07:52:17"
    }
  }
}
```

**Comment by nmoreau** [comment]
@heshansp - Your call is failing due to an authorization issue.
Couple things to check.
1. Make sure you send a Delegated Auth token. Application token are not supported.
2. I can see you are sending the right Scope (File.Read.All). But in order to check that the auth token contains all the right information, I would fiddle the calls you are making, and compare them with those who are sent using the Graph PostMan Collection. You should then be able to understand what is missing in your auth token.
Hope this helps.

**Comment by sidhaw** [comment]
> Think I'm having the same issue. While my Service Principal has the "Files.Read.All" permission, I still get the following error;
> 
> ```json
> {
>   "error": {
>     "code": "0x713DBA9F",
>     "message": "\r\n The call failed, please try again. ",
>     "innerError": {
>       "request-id": "5e48a0bb-b3ba-4257-b3d2-31ccfb0f5d65",
>       "date": "2020-05-10T07:52:17"
>     }
>   }
> }
> ```

@heshansp , As mentioned by @nmoreau above, Application/Service Principal based authn is not supported for Graph Search APIs. You need to get the token On behalf of a user for delegated Authentication

**Comment by heshansp** [comment]
Thanks guys! I will try this out and let you know!! Thanks again for the help!

**Comment by janmechtel** [comment]
I'm confused why this is not working for Application token, but this here mentions it:
>Search requests run in the context of the signed-in user, identified using an access token with delegated permissions.
https://docs.microsoft.com/en-US/graph/api/resources/search-api-overview?view=graph-rest-beta

This SO question says it should be working: https://stackoverflow.com/questions/52446307/does-microsoft-graph-api-search-work-when-using-app-only-token

But that seems to be the v1 Drives Search which explicitly mentions support for application tokens: https://docs.microsoft.com/en-us/graph/api/driveitem-search?view=graph-rest-1.0&tabs=http 

(Also when I remove Files.Read.All permission i will get a different exception. Only after adding Files.Read.All permission i will get the same exception as @heshansp)
