### ISSUE TITLE
Always get AuthenticationError

### ISSUE THREAD

**Issue by syarifme** [microsoftgraph/microsoft-graph-docs#7731]
I use "get access withous user" scenario and work well when I only get user's profil by userPrincipalName. However, I always get "AuthenticationError" when I access others. I have granted admin consent from portal azure and from popup form for /adminsonsent

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
A long time since this issue was raised but do you still experience this @syarifme ? If so, could you clarify if what fails is getting user by id?
