### ISSUE TITLE
$skip has no affect on the end point to list schemaExtensions.

### ISSUE THREAD

**Issue by rabwill** [microsoftgraph/microsoft-graph-docs#7739]
I am using `https://graph.microsoft.com/v1.0/schemaExtensions?$top=10&$skip=10` end point to GET 10 items , skipping the first 10 items (paging) but every time the results are the same and skip is ignored as if I am calling `https://graph.microsoft.com/v1.0/schemaExtensions?$top=10` . What could I be doing wrong? Or is `skip` not supported in this API? @jthake-msft we are trying to use this endpoint for a new command in O365 CLI, any help will be appreciated. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d950a443-0656-d29b-6a3b-d18c2f5d092c
* Version Independent ID: 424c99df-a666-7303-5b23-3f03b14aecc0
* Content: [List schemaExtensions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/schemaextension-list.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
hey @rabwill we're trying to make GitHub more about docs content suggestions. Not troubleshooting APIs. We really want you to go to stackoverflow.com and tag Microsoft-graph for these types of queries.

**Comment by rabwill** [comment]
Sure thing Jeremy. Sorry for the trouble.
