### ISSUE TITLE
/drive/root/createdByUser/planner/plans API retrun 500 error

### ISSUE THREAD

**Issue by johnnyzhangcd** [microsoftgraph/microsoft-graph-docs#7741]
This API is not working. 
And I can't find this API in the Graph Explorer
{
    "error": {
        "code": "InternalServerError",
        "message": "Error processing response from backend service.",
        "innerError": {
            "request-id": "8d0502db-4132-456e-84a2-c6f13585fe04",
            "date": "2020-04-14T05:20:15"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f60667-9c25-f040-1bb0-b214ad2d55cb
* Version Independent ID: e00d1752-cfad-d7d5-93a1-d4de96e8aa09
* Content: [List tasks - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/planneruser-list-tasks?view=graph-rest-1.0&tabs=java#feedback)
* Content Source: [api-reference/v1.0/api/planneruser-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/planneruser-list-tasks.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Sacinandan** [comment]
Same issue

```
{
    "error": {
        "code": "InternalServerError",
        "message": "Error processing response from backend service.",
        "innerError": {
            "date": "2020-10-14T11:22:19",
            "request-id": "6982c6cc-b806-4b5c-826d-18f9e1dcf141",
            "client-request-id": "6982c6cc-b806-4b5c-826d-18f9e1dcf141"
        }
    }
}
```
