### ISSUE TITLE
Property "type" is case-sensitive

### ISSUE THREAD

**Issue by fume** [microsoftgraph/microsoft-graph-docs#7743]
The possible values for the property "type" are case sensitive. Possible values are "Scope" or "Role". Note the S and R are uppercase while the documentation spells it in lowercase. Using the lowercase ones, you'll get a BadRequest error back: "Invalid value specified for property 'type' of resource 'ResourceAccess'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d74f81-566f-f497-75f1-61ea6d0d9f5c
* Version Independent ID: 5ad4a6e4-b716-9a8f-adce-a7768f31e088
* Content: [resourceAccess resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/resourceaccess?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/resourceaccess.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/resourceaccess.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
@fume Thanks for the feedback! This has been fixed now.
