### ISSUE TITLE
What about the notes property? 

### ISSUE THREAD

**Issue by logic-based** [microsoftgraph/microsoft-graph-docs#7745]
If I wanted to build a recurring task and add text or a hypertext link to the notes section, how do I access it?  Looking at the JSON representation, I don't see it.  Is it, "notes": "String",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e496bc30-ad9f-93ca-e99d-83306a415dbf
* Version Independent ID: 407a66f9-652c-7c27-4bba-967fd856cc83
* Content: [plannerTask resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/plannertask.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dave-mills** [comment]
I believe the notes property is contained within the `plannerTaskDetails` object attached to each task [info here](https://docs.microsoft.com/en-us/graph/api/resources/plannertaskdetails?view=graph-rest-1.0). 

So the flow would be:
 1. Create the required task
 2. Update the details of the task. 

If there's a way of doing both in a single request, then I can't find it!

**Comment by TarkanSevilmis** [comment]
You can create details in the same request by including the properties of task details like so:
`{
... task properties ...
"details":
    {
        ... Task details properties ...
    }
}`

This model of operation will only work for creation of the task. Update operations need to be submitted separately (note that task and task details have distinct etags).
