### ISSUE TITLE
How do I include a Block Scheduled Action?

### ISSUE THREAD

**Issue by DecimalZero** [microsoftgraph/microsoft-graph-docs#7746]
Using the published Create windows10CompliancePolicy Example, I am getting error "Compliance policy must have one and only one block scheduled action".  How do I include a Block Scheduled Action in the same request?

Below is the PowerShell code I am executing. 

Invoke-WebRequest -Uri "https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies" -Method Post -Body $Body -Headers $AuthToken -ContentType "application/json"

$Body is below...

{
  "@odata.type": "#microsoft.graph.windows10CompliancePolicy",
  "description": "Windows 10 Compliance Policy",
  "displayName": "Windows 10 Compliance Policy",
  "version": 7,
  "passwordRequired": true,
  "passwordBlockSimple": true,
  "passwordRequiredToUnlockFromIdle": true,
  "passwordMinutesOfInactivityBeforeLock": 5,
  "passwordExpirationDays": 6,
  "passwordMinimumLength": 5,
  "passwordMinimumCharacterSetCount": 0,
  "passwordRequiredType": "alphanumeric",
  "passwordPreviousPasswordBlockCount": 2,
  "requireHealthyDeviceReport": true,
  "osMinimumVersion":  "10.0.16299.1776",
  "osMaximumVersion":  "10.0.18363.753",
  "mobileOsMinimumVersion":  null,
  "mobileOsMaximumVersion":  null,
  "earlyLaunchAntiMalwareDriverEnabled": true,
  "bitLockerEnabled": true,
  "secureBootEnabled": true,
  "codeIntegrityEnabled": true,
  "storageRequireEncryption": true
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19e0b321-168f-75f8-f4b1-bf1cccf5ce45
* Version Independent ID: 8d7b2589-9f49-2596-c40b-4c587bcf1dba
* Content: [Create windows10CompliancePolicy - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-windows10compliancepolicy-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-windows10compliancepolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-deviceconfig-windows10compliancepolicy-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
A compliance policy requires scheduledActionsForRule.
