### ISSUE TITLE
Graph explorer sample is incorrect

### ISSUE THREAD

**Issue by BobGerman** [microsoftgraph/microsoft-graph-docs#7747]
The Graph Explorer sample for Microsoft Teams (beta) / Create Chat Thread is incorrect. The resource should be "messages" not "chatThreads", and the body is also incorrect. See https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http for details.

Not sure where to submit this but I wanted to do my part ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview#feedback)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Just happened to be browsing this open issue again. Today in Graph Explorer, if I select "Microsoft Teams" and then "POST send channel message", the query URL displayed is correct: POST https://graph.microsoft.com/v1.0/teams/{team-id}/channels/{channel-id}/messages.

@BobGerman , do you still see "Create chat thread" as a sample query in Graph Explorer, or do you still see the problem?

Please update this issue accordingly to confirm. Thanks!

**Comment by Prasad-MSFT** [comment]
Hi @BobGerman , as mentioned by @angelgolfer-ms  I also  tried it in Graph Explorer and the query URL displayed is correct only both in beta and v1.0 :
https://graph.microsoft.com/beta/teams/{team-id}/channels/{channel-id}/messages
https://graph.microsoft.com/v1.0/teams/{team-id}/channels/{channel-id}/messages

Could you please confirm if you are still facing the issue or not?
