### ISSUE TITLE
Will there be the ability to change a user's assigned phone number or manage phone numbers in general anytime soon?

### ISSUE THREAD

**Issue by ChrisB9907** [microsoftgraph/microsoft-graph-docs#7749]
This is a function that is frequently used as a manual process or via PowerShell by admins as churn and other admin activities require changing, adding and removing phone numbers regularly. I think what is here so far is great, but having the functions for skype/teams number management would be awesome!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 640cc78f-7e7e-d074-d2a2-3c43ec52ee0f
* Version Independent ID: 008a943e-ceed-4265-eeb7-c13d94dd4d13
* Content: [Working with the communications API in Microsoft Graph - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/communications-api-overview.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Thanks for your feedback, @ChrisB9907 We'll take this into consideration and I'll update this thread with more details in the future.

**Comment by lramosvea** [comment]
Closing as an answer has been provided already
