### ISSUE TITLE
Sample subscription for Lists shows incorrect URL

### ISSUE THREAD

**Issue by johnnycardy** [microsoftgraph/microsoft-graph-docs#7757]
There is a table of `Resource examples` and the example for `List` displays:

> site/{site-id}/lists/{list-id}

This returns a Bad Request error. It should be:

> sites/{site-id}/lists/{list-id}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f20de46-dc28-3cde-642a-4a7fb7b2f454
* Version Independent ID: be834d56-fb0c-0f16-31f8-287221ba6cc4
* Content: [Create subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-post-subscriptions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @johnnycardy 
Thanks for reporting the issue!
A fellow community member @JarbasHorst has already authored a pull request to fix this issue. It'll be closed once the pull request gets merged.
