### ISSUE TITLE
Retrieving DL/DDL members with Graph?

### ISSUE THREAD

**Issue by lindseylanier** [microsoftgraph/microsoft-graph-docs#7761]
Any plans for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4f2e174-e263-4341-b121-b4b2d64bf989
* Version Independent ID: bcbfad43-66dd-2332-e2f5-30f483550b76
* Content: [Working with groups in Microsoft Graph - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/groups-overview?view=graph-rest-1.0#other-types-of-groups)
* Content Source: [api-reference/v1.0/resources/groups-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/groups-overview.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@lindseylanier could you please clarify the ask? Currently we support listing members for DL.

**Comment by lindseylanier** [comment]
Members of Dynamic Distribution Lists with Graph API

**Comment by yyuank** [comment]
We don't have plans to support Dynamic Distribution Lists on Graph, which is what we heard from the Exchange side that masters DDLs.
