### ISSUE TITLE
removing a property does not work for SdkVersion: graph-java/v1.7.1

### ISSUE THREAD

**Issue by omnifreefall** [microsoftgraph/microsoft-graph-docs#7762]
sending { "city": null }, for example : Fiddler trace shows { } is being sent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The documentation currently does not cover the Java SDK. When I run the operation in Graph Explorer, it is successful.

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users(city)/$entity",
    "city": null
}

Does not appear to be a change required to the page. Closing the issue.
