### ISSUE TITLE
Australia GovTeams & Graph - anything special?

### ISSUE THREAD

**Issue by bgervin** [microsoftgraph/microsoft-graph-docs#7764]
Does this page need to include gov.au deployments? Specifically if accessing from govteams.gov.au for teams add-ins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dbd263-9afd-aa90-cb50-bbadfc424cc2
* Version Independent ID: 63aaf699-609e-b4dd-bd02-9f891e09db8d
* Content: [National cloud deployments - Microsoft Graph](https://docs.microsoft.com/en-us/graph/deployments#feedback)
* Content Source: [concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/deployments.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Australia does not have a unique url for Microsoft Graph. Tenants in Australia region are access using graph.microsoft.com
