### ISSUE TITLE
Obtener las reuniones no funciona

### ISSUE THREAD

**Issue by Je1son** [microsoftgraph/microsoft-graph-docs#7765]
He intentado realizar una petición GET filtrando por fecha y demás campos pero en todas me regresa "Bad Request".

Adjunto la URL que uso para hacer la petición: https://graph.microsoft.com/v1.0/communications/onlineMeetings/?$filter=Subject eq 'Prueba'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06f89278-6b03-e6e4-66a3-2127a11750fe
* Version Independent ID: f6f92861-6d72-2260-2277-d963793fbce2
* Content: [Get onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/onlinemeeting-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @Je1son currently for the GET online meeting API, we currently only support filtering by VTC Id (video teleconferencing id). 

Please view the note in the [GET online meeting](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http) documentation.

**Comment by lramosvea** [comment]
Closing this issue as an answer has been provided already
