### ISSUE TITLE
Which properties are filterable with the $filter parameter?

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs#7768]
This document does not indicate which properties are filterable.  Can this be updated please to indicate which ones are filterable with the $filter property?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2aec20a-84b8-f5b5-b30a-07b8bece2eb3
* Version Independent ID: b07140db-8b54-e375-bbb8-1506aa0e616f
* Content: [riskDetection resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/riskdetection.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Cynothoglys** [comment]
I agree with @RayGHeld, this document needs to be updated to include which properties are filterable.  I have not been able to get any filter parameters to work correctly with the riskDetection endpoint.

**Comment by cloudhandler** [comment]
@Cynothoglys - what issues are you having
?

**Comment by cloudhandler** [comment]
@Cynothoglys do you have more details?

**Comment by davidmu1** [comment]
The article has examples that include the $filter parameter. Closing this issue until more information can be provided.

**Comment by RayGHeld** [comment]
Not all properties are filterable.  I am asking to indicate which properties the $filter parameter can be applied to.  Not sure what more information you want me to provide here.
