### ISSUE TITLE
can "allowedSenderType" for the "email" field be included?

### ISSUE THREAD

**Issue by hakanson** [microsoftgraph/microsoft-graph-docs#7770]
This API will return and "email" field in the response.

`"email": "1a2b3c4d.contoso..onmicrosoft.com@amer.teams.ms",`

But in the Teams UI, when you configure the email address for a team, you can go to advanced setting and select one of "Anyone can send emails to this address", "Only members of this team", or "Only email sent from these domains"

In the browser, this call is made to get that email info, which includes both the email address and the allowed sender type.

```
GET https://teams.microsoft.com/api/mt/part/amer-02/beta/channels/{id}/email

{
    "emailAddressDetails": {
        "emailId": "1a2b3c4d.contoso.onmicrosoft.com@amer.teams.ms"
    },
    "allowedSenders": {
        "allowedSenderType": "members"
    }
}
```
Can Get Channel also return this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a639b2c-1646-2fb0-df4b-672717ecef06
* Version Independent ID: 4a5cc49a-ee65-02a5-583b-acfb0993a25f
* Content: [Get channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prithvi-MSFT** [comment]
Hi, In Microsoft 365 admin center -> select Team-> settings-> General settings-> Enable "Allow external senders to email this group" . After enabling this setting and making Graph API call for Get channel /teams/{team-id}/channels/{channel-id} will return the "email" field in response.
