### ISSUE TITLE
Application permissions does work

### ISSUE THREAD

**Issue by antonGritsenko** [microsoftgraph/microsoft-graph-docs#7788]
Seems to be application permission does not supported for this operation. I tried all combinations, but not luck. Always got: 
```
{
  "error": {
    "code": "Authorization_RequestDenied",
    "message": "Insufficient privileges to complete the operation.",
    "innerError": {
      "request-id": "{id}",
      "date": "{date}"
    }
  }
}
```
Same permissions for delegated flow works perfectly. 
I have found this also: https://stackoverflow.com/questions/40808329/add-member-to-directory-role-in-microsoft-graph-api-insufficient-privileges

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09dbdd56-c555-4c0e-eb70-03df339d2a39
* Version Independent ID: f867295f-2c69-5874-9e6b-1461466393c1
* Content: [List directoryRoles - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryrole-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryrole-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryrole-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abhijeetsinha** [comment]
@antonGritsenko - I need to understand your your scenario a bit more.

- Do you expect directoryRoles API to return application permissions like directory.read.all, along with built-in roles like User Admin and Global Admin?

- Or, do you have an app with directory.read.all and you are trying to fetch Azure AD built-in roles using directoryRoles API via that app and the call is failing?

Which one is it?

**Comment by abhijeetsinha** [comment]
@antonGritsenko - We need you to provide us correlation id and timestamp to investigate further.

**Comment by abhijeetsinha** [comment]
@antonGritsenko - Unfortunately, we're unable to assist you further without the additional information requested. Due to inactively on this issue, we'll move forward with closing it. If you have another question or require further assistance, please let us know.
