### ISSUE TITLE
Download shared files with the share link for School Account

### ISSUE THREAD

**Issue by leungyukshing** [microsoftgraph/microsoft-graph-docs#7791]
[Enter feedback here]
I try to download a shared file with the share link generated by a school account. For personal account, everything is pretty good. But for school account, the response shows that the shared link is not valid.

I'm following the encoding step that is provided by the official document.
Encoding sharing URLs
To encode a sharing URL, use the following logic:

First, use base64 encode the URL.
Convert the base64 encoded result to unpadded base64url format by removing = characters from the end of the value, replacing / with _ and + with -.)
Append u! to be beginning of the string.

It's a bit urgent and hope to receive your response ASAP. Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533d203c-42f9-0dae-1d05-7e00ca05c9e8
* Version Independent ID: 31ddb53d-5b63-2d8e-06c3-e56125d22937
* Content: [Share a file with a link - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createlink?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-createlink.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createlink.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by jcharnley** [comment]
if you are using javascript all u need to do is base64 it.no need to replace those char or trim
