### ISSUE TITLE
Error "The password has expired." when logging in

### ISSUE THREAD

**Issue by dennisameling** [microsoftgraph/microsoft-graph-docs#7797]
We create users through the Graph API with the steps mentioned at [Example 2](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http#example-2-create-a-user-with-social-and-local-account-identities), but when we don't set `passwordProfile.forceChangePasswordNextSignIn` to `false`, our users always get "The password has expired." when they try to login. While the note on the docs page says

> and force change password at next sign-in must also be disabled

... the code example below it doesn't include `forceChangePasswordNextSignIn`. The code snippet for `passwordProfile` should be as follows:

```JSON
"passwordProfile": {
    "password": "password-value",
    "forceChangePasswordNextSignIn": false
},
```

Please update the code examples accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http#example-2-create-a-user-with-social-and-local-account-identities)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RoelVerhees** [comment]
Got the same problem, everytime i add an user with forceChangePasswordNextSignIn set to true.
What is the current status of this bug / problem?

**Comment by rick-hayek** [comment]
any update on this bug?

**Comment by davidmu1** [comment]
I'm not seeing a change required for the example. In example 2, the note states:

For local account identities, password expirations must be disabled, and force change password at next sign-in must also be disabled.

The JSON example is:

POST https://graph.microsoft.com/v1.0/users
Content-type: application/json

{
  "displayName": "John Smith",
  "identities": [
    {
      "signInType": "userName",
      "issuer": "contoso.onmicrosoft.com",
      "issuerAssignedId": "johnsmith"
    },
    {
      "signInType": "emailAddress",
      "issuer": "contoso.onmicrosoft.com",
      "issuerAssignedId": "jsmith@yahoo.com"
    },
    {
      "signInType": "federated",
      "issuer": "facebook.com",
      "issuerAssignedId": "5eecb0cd"
    }
  ],
  "passwordProfile" : {
    "password": "password-value",
    "forceChangePasswordNextSignIn": false
  },
  "passwordPolicies": "DisablePasswordExpiration"
}

**Comment by dennisameling** [comment]
@davidmu1 I just checked the history of the page, and apparently you already did that change back on June 30 😅 https://github.com/microsoftgraph/microsoft-graph-docs/pull/8920/files#diff-dfd1aedd1e9be2c1afefc51448cbd7d8R184 so the docs are correct now. Thanks
