### ISSUE TITLE
Application-only permissions should be updated to support Application.Read.All

### ISSUE THREAD

**Issue by elcarlosadrian** [microsoftgraph/microsoft-graph-docs#7799]
It seems Application.Read.All app-only permission should work to read apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016eadaa-d06b-2e43-1726-b7869957bc00
* Version Independent ID: 05d7f4b4-d564-1ce7-d676-ca8b433f763d
* Content: [List applications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=http&source=docs#feedback)
* Content Source: [api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The permissions are listed from least privileged to most privileged. You only need to use the one that is best suited to your needs. So if all you want to do is read the app, Application.Read.All is sufficient. No change identified for the page. Closing the issue.
