### ISSUE TITLE
Unable to Remove Members

### ISSUE THREAD

**Issue by fribeiro1** [microsoftgraph/microsoft-graph-docs#7800]
I am getting the following error when trying to remove members from a group:

{
  "error": {
    "code": "BadRequest",
    "message": "Write requests are only supported on contained entities",
    "innerError": {
      "request-id": "..",
      "date": "..."
    }
  }
}

Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fribeiro1** [comment]
My bad, fixed code in my end.

**Comment by mda590** [comment]
@fribeiro1 Are you able to share how you resolved this issue? I am running in to the same error (Write requests are only supported on contained entities) when trying to remove members from groups, but I'm not seeing what I am doing wrong. Wondering if you can give any insight. Thanks!

**Comment by fribeiro1** [comment]
Sorry, I don't really remember my mistake there 🤦‍♂️🤦‍♂️🤦‍♂️
