### ISSUE TITLE
Deleted but "joinWebUrl" still working.

### ISSUE THREAD

**Issue by jasmalmk** [microsoftgraph/microsoft-graph-docs#7802]
After deleting get HTTP/1.1 204 No Content.  But "joinWebUrl" still working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56494a16-8774-5683-869a-859750bc71fb
* Version Independent ID: 4cbec427-5f5a-68d1-d4e5-1e7e5ae105f3
* Content: [Delete onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/onlinemeeting-delete.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by j1151300783** [comment]
I have same problem, too.

**Comment by ananmishr** [comment]
Hi @jasmalmk and @j1151300783 we are working to resolve this. Thanks.

**Comment by sri3650** [comment]
Any update on this? JoinUrl is still accessible even after successful meeting deletion.

**Comment by sri3650** [comment]
@ananmishr Any update on this? JoinUrl is still accessible even after successful meeting deletion.

**Comment by BronwenZ** [comment]
Is there any update on the progress on this?

We delete on onlinemeeting and then do a get and get a 404
Then we can join this deleted meeting successfully
If we do a get on this meeting all the details are returned
It appears it is only actually soft deleted and can be re-actived but anyone that has the old link accessing it progress on this?

**Comment by JDK76** [comment]
Agree with @BronwenZ above, we need a way to permanently delete an online meeting, currently it seems this is not possible
