### ISSUE TITLE
Can create meeting for paste date

### ISSUE THREAD

**Issue by jasmalmk** [microsoftgraph/microsoft-graph-docs#7803]
There is no validation if the start date and end date are past date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56494a16-8774-5683-869a-859750bc71fb
* Version Independent ID: 4cbec427-5f5a-68d1-d4e5-1e7e5ae105f3
* Content: [Delete onlineMeeting - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/onlinemeeting-delete.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @jasmalmk this is currently by design. As long as the start date is earlier than or equal to the end date, it's alright if the meeting takes place in the past.
