### ISSUE TITLE
Needs information on required scopes/roles/permissions

### ISSUE THREAD

**Issue by jordanmills** [microsoftgraph/microsoft-graph-docs#7804]
I've tried this with a global admin account with .default, Group.ReadWrite.All, and Directory.ReadWrite.All and get an authorization error every time, for beta and 1.0.  This happens with /groups with or without a selector.

Authorization_RequestDenied
Insufficient privileges to complete the operation.

The /teams endpoint just plain doesn't work: 
NotImplemented
'GET /teams' is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75dbe68-e162-8861-d194-4a29de3bd731
* Version Independent ID: f58a6930-8575-8306-4273-fc413b979879
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-list-all-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
If you want to list all the groups in an organization, then you can follow this [doc](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&tabs=http#permissions). Here all the required permission details are mentioned.
