### ISSUE TITLE
Teams API endpoint is not working since 4/16/2020

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#7806]
hi there, do you have any idea how i can resolve this issue, my app creating groups and all but right when it is time to create a team I get an error
https://graph.microsoft.com/v1.0/groups/0*******b7a7-0a931544db69/team PUT request

{
"error": {
"code": "BadGateway",
"message": "Failed to execute backend request.",
"innerError": {
"request-id": "2ab31a91-1093-4b2b-a570-9eb23b36519f",
"date": "2020-04-17T20:23:48"
}
}
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d21f6e2-d207-8fbe-931a-12872e9b50a2
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team from group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by janardhan96** [comment]
Hello @nkramer, resolve the issue as soon as possible. My production app depends on this API.

**Comment by ashoksubedi1** [comment]
It is working thank you whoever fixed it.

**Comment by mrsjoycemara** [comment]
Hi. Experiencing the same issue right now.

**Comment by mrsjoycemara** [comment]
@nkramer

**Comment by joselu1sc** [comment]
Hello, I am exeprience the same result. Even if I use C# or the just the REST API request:
{
    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",
        "innerError": {
            "request-id": "64ed1ebb-ba3e-44cd-8278-6ea320da0000",
            "date": "2020-05-04T06:56:12"
        }
    }
}

This is the group that I am attempting to add the group to:

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groups/$entity",
    "id": "**********{ID}**********-f2746fef11ca",
    "deletedDateTime": null,
    "classification": null,
    "createdDateTime": "2020-04-19T17:35:30Z",
    "creationOptions": [
        "ProvisionGroupHomepage",
        "Groupify:*****************_40",
        "SharePointKeepOldHomepage"
    ],
    "description": "description",
    "displayName": "**************Group1",
    "expirationDateTime": null,
    "groupTypes": [
        "Unified"
    ],
    "isAssignableToRole": null,
    "mail": "*********@*********.onmicrosoft.com",
    "mailEnabled": true,
    "mailNickname": "*********",
    "membershipRule": null,
    "membershipRuleProcessingState": null,
    "onPremisesDomainName": null,
    "onPremisesLastSyncDateTime": null,
    "onPremisesNetBiosName": null,
    "onPremisesSamAccountName": null,
    "onPremisesSecurityIdentifier": null,
    "onPremisesSyncEnabled": null,
    "preferredDataLocation": null,
    "preferredLanguage": null,
    "proxyAddresses": [
        "SMTP:*********@*********.onmicrosoft.com"
    ],
    "renewedDateTime": "2020-04-19T17:35:30Z",
    "resourceBehaviorOptions": [],
    "resourceProvisioningOptions": [],
    "securityEnabled": false,
    "securityIdentifier": "S-1-12-1-2161958283-1201158779-1962021307-3390173039",
    "theme": null,
    "visibility": "Public",
    "onPremisesProvisioningErrors": []
}

To add the endpoint I am using 
PUT https://graph.microsoft.com/v1.0/groups/**********{ID}**********-f2746fef11ca/

**Comment by m365ken** [comment]
Hi @joselu1sc,
I think your particular issue is related to the v1 version of the Graph api not supporting the parameters you have in your code. Have you tried this using /beta? The v1 and beta have very different functionality. Thx

V1:
https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http

beta:
https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta#example-6-create-a-team-with-a-non-standard-base-template-type

**Comment by ashoksubedi1** [comment]
@joselu1sc try with a mailNickname. I dont think mailNickname can be null or empty

**Comment by v-chetsh** [comment]
@ashoksubedi1 - Please let me know if you are still facing this issue.
