### ISSUE TITLE
Should be http method GET

### ISSUE THREAD

**Issue by altcoder** [microsoftgraph/microsoft-graph-docs#7816]
POST is not working. This only works on GET

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b94f01e-d512-36ca-66e7-66bde752c7a5
* Version Independent ID: 2b7c9295-e058-4fa7-1e8d-0b121adade09
* Content: [Table: Range - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/table-range?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/table-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/table-range.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by grangeryy** [comment]
This is currently by design. You can [update table](https://docs.microsoft.com/en-us/graph/api/table-update?view=graph-rest-1.0&tabs=http) as a work around.
