### ISSUE TITLE
Example of sourceData-value

### ISSUE THREAD

**Issue by altcoder** [microsoftgraph/microsoft-graph-docs#7818]
Can you give example of sourceData-value in request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c778a405-3097-cf79-1f89-61a9a5b139a4
* Version Independent ID: b7648c18-0f32-d788-ce41-d5ae4f37c12a
* Content: [Chart: setData - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/chart-setdata.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lumine2008** [comment]
+ Phoebe who is Excel Graph PM.

I am not focusing on graph, so let me involve current graph PM to follow up

Thanks,
Raymond
