### ISSUE TITLE
Add v2 auth instructions to Python getting started instructions

### ISSUE THREAD

**Issue by cbales** [microsoftgraph/microsoft-graph-docs#782]
Getting started guide on our site should match the instructions given in the SDK repo.

https://graph.microsoft.io/en-us/docs/get-started/python

**Comment by cbales** [comment]
It would be good to also call out that this library is in preview currently

**Comment by jamescro** [comment]
Updated the document with v2 auth registration instructions.

**Comment by jamescro** [comment]
Link: https://graph.microsoft.io/en-us/docs/get-started/python
