### ISSUE TITLE
Channel message can't get lastModifiedDateTime value,always null

### ISSUE THREAD

**Issue by berserker23** [microsoftgraph/microsoft-graph-docs#7822]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fa912d-43d1-099b-44d5-fdcdaae00db7
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessages: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@berserker23 

Could you please confirm if you are still facing this issue?

**Comment by Meghana-MSFT** [comment]
Closing this issue for now. Please feel free to reopen this issue if you are still facing the issue.

**Comment by v-chetsh** [comment]
Closing this issue for now. Please feel free to reopen this issue if you are still facing the issue.
