### ISSUE TITLE
Clarify example

### ISSUE THREAD

**Issue by phenixdotnet** [microsoftgraph/microsoft-graph-docs#7828]
Actually the example describe a payload which doesn't work with the API.
A more accurate example could be 
```json
{
    "@odata.id": "https://graph.microsoft.com/beta/{objectType}/{objectId}"
}
```
where `{objectType}` could be `users` or `serviceprincipals` and the `{objectId}` is the id of the object in the directory.
Moreover it's look like a successful response isn't `200 ok`, but a `204 No Content`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3836bd27-4c2b-0481-5069-0b797cc94cdf
* Version Independent ID: 2816e3d5-8ac8-8c40-8b2e-1e13f2ee8fa9
* Content: [Add directory role member - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/directoryrole-post-members?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/directoryrole-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/directoryrole-post-members.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cmendible** [comment]
Hi @phenixdotnet do you have a complete working sample? I'm hitting a _BadRequest: Write requests are only supported on contained entities_ exception when running:

```shell
az rest -m POST -u https://graph.microsoft.com/beta/directoryRoles/<role id>/members/$ref --headers Content-Type=application/json -b "{'@odata.id': 'https://graph.microsoft.com/beta/servicePrincipals/<service principal Id>'}"
```

**Comment by phenixdotnet** [comment]
Hi @cmendible ,
I'm using this curl:
```
curl --location --request POST "https://graph.microsoft.com/beta/directoryRoles/${USER_ACCOUNT_ADMINISTRATOR_ROLE_ID}/members/\$ref" \
                --header 'Content-Type: application/json' \
                --header "Authorization: Bearer ${ACCESS_TOKEN}" \
                --data-raw "{\"@odata.id\": \"https://graph.microsoft.com/beta/serviceprincipals/${APP_OBJECT_ID}\"}
```

The only difference I can see is the `servicePrincipals` in your request instead of `serviceprincipals` in mine.
Also be sure to use the **object id** of the service principal and not the app id

**Comment by cmendible** [comment]
You sample helped me! I had to escape the $ref in the url:

`https://graph.microsoft.com/beta/directoryRoles/<role id>/members/%24ref`

Thanks!
