### ISSUE TITLE
Firewall requirements for the REST API

### ISSUE THREAD

**Issue by StefanIvemo** [microsoftgraph/microsoft-graph-docs#7829]
Can you please specify a little bit more detail regarding the settings to allow discovery and access that need to be made in firewalls or Application Gateways publishing the Exchange Virtual directories? I understand that I need a functional Autodiscover in-place. But what more do I need? Have the API virtual directory published? 

The  "On-Premises Architectural Requirements for the REST API" link under "IT administrators can find more information in the following resources" only send me to the Exchange Team Blog video library. I can't find any video on the topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836a93d8-42f8-3922-6e6a-3939b570eba4
* Version Independent ID: 6b61c0de-30a7-7303-6383-28dad72c7c99
* Content: [Use REST APIs to access mailboxes in Exchange hybrid deployments (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/hybrid-rest-support)
* Content Source: [concepts/hybrid-rest-support.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/hybrid-rest-support.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by liangchr** [comment]
GA date for graph api for hybrid?

**Comment by liangchr** [comment]
oops sorry commented under wrong thread.
