### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by jk14n6** [microsoftgraph/microsoft-graph-docs#7837]
Do we know when this API will be made production ready?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55039f3-15e9-289f-a07b-f886bd382bb2
* Version Independent ID: e839ae12-9d78-c4d2-1868-267a8f1994ce
* Content: [Microsoft Bookings API overview (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/booking-concept-overview?view=graph-rest-beta#next-steps)
* Content Source: [concepts/booking-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/booking-concept-overview.md)
* Product: **bookings**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @jk14n6 , thank you for your question. I can help bubble your request up to the corresponding service side owner. 

In addition, please go to [UserVoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359578) and either vote on an existing item that matches yours, if one exists already, or, open a new item there if there isn't an existing item already. That is in general a best way to aggregate requests for a need (or any service feature need in general) and get the service owner prioritize the request.

Thanks for your continued support!

**Comment by angelgolfer-ms** [comment]
@arvindmicrosoft , FYI.
