### ISSUE TITLE
Naming Policy

### ISSUE THREAD

**Issue by talasz** [microsoftgraph/microsoft-graph-docs#7842]
[Hi guys, we have set a naming Policy in our organization with the three letter state-attribute for example: TST-GROUPNAME. TST- would be the prefix. 
Now I am automatically creating Groups/Teams out of a robot via an application registered in azure-activedirectory. However I always receive the error message that I am missing the prefix/suffix. I can only successfully create a group called -TEAMNAME instead of TST-TEAMNAME

INVOKE REST SCRIPT (PowerShell):

$url = "https://graph.microsoft.com/v1.0/groups"
$Params = @{
    description = "test"
       
    displayName = "TST-TeamMicrosoftGraph3"
            groupTypes = @("Unified")
            visibility = "private"
            mailEnabled = $true
            mailNickname = "TST-TeamMicrosoftGraph3"
            securityEnabled = $false
            }

$params = convertto-json $Params
$Response = Invoke-RestMethod -Method POST -Uri $url -Headers @{Authorization = "Bearer $accesstoken"} -Body $Params -ContentType "application/json"
$groupid = $Response.id

Thank you very much for your help!!
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @talasz 

can you please provide a screenshot of your Groups naming policy configuration in Azure?

Regards,
Jarbas Horst

**Comment by talasz** [comment]
![NamingPolicy](https://user-images.githubusercontent.com/63726909/80098888-e9489900-856d-11ea-826d-0c5dcd61575d.png)

**Comment by talasz** [comment]
Hi @JarbasHorst 

Thx for your help :)

Policy:
![NamingPolicy](https://user-images.githubusercontent.com/63726909/80099031-185f0a80-856e-11ea-970b-f261376e82f8.png)
App Permissions:
![App_permissions](https://user-images.githubusercontent.com/63726909/80099184-5c520f80-856e-11ea-9af3-0d1cb443b528.png)
AccessToken:
![atuh_token](https://user-images.githubusercontent.com/63726909/80099512-daaeb180-856e-11ea-8bb3-58368d0e9f5a.png)
GroupCreation:
![groupcreation](https://user-images.githubusercontent.com/63726909/80099529-e0a49280-856e-11ea-89ce-baa1a2bb9fdb.png)
ErrorMessage:
![errormessage](https://user-images.githubusercontent.com/63726909/80099597-ffa32480-856e-11ea-920a-b034e5c97b28.png)


regards,

Georg Talasz

**Comment by yyuank** [comment]
I see you are missing a string "-" in displayName in your post request. Would that be the case?

**Comment by talasz** [comment]
@yyuank 

Maybe I am mistaken however in the Displayname "TST-TeamMicrosoftGraph4" is a string "-" between "TST" (StateAttribute) and TeamMicrosoftGraph4 (GroupName) follwing our NamingPolicy. However it still Shows me the error. It just lets me create the Group without the TST (state attribute) for example "-TeamMicrosoftGraph4". 

![stringmissing](https://user-images.githubusercontent.com/63726909/80130681-49a10000-8599-11ea-9c33-cb9dc77bf45a.png)

So my actual question is the following: As a Service User (for example tenant-admin) I don't have to follow any Naming Policies if I create an O365 Group. Which permissions does my application need to create O365 Groups not following our naming Policy?

**Comment by yyuank** [comment]
I saw "suggestedPropertyValue" in the error message indicated a string in front of the entire displayName "-TST-TeamMicrosoftGraph4" and was wondering why. 

I'd assume App-level Group.ReadWrite.All would be sufficient to be exempt from naming policy. Can you confirm if your app has it? If yes, we'll need to further investigate.

**Comment by talasz** [comment]
@yyuank :) yes i don't know. The SuggestedPropertyValue suggests "-" in the beginning but my naming policy should be different "TST-". My app has group.readwrite.all (delegated & application). That's why I am a bit confused haha. Thank you for your help

**Comment by talasz** [comment]
@yyuank & @JarbasHorst 

Hi - I solved the Problem. An application is only allowed to overrule the naming Policy if you add the right AzureADDirectoryRole for example "User Administrator" to the application. Group.ReadWrite.All & Directory.ReadWrite.All permissions are not enough. You can achive this via "Add-AzureADDirectoryRoleMember -ObjectId $Role.ObjectId -RefObjectId $APP.ObjectId". Thx for your help. georg

**Comment by yyuank** [comment]
Thank you @talasz for your confirmation and the diagnostic insight!
