### ISSUE TITLE
Is there any more information about providerTypes?

### ISSUE THREAD

**Issue by catmanjan** [microsoftgraph/microsoft-graph-docs#7843]
"other" is listed as a valid providerType, does this mean we can create our own providers which can have reference attachments?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d26b87cc-df40-34a1-aac3-bf32163b8a4e
* Version Independent ID: ea338d28-9fa4-f3da-1f91-fb2313b0937e
* Content: [referenceAttachment resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/referenceattachment?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/referenceattachment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/referenceattachment.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svpsiva** [comment]
Yes, you can create reference attachments. Pls review 
https://docs.microsoft.com/en-us/graph/api/message-post-attachments?view=graph-rest-beta&tabs=http#example-reference-attachment

**Comment by catmanjan** [comment]
Sorry, I do not want to create reference attachments, I want to create a custom providerType - I understand the process for doing this may not be covered by the graph API, but if you could point me to any documentation it would be appreciated.
