### ISSUE TITLE
Unable to send post request

### ISSUE THREAD

**Issue by mallockey** [microsoftgraph/microsoft-graph-docs#7851]
Attempting to send this request through PowerShell but keep getting "Invalid type specified:
\"microsoft.graph.androidManagedStoreApp" If I change the URL to beta I get ""An error has occurred - Operation ID" I have the data exactly as it is in this document, what am I doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ca0df8-1dd8-d88d-435d-d5bb174a54d4
* Version Independent ID: bf046f80-c1b0-3984-9551-0632f8c6dea3
* Content: [Create androidManagedStoreApp - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-androidmanagedstoreapp-create?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-apps-androidmanagedstoreapp-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-apps-androidmanagedstoreapp-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
The UI flow has you select a Google Play Store app, and then a POST to the /beta/deviceManagement/androidManagedStoreAccountEnterpriseSettings/syncApps endpont triggers a sync of any of your managed apps back to Intune.  You can use F12 developer mode in the browser to follow the flow of activity as you select actions in the UI.  This is the easiest way to see how Intune is calling Graph or other services and it will have your actual request body captured as well.

**Comment by mallockey** [comment]
> 
> 
> The UI flow has you select a Google Play Store app, and then a POST to the /beta/deviceManagement/androidManagedStoreAccountEnterpriseSettings/syncApps endpont triggers a sync of any of your managed apps back to Intune. You can use F12 developer mode in the browser to follow the flow of activity as you select actions in the UI. This is the easiest way to see how Intune is calling Graph or other services and it will have your actual request body captured as well.

Thanks for the reply. How would this work when calling the API? Is it possible to create the android managed app then sync it with the endpoint you provided? I'm looking to create the app programmatically if possible.
