### ISSUE TITLE
assignedLicenses supports $filter

### ISSUE THREAD

**Issue by eketo-msft** [microsoftgraph/microsoft-graph-docs#7855]
Docs don't reflect that assignedLicense supports $filter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
@SumitParikh can you please look at this for licensing info?

**Comment by jmohr1972** [comment]
When doing '/users?$filter=assignedLicenses/any(a:a/skuid eq a403ebcc-fae0-4ca2-8c8c-7a907fd6c235)' I get a "@odata.nextLink" that we follow but then errors out after retrieving something over 100+ objects with the following error (I have verified that the token had plenty of time left on it 20+ minutes):

{
"error": {
"code": "Directory_ExpiredPageToken",
"message": "The specified page token value has expired and can no longer be included in your request.",
"innerError": {
"date": "2020-08-11T20:25:32",
"request-id": "b26dcd38-7640-4f9f-bbd4-3cffc5d8f7c1"
}
}
}

**Comment by SumitParikh** [comment]
Adding @Jimmy Zhu<mailto:Zhenying.Zhu@microsoft.com> to help.





Thanks and Regards,
Sumit Parikh, Senior Program Manager
Microsoft Corporation
M: +1 425.241.5440

**Comment by FaithOmbongi** [comment]
Hello @eketo-msft ,

Thank you for the feedback. Yes, `$filter` is supported on assignedLicenses. We'll update the page to reflect this. Closing the issue for now.
