### ISSUE TITLE
UserFlow.Id is required

### ISSUE THREAD

**Issue by thrixton** [microsoftgraph/microsoft-graph-docs#7860]
This page states that the `id` property is readonly.
However, the graph api requires it to be provided and then prepends the standard `B2C_1_` prefix.

```
{
    "error": {
        "code": "AADB2C",
        "message": "The value must not be null or empty. Parameter name: Id",
        "innerError": {
            "correlationId": "9506fc21-616f-4f75-b5d8-6da546e48f5f",
            "date": "2020-04-22T04:25:12",
            "request-id": "6868762d-000c-4534-b5be-adf945a9a66c"
        }
    }
}
```

Also, the documentation at [Create userFlow](https://docs.microsoft.com/en-us/graph/api/identityuserflow-post-userflows?view=graph-rest-beta&tabs=http) is incorrect as the `id` is omitted there as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cb63571-3867-5901-0b38-3f01d95385d4
* Version Independent ID: 7753d54f-3658-3359-94b6-f37c87fd9371
* Content: [UserFlow resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/identityuserflow?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/identityuserflow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/identityuserflow.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @nickgmicrosoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Thank you for your feedback. Added a description for "id" and added it to the request body in the create operation. Closing the issue.
