### ISSUE TITLE
Create appRoleAssignment Help

### ISSUE THREAD

**Issue by bryan-yu** [microsoftgraph/microsoft-graph-docs#7861]
Hello, I would like to enquire as to how the api for assigning a group to an Enterprise application should work for Creating AppRole Assignment. Currently my api (Javascript) request looks something like below:

       await this.msclient.api(`/servicePrincipals/${servicePrincipal.id}/appRoleAssignments`).version('beta').post({
            resourceId: app.id, // app id
            principalId: '82bbd097-91f7-45e5-9b5e-2ba5dd803029', // group id
        })

I have also tried exactly what was in the documentation with principalType and other details but get error I get back is status 400 "This request is currently not supported in the target entity group" same when I do the above with only resourceId and principalId.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f89ec701-8220-14ec-0dfd-543d2b4faafc
* Version Independent ID: 794ffd87-99dd-0521-cd5d-8a340d5babad
* Content: [Create appRoleAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-beta&tabs=javascript#feedback)
* Content Source: [api-reference/beta/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-post-approleassignments.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jiasli** [comment]
[appRoleAssignments](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-1.0&tabs=http) is now GA: https://developer.microsoft.com/en-us/identity/blogs/service-principal-api-in-microsoft-graph-is-now-generally-available/.

Could you check https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479 and see if it works for you. It is for Azure CLI, but the idea is the same.

```
$ az rest --method POST --uri https://graph.microsoft.com/v1.0/servicePrincipals/a3efc889-f1b7-4532-9e01-91e32d1039f4/appRoleAssignments \
          --header Content-Type=application/json \
          --body '{
            "principalId": "8aaa6158-7450-4407-ba08-61377f23d05f",
            "resourceId": "a3efc889-f1b7-4532-9e01-91e32d1039f4",
            "appRoleId": "19dbc75e-c2e2-444c-a770-ec69d8559fc7"
          }'
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#servicePrincipals('a3efc889-f1b7-4532-9e01-91e32d1039f4')/appRoleAssignments/$entity",
  "appRoleId": "19dbc75e-c2e2-444c-a770-ec69d8559fc7",
  "createdDateTime": "2020-05-25T06:26:55.4133464Z",
  "deletedDateTime": null,
  "id": "WGGqilB0B0S6CGE3fyPQX-myZZcnVI1HnMTA1vAfsYo",
  "principalDisplayName": "myapp",
  "principalId": "8aaa6158-7450-4407-ba08-61377f23d05f",
  "principalType": "ServicePrincipal",
  "resourceDisplayName": "Microsoft Graph",
  "resourceId": "a3efc889-f1b7-4532-9e01-91e32d1039f4"
}
```

**Comment by FaithOmbongi** [comment]
Hi @bryan-yu If the sample code by @jiasli hasn't work for you please feel free to reopen this issue. Closing for now.
