### ISSUE TITLE
settingName is always null

### ISSUE THREAD

**Issue by shareonline** [microsoftgraph/microsoft-graph-docs#7862]
the settingName always returns null (even in the Azure Portal). 
Both the 1.0 and Beta endpoint never return any value. This makes it hard to actually use the settings to anything.

The Azure Portal translates the setting names somehow, but can't see any outgoing calls to get the setting name, so i can't see where it gets it from?

Can you please fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ea2e73-84d1-b937-6e10-5dd2ebe9138d
* Version Independent ID: 3a431f56-597b-c77e-4ecb-aca820d3d60d
* Content: [deviceCompliancePolicySettingState resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-devicecompliancepolicysettingstate?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/intune-deviceconfig-devicecompliancepolicysettingstate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-deviceconfig-devicecompliancepolicysettingstate.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
I was able to use this URL to return the compliance policies assigned and their states.  You'll need to replace <mydeviceID> with a proper deviceID from your tenant: https://graph.microsoft.com/beta/deviceManagement/managedDevices/<mydeviceID>/deviceCompliancePolicyStates?$filter=((platformType%20eq%20%27WindowsPhone81%27)%20or%20(platformType%20eq%20%27Windows81AndLater%27)%20or%20(platformType%20eq%20%27Windows10AndLater%27)%20or%20(platformType%20eq%20%27all%27))
