### ISSUE TITLE
onlineMeetingProvider not working

### ISSUE THREAD

**Issue by fixaaay** [microsoftgraph/microsoft-graph-docs#7864]
I am finding that when i try to use section 4 to make a teams meeting, the following sections are all returing a error 400;
  "allowNewTimeProposals": true,
  "isOnlineMeeting": true,
  "onlineMeetingProvider": "teamsForBusiness"
Do i need to request other graph permissions in order to send these types of meeting?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by fixaaay** [comment]
I have found out that other members in my organisation have the permission to set these meetings up, also i have created a private account and it works fine when using this permission.

however, the problem still persists with my original account meaning that i still cannot setup ms teams meeting with the post request. 

Is there a permissions that i could have missticked or something that is saved on my account that would prevent this. When using the graph explorer to test this it will always return an error 400 if the sections outlined above are included

**Comment by Harini84** [comment]
The request will work if 'onlineMeetingProvider' is stamped with 'teamsForBusiness'.

Please check the same on calendar resource type in the original account:
https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

Please debug for access issue.

**Comment by Harini84** [comment]
Closing - no further issue reported.
