### ISSUE TITLE
Retrieve Schedule from accessPackageAssignments 

### ISSUE THREAD

**Issue by timd19** [microsoftgraph/microsoft-graph-docs#7867]
Is there any way to get the schedule (startDateTime & stopDateTime) from this Endpoint?

I see its available via the ELM endpoints for the Azure Portal, but I can't seem to get it out of this one. I tried to filter and select with no luck.

schedule           : @{duration=; startDateTime=2020-03-24T18:09:55.09Z; stopDateTime=2020-03-25T03:59:59Z}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62495d1c-009b-4c87-30d5-b3c415f967b5
* Version Independent ID: c3b9c844-417f-14d2-c887-b708de640c1f
* Content: [List accessPackageAssignments - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/accesspackageassignment-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Sorry, we haven't yet added this field to Microsoft Graph beta.
