### ISSUE TITLE
List all teams - Just doesn't work - Errors with Bad Gateway

### ISSUE THREAD

**Issue by gavsto** [microsoftgraph/microsoft-graph-docs#7868]
When hitting /teams/{id} on the beta graph API I just get an error about Bad Gateway

Invoke-RestMethod : {
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": "29b777b9-4e1c-4760-a404-3e9a29509aba",
      "date": "2020-04-22T13:50:52"
    }
  }
}

My delegated permissions have Group.ReadAll

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75dbe68-e162-8861-d194-4a29de3bd731
* Version Independent ID: f58a6930-8575-8306-4273-fc413b979879
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#feedback)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-list-all-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@gavsto 

We tried to get team information by hitting the endpoint as mentioned by you. We added required permissions as mentioned in [Get team](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=http) documentation. And got proper response.
