### ISSUE TITLE
It would be good if Content-Range / total file size was optional

### ISSUE THREAD

**Issue by nb77qlik** [microsoftgraph/microsoft-graph-docs#7882]
e.g.
Content-Range: bytes 101-127/*

...to cater for cases where total file size is not known up front e.g. streaming or data coming from other systems.

This pattern _is_ supported by a number of other similar APIs e.g. S3, Azure Storage etc.

Also this should be supported as per spec https://www.ietf.org/rfc/rfc2616.txt as I understand it?

'The header SHOULD indicate the total length of the full entity-body,
   unless this length is unknown or difficult to determine. The asterisk
   "*" character means that the instance-length is unknown at the time
   when the response was generated.'

I tried sending '*' for total length but it failed with an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7617b83-e358-4b2f-5791-200cef2fcae6
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkocher** [comment]
Relates to #1638.
