### ISSUE TITLE
Sample not loading

### ISSUE THREAD

**Issue by jdrake3** [microsoftgraph/microsoft-graph-docs#7892]
The demo panel is not loading.  It appears to load and then disappear.  The devtools console reports numerous 404 items, and a couple of SameSite=None cookie problems. Windows 10, Chrome: Version 81.0.4044.122 (Official Build) (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19263e31-2ba6-ce30-ebad-dfc8bab66a5e
* Version Independent ID: 60199252-95cb-1712-a020-457b82f17c4c
* Content: [Get servicePrincipal - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/serviceprincipal-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
This issue does not appear to be related to running the example on the serviceprincipal-get.md page. I can successfully run the example. Closing the issue.
