### ISSUE TITLE
Webhook support

### ISSUE THREAD

**Issue by viperfx** [microsoftgraph/microsoft-graph-docs#7893]
Is there a webhook we can provide so that we can planner updates sent to us via our HTTPS endpoint? We would really like to provide this functionality to our customers and it has been highly requested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d13cb91d-9aff-bd44-28d8-ab1f50a67f0c
* Version Independent ID: 5051abac-5bdf-6fb9-154c-d8714b1d8ed8
* Content: [plannerUser resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/planneruser?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/planneruser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/planneruser.md)
* Product: **planner**
* Technology: **microsoft-graph**
* GitHub Login: @TarkanSevilmis
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Thanks for reaching out @viperfx 
This space is reserved to issues with the documentation, to request new features you should create new ideas on uservoice.
There's already an idea for [webhook support in planner](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/37926055-provide-webhooks-upon-planner-and-task-events) that you can upvote.
Upvoting ideas not only helps us prioritizing work, but it also sends you email alerts whenever progress is made.
Closing.
