### ISSUE TITLE
Filtering example is wrong

### ISSUE THREAD

**Issue by RayGHeld** [microsoftgraph/microsoft-graph-docs#7897]
The filter example is wrong -- it will not work without quoting the field.  In the example, you have $filter=riskType eq 'unfamiliarFeatures'  however, this does not work, we get an invalid filter clause error.  If we quote the field like so:  $filter='riskType' eq 'unfamiliarFeatures'  then it works, which is contrary to the docs and other graph endpoints I've experienced.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3001f30-1059-6cec-741c-c62ba8e94aa4
* Version Independent ID: d1a7d0c5-5e46-4010-bf83-da43abdfc896
* Content: [List riskDetection - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/riskdetection-list?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/riskdetection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/riskdetection-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cloudhandler** [comment]
@RayGHeld - I was not able to repro this, I was able to have the filters work without quoting the field
