### ISSUE TITLE
Selecting the domain to be use when creating Office 365 Group

### ISSUE THREAD

**Issue by superz202** [microsoftgraph/microsoft-graph-docs#7904]
Is there a way to select which Domain to be used when creating Office 365 email enabled group?

By default it created the email as TestingADGroup@ABC.onmicrosoft.com but I would like to create it with email TestingADGroup@ABC.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @superz202 

you should have a look at this reply from another Microsoft forum: https://techcommunity.microsoft.com/t5/office-365/change-domain-for-office-365-groups/m-p/275312/highlight/true#M16817

Adam Ochs (reply's author) explains very well how to create Office 365 group with a different domain.

I hope it helps.

Regards,
Jarbas
