### ISSUE TITLE
What about custom fields

### ISSUE THREAD

**Issue by hkusulja** [microsoftgraph/microsoft-graph-docs#7908]
What if we have extension that added additional / custom field.
How to read that data/field info?

Thank you,
Kind regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b252bb3-498a-55be-12ca-1f2fd7abf56f
* Version Independent ID: 52d7e0a4-c94c-2875-007d-2593eab3b51a
* Content: [Get customers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/dynamics-customer-get?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/dynamics-customer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/dynamics-customer-get.md)
* Product: **dynamics-365-business-central**
* Technology: **microsoft-graph**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by henrikwh** [comment]
Hi @hkusulja 
If you add an extension which exposes APIs in BC, you need to access those custom APIs directly on the API endpoint of BC. Theres no notion of tenant specific APIs in Graph.

**Comment by hkusulja** [comment]
> If you add an extension which exposes APIs in BC, you need to access those custom APIs directly on the API endpoint of BC. Theres no notion of tenant specific APIs in Graph.

ok, please update the documentation with that info. thank you
