### ISSUE TITLE
incomprehensible error

### ISSUE THREAD

**Issue by bardashevich-matvei** [microsoftgraph/microsoft-graph-docs#7910]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e527ca2-ecbe-5512-4115-736edc2ce5e6
* Version Independent ID: c5d90251-c824-6abb-ef53-f3594168fc26
* Content: [Create Calendar - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-calendars?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/user-post-calendars.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-calendars.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

Im tried create new calendar for user but received that error

```javascript
GraphError {
  statusCode: 404,
  code: 'ErrorInvalidUser',
  message: "The requested user '3864667a-d3d5-442a-ab36-5031f9353160@6ab3a8f0-1cc4-4557-a006-b10322d52b05' is invalid.",
  requestId: 'a955f6eb-d536-4435-84a3-0c44a2f8bb72',
  date: 2020-04-24T07:13:59.000Z,
  body: `{"code":"ErrorInvalidUser","message":"The requested user '3864667a-d3d5-442a-ab36-5031f9353160@6ab3a8f0-1cc4-4557-a006-b10322d52b05' is invalid.","innerError":{"request-id":"a955f6eb-d536-4435-84a3-0c44a2f8bb72","date":"2020-04-24T10:13:59"}}`
}
```
this is a piece of code which i use for creating user and calendar
```javascript
const graph = require('@microsoft/microsoft-graph-client')

cosnt req = {
  accountEnabled: true,
  displayName: 'TestUser',
  mailNickname: 'TestUser',
  userPrincipalName: 'TestUser@gmail.com',
  passwordProfile: { forceChangePasswordNextSignIn: true, password: 'passworD123' }
}

const calendar = { name: 'TestCalendar' }

const client = graph.Client.init({
        authProvider: done => {
          done(null, appRequest.token)
        }
      })
const user = await client.api('/users').post(req)
const calendar - await client
        .api(`/users/${user.userId}/calendars`)
        .post(request)
```
I have admin permissions for those methods. Why i am receiving that?

**Comment by Harini84** [comment]
Kindly check MS-Graph documentation on resolving authorization errors:

https://docs.microsoft.com/en-us/graph/resolve-auth-errors

**Comment by bardashevich-matvei** [comment]
I checked it but did not see my error in a list. And other methods work fine(user created successfully)
