### ISSUE TITLE
Application.ReadWrite.OwnedBy

### ISSUE THREAD

**Issue by DecorteHannes** [microsoftgraph/microsoft-graph-docs#7911]
Hallo,
When granting Application.ReadWrite.OwnedBy to an Application/Service Principal to allow that one to create other Service Principals (in Applications that one created) it results in a permissions error.
When granting Application.ReadWrite.OwnedBy but now from the legacy Azure Active Directory Graph everything works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Jackson-Woods** [comment]
@sureshja can you help look into this?

**Comment by davidmu1** [comment]
Communicated the issue to engineering. No immediate change to the page. Closing the issue.
