### ISSUE TITLE
Sample is not working and required properties table is false

### ISSUE THREAD

**Issue by AntoineJo** [microsoftgraph/microsoft-graph-docs#7912]
Hi this sample does not work, here is one that works as you need to create the scheduleactionforrule during the creation of the compliancepolicy....

{
"@odata.type": "microsoft.graph.iosCompliancePolicy",
"description": "iOS Compliance Policy",
"displayName": "iOS Compliance Policy",
"scheduledActionsForRule":[{"ruleName":"PasswordRequired","scheduledActionConfigurations":[{"actionType":"block","gracePeriodHours":0,"notificationTemplateId":""}]}],
"passcodeBlockSimple": true,
"passcodeExpirationDays": null,
"passcodeMinimumLength": 4,
"passcodeMinutesOfInactivityBeforeLock": 15,
"passcodePreviousPasscodeBlockCount": null,
"passcodeMinimumCharacterSetCount": null,
"passcodeRequiredType": "numeric",
"passcodeRequired": true,
"securityBlockJailbrokenDevices": true,
"deviceThreatProtectionEnabled": true,
"deviceThreatProtectionRequiredSecurityLevel": "low"
}
sample is from here: https://github.com/microsoftgraph/powershell-intune-samples/tree/master/CompliancePolicy 
You can see that some of the fields shown here as required are not in my sample, but are in your table + the scheduleactionrule is required and you don't have it in your table ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cacdc799-6a14-0887-0f23-ca06a4499273
* Version Independent ID: 15f5d625-2fcb-c111-d850-e15b5ad50bbb
* Content: [Create iosCompliancePolicy - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-ioscompliancepolicy-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-ioscompliancepolicy-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-deviceconfig-ioscompliancepolicy-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Needs to be reviewed by @davefalkus

**Comment by davefalkus** [comment]
@dougeby, @triplanedave, a compliance policy requires scheduledActionsForRule otherwise it will error with "Compliance policy must have one and only one block scheduled action"

**Comment by AlyaKoni** [comment]
Following payload:
`
{
    "@odata.type": "#microsoft.graph.androidDeviceOwnerCompliancePolicy",
    "displayName": "Android Compliance Policy",
    "description": "Checks the compliance of android devices",
    "deviceThreatProtectionEnabled": false,
    "deviceThreatProtectionRequiredSecurityLevel": "unavailable",
    "advancedThreatProtectionRequiredSecurityLevel": "unavailable",
    "securityRequireSafetyNetAttestationBasicIntegrity": false,
    "securityRequireSafetyNetAttestationCertifiedDevice": false,
    "osMinimumVersion": null,
    "osMaximumVersion": null,
    "minAndroidSecurityPatchLevel": null,
    "passwordRequired": true,
    "passwordMinimumLength": 8,
    "passwordMinimumLetterCharacters": null,
    "passwordMinimumLowerCaseCharacters": null,
    "passwordMinimumNonLetterCharacters": null,
    "passwordMinimumNumericCharacters": null,
    "passwordMinimumSymbolCharacters": null,
    "passwordMinimumUpperCaseCharacters": null,
    "passwordRequiredType": "alphanumeric",
    "passwordMinutesOfInactivityBeforeLock": 10,
    "passwordExpirationDays": 365,
    "passwordPreviousPasswordCountToBlock": 1,
    "storageRequireEncryption": null,
    "scheduledActionsForRule": [{
            "@odata.type": "#microsoft.graph.deviceComplianceScheduledActionForRule",
            "ruleName": null,
            "scheduledActionConfigurations": [{
                    "@odata.type": "#microsoft.graph.deviceComplianceActionItem",
                    "actionType": "block",
                    "gracePeriodHours": 0,
                    "notificationTemplateId": ""
                }
            ]
        }
    ]
}
`
Produces the error:
`
Invoke-RestMethod : {
  "error": {
    "code": "BadRequest",
    "message": "Property scheduledActionConfigurations in payload has a value that does not match schema.",
    "innerError": {
      "date": "2020-10-06T20:26:21",
      "request-id": "341bd758-0539-48b2-be8c-06e204f7a5cb",
      "client-request-id": "341bd758-0539-48b2-be8c-06e204f7a5cb"
    }
  }
}
`

How will be a correct payload for a POST to https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies?

**Comment by AlyaKoni** [comment]
Got it with the following payload:
`
{
    "@odata.type": "#microsoft.graph.androidDeviceOwnerCompliancePolicy",
    "displayName": "Android Compliance Policy",
    "description": "Checks the compliance of android devices",
    "roleScopeTagIds": ["0"],
    "deviceThreatProtectionEnabled": false,
    "deviceThreatProtectionRequiredSecurityLevel": "unavailable",
    "advancedThreatProtectionRequiredSecurityLevel": "unavailable",
    "securityRequireSafetyNetAttestationBasicIntegrity": false,
    "securityRequireSafetyNetAttestationCertifiedDevice": false,
    "osMinimumVersion": null,
    "osMaximumVersion": null,
    "minAndroidSecurityPatchLevel": null,
    "passwordRequired": true,
    "passwordMinimumLength": 8,
    "passwordMinimumLetterCharacters": null,
    "passwordMinimumLowerCaseCharacters": null,
    "passwordMinimumNonLetterCharacters": null,
    "passwordMinimumNumericCharacters": null,
    "passwordMinimumSymbolCharacters": null,
    "passwordMinimumUpperCaseCharacters": null,
    "passwordRequiredType": "alphanumeric",
    "passwordMinutesOfInactivityBeforeLock": 10,
    "passwordExpirationDays": 365,
    "passwordPreviousPasswordCountToBlock": 1,
    "storageRequireEncryption": null,
    "localActions": [],
    "scheduledActionsForRule": [{
            "@odata.type": "#microsoft.graph.deviceComplianceScheduledActionForRule",
            "ruleName": "DefaultPolicy",
            "scheduledActionConfigurations": [{
                    "@odata.type": "#microsoft.graph.deviceComplianceActionItem",
                    "actionType": "block",
                    "gracePeriodHours": 0,
                    "notificationTemplateId": "",
                    "notificationMessageCCList": [

                    ]
                }
            ]
        }
    ],
    "id": "00000000-0000-0000-0000-000000000000"
}
`
In addition I had to specify the depth by creating the json body:
-Body ($policy | ConvertTo-Json -Depth 5)

And as a hint, looks like actionType only supports block!

**Comment by triplanedave** [comment]
Thanks for the update.  Closing based on Alya's suggested payload.
