### ISSUE TITLE
Sign in Failure for the Samples

### ISSUE THREAD

**Issue by jdrake3** [microsoftgraph/microsoft-graph-docs#7914]
The samples continue not to load in the frame.  When opening the URL on its own I am unable to login:

Request Id: 45a82863-a64e-44f5-9cdd-81f4b6771b00
Correlation Id: 8636aa09-076a-4212-b7a5-c6f6a61a927e
Timestamp: 2020-04-24T15:56:12Z
Message: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'cb2d7367-7429-41c6-ab18-6ecb336139a6'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2d896b7-98ea-eab0-b1a1-b01266c61c68
* Version Independent ID: bccef64c-675b-364e-30f6-5c1310fef8bd
* Content: [List servicePrincipals - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/serviceprincipal-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
I was able to run all examples on the page. No change identified for this page. Closing the issue. If you can provide specific information about which example you are trying to run on the serviceprincipal-list page, please reopen the issue.
