### ISSUE TITLE
Example 1 in Java not working; Graph-API issues non usefull error message

### ISSUE THREAD

**Issue by blafasel-cc** [microsoftgraph/microsoft-graph-docs#7919]
If I try to create an event according to example 1 (Java) the following request is generated:

    {
      "hasAttachments": false,
      "subject": "Urlaub",
      "body": {
        "contentType": "html",
        "content": "Urlaub vom 27.04.2020 bis 30.04.2020."
      },
      "sensitivity": "normal",
      "start": {
        "dateTime": "2020-04-27T00:00:00",
        "timeZone": "Europe/Berlin"
      },
      "end": {
        "dateTime": "2017-04-30T00:00:00",
        "timeZone": "Europe/Berlin"
      },
      "location": {
        "displayName": "unbekannt"
      },
      "isAllDay": true,
      "showAs": "oof",
      "attendees": [
        {
          "type": "required",
          "emailAddress": {
            "name": "...somename...",
            "address": "...someaddress..."
          }
        }
      ]
    }

(personal information edited)

I get the following error message, which is not very helpful:

    {
      "error": {
        "code": "ErrorPropertyValidationFailure",
        "message": "At least one property failed validation.",
        "innerError": {
          "request-id": "0b84b2a8-f97e-400e-86e5-9e03af503d1e",
          "date": "2020-04-24T17:18:02"
        }
      }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @blafasel-cc 

I am not sure if the example contains invalid configuration. However, the end date of the provided post body is invalid since it is smaller than the specified start date. Consider changing the end date and trying again. BTW, you are right! The error message could be improved.

I hope it helps to clarify your question.

Regards,
Jarbas

**Comment by blafasel-cc** [comment]
Hello @JarbasHorst 
You are right. I just oversaw this typo. Now it works.
Thanks a lot.
Regards,
Hajo
