### ISSUE TITLE
Out-of-Date attribute filter list

### ISSUE THREAD

**Issue by michelnev** [microsoftgraph/microsoft-graph-docs#7928]
It seems there are a few discrepancies between the main Sign-in page and the list of filterable attributes on this page.  For example, isRisky does not seem to be filterable and riskDetail appears to be filterable but isn't listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e7697f-b03a-3282-ebd8-748b65dde87d
* Version Independent ID: bfd3bfb8-4878-b0f7-48f8-ba08a7136108
* Content: [List signIns - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/signin-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/signin-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @kholtz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Page updated via PR #11342.
No additional update identified for the page. Closing the issue.
