### ISSUE TITLE
API to access PIM needs delegated permission as user

### ISSUE THREAD

**Issue by maya-cnx** [microsoftgraph/microsoft-graph-docs#7934]
Is there a way for Apps to use PIM API with just 'read' permission and not requiring the access as signed in user.
PrivilegedAccess.Read.AzureResources
PrivilegedAccess.Read.AzureAD
Instead of delegted permission as user with 
PrivilegedAccess.ReadWrite.AzureResources
permission

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb10229f-46f3-82b2-b8da-6cd567a9f32c
* Version Independent ID: e272dcc2-641d-33d7-ba26-b3d17239bd4e
* Content: [Privileged Identity Management - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/privilegedidentitymanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/privilegedidentitymanagement-root.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by maya-cnx** [comment]
Checking in to see if there is any alternate options available to list PIM role assignements

**Comment by FaithOmbongi** [comment]
Closed via issue [#54262](https://github.com/MicrosoftDocs/azure-docs/issues/54262). No updates identified for the page. Closing this issue.

**Comment by maya-cnx** [comment]
So is this resolved now? Can we use PIM API without delegated user permission?

**Comment by FaithOmbongi** [comment]
No @maya-cnx , as the Engineer clarified and as per the docs, you do require delegated user permissions.
