### ISSUE TITLE
How to create live event

### ISSUE THREAD

**Issue by hmamoun** [microsoftgraph/microsoft-graph-docs#7938]
Hi, I've been struggling in getting C# sample code to create an online live event using MS Graph, can you please help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
@hmamoun 
Is this related to creation of Teams Live event through MS-Graph REST API?

@ananmishr

**Comment by Harini84** [comment]
Closing as no response
