### ISSUE TITLE
Resource not found for the segment 'revokeDeviceLicense'

### ISSUE THREAD

**Issue by NoctOs** [microsoftgraph/microsoft-graph-docs#7945]
POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/{mobileappid}/revokeDeviceLicense returns "Resource not found for the segment 'revokeDeviceLicense'."

Has this been removed from the API? If so, page should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cb769f-9e88-3473-ae93-b8559f5a6a17
* Version Independent ID: 51abb705-1a30-d51b-b58c-17f1812a37b3
* Content: [revokeDeviceLicense action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-iosvppapp-revokedevicelicense?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-apps-iosvppapp-revokedevicelicense.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-apps-iosvppapp-revokedevicelicense.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Can you confirm that you attempted to do the Post with a specific AppID for a VPP app?  The POST you indicated - has {mobileappid] in the URL - not an actual AppID for a VPP app

**Comment by NoctOs** [comment]
Yes to be specific this is what I tried:
`POST https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/f76de9fd-f617-4f96-9137-738d85edc6e2/revokeDeviceLicense`

Request body:
`{"managedDeviceId":"3c288aaa-e8f4-411d-bd42-cc0af994178b","notifyManagedDevices":false}`

**Comment by portaldotjay** [comment]
https://graph.microsoft.com/beta/deviceAppManagement/mobileApps/{mobileAppId}/microsoft.graph.iosVppApp/revokeDeviceLicense is the URI I've been using.

**Comment by peterson-dane** [comment]
This is the same path that I've been using in one of my scripts for some time, but after looking through the docs fairly extensively, I've never really satisfied myself as to why the OData type should show up next to or as part of the ID in that URI, but not any other that I've used in any of my other scripts.

The person whose script I got it from didn't really offer an explanation, either. Would you mind sharing how you came to it, @portaldotjay?

**Comment by portaldotjay** [comment]
@peterson-dane, I usually get my URIs by monitoring requests while doing the action in the portal. I did see other VPP related actions using the URI in documentation though. I think that documentation just needs to be changed to reflect the others.

**Comment by triplanedave** [comment]
Doing a network trace with F12 (or Fiddler) is how I determine how the console makes calls for specific information also.
