### ISSUE TITLE
Missing openShiftId in the c# and javascript call

### ISSUE THREAD

**Issue by jespper** [microsoftgraph/microsoft-graph-docs#7949]
C# and Javascript example is missing openShiftId in the call, would imagine its because its auto generated, but as a get function it should have a way to specify which openShiftId you want.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14eaa6d7-2003-d77a-b507-4325625df9cc
* Version Independent ID: 9102e54d-ecdc-db31-f5fc-a951fea767ae
* Content: [Get openShift - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/openshift-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/openshift-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/openshift-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Could you please check it once the document got updated and I can see openShiftId in both example.

**Comment by HunaidHanfee-MSFT** [comment]
We are closing this issue, feel free to open if you have any query.
