### ISSUE TITLE
unseenCount is always 0 for team

### ISSUE THREAD

**Issue by felixtilli** [microsoftgraph/microsoft-graph-docs#7951]
When I run "https://graph.microsoft.com/v1.0/groups/{teamId}?$select=visibility,unseenCount" unseenCount is always 0, even though there is new messages in the channels of the team. Same for both v1.0 and beta. 

Am I doing something incorrect? Is this expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e064c0-4789-0ec7-1e7c-c36519049ffd
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
@felixtilli - Group is a resource we use for managing members but GET /groups/id API doesn't show anything wrt to team's chat messages.
So unseenCount is always 0 & it is not support through API as of now.
