### ISSUE TITLE
Missleading section "JSON representation"

### ISSUE THREAD

**Issue by chrisspre** [microsoftgraph/microsoft-graph-docs#7958]
Since deviceConfiguration is declared as abstract, this type is never represented on the wire and the section "JSON Representation" is missleading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fecc6c6c-711d-f072-177a-e9effeb1bc4f
* Version Independent ID: 0e4e2c77-7089-8663-ee8c-a128a18af342
* Content: [deviceConfiguration resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-deviceconfiguration?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/intune-deviceconfig-deviceconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-deviceconfig-deviceconfiguration.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've noted this and asked our team to update the docs accordingly.
