### ISSUE TITLE
List calendarView graph api cannot find repeated events booked perversely

### ISSUE THREAD

**Issue by zhxmk** [microsoftgraph/microsoft-graph-docs#7960]
[Enter feedback here]
We found this API is not able to list the events that booked perversely.
For example, the event is recurrence every day, start from yestoday with 5 repeates. When try to get it today(from 00:00:00 to 23:59:59) through this API, it won't show this event. 
I checked the parameter many times, but cannot get any conclusion.
Is it a bug? 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18fec655-72d2-4bdf-9201-ccfc37848e1e
* Version Independent ID: 63536b57-171d-f44f-97db-78afa8b499ae
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-calendarview.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
For recurring events, please check the recurrence pattern using get Event on seriesMasterId of the recurring event:
https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0

To retrieve specific instances within a time range please use list instances:
https://docs.microsoft.com/en-us/graph/api/event-list-instances?view=graph-rest-1.0&tabs=http

If the instances are existing and verified using above steps, please check in calendarView for the time zone details that has been set in header. 

As specified in documentation:
https://docs.microsoft.com/en-us/graph/api/group-list-calendarview?view=graph-rest-1.0&tabs=http

If no timezone offset is included in the value, it is interpreted as UTC.
