### ISSUE TITLE
Delete without sending cancel message

### ISSUE THREAD

**Issue by atiedemann** [microsoftgraph/microsoft-graph-docs#7968]
Hello @all,

is this possible to add a body with property "sendCancelMessageToAttendees": false|true ?
So we can control the behavior of update the appointments.

Thanks
Arne

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9265c344-d87a-cbbe-3dec-90feafc017ca
* Version Independent ID: 47893faf-f604-8a75-4e1f-663722a89631
* Content: [Delete event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-delete?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-delete.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Hi @atiedemann 
As noted in https://github.com/microsoftgraph/microsoft-graph-docs/issues/7339

the current principle is that in calendar the organizer and attendees should all see the same state, details, etc. of a meeting. So it is not possible to delete (effectively cancelling) a meeting that is organized while leaving it on attendee's calendars and not notifying them that the meeting is cancelled.

isDraft property, as noted in documentation works on event Update.
