### ISSUE TITLE
Device compliance policy state and deviceHealthAttestationState

### ISSUE THREAD

**Issue by maspiter** [microsoftgraph/microsoft-graph-docs#7971]
Trying to get info about compliance policy status and device information from deviceHealthAttestationState from a managed device.

1) How can I query the device's compliance status according to assigned compliance policies?
2) Why is the deviceHealthAttestationState object always empty when trying to query this for a managed device (graph v1.0 and beta))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 336b5b0a-2dac-7994-d4dd-1e7eb5d61ac9
* Version Independent ID: 0766eaad-1842-168c-a6c2-81f529370070
* Content: [Get managedDevice - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-get.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
"complianceState" is the property that shows the device's compliance status based on all compliance policies.  It's a calculated value.  If you want to see all the compliance states for each policy assigned to a device, you can use this query: https://graph.microsoft.com/beta/deviceManagement/managedDevices/<deviceID>/deviceCompliancePolicyStates?$filter=((platformType%20eq%20%27WindowsPhone81%27)%20or%20(platformType%20eq%20%27Windows81AndLater%27)%20or%20(platformType%20eq%20%27Windows10AndLater%27)%20or%20(platformType%20eq%20%27all%27))

You need to configure DHA to get the device health attestation information to be reported for a managed device.  See here: https://docs.microsoft.com/en-us/windows-server/security/device-health-attestation
