### ISSUE TITLE
Org Details

### ISSUE THREAD

**Issue by Sladewill** [microsoftgraph/microsoft-graph-docs#7973]
Why are we not able to update the orgs details, there's so few options available here. All of our tenants are created automatically from our upstream provider, so we need the ability to modify Display Name and such from here but cant...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f61b01d3-a8d9-c6ca-78b1-6f86a1eab9d6
* Version Independent ID: 37f99ca1-9770-4d4c-811d-f3eb6167b81c
* Content: [Update organization - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/organization-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/organization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/organization-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @adimitui
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
This functionality is not available via the API. No updates identified for the page. Closing the issue.
