### ISSUE TITLE
Unable to read JSON request payload when using path

### ISSUE THREAD

**Issue by scara1701** [microsoftgraph/microsoft-graph-docs#7974]
When I try the above instructions with the path: value to define a sharepoint document library I get an 'Unable to read JSON request payload' error. 

Used json:

`{
  "requests": [
    {
      "entityTypes": [
        "microsoft.graph.driveItem"
      ],
      "query": {
        "query_string": {
          "query": "value path:\\"https://thisisourcompanytenant.sharepoint.com/sites/Team Site/Documents/Project\\""
        }
      },
      "from": 0,
      "size": 25
    }
  ]
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25e0a8b7-4841-6a4e-1f60-e45e2db93197
* Version Independent ID: 6a5e4816-7e3a-2cee-4e3d-2426c6ccb126
* Content: [Use the Microsoft Search API in Microsoft Graph to search files - Microsoft Graph](https://docs.microsoft.com/en-us/graph/search-concept-files)
* Content Source: [concepts/search-concept-files.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/search-concept-files.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @nmoreau
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by scara1701** [comment]
I was able to get it working in the following format:

`"query": "value path:\\\"https://thisisourcompanytenant.sharepoint.com/sites/Team Site/Documents/Project\""`

Probably a typo with the json escape character. Needs to be path:\\\ instead of path:\\

**Comment by scara1701** [comment]
Got it to work, there seems to be a backslash too many in the article behind path:

`
"query": "value path:\"https://thisisourcompanytenant.sharepoint.com/sites/Team Site/Documents/Project\""`

**Comment by nmoreau** [comment]
Thanks for pointing this out. I've sent a PR to update the doc.
