### ISSUE TITLE
Automatically favorite or follow created channels

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#7976]
Hello I was creating channels for teams using graph api, but end users are saying that they cannot see options to favorite or follow channels on the list of options. So since we can do "Automatically favorite this channel for the whole team members" while creating manually, Is it possible to do the same using the graph api. End users are tired of going to every channel and configuring notifications settings to banner and feed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create Channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Answer to first question:
- Teams does provide option to  favorite or follow channels on the list of options if we create Channel using Graph API.

Answer to second question:
- Graph API provides option to configure notification while creating Channel using Graph, use  below code,
Code:
```
GraphServiceClient graphClient = this.GetGraphServiceClientBeta("Access-Token");
                var channel = new Channel
                {
                    DisplayName = "<Channel display name>",
                    Description = "<Channel description>",
                    IsFavoriteByDefault = true,
                    ModerationSettings = new ChannelModerationSettings()
                    {
                        AllowNewMessageFromBots = true,
                        AllowNewMessageFromConnectors = true,
                        ReplyRestriction = ReplyRestriction.AuthorAndModerators,
                        UserNewMessageRestriction = UserNewMessageRestriction.Everyone,
                    }
                };

                var result = await graphClient.Teams["<Teams GUID id>"].Channels
                    .Request()
                    .AddAsync(channel);
```
Permission: 

> Group.ReadWrite.All
> Channel.Create
> Directory.ReadWrite.All
