### ISSUE TITLE
'Authorization_RequestDenied' for application

### ISSUE THREAD

**Issue by ftomza** [microsoftgraph/microsoft-graph-docs#7978]
Hi!

Executing the method for getting owners on behalf of the app. The necessary permissions are configured for the app "Group. Read.All" and "User.Read.All". After execution, I get an error with the code 'authorization_requestdenied' and the text 'Insufficient privileges to complete the operation.' Until today everything worked fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fffb948-4179-398f-82e5-d8300408b28c
* Version Independent ID: 2cc62631-7aeb-d8fd-d074-4b253df340f1
* Content: [List owners - Microsoft Graph v1.0](https://docs.microsoft.com/en-US/graph/api/group-list-owners?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by thephoton** [comment]
I've started getting this as well this morning - nothing has changed my side. Exact same code, but auth'd as a delegated user works fine.

**Comment by amyasnov** [comment]
Same case. Fix it, please...

**Comment by yyuank** [comment]
Hi there, I just tested list owner API with Group.Read.All and User.Read.All permissions and it worked fine. Looks like this is not a service-related issue. If it continues, please submit a support ticket on Azure portal and provide all the details, so our engineers can further investigate your issues.

**Comment by thephoton** [comment]
> Hi there, I just tested list owner API with Group.Read.All and User.Read.All permissions and it worked fine. Looks like this is not a service-related issue. If it continues, please submit a support ticket on Azure portal and provide all the details, so our engineers can further investigate your issues.

Did you test it as an **application** with those permissions, or a delegated user? It works fine as a delegated user, not as an application.

**Comment by ftomza** [comment]
> Hi there, I just tested list owner API with Group.Read.All and User.Read.All permissions and it worked fine. Looks like this is not a service-related issue. If it continues, please submit a support ticket on Azure portal and provide all the details, so our engineers can further investigate your issues.

If you can't solve the problem here, although at least three people have the same problem working on behalf of the application, and not from a delegated user, please send a link where you can create an incident on the portal. Since my portal sends to github or stackoverflow. That's why I wrote this incident here.

**Comment by yyuank** [comment]
No need to file a support case now. We have an incident reported for the same issue. There appears to be some regression in some regions. We are investigating.

**Comment by ftomza** [comment]
Thanks! fixed it!
