### ISSUE TITLE
companyName has 64-char limit

### ISSUE THREAD

**Issue by omnifreefall** [microsoftgraph/microsoft-graph-docs#7979]
2020-04-28 If I try to update companyName with a value that has more than 64 characters, it gets rejected with a BadRequest.  The documentation, as far as I can see, does not mention this limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Added a sentence to the description that states the limit is 64 characters.
