### ISSUE TITLE
API does not support creating an IOC for Microsoft Defender ATP target and a custom externalId

### ISSUE THREAD

**Issue by meditadvisors** [microsoftgraph/microsoft-graph-docs#7986]
Creating a custom IOC for "targetProduct": "Microsoft Defender ATP" and "externalId": "custom" does not work
The resulting IOC has "externalId": null

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf05975a-c9e1-c566-cdb2-e5fbfac05382
* Version Independent ID: b3e0227d-0f81-db66-1800-3c183f86200c
* Content: [Create threat intelligence indicator - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/tiindicators-post?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/tiindicators-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/tiindicators-post.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@meditadvisors,  "externalId" field currently isn't supported by Microsoft Defender ATP; that's why it returns null. However, it's supported by Azure Sentinel as targetProduct.

**Comment by altersec** [comment]
Thanks for confirmation. Do you have a timeline to fix this?

**Comment by meditadvisors** [comment]
Thanks for confirmation. Do you have a timeline to fix this?

**Comment by chinguyen1** [comment]
@meditadvisors  We will circle back when there is timeline information available. Thanks for your patience.
