### ISSUE TITLE
Pre-consent for CSP apps still doesn't work

### ISSUE THREAD

**Issue by garkavy** [microsoftgraph/microsoft-graph-docs#7990]
Hey,

I get  "code": "Authorization_IdentityNotFound", "message": "The identity of the calling application could not be established.", error message when trying, for example, to retrieve a list of users when using a token issued for CSP customer tenant.
Service principal exists in customer's tenant:
New-AzureADServicePrincipal : Error occurred while executing NewServicePrincipal 
Code: Request_MultipleObjectsWithSameKeyValue
Message: Another object with the same value for property servicePrincipalNames already exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7ca25a-037d-5202-debc-92c06a2c8480
* Version Independent ID: 8ebb4dbc-76a1-00fd-e740-87eda29a40f0
* Content: [Known issues with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/known-issues#feedback)
* Content Source: [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/known-issues.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Thanks for your feedback. Closing the issue since this is still a known issue.
