### ISSUE TITLE
The user is unauthenticated

### ISSUE THREAD

**Issue by BakkerJan** [microsoftgraph/microsoft-graph-docs#7999]
When calling this API with delegated permission, I get "The user is unauthenticated". 
Even with UserAuthenticationMethod.Read, UserAuthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite, UserAuthenticationMethod.ReadWrite.All applied to the app registration (+admin consent)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df4ede94-a1b0-cdce-59c4-f3fde441f74f
* Version Independent ID: 4138842a-de3b-113e-868e-96cc990d32f5
* Content: [List phoneMethods - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/authentication-list-phonemethods.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmcla** [comment]
Hey @BakkerJan, what action and URL are you calling, and are you passing a body with the request? Are you doing this through Graph Explorer or an app of your own?

**Comment by BakkerJan** [comment]
@mmcla I use Power Automate HTTP trigger. I'm using a app regestrion to authentiate:

{
  "tenant": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "audience": "https://graph.microsoft.com",
  "clientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "secret": "*sanitized*",
  "type": "ActiveDirectoryOAuth"
}

I'm calling the https://graph.microsoft.com/beta/users/<ID>/authentication/phoneMethods
![image](https://user-images.githubusercontent.com/38911727/80999973-d4111b80-8e45-11ea-895b-05f3ad235c05.png)

**Comment by ganeshjadhav44** [comment]
Here is the Script that I am using to get the phone number but is failing with the "**User is Unauthenticated**" error message

Function Get-AzureBearerToken {
    [cmdletbinding()]
    Param(
        #Get Tenant Name
        [Parameter(Mandatory=$false)]
        [String]
        $tenantid = "tenantId",

        # Get Client Id
        [Parameter(Mandatory=$false)]
        [String]
        $ClientID = "ClientId",

        # ClientSecret
        [Parameter(Mandatory=$false)]
        [String]
        $ClientSecret = "ClientSecret",

        # Get API resource URI for which token need to be generated
        [Parameter(Mandatory=$false)]
        [String]
        $ResourceURI = "https://graph.microsoft.com/"

    )
    $TokenEndpoint = {https://login.windows.net/{0}/oauth2/token} -f $tenantid
    $Body = @{
            'resource'= $ResourceURI
            'grant_type' = 'client_credentials'
            'client_id' = $ClientID            
            'client_secret' = $ClientSecret
    }

    $params = @{
        ContentType = 'application/x-www-form-urlencoded'
        Headers = @{'accept'='application/json'}
        Body = $Body
        Method = 'Post'
        URI = $TokenEndpoint
    }

    $token = Invoke-RestMethod @params

    return $token
}

$emailaddress = "Ganesh.Jadhav@Cloudtravellers.co.in"

#Get Token
try {
    $null = $response
    $null = $Token
    $Token =Get-AzureBearerToken
}
Catch [System.Exception]
{
    Write-Error -Message "Could not generate token"
    Write-Error -Message $_.Exception.Message
    Break;
}

if($null -ne $Token)
{  
    $Header = @{        
         "Authorization" = "$($Token.token_type) $($Token.access_token)"                  
    }

$UserUri = "https://graph.microsoft.com/v1.0/Users?`$filter=mail eq '$emailaddress'"
$UserUri
$UserDetails = Invoke-RestMethod -Uri $UserUri -Headers $Header -Method Get -ContentType "application/json" 
$UserId = $UserDetails.value.id

$ApiUri = "https://graph.microsoft.com/beta/Users/{0}/authentication/phoneMethods/{1}" -f $UserId, $UserId
$ApiUri
$ApiDetails = Invoke-RestMethod -Uri $ApiUri -Headers $Header -Method Get -ContentType "application/json" 
}

**Comment by BakkerJan** [comment]
@ganeshjadhav44 @mmcla I also tried the script earlier. Gave me the same result.

**Comment by Hoppy7** [comment]
Seeing this from the Microsoft.Graph 0.5.1 PowerShell module as well.

PS C:\Users\rohopkin> Get-MgUserAuthenticationMethod -UserId <userId> -Verbose
Get-MgUserAuthenticationMethod_List: The user is unauthenticated.

**Comment by BakkerJan** [comment]
Figured that application permission are not supported (yet)
