### ISSUE TITLE
Mention "aadroles" path instead of "azureResources" 

### ISSUE THREAD

**Issue by MrAzureAD** [microsoftgraph/microsoft-graph-docs#8004]
It is documented here (https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/azure-ad-roles-features) that with the new Azure AD PIM feature update, all API calls that must change to azure resources but must also change the path "azureResources" to "aadroles". This is not mentioned anywhere in the Graph docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb10229f-46f3-82b2-b8da-6cd567a9f32c
* Version Independent ID: e272dcc2-641d-33d7-ba26-b3d17239bd4e
* Content: [Privileged Identity Management - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/privilegedidentitymanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/privilegedidentitymanagement-root.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The note has been updated. No change identified for the page. Closing the issue.
