### ISSUE TITLE
A little more explanation would be helpful

### ISSUE THREAD

**Issue by geedsen** [microsoftgraph/microsoft-graph-docs#8015]
Maybe an explanation about the differences between 'isRegistered','isEnabled',isCapable','isMfaRegistered' woul really be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 786282cc-2e01-7a67-bff8-7fdfc069d8f3
* Version Independent ID: 56775e93-d8b0-9fda-88ce-b6dd762a11c5
* Content: [List credentialUserRegistrationDetails - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/reportroot-list-credentialuserregistrationdetails.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The properties are defined on the resource page associated with the API: https://docs.microsoft.com/en-us/graph/api/resources/credentialuserregistrationdetails?view=graph-rest-beta. No change identified for this page. Closing the issue.
