### ISSUE TITLE
How to make use of conversationIndex?

### ISSUE THREAD

**Issue by fstuff** [microsoftgraph/microsoft-graph-docs#8021]
Hello, I am trying to use conversationIndex to determine the first message in a given conversation, and also the relative order of the remaining messages.  The message conversationIndex field appears to be giving very large binary numbers as the index (i.e. they do not seem to be sequential and they don't start at 0/1).

For example, I got the following from a request to the messages endpoint
 ConversationIndexRaw: AdYf8b1iXjirj2LERjizCXPAVpBm4w== gives finalAnswer 30810097
ConversationIndexRaw: AQHWH/EY9PZE3h8utUO20Mg+0OZrig== gives finalAnswer 16897567

I don't see any documentation regarding conversationIndex.  Can you please explain how to interpret the values? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd382e4-95b6-3ccf-6a15-02d0cc7ed841
* Version Independent ID: 276cebbe-10bc-100e-f9b1-51b2ba30c64b
* Content: [message resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/message.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
**The following documentation should help:** 
https://docs.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxomsg/9e994fbb-b839-495f-84e3-2c8c02c7dd9b?redirectedfrom=MSDN

**Summarizing - Structure of Conversation Index**
[reserved-1B] [timestamp-5B] [GUID-16B]  [timestamp-5B][timestamp-5B]…[timestamp-5B]
<-------------Header Block---------------->​<-------------------Child Blocks------------------>

- All messages part of the same conversation thread has the same 16-Bytes GUID.
- 5-Bytes [timestamp] in Header Block: System time when message was received converted into FILETIME format.
- 5-Bytes [timestamp] in Child Blocks: Child blocks are present only for Outlook messages, to indicate subsequent messages in a thread while keeping the header block attributes same. Every message reply to a conversation adds a [timestamp] at end to create a new conversationIndex.
- Relative ordering of messages belonging to same conversation thread:
   - _For all messages belonging to same GUID, SORT the messages by conversationIndex values_

**Comment by abheek-das** [comment]
Closing. Please re-open if more clarification is required.
