### ISSUE TITLE
Wipe Request status

### ISSUE THREAD

**Issue by omardroubi437** [microsoftgraph/microsoft-graph-docs#8024]
Is there another command we can use to get the list of selective wipes and there states after running this command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d81a9ca-f860-909c-97db-cc9693ba64d4
* Version Independent ID: a9af3bb7-ceb7-e8fa-38bd-f8a35bc62a4c
* Content: [wipeManagedAppRegistrationsByDeviceTag action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-shared-user-wipemanagedappregistrationsbydevicetag?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/intune-shared-user-wipemanagedappregistrationsbydevicetag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-shared-user-wipemanagedappregistrationsbydevicetag.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
https://docs.microsoft.com/en-us/graph/api/intune-devices-remoteactionaudit-get?view=graph-rest-beta will show the remote actions that have occurred, and the remote actions themselves are here: https://docs.microsoft.com/en-us/graph/api/resources/intune-devices-remoteaction?view=graph-rest-beta

**Comment by triplanedave** [comment]
marking closed.
