### ISSUE TITLE
Remove the top margin of card when sending card as attachment

### ISSUE THREAD

**Issue by itzik-bd** [microsoftgraph/microsoft-graph-docs#8027]
I am trying to remove this top margin of an adaptive card when i send this card as an attachment of a message to a microsoft teams channel. I'm using microsoft graph api to send the message. Does anybody knows how i can remove this top margin?
![image](https://user-images.githubusercontent.com/7790205/80891797-16641c80-8ccf-11ea-8784-6d69ab39e995.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
This is not possible at the moment.
