### ISSUE TITLE
printDocument: uploadData: What is Request Body example ? 

### ISSUE THREAD

**Issue by nguyenquochungptit** [microsoftgraph/microsoft-graph-docs#8028]
I request a binary data but err Unable to read JSON request payload. Please ensure Content-Type header is set and payload is of valid JSON format.
What is Request Body example ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef05093e-f16e-ea6d-9903-052953fd4334
* Version Independent ID: 93653547-e7d1-9245-54d6-a64ffcf39e11
* Content: [printDocument: uploadData - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/printdocument-uploaddata?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/printdocument-uploaddata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/printdocument-uploaddata.md)
* Product: **universal-print**
* Technology: **microsoft-graph**
* GitHub Login: @braedenp-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by braedenp-msft** [comment]
Warning: This API will be changing soon (we will be introducing some breaking changes to the document upload API) so keep an eye on the [changelog](https://docs.microsoft.com/en-us/graph/changelog) to be updated when this happens.

See the example [here](https://docs.microsoft.com/en-us/graph/api/printdocument-uploaddata?view=graph-rest-beta&tabs=http#request) for how to send the request.

Make sure you're **not** setting the Content-Type header to JSON, since the uploadData request contains binary payload.

**Comment by nguyenquochungptit** [comment]
Thanks for your answer ! I read  new change for this API. In my case, I send a Buffer data on Body and set header appication/octet-stream and err message is : " EndByteIndex 27 should be less than document size:1."
My Data Buffer is 
<Buffer 7b 0d 0a 09 6e 61 6d 65 3a 22 68 75 6e 67 22 2c 0d 0a 09 61 67 65 3a 31 38 0d 0a 7d> 
My document size value  = ?

**Comment by nguyenquochungptit** [comment]
@braedenp-msft  please create for me a example of body .

**Comment by braedenp-msft** [comment]
> Thanks for your answer ! I read new change for this API. In my case, I send a Buffer data on Body and set header appication/octet-stream and err message is : " EndByteIndex 27 should be less than document size:1."
> My Data Buffer is
> <Buffer 7b 0d 0a 09 6e 61 6d 65 3a 22 68 75 6e 67 22 2c 0d 0a 09 61 67 65 3a 31 38 0d 0a 7d>
> My document size value = ?

You're almost there! The above error means you sent the right payload in your request, but you forgot to set the size of the document before you started uploading data.

Make sure when you're [creating your print job](https://docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&tabs=http) you set the `sizeInBytes` property of the document, as shown [here](https://docs.microsoft.com/en-us/graph/api/resources/printdocument?view=graph-rest-beta).

**Comment by nguyenquochungptit** [comment]
Hello @braedenp-msft ,glad you answered my questions. Currently I no longer have the above error, however when I run the following code 
`const status = await client
        .api(`/print/printers/${printerId}/jobs/${printJobId}/documents/${documentId}/uploadData`)
        .version('beta')
        .headers({
          'Content-type': 'application/oxps',
          'Range': `bytes=0-100`,
          'Content-Length': 101
        })
        .post(documentData)`
I did not receive the value of **status**.
I read on the document, there are 2 responses are **201** and **202** but I received nothing.

**Comment by braedenp-msft** [comment]
> Hello @braedenp-msft ,glad you answered my questions. Currently I no longer have the above error, however when I run the following code
> ![image](https://user-images.githubusercontent.com/29354611/80998436-2c0f4880-8e6d-11ea-8c6c-76e0823d9bac.png)
> 
> I did not receive the value of **status**.
> I read on the document, there are 2 responses are **201** and **202** but I received nothing.
> Hope to hear from you soon.
> Thank you very much

Awesome, sounds like you're close to getting it working! Since this problem is not related to the documentation, please either:
* File a support ticket if you have a support plan with Microsoft
OR
* Post this issue on the Microsoft Tech community (and say you don't have a support plan)
