### ISSUE TITLE
The specification of "displayName" for the group

### ISSUE THREAD

**Issue by GvYK** [microsoftgraph/microsoft-graph-docs#8035]
When creating the group with duplicate names, the result seems to be different between "Azure Portal" and "Microsoft Graph".

* Azure Portal
  * it doesn't allow to create a group with duplicate names; it causes an error like "Group name is not available.".

* Microsoft Graph
  * it seems that creating a group with duplicate names are allowed; the group that has duplicate "displayName" and unique "id" is created.
  * Here is the example of the request body when checking the operation in "Graph Explorer".

```
{
  "description": "example group",
  "displayName": "security group",
  "mailEnabled": false,
  "mailNickname": "security",
  "securityEnabled": true,
}
```

When it's the specification of "Microsoft Graph", it would be great to consider to add the note: duplicate "displayName" for the group are allowed and it differs from the operation in "Azure Portal".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@GvYK you are correct. Azure portal has uniqueness enforced on group displayName. We are working to close the gap and enforce the uniqueness of displayName on Microsoft Graph as well. We will then update documentation to call out group displayName needs to be unique when creating and updating groups on Graph.
