### ISSUE TITLE
Settings for Tags isn't cloning from original Team

### ISSUE THREAD

**Issue by GHofstadter** [microsoftgraph/microsoft-graph-docs#8039]
I have done a clone from a team. Everthing seems fine, but the setting who can add tags is not copied as it was set in the template. Is it a bug (It always set to "Owners only")?? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c78c38c-b49d-96d7-ff93-37b4f6bb8e6a
* Version Independent ID: 93752ea2-470d-0226-2928-439d71fe711b
* Content: [Clone a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-clone?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/team-clone.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-clone.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@GHofstadter 

We tried this issue locally and we were able to repro this. We are investigating it further with the engineering team.

**Comment by Meghana-MSFT** [comment]
@GHofstadter - Currently this behavior is as expected. Cloning of a team doesn't copy over Tags related settings right now.

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
