### ISSUE TITLE
Get List of Licensed Users

### ISSUE THREAD

**Issue by M365-DenzilFernandes** [microsoftgraph/microsoft-graph-docs#8042]
I cannot seem to find a way to filter users that have been licensed. I am trying to replicate the powershell equivalent of Get-MsolUser -All | Where {$_.isLicensed -eq $true}).Count

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @M365-DenzilFernandes 

[this Microsoft documentation](https://docs.microsoft.com/en-us/office365/enterprise/powershell/view-licensed-and-unlicensed-users-with-office-365-powershell#use-the-azure-active-directory-powershell-for-graph-module) explains how to retrieve licensed and unlicensed users by using Azure Active Directory PowerShell. However, you can retrieve only licensed users by using the following PowerShell command:

```PowerShell
Connect-AzureAD

Get-AzureAdUser | ForEach { $licensed=$False ; For ($i=0; $i -le ($_.AssignedLicenses | Measure).Count ; $i++) { If( [string]::IsNullOrEmpty(  $_.AssignedLicenses[$i].SkuId ) -ne $True) { $licensed=$true } } ; If( $licensed -eq $true) { Write-Host $_.UserPrincipalName} }
```

I hope it helps!

Regards,
Jarbas

**Comment by M365-DenzilFernandes** [comment]
Thanks. I was looking at a Graph API call. I’m aware of PowerShell both methods Get-AzureADUser and Get-MsolUser. I need a graph call as I have been using Power Automate to retrieve a list of Licensed Users for reporting into my PowerBI dashboard. Thank you for your assistance.

**Comment by krbain** [comment]
@SumitParikh can you please take a look at this for user licensing?

**Comment by SumitParikh** [comment]
There is no direct way to do this in Graph. License assignment information on users can be obtained by  querying licenseAssignmentStates property on [user ](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)object. You will have to query this object on each user to find any licenses assigned to users.

**Comment by M365-DenzilFernandes** [comment]
Thanks for the confirmation. Hope to see this in the near future if possible that would be great for admins who are trying to power automate using Graph API calls
