### ISSUE TITLE
createdOnBehalfOf 404s

### ISSUE THREAD

**Issue by jacobwbutler** [microsoftgraph/microsoft-graph-docs#8043]
GET https://graph.microsoft.com/v1.0/applications/--id of application object--/createdOnBehalfOf is returning 404. Can you please explain how to use the 'createdOnBehalfOf' relationship listed in 'Relationships'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c14af104-d60b-1a37-c36c-5282e521c06d
* Version Independent ID: c23c0d2f-5f70-e67d-9068-99e660126fd0
* Content: [application resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/application.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The issue has been communicated to engineering. No immediate change to the page. Closing the issue.
