### ISSUE TITLE
Graph-Explorer

### ISSUE THREAD

**Issue by Michael-Janke** [microsoftgraph/microsoft-graph-docs#8044]
How could I delete a school as a User in the Graph-Explorer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 051b73a2-d01f-26cb-30b5-3875c56a40cd
* Version Independent ID: 6923adb4-62eb-8892-0eb9-ce2573cfb1b2
* Content: [Delete educationSchool - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/educationschool-delete?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/educationschool-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/educationschool-delete.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmast-msft** [comment]
Unfortunately, Graph Explorer can only be used with delegated permission.  So, it cannot access the delete educationSchool API.
