### ISSUE TITLE
Mapping between callRecord and event

### ISSUE THREAD

**Issue by Danialmz96** [microsoftgraph/microsoft-graph-docs#8045]
Is there anyway to know which event on the calendar each call record belongs to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6259f0-9e69-493b-3158-614d11642312
* Version Independent ID: 08963ed9-21ee-773d-3532-75be9cd57e70
* Content: [Get callRecord - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/callrecords-callrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/callrecords-callrecord-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
We do not currently expose any fields that would allow you to do this correlation.
