### ISSUE TITLE
Booking service options

### ISSUE THREAD

**Issue by adeelsheikh** [microsoftgraph/microsoft-graph-docs#8049]
Could not find the following options while creating booking service.
1. Add online meeting
2. Maximum attendees
3. Custom scheduling policy where we can specify date and time slots for booking availability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9155ed-5b13-0b38-dc46-38e240f8f095
* Version Independent ID: 0d87bad1-3197-4469-7d04-d9f36cd51abb
* Content: [Create bookingService - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/bookingbusiness-post-services?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/bookingbusiness-post-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/bookingbusiness-post-services.md)
* Product: **bookings**
* Technology: **microsoft-graph**
* GitHub Login: @arvindmicrosoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by eLiXee** [comment]
I also did not see an option for adding an online meeting when creating a booking appointment. Did you find any solution to this?
