### ISSUE TITLE
needs a c# example

### ISSUE THREAD

**Issue by gotmike** [microsoftgraph/microsoft-graph-docs#8054]
seeing HTTP and Javascript, but a c# example would be nice...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e621007-b67f-9b43-a215-34346262a307
* Version Independent ID: 5f103903-d402-281a-aaa9-38cfe1ce9d00
* Content: [Update range - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/range-update?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/range-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/range-update.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by gotmike** [comment]
something like this...

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

// for string values
var rangeUpdate = new Microsoft.Graph.WorkbookRange
{
    Values = "someValue"
};

var workbookRange = await graphClient.Me.Drive.Items["{id}"].Workbook.Worksheets["{sheetName}"]
	.Range("{rangeName}")
	.Request()
	.PatchAsync(rangeUpdate);

**Comment by grangeryy** [comment]
We will update the docs to include c# example. Thank you for reporting:)

**Comment by gotmike** [comment]
Would be great if the example shows multiple values like your example with HTTP above.

Trying to replicate in C# using the Microsoft Graph SDK for .NET and seeing issues.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/695
https://stackoverflow.com/questions/61892869/update-values-in-excel-named-ranges-using-microsoft-graph-api

Single values seem to work but arrays not acting as expected.

**Comment by pfaisant** [comment]
Does it make sense to switch from Interop libraries to MS Graph ? Do you have a full example in c# ? Why don't you have a wrapper to make it easier to manipulate excel files ?

**Comment by grangeryy** [comment]
Close this since no feedback from customer for a while. Pls reopen later if necessary. Thx!
