### ISSUE TITLE
Unauthorized response with Directory.Read.All permission 

### ISSUE THREAD

**Issue by Ofekdavid21** [microsoftgraph/microsoft-graph-docs#8059]
I have a token with permission type delegated and Directory.Read.All permission and the response that I get from the API call is unauthorized.
Is there a reason why I get this response? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
Directory.Read.All permissions should suffice. If you are still seeing this issue please re-open with more details about the call and the specific error you're seeing. No doc updated needed. Closing the issue.
