### ISSUE TITLE
Access Denied when using https://graph.microsoft.com/v1.0/sites/siteid/drive/items/driveid/invite

### ISSUE THREAD

**Issue by RuneVed** [microsoftgraph/microsoft-graph-docs#8077]
We are having problems adding permissions to a drive item in our sharepoint site. 

We are using user credentials to get an authorization token from azure that we then use for our graph api calls.

The /invite call worked when we used client secret and Application Permissions, but we have changed to use Delegate permissions to have a more secure solution. 

Our body for the call to https://login.microsoftonline.com/TenantID/oauth2/v2.0/token has:
- client_id: a client id
- scope:https://graph.microsoft.com/.default
- grant_type:password
- userName: email
- password: a password 
- response_type:token

We have added these permissions on Azure:
![image](https://user-images.githubusercontent.com/25870765/81153325-18ee9c80-8f83-11ea-90fd-3525e5fd946c.png)

When trying to add permissions to the drive item we get the scenario that is shown in the screen capture:
https://graph.microsoft.com/v1.0/sites/COMPANYSHAREPOINTID/drive/items/DRIVEITEMID/invite

![image](https://user-images.githubusercontent.com/25870765/81153132-e9d82b00-8f82-11ea-9c59-54ca2a2da309.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75e1562-24d6-bfaf-be46-d52ee93ffb1d
* Version Independent ID: cd35f8f6-774e-70d3-9bd5-11110ab450b1
* Content: [Send an invite to access an item - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-invite?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-invite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-invite.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by JhoeyPTP** [comment]
Found out today that /invite works if we invite people outside the organization, why is it like this? do we have to use a diffrent call for people in and outside the organization?

**Comment by JhoeyPTP** [comment]
We found the issue, and though we should inform you :)

The issue was that the user that we authenticated with diddn't have access to the root site.
This took a while to figure out cause the error code diddn't help much, and we couldn't find any documentation on this spesific issue. 

Message me if you have question about the issue
