### ISSUE TITLE
Unclear what ID is

### ISSUE THREAD

**Issue by hjfitz** [microsoftgraph/microsoft-graph-docs#8079]
The page doesn't state what {id} in the url - is this the id of the user or the role? Can I use this API to give any user any role (given I have the right permissions?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 061d0988-fe99-3d08-b515-b4173f09d794
* Version Independent ID: b7e963b3-ea6a-90e6-12c6-31076f3beab8
* Content: [privilegedRoleAssignment: makePermanent - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/privilegedroleassignment-makepermanent?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/privilegedroleassignment-makepermanent.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/privilegedroleassignment-makepermanent.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The id is the identifier of the privilegedRoleAssignment object. No change identified for the page. Closing the issue.
