### ISSUE TITLE
C# example of updating user/group with schema extension needed.

### ISSUE THREAD

**Issue by zumiek** [microsoftgraph/microsoft-graph-docs#8080]
Is it possible for you to provide us with a C# example of how to update a user/group via schema extension?
Or how do I update the User object with my custom properties, I can't seem to find AdditonalData prop anymore?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ffa23e-2e9e-690f-ac7f-6bd71f91bb3e
* Version Independent ID: a28c9070-172f-f26e-4e79-916439f4ee94
* Content: [Add custom data to groups using schema extensions  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/extensibility-schema-groups#feedback)
* Content Source: [concepts/extensibility-schema-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/extensibility-schema-groups.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
@andrueastman @darrelmiller Is there a way to add the SDK code snippets to a conceptual doc?

**Comment by davidmu1** [comment]
The request has been communicated to engineering. No immediate change identified for the page. Closing the issue.
