### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by MrAzureAD** [microsoftgraph/microsoft-graph-docs#8083]
The example returns the error message "Write requests are only supported on contained entities"
Obviously the suffix $ref is missing.

The correct URL therefor must be 
https://graph.microsoft.com/beta/servicePrincipals/{id}/claimsMappingPolicies/$ref

Please correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30af93d9-4720-8376-d24e-6e8d33fe69ed
* Version Independent ID: de36d578-1a56-eb3f-a417-4c71ce17c31d
* Content: [Assign claimsMappingPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-claimsmappingpolicies?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-post-claimsmappingpolicies.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by akingscote** [comment]
Hmm still dosent work for me, even with the `$ref` suffix.
```
cat <<- EOF > policyAssignment.json
{
    "@odata.id":"https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/xxxxxxxxxxxxxxxxxxxxx"
}
EOF
az rest --method post --headers Content-type="application/json" --url "https://graph.microsoft.com/beta/servicePrincipals/${SP}/claimsMappingPolicies/$ref" --body @policyAssignment.json
```

**Comment by davidmu1** [comment]
Added $ref to the example.
