### ISSUE TITLE
The Second "Important" box needs to be removed or extend the notification period

### ISSUE THREAD

**Issue by mmushatt** [microsoftgraph/microsoft-graph-docs#8084]
The Microsoft Support Team has been contacted by several customers that are pointing to this "Important" information concerning changes to the API and being notified.  It says that it ended November 2019 and the form is no longer available.  What are they supposed to do now if changes occur and they would like to be notified prior?  Either we need to be removed this "Important" information box or we need to provide another means for customers to receive prior notice when PIM API's are being modified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb10229f-46f3-82b2-b8da-6cd567a9f32c
* Version Independent ID: e272dcc2-641d-33d7-ba26-b3d17239bd4e
* Content: [Privileged Identity Management - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/privilegedidentitymanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/privilegedidentitymanagement-root.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
It appears that this page has been changed. No other change identified. Closing the issue.
