### ISSUE TITLE
I tried this using Graph explorer with header Prefer: return=minimal. Started the stop watch timer.

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#8085]
I was wondering if I make group add favorite, hoping team related to that group would be favorite too or be on the top team panel. But this API keeps running in the graph explorer and timer is still going on. I even tried without Prefer Header. That makes me think that this API is not working. I thought it would take time to give me result and waited till 5 mins on the stopwatch. API query is still running on the new graph explorer.
Please responsible party look into it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b001ad-f146-d57f-8318-34c28c45be8c
* Version Independent ID: 333de945-5a1d-93f0-8e0a-e59e8118776d
* Content: [group: addFavorite - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-addfavorite?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-addfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-addfavorite.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@ashoksubedi1 I can repro this in my environment too. We will investigate.

**Comment by yyuank** [comment]
@ashoksubedi1 I tried it today and it worked. Please let me know if it works for you too.

**Comment by ashoksubedi1** [comment]
@yyuank  Hi, are you trying in Graph Explorer because it is still not working for me. I tried with both Prefer header and without it. It is still running. Should I try from code ?

**Comment by yyuank** [comment]
@ashoksubedi1 I tried in Graph Explorer. Yesterday it didn't work, exactly the same way you described. Today it worked fine. I suspect there's regression and a fix has started to roll out. I'll close this issue for now. Send me a note if it doesn't work for you still tomorrow and I'll post it on StackOverflow.

**Comment by ashoksubedi1** [comment]
@yyuank this api endpoint is still not working I am sorry. the query on the graph explorer is still loading
