### ISSUE TITLE
The property isDefaultCalendar is not returning for /me/calendars

### ISSUE THREAD

**Issue by db-dblank** [microsoftgraph/microsoft-graph-docs#8087]
The property `isDefaultCalendar` is not returning for `/me/calendars` even if set in `select` parameter.

I need to know which calendar is the user's default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a073f203-e931-588c-7b15-227483fe01fb
* Version Independent ID: 59982274-4dae-4c9e-fd55-414ec30c0573
* Content: [calendar resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/calendar.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/calendar.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
That property does not exist on v1 (verified in the metadata). It's beta only. The docs are wrong here. As a workaround you can do `GET /me/calendar` to get the default calendar.

From `https://graph.microsoft.com/v1.0/$metadata`

```
<EntityType Name="calendar" BaseType="graph.entity">
    <Property Name="name" Type="Edm.String" />
    <Property Name="color" Type="graph.calendarColor" />
    <Property Name="changeKey" Type="Edm.String" />
    <Property Name="canShare" Type="Edm.Boolean" />
    <Property Name="canViewPrivateItems" Type="Edm.Boolean" />
    <Property Name="canEdit" Type="Edm.Boolean" />
    <Property Name="owner" Type="graph.emailAddress" />
    <Property Name="allowedOnlineMeetingProviders" Type="Collection(graph.onlineMeetingProviderType)" />
    <Property Name="defaultOnlineMeetingProvider" Type="graph.onlineMeetingProviderType" />
    <Property Name="isTallyingResponses" Type="Edm.Boolean" />
    <Property Name="isRemovable" Type="Edm.Boolean" />
    <NavigationProperty Name="singleValueExtendedProperties" Type="Collection(graph.singleValueLegacyExtendedProperty)" ContainsTarget="true" />
    <NavigationProperty Name="multiValueExtendedProperties" Type="Collection(graph.multiValueLegacyExtendedProperty)" ContainsTarget="true" />
    <NavigationProperty Name="calendarPermissions" Type="Collection(graph.calendarPermission)" ContainsTarget="true" />
    <NavigationProperty Name="events" Type="Collection(graph.event)" ContainsTarget="true" />
    <NavigationProperty Name="calendarView" Type="Collection(graph.event)" ContainsTarget="true" />
</EntityType>
```

**Comment by Harini84** [comment]
Work item created for tracking with dev. team

**Comment by Harini84** [comment]
Documentation updated
