### ISSUE TITLE
I create a Group using Graph API, and then added a team to that group. My team gets created but not those members

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#8088]
So I go to Azure portal and look at the members of that group and I see all the members I added over there. So definitely my code is working good. Why can not I see all the azure ad group members in Team right away. I heard it takes about 48 hours for those members to get access to that team. Owners of the group have access to the team right way but members have no clue that there is a new team that they are part of. Any suggestions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ashoksubedi1** [comment]
@nkramer  any update on this. Thank you

**Comment by Meghana-MSFT** [comment]
@ashoksubedi1 

We have followed the document provided by you. We were not able to repro the issue. We see members of the group also have access to the team right way. Please try and check again.

**Comment by Meghana-MSFT** [comment]
Closing this issue for now. Please feel free to reopen this issue if you are still facing the issue.
