### ISSUE TITLE
Which Id is used here as messageId, could you please explain it.

### ISSUE THREAD

**Issue by SwatiTangade2503** [microsoftgraph/microsoft-graph-docs#8098]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 255b956c-6f75-2e82-acfa-f8943bfb5614
* Version Independent ID: e0782778-3134-8905-3bce-98a79fef2d51
* Content: [message: reply - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-reply?view=graph-rest-1.0&tabs=http#request-body)
* Content Source: [api-reference/v1.0/api/message-reply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-reply.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ShaktiSubhraPSwain** [comment]
The id of the mail to which you want to reply

**Comment by svpsiva** [comment]
Every message has a unique identifier and the same can be obtained while listing messages using /me/messages/
