### ISSUE TITLE
Response 202 might come to early? if followup tasks after create are needed

### ISSUE THREAD

**Issue by ofunk** [microsoftgraph/microsoft-graph-docs#8099]
POST https://graph.microsoft.com/beta/teams
works with no error
Returns 202 as foreseen

patch of groupID to change from static to dynamic grouping 
works with not error
Returs 204 as forseen

But the Sharepoint site creatation seems to fail everytime the patch is coming immediadelly after 202 Response. 
If we wait for 1-2 hours -- patch works and SPO site is created in between.

Is there a chance to get a status for SPO creation succeeded before next graph call on Group happens?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Can you share errors or logs?
