### ISSUE TITLE
Buggy policy permissions (create tokenIssuancePolicy/conditionalAccessPolicy)

### ISSUE THREAD

**Issue by 16pierre** [microsoftgraph/microsoft-graph-docs#8106]
Using a default account (no roles assigned), I tried to create policies:
- POST `tokenIssuancePolicy` => rejected
- POST `tokenLifetimePolicy` => authorized

Yet, the docs show that the same permissions are required: `Policy.ReadWrite.ApplicationConfiguration`.
Either docs need an update, or there's a backend issue ?

Also: I've spent hours trying to understand the exact permissions related to the [Directory Synchronization Accounts role](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#directory-synchronization-accounts-permissions), which has quite a few `policies permissions`, yet I still can't understand the _precise_ impact of these permissions : it'd be great if you also could clarify your AAD roles permissions docs, and make it consistent with the Graph docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6906bc8-5a61-59cb-9489-6d08791f3995
* Version Independent ID: e3f234c4-34d5-4e7f-8cf6-a79f22852295
* Content: [Create tokenLifetimePolicy - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/tokenlifetimepolicy-post-tokenlifetimepolicies?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/tokenlifetimepolicy-post-tokenlifetimepolicies.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @lujiangfeng666
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by 16pierre** [comment]
Also curious to understand what the `microsoft.directory/policies/owners/*` permissions refer to in the [AAD roles docs](https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/directory-assign-admin-roles#directory-synchronization-accounts-permissions): I can't seem to find an `owner` property in the _stsPolicy_ objects

**Comment by FaithOmbongi** [comment]
Thank you @16pierre for raising this issue and my apologies for the delayed response. 

Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Graph on Q&A](https://docs.microsoft.com/en-us/answers/products/graph). Please ask your question there.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
