### ISSUE TITLE
Alternative minimal response behavior - tracking property changes

### ISSUE THREAD

**Issue by spanmatej** [microsoftgraph/microsoft-graph-docs#8117]
To properly track and sync event changes with an external application, the delta query for Calendar events should also support only tracking property changes and not just add/update/delete actions of events.

The best example of this is tracking changes on users:
https://docs.microsoft.com/en-us/graph/api/user-delta?view=graph-rest-1.0&tabs=http#example-3-alternative-minimal-response-behavior

Having the option of only tracking actual changes allows us to integrate with an external application in a way that changes between the two are merged, rather than overriden. A much bigger problem would also arise if these same events would be synced with yet another application. This would greatly increase the chances of missing/corrupted data.

Thank you for all the work and best regards, 
Matej

---
#### Podrobnosti dokumenta

⚠ *Ne uredite tega razdelka. Potreben je za povezovanje težav med storitvama docs.microsoft.com in GitHub.*

* ID: f65c9af5-60ee-0887-c63b-0dc338450ec3
* Version Independent ID: 2f7fef8b-4379-1847-751b-f53508ab7bae
* Content: [event: delta - Microsoft Graph v1.0](https://docs.microsoft.com/sl-si/graph/api/event-delta?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-delta.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Not part of current road-map. Please create the request in MS-Graph Uservoice for the feature to be voted and prioritized:

https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests
