### ISSUE TITLE
Amount result of user not same with the AD

### ISSUE THREAD

**Issue by kadalcj** [microsoftgraph/microsoft-graph-docs#8121]
I've realized that what I get when request /users , the result I get from it are just small amount of user that stored in Azure AD.
I tried on the Explorer too, and same result. How can I get it all?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jfendors** [comment]
Did you get all the pages of info?

https://docs.microsoft.com/en-us/graph/paging

**Comment by davidmu1** [comment]
@kadalcj - The basic GET call does return only a subset of all properties. When you look at the user resource page:

https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta

You will see many properties with this in the description: Returned only on $select.

To get to these properties, use something like this: GET https://graph.microsoft.com/beta/users?$select=displayName

For more information, see https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2Fbeta&view=graph-rest-beta#select-parameter
