### ISSUE TITLE
Page not referenced in the navigation

### ISSUE THREAD

**Issue by MrAzureAD** [microsoftgraph/microsoft-graph-docs#8122]
Adding owners is listed in the navigation for applications, but not for service principals.
Both operations are often done together so they should these operations should be either both available in the side navigation or none of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8641fff-2063-de08-4c79-743d82ae962f
* Version Independent ID: 72b36f35-e582-9742-e982-419fc2354faf
* Content: [servicePrincipal: Add owner - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-owners?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/serviceprincipal-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/serviceprincipal-post-owners.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Not seeing the issue to be resolved. Both the serviceprincipal resource and the application resource lists the add owner method under the Owners section of the Methods table and lists the owners relationship in the Relationships table. No change identified for the page. Closing the issue.
