### ISSUE TITLE
Additional Properties

### ISSUE THREAD

**Issue by danmyhre** [microsoftgraph/microsoft-graph-docs#8123]
Are there plans to expose additional (including custom) attributes from the SharePoint user profile service?  It is great that things like Skills are being pulled in...what about additional data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba12e15-4ac1-c0c2-ee37-23e84b6dba14
* Version Independent ID: 4a43deca-3890-cf08-2f59-c223a8c00fd3
* Content: [profile resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/profile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/profile.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by kevinbellinger** [comment]
We're working on the design for the extensions at the moment. skills, projects, interests & education are already available in Profile API and get synced in from SharePoint if present. Responsibilities and AboutMe will be coming in an update soon. (May/June) 

With custom attributes, I don't have a timeline I can share just yet. Hopefully in the Ignite 2020 timeframe we can share something more concrete about timings.

**Comment by danmyhre** [comment]
Thanks for the reply!  Do you know if SPO's user profile service is planned to stay the master source for this type of information (you mentioned a sync)?  Bit of a challenge right now trying to decide between AAD with the msDS-cloudExtensionAttribute* attributes vs the SPO UPS.

**Comment by kevinbellinger** [comment]
We're working on a long-term story where mastering will switch for the majority of the profile properties to the profile service that is available on Graph. 

For extensions - you also have the extensibility mechanisms available from MS Graph on user which are worth investigating
