### ISSUE TITLE
dynamic group

### ISSUE THREAD

**Issue by ismo-creator** [microsoftgraph/microsoft-graph-docs#8125]
can you provide a dynamic group example with a baked-in rule

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@ismo-creator Could you please clarify what a dynamic group with a baked-in rule means? If you need an example of dynamic group rule, please visit here: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-dynamic-membership
