### ISSUE TITLE
Permissions issue when calling 'appliesTo' endpoint for homeRealmDiscoveryPolicies

### ISSUE THREAD

**Issue by ttunstall07** [microsoftgraph/microsoft-graph-docs#8126]
It appears the permissions required for calling the referenced endpoint were recently updated and it is no longer working as expected. 

I'm not sure if this is a bug or the documentation is incorrect, but I tried gradually assigning each permission shown from least to most privileged until I eventually had them all (both delegated and application) and was still unable to successfully authorize. We eventually had to fall back on the [Azure AD Graph API](https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/policy-operations#list-applications-and-service-principals-with-specific-policy-assigned) as a temporary workaround, which still seems to work with the same permissions.

Another issue I noticed in the documentation is an inconsistency in the URL path shown under 'HTTP Request' and in the 'Examples' section below it (note the missing 'policies' segment in the example):

**HTTP Request:**
GET /**_policies_**/homeRealmDiscoveryPolicies/{id}/appliesTo

**Examples:**
GET https://graph.microsoft.com/beta/homeRealmDiscoveryPolicies/{id}/appliesTo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff6120a2-acbb-19e3-6bf0-2a22c60adac8
* Version Independent ID: 27944c54-c11a-c2ba-a1f3-f975e984c25d
* Content: [List appliesTo - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/homerealmdiscoverypolicy-list-appliesto?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/api/homerealmdiscoverypolicy-list-appliesto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/homerealmdiscoverypolicy-list-appliesto.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @hpsin
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hpsin** [comment]
Thanks @ttunstall07 - I'm looking into this internally with the backing team.  Will do some debugging and get back to you.

**Comment by hpsin** [comment]
Hi @ttunstall07 - thanks for your patience.  The team discovered a bug with one of the permissions queries, and it's being fixed now.  It'll take a bit to make it out to production, so I'll let you know here when it's fixed.  Thank you for reporting this!

**Comment by ttunstall07** [comment]
Great, thanks! Looking forward to hearing back.

**Comment by hpsin** [comment]
Hi @ttunstall07 - the fix rolled out to PROD today.  My testing indicates that it works now using just Application.Read.All, Policy.Read.all.  Do let me know if you still run into troubles with this, and thank you for reporting it!

**Comment by hpsin** [comment]
#please-close  
if Tyler indicates an issue we'll reopen.

**Comment by ttunstall07** [comment]
Awesome - thanks for the quick response! Just did a quick Postman test and it appears to be working as expected now. Thanks again!

**Comment by hpsin** [comment]
Great to hear, thanks for checking!
