### ISSUE TITLE
How to Correlate with Service Principal?

### ISSUE THREAD

**Issue by jacobwbutler** [microsoftgraph/microsoft-graph-docs#8129]
Without an appId property on this template, how can I tell which service principal it correlates with in the tenant? Is there a reliable mapping from application template displayName to service principal displayName?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 105c3b64-9092-e23a-0e05-d57136a72278
* Version Independent ID: 5ff0c889-dd39-e40d-a919-e42bf169ea7e
* Content: [applicationTemplate resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/applicationtemplate?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/applicationtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/applicationtemplate.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @luleonpla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by luleonpla** [comment]
When you query the servicePrincipal resource type. You will see a property "applicationTemplateId". If you see a GUID, it correlates to the applicationTemplate from which the servicePrincipal was instantiated.

**Comment by jacobwbutler** [comment]
Thanks @luleonpla. Unfortunately 'applicationTemplateId' is null for me, for a service principal provisioned through the AAD App Gallery. Are there not application templates for all AAD App Gallery apps? Also, there is an application template object with the same display name as my service principal. I see the difference in homepage url but don't know if this is a reliable property. 

Service Principal:
![image](https://user-images.githubusercontent.com/14024128/81616353-2f885f80-9398-11ea-9369-ae9576bb251b.png)
Application Template 
![image](https://user-images.githubusercontent.com/14024128/81616099-bab52580-9397-11ea-8727-c3548b4e88d6.png)

**Comment by luleonpla** [comment]
Are you creating the gallery app using the UI, right? Not the applicationTemplate API. If you use the public preview version of the Azure AD Gallery or the applicationTemplate API, you should see the applicationTemaplteId populated. 

We will provide a way to back-fill these new properties for existing applications that doesn't have. I don't have an ETA for when that's going to happen yet but it's in the plan. 

Regarding the homePageURL and name, we do give the same name from the applicationTemplate to the SP when created from the UI. If you create it via the applicationTemplate API, then you need to provide your own name. Also, the homePageURL will be the same for all instances of SP created from the applicationTemplate. 

What's the main scenario you're trying to achieve?

**Comment by jacobwbutler** [comment]
Yes, I am creating from the AAD Gallery:
![image](https://user-images.githubusercontent.com/14024128/86266160-699d0300-bb8a-11ea-80c5-3f6701846b62.png)
and the applicationTemplateId is still null
![image](https://user-images.githubusercontent.com/14024128/86266363-b7b20680-bb8a-11ea-8761-b6a1577ab445.png)

The scenario I need is: to be able to correlate every service principal in my tenant to it's application template - if it was created from one

**Comment by luleonpla** [comment]
I think we should be able to close this issue. We got the feedback from Jacob and we're working on GAing this API. 

#please-close
