### ISSUE TITLE
List `conversationMembers` method not real-time

### ISSUE THREAD

**Issue by ja-onereach** [microsoftgraph/microsoft-graph-docs#8136]
On adding a new member to a conversation, we have observed that there is an approximately 15 minute delay before the `conversationMembers` list method returns an up-to-date result including the new member. We have confirmed this using Postman to eliminate the possibility that it's a caching issue within our system. If it is somehow impossible for this method to reflect real-time data, it would be helpful if it would return a timestamp indicating the age of the response value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c0f5d6-3a9f-3818-d049-314aa8ec7b93
* Version Independent ID: 43f8ac19-de77-95d6-a7ec-4ce37026305e
* Content: [List conversationMembers - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prithvi-MSFT** [comment]
Hi, Are you still facing the issue, We tried the API and it reflected the added members instantly. Please let us know if you are still facing it.


Thanks

**Comment by ja-onereach** [comment]
Thanks for the follow-up. We've retested this and no longer see the issue. I'll post a message here if it ever recurs. Thanks!
