### ISSUE TITLE
No documentation for Tags

### ISSUE THREAD

**Issue by MrHinsh** [microsoftgraph/microsoft-graph-docs#8139]
Hey, I have found "/api/v1/teams/{0}/memberTags/" but there does not seam to be any documentation listed for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5463d788-8e29-ca0a-5490-93506ff1ec80
* Version Independent ID: 1e7ca228-0b9f-beb1-d61f-7f1fdff50008
* Content: [Use the Microsoft Graph API to work with Microsoft Teams - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teams-api-overview.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @MrHinsh 

I tried the endpoints below using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explore) without success:

* GET https://graph.microsoft.com/beta/teams/{teamsID}/memberTags
* GET https://graph.microsoft.com/v1.0/teams/{teamsID}/memberTags

It looks like those APIs are not available yet. Maybe it is something that hasn't been released yet and is still under development.

Regards,
Jarbas

**Comment by Meghana-MSFT** [comment]
@MrHinsh 

Could you please provide details on the above ask?

**Comment by Meghana-MSFT** [comment]
We are closing this issue for now. Please feel free to reopen this issue if you are still facing the issue.
