### ISSUE TITLE
Error EndOfInput

### ISSUE THREAD

**Issue by JSANT16** [microsoftgraph/microsoft-graph-docs#8140]
Hello, when i try to request https://graph.microsoft.com/beta/administrativeUnits/{id}/members/$ref
whit the body 
{
  "roleId": "53",
  "roleMemberInfo": {
    "id": "id-of-user"
  }
}
I get the error "An unexpected 'EndOfInput' node was found when reading from the JSON reader. A 'StartObject' node was expected."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a5ba9f-ea66-94b1-b5cd-bf9b97e6e0c0
* Version Independent ID: 7a586d2e-260b-fa2d-5981-18797d37ff02
* Content: [Add a scopedRoleMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/administrativeunit-post-scopedrolemembers?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/administrativeunit-post-scopedrolemembers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/administrativeunit-post-scopedrolemembers.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @anandyadavMSFT
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
My apologies for the delayed response.

Could you confirm that you are using only _User account administrator_ or _Helpdesk administrator_ roles roleId's to assign scoped-role memberships? If you are and still hitting the error, kindly post this question at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/microsoft-graph-applications.html) so the Engineering team can troubleshoot with you.
