### ISSUE TITLE
When will this be out of preview?

### ISSUE THREAD

**Issue by 0xVesion** [microsoftgraph/microsoft-graph-docs#8144]
When will the callRecords functionality be out of preview? Is the preview status the reason why the webhook has a delay of about 5 minutes to be called after ending a teams call? It would greatly improve my apps ux if this delay would be less than 1 minute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddac89dc-594c-bb39-a440-41f2f95ba932
* Version Independent ID: 9ba737f6-bad9-30e3-826c-97cebb6c5a58
* Content: [Call records overview - Microsoft Graph](https://docs.microsoft.com/en-us/graph/cloud-communications-callrecords)
* Content Source: [concepts/cloud-communications-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/cloud-communications-callrecords.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
The preview state is unrelated to the webhook's latency.

The reason that we have this minimum delay of a few (5-10) minutes is that our data processing path prioritizes completeness with fewer versions over end-to-end latency. For example, the Call Record entity includes data from the star rating prompt at the end of a call. We need to wait for a few minutes to make sure that we don't need to generate a new call record version once that data comes in if a participant answered the prompt late, which would require consumers to consume the call record multiple times to get all the data.

**Comment by 0xVesion** [comment]
> The preview state is unrelated to the webhook's latency.
> 
> The reason that we have this minimum delay of a few (5-10) minutes is that our data processing path prioritizes completeness with fewer versions over end-to-end latency. For example, the Call Record entity includes data from the star rating prompt at the end of a call. We need to wait for a few minutes to make sure that we don't need to generate a new call record version once that data comes in if a participant answered the prompt late, which would require consumers to consume the call record multiple times to get all the data.
> 
> In terms of GA timing, I don't have exact dates to share, but we're working on getting there fairly soon.

Thank you @stephenjust  very much for the reply. This definitely helped clear things up. Is there any way I can decrease the latency of the webhook? Is there another endpoint I could use to just get the data related to start, end and participants after the call has ended?

**Comment by stephenjust** [comment]
Unfortunately, I'm not aware of such an API. You're welcome to add an item to UserVoice for this, so we can better track demand and prioritize the request.

**Comment by 0xVesion** [comment]
Thank you @stephenjust 
I created the request over on uservoice
https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/40431649-api-for-retrieving-teams-call-records-more-easily
