### ISSUE TITLE
Object types

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#8148]
Can you please update the article to explicitly mention which types of objects are supported by this query. And same for the getByIds endpoint. For example, you cannot query for an application object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7ee9be9-4ab9-6813-27a9-a39c55f111fa
* Version Independent ID: 0bc1f464-486d-5a11-182f-bd439f778547
* Content: [Get directoryObject - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/directoryobject-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/directoryobject-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/directoryobject-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @keylimesoda
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by keylimesoda** [comment]
Can you share your failing request?

[Microsoft.graph.application resource type inherits from directoryObject](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0) so I'd also expect it should be accessible through this API.

For example:  https://graph.microsoft.com/v1.0/directoryObjects/acc848e9-e8ec-4feb-a521-8d58b5482e09

**Comment by michevnew** [comment]
Thanks Rick, I think it's just my expectations here. I was parsing the results of /identity/conditionalAccess/policies and wanted to have a quick way to replace all GUIDs with more suitable identifiers. Which worked great for users/groups/roles, but failed me on applications. Now, this seems to stem from the fact that the output returns the "global" appId instead of the tenant-specific one, for example in the case of Exchange Online it will return 00000002-0000-0ff1-ce00-000000000000 instead of the id of the corresponding service principal in my directory. And /getById s or /directoryObjects doesnt resolve that.

**Comment by keylimesoda** [comment]
I'm looking at the policies object here.  When you say appID, do you mean the "alternativeIdentifies" String in the policy return object?  

https://docs.microsoft.com/en-us/graph/api/resources/policy?view=graph-rest-beta

**Comment by michevnew** [comment]
Here's a more specific example. Take any tenant that has Exchange Online provisioned. If you get the service principal corresponding to the Exchange online app, you will see something like this:

```
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#servicePrincipals/$entity",
    "id": "f5c70b13-9271-48f0-82cf-e6b2ca7c98a1",
    "appDisplayName": "Office 365 Exchange Online",
    "appId": "00000002-0000-0ff1-ce00-000000000000",
    "displayName": "Office 365 Exchange Online",

```

Now, if you run a /directoryObjects or /getById query against the "Id" value above, you will get a proper result. If you run it against the "appId" value, you will get nothing. And that's OK I suppose.

The problem is that the output of CA policy objects that has such applications within its properties returns the AppId, not the Id. In other words, I see this:

```        {
            "conditions": {
                "applications": {
                    "includeApplications": [
                        "00000002-0000-0ff1-ce00-000000000000"
                    ],
                    "excludeApplications": [],
                    "includeUserActions": []
                },
...
```
and when I try to "resolve" the above GUID via /directoryObjects or /getById, I get nothing. 

I suppose I should've opened the issue under the conditionalAccessPolicy article, but it might be best if /directoryObjects could resolve against such "additional" properties as well.

**Comment by keylimesoda** [comment]
Thank you for the updated example.

I think there’s some digging to do, but at first blush it makes sense that
if you’re calling the policy object and we ostensibly have options for
which application ID to show, that we can choose to give you an app ID
local to the tenant so you can perform policy operations against it.

I’ll track down to see if there’s other intent/scenarios I’m overlooking
here as well as the technical feasibility of such a change.


  Ric Lewis
  Microsoft

**Comment by davidmu1** [comment]
Ric is looking into the issue and it appears that there is no immediate change to the page. Please ask questions at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) if there is still an issue. This page will be updated as information becomes available. Closing the issue for now.
