### ISSUE TITLE
!= 200

### ISSUE THREAD

**Issue by vkorichkov-qb** [microsoftgraph/microsoft-graph-docs#8149]
[Enter feedback here]
What about the other cases (!= 200)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f276ed76-e7ad-6fca-5d10-64d88960fd77
* Version Independent ID: 33e996a2-c6a9-631a-56eb-7d7da548d2ef
* Content: [Update subscription - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&tabs=http#http-request)
* Content Source: [api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/subscription-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @vkorichkov-qb 
Thanks for your feedback! I authored PR #8232 to add links to the errors documentation.
This issue will be closed automatically once the pull request is merge.
