### ISSUE TITLE
The following fields now seems to be available in v1.0 but are not documented here, only in the beta documentation

### ISSUE THREAD

**Issue by patrikhellgren** [microsoftgraph/microsoft-graph-docs#8157]
These fields come back when using Graph Explorer to query the v1.0 endpoint but are not documented for v1.0 only for the beta endpoint:
onPremisesDomainName
onPremisesNetBiosName
onPremisesSamAccountName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6b4ebd-685c-0854-6793-2f900cadc554
* Version Independent ID: 953200ad-c9af-a80d-7bc2-836a25ddc273
* Content: [group resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/group.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
Thank you @patrikhellgren for spotting the discrepancies. I have updated the documentation and added those properties. Thanks!!
