### ISSUE TITLE
What is the value provided in "resourceUrl"

### ISSUE THREAD

**Issue by djain1109** [microsoftgraph/microsoft-graph-docs#8161]
In the resourceURL I could see a value "57DAB8B1894C409AB240BD8BEAE78896", is it some unique ID or thumbprint of the Certificate installed on Bot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f082149-fba4-1790-2d28-bd25bd59beff
* Version Independent ID: 278bb27a-237e-52a2-8a87-0dfdc0a098fe
* Content: [call: answer - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/call-answer?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/call-answer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/call-answer.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
That is the ID associated with the call
