### ISSUE TITLE
Can't enable an event as an online meeting in c#

### ISSUE THREAD

**Issue by dkopic1996** [microsoftgraph/microsoft-graph-docs#8164]
When I try to set `isOnlineMeeting` I get a message: Event does not contain a definition for `isOnlineMeeting`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=csharp&source=docs#feedback)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Could not reproduce the issue.

Please check the online meeting provider on calendar resource type has value set:
https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

**Comment by Harini84** [comment]
Kindly check if SDK has been updated to support GA of onlineMeeting API

**Comment by darrelmiller** [comment]
It is available now https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/0cb6ca9fed938cad19fafd26d7d52d5722ddd3aa/src/Microsoft.Graph/Models/Generated/Event.cs#L241
