### ISSUE TITLE
Graph insights: "Folder" type filtering doesnt work

### ISSUE THREAD

**Issue by holylander** [microsoftgraph/microsoft-graph-docs#8168]
Hi there,
I have found that when using the graph api endpoint
`https://graph.microsoft.com/v1.0/me/insights/used`

filtering by `?$filter=ResourceVisualization/Type eq 'Folder'`will always return zero results. It looks like this filter parameter doesnt work.

**Url example:**
`https://graph.microsoft.com/v1.0/me/insights/used?$filter=ResourceVisualization/Type eq 'Folder'`
always returns
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('48d31887-5fad-4d73-a9f5-3c356e68a038')/insights/used",
    "value": []
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98cb3a8b-f51d-a88f-bd92-311b6b0e6816
* Version Independent ID: 77a6dd64-3154-43c5-9606-0431fee00993
* Content: [resourceVisualization resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/insights-resourcevisualization?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/insights-resourcevisualization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/insights-resourcevisualization.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by simonhult** [comment]
Even though the API shape supports Folder entities, we are not yet capturing a rich set of signals for folder-activities. We have also not landed any semantics for how file-activity could/should aggregate up to folder-level. There could still be folders showing up from create-signals, but this will indeed mostly be empty for now.

**Comment by holylander** [comment]
Thats fine Simon, thanks for the quick reply :) I opened the bug 'cause the "type" folder was listed as available, but never returned any result :(. I guess its all about time that endpoint will start to return data.

off topic question:

Are you aware of any way to retrieve [recently visited/used ](https://docs.microsoft.com/en-us/graph/api/insights-list-used?view=graph-rest-1.0&tabs=http) `documentSet`?. There is no way to retrieve such thing with the listed `resourceVisualization\type(s)`, that is why I was trying the `folder` type.

Thanks in advance.

**Comment by simonhult** [comment]
Same challenge, unfortunately; we are not aggregating per-item activity to its container(s). It is straight forward to implement, but the expected cost of running this at scale would require a very strong use-case to justify it.

**Comment by holylander** [comment]
I understand. Thanks for the answer anyway ;).

The workaround I have placed for showing the recently visited folders is to retrieve the 100 latest accessed files, and then retrieve the unique folders url based on those files URL. Its not 100% accurate since it wont include certain folders, but at least you get some info...
