### ISSUE TITLE
misleading JSON representation

### ISSUE THREAD

**Issue by chrisspre** [microsoftgraph/microsoft-graph-docs#8169]
Since managedAppPolicy is an abstract base type, the presented JSON will never be seen in any request/response. This section should be removed. It woudl be better to enumerate the concrete subtypes (e.g.  windowsInformationProtection )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1274d60b-11b5-b0ee-4fc7-986d219d944e
* Version Independent ID: fb27cb16-4f96-d014-7616-eaa347629012
* Content: [managedAppPolicy resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-mam-managedapppolicy?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/intune-mam-managedapppolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-mam-managedapppolicy.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks, I've asked the team to update this resource documentation.
