### ISSUE TITLE
Link to the IP ranges used by change notifications

### ISSUE THREAD

**Issue by joereese** [microsoftgraph/microsoft-graph-docs#8170]
I spent many hours trying to track down the IP ranges used by Change Notifactions as we didn't want to open every Azure IP range as inbound connections.  After much heartburn we stumbled upon the correct IP addreses in this article...

https://docs.microsoft.com/en-us/office365/enterprise/additional-office365-ip-addresses-and-urls

To save others the same trouble we had it would be ideal to include a link to this information on this page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc1ec710-fff6-0690-7eb3-16b9773145ef
* Version Independent ID: c4a14ee1-f979-8409-4481-45272b35d965
* Content: [Set up notifications for changes in user data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks#feedback)
* Content Source: [concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
@joereese thank you for pointing this out. I published the IP addresses over the page you're pointing to a few weeks ago but forgot to link it here.
I just authored a pull request to fix that https://github.com/microsoftgraph/microsoft-graph-docs/pull/8171
