### ISSUE TITLE
Different Id formats for Resources

### ISSUE THREAD

**Issue by dzmitryrozberh** [microsoftgraph/microsoft-graph-docs#8175]
I can see a different formats of Ids for all resources:
for example 'c4d04b8f-6a2d-4aec-87e9-bb2357701576' and '9bcb2ae6d8754e9d8f77e0296ca7e824'
It is not convenient to store such different formats in database

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baff198b-501f-c97d-005d-36875302640d
* Version Independent ID: 413b2545-44cc-1f43-3feb-2c4deab9472e
* Content: [Working with the call records API in Microsoft Graph - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/callrecords-api-overview.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
The ID format varies depending on whether the call was SfB or Teams. Generally Teams calls should have a proper guid. All I can recommend is treating the id as a string, and if the length goes higher than 100 characters, it should be safe to truncate for the purpose of storage in a database.
