### ISSUE TITLE
Pre-Consent Not Working

### ISSUE THREAD

**Issue by TheITRx** [microsoftgraph/microsoft-graph-docs#8176]
I went through this documentation. Made sure that my new service principal is added to to Adminagents group in my partner organization. 
However when I send an auth code request to https://login.microsoftonline.com/{Tenant-ID}/oauth2/authorize
I get this prompt: https://monosnap.com/file/b9Mg6yk7zMLW1csKhFYFiMXoYDTZju

These are my parameters. 
&client_id={Client-ID}
&response_type=code
&redirect_uri=http://localhost
&response_mode=query
&resource=https://graph.microsoft.com
&state=12345
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 901ad71a-7fa8-cb4a-ffe4-396d6b52ccf9
* Version Independent ID: 903c43d0-41d3-99cf-c289-644e64c9b801
* Content: [Call Microsoft Graph from a Cloud Solution Provider application - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-cloudsolutionprovider)
* Content Source: [concepts/auth-cloudsolutionprovider.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-cloudsolutionprovider.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @TheITRx for raising your issue and my apologies for the delayed response. This should be resolved by adding the **Directory.AccessAsUser.All** permission to the app in question.

Closing this issue.
