### ISSUE TITLE
Update user profile for certain parameters like skills, interests works with User.Read permission

### ISSUE THREAD

**Issue by abbodh** [microsoftgraph/microsoft-graph-docs#8177]
It seems that with delegated permission of User.Read only and trying to update user profile properties like skills, interests, schools or aboutMe, the Patch operation gets succeeded. However, other properties cannot be updated due to permission issue (which obviously ask for User.ReadWrite). This looks like a bug or maybe done intentionally! 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5508367-0081-0d0c-5047-3b3201208de4
* Version Independent ID: b99127ca-af8c-cfc8-074c-8699241984c5
* Content: [Update user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-update.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
Yes, it would be a bug if you only have User.Read permissions and you are able to update the user profile. We will investigate. Thanks for pointing this out. No doc updates needed. Closing the issue.
