### ISSUE TITLE
I am Getting Response code as 202

### ISSUE THREAD

**Issue by vinitmalhotra** [microsoftgraph/microsoft-graph-docs#8181]
Hi Team,

We are not getting 200 but 202 for this call. Is it supposed to be 200 or 202?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e9e268-2c85-f2fc-1591-d4397e2b84d7
* Version Independent ID: 3ed61e85-b00c-4791-b734-cef12052374c
* Content: [event: dismissReminder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-dismissreminder?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/event-dismissreminder.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-dismissreminder.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Tariq-Sharif** [comment]
Hi, are you still seeing code 202 getting returned for your scenario, or was that a transient issue?

**Comment by vinitmalhotra** [comment]
Still same
