### ISSUE TITLE
Add link to credential reports

### ISSUE THREAD

**Issue by MrAzureAD** [microsoftgraph/microsoft-graph-docs#8182]
Many options to query the user's information regarding enabled MFA methods are missing here. Fortunately, they are just somewhere else (e.g. /reports/credentialUserRegistrationDetails)
I would recommend add a cross-reference link to the /reports node here to help users find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2131c0c0-b5c1-61fa-98cf-5af744c9f72d
* Version Independent ID: 77be448b-3d8b-9b50-7941-c6218942b6ce
* Content: [Azure AD authentication methods API overview - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/authenticationmethods-overview.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hello @MrAzureAD ,

Thank you for your feedback. The design of the docs is for each node to focus on one topic. In this case, the node exposes the API methods for managing various authentication methods supported on AAD. This serves a different purpose from the Reports node which is all about audit logs and reports.

No updates identified for the page but the page will be updated when possible. Closing the issue for now.
