### ISSUE TITLE
`webUrl` doesn't work for private channels

### ISSUE THREAD

**Issue by RoelVB** [microsoftgraph/microsoft-graph-docs#8185]
When visiting the `webUrl` of a private channel we get a blank page with the text:
`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable`

I don't know if this ever worked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a639b2c-1646-2fb0-df4b-672717ecef06
* Version Independent ID: 4a5cc49a-ee65-02a5-583b-acfb0993a25f
* Content: [Get channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mattdenkers** [comment]
I'm getting the same error for non-private channels.
