### ISSUE TITLE
Retrieve Meeting Online Result from Event Generated

### ISSUE THREAD

**Issue by eichev** [microsoftgraph/microsoft-graph-docs#8190]
How to retrieve meeting online result from the Event Generated (isMeetingOnline=true), so we can know actual starttime and endtime from the meeting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53257c69-9ebe-7fd1-b55e-1612b62b9be0
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/event.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
In me/events or /me/calendars/{id}/events/{id} please include start, end, onlineMeeting in $select to retrieve the values corresponding to an online meeting event:

https://graph.microsoft.com/v1.0/me/events?$select=subject,body,bodyPreview,organizer,attendees,start,end,location,onlineMeeting
