### ISSUE TITLE
Get notification when PSTN(configured through direct routing) makes call to Teams user to apply custom business logic

### ISSUE THREAD

**Issue by bijaykush** [microsoftgraph/microsoft-graph-docs#8191]
Hi @stephenjust

I am in a situation to get the call notification might be through web hook when a call comes from PSTN/Teams user to another Teams user, so that I can write some business logic to send that incoming callerID to the external application. I know if the Bot receives the call we can get the call back but in this case it is only MS Teams user and PSTN number, doesn't include bot.

Could you please help with some possible way or workaround, I could achieve that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baff198b-501f-c97d-005d-36875302640d
* Version Independent ID: 413b2545-44cc-1f43-3feb-2c4deab9472e
* Content: [Working with the call records API in Microsoft Graph - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/callrecords-api-overview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/callrecords-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/callrecords-api-overview.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
It sounds like you would need a notification when the call is initiated for this scenario? The Call Records API only provides data and the end of a call. I'm not aware of any APIs that provide a real-time hook into all calling activity within an organization. I'd recommend suggesting a feature on UserVoice so the request can be more officially tracked.
