### ISSUE TITLE
completedDateTime and timezone

### ISSUE THREAD

**Issue by tipa** [microsoftgraph/microsoft-graph-docs#8192]
The description of completedDateTime states that it refers to the timezone specified. However it appears that the returned date value is always UTC midnight. I created and completed a test todo with the Microsoft To Do app today on May 13th with my device set to Standard Mountain Time. When I list the todos and specify the header outlook.timezone="America/Denver", it returns "2020-05-12T18:00:00" as completedDateTime - which is not correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 269af1ad-db75-2d9d-fb59-5c834dee2863
* Version Independent ID: e21cb190-f4b6-2cb6-68d4-17cd8769b1ba
* Content: [outlookTask resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/outlooktask?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/outlooktask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/outlooktask.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @mashriv
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mashriv** [comment]
Apologies for delay in response. Thanks for reporting this. This is  known behaviour and currently we are discussing this on how to handle this.

**Comment by tipa** [comment]
Thanks for the response @mashriv. Has there been any updates regarding this issue in the meantime?

**Comment by tipa** [comment]
This bug is also still present when using the new endpoint for to-dos: https://docs.microsoft.com/de-de/graph/api/resources/todo-overview?view=graph-rest-beta

**Comment by tipa** [comment]
@mashriv any updates?

**Comment by mashriv** [comment]
@tipa , this was in our backlog but unfortunately we couldn't pick it up earlier. We have picked up now. We are hoping to have an update for you in a months time

**Comment by tipa** [comment]
@mashriv has there been an update in the meantime?

**Comment by tipa** [comment]
The bug/question has now been posted here: https://docs.microsoft.com/en-us/answers/questions/567068/to-do-completeddatetime-and-timezone.html
@mashriv I would highly appreciate a short comment on the current state of this issue. Is this still planned to be fixed?
