### ISSUE TITLE
sortOrderIndex does not appear to work

### ISSUE THREAD

**Issue by ewillman** [microsoftgraph/microsoft-graph-docs#8193]
Regardless of the value passed for sortOrderIndex to create or update the value always remains "10100"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc47abfd-91ac-aa56-4b87-19a0ce6be9aa
* Version Independent ID: 2f5f6c0c-3ea6-a43b-b9da-cbc0c2353a90
* Content: [Update tab - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/teamstab-update?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/teamstab-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/teamstab-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
@ewillman - I tried to repro this but could not able to see sortOrderIndex itself in API response while creating or getting Tab response data.

I referred below API documentation:
https://docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0

However sortOrderIndex is mentioned in documentation, so I have raised a bug for it.
https://github.com/microsoftgraph/microsoft-graph-docs/issues/13988
