### ISSUE TITLE
Guest participants have null values

### ISSUE THREAD

**Issue by ShaneOss** [microsoftgraph/microsoft-graph-docs#8196]
Guest participants that join meetings and specify a displayName to join a meeting, it's not shown in the details from a callRecord. It only shows null for displayName and guest. I'd expect guest to be true and the displayName to be the display name specified by the guest user when they joined the meeting.

E.g.
"participants": [
		{
			"phone": null,
			"guest": null,
			"encrypted": null,
			"onPremises": null,
			"azureApplicationInstance": null,
			"applicationInstance": null,
			"application": null,
			"device": null,
			"user": {
				"id": "teamsvisitor:94a5933c63764bed8ce6e7ee004f9d8b",
				"displayName": null,
				"tenantId": null
			}
		}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6259f0-9e69-493b-3158-614d11642312
* Version Independent ID: 08963ed9-21ee-773d-3532-75be9cd57e70
* Content: [Get callRecord - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/callrecords-callrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/callrecords-callrecord-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
We do not have access to the display name of guest participants

**Comment by ShaneOss** [comment]
But the data is captured when guests join. Considering they're a participant of a meeting/call created within our tenant I'm surprised that we wouldn't have access to it. Although I'm told that Microsoft can't provide an IP address of a guest user who sent a message through Teams either. The message can be found via Content Search/eDiscovery but no IP address. It does show the displayName of the guest though.
For legal reasons the information may be required. As in our case with underage students and inappropriate content within a meeting. Is there any other way? Premier support also tried but in the end just advised it wasn't possible.

**Comment by stephenjust** [comment]
That's interesting. I'll bring that up with our team.

Getting the guest display name included would help with a lot of scenarios, and it is something we had already been looking in to.

**Comment by stephenjust** [comment]
Guest user should now show up in the correct place on the IdentitySet. We do not yet have the display name, but we are continuing with our investigation internally.
