### ISSUE TITLE
CreatedeviceAppManagementTask not working

### ISSUE THREAD

**Issue by tabs-not-spaces** [microsoftgraph/microsoft-graph-docs#8201]
#### Issue 
When trying to create AppManagementTask using examples on docs I get the following error:

#### Request
```
POST https://graph.microsoft.com/beta/deviceAppManagement/deviceAppManagementTasks HTTP/1.1
Authorization: Bearer ***
Content-Type: Application/Json

{
  "@odata.type": "#microsoft.graph.deviceAppManagementTask",
  "displayName": "Example app management task",
  "description": "Example description task",
  "dueDateTime": "2021-01-01T00:02:18.1994089-08:00",
  "category": "unknown",
  "priority": "high",
  "creator": "user@megacorp.com",
  "creatorNotes": "Notes would go here",
  "assignedTo": "support@megacorp.com",
  "status": "pending"
}
```
#### Response

Response Code: 400 (Bad Request)
```
{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation with http verb POST for request /PartnerIntegrations/TicketingFEService/deviceAppManagement/deviceAppManagementTasks.",
        "innerError": {
            "request-id": "c992e87a-9da6-41ff-a953-eef304e76178",
            "date": "2020-05-14T04:52:31"
        }
    }
}
```

It's quite obvious that either POST / PATCH / PUT routes are either not enabled for this endpoint OR the creation process is incorrectly documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc763a1-a229-ff9a-a2be-811edaf2a8ef
* Version Independent ID: 302ba46e-4cab-f9c0-86fc-6c8f42177a12
* Content: [Create deviceAppManagementTask - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-partnerintegration-deviceappmanagementtask-create?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-partnerintegration-deviceappmanagementtask-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-partnerintegration-deviceappmanagementtask-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Correct, there is no code that supports this route.  This sometimes occurs based on how our documentation is generated.  I'll file a bug so it can eventually be cleaned out.  The best method to validate an entity creation is by doing F12 developer tools in the browser and seeing the actual calls being made to create an object.
