### ISSUE TITLE
$filter and createdDateTime can't properly select range

### ISSUE THREAD

**Issue by Shuna322** [microsoftgraph/microsoft-graph-docs#8203]
Selecting time range for alerts with $filter and createdDateTime field causes to select all alerts.

Request example:
'https://graph.microsoft.com/v1.0/security/alerts?$filter= createdDateTime gt 2020-05-14T07:09:43Z and createdDateTime lt 2020-05-14T07:24:43Z'

Receiving logs with way different time range
['2020-04-15T07:38:02.947Z', '2020-04-15T07:38:03.273Z', '2020-04-15T07:38:06.837Z', '2020-04-15T08:21:48.293Z', '2020-04-15T08:21:48.76Z', '2020-04-15T11:29:27.907Z', '2020-04-15T20:50:03.013Z', '2020-04-16T01:05:13.843Z', '2020-04-19T01:55:37.197Z', '2020-04-21T02:10:28.86Z', '2020-04-21T08:27:04.383Z', '2020-04-21T10:22:03.13Z', '2020-04-21T10:45:46.29Z', '2020-04-21T12:31:37.997Z', '2020-04-22T02:26:02.353Z', '2020-04-23T05:32:00.803Z', '2020-04-23T12:47:03.743Z', '2020-04-23T19:37:01.557Z', '2020-04-24T06:13:00.967Z', '2020-04-24T07:41:11.953Z', '2020-04-28T07:17:24.393Z', '2020-04-28T16:19:02.447Z', '2020-04-29T16:47:03.5Z', '2020-04-30T06:01:01.743Z', '2020-05-02T12:44:14.423Z', '2020-05-02T15:06:29.06Z', '2020-05-02T16:29:04.093Z', '2020-05-02T18:35:02.523Z', '2020-05-02T20:07:41.383Z', '2020-05-03T00:14:17.423Z', '2020-05-03T01:42:36.21Z', '2020-05-03T03:15:09.503Z', '2020-05-03T09:14:14.36Z', '2020-05-03T11:45:17.683Z', '2020-05-03T14:10:31.803Z', '2020-05-03T15:17:06.99Z', '2020-05-03T16:23:59.907Z', '2020-05-04T14:20:02.383Z', '2020-05-05T14:07:03.66Z', '2020-05-08T08:42:01.42Z', '2020-05-09T21:07:26.157Z', '2020-05-09T21:07:30.07Z', '2020-05-13T00:51:21.693Z', '2020-05-13T00:57:50.06Z', '2020-05-13T10:37:38.663Z', '2020-05-13T13:03:07.743Z', '2020-05-13T14:19:03.643Z', '2020-05-13T14:49:00.84Z', '2020-05-13T14:59:08.253Z', '2020-05-13T21:51:08.933Z']

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122ff9f6-5393-cb46-79d5-dac18a7131a8
* Version Independent ID: 150fb49f-a607-2297-b461-3979433a88c5
* Content: [List alerts - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/alert-list?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/alert-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/alert-list.md)
* Product: **security**
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@Shuna322 Can you please let us know what provider are you querying the alerts from? If it's from Office 365, then we're working with Office 365 team to land this feature. You can follow this [GitHub issue](https://github.com/microsoftgraph/security-api-solutions/issues/23) to keep track of the update on this.

**Comment by Shuna322** [comment]
@chinguyen1 Yep, problem same, I'll keep track on that.
