### ISSUE TITLE
Lookup Apps with application persmission

### ISSUE THREAD

**Issue by RoelVB** [microsoftgraph/microsoft-graph-docs#8206]
Why isn't it possible to access the app catalog with application permissions? (only delegated permissions)

You can add an app to a Team with application permissions, but you need the app ID to do this. Since you cannot access the app catalog you cannot find the app ID needed to add an app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01fcbc4f-ca00-a642-0a8f-6f5a38f452db
* Version Independent ID: 5832e5e8-9bb4-39bf-5ca0-0aff5b1677b7
* Content: [List the published apps from the Microsoft Teams app catalog - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsapp-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamsapp-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamsapp-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment]
@RoelVB This is a fair question. We don't support it at this moment, and we are adding it to our backlog.

**Comment by RoelVB** [comment]
@Gousia-MSFT Why is this closed? According to the documentation an application is still unable to access the app catalog.

**Comment by Subhasish-msft** [comment]
@RoelVB, This feature is added to backlog item with Teams platform team. 

we need to close this github item as there is no pending work from Developer support team. We will be tracking it internally.
