### ISSUE TITLE
Channels (and tabs) created using "https://graph.microsoft.com/beta/teams" API does not reflect in Microsoft "Teams".

### ISSUE THREAD

**Issue by prademi** [microsoftgraph/microsoft-graph-docs#8210]
I am using "https://graph.microsoft.com/beta/teams" API (beta version), to enable teams on group id and also create channels.

It does succeeds, and I can see team got enabled and also channels got created in "Microsoft graph explorer" for that Group Id. But in reality when I go to "Microsoft Teams" only teams gets enabled but channels are still missing.

I waited for more than 24 hours but still channels not reflecting in microsoft teams.

Channels (and tabs) created using "https://graph.microsoft.com/beta/teams" API does not reflect in Microsoft "Teams".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview#feedback)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@prademi , Could you please share the request id for the Graph API call?

**Comment by prademi** [comment]
Below is the "SharePoint Site" detail, where "API was ran" and it executed successfully, verified using "Microsoft graph explorer". Though Channel got created in group and teams, but folder with channel name is still not created in "SharePoint Site" under "Document" library.

**SiteURL**: https://microsoft.sharepoint.com/teams/Stg_SEE-5572, 
**GroupID**:'a42e988e-7ffe-4719-bb7d-408b9e2f135e'
**Document Library**: https://microsoft.sharepoint.com/teams/Stg_SEE-5572/Shared%20Documents/Forms/AllItems.aspx

**Comment by prademi** [comment]
Why ticket has been closed, without providing solution? Open it again.

**Comment by Trinetra-MSFT** [comment]
@prademi , The issue is not repro at our end, However we asked you to provide the request id earlier, but there was no response from your side, Could you please provide the request id now so we can check why it is failing at your end?

**Comment by prademi** [comment]
Please find request ID below.

**request-id**: 00a62ad5-647c-4a73-bba0-74cc51a8b90c
