### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by JasonHough75** [microsoftgraph/microsoft-graph-docs#8213]
Are you sure we only need one permisison in MS Graph to create a schema extension ? No matter which permisisons I add, I get an constant 403 error. Any input please ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27b7b26c-499c-6b30-96cd-04b6ac80fbc0
* Version Independent ID: 2e8b2a6a-961b-40d6-acf0-a096a3aec9a1
* Content: [Create schemaExtension - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-post-schemaextensions?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/schemaextension-post-schemaextensions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/schemaextension-post-schemaextensions.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
If you are trying to create a schema extension through Graph Explorer, then you need to set the `owner` property in the payload.  Please see the description of the owner property in the above topic.  Maybe one improvement might be to have an example of creation with an owner property.  Let me know if this fixes your problem.
