### ISSUE TITLE
contentType is changed in the background after event creation is finished

### ISSUE THREAD

**Issue by casual033** [microsoftgraph/microsoft-graph-docs#8215]
When creating event contentType is set to TEXT, valid response is returned also with the type TEXT, and event is successfully saved.
However, when this event is fetched, immediately after that, the contentType returned is HTML, and the content is wrapped inside auto-generated html. 
Is this a bug or TEXT type is not at all supported for event body ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a80f4aa-dda6-079a-9e61-df611a2a7e99
* Version Independent ID: 77ea5bcc-08af-7d98-b7be-3b4d758857c4
* Content: [itemBody resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/itembody?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/itembody.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/itembody.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @grangeryy
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by pajic-milos** [comment]
Any update on this???

**Comment by grangeryy** [comment]
Doe this issue still happen to you? If so, could you share with us the request/response samples using Excel Graph? That would help to identify the issue more quickly. Thx!

**Comment by grangeryy** [comment]
Close this without further information from customer. Feel free to reopen later.
