### ISSUE TITLE
Not all members returned in Demo tenants

### ISSUE THREAD

**Issue by OskarNet** [microsoftgraph/microsoft-graph-docs#8216]
There is an issue with the Demo tenants now and this endpoint where not all members are returned when querying the initial classes.
For example the Algebra class has three owners but only one of them are returned when calling this endpoint.
If I remove the owner from the class and add to the class again they get returned from the endpoint.  So this seems like an issue with the initial data provided when creating a new demo tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a32b12-951e-ff94-a7b8-c014968ce6cf
* Version Independent ID: fea401c3-ce70-d7ce-4bae-c112308a711a
* Content: [List members - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-list-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-list-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
Could you please submit a support ticket on Azure portal to investigate your issue? Thank you!
