### ISSUE TITLE
Missing ObjectIdentity in Java SDK

### ISSUE THREAD

**Issue by ptaylor** [microsoftgraph/microsoft-graph-docs#8217]
I cannot find the ObjectIdentity class and the associated user.identities in the Java SDK (version 1.7,1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=java#feedback)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
There currently is no API reference documentation for using Java for Azure AD. No change identified to this page. Closing the issue.
