### ISSUE TITLE
Create Group Add Owners and MEmbers

### ISSUE THREAD

**Issue by jason-appliedis** [microsoftgraph/microsoft-graph-docs#8219]
I am trying to add owners and members when I create a group

The example below works
{
  displayName:"testtesttest",
        description:"descriptiondescriptiondescriptiondescriptiondescription",
        groupTypes: [
          "Unified"
        ],
        mailEnabled:true,
        mailNickname:"testmailname",
        securityEnabled:false,
        visibility:'Private',
        "members@odata.bind":https://graph.microsoft.com/v1.0/users/{UPN}, 
        "owners@odata.bind":https://graph.microsoft.com/v1.0/users/{UPN}
}

The Below Example returns the error 
"Unsupported resource type 'DirectoryObject' for operation 'Create'."
{
  displayName:"testtesttest",
        description:"descriptiondescriptiondescriptiondescriptiondescription",
        groupTypes: [
          "Unified"
        ],
        mailEnabled:true,
        mailNickname:"testmailname",
        securityEnabled:false,
        visibility:'Private',
        owners:['{id:"{userId"}']
}
I am trying to send the payload with the use case for someone not explicitly setting members and owners. I know I can accomplish this with subsequent request or build my objects before the payload, but I am trying to shorten the length of code needed. 

According to the Microsoft Graph Type Groups the owners and members are listed as a "DirectoryObject", but when I send the payload it says it is not allowed on a create operation. Is there any documentation that explains this? I am trying to better understand the code I am writing underneath the hood.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f8461db-2e9b-1a9a-e847-6ce3c6287710
* Version Independent ID: ffcc3cbb-6fd3-ee55-644a-1c6382bcd6e5
* Content: [Create group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=javascript#feedback)
* Content Source: [api-reference/v1.0/api/group-post-groups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-groups.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
This might have something to do with odata convention. I'm not sure about the cause. Could you please post your question to stackoverflow? (https://stackoverflow.microsoft.com/) There you should be able to get hold of the right experts. Thank you!
