### ISSUE TITLE
Add a paragraph at the top to explain where to raise known issues

### ISSUE THREAD

**Issue by jthake-msft** [microsoftgraph/microsoft-graph-docs#8220]
We should add some guidance on where to raise known issues and direct to the support page https://docs.microsoft.com/en-us/graph/known-issues#feedback. As we are getting more and more issues raised directly on this page that are not content feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac7ca25a-037d-5202-debc-92c06a2c8480
* Version Independent ID: 8ebb4dbc-76a1-00fd-e740-87eda29a40f0
* Content: [Known issues with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/known-issues#feedback)
* Content Source: [concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/known-issues.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Lauragra** [comment]
I updated the Known issues topic to include a link to the Support page, which explains how to report an issue.
