### ISSUE TITLE
"/users/{email}/drive/sharedWithMe" API doesn't returns files shared by people outside of my domain

### ISSUE THREAD

**Issue by ganga-sah** [microsoftgraph/microsoft-graph-docs#8222]
"/users/{email}/drive/sharedWithMe" API is returning only files that are shared by people from my own domain but it's missing files that are shared by people outside of my domain. I can see the missing files under Shared-&gt;"Shared With Me" section in my OneDrive. How can I list files shared by people outside of my domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9ff916-e1b7-c60b-bf05-2c5976617ad7
* Version Independent ID: 092666d9-dfd3-44f9-9571-bc67f45c4842
* Content: [List Files Shared With Me - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/drive-sharedwithme.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/drive-sharedwithme.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by ganga-sah** [comment]
@JeremyKelley @nextalias @wobba @vboctor @wdkbot I am still waiting for help on this.
I got some hint from another related issue https://github.com/microsoftgraph/microsoft-graph-docs/issues/8598.
This suggests to suffix "allowexternal=true" as query parameter in REST URL to make the requests returns external shares (across domains shares) , which is what I wanted. Unfortunately this also doesn't return external sharings even if I can see them in OneDrive UI. Please help as I am totally blocked on this.

**Comment by wobba** [comment]
Made a proposal for doc edit.

**Comment by lramosvea** [comment]
Closing as the proposal from Mikael has been merged already. Please feel free to reopen if you are still facing this issue. Thanks.
