### ISSUE TITLE
Remove Participant

### ISSUE THREAD

**Issue by damienestewart** [microsoftgraph/microsoft-graph-docs#8224]
Are there any endpoints for removing participants from calls? Or admitting specific participants from the lobby?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79494120-ed26-7e0c-3de0-36fd2ead869e
* Version Independent ID: 308bfb41-c1a4-98b5-ba6f-1339878488a6
* Content: [participant resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/participant?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/participant.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/participant.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @damienestewart we currently don't have an API that allows you to remove a participant from a call.

For admitting certain participants from a lobby, see the autoAdmittedUsers property type from the [beta online meetings resource type](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta#properties).
