### ISSUE TITLE
Needed Permissions

### ISSUE THREAD

**Issue by TechKumar1981** [microsoftgraph/microsoft-graph-docs#8226]
What kind of permission needed to call this API ? Will that work on Personal Microsoft Account ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba38271d-4038-ac43-fb9d-c2cd172d138d
* Version Independent ID: c83604a3-b769-19d4-fee1-9f3090e8f3cc
* Content: [teamsAsyncOperation resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/teamsasyncoperation?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/teamsasyncoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/teamsasyncoperation.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by TechKumar1981** [comment]
Any updates on permissions needed for  teamsAsyncOperation ?

**Comment by Gousia-MSFT** [comment]
Please re-open if you still have a query here.
