### ISSUE TITLE
Add a note for maximum length of channel displayName

### ISSUE THREAD

**Issue by mpaukkon** [microsoftgraph/microsoft-graph-docs#8227]
Add a note to documentation about maximum length of channel displayName.
When length exceeds 50 on Graph API call, it will fail.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c06a8a7a-b0fa-8304-84f5-9ada3b3c2ea5
* Version Independent ID: 2c33f569-87dd-68be-2048-770788eae940
* Content: [Create Channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by sayali-MSFT** [comment]
@AkJo - Could you please help us to update the document?

**Comment by lramosvea** [comment]
Closing as this issue seems to be fixed
