### ISSUE TITLE
CreationOptions

### ISSUE THREAD

**Issue by prashant1380** [microsoftgraph/microsoft-graph-docs#8228]
The response received from beta api does not contain "creationOptions" but v1.0 provides. Is there any reason for that? We need to use beta api due to some reason, but then "creationOptions" is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a73e08e0-aa5c-dde2-6e05-240052049a67
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@prashant1380 "creationOptions" is to be deprecated and resourceBehaviorOptions and resourceProvisioningOptions will be used instead, which are available in beta. Can those two properties meet your needs?

**Comment by prashant1380** [comment]
resourceProvisioningOptions contains value only when group is provisioned/connected with Teams. What about other resources for e.g. Yammer, SPO etc.? How can we check which method is used to provision the group?

**Comment by data-model** [comment]
Yes, please let us know if the provisioning options will include Yammer. Some tenants contain 'YammerProvisioning' in the resourceBehaviorOptions, but not all.

**Comment by yyuank** [comment]
Our plan is to have Yammer to use resourceProvisioningOptions. We won't retire creationOptions until the existing properties are migrated to resourceProvisioningOptions or resourceBahaviorOptions. Since creationOptions is on the deprecation path, we don't have any plans to enable it on beta. Enabling it on V1 was not intentional.

**Comment by data-model** [comment]
Great news. Do you have a timeline by any chance? When will 'yammer' start showing up in resourceProvisioningOptions?

**Comment by yyuank** [comment]
Unfortunately I don't have a timeline. It depends on Yammer team. If you'd like to help stress the importance of this ask, you could go to Yammer user voice https://yammer.uservoice.com/ and ask for this support. Thank you for your help!
