### ISSUE TITLE
Avoid the confusion between 'subscriptions to change notifications' and 'notifications'

### ISSUE THREAD

**Issue by Josverl** [microsoftgraph/microsoft-graph-docs#8231]
please add a clarification the clearly distinguish between 

- *subscriptions* to change notification (applications)   `/subscriptions`
- human notification `/me/notifications/`

as the articles for 'change notification' often simply state 'notification' there is a risk for confusion with the newly introduced ['Microsoft Graph notifications' API](https://docs.microsoft.com/en-us/graph/notifications-concept-overview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/webhooks.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Thanks @Josverl ! I authored a pull request #8234 to align terminology across all articles so it makes it easier for readers to differentiate. This issue will be closed once the PR is merged.
