### ISSUE TITLE
What is "replacesCallId"

### ISSUE THREAD

**Issue by djain1109** [microsoftgraph/microsoft-graph-docs#8233]
Is this a callid for next call i.e. after transfer ? if yes then how can I know before what would be future call id.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 335dc162-8c2e-49dc-4419-9ef736ec8ba4
* Version Independent ID: b441332e-a653-e538-d9f0-c66739f9122a
* Content: [call: transfer - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/call-transfer.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ananmishr** [comment]
Hi @djain1109, it's a property type on the [invitationParticipantInfo](https://docs.microsoft.com/en-us/graph/api/resources/invitationparticipantinfo?view=graph-rest-1.0#properties) resource type 

When a participant is added to a group call, it's the call that they are currently a part of.
