### ISSUE TITLE
Bad request using Adaptive cards

### ISSUE THREAD

**Issue by michaelstiben** [microsoftgraph/microsoft-graph-docs#8235]
Hi,

I have tried sending the sample thumbnail card of above and everything goes well. However, I tried to send an Adaptive card (that I already test in the Card Designer) and get as a result the Bad request status with message: "Invalid request body was sent." Even I tried with this sample of adaptive card thinking that it was my mistake, but neither works https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card

Thanks for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Can you share the body you sent? Remember the cards json body has to be serialized before it can be sent.

**Comment by sandhi23** [comment]
I am getting below error with all the samples from https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference

{
    "error": {
        "code": "BadRequest",
        "message": "Value cannot be null.\r\nParameter name: Content",
        "innerError": {
            "request-id": "d9fa1faf-f741-45ca-9019-9c62def7fdd6",
            "date": "2020-05-18T04:56:13"
        }
    }
}

I am using the graph explorer.  Thanks in advance.

**Comment by RamjotSingh** [comment]
Can you share the payload you are sending?

**Comment by RamjotSingh** [comment]
Closing this issue, please reopen if you need assistance.
