### ISSUE TITLE
Incorrect size of photo that you can add

### ISSUE THREAD

**Issue by twentytwokhz** [microsoftgraph/microsoft-graph-docs#8236]
Doing a PUT request with a file over 100KB will return a really weird 404 Not found error - which is really hard to figure out.
The idea is that if the file that is uploaded exceeds the 100KB mark it will not be uploaded and 404 will be returned.
Please update the docs to reflect this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83dd5407-0add-ef2f-0fac-e05ac0a65ff1
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilephoto - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/profilephoto-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by twentytwokhz** [comment]
*PUT /me/photo/$value

**Comment by kevinbellinger** [comment]
It would help to have the error so we can understand a bit better what you mean by weird error.

Given the parameters given in the original message, I suspect this is a user who exists only in AAD and does not have an Exchange Online mailbox? If so the limitation comes from AAD in this instance where the max size which can be uploaded is 100k.

**Comment by twentytwokhz** [comment]
@kevinbellinger It returns a 404 error saying the following:
`{
  "error": {
    "code": "MailboxNotEnabledForRESTAPI",
    "message": "REST API is not yet supported for this mailbox.",
    "innerError": {
      "request-id": "5663f4b8-9068-4cba-a5cc-3ebaa7c3eaee",
      "date": "2020-06-02T06:56:29"
    }
  }
}`

**Comment by twentytwokhz** [comment]
> It would help to have the error so we can understand a bit better what you mean by weird error.
> 
> Given the parameters given in the original message, I suspect this is a user who exists only in AAD and does not have an Exchange Online mailbox? If so the limitation comes from AAD in this instance where the max size which can be uploaded is 100k.

Exactly, the user exists only in AAD. But still, the error message is kind of misleading

**Comment by PeterChencha** [comment]
Hello @twentytwokhz thanks for reaching out.  We'll be looking into making the error message more clearer.
