### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by zeitler** [microsoftgraph/microsoft-graph-docs#8237]
Hi

Always getting  400: BadRequest - 'odata.type' must be specified in the request body.

After add "@odata.type": "#microsoft.graph.aadUserConversationMember" in request body worked...
Kind of...
I'm getting 400: BadRequest - Invalid id 'aa7cb3c0-5723-4a66-bae0-d9c1e1d869d2' provided.
It's a recurrent problem I'm facing in other api calls. Probably it's me who's missing something...
The request patch url goes like this:
https://graph.microsoft.com/beta/teams/a8cdb898-3fa6-4e04-86eb-3624d838a750/channels/19:607353a5c58d497683ec0f28e37583aa@thread.tacv2/members/aa7cb3c0-5723-4a66-bae0-d9c1e1d869d2

aa7*d2 is an existing user in group. Any ideas? 
Tks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a47e97e-d09d-5dad-0910-12f39179d4d9
* Version Independent ID: 1942e3bc-5e68-dd17-0596-bd7dad26e8dd
* Content: [Update conversationMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-update?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/conversationmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
@zeitler , On channels, this operation is only supported on channels with a channelMembershipType of private. Calls with any other channelMembershipType will return a 400 Bad Request response.
