### ISSUE TITLE
Teams Beta API - isBroadcast ready to use?

### ISSUE THREAD

**Issue by maheshkommanuru** [microsoftgraph/microsoft-graph-docs#8238]
We are looking to build a custom ui that lets users create Live meetings and choose different access levels for participants. We are exploring the IsBroadcast property referred here - https://developer.microsoft.com/en-us/graph/blogs/breaking-changes-calls-and-online-meetings-api-updates-in-microsoft-graph-beta-2/
When we use 'isBraodcast' along with 'accesslevel' set to "Beta.AccessLevel.Everyone", the live meeting gets created but sets the access level to "sameEnterprise". Anyone else noticed this issue? Appreciate any pointers or guidance on this...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VenkateshKadiri66** [comment]
@maheshkommanuru Have you been able to create a Broadcast meeting (Live Event) with application permissions. I could create it with delegated permissions but not app permissions. So curious to know if you tried app permissions

**Comment by maheshkommanuru** [comment]
We used both Venkat, i haven't tried with just application permissions.
![image](https://user-images.githubusercontent.com/58006891/83277235-bf534980-a19f-11ea-970e-f6e39c44f2a1.png)

**Comment by tonyleone1964** [comment]
> @maheshkommanuru Have you been able to create a Broadcast meeting (Live Event) with application permissions. I could create it with delegated permissions but not app permissions. So curious to know if you tried app permissions


Have you tried the beta version?
