### ISSUE TITLE
Image formats?

### ISSUE THREAD

**Issue by miericsson** [microsoftgraph/microsoft-graph-docs#8239]
Cannot find any information in the documentation about which image formats you can use for profile photos. {png, gif, tiff, tif, jpg, jpeg, and so on ...}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d517bc8-e757-3822-848a-bf6b65d456b5
* Version Independent ID: ed8cafa6-65b9-fe58-57b3-3d57676fae46
* Content: [Update profilephoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http#feedback)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@kevinbellinger  what formats are supported? @miericsson  raises a good point here. Is it just JPEG?

**Comment by kevinbellinger** [comment]
It states in the Content-Type that image/jpeg is required. That is the only format currently supported.

I'll see if we can get someone to add a note elsewhere to make it clearer what is supported.
