### ISSUE TITLE
Intune Service Limits

### ISSUE THREAD

**Issue by PJMarcum** [microsoftgraph/microsoft-graph-docs#8249]
Are the api call limits for Intune documented? I can't seem to find those. If they are documented where are they found?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a36b8419-5890-1e7c-f748-9f71cad21fbf
* Version Independent ID: e6194e1e-a9ca-6acb-1f46-0e3cc1392a02
* Content: [Using the Intune Graph API - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/intune-graph-overview?view=graph-rest-1.0&source=docs)
* Content Source: [api-reference/v1.0/resources/intune-graph-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/intune-graph-overview.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for your feedback.  Currently we don't document the API call limits.  You'll get an HTTP 429 error indicating too many requests if you hit the throttling limit.

**Comment by triplanedave** [comment]
Closing this issue.
