### ISSUE TITLE
For external participants, the phone number is partially redacted

### ISSUE THREAD

**Issue by OferLahav** [microsoftgraph/microsoft-graph-docs#8251]
When subscribing to call record events for external users, the phone number is partially redacted; the first 6 digits are replaced with 'X's.

Is there any way to get the entire value of these numbers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6259f0-9e69-493b-3158-614d11642312
* Version Independent ID: 08963ed9-21ee-773d-3532-75be9cd57e70
* Content: [Get callRecord - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-beta&tabs=javascript#feedback)
* Content Source: [api-reference/beta/api/callrecords-callrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/callrecords-callrecord-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
Phone number masking will be removed soon (for feature parity with the Get-CsUserSession cmdlet that is being removed). This change should roll out next week.

**Comment by stephenjust** [comment]
This should be fixed now.
