### ISSUE TITLE
The token expired

### ISSUE THREAD

**Issue by sachindra149** [microsoftgraph/microsoft-graph-docs#8253]
[Enter feedback here]
The token expired. Can I register the same app twice and get a new token which I can use to send emails or should I mandatorily have to use existing verification through the OTP sent on old phones?
Anyway to get a new token?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99744fa1-3662-8ff5-646b-8be06d43b066
* Version Independent ID: bfc9d00c-c96f-afcc-bb8f-15c2d8601c3b
* Content: [Authentication and authorization basics for Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth/auth-concepts)
* Content Source: [concepts/auth/auth-concepts.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth/auth-concepts.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @matt-steele
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
A long time since this issue was raised, but in case someone else is facing the same issue: When your access token expires, you can request a refresh token. No need to re-register the same application. See https://docs.microsoft.com/en-us/graph/auth-v2-user?view=graph-rest-1.0#authorization-request
