### ISSUE TITLE
'Semi-annually' option missing in accessreview Graph API

### ISSUE THREAD

**Issue by vipulkelkar** [microsoftgraph/microsoft-graph-docs#8262]
The Access reviews UI in Azure portal allows to create a review for 'Semi-Annually' option, however this is missing in the Graph API options
The accessReviewRecurrenceSettings only specifies :

"_The recurrence interval, which must be one of onetime, weekly, monthly, quarterly, or annual._"

Is there a way to set the semi-annual option through the Graph API ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a281916f-c380-e08d-b8e2-9ff8f37c2b48
* Version Independent ID: 8cfa2d8c-2f74-154a-714f-a9c4165a745b
* Content: [accessReview resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/accessreview?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/accessreview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/accessreview.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @markwahl-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markwahl-msft** [comment]
Try "recurrenceType": "halfyearly" in the recurrence settings.

**Comment by vipulkelkar** [comment]
Thanks @markwahl-msft ..it works
