### ISSUE TITLE
Outdated Reference

### ISSUE THREAD

**Issue by HenningBertsch** [microsoftgraph/microsoft-graph-docs#8265]
Example (C#) no longer working: "Cannot implicitly convert type 'System.Collection.Generic.List&lt;Microsoft.Graph. ConversationThread&gt; to 'Microsoft.Graph.IConversationThreadsCollectionPage'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 630e23cf-5fc4-a787-58e4-963f8c15d20f
* Version Independent ID: 54a76f5a-c329-b70f-28fd-7da8a2efa940
* Content: [Create conversation - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-conversations?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/group-post-conversations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-conversations.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Temporarily removed the SDK example until the functionality is revised in the SDK.
