### ISSUE TITLE
Create user with local account identity gives Request_ResourceNotFound error

### ISSUE THREAD

**Issue by michelepatrassi** [microsoftgraph/microsoft-graph-docs#8268]
I'm trying to create a user local account via the azure graph API but I receive a Request_ResourceNotFound. I explained everything in details in this SO question, which I think is quite complete: https://stackoverflow.com/questions/61873199/microsoft-graph-api-create-user-with-local-account-identity-gives-request-reso.

No idea of what I'm missing, I followed the docs and getting all users or creating a normal user in the tenant works fine. Creating a local account fails instead.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-gb/graph/api/user-post-users?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
I'm not able to identify a change to this page. In the SO thread, it seems that others were successful and there may be a problem in the tenant. Closing this issue for now. If you can a describe anything incorrect in the page, please reopen the issue and we can address it.
