### ISSUE TITLE
Watch out for the primaryRole string field (case sensitive!)

### ISSUE THREAD

**Issue by dc911x** [microsoftgraph/microsoft-graph-docs#8278]
Just a heads up for all people trying to assign a primaryRole to a user. We've lost a couple of hours trying to figure out why teachers and students were not showing up in [school data sync](https://sds.microsoft.com/) when giving them a PrimaryRole and other attributes when adding them using Graph API.

example:

PATCH: https://graph.microsoft.com/beta/education/users/objectID

```
{
  "externalSource": "sis",
  "primaryRole": "Teacher",
  "teacher": {
     "externalId": "XXXXX",
     "teacherNumber": "XXX"
 }
}
```

Possible values are: **S**tudent, **T**eacher and Faculty. Capital F or not the last string is just an attribute it doesn't seem to add any value as its not even shown in SDS. 

Please update the docs that you need to use a capital.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d629005-d066-98da-67b3-424849fd8054
* Version Independent ID: d7719b66-bb44-a67b-d87a-ae7bf888c9e4
* Content: [educationUser resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/educationuser.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmast-msft** [comment]
Thank you for your comments, and I apologize for the time you spent on this.  We'll be making changes to SDS to make the UI code case insensitive.  We'll also be changing SDS to write values to AAD in lowerCamelCase. So, we'll be changing SDS, rather than the doc.
