### ISSUE TITLE
how to use update online meeting ?

### ISSUE THREAD

**Issue by thangkj** [microsoftgraph/microsoft-graph-docs#8292]
how to use update online meeting ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bddf229-c02d-7595-78c5-6dac2b1c3c76
* Version Independent ID: a1ccb913-8d51-1445-e81f-a4f100a495e3
* Content: [onlineMeeting resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/onlinemeeting.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ajayvjain** [comment]
@ananmishr - Can you please let us know if there is a way to update online meeting via graph API? Or is there a plan to support this in future releases? Reference - https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http
