### ISSUE TITLE
How to get roomlists contained in a room list?

### ISSUE THREAD

**Issue by rahul-agrawal21** [microsoftgraph/microsoft-graph-docs#8297]
Looks like the Get Place API is now part of v1.0, https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0

But the problem that I am facing is, I am not able to get roomlists contained in a room list

Earlier(beta endpoint), the below endpoint used to return roomlists that are part of bldg2 as well

GET https://graph.microsoft.com/beta/places/bldg2@contoso.com/microsoft.graph.roomlist/rooms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b836740-9263-12cc-9001-c61f08448f0d
* Version Independent ID: 4a5b79f8-d685-6c86-d7ed-12d7c5d309cb
* Content: [List places - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/place-list.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by EliasKaplan** [comment]
Hi @rahul-agrawal21 

What is the error? Can you Provide requestid and timestamp?

Elias

**Comment by rahul-agrawal21** [comment]
@EliasKaplan Thanks for your reply.
Using powershell you can add roomlists to a roomlist and you can retrieve them as well, and it used to work a couple of days back using get places API(beta) as well.

I don't get any error, an empty list is returned. I am not sure how to get the requested, but see if the context helps,
https://graph.microsoft.com/v1.0/$metadata#places('School11%40foghorndev.onmicrosoft.com')/microsoft.graph.roomList/rooms"

**Comment by rahul-agrawal21** [comment]
Hi @EliasKaplan 
Please let me know if you have any updates on this.
Thanks,
Rahul

**Comment by EliasKaplan** [comment]
Hi Rahul

The scenario, show roomlist inside  a roomlist is not specifically supported by MS Graph Places API.
I'll check with @vrod9429  if it is planned for future releases. 
The clients (OWA, Outlook, teams, etc) don't support it either.
What's is the actual scenario to trying to use it for?
Elias

Elias

**Comment by vrod9429** [comment]
@rahul-agrawal21 Do you still need help here or can we close this issue?

**Comment by rahul-agrawal21** [comment]
@vrod9429 This can be closed, we actually went ahead with some other route
