### ISSUE TITLE
List Users also returns the rooms set in O365.

### ISSUE THREAD

**Issue by TiruvedulaMithun** [microsoftgraph/microsoft-graph-docs#8298]
The API returns both the users and rooms configured. Is there a way to filter or distinguish between the two types of objects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5288856d-4731-71a4-8c7b-01a8b9c599cb
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
This users API is not expected to return the rooms. We will investigate. No doc updates needed. You can use this API to specifically list the rooms: https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http
