### ISSUE TITLE
Token duration information missing for Teams

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-docs#8302]
The token duration for Teams entities is not provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by v-chetsh** [comment]
@baywet -  Could you please explain a little more on your requirement.
If possible, please share the repro steps.

**Comment by baywet** [comment]
Hi @v-chetsh 
The [following section](https://docs.microsoft.com/en-us/graph/delta-query-overview#token-duration) lists out the delta token duration for most workloads/entity types (how long is it going to be valid for). Teams is missing from there and I think this information should be provided to the customer.

**Comment by v-chetsh** [comment]
@baywet - We are looking into it internally and we will redirect it to the  documentation team, if any enhancement is required.

**Comment by v-chetsh** [comment]
@RamjotSingh - Could you please share the updates on this issue so that we can close it, if it is already resolved.

**Comment by RamjotSingh** [comment]
The token is valid for the full duration of lookback. The duration for lookback is mentioned already. Closing.
