### ISSUE TITLE
Token duration information missing for Exchange

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-docs#8304]
The token duration for Exchange entities is not provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
There's no specific expiration duration for the delta tokens for the Exchange entities, rather the expiration is dependent on the size of the delta token cache. New delta tokens are continually put in the cache. Once the cache capacity is exceeded, older tokens are deleted. The best way to figure out if a delta token has expired is based on the error code that comes out of the system. I'll update with the specifics of the error code.

**Comment by baywet** [comment]
thanks for the response @abheek-das , can you update the documentation to include the information please? https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md#token-duration
