### ISSUE TITLE
Token duration information missing for Education

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/microsoft-graph-docs#8305]
The token duration for Education entities is not provided.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mlafleur** [comment]
The token duration for Edu resources is the same as [AAD (30 days)](https://docs.microsoft.com/en-us/graph/delta-query-overview?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#token-duration).

**Comment by baywet** [comment]
thanks @mlafleur just created a PR to add it to the docs!
