### ISSUE TITLE
403 Error for Delegated access with Teams I am member of

### ISSUE THREAD

**Issue by ChrisDXC** [microsoftgraph/microsoft-graph-docs#8314]
I believe this is a different issue from https://github.com/microsoftgraph/microsoft-graph-docs/issues/4893 because I am a member of the teams I am trying to read.

Using Delegated access, I am trying to retrieve messages posted in teams I am member of but I still get back a 403 error.
My Delagated access for this app has: ChannelMessage.Read.All and Group.Read.All but not Group.ReadWrite.All

I know this is not a token issue because I can successfully execute in the same flow:
GET: https://graph.microsoft.com/beta/users/{myUserID}/joinedTeams
GET: https://graph.microsoft.com/beta/groups/{GroupID}/owners
GET: https://graph.microsoft.com/beta/teams/{GroupID}/channels
but then:
GET: https://graph.microsoft.com/beta/teams/{GroupID}/channels/{ChannelID}/messages return 403 ?!

And the whole application works as expected in another tenantID - the only difference is that in this other tenant, my Delegated access has also Group.ReadWrite.All.

What else can I run to troubleshoot further this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 701a6812-452b-7724-dc1b-635fc90736c9
* Version Independent ID: c956e3e9-d914-346a-799d-f00707fd786a
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@ChrisDXC , Following delegated permission[`ChannelMessage.Read.All`, `Group.Read.All`, `Group.ReadWrite.All`] required to call [List Channel messages](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http#permissions) Graph API you can also call this with Application permission these should be consented by admin.
