### ISSUE TITLE
Create Team API not working 

### ISSUE THREAD

**Issue by RonakJain7** [microsoftgraph/microsoft-graph-docs#8323]
[
Request : https://graph.microsoft.com/beta/teams
Request Body : 
{
  "template@odata.bind": "https://graph.microsoft.com/beta/teamsTemplates('standard')",
  "displayName": "My Sample Team",
  "description": "My Sample Team’s Description",
  "owners@odata.bind": [
    "https://graph.microsoft.com/beta/users('96cb43af-eaad-4449-b4e9-05c8e005c767')"
  ]
}
Response : {
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": "d7dd5e79-c675-4310-8a72-d8f4cb92788a",
      "date": "2020-05-20T05:55:15"
    }
  }
}
-----------------------------------------------------

PUT https://graph.microsoft.com/v1.0/groups/{id}/team
Content-type: application/json
Request Body
{  
  "memberSettings": {
    "allowCreateUpdateChannels": true
  },
  "messagingSettings": {
    "allowUserEditMessages": true,
    "allowUserDeleteMessages": true
  },
  "funSettings": {
    "allowGiphy": true,
    "giphyContentRating": "strict"
  }
}
Response : 
{
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "request-id": "d7dd5e79-c675-4310-8a72-d8f4cb92788a",
      "date": "2020-05-20T05:55:15"
    }
  }
}
]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
we could not reproduce the issue on our side. Could you please share screen shots of the error what you seeing when you create a team? Also When you want to update the team settings you need to set HTTP request as PATCH https://graph.microsoft.com/beta/teams/{id}. Could you please go through the document [here](https://docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&tabs=http)?

**Comment by RonakJain7** [comment]
The method put(Team) is undefined for the type ITeamRequest

graphClient.groups("{id}").team().buildRequest().put(team);

**Comment by Nikitha-MSFT** [comment]
when you create a team you need to use post method as Documented [here](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http). when you want to Edit you need to use patch method as documented [here](https://docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&tabs=http)
