### ISSUE TITLE
$search behavior

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#8329]
So I've been playing with $search against directory objects, and either this documentation article or the blog article over at https://developer.microsoft.com/en-us/graph/blogs/build-advanced-queries-with-count-filter-search-and-orderby/ is providing incorrect/incomplete information. Here's an example:

I start with
/beta/servicePrincipals?$search="displayName:MicrosoftTeams"
this returns a dozen or so SPs, all have both "Microsoft" and "Teams" in their display name, so all good. If I filter those client-side for say "hook", i get two entries:

displayName                          
-----------                          
Microsoft Teams Mailhook             
Microsoft Teams RetentionHook Service

If I do a $search query that contains "hook" however, I get only a single entry:

displayName                          
-----------                          
Microsoft Teams RetentionHook Service

How so? According to the documentation above, matches should be case-insensitive, so in this regard "Mailhook" should be the same as "RetentionHook"? The blog article on the other hand implies that tokenization is done for matches as well, thus "Mailhook" will not match? Here's the quote:

searching for “abc” will find “123abc”, “zzzAbc”, “abc def”, “Team-ABC”, “x.abc”, but not “aaabc”.

This is indeed the behavior I'm seeing, but the article above claims matches should be case insensitive, as in no tokenization? I suppose I'm reading it wrong, so can you please clarify it, and add some examples to prevent confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters?#using-search-on-directory-object-collections)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by michevnew** [comment]
OK, here's another example, which makes me think I'm not understanding this at all, or it's broken:

$uri = 'https://graph.microsoft.com/beta/users?$search="displayName:new"'
$Gr = Invoke-WebRequest -Headers $AuthHeader -Uri $uri
($gr.Content | ConvertFrom-Json).Value | select displayName

displayName
-----------
newMEU     


$uri = 'https://graph.microsoft.com/beta/users'
$Gr = Invoke-WebRequest -Headers $AuthHeader -Uri $uri
($gr.Content | ConvertFrom-Json).Value | select displayName | ? {$_ -match "new"}

displayName
-----------
newMEU     
sharednew  
WCnew      

Even if we accept tokenization is performed, and the middle entry ignored, why does "WCnew" not match "new"? It's matching on displayname, so it should not be defaulting to startswith, which is the only explanation I have...

Cant you just add wildcard/regexp match like every other API out there...

**Comment by Licantrop0** [comment]
Hi @michevnew, I wrote the blog post.
You are right, our search is not full-text search or semantic search.
We currently rely on tokenizing variances in word cases (`helloWorld` translates in `hello` and `world` tokens, and splitting whenever there is a punctuation character (`.`, `-`, `:`, etc...).
So in this example, searching for `world` will find `helloWorld`, but unfortunately not `helloworld`.

We will provide more functionalities before GA, and this preview will let us collect the needed feedback to prioritize what you need to enable your scenarios.
Please send any other comment [in this brief survey](https://aka.ms/MsGraphAADSurveyGH).
