### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by jzbuaa** [microsoftgraph/microsoft-graph-docs#8331]
I tried this api but got 500 response:
{
  "error": {
    "code": "InternalServerError",
    "message": "Failed to execute request.",
    "innerError": {
      "request-id": "6d93e511-6cdf-4fd5-997f-12778b191801",
      "date": "2020-05-20T09:48:08"
    }
  }
}

the command I was using:
curl --verbose --header "Content-Type: application/zip;" --header "Authorization: $token" --data-binary "@/mnt/c/Users/zjin/Downloads/EasyOA-Edog.zip" "https://graph.microsoft.com/v1.0/appCatalogs/teamsApps"

I can successfully upload the zip to my org in Teams so the zip should be valid, anything I did wrong using this api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc580041-9ed5-dc21-2eb1-813152044527
* Version Independent ID: b229cada-3a68-38b5-4236-7cd0d970679f
* Content: [Permissions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamsapp-publish.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Gousia-MSFT** [comment]
@jzbuaa It looks like there is an issue with your Auth token. Could you please confirm if you have added the access token with all the required permissions?

**Comment by Gousia-MSFT** [comment]
Please re-open if you are still facing any issues.
