### ISSUE TITLE
This page talks about a German national cloud

### ISSUE THREAD

**Issue by memildin** [microsoftgraph/microsoft-graph-docs#8333]
I've heard this was deprecated quite some time ago. Please check.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2dbd263-9afd-aa90-cb50-bbadfc424cc2
* Version Independent ID: 63aaf699-609e-b4dd-bd02-9f891e09db8d
* Content: [National cloud deployments - Microsoft Graph](https://docs.microsoft.com/en-us/graph/deployments)
* Content Source: [concepts/deployments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/deployments.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MSGraphDocsvTeam
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by CelesteDG** [comment]
Hello @negoe - Assigned this question on National Clouds to you. Thank you.

**Comment by negoe** [comment]
@memildin Azure Germany is not yet deprecated. It is a work in progress. All Germany endpoints are very much functional. Any Germany endpoint will not be deprecated without a formal announcement.
