### ISSUE TITLE
How to list the manager name here in java stand-alone app?

### ISSUE THREAD

**Issue by jravi515** [microsoftgraph/microsoft-graph-docs#8334]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0106f6fc-0b6d-deae-ef40-37f29a94abbd
* Version Independent ID: 8614876d-6a23-3c10-c2f6-97a059f5c73b
* Content: [List manager - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=java)
* Content Source: [api-reference/v1.0/api/user-list-manager.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-manager.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Unfortunately, we do not have information about using Java to make this call. Nothing to change in the page. Closing the issue.
