### ISSUE TITLE
Update chatMessage, Delete chatMessage

### ISSUE THREAD

**Issue by zdendyak** [microsoftgraph/microsoft-graph-docs#8335]
It seems there is no option to edit or delete a message in a channel or a chat using Graph API.
Please add these endpoints to the `chatMessage ` resource

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f046b37e-8569-b617-4c9b-402342d4bef9
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/chatmessage.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ashoksubedi1** [comment]
Yes, I am so glad it is in V1 now. All I want now is to delete and update those chat messages

**Comment by diogosilva96** [comment]
I have a use case where it requires the execution of Deletes/Updates of messages in a Team's Channel.
