### ISSUE TITLE
ResourceProvisioningObject is null today

### ISSUE THREAD

**Issue by SpikerDestin** [microsoftgraph/microsoft-graph-docs#8341]
Yesterday our groups that were teams had TEAM in this property.  Today they are all empty.  Anything change today?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75dbe68-e162-8861-d194-4a29de3bd731
* Version Independent ID: f58a6930-8575-8306-4273-fc413b979879
* Content: [List all teams in Microsoft Teams for an organization - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-list-all-teams#feedback)
* Content Source: [concepts/teams-list-all-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-list-all-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Meghana-MSFT** [comment]
@SpikerDestin 

We tried the above issue with [Get a list of groups](https://docs.microsoft.com/en-us/graph/teams-list-all-teams#get-a-list-of-groups). I was able to find my group ID with ResourceProvisioningOptions having Teams.

**Comment by Meghana-MSFT** [comment]
Closing this issue for now. Please feel free to reopen the issue if you are still facing the issue.
