### ISSUE TITLE
Any plans to add application permissions for this API?

### ISSUE THREAD

**Issue by JoeKaplan** [microsoftgraph/microsoft-graph-docs#8349]
By the looks of it the API has no application permissions available and this is by design. However, I'd like to confirm if that situation is temporary or expected to be permanent and if permanent, can you explain why? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df4ede94-a1b0-cdce-59c4-f3fde441f74f
* Version Independent ID: 4138842a-de3b-113e-868e-96cc990d32f5
* Content: [List phoneMethods - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/authentication-list-phonemethods?view=graph-rest-beta&tabs=http#feedback)
* Content Source: [api-reference/beta/api/authentication-list-phonemethods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/authentication-list-phonemethods.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mmcla** [comment]
This is temporary! We do plan to add app-only permissions, but I have no timeline to share.

**Comment by dfoxnb** [comment]
I was able to add application permissions for UserAuthenticationMethod.Read.All, but got access denied with the GET. I'm assuming this is because it's still not supported?

**Comment by FaithOmbongi** [comment]
Hello @JoeKaplan, 
Application permissions are now supported when acting on others, though not on self. Kindly refer to the updated permissions table.

No immediate additional updates identified for the page, but the page will be updated when there's a change. Closing this issue for now.
