### ISSUE TITLE
Question about statement of SLA of 24 hours

### ISSUE THREAD

**Issue by ryanmck-msft** [microsoftgraph/microsoft-graph-docs#8353]
Can anyone comment on when this page included the statements about the 24 hour SLA?  I am trying to determine if that was a recent update or if this page has always stated the SLA as 24 hours.
"The current SLA for synchronizing membership changes made to groups to Teams is up to 24 hours after the sync is triggered by client activity. It can take longer under certain circumstances (due to service load, for example)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed58b36a-1416-fcc0-4dd7-39d2a9f48b7c
* Version Independent ID: 438b361c-d067-4027-6a7d-3988c7028837
* Content: [Creating teams and managing members using Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-create-group-and-team#feedback)
* Content Source: [concepts/teams-create-group-and-team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-create-group-and-team.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @hachandr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hachandr** [comment]
This revision was made in April due to our efforts to accommodate new traffic in light of the COVID crisis. We are actively working to bring this SLA down and make the sync process as near instantaneous as possible.

**Comment by ryanmck-msft** [comment]
Do you have any timing on bringing that SLA back down?  This is impacting a critical Teams production solution with an enterprise customer of mine that is depended on this capability.  They just noticed the issue starting last Thursday 5/14.  Previous to that they were still seeing near instantaneous sync.  Teams Engineering has been engaged with my customer on this for the past year so we are escalating there too.  Nobody on our team was aware this change was coming or that it had been made in April.

**Comment by hachandr** [comment]
We are hoping to bring the SLA down in stages starting the end of this month. Please note that in most cases, the sync will take less than 24 hours. The issue that you’re observing since 5/14 may be unrelated so please do follow up with Teams Engineering on that investigation.

________________________________
