### ISSUE TITLE
How to use it in React App ? Sample

### ISSUE THREAD

**Issue by vikramdadwal** [microsoftgraph/microsoft-graph-docs#8355]
I tried the above code in React Application, but Person card does not load:

![image](https://user-images.githubusercontent.com/10174566/82503577-694f1980-9aae-11ea-81ea-c55307477a59.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c4f0099-62b5-9272-d6ab-7a4f80efcfcb
* Version Independent ID: c6ebefd4-909e-a2a3-2296-306c5e7b6740
* Content: [Get Started with the Microsoft Graph Toolkit - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/get-started#feedback)
* Content Source: [concepts/toolkit/get-started.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/toolkit/get-started.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @elisenyang
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by elisenyang** [comment]
Hi @vikramdadwal,

Can you please post this on the Microsoft Graph Toolkit StackOverflow: https://stackoverflow.com/questions/tagged/microsoft-graph-toolkit

Thanks,
Elise
