### ISSUE TITLE
Is there a property that displays the sensitivity of a message?

### ISSUE THREAD

**Issue by somehowadev** [microsoftgraph/microsoft-graph-docs#8359]
Reading through the documentation - I don't see any reference to this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff33a4a-824d-9605-aa80-bcb37428ed4b
* Version Independent ID: 276cebbe-10bc-100e-f9b1-51b2ba30c64b
* Content: [message resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/message.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
Currently Outlook message sensitivity property (Normal, Personal, Private, Confidential etc.) is not exposed via the Graph API queries.

If you need this property and wish to file a feature request, please use below link: https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests?category_id=359602 

Closing, please re-open if more clarification is required.
