### ISSUE TITLE
Java SDK - Related with Application Methods

### ISSUE THREAD

**Issue by Visinghr** [microsoftgraph/microsoft-graph-docs#8368]
IApplicationCollectionPage applications = graphClient.applications()
	.buildRequest()
	.get();

Java SDK doesn't have method for getting the application. We need to update the documentation to use the customRequest() instead of application()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 016eadaa-d06b-2e43-1726-b7869957bc00
* Version Independent ID: 05d7f4b4-d564-1ce7-d676-ca8b433f763d
* Content: [List applications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-list?view=graph-rest-1.0&tabs=java#feedback)
* Content Source: [api-reference/v1.0/api/application-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @Visinghr 
Thanks for reaching out.
The method was added with version 1.8.0 of the sdk about a month after your created this issue.
https://github.com/microsoftgraph/msgraph-sdk-java/blame/2c6e50743a478bf8b48342fed28166100a75093b/src/main/java/com/microsoft/graph/requests/extensions/BaseGraphServiceClient.java#L267
Closing.
