### ISSUE TITLE
the SDK class representing this object does have a permissions property

### ISSUE THREAD

**Issue by kalyankrishna1** [microsoftgraph/microsoft-graph-docs#8371]
Their is thus no way to retrieve this value

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dabd7961-73aa-5a6c-0935-66038bf6fcfd
* Version Independent ID: 52882de2-8556-9a76-b2fa-0efefe0f0398
* Content: [governanceResource resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/governanceresource?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/governanceresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/governanceresource.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
