### ISSUE TITLE
I want to create MS Team meeting but it create skype meeting

### ISSUE THREAD

**Issue by YasiruUOK** [microsoftgraph/microsoft-graph-docs#8373]
I used,
OnlineMeetingProvider = OnlineMeetingProviderType.TeamsForBusiness
But It create Skype meeting. Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=csharp#feedback)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Please check the allowedOnlineMeetingProviders in this calendar:
https://docs.microsoft.com/en-us/graph/api/resources/calendar?view=graph-rest-1.0

To understand how Exchange and Teams interact, please check below:
https://docs.microsoft.com/en-us/microsoftteams/exchange-teams-interact

https://docs.microsoft.com/en-us/microsoftteams/setting-your-coexistence-and-upgrade-settings

**Comment by YasiruUOK** [comment]
The reason was we try with school account, then we buy basic business account, then problem solved
