### ISSUE TITLE
GET the inviteRedeemUrl property for an existing Invitation

### ISSUE THREAD

**Issue by Dan-SafeGen** [microsoftgraph/microsoft-graph-docs#8380]
I can't find the documentation to determine if I can GET the inviteRedeemUrl property for an existing Invitation entity/external guest (a guest that was previously invited via PS or console or Graph) assuming that the externalUserState eq PendingAcceptance and I have the user ID?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c0170d-e214-ce6f-b7b4-589960e9962d
* Version Independent ID: bc805140-9ebe-a4ef-54e7-90f2054b8b83
* Content: [invitation resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/invitation?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/invitation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/invitation.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @elisolMS
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by elisolMS** [comment]
The invitation redemption URL is only returned by the invitation API when the invitation is sent not stored as a property on the User object, so you can't query for it after inviting the user.  However, you can re-invite the same user and get a new invitation redemption URL to use if needed.
