### ISSUE TITLE
Where does the "Request" object come from?

### ISSUE THREAD

**Issue by joej164** [microsoftgraph/microsoft-graph-docs#8385]
You have this line of code and similar...  `request: new Request(`/me/calendarview?startDateTime=${start}&endDateTime=${end}`, {`. I can't find in the graph-sdk any class object named Request to import.

Would be helpful if you list any required imports for the above examples to work.  None of the other articles above this one reference creating a Request object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0c6b539-d4f6-168f-2574-2e54c7cbcb56
* Version Independent ID: 0d1e3dfd-f3f3-2acf-6b31-d2c22d318fad
* Content: [Use the Microsoft Graph SDKs to batch requests - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/batch-requests?tabs=typescript#feedback)
* Content Source: [concepts/sdks/batch-requests.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/batch-requests.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
@joej164 Request is a standard JavaScript object, part of the Fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Request. There's no import required.
