### ISSUE TITLE
TeamsAppId does not correlate with the Id from my app manifest schema

### ISSUE THREAD

**Issue by erwelch** [microsoftgraph/microsoft-graph-docs#8386]
I manually uploaded an app manifest schema to a Team in Microsoft Teams for a bot I'm developing. When I use the Graph query explorer to find the installed apps in that Team using this query: `https://graph.microsoft.com/v1.0/teams/team-id/installedApps?$expand=teamsAppDefinition` the `teamsAppId` for my manually installed app is not the same id I specified in my manifest. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Gousia-MSFT** [comment]
@erwelch Every time an app is uploaded you have the ability to set the external id field in your manifest. This value is meant specifically for easier tracking of an app from the developer's side.  If you need to track a sideloaded app across different upload/install sessions, then you would use the external id to fetch the app id of your app.
Could you please try using this to get your appId:
`GET /teams/id/installedApps?$filter=externalId eq '{ExternalIdInManifest}'&$expand=teamsApp`
This will give you the app id of your sideloaded app. You could then use this app id to call into the generateNotifications API.
