### ISSUE TITLE
Create Team API Not Working 

### ISSUE THREAD

**Issue by RonakJain7** [microsoftgraph/microsoft-graph-docs#8390]
PUT https://graph.microsoft.com/v1.0/groups/{id}/team
Content-type: application/json
Request Body
{
"memberSettings": {
"allowCreateUpdateChannels": true
},
"messagingSettings": {
"allowUserEditMessages": true,
"allowUserDeleteMessages": true
},
"funSettings": {
"allowGiphy": true,
"giphyContentRating": "strict"
}
}
Response :
{
"error": {
"code": "BadGateway",
"message": "Failed to execute backend request.",
"innerError": {
"request-id": "d7dd5e79-c675-4310-8a72-d8f4cb92788a",
"date": "2020-05-20T05:55:15"
}
}
}
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=java#feedback)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @RonakJain7 

are you still facing this issue? According to the [beta documentation](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-beta&tabs=http), this teamify approach will be deprecated. Microsoft is now suggesting the following way to create a team from a group: https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http#example-4-create-a-team-from-group

I hope it helps.

Regards,
Jarbas

**Comment by RonakJain7** [comment]
Am using java API 

The method put(Team) is undefined for the type ITeamRequest

graphClient.groups("{id}").team().buildRequest().put(team);
