### ISSUE TITLE
Can't get all data for secure score history

### ISSUE THREAD

**Issue by macpak** [microsoftgraph/microsoft-graph-docs#8391]
Hi,

I am using the api to get secure score history.
One question:
- I've tried to get history for the last 90 days (counting from today 2020-05-22) , however the earliest date I got is "createdDateTime":"2020-02-23T00:00:00Z". I'd expect to get data for 2020-02-21T00:00:00Z (21.05.2020 - 90 days).

The other thing I spotted is a situation that I got one missing data. The returned collection earliest date (as mentioned above) is 2020-02-23 however the next date in the collection is 2020-02-25. So it seems 2020-02-24 is missing. Is it normal ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc52e5ba-c66a-a5db-fde8-43ecae447d60
* Version Independent ID: f4ded98c-b942-470f-bb35-a421fccb5261
* Content: [secureScore resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/securescore?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/securescore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/securescore.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by chinguyen1** [comment]
@macpak you should get your daily securescore data. Please send us your tenant Id and app Id, so we can look into our logs.

**Comment by anchawl** [comment]
@macpak - In some cases we don't get data from our partner team for a particular date and because of that the score could be missing for that date. Let us know if you have other issues.

**Comment by chinguyen1** [comment]
Please reopen the issue or create a new one if you have any other issues/questions.
