### ISSUE TITLE
More clarity required for $search with users and groups

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#8393]
All the text and examples do NOT mention that $count=true and ConsistencyLevel: eventual is required for all those requests.  Support case indicated that the customer just tried the queries that are listed, and naturally those are failing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#search-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by michevnew** [comment]
Same for the Odata cast example, it does not work without the header set, and more interestingly, without $count either...

**Comment by Licantrop0** [comment]
I'm planning to do a sweep next week on the new docs, explaining $search better and the requirements for all the new functionalities.
