### ISSUE TITLE
OneNote support

### ISSUE THREAD

**Issue by gclark01** [microsoftgraph/microsoft-graph-docs#8397]
Is there any reason that OneNote support has been removed from this document?

As referenced here - https://github.com/microsoftgraph/microsoft-graph-docs/pull/8313

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62780393-9fa8-78ea-4b4b-8d67beeeae80
* Version Independent ID: d10967c5-b138-fa4d-d357-a23d9b1f6fd7
* Content: [Configuring the built-in tab types in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-configuring-builtin-tabs)
* Content Source: [concepts/teams-configuring-builtin-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-configuring-builtin-tabs.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Well, not only OneNote support has been removed from this documentation. I am also missing:
- Custom Tabs
- Planner Tabs
- Microsoft Stream tabs
- Microsoft Forms tabs
- Wiki tabs
- Document library tabs
- Power BI tabs
- SharePoint page and list tabs

Is that a glitch?

**Comment by v-chetsh** [comment]
@gclark01 - This documented is updated for above mentioned sections, so we are closing this bug from our end.
