### ISSUE TITLE
Get the 500 error when using the Office 365 Management Activity API

### ISSUE THREAD

**Issue by nkxubin** [microsoftgraph/microsoft-graph-docs#841]
When I used the API https://manage.office.com/api/v1.0/{tenantId}/activity/feed/subscriptions/start?contentType=Audit.AzureActiveDirectory.

I got the error message "{"error":{"code":"AF50000","message":"Please retry the request again in an hour. We have been notified and would be resolved soon."}}" with 500 return code. But this API was working last week.

**Comment by dmahugh** [comment]
Temporal issue, please report if it happens again.
