### ISSUE TITLE
The titles of appRoleAssignments and appRoleAssignedTo are confusing 

### ISSUE THREAD

**Issue by jiasli** [microsoftgraph/microsoft-graph-docs#8412]
These 2 APIs have very similar doc title:

**appRoleAssignments**: https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-1.0&tabs=http

> Grant an appRoleAssignment to a service principal

**appRoleAssignedTo**: https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignedto?view=graph-rest-1.0&tabs=http 

> Grant an appRoleAssignment for a service principal

Note that the title uses "_for_" which doesn't comply with the "_to_" in the API name/URL.

The "_to_/_for_" difference is confusing and not clear about what the API really does. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47f3b787-b279-695c-8681-7832b203d5b8
* Version Independent ID: 794ffd87-99dd-0521-cd5d-8a340d5babad
* Content: [Grant an appRoleAssignment to a service principal - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-post-approleassignments?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-post-approleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/serviceprincipal-post-approleassignments.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nataliamelissas** [comment]
Completely agree. The wording of these docs makes developers spend unnecessary time researching and deciphering its meaning.

**Comment by jiasli** [comment]
For anyone who is interested, I have posted some detailed explanations at https://github.com/Azure/azure-cli/issues/12137#issuecomment-596567479, https://github.com/Azure/azure-cli/issues/12137#issuecomment-633397010. Hope this helps.

**Comment by psignoret** [comment]
@jiasli @nataliamelissas Any proposals on alternative naming/wording that would make more sense? (Assume I can't change the actual API name, but can definitely change the words used in the title/article.)

**Comment by psignoret** [comment]
Closing because there was not response. Happy to re-open if there is additional input!
