### ISSUE TITLE
How to get the default picture of the user/group?

### ISSUE THREAD

**Issue by blueelvis** [microsoftgraph/microsoft-graph-docs#8415]
As per this document, I seem to be able to get the pictures of users only who have uploaded their picture but when someone hasn't uploaded it, Active Directory shows a default picture with their initials. 

For example, if my name is **Doe, John**, it will have the default picture with a colored background containing the alphabets - **DJ**. Is there a way to get this?

Thanks,
Pranav

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-US/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@kevinbellinger  do you mind also changing me from being the owner of this page too ;-)

**Comment by kevinbellinger** [comment]
This is client side logic across M365 which auto-creates the initials when a picture isn't present. That is why you receive a 404 instead of an image with initials. 

We don't plan for this to be a service side capability after a long internal discussion about it. 

@jthake-msft how do I change owner here? :)
