### ISSUE TITLE
The fourth example (getting the MIME content) is not implemented by the C# SDK

### ISSUE THREAD

**Issue by kamikkels** [microsoftgraph/microsoft-graph-docs#8426]
Example #4 doesn't work in C#.

'IMessageRequestBuilder' does not contain a definition for 'Content', so the example code doesn't compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4bf275f-7a02-7e90-120f-2e1d055dac95
* Version Independent ID: b1556931-c2fd-7400-4e45-d666a8a53540
* Content: [Get message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=csharp#examples)
* Content Source: [api-reference/v1.0/api/message-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
Adding @andrueastman since this is related to auto-generated SDK code from Example.

**Comment by andrueastman** [comment]
Thanks for raising this. I will investigate this and revert on the solution.

**Comment by nickalbrecht** [comment]
For anyone curious, it looks like this is fixed in the 4.x update to the Microsoft.Graph package. This can probably be closed.

**Comment by kamikkels** [comment]
Re-testing the example, works correctly now.
