### ISSUE TITLE
Please make java examples

### ISSUE THREAD

**Issue by RoarGronmo** [microsoftgraph/microsoft-graph-docs#8429]
[Enter feedback here]
You should do an effort to make a java example on doing a upload file example.

RG

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92fb8c7-4409-d945-57dd-5d6fc4010051
* Version Independent ID: f77c05bd-2688-bd4e-1f8f-f18feb3a8639
* Content: [Upload small files - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by baywet** [comment]
Hi @RoarGronmo 
Thanks for reaching out and thanks for the patience.
The sample was not being generated because of a bug in the generation process.
This has been addressed and the sample will be generated soon.
https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/365
Closing.
