### ISSUE TITLE
/users/{id}/joinedTeams  is not getting me all the teams if more than 1000 teams created

### ISSUE THREAD

**Issue by yogi466** [microsoftgraph/microsoft-graph-docs#8430]
/users/{id}/joinedTeams

this graph api call is not getting me all the teams for provided user id , if more than 1000 teams are created , and it is not having  @odata.nextLink as well , recently created teams are missing 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533cbe72-3c95-04b8-5db4-cdd32d088d57
* Version Independent ID: fb69519b-3e4a-2279-cf1d-8e9c082fafd6
* Content: [Get team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Could you please try it again? it may took sometime to show all teams.
