### ISSUE TITLE
SigninActivity is nowhere to be found in the results? 

### ISSUE THREAD

**Issue by baswijdenes** [microsoftgraph/microsoft-graph-docs#8431]
Hi,

I'm using 'https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http' in PowerShell with this exact url:
'https://graph.microsoft.com/beta/users'

This doesn't contain the SignInActivity though. Even when I add it to the filter:
'https://graph.microsoft.com/beta/users?$filter=({0})&$select=displayName,signInActivity' 

It won't show the SignInActivity. 

Am I doing something wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbc2099e-c474-a648-60bb-4520f9fa1d23
* Version Independent ID: 9c894ef4-2cff-60e5-a726-8281655005fd
* Content: [List users - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
It appears that this issue does not apply to this particular API page. I believe the operation to get sign-in activity, would be something like:

GET https://graph.microsoft.com/beta/users?$select=displayName,signInActivity

This is documented on this page. Closing this issue. Please open an issue against the PowerShell documentation.
