### ISSUE TITLE
Adding a user to a school doesn't enable the user to be seen in SDS

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/microsoft-graph-docs#8433]
We are developing a solution where we would push teachers to the graph api.

They show up in Azure AD, we can query their educationUser details.
We added the user to a school with this command, but if I open https://sds.microsoft.com my new teachers won't show up.

Also SDS doesn't show teachers/students for a newly created group.

Any guidelines on how to "upgrade" a regular user created with graph to an educationUser that shows up in SDS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50566819-38c9-65b2-4a18-433f61db7321
* Version Independent ID: 271cdb3a-7026-6e94-501e-580abd4eda8f
* Content: [Add educationUser to an educationSchool - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/educationschool-post-users?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/educationschool-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/educationschool-post-users.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mlafleur** [comment]
Without seeing how you're creating the Teacher, it's difficult to diagnose why they're not showing up in SDS. That said, the most likely culprit is the `primaryRole` property. The SDS UI filters Users based on Primary Role. In this case, it will only surface Users where `primaryRole` is set to `Teacher`.

Some background:

SDS automatically populates a number of properties that the Edu Graph APIs leave up to the developer. There are a number of reasons for this, but in general, it boils down to SDS having far more context. 

For example, each SDS import operates against a complete collection of Schools, Students, Teachers, etc. which allows it to infer a number of property values (i.e that User is a Teacher or Student.). In contrast, the Edu Graph APIs operates against one resource at a time (e.g. `educationUser`) so it must rely on the developer to explicitly provide this information.

**Comment by svrooij** [comment]
We are trying to create a user in the education context, with the following request. This request **works**.

```http
POST https://graph.microsoft.com/v1.0/education/users
Content-type: application/json

{
  "accountEnabled": true,
  "displayName": "displayName-value",
  "mailNickname": "mailNickname-value",
  "userPrincipalName": "upn-value@tenant-value.onmicrosoft.com",
  "passwordProfile" : {
    "forceChangePasswordNextSignIn": true,
    "password": "password-value"
  },
  "externalSource": "sis",
  "primaryRole": "teacher",
  "teacher": {
    "externalId": "1234"
  }
}
```

This creates a user for us with the education stuff set correctly, but we also want to set the `jobTitle` and the `ageGroup` on the user, and some other less important properties. Since the educationUser is backed by a graph user, I expected that we could set all the regular user properties as well. This request **doesn't work**.

```http
POST https://graph.microsoft.com/v1.0/education/users
Content-type: application/json

{
  "accountEnabled": true,
  "displayName": "displayName-value",
  "mailNickname": "mailNickname-value",
  "userPrincipalName": "upn-value@tenant-value.onmicrosoft.com",
  "passwordProfile" : {
    "forceChangePasswordNextSignIn": true,
    "password": "password-value"
  },
  "externalSource": "sis",
  "primaryRole": "teacher",
  "teacher": {
    "externalId": "1234"
  },
  "jobTitle": "Dean",
  "ageGroup": "adult"
}
```

**Comment by mlafleur** [comment]
I'm glad to hear you sorted it out. 

One aside, there is currently work being done in SDS to camel case enum values at import (in this case, `teacher` and `student`) so this confusion should hopefully be cleared up very soon.
