### ISSUE TITLE
Graph throttles sorting Sharepoint list items by ID column

### ISSUE THREAD

**Issue by BP-StepanO-RUS** [microsoftgraph/microsoft-graph-docs#8450]
Hello,

Sorry if this is a wrong place to ask, please let me know if there's a better place.

I have a Sharepoint list with, let's say, 15000 items. I'm sending a request from a Django app to get that list's items, and if I don't sort and ask for 1000, it gives me items 1→1000. So that works (items?select=id,fields&expand=fields&top=1000).

If I want to sort and get 15000→14001, (items?select=id,fields&expand=fields&top=1000&orderby=id%20desc) it returns "message": "The request has been throttled"

It doesn't work both in python and Graph Explorer.

According to Graph docs, orderby should work
https://docs.microsoft.com/en-us/graph/query-parameters#orderby-parameter

What am I doing wrong? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by schinna** [comment]
I do have same issue, any pointers ?
