### ISSUE TITLE
How to use chatThread ID for proactive message

### ISSUE THREAD

**Issue by erwelch** [microsoftgraph/microsoft-graph-docs#8452]
This page describes how to get all the necessary information, but then links [this page](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet) that doesn't include the same terminology. What does the chatThread ID have to do with sending a proactive message? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4690677-2b12-0d63-06db-45172132f540
* Version Independent ID: 129f7f1f-78c4-4e80-2eac-f0ce7619f231
* Content: [Proactive messaging using a bot in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-proactive-messaging#get-the-chat-thread-id)
* Content Source: [concepts/teams-proactive-messaging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-proactive-messaging.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by HunaidHanfee-MSFT** [comment]
Hello,
Documentation is updated and I didn't see anything related to chat thread Id in updated document. 
Please have a look and let us know if it's convey wrong information.

We are closing this issue as of now, feel free to re-open it in case of any query.
