### ISSUE TITLE
Set up webhook for change in presence

### ISSUE THREAD

**Issue by jafar-pa** [microsoftgraph/microsoft-graph-docs#8459]
As I was trying to configure webhook with graph presence API to get alert on the change occurrence on users status like Away, Available,DoNotDisturb etc, couldnt figured out any doc related to this topic, Would be grateful If I get some links or leads to configure such API  if available

Thanks!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33d14c58-7163-a7b7-6f84-c075d0f6870d
* Version Independent ID: 3710d019-8a67-59cc-75b6-bcecc106180d
* Content: [Use the Microsoft Graph API to get change notifications - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/webhooks.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
The feature is not yet available but the work is in progress. You can upvote the [following uservoice idea](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/39456202-teams-subscription-to-user-presence-updates) to be notified of the progress.

**Comment by jafar-pa** [comment]
Thanks much!! I would appreciate if you could share the ETA for this feature
