### ISSUE TITLE
The content type is required for this call but it is not documented

### ISSUE THREAD

**Issue by Busted1942** [microsoftgraph/microsoft-graph-docs#8460]
The content type is required for this call but it is not documented.

The current documentation says this:

Header | Value
-- | --
Authorization | Bearer {token}. Required.
Content-Type | application/json

It should be made clear that the the content type json is required like it is on other page.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as the doc has been updated
