### ISSUE TITLE
Adding Users using Batch Call of add member

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#8463]
[Enter feedback here]

This documents recommends to wait one sec  between adding members. I am making a Batch call to add about 18 members at time. Is that why my group members are not seen on the Team right away. My process is in the order
1. Create Group
2. Add members through Batch call
3. Add Team

Should I change the Team with this order instead to fix my issue
1. Create Group
2. Add Team
3. Add members through batch calls.

I am hoping if I change the order then all group members will be seen on Team right away. 

Or do recommend to not do batch call and add members with One Sec difference one by one. 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed58b36a-1416-fcc0-4dd7-39d2a9f48b7c
* Version Independent ID: 438b361c-d067-4027-6a7d-3988c7028837
* Content: [Creating teams and managing members using Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-create-group-and-team)
* Content Source: [concepts/teams-create-group-and-team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-create-group-and-team.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @hachandr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Please see response in https://github.com/microsoftgraph/microsoft-graph-docs/issues/8465

**Comment by HunaidHanfee-MSFT** [comment]
We are closing this. Let us know if you have any query.
