### ISSUE TITLE
Add information for 'members' of a channel

### ISSUE THREAD

**Issue by carlo-quinonez** [microsoftgraph/microsoft-graph-docs#8469]
There are [now APIs](https://docs.microsoft.com/en-us/microsoftteams/private-channels-life-cycle-management#using-graph-api-2) for querying a list of Team members that are in a channel.

> `https://graph.microsoft.com/beta/teams/<group_id>/channels/<channel_id>/members` 

Please add this relationship to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75f86208-723e-a0c9-2cce-3e681dfa7b9c
* Version Independent ID: dc38068e-3b39-1352-117d-e770485b7b70
* Content: [channel resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/channel.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Namita2015-lab** [comment]
@carlo-quinonez Is it possible to get list of members for each channel of a team?

**Comment by Nikitha-MSFT** [comment]
@Namita2015-lab - Yes you can get list of members for each channel of a team, Could you please check [List members of a channel](https://docs.microsoft.com/en-us/graph/api/channel-list-members?view=graph-rest-1.0&tabs=http)?
