### ISSUE TITLE
How to list all security groups in an organization?

### ISSUE THREAD

**Issue by xdmushui** [microsoftgraph/microsoft-graph-docs#8471]
Hi, 
In the current document, there is an example: List all Office 365 groups in an organization. （$filter=groupTypes/any(c:c+eq+'Unified')）

I tried the following ways to get all the security groups, however, it was not successful.
$filter=groupTypes/any(c:c not eq 'Unified') and securityEnabled eq true
$filter=not groupTypes/any(c:c eq 'Unified') and securityEnabled eq true
$filter=not groupTypes/any() and securityEnabled eq true
$filter=groupTypes.Length eq 0 and securityEnabled eq true

Can you provide an example for getting all security groups?
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#select-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Apologies @xdmushui for the delayed response.

A working query would be:

[Try in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=groups%3F%24filter%3D(NOT%20groupTypes%2Fany(c%3Ac%20eq%20'Unified'))%20and%20securityEnabled%20eq%20true%26%24count%3Dtrue&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com&headers=W3sibmFtZSI6IkNvbnNpc3RlbmN5TGV2ZWwiLCJ2YWx1ZSI6ImV2ZW50dWFsIn1d) `https://graph.microsoft.com/v1.0/groups?$filter=(NOT groupTypes/any(c:c eq 'Unified')) and securityEnabled eq true&$count=true` 

Of note: this query uses the `NOT `operator which works only when you specify the **ConsistencyLevel** header set to `eventual` and the `$count` query parameter.
