### ISSUE TITLE
Places endpoint not found in msgraph-sdk-java even though used in documentation

### ISSUE THREAD

**Issue by kmichae1** [microsoftgraph/microsoft-graph-docs#8474]
Where can I find a version for the java sdk with the "places" method? The documentation tells you to use this method, which can not be found in version 1.7.1.

graphClient.places()

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b836740-9263-12cc-9001-c61f08448f0d
* Version Independent ID: 4a5b79f8-d685-6c86-d7ed-12d7c5d309cb
* Content: [List places - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/place-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/place-list.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hey @kmichae1 
Thanks for reaching out and for your patience.
This collection was added to the sdk with version 1.8.0.
https://github.com/microsoftgraph/msgraph-sdk-java/blame/2c6e50743a478bf8b48342fed28166100a75093b/src/main/java/com/microsoft/graph/requests/extensions/BaseGraphServiceClient.java#L628
Closing
