### ISSUE TITLE
People Picker from Microsoft graph API toolkit is not working - Create React App

### ISSUE THREAD

**Issue by er-parag91** [microsoftgraph/microsoft-graph-docs#8481]
I am using msal authentication same as this example [microsoft-authentication-library-for-js](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/react-sample-app/src/AuthProvider.js) login page. Once you are logged in I am redirecting to page where I have People picker component. That component code is something like down below. My front end client is React. I am using NPM package ```"@microsoft/mgt": "^1.3.0-preview.2"``` for people picker and ```"msal": "^1.3.0"``` for logging in user

```
    import React, { useState, useRef } from 'react';

    
    import '@microsoft/mgt';

    const PeoplePicker = props => {

          // reference to access mgt-people-picker on DOM
          const peoplePicker = useRef();

          return (
             <div>
                <mgt-msal-provider client-id={process.env.REACT_APP_DEV_AZURE_APP_CLIENT_ID} />
                <mgt-people-picker ref={peoplePicker} />
             </div>
          )

    }
```

As I start typing People Picker is not getting any list of people from our organization AD. I checked Network tab in console, there is no network calls made as you type in this input. It's not throwing error so I assume Provider is working but it could be issue of having session or token attached to people picker though I am not completely sure How would I do that. 

I browsed microsoft docs, github issues etc. but it didn't help either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20833be3-9f0c-0e13-b107-45df6f38944b
* Version Independent ID: 7aefbf92-5842-c84d-c38d-507495a9b970
* Content: [People-Picker component - Microsoft Graph](https://docs.microsoft.com/en-us/graph/toolkit/components/people-picker)
* Content Source: [concepts/toolkit/components/people-picker.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/toolkit/components/people-picker.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @vogtn
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by nmetulev** [comment]
Looks like this issue no longer repros in the latest version of mgt. I'll go ahead and close this issue
