### ISSUE TITLE
Please expand on the meaning of "UploadState" for MobileApp model

### ISSUE THREAD

**Issue by JakeLunn** [microsoftgraph/microsoft-graph-docs#8490]
The "UploadState" description is simply "the upload state" which is unhelpful... especially since it's an Int32 value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e35d5cf-90e5-b225-1782-c725672da529
* Version Independent ID: acba9305-4bc4-6672-280c-bbc086586152
* Content: [mobileApp resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-shared-mobileapp?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-shared-mobileapp.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-shared-mobileapp.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thank you for the feedback.  We'll work to get that updated in the next update cycle or two.

**Comment by lramosvea** [comment]
@triplanedave any update on this? Thanks.

**Comment by triplanedave** [comment]
Details are here: resultantAppStateDetail enum type - Microsoft Graph beta | Microsoft Docs<https://docs.microsoft.com/en-us/graph/api/resources/intune-apps-resultantappstatedetail?view=graph-rest-beta>
