### ISSUE TITLE
importance property does not work for creating a chat message

### ISSUE THREAD

**Issue by dnpatil2** [microsoftgraph/microsoft-graph-docs#8491]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96c52956-2c53-b7c9-755e-6692535564cf
* Version Independent ID: 239f980c-8c36-57d9-b6db-3417ad3db5da
* Content: [chatMessage resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/chatmessage.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Abhijit-MSFT** [comment]
@dnpatil2, can you please what request body you are sending for Post request.
it is working fine for me.

**Comment by dnpatil2** [comment]
Seems to be working now. BTW following is the request body which I was using earlier as well as the one which I tried today.

```
{
    "body": {
        "content": "Hello World - Important message"
    },
    "importance": "high"
}
```

**Comment by Abhijit-MSFT** [comment]
It works...

**Comment by dnpatil2** [comment]
Yes, when I had logged the issue, it was not working.
