### ISSUE TITLE
Incorrect values in the throttling table

### ISSUE THREAD

**Issue by AkJo** [microsoftgraph/microsoft-graph-docs#8494]
Any Graph API calls for Microsoft Teams not called out below | ~~15000~~ 600 requests every 10 seconds | ~~n/a~~ 6000 requests every 10 seconds
-- | -- | --

GET ~~/teams/{team-id},~~ joinedTeams | 30 rps | 300 rps
-- | -- | --

Please contact anandjo for any clarifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling#microsoft-teams-service-limits)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
@FaithOmbongi could you please take a look at this issue?

**Comment by FaithOmbongi** [comment]
Hi @lramosvea , leaving the assignment to the Teams group - @AkJo and @nkramer - to update the article with the correct throttling information.

**Comment by lramosvea** [comment]
Hi @AkJo could you take a look at this issue. The doc that needs to be updated is https://docs.microsoft.com/en-us/graph/throttling-limits

**Comment by Nivedipa-MSFT** [comment]
@AkJo - Could you please share any update here.
