### ISSUE TITLE
Add tab to 1-1 chat in MS Teams 

### ISSUE THREAD

**Issue by bijaykush** [microsoftgraph/microsoft-graph-docs#8501]
Hi, it seems like we can only create a tab in channels of a team's programmatically through MS Graph API. I am looking to create a tab programmatically in a 1-1 chat. Is this supported? If not then is there any workaround available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0778483f-34bc-b383-abfa-99c8d97429e2
* Version Independent ID: 6882946c-c210-29ec-e776-caf8af03c716
* Content: [Add tab to channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamstab-add?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamstab-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamstab-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jaime-olivares** [comment]
Alternatively, assuming that it is not possible to create the tab programmatically, is it possible to re-configure the tab (i.e. a Website tab, for changing the URL)

**Comment by Nikitha-MSFT** [comment]
Currently we don't have any API to add tab to 1:1 chat. Could you  please raise a user voice [here](https://microsoftteams.uservoice.com/)?
