### ISSUE TITLE
Unable to identify type of data in Octet-Stream

### ISSUE THREAD

**Issue by kevit-parth-mansata** [microsoftgraph/microsoft-graph-docs#8506]
I managed to get the response in the form of octet-stream but I don't know to which format does it need to be converted to play the recording of the file. Can anyone please provide the steps to convert the stream into the file? I'm using Node.js(v 11.12.0) as a language here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81b70a1-7507-bea3-0740-c2db706f32b4
* Version Independent ID: 813d4f21-2eff-5dd2-451e-311565c5f597
* Content: [call: recordResponse - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/call-record?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/call-record.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/call-record.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Perustaja** [comment]
I am having this issue too, [this SO post](https://stackoverflow.com/questions/68123352/how-to-receive-a-converted-file-from-microsoft-graph-api) describes my issues. How can we handle the returned stream or the returned data if we manually make the call? I must be missing something in the header or something.
