### ISSUE TITLE
The method put(Team) is undefined for the type ITeamRequest

### ISSUE THREAD

**Issue by RonakJain7** [microsoftgraph/microsoft-graph-docs#8511]
Error : The method put(Team) is undefined for the type ITeamRequest

Team team = new Team();
          TeamMemberSettings memberSettings = new TeamMemberSettings();
          memberSettings.allowCreateUpdateChannels = true;
          team.memberSettings = memberSettings;
          TeamMessagingSettings messagingSettings = new TeamMessagingSettings();
          messagingSettings.allowUserEditMessages = true;
          messagingSettings.allowUserDeleteMessages = true;
          team.messagingSettings = messagingSettings;
          TeamFunSettings funSettings = new TeamFunSettings();
          funSettings.allowGiphy = true;
          funSettings.giphyContentRating = GiphyRatingType.STRICT;
          team.funSettings = funSettings;

          **graphClient.groups("{id}").team().buildRequest().put(team);**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf38bbfb-04cd-17ae-b61e-371816ab987f
* Version Independent ID: c2165d6a-a317-6292-32e6-ad67b4fd3faf
* Content: [Create team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-put-teams.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-put-teams.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment]
Hi @RonakJain7 , Are you able to resolve this issue? Can you please confirm if You are still facing it?

**Comment by RonakJain7** [comment]
No. Library does not have put(Team) method. (using java sdk)
`graphClient.groups("{id}").team().buildRequest().put(team);`

**Comment by Subhasish-msft** [comment]
Hi @RonakJain7 , I have created a bug for this and will be tracking it internally.

**Comment by ChetanSharma-msft** [comment]
Hello @RonakJain7 - Sorry for delay in response.
We will check the updates on the bug and let you know.

**Comment by ChetanSharma-msft** [comment]
Hello @RonakJain7 - We are actively checking the updates with engineering team and let you know.
Sorry for the inconvenience.

**Comment by Meghana-MSFT** [comment]
Update : The bug has been fixed and we were able to call the PUT method using the latest GA version of the Java SDK:

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/81138249/4c9e248b-cdba-4720-9a9d-0e19af15b527)

![image](https://github.com/microsoftgraph/microsoft-graph-docs/assets/81138249/fa2019f1-8843-4bef-a2a2-0448f3ab8298)
