### ISSUE TITLE
URLs for manipulating appRoles

### ISSUE THREAD

**Issue by et1975** [microsoftgraph/microsoft-graph-docs#8513]
I don't see any url specification for accessing and manipulating appRole assignments anywhere.

For example, here's a corresponding URL specification for accessing servicePrincipal role assignments using Azure Graph API:
`https://graph.windows.net/{tenant-name}.onmicrosoft.com/servicePrincipals/{principal-id}/appRoleAssignments?api-version=1.6`

How would I access the same resource using Microsoft Graph API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ba2d096-43e1-c42d-a258-e31f76d2c5f2
* Version Independent ID: de382dbd-ef59-9a2e-dad0-aefd5f97555b
* Content: [appRoleAssignment resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/approleassignment?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/approleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/approleassignment.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @psignoret
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by psignoret** [comment]
On a **user**, **group**, or **servicePrincipal**, you can query the **appRoleAssignments** navigation to see the app roles which have been granted to the user, group or service principlal:

* [`GET /v1.0/users/{id}/appRoleAssignments`](https://docs.microsoft.com/graph/api/user-list-approleassignments?view=graph-rest-1.0)
* [`GET /v1.0/groups/{id}/appRoleAssignments`](https://docs.microsoft.com/graph/api/group-list-approleassignments?view=graph-rest-1.0)
* [`GET /v1.0/servicePrincipals/{id}/appRoleAssignments`](https://docs.microsoft.com/graph/api/serviceprincipal-list-approleassignments?view=graph-rest-1.0)

On a **servicePrincipal**, you can also query **appRoleAssignedTo** to query all app role assignments granted to users, groups or service principals, for the resource service principal:

* [`GET /v1.0/servicePrincipals/{id}/appRoleAssignedTo`](https://docs.microsoft.com/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0)

Each of these also have a POST and DELETE counterpart, though the recommendation is to always POST and DELETE through the resource service principal's **appRoleAssignedTo** collection.

Does this help answer you question?

**Comment by et1975** [comment]
Thanks!
