### ISSUE TITLE
Event as an online meeting cannot be created via Java SDK

### ISSUE THREAD

**Issue by AnatoliiBobakTR** [microsoftgraph/microsoft-graph-docs#8521]
Hello

In the document mentioned that we are able to create an online meeting via SDK (Java) and we just needed to use the following:

```
event.isOnlineMeeting = true;
event.onlineMeetingProvider = OnlineMeetingProviderType.TEAMS_FOR_BUSINESS;
```

So, I added the latest version of the SDK to my project, but I don't see those fields and Enum "OnlineMeetingProviderType". 

I used 1.7.1 version.
What am I doing wrong? Should I use another version or these features weren't released yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4156ca1c-a519-c562-8d6e-383975ce918e
* Version Independent ID: 87fbaaf5-67fa-7eac-b765-f01d06114a4a
* Content: [Create Event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-events.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
@darrelmiller 
Kindly comment if SDK issue.

**Comment by baywet** [comment]
Hey @AnatoliiBobakTR 
Thanks for reaching out and thanks for your patience.
The enum was added with version 1.8.0 of the SDK. https://github.com/microsoftgraph/msgraph-sdk-java/blob/dev/src/main/java/com/microsoft/graph/models/generated/OnlineMeetingProviderType.java
Closing.
