### ISSUE TITLE
driveItem.additionalDataManager().put("@microsoft.graph.conflictBehavior", new JsonPrimitive("rename")); not working in java sdk version 1.6 t0 1.7.1

### ISSUE THREAD

**Issue by vikasprabhakar** [microsoftgraph/microsoft-graph-docs#8524]
[Enter feedback here]
in create folder api call using java sdk, the content "@microsoft.graph.conflictBehavior", new JsonPrimitive("rename")) is not added in request payload

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9069032a-3cb9-37df-9ef5-3901aad572e0
* Version Independent ID: 37fce8f3-cd7c-2450-b1ee-95956653d179
* Content: [Create a new folder - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-post-children?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/driveitem-post-children.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-post-children.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by baywet** [comment]
Hey @vikasprabhakar 
Thanks for reaching out.
This has been discussed and addressed in this issue https://github.com/microsoftgraph/msgraph-sdk-java/issues/468
2.3.2 contains the fix.
Closing.
