### ISSUE TITLE
Removing a member from a channel problem

### ISSUE THREAD

**Issue by brian-rose-sp** [microsoftgraph/microsoft-graph-docs#8525]
[Enter feedback here]
I am trying to remove a member from a channel.  The documentation states that I can do this with the unique user id.  When I add the user to the channel, I am using the user's GUID but it fails when attempting to remove.  

**<beta_url>/teams/<teamId>/channels/<channel_id>/members/<*userId*>

I am however able to remove a user from a channel if I use the Base64 aadConversationMember id.  I decoded it an see that it is nothing more than the {channelId}##{userId}

I suppose I could build the Base64 encoding myself, but I couldn't find documentation on that and seems like an unnecessary step. 

So, is this correct?  It seems I should be able to remove the user from the channel since the URL has the DELETE request has the channelID and the /member/{id} where {id} would be the userId, not the aadConversationMember id.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8be65b6e-9e69-205c-cf67-44b433dfeca7
* Version Independent ID: 770ecfc4-e9a5-cafc-e170-e281a60c1cd1
* Content: [conversationMember resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/conversationmember.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
Hi @brian-rose-sp , In order to remove a member from Team or Private Channel, you need to use {membership-id} instead of {userId}.
1. To remove any member from private channel use the below request:
    `DELETE /teams/{team-id}/channels/{channel-id}/members/{membership-id}`
2. To remove any member from a Team use below endpoint:
    `DELETE /teams/{team-id}/members/{membership-id}`

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
