### ISSUE TITLE
Cannot retrieve the "CreatedOnBehalfOf" relationship setting

### ISSUE THREAD

**Issue by m365ken** [microsoftgraph/microsoft-graph-docs#8528]
I want to utilize the "CreatedOnBehalfOf" relationship [setting](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#relationships). I can successfully set this parameter right after the group is created. However, I'm unable to retrieve the setting using a basic Get call to the group. Even if I attempt to filter for it using the select keyword nothing is returned for that paramter. Thx
https://graph.microsoft.com/v1.0/groups/groupGuid?$select=displayname,createdonbehalfof
Response:
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#groups(displayName,createdOnBehalfOf)/$entity",
    "displayName": "mygroup_displayName"
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52e064c0-4789-0ec7-1e7c-c36519049ffd
* Version Independent ID: aa0adc0e-5c50-3a2f-ab01-152f8f3d92e3
* Content: [Get group - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-get.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@m365ken createdOnBehalfOf is not a property on group entity and thus can't be retrieved with $select in the way you specified. Try $select=displayName, id - this would work, as id is a property on group. Closing this issue as it is not a document issue. Please ask your question on stackoverflow.microsoft.com, if you need further assistance. Thank you!

**Comment by m365ken** [comment]
Hey @yyuank 
Thanks for the quick response. If I $select=id I get the id of the group, not the value for createdOnBehalfOf. Maybe I'm not understanding this property fully. What is the advantage of having/setting this property but not being able to retrieve it? Thanks
