### ISSUE TITLE
Ordering of pages - Conditional Access

### ISSUE THREAD

**Issue by jason-ra** [microsoftgraph/microsoft-graph-docs#8535]
Viewing **LIST** page for Conditional Access \ Named Location redirects to List page under **Country named location**.  Suggest LIST and CREATE pages under "Country named location" should be under the parent Named Location as they don't only relate to Country. Or other re-sorting of these pages required to make it clearer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4bab884-b637-dcc7-ac64-fff82a1eb97f
* Version Independent ID: a51a0a37-886c-91d6-ff00-99de5a4811c8
* Content: [List namedLocations - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-list-namedlocations?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conditionalaccessroot-list-namedlocations.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conditionalaccessroot-list-namedlocations.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @jason-ra for your feedback. Yes, you're right — the **namedLocation** resource exposes both **ipNamedLocation** and **countryNamedLocation** object types. We'll review the TOC and raise a fix to make this clearer.

Closing this issue for now.
