### ISSUE TITLE
C# example is wrong

### ISSUE THREAD

**Issue by kuralex1** [microsoftgraph/microsoft-graph-docs#8545]
Hi guys,

I am using Microsoft.Graph.dll v3.6.0 and there is no **CallRecords** collection.

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var callRecord = await graphClient.Communications.**CallRecords**["{id}"]
	.Request()
	.GetAsync();

Thanks,
Alex
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd76e0a9-874e-1e5e-7238-77247a020064
* Version Independent ID: 08963ed9-21ee-773d-3532-75be9cd57e70
* Content: [Get callRecord - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/callrecords-callrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/callrecords-callrecord-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
Normally there is a small amount of lag time between an API being published and the SDK being published. However in our case, we are aware of some SDK limitations delaying availability a little bit longer.

@darrelmiller Do you have any ETA on when we could see an SDK that includes CallRecords?

**Comment by smithmart** [comment]
Hello,

Came to report the same issue, for V3.7.0 of the client

**Comment by darrelmiller** [comment]
@stephenjust Adding support for namespaces is being worked on currently.  It is going to be at least a few more weeks before being ready.

**Comment by davidjrh** [comment]
I'm currently using 0.25.0-preview and seems that this has now been included. Thanks!!!

**Comment by stephenjust** [comment]
I can confirm that the C# sdk does have the needed models in it now. We'll re-enable examples in the docs after the SDK comes out of preview.
