### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by michevnew** [microsoftgraph/microsoft-graph-docs#8546]
With the IdentityRiskEvents endpoint being deprecated, are there plans to change the name of the permission required to query this data, as to align it with the actual endpoint? Or will it stay as 
IdentityRiskEvent.Read.All?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3001f30-1059-6cec-741c-c62ba8e94aa4
* Version Independent ID: d1a7d0c5-5e46-4010-bf83-da43abdfc896
* Content: [List riskDetection - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/riskdetection-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/riskdetection-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/riskdetection-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cloudhandler** [comment]
The plan is to keep the permission the same
