### ISSUE TITLE
What permissions are needed for GET /users/{user-id}/chats?$filter=installedApps/any(a:a/teamsApp/id eq '{teamsAppid}')

### ISSUE THREAD

**Issue by GauravES** [microsoftgraph/microsoft-graph-docs#8550]
GET /users/{user-id}/chats?$filter=installedApps/any(a:a/teamsApp/id eq '{teamsAppid}')
Is this currently expected to work for anyone other than the user authenticated to use graph? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4690677-2b12-0d63-06db-45172132f540
* Version Independent ID: 129f7f1f-78c4-4e80-2eac-f0ce7619f231
* Content: [Proactive messaging using a bot in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-proactive-messaging)
* Content Source: [concepts/teams-proactive-messaging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-proactive-messaging.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prithvi-MSFT** [comment]
Hi @GauravES ,
Since this API supports only delegated permissions only the user's with the required permissions will be able to use this API. You can get more information on permissions from below link
https://docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-1.0&tabs=http#permissions

Thanks

**Comment by v-chetsh** [comment]
We are closing this issue for now, Please feel free to reopen it, if required.
