### ISSUE TITLE
createdDateTime and lastModifiedDateTime Incorrect

### ISSUE THREAD

**Issue by clsmit12** [microsoftgraph/microsoft-graph-docs#8551]
Whenever making a ms graph call to one of the profile relationships (ex: https://graph.microsoft.com/beta/users/{user email}/profile/{profile relationship}), the createdDateTime and lastModifiedDateTime that is returned is incorrect- the date that is returned is the current date/time that he call was made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba12e15-4ac1-c0c2-ee37-23e84b6dba14
* Version Independent ID: 4a43deca-3890-cf08-2f59-c223a8c00fd3
* Content: [profile resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/profile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/profile.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PeterChencha** [comment]
Hello @clsmit12 thanks for reaching out. We could not replicate this issue, kindly confirm if you are still facing this problem.
