### ISSUE TITLE
Need clarify that the parameters are

### ISSUE THREAD

**Issue by Nepomuceno** [microsoftgraph/microsoft-graph-docs#8569]
Not clear what resource Id  refers to when activating a role and the example talks about usernames but them put ids in the values. would be useful to know which Id maps to which username or rolename.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0926dfc7-4119-849b-cce6-428d14b310ef
* Version Independent ID: e34cdb5e-9682-1321-bc32-495801540df5
* Content: [Create governanceRoleAssignmentRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/governanceroleassignmentrequest-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/governanceroleassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/governanceroleassignmentrequest-post.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
To verify all the parameters used in the API, review the guiding **governanceRoleAssignmentRequest** resource page: https://docs.microsoft.com/en-us/graph/api/resources/governanceroleassignmentrequest?view=graph-rest-beta 

In this case, the user names or mail are shared to help you get the `subjectId`; while the role names (Azure RBAC roles e.g. owner) are shared to link you with the `roleDefinitionId`.

No updates identified for the page. Closing the issue.
