### ISSUE TITLE
Add time frame to page documentation

### ISSUE THREAD

**Issue by wonderplayer** [microsoftgraph/microsoft-graph-docs#8571]
[Enter feedback here]
There is no information on page of delta timeline.
It would be great, if you could add this information on this page - what is the default timeline and can it be modified with request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @wonderplayer 
Thanks for reaching out. I'm not sure I understand the suggestion. What do you mean by timeline?

**Comment by wonderplayer** [comment]
Hi @baywet 
By time line I meant, time when event occurred.
For example, I'd like to get delta for past week.

**Comment by baywet** [comment]
delta always starts from the "beginning" meaning that you get the all changes, from the first one ever made for the resource, when you start a delta sequence. (query with no token).
Delta does not support filtering items at this time. 
The only [exception is for calendar events](https://docs.microsoft.com/en-us/graph/api/event-delta?view=graph-rest-1.0&tabs=http) where you need to specify a start and end datetime to get the sync.

**Comment by wonderplayer** [comment]
Cool! Thank you for explanation :)
Could you please then put this information on page, so next poor guy like me won't bother you?

**Comment by baywet** [comment]
https://github.com/microsoftgraph/microsoft-graph-docs/pull/8573
