### ISSUE TITLE
Could you please be more specific on what kind of "Personal data" this permission "user.export.all" allows exporting ? 

### ISSUE THREAD

**Issue by YassineSOUABNI** [microsoftgraph/microsoft-graph-docs#8572]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4383252f-b890-bc67-2bbe-8c635c5a637c
* Version Independent ID: 59d522c3-60a2-89c0-19b4-e17134502aa0
* Content: [user: exportPersonalData - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-exportpersonaldata?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-exportpersonaldata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-exportpersonaldata.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
We update this doc to provide more info and examples. Closing this issue.
