### ISSUE TITLE
Wrong example for C# "Add multiple members to a group in a single request"

### ISSUE THREAD

**Issue by Rafaelki** [microsoftgraph/microsoft-graph-docs#8589]
In C#, the example 2 is exactly the same as the example 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
@davidmu1  could you please help take a look? The code with reported issues was auto-generated.

**Comment by davidmu1** [comment]
The examples look to be correct now. No change identified for the page. Closing the issue.
