### ISSUE TITLE
PIM documentation on AAD roles is outdated. Please fix

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#8590]
[Enter feedback here]

see my comment below about outdated content
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8979cb9d-0fb7-2d29-bd6b-84b61e3eae4b
* Version Independent ID: de960bdc-feee-8c12-184e-515f0b59213b
* Content: [List privilegedRoles - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/privilegedrole-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/privilegedrole-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/privilegedrole-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bachoang** [comment]
I believe the documentation on PIM AAD roles are no longer accurate.  Please check all pages in this section and update documentation.

Example:
List privileged roles - outdated

https://docs.microsoft.com/en-us/graph/api/privilegedrole-list?view=graph-rest-beta&tabs=http

 

GET https://graph.microsoft.com/beta/privilegedRoles

 

{
"error": {
"code": "TenantEnabledInAadRoleMigration",
"message": "The current endpoints of AAD roles have been disabled for the tenant for migration purpose. Please use the new Azure AD RBAC roles. Please refer to https://aka.ms/PIMFeatureUpdateDoc for new PIM features; https://aka.ms/PIMAPIUpdateDoc for API and PowerShell changes because of migration.",
"innerError": {
"request-id": "43f76855-3e35-4b58-a70b-a01f1d8fc56f",
"date": "2020-05-29T22:43:10"
}
}
}
The documentation should match the API changes section in https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/azure-ad-roles-features

I believe the correct request should be:
GET https://graph.microsoft.com/beta/privilegedAccess/aadRoles/resources/<Directory ID>/roleDefinitions

**Comment by FaithOmbongi** [comment]
Thank you for the feedback. Yes, this is an outdated documentation and we're working on making the latest docs as per the new PIM experience available soon. 

No updates identified for this page. Closing the issue.
