### ISSUE TITLE
This page says the id is a GUID-type id but graph actually returns a string

### ISSUE THREAD

**Issue by read-0nly** [microsoftgraph/microsoft-graph-docs#8594]
https://github.com/microsoft/Intune-PowerShell-SDK/issues/81 has these details too, I assumed it was the modules that were broken. Graph explorer shows the same though.

The response section of the docs says the ID should be a UID: https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancepolicysettingstatesummary-get?view=graph-rest-1.0#response-1
```
{
  "value": {
    "@odata.type": "#microsoft.graph.deviceCompliancePolicySettingStateSummary",
    "id": "7474d6d5-d6d5-7474-d5d6-7474d5d67474",
    "setting": "Setting value",
    "settingName": "Setting Name value",
    "platformType": "iOS",
    "unknownDeviceCount": 2,
    "notApplicableDeviceCount": 8,
    "compliantDeviceCount": 4,
    "remediatedDeviceCount": 5,
    "nonCompliantDeviceCount": 7,
    "errorDeviceCount": 0,
    "conflictDeviceCount": 3
  }
}
```

This is what gets returned when running https://graph.microsoft.com/v1.0/deviceManagement/deviceCompliancePolicySettingStateSummaries or https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicySettingStateSummaries

```
{
	"id": "DefaultDeviceCompliancePolicy.RequireDeviceCompliancePolicyAssigned",
	"setting": "DefaultDeviceCompliancePolicy.RequireDeviceCompliancePolicyAssigned",
	"settingName": "DefaultDeviceCompliancePolicy.RequireDeviceCompliancePolicyAssigned",
	"platformType": "all",
	"unknownDeviceCount": 0,
	"notApplicableDeviceCount": 0,
	"compliantDeviceCount": 7,
	"remediatedDeviceCount": 0,
	"nonCompliantDeviceCount": 0,
	"errorDeviceCount": 0,
	"conflictDeviceCount": 0
}
```

https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicySettingStateSummaries/DefaultDeviceCompliancePolicy.RequireDeviceCompliancePolicyAssigned and https://graph.microsoft.com/v1.0/deviceManagement/deviceCompliancePolicySettingStateSummaries/DefaultDeviceCompliancePolicy.RequireDeviceCompliancePolicyAssigned both fail, suggesting that's not the ID that should be provided

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52ac455-81ba-93cf-c436-765b13c04574
* Version Independent ID: 378297d6-1adb-e92e-b396-cc03e6c61d2f
* Content: [List deviceComplianceSettingStates - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-deviceconfig-devicecompliancesettingstate-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-deviceconfig-devicecompliancesettingstate-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-deviceconfig-devicecompliancesettingstate-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by read-0nly** [comment]
I realize this is a technical issue, but if you could just have this flagged or confirm that this is normal behavior I'll be happy to close this.

**Comment by triplanedave** [comment]
Thanks, I've asked one of our engineers to take a look.  I'm not sure if it's normal - seems like most ID's are GUIDs rather than strings, so we'll get clarification.

**Comment by read-0nly** [comment]
Many thanks!

**Comment by lramosvea** [comment]
@triplanedave any update on this issue? Is it resolved now? Thanks

**Comment by triplanedave** [comment]
The response is correct with the non-GUID type ID.  If you refer to https://docs.microsoft.com/en-us/graph/api/resources/intune-deviceconfig-devicecompliancesettingstate?view=graph-rest-1.0 you'll see that it's simply a "key of the entity" which doesn't necessarily require it to be a GUID.  So, you're welcome to close this issue.
