### ISSUE TITLE
how can i get the all exceptions of a seriesMaster event include exception and deleted occurrence

### ISSUE THREAD

**Issue by hxt1994** [microsoftgraph/microsoft-graph-docs#8597]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c927daf-9a45-a43a-2fae-5cec36564ea9
* Version Independent ID: 3af032d0-3e89-1b6c-be38-0da1e580d2e9
* Content: [List calendarView - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/calendar-list-calendarview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/calendar-list-calendarview.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Hi,
Please check out two properties cancelledOccurrence and exceptionOccurrence that is available on MS-Graph beta now:
https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta
