### ISSUE TITLE
Access external shared 

### ISSUE THREAD

**Issue by mrdang1407** [microsoftgraph/microsoft-graph-docs#8598]
Hi,

I'm using One drive for Business. The" https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true" returns a list of folders (remoteItem), and I try to access this folders.
The "allowexternal=true" makes the requests returns external shares (across domains shares).
But when i access drives external shared by :
/drives/{driveId}/items/{itemId}
It return error : ItemNotFound.
How can i access the item shared externally and upload file or folder to it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f9ff916-e1b7-c60b-bf05-2c5976617ad7
* Version Independent ID: 092666d9-dfd3-44f9-9571-bc67f45c4842
* Content: [List Files Shared With Me - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/drive-sharedwithme?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/drive-sharedwithme.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/drive-sharedwithme.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by ganga-sah** [comment]
@mrdang1407 I was looking for solution to #8222 and was happy to see from your comment above that "allowexternal=true" makes the requests returns external shares (across domains shares). Unfortunately this also doesn't return external sharings even if I can see them in OneDrive UI. Can you please share your REST URL with response that include external sharings in response? I tried following URL that included **only** internal sharing:
https://graph.microsoft.com/v1.0/users/user1@mydomain.com/drive/sharedWithMe?allowexternal=true

**Comment by DavicVictor** [comment]
Hello ! I am having the same problem. Do you know when this will be fixed ? Have you find a workaround ?

**Comment by ganga-sah** [comment]
As in previous post, workaround for me was to to pass allowexternal=true in query param of the API.

**Comment by JeremyKelley** [comment]
The external item possibly lives in a tenant other than the one you've currently got an access token for.  You should check the tenantId parameter in the SharePointIds facet to see if it's the ID of the current tenant or a different one to validate.

**Comment by zorzigio** [comment]
Encountering the same issue here.

The resource I am trying to access is located in another organisation. 

I can list the items shared with me using ```https://graph.microsoft.com/v1.0/me/drive/sharedwithme?allowexternal=true```, however when I try to access the content of a folder with ```https://graph.microsoft.com/v1.0/drives/{driveId}/items/{itemId}``` I get ```itemNotFound``` error.

I also tried to append ```https://graph.microsoft.com/v1.0/drives/{driveId}/items/{itemId}?allowexternal=true``` but the error persists.

If I can list the folder I should also be able to get the content through the API right?

Any way to get around this?
