### ISSUE TITLE
get all sensitivity label example does not seem to be working

### ISSUE THREAD

**Issue by harp365** [microsoftgraph/microsoft-graph-docs#8602]
[GraphSensitivityLabelsIssue.docx](https://github.com/microsoftgraph/microsoft-graph-docs/files/4736475/GraphSensitivityLabelsIssue.docx)

Hi, sorry as I know this is in Beta and sorry in advance if this is the wrong place to raise this as it is not an issue with the doc as such but more the running of the rest call itself.

Please see attached doc for further info but basically I am unable to get any of the Graph API calls relating to retrieving sensitivity labels to work.

Thanks in advance,

Henry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91fdbdd5-048d-25b8-5421-f428ee57318c
* Version Independent ID: eea23b67-74d5-9093-4470-dba18eeedc6b
* Content: [Get informationProtectionLabel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/informationprotectionlabel-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/informationprotectionlabel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/informationprotectionlabel-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @tommoser
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tommoser** [comment]
Hi Henry, 

It looks like you're trying to use the tenant endpoint rather than the /me endpoint. Can you try to use this instead and let me know the result?

https://graph.microsoft.com/beta/me/informationprotection/policy/labels

**Comment by harp365** [comment]
That worked perfectly this time, thanks!
