### ISSUE TITLE
MS Graph user endpoint does not return MS Graph open extension and schema extension

### ISSUE THREAD

**Issue by bachoang** [microsoftgraph/microsoft-graph-docs#8604]
GET https://graph.microsoft.com/beta/users/UPN or ObjectId does not contain open extension and schema extensions on the user even though they all have valid values.  The only extension values this endpoint returns is Directory Schema created via AAD Graph.  Refer to ICM 186302720 for more info on the thread discussion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d24b1d9-ee3e-32ca-5c86-aebef8f09a85
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by bachoang** [comment]
To be clear I am referring to open extension documented here:  https://docs.microsoft.com/en-us/graph/extensibility-open-users

and schema extension here:  https://docs.microsoft.com/en-us/graph/extensibility-schema-groups

**Comment by krbain** [comment]
This is a feature request to update the user API to return additional values for Graph schema extensions. We will need to explore this request further. No doc update needed. Closing the issue.
