### ISSUE TITLE
Does this api actually exist for customers to use?

### ISSUE THREAD

**Issue by robstove** [microsoftgraph/microsoft-graph-docs#8608]
We are looking to use the InTune graph api to create managedDevices from our datasets. While attempting to use this api from the graph explorer we are receiving a "POST not supported" response. Can someone clarify?

fyi: We have a valid InTune license.

Cheers,
-rob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04504a62-d768-a27c-d4f9-64092a6b2edd
* Version Independent ID: 29741af4-f851-5a0c-3eca-c836120f5172
* Content: [Create managedDevice - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-create?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by robstove** [comment]
Appears to be a dup of https://github.com/microsoftgraph/microsoft-graph-docs/issues/5321.

**Comment by triplanedave** [comment]
No, there is not a way to create a new managed Device.  You must enroll a device to have the managed device object get created.
