### ISSUE TITLE
SignInActivity attribute no longer returns a valid skip token

### ISSUE THREAD

**Issue by ChrisB9907** [microsoftgraph/microsoft-graph-docs#8612]
Selecting the SignInActivity attribute is no longer returning valid skip tokens.
When the command is run it returns that the NextPageRequest method doesn't return a valid skip token.

Language used: C#

command used: 
```
var temp = await client.Users
                    .Request()
                    .Select("SignInActivity")
                    .GetAsync();
                if (temp.NextPageRequest != null)
                {
                   var currentPage = await temp.NextPageRequest.GetAsync();
                }
```
 

Odata shows the following:
`{[@odata.nextLink, https://graph.microsoft.com/beta/users?$select=SignInActivity&$skiptoken=X%27445370740200010000001E3A612D6D6F686F736E406F6666696365333635737570706F72742E636F6D29557365725F37663366326262362D333664632D343336622D396164622D376464373163346163326130B900000000000000000000%27]}`

putting the above into https://developer.microsoft.com/en-us/graph/graph-explorer returns the following 

`{
    "error": {
        "code": "",
        "message": "Invalid Skip Token",
        "innerError": {
            "request-id": "2388bbdd-abef-4adf-801f-dff0ea741fca",
            "date": "2020-06-06T01:47:39"
        }
    }
}`

The error does not happen when selecting other attributes using Select, for example UserPrincipalName doesn't return an error.

There has been no changes to the code of the program that has been running for weeks now with no issues. It stopped working between 12:20 am on 6/3/2020 and 12:20 am on 6/4/2020. This seem to say that something was changed on the API side of things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a0f258b-b61e-72a2-0caf-d9b7fff5857d
* Version Independent ID: 90c2edf2-51ee-6bab-84a6-3710a3f0ccd2
* Content: [signInActivity resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signinactivity?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/signinactivity.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signinactivity.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by tosokr** [comment]
I have the same issue. Is there any workaround available?

**Comment by jachrist** [comment]
I also struggle with this, calling Graph from Azure Logic Apps and using the built-in pagination.
It only happens with the beta api, but I need attributes that are not available in v1.0.

**Comment by thuld** [comment]
Same problem when using PowerShell:

````
$baseUrl = 'https://graph.microsoft.com/beta/users'
$selectQuery = 'select=displayName,userPrincipalName, mail, id, CreatedDateTime, signInActivity, UserType'
$uri = "{0}?`${1}&`$top=999" -f $baseUrl, $selectQuery

do {
  $signInData = (Invoke-RestMethod -Uri $uri -Headers $Headers -Method 'GET' -ContentType "application/json") 
    
  ## only considers those sign-ins that belongs to members, not for GUEST users
  $memberSignInData = $signInData.Value | Where-Object { $_.UserType -eq 'Member'}

  foreach($sign in $memberSignInData) {

     if($sign.SignInActivity.LastSignInDateTime) {

            $lastSignInDate = (Get-Date($sign.SignInActivity.LastSignInDateTime)).ToString('yyyy-MM-dd')
            $userSignIns.Add([String]$sign.UserPrincipalName, $lastSignInDate) 
     }
  }

  $nextLink = $SignInData.'@Odata.NextLink'
  $uri = $nextLink
}
while($null -ne $nextLink)
````

**Comment by anarii** [comment]
This was working fine before, but now getting the same error here when querying the SignInActivity with https://graph.microsoft.com/beta/users endpoint:

```
+ ...     $Data = Invoke-RestMethod -Uri $Data.'@odata.nextLink' -Headers @ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : {
  "error": {
    "code": "",
    "message": "Invalid Skip Token",
    "innerError": {
      "request-id": "59c91e9d-d87c-4b05-befa-fce7f8f405d6",
      "date": "2020-06-11T11:42:42"
    }
  }
}
```

**Comment by ChrisB9907** [comment]
Update on this: Verified that this is now working again, at least on the Graph API Beta using C# code.

**Comment by davidmu1** [comment]
No change identified for the page. Closing the issue.
