### ISSUE TITLE
Use ID of new item from first request 

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/microsoft-graph-docs#8615]
The documentation isn't clear to me if it would be possible to use the ID of a newly created item from request one in a second request. This clarification is about the batch endpoint.

The idea is that we combine 2 request into one batch request and use the ID of a newly created entity from the first request in the batch, in the second request of the batch.

Example requests:

1. Create new user 
  `POST /users {.......}`
2. Add the newly created user to a group
  `POST /groups/{groupID}/members/$ref { id: {newIdFromRequest1} }`

This is just one sample but could be used in other places. For example creating a user and assigning a license to that newly created user.

So the question is, in a batch request is it possible to create an entity in the first request and use the ID in the second request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26695cc3-710f-0579-7d0a-d770988a0e97
* Version Independent ID: 5bcdfc0f-d9d8-066f-60aa-17ecb174b346
* Content: [Combine multiple requests in one HTTP call using JSON batching - Microsoft Graph](https://docs.microsoft.com/en-us/graph/json-batching)
* Content Source: [concepts/json-batching.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/json-batching.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
@svrooij thanks for reaching out. Today there's no capability in batching that'd allow you to take the result of a previous request in the batch and use it for a subsequent request. You can upvote the [following idea](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/38322757-graph-api-batch-request-with-dependencies) to help prioritize the work and also be notified of any progress.
