### ISSUE TITLE
Access age group and jobtitle (GET, POST, PATCH)

### ISSUE THREAD

**Issue by svrooij** [microsoftgraph/microsoft-graph-docs#8616]
When creating a new user with `/education/users` endpoint I found out the you cannot set the `ageGroup` this seems like a really usefull property in the education context. Since we work mostly with minors.
Also the `JobTitle` cannot be set in the education user context.

My expectation would be that we could set every property of a **regular user** extended with the **education properties**.  Otherwise our flow would become that we create a user with the **Education user** endpoint and then send a patch request to the normal user endpoint setting the other properties.

The same counts for selecting. I get that the default select on the education users is different, but I would expect that an education user (with a jobtitle) could be selected with the `?$select=id,displayName,jobTitle` query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 777a85af-5cbb-e62e-7123-bd7ffac215dc
* Version Independent ID: d7719b66-bb44-a67b-d87a-ae7bf888c9e4
* Content: [educationUser resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/educationuser?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/educationuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/educationuser.md)
* Product: **education**
* Technology: **microsoft-graph**
* GitHub Login: @mmast-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svrooij** [comment]
possibly related to https://github.com/microsoftgraph/microsoft-graph-docs/issues/3897

**Comment by svrooij** [comment]
We are trying to create a user in the education context, with the following request. This request **works**.

```http
POST https://graph.microsoft.com/v1.0/education/users
Content-type: application/json

{
  "accountEnabled": true,
  "displayName": "displayName-value",
  "mailNickname": "mailNickname-value",
  "userPrincipalName": "upn-value@tenant-value.onmicrosoft.com",
  "passwordProfile" : {
    "forceChangePasswordNextSignIn": true,
    "password": "password-value"
  },
  "externalSource": "sis",
  "primaryRole": "teacher",
  "teacher": {
    "externalId": "1234"
  }
}
```

This creates a user for us with the education stuff set correctly, but we also want to set the `jobTitle` and the `ageGroup` on the user, and some other less important properties. Since the educationUser is backed by a graph user, I expected that we could set all the regular user properties as well. This request **doesn't work**.

```http
POST https://graph.microsoft.com/v1.0/education/users
Content-type: application/json

{
  "accountEnabled": true,
  "displayName": "displayName-value",
  "mailNickname": "mailNickname-value",
  "userPrincipalName": "upn-value@tenant-value.onmicrosoft.com",
  "passwordProfile" : {
    "forceChangePasswordNextSignIn": true,
    "password": "password-value"
  },
  "externalSource": "sis",
  "primaryRole": "teacher",
  "teacher": {
    "externalId": "1234"
  },
  "jobTitle": "Dean",
  "ageGroup": "adult"
}
```

**Comment by mlafleur** [comment]
That is correct. While the `educationUser` is build on the `user` resource, they are still distinct OData types. 

In order to set properties in the underlying `user` not otherwise exposed by `educationUser`, you'll need to make a secondary `PATCH` to that `user` resource.

**Comment by svrooij** [comment]
Since the education parameters are saved as extensions on the user, would advice to set the education properties that way, so we can do it in one request?

Extension_tenantid_.... (not sure about the exact format)

Or is the recommended way doing it in 2 requests?


Would it be possible to expose the AgeGroup and the JobTitle in the education user? They seem really relevant in this context (especially the first one).

**Comment by mlafleur** [comment]
You should make 2 calls, one to create the `educationUser` and another to set the underlying `user` properties not otherwise exposed. 

When setting Edu specific properties, you should use the Edu Rostering APIs. While you _can_ set the extension property value directly, there is zero validation of the data. For example, if you set the underlying extension for `student.birthDate` to an unparsable date, attempting to read that record view `/education/users` would result in an `HTTP 500` exception when the Rostering API attempts to cast the underlying string into a Date. 

I will file a feature request to surface `AgeGroup` and `JobTitle`. When we start planning the next rev of the API, we will certainly look at these. As you mention, `AgeGroup` certainly seems relevant at first glance.

**Comment by svrooij** [comment]
Thanks @mlafleur for your response. We have a working solution at the moment (with the two requests). And in the future, if the api is changed, we will probably optimize the flow to start using one request.

Can we (us users) see the feature requests somewhere?
