### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by benhatton-unsw-edu-au** [microsoftgraph/microsoft-graph-docs#8619]
Hi, this API call does not work, returns a 502 Bad Gateway / API Error.

    "error": {
        "code": "BadGateway",
        "message": "Failed to execute backend request.",

Can you please review for breaking changes made to the backend?

Regards
Ben.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497ad1e7-5a61-731f-e0e9-75b5cb9336c8
* Version Independent ID: 776a8387-3525-7289-51bd-1232f58d283a
* Content: [Add conversationMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by robinmalik** [comment]
I'd hit similar issues with Teams endpoints. More comments here but this issue is closed (only just realised, but added comments today/yesterday): https://github.com/microsoftgraph/microsoft-graph-docs/issues/7793

**Comment by ebvjr** [comment]
Any fix?

**Comment by aglumova** [comment]
Any updates?

We retrieved such error during `delta query` for Teams channels

```
Status code [502]
Message:
{
  "error": {
    "code": "BadGateway",
    "message": "Failed to execute backend request.",
    "innerError": {
      "date": "2021-08-03T19:15:53",
      "request-id": "9269e258-6625-42ff-8fc1-aecdc4261bca"
      ...
    }
  }
}
```
