### ISSUE TITLE
Attendance for an onlineMeeting

### ISSUE THREAD

**Issue by ajayvjain** [microsoftgraph/microsoft-graph-docs#8626]
Is it possible to capture the attendance for an onlineMeeting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abc42382-5626-8a11-1af6-82eead08335d
* Version Independent ID: 096787aa-3464-da1a-4d48-b96c53d7f5e7
* Content: [Create onlineMeeting - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-onlinemeetings.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ajayvjain** [comment]
@ananmishr Is it possible to capture the attendance for an onlineMeeting?

**Comment by greenjimll** [comment]
There's [this Uservoice.com suggestion](https://microsoftteams.uservoice.com/forums/599053-schools-and-universities/suggestions/19767967-track-student-attendance-within-teams%29) that may be of interest.
