### ISSUE TITLE
unifiedRoleAssignment response body should contain "@odata.type" for principal property

### ISSUE THREAD

**Issue by chrisspre** [microsoftgraph/microsoft-graph-docs#8635]
It would be good to demonstrate that unifiedRoleAssignment response contains "@odata.type" for the `principal` property. that property can be either a user or  servicePrincipal and that type property allows to distinguish them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c099da1e-238d-d6fb-0e0a-5b767d58cb7e
* Version Independent ID: c395a619-7029-141d-e283-5e0f6d69df05
* Content: [Get unifiedRoleAssignment - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/unifiedroleassignment-get.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @abhijeetsinha
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abhijeetsinha** [comment]
@chrisspre - Added $expand to an existing example. The response has principalType info. See this PR - https://github.com/microsoftgraph/microsoft-graph-docs/pull/8809/files
