### ISSUE TITLE
Please add documentation for expected errors

### ISSUE THREAD

**Issue by adamtoth** [microsoftgraph/microsoft-graph-docs#8636]
Please add to the documentation the expected error responses in the following scenarios:

1. owner specified is already an owner on the group
This one returns 400 bad request, with message: 
"One or more added object references already exist for the following modified properties: 'owners'."

2. owner specified is not a valid user (invalid id)
This one returns 404 not found, with message:
Resource 'user@domain.com' does not exist or one of its queried reference-property objects are not present.

3. owner specified is disabled in Azure AD
(does this generate an error?)
4. owner specified does not have a valid license to use o365 services
(does this generate an error?)

Any other known error scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c8c3174-470e-6bd6-0445-eb95526e85ea
* Version Independent ID: bb1a9ace-6ef2-ddef-b6d1-999a891697ab
* Content: [Add group owner - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-owners?view=graph-rest-1.0&tabs=http&source=docs)
* Content Source: [api-reference/v1.0/api/group-post-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-owners.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Added error code information. Owner specified is disabled in Azure AD, does not cause an error.
