### ISSUE TITLE
Please add expected error responses to the documentation

### ISSUE THREAD

**Issue by adamtoth** [microsoftgraph/microsoft-graph-docs#8637]
Please add to the documentation the expected error responses in the following scenarios:

1. member specified is already a member on the group
This one returns 400 bad request, with message: 
"One or more added object references already exist for the following modified properties: 'members'."

2. member specified is not a valid user (invalid id)
This one returns 404 not found, with message:
Resource 'user@domain.com' does not exist or one of its queried reference-property objects are not present.

3. member specified is disabled in Azure AD
(does this generate an error?)
4. member specified does not have a valid license to use o365 services
(does this generate an error?)

Any other known error scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Added error code information. Owner specified is disabled in Azure AD, does not cause an error.
