### ISSUE TITLE
This API is still Loading in the Graph Explorer. 

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#8639]
[I have been trying to use this api for about 2 months now. It has not been fixed. I run this api in the Graph Explorer waited 5 mins before closing the Graph explorer. Problem is keep Loading]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b001ad-f146-d57f-8318-34c28c45be8c
* Version Independent ID: 333de945-5a1d-93f0-8e0a-e59e8118776d
* Content: [group: addFavorite - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-addfavorite?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-addfavorite.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-addfavorite.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Wasn't able to reproduce the error. Quickly received OK - 200. No change identified for the page. Closing the issue.
