### ISSUE TITLE
Unable to retrieve easdeviceID from managed devices 

### ISSUE THREAD

**Issue by cbdev22** [microsoftgraph/microsoft-graph-docs#864]
Issue: I domain joined an iOS device and logged in successfully to Outlook native iOS app. When I query the "manageddevice" using GET request documented [here](https://graph.microsoft.io/en-us/docs/api-reference/beta/resources/intune_onboarding_manageddevice). It indicates that I my managementState is "managed" and managementAgent is "eas". However, I am unable to see the easDeviceId. Is there another end point that can pull this value?  
![screenshot 2017-02-13 at 5 26 18 pm](https://cloud.githubusercontent.com/assets/25748409/22906288/d2739fa6-f211-11e6-82b7-25462fc4ed5a.png)

**Comment by triplanedave** [comment]
You're looking at the right API.  I have a managed iPad, and I see the following:

{
            "id": "57a73c96-e49b-4e1f-9b14-------------",
            "userId": null,
            "deviceName": "iPad",
            "hardwareInformation": {
                "serialNumber": "DM-----------82",
                "totalStorageSpace": 0,
                "freeStorageSpace": 0,
                "imei": "",
                "meid": null,
                "manufacturer": null,
                "model": null,
                "phoneNumber": null,
                "subscriberCarrier": null,
                "cellularTechnology": null,
                "wifiMac": null,
                "operatingSystemLanguage": null,
                "isSupervised": false,
                "isEncrypted": false,
                "isSharedDevice": false,
                "sharedDeviceCachedUsers": []
            },
            "ownerType": "company",
            "deviceActionResults": [],
            "managementState": "managed",
            "enrolledDateTime": "2017-06-06T23:44:04Z",
            "lastSyncDateTime": "2017-06-09T07:22:36Z",
            "chassisType": "unknown",
            "operatingSystem": "iOS",
            "deviceType": "iPad",
            "complianceState": "unknown",
            "jailBroken": "Unknown",
            "managementAgent": "mdm",
            "osVersion": "10.3.2",
            "easActivated": false,
            "easDeviceId": "QA78B691UD6OP18QLOA327MKNC",
            "easActivationDateTime": "0001-01-01T00:00:00Z",
            "aadRegistered": false,
            "enrollmentType": "deviceEnrollment",
            "lostModeState": "disabled",
            "activationLockBypassCode": null,
            "emailAddress": "",
            "azureActiveDirectoryDeviceId": "57a73c96-e49b-4e1f-9b14--------------c5",
            "deviceRegistrationState": "registered",
            "deviceCategoryDisplayName": "Unknown",
            "isSupervised": false,
            "exchangeLastSuccessfulSyncDateTime": "0001-01-01T00:00:00Z",
            "exchangeAccessState": "none",
            "exchangeAccessStateReason": "none",
            "remoteAssistanceSessionUrl": null,
            "isEncrypted": false,
            "userPrincipalName": "",
            "model": "iPad 4",
            "manufacturer": "Apple",
            "imei": "",
            "complianceGracePeriodExpirationDateTime": "0001-01-01T00:00:00Z",
            "serialNumber": "D------------182"

The interesting thing is that my iPad is MDM managed with an EAS ID, but yours is EAS managed without an EAS ID.  Do you have the mail app configured to connect with Exchange?

**Comment by lleonard-msft** [comment]
Hi @cbdev22,

Is this still an active issue or may we close it?  If not, did you see @triplanedave's question? 

-- Lance
