### ISSUE TITLE
No UID Filter?

### ISSUE THREAD

**Issue by mhagesfeld** [microsoftgraph/microsoft-graph-docs#8640]
OK, I understadn changing iCalUId to uid, but why can I not filter on uid the way I could on iCalUId?

"code": "UnsupportedEntityExpression",
        "message": "'x => (x.Uid == \"040000008200E00074C5B7101A82E00800000000F0B9F727763DD601000000000000000010000000FD67034ABD1DF54FB31D68570FC7EDEB\")' is not a supported filter expression.",
        

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53257c69-9ebe-7fd1-b55e-1612b62b9be0
* Version Independent ID: b8b43aa7-df77-3203-7191-43a86297e835
* Content: [event resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/event.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
@darrelmiller 
Kindly comment if SDK issue.

**Comment by Harini84** [comment]
UId does not support filtering yet. Plan is to allow UId and iCalUId to co-exist.

**Comment by mhagesfeld** [comment]
Thank you for your response. What is the difference between the two? What
is the expected time frame, or is there one?

**Comment by Harini84** [comment]
As defined in MS-Graph documentation:

UID - A unique identifier for calendar events. For recurring events, the value is the same for the series master and all of its occurences including exceptions.

iCalUID - A unique identifier for an event across calendars. This ID is different for each occurrence in a recurring series. Read-only.

As commented in #6247 plan is to restore iCalUID in Graph beta.
