### ISSUE TITLE
Can we please remove the second "Important" box on this page.  The supported period has ended last year.

### ISSUE THREAD

**Issue by mmushatt** [microsoftgraph/microsoft-graph-docs#8642]
Can we please remove the second Important box on this page?  The PIM change notification has ended in November 2019 and the link goes to a "Form can no longer be accessed" page.  This will also reduce calls to support concerning why this feature is no longer available or extended.

Thank you in advance,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb10229f-46f3-82b2-b8da-6cd567a9f32c
* Version Independent ID: e272dcc2-641d-33d7-ba26-b3d17239bd4e
* Content: [Privileged Identity Management - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/privilegedidentitymanagement-root?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/privilegedidentitymanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/privilegedidentitymanagement-root.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The text looks to have been changed. No change identified for the page. Closing the issue.
