### ISSUE TITLE
Newly Added Members are not reflecting in Team 

### ISSUE THREAD

**Issue by RonakJain7** [microsoftgraph/microsoft-graph-docs#8654]
Steps : 
1. Create Group with few members.

2. Create Team.

3. Add more members to the group.
IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Group group = new Group();
group.additionalDataManager().put("members@odata.bind", new JsonPrimitive("[
  "https://graph.microsoft.com/v1.0/directoryObjects/{id}",
  "https://graph.microsoft.com/v1.0/directoryObjects/{id}",
  "https://graph.microsoft.com/v1.0/directoryObjects/{id}"
]"));

graphClient.groups("{id}")
	.buildRequest()
	.patch(group);

Issue : Not showing new members in team. 

Using Following Code to Add New members to the existing group which also has team 

IGraphServiceClient graphClient = GraphServiceClient.builder().authenticationProvider( authProvider ).buildClient();

Group group = new Group();
group.additionalDataManager().put("members@odata.bind", new JsonPrimitive("[
  "https://graph.microsoft.com/v1.0/directoryObjects/{id}",
  "https://graph.microsoft.com/v1.0/directoryObjects/{id}",
  "https://graph.microsoft.com/v1.0/directoryObjects/{id}"
]"));

graphClient.groups("{id}")
	.buildRequest()
	.patch(group);

newly added members are not showing in team created using this group Id. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RonakJain7** [comment]
Any update on this ?

**Comment by ashoksubedi1** [comment]
any update same problem

**Comment by arpit107** [comment]
I have been facing this same issue for long. Any update on this?

**Comment by ashoksubedi1** [comment]
@yyuank

**Comment by Trinetra-MSFT** [comment]
@RonakJain7 , Are you facing the same issue with Graph Explorer? 
I tried the same thing in explorer and it was working fine  Here is the steps I followed:

1. [Created a group with owners and members](https://docs.microsoft.com/en-us/graph/api/group-post-groups?view=graph-rest-1.0&tabs=http#example-2-create-a-group-with-owners-and-members) using Graph API.
2. [Create a Team within same Group](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-1.0&tabs=http#example) 
3. [Adding Member to the Group](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http#example-1-add-a-member-to-a-group)

I got the correct response when I add a new member to the Group that is visible within the Team also. Please see screenshot: if you I've three members added and one owner.
![image](https://user-images.githubusercontent.com/50989436/85689448-41c42000-b6f0-11ea-91dd-7fb4703bfa44.png)

After adding a new member:
![image](https://user-images.githubusercontent.com/50989436/85689766-8cde3300-b6f0-11ea-9b70-833a445e2ea1.png)

I need to know, Are you getting any specific error while adding member? if so please share the request-id.

**Comment by RonakJain7** [comment]
Working fine now.

**Comment by ashoksubedi1** [comment]
I don't get users 20% percent of the time which is useless because I have to check in Teams everytime if this all users came into teams or not. If I have to check every single time. what is the point. Those team that members don't come in, I go add manually from group
