### ISSUE TITLE
Improve code example for the OnBehalveOfProvider

### ISSUE THREAD

**Issue by verbedr** [microsoftgraph/microsoft-graph-docs#8655]
At the #OnBehalfOfProvider example is it possible to add a mention to the WithUserAssertion requirment like it is done for the #UsernamePasswordProvider example

When users are trying this provide they will report a null pointer exception from the code as the code is not validating that requirment. And it would be good to add an example usage like this

```
IHttpContextAccessor httpContextAccessor; /* register this service before using in DI */

var accessToken = await httpContextAccessor
                .HttpContext.GetTokenAsync(AzureADDefaults.BearerAuthenticationScheme, "access_token");

GraphServiceClient graphClient = new GraphServiceClient(authProvider);

User me = await graphClient.Me.Request()
                .WithUserAssertion(new UserAssertion(accessToken))
                .GetAsync();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4537f77e-a8e8-e3f1-9cc4-2fd930db7ada
* Version Independent ID: 46396fa2-f7e2-322e-5e76-f9e2d17d1b48
* Content: [Choose a Microsoft Graph authentication provider - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS)
* Content Source: [concepts/sdks/choose-authentication-providers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/choose-authentication-providers.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @MIchaelMainer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
With v4 of the SDK we no longer recommend using that provider. See the new code in the linked pull request.
