### ISSUE TITLE
Add app to chat

### ISSUE THREAD

**Issue by husseinraoouf** [microsoftgraph/microsoft-graph-docs#8660]
I would like to add a bot to a channel that is not inside a team
currently, I am trying this with c# sdk
```C#
var installedApp = await graphClient.Chats[chatId].InstalledApps
      .Request()
      .AddAsync(new Beta.TeamsAppInstallation
      {
          AdditionalData = new Dictionary<string, object>()
          {
              {"teamsApp@odata.bind","https://graph.microsoft.com/beta/appCatalogs/teamsApps/8624b870-ff42-408f-a085-0f2daa0282d4"}
          }
      });
```
but it returns an error and I don't see this case documented anywhere
am I doing something wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34603d36-1be8-0a02-eeaf-09ffe733bd86
* Version Independent ID: ffb494cb-0954-7294-e71d-c019250b5c35
* Content: [Add app to team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-add?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/teamsappinstallation-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/teamsappinstallation-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by husseinraoouf** [comment]
Just to know the context
what I am trying to do is to create an online meeting with graph API then invoke my bot to send a proactive message to the chat of that meeting, but after creating the meeting, invoking the bot to send a proactive message fails with the following error `BotNotInConversationRoster`

I have tried the same logic with a hardcode chat Id that I know the bot is part of, and it worked so the only thing that stops me now is to add the bot in the chat of the online meeting

**Comment by clearab** [comment]
I'm fairly certain that you cannot use this endpoint to proactively install an app into a meeting or a group chat - I believe it only works for 1-1 and Teams. @nkramer  can you confirm?

**Comment by husseinraoouf** [comment]
thanks for the fast response

if i can't is there is any other way?

**Comment by husseinraoouf** [comment]
@clearab friendly ping

I just need to if there is any way to do it

**Comment by clearab** [comment]
I'm not part of the Graph team, so I cannot say with certainty. However, I'm unaware of any way to accomplish what you're looking for.
