### ISSUE TITLE
Application rights for CreateEvent  in MS Teams

### ISSUE THREAD

**Issue by greenjimll** [microsoftgraph/microsoft-graph-docs#8661]
Looking at accessing Teams calendars via Graph API application (daemon) rights, is it really true that whilst you can use Calendar.ReadWrite to get, update or delete a group calendar event, you can't create the events using any application rights?  Or is this a mistake in the documentation?  

Seems a bit odd that a daemon process can alter or delete events but can't create them. And rather limits using Graph API to populate Teams' calendars from external data sources (for example in our use case to support creating online meetings based on events in our existing University timetabling system).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3657f7cb-10f9-0631-362d-f8e66edcd018
* Version Independent ID: dfa0e4c5-38d0-6aa0-6d5b-e35f66c78135
* Content: [Create event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-events?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-events.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-events.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Yes, only with delegated permissions can you run the **Create event** API. No updates identified for the page. Closing the issue.
