### ISSUE TITLE
Clarify that app only permissions are not supported for MSA. 

### ISSUE THREAD

**Issue by hpsin** [microsoftgraph/microsoft-graph-docs#8662]
It is not explicitly discussed anywhere that app only permissions are not supported for MSA. There is no way that an app can get "files.read.all" in the MSA tenant. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d9333e-3b22-fd5a-2bc7-9aac994778a1
* Version Independent ID: 1d92b01c-f82d-7e62-8e7e-9b9ce1b37a92
* Content: [Microsoft Graph permissions reference  - Microsoft Graph](https://docs.microsoft.com/en-us/graph/permissions-reference#files-permissions)
* Content Source: [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/permissions-reference.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @hpsin for raising your issue.
Application permissions require Admin consent which cannot be granted for consumer resources. Kindly use the delegated permissions to read your files.

No updates identified for the page for now. Closing the issue.
