### ISSUE TITLE
How many groups can we create in MS Teams 

### ISSUE THREAD

**Issue by YasiruUOK** [microsoftgraph/microsoft-graph-docs#8670]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed58b36a-1416-fcc0-4dd7-39d2a9f48b7c
* Version Independent ID: 438b361c-d067-4027-6a7d-3988c7028837
* Content: [Creating teams and managing members using Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-create-group-and-team)
* Content Source: [concepts/teams-create-group-and-team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-create-group-and-team.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @hachandr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @YasiruUOK 

this web site shows limits that applies to Microsoft 365 Groups: https://docs.microsoft.com/en-us/microsoft-365/admin/create-groups/office-365-groups?view=o365-worldwide#group-limits

I hope it helps to clarify your quesiton.

Regards,
Jarbas

**Comment by FaithOmbongi** [comment]
Thank you @JarbasHorst 

No updates identified for the page. Closing the issue.
