### ISSUE TITLE
Stopping PageIterator if reached end of results.

### ISSUE THREAD

**Issue by adnan-azmat** [microsoftgraph/microsoft-graph-docs#8683]
Suppose PageIterator reaches end of results before count reaches pauseAfter. How to come out of PageIterator in this scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d558deeb-3492-230e-b2d9-8d9efeb6f97f
* Version Independent ID: bb2e0da9-acb9-0ffa-7fb6-d1bb534bfd20
* Content: [Page through a collection using the Microsoft Graph SDKs - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/paging?tabs=typeScript)
* Content Source: [concepts/sdks/paging.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/paging.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
It exits when it gets to the end of a page and there are no more pages available automatically. There's no requirement that your callback must return false explicitly. Note that the first sample snippet is hardcoded to always return true.
