### ISSUE TITLE
Error creating sharepoint page with image

### ISSUE THREAD

**Issue by viveksk6** [microsoftgraph/microsoft-graph-docs#8689]
Get /page/{page-id} REST API of a page containing an image returns only the ID and InstanceID of the image as the webparts.
For example:
"webParts": [
    "type": "d1d91016-032f-456d-98a4-721247c305e8",
    "data": {
          "id": {id},
          "instanceId": {instanceID}
    }
]

Now if I want to create a page withe the same image using the POST /pages API, how should I upload this image to the page in webpart? Uplaoding the exact same response in the webpart using:
POST /pages
{
    "name": "test.aspx",
    "title": "Test7",
    "publishingState": {
        "level": "checkedOut",
        "versionId": "0.1"
    },
    "webParts": [
         {
                    "type": "d1d91016-032f-456d-98a4-721247c305e8",
                    "data": {
                         "id": {id},
                         "instanceId": {instanceID}
                    }
                }
    ]
}

 gives an error: 

{
  "error": {
    "code": "invalidRequest",
    "message": "One of the provided arguments is not acceptable.",
    "innerError": {
      "code": "badArgument",
      "date": "2020-06-11T05:55:22",
      "request-id": {request-id}
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbf8c08e-49be-b1b7-54fc-c83983f8ff83
* Version Independent ID: d5afa542-1f60-630e-4133-314a90e03165
* Content: [Create a new page in a SharePoint site - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/sitepage-create?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/sitepage-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/sitepage-create.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @rahmit
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rohit404404** [comment]
@viveksk6 Add image webpart to any page. Add tag ?maintenancemode=true at the end of the URL (After aspx)

This should expose the webpart data is raw format. Click on Data header and use that payload as webpart data

Sample payload below to create a page with text editor webpart in modern page.

`{
    "name": "12.aspx",
    "title": "Default",
    "publishingState": {
        "level": "checkout",
        "versionId": "0.1"
    },
    "webParts": [
        {
            "type": "rte",
            "data": {
                "innerHTML": "DefaultTextOnPage",
                "title": "List"
            }
        }
    ]
}`

![image](https://user-images.githubusercontent.com/3784144/134492677-ac90c0c0-f605-424f-809e-5c38398c4cff.png)
