### ISSUE TITLE
Maximum file size is not mentioned in the Docs

### ISSUE THREAD

**Issue by yashjain12yj** [microsoftgraph/microsoft-graph-docs#8691]
I was going through the docs for large file upload. [Resumable file upload](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0)

The very first line is

> allow your app to upload files up to the maximum file size.

But in the whole doc, this maximum file size is not mentioned as it is mentioned for small file upload which is 4MB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c42d74d1-8c6f-5282-9fba-30fdd6449362
* Version Independent ID: 88bd8f18-730d-6970-8a02-641346661404
* Content: [Resumable file upload - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#feedback)
* Content Source: [api-reference/v1.0/api/driveitem-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-createuploadsession.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @JeremyKelley
* Microsoft Alias: **JeremyKelley**

**Comment by lramosvea** [comment]
Hi @yashjain12yj I can see the doc mentions the following: You can upload the entire file, or split the file into multiple byte ranges, as long as the maximum bytes in any given request is less than 60 MB.

Feel free to reopen this bug if that does not answer your question/issue. Thanks.
