### ISSUE TITLE
Does appRoleAssignedTo support count, paging and filtering?

### ISSUE THREAD

**Issue by twentytwokhz** [microsoftgraph/microsoft-graph-docs#8693]
On the **beta** endpoint there is a GET /servicePrincipals/{id}/appRoleAssignedTo call
Does this support $**count**, $**filter** and $**search**?
My use case is searching the user list of a particular enterprise app (based on the user appRoleAssignment on it)

1. Can I perform **filter**?
2. Can I perform **count**?
3. Can I perform **search**?
4. Is there an option for performing my use case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 585bb8e4-a9bb-f727-a5eb-e9c3244ec3a2
* Version Independent ID: b66f0561-4c0f-9ded-4734-482328d99eb0
* Content: [List appRoleAssignments granted for a service principal - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/serviceprincipal-list-approleassignedto.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Successfully ran these operations:

https://graph.microsoft.com/beta/servicePrincipals?$filter=startsWith(displayName,'Intune')
https://graph.microsoft.com/beta/servicePrincipals/$count
https://graph.microsoft.com/beta/servicePrincipals?$search="displayName:wa"

A workitem has been created to better document query parameters. Closing the issue.
