### ISSUE TITLE
Application permissions are working for this

### ISSUE THREAD

**Issue by JeremyTBradshaw** [microsoftgraph/microsoft-graph-docs#8696]
FYI, Application permissions are working for this.  Can/have tested to confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1691c888-7955-2567-d53d-3a03eae9d9eb
* Version Independent ID: 6fd35314-8882-a049-fbb9-6037d818d100
* Content: [List managedDevices - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-devices-manageddevice-list?view=graph-rest-1.0&viewFallbackFrom=graph-rest-beta)
* Content Source: [api-reference/v1.0/api/intune-devices-manageddevice-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-devices-manageddevice-list.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Excellent, thank you very much!  We know that app permissions are an important part of overall automation of Intune, so I'm glad you are able to take advantage of them!

Dave

**Comment by JeremyTBradshaw** [comment]
@triplanedave , but the page says "Unsupported".  Just wondering if this will be updated or should I submit a PR for this instead?  The reason I didn't do that to start is that I don't want to guess and not get the exact permissions list correct.

**Comment by triplanedave** [comment]
Thanks for clarifying.  Sorry I missed that point.  The docs are regenerated each month so I'll file a work item to update the source content.  App permissions should be supported.
