### ISSUE TITLE
Graph API Teams user activity report contents vs. admin console report contents

### ISSUE THREAD

**Issue by MushyMiddle** [microsoftgraph/microsoft-graph-docs#8698]
Hi.  It appears that the Teams User Activity report documented at https://docs.microsoft.com/en-us/microsoftteams/teams-analytics-and-reports/user-activity-report has changed, to include a number of new (and useful) fields.  However, as of today, while our tenant has the new report contents in the admin console, the API still has the old, and less useful report format.  What are the plans for rolling-out these changes to the Graph API?

Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cb618b3-a6d3-613e-d369-946a045b76fc
* Version Independent ID: ea791697-f437-1aa2-7ec4-96b07fb25150
* Content: [teamsUserActivityUserDetail resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/teamsuseractivityuserdetail?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/teamsuseractivityuserdetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/teamsuseractivityuserdetail.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by junhui** [comment]
hope MS can do a quickly alignment. the graph api is too old to use

**Comment by Abhijit-MSFT** [comment]
This is a known issue. Our team is working on it.

**Comment by TimZhou1987** [comment]
we have the same issue

**Comment by maciz84** [comment]
Any update on this? Would be nice for the Graph API to be updated or aligned to the Teams Admin Center data. I have also noticed the call count stats are usually wrong in the Graph API getTeamsUserActivityUserDetail endpoint. The meeting ones are a bit more accurate.

The more we all use Teams the more meaningful stats we would like to see 👍

**Comment by Abhijit-MSFT** [comment]
This is currently under development and there is no timeline that i can provide.
