### ISSUE TITLE
Inconsistent/Incorrect Documentation

### ISSUE THREAD

**Issue by rcg-dev** [microsoftgraph/microsoft-graph-docs#8700]
On this page the url provided in step 4 to get an access_token doesn't work. Because that url is a bit off. However on [https://developer.microsoft.com/en-us/graph/docs/authorization/app_only](this) page the url works. Please update documentation to help people not want to kill themselves. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service?view=graph-rest-1.0)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by rcg-dev** [comment]
All jokes aside. I thought I was doing something terribly wrong when in fact the url's are off by a bit
`https://login.microsoftonline.com/{tenantId}/oauth2/token`
`https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token`

**Comment by jasonjoh** [comment]
No, the v2.0 is correct and should work, per Azure's own docs: https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow

@Jackson-Woods why would the v2 endpoint not work for @rcg-dev but the v1 endpoint would?

**Comment by rcg-dev** [comment]
@

> No, the v2.0 is correct and should work, per Azure's own docs: https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow
> 
> @Jackson-Woods why would the v2 endpoint not work for @rcg-dev but the v1 endpoint would?

![fails](https://user-images.githubusercontent.com/56566262/84546356-11bf5a80-acb6-11ea-8b69-d5136f68184f.jpg)
![works](https://user-images.githubusercontent.com/56566262/84546360-1257f100-acb6-11ea-8831-bd5d16374aac.jpg)

One works, one doesn't. I wish I knew why.

**Comment by jasonjoh** [comment]
Unescape your scope value I think.

**Comment by jasonjoh** [comment]
Yep, confirmed it on my side. If I escape it in the Postman form, it fails with the same error. If I just put `https://graph.microsoft.com/.default`, it works.

**Comment by rcg-dev** [comment]
Well that works yes. However that's still incorrect documentation as it tells you to URL encode it.

**Comment by jasonjoh** [comment]
Well, you do URL-encode it on the wire. I'll have to defer to @Jackson-Woods intent here, but I think that the code block is showing wire traffic:

```
// Line breaks are for legibility only.

POST https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id=535fb089-9ff3-47b6-9bfb-4f1264799865
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
&client_secret=qWgdYAmab0YSkuL1qKv5bPX
&grant_type=client_credentials
```

But in the table below where he lists the parameters, it says: "For Microsoft Graph, the value is `https://graph.microsoft.com/.default`."

I checked with Fiddler to see what's going on the wire. If you use the non-escaped string in the Postman UI, it goes over the wire as URL-encoded (if you look at the raw traffic):

![image](https://user-images.githubusercontent.com/8966342/84663789-9f37c000-aeeb-11ea-80a4-e33afa79b11a.png)

If you put the URL-encoded version in the Postman UI, it appears Postman is encoding the percent signs, invalidating the value:

![image](https://user-images.githubusercontent.com/8966342/84663917-cabaaa80-aeeb-11ea-98d5-59142fd1ba42.png)

So this appears to be a Postman issue. I don't know if they would consider it a bug that they're re-encoding an encoded value.

**Comment by psignoret** [comment]
Closing this issue, as the documentation here is accurate.
