### ISSUE TITLE
Attachment example not working

### ISSUE THREAD

**Issue by Denford29** [microsoftgraph/microsoft-graph-docs#8704]
I have been trying this example on request 3 for c# here https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp#request-3 and the line here doesnt seem to work.

```
Attachments = (IMessageAttachmentsCollectionPage)new List<Attachment>()
```

I keep get a type conversion error from `List<Attachment>` to `IMessageAttachmentsCollectionPage` and in my case i need to create the message with multiple attachments and cant find a way to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp#request-3)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Yes that is incorrect code. These are auto-generated and it looks like the generator isn't handling it correctly.

Try this:

```
// Initialize the collection page
message.Attachments = new MessageAttachmentsCollectionPage();
// Add an attachment
// Use FileAttachment object since this is a file
message.Attachments.Add(new FileAttachment
{
    Name = file.FileName,
    ContentType = file.ContentType,
    ContentBytes = memoryStream.ToArray()
});
```

**Comment by Denford29** [comment]
@jasonjoh Thanks for the details, didn't know the code was auto-generated which explains why that wasn't working. I had resorted to a work around 1)create a draft message 2) add the attachments to the draft 3) send the draft message.

I have update the "work-around" i had with the implementation you provided above and that is working fine, thanks.
