### ISSUE TITLE
how to get calendar room resource use graph? 

### ISSUE THREAD

**Issue by hxt1994** [microsoftgraph/microsoft-graph-docs#8706]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1f9a95c-0ddb-bbce-cb13-a8feda9a109b
* Version Independent ID: f4112c62-f03d-47b2-01a2-f26efedb9e57
* Content: [List calendarGroups - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-calendargroups?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-calendargroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-calendargroups.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hxt1994** [comment]
we can get roomlist and then get roomresouce with ews sdk，but i can't find how to realize it with graph?

**Comment by Harini84** [comment]
Please use Places API: 
https://docs.microsoft.com/en-us/graph/api/place-list?view=graph-rest-1.0&tabs=http
