### ISSUE TITLE
Property .Range("$A$1").Format cannot be found in the sdk

### ISSUE THREAD

**Issue by crong-tek** [microsoftgraph/microsoft-graph-docs#8710]
I tried to use the SDK to update the cell format. However, with the sample C# code, the Property Format for IWorkbookWorksheetRangeRequestBuilder cannot be found. Thus compilation of code .Range("$A$1").Format reported an error in Visual Studio. Please check where I did wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae6d2e88-8df9-ca1e-5077-9e5c2d399e8d
* Version Independent ID: 2ede998c-f1e1-8690-aea1-6d930b6d27de
* Content: [Update a range format in Excel with Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/excel-update-range-format?tabs=http)
* Content Source: [concepts/excel-update-range-format.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/excel-update-range-format.md)
* Product: **excel**
* Technology: **microsoft-graph**
* GitHub Login: @lumine2008
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by grangeryy** [comment]
@crong-tek  Does this issue still happen to you?

**Comment by grangeryy** [comment]
Close this since no more information from customer. Feel free to reopen later.
