### ISSUE TITLE
Members are not coming through to Team and only remain in groups. Forced to add members manually on Teams

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#8711]
[So I am creating a groups and added members to it and then add teams to it all using graph API. But not all members of the group are shown in the teams. I have to come back to teams and add members manually. That is weird. Is it because I adding about 18 users at the same time to a group using a batch call. Some teams all members load of correctly from groups and some none of them gets into the teams. i have to do manually. Help!!!!!!!!!!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30c10d6f-f836-ccc7-992d-36f1d904737e
* Version Independent ID: c2a9877d-ccf8-2829-bef0-4f813ee155ee
* Content: [Add member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-post-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-post-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ashoksubedi1** [comment]
Any update on this. I am going and adding members manually on Teams when those are already the members of group

**Comment by FaithOmbongi** [comment]
Confirmed that adding new users to a group via the Microsoft Graph API should automatically add these users to the linked team. No updates identified for the page. Closing the issue.
