### ISSUE TITLE
/sites/{site-id}/lists/{list-id}/items/{item-id}/versions/{version-id}/restoreVersion - Creates New Version

### ISSUE THREAD

**Issue by jagrock** [microsoftgraph/microsoft-graph-docs#8720]
/sites/{site-id}/lists/{list-id}/items/{item-id}/versions/{version-id}/restoreVersion

This does not restore to the previous version, but creates a new version that matches the said version.  However, it does not keep the version you are trying to restore modified/created and uses the person that called this api.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a23b60-5fc4-9d75-879f-c04e10466527
* Version Independent ID: 148e1195-79b5-65d8-da5a-5269c0b6a34d
* Content: [Restore a previous version of a ListItem - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/listitemversion-restore?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/listitemversion-restore.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/listitemversion-restore.md)
* Product: **sharepoint**
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JeremyKelley** [comment]
The is the expected behavior across SharePoint's history.  Restoring a version creates a copy of that version as the latest one.  This is documented correctly at: https://docs.microsoft.com/en-us/graph/api/driveitemversion-restore?view=graph-rest-1.0&tabs=http
