### ISSUE TITLE
How do we get Message ID to attach the uploaded attachment to

### ISSUE THREAD

**Issue by wjvii** [microsoftgraph/microsoft-graph-docs#8725]
The new method for large attachments is great, but the sample assumes you know the message ID and it is hard coded in the example. If I am sending a new message that I wish to attach the large uploaded file to how do I obtain the email message id to attach it to? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e6b4ed-4a94-6789-95e3-407780e8fd7e
* Version Independent ID: ff8aca6f-1a1f-1bef-c1dd-bfdbbaf9f901
* Content: [Attach large files to Outlook messages or events - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http)
* Content Source: [concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-large-attachments.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
@wjvii , you can [create a message draft](https://docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http) first without sending it, attach the file to the draft, and then [send](https://docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http) it.
