### ISSUE TITLE
Problem Resource not found for the segment 'identityRiskEvents'

### ISSUE THREAD

**Issue by zzendon** [microsoftgraph/microsoft-graph-docs#8731]
Someone got a idea why i get this problem
![image](https://user-images.githubusercontent.com/43130955/84641315-25a7ce00-aefb-11ea-9f7a-6326b182ec7c.png)

---
#### Document Details 

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ef6d73-3f70-1132-7e5f-d43e2cecf10d
* Version Independent ID: 5925ebcb-a1da-11fa-d12f-3d7bb3cf0d19
* Content: [List identityRiskEvents - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/identityriskevent-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/identityriskevent-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/identityriskevent-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cloudhandler** [comment]
This API has been deprecated- please move to riskDetections https://docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-beta
