### ISSUE TITLE
Reference of appliedConditionalAccessPolicies points to the wrong link

### ISSUE THREAD

**Issue by elcarlosadrian** [microsoftgraph/microsoft-graph-docs#8735]
In the documentation of signIn resource type, the reference to the appliedConditionalAccessPolicies type is wrong:
Actual: https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccesspolicy?view=graph-rest-beta
Expected: https://docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-1.0&viewFallbackFrom=graph-rest-beta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e7c8c9-8f24-f7b9-f275-59699e748383
* Version Independent ID: 9a912f06-6ffd-d5c9-de30-66c8fff1d578
* Content: [signIn resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/signIn?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/signin.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @kholtz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Hi @elcarlosadrian The link is OK as-is. It's linking from a resource page in the beta version to another in the same version. Closing without a doc update.
