### ISSUE TITLE
Requesting Addition of "Applies To" Section

### ISSUE THREAD

**Issue by atobrandon** [microsoftgraph/microsoft-graph-docs#8736]
Could you add an "applies to" section that indicates whether this works for AAD / AAD B2C / etc.?  
I think this should really be done for all pages if possible. It's very difficult to determine what does and does not work with B2C currently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2131c0c0-b5c1-61fa-98cf-5af744c9f72d
* Version Independent ID: 77be448b-3d8b-9b50-7941-c6218942b6ce
* Content: [Azure AD authentication methods API overview - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/authenticationmethods-overview.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @mmcla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @atobrandon for raising this issue. I've raised it with the team and we'll be updating the docs with this information soon. Closing this issue for now.
