### ISSUE TITLE
Update application: Property table is messed up

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#8737]
One of the values for signInAudience, AzureADandPersonalMicrosoftAccount, was incorrectly added in another column, hence there's actually no description and it's messing up the whole table for adding a new column with just this undefined option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c6afab3-9682-0f8e-0441-2adfde3f84ef
* Version Independent ID: 6eee450a-b6d0-0908-0392-00e01d412185
* Content: [Update application - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http#request-body)
* Content Source: [api-reference/v1.0/api/application-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/application-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
This does not appear to be an issue now. Closing the issue.
