### ISSUE TITLE
View or export a list of users who attended a meeting

### ISSUE THREAD

**Issue by YasiruUOK** [microsoftgraph/microsoft-graph-docs#8740]
Currently, there is no method of viewing a list of meeting attendees after a meeting has ended.

Meeting organizers should be able to view or export a list of attendees, including enter and exit times, duration, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2e308f-24ac-6159-cc31-a70729672f6e
* Version Independent ID: ed5ba667-4caa-6db4-a409-96ee585ba11e
* Content: [Get event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
List of attendees of an event is already returned in getEvent API.

Entry and exit times of an attendee to a venue or online meeting is not part of event construct and is not planned to be included in near future.
