### ISSUE TITLE
New Graph Api for Secure Score

### ISSUE THREAD

**Issue by macpak** [microsoftgraph/microsoft-graph-docs#8741]
Hi,

Recent changes to [Security Portal](https://security.microsoft.com/securescore?viewid=overview)  made it [incompatible with graph api](https://docs.microsoft.com/en-gb/microsoft-365/security/mtp/microsoft-secure-score-new?view=o365-worldwide#whats-new) . When can we expect an update to graph api ? Is there maybe a beta version which is compatible with the Security Portal ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9f76a9-cef3-1651-9dd0-2be6d638eda1
* Version Independent ID: 52ab95c0-8796-f539-20af-c8d6dc824d2e
* Content: [List secureScores - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/security-list-securescores?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/security-list-securescores.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/security-list-securescores.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @preetikr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by PaulBendall** [comment]
@macpak supporting this issue as current functionality is incompatible with Graph API and it is difficult to find any specific roadmap information when this will be addressed

**Comment by jchaundy** [comment]
With the new secure score now being GA is there any update on the compatibility with Graph?
(https://techcommunity.microsoft.com/t5/microsoft-security-and/announcing-general-availability-of-the-new-version-of-microsoft/bc-p/1520463#M3721)

**Comment by despian** [comment]
Any update on this issue?
