### ISSUE TITLE
Response doesn't respect Header Prefer outlook.timezone

### ISSUE THREAD

**Issue by olivermue** [microsoftgraph/microsoft-graph-docs#8755]
Within the documentation of [Get Events](https://docs.microsoft.com/en-us/graph/api/event-get#support-various-time-zones) you can define a timezone that should be used for the start and end time of the event, but PATCH ignores this header an answers always in UTC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1c68e-95bf-e8af-992e-cb790f8ca884
* Version Independent ID: 4072bab0-de7c-1f9f-05b9-6a7b4b6787f8
* Content: [Update event - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/event-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/event-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/event-update.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @Harini84
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Harini84** [comment]
Header value is only for returning response in the specified timezone in Get/ list events.
In PATCH calls, the updated event is returned in response in default timezone i.e. UTC. This call does not support timezone in header.
