### ISSUE TITLE
Conflict in roleDefinition resource type properties description

### ISSUE THREAD

**Issue by nitinb-msft** [microsoftgraph/microsoft-graph-docs#8764]
Properties permissions and rolePermissions have same description. Can you update?

permissions | rolePermission collection | List of Role Permissions this role is allowed to perform. These must match the actionName that is defined as part of the rolePermission.
-- | -- | --
rolePermissions | rolePermission collection | List of Role Permissions this role is allowed to perform. These must match the actionName that is defined as part of the rolePermission.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa24b0e-6c77-2268-7f21-fb1b06003c71
* Version Independent ID: 19046e56-e829-8b4f-141e-a711cf0e3be7
* Content: [roleDefinition resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/intune-rbac-roledefinition?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/intune-rbac-roledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/intune-rbac-roledefinition.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for the feedback.  This is an artifact of having permissions and rolePermissions in both the /beta and /v1.0 trees.  They do in fact mean exactly the same thing, so the description is correct.
