### ISSUE TITLE
CreationType field requested when creating a local account

### ISSUE THREAD

**Issue by hemikak** [microsoftgraph/microsoft-graph-docs#8769]
I get the following error when trying to create a LocalAccount under "Create a user with social and local account identities"

`Property creationType is invalid`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17cbd4b2-1fdf-6a5d-58f9-63b2d831d9d6
* Version Independent ID: a5700fd6-347e-7124-7b90-0a82b6f1a70a
* Content: [Create User - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-post-users.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-post-users.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@hemikak - Unfortunately, there isn't enough information here to identify an issue with the page. Be sure to pay attention to this note: For local account identities, password expirations must be disabled, and force change password at next sign-in must also be disabled.

 I'm going to close this issue for now. Please reopen the issue with the body of the request that you are using and we can take another look.
