### ISSUE TITLE
Elaborate on how "only VoIP calls are supported" applies

### ISSUE THREAD

**Issue by sipsorcery** [microsoftgraph/microsoft-graph-docs#8772]
There's a note at the top of the page that states:

> Note: Currently, only VoIP calls are supported.

It needs to be elaborated on what this means? Does it mean a peer-to-peer call cannot be established unless the Teams user being called has a VoIP number assigned? For a Group call does it mean all users in the Group call must have VoIP numbers assigned. What does it mean for a bot to call into an existing meeting? Does the meeting have to have a VoIP number assigned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71b5f237-e7af-1f0f-201c-c600eb4a3cc8
* Version Independent ID: 7aa5b80a-5565-b702-20ae-8d550357980a
* Content: [Create call - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/application-post-calls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lund76** [comment]
I found this issue searching the frase . Does it mean, that create call can't initiate af call to PSTN via SIP trunk ?

**Comment by lramosvea** [comment]
Closing as the doc has been updated
