### ISSUE TITLE
Update the throttling limits documentation

### ISSUE THREAD

**Issue by gregory** [microsoftgraph/microsoft-graph-docs#8777]
The doc claims `4 concurrent requests on Beta endpoint` yet we hit it on v1. 
It's kinda hard to use the graph api to send outbounds, since this 4 concurrent requests limit force us to upload outbound attachments in series ... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df32e5f-8ccb-0c93-28d9-02392f9c7256
* Version Independent ID: 4aadd084-fb61-e89b-f63f-3b71622636b7
* Content: [Microsoft Graph throttling guidance - Microsoft Graph](https://docs.microsoft.com/en-us/graph/throttling#outlook-service-limits)
* Content Source: [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/throttling.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Thanks for letting us know! Those limits started applying to the v1.0 endpoint recently, see [the blog post](https://developer.microsoft.com/en-us/graph/blogs/beta-outlook-api-throttling-limits-deploying-to-v1-0-on-microsoft-graph-may-2020/)
I've authored a pull request #8783, whenever it gets merged it'll close this issue

**Comment by gregory** [comment]
Whats the best place to be aware of the changes happening on production ready endpoints? 
it feels like this information was buried on some blog post and I would have never been able to take proactive actions against this production change...

**Comment by nozhT** [comment]
Are the new limits also applied to the other national clouds (ex: Germany / China), or are they only for the global service?

**Comment by baywet** [comment]
@nozhT thanks for pointing this out. Edited my PR to include this distinction.
