### ISSUE TITLE
Call Record ID

### ISSUE THREAD

**Issue by Chameleon2525** [microsoftgraph/microsoft-graph-docs#8791]
Hello,

I have the latest C# Microsoft Graph SDK NuGet package (3.8.0) however this doesn't appear to have the **CallRecords** extension method to access call record IDs:

            var callRecord = await graphClient.Communications.CallRecords["{id}"]
    .Request()
    .GetAsync();

There also doesn't seem to be any information on how to isolate the call record ID for the HTTP GET request. I have tried the call id returned in the JSON response from the Create Call SDK method but no record is found.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd76e0a9-874e-1e5e-7238-77247a020064
* Version Independent ID: 08963ed9-21ee-773d-3532-75be9cd57e70
* Content: [Get callRecord - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/callrecords-callrecord-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/callrecords-callrecord-get.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by stephenjust** [comment]
Does #8797 provide sufficient clarification?

**Comment by Chameleon2525** [comment]
Hi Stephen, this does provide clarification thanks, however unfortunately it doesn't solve my reasoning for making the call record API call.

I was looking to access the call record to obtain the **joinWebUrl** property value to provide colleagues who miss an initial Teams bot call so they can join at their convenience.

I can see that the CallRecord object is only available after the call is complete, does the cloud communications API provide a URL for users to join while an automated call is still in progress? I can't seem to locate this in the docs currently. Thanks

**Comment by stephenjust** [comment]
For a joinWebUrl to be generated, you need to create an onlineMeeting for the call, which the bot uses to join. The onlineMeeting does have a joinWebUrl property that you can read.

**Comment by Chameleon2525** [comment]
Thank you for your assistance on this, I'll look into this method.
