### ISSUE TITLE
API call should be openShiftChangeRequests not openShiftsChangeRequests

### ISSUE THREAD

**Issue by buildbod** [microsoftgraph/microsoft-graph-docs#8794]
The openShiftChangeRequest section has a consistent typo.

The HTTP Requests are incorrectly stating the request to be .... openShiftsChangeRequests ...

HTTP Requests will fail using this.

The correct request is ... openShiftChangeRequests ...

i.e. delete the s after Shift openShift**s**ChangeRequests

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3090dc79-ae0e-fd62-7044-c97a24765e3a
* Version Independent ID: 621bb319-17d3-9210-ba43-00cb84f3432b
* Content: [Create openShiftChangeRequest - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/openshiftchangerequest-post?view=graph-rest-beta&source=docs)
* Content Source: [api-reference/beta/api/openshiftchangerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/openshiftchangerequest-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lramosvea** [comment]
Closing as the doc has been updated
