### ISSUE TITLE
Invalid filter clause on https://graph.microsoft.com/v1.0/teams('id')/channels/anotherid/tabs API

### ISSUE THREAD

**Issue by David-Rousselle** [microsoftgraph/microsoft-graph-docs#8796]
Since June 12th I get the error:
**Invalid filter clause**
when I call from Power Automate
https://graph.microsoft.com/v1.0/teams('id')/channels/anotherid/tabs
{
  "$filter": "name eq 'Wiki'",
  "$select": "id"
}
I didnt get the error before this date.
When I try in Graph Explorer, I don't get the error.
Any help ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002fd0aa-9008-9299-e29f-fb26f4d1b1e7
* Version Independent ID: bd94c468-347b-1db6-8c61-50d8a6ae58b6
* Content: [List tabs in channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamstab-list?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/teamstab-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamstab-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer      
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @David-Rousselle 

the name property is no longer available. It looks like Microsoft deprecated this property 👎  However, you can use the DisplayName property in your request 😀

I hope it helps

Regards,
Jarbas

**Comment by JarbasHorst** [comment]
I did some research and figured out that the name property has been deprecated since 2018. Now it was removed from the get tabs response! I wrote a short blog post which contains all my findings: https://www.devjhorst.com/2020/06/name-property-no-longer-supported-by-Graph-tabs-API.html

**Comment by David-Rousselle** [comment]
Thanks Jarbas, it solved my problem. I didn't think about this because when creating a tab, "name" was still working. Weird that the $filter on name was still working on Graph Explorer though, but not so surprised ;)
