### ISSUE TITLE
Unable to create App dependency using the request body in the example

### ISSUE THREAD

**Issue by PaulBremmer** [microsoftgraph/microsoft-graph-docs#8806]
When i try to create a new App Dependency using the same post paramaters as shown in te example request i get the following error:

{
    "error": {
        "code": "No method match route template",
        "message": "No OData route exists that match template ~/singleton/navigation/key/navigation with http verb POST for request /AppLifecycle/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('62f8b0a6-9088-4627-a9a6-e48debacd4c5')/relationships.",
        "innerError": {
            "date": "<Date>",
            "request-id": "<request ID>"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6e3468-6e5d-2f91-ec98-21491fa65978
* Version Independent ID: 91baacee-c77c-c953-2b2e-e08cff131831
* Content: [Create mobileAppDependency - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-apps-mobileappdependency-create?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-apps-mobileappdependency-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-apps-mobileappdependency-create.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
See issue #9147.  This is the same root issue.
