### ISSUE TITLE
Private Channels

### ISSUE THREAD

**Issue by m3ngi3** [microsoftgraph/microsoft-graph-docs#8840]
Any information in Private Channels?
We are able to create them through the Graph but when using the list call --> private channels are not included in results 🙏

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc7bd1a-6210-6010-c9ff-4245c342b20a
* Version Independent ID: e667c977-60ef-a81d-e94b-7eed5061b2c7
* Content: [List channels - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment]
Hi @m3ngi3 , I am not able to reproduce it. Can you please share your request Id and timestamp.

**Comment by m3ngi3** [comment]
Thank you for your time @Subhasish-msft !
It must have been a temporary issue because now I am getting the private channel when using the URI:
https://graph.microsoft.com/beta/teams/{6648712e-d804-4624-a086-7dc70579215f}/channels

As you can see I have a team with the same private channel twice because it did found the private channel on a check call:
![image](https://user-images.githubusercontent.com/47530580/85799913-57f9cc80-b740-11ea-98b8-2a97f985bb6e.png)

But now it seems to be included --> maybe a beta thing 😁
