### ISSUE TITLE
Create team, beta 403 Forbidden

### ISSUE THREAD

**Issue by mdanielcristian** [microsoftgraph/microsoft-graph-docs#8876]
Create team beta, not working, getting 403 - Forbbiden even from Graph Explorer

![image](https://user-images.githubusercontent.com/30260770/85844135-e9058d80-b7aa-11ea-9929-619617ae605e.png)

Even though on the Modify permissions tab, the permision is consented

![image](https://user-images.githubusercontent.com/30260770/85844219-076b8900-b7ab-11ea-8b6f-672ecd44786d.png)

I have the same experience in an Application Permission mode, using an App Registration.

Might be related to, same permissions are involved: [https://github.com/microsoftgraph/microsoft-graph-docs/issues/8872](url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Gousia-MSFT** [comment]
@mdanielcristian I could not repro the issue on my side. Could you please try [creating a team from a group](https://docs.microsoft.com/en-us/graph/api/team-put-teams?view=graph-rest-beta&tabs=http) and see if you are able to create the team successfully?

**Comment by mdanielcristian** [comment]
@Gousia-MSFT thanks, that works, but after digging a bit I found exactly what is not working for my scenario.
I still get forbidden when I try to create a team that has an owner, by setting the owner@odata.bind property as in [Example 2](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=http)
Same call works if I delete the owner property, but with it, I have the following error, even on graph explorer.

`{
    "error": {
        "code": "Forbidden",
        "message": "Failed to execute Templates backend request CreateTeamFromTemplateRequest. Request Url: https://teams.microsoft.com/fabric/templates/api/team, Request Method: POST, Response Status Code: Forbidden, Response Headers: Strict-Transport-Security: max-age=2592000\r\nx-operationid: 2d1e2774ccc04444811af62671926f8f\r\nx-telemetryid: |2d1e2774ccc04444811af62671926f8f.e969b0c6_1.\r\nX-MSEdge-Ref: Ref A: 8DB5BA12A3254FDF9F6E11CDCBE3861F Ref B: BLUEDGE0313 Ref C: 2020-06-29T12:15:24Z\r\nDate: Mon, 29 Jun 2020 12:15:24 GMT\r\n, ErrorMessage : {\"errors\":[{\"message\":\"Error when calling Middle Tier. Message: 'Failed to retrieve appliable Sku categories for the user'. Error code: 'Forbidden'. Status code: Forbidden.\"}],\"operationId\":\"2d1e2774ccc04444811af62671926f8f\"}",
        "innerError": {
            "date": "2020-06-29T12:15:25",
            "request-id": "92cc46b6-736d-4043-aa88-b8414efbafdf"
        }
    }
}`

**Comment by mdanielcristian** [comment]
@Gousia-MSFT sorry, just checked again with a different user and it worked. Seems to be an issue with a specific user on my end.

**Comment by Gousia-MSFT** [comment]
@mdanielcristian Could you please try sign out and sign in back to the Graph Explorer and try it for the user that fails?

**Comment by mdanielcristian** [comment]
@Gousia-MSFT  sorry, forgot to update, that user didn't have a teams license that's why I had the error. We can close this.
