### ISSUE TITLE
400 Bad Request - in case there's no mailbox associated with the user is not documented

### ISSUE THREAD

**Issue by biste5** [microsoftgraph/microsoft-graph-docs#8877]
When the endpoint is called for a user that has no mailbox associated, the API returns a 400 status code, with AuthenticationError in it.
I can verify / reproduce this with Postman

Found similar issue description here
https://www.reddit.com/r/AZURE/comments/4fzk8t/unable_to_get_profile_photo_using_microsoft/

This should be properly documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7710698-d997-c4c0-8515-dfb72d3551af
* Version Independent ID: 81ccdb02-f40d-277d-d51e-157d654a6e3a
* Content: [Get photo - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/profilephoto-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-get.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @jthake-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jthake-msft** [comment]
@kevinbellinger  is this true? hard to repo this in my test tenant.

**Comment by biste5** [comment]
I have just noticed the issue has been reported already in the past, for instance #5668

For the record, it can be reproduced easily for example by having an extra AAD tenant with 'guest' user(s) in it, and authenticating using an external user (which doesn't have mailbox by default)

Furthermore, also the Graph Toolkit component `Person` doesn't render and throws an exception in this scenario; due to this same issue.

**Comment by PeterChencha** [comment]
Hello @biste5 , thanks for reaching out. This limitation is highlighted on the note section of this documentation -> https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0.
