### ISSUE TITLE
Getting different results with credentialUserRegistrationDetails compared to Get-MsolUser

### ISSUE THREAD

**Issue by Smudo1291** [microsoftgraph/microsoft-graph-docs#8879]
I created a script to parse all AAD users who enrolled for at least one MFA method. 

Running it with the "interactive" Get-MsolUser cmdlet gets me 1929 results. Using the Azure Graph API (/beta/reports/credentialUserRegistrationDetails) gives me 1845 results. 

Taking a closer look at the users not present in the Graph API query shows that they ARE actually enrolled. I also confirmed that with the Sign-Ins over the last 7 days. MFA must be enrolled and working for at least some of them (I didn't test all).

Isn't the Graph API query providing real-time data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8238a381-7421-a45f-8972-d71e23a3a380
* Version Independent ID: 35235db8-2017-ff94-1574-ec10671a7ba9
* Content: [credentialUserRegistrationDetails resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/credentialuserregistrationdetails?view=graph-rest-beta#feedback)
* Content Source: [api-reference/beta/resources/credentialuserregistrationdetails.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/credentialuserregistrationdetails.md)
* Product: **reports**
* Technology: **microsoft-graph**
* GitHub Login: @khotz
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cjklouda** [comment]
I'm seeing the same behavior.  We have a simple lookup to determine if a user has registered for MFA.  I can walk a user through registering and, after they have successfully registered, I can perform the lookup and in many cases they will still show as unregistered.  It often takes several hours or a day for the graph to show their registration status.  Is there a forward sync (similar to Exchange) that occurs?  Is there an expectation as to the time delay between a registration and it being reflected in the graph?

**Comment by shrikantkulkarni23** [comment]
Any updates? I am getting significant difference between get-msoluser and credentialUserRegistrationDetails report.

**Comment by alextriaca** [comment]
I'm running into this issue as well. I created a new testing tenant, added test users and then ran the `credentialUserRegistrationDetails` query. I get an empty result back. It has now been 4 days and there is still only an empty result (`"value":[]`). All users are assigned an E5 license so this report should definitely be populated.

**Comment by FaithOmbongi** [comment]
Hello @Smudo1291 , @cjklouda , @shrikantkulkarni23 , @alextriaca ,

We have flagged this as a functionality issue and raised it up with Engineering.

Unfortunately this forum isn't monitored for functionality issues, but we recommend that you post this question at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) where issues such as these are closely monitored. We have a pool of Engineers ready to look into this and update on resolution.

No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.

**Comment by alextriaca** [comment]
@FaithOmbongi  thanks for the reply and suggestions. You mentioned that this issue has been raised to the engineering team. Do you possibly have a ticket number or something we can use to track this issue?

**Comment by FaithOmbongi** [comment]
@alextriaca Sorry, I cannot share internal comms. Just post the issue at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*) and you'll receive a response in good time.

After you post your Q there, and if it's not too much to ask, you can post here it's link to help other customers facing the same issue follow the question and track it's resolution. Thanks.
