### ISSUE TITLE
Deleted members from group still showing in teams

### ISSUE THREAD

**Issue by RonakJain7** [microsoftgraph/microsoft-graph-docs#8896]
Steps : 

1. Create Teams.
2. Remove admin/members via 

graphClient.groups("{id}").members("{id}").reference()
	.buildRequest()
	.delete();

graphClient.groups("{id}").owners("{id}").reference()
	.buildRequest()
	.delete();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1141e6-3381-6433-0fdc-187b65eb299d
* Version Independent ID: 5f05d149-8a88-5dea-35a3-02ade58fa9aa
* Content: [Remove member - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/group-delete-members?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/group-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/group-delete-members.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RonakJain7** [comment]
Any Update?

**Comment by vineet00pareek** [comment]
Hey, 
I am also facing the same issue from the last couple of days, please provide any suggestion to resolve or workaround to update the deleted members in the group.

**Comment by arpit107** [comment]
I am facing the same issue that even after removing user from group, it is visible in group. When i deleted that particular user it was removed successfully. The proof is when i again try to delete the same user it gives error: Error message: Resource '<user-id>' does not exist or one of its queried reference-property objects are not present.
Please provide a solution to this problem.

**Comment by RonakJain7** [comment]
Any update on this ?

**Comment by HN5** [comment]
Same issue using Power Platform (Power Automate / Flow) to make the HTTP calls to Graph API to remove an account from a team's membership (tested with app permission and delegated permission with same behaviour)

No Error on HTTP response using /v1.0 (or /beta) endpoints Removing account is properly done on Microsoft 365 Groups backend but not on Teams.

Check on SPO/Teams/Outlook/AAD Admin Center show everything is good (meaning the account is removed)

Also checking on Graph API (through Graph Explorer) itself shows that the account is no longer present on the target team immediately after the calls are done.

BUT on Teams client interface the account is still present in owners/members

Other undesired behaviour discovered : the account still have the capabilities to communicate/work with the team (creating channels, posting messages, being tagged ...)

**Comment by Gousia-MSFT** [comment]
@RonakJain7 Thanks for reporting this. We could repro the issue and we are looking into this.

**Comment by RonakJain7** [comment]
Any update on this issue, As this highest priority for us right now ?

**Comment by Gousia-MSFT** [comment]
@RonakJain7 How long has it been since you have deleted the member? Group->Team sync is not instantaneous and it take time to sync them.

**Comment by RonakJain7** [comment]
@Gousia-MSFT : May I know average time taken in order to reflect correct changes ?

**Comment by Gousia-MSFT** [comment]
@RonakJain7 It can take upto 48 hours (or even longer at times and one of the owners needs Teams client running too). The near instant sync is best effort and if multiple operations were done on the group. It will take time for system to sync them.

**Comment by HN5** [comment]
just received this information from M365 Service Heal notification

Some users are seeing delays when add member changes are made to Microsoft Teams using Microsoft Graph
TM218800, Microsoft Teams, Dernière mise à jour: July 19, 2020 5:56 AM
Heure de début: July 14, 2020 6:00 PM, Heure de fin: July 18, 2020 10:45 PM

is this related to this issue or not ?

**Comment by HN5** [comment]
Any update on this issue, or comment on previous shared detail ? 
Currently this issue is highest priority for us right now due to impact on solutions built using AAD Application and Graph API endpoints. Thx for help.

**Comment by Gousia-MSFT** [comment]
We are checking this on our side. Could you please share the user ID's and group ID's for which you see this issue?

**Comment by HN5** [comment]
a just reacreate the "bug" to let you time to look at 

user ID : 642743f0-8e13-4880-83ae-60914ca05560
group ID : 4a7ee3a0-9087-4f0e-aa16-6bae4db44a84

**Comment by HN5** [comment]
@Gousia-MSFT any update or you need more details ? 
Issue is still present is a long delay to reflect permissions changes in Teams. Meaning this is a big issue because the user is removed from Groups/AAD but can still interact with the Teams (send message, delete channels and even delete the team )

Any workaround you suggest to handle this case ?
Is the beta endpoint better to use on this scenario : https://www.devjhorst.com/2020/07/manage-teams-membership-using-Microsoft-Graph-Teams-API.html

**Comment by Gousia-MSFT** [comment]
@HN5 We are checking this internally! Will get back to you with an update on this.

**Comment by Gousia-MSFT** [comment]
@HN5 Yes- the new beta API link shared above is a better option to try. Please do keep in mind that it is in beta, but it is aimed at solving the delayed sync problem.
