### ISSUE TITLE
Example Gives HTTP 404

### ISSUE THREAD

**Issue by sambetts** [microsoftgraph/microsoft-graph-docs#8929]
Running a GET on "https://graph.microsoft.com/beta/onPremisesPublishingProfiles/applicationProxy/publishedResources?$expand=agentGroups"

...gives error:

{
    "error": {
        "code": "",
        "message": "No HTTP resource was found that matches the request URI 'https://eur1.msgraph.msappproxy.net:8082/v2/onPremisesPublishingProfiles('applicationProxy')/publishedResources?$expand=agentGroups'.",
        "innerError": {
            "date": "2020-07-01T09:24:10",
            "request-id": "d03a11d5-1adb-490d-a9e7-90ea87d63f29"
        }
    }
}

Any ideas?

Cheers,

Sam 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a52a0fda-8cef-9a49-7f4e-b36f88beb661
* Version Independent ID: a2ba1c48-b3de-3fa8-957f-0b2c02581a53
* Content: [List publishedResources - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/publishedresource-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/publishedresource-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/publishedresource-list.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @japere
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by japere** [comment]
Are you trying to list all the connector groups for App Proxy? Have you tried this call: https://docs.microsoft.com/en-us/graph/api/connectorgroup-list?view=graph-rest-beta&tabs=http

**Comment by sambetts** [comment]
Hi Jasmine,

I'm trying to read the app-proxies setup in Azure AD. The example you gave above works fine, but just gives me the connector groups. The error I'm getting back from my example feels like there's a configuration error on the Graph end or something maybe...?


// Sam

**Comment by japere** [comment]
I'm sorry, I see now that you are trying to list out the configuration for apps with app proxy configured. We don't have a way to enumerate this out yet. You can get the configuration for a specific app by calling: GET https://graph.microsoft.com/beta/applications/[appID]/onpremisespublishingprofile. We're working on a way to improve this so you can list out all apps and their configuration. You can do this today via PowerShell. https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy-powershell-samples. We also recently released a tutorial for how to use the APIs end to end to configure AppProxy. https://docs.microsoft.com/en-us/graph/application-proxy-configure-api?view=graph-rest-beta

**Comment by sambetts** [comment]
Ok thanks; could be worth adding a note to the documentation to say it's not supported yet?

**Comment by japere** [comment]
Yes, we will leave a note in the docs on this topic. Thank you for your feedback.
