### ISSUE TITLE
v1.0 ETA?

### ISSUE THREAD

**Issue by jacobwbutler** [microsoftgraph/microsoft-graph-docs#8938]
What is the ETA for application templates to move to v1.0?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 105c3b64-9092-e23a-0e05-d57136a72278
* Version Independent ID: 5ff0c889-dd39-e40d-a919-e42bf169ea7e
* Content: [applicationTemplate resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/applicationtemplate?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/resources/applicationtemplate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/applicationtemplate.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @luleonpla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by luleonpla** [comment]
Hi @jacobwbutler,

We're working on that as we speak. We target early September. Have you notice any problem in the beta version we should be aware before moving to v1.0?

**Comment by jonbe16** [comment]
Not sure if this is a Graph issue or not but the List win32LobApps is not populating some of the fields, for example uninstallCommandLine, detectionRules and requirementRules. The installCommandLine field is populated. Is this fixed in V1.0?

**Comment by luleonpla** [comment]
@jonbe16 I don't think those properties relates to the applicationTemplate API: https://docs.microsoft.com/en-us/graph/api/resources/applicationtemplate?view=graph-rest-beta

Could you please add a link to the apps you're mentioning.

**Comment by jonbe16** [comment]
List win32LobApps? https://docs.microsoft.com/en-us/graph/api/intune-apps-win32lobapp-list?view=graph-rest-beta

**Comment by luleonpla** [comment]
Thanks for the context @jonbe16. The win32LobApps aren't in scope for that API. This APIs returns the application templates you can use in Azure AD to enable single sign-on for those apps. Example, Salesforce, ServiceNow, etc

**Comment by jacobwbutler** [comment]
@luleonpla Thanks for the response - please update here if timelines shift :).

To answer your question, it would be helpful if appId could be included in the application template - this allows for easier correlation from the template to the application, instead of having to go from the application to the template (via applicationTemplateId). Further details in this [thread](https://github.com/microsoftgraph/microsoft-graph-docs/issues/8129)

**Comment by chrisappianti** [comment]
@luleonpla I noticed that the object id of the application and service principal is not returned when calling instantiate on an application template. Is there a known issue around this?

**Comment by lcleonp** [comment]
@chrisappianti you should be getting the object id for app and service principal objects. Below is a screenshot of what I see using Graph explorer. What are you using?

![image](https://user-images.githubusercontent.com/65643898/88979531-be5d9780-d276-11ea-8f1c-d45ae3c6061f.png)

**Comment by chrisappianti** [comment]
@lcleonp  I am using the C# code: 

GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var displayName = "My custom name";

await graphClient.ApplicationTemplates["{id}"]
	.Instantiate(displayName)
	.Request()
	.PostAsync();

The resulting has returns with id field of null in the Application and ServicePrincipal. I will try using the HTTP request

**Comment by lcleonp** [comment]
Yes, in that scenario we do have a inconsistency. We're working on fixing that before going GA.

For now, you can get the object Ids using the additionalData properties in the response. 

```
public async Task<Beta.ApplicationServicePrincipal> CreateApplicationTemplate(string id, string appDisplayName)
        {
            var result = await _graphBetaClient.ApplicationTemplates[id]
                .Instantiate(appDisplayName)
                .Request()
                .PostAsync();

            string spoId = result.ServicePrincipal.AdditionalData.First(x => x.Key == "objectId").Value.ToString();
            string appoId = result.Application.AdditionalData.First(x => x.Key == "objectId").Value.ToString();

            logger.Info("applicationTemplate created with spoId =" + spoId + "app object Id =" + appoId);
            //logger.Info("applicationTemplate created with spoId =" + result.ServicePrincipal.Id + "app object Id =" + result.Application.Id);
            return result;
        }
```

**Comment by davidmu1** [comment]
We should probably go ahead and close this issue since there does not currently seem to be a change to the article.

**Comment by luleonpla** [comment]
#please-close
