### ISSUE TITLE
Adding Incoming Webhook through API is not returning Webhook URL

### ISSUE THREAD

**Issue by noopurit** [microsoftgraph/microsoft-graph-docs#8953]
[Enter feedback here]
Hi,

If I want to add an "Incoming Webhook" app to one of my Teams, I should receive the Webhook URL in the response. How else would I be able to post notifications to the webhook otherwise? 

Noopur

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ac1bdb-1ac9-e0aa-67a0-d92ab2d7d7f9
* Version Independent ID: beed2749-a8a2-9670-f3e4-a1bba9e35a62
* Content: [teamsApp resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-US/graph/api/resources/teamsapp?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/teamsapp.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/teamsapp.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Abhijit-MSFT** [comment]
There is no other way to create incoming webhook.
[Documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#add-an-incoming-webhook-to-a-teams-channel)

**Comment by noopurit** [comment]
> There is no other way to create incoming webhook.
> [Documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook#add-an-incoming-webhook-to-a-teams-channel)

That doesn't make real sense. If you are providing an API end point to add Apps programatically, then these webhooks are also an app. Moreover, the API documentation doesn't mention an exception for this type of app anywhere. Even if it's not a bug, you should consider adding this as a feature to existing API. It can be very very useful for Business applications to collaborate their notifications with MS Teams with minimal user engagement.

**Comment by Abhijit-MSFT** [comment]
You can go to [Uservoice](https://microsoftteams.uservoice.com/) and raise this feature request.

**Comment by noopurit** [comment]
> You can go to [Uservoice](https://microsoftteams.uservoice.com/) and raise this feature request.

Added https://microsoftteams.uservoice.com/forums/555103-public/suggestions/40840123-adding-incoming-webhook-through-api
