### ISSUE TITLE
To filter signInActivity do we need a Premium license?

### ISSUE THREAD

**Issue by anasimao** [microsoftgraph/microsoft-graph-docs#8988]
In this doc we have the next info about the signInActivity:
"Get the last signed-in date and request ID of the sign-in for a given user.
Supports $filter, but not with any other filterable properties.
Returned only on $select. Read-only."

But when we test this we see that a filter only works when we have a Premium license.
If this expected please add it to the doc.

Also in this other doc:
https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-manage-inactive-user-accounts#what-edition-of-azure-ad-do-i-need-to-access-the-property

Where it explains how to use the signInActivity filter is mentioned that all editions of Azure AD should be able to use it. This would also need to be updated if a Premium license is required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8446021-6786-c54c-066f-d99ba4644312
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
API doc has been updated to add the licensing note. Closing this issue.
