### ISSUE TITLE
Cannot send/reply to a message either in channel or private chat.

### ISSUE THREAD

**Issue by hkadakia** [microsoftgraph/microsoft-graph-docs#8998]
I am trying to use the Graph API to send/reply to a message in MS Teams both channel or in a private chat, but I am getting Unknown Error.

Below are POST URL requests:

https://graph.microsoft.com/beta/chats/{chat-id}/messages/{message-id}/replies
https://graph.microsoft.com/beta/chats/{chat-id}/messages/
https://graph.microsoft.com/beta/teams/{team-id}/channels/{channel-id}/messages/{message-id}/replies
https://graph.microsoft.com/beta/teams/{team-id}/channels/{channel-id}/messages

For all the above 4 requests I am getting Unknown Error.
```
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-07-08T01:06:55",
      "request-id": "52beb708-1737-4a62-baab-7db4e7169dc1"
    }
  }
}
```
App permissions are correctly set to Delegated with "ChannelMessage.Send" and "Chat.ReadWrite"
<img width="768" alt="Screen Shot 2020-07-07 at 6 12 02 PM" src="https://user-images.githubusercontent.com/6836802/86862099-6370c000-c07d-11ea-8bad-b72ab775d0cb.png">

I do have permissions to access Teams through Protected API request. Please suggest what needs to be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Hello @hkadakia 

in order to send messages to a channel one of the following delegated permissions is required as: ChannelMessage.Send, Group.ReadWrite.All. Since you have ChannelMessage.Send (delegated), sending a message should work correctly.

Can you please provide the code you are using to send the messages?

Regards,
Jarbas

**Comment by hkadakia** [comment]
Hey @JarbasHorst 
I tried it through postman and I got the above response. Here's the request and body in case its helpful to narrow down the issue.

```
 https://graph.microsoft.com/beta/teams/a0fcce7e-7fa9-463a-a776-9d0f0e47cb9a/channels/19:f73f6eddbeaf4df38d369fd2bad81fa0@thread.tacv2/messages/1594185684424/replies

{"body": {
    "contentType": "html",
    "content": "Hello World"
  }
}

Code:
response = requests.request("POST", url, headers=headers, data = payload)
print(response.text.encode('utf8'))
```

Response:
```
{
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-07-08T16:18:44",
      "request-id": "755b8de4-3eb6-4e37-a20d-c5bddb348663"
    }
  }
}
```

**Comment by hkadakia** [comment]
Do I need to remove application permission for this to work? I tried giving more permissions but still get the unknown error.
```
2020-07-10 00:32:25,284 : [INFO] [teams_helper.py:send_reply_teams_message:832] Resource to be replied: chats('19:c7c7084f247245cdb648872d2d8fadd7@thread.v2')/messages('1594341138372')
2020-07-10 00:32:25,285 : [INFO] [helper.py:make_request:201] Graph API request https://graph.microsoft.com/beta/chats/19:c7c7084f247245cdb648872d2d8fadd7@thread.v2/messages Method: POST
2020-07-10 00:32:25,916 : [WARNING] [teams_helper.py:send_reply_teams_message:841] Received error when replying to message: 401 {'error': {'code': 'UnknownError', 'message': '', 'innerError': {'date': '2020-07-10T00:32:25', 'request-id': 'b487de94-e0fe-4109-b3eb-d7926dcdf984'}}}
```

**Comment by RamjotSingh** [comment]
Are you sending the request in delegated (as in user) context or app only context? The request is only supported in delegated context (as the documentation lists). 

One way to check context would to check the token. If the token contains scp claim then it a delegated context token, if it contains roles claim it is an app only token and thus not supported. You can check token at jwt.ms or similar token inspectors.

**Comment by hkadakia** [comment]
@RamjotSingh Thanks for your reply above. I did check the token and it looks to be app only token. Is there a way to get a token which has both delegated and app only context? Currently I am following this steps to get the app token : [Auth Token](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc).

**Comment by RamjotSingh** [comment]
No, a token can only be delegated or app, not both.
