### ISSUE TITLE
Search query example for group results in error

### ISSUE THREAD

**Issue by 2ATCaroline** [microsoftgraph/microsoft-graph-docs#9016]
When testing the above search query for groups in the graph-explorer (selecting the beta):
https://graph.microsoft.com/beta/groups/?$search="displayName:OneVideo"
I receive the following error:
This query is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#search-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by 2ATCaroline** [comment]
After changing the URL to:
https://graph.microsoft.com/beta/groups/?$count=true&$search="displayName:OneVideo"
And adding the request header:
key:consistencylevel with value:eventual
it does work!
(and changing OneVideo to HR I also get results from the sample account :) )

**Comment by FaithOmbongi** [comment]
Apologies @2ATCaroline for the delayed response.

As you've realized, `$search` is a query parameter what works only when you add the **ConsistencyLevel** header set to `eventual`. This behavior is also in:
- other query parameters (specifically `$count`, `$search`)
- some `$filter` operators (`endsWith`, `ne`, `NOT`) - require both the header & `$count=true`.
- some `$filter` operators + property combinations, for example, the **companyName** property of User resource supports `eq`, `ne`, `NOT`, `ge`, `le`, `in`, `startsWith` - require both the header & `$count=true`.

Additional guidance for this will be available via the [Use query parameters ](https://docs.microsoft.com/en-us/graph/query-parameters?context=graph%2Fapi%2F1.0&view=graph-rest-1.0)page.

Note that search on directory objects also works based on tokenization.
