### ISSUE TITLE
How to schedule 'restart synchronization job' using MS Graph?

### ISSUE THREAD

**Issue by nikusworld** [microsoftgraph/microsoft-graph-docs#9045]
[Enter feedback here]

I can restart a 'synchronization job' manually from Graph using https://graph.microsoft.com/beta/servicePrincipals/xxxxx/synchronization/jobs/gsuite.xxxx/restart
Authorization: Bearer <token>
Content-type: application/json

{
   "criteria": {
       "resetScope": "Watermark, Escrows, QuarantineState"
   }
}

Question- how can I schedule this job to run automatically, like trigger the re-sync at a predefined time?

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84b8b600-e42b-3294-b8c7-59dc7cc0d9b6
* Version Independent ID: 07276223-cf3f-5c2d-7efe-27bcdd17009c
* Content: [Restart synchronizationJob - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-restart?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/synchronization-synchronizationjob-restart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/synchronization-synchronizationjob-restart.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @ArvindHarinder1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by ArvindHarinder1** [comment]
Hi this isn't possible today. Could you describe the scenario? What's the trigger for forcing the job and how frequent is it? We do have the following API that we just released: https://docs.microsoft.com/en-us/graph/api/synchronization-synchronizationjob-provision-on-demand?view=graph-rest-beta

**Comment by nikusworld** [comment]
Hi Arvind,



Thanks for the reply.



We are leveraging 'G Suite Connector by Microsoft' Enterprise app in Azure for syncing our selective identities (users and groups) from AAD-GCP.



Sync is working fine to some extent, the problem comes in if we add a user in Project permissions group first>sync> then at a later time we add user in Master Users Sync group which will create the identity in GCP. If we do it other way around, like add user in Master Sync group first and then to Project permissions group then everything works as expected.



I had a ticket opened with Azure Product engineering Team and they have confirmed this behavior is expected by design and MS is working on fixing this in upcoming release.



So, for the time, we are left with the option to restart the sync from the scratch, this will help us to update group memberships on GCP side. We would like to schedule the restart of ‘Full Sync’ once or twice a day.



As I’ve mentioned before with MS Graph I am able to do this manually but no idea as-in how to automate this job.




________________________________

**Comment by ArvindHarinder1** [comment]
@nikusworld you would have to build an app that calls the restart API to accomplish what you are  looking for. Unfortunately the API only supports delegated permissions today. The issue where memberships aren't updating should be addressed by end of next week so you don't have to do this.

**Comment by nikusworld** [comment]
@ArvindHarinder1  Thank you!
