### ISSUE TITLE
resourceBehaviorOptions Graph Release date

### ISSUE THREAD

**Issue by GaneshPrabuBaburaj** [microsoftgraph/microsoft-graph-docs#9061]
Could you please confirm whether the resourceBehaviorOptions and "HideGroupInOutlook" is released to Graph v1.0 version. Are is it still in beta version?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfbb1507-6e3c-c2d4-54ae-874805cf1d12
* Version Independent ID: 8be90c8c-2671-cc5e-b50d-64d79335a2a0
* Content: [Set Microsoft 365 group behaviors and provisioning options - Microsoft Graph](https://docs.microsoft.com/en-us/graph/group-set-options)
* Content Source: [concepts/group-set-options.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/group-set-options.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by GaneshPrabuBaburaj** [comment]
May I have update on the query. Seems this option is available in latest graph client dll. Is the same available in API ?

**Comment by GaneshPrabuBaburaj** [comment]
Hi Team, Could you please update me on the question?

**Comment by davidmu1** [comment]
This property is defined on the v1.0 Group resource page:


resourceBehaviorOptions | String collection | Specifies the group behaviors that can be set for a Microsoft 365 group during creation. This can be set only as part of creation (POST). Possible values are AllowOnlyMembersToPost, HideGroupInOutlook, SubscribeNewGroupMembers, WelcomeEmailDisabled. For more information, see Set Microsoft 365 group behaviors and provisioning options.


No change identified for the page. Closing the issue.
