### ISSUE TITLE
lastModifiedDateTime odata filter including channel messages outside of window on inital delta

### ISSUE THREAD

**Issue by liiamjones** [microsoftgraph/microsoft-graph-docs#9063]
I have a tenant with 1386 channel messages in. of which, 164 have been created/modified/deleted since 2019-11-01T00:00:00Z 
When i perform channel message delta queries for every channel in the tenant with `?$filter=lastModifiedDateTime gt 2019-11-01T00:00:00Z ` i get back 247 channel messages, of which, 83 have not been created/modified/deleted since 2019-11-01T00:00:00Z. 

An example of this query is

`https://graph.microsoft.com/beta/teams/131EC081-ABA3-4643-B603-470DE6209081/channels/19:4ab1abc56abe4cf0a5df2d8f8bf0eb48@thread.skype/messages/delta?$filter=lastModifiedDateTime gt 2019-11-01T00:00:00Z`

it returns me messages including ones like below, that are not created, modified or deleted inside the lastModifiedDateTime  window. I cannot see a pattern to these 'old' messages, some are deleted, some aren't, some are modified, some arene't. this particular example doesnt have any replies, nor is it a reply to another message.

```
        {
            "@odata.type": "#microsoft.graph.chatMessage",
            "replyToId": null,
            "etag": "1571221369879",
            "messageType": "message",
            "createdDateTime": "2019-10-16T10:22:49.879Z",
            "lastModifiedDateTime": null,
            "deletedDateTime": "2019-10-16T10:22:49Z",
            "subject": null,
            "summary": null,
            "importance": "normal",
            "locale": "en-us",
            "webUrl": "https://teams.microsoft.com/l/message/19%3A4ab1abc56abe4cf0a5df2d8f8bf0eb48%40thread.skype/1571221369879?groupId=131EC081-ABA3-4643-B603-470DE6209081&tenantId=f7af6be0-1017-4a4e-8e81-5325b780ef98",
            "from": null,
            "policyViolation": null,
            "id": "1571221369879",
            "body": {
                "contentType": "text",
                "content": null
            },
            "attachments": [],
            "mentions": [],
         }
```

this particular message appears in the delta for that channel up to and including march 2020, eg. 

`https://graph.microsoft.com/beta/teams/131EC081-ABA3-4643-B603-470DE6209081/channels/19:4ab1abc56abe4cf0a5df2d8f8bf0eb48@thread.skype/messages/delta?$filter=lastModifiedDateTime gt 2019-03-01T00:00:00Z` still contains it

`https://graph.microsoft.com/beta/teams/131EC081-ABA3-4643-B603-470DE6209081/channels/19:4ab1abc56abe4cf0a5df2d8f8bf0eb48@thread.skype/messages/delta?$filter=lastModifiedDateTime gt 2019-04-01T00:00:00Z`  doesnt contain it

I have a further 82 examples of messages being return outside of the lastModifiedDateTime filter if you'd like to see any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95fa912d-43d1-099b-44d5-fdcdaae00db7
* Version Independent ID: faa5b2f3-45a4-ff2f-24b7-09b0363aea8c
* Content: [chatMessages: delta - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/chatmessage-delta?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/chatmessage-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/chatmessage-delta.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment]
@liiamjones , Can you please share a recent request Id and timestamp for the API call.

**Comment by Gousia-MSFT** [comment]
Please re-open if the issue persists
