### ISSUE TITLE
How do I set the Bearer token in this example. 

### ISSUE THREAD

**Issue by chadsowald** [microsoftgraph/microsoft-graph-docs#9069]
Hi.  I want to pass in my own HttpClient that I dependency inject.  This example shows how to pass in your own HttpClient, but lacks showing how to set/pass the token.  Can you please add information on that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d7184ab-9db8-f040-e61f-f8cef01df25e
* Version Independent ID: ca61d03d-4a6d-21fe-31cc-08f339981ffe
* Content: [Customize the Microsoft Graph SDK service client - Microsoft Graph](https://docs.microsoft.com/en-us/graph/sdks/customize-client?tabs=csharp)
* Content Source: [concepts/sdks/customize-client.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/sdks/customize-client.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @darrelmiller
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by darrelmiller** [comment]
You can create your own implementation of the IAuthenticationProvider that returns a token and pass it in to the CreateDefaultHandlers method. We generally don't recommend people manage their own tokens and let MSAL do that instead, hence why we don't have a sample showing how.
