### ISSUE TITLE
Not able to Send message in channel 

### ISSUE THREAD

**Issue by shrikantupadhyay-tudip** [microsoftgraph/microsoft-graph-docs#9082]
I'm not able to send message to channel 
{
  "error": {
    "code": "Unauthorized",
    "message": "Unauthorized",
    "innerError": {
      "date": "2020-07-13T16:25:12",
      "request-id": "6c81232f-3fab-4eb9-a2c9-f6ed962a6173"
    }
  }
}
I've proper set of permissions 
![ss](https://user-images.githubusercontent.com/58065145/87336486-8e688180-c55f-11ea-96b0-a5b710a3c090.png)
![ss2](https://user-images.githubusercontent.com/58065145/87336489-8f99ae80-c55f-11ea-80f1-fdef9f5ff569.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a53c325-9d51-861a-36aa-5bb4e69d9456
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Abhijit-MSFT** [comment]
Can you please check your token in jwt.io and confirm if you see all the above mentioned permissions in it.

**Comment by shrikantupadhyay-tudip** [comment]
@Abhijit-MSFT  I've these set of permissions.
"roles": [
    "Chat.UpdatePolicyViolation.All",
    "ChannelSettings.Read.All",
    "Channel.ReadBasic.All",
    "Group.Read.All",
    "Directory.ReadWrite.All",
    "Group.ReadWrite.All",
    "Directory.Read.All",
    "ChannelMember.Read.All",
    "Chat.Read.All",
    "ChannelMessage.Read.All",
    "Chat.ReadWrite.All",
    "ChannelMember.ReadWrite.All",
    "ChannelSettings.ReadWrite.All",
    "Channel.Create",
    "Chat.ReadBasic.All"
  ]

**Comment by hkadakia** [comment]
@shrikantupadhyay-tudip In order to send message you need Delegated context token. From the context info above, it seems the context you sending the message is using Application context token, which is currently not supported.

Since you have already gotten the context info for the token above, you can check if the token contains scp claim then it is a delegated context token, if it contains roles claim it is an app only token and thus not supported.

**Comment by shrikantupadhyay-tudip** [comment]
@hkadakia 
can you help me, how can i get "Delegated context token" ?

**Comment by hkadakia** [comment]
@shrikantupadhyay-tudip You may want to get the delegated token using refresh token. When making a request for getting token send grant_type=refresh_token, scope="openid offline_access ChannelMessage.Send" and refresh_token="..." which you should have received when you authorized the org.

You can read more about how to get delegated token here: [Delegated Token Context](https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#5-use-the-refresh-token-to-get-a-new-access-token)

**Comment by shrikantupadhyay-tudip** [comment]
Thanks @hkadakia for your help.
