### ISSUE TITLE
Add Guest not working

### ISSUE THREAD

**Issue by zeitler** [microsoftgraph/microsoft-graph-docs#9093]
Hi

Since yesterday it's not possbile to add guests to channels.
My app had this feature working, and suddenly I get an error: "Failed to execute request"

I've tried the same process in admin center (https://admin.teams.microsoft.com) and I receive that it's not possible to add the selected users.

What have changed?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497ad1e7-5a61-731f-e0e9-75b5cb9336c8
* Version Independent ID: 776a8387-3525-7289-51bd-1232f58d283a
* Content: [Add conversationMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
We could not reproduce the issue on our side. Could you please check the permissions? Also could you please share your  request body?

**Comment by zeitler** [comment]
Hi
After one week everything started to work again. 

Thank you
