### ISSUE TITLE
Beta nameditem_add not working as expected

### ISSUE THREAD

**Issue by ValerioSevilla** [microsoftgraph/microsoft-graph-docs#913]
Issue:

nameditem_add method in beta endpoint not working as expected

Article:

Hi,

I have been trying to add a named item using [nameditem_add method in beta](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/nameditem_add.md). The most I can get now is this error:

```javascript
{
  "error": {
    "code": "ItemNotFound",
    "message": "The requested resource doesn't exist.",
    "innerError": {
      ...
    }
  }
}
```

This is the request URL I have:

`https://graph.microsoft.com/beta/me/drive/items/<itemId>/workbook/names/add`

(replacing `<itemId>` with an actual item Id).

With this request body:

```javascript
{
	"name": "APITestName1",
	"reference": "=B3+A3",
	"comment": "Awesome named range"
}
```

I'm opening this issue here as I think it may be a documentation issue rather than a code issue. It looks like this method is not being exposed at the moment in the Beta API.

**Comment by ValerioSevilla** [comment]
Update:

After multiple tests, we have found out that:

- There is no explicit way of setting the type of the named item through this method.
- In general, it is created with type String.
- The only way to create a correct named item with type Range is by setting a reference like this: **=Sheet1!$A$1:$B$2** (including the sheet name and the ‘$’ characters).
- A Range item can also be created with a reference that does not include the ‘$’ character: **=Sheet!A1:B2**. But when including the named range in a formula from other cell, the formula is not correctly calculated. For example, if all cells in the range contain numbers, and we create this formula in other cell: **=SUM(<namedItem>)**, it always returns 0. However, if the named range includes the ‘$’ signs, it works fine.

- There is a Delete Named Item method in Beta version that is not documented at all:
DELETE https://graph.microsoft.com/beta/me/drive/items/<id>/workbook/names(<name>)

**Comment by isvargasmsft** [comment]
This one is fixed. My deepest apologies for the delay.
