### ISSUE TITLE
Missing a new property for HRD policy

### ISSUE THREAD

**Issue by dkershaw10** [microsoftgraph/microsoft-graph-docs#9135]
This topic talks about how to configure sign-in with an email address: https://docs.microsoft.com/en-gb/azure/active-directory/authentication/howto-authentication-use-email-signin#enable-user-sign-in-with-an-email-address

It indicates a new property called "AlternateIdLogin" but this is not documented...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec647fc-2af6-578b-f234-54b8f9f11246
* Version Independent ID: dd847f48-8a3c-0cd5-e69b-024f1744011f
* Content: [homeRealmDiscoveryPolicy resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/homerealmdiscoverypolicy?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/homerealmdiscoverypolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/homerealmdiscoverypolicy.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @hpsin
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hpsin** [comment]
#assign-to:hpsin Can't find Scott's GH handle

**Comment by hpsin** [comment]
Fixed by https://github.com/microsoftgraph/microsoft-graph-docs/pull/9967 
#please-close
