### ISSUE TITLE
beta - $filter and $select do not reference the same oData type as the initial get request

### ISSUE THREAD

**Issue by middletoni** [microsoftgraph/microsoft-graph-docs#9138]
when performing a /team/{team_id}/members get, the odata type returned is microsoft.graph.aadUserConversationMember.  When trying to perform a $filter or $select (on email for instance), it is searching microsoft.graph.ConversationMember, which does not contain the same properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a4fa954-8084-24e0-cef0-591373c8b2b8
* Version Independent ID: 83151040-4b99-2389-87da-b49443af92bf
* Content: [List members - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-list-members.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@middletoni , API returns list of members in Team. while using `$filter` or `$select` query parameter you can check with following [documentation ](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter) for it

**Comment by middletoni** [comment]
@Trinetra-MSFT  I understand that.  The issue I'm running into, is the unfiltered odata result is of type aadUserConversationMember, but when you perform a filter or select, it is running against just ConversationMember, which doesnt have the correct fields.

**Comment by Trinetra-MSFT** [comment]
@middletoni , Could you please tell us what URL you are trying while using query parameters?

**Comment by middletoni** [comment]
@Trinetra-MSFT When I call: https://graph.microsoft.com/beta/teams/<myteamid>/members with no filter/select parameters, I get something like this (I truncated to just one record) - Note the odata.type being returned:

{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#teams(valueishere)/members",
    "@odata.count": 5,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "idishere",
            "roles": [
                "owner"
            ],
            "displayName": "Name here",
            "userId": "14439a1e-idhere",
            "email": "emailhere"
        }


when I then try to do a $select, as such:

GET: https://graph.microsoft.com/beta/teams/<team_id_here>/members?$select=email

I receive a 400 error:

{
  "error": {
    "code": "BadRequest",
    "message": "Parsing OData Select and Expand failed: Could not find a property named 'email' on type 'microsoft.graph.conversationMember'.",
    "innerError": {
      "date": "2020-07-22T16:12:18",
      "request-id": "21eeaf99-1562-492d-957f-d1d5aa924468"
    }
  }
}

Note the odata type it is looking at:  conversationMember.  email is not part of conversationMember, it is part of aadUserConversationMember, which is the data type of the non $selected query.

Essentially, $select (and filter) are performing the search on a different data type than that which is returned by the unfiltered result.

**Comment by Trinetra-MSFT** [comment]
@middletoni , These query parameter doesn't work, [$select](https://docs.microsoft.com/en-us/graph/query-parameters#select-parameter) parameter works when you specify `from `and `subject `property to be returned
