### ISSUE TITLE
Error when calling listing Privileged Role Assignments

### ISSUE THREAD

**Issue by hausec** [microsoftgraph/microsoft-graph-docs#9141]
Getting an error when doing it manually and when using the 'try it' button/Graph Explorer.

```
 "message": "The current endpoints of AAD roles have been disabled for the tenant for migration purpose. Please use the new Azure AD RBAC roles. Please refer to https://aka.ms/PIMFeatureUpdateDoc for new PIM features; https://aka.ms/PIMAPIUpdateDoc for API and PowerShell changes because of migration.",

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 174921e7-8efc-2dce-9a97-64b3e34f1eee
* Version Independent ID: 419d2c69-123b-d36d-f6b1-e8bfca638792
* Content: [privilegedRoleAssignment: my - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/privilegedroleassignment-my?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/privilegedroleassignment-my.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/privilegedroleassignment-my.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by hausec** [comment]
Any update on this?

**Comment by shauliu** [comment]
Hello, we are in the process of launching new API to replace this one. But we also have one that's working in the interim. Mind letting me know what scenario you are trying to achieve and the timeline so I can help you?

**Comment by hausec** [comment]
Sure, so I'm making an API request via `Invoke-RestMethod` to just list the available privileged role assignments.

```
function Get-AzureGraphToken
{
    $APSUser = Get-AzContext *>&1 
    $resource = "https://graph.microsoft.com"
    $Token = [Microsoft.Azure.Commands.Common.Authentication.AzureSession]::Instance.AuthenticationFactory.Authenticate($APSUser.Account, $APSUser.Environment, $APSUser.Tenant.Id.ToString(), $null, [Microsoft.Azure.Commands.Common.Authentication.ShowDialog]::Never, $null, $resource).AccessToken
    $Headers = @{}
    $Headers.Add("Authorization","Bearer"+ " " + "$($token)")    
    $Headers
}

$Headers = Get-AzureGraphToken
$uri = 'https://graph.microsoft.com/beta/privilegedRoleAssignments'
Invoke-RestMethod -Headers $Headers -Uri $uri | convertto-json
```
And it returns the error:
```
Invoke-RestMethod : {
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "date": "2020-07-22T18:03:12",
      "request-id": "9bb22d94-175f-4177-9676-ab288464fb15"
    }
  }
}
```

**Comment by shauliu** [comment]
GET /privilegedAccess/aadRoles/roleAssignments?$filter=resourceId+eq+'{YOURTENANTID}'

You can try this one above

**Comment by hausec** [comment]
```
$uri = "https://graph.microsoft.com/beta/privilegedAccess/aadRoles/roleAssignments?$filter=resourceId+eq+'{ba8c4db2-xxxx-427a-xxxx-xxxxxxx}'"
Invoke-RestMethod -Headers $Headers -Uri $uri
```
This generates an error

```
Invoke-RestMethod : {
  "error": {
    "code": "UnknownError",
    "message": 
"{\"errorCode\":\"PermissionScopeNotGranted\",\"message\":\"Authorization 
failed due to missing permission scope Directory.AccessAsUser.All,Directory.Rea
d.All,Directory.ReadWrite.All,PrivilegedAccess.ReadWrite.AzureAD.\",\"target\":
null,\"details\":null,\"innerError\":null,\"instanceAnnotations\":[],\"typeAnno
tation\":null}",
    "innerError": {
      "date": "2020-09-08T14:29:06",
      "request-id": "51fd44ad-694c-429b-be7f-e57785a6a454"
    }
  }
}
```

I am logged in as Global Administrator.

**Comment by shauliu** [comment]
Hi, you need to setup an application with the right permission. Calling PIM API requires both an app token and and user token. You can grant application with one of these tokens when setting up the app.

https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/pim-apis#required-permissions

**Comment by hausec** [comment]
So there's no way to do this from a user context?

**Comment by shauliu** [comment]
I believe there's two option in graph today:
user + app
app only

We only support user + app but eventually want to support app only. In either case, app permission is required. If you are having issue with getting permission, I recommend you to try out our PowerShell commands: https://docs.microsoft.com/en-us/azure/active-directory/privileged-identity-management/powershell-for-azure-ad-roles

**Comment by hausec** [comment]
Is there a reason why a user wouldn't be able to do this without the need for an application (or use PowerShell as the application)? Why would a system administrator need to register an application to find out privileged roles in their environment?

**Comment by shauliu** [comment]
If you use PowerShell, you won't need to register an app. If you are just using graph API, always require an application.

**Comment by hausec** [comment]
Ah ok, thank you. I managed to get data back with the PowerShell cmdlets, but when using `-ProviderId AzureResources` and passing in a resource, I get back an object with a roledefinitionId property. That ID does not match any roles when comparing to the list gathered from `Get-AzRoleDefintion`. Where does this ID come from and how can I map it to a role name?

**Comment by shauliu** [comment]
Hey do you mind telling me which command you are using in PIM?

https://docs.microsoft.com/en-us/powershell/module/azuread/?view=azureadps-2.0-preview#privileged-role-management

You can refer to doc in this link. For Azure Resource, you will need:
(1) Register/onboard the resource onto PIM
(2) Query the resource to get the resource ID
(3) Use the resource ID to query roleDefinitionList

role definition should have role name and role ID (ID may be different to ID in AzRoleDefinition)

**Comment by hausec** [comment]
I'm gathering all PIM assignments for Azure Resources using the following command: 
`Get-AzureADMSPrivilegedRoleAssignment -ProviderId AzureResources -ResourceId $Resource.Id`

Where $Resource is a collection from `Get-AzureADMSPrivilegedResource -ProviderId AzureResources`

It's returning a object with a property called 'RoleDefinitionId'. The IDs in this field do not match to role IDs gathered by `Get-AzRoleDefinition`.

**Comment by shauliu** [comment]
You need to also Get the role definition and map the roleDefinitionID to get the name

https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureadmsprivilegedroledefinition?view=azureadps-2.0-preview

**Comment by hausec** [comment]
That did it, thank you!
