### ISSUE TITLE
For Guest users, getting 403 Forbidden "User Login. Teams is disabled for your tenant."

### ISSUE THREAD

**Issue by vman** [microsoftgraph/microsoft-graph-docs#9181]
Guest user with an M365 account is invited to the Team and they are able to see all channels in the Teams UI when they login.

However, when calling this API as the same guest user, we get a 403 Forbidden "User Login. Teams is disabled for your tenant."

```
{
  "error": {
    "code": "Forbidden",
    "message": "User Login. Teams is disabled for your tenant.",
    "innerError": {
      "date": "2020-07-20T11:41:27",
      "request-id": "aa7492c8-1ade-4a70-a310-4893e0e12d96"
    }
  }
}
```

I have confirmed that Teams is enabled in the guest users home tenant. 

Is this expected behaviour or should the endpoint work for Guest users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc7bd1a-6210-6010-c9ff-4245c342b20a
* Version Independent ID: e667c977-60ef-a81d-e94b-7eed5061b2c7
* Content: [List channels - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-list.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Trinetra-MSFT** [comment]
@vman Could you please check your token have `Group.ReadWrite.All` permission listed in roles? you can check it at [jwt.io](https://jwt.io). it should be granted by tenant admin.

**Comment by vman** [comment]
Hi @Trinetra-MSFT, yes I have `Group.ReadWrite.All` in the `scopes` property of the jwt. As I am using delegated authentication and requesting a user token, I get the permissions back in the scopes property instead of the roles property: 

![image](https://user-images.githubusercontent.com/173794/88033495-5a7cf580-cb37-11ea-9d25-a18c8bb9761f.png)

**Comment by Trinetra-MSFT** [comment]
@vman For guest users the permissions should be granted at admin level,  you can also check if your guest users have office 365 license assigned any of E3-E5.

**Comment by vman** [comment]
@Trinetra-MSFT are you sure the guest needs at least an E3 license? Are there any docs mentioning this requirement that I might have missed?

**Comment by Trinetra-MSFT** [comment]
@vman If you already have Office 365 Enterprise subscriptions. No additional Microsoft 365 or Office 365 license is necessary because Guest Access is included in it. but it depends on how many Guest users your are inviting there is [restriction](https://docs.microsoft.com/en-us/microsoftteams/guest-access#licensing-for-guest-access) on it. in the Meantime could you please try to grant the `Group.ReadWrite.All` Application permission at admin level, you will see that permission listed in Roles, not in scope. Let me know how it goes

**Comment by vman** [comment]
Hi @Trinetra-MSFT, I am checking with an E3 license assigned in the guest users home tenant right now. Will keep you posted.

Regarding the `Group.ReadWrite.All` Application permission, wouldn't that only work if I was getting an access token for a service principal? 
My scenario is that we need to request a Delegated token on behalf of the logged in guest user. So only permissions coming back in the token are the ones defined as Delegated ones in the Azure AD app.

**Comment by vman** [comment]
@Trinetra-MSFT explicitly assigning an E3 license in the guest users home tenant also did not help. Any thoughts on the Application vs Delegated permissions scenario I mentioned above?

I have assigned the `Group.ReadWrite.All` permission in both the application and delegated scope and granted admin consent as you mentioned:
![image](https://user-images.githubusercontent.com/173794/88280801-68b94600-ccde-11ea-84e8-a0551b9b8ab2.png)

But since I am requesting a token on behalf of the guest user, only the Delegated permission is coming back in the token (which is correct IMO). 

But still getting the "Teams is disabled for your tenant" error

```
{
  "error": {
    "code": "Forbidden",
    "message": "User Login. Teams is disabled for your tenant.",
    "innerError": {
      "date": "2020-07-23T11:21:04",
      "request-id": "602b0c3b-14c9-48b2-8dc3-668dd348ac3e"
    }
  }
}
```

**Comment by Trinetra-MSFT** [comment]
@vman , Let me check this with our Engineering Team, I will get back to you in sometime

**Comment by vman** [comment]
Hi @Trinetra-MSFT any update from the engineering team around this? Thanks!

**Comment by Trinetra-MSFT** [comment]
@vman , I had a discussion with Team after digging into it we found the issue with the wrong code path that Team was using rather than having the license check code path. We have an We have a work item for this that will be tackle down after start of Q3. Thanks for raising this
