### ISSUE TITLE
Windows Hello for Business "Not Yet Documented"

### ISSUE THREAD

**Issue by brasky** [microsoftgraph/microsoft-graph-docs#9188]
It seems like every graph API field for Windows Hello for Business has a description that says "Not yet documented." 

That makes it sound like it will be documented in the future, is this planned? Although most fields are relatively clear, it's confusing for customers and doesn't provide a timeline for when they will be documented. 

For instance: 
https://docs.microsoft.com/en-us/graph/api/resources/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration?view=graph-rest-1.0

https://docs.microsoft.com/en-us/graph/api/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration-create?view=graph-rest-1.0

https://docs.microsoft.com/en-us/graph/api/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration-update?view=graph-rest-1.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ddf30bf-ae8a-0317-f391-1f85baf70e29
* Version Independent ID: 2afc5a27-e8f8-880a-59ac-9ea30ac72862
* Content: [Update deviceEnrollmentWindowsHelloForBusinessConfiguration - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration-update?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/intune-onboarding-deviceenrollmentwindowshelloforbusinessconfiguration-update.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Thanks for this.  Generally we set the property value to "Not yet documented" at the time we first design the API - so I've added a task for our team to review and update these properties.
