### ISSUE TITLE
Unknown Error: Get Conversations

### ISSUE THREAD

**Issue by tathagatbanerjee** [microsoftgraph/microsoft-graph-docs#920]
Hi,

I'm trying to get the conversations within a group, as per [this](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/group_list_conversations) page. 

(1) The token I am using has the below permissions, which includes Group.Read.All and Group.ReadWrite.All

![image](https://cloud.githubusercontent.com/assets/11780602/23442759/af137378-fe7e-11e6-82b1-89e47315926c.png)

(2) The group definitely exists and I can get a list of groups.

(3) Using the below code causes a unknown error? Code:
```
case ('getGroupConversations'): {
  const method = 'GET';
  const url = 'https://graph.microsoft.com/v1.0/'
    + 'groups/'
    + msGraphInformation.groupId
    + '/conversations';

  const headers = {
    'Authorization': `Bearer ${msGraphInformation.token}`,
  };

  return await HTTP.call(method, url, { headers });
}
```
Error:
```
Exception while invoking method 'msGraph.outlook' Error: failed [429] {
I20170301-12:54:19.671(11)?    "error": {
I20170301-12:54:19.671(11)?      "code": "UnknownError",
I20170301-12:54:19.673(11)?      "message": "",
I20170301-12:54:19.673(11)?      "innerError": {
I20170301-12:54:19.674(11)?        "request-id": "d5639e39-a22a-4021-bada-b992194a2ba3",
I20170301-12:54:19.674(11)?        "date": "2017-03-01T01:54:17"
I20170301-12:54:19.674(11)?      }
I20170301-12:54:19.675(11)?    }
I20170301-12:54:19.675(11)?  }
```

If someone could have a look at this and provide some feedback, it would be most brilliant. Thanks so much.

Tat

**Comment by tathagatbanerjee** [comment]
I just restarted the app and tried it again, the error message has now changed. Please note I am trying to access this group with a server side node webapp, and so should not have any user permissions?
```
I20170301-13:19:09.437(11)? Exception while invoking method 'msGraph.outlook' Error: failed [403] {
I20170301-13:19:09.475(11)?    "error": {
I20170301-13:19:09.476(11)?      "code": "ErrorAccessDenied",
I20170301-13:19:09.476(11)?      "message": "This EWS API requires being called with a user context. The user context is missing.",
I20170301-13:19:09.476(11)?      "innerError": {
I20170301-13:19:09.476(11)?        "request-id": "a2c83ebc-f73a-4fa4-8848-340980709b79",
I20170301-13:19:09.477(11)?        "date": "2017-03-01T02:19:06"
I20170301-13:19:09.477(11)?      }
I20170301-13:19:09.477(11)?    }
I20170301-13:19:09.477(11)?  }
```

**Comment by tathagatbanerjee** [comment]
Hi,

After much messing around, I found this in known limitations.
```
Examples of group features that support only delegated permissions:

- Group conversations, events, photo
- External senders, accepted or rejected senders, group subscription
- User favorites and unseen count

```

Is this the issue above? Given that I am using a node server app to perform actions in the group? <strong>Could you please let me know if this is in your near term road map or in the beta spec?</strong>

For the use case we want to address, using groups seems substantially preferable to shared mailboxes (which works fine, after I discovered that app only may not allow this capability).

Additionally, can you guys please add better error messages for this sort of scenario, where app-only access does not work but other access is fine. Unknown Error and EWS API does not say anything at all, apart from spending a lot of time playing with permissions fruitlessly.

You guys have some dope capability here, but jeez it has some rough edges. Thanks so much. 

Tat

**Comment by isvargasmsft** [comment]
Hello, 

My deepest apologies for the delays in this issue. 

I tried from my end and it looks like the issue was fixed already. My apologies again for the delays. 

We are working hard to properly document error messages, please bear with us while we make progress on this matter. 

Closing issue as answer was provided. Please ask any future questions about Microsoft Graph at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).
