### ISSUE TITLE
Incorrect permissions specified

### ISSUE THREAD

**Issue by a-hackw** [microsoftgraph/microsoft-graph-docs#9202]
The documentation for "List memberOf" specifies that an application requires Directory.ReadWrite.All but that is actually not required.  Only Directory.Read.All is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9188ffdb-b7af-597d-9e0a-d92e75ff8e7d
* Version Independent ID: c4427823-3f37-dc4b-ac1e-b750cb633e23
* Content: [List memberOf - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-memberof.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by svrooij** [comment]
@a-hackw it actually says which permissions you need to access this endpoint. Starting with the **least privileged**.

If you already have `Directory.ReadWrite.All` in your token but not `Directory.Read.All` there is no need to request a new token with this last scope. I guess it is checked by something like the following pseudo code.

```csharp
if (identity.HasClaim("scope", "Directory.Read.All") || identity.HasClaim("scope", "Directory.ReadWrite.All")) {
  return something;
} else {
  return error_401;
}
```

**Comment by davidmu1** [comment]
As was stated by @svrroij, the permissions are listed from least privileged to most privileged. The table does not specify that all the permissions are required. The intent is that you choose the permission that is best for your app assuming the least permissions required. Closing this issue.
