### ISSUE TITLE
I am seeing a risk event type generic not seen in the documentation.

### ISSUE THREAD

**Issue by dkotars** [microsoftgraph/microsoft-graph-docs#9208]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ce56fe4-b5f4-cdde-1f35-39091aaa6303
* Version Independent ID: b07140db-8b54-e375-bbb8-1506aa0e616f
* Content: [riskDetection resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/riskdetection?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/riskdetection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/riskdetection.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @cloudhandler
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by cloudhandler** [comment]
@dkotars - do you have a screenshot?

**Comment by dkotars** [comment]
![image](https://user-images.githubusercontent.com/42387167/88175825-67135380-cbf4-11ea-872a-4c2c7e39f149.png)

**Comment by dkotars** [comment]
![image](https://user-images.githubusercontent.com/42387167/88176020-ac378580-cbf4-11ea-818c-1b022822a51e.png)

**Comment by dkotars** [comment]
![image](https://user-images.githubusercontent.com/42387167/88176090-c5403680-cbf4-11ea-9192-642974accfb4.png)

**Comment by dkotars** [comment]
![image](https://user-images.githubusercontent.com/42387167/88176195-e6a12280-cbf4-11ea-97e3-fbb0b910f006.png)

**Comment by cloudhandler** [comment]
Thanks, "generic" is used to represent "additional risk detected" in our API- meaning that a risk event was detected, but the details (like the name of the event type) are only available for customers with a P2 license.

**Comment by cloudhandler** [comment]
Updating docs and closing issue
