### ISSUE TITLE
Filter query param based on id/name does not work for user/groups

### ISSUE THREAD

**Issue by hkadakia** [microsoftgraph/microsoft-graph-docs#9222]
I am trying to retrieve a particular file belonging to a group/user. I added the filter clause with id field, but it seems to be returning all drive entries for the group/user and not filtering based on the id.

Tried with both Beta and v1.0 and same result.
```
 https://graph.microsoft.com/v1.0/groups/{group-id}/drive/root/delta/?$filter=id eq '01LSLVSYN6Y2GOVW7725BZO354PWSELRRZ'&$select=id

{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Collection(driveItem)",
    "@odata.deltaLink": "https://graph.microsoft.com/v1.0/groups/...",
    "value": [
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "id": "01LSLVSYN6Y2GOVW7725BZO354PWSELRRZ"
        },
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "@odata.etag": "\"{...},1\"",
            "id": "01LSLVSYLL27TECNSBARHZQP7O6JYNY3ER"
        },
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "@odata.etag": "\"{...},5\"",
            "id": "01LSLVSYKMRAB2KJPWDZHYDAOD23Q2IHIX"
        },
        {
            "@odata.type": "#microsoft.graph.driveItem",
            "@odata.etag": "\"{...},2\"",
            "id": "01LSLVSYI47IMKJMAJDJF24JAUXPHJFK6Y"
        },
    ]
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fefc984-0dac-5531-6620-13f577ebee5f
* Version Independent ID: 92438f30-1bb9-9b45-57dc-094fdcdeecc1
* Content: [Use query parameters to customize responses - Microsoft Graph](https://docs.microsoft.com/en-us/graph/query-parameters#filter-parameter)
* Content Source: [concepts/query-parameters.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/query-parameters.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @mumbi-o
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JeremyKelley** [comment]
Can you expand on your scenario for using this method?  Are you looking to find whether the item changed or just return the item's metadata?

Separately we will look into whether Filter is expected to work in this case.

**Comment by hkadakia** [comment]
Hi Jeremy,
Thanks for your reply.
We currently receive resource data information as part of Teams Webhook notification callback. Currently as part of the response, the API returns etag id and file name but no file metadata. We can download the file content using the etag id but we cannot get the file metadata using the etag id. So, in order to get the file metadata, I can think of 2 ways (search or filter based on the file name). Search doesn't seem to be working consistently (https://github.com/microsoftgraph/microsoft-graph-docs/issues/9223). If we could use the file name and filter that particular file belonging to the user/group, we could get the file metadata. We would like to save the file metadata since, we might move the file or delete the file based on some other conditions.

APIs using to download content:

 https://graph.microsoft.com/beta/groups/<group-id>/drive/items/<etag-id>/content
