### ISSUE TITLE
Change AddAsync to CreateAsync

### ISSUE THREAD

**Issue by mhomol** [microsoftgraph/microsoft-graph-docs#9224]
Currently, the C# example refers to an AddAsync method, however in the actual SDK the method is CreateAsync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e385d91b-23bd-030f-f878-7350fe037008
* Version Independent ID: eee15c96-5f93-5336-b99d-d2b6686ba2ae
* Content: [Create schema - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/externalconnection-post-schema.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/externalconnection-post-schema.md)
* Product: **search**
* Technology: **microsoft-graph**
* GitHub Login: @snlraju-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by snlraju-msft** [comment]
Adding Darrel

**Comment by snlraju-msft** [comment]
@pixieofhugs could you look into this issue.

**Comment by MIchaelMainer** [comment]
The C# code sample emits the same HTTP method, URL, and body as the HTTP example:

```csharp
GraphServiceClient graphClient = new GraphServiceClient( authProvider );

var externalConnection = new ExternalConnection
{
	Id = "contosohr",
	Name = "Contoso HR",
	Description = "Connection to index Contoso HR system"
};

await graphClient.External.Connections
	.Request()
	.AddAsync(externalConnection);
```


Emits the following:

```http
POST https://graph.microsoft.com/beta/external/connections
Content-type: application/json

{
  "id": "contosohr",
  "name": "Contoso HR",
  "description": "Connection to index Contoso HR system"
}
```

I could not repro with LinqPAD running the sample and Fiddler capturing the HTTP.
