### ISSUE TITLE
Invalid example for send mail with attachment 

### ISSUE THREAD

**Issue by LeonsBuntis** [microsoftgraph/microsoft-graph-docs#9233]
Sending email with attachment using C# as in docs example nr. 3 https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp#request-3
Casting to attachments to `(IMessageAttachmentsCollectionPage)` throws exception at runtime. 
Also mentioned here: https://github.com/microsoftgraph/microsoft-graph-docs/issues/8704#issue-637492882
Replace it with suggested code:

```
// Initialize the collection page
message.Attachments = new MessageAttachmentsCollectionPage();
// Add an attachment
// Use FileAttachment object since this is a file
message.Attachments.Add(new FileAttachment
{
    Name = file.FileName,
    ContentType = file.ContentType,
    ContentBytes = memoryStream.ToArray()
});
```

 _Originally posted by @jasonjoh in https://github.com/microsoftgraph/microsoft-graph-docs/issues/8704#issuecomment-643352653_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3b984b6-9100-69aa-f0f8-84bcdcea20dd
* Version Independent ID: 3f8b622d-becd-f287-98ac-18e408200523
* Content: [Send mail - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/user-sendmail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-sendmail.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by abheek-das** [comment]
Adding @andrueastman since this is related to the auto-generated SDK code from the example

**Comment by andrueastman** [comment]
This was resolved via https://github.com/microsoftgraph/microsoft-graph-docs/commit/4a13b5bb2b526a3e58cc034dd94adf7cca7acc49
