### ISSUE TITLE
Attachment id in decrypted data in webhook response is different than file-id

### ISSUE THREAD

**Issue by hkadakia** [microsoftgraph/microsoft-graph-docs#9237]
We have webhooks for teams/allMessages and chats/allMessages and we successfully decrypt the response. A sample response looks like:
```
{
  "body": {
    "contentType": "text",
    "content": "<attachment id='43f0f087-0210-4439-83a3-a10ad181a9f4'></attachment>"
  },
  "attachments": [
    {
      "id": "43f0f087-0210-4439-83a3-a10ad181a9f4",
      "contentType": "reference",
      "contentUrl": "...",
      "content": null,
      "name": "99adb8db68a29fad97854d98642d1a79.doc.zip",
      "thumbnailUrl": null
    }
  ]
}
```
When querying using the attachment id it seems it cannot find the file information. Looks like the attachment id is the etag id. I am able to download the content using /groups/{group-id}/drive/items/{attachment-id}/content but I am not able to get any file metadata information using /groups/{group-id}/drive/items/{attachment-id} or /users/{user-id}/drive/items/{attachment-id}.

How can we get metadata information about a file using the above decrypted resource data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7bb652-e041-1ba5-9679-908a98e51a79
* Version Independent ID: 540d51d6-50d6-828c-2aa1-0bb02f30ee22
* Content: [Set up change notifications that include resource data (preview) - Microsoft Graph](https://docs.microsoft.com/en-us/graph/webhooks-with-resource-data)
* Content Source: [concepts/webhooks-with-resource-data.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/webhooks-with-resource-data.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @baywet
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
You can get the info based on filename. Additionally you can look at OneDrive\Sharepoint search APIs
https://docs.microsoft.com/en-us/graph/search-concept-files#:~:text=The%20Microsoft%20Search%20API%20uses%20a%20relevance%20model,Files%20tab%20that%20lists%20search%20results%20in%20SharePoint.

**Comment by hkadakia** [comment]
I tried using both search and filter but it is not consistent, especially search response.

Please check another issue I raised here related to search:

https://github.com/microsoftgraph/microsoft-graph-docs/issues/9223

**Comment by RamjotSingh** [comment]
Right set of folks will reply to that issue. Let's wait for their reply because that is the best path forward here.

**Comment by hkadakia** [comment]
Is there a plan to add file-id in the response data or is there a way to retrieve a file using etag-id. The etag id which is returned currently has not correlation nor are there any MS Graph APIs which support it. We would be making extra calls just to fetch file id even after having all resource-info.

**Comment by Nikitha-MSFT** [comment]
Currently teams does not allow to view meta data of the file. There is a feature request on this. Could you please go [here](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/18694213-metadata-customized-views-in-files-tab) and upvote it?

**Comment by hkadakia** [comment]
@Nikitha-MSFT Sorry if I misunderstood the above feature request, but what I need is metadata as part of encryptedContent when a webhook notification is sent. From the request description it seems the original request is related to adding metadata as part of the Files Tab in the Teams app itself and not related to content being sent as part of webhook. Please correct me if I am wrong.

**Comment by Nikitha-MSFT** [comment]
Currently Teams does not support to get meta data as a part of encryptedContent when a webhook notification is sent. Could you please raise a [uservoice](https://microsoftteams.uservoice.com)?
