### ISSUE TITLE
Retrieving immutableentryId for old mail items not possible?

### ISSUE THREAD

**Issue by PugMcThug** [microsoftgraph/microsoft-graph-docs#9250]
When I use translateExchangeIds to retrieve an immutableEntryId from a mail that was originally sent using an Outlook client, I always receive a "Notfound" error. If I set the targetIdType to "entryID" it works fine.

Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77dc8516-103a-7df2-2685-1ce9045941b5
* Version Independent ID: 90ebf4ab-1563-4a6d-d184-c91159352366
* Content: [Get immutable identifiers for Outlook resources - Microsoft Graph](https://docs.microsoft.com/en-us/graph/outlook-immutable-id)
* Content Source: [concepts/outlook-immutable-id.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/outlook-immutable-id.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by markfoden** [comment]
I get the same. Does anyone have an update on this? Thanks

**Comment by jasonjoh** [comment]
Sorry folks, the notification that this was assigned to me got lost in the mountain of GitHub emails. I'll have to check with the engineering team on this, it's not something I expected.

When you say "old mail items", and "originally sent by Outlook client", can you clarify?

- Does old mean years ago, months ago, etc.?
- Sent by Outlook client - was it sent through Exchange Online but using an Outlook client? Was it an older version of Outlook?
- Where are you getting the source ID to pass to translateExchangeIds? Is it the Graph `id` property?
- Finally, could you reproduce this in Graph Explorer, then post the body of your request along with the response headers?
