### ISSUE TITLE
There are multiple examples using $count but none of them work in Graph

### ISSUE THREAD

**Issue by GalmWing** [microsoftgraph/microsoft-graph-docs#9254]
When I try to do memberOf/$count I get Bad Request. I tried for me/memberOf and devices/{id}/memberOf
{
    "error": {
        "code": "Request_BadRequest",
        "message": "$count is not currently supported.",
        "innerError": {
            "date": "2020-07-24T18:49:19",
            "request-id": "ce51f287-7b50-4a67-81d7-f0e5d9dca306"
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e30da6e9-975e-15a0-2679-504ecdc1e6c4
* Version Independent ID: f37e1e2e-fb43-a525-a6db-5bd1cff3680c
* Content: [List group memberOf - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-list-memberof?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/group-list-memberof.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list-memberof.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by yyuank** [comment]
Please remember to add the key-value pair of consistencyLevel-eventual to the request header as instructed in the examples.
