### ISSUE TITLE
Property Descriptions Flipped

### ISSUE THREAD

**Issue by w00dbury** [microsoftgraph/microsoft-graph-docs#9274]
The property "end" is described as "The time of the day that work starts" and "start" is described as "The time of the day that work stops". Based on my testing "start" should say "The time of the day that work starts" and "end" should say "The time of the day that work stops".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919e96a0-48e8-c181-7262-5e7f945fa37f
* Version Independent ID: 5db3e679-728b-0982-50e7-6bcb27b5f8a9
* Content: [bookingWorkTimeSlot resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/bookingworktimeslot?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/bookingworktimeslot.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/bookingworktimeslot.md)
* Product: **bookings**
* Technology: **microsoft-graph**
* GitHub Login: @arvindmicrosoft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by isvargasmsft** [comment]
Hello @w00dbury, 

Thank you very much for bringing this into our attention. My deepest apologies for the delays in our response.

Creating PR to fix this issue.

**Comment by isvargasmsft** [comment]
Hello @w00dbury, 

This issue is now resolved. 

Please keep sharing feedback with us, we'll do our best to improve the response time for the future. 

Kind regards,

Isaac Vargas
