### ISSUE TITLE
User query: '$skip' is not supported by the service.

### ISSUE THREAD

**Issue by j3soon** [microsoftgraph/microsoft-graph-docs#9279]
When performing the query:

```
https://graph.microsoft.com/beta/users/?$top=1&$skip=1
```

results in the following error:

```
{
    "error": {
        "code": "Request_BadRequest",
        "message": "'$skip' is not supported by the service.",
        "innerError": {
            "date": "2020-07-27T23:31:18",
            "request-id": "3d83a73e-dc9c-4e7a-887b-9eed73950255"
        }
    }
}
```

---

#### Expected behavior

The return result should respect the `$skip` parameter as mentioned in [the documentation](https://docs.microsoft.com/en-us/graph/api/user-list-people?view=graph-rest-1.0&tabs=http#optional-query-parameters).

---

#### Minimum steps to reproduce

It can be reproduced easily by following the link below:
https://developer.microsoft.com/en-us/graph/graph-explorer?request=users%3F%24top%3D1%26%24skip%3D1&method=GET&version=beta&GraphUrl=https://graph.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f2936c0-5bfb-5bb9-3641-d5ff68c13982
* Version Independent ID: 28758a37-e96d-67e3-c48c-92f5064d477a
* Content: [List people - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list-people?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list-people.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list-people.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
$skip is **not** supported by the core /users API (and all directory APIs), but is supported by the people API (under users) - which is the topic you link to.  That's different from the example you are showing.

If you want to do paging, suggest that you look at this topic: https://docs.microsoft.com/en-us/graph/paging
