### ISSUE TITLE
instantiateTemplate returns with no object Ids

### ISSUE THREAD

**Issue by chrisappianti** [microsoftgraph/microsoft-graph-docs#9282]
When calling the instantiateTemplate method, the ApplicationServicePrincipal object returned does not have the id of the Application or ServicePrincipal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2bcec4-f3cb-29ad-1f74-4b2419d98bac
* Version Independent ID: 97634873-8d0d-1e6c-01a1-cf03082c611a
* Content: [applicationTemplate: instantiate - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/applicationtemplate-instantiate?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/applicationtemplate-instantiate.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/applicationtemplate-instantiate.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @luleonpla
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by lcleonp** [comment]
If you call the API directly you should see the objectID, if you're using the MS graph SDK, we do have a inconsistency. We're working on fixing that before going GA.

For now, you can get the object Ids using the additionalData properties in the response.

public async Task<Beta.ApplicationServicePrincipal> CreateApplicationTemplate(string id, string appDisplayName)
        {
            var result = await _graphBetaClient.ApplicationTemplates[id]
                .Instantiate(appDisplayName)
                .Request()
                .PostAsync();

            string spoId = result.ServicePrincipal.AdditionalData.First(x => x.Key == "objectId").Value.ToString();
            string appoId = result.Application.AdditionalData.First(x => x.Key == "objectId").Value.ToString();

            logger.Info("applicationTemplate created with spoId =" + spoId + "app object Id =" + appoId);
            //logger.Info("applicationTemplate created with spoId =" + result.ServicePrincipal.Id + "app object Id =" + result.Application.Id);
            return result;
        }

**Comment by luleonpla** [comment]
#please-close
