### ISSUE TITLE
User Mail field misleading?

### ISSUE THREAD

**Issue by garrettm** [microsoftgraph/microsoft-graph-docs#9296]
I'm using the Microsoft Graph API to access Outlook mailboxes and have a quick question about Github accounts.  It seems I can sign in just fine with a Github account.  But everywhere I look, email shows up as the value of the contact email on the Github account.  I have visited outlook.com with this account and it got an autogenerated mailbox, so it has its own outlook mail address.  But I can't figure out how to retrieve that using the API.  

From the Graph Explorer: https://developer.microsoft.com/en-us/graph/graph-explorer
`my profile (beta)` shows my Github contact email under `emails`.
`my mail` shows with odata.context as `https://graph.microsoft.com/v1.0/$metadata#users(<GITHUB_ADDRESS>)/messages`, I do see the right email address under `toRecipients`, though

In general, how can I tell what a user's Outlook mailbox account is, given they signed in.  Or, alternatively, is there a way to disable login via Github for my app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3162dd2-cc3e-64f1-757b-ab752a6320ac
* Version Independent ID: d6551c10-ae06-eb82-c905-88ec2beb760a
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
This question is specific to GitHub account behavior not users API. No doc updates needed. Closing this issue.

**Comment by garrettm** [comment]
@krbain I'm asking about the users API in regard to a specific type of account, where should I put that?
