### ISSUE TITLE
Post ID is not returned when creating a new conversation

### ISSUE THREAD

**Issue by scordonnier** [microsoftgraph/microsoft-graph-docs#93]
If I create a conversation with the following JSON request...

```
{
  threads = ({
    posts = ({
      body = {
        content = "New Conversation Body",
        contentType = "html"
      }
    })
  }),
  topic = "New Conversation"
}
```

... then I receive the following response from the server:

```
{
  "@odata.id" = "groups/95735451-5c50-44fb-abce-dc731757ad99/conversations/AAQkADExMjg1OWZiLTM4Y2EtNDllNS04ZDYwLTBkOGY4YTFkODlhNwAQAJ0CoQSogq1DtxaG3dgLErs%3D",
  "@odata.type" = "#microsoft.graph.conversation",
  id = "AAQkADExMjg1OWZiLTM4Y2EtNDllNS04ZDYwLTBkOGY4YTFkODlhNwAQAJ0CoQSogq1DtxaG3dgLErs=",
  threads = ({
    "@odata.id" = "groups/95735451-5c50-44fb-abce-dc731757ad99/conversations/AAQkADExMjg1OWZiLTM4Y2EtNDllNS04ZDYwLTBkOGY4YTFkODlhNwAQAJ0CoQSogq1DtxaG3dgLErs%3D/threads/AAQkADExMjg1OWZiLTM4Y2EtNDllNS04ZDYwLTBkOGY4YTFkODlhNwMkABAAnQKhBKiCrUO3Fobd2AsSuxAAnQKhBKiCrUO3Fobd2AsSuw%3D%3D",
    "@odata.type" = "#microsoft.graph.conversationThread",
    id = "AAQkADExMjg1OWZiLTM4Y2EtNDllNS04ZDYwLTBkOGY4YTFkODlhNwMkABAAnQKhBKiCrUO3Fobd2AsSuxAAnQKhBKiCrUO3Fobd2AsSuw=="
  })
}
```

The response is not exactly the same as mentioned in the documentation (http://graph.microsoft.io/docs/api-reference/v1.0/api/group_post_conversations) but that's not my issue, even if it's good to be noted ;-)

Because the initial JSON message contains a conversation, a thread and a post, it should be logical to get the IDs for all these items, but only IDs for the conversation and the thread are returned by the server.

**Comment by angelgolfer-ms** [comment]
Hi @scordonnier , sorry for the long delay in responding. FYI I updated the topics for creating a new conversation in both the [v1](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_post_conversations) and [beta](https://developer.microsoft.com/en-us/graph/docs/api-reference/beta/api/group_post_conversations) versions by including some real REST examples. I also clarified that the response includes the new conversation and thread IDs, and one can use these IDs to [list the new post](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/conversationthread_list_posts) as well. You should be able to see these content updates within a day or less, and by the end of day 1/4/2018 PST.

As for your product-side request to have the create new conversation operation return the new post ID as well, FYI I added a [feature request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/32812381-post-group-conversation-should-return-new-post-id) in User Voice on your behalf. 

[User Voice](https://officespdev.uservoice.com/forums/224641-general/filters/new?category_id=101632) is a good venue for customers to enter and track their feature requests. If you haven't had a chance to try it, here's some more [information](https://officespdev.uservoice.com/) about User Voice. You can use the following handy link to add your future feature requests, that has the appropriate tagging for Microsoft Graph/O365 REST APIs:
https://officespdev.uservoice.com/forums/224641-general/filters/new?category_id=101632

Thank you for your continued support.
