### ISSUE TITLE
Typo in HTTP Request section

### ISSUE THREAD

**Issue by cadi3s** [microsoftgraph/microsoft-graph-docs#9315]
The API URI in the HTTP Request section says /teams/{id}/channels/{id}/primaryChannel
That should be /teams/{id}/primaryChannel as it does in the Sample Request section
(BTW great to see this addition to the API)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e20e34b-f7fe-a9b9-0040-c1c5be5470fc
* Version Independent ID: 6389d8fc-b3d9-4ea0-13b8-9a832d40499c
* Content: [Get primaryChannel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-get-primarychannel?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/team-get-primarychannel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-get-primarychannel.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by JarbasHorst** [comment]
Thanks @cadi3s for reporting this issue. I've authored a pull request, whenever it gets merged it'll close this issue!
