### ISSUE TITLE
Missing instructions for how to mention tag groups

### ISSUE THREAD

**Issue by middletoni** [microsoftgraph/microsoft-graph-docs#9320]
On this page, it says how to mention individuals.  Using other pages on the documentation, as well as the api explorer, you can also figure out how to mention teams and channels. There appears to be no documentation anywhere on how to mention tag groups within teams.  The functionality must exist at some level, as it can be done from within the Teams client itself, but even when duplicating the raw json returned from a Get Channel Messages call ( setting mention id, mention text, and setting the 4 identityset properties to null ), I am still unable to mention group tags successfully.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2597c208-2548-9bf3-3c0c-95a15975c53d
* Version Independent ID: cc1d5794-460d-903d-5f60-548f55101e21
* Content: [Create chatMessage in a channel - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-post-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-post-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-post-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @RamjotSingh
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by RamjotSingh** [comment]
Tag atmentions are not supported through Graph at the moment. We are working on bringing them to Graph, however no concrete  timeline to share yet.

**Comment by ashoksubedi1** [comment]
we need tag mention through Graph API thank you

**Comment by rlh1994** [comment]
@RamjotSingh Hey, is there any update on timelines for this or any Graph options for tags e.g. create/assign them?

**Comment by RamjotSingh** [comment]
The baseline work for having tags is nearing it's finish. AtMention will be picked post that.

**Comment by RamjotSingh** [comment]
Instructions updated.
