### ISSUE TITLE
Extending User Profile schema with custom properties

### ISSUE THREAD

**Issue by jimmywim** [microsoftgraph/microsoft-graph-docs#9347]
Is it/will it be possible to extend the Profile object with custom properties, like is currently possible in the SharePoint User Profile Service?

Or will this requirement be satisfied using open/schema extensions (noting that the documentation on extensions doesn't say that Profile is a supported entity - https://docs.microsoft.com/en-us/graph/extensibility-overview )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba12e15-4ac1-c0c2-ee37-23e84b6dba14
* Version Independent ID: 4a43deca-3890-cf08-2f59-c223a8c00fd3
* Content: [profile resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/profile?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/profile.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/profile.md)
* Product: **people**
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by extraordinaire01** [comment]
Hello @jimmywim, thanks for reaching out. Kindly have a look at this documentation under the open extensions section -> https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0.

**Comment by jimmywim** [comment]
Hi @PeterChenchaa - my understanding is that $filter isn't supported on open extensions, is this still the case?

The use-case:
We want to store custom information (such as Security Clearance Level, or a flag indicating whether they are a Part-Time or a Full-Time employee for example), and be able to locate users who are in specific groupings (such as return all with SCLevel 1, or search across all Part Time employees).

**Comment by PeterChencha** [comment]
Hi @jimmywim, filtering is possible on open extensions. This is documented here -> https://docs.microsoft.com/en-us/graph/api/opentypeextension-get?view=graph-rest-1.0&tabs=http. Kindly refer to the examples provided. If it's not what you are looking for feel free to reach out, am happy to help.

**Comment by jimmywim** [comment]
Hi @PeterChencha 

I've tried to use the patterns in that article to filter by an open extension value, and it has yielded a message which I can't find any page for.

Open extension created:

```
POST https://graph.microsoft.com/v1.0/users/[redacted UPN]/extensions

{
    "@odata.type": "microsoft.graph.openTypeExtension",
    "extensionName": "[redacted ID]",
    "securityClearance": "High"
}

Query attempt:
```
GET https://graph.microsoft.com/v1.0/users?$filter=Extensions/any(f:f/securityClearance eq 'High')&$expand=Extensions($filter=id eq '[redacted ID]')

Response:
{
    "error": {
        "code": "BadRequest",
        "message": "Open extension requests such as these require Entity Keys.",
        "innerError": {
            "date": "2021-03-01T11:32:52",
            "request-id": "2648bd66-09a8-4692-ba22-f4c29bc23668",
            "client-request-id": "820ce84d-bd29-eee9-7724-9248d872a063"
        }
    }
}
```

NOTE: I am intending on filtering on a specific *value* of a property - I want all users with a "high" `securityClearance`. The page you linked to only refers to including open extensions in the results of a query for users/events/messages, etc.

**Comment by yaw-innovate** [comment]
@jthake-msft Hi Jeremy, can you please point to a contact who can assist with the /v1.0/users endpoint?

**Comment by dkershaw10** [comment]
Hi @jimmywim.  On some resources, very limited filtering (i.e. find resources that have an extension with a specific id) is possible.  This is supported by the Outlook open extensions.  For Directory's open extensions, no filtering at all is currently supported.  It's not possible to offer filtering on the value of extension properties, since this open extension data is not schematized it would be difficult to index.  We might be able to search for strings within the extension data, but it's not possible today.
Schema extensions on the other hand can support filtering.

Unfortunately the Profile resource does not support any extensibility mechanism today AFAIK.
