### ISSUE TITLE
Patch OrgContacts able to be tested or roadmap available?

### ISSUE THREAD

**Issue by kevinblumenfeld** [microsoftgraph/microsoft-graph-docs#9360]
[Enter feedback here]
Really looking forward to this endpoint.  Are there any plans for it on the Roadmap?  I have not seen any information either way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75cfbb9-b36c-a3f4-0760-8a8a066c0f32
* Version Independent ID: 98478c05-3078-773e-92e2-4c698743d0d5
* Content: [Update orgcontact - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/orgcontact-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/orgcontact-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/orgcontact-update.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by dkershaw10** [comment]
This API is a read-only API.  While the topic you reference is still in the doc set, it's removed from table of contents and doc links, as it was added by mistake.  You won't see this topic in the v1.0 doc.  
At some point we *might* have the ability to create and update org contacts through Microsoft Graph, but not right now.
