### ISSUE TITLE
How could I get teamId using c# SDK

### ISSUE THREAD

**Issue by sjr2** [microsoftgraph/microsoft-graph-docs#9377]
var result = GraphClient.Client.Teams
                 .Request()
                 .AddAsync(team);

result is null after team created.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f249664-3b6d-e3f9-9017-1aa0121fe949
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Subhasish-msft** [comment]
@sjr2 , Can you please share the complete request payload and also the request id and timestamp in which teams got created successfully and it returned null.

If the team is created successfully, you could call [MyJoinedTeam API](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http) to get list of teams .

**Comment by sjr2** [comment]
I'm  issuing requests with application permissions.
team was created successfully but return value always null.
SDK version is 0.20.0-preview

           string[] owners = new string[1];
            owners[0] = "https://graph.microsoft.com/beta/users/xxxxxx";
            var team = new Microsoft.Graph.Team()
            {
                DisplayName = name,
                AdditionalData = new Dictionary<string, object>()
                {
                    {"template@odata.bind", $"https://graph.microsoft.com/beta/teamsTemplates('{template}')"},
                    {"owners@odata.bind", owners}
                }
            };

            return await GraphClient.Client.Teams
                 .Request()
                 .AddAsync(team);

**Comment by Subhasish-msft** [comment]
@sjr2 , Thanks for the response. I have created a bug for this. we will track it internally. 

As a workaround, you could call [MyJoinedTeam ](https://docs.microsoft.com/en-us/graph/api/user-list-joinedteams?view=graph-rest-1.0&tabs=http) API to get list of teams to get the newly created team Id.

**Comment by Nikitha-MSFT** [comment]
@sjr2 - Currently when you create team it will return only 200 okay response. This is by design.
