### ISSUE TITLE
Several properties are not documented

### ISSUE THREAD

**Issue by h-david-a** [microsoftgraph/microsoft-graph-docs#9398]
Following properties are not documented:
devices          
deviceStates,
userRiskLevels

>$ca.conditions|fl 
**userRiskLevels**   : {}
signInRiskLevels : {}
clientAppTypes   : {browser, mobileAppsAndDesktopClients}
platforms        : 
**deviceStates     :** 
**devices          :** 
applications     : {}
users            :  {}
locations        : {}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76bd679e-c5b2-e1cd-c402-7bb162a958ec
* Version Independent ID: 1d56190d-96db-a565-54d9-b752eadbbd89
* Content: [conditionalAccessConditionSet resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/conditionalaccessconditionset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/conditionalaccessconditionset.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @videor
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by videor** [comment]
@h-david-a we currently don't support device states and user risk in v1.0 GA release of MS Graph and thus they are not part of the data contract. https://docs.microsoft.com/en-us/graph/api/resources/conditionalaccessconditionset?view=graph-rest-1.0
