### ISSUE TITLE
These instructions don't make any sense

### ISSUE THREAD

**Issue by xtianus79** [microsoftgraph/microsoft-graph-docs#9409]
The request body must contain the following parameter: 'grant_type'

```
// Line breaks are for legibility only.

POST https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

client_id=535fb089-9ff3-47b6-9bfb-4f1264799865
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
&client_secret=qWgdYAmab0YSkuL1qKv5bPX
&grant_type=client_credentials
```

The endpoint is returning an error. 

Do people look at the instructions they post and actually think to themselves if they make sense and if they really would work if someone tried to use them? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service#4-get-an-access-token)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by jasonjoh** [comment]
Works fine for me. What error are you getting?

**Comment by xtianus79** [comment]
@jasonjoh can you give your example output. 

this is a part of the error output. it just gives that all of the time. 
The request body must contain the following parameter: 'grant_type'

**Comment by jasonjoh** [comment]
Ok, that's odd. The included request in the docs has `grant_type=client_credentials`. That error tells me either however you're sending it left it out, or you maybe didn't send it as `application/x-www-form-urlencoded`?

I used Postman, there's an included token request for app-only token in our [Graph Postman collection](https://github.com/microsoftgraph/microsoftgraph-postman-collections).


![image](https://user-images.githubusercontent.com/8966342/89661641-eebdbb00-d8a0-11ea-94d2-8a6f8de1a168.png)

**Comment by xtianus79** [comment]
@jasonjoh Where did you get the clientID and ClientSecret From. Just double checking that exactly.

**Comment by jasonjoh** [comment]
I registered an application in the Azure portal. This is mentioned in step 1.

**Comment by xtianus79** [comment]
@jasonjoh that was it. Thank you sir.
