### ISSUE TITLE
CallRecords.Read.PstnCalls permission not available

### ISSUE THREAD

**Issue by mohsinhere** [microsoftgraph/microsoft-graph-docs#9410]
Hi,

I was trying to test this out. But I couldn't find permission: "CallRecords.Read.PstnCalls" inside GraphAPI permissions.

Is that not rolled out?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 225370c6-9fb6-9a48-9275-12cff5d87d46
* Version Independent ID: c3fdaa61-1d7d-447d-7844-737902b786d8
* Content: [callRecord: getPstnCalls - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&viewFallbackFrom=graph-rest-1.0)
* Content Source: [api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/callrecords-callrecord-getpstncalls.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @stephenjust
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by mohsinhere** [comment]
@stephenjust any updates on this yet? 

Below is what I can see in API permissions under CallRecords. Thanks!

![image](https://user-images.githubusercontent.com/14170957/89844343-9f3bff80-dbbe-11ea-97de-7940913cc82a.png)

**Comment by stephenjust** [comment]
Apologies for the delay. Yes, I'm still waiting on the permission to roll out.

**Comment by mohsinhere** [comment]
Hi @stephenjust ,

Just wanted to check if this permission is not available to anyone at the moment? or is it just us?

Thanks!

**Comment by aakashbhardwaj619** [comment]
I'm also facing the same issue. `CallRecords.Read.PstnCalls` permission is not available.

**Comment by stephenjust** [comment]
#9859 should clarify this. We will still be adding an additional permission to only grant access to these direct routing and pstn calls functions, we expect the name to be CallRecord-PstnCalls.Read.All when it eventually gets provisioned.

**Comment by stephenjust** [comment]
Note that you can already access these apis using `CallRecords.Read.All`, but depending on your scenario this may be too much access (which is why we're adding a more granular permission)

**Comment by mohsinhere** [comment]
@stephenjust Thanks for the update. Yes, I can now query pstn call records using permission CallRecords.Read.All... i think before it was not allowing. 

Cheers!
