### ISSUE TITLE
21vianet Office 365 cannot get this 'Places' property

### ISSUE THREAD

**Issue by leapyear1969** [microsoftgraph/microsoft-graph-docs#9443]
when calling places API get below error:

GET: https://microsoftgraph.chinacloudapi.cn/v1.0/places/microsoft.graph.room 

{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'places'.",
    "innerError": {
      "date": "2020-08-11T01:50:18",
      "request-id": "6540cd56-0104-4426-b446-554a0dde6ff8"
    }
  }
}

refer [link:](https://docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-1.0)
Does 21vianet Office 365 support this API? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1521efeb-f96d-39e9-92f7-614881b350ec
* Version Independent ID: 44cfac3b-3d9f-0f26-5f50-e695da0fcea7
* Content: [place resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/place?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/place.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/place.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @vrod9429
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by vrod9429** [comment]
Hello, are you still having this issue?

**Comment by leapyear1969** [comment]
> Hello, are you still having this issue?

Yes, i still get this error, here is fiddler log:

**Request:**
GET https://microsoftgraph.chinacloudapi.cn/v1.0/places/microsoft.graph.room HTTP/1.1
Authorization: Bearer xxxx
Host: microsoftgraph.chinacloudapi.cn
Connection: Keep-Alive
X-P2P-PeerDist: Version=1.1
X-P2P-PeerDistEx: MinContentInformation=1.0, MaxContentInformation=2.0
Accept-Encoding: peerdist

**Response:**
HTTP/1.1 400 Bad Request
Cache-Control: private
Content-Type: application/json
request-id: de3fdc39-f0c9-4306-99b1-5f87bbedcd06
client-request-id: de3fdc39-f0c9-4306-99b1-5f87bbedcd06
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"China North","Slice":"SliceC","Ring":"5","ScaleUnit":"001","RoleInstance":"AGSFE_IN_0"}}
Strict-Transport-Security: max-age=31536000
Date: Thu, 17 Dec 2020 06:42:36 GMT
Content-Length: 308

{
  "error": {
    "code": "BadRequest",
    "message": "Resource not found for the segment 'places'.",
    "innerError": {
      "date": "2020-12-17T06:42:37",
      "request-id": "de3fdc39-f0c9-4306-99b1-5f87bbedcd06",
      "client-request-id": "de3fdc39-f0c9-4306-99b1-5f87bbedcd06"
    }
  }
}
