### ISSUE TITLE
List schemaExtensions returns only one Schema Extension

### ISSUE THREAD

**Issue by manvendrautralia** [microsoftgraph/microsoft-graph-docs#9494]
[Enter feedback here]
Hi,

While trying to add schema extensions, I get the error message, as below. This means I have exhausted my limit of 5 for this application.

_"message": "Limit of: 5 extension schema definitions can be written."_

But while listing all schema extensions for this application (query:- https://graph.microsoft.com/v1.0/schemaExtensions?$filter=owner%20eq%20'XXXXXXXX'), only one is returned. Looks like only one schema extension is registered for this application. 

Could you please help. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eaa53a2-e2a5-1c94-2b0a-7afc74330b8d
* Version Independent ID: 3c3d35d5-b9e0-9b72-781b-1862ed15e0d9
* Content: [List schemaExtensions - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/schemaextension-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/schemaextension-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/schemaextension-list.md)
* Product: **extensions**
* Technology: **microsoft-graph**
* GitHub Login: @dkershaw10
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by manvendrautralia** [comment]
Hi @dkershaw10 , Could you please help here.

Thanks,
Manvendra

**Comment by fabrazer** [comment]
Hi,

I have the same behavior in my app. I'm able to add more Schema Extensions via [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) but the same request with the same Access Token results in the error mentioned by @manvendrautralia.

Thank you in advance!

**Comment by davidmu1** [comment]
The issue has been communicated to engineering. No immediate change identified for the page. Closing the issue.
