### ISSUE TITLE
search-to-get-groups-with-display-names: wrong C# example, ".Search" does not exist at all in .NET, neither current nor beta version

### ISSUE THREAD

**Issue by spashx** [microsoftgraph/microsoft-graph-docs#9503]
[Enter feedback here]

Hi,

As an example to use $search in C# on groups, you give:

```
var groups = await graphClient.Groups
	.Request()
	.Header("ConsistencyLevel","eventual")
	**.Search("displayName:Video")**
	.GetAsync();
```

the ".Search()" keyword does not exist, neither in current sdk version, nor in the last beta at the time of writing (0.22).
Morevever, when using "$search" in query options, it always returns "query not supported " :

```
string term = "\"displayName:Video\"";           
var qo = new QueryOption("$search", term);
List<QueryOption> optionsAsList = new List<QueryOption> { qo };
var result = GraphServiceClient.Groups.Request(optionsAsList).GetAsync().Result;
```
throws: "Code: Request_UnsupportedQuery. Message: This query is not supported."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b65a8cbc-3916-b5ae-1f83-8ca0471d6d5b
* Version Independent ID: 1668bd18-63b3-6b21-d9c8-2706cb654e61
* Content: [List groups - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&tabs=csharp)
* Content Source: [api-reference/beta/api/group-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/group-list.md)
* Product: **groups**
* Technology: **microsoft-graph**
* GitHub Login: @yyuank
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by spashx** [comment]
doc url: https://docs.microsoft.com/en-us/graph/api/group-list?view=graph-rest-beta&tabs=csharp#example-5-use-search-to-get-groups-with-display-names-that-contain-the-letters-video-including-a-count-of-returned-objects

**Comment by spashx** [comment]
Working example:

            string term = "\"description:testDescription\"";
            var searchOption = new QueryOption("$search", term);
            var countOptions = new QueryOption("$count", "true");
            List<QueryOption> optionsAsList = new List<QueryOption> { searchOption, countOptions };

            var result = GraphServiceClient.Groups
                    .Request(optionsAsList)
                    .Header("ConsistencyLevel", "eventual").GetAsync().Result;

**Comment by Licantrop0** [comment]
You are correct @spashx. The SDK doesn't have $search support for directory objects yet, and you must add it manually using the QueryOptions. I am creating a sample for this: https://github.com/microsoftgraph/dotnet-aad-query-sample

@davidmu1 is updating the documentation.

**Comment by davidmu1** [comment]
Temporarily removed the SDK examples until $search is supported there.
