### ISSUE TITLE
Need code examples.

### ISSUE THREAD

**Issue by shwork96** [microsoftgraph/microsoft-graph-docs#9529]
This page needs code examples beyond the html.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc76cac-d03b-00da-14b0-f9bd10ad2d9e
* Version Independent ID: aca98506-742e-b7f2-5061-08fe94e9c15c
* Content: [Get a user - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-get.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
@shwork96 - There are tabs at the top of the examples that take you to the different examples for the SDKs. Closing this issue, but if you have a specific example that you think should be on the page that isn't there, please reopen the issue with specific information.
