### ISSUE TITLE
Cannot add member to private channel...

### ISSUE THREAD

**Issue by kepeter** [microsoftgraph/microsoft-graph-docs#9538]
Hi,

I'm using this code (C#) to add a member (not owner) to a private channel:
```
AadUserConversationMember oChannelMember = new AadUserConversationMember
{
  Roles = new List<String>() { },
  AdditionalData = new Dictionary<string, object>()
  {
    ["user@odata.bind"] = string.Format("https://graph.microsoft.com/beta/users('{0}')", oMember.Id)
  }
};

await _Client.Teams[TeamId].Channels[ChannelId].Members.Request().AddAsync(oChannelMember);
```
It passes without any error, but the member never shows on the channel...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497ad1e7-5a61-731f-e0e9-75b5cb9336c8
* Version Independent ID: 776a8387-3525-7289-51bd-1232f58d283a
* Content: [Add conversationMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Gousia-MSFT** [comment]
@kepeter How long has it been since you have added the member? Graph takes some time to sync with teams. Did you try this with Graph Explorer?

**Comment by kepeter** [comment]
@Gousia-MSFT 
Tried it with different waiting times - including 24 hours...

I will try Graph Explorer and update here...

**Comment by kepeter** [comment]
@Gousia-MSFT 
The results of Graph Explorer...
```
POST https://graph.microsoft.com/beta/teams/a7166afa-dc34-4684-ba5c-88e8dbc8e50a/channels/19:a8dc25650f744123a2259b418f20d945@thread.tacv2/members

{
    "@odata.type":"#microsoft.graph.aadUserConversationMember",
    "roles":[],
    "user@odata.bind":"https://graph.microsoft.com/beta/users/fe18e408-1be2-4e32-89f4-895330c28406"
}
```
Result
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#teams('a7166afa-dc34-4684-ba5c-88e8dbc8e50a')/channels('19%3Aa8dc25650f744123a2259b418f20d945%40thread.tacv2')/members/$entity",
    "@odata.type": "#microsoft.graph.aadUserConversationMember",
    "id": "MTk6YThkYzI1NjUwZjc0NDEyM2EyMjU5YjQxOGYyMGQ5NDVAdGhyZWFkLnRhY3YyIyNmZTE4ZTQwOC0xYmUyLTRlMzItODlmNC04OTUzMzBjMjg0MDY=",
    "roles": [],
    "displayName": "Student Two",
    "userId": "fe18e408-1be2-4e32-89f4-895330c28406",
    "email": null
}
```

Looking at the UI the user does not listed...
![image](https://user-images.githubusercontent.com/695660/90627534-c2048e80-e224-11ea-9ff1-4c4d614912a0.png)

But! Listing the members via Graph Explorer it says something different...
```
GET https://graph.microsoft.com/beta/teams/a7166afa-dc34-4684-ba5c-88e8dbc8e50a/channels/19:a8dc25650f744123a2259b418f20d945@thread.tacv2/members
```
Result
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#teams('a7166afa-dc34-4684-ba5c-88e8dbc8e50a')/channels('19%3Aa8dc25650f744123a2259b418f20d945%40thread.tacv2')/members",
    "@odata.count": 2,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MTk6YThkYzI1NjUwZjc0NDEyM2EyMjU5YjQxOGYyMGQ5NDVAdGhyZWFkLnRhY3YyIyNmZTE4ZTQwOC0xYmUyLTRlMzItODlmNC04OTUzMzBjMjg0MDY=",
            "roles": [],
            "displayName": "Student Two",
            "userId": "fe18e408-1be2-4e32-89f4-895330c28406",
            "email": null
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "MTk6YThkYzI1NjUwZjc0NDEyM2EyMjU5YjQxOGYyMGQ5NDVAdGhyZWFkLnRhY3YyIyM3ZGQ3YTFhYi1kOGRhLTQ2ZGMtYWU1ZS1jODUyMDc3ZWM0ZGE=",
            "roles": [
                "owner"
            ],
            "displayName": "peter",
            "userId": "7dd7a1ab-d8da-46dc-ae5e-c852077ec4da",
            "email": "peter@rashhim.onmicrosoft.com"
        }
    ]
}
```
It is obvious that the member is there, but I (peter the owner) can not see!!!

Any clue?

**Comment by Gousia-MSFT** [comment]
@kepeter Could you please try filling the roles array? Please add "owner" in the array instead of keeping it empty.

**Comment by kepeter** [comment]
It makes no difference...
```
GET https://graph.microsoft.com/beta/teams/a7166afa-dc34-4684-ba5c-88e8dbc8e50a/channels/19:d4365482ef8e4e41abdba179a9ffaad5/members
```
This query returns 4 members as follows
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#teams('a7166afa-dc34-4684-ba5c-88e8dbc8e50a')/channels('19%3Ad4365482ef8e4e41abdba179a9ffaad5')/members",
    "@odata.count": 4,
    "value": [
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "YTcxNjZhZmEtZGMzNC00Njg0LWJhNWMtODhlOGRiYzhlNTBhIyNmZTE4ZTQwOC0xYmUyLTRlMzItODlmNC04OTUzMzBjMjg0MDY=",
            "roles": [],
            "displayName": "Student Two",
            "userId": "fe18e408-1be2-4e32-89f4-895330c28406",
            "email": null
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "YTcxNjZhZmEtZGMzNC00Njg0LWJhNWMtODhlOGRiYzhlNTBhIyNiMTE0ZGY1ZS0zZjZiLTQ4NWUtOGFhMS1mMGE4YTZlZGU3OTY=",
            "roles": [
                "owner"
            ],
            "displayName": "Teacher One",
            "userId": "b114df5e-3f6b-485e-8aa1-f0a8a6ede796",
            "email": null
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "YTcxNjZhZmEtZGMzNC00Njg0LWJhNWMtODhlOGRiYzhlNTBhIyM0YmRiYWE2ZS1kZDA4LTRiYzktYmRhZS0yZGY5ZDhmNjkwNzM=",
            "roles": [],
            "displayName": "Student One",
            "userId": "4bdbaa6e-dd08-4bc9-bdae-2df9d8f69073",
            "email": null
        },
        {
            "@odata.type": "#microsoft.graph.aadUserConversationMember",
            "id": "YTcxNjZhZmEtZGMzNC00Njg0LWJhNWMtODhlOGRiYzhlNTBhIyM3ZGQ3YTFhYi1kOGRhLTQ2ZGMtYWU1ZS1jODUyMDc3ZWM0ZGE=",
            "roles": [
                "owner"
            ],
            "displayName": "peter",
            "userId": "7dd7a1ab-d8da-46dc-ae5e-c852077ec4da",
            "email": "peter@rashhim.onmicrosoft.com"
        }
    ]
}
```
However only the owner 'peter' shows on the UI... And this owner was added during the channel creation (as I must have a owner to create a private channel)...

![image](https://user-images.githubusercontent.com/695660/90732770-419d6680-e2d4-11ea-91c0-14ce5983aec2.png)

It seems that all the members (Student One, Student Two) or owners (Teacher One) that were added via this API not show on the UI... The owner 'peter' is there, but it was added from other API (https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta)...

**Comment by Gousia-MSFT** [comment]
@kepeter Could you please share the client-request-ID header being returned in the response?

**Comment by kepeter** [comment]
All the headers...

{
    "cache-control": "private",
    "client-request-id": "8fc2bafb-681b-250d-c201-8e72e57215a1",
    "content-length": "855",
    "content-type": "application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8",
    "request-id": "4bd6dbff-83a5-4057-8ec5-6d0bdd20ef06"
}

**Comment by Gousia-MSFT** [comment]
@kepeter We are checking this internally!

**Comment by Gousia-MSFT** [comment]
@kepeter Could you please try using `GET /beta/teams/id` and check the value of `isMembershipLimitedToOwners`? If that value is true, the client won't show any non-owners in the roster and the users won't have access.

**Comment by kepeter** [comment]
@Gousia-MSFT 
```
GET https://graph.microsoft.com/beta/teams/0919aabe-32e8-4563-b322-a79b4add136e
```

The results are:
```
"isMembershipLimitedToOwners": true,
```

You are right... Which actually brings us to - probably - the final question...
How I set it if Microsoft.Graph.Team object has no such property?

```

**Comment by Gousia-MSFT** [comment]
@kepeter Could you please try setting that property to false? You could use the [Update team ](https://docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&tabs=http)API to do so. Please check the [example ](https://docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&tabs=http#example)here.

**Comment by kepeter** [comment]
I can not, as - in contrast to the API - the Team class has no such property...
```
Error CS0117 'Team' does not contain a definition for 'IsMembershipLimitedToOwners'
```

**Comment by Gousia-MSFT** [comment]
@kepeter Could you please try this using beta? Please call the Update Team API setting `IsMembershipLimitedToOwners `to false.

**Comment by kepeter** [comment]
@Gousia-MSFT - as in the original issue, I use beta... Copied the C# sample and got the mentioned error...

**Comment by Gousia-MSFT** [comment]
@kepeter The Graph SDK doesn't support all beta properties. In particular, the isMembershipLimitedToOwners property is not available in the SDK, but is available if you make Graph API calls directly. Could you please try making a Graph API call from the Graph Explorer to update the team and set isMembershipLimitedToOwners  to false?

**Comment by kepeter** [comment]
@Gousia-MSFT Even assuming that it works (hi probability)... How that helps me and my application? I do have to use SDK!

**Comment by Gousia-MSFT** [comment]
@kepeter You could continue to use SDK to add members to channel. Suggesting you to use Graph Explorer to update Team to change a field that is causing the actual issue.

**Comment by kepeter** [comment]
@Gousia-MSFT I have here an application that should manage the CRUD functionality against Teams (it is actually a service that monitors DB changes and reflects them). Can't see how Graph Explorer can fit into this flow!?

**Comment by Gousia-MSFT** [comment]
@kepeter I understand that! The issue you are facing here is that you are not able to view the members added to a private channel. And we suspect that this is because of having the IsMembershipLimitedToOwners property set to true. We need to try setting it to false and see if that fixes the issue. Unfortunately this property is not available with the Graph SDK. So you could try getting the team id and channel id of the team/channel where you are trying to add member and use the Update API through Graph explorer to change this property. Once this is changed you can continue to use your C# code to add member.

**Comment by kepeter** [comment]
@Gousia-MSFT From my tests - if I break my work into 3 parts by setting the IsMembershipLimitedToOwners property in-between the 'create' and the 'add-member' part it works as expected... So it seems that the missing part is to expose this property in C# too...

**Comment by Gousia-MSFT** [comment]
Thanks @kepeter. We will raise a request to add this property in C# Graph SDK as well.

**Comment by kepeter** [comment]
Thank you very much @Gousia-MSFT !
Do I have any way to follow that request?

**Comment by Gousia-MSFT** [comment]
@kepeter Our team is working on adding this property in the latest beta SDK. Unfortunately, there is no way to track this at your end.
