### ISSUE TITLE
shoud list messages if app is in the creator/owner of team channel

### ISSUE THREAD

**Issue by brookqi** [microsoftgraph/microsoft-graph-docs#9540]
list channel messages is a useful function. However for application permissions, it only has 2 results, App has permissions to list messages of all channels if permission granted, or has no permission to list any channel messages. The first one has security risk and mostly not be accepted by customer. 
For background deamon service which uses application permissions, a common scenario is creating team/channel and then synchronize channel messages back. So it should be better to get channel messages without request permission if the channel is created by this App or the channel owner/member is the App account, just like the behavior of "on behalf of" Apps owner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b32ca7f9-ea75-d0fd-f887-136e0c9686e3
* Version Independent ID: 6e9b24bc-9869-0b70-8881-3c4aad2bebed
* Content: [Protected APIs in Microsoft Teams - Microsoft Graph](https://docs.microsoft.com/en-us/graph/teams-protected-apis)
* Content Source: [concepts/teams-protected-apis.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/teams-protected-apis.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Gousia-MSFT** [comment]
@brookqi Thanks for reaching out to us! Please go ahead and raise a uservoice for this. Could you also please try using [Resource specific consent](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent#resource-specific-permissions) that will allow the Team owner to grant consent rather than having the admin consent on behalf of the entire organisation.

**Comment by brookqi** [comment]
However I found Resource specific consent may not be suitable in my scenario, now I try [Resource Owner Password Credentials](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc) which could be used in background service too with delegated permission rather than application permission. It has less security risk.
