### ISSUE TITLE
unable to get my emails via graph API

### ISSUE THREAD

**Issue by rakeshkeerthi** [microsoftgraph/microsoft-graph-docs#957]
Hi Team, 

I'm using the graph api to fetch my emails. and I'm using a postman client, I'm getting the authorize token and sending it to the api as header.

When I run the below query.

https://graph.microsoft.com/v1.0/me 

the response that I get is

`{ "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity", "id": "someId", "businessPhones": [], "displayName": "MyName", "givenName": "MyFirstName", "jobTitle": "MyDesignation", "mail": "myEmailAddress", "mobilePhone": "MyMobileNumber", "officeLocation": "MyWorkLocation", "preferredLanguage": null, "surname": "MySurName", "userPrincipalName": "MyEmailAddress" } `

and when I try to run the below query.

https://graph.microsoft.com/v1.0/me/messages 

The response that I get is as below.

`{ "error": { "code": "ResourceNotFound", "message": "Resource could not be discovered.", "innerError": { "request-id": "59a0a25b-67c4-4fe8-8aff-eb035b974a4b", "date": "2017-03-10T14:09:13" } } } 
`
Also tried the below URL to get the emails.

https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/messages 

I get the same response as above.

Finally I tried

https://graph.microsoft.com/v1.0/me/mail 

Here the response that I got is

`{ "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('someRandomId')/mail", "value": "myEmailAddress" } `

please let me know how can I get my emails shown.

In the portal(https://apps.dev.microsoft.com), I've the below things enabled for this application.

[permissions screenshot](http://imgur.com/a/ZU271)

Thanks, 
Rakesh

**Comment by ronengreen** [comment]
@rakeshkeerthi hi , did u find any solution for that?!

**Comment by lsnider** [comment]
Can reproduce this too if anyone at microsoft wants help recreating the issue

**Comment by jthake-msft** [comment]
Closing due to lack of response. Also this issues lists is specifically for documentation issues, not the underlying service, sdks or samples. I will close this issue so our documentation team can focus on content issues.
The official channel for questions is StackOverflow with '[microsoft-graph](https://stackoverflow.com/questions/tagged/microsoft-graph
)' tag.
For issues, you can raise a support ticket on the Azure Portal where you registered your application. This [simple video](https://twitter.com/jthake/status/1030489336439959553) shows how to file it properly by visiting [here](https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).

**Comment by lsnider** [comment]
> Closing due to lack of response.

What response do you need?  I can reproduce this issue on a number of mailboxes.  I don't understand this comment.  The bug was reported and we have someone offering to provide current examples of the issue.

**Comment by jthake-msft** [comment]
As my message above states, this is not the correct place to file an issue on the service. This repo is specifically for docs.

The best way to escalate this is via the Azure Portal here https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview

That will go through to the correct team who can help with the issue.

**Comment by lsnider** [comment]
Ok, that makes sense.  I tried following your video on how to submit tickets through the azure portal.  Looks like I need to purchase a support plan to file bugs there?  Is there a way to file bugs w/o paying to do so?

**Comment by jthake-msft** [comment]
As you don't have paid support. If you post this on StackOverflow using Microsoft-graph tag https://stackoverflow.com/questions/tagged/microsoft-graph and post the link here i'll make sure it gets looked at.

**Comment by lsnider** [comment]
Sweet!  Thanks!
