### ISSUE TITLE
Can we use this for Azure AD B2C as well?

### ISSUE THREAD

**Issue by angie4u** [microsoftgraph/microsoft-graph-docs#9579]
Hi team,

I followed this tutorial to update profile photo for AAD B2C user account, but it didn't work with following error.
![image](https://user-images.githubusercontent.com/16282358/90645395-d8d0d280-e270-11ea-9092-a8e70f0cbcd1.png)
Can we use this rest API call to AAD B2C as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe020479-a6f3-1dbf-2b2b-3dbd50e74d92
* Version Independent ID: 6da3efa4-e243-1d29-65a2-8ce172dc9cf3
* Content: [Update profilephoto - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/profilephoto-update.md)
* Product: ****
* Technology: **microsoft-graph**
* GitHub Login: @kevinbellinger
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by extraordinaire01** [comment]
Hello @angie4u, could you kindly confirm if your app has the right permission scope that is, User.ReadWrite.All and you are calling the API under the identity of the user. Kindly refer to this documentation for more info -> https://docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-1.0&tabs=http

**Comment by PeterChencha** [comment]
Hello @angie4u this issue appears fixed. Kindly feel free to open another issue if this problem is still recurring for you.
