### ISSUE TITLE
Is delta working for directoryObjects

### ISSUE THREAD

**Issue by nmoATusercube** [microsoftgraph/microsoft-graph-docs#9590]
The documentation contains plenty of examples for https://graph.microsoft.com/beta/directoryObjects/delta but none of them are working in the Graph Explorer.
Is directoryObjects/delta abandoned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee466947-0540-96d4-3c56-22dee7186db4
* Version Independent ID: f17f647a-22da-1433-1df1-0f18685878cf
* Content: [Use delta query to track changes in Microsoft Graph data - Microsoft Graph](https://docs.microsoft.com/en-us/graph/delta-query-overview)
* Content Source: [concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/delta-query-overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @davidmu1
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
Delta on directoryobjects isn't currently supported. The documentation was published by mistake and will be taken down. Closing the issue.
