### ISSUE TITLE
licenseAssignmentStates property of user resource type does not return all assigned licenses

### ISSUE THREAD

**Issue by mkomko** [microsoftgraph/microsoft-graph-docs#9636]
The _licenseAssignmentStates_ property of the _user_ resource type does not return **all** assigned licenses. It is probably a bug in Graph API, but who knows. Please see: https://stackoverflow.com/questions/63518563/

Can you please adjust the documentation or have the bug fixed ASAP, if you can report or influence that in any way? Thank you very much in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71215894-d1c8-8d36-9dbb-adb35cfbc5f9
* Version Independent ID: 34e2e6e4-578a-9309-ebcf-94b640dc4e4c
* Content: [user resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @mkomko for highlighting this issue. We have logged it a bug and its in the Engineering queue for resolution.
