### ISSUE TITLE
Nested query of MS Graph

### ISSUE THREAD

**Issue by SruthiJeelugula** [microsoftgraph/microsoft-graph-docs#9646]
[The manager is inside properties of the user object and employeeid is inside property of manager and we are using this below query .can you please let us know is it considered as a nested query of ms graph
for example:
https://graph.microsoft.com/beta/users?$expand=manager($select=employeeId)

Note: This above query is not working]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabdb652-eb03-bae6-fa99-66d71fbdd044
* Version Independent ID: 7f5744b6-6770-586e-217c-4b7ac7657051
* Content: [List users - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by krbain** [comment]
Issue seems to be in the graph SDK for expand and select/filter. See [microsoftgraph/msgraph-sdk-javascript#291](url) which tracks it. Closing this issue as there's no specific doc update for users.
