### ISSUE TITLE
Incorrect content in Diagram

### ISSUE THREAD

**Issue by PrasadKasireddy** [microsoftgraph/microsoft-graph-docs#9668]
In Powering the Microsoft 365 Platform diagram, it should be Office 365(not Microsoft 365) as highlighted in diagram 

![image](https://user-images.githubusercontent.com/11626905/91296239-ec70c180-e7b9-11ea-8add-9dfe1d11e503.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8a7f020-9903-7af9-7102-3bf26ff89c3a
* Version Independent ID: 11dc19b6-ee12-b814-c871-f0df80adc8d3
* Content: [Overview of Microsoft Graph - Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview)
* Content Source: [concepts/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/overview.md)
* Product: **non-product-specific**
* Technology: **microsoft-graph**
* GitHub Login: @angelgolfer-ms
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by angelgolfer-ms** [comment]
Hi @PrasadKasireddy , thank you for viewing our docs!
Microsoft rebranded Office 365 as Microsoft 365 earlier this year. Please take a look:
https://www.microsoft.com/en-us/microsoft-365/business/compare-all-microsoft-365-business-products-b

Thanks for your continued support!

**Comment by PrasadKasireddy** [comment]
@angelgolfer-ms  - Thanks for your response, 
I know that it' not just a re-banded Office 365 and also extended the functionality that includes Windows 10 +  and Enterprise Mobility + Security.

as per the Microsoft standard that Microsoft 365 brings together **Office 365, Windows 10, and Enterprise Mobility + Security**, In the diagram it should be **Office 365, Windows 10, and Enterprise Mobility + Security**  or Only Microsoft 365.
as Microsoft 365 = Office 365 + Windows 10+ Enterprise Mobility + Security

![image](https://user-images.githubusercontent.com/11626905/91426353-0a056000-e87a-11ea-97b1-08f95a37cca5.png)

https://www.microsoft.com/en-us/microsoft-365/enterprise-mobility-security/compare-plans-and-pricing

I saw the correct diagram in Microsoft Build 2020 - Microsoft Graph Live - Jun 04, 2020 at 11:40PM by Darrel Miller

![image](https://user-images.githubusercontent.com/11626905/91427226-32da2500-e87b-11ea-9b83-38d94d6588a3.png)

**Comment by angelgolfer-ms** [comment]
@PrasadKasireddy , thank you for relaying your understanding.
I can confirm that "Office 365" as a product or service name has been replaced by "Microsoft 365".
"Microsoft 365" can be used as a _general_ term to represent the Microsoft cloud offerings.

When used in the context of the exact services Microsoft 365 contains, "Microsoft 365" is qualified by the customer purpose: home, business, enterprise, and education, as described in the Microsoft 365 home page: https://www.microsoft.com/en-us/microsoft-365
_At the sales level_, Microsoft 365 for home forms the fundamental package, and is referred to as Microsoft 365.

If you click the **Home** tab on this [page](https://www.microsoft.com/en-us/microsoft-365/buy/compare-all-microsoft-365-products), that page says:
"**Office 365 is now Microsoft 365. New name, more benefits, same price.**" 
Microsoft 365 for home is the basic package that consists of a few major apps in what used to be called Office 365.

If you click the **Business** tab on that [page](https://www.microsoft.com/en-us/microsoft-365/buy/compare-all-microsoft-365-products), you can see the description:
"**Reimagine productivity with Teams & Microsoft 365**"
Microsoft 365 for business is the apps in Microsoft 365 (for home), plus Teams and a few apps such as Bookings, that were all part of Office 365, plus a few security, compliance, support, deployment services, depending on the selected license.

If you select **For enterprise** or **For education** on the [home page for Microsoft 365](https://www.microsoft.com/en-us/microsoft-365), you'd notice that each of these editions builds on top of a set of apps that used to be part of Office 365, plus again, a number of other apps and services including security, compliance, etc., depending on the selected license.

In particular, on the [page](https://www.microsoft.com/en-us/microsoft-365/enterprise-mobility-security/compare-plans-and-pricing) for Microsoft 365 Enterprise that you included, you can please interpret those 4 lines you highlighted to mean, the edition Microsoft 365 Enterprise brings together what used to be referred to as Office 365, plus Windows 10 and Enterprise Mobility + Security.

And to clarify, the diagram that you shared above, that Darrel used for Build 2020, is out-of-date. Build 2020 coincided with the period of time when the Microsoft Graph docs were being updated for the rebranding. So he grabbed that diagram before it got updated.

Hope that helps!

**Comment by PrasadKasireddy** [comment]
@angelgolfer-ms  - Thanks for your clarification
