### ISSUE TITLE
GET /users required Directory.Read permissions

### ISSUE THREAD

**Issue by Jan-Kruse** [microsoftgraph/microsoft-graph-docs#967]
Issue: 
GET /users requires Directory.Read permissions, User.Read.All does not work. A ticket at Microsoft is open under [REG:217031315445064001]. It is not clear if this is a bug in the API or in the documentation. They asked me to file the issue on GitHub.

Article:
https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list

**Comment by bobbyfu** [comment]
I ran in to the same issue.  There is no Directory.Read permission in the article - https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_list.   

I tried Directory.Read.All permission. and it fails, too.

**Comment by dkershaw10** [comment]
This was fixed as of end of April.  User.Read.All should allow read of all users both in application and delegated auth modes.
