### ISSUE TITLE
Error "Too Many requests"

### ISSUE THREAD

**Issue by cconrado** [microsoftgraph/microsoft-graph-docs#9691]
The command worked but I couldn't run it again. The error I got was too many requests. I only ran it once though. So what is the lock out period and it should be added to the doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6f309c-e811-bb9a-7b42-4a3547c2a810
* Version Independent ID: 0b8ae903-0cee-8d85-9ce5-b0a2845f88a2
* Content: [sync action - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/intune-enrollment-windowsautopilotsettings-sync?view=graph-rest-beta)
* Content Source: [api-reference/beta/api/intune-enrollment-windowsautopilotsettings-sync.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/intune-enrollment-windowsautopilotsettings-sync.md)
* Product: **intune**
* Technology: **microsoft-graph**
* GitHub Login: @dougeby
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by triplanedave** [comment]
Currently the minimum interval between sync actions is 10 minutes.  We're looking to improve this timing.  If we do make any updates to reduce the minimum interval, we'll update the docs to indicate the new minimum interval.
