### ISSUE TITLE
Remove app from team Graph API not working

### ISSUE THREAD

**Issue by PavithraTamizh** [microsoftgraph/microsoft-graph-docs#9716]
I was trying to remove an app from a team using the Graph API, 
DELETE 'https://graph.microsoft.com/v1.0/teams/{team-id}/installedApps/{teamsApp-id}'
The 'teamsAppId' was retrieved from the Graph API:
GET 'https://graph.microsoft.com/v1.0/teams/{team-id}/installedApps?$expand=teamsAppDefinition'
But I am getting below the error:
Bad Request - 400

 "error": {
        "code": "BadRequest",
        "message": "Invalid id '0d820ec*-def*-429*-ada*-78056cde7c7*' provided.",
        "innerError": {
            "date": "2020-08-31T16:27:30",
            "request-id": "03166c0d-c7e1-40fc-889d-2619f4e0ab03"
        }
    }

Note: I am the global administrator and I have all the required permissions.
1. TeamsAppInstallation.ReadWriteForTeam.All
2. Group.ReadWrite.All
3. Directory.ReadWrite.All

Please provide a solution for this, Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bba976e2-af1b-a842-1e98-803ab493010d
* Version Independent ID: a545e300-5d46-3487-a9e2-dbc1647a520d
* Content: [Remove app from team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/teamsappinstallation-delete?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/teamsappinstallation-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/teamsappinstallation-delete.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VaraPrasad-MSFT** [comment]
@PavithraTamizh , 

Could you please try using the id as highlighted below screenshot instead of teamsAppId.

<img width="691" alt="remove" src="https://user-images.githubusercontent.com/67954779/91815523-62f63f00-ec52-11ea-82a7-02d95a159e87.PNG">

**Comment by PavithraTamizh** [comment]
@VaraPrasad-MSFT 

When I tried using the id that you have highlighted above screenshot, I am getting the below error.

![error](https://user-images.githubusercontent.com/30800883/91843408-53d3b900-ec73-11ea-9aec-72c1afe1c075.png)

**Comment by VaraPrasad-MSFT** [comment]
@PavithraTamizh , we are able to reproduce the issue and raised a bug . We do not have any ETA to share.

**Comment by Rao-Muneeb** [comment]
Hello all! @VaraPrasad-MSFT could you please share the update here regarding above issue??

**Comment by Mallipriya-MSFT** [comment]
Hi @Rao-Muneeb, The issue is resolved. We have teste it from our end and got it working. 
1. GET https://graph.microsoft.com/v1.0/teams/<team-id>/installedApps?$expand=teamsAppDefinition
2. Fetch the corresponding app-installation-id, not the the teams app id. 
3. DELETE https://graph.microsoft.com/v1.0/teams/<team-id>/installedApps/<app-installation-id>
![image](https://user-images.githubusercontent.com/73868678/109507291-952f0f00-7ac4-11eb-9698-48ad1a75318c.png)

Could you please try from your end and confirm on the same.

**Comment by Rao-Muneeb** [comment]
Hello @Mallipriya-MSFT, I really apologize for the late response as I was busy with another task and literally missed your response... Yes, the issue has been resolved... I tried to check the issue with user scope as well and it is also working fine... Thanks and really appreciate the efforts of the team...
