### ISSUE TITLE
Update application has wrong return type

### ISSUE THREAD

**Issue by pihai** [microsoftgraph/microsoft-graph-docs#9734]
In the methods table it is stated that "Update application" action has return type "application". However, if you follow the [link](https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=http) it says: `If successful, this method returns a 204 No Content response code and does not return anything in the response body.` The return type in the methods table should be *None*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f54172c8-c149-8002-b172-5d1d286177f0
* Version Independent ID: c23c0d2f-5f70-e67d-9068-99e660126fd0
* Content: [application resource type - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/resources/application.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/application.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @sureshja
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you for catching this @pihai . Will propose a fix and close the issue.
