### ISSUE TITLE
Microsoft graph api insights/used?$orderby=LastUsed/LastAccessedDateTime is not returning last accessed files correctly

### ISSUE THREAD

**Issue by dawid1** [microsoftgraph/microsoft-graph-docs#9797]
I want to list all accessed files by a user. According to Microsoft specification https://docs.microsoft.com/en-us/graph/api/insights-list-used?view=graph-rest-1.0&tabs=http#example-2-return-the-most-recently-viewed-documents-that-the-signed-in-user-might-or-might-not-have-modified I should be able to do that by using the link above.

It works fine until I open Microsoft Edge with a new tab. After that it returns also recomended files which I have not opened

Does anyone have any idea why after opening Microsoft Edge with a new tab of Microsoft Office, graph api insights/used?$orderby=LastUsed/LastAccessedDateTime returns documents which were listed as recomended (in Microsoft Edge tab) and I haven't opened them at the date which is returned by insights/used.

Does anyone know how can I invoke from .net core web api https://ocws.officeapps.live.com/ocs/v2/recent/docs?apps=Word,Excel,PowerPoint,Visio,OneNote,Sway,PdfViewer&show=${count}&sort=Date which seems to return better results then graph api insights/used

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4807275-0aa5-9ae6-09c4-43aa35ca933d
* Version Independent ID: 5529441d-5ef3-6f7e-4885-751bb93a7658
* Content: [List used - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/insights-list-used?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/insights-list-used.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/insights-list-used.md)
* Product: **insights**
* Technology: **microsoft-graph**
* GitHub Login: @simonhult
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by simonhult** [comment]
Where the Recent API returns the list of documents that you have recently **opened** in a compatible client, the Used API leverages multiple other signals available from within the Microsoft Graph to build a list of documents **used**. The former is much more strict in its definition, which leads to you more easily recognizing its content. The reason that the Used API is influenced by opening a new tab in Edge, is due to the size of the document previews used in that application. When previews pass a certain threshold, we consider the documents as **used**. In this case, it is not deliberate, and I will make sure that we tweak our models to not catch these previews in the future.

Thank you for notifying us, dawid1.

**Comment by dawid1** [comment]
Thank you Simon for your response.
Could you advise what api should I use to present accessed files for a particular date. Used API only shows latest and as you already mentioned not realy corectly because of previews. Recent api seems to be more reliable but it is not documented and I don't know how to get access token in order to be able to invoke it. Could you advise please.

**Comment by simonhult** [comment]
For the record; the Used API is **not** by-design incorrect. We are leveraging as much information as we can within Microsoft Graph to give you the most precise list of content that you have engaged with. I have already started a follow-up internally to remedy the root-cause of the Edge issue that you reported.
 
If you still want to use the Recent API, could I ask that you open a separate ticket on your challenges with that? This will allow our automated system pick up and assign the issue to the rightful owner on our end.

**Comment by petevb** [comment]
>  I will make sure that we tweak our models to not catch these previews in the future.

Thanks @simonhult.  Is there an issue that we can follow (or ideally link to this one) to track that work please?

**Comment by simonhult** [comment]
I will make sure to have this thread notified as soon as the work is complete.

**Comment by dawid1** [comment]
Thank you Simon
