### ISSUE TITLE
Activating Azure Ad PIM role using graph api.

### ISSUE THREAD

**Issue by Ashok103606** [microsoftgraph/microsoft-graph-docs#9816]
I have a quick question regarding the graph api.

In Azure Active directory , My user account assigned to a PIM azure ad role which is called Application administrator. The role is a permeant assignment to my user account. However, I need to activate it whenever I need it and my tenant settings are in such a way that the maximum activation period is 4 hours. 

My requirement is I would like to activate this role using graph api, so could you please tell what graph api I have to use, what should body(load) for that api.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c8925b-bf52-c385-b2f0-cace73234560
* Version Independent ID: 31800dc3-4297-831e-3d9e-688e444d8fd7
* Content: [governanceRoleAssignmentRequest resource type - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/resources/governanceroleassignmentrequest?view=graph-rest-beta)
* Content Source: [api-reference/beta/resources/governanceroleassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/resources/governanceroleassignmentrequest.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @shauliu
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Ashok103606** [comment]
Forgot to say, our tenant using AAD roles, and we have ticketing rule and ticking system enabled.
 
Thank you,

**Comment by Ashok103606** [comment]
I have tried the following ways and it gave the respective errors.
Powershell:
$schedule = New-Object Microsoft.Open.MSGraph.Model.AzureADMSPrivilegedSchedule
$schedule.Type = "Once"
$schedule.StartDateTime = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ss.fffZ")
$4hours=New-TimeSpan -Hours 4 
$schedule.endDateTime = $schedule.StartDateTime+$4hours

$role_activation=Open-AzureADMSPrivilegedRoleAssignmentRequest -ProviderId 'aadRoles' -ResourceId 'Directoryid(Tenantid)' -RoleDefinitionId 'roleid’ -SubjectId ‘<userid(subjected)' -Type 'UserAdd' -AssignmentState 'Active' -schedule $schedule -reason "powershell testing" 

Error:
Open-AzureADMSPrivilegedRoleAssignmentRequest : Error occurred while executing OpenAzureADMSPrivilegedRoleAssignmentRequest 
Code: RoleAssignmentRequestPolicyValidationFailed
Message: The following policy rules failed: ["TicketingRule"]
InnerError:
  RequestId: fed89fcc-b8f6-4265-afa9-dfbcfa20c429
  DateTimeStamp: Fri, 04 Sep 2020 02:50:35 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At line:10 char:18
+ ... _activation=Open-AzureADMSPrivilegedRoleAssignmentRequest -ProviderId ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Open-AzureADMSP...signmentRequest], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.OpenAzureADMSPrivilegedRoleAssignmentRequest 

I didn’t know hoe to pass that ticketing rule parameter in the call. Could you tell me is there a way to do that.

Graph API call:

def pimroleactivation():
    pimrole_url = 'https://graph.microsoft.com/beta/privilegedAccess/aadRoles/roleAssignmentRequests'
    expiration_time = str(datetime.datetime.now() + datetime.timedelta(hours=4))
    pim_data = {
    "roleDefinitionId": "roleid",
    "resourceId": "tenanted(Directoryid)",
    "subjectId": "userid(subjectid)",
    "assignmentState": "activate",
    "type": "UserAdd",
    "reason": "business reason",
    "schedule": {
        "type": "Once",
        "startDateTime": datetime.datetime.now(),
        "endDateTime": expiration_time
    }
    }
    pimrole_response = requests.post(pimrole_url, headers=headers, data=json.dumps(pim_data, default=str), verify=False)
    return pimrole_response.status_code, pimrole_response.text

Error:
		0
0	"b'{\r\n  ""error"": {\r\n    ""code"": ""InvalidRoleAssignmentRequest"",\r\n    ""message"": ""The role assignment request is invalid."",\r\n    ""in'"
1	"b'nerError"": {\r\n      ""date"": ""2020-09-07T23:49:47"",\r\n      ""request-id"": ""123456789""\r\n    }\r\n  }\r\n}'"

**Comment by filipne** [comment]
HI, 

I have executed the same Powershell line but got a slightly different error:
Open-AzureADMSPrivilegedRoleAssignmentRequest : Error occurred while executing OpenAzureADMSPrivilegedRoleAssignmentRequest
Code: InvalidRoleAssignmentRequest
Message: The role assignment request is invalid.
InnerError:
  RequestId: c81cb4da-c558-4b83-8802-bcfcabd0efe1
 HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed

**Comment by FaithOmbongi** [comment]
Hello @Ashok103606 ,

Thank you for your query. Unfortunately this forum isn't monitored for functionality issues, but questions like this are monitored at [Microsoft Support](https://docs.microsoft.com/en-us/answers/search.html?type=question&q=microsoft-graph-*). Please ask your question there. No immediate change identified for the page, but the page will be updated when possible. Closing this issue for now.
