### ISSUE TITLE
Invalid bind property name owners in request.

### ISSUE THREAD

**Issue by pawelma8** [microsoftgraph/microsoft-graph-docs#9818]
Hi! 
When using this method I'm getting an error:
"error": {
    "code": "BadRequest",
    "message": "Invalid bind property name owners in request.",

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14650eac-eef3-e892-50ee-85e4692d21e9
* Version Independent ID: c7aeea07-12b6-45c9-8fb9-f942974811fa
* Content: [Create a team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0)
* Content Source: [api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-post.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by VaraPrasad-MSFT** [comment]
@pawelma8 , Thanks for reaching out ,we are checking internally and get back to you on this.

**Comment by VaraPrasad-MSFT** [comment]
Try using this payload:

{
"template@odata.bind":"https://graph.microsoft.com/v1.0/teamsTemplates('standard')",
"displayName":"My Sample Team",
"description":"My Sample Team’s Description",
"members":[
{
"@odata.type":"#microsoft.graph.aadUserConversationMember",
"roles":[
"owner"
],
"user@odata.bind":"https://graph.microsoft.com/beta/users('userId')"
}
]
}

**Comment by Nikitha-MSFT** [comment]
Please feel free to reopen the issue if issue still persists.
