### ISSUE TITLE
Email Address of the Channels Come Empty when GET request is sent

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#9828]
[
Request :GET:
https://graph.microsoft.com/v1.0/teams/blaId/channels/blablaId?$select=email

Response
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#teams('blaTeamId')/channels(email)/$entity",
    "email": ""
}

I needed a email address of that channel via graph api if possible. Is this a bug ? Documentation says readOnly but I am doing get request that is read right ? Please help. Thank you advance
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 029bd002-71ee-4ec1-25fe-398edd59070a
* Version Independent ID: 981d73a8-2fe7-a0de-14d5-9ef161770c16
* Content: [Get channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
We are not able to reproduce the issue at our end
![image](https://user-images.githubusercontent.com/61688740/92721167-4610e880-f383-11ea-828b-3c54666a37cf.png)

Could you please share screen shot of the issue?

**Comment by ashoksubedi1** [comment]
I did send the screen shot of the issue up there on my initial post. email field is just coming empty for every of our channel in the organization. We did hide the group in Outlook can that be a reason.

**Comment by Nikitha-MSFT** [comment]
Teams initially do not generate the email address for the channels created, the email address will be generated on demand.This is by design. Did you generate the email address for channel using UI? If no could you please generate a email address from the UI and then check from graph API?

**Comment by ashoksubedi1** [comment]
From UI I can always generate, I was hoping to get email via graph without triggering or producing from UI. 
I guess that is not possible. If I am getting from UI anyways, getting it later using graph api does not go along with my logic.
Thanks anyways.
