### ISSUE TITLE
Call transfer to resource account from another resource account of Bot

### ISSUE THREAD

**Issue by bijaykush** [microsoftgraph/microsoft-graph-docs#9853]
@VinodRavichandran @ksikorsk and anyone who can help on this.
Use case:

The bot answers the incoming call from PSTN number into one resource account (object id: 1234) and looking to transfer the call to another resource account (object id: 5678)
```

       var values = new Dictionary<string, object>
                {
                    { "tenantId", tenantId },
                };

                InvitationParticipantInfo target = new InvitationParticipantInfo
                {
                    Identity = new IdentitySet
                    {
                        Application = new Identity
                        {
                            Id = "objectId",
                            DisplayName = "Resource Account 2",
                            AdditionalData = values,
                        },
                    },
                };
 await this.callingService.TransferCallAsync(tenantId, target, call.Id, scenarioId);
```

Expected Behavior: It should transfer the call to the 2nd resource account

Error: 

`Code: 7505 Message: Request authorization tenant mismatch. Inner error: AdditionalData: date: 2020-08-04T18:50:31 request-id: 780da2c3-21a0-4be1-8df9-644f63a8c010`

Any help would be appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 335dc162-8c2e-49dc-4419-9ef736ec8ba4
* Version Independent ID: b441332e-a653-e538-d9f0-c66739f9122a
* Content: [call: transfer - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-1.0&tabs=csharp)
* Content Source: [api-reference/v1.0/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/call-transfer.md)
* Product: **cloud-communications**
* Technology: **microsoft-graph**
* GitHub Login: @ananmishr
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Ravindra-MSFT** [comment]
Hi @bijaykush Could you please confirm whether you had registered this app for Single Tenant or Multi Tenant.

**Comment by dannygar** [comment]
Has it been ever resolved? I'm facing with the same issue. My bot is multi-tenant, so it shouldn't be a problem with the users from outside of the org joined and transferred to another group call. I'm getting this error in these two use cases:
1) the guest joins the call from the Teams client
2) The guest joins the call from a PSTN phone dial

Any insightful suggestions are welcome!

**Comment by jackry** [comment]
Transfer target can only be Teams user or PSTN number. Transfer to another application is not supported so far.
See the API doc: https://docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-1.0&tabs=http
Here is the info in the first note: _"Note: This is only supported if both the transferee and transfer target are Microsoft Teams users that belong to the same tenant. Transfer to PSTN number is supported only for application instance. "_
