### ISSUE TITLE
Need example with application/ipp payload

### ISSUE THREAD

**Issue by clanie** [microsoftgraph/microsoft-graph-docs#9878]
I'd very much like to see an example with an application/ipp payload on this page.

Also, the links to RFC-8011 link to the wrong sections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1786660a-149f-2ed8-087d-c87017a526a6
* Version Independent ID: 75e01f78-9c2c-7b8b-6cb6-9957e59cf8fb
* Content: [Update printer - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/printer-update?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/printer-update.md)
* Product: **universal-print**
* Technology: **microsoft-graph**
* GitHub Login: @braedenp-msft
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by braedenp-msft** [comment]
Hi @clanie,

Thanks for raising these issues! I'll get the RFC link fixed (it should point [here](https://tools.ietf.org/html/rfc8011#section-5.2)).

The required IPP payload is documented in the IPP specs, and it's hard to represent here. Is the IPP documentation sufficient, or is there some particular information it's lacking?

Thanks!
Braeden

**Comment by clanie** [comment]
Hi Braden

The IPP spec is probably great, I just don't understand it well enough to
make a successful request with IPP payload on the Update Printer endpoint.

Our payload is an updateOutputDeviceAttributes operation built using the
jipp java library, and what we get back is this:

{
  "error": {
    "code": "500",
    "message": "Additional data found after serialized IPP attribute group.
First byte of additional data: Reserved",
    "innerError": {
      "date": "2020-09-29T09:25:18",
      "request-id": "e103342b-96a3-44b0-adb2-f97b29dc3846",
      "client-request-id": "e103342b-96a3-44b0-adb2-f97b29dc3846"
    }
  }
}

I realize you cannot help debug my code, but an example of what could be
sent would really help, whatever format you use to describe it. One option
would be to use the textual format used by ipptool, since you already
recommend using that for testing here:
https://docs.microsoft.com/en-us/universal-print/hardware/universal-print-oem-faq
.
The file format is described here:
https://www.cups.org/doc/man-ipptoolfile.html.

Best regards
Claus Nielsen

Den fre. 25. sep. 2020 kl. 00.34 skrev Braeden Petruk [MSFT] <
notifications@github.com>:
