### ISSUE TITLE
Cannot add channel members and owners to a private channel in Teams

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/microsoft-graph-docs#9882]
Hello,
we created a private channel on behalf of a user as documented here: https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&tabs=http

The private channel is correctly provisioned and the owner of the private channel is shown correctly in MS Teams client.
![image](https://user-images.githubusercontent.com/18241305/92888493-a81a2e00-f415-11ea-89e7-61c8da932517.png)

We started adding the members using the add command and the graph rest api. We first execute the command without passing a role (I am removing the displaynames and e-mail from the output.

```
@odata.context : https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyMwMWI5M2UyNi04MzQ4LTQxNDYtYjM2ZS0wNWY0N2I1M2MzN2E=
roles          : {}
displayName    : 
userId         : 01b93e26-8348-4146-b36e-05f47b53c37a
email          : 

https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyNhZTQzNDE2My0wNjFlLTQxOTktOTE3Zi03MWIwNzQ3MDU2MDU=
roles          : {}
displayName    : 
userId         : ae434163-061e-4199-917f-71b074705605
email          : 

https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyM0NjI1ZjFlMC1hNDE4LTQ1MmEtYTc5Zi0zYzYyOTBjMzkzMzQ=
roles          : {}
displayName    : 
userId         : 4625f1e0-a418-452a-a79f-3c6290c39334
email          : 

https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyNmYzQ0M2ViMC0xYzQ5LTQ3YjctYWVhNC1iMzE1Nzk2ZjA1ZDc=
roles          : {}
displayName    : 
userId         : fc443eb0-1c49-47b7-aea4-b315796f05d7
email          : 

https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyNjMjJhOWRjNy0xODIwLTQwMTctOTRiOS05YWRkNTY0YmM2Yjg=
roles          : {}
displayName    : 
userId         : c22a9dc7-1820-4017-94b9-9add564bc6b8
email          : 

https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyNhNDY2ODA4MC0zMTMxLTRiMjMtYTI3Mi02MmVhYTY0ZjY4NTE=
roles          : {}
displayName    : 
userId         : a4668080-3131-4b23-a272-62eaa64f6851
email          : 
```

After the operation above we execute the same commands by passing the "owners" role instead. Please note that the owners below have already been added as members before. This is the output we receive from Graph (I am removing displayname and email address from the output).

```
@odata.context : https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyNhZTQzNDE2My0wNjFlLTQxOTktOTE3Zi03MWIwNzQ3MDU2MDU=
roles          : {owner}
displayName    : 
userId         : ae434163-061e-4199-917f-71b074705605
email          : 

@odata.context : https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyMwMWI5M2UyNi04MzQ4LTQxNDYtYjM2ZS0wNWY0N2I1M2MzN2E=
roles          : {owner}
displayName    : 
userId         : 01b93e26-8348-4146-b36e-05f47b53c37a
email          : 

@odata.context : https://graph.microsoft.com/beta/$metadata#teams('95c350ea-c91f-4af4-ab9d-9f30bef7130a')/channels('19%3A5fd5e5350eaa4d3d875777f9170343c3%40thread.t
                 acv2')/members/$entity
@odata.type    : #microsoft.graph.aadUserConversationMember
id             : MTk6NWZkNWU1MzUwZWFhNGQzZDg3NTc3N2Y5MTcwMzQzYzNAdGhyZWFkLnRhY3YyIyM0NjI1ZjFlMC1hNDE4LTQ1MmEtYTc5Zi0zYzYyOTBjMzkzMzQ=
roles          : {owner}
displayName    : 
userId         : 4625f1e0-a418-452a-a79f-3c6290c39334
email          : 
```

When calling the Graph API by returning the conversationmembers of this channel, I am getting the correct list of assigned permissions. 

On the other hand, we notice following issues in the Teams Client and SharePoint Online.
- The Teams client does not update the membership. This happens even after some time. The result remains as it was before when we provisioned the channel
![image](https://user-images.githubusercontent.com/18241305/92888493-a81a2e00-f415-11ea-89e7-61c8da932517.png)
- When looking at the SharePoint Online permissions, we can see that all members have been added correctly to the **Members** group of SharePoint. But the owners haven't been updated correctly. It is the same as it was before provisioning
![image](https://user-images.githubusercontent.com/18241305/92894375-ce8e9800-f41a-11ea-9842-7c97ae02089c.png)

At first glance it looks to me that the initial command to add members to the channel successfully adds the members in the members group of SharePoint Online. Teams, however, does not reflect the changes. On top of that, re-adding an existing member with an owner role will execute the necessary activities on Graph end, but does not update the SharePoint permissions.

How do we ensure that we can correctly add members and owners to a Microsoft Teams private channel?

What are your recommendations?

Thank you,
Patrick
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 497ad1e7-5a61-731f-e0e9-75b5cb9336c8
* Version Independent ID: 776a8387-3525-7289-51bd-1232f58d283a
* Content: [Add conversationMember - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conversationmember-add?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conversationmember-add.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by plamber** [comment]
We performed some additional tests and where able to identify these situations.

If you call POST "https://graph.microsoft.com/beta/teams/$teamId/channels/$channelId/members" of a conversational member without role and a couple of seconds after the same endpoint with the same member but with "owner" role, SharePoint messes up the permissions. The user is just in the members group and not in the owners group. 

If you call POST "https://graph.microsoft.com/beta/teams/$teamId/channels/$channelId/members" of a conversational member without a role and a 15-20 seconds later you call the PATCH operation promoting a member as a channel owner, SharePoint tracks the user in the members and owners group.

In both situations, the DELETE operation successfully removes the user from both SharePoint groups.

The Teams client is still not updating the membership.

**Comment by VaraPrasad-MSFT** [comment]
@plamber , we are checking internally and get back to you on this.

**Comment by VaraPrasad-MSFT** [comment]
@plamber , Could you please check now, we are able to add members to private channel and the same is reflecting under  Members.

**Comment by plamber** [comment]
@VaraPrasad-MSFT: we will perform some additional tests. Has something changed to the API or was it working like this also before? Just to understand what we need to look at during testing

**Comment by VaraPrasad-MSFT** [comment]
@plamber : Are you still facing the issue could you please confirm.

**Comment by plamber** [comment]
@VaraPrasad-MSFT: we will be able to perform the test beginning of next week and I will come back to you

**Comment by plamber** [comment]
Hello @VaraPrasad-MSFT,
we are still experiencing inconsistencies in this context. Now it seems to be also related with the private channel creation on-behalf of a user. The private channels created (hundreds) are not showing up in the teams client on the navigation bar. Even if the channel was created.

I am wondering if we should use the beta or v1.0 endpoint right now. We see that the operations run on both endpoints. But both endpoints seem to have issues when performed on a larger scale.

Thank you

**Comment by coupalm** [comment]
What is the outcome? I have the same issue. Members in the private channel are not showing in Teams but belongs to the SharePoint members group.

**Comment by coupalm** [comment]
Ok, after a couple of minutes, the private channel is showing the members. So it looks ok.
Thanks.
