### ISSUE TITLE
HTTP example should include PUT as per guidance and not PATCH

### ISSUE THREAD

**Issue by epressey** [microsoftgraph/microsoft-graph-docs#9913]
Discrepancy in example vs guidance: HTTP example should include PUT as per guidance and not PATCH. Using PATCH throws "unknown error".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f9451ef-56a7-3ad1-a4e6-5aea51f46b3a
* Version Independent ID: ce02ade0-c957-0cbf-fe27-27cb1e8af89f
* Content: [Update openShift - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/openshift-update?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/openshift-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/openshift-update.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @akumar39
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Prasad-MSFT** [comment]
The documentation needs to be updated.
```
PUT https://graph.microsoft.com/v1.0/teams/{id}/schedule/openShifts/OPNSHFT_577b75d2-a927-48c0-a5d1-dc984894e7b8
Content-type: application/json

{
"schedulingGroupId": "TAG_228940ed-ff84-4e25-b129-1b395cf78be0",
"sharedOpenShift": {
"notes": "Inventory Management",
"openSlotCount":5,
"displayName": "Field shift",
"startDateTime": "2018-10-04T00:58:45.340Z",
"endDateTime": "2018-10-04T09:50:45.332Z",
"theme": "white",
"activities": [
{
"isPaid": true,
"startDateTime": "2018-10-04T00:58:45.340Z",
"endDateTime": "2018-10-04T01:58:45.340Z",
"code": "",
"displayName": "Lunch"
}
]
},
"draftOpenShift": null
}
```

**Comment by v-chetsh** [comment]
Hello Doc Team,
Could you please update the contents for this issue.
