### ISSUE TITLE
Beta permissions already valid for v1.0 api

### ISSUE THREAD

**Issue by jeubank12** [microsoftgraph/microsoft-graph-docs#9931]
It appears that the permissions listed in the v1.0 api already are effective for this endpoint. With Team.ReadBasic.All I was able to access this endpoint with delegated permissions on a user that was a member of the team

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04dfdea1-2848-4462-1e78-3c08c7b4fc45
* Version Independent ID: f9c8bdce-c8b8-7c1d-8f4d-9ab841902c89
* Content: [Get team - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/team-get.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
We are able to repro it at our end
