### ISSUE TITLE
Referencing in the example a non existing method

### ISSUE THREAD

**Issue by verhasi** [microsoftgraph/microsoft-graph-docs#9932]
The example number 4 on this page states the messages("messageid") that returns IMessageRequestBuilder has a method name content(). Actually it does not exist in version 2.1.0. I tried to figure out if only the code generation failed or missed it and looked at the https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/openapi.yaml. I have not found any information relating to the content method at all. I suppose there is no replacement of it as the whole Microsoft Graph Java SDK is based on that the response content type is JSON. In this case, the response is bare MimeMessage.

Regards,
Istvan
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cade3fc-500a-db83-8c66-12d54c218356
* Version Independent ID: 8f7f5555-03be-01c8-f981-939f51aaeaa8
* Content: [Get message - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=java#example-4)
* Content Source: [api-reference/v1.0/api/message-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/message-get.md)
* Product: **outlook**
* Technology: **microsoft-graph**
* GitHub Login: @svpsiva
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by baywet** [comment]
Hi @verhasi 
Thanks for reaching out.
This was a temporary issue in the generation process for the SDK and it had been addressed. The method is available in 2.3.2.
You can follow the details here https://github.com/microsoftgraph/msgraph-sdk-java/issues/323
Closing
