### ISSUE TITLE
Like break required in POST example

### ISSUE THREAD

**Issue by savoiebz** [microsoftgraph/microsoft-graph-docs#9936]
Please, add a line break at the URL exemple for the Token request exemple. 

As someone using a request library I tought the url was https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token HTTP/1.1 

I know it might be obvious, but if you consider the comment it implies it,s already proplery formatted. 

Might just be me but after googling, I guess i wasn't alone.

Thank you

```
// Line breaks are for legibility only. 
POST https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token{here} HTTP/1.1 
Host: login.microsoftonline.com 
Content-Type: application/x-www-form-urlencoded
client_id=535fb089-9ff3-47b6-9bfb-4f1264799865
&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default
&client_secret=qWgdYAmab0YSkuL1qKv5bPX
&grant_type=client_credentials
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38b3d5e6-46bc-11d2-214f-b9c4fa29c326
* Version Independent ID: ad6dd1cd-c08f-f447-ffd3-7a3473f169fb
* Content: [Get access without a user - Microsoft Graph](https://docs.microsoft.com/en-us/graph/auth-v2-service)
* Content Source: [concepts/auth-v2-service.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/concepts/auth-v2-service.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @Jackson-Woods
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by FaithOmbongi** [comment]
Thank you @savoiebz for raising your issue. Unfortunately, this is the universal standard for defining wire compatibility. In this case,  HTTP/1.1 protocol version instead of, for example, HTTP/2.

No updates identified for the page. Closing this issue.

**Comment by savoiebz** [comment]
Shouldn't you keep the idea of love breaks for legibility? If not then you should remove the comment all together.

Only doing half love breaks for readability only makes it worst since people would expect then to be there.

I think it's fine to keep HTTP/1.1 just have it on its own line for clarity. The way it currently is written it makes it seems like it is part big the URL.
