### ISSUE TITLE
OneDrive DriveItems Username Inconsistency

### ISSUE THREAD

**Issue by drewpc** [microsoftgraph/microsoft-graph-docs#995]
Issue:
There was an undocumented change in the DriveItems API behavior that is causing 404 errors now.  Previously, when using the username from the `webUrl` of a drive item, the Graph API would respond with the drive item details.  Now, you need to specify the actual username, not the `webUrl`-safe version of the username.

Using a modified version of the example in the below referenced article, if you requested a drive item and specify the domain and username, this used to work:

Request:
```
GET https://graph.microsoft.com/v1.0/contoso.com/users/rgregg_contoso_com/drive/root
```

Response:
```
HTTP/1.1 200 OK
Content-type: application/json

{
  "createdBy": {
      "user": {
          "id": "efee1b77-fb3b-4f65-99d6-274c11914d12",
          "displayName": "Ryan Gregg"
      }
  },
  "createdDateTime": "2016-03-21T20:01:37Z",
  "cTag": "\"c:{86EB4C8E-D20D-46B9-AD41-23B8868DDA8A},0\"",
  "eTag": "\"{86EB4C8E-D20D-46B9-AD41-23B8868DDA8A},1\"",
  "folder": { "childCount": 120 },
  "id": "01NKDM7HMOJTVYMDOSXFDK2QJDXCDI3WUK",
  "lastModifiedBy": {
      "user": {
          "id": "efee1b77-fb3b-4f65-99d6-274c11914d12",
          "displayName": "Ryan Gregg"
      }
  },
  "lastModifiedDateTime": "2016-03-21T20:01:37Z",
  "name": "OneDrive",
  "root": { },
  "size": 157286400,
  "webUrl": "https://contoso-my.sharepoint.com/personal/rgregg_contoso_com/Documents"
}
```

Note that the username `rgregg_contoso_com` is the same in both the request and the response `webUrl` value.

Since the undocumented change, this now returns the following error:

```
client-request-id: 9be11192-d76b-4431-abb5-cc77d7e62d4a
content-type: application/json
cache-control: private
request-id: 9be11192-d76b-4431-abb5-cc77d7e62d4a
Status Code: 404
{
    "error": {
        "code": "ResourceNotFound",
        "message": "User not found",
        "innerError": {
            "request-id": "9be11192-d76b-4431-abb5-cc77d7e62d4a",
            "date": "2017-03-24T20:14:33"
        }
    }
}
```

If I change the username in the request from `rgregg_contoso_com` to `rgregg@contoso.com`, the request succeeds again.  Please document this change and/or allow the `webUrl` version of the username to work again.

Article: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/item_get

**Comment by isvargasmsft** [comment]
Hello, 

Our sincere apologies for the delays in our response. 

We have updated the API and the documentation several times since this issue was opened. Today, the API supports calling a user by the ID or the userPrincipalName, as stated in the documentation. In the case of navigating to the user's drive, please use the user ID.

Closing this issue as the answer was provided. Please ask any future questions about Microsoft Graph at [Microsoft Q&A: Ask a Question - Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/ask.html).
