### ISSUE TITLE
Typo in the JSON request on Example 1 Create conditionalAccressPolicy

### ISSUE THREAD

**Issue by autohub7** [microsoftgraph/microsoft-graph-docs#9950]
I resolved a JSON format error after removing the common(,) after the closing square bracket on Example 1. 
"includeGroups": ["ba8e7ded-8b0f-4836-ba06-8ff1ecc5c8ba"],

```
POST https://graph.microsoft.com/beta/identity/conditionalAccess/policies
Content-type: application/json

{
    "displayName": "Access to EXO requires MFA",
    "state": "enabled",
    "conditions": {
        "clientAppTypes": [
            "mobileAppsAndDesktopClients",
            "browser"
        ],
        "applications": {
            "includeApplications": [
                "00000002-0000-0ff1-ce00-000000000000"
            ]
        },
        "users": {
            "includeGroups": ["ba8e7ded-8b0f-4836-ba06-8ff1ecc5c8ba"],
        },
        "locations": {
            "includeLocations": [
                "All"
            ],
            "excludeLocations": [
                "AllTrusted"
            ]
        }
    },
    "grantControls": {
        "operator": "OR",
        "builtInControls": [
            "mfa"
        ]
    }
}

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1052ee37-5a9e-d36d-2767-a39cdbd5a4df
* Version Independent ID: 10b8d865-1b5b-732f-70c9-a75ea83ce15b
* Content: [Create conditionalAccessPolicy - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/conditionalaccessroot-post-policies.md)
* Product: **microsoft-identity-platform**
* Technology: **microsoft-graph**
* GitHub Login: @videor
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by autohub7** [comment]
I found the same type of error in the example 2 and 4 on the same page

**Comment by JarbasHorst** [comment]
Hello @autohub7

thanks for reporting this issue. I've authored a pull request, whenever it gets merged it'll close this issue!

Regards
Jarbas
