### ISSUE TITLE
Undocumented error when using channel-list-messages on an empty channel

### ISSUE THREAD

**Issue by Hannesfornell** [microsoftgraph/microsoft-graph-docs#9960]
When fetching messages from an empty channel it a HTTP error 403 (forbidden) is thrown. Since there is no way to check beforehand if a channel is empty this issue might create some headaches. I doubt it is intended but if it is; then maybe the docs should reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bea46ed-94e0-6648-0293-8c50639ab4d7
* Version Independent ID: 139a2723-2b4b-21a2-a11b-ff5a77a61d42
* Content: [List channel messages - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/channel-list-messages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/channel-list-messages.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @nkramer
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by Nikitha-MSFT** [comment]
We are not repro duce the issue at our end. When you are fetching messages from the empty channel you will receive response as below
```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#teams('90baabba-1b5e-471c-a163-8a9b4b680de7')/channels('19%3A01c741f599e547f0b9b38296283b7fec%40thread.skype')/messages",
    "@odata.count": 0,
    "value": []
}
```
Could you please check the permissions required?

**Comment by Hannesfornell** [comment]
That it could be a permissions problem struck me as well. Therefor I went into Azure Active Director/appregistration/myApp/API Permissions and added all the permissions to rule that out. I am using delegated permissions and my scope object looks like this: 

scopes: [
      "user.read.all",
      "user.read",
      "group.read.all",
      "group.readWrite.all",
      "ChannelMessage.Read.All",
      "Channel.ReadBasic.All",
      "Channel.Create",
      "Channel.Delete.All",
      "Directory.ReadWrite.All",
      "ChannelSettings.Read.All",
      "ChannelSettings.ReadWrite.All",
      "ChannelMember.Read.All",
      "ChannelMember.ReadWrite.All",
      "GroupMember.ReadWrite.All",
      "Member.Read.Hidden",
      "Team.ReadBasic.All",
      "TeamSettings.ReadWrite.All",
      "TeamsActivity.Read",
      "TeamMember.ReadWrite.All",
    ]

Most notably I have got the ChannelMessage.Read.All, Group.Read.All, Group.ReadWrite.All permissions that is mentioned in the documentation. The thing that struck me as weird was that I had no problems getting a proper response object from a Team whose channels where not empty.

**Comment by Nikitha-MSFT** [comment]
Could you please share response body what you are getting?

**Comment by Hannesfornell** [comment]
Of course!

While looking into it I found that the response body was as it was supposed to, so I was mistaken.
```
{  
"@odata.context": "https://graph.microsoft.com/beta/$metadata#teams('90baabba-1b5e-471c-a163-8a9b4b680de7')/channels('19%3A01c741f599e547f0b9b38296283b7fec%40thread.skype')/messages",
"@odata.count": 0,
"value": [] 
} 
```

The problem is that in when I look in  Google Chrome > Dev tools > Console, the fetch still displays the error:
 `GET https://graph.microsoft.com/beta/teams/4f460179-4691-42e5-8677-9101dcdb65fe/channels/19:3497f5b8f9f54149919631b32d21e608@thread.tacv2/messages 403 (Forbidden) `

And when I console log the error it just displays as:

  `error: {code: "Forbidden", message: "Forbidden", innerError: {…}} `

**Comment by Nikitha-MSFT** [comment]
Could you please share the client request id?

**Comment by Hannesfornell** [comment]
Of course
"client-request-id": "cbd652a3-178d-45e0-9b85-0c00ea7f17d5"

**Comment by Nikitha-MSFT** [comment]
@Hannesfornell Is user part of the team? Could you please conform?

**Comment by Hannesfornell** [comment]
@Nikitha-MSFT I looked into this and it turns out that the error only shows up when the user is not a member of the team. But the user is a Global Administrator, shouldn't he also have access? Or is there another role that automatically (I.E that is not a member of the team) has access?

**Comment by Nikitha-MSFT** [comment]
Only team members are allowed to read messages. Admins can do team management i.e. CRUD operations on teams, channels, tabs etc. They however cannot read messages. This is intentional and we do not have plans to change this in near future.
