### ISSUE TITLE
Example Request has no Body; what is that it is updating in Example Request. Please update the doc

### ISSUE THREAD

**Issue by ashoksubedi1** [microsoftgraph/microsoft-graph-docs#9968]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3fbf2fa-dd10-df16-13c6-6cc6426538ff
* Version Independent ID: 59ae05e6-df9d-b1c3-a080-c7c5134c7a43
* Content: [Patch channel - Microsoft Graph v1.0](https://docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&tabs=http)
* Content Source: [api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/channel-patch.md)
* Product: **microsoft-teams**
* Technology: **microsoft-graph**
* GitHub Login: @clearab
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by clearab** [comment]
The request body needs to be a `channel` object. Please see the section [Request Body](https://docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&tabs=http#request-body) for reference.
