### ISSUE TITLE
The $search examples do not work

### ISSUE THREAD

**Issue by geemang2000** [microsoftgraph/microsoft-graph-docs#9969]
I'm trying the $search examples and they do not constrain the results. Has something changed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae00a068-e08c-298b-9104-13b3f6e2d695
* Version Independent ID: 7f5744b6-6770-586e-217c-4b7ac7657051
* Content: [List users - Microsoft Graph beta](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-beta&tabs=http)
* Content Source: [api-reference/beta/api/user-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/beta/api/user-list.md)
* Product: **users**
* Technology: **microsoft-graph**
* GitHub Login: @krbain
* Microsoft Alias: **MSGraphDocsVteam**

**Comment by davidmu1** [comment]
The examples work for me. There are a couple possibilities. Did you make sure that the ConsistencyLevel header is set to eventual? The $count and $search parameters do not currently work for a B2C tenant. A note has been added stating this. No change identified for the page. Closing the issue. Please reopen with more specific information about issues on the page if necessary.
